### ISSUE TITLE
Shaders issue with Intangible

### ISSUE THREAD

**Issue by Jomik** [sp614x/optifine#10]
Hey,

Initially posted an issue to Intangible. http://minecraft.curseforge.com/projects/intangible/issues/59

Quote from Emoniph;
"With an empty hand, or the foci equipped, Intangible will use the Forge hand render event to render the hand with armor added. This approach uses exactly the vanilla methods to do this, just with the addition of adding the armor render. I can only assume that the shaders mod is replacing parts that are not expected to be used by other mods, hence the oddness when they are. Perhaps ping the OptiFine guys to take a look?"

Pinging you guys.

So I got this strange issue with my shaders when I added Intangible to my pack. Happens on both KUDA and SEUS shaders, most noticable on KUDA which is my favorite.
I'm running a few mods, but as soon as I remove Intangible, everything is fine and dandy, put Intangible back in, and I get this issue. I am not sure what sort of data you'd want...
 
I also tested with just OptiFine, Intangible and KUDA shaders, issue persists.
 
Disabling "FOG" from my shaders resolves the issue, partly. I don't have the annoying white overlay with the line, but... I also lose the fog effects, which are quite nice :)

Water is still messed up.
 
It seems like holding an item in my hand fixes the issue completely. Does Intangible add something with no item held in your hand?
 
 
Using Forge 1.8.9-11.15.1.1722
Mod List:

- Bagginses
- Better Foliage
- Biomes O' Plenty
- Cyanos Lootable Bodies
- Dynamic Surroundings
- Intangible
- Iron Chest
- JEI + JEI Addons + JER
- Open Computers
- OptiFine
- Packing Tape
- Parachute Mod
- Sound Filters
- Storage Drawers
- Thaumcraft 5 + Thaumic Infusion
- Version Checker
- Xaero's Minimap

http://i.imgur.com/LlWLP5v.jpg
http://i.imgur.com/vy00wG7.jpg

http://minecraft.curseforge.com/projects/intangible/issues/59

**Comment by Jomik** [comment]
https://github.com/sp614x/optifine/issues/9

**Comment by sp614x** [comment]
Also happens when the empty hand is not rendered (F1). It is not the hand rendering itself, but something else around it.
The shadow map is also broken: http://i.imgur.com/NgZwcGr.png
Looks like a wrong coordinate transformation.

**Comment by sp614x** [comment]
The Shaders use a 2-pass hand rendering which is combined with the composite and final rendering. 
The Intangibles mod uses custom hand rendering which does not have the Shaders patches included.
Currently the Forge onRenderHand event is not compatible with shaders.

**Comment by sp614x** [comment]
The Forge onRenderHand event is totally broken and should not exist, it replaces not only the hand rendering, but also: camera setup, screen overlays (underwater, fire, inside block, ...), hurt effects and view directions.
The custom hand rendering should only replace ItemRenderer.renderItemInFirstPerson() which renders the current item or empty hand.

**Comment by sp614x** [comment]
Updated preview OptiFine H4 for 1.8.9: [link](http://optifine.net/adloadx?f=preview_OptiFine_1.8.9_HD_U_H4_pre.jar)

- disabled ForgeHooksClient.renderFirstPersonHand() when shaders are active, not compatible

Custom hand rendering with Shaders will work when Forge adds a way to overwrite ItemRenderer.renderItemInFirstPerson() or ItemRenderer.func_178095_a().
