### ISSUE TITLE
Grass Grow Under Water

### ISSUE THREAD

**Issue by NintendoBest** [sp614x/optifine#1000]
I found the grass can start growing underwater (while using Optifine)
I don't think this was wished and if it was, then this doesn't look natural at all.

How to make this reproduce:
Optifine's version: (N/A: I don't know what is the oldest version that has this issue) (Currectly on 1.11.2 C3)
-Create a world, get to a place that has grass on edge of a ocean/river while there is dirt underwater.
-Then Set RandomTickSpeed faster to not waste time to see this issue happen.

*However i feel this should be keep for Swamp Biome because this is giving a nice looking for it.

**Comment by sp614x** [comment]
This is a side effect of Clear Water. 
The grass growing does not check if there is water above it, only the current skylight level.
With Clear Water ON more skylight can enter underwater and grass starts to grow.
To fix it disable Clear Water and the grass should slowly disappear.

**Comment by zombye** [comment]
1: If it is a side effect of Clear Water, it should be specified in the description of the option.
2: With Clear Water enabled, grass grows below water until the skylight level is around 7-8 (it seems to vary a little). When disabled, grass doesn't grow below water even if the skylight level is above 9.
3: Grass below water does not fully disappear after clear water has been disabled - if the light level is above 7-8, grass will not decay.

**Comment by sp614x** [comment]
Grass  checks the combined light of the blocks above it, here is the check: https://pastebin.com/azz0KvJ9
