### ISSUE TITLE
Confusion on how to make emissive textures work in game.

### ISSUE THREAD

**Issue by MisterQuiggly** [sp614x/optifine#1001]
Even after reading the part about emissive textures in your color.properties, I still don't understand:

- What folder it goes in

- what the properties file would look like

I got it to be full bright when in my hand or dropped on the floor, but I cannot figure out how to get it to change when placed. I also do not know how to edit the brightness of it.

**Comment by sp614x** [comment]
Each texture (blocks and items for now) can get a emissive overlay.
The overlay is located in the same folder as the main texture and has the same name as the main texture with added suffix as configured in color.properties.

Example:
- `assets/minecraft/textures/blocks/bedrock.png` - main texture
- `assets/minecraft/textures/blocks/bedrock_e.png` - emissive overlay
