### ISSUE TITLE
Emissive textures dont work on models with  "ambientocclusion": false.

### ISSUE THREAD

**Issue by Danchuc** [sp614x/optifine#1003]
I had to set "AO=false" on my raised rails since it looked ugly but now emissive textures don't work on it.

![2017-11-16_11 47 47](https://user-images.githubusercontent.com/22410902/32887372-fc7dbd28-cac3-11e7-901e-a92e5ae5c029.png)

**Comment by sp614x** [comment]
Updated preview C7
- fixed emissive textures for models with "ambientocclusion": false

The emissive texture configuation was moved to "assets/minecraft/optifine/emissive.properties": 
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/emissive.properties

![image](https://user-images.githubusercontent.com/16635441/32960087-0ba471ba-cbc4-11e7-93d8-9cc77457ad4c.png)
