### ISSUE TITLE
Add multiple textures to the same CEM model

### ISSUE THREAD

**Issue by mexbotdude** [sp614x/optifine#1005]
Lets say I have a CEM spider but I want to make them change their texture for different biomes, like snow, desert, jungle. The base model would be the same. Is that possible?

**Comment by sixfootblue** [comment]
This can already be done with the random/alternate mobs feature.
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/mob.properties

If your CEM mob uses multiple textures, or a different one altogether, that are specified in the .jem file:
1) Save your custom CEM textures in assets/minecraft/textures/entity/spider
2) Specify that file path in your .jem and/or .jpm files
3) Make a mob.properties file for each new texture following the naming scheme. (texturename.properties) and give it the same conditions as the base mob texture.
4) Create variants for each texture following the same naming and numbering scheme.

I haven't tested this randomized textures so I'm not sure if they'll stay linked, but this should definitely work for biome specific mobs.

**Comment by mexbotdude** [comment]
Oh thanks I could figure it out, but what about the texture change based on name? Is there any quick example for this case, I dont really understand that part in the mob.properties url

**Comment by KaiAF** [comment]
Since this is possible I am going to close this. If you want to ask for support regarding this, go to our Discord. https://optifine.net/discord.
