### ISSUE TITLE
enchanted item in hand

### ISSUE THREAD

**Issue by seema84** [sp614x/optifine#1011]
Since a long time i have a issue with enchanted (in right or left hand) items and no shader.

Picture: https://picload.org/view/drlgrpgi/2017-11-18_16.06.21.png.html

With internal shader option or other shader i dont have this bug. Only with shader "off" it will show.

**Comment by sp614x** [comment]
More details needed:
- OptiFine installed standalone or with Forge, other mods installed?
- F3 screenshot
- resource pack

**Comment by seema84** [comment]
- with forge
- F3 screen https://picload.org/view/drldlgwl/2017-11-19_19.57.24.png.html
- default

**Comment by sp614x** [comment]
OptiFine C6 for 1.12.2 is compatible with Forge #2493: 
http://optifine.net/changelog?f=OptiFine_1.12.2_HD_U_C6.jar
You are running with Forge #2531

**Comment by sp614x** [comment]
You could try the preview C7 for 1.12.2, it is compatible with Forge #2512

**Comment by seema84** [comment]
the preview build C7 for 1.12.2 works

**Comment by seema84** [comment]
in OptiFine C6  and Forge #2493 i have this bug too

**Comment by sp614x** [comment]
If preview C7 works correctly, then everything is OK.

**Comment by seema84** [comment]
its not completed fixed 
f3 screen: https://imgur.com/a/MYFbK
C7 and Forge #2549 dont work (changelog info is compatible with Forge #2549)

**Comment by sp614x** [comment]
Works for me:

![image](https://user-images.githubusercontent.com/16635441/33189352-26dece0c-d0a2-11e7-9c67-c03dfd53414b.png)

You have 6 additional mods installed, one of them may be conflicting with OptiFine.
Can you test without the other mods?

**Comment by seema84** [comment]
you're right its the "WorldEditCUI Mod" - thanks sp614x
