### ISSUE TITLE
Extend Clear Water to apply to GT6 Sea Water and Dirty Water

### ISSUE THREAD

**Issue by retep998** [sp614x/optifine#1016]
In GregTech 6, vanilla water is replaced by Sea Water and Dirty Water in oceans and swamps respectively, which have the unfortunate property of being completely opaque to light. It would be quite useful if Optifine could extend Clear Water to adjust the opacity of Sea Water and Dirty Water, the same way it does for vanilla water.

MC Version: 1.7.10

**Comment by sp614x** [comment]
The GregTech6 water blocks have a fixed transparency and it can't be changed.
