### ISSUE TITLE
Dynamic Lights doesn't work with LittleTiles

### ISSUE THREAD

**Issue by CreativeMD** [sp614x/optifine#1017]
Hey there,

LittleTiles uses a rather hacky way to hook into the render engine to save performance. So it's not a huge surprise that this issue occurs (LittleTiles blocks are not affected by dynamic light):
![](https://cdn.discordapp.com/attachments/276752435869908993/338421614876295168/2017-07-22_16.46.20.png)

So how does this system work and is there a way to solve this somehow?

In Regards
CreativeMD

**Comment by sp614x** [comment]
RenderChunk uses a proxy ChunkCache which checks for dynamic lights:
```
public class ChunkCacheOF implements IBlockAccess
{
  private ChunkCache chunkCache;

  public ChunkCacheOF(ChunkCache chunkCache)
  {
    this.chunkCache = chunkCache;
  }

  @Override
  public int getCombinedLight(BlockPos pos, int lightValue)
  {
    int light = chunkCache.getCombinedLight(pos, lightValue);
    if(Config.isDynamicLights())
    {
      if(!getBlockState(pos).isOpaqueCube())
        light = DynamicLights.getCombinedLight(pos, light);
    }
    return light;
  }
  ...
}
  ```

**Comment by CreativeMD** [comment]
LittleTiles creates a VertexBuffer for each block and saves its rendering data. This will not be updated during each chunk update, but only if necessary. It looks like the issue appears because my blocks will not get notified.

I hooked into `IWorldEventListener` in order to update my blocks when the lighting changes:
https://github.com/CreativeMD/LittleTiles/blob/1.11.2/src/main/java/com/creativemd/littletiles/client/render/LightChangeEventListener.java#L30

So maybe you could implement some kind of notification system for dynamic lights? No idea, but i'm not able to solve this from my end.

**Comment by sp614x** [comment]
The `IWorldEventListener.notifyLightSet()` is called for real world light changes. It may trigger the relighting of the affected chunks which is quite expensive. The dynamic lights do not change the world light so OF can't call `IWorldEventListener.notifyLightSet()`. 

The moving dynamic lights generate a lot of chunk updates. If LittleTiles chunk updates are too expensive then it would have a problem with the amount of updates necessary for the dynamic lights.

**Comment by CreativeMD** [comment]
Maybe you can setup up an external hook for this? LittleTiles updates can be expensive, but this is not really important since it's threaded anyway.

**Comment by sp614x** [comment]
Danymic lights mark chunks for update like vanilla using "renderChunk.setNeedsUpdate(false)". This is the standard way to rebuild chunks.

**Comment by CreativeMD** [comment]
Okay, but LittleTiles does not rerender its stuff, if nothing has changed. Maybe you could move this call to a separate method, so i can hook into this via asm transforming. My suggestion:
```java
public void markRenderUpdateForDynamicLight(RenderChunk chunk)
{
    chunk.setNeedsUpdate(false);
}
```

**Comment by sp614x** [comment]
You can patch `DynamicLight.updateChunkLight()`
```
  /**
   */
  private void updateChunkLight(RenderChunk renderChunk, Set<BlockPos> setPrevPos, Set<BlockPos> setNewPos)
  {
    // Check null
    if(renderChunk == null)
      return;
    // Compiled chunk
    CompiledChunk compiledChunk = renderChunk.getCompiledChunk();
    // Update if not empty
    if(compiledChunk != null && !compiledChunk.isEmpty())
      renderChunk.setNeedsUpdate(false);
    // Position (immutable)
    BlockPos pos = renderChunk.getPosition().toImmutable();
    // Remove from old set
    if(setPrevPos != null)
      setPrevPos.remove(pos);
    // Add to new set
    if(setNewPos != null)
      setNewPos.add(pos);
  }
```

**Comment by CreativeMD** [comment]
Nice, thanks a lot!!! It is working now and i will release it soon.

https://github.com/CreativeMD/LittleTiles/blob/1.12/src/main/java/com/creativemd/littletiles/client/render/LittleChunkDispatcher.java#L42
https://github.com/CreativeMD/LittleTiles/blob/1.12/src/main/java/com/creativemd/littletiles/LittleTilesTransformer.java#L278

Again thank you very much for your help!!!
