### ISSUE TITLE
Allow for Custom Install Location in Installer

### ISSUE THREAD

**Issue by WolfLeader116** [sp614x/optifine#102]
I am using a little hack to trick my Minecraft launcher to install to a different location because I don't want any data other than the operating system on the main disk and I want my games on another disk. This means, however, that OptiFine's installer doesn't like to install... So please add some kind of custom install location option in the installer to make that installation easier than first running a normal launcher's game, installing OptiFine and then copying over the files to my main installation. Thank you!

**Comment by sp614x** [comment]
Added folder selection in latest preview B3 for 1.9.
