### ISSUE TITLE
Can't Run

### ISSUE THREAD

**Issue by AbductedSnake** [sp614x/optifine#1020]
I installed optifine 1.12.1, and I can't run.  Any help is greatly appreciated!  Thanks!
P.S. I'm new here, so sorry if I didn't do this right.

**Comment by sp614x** [comment]
Make sure that the OptiFine and Minecrat versions match.
For Minecraft 1.12.2 you need OptiFine for 1.12.2.

**Comment by AbductedSnake** [comment]
The Optifine version matches the Minecraft version perfectly, but I still cannot run.  Every other feature works perfectly, but I cannot run.

**Comment by sp614x** [comment]
Do you mean the game does not work or the player in the game can't run?
