### ISSUE TITLE
Custom lightmap blinking

### ISSUE THREAD

**Issue by CoolboyUA** [sp614x/optifine#1025]
I used template from images folder, but in game, screen randomly starts blinking.
https://www.youtube.com/watch?v=Dj02xS7POLw

**Comment by sp614x** [comment]
Resource pack link?

**Comment by CoolboyUA** [comment]
[Test.zip](https://github.com/sp614x/optifine/files/1509822/Test.zip)

**Comment by sp614x** [comment]
The template was scaled so it is easier to see.
The lightmap should have height either 32 or 64 pixel: https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/custom_lightmaps.txt#L41

Updated the template, fixed size and added nightvision.
