### ISSUE TITLE
Unable to re-activate programs.

### ISSUE THREAD

**Issue by VignetteCoeff** [sp614x/optifine#1026]
If I set a profile to have a specific program turned off, then I cannot re-activate it when using that profile as the base for my next profile. For example:
profile.low= !program.composite
profile.standard=profile.low program.composite

It will not re-activate the program for some reason.

**Comment by sp614x** [comment]
Updated preview C7 for 1.12.2
 - extended shaders configuration to re-enable program disabled in parent profile
