### ISSUE TITLE
Better Grass not working properly with Fancy Block Particles

### ISSUE THREAD

**Issue by TominoCZ** [sp614x/optifine#1027]
here's the original issue on my github project page: https://github.com/TominoCZ/FancyBlockParticles/issues/29

What my mod is doing is that it takes the IBakedModel of the block and makes a copy of it with changed positions of it's quads' vertexes (I'm rotating it).

Clearly there is something not right with the better grass model.

**Comment by sp614x** [comment]
BetterGrass is applied dynamically when rendering the block model. 
The block side quads are replaced with full grass quads depending on the neighbour blocks.
The quads are taken from replacement models in BetterGrass:
```
public class BetterGrass
{
  ...
  // Models
  private static IBakedModel modelCubeGrass = null;
  private static IBakedModel modelGrassPath = null;
  private static IBakedModel modelCubeGrassPath = null;
  private static IBakedModel modelCubeMycelium = null;
  private static IBakedModel modelCubePodzol = null;
  private static IBakedModel modelCubeSnow = null;
  private static boolean modelsLoaded = false;
  ...
```
Grass path has two models because the default model is not a full cube.
