### ISSUE TITLE
(Shaders) #elif preprocessor not recognizing options

### ISSUE THREAD

**Issue by BruceKnowsHow** [sp614x/optifine#103]
Only explicit #ifdef statements seem to trigger a setting as "in use," and therefore allow it to be visible on shaderpack menu screens. This makes it really troublesome to deal with some situations. Here's the example I'm dealing with at the moment:

https://github.com/BruceKnowsHow/Ebin-Shaders/blob/06e4b147dc1a28123d380c63abcf71c26a23c7d5/shaders/lib/ShadingFunctions.fsh#L151

In order to use an obvious #ifdef that would be detected, I would have to add another #else statement, and then it would get extremely confusing as to what code is in what block.

**Comment by sp614x** [comment]
Fixed in latest preview B3 for 1.9.
