### ISSUE TITLE
Issues with BlockModelRenderer#renderModel and optifine

### ISSUE THREAD

**Issue by Wyn-Price** [sp614x/optifine#1032]
Link to thread [here](https://github.com/AbrarSyed/SecretRoomsMod-forge/issues/204)

Whats going on is when i call BlockModelRenderer#renderModel ([here](https://github.com/AbrarSyed/SecretRoomsMod-forge/blob/master/src/main/java/com/wynprice/secretroomsmod/base/BaseTERender.java#L87-L115)) and Optifine Fancy textures are turned on, it renders the Minecraft original version, not the Optifine version. I dont think this could be a bug but if you could suggest a way to get around this it would be helpful.

**Comment by sp614x** [comment]
What are the Minecraft and OptiFine versions?

**Comment by Wyn-Price** [comment]
Minecraft 1.12.2
Optifine 1.12.2 HD U C6

**Comment by sp614x** [comment]
What do you mean with "it renders the Minecraft original version, not the Optifine version"?
How should the block look different?

**Comment by Wyn-Price** [comment]
Well when fancy textures is on blocks like smooth sandstone are textured depending on the block above it. In the thread I linked there's pictures explaining in more detail. I'll be able to make a video about it in around an hour

**Comment by sp614x** [comment]
You are calling "BlockModelRenderer.renderModel()" with the real block state, not with the mirror one. 
CTM connects the textures only when the block state matches the neighbour block states.

**Comment by Wyn-Price** [comment]
Ah yes of course I get it now. Ill mess around with my code an see if I can produce a fix. Sorry for wasting ur time
