### ISSUE TITLE
[Question] Why are minecart CEM models separated?

### ISSUE THREAD

**Issue by realjackasterisk** [sp614x/optifine#1039]
I'm working on a new minecart model for my resource pack. I was just looking at the docs and realized there are three separate models for these. `minecart`, `tnt_minecart`, and `spawner_minecart`. They all have the same parts, and when I applied my model to the other two, it worked just fine. Is there a reason for this?

**Comment by sp614x** [comment]
Internally the game uses different renderers for `minecart`, `tnt_minecart` and `spawner_minecart`. This allows them to use different models.
