### ISSUE TITLE
Permanent water texture when switching optifine version or adding shaders (using aqua tweaks)

### ISSUE THREAD

**Issue by lightning02** [sp614x/optifine#104]
Hello, I'm trying to use a very nice mod called aqua tweaks (http://minecraft.curseforge.com/projects/aquatweaks?page=2#comments) to make water more realistic ( this is client side only)
I noticed that this mod have some problem with optifine, even using Optifine_HD_U_D4.
If you place some object in water in your world and then you update Optifine and rejoin your world you'll notice that even removing the blocks you have put the water texture glitches it remain the same as it was when you was using the other version of Optifine.
This happen even by just only adding shaders.
The water textures of the blocks you've put in any water source remain visually glitched.
I'm not sure if i get the idea, my english isn't perfect, btw i have some screenshot that may help to understand the problem.

![5fed2b99b71adf53d255a0ea903609aa9b0f5bd646a5de3d6c pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/11884147/15121600/9c77e286-161b-11e6-9cf8-21428e24cb8c.png)
![c6ca4b0d4d4c97f9a4f2d914c82a393364a0ec99a2f61f0c0c pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/11884147/15121625/b3e797b8-161b-11e6-886a-667d5d4a707b.png)

[Edit: Is there also a way to delete Optifine local files? (this make could temporally fix the issue) ]

**Comment by sp614x** [comment]
You can set Chunk Loading to Default to fix it.

**Comment by lightning02** [comment]
Just to let you know, Chunk loading is already set on Default.
By the way I noticed that sometimes (not Always) the problem fixes itself by leaving and re-entering in the world, so I guess this isn't a serious issue, but still, I expected more willingness on your part instead of a rude response without even asking if I was already on default-chunk-loading and closing the issue liquidating me that way.

**Comment by sp614x** [comment]
For me setting Chunk Loading to anything other than Default immediately breaks the AquaTweaks water. Setting Chunk Loading to Default fixes AquaTweaks water and it works properly.

**Comment by lightning02** [comment]
If for example you place a fence in a 2x1 water source then you add shader mod core at that point logging again in your old world will results in a temporarly glitch of the water-flowing texture in the place where the fence was placed.
You can also reproduce it if you are updating your optifine version from (for example HD U D3 with the HD U D4).
Example: You create a single player world and put a fence or a ladder or whatever block that work with aqua tweaks in a source of water for example 2x1, and after you updated optifine and join that world again you'll see that the texture where defence was is now glithced.
Anyway as I stated before most of the times this glitch fixes itself when you log out and join again in the world, so it is not really a serious issue but i wanted let you know about it and i'm happy to see that you have considered this issue with more kindness.

**Comment by lightning02** [comment]
Well I guess I'm gonna close this small issue in favor of another one (more serious) with another mod that I discovered recently.
I want not make you lose time on the 'small things', thanks anyway :)
