### ISSUE TITLE
Shaders not working

### ISSUE THREAD

**Issue by UDPSendToFailed** [sp614x/optifine#1040]
Hi, i have some problems with shaders on Windows, but working fine on Linux. 

Windows:

![w1](https://user-images.githubusercontent.com/16057404/33480122-203d6a92-d690-11e7-8037-d69655de8c7b.png)
![w2](https://user-images.githubusercontent.com/16057404/33480123-2062d9e4-d690-11e7-8766-dc0cb5890cd6.png)
![w3](https://user-images.githubusercontent.com/16057404/33480124-20806022-d690-11e7-9eca-46a91ce304d1.png)

Linux:

![l1](https://user-images.githubusercontent.com/16057404/33480132-2f2fb348-d690-11e7-9af3-41bbfec14d9c.png)

Tried with many Java and driver versions, same problem.

**Comment by sp614x** [comment]
If the same OF version and shader pack work on Linux, but not on windows then this is a driver problem.
Intel graphics is generally problematic with shaders. Only a few shader packs are compatible with Intel graphics (Sildurs for example).

**Comment by sp614x** [comment]
I suppose this is Windows 10.
Intel HD 3000 is not supported by Intel on win10: https://downloadcenter.intel.com/product/81500/Intel-HD-Graphics-3000
Microsoft also does not support it on Win10: https://social.technet.microsoft.com/Forums/en-US/53e9decd-0870-4a26-a6c1-a2e526de65b6
The driver delivered by Microsoft only works in "legacy mode" and most probably does not have full OpenGL support.
