### ISSUE TITLE
Minecraft Server Resource Pack Won't Download

### ISSUE THREAD

**Issue by PaulHotel** [sp614x/optifine#1045]
Hi, 
I have a server resource pack which has a mcpatcher file in it. I have checked that the file is under 50 MB and that the link is valid but it still wont download. I think this has something to do with that mcpatcher file.

**Comment by sp614x** [comment]
Can you post the error log or game output?
Server address or RP link?

**Comment by PaulHotel** [comment]
Server ip is play.enderhotelmc.com
Resource pack link: http://download2146.mediafire.com/qd4kbp5wmpug/dnpxco97tx2r75i/EnderHotelMC.zip
