### ISSUE TITLE
Emissive item textures seem to be incompatible with Forge

### ISSUE THREAD

**Issue by realjackasterisk** [sp614x/optifine#1049]
I'm using the recommended version (#2555) that's compatible with Optifine 1.12.2 C7
I've also completely cleaned out my .minecraft folder just to make sure.
This is without running any other mods. I initially thought some other mod was causing the problem, but this occurs with or without them.

Log file here: https://pastebin.com/zBPwmRs4
Test resource pack: https://drive.google.com/open?id=1ARX-QHiRFisCY3NvcOCWUVxoI9wYaTvA

The pack works just fine in Optifine standalone. Trying to launch the game with the pack active will cause Forge to crash before even reaching the main menu.

**Comment by sp614x** [comment]
Fixed, please redownload C7 for 1.12.2.

**Comment by realjackasterisk** [comment]
Thanks for the quick fix!
