### ISSUE TITLE
No rendering for Items in hand

### ISSUE THREAD

**Issue by 0ctave** [sp614x/optifine#105]
I develop on Mcp 9.18, the version for minecraft 1.8.8, hand after I have add some Items/Blocks in game, I add with GameTweak of LaunchWarpper Optifine, and when I launch everything work, but the textures and models of added items/blocks are not rendering, have just the purple and black cube to replace the missing textures/models. It don't comes from me, I test without Optifine and all work.

**Comment by sp614x** [comment]
The tweaker and launch wrapper are used for starting the game not for modding. If you add the mod as a cusom library in the classpath then you are probably overwriting OptiFine or Forge classes and this may be the problem.
How are you adding the new items? Using Forge?

**Comment by octave33** [comment]
No, I add items in mcp like I said, sorry for my misexpression, that Optifine that I add using the tweaker, but my classes are added directly in the jar after reobfuscation. I don't use Forge for security problems

**Comment by sp614x** [comment]
What classes are you replacing in the JAR (MCP names)?

**Comment by 0ctave** [comment]
A lot I can't list all of them, the problematic is ItemRender in package client.render.entity

**Comment by sp614x** [comment]
The changes in ItemRender are only needed for Shaders.
I don't know how are you adding new models and textures without Forge. The models and textures have to be loaded in ModelBakery.setupModelRegistry() before the TextureMap sprites are initialized.

**Comment by 0ctave** [comment]
In a past release I modify it and it work, but now the patch in client jar are made with .class.xdelta I don't know how use this format, do you have a solution ?

**Comment by 0ctave** [comment]
I find a solution, I put after in the model map the custom items/blocks models, thank for your help

**Comment by sp614x** [comment]
You can get the patched classes by double clicking the OptiFine jar and selecting Export. The exported file has the class files inside. Modifying the OptiFine classes is not recommended as they can change with each release.
