### ISSUE TITLE
Underwater colormaps are completely non-functional with Forge

### ISSUE THREAD

**Issue by realjackasterisk** [sp614x/optifine#1050]
Works as it should with Optifine standalone, does nothing in Forge.

Log file: https://pastebin.com/z1taRkdi (not sure if its even useful in this case)
Test resource pack: https://drive.google.com/file/d/1IXzk9uId1yIw_wFlzM_AWRBdJrsW34AI/view
This should turn the underwater fog color to *~~an eye-burning bright~~* pink.

**Comment by sp614x** [comment]
The underwater and underlava colors are affected.

**Comment by sp614x** [comment]
Updated C7 and preview C8 for 1.12.2 with a bugfix.
