### ISSUE TITLE
Configurable entity render distance

### ISSUE THREAD

**Issue by kopftpista** [sp614x/optifine#1053]
I'm building a huge farm with over 3000 signs, and it causes a lot of lag even when hidden by other blocks. I read that this issue was fixed in Optifine (in an old 2013 thread), but in the newest build (Optifine HD C7 Ultra) it's still a problem.

**Comment by sp614x** [comment]
OptiFine optimizes the sign rendering by skipping the text on the signs which are too far to be readable. 
The signs itself still have to be rendered and with 3000 signs it is going to add some lag.

**Comment by kopftpista** [comment]
@sp614x thank you. Then this would be an enhancement: the signs don't take part in occlusion culling so would it be possible to make them use it? I mean they are rendered even when other blocks hide them.

**Comment by sp614x** [comment]
There is no occlusion culling in MC. There was occlusion culling up to 1.7.x (Advanced OpenGL), but it was removed as it was not very effective.
Currently MC uses another culling method which is mostly effective for underground structures (caves, ravines, etc). 
The game does not really render the models, their pixels are discarded in the depth test, but still sending 3000 models to the GPU just takes time that can't be avoided.
An option to limit the entity render distance could help, then the signs would not be visible after a certain distance.

**Comment by kopftpista** [comment]
@sp614x sounds good, will you add it? :)

**Comment by kopftpista** [comment]
Thanks!

**Comment by RedCriterion** [comment]
Asking this too, i need higher entity render distance for mobs and stuff

**Comment by ewanhowell5195** [comment]
Entity Distance is now a vanilla option in the video settings: https://minecraft.wiki/w/Options#Video_Settings
