### ISSUE TITLE
Hostile mobs not spawning with OptiFine 1.12.2 HD U C7

### ISSUE THREAD

**Issue by jazwec** [sp614x/optifine#1055]
Since I updated to this version, my gold and guardian farms stopped spawning mobs. Finding one out in the world is also incredibly rare. Everything goes back to normal if I turn Optifine off...

**Comment by sp614x** [comment]
Video Settings -> Performance -> Smooth World -> OFF ?

**Comment by jazwec** [comment]
Switched it ON and OFF a few times, no difference

**Comment by sp614x** [comment]
Running with Forge or standalone?
Forge version, other mods installed?

**Comment by jazwec** [comment]
Regular linux launcher, no mods

**Comment by sp614x** [comment]
Can you post the error log or game output?

**Comment by jazwec** [comment]
https://pastebin.com/MEjwwSQX

It may be because of the computer not keeping up, its an older laptop however this was not a problem until now...

**Comment by sp614x** [comment]
```
[15:47:31] [Server thread/INFO]: jazwec[local:E:f87cf06f] logged in with entity id 56 at (-60.46602440132358, 256.0, -25.038510209044375)
```
Are you above the maximum world height (256)?
Mobs don't spawn above Y=256.

**Comment by jazwec** [comment]
I'm definitely not...

**Comment by jazwec** [comment]
Oh I see what you mean, I was on mobile and didnt see the log. Im standing on the top of the gold farm in the nether...

**Comment by sp614x** [comment]
Can you post the world as ZIP file?

**Comment by jazwec** [comment]
I could, however if I create a new world from a random seed, the behaviour is the same. Everything goes back to normal in OptiFine 1.12.2 HD U C6

**Comment by fox86fox86** [comment]
I have had the same problem using OptiFine 1.12.2 HD U C7, no spawns in my guardian and goldfarms.
Using OptiFine 1.12.2 HD U C6 fixed this problem for me.

**Comment by sp614x** [comment]
I need a world with a mob farm which works with C6 and does not work with C7.

**Comment by jazwec** [comment]
Any preferred hosting?

**Comment by sp614x** [comment]
You can zip the world folder and paste it in the comment area, it will be uploaded to github.

**Comment by jazwec** [comment]
It says I can only upload files smaller than 10MB... The world is 170MB

**Comment by sp614x** [comment]
You can upload it to any hosting (MediaFire, RapidShare, ShareFile, Box, 2Shared, etc).

**Comment by jazwec** [comment]
http://www.mediafire.com/file/41u1qcqybupsu22/NoMobsSpawning.zip
Overworld Guardian Farm: -622 12 87
Nether Gold Farm: -73 250 -24

Thank you for looking into this and for all the great work you've done with the mod

**Comment by fortify45** [comment]
Just to add onto this post, I can report similar activity. However, instead of hostile mobs not completely spawning, they will only spawn slowly and in severely smaller groups. (I am using my enderman-mite farm in this case) 
The way they are spawning almost makes me think that their spawning (timings/limitations) was altered in some form or fashion.
Just so you are aware. This is on plain OptiFine 1.12.2 HD U C7 w/ no mods.
Even went as far as doing a clean wipe and reinstall with no success.
However, after reverting back to C6, the issue was resolved as if nothing happened.

And until the issue can be addressed, I'd say going back to C6 is your best bet.

**Comment by sp614x** [comment]
Found the problem, the limit per mob type was wrongly initialized.
Updated C7 for 1.12.2 with a bugfix, please download it again.
