### ISSUE TITLE
Relaxed OptiFine constant parsing.

### ISSUE THREAD

**Issue by VignetteCoeff** [sp614x/optifine#1056]
It would be better for OptiFine to look for the name and behaviour of something, instead of requiring `const <type>`

for example

`const int colortex0Format = RGB10_A2;`

would be replaced with

`colortex0Format = RGB10_A2;`

The same logic applies for other variables, shadow hardware filtering, buffer mipmapping, buffer clearing, etc.

I think that most shader-pack developers have started commenting these lines because OptiFine finds them when they're commented, which means we don't need to set a new constant variable for something, increasing shader compile time.

**Comment by sp614x** [comment]
Added in OptiFine 1.12.2_HD_U_C7.
