### ISSUE TITLE
Custom Mob Textures: Horses not changing textures

### ISSUE THREAD

**Issue by Jwguy0** [sp614x/optifine#1057]
https://github.com/sp614x/optifine/blob/7ec40de77ccfd7ae267f0899fa0c21c61c81b5df/OptiFineDoc/doc/mob.properties#L104

I've successfully used this feature for several other mobs, such as creating rat textures for silverfish named 'Rat' with gray colored text, and shark textures for guardians under similar circumstances, but for some reason, I'm unable to get horses to change textures based on their names.

I've attached the files I'm using; Also, I'm currently using C8_Pre Ultra. I have these files inside the resource pack within /assets/minecraft/mcpatcher/mob/. The horse folder is located there, with the properties and textures inside.
[horse.zip](https://github.com/sp614x/optifine/files/1544475/horse.zip)

**Comment by Jwguy0** [comment]
I've also tried with making individual properties files and textures for each type of horse variation, including the separate entities like the skeleton and zombie horse, but it does not seem to work with that method, either. Is there a special method when it comes to creatures with vanilla variations, such as horses and rabbits?

**Comment by sixfootblue** [comment]
Your naming scheme should follow the same names as the base horse textures in the entities folder. That being said, I can't get it work either. The only horse textures it looks like you can change with random mobs are the zombie and skeleton horses.

**Comment by Jwguy0** [comment]
If I could get the skeleton horse working, that'd be better than nothing. I figured the same thing you had mentioned, about getting them to match the base textures, while waiting for a response. Still, I can't even seem to get the skeleton horse to change textures. How did you manage?

I've attached my properties and texture.
[horse.zip](https://github.com/sp614x/optifine/files/1550156/horse.zip)

**Comment by Jwguy0** [comment]
Also, it does appear that horses specifically don't respond to the colored names, all that well, in regards to this. Seems like it works if I remove any and all color formatting codes, but otherwise it doesn't, even though they've worked with other mobs.

**Comment by sp614x** [comment]
OptiFine 1.12.2_HD_U_D2_pre
 - fixed horse random textures (#1357) 

The main horse textures should work, the markings are ignored.
