### ISSUE TITLE
 (Shaders) #elif preprocessor fix didn't fix the correct syntax

### ISSUE THREAD

**Issue by BruceKnowsHow** [sp614x/optifine#106]
It looks like you fixed the option scrubbing for statements of the form:
#elif PREPROCESSOR_NAME

This isn't how #elif syntax actually works, the above statement will throw an error. The correct syntax is:
#elif defined PREPROCESSOR_NAME

**Comment by BruceKnowsHow** [comment]
To be quite honest, if this is more than a little work for you, I can just workaround it by placing empty #ifdef blocks in the bottom of one of my #includes, not a big deal.

**Comment by sp614x** [comment]
Yep, the #elif detection is broken, reverting changes.

**Comment by BruceKnowsHow** [comment]
I hadn't realized how versatile the #if preprocessor was, I'll likely update a lot of my preprocessors to use it instead. Because the conditions it evaluates can be arranged in almost any order, it makes more sense at this point to just have an [initializer](https://github.com/BruceKnowsHow/Ebin-Shaders/blob/master/shaders/lib/MenuInitializer.glsl) than to try and sort out every syntax case of #if condition.
