### ISSUE TITLE
Problem with model [with nametag]

### ISSUE THREAD

**Issue by Axios932** [sp614x/optifine#1060]
I know that my problem comes from the texture, but which folder?
![2017-12-12_00 06 23](https://user-images.githubusercontent.com/34461743/33859975-cd2f82dc-ded6-11e7-9e79-a3f0896a220b.png)
![2017-12-12_00 05 51](https://user-images.githubusercontent.com/34461743/33859976-cd45d3e8-ded6-11e7-9620-9451012db26d.png)
if you have the solution, I would be grateful to you ^^

**Comment by sp614x** [comment]
Is the position of the name wrong?

**Comment by Axios932** [comment]
I would like to have the vanilla model and the other model I created will rename it
if you have the solution, here is the resource pack : 
[test_cerf.zip](https://github.com/sp614x/optifine/files/1551356/test_cerf.zip)

**Comment by IMerlin1009I** [comment]
I just have a question regarding the pictures :D...
Is it now possible to make custom models only for a specific name?
That would be awesome!

**Comment by sp614x** [comment]
@IMerlin1009I models depending on mob properties (name, etc) are currently not possible.
