### ISSUE TITLE
Custom startup logos (mojang.png) don't work with Forge

### ISSUE THREAD

**Issue by realjackasterisk** [sp614x/optifine#1061]
Works in standalone, not with Forge. No other mods.

**Comment by MisterQuiggly** [comment]
It might have a separate texture in the forge mod that you have to change as well.

**Comment by realjackasterisk** [comment]
Actually, that was the first thing I checked. I suspected it too, but all I could find was that animated anvil and some server icons.

**Comment by AlexIIL** [comment]
A while ago forge changed their splash loading code to never check resource packs, and only load from the minecraft jar file. Optifine would (probably) have to replace that loading code in order to override it, or replace forge's splash screen with its own.

**Comment by sp614x** [comment]
Forge uses a custom splash screen which is created very early before any resource packs are loaded. 

https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/fml/client/SplashProgress.java#L181

https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/fml/client/SplashProgress.java#L251

**Comment by sp614x** [comment]
The logo can only be fixed after the resource packs are initialized, so the original logo will appear for some time and then it will switch to the custom one.

The Forge splash screen is layed out to work with the original logo. Custom logos would not look good if not specifically made to work with Forge.

Vanilla logo:

![image](https://user-images.githubusercontent.com/16635441/34885472-62118fd8-f7c0-11e7-9744-e83642ff5711.png)

PureBDCraft logo:

![image](https://user-images.githubusercontent.com/16635441/34885500-7a8c5462-f7c0-11e7-9e5f-a7ca56d9c857.png)

**Comment by sp614x** [comment]
You can disable the Forge splash screen and then the custom logo would be shown.
To disable it set `enabled=false` in `config/splash.properties`.
