### ISSUE TITLE
Custom Sky for Nether and End dimensions.

### ISSUE THREAD

**Issue by CosmicjLightning** [sp614x/optifine#1065]
Sorry if in wrong spot, github still confuses me

Basically wanted to make an actual skybox in the nether and end by pictures and alsoable to do an opacity overlay of red color at 40% on all mobs

If not possible via optifine it's alright, if it's already possible can you point me in the right direction and lastly could you make it possible or do i need to use a mod instead? Thank you for reading.

**Comment by sp614x** [comment]
The nether does not have a sky, it has a bedrock ceiling. 
The end sky uses a special texture.
Currently only the overworld can use custom sky.

**Comment by CosmicjLightning** [comment]
There's still a sky above the bedrock. And was asking if you could but apparently can't. I'll go ask a modder instead of rude folk. Geesh.

**Comment by sp614x** [comment]
Currently it is not possible to have custom sky in the nether and the end. It may be added in the future. This is why the issue is marked "enhancement" and is still open. The issue would be closed when the feature is added or it is clear that it can't be implemented.
The response was meant to be informative, not rude.

**Comment by DaDodger** [comment]
Logically, a custom sky in the Nether is pretty useless since the dimension is like a locked cage, due to double void at the top and the bottom of world. Needless to say that playing above bedrock is meaningless as well.

**Comment by Miclebrick** [comment]
if it helps I managed to do this pretty easily with forge:
https://github.com/Miclebrick/StarForge/blob/master/src/main/java/net/starlegacy/starforge/StarForge.java#L42
https://github.com/Miclebrick/StarForge/blob/master/src/main/java/net/starlegacy/starforge/SpaceRenderHandler.java#L32

**Comment by ireece1** [comment]
At the same time it would be nice to have an option to enable custom skyboxes for dimensions other than the 3 vanilla ones.

Idk it doesn’t feel right to have gorgeous clouds in the overworld and then nothing in the twilight forest or lost cities dimension.

**Comment by Ratchet97** [comment]
After a long time since the first post I would like to ask if there has been some efforts in implementing this neat feature to OptiFine. Many resource pack creators including myself would be very pleased with this addition.

**Comment by MicleBrick** [comment]
If you can make forge mods, you can do something like I did on https://github.com/StarLegacy/SpaceCandy

You could also try modifying it, I think it's MIT licensed or something

**Comment by Yekul10** [comment]
Unloaded chunks in the nether sometimes shows the "sky." It would be nice to be able to make it look like fire or something. It might look weird with the fog colors though. Is it possible to have texture for the fog?

**Comment by JoshMerlino** [comment]
> Added custom sky for the end dimension (world1).

Can confirm this works for the end and looks great,

![2021-08-19_21 42 35](https://user-images.githubusercontent.com/31785395/130165886-4ade9648-7f1b-4476-943f-2be1a849314f.png)

**Comment by Yekul10** [comment]
> 
> 
> > Added custom sky for the end dimension (world1).
> 
> Can confirm this works for the end and looks great,
> 
> ![2021-08-19_21 42 35](https://user-images.githubusercontent.com/31785395/130165886-4ade9648-7f1b-4476-943f-2be1a849314f.png)

How did you get yours to work?

**Comment by JoshMerlino** [comment]
I downloaded [this resource pack](https://www.planetminecraft.com/texture-pack/milkyway-galaxy-night-sky/), went into the files and went to this folder `assets/minecraft/optifine/sky` and duplicated the `world0` folder to a `world1` folder. Also make sure your using the latest optifine preview version. I think mine was like pre34.

![image](https://user-images.githubusercontent.com/31785395/130232869-6c826aa7-c768-458e-8418-23c9eab97abc.png)

**Comment by UsernameGeri** [comment]
Skies in the Nether still don't work. Don't know if that's intentional or not, or if it's even possible to implement at all.

**Comment by CosmicjLightning** [comment]
It is if you follow this. But it might need directory changed for newest
optifine.

**Comment by CosmicjLightning** [comment]
You need to use a mod, either fabric mod or forge mod. Unfortunately the
only pheasible way...As minecrafts nether skybox does not have built in
support. Sorry.

Also no clue why I'm being asked for help, I just asked if it was possible
lol...

**Comment by UsernameGeri** [comment]
??
Didn't ask for help, simply shared my setup and said it's not working. 
> You need to use a mod
Uh ok, sure. But this is the Optifine github sooo.. Not sure why you would recommend other mods, especially fabric.

**Comment by CosmicjLightning** [comment]
Yes because I created the thread to ask for help doing the same thing. Also
I gave those as it's the only way. If you don't like that, then you'll need
to ask minecraft on feedback site for ability to change the nether skybox.
Optifine can't do it without mods...

**Comment by Arcanum7567** [comment]
> Logically, a custom sky in the Nether is pretty useless since the dimension is like a locked cage, due to double void at the top and the bottom of world. Needless to say that playing above bedrock is meaningless as well.

Using the nether roof for nether travel and hubs is extremely useful and common. It makes sense to want a Nether custom skybox mod for aesthetics while up there

**Comment by Emfire12345** [comment]
> > Logically, a custom sky in the Nether is pretty useless since the dimension is like a locked cage, due to double void at the top and the bottom of world. Needless to say that playing above bedrock is meaningless as well.
> 
> Using the nether roof for nether travel and hubs is extremely useful and common. It makes sense to want a Nether custom skybox mod for aesthetics while up there

I have an entire Oblivion inspired landscape up on the nether ceiling, waiting to add a red nightsky to it for ages

**Comment by Banishedddd** [comment]
Was this ever figured out, Im not trying to change the colour of the red, and all Ive found is "fog.nether=" in optifine color.properties but cant seem to make it work.

https://optifine.readthedocs.io/custom_colors.html
