### ISSUE TITLE
Game crashes when creating a new world OptiFine_1.12.2_HD_U_C8_pre

### ISSUE THREAD

**Issue by MisterQuiggly** [sp614x/optifine#1066]
When I create a new world, it crashes. When I try to join the world that was just created after restarting the game, it crashes, No resourcepack is loaded, no mods, only OptiFine_1.12.2_HD_U_C8_pre. Removing optifine fixes the problem. No problem joining pre-existing worlds.

**Comment by Dushess** [comment]
crashlog pls, nobody can help you without this info.

**Comment by MisterQuiggly** [comment]
https://paste.ee/p/WyQVB

**Comment by sp614x** [comment]
Updated preview C8 for 1.12.2 with a bugfix.
