### ISSUE TITLE
Forge 14.23.1.2577 crash with PlayerControllerOF

### ISSUE THREAD

**Issue by SteveKunG** [sp614x/optifine#1067]
See also : https://github.com/MinecraftForge/MinecraftForge/pull/4584

Crash Log :
---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Who set us up the TNT?

Time: 12/18/17 1:21 PM
Description: Unexpected error

java.lang.AbstractMethodError: net.minecraft.block.state.BlockStateContainer$StateImplementation.doesSideBlockChestOpening(Lnet/minecraft/world/IBlockAccess;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/util/EnumFacing;)Z
	at net.minecraft.block.BlockEnderChest.func_180639_a(BlockEnderChest.java:103)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:423)
	at PlayerControllerOF.func_187099_a(PlayerControllerOF.java:96)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1577)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2252)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2018)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1806)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.block.BlockEnderChest.func_180639_a(BlockEnderChest.java:103)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:423)
	at PlayerControllerOF.func_187099_a(PlayerControllerOF.java:96)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1577)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2252)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2018)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['MCCommanderz'/174, l='MpServer', x=349.67, y=66.00, z=277.57]]
	Chunk stats: MultiplayerChunkCache: 591, 591
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (284,64,227), Chunk: (at 12,4,3 in 17,14; contains blocks 272,0,224 to 287,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 8343 game time, 8343 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 67 total; [EntityZombie['Zombie'/128, l='MpServer', x=370.77, y=25.00, z=210.41], EntityZombie['Zombie'/129, l='MpServer', x=368.51, y=27.00, z=213.77], EntitySquid['Squid'/131, l='MpServer', x=375.52, y=62.53, z=314.84], EntitySquid['Squid'/132, l='MpServer', x=372.43, y=51.79, z=307.24], EntityCreeper['Creeper'/139, l='MpServer', x=397.50, y=24.00, z=216.50], EntityBat['Bat'/140, l='MpServer', x=391.45, y=20.10, z=265.75], EntityZombie['Zombie'/141, l='MpServer', x=395.50, y=16.00, z=298.50], EntitySquid['Squid'/142, l='MpServer', x=393.82, y=57.95, z=286.09], EntityCreeper['Creeper'/143, l='MpServer', x=393.84, y=35.00, z=331.50], EntitySquid['Squid'/144, l='MpServer', x=393.48, y=53.59, z=342.97], EntitySquid['Squid'/145, l='MpServer', x=393.90, y=55.86, z=341.24], EntityWitch['Witch'/147, l='MpServer', x=403.81, y=12.00, z=238.75], EntitySkeleton['Skeleton'/149, l='MpServer', x=406.50, y=36.00, z=256.74], EntityZombie['Zombie'/277, l='MpServer', x=331.50, y=22.00, z=227.50], EntityCreeper['Creeper'/150, l='MpServer', x=416.23, y=12.00, z=283.50], EntityBat['Bat'/151, l='MpServer', x=415.77, y=19.68, z=333.75], EntityCreeper['Creeper'/155, l='MpServer', x=418.50, y=13.00, z=284.30], EntityCreeper['Creeper'/156, l='MpServer', x=419.50, y=13.00, z=299.50], EntityBat['Bat'/158, l='MpServer', x=424.88, y=13.61, z=307.77], EntityZombie['Zombie'/160, l='MpServer', x=422.50, y=31.00, z=332.50], EntitySkeleton['Skeleton'/161, l='MpServer', x=423.50, y=31.00, z=332.50], EntityBat['Bat'/162, l='MpServer', x=422.66, y=19.11, z=326.48], EntitySkeleton['Skeleton'/163, l='MpServer', x=423.58, y=25.00, z=332.50], EntitySkeleton['Skeleton'/175, l='MpServer', x=289.50, y=19.00, z=315.50], EntitySpider['Spider'/176, l='MpServer', x=384.50, y=15.00, z=283.50], EntityZombie['Zombie'/177, l='MpServer', x=394.50, y=17.00, z=275.50], EntityPlayerSP['MCCommanderz'/174, l='MpServer', x=349.67, y=66.00, z=277.57], EntityPig['Pig'/58, l='MpServer', x=266.67, y=90.00, z=283.90], EntityPig['Pig'/60, l='MpServer', x=267.07, y=80.00, z=293.79], EntityZombie['Zombie'/61, l='MpServer', x=269.50, y=24.00, z=315.50], EntityBat['Bat'/69, l='MpServer', x=275.54, y=23.34, z=316.57], EntityZombie['Zombie'/70, l='MpServer', x=286.50, y=18.00, z=312.50], EntityZombie['Zombie'/71, l='MpServer', x=287.50, y=18.00, z=313.50], EntityCreeper['Creeper'/72, l='MpServer', x=284.48, y=38.00, z=318.80], EntityCreeper['Creeper'/77, l='MpServer', x=299.50, y=22.00, z=219.81], EntitySquid['Squid'/78, l='MpServer', x=300.19, y=57.31, z=278.35], EntitySquid['Squid'/79, l='MpServer', x=304.15, y=59.01, z=290.85], EntityCreeper['Creeper'/80, l='MpServer', x=300.50, y=39.00, z=300.50], EntityZombie['Zombie'/81, l='MpServer', x=292.50, y=20.00, z=319.80], EntityBat['Bat'/82, l='MpServer', x=285.98, y=35.10, z=316.25], EntityCreeper['Creeper'/83, l='MpServer', x=290.85, y=29.00, z=322.56], EntitySquid['Squid'/87, l='MpServer', x=305.86, y=59.06, z=277.04], EntitySquid['Squid'/88, l='MpServer', x=307.43, y=58.77, z=300.97], EntitySquid['Squid'/89, l='MpServer', x=308.11, y=59.48, z=283.44], EntitySkeleton['Skeleton'/90, l='MpServer', x=308.21, y=41.00, z=323.44], EntitySkeleton['Skeleton'/91, l='MpServer', x=319.49, y=47.00, z=327.29], EntityBat['Bat'/92, l='MpServer', x=316.12, y=48.58, z=326.23], EntitySquid['Squid'/99, l='MpServer', x=326.40, y=59.39, z=252.35], EntitySquid['Squid'/100, l='MpServer', x=332.53, y=60.73, z=309.36], EntitySkeleton['Skeleton'/101, l='MpServer', x=330.50, y=27.00, z=342.50], EntitySkeleton['Skeleton'/102, l='MpServer', x=333.29, y=27.00, z=345.49], EntityZombie['Zombie'/103, l='MpServer', x=326.65, y=39.00, z=355.80], EntityCreeper['Creeper'/104, l='MpServer', x=326.09, y=38.00, z=356.52], EntityCreeper['Creeper'/105, l='MpServer', x=330.85, y=37.00, z=352.39], EntityCreeper['Creeper'/106, l='MpServer', x=348.56, y=13.00, z=333.77], EntityZombie['Zombie'/107, l='MpServer', x=349.50, y=13.00, z=335.75], EntityZombie['Zombie'/108, l='MpServer', x=340.50, y=21.00, z=330.50], EntityWitch['Witch'/109, l='MpServer', x=342.50, y=19.00, z=324.50], EntityCreeper['Creeper'/110, l='MpServer', x=341.50, y=23.00, z=333.17], EntityCreeper['Creeper'/111, l='MpServer', x=342.50, y=19.00, z=327.50], EntityWitch['Witch'/112, l='MpServer', x=343.68, y=16.00, z=345.50], EntitySquid['Squid'/116, l='MpServer', x=349.77, y=56.97, z=309.62], EntityCreeper['Creeper'/244, l='MpServer', x=395.50, y=17.00, z=275.50], EntityCreeper['Creeper'/117, l='MpServer', x=353.50, y=16.00, z=325.50], EntitySkeleton['Skeleton'/125, l='MpServer', x=380.50, y=24.00, z=202.73], EntitySkeleton['Skeleton'/126, l='MpServer', x=376.77, y=25.00, z=205.50], EntitySkeleton['Skeleton'/127, l='MpServer', x=370.50, y=27.00, z=216.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2748)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:426)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1604434568 bytes (1530 MB) / 2040135680 bytes (1945 MB) up to 2040135680 bytes (1945 MB)
	JVM Flags: 32 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms2048m -XX:PermSize=256m -XX:NewRatio=3 -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+UseNUMA -XX:+CMSParallelRemarkEnabled -XX:MaxTenuringThreshold=8 -XX:MaxGCPauseMillis=10 -XX:GCPauseIntervalMillis=50 -XX:MaxGCMinorPauseMillis=7 -XX:+ExplicitGCInvokesConcurrent -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=60 -XX:+UseAdaptiveGCBoundary -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=3 -XX:TargetSurvivorRatio=80 -XX:MaxTenuringThreshold=15 -XX:+UseFastAccessorMethods -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+AggressiveOpts -XX:ReservedCodeCacheSize=2048m -XX:+UseCodeCacheFlushing -XX:SoftRefLRUPolicyMSPerMB=10000 -XX:ParallelGCThreads=6 -XX:+BindGCTaskThreadsToCPUs -Xnoclassgc
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.1.2577 Optifine OptiFine_1.12.2_HD_U_C8_pre 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                | Version      | Source                        | Signature                                |
	|:--------- |:----------------- |:------------ |:----------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft         | 1.12.2       | minecraft.jar                 | None                                     |
	| UCHIJAAAA | mcp               | 9.42         | minecraft.jar                 | None                                     |
	| UCHIJAAAA | FML               | 8.0.99.99    | forge-1.12.2-14.23.1.2577.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge             | 14.23.1.2577 | forge-1.12.2-14.23.1.2577.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | mercurius_updater | 1.0          | MercuriusUpdater-1.12.2.jar   | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 388.59' Renderer: 'GeForce GTX 750 Ti/PCIe/SSE2'
	Launched Version: 1.12.2-forge1.12.2-14.23.1.2577
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 750 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 388.59, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 3d_item_block_1.12+.zip, custom_entity_models.zip, slime_sounds_fix_1.11+.zip, vanilla_model_rendering_fix_1.12+.zip, sounds.zip, sounds, lightmap.zip (incompatible), 8ecbc1e9fc691af61e0f16995ef5b097-NewDefault.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 6x AMD FX(tm)-6300 Six-Core Processor 
	OptiFine Version: OptiFine_1.12.2_HD_U_C8_pre
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 388.59
	OpenGlRenderer: GeForce GTX 750 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 6

**Comment by sp614x** [comment]
Updated preview C8 for 1.12.2 with a bugfix.
