### ISSUE TITLE
Connected Textures / Shader reflection interaction 

### ISSUE THREAD

**Issue by VonDestinatus** [sp614x/optifine#1069]
![reflections](https://user-images.githubusercontent.com/34648680/34103532-1c188ac8-e441-11e7-955c-20ee0e399552.jpg)

I couldn't find this issue anywhere here, or its under a title I couldn't find. The picture is pretty self explanatory. I was told this was a "common" optifine issue, not a shader issue on the minecraft forums. I didn't have this issue in version 1.9, only just updated MC and all mods to 1.12.

minecraft: 1.12.2
optifine: 1.12.2-HD_U_C7
shader: sildurs vibrant shaders 1.163
textures: conquest 1.12

**Comment by sp614x** [comment]
Some resource packs define the CTM overlays on the translucent layer.
Sildur's shaders is adding reflections for all blocks rendered on the translucent layer, not only water or stained glass. It has to be fixed to enable reflections only for water blocks.

**Comment by sp614x** [comment]
You could try with latest Sildur's Shaders v1.166.

**Comment by VonDestinatus** [comment]
Thank you for the reply, I'll try that now and see how it goes.
