### ISSUE TITLE
[Optifine Startup Crash]

### ISSUE THREAD

**Issue by FrancisDaPugtato** [sp614x/optifine#1072]
Optifine Version: Optifine 1.12.2 Optifine C8-pre (Downloaded from the 12/18/17 version of the pre-build. Crashed when starting up. 
Here is a pastebin on the crash:
https://pastebin.com/4W1QaRZN
It is able to start but crashes within 10 seconds of run time.

**Comment by FrancisDaPugtato** [comment]
It is able to start but crashes within 10 seconds of run time.

**Comment by sp614x** [comment]
Updated preview C8 with a bugfix. Please redownload it.

**Comment by FrancisDaPugtato** [comment]
o-o It worked. Thanks! I dunno why it happened since I was sure I downloaded the latest...
