### ISSUE TITLE
Crash when opening an ender chest with Forge 2569+

### ISSUE THREAD

**Issue by alienheadtransplant** [sp614x/optifine#1074]
Hi. I'm getting a client crash when opening ender chests using OptiFine 1.12.2 HD U C7 with Forge 1.12.2-14.23.1.2569 and up. I'm guessing it's related to this: Change how chests check if they're blocked. ([#4584](https://github.com/MinecraftForge/MinecraftForge/pull/4584))

Crash Log:

[crash-2017-12-19_15.43.29-client.txt](https://github.com/sp614x/optifine/files/1572363/crash-2017-12-19_15.43.29-client.txt)

**Comment by sp614x** [comment]
Preview C8 is updated with a bugfix. 
Compatible with Forge #2577
