### ISSUE TITLE
Re-Enable entityID in the shadow program

### ISSUE THREAD

**Issue by JinTheDev** [sp614x/optifine#1075]
Myself, as well as few other shader developers, would appreciate it if entityID was enabled in the shadow program. As it currently stands, entityID and blockEntityID are both useful to know in the shadow programs, but currently they are both set to 0.

**Comment by sp614x** [comment]
Updated preview C8 for 1.12.2
 - enabled shader uniforms "entityId" and "blockEntityId" for the shadow pass
