### ISSUE TITLE
Black lines on top of every connected block?

### ISSUE THREAD

**Issue by ColonelOverspel** [sp614x/optifine#1076]
Please look at this screenshot: https://i.imgur.com/DrYXZ8s.png

I don't know what is wrong, but I can't seem to fix it. Here are my ctm settings (and yes I saved the file in the right format and the right file type)

matchBlocks=159
method=ctm_compact
tiles=0-8
connect=block
metadata=0
ctm.13=5
ctm.15=6
ctm.37=7
ctm.39=8

**Comment by MisterQuiggly** [comment]
> ctm.13=5
ctm.15=6
ctm.37=7
ctm.39=8

What is all of that for? Don't think that would cause it. It shouldn't.

**Comment by sp614x** [comment]
The method `ctm_compact` needs 5 tiles, not 9.
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/ctm.properties#L63

The `ctm.N` properties are special cases:
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/ctm.properties#L165

**Comment by ColonelOverspel** [comment]
@MisterQuiggly It's to specify special tiles, you can add that to the ctm_compact method.

@sp614x I know that, but it shouldn't cause this bug, right? I tested it, and even without those specifications the bug occurs.

**Comment by sp614x** [comment]
Is OptiFine running standlone or with Forge?
Other mods installed?

**Comment by ColonelOverspel** [comment]
@sp614x with Forge, almost no other mods, other people have the bug too (without having any other mods active)

**Comment by realjackasterisk** [comment]
@ColonelOverspel ***almost*** no other mods?

**Comment by ColonelOverspel** [comment]
@realjackkasterisk @sp614x Xaeros Minimap

**Comment by ColonelOverspel** [comment]
@sp614x I know what caused this bug. You have to make sure that the textures/models/blockstates on the normal (vanilla) resourcepack side are not causing trouble. I had the blockstates messed up (if you don't have optifine it will display the 'missing texture' texture) and it affected the ctm textures as well.

**Comment by sp614x** [comment]
If the model is broken and it has other issues then CTM may not work correctly.
Resource pack link?
