### ISSUE TITLE
Crash when opening ender chest with custom texture pack.

### ISSUE THREAD

**Issue by bobotje** [sp614x/optifine#1079]
I play a lot on the server Wynncraft and it has a custom texture pack, I use the texture pack. Now I'm using the lastest version of the 1.12.2 optifine and when I open the ender chest it crashes me. I also tried in vanilla minecraft and got the same issue. The problem is recent and hasn't happened before.

Here's the crash file: https://pastebin.com/W9dqNxqr

**Comment by Builderb0y** [comment]
#1078, #1074, #1071, #1067

**Comment by sp614x** [comment]
Fixed in preview C8 for 1.12.2 with a bugfix.
