### ISSUE TITLE
When will the chest problem be fixed?

### ISSUE THREAD

**Issue by Kzitold** [sp614x/optifine#1080]
1.12.2 HD U C7 made opening chests impossible, as many have said before. I know you all said it's fixed in the 1.12.2 HD U C8 **_pre_**.

The problem is not everyone will notice the Preview Versions, and I don't imagine the preview versions playing nicely with things to automate keeping up to date. Is the chest problem really so bad that you can't release a just-a-fix without weeks of it hiding in the preview versions?

**Comment by JonasCiss** [comment]
A preview is not really tested. It takes so long to ensure that bug are already fixed. And if someone is looking for that issue, the answers can be found fast. Just use the preview versions if you suffer from the issue.

**Comment by sp614x** [comment]
The stable OptiFine C7 is compatible with the stable (recommended) Forge #2555.
The preview OptiFine C8 is compatible with the unstable (latest) Forge #2577.
The change in chest behaviour was added in Forge #2569 which is not recommended yet.
