### ISSUE TITLE
Unable to open chests

### ISSUE THREAD

**Issue by OHYtheAwesome** [sp614x/optifine#1088]
I am having a problem where in the newest 1.12.2 update (OptiFine HD C7), I am unable to open chests and it crashes when opening enderchests.
I am using the newest for forge (1.12.2 - 14.23.1.2581). There is only 1 mod in my mods directory that is OptiFine.
I have tried it many times, restarting my game and reinstalling the mod but to no avail it still crashed
This is the crash report when opening enderchests:
https://pastebin.com/ZavrES5V

**Comment by sp614x** [comment]
Fixed in preview C8.
You are using latest Forge which is NOT STABLE.
OptiFine C7 is compatible with the stable (recommended) Forge #2555.
