### ISSUE TITLE
OF 1.12 c8 crashes when loading chunk with shulkerbox facing down connected with a glasspane.

### ISSUE THREAD

**Issue by i9hdkill** [sp614x/optifine#1089]
Screenshot from mcedit:
(purpur_stairs is actually a shulkerbox facing down with stone under it)
http://prntscr.com/hr9ytq

https://pastebin.com/j1g1L0JP
Game doesn't crash when removing OF C8

Tested with forge 2778 and 2781

**Comment by sp614x** [comment]
Screenshot without OptiFine?
Can you redownload preview OptiFine C8 and try again?

**Comment by i9hdkill** [comment]
Screen without Optifine
http://prntscr.com/hrdij2

Crash with fresh C8 download:
https://pastebin.com/45gMNbGd

Okay more info that is relevant I guess:
It's a world converted from 1.10.2.
When loading this chunk for the first time with 1.12, Forge with Optifine installed always crashes. 
But when loading withut Optifine, the shulkerbox only apears visible clientside if you come very close to it. (10 blocks)
At the point the server seems to change something in region.nbt regarding this box. If you join after loading the chunk and box with forge only, you can join with Optifine just fine.
You can reproduce this behaviour every time by replacing the 1.12 region file with original 1.10 region file, restart the server and join with optifine--> crash und less you load the chunk with normal forge once.

**Comment by sp614x** [comment]
The crash is inside `BlockShulkerBox` most probably because it can't find the shulker box tile entity.
If the world behaves strange without OptiFine (shulker box only visible from 10 blocks) then the world may be corrupted. 
Does not seem to be related to OptiFine. The crash is triggered by CTM, but the BlockShulkerBox should never crash when asked about it's shape.

**Comment by i9hdkill** [comment]
The world isn't corrupted, as it's totally fine with vanilla Forge clients.
My guess is, as I said, that when loading an old 1.10 chunk for the first time with a 1.12 client, there is some auto-update from minecraft that saves the shulkerbox in a new format or what so ever. But Optifine doesn't support this old 1.10 format. So it crashes, until the old chest has been auto-migrated to the new format. I would be glad if you could look into it, as many of users are running into this issue. It should be reproducible by placing a shulkerbox in a 1.10 world and try to load it with 1.12 optifine.

**Comment by i9hdkill** [comment]
Okay, turns out that these "shulkerboxes" were different items/blocks on 1.10. These blocks just matched the ids of shulkerboxes in 1.12
