### ISSUE TITLE
Installers'll Copy Jar File Unnecessarily

### ISSUE THREAD

**Issue by HeartyYF** [sp614x/optifine#109]
For example,if you write down`"inheritsFrom": "1.9"`,then you need't copy its jar to 1.9-OptiFine and rename it.

**Comment by HeartyYF** [comment]
I touched "enter" by mistake..

**Comment by HeartyYF** [comment]
This has been fixed in 1.13 alpha8.

**Comment by HeartyYF** [comment]
No I mistook. Now it uses "inheritsFrom" but it still copy jar file.

**Comment by RedCarlos26** [comment]
The oldest issue of all optifine's GitHub

**Comment by omerien** [comment]
yeah, and nobody understood the problem, because the user doesn't speak correctly English
