### ISSUE TITLE
CTM does not work well.

### ISSUE THREAD

**Issue by KKMNNOIR** [sp614x/optifine#1092]
I tried the latest preview of 1.12. When using a resource pack, CTM does not work in most cases, it works only in a few cases(Sandstone, Bookeshelves) This also happened with 1.12.2 C7 and 1.11.2 C3. I am looking at documentation, but I do not know what is the cause.
Here are my Bookshelves,  Glasses,  Sandstones CTM properties:

> method=horizontal
tiles=0-3
faces=sides

> method=ctm
tiles=0-46
connect=tile
matchTiles=glass

> method=vertical
tiles=0-3
metadata=0
faces=sides
connect=tile
matchBlocks=24

> method=vertical
tiles=0-3
metadata=0
faces=sides
connect=tile
matchBlocks=179

![2017-12-24_00 31 55](https://user-images.githubusercontent.com/34789830/34320713-704132ac-e843-11e7-9317-e05eaa508fb2.png)

**Comment by sp614x** [comment]
Resource pack link?

**Comment by KKMNNOIR** [comment]
Here
[A8.zip](https://github.com/sp614x/optifine/files/1584850/A8.zip)

**Comment by MisterQuiggly** [comment]
Remove all capital letters from every folder. Remove all [Data values] from every folder. That should fix your problem

**Comment by sp614x** [comment]
Since 1.11 resource packs have to use lowercase for all folder and file names.
This is a vanilla requirement.

**Comment by KKMNNOIR** [comment]
Oh, I see. It worked:) 
Thx! !
