### ISSUE TITLE
Crash with Optifine [Custom Sky Color]

### ISSUE THREAD

**Issue by Vyraal1** [sp614x/optifine#1093]
Not exactly sure what's the cause of this crash or how to fix it - it sometimes occurs, and it sometimes doesn't.
https://pastebin.com/aWDicrNL

**Comment by sp614x** [comment]
Duplicate of https://github.com/sp614x/optifine/issues/603
This seems to be a known limitation of Forge when extending enums: MinecraftForge/MinecraftForge#2787
To fix this JED should extend the enum as early as possible, for example in a static block in the main mod file.

**Comment by Vyraal1** [comment]
Hi, I just talked with the JED dev and he was wondering if it was possible if:

> masa: Of course there would also be the option that Optifine would stop using a switch on the DimensionType, due to it being an enum that mods need to modify...

Is this something that is do-able? Otherwise I can go back and see if another solution can be worked out.
