### ISSUE TITLE
Vanilla Chests Won't Open

### ISSUE THREAD

**Issue by Rayzilla68** [sp614x/optifine#1094]
I have a modded world I've been playing for a couple months with version C6 installed and,  it had been running properly. However, when I went to play today, none of my oak chests would open. I had some birch ones and they opened fine (from Forestry, I think? I have about 75 mods running). I turned off all my mods and re-started them a few at a time until the vanilla chests wouldn't open and Optifine was the culprit. I updated to C7 and no luck. I started a brand new 100% vanilla world and the chests worked as expected until I installed either of the Optifine versions, then they would not open. Removing Optifine let them open properly again. 

I am on 1.12.2 and am using the Twitch launcher.

Thanks,

**Comment by Builderb0y** [comment]
#1079, #1078, #1074, #1071, #1067

**Comment by sp614x** [comment]
Fixed in preview C8 for 1.12.2
