### ISSUE TITLE
Minecraft Server Resource Pack Won't Download (reopened)

### ISSUE THREAD

**Issue by PaulHotel** [sp614x/optifine#1096]
Hi,
I have a server resource pack which has a mcpatcher file in it. I have checked that the file is under 50 MB and that the link is valid but it still wont download. I think this has something to do with that mcpatcher file.

EDIT: I tried to add the default minecraft assets and it still doesnt work.

Server ip is play.enderhotelmc.com
Resource pack link: http://download2146.mediafire.com/qd4kbp5wmpug/dnpxco97tx2r75i/EnderHotelMC.zip

Please use version 1.12.2

**Comment by CoolboyUA** [comment]
Try to remove folder from first level. `pack.mcmeta` and others files must be at top level.

**Comment by sp614x** [comment]
The resource pack is wrongly zipped.
The folder "EnderHotelMC" should not be in the ZIP, "pack.mcmeta" and "pack.png" shoot be in the root folder.

**Comment by PaulHotel** [comment]
Oops, thanks for the help!
