### ISSUE TITLE
Add support for sliders in shaders

### ISSUE THREAD

**Issue by lasermarty** [sp614x/optifine#11]
It would be great if we could use sliders for options in our shaderpacks. I like the current list ability but a slider would offer more freedom.

I would suggest allowing to set a min and max value of the slider value so there is some limitation possible.

**Comment by BruceKnowsHow** [comment]
Configurable quantization (you can set the intervals, like how FOV can only be an integer) would also be nice.

**Comment by dotModded** [comment]
bump

**Comment by sp614x** [comment]
![image](https://user-images.githubusercontent.com/16635441/27307813-d34f60b6-554b-11e7-8191-24835834efb3.png)

**Comment by sp614x** [comment]
Updated preview C3 for 1.12
- added shader option sliders

All options with a list of values are automatically shown as sliders.
