### ISSUE TITLE
[Advice]Why not add Dynamic Lights and Custom Skin?

### ISSUE THREAD

**Issue by HeartyYF** [sp614x/optifine#110]

**Comment by sp614x** [comment]
Dynamic Lights are quite complex to implement properly. I am experimenting with a prototype currently, it may or may not be added to OptiFine, depending on many factors.
The player skins can be changed on the http://minecraft.net website, resource packs may change the default player skin.
What are "custom skins" meant to be?

**Comment by HeartyYF** [comment]
Custom skin loading URI,which means another skin website besides Mojang

**Comment by mindforger** [comment]
@HeartyYF why would you need that, besides using cracked MC which is absolutely stupid

**Comment by sp614x** [comment]
Experimental B5_pre with Dynamic Lights: [here](http://optifine.net/tmp/OptiFine_1.9.0_HD_U_B5_pre_DL.jar)

**Comment by HeartyYF** [comment]
@sp614x Dynamic Lights don't render the torch on the head as a light source.
It seems that China Unicom don't want me to upload my screenshot...

**Comment by sp614x** [comment]
What is torch on the head - a torch in the head armor slot?

**Comment by HeartyYF** [comment]
Yes,in a server with Essentials you can use /hat to wear everything in your head armor slot.

**Comment by sp614x** [comment]
Updated B5_pre, the torch in the head slot should work now.

**Comment by HeartyYF** [comment]
Yes,I think it's perfect now.But it seems that language files are't updated..

**Comment by HeartyYF** [comment]
Ah,another problem.If I change my gamemode to spectator with a torch held in my hand(or in my head slot),it will still shine.

**Comment by EskiMojo14** [comment]
Would "Custom Skins" allow for loading of HD skins?

**Comment by sp614x** [comment]
Spectator mode is fixed.

**Comment by HeartyYF** [comment]
@EskiMojo14 I think that's great,but obviously I can't decide:)

**Comment by EskiMojo14** [comment]
One other thing to think about: would the "Custom Skin" display to only you, or would it be able to display to everyone using OF, like the capes? :)

**Comment by mindforger** [comment]
i support EskiMojo14's solution as a general idea, but how should people sync the skin? you'll need quiet a beefy server to provide the skins for all those players using this :)

custom skins only on client side would only help those playing minecraft in "offline mode" (if you get what i mean) and this should not be supported in any way ... 

but i understand the urge for high res skin textures ... maybe a tradeoff like "skin-file-name has to match UUID" and overrides the default skin when the player is present !?

**Comment by HeartyYF** [comment]
@EskiMojo14 @mindforger My first idea is to use it offline,but for some servers,they want their players to use their servers' own skin server,so that they can make a difference and attract more players.
As for other players,if they use OF skins will also display.
By the way,load skins from each other maybe a good idea.

**Comment by mindforger** [comment]
this is practically impossible! you can not "simply" exchange skins from player to player with at least a server side plugin/mod to grant a channel to exchange the skin data or some sort of public server where the skins are deployed
`My first idea is to use it offline` i hate this idea from the bottom of my heart
 `want their players to use their servers' own skin server,so that they can make a difference and attract more players` as i said if there is some sort of serverside mod that connects with the optifine client mod this would work actually! But still the only simple solution here is to store the skin as UUID linked file to override the rendering of certain UUID Player Entitys

**Comment by jriwanek** [comment]
The offline skin server idea sounds terrible to me, sounds like it'd be used for unpaid copies of minecraft (Why in the hell would it be so hard for people to just upload their skins to mojang's skin server?) very dodgy indeed...

**Comment by mindforger** [comment]
` (Why in the hell would it be so hard for people to just upload their skins to mojang's skin server?)` he was speaking of high res skins, nothing that mojangs skin servers support .. or did i miss an update?

**Comment by jriwanek** [comment]
Ahh, I apparently missed that.

**Comment by SimJoSt** [comment]
I would recommend making it more clear, that the Dynamic Lights feature is unrelated to @AtomicStryker's mod. Especially on the public sites like the minecraft forum and optifine.net

**Comment by sp614x** [comment]
Updated forum post and optifine.net
