### ISSUE TITLE
Optifine makes chests impossible to interact with

### ISSUE THREAD

**Issue by icebunny08** [sp614x/optifine#1100]
so when I installed optifine 1.12.2 c7 something I can't interact with chests, how did I know?when i removed all mods except for optifine I still can't interact but when i removed optifine I can interact with it again and when I added all my mods except optifine I can interact, when I have optifine I can't interact with any chests, when I created a test world with bonus chest on i can't interact with the bonus chest/normal chest and when I break it it only drops the chest itself not the items also when I interact with the ender chest Minecraft crashes.

**Comment by Builderb0y** [comment]
#1094, #1079, #1078, #1074, #1071, #1067

**Comment by sp614x** [comment]
Fixed in preview C8 for 1.12.2
