### ISSUE TITLE
Cannot open chests

### ISSUE THREAD

**Issue by RtHiaHB** [sp614x/optifine#1101]
This is an odd one, I know. Believe me, I was surprised myself.  Note: it may be related to chests being reskinned for the holidays, I don't know.

I'm using Optifine 1.12.2 HD_U_C7

Anyway, the other day, I couldn't open any of my chests, so I logged out of the world and without shutting down the MC client, relogged.  MC client crashed (see attached crash report).

[crash-2017-12-24_02.58.59-server.txt](https://github.com/sp614x/optifine/files/1586482/crash-2017-12-24_02.58.59-server.txt)

I experimented a little bit (I cleared the mods folder and reintroduced mods one at a time until the crash occurred), I found it crashed again after adding Optifine back into the mods folder.  I then took it out and added the rest back without a problem.

[crash-2017-12-24_03.37.33-server.txt](https://github.com/sp614x/optifine/files/1586484/crash-2017-12-24_03.37.33-server.txt)

I have Forge for 1.12.2 v 14.23.1.2581 installed with the following mods (all for 1.12.2):

- CodeChickenLib 3.1.5.331
- CoFHCore 4.3.8.28
- CoFHWorld 1.1.0.11
- Extra Utilities 2 1.7.2
- gravestone 1.10.0
- hopperducts 1.5
- JEI 4.8.5.138
- Journey Map 5.5.2
- Light Level Overlay Reloaded 1.1.4
- McJtyLib 2.5.0
- RedstoneFlux 2.0.1.2
- RF Tools 7.15
- The One Probe 1.4.19
- Thermal Dynamics 2.3.8.16
- Thermal Expansion 5.3.8.38
- Thermal Foundation 2.3.8.22
- Time HUD 7.2.1

Thanks.

**Comment by Builderb0y** [comment]
#1100, #1094, #1079, #1078, #1074, #1071, #1067

**Comment by sp614x** [comment]
Fixed in preview C8 for 1.12.2
