### ISSUE TITLE
Variable resolution for post processing stages

### ISSUE THREAD

**Issue by Choca13** [sp614x/optifine#1103]
Having the ability to set the output resolution of a particular post processing stage would be extremely useful for many effects. For example, we could use a fixed size 2D texture to simulate a fake 3D texture, compute some effects at half or quarter resolution, efficiently generate filtered mips for bloom, apply pre-filtering to the shadow map...

For example : 
Composite is set to run at 1024*1024, and outputs to colortex0 and colortex1. colortex0 and 1 now are 1024^2 textures but the others framebuffer textures are still using the current screen resolution.
Later on, colortex0 is not required anymore and will be used as an output to composite4 which is set to run at half of the screen resolution. colortex0 becomes a half-resolution texture but colortex1 stays at 1024^2.

Possible implementation:
Into the shader program, two variables for the texture's width and height, for example:
const int outputSizeX = 1024;
const int outputSizeY = shadowMapResolution/4;
const int outputSizeX = viewWidth/8;
If nothing is specified, just use the current screen resolution.

**Comment by sp614x** [comment]
Relevant
https://stackoverflow.com/questions/18678604/multiple-render-targets-in-one-fbo-with-different-size-textures

**Comment by Choca13** [comment]
Even if it is not possible to change the resolution of one buffer between two stages, i'm still interested in having the ability to set a post process stage to run at a specified resolution, even if the outputs are forced to stay at that resolution for all the rendering process.

**Comment by sp614x** [comment]
Testing custom composite resolution.

Deferred writes to `colortex5` with full resolution, composite reads from `colortex5`:
![image](https://user-images.githubusercontent.com/16635441/34749637-d17a8a8e-f5a2-11e7-999f-9fe8f7b751ee.png)


Deferred1 writes to `colortex6` with low resolution, composite reads from `colortex6`:
![image](https://user-images.githubusercontent.com/16635441/34749616-b6bbe198-f5a2-11e7-9da6-23d427e70183.png)

Deferred1 writes to `colortex6` with low resolution, composite reads from `colortex6` with scaled UV:
![image](https://user-images.githubusercontent.com/16635441/34749596-922703da-f5a2-11e7-94b4-74dff4fa42e1.png)

By changing the viewport size a low resolution output can be generated. Configurable as scale factor per composite/deferred program. The size of the buffers is not changing, only the rendered region. Using a complex `deferred1` program shows that lower scale factors (1/16) are faster as less pixels are processed. One problem with the scaled UVs is that the border color (black) bleeds on the edges. The current magnification filter is GL_LINEAR.

**Comment by Choca13** [comment]
That's very nice! Could you also add a way to write at a specific place in the buffer? I mean for example in your screenshot the image is written from (0,0) cordinates to (1/16,1/16), could you configure it to write from (2/16,2/16) to (3/16,3/16) by moving the quad? For example one pass could write in the bottom left and the next one in the upper right.

**Comment by sp614x** [comment]
By definition composite stages are expected to transfer all pixels. Otherwise the ping-pong buffers will be very tricky to get right.
If composite1 writes in bottom left and composite2 writes in upper right, then in composite3 the bottom left would be empty. However in composite4 the bottom left will appear again (ping-pong buffer magic).

**Comment by sp614x** [comment]
When sampling the low-res buffer the texture coordinates have to be clamped to the low-res size minus half pixel to avoid sampling from outside the low-res region.

![image](https://user-images.githubusercontent.com/16635441/35075640-903e7208-fbf4-11e7-926e-01f0d7c2e32c.png)

**Comment by sp614x** [comment]
It may be possible to write to different small regions in one buffer if the ping-ponging for this buffer is disabled. In this case it would not be possible to read from and to write to this buffer in the same program.

**Comment by sp614x** [comment]
```
# Composite render scale
# Custom render scale for composite and deferred programs.
# The scale is used to define a custom viewport which only renders in a part of the draw buffers.
# The scale, offsetX and offsetY should be between 0.0 and 1.0
# Default offsetX and offsetY are 0.0.
scale.<program>=<scale|scale offsetX ofsetY>
```

**Comment by mindforger** [comment]
just for the sake of understanding, as i am very uneducated regarding rendering things, you render the image actually in low res and scale it up through the viewport? does this actually reduce rendering load? i want to ask for the other topic with dynamic resolution switching if you can remember :)

**Comment by sp614x** [comment]
several composite programs, each writing to a different low-res region in the same buffer:

![image](https://user-images.githubusercontent.com/16635441/35098689-819d8002-fc55-11e7-9f1d-01420fa29eb9.png)

**Comment by sp614x** [comment]
On the other hand, forced buffer flip can be used to double the amount of avilable buffers:

Classic flow:
- deferred writes to colortex6(A) - auto flip
- deferred1 writes to colortex6(B) -  auto flip
- all subsequent programs can only read from colortex6(B) as long as they don't write to colortex6

Alternative flow:
- deferred writes to colortex6(A) - auto flip
- deferred1 writes to colortex6(B) -  auto flip
- composite reads from colortex6(B) - forces flip
- composite1 reads from colortex6(A)  - forces flip
- all subsequent programs can read last flipped buffer(edited)
so colortex6 can transfer 2 buffers from deferred to composite instead of 1

**Comment by sp614x** [comment]
@mindforger the composite image is rendered al low resolution so there are much less pixels to be processed. This can help with complex shaders which do many calculations per pixel, but don't need high resolution.
The next composite program can upscale the low-res texture by reading from low-res texture coordinates.

**Comment by sp614x** [comment]
Updated preview C9 for 1.12.2
 - added variable resolution for composite programs (#1103)
 - added configurable buffer flip for composite programs (#1103)

https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.properties#L365
