### ISSUE TITLE
Minecraft java crash, Minecraft crash and audio error.

### ISSUE THREAD

**Issue by MZPL** [sp614x/optifine#1104]
Audio: https://pastebin.com/jQ7qvHpJ
Java: https://imgur.com/hLh1zMy
Translated: Program Java stopped working. 
The program has stopped working due to the problem. Windows will close the program and notify you if a solution is available.
Minecraft crash: https://pastebin.com/gSKTEW70
Please help!

**Comment by sp614x** [comment]
```
# Problematic frame:
# C  [SafeIPs64.dll+0x5a0b]
```
The `SafeIPs64.dll` is crashing. 
Looks like this is external program not related to OptiFine or Minecraft: http://www.shouldiblockit.com/safeips64.dll-3a9a531154c3c29fccf22a9908ca2e8c.aspx
