### ISSUE TITLE
Sea Lantern CTM Missing Texture?

### ISSUE THREAD

**Issue by Goopy25** [sp614x/optifine#1105]
Every connected texture I've made is working, for example stone slabs.

But for some odd reason, sea lanterns won't work! The funny thing is, in the last resource pack I made, the sea lanterns did work. Both my old and new resource pack have the _exact same_ .properties folder, yet only the new resourcepack doesn't work!
![2017-12-27_11 47 50](https://user-images.githubusercontent.com/34896763/34393055-49cec286-eafc-11e7-8d64-865707a71d46.png)

inside mcpatcher\ctm\sea_lantern\

`matchBlocks=169
method=ctm_compact
tiles=0-4`

**Comment by sp614x** [comment]
Resource pack link?

**Comment by MisterQuiggly** [comment]
Im guessing its a problem with the animation. Make sure it has the animation text file for each texture and named properly.

> 0.png.mcmeta
1.png.mcmeta
2.png.mcmeta
3.png.mcmeta
4.png.mcmeta

**Comment by Goopy25** [comment]
here's the link to the dropbox download: https://www.dropbox.com/s/gnmzxic1jqy39xv/betterMC_Quark_Edition.zip?dl=0

sorry for taking so long :/

**Comment by MisterQuiggly** [comment]
Yep just as I thought, you're missing the animation files. Do what I said above and it will fix it. If you have questions reply back. Take the sea_lantern animation from the blocks folder and make copies and rename it as said above.

**Comment by Goopy25** [comment]
But, the textures aren't animated. They're only one frame

**Comment by MisterQuiggly** [comment]
try removing matchBlocks=169 and renaming the file sea_lantern

**Comment by Goopy25** [comment]
ah, finally! Thanks so much. It worked. Now I can finally move on to _other_ things!

**Comment by MisterQuiggly** [comment]
No problem!
