### ISSUE TITLE
How to change a villager texture based on biome

### ISSUE THREAD

**Issue by CacheTellsStories** [sp614x/optifine#1107]
Hello, I was wondering if it is possible to change villager texture based on biome. Each villager has a different name so it is different from something like a zombie. If it is not possible, then is it possible to change the texture based on name?

**Comment by sp614x** [comment]
With Random Entities (Random Mobs) you can change villager textures by biome or by name:
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/random_entities.properties#L75
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/random_entities.properties#L89
