### ISSUE TITLE
Lag with smooth fps in minecraft optifine 1.11.2 & 1.12.2 in windowns 10

### ISSUE THREAD

**Issue by Chrishunk** [sp614x/optifine#1108]
Notebook Configuration
Intel i3 processor 2310m
integrated graphics card intel hd graphics 3000
8 GB of RAM
oprecional system windowns 10 64 bits

so I installed the optifine, I was configure in the performase options, to get a better performance in minecraft, so I activate the option to soften fps, the game starts to lock, then in the menu, it is 1 fps, without adding or Decrease, can anyone help me with this?

**Comment by sp614x** [comment]
Is Smooth World enabled?
Is OptiFine installed standalone or with Forge?
Other mods installed?

**Comment by Chrishunk** [comment]
I need smooth fps enabled not to get caught, I use the optifine on 1.12.2 without the forge it is on 1.11.2 with forge is 50 mods

**Comment by Chrishunk** [comment]
I need smooth fps enabled not to get caught, I use the optifine on 1.12.2 without the forge it is on 1.11.2 with forge is 50 mods
