### ISSUE TITLE
Custom shader texture causes OpenGL error 0x0500

### ISSUE THREAD

**Issue by sp614x** [sp614x/optifine#1109]
From Discord @Builderb0y:

Custom textures seem to be causing issues for darian. in this case, binding texture.gbuffers.gaux1 in shaders.properties and having uniform sampler2D gaux1 enabled in gbuffers_block will cause GL error 0x0500: Invalid enum at pre-final to be spammed to the console, but not consistently. 

Apparently it shows up if the pack is enabled when launching the game, but has a delay for showing up when switching to this pack. It also apparently doesn't disappear when switching to a different pack either and a full client restart is necessary for it to go away. 

Packs for testing:

https://www.dropbox.com/s/fgyurxs8btd7au1/Builder%27s%20QOL%20Shaders%20V1.14.3_no_end_texture.zip?dl=0

https://www.dropbox.com/s/7n2lxktxec5a5ph/Builder%27s%20QOL%20Shaders%20V1.14.3_hotfix_1.zip?dl=0

the "no_end_texture" version works as intended, and the "hotfix_1" version has this spam error.
later, darian posted the following log files: (also copy-pasted)

I probably had to cut out ~90% of the log there.
I'll post two versions: The cut one, and the raw unfiltered one.
THIS version is the CUT one: https://pastebin.com/urL1WD8c

THIS version is RAW: https://pastebin.com/4EsYQjhi

if it's relevant, the custom textures in question were used by end portals. no idea if having one on-screen or not changes anything though.

**Comment by realjackasterisk** [comment]
Wait, "Discord"? Is there an Official Optifine Discord server I don't know about?

**Comment by sp614x** [comment]
@realjackasterisk there is an #optifine channel on the Shader Labs discord server.

**Comment by sp614x** [comment]
Can't reproduce the problem. 
The "hotfix_1" shader pack seems to work correctly, the end portal looks OK:

![image](https://user-images.githubusercontent.com/16635441/34448414-5a3757bc-eced-11e7-8c0e-091d41278d2a.png)

Tested changing shader packs, restarting game with and without the shader pack.
