### ISSUE TITLE
In Optifine C7 due to the new chunk loading optimizations sometimes block updates make invisible blocks

### ISSUE THREAD

**Issue by Miclebrick** [sp614x/optifine#1112]
I was ecstatic when I first discovered Optifine C7, as it makes the starship plugin on my server so much less laggy! 

But I quickly noticed that when moving, blocks often go invisible. Actually, all the blocks of the ships in a specific chunk go invisible, until I do f3 + a. This also happens very rarely when building, I suppose building just doesn't have as many rapid chunk updates. 

When the blocks of the ship move out of that chunk, it's a gamble whether the next chunk is broken too, but eventually it gets to a non-broken chunk and is visible again.

Here's a screenshot of an invisible ship:
![image](https://user-images.githubusercontent.com/6323125/34453959-0989ff54-ed2e-11e7-90e9-4736f9344dc8.png)
If you look carefully, you can see that I have the hitbox of one of the blocks selected.
![image](https://user-images.githubusercontent.com/6323125/34453965-1ef11c24-ed2e-11e7-895d-aa7083b67349.png)
Post F3 + A

If this bug can get fixed without making chunk loading slow again, that would be wonderful!

**Comment by sp614x** [comment]
How can I test it?
Server link?

**Comment by Miclebrick** [comment]
Sorry for late response
Server IP is mc.starlegacy.net, you can get a ship shortly after the spawn.

**Comment by Miclebrick** [comment]
Any update?

**Comment by sp614x** [comment]
Is this working correctly in latest version D3 for 1.12.2?

**Comment by Miclebrick** [comment]
I don't get the issue anymore, I think it's because the plugin i was using to send the packets started using bitmasks that don't send the entire chunk but im not 100% certain if that's the reason so I made that a separate issue
