### ISSUE TITLE
Optifine C7 (1.12.2) - Forge > build 2569 - Cannot open Chest in SinglePlayer

### ISSUE THREAD

**Issue by Dockter** [sp614x/optifine#1114]
Abstract Method Error:  https://gist.github.com/Dockter/1d4609d4991003363683d8bc841624f5

Issue was introduced with Forge build 2569 on 12/17/2017

Process of elimination points the issue to Optifine C7.  This method doesn't exist in this class in Vanilla.

Confirmed working fine with Forge: 2555, 2565, 2566, 2567, 2568.
Confirmed Broken: 2569, 2570, 2575, 2582

Thx.

**Comment by Builderb0y** [comment]
#1101, #1100, #1094, #1079, #1078, #1074, #1071, #1067

**Comment by realjackasterisk** [comment]
Will these duplicate reports ever end?

**Comment by sp614x** [comment]
Quite normal. 
OptiFine C7 is compatible with Forge #2555.
Preview OptiFine C8 is compatible with Forge #2577.
