### ISSUE TITLE
Keep /gamemode shorthands

### ISSUE THREAD

**Issue by Diamond-Wolf** [sp614x/optifine#1115]
I'm sure I'm not the only one who wants to not spend a long time typing "/gamemode adventure" when a simple "/gamemode a" works.

**Comment by realjackasterisk** [comment]
Er... are you saying this doesn't work with Optifine installed? Tested on standalone and Forge, it still works fine for me.

**Comment by sp614x** [comment]
This is probably a future request to fix MC 1.13 (when it gets released) which removes the shortcuts `/gamemode 0/1/2/3`

**Comment by Brottweiler** [comment]
Learn to use tab auto completion; `/gamemode a` <kbd>TAB</kbd>

**Comment by sp614x** [comment]
Changing command syntax is outside of the scope of OptiFine.
Also I tried something similar a while ago and it was quite complicated, so it was not added.
