### ISSUE TITLE
More buffer formats.

### ISSUE THREAD

**Issue by VignetteCoeff** [sp614x/optifine#1116]
I'd like to request a few buffer formats that would be helpful for specific cases.

`R16_G16_B8`
`R16_G16_B4`
`R16_G8_B8`
`R16_G8_B4`
`RGB10_A1`
`RGB16_A8`

Others most likely have more suggestions but those are ones that would be very useful for fully optimizing my shader.

**Comment by sp614x** [comment]
These color formats are not supported by OpenGL and they can't be added:
https://www.khronos.org/opengl/wiki/Image_Format#Special_color_formats
