### ISSUE TITLE
Parrot & Bed and upcoming 1.14 mobs CEM

### ISSUE THREAD

**Issue by mexbotdude** [sp614x/optifine#1117]
I want to know if its gonna be possible to make parrots compatible with CEM, so as beds, now that they are multicolored and are considered as entity.

If there are still missing this I suppose upcoming mobs will have this issue as well

regards,

**Comment by sp614x** [comment]
OptiFine 1.12.2_HD_U_D2_pre
 - added CEM support for bed and parrot (#1117)
