### ISSUE TITLE
[BUG] Optifine does not allow chest opening in singleplayer

### ISSUE THREAD

**Issue by scigeotech** [sp614x/optifine#1119]
I used forge version 1.12.2-14.23.1.2583 (required by some of my mods) and could not open chests. I then decided to take away most of my mods, isolated Optifine, and ran it with Forge again. I still was unable to open any chests in singleplayer mode. Here's the log, if it helps.

https://pastebin.com/xjxYEa8H

**Comment by realjackasterisk** [comment]
#1114, #1101, #1100, #1094, #1079, #1078, #1074, #1071, #1067

**Comment by scigeotech** [comment]
+ Chests can still be opened in forge version 14.23.1.2555. However, I still use version 14.23.1.2583 because it is required by some of my mods to use version 2571+

**Comment by cool9535** [comment]
Well, @realjackasterisk I don't have any problems with normal vanilla chests
