### ISSUE TITLE
More buffer formats needed

### ISSUE THREAD

**Issue by BruceKnowsHow** [sp614x/optifine#112]
I'm trying to add [quad-channel buffer encoding](https://github.com/BruceKnowsHow/Ebin-Shaders/commit/992a8a24b612b1539f401be69697e10e2c94493d#diff-cecbbb10c0a7dc0a86848975c6ba075f) (compress 4 8bit buffer channels into a single 32bit buffer channel). I can only figure out how to encode the first 3 buffers, because the only 32bit buffer formats are floating point, which dedicate 8 bits to exponents, which I don't know how to encode/decode.

It would be convenient (and perhaps more efficient) if I could just store the encoded buffer channel in a 32bit integer format, or whatever the non-floating point faux-float-integer hybrid types the 8bit and 16bit buffer settings have (they have a range 0.0 to 1.0, so they don't seem to be real floating point values).

[This](https://www.opengl.org/wiki/Layout_Qualifier_%28GLSL%29#Image_formats) might be helpful.

**Comment by sp614x** [comment]
Curently the supported formats are: 

A. Normalized int
  GL_R8
  GL_RG8
  GL_RGB8
  GL_RGBA8
  GL_R16
  GL_RG16
  GL_RGB16
  GL_RGBA16

B. Floating point
GL_R32F
GL_RG32F
GL_RGB32F
GL_RGBA32F

Is GL_RGBA32I or GL_RGBA32UI the one you need?

**Comment by sp614x** [comment]
Added support for:

A. Integer
GL_R32I
GL_RG32I
GL_RGB32I
GL_RGBA32I

B. Unsigned integer
GL_R32UI
GL_RG32UI
GL_RGB32UI
GL_RGBA32UI

Coming in preview B5 for 1.9.

**Comment by BruceKnowsHow** [comment]
RGBA32UI Is exactly what I need in this case.

Also, assuming "snorm" means signed normalized int (float ranging from -1.0 to 1.0), snorm formats would be conveniant for storing normals, which have to be converted from signed to unsigned very frequently. This would be especially beneficial if we could use snorm for shadow map textures, so that we wouldn't have to convert shadow-view-normals for every GI sample (this would probably save 1 MAD operation per sample, not a huge deal but it would be nice).

**Comment by sp614x** [comment]
Added SNORM formats.

Texture Formats
===============
1. 8-bit normalized
 GL_R8
 GL_RG8
 GL_RGB8
 GL_RGBA8
2. 8-bit signed normalized
 GL_R8_SNORM
 GL_RG8_SNORM
 GL_RGB8_SNORM
 GL_RGBA8_SNORM
3. 16-bit normalized
 GL_R16
 GL_RG16
 GL_RGB16
 GL_RGBA16
4. 16-bit signed normalized 
 GL_R16_SNORM
 GL_RG16_SNORM
 GL_RGB16_SNORM
 GL_RGBA16_SNORM
5. 32-bit float     
 GL_R32F
 GL_RG32F
 GL_RGB32F
 GL_RGBA32F
6. 32-bit integer
 GL_R32I
 GL_RG32I
 GL_RGB32I
 GL_RGBA32I
7. 32-bit unsigned integer 
 GL_R32UI
 GL_RG32UI
 GL_RGB32UI
 GL_RGBA32UI

**Comment by sp614x** [comment]
The new formats are added in OptiFine 1.9.0_HD_U_B5_pre.
