### ISSUE TITLE
[Updated] 1.7.10 FairyLights Crash

### ISSUE THREAD

**Issue by Matthysse** [sp614x/optifine#1121]
The last version for play with FairyLights mod and Optifine is Optifine D6, since this version of optifine all new one are not compatible with FairyLights and the autor of fairy lights don't want to fix thix problem.

**Comment by sp614x** [comment]
Moe details needed:
- crash report
- error log (game output)
- how to reproduce

**Comment by Matthysse** [comment]
How to reproduce: Use the latest version of optifine (E7) and the latest version of fairylights (1.4.0) for minecraft 1.7.10. The latest version of optfine that work with FairyLight is D6.

Crash report:

[crash-2018-01-10_18.52.12-client.txt](https://github.com/sp614x/optifine/files/1619908/crash-2018-01-10_18.52.12-client.txt)

Logs:

[fml-client-latest.log](https://github.com/sp614x/optifine/files/1619915/fml-client-latest.log)

**Comment by sp614x** [comment]
FairyLights crashes here: https://github.com/pau101/Fairy-Lights/blob/1.7.10/src/main/java/com/pau101/fairylights/client/renderer/ConnectionRenderer.java#L57

It tries to find the field `EntityRenderer.currentFrustum` which is not part of vanilla or OptiFine. 
No idea where this field should come from or why it is missing.

**Comment by sp614x** [comment]
Maybe FairyLights tries to patch the EntityRenderer.renderWorld() at the place where the Frustum is created.

Here is how this place has changed between D6 and D7:

![image](https://user-images.githubusercontent.com/16635441/34792355-0d19afd4-f648-11e7-8a2e-61d0f077c48b.png)

**Comment by sp614x** [comment]
This should be fixed in FairyLights, OptiFine can't change how the code at this place works.

**Comment by pau101** [comment]
This is an issue I receive reports on fairly regularly and it is not something I'm going to be releasing a patch for. I simply can't hold the routine to update old asm of mine for other mod releases to maintain compatibility after I've stopped development on that Minecraft version.

**Comment by sp614x** [comment]
The problem can't be fixed in OptiFine as FairyLights is the one actively patching the class.
