### ISSUE TITLE
1.12.2 Chest opening bug

### ISSUE THREAD

**Issue by BlackSmeim** [sp614x/optifine#1122]
There is a bug on the new Optifine C5, C6, C7 Versions.
You cannot open chests anymore, whether they have things inside them or not.
Please fix this problem!
-BlackSmeim

**Comment by Builderb0y** [comment]
#1119, #1114, #1101, #1100, #1094, #1079, #1078, #1074, #1071, #1067

**Comment by BlackSmeim** [comment]
Are you guys working on C8 and when can i expect it?

**Comment by sp614x** [comment]
C8 is on the way.
