### ISSUE TITLE
Corners not Showing with CTM

### ISSUE THREAD

**Issue by ichbineinNerd** [sp614x/optifine#1126]
i tried all of the variants that are supposed to show corners, but they are invisible...

pack -> [here](https://drive.google.com/uc?export=download&id=1EexJ5ru_ed8PAd9VDKugu1iijFF7efyR)

![2018-01-06_12 20 32](https://user-images.githubusercontent.com/34607504/34639232-5d34abf0-f2dc-11e7-828d-50044e9c1337.png)

**Comment by sp614x** [comment]
Video Settings -> Quality -> Connected Textures -> **Fancy**

**Comment by ichbineinNerd** [comment]
oh ok. thanks
