### ISSUE TITLE
Where i can download the preview of C8? Or if i can at all.

### ISSUE THREAD

**Issue by Liberage** [sp614x/optifine#1129]
Also the Italian localization is badly done (like, in 3 minutes with google translator)

**Comment by realjackasterisk** [comment]
https://optifine.net/downloads

![image](https://user-images.githubusercontent.com/31686191/34644645-0e3f15fe-f2ef-11e7-8389-5715a895ffc1.png)

**Comment by Liberage** [comment]
@realjackasterisk OH well thanks
