### ISSUE TITLE
1.12.2 Vanilla Chests will not open

### ISSUE THREAD

**Issue by ClaudiusMinimus** [sp614x/optifine#1135]
With either OptiFine 1.12.2 HD U C7 or OptiFine 1.12.2 HD U C6 vanilla chests and trapped chests will not open. All other chests seem to work fine.

Running forge-14.23.1.2585 and the following 133 mods : 

netherportalfix@5.3.13
creativecoredummy@1.0.0
mobdismemberment@7.0.0
clayspawn@1.12a
multistorage@1.4.7
mtrm@1.2.2.30
incontrol@3.6.5
modnametooltip@1.10.0
reborncore@3.6.1.183
ctm@MC1.12-0.2.3.9
controlling@3.0.5
cookingforblockheads@6.3.17
reauth@3.5.2
mputils@1.4.1
rangedpumps@0.5
bookshelf@2.3.518
forgelin@1.6.0
darkutils@1.7.181
betterbuilderswands@0.11.1
morpheus@1.12-3.3.2
waterstrainer@3.2.0
jeresources@0.8.6.28
mcmultipart@2.4.1
shetiphiancore@3.5.5
nmsot@1.2.1-mc1.12
mob_grinding_utils@0.3.4
twilightforest@3.5.263
storagedrawersextra@@VERSION@
tinkertoolleveling@1.12-1.0.3.DEV.56fac4f
torchmaster@1.6.1.53
ambientsounds@2.0.0
crafttweakerjei@2.0.0
endertanks@1.6.3
openglider@@VERSION@
biomesoplenty@7.0.1.2302
valkyrielib@1.12.2-2.0.6b
soulshardstow@1.12-2.7.4-53
reccomplex@1.4.7
aromabackup@2.1.1.3
botania@r1.10-352
llor@1.1.4-mc1.12
customspawner@3.11.3
resourceloader@1.5.3
trackapi@1.0
actuallyadditions@1.12.2-r126
roguelike@1.8.0
littletilescore@1.0.0
mocreatures@12.0.3
ic2@2.8.16-ex112
topaddons@1.12.2-1.2.1
backpacks16840@3.4.2
elevatorid@1.3.5
FML@8.0.99.99
customnpcs@1.12
aromabackuprecovery@2.1.1.3
environmentaltech@1.12.2-2.0.6b
immersiverailroading@0.4.2
moreoverlays@1.13
nice@0.2.0
badwithernocookiereloaded@1.12.2-2.12
codechickenlib@3.1.5.331
armorplus@1.12.2-11.9.2.32-beta
quantumstorage@4.4.6
getalltheseeds@1.12a
ctgui@1.0.0
simplevoidworld@1.2.0.9
jei@4.8.5.138
ftbu@4.2.4
ivtoolkit@1.3.3-1.12
waystones@4.0.20
mcp@9.42
journeymap@1.12.2-5.5.2
furnus@2.1.5
appliedenergistics2@rv5-stable-4
notenoughwands@1.6.0
naturescompass@1.5.1
aroma1997core@1.3.0.2
chameleon@1.12-4.1.3
inventorytweaks@1.63+release.109.220f184
harvestcraft@1.12.2c
ftbl@4.2.5
joypadsplitscreenmod@1.12.0-0.22
bedbugs@@VERSION@
ichunutil@7.1.4
crafttweaker@4.0.12
forge@14.23.1.2585
quickleafdecay@1.2.4
chesttransporter@2.8.7
ironchest@1.12.2-7.0.34.820
variedcommodities@1.12.2
craftingtweaks@8.1.6
minecraft@1.12.2
tconstruct@1.12-2.8.1.49
earthworks@1.3.4.3
theoneprobe@1.4.19
mousetweaks@2.8
psi@r1.1-59
immersiveengineering@0.12-76
baubles@1.5.1
creativecore@1.9.9
yabba@1.0.11
fw@1.6.0
rustic@0.4.7
stevescarts@${version}
mpbasic@1.3.0
sophisticatedwolves@3.12.0
extrautils2@1.0
jeiintegration@1.5.1.36
bloodmoon@1.5.2
mantle@1.12-1.3.1.21
quark@r1.4-121
usefulnullifiers@1.4.1
gravestone@1.10.0
moreplayermodels@1.12.2
autoreglib@1.3-15
keywizard@1.10.2-1.5
storagedrawers@1.12-5.2.5
natura@1.12-4.3.1.35
opframe@1.4.0
appleskin@1.0.9
chisel@MC1.12-0.1.1.26
limelib@1.7.9
recipehandler@0.9
flatcoloredblocks@mc1.12-6.6
foamfix@@VERSION@
thedragonlib@1.12.2-5.2.0
chiselsandbits@14.11
morphtool@1.2-16
littletiles@1.5.0
forestry@5.7.0.231
unlimitedchiselworks@0.1.9
defaultoptions@9.2.5
xpbook@0.0.3-beta

**Comment by Builderb0y** [comment]
#1122, #1119, #1114, #1101, #1100, #1094, #1079, #1078, #1074, #1071, #1067

**Comment by sp614x** [comment]
Fixed in preview C8 for 1.12.2.

**Comment by ClaudiusMinimus** [comment]
Thank you!

**Comment by jesserobbins98** [comment]
Im glad in wasn't the only one.
