### ISSUE TITLE
autosave interval

### ISSUE THREAD

**Issue by jesserobbins98** [sp614x/optifine#1136]
would you beable to add a off optionfor the auto save? cause i have a low end computer and it freezes up for around 10 minutes every half hour so could you please put in a off option?
  
p.s. this is from prior experience of using autosave i dont think c7 autosave is working properly cause i havent frozen up for 10 minutes or crashed.

**Comment by sp614x** [comment]
A freeze or crash should not be caused by auto-save.
It is most probably due to memory problems or other programs running on the computer.

**Comment by jesserobbins98** [comment]
its not gonna hurt to add an off to autosave though is it?
