### ISSUE TITLE
[Optifine_1.12.2_HD_U_C8.jar] Error while opening enderchests in any minecraft world or server

### ISSUE THREAD

**Issue by cool9535** [sp614x/optifine#1139]
So I get this following strange error, while using optifine in my personal modpack of course for personal usage only, using the Twitch Desktop App I don't know why it does that:

`.Minecraft | Unreported exception thrown! java.lang.AbstractMethodError: net.minecraft.block.state.BlockStateContainer$StateImplementation.doesSideBlockChestOpening(Lnet/minecraft/world/IBlockAccess;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/util/EnumFacing;)Z 	at net.minecraft.block.BlockEnderChest.func_180639_a(BlockEnderChest.java:103) 	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:423) 	at PlayerControllerOF.func_187099_a(PlayerControllerOF.java:96) 	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1577) 	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2252) 	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2018) 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1806) 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096) 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) 	at net.minecraft.client.main.Main.main(SourceFile:123) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.lang.reflect.Method.invoke(Method.java:483) 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)`

I have already tried disabling my other mods just to see if it worked, that didn't do any difference, I even tried disabling/enabling a shader and even tried remaking the whole mod profile, still no difference

Here is my full crash report:
[crash-2018-01-09_20.50.03-client.txt](https://github.com/sp614x/optifine/files/1616473/crash-2018-01-09_20.50.03-client.txt)

**Comment by Builderb0y** [comment]
#1135, #1122, #1119, #1114, #1101, #1100, #1094, #1079, #1078, #1074, #1071, #1067

**Comment by sp614x** [comment]
Fixed in preview C8.

**Comment by cool9535** [comment]
Well @Builderb0y I don't have any problems with normal chests
