### ISSUE TITLE
Normal map fallback for banners

### ISSUE THREAD

**Issue by MathGeniusJodie** [sp614x/optifine#1140]
The fallback if there is no normal map texture is vec4(0,0,0,1) instead of vec4(0.5,0.5,1,1) like it should, making normals broken on banners, this might also affect other blocks

**Comment by sp614x** [comment]
Other entities or tile entities affected (mobs, signs, chests, etc)?

**Comment by sp614x** [comment]
The text default normals should also be wrong:
![image](https://user-images.githubusercontent.com/16635441/34824877-92ab8068-f6d0-11e7-99b1-2080ad3197cc.png)

**Comment by sp614x** [comment]
Also the player skin and cape textures:

![image](https://user-images.githubusercontent.com/16635441/34825001-0e1fc056-f6d1-11e7-97b6-b39ea7fd143f.png)

**Comment by sp614x** [comment]
Same with horses

![image](https://user-images.githubusercontent.com/16635441/34825510-1342f34e-f6d3-11e7-8545-f7d5846f6e24.png)

**Comment by sp614x** [comment]
Fixed banner and horse normals, showing custom normals from RP:

![image](https://user-images.githubusercontent.com/16635441/34828501-0afcd6ae-f6de-11e7-9434-59d163266eda.png)

**Comment by sp614x** [comment]
Fixed player skin and cape:

![image](https://user-images.githubusercontent.com/16635441/34829972-baaf35f2-f6e2-11e7-916d-2be801e7ad34.png)

**Comment by sp614x** [comment]
The multi-layer mobs (spider, enderman) still have problems

![image](https://user-images.githubusercontent.com/16635441/34831412-2abe460e-f6e7-11e7-96d0-9e2184ba10eb.png)

**Comment by sp614x** [comment]
Updated preview C9 for 1.12.2 
- fixed normal maps for banner, horse and player models
