### ISSUE TITLE
[1.12.2] Cloud Height slider not working with forge

### ISSUE THREAD

**Issue by Managarmr719** [sp614x/optifine#1141]
The cloud height slider doesn't work when using optifine together with forge.

Optifine: 1.12.2_HD_U_C8
Forge: 14.23.1.2587

**Comment by sp614x** [comment]
Forge #2527 and newer use a custom cloud renderer which breaks several OptiFine features.

Changelog: http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.0.2527/forge-1.12.2-14.23.0.2527-changelog.txt
Commit: https://github.com/MinecraftForge/MinecraftForge/commit/9c7538db8de0e385f816c4be37b829673a49a5d9#diff-af08d970ea2475e6cb55f2f8c14edefb

**Comment by sp614x** [comment]
Updated preview C9 for 1.12.2
- fixed Forge cloud renderer breaking cloud height and shader clouds
