### ISSUE TITLE
Cannot turn on "Smooth Lighting" on, from C7 and greater

### ISSUE THREAD

**Issue by Liberage** [sp614x/optifine#1142]
If i do that i can only select "minimal" but then it resets to "no"

**Comment by sp614x** [comment]
Works for me, both with or without Forge.
Error log (game output), installed mods, resource pack, shaders?

**Comment by Liberage** [comment]
@sp614x I don't have really (i have waving plants, but is not the cause because i removed it), but when removing optifine, i can turn it on so other mods seem not the fault

**Comment by sp614x** [comment]
This probably some other mod which is conflicting with OptiFine.
The error log (game output) may have more information.

**Comment by Draylynn** [comment]
@Liberage Are you using the Quark mod?
[In-Game] ESC menu > Mod Options > find Quark and click on it > Config (lower left) > Experimental settings > Coloured Lights > Disable.
