### ISSUE TITLE
what's the difference between sides and all in faces?

### ISSUE THREAD

**Issue by xAphex** [sp614x/optifine#1143]
https://github.com/sp614x/optifine/blob/61db8c07261ad9a3f93821ea7dfb61a8eac14872/OptiFineDoc/doc/ctm.properties#L114-L115

in **faces**, what's the difference between **sides** and **all**?

if **sides** means "north south east west", then that means it's **all**, right?

i'm just confused, this is not an issue.

**Comment by realjackasterisk** [comment]
`sides` = north, south, east, west.

`all` = north, south, east, west, **up, down**

**Comment by MisterQuiggly** [comment]
Sides doesnt do the top or the bottom. all does everything

**Comment by xAphex** [comment]
thanks for the reply's guys, appreciate it.

so i cant use **all** for glass panes right?

**Comment by sp614x** [comment]
the glass panes have different textures on the sides so you can use `matchTiles` to target the front or the side of the pane.
https://github.com/sp614x/optifine/blob/61db8c07261ad9a3f93821ea7dfb61a8eac14872/OptiFineDoc/doc/ctm.properties#L39
