### ISSUE TITLE
Portal particles shown even when disabled

### ISSUE THREAD

**Issue by Nessiesson** [sp614x/optifine#1146]
Nether portals emit particles even when they're disabled in the settings (`Video Settings... -> Animations... -> Portal Particles: OFF`).

I am running the latest (`1.12.2_HD_U_C8`) vanilla version of OptiFine, but it seems to have the same behaviour in `1.12_HD_U_C7`.

**Comment by sp614x** [comment]
Updated preview C9 for 1.12.2
 - fixed option Portal Particles (#1146)
