### ISSUE TITLE
Grass CTM Bug!

### ISSUE THREAD

**Issue by shinkuan** [sp614x/optifine#1147]
When I tried to make a grass connected texture, I found a problem, the way that glass connect isn't connecting as the way it should be.  I did everything CTM told me to do, and I triple checked everything, but the pack still work like this:
[https://i.imgur.com/UMS9ezE.jpg](url)

And when I tried to fix the problem, I tried to use the same texture as the diamond block aside there and see if it will work well, but it appear like this:
[https://i.imgur.com/gMmbzJD.jpg](url)

The Texture Pack:
[https://i.imgur.com/0b0ErF2.png](url)
[https://i.imgur.com/IR9zMku.png](url)

TP Download Link:
[https://drive.google.com/open?id=1h1QoX8VJX1K9JxIQmxGM0mmxxfHtZQVn](url)

**Comment by shinkuan** [comment]
@sp614x thx

**Comment by realjackasterisk** [comment]
1. Please be patient.
2. Your image links are broken.

**Comment by shinkuan** [comment]
Sorry for the tag. Here is the link https://imgur.com/a/ezImZ

**Comment by sp614x** [comment]
The grass block model uses alternative (randomly rotated) textures. You should fix the model to use one fixed top texture. Then check if Natural Textures is also not rotating the top texture.
When the block model and the Natural Textures are OK it should work.

**Comment by shinkuan** [comment]
Thanks! I turned off the Alternate blocks and it worked!
