### ISSUE TITLE
[Suggestion] Force face culling

### ISSUE THREAD

**Issue by realjackasterisk** [sp614x/optifine#1148]
Minecraft seems to have an odd way of handling face culling for block models. When it's told to do so, it'll only try to determine if a face *should* be culled. This is hardly reliable.

Optifine should give block modelers an option to **force** culling on faces, maybe though a new key in the block model JSON. Example:

```json
"north": {
	"uv": [0, 0, 16, 16],
	"texture": "#texture",
	"cullface": "north",
	"forcecull": "north"
}
```

This would help greatly with model optimization, and potentially give some modelers a new trick to play with.

**Comment by sp614x** [comment]
A model face is automatically culled if the face is located on a full cube side and the neighbour block is opaque full cube. 
Faces which are not located on a full cube side are not culled as they are still visible even when the neighbour block is opaque full cube.

**Comment by sp614x** [comment]
OptiFine is generally not changing the vanilla models, so it can't extend the JSON format with new fields.
