### ISSUE TITLE
Dynamic Resolution Scaling

### ISSUE THREAD

**Issue by supersim3** [sp614x/optifine#1149]
The frame rate of Minecraft can change significantly depending on the surroundings. Jungles with extra leaves and shader effects like water can drop FPS by 20%.

The option to vary resolution would be preferable to the halving of frame rate with vsync or screen tearing without vsync.

**Comment by sp614x** [comment]
Which resolution should be changed?

**Comment by supersim3** [comment]
The screen resolution. I don't know about the other resolutions you are
talking about. Would it be more effective to change another one or multiple
ones at the same time?

**Comment by mindforger** [comment]
that sounds almost impossible, you would have to reload the screen when changing resolution! that would be WAY more annoying to have this "switch" happening just because my framerates are dropping

how about some sort of adaptive details level ... dunno, reduce texture resolution when framerate heavily drops or maybe some adaptive limitation of renderdistance or other rendering stuff that can be changed on the fly, could be usefull for weaker systems or laptops with instable computing speed due to thermal regulation

**Comment by supersim3** [comment]
Is reloading the screen a limitation of the Minecraft renderer? Lots of
recent games change resolution frame to frame based on render loads.

On 16 Jan 2018 22:33, "mindforger" <notifications@github.com> wrote:

that sounds almost impossible, you would have to reload the screen when
changing resolution! that would be WAY more annoying to have this "switch"
happening just because my framerates are dropping

how about some sort of adaptive details level ... dunno, reduce texture
resolution when framerate heavily drops or maybe some adaptive limitation
of renderdistance or other rendering stuff that can be changed on the fly,
could be usefull for weaker systems or laptops with instable computing
speed due to thermal regulation

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/sp614x/optifine/issues/1149#issuecomment-357978112>,
or mute
the thread

**Comment by mindforger** [comment]
huh? What games are those? I don't know any that could!

**Comment by supersim3** [comment]
From a quick search; titanfall 2, assassin's creed origins, shadow of war
and unreal engine 4. These all use dynamic resolution scaling on pc. Most
console games do now too, because of their low powered chips.

**Comment by 5t0rmr1d3r** [comment]
As fahr as i know they don't change/reduce the screen resolution. The thing that is changed is the quality of the rendering. After that they scale the rendered scene up to the screen resolution.

**Comment by mindforger** [comment]
@supersim3 what @5t0rmr1d3r described is the mechanic i also only know and thats what i asked for in my post

**Comment by sp614x** [comment]
Changing the screen resolution while the game is running is not possible.
Changing the render quality depending on the frame rate is only possible with a very specialized shader. 
By default Minecraft does not use shaders so the idea can't be implemented.
