### ISSUE TITLE
[Question] How to install Optifine and forge ?

### ISSUE THREAD

**Issue by conetopia** [sp614x/optifine#1150]
New .minecraft folder
Installed forge 1.7.10 - 10.13.4.1614
I noticed you guys don't have mod downloads.. you have installer.exe's for optifine.
I tried 1.7.10 HD u E3 , D8,D7,D6,D4...
I used the installer on each type.

Forge has its own installer... that generates .minecraft/versions/forge w/e
so i dragged 1 at a time... and tried the optifine mod.. put it in the folder .minecraft/mods 

Double clicked minecraft.exe , ran the forge profile.
Nothing ....

I tried technic launcher... search box...
optifine forge

Result 1.7.10 forge & optifine
technic launcher pack was outdated, but i was able to type the website in.
http://www.mediafire.com/file/ncidy52rsd6hiv6/Modpack+1.7.10.zip

downloaded that...
apparently ... his version of 1.7.10 optifine HD_U_D4....
is different, than the 1.7.10 optifine HD_U_D4.... that is available for download

http://optifine.net/downloads
Not sure why, or if b/c the installer.. there is a dependency missing maybe or something???

b/c when i go to run forge... anything off the optifine.net website doesn't actually load up... 
Optifine installer.jar or the optifine mod.jar ( yes im putting them in the mods folder 1 at a time)

But when i use the version from this dudes pack... it loads right up !!!!! first try ! optifine and forge both listed BOOOM ! no errors? how ??? there supposed to be the same exact file?????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????

Can someone tell me if the file from this dudes modpack version of optifine mod had something added or changed to make it work????

i just don't understand how his optifine mod name is the exact same, and exact size.. but 
his works and the official website one doesn't?

---
anyways my problem, is that even with his version... there is no shaders button for shaderpack menu?
I am attempting to run Seus renewed 1.0.0 on mc 1.7.10
Optifine installers from official website work... Just don't work with forge even though they say they are compatible in the changelog.

so maybe im supposed to drag something out of the forge.jar into the optifine.jar? idk
so much has changed in the last year with the mc launcher.

Goal is to run 1.7.10 forge + optifine , to play on a modded server.

( also running windows 10 ) not sure if it matters. Any Questions just ask.

**Comment by Dushess** [comment]
Commonly need to install game version + forge platform, then put optifine jar into mods folder.

**Comment by sp614x** [comment]
OptiFine can run as normal Forge mod. Just put it in the "mods" folder and it would be loaded.
Only OptiFine JARs downloaded from http://optifine.net are guaranteed to work.
