### ISSUE TITLE
[Question/Semi-suggestion?] Custom lightmaps per block

### ISSUE THREAD

**Issue by realjackasterisk** [sp614x/optifine#1151]
~~This is probably a stupid question, but~~ would it be possible to create lightmaps for different blocks?
For example, having a different lightmap for Lava, Torches, Redstone Torches, Redstone Lamps, Beacons, etc.

**Comment by sp614x** [comment]
Different lightmaps for different light sources is not possible.
There are only two types of light in MC: sun light and block light (torches, lava, redstone lamps, etc)
