### ISSUE TITLE
1.7.10 mods not allowing optifine shaderpacks?

### ISSUE THREAD

**Issue by conetopia** [sp614x/optifine#1154]
Installed fresh .minecraft
Ran mc 1.7.10
Used the forge 1.7.10 1614 installer & ran it.
Placed optifine HD U 3 in mods folder.
Ran it, everything worked great. Seus Shaders worked ect.

Added all of the mods from my 7 friends modpack.
Instant crash, read the crash report, googled it.
Apparently BiblioCraft and Fast craft don't like the new optifine, and caused the crash.
Downgraded to optifine HD_U_D6.

Went to video settings, Shaders button is gone.
I seen an other... button , and no shaders button listed in there either.

Is there a mod or a couple mods, that are preventing that shaders button to not show?
Any suggestions?

![c629ee0063b5cd026806384f2a85d715](https://user-images.githubusercontent.com/4310295/35083018-73f26116-fbe2-11e7-8e3e-4073c23280e1.png)

**Comment by sp614x** [comment]
OptiFine D6 for 1.7.10 don't suppot shaders.
Support for shaders was added in OptiFine D7 for 1.7.10.
