### ISSUE TITLE
[Shaders] Custom uniforms: matrix access and vector uniforms

### ISSUE THREAD

**Issue by sp614x** [sp614x/optifine#1155]
Matrix components should be accessible like `matrix.2.3`.
Vector uniforms can use a pack function `vec3(x, y, z)`.

**Comment by MathGeniusJodie** [comment]
omg omg omg hype!

**Comment by sp614x** [comment]
OptiFine 1.12.2_HD_U_C9_pre
 - added vector custom uniforms (#1155)
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.properties#L343
 - added matrix access for custom uniforms (#1155)
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.properties#L283
