### ISSUE TITLE
[Shaders] Shaders to require minimum OptiFine version

### ISSUE THREAD

**Issue by DethRaid** [sp614x/optifine#1166]
Lots of shaders depend on features from newer optifine versions. Users with older optifine versions see horribly broken shaders, leading to a poor user experience and increased support work for shader developers. If optifine allowed shaders to specify a minimum required optifine version then optifine could warn users if they tried to use a shader with too small of an optifine version, letting users know they need to upgrade.

I'm envisioning that the shaderpack name would be greyed out an unselectable in the shaderpack selection screen. Hopering over a grayed out shaderpack would display a tooltip with the required optifine version

There could be a line in the shaderpack.properties file that specifies the required version

This change would probably be most useful if it was snuck in to older optifine versions

**Comment by realjackasterisk** [comment]
Why isn't this already a thing?

**Comment by DethRaid** [comment]
Wait actually for better compatibility with Nova I would prefer that optifine provide a list of features it supports and shaderpacks provide a little of required features, rather than everything working off if version numbers

**Comment by sp614x** [comment]
The list of features seems reasonable, but there are several problems:
- the list would be very long
- one feature may be existing in several versions, but only the last version has all the bugs fixed so the shader pack can work properly

**Comment by DethRaid** [comment]
Perhaps the bugfixes would be separate features? But that would make the list even longer. Idk, it was a thought. Using version numbers might be best

**Comment by sp614x** [comment]
OptiFine versions are not identical between MC major versions. For example OF C7 for 1.12.x is roughly equivalent to OF E7 for 1.10.x. Therefore minimum versions should be specified per major MC version.

For example:
```
optifine.version.1.12.*=C7
optifine.version.1.11.*=C7
optifine.version.1.10.*=E7
optifine.version.1.9.*=E7
optifine.version.1.8.*=I7
optifine.version.1.7.*=E7
```

**Comment by DethRaid** [comment]
I thought there might be a lot of complexity with versions because of that

**Comment by sp614x** [comment]
Added to D1.
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.properties#L65
