### ISSUE TITLE
[1.12.2] It's impossible to make a shield that blocks with CIT models

### ISSUE THREAD

**Issue by lanekrushing** [sp614x/optifine#1169]
Optifine HD C8 Ultra || Minecraft 1.12.2

These rules will successfully replace a renamed shield's model; however, when you block, the model will not change.
```
type=item
items=shield
nbt.display.Name=Myshield
model=item/myshield
```
However, these rules have no effect when used, and will show a vanilla shield:
```
type=item
items=shield
nbt.display.Name=Myshield
model.shield=item/myshield
model.shield_blocking=item/myshield_blocking
```
I also searched the internet for resource packs with "custom shields," and they suffer similar issues; either the shield does not change models when blocking, or in one case, the vanilla and custom shields were using builtin/generated, which doesn't allow 3D shields.

I believe this is a bug, but if there is a method I've overlooked please teach me. :slightly_smiling_face:

**Comment by sixfootblue** [comment]
This seems to be the case with a handful of items that use multiple .jsons files for different states. (Shields, clocks, compasses). Afaik the only multi-model predicate items you can customize properly are bows and fishing rods.

**Comment by DataCrusade** [comment]
Would like to see this fixed soon, it's the only thing stopping a friend from properly doing custom shields.

**Comment by sp614x** [comment]
Models using predicates:
- bow - implemented
- clock/compass - already using multiple textures, multiple models probably not needed
- elytra (broken) - can be configured via damage
- fishing rod - implemented
- shields - added

**Comment by sp614x** [comment]
OptiFine 1.12.2_HD_U_D2
 - added shield blocking model to CIT (#1169)
