### ISSUE TITLE
(Shaders) 32 bit integer buffer formats cause crashing

### ISSUE THREAD

**Issue by BruceKnowsHow** [sp614x/optifine#117]
So I tried out the new buffer formats, all of the 32 bit integer formats cause the following error:
[SEVERE] [Shaders] Error: Failed creating framebuffer! (Status 36054)

[Full log file](https://puu.sh/oWNg2/d0851f8662.txt)

The snorm formats do not cause a crash.

**Comment by sp614x** [comment]
The integer formats may need other sampler to be used:
- https://www.opengl.org/wiki/GL_EXT_texture_integer
- http://stackoverflow.com/questions/13041830/the-internalformat-of-texture
- https://www.opengl.org/registry/specs/EXT/texture_integer.txt

**Comment by BruceKnowsHow** [comment]
I tried converting the colortex3 declarations to usampler, no luck. I also updated to OpenGL 4.1 compatibility mode, no change whatsoever.

**Comment by BruceKnowsHow** [comment]
This might not be a big deal. It's a waste of memory/bandwidth, but that probably doesn't add up to much, and I don't think my shader will need more than the 9 encoded channels that are already possible.

**Comment by BruceKnowsHow** [comment]
Joey brought up a point, the 32bit integer buffers are probably newer, and require OpenGL 1.3+

**Comment by BruceKnowsHow** [comment]
I'm ready to close this. I moved away from 32bit buffers because they were pretty slow, and I will avoid using them in the future for that reason. I'd recommend removing the code for the new 32bit formats, because it's not working for whatever reason.

**Comment by sp614x** [comment]
I will keep the integer format parsing, it only matches strings to opengl constants and does not cause problems. Someone can find a use for them.
