### ISSUE TITLE
Glowing effect creates ghost

### ISSUE THREAD

**Issue by SlimeDog** [sp614x/optifine#1174]
Spigot 1.12.2
OptiFine 1.12.2-HD-U-C8

> /effect {playerName} minecraft:glowing 100 1

renders the player as a ghost.
![untitled](https://user-images.githubusercontent.com/17748923/35239207-b0b32498-ff64-11e7-979b-54c26ccf92e8.png)

It correctly creates the "outline" aura without OptiFine.
![untitled](https://user-images.githubusercontent.com/17748923/35239450-5eebf508-ff65-11e7-83d2-4636e10cdaed.png)

**Comment by SlimeDog** [comment]
Options > Video Settings > Performace > Fast Render:OFF masks the problem.

**Comment by okl1001** [comment]
I believe this is intentional as it butchers the frame rate on lower end computers. Or it could be a bug.

**Comment by SlimeDog** [comment]
On my higher-end computer...it's a bug. :)

**Comment by sp614x** [comment]
The spectral effect (glowing outline) is not compatible with Fast Render and with shaders. When one of them is active an alternative "ghost" effect is used as an approximation.

**Comment by mixxit** [comment]
Move options files out to fix
