### ISSUE TITLE
[1.12.2_HD_U_C8] Crash when updating a DynamicTexture...

### ISSUE THREAD

**Issue by OreCruncher** [sp614x/optifine#1175]
Forge version 2600

Pertinent code: https://github.com/OreCruncher/DynamicSurroundings/blob/master/src/main/java/org/blockartistry/lib/gfx/GeneratedTexture.java#L139.  My best guess is the crash happens on line 145 when the texture is being uploaded.

What I am doing is pre-redendering a bunch of text into a Framebuffer then moving it over to a DynamicTexture.  Without OptiFine it works.  With OptiFine some of my users are [reporting hard crashes](https://github.com/OreCruncher/DynamicSurroundings/issues/219).  The irony of all this is that this code works on my system.

I would like to make it compatible with OF if at all possible.  If I have to tweak the code on my end I am more than happy to do so.  Thanks!

(Edited for additional info and clarity)

**Comment by sp614x** [comment]
When the option Fast Render is enabled or shaders are active the Framebuffer class may not work properly.

**Comment by OreCruncher** [comment]
This a bug in Framebuffer, or a side effect of using OptiFine?

**Comment by sp614x** [comment]
The option Fast Render disables the MC framebuffer, so it is not active.
When shaders are active the framebuffer may function differently, not sure.

**Comment by OreCruncher** [comment]
Ah!  Gottcha.  I will close the issue and make some code adjustments.  Thanks!
