### ISSUE TITLE
QSU Translucency Rendering As Opaque

### ISSUE THREAD

**Issue by number65259** [sp614x/optifine#1176]
gigabit101/quantumstorage#130

Vivecraft+MC vers 1.12.2
Forge x.2583
OptiFine HD U C7

**Comment by sp614x** [comment]
Which block, screenshot with and without OptiFine?
Video Settings -> Other -> Reset ?

**Comment by number65259** [comment]
Affects the tank and item QSU. Reset video settings after taking the second screenshot but no go.

Screens from a fresh install of 1.12.2, Forge x.2583, Optifine HD U C7, 2 Other Mods: RebornCore and QSUs:
[https://imgur.com/a/ot7sC](https://imgur.com/a/ot7sC)
