### ISSUE TITLE
[1.7.10] thaumcraft golems

### ISSUE THREAD

**Issue by Fabboz** [sp614x/optifine#1177]
thaumcraft golems don't work in chunkloaded  area and far away of player render distance.
i'm sure optifine unload entity outside render distance. is possible to have a config or anything to fix that?
thx

**Comment by sp614x** [comment]
Video Settings -> Performance -> Smooth World

**Comment by Fabboz** [comment]
tryed turning on smooth world in config but only uninstalling optifine can make golem working.

**Comment by Fabboz** [comment]
also enderio powered spawner that spawn mob even if player isn't in range don't work.
carts work good.
all tested with tesseracts.
