### ISSUE TITLE
Custom VertexData (x,y,z) and shaders

### ISSUE THREAD

**Issue by TalosDx** [sp614x/optifine#1178]
With Optifine and shaders
https://imgur.com/a/28tYY
With optifine no shaders
https://imgur.com/Vv558ys (bad internet connection, and many images no uploading)
я просто генерирую модель на основе blockpos, и меняю в VertexData с 0 до 3 (+(7*n))
То есть:
`                    list.get(y).getVertexData()[n * 7] = Float.floatToRawIntBits((float) (vertex[3].x - d0));
                    list.get(y).getVertexData()[n * 7 + 1] = Float.floatToRawIntBits((float) (vertex[3].y - d1));
                    list.get(y).getVertexData()[n * 7 + 2] = Float.floatToRawIntBits((float) (vertex[3].z - d2));`
When d0-d2:
`            double d0 = (double) posIn.getX() + vec3d.x;
            double d1 = (double) posIn.getY() + vec3d.y;
            double d2 = (double) posIn.getZ() + vec3d.z;`
On vanilla works fine and I do not understand what the problem is, even though the head of the wall is knocked out.
I try to understand the problem for about 3 months and English is not my own: |
And I already asked many people, but they are not familiar with either OpenGl or Optifine.

**Comment by sp614x** [comment]
The shaders use extended vertex format (double size), each vertex takes 56 bytes instead of 28 (vanilla).

**Comment by TalosDx** [comment]
GOD'S THANKS!
Of course you are, not God; D
