### ISSUE TITLE
lit particles use gbuffers_textured, instead of textured_lit

### ISSUE THREAD

**Issue by BruceKnowsHow** [sp614x/optifine#118]
I can't think off the top of my head of any particles that aren't lit, but it seems like all particles are handled by gbuffers_textured.

The obvious particles I've noticed so far are broken-block-particles, and rain droplets.

**Comment by sp614x** [comment]
The particle rendering code looks like this:

            this.enableLightmap();
            this.mc.mcProfiler.endStartSection("litParticles");
            // Shaders
            Shaders.beginLitParticles();
            //  
            effectrenderer.renderLitParticles(entity, partialTicks);
            RenderHelper.disableStandardItemLighting();
            this.setupFog(0, partialTicks);
            this.mc.mcProfiler.endStartSection("particles");
            // Shaders
            Shaders.beginParticles();
            //  
            effectrenderer.renderParticles(entity, partialTicks);
            // Shaders
            Shaders.endParticles();
            //
            this.disableLightmap();
The names "particles" and "litParticles" come from the vanilla profiler sections.
The litParticles use fxLayer 3, currently these are:
- FootStep - textures/particle/footprint.png
- LargeExplode - textures/entity/explosion.png
- ParticleEmitter - not rendered
- Pickup - item pickup effect
- SweepAttack - the 1.9 sword sweep attack
- MobAppearance - elder guardian ghost image

**Comment by BruceKnowsHow** [comment]
I'm not sure I understand. Are the particles I'm having issues with (broken-block-particles, rain droplets, etc...) considered litParticles? If not, would it be possible to make them render as litParticles? Because they (at least broken-block-particles) do recieve lightmaps.

**Comment by sp614x** [comment]
All the particles are rendered with lightmap, otherwise they would glow in dark caves.
The lit particles should receive the standard entity/block lighting (down: 0.5, up=1.0, north/south: 0.8, east/west: 0.6). This is implemented with 2 opengl lights.
Currently in vanilla the standard entity/block lighting is NOT turned on for lit particles so they render identical to the normal particles.

**Comment by BruceKnowsHow** [comment]
I guess I just don't see what the need is for the distinction.

The reason this came up is because I've only implemented texture_lit so far, and it's a bit irritating having particles fall back to gbuffers_basic. It's not a serious issue, it'll just go away as soon as I add more gbuffers (which will happen whenever I'm reasonably confident I'll never need to edit them again).

**Comment by sp614x** [comment]
You can implement only "gbuffers_textured" and textured_lit will automatically use it (fallback).
The reason for the split is historical, in previous versions the lit particles were rendered differently.
If the programs are merged now, then some shaderpacks may stop working properly.

**Comment by BruceKnowsHow** [comment]
That solution works perfectly, thanks.
