### ISSUE TITLE
Written usage permission?

### ISSUE THREAD

**Issue by PulzHF** [sp614x/optifine#1188]
Greetings, wondering if I'm able to request permission to use your fine mod in my modpack - The New Tekkit Classic.
I have around 200k runs and 43k downloads to date:
https://www.technicpack.net/modpack/tc-redux.786294

If not, I still wish you the best. I've been a keen supporter of the mod for many years now.

Thanks.

**Comment by sp614x** [comment]
Sorry, no.

**Comment by PulzHF** [comment]
No worries, I'll just look into using Fastcraft or BetterFPS. You might want to add mention of your 'required permission' to the main website, maybe on the downloads page and especially on your FAQ. I only removed Optifine from my pack yesterday after a user pointed me to the original Forum post.

**Comment by mindforger** [comment]
The website FAQ really should contain a hint that the redistribution (and make clear that this is not only modpack distribution) requires permission

i was looking everywhere and only got it from an article about "why is optifine not available in certain modpack" (information seems outdated but is the only hint)
