### ISSUE TITLE
CTM Glass Panes only work one way while using resource pack.

### ISSUE THREAD

**Issue by ignamiranda** [sp614x/optifine#1189]
My resource pack doesn't edit any glass assets at all but whenever I use it this happens: https://imgur.com/a/uKai6

Both of these pics are using the resource pack, just from different sides of the window. This doesn't happen when I don't use the pack but I don't know why it does when I do use it. I even did a search for "glass" in my pack files and deleted all.

The problem doesn't happen with full glass blocks.

**Comment by MisterQuiggly** [comment]
This is a bug I've noticed for a while. No idea what causes it. Happens to me as well.

**Comment by sp614x** [comment]
Resource pack link?

**Comment by ignamiranda** [comment]
[Here you go](https://drive.google.com/open?id=1hN-UMCP3NYMZbz8hdaygUYj2UqSEDJ7K). Thanks for taking a look.

**Comment by sp614x** [comment]
The resource pack has a custom pane model `assets/minecraft/models/block/pane_side.json`.
The glass pane model `glass_pane_side.json` uses `block/pane_side.json` as parent.
OptiFine fixes the vanilla pane models so that CTM can work properly and the resource pack overwrites the fix.

**Comment by sp614x** [comment]
Then you should remove the glass pane models from the resource pack:
- assets/minecraft/models/block/pane_noside.json
- assets/minecraft/models/block/pane_noside_alt.json
- assets/minecraft/models/block/pane_side.json
- assets/minecraft/models/block/pane_side_alt.json
