### ISSUE TITLE
Updated to Preview C9, everthing that used method "random" no longer works.

### ISSUE THREAD

**Issue by MisterQuiggly** [sp614x/optifine#1191]
Version 1.12.2
All information in title.
No mods

**Comment by MisterQuiggly** [comment]
Fixed, I guess? Apparently we are required to put randomLoops in the properties file. It said default 0 so I guess that means it doesn't do any at all. I think default should be 1?

**Comment by sp614x** [comment]
The property `randomLoops` is used to change the pattern of the random distribution when several random overlay layers are put on top of each other so they don't use the same pattern.
Value 0 is the classic random pattern, higher values may indeed appear to be less random.

Updated preview C9 for 1.12.2
- fixed `randomLoops` default value to be 0
