### ISSUE TITLE
Freezing Players and Lag

### ISSUE THREAD

**Issue by AngelCake37** [sp614x/optifine#1198]
When ever I go onto servers (Hypixel,Factions,etc.) My game lags A LOT. This has only happened on hypixel so far, but people freeze for 5-10 seconds. Also I walk/place blocks and its like I get set backward and I am in the same place I was or the blocks are gone!(this happens on all servers) 
When I go to single player worlds i do not know if this happens because I can't even move. When I check the fps it is either 10 or under. Also, on multiplayer and single player I freeze for 7 seconds and can't move. I do have forge installed but no mods because forge keeps crashing. 
~~~
My computer is a Toshiba made in 2006 running on windows vista. Old graphics card and a bit slow.

**Comment by sp614x** [comment]
You can try running OptiFine without Forge.
Also decrease render distance and check with VBOs ON or OFF.

**Comment by sp614x** [comment]
If your computer has not enough RAM (2GB or less) you should decrease the memory allocated to Minecraft. For lower render distances 400 or 500 MB should be enough.
