### ISSUE TITLE
Grass / Mycelium Bug

### ISSUE THREAD

**Issue by Jazumes22** [sp614x/optifine#1201]
In optifine 1.12.2, there is an issue with grass and mycelium and the way it spreads. Grass and mycelium can spread underwater without suffocating, which is a minecraft vanilla bug. If you could fix this, that would be awesome because its really annoying that this happens.

![2018-02-04_10 21 27](https://user-images.githubusercontent.com/36134555/35779963-1923fb22-09a3-11e8-848f-8b0dc7e1bec6.png)

**Comment by KKMNNOIR** [comment]
Is Clear Water ON? If it is ON it should be solved by turning it OFF.

**Comment by Jazumes22** [comment]
Thank you! my question is was this intentional?

**Comment by Brottweiler** [comment]
Usually the water is too dark for grass to grow, but clear water makes the light level bright enough. So it's not intentional that grass is supposed to grow under water, but that's what will happen since the water is not dark enough.

**Comment by sp614x** [comment]
This is a side effect of Clear Water as the grass growth is linked to the light level. Grass doesn't check if the block above is water or not. Some people like the underwater grass as it looks like algae. This is not easy to be fixed.
