### ISSUE TITLE
Custom Gui BUG

### ISSUE THREAD

**Issue by IMerlin1009I** [sp614x/optifine#1204]
I tried to add an custom texture to an anvil gui based on its height... this works fine when i place the anvil at the specific location.

But here is the problem:
I open an AnvilGUI with packets when I click an specific block, and set the location to the height set in the custom gui properties but the texture wont show up... when i debug in console there is no difference between an Inventory which is opened, when i actually open an anvil at the height (which work) to the Inventory my plugin opens both have the same type and the same location...

Here is the weird side of the bug when I place my custom block to open the gui at the height I specified, it works... so it seems optifine dont uses the actual inventory location but the location you last clicked on...

Why it would be nice if that get fixed:
So you could create custom guis via plugin and set the height for example to 250 so it dont interfere with other inventorys

Thanks in advance,
Merlin

**Comment by ZenIsBestWolf** [comment]
Closing in favor of #7671
