### ISSUE TITLE
Fix midcoord on lava

### ISSUE THREAD

**Issue by MathGeniusJodie** [sp614x/optifine#1205]
I use midcoord to get the tilesize of textures on the atlas
`tilesize = abs( gl_MultiTexCoord0.xy - mc_midTexCoord.xy ) * 2.;`
I use the tile size to wrap textures around for pom, this works for everything except lava
![2018-02-08_19 24 59](https://user-images.githubusercontent.com/26694627/36005557-41402f66-0d06-11e8-96c5-2322b768d33a.png)
if I set tilesize to a hardcoded number (in this case 1./32.) lava looks fine
![2018-02-08_19 24 47](https://user-images.githubusercontent.com/26694627/36005582-5a07fbf0-0d06-11e8-9fea-e2c956a58ed1.png)

I use this to wrap the texture btw
`	vec2 wrapTexture(vec2 p){
		return round( (midCoord - p ) / tileSize ) * tileSize + p;
	}`

**Comment by MathGeniusJodie** [comment]
this problem might be my fault and I might be stupid

**Comment by sp614x** [comment]
Water and lava use 2x textures which are dynamically shifted to simulate the "flowing" textures:

![image](https://user-images.githubusercontent.com/16635441/36026051-b4ac20e2-0d95-11e8-9618-5efec1fbd5f8.png)
