### ISSUE TITLE
Cant Extract Mod

### ISSUE THREAD

**Issue by niklas2233** [sp614x/optifine#1209]
Cant Extract the optifine for forge. just says " Minecraft version 1.12.2 not found. You need to start the version 1.12.2 manually once.

**Comment by Dushess** [comment]
Strange actions, optifine jars from site (downloads page) is forge modules, just put them into mods.

**Comment by niklas2233** [comment]
yeah totaly work thanks thought you need to extract cause i read that somewhere Thanks
