### ISSUE TITLE
Allow shaders to define custom render layers per block, too!

### ISSUE THREAD

**Issue by jcm2606** [sp614x/optifine#1210]
Supposedly resource packs are able to control which render layer a block or set of blocks use. I think shaders should get this ability, too, as it would allow shaders to properly handle blocks rendering in the cutout layer without having to piggyback off of a resource pack. Not only will we be able to do things like reflections & refraction on cutout glass, but we would also be able to control which render layer modded blocks use, in case a modded block is being sorted into the wrong render layer.

It shouldn't be too hard to do, given the fact that resource packs already have it. You could add it to the shaders' `block.properties`, alongside custom block mapping.

**Comment by MathGeniusJodie** [comment]
mak gud

**Comment by sp614x** [comment]
Updated preview C9 for 1.12.2
- shaders can define custom block render layers
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.txt#L319
