### ISSUE TITLE
Modpack Permissions Are Confusing

### ISSUE THREAD

**Issue by FireController1847** [sp614x/optifine#1216]
I'm extremely confused now.

Recently, your website (at the bottom of the page) explicitly stated that OptiFine was NOT allowed in modpacks. It's gone now. This raises a concern and question about distribution and modpack usage. If we are to reference the direct download itself (say using the JourneyMap example found in #1206), would we be allowed? From a previous issue, I noticed it was marked as a "no, sorry". I agree with #1188 where you guys should explicitly state that it is or is not allowed to be distributed at all.

To be specific with what I'm doing, I made a modpack called [Yogbox 2.0](https://www.technicpack.net/modpack/yogbox-20) (based on the original Yogbox), and I was a little concerned when I noticed Yogbox has optifine. I try to be as close to the original modpack as possible, so I've emailed you TWICE about custom usage (via the contact button). Each time was met with no response after a month's time. So now I'm here. Can I have permission to include this in Yogbox 2.0? All issues would be handled by ME, and it will be explicitly stated via Solder on the [mods ](https://www.technicpack.net/modpack/yogbox-20/mods) tab.

So, whether it is a no or yes, I suggest you guys add a "distribution" or "modpack" clause on your website (most likely in the FAQ section) that clears all this up. That will avoid a lot of spam Emails and confusion, such as this issue. Thanks in advance.

**Comment by PulzHF** [comment]
I couldn't help but notice that this is still an open issue.
Do we have any news on updated permissions, or requirements for popular modpack owners?

**Comment by FireController1847** [comment]
@sp614x Mate, a lot of modpack developers depend on this mod because a lot of mods are unoptimized and don't work well together. Can you at least explicitly state if we are or are not allowed to include the mod in modpacks?

**Comment by sp614x** [comment]
By default modpacks are not allowed to add OptiFine.

**Comment by FireController1847** [comment]
Ok, now I have two questions...

1. If you don't mind, may I ask why? I've just never understood why some people don't allow it, so knowing could prevent me from asking in the future.
2. If we Email the contact link, do we get a response? And do you guys ever give explicit permission to some people?

**Comment by PulzHF** [comment]
@FireController1847 I'd like to know too- as it makes absolutely no sense to me whatsoever. Surely when you create something, you'd want it pushed to the masses as much as possible- and not just kept to a single site. I often get tired of directing people to the Optifine site when they ask- is it about funding?
 
Is the worry that Optifine would get no donations if people didn't hit the site? Why not simply add an alert to all versions, reminding you that you can get a cape etc..?
