### ISSUE TITLE
beginning with version D8 1.7.10  character no longer renders properly/game crashes

### ISSUE THREAD

**Issue by trollworkout** [sp614x/optifine#1217]
And it appears the error is something to do with 

net.minecraft.client.renderer.EntityRenderer::func_78471_a 

Every version since then it crashes the game.  When I load the game my character does not render all I see is a floating arm then it will crash 2-3 seconds after.

D6 and previous versions work fine however.

Here is the complete crash log
[hs_err_pid916.log](https://github.com/sp614x/optifine/files/1723610/hs_err_pid916.log)

The issue has to do with a mod called The Betweenlands or possibly Ars Magica 2 (which is notorious for not working with Optifine) although I suspect is the former rather than the latter.  The odd thing is it USED to work so it can work. Not sure what changed.

**Comment by trollworkout** [comment]
Looking though the list of changes in D7 I see :
- fixed transparent hand with shaders when the world border is visible
- fixed Forge RenderHandEvent to work with shaders 

Not sure if that is the problem but seems to be the only match as what I experience is a floating hand and character no longer renders properly.

**Comment by sp614x** [comment]
This is a native JVM crash, not directly caused by OptiFine.
Most probably some mod is patching the OptiFine classes in an invalid way which causes the JVM to crash.
The changes from D7 to D8 are minimal, in EntityRenderer only the visibility of one method is changed to public.

**Comment by trollworkout** [comment]
nice it got fixed so fast.
