### ISSUE TITLE
[Question] Variety in connected textures?

### ISSUE THREAD

**Issue by ColonelOverspel** [sp614x/optifine#1219]
Is there a way to create variety in connected textures the same way the random method does that? You would have 0.png and a 47.png, for example, that both fill the ctm.0 spot? I have been looking for a way, and trying various things, but this doesn't seem to exist yet.

**Comment by sp614x** [comment]
It should be possible to add properties file which matches 0.png so it would be randomized to 0a.png, 0b.png, 0c.png, etc.
```
matchTiles=0
method=random
tiles=0a 0b 0c 0d
```

**Comment by ColonelOverspel** [comment]
Thanks @sp614x. For people who found this and want to do the same: He forgot to mention that if you want to do matchTiles you have to determine the whole file path you set for that block to work, so:

matchTiles=mcpatcher/ctm/%your filename%/0
method=random
tiles=0a 0b 0c 0d
