### ISSUE TITLE
RudoPlays Shader issues

### ISSUE THREAD

**Issue by ModestPixels** [sp614x/optifine#1220]
Goodday!

I love the RudoPlays Shaders for Minecraft but it has some annoying issues. I kinda figured out some but I know nothing about coding. I just tried to fix it. The player's hand and skin and everything in the hand are transparent as well as the birch doors. I fixed the hand and players by changing gbuffers_hand  
`varying float translucent;1` (There was no number there before and I changed it to 1.  Seems to have fixed the problem, shadows on it are weird though)
I tried changing the water because the chunks don't flow well together 

These are the unchanged setting:
`if (mc_Entity.x == 8.0 || mc_Entity.x == 9.0) {
	iswater = 1.0;
		float speed = 1.0;
        float magnitude = (sin((worldTime * 3.14159265358979323846264 / ((28.0) * speed))) * 0.05 + 0.15) * 0.27;
        float d0 = sin(worldTime * 3.14159265358979323846264 / (122.0 * speed)) * 3.0 - 1.5;
        float d1 = sin(worldTime * 3.14159265358979323846264 / (142.0 * speed)) * 3.0 - 1.5;
        float d2 = sin(worldTime * 3.14159265358979323846264 / (162.0 * speed)) * 3.0 - 1.5;
        float d3 = sin(worldTime * 3.14159265358979323846264 / (112.0 * speed)) * 3.0 - 1.5;
        //position.x += sin((worldTime * 3.14159265358979323846264 / (13.0 * speed)) + (position.x + d0)*0.9 + (position.z + d1)*0.9) * magnitude;
        //position.z += sin((worldTime * 3.14159265358979323846264 / (16.0 * speed)) + (position.z + d2)*0.9 + (position.x + d3)*0.9) * magnitude;
        position.y += sin((worldTime * 3.14159265358979323846264 / (15.0 * speed)) + (position.z + d2) + (position.x + d3)) * magnitude;
	}`
I guess I have to change something in here...

[See trough skin Image (fixed)](https://drive.google.com/open?id=1t9SkwPwW_kT2Bi1OqiCmTlbf8e5w3hoj)
[See trough hands and items (fixed)](https://drive.google.com/open?id=1gqilstqFJYaSU2Bu9dnNYl9morg5kxVH)
[Water somewhat fixed (just changed everyting to 0](https://drive.google.com/open?id=16nQGX1Ayi06-ehKkMdwS3X-lPinMR5so) I really want this to be floating water without the cracks.

Then there is this issue where the falling leaves and smoke turn black when I come closer than 5 block away from them.
[closeup normal(zoomed in from 5 blocks distance)](https://drive.google.com/open?id=1NrPSMY0HpS4Ns03DnVsvCx3Ib36sEd8b)
[coming closer (black)](https://drive.google.com/open?id=1797K06BFVpiJUEN5uipX-gi9g4M6O85w)

I really don't know how to fix those things.. 

Hope someone can help!

Thnq very much!

**Comment by Strum355** [comment]
Rudoplays is old and unmaintained. Your best option would be to use a modern shader designed for new versions. Rudoplays, MrMeepz etc need to be phased out

**Comment by sp614x** [comment]
This looks like a problem with the shaders not with OptiFine.

**Comment by ModestPixels** [comment]
Thnx for the response.. but how do I tag it right? Do I open another thread with a shader tag?

**Comment by sp614x** [comment]
The issue tracker is only for OptiFine issues. This is not an OptiFine issue as OptiFine is working correctly and it has no problems. 

RudoPlays is a very old shader pack which is a copy/paste of an early Chocapic13 v3 shader. The original author Chocapic13 commented on this issue:

![image](https://user-images.githubusercontent.com/16635441/36303792-a1d859e0-130d-11e8-8a97-f96bbf7e46af.png)

**Comment by sp614x** [comment]
This is the list of current shaders: http://shaders.wikia.com/wiki/Shader_Packs

**Comment by ModestPixels** [comment]
I see.. It's not that I don't have other shaders. I have all the popular ones. But this Shader is soo beautifull and unique! If it's a copy-paste thing why does the Chocapic13 creator not just fix it and put it up for download. Since it was his in the first place. O well.. Thnx for the help anyway!

**Comment by Strum355** [comment]
Why would or should he fix a shader that uses code that was stolen from him? That makes no sense. Go try out some "less popular" shaders if you already have the popular ones. Im sure there are loads you havent seen yet.

**Comment by ModestPixels** [comment]
I didn't mean it in a rude way. More of why not take it to his advantage. a lot of youtubers use this shader and if it's originally his he should take the credits. I have older and newer shaders and I'm sure there are a ton more out there. But I just happen to love this one.. If I find anything that's similar or the same i'll definitely use it. Thnx for your input..

**Comment by Strum355** [comment]
Rudoplays, as a shader, shouldn't even exist anymore. It breaks chocapic13s agreement. Why should chocapic further facilitate the publicity and use of rudoplays when it violates his agreement? people arent going to credit chocapic for rudoplays shader, regardless of what chocapic does.
