### ISSUE TITLE
Random TileEntity Bug

### ISSUE THREAD

**Issue by IMerlin1009I** [sp614x/optifine#1221]
When I place a chest with a CustomName the texturing works fine but when I reconnect on the server the texture is gone... so i am asking myself wether I do something wrong or whats the sense of the feature when  I lose the texture on reconnect.

The 2nd Issue I have when I change the Custom name of a chest or any other tileentity via Plugin or the /blockdata command the texture wont update.

I hope you can fix that, I would really appreciate that!

Thanks for reading!

**Comment by sp614x** [comment]
The custom tile entity names only work in single-player. In multiplayer the server does not send the custom name until the chest is open. This is a vanilla problem and can't be fixed.

**Comment by IMerlin1009I** [comment]
Do you know wich packet that is i could send that manually when the chunk loads...

**Comment by IMerlin1009I** [comment]
Would that be the PacketPlayOutTileEntityData?

**Comment by sp614x** [comment]
The tile entities are usually coming with the SPacketChunkData.
The custom name is sent when the player opens the chest with SPacketOpenWindow.
