### ISSUE TITLE
overlay_random (and probably the other overlays) puts the texture behind.

### ISSUE THREAD

**Issue by MisterQuiggly** [sp614x/optifine#1224]
Tried to make title concise. So what's happening is, with leaves, I have an overlay and when it is set to fancy it displays the overlay texture only where there is no texture, making it seem like it's behind the leaves. This is not true for leaves set to fast. Latest optifine C9 version for 1.12.2

![2018-02-16_17 19 24](https://user-images.githubusercontent.com/26760490/36331984-33bdf420-133e-11e8-9e19-16b39f530101.png)
![2018-02-16_17 19 32](https://user-images.githubusercontent.com/26760490/36331985-33d27d28-133e-11e8-8972-42477714354a.png)

**Comment by sp614x** [comment]
Can you post the resource pack link?

**Comment by MisterQuiggly** [comment]
https://drive.google.com/file/d/173ABVyo9JrbRqb14jvUKYM60IF5AKF_h/view?usp=sharing
sorry for delay

**Comment by sp614x** [comment]
Works for me:
![image](https://user-images.githubusercontent.com/16635441/37145060-2f041ea0-22c0-11e8-8bc7-e823560979a8.png)

**Comment by sp614x** [comment]
OptiFine installed standalone or with Forge? 
Forge version? 
Other mods installed?

**Comment by MisterQuiggly** [comment]
Forge
Mods:
Better Foliage
Blur

Better foliage was disabled using the in-game disabler on the picture I sent you. Removed this mod, still doesn't work.
Removing forge and disabling blur, so the only thing that remains is optifine, still didn't fix it.

**Comment by sp614x** [comment]
As visible in the screenshot above it works for me with OptiFine C9 and Forge #2615.
Can you reproduce it with Forge 2615 and only OptiFine installed?

**Comment by MisterQuiggly** [comment]
The problem still exists using 2615 and Optifine C9

**Comment by sp614x** [comment]
Not reproducible, for me it works correctly.

**Comment by MisterQuiggly** [comment]
Very strange. Would you mind posting your optionsof.txt?

**Comment by sp614x** [comment]
Current options:
[options.txt](https://github.com/sp614x/optifine/files/1955122/options.txt)
[optionsof.txt](https://github.com/sp614x/optifine/files/1955123/optionsof.txt)

![image](https://user-images.githubusercontent.com/16635441/39363221-d2b5de9a-4a29-11e8-8146-4620900c2116.png)

![image](https://user-images.githubusercontent.com/16635441/39363234-e0c3fe90-4a29-11e8-8740-3b8d43bfbd5b.png)

**Comment by MisterQuiggly** [comment]
So it's the mipmapping that causes them to appear normally. So I added layer=cutout and now it works without having mipmap on. Thanks!
