### ISSUE TITLE
optifine capes and minecraft accounts

### ISSUE THREAD

**Issue by asbyth** [sp614x/optifine#1229]
for the past few months, sometimes when people change their cape designs, it'll lock their minecraft account, i have no idea whats causing this but a lot of people have lost their accounts completely including many of my friends. it's happened to me aswell, but gladly i had the transaction id to recover my account. some others dont have their transaction id anymore.

**Comment by patos5** [comment]
xd

**Comment by ehhthing** [comment]
This happens because of Mojang's new protections against alt sellers by locking accounts that have had suspicious IP addresses try to login.

I believe that this can be fixed by using a new "change cape" mechanism where the user needs to log in to a server to validate their ownership.
