### ISSUE TITLE
Permanent Night Time on Solo Worlds

### ISSUE THREAD

**Issue by EpicDan01** [sp614x/optifine#123]
For OptiFine 1.9.x, whenever I create a new world, it instantly becomes night time and mobs will spawn. I have tried changing it to day time with /time set day, but this does not work. And when I query the time, it tells me what the time should be, but with 14000 added to it. Whenever I set the time to a number, it goes back to 14000.

http://postimg.org/image/79juuycz5/

**Comment by cyilin** [comment]
Video Settings -> Other -> Time 
Set to "Default"

**Comment by EpicDan01** [comment]
thanks a lot!
