### ISSUE TITLE
Optifine Problem

### ISSUE THREAD

**Issue by JamesIsTheBes** [sp614x/optifine#1230]
When i play in singleplayer it says channel closed and i need help

**Comment by JamesIsTheBes** [comment]
pls someone help

**Comment by realjackasterisk** [comment]
dude, It's been 30 minutes, have some patience. and post some logs too.

**Comment by JamesIsTheBes** [comment]
ok it says intenal Excepetion: java.nio.channels.ClosedchannelException

**Comment by realjackasterisk** [comment]
***full*** logs

**Comment by JamesIsTheBes** [comment]
[latest.log](https://github.com/sp614x/optifine/files/1735132/latest.log)
ok here

**Comment by JamesIsTheBes** [comment]
[fml-client-1.log](https://github.com/sp614x/optifine/files/1735143/fml-client-1.log)

**Comment by JamesIsTheBes** [comment]
[fml-client-latest.log](https://github.com/sp614x/optifine/files/1735145/fml-client-latest.log)

**Comment by realjackasterisk** [comment]
1. What version of Optifine do you have? (full name please)
2. What version of Forge do you have? (log says 2611, but I just wanna be sure)
3. Have you tried disabling your mods? (conflicts aren't uncommon)

**Comment by JamesIsTheBes** [comment]
1 its version 1.12.2-optifine_HD_U_C9
2 yep ist 2611
3 yes they are disabled

**Comment by realjackasterisk** [comment]
Optifine 1.12.2 C9 is compatible with Forge #2615. Try updating it.
Additionally, see if the problem occurs in Optifine standalone, or even Vanilla MC.

**Comment by JamesIsTheBes** [comment]
ok

**Comment by JamesIsTheBes** [comment]
well i will be back tommorow
