### ISSUE TITLE
Upload Donator Capes

### ISSUE THREAD

**Issue by Kore-Development** [sp614x/optifine#1236]
I have a file with a custom cape as a file but why can't I upload it. If it can be added I would like it to.

**Comment by Brottweiler** [comment]
You can't upload files. You either customise your own using colours on the optifine website, or you copy paste a link to a banner from a site like https://www.needcoolshoes.com/banner.

**Comment by sp614x** [comment]
Uploading custom capes is not allowed to avoid conflicts with the official Mojang capes.
