### ISSUE TITLE
Flickering water bottom texture

### ISSUE THREAD

**Issue by Mangabum** [sp614x/optifine#1238]
I'm running 1.12.2 with Optifine HD U C9. I noticed the bottom texture of water kinda flickers every time I place a block or change the surrounding light level. Its especially noticeable if you move around with dynamic lights on. The resource pack I'm using is bdcraft x32, though the issue is present but less noticeable in other resource packs. Not running any shaders or mods, just that resource pack. Not sure if this is a problem with optifine or just something on my end but I appreciate any help. 

![ezgif-4-822ced1342](https://user-images.githubusercontent.com/36723699/36523762-28e61074-17de-11e8-8157-3c8d21c902ee.gif)
Flickering when placing blocks

![ezgif-4-474f5d9a47](https://user-images.githubusercontent.com/36723699/36523761-28aea698-17de-11e8-9890-35cb4273bdca.gif)
Flickering with dynamic lights or any normal light source

**Comment by sp614x** [comment]
This doesn't look like BDCraft water.

This is how it should be:

![image](https://user-images.githubusercontent.com/16635441/36533715-b9586590-17c4-11e8-9ac1-48c2b7ac63a8.png)

**Comment by Mangabum** [comment]
Sorry, I'll try to clarify the problem. The structure in my original post is 2 blocks deep of water held up by glass blocks. I tried to recreate the problem using vanilla textures and a body of water surrounded by glass blocks. From what I can tell, the problem only happens with water bodies at least 2 blocks deep and low light conditions. To make it clearer I maxed out the brightness slider.

![2018-02-22_21 09 46](https://user-images.githubusercontent.com/36723699/36541053-a00d0534-1817-11e8-99f0-bebe809a38ae.png)

As you can see the issue happens even with vanilla textures.
![ezgif-4-1071a69c4f](https://user-images.githubusercontent.com/36723699/36541152-f3e4e6b8-1817-11e8-862d-ac184eec1ba2.gif)

Same thing with a 3 block deep water pool
![ezgif-4-5326cc071e](https://user-images.githubusercontent.com/36723699/36541122-d560768a-1817-11e8-843b-d3efc72c545d.gif)

I redownloaded Minecraft and optifine but the issue is still there

**Comment by sp614x** [comment]
Tested OptiFine C9 standalone and also with with Forge #2615, no flickering textures:

![image](https://user-images.githubusercontent.com/16635441/36542523-506ca416-17e1-11e8-9296-9fdf0ab639cd.png)

This is 2 blocks deep water on glass blocks.
The dynamic lighting is only generating chunk updates, it looks like a problem with chunk loading.

**Comment by sp614x** [comment]
Debug screenshot (F3)?
Running with Forge or standalone?
Other mods installed?

**Comment by Mangabum** [comment]
![2018-02-22_23 19 36](https://user-images.githubusercontent.com/36723699/36546683-fc26e39e-1826-11e8-8ca9-bfc223abfad9.png)

Running it standalone. No other mods.

[optionsof.txt](https://github.com/sp614x/optifine/files/1748445/optionsof.txt)

**Comment by sp614x** [comment]
Managed to reproduce it (the glass is unvisible):

![image](https://user-images.githubusercontent.com/16635441/36594257-b07e4c3a-189d-11e8-9d96-4cc9c84327c1.png)

**Comment by sp614x** [comment]
Seems to only happen when antialiasing or anisotropic filtering is enabled.

**Comment by sp614x** [comment]
Updated preview D1 for 1.12.2
- fixed flickering water bottom texture with AA/AF enabled

**Comment by mindforger** [comment]
@sp614x there is a specific version of optifine recommended to use with viviecraft (and only this particular version for compatibility reasons afaik), that suffers from the same issue, do you think you can fix this version too?
http://www.vivecraft.org/

i stopped using vivecraft currently (mostly because of motion sickness) but i would be happy to test again

i am yet on my rift PC so i can not tell the exact version but in a few hours i can

**Comment by sp614x** [comment]
Released versions are generally not changed. 
The only exception would be a very serious bug found shortly after the version is released.

**Comment by mindforger** [comment]
well, let's say this one is kinda disturbing, especially in 3D 

:P

but i can disable AA or AF as a workaround

**Comment by sp614x** [comment]
It could be patched to C7, but the bugfix may also have another negative effects as it is not tested enough.
To avoid the confusion between unpatched C7 and patched C7 a new version should be made. 
The bugfix will come with D1 when it is released.

**Comment by mindforger** [comment]
Okay, hope vivecraft doesn't have issues with newer versions
