### ISSUE TITLE
Custom Shader Texture Filtering

### ISSUE THREAD

**Issue by dotModded** [sp614x/optifine#1239]
Wondering if you could add an option to change the filtering type for custom textures, specifically GL_NEAREST and GL_LINEAR, however more would be welcome. I'm trying to load a custom LUT however I'm using a 16x16x16 (4096 bit flattened) LUT, I would like to use linear interpolation to sample in between the pixels and get the average, this lets me get the bit depth back.

**Comment by Builderb0y** [comment]
This is already possible in the .png.mcmeta file:
```json
{
	"texture": {
		"blur": true,
		"clamp": true
	}
}
```
Blur true = linear, blur false = nearest. Clamp controls how texcoords are handled outside the 0-1 range.

**Comment by sp614x** [comment]
The vanilla mcmeta approach should work.
