### ISSUE TITLE
Optifne 1.7.10 D4 Fast render bug

### ISSUE THREAD

**Issue by Expansing01** [sp614x/optifine#124]
Hello, I'm here to report a bug. The bug is: if you go near the water (next to water is a dirt block which is plowed), the water flickers crazy.

http://imgur.com/FNa3O5t

The bug is only in the fast render mode which is important for me, because I have the transparent pixel bug.

MC1.7.10 optifine version D4

**Comment by sp614x** [comment]
This is a side effect of FastRender and can not be fixed easily.
The proper fix would be the water block not to render flowing water on the sides of tilled dirt.
