### ISSUE TITLE
Shaders seem to glitch out at high coordinate values

### ISSUE THREAD

**Issue by E-daw** [sp614x/optifine#1240]
![2018-02-22_21 55 01](https://user-images.githubusercontent.com/34014927/36577221-85a928c2-181b-11e8-96bb-6be8d6654523.png)

Shaders seem to glitch at higher coordinate values, my cords in game are x:100 y:70 z:-20000000.
Currently in this image I'm running SEUS shaders but every other shader pack seems to have a similar glitch of some sort. Animations skip and move very slowly. My shaders seem to work fine bellow coordinates of two million (negative or positive)

**Comment by E-daw** [comment]
![2018-02-22_21 54 53](https://user-images.githubusercontent.com/34014927/36577263-d479303c-181b-11e8-8ad1-2bd1fcd51837.png)
Running BSL Shaders here

**Comment by sp614x** [comment]
This is something that depends on the specific shader pack.
Vanilla takes special care to avoid overflows when rendering at high coordiante values. The shaders usually do very complex calculations and they are probably not verified to run correctly at high coordinates.

**Comment by sp614x** [comment]
Updated preview D1 for 1.12.2
 - fixed shaders to work properly at high coordinate values (#1240)
