### ISSUE TITLE
Use HTTPS in optifine.net

### ISSUE THREAD

**Issue by Madis0** [sp614x/optifine#1244]
After the incident of #1206 and your claim of
> We take the security of OptiFine and the website very seriously.

it is especially important to start using HTTPS on all pages of optifine.net already.

[Protecting the login page is not enough](https://doesmysiteneedhttps.com) and since you seem to use Cloudflare anyway, [take a look at their solution.](https://www.cloudflare.com/ssl/)

Edit: looks like HTTPS is enabled for some pages, but not enforced. Downloads are still insecure.

**Comment by sp614x** [comment]
Not sure if every possible browser would be OK with SSL per default

**Comment by Madis0** [comment]
Those that are not need to be updated then, because [HSTS](https://en.m.wikipedia.org/wiki/HTTP_Strict_Transport_Security) is a thing, and in the future major browsers will complain if SSL is _not_  default.

**Comment by Foorack** [comment]
@sp614x I completely agree. Beginning in July 2018 Chrome will start marking optifine.net as "Not Secure". All browsers handle HTTPS perfectly fine. Best would be if Optifine enabled HSTS due to some network connections stripping HTTPS redirects, however HTTPS by default would be a good first step.

**Comment by sp614x** [comment]
Enabled HTTPS by default with automatic redirect.

**Comment by Madis0** [comment]
@sp614 Downloads are still initiated with http and cause an error "too many redirects".

**Comment by Madis0** [comment]
@sp614x Downloads are still initiated with http and cause an error "too many redirects".

**Comment by sp614x** [comment]
Fixed reverse redirect to HTTP in "download".

**Comment by Madis0** [comment]
I've noticed that download and mirror links are still http, even though they support https when attempted.

**Comment by sp614x** [comment]
Temporary disabled HTTPS redirects to fix AutoSSL problems, it would need a better configuration.
Now it is enabled again.

**Comment by Madis0** [comment]
On https://optifine.net/downloads the Download and mirror links lead to HTTP.
