### ISSUE TITLE
 Multiplayer VBO Crash With New Optimized VBO Rendering

### ISSUE THREAD

**Issue by FrancisDaPugtato** [sp614x/optifine#1248]
MC Version 1.12.2, Java 8 update 162, Intel Graphics HD 4600, OpenGL 4.3, Optifine Version: 1.12.2 D1pre 
   VBO Rendering was changed a few days ago, and I think I have found a crash. 
Crash Report Link:
https://pastebin.com/s9tjrSx0

** MULTIPLAYER **

**Comment by FrancisDaPugtato** [comment]
I can give you all the crash reports you need since I am like completely stored with them

**Comment by sp614x** [comment]
Updated preview D1 for 1.12.2 with a bugfix.
