### ISSUE TITLE
[suggestion] Custom blockstate variables as alternative to CTM

### ISSUE THREAD

**Issue by leagris** [sp614x/optifine#1251]
Having custom glass pane model is not compatible with connected glass.
Glass Pane models are provided 4 block state variables to indicate connection with any block:
Boolean: `north`, `south`, `east`, `west`.

If Optifine provided additional custom block-state variables:
Boolean: `ctmnorth`, `ctmsouth`, `ctmeast`, `ctmwest`…
it would be possible to provide custom glass pane models to connect properly with the help of block-state logic on multi-part models.

It could even provide a complete CTM replacement for any block whose model can only connect properly with varying model parts rather than altering existing model and textures automatically.

**Comment by sp614x** [comment]
Currently it is not possible to create custom block states.
