### ISSUE TITLE
Slivers of blocks disappearing after installing Optifine

### ISSUE THREAD

**Issue by The-Soulless** [sp614x/optifine#1252]
So yesterday I downloaded Minecraft, today I installed Optifine for the FPS boost. Problem with that is now this is happening:

https://a.doko.moe/husqzf.mp4

I ran Minecraft without optifine and it still happens, deleted ~/.minecraft, still happening, reinstalled everything with opengl in it's description and name, reinstalled java, tried using the "new" launcher from the AUR, and it's still happening.

I'm currently running Antergos x64 Linux, will provide Dmesg if neccesary

**Comment by sp614x** [comment]
The antivirus is blocking the "https://a.doku.moe" URL.
If the problem happens without OptiFine, this it is not relevant to OptiFine.

**Comment by sp614x** [comment]
Maybe you have installed an older version of OptiFine which automatically uses the older MC version?
If the old MC version does not recognize the blocks, they may disappear.

**Comment by The-Soulless** [comment]
First of all you have a bad antivirus as doko.moe is just a file hosting site, I reuploaded the video here:
https://a.pomfe.co/apnxxm.mp4
and second of all, this only happened *after* optifine was installed. Would hate to have to reinstall Antergos because of a Minecraft mod.

**Comment by The-Soulless** [comment]
Also as I said in OP, I deleted my .minecraft, that means that all my data was erased, meaning that I couldn't be running an old version of minecraft

**Comment by sp614x** [comment]
The URL "a.doku.moe" is reported by 8 antivirus engines as malicious, they may have a problem: https://www.virustotal.com/#/url/3a9280e5730125f31c20962246a17bb3c31547a5bac52397614259737a0285ef/detection

The second video link works, but doesn't show what is the problem.
Was OptiFine installed standalone (with installer) or placed in the Forge mods folder?
Could you post an F3 screenshot?

**Comment by The-Soulless** [comment]
It was installed with the installer (from optifine.net), and what do you mean an F3 screenshot?
Also my problem was fixed by: Doing everything described in the OP, it only worked after I restarted.

**Comment by The-Soulless** [comment]
Also to answer your virus total scan, 
BitDefender is known for false positives, and the rest are just random antiviruses, if you look at the community score it's +32. also it's Doko, not doku

**Comment by MauveCloud** [comment]
> what do you mean an F3 screenshot?

Since sp614x hasn't answered this, I think what is desired here is a screenshot with the F3 (debug) info showing, which will reveal some potentially-relevant details, e.g. which exact build of Java you're running, what video card you're using, and how close Minecraft is to the limits of its allocated memory.
