### ISSUE TITLE
Vanilla Profile Crashes After Installing OptiFine

### ISSUE THREAD

**Issue by Joonits** [sp614x/optifine#1253]
Minecraft 1.12.2
OptiFine 1.12.2_HD_U_C9
No mods
No resourcepacks

My vanilla profile worked perfectly until I installed OptiFine. After playing with OptiFine for a few days, the no sound bug (#758) was occurring every single time I launched and I wanted to switch back to vanilla since OptiFine wasn't really providing me benefit anyway (I have no mods, shaders, or FPS problems).

My vanilla profile now crashes every time within a few seconds after launch by freezing Minecraft in the menu, not allowing mouseclicks/buttonpresses, though music still plays and the animated diamond on the Realms button continues animating. I have deleted OptiFine and its profile and the crash still occurs. I have manually deleted the .minecraft folder, re-installed Minecraft and the crash still occurs on a vanilla profile without OptiFine installed.

I re-installed OptiFine and I can play again without crash using the OptiFine profile, but vanilla profile still causes a crash.

My current configuration is fresh install of Minecraft 1.12.2 + fresh install of OptiFine 1.12.2_HD_U_C9

Which logs do you need?

**Comment by sp614x** [comment]
If you have manually deleted the minecraft folder then all changes made by OptiFine have been removed.
Can you post the error log or crash report?
