### ISSUE TITLE
Shader option to disable frustum culling

### ISSUE THREAD

**Issue by BruceKnowsHow** [sp614x/optifine#1254]
Certain large-scale vertex shader effects move blocks inside the frustum that originate outside of the frustum. Frustum culling makes these blocks invisible, causing unloaded chunks within the field of view. This is visible with the Acid or Planetoid effect.

In more arcane settings, frustum culling can be a huge issue. [This video](https://www.youtube.com/watch?v=geGziPUQD2U) I made simulates non-euclidean geometry ([0:43](https://youtu.be/geGziPUQD2U?t=43s)). This effect was accomplished by have two adjacent sets of terrain, obviously both sets of terrain didn't fit into the frustum. I had to hack one of the mods I was using to disable frustum culling to film this vid, it was a big headache and I've never done it after 1.7.10.

There's talk of some sort of frustum culling feature for the shadow map, and obviously it will have to be optional because it will probably break effects like Global Illumination. I think regular frustum culling should be optional as well.

The option would be best put into the shader (not shaders.properties) so that it could be dynamically toggled with the new macro stuff. A second option is also possible, a numerical FOV extension. I'm not sure exactly how this would work, because a linear addition to the FOV does not correspond to a linear change in scene composition.

`// this number would have to be fed into some trig function, I'm not sure about it yet`
`const float frustumOverdraw = 5.0;`

`const bool disableFrustumCulling = true;`

Clarification: frustumOverdraw would only have some effect if frustum culling was still enabled

**Comment by sp614x** [comment]
The option could be placed in "shaders.properties" and still be controllable with user options similar to: https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.properties#L401

The frustum expansion could be defined as plane offset (move frustum planes N chunks in outside direction) or as FOV extension (rotate frustum planes in outside direction). Both could also be combined.

**Comment by sp614x** [comment]
Added in D1
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.properties#L61
