### ISSUE TITLE
Feature: using * before  a name so anything before that works as well

### ISSUE THREAD

**Issue by lilmrmagoo** [sp614x/optifine#1258]

**Comment by sp614x** [comment]
Is this for Custom Item Textures (CIT)?
You can use patterns and regular expressions, they can include wildcards (*).

**Comment by lilmrmagoo** [comment]
yes it is for cit because ex * pick would work for ice pick or diamond pick but not pick of ice sorry for my bad english

**Comment by lilmrmagoo** [comment]
and if you did * pick * if the name of that item had the word pick in it anywhere it would work

**Comment by sp614x** [comment]
You can use `ipattern:*pick*` to match any name containing "pick"
