### ISSUE TITLE
OptiFine 1.12.2 HD U C9

### ISSUE THREAD

**Issue by ninjaassassasin** [sp614x/optifine#1264]
I load into any world, server, or realm and my game instantly goes to 0fps. Optifine is the reason as i have no other mods and when i went into vanilla minecraft it didn't occur and i had a steady 30-40fps. I changed no settings and it randomly started happening. I restarted my game and my computer, so i don't know what made it happen. Also the game was working perfectly fine a few hours before this occurred.

**Comment by sp614x** [comment]
More details needed:
- debug screenshot (F3)
- installed standalone or with forge
- error log (game output)
- have you tried to reset the video settings (Video Settings -> Other -> Reset)
- have you allocated more memory to MC? if yes, then revert to default 1GB could help

**Comment by KaiAF** [comment]
Closing this as there has been no response from the user.
