### ISSUE TITLE
[question] [ctm] question about ctm methods

### ISSUE THREAD

**Issue by abbie** [sp614x/optifine#1265]
Sorry if this isn't the correct place to ask this. I tried looking at the documentation for ctm and couldn't really find out if there was a way to do what I am trying to achieve.

I have a total of 8 textures I am trying to apply to a block. These textures are 2 sets of 4 connected textures, so set one appears as: ![](https://i.imgur.com/n35lvbM.png) *(4 textures)*, and set two appears as: ![](https://i.imgur.com/vkIgAcn.png) *(4 textures)*.

I am able to make achieve the connected texture part just fine:

1. Set one *(red textures)*:
```properties
method=repeat
# cobblestone
matchBlocks=4
tiles=0-3
height=2
width=2
``` 

2. Set two *(blue textures)*:
```properties
method=repeat
# cobblestone
matchBlocks=4
tiles=4-7
height=2
width=2
```

Now what I would like to do is randomize these two sets; however, I cannot find a way to achieve that without disrupting the repeat patterns. **This is an example of what I would like to achieve:**

![](https://i.imgur.com/PratQuZ.png)
<sup>Grid of `10 x 6` blocks</sup>

What I would think would be a logical way to achieve this is to create a third `.properties` file with `method=random`, but instead of referring to a set of tiles, refer to the other two `.properties` files I have already created. Referring to a set of tiles does not appear to work as it will either: **a**) override the repeat patterns that must be followed, resulting in textures not aligning correctly; or **b**) get ignored due to lower priority, which will also result in one of the two repeat patterns getting ignored.

Referencing another `.properties` file for a random method instead of a set of tiles does not appear to be possible, so is there a way to achieve what I am asking? Thanks!

*(sorry if I overlooked something that would allow me to achieve this or did not explain it thoroughly!)*

**Comment by sp614x** [comment]
You want to make groups of tiles (2x2) that use a common random seed.
Currently it is not possible to group tiles together. Each tile uses its own random seed based on the block position and model side.

**Comment by sp614x** [comment]
It is possible to make a checkerboard pattern with 2x2 groups (or bigger), but they would be distributed uniformly (checkerboard), not random.

**Comment by sp614x** [comment]
To do this a new CTM parameter would be needed `randomScale`, which could be used to make groups of 2x2, 3x3, 4x4, etc blocks use the same random seed.

**Comment by abbie** [comment]
That's what I had concluded myself, just wanted to check to be 100% sure. Thanks, I appreciate it.
