### ISSUE TITLE
[Enhancement] Improve Ocean Rendering

### ISSUE THREAD

**Issue by fisher521** [sp614x/optifine#1268]
https://www.reddit.com/r/Minecraft/comments/82han9/suggestion_for_113_improve_ocean_rendering/

Just a suggestion I found on Reddit that I thought would be a great feature for Optifine.

**Comment by sp614x** [comment]
This can only be done with a custom shader, like the Win10 edition does it.

Made a simple shader pack that changes water alpha depending on the distance:
![image](https://user-images.githubusercontent.com/16635441/37153877-650c1d0e-22de-11e8-8f32-293c72e2ca59.png)

One disadvantage is that the water at a distance looks like plastic.
