### ISSUE TITLE
smooth lighting not working

### ISSUE THREAD

**Issue by Ormega** [sp614x/optifine#1269]
Tried to set smooth lighting to max using optifine, but when i toggle smooth lighting, starting from OFF, it just goes to minimum, and after I leave the video settings menu, it goes back to OFF.

**Comment by sp614x** [comment]
Is OptiFine installed standalone or with Forge?
Other mods installed, Forge version?
Error log (game output)?

**Comment by Ormega** [comment]
Installed with forge; forge version 14.23.2.2624.
No error log, the game doesn't seem to recognize this as a problem.

Minecraft version: 1.12.2 (felt that might be needed)
Mods list (only included the ones that have a significant visual effect or installed recently):
Astral Sorcery
Chisel
Quark
RealBench
The One Probe/HWYLA

**Comment by sp614x** [comment]
To show the game output:
In the MC launcher go to Settings -> Open output log when game starts

**Comment by Ormega** [comment]
[latest.log](https://github.com/sp614x/optifine/files/1795167/latest.log)

**Comment by Ormega** [comment]
Got it. While the log was opened i tried turning the smooth lighting on, then tried it again while I was in a game world.

**Comment by sp614x** [comment]
The error log is OK. no problems reported.
Can you reproduce the problem with less mods installed?

To quickly find the problematic mod:
1. Remove half of the mods
2. If the problem appears keep the mods, otherwise use the removed half of the mods
3. Continue with 1.

**Comment by Ormega** [comment]
Just found that the bug is either related to Quark or AutoRegLib, I'll try fidgeting with those to see if its something caused by a configuration in Quark, because it was working fine for months with quark installed.

I have to be at work for a few hours, so I wont be able to investigate this further until later tonight.

**Comment by Shiny-andKittens** [comment]
Apologies for bumping this issue, but

**Comment by Fearaniar** [comment]
Quark:
     Experimental:
          - Coloured Lighting: turn it off.

It's an old thread, but I'm using the same/similiar versions of MC, so I think this solution is helpful.
