### ISSUE TITLE
NullPtr Crash Upon Clicking Connected Textures: Fancy

### ISSUE THREAD

**Issue by princessbinas** [sp614x/optifine#1272]
Opti-Fine version: OptiFine 1.12.2 HD U C9

I am reporting an issue involving changing the Connected Textures setting from Fancy to one of the others. Clicking the button causes an intense lag in both the main screen and in-game on a multiplayer server and in single player. This lag has lead to my sister crashing from a NullPtr error and a long "Not Responding" wait time for me. 

Note: Changing the Emissive Textures setting has also caused lag, but not a crash so far.

[NullPtr-Optifine-Crash.txt](https://github.com/sp614x/optifine/files/1798749/NullPtr-Optifine-Crash.txt)
[crash-2018-03-09_16.56.22-client.txt](https://github.com/sp614x/optifine/files/1798750/crash-2018-03-09_16.56.22-client.txt)
[crash-2018-03-09_17.07.02-client.txt](https://github.com/sp614x/optifine/files/1798751/crash-2018-03-09_17.07.02-client.txt)

**Comment by sp614x** [comment]
The crash is inside the search tree initialization. Doesn't seem to be related to OptiFine.
Most probably a mod item or recipe without name or ID.
