### ISSUE TITLE
Nether Chunk Errors on 17+ Render Distance

### ISSUE THREAD

**Issue by mike-ers** [sp614x/optifine#1274]
Version: OptiFine 1.12.2 HD U C9

Using any render distance above 16- If you create a fresh new world in creative mode and enter the nether before the world around the spawn location finishes rendering, then chunks begin to glitch in the Nether as the game attempts to render chunks from the overworld (often failing and leaving phantom chunks that cannot be interacted with) - works with 100% consistency if as soon as you enter the nether, you go straight up and get through the nether's bedrock ceiling. Never noticed it in survival, where I play on 32 chunk render, so it might only affect fresh worlds.

Does not seem to work with vanilla Minecraft - I'm thinking that it's something to do with one of the settings of Optifine.

I have all of the settings in performance that have to do with chunk loading/rendering enabled / at their highest values (basically, all of them are not default Minecraft settings.)

![2018-03-09_21 25 56](https://user-images.githubusercontent.com/37232096/37237667-a198944e-23e4-11e8-8af7-b812945a0c37.png)

**Comment by sp614x** [comment]
Fixed in latest preview D1 for 1.12.2.
