### ISSUE TITLE
Leaf issue with Dynamic Trees

### ISSUE THREAD

**Issue by whitestarx0312** [sp614x/optifine#1275]
It seems that leaves from the dynamic trees mod flickers back and forth between fancy and fast leaves. 

Imgur: https://imgur.com/a/50znl

*Note that this issue persists when optifine leaves are on any setting (Fast, Fancy, Smart) and when left on default settings.

**Comment by sp614x** [comment]
Works for me:

![image](https://user-images.githubusercontent.com/16635441/37725574-8ce4a936-2d33-11e8-8ea8-4c41b4d92094.png)

![image](https://user-images.githubusercontent.com/16635441/37725600-9cb5914a-2d33-11e8-9f62-f197a837bf78.png)

**Comment by sp614x** [comment]
Forge version, other mods installed, error log (game output)?

**Comment by whitestarx0312** [comment]
Forge: forge-14.23.2.2624
Optifine: preview_OptiFine_1.12.2_HD_U_D1_pre
Other Mods: https://imgur.com/a/oqSmZ
Latest log; https://pastebin.com/QbGdCCFX

**Comment by whitestarx0312** [comment]
https://imgur.com/a/oqSmZ Seems to still be happening on my end. No resource packs either.

**Comment by sp614x** [comment]
What other mods are installed?
Does removing the other mods fix the problem?

![image](https://user-images.githubusercontent.com/16635441/37781031-41bd03c8-2df0-11e8-97c9-5feca3ead059.png)

**Comment by whitestarx0312** [comment]
https://m.imgur.com/a/oqSmZ

Other mods are listed here. Ill try removing JEI and streams buts the others are needed to run Dynamic Trees and Dynamic Trees BOP.

**Comment by sp614x** [comment]
You can try with latest preview D1.

**Comment by whitestarx0312** [comment]
Issue is still present using only the following:
DynamicTrees-1.12.2-0.7.5b
preview_OptiFine_1.12.2_HD_U_D1_pre

**Comment by sp614x** [comment]
Tested with OptiFine_1.12.2_HD_U_D1_pre and DynamicTrees-1.12.2-0.7.5b - still works correctly.
You can try to reset the video settings "Video Settings -> Other -> Reset".
What happens if you change the tree type in "Video Settings -> Detail -> Trees"?

**Comment by whitestarx0312** [comment]
I tried  resetting my video settings, issue still there. I tried Fast, Fancy, and Smart leaves. It seems to glitch out a lot more with fancy leaves, but the issue is present on all three settings.

**Comment by sp614x** [comment]
Single-player or multiplayer?
Only on specific worlds or specific places in the world?

**Comment by whitestarx0312** [comment]
Single-player, happens on any world I seem to generate (tested on 5 new world generations)

**Comment by whitestarx0312** [comment]
A block update seems to fix the rendering of the blocks.

**Comment by sp614x** [comment]
Is this only happening on creating new worlds or also opening existing worlds?

**Comment by whitestarx0312** [comment]
Both new worlds and old worlds have this problem if dynamic trees and optifine are installed. The problem goes away when removing optifine.

**Comment by Kolljak** [comment]
Same issue was Whitestarx Only mods we have in common are Geographcarft and BoP. Optfine is HD_U_D1 and using SEUS

**Comment by Kolljak** [comment]
Probably is Geo.

**Comment by Kolljak** [comment]
Yep i just did the same thing. same results.

**Comment by whitestarx0312** [comment]
https://minecraft.curseforge.com/projects/dynamictrees/files/2571383

Seems like it's fixed.

**Comment by sp614x** [comment]
Should work with latest preview E1 for 1.12.2.

**Comment by SkeleBones** [comment]
This is broken again.
