### ISSUE TITLE
"cameraPosition" uniform is one frame old in shadow program

### ISSUE THREAD

**Issue by sonicether** [sp614x/optifine#1279]
It seems that the "cameraPosition" uniform is updated after the shadow program, but before the other programs. That means that the value in this uniform during the shadow program is one frame late, and causes issues when the player moves when relying on this value.

I'm using this value for generating world-space data for path-traced GI seen here: https://www.youtube.com/watch?v=7MV26bOSAyk

You can see the issues that are caused by this in the video. It would be great to have this problem solved!

**Comment by sp614x** [comment]
Probably related to https://github.com/sp614x/optifine/issues/384.

**Comment by sp614x** [comment]
Updated preview D1 for 1.12.2
- fixed camera position in shadow program

**Comment by sp614x** [comment]
For the world voxelization there is an open request https://github.com/sp614x/optifine/issues/1120.
I have it mostly working in 2d texture (biomes and precipitation height).
This would have the advantage that it would respond immediately to block/light changes and it should also be faster.
