### ISSUE TITLE
For people who are having login problems...

### ISSUE THREAD

**Issue by MaskedPvPer** [sp614x/optifine#1284]
I had a login logging in and i ended up waiting 360 mins, And i figured it out now.

All you have to do is...
1. Use the minecraft email you bought MINECRAFT with (Not optifine)
2. Use the minecraft password you put for MINECRAFT (Not optifine)

**Comment by FrancisDaPugtato** [comment]
Hello! What was your original problem? What were you trying to do?

**Comment by sp614x** [comment]
This is also written on the login page.
