### ISSUE TITLE
Conflict with WDL and Optifine 1.12.2 U D1 pre

### ISSUE THREAD

**Issue by Tsoccerguy3** [sp614x/optifine#1286]
https://github.com/Pokechu22/WorldDownloader/issues/79

Seems that the new Optifine 1.12.2 U D1 pre (March 13 , 18) is breaking GUI rendering in WDL . Issue not present in 1.12.2 U C9 .

**Comment by Tsoccerguy3** [comment]
Hi sp614x , this is a Opitifine bug with 1.12.2 U D1 pre .please review WDL's code .There is no logs for this issue , as it is a rendering problem in the GUI menu that was not present in 1.12.2 U C9 .Hopefully it can be fixed before the release of D1 final . Thank You

**Comment by Pokechu22** [comment]
The relevant code in WDL is [in GuiTurningCameraBase](https://github.com/Pokechu22/WorldDownloader/blob/v4.0.1.7/share/src/main/java/wdl/gui/GuiTurningCameraBase.java), which works by changing the render view entity to a new player that is moved around.  (I've linked to the v4.0.1.7 version of the code as it got slightly more complicated in v4.0.2.0, but the changes there are to support some esoteric entity ticking behavior and it occurs in both versions of the code; the linked version is a lot easer to test with).  I'll try to make a very minimal example, one minute.

**Comment by Pokechu22** [comment]
That took a while to set up, but here it is: [OF-1286-mcve-0.1.zip](https://github.com/sp614x/optifine/files/1813361/OF-1286-mcve-0.1.zip)

To reproduce:

0. Install liteloader and add `mod-of-1286-mcve-0.1-mc1.12.2.litemod` to the mods folder (and of course optifine must be installed)
1. Connect to a server.
2. Press the "G" key to open the test GUI
3. Observe that the world vanishes

Some notes:

* Entities remain visible, but block entities do not.
* This doesn't happen in singleplayer, even if `doesGuiPauseGame` is overridden to return false (which I didn't do)
* This issue does not happen with C9, only the D1 prerelease.

**Comment by sp614x** [comment]
Does it still happen with latest D1 preview (it has some forge fixes inside).

**Comment by Tsoccerguy3** [comment]
Hi sp614x , Just tested the new D1 preview and its the same

**Comment by Pokechu22** [comment]
Oh, just as a note: WDL doesn't use forge, and I've been testing with only liteloader.  I didn't have forge installed when I was doing this testing.

**Comment by Tsoccerguy3** [comment]
From Mumfrey

Mixin has the ability to export the classes it modifies (it will also decompile them on-the-fly if fernflower is available on the classpath), so I recommend starting with that to see if you can spot any weird interactions with WDL and OF that are a result of the code getting mangled on injection.

**Comment by Pokechu22** [comment]
The code in question isn't involved in anything that I'm mixing into (and the minimal test case doesn't actually use any mixins, other than those built into liteloader), so I'm not sure how helpful that would be.  I don't know if OF uses mixin or some other thing.

**Comment by sp614x** [comment]
OptiFine is not unsing mixins or bytecode manipulation.

**Comment by sp614x** [comment]
OptiFine works correctly with a custom renderViewEntity. To test it you can enter spectator mode and click on any mob, the camera should switch to the mob perspective and it may enable mob specific shaders.

**Comment by Tsoccerguy3** [comment]
Tested this new release with forge-1.12.2-14.23.2.2631
still broken with WDL litemod . I unzipped both the C9 and D1 pre and did a checksum comparison . 163 files changed out of 2647 more than half those changed files are MD5 and language related .
sp614x , it should be easy enough to go back and check your first commit for D1 and find the problem .
Is there somewhere you stash all these D1 per-releases

**Comment by sp614x** [comment]
The `renderViewEntity` fields `chunkCoordX` and `chunkCoordZ` are not correctly initialized.
```
chunkCoordX = posX >> 4;
chunkCoordZ = posZ >> 4;
```

**Comment by Pokechu22** [comment]
Can confirm that adding that fixes it.  I'll add that to the main repo later today and hopefully release a fixed version of the mod sometime this week.  Thanks!

**Comment by sp614x** [comment]
Updated preview D1 for 1.12.2
 - fixed chunk visibility culling for custom view entity (#1286)
