### ISSUE TITLE
FTB Infinity Evolves crashes

### ISSUE THREAD

**Issue by Bettimine** [sp614x/optifine#1288]
I cannot play Infinity Evolved 1.7.10 with the newest Version because game crashes since OptiFine 1.7.10 HD U D7
[crash-2018-03-14_15.27.46-client.txt](https://github.com/sp614x/optifine/files/1811546/crash-2018-03-14_15.27.46-client.txt)

**Comment by sp614x** [comment]
Looks like incompatible Fastcraft version.
Latest Fastcraft should work.

```
java.lang.NoClassDefFoundError: net/minecraft/client/renderer/texture/TextureMap
	at fastcraft.Z.<clinit>(F:11)
	at fastcraft.ab.<clinit>(F:16125)
	at fastcraft.HC.j(F:70)
...
```
