### ISSUE TITLE
Optifine rendering invalid chunks

### ISSUE THREAD

**Issue by rcmaehl** [sp614x/optifine#1293]
This may have already been reported, however I couldn't find it. 

As seen here:

https://www.youtube.com/watch?v=QUI7iRR9FD8

Optifine seems to load invalid chucks on the client which causes issues with the internal server, possibly from a cache based on wrong world type chucks being rendered.

**Comment by rcmaehl** [comment]
Okay found #1274 which is related but #1274 only covers the Nether where this video shows it occurring in all worlds

**Comment by sp614x** [comment]
Fixed in latest preview D1 for 1.12.2.
