### ISSUE TITLE
Random mob textures with profiles in Multiplayer

### ISSUE THREAD

**Issue by Echoweaver** [sp614x/optifine#1296]
I just started using the Lithos 1.18 texture pack, which has random villager textures using .profile files to direct different skins to different sub-occupations. 

This works fine in single player, but in multiplayer, I am seeing an odd behavior where all villagers load with the (non-mcpatcher) default skin for their primary occupation, then change to a random skin within that primary occupation when I talk to them. The skin chosen is different each time, and it doesn't follow the instructions in the .profile.

I saw this previous ticket regarding random skins in multiplayer and UUIDs: https://github.com/sp614x/optifine/issues/753. I may not have tested against C5. I have tested against 1.12 and 1.12.2 using the corresponding C7, C8, and C9 versions of Optifine.

**Comment by sp614x** [comment]
In multiplayer the server does not send the villager career to the client until the first interaction (trading).
Currently this can't be fixed in OptiFine as it depends on the server.

**Comment by Echoweaver** [comment]
I don't know if comments are answered on closed tickets, but it seemed more appropriate than opening a new one.

OK, that makes sense. When I do talk to the villager, though, it changes skins to a random option, not based on the instructions in the .profile. It's also different every time. Is there some reason that a new, random skin is assigned rather than using the .profile to pick the same one each time as would happen in single-player?

Currently, career-based .profile instructions make a resource pack essentially unusable in multiplayer mode.
