### ISSUE TITLE
atlasSize broken in D1

### ISSUE THREAD

**Issue by MathGeniusJodie** [sp614x/optifine#1298]
using this minimal pom shader to test
[pom test.zip](https://github.com/sp614x/optifine/files/1821032/pom.test.zip)

in C9, atlasSize was broken on hand but worked on terrain
![2018-03-16_19 19 19](https://user-images.githubusercontent.com/26694627/37548774-a2059c58-2950-11e8-883c-be2582e1f84d.png)

in D1, atlasSize is broken on terrain but fixed on hand
![2018-03-16_19 21 37](https://user-images.githubusercontent.com/26694627/37548791-c03c5888-2950-11e8-900d-0f05fe48bf72.png)

**Comment by MathGeniusJodie** [comment]
the offending line is
`* vec3(float(atlasSize.y)/float(atlasSize.x), 1, 1)`
used to correct tangent space vectors for rectangular texture atlases

**Comment by MathGeniusJodie** [comment]
oh @sp614x you wanted an example pom implementation for the wiki didn't you? you can use this one if you want

**Comment by sp614x** [comment]
Fixed, coming in next preview D1.
Terrain works now, but tile entities (chests) and entities (mobs) are still broken as they are not rendered with the texture atlas and the atlasSize is 0.
Wouldn't it be easier to just use `textureSize` as it always returns the correct size?
https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/textureSize.xhtml

**Comment by sp614x** [comment]
Fixed in preview D1.
