### ISSUE TITLE
GUI scale and Chunk Loading option

### ISSUE THREAD

**Issue by DarkAyron** [sp614x/optifine#13]
Optifine version: 1.7.10 HD U D1
OS: Linux 3.2.0
Screen resolution: 1440x900

When changing the GUI scale option from normal to large, the Chunk loading option changes as well. This only happens, when the Minecraft window is maximized or the Fullscreen option is turned on.

**Comment by sp614x** [comment]
Confirmed in 1.7.10 and 1.8.9.
In 1.8.9 the option "Alternate Blocks" is being switched, it is at the same position as "Chunk Loading".
The mouse click handling has a bug (vanilla). After the GUI scale is changed the event handling goes over the rest of the buttons with the old click coordinates (which are no more valid) and triggers another button.

**Comment by sp614x** [comment]
This is a vanilla bug, can not be fixed.
