### ISSUE TITLE
There is a problem with OptiFine 1.11.2 HD U C7!

### ISSUE THREAD

**Issue by tsgrgo** [sp614x/optifine#1302]
With this version of optifine the game doesn't render titles. For example _/title @a title ["",{"text":"hello"}]_ doesn't show text in the middle of the screen. Please fix this bug!

**Comment by sp614x** [comment]
Works for me

![image](https://user-images.githubusercontent.com/16635441/37586794-b8343b74-2b5d-11e8-8f8c-82464ba27e14.png)

**Comment by tsgrgo** [comment]
I am talking about the 1.11.2 optifine. Yes I still use 1.11 .

**Comment by sp614x** [comment]
Works for me in 1.11.2 with OptiFine C7

![image](https://user-images.githubusercontent.com/16635441/37647487-a7bb1ec8-2c2c-11e8-903a-51707a24bfd5.png)
