### ISSUE TITLE
There is impossible to target any method or class in default package using Mixins

### ISSUE THREAD

**Issue by Foghrye4** [sp614x/optifine#1303]
Since I need to write something like "LChunkCacheOF;getBlockState(Lnet/minecraft/util/math/BlockPos;)Lnet/minecraft/block/state/IBlockState;" in target descriptor such Mixins fail sanity check during obfuscation time of mod.
Why its happened: https://github.com/SpongePowered/Mixin/issues/242

**Comment by sp614x** [comment]
Not related to OptiFine.

**Comment by Barteks2x** [comment]
The fact that there is an underlying mixin issue doesn't mean that using the default package is a good idea.

**Comment by sp614x** [comment]
Using default package is legacy, but it is still needed to make backporting to old versions possible.
