### ISSUE TITLE
Add lightmap sampler to composite stages

### ISSUE THREAD

**Issue by Builderb0y** [sp614x/optifine#1304]
I have to handle lighting after all terrain has already been rendered so that light levels can be overridden behind water, but there is no lightmap sampler available at that point. A custom light color function works quite well, but I've gotten more than one request to use the vanilla light colors instead. This is not possible without a lightmap sampler.

**Comment by sp614x** [comment]
Extending custom textures to be loaded by resource location (minecraft:path)
```
# Shader pack
texture.composite.colortex1=textures/noise.png
# Resource pack
texture.composite.colortex2=minecraft:textures/font/ascii.png
# Dynamic (lightmap)
texture.composite.colortex3=minecraft:dynamic/lightmap_1
# Special (texture atlas)
texture.composite.colortex4=minecraft:textures/atlas/blocks.png
```
The lightmap name is `minecraft:dynamic/lightmap_1`.

**Comment by sp614x** [comment]
Updated preview D1 for 1.12.2
- custom textures from resource pack and dynamic textures
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.properties#L92
