### ISSUE TITLE
Titles don't work

### ISSUE THREAD

**Issue by tsgrgo** [sp614x/optifine#1306]
I am talking about the 1.11.2 version of optifine and not the 1.12 one! With this version of optifine the game doesn't render titles. For example /title @A title ["",{"text":"hello"}] doesn't show text in the middle of the screen. Please fix this bug! 
Last time I reported this issue I got a screenshot of minecraft 1.12 and the issue got closed. But as I mentioned earlyer I am using mc 1.11.2.

**Comment by tsgrgo** [comment]
To be precise i have this problem with OptiFine **1.11.2** HD U C7

**Comment by sp614x** [comment]
Works for me in 1.11.2 with OptiFine C7

![image](https://user-images.githubusercontent.com/16635441/37647557-d1f1cf34-2c2c-11e8-8541-5fc9fd357cfc.png)
