### ISSUE TITLE
Black Screen with 1.12 ATM3

### ISSUE THREAD

**Issue by flarefluffsune** [sp614x/optifine#1307]
https://i.gyazo.com/8b47c61ec2462abe4bf73e52355f6e7a.mp4

Been trying to get Optifine working with FTB's All the Mods 3, I know Astral Sorcery usually gives me problems with its custom skyboxes so those are easily removed using the mods config but when I try and use shaders with this pack all I keep getting is a black screen. Using 1.12 D1 Pre with Chocapic13 V6 Extreme shaders.

![2018-03-19_18 55 44](https://user-images.githubusercontent.com/20187367/37616396-b43ef578-2ba7-11e8-84a4-3a537cb11615.png)

**Comment by flarefluffsune** [comment]
[latest.log](https://github.com/sp614x/optifine/files/1828498/latest.log)
Just uploading this in case anything from here may help diagnose the issue.

**Comment by sp614x** [comment]
![image](https://user-images.githubusercontent.com/16635441/37646957-56c0a91c-2c2b-11e8-929e-bfaa554578c7.png)

Most probably a conflict with one of the 232 installed mods.
To find the problemstic mod:
- split mods in half and test with one half of them
- keep the mods which reproduce the problem
- repeat until only one mod is left

**Comment by flarefluffsune** [comment]
It could be the shader's itself, I have tried multiple shader packs now and found one that is functioning but now I get this issue. As for the mods I've been working on that too.
![2018-03-20_12 07 51](https://user-images.githubusercontent.com/20187367/37653711-b28e46ee-2c37-11e8-9eba-d6f4e9b23b4c.png)
This is using Kuda Shaders 6.1 Legacy which is the most up-to-date version.

I'm starting to feel this is just shader issues itself and not Optifine lol I will try some other shader packs between having a look at the mods.

**Comment by flarefluffsune** [comment]
![2018-03-20_15 22 28](https://user-images.githubusercontent.com/20187367/37664184-b2d8a994-2c52-11e8-8eb9-60369b74a333.png)

Okay it appears I have found the cause, it was Advanced Rocketry, after trawling the config for culprits seems that the cause was the mod rendering a skybox on the overworld. Specifically these settings (which I have changed to false):
```javascript
    # If true, AR will use a custom skybox on planets
    B:PlanetSkyOverride=false
    # If UI is not locked, the middle mouse can be used to drag certain AR UIs around the screen, positions are saved on hitting quit in the menu
    B:overworldSkyOverride=false
```
There's another one in the middle of
```javascript
    # If true, AR will use a custom skybox on space stations
    B:StationSkyOverride=true
```
But won't know what effect that has until i get to that stage, playing on a server and I know nothing of the mod.

**Comment by sp614x** [comment]
Relevant https://github.com/zmaster587/AdvancedRocketry/issues/1076
Seems to be a known Advanced Rocketry problem with shaders.

**Comment by 1butler1** [comment]
This happens to me but I'm unable to see the GUI or anything on my screen. My entire window is black screened, nothing I can do but restart and sometimes that doesn't even fix it.

**Comment by TopCraft** [comment]
> This happens to me but I'm unable to see the GUI or anything on my screen. My entire window is black screened, nothing I can do but restart and sometimes that doesn't even fix it. I don't even use shaders either.

Same thing for me I can still interact and hear sound and the mini map but everything else is black...
