### ISSUE TITLE
 mod modern warfare 

### ISSUE THREAD

**Issue by tyrex30** [sp614x/optifine#1308]
mod Modern Warfare has a bug that puts the inconos of the weapons is blank and when points with the weapon is put into the screen this happens only when you put the optifine mod

**Comment by sp614x** [comment]
Example screenshot with and without OptiFine?

**Comment by xLastt** [comment]
Hmmm your PC specs?

**Comment by LithTheKitten** [comment]
get rid of fast rendering,

**Comment by KaiAF** [comment]
No response, if you still having issues, let us know.
