### ISSUE TITLE
Barrier particles.

### ISSUE THREAD

**Issue by TimkaG** [sp614x/optifine#131]
When player hold barrier in hand, count of particles "barrier" is more than count of barriers. Therefore FPS decreases.
For example, 1024 barriers create ≈4050 particles, but this barriers might create 1024 particles.
![2016-05-28_20 45 46](https://cloud.githubusercontent.com/assets/17567951/15629387/9307fc36-2520-11e6-8d6a-314543425cd9.png)
![2016-05-28_20 42 34](https://cloud.githubusercontent.com/assets/17567951/15629388/93083b7e-2520-11e6-8b99-ca3b71d80f3a.png)
Please optimise it.

**Comment by sp614x** [comment]
Fixed in B5_pre, now the number of particles should be the same as the barrier blocks.
Also fixed barrier block in off hand to show barrier particles.
