### ISSUE TITLE
Block textures of odd resolution look blurry with mipmapping enabled

### ISSUE THREAD

**Issue by Brottweiler** [sp614x/optifine#1316]
Using `OptiFine 1.12.2_HD_U_D1`, when having mipmapping enabled and using a [resource pack with 7x7 block textures](https://minecraft.curseforge.com/projects/prime-craft-7x7-faithful), the textures for blocks look blurry. It's like the game is trying to scale the 7x7 textures to 16x16 and it's not using "nearest neighbour" method. 

This does not happen without optifine.

![2018-03-24_01 14 40](https://user-images.githubusercontent.com/1613137/37868590-5b59e372-2fa9-11e8-8170-9eed37ffacd6.png)

**Comment by VignetteCoeff** [comment]
Textures for optifine have to be to the power of two to work if I remember correctly.

**Comment by sp614x** [comment]
Only power of 2 textures are compatible with mipmaps.
When textures are not power of 2:
- vanilla lowers or disables mipmaps
- OptiFine scales the images to power of 2 so that mipmaps can stay enabled

**Comment by GDEngine** [comment]
Is there any way to disable optifine scaling textures to the power of 2 while still keeping mipmaps on?
