### ISSUE TITLE
In gbuffers_water, depthtex1 is blank when depthtex2 is not enabled

### ISSUE THREAD

**Issue by zombye** [sp614x/optifine#1319]
Presumably affects all programs between deferred and composite, but I have not checked.

**Comment by sp614x** [comment]
OptiFine 1.12.2_HD_U_D2_pre
 - fixed shaders uniform "depthtex1" in program "gbuffers_water"
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.txt#L184
