### ISSUE TITLE
Offhand Torch Lighting

### ISSUE THREAD

**Issue by J4D3N** [sp614x/optifine#132]
When playing with OptiFine I noticed that the lighting in the players offhand doesn't display the same lighting effect as if it were being held in the main hand; I presumed this is a bug, and would think it should do the same no matter what hand a torch (for example) is in.

![2016-05-29_13 20 16](https://cloud.githubusercontent.com/assets/6133275/15633285/7a4d6afc-25a0-11e6-9f74-e0c51ed09e9a.png)
![2016-05-29_13 20 29](https://cloud.githubusercontent.com/assets/6133275/15633284/7a4c5b94-25a0-11e6-96a3-ad1f7fb2b8c9.png)

**Comment by HeartyYF** [comment]
What's your Minecraft version and OptiFine version?

**Comment by J4D3N** [comment]
1.9.4-Optifine HD U B4

**Comment by sp614x** [comment]
What shaderpsck?
How is the option "Shaders -> Old Hand Light" set?

**Comment by J4D3N** [comment]
Sorry for the delay, I am using "Slidurs Vibrant Shaders v1.141 Medium" with old hand lighting turned off.

**Comment by sp614x** [comment]
Set "Old Hand Light" and "Old Lighting" to Default.
They should only be changed if the shader pack has some problems.

**Comment by J4D3N** [comment]
Thanks for solving my issue.
