### ISSUE TITLE
No sound randomly with Forge or Mods

### ISSUE THREAD

**Issue by lostallmymoney** [sp614x/optifine#1322]
I need to launch minecraft like 10 times with optifine to get sound to work. Also when i try to do F3 + T in game i get this crash : https://puu.sh/zPDGz/c803fd7175.txt . Thx for trying to solve it it's really annoying to launch minecraft 10 times to get a modpack working. Here's the full log : https://puu.sh/zPDMU/4d3fae56d9.log . Not too sure what mod it is but i tried removing all the 'fps' mods one by one and it still crashed and i got no sound.

**Comment by dannyss6** [comment]
Here's the modpack if anyone wants the mods used : https://1drv.ms/u/s!AlHoTsCx5kumgrYqgEUhNow9SJUHRA

**Comment by dannyss6** [comment]
The bug happens before loading a game.

**Comment by dannyss6** [comment]
![17635edb2e 1](https://user-images.githubusercontent.com/6634309/37890369-66e8046c-309e-11e8-8f52-d0404eafe4ea.png)

Is not linked to : 
AppleCore,
AppleSkin,
BetterFps,
Chameleon,
EnderStorage,
FoamFix,
JEI -all of them,
QuantumStorage
RebornCore,
InventoryTweaks,
Customport.

I haven't trimmed all the mods but i did a part.
I doubt it's linked to Quark, OpenGlider, Tri-Addon, randompatches and gravestone.

**Comment by sp614x** [comment]
Can you reproduce the problem with the minimal number of mods (Forge + OptiFine + one other mod)?

**Comment by wjunniorw** [comment]
Could you fix it? I have the same problem.

**Comment by KaiAF** [comment]
Unfortunately, the logs you provided don't exist anymore. If you have the same issue, please create a new bug report with the correct format.
