### ISSUE TITLE
 OptiFine 1.12.2 HD U D2 pre has no option to extract & more

### ISSUE THREAD

**Issue by MisterQuiggly** [sp614x/optifine#1324]
The title says it all. There is no extract option on the installer for the new preview version. Also, if you increased the limit of method repeat (I don't know if you did in this version), then you forgot to mention it in the changelog unless you didn't want to mention it, or if you didn't add it like I mentioned. But I just thought I'd point that out.

**Comment by MisterQuiggly** [comment]
Somehow forced the minecraft I use to recognize the installer as the mod so that works. In terms of the limit we discussed earlier, I don't know the situation with that. But, instead of not showing up at all and just showing the normal grass texture, it all shows up as the purple missing texture, so that's new in this version.

**Comment by sp614x** [comment]
OptiFine 1.12.2_HD_U_D2
 - removed width and height limits for CTM method "repeat"
 - fixed installer button "Extract"

**Comment by MisterQuiggly** [comment]
![2018-03-26_22 38 21](https://user-images.githubusercontent.com/26760490/37944716-b90f86e6-314a-11e8-8cc4-3b1f57833be3.png)
Have any idea why I'm getting this missing texture problem? These are the same files I sent you before and you got them to work.

**Comment by sp614x** [comment]
You should check the error log (game output) for errors and warnings.

**Comment by MisterQuiggly** [comment]
The folder used to be in the folder for my other grass texture that I disabled to get the giant one to work. I moved it to its own separate place so now it doesn't show missing textures but it just shows the default grass texture. I reloaded my texture pack then found this in my log:

[15:42:09] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/nature/grass_top/grass_top.properties
[15:42:09] [Client thread/WARN]: [OptiFine] Invalid width: mcpatcher/ctm/nature/grass_top/grass_top.properties

I don't understand why it says invalid width, its the same as the height, which is 64.

**Comment by sp614x** [comment]
The warning "Invalid width" is shown when "width" is not set or less than 1.

**Comment by MisterQuiggly** [comment]
> matchTiles=grass_top
> method=repeat
> tiles=[removed or else it would be really long, but I gave you the file earlier]
> width=64
> height=64

That is the exact file, it is set and it is not less than 1.

**Comment by sp614x** [comment]
Can you try to put the tiles after width/height?

**Comment by MisterQuiggly** [comment]
Same output, invalid width. What I don't understand is how you got it to work, unless what you did was different than the version of optifine you released.

**Comment by sp614x** [comment]
Can you post the RP link again, it was removed from the previous issue?

**Comment by sp614x** [comment]
Latest preview D2 works for me.
Build 20180328-135713.
```
[22:46:52] [main/INFO]: [OptiFine] OptiFine_1.12.2_HD_U_D2_pre
[22:46:52] [main/INFO]: [OptiFine] Build: 20180328-135713
...
[22:46:58] [main/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/grass_64x64/grass_top.properties
[22:47:01] [main/INFO]: [OptiFine] Multipass connected textures: false
```
