### ISSUE TITLE
The end is broken with the newest update.

### ISSUE THREAD

**Issue by unknownxgamer** [sp614x/optifine#1326]
With the newest update to optifine (version 1.12.2 HD U D1) travelling to the end causes the game to no longer recognize armor or other worn equipment(like the alytra).

When then travelling from the end back to the overworld only the first 10 or so chunks around the player will load, walking too far in any direction at this point causes the game to crash.

Also, when creating a new world to test the glitch in creative a similar thing happened, only the game did not crash and instead took an extremely long amount of time to load the chunks before it stopped loading them altogether.

Reverting back to the previous version fixed this issue.

**Comment by sp614x** [comment]
How is the game not recognizing armor/elytra?
Crash report (error log)?
Forge version, other mods installed?

**Comment by unknownxgamer** [comment]
Worn equipment is not recognized in the sense that armor rating becomes zero and the alytra is unusable inside the end.

[crash-2018-03-25_05.06.35-server.txt](https://github.com/sp614x/optifine/files/1851249/crash-2018-03-25_05.06.35-server.txt)

No mods or mod loader beside optifine is installed.

**Comment by sp614x** [comment]
OptiFine 1.12.2_HD_U_D2
 - fixed End loading bug (#1326)
