### ISSUE TITLE
Custom text label color for the GUIs

### ISSUE THREAD

**Issue by Regnander** [sp614x/optifine#1335]
I _love_ Painterly Pack for its wooden and stone GUIs, but there's one thing that is bothering me with the darker ones - namely, the label backgrounds. (Please ignore the giant numbers on the grass blocks as they are a part of a `overlay_random` experiment.)

![a](https://user-images.githubusercontent.com/17113053/38178237-a68b7cbe-360e-11e8-980f-36484f750dfd.png)

Let's boot up an image editing software and get rid of them!

![b](https://user-images.githubusercontent.com/17113053/38178257-23cdba16-360f-11e8-8b1c-fce263ad3df2.png)

Oops. Now it's almost impossible to read the labels. What I want is a way to change the color of the text labels. For example, if I were to select the `§f` [color code](https://minecraft.gamepedia.com/Formatting_codes#Color_codes) for the furnace GUI, it would look like this:

![c](https://user-images.githubusercontent.com/17113053/38178290-bd0416f8-360f-11e8-9558-4b1bb1240990.png)

Much better. Or if I selected `§6`, it would look like this instead:

![d](https://user-images.githubusercontent.com/17113053/38178352-5053bebc-3611-11e8-9bb8-01d0ad2e86f6.png)

Okay, maybe not the best choice of color, but I hope you get the point!

**Comment by aws404** [comment]
You could all ways just change your en_US.lang file to have the color code before the GUI name.

**Comment by Regnander** [comment]
That's a really good idea since the color change only seems to affect the text in the GUI and nowhere else. I just tried it out and it works fantastic, but since the "Inventory" string is used in other GUIs and my chest GUI happens to have a light wooden background, I get this:

![a](https://user-images.githubusercontent.com/17113053/38471510-6db527be-3b72-11e8-8312-c589e3f5ff17.png)

Sure, I could change it to a dark wooden GUI, but I want to have the freedom to select a different color for each GUI.

**Comment by Regnander** [comment]
I just found [`color.properties`](https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/color.properties) while scanning the `doc` folder and I believe this would fit perfectly under the "Text colors" section:
> text.chest.normal=000000
> text.anvil=000000
> text.furnace=000000

**Comment by QuImUfu** [comment]
A little addition.  
The colour of the "magical glyphs" in the enchanting table should be customizable as well.

**Comment by Regnander** [comment]
I'm closing this since #3175 got more attention.
