### ISSUE TITLE
Turning Dynamic FOV off does not stop underwater fov change.

### ISSUE THREAD

**Issue by GlitchHead** [sp614x/optifine#1339]
Is this intended? If so could you add a new option to disable the underwater fov change?

**Comment by sp614x** [comment]
The underwater FOV change is not dynamic (based on player action). 
It simulates the vision change when diving underwater: https://en.wikipedia.org/wiki/Underwater_vision#Humans

**Comment by Dainternetdude** [comment]
Sprinting is a player action and it is affected by Dynamic FOV, is this a bug?
