### ISSUE TITLE
[1.7.10_HD_U_E7] Incorrect version being reported... somewhere

### ISSUE THREAD

**Issue by Sinxar** [sp614x/optifine#1343]
Keeps bugging me to update when I already have latest version installed from the website. I tried a few more times and each time it shows the incorrect version on the title screen.

Here we have the mods being used
![untitled](https://user-images.githubusercontent.com/3210315/38460219-7a114d66-3a83-11e8-979d-b9dac77fa440.png)

Title screen report of versions
![javaw 2018-04-07 16-40-02-410](https://user-images.githubusercontent.com/3210315/38460222-87fc1988-3a83-11e8-877a-63853a9afbdf.jpg)

Ingame nag
![javaw 2018-04-07 16-40-17-321](https://user-images.githubusercontent.com/3210315/38460224-8ea66586-3a83-11e8-9c10-4e170a0bf980.jpg)

**Comment by sp614x** [comment]
Forge always searches in a version specific folder first (1.7.10) and then in the main folder. 
If this is your "mods" folder, then you probably have an OptiFine E3 in the "1.7.10" folder which gets loaded.

**Comment by Sinxar** [comment]
The "1.7.10" folder (yes the one shown is inside the "mods" folder) only has "CodeChickenLib-1.7.10-1.1.3.138-universal.jar" in it. I checked the versions folder where the game is actually kept and it only has "1.7.10.jar" and "1.7.10.json". And it seems you are right but where is it loading this version of optifine from? Searching the .minecraft folder only turns up this:
![untitled](https://user-images.githubusercontent.com/3210315/38646877-c335317e-3db7-11e8-8848-897aa93071fc.png)

**Comment by sp614x** [comment]
Either OptiFine is put directly in the "1.7.10.jar" or it is being loaded by the "1.7.10.json".
In any case the launcher finds and loads an OptiFine E3 from somewhere.

**Comment by Sinxar** [comment]
Thanks for your support. I'll try to figure it out soon.
