### ISSUE TITLE
gbufferProjection & gbufferProjectionInverse don't properly update when under water.

### ISSUE THREAD

**Issue by jcm2606** [sp614x/optifine#1344]
So this has been an issue for a long time, even back as far as when Karyonix's shaders mod was still relevant. Shaders have got some workarounds, though I feel as if it should be officially fixed on Optifine's end, as that way shaders wouldn't have to work around the issue.

**Comment by zombye** [comment]
#827

**Comment by sp614x** [comment]
OptiFine 1.12.2_HD_U_D2_pre
 - fixed shaders projection matrix when underwater (#1344, #827)
