### ISSUE TITLE
LittleTiles - Add support for emissive textures

### ISSUE THREAD

**Issue by CreativeMD** [sp614x/optifine#1345]
Hey there,
it's me again :) LittleTiles does not support emissive textures, is there a way to add support for it?
https://github.com/CreativeMD/LittleTiles/issues/83

Unfortunately I can't look at the source and find it out myself. As you might remember LittleTiles renders its blocks separately.

Furthermore the option "Render Regions" is not supported as well, probably due to the fact that the render data is added to the VertexBuffer before its uploaded to the gpu.

**Comment by sp614x** [comment]
This seems to be a LittleTiles issue, not directly related to OptiFine.

**Comment by CreativeMD** [comment]
Of course not :D, but I in order to fix it from my end I need to now how to works.

**Comment by sp614x** [comment]
Render regions work by using one offset for a group of chunks and then rendering them at once. 
RenderChunk.preRenderBlocks() uses the common offset instead of the offset per chunk.

**Comment by CreativeMD** [comment]
How are these blocks rendered? I need to know which method to call and when ([example](https://github.com/CreativeMD/LittleTiles/blob/1.12/src/main/java/com/creativemd/littletiles/client/render/RenderingThread.java#L265)).
Maybe you can show me the source of the render method? Otherwise I will try to decompile your mod in order to see how things are done (I doubt that there is a different way to do things).

**Comment by sp614x** [comment]
The BlockModelCustomizer.getRenderQuads() adds the emissive quads.

**Comment by CreativeMD** [comment]
Ok, I finally found some time to work on it, but it does not work in the way I expected it:

before
```java
List<BakedQuad> blockQuads = blockModel.getQuads(state, facing, rand)
```
after
```java
List<BakedQuad> blockQuads = BlockModelCustomizer.getRenderQuads(blockModel.getQuads(state, facing, rand), world, state, pos, facing, layer, rand, renderEnv);
```

![](https://i.imgur.com/Jgv8q5W.png)

Basically the result is the same (no emissive quads). I'm not sure about the RenderEnv object, for now I created a ThreadLocal field and use RenderEnv.reset() for each call (don't know if it is intended to work like that).

Is there a method I could use to get all quads from a block which includes features (like emissive, connected textures, better grass, etc.) ?

**Comment by CreativeMD** [comment]
Seems like the new version of Optifine E1 changes many things. I will try to update to it soon, but I still don't know how to get connected and emissive textures working.

**Comment by sp614x** [comment]
E1 mostly reorganizes the OptiFine classes in separate packages `net.optifine.*`. 
The connected/emisive textures should work identically.

**Comment by CreativeMD** [comment]
Ok, but how did they work before? I tried to implement support for it (as explained above), but it didn't work.

**Comment by CreativeMD** [comment]
Thanks to @Barteks2x I could add Optifine to my dev environment. That made it easier for me to look at the source code and do some debugging. I managed to add support for render regions and to get connected textures working (had to use some asm hacks to make it connect between all blocks).
![](https://cdn.discordapp.com/attachments/375349590100017155/466302166697508884/2018-07-10_19.57.37.png)

Unfortunately EmmsiveTextures still don't work although I'm using the BlockModelCustomizer. Is there anything extra I need to do?
