### ISSUE TITLE
[1.7.10-E3, D8] Crash with ClassNotFoundException: bxf

### ISSUE THREAD

**Issue by chaos234** [sp614x/optifine#1348]
Like the title states, there is also a client crash with the E3 version.

Log: https://paste.ee/p/BpVeQ
Log2: https://paste.ee/p/4c7yU
Task: Fixing it, because of multiple involved Core patches from other mods, it is indeed the fault of optifine.

**Comment by Builderb0y** [comment]
As stated in [your last issue](https://github.com/sp614x/optifine/issues/1347), you need to update fastcraft to 1.25. You're still on 1.23. You also have multiple versions of optifine installed, one of which isn't even for MC 1.7.10.

**Comment by sp614x** [comment]
You should update to FastCraft 1.25
https://minecraft.curseforge.com/projects/fastcraft/files
