### ISSUE TITLE
Openblocks Skyblocks

### ISSUE THREAD

**Issue by mthp1999** [sp614x/optifine#1351]
Optifine installed is preventing the openblocks skyblocks from rendering correctly. Instead of a sky immitation, they are wavy grey lines. See [link](https://imgur.com/a/CVDpf) for example

**Comment by sp614x** [comment]
OpenBlocks is disabling the skyblocks rendering when OptiFine is installed, no idea why.
```
[09:39:07] [main/INFO] [OpenMods]: openblocks.client.renderer.SkyBlockRenderer.setup(SkyBlockRenderer.java:82): Disabled due to Optifine (use `optifineOverride` config to override)
```

**Comment by sp614x** [comment]
The skyblocks use a complex way to render: https://github.com/OpenMods/OpenBlocks/issues/891#issuecomment-368592665
This is probably not compatibe with some OptiFine features (shaders).

**Comment by sp614x** [comment]
You can enable the skyblock rendering by setting `optifineOverride=true` in `config/openblocks.cfg`.

**Comment by sp614x** [comment]
OpenBlocks could dynamically check if shaders are enabled so the manual configuration would not be needed: https://github.com/OpenMods/OpenBlocks/issues/908
