### ISSUE TITLE
Capes should be fetched over an HTTPS connection.

### ISSUE THREAD

**Issue by LogalDeveloper** [sp614x/optifine#1358]
Capes are currently fetched over a plaintext HTTP connection. This should be upgraded to an HTTPS connection.

**Comment by sp614x** [comment]
There is no need for encription. The capes are public and read-only.
The HTTPS would only slow down the cape download (SSL handshake) and put additional load on the server.

**Comment by LogalDeveloper** [comment]
That’s not a reason to not use HTTPS. This website should explain everything: https://doesmysiteneedhttps.com/

**Comment by anjum-ahmed** [comment]
Wrong. HTTPS would faciliate better speed advantage. https://www.troyhunt.com/i-wanna-go-fast-https-massive-speed-advantage/

**Comment by humaidq** [comment]
@anjum-ahmed That seems to be the case with modern web browsers, not Java's HTTP client.  
Looking at doesmysiteneedhttps.com, it seems the disadvantages outweighs the advantages of having HTTPS for this static image server.
