### ISSUE TITLE
Optifine Lags Entire System

### ISSUE THREAD

**Issue by ColouredGlass** [sp614x/optifine#1359]
When I use Optifine and I tab out, say to change songs on Spotify, my computer doesn't let me tab back in to Minecraft. Doing this opens up a little box in the top left corner of my screen that says Minecraft 1.12.2. I've tried installing different versions of Optifine and it continues to do this.
The game itself doesn't lag but here are my specs:
i5 6500
GTX 1050ti
8gb DDr4
MSI b150 MOBO
pls help ty
xd

**Comment by sp614x** [comment]
There is nothing in OptiFine that should cause that.
I have no idea what the problem is or how it could be fixed.
