### ISSUE TITLE
CTM: tiles=default not working correctly

### ISSUE THREAD

**Issue by joblo2213** [sp614x/optifine#1360]
I'm working on a addon for a existing resourcepack which uses ctm. Therefor I want to override these.

As [the documentation](https://github.com/sp614x/optifine/blob/eaf2c02db2370ae5dd5ead404bb285fc31d6bf8d/OptiFineDoc/doc/ctm.properties#L89) says: 
> ```properties
> # (Required) List of replacment tiles to use.  Each tile must be a separate
> # image, just like terrain and item textures.  Tiles can be specified in
> # several ways
> #   0                   -> 0.png
> #   8-11                -> 8.png, 9.png, 10.png, 11.png
> #   name                -> name.png
> #   name.png            -> name.png
> #   default             -> none, use the default texture for that block/tile
> #   full/path/name.png  -> full/path/name.png
> # In all cases but the last, the png file must be in the same directory as
> # the properties file itself.
> # The formats can be mixed and matched, e.g.
> #   tiles=0-4 5 some/other/name.png
> # The overlay methods may use the special name "<skip>" for empty tiles 
> # that are to be skipped.
> tiles=<list of tiles>
> ```

I have the following defined in a properties file:
```properties
weight=1000
matchBlocks=glass
method=fixed
tiles=default
```

And I am getting the following error:
```
[10:32:29] [main/WARN]: [OptiFine] File not found: mcpatcher/ctm/overrides/default.png
```

For me this seems like `tiles=default` is not detected by the code corrctly and instead considered to be a filename.

I'm using `OptiFine 1.12.1_HD_U_C7`

**Comment by sp614x** [comment]
The check for tile "default" is not implemented yet. 
The documentation is a bit ahead of the real code.

**Comment by joblo2213** [comment]
Any progress on this?

**Comment by sp614x** [comment]
It should probably be implemented as "<default>", like "<skip>" to avoid collision with a texture named "default.png".

**Comment by sp614x** [comment]
OptiFine 1.12.2_HD_U_E1
 - added CTM tile name `<default>`
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/ctm.properties#L90

**Comment by joblo2213** [comment]
Thanks for adding :+1:
It saves a lot of work.
