### ISSUE TITLE
Error installing 1.12.2

### ISSUE THREAD

**Issue by Feksa** [sp614x/optifine#1361]
I had the newest version (1.12.2, version HD U D1) installed a bit ago, then I installed 1.8.9 (HD U I7) and when i re-downloaded the 1.12.2 installer and tried to install (I hit [Extract] in hopes of it making a new instance instead of overwriting the existing 1.8.9 version) it didn't pop up with the usual message of "Successfully installed!" but instead gave no message, and made a new error file which i've attached.
Pressing the [Install] button worked fine, though. This issue only happened with [Extract].
[hs_err_pid1504.log](https://github.com/sp614x/optifine/files/1934608/hs_err_pid1504.log)

**Comment by sp614x** [comment]
This looks like a Java problem, reinstalling Java could fix it.
You have Java 1.8.0_131, latest is 1.8.0_172.

```
Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  sun.awt.shell.Win32ShellFolder2.getDisplayNameOf(JJI)Ljava/lang/String;+0
j  sun.awt.shell.Win32ShellFolder2.access$1600(JJI)Ljava/lang/String;+4
j  sun.awt.shell.Win32ShellFolder2$13.call()Ljava/lang/String;+15
j  sun.awt.shell.Win32ShellFolder2$13.call()Ljava/lang/Object;+1
J 915 C1 java.util.concurrent.FutureTask.run()V (126 bytes) @ 0x0000000005502dcc [0x0000000005502b80+0x24c]
j  java.util.concurrent.ThreadPoolExecutor.runWorker(Ljava/util/concurrent/ThreadPoolExecutor$Worker;)V+95
j  java.util.concurrent.ThreadPoolExecutor$Worker.run()V+5
j  sun.awt.shell.Win32ShellFolderManager2$ComInvoker$3.run()V+7
j  java.lang.Thread.run()V+11
v  ~StubRoutines::call_stub
```
