### ISSUE TITLE
Has Labymod permission to redistribute your mod?

### ISSUE THREAD

**Issue by GGWarriorWP** [sp614x/optifine#1363]
Just asking cause they do
Here is the json file that shows your mod: http://dl.labymod.net/addons.json
Here is a direct download link: dl.labymod.net/latest/?file=7d62bffd-fe3f-4667-8200-e8decb384fa0&a=1
Here is their installer http://dl.labymod.net/latest/install/LabyMod3_Installer.jar
They even advertise this on their main page, here a link to the image: https://www.labymod.net/page/tpl/assets/images/screenshots/3/6.jpg
Here is the main page: https://www.labymod.net/

**Comment by sp614x** [comment]
LabyMod doesn't have permission to distribute OptiFine.
