### ISSUE TITLE
[1.12.2 + D1/D2] OpenGL error 1281 involving Voxelmap + shaders + resource packs.

### ISSUE THREAD

**Issue by Geethebluesky** [sp614x/optifine#1365]
(note: I've submitted this report to the Voxelmap thread as well as helpfully suggested, I hope that's OK).

Versions:
**Java**: jre1.8.0_162
**MC Forge**: Recommended 1.12.2 - 14.23.3.2655
**Liteloader** 1.12.2 snapshot
**Optifine**: preview_OptiFine_1.12.2_HD_U_D2_pre.jar
(also occurs with version D1, but d2 provides a more verbose log)
**Card**: Nvidia GTX 980. 391.35 drivers (latest released)
**Resource pack**: Sphax PureBDcraft for 1.12, 32x resolution, available [here](http://bdcraft.net/purebdcraft-minecraft)

Setup + steps to reproduce (all scenarios I could think of, with the one that errors in bold):

- Minecraft setup with a clean launcher profile and versions above. Don't change any video options, don't load respack yet.
- Generate a new vanilla world: no error yet.
- Enable internal Optifine shaders: no error yet.
- **Enable resource pack: error 1281 (combination of shaders + Voxelmap + resource pack is what triggers it.)**

Game without resource pack (Voxelmap + shaders): no error.
Game without shaders (Voxelmap + resource pack): no error.
Game without Voxelmap (shaders + resource pack): no error.

Enabling and disabling the various options while in-game start or stop triggering the error with no restart needed. This doesn't trigger a crash.

Here is a shortened [latest.log ](https://pastebin.com/gV7ZDUhW) where I removed long chunks of repeated error output to make it kind of readable (those sections are marked).

**Comment by sp614x** [comment]
Voxelmap is trying to do something with the CTM textures:
[11:27:40] [main/INFO]: [com.mamiyaotaru.voxelmap.a:do:1600]: error getting CTM block from mcpatcher/ctm/glass/frame/block102.properties: mcpatcher/ctm/glass/frame/block102.properties 102 0 mcpatcher/ctm/glass/frame/textures/blocks/glass.png

**Comment by sp614x** [comment]
Testing Forge #2627 + LiteLoader 1.12.2 + OptiFine D2_pre + VoxelMap 1.12.2 + Internal shaders.
No OpenGL errors, everything seems to work.

![image](https://user-images.githubusercontent.com/16635441/39155530-aa94371a-4752-11e8-8b18-c6936b656cd0.png)

![image](https://user-images.githubusercontent.com/16635441/39155604-ee31aea8-4752-11e8-98e4-4f518e02fbcc.png)

Loading Sildur's Vibrant Shaders 1.163 also works.

![image](https://user-images.githubusercontent.com/16635441/39155661-2e9da528-4753-11e8-9ddb-4f065c6bbad6.png)

**Comment by sp614x** [comment]
OptiFine D2_pre is compatible with Forge #2627, you have Forge #2655. 
There are some significant changes in Forge for which OptiFine is not updated yet.

**Comment by Geethebluesky** [comment]
Thanks!

**Comment by Geethebluesky** [comment]
Question, I checked the changelog but I'm not sure if the changes have now been accounted for in D3 (with Forge 2705?)

I'm getting a tesselation error involving this time a mod (Agricraft), Voxelmaps, and a resource pack, that only occurs when all four + Optifine D3 are run together.

Is it worth opening a new issue? Trying to avoid cluttering and confusing anyone.
