### ISSUE TITLE
1.12.2 HD U D1 crash on launch

### ISSUE THREAD

**Issue by CirnoTheFrosty** [sp614x/optifine#1369]
Crash log is as follows:

[20:25:22] [main/ERROR] [LaunchWrapper]: Unable to launch
--
13:25:22 | game |   | java.lang.reflect.InvocationTargetException: null
13:25:22 | game |   | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
13:25:22 | game |   | at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
13:25:22 | game |   | at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
13:25:22 | game |   | at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_171]
13:25:22 | game |   | at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
13:25:22 | game |   | at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
13:25:22 | game |   | Caused by: java.lang.NoClassDefFoundError: Could not initialize class Reflector
13:25:22 | game |   | at net.minecraft.crash.CrashReport.func_71504_g(CrashReport.java:138) ~[b.class:?]
13:25:22 | game |   | at net.minecraft.crash.CrashReport.<init>(CrashReport.java:54) ~[b.class:?]
13:25:22 | game |   | at net.minecraft.crash.CrashReport.func_85055_a(CrashReport.java:425) ~[b.class:?]
13:25:22 | game |   | at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:381) ~[bib.class:?]
13:25:22 | game |   | at net.minecraft.client.main.Main.main(SourceFile:123) ~[Main.class:?]
13:25:22 | game |   | ... 6 more
13:25:22 | game |   | Exception in thread "Client thread" [20:25:22] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
13:25:22 | game |   | [20:25:22] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
13:25:22 | game |   | [20:25:22] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
13:25:22 | game |   | [20:25:22] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Runtime.exit(Unknown Source)
13:25:22 | game |   | [20:25:22] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.System.exit(Unknown Source)
13:25:22 | game |   | [20:25:22] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
13:25:22 | game |   | [20:25:22] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Mods used:
Forge 1.12.2 ver 14.23.3.2655
Crosshair Mod 0.8.2-mc1.12
Cubic Chunks 1.12.2-0.0.809.0-all_(AntVenom build - with Farlands)
Inventory Tweaks 1.63
JourneyMap 5.4.9
Optifine HD U D1 MOD
Squake 1.0.4
Squeedometer 1.0.3
WorldEdit 6.1.8

Tried across multiple java versions as well, including the one packaged with the launcher and the most current Java release

**Comment by sp614x** [comment]
Most robably a conflict with Cubic Chunks.
For OptiFine D1 you need the latest CubicChunks-1.12.2-0.0.826 (https://cdn.discordapp.com/attachments/322363883698520065/437413095976206336/CubicChunks-1.12.2-0.0.826.0-SNAPSHOT-all.jar)
Alternatively you can try the older OptiFine C9, it should work with older Cubic chunks versions.

**Comment by CirnoTheFrosty** [comment]
If having more advanced control over my video settings means removing the farlands patched version of CubicChunks that I have installed, then that is a sacrifice I must make I guess.
Thanks for the heads up, wasn't aware of any incompatibilities with CC before hand

**Comment by sp614x** [comment]
OptiFine C9 should work.
