### ISSUE TITLE
No sounds 1.12.2_HD_U_D1

### ISSUE THREAD

**Issue by babybasher** [sp614x/optifine#1370]
Game launches with sounds not working.  Once I get into a world pressing F3+T to reload will fix issue.

Using Forge 1.12.2-14.23.3.2655

Removed all other mods having ONLY optifine, issue persisted.

Put all other mods back in folder, removed optifine and sound works as normal.

**Comment by NerfyZygon** [comment]
I have the same issue, but with me f3+T does not work, here is my game log, i only use optifine.
[latest.log](https://github.com/sp614x/optifine/files/1951608/latest.log)

**Comment by Jak81** [comment]
Same problem with Forge 1.12.2-14.23.3.2691 and Optifine 1.12.2_HD_U_D3.
No sounds, F3+T helped, but that shouldn't be the only way to play with sounds.

**Comment by KaiAF** [comment]
If this is still an issue, let me know.
