### ISSUE TITLE
Random Entities - Horse GUI

### ISSUE THREAD

**Issue by aws404** [sp614x/optifine#1371]
Its just a minor issue, that in reality does not affect much at all but when a horse has a custom texture it will still show as the default inside the inventory.
Example:

![image](https://user-images.githubusercontent.com/16742531/39341694-b1bc9a1a-4a17-11e8-9bcb-27b03b5510a8.png)

**Comment by xLastt** [comment]
XD

**Comment by EnIGuess** [comment]
Also true for llamas

**Comment by sp614x** [comment]
Fixed, coming in next preview.
