### ISSUE TITLE
Mining Drill and Revolver from Immersive Engineering have no texture/model

### ISSUE THREAD

**Issue by Tanto17** [sp614x/optifine#1375]
Hello, 
The Mining Drill and Revolver from Immersive Engineering  have no model/ texture with Optifine installed. The essentially disappear.  When I remove optimize they render normally.

MC Version: 1.12.2
Forge Version: 14.23.3.2674
Optifine Version: 1.12.2 HD U D1

Let me know if you need anything else.
Thanks.

**Comment by Tanto17** [comment]
Fixed in newest release. Thank you.

**Comment by sp614x** [comment]
Yay
