### ISSUE TITLE
Spectral Arrows / Glow Effect - Black Screen and Glowing Mob

### ISSUE THREAD

**Issue by mixxit** [sp614x/optifine#1377]
There is a bug with optifine where the screen will go black and the mob will show as a single glowing light

![image](https://user-images.githubusercontent.com/233287/39399083-71cc6e00-4b0f-11e8-9a71-d5014a08a01d.png)

You can mitigate the black screen by turning Fast Render on but you cannot mitigate the mob glowing with this effect

![image](https://user-images.githubusercontent.com/233287/39399087-7fa6aa0e-4b0f-11e8-9fa7-36a64a0c8506.png)

However, closing minecraft and removing the two '*options*' files will allow the glow effect to work perfectly fine with optifine the next time you load minecraft

![image](https://user-images.githubusercontent.com/233287/39399097-bb5f5e42-4b0f-11e8-8385-de8dbfb2112f.png)

However on the next boot, the files seem to change again and break the glowing when you next boot optifine

This issue has been raised on other tickets and closed but i believe there is still an issue here that can be resolved

I have attached the broken files that get generated
[options.txt](https://github.com/sp614x/optifine/files/1957959/options.txt)
[optionsof.txt](https://github.com/sp614x/optifine/files/1957960/optionsof.txt)

**Comment by mixxit** [comment]
Hmm this may be resource pack related, investigating...

**Comment by mixxit** [comment]
Shader issue inside the resource pack, closing thanks

**Comment by sp614x** [comment]
The spectral effect (glowing outline) is not compatible with Fast Render and with shaders. When one of them is active an alternative "ghost" effect is used instead.
