### ISSUE TITLE
Toggle chat background.

### ISSUE THREAD

**Issue by MastaNub** [sp614x/optifine#1379]
Read the title. Thank you very much. Shouldn't be hard to implement.

**Comment by sp614x** [comment]
Like this?

![image](https://user-images.githubusercontent.com/16635441/39405003-565f5f40-4b9d-11e8-859c-c9692a29adea.png)

**Comment by realjackasterisk** [comment]
Out of curiosity, *why* would you want this? I can only imagine this makes the text magnitudes more difficult to read.

**Comment by sp614x** [comment]
The chat lines background has always full width, even when the text is shorter. 

![image](https://user-images.githubusercontent.com/16635441/39407392-b45588ae-4bc5-11e8-81c4-86325c5ece03.png)

Limiting the background width to match the text width could be better.

**Comment by MastaNub** [comment]
% for the capacity, changing chat's background color?

**Comment by Brottweiler** [comment]
I do not like chat background, it obscures too much of the screen even when there's no text. **But** it is hard to read when you open chat, so having a background when chat is open but not when chat is closed would be an option.

The 2nd image where the background of chat only shows behind the characters and not when there's empty space would be a nice option as well.

**Comment by sp614x** [comment]
More things that could be fixed:
- chat background opacity
- chat width above 320px

![image](https://user-images.githubusercontent.com/16635441/48201300-0d0c2500-e362-11e8-825b-fb0fa050d60c.png)

- chat scale to only allow multiple of base font size to avoid skewed font rendering

75% (skewed)
![image](https://user-images.githubusercontent.com/16635441/48201375-3e84f080-e362-11e8-970e-fb732253a613.png)

50% (exact)
![image](https://user-images.githubusercontent.com/16635441/48201395-53fa1a80-e362-11e8-91d4-1dd8f7da1e86.png)

Wider chat combines nicely with background per line:

![image](https://user-images.githubusercontent.com/16635441/48201562-d1be2600-e362-11e8-8473-c73855603b0a.png)

**Comment by sp614x** [comment]
Alternatively the chat width should compensate for a smaller GUI scale so that 320px is always close to full width (on 4:3 screens).

**Comment by Madis0** [comment]
FWIW, I made a separate issue for chat width: #1959

**Comment by sp614x** [comment]
Fixed, coming in next preview.

**Comment by Madis0** [comment]
[19w11a now has options](https://www.minecraft.net/en-us/article/minecraft-snapshot-19w11) for text background opacity and whether it is applied on chat only or more GUI items.
