### ISSUE TITLE
Server error during Cape Change from Double Username

### ISSUE THREAD

**Issue by skinnyplayer** [sp614x/optifine#1382]
Hello sp614x,

I'm here for the problem I've talked in private messaging on Minecraft Forum about the "Server error" I receive when I try to change my cape. 

https://gyazo.com/2055c9e2e091e566caa88af63db8a538 < trying to change to another name
https://gyazo.com/28ce37077c6cd292a138aa11b1e4f89f < server error.

My real account (the account I used to purchase the cape and the one I play on) is this:

8769e02805fe4366a3501e002a936690 - MY ACCOUNT (https://namemc.com/profile/Skinny.7)

The OTHER Skinny account is this one: 8776c26988f74315b5208faaa2458878 https://namemc.com/profile/Skinny.3)

On my Optifine donation email profile, it says that the cape is on "Skinny" even though:

1. I can't change its design (when I log in with my Minecraft account, it shows that the cape "was moved to [Username] in June 2016." even though on my donation email it appears to be on Skinny!)
2. I can't move it to a different player (Server error)
3. It doesn't exist on my account (you can see in NameMC too that I don't have it - I also don't have it in-game).

Thanks for the consideration!

**Comment by skinnyplayer** [comment]
???

**Comment by sp614x** [comment]
Both Mojang accounts have the same name, using different case. The Minecraft player names are not case-sensitive so this is not allowed. A request for "Skinny", "SKINNY" and "skinny" should return the same user profile. 

Currently the official Mojang profile for "skinny" is 8776c26988f74315b5208faaa2458878 (not your profile):
https://api.mojang.com/users/profiles/minecraft/SkInNy

The request uses the official Mojang API which maps usernames to Mojang profiles:
http://wiki.vg/Mojang_API#Username_-.3E_UUID_at_time

This is a problem of the Mojang authentication service and OptiFine can't fix it.
I can move the cape manually, but it can't be moved automatically as there are two Mojang accounts with the same name.

**Comment by sp614x** [comment]
Cape moved to "skinny" 8769e02805fe4366a3501e002a936690.

**Comment by skinnyplayer** [comment]
Thank you so much! Won't trouble you with this problem anymore.

**Comment by yoogus** [comment]
help me I have exactly the same problem what should I do?! 

my account with a cape is IAMNOOBXDDDDDD
I changed my nickname to yoogus_ and when I change my nickname in optifine, Server Error gives me
