### ISSUE TITLE
gbuffers_beaconbeam does not bind textures correctly

### ISSUE THREAD

**Issue by Builderb0y** [sp614x/optifine#1383]
Sampling noisetex will return values from the normal beacon beam texture instead. The same is true for gaux custom textures. Pack for testing: https://www.dropbox.com/s/whfca6w3ornsv3k/beacon%20texture%20test.zip?dl=0

**Comment by sp614x** [comment]
The samplers were not correctly bound:

![image](https://user-images.githubusercontent.com/16635441/39516385-0e5092fc-4dfd-11e8-9adf-b0eb1d213c4a.png)

**Comment by sp614x** [comment]
OptiFine 1.12.2_HD_U_D3
 - fixed sampler binding for programs "gbuffers_beaconbeam", "gbuffers_item" and "gbuffers_armor_glint"
