### ISSUE TITLE
Not able to open chests in 1.12.2 

### ISSUE THREAD

**Issue by aroe11** [sp614x/optifine#1385]
Hi, running minecraft 1.12.2 with forge and optifine.  Not able to open chests, has anyone else had same problem?

**Comment by Builderb0y** [comment]
#1139, #1135, #1122, #1119, #1114, #1101, #1100, #1094, #1079, #1078, #1074, #1071, #1067

**Comment by aroe11** [comment]
Hi Builderb0y thank you.  Looking through its been an issue and was fixed in C8 have I got that right?  We downloaded D1. So you'd think it'd be OK. I'll reinstall latest and go from there.  Many thanks for being so quick

**Comment by realjackasterisk** [comment]
What version of Forge are you using? Optifine D1 is compatible with Forge #2627

**Comment by sp614x** [comment]
This is getting epic.
