### ISSUE TITLE
CTM using the wrong textures?

### ISSUE THREAD

**Issue by Lemente** [sp614x/optifine#1387]
Hello !

Here is my problem:
I made a connected texture, but it seems that some textures are ignored, and wrong textures used instead (especially in corners)

Am I looking at an outdated guide?
![y2uize](https://user-images.githubusercontent.com/27686967/39584542-fa101fa0-4ef2-11e8-80cf-bdad181cd8e0.png)
![840f0c228a9431ecc440e67ad09f0ca3](https://user-images.githubusercontent.com/27686967/39584648-31db5968-4ef3-11e8-9d06-124c02646d2d.png)
![2018-05-03_16 39 36](https://user-images.githubusercontent.com/27686967/39584663-3d049ed0-4ef3-11e8-86bd-077dcb4bb3a0.png)

`method=ctm

tiles=1-48
metadata=0
faces=all
`
[The Elder's Scales Original.zip](https://github.com/sp614x/optifine/files/1971454/The.Elder.s.Scales.Original.zip)

**Comment by sp614x** [comment]
The CTM template: 
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/images/ctm_template.png

Video Settings -> Quality -> Connected Textures -> Fancy ???

**Comment by Lemente** [comment]
I was using fast connected textures, sorry !

I didn't even knew it was a thing ...

Thanks for the template, couldn't find it myself !
