### ISSUE TITLE
Can I mask a part of a tinted glass to block reflection on the frame ?

### ISSUE THREAD

**Issue by Artwind2** [sp614x/optifine#1395]
Hello,
Is there any possibility to make a texture mask or something to create a mask where reflections will not affect certains part of block ?
I tried some specular textures, but unfortunatly it doesn't seem to affect tinted glass. 
![2018-05-06_20 26 21](https://user-images.githubusercontent.com/38019992/39676486-ebb53a1e-516b-11e8-96f4-5a462a383f01.png)

**Comment by sp614x** [comment]
Translucent textures (glass, water) are rendered last and shaders then apply reflections to them.
It is not a possible to render a non-reflective texture (cutout, cutout mipped) after translucent.
