### ISSUE TITLE
Emissive Textures not working properly on Mobs

### ISSUE THREAD

**Issue by DiaTheAngel** [sp614x/optifine#1398]
So basically I tried to put emissive texture for my zombie's eyes. I tried to make the eye have a glow to it (so it'd fade outwards) but it didn't seem to work: it didn't register transparency. So I just deleted that part and just kept the eye itself, no glow

I think noticed that a zombie spawned with some gold armour, with emissive textures not working on it properly either.
Here is a screenshot
![2018-05-09_16 14 41](https://user-images.githubusercontent.com/31866297/39798666-ccfa2112-53a4-11e8-9d52-45665029d194.png)
On the left is the zombie, on the right is me

**Comment by sp614x** [comment]
Emissive textures should work for zombies:

![image](https://user-images.githubusercontent.com/16635441/41666891-def2a83a-74ab-11e8-9907-6ef2808f8193.png)

Mobs are rendered without blending so they can't use semi-transparent (translucent) textures.
