### ISSUE TITLE
Optfine triggers java assertion failure

### ISSUE THREAD

**Issue by Jifl** [sp614x/optifine#1399]
Hi,

I've been using 1.8.9_HD_U_I3 fine, except today all of a sudden starting minecraft, and after the launcher but before the main minecraft screen I get:
[09:29:30] [Client thread/INFO] [Config]: [OptiFine] BetterGrass: Parsing default configuration optifine/bettergrass.properties
[09:29:30] [Client thread/INFO]: Created: 32x32 textures-atlas
[xcb] Unknown request in queue while dequeuing
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
java: xcb_io.c:165: dequeue_pending_request: Assertion `!xcb_xlib_unknown_req_in_deq' failed.

If I remove optifine from my mods, everything's fine. Bear in mind I haven't changed anything with my setup, nor any configuration option, it's just started doing this all on its own.

The really weird thing is that I have an alt account with its own separate .minecraft directory (this is Linux in case it isn't obvious), but with the same version of optifine. That setup still works fine!

I also updated to 1.8.9_HD_U_I7, but it didn't help.

Any ideas?

Jifl

**Comment by Barteks2x** [comment]
AFAIK, this is not optifine, this is the animated forge loading screen. Optifine may just slightly alter some timings and expose an issue in your GPU drivers. Likux GPU drivers generally seem to have issues with any multithreading, even if it's allowed by opengl specification. Just disable the animated loading screen in forge (config/splash.properties). If you are using open source nvidia drivers (nouveau), try proprietary ones if you want.

**Comment by sp614x** [comment]
Disabling the Forge splash screen should fix it.
