### ISSUE TITLE
OptiFine Not Working with Windows 10 

### ISSUE THREAD

**Issue by JFlameStudios07** [sp614x/optifine#1400]
I just updated to Windows 10 and now no Optifine works when I play Minecraft. I really want OptiFine to work but have little knowledge over the topic; I've watched a ton of videos and none have helped me. Can anyone help me with all of this?

**Comment by realjackasterisk** [comment]
Some details would be appreciated.
Version of Minecraft? Version of Optifine? Using Forge? You aren't using the Bedrock edition, right? How did you install Optifine? How did you install Minecraft? etc.

**Comment by sp614x** [comment]
Are you using Minecraft "Windows 10" edition? 
OptiFine only works with the Java edition.

**Comment by JFlameStudios07** [comment]
The version of Minecraft I'm using is 1.8.9 Forge in a folder with mods for Hypixel. It is OptiFine_1.8.9_HD_U_I7 and I'm not sure what the bedrock edition is. I used the normal website where you get Optifine and Minecraft from. Also, I'm pretty sure i've been using the Java  edition.  @realjackasterisk  and @sp614x

**Comment by sp614x** [comment]
How does it not work? Game is not starting or crashing on opening world or crashing when joining server?
Can you post the crash report, error log or game output?
OptiFine should work just fine on Win 10.
A typical problem when updating to Win 10 is that it installs some old graphics drivers instead of the latest vendor drivers.

**Comment by JFlameStudios07** [comment]
It's not crashing or anything like that just . When I enter a server or start playing minecraft with my modded folder with optifine it's laggy zoomed in on my screen and I just can't move or select anything. I have to quit the game. I'll try updating graphics card. 
@sp614x

**Comment by KaiAF** [comment]
Assuming it got resolved after they updated their graphics card, closing
