### ISSUE TITLE
Rendering Problem with transparent layer on block

### ISSUE THREAD

**Issue by SjetCraft** [sp614x/optifine#1401]
Issue was first reported [here](https://github.com/HellFirePvP/AstralSorcery/issues/561).

![2018-05-10_14 57 44](https://user-images.githubusercontent.com/24903975/39888540-1610eb4c-5463-11e8-9764-0cf1af365733.png)

The block uses an overlay png to render the blue aquamarine over the sand block.
The item renders correctly, but the block does not.

Issue is not present when Optifine is not installed.

**Comment by sp614x** [comment]
How is the overlay rendered?
Is the overlay using transparency (translucent)?

**Comment by SjetCraft** [comment]
Yes. The overlay is transparent. 
The transparent part is rendering correctly, but the semitransparent part is rendering as opaque. (T
The item block is being held in the main hand and it is rendering correctly.

**Comment by mxnmnm** [comment]
Can confirm this is an issue...

**Comment by KaiAF** [comment]
Is this still an issue?

**Comment by mxnmnm** [comment]
It is on 1.12 idk about newer versions cuz I haven't used them

**Comment by KaiAF** [comment]
If this is still an issue, create a new bug report
