### ISSUE TITLE
Mipmap level >0 casues lines between blocks

### ISSUE THREAD

**Issue by ProxyPlayerHD** [sp614x/optifine#1404]
![sgcea8x](https://user-images.githubusercontent.com/13576843/39955042-da3b8be6-55c9-11e8-821e-f9cf31243517.gif)

i already updated my GPU Drivers, Optifine and MC version doesn't matter since it is happening with all versions.

what could cause this?

**Comment by realjackasterisk** [comment]
what GPU do you have? what version of optifine and MC?

**Comment by sp614x** [comment]
In the graphics driver control panel set all 3D settings to "Application controlled" or "Default".
Especially Antialiasing or Anisotropic Filtering.

**Comment by ProxyPlayerHD** [comment]
Thanks it works now, i had no idea that setting was even enabled.
