### ISSUE TITLE
CTM overlays above rain? 

### ISSUE THREAD

**Issue by GuardOscar** [sp614x/optifine#1408]
Look at the overlays between different blocks in the rain.

![2018-05-12_19 13 34](https://user-images.githubusercontent.com/29942659/39966850-861818d6-56c3-11e8-96f6-f98b6fc571a3.png)

![2018-05-13_08 44 26](https://user-images.githubusercontent.com/29942659/39966953-fc719baa-56c4-11e8-9b03-2df486e34133.png)

![2018-05-13_10 33 07](https://user-images.githubusercontent.com/29942659/39967847-ea5240be-56d3-11e8-9c15-0d6b8aa8f8a3.png)

I'm using OptiFine 1.12.2 HD U D2.

**Comment by sp614x** [comment]
If the overlays use layer TRANSLUCENT then they may appear behind the rain.

**Comment by GuardOscar** [comment]
I'm trying to change layer type and it works! But results looks not so good: 
before
![2018-05-14_06 51 44](https://user-images.githubusercontent.com/29942659/39990599-00dadec2-577e-11e8-9d67-b3f665339b71.png)
after
![2018-05-14_06 51 25](https://user-images.githubusercontent.com/29942659/39990611-0baf0fa8-577e-11e8-947a-5a91339aedbe.png)

This bug with rain may be a fixed in the next updates?

**Comment by sp614x** [comment]
The overlay looks bad because the texture was designed to be used on the translucent layer and it has semi-transparent pixels. It would look better if the semi-transparent pixels are fixed.
The translucent textures rendering above rain can't be fixed, this is how the Minecraft render engine works.
