### ISSUE TITLE
java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by Alugia7** [sp614x/optifine#1413]
Crash report: https://pastebin.com/GWGSrg0U
Crash tends happen when activating large redstone contraptions involving pistons.

**Comment by sp614x** [comment]
OptiFine 1.12.2_HD_U_E1
 - fixed crash in chunk visibility check (#1413)

**Comment by darthvader45** [comment]
Happens to me when loading new chunks in E3.  Pretty sure no other mods could be interfering, as I'm not using mods that are overly hacky.
