### ISSUE TITLE
OptiFine being rehosted, presumably without permission

### ISSUE THREAD

**Issue by sctjkc01** [sp614x/optifine#1417]
I'm less than certain this is the proper avenue for this, however I feel this might be the best way to get into contact with the OptiFine team for this urgent issue.

As was noted on [this Reddit post](http://www.reddit.com/r/feedthebeast/comments/8klvw6/what_is_this_knockoff_optifine_site_that_suddenly/), it appears that OptiFine was taken up by mod re-hosting site topminecraftmods.  Due to the paid promotion with Google, it now appears above the legitimate source in Google Search, such as [when searching for "optifine"](https://www.google.com/search?q=optifine).

From what I can tell, they've set up a mirror site that looks markedly similar to the legit source, the primary differences being the lack of adfly links, downloading of EXEs as opposed to JARs, and only offering one JAR for each Minecraft version.  I highly suggest the most legal-minded get in contact with Google to strike the advertising campaign.

**Comment by PulzHF** [comment]
You should install a browser add-on for [StopModReposts](http://stopmodreposts.org)

As that site is listed as a malicious reposting site.
![](https://i.imgur.com/UYGNF7X.png)
![](https://i.imgur.com/or72MVW.png)

I've already reported them to [http://www.launchpad.com](http://www.launchpad.com), their Registrar.
