### ISSUE TITLE
entity model by name tag?

### ISSUE THREAD

**Issue by perengano99** [sp614x/optifine#1423]
Is there a way to create an entity model and that it only applies to a certain mob with a custom name??

**Comment by MastaNub** [comment]
https://youtu.be/2wdEPjmxQEY?t=3m35s
this?

**Comment by sixfootblue** [comment]
You can't swap out entire models yet. The mobs in that video have extra geometry with an invisible texture, which are then given a visible texture when the proper nametag is used.

**Comment by sp614x** [comment]
The CEM model has extra geometry with unvisible texture.
With RandomEntities you can assign a visible texture to the extra model parts.
