### ISSUE TITLE
No Random Mobs Support for Item Frames?

### ISSUE THREAD

**Issue by Oscilite** [sp614x/optifine#1424]
As far as I can tell there is no random mobs support for item frames, but it would be very useful for decorating if you could conditionally change the texture (change the wood type by biome for example) and there is already support for paintings.
I know item frames are handled differently than other models but this would be greatly appreciated (or a quick explanation on how to do it if it is already a feature)

**Comment by sp614x** [comment]
Item frames are using block models with texture atlas sprites. 
These are not separate textures and they can't be configured with Random Entities.
CTM could be used (it works with sprites), but item frames are entities, they don't have blockstate and can't be targeted in CTM by blockID or metadata.

**Comment by sp614x** [comment]
Other entities which have the same problem are:
- primed TNT
- enderman held blocks
- iron golem held blocks (flower)
- mooshroom mushrooms (on the back)
- minecart contents (tnt, furnace, etc.)
