### ISSUE TITLE
Glowing

### ISSUE THREAD

**Issue by snoggie1487** [sp614x/optifine#1427]
If something has the glowing effect, all of it will be white, not just the outline.

**Comment by Strum355** [comment]
Can you provide some info, like: mods, system specs, provide a screenshot

**Comment by MastaNub** [comment]
https://imgur.com/a/1LG1a1K
This is a known issue. It only happens when you have Fast Render/Shaders turned on.

**Comment by sp614x** [comment]
Duplicate of #1377, #1174, #189, #1432.

The spectral effect (glowing outline) is not compatible with Fast Render and with shaders. When one of them is active an alternative "ghost" effect is used instead.
