### ISSUE TITLE
Model Overrides doesn't work correctly

### ISSUE THREAD

**Issue by fluid-uu-matter** [sp614x/optifine#1429]
When I made a resource pack with 3D bow model and I test it in a MC installed optifine, the pulling animation doesn't work correctly. It works when using MC without optifine. Maybe optifine has bugs on reading model overrides. Please fix this.

**Comment by sp614x** [comment]
OptiFine doesn't change the vanilla model loading.
If you configure custom bow models with CIT, then the pulling animations have to be configured as specified in the documentation: 
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/cit_single.properties#L279
