### ISSUE TITLE
[1.7.10]Is there any possibility to add triple buffering in Optifine?

### ISSUE THREAD

**Issue by TataTawa** [sp614x/optifine#1435]
Is there any possibility to add triple buffering in Optifine? Although the multithread world loading is open, in large modpacks the frame time is not stable, some frame take 100ms and some frame take 10ms, and this makes gamer 3D glazing(although the fps is 60 or above).

I use Optifine HD U E7 (1.7.10)

**Comment by sp614x** [comment]
The unstable framerate in larger modpacks is mostly due to tick time.
Triple buffering can't be enabled from opengl/lwjgl: https://www.khronos.org/opengl/wiki/Common_Mistakes#Triple_Buffering
It can only be enabled via the graphics driver control panel.
