### ISSUE TITLE
[Suggestion] Is there a way to remove the shadow/black circle under a certain entity?

### ISSUE THREAD

**Issue by Xanaduude** [sp614x/optifine#1442]
I'm trying to remove the circular shadow under the XP orbs and can't figure out how.. if it's even possible.
I'm essentially trying to make the XP orbs invisible but still part of the game if that makes any sense? So far i've gotten the orbs themselves invisible but the shadow under them still remains. The only way I was able to get rid of it was by turning off Entity Shadows altogether.. which isn't what I wanted. Any help would be greatly appreciated, if it's not possible no worries.

**Comment by realjackasterisk** [comment]
I don't think this is currently possible. Interesting idea, though. Maybe you could re-label this as a suggestion?

**Comment by sp614x** [comment]
Currently it is not possible to configure the shadow per entity.
