### ISSUE TITLE
OptiFine Donation / Paymentwall Problem

### ISSUE THREAD

**Issue by eggnog1219** [sp614x/optifine#1444]
Last month I wanted to donate to OptiFine because I wanted the cape. I used my dad's credit card. I chose Paymentwall because for payment because that was the only option. I filled up all the things until I made it to the payment loading section. (I posted the photos via Gmail last month.) It got stuck there for a min so I said to myself maybe I should just wait... About 8 hours later, I just turned off my computer and try to resolve the problem. When I went back to the OptiFine then filled the payment up, I was greeted with a message saying that I was refunded! It says to complete this payment I have to send a photo of the receipt and drivers license, passport or anything that shows the identity of the cardholder. At this time, my dad was very busy so I had to solve this problem at a later time. About 5 days later, I went back to OptiFine and tried to donate. I once again filled up the information then I was greeted with the refunded message again. Then I pressed the button ("Start an Inquiry") to try to send some photos of my dads drivers license. I clicked it then nothing loaded up... Thrn I refreshed and nothing happened... I think I got my account locked. :( I can't choose the Visa option anymore because it just keeps showing the message. I don't even know if I got refunded because every time I make a purchase, a message pops up on my dad's phone that money was taken. Please help me solve this problem. I just want a cape. :( Thanks for Reading!!

                                       -eggnog1219

**Comment by sp614x** [comment]
Only Paymentwall can solve this problem.
