### ISSUE TITLE
Custom GUI with symbol/unicode

### ISSUE THREAD

**Issue by ULSTICK** [sp614x/optifine#1446]
so i want to make a custom gui with my warp gui, it has these "「」" symbols on the name of the gui
the name was "§f§m--------§7「§bWarp List§7」§f§m--------"

so i did all the unicode things. but it didn't show up
_**container=chest
texture.container/generic_54=warp
name=iregex:\u00a7f\u00a7m--------\u00a77\u300C\u00a7bWarp List\u00a77\u300D\u00a7f\u00a7m--------**_
and it once work when i use *
`name=iregex:\u00a7f\u00a7m--------\u00a77.*\u00a7bWarp `List\u00a77.*\u00a7f\u00a7m--------`
but then it does not work after i reload the resource pack. its so unstable

am i doing anythig wrong? if not can you fix this!!
(sorry for my bad english)

**Comment by ULSTICK** [comment]
so i give it to my friend to test it out, so they say they can see the custom GUI.. its just me for some reason i already checked every settings and it didn't show up

how do i fix this

**Comment by ULSTICK** [comment]
It appears that if I open a GUI from another plugin directly after opening a chest, the texture appears

**Comment by sp614x** [comment]
The custom guis only work for chests and vanilla containers.
The problem is that the server doesn't send why the GUI is opening. 
To fix this the client has to keep track which objects the player has clicked last.
