### ISSUE TITLE
Custom entities model is buggy (often)

### ISSUE THREAD

**Issue by Soolz** [sp614x/optifine#1448]
Hello, 
I'm using the custom entity model by nametag, but often, it's buggy, (pink and black texture, I will send an image. And I'm not the only one with this problem.

Thank you in advance!

**Comment by eot13** [comment]
No, in fact, the model works well, but at times if I die for example. If a pig with the name "test" has a hat, then all the other pigs will have one, but with the purple and black texture.

**Comment by sp614x** [comment]
When exactly it doesn't work?
Steps to reproduce it and screenshot would be nice.

**Comment by eot13** [comment]
It's random, after leaving a world, being dead, leaving a server, etc.

[https://imgur.com/6HX78zl](url)

**Comment by ewanhowell5195** [comment]
If you are experiencing pink and black (missing textures) on entities, it is because you have a texture referenced in the JEM model file that cannot be found in the CEM folder
