### ISSUE TITLE
Glass block render

### ISSUE THREAD

**Issue by Homosanians** [sp614x/optifine#1449]
I've noticed that glass block (item) is invisible when I use Faithfulx32 texture pack.
I tried decreasing mipmap to 0, that helped a bit, but the game looks sharper and I turned this back.
Also, glass block (exactly block) can also be invisible if you're not too close with that but borders are visible however.

Well, Is it possible to fix this without changing texturepack, deleting sys32, etc?

Here are some screenshots:
![image](https://user-images.githubusercontent.com/35880220/41205340-47a1b664-6cfa-11e8-8c31-9bbc431f25d8.png)
![image](https://user-images.githubusercontent.com/35880220/41205343-537af572-6cfa-11e8-8dc9-3ce5884998e7.png)

Optifine: HD_U_E7 for 1.7.10

**Comment by sp614x** [comment]
This is a general problem with mipmaps. When viewed sideways the glass lines become too thin and disappear. Possible solutions:
- disable mipmaps or reduce mipmap level
- change resource pack
- enable anisotropic filtering or antialiasing
- increasing the GUI size may help to fix the items in the hotbar (Video Settings -> GUI Size)
