### ISSUE TITLE
Will 1.13 optifine use modlaucher as a patching framework?

### ISSUE THREAD

**Issue by DerpyNerd** [sp614x/optifine#1450]
Hi,
cpw and others are working on a new patching system for 1.13+ that is intended to replace launchwrapper to support J9+ and make transformers cleaner. Are you aware of that and are willing to move to it to preserve compat with forge and other core tweakers? Here's a link: https://github.com/cpw/modlauncher

**Comment by sp614x** [comment]
This concerns Java 9 and is still in progress.
OptiFine will switch to it when it is ready and becomes usable.
