### ISSUE TITLE
How to stop Sign Text from disapearing

### ISSUE THREAD

**Issue by DiggerZC** [sp614x/optifine#1452]
Hi there, I like optifine but I do not like how sign text disapears after getting about 16 blocks away from the sign. Is their any way to disable this? Thanks!

**Comment by realjackasterisk** [comment]
But why? You can't even read text from that distance, unless you have a crazy high-resolution monitor.

**Comment by DiggerZC** [comment]
It’s just I don’t like how it just disappears. It’s not about (for me at least) being able to see what it says at a distance, it just is not visually pleasing. Is their any way to do it?

________________________________

**Comment by Miclebrick** [comment]
16 blocks isn't actually that far.... I can read past that range

**Comment by sp614x** [comment]
Currently the text disappears when it becomes too small to be readable.

For example, sign near:

![image](https://user-images.githubusercontent.com/16635441/41487982-1214c3b6-70eb-11e8-84cb-e8c119c01c3c.png)

Sign before the text disappears:

![image](https://user-images.githubusercontent.com/16635441/41488013-2f1921fa-70eb-11e8-8bc4-99139491c197.png)

At this point the text is not readable anymore.

This is for a standard 100 ppi monitor. On a 4k monitor (200 ppi) the text may still be readable at this distance.

**Comment by DiggerZC** [comment]
I have a 4k monitor. Could their be a feature to disable the sign text from disapearing?

**Comment by sp614x** [comment]
The distance calculation can be changed to account for the FOV and display size.
Then for a 4k monitor the sign text would be visible to 32m.

**Comment by sp614x** [comment]
OptiFine 1.12.2_HD_U_E1
 - fixed sign text render distance to depend on screen resolution and FOV

**Comment by MauveCloud** [comment]
It's better with the E1 preview, but still a little bit of a problem.  Perhaps I can clarify what DiggerZC probably meant.  I have a 2560x1440 monitor, and when approaching signs, they go from looking like blank signs to suddenly having text on them.  Even if the text itself is illegible, it would still be distinct from a completely blank sign from further away than the current calculations.

**Comment by Miclebrick** [comment]
It often confuses me, making me think it's an empty sign so I have go over and fix it...

**Comment by Regnander** [comment]
Using the zoom, the text is still visible at "unreadable" distances. Is this intentional?
(I'm using a resource pack to make it easier to see the sign text.)

This is when I'm looking at a sign from the farthest distance that a sign can be seen before it disappears:
![2018-06-24_18 24 46](https://user-images.githubusercontent.com/17113053/41821145-9c120ec8-77dc-11e8-8d41-f23496377287.png)
And now I've back up a few millimeters:
![2018-06-24_18 24 56](https://user-images.githubusercontent.com/17113053/41821146-9c2fb8a6-77dc-11e8-9684-56f4c1bb4f2a.png)

**Comment by DiggerZC** [comment]
It disappears because of Minecraft. But I think the zoom thing is intentional, but I don’t think I should have to zoom to at least see text on a sign from that distance. Even though I cannot read it, it just looks nice if you see some black pixels on the sign, showing that the sign says something.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by sp614x** [comment]
The sign text optimization is disabled when the zoom is active, this is intentional.
The signs themselves disappear after certain distance, this is the vanilla functionality.
Now on HD screens the text should be visible almost to the max. sign visibility distance.

**Comment by DiggerZC** [comment]
Ok… I just don’t get why their cannot be an option implemented into video settings to disable it if we want to


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by sp614x** [comment]
This is a very small optimization that is not making problems for anyone in the last 4 years.
If each small optimization gets an option in video settings I would have to add at least 4 additional screens with options.
