### ISSUE TITLE
[Suggestion] Configurable option to silence Stitching verbose

### ISSUE THREAD

**Issue by Dockter** [sp614x/optifine#1454]
Is it possible to silence the Custom loader: / Sprite Dependency: verbose of OF during the texture stitch phase?

sp614x - Today at 8:15 AM
@Dockter quite possible
please make an issue on the tracker so I can fix it later

**Comment by sp614x** [comment]
OptiFine 1.12.2_HD_U_E1
 - added system property "log.detail=<true|false>" for extended logging
 - reduced logging when loading sprites (custom loader, sprite dependency) 

https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/system_properties.txt#L8
