### ISSUE TITLE
Items rendered using TEISR are invisible with optifine.

### ISSUE THREAD

**Issue by Alex-the-666** [sp614x/optifine#1457]
Items rendered using a custom TEISR become invisible with optifine. Registered like:
https://github.com/Alex-the-666/Ice_and_Fire/blob/1.12.2/src/main/java/com/github/alexthe666/iceandfire/ClientProxy.java#L275

Appears fine in vanilla inventory, but rendered with optifine in game becomes like this:
https://user-images.githubusercontent.com/23727270/41319136-d20c4eb2-6e68-11e8-90d8-ecbc298e3373.png

**Comment by sp614x** [comment]
Looks like a reference to this: https://mcforge.readthedocs.io/en/latest/rendering/teisr/
Does it work with latest preview E1 for 1.12.2?

**Comment by sp614x** [comment]
Where can I get the Ice and Fire 1.5.0 alpha?

**Comment by sp614x** [comment]
Testing latest OptiFine preview E1 + IceAndFire_1.5.0_Alpha4 + Library-1.7.13-1.12.2, the troll weapons are rendered correctly:

![image](https://user-images.githubusercontent.com/16635441/41474516-76df9b56-70bc-11e8-9c27-7496cb5d7ace.png)

**Comment by sp614x** [comment]
OptiFine D3 also seems to work correctly.
