### ISSUE TITLE
CIT on item models

### ISSUE THREAD

**Issue by EskiMojo14** [sp614x/optifine#146]
Is it possible to use CIT for items that use models? For example, if I had a model for the elytra, that matched the entity, and I used CIT to make an alternate colour scheme for the elytra entity when named "Dark Elytra", would it be possible to use CIT to make the model's texture change to match? 
(to clarify, I do not intend to change the model's elements, only the texture)
Also, is it possible to reference textures from assets/minecraft/textures/items or /items_alt1?

**Comment by EskiMojo14** [comment]
Although, if it were possible to change models using CIT, that would be great.

**Comment by TheHADILP** [comment]
Yeah changing the elytra texture is possible.
https://github.com/sp614x/optifine/commit/a16859b441d1264593a974227e1365e5d8705798
And for the named items you could define
nbt.display.Name=Dark Elytra
in the porperties file.

**Comment by TheHADILP** [comment]
And yeah referencing textures from these paths is possible you just have to define them in your properties file.
Useful resource:
https://bitbucket.org/prupe/mcpatcher/wiki/About_Properties_Files

**Comment by EskiMojo14** [comment]
I'm aware that you can change the elytra texture. I have that working. What I don't have working is the elytra *item*, because it uses a simple model. CIT doesn't seem to be able to replace the texture used in that model. That's what I'm asking about.

**Comment by sp614x** [comment]
This works for me http://i.imgur.com/3UJ4uYn.png

  type=item
  items=elytra
  nbt.display.Name=Dark Elytra

**Comment by EskiMojo14** [comment]
That works for items that parent "item/generated", but for items that actually use a custom model, like PureBDcraft's elytra (http://i.imgur.com/bjrQnEG.png), there seems to be no way of redefining the texture that the model uses.

**Comment by EskiMojo14** [comment]
If there were some way of replacing the defined textures, that would be much more useful. If it were possible to replace the entire model itself, that would be even better.

**Comment by EskiMojo14** [comment]
Also, referring to textures in textures/items may work, but referring to textures in textures/items_alt1 throws a NullPointerException, and unloads all of the packs.

**Comment by EskiMojo14** [comment]
Would it be possible to add a new type, like type=model? Then, you could refer to a .json within the (assets/minecraft/models/)item folder, possibly in items/cit? That would save defining a texture, and would be incredibly useful.

**Comment by reinder-s** [comment]
soooo?
is this going to be a thing. because i actually need to be able to use json files for textures

**Comment by sp614x** [comment]
Eventually, however it is quite complex.

**Comment by EskiMojo14** [comment]
Added in OptiFine 1.11.2 version C2. 
https://github.com/sp614x/optifine/commit/a7643576ad13cbf958ef70d5ea6f86aad6363585
