### ISSUE TITLE
un able to install 

### ISSUE THREAD

**Issue by s4sutler100** [sp614x/optifine#1461]
Optifine will not install, double clicking does not activate install. also  I dont see why Optifine can not play nice with forge loader.

**Comment by sp614x** [comment]
OptiFine needs Java to be installed on the computer.
If double-click on the "OptiFine_1.12.2_HD_U_D3.jar" doesn't work, you can try with right click and select "Open with... -> Java".
You can also place the OptiFine JAR file in the Forge mod folder and would be automatically loaded.
