### ISSUE TITLE
Permission and Clarification

### ISSUE THREAD

**Issue by PulzHF** [sp614x/optifine#1463]
I'd like to start off by referencing my first request #1188 in which we highlighted issues with the current modpack policy. I'd also like to reference #1216 which has still received no further response.

I originally requested permission for my pack "The New Tekkit Classic", which is a front page popular modpack- which is actually ranked 16th most popular currently, 12th if you remove the four new packs that broke the popularity formula and 4th most popular non-pixelmon modpack on the platform.

I originally had the mod in my modpack, until I user pointed me all the way back to a forum post written in 2011 and copywritten in 2013- in which it was only stated _there_ that written permission is required. I quickly pushed an update, replacing it with FastCraft.
There is no mention on your site FAQ, which misleads a lot of people- including myself, initially- who have posted on GitHub before.

Can we get an official statement regarding modpack usages, why permission even needs to be given (is it not the purpose of creating a mod for the community, so that the community can use it?) and amendments to the site- even if just the FAQ, regarding redistribution via modpacks?

**Comment by sp614x** [comment]
The official statement is: OptiFine can't be added to a modpack without a permission.
Currently there are no modpacks that have a permission. That may change in the future.

**Comment by sp614x** [comment]
Updated FAQ.

**Comment by FireController1847** [comment]
@sp614x So how do we get said explicit permission?

I have a modpack called Yogbox 2.0, which of course is a remake of the original Yogbox which includes OptiFine. I need to know if I'm allowed to have it in or not, as it completely changes the experience.

I've tried to contact you via Email (and my previous issue on this). I have yet to get a true response other than "Can't be added without permission." Well, how do we _get_ permission.
