### ISSUE TITLE
POM for emissive textures

### ISSUE THREAD

**Issue by Blockstate** [sp614x/optifine#1467]
The emissive textures should be affected by the normal map provided like the specular texture is so when using pom you don't have a floating overlay as seen in the attached image.

EDIT: Also, after more testing, it is not being affected by specular textures either which it should.
![2018-06-20_16 10 25](https://user-images.githubusercontent.com/11284043/41689215-7a407090-74a4-11e8-86cb-bb52a23b7b35.png)

**Comment by sp614x** [comment]
The emissive textures can have their own normal/specular textures.
Base texture: block.png
Normal/specular: block_n.png, block_s.png
Emissive: block_e.png
Emissive normal/specular: block_e_n.png, block_e_s.png
