### ISSUE TITLE
some block craftery blocks dont render and everything turns black in the betweenlannds when fast render is on

### ISSUE THREAD

**Issue by kuroyure** [sp614x/optifine#1469]
![2018-06-21_17 16 31](https://user-images.githubusercontent.com/34189248/41778375-f8fbc73e-7604-11e8-84b1-cbbfbaf6104b.png)
i got this problem with render in blockcraftery , and also when fast render is enabled in the betweenlands everything turns black

**Comment by sp614x** [comment]
Betweenlands probably uses custom shaders which are not compatible with FastRender.
The Blockcraftery blocks probably have wrong shading because OptiFine disables the Forge lighting pipeline https://github.com/sp614x/optifine/issues/298.
