### ISSUE TITLE
Visual glitches using Antialiasing at max

### ISSUE THREAD

**Issue by hhiru** [sp614x/optifine#147]
I noticed visual glitches in GUI using Antialiasing at max: http://imgur.com/a/ivILz
I'll attach my options.txt and optionsof.txt files too..! Using OptiFine HD B5 (1.9.4)

[options.txt](https://github.com/sp614x/optifine/files/296512/options.txt)
[optionsof.txt](https://github.com/sp614x/optifine/files/296513/optionsof.txt)

**Comment by sp614x** [comment]
The artifacts are a side effect of AA and can not be fixed easily.
