### ISSUE TITLE
Transparency in animated XP bar sometimes becomes white.

### ISSUE THREAD

**Issue by MastaNub** [sp614x/optifine#1471]
Transparency becomes white when:
•Going into 3rd person view.
•Opening up F3.
https://imgur.com/a/ZyxtLKI

**Comment by realjackasterisk** [comment]
are you sure there aren't any semi-transparent pixels in the texture?

**Comment by MastaNub** [comment]
![image](https://user-images.githubusercontent.com/35407179/41799419-6af185c2-7669-11e8-8e56-c858dcea809a.png)
It's completely transparent. That bug only occurs in 3rd person mode or when having F3 open.

**Comment by sp614x** [comment]
This is a known vanilla bug: https://bugs.mojang.com/browse/MC-58614?attachmentViewMode=list

**Comment by sp614x** [comment]
OptiFine 1.12.2_HD_U_E1
 - fixed experience bar transparency (#1471)
