### ISSUE TITLE
Optifine is not secure

### ISSUE THREAD

**Issue by Villqin** [sp614x/optifine#1474]
When I go to optifine.net it says that it is not secure and the error message is 'ERR_CERT_DATE_INVALID' I searched up what that means and it says that it means that my computer is not up to date. But it is up to date! I clicked continue to site and it says 'Not Secure' and the https in optifine.net is crossed out. I want to get a cape but I am scared that my money might get stolen from hackers! Please respond to this quickly!

**Comment by realjackasterisk** [comment]
I'd like to know which website you got that explanation from, because that doesn't sound correct at all.

The SSL certificate simply expired today. Wait until @sp614x gets it renewed.
![image](https://user-images.githubusercontent.com/31686191/41815779-8176406a-7729-11e8-9028-e2e758572cc7.png)

**Comment by danilogico** [comment]
Got it! It happened to me too.

**Comment by sp614x** [comment]
The SSL certificate has been updated.
