### ISSUE TITLE
OpenGL error: 1281 (Invalid value), program: shadow, at: shadow terrain cutout

### ISSUE THREAD

**Issue by Seth0067** [sp614x/optifine#1475]
Receiving this error spammed to console with Sevtech Ages.  Possibly a mod incompatibility?  Would be nice to know which one perhaps.

_**[main/ERROR] [shadersmod.common.SMCLog]: [Shaders] OpenGL error: 1281 (Invalid value), program: shadow, at: shadow terrain cutout**_

I'm using latest Optifine (not preview),  and Sevtech Ages modpack.

[Here's](https://www.dropbox.com/sh/l5nqugjf8a865ik/AAA3bo263shjzWxgGL6fCIB2a?dl=0) some logs, in case it helps

**Comment by sp614x** [comment]
To find the problematic mod:
1. Remove half of the mods (without OptiFine), test
2. If the problem still appears continue with 1.
3. If the problem doesn't appear, restore the removed mods and remove the other half of the mods
4. Repeat until only 1 or 2 mods are left

**Comment by Seth0067** [comment]
- This does not occur when shaders are unloaded
- This happens using different shader pack: seus renewed, sildur's 1.17 w/volumetric, BSL 7, etc.

Not sure if I will have time to do ye old 50/50 elimination game, but was hoping that maybe someone in the community (or on your team) might have seen this since sevtech is a popular pack.

**Comment by Seth0067** [comment]
Nevermind - I guess when I saw the previous BDcraft / 1281 bug i did not see the "disable rendering regions" solution (maybe i looked at it before the solution posted, dunno).  Disable render regions does seem to eliminate this problem.
