### ISSUE TITLE
Mod Particle Error, OptiFine 1.12.2 HD U C9 Above

### ISSUE THREAD

**Issue by danilogico** [sp614x/optifine#1476]
The mod Dynamic Surroundings and the mod Better foliage have, respectively, a particle that stays on the ground while walking (footprints) that has a certain transparency and the other has a particle that falls from the trees (leaves) that begins opaque and ends disappearing transparently.
From version 1.12.2 HD U C9 Above, there is an error that causes the texture of these particles to blink in colors such as light green and brown (without showing the correct transparency). This is with version 1.17 of Sildurs Shaders and with forge1.12.2-14.23.4.2710, in minecraft 1.12.2. Maybe the problem is in the forge, but testing in this version and in the last 10 the result is the same. In addition to the other mods use the latest forge.

This only happens during the day. At night neither shows the transparency nor blinks (turns black).
This is preventing me from using the latest versions of optifine.
Anything else is just asking.

**Comment by sp614x** [comment]
Is this only with Forge and Shaders active?
Does it happen with another shader pack?

**Comment by danilogico** [comment]
"Is this only with Forge and Shaders active?" - Yes

"Does it happen with another shader pack?" - I'm not sure if there is another shader with this problem, when I test this, I update this comment (but only this shader is good, so can not change). If it is a thing too random to solve I understand ...

**Comment by sp614x** [comment]
The shader packs have a full control over the rendering. They are usually made to work with vanilla. Depending on how and when the modded particles are being rendered it may happen that they can work with one shader pack and not work with another one.

**Comment by sp614x** [comment]
The Dynamic Surroundings footsteps also flicker with OptiFine C8 and Sildurs Shaders 1.17. Older OptiFine versions are probably behaving the same. 
With Sildurs Enhanced Default 1.3 shaders the footsteps are rendered correctly.
With Chocapic13 v7 Low shaders the footsteps are rendered without transparency (solid), but don't flicker.
Looks like the modded particle rendering depends on the shader pack and not on OptiFine.

**Comment by danilogico** [comment]
I understand...
It is the shader that fits optifine, not the opposite.
However, using the OptiFine C8 the texture blinks less, almost nothing.
You can leave it like this, I'll talk to the owner of Shader.
Thank you so much! For understanding and responding fast.
