### ISSUE TITLE
Website Error - Unable to connect

### ISSUE THREAD

**Issue by Azounstone** [sp614x/optifine#1478]
When trying to connect to your website I get this error:

Secure Connection Failed

An error occurred during a connection to optifine.net. Cannot communicate securely with peer: no common encryption algorithm(s). Error code: SSL_ERROR_NO_CYPHER_OVERLAP

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the web site owners to inform them of this problem.

**Comment by mindforger** [comment]
Your browser and the website can't find an methode to handle out the SSL connection you may have very strict SSL settings or maybe a strong hardware firewall between you and the internet with SSL inspection, you may also have an Antivirus suit running that does SSL inspection, try turning it off

**Comment by Regnander** [comment]
This may be related to #1474

**Comment by Azounstone** [comment]
It does this in all browsers:

Firefox
Edge
IE

**Comment by sp614x** [comment]
The DDOS protection from Cloudflare has a problem and it may take a while until the SSL certificate is update.

**Comment by sp614x** [comment]
The SSL certificate has been updated.
