### ISSUE TITLE
Default option of Translucent Blocks is lacking context

### ISSUE THREAD

**Issue by Regnander** [sp614x/optifine#1479]
Translucent Blocks can be set to three values (Default, Fancy and Fast), but the tooltip only describes the two latter:
>`Fancy - correct color blending (default)`
`Fast - fast color blending (faster)`

Since the description for Fancy reads `(default)`, it makes me wonder if Default and Fancy are the same or if Default is "as set by setting Graphics". Which is it?

**Comment by sp614x** [comment]
The default setting is controlled by the option Graphics.

**Comment by sp614x** [comment]
Fixed.
