### ISSUE TITLE
Emissive Textures Not Working With CIT

### ISSUE THREAD

**Issue by HunterBlackbrick** [sp614x/optifine#1481]
When trying to implement ET for alternate CIT textures, for example a different sword changed via NBT Display Name, ET does not show in-game for said CIT items/armors.

**Comment by sixfootblue** [comment]
They're working for me. How are you setting up your emissive textures?

**Comment by HunterBlackbrick** [comment]
Well, all of my CIT are in the mcpatcher folder, and I was under the impression that I'm supposed to put the emissive texture in the same folder as the texture I want to add on to. For example I have a sword texture in mcpatcher/cit/items/weapons/sword.png, and I made and ET in the same location called sword_e.png. This has not worked, but ET for anything in the normal vanilla folders will work. I've been out of the texturing game for a bit so I'm getting back into it, so if it's blatantly obviously wrong it's not my fault I'm trying to catch up 😂

**Comment by sixfootblue** [comment]
That's odd then. That looks like the correct format. Not sure what the problem could be. Are you on the most recent version of Optifine?

**Comment by HunterBlackbrick** [comment]
I am, yeah. I'm really not sure what's causing it to not work. It might be that I was working on bringing my pack to 1.13, so the version number in the pack json file is 4 rather than 3 for 1.12.2. I might try tomorrow to see if I can get it working in a new test pack for the right version and see if that changes anything.

**Comment by HunterBlackbrick** [comment]
Issue resolved in OptiFine_1.12.2_HD_U_E1
