### ISSUE TITLE
Option to make long name or lore texts wrap if they go offscreen

### ISSUE THREAD

**Issue by DataCrusade** [sp614x/optifine#1482]
Because you cant stop people from making long names/lore text (see: Wynncraft) + this just should be an optifine feature (because I don't want to have to use forge and a whole separate mod that does this + stuff I dont want it to do just to have text wrapping).

**Comment by Regnander** [comment]
Just for the sake of illustrating this issue to those to don't play Wynncraft, this is the normal screen size:
![2018-06-25_15 31 58](https://user-images.githubusercontent.com/17113053/41853046-1a28d4e4-788d-11e8-8a56-35cac6a08471.png)
And this is fullscreen:
![2018-06-25_15 32 08](https://user-images.githubusercontent.com/17113053/41853094-39093214-788d-11e8-8368-c2a1a5e67c10.png)

**Comment by sp614x** [comment]
Curently OptiFine can't change the tooltip before or while it is being rendered.
This would need significant changes that would affect the Forge compatibility.
