### ISSUE TITLE
Optifine HD U E1 - World Ticking Crash

### ISSUE THREAD

**Issue by MokahTGS** [sp614x/optifine#1488]
I'm getting a crash while exploring the world and the game tries to render some entity:

https://paste.dimdev.org/isuyovobuk.mccrash

Mod List: https://paste.dimdev.org/beqokibigi.md

**Comment by KaiAF** [comment]
Neither of those paste is valid. If you are still having this issue, please create a new ticket.

**Comment by MokahTGS** [comment]
Yes, because this was reported in 2018.
