### ISSUE TITLE
Flickering orange texture in armor slots while on fire and AA/AF enabled

### ISSUE THREAD

**Issue by Mangabum** [sp614x/optifine#1495]
I found this while in a creative world. Setting yourself on fire makes all the armor slots flicker orange. Haven;t been able to reproduce this in vanilla Minecraft or even a Survival Optifine world, so it seems to me like it only happens in Creative. Found in Optifine 1.12.2 HD U E1

![ezgif-4-712f078b7b](https://user-images.githubusercontent.com/36723699/41951903-d97ebd22-79ff-11e8-8003-f9b631430a38.gif)

**Comment by sp614x** [comment]
Cool!

**Comment by sp614x** [comment]
Works for me:

![image](https://user-images.githubusercontent.com/16635441/41968037-881acfbc-7a03-11e8-9058-14f2fd7a5de9.png)

**Comment by sp614x** [comment]
Also works with Forge:

![image](https://user-images.githubusercontent.com/16635441/41969427-af46595e-7a07-11e8-90d6-6514bd24f4ca.png)

**Comment by sp614x** [comment]
F3 screenshot, error log (game output), shaders/AA/AF, etc?

**Comment by Mangabum** [comment]
[latest.log](https://github.com/sp614x/optifine/files/2143439/latest.log)

[options.txt](https://github.com/sp614x/optifine/files/2143445/options.txt)

[optionsof.txt](https://github.com/sp614x/optifine/files/2143446/optionsof.txt)

![2018-06-28_09 52 17](https://user-images.githubusercontent.com/36723699/42008650-4962c08e-7ab9-11e8-80c3-585d18591b49.png)

No shaders used

**Comment by sp614x** [comment]
I can reproduce it when Antialiasing or Anisotropic Filtering is enabled.

**Comment by sp614x** [comment]
Ninja updated E1 for 1.12.2 with a bugfix, please redownload it.

OptiFine 1.12.2_HD_U_E1
 - fixed armor slots with player on fire and AA/AF enabled (#1495)
