### ISSUE TITLE
Predicates Lag Issue

### ISSUE THREAD

**Issue by RubbaBoy** [sp614x/optifine#1500]
There has been a bug/issue in the game for nearly two years now, in which Mojang has refused to fix ever since it was reported [here](https://bugs.mojang.com/browse/MC-101792). It had to do with many predicates heavily lagging the game (By several hundred FPS for many users), as a certain part of a class mentioned in the comments looped through each predicate per item per tick. This is demonstrated in [this video](https://www.youtube.com/watch?v=uRfGOef_aJM), showing the substantial difference this bug makes. I believe these repeated iterations could be cached, to reduce the amount of looping that had to be done.

Mojang has only marked this as "Works As Intended", and the reason is thought to have been because with taking such a feature to its limits and so far away from the actual game like this, it comes with a price, and Mojang doesn't want to invest time into fixing it for this reason. If they have an official statement on this issue I missed, I would love to see it, these words did not come from them, I don't want anything thinking they said this (Other than marking the bug as "Works As Intended").

I've talked to several map makers and resourcepack creators, and several of them have had to drop models because of the amount of lag it created, and the sheer amount of models and textures they had.

**Comment by Miclebrick** [comment]
+1 I know of many servers/plugins/maps that take advantage of this feature which would benefit from having this fix implemented into Optifine even if Mojang refuses

**Comment by winnipeg21** [comment]
+1 Hope this can be solved

**Comment by TheJayZ** [comment]
+1

**Comment by AL1L** [comment]
+

**Comment by sp614x** [comment]
This looks interesting. It could probably be fixed with some caching.

**Comment by sp614x** [comment]
Testing the bugfix, baseline 600 FPS:

![image](https://user-images.githubusercontent.com/16635441/42294896-4baaaf06-7fe5-11e8-976a-53db5d118b24.png)

36 diamond hoes with 1560 custom models.
Before 120 FPS:

![image](https://user-images.githubusercontent.com/16635441/42295004-5bd4ef1c-7fe6-11e8-9052-16e20221fcaf.png)

After 500 FPS:

![image](https://user-images.githubusercontent.com/16635441/42294986-39ea093c-7fe6-11e8-8f80-95741e74e6e3.png)

**Comment by sp614x** [comment]
Should the optimization be:
- always active - potential mod conflicts
- active only for models with more than 32 overrides - to skip vanilla compass/clock
- activated by the resource pack - property file

**Comment by NickAcPT** [comment]
In my opinion, it should be activated for models with more than 32 overrides.

**Comment by RubbaBoy** [comment]
Yeah, I think the second option would probably be the best. Are you just caching the items to an extent, or are you doing something more complicated?

**Comment by sp614x** [comment]
It is caching the combinations of item values and their corresponding models. The item values are quantized depending on the predicate test values to reduce the possible combinations.

**Comment by sp614x** [comment]
Preview OptiFine 1.12.2_HD_U_E2
 - optimized rendering of item models with many predicates (#1500)

The optimization is active for models with more than 65 predicates (the vanilla clock model has 65).

**Comment by sp614x** [comment]
Is the fix effective, FPS before/after?

**Comment by RubbaBoy** [comment]
Yeah, just tested it, I got an additional 500 FPS in some tests, thank you very much! I think a lot of people will be able to use feature/fix this with maps and resourcepacks.

**Comment by SteveKunG** [comment]
After implemented this, Latest OptiFine incompatible with Forge 2729 (latest).

**Comment by sp614x** [comment]
Updated preview E2 for 1.12.2 to be compatible with Forge #2729.
