### ISSUE TITLE
Minecraft optifine won't open

### ISSUE THREAD

**Issue by Bubblebuddy14** [sp614x/optifine#1501]
I was just playing minecraft one day then suddenly My skin or any skin won't load so I thought it was a game bug so I reopened the game and it wouldn't load and I went to task manager and found 2 launchers and I delete the bottom one and the game works but the skin still is a problem. I thought it was a minecraft bug but when I play the original version it works properly so if anyone can please help

**Comment by VirxEpicoder** [comment]
A. What version of Optifine r u using? U might have to update it. Also, what version of Minecraft r u using?
B. How are you launching Optifine (via Forge or as a launch option.)
B1. If you're using Forge, make sure you're using the right version of Forge for you Minecraft version and Optifine version. You can't run Forge 1.12.2 with Optifine 1.8.9. Update Forge and Optifine to their correct versions. (Forge: [files.minecraftforge.net](https://files.minecraftforge.net) Optifine: [optifine.net/downloads](https://optifine.net/downloads))
B2. If you're launching Optifine as a launch option, make sure to run Optifine's .jar file and click install, and that will create the proper launch file to run Minecraft.
