### ISSUE TITLE
Erratic mouse movements

### ISSUE THREAD

**Issue by Novotisy** [sp614x/optifine#1506]
Using optifine, both the optifine profile and with forge(with and without mods), my mouse movement is randomly erratic(moving slowly then fast randomly). It makes the game unplayable. I have two monitors, while one is 144 hz, while my friends have one. They dont have the problem while I do. It continues to happen even after wiping windows twice on two different builds. When I have a higher fps however, it only does it for the first 10 or 20 seconds, then goes away. If I have 100+ mods installed, it will constantly do it.
[latest.log](https://github.com/sp614x/optifine/files/2152775/latest.log)
I am using the latest 1.12.2 version E1

**Comment by Enigmat1s** [comment]
**Upvote** 
I have the exact same issue, on clean OptiFine E1

**Comment by KaiAF** [comment]
This should have been fixed in 1.12 / 1.13. If you are still having this issue, create a new issue, please.
