### ISSUE TITLE
The jar was a rar file for no reason

### ISSUE THREAD

**Issue by ReylordFX** [sp614x/optifine#1508]
I dont know how

**Comment by Dushess** [comment]
it should be local problem with your OS.

**Comment by mindforger** [comment]
>The jar was a rar file for no reason

you may have bound winrar to open jar files ... or do you mean the jar war a renamed rar container ?

**Comment by sp614x** [comment]
Sometimes WinRar is registered to open JAR files. 
This should be fixed when Java is installed or reinstalled.
