### ISSUE TITLE
Rain splashes on entities

### ISSUE THREAD

**Issue by Regnander** [sp614x/optifine#1513]
A few days ago I was watching a Minecraft Let's Play where it suddenly started raining. I couldn't help but notice how the rain was splashing on the ground around the players, but not on the players themselves.

Then I remembered how the rain works in _Metal Gear Solid 2: Sons of Liberty_, where it splashes on the head and shoulders of any character in the rain:

![metal-gear-solid-2-making-of-the-hollywood-game](https://user-images.githubusercontent.com/17113053/42395969-18112644-8160-11e8-990a-2eb801def844.gif)

Can this be implemented in a similar fashion so when an entity is standing in the rain, water particles are added on top of their hitbox or model? 

I hope the latter isn't too resource demanding, since one downside with using the hitbox is that it won't look good on all entities, like the llamas where the rain splashes will appear in midair above their back since their hitbox stretches vertically to cover their long neck:

![lama-hitbox](https://user-images.githubusercontent.com/17113053/42404713-eba13564-818b-11e8-9bf4-5a5629b218d8.png)

Here's an photomontage how my idea would look like, without and with rain splashes:

![rain-splash-example](https://user-images.githubusercontent.com/17113053/42405044-669a79ac-8190-11e8-8de1-e89862f2b2da.png)

**Comment by sp614x** [comment]
Most animals have some kind of fur or hairs so the raindrops don't splash as much as they do on the hard ground. 
Implementing it is also quite complex as the rain splashes would depend on the entity model (which can be very complex), they should be uniformly distributed between all the model surfaces, etc. The best solution would be some kind of raytracing which would be slow.
