### ISSUE TITLE
OptiFine 1.12.2 HD U E2 pre can't raise shield

### ISSUE THREAD

**Issue by HawaiianPi** [sp614x/optifine#1516]
Clean install of Windows 10 x64 version 1803 (spring update version).

Clean install of Minecraft Java Edition 1.12.2 as well (no mods other than Optifine),

Default launcher settings.

Optifine_1.12.2_HD_U_E1 works as expected. When blocking the shield is raised up.

With preview_OptiFine_1.12.2_HD_U_E2_pre I do not get the blocking position. The shield just bobs down off the screen for a split second and then returns to the holding position.

**Comment by PabloVllgs** [comment]
Also affects bow charging animation. Doesn't show up the arrow entity in the animation

**Comment by sp614x** [comment]
OptiFine 1.12.2_HD_U_E2
 - fixed shield and bow model variants (#1516)
