### ISSUE TITLE
[Request] CBT(custom block textures)

### ISSUE THREAD

**Issue by OktayYeniTR** [sp614x/optifine#1519]
I do not know but it would be nice if it is added

**Comment by SetantaLP** [comment]
Would be cool, but it's not possible at the moment due to technical reasons (see https://github.com/sp614x/optifine/issues/968)

**Comment by sp614x** [comment]
Blocks have only a block ID and metadata (block state). These can already be used with CTM.
Keeping the item properties (name, nbt, etc.) when placing the block would require changing the game save format and it would negatively affect the performance. This would also not work in multiplayer.
Changing the game save format is something that OptiFine generally doesn't do.

**Comment by g-flyMC** [comment]
@sp614x now whis nms it's possible if optifine make change ? (i'm 1.8.9 player i don't now how to make custom block , i've try ctm but i'm stuck )
