### ISSUE TITLE
Underwater texture overlay with shaders

### ISSUE THREAD

**Issue by BruceKnowsHow** [sp614x/optifine#152]
Currently, going underwater overlays a version of the non-animated water texture on top of the screen. I'm not a fan of the effect, and it seems to be applied post-shaderpack (here's a [picture](http://puu.sh/pg8Mz/169dae7f72.png) of a pure grey shaders output). It seems like a bad idea to be enforcing cheap overlay on top of the more varied underwater effects that shaderpacks come up with.

**Comment by sp614x** [comment]
Added option underwaterOverlay
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.properties
