### ISSUE TITLE
Extreme lag (1.12.2 - Optifine HD U E1)

### ISSUE THREAD

**Issue by GammaMicroscopii** [sp614x/optifine#1521]
I just updated Optifine from C6 to E1 (1.12.2) and I have experienced a massive decrease in fps (from 30-60 to 3-5) and chunk loading rate. I also have noticed that the framerate is almost equal to the amount of chunk updates (the display only updates if any chunk does, with sometimes a couple or three extra fps that might come from another internal process update).

Exploring in creative, however, increases fps and chunk loading to almost C6 levels, but when I stop, chunks almost stop loading and the framerate drops back to 3-5.

**Comment by sp614x** [comment]
Is OptiFine installed standalone or with Forge?
Which Forge version, other mods installed?
Can you post the game output or error log?
F3 screenshot?
From which OptiFine version does the problem appear (C7, C9, D1, D3, ...)?

**Comment by GammaMicroscopii** [comment]
I tried with all versions of Optifine from D1 to C7 and this happened in every one. If it isn't weird enough, I re-downloaded C6 (the one I used until last week) and this not only started happening, but FPS just dropped to HALF of the chunk updates. I think this is caused by some kind of paranormal activity.

**Comment by GammaMicroscopii** [comment]
I have Optifine installed with Forge version 1.12.2 - 14.23.0.2491.
Other mods: WorldEdit (mc1.12-6.1.8-dist) only.
Game output: I don't know how.

**Comment by GammaMicroscopii** [comment]
![2018-07-14_23 57 03](https://user-images.githubusercontent.com/41028263/42728769-e381e88c-87c2-11e8-9689-1baa36b428cc.png)
![2018-07-15_00 00 54](https://user-images.githubusercontent.com/41028263/42728773-ec374346-87c2-11e8-96b2-a8ddb7b88a54.png)

**Comment by GammaMicroscopii** [comment]
Note that it took over 2 minutes to fill the first lap of the lagometer in the second picture.

**Comment by Miclebrick** [comment]
Try optifine without forge (run the jar directly it will install a standalone profile) also that forge build is a few hundred versions outdated I think

**Comment by GammaMicroscopii** [comment]
Is this common? I have Java 8 update 171 installed, but i open Minecraft and it displays my Java version as 1.8.0_51. I used the Java old version uninstall tool and it only detected in my system the update 171. Then I opened minecraft again and it displayed again 1.8.0_51. This is intended, is a Java issue, a Windows issue, a Minecraft issue, an OptiFine issue, or is my computer haunted? Does this happen to anyone of you? Can it have something to do with my lag problem?

**Comment by GammaMicroscopii** [comment]
I cannot dowload the latest version of OptiFine (E1) because mi antivirus detected malware in the download URL (https://optifine.net/downloadx?f=OptiFine_1.12.2_HD_U_E1.jar&x=2a16bfff8679810b014ce2abc96ac024)
I removed all the OptiFine installers after trying all versions to see the first problematic one.
What can I do?

**Comment by Miclebrick** [comment]
What anti-virus do you have? Also, it's possible to bypass that, how you do that depends on the anti-virus. If it's something like avast or McAfee I personally recommend you get rid of it

**Comment by KaiAF** [comment]
Is this still an issue?
