### ISSUE TITLE
Disappearing blocks

### ISSUE THREAD

**Issue by barteldvn** [sp614x/optifine#1522]
Tested with Optifine 1.12.2 E1 and E2pre.
Launching with no other mods and from the vanilla launcher.

High blocks disappear when viewed from far away.
(note I used fov 30 in these screenshots to show it more clearly, so it looks quite close)

![2018-07-10_16 08 56](https://user-images.githubusercontent.com/41066499/42515511-376d1440-845c-11e8-9b0b-7b60144dc69b.png)
![2018-07-10_16 08 59](https://user-images.githubusercontent.com/41066499/42515436-0bd02f84-845c-11e8-9347-e06fdede5bb5.png)

**Comment by sp614x** [comment]
Is this a superflat world?
World download link?

**Comment by barteldvn** [comment]
It happens on every multiplayer world, doesn't seem to happen on singleplayer.
![2018-07-11_11 43 05](https://user-images.githubusercontent.com/41066499/42563917-b6d53a52-84ff-11e8-8774-5d7efa355783.png)
![2018-07-11_11 43 11](https://user-images.githubusercontent.com/41066499/42563918-b6ef30c4-84ff-11e8-92b5-eca97ff152e8.png)
![2018-07-11_11 42 57](https://user-images.githubusercontent.com/41066499/42563919-b705bb32-84ff-11e8-8547-b79cb40a7ad5.png)

**Comment by sp614x** [comment]
Preview OptiFine 1.12.2_HD_U_E2
 - fixed distant higher chunks disappearing in multiplayer (#1522)
