### ISSUE TITLE
OptiFine's Smart Animation Bug

### ISSUE THREAD

**Issue by princessbinas** [sp614x/optifine#1524]
I used two different version of VoxelMap (mod_voxelMap_1.7.0_for_1.12.2 and mod_voxelMap_1.7.1_for_1.12.2) during my pursuit of solving a bug I had. The bug involves Smart Animations being turned on. When turned on, you are unable to enter the "Create Waypoint" menu. What happens is that the game crashes. I am using this modpack with some of my changes, which are visible in the crash reports: https://minecraft.curseforge.com/projects/vampirism-official-server-modpack

Optifine Version in Question: OptiFine 1.12.2 HD U E1

Crash Reports:

(With VoxelMap 1.7.0)

[crash-2018-07-10_17.28.03-client.txt](https://github.com/sp614x/optifine/files/2182371/crash-2018-07-10_17.28.03-client.txt)

(With VoxelMap 1.7.1)

[crash-2018-07-10_17.39.21-client.txt](https://github.com/sp614x/optifine/files/2182373/crash-2018-07-10_17.39.21-client.txt)

**Comment by sp614x** [comment]
Voxelamp is calling `GlStateManager.bindTexture(-1)` which is not allowed by OpenGL and should generate an error.

**Comment by sp614x** [comment]
OptiFine 1.12.2_HD_U_E2
 - fixed crash with Voxelmap and Smart Animations (#1524)

**Comment by princessbinas** [comment]
Thank you!

**Comment by darthvader45** [comment]
Hopefully this new version, when released, can help with my current OpenGL errors.

**Comment by sp614x** [comment]
@darthvader45 you can download the preview E2 version on https://optifine.net/downloads

**Comment by darthvader45** [comment]
Thanks.

Golden rule in Minecraft: Never dig straight down.
