### ISSUE TITLE
Optifine not working with chiseled glowstone from chisels & bits

### ISSUE THREAD

**Issue by tedmihu** [sp614x/optifine#1526]
Minecraft version: 1.12.2
Forge Version: 14.23.4.2708
Optifine Version: 1.12.2_HD_U_D1

When placing down chiseled glowstone blocks from the mod chisels and bits, the glowstone does not glow when optifine is in the mod-pack. THis applies to the bit-sized blocks as well as all the other fractions.

**Comment by sp614x** [comment]
Testing Forge #2729 + OptiFine E1 for 1.12.2 + Chisel & Bits 14.18.
The chiseled glowstone block emits light as it should:

![image](https://user-images.githubusercontent.com/16635441/42626070-a07393e2-85c9-11e8-84cc-bcea9d040f64.png)

**Comment by sp614x** [comment]
The single glowstone bit doesn't emit light with or without OptiFine:

![image](https://user-images.githubusercontent.com/16635441/42626335-53b618c6-85ca-11e8-90cd-74b5a3816355.png)

**Comment by sp614x** [comment]
The glowstone bits are using emissive (fullbright) texture.
The relevant issue is #631.

Currently it can't be fixed because:
- the Forge lighting pipeline breaks way too many OptiFine features
- Forge doesn't give enough information to OptiFine, so that it can simulate the fullbright effect

**Comment by tedmihu** [comment]
Oh wait, so this is a resource pack issue?

**Comment by sp614x** [comment]
Chisel is using a built-in emissive textures. They are part of the block model, not loaded as resource pack.
This special functionality is supported by the Forge lighting pipeline. 
OptiFine disables the Forge lighting pipeline because it breaks way too many OptiFine features. 
More details here #631.
