### ISSUE TITLE
Sensitivity Issue with 1.12

### ISSUE THREAD

**Issue by springtrr** [sp614x/optifine#1528]
Using no other mods, launching the Optifine 1.12_HD_U_C7 profile whenever I load into the game I have erratic mouse movement as if it's reached 500% sensitivity, the problem persists whenever I'm doing terrain generation/chunk loading (or maybe CPU issue? I haven't looked that far). The problem started when I came back to the game after taking a break for my exams, with all the mods untouched. I tried to single out which mod might be the problem and after testing standalone Optifine, the problem was clear it was the mod. I removed everything from my .minecraft folder and started anew by running Optifine 1.12_HD_U_C7 to ensure no other options/configs were interfering of some kind and the problem was still there. I tested this with C7, C5, C4, C3, C2 on the same world and the issue still remains in every Optifine version. I also tested this issue _without_ using an Optifine profile and suddenly no crazy mouse glitching. I can only use 1.12 versions because that's what my server runs and I really need Optifine because lag-optimization. The Optifine version that I use (1.12_HD_U_C7) with my mods is compatible and my mods don't auto-update (I'm not sure if that's even a thing) and I haven't added any new mods or updated any of my existing mods. 

I saw a few others submit the same issue and one of their solutions which was to reinstall Windows is a little out of reach for me.

sp614x stated: "OptiFine does not change the mouse handling in any way. It also does not change anything related to the mouse". So I'm unsure why this problem occurs in the first place.

Any help is appreciated,
Thanks.

**Comment by Miclebrick** [comment]
C7 is old, update to E1 and test it there before reporting any issues.

**Comment by sp614x** [comment]
What CPU are you using?
F3 debug screenshot?

**Comment by mgdgfbhevdyeh** [comment]
I have meet this BUG after 1.8 with Optifine
This happens to any Optifine version I have download
A known workaround is to set the priority of javaw.exe to "below the normal" in the task manager.
if it isn't working, try to turn on "Disable display scaling when setting high DPI" in javaw.exe properties panel(also Minecraft)
This is commonly known as "Mouse spasms"
In fact, I don't know how it happen
Also, It seems to be related to the graphics card driver.

**Comment by sp614x** [comment]
Does reducing the priority of "java.exe" in TaskManager to "below normal" solve this problem?

**Comment by mgdgfbhevdyeh** [comment]
at least working for me and I have long time not meet this problem.

**Comment by springtrr** [comment]
I'm using a i5-4460 @ 3.20Hz and setting the priority below normal does absolutely nothing.

![image](https://user-images.githubusercontent.com/41165187/43659833-18f3690e-9755-11e8-883b-9b230a181a90.png)

Here is the F3 Screenshot, I'm not exactly what is needed but ya'know

**Comment by realjackasterisk** [comment]
Do you have a Razer mouse by any chance? I've seen several people having sensitivity issues with MC and all of them had Razer mice.

**Comment by springtrr** [comment]
I'm using a Logitech mouse

**Comment by MineyShadow** [comment]
Still an issue on the latest optifine (1.12.2 E4 pre1), normally this happens to me if my CPU usage is high (especially in resource heavy mod packs) and doesn't occur much when playing multiplayer where most of the load is on the server.

**Comment by Rozzemak** [comment]
To summarize the problem: 
Forced v-sync like input processing & mouse smoothing in minecraft is not implemented as dpi aware app.
1) Mouse smoothing, which will kick in at fps spikes => chunk fetching & loading as well and other cpu heavy tasks.
1a) The mouse movement presumtion algorythm is wrong. It does not count with windows dpi scaling, so if you have it set to anything else than 100%, it will behave badly. (Especially when fps<hz. Even with only micro-stuttering.)
2) Try to enable other v-sync than the one that is built in. Add nvidia profile to jawaw.exe in runtime folder. 
There are 3 other solutions: 
1) Hack in raw input. (Gl)
2) Create mod that disables mouse smoothing routines.
3) Use controller,.. kappa.

**Comment by thegamerx1** [comment]
Still happening with f5

**Comment by TwinShards** [comment]
" I have erratic mouse movement as if it's reached 500% sensitivity"
This may be a open issue left behind but Optifine has nothing to do with the issue i quotted.
It still happen with vanilla minecraft.
If you have a Razer, LogiTech, Corsair or any other mouse that have a Polling rate setting, you probably did set it to 1000hz/1msec And this is your issue.
Random mouses with no setting all have a polling rate of 125hz/8ms. with a (dpi of 800-1200 irrellevant to the issue)
This issue does appear to happen in 1.12.2, (in 1.13 i don't know) below (>1.11 idk either) and in 1.14.4+ this issue is not present.
You can't do much about it beside lowering your polling rate while playing 1.12.2 (and i suspect older version)

**Comment by KaiAF** [comment]
Is this still an issue?

**Comment by DiamondDilly** [comment]
> 4\. polling rate

How do I change the polling rate in my mouse?
