### ISSUE TITLE
Bug: "Fast Math" option changes world generation

### ISSUE THREAD

**Issue by hypehuman** [sp614x/optifine#1530]
The "Fast Math" option causes blocks to generate a bit differently. I haven't observed it causing big changes, rather minor differences in block type boundaries, especially in caves. I think this should either be considered a bug and fixed, or the tooltip for the "Fast Math" option should warn the user that world generation will be affected.

Steps to reproduce:

1. Run Vanilla Minecraft v1.12.2 (with no mods).
2. Create a world with seed -343522682.
3. Observe that the block at (-177,69,-311) is air. 👍 
4. Run Minecraft v1.12.2 with OptiFine 1.12.2 HD U E1
5. Turn off Options.. => Video Settings.. => Performance.. => Fast Math (if not already, since this is the default setting).
6. Create a world with seed -343522682.
7. Again, observe that the block at (-177,69,-311) is air. 👍 
8. Turn the "Fast Math" option on.
9. Create a world with seed -343522682.
10. Observe that the block at (-177,69,-311) is stone. 👎

**Comment by sp614x** [comment]
The option Fast Math uses a faster version of sin() and cos() with lower precision.
Usually this is no problem, but in some cases it can minimally change the world generation. 
This is normal and expected behaviour.

**Comment by hypehuman** [comment]
But then shouldn't the tooltip say that? If I had known this, I would not have used that option. The tooltip just says it's faster, nothing about lower precision.

**Comment by realjackasterisk** [comment]
^ I second this. People seem to constantly have compatibility issues with the fast render and fast math options in Optifine.

**Comment by sp614x** [comment]
The tooltips should probably be updated.

**Comment by hypehuman** [comment]
Thanks sp614x! This will help people avoid surprising results when doing fixed-seed speedruns, or sharing seeds that generated funny faces in the terrain :)

**Comment by sp614x** [comment]
Updated Fast Render and Fast Math tooltips.
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/assets/minecraft/optifine/lang/en_us.lang#L552

**Comment by Artoria2e5** [comment]
How much faster is fast math supposed to be anyways? I checked the stuff in Optifine's version of `net.minecraft.util.math.MathHelper`, and it just doesn't sound convincing enough to say a 4096-sized lookup table is much faster than a 65536-sized one, unless stuff like CPU cache get deeply involved.

Well, guess it's time for some benchmarking...
