### ISSUE TITLE
[Request] Separate contrast and brightness?

### ISSUE THREAD

**Issue by Miclebrick** [sp614x/optifine#1540]
A lot of the time I find myself switching between low and high brightness. I do this because low brightness is too dark to see things, and high brightness just makes shadows less dark and therefore simply has less contrast. In image editors like Paint.NET you can edit screenshots of MC with both brightness and contrast, which I've used to make screenshots for YouTube thumbnails more presentable.
What if there was a way to increase the contrast while still having brighter light, without having to get slow shaders?

**Comment by retep998** [comment]
Use a custom lightmap with the light levels you want.

**Comment by sp614x** [comment]
Increased contrast generally means non-linear brightness.
This can be done with a custom lightmap: https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/custom_lightmaps.txt
