### ISSUE TITLE
Infinity evolves crash

### ISSUE THREAD

**Issue by Bettimine** [sp614x/optifine#1547]
Since HD_U_D7 Infinity Evolved (1.7.10) crashes.
[crash-2018-07-15_19.44.37-client.txt](https://github.com/sp614x/optifine/files/2195960/crash-2018-07-15_19.44.37-client.txt)

**Comment by sp614x** [comment]
Java complains that it can't load the class TextureMap.
Looks like a conflict with some other mod which is incorrectly patching the TextureMap class.
