### ISSUE TITLE
A Suggestion For The Dynamic Lights

### ISSUE THREAD

**Issue by mxnmnm** [sp614x/optifine#1549]
Can you add a config that allows you to put an item id that would make it behave like torches and such?  I think it would add more mod compat :)

**Comment by realjackasterisk** [comment]
Uh, isn't that just this?
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/dynamic_lights.properties

**Comment by mxnmnm** [comment]
All of the things I wanted to add already worked xD
