### ISSUE TITLE
Dynamic Lights - Redstone Torches 

### ISSUE THREAD

**Issue by iamtherealdoge** [sp614x/optifine#155]
Redstone torches reduce the light of a certain area when held, using Dynamic Lights on "Fancy". The floor there is made out of slabs not full blocks [EDIT: this only happens if there are no blocks beneath the ones in the wall, check 3rd screenshot]

[Redstone Torch held](http://s33.postimg.org/j2kpfsegv/2016_06_05_13_23_24.png)

[No Redstone Torch held](http://s33.postimg.org/fq413it6n/2016_06_05_13_23_21.png)

[Explanation](http://s33.postimg.org/d1zgpctof/Explanation.png)

[With blocks](http://s33.postimg.org/5vka6tkqn/2016_06_05_13_43_01.png)

**Comment by sp614x** [comment]
This seems to be specific to top slabs.
When using top stairs for the floor  the problem does not appear.

**Comment by sp614x** [comment]
The vanilla smooth lighting for slabs seems to be broken. Lighting the slab floor from below in a dark room causes the slabs to be fully lit: http://i.imgur.com/2ie68OY.png
Dynamic lights handle stairs and slabs identically and the stairs lighting is correct.
