### ISSUE TITLE
[Suggestion?] Merge 'mcpatcher' and 'optifine' folders for the 1.13 update

### ISSUE THREAD

**Issue by realjackasterisk** [sp614x/optifine#1557]
Minecraft 1.13 is just around the corner, and unfortunately, it brings very notably breaking changes to resource packs once again.

This is a great opportunity to help add some more consistency and convenience to OptiFine. For this update, I'd like to suggest merging the mcpatcher folder with the optifine folder in resource packs. The idea is to simply bring all of OptiFine's resource pack features into a single folder. No more going back and forth between two completely separate file directories, with one being the remains of the now 3 years outdated MCPatcher.

Is it a good idea? Maybe, maybe not.
Tell me what you guys think, especially you resource pack creators. What are your arguments for **or** against this?

**Comment by realjackasterisk** [comment]
Many mods including OptiFine still have to wait for MCP to update to 1.13, before they themselves can update. It's not like it's too late for suggestions.

**Comment by Madis0** [comment]
Obviously it isn't too late for suggestions as a whole, but doing this in 1.13 can cause a lot of confusion - resource pack makers update their packs to be compatible with version 4 and suddenly OptiFine breaks. I'm suggesting would be better to do (enforce) it whenever Mojang updates resource pack version to 5, meanwhile the changes could be planned and documented or even a transition conversion or dual support implemented.

**Comment by sp614x** [comment]
OptiFine 1.13.1_HD_U_E3_pre5
 - moved all configurations from folder "mcpatcher" to folder "optifine" (#1557)
