### ISSUE TITLE
Shaders bug with AstralSorcery

### ISSUE THREAD

**Issue by QianChang233** [sp614x/optifine#1564]
There is a problem like this.
https://i.loli.net/2018/07/19/5b5039e7be467.png

**Comment by sp614x** [comment]
This is a known problem with the AstralSorcery sky:
https://github.com/HellFirePvP/AstralSorcery/issues/505
https://github.com/HellFirePvP/AstralSorcery/issues/236
https://github.com/HellFirePvP/AstralSorcery/issues/705
