### ISSUE TITLE
CTM Glasspane frame bug

### ISSUE THREAD

**Issue by TheHADILP** [sp614x/optifine#157]
In the first picture you can see that the glass panes have a top texture (without Optifine).
![2016-06-06_22 41 14](https://cloud.githubusercontent.com/assets/16366556/15880680/f7151abc-2d2f-11e6-8f5c-e3ec1335e0f3.png)
But here in the second image the top glasspane frame textures are weird (Optifine installed).
![2016-06-06_22 42 00](https://cloud.githubusercontent.com/assets/16366556/15880716/31f3460e-2d30-11e6-990a-f5aada1f63d5.png)
I tested it on the stock resourcepack and also on another one with the same results.

**Comment by sp614x** [comment]
Fixed, coming in B6 for 1.9.4

**Comment by TheHADILP** [comment]
Thanks for the quick fix.
I tested the new pre Version and this issue is fixed for the Stock textures.
But when I use a custom resourcepack this is still an issue.
I wanted to ask how you fixed the textures so that I can apply that fix to the pack I use.
Thank you in advance.

**Comment by sp614x** [comment]
The CTM properties for glass panes should specify "faces=sides" so that top and bottom textures are not replaced.

**Comment by TheHADILP** [comment]
Ah yeah I forgot that. Thanks
