### ISSUE TITLE
Combine full screen toggle and resolution

### ISSUE THREAD

**Issue by Madis0** [sp614x/optifine#1571]
In 1.13, the full screen resolution setting has been implemented to vanilla, the slider is wider and contains more information than Optifine's. However, since it is wider, it takes up the space of two buttons and that space is really precious with Optifine's menus.

That gave me an idea - what if you combined the full screen toggle with the full screen resolution? It could work similarly to how you combine FPS with VSync - the lowest value would be "off" in this case.

**Comment by Madis0** [comment]
As of OptiFine HD E3_alpha8 Ultra, neither built-in or Optifine's slider is present, so maybe this is still under consideration? :slightly_smiling_face:

**Comment by Jiingy** [comment]
This isn't really possile with how the slider works. 

If the slider is 1-10, you can't have a 1 or 0 (on/off) within that
