### ISSUE TITLE
Extreme Reactors reactor control buttons are blurry with Optifine installed. 

### ISSUE THREAD

**Issue by Mario3264** [sp614x/optifine#1578]
For reference, the buttons usually look like this (looks like nearest neighbor, no filtering):
![image](https://user-images.githubusercontent.com/16366524/43117198-6d282ee4-8ec0-11e8-8ff5-32f9c5d6b8b3.png)
But, it looks like this with Optifine (looks like bilinear filtering):
![image](https://user-images.githubusercontent.com/16366524/43117220-8c423f0e-8ec0-11e8-824b-d5ab55456ccd.png)

**Comment by sp614x** [comment]
When mipmaps are enabled all textures need to have power-of-2 sizes.
If there are non power-of-2 textures OptiFine rescales them to the next power-of-2 size.
In the same case Vanilla/Forge don't rescale the textures, they reduce the mimap level or disable the mipmaps which affects all the textures.
