### ISSUE TITLE
Glasspane frame bug in inner corners

### ISSUE THREAD

**Issue by TheHADILP** [sp614x/optifine#158]
When you build a corner with glasspanes they have a weird CTM on the inside corner.
![2016-06-07_23 22 21](https://cloud.githubusercontent.com/assets/16366556/15891146/8899d156-2d73-11e6-906f-42f2f8b71e99.png)
The outside of the corner works just great.
![2016-06-08_12 14 36](https://cloud.githubusercontent.com/assets/16366556/15891011/cd25260a-2d72-11e6-9236-6bb642de0cd7.png)

**Comment by sp614x** [comment]
Resource pack, version?

**Comment by TheHADILP** [comment]
Version: 1.10-OptiFine_HD_U_A2_pre
Resource pack: based on Misa but tweaked and updated by me.
                         The CTM glass textures are from [this](http://www.mediafire.com/download/uxbct865r0oo1p1/CTU+1.5.x.zip) pack (under ctm-->ctm)
but I also updated them slightly.
So here is the CTM glass that I use now (https://www.dropbox.com/s/l8bcobemd214wkc/glass.zip?dl=0).

**Comment by Brottweiler** [comment]
This is an issue with your properties files. I had the same issue, and I fixed it in [this commit](https://github.com/Plastix/Plast-Pack/commit/8ebf5e64525767777d4a12a823c99eeba4e215c1) for a resource pack.

Please read [this post](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1272953-optifine-hd-c3-fps-boost-dynamic-lights-shaders?page=2507#c52129) and the posts following that one, made by sp614x and myself.

**Comment by TheHADILP** [comment]
Thanks for the hint.
I read a bit in the thread and then I refactored my glass ctm tiles to 0-46 numbering (they were messed up with the legacy numbering before).
I also had a 47th tile; I removed it as it isn't even used.
Now the glasspanes work properly.
