### ISSUE TITLE
[1.12.2] Emissive Textures on Entities and Astral Sorcery

### ISSUE THREAD

**Issue by Liamdude** [sp614x/optifine#1581]
I have a custom texture pack which uses emissive textures to spruce up items. However, after adding mods, I discovered that Minecraft would crash when loading emissive textures only for entities (not for regular blocks or items and from a variety of mods with special textures and some items that have no emissive textures nor texture changes at all [had a crash for a boat render once]). After removing all mods and slowly re-adding them, I have determined that Astral Sorcery is the mod causing the problem. However, I am not sure why, since the log says that the textures for entities magically cannot be found after adding it. I am also going to post this issue on the Astral Sorcery error page, but I wanted to mention it here because not many people discuss emissive texture issues at all. The two logs are with the EXACT same settings and texture pack. Only the alchemical chest has an emissive texture (the Quark chest does not), but even the Quark chest crashes (only when the emissive texture pack includes textures for entities).

EDIT: I contacted AS, and they were unwilling to help with this issue, especially because the error log does not specifically mention AS. I had tried adjusting the configs for AS as well, but that did not change the result, and the development team was only able to weakly suggest that I change configs I had already tried.

[crash-2018-07-26_21.59.38-client.txt](https://github.com/sp614x/optifine/files/2234187/crash-2018-07-26_21.59.38-client.txt)
[crash-2018-07-26_21.44.38-client.txt](https://github.com/sp614x/optifine/files/2234188/crash-2018-07-26_21.44.38-client.txt)

**Comment by GreatestFool** [comment]
The Astral Sorcery dev wasn't unwilling to help, they were *unable* to help.

Regardless, I can confirm that this is easily reproducible. Only Optifine and Astral Sorcery is enough to make it happen. If there is only an emissive block texture, it works fine. But the moment the resource pack contains emissive textures for entities, it crashes once an emissive texture is rendered.

Here's the [full log](https://pastebin.com/1fWFVmwc). And here's a [crash log](https://pastebin.com/QCGiUhVW) and another [crash log](https://pastebin.com/jyb48rY4) with another version of Optifine.

**Comment by sp614x** [comment]
Fixed, coming in next 1.12.2 preview.
