### ISSUE TITLE
[Suggestion] When textures are mipmapped, only non-transparent parts should be filtered.

### ISSUE THREAD

**Issue by Mario3264** [sp614x/optifine#1582]
When textures are mipmapped, but only non-transparent parts should be filtered (filtered as in Nearest, Linear, etc.) It would fix the issues such as the torches being blurred outside of their actual intended model when their textures get replaced with their mipmapped version while being too far away from the player.

**Comment by sp614x** [comment]
Mipmap filtering is applied to the whole texture at once, it can't be controlled per pixel.
Anisotropic filtering should fix the mipmap artifacts for torches.
