### ISSUE TITLE
[Installer] Fix installer for latest launcher version (w/ solution).

### ISSUE THREAD

**Issue by dscalzi** [sp614x/optifine#1601]
**Launcher Version**: 2.1.1351

After trying to install optifine on the latest version of the launcher, the profile was not showing up. 
After manually editing the configuration JSON, it worked.

### JSON generated by installer

```JSON
"OptiFine": {
    "name": "OptiFine",
    "lastVersionId": "1.12.2-OptiFine_HD_U_E2"
}
```

### What worked:

```JSON
"OptiFine": {
    "name": "OptiFine",
    "type": "custom",
    "created": "2018-07-31T13:06:28.919Z",
    "lastUsed": "1970-01-01T00:00:00.000Z",
    "lastVersionId": "1.12.2-OptiFine_HD_U_E2"
}
```

#### It's possible that the `type`, `created`, and `lastUsed` fields are now required. The following JSON is created for a bare minimum profile by the launcher.

```JSON
"ac8ee4df2c9bd4e002e36e44296c4db0": {
    "name": "",
    "type": "custom",
    "created": "2018-07-31T13:06:28.919Z",
    "lastUsed": "1970-01-01T00:00:00.000Z",
    "lastVersionId": "1.12.2"
}
```

## Suggestion

It would be better to have the installer store the profile with the OptiFine version. This way, it will not override other optifine installs.

### Solution JSON

```JSON
"OptiFine {VERSION}": {
    "name": "OptiFine",
    "type": "custom",
    "created": "2018-07-31T13:06:28.919Z",
    "lastUsed": "1970-01-01T00:00:00.000Z",
    "lastVersionId": "1.12.2-OptiFine_HD_U_E2"
}
```

`{VERSION}` could be something like this `(1.12.2_HD_U_E2)`. Alternatively you could just reuse the `lastVersionId` as the object's identifier.

**Comment by sp614x** [comment]
Fixed.

**Comment by dscalzi** [comment]
As a possible suggestion, save the profile as `Optifine {mcversion}` so that only updates for the same version are overriden.

Ex.
`Optifine 1.13.2` -> Only overriden by new Optifine 1.13.2 installs.

This way, old installations won't be removed (for example 1.12.2).

**Comment by sp614x** [comment]
The launcher doesn't overwrite the existing profile, it only updates it to use the next OF version. All profile settings are preserved.
