### ISSUE TITLE
Almost every time without fail, I crash.

### ISSUE THREAD

**Issue by prettyinaccurate** [sp614x/optifine#1608]
So, I downloaded the most recent Optifine installation, 1.12.2, and at first it seemed fine, but then I realized

_every time, without fail, i always crash when i leave a server and join it or a new one again._

This has happened ever since I had optifine installed and i don't understand what goes wrong. I join a server, seems fine, shaders are nice etc. but then, I leave, and try to go somewhere like Hypixel or I get kicked and try to rejoin and I _keep. crashing._ I always have to restart minecraft, and on my computer, that takes forever. Is it possibly just me or something in my game folders, or is it an issue that I just have to wait for optifine's update to have it fixed?

**Comment by Eeverlasting** [comment]
When i crashed like that it was because I only had 1g memory allocated to the mod. Once I bumped it to 2 then 3(due to more mods) all went fine.

**Comment by ZenIsBestWolf** [comment]
We need more details about this crashing, specifically logs and screenshots would help. Closing this due to it being old.
