### ISSUE TITLE
Issue's for Windows Minecraft 

### ISSUE THREAD

**Issue by LadyBugAngel80** [sp614x/optifine#1613]
II keep getting Minecraft Version 1.12.2 not found you need to dawnload it Manually once am on Windows 10 :/

**Comment by realjackasterisk** [comment]
.....uh, are you trying to install OptiFine for the bedrock edition of MC?

**Comment by Regnander** [comment]
I recognize this error message. You have to select the 1.12.2 vanilla version and click [PLAY] in the launcher in order to download it to your PC. When the download is finished, you should be able to install OptiFine.
