### ISSUE TITLE
Debug Profiler

### ISSUE THREAD

**Issue by EdwardTheGamer** [sp614x/optifine#1624]
Hello, in the last days I often have the problem below, the Debug Profiler is completely green, with the word "unspecified". I'm using Optifine 1.12.2 HD U E2.

![optifine bug 2](https://user-images.githubusercontent.com/42244508/43905825-29e3a9b2-9bf2-11e8-87ac-f39c7f70f7b8.jpg)

**Comment by sp614x** [comment]
You are inside the "display_update" branch. Press 0 to get one level up.
