### ISSUE TITLE
Camera Bug

### ISSUE THREAD

**Issue by CoutovyLp** [sp614x/optifine#1628]
Hi.
I installed the alpha version of Optine 1.13 and I have this bug/problem with camera

https://media.discordapp.net/attachments/468123442852397058/477759277596016640/unknown.png?width=994&height=560

**Comment by realjackasterisk** [comment]
This is a known issue with anti-aliasing. Also I don't think you should be posting issues for OF 1.13 until it reaches a final release...

**Comment by sp614x** [comment]
OptiFine 1.13_HD_U_E3_alpha9
 - fixed FXAA flipping screen vertically
