### ISSUE TITLE
[1.13 Alpha8] opening crash + temp workaround

### ISSUE THREAD

**Issue by BinaryJinx** [sp614x/optifine#1632]
hi, think i'm making a mountain out of a a mole hill.

Always crashes when opening lauching the version. dunno if its me but thought meh i'll let them know.

[crash-2018-08-11_20.52.57-client.txt](https://github.com/sp614x/optifine/files/2280509/crash-2018-08-11_20.52.57-client.txt)

Unexpected error

i: Non [a-z0-9/._-] character in path of location: minecraft:optifine/lang/en_US.lang

!Temp workaround.
Change language to: German, Czech or English (United kingdom) in vanilla.
Launch 1.13Alpha8 optifine and change to your language.  

i've tried it with English US, Portuguese Brazil.
i don't know if it'll work 100% afterwords though

**Comment by Chrishunk** [comment]
i what now too

**Comment by Chrishunk** [comment]
y, i'm using a launcher free, SKlauncher

**Comment by BinaryJinx** [comment]
it's just a bit confusing reading what you commented. so i just wanted to check.

i'm using Native launcher.

**Comment by BinaryJinx** [comment]
OK so i think the problem in the seqeance is at the en_us.lang part.  i know this because if i change my language to English United Kingdom in the Vanilla, i can launch the game in Optifine. working fine.

not really helpful for not english reading people tho.

**Comment by DjGamerDz** [comment]
me too

**Comment by sp614x** [comment]
Fixed in latest beta.
