### ISSUE TITLE
[1.13 Alpha 8] Liquids Aren't Animated 

### ISSUE THREAD

**Issue by Primed-Pixel** [sp614x/optifine#1633]
In the latest optifine 1.13 alpha, liquids aren't animated, whether they are on or off in Video Settings > Animations

**Comment by Chrishunk** [comment]
how did u do fixing the bug?

**Comment by BinaryJinx** [comment]
@Chrishunk what language do you play MC in?

**Comment by Chrishunk** [comment]
@Bjornskjald Portugues (brazilian)

**Comment by BinaryJinx** [comment]
@Chrishunk thanks just wondering

**Comment by Primed-Pixel** [comment]
@Chrishunk I haven't had that bug

**Comment by BinaryJinx** [comment]
@Primed-Pixel are you using English UK in minecraft?

**Comment by Primed-Pixel** [comment]
@BinaryJinx Yes

**Comment by BinaryJinx** [comment]
@Primed-Pixel anyone who isn't using German, Czech or English UK will have the language Crash bug.

**Comment by Bjornskjald** [comment]
@Chrishunk why did you mention me here?

**Comment by 133Seven** [comment]
Where are you getting the alpha builds?

**Comment by Primed-Pixel** [comment]
@133Seven On the optifine website, there is a preview builds button, click on that.
However the website seems to be down atm

**Comment by Andrew963** [comment]
dont you have smart animations on? because it turned animation of water when i turned it on

**Comment by Primed-Pixel** [comment]
@Andrew963 I can't find smart animations?

**Comment by HaiImDan** [comment]
This is seemingly an error with Smart Animations. It's meant to disable animations like water when you're not looking at them. However in this version it is disabling them no matter where you are looking.

**Comment by Primed-Pixel** [comment]
@HaiImDan Yes, turning off Smart Animations in Performance Settings does fix the issue

**Comment by 133Seven** [comment]
Shaders are really laggy and I'm on a system with a R9 270X & Xeon X5460, what seems to be the issue?

**Comment by sp614x** [comment]
Fixed in beta1.
