### ISSUE TITLE
[1.13 Alpha8] Textures not rendering correctly

### ISSUE THREAD

**Issue by BinaryJinx** [sp614x/optifine#1634]
Noticed some of the textures are being funky.

![2018-08-11_21 56 18](https://user-images.githubusercontent.com/42304045/43995989-809d37b2-9db1-11e8-9048-e74d6e64e438.png)
![2018-08-11_21 56 19](https://user-images.githubusercontent.com/42304045/43995990-80b2f552-9db1-11e8-8aaf-22b534202ed4.png)

There is also like a small gap inbetween the block edges (where the texture doesn't mesh/ line up correctly) that is transparent

![2018-08-11_22 03 23](https://user-images.githubusercontent.com/42304045/43996053-754be88a-9db2-11e8-82b6-29e9c9035f3a.png)

i just read somewhere that you shouldn't be posting pre 1.13 optifine errors/bugs. 
if so sorry.

**Comment by realjackasterisk** [comment]
This is a known issue with fast math.

**Comment by sp614x** [comment]
OptiFine 1.13_HD_U_E3_alpha9
 - fixed Fast Math accuracy
