### ISSUE TITLE
[1.13] A bug caused by Mojang makes a paricular("（ ") shown as square frame

### ISSUE THREAD

**Issue by HeartyYF** [sp614x/optifine#1638]
https://bugs.mojang.com/browse/MC-134299

Mojang changed all full-width left parentheses into half-width left parentheses to avoid the problem, and before 1.13 all characters in zh_cn(Minecraft) are full-width, but in 1.13 they are changed into half-width (this happens with all lang files changed into json files).

However, we still use lang files and I use full-width characters to adapt to zh_cn(Minecraft) before 1.13, so I wonder if OptiFine can fix the bug, or I will use half-width characters instead.

**Comment by HeartyYF** [comment]
And it has been fixed in 1.13.1 snapshot, so I suggest OptiFine fix this bug in 1.13.

**Comment by sp614x** [comment]
OptiFine generally doesn't fix bugs which are fixed in a vanilla bugfix release.
After updating to 1.13.1 there would be no reason to support the 1.13 branch.
