### ISSUE TITLE
Distorted (Streaking) Textures on certain blocks

### ISSUE THREAD

**Issue by Zefferis** [sp614x/optifine#1639]
![2018-08-12_02 51 28](https://user-images.githubusercontent.com/15270437/44000790-ea8b63be-9dda-11e8-804b-4dad397f4dfb.png)
Certain Blocks have face textures that are "streaking";

So far I have found this present on:

Sticky Piston
Piston

Brown Mushroom Block
White Mushroom Block
Mushroom Stem

Command Block
Chain Command Block
Repeating Command Block

Log circle texture when facing north

**Comment by Vencorr** [comment]
It seems to be rare but on this also happens on seemingly random blocks. Netherrack is one that only seems to have the streaking in specific positions and on specific sides.

**Comment by Andrew963** [comment]
I have same issue on pistons north side and leavers that are placed on wall

**Comment by FailGamesMC** [comment]
Lever also

**Comment by HaiImDan** [comment]
Also occurs on all open trapdoors when placed facing east/west on the upper sides of blocks. 
![2018-08-14_17 30 25](https://user-images.githubusercontent.com/42394615/44125756-2da98f3a-9fe9-11e8-93dd-5ded05bcedc0.png)

**Comment by realjackasterisk** [comment]
This is a known issue with fast math.

**Comment by crafter312** [comment]
I have this issue as well, although it seems to persist even when I turn off fast math.

**Comment by realjackasterisk** [comment]
@crafter312 Restart your game after disabling fast math.

**Comment by sp614x** [comment]
OptiFine 1.13_HD_U_E3_alpha9
 - fixed Fast Math accuracy
