### ISSUE TITLE
cant go to website

### ISSUE THREAD

**Issue by peijari** [sp614x/optifine#1644]
i cant go to optifine website but i can go to eny else website

**Comment by bballboy2002** [comment]
My theory is that so many people tried to go there at once after youtubers made videos about it that the traffic crashed the site

**Comment by 133Seven** [comment]
no it's probably a cloudflare DNS issue

**Comment by bballboy2002** [comment]
Can't be
![screen shot 2018-08-13 at 11 26 46a](https://user-images.githubusercontent.com/14823057/44050453-d132300c-9eeb-11e8-953b-c4d2ccffa421.png)

**Comment by HYPExMon5ter** [comment]
It's working now
