### ISSUE TITLE
[1.13 Alpha8]Antialiasing in Shaders settings work wrong

### ISSUE THREAD

**Issue by cui0v0** [sp614x/optifine#1646]
If I turn Antialiasing setting to FXAA 2X or FXAA 4x, the game screen will be wrong!

![Uploading O}`~{ME`8GGBDJ4KMC9YDE3.png…]()
![Uploading [Z3GE7_AD7R$C0%Z9YXQC[0.png…]()

**Comment by realjackasterisk** [comment]
#1628, #1636

**Comment by cui0v0** [comment]
OK, I saw.
