### ISSUE TITLE
[1.13 alpha8] Corner rail visual bug

### ISSUE THREAD

**Issue by brackets9357** [sp614x/optifine#1649]
![image](https://user-images.githubusercontent.com/42375655/44086688-3db514dc-9fb5-11e8-8171-520f720c1a1d.png)
Here I have spotted a bug where two corner rails have flipped to face the opposite of the way they should. Breaking and replacing them does not fix the issue. The rails function as normal regardless of visual orientation. You can also see that one rail has not become bugged; perhaps only certain rail orientations have visual issues.

**Comment by realjackasterisk** [comment]
I can't get this to work on my own client. What are your settings?

**Comment by sp614x** [comment]
OptiFine 1.13_HD_U_E3_alpha9
 - fixed Fast Math accuracy

This should probably fix it.
