### ISSUE TITLE
Texturepack sides broken

### ISSUE THREAD

**Issue by Dzakvh** [sp614x/optifine#1651]
![image](https://user-images.githubusercontent.com/32986041/44090655-3ad7648e-9fcb-11e8-8c6d-34fc791f136a.png)
As you can see, the sides textures from the stairs are glitched with/without resourcepack.
Also with trapdoors
It only when placed on the above side of the block
![image](https://user-images.githubusercontent.com/32986041/44091149-cf1ba6a4-9fcc-11e8-9f60-aff256c02d7e.png)

**Comment by Zefferis** [comment]
#1639 contains similar issues

**Comment by realjackasterisk** [comment]
This is a known issue with fast math.

**Comment by sp614x** [comment]
OptiFine 1.13_HD_U_E3_alpha9
 - fixed Fast Math accuracy
