### ISSUE TITLE
[1.13 alpha8] Bad texture of piston, when facing up/down

### ISSUE THREAD

**Issue by Interentak** [sp614x/optifine#1653]
When I place piston with facing up/down, so it has a bad texture.

![image](https://user-images.githubusercontent.com/28293642/44096658-19bfddec-9fdc-11e8-9802-3d26cd948d32.png)

**Comment by Zefferis** [comment]
contains the same issue as #1639

**Comment by realjackasterisk** [comment]
This is a known issue with fast math.

**Comment by FailGamesMC** [comment]
This problem is removed if you turn off fast math and reset minecraft.

**Comment by sp614x** [comment]
OptiFine 1.13_HD_U_E3_alpha9
 - fixed Fast Math accuracy
