### ISSUE TITLE
Optifine 1.13 is upside down

### ISSUE THREAD

**Issue by Bugboy72** [sp614x/optifine#1654]
I was testing out the alpha8 version, and when i joined my world, the world was entirelly upside down, this never happened with vanilla mc but happened on the latest alpha8 optifine.

**Comment by SkypilotTom** [comment]
check your shaders options.  options, video, shaders.  on the far right the first option is antialiasing.

turn off antialiasing.  you can also hit f4 to fix it.  that temporarily turns of antialiasing.

**Comment by lug-gh** [comment]
Same for me, no shaders, no shaders, no texture pack.

![screenshot](https://lickmynip.pl/share/i/j6vzf9esru.png)

**Comment by sp614x** [comment]
OptiFine 1.13_HD_U_E3_alpha9
 - fixed FXAA flipping screen vertically
