### ISSUE TITLE
Seemingly random rotated textures

### ISSUE THREAD

**Issue by madartist0** [sp614x/optifine#1655]
![2018-08-13_20 33 00](https://user-images.githubusercontent.com/42384348/44102125-f8148578-9fb6-11e8-9bc2-b6ebbdb1eb08.png)
![2018-08-13_20 43 40](https://user-images.githubusercontent.com/42384348/44102127-f850f1de-9fb6-11e8-94ac-a3e0d2ca8df1.png)
![2018-08-13_20 53 05](https://user-images.githubusercontent.com/42384348/44102128-f89b4f72-9fb6-11e8-8525-2347b34c88c2.png)
[1.13 Optifine preview HD-U-E3-alpha8] idk why this is happening or what causes it, but I unloaded all my resource packs and it was still happening, as well as turned off 'rotated blocks'

**Comment by brackets9357** [comment]
That is very strange. I found some corner rails were facing the opposite direction for no reason yet still functioned normally. Hopefully it will be fixed soon; at least it doesn't affect gameplay.

**Comment by Zefferis** [comment]
Idk about the rotation, but the streaked faces are mentioned with #1639

**Comment by realjackasterisk** [comment]
This is a known issue with fast math.

**Comment by sp614x** [comment]
OptiFine 1.13_HD_U_E3_alpha9
 - fixed Fast Math accuracy
