### ISSUE TITLE
[1.13 alpha8] Rendering issue on the edges of random blocks.

### ISSUE THREAD

**Issue by Voxolotl** [sp614x/optifine#1658]
There's a graphical issue where random sets of blocks are rendered incorrectly, making their edges invisible, thus letting the player see through.

![2018-08-14_19 34 06](https://user-images.githubusercontent.com/42387308/44108269-2e3d1474-9ffa-11e8-8c3a-1c8f357349aa.png)

**Comment by Zefferis** [comment]
Does this happen only with optifine? And do you run an Nvidia graphics card?

**Comment by FailGamesMC** [comment]
Im think it is only on optifine,but this annoys me a lot...

**Comment by FailGamesMC** [comment]
Does this error happen to you Zefferis?

**Comment by Voxolotl** [comment]
It only happens with Optifine, Zefferis. I'm also using an AMD GPU, a Radeon R9 270X.

**Comment by Memequickie** [comment]
**Cannot reproduce**

**Comment by realjackasterisk** [comment]
This is a known issue with fast math.

**Comment by The420Logic** [comment]
I am getting the same issue.  Only happens with Optifine - even with Fast Math disabled.

**Comment by realjackasterisk** [comment]
Restart your game after disabling fast math.

**Comment by OpenMind23** [comment]
I can confirm that disabling fast math and restarting the game fixes the issue. Thanks for the workaround realjackasterisk :)

**Comment by sp614x** [comment]
OptiFine 1.13_HD_U_E3_alpha9
 - fixed Fast Math accuracy
