### ISSUE TITLE
[1.13 Alpha8] Fog Cannot be Completely Disabled

### ISSUE THREAD

**Issue by Unicarn** [sp614x/optifine#1659]
![fog](https://user-images.githubusercontent.com/42402679/44136450-af31edbc-a021-11e8-9e07-cb24384f61ef.jpg)
Despite fog being disabled in options, there is still some fog. Turning on Fast or Fancy fog increases the amount of fog.

Edit: I forgot to mention it does not matter if I have resource packs enabled or not.

**Comment by Memequickie** [comment]
Since it's alpha version. Don't expect everything to be ready.

**Comment by sp614x** [comment]
OptiFine 1.13_HD_U_E3_alpha9
 - fixed fog options
