### ISSUE TITLE
Optifine Alpha 8 Connected textures not working

### ISSUE THREAD

**Issue by DanielAgostinho** [sp614x/optifine#1661]
On normal glass pane, there's no connection between panels like on 1.12 versions
![2018-08-15_18 02 34](https://user-images.githubusercontent.com/42416548/44161753-1add4180-a0b6-11e8-941f-a5c37f9dce34.png)
![2018-08-15_18 05 09](https://user-images.githubusercontent.com/42416548/44161756-1e70c880-a0b6-11e8-9137-6139d0664e39.png)

**Comment by KAlSi3O8** [comment]
You can change file name glass_pane.properties to glasspane.properties (delete '_') in -.jar\assets\minecraft\mcpatcher\ctm\default

**Comment by DanielAgostinho** [comment]
Thank you!

**Comment by sp614x** [comment]
Fixed in next beta2.

**Comment by sp614x** [comment]
Fixed in beta2.
