### ISSUE TITLE
[1.13 alpha] Crashes when starting game

### ISSUE THREAD

**Issue by suchdotaplayer** [sp614x/optifine#1662]
I get this when I try to open the game
"could not find or load main class net.minecraft.a.m"
exit code (1)
That's all. there's not a crash log about it
Any idea?

**Comment by Chrishunk** [comment]
I also have this problem if I can solve <3

**Comment by Chrishunk** [comment]
but what it seems to be is this error, being caused by the pirate launcher. maybe some launchers have already said updates to fix this bug. I just do not know which ones.

**Comment by suchdotaplayer** [comment]
Oh my secret! Yes, you are right. Maybe i'll have to buy minecraft but I can't afford it yet :(

**Comment by skmedix** [comment]
Duplicate of #1635

**Comment by suchdotaplayer** [comment]
SKMEDIX solve my problem, thank you so much dude, is there a way i can thank you?
