### ISSUE TITLE
Custom item textures not working (1.13)

### ISSUE THREAD

**Issue by JdaxCZ** [sp614x/optifine#1663]
Custom items don't work on 1.13 alpha8 - I have checked that the IDs are correct, works perfectly on previous versions.

**Comment by sp614x** [comment]
Numeric item IDs shouldn't be used anymore.
The CIT custom models are not working yet, the rest should be OK.

**Comment by Galaxy-Prism** [comment]
Is there anywhere I can find a tutorial for the new format?

**Comment by sp614x** [comment]
CIT is fixed in next beta9.
