### ISSUE TITLE
Repeater Base Texture

### ISSUE THREAD

**Issue by iamc24** [sp614x/optifine#1668]
When facing east or west, the top texture of the base of the repeaters are flipped.
[This link has pictures.](https://imgur.com/a/p5ba6nd)

**Comment by realjackasterisk** [comment]
This is a known issue with fast math. Disable it, then restart your game.

**Comment by JimStoneCraft** [comment]
Nothing to do with fast math, as on or off makes no difference.

This issue also affects the Comparator.

**Comment by realjackasterisk** [comment]
@JimStoneCraft Have you restarted your game after disabling it?

**Comment by JimStoneCraft** [comment]
You're correct, it would seem it displays correctly when it fast math is set to off but you have to restart the client for it to make a difference.

**Comment by realjackasterisk** [comment]
Er... yes, that's why I said you restart your game in my first post.

**Comment by sp614x** [comment]
OptiFine 1.13_HD_U_E3_alpha9
 - fixed Fast Math accuracy
