### ISSUE TITLE
Optifine cape login not working 

### ISSUE THREAD

**Issue by deldog** [sp614x/optifine#1669]
Hi,

    So recently I have migrated my minecraft email to a new one, as I no longer have access to my old one because yahoo had reset the password or it was hacked, I have no idea. Recently my password wouldn't be accepted even though it's the password I have been using for the past 3 years to login into minecraft, I could not reset it, and I logged into mojang.com with the same password and it had worked there. I decided to move emails from my old one because I no longer have access to it, and moved to this new one I'm emailing you on right now. 
    I had been changing my cape design around a lot and have been using the same login with my old email, the one I used to donate to you guys for an Optifine cape, and now when I log in with my new email/password on optifine.net it continues to say it is the wrong email or password, and because I no longer can access the old email (declanburke514@yahoo.com) I was wondering if I could get the donation email moved to this one (declanrb514@yahoo.com) So I can log in and continue to enjoy my optifine cape. 

Thank you for reading, 

Declan / mc user: deldog

**Comment by sp614x** [comment]
The donator email is the owner of the cape and it can't be updated for now.
