### ISSUE TITLE
Invisible Sheep - 1.13 Alpha8

### ISSUE THREAD

**Issue by OpenMind23** [sp614x/optifine#1671]
Now this one made me laugh. I created a new world and could hear the sheep and they even ate grass and created a dirt patch, but I could not see them. All audio of them was fine, could hear what they were doing and where they were. Reloaded the newly created world and all was corrected, they were visible. 

I also had that issue of lines on corner of random blocks, but fixed it by turning off fast math. Whether turning that off had something to do with the sheep, i'm not sure. 

BTW I am using Faithful mod (by xMrVizzy) for better textures, so it could be that. If anyone else has this "invisible animal" issue when either creating a new world or generally, let me know so I can rule out the Faithful texture mod. 

Thanks sp614x for continuing your awesome work with Optifine :)

**Comment by KingHorse2015** [comment]
Can confirm that I had on my server a invisible skeleton :), Now everything seems to be normal after the second time joining

**Comment by ZenIsBestWolf** [comment]
Main issue now located at #5016
