### ISSUE TITLE
Optifine (1.13 alpha8) crash

### ISSUE THREAD

**Issue by PWPC** [sp614x/optifine#1672]
![screenshot 2018-08-16 18-56-38](https://user-images.githubusercontent.com/42447193/44222988-93133800-a186-11e8-89fd-ffdd10c655e8.jpg)
 Can someone help me?
It only happens with optifine client.

**Comment by PWPC** [comment]
Freezing on the Mojang logo ;/

**Comment by sp614x** [comment]
Fixed in beta4.
