### ISSUE TITLE
Wood Acting Like Leaves

### ISSUE THREAD

**Issue by Garr0** [sp614x/optifine#1673]
The Wood In Games Like Dark Oak Planks, Jungle Wood Logs Seem To Move Like Leaves I've Tried Many Shader Packs And It Acts Like Leaves.

**Comment by ZigTag** [comment]
This is no issue with opti, this is a shader side issue, ask the shader devs instead
(minecraft changed almost all block names)

**Comment by sp614x** [comment]
This is a problem with the shader packs, they have to be updated for 1.13.
