### ISSUE TITLE
Random glitched textures [1.13]

### ISSUE THREAD

**Issue by BillyPlayz** [sp614x/optifine#1674]
Hi, so I was playing with my friend on his server and we came across something weird, I will let the screenshots show you.
![2018-08-17_04 08 02](https://user-images.githubusercontent.com/32024962/44246206-d399a280-a1d4-11e8-9c8a-0a25bd6e69b3.png)

So far it has been the sandstone with a weird glowing orange texture, and this nether rack that my friend took.

![2018-08-16_19 50 22](https://user-images.githubusercontent.com/32024962/44246230-f926ac00-a1d4-11e8-94fc-e1342dc7f752.png)

How do I disable this feature? I don't really want to have glowing orange blocks everywhere...

**Comment by Zefferis** [comment]
Bug was first posted with #1639 

A temporary solution was given by another user:
___
Turn off fast math and restart minecraft (optifine).
This is a temporary solution as the dev works out the problems, remember that this is still in alpha ^ ^

**Comment by hbffbh** [comment]
I got the nether-rack thing, and a similar thing with observers and levers, thanks for the fix.

**Comment by sp614x** [comment]
OptiFine 1.13_HD_U_E3_alpha9
 - fixed Fast Math accuracy
