### ISSUE TITLE
[1.13 Alpha8]  Custom animations not working

### ISSUE THREAD

**Issue by Norzeteus** [sp614x/optifine#1676]
I have a lot of animations in my texturepack and they worked fine in 1.12, now in 1.13 not a single one will do! Is there any change in the anim- folder? My path: assets/minecraft/mcpatcher/anim

![gui](https://user-images.githubusercontent.com/24456750/44274312-21002900-a242-11e8-84f3-a758586bfda9.png)

**Comment by Norzeteus** [comment]
Thx for  response; tried to rename the folder  mcpatcher to optifine with the result, that "nothing" works
anyway, no ctm, no skys, no random mobs.....Created a second folder named optifine and put  the "animfolder" in, didn`t work.... ; ( 
This resourcepack was created by me, you can have a look at it here:
[https://www.planetminecraft.com/member/norzeteus/](url)

**Comment by Norzeteus** [comment]
Thx for information...

**Comment by sp614x** [comment]
Are the source/target paths correct, warnings in game output (error log)?
In 1.13 some vanilla texture folders have been renamed

**Comment by Norzeteus** [comment]
@sp614x 
Now I tried the new optifine 1.13 pre beta2, with my updated, not released RP but animations won`t work, error log shows "skipped" all
animations and  "missing" some textures as redstone_lamp_on....
I´ll send you a PM to minecraftforum.net with a dwl.link for my pack for testing( also the emissive problem with animations)....

**Comment by sp614x** [comment]
You can PM me on the OptiFine discord server: https://discord.gg/tKxWtyf

**Comment by Norzeteus** [comment]
I just wanted to ask if the function for animations in the last optifine was already added, I'm trying the version beta6 but my animations still do not work ....

**Comment by sp614x** [comment]
This is the problem
```
[OptiFine] Texture animation: mcpatcher/anim/anvil.properties
[OptiFine] Skipped: mcpatcher/anim/anvil.properties, target texture not loaded from same resource pack
```

**Comment by sp614x** [comment]
Fixed in next beta9.
