### ISSUE TITLE
Crash with Optifine and TIS-3D Rift

### ISSUE THREAD

**Issue by CaptainKyros** [sp614x/optifine#1677]
[crash-2018-08-17_08.11.59-client.txt](https://github.com/sp614x/optifine/files/2297786/crash-2018-08-17_08.11.59-client.txt)
I get this crash only when Optifine 1.13 alpha is installed with Asie's Rift port of TIS-3D

**Comment by sp614x** [comment]
Fixed in next preview beta1.
