### ISSUE TITLE
[1.13] K and Y not showing

### ISSUE THREAD

**Issue by RagerGamer** [sp614x/optifine#1678]
So I'm not sure if this is a bug with my minecraft or optifine, but in my chat, I was doing ABC's because I noticed when typing a IP that Y was gone, as in blank so I had to check if it was any others. It was only K and Y that were not showing. 

This is a screenshot but snipped that I sent to my friend.
![image](https://user-images.githubusercontent.com/42478620/44284355-fb195b00-a226-11e8-838c-e30cd591f36f.png)

**Comment by Regnander** [comment]
Can you try this without OptiFine?

**Comment by RagerGamer** [comment]
I have had no issues when I play without optifine, I'm not sure what causes this. Its fixed itself on its own sometimes when I open my game, but it just reverted back to glitching but with different letters.

**Comment by KaiAF** [comment]
Closing this as they haven't responded to the last question. If you are still having any issues, let us know. Possibly was fixed already.
