### ISSUE TITLE
[1.13 alpha 8] High CPU usage when toggling certain options (occasional crashes)

### ISSUE THREAD

**Issue by AlexLXPG** [sp614x/optifine#1682]
The game freezes, and sometimes outright crash when toggling any one of these options:
Details -> Alternate Blocks
Quality -> Connected Textures
Quality -> Custom Entity Models
Quality -> Emissive Textures
Quality -> Custom Items

It wasn't as bad when I was using optifine 1.12

**Comment by Regnander** [comment]
This is an alpha version. You cannot expect it to run as a stabile release would.

**Comment by AlexLXPG** [comment]
Yeah I mean that's why I opened this issue, since how specific settings affects the cpu usage

**Comment by AlexLXPG** [comment]
Yes, and this does indeed happen in 1.13.1 beta 7, though
