### ISSUE TITLE
[1.13 alpha 8] CTM for logs not working correctly

### ISSUE THREAD

**Issue by JimStoneCraft** [sp614x/optifine#1685]
![ctm_logs_1](https://user-images.githubusercontent.com/42512910/44308321-d0eca800-a3a2-11e8-83d2-debb591329ce.jpg)
![ctm_logs_2](https://user-images.githubusercontent.com/42512910/44308322-d0eca800-a3a2-11e8-8a6a-6dcd0df147d5.jpg)
![ctm_logs_3](https://user-images.githubusercontent.com/42512910/44308323-d1853e80-a3a2-11e8-892a-47ce8bb24bd0.jpg)

CTM for all the logs doesn't work as expected, it works correctly in the Y axis but show the wrong textures when place in the X axis or Z axis.

**Comment by JimStoneCraft** [comment]
ctm/oak_log_end/oak_log_end.properties

# John Smith Legacy - JimStoneCraft - 2018
matchBlocks=minecraft:oak_log
faces=top bottom
tiles=0-46
method=ctm

**Comment by JimStoneCraft** [comment]
ctm/oak_log_end/oak_log_end.properties

matchBlocks=minecraft:oak_log
faces=top bottom
tiles=0-46
method=ctm

**Comment by sp614x** [comment]
Fixed in next beta3.

![image](https://user-images.githubusercontent.com/16635441/44724078-08113680-aad2-11e8-86ee-50620ec78941.png)
