### ISSUE TITLE
Weird streched out textures in 1.13 alpha

### ISSUE THREAD

**Issue by Gunseeker** [sp614x/optifine#1688]
Some textures are bugged and streched out. This makes terracotta look very weird because its all rotated, and makes pistons hard to use because you cannot see their direction. It also makes redstone repeaters look odd. Here are some photos
![2018-08-19_20 23 17](https://user-images.githubusercontent.com/42528699/44319694-4764c680-a3f2-11e8-910b-46051a80bfbc.png)
![2018-08-19_20 29 08](https://user-images.githubusercontent.com/42528699/44319700-4e8bd480-a3f2-11e8-8649-f9c21c03e62b.png)
![2018-08-19_20 35 29](https://user-images.githubusercontent.com/42528699/44319707-564b7900-a3f2-11e8-8168-6b118182a25f.png)

**Comment by realjackasterisk** [comment]
Please look at the other issues before posting.
#1634, #1639, #1651, #1653, #1655, #1674

**Comment by realjackasterisk** [comment]
Disable "Fast Math" in Performance Settings, then restart your game.

**Comment by Gunseeker** [comment]
oh, sorry to waste your time, I checked like 3 issues and didnt see it so I just thought it wasnt talked about. Thanks for the fix though!

**Comment by Regnander** [comment]
You can use the text field next to the dropdown menu called "Filters" (just clear all existing text and type for example "texture") to search for relevant issues so you don't have to read every single one.

![1](https://user-images.githubusercontent.com/17113053/44482639-38c41c80-a649-11e8-8698-bf29a61b2cd5.png)

Also, please close this issue if you don't have any other questions.

**Comment by sp614x** [comment]
OptiFine 1.13_HD_U_E3_alpha9
 - fixed Fast Math accuracy
