### ISSUE TITLE
World and player model upside down in  OptiFine 1.13 HD U E3 alpha8

### ISSUE THREAD

**Issue by Clobyy** [sp614x/optifine#1689]
When entering a world or a sever the game is upside down but the hot bar, chat, and setting are all right side up. 
![mc](https://user-images.githubusercontent.com/42547213/44349797-d5c95e80-a46b-11e8-8d85-210eda27bd1f.jpg)

**Comment by IljaNemo** [comment]
I have the same problem, it's sad. :(

**Comment by ZigTag** [comment]
turn off AA

**Comment by Nodws** [comment]
Remove DinnerBone tag

**Comment by YolineWu** [comment]
Same for me, I fix it with turning off antialiasing
https://github.com/sp614x/optifine/issues/1654

**Comment by Wasdspacemouse** [comment]
I managed to fix it by turning on Fast Render in the performance options.

**Comment by sp614x** [comment]
OptiFine 1.13_HD_U_E3_alpha9
 - fixed FXAA flipping screen vertically
