### ISSUE TITLE
Permission for my modpack

### ISSUE THREAD

**Issue by TechnicBear** [sp614x/optifine#1691]
I want to get permission, but i think you are going to say no.
This is the link on Technic (https://www.technicpack.net/modpack/dragoniary.1265482)
Plz accept, cause my modpack has many mods!

**Comment by realjackasterisk** [comment]
sp614x pretty much never gives permission for modpacks to use optifine

**Comment by ZigTag** [comment]
You should just put in the description of the pack to install optifine, then leave a link to the website

**Comment by TechnicBear** [comment]
Okay, but i still want to try...

**Comment by sp614x** [comment]
Sorry, no.
