### ISSUE TITLE
Seams in between blocks in 1.13 alpha

### ISSUE THREAD

**Issue by 23Link89** [sp614x/optifine#1695]
I'm getting seams between the blocks with the latest alpha build, I've tried adjusting all my settings from ingame to nvidia control panel, disabling things like AA and Anisotropic filtering. Nothing ended up working

**Comment by realjackasterisk** [comment]
This is a known issue.
Disable Fast Math in Performance Settings, then **restart your game.**

**Comment by 23Link89** [comment]
Thanks for the tip, it worked

**Comment by sp614x** [comment]
OptiFine 1.13_HD_U_E3_alpha9
 - fixed Fast Math accuracy
