### ISSUE TITLE
Biome Temperature Uniform

### ISSUE THREAD

**Issue by sonicether** [sp614x/optifine#1697]
I'd like to be able to assign biome temperature as a custom uniform.

We can stitch up our own representation of biome temperature with custom uniforms already, but in order to support modded biomes and for simplicity, I'd like to be able to assign the current biome's temperature directly as a uniform.

Perhaps this is already possible directly, as it was mentioned [here](https://github.com/sp614x/optifine/issues/924#issuecomment-333257460), but I cannot find the correct syntax.

Thank you for your time!

**Comment by sp614x** [comment]
The temperature is needed to detect if raining or snowing.
Currently the check in the code is:
```
if (biome.getTemperature(pos) >= 0.15F)
  renderRain()
else
  renderSnow()

```

**Comment by sp614x** [comment]
OptiFine 1.13.2_HD_U_E7_pre2
 - added custom uniform parameters: temperature, rainfall, biome_category, biome_precipitation
