### ISSUE TITLE
[1.13] CTM full/path/name.png gets confused by subfolders 

### ISSUE THREAD

**Issue by HanFox** [sp614x/optifine#1700]
As an example (lifted from PureBDcraft's ExOF addon):
`tiles=0 textures/block/_bdc/sandstone_tiles.png 2 3 textures/block/_bdc/sandstone_tiles.png`

However, in the log this error appears:
`[14:41:58] [main/ERROR]: Using missing texture, unable to load minecraft:textures/_bdc/sandstone_tiles.png : java.io.FileNotFoundException: minecraft:textures/_bdc/sandstone_tiles.png`

As you can see OptiFine seems to be ignoring the `block/` part of the path.

**Comment by sp614x** [comment]
Link to 1.13 ExOF?

**Comment by sp614x** [comment]
Fixed in next beta3.
