### ISSUE TITLE
When a zombie has a RandomMob skin, the skin number won't carry over when they turn into a Drowned.

### ISSUE THREAD

**Issue by MushirMickeyJoe** [sp614x/optifine#1704]
For example, I have two zombie variants:` zombie1.png` and `zombie2.png`, and two drowned variants: `dronwed1.png` and `drowned2.png`. But when the zombie who's assigned texture `zombie2.png` turns into a drowned (zombies turn into drowneds when they're underwater for a certain period of time), he won't necessarily turn into a drowned with the `drowned2.png` skin.

This is very inconsistent behaviour because, for example, wolves _do_  carry over their texture number when they change their skin (go hostile/are tamed).

**Comment by sp614x** [comment]
RandomMobs skins uses the mob unique id (UUID) when deciding which skin number to use. This id is persistent and unique to each mob. 
When a zombie turns into a drowned, the game kills the zombie and creates a new drowned mob. The new drowned mob has a different id and gets a new skin.
The problem can't be fixed (especially for multiplayer) without breaking the persistency of the skin numbers.
