### ISSUE TITLE
[1.13 + MultiMC] Dyed glass textures replaced with a pulsating orange

### ISSUE THREAD

**Issue by Ulisse54** [sp614x/optifine#1705]
Hello, I an running OptiFine 1.13 HD U E3 alpha8 from MultiMC. I noticed this weird bug with dyed glass.
How it looks:
![2018-08-24_16 56 41](https://user-images.githubusercontent.com/25094434/44570291-a8a8e300-a7c0-11e8-9872-f9aa739c0fe0.png)

All the orange bits are supposed to be dyed glass panes. Seemingly this bug occurs with every color. I tried to flick some options to ON or OFF including Fast Render, Fast Math, Smart Animations etc, I even reset all video settings to default, but it kept happening.  I however noticed that the "pulsation" of the orange color occurs with Smart Animations set to ON. _Bonus report: Smart animation doesn't seem to work properly at the moment, it disables ALL animations, including the ones of water that you're staring at from 2 blocks._

https://youtu.be/496kYJyF8ks

I am using the default texture pack, although it must be noted that I ran Minecraft from MultiMC, although I'm not sure how that could affect rendering. 

For the second part of the issue title, some of the textures are not rendered correctly.
![2018-08-24_16 59 03](https://user-images.githubusercontent.com/25094434/44570688-feca5600-a7c1-11e8-9f4b-8c03763208ed.png)
This would be a duplicate of [#1634](https://github.com/sp614x/optifine/issues/1634). Someone replied that it's a common issue with fast math, although I switched it to off and the textures were still glitched.

**Comment by Ulisse54** [comment]
Update: As you might have seen, I tested that on a multiplayer server. If anyone was wondering, it happens in singleplayer too. Just to resolve any doubt.

**Comment by Ulisse54** [comment]
Update: It was the connected textures, that's why defaults wouldn't fix it. Still, worthy to look into, I suppose.

**Comment by sp614x** [comment]
Is this still happening in OptiFine alpha 10?

**Comment by Ulisse54** [comment]
I can't find an alpha10 version in the previews on the official site, did you mean beta2? I am having trouble installing optifine on MultiMC so I tred alpha8 on the default launcher. Everything works fine in there. Connected textures aren't orange and the normal glass connects fine(normal glass doesn't connect apparently). I think it might be MultiMC's fault, as the installation process is different.

**Comment by peterix** [comment]
Looks like some sort of classpath issue to me. See the log:
https://paste.ee/p/1KQON

It can't find any of the textures bundled in the optifine jar, for whatever reason.

**Comment by sp614x** [comment]
The installer takes some files from 1.13.jar (class, png, etc) patches them and puts the result in `libraries/optifine/OptiFine/1.13_HD_U_E3_beta2/OptiFine-1.13_HD_U_E3_beta2.jar`
The jar is added in the JSON library classpath and loaded normally.

**Comment by sp614x** [comment]
1.13-OptiFine_HD_U_E3_beta2.json
```
{
  "id": "1.13-OptiFine_HD_U_E3_beta2",
  "inheritsFrom": "1.13",
  "time": "2018-08-28T11:17:02+02:00",
  "releaseTime": "2018-08-28T11:17:02+02:00",
  "type": "release",
  "libraries": [
    {
      "name": "optifine:OptiFine:1.13_HD_U_E3_beta2"
    },
    {
      "name": "net.minecraft:launchwrapper:1.12"
    }
  ],
  "mainClass": "net.minecraft.launchwrapper.Launch",
  "minimumLauncherVersion": "21",
  "arguments": {
    "game": [
      {
        "value": [
          "--tweakClass"
        ]
      },
      {
        "value": [
          "optifine.OptiFineTweaker"
        ]
      }
    ]
  }
}
```

**Comment by peterix** [comment]
That will never work. Please don't do this

**Comment by sp614x** [comment]
This is OK with the vanilla launcher.
Why wouldn't it work?

**Comment by peterix** [comment]
1. It will not work with forge or any of the other mod loaders in the future.
2. It will never work with MultiMC. I do not want installers integrating with it, ever.
3. As the developer on the vanilla launcher I can only tell you: Please don't do this. It will most likely break in the future.

**Comment by sp614x** [comment]
This is how the OptiFine installer has done it since 1.6 and it has always worked.
Also for Forge and other launchers. Can't see where the problem is.

**Comment by peterix** [comment]
The problem is that those files do not exist. They are nowhere to be found when you just take the jar and use it.

It could be a bug that you don't patch the non-class files when it's used as a tweaker?

In any case, this missing texture problem is new.

**Comment by sp614x** [comment]
When used as a tweaker (loaded by Forge), then the patching happens in memory as part of the class transformation.

**Comment by peterix** [comment]
Well, forge is not there yet, I tell people to add optifine as a tweaker, and there are missing texture errors all over the log (added to previous comment for reference).

So, there might be some issue?

**Comment by peterix** [comment]
Also for reference, this is the install process:
https://github.com/MultiMC/MultiMC5/wiki/MultiMC-and-OptiFine

It's definitely as smooth as it should be, it's very manual and error prone because of that. I am hoping for Forge to be there, ideally sooner than later.

**Comment by sp614x** [comment]
The patching is the same like 1.12 and it works there. 
Why would 1.13 behave differently?
The only launcher problems with 1.13 so far were caused by changed JSON format for arguments, profiles, etc. and they should only affect the vanilla launcher.

**Comment by peterix** [comment]
Well, I could be completely wrong about this of course :)

Anyway, this is what I get:
![image](https://user-images.githubusercontent.com/203326/44719155-b4e3b780-aac2-11e8-98dc-a6169d34a2aa.png)

**Comment by sp614x** [comment]
You can join the OF discord so this can be fixed faster: https://discord.gg/tKxWtyf

**Comment by sp614x** [comment]
Fixed, coming in next beta3.
