### ISSUE TITLE
Issues with shader option comments

### ISSUE THREAD

**Issue by BruceKnowsHow** [sp614x/optifine#171]
The shader option comments have a lot of debug info added to them that I don't think will benifit the general user, I've yet to use them even. They can also clutter up the comments and make them difficult to read. The only piece of information that I think would benifit the user is the default value, and even then the text coloring pretty much has that covered. 

[This](http://puu.sh/ptfRG/d5ffe8ed04.jpg) happens with all of my numeric options, because they're all defined in a global #include. Once again, I don't think this information even needs to be presented to the user.

[Some comments](https://puu.sh/ptgq1/f610632c10.png) are running out of space, not sure how to deal with this.

Emphasis! only aplies to the final comment line when emphasis sentences roll over to a newline ([pic](http://puu.sh/ptgFH/f9cdbc2f55.png))

**Comment by sp614x** [comment]
I can remove the "From" section, it is not relevant to end users.
The ID should probably stay as it can be used to find the option in the source.

**Comment by sp614x** [comment]
The lines ending with "!" are shown red, so when one long line is split in two only the second part gets the red color.

**Comment by BruceKnowsHow** [comment]
I've personally never used to ID, it can be found by looking in the lang file, however I can imagine certain situations where it would be useful.

Is it a deliberate choice to only highlight the final line of split sentences? It seems like a bug. Split sentences are also kind of hard to read, they might be more readable if they were indented like regular lines, but without the tack (-) in front of them.

**Comment by sp614x** [comment]
Maybe the tooltips should only show extended information when F3 + H is pressed (vanilla Advanced Item Tooltips)?

**Comment by BruceKnowsHow** [comment]
Yeah, that's a good idea.

**Comment by sp614x** [comment]
Added option Advanced Tooltips (vanilla F3+H)
Updated shader option tooltips to check for advanced tooltips. 
Updated preview D3 for 1.10.2.
