### ISSUE TITLE
Random Texturebug

### ISSUE THREAD

**Issue by Willibaldgamer** [sp614x/optifine#1711]
Hi 
My textures are very buggy like on the picture. 
![2018-08-25_18 45 44](https://user-images.githubusercontent.com/42421159/44620580-36ef9880-a897-11e8-954c-60ceed585e7b.png)
(fast Mathe disabled)
Any ideas? Pls help :)
Sorry for bad english

**Comment by Hax4Ever** [comment]
Have you tried disabling shaders?

**Comment by Willibaldgamer** [comment]
![2018-08-25_18 49 15](https://user-images.githubusercontent.com/42421159/44620606-951c7b80-a897-11e8-839e-e9632cc5fa22.png)

**Comment by Willibaldgamer** [comment]
Thanks for the fast reply
Yes without shaders no problem.
But this problem is with every shader.

**Comment by Hax4Ever** [comment]
For now, disable shaders, as they are not fully ready for use in 1.13.

**Comment by Willibaldgamer** [comment]
Ok

**Comment by sp614x** [comment]
Shader packs would have to be updated for 1.13 as the block IDs have changed.
This is not something that OptiFine could easily fix.
