### ISSUE TITLE
A little freshness for Optifine [Idea]

### ISSUE THREAD

**Issue by BinaryBreakFast** [sp614x/optifine#1714]
Hello, I would like to suggest an improvement that would do Optifine good.

Using Optifine for 2 years now, I'm getting tired of always having the same kind of capes ( Cape-Bannière) that can be generated via the Optifine Banner Generator.

I know that it is possible to get custom capes via Mod or Minecraft versions like LabyMod.

I think it would be nice if Optifine added an option on its capes system so we could upload our own capes.
This would undoubtedly attract more people to buy Optifine and it would make it possible to obtain a great diversification of the capes and to avoid continuing on the way of the current stagnation which Optifine undergoes.

A simple UPLOAD button with next cape.png that appears ( or the file name).
and that as soon as we click on OK, that upload our personalized cape.

Because Optifine is the most used Minecraft version for capes but it is running out because there are no real novelties that would bring a little freshness.
I hope that my idea will interest the Optifine team and that they will think of adding a small system like the one so that we don't get bored contemplating the same capes 5000 times.

Sincerely,

AeRogue / BinaryBreakfast

**Comment by realjackasterisk** [comment]
#1236, #578

**Comment by sp614x** [comment]
Not really possible without limits. It is going to be abused.
