### ISSUE TITLE
Issue Use Nvidia FXAA

### ISSUE THREAD

**Issue by Syncter** [sp614x/optifine#1716]
Resolution not same, between two picture below!
![screenshot_30](https://user-images.githubusercontent.com/42674453/44661638-69cf9300-aa35-11e8-9c73-2da0abbc396e.png)

**Comment by sp614x** [comment]
Do you mean that FXAA is softening the GUI font texture?

**Comment by sp614x** [comment]
The OptiFine FXAA doesn't affect the GUI fonts. (Video Setting -> Shaders -> Antialiasing)
If you enable the NVidia FXAA in the graphics driver settings, then the GUIs may be affected.
