### ISSUE TITLE
The game crashed whilst tesselating liquid in world

### ISSUE THREAD

**Issue by huntdogy** [sp614x/optifine#1717]
`The game crashed whilst tesselating liquid in world
Error: java.lang.IllegalArgumentException: Cannot get property bly{name=type, clazz=class bmg, values=[top, bottom, double]} as it does not exist in Block{minecraft:water}`

**Comment by realjackasterisk** [comment]
You need to post the full log, not just part of it.

**Comment by Tayfu** [comment]
There it is (i have the same issue) 
https://pastebin.com/pVXZwAhe

**Comment by curz46** [comment]
Output from Optifine prior to error: `[OptiFine] (Reflector) Field not present: bna.(type: class [I, index: 0)`

**Comment by RefrainS** [comment]
I have the same issue :(

**Comment by RefrainS** [comment]
https://pastebin.com/gFwFj8yt

**Comment by sp614x** [comment]
Fixed, coming in beta2.
