### ISSUE TITLE
Weird visual bug: Handheld items are disappearing while looking at nearby blocks/objects

### ISSUE THREAD

**Issue by RefrainS** [sp614x/optifine#1724]
If i turn "Fast Render" on, handheld objects disappear and JourneyMap isnt working properly. But if i try to turn it off, the crosshair starts to bug hard and distant objects are flicking. Is there any way to fix this?
1.12.2 HD_U_E2

**Comment by sp614x** [comment]
Fast Render may conflict with some mods and there is no way to fix it.
