### ISSUE TITLE
Some sounds not working in Optifine_1.13_HD_U_E3_beta4

### ISSUE THREAD

**Issue by ASFdirrt** [sp614x/optifine#1727]
Hi!
I played optifine in 1.13, beta4, i opened the game and found various messages saying something like: Missing sound event: minecraft:block.wool.break. I did not think that was important, so i played normally.
I discovered the missing sounds when i was about to make a bed in my survival world, i placed accidentally the wool blocks on the ground, but the blocks made no sound. In that moment i created a new world, with the purpose of testing the sounds.
There are some missing sounds that i found:
Underwater sounds
Beacon sound
Wool sounds
Conduit sound
Kelp sounds and sea grass sounds
Coral sounds
Note blocks.
How can i fix this?, i wait your reply.
PD: This also happened in previous betas.
Sorry, i don't speak english very well :<.

**Comment by sp614x** [comment]
Are you using the official launcher or a custom launcher?
Can you post the part of the log where it complains about the missing sounds?

**Comment by ASFdirrt** [comment]
I'm not using the official launcher, i'm using Shiginima launcher. 
     Here you have the log.
[El registro.txt](https://github.com/sp614x/optifine/files/2341962/El.registro.txt)

**Comment by ASFdirrt** [comment]
There's no solution, right?

**Comment by sp614x** [comment]
Custom launchers are not supported.
The warning "Missing sound for event" is coming from vanilla code.
OptiFine doesn't change anything in the sound handling.
