### ISSUE TITLE
Visual problem

### ISSUE THREAD

**Issue by EdwardTheGamer** [sp614x/optifine#1730]
Sometimes the sight is buggy, and the chunks do not load. The problem can be solved with F3 + T.
I was using Optifine 1.12.2 HD U E2.

![2018-08-29_20 39 30](https://user-images.githubusercontent.com/42244508/44847807-ef7d5980-ac54-11e8-8bf3-ff1b2104c581.png)
![2018-08-29_20 39 23](https://user-images.githubusercontent.com/42244508/44847812-ef7d5980-ac54-11e8-9a03-1b3b4e494c83.png)
![2018-08-29_20 39 25](https://user-images.githubusercontent.com/42244508/44847813-f015f000-ac54-11e8-8f52-af2cbb3892e4.png)
![2018-08-29_20 39 27](https://user-images.githubusercontent.com/42244508/44847814-f015f000-ac54-11e8-93f6-a5d038a18ba6.png)

**Comment by KaiAF** [comment]
If this is still an issue, create a new report. This is invalid now.
