### ISSUE TITLE
fr_fr.lang correction

### ISSUE THREAD

**Issue by SLDDL** [sp614x/optifine#1731]
fr_fr.lang Correction
[fr_fr.lang.zip](https://github.com/sp614x/optifine/files/2336844/fr_fr.lang.zip)

**Comment by sp614x** [comment]
Language updates should be submitted as pull requests.
@Calinou @SkytAsul 
https://github.com/sp614x/optifine/commits/master/OptiFineDoc/assets/minecraft/optifine/lang/fr_fr.lang
