### ISSUE TITLE
Letters keep getting invisible.

### ISSUE THREAD

**Issue by Tim901** [sp614x/optifine#1733]
From time to time, the letters in Chat, on signs and item names keep going invisible. Makes it pretty hard to play.

**Comment by Tim901** [comment]
jep

**Comment by Tim901** [comment]
I use the newest Optifine Version (Beta4) and the new minecraft textures that was updated by Welsknight (https://www.reddit.com/r/HermitCraft/comments/90e4du/for_those_of_you_asking_about_the_texture_pack/) and at first i can see all the letters, but they keep disappearing from time to time. Not all but "X" and "/" are common evils ^^.

**Comment by Lovelessduck48** [comment]
it happens when you load in
