### ISSUE TITLE
1.13 - Shaders custom noise texture does not work properly

### ISSUE THREAD

**Issue by zombye** [sp614x/optifine#1737]
I think the exact issue is that only one channel gets used, but I'm not entirely sure. May also be that noisetex always has the standard noise texture.

Either way, the most noticeable effect this has is that volumetric clouds in many shaders look very blocky, or have lots of seams, or similar.

**Comment by sp614x** [comment]
Is the custom noise texture not loaded or is the noise texture not correctly generated?
There may also be a problem with switched channels BGR instead of RGB.

**Comment by zombye** [comment]
After some further testing I've found that the custom noise texture does actually get loaded properly, but is using nearest interpolation for filering, rather than bilinear interpolation like it should, regardless of there being a .mcmeta file specifying it.

**Comment by sp614x** [comment]
Fixed in next beta6.
