### ISSUE TITLE
Suggestion: make it posssible to changetexturere of mushroom on mooshroom 

### ISSUE THREAD

**Issue by MrConfusioned** [sp614x/optifine#1744]

**Comment by sp614x** [comment]
The mooshroom back mushroom can be configured by adding the texture "assets/minecraft/textures/entity/cow/mushroom_red.png".
In 1.13.2_HD_U_E5 the texture was changed to "assets/minecraft/textures/entity/cow/red_mushroom.png" to reflect the 1.13 texture changes.
