### ISSUE TITLE
Suggestion: make it posssible to change texturere of mushroom on mooshroom 

### ISSUE THREAD

**Issue by MrConfusioned** [sp614x/optifine#1745]
Make it possible with random textures, transmobifier proved it was possible with named mobs

**Comment by sp614x** [comment]
The mooshroom back mushroom can be configured by adding the texture "assets/minecraft/textures/entity/cow/mushroom_red.png".
In 1.13.2_HD_U_E5 the texture was changed to "assets/minecraft/textures/entity/cow/red_mushroom.png" to reflect the 1.13 texture changes.
