### ISSUE TITLE
45' turned textures

### ISSUE THREAD

**Issue by RickWeerdex** [sp614x/optifine#1755]
Some textures, for example stairs and buttons are turned diagonal when you place them in a certain way.

OptiFine 1.13 Alpha8
![2018-08-24_14 30 56](https://user-images.githubusercontent.com/43009388/45106751-c9195b80-b137-11e8-88e0-174fe3bd448b.png)

**Comment by realjackasterisk** [comment]
dude, really? update your game, we're far past alpha8 now.

**Comment by sp614x** [comment]
Fixed in one of the beta versions.
