### ISSUE TITLE
Detects only 4:3 resolutions

### ISSUE THREAD

**Issue by freijon** [sp614x/optifine#176]
I have a UHD (3840x2160) display. When using shaders, my FPS drops to about 15. I usually play GPU intense games on 1920x1080. Unfortunately this is not possible with Optifine because it only suggests 4:3 resolutions which leaves me with a black border on the side. I tried to manually write 1920x1080 in the configuration file but my change is ignored and it falls back to 4:3. However, the full resolution of 3840x2160 works fine.

Using 1.10-OptiFine_HD_U_B6

**Comment by sp614x** [comment]
OptiFine shows only the screen modes which have the same color depth (bits per pixel) and refresh rate as the desktop mode. This is done in order to remove all duplicates.

**Comment by freijon** [comment]
I can't use my entire screen like this. Is there a workaround for my issue?

**Comment by sp614x** [comment]
Fixed Fullscreen Mode to show all avalable resolutions.
Changed the option Fullscreen Mode to a slider.
Coming in next preview B7 for 1.10.

**Comment by sp614x** [comment]
Preview B7 for 1.10 it out with bugfix.

**Comment by freijon** [comment]
Thanks man, that was quick! I'll test the preview and will give you feedback ASAP

**Comment by freijon** [comment]
Unfortunately it still only shows 4:3 resolutions and not those that fit my screen size :-( The resolution slider is definitely an improvement though.

**Comment by sp614x** [comment]
OptiFine shows all the resolutions that the graphics card driver is reporting.
It may be a driver or monitor problem.

**Comment by freijon** [comment]
I see... I don't have this issue with other games though.. Is there a workaround for me to force a specific resolution?

**Comment by sp614x** [comment]
Updated preview B7 for 1.10, can you check it again

**Comment by freijon** [comment]
I notice nothing different

**Comment by sp614x** [comment]
Is the issue still relevant when using latest version D2 for 1.10.2?

**Comment by freijon** [comment]
Yes, still the same issue. It doesn't detect 1920x1080 although for other
applications and in my system settings the resolution is available

**Comment by sp614x** [comment]
Here is a test version which prints all available modes: http://optifine.net/tmp/OptiFine_1.10.2_HD_U_D3_pre_FS.jar
Can you start it and post the error log?

**Comment by freijon** [comment]
Here you go:
http://pastebin.com/raw/H8eLBXPi

**Comment by sp614x** [comment]
This is the launcher log.
Post the game output after changing the resolution. It should show a list of all detected resolutions.

**Comment by freijon** [comment]
Where can I get the game output?

**Comment by sp614x** [comment]
For the vanilla launcher the error log is the tab "Game Output"
