### ISSUE TITLE
Mushrooms

### ISSUE THREAD

**Issue by snoggie1487** [sp614x/optifine#1762]
![image](https://user-images.githubusercontent.com/38010396/45237520-8b861100-b2a4-11e8-9717-2b3fb710a678.png)

Mushrooms create a bright spot in OptiFine 1.13.1 HD U E3 beta7

**Comment by realjackasterisk** [comment]
Um, this is vanilla behaviour. https://minecraft.gamepedia.com/Mushroom#Light_source

**Comment by Redd56** [comment]
gotta love the fact notch made mushrooms provide 1 level of light for some reason... imo the 2nd wierdest thing in the game next to the player camera being at the players feet and the entire world just being shifted down to compensate

**Comment by sp614x** [comment]
They are magical mushrooms growing in caves, so glowing comes naturally.
Otherwise this is vanilla behaviour.

**Comment by Redd56** [comment]
So thats why he added it.... Ive been wondering that for like 4 years XD 
Guess that explains it.
