### ISSUE TITLE
[Solved][1.13] [CTM] matchTiles:minecraft: furnace_front_on doesn't replace texture

### ISSUE THREAD

**Issue by eccentricdevotion** [sp614x/optifine#1768]
(Once again) I realise that this is still a preview and not all functions are tested, but I'm trying to replace the lit texture on a furnace using CTM:
```
matchTiles:minecraft:furnace_front_on
method=fixed
faces=sides
```
with no success (no errors/warnings shown in the launcher log when OptiFine loads).
Prior to 1.13 I was using:
```
blocks=minecraft:lit_furnace
```
to good effect.

![working artron furnace](https://eccentricdevotion.github.io/TARDIS/images/docs/artron_furnace.jpg)

Also affected is:
```
matchTiles=minecraft:redstone_lamp_on
```

**Comment by realjackasterisk** [comment]
Remove the `minecraft:` part.

**Comment by eccentricdevotion** [comment]
Makes no difference, and all my other properties files that use `minecraft:` work as they should...

**Comment by realjackasterisk** [comment]
Oh, just realized you have the ID's wrong.
`furnace_front_on` should be just `furnace`, and `redstone_lamp_on` should be `redstone_lamp`. Check the MC wiki for the correct block IDs in 1.13. https://minecraft.gamepedia.com/Minecraft_Wiki

To get your stuff working on only lit furnaces and lamps, you might need to use `metadata`. But from what I've heard, metadata has gotten all weird in 1.13, and honestly I don't know how it's supposed to work to begin with.

I can't tell you why the ones with `minecraft:` still work, either. From what I've seen and heard, it *shouldn't* work.

Afraid I can't help much further beyond that. I wish you luck on this.

**Comment by eccentricdevotion** [comment]
I think you are confusing `matchBlocks` with `matchTiles`...
`matchTiles` uses (from my understanding) the actual file name of the texture you are trying to replace - if you look at the default texture file names (I unzip the Minecraft client jar file, in this case 1.13.1) and then look at the file names eg: `assets/minecraft/textures/block/furnace_front_on.png` - there is no `furnace.png` in vanilla Minecraft.
Metadata no longer exists in 1.13.1 so cannot be used (and wouldn't work with a furnace anyway - see my original post for how it used to work in 1.12.x).
I have also tried using block data eg `matchBlocks:minecraft:furnace[lit=true]` but that doesn't work  (yet?) either.
Using `minecraft:` is perfectly legitimate way of specifying a block, item or tile - it just specifies the namespace to look for the object. If I wanted to retexture something from a mod I would use `modnamespace:a_cool_mod_block` and that should work too.

**Comment by realjackasterisk** [comment]
jesus, i keep coming back to this post to find even more stuff that I never read to begin with. sorry dude, i should've read this whole thing in detail.
