### ISSUE TITLE
CIT isn't work (Beta8)

### ISSUE THREAD

**Issue by OktayYeniTR** [sp614x/optifine#1783]
![](http://imgim.com/2018-09-11_091620.png)
![](http://imgim.com/6629incij6066846.png)

Pack:https://www.dropbox.com/s/v1cn19i68pi6i3f/test%20pack.zip

**Comment by sp614x** [comment]
CIT is fixed, coming in next beta.
The item names have been changed in 1.13, so resource packs have to be updated.
