### ISSUE TITLE
Teleporting player makes screen jitter

### ISSUE THREAD

**Issue by NOPEname** [sp614x/optifine#1785]
Teleporting a player every tick to create a cutscene (video) makes screen jitter.
Video showing the issue: https://youtu.be/eJOAIYUIF-k

**Comment by sp614x** [comment]
How is the teleport triggered (command block)?
Which command is used?

**Comment by NOPEname** [comment]
I'm using "/tp (facing)" triggered by functions.
So far I only tested "OptiFine 1.13.1 HD U E3 beta7"

**Comment by sp614x** [comment]
Tested with next beta9, using command
`/execute as @p at @p run tp ~0.01 ~0.005 ~0.01`
Everything is smooth, no jitter at all.

**Comment by NOPEname** [comment]
Looks like only this type of teleportation is causingthe issue:
`/execute as @e[tag=marker] at @s run tp @a ^ ^ ^7 facing entity @e[tag=marker,limit=1,sort=nearest]`
`/execute as @e[tag=marker] at @s run tp @s ~ ~ ~ ~0.01 ~`
Use an entity as a marker (tag) and run these commands every game tick. The command will teleport all players 7 blocks into the direction the entity is facing and make the players face the marker entity.
