### ISSUE TITLE
Sky bug (Pre2)

### ISSUE THREAD

**Issue by OktayYeniTR** [sp614x/optifine#1786]
![](http://imgim.com/2018-09-12_155259.png)

MY RENDER DISTANCE IS 2

**Comment by sp614x** [comment]
Resource pack, Shaders, VBOs?
Is this below or above the player?

**Comment by OktayYeniTR** [comment]
![gfd](https://user-images.githubusercontent.com/31184544/45492240-76adef80-b774-11e8-94f4-c72f56654e6b.PNG)
above player

**Comment by OktayYeniTR** [comment]
no shaders

**Comment by OktayYeniTR** [comment]
can u fix it?

**Comment by sp614x** [comment]
Fixed, coming in E5_pre1.
