### ISSUE TITLE
CIT Models: Custom display settings don't override the vanilla ones. (1.13.1 beta 9)

### ISSUE THREAD

**Issue by sixfootblue** [sp614x/optifine#1787]
This is for OptiFine 1.13.1 HD U E3 beta9.

When using CIT models, the display settings (first person, third person, gui, etc) in the custom model file don't get applied to the CIT item. The item's model will change, but it will instead use the display settings of the original item model.

Here's a sample resource pack to show the issue. (Rename a diamond sword to diamond spear). The new sword model should be twice as big as the vanilla one, but the size doesn't change. 
https://drive.google.com/open?id=16NrS4X4XUOiHwaB_ucbgPe-0ZOrcpCT3

**Comment by OktayYeniTR** [comment]
yea,its a problem :/

**Comment by InfiniteCorners** [comment]
I'm experiencing similar issues with custom models not being applied. In fact every item I have that uses a model is either a broken texture or just not displaying (in the case of the shields). Maybe custom models aren't supported yet?

![2018-09-13_21 50 49](https://user-images.githubusercontent.com/41232136/45525053-66f7d080-b79f-11e8-9b6c-11a14b76e5ee.png)

**Comment by OktayYeniTR** [comment]
confirmed in alpha 1

**Comment by D3monPixel** [comment]
What are you doing, Yeni? Alpha 1 is old. There are already much newer versions out. You can't just create new issues or comment about one issue that it existed before... We already had Alpha 8 over a month ago. And Alpha 1 was much older but I couldn't find a date to it

**Comment by OktayYeniTR** [comment]
Sorry it must be pre1

**Comment by sp614x** [comment]
Were CIT models working properly in 1.12.2?

**Comment by sixfootblue** [comment]
Yes they're working properly in 1.12.2.

**Comment by sp614x** [comment]
Fixed, coming in pre6.
