### ISSUE TITLE
Monochrome sky on F1

### ISSUE THREAD

**Issue by AnrDaemon** [sp614x/optifine#179]
MC 1.7.10
Optifine HD U D4
1. Optifine:
![javaw-20160619-092047 97-1](https://cloud.githubusercontent.com/assets/6532485/16175970/6cedb4f6-3609-11e6-9c25-216c6df522b1.png)
2. No Optifine:
![javaw-20160619-100707 76-1](https://cloud.githubusercontent.com/assets/6532485/16175969/6ceba684-3609-11e6-9353-f7ef6459c686.png)

There's no Fastcraft or CoFH tweaks, and removing JourneyMap doesn't change the outcome.

**Comment by sp614x** [comment]
What exactly is the problem?
Vanilla and OptiFine seem pretty similar.

**Comment by AnrDaemon** [comment]
Vanilla - blue sky.
Optifine - gray sky.
It is very pronounced, when you actually toggle the HUD. In Vanilla, the scene remains the same color.
In Optifine, the sky immediately turn gray.

**Comment by sp614x** [comment]
Is this a resource pack, shader pack, mod or something else?
Download link?

**Comment by AnrDaemon** [comment]
No shader pack, no resource pack.
Just plain old Optifine.
Hold a second, I'll make a better screenshot.

**Comment by AnrDaemon** [comment]
Trned up, it is a bit harder to reproduce, than I expected.
Removing Optifine does cause the effect to go away, but Optifine alone is not the cause for it, it seems.

**Comment by AnrDaemon** [comment]
And this is how it looks by comparison.
![javaw-20160619-230835 92-1](https://cloud.githubusercontent.com/assets/6532485/16179625/96c415f8-3673-11e6-8462-db2f15466712.png)

**Comment by AnrDaemon** [comment]
ProjectRed-Base >.<
The one I would the least expect…

**Comment by sp614x** [comment]
No idea what Project Red does to the OptiFine classes. 
It is possible that it has a custom class transformer which is designed to work on the vanilla classes and failes on the modified OptiFine classes.

**Comment by AnrDaemon** [comment]
I finnaly dug up the "Fast Render" option. Turning it off helped to get rid of this and a few other rendering glitches.
