### ISSUE TITLE
[1.13.1] Optif.beta9  Custom animations crash down the game

### ISSUE THREAD

**Issue by Norzeteus** [sp614x/optifine#1792]
So far my RP worked in 1.13.1 with version beta 8 (without custom animations) very good. 
Today I installed optifine beta 9 and the game crashed. If I remove the "anim-folder" , it works again.
Crashlog shows me: 
Process Monitor | fatal | Process crashed with exit code -1073741819
And the errorlog:
[hs_err_pid8932.log](https://github.com/sp614x/optifine/files/2383773/hs_err_pid8932.log)
Java is updated to vers. jre1.8.0_181, graphic driver vers. 399.24 nvidia
I am a bit overwhelmed with this situation and ask for help.....pls

**Comment by giammod** [comment]
Can confirm, applies to pre1 as well. java,drivers, computer up to date

**Comment by kikipunk** [comment]
I confirm, same problem on pre1

**Comment by sp614x** [comment]
Should be fixed in pre2.
