### ISSUE TITLE
[1.13] CIT models, display settings with spawner.

### ISSUE THREAD

**Issue by OktayYeniTR** [sp614x/optifine#1796]
Pack:https://www.dropbox.com/s/v1cn19i68pi6i3f/test%20pack.zip
![2018-09-15_00 25 32](https://user-images.githubusercontent.com/31184544/45575974-0ab7ae00-b87e-11e8-8c99-109854d096fa.png)

**Comment by OktayYeniTR** [comment]
isnt work :((((((((

**Comment by sp614x** [comment]
Resource pack link?

**Comment by OktayYeniTR** [comment]
https://www.dropbox.com/s/v1cn19i68pi6i3f/test%20pack.zip

**Comment by sp614x** [comment]
Rename folder "mcpatcher" to "optifine".
