### ISSUE TITLE
Most biomes ignored for biome specific textures in 1.13.1 (pre2)

### ISSUE THREAD

**Issue by giammod** [sp614x/optifine#1798]
As it says. I've tried  with and without the "minecraft:" prefix the log has a long list of biomes it can't find

> [16:16:14] [main/WARN]: [OptiFine] RandomEntities: Biome not found: forest_hills
> [16:16:14] [main/WARN]: [OptiFine] RandomEntities: Biome not found: swamp_hills
> [16:16:14] [main/WARN]: [OptiFine] RandomEntities: Biome not found: taiga_hills
> [16:16:14] [main/WARN]: [OptiFine] RandomEntities: Biome not found: frozen_ocean
> [16:16:14] [main/WARN]: [OptiFine] RandomEntities: Biome not found: frozen_river
> [16:16:14] [main/WARN]: [OptiFine] RandomEntities: Biome not found: ice_spikes
> [16:16:14] [main/WARN]: [OptiFine] RandomEntities: Biome not found: deep_frozen_ocean
> [16:16:14] [main/WARN]: [OptiFine] RandomEntities: Biome not found: snowy_taiga_mountains
> [16:16:14] [main/WARN]: [OptiFine] RandomEntities: Biome not found: snowy_tundra
> [16:16:14] [main/WARN]: [OptiFine] RandomEntities: Biome not found: snowy_mountains
> [16:16:14] [main/WARN]: [OptiFine] RandomEntities: Biome not found: snowy_beach
> [16:16:14] [main/WARN]: [OptiFine] RandomEntities: Biome not found: snowy_taiga
> [16:16:14] [main/WARN]: [OptiFine] RandomEntities: Biome not found: snowy_taiga_hills
> [16:16:14] [main/WARN]: [OptiFine] RandomEntities: Biome not found: desert_hills
> [16:16:14] [main/WARN]: [OptiFine] RandomEntities: Biome not found: mushroom_fields
> [16:16:14] [main/WARN]: [OptiFine] RandomEntities: Biome not found: mushroom_field_shore
> [16:16:14] [main/WARN]: [OptiFine] RandomEntities: Biome not found: frozen_river
> [16:16:14] [main/WARN]: [OptiFine] RandomEntities: Biome not found: frozen_ocean
> [16:16:14] [main/WARN]: [OptiFine] RandomEntities: Biome not found: warm_ocean
> [16:16:14] [main/WARN]: [OptiFine] RandomEntities: Biome not found: lukewarm_ocean
> [16:16:14] [main/WARN]: [OptiFine] RandomEntities: Biome not found: deep_cold_ocean
> [16:16:14] [main/WARN]: [OptiFine] RandomEntities: Biome not found: deep_frozen_ocean
> [16:16:14] [main/WARN]: [OptiFine] RandomEntities: Biome not found: deep_warm_ocean
> [16:16:14] [main/WARN]: [OptiFine] RandomEntities: Biome not found: deep_lukewarm_ocean
> [16:16:14] [main/WARN]: [OptiFine] RandomEntities: Biome not found: cold_ocean

Only biomes with old names seem to work (beach, plains, etc)

full list of biomes that should be there:
https://minecraft.gamepedia.com/Biome#Biome_IDs

**Comment by sp614x** [comment]
Fixed, coming in next pre3.
