### ISSUE TITLE
[1.12.2] crash in main menu (sevtech modpack)

### ISSUE THREAD

**Issue by TheSnowyChickens** [sp614x/optifine#1799]
Hi,
Im playing SevTech Ages (v3.0.8) and my FPS are slowly in the basement, so I tried to install Opti (1 tips side say that also), but my game is crashing at the main menu.
The game load normal and then the main menu pops up and after a short time (or trying to do something) it crashes.

Crash log: (there you also can find the versions from all mods and more) (this one is with opti E2)
[crash-2018-09-15_02.57.08-client.txt](https://github.com/sp614x/optifine/files/2385233/crash-2018-09-15_02.57.08-client.txt)

This one is with Opti E1:
[crash-2018-09-15_03.25.08-client.txt](https://github.com/sp614x/optifine/files/2385242/crash-2018-09-15_03.25.08-client.txt)

MC: 1.12.2
Optifine: tested with E3/2
Forge: 2707

Edit: 
- I updated BetterFont to the newest version, because I thought this is maybe a reason for this crash, but no.
- I removed BetterFoliage
- I removed FancyBlockParticles

**Comment by sp614x** [comment]
Some other mod is incorrectly patching the files changed by OptiFine.
Can't be fixed in OptiFine.

**Comment by TheSnowyChickens** [comment]
:( 
Okay
