### ISSUE TITLE
Water sides invisible next to upside-down slabs

### ISSUE THREAD

**Issue by Techy4198** [sp614x/optifine#181]
Appears to be related to some attempt to stop water rendering next to slabs, without considering upside-down slabs.

Github image attachment is broken so linked as Imgur album:
http://imgur.com/a/CTmEr

**Comment by sp614x** [comment]
Fixed, coming in preview B7 for 1.10.

**Comment by sp614x** [comment]
Preview B7 for 1.10 is out with a fix.
