### ISSUE TITLE
Intel graphics 0fps

### ISSUE THREAD

**Issue by adamwbb** [sp614x/optifine#1813]
seems on a Lenovo Idealpad with i5CPU intel integrated graphics optifine all versions 1.12.1+ including the 1.13.1 beta and prerelease versions have 0fps regardless of any settings in game. running vanilla minecraft without optifine results in 9-25FPS but when trying to load optifine (vanilla no mods) its just plummets and wont go above 0FPS

**Comment by adamwbb** [comment]
OS WIndows 10 build 1803
Java 8 181

**Comment by sp614x** [comment]
Video Settings -> Other -> Reset Video Settings?
Can you post the error log or game output?

**Comment by KaiAF** [comment]
No response from Author, closing issue.
