### ISSUE TITLE
Crash With Resource Pack Upon Loading 1.13.1 Optifine E3 Beta 9 & Pre 1

### ISSUE THREAD

**Issue by HunterBlackbrick** [sp614x/optifine#1816]
Everything worked perfectly in 1.13 (E3 Beta 4), and I just got around to updating yesterday to 1.13.1.

Without Optifine in 1.13.1, everything works fine; With Optifine but without my resource pack works fine; But the moment I switch to my pack it'll crash. Tested the "New Default" pack from Mojang, that one works fine. It's got to be some instance of collision with OF and my pack, but I can't pin down what.

As you'll see in the latest.log, there are a lot of outdated CIT and CTM files due to "The Flattening" nullifying metadata and such permanently, so I'm not sure if any of that is contributing.

Below are the error log and the latest.log, hopefully with both included something can be concluded.
[latest.log](https://github.com/sp614x/optifine/files/2399675/latest.log)
[hs_err_pid6772.log](https://github.com/sp614x/optifine/files/2399677/hs_err_pid6772.log)

**Comment by HunterBlackbrick** [comment]
#1802 This seems to be a similar if not identical issue, sorry if this ends up being a duplicate

**Comment by JanneSoon** [comment]
what is 1.3.1? do you mean 1.13.1?

**Comment by HunterBlackbrick** [comment]
> what is 1.3.1? do you mean 1.13.1?

I did mean 1.13.1, thank you for noticing I mistyped in my tiredness :P

**Comment by HunterBlackbrick** [comment]
Issue resolved in 1.13.1 OF E3 Pre 2
