### ISSUE TITLE
Only shows on 1/4 of screen

### ISSUE THREAD

**Issue by therealduckie** [sp614x/optifine#1817]
Am I the only one having this issue? (see image)
![cxmaflu](https://user-images.githubusercontent.com/887231/45849109-d705d980-bcfe-11e8-904e-a5948724eea0.jpg)

As you can see, it shows the server as 1/4 of the screen but all menus are full-screen. (same happens in single player)

Running:

macOS Mojave 10.14 (18A389)
OptiFine 1.13.1 HD U E3 pre2
on iMac (Retina 5K, 27-inch, 2017) with Radeon Pro 570 4GB

Have tried changing my resolution, clicked every single setting in "Shader Settings" and Minecraft's Video Settings. Tried it with and without a resource pack. Have even reinstalled the game from scratch. Nothing seems to fix it.

Yes, I know it's alpha software. Yes, I am aware it's early in development. Just hoping someone has a solution.

Thanks

**Comment by therealduckie** [comment]
Please note: Same thing happened on pre1

**Comment by sp614x** [comment]
Shaders -> FXAA or shader packs activated?
Video Settings ->Other -> Reset Video Settings?

**Comment by therealduckie** [comment]
Good points.

Shader Pack activated is Suldur's 1.13
Yes, I reset video settings and shader settings
No, I am using default screen resolution. Nothing custom.

**Comment by joeleduggan** [comment]
I had this issue as well and continue to have the problem with 1.13.1 pre4.
Doesn't matter what shaders I try. Same results.
Default screen res. "full screen".
Mid 2017, 27" iMac.

**Comment by samuelw3** [comment]
Thanks. I'll try that when I get some time.
It also only shows 1/4 it on my MBP that has an Intel Iris Plus Graphics 640 1536 MB.
MBP is running 10.14 /Java 8 Update 181
iMac is running 10.13.6 (Java v.?)

It is interesting that on Both iMac and MBP I can see the full screen (centered in the lower left corner). For example, left clicking a block in the center of the 1/4 screen is the target, not the target icon in the center of the entire screen.

But WOW it was so cool to see shaders on my mac. Super excited when I have time to troubleshoot.

**Comment by joeleduggan** [comment]
@sp614x I don't have any issues playing Minecraft full screen on the 5K iMac when not using Optifine.

**Comment by brianmcculloh** [comment]
I have a brand new Macbook Pro running Mojave and I have this exact same issue. Has anyone figured out how to fix it yet?

**Comment by ozals** [comment]
Have you tried unzipping the shader?

**Comment by ozals** [comment]
No, when you unzip the shader the order would be (using sildurs medium for example)
.minecraft\shaderpacks\Sildurs Vibrant Shaders v1.17 Medium\shaders\

**Comment by brianmcculloh** [comment]
Didn't work, but thanks for trying.
![screen shot 2018-10-09 at 7 39 21 pm](https://user-images.githubusercontent.com/22939642/46704928-31f26880-cbfb-11e8-8236-6d70746c9841.png)
<img width="1399" alt="screen shot 2018-10-09 at 7 40 07 pm" src="https://user-images.githubusercontent.com/22939642/46704929-31f26880-cbfb-11e8-8647-e0f7adf1c2d9.png">

**Comment by samuelw3** [comment]
ozals, thanks also... didn't work on my machines either.

**Comment by samuelw3** [comment]
> Probably related to the Retina 5K display, it may report half the resolution to Java programs.
> A similar vanilla problem: https://bugs.mojang.com/browse/MC-32327
> Also relevant: https://www.macworld.com/article/3024239/macs/how-to-adjust-your-mac-displays-resolution-settings.html

I set my resolution to the lowest possible before opening Minecraft/Optifine/shaders but still had the same issue of 1/4 screen on my iMac 5K and MBP. It was worth trying!

**Comment by sp614x** [comment]
Is pre7 working better?

**Comment by brianmcculloh** [comment]
Actually I just realized this is not fixed. It works on an external non-4k display which is what I was testing with before, but when I load it on my built-in retina laptop mac display it is still locked in the bottom corner of the screen.

**Comment by samuelw3** [comment]
It worked on my MBP is running 10.14 /Java 8 Update 181
Using preview_OptiFine_1.13.1_HD_U_E3_pre7.jar

I used two separate shader packs.

I've not yet tested it on my on iMac (Retina 5K, 27-inch, 2017) with Radeon Pro 570 4GB

**Comment by brianmcculloh** [comment]
I updated my version of Java and it appears to be working now. I tested my Macbook Pro 10.14 native display with Java 8 Update 181 using preview_OptiFine_1.13.1_HD_U_E3_pre7.jar and I am now getting full screen display.

**Comment by Muhammad-Fiqri** [comment]
Change The Render Quality to 1x

<img width="1365" height="767" alt="Image" src="https://github.com/user-attachments/assets/e7d7d07b-d417-46d1-b3bc-48911379366e" />

This what happen if Render Quality is 1.5x

<img width="1365" height="767" alt="Image" src="https://github.com/user-attachments/assets/95b3950c-c1d4-4664-9ae4-620de2d9eba1" />

**Comment by tejaswibteggihalli** [comment]
> Change The Render Quality to 1x
> 
> <img width="1365" height="767" alt="Image" src="https://github.com/user-attachments/assets/e7d7d07b-d417-46d1-b3bc-48911379366e" />
> 
> This what happen if Render Quality is 1.5x
> 
> <img width="1365" height="767" alt="Image" src="https://github.com/user-attachments/assets/95b3950c-c1d4-4664-9ae4-620de2d9eba1" />




Thank you!!! It's working!!! I had the same issue

**Comment by Muhammad-Fiqri** [comment]
You are welcome! @tejaswibteggihalli enjoy your game!
