### ISSUE TITLE
sea lantern ctm is weird 

### ISSUE THREAD

**Issue by MrConfusioned** [sp614x/optifine#1820]
it goes from orange to red to yellow back to orange
![2018-09-21_10 24 46](https://user-images.githubusercontent.com/42947430/45863876-1aa52580-bd89-11e8-89df-546e2d51192f.png)

**Comment by realjackasterisk** [comment]
what version of OptiFine are you using?

**Comment by giammod** [comment]
assuming he's using beta9 or pre1or2 the results would be the same

**Comment by sp614x** [comment]
Works for me with default resource pack:

![image](https://user-images.githubusercontent.com/16635441/45885596-2576af00-bdb7-11e8-9eca-52ad9eed1e85.png)
