### ISSUE TITLE
Ability to combine random entities and CEM inside the properties

### ISSUE THREAD

**Issue by D3construct** [sp614x/optifine#1826]
I think just a short explanation with an example of what I am imagining would be enough here.
Let's say you have a pack, which adds 3D modeled pigs which also have random textures for them but use a different format for the texture.  
If you put the new pig texture format into the original folder, the game would try to put that on the original pig model if you play without optifine or have entity models off. 
But if you put the new format into optifine/random/entity and not have random mobs on, then the pig model would search for the texture in the original folder and apply the old format to the model, which might look really wrong.
Adding something like `model=true` or so to the random entity part would link them both and only be working if both menu points are set to be on. Similarly the model could have some line to redirect into its own folder for a new texture so Non-Optifine users see the regular model and texture but Optifine users without random entities on in the options see the model with only one skin.

**Comment by OktayYeniTR** [comment]
i was suggested it but he said it's impossible

**Comment by OktayYeniTR** [comment]
oh, sorry i was suggest this for blocks (#1519)

**Comment by ewanhowell5195** [comment]
random entity models has ebeen added to optifine: https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/cem_model.txt#L206
