### ISSUE TITLE
Black water / No reflection issue with seus shader renewed

### ISSUE THREAD

**Issue by KampfschaFF** [sp614x/optifine#1828]
Get Black water / No reflection issue with seus shader renewed. Don't know optifine or the shader is the reason.

Clear Minecraft: 1.13.1 + Optifine E3_pre2

**Comment by realjackasterisk** [comment]
SEUS and pretty much every other shader pack needs to be updated for 1.13 due to The Flattening. This isn't an OptiFine issue.
