### ISSUE TITLE
ender io + optifine crash

### ISSUE THREAD

**Issue by jesserobbins98** [sp614x/optifine#1829]
i run minecraft boot all the way up as soon as i try to load a world it crashes https://pastebin.com/v5ZV8uPZ minecraft 1.12.2 optifine d1 i believe ender io: 5.0.33 endercore: 0.5.39 curse launcher (twitch) i take out optifine and it loads just fine

Edit: confirmed D1

**Comment by eihns** [comment]
Hmm i have latest optifine with latest stable enderio and it works..^^

**Comment by jesserobbins98** [comment]
sorry nevermind my problem is due to only being able to have 2 gigs of ram dedicated to minecraft
