### ISSUE TITLE
OpenGL Error 1286 & incorrect water appearance

### ISSUE THREAD

**Issue by JdeFalconr** [sp614x/optifine#1831]
Thanks in advance for the help.

Not sure if this is an issue with shaders (SEUS Renewed 1.0) or with Optifine but I'll post here anyway in hope of getting some help. This is also a cross-post from https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1280299-sonic-ethers-unbelievable-shaders-compatible-with?page=1504#c30547. Details and screenshot are there. In short, though, I'm seeing two issues that may or may not be related. First is a periodic OpenGL Error 1286 (Invalid framebuffer operation). Additionally I've found that water in my game appears grey and transparent while objects are either black or normally colored. The two screenshots in the linked forum post show what's happening. Additionally the images have F3 info on them which hopefully should help indicate my operating environment.

**Comment by skribe** [comment]
I'm getting the 1286 error with the internal shaders whenever I alt-tab away and back.

**Comment by chland** [comment]
The interesting thing is: a **few** of these errors are shown in the chat-window

`[10:00:00] [main/INFO]: [CHAT] [Shaders] Error: Failed creating framebuffer! (Status 36054)`

but literally hundreds of thousands of these here in the launcher.log:

```
[0928/100426:INFO:GameCallbacks.cpp(199)] game/cty (main) info OpenGL debug message, id=1286, source=API, type=ERROR, severity=HIGH, message=GL_INVALID_FRAMEBUFFER_OPERATION error generated. Operation is not valid because a bound framebuffer is not framebuffer complete.

[0928/100426:INFO:GameCallbacks.cpp(199)] game/net.optifine.shaders.SMCLog (main) error [Shaders] OpenGL error: 1286 (Invalid framebuffer operation), fbStatus: 36054 (Incomplete attachment), program: gbuffers_textured, drawBuffers: 56, at: setDrawBuffers

[0928/100426:INFO:GameCallbacks.cpp(199)] game/game () error FramebufferStatus 0x8CD6 at clear
  <log4j:Event logger="cty" timestamp="1538121866748" level="INFO" thread="main">
    <log4j:Message><![CDATA[OpenGL debug message, id=1286, source=API, type=ERROR, severity=HIGH, message=GL_INVALID_FRAMEBUFFER_OPERATION error generated. Operation is not valid because a bound framebuffer is not framebuffer complete.]]></log4j:Message>
  </log4j:Event>
```

and these here in the latest.log:

`[10:00:01] [main/INFO]: OpenGL debug message, id=1286, source=API, type=ERROR, severity=HIGH, message=GL_INVALID_FRAMEBUFFER_OPERATION error generated. Operation is not valid because a bound framebuffer is not framebuffer complete.`

Yesterday evening i tabbed out of Minecraft to do a few things and i ended up with 15 GB of log-files. Right now, Optifine is completely unusable for me when shaders (even the internal-ones) are enabled.

**Comment by chland** [comment]
@JdeFalconr @skribe - i noticed something. Are you guys using resource-packs?

If yes, try disabling them and see if the errors still show up. I changed up the loading order of my resource-packs and removed 2 (i'm using a bunch of small packs to add some things like grass-variations, etc.) and it seems like this somehow fixed the log-spam. I'm currently not getting any 1286-errors.

**Comment by JdeFalconr** [comment]
@chland thanks for the suggestion. I'm using the default resource pack.

**Comment by sp614x** [comment]
The OpenGL errors spamming the log is fixed in pre8.
The errors in pre8 come with a stack trace so there is a higher chance that their source can be fixed.

**Comment by JdeFalconr** [comment]
Thank you for the great work as always! What about the water appearance problem? This bug report diverged on the OpenGL errors but the water problem was where I really could use help.
