### ISSUE TITLE
Black lines between distant blocks.

### ISSUE THREAD

**Issue by RedstoneJohn** [sp614x/optifine#1836]
After updating from OptiFine 1.13.1 HD U E3 pre2 to OptiFine 1.13.1 HD U E3 pre3 , I noticed black lines between distant blocks and water losing it's blue color to a green-ish one (when you look at it from certain angles). It's not too important, but is annoying.
![2018-09-26_17 53 09](https://user-images.githubusercontent.com/43613021/46088587-55f28a80-c1b5-11e8-9e52-e2fe3b45f4b5.png)
![2018-09-26_17 53 55](https://user-images.githubusercontent.com/43613021/46088589-568b2100-c1b5-11e8-8ffa-e22b8f681de1.png)
![2018-09-26_17 53 58](https://user-images.githubusercontent.com/43613021/46088591-568b2100-c1b5-11e8-8dfa-0d7854dcde63.png)

**Comment by pajicadvance** [comment]
I had the exact same problem, but with way more black lines. Turning off both anisotropic filtering and antialiasing fixed the issue.

![2018-09-27_18 33 26](https://user-images.githubusercontent.com/32738446/46160858-1e9edf00-c284-11e8-8d64-5047bd74c3b6.png)

**Comment by RedstoneJohn** [comment]
Not for me. I turned both off and this trippy pattern appears.

![2018-09-28_15 41 32](https://user-images.githubusercontent.com/43613021/46209054-56b22a80-c335-11e8-9d5c-d7c0d931867b.png)

**Comment by sp614x** [comment]
Fixed, coming in next preview.
