### ISSUE TITLE
[1.13.1-pre3]crash when launch the game with Java 11 and 10

### ISSUE THREAD

**Issue by LTSMaker** [sp614x/optifine#1839]
I had a crash when i try to launch it with Java 11 and 10,but when I launch minecraft without optifine it is okay. the launcher`s log is here:
>[0927/204836:INFO:GameCallbacks.cpp(199)] launcher/launcher (main) info Exception in thread "main" 
> java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
> 	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

I use the offical launcher and Windows 10 Home.

**Comment by sp614x** [comment]
See here
https://github.com/sp614x/optifine/issues/1739#issuecomment-417884419

**Comment by sp614x** [comment]
Duplicate of #1739,

**Comment by sp614x** [comment]
Relevant https://github.com/sp614x/optifine/issues/1376#issuecomment-417884401

**Comment by sp614x** [comment]
Fixed installer to use launchwrapper-2.0
All new versions would use the new installer.
