### ISSUE TITLE
[1.13.1] Weather Off doesnt work

### ISSUE THREAD

**Issue by jdawson243** [sp614x/optifine#1840]
OS WIN10
GPU GTX 1070
16gb ram
i7-7700 cpu

Yesterday weather on and off option worked perfectly.
Then today suddenly it stopped working and rain started pouring.
at the time of the bug i was using 1.13.1 HD U E3 pre3 
and i downloaded the new pre4 ,but that didnt fix the problem

**Comment by sp614x** [comment]
Weather control works only in creative mode, single-player.

**Comment by jdawson243** [comment]
well nvm, im an idiot, though it was the rain option, thanks anyways :D
