### ISSUE TITLE
[1.13.1 pre4] Chests, beds, and water are completely dark regardless of surroundings (shaders enabled)

### ISSUE THREAD

**Issue by biggles5107** [sp614x/optifine#1841]
Running Minecraft 1.13.1 with Optifine HD Ultra E3 pre4 with shaders enabled. Shader pack is SEUS Renewed 1.0.0.

Had to enable normal map in the shader settings so that everything doesn't look completely dark. With normal map on, everything is lit up how it is supposed to be, with the exception of chests, beds, and water blocks. Those three block types (there may be more; just haven't discovered any as of yet) are completely dark regardless of the positions of nearby objects and light sources.

**Comment by cnelson711** [comment]
SEUS renewed 1.0.0 works with MC 12.x.  With 1.13 and the 'flattening' of the block ids from integers to strings, my bet is that SEUS renewed will need to be updated to fix the dark chests/beds, animation of leaves and grass, etc.

**Comment by sp614x** [comment]
SEUS Renewed is not updated to 1.13 yet.
The changes in 1.13 are significant and most shader packs need to be updated.

**Comment by Laserjones** [comment]
Interestingly, the old "SEUS v11 legacy" does produce correct water in MC 1.14, but the newer SEUS Renewed" does not. Really strange.

**Comment by sp614x** [comment]
Because SEUS Renewed check for water blocks in a very strange way which doesn't work in 1.14.
