### ISSUE TITLE
[1.13.1 pre4] Custom Screenshot doesn't work

### ISSUE THREAD

**Issue by SteveKunG** [sp614x/optifine#1842]
As title said, Also when enable Fast Render and press F2. The game lag for a second.
Related to : https://bugs.mojang.com/browse/MC-33383

**Comment by snappyapple632** [comment]
Can confirm, the screenshot will always be the default resolution, no matter which screenshot multiplier is set.

**Comment by sp614x** [comment]
Should be fixed in latest release.
