### ISSUE TITLE
1.13-1.13.2 U E4: Nether Shaders Applying in Over-world, and Vice-versa

### ISSUE THREAD

**Issue by rqnd0m** [sp614x/optifine#1844]
When you log out of a server or singleplayer world in the nether, and join another server or singleplayer world in the over-world, the nether visuals don't change, and you get something like this. This also happens when you log out in the over-world and join a world in the nether. A shader reload fixes this.
![2018-09-29_00 01 24](https://user-images.githubusercontent.com/43692455/46240956-3d34d100-c37d-11e8-9ba2-6690ca3fd4d5.png) This is what it should look like, after a shader reload: 
![2018-09-29_00 01 31](https://user-images.githubusercontent.com/43692455/46240969-563d8200-c37d-11e8-8cea-68465d813087.png)

**Comment by sp614x** [comment]
Fixed, coming in next preview.
