### ISSUE TITLE
[Suggestion] Custom ambient light colors

### ISSUE THREAD

**Issue by realjackasterisk** [sp614x/optifine#1847]
Quick disclaimer: As usual, I don't know anything about how shaders work internally, so I don't know how realistically possible this is.

Ambient lighting in Minecraft is pretty dull. It's just basic greyscale shading.
![image](https://user-images.githubusercontent.com/31686191/46253381-4d0ced80-c42f-11e8-9cc6-d4f2519083d8.png)

What if we were able to change this?
![image](https://user-images.githubusercontent.com/31686191/46253398-bc82dd00-c42f-11e8-9131-936b3fb81f20.png)
(my terrible mockup)

This can be done using shaderpacks, but having the option to change this via resource packs as well would be much nicer. It's a fairly simple effect, and it would much further improve the look of resource packs that utilize OptiFine.

![image](https://user-images.githubusercontent.com/31686191/46253419-4632aa80-c430-11e8-89c5-14b5e1efa1bf.png)
![image](https://user-images.githubusercontent.com/31686191/46253420-492d9b00-c430-11e8-965a-510afd60e6e6.png)
These last two images are examples made by @CaptTatsu on the Discord server. (normal on left, colored on right)
Relevant code:
```glsl
color.rgb *= vanillaLighting * mix(ambientColor, vec3(1.0), vanillaLighting * vanillaLighting);
```

The color for this shading should be able to change depending on the in-game time of day, weather, and world/dimension. I'd also suggest light level, to adjust when inside caves or buildings.

Perhaps this could be adjusted in a similar way to custom lightmaps?

**Comment by snappyapple632** [comment]
So basically [changing color temperature](https://en.wikipedia.org/wiki/Color_temperature)? Some shaders are already able to change color temperature. Perhaps this could be added to OptiFine's internal shader?

**Comment by sp614x** [comment]
This should be possible with lightmaps.

**Comment by Hax4Ever** [comment]
It isn't though?

**Comment by sp614x** [comment]
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/custom_lightmaps.txt

**Comment by Hax4Ever** [comment]
This is a suggestion about the shading that is applied to the side of blocks (that is disabled when you turn off "old lighting" in shaders)

**Comment by sp614x** [comment]
The fake lighting (shading on the side of blocks) is only a brightness (0 to 1). It doesn't have a color.
The color is controlled by the lightmap, depending on:
- time of day and light level (for sky light) 
- block light level and torch flicker (for block light)

The lightmap is the reason why the torch light is warm (yellow) and the sky light is cold (blue). 
With a custom lightmap they could be reversed or made red/green:
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/custom_lightmaps.txt
