### ISSUE TITLE
[Suggestion] OptiFine Cape Donators should be able to have Elytra skins too

### ISSUE THREAD

**Issue by joshi77** [sp614x/optifine#1848]
### Hello OptiFine Developer or let's better say, sp614x also hello to all the other readers.

I want to suggest a feature where Cape Donators should also be able to modify their Elytra wings using the default OF or the banner.

**People with Minecon Capes get those Elytras:**

![Eyltra Capes](https://d1u5p3l4wpay3k.cloudfront.net/minecraft_de_gamepedia/c/ce/Elytren_jeb_reddit.jpg?version=1ea0d23b5214b1b6972cec1b058a590a)

Could we get capes too? I can help you too with the design or something or we all could submit something on this GitHub.

jeb_ once said that he might is going to add something where everyone can personalize their Elytras, but since we can't atm and we don't want to conflict the original capes, please add something where we can modify our elytra's using the banner editors or the default layout please!

**Comment by Regnander** [comment]
#241

**Comment by k9lego** [comment]
Maybe it could reskin the Elytra if you have one on, and hide your cape while you have the Elytra equipped.

**Comment by Regnander** [comment]
>[...] hide your cape while you have the Elytra equipped.

The cape is hidden by default in vanilla Minecraft when you equip an elytra.

**Comment by joshi77** [comment]
So basically this is what I got now, not sure what method got used when doing the upside down shading, where the down part enlights up.

![OptiFine Cape design](https://i.imgur.com/5v4tXcB.png)

Doing letters on Elytras is okay, but the other Elytra side will reflect it, like a mirror so I had to stack them up together otherwise I would get the word, FOOF when players are basically not moving, which I thought that would be bad.

Now....

Coding this, might be hard if you do it with custom banners, since players might don't want something rectangular that instantly flys, so I'm gonna search around the internet for templates where I only use the color, black and white containing grey. Like that you can modify the RGB parts, maybe I just decide one color.

**Comment by joshi77** [comment]
We could also use this skin, but the user there https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/skins/2627315-ender-wings-elytra-skin-1-9-re-skin says that it's under copyright or something.

![](https://i.imgur.com/DSC50aB.png)

But this is how the Elytra skin would look like, and if there would be RGB settings that you can choose from, to modify the purple part, then we already have one elytra skin people can choose and yeah basically change the color.

Here's the skin, https://i.imgur.com/Tdt3PoV.png

Or some of those

https://imgur.com/a/sI5cv
https://minecraft.novaskin.me/skin/924403075/Mechanic-Crimson-Dragon-Elytra-Wings

or those neon ones http://mcpedl.com/paradiscals-elytra-wings-pack/ which nearly look like some lava

maybe any of these
https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/resource-packs/2632556-aidenr0s-elytra-textures-free-elytra-textures-for


or like I said with the banner website, but you should be able to choose a shape, otherwise you have rectangular skins.


They should not conflict the Minecon capes ofc.

**Comment by Regnander** [comment]
Here is a concept of my idea for how a default OptiFine cape would look on an elytra, which will only work if we get a way to have a separate texture for each side. I tried to place O and F in the middle vertically so they are split between the wings, but it didn't look that great IMO.

![a](https://user-images.githubusercontent.com/17113053/46371315-4e852280-c688-11e8-900b-c277029b8f48.png)

>or like I said with the banner website, but you should be able to choose a shape, otherwise you have rectangular skins.

True, but how many shapes should you be able to choose from? I believe that the best way is to have two options (rectangular or default shape) to keep it simple and user-friendly for the users and perhaps an option to disable mirrored texture for other wing.

Not only that, some players may not want a cape texture on their elytra and prefer the default texture. But this could be solved by adding an in-game option to disable this, like the customization setting where you can disable cape and certain skin parts.

> maybe any of these
> https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/resource-packs/2632556-aidenr0s-elytra-textures-free-elytra-textures-for

Haha, my favorite is "Monilytra".

**Comment by Regnander** [comment]
> wait how did you make this texture? Doesn't it mirror by default?

I made two resource packs with different elytra textures, one with "O" and another with "F", then I took two screenshots of each elytra texture and edited them together. 

>Also from where did you get that shading? or did you use photoshop and applied that shading?

Nope, I've just disabled smooth lightning. I generally use Fast graphics since I'm on a laptop.

**Comment by joshi77** [comment]
> > wait how did you make this texture? Doesn't it mirror by default?
> 
> I made two resource packs with different elytra textures, one with "O" and another with "F", then I took two screenshots of each elytra texture and edited them together.
> 
> > Also from where did you get that shading? or did you use photoshop and applied that shading?
> 
> Nope, I've just disabled smooth lightning. I generally use Fast graphics since I'm on a laptop.

so you made an Elytra with O O and another with F F changed both and made photoshop magic? So that elytra never existed :o

**Comment by Regnander** [comment]
(Strange, I thought I replied to this two days ago...)

>so you made an Elytra with O O and another with F F changed both and made photoshop magic? So that elytra never existed :o

Yes, that's right. Sorry to disappoint you. :-(

**Comment by Hax4Ever** [comment]
> (Strange, I thought I replied to this two days ago...)
> 
> > so you made an Elytra with O O and another with F F changed both and made photoshop magic? So that elytra never existed :o
> 
> Yes, that's right. Sorry to disappoint you. :-(

You guys could try making a custom elytra model to use a different texture for each wing, I know that's possible.

**Comment by joshi77** [comment]
> > (Strange, I thought I replied to this two days ago...)
> > > so you made an Elytra with O O and another with F F changed both and made photoshop magic? So that elytra never existed :o
> > 
> > 
> > Yes, that's right. Sorry to disappoint you. :-(
> 
> You guys could try making a custom elytra model to use a different texture for each wing, I know that's possible.

I'm pretty sure we try to keep it original.

**Comment by Regnander** [comment]
> > You guys could try making a custom elytra model to use a different texture for each wing, I know that's possible.
> 
> I'm pretty sure we try to keep it original??

Yes, we want to keep the original model but being able to have a cape texture / custom texture for the elytra.

**Comment by joshi77** [comment]
> > > You guys could try making a custom elytra model to use a different texture for each wing, I know that's possible.
> > 
> > 
> > I'm pretty sure we try to keep it original??
> 
> Yes, we want to keep the original model but being able to have a cape texture / custom texture for the elytra.

I asked sp614x and he said, that he also want's to maybe plan a custom model.

**Comment by sp614x** [comment]
Current design:

![grafik](https://user-images.githubusercontent.com/16635441/46896425-e3e89980-ce74-11e8-90cb-e9bea5e83984.png)

![grafik](https://user-images.githubusercontent.com/16635441/46896441-f2cf4c00-ce74-11e8-9295-ff27f0719103.png)

**Comment by sp614x** [comment]
Banner designs would be similar

Cape
![grafik](https://user-images.githubusercontent.com/16635441/46896976-e5679100-ce77-11e8-84a5-b2b0d6d4d812.png)

Elytra
![grafik](https://user-images.githubusercontent.com/16635441/46896983-f3b5ad00-ce77-11e8-9bd8-34cb5acedc6c.png)

![grafik](https://user-images.githubusercontent.com/16635441/46897160-041a5780-ce79-11e8-8be9-511a4a97daaa.png)

**Comment by joshi77** [comment]
> Banner designs would be similar
> 
> Cape
> ![grafik](https://user-images.githubusercontent.com/16635441/46896976-e5679100-ce77-11e8-84a5-b2b0d6d4d812.png)
> 
> Elytra
> ![grafik](https://user-images.githubusercontent.com/16635441/46896983-f3b5ad00-ce77-11e8-9bd8-34cb5acedc6c.png)
> 
> ![grafik](https://user-images.githubusercontent.com/16635441/46897160-041a5780-ce79-11e8-8be9-511a4a97daaa.png)

Did you change the elytra texture or is that already the prototype of the system?

**Comment by sp614x** [comment]
Support for eltra capes is added in E3 for 1.13.1, but the website is not updated to activate the elytra yet.

**Comment by Marfjeh** [comment]
Any updates on this still?

**Comment by sp614x** [comment]
Coming soon

**Comment by wh0oo** [comment]
Cannot wait for this, I would donate again!

**Comment by joshi77** [comment]
fix login system soon too :) :)

**Comment by wh0oo** [comment]
Up up up!!

**Comment by sp614x** [comment]
The OptiFine capes are updated to include elytra.
