### ISSUE TITLE
[1.12.2] E2 ULTRA [1.13/1.13.1] BETA 2 BUG [DEBUG SCREEN/COLOUR MAP]

### ISSUE THREAD

**Issue by Kirill1173** [sp614x/optifine#1850]
In the f3 debug screen vital information is missing such as 
xyz coordinates
biome name
light level
local difficulty
along with chunk , block looking at block state and many others
please see the return of this information to both 1.12.2 and 1.13 optifine versions
This is extremely useful information.. that is present in vanilla minecraft.. Do fix 

Along with this the colour map is broken fully in 1.13 beta optifines..
the debug information is broken for E2 1.12.2 Optifine and higher and all 1.13/1.13.1 beta /alpha optifine versions

**Comment by realjackasterisk** [comment]
I don't have this issue on *any* version of OptiFine.... Dumb question, but just to be sure, are you sure you aren't confusing the debug menu with "Show FPS"? Can you post a screenshot of this bugged debug menu?

**Comment by Kirill1173** [comment]
![2018-10-01_18 49 45](https://user-images.githubusercontent.com/43733383/46320154-d76d6280-c591-11e8-969d-f811291f06e7.png)

**Comment by Kirill1173** [comment]
As you can see multiple vital and useful pieces of information is missing from the F3 Debug screen
 such as : block looking at 
               Block state
               XYZ COORDs
               Light level
               Local Difficulty
               Time and much others
please see the return of these information

**Comment by Kirill1173** [comment]
I've checked ...for some reason it isn't off.. and it isn't showing the stuff

**Comment by sp614x** [comment]
The is the Reduced Debug Info.
The server can force it on the players, for example on an adventure maps where the coordinates could be used to cheat.
