### ISSUE TITLE
CTM not initializing properly

### ISSUE THREAD

**Issue by Stevecurious** [sp614x/optifine#1851]
When Minecraft is started with a CTM supporting resource pack, when it comes to CTM blocks, they aren't properly initialized and recquire either F3+T or to reselect the pack. So when I join a server, the pack is right on, but CTM doesn't work from the beginning.

**Comment by sp614x** [comment]
Minimal resource pack to reproduce the problem?

**Comment by Stevecurious** [comment]
I found out what the problem is: if you don't define matchBlocks=<name> within the .properties file, but just name the file like the block, it needs a refresh. IF you put the matchBlocks=<name> thing in, it does work properly and from the beginning. Not sure if this needs fixing then anymore xD

**Comment by sp614x** [comment]
Fixed, coming in pre6.
