### ISSUE TITLE
Fire Not Animated

### ISSUE THREAD

**Issue by CreativeNorb** [sp614x/optifine#1853]
Since installing Pre 3 a few days ago and even after installing Pre 4 today, I have had no animated fire no matter what the settings are. Everything else that's supposed to animate does, just not fire.

MC 1.13.1 Java on Windows 10.

This is my first issue submission, so if you need additional info I'll be happy to provide it.

**Comment by CreativeNorb** [comment]
I turned off all the packs and restarted so that only Optifine was active. No change, still no fire animation.

**Comment by sp614x** [comment]
Animations -> All ON ?
Performance -> Smart Animations ?

**Comment by sp614x** [comment]
Should be working by now.
