### ISSUE TITLE
Flipping Gbuffer writes

### ISSUE THREAD

**Issue by dotModded** [sp614x/optifine#1854]
I'd like to have a setting for flipping certain types of geometry into separate A and B buffers explicitly. Being able to have translucents in buffer A and solids in buffer B would be extremely useful for packing both sets of information separately to be used staggered in the next programs. This allows for 2x the gbuffer output capacity allowing for not only more efficient data packing, but allowing more data with little to no extra footprint.

**Comment by dotModded** [comment]
Little update on a visual of the idea I'm trying to accomplish https://docs.google.com/spreadsheets/d/1YPC1Py8-jltf_ayQ64_pXHN5B7cabFqvyiHFKrvd6fo/edit?usp=sharing

**Comment by McHox** [comment]
need this asap

> literally unplayable without

**Comment by Coolbro458** [comment]
+1 Need this ASAP.

**Comment by soulshot96** [comment]
Seriously need this.

**Comment by ozals** [comment]
can we please get this

**Comment by sp614x** [comment]
Currently there is no buffer flip in gbuffers stages, this has to be added.

**Comment by sp614x** [comment]
Got it working more or less, but currently it has problems as the B buffers are not cleared.
Tested terrain render to A, water render to B, composite read A (flip), composite1 read B.

**Comment by sp614x** [comment]
@dotModded also needs a copy from A to B before water program
this can be done with a simple deferred program

An option to disable `deferred_last` could be added so the A -> B copy overhead is minimal
then something like this can be added to select A/B
```
read.gbuffers_water.colortex1=B
```
it could also be extended for any composite program to override the automatic buffer flip
```
read.composite1.colortex5=B
write.composite1.colortex5=A
```

**Comment by sp614x** [comment]
Next preview should have custom buffer flips.

**Comment by sp614x** [comment]
OptiFine 1.13.2_HD_U_E5_pre2
 - removed shaders programs deferred/composite_last, added deferred/composite_pre
 - reorganized shaders buffer flipping

https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.txt#L33
