### ISSUE TITLE
[Suggestion] Disable OpenGL-errors in log-files / Limit amount of errors logged

### ISSUE THREAD

**Issue by chland** [sp614x/optifine#1860]
Right now, there is a button in the options which allows us to disable that OpenGL-errors show up in the chat-window. The problem is, that there isn't a setting like this for the error-logs (launcher_log.txt and latest.log).

Right now, I've got the problem that even though Optifine seems to be running fine, I get hundreds of thousands of error-messages in the log-files (see: https://github.com/sp614x/optifine/issues/1831) until my disk runs out of space.

While it would of course be the best solution if those errors wouldn't happen at all, I would really love to see some kind of switch which allows me to disable the error-logging of OpenGL-errors completely. Or probably a better solution would be if Optifine would count the number of errors it writes to the log-file and would simply stop after reaching a certain threshold (lets say: after 5000 errors, it could just write one final entry saying something along the lines of "Optifine has encountered too many errors, logging of any additional errors has been stopped.") to prevent filling up the hard-disk.

**Comment by sp614x** [comment]
This was fixed in one of the releases.
The opengl errors are rate limited and will log something like "Skipping 148 errors" when there are too many.
