### ISSUE TITLE
Add option to toggle chat background

### ISSUE THREAD

**Issue by Technerder** [sp614x/optifine#1861]
Add an option within the video settings menu to disable the chat background rendering line of code in GuiNewChat line 98 which calls:

drawRect(var15,` var16 - 9, var15 + var8 + 4, var16, var14 / 2 << 24);`

**Comment by sp614x** [comment]
Another option would be background per chat line (as long as the line) to keep the text visible.

**Comment by Technerder** [comment]
The toggle could extend to have 3 states:

 - Full background
 - No background
 - Surround text

**Comment by Regnander** [comment]
#1379 is identical to this issue

**Comment by sp614x** [comment]
Fixed, coming in next preview.

**Comment by Technerder** [comment]
Will this include the option to completely remove the chat background?

**Comment by sp614x** [comment]
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/assets/minecraft/optifine/lang/en_us.lang#L725

**Comment by Technerder** [comment]
Last question, will this be added to the previous version of minecraft as well (Mainly 1.7.10 and 1.8)?
