### ISSUE TITLE
Make it possible to change emitting light color separately for each specific block?

### ISSUE THREAD

**Issue by Resuz** [sp614x/optifine#1863]
I have seen that its possible to change light color for Torchlight and Blocklight. But it seems its not possible to change it separately for each light-emitting block. Would be nice if you make it possible to do so.
This would basically replace mods like ColoredLightsCore, Albedo (which are unstable, incompatible with Optifine shaders, and have serious FPS drop).

Sorry for my English.

**Comment by Resuz** [comment]
(So we could have more than 2 colors of light at the same time)

**Comment by sp614x** [comment]
This would require a significant rewrite of the lighting system.
Not in the scope of OptiFine.
