### ISSUE TITLE
Model mapping 

### ISSUE THREAD

**Issue by Triliton** [sp614x/optifine#1864]
Custom item textures  custom models are not working (mc 1.13)  (iand for the entities ai need to know is how mojang managed to set up their models as no matter how you turn the model etc the mapping will never line up how it does in default.  Mc 1.12 and 1.13

here is the setup default minecraft uses you can see the behind and the front of the pig are all oriented horizontally while the rest of the body is vertical https://i.imgur.com/0J7XgLn.png the problem is there is currently no way to arrange those textures to apply on the model properly as long as we are not able to mirror at least one of the uv mapping areas which you can see in the example here  https://i.imgur.com/Zgdbpjy.gifv. so question here is, is there really no way to mirror the textures/how has mojang done it in that case as i cant even begin to replicate the uv mapping mojang has done.

cit custom itemmodels per renamed item doesnt work anymore (it worked in the version before) https://i.imgur.com/dikRGHK.png  all i did was replace the id with the itemnames since item ids have been removed and they were not showing up at all  this is what the properties file looks like https://i.imgur.com/Sbw0wsl.png and this for the model i assume that it has something to do with the parent? https://i.imgur.com/3GOZgDu.png parent file i set up so i get the itemrender without using  a highly detailed custom model https://i.imgur.com/A6Fly65.png << is the base parent i am using for the custom items now the question here is has something changed so this is not going to work anymore is there a issue on my part or is this something that will be adressed moving forward?

**Comment by Triliton** [comment]
Anyone ??

**Comment by sp614x** [comment]
CIT textures and models should be fixed in pre7.

**Comment by Triliton** [comment]
Fantastic :)
