### ISSUE TITLE
[1.13.1 E3 Pre4] Shaders bug : Grass block has no shadow

### ISSUE THREAD

**Issue by KyoukoChan** [sp614x/optifine#1867]
![2018-10-06_12 52 08](https://user-images.githubusercontent.com/43900841/46567922-d1e39400-c966-11e8-9515-2563ec2c957f.png)

**Comment by realjackasterisk** [comment]
....you wanna give us some details? Shader pack? Game logs? Maybe PC specs?

**Comment by KyoukoChan** [comment]
Umm
![2018-10-06_12 39 18](https://user-images.githubusercontent.com/43900841/46567855-2f76e100-c965-11e8-938c-a933051474ff.png)

I try some shader like Seus,Continumm but same
Shaders pack : Chocapic13 V7

PC specs 
-Intel core i7 4500U 1.80 Ghz
-Nvidia GT720M

**Comment by sp614x** [comment]
Looks like a shader pack or a driver problem.
