### ISSUE TITLE
latest optifine preview 4 - 1.13.1 - Minecraft is locked into one quater of the window when shader applied..

### ISSUE THREAD

**Issue by quantyx** [sp614x/optifine#1869]
Regardless of which shader I'm installing and which is already optimized for 1.13.1 my Minecraft is locked into the one quater of the window. Haven't had the issue on 1.12.1.
<img width="1680" alt="screenshot 2018-10-06 at 12 28 42" src="https://user-images.githubusercontent.com/43905734/46570466-f76f9e00-c964-11e8-8078-4023c60a31b5.png">

**Comment by brianmcculloh** [comment]
I have this exact same issue.

**Comment by ozals** [comment]
Unzip the shader, this should be something you do to all shaders anyway, unless the shader creator states otherwise.

**Comment by ozals** [comment]
No, unzip it like you would any other file (if you're using winrar, you right click, and then click "extract to [filename]\". The order should be .minecraft\shaderpacks\[shader name]\shaders

**Comment by quantyx** [comment]
alright, got you. But with this shader I'm using (Sildurs Vibrant) there is no need for unzipping..
So I tried both, unzipped and .zip file but still get the same result..

**Comment by ozals** [comment]
Can you post an f3 screenshot with the unzipped shader on?

**Comment by quantyx** [comment]
<img width="1920" alt="screenshot 2018-10-10 at 16 06 53" src="https://user-images.githubusercontent.com/43905734/46742120-a9310680-cca6-11e8-8415-91d8ec6bfc3d.png">

**Comment by ozals** [comment]
I got no idea, this issue seems to have the same problem though. https://github.com/sp614x/optifine/issues/1817#issue-362383775

**Comment by quantyx** [comment]
hmm.. that's weird indeed. I hope this gets fixed in the final version.

Thanks for your help tho man! Appreciate it!

**Comment by sp614x** [comment]
Should be fixed in latest release.
