### ISSUE TITLE
Already Building Crash

### ISSUE THREAD

**Issue by cjburkey01** [sp614x/optifine#187]
My friend gets this crash report when using a large amount of mods on Windows with optifine installed and views a recipe in JEI: [GIST](https://gist.github.com/cjburkey01/7b3903c48973ee3787edfe0e6e5c9684). However, once optifine is removed, it works fine. Also, I can use the same mods on Mac and not get the crash with optifine.

**Comment by sp614x** [comment]
Can you post the full error log, the real problem is there.

**Comment by Alaberti** [comment]
@Cjburkey Does your have an Nvidia graphics card?

**Comment by cjburkey01** [comment]
I believe he does, but this problem hasn't happened recently.
