### ISSUE TITLE
Black Texture between vertical walls

### ISSUE THREAD

**Issue by sakib-ullah** [sp614x/optifine#1872]
Default texture pack.
![2018-10-06_19 43 44](https://user-images.githubusercontent.com/41649230/46572021-0a07c880-c9a1-11e8-8627-f1532abc7e8e.png)
![2018-10-06_19 44 58](https://user-images.githubusercontent.com/41649230/46572022-0ecc7c80-c9a1-11e8-885a-3fcedb911c80.png)

**Comment by sp614x** [comment]
How does it look in vanilla 1.13.1?

**Comment by sakib-ullah** [comment]
Same for mossy cobblestone wall too.

With optifine:
![2018-10-14_13 31 26](https://user-images.githubusercontent.com/41649230/46913806-1a79fd80-cfb6-11e8-9ab2-735e108741b2.png)


Vannila:
![2018-10-14_13 27 28](https://user-images.githubusercontent.com/41649230/46913809-236acf00-cfb6-11e8-9210-48c1d9dfbfea.png)

**Comment by sp614x** [comment]
Is the problem existing in 1.12.2?

**Comment by sakib-ullah** [comment]
No, 1.12.2 Works Just fine

vanilla:
![2018-10-14_14 42 02](https://user-images.githubusercontent.com/41649230/46914481-2cf93480-cfc0-11e8-8199-48a47c9b3ca4.png)


optifine:
![2018-10-14_14 44 50](https://user-images.githubusercontent.com/41649230/46914482-35516f80-cfc0-11e8-8876-33b438ec38d6.png)

**Comment by sp614x** [comment]
Fixed, coming in E5_pre1.
