### ISSUE TITLE
Custom Item Model bugged 1.13.1

### ISSUE THREAD

**Issue by Aaron2550** [sp614x/optifine#1875]
The weapons are from [https://goo.gl/Qd5Dzo](url), I fixed one of the many models myself but changing scale and rotation is very tedious. Did something change or this an OptiFine issue (which i'm pretty sure it is) ? There's probably something obvious im missing...
![chrome_2018-10-07_17-24-22](https://user-images.githubusercontent.com/24834067/46583372-1f8afa00-ca56-11e8-85c2-8f5d02fa1119.png)
![javaw_2018-10-07_17-23-31](https://user-images.githubusercontent.com/24834067/46583373-1f8afa00-ca56-11e8-897e-a00d5c040376.png)

**Comment by joshi77** [comment]
is that a mod or? armor stands?

**Comment by Stevecurious** [comment]
#1787 #1824 
Seems to be still up.

**Comment by sp614x** [comment]
Were CIT models working properly in 1.12.2?

**Comment by Aaron2550** [comment]
Yep, its a 1.12.2 pack, i even tested it right after i saw it was bugged in 1.13.1 because i couldnt believe it was OptiFine's "fault" (I remembered to have read "Fixed Custom Items" in the changelog, but it apparently has nothing to do with CIT's ), its perfectly normal in 1.12.2

**Comment by Aaron2550** [comment]
OH! what might be interesting is that ive managed to port one specific model from that respack to 1.13.1, it works fine, scale and rotation work perfectly, although i cant remember how i did it, if you guys need that model as it could help i can upload it.

**Comment by sp614x** [comment]
Item rendering and model loading are significantly different between 1.12 and 1.13 so it is quite possible that OptiFine doesn't handle or that it handles incorrectly the model transforms.

**Comment by sp614x** [comment]
Are the 1.13 CIT models not reacting to scale/transforms at all (always using the original model transforms) or are the transforms just applied differently?

**Comment by Stevecurious** [comment]
Let me explain that a bit more: the custom items don't react to scaling, rotating or translating at all. Several items are displayed differently when set on head, like the end rod making an unicorn horn. Thus I can report that for example my models based on a gold nugget are just displayed where the center of the normal gold nugget would be when set on hat. (They are normally displayed at the back of the head right above it like in a 2D grid)

![2018-10-14_12 05 43](https://user-images.githubusercontent.com/21973456/46915274-8144ea00-cfa9-11e8-924d-f3b199ac7ec3.png)
![2018-10-14_12 02 51](https://user-images.githubusercontent.com/21973456/46915250-362ad700-cfa9-11e8-82e4-f147ab62b205.png)
![2018-10-14_12 03 23](https://user-images.githubusercontent.com/21973456/46915251-362ad700-cfa9-11e8-8894-dc551c066bb8.png)

The image with the golden crown shows that translation isn't working, is it should be moved several pixels towards the middle of the hat, the other one indicating all three settings not working (should be rotated, scaled down and translated properly). These are no problems with the models itself, if I define them as the normal model for a gold nugget (or every other item), the settings work. So it is an issue with how Custom Item Models recognize these settings. Hope that helps a bit :)

**Comment by Aaron2550** [comment]
Thanks! I kinda understand it now, so basically only scale, rotation and position are bugged.

**Comment by sp614x** [comment]
Fixed, coming in pre6.
