### ISSUE TITLE
1.13.1 Stairs waving like foliage

### ISSUE THREAD

**Issue by AtomicHawk** [sp614x/optifine#1882]
As the title states, stairs are currently waving as if they were foliage (leaves, vines, etc)

**Comment by D3monPixel** [comment]
Your shader probably uses numeric ids to apply the waving effect. And due to the flattening in 1.13 numeric ids are no longer consistent. Update your shader to use the proper block names.

**Comment by realjackasterisk** [comment]
This is seriously the oldest and most known issue with 1.13. Please search issues before posting.
Like D3mon said, this is an issue with shader packs, not OptiFine itself.

**Comment by sp614x** [comment]
Preview pre5 should fix this.
