### ISSUE TITLE
1.13.1 Pre With Ubuntu 18.04

### ISSUE THREAD

**Issue by alexisantonakis** [sp614x/optifine#1883]
Just tried the above combination and Minecraft will not even start.
I can open the loader and select the optifine 1.13.1 option, but when I click on the play button there is a short pause and then I am told that Minecraft has crashed,
Oh yes, this is using the new Minecraft loader, so not sure if that makes any difference.

Any one able to offer any advice please or is the pre version not yet sorted for Ubuntu.

Cheers

**Comment by ozals** [comment]
https://github.com/sp614x/optifine/issues/1818#issuecomment-427983171 this might fix your problem, it's on an issue for Linux Mint, but since Ubuntu and Mint are based on Debian, the fix works on both.

**Comment by alexisantonakis** [comment]
Excellent...and thanks for the quick reply...that indeed fixed everything :)
