### ISSUE TITLE
Optimize cutting tall structures in half

### ISSUE THREAD

**Issue by MrGundum** [sp614x/optifine#1885]
Is there anyway to turn this 'feature' off?

Example:

With optifine:
~~https://imgur.com/nBXOyJT~~
https://imgur.com/Y26sDFv
https://imgur.com/2UkFZKW

Without optine:
~~https://imgur.com/6JSenUi~~
https://imgur.com/ZnpnoH9

**Comment by realjackasterisk** [comment]
This isn't even a thing, as far as I'm aware. Are you sure you don't have a lower render distance with OptiFine installed? Can you post some F3 screenshots?

**Comment by realjackasterisk** [comment]
Also, screenshots at about the same in-game time would be better.

**Comment by MrGundum** [comment]
> Also, screenshots at about the same in-game time would be better.

updated the screenshots. Options show same render distance. My friend has the same issue when he has optifine installed as well.

**Comment by realjackasterisk** [comment]
![image](https://user-images.githubusercontent.com/31686191/46769878-06768900-cca2-11e8-8d84-4cec40950269.png)
oh boy.

well first, see if the issue persists without all those mods. OptiFine is known for being incompatible with some.

second, what version of OF do you have?

**Comment by MrGundum** [comment]
OptiFine 1.12.2 HD U D3

After loading up a new world with only optifine it seems to be a compatibility issue with something inside of the sevtech mod pack. Guess i just can't use optifine with it then.

**Comment by realjackasterisk** [comment]
You should try it with the actual latest version of OptiFine. Likely it won't help, but it's still worth a shot. https://optifine.net/downloads
