### ISSUE TITLE
Spectral Arrow Bug

### ISSUE THREAD

**Issue by mandm635** [sp614x/optifine#189]
This is normal 1.10:
![db3c0a438fbe2875eb9820ce37fdb7c4](https://cloud.githubusercontent.com/assets/13128898/16308152/b1733a80-3918-11e6-8610-802c62c4c08e.png)
This is 1.10 with Optifine HD_U_B6:
![738a5cb8072721d3c0ffedef5b6d2265](https://cloud.githubusercontent.com/assets/13128898/16308179/c9c8ebe8-3918-11e6-846f-14eff89934e7.png)

This issue applies to any creature shot with a spectral arrow.

**Comment by sp614x** [comment]
The spectral effect is not compatible with Fast Render, Antialiasing and
Shaders.
OptiFine uses a simplified version when the full spectral effect is not
possible.

**Comment by sp614x** [comment]
The spectral effect is not compatible with Fast Render, Antialiasing and Shaders. OptiFine uses a simplified version when the full spectral effect is not possible.

**Comment by mandm635** [comment]
Oh ok, Ill try that

**Comment by mixxit** [comment]
Move options files out of .minecraft dir to fix
