### ISSUE TITLE
[1.13.1-pre5] Font - Incorrect character spacing

### ISSUE THREAD

**Issue by Heitzenberg** [sp614x/optifine#1891]
In 1.13.1-pre5, "FontRenderer" has been merged. Now, every font is way too wide (spacing between characters is incorrect). How can I access the settings or is this a bug?

**Comment by sp614x** [comment]
If the font uses custom font properties (for example `ascii.properties`) they are going to be applied in pre5.
Either remove or fix the font properties to fix the character spacing.
