### ISSUE TITLE
[Pre-5, 1.13.1] color.properties not entirely functional.

### ISSUE THREAD

**Issue by DataCrusade** [sp614x/optifine#1893]
Changing the spawn eggs colors with (for example) `egg.shell.Enderman=ff4ce5
egg.spots.Enderman=ff4ce5` does not work at all, 

Changing `particle.water=000000` (for example) does not work either. Changing `particle.portal=000000` however works no problem.

**Comment by sp614x** [comment]
Fixed, coming in pre6.
