### ISSUE TITLE
(1.13.1 Pre5) Custom Item Textures (CIT) not working

### ISSUE THREAD

**Issue by JeffrySG** [sp614x/optifine#1896]
Just noticed that CIT are not working in the 1.13.1 pre5 release. Everything was working fine in pre4, though. This was with testing with items renamed in the anvil to use specific new textures. I was testing with my poison potato pack found at: <https://blocktools.deep-orbit.com/#potato> if that can help or makes a difference. I can post any other info as requested.

**Comment by realjackasterisk** [comment]
1.13.1 pre5 changelog:
> - moved all configurations from folder "mcpatcher" to folder "optifine" (#1557)

**Comment by JeffrySG** [comment]
Thank you, I totally missed that!
