### ISSUE TITLE
1.13.1 Entities ID Mapping

### ISSUE THREAD

**Issue by ghost** [sp614x/optifine#1897]
Hello @sp614x it's possible to Add Entites.properties please?

For make effect i.e "experience_orb" etc...

Thanks for your work !

Best regards

**Comment by LexBoosT** [comment]
+1

**Comment by Regnander** [comment]
@LexBoosT You can also click the smiley icon and then the thumbs up emoji if you support an idea. 

![1](https://user-images.githubusercontent.com/17113053/46908605-83fdfb80-cf25-11e8-8488-ea8085737bf0.png)

This way other users can sort the issues by most thumbs-up to see which one's the most popular.

![2](https://user-images.githubusercontent.com/17113053/46908633-de975780-cf25-11e8-99f0-4d16bfabe83b.png)

**Comment by LexBoosT** [comment]
Thanks @Regnander  ;)

**Comment by sp614x** [comment]
Coming in pre6.

```
Entity ID mapping
================
The entity ID mapping is defined in "shaders/entity.properties" included in the shader pack.
Forge mods may add custom entity mapping as "assets/<modid>/shaders/entity.properties" in the mod JAR file.
The "entity.properties" file can use conditional preprocessor directives (#ifdef, #if, etc.)
For more details see section "Standard Macros" A to G. Option macros are not available.
Format "entity.<id>=<entity1> <entity2> ..."
The key is the substitute entity ID, the value are the entities which are to be replaced.
Only one line per entity ID is allowed.

  # Short format
  entity.2000=sheep cow
  # Long format
  entity.2001=minecraft:pig botania:pixie
```
