### ISSUE TITLE
Odd CTM Loading (pre5)

### ISSUE THREAD

**Issue by InfiniteCorners** [sp614x/optifine#1902]
I have been updating my CTM files and have come across an unusual situation/bug regarding my bookshelves. I have an altered vanilla block model for bookshelf pointing to an image called bookshelf_top for the tops and bottoms of my bookshelf, rather than oak planks. I have CTM files for the bookshelf.png as well as bookshelf_top.png and for the most part they seem to work as planned. The issue is that upon the initial launch, or when trying to switch to the pack from the pure default, the CTM for bookshelf_top is not applied. This can be resolved by loading any other pack, causing it refresh. It also seems that if you have a custom pack already in use then load the CTM pack it will not load the CTM files however once the CTM pack has been activated removing the custom pack is enough to refresh the files and get them working. Not sure if I'm doing something wrong on my end or if this is a bug you folks can resolve.

http://www.mediafire.com/file/kjx4v3p268r7z2p/CTM.zip/file

**Comment by sp614x** [comment]
Fixed, coming in pre6.
