### ISSUE TITLE
Changing focus from fullscreen with shaders enabled causes massive lag spikes and temporary freezing

### ISSUE THREAD

**Issue by pyrestriker** [sp614x/optifine#1906]
nVidia 750ti running dual monitors with the 416.34 Drivers.
4-core Intel Core i5 @3.1 Ghz.
12 GB RAM (4 allocated)
Windows 10 Pro.
OptiFine 1.13.1 HD U E3 pre6

When I select a window on my second monitor while in fullscreen, the game shifts into the background on the primary monitor. If I do this with any shader enabled, the game will stutter down to a screeching halt, taking up to 10 seconds to start showing frames again, and even then it will keep halting for a good bit and the FPS will remain at about half. If done again, it gets progressively worse each time. This will also occur if I'm in fullscreen and alt+Tab to another program on the same monitor.

**Comment by sp614x** [comment]
Release E3 should fix the problem with OpenGL errors spamming the log.
