### ISSUE TITLE
Slider Bars on shader options not work

### ISSUE THREAD

**Issue by 6ix7even** [sp614x/optifine#1907]
In shader options, slider bars do not work properly on Optifine E3 pre 7

![](https://i.imgur.com/Oi1dFhP.png)

**Comment by ozals** [comment]
Do you have any resource packs on?

**Comment by 6ix7even** [comment]
Yep but it does it with any resource pack

**Comment by ozals** [comment]
I’ve had this problem before, try again with all resource packs off.

**Comment by sp614x** [comment]
Please test again with latest preview pre7.

**Comment by 6ix7even** [comment]
well it does not work even with the basic resource pack and I have pre7

**Comment by sp614x** [comment]
Fixed, coming in pre8.
