### ISSUE TITLE
1.13.1 Font Rendering looks weird.

### ISSUE THREAD

**Issue by howmanysmall** [sp614x/optifine#1908]
Here's how it looks in the latest preview versions:

![image](https://user-images.githubusercontent.com/26746527/46973064-6a6fc780-d07d-11e8-9e79-3bb1cba00ecc.png)

Versus how it looked before in preview E4:

![image](https://user-images.githubusercontent.com/26746527/46973170-a7d45500-d07d-11e8-8b35-b7e5b20f43f0.png)

This started in preview E5 if I remember correctly, and I'm a little annoyed by it.

**Comment by sp614x** [comment]
Looks like the resource pack has font properties files, for example "ascii.properties".
Either delete the properties or fix the character widths in them.
