### ISSUE TITLE
Comparator/Repeater texture issue [Pre7]

### ISSUE THREAD

**Issue by Treijim** [sp614x/optifine#1910]
I'm having problems remodelling/retexturing comparators and repeaters. 

On older versions of Optifine, I would do this for the blockstate: 

`{
    "variants": {
        "delay=1,facing=south,locked=false": { "model": "block/repeater_lp1" },
        "delay=1,facing=west,locked=false": { "model": "block/repeater_lp2", "y": 90 },
        "delay=1,facing=north,locked=false": { "model": "block/repeater_lp3", "y": 180 },
        "delay=1,facing=east,locked=false": { "model": "block/repeater_lp4", "y": 270 },
        "delay=2,facing=south,locked=false": { "model": "block/repeater_lp5" },
        "delay=2,facing=west,locked=false": { "model": "block/repeater_gl1", "y": 90 },
        "delay=2,facing=north,locked=false": { "model": "block/repeater_gl2", "y": 180 },
        "delay=2,facing=east,locked=false": { "model": "block/repeater_gl3", "y": 270 },
        "delay=3,facing=south,locked=false": { "model": "block/repeater_lp6" },
        "delay=3,facing=west,locked=false": { "model": "block/repeater_gl4", "y": 90 },
        "delay=3,facing=north,locked=false": { "model": "block/repeater_lp7", "y": 180 },
        "delay=3,facing=east,locked=false": { "model": "block/repeater_gl5", "y": 270 },
        "delay=4,facing=south,locked=false": { "model": "block/repeater_gl6" },
        "delay=4,facing=west,locked=false": { "model": "block/repeater_gl7", "y": 90 },
        "delay=4,facing=north,locked=false": { "model": "block/repeater_gl8", "y": 180 },
        "delay=4,facing=east,locked=false": { "model": "block/repeater_gl9", "y": 270 },
        "delay=1,facing=south,locked=true": { "model": "block/repeater_locked_1tick" },
        "delay=1,facing=west,locked=true": { "model": "block/repeater_locked_1tick", "y": 90 },
        "delay=1,facing=north,locked=true": { "model": "block/repeater_locked_1tick", "y": 180 },
        "delay=1,facing=east,locked=true": { "model": "block/repeater_locked_1tick", "y": 270 },
        "delay=2,facing=south,locked=true": { "model": "block/repeater_locked_2tick" },
        "delay=2,facing=west,locked=true": { "model": "block/repeater_locked_2tick", "y": 90 },
        "delay=2,facing=north,locked=true": { "model": "block/repeater_locked_2tick", "y": 180 },
        "delay=2,facing=east,locked=true": { "model": "block/repeater_locked_2tick", "y": 270 },
        "delay=3,facing=south,locked=true": { "model": "block/repeater_locked_3tick" },
        "delay=3,facing=west,locked=true": { "model": "block/epeater_locked_3tick", "y": 90 },
        "delay=3,facing=north,locked=true": { "model": "block/repeater_locked_3tick", "y": 180 },
        "delay=3,facing=east,locked=true": { "model": "block/repeater_locked_3tick", "y": 270 },
        "delay=4,facing=south,locked=true": { "model": "block/repeater_locked_4tick" },
        "delay=4,facing=west,locked=true": { "model": "block/repeater_locked_4tick", "y": 90 },
        "delay=4,facing=north,locked=true": { "model": "block/repeater_locked_4tick", "y": 180 },
        "delay=4,facing=east,locked=true": { "model": "block/repeater_locked_4tick", "y": 270 }
    }
}
`

and this for each model I customised: 

`{
    "ambientocclusion": false,
    "textures": {
        "particle": "block/repeater_lp1",
        "texture": "block/repeater_lp1"
    },
    "elements": [
        {   "from": [ 0, 0.25, 0 ],
            "to": [ 16, 0.25, 16 ],
            "faces": {
                "down":  { "uv": [ 16, 16, 0,  0 ], "texture": "#texture", "tintindex": 0 },
                "up":    { "uv": [ 16,  0, 0, 16 ], "texture": "#texture", "tintindex": 0 }
            }
        }
    ]
}
`

which should force each individual state to act flat like rail models, or a standing cross-section like cobweb models. Everything works except for the way the texture is rendered. As you can see, it treats the bottom face as solid, giving an x-ray view. I'm not sure if I'm doing something wrong, or if this feature isn't implemented yet. Any help appreciated. 

![screenshot 5](https://user-images.githubusercontent.com/344239/46993452-d4a86b00-d156-11e8-9fd0-cfd494826477.png)

**Comment by sp614x** [comment]
This is a vanilla JSON model, OptiFine doesn't change how vanilla models work.
See here https://minecraft.gamepedia.com/Model
