### ISSUE TITLE
Connected Glass Textures 1.13.1

### ISSUE THREAD

**Issue by XpatJohn** [sp614x/optifine#1912]
Hi All,

  First, let me say if it wasn't for Optifine, I wouldn't be playing Minecraft.  Thank you, very much, for creating such an awesome product.

  I have been eagerly trying out the various beta versions of Optifine 1.13.1 and I have noticed an issue.  In Pre-build 4, (I have tested this on Pre5, Pre6 & Pre7) connected glass textures worked.  Every build since then has stopped working.  Please see the screenshots below.

![2018-10-16_07 33 56](https://user-images.githubusercontent.com/44201709/47020437-9ab77480-d116-11e8-97de-770fb552423f.png)
![2018-10-16_07 29 30](https://user-images.githubusercontent.com/44201709/47020439-9ab77480-d116-11e8-9f0d-3d7f5fb00077.png)

Again, thank you for the awesome product, you guys rock!

**Comment by chland** [comment]
this happens most likely because the folder-structure was changed. Check if there is a folder called 

`assets/minecraft/mcpatcher`

in your resource-pack. If it exists, rename it to 

`assets/minecraft/optifine`

**Comment by XpatJohn** [comment]
Thank you.  Oddly, that worked for the texture pack I have in the images (which is awesome), but it didn't work for any of my other texture packs.
Thank you for the assistance.  I will keep an eye out for texture pack updates from the various authors.

**Comment by InfiniteCorners** [comment]
You other texture packs may be using numeric IDs to distinguish blocks which is also no longer supported. Switching files to the right folders and using the block names instead of numbers should have you working across the board.

**Comment by sp614x** [comment]
To fix the resource pack
- rename the folder "mcpatcher" to "optifine"
- replace the numeric block IDs and metadata with block names and properties
