### ISSUE TITLE
Leaves and Grass don't move with shaders.

### ISSUE THREAD

**Issue by JonIsPatented** [sp614x/optifine#1915]
In 1.12, the leaves and grass would move. In an older 1.13.1 optifine beta, leaves and grass would still move except the grass actually would remain still and diorite would move instead (with hilarious results), but now, neither one moves at all. Crops, water, etc. All stationary now.

**Comment by Regnander** [comment]
>diorite would move instead (with hilarious results)

Can you post a gif of it?

**Comment by DataCrusade** [comment]
Use the search tool, there's gotta be at least 10 of these issues made. It's an issue with the shaders, not with optifine. The shaders need to update.

**Comment by ozals** [comment]
Seriously, not enough people search for other issues before opening one, but yes, this is a problem with the shaders being outdated, since the 1.13 flattening changed IDs and other things with blocks.

**Comment by sp614x** [comment]
Shader packs have to be updated to work with 1.13.

**Comment by JonIsPatented** [comment]
Ok. Thanks. I just made an account right before posting so I have no clue how this works. Thanks for clearing it up.
