### ISSUE TITLE
Fonts in Pre6 and Pre7 Are Illongated

### ISSUE THREAD

**Issue by CyberGen49** [sp614x/optifine#1916]
Custom resourcepack fonts are longer than they need to be in the latest couple previews. See the attached image for an example.
![Issue Example](https://user-images.githubusercontent.com/38225790/47052935-52c53b80-d170-11e8-84e6-2688a2e6d116.png)

**Comment by realjackasterisk** [comment]
#1891, #1908

**Comment by ozals** [comment]
does no one search for other issues?

**Comment by CyberGen49** [comment]
Ah, I should have looked first, my bad.
