### ISSUE TITLE
Broken rendering after disabling Fast Render

### ISSUE THREAD

**Issue by The-Fireplace** [sp614x/optifine#1920]
After disabling Fast Render, the screen did this:
![image](https://user-images.githubusercontent.com/5914284/47126317-a063a600-d24d-11e8-967c-80552471501d.png)
OptiFine 1.12.2 HD U E2
Forge 1.12.2 - 14.23.5.2770

**Comment by sp614x** [comment]
Is this a mod pack, if so which other mods are installed?

**Comment by The-Fireplace** [comment]
Not a public modpack, but yes. Here is the full list:
https://modlister.com/user/The_Fireplace

**Comment by sp614x** [comment]
Most probably a confict with one of the mods.

**Comment by The-Fireplace** [comment]
After finally loading up the game and trying to get the info needed, I was unable to reproduce the issue.
