### ISSUE TITLE
Rain changes colors when player is standing on leaf block or is mid-air.

### ISSUE THREAD

**Issue by BeltfedJoe** [sp614x/optifine#1921]
This may actually apply to all transparent blocks, it appeared to do the same on glass, but the rain stopped before snagged a screen shot. In the pictures you can see the rain looks totally different an the only thing that changed was the block i was standing. I also placed a dirt block so i was at the same elevation on a solid block.  This still showed the same rain as the sand and all other solid blocks i checked.

![standing on sand](https://user-images.githubusercontent.com/44252522/47131558-2da9f900-d254-11e8-93f1-62efe8289c86.png)
![standing on leaf block](https://user-images.githubusercontent.com/44252522/47131559-2edb2600-d254-11e8-8ef0-41de716be512.png)

**Comment by sp614x** [comment]
Were you standing in a shadow (under another block)?

**Comment by BeltfedJoe** [comment]
Negative. Nothing but sky above.

**Comment by sp614x** [comment]
The rain/snow color depends on the local light level.
You can see the light level in the debug screen (F3).

**Comment by BeltfedJoe** [comment]
How is that affected by the block youre standing on? Assuming both are
surrounded by torches?

**Comment by sp614x** [comment]
The light level may sometimes get stuck after a failed lighting update.
You can check the light level in the debug screen (F3).

**Comment by BeltfedJoe** [comment]
I will double check block light levels this evening. But how does this
explain the change while midair?

**Comment by KaiAF** [comment]
Is this still an issue?

**Comment by Jiingy** [comment]
Closing as this issue has had no follow up in over 5 years. As sp614x stated in an earlier comment the change in rain color was likely due to the local light level.
