### ISSUE TITLE
Custom Sky for the End

### ISSUE THREAD

**Issue by InfiniteCorners** [sp614x/optifine#1922]
I want to start by saying that I know this is slightly related to https://github.com/sp614x/optifine/issues/1065 however what is proposed there is different from what I've been trying to do and I was wondering if I'm doing something wrong, if this is impossible or if it's a feature that could be added. 

Not being happy with the quality of my end sky I decided I'd like to try to improve it. The repeating texture of end_sky is applied in a 16x16 grid so I THOUGHT I should be able to use a repeating CTM with a width and height of 16x16 to apply a large image to the walls of the segmented skybox. When applied to dirt the texture works as expected however when targeting end_sky I see no change from default end_sky image used in the environments folder. I was honestly hoping I would be able to find a block model for the end_sky that I could then alter to use different 16x16 images for N, S, E, W, top and bottom but I'm not entirely sure if that's possible with how that box is rendered or if, even using CTM, all 6 faces would need to be the same texture- I never did find a blockstate or model or any asset beyond end_sky.png

Is it possible to do what I'm attempting? Could it be made possible or would it be easier for you guys to just add a real skybox, as mentioned in #1065, if you're going to devote the time to the end sky? Sorry if you consider this a duplicate but I'm trying to figure out if this is doable or if I'm wasting my time cropping and formatting these images.

**Comment by sp614x** [comment]
CTM is only for blocks, it is not going to work for the End sky.
Currently the End sky uses the vanilla rendering, which is limited to the vanilla texture.
Custom Sky could be expanded to allow the End also to be customized.

**Comment by InfiniteCorners** [comment]
Thanks for the quick reply. It saves me hours of work creating and testing images to know is isn't possible. I'll wait for you guys to give me a way to do it.

**Comment by sp614x** [comment]
Added custom sky for the end dimension (world1).
