### ISSUE TITLE
transition overlays still dont render proper

### ISSUE THREAD

**Issue by VanimaPermai** [sp614x/optifine#1923]
the transition overlays for grass and such don't render correctly at all
the textures dont always display and when they do they clip in to the block 
and there positioning dosent line up corectly 
https://imgur.com/a/AxFBnkK

**Comment by sp614x** [comment]
Resource pack link?

**Comment by VanimaPermai** [comment]
link to pack with this issue s reqested 
https://www.planetminecraft.com/texture_pack/vanim/

**Comment by sp614x** [comment]
## Update to 1.13
## Resource packs
* Rename folder "assets/minecraft/mcpatcher" to "assets/minecraft/optifine"
* In all ".properties" files replace references to "assets/minecraft/mcpatcher" with "assets/minecraft/optifine"
* Replace all numeric IDs (blocks, items, enchantments, etc.) with [names](https://minecraft.gamepedia.com/1.13/Flattening)

Also check the block/tile names, many have been changed in 1.13, for example the grass texture.
https://minecraft.gamepedia.com/1.13/Flattening

**Comment by VanimaPermai** [comment]
ill try it with the newest optifine.... nope its still broken
