### ISSUE TITLE
Custom Sky stopped working

### ISSUE THREAD

**Issue by BatHeart** [sp614x/optifine#1925]
This may be my mistake, but I was using Custom Sky and it was working in 1.13.1 early pre-releases but I've noticed it has now stopped working. Appears to have happened between pre4 and pre5.

**Comment by ozals** [comment]
Is it in an mcpatcher folder?

**Comment by D3monPixel** [comment]
how do people miss the f***ng patch notes and changelogs? The button is right beside the "(mirror)" and should be checked instantly as a new update comes so you know what has been changed...
Move everything from inside /mcpatcher to /optifine in your resourcepack...

**Comment by BatHeart** [comment]
I just checked, and I think you're right. It does have 'colormap', 'lightmap' and 'sky' within the mcpatcher folder of the respack.

**Comment by BatHeart** [comment]
Wow @D3monPixel. Such a polite reply. Thank you! 
I always read the patchnotes, but just hadn't realised there was anything related to mcpatcher in this resourcepack. Thank you for being so understanding

**Comment by D3monPixel** [comment]
I got to a point where I lost care if I'm rude or not. Seeing so many people open issues about the same things just because they haven't read the patchnotes gets tiring and annoying

**Comment by BatHeart** [comment]
I assure you this wasn't the case with me. I just hadn't put two and two together. 
But I'll remember you in future, and attempt not to antagonise you.
