### ISSUE TITLE
Launch Crash on Linux

### ISSUE THREAD

**Issue by homonovus** [sp614x/optifine#1926]
When launching from the default Minecraft launcher while running Manjaro 17.1.12 causes the Minecraft instance to crash without starting.

No crash report is generated.

**Comment by ozals** [comment]
I'm not a Manjaro user myself, but this might be a problem with OpenJDK runtime, this should help. https://github.com/sp614x/optifine/issues/1818#issuecomment-427983171
Seems to be a common problem with linux right now, 3 issues on it, been fixed by this solution though.

**Comment by homonovus** [comment]
i'm using oracle jdk 11.0.1-1 from AUR

**Comment by ozals** [comment]
did you try the commands though?

**Comment by homonovus** [comment]
manjaro uses pacman, not apt, so i can't sadly :B

**Comment by homonovus** [comment]
which java
`/usr/bin/java`
java --version
`java 11 2018-09-25
Java(TM) SE Runtime Environment 18.9 (build 11+28)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11+28, mixed mode)`
pacman -Qe jdk
`jdk 11-2`

**Comment by homonovus** [comment]
optifine just doesnt seem to like jdk 11 for some reason;
installing jdk8 from AUR fixed the issue.
maybe there should be a tip for linux users to user java/jdk 8 on the optifine website

**Comment by ozals** [comment]
Actually I found a way to do it without apt commands

**Comment by ozals** [comment]
Ohhh you were trying with java 11
Yep right now it only supports java 8

**Comment by FX9ZVI** [comment]
I have java 8 installed, how do I use it to open the optifine .jar file?

**Comment by ozals** [comment]
You just open it like you would any other file, then it would ask to install, and install it.
