### ISSUE TITLE
mcPatcher breaks in new versoin of optifine

### ISSUE THREAD

**Issue by ham1255** [sp614x/optifine#1930]
![image](https://user-images.githubusercontent.com/34905970/47198009-e36f6780-d37a-11e8-8fec-6363d5c6d5ec.png)
i had thes files does work on aplha versoin that was release but the Release of the new one McPatcher Not working at all

**Comment by ham1255** [comment]
it only shows the normal sky 
![image](https://user-images.githubusercontent.com/34905970/47198054-1dd90480-d37b-11e8-86f6-79cfcdeafb05.png)
![image](https://user-images.githubusercontent.com/34905970/47198065-30ebd480-d37b-11e8-9c3b-e42bd9c630f6.png)

**Comment by ozals** [comment]
Pre5 merged the mcpatcher and optifine folders. Rename it to optifine and it will work. We're at the point where we need to have this in bold flashing red text on the website.

**Comment by sp614x** [comment]
Rename the folder "mcpatcher" to "optifine":
https://github.com/sp614x/optifine/issues/1557
