### ISSUE TITLE
[1.13] item/model.json CIT model paths don't work correctly

### ISSUE THREAD

**Issue by HanFox** [sp614x/optifine#1932]
Using OptiFine_1.13.1_HD_U_E3.jar

When trying to map models for CIT as per https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/cit_single.properties#L64 models can't be found.

e.g. `model=item/bow` gives the path `minecraft:models/item/item/bow.json` instead of just `minecraft:models/item/bow.json`

**Comment by Regnander** [comment]
I just want to make sure, have you tried removing "item/" from `model=item/bow`? I don't know if this works, but I messed around with model files yesterday and had the same issue where I got `models/block/block` just because I included "block" in my model path.

**Comment by HanFox** [comment]
Removing `item/` causes OF to look for the model in the same folder as the .properties file.

**Comment by sp614x** [comment]
The path normalization in 1.13 is a bit too complex.

**Comment by sp614x** [comment]
Fixed, coming in E4_pre2
