### ISSUE TITLE
Text in chat is too much spacing

### ISSUE THREAD

**Issue by xMoony** [sp614x/optifine#1933]
I don't know what happened but the fontrenderer is too much spaces  between the letters
![2018-10-19_13 16 59](https://user-images.githubusercontent.com/44292264/47215305-483db880-d3a1-11e8-91cb-1481b91ac855.png)

**Comment by InfiniteCorners** [comment]
https://github.com/sp614x/optifine/issues/ You can search for issues before posting about them. This seems to be an issue with the resource pack's font in ascii.properties or a similar file.

**Comment by xMoony** [comment]
I forgot i had a texture pack, woops. How can i change the Width in that file?

**Comment by InfiniteCorners** [comment]
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/hd_fonts.txt That should have everything you need to know.

**Comment by sp614x** [comment]
Remove or fix the font ".properties" files where the font textures are located.
