### ISSUE TITLE
[1.13.1] CTM not working

### ISSUE THREAD

**Issue by rger0** [sp614x/optifine#1938]
For some reason, even after updating the .properties files to the new format, ctm doesn't seem to work at all ;
(the option is set to "ON" in the settings)

Glass won't connect, etc.

Here's an example of the code I use :
file location : assets\minecraft\mcpatcher\ctm\blocks\glass\default\glass.properties
file code :
`matchBlocks=glass
connect=block
method=ctm
faces=sides
tiles=0-46`

Any idea on what's going on?
If the code and file name are correct, should I delete the optifine install and reinstall?
(I use OptiFine 1.13.1 HD U E3)

**Comment by ozals** [comment]
ok we need this in red flashing letters "THE MCPATCHER FOLDER HAS MOVED TO OPTIFINE"

**Comment by sp614x** [comment]
It is here -> https://github.com/sp614x/optifine/tree/master/OptiFineDoc/doc

**Comment by ozals** [comment]
rename your mcpatcher folder to optifine, and it will work just fine

**Comment by rger0** [comment]
Oh sorry, thanks for your help !
