### ISSUE TITLE
3D Anaglyph and Shaders don't play nice together, however, there's nothing saying this

### ISSUE THREAD

**Issue by quat1024** [sp614x/optifine#194]
If I turn on the internal shader and 3D Anaglyph at the same time, the 3d effect isn't applied (I just get "[colorblindless](http://puu.sh/pFTxn.png)" instead)

Usually when shaders don't play nice with something there's a message when you try to turn them on, for example when you try to turn on Fast Render and Shaders at the same time you get an error message. Maybe consider adding one for 3d Anaglyph.

**Comment by sp614x** [comment]
Fixed, coming in next preview C1 for 1.10.2
