### ISSUE TITLE
Custom Item Textures Broken

### ISSUE THREAD

**Issue by Powerless001** [sp614x/optifine#1940]
In the latest version of Optifine 1.13.1 HD U E3, no custom textures are being loaded. If I go back to OptiFine 1.13.1 HD U E3 pre3, they work fine. I don't know why.

**Comment by realjackasterisk** [comment]
Please, PLEASE read the changelog and documentation. The mcpatcher folder is no longer used in 1.13. Move your stuff to the optifine folder.
