### ISSUE TITLE
drowned cem not working properly

### ISSUE THREAD

**Issue by MrConfusioned** [sp614x/optifine#1943]
i tried to use the alex thin arms on zombies and husks and it worked, but drowned have one big hand and one thin hand
![2018-10-20_10 55 24](https://user-images.githubusercontent.com/42947430/47252515-4d5d3f00-d457-11e8-9792-7ff6b67a29dc.jpg)

**Comment by sp614x** [comment]
The drowned model has inner model (zombie) and outer model (drowned).
Currently only the inner model is configurable.
The outer model is to be added.

**Comment by MrConfusioned** [comment]
how come one of them works

**Comment by ewanhowell5195** [comment]
the outer drowned layer has been added
