### ISSUE TITLE
Custom armor texture issue (solved)

### ISSUE THREAD

**Issue by CptMico** [sp614x/optifine#1946]
I've assigned custom texture for named chainmail armor. Chestplate and boots are working but leggings and helmet seem bugged, textures are not displayed correctly on them. Am I doing something wrong or is it a bug? All items are named properly in game.

![screen002](https://user-images.githubusercontent.com/44323995/47258564-3fcaa800-d49d-11e8-9dd5-ea212f8837af.png)

![screen001](https://user-images.githubusercontent.com/44323995/47258563-3fcaa800-d49d-11e8-993e-e231cdec0f12.png)

Here are my properties files:

type=armor
items=minecraft:chainmail_boots
texture.chainmail_layer_1=fur_boots_layer
nbt.display.Name=Fur Boots

type=armor
items=minecraft:chainmail_chestplate
texture.chainmail_layer_1=fur_chestplate_layer
nbt.display.Name=Fur Chestplate

type=armor
items=minecraft:chainmail_helmet
texture.chainmail_layer_1=fur_helmet
nbt.display.Name=Fur Helmet

type=armor
items=minecraft:chainmail_leggings
texture.chainmail_layer_2=fur_leggings
nbt.display.Name=Fur Leggings

**Comment by InfiniteCorners** [comment]
For the leggings and helmet your forgot the _leggings portion for your texture name so it's trying to put the item texture for each on the armor model. Change your texture path files for those 2 and they should work fine.

**Comment by CptMico** [comment]
Thank you! I didn't see that. Now everything is working.

**Comment by Regnander** [comment]
Use the "Close issue" button to mark this issue as solved.
