### ISSUE TITLE
[1.13.1 E4 pre1] [CEM] Horse body and neck parts affect other model parts

### ISSUE THREAD

**Issue by Fuzss** [sp614x/optifine#1948]
Replacing the `body` or `neck` model part for horses with the CEM feature via `"attach": false` also replaces other parts of the model. So far I've noticed:
- `body` affects `tail` and `saddle`
- `neck` affects `head`, `mane`, `mouth`, `left_ear`, `right_ear`, `headpiece`, `noseband`, `left_bit` and `right_bit` 

I've tried a few different approaches to solve this issue in my current project and since I wasn't able to I can only guess that this is a bug. Since support for the new horse model was introduced very recently this might just be an oversight.
Could also be me having gotten something about CEM completely wrong.

**Comment by Fuzss** [comment]
Replacing models of donkeys, mules, skeleton horses and zombie horses doesn't work at all (the completely disappear and an error is spammed in the console), so I'm guessing this whole thing is still wip.

Also tested the originally described issue in 1.12 and there it works flawlessly.

**Comment by sp614x** [comment]
The 1.13 horse model uses an internal hierarchical structure. 
The "body" is base for all other parts. The "neck" is base for all head parts.
Replacing the body or neck is going to disable all other parts attached to them.

**Comment by sp614x** [comment]
The mule and donkey models are fixed, coming in next preview.
