### ISSUE TITLE
Fonts too large.

### ISSUE THREAD

**Issue by HawaiianPi** [sp614x/optifine#1953]
When using Optifine fonts are too large. Text runs out of the buttons on the settings screens, and signs I had previously made in-game have some of the text cut off. No such troubles with 1.13.1 vanilla.

Minecraft 1.13.1
OptiFine 1.13.1 HD U E3
Oracle Java 1.8.0_181 (64 bit)
Windows 10 x64 (version 1803, build 17134.345) Scaling set at 100% (no scaling).
Nvidia GeForce 1050ti (driver 391.25)

**Comment by 6ix7even** [comment]
This problem it's from your ressource pack , go check with another ressource pack if you have the same probleme

**Comment by realjackasterisk** [comment]
#1891, #1908, #1916, #1933

**Comment by ozals** [comment]
I wouldn't be surprised if it's just one guy making all these duplicate issues just to fuck with us.
