### ISSUE TITLE
CIT not working

### ISSUE THREAD

**Issue by tychoflorent** [sp614x/optifine#1954]
CIT is not working in Minecraft version 1.13.1

**Comment by realjackasterisk** [comment]
Let me guess, mcpatcher folder?

**Comment by tychoflorent** [comment]
Yes

**Comment by realjackasterisk** [comment]
**Please** read. The documentation. The changelog. Anything.

**Comment by sp614x** [comment]
# Update to 1.13
## Resource packs
* Rename folder "assets/minecraft/mcpatcher" to "assets/minecraft/optifine"
* In all ".properties" files replace references to "assets/minecraft/mcpatcher" with "assets/minecraft/optifine"
* Replace all numeric IDs (blocks, items, enchantments, etc.) with [names](https://minecraft.gamepedia.com/1.13/Flattening)
## Shader packs
* Add mappings for all numeric IDs used in the shader ([blocks](https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.txt#L487), [items](https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.txt#L528), [entities](https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.txt#L543), etc.)
