### ISSUE TITLE
[1.13.1+] Strange Problems With FPS & Movement

### ISSUE THREAD

**Issue by TheRealDannyyy** [sp614x/optifine#1955]
## Problem description
After updating to _OptiFine 1.13.1 HD U E3_, I noticed strange framerate problems. These problems lead to gameplay feeling "laggy" and unresponsive in general, especially during combat. 

I have no clue what the cause of this could be but I noticed strange "fr reg" tags in my F3 console and from what I can tell, the framerate seems to be smoothed, despite all FPS smoothing options being set to OFF.

## Steps to reproduce
1. Install OptiFine 1.13.1 HD U E3
2. Join any server (e.g. Vanilla or Hypixel)
3. Notice uneven framerate and stuttering

## Observed result
_OptiFine 1.13.1 HD U E3_ seems to force FPS smoothing despite the option being toggled to OFF.

## Expected result

_OptiFine 1.13.1 HD U E3_ should work like the previous versions and not feel laggy and unresponsive.

## Affected/Tested Versions

* OptiFine 1.13.1 HD U E3
* OptiFine 1.13.1 HD U E4 pre1

## Attachments
_OptiFine 1.13.1 HD U E4 pre1 Debug:_
![optifine results](https://user-images.githubusercontent.com/15656049/47268748-0d7c8180-d555-11e8-80b0-fd128f86e871.jpg)

_Vanilla Debug:_
![default results](https://user-images.githubusercontent.com/15656049/47268745-09506400-d555-11e8-9216-5c1c24fb76d6.jpg)

**Comment by sp614x** [comment]
Can you post a screenshot with the lagometer enabled (Alt+F3)?

**Comment by TheRealDannyyy** [comment]
@sp614x here you go:
![optifine lagometer](https://user-images.githubusercontent.com/15656049/47269341-a236ad80-d55c-11e8-9dbc-414f2082a1d0.jpg)

**Comment by sp614x** [comment]
"fr" -> Fast Render
"reg" -> Render Regions
Both options are in the Performance settings.

**Comment by sp614x** [comment]
The only big lag spike visible is from the garbage collector (memory).

**Comment by TheRealDannyyy** [comment]
No different when switching both of those options to off.

Did 1.13.1 perhaps introduce any new form of "mouse smoothing" or something like that? It's generally noticable when quickly aiming with the mouse.

**Comment by TheRealDannyyy** [comment]
Here is another laggometer screenshot while performing basic movements:
![laggometer movement](https://user-images.githubusercontent.com/15656049/47269457-0f970e00-d55e-11e8-93cd-282ba2b891e6.jpg)

**Comment by sp614x** [comment]
The option Smooth FPS should fix any visual lag if it is caused by the graphics card delaying some frames.

**Comment by TheRealDannyyy** [comment]
Well I switched to 1G and did everything else that I was assuming could be the cause. OptiFine 1.13.1 HD U E3 is running worse in comparison with OptiFine 1.12.2 HD U E2.

It's also Optifine's fault based on my tests because Vanilla 1.13.1 doesn't have those kinds of issues with movement but I still prefer using Optifine over Vanilla for obvious reasons.

If you got any more suggestions for what could be the cause, feel free to share them here.

**Comment by TheRealDannyyy** [comment]
@sp614x I think I found the bug. It keeps repeating _opengl error: 1281_ in the chat.

**Comment by sp614x** [comment]
Can you post the error log or game output?

**Comment by TheRealDannyyy** [comment]
Where can I find those outputs?

**Comment by TheRealDannyyy** [comment]
I found this information inside the "latest.log" file. It repeats at least 10 times before it stops.

`[23:12:30] [main/ERROR]: OpenGL API ERROR: 1281 (GL_INVALID_VALUE error generated. View frustum must not have a zero values of: (right-left), (top-bottom), or (zFar-zNear).)
java.lang.Exception: Stack trace
	at org.lwjgl.opengl.GLDebugMessageCallbackI.callback(GLDebugMessageCallbackI.java:39) [lwjgl-opengl-3.1.6.jar:build 14]
	at org.lwjgl.system.JNI.invokePV(Native Method) ~[lwjgl-3.1.6.jar:build 14]
	at org.lwjgl.glfw.GLFW.glfwSwapBuffers(GLFW.java:4518) [lwjgl-glfw-3.1.6.jar:build 14]
	at cgc.a(MainWindow.java:457) [cgc.class:?]
	at cfs.c(SourceFile:875) [cfs.class:?]
	at cfs.a(SourceFile:395) [cfs.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:144) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]`

**Comment by TheRealDannyyy** [comment]
@sp614x Any clue on what's going wrong here? Would appreciate if you could look into it soon.

**Comment by realjackasterisk** [comment]
posting the full log might help more

**Comment by TheRealDannyyy** [comment]
@realjackasterisk the rest of the log just has your common gameplay related stuff, I don't think it would be of much use.

**Comment by ozals** [comment]
I'd still recommend posting the whole thing

**Comment by realjackasterisk** [comment]
as a matter of fact, logs can contain more than just "common gameplay" stuff. it doesn't hurt to include as much information as possible, either.

**Comment by TheRealDannyyy** [comment]
I guess you guys are right about that. I found 3 logs, the 2nd one seems to be the largest one with the mentioned error happening multiple times (some java related errors too).

Logs:
[2018-10-21-1.log](https://github.com/sp614x/optifine/files/2506624/2018-10-21-1.log)
[2018-10-21-2.log](https://github.com/sp614x/optifine/files/2506625/2018-10-21-2.log)
[2018-10-21-3.log](https://github.com/sp614x/optifine/files/2506627/2018-10-21-3.log)

**Comment by TheRealDannyyy** [comment]
Can't reproduce the openGL errors in 1.13.2, so I assume these have been fixed. The performance issues still persist but in 1.13.2 only occur occasionally after playing for a while and last for 5-10 seconds.

I'm trying to F3 debug and screenshot it when it happens again.

**Comment by TheRealDannyyy** [comment]
@sp614x The lag still occasionally happens but it has improved in 1.13.2.

_Here is a debug screenshot I took during those "laggy" 5-10sec spikes:_
![lagpic](https://user-images.githubusercontent.com/15656049/47682354-6212a300-dbcc-11e8-9396-873bc9e1e7f4.jpg)

_Here is the latest log:_
[latest.log](https://github.com/sp614x/optifine/files/2527204/latest.log)

Would really appreciate if you guys could look into this. I'm not sure if the openGL error is at fault but it might as well be, since it mostly pops up right after those lag spikes happen.

**Comment by Strum355** [comment]
I would still keep the allocated memory at 1gb. Youre using barely over half a gigabyte, allocating more is a waste of resources and can cause longer GC pauses as the game continues. Please do not believe the all too common phrase "add more ram to Minecraft"

**Comment by Strum355** [comment]
Doesnt seem all that weird to me, the GC probably does a small sweep whenever the garbage ratio reaches a certain level, and does larger sweeps at a different interval.
Regarding flags, it probably exists

**Comment by TheRealDannyyy** [comment]
These don't look like minor sweeps to me. These seem to be major ones every, occuring every couple of seconds. Maybe that's just a think with Java but small sweeps shouldn't cause hangs like that, just jitter a bit at best in my opinion.

Anyway the performance issues still persist but I'm slowly starting to think that this might not be Optifine's fault and rather some of the recent "performance fixes" published by Mojang. Based on the snapshots they seem to be working on performance improvements still, so I'll wait for now and report back when they release some more performance updates for Minecraft stable.

**Comment by Zefferis** [comment]
@TheRealDannyyy Take a look here about the GL error

https://github.com/sp614x/optifine/issues/1950#issuecomment-432928590

**Comment by TheRealDannyyy** [comment]
@Zefferis Thanks for the info, I have no clue how to do any of that I'm afraid. If you know how stuff works, feel free to download the log files I provided above. (Not using any texture packs or mods.)

**Comment by TheRealDannyyy** [comment]
> There's some kinda issue with certain optifine features; when you're getting that error you can't have BOTH VBOs and Render Regions on, so in this case turn off Render Regions.
I will try that out the next time I play. This must be a new thing introduced with 1.13.x then because I've always been using both without any issues.

**Comment by jmuckian** [comment]
I have this, or a very similar issue as well. Minecraft w/ Optifine will usually run fine for a little while (15 minutes or so) but these huge lag spikes start happening. I've noticed that I can reproduce them while moving to or between certain blocks, but they don't need to be chunk borders.

For example, if I'm running along and I hit a lag spike at say 10,65,10, and then run a little further to 10,65,20 and hit another lag spike, I can run between these two points and every time I come to these points I get a lag spike. It's like it's loading something new at that point, but again they don't have to be chunk borders, and they aren't generally very far apart either. I'll see if I can capture a video of it tonight or something.

**Comment by TheRealDannyyy** [comment]
Seems to be fixed in latest version, closing.
