### ISSUE TITLE
All text contain unnecessary space- Optifine 1.13.1 E3

### ISSUE THREAD

**Issue by Kirill1173** [sp614x/optifine#1957]
In optifine 1.13.1 E3, text especially noticeable in faithful resource pack is found to be unnecessarily spaced out between each letter ie. Hello ---> H e l l o 
This results in some words going out of the screen and it looking extremely weird and bad
Please see it fix asap Thanks
![2018-10-21_10 27 41](https://user-images.githubusercontent.com/43733383/47269960-bad1a400-d519-11e8-94ef-27a35179da94.png)
![2018-10-21_10 28 40](https://user-images.githubusercontent.com/43733383/47269967-cb821a00-d519-11e8-8c79-fc1b4dcd7aed.png)
![2018-10-21_11 17 40](https://user-images.githubusercontent.com/43733383/47269970-d5a41880-d519-11e8-9890-ab1dfe73e55a.png)

**Comment by Kirill1173** [comment]
Also
It is not the text found within the resource pack. In default resource pack, you can notice  a slight change(since the text is low resolution). However i've run faithful 1.13 on previous beta/alpha 1.13.1 optifine version and it was normal

**Comment by realjackasterisk** [comment]
come on, dude
#1891, #1908, #1916, #1933, #1953

**Comment by Kirill1173** [comment]
Do i look as if i went back like 35 posts?

**Comment by D3monPixel** [comment]
You don't need to scroll back too much. A simple search can aid you on your search for a problem solution. It gets really annoying to see people like you who don't check for existing issues or people who are too stupid to read a new versions changelog.
