### ISSUE TITLE
Allow larger chat width

### ISSUE THREAD

**Issue by Madis0** [sp614x/optifine#1959]
On vanilla, Minecraft only allows the chat width to be from 0.0 to 1.0 which is between 40 and 320 pixels. However, on screen resolutions like 1920x1080, this only fills about half the screen. Minecraft itself does support values larger than 1.0, these just cannot be set from the client GUI.

Therefore, I suggest either

- allowing values up to max (window width)
or
- fixing the values from 0.0 to 3.0

The max could be calculated by the chat's _input field_ since that seems to fit the letters perfectly at any window size.

**Comment by sp614x** [comment]
The chat input field is always as wide as the window.
The chat itself uses virtual screen size (320x240) which usually doesn't cover the whole window depending on the aspect ratio.

**Comment by sp614x** [comment]
The chat width could be fixed to be relative to the screen size so 0.5 would be half window and 1.0 would be full window.

**Comment by sp614x** [comment]
Related #1379

**Comment by sp614x** [comment]
Fixed, coming in next preview.
