### ISSUE TITLE
Mipmapping affects certain item textures

### ISSUE THREAD

**Issue by RacerN2O** [sp614x/optifine#1961]
Using the mipmap feature makes items which have a texture resolution that isn't 2^x (16, 32, 64 etc.) blurry. This impacts resource packs with items that are given slightly different sizes (for example a 1 pixel longer sword) negatively as you have to either work around this issue, almost double the size of the sprites dimensions and sacrifice inventory icon space or tell ppl that use the resource pack to turn of mipmapping.

This seems like an oversight to me, since item textures aren't supposed to be antialiased.

**Comment by ZwipZwapZapony** [comment]
Mip-mapping works by halving texture sizes for distant objects (blurring them in the process, making them nicer to look at than very grainy things, especially the farther away you are). Half of 16 is 8, half of 8 is 4, half of 4 is 2, half of 2 is 1. But half of 17 is 8.5, and you can't have half a pixel, and you also can't just not apply mip-mapping to a texture in the way that Minecraft and OptiFine handle mip-mapping.

Either way, regardless of whether or not you use mip-mapping, it's a good idea to stick to textures which's sides are powers of two (2^X; 1, 2, 4, 8, 16, 32, 64, 128, 256, et cetera) anyway.

~

"- _you have to either work around this issue, almost double the size of the sprites dimensions and sacrifice inventory icon space or tell ppl that use the resource pack to turn of mipmapping_ -" This is wrong. You can make the image a power-of-two-sized texture (which makes the sword look smaller) and use a custom item model that enlarges it (making it just as big as before) while still using a power-of-two-sized texture.

**Comment by sp614x** [comment]
Mipmaps only work with power-of-2 textures (16, 32, 64, etc.). 
When non-power-of-2 textures are loaded vanilla disables mipmaps for all textures which causes texture flickering in distant objects.
In the same case OptiFine rescales the problematic textures to power-of-2 sizes so the mipmaps can be active. The user can disable mipmaps in the video settings and then the problematic textures would not be upscaled.

**Comment by RacerN2O** [comment]
Ah okay, that makes sense. Thanks for the explanation and sorry for the trouble.
