### ISSUE TITLE
OptiFine 1.13.1 HD U E3 won't load CTM anymore

### ISSUE THREAD

**Issue by DracoNosferatus** [sp614x/optifine#1962]
Glass.properties

code inside:
tiles=0-47
innerseams=true
connect=block

I had this working before on older beta versions but after this release it doesn't work anymore.

**Comment by sp614x** [comment]
# Update to 1.13
## Resource packs
* Rename folder "assets/minecraft/mcpatcher" to "assets/minecraft/optifine"
* In all ".properties" files replace references to "assets/minecraft/mcpatcher" with "assets/minecraft/optifine"
* Replace all numeric IDs (blocks, items, enchantments, etc.) with [names](https://minecraft.gamepedia.com/1.13/Flattening)
## Shader packs
* Add mappings for all numeric IDs used in the shader ([blocks](https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.txt#L487), [items](https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.txt#L528), [entities](https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.txt#L543), etc.)

**Comment by DracoNosferatus** [comment]
ok worked by renaming the folder thanks
