### ISSUE TITLE
[1.13.1] CTM neighbours don't respect type correctly

### ISSUE THREAD

**Issue by HanFox** [sp614x/optifine#1963]
Using preview_OptiFine_1.13.1_HD_U_E4_pre2.jar

`matchBlocks=prismarine_brick_slab:type=double`
`tiles=0 ~/ctm/hard_materials/sandstone/sandstone/1.png 2-4`
`method=ctm_compact`

You would expect that the CTM would only trigger if all the blocks are double slabs, however, the CTM on the blocks which are already double will trigger when a top or bottom slab is placed beside it.

Without the neighbour:
![2018-10-23_12 26 38](https://user-images.githubusercontent.com/1781312/47357566-ef329500-d6be-11e8-86c7-44256156569d.png)

With the neighbour:
![screenshot_20181023_122920](https://user-images.githubusercontent.com/1781312/47357667-52242c00-d6bf-11e8-99ad-b36da89cbc46.png)

**Comment by sp614x** [comment]
Default connect type when `matchBlocks` is used is `block`, so blocks would be connected by block ID independent of the blockstate properties.
`connect=state` will only connect when the blocks have identical ID and properties.
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/ctm.properties#L102
