### ISSUE TITLE
[1.13.2 E4 pre2] Framerate drops considerably when switching to resolution higher than 1920x1080 (widescreen)

### ISSUE THREAD

**Issue by MSpaceDev** [sp614x/optifine#1964]
Using OptiFine 1.13.2 HD U E4 pre2

When I run the game on my first monitor (1920x1080), the game runs perfectly smooth 100+ FPS.
The moment I drag it over to my widescreen monitor (2560x1080) the framerate drops to about 10-15FPS.

This occurs both `in-world` and in the `main menu.`
Also, this does not happen in `Vanilla 1.13.2`.
I opened the game with Optfine 3 times, and every time, I got consistent frame rate drops when switching monitors.
Switching to Vanilla 1.13.2 made the problem not persist anymore.

**Comment by HopefulFire** [comment]
Do you have screenshots?

**Comment by sp614x** [comment]
Are both monitors running on the same GPU?
Can you post debug screens from both monitors (2 x vanilla and 2 x optifine)?
