### ISSUE TITLE
[1.13.1 E3] Grid pattern on blocks when antialiasing is turned on

### ISSUE THREAD

**Issue by DMZ5** [sp614x/optifine#1966]
Turn of antialiasing beyond 2, open any world, look at the ground around you.

The lines get thicker the farther it gets from the player

![2018-10-23_19 51 24](https://user-images.githubusercontent.com/44413392/47383854-828abb00-d6fd-11e8-8dd6-4ab9385bcbf9.png)

**Comment by ozals** [comment]
I think this is because of mipmap quality, if you put it at the best mipmap settings it should look better

**Comment by DMZ5** [comment]
> I think this is because of mipmap quality, if you put it at the best mipmap settings it should look better

**Comment by DMZ5** [comment]
that fixed it thanks
