### ISSUE TITLE
Can't launch with Java 11 (1.13.1-E3)

### ISSUE THREAD

**Issue by TheGoatOnABoat** [sp614x/optifine#1967]
Despite the changelog saying it was fixed, I can't launch the newest version of optifine with Java 11. I keep getting crashes as soon as I click play.

**Comment by ozals** [comment]
are you on linux? or using multimc?

**Comment by TheGoatOnABoat** [comment]
No, normal mc launcher on Windows.

**Comment by ozals** [comment]
ahhh I just noticed java 11, right now only java 8 works with optifine

**Comment by TheGoatOnABoat** [comment]
That's weird, it said on the changelog that it should work with Java 9+ now.

**Comment by ozals** [comment]
I'd still use java 8 anyway

**Comment by sp614x** [comment]
Updated launchwrapper by Runemoro, should be compatible with Java 8, 9, 10:
https://github.com/sp614x/optifine/issues/1739#issuecomment-417884419

**Comment by sp614x** [comment]
Fixed installer to use launchwrapper-2.0
All new versions are going to use the new installer.
