### ISSUE TITLE
Custom Sky and Custom Color 

### ISSUE THREAD

**Issue by Trackasama** [sp614x/optifine#1970]
With Optifine 1.13.2 Pre1 and Pre2. I can't active my custom sky and my custom color. With shaders or not.

**Comment by realjackasterisk** [comment]
are you using the mcpatcher folder?

**Comment by Trackasama** [comment]
In my resource pack ? (Ressource Pack --> Assets --> minecraft --> mcpatcher) Yes. My custom sky and custom colors worked before Optifine 1.13.1 HD U E3.

**Comment by ozals** [comment]
rename the mcpatcher to optifine, in pre5 of 1.13.1 the mcpatcher folder moved to optifine, please read the changelogs in the future
