### ISSUE TITLE
Launchwrapper 2.0 Not Working with Servers

### ISSUE THREAD

**Issue by TheGoatOnABoat** [sp614x/optifine#1971]
I installed Launchwrapper 2.0 to use optifine with Java 11, but now I can't go on servers as they keep indefinitely pinging.

**Comment by ozals** [comment]
Try with java 8

**Comment by TheGoatOnABoat** [comment]
Yes, it can.

**Comment by sp614x** [comment]
Looks like a firewall problem, it may be blocking Java 11 from connecting to the servers.
Firewalls use rules per executable, so Java 8 and Java 11 can have different rules.

**Comment by TheGoatOnABoat** [comment]
I tried disabling my firewall and it still didn't work.

**Comment by sp614x** [comment]
OptiFine doesn't change anything related to network connections.
If java 8 works and java 11 doesn't work then the OS is handling them in a different way (firewall rules or something else).
