### ISSUE TITLE
1.12.2 crash during texture stitching

### ISSUE THREAD

**Issue by Sora-Canstavia** [sp614x/optifine#1974]
one of the players on my server has been using Optifine to boost his FPS, but recently he's been unable to launch his game due to "texture too big" errors, after uninstalling Optifine he was able to launch without issue.

I Have three crash-reports from him here:
https://pastebin.com/69CYBvDM
https://pastebin.com/QK4wRyUu
https://pastebin.com/gN9VHfyu

He's using Optifine HD U E2 and is using default minecraft textures, I Have a full modlist here as well: https://pastebin.com/gmU40Jwd
Any help in this matter is very much appreciated.

**Comment by sp614x** [comment]
This doesn't seem right: `atlasMax: 512x512`
The maximum texture size should be 16k x 16k for all modern GPUs. 
Either the driver or the GPU itself has a problem.
Disabling connected textures should fix the problem for now.
