### ISSUE TITLE
Sun/moon only visible in the corner of the screen at lower render distances (1.13.2)

### ISSUE THREAD

**Issue by Regnander** [sp614x/optifine#1975]
_(This may or may not be identical to #1786, but I decided to create a new issue just in case they're not related.)_

When I set my render distance to 2 chunks in 1.13.2, the sun/moon is not visible in vanilla and OptiFine. However, if you try to look at the sun/moon in the corner of the screen, you can see it in OptiFine but not in vanilla.

In 1.12.2, you can see the sun/moon with Optifine no matter what render distance you have.

### 1.13.2
  | Vanilla | OptiFine
--|--|--
Looking directly at the sun/moon<br>(Render dist.: 4) | ![2018-10-25_20 59 21](https://user-images.githubusercontent.com/17113053/47524465-fadab300-d89a-11e8-9e93-287578473b19.png) | ![2018-10-25_20 55 40](https://user-images.githubusercontent.com/17113053/47524303-8c95f080-d89a-11e8-93c8-6842ff9b0771.png)
Looking directly at the sun/moon<br>(Render dist.: 2) | ![2018-10-25_20 59 45](https://user-images.githubusercontent.com/17113053/47524497-12b23700-d89b-11e8-9bad-919357819641.png) | ![2018-10-25_20 55 57](https://user-images.githubusercontent.com/17113053/47524338-a59ea180-d89a-11e8-9b25-d93cd04dac01.png)
Looking at the sun/moon in the upper-left corner of the screen<br>(Render dist.: 2) | ![2018-10-25_21 18 28](https://user-images.githubusercontent.com/17113053/47524676-8e13e880-d89b-11e8-969a-89e1b514e329.png) | ![2018-10-25_20 56 14](https://user-images.githubusercontent.com/17113053/47524362-b51dea80-d89a-11e8-973c-91179fb62682.png)

### 1.12.2
  | Vanilla | OptiFine
--|--|--
Looking directly at the sun/moon<br>(Render dist.: 5) | ![2018-10-25_21 33 07](https://user-images.githubusercontent.com/17113053/47529048-0cc25300-d8a7-11e8-899e-00f00a3bbc4b.png) | ![2018-10-25_21 31 56](https://user-images.githubusercontent.com/17113053/47528945-c40a9a00-d8a6-11e8-8492-b2dae7b7d82c.png)
Looking directly at the sun/moon<br>(Render dist.: 2) | ![2018-10-25_21 32 58](https://user-images.githubusercontent.com/17113053/47529129-38453d80-d8a7-11e8-8078-5d2dd62c35a4.png) | ![2018-10-25_21 32 05](https://user-images.githubusercontent.com/17113053/47529132-3bd8c480-d8a7-11e8-88c2-a367d4d572d3.png)

**Comment by sp614x** [comment]
Fixed, coming in E5_pre1.
