### ISSUE TITLE
[1.13.2] Huge FPS spikes from memory garbage collector

### ISSUE THREAD

**Issue by lyncorbray** [sp614x/optifine#1977]
### Problem
On ocassion the game starts suffering enormous drops in the FPS, according to the lagometer, caused by the memory garbage collector.
_Example:_
![2018-10-26_17 57 26](https://user-images.githubusercontent.com/44164928/47578311-5cf1f180-d949-11e8-85b3-a8e983dc370c.png)
With a render distance of 8 (as seen in the image) the game usually plays out perfectly, however this stops when I generate more world. With higher render distances this happens even when standing still.

Previous to 1.13 Minecraft ran fine on my PC with 16chunk view and even during the snapshots. I have no idea what the cause for this is or if there is any thing I can do to solve it.

The game becomes obviously unplayable for a while and then goes back to normal. I have tried altering all video settings and with the exception of reducing render distance to 2 none seem to work.

If there is any more information I need to post please say so.
I hope there is a fix for this,
Thank you for your time.

**Comment by ichttt** [comment]
Maybe you should allocate 1gigabyte of memory to minecraft instead of hald a gig, so the gc doesn't have to work as hard to free memory

**Comment by lyncorbray** [comment]
> Maybe you should allocate 1gigabyte of memory to minecraft instead of hald a gig, so the gc doesn't have to work as hard to free memory

These are my arguments:
-Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M

As you can see I have the default that allocates 2 gigabites
For some reason the game displays 512 megabites. Perhaps this is at the core of the problem...

**Comment by MauveCloud** [comment]
> These are my arguments:
-Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M

> As you can see I have the default that allocates 2 gigabites
For some reason the game displays 512 megabites. Perhaps this is at the core of the problem...

Check your logs for additional arguments that may come from elsewhere (e.g. environment variables).  Don't ask me why those can override the command-line arguments, though.  IMO that's backwards.

**Comment by lyncorbray** [comment]
> 
> Check your logs for additional arguments that may come from elsewhere (e.g. environment variables). Don't ask me why those can override the command-line arguments, though. IMO that's backwards.

Thank you.

I have checked said logs but unfortunately can´t seem to find any arguments overriding the command-line ones. If anyone has a better idea of what to search for, this is my latest log.

[latest.log](https://github.com/sp614x/optifine/files/2520146/latest.log)

**Comment by sp614x** [comment]
According to Java the memory limit is 512MB.
If the JVM arguments are `-Xmx2G` then there is a problem between the launcher and the JVM.
This is not related to OptiFine.

**Comment by lyncorbray** [comment]
Huge thanks to the people that tried to help. I have now been able to identify the exact problem and fix it.
