### ISSUE TITLE
Kernel panic while using Optifine HD U E4 for 1.13.2 [Crash]

### ISSUE THREAD

**Issue by AnotherWryTeenager** [sp614x/optifine#1978]
So far I've had multiple kernel panics - "_Graphics firmware encountered an exception_" - and the only thing connecting them is that I've been running Optifine U E4 for 1.13/1.13.2

Normal minecraft runs fine, but I'm working on an Optifine-dependent resource pack so this is rather frustrating, especially when my entire computer randomly shuts down.

Full Panic Report: [pastebin link](https://pastebin.com/E9xXqpt6)

**Comment by sp614x** [comment]
This is driver/java specific. OptiFine can't fix it.
You can try to update the graphics driver, enable/disable vbos, enable/disable render regions.

**Comment by AnotherWryTeenager** [comment]
Ok - good to know.
Thanks for the speedy reply!
