### ISSUE TITLE
HD U B7 on 1.10 - Issues with Chisels & Bits

### ISSUE THREAD

**Issue by Amaxter** [sp614x/optifine#198]
https://github.com/AlgorithmX2/Chisels-and-Bits/issues/60

**Comment by sp614x** [comment]
OptiFine C1 for 1.10 should be compatible with Forge #2000

**Comment by sp614x** [comment]
Fixed in Chisel & Bits: https://github.com/AlgorithmX2/Chisels-and-Bits/issues/60#issuecomment-230075634
