### ISSUE TITLE
Mipmaps make blurred textures

### ISSUE THREAD

**Issue by jofffu** [sp614x/optifine#1982]
When i use optifine some textures with certain resolutions (that are not 2^n like for example 48) get blurred. Vanilla supports other resolutions. 

Test Texturepack (i used planks textures):
[Optifine Mipmap Bug.zip](https://github.com/sp614x/optifine/files/2521620/Optifine.Mipmap.Bug.zip)

Optifine Mipmap 4x:
![optifine mipmap 4x](https://user-images.githubusercontent.com/44521380/47601988-6a09f180-d9d8-11e8-95b1-56c2aef80401.png)
Optifine Mipmap off:
![optifine mipmap off](https://user-images.githubusercontent.com/44521380/47601989-6a09f180-d9d8-11e8-8270-2823eb3577b0.png)
Vanilla Mipmap 4x
![vanilla mipmap 4x](https://user-images.githubusercontent.com/44521380/47601990-6a09f180-d9d8-11e8-92dc-a2fa817ad4db.png)
Vanilla Mipmap off:
![vanilla mipmap off](https://user-images.githubusercontent.com/44521380/47601991-6a09f180-d9d8-11e8-9970-dc5bad262144.png)

**Comment by sp614x** [comment]
Mipmaps can only work with power-of-2 textures.
Vanilla "supports" non-power-of-2 textures by reducing or disabling mipmaps.
OptiFine rescales non-power-of-2 textures to power-of-2 sizes so the mipmaps can work correctly.
If the mipmaps are reduced ot disabled OptiFine will not rescale the textures.

Vanilla Mipmaps 4x (mipmaps are disabled)
![image](https://user-images.githubusercontent.com/16635441/47602584-48613800-d9e1-11e8-9b8c-fa068be8577f.png)

OptiFine Mipmaps 4x (mipmaps working correctly)
![image](https://user-images.githubusercontent.com/16635441/47602590-58791780-d9e1-11e8-830d-f8c36f357167.png)

**Comment by jofffu** [comment]
Thanks for the explanation. Is there any possibility to disable mipmaps for individual textures (if not can you create that feature?)? 

Another thing i found out:
Mipmaps also apply to item textures in inventory that are not 2^n. I dont think this makes sense because as far as i understand mipmaps are only used for very downscaled textures in the distance. Can you disable them for inventories?

One last question: what do you mean with "reduced mipmaps"?

**Comment by sp614x** [comment]
Mipmaps are also used for slanted textures and for all cases where several texture pixels have to be merged in one screen pixel.
Mipmaps at level 4 are full, the actual mipmap leve may be higher depending on the resource pack.
Mipmap level below 4 are reduced and do not apply full smoothing.
