### ISSUE TITLE
Crooked pointer

### ISSUE THREAD

**Issue by EdwardTheGamer** [sp614x/optifine#1986]
The issue only occurs using the scale level 1 and 3.
I'm using OptiFine 1.13.2 HD U E4 in 1920x1080 resolution.

![2018-10-27_23 10 18](https://user-images.githubusercontent.com/42244508/47609394-d3701b80-da3d-11e8-906f-c4094ddcce55.png)
![2018-10-27_23 10 27](https://user-images.githubusercontent.com/42244508/47609395-d3701b80-da3d-11e8-9b96-509e16e3966f.png)

**Comment by ozals** [comment]
are you using any resource packs?

**Comment by EdwardTheGamer** [comment]
> are you using any resource packs?
No, a completely clean version of OptiFine.

**Comment by EdwardTheGamer** [comment]
> are you using any resource packs?

**Comment by EdwardTheGamer** [comment]
I accidentally closed the report

**Comment by realjackasterisk** [comment]
so just... re-open it??

**Comment by EdwardTheGamer** [comment]
It's a Minecraft Vanilla bug: https://bugs.mojang.com/browse/MC-122846

**Comment by sp614x** [comment]
Known vanilla problem, there are several bugs about the cursor being skewed in different ways, sometimes depending on the GUI scale or the screen size.
