### ISSUE TITLE
CIT documentation - No mention of tile=

### ISSUE THREAD

**Issue by leewdch** [sp614x/optifine#1988]
There is no mention of the `tile=` rule I found in my a resourcepack. Apparently it uses the .properties root path as starting point to check for textures so the `texture=` becomes useless since it needs absolute path to work. Is the `tile=` a more general rule that doesn't apply to cit only?

**Comment by leewdch** [comment]
Same issue for `matchItems=`. Is there a reason why there are missing rules in the documentation? Are these legacy rules?

**Comment by sp614x** [comment]
The "tile" and "source" are legacy synonyms for "texture", they are not in the docs because they are deprecated and shouldn't be used. Same for "matchItems", it is a synonym of "items".
The synonyms work identically, no different behaviour.

**Comment by sp614x** [comment]
Textures can be specified in many different ways (relative, absolute...)
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/properties_files.txt#L29
