### ISSUE TITLE
[1.13.2] grid based custom colors

### ISSUE THREAD

**Issue by con-reforged-dev** [sp614x/optifine#1989]
After updating my pack to the 1.13 Minecraft with replacing ids with names and updating the mcpatcher folder to be optifine instead, it seems like grid-based custom colors are not functional on my end.

Here is a screenshot for the file setup for custom colors as an example https://i.imgur.com/EzCFXR8.png
as far as I can tell this should work if nothing changed about how it worked in the past.

Instead, it using the default colormap regardless of what I do to the custom colors setup even the most basic ones don't get used by the game. 

I made extra sure that the settings in-game are also enabled as well to make sure. I also checked through the game output and it seems like the grid format colormaps and their properties are being completely ignored while others like the pine.png ones are applied. 
The same is true for custom colors in the color.properties file referring to colormaps using the grid format. 
As seen in the screenshot the grid-based colormaps are not being loaded or even recognized https://i.imgur.com/3dt2Vjc.png

If there is something unclear I am happy to provide more information
Monsterfish_

**Comment by sp614x** [comment]
Resource pack link (only the grid colormaps part)?

**Comment by con-reforged-dev** [comment]
here you go i put in everything colormap related so you can see how it loads the "normal" colormaps and not the grid-based ones http://www.mediafire.com/view/xct9yedrdj4yd8g

**Comment by sp614x** [comment]
The correct format is `palette.block.<>` not `palette.blocks.<>`:
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/biome_palettes.txt#L122

**Comment by sp614x** [comment]
The biome IDs in 1.13 are the same as 1.12 (only some biome names have changed). The grid colormaps should work identically in 1.13.

**Comment by con-reforged-dev** [comment]
Yeah, thanks a bunch for the help it's working now .. it seems like the biomes have shifted a little bit through but I can get that fixed no problem 
Cheers
