### ISSUE TITLE
Problem in ctm.properties doc

### ISSUE THREAD

**Issue by Dovahrt** [sp614x/optifine#1993]
In the ctm.properties doc (https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/ctm.properties) it is stated:

(Optional) Biome and height restrictions.  Limit the mod to only certain
biomes or height ranges.  **See mob.properties for a list of valid biome names.**
The legacy properties "minHeight" and "maxHeight" are also recognized.
biomes=<biome list>
heights=<height ranges>

But there is not a **mob.properties** doc where to see a list of valid biome names. The list of valid biomes could be integrated into the ctm.properties doc itself.

**Comment by sp614x** [comment]
The biomes are the standard minecraft biomes:
Mod biomes can also be used with full name `<mod>:<biome>`.
https://minecraft.gamepedia.com/Biome#Biome_IDs

The `ctm.properties` have to be updated.

**Comment by sp614x** [comment]
Updated `ctm.properties`.
