### ISSUE TITLE
[1.13.2 HD U E4 & E5 pre1] Game autosaving regardless of autosave interval setting

### ISSUE THREAD

**Issue by Namelesswonder** [sp614x/optifine#1995]
### Issue:
Every 45 seconds the game autosaves, regardless of the autosave interval setting.
Setting the autosave interval to any setting does nothing. The game does not save at the specified interval and only saves every 45 seconds.

#### Game Version Used:
1.13.2

#### OptiFine Versions Used:
1.13.2 HD U E4
1.13.2 HD U E5 pre1

##### OS:
Fedora 28, kernel 4.18.16-200.fc28.x86_64
##### Java Versions Used:
OpenJDK 1.8.0_181-b15 (launchwrapper 1.12 and 2.0)
OpenJDK 11.0.1+13 (launchwrapper 2.0)

### Observations:
Happens precisely every 45 seconds, however, when the game is paused this timer is halted, and then resumes after unpausing.
This saving is not written to the output.
Saving every 45 seconds during gameplay seems to be a behavior the base game does.

##### Comments:
I have not tested if this behavior happens on older game versions, or with older OptiFine versions, or on other OSes. I have only tested with the specified game version, the specified OptiFine versions, and the specified Java versions.

**Comment by Regnander** [comment]
How did you measure the save intervals? I want to check if it is the same way on my PC.

**Comment by Namelesswonder** [comment]
> How did you measure the save intervals? I want to check if it is the same way on my PC.

Easiest way is to just watch the lagometer, you'll notice the lag spike from saving, and is very noticeable if you have a high render distance.
![savespike](https://user-images.githubusercontent.com/12788603/48367398-8e272d00-e67e-11e8-89af-2dcfcdc67a33.png)
Running a stopwatch or watching a clock and the spike always happens every 45 seconds in-game for me.

The more technical measurements can be done with something like inotifywait to watch the inodes for if they are being opened and written to, in case your lagometer is very spiky from the GC.
![inotifywait](https://user-images.githubusercontent.com/12788603/48367664-62f10d80-e67f-11e8-9c15-f096ea871946.png)

Or using VisualVM to watch the File IO Thread (also great because CPU time used for the FileOutputStream class measures about how long each spike is).
![visualvm](https://user-images.githubusercontent.com/12788603/48367849-f9bdca00-e67f-11e8-927c-18f2d3ae06bc.png)

**Comment by sp614x** [comment]
The autosave interval and the lag spike on autosave are fixed.
Coming in next preview.
