### ISSUE TITLE
Glass block dropped items render shulker boxes invisible

### ISSUE THREAD

**Issue by Jamdog** [sp614x/optifine#1998]
As the title suggests, if you drop a glass block on the ground in front of a shulker box, it allows you to see through the shulker box.  The image below illustrates this.

Server: Spigot 1.13.1
Client: Vanilla 1.13.1 with only Optifine installed
Optifine version: 1.13.1-Optifine_HD_U_E3

![2018-11-01_07 25 29](https://user-images.githubusercontent.com/94101/47838760-3e0bb900-dda8-11e8-9649-f51a63b72faa.png)

**Comment by DataCrusade** [comment]
This is a rendering order issue and it's not an optifine issue specifically.

**Comment by Regnander** [comment]
https://bugs.mojang.com/browse/MC-9553

**Comment by sp614x** [comment]
This is a vanilla problem, not related to OptiFine.
