### ISSUE TITLE
Conduits do not grant enhanced underwater vision

### ISSUE THREAD

**Issue by LTK1** [sp614x/optifine#1999]
![Without Optifine](https://user-images.githubusercontent.com/34627908/47945986-7d501c00-df06-11e8-912f-1a186ca0c9eb.png)
![With Optifine](https://user-images.githubusercontent.com/34627908/47945990-87721a80-df06-11e8-9c8b-de9b25ef04c9.png)

Being near a conduit is supposed to grant a night-vision-like buff underwater, but it doesn't work with Optifine. Night vision potions, however, work fine.

**Comment by LTK1** [comment]
Yes, that seems to affect it, deleting optifine/lightmap/world0.png restores visibility. Does this texture need to be modified to solve this?

**Comment by sp614x** [comment]
Fixed, coming in next preview.
