### ISSUE TITLE
minecraft version not found you need to start the version 1.13.2 manually once

### ISSUE THREAD

**Issue by CrisuPoland** [sp614x/optifine#2000]

**Comment by MastaNub** [comment]
Answer is in the title ♿️

**Comment by ozals** [comment]
what is this issue????

**Comment by Etrainquandt17** [comment]
I'm not sorry, but seriously. Is this what the world is going to be like? Full of stupid people? Like, really? What even is this. You have to run Minecraft 1.13.2 once 🤦‍♂️

**Comment by sp614x** [comment]
This is correct, you have to start the version 1.13.2 manually once.
