### ISSUE TITLE
CEM donkey & mule models don't render in game.

### ISSUE THREAD

**Issue by Danchuc** [sp614x/optifine#2006]
-Unlike Horse Model that renders fine in game. Donkey and Mule that use same body part names as horse don't render in game (are invisible), debug log doesn't find anything wrong with resource pack that contains these models. Log spams **"can't render entity**" while in game.
-My custom models change legs and tail ... for horses, donkeys and mules. Skeleton and zombie horses might also need fixing but idk.
- OptiFine 1.13.2 HD U E5 pre1
[BitBetterHorseOld-1.0.0.zip](https://github.com/sp614x/optifine/files/2545038/BitBetterHorseOld-1.0.0.zip)

**Comment by sp614x** [comment]
Fixed CEM for mule and donkey. 
Doesn't crash anymore, but the model ears are missing.

![image](https://user-images.githubusercontent.com/16635441/48702401-211d1580-ebf1-11e8-8fab-d156710f76cd.png)

**Comment by sp614x** [comment]
Fixed, coming in next preview.

![image](https://user-images.githubusercontent.com/16635441/48775850-898df480-ecce-11e8-9098-da94157d6292.png)
