### ISSUE TITLE
Better Snow - Support for more blocks

### ISSUE THREAD

**Issue by Regnander** [sp614x/optifine#2015]
First and foremost, I want to address that Better Snow doesn't apply snow layers on upside-down stairs and upper slabs, which has been possible since 1.12:

![2018-11-08_23 37 16](https://user-images.githubusercontent.com/17113053/48231830-d52bce80-e3af-11e8-9641-16ffbe5f0ae8.png)

Here are the blocks / block entities I found that currently lacks support for Better Snow:

- Anvils
- Banners
- Buttons*
- Cobweb
- Chests (regular, trapped, ender)
- Chorus fruits
- Chorus plants
- Doors**
- Hoppers
- Ladders
- Levers (when placed on walls/ceiling; this already works for levers on the ground)
- Item frames (when placed on walls/ceiling **only**)
- Paintings
- Sea pickles***
- Signs
- Skulls
- Turtle eggs
- Vines

*Only when placed on walls/ceiling. Other redstone-related components (redstone dust, pressure plates, rails, etc.) would only be buried beneath the snow layer since they can only be placed on the ground.

**It would be nice if snow is applied under the door only when a snow layer is placed on the block facing away from the door:

![ezgif-4-1411556a3fc2](https://user-images.githubusercontent.com/17113053/48233967-c0533900-e3b7-11e8-9755-0377cbeb6215.gif)

***I understand why this isn't implemented for torches and end rods, since they [emit light with a light level above 11 which melts snow](https://minecraft.gamepedia.com/Snow#Melting), but the sea pickle isn't lit unless it's underwater and snow cannot be placed underwater anyway.

**Comment by sp614x** [comment]
Coming in next preview.

**Comment by Regnander** [comment]
I found some z-fighting when placing upside down stairs next to a snow layer in E5 pre3.

![2018-11-21_03 34 59](https://user-images.githubusercontent.com/17113053/48815328-7286eb00-ed3e-11e8-875d-9f0c9fdc6d8f.png)
