### ISSUE TITLE
Anisotropic Filtering has a weird grid pattern.

### ISSUE THREAD

**Issue by popa1234** [sp614x/optifine#2016]
Anisotropic Filtering seems to have this grid effect on far away blocks. Present in the newest versions.
![capture1](https://user-images.githubusercontent.com/44902140/48270569-07d2d700-e443-11e8-9140-4b8df3f36a05.PNG)

**Comment by Regnander** [comment]
In #1966, this was fixed by increasing the values of the mipmap options. Does it solve the problem for you?

**Comment by popa1234** [comment]
Results with set settings. Same settings as in original image as well.
![capture](https://user-images.githubusercontent.com/44902140/48317096-9f782700-e5f5-11e8-8c37-1fea3f1c7133.PNG)
![capture1](https://user-images.githubusercontent.com/44902140/48317103-b74fab00-e5f5-11e8-916a-4b40d007d461.PNG)

**Comment by sp614x** [comment]
There is an opengl error
![image](https://user-images.githubusercontent.com/16635441/48674121-422a2b80-eb49-11e8-979d-c9decd6810a4.png)

**Comment by sp614x** [comment]
Can you post the error log (game output)?

**Comment by sp614x** [comment]
Fixed, coming in next preview.
