### ISSUE TITLE
Dynamic Lights is much slower than it was in 1.12

### ISSUE THREAD

**Issue by popa1234** [sp614x/optifine#2017]
When dynamic lights is set to fancy it seems to struggle with updating torch light when walking in the dark. Much more so than it earlier has.

**Comment by sp614x** [comment]
The chunk updates in 1.13 are about 2x slower than in 1.12. Mostly to do with waterlogging.
Dynamic Lights works by updating the chunks around the player and is affected by the chunk update speed.
