### ISSUE TITLE
[1.12.2] Memory leak on Alt-Tab with fullscreen and certain shaders packs

### ISSUE THREAD

**Issue by Cyphall** [sp614x/optifine#2019]
I'm experiencing some huge memory leaks while alt tabing using **OptiFine 1.12.2 HD U E2** with some shaders packs enabled (does not happens with all packs).

It happens only in fullscreen, with [SEUS Renewed 1.0.0](https://sonicether.com/download/seus-renewed-v1-0-0/) (biggest memory leak, up to 500 MB/s increase) and [Sildur's Vibrant Shaders 1.18 High-Motionblur](https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1291396-1-6-4-1-13-2-sildurs-shaders-pc-mac-intel) (smaller memory leak but still present) but **not** with [KUDA Shaders 6.1](https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1293662-kuda-shaders-v6-1-legacy).

For some reasons, there is no memory leak if I set my max FPS to 135 or bellow but it starts happening at 140, and the higher the FPS limit is, the faster the RAM increases, with around 5 MB/s at 140 FPS and 500+ MB/s at Unlimited FPS for SEUS Renewed.

I've tried to make a new .minecraft install and leaving as much options as I could to default (basically just installing optifine and selecting the shaders pack in-game) and it is still happening.
So far, I don't have this issue in 1.13.

**Comment by sp614x** [comment]
Does it happen in all worlds?
When the memory allocation increases, do you get the GC lag spikes (orange in the lagometer) much more often?

**Comment by Cyphall** [comment]
So far it happens both on normal worlds and superflat.

I think I wasn't very clear sorry: the leak starts when I alt-tab from the game (with fullscreen enabled only) and the memory increases while the game is unfocused.
When I go back to the game, it freezes for some seconds, depending of the amount of leaked memory (freeze for ~3sec with a 1GB leak and ~15sec with a 4.5 GB leak).
Also, it doesn't happens in menus, only when a world is loaded.

**Comment by Cyphall** [comment]
Here are my specs:
Intel Core i5-7600K @4.6GHz
Nvidia GTX 1070
16GB Corsair Vengeance @3000MHz (XMP on)
Samsung 850 Evo

**Comment by sp614x** [comment]
Should be fixed in E5_pre2.
