### ISSUE TITLE
Question: "And" Statements

### ISSUE THREAD

**Issue by Reper516** [sp614x/optifine#2020]
I was wondering there was a way to create an "and" statement in the .properties file.
For example here is my code.

type=item
items=278
texture=diamond_pickaxe_M&U.png
nbt.display.Lore.*=ipattern:\u00a7bMagic Touch *
nbt.display.Lore.*=iregex:(\u00a7d\u00a7lEternal|\u00a7bUpgrade) .*

I want it so that if the item (pickaxe) has the lores Magic Touch * AND either Eternal Upgrade or Upgrade * it will apply the texture diamond_pickaxe_M&U.png
Is there a way to do this?

**Comment by Reper516** [comment]
Thank you so much! It works perfectly! Thank you, Thank you, Thank you!!!!!!!!!!

**Comment by Regnander** [comment]
You're welcome. I'm glad to hear that!
You can click the "Close issue" button below to mark this issue as solved.
