### ISSUE TITLE
[Meta] New rendering engine in 1.14

### ISSUE THREAD

**Issue by Madis0** [sp614x/optifine#2021]
Minecraft 1.14 will have a new rendering engine called Blaze3D. 
This will likely affect Optifine by a lot so I thought I should give an early heads-up with details as we learn them so you can plan your changes accordingly.

>The Java team will be opening up more libraries soon and we'll update this article when they do. One library under consideration is Blaze3D - a complete rewrite of the render engine that we're aiming to implement for 1.14.

[Source](https://minecraft.net/en-us/article/programmers-play-minecrafts-inner-workings) [(via)](https://minecraft.gamepedia.com/1.14#cite_ref-5)

>The question about the VBO option in the latest snapshots came up a few times. It's been removed on purpose [as of 18w45a] and VBO will now always be used. This is one of the first side effects of the ongoing work we do to improve the rendering engine.

[Source](https://twitter.com/SeargeDP/status/1060455384471793664) [(via)](https://minecraft.gamepedia.com/18w45a#cite_ref-2)

**Comment by sp614x** [comment]
The Blaze3D engine is currently in the Minecraft JAR file and is obfuscated. It is hard to say how different it would be from the current engine. Based on performance and general behaviour it should be working in a similar way.

The removal of VBO option may be more complex to fix.

Lately Mojang has increased the minimum system requirements to OpenGL 4.4. The latest 1.14 snapshot still runs on GPUs supporting only OpenGL 4.0 so it is not clear if the requirement is hard.

**Comment by Madis0** [comment]
18w46a:

> Added support for directional opacity of blocks (used by slabs, stairs, snow layers, non-full-block dirt-related blocks and extended piston base blocks)
> Removed option to turn off VBO in the game settings. VBO are now always used.

[Source](https://minecraft.net/en-us/article/minecraft-snapshot-18w46a)

[MC-92: "Slab and stairs lighting incorrect"](https://bugs.mojang.com/browse/MC-92) fixed

**Comment by asiekierka** [comment]
@sp614x They still support the HD4000 in your quote, which is limited to OpenGL 4.0 (on Windows) and OpenGL 4.2 (on Linux - but we can use the Windows value, as they can't just force users to use Linux), and due to a high proliferation of Ivy Bridge and Haswell integrated GPU devices still in use I don't think they'll jump up to requiring 4.4 quite yet.

**Comment by yannicklamprecht** [comment]
A sub version of lwjgl 3 supports vulkan and metal as a backend. So this jump would only affect device that doesn't support all three technologies.

**Comment by asiekierka** [comment]
>So this jump would only affect device that doesn't support all three technologies.

"Supports" doesn't mean "uses". Coming back to the HD4000 - it only supports Vulkan on Linux; not Windows.

**Comment by Madis0** [comment]
Not exactly the OP subject, but probably relevant to Optifine additions in resource packs:

>19w06a: Particles are now broken up into individual textures rather than being in particles.png

[Source](https://minecraft.net/en-us/article/minecraft-snapshot-19w06a)

**Comment by asiekierka** [comment]
So we finally have more information.

As of 19w08a, Mojang shows a warning message linking to [here](https://help.mojang.com/customer/portal/articles/325948?ref=game) under the following conditions:

* OpenGL 2.0+ is NOT present, AND
* OpenGL 2.1+ is NOT present AND vertex/fragment shader/shader object 

Their warning message is as such:

```
  "title.oldgl1": "Old graphics card detected; this may prevent you from",
  "title.oldgl2": "playing in the future as OpenGL 2.0 will be required.",
```

Therefore, we can assume that the new rendering engine will require OpenGL 2.0+. I guess I've started believing in Blaze3D.

**Comment by sp614x** [comment]
Most probably means that VBOs would be required (no way to turn VBOs OFF).

**Comment by Madis0** [comment]
19w09a:

- Particles have been split up to customize separately 

[Post](https://minecraft.net/en-us/article/minecraft-snapshot-19w09a)
[Wiki](https://minecraft.gamepedia.com/19w09a)

19w11a:

- Languages and (previously) resource packs use a loading bar view (could be used for intense graphics settings?) 
- Menu items can be navigated with Tab/Shift-Tab/Arrow keys 
- Chat background opacity can be adjusted 
- Backgrounds can be applied to texts like actionbar

[Post](https://minecraft.net/en-us/article/minecraft-snapshot-19w11) [Wiki](https://minecraft.gamepedia.com/19w11a)

19w12a:

- Glass is now a solid block (but doesn't suffocate as of 19w12b)
- Totem of Undying effect uses the same model as item 
- Several hitboxes changed, including player sneak 
- Sound system has been rewritten

[Post](https://www.minecraft.net/en-us/article/minecraft-snapshot-19w12a) [Wiki](https://minecraft.gamepedia.com/19w12a)

**Comment by Madis0** [comment]
19w13a:
* Accessibility options submenu that duplicates various options

[Post](https://minecraft.net/en-us/article/minecraft-snapshot-19w13a) [Wiki](19w13a)

19w14a:
* Debug screen indicates sounds, ambient sounds have a limit of 247 and jukeboxes 8
* Players can crouch to 1,5 block height and crawl to 1 block height (if a block is placed to their head)

[Post](https://minecraft.net/en-us/article/minecraft-snapshot-19w14a0) [Wiki](https://minecraft.gamepedia.com/19w14a) 

Pre-Release 2:
* Mouse settings submenu under Controls with old and new options

[Post](https://www.minecraft.net/en-us/article/minecraft-1-14-pre-release-1) [Wiki](https://minecraft.gamepedia.com/Java_Edition_1.14_Pre-Release_2)

**Comment by redg3ar** [comment]
1.14 has been released, and we have no word on a new rendering engine in the changelog or from any devs. The only graphics related things mention "VBOS always used by default" and "New lighting engine".

**Comment by asiekierka** [comment]
Yep, all "Blaze3D" changes have been delegated to 1.15.

**Comment by Artuto** [comment]
>Yep, all "Blaze3D" changes have been delegated to 1.15.

What is the source of that

**Comment by asiekierka** [comment]
A tweet which I don't have on hand - but also, the code present in the engine as of 1.14 release.

**Comment by sp614x** [comment]
There is no new render engine in 1.14.
Source: looking at the 1.14 decompiled sources.

**Comment by tr7zw** [comment]
Just found this thread after Searge posted a screen on Twitter: https://twitter.com/SeargeDP/status/1149613707032293376 His worlds are in the version "1.15/blaze3d".

**Comment by yannicklamprecht** [comment]
> Just found this thread after Searge posted a screen on Twitter: https://twitter.com/SeargeDP/status/1149613707032293376 His worlds are in the version "1.15/blaze3d".
> https://twitter.com/SeargeDP/status/1149289545285980160

Yeah they do Minecraft API LUA experiments. 👍
