### ISSUE TITLE
Particle count skyrocketing near Water pipes and Mob Spawners

### ISSUE THREAD

**Issue by Kryyss** [sp614x/optifine#2022]
I'm encountering a serious issue relating to a rapid drop in performance on a multiplayer server when anyone is near to certain parts of a mob farm I've created from 3 spider spawners and water pipes. The FPS rapidly drop but the RAM use remains the same, the issue is not even chunk specific but appears to be block specific. Even if I am away from the area but someone is standing in one of these laggy spots it will affect us both if we both have Optifine.

On the F3 debug screen, the [P] particles count is usually around 400 but when standing on in one of these laggy spots it will rapidly rise to over 12000 and keep going. However, this only happens with Optifine on Maximum or Reduced particle settings, not on Minimum. I have also tested this with someone who does not run Optifine and they experience no issues.

I can only imagine that the 1.13 water particles are causing the issue since my mob farm makes extensive use of them to funnel around mobs. There is also a sugar cane farm nearby that uses the pipes too.

**Comment by Regnander** [comment]
Issues that relates to bubble particles: #1878, #1895 
>I have also tested this with someone who does not run Optifine and they experience no issues.

Huh? So OptiFine is causing the framedrop? That's kinda strange... and interesting.

**Comment by Kryyss** [comment]
I've created an image to illustrate what is happening. Here is a side-by-side comparison of the debug screens before and after moving into what I'm calling a 'laggy spot'. What I noticed myself here is that it isn't even a specific block since in this example I was on almost exactly the same coordinates but around 0.200 closer to the area that has the water pipes and spawners. The top half is before, the lower half is after.

https://imgur.com/a/STRS39E

In the top image, the particle count is around 457, but when I step forward it skyrockets to 16138! What is odd is that this figure will increase continually and will retain it's last value if I step away and then step forward again. I can only imagine that Optifine is retaining the particles and not flushing them from memory once they are no longer needed. A memory leak of sorts.

**Comment by sp614x** [comment]
Is vanilla behaving the same way (10k particles)?

**Comment by Kryyss** [comment]
I tested on the same spot with vanilla, the particle count rises slowly as well over time but not as fast as with Optifine. Standing on that spot for around 3 mins caused the particle count to rise to around 4700 and keep rising. Whatever Optifine is doing its making a problem that already exists within Minecraft significantly worse.

**Comment by sp614x** [comment]
Relevant #2075

**Comment by sp614x** [comment]
OptiFine 1.13.2_HD_U_E5_pre5
 - fixed particle tick lag (#2022)

Optimized the particle collision detection and set limit to the maximum tick time. 
This should fix the lag spikes.
