### ISSUE TITLE
Connected textures on oak leaves not working, 1.13.1

### ISSUE THREAD

**Issue by Novabella** [sp614x/optifine#2023]
![image](https://user-images.githubusercontent.com/17990493/48458300-99f81980-e77a-11e8-9912-4c79517c6c25.png)
![image](https://user-images.githubusercontent.com/17990493/48458320-b005da00-e77a-11e8-976b-a0d30350e7f4.png)

I've tried uninstalling and reinstalling optifine a number of times, grabbing different downloads and such, so far I've had no progress in fixing this one issue with the conquest pack.

**Comment by ozals** [comment]
rename the mcpatcher folder to optifine

**Comment by sp614x** [comment]
# Update to 1.13
## Resource packs
* Rename folder "assets/minecraft/mcpatcher" to "assets/minecraft/optifine"
* In all ".properties" files replace references to "assets/minecraft/mcpatcher" with "assets/minecraft/optifine"
* Replace all numeric IDs (blocks, items, enchantments, etc.) with [names](https://minecraft.gamepedia.com/1.13/Flattening)
## Shader packs
* Add mappings for all numeric IDs used in the shader ([blocks](https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.txt#L487), [items](https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.txt#L528), [entities](https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.txt#L543), etc.)
