### ISSUE TITLE
new biomes not working with grid colormap

### ISSUE THREAD

**Issue by MrConfusioned** [sp614x/optifine#2026]

**Comment by ZwipZwapZapony** [comment]
I would personally suggest for the biome grid colormap column order to be based on a new "variable" which would consist of the grid's target biome order.

For example, specifying a hypothetical "order=minecraft:plains, minecraft:desert, minecraft:ocean" in the property file would have the X=0 column be for un-specified biomes, the X=1 column correspond to Minecraft's Plains biome, the X=2 column to the Desert, and the X=3 column to the Ocean.

However, I don't know how easy or hard this would be to maintain in practice, but it's better than relying on a hardcoded order in my opinion.

**Comment by sp614x** [comment]
The biome IDs haven't changed between 1.12 and 1.13. 
Only the names of the biomes have been updated, but they are not relevant to the colormaps.
The 1.12 colormaps should work correctly in 1.13.x.

**Comment by sp614x** [comment]
Using a custom biome order for the grid colormaps may be added (a new issue should be crated for it).
However it would be more unstable as the biome names tend to change more often than the biome IDs.
