### ISSUE TITLE
Block id re-mapping doesn't work on 1.13

### ISSUE THREAD

**Issue by Choca13** [sp614x/optifine#2045]
Shaders can't modify block ids using the block.properties file in optifine 1.13.2_HD_U_E5_pre3 . It affects the latest version of my shaders and probably some other recent shaders as well.

**Comment by sp614x** [comment]
Is it working in E4?
Errors in game output/log?

**Comment by zombye** [comment]
It is working for me, tested in E4, E5 pre2, and E5 pre3.

If you're using block names from 1.12.2 (and earlier) then that is probably why it isn't working for you, as a lot of the block names were changed in 1.13.

**Comment by Choca13** [comment]
Nevermind, i thought numerical block ids were still usable
