### ISSUE TITLE
Illusioner loses hood when I use CEM

### ISSUE THREAD

**Issue by MushirMickeyJoe** [sp614x/optifine#2046]
![2018-11-24_02 58 43](https://user-images.githubusercontent.com/31923214/48963564-3ef1ce00-ef95-11e8-9840-c6d5ba0345fd.png)

I added basic ears to the illusioner using CEM, but as soon as I got the CEM to work the illusioner's hood disappeared.

**Comment by sp614x** [comment]
Fixed, coming in next preview.
