### ISSUE TITLE
[1.13.2 HD U E4-E5 pre3] Better Grass not applying to Podzol blocks

### ISSUE THREAD

**Issue by Namelesswonder** [sp614x/optifine#2049]
### Issue:
Podzol blocks are not changed at all by Better Grass, at any option level, with or without a resource pack that contains `bettergrass.properties`.

#### Game Version Used:
1.13.2

#### OptiFine Versions Used:
1.13.2 HD U E4
1.13.2 HD U E5 pre1
1.13.2 HD U E5 pre2
1.13.2 HD U E5 pre3

###### OS:
Fedora 29, kernel 4.19.2-300.fc29.x86_64
###### Java Versions Used:
OpenJDK 1.8.0_191-b12 (launchwrapper 1.12 and 2.0)
OpenJDK 11.0.1+13 (launchwrapper 2.0)

### Observations:
Happens with any configuration of natural textures, alternate blocks, and Better Grass settings.

Without a resource pack and the Better Grass option set to either fast or fancy the podzol block does not get any treatment from Better Grass:
![2018-11-21_22 45 22](https://user-images.githubusercontent.com/12788603/48972298-5791d080-eff5-11e8-88b6-7f032717aa76.png)

With a resource pack and a configured bettergrass.properties the block still is unaffected:
![2018-11-21_22 45 35](https://user-images.githubusercontent.com/12788603/48972306-7ee89d80-eff5-11e8-9480-b8eda76b8558.png)
`bettergrass.properties` from the resource pack:
```
grass=true
grass_path=true
mycelium=true
podzol=true

grass.snow=true
mycelium.snow=true
podzol.snow=true

grass.multilayer=false

texture.grass=block/grass_block_top
texture.grass_side=block/grass_block_side
texture.grass_path=block/grass_path_top
texture.grass_path_side=block/grass_path_side
texture.mycelium=block/mycelium_top
texture.podzol=block/podzol_top
texture.snow=block/snow
```

The `bettergrass.properties` from the resource pack is still being loaded, as with this test resource pack that includes a change for the texture Better Grass uses for mycelium to the grass path texture:
![2018-11-24_14 34 54](https://user-images.githubusercontent.com/12788603/48972349-69c03e80-eff6-11e8-8368-09a61ab4641b.png)

The snow texture is also not applied to any podzol blocks with snow around them:
![2018-11-24_14 35 31](https://user-images.githubusercontent.com/12788603/48972400-65485580-eff7-11e8-8482-90f37b86e66d.png)

I don't know when it stopped working, it was working when the `bettergrass.properties` was added back in release B2 for 1.9, as [evidenced by this post.](https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1272953-optifine-hd-fps-boost-dynamic-lights-shaders-and?page=2431#c50921)

**Comment by JimStoneCraft** [comment]
I can confirm with the John Smith Legacy pack that Podzol does not work, while the other three type work fine (Grass, Grass Path and Mycelium).

**Comment by sp614x** [comment]
Fixed, coming in next preview.
