### ISSUE TITLE
Emmisive textures on modded blocks/paintings?

### ISSUE THREAD

**Issue by jisuke** [sp614x/optifine#2050]
I'm using the latest build for 1.12.2 and I can't get emissive textures to show up for blocks added by chisel or paintings from paintings++, but they do seem to work for vanilla blocks & entities. Is there some kind of special trick to making it work with non-vanilla textures?

**Comment by sp614x** [comment]
OptiFine adds emissive textures to all blocks and items that use the vanilla rendering.
If the modded blocks/items use custom rendering then OptiFine can't fix them.
