### ISSUE TITLE
forge 1.12.2 crashed when optifine U E2 is installed

### ISSUE THREAD

**Issue by QuinnSchukkink** [sp614x/optifine#2051]
[latest.log](https://github.com/sp614x/optifine/files/2613002/latest.log)

**Comment by boosterdev** [comment]
this allready starts with forge 2781

**Comment by JasonKillsUs** [comment]
same crash same log MC 1.12.2 Forge 2781  OF U E", no other mods installed

"https://paste.ee/p/csBzd"

thanks for looking into it :-)

**Comment by sp614x** [comment]
OptiFine 1.12.2_HD_U_E3_pre is out, compatible with Forge #2795.
