### ISSUE TITLE
spawn egg color

### ISSUE THREAD

**Issue by IgorEstevao** [sp614x/optifine#2053]
Hey,

I trying to remove all colors from zombie spawn egg, but doesn't work, i think it's bugged
![a](https://user-images.githubusercontent.com/41526335/48987768-cd3a9100-f108-11e8-8035-cc06905b8ece.PNG)
![b](https://user-images.githubusercontent.com/41526335/48987769-cd3a9100-f108-11e8-89af-ae52b3504c8c.PNG)

my color file->
../optifine/colormap/color.properties
```
#1.13
egg.shell.Zombie=ffffff
egg.spots.minecraft\:Zombie=ffffff

#1.12
# egg.shell.Zombie=FFFFFF
# egg.spots.Zombie=FFFFFF
```

**Comment by realjackasterisk** [comment]
`color.properties` isn't supposed to go in the `colormap` folder.
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/color.properties#L257

**Comment by KKMNNOIR** [comment]
How about using only lower case letters?
(Change from Zombie to zombie.)

**Comment by IgorEstevao** [comment]
Worked!

**right way in 1.13:**
```
egg.shell.zombie=FFFFFF
egg.spots.zombie=FFFFFF 
```

**Comment by Dewaxel** [comment]
Doesn't work on version 1.16

**Comment by IgorEstevao** [comment]
#4173
