### ISSUE TITLE
FallingBlock entities flicker when they turn into regular blocks.

### ISSUE THREAD

**Issue by towelcat** [sp614x/optifine#2054]
Example with sand: https://gfycat.com/BowedUnsteadyGrub
Happens with custom commands as well: https://gfycat.com/UnknownOblongDogwoodtwigborer
(The commands used above are destroying the entity and creating the block on the same tick. I've also tried destroying the entity 1 tick later and the issue still persists)

I've tried toggling nearly every setting in the graphics menu, nothing seems to change it. This does not happen in the vanilla game.

**Comment by towelcat** [comment]
Update: It appears to happen whenever you /setblock any bit of air into an actual block. 
https://gfycat.com/ShadowyFrankHammerheadshark

I imagine falling block entities work in a similar way. This doesn't occur when you manually place blocks via right-click.

**Comment by sp614x** [comment]
Chunk updates which are not initiated by the player are run in on a background thread to avoid the chunk update lag spikes.
In this case the moving block (entity) is being replaced with a normal block which needs a chunk update. The chunk update is executed with 1 frame delay so there is a small flicker between the disappearing of the entity and the appearance of the block.
