### ISSUE TITLE
Clear water moved?

### ISSUE THREAD

**Issue by Xetaxheb** [sp614x/optifine#2060]
Clear water and dynamic fov/vignette off are pretty much the only reasons I use optifine, where is the button? Minecraft 1.13.2/OptiFine_1.13.2_HD_U_E4.jar

**Comment by Hax4Ever** [comment]
Clear water is gone.

**Comment by realjackasterisk** [comment]
iirc, clear water was removed from optifine in 1.13 because 1.13 already has it, or at least something similar.

**Comment by Xetaxheb** [comment]
Oh, how do I set that in 1.13? The existing clarity doesn't work for me.

**Comment by realjackasterisk** [comment]
there is no option for it, as far as i'm aware.

**Comment by Xetaxheb** [comment]
ah, alright. I guess it's a non-issue but if we could get this back in like it used to be that would be wonderful.

**Comment by Brottweiler** [comment]
@Xetaxheb 
>sp614x07/09/2018
>vanilla underwater brightness is the same as 1.12 Clear Water, there is only more fog
>night vision manipulates the lightmap so clear water can't work like it

If you want more transparent water you can make the water texture less opaque.
