### ISSUE TITLE
Crash on newer Forge versions

### ISSUE THREAD

**Issue by TheRealDadbeard** [sp614x/optifine#2061]
I know using bleeding edge stuff can cause issues, just a heads up. Using Forge 2784 on Minecraft 1.12.2 crashes with Optifine.

Tried it with my other mods and seperate. Here is the latest.log only with Optifine. https://hastebin.com/oquwapozoz.sql

I get no crashlog with more informations. Debug.log doesn't get updated either.

**Comment by Insane-96** [comment]
Can confirm. Just optifine+forge, no other mods, game crashes on startup. Going back to Forge recommended (2768) fixes the problem.

**Comment by skmedix** [comment]
Probably related to:
https://github.com/MinecraftForge/MinecraftForge/commit/9587f08ece96327ec0ba0faae469277c1baf2bc2
https://github.com/MinecraftForge/MinecraftForge/commit/d16472d0ba38c04d46fbdb59cc035c6796b4798f

**Comment by magcicada** [comment]
Only crashed by Forge 2781 and the newer version

**Comment by Tsoccerguy3** [comment]
Optifine 1.12.2 , is no longer compatible with Forge builds 2781 - 2795 plus . All these updates with Forge are to improve Forge and more hooks and patches are coming . Recommended is still 1.12.2 - 14.23.5.2768
to see what's going on , https://github.com/MinecraftForge/MinecraftForge/commits/1.12.x_

**Comment by sp614x** [comment]
OptiFine 1.12.2_HD_U_E3_pre is out, compatible with Forge #2795.
