### ISSUE TITLE
[Question/Suggestion] Player Armor stands with CEM?

### ISSUE THREAD

**Issue by dallin1016** [sp614x/optifine#2062]
I'm not very familiar with CEM, so forgive me if this seems like a dumb question.

Is it possible to change an armor stand's model so that it is a player skin? I haven't seen anyone do it yet, so I assume it isn't, but I could be wrong.

If not I'd really like to see that ability. Plus the possibility to change the skin depending on the stand's name. I think it would be very useful for servers/maps.

Thanks for reading,
~dallin1016

**Comment by Francy-Chan** [comment]
Yes, you can, since you can change entities texture by their name, you can do it.
Also, thanks for the idea, I'll do it right now, plus I'll leave the pack on the comments in the future.

[Reference ](https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/cem_model.txt)

**Comment by Francy-Chan** [comment]
Yes, you can, since you can change entities texture by their name, you can do it.
[Reference](https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/cem_model.txt)

**Comment by dallin1016** [comment]
I'm more specifically asking about whether it's possible to change an Armor stand's entity model to look like a player.

**Comment by sp614x** [comment]
It should be possible to change the armor stand model with CEM to be like a player model.
