### ISSUE TITLE
[1.13.2] Extreme lag

### ISSUE THREAD

**Issue by TrueMeltix** [sp614x/optifine#2063]
I have Minecraft Optifine 1.13.2 for a while now. Usually, when i play Minecraft Vanilla (no Optifine) i get 40-70 fps. When i use optifine i get 0 fps,
I already tried to set every single particle off, reduce every detail, removing texture packs and more ì, but nothing changes.
Is there any way to fix this problem? Is it a Optifine problem?
I Dont really think that is my PC performance problem, because, even activing the VBO (That should slow down a lot the game) makes my FPS go to 120 and more.

**Comment by Quavelen** [comment]
@TrueMeltix it's not an OptiFine problem, and yes there is a way to "fix" your issue. However, you haven't provided any details. Once you do, maybe someone will be able to help you.

For starters, what are your specs? Cpu, gpu, etc. You can find it either in the "Performance" tab of task manager, or on the right side of the F3 screen in Minecraft. The latter will also show which version of Java you have, along with how much ram you've allocated and specifically which version of OptiFine you're using. 

I would suggest providing that before we go any further.

**Comment by TrueMeltix** [comment]
![2018-12-01_18 56 56](https://user-images.githubusercontent.com/43494249/49331315-36078a80-f59b-11e8-93fb-2bcdfdf961c5.png)
There are my current specs

**Comment by Quavelen** [comment]
The driver for your IntelHD integrated graphics chip is severely outdated. Please update it: https://downloadcenter.intel.com/download/28164/Intel-Graphics-Driver-for-Windows-15-33-?product=71465

Make sure you select this one:

![image](https://user-images.githubusercontent.com/19168008/49331389-d9ed3800-f593-11e8-966c-dc1804e1a017.png)

Once you install it, restart your laptop and try using OptiFine again. Make sure you are using the latest version, from the official OptiFine site, found here: https://optifine.net/adloadx?f=preview_OptiFine_1.13.2_HD_U_E5_pre3.jar

**Comment by TrueMeltix** [comment]
Works flawlessly! Thank you so, so much, so helpful!
Should i leave this issue here as closed and solved?

**Comment by Quavelen** [comment]
Yup, just close the issue now. I'm happy it's working for you. =)
