### ISSUE TITLE
Missing giant CEM

### ISSUE THREAD

**Issue by Francy-Chan** [sp614x/optifine#2069]
<title>

**Comment by sp614x** [comment]
https://minecraft.gamepedia.com/Giant

**Comment by Francy-Chan** [comment]
The CEM is different from zombies, the texture not.
I'm using CEM with zombies and the zombie doesn't share their model with giant.
here's a example:
![image](https://user-images.githubusercontent.com/40085587/49586341-09ab8f80-f948-11e8-84ff-3b5ceb8a5507.png)
My Zombie CEM have Slim arms and the Giant do not, witch causes the black lines.
(I'm using E5_pre5)

**Comment by Gunging** [comment]
The reply by sp614x was Minecraft wiki's wikipedia page. There are two sections that kind of match this topic, the summary of them is:

#1: The Giant has the same texture as the zombie (Though CEM does not affect giants).
#2: The Giant is an unsupported entity and thus issues related to them wont be fixed.

I hope he didn't mean #2 when he sent the link.

**Comment by sp614x** [comment]
Added giant CEM in latest 1.14.4 F4 preview.
