### ISSUE TITLE
Crash when using optifine on ubuntu

### ISSUE THREAD

**Issue by Smolkis** [sp614x/optifine#2070]
I have a clean install of latest lte ubuntu, with little else than minecraft installed. Running without mods works fine, but if I run with optifine it crashes on launch. 

If I test the environment via magic launcher I get the following error dump

java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
    magic.launcher.ap.a(SourceFile:147)
    magic.launcher.ab.r(SourceFile:1558)
    magic.launcher.am.actionPerformed(SourceFile:268)
    java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
    java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
    java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
    java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
    java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:270)
    java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
    java.desktop/java.awt.Component.processMouseEvent(Component.java:6589)
    java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
    java.desktop/java.awt.Component.processEvent(Component.java:6354)
    java.desktop/java.awt.Container.processEvent(Container.java:2261)
    java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4966)
    java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2319)
    java.desktop/java.awt.Component.dispatchEvent(Component.java:4798)
    java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4914)
    java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4543)
    java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4484)
    java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2305)
    java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
    java.desktop/java.awt.Component.dispatchEvent(Component.java:4798)
    java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
    java.desktop/java.awt.EventQueue.access$600(EventQueue.java:97)
    java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
    java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
    java.base/java.security.AccessController.doPrivileged(Native Method)
    java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
    java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
    java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
    java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
    java.base/java.security.AccessController.doPrivileged(Native Method)
    java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
    java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
    java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
    java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
    java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
    java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
    java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by SetantaLP** [comment]
Since the problem seem to be a ClassCastException between AppClassLoader and URLClassLoader in the java.base module, I would assume that it's the same problem as in #2044 (the missing launchwrapper compatibility with java9+).

**Comment by Smolkis** [comment]
Since that one is closed, does it mean there is a release somewhere I can use to verify?

**Comment by SetantaLP** [comment]
I think it is closed because there are two similar issues linked, so I would check these ones.

**Comment by ozals** [comment]
do this https://github.com/sp614x/optifine/issues/1818#issuecomment-427983171 @Smolkis it should fix your issue

**Comment by ozals** [comment]
what do you mean?

**Comment by ozals** [comment]
If you're asking what the reason is for the problem, it's from minecraft not liking openjdk runtime java, the commands that strum said were to change it to oracle runtime

**Comment by SetantaLP** [comment]
As explained in #1739, it's not a problem inside Optifine itself, but inside the launchwrapper optifine uses, that exists if you use java9+ (no matter if it's openjdk or oraclejdk), due to breaking changes introduced in java9 (URLClassLoader is no longer the parent-class for AppClassLoader) There is also a launchwrapper fork that includes a workaround for the issue, but since the whole launchwrapper is not really made for java9+, the workaround will not be included the official repository. Instead cpw (one of the forge devs) is developing a new tool, which is not yet finished.
So there are two possible solutions until the new tool is finished: use java 8 if you play with optifine (as mentioned by @ozals) or use the launchwrapper-fork (as explained in the issue linked at the beginning of the post).

**Comment by Smolkis** [comment]
Sound valid, if a long term new tool is in progress then a valid fix is in pipe, i was just stating that as a user i dont care why the game crashes, I just know I installed the correct mod for the version I use, following the instructions when installing both minecraft and the mod, without error messages, and get a crash on start. Digging into github seems a bit much to request from the mod user, but I might be wrong on the level of expectation. Just a quality of service mindset, but take it as a tip, not a whine or rage, I'm all set and moving on, thankful for the help and explaniations

**Comment by Smolkis** [comment]
> If you're asking what the reason is for the problem, it's from minecraft not liking openjdk runtime java, the commands that strum said were to change it to oracle runtime

Is that just when modding? It did run fine without the mod, or fine is a grand word for it, but it rendered a frame every now and then

**Comment by Mhowser** [comment]
@ozals that solution does not work anymore https://launchpad.net/~webupd8team/+archive/ubuntu/java

**Comment by sp614x** [comment]
OptiFine 1.14.3_HD_U_F1
 - fixed compatibility with Java 9+
