### ISSUE TITLE
Optifine 1.12.2 E2 keeps crashing with forge 1.12.2 2795 

### ISSUE THREAD

**Issue by CraftKiller99** [sp614x/optifine#2072]

**Comment by kerts93** [comment]
Can confirm the same happening after updating our modpack to 14.23.5.2784. Client crashes on start.

**Modpack:** https://minecraft.curseforge.com/projects/the-society-transportcraft
**Modpack version** from which issue starts occuring: 5.0.6.9
**Logfile:** https://pastebin.com/tk88SdG2

**Comment by Quavelen** [comment]
@CraftKiller99 and @kerts93, please see issue #2074. 
This was fixed in the latest preview version, found on the OptiFine site:
![image](https://user-images.githubusercontent.com/19168008/49498200-2ec5d280-f862-11e8-8121-ccfb305ec19a.png)

**Comment by sp614x** [comment]
Fixed in latest preview.
