### ISSUE TITLE
Suggestion: Option to disable all particles entirely

### ISSUE THREAD

**Issue by DataCrusade** [sp614x/optifine#2075]
In 1.13, particles cause a lot more lag that can tank the framerate very easily, and there's many particles that you can't disable at all. An option to disable all particles would be great, especially for people with bad PCs, until the particle lag is fixed and where it's no longer needed to disable particles (would still be useful tho).

**Comment by sp614x** [comment]
OptiFine 1.13.2_HD_U_E5_pre5
 - fixed particle tick lag (#2022)
