### ISSUE TITLE
Biome blend

### ISSUE THREAD

**Issue by popa1234** [sp614x/optifine#2076]
Biome blend doesn't seem to work everywhere, but works in some places. Biome blend settings: 15x15. Didn't find the problem anywhere but the swamp.
OptiFine 1.13.2 HD U E5 pre5:

![2018-12-05_16 47 23](https://user-images.githubusercontent.com/44902140/49521996-45dee180-f8af-11e8-9e62-41086bfede26.png)

**Comment by sp614x** [comment]
Is Swamp Colors enabled?

**Comment by popa1234** [comment]
Yes

**Comment by sp614x** [comment]
Fixed, coming in next preview.
