### ISSUE TITLE
[1.13.2 OptiFine E5 pre5] Block breaking particles slide on the ground

### ISSUE THREAD

**Issue by SteveKunG** [sp614x/optifine#2077]
After fixing #2022 Block particles slide when it touch the ground. Not sure about other particles.

**Comment by sp614x** [comment]
Looks like a problem with the particles decompilation/deobfuscation.

**Comment by sp614x** [comment]
Fixed, coming in next preview.

**Comment by sp614x** [comment]
Also needs a fix for fluid particles:
![image](https://user-images.githubusercontent.com/16635441/49546979-d209fc80-f8e1-11e8-930f-b63f6750571f.png)

**Comment by sp614x** [comment]
The bubbles work identically in vanilla

![image](https://user-images.githubusercontent.com/16635441/49575751-c0f1d780-f943-11e8-8766-7ebaf7a16abe.png)
