### ISSUE TITLE
Can't scroll using mouse wheel in shaders menu

### ISSUE THREAD

**Issue by Redspyro99** [sp614x/optifine#2078]
Ever since the release of Optifine for 1.13 with version E3, the mouse wheel has not been able to scroll the shaders menu up or down. I have tested it in version E2 for 1.12.2, and the mouse wheel does scroll the menu up and down, so it seems to be purely isolated to 1.13. The bug still persists however even on the latest E5 Pre5 release for 1.13.2. I hope this is sufficient enough of a report.

**Comment by ozals** [comment]
This happens to me as well actually, I did not know it wasn't normal behavior

**Comment by sp614x** [comment]
The shaders menu uses the standard minecraft scroll pane. It scrolls with the mouse wheel only when it has the focus. You can click on the scroll bar to set the focus).
The scroll pane for resource pack selection works identically.

**Comment by sp614x** [comment]
Fixed, coming in next preview.

**Comment by GeForceLegend** [comment]
This happens again in 1.20.4 preview. If any collaborator see this, please reopen it.
