### ISSUE TITLE
Water texture glitches when AA is enabled

### ISSUE THREAD

**Issue by enderkitsune** [sp614x/optifine#2089]
With AA enabled, the water texture becomes very wonky. It appears to be untextured and a deep blue color. It will flicker between the deep blue color, normal blue color, and sometimes become totally transparent when moving the camera around. It's especially bad on a save with a lot of objects and different textures.

![2018-12-08_10 12 04](https://user-images.githubusercontent.com/45715683/49687565-b4e85000-fad2-11e8-9140-682624031927.png)

I only use Optifine and the PureBDCraft texture pack.

Does anyone have any idea why this would happen? I'm completely baffled.

**Comment by Regnander** [comment]
I believe this was addressed and fixed in #1981. Can you try the latest pre-release and see if it works?

**Comment by enderkitsune** [comment]
Yep, that fixed it! Thank you so much! :D
