### ISSUE TITLE
Bug with SIGN

### ISSUE THREAD

**Issue by jere62smi** [sp614x/optifine#2091]
Hello,

Since the release of Optifine in 1.13.X, I encounter a problem with the SIGN, I call a SIGN at the coordinates of the player with some information to allow him then to enter a value and to make such an action, the problem and that like you can see it through the screens below, we see no information and no writing of the player when he marks a few things on the panel.
So you have to know that my action works anyway, that is if I mark as if I saw the panel validating, it works but it's really annoying because it is not very professional and suddenly a lack of info for my players.
I remain available if you have questions about this problem, or better, if you want to test the problem, I can take you to a test server and show you directly the problem.

Have a nice day !

Cordially.

Screen with the bug SIGN:
![screenbug](https://user-images.githubusercontent.com/31114661/49690545-35d73400-fb33-11e8-9489-3ab85a90d01a.png)

Screen with the correct SIGN:
![screensansbug](https://user-images.githubusercontent.com/31114661/49690551-45567d00-fb33-11e8-9481-cc73ba85bcbe.png)

Code of my plugin for the SIGN:
https://pastebin.com/MdJLuDnA
http://prntscr.com/lsdexp

PS: I want to clarify that it works really well without optifine and that I have another plugin that does the same function and that meets the same problem with the SIGN when using optifine in 1.13.X.

**Comment by sp614x** [comment]
On which server can I test this?

**Comment by jere62smi** [comment]
For reasons of confidentiality, I prefer if possible to send you the private ip of the test server and be there to show you live.
You can however if you want to go on my public server, the problem is still with Optifine, the ip is: mc-imperia.fr
I will give you the commands to perform to allow you to reproduce this bug:
/mondes > Nature> Nature
Then, you will have to walk and find an empty parcel and write the following command: / cubo, if you see green particles, the terain is available and you will then have to click in the chat on [Acheter le cubo], and it will be is at this exact moment or the bug this product, the SIGN opens and you will see nothing dedant and nothing that you write.
The simplest way would be to contact me privately and see him directly together to guide you to the problem.

Cordially.

**Comment by jere62smi** [comment]
Hello,

I allow myself to come to you because I have no news for several months. I hoped that with the latest version of optifine this bug is fixed but unfortunately no. Can we with a way to communicate privately to fix this problem together? I can not give access to my test server to everyone ^^ because on GITHUB everyone will see the ip.
You can add me on Discord and we will see together because the server is not in english server so I think you will need help to realize by yourself the bug ^^
My discord: jere62smi # 2156

Hoping you can correct that.

**Comment by sp614x** [comment]
You can PM me on discord: https://discord.gg/tKxWtyf

**Comment by sp614x** [comment]
Further discussion and possible fix in: https://github.com/sp614x/optifine/issues/2422
