### ISSUE TITLE
Crash with C5 1.13.2 preview6

### ISSUE THREAD

**Issue by WeirdDude96** [sp614x/optifine#2092]
Crash. 
Pastebin: https://pastebin.com/xN60FDiL
Java 8 191,
Intel Graphics Card,

**Comment by ozals** [comment]
Where did you download optifine from?? there is no C5, and are you on windows?

**Comment by realjackasterisk** [comment]
@ozals crash log says windows 10.
it also says E5, so i'd assume "C5" was just some sort of typo.

**Comment by sp614x** [comment]
There is nothing in the crash stack trace that may be linked to OptiFine.
Looks like a known vanilla problem: https://bugs.mojang.com/browse/MC-111544
