### ISSUE TITLE
minecraft wont start with this installed, no crash generated

### ISSUE THREAD

**Issue by kuroyure** [sp614x/optifine#2095]
https://pastebin.com/2XXA5iWY pastebin link to the log

**Comment by kuroyure** [comment]
Pls quote the latest forge version i can use and Tell me If that is going to be fixed or If you guys only work with 1.13 rn

**Comment by realjackasterisk** [comment]
I meant try the latest preview version of OptiFine, 1.12.2 E3, which already fixes this issue with Forge. 
![image](https://user-images.githubusercontent.com/31686191/49706537-607cc780-fbdb-11e8-9a53-94b9053313f4.png)

**Comment by kuroyure** [comment]
Tks, also same happens with foamfix, any clue If they have It fixed ?

**Comment by realjackasterisk** [comment]
I don't really keep up with other optimization mods, so no idea.

**Comment by sp614x** [comment]
Fixed in E3 for 1.12.2
