### ISSUE TITLE
Glass connected textures doing wierd connections 1.13.2

### ISSUE THREAD

**Issue by Frizlerrr** [sp614x/optifine#2097]
When facing east and north the glass use the wrong connected textures, but the correct ones are used when facing south and west. Im using the Lithos Core texturepack
![2018-12-10_19 41 12](https://user-images.githubusercontent.com/45767599/49753524-fa17a800-fcb3-11e8-988a-0beb33dc7cf7.png)
![2018-12-10_19 41 14](https://user-images.githubusercontent.com/45767599/49753525-fa17a800-fcb3-11e8-882b-504f8db3c8fe.png)
![2018-12-10_19 41 23](https://user-images.githubusercontent.com/45767599/49753526-fa17a800-fcb3-11e8-84fd-7972cac20949.png)
![2018-12-10_19 41 09](https://user-images.githubusercontent.com/45767599/49753527-fab03e80-fcb3-11e8-8af6-4703ea463923.png)

**Comment by sp614x** [comment]
CTM only works correctly for the vanilla glass pane models.
If the resource pack uses custom glass pane models CTM will have the problem that you describe above.
