### ISSUE TITLE
Add option to use old legacy 1.7 animations in the 1.8 version of optifine.

### ISSUE THREAD

**Issue by Technerder** [sp614x/optifine#2098]
When the 1.8 version of the game was released, the old blocking animation was removed, however the blocking mechanic was not, which essentially just made the game look weird, by making it look like so:

Figure A (1.7 Animations): https://www.youtube.com/watch?v=rMSLk0B0JmU
Figure B (1.8 Normal Animations): https://www.youtube.com/watch?v=sINuC3mqAIY
Figure C (1.8 My Fix): https://www.youtube.com/watch?v=1JYsnK83xiU

This issues is quite wide spread between the multiplayer player versus player community to the point where there have been mods created (Such as: https://hypixel.net/threads/1-7-animations-mod-for-1-8-forge.709981/) and numerous clients have also added it such as Hyperium (https://hyperium.cc/), BadlionClient (https://client.badlion.net/) and many others. But many people including myself don't like to use a custom client or mod to be able to see the old animations, and feel like it should be something that optifine can address. 

All me and many other people would like is to have an option in (Options -> Video Settings > Animations) called "Old Animations" or "Legacy Animations" to allow us to see the old animations instead of the new broken 1.8 ones.

The way to implement this is by adding this code to the start of GuiInGame#renderPlayerStats
```java
		if (this.mc.thePlayer.getHeldItem() != null && shouldDisplayLegacyAnimationsBooleanVariable) {
			this.attemptSwing();
		}
```

Then also add these two methods into the same class:

```java
	private void attemptSwing() {
		if (this.mc.thePlayer.getItemInUseCount() > 0) {
			final boolean mouseDown = this.mc.gameSettings.keyBindAttack.isKeyDown() && this.mc.gameSettings.keyBindUseItem.isKeyDown();
			if (mouseDown && this.mc.objectMouseOver != null && this.mc.objectMouseOver.typeOfHit == MovingObjectPosition.MovingObjectType.BLOCK) {
				this.swingItem(this.mc.thePlayer);
			}
		}
	}

	private void swingItem(EntityPlayerSP entityplayersp) {
		final int swingAnimationEnd = entityplayersp.isPotionActive(Potion.digSpeed) ? (6 - (1 + entityplayersp.getActivePotionEffect(Potion.digSpeed).getAmplifier()) * 1) : (entityplayersp.isPotionActive(Potion.digSlowdown) ? (6 + (1 + entityplayersp.getActivePotionEffect(Potion.digSlowdown).getAmplifier()) * 2) : 6);
		if (!entityplayersp.isSwingInProgress || entityplayersp.swingProgressInt >= swingAnimationEnd / 2 || entityplayersp.swingProgressInt < 0) {
			entityplayersp.swingProgressInt = -1;
			entityplayersp.isSwingInProgress = true;
		}
	}
```
And then finally modifying ItemRenderer#transformFirstPersonItem to:
	
```java
	private void transformFirstPersonItem(float equipProgress, float swingProgress) {
				
		boolean displayLegacyAnimations = settings.shouldUseOldAnimation();
		
		if (displayLegacyAnimations && this.mc != null && this.mc.thePlayer != null && this.mc.thePlayer.getItemInUse() != null && this.mc.thePlayer.getItemInUse().getItem() != null && Item.getIdFromItem(this.mc.thePlayer.getItemInUse().getItem()) == 261) {
			GlStateManager.translate(-0.01f, 0.05f, -0.06f);
		}

		if (displayLegacyAnimations && this.mc != null && this.mc.thePlayer != null && this.mc.thePlayer.getCurrentEquippedItem() != null && this.mc.thePlayer.getCurrentEquippedItem().getItem() != null && Item.getIdFromItem(this.mc.thePlayer.getCurrentEquippedItem().getItem()) == 346) {
			GlStateManager.translate(0.08f, -0.027f, -0.33f);
			GlStateManager.scale(0.93f, 1.0f, 1.0f);
		}

		if (displayLegacyAnimations && this.mc != null && this.mc.thePlayer != null && this.mc.thePlayer.isSwingInProgress && this.mc.thePlayer.getCurrentEquippedItem() != null && !this.mc.thePlayer.isEating() && !this.mc.thePlayer.isBlocking()) {
			GlStateManager.scale(0.85f, 0.85f, 0.85f);
			GlStateManager.translate(-0.078f, 0.003f, 0.05f);
		}

		GlStateManager.translate(0.56F, -0.52F, -0.71999997F);
		GlStateManager.translate(0.0F, equipProgress * -0.6F, 0.0F);
		GlStateManager.rotate(45.0F, 0.0F, 1.0F, 0.0F);
		float f = MathHelper.sin(swingProgress * swingProgress * (float) Math.PI);
		float f1 = MathHelper.sin(MathHelper.sqrt_float(swingProgress) * (float) Math.PI);
		GlStateManager.rotate(f * -20.0F, 0.0F, 1.0F, 0.0F);
		GlStateManager.rotate(f1 * -20.0F, 0.0F, 0.0F, 1.0F);
		GlStateManager.rotate(f1 * -80.0F, 1.0F, 0.0F, 0.0F);
		GlStateManager.scale(0.4F, 0.4F, 0.4F);
	}
```

Thank you for reading this request.

**Comment by sp614x** [comment]
So when the player is blocking with the sword and the crosshair comes over a block the block breaking animation should start while keeping the blocking animation active?

**Comment by Technerder** [comment]
Precisely, although in 1.8 you should only be able to have the animation of breaking the block, not actually being able to break the block.

**Comment by sp614x** [comment]
Having the block breaking animation, but not really breaking the block is misleading.
If the block is not going to break then the breaking animation shouldn't start.

**Comment by Technerder** [comment]
If we're thinking about this on a logical level you'd be right, even though most of Minecraft does not rely on real logic (Mainly talking about how you are able to break the logs of a tree and have the rest of the tree stay floating, or even breaking the wood by punching it in the first place.). However from an aesthetic standpoint it would make sense to add an option to revert these animations to their previous state, hence why the mods/clients I mentioned above were created. Furthermore you could argue that the option to disable particles in the Video Settings -> Animations menu would also misleading if someone were to just stand in front of a painting that looked like fire or have the fire resistance potion active while being on fire, and thus might think they are/would be taking damage. If you would like more community feedback on this request (I'm referring to the 'Thumbs up' reactions) I would be able to make a Straw Poll for this issue and have the player versus player community display their choice there.

**Comment by KaiAF** [comment]
I am going to close this as I am almost certain this would not be added. There are other mods that would do this, you could use them.

**Comment by dragon6810** [comment]
it didnt work for me, what should i do?

**Comment by dragon6810** [comment]
update: i traced it back until if found out it is indeed affecting swingProgressInt the way it should, the animation just isnt playing. ???

**Comment by Tuffdufroggins** [comment]
@dragon6810 I just came across this, and your issue is that in ItemRenderer#renderItemInFirstPerson, 
there is "else if (abstractclientplayer.getItemInUseCount() > 0)" 
that makes it so its not applying the swing progress ( float f1 = abstractclientplayer.getSwingProgress(partialTicks); ) even if the getSwingProgress is working

In order for it to work, you need to change
this.transformFirstPersonItem(f, 0.0F); to
this.transformFirstPersonItem(f, f1);
so that is actually uses the swing progress

I know its been a while since you asked "???", but I found out what you were having trouble with, so I decided to reply.
Hope this helps!

**Comment by ElectronicApple** [comment]
@Tuffdufroggins thank you so much!! I've just come across this now while making my client (perfect timing) and it works perfectly.

**Comment by TheJamer** [comment]
@floreidev I know this is roughly 2 years late but how did you manage to get the 1.7 animations in your client? I've been trying for a while but it never worked, so it would be of great help if you could show how it works and your script

**Comment by floreidev** [comment]
Ive not got access to the files anymore but i was basically a process of
constantly go and back and forth between files, finding declarations and
ctrl+f’ing their usage. I think i also downloaded the old 1.7 version of
MCP and compared
