### ISSUE TITLE
A cape is asigned to 2 donation accounts

### ISSUE THREAD

**Issue by RealRunSpace** [sp614x/optifine#210]
The cape is asigned to 2 accounts, because when I donate my friend give me his cape before the donation, so now my donation e-mail and his donation email have the same cape ID, but the cape can be only managed from 1 account, I tryed to contact you via email, but I think this is also a bug (buy a cape to a username when the username have alredy one)

**Comment by RealRunSpace** [comment]
Now, if you want to help me, this is the both cape ID (66DF0E74) and emails: mejoresamigoslostres77@gmail.com & erfefeendaro1@gmail.com

**Comment by Anqelow** [comment]
Hello, i have the same problem, did you fixed that? im really pissed out

**Comment by RealRunSpace** [comment]
No, I'm still waiting D:

**Comment by sp614x** [comment]
The payment from mejoresamigoslostres77@gmail.com is free now.
You can go to https://optifine.net/login and activate another cape for it.

**Comment by RealRunSpace** [comment]
Can you change erfefeendaro1@gmail.com to a new email address (realrunspacebusiness@gmail.com)

**Comment by RealRunSpace** [comment]
Also thanks for fixing this issue, this was a surprise for me xD

**Comment by sp614x** [comment]
Email migration is not possible for now
