### ISSUE TITLE
[Feature Request] Ability to specify what specific blocks a ctm can connect to.

### ISSUE THREAD

**Issue by Titus-Armillius** [sp614x/optifine#2105]
MC version: 1.12.2
Optifine version: U_E3

Currently classic ctm does not allow one to have the ctm connect to a block type other than itself. 

If I include:
matchBlocks=251
connect=block

The ctm will be applied to every metadata variant of concrete (ID:251), but will not connect between them. 

Even if one includes:
matchTiles=concrete_orange concrete_yellow
connect=tile

The ctm will not connect between the two block variants.

The only way I know of how to have a ctm connect to a block other than itself is to have 'connect=material'. I would prefer not to use this as difference in material will cause complications in other areas, such as breaking sound, flammability, etc.

I would like to be able to set which blocks my ctm can connect to like in the overlay system.

https://imgur.com/a/qK8OT7i 

Here is the effect I want to make (in this case using the 'connect material' option). It's possible, but the lightest tone is a re-texture over sand, while the two darker textures use dirt/course dirt; resulting in odd sounds/unable to place certain features.

**Comment by sp614x** [comment]
CTM can connect only to the same block (tile, metadata, etc.).
Conecting to another block requires overlays which are placed on top of each other.
For example if there are CTM configurations for stone-dirt, stone-sand, stone-gravel and stone-cobblestone then the block in the middle has to get 4 different transition at the same time:

![image](https://user-images.githubusercontent.com/16635441/50006145-131ea280-ffad-11e8-948d-544ae9315231.png)

The `method=overlay` and the other overlay variants can be used for block transitions: 
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/ctm.properties#L74
