### ISSUE TITLE
New uniform or macro for field-of-view option.

### ISSUE THREAD

**Issue by jcm2606** [sp614x/optifine#2107]
One of the newer effects we're doing in Continuum requires us to override the game's FOV with a custom one we're calculating in the shader. All the code is in place and working, however the code needs to know the game's FOV in order to calculate our custom FOV, which is a problem.

Currently the only way to get the game's FOV is to simply ask the user through a shader option, however that requires manual input, and is quite tedious given how many increments we'd have to support.

If Optifine could provide the game's FOV through a uniform or macro, it would be a simple drop-in replacement, and would work perfectly.

**Comment by sp614x** [comment]
Can't the FOV be calculated from some of the matrices?

**Comment by zombye** [comment]
You can easily calculate the FOV from the matrices. `verticalFov = 2 * atan(1 / gbufferProjection[1].y)`

**Comment by sp614x** [comment]
This should be possible with a custom uniform: 
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.properties#L326
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.properties#L358
