### ISSUE TITLE
[Feature Request] Ability to specify what blocks a ctm can connect to.

### ISSUE THREAD

**Issue by ghost** [sp614x/optifine#2108]
https://imgur.com/a/UsgXgYr

The image linked above presents three different sets of ctm; ‘course dirt’ and ‘dirt’ both use classic ctm with 47 tiles, while the clay has a repeat ctm applied.

The ctm’s for ‘dirt’ and ‘course dirt’ have the following information in their .properties files:

[Dirt]                                             
tiles=1-47                                     
method=ctm                               
matchBlocks=3                            
metadata=0                                
connect=material  

[Course Dirt]
tiles=1-47
method=ctm
matchBlocks=3
metadata=1

In this case, the ctm for dirt only connects to course dirt because I have specified it to connect to the same material. Course dirt will not connect because I have not specified it to do the same. 

The reason why I go to this trouble is because if the dirt did not connect only to the course dirt the lighter border found in the right circled area would appear on the left side also, thereby drawing a line between the two ctm’s.

Dirt has different breaking/placing sounds, it also accepts different types of plants. I would like all three ctm’s to apply to the same material type of sand, with each block having a different metadata. 

Hence, I would like you to add the ability to specific exactly what block ID’s/metadata’s a ctm can connect to, akin to the one utilised by the overlay system, to all ctm types, or at least classic ctm.

**Comment by sp614x** [comment]
If I understand correctly you want dirt and coarse dirt to use different textures, but still to connect to each other. Is this correct?

The textures in the screenshot are very similar and it is quite hard to say how they are connecting. Using distinct textures would make it easier to understand. You can use for example the CTM template textures with different colors, it would also show which exact texture is being used.

**Comment by Jiingy** [comment]
Closing for lack of response from the original poster.
