### ISSUE TITLE
Entities that fall out of the world cast "ghost" dynamic light

### ISSUE THREAD

**Issue by quat1024** [sp614x/optifine#211]
When an entity falls out of the world, the dynamic light that it casted doesn't go away with it. You have to update the dynamic light for the light to go away.

[Gif demonstration](https://cloud.githubusercontent.com/assets/2068021/16543373/97536bbe-409f-11e6-8546-7eb72d1d721b.gif)

**Comment by HeartyYF** [comment]
It's interesting.
In an early version,if I change my gamemode to spectator with a torch held in my hand(or in my head slot),it will still shine,but now it's fixed.As you can see,everything is going to be better,every issue will be fixed,so wait patiently.

**Comment by sp614x** [comment]
Fixed, coming in next preview C2 for 1.10.2.
Spectator mode is fixed to not give light.

**Comment by HeartyYF** [comment]
I know...I said"in a early version".

**Comment by sp614x** [comment]
Preview C2 for 1.10.2 with a bugfix is out.
