### ISSUE TITLE
Text is not showing correctly

### ISSUE THREAD

**Issue by StormyIceLeopard** [sp614x/optifine#2113]
The attached photo shows a sign where the second line does not show all the text, (With or without my faithful texture pack). This is not just signs, it's also the MOTD and books. Anyone else having these issues?
The second line should be: The BlizzardCraft

![2018-12-16_10 00 11](https://user-images.githubusercontent.com/10292779/50055201-88a78180-0119-11e9-9e76-383314428d80.png)

**Comment by ozals** [comment]
Have you check if this happens without optifine?

**Comment by StormyIceLeopard** [comment]
According to 2 of my friends, which have issues with optifine on the linux launcher, it shows up correctly. I even asked him to screen share and they see it correctly. I can't run Minecraft well without optifine but if I have to in order to get someone to fix this I will.

**Comment by ozals** [comment]
1. Tell your linux friend to use do this https://github.com/sp614x/optifine/issues/1818#issuecomment-427983171, it should fix his problem
2. I say try it for yourself without optifine, it could be a problem on your side

**Comment by StormyIceLeopard** [comment]
Left is without optifine and right is with optifine. Both 1.13.2 and the same Faithful texture pack.
![image](https://user-images.githubusercontent.com/10292779/50055518-30bf4980-011e-11e9-9041-0adc0e92f970.png)

So can someone please fix this?

**Comment by Quavelen** [comment]
@StormyIceLeopard, you're using an outdated version of faithful. OptiFine handles the font spacing differently now, so either update the pack or delete the text file called "ascii.properties" inside `\AppData\Roaming\.minecraft\resourcepacks<pack name>\assets\minecraft\textures\font`.

**Comment by StormyIceLeopard** [comment]
Actually, I am using the latest version. I guess the creator never consider that.
But thanks for letting me know what to delete that might fix the issue.
I'll edit this post with the results.

**Comment by Quavelen** [comment]
@StormyIceLeopard hmm... you're right. I must not remember deleting the file myself, then. I'll open an issue on [the author's github](https://github.com/FaithfulX32/Faithful/issues) and let him know.

**Comment by StormyIceLeopard** [comment]
> @StormyIceLeopard, you're using an outdated version of faithful. OptiFine handles the font spacing differently now, so either update the pack or delete the text file called "ascii.properties" inside `\AppData\Roaming\.minecraft\resourcepacks\<pack name>\assets\minecraft\textures\font`.

Doing this fixed the issue. Thanks for the help.
