### ISSUE TITLE
Sky Glitch with shaders

### ISSUE THREAD

**Issue by MrProton657** [sp614x/optifine#2117]
Affected Versions:

Minecraft: 1.12.2
Forge: 1.12.2 - 14.23.3.2768
Optifine: HD_U_E3 (Sildurs Vibrant Shaders: v1.19)

Discribtion:
Then I turn on any shader I get weird sky glitches the I`m looking down:
https://ibb.co/D78GfX3
https://ibb.co/ccvP32P

**Comment by sp614x** [comment]
Does this happen with other shaders (SEUS, Chocapic13, QOL)?
https://shaders.wikia.com/wiki/Shader_Packs

**Comment by MrProton657** [comment]
Fixed!, just diable weaksky in Astral Sourcery
