### ISSUE TITLE
Colored / White dots between block connections (Optifine 1.13.2 HD U E5 - MC1.13.2)

### ISSUE THREAD

**Issue by Gardenian** [sp614x/optifine#2119]
So I am not getting this in vanilla Minecraft, just after installing Optifine, I did a complete fresh Minecraft and Optifine install to verify it was still happening.  I will post a few screen shots.

![2018-12-17_23 55 25](https://user-images.githubusercontent.com/45958491/50133554-15595900-025a-11e9-820d-03b0c787cb6c.png)

![2018-12-18_00 13 04_4](https://user-images.githubusercontent.com/45958491/50133563-20ac8480-025a-11e9-906a-e5ab023ec93f.png)

![2018-12-18_00 13 03](https://user-images.githubusercontent.com/45958491/50133569-23a77500-025a-11e9-82ff-4408d512a1fa.png)

This doesn't always happen but once it appears and starts it seems to get worse and I notice it everywhere, its not always in the dark either just the most noticeable and why I choose to take pictures in the dark.

Any help is appreciated, thank you for your time!  I love your mod and its let me use shader packs and really change the game for me, this little problem just drives me crazy.

Edit: You obviously have to click these shots and zoom in to really see what im talking about.

**Comment by sp614x** [comment]
Have you tried to disable Render Regions?

**Comment by Gardenian** [comment]
I have tried disabling render regions and so far so good, I also think the problem is happening in the daytime (I'm mostly underground but I've been carrying a bed and trying to sleep when I notice the problem and it always seems to be day).  I will update this post in a few hours (I'm currently playing going to keep an eye on this), I will report back at the end of the session and let you know how it ends up.  I appreciate your quick reply and thank you so much for getting personally involved with this.

**Comment by Gardenian** [comment]
After playing about three hours in all manner of environments I can say that your suggestion fixed the problem completely.  

Thank you so much, having the author of one of the biggest Minecraft mods take the time to respond to my issue personally and help me fix the problem blows me away.
