### ISSUE TITLE
CIT doesn't support references to assets/minecraft/textures

### ISSUE THREAD

**Issue by EskiMojo14** [sp614x/optifine#212]
When I create a .properties file to use a texture in textures/item, the launcher throws an error, and removes all the packs. 

> [15:15:15] [Client thread/INFO]: Caught error stitching, removing all assigned resourcepacks
> java.lang.NullPointerException
>     at bpg.a(FaceBakery.java:198) ~[bpg.class:?]
>     at bpg.fillVertexData(FaceBakery.java:185) ~[bpg.class:?]
>     at bpg.makeQuadVertexData(FaceBakery.java:111) ~[bpg.class:?]
>     at bpg.makeBakedQuad(FaceBakery.java:75) ~[bpg.class:?]
>     at bpg.a(FaceBakery.java:57) ~[bpg.class:?]
>     at CustomItemProperties.makeBakedQuad(CustomItemProperties.java:839) ~[CustomItemProperties.class:?]
>     at CustomItemProperties.bakeModel(CustomItemProperties.java:825) ~[CustomItemProperties.class:?]
>     at CustomItemProperties.makeBakedModel(CustomItemProperties.java:692) ~[CustomItemProperties.class:?]
>     at CustomItemProperties.updateModel(CustomItemProperties.java:648) ~[CustomItemProperties.class:?]
>     at CustomItems.updateModels(CustomItems.java:291) ~[CustomItems.class:?]
>     at TextureUtils.resourcesReloaded(TextureUtils.java:301) ~[TextureUtils.class:?]
>     at TextureUtils$1.a(TextureUtils.java:334) ~[TextureUtils$1.class:?]
>     at bxi.c(SourceFile:105) ~[bxi.class:?]
>     at bxi.a(SourceFile:93) ~[bxi.class:?]
>     at bcx.f(Minecraft.java:825) [bcx.class:?]
>     at bhq.a(SourceFile:133) [bhq.class:?]
>     at bft.a(SourceFile:346) [bft.class:?]
>     at bhq.a(SourceFile:141) [bhq.class:?]
>     at bft.k(SourceFile:409) [bft.class:?]
>     at bhq.k(SourceFile:77) [bhq.class:?]
>     at bft.p(SourceFile:386) [bft.class:?]
>     at bcx.t(Minecraft.java:1814) [bcx.class:?]
>     at bcx.av(Minecraft.java:1138) [bcx.class:?]
>     at bcx.a(Minecraft.java:448) [bcx.class:?]
>     at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
>     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
>     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
>     at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
>     at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) [launchwrapper-1.7.jar:?]
>     at net.minecraft.launchwrapper.Launch.main(Launch.java:27) [launchwrapper-1.7.jar:?]

.properties in question: 

> texture=textures/items/ruby.png
> nbt.display.Name=Ruby
> matchItems=264

**Comment by sp614x** [comment]
Fixed in preview C3 for 1.10.2.
