### ISSUE TITLE
Shaders: Specular/Normals/Emissive atlas as custom texture

### ISSUE THREAD

**Issue by zombye** [sp614x/optifine#2120]
I'm not sure if this is possible yet or not, but I need access to the atlases for specular, normals, and emissive in composite, in addition to the regular texture atlas.

If it's already possible, it doesn't seem to be documented anywhere and I haven't been able to guess the path I need to use.

**Comment by sp614x** [comment]
OptiFine 1.13.2_HD_U_E6_pre2
 - extended shaders custom textures with normal/specular variants (#2120)

https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.properties#L100
