### ISSUE TITLE
Allow for entity rendering overrides using the resourcepack

### ISSUE THREAD

**Issue by Joeywp** [sp614x/optifine#2121]
As mentioned in several other issues such as #2088 and my own #1214, 3d models attached to entities become invisible when look at from specific angles/locations. As a work around, it could be useful if entities could be forced to render, as discussed on Discord.

A proposal for this could be something the likes of:
```
File assets/minecraft/optifine/entity.properties
============
alwaysRender=armor_stand[head] arrow player[head,offhand,mainhand]
```

Basically it's a space-separated array, where either an entity can be forced to always be overriden (`armor_stand`), or only when it's wearing items in specific slots, like the helmet (`armor_stand[head]`) or a collection of slots (`armor_stand[head,offhand]`).

I'm not sure if there is already a "standard" for slotnames, but if not, these could be (following the internal names for these slots as found in Spigots EnumItemSlot):
- head
- chest
- legs
- feet
- mainhand
- offhand

This workaround would have the possibility to at least partially fix this problem

**Comment by 78wesley** [comment]
This would be great !

**Comment by JanUmbach** [comment]
Any updates on this? :)
