### ISSUE TITLE
fire animation bugged

### ISSUE THREAD

**Issue by requzzic2** [sp614x/optifine#2124]
wen you disable terrain animation all fire animations stop working (even if you have fire animation turn on) this problem is only for the 1.13+ update

**Comment by Quavelen** [comment]
I can confirm this. The "Fire Animated" function seems to have been bound with the "Terrain Animated" setting, whereas the "Fire Animated" setting currently does nothing. I am using E6_pre2 to test. Here is proof:

![image](https://giant.gfycat.com/LawfulBowedAmberpenshell.gif)

**Comment by sp614x** [comment]
Fixed, coming in next preview.
