### ISSUE TITLE
Stronger emissive light from beacon beams

### ISSUE THREAD

**Issue by woody77** [sp614x/optifine#2141]
The beams of beacons appear to emit a soft blue glow, which when compared to the brightness of the beam itself doesn't seem to match.  Can this be adjusted somehow?

**Comment by sp614x** [comment]
The beacon beam doesn't emit light.
The beam itself is a texture which can be changed with a resource pack.

**Comment by woody77** [comment]
After playing around with emissive textures, I see that what I should have said is that the beacon beam should be added to dynamic lighting.  More reading on dynamic_lights.properties suggests that I'd need to create a mod to allow the addition of new entities/items to the dynamic lighting model?

**Comment by sp614x** [comment]
The real life beams are not emitting light, except for some minimal reflections in dust particles.
An object placed next to a beam would still be dark.

**Comment by woody77** [comment]
I think I see what you're getting at.  If it was an actual beam of light, the only scattering to the sides would be off of the dust particles that are making it visible (like a spot-light beam)?

**Comment by xerotrinity** [comment]
> The real life beams do not emit light, except for some minimal reflections in dust particles.
> An object placed next to a beam would still be dark.

Totally, I think a ~1' wide visible beam would emit lots of light.  It's not like a laser where you only see the point of contact ya know?
