### ISSUE TITLE
I can't buy an cape.

### ISSUE THREAD

**Issue by Yazooyy** [sp614x/optifine#2143]
I can't purchase an cape with paymentwall,  it says

**We were not able to authorize your card
Please contact your bank to unblock payments to merchant "FasterPay.com" located in London, UK**

But, it says my card doesn't block transactions with fasterpay, any ideas how to fix?

**Comment by Yazooyy** [comment]
I am also paying with an visa card prepaid

**Comment by Artuto** [comment]
It probably doesnt accept prepaids cards then.

**Comment by sp614x** [comment]
You should contact Paymentwall, only they can answer this.
