### ISSUE TITLE
"Custom Fonts" option set to OFF does not work

### ISSUE THREAD

**Issue by HalfOfAKebab** [sp614x/optifine#2145]
Pretty simple, setting "Custom Fonts" to OFF doesn't disable custom fonts.

**Comment by sp614x** [comment]
The resource pack may include a font that is to be used only when OptiFine is installed. It could use custom character widths and it would probably not look good when used in vanilla.

Default font: `assets\minecraft\textures\font\ascii.png`
OptiFine font: `assets\minecraft\optifine\font\ascii.png`

The option Custom Fonts disables the OptiFine version of the font.

If the resource pack changes the vanilla font with a HD version, then it can't be restored to the vanilla version.
