### ISSUE TITLE
Banner colors from capes don't match real colors.

### ISSUE THREAD

**Issue by Napero44** [sp614x/optifine#2146]
Since the "World of color" update, the colors of banners, when used as capes, don't match the real colors. ex.
![2019-01-02_17 06 53](https://user-images.githubusercontent.com/46330358/50612434-c5fd6480-0eb8-11e9-8564-3c00fdf28dd0.png)

**Comment by KaiAF** [comment]
This is something related to needcoolshoes, we can't fix this as far as I know. This would require us to create our own cape editor.
