### ISSUE TITLE
Minecraft not allowing custom fullscreen resolution

### ISSUE THREAD

**Issue by GreyAsteroid** [sp614x/optifine#2147]
When I try to use fullscreen while using a custom resolution (created via Nvidia drivers) Minecraft resets to the default resolution for the display and there's no option for the custom resolution via the in game option.

I've tried forcing the correct resolution via options.txt but it ignores it. The custom resolution is actually just display overclocking in my case (1080p60 to 1080p75) and the only option in the fullscreen slider other than "current" is 1152x865 75 24 bit.

It's exceptionally annoying because this wasn't an issue before 1.13 and I can see the game go fullscreen without a resolution change for a split second before the display goes black and it reverts to 60hz.

I'm not sure if this is an Optifine issue or a Minecraft one but I figure I'd at least bring it up here to see if there's anything that can be done.

**Comment by sp614x** [comment]
The video modes are reported by the LWJGL library and the game can only use modes which the display supports.  If LWJGL can't see the custom resolution, then the game can't use it.
