### ISSUE TITLE
Flicker after starting Minecraft with 1.12.2 HD U E3

### ISSUE THREAD

**Issue by UnknownEvil** [sp614x/optifine#2150]
So this happens upon loading into the game. You can see how many mods I have, though (Edit: you can't, but it's 100+). Never happened until I installed optifine (very last). Stops permanently when I resize window.
![image](https://puu.sh/Cs6UG/ab33e5cc2d.png)
Imagine it flickers

**Comment by GracieTheLatias** [comment]
i am having this exact issue.https://i.gyazo.com/40f1e7421930be9a078a01c52b65bf5f.png

**Comment by UnknownEvil** [comment]
Seems to go away if I click the resize window button

**Comment by UnknownEvil** [comment]
Modded?

**Comment by Siavel** [comment]
I'm running a 100+ modded pack with Optifine, too. Same pack was distributed to my fam and friends. I'm the only person out of over 10 people that had the glitching/strobing (oh boy, that's a big epilepsy warning there) issue. When I uninstalled and reinstalled the pack, it completely stopped.

No idea from my end what caused it.

**Comment by sp614x** [comment]
Most probably a conflict with one of the 100+ installed mods.
Looks like it is not reproducible.
