### ISSUE TITLE
Advanced Animations: `enchanting_table_book.png` not supported

### ISSUE THREAD

**Issue by MushirMickeyJoe** [sp614x/optifine#2153]
I'm fairly sure everything I wrote is in order, but nothing is changing in-game, and there's no errors in the log.

**Comment by sp614x** [comment]
Minimal resource pack?

**Comment by MushirMickeyJoe** [comment]
[Advanced Animation MRP.zip](https://github.com/sp614x/optifine/files/2747399/Advanced.Animation.MRP.zip)

**Comment by Regnander** [comment]
@MushirMickeyJoe Did you manage to solve this issue or did you close it by accident?

**Comment by MushirMickeyJoe** [comment]
I closed it because the issue I was having had nothing to do with how the enchantment book was rendered, I found it was because of [this](https://github.com/sp614x/optifine/issues/2158).
