### ISSUE TITLE
Advance Animation: Would be neat to have animations be proximity based

### ISSUE THREAD

**Issue by MushirMickeyJoe** [sp614x/optifine#2154]
For example, the animation won't play until the player is within a certain radius of a texture that has an advanced animation.

I could make the pages of the enchanting table book shimmer when the player gets close enough for the book to open, so the animation takes a couple seconds to kick in.

P.S. Emissive advanced animations?? 😁

**Comment by sp614x** [comment]
This is quite complex to implement and it would probably look strange as all blocks will animate at the same time. There is only one texture that is being animated.
