### ISSUE TITLE
payment iframe not scrolling

### ISSUE THREAD

**Issue by Jm56Z** [sp614x/optifine#2162]
I was trying to donate, using the non-fasterpay Credit/Debit VISA card method.

I was unable to scroll through the iframe, thus preventing me from entering my credentials - or correcting errors if any.
And please don't tell it's PaymentWall's fault, I wouldn't trust you -I'm a programmer.

**Comment by sp614x** [comment]
The payment iframe is provided by paymentwall, only they could fix it.

**Comment by Jm56Z** [comment]
Indeed, It's been quite a long time I didn't use iframes. The scrolling attribute is no longer supported in HTML5 (Which is utterly stupid)
