### ISSUE TITLE
Optifine cape locked my account?

### ISSUE THREAD

**Issue by orahh** [sp614x/optifine#2165]
I have been using Optifine for around 6 years and never had a problem until now. I could log into my account and after contacting support i got an email saying my account has been permanently suspended. Only thing i could think of that would cause this is logging into optifine to change my cape since it would log me out of my account in the past. Im hoping this is a glitch and i will get my account back but mojang arent really helping out much so i was wondering if i could get some help here.

**Comment by Regnander** [comment]
> i got an email saying my account has been permanently suspended

Account scamming is not that uncommon. From what address did you get that email?

**Comment by orahh** [comment]
support@mojang.desk-mail.com

**Comment by Regnander** [comment]
Yep, that looks like a scam address, since the domain is desk-mail.com instead of mojang.com. **_DO NOT_** give them your account details.

**Comment by Regnander** [comment]
By the way have you tried logging in to your Minecraft account in the launcher to see if it works?

**Comment by sp614x** [comment]
This something that only Mojang could fix.

**Comment by orahh** [comment]
> By the way, have you tried logging in to your Minecraft account in the launcher to see if it works?

yes ive tried everything and im not getting in my account or getting any password reset emails from mojang

**Comment by Etrainquandt17** [comment]
Have you tried contacting the actual mojang support?

**Comment by orahh** [comment]
> Have you tried contacting the actual mojang support?

yes i have but they havent gotten back to me yet.

**Comment by Etrainquandt17** [comment]
Alright, hopefully you get your account back.

**Comment by orahh** [comment]
> Alright, hopefully you get your account back.

me too

**Comment by orahh** [comment]
welp little update i guess it was actually them.
![052cf2ff73ed1fe3190e28cc354da67f](https://user-images.githubusercontent.com/46732020/51433132-09660b80-1bf9-11e9-974a-6484c0ce712b.png)
