### ISSUE TITLE
Optifine (ANY VERSION) will not work! Help?

### ISSUE THREAD

**Issue by Pfand97** [sp614x/optifine#2170]
Hey,

I have recently downloaded and attempted to install optifine 1.13.2 after becoming interested in the boosted performance and graphics that it has to offer. However, after attempting to run optifine after it has finished downloading, I have constantly run into an issue that seems to be unfixable. Rather than the normal "optifine installer" tab popping up, opening optifine redirects me to an outdated version (1.6) Minecraft launcher. I am then prompted with a message which reads, "It looks like you've used a newer launcher than this one! If you go back to using this one, we will need to reset your configuration." The two options which I am able to click read, "Never mind, close this launcher." while the other is "I'm sure I'll reset my settings". I have selected both options, the first simply exits out of the outdated launcher, while the other option (resetting my settings) asks me to login. Nevertheless, the outdated Minecraft launcher refuses to accept both my username, email, and password for my account. I have verified and reset my password several times since then- to no avail. After hours of dabbling with Minecraft's settings and reinstalling both optifine and Minecraft I have not found any solution, nor have I narrowed down the exact problem. I exclusively play on Minecraft version 1.13.2 and have the latest update for Java. I am simply stuck on this issue, and unable to use any version of optifine for Minecraft. I've posted this thread to several other Minecraft related forums for help and have been directed to this forum. As a user suggested in one of the previous forums- they believed that a hidden launcher may have been causing the issue but I have yet to find any. Any input is welcome!

Thank you!

**Comment by Pfand97** [comment]
Update: I am able to login to the Outdated 1.6 launcher, after doing so it reverts back to the 1.13.2 launcher and does not make any changes.

**Comment by realjackasterisk** [comment]
some screenshots might be necessary here. what do you mean "optifine installer **tab**"?

**Comment by sp614x** [comment]
You can try with JarFix: https://download.cnet.com/Jarfix/3000-18512_4-77571216.html
It can restore the JAR file association so that JAR files start with Java.
Relevant #943, #906, #763.
