### ISSUE TITLE
1.13.2 HD_U_E5 Incorrect Fire Animation Control

### ISSUE THREAD

**Issue by Trenly** [sp614x/optifine#2180]
I checked and I have Fire Animated and Flame Animated on. Textures Animated is on. Not using any resource pack, just the default textures. Fire has no animation, but is animated when I go into vanilla 1.13.2

**Comment by Spitfyre03** [comment]
I'm having the same issue as well. Version HD_U_E5. Won't animate for vanilla or custom resource packs

**Comment by Regnander** [comment]
I'm guessing that you two have disabled "Terrain Animated". Here are my settings:

![ezgif-4-0662c6b40701](https://user-images.githubusercontent.com/17113053/52182323-3ec74780-27fc-11e9-8d19-1745c2ddf242.gif)

**Comment by Spitfyre03** [comment]
I have it disabled, yes

**Comment by Regnander** [comment]
Have you tried enabling it to see if your fire gets animated?

**Comment by Trenly** [comment]
Having terrain animated makes the fire animated. However, I am leaving this issue open since there is a specific setting for fire animation which I feel should be unaffected by terrain animated.  Additionally, with Terrain Animated, but Fire and Flame animations off the fire is still animated both when it is on the ground, and when the players model is on fire.

**Comment by sp614x** [comment]
Fixed, coming in next preview.
Relevant: #2124
