### ISSUE TITLE
[SUGGESTION] Optifine capes update

### ISSUE THREAD

**Issue by Zillandroid** [sp614x/optifine#2186]
Hi, i'm Zillandroid aka Felipe.B and here is my suggestion.

> I would like (and I suppose a lot of people too) to have an optifine player with a functional texture with the new elytras

 And here is how. (explanation in the end)

I always used (and i still use it) optifine and i love the option to donate to adquire a OF cape, but the thing is there's not a OF cape elytra's texture, so i started to investigate.
i downloaded a texture of the OG OF cape and Minecon cape (for the elytras texture) and i begin to shape it on GIMP.
[This is my first try](https://i.imgur.com/WONxami.png)
![optifine_cape_elytra_freetouse](https://user-images.githubusercontent.com/26658509/52319540-09ac2800-29a9-11e9-89ca-2d4e4e746682.png)
 The new texture for the elytras looks great, but I realized that it would be very complicated to code it, so I decided to simplify it without losing quality.
[This is my second attempt](https://i.imgur.com/JvHV2Y0.png)
![optifine_cape_elytra_freetouse](https://user-images.githubusercontent.com/26658509/52319679-d3bb7380-29a9-11e9-8dc1-1e858ce9c1e5.png)
OG OFcape texture
![2019-02-06_00 01 14](https://user-images.githubusercontent.com/26658509/52319768-40cf0900-29aa-11e9-86f2-5d32d7f069c7.png)
New elytra texture ""easier to code""(because i know it's hard to code )
![2019-02-06_00 01 33](https://user-images.githubusercontent.com/26658509/52319743-2ac14880-29aa-11e9-9bb7-e5e1fe1e16f0.png)
![2019-02-06_00 02 14](https://user-images.githubusercontent.com/26658509/52319750-301e9300-29aa-11e9-8ec5-810efb2468bd.png)
i made 3 textures to experience(This one is for my ["alt"](https://i.imgur.com/bQOaA7H.png))
![optifine_cape_elytra_freetouse_simple colorberries](https://user-images.githubusercontent.com/26658509/52320072-e46ce900-29ab-11e9-9ae6-2742ab5d19c0.png)

![2019-02-05_23 57 49](https://user-images.githubusercontent.com/26658509/52319863-a1f6dc80-29aa-11e9-8245-a916b90045e3.png)
![2019-02-05_23 58 07](https://user-images.githubusercontent.com/26658509/52319874-ade29e80-29aa-11e9-981a-8ee50b3b72ed.png)
![2019-02-05_23 53 41](https://user-images.githubusercontent.com/26658509/52319921-ef734980-29aa-11e9-8162-01aa79d0816b.png)
Finally before the explanation of ""how to do it"" i tried to made a version of my actual OF cape ([Zillandroid](https://i.imgur.com/Udsbfe5.png))
![zillandroid cape xd](https://user-images.githubusercontent.com/26658509/52320115-357cdd00-29ac-11e9-93ed-81ebbcd71038.png)
![2019-02-06_00 23 37](https://user-images.githubusercontent.com/26658509/52320141-60673100-29ac-11e9-9555-09dcd5b583b7.png)
![2019-02-06_00 23 46](https://user-images.githubusercontent.com/26658509/52320146-63fab800-29ac-11e9-9417-58812c9aa6db.png)
![2019-02-06_00 24 35](https://user-images.githubusercontent.com/26658509/52320148-69580280-29ac-11e9-9ee0-906f2c7b1284.png)
###  "EXPLANATION"
The new images have to be 64x32 pixels to have space for the elytra texture.
![captura de pantalla de 2019-02-05 23-45-46](https://user-images.githubusercontent.com/26658509/52320253-1468bc00-29ad-11e9-9ad7-b52c875e3a20.png)
You use the same system to generate a cape in the same place (left-top), but you copy the back layer of the OF cape and paste it on the elytra texture position
![captura de pantalla de 2019-02-06 00-13-09](https://user-images.githubusercontent.com/26658509/52320362-b1c3f000-29ad-11e9-9930-c0e0d31b5b3b.png)
but if you do that u will notice that its left 3 lines of pixels so it will be necessary to add 3 lines of lighter tones to the degraded.
![captura de pantalla de 2019-02-05 23-48-57](https://user-images.githubusercontent.com/26658509/52320447-2008b280-29ae-11e9-9173-ed160290e107.png)
![captura de pantalla de 2019-02-05 23-49-02](https://user-images.githubusercontent.com/26658509/52320452-239c3980-29ae-11e9-9e07-b6d05859f693.png)
You have to select and remove this specific pixels and it's pretty much done
![captura de pantalla de 2019-02-06 00-14-37](https://user-images.githubusercontent.com/26658509/52320638-5430a300-29af-11e9-9cb5-a827e8ca4d84.png)
the only thing left is to add the "OF" letters in the new texture
![captura de pantalla de 2019-02-06 00-19-22](https://user-images.githubusercontent.com/26658509/52320687-7e826080-29af-11e9-8e21-fe37cdcfd4d2.png)
("by zilla free to use" should be removed xD)
and thats it!
Sorry for my english (i know its bad), and sorry if i sounded rude or mean.
Thanks for your mod! and your time that you loose reading this :c
Bye! 
[Zillandroid](mailto:Felipe@ayste.men)

**Comment by realjackasterisk** [comment]
#241, #1848

Donator elytra are already being worked on. They're actually pretty much finished on the client, all that's really left is to update the website.

**Comment by Zillandroid** [comment]
woah <3

**Comment by Zillandroid** [comment]
woah!!! <3 
![sp614x](https://user-images.githubusercontent.com/26658509/52323765-1c305c80-29bd-11e9-8445-847d5c69c894.png)
@sp614x that look awesome!

**Comment by Zillandroid** [comment]
i did this for nothing hahahahah, i should checked the website first xD <3<3<3<3<3

**Comment by sp614x** [comment]
The OptiFine cape elytra is already active.
