### ISSUE TITLE
Can't launch Optifine

### ISSUE THREAD

**Issue by Milouvert** [sp614x/optifine#2187]
Minecraft launcher just had an update, Optifine can no longer be launched. 

`Internal error. Preparing OptiFine-1.13.2_HD_U_E5.jar`
```
Name: Preparing OptiFine-1.13.2_HD_U_E5.jar
Error details: std::exception
```
![minecrafterror](https://user-images.githubusercontent.com/38847520/52373715-59cacf00-2a29-11e9-890a-991cd5e890e3.png)

I'm usually using Optifine on 1.12, but I saw it wasn't working any better on 1.13. Was working earlier in the day. Tried reinstalling.
On a MacBook, macOS 10.14.

**Comment by Milouvert** [comment]
Minecraft 1.12 still works fine.

**Comment by Milouvert** [comment]
1.13 as well..

**Comment by Quavelen** [comment]
If you're using the new experimental launcher, then get rid of it and use the current standard. The latest update to it broke the usage of custom/modified jars. I had this same issue, until I switched.

**Comment by Milouvert** [comment]
Thanks @Quavelen , trying it now!

**Comment by Milouvert** [comment]
> If you're using the new experimental launcher, then get rid of it and use the current standard. The latest update to it broke the usage of custom/modified jars. I had this same issue, until I switched.

It worked, thank you very much!
