### ISSUE TITLE
Website reported as malicious

### ISSUE THREAD

**Issue by megaxlr** [sp614x/optifine#2189]
Following what happened in early august, the website seems to be blocked by Yandex.ru again.

Browser: Opera Stable
OS: Debian GNU/Linux 9 stretch

![image](https://user-images.githubusercontent.com/8215278/52464786-7a576e00-2b7c-11e9-9f24-c56dbb566651.png)

**Comment by sp614x** [comment]
According to VirusTotal all engines report the site as clean:
https://www.virustotal.com/#/url/18bf8c18f49875d4a41a5170f7748f9bef6056c2d582a2b282c8b469147cc887/detection

Yandex Safebrowsing also marks it as clean.
