### ISSUE TITLE
Black texture at random item every time when i start client

### ISSUE THREAD

**Issue by Anapxist** [sp614x/optifine#219]
Hi,
I have problem with black textures. They can apper on sky(no clouds look like storm), minimap, minimap marks or any item in game.
![bug](https://cloud.githubusercontent.com/assets/20355531/16686181/07709494-4519-11e6-8529-ccc8a12fcc87.png)
Here it on chest. And it will stay till i exit and launch client again. After that other item will be black. I notice that only 1 item type got black texture at once. So if no black textures on items i use i can play, if they on my chests or lamps or pipe, i restart client till it gone. Any advice how could i fix it? I have this bug at leat at 2 different PC. I'm using OptiFine_1.7.10_HD_U_D4 coz D6 spam OpenGL Error: 1281 (Invalid value) in chat and log.

**Comment by sp614x** [comment]
Forge, other mods installed?
Is Chunk Loading set to  "Default"?
Resource pack, error log?

**Comment by Anapxist** [comment]
Forge 1614,Chunk loading: Default, Resours pack :F32-1.7.10 but problem stay after i switch to default textures. 
Mods:
![mods](https://cloud.githubusercontent.com/assets/20355531/16693868/eddf697a-453f-11e6-9d0c-fd866a4c1327.JPG)
And were i can find error log? when game run there is no errors in console after client start. If u mean latest.log. Its here:

[latest.zip](https://github.com/sp614x/optifine/files/354637/latest.zip)

**Comment by Anapxist** [comment]
There is no crash or something i can play normal but 1 item always get black texture and it random, not same every time.
