### ISSUE TITLE
Optifine Lighting is noticeably darker than vanilla 

### ISSUE THREAD

**Issue by squalchen** [sp614x/optifine#2190]
Optifine's light in 1.13.2_HD_U_E5 noticeably darker and less vibrant than vanilla at night. Graphics on fancy in both. Lighting on moody in of and vanilla.
Vanilla light.
![2019-02-10_12 30 32](https://user-images.githubusercontent.com/19976528/52537026-bd0d7780-2d2f-11e9-96ce-ef820103a17a.png)

Optifine 1.13.2_HD_U_E5
![2019-02-10_12 29 25](https://user-images.githubusercontent.com/19976528/52537054-170e3d00-2d30-11e9-8ce5-01973b9c9b2d.png)

**Comment by thatJARED** [comment]
These both look like the same screenshot.

**Comment by squalchen** [comment]
They aren't open the images in imgur and compare them zoomed in, Its especially noticeable in the glowstone

**Comment by sp614x** [comment]
It looks like only the chunks near the render distance are affected.
Looks like you have changed the option Video Settings -> Details -> Fog Start?
The night fog is black, so everything would appear slightly darker.
There is also the option Smooth Lighting Level which would also affect the lighting.
