### ISSUE TITLE
Weird mouse lag

### ISSUE THREAD

**Issue by VanillaCold** [sp614x/optifine#2193]
I seem to have a weird issue where my mouse lags. It's not related to chunk loading or resource packs, as I use the default resource pack.

I'm using Windows 10 and Intel HD Graphics.

**Comment by angrynerd** [comment]
By chance do you have vsync enabled? If not what is you average frame rate?
Depending on your settings i know intel hd could have an interesting time
with it.

**Comment by KaiAF** [comment]
No response from the author, if you are still having any issues, create a new ticket.
