### ISSUE TITLE
"Cape not found"

### ISSUE THREAD

**Issue by iNachoo** [sp614x/optifine#2196]
From one moment to another the cape stopped working. I looked at the optifine.net/capeChange page and it showed the typical image error where the design of my cape should be. When trying to change it it said "Cape not found for: iNacho_" I tried to deactivate it but it said the same, I tried to move it to another user but it said "Server Error". What happens? I am looking forward to your response. Thank you.
![screenshot_20190213-172019_chrome](https://user-images.githubusercontent.com/47622432/52766388-c2a3df80-3005-11e9-9b42-859b586ed5fb.jpg)
![screenshot_20190213-171958_chrome](https://user-images.githubusercontent.com/47622432/52766390-c33c7600-3005-11e9-9370-b380c839aadf.jpg)
![screenshot_20190213-172436_chrome](https://user-images.githubusercontent.com/47622432/52766392-c5063980-3005-11e9-9411-8839e98ae2e2.jpg)

**Comment by sp614x** [comment]
Fixed.

**Comment by sj3845** [comment]
I have the same problem
