### ISSUE TITLE
connected textures POM

### ISSUE THREAD

**Issue by Edo022** [sp614x/optifine#2199]
When I use POM with connected textures this happens... I tried to use other CTM methods but it doesn't work anyway
how can i fix it?
(texturepack 1024x POM, specular map, minecraft 1.13.2. shader BSL ultra)

![2019-02-15_16 30 25](https://user-images.githubusercontent.com/47669437/52867972-714d3a80-3142-11e9-8ab0-91843fb4d526.png)

**Comment by sp614x** [comment]
These are CTM overlays which are placed on top of the oiginal block texture.
POM is simulating a variable height effect, so it would probably not work when two textures are on top of each other.
