### ISSUE TITLE
Optifine cape elytra

### ISSUE THREAD

**Issue by Calvineries** [sp614x/optifine#2200]
_"OptiFine 1.13.2_HD_U_E6
 - fixed support for optifine cape elytra "_

Not work, just default elytra.

**Comment by Regnander** [comment]
It works for me. Have you tried messing around with the settings at [https://optifine.net/capeChange](https://optifine.net/capeChange)?

![](https://i.redd.it/1sipn1pumlf21.png)

**Comment by Calvineries** [comment]
![image](https://user-images.githubusercontent.com/29179001/52909566-bed4bf00-328a-11e9-9f54-3bbac41941df.png)
![image](https://user-images.githubusercontent.com/29179001/52909568-c4320980-328a-11e9-877c-53b83a8fd169.png)
I use banner optifine cape.
Not work.

**Comment by sp614x** [comment]
All OptiFine capes have been updated to include elytra.
