### ISSUE TITLE
[SUGGESTION] please add 2 step verification to change username for capes

### ISSUE THREAD

**Issue by BRENTGAMEZ** [sp614x/optifine#2201]
There should be 2 step verification when changing the username a cape is assigned to, If possible the 2 step verification should go through the donation email and have to confirm the change before changing the account name. That way if someone gets into the optifine account it be much harder for them to change the cape over to their username without permission and prevent the theft of the cape.

**Comment by 0xicl33n** [comment]
BUMP

My cape was taken today

**Comment by realjackasterisk** [comment]
This is a no-brainer, honestly. We need this.

**Comment by KaiAF** [comment]
closing in favor of #3796
