### ISSUE TITLE
Elytra texture does't load by default  after traveling by dimensions

### ISSUE THREAD

**Issue by Zillandroid** [sp614x/optifine#2203]
As the tittle says,  the issue is that after you have traveled by some dimension(nether,end [not tested with other mods])  wearing an elytra on you, the elytra texture dessapears, this coud be fixed by updating the capy via skin customization on the settings menu, but i still think that this should be updated(the cape texture) after arriving a new dimension to prevent this issue.

**Comment by sp614x** [comment]
Fixed, coming in next preview.
