### ISSUE TITLE
Cape change on 1.12.2 and 1.8.9.

### ISSUE THREAD

**Issue by MastaNub** [sp614x/optifine#2205]
A lot of people play 1.8/1.12 and barely anyone uses 1.13.2. sp614x, please fix.

**Comment by PointyDev** [comment]
Just download 1.13.2, update your cape then switch back? No point retroactively updating versions just for that, it was a security update, I doubt we need more vectors for error.

**Comment by realjackasterisk** [comment]
having to download a completely different version of the mod to change your cape seems like incredibly poor design, and i pray that it isn't kept that way.

i believe sp614x already plans to update **all** older versions to use the new authentication system anyway, so we'll just have to wait.

**Comment by sp614x** [comment]
Older versions would be updated on the next round of updates.

**Comment by MastaNub** [comment]
When can we expect next round of updates?

**Comment by asbyth** [comment]
this could probably be closed by now seeing as these have been added

**Comment by JackDotJS** [comment]
agreed
