### ISSUE TITLE
Screenshot Clears Typing 1.12.2-HD_U_E3

### ISSUE THREAD

**Issue by Trenly** [sp614x/optifine#2208]
Open Chat, Type in something, take a screenshot before pressing enter. Whatever I was typing gets cleared.

**Comment by Regnander** [comment]
This sounds like https://bugs.mojang.com/browse/MC-258, which was fixed in Minecraft 1.13-pre3.

**Comment by Trenly** [comment]
It may be related, however I haven’t experienced it previously.
