### ISSUE TITLE
Not raining even when Rain is on when using optifine 

### ISSUE THREAD

**Issue by veta76787** [sp614x/optifine#221]
I've encountered a problem while using optifine I was initially using the 1.10 version now I have updated to the 1.10.2 but I have the same problem with both, it won't rain at all when running the game on the optifine profile even when using the command /weather rain it does read on the chat "changing weather to rainy" but it won't start raining, when loading the vanilla profile it rains just fine, I'm not using other mods at all 
![rain issue](https://cloud.githubusercontent.com/assets/20378180/16711824/0ade5e82-4635-11e6-83cd-451b947c32aa.jpg)

![rain issue 2](https://cloud.githubusercontent.com/assets/20378180/16711823/0ad933e4-4635-11e6-89ce-0d8382483ee4.png)

![rain f3](https://cloud.githubusercontent.com/assets/20378180/16711833/4529b79e-4635-11e6-8c10-22d128578abe.png)

I tried toggling several settings and nothing has helped 
The issue is affecting all of my saved games while I'm running the optifine profile. I{m not sure when the issue started I just recently noticed it since I build a charged creeper farm, however I know that it didn't always affected me since I did got rain several times shortly after installing optifine, not sure what caused it to stop the rain.

**Comment by sp614x** [comment]
Video Settings -> Other -> Weather -> ON
Only effective in creative mode.
