### ISSUE TITLE
[1.12.2]Fix Forge Duping Class Load

### ISSUE THREAD

**Issue by NullSector76** [sp614x/optifine#2211]
Fix forge LaunchClassLoader.resourceCache there is no reason why this should ever be used or stored ob classes. Each time a new class is loaded it grabs it from the disk anyways. It causes massive memory leaks.

In your Class transformer add this and it will fix it
https://pastebin.com/BrSP2r5j

**Comment by sp614x** [comment]
OptiFine can't overwrite Forge classes, at least up to 1.12.2.
Maybe the 1.13 Forge mod loader would allow something like that.

**Comment by NullSector76** [comment]
You don't have to it's a memory thing

**Comment by NullSector76** [comment]
I already got this working without editing byte code simply by highjacking forge IClassTransformers to run the code very early then set the maps to a dummy map.

Note ClassLoaders sub classes don't have to store any classes the original object does that so both maps need to be cleared

**Comment by sp614x** [comment]
What is the LaunchClassLoader.resourceCache used for?

**Comment by sp614x** [comment]
I see that the LaunchClassLoader.resourceCache is from the Mojang Launcher, not from Forge.
Still not clear why it should be disabled.

**Comment by sp614x** [comment]
From the source it looks like the resourceCache is used to speed up resource loading, by skipping the loop over RESERVED_NAMES and toUpperCase() + startsWith().
https://github.com/Mojang/LegacyLauncher/blob/master/src/main/java/net/minecraft/launchwrapper/LaunchClassLoader.java#L337

**Comment by NullSector76** [comment]
hey I went ahead and wrote this code for you **add the static{}* class initializer in any one of your transformers.

Both LaunchClassLoader#resourceCache && LaunchClassLoader#cachedClasses can both be cleared safley tested in main modpacks.
https://pastebin.com/wpDPpgSP

**Comment by NullSector76** [comment]
Also you need to use a try/catch when setting the fields due to mods like fast craft replacing the class launcher. I already did this with my utility
https://github.com/asiekierka/FoamFix/issues/191#issuecomment-465622751

**Comment by asiekierka** [comment]
>gigs

The biggest modpacks I've seen around take up 2.5GB-3GB of the JVM heap with FoamFix installed. The resource cache, at its absolute worst, storing every class from every mod and then some, would take up about 150-200MB - but realistically it's usually a lot smaller.

**Comment by sp614x** [comment]
So this is a memory optimization for big mod packs.
This should be handled by Forge or by FoamFix.
