### ISSUE TITLE
[Suggestion] [1.13] Animation Setting for Bubble Columns

### ISSUE THREAD

**Issue by thatJARED** [sp614x/optifine#2212]
With the addition of the bubble columns in 1.13 they have seemed to cause a monumental amount of lag when the particles is set to 'All' or 'Decreased' but when set to minimal the FPS is significantly increased in the locations with a large amount of bubble columns. 

The suggestion is to add a setting in the animations tab to specifically reduce the particles of the bubble columns instead of having to set all the particles to minimal.

**Comment by Regnander** [comment]
Have you tried using 1.13.2_HD_U_E5_pre5 and above, since the lag was fixed in #2022?

**Comment by KaiAF** [comment]
Closing this as it doesn't seem like an issue anymore. If I'm wrong, let me know, please.
