### ISSUE TITLE
fix this issue

### ISSUE THREAD

**Issue by iRxshed** [sp614x/optifine#2213]
ur downloading links are not working any more plz fix  this and thank u

**Comment by Quavelen** [comment]
Um... no? The download links work fine. Here's a gif for you:

![2019-02-20_19-24-42](https://user-images.githubusercontent.com/19168008/53118539-3a619500-3545-11e9-8fc0-2ce2f9e14d92.gif)


Please make sure you are ***only*** using https://optifine.net/ and not any other site.

**Comment by sp614x** [comment]
The links are working.

**Comment by iRxshed** [comment]
k can u see this video


‫في الخميس، 21 فبراير 2019 في 1:41 م تمت كتابة ما يلي بواسطة ‪sp614x‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by iRxshed** [comment]
‫في الخميس، 21 فبراير 2019 في 5:56 م تمت كتابة ما يلي بواسطة ‪rashed
raami‬‏ <‪rashedraami1@gmail.com‬‏>:‬

**Comment by iRxshed** [comment]
check this video please !


‫في الخميس، 21 فبراير 2019 في 5:58 م تمت كتابة ما يلي بواسطة ‪rashed
raami‬‏ <‪rashedraami1@gmail.com‬‏>:‬

**Comment by sp614x** [comment]
There is no video link.

**Comment by iRxshed** [comment]
‫في الخميس، 21 فبراير 2019 في 6:08 م تمت كتابة ما يلي بواسطة ‪sp614x‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by iRxshed** [comment]
.

‫في الجمعة، 22 فبراير 2019 في 1:42 م تمت كتابة ما يلي بواسطة ‪rashed
raami‬‏ <‪rashedraami1@gmail.com‬‏>:‬

**Comment by iRxshed** [comment]
https://i.gyazo.com/ea8b21acb0369202b088e62c86346475.gif

**Comment by iRxshed** [comment]
check this

**Comment by Quavelen** [comment]
> https://i.gyazo.com/ea8b21acb0369202b088e62c86346475.gif



> check this


Lol, @iRxshed use the mirror link. It appears that AdFly is unusable in your country.

**Comment by iRxshed** [comment]
i fixed the problem but i have another problem

‫في الأحد، 24 فبراير 2019 في 12:00 ص تمت كتابة ما يلي بواسطة ‪Flannery Lue
Moore‬‏ <‪notifications@github.com‬‏>:‬

**Comment by iRxshed** [comment]
i cant see my cape and cape is on from skin customization ! ? what can i do
?


‫في الأحد، 24 فبراير 2019 في 8:42 ص تمت كتابة ما يلي بواسطة ‪rashed raami‬‏
<‪rashedraami1@gmail.com‬‏>:‬

**Comment by Quavelen** [comment]
> i cant see my cape and cape is on from skin customization ! ? what can i do ?

Open a new issue. You have a cape, but I don't know how to resolve that.

![image](https://user-images.githubusercontent.com/19168008/53296139-4bd6c580-3801-11e9-8420-c599bcedc0fc.png)
