### ISSUE TITLE
Optifine Donation Email Change

### ISSUE THREAD

**Issue by ghost** [sp614x/optifine#2215]
Hello sp614x, is it possible for me to contact you privately (Reddit, Discord ?) in order to have my Optifine donation email changed? I no longer use the email, I have to delete it, but I do not want to lose access to Optifine. And, in case it's not possible, do you consider implementing a feature like this in the future? I think it could be really helpful to account security.

Thanks!

**Comment by 51Percentage** [comment]
I think this should be a new feature. It really would be very helpful.

**Comment by ZenIsBestWolf** [comment]
Donation emails can't be changed, sorry! (And sorry for the very old reply.)
