### ISSUE TITLE
(1.13.2) CEM Banner doesn't differentiate between "slate" " top" and "stand." Defaults to "top"

### ISSUE THREAD

**Issue by sixfootblue** [sp614x/optifine#2217]
I've run into an issue with banner CEM. When adding new .jpm elements to the existing model, it seems to automatically attach/replace to the "top" part instead of the part I specified. I've tried attaching/replacing elements to "slate" "top" and "stand" and each time the element is attached to "top" regardless of what I chose. 

(I'm trying to replace the "slate" with the green part in this screenshot)
https://i.gyazo.com/50a48391913224bba894a16c2a8f2449.png

This seems to also apply to animations as well. When trying to set the new part's X rotation to match that of the slate, the values don't seem to copy over, leading me to believe it's defaulting to getting the rotation information from "top" or just not detecting "slate" at all. 

The settings in the files I'm using worked fine in 1.12.2

Here's a sample resource pack with the files:
https://drive.google.com/open?id=18LKI3tt0Xsu9mLJ4gkocSHJFWOSouA2T

**Comment by sixfootblue** [comment]
This issue is also present in the 1.14 releases of Optifine.

**Comment by ewanhowell5195** [comment]
Banner CEM was fixed in 1.15.2
