### ISSUE TITLE
Lost my cape

### ISSUE THREAD

**Issue by MathiasMC** [sp614x/optifine#2218]
I have first seeing my cape was moved to another account and it was not done by me and i cannot login with the email i have used 
Username: MathiasMC

The cape was moved from "MathiasMC" to "AtomicAdult" by the cape owner on 14.12.2018 15:22h.

**Comment by sp614x** [comment]
You can fix the cape here: https://optifine.net/login

**Comment by MathiasMC** [comment]
No donation found from email

**Comment by sp614x** [comment]
The donation for MathiasMC is from d********ing@gmail.com

**Comment by MathiasMC** [comment]
I dont have any email starting with d?

**Comment by MathiasMC** [comment]
i have writing a email to you can you maybe check that so i can write more personal information?

**Comment by MathiasMC** [comment]
I just have found transaction proof

**Comment by MathiasMC** [comment]
Can you change the email because that is not my email?

**Comment by MathiasMC** [comment]
And now you're probably not writing back?

**Comment by DataCrusade** [comment]
or... he's busy? have some patience?

**Comment by MathiasMC** [comment]
I know but i have seen an issue opened 2 days ago and he has not responded to that about email change so thats why im thinking he is probably not writing back

**Comment by MathiasMC** [comment]
> or... he's busy? have some patience?
I know but i have seen an issue opened 2 days ago and he has not responded to that about email change so thats why im thinking he is probably not writing back

**Comment by MathiasMC** [comment]
Does not matter i will just donate again because the i will support you :)
