### ISSUE TITLE
(Shaders) Textures are still enabled even if they're only declared in programs disabled by a profile

### ISSUE THREAD

**Issue by BruceKnowsHow** [sp614x/optifine#222]
The primary reason I was interested in profiles was that I thought they could be used to disable textures (such as shadowcolor) when they're not being used. Unfortunately that isn't the case.

I think the shadersmod is probably scanning the shaderpack and enabling the textures before it disables programs. The program disabling should completely remove files before the shaderpack is scanned to enable textures.

Right now, I already have a way to disable "composite" by just [placing its vertices offscreen](https://github.com/BruceKnowsHow/Ebin-Shaders/blob/7d64cdb3d8c3a66b3d154c6c0bfe80111f30ad98/shaders/composite.vsh#L36). This method seems to be just as fast as disabling "composite" through a profile, So the ability to disable a program is basically redundant at this point. When I actually remove "composite" from the shaderpack, I see a ~100 fps difference, I'm assuming because it's no longer drawing to two full RGB textures that are the size of the shadow map.

**Comment by sp614x** [comment]
Looking here: https://github.com/BruceKnowsHow/Ebin-Shaders/blob/7d64cdb3d8c3a66b3d154c6c0bfe80111f30ad98/shaders/shaders.properties
I see no disabled programs in the profiles. Maybe this is correct:
`profile.Low=low_profile !standard_profile !program.composite`

**Comment by BruceKnowsHow** [comment]
Oh shoot, looks like it was my mistake. Thanks.
