### ISSUE TITLE
Translucent overlays break in combination with water shaders

### ISSUE THREAD

**Issue by LTK1** [sp614x/optifine#2222]
When a semitransparent overlay is applied with layer=translucent, and a shader with water effects like Sildur's Vibrant Shaders is applied, overlays on underwater blocks aren't lit correctly, do not receive the 'wavy' effect and become invisible from certain angles.

Overlays from sand blocks visible:
![2019-02-27_21 22 42](https://user-images.githubusercontent.com/34627908/53521362-364eed80-3ad8-11e9-8076-57d4211adb0f.png)

Overlays from sand blocks invisible:
![2019-02-27_21 22 52](https://user-images.githubusercontent.com/34627908/53521410-4e267180-3ad8-11e9-831e-fd0ea48f2478.png)

Example overlay texture:
![12](https://user-images.githubusercontent.com/34627908/53521487-8af26880-3ad8-11e9-8857-8b24daa6083a.png)

Version: Minecraft 1.13.2, Optifine HD_U_E5

**Comment by sp614x** [comment]
This is a shader pack problem.
Most shader packs are not developed and tested for transparent overlays under water.
Translucency and transparency in shaders are very complex and a case like that would probably need special handling.
