### ISSUE TITLE
Different CEM based on name (suggestion)

### ISSUE THREAD

**Issue by Vyrgax** [sp614x/optifine#2223]
For example, when you name a Pig 'Wild Boar', it gets its CEM, without entirely replacing the mob itself. Adding this will allow a lot of possibilities, and will really make optifine perfect.

**Comment by realjackasterisk** [comment]
This can *sort of* already be done with a combination of Random Entities and CEM. https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/random_entities.properties#L106

**Comment by ewanhowell5195** [comment]
random entity models have now been implemented: <https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/cem_model.txt#L206>
