### ISSUE TITLE
[1.13.2] Significant FPS drop while using shaders.

### ISSUE THREAD

**Issue by blahber** [sp614x/optifine#2224]
The only mod I have installed is the latest version of Optifine, and while using shaders, my framerate will go from around 60-80 to 4ish, seemingly randomly. I've noticed this happens more when I near areas that have more "stuff" in them (i.e. jungles), but I can't be sure. Sometimes the shaders will run perfectly fine with great FPS for a long time, but then randomly it will freeze then lag out. I can easily temporarily fix the problem by refreshing the game (F3+T or clicking on the same/another shader pack to reload it), but eventually it happens again. This happens with all shaders.

I looked into the debug screen, and the number 1 thing in gameRender was something called "finish." I do not know what this is, but it appears to be the cause for the jump from 60-80 FPS to 4-6 FPS. All my drivers are up-to-date as well. I have included screenshots of the before and after the lag hits.
![2019-02-26_21 05 15](https://user-images.githubusercontent.com/32002145/53608256-99e42400-3b87-11e9-98c2-e4c66b550697.png)
![2019-02-26_21 06 14](https://user-images.githubusercontent.com/32002145/53608265-a10b3200-3b87-11e9-839d-376d5ee5ee62.png)

**Comment by sp614x** [comment]
Looks a lot like an overheating GPU or some other GPU related problem.
Updating the graphics driver may help.

**Comment by blahber** [comment]
How could that even be the case if doing something like F3+T fixes it?
