### ISSUE TITLE
incompatible with VanillaFix

### ISSUE THREAD

**Issue by 27638166** [sp614x/optifine#2227]
if i used it with VanillaFix fire animation won't work at all

**Comment by realjackasterisk** [comment]
More details needed. What version of OptiFine? What version of VanillaFix? What version of Forge? Any other mods? A log file might help too.

**Comment by 27638166** [comment]
VanillaFix-1.0.10-99 and OptiFine 1.12.2 HD U E3 and forge 14.23.5.2815

**Comment by 27638166** [comment]
Other mod....hmmm.. I have test for them and they aren't cause it

**Comment by sp614x** [comment]
To find the problematic mod:
- split the mods in two groups
- test one group of the mods
- keeping the group which crashes
- repeat until there is only one mod except OptiFine left
