### ISSUE TITLE
Vanilla Custom block models don't work with Optifine enabled 

### ISSUE THREAD

**Issue by Azagwen** [sp614x/optifine#2230]
I tried importing Custom models to a few blocks in my pack _(most of them were to redirect textures because I separated some of them into other files to sort that all)_ but when I connected into my game it simply and completely ignored all of my JSON models.

**Comment by sp614x** [comment]
OptiFine doesn't change handling of vanilla models.
Make sure you are running the correct Minecraft version and check the game output (error log) for errors.

**Comment by Azagwen** [comment]
My bad, doing that in the late evening I forgot to put a "block" folder and put the models in the "models" folder instead.
