### ISSUE TITLE
Optifine instantly crashes on 1.12.2

### ISSUE THREAD

**Issue by CacheTellsStories** [sp614x/optifine#2231]
Optifine is the only mod I have installed and nothing else. I am using Forge 2362. The game instantly crashes when I press the play button. Any fixes? I am using the latest version of JAVA

**Comment by CacheTellsStories** [comment]
---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 3/3/19 1:57 PM
Description: Exception ticking world

java.lang.NoSuchMethodError: net.minecraft.entity.EntityLiving$SpawnPlacementType.canSpawnAt(Lnet/minecraft/world/World;Lnet/minecraft/util/math/BlockPos;)Z
	at net.minecraft.world.WorldEntitySpawner.func_180267_a(WorldEntitySpawner.java:226)
	at net.minecraft.world.WorldEntitySpawner.func_77192_a(WorldEntitySpawner.java:135)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:203)
	at WorldServerOF.func_72835_b(WorldServerOF.java:37)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:239)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.world.WorldEntitySpawner.func_180267_a(WorldEntitySpawner.java:226)
	at net.minecraft.world.WorldEntitySpawner.func_77192_a(WorldEntitySpawner.java:135)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:203)
	at WorldServerOF.func_72835_b(WorldServerOF.java:37)

-- Affected level --
Details:
	Level name: New World-
	All players: 1 total; [EntityPlayerMP['ScabbersStories'/11, l='New World-', x=109.50, y=64.00, z=581.50]]
	Chunk stats: ServerChunkCache: 1135 Drop: 0
	Level seed: 3133518929786696195
	Level generator: ID 01 - flat, ver 0. Features enabled: true
	Level generator options: 3;minecraft:bedrock,3*minecraft:stone,52*minecraft:sandstone,8*minecraft:sand;2;village,biome_1,decoration,stronghold,mineshaft,dungeon
	Level spawn location: World: (104,4,583), Chunk: (at 8,0,7 in 6,36; contains blocks 96,0,576 to 111,255,591), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,0,512 to 511,255,1023)
	Level time: 20 game time, 20 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 115242 (now: false), thunder time: 124054 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:239)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 208121248 bytes (198 MB) / 671088640 bytes (640 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2796 Optifine OptiFine_1.12.2_HD_U_C5 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID        | Version      | Source                        | Signature                                |
	|:------ |:--------- |:------------ |:----------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft | 1.12.2       | minecraft.jar                 | None                                     |
	| LCHIJA | mcp       | 9.42         | minecraft.jar                 | None                                     |
	| LCHIJA | FML       | 8.0.99.99    | forge-1.12.2-14.23.5.2796.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge     | 14.23.5.2796 | forge-1.12.2-14.23.5.2796.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |

	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['ScabbersStories'/11, l='New World-', x=109.50, y=64.00, z=581.50]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_C5
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Seus
	OpenGlVersion: 4.6.0 NVIDIA 388.13
	OpenGlRenderer: GeForce GTX 1050 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by realjackasterisk** [comment]
According to that log, you're using Forge 2796, not 2362. You're also using the oldest version of OptiFine for 1.12.2, which is *horribly* outdated now.

**Comment by MauveCloud** [comment]
While we're at it, you're not really using the latest version of Java, either:

> Java Version: 1.8.0_51, Oracle Corporation

I believe that's the version that comes "bundled" with Minecraft, so even if you have a newer version of Java installed, you haven't configured Minecraft to use it.

**Comment by CacheTellsStories** [comment]
Sorry I posted the wrong log. I have used 2362 and the latest version of Optifne, same result. I am just putting the .jar, downloaded from the Optifine website and nothing changed. Do I have to mess around with an installer?

**Comment by MauveCloud** [comment]
No, the installer is for using Optifine w/o Forge, and doesn't give an easy way to use it alongside mods, but it might help if you post the correct log.  Please don't assume (or expect us to take your word for it) that the details of the crash are the same.

**Comment by CacheTellsStories** [comment]
Yeah sorry about that

**Comment by realjackasterisk** [comment]
...what do you mean "it doesn't give an easy way to use it alongside mods"? Installing OptiFine as a Forge mod should be the same as any other mod.

**Comment by CacheTellsStories** [comment]
I might just be an idiot and trying to put the installer in my mods folder. Where is the download for the normal mod?

**Comment by realjackasterisk** [comment]
Placing the installer in the mods folder is exactly what you're supposed to do. https://optifine.net/downloads

**Comment by CacheTellsStories** [comment]
Alright

**Comment by MauveCloud** [comment]
Sorry, I guess I wasn't clear, I meant _running_ the installer doesn't give an easy way to use it alongside mods.

**Comment by CacheTellsStories** [comment]
I have fixed the problem. My forge version was off by one. Thanks guys.
