### ISSUE TITLE
(1.13.2) Optifine hangs on Mojang logo - no other mods

### ISSUE THREAD

**Issue by Averrak** [sp614x/optifine#2235]
Upon launching the Optifine profile created by the respective installer, Minecraft freezes on the Mojang logo and does not proceed further. In the output log generated by the Minecraft launcher, no errors are reported aside from inability to reach a server to verify a file, using a local file instead.

Windows 7, if that's relevant, launching through the normal Minecraft launcher. Tried Optifine Ultra U E6/5/4, the problem happening across each version. Minecraft 1.13.2 without Optifine works as expected.

**Comment by SetantaLP** [comment]
Which java-version are you using?

**Comment by Averrak** [comment]
My Java is version 8, update 201, the most recent to my knowledge.

**Comment by Averrak** [comment]
Issue was resolved via a computer reboot - unclear what final issue was, but working as expected on the other side of said reboot.
