### ISSUE TITLE
OptiFine cape texture on Elytra disappears after going thru nether portal.

### ISSUE THREAD

**Issue by Ratchet97** [sp614x/optifine#2236]
Hello,

today I donated to OptiFine and got my cape. I customized it, saved and reloaded as usual. Logged on my server and my cape was showing. After equping leytra wings the texture showed on the wings, but suddenly dissapierd after going thru a nether portal and the elytra wings turned to default grey colour. I tried to reload the cape, it displa it again on the elytra but going thru a nether portal it again disappeared. Relogs did not help.

I called my friend on our server who also has a optifine cape to try the same thing. He told me that his texture on elytra disappeared doing the same thing. I also noticed that from my view.

The same thing also happend in a singleplayer game. I was running the newest optine version without any other mods and with mods. In both situations with the same outcome. Restarting game did not work.

Is this normal or is it a glitch? I am really frustrated about this.

![2019-03-07_01 40 08](https://user-images.githubusercontent.com/48301568/53923874-1a1ff300-407a-11e9-8d2c-5194dfe61472.png)
![2019-03-07_01 40 21](https://user-images.githubusercontent.com/48301568/53923875-1a1ff300-407a-11e9-878f-de28a7bd7888.png)

**Comment by realjackasterisk** [comment]
this has already been fixed in the latest preview version

**Comment by Ratchet97** [comment]
> this has already been fixed in the latest preview version

So can we expect this fix to be implemented in a final version of optifine then? In a next official version?

Thaks for the quick response!

**Comment by realjackasterisk** [comment]
well yes, that's generally what happens to preview versions.
