### ISSUE TITLE
overlay CTM not working with slabs/stairs

### ISSUE THREAD

**Issue by Chrisblox** [sp614x/optifine#2237]
Hello, I'm working on making overlay textures for my pack and I've run into some trouble.
I can't seem to get the overlays to work with slabs or stairs, It works fine for double slabs.
![image](https://user-images.githubusercontent.com/35179334/53974081-d240b080-40f9-11e9-8d0a-79eba464a02a.png)
The arrow is the double slab and the circled area is where it should connect but doesn't.
I have also tried making a separate property file for the slabs but that didn't work either.

Here is what's in the property file:

matchBlocks=cobblestone mossy_cobblestone stone diorite granite andesite
method=overlay
tiles=0-16
faces=north south east west
connectBlocks=stone_bricks stone_brick_slab stone_brick_stairs
layer=cutout

I also tried to specify all the extra info for the slabs/stairs eg: minecraft:stone_brick_stairs:facing=east,half:bottom ect...
However that did not work either, I can't tell if this is a bug or I'm missing something in the file.
Thanks for your time.

**Comment by sp614x** [comment]
Minimal resource pack to reproduce the problem?

**Comment by Chrisblox** [comment]
[Overlay slab issue.zip](https://github.com/sp614x/optifine/files/2977077/Overlay.slab.issue.zip)

**Comment by sp614x** [comment]
Currently the CTM overlays only work for full blocks.
