### ISSUE TITLE
[Request] (Custom Entity Models) Add Giant support

### ISSUE THREAD

**Issue by Gunging** [sp614x/optifine#2239]
Hello,

For some reason, **Giants** are not included in [this list](https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/cem_model.txt) with all the supported mobs for Custom Entity Models (This is presumably because they are not supported).

Honestly, if you are using custom entity models, you are very likely doing an adventure map or creating some very good quality experience in a mythicmobs server. So the fact that it is impossible to find giants under normal circumstances does not mean they should not be supported.

Thanks in advance.

**Comment by realjackasterisk** [comment]
#2069

**Comment by LoneDev6** [comment]
This can be closed I think: https://github.com/sp614x/optifine/issues/2069#issuecomment-545040203
