### ISSUE TITLE
New worlds do not save after generating with 1.13.2 HD U E6.

### ISSUE THREAD

**Issue by e2cool** [sp614x/optifine#2244]
Any worlds generated with 1.13.2 HD U E6 have immediate issues such as no mob AI, no flowing water, and no tile drops. Any blocks you break and any changes you make are reverted to the seed's default state upon reloading the world.

**Comment by sp614x** [comment]
Errors in the error log (game output)?

**Comment by KaiAF** [comment]
Closing this as they haven't responded. If you are still having issues, let us know.
