### ISSUE TITLE
Optifine crashing on 1.12.2

### ISSUE THREAD

**Issue by ireece1** [sp614x/optifine#2245]
Version E3 works fine, but E4 and up causes the game to crash before the window displays the loading screen,

https://pastebin.com/yN0XzDja

**Comment by realjackasterisk** [comment]
1. preview E4 is compatible with forge 2795, you're using 2768. try updating forge and test again
2. it looks like you're using other mods, try removing them one half at a time. if the problem persists after all mods have been removed, its a problem with optifine. if the problem disappears after removing some mods, theres an incompatibility.

**Comment by Midnight-Vortex** [comment]
E4 is 1.13 for 1.12.2 is only E3

**Comment by Quavelen** [comment]
> E4 is 1.13 for 1.12.2 is only E3

Hmm. Are you certain?

![image](https://user-images.githubusercontent.com/19168008/54082327-aeed4f80-430b-11e9-9f6c-6e9e53b527b4.png)

I'm fairly sure what Jack said is accurate.

**Comment by sp614x** [comment]
Incompatibility with one of the installed core mods.
To find the problematic mod:
- splitting the mods in two
- test one half of the mods
- keeping the half which crashes
- repeat until there is only one mod except OptiFine left
