### ISSUE TITLE
Optifine 1.12.2 HD U E3 - Render Regions incompatible with Schematica

### ISSUE THREAD

**Issue by adrevki** [sp614x/optifine#2246]
**Problem:**
- Visual glitches in loaded schematics

**Mods:**
- Schematica 1.8.0.169
- Lunatrius Core 1.2.0.42
- Optifine 1.12.2 HD U E3

**How to Replicate:**
1. Enable "Render Regions" in Optifine
2. Load in any schematic through Schematica

**Comment by sp614x** [comment]
Render Regions uses a different rendering mode which is probably not compatible with the Schematica rendering.
