### ISSUE TITLE
Cant change my optifine cape

### ISSUE THREAD

**Issue by MythicalPandaaa** [sp614x/optifine#2247]
I want to change my OF cape but when i go to change cape it says:
Change cape
To change the design of your OptiFine cape, deactivate it or move it to another username:
Download and install OptiFine E6 for 1.13.2 or newer
Start Minecraft with OptiFine
Go to Settings -> Skin Customization -> OptiFine Cape -> Open Cape Editor
You will be automatically redirected to the cape editor page.

The Minecraft login was removed as it may cause your account to be blocked.

I tried the steps but didnt work and last thing they say ''The Minecraft login was removed as it may cause your ccount to be blocked''

HOW CAN I UNBLOCK IT, I WANT TO CHANGE MY CAPE. HELP ME PLEASE!!

**Comment by realjackasterisk** [comment]
what do you mean "it didnt work"?

**Comment by MythicalPandaaa** [comment]
Nvm it alreadu worked

Op zo 10 mrt. 2019 20:49 schreef Kyle Edwards <notifications@github.com>:
