### ISSUE TITLE
99% GPU Usage on Nvidia Titan RTX (Optifine 1.7.10)

### ISSUE THREAD

**Issue by colbias** [sp614x/optifine#2249]
I've been having issues with GPU usage on Optifine (Minecraft 1.7.10) with my Nvidia Titan RTX. Whenever I have optifine in my mods folder, my GPU usage soars to around 80-90%, and when I open my chat, it almost always goes to 99%. I don't actually experience FPS drops in game, but I do YouTube, so when my GPU usage is at 99%, my OBS starts to lag and I cannot record. I've been having to play Minecraft w/out Optifine, and then I have the stable 30-40% GPU usage. Does anyone have any ideas?

I've tried Optifine 1.7.10 HD_U_D6/D8/E7, and nothing works. There are sometimes where the issue seems to disappear, but then it comes back, so I've had to resort to playing without Optifine so that I can record.

**Comment by zWyrn** [comment]
Disable Multi-Resampling on NVIDIA Interface, had the problem too, fixed it with the Option

**Comment by sp614x** [comment]
This should be something GPU or driver specific.
Disabling Smooth FPS may help.

**Comment by entity493** [comment]
@zWyrn How do you get there step by step i may be having this issue
