### ISSUE TITLE
Lightning bolts, glint on items and glowing effects on players aren't rendered correctly

### ISSUE THREAD

**Issue by DeDelner** [sp614x/optifine#225]
For example, when you type `/effect @p glowing`, the glowing effect isn't rendered correctly.
Lightning bolts aren't rendered correctly and will only shown under certain conditions.
And the glint texture on items and held items aren't shown.

I simply tried to make the lightning bolts pitch black (just for testing) and it looks like it only worked in gbuffers_textured_lit.

![2016-07-12_23 29 25](https://cloud.githubusercontent.com/assets/20246347/16784425/1658f65e-4889-11e6-9935-102a1aa2cb2b.png)
![2016-07-12_23 29 59](https://cloud.githubusercontent.com/assets/20246347/16784435/1f997d24-4889-11e6-89ff-1f0387f67d44.png)

**Comment by sp614x** [comment]
The glowing effect is not compatible with shaders and Fast Render. 
A simplified version is used when shaders are active and it looks a bit ugly, but the player should be visible behind blocks,

**Comment by DeDelner** [comment]
Oh alrighty .w.
