### ISSUE TITLE
[Tutorial] (Custom Entity Models) Animation "Entity (float) parameters"

### ISSUE THREAD

**Issue by Gunging** [sp614x/optifine#2250]
So, [cem_animation.txt](https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/cem_animation.txt) contains the a list of "Entity Parameters." But to be honest it doesn't document them throughly. Thus there are not-so-obvious ones that need some explaining. The list is the following:

- health
- hurt_time
- idle_time
- max_health
- move_forward
- move_strafing
- pos_x, pos_y, pos_z
- revenge_time
- swing_progress

**health**:
Linked to the health attribute of the entity {Health:#}
(The current amount of health, in half hearts, the mob has)

**hurt_time**:
Linked to the HurtTime attribute of the entity {HurtTime :#}
(How long the entity will remain tinted red after being hit) 
[Note it will be forced to be zero if the entity is not red-tinted]

**idle_time**:
Seems to be always increasing by 1 every tick regardless of any condition.
(Tested conditions: Mob taking damage, chasing target, death animation, attacking target, idly standing, randomly strolling)
_Could someone explain this one please?_

**max_health**:
Linked to the max health attribute of the entity. {Attributes:[{Name:generic.maxHealth,Base:#}]}
(The max health, in half hearts, the mob can have)

**move_forward**:
Always zero?
(Tested conditions: Chasing target, idly standing, randomly strolling)
_Could someone explain this one please?_

**move_strafing**:
Always zero?
(Tested conditions: Chasing target, idly standing, randomly strolling)
_Could someone explain this one please?_

**pos_x, pos_y, pos_z**
Linked to the position of the entity. {Pos:[#.#d,#.#d,#.#d]}
(The world co-ordinates of the entity)

**revenge_time**:
Always zero?
(Tested conditions: Chasing target, idly standing, randomly strolling, attacking target, taking damage, death animation)
_Could someone explain this one please?_

**swing_time**:
Increases while the mob is attacking its target.

Could someone help me complete this information? Thanks in advance.

**Comment by sp614x** [comment]
These are taken directly from the MC code.
Explanations are welcome and they could be added to the docs.

**Comment by ewanhowell5195** [comment]
docs have now been updated
