### ISSUE TITLE
Mipmaps don't work for any composite (and likely deferred) after 7.

### ISSUE THREAD

**Issue by jcm2606** [sp614x/optifine#2251]
I think this is the same problem as #2140, except that issue assumed the wrong source of the problem. I just ran into the same issue as #2140, where mipmaps wouldn't work in composite14, except instead of renaming to composite, I renamed to composite6, and it suddenly worked. I only have composite, no composite1 or above, so it can't be what #2140 outlines.

**Comment by zombye** [comment]
Disabling buffer clearing also doesn't seem to work in composite after composite9 (and likely also deferred after deferred9). Probably the same issue if you haven't tested composite8 & composite9.

**Comment by sp614x** [comment]
Fixed, coming in next preview.
