### ISSUE TITLE
screen issues

### ISSUE THREAD

**Issue by Bugsabby** [sp614x/optifine#2252]
![Screenshot (41)](https://user-images.githubusercontent.com/48555763/54393822-265b1000-4679-11e9-90ff-035ee2b77701.png)
I recently installed optifine and a shader pack called sildur's shader pack < vibrant pack medium and it works great its just every 10 to 15 minutes my screen goes weird and the only way to stop doing it, is that I have to restart minecraft 
![Screenshot (37)](https://user-images.githubusercontent.com/48555763/54359660-20414100-4631-11e9-9862-5af6255e625d.png)
is this a current issue? (its not the resource pack btw)

**Comment by realjackasterisk** [comment]
F3 screenshot?

**Comment by Bugsabby** [comment]
window's key + prt sc

**Comment by realjackasterisk** [comment]
press F3 while in-game and then take a screenshot, please.

**Comment by Bugsabby** [comment]
I did, it wont let me either other way

**Comment by Quavelen** [comment]
I think you're misunderstanding Jack's request, @Bugsabby. He wants you to turn on the debug menu (which is opened by pressing F3 ingame) and then take a screenshot whilst that is opened.

**Comment by Bugsabby** [comment]
there

**Comment by Quavelen** [comment]
>AMD Ryzen 3 2200G

There's the issue. You're using the Vega 8 integrated graphics chip on that cpu, which currently has a problem: https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1291396-1-6-4-1-13-2-sildurs-shaders-pc-mac-intel-vibrant?comment=5498

Others are experiencing this as well, and it appears that Sildur took the conversation to private messages. So more than that, I can't say.

**Comment by Bugsabby** [comment]
is it just sildurs? or is this happening to other shaders as well?

**Comment by Quavelen** [comment]
According to that post I linked you to, I would assume it's not just Sildur's. Driver issues tend to be a thing that affects most things related to the issue, but it wouldn't hurt to try something else. Just please bear in mind what I said in my edit, above.

**Comment by Quavelen** [comment]
Small update @Bugsabby - yes, the AMD driver issue affects almost all shaders. I just checked in the Shaderlabs discord.

**Comment by sp614x** [comment]
Looks like this is an AMD driver issue, not related to OptiFine.
