### ISSUE TITLE
Display_Update 85%

### ISSUE THREAD

**Issue by BobCrawls** [sp614x/optifine#2255]
I don't really understand why but I always see blue (display_update) 85% no matter what and I can't run any shader or resource pack at any playable fps
Does it on 1.12.2 and 1.13.2
Screenshot (Shader: BSL | Resource Pack: Realistco Full) https://cdn.discordapp.com/attachments/423430686880301060/556748273906352128/unknown.png https://cdn.discordapp.com/attachments/423430686880301060/556748424926593024/unknown.png

**Comment by sp614x** [comment]
The `display.update` is waiting for the GPU to finish current frame.
You need a GPU powerful enough to run shaders.
