### ISSUE TITLE
Installer GUI won't run

### ISSUE THREAD

**Issue by LeBotDevNoob** [sp614x/optifine#2258]
I'm trying to run the OptiFine installer, but it won't work.
Before you start replying that I should right click and then open with Java; acknowledge that I have already tried it.

**Comment by sp614x** [comment]
You can try with JarFix: https://download.cnet.com/Jarfix/3000-18512_4-77571216.html
It can restore the JAR file association so that JAR files start with Java.
Relevant #943, #906, #763.
