### ISSUE TITLE
Crashes upon trying to rename item. (1.13.2 HD U E6)

### ISSUE THREAD

**Issue by MinecraftMinun** [sp614x/optifine#2260]
I am using a resource pack that changes textures upon renaming, but I've had it before with no problems. Suddenly, when I try to type to rename an item, it crashes.
It was working perfectly fine yesterday and I don't think I have changed anything to do with my resource pack since yesterday, so I have no idea what the issue is.

[crash-2019-03-20_08.19.06-client.txt](https://github.com/sp614x/optifine/files/2985786/crash-2019-03-20_08.19.06-client.txt)

**Comment by Regnander** [comment]
Can you upload your resource pack? I want to try it out to see what's wrong.

**Comment by MinecraftMinun** [comment]
I reverted it back to an old version without the bug and copied all the image files from the current then redid the properties file and that solved things. I assume it was the properties file that had a problem and I just didn't pick up on the error?
Here's the old version of the resource pack
[https://cdn.discordapp.com/attachments/367422083874947085/557853494007300106/MinunCraft_0.3.7_-_1.13.zip](url)
