### ISSUE TITLE
Fullscreen suggestion

### ISSUE THREAD

**Issue by Kwegg** [sp614x/optifine#2269]
If possible, fix screen tear while in fullscreen. Currently I dont have a gsync monitor however I have a free sync monitor so I experience screen tear when in fullscreen. 

I noticed that on 1.13 fullscreen is now 24bit, not sure what that means but im guessing whatever it is fixed screen tear because I hopped on that version the other day to check it out with Optifine and I went in fullscreen and noticed I wasnt getting any screen tear and I think it is down to that. 

My question is, would you be able to implement that into 1.8.9 optifine? It would be super useful. Sure vsync would fix screen tear but I have my frame rate set to max because I prefer higher fps. I havent tested default 1.13 out so I wouldnt know if mojang thenselves implemented the fix but yeah it would be greatly appreciated if you could look into this. It means I can play fullscreen with no tear, im sure theres other people out there who are on the same boat as me and dont play fullscreen because of screen tear. 

Many thanks, Kwegg.

**Comment by Kwegg** [comment]
Scrap that, it's a new feature for 1.13. This is what I was talking about though http://prntscr.com/n2t9bj if you could possibly implement that into versions below 1.13 that don't support this, that would be great! If it's not possible then don't worry about it, still worth the ask though haha,

Thanks, Kwegg.

**Comment by sp614x** [comment]
1.13 is using LWJGL 3, while 1.12 and lower are using LWJGL 2.
This is the graphics library which is responsible for the screen modes.
