### ISSUE TITLE
How do I use Entity parameters (float) in my custom entity model's animation?

### ISSUE THREAD

**Issue by XKane55** [sp614x/optifine#2273]
Like, I'd like to make an animation when the entity is attacking. Like : if the entity is chasing, or attacking, it makes an animation. Example of what I'm doing wrong: 
	  "animations":
	  [
		{
		  "this.rx": "if(revenge_time, 1.2, 0)",
How can I do it right sot it works? I don't know anything about scripting. It's probably so simple, but I can't figure it out.

**Comment by sp614x** [comment]
the format for "if" is "if(boolean, value, value)", you are using it as "if(value, value, value)".
To fix it for example "if(revenge_time > 1.0, 1.2, 0)"

**Comment by XKane55** [comment]
Thanks for the reply. It doesn't seem to make an animation when the entity is attacking/chasing tho. Is there anything I could do for it to work?

**Comment by sp614x** [comment]
Looks like this is the time when the entity was hurt. 
Not useful for CEM animation.

**Comment by XKane55** [comment]
Oh okay I understand now, thank you for your time!
