### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by NotV4pe** [sp614x/optifine#2274]
Hey I am trying to get optifine cape right now but I have no idea where to create my donation email. Can someone help me please??

**Comment by realjackasterisk** [comment]
what do you mean "create my donation email"??

**Comment by xParadoxical69** [comment]
You only have to use your minecraft account nickname. Donate at https://optifine.net/donate

**Comment by sp614x** [comment]
You can use any email, for example the minecraft account email.
