### ISSUE TITLE
can you add to the blocks and nbt texture system ofr tile entitys

### ISSUE THREAD

**Issue by danjhop** [sp614x/optifine#2277]
can you add a setting for textures linked to nbt so that tile entitys can be give texture based on a nbt tag

**Comment by sp614x** [comment]
Currently this only works for names:
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/random_entities.properties#L84

**Comment by sp614x** [comment]
Internally the tile entities don't have NBT properties. The NBT tags are only generated when saving the world.
Using the NBT save functionality to check the properties of the tile entity would be very slow as this is repeated for every frame when the tile entitity is rendered.
