### ISSUE TITLE
Crash on startup with D6 for 1.7.10

### ISSUE THREAD

**Issue by lightning02** [sp614x/optifine#228]
http://pastebin.com/EnsEJGeN
Switching from D4 to D6 version the Modpack does not start and give this error in the logs.

**Comment by sp614x** [comment]
Problem with Factorization:

[B#347]  Caused by: java.lang.RuntimeException: Method mutation failed: did not find cpw/mods/fml/common/eventhandler/EventBus.post / (Lcpw/mods/fml/common/eventhandler/Event;)Z
[B#347]     at **factorization.coremod.AbstractAsmMethodTransform**$MutateCall.apply(AbstractAsmMethodTransform.java:141) ~[Factorization-1.7.10-0.8.107.jar:?]
[B#347]     at **factorization.coremod.ASMTransformer**.applyTransform(ASMTransformer.java:155) ~[Factorization-1.7.10-0.8.107.jar:?]

**Comment by Darkos333** [comment]
Im not sure why you closed the issue, so just letting you know sp614x:
I have exact same crash, and removing Optifne from pack prevents its occurence.
So its definitely an incompability between Factorization and Optifine.

**Comment by sp614x** [comment]
The crash is inside a Factorization class (factorization.coremod.AbstractAsmMethodTransform$MutateCall). It probably crashes when trying to modify a base class which is already modified by OptiFine.

**Comment by Ushupiuck** [comment]
anything that could be done on Optifine's side?

**Comment by sp614x** [comment]
OptiFine can not help much, Factorization is making the changes.
No idea what are the changes and how they are applied.

**Comment by Ushupiuck** [comment]
hm. an Idea I've got is that if optifine detects the mod, it then "waits" and patches the file _after_ Factorization does it's own patch... I am unsure, but maybe this workaround could work..?

**Comment by sp614x** [comment]
OptiFine does not patch at runtime, so the workaround is not possible.

**Comment by Ushupiuck** [comment]
Ignore that part; take in account just the linked code. I derped, and forgot to remove it...

**Comment by AforAnonymous** [comment]
Considering the fact that OptiFine D4 works, this crash should be avoidable on the OptiFine side. Could you maybe reopen this issue or simply fix it, @sp614x? :(

**Comment by AforAnonymous** [comment]
Also, on a related note, there existed a related crash caused by FastCraft, Player released a fix for that back in March: https://forum.industrial-craft.net/thread/10820-wip-1-7-10-fastcraft-1-23-note-all-posts-of-new-members-need-to-be-approved-firs/?postID=207199#post207199

**Comment by Gamerbolts** [comment]
Not sure if you all are still having this problem but I did something that worked for me. I went into the HammerChannels config file and set it to false. Hope this helps you.
