### ISSUE TITLE
1.13.2 E7 jar doesn't contain mods.toml file

### ISSUE THREAD

**Issue by xParadoxical69** [sp614x/optifine#2280]
I downloaded OptiFine_1.13.2_HD_U_E7.jar, but after placing it in mods folder forge is not loading it, because it doesn't contain mods.toml file, which is now required in mod jars.

`[17:25:01] [main/WARN]: Mod file Mod File: C:\Users\USER\AppData\Roaming\.minecraft\mods\OptiFine_1.13.2_HD_U_E7.jar is missing mods.toml file
[17:25:01] [main/WARN]: File C:\Users\USER\AppData\Roaming\.minecraft\mods\OptiFine_1.13.2_HD_U_E7.jar has been ignored - it is invalid`

**Comment by DataCrusade** [comment]
Optifine 1.13 does not support Forge yet, so this is expected. It's being worked on.

**Comment by realjackasterisk** [comment]
#2148, #2207, #2271
