### ISSUE TITLE
What mean the "white" color in the lagometer ?

### ISSUE THREAD

**Issue by ExDomino** [sp614x/optifine#2281]
Hello,

When using your lagometer to see what is lagging, the white color is not documented.
I'm trying to figure out what is lagging here:

https://image.noelshack.com/fichiers/2019/14/1/1554085491-2019-03-31-22-24-24.png

A simple vanilla building without any machine, no mobs inside, no redstone, etc, where my main base with a lot more machines is not lagging at all. As you can see, white is not listed in the tooltip.

Minecraft version : 1.12.2
Forge version : 2815
Optifine version : HD U E3

I'm not reporting a lag issue with your mod but only the fact that the white color is not documented. Can you tell me here what this color means please?

Thank you in advance.

**Comment by Quavelen** [comment]
If you open the lagometre, the white is clearly labelled: 

![image](https://user-images.githubusercontent.com/19168008/55301213-52291480-5433-11e9-82e5-b1daadd5fb6f.png)

**Comment by sp614x** [comment]
White color in the lagometer is everything else that can't be measured.
For example: display update, mouse and keyboard handling, sound and so on...
The profiler (round pie thing) can be used to track where this time is spent.

**Comment by TixuMC** [comment]
i want to tell that if most is white its not lagging ur game out, wait how did i not realize this was from 2019
