### ISSUE TITLE
Normal map (fallback?) broken for entities

### ISSUE THREAD

**Issue by zombye** [sp614x/optifine#2286]
Example using a resource pack with no normal maps, showing values from the `normals` sampler:
![2019-04-04_13 35 10](https://user-images.githubusercontent.com/9051920/55552874-f387c300-56de-11e9-802e-b4c9f2cc508a.png)

Not sure if this affects entities with a normal map provided by the resource pack.
I haven't tested in 1.12, but I'm pretty sure it only affects 1.13 as this was an issue in 1.12 that was eventually fixed (#824, #1140).

**Comment by zombye** [comment]
Also affects banners, chests, shulker boxes, mob heads, conduits, and particles:
![2019-04-04_14 30 10](https://user-images.githubusercontent.com/9051920/55555762-4add6180-56e6-11e9-82ea-eef9bb499aac.png)

**Comment by sp614x** [comment]
Fixed normals/specular for all entities.
Coming in next 1.13.2 preview.
