### ISSUE TITLE
Surfaces rendered in `translucent` layer do not update correctly to moving around when shadow maps are enabled

### ISSUE THREAD

**Issue by zombye** [sp614x/optifine#2287]
This causes surfaces to become invisible when viewed through other surfaces in that layer from different directions to when the chunk loaded/started rendering (or something like that). F3+A, F3+R, and F3+T all seem to cause it to update to where the player currently is.

This does on occasion happen even when shadow maps are not enabled, but it's very rare and usually only limited to a few blocks, while with shadow maps this seems to always happen when there are more than two layers and affect the entire world.

Viewed from one side, without shadow maps:
![2019-04-04_14 55 04](https://user-images.githubusercontent.com/9051920/55557240-b96fee80-56e9-11e9-8573-57e88071be53.png)
Viewed from the other side, without shadow maps:
![2019-04-04_14 55 12](https://user-images.githubusercontent.com/9051920/55557250-c1c82980-56e9-11e9-98df-f99f0c02f3b0.png)
As expected, every layer is visible from both sides.

Viewed from one side, with shadow maps:
![2019-04-04_14 53 36](https://user-images.githubusercontent.com/9051920/55557168-89285000-56e9-11e9-857a-a0967e8e76bc.png)
Now, when viewed from the other side, with shadow maps:
![2019-04-04_14 53 41](https://user-images.githubusercontent.com/9051920/55557186-95aca880-56e9-11e9-8f67-041b011d6074.png)
Here, the lime stained glass in the middle ended up not rendering through the purple stained glass that was behind it in the first image, but is now in front of it in the second image.

**Comment by sp614x** [comment]
Does this happen with other shader packs?

**Comment by sp614x** [comment]
Fixed, coming in next preview.
