### ISSUE TITLE
Connected textures for glass pane, odd render issue.

### ISSUE THREAD

**Issue by Zorock666** [sp614x/optifine#2288]
Hi there.
So, I've made my own texturepack, which have been going for a long time. I've also made connected textures, which worked fine in the past, but there's an issue now that I can't seem to solve, and I'm hoping you can help.
I'm in MC 1.13.2, vanilla, using OptiFine 1.13.2 HD U E7.
Does anyone know if this issue lies with Optifine or my resourcepack?  I don't think there's anything in my files that would be causing the issue.

![2019-04-04_18 57 45](https://user-images.githubusercontent.com/38118045/55574149-fcdb5480-570b-11e9-8b9c-f035502ccd72.png)

The .properties file for white-stained glass and glasspane looks like this:
![light grey glass pane](https://user-images.githubusercontent.com/38118045/55574377-8be86c80-570c-11e9-9ae3-7ce431180bfe.jpg)

Is the .properties file the issue?  Would I need to make separate texture files for glass and glass-panes, and then separate .properies files as well?

**Comment by Regnander** [comment]
Can you upload the texture pack so I can try it out?

**Comment by Zorock666** [comment]
[Pure Edge 32x - 1.13.2.zip](https://github.com/sp614x/optifine/files/3049221/Pure.Edge.32x.-.1.13.2.zip)
Here it is =)

**Comment by Zorock666** [comment]
are bumps allowed?

**Comment by JimStoneCraft** [comment]
Not sure what the issue is (ctm_compact bug maybe) but you can fix it by spitting to two properties files (glass block and glass pane)

ctm_glass_white.properties

matchBlocks=white_stained_glass
method=ctm_compact
tiles=0-4

ctm_glass_white_pane.properties

matchBlocks=white_stained_glass_pane
method=ctm_compact
tiles=0-4
faces=sides

**Comment by Zorock666** [comment]
ah, thank you very much =)
