### ISSUE TITLE
Storing textures in vram rather than system memory.

### ISSUE THREAD

**Issue by dotModded** [sp614x/optifine#229]
I've noticed whenever loading larger resolution texturepacks you can get a massive ram usage increase and maybe even giving a out of memory error. It would probably be a major optimization if this is true. I'm not sure how this works in mc however if you have an idea on how this would be a really nice feature to have.

**Comment by sp614x** [comment]
Computer RAM can not be replaced with graphics VRAM. 
They are used in a different way.

**Comment by dotModded** [comment]
I'm aware, however texture should be stored in a ubo or some other method that puts it on the vram, this is the use of vram.

**Comment by dotModded** [comment]
Okay after a little bit of googling in opengl 2.1, minecrafts version it runs ogl, introduced PBO's (Pixel Buffer Objects) for storing textures on the gpu. This could be used to store texures on the gpu rather than sending them half way across the system every frame and this would lower memory usage and bring up framerate.
