### ISSUE TITLE
Minecraft 1.13.2 Freezing with Continuum shaders and Realistico Texture pack

### ISSUE THREAD

**Issue by Jackaroo05** [sp614x/optifine#2290]
Hello... I have a very bad problem with Continuum shaders and Realistico texture pack. No matter what I do, it freezes about 15 seconds into playing the game- not the main menu. I have looked at the logs and nothing is showing up. If anyone is able to help, let me know. Thanks!

**Comment by sp614x** [comment]
Can you post an F3 screenshot?
The realistico texture pack is very big, the GPU may be getting out of memory.

**Comment by wilkesreid** [comment]
Same issue here

**Comment by sp614x** [comment]
AMD graphics?
Please post an F3 screenshot, it has a lot of useful information that is needed to find the problem.

**Comment by Jackaroo05** [comment]
I am using AMD Graphics (RX 480 4gb), but It's pretty much impossible for me to get an F3 Screenshot before it freezes, and if I get lucky, I barely get enough time to get it.

**Comment by Jackaroo05** [comment]
Here's the log. https://paste.ubuntu.com/p/45jzTSZH6V/   (I'm using Win 10, not Ubuntu. I had to use Ubuntu's Pastebin because of discord server problems)

**Comment by wilkesreid** [comment]
I'm running an RX 580 8GB, and I've allocated over 10GB of RAM to Minecraft. The realistico pack works with other shaders, and the Continuum shader works with normal textures. They cause Minecraft to freeze when put together. I'll try to get an F3 screenshot.

**Comment by sp614x** [comment]
Continuum and some other shaders have problems with the latest AMD drivers (crashes, freezes).

**Comment by wilkesreid** [comment]
Then I guess that's the problem. Thanks.
