### ISSUE TITLE
"OpenGL Error 1280 (Invalid Enum)"

### ISSUE THREAD

**Issue by nasfinasfinasfi1** [sp614x/optifine#2291]
When booting up Minecraft on 1.13.2 on version OptiFine-1.13.2_HD_U_E6.jar that error occurs. It happens every 11 seconds from the moment the game is at "Reloading Custom Textures". This shows up in chat
![image](https://user-images.githubusercontent.com/31577169/55655549-27590a80-57fd-11e9-8c30-10641f0fdac9.png)

The error in the game output is this:

OpenGL API ERROR: 1280 (Error has been generated. GL error GL_INVALID_ENUM in (null): (ID: 173538523) Generic error) java.lang.Exception: Stack trace at org.lwjgl.opengl.GLDebugMessageCallbackI.callback(GLDebugMessageCallbackI.java:39) at org.lwjgl.system.JNI.invokePV(Native Method) at org.lwjgl.glfw.GLFW.glfwSwapBuffers(GLFW.java:4518) at cgd.a(MainWindow.java:457) at cft.c(SourceFile:875) at cft.a(SourceFile:395) at net.minecraft.client.main.Main.main(SourceFile:144) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:497) at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Resource packs:
96f743018ca1a68d161f312f9b387386-Texture Update V3.3 Java.zip, Lower Shield.zip

F3 Screenshot:
![image](https://user-images.githubusercontent.com/31577169/55656109-a0a52d00-57fe-11e9-9245-cc538b5f7de9.png)

I don't know if this is helpful, but the OpenGL version is:
4.3.0 - Build 20.19.15.4642

EDIT:
The error still occurs on version 1.13.2-OptiFine_HD_U_E7, though every 3 seconds instead of 11

**Comment by sp614x** [comment]
The error is reported at GPU swap buffers, which doesn't do anything special.
`org.lwjgl.glfw.GLFW.glfwSwapBuffers(GLFW.java:4518)`

Updating the graphics driver or enable/disable VBOs may help.

**Comment by sp614x** [comment]
Does this happen with the default resource pack?
