### ISSUE TITLE
Previous frame usage and allow in shadow/water/gbuffers shaders?

### ISSUE THREAD

**Issue by helixd-2k18** [sp614x/optifine#2292]
I want to add planar reflections into Minecraft, using shadow shader hacks. But for clipping and reflection correction, need previous frame projections and compute results (in water, gbuffers and shadow shaders). I propose to allow using colortex{0-7} from previous frame in all shaders. Also suggest to add clear custom color support. I can rise make "Water Shader" into Minecraft.

**Comment by sp614x** [comment]
Previous frame projections are avilable as `previousCameraPosition`, `gbufferPreviousModelView` and `gbufferPreviousProjection`.
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.txt#L153

Previous frame buffers can be accessed via skip clear:
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.txt#L424

**Comment by zombye** [comment]
@sp614x Previous frame buffers do not seem to be accessible in gbuffers before deferred.
I think this is actually what they were asking for, since they mentioned needing it in gbuffers.

**Comment by sp614x** [comment]
The buffers gaux1 to gaux4 can be used in gbuffers programs and with skip clear they would have the information from the previous frame(s).

**Comment by zombye** [comment]
Huh, it didn't seem to work when I tried before, but I tried again and it seems to be working now.
I guess I must have had a typo somewhere or something, then.
