### ISSUE TITLE
Forge Modded Server: Optifine Freezing/Crashing

### ISSUE THREAD

**Issue by AwesomeAnimationGamer** [sp614x/optifine#2294]
I am running a modded server for my friends and I, and about every half hour or so, the game will start freezing to the point we have to force close it and reboot the modpack. In the output log, Optifine throws this error:
`23:56:42
STDERR
main
info
[net.optifine.reflect.Reflector:handleException:1424]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
23:56:42
STDERR
main
info
[net.optifine.reflect.Reflector:handleException:1424]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
23:56:42
STDERR
main
info
[net.optifine.reflect.Reflector:handleException:1424]: at java.lang.reflect.Method.invoke(Method.java:497)
23:56:42
STDERR
main
info
[net.optifine.reflect.Reflector:handleException:1424]: at net.optifine.reflect.Reflector.callVoid(Reflector.java:750)
23:56:42
STDERR
main
info
[net.optifine.reflect.Reflector:handleException:1424]: at net.minecraft.client.Minecraft.func_147116_af(Minecraft.java:1787)
23:56:42
STDERR
main
info
[net.optifine.reflect.Reflector:handleException:1424]: at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2533)
23:56:42
STDERR
main
info
[net.optifine.reflect.Reflector:handleException:1424]: at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2304)
23:56:42
STDERR
main
info
[net.optifine.reflect.Reflector:handleException:1424]: at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2082)
23:56:42
STDERR
main
info
[net.optifine.reflect.Reflector:handleException:1424]: at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1318)
23:56:42
STDERR
main
info
[net.optifine.reflect.Reflector:handleException:1424]: at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:495)
23:56:42
STDERR
main
info
[net.optifine.reflect.Reflector:handleException:1424]: at net.minecraft.client.main.Main.main(SourceFile:123)
23:56:42
STDERR
main
info
[net.optifine.reflect.Reflector:handleException:1424]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
23:56:42
STDERR
main
info
[net.optifine.reflect.Reflector:handleException:1424]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
23:56:42
STDERR
main
info
[net.optifine.reflect.Reflector:handleException:1424]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
23:56:42
STDERR
main
info
[net.optifine.reflect.Reflector:handleException:1424]: at java.lang.reflect.Method.invoke(Method.java:497)
23:56:42
STDERR
main
info
[net.optifine.reflect.Reflector:handleException:1424]: at com.mtbs3d.minecrift.main.VivecraftMain.main(VivecraftMain.java:118)
23:56:42
STDERR
main
info
[net.optifine.reflect.Reflector:handleException:1424]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
23:56:42
STDERR
main
info
[net.optifine.reflect.Reflector:handleException:1424]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
23:56:42
STDERR
main
info
[net.optifine.reflect.Reflector:handleException:1424]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
23:56:42
STDERR
main
info
[net.optifine.reflect.Reflector:handleException:1424]: at java.lang.reflect.Method.invoke(Method.java:497)
23:56:42
STDERR
main
info
[net.optifine.reflect.Reflector:handleException:1424]: at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
23:56:42
STDERR
main
info
[net.optifine.reflect.Reflector:handleException:1424]: at net.minecraft.launchwrapper.Launch.main(Launch.java:28)`
I'm at a loss for what to do. I've searched Google and have found no answer regarding this. Any help is greatly appreciated.

**Comment by AwesomeAnimationGamer** [comment]
For whatever reason the output log isn't copying properly (I think) so here's a screenshot of what the log shows:
![Optifine Crash](https://user-images.githubusercontent.com/13543820/55698594-9fa60400-5994-11e9-8f9f-04c9538314b7.jpg)

**Comment by AwesomeAnimationGamer** [comment]
It's worth noting that I have removed EnderIO, and yet the issue persists

**Comment by realjackasterisk** [comment]
please don't tell me you're trying to run OptiFine on the server itself

**Comment by AwesomeAnimationGamer** [comment]
No I'm not, this is a client output log.

**Comment by AwesomeAnimationGamer** [comment]
After further testing, I no longer believe the issue is with Optifine.
