### ISSUE TITLE
Custom Render Layer for Block Disabling Specular Mapping

### ISSUE THREAD

**Issue by DiaTheAngel** [sp614x/optifine#2297]
So I created a custom model for a Dark Oak Door, that I did up in a modern style, with the frosted glass between the wood.
So I added the custom render layer for the door, to let me do this, then went and added Normal and Specular maps to my door before realising they weren't working
https://cdn.discordapp.com/attachments/425702172219408385/564986183906492456/unknown.png

https://cdn.discordapp.com/attachments/425702172219408385/564986276252745769/unknown.png

**Comment by sp614x** [comment]
Most shaders packs render translucent objects in a special way in order to get transparency and reflections correctly. Most probably the shader pack doesn't support normal/specular for translucent objects.
