### ISSUE TITLE
Block rendering, client crash

### ISSUE THREAD

**Issue by ArukaAlter** [sp614x/optifine#230]
http://pastebin.com/dD0c6GTH
Tested on OptiFine 1.10.2 HD U C2
Placing a Mekanism portable tank in a TCon Crafting Station with item preview on causes a client crash.
Does not occur without Optifine.

**Comment by sp614x** [comment]
This looks like a Mekanism crash.
It is trying to use OpenGL commands in the background chunk loading thread which is not possible.
