### ISSUE TITLE
[CEM] Vindicator Support in 1.12.2 HD U E3

### ISSUE THREAD

**Issue by Gunging** [sp614x/optifine#2305]
As the title states, the model of the vindicator cannot be modified with OptiFine 1.12.2 HD U E3.

I've seen a post about mc 1.13 that says that vindicators are now supported, but because mine is not working (Nothing happens even if I set attach to false) I suppose that post refers only to 1.13 OptiFine.

I know my model is working, because solely by changing the name of the .jem file from "vindicator.jem" to "skeleton.jem" the model is applied perfectly to skeletons. But I want this on vindicators.

vindicator.jem file content:
```
{
  "models": 
  [
    {
      "model": "vindicatortst.jpm",
      "part": "body", 
      "attach": true,
      "translate": [0, 0, 0],
      "rotate": [0, 0, 0],
      "scale": 3
    }
  ]
}

**Comment by sp614x** [comment]
In 1.12.2 the vindicator is named "vindication_illager".
The corresponding JEM file is "vindication_illager.jem".
