### ISSUE TITLE
When advanced tooltips are enabled, item IDs appear twice

### ISSUE THREAD

**Issue by Dimentive** [sp614x/optifine#2306]
When advanced tooltips are enabled, item IDs appear twice on every item.

![Double advanced tooltips (cropped)](https://user-images.githubusercontent.com/34230933/55925171-0afa0b00-5c0d-11e9-8c8f-fc78b1ecd5a7.png)

The dark grey `minecraft:diamond` is added by vanilla Minecraft, while the light grey `minecraft:diamond` is added by OptiFine. Before I installed OptiFine, there was only the dark grey one.

When advanced tooltips are on, whether it’s enabled with F3 + H or in OptiFine’s “Other” settings, the item ID tooltip appears twice, and when advanced tooltips are off, they don’t appear at all. There’s no way to only make the vanilla one appear or only make the OptiFine one appear; it’ll always appear twice (with advanced tooltips on) or not at all (with advanced tooltips off).

I am playing with other mods, so there might be some odd conflict with one of the mods, but as mentioned, the item ID only appeared once before I installed OptiFine. I’m not sure whether this happens when only OptiFine is installed, though. I’m also using a preview build of OptiFine, so it could be an issue with this particular build; I’m not sure.

#### Versions

* **Minecraft:** 1.12.2
* **Forge:** 14.23.5.2825 (latest)
* **OptiFine:** 1.12.2 HD U E4 pre1

**Comment by MauveCloud** [comment]
> while the light grey minecraft:diamond is added by OptiFine.

I think you're mistaken about that.  I tried updating to 1.12.2 HD U E4 pre4, and I don't get such a light grey tooltip, even with advanced tooltips on.  Are you using EnderCore (required by Ender IO)?  That has an option in the config "I:showRegistryNameTooltips" for this.  I have already reported it in that mod's issue tracker as being redundant: https://github.com/SleepyTrousers/EnderCore/issues/87

**Comment by sp614x** [comment]
OptiFine doesn't change the contents of the item tooltips.
This is probably caused by something else.

**Comment by Dimentive** [comment]
@MauveCloud @sp614x Whoops, it’s EnderCore. I’m making a private modpack that _doesn’t_ focus on tech mods, so I _don’t_ want Ender IO or EnderCore, but it looks like I accidentally installed it. The Twitch launcher even told me that EnderCore _wasn’t_ installed. It lies!

Sorry about that.

**Comment by Dimentive** [comment]
@MauveCloud @sp614x Whoops, it’s EnderCore. I’m making a private modpack that _doesn’t_ focus on tech mods, so I _don’t_ want Ender IO or EnderCore, but it looks like I accidentally installed them. The Twitch launcher even told me that EnderCore _wasn’t_ installed. It lies!

Sorry about that.

**Comment by NuanKi** [comment]
> [@MauveCloud](https://github.com/MauveCloud) [@sp614x](https://github.com/sp614x) Whoops, it’s EnderCore. I’m making a private modpack that _doesn’t_ focus on tech mods, so I _don’t_ want Ender IO or EnderCore, but it looks like I accidentally installed them. The Twitch launcher even told me that EnderCore _wasn’t_ installed. It lies!
> 
> Sorry about that.

Thanks, i was also having that problem haha
