### ISSUE TITLE
I can not change my cape optfine!

### ISSUE THREAD

**Issue by SrFaltoso** [sp614x/optifine#2308]
Even if I do everything I can not change!

**Comment by realjackasterisk** [comment]
can we please have *some* useful information?
what have you tried already?

**Comment by SrFaltoso** [comment]
> can we please have _some_ useful information?
> what have you tried already?

I've tried a lot ... I tried to change my browser, tried to download E8, tried reinstalling minecraft, tried to search for help on forums, deleted my entire .minecraft, checked the default browser on my computer, and none of that worked!

**Comment by realjackasterisk** [comment]
E8 for 1.13.2, correct? You're not using Forge, are you?

**Comment by SrFaltoso** [comment]
> E8 for 1.13.2, correct? You're not using Forge, are you?

I used E8 and E7! And I'm not using forge.

**Comment by SrFaltoso** [comment]
> E8 para 1.13.2, correto? Você não está usando o Forge, está?

Is there anything I can do to change my cape?

**Comment by KaiAF** [comment]
I doubt this is still an issue now. If it is still an issue, please contact our support team. You can contact us either by [Email](https://optifine.net/contact) or by [Discord](https://optifine.net/discord)
