### ISSUE TITLE
I have questions for the cem animations.

### ISSUE THREAD

**Issue by XKane55** [sp614x/optifine#2310]
HI, I'm not so familiar with coding and I have a couple of questions for the optifine cem : 
- Is it possible to make a mob in minecraft blink his eyes at random moments?
- Is there a way to make an animation wait for a couple of seconds and then continue? 
- If there is a way to make transition animations? (like when the mob is moving and he stops, there is an animation before the idle animation.)

**Comment by sp614x** [comment]
Random animations per mob are not possible.
What is possible is with random entities to assign random textures per mob. Then animate each of the textures with different intervals.

**Comment by XKane55** [comment]
Okay, thanks for the answer!
