### ISSUE TITLE
Static and random textures of mobs

### ISSUE THREAD

**Issue by JacobAnderson21** [sp614x/optifine#2311]
I want to use some random textures for zombies and  use 3 permanent skins for zombies with the names "zombie1", "zombie2", "zombie2"
I wrote this:
skins.1=2-5
skins.2=6
skins.3=7
skins.4=8
name.2=zombie1
name.3=zombie2
name.4=zombie3

but it does not work, how to write it correctly? 

I tested it:

skins.1=2
name.1=!pattern:eve

and "eve" changed the texture anyway, I don't understand it, I use the last optifine 1.13.2
Why ! not working...

**Comment by sp614x** [comment]
Minimal resource pack to reproduce the problem?
