### ISSUE TITLE
Skin

### ISSUE THREAD

**Issue by Locomenmod** [sp614x/optifine#2314]
Hello. I have a launcher. In the configurations of LaucnhServer it is prescribed to take skins from http://site.ru/minecraft/skins/%nick%.png. In a client without an optical file, everything works fine. However, after installation, skins and cloaks stopped working. How to fix it?

**Comment by Locomenmod** [comment]
Can help?
Log: https://pastebin.com/mEAEctck

**Comment by mindforger** [comment]
you might want to delete that log immeditately

**Comment by realjackasterisk** [comment]
@mindforger er, why? i dont see anything that might be private in it
