### ISSUE TITLE
Optifine - Time Speed Mod Crash

### ISSUE THREAD

**Issue by RodrigoTaipe93** [sp614x/optifine#2315]
There seems to be a conflict with this mod:

- https://minecraft.curseforge.com/projects/time-speed-mod

- https://paste.ee/p/JS3d4

**Comment by Cadiboo** [comment]
Does this crash happen without OptiFine installed?

**Comment by RodrigoTaipe93** [comment]
I tested my world without the Time Speed Mod. Seems like that mod is the problem. 
Since I went to sleep again and everything was normal. Nonetheless, I try to share the crash log between both authors to avoid future incompatibilities in the future.

**Comment by Cadiboo** [comment]
Does the crash happen with
- Only OptiFine (no other mods installed)
- Only the Time Speed Mod (no other mods installed)
- Both OptiFine and the Time Speed Mod installed (no other mods installed)

**Comment by RodrigoTaipe93** [comment]
The last part

**Comment by Cadiboo** [comment]
Please post the log with just those two installed

**Comment by sp614x** [comment]
Looks like the TimeSpeedMod patch for WorldServer has failed:
```
java.lang.NoSuchMethodError: sedridor.B3M.B3M_Core.getDawnTime(J)J
    at net.minecraft.world.WorldServer.tick(WorldServer.java:192)
    at net.optifine.override.WorldServerOF.tick(WorldServerOF.java:39)
```
This can only be fixed in TimeSpeedMod.
