### ISSUE TITLE
[REQUEST]

### ISSUE THREAD

**Issue by RodrigoTaipe93** [sp614x/optifine#2316]
This is just a suggestion/request:

I'm trying to play with 192 mods. Therefore, I need some mods to help me with my FPS and RAM, etc etc.

I wanted to suggest compatibility between Optifine and Foamfix!

**Comment by DaMatrix** [comment]
they already are compatible with each other...

**Comment by sp614x** [comment]
OptiFine and FoamFix should be compatible.
