### ISSUE TITLE
MC crash when loading Custom Horse Model

### ISSUE THREAD

**Issue by mexbotdude** [sp614x/optifine#2317]
https://pastebin.com/mQWsbWu0

I made custom models for most of the mobs in my resource pack. However, when  I summon a Horse with the custom texture the game takes 15 seconds to crash. I also have a custom model  for the Mule, however it doesnt seem to crash with it.

![2019-04-15_16 02 38](https://user-images.githubusercontent.com/31808869/56138899-18f6b580-5f98-11e9-9916-1e488a0e8388.png)

this is how my horse.jem file looks like

https://pastebin.com/1FuQTZmW

**Comment by sp614x** [comment]
Can you post the crash report or error log?

**Comment by KaiAF** [comment]
Seems to be fixed now. If you are still having this issue, let me know, please.
