### ISSUE TITLE
Crash: Failed to write core dump

### ISSUE THREAD

**Issue by NeoSmelter** [sp614x/optifine#232]
Hello. I am reporting an extremely annoying crash that (at least for me) occurs very often.

When playing on servers (I'm not sure of singleplayer) I get this crash literally once every 10 minutes or so. It is really annoying and pretty much prevents me on playing multiplayer, because I can't play without OptiFine due to my crappy computer.
    I know this occurs on unmodded Minecraft too, but there it can be fixed by turning VBOs and VSync on. With OptiFine this doesn't help at all.

Here is one of the crash logs: [https://www.mediafire.com/?boi1e4znx1i1sj2](url)
These fill my .minecraft directory right now, hopefully not in the future.

Please fix this. I look forward to playing Minecraft smoothly without needing to restart it every 15 minutes.

**Comment by mindforger** [comment]
link is broken

**Comment by sp614x** [comment]
> # Problematic frame:
> # C  [ig4icd64.dll+0x43033]

The Intel graphics driver is crashing.
You can try to:
- update graphics driver
- enabled/disable VBO
- disable AA/AF
- disable shaders, etc.
