### ISSUE TITLE
Ticking World Crash

### ISSUE THREAD

**Issue by RodrigoTaipe93** [sp614x/optifine#2321]
Hello!

I got another issue.

- https://paste.dimdev.org/isabagural.mccrash

**Comment by RodrigoTaipe93** [comment]
This is strange.

So I tested my private modpack without Optifine. Still got a crash

https://paste.dimdev.org/pevusajamu.mccrash

https://mega.nz/#!gwMWTKTZ!Fl12p57iZPWuH0q92yzL6ig3KkyYz-J3NmQ3ghSF5Gk

My apologiez.

**Comment by sp614x** [comment]
Not related to OptiFine.
