### ISSUE TITLE
Optifine bug or what ever it is..

### ISSUE THREAD

**Issue by DaveGomes12** [sp614x/optifine#2322]
![2019-04-18_01 06 04](https://user-images.githubusercontent.com/49735700/56326661-4483c680-6177-11e9-8021-6dad74be63d1.png)
![2019-04-18_01 05 07](https://user-images.githubusercontent.com/49735700/56326662-451c5d00-6177-11e9-8d30-3619c34adf97.png)
![2019-04-18_01 05 46](https://user-images.githubusercontent.com/49735700/56326663-451c5d00-6177-11e9-830b-25c53f943b25.png)
![2019-04-18_01 05 52](https://user-images.githubusercontent.com/49735700/56326664-451c5d00-6177-11e9-8aac-e289da4940cc.png)
pls help idk know what`s that I just start playing my game and then i walk around etc and then there came like white lines and then this in the pictures starts .... anyone ? sorry for my bad english ....

**Comment by DaveGomes12** [comment]
using minecraft 1.12.2 latest version optifine 1.12.2 tried with a lot of shaders all the same..

**Comment by Quavelen** [comment]
@DaveGomes12, could you please press F3 to open the debug overlay, and then upload a screenshot of that debug overlay here?

**Comment by DaveGomes12** [comment]
> 
> 
> @DaveGomes12, could you please press F3 to open the debug overlay, and then upload a screenshot of that debug overlay here?

![2019-04-18_14 40 31](https://user-images.githubusercontent.com/49735700/56361578-05da2480-61e8-11e9-8c89-89e6e3682c4e.png)

**Comment by DaveGomes12** [comment]
@Quavelen

**Comment by Quavelen** [comment]
That's... odd. It isn't displaying what version of OptiFine you have in the correct location. Instead it only shows it on the same line as the shader. Could you please attempt a reinstall of both Minecraft and OptiFine?

Please ensure you download both explicitly from these two pages:
* https://optifine.net/downloads
* https://www.minecraft.net/download/

**Comment by DaveGomes12** [comment]
@Quavelen yes i did it but now I walk around etc and my game just crashed .-. then there came the thing with java :/
![2019-04-18_15 12 56](https://user-images.githubusercontent.com/49735700/56363434-80a53e80-61ec-11e9-852d-b43d06e954d1.png)

**Comment by Quavelen** [comment]
Well, now we're getting somewhere @DaveGomes12. To tell the game to use your own java installation, simply click on the "Launch options" tab, click on the switch to enable "Advanced settings", click on the OptiFine profile, click on the switch to enable a custom "java executable", and finally enter where your java installation is. Mine for example is `C:\Program Files\Java\jre1.8.0_202\bin\javaw.exe`. 

Regarding the crash, if it happens again after enabling your own java, please open the crash log in a text editor, and then copy paste the contents into this site: https://paste.ubuntu.com Once you do, link that here. If you do not crash again, then don't worry lol.

**Comment by DaveGomes12** [comment]
@Quavelen holy thank you so much :)  
thx for your time :)

**Comment by Quavelen** [comment]
Yup, you're welcome. =)

**Comment by DaveGomes12** [comment]
![2019-04-18_15 51 40](https://user-images.githubusercontent.com/49735700/56365762-e8aa5380-61f1-11e9-854f-e5a70755ff09.png)
@Quavelen  woops there it is again

**Comment by Quavelen** [comment]
@DaveGomes12 match your mipmaps to this, and do not change them:

![image](https://user-images.githubusercontent.com/19168008/56366292-b9441880-61ea-11e9-8fe7-91f9c2a9afb6.png)

**Comment by DaveGomes12** [comment]
@Quavelen  did happen again :/

**Comment by Quavelen** [comment]
@DaveGomes12 could you please join the official OptiFine discord? It'll be easier to offer support to you there. 

https://discordapp.com/invite/tKxWtyf

People who know more than me will be able to quickly answer you. Not everyone follows the GitHub.

**Comment by DaveGomes12** [comment]
@Quavelen sure

**Comment by sp614x** [comment]
Looks like a driver, GPU or shader problem.
Not directly related to Optifine.
