### ISSUE TITLE
[CEM] Ender dragon `jaw` not working

### ISSUE THREAD

**Issue by MushirMickeyJoe** [sp614x/optifine#2323]
![jawless dragon](https://user-images.githubusercontent.com/31923214/56355696-41202780-61d7-11e9-8a4a-b53d1c8b5be2.png)
I'm certain my files are correct at this point, but I can't seem to change the ender dragon's jaw using CEM.

Even when I just change the ender dragon's `head` using CEM, the default jaw disapears as if it's part of the head.
I've made a custom .jpm file for the dragon jaw but it's not showing up either.

**Comment by MushirMickeyJoe** [comment]
![double jawed dragon](https://user-images.githubusercontent.com/31923214/56355887-bc81d900-61d7-11e9-95d1-fdf1dfd02fcc.png)
I've done some testing and CEM definitely thinks the jaw is part of the default head mode. In this screenshot I've set `attatch` to `true`, and the jaw (including my custom jaw model) show up.

**Comment by sp614x** [comment]
Works for me in preview F3 for 1.14.4:

![image](https://user-images.githubusercontent.com/16635441/62424587-e270b200-b6d0-11e9-9667-0007e0973f29.png)

dragon.jem
```
{
  "texture": "optifine/cem/cow.png",
  "textureSize": [64, 32],
  "models": 
  [
    {
      "id": "Jaw",
      "model": "pirate_leg.jpm",
      "part": "jaw", 
      "translate": [0, 0, 0],
      "rotate": [-70, 0, 0]
    }
  ]
}
```

**Comment by MushirMickeyJoe** [comment]
using 1.14.4 F3 pre3,

why doesn't the jaw show up for me then? Here's my dragon.jem

```
{
  "models": 
  [
    {
      "model": "rid_dragon_head.jpm",
      "part": "head", 
	  "attach": false,
      "translate": [ 7, 6, -12],
      "rotate": [0, 0, 0]
    },
	{
      "model": "rid_dragon_horns.jpm",
      "part": "head", 
	  "attach": true,
      "translate": [ 7, 11, -6],
      "rotate": [30, 0, 0]
    },
	{
      "model": "rid_dragon_jaw.jpm",
      "part": "jaw", 
	  "attach": false,
      "translate": [ 7, 2, -3.5],
      "rotate": [0, 0, 0]
    }
  ]
}
```

**Comment by sp614x** [comment]
The jaw model is attached to the head so that it moves together with it.
When replacing the head model (attach=false), the jaw model is also replaced as it is attached to the head.
The solution would be to detect child models which are accessible by name and not remove them when replacing the parent.

**Comment by MushirMickeyJoe** [comment]
Right. I'd obviously like to be able to actually replace the head. Is there anything I can do to fix this right now, or do you need to make some changes to CEM first?

**Comment by sp614x** [comment]
Fixed, coming in next preview.
