### ISSUE TITLE
Trees shining at night

### ISSUE THREAD

**Issue by DicDale** [sp614x/optifine#2325]
![234234](https://user-images.githubusercontent.com/25640173/56477071-289b6000-64aa-11e9-82cc-65edcd1bfed2.png)
![333](https://user-images.githubusercontent.com/25640173/56477072-289b6000-64aa-11e9-9a01-db666fea96d9.png)
![cccc](https://user-images.githubusercontent.com/25640173/56477081-55e80e00-64aa-11e9-8eab-067bc256fc27.png)
![xxc](https://user-images.githubusercontent.com/25640173/56477089-6c8e6500-64aa-11e9-92c0-2618d8b96ab0.png)

**Comment by DataCrusade** [comment]
It's likely a compatibility issue with one of the 24 mods you're using. You can remove half the mods, and keep the group that still has the issue until you narrow down the mod causing the issue.

**Comment by KaiAF** [comment]
No response from the Author, closing issue.
