### ISSUE TITLE
Problem with the cit function . Weird Things Happening XD 

### ISSUE THREAD

**Issue by Shaddict** [sp614x/optifine#2327]
Hi . I'm creating a resource pack and a met something ..... weird :

In the **cit** folder , I put a .JSON file for my model and a .PROPERTIES file to make this working .
![files](https://user-images.githubusercontent.com/49870420/56501500-152adc00-6520-11e9-9e76-14619918b446.PNG)
In my .PROPERTIES file I've got that :
![properties file](https://user-images.githubusercontent.com/49870420/56501534-38ee2200-6520-11e9-8f51-63fbccf662a4.PNG)
So if everything is perfect , it's suppose to look like that :
![sword](https://user-images.githubusercontent.com/49870420/56501604-6cc94780-6520-11e9-8094-49745407c7c2.PNG)
But when I rename it like in the .PROPERTIES file : 
![Enclume](https://user-images.githubusercontent.com/49870420/56501638-88cce900-6520-11e9-9430-f1ff8a9064bb.PNG)
That weird thing happens : 
![InGameResult](https://user-images.githubusercontent.com/49870420/56501661-9c784f80-6520-11e9-9404-dd1be31f94dd.PNG)

So if you know why it does that ... please tell me XD

And , sorry if my English is not perfect , you may notice my game is in French because i'm French .

**Comment by realjackasterisk** [comment]
pretty sure you need to adjust the "display" transformations in the model file to fix that odd position/rotation. this has nothing to do with CIT

**Comment by Zefferis** [comment]
There's a "#help_and_technical" chat channel in the Texture Artist's Union Discord Server that can also give you some insight:

https://discord.gg/phNp3R

**Comment by Shaddict** [comment]
> 
> 
> pretty sure you need to adjust the "display" transformations in the model file to fix that odd position/rotation. this has nothing to do with CIT

Yes I know but my model doesn't show , it's the problem . It's suppose to be a sword , not a chest

**Comment by Shaddict** [comment]
> 
> 
> There's a "#help_and_technical" chat channel in the Texture Artist's Union Discord Server that can also give you some insight:
> 
> https://discord.gg/phNp3R

Okay thanks , I will check .

**Comment by Shaddict** [comment]
> 
> 
> There's a "#help_and_technical" chat channel in the Texture Artist's Union Discord Server that can also give you some insight:
> 
> https://discord.gg/phNp3R

Okay thanks , I will check .

EDIT: Okay , the comment was deleted ...
