### ISSUE TITLE
Make 1.14 Optifine

### ISSUE THREAD

**Issue by Govindass** [sp614x/optifine#2329]
title ^

**Comment by Govindass** [comment]
> seriously? this is just spam

well I noticed there being no any information about 1.14 anywhere in optifine website, so I thought I should create issue.

**Comment by Quavelen** [comment]
>well I noticed there being no any information about 1.14 anywhere in optifine website, so I thought I should create issue.


You should maybe try joining the official discord server. 

![image](https://user-images.githubusercontent.com/19168008/56638386-efa7ea80-6665-11e9-9268-8f2a1f3e4b62.png)

**Comment by Tokenyet** [comment]
If you want to get Optifine 1.14 ASAP, I suggested you go to the link below:
[https://optifine.net/donate](https://optifine.net/donate)

If you have such a big power to support @sp614x, I'm pretty sure that you could get the fresh hot pre-pre-alpha version of Optifine 👍 

I agree with @realjackasterisk, this is a spam issue, and would be unconfortable for developer.

**Comment by Govindass** [comment]
> If you want to get Optifine 1.14 ASAP, I suggested you go to the link below:
> https://optifine.net/donate
> 
> If you have such a big power to support @sp614x, I'm pretty sure that you could get the fresh hot pre-pre-alpha version of Optifine 👍
> 
> I agree with @realjackasterisk, this is a spam issue, and would be unconfortable for developer.

is there a way to donate via PayPal?

**Comment by realjackasterisk** [comment]
currently no

**Comment by Bilgewat3r** [comment]
> well I noticed there being no any information about 1.14 anywhere in optifine website, so I thought I should create issue.
> 
> You should maybe try joining the official discord server.

Would be easier if one knew where to find the invite link. Or if you provided it too.

**Comment by realjackasterisk** [comment]
https://discord.gg/3mMpcwW

**Comment by TeraGX** [comment]
> You should maybe try joining the official discord server.

I have to say I started my 1.14 info hunt with first looking for an OptiFine Discord server. The Discord server is not mentioned on optifine.net, the minecraftforum post, his Twitter, GitHub or any documentation, and the blogspot link is surely a meme.

An "issue" like this one shouldn't be needed, but it did more good for me than that reply. A Discord link should be near the top of the main page, maybe like how vivecraft.org has it.

**Comment by realjackasterisk** [comment]
yeah im not sure why sp614x keeps it like a secret. anyone can join and make invite links, its entirely public so idk. the first invite link was posted on the shaderLABS discord server and it just kinda grew from there

i've made sure to add plenty of links to the discord on the new subreddit, though. probably borderline advertising but at least now its in a *sort of* public spot.

**Comment by sp614x** [comment]
It was not publicly advertised in order to avoid the general users.
The first links were posted in shaderlabs and packpainters so more technical users could join.
This is probably not so relevant now.

**Comment by sp614x** [comment]
Update 1.14 is on the way.
