### ISSUE TITLE
Crash with VBO

### ISSUE THREAD

**Issue by jochuan** [sp614x/optifine#233]
when i try to use the VBO option the game crashes i am using optifine ultra B6 for 1.9.4 with the latest forge
https://gist.github.com/jochuan/1573388c3dfe89330079a1441f9df824
https://gist.github.com/jochuan/87a52617fe8b1f61c761c3c26c2473b0

**Comment by sp614x** [comment]
> Problematic frame:
> C [ig4icd32.dll+0x6208e]

The Intel graphics driver has crashed.
Updating the driver may help.
