### ISSUE TITLE
Error starting with Java 9

### ISSUE THREAD

**Issue by Redo11** [sp614x/optifine#2330]
Just don't starting. Printed error in console:
"Exception in thread "main" java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
"
Java 11 ( Java 8 works fine) on linux (Ubuntu 18.4) with version 1.13.2.

**Comment by SetantaLP** [comment]
That's a bug inside the launchwrapper optifine uses to launch the game (see #2070). This bug exists due to the changes made between java 8 and java 9, so to fix the bug, you can either use java 8 or an altered version of the launchwrapper.

**Comment by Redo11** [comment]
Already tried and launches, but crashes after audio engine starts

25 kwi 2019 10:30 SetantaLP <notifications@github.com> napisał(a):

That's a bug inside the launchwrapper optifine uses to launch the game (see #2070<https://github.com/sp614x/optifine/issues/2070>). This bug exists due to the changes made between java 8 and java 9, so to fix the bug, you can either use java 8 or an altered version of the launchwrapper.

**Comment by sp614x** [comment]
OptiFine 1.14.3_HD_U_F1
 - fixed compatibility with Java 9+

**Comment by Redo11** [comment]
Love you😍thx

On 27 Jun 2019 17:09, sp614x <notifications@github.com> wrote:

OptiFine 1.14.3_HD_U_F1

  *   fixed compatibility with Java 9+
