### ISSUE TITLE
100+ Custom Optifine Entity Models?

### ISSUE THREAD

**Issue by CombatBorn** [sp614x/optifine#2332]
Hello. I’m interested in making a rather large resource pack filled with Hundreds of custom created .jem files. However, it says I must name .jem files ‘entity name.jem’. If that’s the case, I’m only limited to a certain set of customized Optifine Entities.
Is there any possible way for me to achieve hundreds of custom Optifine Entity models?

**Comment by realjackasterisk** [comment]
....Uh, what? How is the file type going to limit how many models you can use?

**Comment by SaitoValliere** [comment]
The format is <entity name>.jem. Therefore ‘iron_golem2.jem’ wouldn’t be a valid name for a .jem file. However, ‘iron_golem.jem’ is a valid name.

**Comment by realjackasterisk** [comment]
....*oh i see.*

yeah i really shouldn't be posting at 4-5 in the morning.

**Comment by CombatBorn** [comment]
Still looking

**Comment by sp614x** [comment]
Currently there is only one CEM model per entity type and it uses the entity name.
The "iron_golem2.jem" can't be loaded as there is no entity named "iron_golem2".

You are probably thinking about Random Entities which allows several textures per entity. This functionality is not available in CEM.

Relevant #572, #2100, #937, #377.
