### ISSUE TITLE
Font looks blurry using OptiFine 1.12.2 HD U E4 pre4.

### ISSUE THREAD

**Issue by Mario0051** [sp614x/optifine#2339]
Using the Normal or Large GUI Scale, the font is blurry (issue does not show up with Small GUI Scale or with force Unicode font on). Mipmaps, antialiasing, and anisotropic filtering are all off.

Here is an example of the issue:
![image](https://user-images.githubusercontent.com/16366524/56870107-1e53f700-69bf-11e9-9521-fc0293343888.png)

**Comment by Mario3264** [comment]
On another note, it also blurs the GUI, and blocks if you hold an item above a GUI.

**Comment by sp614x** [comment]
Is this with Forge or standalone?
Forge version, list of other mods installed?
Custom resource pack?

**Comment by Mario3264** [comment]
It happens when I placed Optifine into the modpack SkyFactory 4, I am not sure of the exact cause.

**Comment by KaiAF** [comment]
Is this still an issue?

**Comment by Mario0051** [comment]
Probably not an issue anymore, the text appears fine in my quick testing.
