### ISSUE TITLE
Crash with StacksOnStacks mod

### ISSUE THREAD

**Issue by Bulldog83** [sp614x/optifine#234]
Crash log: https://gist.github.com/Bulldog83/391b1de5e643c7e0c9a36337a4147409

**Comment by darthvader45** [comment]
Noticed this on their CurseForge page, that they cannot fix this.  Can an Optifine dev fix this?  We will see.

**Comment by Bulldog83** [comment]
Some one has done it already. [Here](https://github.com/primetoxinz/StacksOnStacks/issues/12).

**Comment by darthvader45** [comment]
I was wondering if an Optifine dev could fix this.

**Comment by sp614x** [comment]
The crash does not seem to be related to OptiFine.
The BlockMultipartContainer is using an unsynchronized map and it crashes on multithreaded access.
The first thread is the rendering thread (it should be identical to vanilla), the other thread may be the server thread or some other backgroudn thread (minimap?).

**Comment by darthvader45** [comment]
Quoted straight from their page: "This mod is incompatible with optifine, attempting to place an ingot with optifine installed will crash your game due to it's hacky render changes. This cannot be fixed."

**Comment by sp614x** [comment]
A similar bug related to StacksOnStacks was fixed in a recent version. 
Maybe this issue is not relevant anymore.

**Comment by darthvader45** [comment]
I'll see.
