### ISSUE TITLE
Donation Email inaccesible

### ISSUE THREAD

**Issue by 8BitItv** [sp614x/optifine#2340]
I donated about 3 to 4 years ago, with an email from our internet provider, which were all removed a few years back, is there anything I could do to still log into the Optifine site?

Thank you!

(MC Username: 8BitItv) 

Edit: Is there any way to get the first and last few letters of the donators mail connected to my account?, 
I saw this happen in another post...

**Comment by ZenIsBestWolf** [comment]
Unfortunately email changes are not possible, sorry for the delayed response.
