### ISSUE TITLE
[Discord] Role name changes

### ISSUE THREAD

**Issue by JackDotJS** [sp614x/optifine#2347]
Now this is totally different (and maybe borderline off-topic) from the other issues that are normally posted here, but @sp614x himself has informed me that this would fit here. I have many more suggestions which I might post later, but I'll start with this.

I'd like to suggest renaming a decent chunk of roles for our Discord server. A lot of confusion stems from the current set of role names, especially "Mod Developer."

In order of **most-to-least importance,** this is a list of replacement names I've come up with.

| Current Name | Suggested New Name |
| --- | --- |
| Mod Developer | Forge Mod Developer |
| OptiFine | OptiFine Developer |
| Shader Developer | Shader Pack Developer |
| Texture Artist | Resource Pack Creator |

### Reasons for change

I very often see people get VERY confused about the few people with the "Mod Developer" role. They assume people with this role are *OptiFine* developers, going as far as contacting them via DM hoping to resolve issues with their game.

![image](https://user-images.githubusercontent.com/31686191/57127805-5c964100-6d46-11e9-9ab9-281600693783.png)

![image](https://user-images.githubusercontent.com/31686191/57128208-8b60e700-6d47-11e9-993d-7080c999b710.png)

I believe it would help to specify that the "Mod Developer" role is specifically for Forge mods. To support this change, I also believe renaming sp614x's role to "OptiFine Developer" will clear up a majority of the confusion.

As for the remaining two roles, these are mostly cosmetic. The new "Forge Mod Developer" name ends up being quite long compared to the other technical roles, so I feel it's appropriate to keep them all syntactically consistent for the most part.

**Comment by sp614x** [comment]
"Mod developer" may be confusing as OptiFine is also a mod.
On the other hand "Forge Mod Developer" is also confusing because Forge is not the only mod loader (fabric, liteloader, etc.).
Correct would be "Other Mod Developers" or "Non-OptiFine Mod Developers", but they are too verbose.

**Comment by realjackasterisk** [comment]
I figured Forge alone would be appropriate, as OptiFine only officially supports the Forge modloader. 

On the other hand, I've already updated that to be simply "Modder" in my complete redesign server. 
![image](https://user-images.githubusercontent.com/31686191/61547695-c5658f00-aa00-11e9-8274-6b726c01d0cf.png)

**Comment by realjackasterisk** [comment]
"Non-OF Modder" was suggested on the Discord.

**Comment by realjackasterisk** [comment]
Updated names: 
![image](https://user-images.githubusercontent.com/31686191/61550695-044b1300-aa08-11e9-8c0b-bdf30225c8d5.png)

**Comment by realjackasterisk** [comment]
### Color HEX codes:
OptiFine Developer - #e29f00
Moderator - #c42121
OptiBot - #e29f00
Muted - #010101 (Discord wouldn't let me use pure black)
Donator - #ff5f0c
Non-OF Modder - #6c85af
Shader Developer - #53b3b7
Texture Artist - #94c945

**Comment by JackDotJS** [comment]
no longer relevant
