### ISSUE TITLE
[Discord] Ability to "shutdown" the #feedback channel when not in use

### ISSUE THREAD

**Issue by realjackasterisk** [sp614x/optifine#2349]
This channel seems to only really be used when sp614x is showcasing new features and asking for community feedback. Like I said in my previous post, (#2348) this only happens every once in a while, so I feel that making the channel inaccessible to general users will help to cut down on spam and off-topic posts. (effectively saving us moderators time and effort)

To simplify this process, a new OptiBot command could be used to quickly toggle sets of permissions on the channel. This would give the channel two modes of operation: Open and closed.

When open, the channel is essentially free for all to post, like right now. Pretty self-explanatory.
When *closed* however, nobody is allowed to post messages, except for moderators and admins.

There's not really much else to it. The only change this would require is granting the "manage channels" permission for OptiBot. I suppose you *could* do this by hand instead of giving more permissions for the bot, but that'd be really time-consuming. 

EDIT: Permissions can be set per user *and* per channel. In this case, it would make more sense to have optibot only have the "manage channels" permission for this one channel.

**Comment by sp614x** [comment]
Added "Manage Permissions" to OptiBot for #feedback
