### ISSUE TITLE
Weird leave texture

### ISSUE THREAD

**Issue by Batman5300** [sp614x/optifine#235]
In the picture, I was using OptiFine 1.8.9 HD U H6. In my video settings for Trees, it is set to fast. In fact, I use the lowest settings because I have a crappy computer. 

Here is a picture of my problem:
http://i.imgur.com/LL9P88u.png

This applies for any version of OptiFine, but never happens on Vanilla.

**Comment by sp614x** [comment]
Need more details:
- OptiFine version
- Forge version (installed?)
- Other mods installed?
- Trees setting (smart trees?)
- Debug screenshot (F3)

**Comment by Batman5300** [comment]
OptiFine Version: OptiFine 1.8.9 HD U H6
Forge: No
Other mods: 5Zig
Tree setting: Fast
Debug Screenshot: http://imgur.com/iVgT74t

**Comment by sp614x** [comment]
Is this happening without the 5Zig mod?

**Comment by Batman5300** [comment]
Yes, it is happening with the 5Zig mod

**Comment by sp614x** [comment]
Is it fixed after resetting video settings?
Video Settings -> Other -> Reset Video Settings

**Comment by Batman5300** [comment]
No, it is not fixed after resetting my video settings. Yes, I followed your instructions to reset your video settings.

**Comment by Batman5300** [comment]
Anything yet?

**Comment by sp614x** [comment]
Make sure to test with OptiFine only. 
Install OptiFine and start the OptiFine profile in the vanilla launcher.
I can not reproduce it and there have never been reports about a similar bug.

**Comment by sp614x** [comment]
Not reproducible.

**Comment by EzerArch** [comment]
A guy who's using my resource pack pointed out something similar: https://twitter.com/EzerArch/status/835001595955904512

This is what might be happening:
1. In vanilla minecraft, each leaf block has two versions: 1) normal with transparent pixels, for fancy graphics, and 2) opaque, for fast graphics.
2. But you are using a resource pack. As we know, the resource pack overrides vanilla.
3. Yet, the resource pack you are using uses leaf blocks with CTM/properties for Optifine. So the textures from \minecraft\textures are replaced with those in \minecraft\mcpatcher\ctm + properties.
4. Here's where the problem might be: either, the resource pack lacks the 2 leaf versions (said in item 1) in \minecraft\mcpatcher\ctm, or, Optifine doesn't support graphics mode change for leaves (TBH, I don't know).

Therefore, no matter if you are on fancy or fast graphics, Optifine will use the png file saved in \minecraft\mcpatcher\ctm\{leaf_block_dir} which has supposedly transparent pixels, which in turn - if used in fast graphics - will cause the glitch shown in the 1st post.

In the resource pack I'm maintaining, the only leaf block that has CTM is the birch leaves. It is also the only one that glitches out.
Fancy:
![2017-03-11_13 34 01](https://cloud.githubusercontent.com/assets/6743303/23824946/7b4ca256-065f-11e7-8142-94dfadaaea71.png)
Fast:
![2017-03-11_13 34 22](https://cloud.githubusercontent.com/assets/6743303/23824947/7b4cffda-065f-11e7-82c9-1c8506c75f5c.png)
I haven't figured out yet: How to tell Optifine to use X.png for fancy graphics, and Y.png for fast.
