### ISSUE TITLE
[Discord] Allow moderators to post OptiFine-related announcements in the #updates channel

### ISSUE THREAD

**Issue by JackDotJS** [sp614x/optifine#2356]
Note: This suggestion works best in conjunction with my recent additions to #2348.

Posting updates on OptiFine-related things, such as the Forge compatibility post from a while ago, feels a bit inappropriate for a channel that is mainly focused on meta server-related updates (rules changed, invite links updated, etc)

It would be much nicer to be able to post this type of content in the one announcements-type channel that is dedicated solely to OptiFine as a Minecraft mod. For those with notifications enabled, (which is a large majority of people, I would assume) this would reduce the mystery of what to expect when reading what channel the notifications came from.

Before someone says something like "But that channel is for changelogs!", sp614x himself has posted announcements about the OptiFine website, MCP patches, and various other things that are OptiFine-specific. Not always just changelogs.

**Comment by sp614x** [comment]
The #updates was designed as realease updates (new versions, new features), not general updates.
#announcements should be for general topics.

**Comment by realjackasterisk** [comment]
perhaps priority announcements (changelogs, releases, etc) could be posted with an @everyone/@here. I imagine a large amount of people on the server are just there to know when updates are released, so this would help give them more options for notification settings

**Comment by JackDotJS** [comment]
not really relevant anymore, this is more appropriate for admins at this point
