### ISSUE TITLE
Armorstand CEM model part not found: head

### ISSUE THREAD

**Issue by AhmetDS** [sp614x/optifine#2358]
getting this error "[OptiFine] Model part not found: head, model: bpe@5a70de9d"

[https://cdn.discordapp.com/attachments/520581956094787603/574661359493709825/unknown.png](url)

**Comment by sp614x** [comment]
Can you post a minmal resource pack reproducing the problem?

**Comment by AhmetDS** [comment]
[optifine.zip](https://github.com/sp614x/optifine/files/3148682/optifine.zip)

**Comment by AhmetDS** [comment]
:/

**Comment by sp614x** [comment]
The armorstand "head" model is working correctly.

![image](https://user-images.githubusercontent.com/16635441/66848652-bfd30300-ef75-11e9-924e-7235e77e1343.png)
