### ISSUE TITLE
Possibility to set/lock the Smooth Lighting Level for a shaderpack?

### ISSUE THREAD

**Issue by DeDelner** [sp614x/optifine#236]
For example `smoothLightningLevel=0.5` in the shader.properties file or as a constant.

**Comment by sp614x** [comment]
This is possible

**Comment by DeDelner** [comment]
Yuy! :3

**Comment by sp614x** [comment]
It may be better to export the smooth lighting level as an attribute. 
Then it should not be fixed.

**Comment by DeDelner** [comment]
I guess `const float ambientOcclusionLevel = 0.8f;` was supposed to control the smooth lightning level. But it's not working anymore :T

**Comment by sp614x** [comment]
Enabled "const float ambientOcclusionLevel" to control AO level.
Values are between 0.0 (AO disabled) and 1.0 (vanilla AO level, same as old value 0.8)
Coming in next preview C3 for 1.10.2.

**Comment by DeDelner** [comment]
Nice! :3
