### ISSUE TITLE
[Shaders] Player through the walls

### ISSUE THREAD

**Issue by 6ix7even** [sp614x/optifine#2365]
With any shader, you can see a player through the walls

I have E8 pre1 in 1.13.2

Continuum 2.0.2
![2019-05-08_19 17 40](https://user-images.githubusercontent.com/44172841/57394860-e589fe00-71c6-11e9-8efe-034bb603d66f.png)

Chocapic 13 V8
![2019-05-08_19 18 02](https://user-images.githubusercontent.com/44172841/57394861-e589fe00-71c6-11e9-873d-d59567c16cf2.png)

Robobo1221 V8
![2019-05-08_19 18 16](https://user-images.githubusercontent.com/44172841/57394863-e6229480-71c6-11e9-921b-eb3bb0d56820.png)

Sildurs Vibrant V1.20
![2019-05-08_19 25 39](https://user-images.githubusercontent.com/44172841/57394979-2eda4d80-71c7-11e9-85fe-75a550290f48.png)

**Comment by Kaydax** [comment]
This is only caused when the player has the "Glowing" status effect on them. You can even see by the screenshots you provided that you can see other players names but not their model.

**Comment by sp614x** [comment]
The glowing entities are visible through walls, this is vanilla functionality.
With shaders the vanilla entity outline is not visible.
Relevant #2328
