### ISSUE TITLE
[Suggestion] Blocks on Capes

### ISSUE THREAD

**Issue by ilkerbey-01** [sp614x/optifine#2366]
Okay, so this is a simply idea. Like OF or patterns we can set a new looking for capes thats a block, the block will be in middle that used for inventory texture. We will able to turn left or right or move it to up or down. We are able to set background and how big the block will be.
Sorry for bad english, english isnt my native language. Thanks.

UPDATED:
> This is for blocks:
> ![Screenshot_3](https://user-images.githubusercontent.com/34978332/58876506-fdc23f80-86d6-11e9-8e6b-9010947e43d7.png)
> And this is for items:
> ![Screenshot_5](https://user-images.githubusercontent.com/34978332/58876633-5f82a980-86d7-11e9-9eb6-226c011e5782.png)

> Capes saving as png files so that wont be a really problem I believe.
> ![Screenshot_4](https://user-images.githubusercontent.com/34978332/58878548-31539880-86dc-11e9-92c3-62393a74354f.png)
> Also thats how it will look like in cape edit site. Scale will work like font size. But will change size of block or item.

**Comment by Galaxy-Prism** [comment]
What about being able to add a .png file to be able to customise a cape to ones liking?

**Comment by realjackasterisk** [comment]
@Galaxy-Prism this has been suggested a hundred times before. its never going to happen.

**Comment by ilkerbey-01** [comment]
@Galaxy-Prism you cant stop using illegal photos like racism, pornography etc. So thats not a so good idea...

**Comment by Artuto** [comment]
Setup a neural network with AI that checks for inappropriate images :^)

**Comment by ilkerbey-01** [comment]
So much work for a not really useful feature

**Comment by Galaxy-Prism** [comment]
Oh yeah... I forgot about that.

**Comment by Redd56** [comment]
We gonna leave it at blocks, or at most custom with manual review

**Comment by ilkerbey-01** [comment]
I have a few more ideas but firstly Sp614x should accept that before I publish other ones

**Comment by MastaNub** [comment]
How exactly would that look? Could you post an image of how you'd imagine said cape design to look like?

**Comment by ilkerbey-01** [comment]
This is for blocks:
![Screenshot_3](https://user-images.githubusercontent.com/34978332/58876506-fdc23f80-86d6-11e9-8e6b-9010947e43d7.png)
And this is for items:
![Screenshot_5](https://user-images.githubusercontent.com/34978332/58876633-5f82a980-86d7-11e9-9eb6-226c011e5782.png)

**Comment by MastaNub** [comment]
I believe capes have texture size too small for the first one so it would look pixelated.

**Comment by ilkerbey-01** [comment]
Capes saving as png files so that wont be a really problem I believe.
![Screenshot_4](https://user-images.githubusercontent.com/34978332/58877847-7ecf0600-86da-11e9-8d1f-5fb15cb48db8.png)
Also thats how it will look like in cape edit site. Scale will work like font size. But will change size of block or item.

**Comment by ilkerbey-01** [comment]
noticed I forgot to place dirt block to elytra texture lmao...

**Comment by ZenIsBestWolf** [comment]
These items are copyrighted by Mojang.
