### ISSUE TITLE
[cape] i am having trouble using paymentwall (fasterpay) to donate for my optifine cape.

### ISSUE THREAD

**Issue by Varbil** [sp614x/optifine#2367]
I have once tried to pay, but when the i have entered my card details it just goes to a white screen. Do i need to make a fasterpay login and if so, the login doesn't seem to work. I can also not use paysafecard only visa card

**Comment by realjackasterisk** [comment]
> it just goes to a white screen.

Are you using an adblocker?

**Comment by Varbil** [comment]
no.

Den søn. 12. maj 2019 kl. 15.31 skrev Kyle Edwards <notifications@github.com

**Comment by sp614x** [comment]
You should contact Paymentwall, only they can fix this.
