### ISSUE TITLE
[CEM/RandomEntities] Containers lose model when changing dimensions, logging off, or dying.

### ISSUE THREAD

**Issue by InfiniteCorners** [sp614x/optifine#2368]
Recently I decided to try combining CEM, RandomMobs, and CIT to insert unique block textures into the game, which worked very well: I now have the ability to texture shulkers and chests and place the blocks into the world with their texture preserved. As nice as it is to be able to add as many decorative blocks to the game  and texture/model them how I want; this feature seems to be made mostly useless due to the fact the textures reset to default if you die, change dimensions or log out of the world with nothing short of breaking and replacing the items fixing the issue.

I spawned a zombie, named it to change the texture, and this texture was preserved when changing dimensions and so forth but the anvil named shulkerbox does not. Is there any way to fix this situation? I have noticed that when I use pick-block on the blocks they return an unnamed chest to my inventory BUT opening the chest reveals that the name is intact and I would expect the texture to still be valid. I'm not sure if there is something I's doing wrong or something you could change so these container entities render like other Random Entities but this would be a really nice feature if it could be used reliably and consistently. 

(Using most recent build of Optifine 1.13.2)

**Comment by sp614x** [comment]
When loading a world or changing dimensions the server sends some containers (chests, shulker boxes, etc) without a name. The name is first send to the client when the player opens the chest or shulker box.

**Comment by InfiniteCorners** [comment]
Is there nothing that can be done about this? I understand what you're saying but I don't understand why the textures can't be refreshed by opening/closing them, which reveals their name to me but doesn't seem to signal to optifine a texture should be applied.
