### ISSUE TITLE
[CEM] Option to add a simple .json model for the mooshroom's mushroom

### ISSUE THREAD

**Issue by MushirMickeyJoe** [sp614x/optifine#2376]
Because this doesn't look too good. I'd like to make a custom model instead of only being able to set a custom texture for the mooshroom's mushroom (same goes for the new brown mooshroom).

![2019-05-17_18 53 51](https://user-images.githubusercontent.com/31923214/57943769-35f31100-78d5-11e9-9a77-140eba5f539f.png)

**Comment by ewanhowell5195** [comment]
u can make the texture transparent and then just custom model them

https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/cem_model.txt#L12

**Comment by KaiAF** [comment]
What Ewan said ^
