### ISSUE TITLE
Deferred_pre, composite_pre, and buffer flipping.

### ISSUE THREAD

**Issue by jcm2606** [sp614x/optifine#2378]
According to the documentation, there are virtual programs called "deferred_pre" and "composite_pre" that exist to flip the ping-pong buffers. We are able to control the flips of any other program, including the "_last" deferred and composite programs, but not these two. Trying to control the flips of these two leads to flipping breaking entirely, and the shaders mod complaining that we're referencing programs that don't exist.

Is the documentation wrong? Do these programs not exist? If they do, why aren't we able to control their flipping? Not being able to control the flipping makes building data pipelines around controlled flipping, such as the one used in the Continuum base, so, so, so much more complicated than they should be.

**Comment by sp614x** [comment]
In 1.13.2_HD_U_E5 the deferred/composite_last programs were removed and the deferred/composite_pre were added. These changes are not ported to 1.12 and below yet.
https://optifine.net/changelog?f=OptiFine_1.13.2_HD_U_E5.jar
