### ISSUE TITLE
Connected textures

### ISSUE THREAD

**Issue by snoggie1487** [sp614x/optifine#2386]
In 1.14, the connected glass / bookshelf texture uses the old textures (programmer art) instead of the new ones.

![image](https://user-images.githubusercontent.com/38010396/57987838-dcaded80-7a4c-11e9-889b-283dee7f59e4.png)

![image](https://user-images.githubusercontent.com/38010396/57987844-e899af80-7a4c-11e9-9742-062157399403.png)

**Comment by sp614x** [comment]
Fixed in latest preview.
