### ISSUE TITLE
Smooth Sandstone Stairs

### ISSUE THREAD

**Issue by MrDuckers** [sp614x/optifine#2388]
After using the preview version, I thought it best to bring up the fact that the texture for the base of the smooth sandstone stairs is missing, it appears to be invisible and allows people to see through it. Picture evidence below.

![ssissue](https://user-images.githubusercontent.com/37488150/57996157-383db100-7b09-11e9-8a50-2c20805baf1a.png)

Forge is not installed, as there is no 1.14 version. Only optifine is enabled

**Comment by sp614x** [comment]
Fixed in latest preview.
