### ISSUE TITLE
Resolution Reset on Fullscreen

### ISSUE THREAD

**Issue by GreyAsteroid** [sp614x/optifine#239]
I'm using Optifine on a Linux operating system and ever since 1.10 whenever I enter fullscreen with the resolution set to a non-default resolution, the screen goes black for a few seconds and the entire monitor's resolution is changed to the set resolution instead of just Minecraft.

The two issues with this are:
1. This causes the monitor to shut off for around 2-5 seconds depending on the monitor whenever fullscreen is entered and exited because of the resolution being changed.
2. This causes Minecraft to ignore custom resolution settings in the display server meaning that it ignores things like monitor overclocking and color range causing, in my case at least, my monitor to lose it's 75hz overclock and default back to 60hz and for the display to go back to limited 16:235 color range instead of full causing a greyish picture while in fullscreen.

**Comment by sp614x** [comment]
Looks like a graphics driver problem. 
OptiFine uses the same fullscreen functions as vanilla, it only selects a custom mode. Maybe the custom modes are not reported properly.

**Comment by sp614x** [comment]
Driver problem
