### ISSUE TITLE
1.14 Pre2 Crash on Launch with MultiMC Field Not Found: EntityVillager

### ISSUE THREAD

**Issue by ScottoMotto** [sp614x/optifine#2392]
Optifine preview for 1.14 crash on launch with MultiMC. Works in the Vanilla launcher. 

[12:52:51] [main/WARN]: [OptiFine] Field not found: EntityVillager.careerId
[12:52:51] [main/WARN]: [OptiFine] Field not found: EntityVillager.careerLevel

Crashlog:
https://paste.ee/p/VQRpE

JSON patch for MMC. I think it is ok. https://gist.github.com/ScottoMotto/f5bb22e6ff5691e2465d8720ba648885

Also, I tried the DIscord server first but that place seems very toxic (at least today).

**Comment by FakeMichau** [comment]
Use extracted jar, it doesn't have "preview" in front

**Comment by ScottoMotto** [comment]
Nice. That works. Thank you so much!
