### ISSUE TITLE
Connected glass using outdated textures in 1.14

### ISSUE THREAD

**Issue by TitanicMonarch** [sp614x/optifine#2395]
Connected glass still uses the old texture for glass in 1.14. This does not apply to the programmer art resource
 pack, since the pack uses that texture anyway.

<img width="1280" alt="Screenshot 2019-05-24 at 12 04 20" src="https://user-images.githubusercontent.com/47922690/58323549-367f3080-7e1c-11e9-956d-9585dbda9ceb.png">

**Comment by Regnander** [comment]
#2386

**Comment by Regnander** [comment]
#2386

**Comment by sp614x** [comment]
Fixed in latest preview.
