### ISSUE TITLE
Game Crash on World load in 1.13 with OptiFine 1.13 HD U E4

### ISSUE THREAD

**Issue by schelias** [sp614x/optifine#2396]
Launching the game works just fine, but whenever I try to connect to a server or enter a singleplayer world, my game crashes. Any Help besides "pls Update" would be appreciated, since I play on a Server I can`t change the Version of. Crash Report in the Attachments
[crash-2019-05-24_08.56.45-client.txt](https://github.com/sp614x/optifine/files/3215526/crash-2019-05-24_08.56.45-client.txt)

**Comment by sp614x** [comment]
You can try to disable Render Regions.

```
java.lang.NullPointerException: Unexpected error
	at cue.updateVboRegion(ViewFrustum.java:214)
	at cue.a(ViewFrustum.java:58)
...
	Using VBOs: Yes
	Resource Packs: 
	OptiFine Version: OptiFine_1.13_HD_U_E4
	OptiFine Build: 20181025-102956
	Render Distance Chunks: 23
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Sildurs Vibrant Shaders v1.18 High.zip
	OpenGlVersion: 4.6.0 NVIDIA 419.67
	OpenGlRenderer: GeForce GTX 1070/PCIe/SSE2
```

**Comment by schelias** [comment]
Ty, that did it for me!
