### ISSUE TITLE
1.14 Pre_2 Resource Pack Change Crash

### ISSUE THREAD

**Issue by Gator-Boy11** [sp614x/optifine#2399]
When changing resource packs or shader packs in the preview I will crash around 90% of the time. This seems to happen with any resource pack and shader pack. The game will switch when I boot it back up.
 
The specific resource packs that have issues are Default 32x32 (with the 3D Addon) and Canvas v128 Up and the specific shader pack is  Sildur's Vibrant Shaders v1.17 Medium. I Have also gotten similar issues with Seus Renewed and Kuda-Shaders.

I have edited the crash report because it includes information I am not comfortable sharing like my computer username which is my actual name and my path variable which shows how I use my computer.

I also noticed this appears to be an issue outside of the JVM (see the line "The crash happened outside the Java Virtual Machine in native code.") There are also several errors in the section labeled "Internal Errors".
[crashReport_redacted.log](https://github.com/sp614x/optifine/files/3218775/crashReport_redacted.log)

**Comment by Gator-Boy11** [comment]
I forgot to mention I am running an Intel 8700 with a  NVIDIA GTX 770 based gpu.

**Comment by DataCrusade** [comment]
invalid, you're using a version that's 3 versions out of date

**Comment by sp614x** [comment]
The crash is in the nvidia drivers.
Please test with latest preview.
