### ISSUE TITLE
Spawn chunk don't load when go away

### ISSUE THREAD

**Issue by iPlay4Fun** [sp614x/optifine#240]
Hi, 
Since optifine 1.10.x when we go away from spawn chunk, the chunk stop loading, and it's  unfortunate for farm who need to be on spawn chunk (iron titan for example). 
Can you add on option for turn on/off the load of spawn chunk ? 
Thanks

(Sorry for my bad English but i'm French)

**Comment by sp614x** [comment]
Options -> Video Settings -> Performance -> Smooth World -> OFF

**Comment by iPlay4Fun** [comment]
Thanks, i had seen this option before but didn't know what it was
