### ISSUE TITLE
Camera shakes when using zoom in third person view

### ISSUE THREAD

**Issue by shurik204** [sp614x/optifine#2400]
Camera like shaking when viewing from the third person view and slowly moving mouse. Using OptiFine 1.14 pre5. There is no such bug on OptiFine 1.12.2 and 1.13.2
There is a video demonstration I recorded:
https://youtu.be/sBOwu2_9hSw
P.S: Sorry for background noise idk how to remove it
P.S.S: My hardware in the video description

**Comment by BruceKnowsHow** [comment]
Only your entity model is shaking. You think the camera is shaking in 3rd person because that's the only time you can actually see your player model. Can you check to see if it happens in 1st person when looking at other entities? Such as a pig or something?

**Comment by shurik204** [comment]
Seems this issui is in third person only. Summoned floating pig without AI to check. Looks like other entities in 3rd person shake too.
https://youtu.be/_DtYsT3UA1w

**Comment by sp614x** [comment]
Fast Math -> OFF
FOV Quake Pro with zoom needs very fine angular resolution that Fast Math can't deliver.
