### ISSUE TITLE
Vanilla trees are not transparent with fancy preset

### ISSUE THREAD

**Issue by w7rus** [sp614x/optifine#2401]
#1430 Same issue without an answer how it was resolved. Vanilla leaves are opaque with fancy graphics, while other mods added ones have transparency
As seen on screenshot (on the left is vanilla oak tree, on the right BIOMESOP trees)
![](https://i.imgur.com/tAV6o8p.jpg)

Only happens with optifine installed

Minecraft 1.12.2
Optifine HD E4_pre4 (using that for chunk pregenerator compatibility)

**Comment by sp614x** [comment]
Forge version, which other mods are installed, F3 screenshot?

**Comment by w7rus** [comment]
Forge: 1.12.2-14.23.5.2838
![](https://i.imgur.com/5uptVr8.jpg)
[Modpack List](https://docs.google.com/spreadsheets/d/1gu8rYXCoiQquVeC6UaoCFIFw7bcag5VlXm-8MBlDa-o/edit#gid=0)

**Comment by sp614x** [comment]
Can you reproduce it with a minimum number of mods installed (ideally only OF and one other mod).
It could be a conflict with any of the 228 installed mods.

**Comment by DieselpunkCyborg** [comment]
I still have this issue, anyone ever solve it? I got like 330 mods, Optifine and SEUS shader so it could be anything...

**Comment by w7rus** [comment]
> 
> 
> I still have this issue, anyone ever solve it? I got like 330 mods, Optifine and SEUS shader so it could be anything...

Well, just updated to the latest stable releases of most mods, does not happen anymore.
[https://docs.google.com/spreadsheets/d/1gu8rYXCoiQquVeC6UaoCFIFw7bcag5VlXm-8MBlDa-o/edit?usp=sharing](Modpack spreadsheet) for reference.
