### ISSUE TITLE
[CIT - 1.14 Pre-6] Alternate textures for crossbow broken

### ISSUE THREAD

**Issue by k-wins-it** [sp614x/optifine#2404]
Normal bows work perfect with a bow.properties file containing:

```C#
items=bow
texture=textures/item/bow
texture.bow_pulling_0=textures/item/bow_pulling_0
texture.bow_pulling_1=textures/item/bow_pulling_1
texture.bow_pulling_2=custom_bow_texture
```
So i would expect a similar format to work for crossbows. 

However, crossbows do ***not*** work with a crossbow.properties file containing:
```C#
items=crossbow
texture=textures/item/crossbow_standby
texture.crossbow_pulling_0=textures/item/crossbow_pulling_0
texture.crossbow_pulling_1=textures/item/crossbow_pulling_1
texture.crossbow_pulling_2=textures/item/crossbow_pulling_2
texture.crossbow_firework=textures/item/crossbow_firework
texture.crossbow_arrow=custom_crossbow_texture
```
- The first thing "texture=[...]" works, but the texture won't change to the textures listed as
"texture.[...]=[...]", resulting in all crossbows always having the crossbow_standby texture,
which is undesirable.

Hopefully this is an easy fix!
It will be awesome to have the crossbow texture change based on which arrow is loaded into the bow!

**Comment by FrancescNosas** [comment]
I've encountered the same issue

**Comment by sp614x** [comment]
Fixed, coming in next preview
