### ISSUE TITLE
(1.14 pre 6)Game running extremely slow

### ISSUE THREAD

**Issue by hdgrady8** [sp614x/optifine#2405]
Installed latest version, install went fine and world loaded grand but once in the world the game lagged to the point it was a still image for at least 4 seconds at a time, render distance of about 8 blocks as well, apart from mobs which could be seen.

**Comment by sp614x** [comment]
Is this still relevant with latest preview for 1.14.2?

**Comment by hdgrady8** [comment]
Have been busy so haven't got the chance to check, once I do I'll let you
know.

**Comment by KaiAF** [comment]
I assume this is resolved now.
