### ISSUE TITLE
Third Person Zooming and Cape

### ISSUE THREAD

**Issue by Whitsy** [sp614x/optifine#2407]
Third Person zooming is not smooth and cape when sprinting with speed 2 and possibly just sprinting is a bit glitchy as well

**Comment by landfillbaby** [comment]
#2400 ?

**Comment by Whitsy** [comment]
Third person zoom is not smooth like it normally is and with the cape sprinting makes it a bit glitchy

**Comment by Whitsy** [comment]
Yes this is it sorry for not looking before hand

**Comment by sp614x** [comment]
Fast Math -> OFF should fix it.
