### ISSUE TITLE
Campfire smoke goes through slime blocks

### ISSUE THREAD

**Issue by VincyZed** [sp614x/optifine#2408]
Small bug, but still bugs me. Campfire smoke particles go through slime blocks when they shouldn't.
- Optifine 1.14.2 HD U F1 pre6
- This does not happen in vanilla.
- Toggling smart animations does not change anything.
- This might or might not happen with other blocks than Slime Blocks, I am not sure.

**Comment by sp614x** [comment]
Looks like the smoke particles are going through any solid block as long as it is only one.
A second block on top stops the particles.

**Comment by sp614x** [comment]
This also happens in vanilla, but less frequently:

![image](https://user-images.githubusercontent.com/16635441/59362178-4f03ac00-8d33-11e9-82bc-faa65bb617f6.png)

**Comment by sp614x** [comment]
Fixed, coming in next preview

**Comment by VincyZed** [comment]
Awesome, thanks!
