### ISSUE TITLE
Custom Elytra with custom capes?

### ISSUE THREAD

**Issue by williambl** [sp614x/optifine#241]
Hi, I bought a cape, and it works perfectly. However, [Minecon capes have their own elytra textures](https://pbs.twimg.com/media/Cac8EG7WAAAhAu3.jpg:large). Optifine capes do not. Is this intended? I would love to fly around using my custom cape as an elytra!

**Comment by XxPoNaGeXx** [comment]
please add this!

**Comment by MyTheValentinus** [comment]
Up ?

**Comment by Probdutch** [comment]
Please implement this :)

**Comment by theepicdeath100** [comment]
Bump!

**Comment by lieuwe-berg** [comment]
👍 +1

**Comment by Image64Labs** [comment]
that would be awesome to have

**Comment by sp614x** [comment]
Custom elytra was added.
