### ISSUE TITLE
VBO toggle on 1.14(.2)

### ISSUE THREAD

**Issue by Madis0** [sp614x/optifine#2412]
Using OptiFine 1.14.2 HD U F1 pre6, I see the toggle "Use VBOs" in settings.

Per #2021 I started to wonder if it actually does anything at this point, in other words: is it an oversight/leftover or did you actually intend to bring back the option?

If it is the latter, the phrase should be added to Optifine's language file as it no longer exists in vanilla.

**Comment by sp614x** [comment]
There is no new render engine in 1.14.
The non-VBOs code is still in the game, only the option is hidden.
The VBOs options should work like in 1.13.2.
