### ISSUE TITLE
Random entities don't work for paintings

### ISSUE THREAD

**Issue by KKMNNOIR** [sp614x/optifine#2413]
I created `optifine/random/painting/kebab2`, `kebab3` and `kebab4`. They don't work.
I added `kebab.properties` and other textures, they didn't work.

Similar to #2373, but this is not fixed in 1.14.2 HD U F1 pre6.

**Comment by sp614x** [comment]
The paintings in 1.14 are using a dynamic texture atlas, similar to block/item textures.
Random entities don't support a texture atlas yet.

**Comment by Paragraph64** [comment]
someone please fix this :(

**Comment by DotFlv** [comment]
I hope the problem with painting's random entity will be solved soon : (

**Comment by giammod** [comment]
Annual reminder we need this.  I spent hours yesterday updating one of my old art add-on packs to 1.19 only to eventually realize Random paintings aren't in the current version of optifine ;'(

**Comment by sp614x** [comment]
Fixed, coming in next 1.19 preview.

**Comment by LJP-92** [comment]
Random paintings are no longer working again.  Worked perfectly in 1.19.2 but not in 1.19.4 pre1
