### ISSUE TITLE
1.14.2 pre 6 Crash on startup MultiMc

### ISSUE THREAD

**Issue by Failfail2603** [sp614x/optifine#2414]
So I installed the new Optifine version : preview_OptiFine_1.14.2_HD_U_F1_pre6.jar in the newest version of MultiMC the JSON File for the libraries is correct and Optifine loads up but then I get the following crash log
[crashlog01.txt](https://github.com/sp614x/optifine/files/3238149/crashlog01.txt)

**Comment by Failfail2603** [comment]
Here again as link : https://paste.ee/p/HX3fO

**Comment by akoimeexx** [comment]
Also experiencing this issue in MultiMC on Linux. Appears similar to other reports, one mentions using an extracted version? to work around this; but with no context on what that means...

**Comment by Hellzbellz123** [comment]
yeah your supposed to use the extract button in the optifine installer
but it seems that this doesnt work because you need to have minecraft 1.14.2 installed

**Comment by Failfail2603** [comment]
Yes the problem is that the installer cant detect the minecraft instance on MultiMC. I got a workaround : just get rid of the preview_ in the json and rename the optifine jar accordingly.

**Comment by sp614x** [comment]
The OptiFine initialization is missing.
It looks like the "com.mojang.blaze3d.*" patches are not being applied.

**Comment by Failfail2603** [comment]
Because theres a simple workaround and apparently its not an optifine related issue I closed this thread

**Comment by matcool** [comment]
@Failfail2603 What is your `optifine.OptiFine.json`? I tried removing the preview_ and it still didnt work

**Comment by Failfail2603** [comment]
First you need to extract Optifine so you need the normal Minecraft launcher. You put the extracted file in the libaries folder and rename the file to something like this -> OptiFine_1.14.2_HD_U_F1_pre9.jar The biggest issue here is within the json (file follows) the line "name": "optifine:OptiFine:1.14.2_HD_U_F1_pre9"
its not "_" between Optifine and the version its a ":". The MMC-filename is with "_" and .jar at the end.
[auto_generated.txt](https://github.com/sp614x/optifine/files/3269392/auto_generated.txt)
