### ISSUE TITLE
OptiFine 1.14.2 HD U F1 pre6 - pre10 Resourcepack Reload Crash

### ISSUE THREAD

**Issue by CyberGen49** [sp614x/optifine#2415]
I installed OptiFine 1.14.2 HD U F1 pre6, and when reloading resourcepacks with F3 + T, the game crashes with [this error log](https://pastebin.com/eKR8snX5). This doesn't happen in Vanilla.

**Comment by grillo78** [comment]
I have the same issue with OptiFine 1.14 HD U F1 pre6

**Comment by CyberGen49** [comment]
The issue persists in OptiFine 1.14.2 HD U F1 pre7.
