### ISSUE TITLE
BetterPortals compatibility

### ISSUE THREAD

**Issue by Johni0702** [sp614x/optifine#2419]
[BetterPortals](https://minecraft.curseforge.com/projects/betterportals) is a mod which allows for see-through portals which can be used without any loading screen.
(Currently 1.12.2 but I'd imagine most issues will also exist on 1.14.2 once BP has been ported.)

## How it works
To accomplish this, it spawns fake players on the server, tunnels their packets to the client and then maintains multiple independent worlds there by swapping all the relevant state whenever a packet needs to be handled, the world needs to be ticked or a frame needs to be drawn.
That last part is where we unsurprisingly run into issues with OF.

For drawing a normal frame BP first determines all portals visible and the relative positions of the camera entities in all visible worlds and then sequentially renders these worlds into framebuffers which are in turn are used when it comes to rendering the actual portal entity.

## And then stuff breaks
Surprisingly (at least for me) it's not actually as bad as it sounds. Aside from a few small initial issues on BP's side, it mostly just works out of the box, including Render Regions and Shaders (with caveats).

### Switching dimensions at 60fps
This is probably the most severe and most obvious issue of them all.
Since OF allows for different shaders in different dimensions, whenever the dimension changes, the current shader pack is re-loaded. Normally this only happens when the player actually changes dimension so it's no big issue but with BP this happens twice per frame which contains a portal.

Not sure how best to approach this, so I'll start simple: Would it even be feasible for multiple shader states to co-exist (not be active at the same time but just to coexist and be able to be swapped out depending on the current world)?

### Toggling Render Regions
Toggling render regions while near a portal causes the game to crash in the next frame.
Presumably there's some setup/tear down code which only gets applied to one world and not the other (ofc OF cannot know that there are multiple worlds).
I can probably detect that the setting has changed by polling it via reflection before very frame but is there some method I can call to run the setup code for other worlds? Is it maybe even just as simple as reloading all chunks?

### What's this Fast Render thing doing?
I have no idea what it actually does. Only thing I know is that BP's main hook (it hijacks the call from `updateCameraAndRender` to `renderWorld`) is no longer called (I think) and therefore the portal framebuffers are no longer updated.

**Comment by Cadiboo** [comment]
[Related Issue](https://www.minecraftforge.net/forum/topic/70592-113how-to-use-mixin-for-forge-modding/)

**Comment by sp614x** [comment]
The shaders are not built in a way that would allow the shaders for two dimensions to be loaded at once. This would require a total redesign of the shaders, removing all static variables and attaching a set of shaders to each world. I can't see this happening in the near future.

Having two worlds coexist and alternate each frame is not a native MC concept, there could be other parts of OptiFine where it may be problematic. The world change is expected to be a major transition.

On the other side, not all shader packs have separate shaders per dimension so with them there would be no shader switch when changing dimensions and the performance should be ok.

No idea what the problem with Render Regions may be.

Fast render (among other things) disables the MC framebuffer so the rendering is direct to screen. This can help when using an integrated GPU with HD screen.

**Comment by SylveonBottle** [comment]
Seems like this bug isn't present in [Immersive Portals](https://www.curseforge.com/minecraft/mc-mods/immersive-portals-mod)?

![Example Image](https://i.ibb.co/GTCwznj/2019-08-29-17-31-54.png)

**Comment by Johni0702** [comment]
@SylveonBottle 
Immersive Portals heavily modifies Optifine's shaders to make that work.


> The shaders are not built in a way that would allow the shaders for two dimensions to be loaded at once. This would require a total redesign of the shaders, removing all static variables and attaching a set of shaders to each world. I can't see this happening in the near future.

It basically does this but at runtime (and a little different).

I'm not prepared to invest the same effort in figuring how exactly OF's shaders work (cause no source code is provided) and maintaining / fixing bugs in that workaround (since again, no source code is provided and fixing issues with OF, which is effectively a big black box, is no fun).

Especially because that'd be far more difficult than just fixing it in OF itself (which could be a matter of hours instead of days). But given OF's license, sp614x is the only one that can do that.
