### ISSUE TITLE
Crash when alt+tab is pressed in 1.10

### ISSUE THREAD

**Issue by TomeWyrm** [sp614x/optifine#242]
The following links are the crashlog and the hs_err log

http://pastebin.com/cWDPbCea
http://pastebin.com/XZ0X5KMx

I am using Forge 1.10.2-12.18.1.2061 and OptiFine 1.10.2_HD_U_C2. I'm using the most up to date graphics drivers for my video card. I'm using 64-bit Java 1.8.0_101-b13.

Whenever I alt+tab after the game has reached the main menu with optifine installed, the game crashes to the launcher. I'd try with forge 2002 instead of 2061 except that the mods I am using require a much later version than 2002.

I tested without optifine, and it does not crash.

I can provide more information if requested.

**Comment by sp614x** [comment]
> # Problematic frame:
> # C  [ig4icd64.dll+0x84bc5a]
The Intel graphics driver has crashed.
Using the default fullscreen resolution may help.

**Comment by sp614x** [comment]
Driver problem
