### ISSUE TITLE
Chunk Rending Error 1.14.2 Preview

### ISSUE THREAD

**Issue by frozenMC** [sp614x/optifine#2420]
https://pastebin.com/FV1bDTF4

Normal Installation of Optifine. SP works fine, realm works fine.

Entered server, immediately crashes to desktop. Not sure what can be the cause.

Possible Causes:
-Server request for a RP Download (?)

**Comment by frozenMC** [comment]
Issue resolved in OptiFine_1.14.2_HD_U_F1_pre7.jar  

Thank you.

**Comment by frozenMC** [comment]
https://hastebin.com/anorakiquw.php

Same issue popped up; worked fine previously.

**Comment by sp614x** [comment]
The hastebin link is empty.

**Comment by frozenMC** [comment]
https://pastebin.com/3xBimdNj

Still seeing the same problem as earlier. I apologize for the missing hastebin earlier.

**Comment by frozenMC** [comment]
https://pastebin.com/DX8VhynG

Pre10 still seeing the same issue with the same server. SP and Realms works fine.

**Comment by frozenMC** [comment]
Uhhh...

with Pre12 I am now seeing a different error -- rendering items. I have no clue whats going on with this one.

https://pastebin.com/DuNEWFXV

**Comment by Jiingy** [comment]
Closing as provided issue varries from crash-to-crash, leaving the issue needing to be fixed very vague.
