### ISSUE TITLE
1.14.2 Render Region causes invisible blocks

### ISSUE THREAD

**Issue by ReeceBar** [sp614x/optifine#2421]
Basically with Render Region on most blocks, atleast above ground, are invisible but mobs are fine. Just turned if off fixed this issue, but I used to have it on before, 1.14.2 must be bugged. Here's a screenshot 
![2019-05-31_22 54 44](https://user-images.githubusercontent.com/42558495/58743002-e98cf280-83f7-11e9-8230-b8f2fb02ba76.png)

And here's instant change/fix when I turned it off

![2019-05-31_22 55 37](https://user-images.githubusercontent.com/42558495/58743006-f3165a80-83f7-11e9-9ea2-917d9a5161f1.png)

**Comment by ReeceBar** [comment]
If I need to give more info let me know what else I should give

**Comment by ReeceBar** [comment]
Btw this setting works on 1.12.2 and 1.8.9 haven't tested any other version, but I bet it's fine on any other except 1.14.2

**Comment by sp614x** [comment]
Testing F1_pre10 for 1.14.2, render regions is working work correctly.
Can you post an F3 screenshot?

**Comment by KaiAF** [comment]
no response from the author.
