### ISSUE TITLE
1.14.2 pre 6 Sky box horizon

### ISSUE THREAD

**Issue by JimStoneCraft** [sp614x/optifine#2424]
The sky box horizon does not display correctly on 1.14.2 pre6.

Here are some screen shots comparing 1.13.2 - 1.14.2, both games have the same OptiFine settings.

![1 13 2](https://user-images.githubusercontent.com/42512910/58750901-9f575000-848f-11e9-8192-ebaa48a0d456.png)
![1 14 2](https://user-images.githubusercontent.com/42512910/58750902-9fefe680-848f-11e9-88f8-ad7f5deaa8aa.png)

**Comment by JimStoneCraft** [comment]
I stands out more in my resource pack (John Smith Legacy).

![1 13 2 John Smith Legacy](https://user-images.githubusercontent.com/42512910/58750940-24db0000-8490-11e9-815e-57835414d505.png)
![1 14 2 John Smith Legacy](https://user-images.githubusercontent.com/42512910/58750941-24db0000-8490-11e9-8c5c-e1b53f40100b.png)

**Comment by JimStoneCraft** [comment]
Closed by mistake.

**Comment by sp614x** [comment]
Looks like the sky fog is missing.

**Comment by sp614x** [comment]
OptiFine 1.14.2_HD_U_F1_pre8
 - fixed sky fog
