### ISSUE TITLE
1.14.2 pre7 Sliders broken in shaders options

### ISSUE THREAD

**Issue by 6ix7even** [sp614x/optifine#2425]
the sliders in shaders option are really broken with the last version for 1.14.2 : the F1_pre7
![2019-06-01_18 54 43](https://user-images.githubusercontent.com/44172841/58751563-73909600-84a0-11e9-9bd1-4562265eaec1.png)

**Comment by sp614x** [comment]
Fixed, coming in F1_pre7.
