### ISSUE TITLE
[1.14 Pre 6 - 1.14-2 Pre 7] Mojang splash screen doesn't replace white background

### ISSUE THREAD

**Issue by murrty** [sp614x/optifine#2427]
When replacing the Mojang splash screen, I assume optifine filled the remaining background based on the colors of the edges on the custom logo. However, 1.14 pre-releases, it does not fill the background and instead leaves the remaining white background intact, which can cause a sharp contrast. This is present on the latest pre-release of Optifine.

1.14 Pre 6
![2019-06-01_17-15-59-798-_javaw](https://user-images.githubusercontent.com/35756280/58754251-d0388480-8491-11e9-9ced-724ba694cfa6.png)
1.14.2 Pre 7
![2019-06-01_17-18-18-096-_javaw](https://user-images.githubusercontent.com/35756280/58754260-e8a89f00-8491-11e9-93b3-30ab8c8a0560.png)

(The logo size differences were a resource pack issue)

**Comment by sp614x** [comment]
The mojang logo in 1.14 have a transparent background and it is overlayed on a white filled background

**Comment by murrty** [comment]
I see, I assumed that it was also changed using optifine since optifine was the only way you could change the mojang logo, so I thought the white background was a bug.

I've noticed you have released it in the latest pre-release, so I'll close this issue.
