### ISSUE TITLE
Optifine white screen  issue

### ISSUE THREAD

**Issue by zacharyhenry** [sp614x/optifine#2431]
Optifine  v 1.12.2_HD_U_E3
14.23.5.2838

I turned off fast render  and now it just shows white screen but minecraft still works

**Comment by sp614x** [comment]
Other mods installed?

**Comment by zacharyhenry** [comment]
Yes

**Comment by zacharyhenry** [comment]
Nevermind I fixed it

**Comment by Regnander** [comment]
How did you fix it? There might be other players who are having the same problem, so any info is helpful.

**Comment by zacharyhenry** [comment]
I just went to performance  thru optifine and turned everything off and
turned everything back on except fast render and it works

**Comment by zacharyhenry** [comment]
I turned everything on performance option off on optifine and then turned everything on except fast render which affects  journeymap  fullscreen with immersive railroading
