### ISSUE TITLE
[SUGGESTION] Website Improvement/Overhaul

### ISSUE THREAD

**Issue by techied** [sp614x/optifine#2434]
Obviously, the mod comes first, but

Considering that the OptiFine website looks very old and outdated, it may appear to some users that it is an illegitimate website to download OptiFine from. The new site would ideally use something like Twitter Bootstrap just to make a simple site that looks nice, and it could even run off GitHub Pages. 

Some screenshots and images on the front page would also help liven it up.

**Comment by techied** [comment]
- [ ] 

1. 

-

**Comment by KaiAF** [comment]
The website ended up getting updated 👍
