### ISSUE TITLE
[1.13-1.14.2 pre8] Incredibly strange crash involving CTM and "Tesselating block model"

### ISSUE THREAD

**Issue by realjackasterisk** [sp614x/optifine#2436]
Never seen anything like this. I was testing a little idea I had using some CTM with cobblestone and stone bricks. I made sure I was following [the documentation](https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/ctm.properties) precisely, and yet somehow, I managed to create CTM that perfectly crashes the game in a specific way every single time without fail. This works on both 1.13 and 1.14, not sure if other versions are affected.

Crash Log (1.14.2, F1 pre8): https://pastebin.com/0f5tR3n0
Crash Log (1.13.2, E7): https://pastebin.com/1SY8hPnW
Resource Pack: [broken_game.zip](https://github.com/sp614x/optifine/files/3250547/broken_game.zip)

To make the crash, simply place down some cobblestone next to stone bricks. The important thing to note is that this only works on the TOP SIDE of the blocks.
![image](https://user-images.githubusercontent.com/31686191/58854139-4800dd80-8651-11e9-813b-5f91dc2bf1cc.png)

Once the cobblestone and stone bricks connect on the top, the crash will occur, but only if the cobblestone has been placed down last. If you attempt to build a 2 block high stone brick tower, then place cobblestone, THEN break the stone bricks on top to make the connection, nothing will happen. Other than that, the game will either crash immediately or freeze indefinitely.

On 1.14.2, trying to load the world again with the resource pack still loaded will yield the same results before you can even see anything. At this point, you MUST disable the resource pack before you can open the world again.

However, on 1.13, you CAN load the world, but attempting to build the same structure will still lead to the same problem.

**Comment by sp614x** [comment]
Fixed, coming in next preview.
