### ISSUE TITLE
I Still Want The Cape

### ISSUE THREAD

**Issue by eggnog1219** [sp614x/optifine#2441]
Ok, so almost 1 year ago I have posted an issue about my Optifine cape donation issue. And until today, I still can't get over it. As you said in the post, "Only paymentwall can solve this problem
", I have sent multiple emails to PaymentWall for the past 6 months and they have not replied once (Photo below shows one of the emails i sent to them...). Seeing the reviews from the PaymentWall website, they weren't good. All the reviews were talking about the company scamming them (Photo shows it below..); and they scammed ME! I know what your thinking. Why can't I just get over this, it's only a cape and 10 dollars. For me, I rarely buy ingame items so this was pretty rare. And I myself payed using my very own 10 dollar. PaymentWall is a hell of a company and I don't even know why you chose it to be in your website. I still feel sad that I got scammed from this. I feel left out without a cape (which sounds stupid). I hope you understand what i'm saying here. And  I hope I get a cape considering that I technically payed 10 dollars for it but it didn't go thru (they never gave back the money btw). Thanks for reading.

                                                                                                        -eggnog1219 (my ING name) 

![Screenshot (357) copy](https://user-images.githubusercontent.com/40073076/58885126-39c7c580-8714-11e9-8910-627987014740.png)
![Screenshot (358)](https://user-images.githubusercontent.com/40073076/58885133-3df3e300-8714-11e9-91d5-676365a3ae00.png)

**Comment by eggnog1219** [comment]
Oh yeah btw. I tried paying w/ my second email & they also declined that... So now I got scammed twice -,-

**Comment by DataCrusade** [comment]
if it didn't go through and got declined, you're either using the wrong wording or you're lying, lol. it sounds like you're more just trying to get a free cape more than anything. there is nothing sp614x can do about this if true and you're not gonna get your back rectangle for your block character

**Comment by eggnog1219** [comment]
I got a reciept

**Comment by eggnog1219** [comment]
As you can see in the email, there is a little photo showing that the card was declined. Whenever my dad uses his card a message pops up indicating that he bought something using it. And for this case, it did. The only concern is that there is no message saying that the payment was returned to the account holder.

**Comment by Thepenguin9** [comment]
If the card was declined, it CANNOT take money. You are not out of any money so donate again.

Source: Worked with payment solutions

**Comment by eggnog1219** [comment]
I said in an earlier comment that I tried again with my second email. No luck. Now both my emails are locked out and $20 gone. It said that to proceed this payment, it needs the account holders drivers license and photo ID. I think that’s all a scam and bs considering that every payment company doesn’t do that.

**Comment by Regnander** [comment]
When I donated for the cape I used Paysafecard since I didn't want to use my credit card, which worked great for me.

**Comment by eggnog1219** [comment]
Sadly I don't have that option because I don't live in the US (if that's how it works).

**Comment by mindforger** [comment]
>It said that to proceed this payment, it needs the account holders drivers license and photo ID. I think that’s all a scam and bs considering that every payment company doesn’t do that.

many companys do that, especially those who sell gamekeys do require this kind of confirmation ... but most of the time you can write to the support and ask for alternative validation methodes

**Comment by eggnog1219** [comment]
Well even tho I sent the requirements they still wouldn't respond because of the bad customer service. Its been months since i've emailed them about this. No response.

**Comment by Thepenguin9** [comment]
Still, it's not an issue for optifine so please willingly close this issue

**Comment by eggnog1219** [comment]
But he has the option to do changes in his website so maybe he can fix this problem.

**Comment by Thepenguin9** [comment]
No, he cannot. This is for issues with the **Optifine Mod** not the website. Close this issue, please

**Comment by eggnog1219** [comment]
How is the issue from the Optifine Mod and not the website. Paymentwall is clearly in the website and not the mod. What are you talking about.

**Comment by DataCrusade** [comment]
> How is the issue from the Optifine Mod and not the website. Paymentwall is clearly in the website and not the mod. What are you talking about.

They said the github, which this issue is on, is for issues with the OPTIFINE MOD, not the OPTIFINE WEBSITE.

**Comment by Thepenguin9** [comment]
> How is the issue from the Optifine Mod and not the website. Paymentwall is clearly in the website and not the mod. What are you talking about.

This (being the github) is for issues with the Optifine Mod (aka what you use in game), not the website (aka what you use to get the mod)

**Comment by eggnog1219** [comment]
I've seen this thread asking for a fix on the website. https://github.com/sp614x/optifine/issues/764
I don't think this website is only about the mod.

**Comment by eggnog1219** [comment]
As you can see in the comments of the thread that he made changes to the website.

**Comment by Thepenguin9** [comment]
You're missing the point

Instead of closing this issue and just, leaving it be, you decided instead to scour the issues page for an example of a website issue in this tracker

You're fighting a battle that's already lost

**Comment by sp614x** [comment]
If the card was declined then the payment has not been processed at all. 
It looks like the payment has triggered some of their security checks and they want to make sure that you are really the card owner.
Only Paymentwall can decide which cards they work with and which additional checks may be needed.
