### ISSUE TITLE
MC+Optifne won't launch with JRE10+ but, normal MC will.

### ISSUE THREAD

**Issue by muHashh** [sp614x/optifine#2442]
Not sure what's up with the latest preview of optifine (1.14.2 HD U F1 pre9). Tested with OpenJDK and Oracle JDK (versions 11 and 12). Both can run vanilla minecraft perfectly. However, the launcher crashes when trying to run anything other than JRE8 (From OpenJDK or Oracle) when using optifine. Logs don't show any error to do with this either. Is this a known limitation of optifine?

**Comment by chungy** [comment]
Thanks. Came here trying to ask about launching it on Linux, but it seems setting JAVA_HOME to openjdk-8 allows it to work.

**Comment by i0xHeX** [comment]
Same issue running on JDK 11 (Oracle)
Output log shows next stack trace:
```
Exception in thread "main" java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
 at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
 at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by landfillbaby** [comment]
This is actually due to Mojang/LegacyLauncher#20 (Mojang's launchwrapper library), which in turn is due to https://community.oracle.com/message/14205705 (a backwards compatibility issue with Java 9+), so I'd say it's really out of sp614x's hands

**Comment by i0xHeX** [comment]
> This is actually due to [Mojang/LegacyLauncher#20](https://github.com/Mojang/LegacyLauncher/issues/20) (Mojang's launchwrapper library), which in turn is due to [a backwards compatibility issue with Java 9+ itself](https://community.oracle.com/message/14205705), so I'd say it's really out of sp614x's hands, and due to this and various other issues, everyone should just continue using Java 8 for Minecraft. Java 8 is supported until next next year's December, so hopefully Mojang will update to 11 by then.

But wait, pre6 worked good in Java 11

**Comment by muHashh** [comment]
> This is actually due to [Mojang/LegacyLauncher#20](https://github.com/Mojang/LegacyLauncher/issues/20) (Mojang's launchwrapper library), which in turn is due to [a backwards compatibility issue with Java 9+ itself](https://community.oracle.com/message/14205705), so I'd say it's really out of sp614x's hands, and due to this and various other issues, everyone should just continue using Java 8 for Minecraft. Java 8 is supported until March 31st 2022, so hopefully Mojang will update to 11 by then.

Normal MC runs fine with 9+. It was working with an older version of optifine too. So it's an issue with an update.

**Comment by landfillbaby** [comment]
https://github.com/sp614x/optifine/issues/1739#issuecomment-417884419 for the updated launchwrapper, should close the issue

**Comment by i0xHeX** [comment]
May confirm the fix above is working. But it should be implemented by default, not patched by user every time.

**Comment by JpegXguy** [comment]
Yeah just patch the json with optifine installation, come on @sp614x !

**Comment by sp614x** [comment]
I want to check how exactly the fix works and to add some other fixes that are needed for1.14 before making it official.

**Comment by Justsnoopy30** [comment]
I used the fix from https://github.com/sp614x/optifine/files/2342731/NewerJavaCompatibility.zip but I get this error in the Minecraft logs and it crashes right before the loading screen completes:
`20:36:39
launcher
main
info

 # # A fatal error has been detected by the Java Runtime Environment: # # EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ff9d2bb44d2, pid=104200, tid=40944 # # JRE version: OpenJDK Runtime Environment (12.0.1+12) (build 12.0.1+12) # Java VM: OpenJDK 64-Bit Server VM (12.0.1+12, mixed mode, sharing, tiered, compressed oops, shenandoah gc, windows-amd64) # Problematic frame: # V [jvm.dll+0x5144d2] # # No core dump will be written. Minidumps are not enabled by default on client versions of Windows # # An error report file with more information is saved as: # C:\Users\EV Local\AppData\Roaming\.minecraft\hs_err_pid104200.log [thread 30604 also had an error] # # Compiler replay data is saved as: # C:\Users\EV Local\AppData\Roaming\.minecraft\replay_pid104200.log # # If you would like to submit a bug report, please visit: # https://github.com/AdoptOpenJDK/openjdk-build/issues # AL lib: (EE) alc_cleanup: 1 device not closed
20:36:39
monitor
Process Monitor
fatal
Process crashed with exit code 1`

**Comment by i0xHeX** [comment]
> I used the fix from https://github.com/sp614x/optifine/files/2342731/NewerJavaCompatibility.zip but I get this error in the Minecraft logs and it crashes right before the loading screen completes:
> ...

That's not an Optifine issue. This is a OpenJDK 12 bug with Shenandoah GC. You better stay on Oracle's JDK 11 (LTS) or remove -XX:+UseShenandoahGC from startup arguments

**Comment by sp614x** [comment]
OptiFine 1.14.3_HD_U_F1
 - fixed compatibility with Java 9+
