### ISSUE TITLE
Crashes when custom font is toggled

### ISSUE THREAD

**Issue by b-gong** [sp614x/optifine#2443]

**Comment by Regnander** [comment]
I'm guessing that you are using one of the prereleases of 1.14.2, but which one of them?

**Comment by b-gong** [comment]
OptiFine 1.14.2 HD U F1 pre9

Sorry if I duplicated a report

**Comment by Nathan22211** [comment]
if it's a negative font it might be due to an Intel APU. had that issue with a datapack

**Comment by sp614x** [comment]
Fixed, coming in next preview.
