### ISSUE TITLE
Backport cape editor button

### ISSUE THREAD

**Issue by asbyth** [sp614x/optifine#2444]
was wondering if the cape editor button would ever be backported to versions that dont have it.

if not, would it be possible to give permission to make a mod that does it? kind of tired of having to open a new version just to change my cape, i'd do whatever you ask to backport it with your permission
thanks

**Comment by sp614x** [comment]
It would be backported.

**Comment by sp614x** [comment]
Backported to 1.12.2.

**Comment by asbyth** [comment]
seeing as this is backported to supported versions, closing
