### ISSUE TITLE
Crashes when I change ressources packs

### ISSUE THREAD

**Issue by Topbleyzer** [sp614x/optifine#2445]
`Hey I've find a crash bug on` **OptiFine 1.14.2 HD U F1 pre9 / Windows 10 pro 64bit / gtx 1060 3go / i5 8400**
[](https://youtu.be/UbAOuqL2CTQ)

https://pastebin.com/xeBZSmLG

When I change my pack, but finaly don't change nothing, the game often crash

**Comment by sp614x** [comment]
Crash inside nvidia driver. 
It is not clear what may be the cause.
