### ISSUE TITLE
Connected Textures wont disable 1.14.2

### ISSUE THREAD

**Issue by LtRedRooster** [sp614x/optifine#2446]
I didn't know what connected textures were, so I decided to enable it. I decided I didn't like it, so I turn it off, but the grass textures are still connected. I tried restarting Minecraft, uninstalling and reinstalling Optifine, restarting my computer still, the grass textures are connected.

now I have to choose between 16x AA and not connected textures :(
![bug p1](https://user-images.githubusercontent.com/51420795/58986719-03d62000-87ac-11e9-81c8-12d755e51d7b.jpg)
![Bug p2](https://user-images.githubusercontent.com/51420795/58986730-08023d80-87ac-11e9-976d-945a8453fc70.png)

**Comment by xerotrinity** [comment]
The connected grass option is found as "Better Grass" under the Quality settings.

**Comment by LtRedRooster** [comment]
@xerotrinity This is the first time I've downloaded Optifine (I got java edition a week ago) thanks for the tip!
