### ISSUE TITLE
[Suggestion] Add entity render optimizations

### ISSUE THREAD

**Issue by i0xHeX** [sp614x/optifine#2448]
One of the big issues running minecraft on low PCs are entities render. I suggest following things:
- Configurable entity distance render, so we don't render entities if they are too far.
- Ability to make rendering more lightweight, for example changing number of details (yes, that will make mobs look worse)

**Comment by sp614x** [comment]
Entities are usually not the problem as there are not many of them visible on the screen at the same time.
Usually the problems for slow PCs are: 
- integrated GPU + HD screen = lot of pixels to update (use lower resolution)
- animated textures - need upload bandwidth (smart animations, disable animations)
- render distance (descrease)
- world simulation - needs CPU resources
