### ISSUE TITLE
Curved Stairs Create See-Through Texture

### ISSUE THREAD

**Issue by mandm635** [sp614x/optifine#245]
Optifine 1.10.2 HD U C3 (Using Forge)
Windows 10
Java 8

When placing a curved stair next to a normal block, the corner piece becomes see-through
![2016-08-25_15 40 20](https://cloud.githubusercontent.com/assets/13128898/17988371/b5f62736-6ada-11e6-896b-b1a5c03a9c63.png)
.

**Comment by sp614x** [comment]
This is a Forge bug.
It also happens without OptiFine.

**Comment by sp614x** [comment]
The bug is probably introduced in Forge #2047 or #2049.
