### ISSUE TITLE
1.14.2 Crash OptiFine and Fabric

### ISSUE THREAD

**Issue by JimStoneCraft** [sp614x/optifine#2450]
Game plays fine with OptiFine only and also plays fine with Fabric (with or without mods loaded).

However with OptiFine and Fabric I get a crash (Batching chunks).

OptiFine 1.14.2 HD U F1 pre9

Fabric
Game/Mappings version 1.14.2+build.7
Loader version 0.4.8+build.154
[1.14.2] Fabric API 0.3.0 build 179
VoxelMap-1.9.5_for_1.14(.2).jar

The game loads and displays for second and then crashes.

Is this OptiFine or Fabric causing the crash as I'm not sure on the issue in the crash report.
[crash-2019-06-07_06.07.37-client.txt](https://github.com/sp614x/optifine/files/3264484/crash-2019-06-07_06.07.37-client.txt)

**Comment by mikroskeem** [comment]
OptiFine is not compatible with Fabric sadly. You can try OptiFabric, but according to my testing, all blocks (except liquids) were invisible with 1.14.2 pre9 OptiFine and said compatibility mod is not maintained anymore.

It's up to OptiFine developers to add support for Fabric I guess.

**Comment by sp614x** [comment]
There are Fabric settings that make it compatible with OptiFine.
According to another user comment:
![image](https://user-images.githubusercontent.com/16635441/59127982-409b4600-8969-11e9-8a79-f55bd985d569.png)

**Comment by sp614x** [comment]
OptiFine can't fix the Fabric compatibility because Fabric is actively installing hooks and changing the rendering pipeline. This is not something that OptiFine can influence.

**Comment by JimStoneCraft** [comment]
Yep I found the same conclusion, the crash-report says):-

java.lang.ClassCastException: net.optifine.override.ChunkCacheOF cannot be cast to net.fabricmc.indigo.renderer.accessor.AccessChunkRendererRegion
	at net.minecraft.class_851.redirect$hookChunkBuildTesselate$zbc000(class_851.java:1108)
	at net.minecraft.class_851.method_3652(class_851.java:380)
	at net.minecraft.class_845.method_3615(class_845.java:80)
	at net.minecraft.class_845.run(class_845.java:39)
	at java.lang.Thread.run(Unknown Source)

So with some searching for the word indigo in the OptiFine Discord I found that you can edit the Fabric properties file.

If you edit the Fabric indigo-renderer.properties file (created after running Minecraft with Fabric at least once) and change the always-tesselate-blocks from auto to false, Minecraft no longer crashes.

Not sure what this does in Fabric but OptiFine and VoxelMap still work so I'm good now.

.minecraft\config\fabric\indigo-renderer.properties

change:-

always-tesselate-blocks=Auto

to:-

always-tesselate-blocks=false

**Comment by JimStoneCraft** [comment]
![2019-06-07_20 52 21](https://user-images.githubusercontent.com/42512910/59130021-362b7d00-8966-11e9-8ca5-94c41665b2bb.png)
