### ISSUE TITLE
Sprint,shift does not slow

### ISSUE THREAD

**Issue by Misio12320** [sp614x/optifine#2455]
Hello. I have a bug when eating and sprinting player does not slow. While eating and shifting this same player's movement speed isn't slowed...
Version:  OptiFine 1.14.2 HD U F1 pre9.

**Comment by sp614x** [comment]
Tested F1_pre10 for 1.14.2.
When sprinting and eating the player slows down.
You may have disabled "Dynamic FOV" so the slow down is not noticeable.

**Comment by Misio12320** [comment]
Installed the new one. I have turned it on. And... STILL this same. https://imgur.com/36fGtGa
2. Isn't the FOV bugged? When moving head from near block, the 'block' are moving to me closer
