### ISSUE TITLE
[1.14.x] Not compatible with Forge beta

### ISSUE THREAD

**Issue by Cadiboo** [sp614x/optifine#2457]
OptiFine isn't compatible with Forge 1.14.2 beta (Tested on 26.0.5 with OptiFine_1.14.2_HD_U_F1_pre9).
This is obviously known, I thought I'd just put it here to make it easier to track.

**Comment by axemwa** [comment]
It will be good when 1.13.2 will be compatible as well, pretty keen.

**Comment by sp614x** [comment]
Forge compatibility added in F4_pre1 for 1.14.4.
The fix will be backported to 1.13.x.
