### ISSUE TITLE
Optifine 1.14.2 and 1.13.2 Crashes On Linux Mint

### ISSUE THREAD

**Issue by brktz** [sp614x/optifine#2458]
The installation is successful, but when I'm trying to play it from the launcher it crashes.

**Comment by Brottweiler** [comment]
What's the crash message? Also run `java --version` and tell us what java version you're using.

**Comment by brktz** [comment]
@Brottweiler crash message - https://imgur.com/zFcNNbu

java version - openjdk 11.0.3 2019-04-16
OpenJDK Runtime Environment (build 11.0.3+7-Ubuntu-1ubuntu218.04.1)
OpenJDK 64-Bit Server VM (build 11.0.3+7-Ubuntu-1ubuntu218.04.1, mixed mode, sharing)

**Comment by Brottweiler** [comment]
Yeah, Optifine doesn't work with Java newer than Java 8.

You have two options:

1. Install OpenJDK 8 and use that instead of Openjdk 11, or
2. Use the updated launchwrapper that you can find here: https://github.com/sp614x/optifine/issues/1739#issuecomment-417884419

**Comment by brktz** [comment]
@Brottweiler thanks, it worked by changing to OpenJDK 8
