### ISSUE TITLE
Stolen Cape

### ISSUE THREAD

**Issue by CaptainX1** [sp614x/optifine#2459]
I had my cape stolen recently and just found out about it. And it seems my donation email was changed. Please help. Here is evidence: https://imgur.com/SMvZo4O

I am emailed the optifine help, but they are taking a while to get back to me. The IGN the cape was on was CaptainX and it was a black cape with a green and white letter X.

**Comment by RetroBot98** [comment]
You cant change the donation email. The cape was simply moved by someone that probably had access to your mc account.
the things you can do now are:
-Log into optifine.net with your donation email and password and move it back
-change your mc password, so it wont be moved again
-reset your optifine password just to be safe

**Comment by CaptainX1** [comment]
I cannot log in now and it says my email is not the donation email. And a second email I tried for the donation email worked to reset password but never sent.

**Comment by sp614x** [comment]
The cape owner is "tand.....s@hotmail.com" (truncated for security reasons).
The password reset email was sent on Jun 10, 2019, 12:06 and accepted by the outlook.com mail server (hotmail-com.olc.protection.outlook.com).
You can check the spam folder if it hasn't arrived yed.

**Comment by CaptainX1** [comment]
@sp614x It will not receive the email for whatever reason. I know the email and have access to it. I checked the spam folders as well as the blocked list and cannot find the email. What email address would it send from optifinex??

**Comment by landfillbaby** [comment]
hotmail/outlook just randomly block emails without even letting you know sometimes
it's such a widely known issue that a lot of sites don't let you use them to sign in

**Comment by mindforger** [comment]
i had this with gmail and epic games, it is an unfortunate fact

maybe @sp614x can send an mail from another email account of the same host or antoher host perhaps to double check (this would still maintain security, maybe the host got blacklisted for some reason!?

**Comment by CaptainX1** [comment]
> hotmail/outlook just randomly block emails without even letting you know sometimes, they accept it then discard it completely
> it's such a widely known issue that a lot of sites don't let you use them to sign up
> not sure how to solve it honestly



> i had this with gmail and epic games, it is an unfortunate fact
> 
> maybe @sp614x can send an mail from another email account of the same host or antoher host perhaps to double check (this would still maintain security, maybe the host got blacklisted for some reason!?

Yeah hopefully. I just want my cape back. And am doing my best. Thanks for the input guys.

**Comment by mindforger** [comment]
You need to understand too that you indeed could be an imposter trying to convince him tot change the connected email, this is also why i hesitated to  answer earlier, but since sp614x is the owner it should be less problematic to send a verification mail from another email account than it is for a company like epic games like in my case

**Comment by CaptainX1** [comment]
> You need to understand too that you indeed could be an imposter trying to convince him tot change the connected email, this is also why i hesitated to answer earlier, but since sp614x is the owner it should be less problematic to send a verification mail from another email account than it is for a company like epic games like in my case

I can prove I know what the blurred email is and that I do have access to it though. Like I could go on and take screenshot that Im into my email or even send mail out of it.

**Comment by CaptainX1** [comment]
@sp614x As I understand it, Hotmail has a habit of dropping emails. Would you be able to force set it to another email, like a gmail one? I can provide any needed documentation about access to that email address etc. but I am not getting the optifinex emails and have tried everything.
