### ISSUE TITLE
Crash when client unloading mods

### ISSUE THREAD

**Issue by Rongmario** [sp614x/optifine#246]
http://hastebin.com/qapopejoze.hs

**Comment by sp614x** [comment]
The error is: ClassNotFoundException: net.minecraft.client.renderer.RenderGlobal
Most probably some of the core mods is not patching correctly RenderGlobal.

To isolate the mod: 
- start with OptiFine only
- add the mods one by one (or groups of 5) until the issue appears
- test with only OptiFine and the problematic mod to verify that the issue appears
- post results
