### ISSUE TITLE
[1.14.2 HD U F1 pre9] Compact CTM Broken (image)

### ISSUE THREAD

**Issue by MisterQuiggly** [sp614x/optifine#2460]
[Example](https://i.imgur.com/QkhOXEx.png)
[Example 2](https://imgur.com/a/0pD7QGH)

Where the different textures in the compact ctm connect, there is invisibility which almost functions as an x-ray.

**Comment by xAphex** [comment]
huh, i thought this was fixed in #2423.

guess not

**Comment by MisterQuiggly** [comment]
> this issue is fixed in multimc using pre 9.

I am using pre 9 and multimc. I didn't have this issues in previous versions for 1.14.2.

**Comment by sp614x** [comment]
Fixed, coming in next preview.
