### ISSUE TITLE
emissive textures only work on entities

### ISSUE THREAD

**Issue by RyanCR03** [sp614x/optifine#2461]
emissive textures dont work on blocks and items. just entities.

**Comment by LapisDemon** [comment]
I was just about to post this as well, I can confirm that emissive textures work with my Elytra, but not with e.g. my carved_pumpkin-model, nor e.g. ore blocks.
![image](https://user-images.githubusercontent.com/30055749/59195870-6012b880-8b8d-11e9-9e1e-2ed16e8fb9ab.png)
Here on this screenshot are also ores surrounding me, I wear a pumpkin-halo-model, and wear an Elytra. Only the latter shows an emissive texture.

**Comment by MisterQuiggly** [comment]
Same issue here

**Comment by RyanCR03** [comment]
Technically the Elytra is armor once it's equipped and the pumpkin is still
rendered as an item

**Comment by LapisDemon** [comment]
> 
> Technically the Elytra is armor once it's equipped and the pumpkin is still rendered as an item
> […](#)

Yeah sure, I just wanted to note that it works on my Elytra, but not with blocks, also not equipped.

I haven't tested entities, I would have thus posted this bug with a different headline than you, just wanted to make sure that it was mentioned, so the issue gets maybe a bit more narrowed down for the Dev.

I'm not native English, so may way to write might occasionally be a bit misunderstandable ;)

**Comment by sp614x** [comment]
Fixed, coming in next preview

**Comment by LapisDemon** [comment]
> 
> 
> Fixed, coming in next preview

You're awesome, thank you <3
