### ISSUE TITLE
[1.14.2] instant crash with opdifine on linux mint 19

### ISSUE THREAD

**Issue by Nathan22211** [sp614x/optifine#2463]
probably same anwser as https://github.com/sp614x/optifine/issues/2458 but i have no clue how to change the openJDK version

**Comment by Regnander** [comment]
Can you try this out to see if it works? From what I've read, Linux Mint is based on Ubuntu so I'm crossing my fingers that this will work on your system as well.

https://askubuntu.com/a/272190

**Comment by JpegXguy** [comment]
Changing the java version is a workaround. Why should we use older versions? There is an updated launchwrapper, why doesn't the installer handle that?  The json has to be patched manually each time... @sp614x

**Comment by sp614x** [comment]
OptiFine 1.14.3_HD_U_F1
 - fixed compatibility with Java 9+
