### ISSUE TITLE
Laggy performance with 3rd Party Resource Packs

### ISSUE THREAD

**Issue by jrteeter3** [sp614x/optifine#2464]
When using Resource packs, the performance is sluggish and when using torches to light the path, often crashes. This has been replicated with all versions of PureBDCraft (x512 - x16) and other lesser known packs. This was seen in Minecraft 1.14.2

**Comment by sp614x** [comment]
Can you post the crash report?

**Comment by KaiAF** [comment]
No response from the author, closing issue.
