### ISSUE TITLE
1.14.2 Emissive Textures

### ISSUE THREAD

**Issue by SkaliberWasTaken** [sp614x/optifine#2466]
I've already had a look through the issues for 1.14, and noticed that nobody has said anything about emissive textures? i discovered the feature today, and immediately went to test it, but it doesn't appear to be working.

I have "emissive.properties" in assets/minecraft/optifine with "suffix.emissive=_glow" and my textures are redstone_ore.png, and redstone_ore_glow.png in assets/minecraft/textures/block.

Is this feature not operational for 1.14.2 yet, or is the issue on my part?

**Comment by sp614x** [comment]
Fixed, coming in next preview

**Comment by Redd56** [comment]
:okay-hand:
