### ISSUE TITLE
Continuation Cape Crisis 

### ISSUE THREAD

**Issue by CaptainX1** [sp614x/optifine#2468]
Following this previous post: https://github.com/sp614x/optifine/issues/2459

I know and have access to that email. However for whatever reason the email is not being received neither in spam nor regular inbox. I looked further into the settings of spam/junk and did not find any blocked emails related to Optifine. 

What email would this password reset be sent on? Optifinex? 

I can prove I have access to the email, so is it possible to either send my reset code as a different email or to an alternate address?

**Comment by sp614x** [comment]
This is the mail delivery report:

![image](https://user-images.githubusercontent.com/16635441/59342895-f9b3a480-8d0a-11e9-8369-d112770f4572.png)

The mail was accepted by the mail server "hotmail-com.olc.protection.outlook.com".

**Comment by sp614x** [comment]
There is nothing more that the sending mail server could do.
