### ISSUE TITLE
Flowing fluids (Vanilla, water+lava) missing bit of texture

### ISSUE THREAD

**Issue by LapisDemon** [sp614x/optifine#2469]
Flowing Vanilla fluids show a tiny bit of missing texture.
This seems to only apply to the lines in a square, not to those of the triangles-/rhombus-shaped (see pictures).

![2019-06-12_08 43 09](https://user-images.githubusercontent.com/30055749/59329038-2c02d900-8cee-11e9-80c6-9e83d2afd1fc.png)
![2019-06-12_08 12 49](https://user-images.githubusercontent.com/30055749/59328514-d7ab2980-8cec-11e9-99c8-6b25220bb006.png)
![2019-06-12_08 03 05](https://user-images.githubusercontent.com/30055749/59328565-f8737f00-8cec-11e9-9943-5c58fe9b5c97.png)
![2019-06-12_08 10 11](https://user-images.githubusercontent.com/30055749/59328571-fad5d900-8cec-11e9-8f9f-452c4ae977a2.png)
![2019-06-12_08 10 04](https://user-images.githubusercontent.com/30055749/59328575-fc9f9c80-8cec-11e9-828c-56569a303596.png)
![2019-06-12_08 08 52](https://user-images.githubusercontent.com/30055749/59328584-fe696000-8cec-11e9-8c03-632ef74ed03c.png)

Sorry if I missed an already-posted bugpost for this, I searched beforehand.

**Comment by sp614x** [comment]
This is a vanilla problem:

![image](https://user-images.githubusercontent.com/16635441/59344704-e6a2d380-8d0e-11e9-88e6-602e0a9866b1.png)

**Comment by mindforger** [comment]
but can you fix it? :D 

i have no understanding on why this happens, but if it happens due to a vanilla problem, couldn't you fix it probably with your knowledge? :)

**Comment by LapisDemon** [comment]
> This is a vanilla problem:
> 
> ![image](https://user-images.githubusercontent.com/16635441/59344704-e6a2d380-8d0e-11e9-88e6-602e0a9866b1.png)

Ah I see, sorry for not checking in Vanilla before!
I never noticed it in Vanilla, I probably only noticed now because I used emissive blocks in my pack.

I'll be looking on Mojira, if it has been reported.
Thank you!
