### ISSUE TITLE
Lava and Water textures on Localized Weather2 mod's Particles -label:bug

### ISSUE THREAD

**Issue by Rapolis** [sp614x/optifine#248]
This problem was bragging me to remove optifine alot and i hate that, it's the only way to fix it and I will have to give you a screenshot of example. Please fix it! If you do, I will give you diamonds from the MC Forums! Thank you and good luck working on it.

SCREENSHOTS:

With Optifine (Lava and Water!)
A Huge Wind Storm (Wall cloud):
![2016-08-31_09 10 56](https://cloud.githubusercontent.com/assets/21354949/18118036/182efe30-6f5b-11e6-8960-ed7f43f7e4ef.png)
EF1 Tornado:
![2016-08-31_09 11 25](https://cloud.githubusercontent.com/assets/21354949/18118055/35d5cffe-6f5b-11e6-9466-347c59b08079.png)
Without Optifine (No Bugs)
Wall cloud:
![2016-08-31_09 15 33](https://cloud.githubusercontent.com/assets/21354949/18118123/999f0bfe-6f5b-11e6-91b1-9aa4305df59a.png)
EF1 Tornado:
![2016-08-31_09 16 04](https://cloud.githubusercontent.com/assets/21354949/18118130/a2a7218c-6f5b-11e6-9f56-11039a97a5f5.png)

I just hope you can fix it! This is my first time posting on Github.

**Comment by Rapolis** [comment]
welp 2.3.15 is the bugfix version for optifine as your mod likes to change forge methods also i realized that only github contributors that work with codes n'stuff can add labels only
i had a crap ton of mods but i removed them due to the bugs and performance leak i have been expierencing sorry but its now outdated and the fix came here

**Comment by sp614x** [comment]
Fixed
