### ISSUE TITLE
i think saved toolbars are broken

### ISSUE THREAD

**Issue by ddrs15** [sp614x/optifine#2480]
even in 1.14.2_HD_U_F1_pre11 i am unable to save toolbars with C + 1-9
i think the issue lies in the zoom function that messes it up 
and there is also something strange going on which you can see in the picture: in front of the + there is supposed to be a C.
![Schermopname (4)](https://user-images.githubusercontent.com/47245725/59458304-6ff2fc80-8e1a-11e9-9d61-753e463c6351.png)
would you please take a look at it.

**Comment by sp614x** [comment]
By default 'C' is the zoom key.
You can go in "Options -> Controls" and assign another button for "Save Toolbar" or move "Zoom" to another key.

**Comment by ddrs15** [comment]
thanks i completely missed the save toolbar control setting when i was looking for it but i found it now

**Comment by DanHal11** [comment]
even after changing the zoom key I still see the missing C with or without Optifine on?
