### ISSUE TITLE
[1.14.2] [Shaders] End Portal 3D Effect Not Showing

### ISSUE THREAD

**Issue by TenLetterz** [sp614x/optifine#2490]
![2019-06-14_13 54 28](https://user-images.githubusercontent.com/7435244/59537845-9f524980-8eac-11e9-971b-6ab4442d9535.png)

Every shader that I've used doesn't render the 3D effect of the end portal/gateway block properly. Is this the shader's problem or is optifine unable to show it in shaders.

**Comment by sp614x** [comment]
The vanilla 3d effect of the end portal is not compatible with shaders.
Instead OptiFine uses a simple moving texture which is visible with shaders.
