### ISSUE TITLE
«Use VBOs» is in English

### ISSUE THREAD

**Issue by Jerozgen** [sp614x/optifine#2491]
«Use VBOs» is in English instead of language which I chosen.
![image](https://user-images.githubusercontent.com/17567951/59549543-fbc66f00-8f67-11e9-878d-e4c4f25bb163.png)

**Comment by sp614x** [comment]
Because it is not translated yet:
https://github.com/sp614x/optifine/tree/master/OptiFineDoc/assets/minecraft/optifine/lang
