### ISSUE TITLE
[Suggestion] Strange shading on slopes, could this be fixed with Optifine? 

### ISSUE THREAD

**Issue by noacubestudio** [sp614x/optifine#2493]
![grafik](https://user-images.githubusercontent.com/31667392/59553106-5d9acf00-8f90-11e9-8cce-f9467f2661d4.png)

This does happen in vanilla as well, just wondering if it's possible.

**Comment by sp614x** [comment]
Vanilla has no slopes. Is this from another block?

**Comment by OktayYeniTR** [comment]
add "ambientocclusion": false, to model

**Comment by noacubestudio** [comment]
I meant vanilla as in no mods, I just did this in a resource pack, my bad. It happens with all sorts of shapes that have a 45 degree angle, etc. Disabling ambient occlusion does work, but it then looks almost as strange on the sides of blocks. And since it only happens in certain situations based on the other blocks around it, I was seeing that as a bug for sure ... so maybe rather something for Mojang to fix!

**Comment by sp614x** [comment]
OptiFine doesn't change the vanilla block model loading.
Adding "ambientocclusion: false" may help as the smooth lighting (ambientocclusion) is designed to work with cubic blocks and would probably be incorrect for slopes.

**Comment by noacubestudio** [comment]
Ah, okay.
