### ISSUE TITLE
immersive engineering invisible texture

### ISSUE THREAD

**Issue by GJan12** [sp614x/optifine#250]
hey i have problem with IE most of coins are invisible and author will probably do nothing about it so is there hope for fix this issue
[![2016-09-03_19.34.40.png](https://s10.postimg.org/5s350yard/2016_09_03_19_34_40.png)](https://postimg.org/image/8m6aeecxh/)

**Comment by GJan12** [comment]
sorry it´s actully connectors

**Comment by sp614x** [comment]
OptiFine version, forge version, IE version, other mods installed, F3 screenshot?

**Comment by mindforger** [comment]
>author will probably do nothing about it

you got an outdated IE version, i can tell from the cable rendering
