### ISSUE TITLE
Crash on Loading my TexturePack

### ISSUE THREAD

**Issue by aciapek** [sp614x/optifine#2501]
When I try to load minecraft with my texturepack, the loading bar of minecraft stops almoast at the very end and don't load up any more

**Comment by realjackasterisk** [comment]
really need more info here. crash log?

**Comment by OktayYeniTR** [comment]
can you post your log(not crash log)

**Comment by aciapek** [comment]
Actually it's not crashing but something like hanging on screen from picture. Dont wanna either crash, either load.
![Bez tytułu](https://user-images.githubusercontent.com/51880492/59612960-51dd1300-911e-11e9-945f-56efc09ff023.png)

**Comment by aciapek** [comment]
Actually it's not crashing but something like hanging on screen from picture. Dont wanna either crash, either load.
![Bez tytułu](https://user-images.githubusercontent.com/51880492/59613039-7933e000-911e-11e9-8755-e630be1f1ac4.png)

**Comment by OktayYeniTR** [comment]
can you post your latest.log file?

**Comment by sp614x** [comment]
You can configure the launcher to show the game output (console) and then the log will be visible while the game runs.

**Comment by KaiAF** [comment]
Closing as this ticket is invalid, please create a new ticket if you are still having this issue.
