### ISSUE TITLE
[Suggestion] Seaweed animation toggle

### ISSUE THREAD

**Issue by july3303** [sp614x/optifine#2508]
I've noticed that my fps plummets whenever I look out at an ocean biome with a lot of seaweed present and I'm guessing that it's because of the seaweed's animation cycle, it would be great if we could get a toggle for this (and underwater grass in general) much like the toggles for the rest of the animations (e.g. fire, void particles, etc.)
Unless there is such a toggle already present and I missed it, or if the lag spikes are caused by some other issue?
Thanks!

**Comment by sp614x** [comment]
The animation has a fixed effect on the FPS that is usually small and it doesn't depend on the amount of blocks being rendered.
The underwater seaweed, kelp, etc. just generate a lot of geometry that has to be rendered with transparency.
