### ISSUE TITLE
Optifine not turning off Animations (Modded)

### ISSUE THREAD

**Issue by mouro001** [sp614x/optifine#251]
Im running the modpack SkyFactory 2.5.4 and i installed OptiFine 1.7.10 HD U D6
I tried to turn off animations (all of them) but there are still animated blocks, like Fan (OpenBlocks), ME Controller, Molecular Assembler (Applied Energistics) Automatic Sieve (Ex Astris).
Could that be patched please?

**Comment by XFactHD** [comment]
Those blocks use different animation systems. The ME Controller and the Molecular Assembler use a system with a special texture with multiple frames and a meta file to tell MC how fast the frames should be played (this animation type should be disabled by the setting), the fan uses a special system which most likely won't be controllable and the uses a TESR and the animation is hardcoded. To make that controllable, OptiFine would need to access every TESR that does this kind of animation which would mean special integration for every mod that has such animations and that's simply impossible.

**Comment by sp614x** [comment]
So, closed.
