### ISSUE TITLE
Shaders goes crazy

### ISSUE THREAD

**Issue by aciapek** [sp614x/optifine#2511]
Dont know is that a optifine side or something is wrong on mine but here is what happens when iload shaders.
![2019-06-18_22 47 47](https://user-images.githubusercontent.com/51880492/59719513-d44bfc80-921c-11e9-81cd-02607754174f.png)

**Comment by sp614x** [comment]
To make shaders work with Fabric:
```
# Indigo properties file
always-tesselate-blocks=false
ambient-occlusion-mode=vanilla
```
