### ISSUE TITLE
Gamebreaking glitch on optifine 1.13.2

### ISSUE THREAD

**Issue by xXmartin0311** [sp614x/optifine#2512]
This is a weird glitch that i have that makes the game unplayable:

-I use OptiFine HD_U_E7

-Goes away if i disable Optifine

-I use minecraft 1.13.2

-All of my drivers, java, and Optifine is up to date

-Doesn't happen in simple worlds,like skyblock

-I use the latest version of Windows

If anyone can help me fix this i will be grateful. 
![2019-06-15_11 59 21](https://user-images.githubusercontent.com/51985409/59741388-29aefa80-926b-11e9-9c3b-e3e2770b203e.png)

**Comment by sp614x** [comment]
Can you post a F3 screenshot?
Forge, other mods installed?

**Comment by xXmartin0311** [comment]
No forge, conpletely vanilla except OF
(The glitch didn't appear here because it's completely random and probably appear after a few minutes)
![2019-06-19_21 20 23](https://user-images.githubusercontent.com/51985409/59793955-17b77100-92d8-11e9-814e-04a892eff878.png)

**Comment by sp614x** [comment]
Looks like a GPU or graphics driver problem.
Intel GPUs don't like VBOs, enabling/disabling VBOs may help.
Updating the grapics driver may also help. The screenshot shows v. 4248, latest is 5063/5067.
https://downloadcenter.intel.com/product/81496/Intel-HD-Graphics-4600
