### ISSUE TITLE
Dolphin model reference seems to be incorrect

### ISSUE THREAD

**Issue by NitroCipher** [sp614x/optifine#2513]
I have all of the parts listed in the docs, but Optifine claims that the tail model doesn't exist. Are the docs wrong on the list of model parts?

https://github.com/sp614x/optifine/blob/d6a9f9e7106feac1521430e48bf3065847a28c55/OptiFineDoc/doc/cem_model.txt#L33
![image](https://user-images.githubusercontent.com/11393734/59788245-eb2c3680-9290-11e9-9d86-58bb238e8637.png)
![image](https://user-images.githubusercontent.com/11393734/59788221-dfd90b00-9290-11e9-9fac-5e8928b7bb15.png)

**Comment by sp614x** [comment]
The "tail" model exists and should be working.

**Comment by NitroCipher** [comment]
Was it already working outright? Or was there something that needed to be patched?

**Comment by sp614x** [comment]
It is working in the latest 1.14.4 preview, maybe it was broken in some older version.
