### ISSUE TITLE
Optifine_1.12.2_HD_U_E3 crashing game when I turn on custom items (with other mods)

### ISSUE THREAD

**Issue by DeathBringer22** [sp614x/optifine#2518]
This is the crash report:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  FMLModule (mdxlib-3.0.0.15.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  weaponlib (mw-1.11.7.7_mc1.12.2.jar)
Contact their authors BEFORE contacting forge

// Ouch. That hurt :(

Time: 6/21/19 12:54 PM
Description: Updating screen events

java.lang.NullPointerException: The validated object is null
	at org.apache.commons.lang3.Validate.notNull(Validate.java:225)
	at org.apache.commons.lang3.Validate.notNull(Validate.java:206)
	at com.rwtema.extrautils2.backend.model.Textures.getModelResourceLocation(Textures.java:62)
	at com.rwtema.extrautils2.backend.model.Textures.registerModels(Textures.java:156)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_274_Textures_registerModels_ModelBakeEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.ForgeHooksClient.onModelBake(ForgeHooksClient.java:414)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:30)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:112)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:816)
	at net.minecraft.client.settings.GameSettings.setOptionValueOF(GameSettings.java:2044)
	at net.minecraft.client.settings.GameSettings.func_74306_a(GameSettings.java:510)
	at net.optifine.gui.GuiQualitySettingsOF.func_146284_a(GuiQualitySettingsOF.java:67)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:443)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at org.apache.commons.lang3.Validate.notNull(Validate.java:225)
	at org.apache.commons.lang3.Validate.notNull(Validate.java:206)
	at com.rwtema.extrautils2.backend.model.Textures.getModelResourceLocation(Textures.java:62)
	at com.rwtema.extrautils2.backend.model.Textures.registerModels(Textures.java:156)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_274_Textures_registerModels_ModelBakeEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.ForgeHooksClient.onModelBake(ForgeHooksClient.java:414)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:30)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:112)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:816)
	at net.minecraft.client.settings.GameSettings.setOptionValueOF(GameSettings.java:2044)
	at net.minecraft.client.settings.GameSettings.func_74306_a(GameSettings.java:510)
	at net.optifine.gui.GuiQualitySettingsOF.func_146284_a(GuiQualitySettingsOF.java:67)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:443)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)

-- Affected screen --
Details:
	Screen name: net.optifine.gui.GuiQualitySettingsOF

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['DeathBringer22_'/161, l='MpServer', x=-68.07, y=72.00, z=333.32]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-103,68,332), Chunk: (at 9,4,12 in -7,20; contains blocks -112,0,320 to -97,255,335), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 3668713 game time, 3419413 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 73 total; [EntityPlayerSP['DeathBringer22_'/161, l='MpServer', x=-68.07, y=72.00, z=333.32], EntityWarrior['Xenomorph Warrior'/17411, l='MpServer', x=-94.50, y=8.00, z=405.50], EntityChestburster['Chestburster'/14340, l='MpServer', x=-15.35, y=30.00, z=191.71], EntityDrone['Xenomorph Drone'/14341, l='MpServer', x=37.40, y=2.00, z=439.50], EntityDrone['Xenomorph Drone'/14343, l='MpServer', x=35.41, y=3.00, z=447.81], EntityWarrior['Xenomorph Warrior'/14344, l='MpServer', x=38.41, y=20.00, z=220.26], EntityDrone['Xenomorph Drone'/14345, l='MpServer', x=30.50, y=51.00, z=219.22], EntityDrone['Xenomorph Drone'/14346, l='MpServer', x=38.49, y=32.00, z=252.82], EntityDrone['Xenomorph Drone'/14347, l='MpServer', x=46.50, y=26.00, z=265.60], EntityWarrior['Xenomorph Warrior'/14348, l='MpServer', x=58.53, y=17.00, z=279.53], EntityDrone['Xenomorph Drone'/14349, l='MpServer', x=38.40, y=19.00, z=373.79], EntityDrone['Xenomorph Drone'/14365, l='MpServer', x=73.50, y=26.00, z=377.44], EntityPraetorian['Xenomorph Praetorian'/15389, l='MpServer', x=-57.25, y=4.00, z=332.50], EntityDrone['Xenomorph Drone'/14371, l='MpServer', x=64.60, y=15.00, z=234.77], EntityBat['Bat'/17446, l='MpServer', x=-76.50, y=44.03, z=300.26], EntityBat['Bat'/16935, l='MpServer', x=-67.45, y=45.87, z=349.57], EntityCreeper['Creeper'/17460, l='MpServer', x=-90.50, y=13.00, z=386.50], EntityDrone['Xenomorph Drone'/15934, l='MpServer', x=-50.40, y=58.00, z=313.40], EntityDrone['Xenomorph Drone'/15935, l='MpServer', x=-50.40, y=58.00, z=313.40], EntitySpider['Spider'/15936, l='MpServer', x=-46.68, y=60.00, z=311.67], EntityPraetorian['Xenomorph Praetorian'/15938, l='MpServer', x=-15.50, y=19.29, z=330.50], EntitySpider['Spider'/17475, l='MpServer', x=-47.50, y=32.00, z=350.50], EntityBat['Bat'/16964, l='MpServer', x=-26.70, y=25.88, z=352.95], EntityZombie['Zombie'/17476, l='MpServer', x=-47.50, y=32.00, z=353.50], EntityZombie['Zombie'/17478, l='MpServer', x=-81.50, y=57.00, z=292.50], EntityEnderman['Enderman'/17481, l='MpServer', x=-102.50, y=10.00, z=280.50], EntityChestburster['Chestburster'/15958, l='MpServer', x=-6.93, y=33.84, z=423.02], EntityDrone['Xenomorph Drone'/15487, l='MpServer', x=-45.85, y=11.00, z=262.55], EntityItem['item.item.avp:boots.xeno'/16021, l='MpServer', x=-79.88, y=40.00, z=365.15], EntitySkeleton['Skeleton'/16041, l='MpServer', x=-47.30, y=55.00, z=317.54], EntityBat['Bat'/16557, l='MpServer', x=-93.40, y=5.12, z=359.83], EntityBat['Bat'/16073, l='MpServer', x=-76.25, y=35.10, z=341.45], EntityZombie['Zombie'/17105, l='MpServer', x=-7.50, y=16.00, z=307.50], EntityYautjaWarrior['Yautja (Predator)'/15066, l='MpServer', x=-105.50, y=44.00, z=287.50], EntityVampire['Vampire Thrall'/17135, l='MpServer', x=-87.50, y=26.00, z=328.50], EntityDrone['Xenomorph Drone'/16624, l='MpServer', x=-44.60, y=3.00, z=360.40], EntityVampire['Vampire Thrall'/17136, l='MpServer', x=-90.50, y=26.00, z=328.50], EntitySkeleton['Skeleton'/17137, l='MpServer', x=-84.50, y=26.00, z=337.24], EntityWarrior['Xenomorph Warrior'/15623, l='MpServer', x=-162.50, y=21.00, z=400.50], EntityDrone['Xenomorph Drone'/15626, l='MpServer', x=-79.49, y=40.00, z=366.94], EntitySquid['Squid'/17162, l='MpServer', x=-20.40, y=51.13, z=370.40], EntityDrone['Xenomorph Drone'/15121, l='MpServer', x=-90.40, y=19.00, z=330.51], EntityDrone['Xenomorph Drone'/15122, l='MpServer', x=-107.00, y=18.00, z=326.41], EntityZombie['Zombie'/17182, l='MpServer', x=-88.50, y=32.00, z=278.50], EntityItem['item.name.lootbags_lootbagRare'/16676, l='MpServer', x=-125.11, y=15.00, z=330.55], EntityFacehugger['Facehugger'/15653, l='MpServer', x=-32.17, y=41.00, z=413.60], EntityFacehugger['Facehugger'/15654, l='MpServer', x=-33.60, y=41.00, z=411.50], EntityBat['Bat'/17219, l='MpServer', x=4.07, y=19.78, z=311.47], EntityBat['Bat'/17222, l='MpServer', x=-18.25, y=18.02, z=330.54], EntityBat['Bat'/15184, l='MpServer', x=-74.30, y=32.68, z=339.69], EntityItem['item.name.lootbags_lootbagCommon'/15696, l='MpServer', x=-79.56, y=40.00, z=368.38], EntityItem['item.item.avp:royaljelly'/15698, l='MpServer', x=-45.88, y=30.00, z=359.21], EntityBat['Bat'/16210, l='MpServer', x=-38.95, y=55.62, z=337.73], EntityZombie['Zombie'/14677, l='MpServer', x=-43.52, y=70.00, z=325.70], EntityVampire['Vampire Thrall'/15705, l='MpServer', x=-35.50, y=6.00, z=355.50], EntityChestburster['Chestburster'/17251, l='MpServer', x=-119.50, y=25.00, z=212.50], EntityZombie['Zombie'/17255, l='MpServer', x=-131.50, y=16.00, z=369.50], EntityWarrior['Xenomorph Warrior'/15735, l='MpServer', x=-47.50, y=2.00, z=367.50], EntityWarrior['Xenomorph Warrior'/14717, l='MpServer', x=1.50, y=2.00, z=301.50], EntityDrone['Xenomorph Drone'/16776, l='MpServer', x=-97.82, y=4.00, z=395.15], EntityBat['Bat'/17295, l='MpServer', x=-88.86, y=37.58, z=287.29], EntityBat['Bat'/17297, l='MpServer', x=-21.55, y=8.10, z=362.25], EntityWarrior['Xenomorph Warrior'/16277, l='MpServer', x=-66.50, y=18.00, z=236.50], EntityBat['Bat'/17308, l='MpServer', x=-94.81, y=6.98, z=278.16], EntityBat['Bat'/17309, l='MpServer', x=-100.50, y=10.00, z=279.09], EntityItem['item.item.arrow'/17323, l='MpServer', x=-97.48, y=4.00, z=394.13], EntityItem['item.item.bone'/17324, l='MpServer', x=-98.25, y=4.00, z=395.09], Entityhamonuser['Hamon User'/14773, l='MpServer', x=-74.20, y=69.00, z=304.52], EntityWarrior['Xenomorph Warrior'/14793, l='MpServer', x=-38.50, y=3.00, z=370.50], EntityDrone['Xenomorph Drone'/14305, l='MpServer', x=-206.60, y=11.18, z=203.40], EntitySkeleton['Skeleton'/17377, l='MpServer', x=-40.50, y=13.00, z=321.50], EntityDrone['Xenomorph Drone'/15334, l='MpServer', x=-91.60, y=3.00, z=290.40], EntitySkeleton['Skeleton'/17386, l='MpServer', x=-95.78, y=5.00, z=363.44]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 337567720 bytes (321 MB) / 2986344448 bytes (2848 MB) up to 3221225472 bytes (3072 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 Optifine OptiFine_1.12.2_HD_U_E3 40 mods loaded, 40 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                  | Version                  | Source                                               | Signature                                |
	|:------ |:------------------- |:------------------------ |:---------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft           | 1.12.2                   | minecraft.jar                                        | None                                     |
	| LCHIJA | mcp                 | 9.42                     | minecraft.jar                                        | None                                     |
	| LCHIJA | FML                 | 8.0.99.99                | forge-1.12.2-14.23.5.2838.jar                        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge               | 14.23.5.2838             | forge-1.12.2-14.23.5.2838.jar                        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | ivtoolkit           | 1.3.3-1.12               | minecraft.jar                                        | None                                     |
	| LCHIJA | openmodscore        | 0.12.2                   | minecraft.jar                                        | None                                     |
	| LCHIJA | deconstruction      | 3.0.4                    | [MC1.12.2]DeconTable-3.0.4.jar                       | None                                     |
	| LCHIJA | jei                 | 4.15.0.281               | jei_1.12.2-4.15.0.281.jar                            | None                                     |
	| LCHIJA | abyssalcraft        | 1.9.8                    | AbyssalCraft-1.12.2-1.9.8.jar                        | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| LCHIJA | mantle              | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                             | None                                     |
	| LCHIJA | tconstruct          | 1.12.2-2.12.0.135        | TConstruct-1.12.2-2.12.0.135.jar                     | None                                     |
	| LCHIJA | acintegration       | 1.8.1                    | AbyssalCraft+Integration-1.12.2-1.8.1.jar            | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| LCHIJA | actuallyadditions   | 1.12.2-r148              | ActuallyAdditions-1.12.2-r148.jar                    | None                                     |
	| LCHIJA | mdxlib              | 3.0.0.15                 | mdxlib-3.0.0.15.jar                                  | None                                     |
	| LCHIJA | avp                 | 6.0.0.34                 | aliensvspredator-6.0.0.34.jar                        | None                                     |
	| LCHIJA | carryon             | 1.12.1                   | CarryOn+MC1.12.2+v1.12.1.jar                         | 55e88f24d04398481ae6f1ce76f65fd776f14227 |
	| LCHIJA | conarm              | 1.2.4                    | conarm-1.12.2-1.2.4.jar                              | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LCHIJA | extendedrenderer    | v1.0                     | coroutil-1.12.1-1.2.31.jar                           | None                                     |
	| LCHIJA | coroutil            | 1.12.1-1.2.31            | coroutil-1.12.1-1.2.31.jar                           | None                                     |
	| LCHIJA | configmod           | v1.0                     | coroutil-1.12.1-1.2.31.jar                           | None                                     |
	| LCHIJA | extrautils2         | 1.0                      | extrautils2-1.12-1.9.9.jar                           | None                                     |
	| LCHIJA | foamflower          | 1.12.2-1.0.0.0-beta1     | foamflower-1.12.2-1.0.0.0-beta1.jar                  | None                                     |
	| LCHIJA | jojobadv            | 1.0.0                    | JojoBAdv-1.0.0-1.12.2.jar                            | None                                     |
	| LCHIJA | journeymap          | 1.12.2-5.5.5b7           | journeymap-1.12.2-5.5.5b7.jar                        | None                                     |
	| LCHIJA | kagic               | 1.10.0                   | kagic-1.10.0.jar                                     | None                                     |
	| LCHIJA | levelup2            | ${version}               | Level+Up!+2-1.1.22-1.12.jar                          | None                                     |
	| LCHIJA | lootbags            | 2.5.8.5                  | LootBags-1.12.2-2.5.8.5.jar                          | None                                     |
	| LCHIJA | mw                  | 1.11.7.7                 | mw-1.11.7.7_mc1.12.2.jar                             | None                                     |
	| LCHIJA | naturescompass      | 1.5.1                    | NaturesCompass-1.12.2-1.5.1.jar                      | None                                     |
	| LCHIJA | openmods            | 0.12.2                   | OpenModsLib-1.12.2-0.12.2.jar                        | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| LCHIJA | openblocks          | 1.8.1                    | OpenBlocks-1.12.2-1.8.1.jar                          | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| LCHIJA | harvestcraft        | 1.12.2zb                 | Pam's+HarvestCraft+1.12.2zd+Surprise+for+Yogcast.jar | None                                     |
	| LCHIJA | roguelike           | 1.8.0                    | RoguelikeDungeons-1.12.2-1.8.0.jar                   | None                                     |
	| LCHIJA | ruins               | 17.2                     | Ruins-1.12.2.jar                                     | None                                     |
	| LCHIJA | tinkertoolleveling  | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar                  | None                                     |
	| LCHIJA | torohealthmod       | 1.12.2-11                | torohealth-1.12.2-11.jar                             | None                                     |
	| LCHIJA | veinminer           | 0.38.2                   | VeinMiner-1.12-0.38.2.647+b31535a.jar                | None                                     |
	| LCHIJA | veinminermodsupport | 0.38.2                   | VeinMiner-1.12-0.38.2.647+b31535a.jar                | None                                     |
	| LCHIJA | vending             | 1.12.2-3.0.1.2           | vending-1.12.2-3.0.1.2.jar                           | None                                     |
	| LCHIJA | zombie_players      | 1.12.1-1.2.7             | zombie_players-1.12.1-1.2.7.jar                      | None                                     |

	Loaded coremods (and transformers): 
FMLModule (mdxlib-3.0.0.15.jar)
  com.asx.mdx.AccessTransformer
OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  openmods.core.OpenModsClassTransformer
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
weaponlib (mw-1.11.7.7_mc1.12.2.jar)
  com.vicmatskiv.weaponlib.core.WeaponlibClassTransformer
	GL info: ' Vendor: 'Intel' Version: '4.5.0 - Build 25.20.100.6472' Renderer: 'Intel(R) HD Graphics 620'
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	Launched Version: 1.12.2-forge1.12.2-14.23.5.2838
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 620 GL version 4.5.0 - Build 25.20.100.6472, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (Australia)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_E3
	OptiFine Build: 20181210-121000
	Render Distance Chunks: 7
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 - Build 25.20.100.6472
	OpenGlRenderer: Intel(R) HD Graphics 620
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by mindforger** [comment]
Please use pastebin to post crashlogs, this wall of text is hard to read

**Comment by sp614x** [comment]
Crash in Extra Utilities 2:
```
java.lang.NullPointerException: The validated object is null
at org.apache.commons.lang3.Validate.notNull(Validate.java:225)
at org.apache.commons.lang3.Validate.notNull(Validate.java:206)
at com.rwtema.extrautils2.backend.model.Textures.getModelResourceLocation(Textures.java:62)
at com.rwtema.extrautils2.backend.model.Textures.registerModels(Textures.java:156)
```
Doesn't seem to be related to OptiFine.
