### ISSUE TITLE
Crash With Immersive Engineering

### ISSUE THREAD

**Issue by Hastling** [sp614x/optifine#252]
I originally posted this issue on the [Immersive Engineering GitHub](https://github.com/BluSunrize/ImmersiveEngineering/issues/1390), but was told that it was an Optifine issue. I hope that the information provided in the crash report is enough but if it isn't please let me know anything else I can provide to help.

**Comment by sp614x** [comment]
OptiFine C3 for 1.10.2 + Immersive Engineering 0.10.42 works for me: http://i.imgur.com/l3MNOW8.png
You are also running a lot of other mods and the problem may be somewhere else.
Isolate the mod that is causing the issues, then it could be fixed.
To isolate the problematic mod:
- start with OptiFine only
- add the mods one by one (or groups of 5) until the issue appears
- test with only OptiFine and the problematic mod to verify that the issue appears
- post results

**Comment by Hastling** [comment]
When I removed [Enchiridion](https://minecraft.curseforge.com/projects/enchiridion?gameCategorySlug=mc-mods&projectID=76612) the client started up.

**Comment by sp614x** [comment]
This is why it crashed:

OptiFine is adding in FontRenderer a private method getCharWidthFloat(). This is safe as the private method can not be overriden by a subclass.
IE is extending the FontRenderer and adding a public method with the same name. So far everything is good as private and public methods can coexist peacefully.
However Enchiridion uses an AccessTransformer (AT) which changes all private FontRenderer methods to public. Now the OptiFine getCharWidthFloat() is public and the IE method is overriding it. When OptiFine calls its "private" method it instead calls the IE method and full chaos ensues.

Runtime bytecode manipulation (even AT) should not be used unless absolutely required. It can generate complex bugs which are very hard to fix.

**Comment by mezz** [comment]
Looks like they changed their AT to be more conservative, should fix this issue.
https://github.com/PenguinSquad/Enchiridion/commit/1d0f19a93e17320c16ff49a6f7639ced9238ab88

**Comment by sp614x** [comment]
The Enchiridion AT has been fixed.
