### ISSUE TITLE
Underwater fog cannot be disabled

### ISSUE THREAD

**Issue by realjackasterisk** [sp614x/optifine#2521]
Despite turning fog off at `Video Settings > Details > Fog: OFF`, underwater fog can still be clearly seen. 

Back in 1.12 and earlier, it was *very* difficult to see underwater. Obviously, turning the fog off would go against this design, and might even be considered cheating in a way. However, we've been given the Update Aquatic in 1.13, which gives players MUCH more visibility underwater by default. Now that we're on 1.14, I think it'd be safe to have the ability to disable underwater fog at this point.

**Comment by sp614x** [comment]
There is no fog underwater. The fog is an athmospheric effect (tiny droplets suspended in the air).
The Fog type option has always affected only the air fog.

Above water looks OK without fog even on shortest render distance.

![image](https://user-images.githubusercontent.com/16635441/66747288-75be2480-ee84-11e9-8ab7-94616c8c7c06.png)

Underwater looks strange without fog:

![image](https://user-images.githubusercontent.com/16635441/66747324-87073100-ee84-11e9-92f5-3df1fcec0356.png)

Air is usually clear with visibility above 1km, having fog is the exception.
On the other hand visibility underwater is usually limited, having perfectly clear water would be the exception.  For perfectly clear water the visibility distance is about 60m (4 chunks), real world water (like in MC) would be much less.
https://en.wikipedia.org/wiki/Underwater_vision#Visibility

The option Fog=OFF was added to remove the unrealistically looking fog at short render distance. Applying it to underwater vision would produce the reverse effect (realistic -> unrealistic).

**Comment by realjackasterisk** [comment]
I thought the point of disabling fog was to help with performance?

**Comment by sp614x** [comment]
Fog has minimal effect on modern GPUs, including integrated graphics.
