### ISSUE TITLE
1.14.2 preview14 shader issues and wont load into forge.

### ISSUE THREAD

**Issue by glh290** [sp614x/optifine#2525]
So far with preview 14 all the issues ive seen is it does not load into the lastest forge(makes sense the 1.14 stuff just started to come out, I didn't test with previous previews) and when loading 1.14.2 compatible sharers (worked in previous previews) over world sky glitches out, and nether loses render distance after 2-4 chunks. and general light rendering issues(overbright or overdark with some shaders)

**Comment by RyanCR03** [comment]
its not compatible with forge yet

**Comment by sp614x** [comment]
Duplicate of #2457, #2207.
