### ISSUE TITLE
Decreases FPS 

### ISSUE THREAD

**Issue by AjaxX500** [sp614x/optifine#2530]
Usually, without optifine, I get 300 fps. with optifine I get around 60! why is this?? I have a Dell G7 15. SOMEONE PLZ HELP!

**Comment by sp614x** [comment]
1. Video Settings -> Other -> Reset Video Settings
2. Check if Minecraft is using your dedicated GPU

**Comment by AjaxX500** [comment]
The first step helped a little bit thanks. How can I check if Minecraft is using my dedicated GPU?

**Comment by Studio528-real** [comment]
do ctrl+shift+esc and if minecraft is using the GPU1 (i have a laptop and it has the intel integrated (GPU0) and AMD dedicated (GPU1)) if its not go into your graphics settings for that company and go to switchable graphics, next go to C:\Program Files (x86)\Minecraft\runtime\jre-x64\bin and set the file "javaw.exe" for your switchable graphics

**Comment by AjaxX500** [comment]
mine is using (GPU0) I have an nvidia GTX 1060. If that helps

**Comment by Studio528-real** [comment]
is that your only graphics card?
or if you have multiple make sure its using the better one, for me GPU1 (the AMD dedicated)

**Comment by AjaxX500** [comment]
i only have 1 graphics card

**Comment by sp614x** [comment]
You can post an F3 screenshot, it shows the active GPU.

**Comment by Studio528-real** [comment]
so then that is your dedicated GPU, which means that you need to mess around with your optifine settings to get higher fps again.

**Comment by AjaxX500** [comment]
ok thanks guys!

**Comment by AjaxX500** [comment]
wait there is a new Minecraft launcher! open the game

**Comment by AjaxX500** [comment]
and 1.14.3 is out

**Comment by Luke100000** [comment]
60 FPS sounds to me like vsync, which is fine. Move the max FPS slider (should be on the very left, vsync, by default) to the very right.

**Comment by KaiAF** [comment]
Closing this as it doesn't seem like it's an actual issue anymore.
