### ISSUE TITLE
Textures not showing up correctly.

### ISSUE THREAD

**Issue by josh-65** [sp614x/optifine#2531]
When ever I have a custom texture pack, shader or just vanilla everything in the sky seems to be broken. With frequent full black skys.
Im using minecraft 1.12.2 with forge also using optifine prerelease 4 (I have tried using the latest official version and the previous 2 versions available same thing happens)

**This is what it should look like:**
![2019-06-24_16 18 19](https://user-images.githubusercontent.com/26977075/60031191-27e69c00-969c-11e9-865c-229999a076bd.png)

**This is what it actually looks like**
![2019-06-24_16 18 48](https://user-images.githubusercontent.com/26977075/60031164-1d2c0700-969c-11e9-8db6-5a891412a1d5.png)
![2019-06-24_16 18 02](https://user-images.githubusercontent.com/26977075/60031165-1dc49d80-969c-11e9-971e-12096815a253.png)
![2019-06-24_16 18 15](https://user-images.githubusercontent.com/26977075/60031166-1dc49d80-969c-11e9-8d51-691ac4cad84a.png)

**Comment by Studio528-real** [comment]
have you tried it without the resource pack? it might be an issue with the RP and the mod that is doing the Aurora Borealis. if it still persists then it is an issue with the mod. if removing optifine fixes it instead of removing the RP, then I can't think of a way to fix it.

**Comment by josh-65** [comment]
removing optifine fixes it. here's the log if that helps
[2019-06-24-3.log](https://github.com/sp614x/optifine/files/3321891/2019-06-24-3.log)

**Comment by sp614x** [comment]
From which mod is the sky?
Which other mods are installed?
Video Settings -> Other -> Reset Video Settings ?

**Comment by josh-65** [comment]
The sky is just a texture pack and I have try a different one and it does the same. I have also tryed reseting the video settting and it hant done anything either.
I will make a list of ghe mod and post it later

**Comment by Studio528-real** [comment]
have you tried just default textures? you said "another" but not default, I think the mod is called "dynamic surroundings", try removing it and see if anything fixes, try default then add back the RP then remove the mod and see if that fixes.

**Comment by josh-65** [comment]
I have tried using default texture and it still happens.
here's a link to the updated logs as i didn't post them all.
https://drive.google.com/drive/folders/1CCffaBzt4heF7JYtxPFVTgTmZqaCON2C?usp=sharing

**Comment by josh-65** [comment]
After playing some more it seems that also the redstone paste mod and thermal dynamic mod have broken glitched textures too.

**Comment by josh-65** [comment]
i have found out that is properly some mod conflict as i t works fine without any others installed

**Comment by josh-65** [comment]
I have found out that it was the dalek mod v.49. Thanks guys for the help.
