### ISSUE TITLE
Sometimes, textures are replaced with "Missing texture" pattern | Connected textures | Crash (OptiFine 1.14.2 HD U F1 pre15).

### ISSUE THREAD

**Issue by Boptilop** [sp614x/optifine#2532]
![log screenshot](https://user-images.githubusercontent.com/34608883/60036117-112c4f00-9674-11e9-85e8-ec6e7e4efb62.png)
This doesn't happen with connected textures disabled.
Almost every time the game will crash. If it doesn't, then this happens upon loading a world: 
![f3 screenshot](https://user-images.githubusercontent.com/34608883/60036246-65cfca00-9674-11e9-965b-2f3e63b78299.png)

Log (no crash): [latest.log](https://github.com/sp614x/optifine/files/3321753/latest.log)
Log (crash): [2019-06-24-6.log](https://github.com/sp614x/optifine/files/3321754/2019-06-24-6.log)

This was described as fixed in pre14, however, that is not the case.

This behavior was referenced in issue #2499.

Edit: Used F3+T to reload textures. This happened:
![Captura de Pantalla 2019-06-24 a la(s) 11 45 57 a  m](https://user-images.githubusercontent.com/34608883/60036805-ab40c700-9675-11e9-92df-1595a11e0e15.png)
lol very cool
don't worry though, pig is fine.
![Captura de Pantalla 2019-06-24 a la(s) 11 48 41 a  m](https://user-images.githubusercontent.com/34608883/60036978-14283f00-9676-11e9-9203-e4d72796bc93.png)

**Comment by sp614x** [comment]
```Too many open files``` when loading the CTM textures.

**Comment by sp614x** [comment]
The game has reached the maximum number of open files.

The default limit on OSX seems to be prettly low (256).

Possible fix: https://medium.com/mindful-technology/too-many-open-files-limit-ulimit-on-mac-os-x-add0f1bfddde

**Comment by Boptilop** [comment]
Unfortunately, this fix didn't fix it. After some light research I found [this.](https://stackoverflow.com/questions/16451343/java-file-limit-on-osx-lower-than-in-bash) It might fix it for you if you're having this issue too.

**Comment by Boptilop** [comment]
I can confirm that adding `-XX:-MaxFDLimit` to the JVM Arguments fixes this issue for me.

**Comment by Boptilop** [comment]
Would it be possible to add it automatically through the installer so that users don't have to do it manually?

**Comment by sp614x** [comment]
If the installer changes the jvm arguments, then it would override the launcher defaults which may be different than what the installer expects.
Custom JVM arguments are better left to the user.
