### ISSUE TITLE
Block.properties doesnt affect blocks for translucency.

### ISSUE THREAD

**Issue by RyanCR03** [sp614x/optifine#2534]
blocks don't render translucency when they are placed down but in item form, they are fine here is an example.
![2019-06-24_16 32 52](https://user-images.githubusercontent.com/32957560/60054086-2f5b7480-969f-11e9-8cb2-a7d7527cf6dd.png)

**Comment by realjackasterisk** [comment]
This is expected behaviour, the documentation even states this. https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/block.properties#L20
