### ISSUE TITLE
[Suggestion] CTM method=apply

### ISSUE THREAD

**Issue by VMan-2002** [sp614x/optifine#2542]
method=apply_overlay
method=apply_ctm
method=apply_repeat
method=apply_random
method=apply_fixed

Like overlay but instead of applying the overlaid texture to the block, it applies it to the base texture.

**Comment by sp614x** [comment]
This would be normal CTM, it repaces the base texture.

**Comment by VMan-2002** [comment]
No, it doesn't replace the base texture, that's not what I said

**Comment by sp614x** [comment]
How can CTM be applied to the base texture?

**Comment by MEEPofFaith** [comment]
yes (I answer unhelpingly)
