### ISSUE TITLE
Graphical bug (1.14.2 preview 15)

### ISSUE THREAD

**Issue by Laonyyyx** [sp614x/optifine#2543]
Hello

I launched Minecraft with Optifine preview 15 on 1.14.2 to play with my friends but when I got into the server, all entities and particules became black. I found it was a shader problem because when I disable them all come back to normal. I tried with another shader (Chocapic's 13, I usually play with Sildur's Vibrant) to check if it was only one shader problem but it was worse.

SV : 
![2019-06-26_19 03 32](https://user-images.githubusercontent.com/46350432/60201500-b13ad180-9848-11e9-9def-60ffa92041be.png)

Chocapic : 
![2019-06-26_18 52 05](https://user-images.githubusercontent.com/46350432/60201519-be57c080-9848-11e9-93f2-4d66fb3870cd.png)

I also deleted and re-installed Minecraft 1.14.2 files and Optifine 1.14.2 files but nothing changed. Same thing after I rebooted my PC.

**Comment by sp614x** [comment]
Can you post an F3 screenshot?

**Comment by Laonyyyx** [comment]
> Can you post an F3 screenshot?

Can't provide you any screenshot because the bug seems to be fixed
