### ISSUE TITLE
Shaders graphical glitch when viewing inventory of animal with lead attached 1.14.2 HD U F1 pre15

### ISSUE THREAD

**Issue by SignumEternis** [sp614x/optifine#2545]
When an animal such as a horse or llama is attached to a fence post by a lead and their inventory is opened by shift-right-clicking on them, weird graphical glitches occur. It's different with each shader and the appearance of it varies between in game screenshots and screenshots through Windows.

I've attached screenshots through each while the F3 overlay is open with 3 different shaders.

![2019-06-26_17 30 11](https://user-images.githubusercontent.com/42227117/60226030-48e6f280-983e-11e9-8011-7e42b489d072.png)
![2019-06-26_17 30 37](https://user-images.githubusercontent.com/42227117/60226031-48e6f280-983e-11e9-9b55-414feee4269c.png)
![2019-06-26_17 30 53](https://user-images.githubusercontent.com/42227117/60226032-48e6f280-983e-11e9-97ab-f57838a5b240.png)
![bsl](https://user-images.githubusercontent.com/42227117/60226033-48e6f280-983e-11e9-8fc1-4aaf5125ea2e.png)
![enhanced-default](https://user-images.githubusercontent.com/42227117/60226034-497f8900-983e-11e9-9759-cf3155ac2eb2.png)
![seus-renewed](https://user-images.githubusercontent.com/42227117/60226035-497f8900-983e-11e9-9a56-a4bcc8d8185d.png)

**Comment by sp614x** [comment]
There was a similar problem with Sildurs shaders and horse inventory.

**Comment by sp614x** [comment]
OptiFine 1.14.3_HD_U_F2_pre1
 - fixed leashed horse GUI with shaders (#2545)

**Comment by SignumEternis** [comment]
> OptiFine 1.14.3_HD_U_F2_pre1
> 
> * fixed leashed horse GUI with shaders (#2545)

That was fast. Thanks sp614x.
