### ISSUE TITLE
Crash on launch: 1.14.3 OptiFine 1.14.3 HD U F1 pre15

### ISSUE THREAD

**Issue by Citysurvivor** [sp614x/optifine#2547]
I'm using an old laptop which can barely run vanilla 1.14.3 Minecraft. The game crashes almost immediately on launch with OptiFine 1.14.3 HD U F1 pre15 selected. I tried disabling my antivirus and closing some background applications.

Pastebin crash report: https://pastebin.com/gS5wBgjm
NOTE: This crash log is outdated. My game kept crashing after this but generated no logs.

**Comment by sp614x** [comment]
Doesn't seem to be related to OptiFine.
No OptiFine classes in stack trace, no OptiFine details in crash report.

**Comment by Citysurvivor** [comment]
This is related to optifine, the crash file is outdated then. The game crashes without generating a crash report now when I launch with optifine.

**Comment by sp614x** [comment]
You can configure the launcher to show the game output.
You can also get the error log from "logs/latest.log".
Without a crash report, error log or game output it is hard to find what is the problem.
