### ISSUE TITLE
ultra c2 ultra c3 odd rendering of light smoothing and rendering

### ISSUE THREAD

**Issue by ilordnightmarei** [sp614x/optifine#255]
heres an image of it  but its  odd for how it renders forge version is 7076
using allthemods modpack  for 1.10.2  http://imgur.com/wGhfxCr http://imgur.com/SeIHCCt
its has to do with light smoothing i think or somthing has gone terribly wrong this apears and disapears in random places witch is really odd

**Comment by sp614x** [comment]
There is no Forge 7076, latest Forge is #2092
