### ISSUE TITLE
color.properties missing option to change Mojang screen loading bar outline

### ISSUE THREAD

**Issue by StrideyGH** [sp614x/optifine#2558]
![desc](https://user-images.githubusercontent.com/19396085/60358497-24ba1b80-99ce-11e9-88ce-cc683466424d.png)
The color.properties file has options to change the Mojang screen's loading bar colours and background colour but lacks the option to change the outline of the loading bar itself.

**Comment by Luke18033** [comment]
Ran into this as well while dark-ifying this screen in my pack. Not sure why this hasn't been fixed yet, seems like it would be relatively simple, given they were able to make the other colors changeable.

**Comment by Studio528-real** [comment]
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/color.properties look at line 245...

**Comment by Luke18033** [comment]
Yes, the black line surrounding the progress bar is exactly what this issue is referring to. If it was referring to the background then it would have been closed.

**Comment by Luke18033** [comment]
Can someone please explain why this hasn't been added yet? It seems like an incredibly simple change.

**Comment by sp614x** [comment]
Coming in next preview
