### ISSUE TITLE
Fullscreen

### ISSUE THREAD

**Issue by ballerball1231** [sp614x/optifine#2563]
I have 3 monitors and play Minecraft on the one in the middle but whenever I turn on fullscreen the middle screen turns completely black and the Minecraft gameplay mirrors to another monitor, I still have my mouse on the middle screen but I see what I choose on one of the other monitors. anyone has any idea how i can fix this?

**Comment by ZeLalo** [comment]
Does this only happen with Optifine?

**Comment by ballerball1231** [comment]
No i tested it and it happens on every version 1.14 - 1.14.3 with and without optifine
I’ve also tried to delete .minecraft in the dictionary folder and uninstalling the minecraft launcher and installing it again but still the same.

**Comment by sp614x** [comment]
Not related to OptiFine.
Most probably caused by the way LWJGL handles fullscreen.
