### ISSUE TITLE
1.14.3 BlingEdit (Datapack by SethBling) is Disfunctional

### ISSUE THREAD

**Issue by SmashPortal** [sp614x/optifine#2567]
The BlingEdit datapack by SethBling adds functionality similar to WorldEdit to Minecraft. You rename a fishing rod "BlingEdit" and it lets you highlight groups of blocks, then make changes to them using buttons in the chat box. In vanilla (1.14.3 and prior), if you throw the fishing rod, it gives you a replacement one with a blue name. In Optifine 1.14.3_HD_U_F1, you can highlight blocks, but nothing happens when you click on the highlighted block (normally it would select the highlighted block and provide the buttons in chat). You can throw the fishing rod, but it gives you a diamond sword that still highlights blocks, but doesn't let you do anything with them (clicking does nothing).

**Comment by xwjcool123** [comment]
Cannot reproduce.
Check if you use BlingEdit correctly.
BlingEdit detects your left click by teleporting a slime into your crosshair. You cannot hit the slime when it is stuck in a block.

**Comment by SmashPortal** [comment]
Unfortunately I was using a fishing rod, while BlingEdit requires the use of a carrot on a stick. Using a carrot on a stick works correctly.
