### ISSUE TITLE
"Incompatibile Vertex States"

### ISSUE THREAD

**Issue by DDzwiedziu** [sp614x/optifine#257]
Hello

Crashlog: http://pastebin.com/THJ0EL1M

This started happening with the Project Ozone 2 modpack on Linux. The only workaround as far as I managed is to turn off Optifine.

Happens with D4 and D6 versions.

Linux: Kubuntu 16.04.1, VESA X.org drivers [1], Intel 4000 series "GPU".

[1] Intel drivers cause nausea-inducing screen flickering.

**Comment by sp614x** [comment]
Testing against a modpack containing over 100 different mods is not possible.
Isolate the mod that is causing the issues, then it could be fixed.
To isolate the mod: 
- start with OptiFine only
- add the mods one by one (or groups of 5) until the issue appears
- test with only OptiFine and the problematic mod to verify that the issue appears
- post results

**Comment by DDzwiedziu** [comment]
It's EnderIO (sigh) 2.3.0.429_beta.

Double-checked with 428_beta, and the problem stays the same.

Also I've wanted to do a "all mods - EnderIO" test, but the cross-mod recepies would require disabling more mods and the test would not be as much reliable.

Do tell if you would need more experiments or the instance with tested worlds.

**Comment by sp614x** [comment]
You can try to set "Chunk Loading" to Default.
This may fix the problem.

**Comment by DDzwiedziu** [comment]
Both "Default" and "Multi-Core" work. Setting back to "Smooth" crashes instantly (as somewhat expected).

Closing (I think).

Thank you
