### ISSUE TITLE
Optifine 1.14.3 Crashes when i try to open Minecraft with a custom font activated

### ISSUE THREAD

**Issue by MainGameCentral** [sp614x/optifine#2571]
I put the custom font in my resource packs folder, then I open Minecraft. I go into Resource Packs and activate it, and then the game crashes without letting me view the crash report.
https://pastebin.com/iwJeSFvx

**Comment by shinji257** [comment]
Not the same Minecraft version but it is an issue with crashes when loading custom fonts.  I erroneously put this on the Forge bug tracker thinking it was the Optifine tracker.  Not sure how I did that.  I'll drop it here as the most appropriate location.  This crash is not Forge related.

**Minecraft Version:** 1.14.4

**Optifine Version:** 1.14.4_HD_U_F4

Logs: [Gist](https://gist.github.com/shinji257/1543b368ac5ae4048699ef88deb3c428)

**Steps to Reproduce:**
Load any font resource pack.

**Description of issue:**
When attempting to load a resource pack the game crashes with the above crash dump. Checked and verified using a Vanilla launcher. This issue does not appear on 1.14.4_HD_U_F4_pre3. I don't have any other preview releases but it has started showing up as of the released 1.14.4_HD_U_F4 that is now on the website.

**Font resources tested:**
[BDcraft's addon font resource pack](https://bdcraft.net/downloads/purebdcraft-minecraft/font-addon/)
[Roboto font replacement](https://www.curseforge.com/minecraft/texture-packs/hd-font-roboto)

**Comment by shinji257** [comment]
Issue fixed now for 1.14.4.  Thanks for the quick fix! 👍
