### ISSUE TITLE
[1.14.2] Emissive Textures Transparency

### ISSUE THREAD

**Issue by MisterQuiggly** [sp614x/optifine#2572]
Am I remembering incorrectly? I could've sworn that at one point, you could lower the opacity of the emissive texture to have it show up less bright in game.
Maybe this was never a feature? But I thought it was a future.
Is there a chance this could be added so its not always rendered at full brightness.

**Comment by sp614x** [comment]
This is currently not possible.
You can still use darker colors for the emissive texture, then it would be less visible.
