### ISSUE TITLE
[Request] Changing the password by myself

### ISSUE THREAD

**Issue by GCCodes** [sp614x/optifine#2574]
Hi there! First of all, I'm sorry if this is not the right way to report this; I contacted the support via the email address that I found into the "Contact" section of the site, but I got no reply. So, the issue is that since a year, due to the password generated by the website itself, I have to change my password and my cape. I'm sure that somebody came to know my email address used for Optifine and then used some password generator to steal my account. I'm so sick of requesting a new password without having the possibility to change it by myself, since I paid for it and everyday I have to recover my account just to have one cape. Thanks in advance.

**Comment by ZenIsBestWolf** [comment]
At the time of this issue being created, cape locking was not a thing, and it may be that your account was compromised.

If this is still an issue, please contact Support via Discord, Twitter, or Email.
