### ISSUE TITLE
I cant buy i cape with paysafecard

### ISSUE THREAD

**Issue by Johzzz** [sp614x/optifine#2575]
i would like to buy i opyifine cape , but for some reason there isnt an paysafecard option. last year i was able to do so but now i cant. Can sb help me pls?

**Comment by sp614x** [comment]
You should contact paymentwall directly and them ask why Paysafecard is not available for your region.

**Comment by Johzzz** [comment]
ok i will see if that works thx

**Comment by Johzzz** [comment]
for some unknow reason no country has paysafecard available. is there another way i can donate the money through paysafecard. I really want to buy i cape.
