### ISSUE TITLE
Can't open Windows Game Bar (WinKey + G) while fullscreen

### ISSUE THREAD

**Issue by chasejsutton49** [sp614x/optifine#2577]
Usually I record my games with this feature. Just hold the Windows Key and G to open the Windows 10 Game Bar, and there it is. But whenever I'm playing with fullscreen (default resolution) with Optifine installed, the Game Bar doesn't open. For a bit, when I try to open it, there game flashes/gets brighter twice, but that's it. When I'm playing in Windowed Mode, it opens fine. It also opens fullscreen when Optifine is NOT installed. Is there a way to fix this?

**Comment by KaiAF** [comment]
#5351 Game Bar and discord both don't detect OptiFine, this is something related in the code I believe. I provided a potential fix, but this is not official.
