### ISSUE TITLE
Optifine with Java 11 or 12 does not let you connect to many servers

### ISSUE THREAD

**Issue by SecretlyJealous** [sp614x/optifine#2579]
Hi,

I've isolated this issue to Optifine and the launchwrapper 2.0 stuff. Basically many servers appear as offline for some reason, a good example would be mineplex.com , extremecraft.net and mc-central.net This is not an issue when using the default minecraft client with Java 11 or Java 12 (I tested this with 1.13.2, 1.14.2 and 1.14.3), this seems to be an issue that is specific to optifine.

**Comment by sp614x** [comment]
You can check if a firewall is not blocking java from accessing the internet.
OptiFine doesn't change anything related to the network or servers.

**Comment by SecretlyJealous** [comment]
I don't think this is related to firewalls. This issue is not present when using default minecraft with Java 11 or Java 12. With optifine a large amount of servers just ping as "Can't connect to server" while some servers still work. You can try this for yourself. Hypixel for example works but Mineplex does not when using optifine with java 12 or java 12. If it was a firewall issue it would prevent me from using java 11/12 on multiplayer servers regardless of whether I use the default client or optifine but that's not the case, and even then I'm still able to use optifine with java 11/12 on Hypixel for example but the majority of servers are not working such as mineplex, extremecraft or mc central. When mojang decides to make java 11 or java 12 the default I can imagine lots of people having issues connecting to servers when using optifine with java 11 or java 12. I know that optifine doesn't change anything related to network or servers, but there's something going on with the launchwrapper 2.0 I'm assuming which is causing this.

![Untitled](https://user-images.githubusercontent.com/10485646/60530158-1599dd00-9cf0-11e9-8f2b-2d297a9e6a81.png)

**Comment by sp614x** [comment]
Works for me:

![image](https://user-images.githubusercontent.com/16635441/61135283-99f31980-a4c1-11e9-8794-cd3b7b8d8c89.png)

![image](https://user-images.githubusercontent.com/16635441/61135249-8fd11b00-a4c1-11e9-87cd-c4487e554514.png)

**Comment by sp614x** [comment]
"Connection refused" is a socket error meaning that the connection can't be established on the network level. This may be caused by firewalls, routers, switches, internet providers, DNS resolution, etc.
OptiFine doesn't have control over what happens on the network level.

**Comment by SecretlyJealous** [comment]
> "Connection refused" is a socket error meaning that the connection can't be established on the network level. This may be caused by firewalls, routers, switches, internet providers, DNS resolution, etc.
> OptiFine doesn't have control over what happens on the network level.
> You can use a packet analyzer like Wireshark and see what packets go in and out over the network.

What java version are you using? I'm still very confused on why this works for me on normal minecraft but not when using optifine

**Comment by sp614x** [comment]
This is with bundled Java 8 on Windows.

**Comment by SuperMonis** [comment]
> This is with bundled Java 8 on Windows.

Can you try Optifine with Java 11 or Java 12? I'm having issues using those versions

**Comment by SecretlyJealous** [comment]
> This is with bundled Java 8 on Windows.

Can you try Optifine with Java 11 or Java 12? I'm having issues using those versions

**Comment by Caspea** [comment]
I deal with this issue too but it seems to be random in which servers you can’t connect to because I can connect to mineplex fine. It is only a specific server in my list.

**Comment by sp614x** [comment]
After some testing:
- OF + Oracle Java 12.0.2 - all servers are online
- OF + OpenJDK Java 12.0.2 - some servers are offline
- Vanilla + OpenJDK Java 12.0.2 - some servers are offline

The problem is with OpenJDK, vanilla MC has the same problem.

**Comment by SecretlyJealous** [comment]
> After some testing:
> 
> * OF + Oracle Java 12.0.2 - all servers are online
> * OF + OpenJDK Java 12.0.2 - some servers are offline
> * Vanilla + OpenJDK Java 12.0.2 - some servers are offline
> 
> The problem is with OpenJDK, vanilla MC has the same problem.
> Not related to OptiFine.

Could you give me a link to the oracle java download? I've only been seeing the JDK downloads

**Comment by mindforger** [comment]
https://www.java.com/de/download/manual.jsp this?

**Comment by SuperMonis** [comment]
> https://www.java.com/de/download/manual.jsp this?

That doesn't hava Java 11 or Java 12

**Comment by SecretlyJealous** [comment]
> https://www.java.com/de/download/manual.jsp this?

That doesn't hava Java 11 or Java 12, I need the version that doesn't have this issue.

**Comment by ac101m** [comment]
I was able to work around this issue on ubuntu 18.04 LTS by manually installing openjdk-8, then pointing the problem profiles towards the new installation (on my sytstem: /usr/bin/java).

**Comment by sslanec** [comment]
I'm having this issue with the latest preview (1.15 pre15). I can connect to minecraft.rtgame.co.uk fine with the vanilla client on Java 8 or 11, but only with Java 8 using Optifine. Otherwise it just sits at "connecting..." until it times out. Even weirder, I can connect fine using Forge on Java 11, but you can't leave spawn with a non-vanilla client. Hypixel and Mineplex work fine either way, so I'm not sure if it's a problem with this specific server or what.
