### ISSUE TITLE
[Bug] Permanent Day Time on Solo Worlds

### ISSUE THREAD

**Issue by GameroftheUndead** [sp614x/optifine#2580]
Recently, I have discovered that when I use any 1.14, 1.14.1, 1.14.2, or 1.14.3 version of optifine, including OptiFine 1.14.3 HD U F1, all of my singleplayer worlds will be in a constant day as shown in the video attatched. I have done testing and this bug only occurs when I use optifine. If I am to run a non-optifine instance of Minecraft, the worlds work fine and the day/night cycle is normal. I can only conclude this is due to optifine. Please help.
![ezgif com-optimize](https://user-images.githubusercontent.com/28843081/60471148-6e567080-9c31-11e9-91a1-30c9b13ab826.gif)

**Comment by ZachArtHunter** [comment]
There is an option in the other settings part of video settings called Time: [---] check to see if that's toggled to something other than default.

**Comment by sp614x** [comment]
Options -> Video Settings -> Other -> Time -> Default

**Comment by GameroftheUndead** [comment]
That worked. Thank you sincerely. I apologize that I did not see the option to begin with. Thanks!
