### ISSUE TITLE
I can't change my cape

### ISSUE THREAD

**Issue by Exaflar** [sp614x/optifine#2586]
I can't change my cape, whenever i enter the URL of my new cape and hit save and reload it in the game, it still uses the cape i selected before. Help?

**Comment by rayblon** [comment]
If you haven't already, try restarting minecraft.

If that doesn't work, you may be using too many parameters in the cape itself. It has a limit, but i forget what it is exactly.

**Comment by Exaflar** [comment]
I've already restarted Minecraft several times, opened the Cape Editor again and reloaded my cape and added the URL again. It is a very simple cape and i've had capes with more detail working just fine. But when i try reloading it just saves my old cape design. Now it even went far enough to just not include my cape at all, and i have the setting Show Capes in details on.

**Comment by Vexima** [comment]
What's your IGN?

**Comment by ZenIsBestWolf** [comment]
If this is still an issue, please contact Support on Twitter, Discord, or via Email.
