### ISSUE TITLE
Crash with certain ISmartBakedModel

### ISSUE THREAD

**Issue by Da-Technomancer** [sp614x/optifine#259]
I'm the dev of the Crossroads mod, and several people have reported a crash when placing down any of the blocks that use an ISmartBakedModel that is caused by an incompatibility with optifine. I'm not sure if it's on my side or Optifine's, but here is a link to one of the relevant crash reports and the ISmartBakedModel code. 

http://pastebin.com/cpcLMbkp
https://github.com/Da-Technomancer/Crossroads/blob/master/src/main/java/com/Da_Technomancer/crossroads/client/bakedModel/ConduitBakedModel.java

Sorry to bother you if this is on my end, but if so could you point me in the right direction for fixing it?

**Comment by sp614x** [comment]
The crash is caused by a BakedQuad with a NULL facing (EnumFacing).
Maybe one of the quad vertex points is not correct (not on a plane with the rest) and the UnpackedBakedQuad.Builder can not determine the quad orientation.

**Comment by Da-Technomancer** [comment]
Thank you, I was able to fix the bug.
