### ISSUE TITLE
Error Cape not found for <USEERNAME>

### ISSUE THREAD

**Issue by gr4nt** [sp614x/optifine#2591]
halp pls. When I try to change my cape I get this error :/ .
![Untitled presentation](https://user-images.githubusercontent.com/52511582/60687685-5bc87b00-9e6d-11e9-91da-e63f91223ae0.png)

**Comment by sp614x** [comment]
Fixed, you may have to fix the cape design: 
banner_paaHazplaHaK_m_202020_202020

**Comment by gr4nt** [comment]
Thank you so much for replying and thanks for fixing the issue so promptly!

>
