### ISSUE TITLE
Dynamic Lighting Properties and Vanilla

### ISSUE THREAD

**Issue by acars123** [sp614x/optifine#2599]
Hi there!
Firstly, big fan of your work and your knowledge of programming. It's very interesting to see how Optifine has developed over the years.

I've been working on a 'miner's helmet' of sorts, in vanilla, and it works by a custom model with nbt data on a skeleton skull. When worn, it becomes a custom modeled carrot on a stick.

I cannot, for the life of me, find out how to add vanilla items to the dynamic lighting properties file in my resource pack. It uses a data pack, and initially I was going to settle on just using night vision. But dynamic lighting? Knocks that idea out of the park.

Edit: I realize making it a torch would make the have the same effect. My point still stands: I'd like to add vanilla items and blocks to the properties.

My 'dynamic_lights.properties' file is located in '(Root resource pack dir)\assets\minecraft\optifine\'

I would very much appreciate your help on the matter.

If it's just some simple misunderstanding on my part, please tell me what I can do to fix this. Thanks in advance.

(Just for GitHub, the properties file is being added as a txt.)
[dynamic_lights.properties.txt](https://github.com/sp614x/optifine/files/3365366/dynamic_lights.properties.txt)

**Comment by sp614x** [comment]
```This configuration file allows mods to define dynamic light levels for entities and items.```
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/dynamic_lights.properties#L9

The "dynamic_lights.properties" is made for mods. 
All vanilla items that emit light are automatically detected.

**Comment by sp614x** [comment]
Relevant #1748, #1664, #182.
