### ISSUE TITLE
JEI rendering errors [bug] [high importance]

### ISSUE THREAD

**Issue by DanHolli123** [sp614x/optifine#260]
whole original discussion with the creator of JEI about the problem

[JustEnoughItems issue #372](https://github.com/mezz/JustEnoughItems/issues/372)

**Comment by DanHolli123** [comment]
until this is solved i won't be using optifine (witch I hate to need to do)

**Comment by sp614x** [comment]
Is this reproducible with only OptiFine and JEI installed (no other mods)?

**Comment by mezz** [comment]
Here's a crash log with fewer mods, but I haven't seen anyone try to reproduce it with a minimal setup yet.
https://gist.github.com/mightydanp/06dbd8f674ac06ccb5e9f7025c59137b

JEI copies some of the Minecraft item rendering code into its own classes with some small changes in order to render the item list with fewer OpenGL context changes. If Optifine is changing that code in Minecraft and expects it to work a certain way, it may be relevant to this bug. 

Rendering code starts here:
https://github.com/mezz/JustEnoughItems/blob/1.10/src/main/java/mezz/jei/gui/ingredients/GuiItemStackFastList.java#L96-L161
and the copied stuff starts here:
https://github.com/mezz/JustEnoughItems/blob/1.10/src/main/java/mezz/jei/gui/ingredients/GuiItemStackFast.java#L74-L105

**Comment by sp614x** [comment]
The "IllegalStateException: Already building!" is a follow-up error. 
Something else have crashed already and because of this the VertexBuffer is still open and the next code which tries to use the VertexBuffer gets the "Already building" error.
The previous error may be visible in the error log.

**Comment by DanHolli123** [comment]
it only happens for me with optifine installed

**Comment by sp614x** [comment]
@DanHolli123 Error log with only OptiFine and JEI?
Steps to reproduce?

**Comment by eruantien-hiraear** [comment]
When using only OptiFine_1.10.2_HD_U_C3 and jei_1.10.2-3.12.6.304 on Forge 2099 this error does not occur for me. However I've had it happen when searching for items, earlier today in fact, on a larger mod order. So I'll probably spend a bit of time going through the mods in my load order manually and finding which recipes this happens for. No guarantees on timeliness however.

**Comment by eruantien-hiraear** [comment]
The only mod that has thrown an error for me so far is Inductive Automation and its dependency library (which has a long and complicated name that I don't have with me atm). I'll try reproducing the crash on a minimal load order later and report the crash to IA's mod author meanwhile.

**Comment by eruantien-hiraear** [comment]
okay, so IA is definitely one mod that causes issues, but I think that by hiding its items from the JEI menu this crash can be bypassed. obviously this isn't a proper workaround, and there may be more mods that have errors with JEI and Optifine. 

to clarify, JEI and Optifine work together fine; and, JEI and IA work together fine (I haven't tested only IA and Optifine). it seems to be that when the three are combined that a crash occurs. whose end is this on?

**Comment by sp614x** [comment]
In ordr to be fixed the bug has to be reproducible with the minimal number of mods involved.
Best would be only 2 mods (optifine and another), but sometimes there are 3-mod dependancies.

**Comment by eruantien-hiraear** [comment]
With only Optifine, IA and its dependency (CD4017BE_lib-1.10.2-4.2.0) loaded, I get an identical crash when attempting to navigate to IA's creative tab in creative mode. The crash does not occur when loading only Optifine & CD4017BE_lib. The crash does not occur with Optifine disabled. JEI, then, seems to be unrelated to this case. I believe the words required here are, "my bad". xP

Crash: http://pastebin.com/raw/E2cFHdBT
Log: http://puu.sh/rGV7N/0f6a9b4542.log

https://github.com/CD4017BE/InductiveAutomation/issues/17

**Comment by sp614x** [comment]
Tested MC 1.10.2 + Forge #2099 + preview OptiFine C4 + IA 5.1.1 + CD4017BE_lib 4.2.0.
Not crashing when opening IA creative menu, everything seems to work.
The error log shows missing model variants, but this also happens without OptiFine.
Cabn you test again with latest preview OptiFine C4?

**Comment by eruantien-hiraear** [comment]
Fantastic, the preview C4 works perfectly (as far as I can tell). Thanks for fixing that so quickly!

**Comment by DanHolli123** [comment]
will try soon
