### ISSUE TITLE
Crash with Java 12

### ISSUE THREAD

**Issue by jamesrothermel** [sp614x/optifine#2600]
[Wowowowow.txt](https://github.com/sp614x/optifine/files/3366003/Wowowowow.txt)
[crash-2019-07-05_22.05.59-client.txt](https://github.com/sp614x/optifine/files/3366004/crash-2019-07-05_22.05.59-client.txt)
I don't know what is going on.

**Comment by sp614x** [comment]
```
Failed to load library: C:\Users\...\AppData\Local\Temp\a205-d3bf-859d-1216\OpenAL32.dll
```
Why is the launcher trying to load a library from the "Local\Temp" folder?

**Comment by jamesrothermel** [comment]
So than what do I do?

**Comment by sp614x** [comment]
This is a launcher/java problem, not related to OptiFine.
