### ISSUE TITLE
Error on installation 1.14.3

### ISSUE THREAD

**Issue by Madsee** [sp614x/optifine#2601]
![Безымянный12](https://user-images.githubusercontent.com/25270255/60775309-d7565080-a129-11e9-9021-7d0da0f6aa9f.png) When i press install it says that it cant find minecraft 1.14.3 though i have it and i play it just fine. In the launcher i use version with forge and i wanted to install optifine separately

**Comment by acars123** [comment]
Locate the install directory for that launcher and in the folder called 'mods', place the optifine jar. It will load automatically.

**Comment by sp614x** [comment]
The error message says:
You have to download and start Minecraft 1.14.3 (not Forge 1.14.3) in the official launcher (not the TLauncher).

**Comment by GemmaRose628** [comment]
I have this same issue and I've been playing 1.14.3 multiple times a week for about a month now via the official launcher
