### ISSUE TITLE
Smooth FPS breaks playability 

### ISSUE THREAD

**Issue by datmelonkid** [sp614x/optifine#2603]
Whenever I turn on the "Smooth FPS" option, I get 0 fps, and i can barely navigate the pause menu to turn it off. I actually use the smooth fps option, so i don't want it off all the time just to play. Any help would be much appreciated.

**Comment by sp614x** [comment]
If the Smooth FPS option doesn't work for you, then don't use it.
There is nothing that can be changed in it.
