### ISSUE TITLE
innerSeams not working with inner corners.

### ISSUE THREAD

**Issue by dankcatlord** [sp614x/optifine#2606]
The Connected Textures is set to fancy.
![2019-07-10_01 23 44](https://user-images.githubusercontent.com/52134780/60942783-ec5deb80-a2b1-11e9-9c77-1eb7fe719b55.png)
![2019-07-10_01 24 00](https://user-images.githubusercontent.com/52134780/60942784-ec5deb80-a2b1-11e9-9521-7f0f1cd0b99f.png)

**Comment by Spook2U** [comment]
This is fixed in a newer version. #2966
