### ISSUE TITLE
blocks split between different block types?

### ISSUE THREAD

**Issue by donovan1212** [sp614x/optifine#2607]
I was messing with CPU affinity at the time (I have had it happen before without messing affinity too but on a prerelease build for 1.14.2, I did not get it again after that until weeks later) I was getting this bug and performance issues and so I chalked it up to that. I started to enable cores and was seeing if that fixed the issue and how many were mandatory. The thing is both still persisted. It eventually went away but I caught photos. I am trying to reproduce the issue I will let you know if I am able too and what I did. I think the poor performance is probably to do with chunk rendering as I was traveling at the time in my creative world and the shaders, therefore, I am not going to publish that as an issue, however, I cannot find an instance with this one. My apologies if it is a duplicate!
Specs: Windows 10 Pro OEM version 18362.175
Core I7 2600k @ 3.4ghz
RTX 2060 (non-super) 
8gb ram (DDR3 @ 1600mhz)
860 EVO 500gb (My PC loves the numbers 8 and 6 LOL)
Video Drivers: 430.86
Optifine 1.14.3 f1
![Bug2](https://user-images.githubusercontent.com/32581031/60943726-6be8bc00-a2ac-11e9-939d-8e7da1a7668e.png)
![Bug1](https://user-images.githubusercontent.com/32581031/60943736-730fca00-a2ac-11e9-9844-439fa185d030.png)
![bug3](https://user-images.githubusercontent.com/32581031/60943226-e4e71400-a2aa-11e9-9972-bd33cce55a41.png)

**Comment by donovan1212** [comment]
My apologies for it being rainy, I should have turned it off!

**Comment by sp614x** [comment]
Resource pack, shader pack, F3 screenshot?
It would be nice if you can post daylight screenshots, the above ones are very dark.

**Comment by donovan1212** [comment]
I apologize, I am trying to reproduce the issue, currently, However, I have not yet been successful. The texture pack was realistico though a slightly older version and SUSE renewed was the shader. However, the issue when I had it in the older build did not have any shaders or texture packs applied. Let me double check but I should have an F3 screenshot.

**Comment by donovan1212** [comment]
Here we go, I messed with affinity and graphics settings (switching between fancy and fast graphics) my affinity was 5 threads at javaw.exe and I got the information you asked ad a set of new photos.
![Bug_close](https://user-images.githubusercontent.com/32581031/61011398-10680e00-a340-11e9-959f-1b5d37c922c6.png)
![Bug_far](https://user-images.githubusercontent.com/32581031/61011400-1231d180-a340-11e9-9783-afc197b83aee.png)
![Debug info](https://user-images.githubusercontent.com/32581031/61011403-152cc200-a340-11e9-8efa-bd680cc6a118.png)

**Comment by donovan1212** [comment]
Unfortunately, while I am sure I have had this glitch occur either on internal shaders or no shaders, I cannot reproduce it on anything but SUES Renewed. Unfortunately, this means I cannot at the moment confirm this is an Optifine problem. I will investigate reopening if I get the glitch outside of SUES renewed, but for the time being, I will treat it as a SUES problem and report it there. I apologize for wasting your Time!
