### ISSUE TITLE
Slow Chunk Rendering In OptiFine 1.14.3 HD U F1

### ISSUE THREAD

**Issue by Lermatroid** [sp614x/optifine#2608]
When using optifine the load times on chunks is extremely slow, only once you walk up to the chunk will it load. I have my render distance set to 12 and everything works fine in vanilla 1.14.3 and optifine/vanilla 1.13.2

edit: if I spawn in a world and stand still it renders only the a few chunks around me as seen below
![screenshot](https://user-images.githubusercontent.com/38444224/61006377-c9721c80-a32f-11e9-8784-f7c0af9d82a0.png)

**Comment by KaiAF** [comment]
Is this still an issue? Update optifine to a new version?
