### ISSUE TITLE
payment method broken?

### ISSUE THREAD

**Issue by Dovahfruit** [sp614x/optifine#2609]
ccnow is gone? why?
![sdgsdgdsf](https://user-images.githubusercontent.com/52689684/61019773-656c4a00-a369-11e9-8758-b47b3c61ebc6.PNG)

**Comment by realjackasterisk** [comment]
CCNow was removed like a year ago, dude.

Explanation here: https://twitter.com/OptiFineNews/status/1136151276675162114
