### ISSUE TITLE
Optifine collapses with large texture-atlas

### ISSUE THREAD

**Issue by Megistus** [sp614x/optifine#261]
Issue does not crash minecraft, but essentially renders it unplayable and lags really hard. If I remove some textures, the problem goes away, or at least I am able to reload the game and it goes away.

Without Optifine:
![2016-09-22_13 07 02](https://cloud.githubusercontent.com/assets/6314023/18768805/c03d0a44-80f5-11e6-8637-3670f19909c7.png)

With Optifine:
![2016-09-22_18 45 16](https://cloud.githubusercontent.com/assets/6314023/18768814/c9fb424e-80f5-11e6-9cb5-01f1f6dee731.png)

8192x8192 textures-atlas
OptiFine 1.10.2 HD U C3

Whatever other information you may need, I am quite willing to provide.

**Comment by sp614x** [comment]
Which resource pack?
F3 screenshot with lagometer?
OptiFine can recognize and load much more textures than vanilla, for example Connected Textures, Custom Animations, Custom Sky, etc.

**Comment by EskiMojo14** [comment]
What mods are you using? Using only Optifine (and Forge) my texture atlas is 16384x8192, but I can't reproduce this.

**Comment by Megistus** [comment]
![2016-09-23_06 56 25](https://cloud.githubusercontent.com/assets/6314023/18784728/faeb95d6-8161-11e6-8cf4-0ad3a8c5f89d.png)
![2016-09-23_06 58 57](https://cloud.githubusercontent.com/assets/6314023/18784729/faef2cd2-8161-11e6-98cd-be98b2b0ed8a.png)

Texture Packs:
Glimmar's Steampunk
Glimmar's Steampunk - Mod Support
Glimmar's Alts by Megistus

Glimmar's Mod Support and Alts is my work and I have not published yet, at least the Mod Support, to curse yet for 1.10 as it required a lot of work to change it over as well as add new textures. Also, dunno if it will help, but, the only textures that are part of any of the packs are those that have been modified from 16x to 64x .... thus, leaving optifine to combine the 16x with the 64x into the texture-atlas. Would it help if I converted the unmodified textures all to 64x so that optifine does not have to parse the 16x from the 64x? Just a thought.

Mod's: (All latest versions)
Chisel
Clay World Generation
Disenchanter
EnderIO
Forestry
JEI
Mekanism
MyChunkLoader
Nether Metals
Quantum Storage
Roguelike Dungeons
Storage Drawers
Tinkers Construct
Vies Craft
Waila
Xaeros Minimap
Xerox World Map
OptiFine

**Comment by sp614x** [comment]
You have an Intel GPU which is using the system memory as VRAM. Minecraft has allocated 4GB RAM and is realistically using between 6 and 8GB system memory. The resource pack is loading a lot of textures. It looks like the GPU or the OS is geting out of memory.
Decrease the MC memory (2GB or less) or turn off some RP features (Custom Sky, Connected Textures, etc).

**Comment by Megistus** [comment]
Adjusted down to 2GB ... minimum needed to not run out of memory and shut off anti-aliasing to get it to function correctly, that and turn off some other things like CIT. Thanks for the help!
