### ISSUE TITLE
I cannot make a donation 

### ISSUE THREAD

**Issue by WeebPickler** [sp614x/optifine#2611]
i keep getting the same message verify and then 3D verification failed with any card i own
![Untitled-1](https://user-images.githubusercontent.com/52778890/61035673-3798fc80-a38d-11e9-802c-bc4b67913bab.png)
 how do i fix this i want a cape
( also i covered my info for obvious reason )

**Comment by sp614x** [comment]
You should contact Paymentwall, only they can fix it.
