### ISSUE TITLE
Can't install Optifine

### ISSUE THREAD

**Issue by Sasha2k1** [sp614x/optifine#2612]
I am having troubles running the installation of Optifine. When I run it, it opens cmd for a split second and after that does nothing. I have noticed that sometimes just before it closes it prints out an error message. Opening the file from cmd leaves this error: "Could not find or load main class [filename]" What do I do? Both Java and Minecraft are on the latest version.

**Comment by Vexima** [comment]
Are you doing `right click > open with > java`?

**Comment by Sasha2k1** [comment]
when I tried it at first, windows prompted me to use something to open the file. Seeing as it's a .jar file I opened it with Java

**Comment by Vexima** [comment]
What OptiFine version are you using? Full name, eg OptiFine 1.14.3 HD U F1.
And, what is the output of `java -version` in cmd?

**Comment by Vexima** [comment]
> "Could not find or load main class [filename]"

This suggests that you may need to reinstall Java as your file associations may be broken.

**Comment by Sasha2k1** [comment]
> 
> 
> What OptiFine version are you using? Full name, eg OptiFine 1.14.3 HD U F1.
> And, what is the output of `java -version` in cmd?

That IS the version of Optifine I'm trying to run.

As for the Java version, it's "1.8.0_211"
I did try reinstalling it while trying to run it. before the reinstall I had Java 1.8.0_144

**Comment by Vexima** [comment]
Well no issues with the Java version and/or its compatibility with OptiFine. That's all I can think of. All I can suggest it waiting for someone else to roll up with a new idea.

**Comment by Sasha2k1** [comment]
Fixed it myself. Ran Jarfix to restore file associations.
