### ISSUE TITLE
Default 3d textures not loading properly issue 

### ISSUE THREAD

**Issue by Titan7272** [sp614x/optifine#2613]
If logging on with default 3d everything is a missing texture, if I attempt to reload it helps but some textures are still missing, if I log on without default 3d, and then pull it in, some textures are still missing. I decided to copy and paste the latest.log of the first scenario

[latest.log](https://github.com/sp614x/optifine/files/3383730/latest.log)

**Comment by sp614x** [comment]
"Too many open files"
You should increase max open files in OSX.

**Comment by Titan7272** [comment]
thanks
