### ISSUE TITLE
Minecraft crashes with OptiFine, reports "insufficient memory for JRE" (16 GB system)

### ISSUE THREAD

**Issue by Laserjones** [sp614x/optifine#2614]
My specs:
Windows 10, 16 GB RAM, Ryzen 2600, GeForce 1060 
Minecraft 1.14.3 with OptiFine for 1.14.3
Default JVM settings
No other mods installed, no Forge

When I start Minecraft with OptiFine, it crashes a few seconds after starting to render the world. No crash happens when I run it without OptiFine. It happens both with the internal shader and with SEUS shader, and even with shader set to OFF, only the time until it crashes varies.

No crash report is displayed in the launcher (only a crash message), but each time two files like the attached ones appear in the .minecraft folder, which report insufficient memory for the JVM. I tried different JVM settings recommended on various web sites, but no change.

Can anyone help me with this?

[hs_err_pid16568.log](https://github.com/sp614x/optifine/files/3383905/hs_err_pid16568.log)
[replay_pid16568.log](https://github.com/sp614x/optifine/files/3383906/replay_pid16568.log)

**Comment by Laserjones** [comment]
Also installed the latest version of 64-bit Java (I had 32-bit Java installed before for some reason) and instructed the launcher to use that one instead of the built-in Java, but this did not help either.

**Comment by sp614x** [comment]
Give more memory to MC "-Xmx3G" or reduce the render distance.

**Comment by Laserjones** [comment]
That was actually one of the first things I had tried. 3G, 4G, even 8G. Nothing helped. Please do not close an issue before it is solved.

**Comment by sp614x** [comment]
This is a native memory problem, not java heap memory.
Native memory is used by JVM itself. In this case the JIT compiler failed to allocate native memory.
No idea why it crashes like that. It may be connected to running on a 12 core CPU. Thread stack size may have an effect on it. 
This is not something that OptiFine can fix.

**Comment by Laserjones** [comment]
Okay, thanks. It must have to do at least _something_ with OptiFine though, because it crashes only when I run the Optifine installation, not the standard MC installation in the same launcher.

**Comment by Barteks2x** [comment]
What it is that you are running on this system?
`Memory: 4k page, physical 16704756k(4703808k free), swap 17753332k(7884k free)`
This would suggest that you have almost all of your pagefile used, and at the moment this file has been written, 4GB of RAM free, which was probably after some of it has been freed already.

In that case, it's just that your OS is running out of memory, and allocating more to java will only make it worse.

**Comment by Laserjones** [comment]
I solved the problem now by deleting the .minecraft folder completely and installing a fresh MC from scratch. Looks like some old config stuff in that folder had caused some incompatibility.
