### ISSUE TITLE
Installer fails to install

### ISSUE THREAD

**Issue by Leenuks** [sp614x/optifine#2615]
The installer will install the profile but does not install the jar file.

Extracting the jar file manually into the minecraft folder does nothing and is ignored by the game.

Double clicking on the extracted jar file in the minecraft folder duplicates the installer but without the 'Extract' button.

**Comment by sp614x** [comment]
The JAR file is not needed anymore.
The installled JSON is extending the vanilla profile and the launcher uses the vanilla JAR file.
