### ISSUE TITLE
Feature request (clouds related)

### ISSUE THREAD

**Issue by Dovahrt** [sp614x/optifine#262]
Hi, first of all, thank you for the amazing work you are doing with OptiFine (for example "dynamic lights" was brilliant). I would like to suggest you a little feature about clouds: to add a height level lower than 0 (maybe with negative values?)... in short, I would like to have the opportunity to bring the clouds at sea level (no lower than that)... it would be nice to see similar events with volumetric clouds enabled.
![image](https://cloud.githubusercontent.com/assets/22390376/18779348/f05de292-8178-11e6-8c0a-6ba37f85a943.png)
Rarely players buid above the clouds and extreme hills barely touch the "vanilla" height of the clouds (the actual level 0, with OF)... the "fog" of the game is also too "regular" (it covers everything, as opposed to how it behaves in this photo... obviously because, Minecraft's fog is just an expedient used for the render distance)...
This feature + shaders (with volumetric clouds enabled) would make some views very spectacular!! What do you think about it? :))) Maybe with two layers of clouds (with changeable heights independently of each other) we could have both clouds and a better fog effect :P

**Comment by mindforger** [comment]
this real fog stuff could be related to the humidity and temperatur of biomes and the daytime! Maybe also their boundary biome :) think of a swamp aside a snowy biome ... would lead to a wall of fog quiet a few blocks into the swamp and the other snowy biome

**Comment by sp614x** [comment]
Currently there is no way to tell a shader pack how high the clouds should be. The volumetric cloud height is hardcoded in the shader pack.

**Comment by Dovahrt** [comment]
Oh... so it depends on each individual shader pack, and not from the game options :(
