### ISSUE TITLE
Cant download optifine

### ISSUE THREAD

**Issue by xvary** [sp614x/optifine#2623]
i try to get optifine but when i click download or (mirror) this is what happens
![New Tab - Google Chrome 7_13_2019 8_37_29 PM](https://user-images.githubusercontent.com/52870726/61177904-1fec8e80-a5ae-11e9-91bf-27353178aa9c.png)

**Comment by Vexima** [comment]
Disable you adblocker, that't the reason 99% of the time the download link doesn't come up.
