### ISSUE TITLE
Optifine 1.14.3 F2_pre2 problem with Forge 1.14.3

### ISSUE THREAD

**Issue by 6ix7even** [sp614x/optifine#2632]
When i see this thing in the changelog , i believe it's work with forge finally
![gethtrhrthtr](https://user-images.githubusercontent.com/44172841/61288006-851acc80-a7c6-11e9-97e3-bcac92eb2abf.jpg)

But when i launch the game , i have this :/

![2019-07-16_12 35 00](https://user-images.githubusercontent.com/44172841/61288029-919f2500-a7c6-11e9-87fd-677f9b503388.png)

**Comment by realjackasterisk** [comment]
Literally no more than 2 lines down you could've read the following:

> internally compatible with Forge 27.0.51 (can't be installed yet)
