### ISSUE TITLE
Smart Animations mod compat question

### ISSUE THREAD

**Issue by Johni0702** [sp614x/optifine#2633]
(OF 1.12.2 E3)
How do I get OF to recognize that I've manually rendered an animated block sprite?
As is, with Smart Animations turned on, the sprite isn't animated (because I'm the only one rendering it).
Specifically after [this](https://github.com/Johni0702/BetterPortals/blob/d407920f114d25ffe9a269a33f67f66c5a0520ea/src/api/kotlin/de/johni0702/minecraft/betterportals/client/render/FramedPortalRenderer.kt#L102-L110) draw call, where previously I've manually filled the BufferBuilder using the sprite's [UV coordinates](https://github.com/Johni0702/BetterPortals/blob/d407920f114d25ffe9a269a33f67f66c5a0520ea/src/api/kotlin/de/johni0702/minecraft/betterportals/client/render/FramedPortalRenderer.kt#L127-L130).

**Comment by sp614x** [comment]
`BufferBuilder.setSprite()` is used to update animated sprites.

**Comment by Johni0702** [comment]
Thank you very much. With that call it's now working as expected.
