### ISSUE TITLE
Can i translate to finnish

### ISSUE THREAD

**Issue by viluzi** [sp614x/optifine#2635]
title

**Comment by Vexima** [comment]
Please explain what you mean in more detail, then me pr others will be able to help you.

**Comment by Regnander** [comment]
@viluzi Sure! You can find the English text at https://github.com/sp614x/optifine/blob/master/OptiFineDoc/assets/minecraft/optifine/lang/en_us.lang. When you are done you can upload the translation to https://github.com/sp614x/optifine/new/master/OptiFineDoc/assets/minecraft/optifine/lang, but make sure the file is called `fi_fi.lang`.

> Please explain what you mean in more detail, then me pr others will be able to help you.

Read the title. He/She wants to translate OptiFine to Finnish.

**Comment by Vexima** [comment]
Sorry, my head wasn't working - I thought it said finish.

**Comment by Regnander** [comment]
> Sorry, my head wasn't working - I thought it said finish.

No worries. Everyone makes mistakes, including myself.

**Comment by viluzi** [comment]
one problem, in what context is the from in the beginning used? because in finnish that word doesnt exist it is instead in the endings of words. like from "my house" "minun talo**sta**"
