### ISSUE TITLE
Connected textures not working yet on 1.14.3 Optifine HD U F1  

### ISSUE THREAD

**Issue by Ha3mster** [sp614x/optifine#2639]
i recently installed optifine HD U F1 and discoverd that even when i have the option conected textures on fancy glas wont connect with the standard texture pack wich i find sad because it looks good and its a bummer that it is not working please consider to fix that in the next version 

![2019-07-17_18 58 49](https://user-images.githubusercontent.com/53014599/61395118-ecb74180-a8c4-11e9-8dcc-4bed1ccc68d9.png)

**Comment by TheThunderGuyS** [comment]
For me it works just fine.
![Annotation 2019-07-18 102925](https://user-images.githubusercontent.com/52540509/61465932-0731ff00-a947-11e9-9af9-0b32089f30b5.png)
It might be a issue related to your PC, I know some versions of Java or some graphics drives could mess it up. I'm on 64-bit Java 11.0.4 if that makes any difference.

**Comment by sp614x** [comment]
Fixed in latest preview for 1.14.4.
