### ISSUE TITLE
Optifine 1.14.3 Does not install and instead downloads a text document

### ISSUE THREAD

**Issue by Abdurrr** [sp614x/optifine#2647]
The file is called hs_err_pid and a bunch of numbers after

**Comment by realjackasterisk** [comment]
Where did you download OptiFine?

**Comment by sp614x** [comment]
The hs_err_pidXXX is a Java native crash log.

**Comment by Abdurrr** [comment]
I downloaded 1.14.3 hd u F1 from the download page of the optifine website

**Comment by Abdurrr** [comment]
What should I do

**Comment by Luke100000** [comment]
What is your current installed Java version? Try updating.
