### ISSUE TITLE
[Suggestion] Include checksums on every download page

### ISSUE THREAD

**Issue by realjackasterisk** [sp614x/optifine#2648]
This would help people to avoid using corrupt or even infected downloads.

Little concept using some basic inspect element:
![image](https://user-images.githubusercontent.com/31686191/61529575-87537580-a9d6-11e9-9ef6-7692d9e00eb6.png)

It should be possible to automatically generate a checksum for every file on the server.

**Comment by DaMatrix** [comment]
note that the people who are easily tricked by infected download sites are also highly unlikely to even know how to verify a checksum, or why they should.

**Comment by mindforger** [comment]
then throw a link to some known tool also in there and a "what does this mean" button, so people can learn ^^

**Comment by sp614x** [comment]
This would only help people which visit the official download page and these are going to get the correct file anyway. A fake site would copy the design and include a fake checksum so it would validate correctly.
A checksum is only useful if files are distributed over mirrors not controlled by the original website.
