### ISSUE TITLE
(Request) New Optifine.net Logo

### ISSUE THREAD

**Issue by NickTheCarrot** [sp614x/optifine#2653]
With 1.14.4 being the final release of 1.14 I thought it would be nice to redesign the Optifine logo. I was hoping it might get featured/used on the actual website. I'd love it if someone could find a use for it! Many thanks!
![Optifine Redesign](https://user-images.githubusercontent.com/53128178/61585100-f5f11a00-ab21-11e9-99af-246509f7d865.jpg)

**Comment by realjackasterisk** [comment]
Sorry, but... this looks *really* awful. There's far too much clutter, and the colors of the text don't really stand out from the background. In addition, the color palatte is far too diverse. I believe a logo should be able to work with a single color, giving it the ability to work on essentially any background. Lastly, the small image size is absolutely not useable. Logos should generally have a high-res image to use as a base. Vector graphics would be even better.

**Comment by theheeper55** [comment]
uhh what logo? i literally cant see anything. just....dirt and stone.

**Comment by sp614x** [comment]
Not readable at all.
