### ISSUE TITLE
OptiFine 1.14.3_HD_U_F2 - "Could not find the main class. Program will exit"

### ISSUE THREAD

**Issue by crosart** [sp614x/optifine#2656]
When launching the OptiFine 1.14.3_HD_U_F2.jar, an error message from JVM Launcher pops "Could not find the main class. Program will exit" and closes.

**Comment by TheSnowyChickens** [comment]
I have the same error with the 1.14.4 version.

**Comment by sp614x** [comment]
What Java version do you have installed?
Open a command prompt and write "java -version".

**Comment by crosart** [comment]
CMD Prompt dump :

java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)

**Comment by sp614x** [comment]
You can start the JAR like this:
`java -jar OptiFine_1.14.4_HD_U_F2_pre1.jar`

**Comment by crosart** [comment]
Did work indeed !

Might be a problem in my Environment variables, I'll have to check ...

**Comment by sp614x** [comment]
Most probably you have association for JAR files with an older Java runtime.
You can try JarFix:
https://download.cnet.com/Jarfix/3000-18512_4-77571216.html

**Comment by crosart** [comment]
Got it, Jarfix relinked everything with an old faulty Java 1.6 install I had, Uninstalled it, and tried to relaunch the JAR > Works perfectly.

Thanks for the heads up and keep up the great work on Optifine ;)
