### ISSUE TITLE
optifine cape not working trough fasterpay

### ISSUE THREAD

**Issue by dogemongames** [sp614x/optifine#2657]
yeah so I wanted to buy a cape so I go donate. Click paymentwall that took me to fasterpay page. I put in all credit card details and when i click im done, it says Internal error. Anyone knows how to fix this?

**Comment by DaMatrix** [comment]
that's almost definitely not optifine's problem, but rather something on paymentwall/fasterpay's end.

**Comment by sp614x** [comment]
This is Paymentwall/Fasterpay problem.
You can contact them directly to resolve the problem.
