### ISSUE TITLE
Your graphics driver doesn't support framebuffer objects

### ISSUE THREAD

**Issue by ItsmeFawaz** [sp614x/optifine#2658]
My pc is really old and normal minecraft doesn't work on it as it instantly crashes when the minecraft instance opens. It worked when I used optifine but since the 1.14.3 F1 pre 15 update it doesn't work anymore and shows this crash report. 

and FastRender is enabled in optionsof.txt in my .minecraft folder 
https://pastebin.com/3TSw6itP

**Comment by sp614x** [comment]
What is the last working OptiFine version?

**Comment by sp614x** [comment]
Duplicate of #2671.
