### ISSUE TITLE
After changing version, optifine was still loaded up?

### ISSUE THREAD

**Issue by xSaturnityx** [sp614x/optifine#2659]
Not sure if this was a Minecraft problem or Optifine

I chose 1.14.3 Optifine, was playing with a shaderpack and texture pack enabled.

When I was done playing I closed the game, 5 minutes later or so I opened the launcher, chose my normal 1.14.3 installation (not at all related to optifine) and my shaders and texturepack were still enabled? Then after about a 20 seconds my  computer crashed. Probably a one time thing but thought it'd be something to mention.

**Comment by sp614x** [comment]
The OptiFine profile is separate from the vanilla profiles.
Looks like a launcher problem.
