### ISSUE TITLE
OptiFine 1.14.3 HD U F2 couldn't post ChunkEvent.Load event

### ISSUE THREAD

**Issue by ZekerZhayard** [sp614x/optifine#2661]
A few days ago, I created a new repo called [OptiForge](https://github.com/ZekerZhayard/OptiForge). It can make OptiFine be like an ordinary mod that can be loaded with Forge.

I found that in `ClientChunkProvider.func_212849_a_`, OptiFine could not post [ChunkEvent.Load](https://github.com/MinecraftForge/MinecraftForge/blob/1.14.x/patches/minecraft/net/minecraft/client/multiplayer/ClientChunkProvider.java.patch) event. Can it be added to OptiFine officially?

**Comment by sp614x** [comment]
Added, coming in next 1.14.4 version.
