### ISSUE TITLE
[CEM] No way to replace the vanilla pig nose?

### ISSUE THREAD

**Issue by MushirMickeyJoe** [sp614x/optifine#2662]
The pig's nose isn't documented on [the CEM page here on GitHub](https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/cem_model.txt), but the nose doesn't disappear when I replace the pig head. This means the nose is a separate 'part', but isn't supported by CEM.

**Comment by sp614x** [comment]
There is no separate model for the pig nose, it is added as another box in the head model.
It should disappear when the head model is changed.

**Comment by MushirMickeyJoe** [comment]
But it doesn't.
![2019-10-15_19 48 43](https://user-images.githubusercontent.com/31923214/66856229-11cf5500-ef85-11e9-94ec-9abf5e21b614.png)

**Comment by sp614x** [comment]
Works for me in 1.14.4 previews

![image](https://user-images.githubusercontent.com/16635441/66864757-2e27bd80-ef96-11e9-919d-ca24ca134d1c.png)
