### ISSUE TITLE
[Request Discord] Animated GIF?

### ISSUE THREAD

**Issue by Studio528-real** [sp614x/optifine#2663]
So we have enough nitro boosts for an Animated GIF on the server icon, Idk if this would fall under #2360 but I had the idea for a glint along on the OF logo, whether or not this will be added I do not know, it would be nice to see and take advantage of out nitro boosts.
![Bigger-Optifine-Glint-white](https://user-images.githubusercontent.com/52116771/61663350-a7608e80-ac8d-11e9-9788-c5529479105f.gif)

**Comment by realjackasterisk** [comment]
I feel like everything here could be well improved. For starters, the white line looks *really* out of place. I think it'd look better if it was tinted like the colors it overlaid, like having a light yellow over the text. I also think the effect should be limited to the text alone, given that it has a gold color. Just makes sense.

I decided to take a turn trying the same effect using Blender. Here's the final result:

![logo_anim_reversed_new](https://user-images.githubusercontent.com/31686191/61668853-ee04b780-ac92-11e9-86c8-659780316278.gif)

And just for the hell of it, this was the first version:

![logo_anim](https://user-images.githubusercontent.com/31686191/61668941-518ee500-ac93-11e9-8863-becd82d5f821.gif)

I felt the timing of the animation here had such an intense curve that it was both too slow and too fast all at once. It also had +25 unnecessary frames, which did nothing but help to bloat its almost 0.5mb file size, among other contributing factors. Luckily the new version above was able to cut that in half.

**Comment by Studio528-real** [comment]
yea that's what I was more going for except I was using a website that didnt have much functionality since paint.net desnt do gifs... (i tried that a while back)

**Comment by realjackasterisk** [comment]
new version. 
- now centered properly
- fixed the issue with the random pixels at the top
- simplified the glint
- fixed the relatively long delay at the start of the animation (this is more noticeable in Discord where it only plays when you're hovering over the image)
- slightly faster with a longer delay at the end, as suggested by @Builderb0y on Discord

![logo_anim_rc2](https://user-images.githubusercontent.com/31686191/61741927-d129bc00-ad46-11e9-9d3a-575515bef9f1.gif)

**Comment by sp614x** [comment]
Icon set.
