### ISSUE TITLE
(CIT) Custom Dragon Head?

### ISSUE THREAD

**Issue by bpalmz** [sp614x/optifine#2667]
is it possible to do a custom wearable dragon head?  Im having some trouble figuring it out. I know the vanilla one borrows from the dragon entity texture. I tried making a different dragon entity texture and putting it in the item folder with a .properties file matching its nbt name, but it didnt work.  Sorry if this isn't the place to post this, or if its a noob question.

my .properties file looks like this:

type=item
items=minecraft:dragon_head
#nbt.display.Name=\u00a7C\u00a7LRift Dragon Head
nbt.display.Lore.0=Weird how it still moves.

its rift_head.properties, and the texture is a dragon entity texture named rift_head.png

**Comment by sp614x** [comment]
The dragon head in hand is an item and can be customized with CIT.
The dragon head on the player is an entity model and can be customized with CEM.
