### ISSUE TITLE
Forge Won't Load preview_OptiFine_1.14.4_HD_U_F2_pre1.jar

### ISSUE THREAD

**Issue by iancbogue** [sp614x/optifine#2670]
latest.log mentions that Optifine 1.14.4 HD U F2 pre1 is missing the mods.toml file and that it has been ignored because it is invalid. After Forge finishes loading, a screen pops up telling me that Optifine is not supported by this version of Forge, but it lets me go to the title screen. However, Optifine is not loaded when I check the Mods menu.

**Comment by realjackasterisk** [comment]
#2148, #2207, #2271, #2280, #2318, #2457, #2525, #2529, #2539, #2632

**Comment by sp614x** [comment]
OptiFine is not compatible with Forge yet.

**Comment by Elxafil** [comment]
When will it be compatible with Forge? We've been waiting a while for it.

**Comment by Vexima** [comment]
Soon, soon. You can see progress here https://github.com/sp614x/optifine/issues/2148#issuecomment-511156098

From that link:
> Crash fixed, now OF can run with Forge when installed as a library.
Next step is to make it load from the "mods" folder.

>Loading from mods folder is generally working, but crashes with some classes.
ModLauncher needs a bugfix:
cpw/modlauncher#31
