### ISSUE TITLE
[1.14] Witch CEM doesn't line up with Villager CEM

### ISSUE THREAD

**Issue by Spazmunki13** [sp614x/optifine#2673]
I've been working on replacing villagers and their variants, including witches, and through trial and error I found out that the part names don't correspond to the right parts on the witch model.

These were my findings:
```
head = head
headwear = "Model part not found: headwear, model: net.minecraft.class_622@4d8e060e"
headwear2 = "Model part not found: headwear2, model: net.minecraft.class_622@2422c7f"
body = headwear?
bodywear = "Model part not found: bodywear, model: net.minecraft.class_622@23d503fc"
arms = no change and no error
left_leg = bodywear
right_leg = body
nose = arms
mole = mole
```

I got curious and opened up the jar to see if I could find the cause of the issue and I think I might've found it. The ModelAdapterWitch.class doesn't have the parts that the updated ModelAdapterVillager.class has, therefore the part numbers don't line up with the villager parts. Which is makes sense with what I found through trial and error.

Hopefully this helps in some way.

**Comment by sp614x** [comment]
Fixed, coming in next preview.
