### ISSUE TITLE
When trying to get an Optifine cape, it shows up in the preview but when I continue it says invalid banner.

### ISSUE THREAD

**Issue by MisterQuiggly** [sp614x/optifine#2674]
I'm trying to use this banner: https://www.needcoolshoes.com/banner?=mapedfmcmcdgjvaoakdAmFmEdt

and it when I click the donate with PaymentWall button, I get:
Invalid cape design: banner_mapedfmcmcdgjvaoakdAmFmEdt_s_5E8CC6_5E8CC6

**Comment by sp614x** [comment]
Too many layers.
Maximum 8 layers are supported.

**Comment by MisterQuiggly** [comment]
Is it possible the maximum layers will ever be increased?
