### ISSUE TITLE
Shulker Boxes GUI

### ISSUE THREAD

**Issue by nenuvutive** [sp614x/optifine#2676]
I was making custom GUIs for the shulker boxes, and the textures didn't change for the **light blue, white, yellow and light gray** shulker boxes
I'm using these codes

```
container=shulker_box
texture.container/shulker_box=1
colors=white
```

```
container=shulker_box
texture.container/shulker_box=9
colors=light_gray
```

```
container=shulker_box
texture.container/shulker_box=4
colors=light_blue
```

```
container=shulker_box
texture.container/shulker_box=5
colors=yellow
```

Each one has its own properties file. I'm in version 1.14.3
The other colors work instead, so I don't know what's wrong.

Any solutions?

**Comment by MushirMickeyJoe** [comment]
[These work perfectly for me](https://i.gyazo.com/b11f9d6afd451a4c2f0c3ecb5a1ebfc7.mp4). Make sure the names of your GUI textures are correct.

**Comment by nenuvutive** [comment]
> [These work perfectly for me](https://i.gyazo.com/b11f9d6afd451a4c2f0c3ecb5a1ebfc7.mp4). Make sure the names of your GUI textures are correct.

I did made sure, here is how I am doing it
![Untitled](https://user-images.githubusercontent.com/52083832/61903777-a2b60780-af25-11e9-88a8-3416c17c311c.png)



It's the exact same for every other texture, and it works fine for everything besides these 4 ones.

**Comment by nenuvutive** [comment]
An update to this issue.
I've looked further into it and i tried to remove the properties for the default shulker box GUI

With this change the white and yellow shulker boxes now show the custom GUI

Although the light blue and light gray GUIs still don't show.
(and the default shulker GUI doesn't show too, which previously did)

I still can't figure out what's wrong.

**Comment by nenuvutive** [comment]
I figured it out.
I'll try to explain what caused the errors, I apologize if it's not clear enough.

There were a few main issues:

- The default shulker box `.properties` file.

- The `.properties` file names.

- The order of the `.properties` files.

1. The file for the default shulker box was interfering with the other (light blue, yellow, etc) textures, as it would replace them with its own (the purple texture).
After removing the file the white and yellow worked, but still not the light gray and light blue.

2. I checked the file names for the light gray and light blue, and noticed that the names `LB_shulker_box.properties` and `LG_shulker_box.properties` weren't recognized since they had uppercase letters in them. So i renamed them to be lowercase.

3. There was still one problem, the default GUI.
I tried re-adding the file, and it replaced those textures once again.
The file was called `shulker_box.properties`, and it wasn't the last file in the folder. (What I mean is that it wasn't last in alphabetical order. I had the yellow and white file after since they start with Y and W)
After renaming it to `z_shulker_box.properties`, making it the last file in alphabetical order, I reloaded the texture pack and every shulker box showed its own texture.
Apparently the properties files override in an alphabetical order.

Thank you anyway MushirMickeyJoe for looking into this, the help is appreciated.

**Comment by HeavenlyDark** [comment]
he tenido problemas con los colores amarillo, blanco y el color por defecto, ya que para el color amarillo, use una textura con el nombre "yellow.png" y la propiedad "yellow.properties", para solucionar este problema solo tuve que cambiar el nombre "yellow" en ingles a español o a otro nombre como "amarillo" (ya que significan lo mismo en mi idioma ) a lo que me quedaría: container=shulker_box
texture=amarillo	
colors=yellow , espero que se haya comprendido.
