### ISSUE TITLE
[Discord] Allow users to subscribe to OptiFine updates via role pings

### ISSUE THREAD

**Issue by JackDotJS** [sp614x/optifine#2677]
Users could subscribe to OptiFine updates by being granted a new role (something called "Notifications" or "Updates"). This would work via an OptiBot command, such as `!sub`. Users may also unsubscribe at any time with the opposite command: `!unsub`

When a new update is posted, another command (could be `!notify`) may be used by mods/admins to ping everyone with that role. To prevent mass pings, this role CAN NOT be pinged by default. To make this work, the bot must have the "Manage Roles" permission. With this permission in place, the bot can now perform this set of actions:
1. modify the notification role to allow pings
2. ping the role with a message posted in the channel where the command is used.
3. modify the notification role once again to disallow pings
Given a stable connection to Discord's API, this would all occur within less than a second, making it effectively impossible to abuse the mass ping.

> ### This is great and all, but why not just enable notifications for the #updates channel manually?

I've asked this same question when 5 people suggested it to me. They all gave me pretty much the same response: Discord's notifications don't work. With this system, it basically acts like an opt-in @<span></span>everyone.

**Comment by ZenIsBestWolf** [comment]
Issue moved.
