### ISSUE TITLE
Filtering messages to asign a new line number

### ISSUE THREAD

**Issue by dotModded** [sp614x/optifine#268]
I know you said that this was not possible but it is, simply adding the #line notation in the shader can fix line numbers and you can use glDebugMessageControl to tell us what file it is in. You can also insert messages with glDebugMessageInsert.

**Comment by sp614x** [comment]
Extended the "#include" parser to add "#line" directives with file and line numbers. The file numbers are printed before the error itself.

The errors now look like this:

    [Shaders][SEVERE] Error compiling fragment shader: /shaders/gbuffers_basic.fsh
    [Shaders] File: 1 = /shaders/basic_sub.finc
    [Shaders] File: 2 = /shaders/basic.finc
    [Shaders] Shader info log: /shaders/gbuffers_basic.fsh
    ERROR: 2:6: '=' :  cannot convert from 'const int' to '3-component vector of float'

The error is in file 2 ("/shaders/basic.finc") at line 6.

**Comment by sp614x** [comment]
Added in preview D3 for 1.10.2.
