### ISSUE TITLE
Shaders (in overworld) performs differently when stored in /shaders/world0 compared to /shaders

### ISSUE THREAD

**Issue by CaptTatsu** [sp614x/optifine#2687]
Title. I originally want to say "it runs slower" since that's the case on my shader, however I decided to run a test on several shaders (unzipped).

The result is somewhat interesting, this will be formatted as [Shader name]: [/shaders fps]. [/shaders/world0 fps]. The star (*) indicates where the shader programs were originally stored.

- BSL v7.1.03.2: 35*, 33
- Sildur's Vibrant v1.21 High: 39*, 37
- projectLUMA v1.00: 34, 31*
- Chocapic's v7.1: 36*, 36
- SEUS Renewed 1.0.0: 19*, 19
- Sildur's Enhanced Default v1.06: 78*, 80

**Comment by sp614x** [comment]
The paths `shaders` and `shaders/world0` are synonyms and they are only used when loading the program files. There should be no difference at runtime.
The listed differences seem to be about 5% which is not significant and they may be caused by GPU temperature, GPU load, CPU load or external factors. Sildur's even shows the inverse trend, faster in `world0`.

**Comment by sp614x** [comment]
This is probably the difference:
```
#Program Toggle
program.composite1.enabled=LightShaft
program.world1/composite1.enabled=LightShaft
program.composite2.enabled=MotionBlur
program.world-1/composite2.enabled=MotionBlur
program.world1/composite2.enabled=MotionBlur
program.composite3.enabled=DOF
program.world-1/composite3.enabled=DOF
program.world1/composite3.enabled=DOF
program.deferred1.enabled=RPSupport && RPSReflection
program.world-1/deferred1.enabled=RPSupport && RPSReflection
program.world1/deferred1.enabled=RPSupport && RPSReflection
```
Tested with BSL+7.1.02.2, several composite programs are not active when running in `shaders`, but active in `world0`.

**Comment by CaptTatsu** [comment]
That makes sense now. I've added world0/ to the program toggle and the performance drop is pretty much gone, thanks.
