### ISSUE TITLE
Blocks appering white

### ISSUE THREAD

**Issue by MaximumPlayz** [sp614x/optifine#269]
Optifine has a bug that bothers me very much. It will turn my screen white. Not entirely white, but it will be very hard to see what is going on. All the blocks turn white unless being shaded. Most color is unnoticeable. I know its optifine because I removed (and reinstalled after testing for the glitch) almost every visual mod. but after uninstalling optifine the problem was gone. My fps was worse and I could no longer use shaders. That's why I use optifine. Please fix this! My MC version is 1.9.4 And I use Optifine HD Ultra B6. Please tell me when it will be resolved. There should be a log and screenshot attached. I kinda messed up the screenshot and it also took a screenshot of the BetterFPS gui. Sorry.
Thanks.
![unnamed](https://cloud.githubusercontent.com/assets/22422618/18812598/6eae8230-828e-11e6-847f-a63f531e0967.jpg)
[2016-09-09-4.log.gz](https://github.com/sp614x/optifine/files/491474/2016-09-09-4.log.gz)

**Comment by sp614x** [comment]
To find which mod conflicts with OptiFine:
- start with OptiFine only
- add mods until the problem appears
- test with ONLY OptiFine and the last added mod to verify that it is the problem
- post error log

**Comment by MaximumPlayz** [comment]
Yeah its been fixed.
