### ISSUE TITLE
[Connected Textures] Not working 1.14.4 for glass Using Programmer art.

### ISSUE THREAD

**Issue by Renewat** [sp614x/optifine#2692]
![2019-07-27_22 34 53](https://user-images.githubusercontent.com/53386626/62001522-6834a200-b0c0-11e9-93ce-59dcf1c98b76.png)

1.14.4 With Connected Textures on. Programmer art. 

![2019-07-27_22 34 57](https://user-images.githubusercontent.com/53386626/62001524-708cdd00-b0c0-11e9-99be-e4c5bcfce47d.png)

1.13.2 With Connected Textures on. Defualt

**Comment by AbsoluteEggo** [comment]
its a shame 
how it has to go down like this ;((((((((((((((

**Comment by sp614x** [comment]
Fixed in latest preview for 1.14.4.
