### ISSUE TITLE
Shader custom textures do not work in gbuffers.

### ISSUE THREAD

**Issue by BruceKnowsHow** [sp614x/optifine#2694]
I'm on OptiFine 1.12.2 HD U F2 pre1, and attempting to load a custom texture. 

`texture.gbuffers.colortex7 = ...`

Using this line, colortex7 is still the default block atlas texture (as are all the other samplers, besides normal and specular). A custom noisetex does work in gbuffers, however.

**Comment by sp614x** [comment]
There is no colortex7 in gbuffers:
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.txt#L266
