### ISSUE TITLE
Fullscreen caps framerate to monitor refresh rate even though vsync is disabled

### ISSUE THREAD

**Issue by cobaltrogue1998** [sp614x/optifine#2695]
Optifine: 1.14.4 HD U F2
OS: Ubuntu 18.04.2 LTS
Java: OpenJDK 1.8.0_212
GPU: 1050 Ti, Driver 430.26

This does not happen when the game is windowed. This can be temporarly resolved by moving the max framerate slider to vsync and move it back to where it was. A couple of times while doing this, the game would flicker blue for a couple of seconds. But the issue happens again when you close and reopen the game.

**Comment by sp614x** [comment]
VSync is set identically for windowed or fullscreen modes.
Most probably the driver/OS doesn't react correctly to VSync in fullscreen mode.
