### ISSUE TITLE
Any way for OptiFine to fix FPS dips on chunk crossing before Mojang?

### ISSUE THREAD

**Issue by hurrgurl** [sp614x/optifine#2696]
Crossing certain chunks in 1.14.4 makes FPS very sad.

Likely related to
https://bugs.mojang.com/browse/MC-123584

Demonstration:
https://www.youtube.com/watch?v=2BJIgVvkHEU

**Comment by Jiingy** [comment]
The [Mojira issue post](https://bugs.mojang.com/browse/MC-162253) for this problem has been marked as resolved as of snapshot 23w16a.
