### ISSUE TITLE
Invisible mobs with optifine 1.14

### ISSUE THREAD

**Issue by DebugMC** [sp614x/optifine#2699]
I have no idea why this is happening, but mobs are invisible. If i reload the same area in vanilla mobs are visible. 
https://youtu.be/pOfc4mZ_Yso

also this only happens upon joining a world, this is not a server plugin that spawns invisible mobs, it has happened to me in survival vanilla worlds. 

Worst part is that reloading chunks doesn't fix, and swinging has no indication for when i hit the mobs. Players who have vanilla just see me hitting them and the mobs taking damage.

**Comment by ZenIsBestWolf** [comment]
Duplicate: #1892
