### ISSUE TITLE
Minecraft 1.12.2 UHD3 OpenGL insufficient memory issue with mipmap

### ISSUE THREAD

**Issue by AsimRamay** [sp614x/optifine#2700]
Im getting a weird issue when turning mipmap off, it says insufficient memory irrelevant of distance, and the strange thing is i remember it being just fine when i first installed it because mipmapping is off by default  , i tried resetting everything to default and still it didnt work with mipmap off , and the level of mipmap is irrelevant , now the problem is i got from 150 fps to just 6 , so the game becomes unplayable , the werid thing is ive tried allocating upto 55 GB ram and it doesnt seem to fix it and its only using 1/8gb Vram from my 2080 
sys specs are
64 GB ram, 9700K, RTX 2080 and MultiMC instance is installed on 1 TB NVME  (Drivers are up to date)

im using minecraft 1.12.2 and the latest version of optifine with BSL shaders

the insffucient memory error is from OpenGL and not Java , im not sure how to go about fixing this

Update: this might be due to extra mods - still dont know why that would cause isufficent memory when ive seen java modpacks use upto 30 GB just fine , and idk why mimap blurring would fix everything, and its not like java is using more memory its stuck aroung 18 gb no matter what settings , but turning mipmack off on my other modpack results in no problems but in this one it results in everything being black except water 

as an aside why does optifine render translucent blocks with less then X transparency black / solid is there a way to change this behavior ?
AE2 facades , when using network tool make blocks black
ik there is block.properties but how would i go about adding the block only when it is being viewed by network tool to the files 

Update2: seems to be no particular mod, but just adding more mods does this , as after adding another 20 mods , mipmapping had to go 2 to stop world rendering black , though again not using all the allocated memory - adding another 20 , memory did hit limit i tired turning to 4 and still black, i restarted with more memory and it worked , but overall its using less memory then when i had memory set at 26 gb (currently at 22 set at 35)  so i went from memeory error to completely normal 140 FPS playable with shaders enabled - the reasaon this makes no sense is that changing render distanced does nothing at all wether its 2 or 32 nothing changes - which if its a straight memory issue logically should since its loading less into memory - and this was tested in Single player so that render distances are not effected by server configs

**Comment by sp614x** [comment]
Can you post an F3 screenshot?
