### ISSUE TITLE
The UV of custom entity models does not accept floating point numbers

### ISSUE THREAD

**Issue by Hallo89** [sp614x/optifine#2705]
Hey,
I normally write my Minecraft models myself, and therefore I often define model and texture coordinates using decimal numbers for maximal precision.
In Optifine's CEM format, faces can't correctly be assigned texture coordinates which are positioned in between full texture pixels. Instead, UV floating points are always rounded down.
This is really annoying as this restricts the model access to a correct texture mapping.
Example:
```
"boxes": [
  {
    "coordinates": [
      14.2, 5.98, 0.0,
      0.6, 1.07, 7.5
    ],
    "uvEast":  [ 8.0, 1.6, 0.0, 0.0],
    "uvSouth": [ 8.0, 1.6, 5.85, 0.0],
    "uvWest":  [ 0.0, 1.6, 8.0, 0.0]
  }
]
```
This is automatically equal to
```
"boxes": [
  {
    "coordinates": [
      14.2, 5.98, 0.0,
      0.6, 1.07, 7.5
    ],
    "uvEast":  [ 8.0, 1.0, 0.0, 0.0],
    "uvSouth": [ 8.0, 1.0, 5.0, 0.0],
    "uvWest":  [ 0.0, 1.0, 8.0, 0.0]
  }
]
```

**Comment by sp614x** [comment]
CEM is based on the vanilla models which only use integer UVs.
The UVs should match 1:1 the texture pixels so for example a texture 32x64 can use 0-32/0-64 for UVs. This automatically fixes the split pixel problems.

**Comment by Hallo89** [comment]
I don't understand your comment. Can you please give me an example in which vanilla models can only accept integers?
Here's a very simple example of normal vanilla Minecraft behavior:

`assets/minecraft/model/block/dirt.json`:
```
{
    "parent": "block/block",
    "textures": {
        "all": "block/dirt"
    },
    "elements": [
        {   "from": [ 0, 0, 0 ],
            "to": [ 16, 16, 16 ],
            "faces": {
                "down":  { "texture": "#all", "uv": [0.5, 0.5, 15.5, 15.5], "cullface": "down" },
                "up":    { "texture": "#all", "uv": [0.5, 0.5, 15.5, 15.5], "cullface": "up" },
                "north": { "texture": "#all", "uv": [0.5, 0.5, 15.5, 15.5], "cullface": "north" },
                "south": { "texture": "#all", "uv": [0.5, 0.5, 15.5, 15.5], "cullface": "south" },
                "west":  { "texture": "#all", "uv": [0.5, 0.5, 15.5, 15.5], "cullface": "west" },
                "east":  { "texture": "#all", "uv": [0.5, 0.5, 15.5, 15.5], "cullface": "east" }
            }
        }
    ]
}
```
You see, I have modified the UV to use floats; the UV reaches from 0.5 to 15.5 in both directions, so one should see the outer row of pixels being cut-off in half.

And that is indeed the case, here's how the dirt block looks in game:
![image](https://user-images.githubusercontent.com/21200815/66850316-d4fd6100-ef78-11e9-8422-5e4c2f913bed.png)

(Obviously I have only taken a .5 floating point step here for showcasing purposes, every floating point is allowed and registered by the Minecraft model system)
