### ISSUE TITLE
Dont receive email for password reset for my optifine account, help cant access my cape i bought

### ISSUE THREAD

**Issue by ScepterW** [sp614x/optifine#2708]
Whenever i request a password reset it says it has sent my an email for me to reset my password but this is the second time i have done this and i am 1000% i am not getting the email, i donated yesterday and i still havent gotten the password reset, help

**Comment by sp614x** [comment]
You can check your spam folder.
Some mail providers (outlook.com) like to silently drop messages without a trace.

**Comment by ScepterW** [comment]
You a fucking God, thanks bro, fml lmao
