### ISSUE TITLE
[Feature request] custom textures for every color of a CEM bed

### ISSUE THREAD

**Issue by Hallo89** [sp614x/optifine#2709]
Hey,
In the last few days, I have transferred my bed model from 1.11- to OptiFine's CEM system so that it can be used in 1.12+ again.
I think it looks kinda cool:
![image](https://user-images.githubusercontent.com/21200815/62246405-d55b7680-b3e3-11e9-80a9-d563e03d8f87.png)

Sadly, custom bed models can only have one fixed texture for its color, and having no colored beds is a huge drawback for most people. As you know, as it's an entity, resource packs can't control anything except the texture by default, so it would be amazing if you added a system to apply color to CEM beds again!

I'm thinking of something a bit like the custom GUI system, here is my proposal:

---
In optifine/cem, there's a file e.g. called "cem_bed_colors.property". The file contains properties of what texture is applied to what color of the bed, for example like this:
```properties
entity=bed
property=color
red=bed_red
blue=bed_blue
cyan=bed_cyan
...
```
Where `bed`, `bed_red`, `bed_blue`, etc. are .png files in the same folder of the .properties file or in subfolders when specified. I also thought that just throwing colors in the file is maybe a bit too specific, so I added a `property` trait to define what is being customized (But you can decide best on how the structure should look).
In the actual CEM model, one will define something like a `property` or `properties` property, in which a .property file is specified. This is then read and applied to the model part!
Example:
```
"texture": "bed",
"textureSize": [16, 16],
"property": "cem_bed_colors",
"boxes": [
   ...
]
```
A `"texture"` property still needs to be specified - it functions as the default texture if not all colors are specified in the .properties file and as fallback if the file cannot be read correctly.
I hope this helps a bit!

Cheers,
Hallo89

**Comment by Francy-Chan** [comment]
Actually you can do it, just don't specify the texture path, so it will use the default minecraft path.
Example:
![2019-10-24_14 58 05](https://user-images.githubusercontent.com/40085587/67507937-597d6d00-f666-11e9-87d6-3ec9e5aed2f4.png)
![image](https://user-images.githubusercontent.com/40085587/67508016-892c7500-f666-11e9-8a50-4cf2a2c8318c.png)

**Comment by Hallo89** [comment]
You deserve a price, my man.
Although it's still not as good as having separate configurable textures, I didn't think of the fact that custom entity models will take the Minecraft texture by default, even if it has multiple variants.
You are a genius, thanks so much!

I've actually already finished the new models:
![Colored bed models](https://user-images.githubusercontent.com/21200815/67519292-d4ff0e80-f6a6-11e9-8cf9-0e176d31578c.png)

Gonna close the issue, a solution, even if it's not the proposed one, has been found after all

**Comment by NitroCipher** [comment]
I believe this issue should be reopened. If a user is not using optifine, their bed textures will be entirely warped and distorted.

**Comment by NitroCipher** [comment]
The only way around that for a resource pack, is by having these changes in a separate addon pack

**Comment by Hallo89** [comment]
This is not true, the default UV does not have to be modified in any way.
The texture UV does not fill the whole 64x64 texture, so there is quite a bit unused space which one can use to add custom textures. That is, if one actually needs custom textures: I did in my case because the model is quite different from the default model, but in most cases one should be able to use the default texture

**Comment by Francy-Chan** [comment]
Correctly, I use that method for some custom mob models based on biome or variant, and it doesn't glitch without optifine.
