### ISSUE TITLE
Messed up textures when using VBOs

### ISSUE THREAD

**Issue by kalebsanders007** [sp614x/optifine#271]
The blocks appear rainbow when using VBOs in Optifine ONLY. VBOs work fine in Vanilla but not in Optifine, dunno why
![2016-09-25_12 52 37](https://cloud.githubusercontent.com/assets/16215326/18817143/0df3484a-831f-11e6-9910-032a3e3dfbaf.png)

**Comment by sp614x** [comment]
This is most probably a graphics driver problem. 
Some driveres have problems with VBO (crashes, broken textures, etc).

**Comment by mindforger** [comment]
wow that one reminds me of some funny graphic glitches in the old Turok Game XD

if you actually know the cause of this, can you make it a shader please?

**Comment by sp614x** [comment]
Driver issue
