### ISSUE TITLE
Corrupted player head data with loot tables in 1.14.4_HD_U_F2

### ISSUE THREAD

**Issue by MiSosumi** [sp614x/optifine#2710]
I have found a bug in **1.14.4 HD_U_F2**
___________
I get **corrupted player head data** when running a basic command from **[MinecraftPhi](https://github.com/MinecraftPhi/MinecraftPhi-modules/wiki/Player-Information)**

To be clear, the only difference between Minecraft versions used is Optifine, and the command works fine without Optifine.
___________
With Optifine = Default Steve head with corrupted data, in chest

Without = Actual player's head in chest
___________

The command is just:

`loot replace block 1 6 1 container.0 loot phi.playerinfo:get_head`

the contents of the **get_head.json** loot table are:

`{ "type": "minecraft:entity", "pools": [ { "rolls": 1, "entries": [ { "type": "minecraft:item", "name": "minecraft:player_head", "functions": [ { "function": "minecraft:fill_player_head", "entity": "this"}]}]}]}`

**Comment by sp614x** [comment]
No idea how this can be relevant to OptiFine.
Errors in the error log?

**Comment by MiSosumi** [comment]
I agree, it makes no sense. 
I will try to replicate it again when I get home

**Comment by MiSosumi** [comment]
The data for the player head was:
`setblock 4 6 1 minecraft:player_head[rotation=10]{Owner:{Id:"836c9316-3205-49b6-a454-22fb336a4b21",Properties:{textures:[{Value:"coWQTFMbX2k4WNMu0wB4gA2HiHJUl8vm6PCflgIugWOyBOuTM7WfzkDmEbxieHWcVVXi+EebtO+4D5ef8FPEpdH1HvahhTKzby7wkQpaoPmVb7dLe40pHqGot63IeLq1VbOFeLNTRiRp4cCqdGrqUh+TUfNR54SS/9ukw3ZgiCUbS+I776zTbHRhl7vbRAkPInba77g2uu7C9W1jJ6CyrrTYXXpKtjc+yBz4vTgfOE7+jjMdctvUUY5hkIvL7MO1fqreC7yQ98XdWp0CQq4Y73ItDaFHDSncxywOAshVk4VlYQtBYgc44OmqCNokCSyc2Q5r1vZ6h8lQPztm718OaE/hUkjtAqDCczc8lbDpf/eLvg5ayrrn8AYV8kVC1St8Bo2qYLaQ6A9n4ULxePqdTEvaihOwi1bPITnAqHTHHlUEyGTsWK9sfYZ+uG3mMD358Ekyr1g/Ej/OLKK/CEgLyzMBLzWHcjq2P1cfHRhykWzOZFxeIOOM0qhZvqJ3z0ZUmNlaKMrOoxcBymvuMU+Vx/NJwsqB3y79DZLWG697ZkxA5iVzLlx8OW9QdYUxDsGkgjNpzzNP+0km3DEzC32MMtPL5MSMV7kBKTyPY5cE/eg924nmrZtiILj8pywgtOJAMea5CSO99rsr6MpdCT2J2UkRtR8HgXBtxq3f+ifnJ9k=",Value:"eyJ0aW1lc3RhbXAiOjE1NjQ1NjAxMDgzNjYsInByb2ZpbGVJZCI6IjgzNmM5MzE2MzIwNTQ5YjZhNDU0MjJmYjMzNmE0YjIxIiwicHJvZmlsZU5hbWUiOiJaYW1wb25lIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9mODUwOWUwM2U0MjBhMWFhM2YzOGZjNTFlYTZmOGMzMDdiZDI2OWYyMjljOWI0NzY2NzU0M2UzNzQ3YmMyMDg0In19fQ=="}]},Name:"Zampone"}}`

When decoded the base64 has a lot of garbled mess before the usual texture information. but now at least the player head has my skin. 
_________

I tried it again in a fresh world and the corrupted data is gone but the head still shows with a default skin, then if I switch to vanilla the head renders correctly, then going back to Optifine all of those spawned heads now render correctly

I do not understand how or why this is happening.

I am very sorry to have wasted your time with what seems to more likely be a Minecraft bug.
There are no other mods running but I am thinking that the Optifine being loaded was purely coincidental. I can't see how data could be affected like that, but the guys in the discord who were helping me advised me to try these tests and post it as a bug.

Thank you for all your work on Optifine, without it I could not even play the vanilla game.
