### ISSUE TITLE
[Shaders] Red screen when viewing shaders on replay

### ISSUE THREAD

**Issue by Categorical6** [sp614x/optifine#2711]
Every time I turn my shaders on, it works perfectly fine in game when I use it. However, whenever I replay the footage, the screen turns completely red and black. (Mostly black, but if I shift my mouse to a certain angle I can only see bright red). If I leave the replay, my menu tab turns red. 
I am using 1.8.9

https://www.youtube.com/watch?v=uD2sKkoslX0&feature=youtu.be

Please help! Thanks

**Comment by sp614x** [comment]
Looks like a problem with the Replay Mod.
No idea how the Replay Mod works when shaders are enabled.
