### ISSUE TITLE
[1.12.2] Crash when entering Video Settings with Hardcore Darkness

### ISSUE THREAD

**Issue by Insane96** [sp614x/optifine#2713]
https://github.com/lumien231/Hardcore-Darkness/issues/37

I don't know if something can be done about this

**Comment by sp614x** [comment]
It looks like Hardcore Darkness is trying to patch GuiVideoSettings (probably to disable some options).
The Video Settings in OptiFine are organized in a different way. There is no optionsRowList (field_146501_h) and this is probably why the patch fails.
