### ISSUE TITLE
Allow shaders to accept arbitrary data streams as input.

### ISSUE THREAD

**Issue by chexo3** [sp614x/optifine#2716]
You’d still need to write code to pass the data stream to OptiFine, and get it into Minecraft somehow,  via Forge or as a tweakclass. The idea being that another mod could take some sort of input, like an audio signal from another program, or input from a light sensor connected to the computer, a file input, anything a Java program can interface with, can be used to create a data stream to control a shader’s behavior. For example, I could write code to take the audio output of a selected application, run some sort of transformation on it, and pass it to the shader to make a trippy audio sync effect. The idea being that OptiFine would only provide a handler to convert a Java data stream into input for the shader, and maybe recompile the shader with some new code, possibly via a special preprocessor macro.

**Comment by sp614x** [comment]
The shaders can already access non-standard data via Custom Uniforms:
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.properties#L324

Custom uniforms could be extended to accept external data, for example by adding a function `external(id)`.

The mod could call `net.optifine.shaders.Shaders.setExternalData(id, value)` to set the value.

**Comment by chexo3** [comment]
Could custom uniforms be used to accept a stream of data, rather than a value?

**Comment by sp614x** [comment]
How would a stream of data be useful?
Shaders render one frame at a time and the custom value should be more or less fixed while the frame is being rendered. Otherwise there would be all kind of bad effects, like half of the screen rendered brighter.

**Comment by chexo3** [comment]
I suppose it should sample the stream every frame. The main idea I had for this kind of feature was making an audio visualization shader possible.

**Comment by sp614x** [comment]
Streams and pipes (what you probably mean) are not made for things that should happen at specific times. Streams can't be sampled from time to time, ALL the values from the stream have to be read to get to the end of the stream.
If someone is writing 20k/sec in the pipe, someone else on the other side HAS to read 20k/sec or the pipe would overflow.
To do audio visualization a mod should wait for the frame start/end event and then update the custom uniform with the current value. If the sound manager is writing to a pipe, the mod has to organize reading from the pipe and updating the current value.

**Comment by chexo3** [comment]
Okay, that makes sense. The mod grabs some sort of data, (maybe audio data) performs some sort of computation on it, and then passes values to the shader.
