### ISSUE TITLE
Error joining servers with OptiFine C4_pre for 1.10.2

### ISSUE THREAD

**Issue by sp614x** [sp614x/optifine#272]
The player hangs in the air.
Error log: http://pastebin.com/chBsQFM6
OptiFine C3 works fine with all the mods.

**Comment by BBoldt** [comment]
Doesn't seem to be an issue with [my pack](https://minecraft.curseforge.com/projects/abridged). 
Using OptiFine C4_pre as it's required for that Extra Utils update(#285), no issues so far with Beta 4 of Abridged.
