### ISSUE TITLE
3d verification error

### ISSUE THREAD

**Issue by AzmeaL48** [sp614x/optifine#2720]
Hello
     Hello, I'm trying to donate OptiFine but everytimes i try i am getting 3d verification error i tried it about 25 times but i cant buy optifine. Can you please help me. I tried to buy it on: opera windows with anti-ad, opera android with anti ad and google chrome android without any add-onds

Is there a problem with paymentwall api etc.
and im using windows 7 sp1
amd mobility radeon 5470 hd
intel core i3 M370 @2.4 ghz

and im living in Mugla, Turkey

I recieved sms 25 times and i wrote the code 25 times

also i dont have any anti-virus softwares

just have logmein hamachi

**Comment by AzmeaL48** [comment]
Is there a problem with paymentwall api etc.
and im using windows 7 sp1
amd mobility radeon 5470 hd
intel i3 340 @2.4 ghz

and im living in Mugla, Turkey

**Comment by AzmeaL48** [comment]
I recieved sms 25 times and i wrote the code 25 times

**Comment by AzmeaL48** [comment]
also i dont have any anti-virus softwares

**Comment by AzmeaL48** [comment]
just have logmein hamachi

**Comment by AzmeaL48** [comment]
finally sorry for my bad english. english is not my main lang

**Comment by realjackasterisk** [comment]
You could've easily included all this information in your initial post instead of 5 separate comments

**Comment by AzmeaL48** [comment]
Ahh sorry for that

**Comment by AzmeaL48** [comment]
i updated it sorry

**Comment by sp614x** [comment]
You should contact Paymentwall or your bank, only they can fix this.
