### ISSUE TITLE
Optifine Installation Won't Start?

### ISSUE THREAD

**Issue by Leficent** [sp614x/optifine#2721]
I can't even start the Optifine installation because every time i click the version i want to install, it takes me to this page https://gyazo.com/7f181068d3eed2f0da67d62c3d3af907 and the download won't start. I've tried this on multiple browsers and other things download and install, but for whatever reason, Optifine won't. Help!

**Comment by Regnander** [comment]
Try this link: https://optifine.net/downloadx?f=OptiFine_1.14.4_HD_U_F2.jar&x=f92f2071b1d0838f536c12cddaca9bc3

**Comment by sp614x** [comment]
Disable your adblocker or use a better adblocker (uBlock Origin).
