### ISSUE TITLE
[1.14.4 HD F3] Water artifacts with stairs when Render Regions is ON

### ISSUE THREAD

**Issue by BoldStep** [sp614x/optifine#2724]
When I'm at a certain distance from stairs with water in it, it starts having artifacts. This only happens when Render Regions is on and stops after turning it back off. Shaders are always off with latest nvidia drivers.
![2019-08-05_20 54 28](https://user-images.githubusercontent.com/53684197/62460097-6bb4e100-b7c4-11e9-878a-37e71aafa6bb.png)
![2019-08-05_20 54 38](https://user-images.githubusercontent.com/53684197/62460109-753e4900-b7c4-11e9-910b-26f138db99b3.png)

CPU: Intel core i5 8600k
GPU: Geforce GTX 1080

**Comment by sp614x** [comment]
This is a vanilla bug which is amplified by Render Regions: https://bugs.mojang.com/browse/MC-127004
Relevant: #2627.
