### ISSUE TITLE
[1.12.2] Textures/Graphics Bug/Glitch

### ISSUE THREAD

**Issue by NickJonesLawsRBLX** [sp614x/optifine#2726]
So I redownloaded the download for 1.12.2 yesterday it was working fine then I go to get in the game today and the textures are messed up so bad that the game is not playable and without optifine, I can not play the game due to lag and when I play the game without optifine the game is fine I just can't play it due to lag 
![2019-08-05_13 03 40](https://user-images.githubusercontent.com/49010348/62485353-1526b300-b782-11e9-8c64-316d6ed7297e.png)
![2019-08-05_13 03 48](https://user-images.githubusercontent.com/49010348/62485354-1526b300-b782-11e9-8ffd-fafecfdc16fd.png)
![2019-08-05_13 03 52](https://user-images.githubusercontent.com/49010348/62485355-1526b300-b782-11e9-935f-dc103f7c2271.png)
![2019-08-05_13 04 20](https://user-images.githubusercontent.com/49010348/62485356-1526b300-b782-11e9-84ce-d15aa1c55dd3.png)

I will try a newer version.

**Comment by sp614x** [comment]
Are you using Fabric?

**Comment by Vexed01** [comment]
Fabric doesn't exist for 1.12.2, so I'll answer no for them.

**Comment by KaiAF** [comment]
No response from the author, if you are still having any issues, create a new issue, please.
