### ISSUE TITLE
Can optifine shaders be turned off for a certain dimension or world?

### ISSUE THREAD

**Issue by tuckerandlexus** [sp614x/optifine#2729]
Hi there. Can somebody please tell me if there is some way to turn shaders off for a particular world? The mod I am using isn't compatible and I would love to use both on my new server.  I am using Windows 10, Minecraft 1.12.2,, Optifine 1.12.2 HD U E3, Forge 1.12.2.14.23.5.2769. Thank you. 😊

**Comment by sp614x** [comment]
To turn off shaders for a specific dimension add an empty folder "shaders/worldN" to the shader pack, where N is the dimension id.

**Comment by derdiedasmelek** [comment]
Is there also a way to disable Optifine in a certain dimesion?
