### ISSUE TITLE
Custom Sky to check weather (rain, thunderstorm)

### ISSUE THREAD

**Issue by sp614x** [sp614x/optifine#273]
Hello, would it be possible one day to add a skybox that only appears when it's raining/snowing, and maybe one more for thunderstorms? A dark, cloudy sky would help immersion a lot, also because currently the custom colors for the sky mix with the vanilla gray background and the final result doesn't look rainy at all.

**Comment by ZephaniahNoah** [comment]
I'm excited for this feature. As of right now if you do add a custom sky to your resource pack and it starts raining your custom sky will disappear, being replaced with a dark colour.

**Comment by sp614x** [comment]
Updated preview B6 for 1.11.2.
Added Custom Sky option "raining": https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/sky.properties

**Comment by sp614x** [comment]
Updated preview B6 for 1.11.2.
Replaced option "raining" with option "weather=clear/rain/thunder", default is "clear".
