### ISSUE TITLE
Smart Animations does not take into account blocks in minecarts

### ISSUE THREAD

**Issue by Luke18033** [sp614x/optifine#2731]
Experienced in 1.14.4. As stated in the title, when Smart Animations are on, textures will not animate if the only place they are visible is on a block in a minecart. This can be seen by spawning a minecart containing a campfire (or any other animated block):
```
/summon minecart ~ ~ ~ {CustomDisplayTile:1,DisplayState:{Name:"campfire"},DisplayOffset:4}
```
Alternatively, this can also be seen if one of the standard minecart blocks (furnace, TNT, hopper) has an animated texture applied. In both cases, the texture will not animate unless it is also visible elsewhere. [Here](https://drive.google.com/open?id=1t6sm0nXfUxqUJIB4ySdv6DfLwGMl41dh) is a video demonstrating the bug. I've tested various other ways of displaying blocks/items (wearing on head, falling blocks, item frames) and nothing else has this issue as far as I can tell.

**Comment by sp614x** [comment]
Fixed, coming in next preview.
