### ISSUE TITLE
Optifine is slower than vanilla 

### ISSUE THREAD

**Issue by AlucardMBZ** [sp614x/optifine#2733]
on vanilla i get 160-400 fps on vanilla and 40-50 on optifine, ive tried messing with settings, changing ram usage, reseted the video settings, and nothing i do changes the fps, smooth fps is off. framerate is max.
can someone please help

**Comment by sp614x** [comment]
Running standalone or with Forge? Which OF version? Default or custom resource pack? Errors in error log?

**Comment by AlucardMBZ** [comment]
Standalone, anything past 1.13 has the problem, default, no errors visible

**Comment by sp614x** [comment]
Running with integrated or dedicated GPU?
It is shown on the debug screen F3.

**Comment by AlucardMBZ** [comment]
gpu

**Comment by sp614x** [comment]
Can you post F3 screenshots of vanilla and optifine?
