### ISSUE TITLE
Optifine Problem

### ISSUE THREAD

**Issue by OTAKU1733** [sp614x/optifine#2740]
in minecraft when i play optifine because of my bad pc i have low fps so i use optifine i had no problems but now i have a problem and its when i open the game and join my world or any server when i move or i just turn the mouse the fps drop tp 0/0 the game freeze
![Screenshot_209](https://user-images.githubusercontent.com/53883621/62667305-f80b0380-b97e-11e9-92ec-2ab47a23e861.png)
 i tried multiple versions like 1.14.3 and 1.14.4 and i have the same problem i tried to reset the video setting i tried to reinstall optifine i even tried to reinstall minecraft but still the same probelm
please help me and thanks

**Comment by realjackasterisk** [comment]
do you have smooth fps enabled

**Comment by OTAKU1733** [comment]
enabled or disabled i have this problem i tried them both : (

**Comment by sp614x** [comment]
Can you post an F3 screenshot and the error log (game output)?
Which is the last correctly working OptiFine version?

**Comment by KaiAF** [comment]
No response from the author.
