### ISSUE TITLE
Howto release and rebind shaders in Mods?

### ISSUE THREAD

**Issue by ben-mkiv** [sp614x/optifine#2744]
I'm currently struggling to make my mod compatible to Optifine with Shaders.

The Mod adds AR Glasses which can render into the world space/overlay, so should not be affected by shaders [screenshot](https://i.imgur.com/Fk6TBJw.png)

world elements get rendered to their own framebuffer in the RenderWorldLastEvent because depth testing is required. However shaders seem to use their own depth buffer and i couldnt figure out where its located (is there any way to access the depth buffer of optifine, or does it get flushed before RenderWorldLastEvent even fires?)

my other issue is that i cant figure out a way to set all required gl flags back so that other render methods would use the shaders as usual

this is what works for vanilla
```java
preRender(){
    myFramebuffer.bindFramebuffer(false);
    int depthBuffer = Minecraft.getMinecraft().getFramebuffer().depthBuffer;
    OpenGlHelper.glFramebufferRenderbuffer(OpenGlHelper.GL_FRAMEBUFFER, OpenGlHelper.GL_DEPTH_ATTACHMENT, OpenGlHelper.GL_RENDERBUFFER, depthBuffer);
}

postRender(){
        Minecraft.getMinecraft().getFramebuffer().bindFramebuffer(true);
}
```

this is the closest i could figure out to use with optifine (still getting log spam of this error, and no depth testing for my FB against real world depthBuffer)
```
[00:03:46] [Client thread/ERROR] [net.optifine.shaders.SMCLog]: [Shaders] OpenGL error: 1280 (Invalid enum), program: gbuffers_textured, at: pre-render CompositeFinal
```

```java

int optiFramebuffer;

preRender(){
        //store current FB in a global val
        optiFramebuffer = GL11.glGetInteger(OpenGlHelper.GL_FRAMEBUFFER);
        ARBShaderObjects.glUseProgramObjectARB(0);
        myFramebuffer.bindFramebuffer(false);
}

postRender(){
        //rebind the FB that was used before preRender()
        EXTFramebufferObject.glBindFramebufferEXT(OpenGlHelper.GL_FRAMEBUFFER, optiFramebuffer);
}
```

btw. caching the shader program id with `shaderObject = GL11.glGetInteger(ARBShaderObjects.GL_SHADER_OBJECT_ARB);` and restoring it after rendering, did not work at all (so i guess the shaderprogram is restored by optifine anyways but not all buffers/textures?

sorry for the long post, and any help is appreciated :)

**Comment by sp614x** [comment]
The shaders pipeline uses its own framebuffer, for more details see `net.optifine.shaders.Shaders.setupFrameBuffer()`.
The Forge's RenderWorldLast is called after terrain and before hand rendering. At this time the shaders framebuffer is still active and it is using the translucent layer program.

**Comment by ben-mkiv** [comment]
Thanks for your response, but i couldnt make any progress yet.

Isn't there an easy way for Mods which draw an overlay into the world to bypass the Shader programs while still having access to the worlds DepthBuffer?

**Comment by ben-mkiv** [comment]
closing this in favor of https://github.com/sp614x/optifine/issues/2959
