### ISSUE TITLE
My optifine was hacked by JammyOnToast!!!!!!

### ISSUE THREAD

**Issue by ItzFluker** [sp614x/optifine#2752]
Username: Itz_Fluker_

The cape was moved from "Itz_Fluker_" to "JammyOnToast" by the cape owner on 20.07.2562 16:58h.

You can recover the cape with your donation email.

WHAT IS THIS MY CAPE!!

**Comment by realjackasterisk** [comment]
> Q: **My cape was stolen! What do I do?**
> A: **Scan your computer, and change your passwords IMMEDIATELY.** This should at least include your Email account, your Minecraft/Mojang account, and your OptiFine.net account. Ideally, it should also be in that same order. All of this is to ensure no strangers have access to any of your relevant accounts. After the passwords have been updated, log in at https://optifine.net/login and simply update the username for the donator cape.

**Comment by ItzFluker** [comment]
He stole my id too.

**Comment by realjackasterisk** [comment]
what do you mean your ID?

**Comment by ItzFluker** [comment]
Donation Email

**Comment by ItzFluker** [comment]
I have to donate email again to move cape

**Comment by sp614x** [comment]
The donation email is the cape owner.
