### ISSUE TITLE
Not detecting and using SRV Records for servers

### ISSUE THREAD

**Issue by Vencorr** [sp614x/optifine#2756]
I've recently obtained a domain for my server and set up an SRV Record for _minecraft using Cloudflare to look at port 25584 since my port isn't the usual 25565.

I noticed that I was able to connect to mc.example.com if I had the port at the end, suggesting that the SRV record was not working. However, many other users were able to connect without the port, and it was found that most were using vanilla. Everyone who wasn't able to connect was using Optifine. Using just the address in vanilla gives the result, but Optifine needs to have a port to connect, suggesting that Optifine isn't using SRV records or atleast not Cloudflares.

My relevant records (without information):
Type | Name | Value | TTL | Proxy?
A | example.com | points to x.x.x.x | Automatic | No
SRV | _minecraft._tcp.example.com. | SRV 0 5 25584 example.com | Automatic | No

I've tested that this is still the case on 1.14.4 F4-pre2

**Comment by x1p** [comment]
Same here with both 1.14.4 F3 as the F4pre2.
Vanilla has no problems detecting SRV records.

**Comment by sp614x** [comment]
OptiFine is not changing how the server connection works. 
This is the relevant piece of vanilla code: https://pastebin.com/Bun7c6kS
However the OptiFine profile may be configured to use a different Java version, which could cause similar problems.
No idea how Cloudflare handles SRV records.

**Comment by irgendwr** [comment]
I'm also able to reproduce this issue with openJDK 12 and openJDK 10 on linux.

> OptiFine is not changing how the server connection works.
> However the OptiFine profile may be configured to use a different Java version, which could cause similar problems.

That does not seem to be the cause of this issue.
I've tested both vanilla 1.14.4 and OptiFine 1.14.4 HD U F3 (and F4pre5) with both of these java versions and **vanilla** is **always able** to resolve SRV records while **OptiFine** is **not**.

**Comment by BrilZliaN** [comment]
I'm able to reproduce this issue with OptiFine 1.15.2 HD U G1 pre9 and Java 11 (OpenJDK, Oracle, and Amazon Corretto). However, Java 8 and Optifine works just fine like Vanilla MC with every version of Java.

**Comment by Askalein1234** [comment]
Got the exact same problem with optifine, works just fine without it. Everything else is exactly the same, no special java args or anything like that. Using JRE 14 on Linux. Really recommend to reopen and investigate this as @starcraft66 suggested

**Comment by sp614x** [comment]
Should be fixed in 1.16.2 pre4.

**Comment by Askalein1234** [comment]
works for me
