### ISSUE TITLE
Optifine 1.14.4 crashes on startup

### ISSUE THREAD

**Issue by IronFootBoy1234** [sp614x/optifine#2759]
Minecraft gets to the main menu but crashes before the buttons (singleplayer, multiplayer, etc.) load, the game crashes. I try to view crash report but it doesn't do anything when I press it. The crash message just says:
ERROR
Game crashed
An unexpected issue occurred and the game has crashed. We’re sorry for the inconvenience.

**Comment by rynmss3** [comment]
So I had the EXACT SAME issue and I'm not sure if you're still struggling with this issue but I found out that I actually was doing everything right but my texture pack was what kept crashing my game when i tried to start minecraft up with optifine. I hope this helps you!

**Comment by sp614x** [comment]
A crash without report is usually in native code (java, libraries, drivers).
It could be triggered by resource pack features or shaders.
It can't be fixed without more details.
