### ISSUE TITLE
Custom 3D barrier world model loading for resource packs

### ISSUE THREAD

**Issue by insomniacUNDERSCORElemon** [sp614x/optifine#276]
Just by loading the barrier.json file from within ~/models/block/ should it be present.

If so, rendering should be simplified to that of a normal block (if possible) so multiple particles per barrier per second is not needed. Perhaps put on its own render layer/buffer whathaveyou so its display can be turned on and off rather quickly while the model mesh is still loaded, possibly have the mesh loaded until there is no longer a barrier in the hotbar for a considerable amount of time (to stop issues from arising from unloading/reloading a large amount of meshes at once, though it would be best to make sure they load closest to the player first and a bit of pacing if needed)

Though even without performance benefit, the real reasoning is better aesthetics and visibility.

![Imgur](http://i.imgur.com/w5mnsYh.png)

**Comment by sp614x** [comment]
Using a separate render layer is probably the best way, but it will require significant internal changes.
The Forge compatibility makes everything related to custom block models quite complex.

**Comment by insomniacUNDERSCORElemon** [comment]
Closing due to other issue
