### ISSUE TITLE
Optifine Verision Issue.

### ISSUE THREAD

**Issue by BuffBuffBuff** [sp614x/optifine#2766]
Minecraft keeps using newer version of Optifine for older version of Minecraft. I've been trying to use OptiFine_1.7.10_HD_U_E7 with 1.7.10 minecraft forge, but it keeps resulting in this error:

`[VersionManager] Refreshing versions locally...
[VersionManager] Versions has been refreshed (7 ms)
[Version:1.12.2-OptiFine_HD_U_E2] Resolving...
[Version:1.12.2-OptiFine_HD_U_E2] Inherits from 1.12.2
[Version:1.12.2-OptiFine_HD_U_E2] Resolving...
[Version:1.12.2-OptiFine_HD_U_E2] Inherits from 1.12.2
[Version:1.12.2-OptiFine_HD_U_E2] Resolving...
[Version:1.12.2-OptiFine_HD_U_E2] Inherits from 1.12.2
[Launcher] Launcher exited.
[Launcher] Minecraft closed with exit code: 1`

Removing 1.12.2_Optifine_HD_U_E2 and/or all 1.12.2 optifine versions while also force updating just results in this error instead:

`[VersionManager] Refreshing versions locally...
[VersionManager] Versions has been refreshed (7 ms)
[Launcher] Launcher exited.
[Launcher] Minecraft closed with exit code: 1`

**Comment by sp614x** [comment]
OptiFine is not refereshing anything.
If there is a problem it should be with the launcher.
