### ISSUE TITLE
Optifine Cape Stolen + Donation Email Deleted

### ISSUE THREAD

**Issue by doppiopio** [sp614x/optifine#2769]
Hi, sorry for contacting this way, I contacted OptiFine support a while ago but I got no response.
Anyways, I was wondering if it would be possible if you could change my email for my OptiFine donation cape, because it was stolen in 2018 by some random person. 
This would normally be a quick solution, however, my donation email as been deleted a long time ago.
![a](https://user-images.githubusercontent.com/54067724/62941974-a1884400-be1a-11e9-931a-37b87e718639.PNG)
If you could do something, that would be great,
Thanks.

**Comment by sp614x** [comment]
The donation email is the cape owner.
Changing the donation email is currently not possible.
