### ISSUE TITLE
Overlay Issue

### ISSUE THREAD

**Issue by dallin1016** [sp614x/optifine#2771]
So I'm trying to create an overlay where gravel overlays onto snow. However, it is not working at all.  I have every texture required. Both Gravel, and Snow have CTM that both work. Basically, the overlay is supposed to get rid of the border on the snow that is touching the gravel. The overlay works when I swap "snow" and "gravel" in the properties file, but it puts it on the gravel instead of the snow. 

Screenshots (1st, with properties file shown below, 2nd, with "snow" and "gravel" switched"):
https://imgur.com/a/Qlf5N0e

Properties file for the overlay:
`matchTiles=snow`
`method=overlay`
`tiles=0-16`
`connectTiles=gravel`

Resource Pack Link: https://www.dropbox.com/s/rhdocytoy35kwcg/OverlayIssue.zip?dl=1

**Comment by sp614x** [comment]
The block `snow` is the snow layer found in cold biomes.
The `snow_block` is the 1m high block of snow, usually crafted.
Overlays only work for full cube blocks, the snow layer is not a full cube block.

**Comment by dallin1016** [comment]
I am aware of that, I'm using "matchTiles" for snow, and even when switching it to "matchBlocks=snow_block" it still doesn't work.

**Comment by dallin1016** [comment]
I updated the link in the original post to be a minimal resource pack with only the appropriate textures and CTM/Overlay files

**Comment by dallin1016** [comment]
Any updates on this?

**Comment by dallin1016** [comment]
I've actually just found out the issue. The overlay did not come before the ctm in the load order. I moved the folder & renamed to have it come before alphabetically, and it works fine.
