### ISSUE TITLE
White dots when on fire

### ISSUE THREAD

**Issue by Ramere123** [sp614x/optifine#2773]
Might be a mojang issue... Noticed that white dots appear while on fire when using HD textures. Depending on the resource pack you get more or less. The weird thing is that the resource pack in the image doesn't even change the fire textures. Some seem to appear even with default textures but not nearly as many as with the 128x resource pack. Fullscreen seems to produce more of these. The screenshot provided doesn't show as many of the dots as there are when playing in fullscreen.

![Screenshot (7)](https://user-images.githubusercontent.com/54119251/63049647-d8755d00-bee1-11e9-878b-761380334580.png)
Link: [https://i.imgur.com/5aRUZ7a.png](https://i.imgur.com/5aRUZ7a.png)

The resource pack i used was "Vanilla PBR by h0ppip."
I got some with Sphax 128x as well, so it's not a resource pack problem, I don't think.

**Comment by sp614x** [comment]
Does it happen in vanilla?
