### ISSUE TITLE
Banner custom colors not working.

### ISSUE THREAD

**Issue by drzoidberg666** [sp614x/optifine#2777]
I am trying to change the lime banner color to #00ff00 to make it more vibrant using the color.properties file. It says on the template to change the map.lime because banners use that but it doesn't work. The map color changes but the banner does not. I have tried editing map.lime, dye.lime, collar,lime, sheep.lime, even text.code.10, all of which had no result on the banner.

**Comment by Mangaka-Nekori** [comment]
I am having this same issue, I'm working on a pack that's supposed to have a pastel color scheme and I can't get the banners or waypoints on the map to change.

**Comment by sp614x** [comment]
Fixed custom dye colors, the banners are using the dye colors and should work now.
Coming in next preview.
