### ISSUE TITLE
Smoother biome transitions

### ISSUE THREAD

**Issue by insomniacUNDERSCORElemon** [sp614x/optifine#278]
Have a biome color smoothing over 1 block rather than only 1 color per block.

New 'smooth biomes' setting within quality would change to 'off, smooth, smoother', smoother should likely be the default (I believe it was the default for MCpatcher and I don't remember performance complaints), aside from users with it off or already on automatic trigger of lower settings because of poor performance (if that's a thing?)

Example comparison:

![Mcpatcher/Optifine comparison](http://i.imgur.com/NcpgOLa.gif)

**Comment by sp614x** [comment]
The proper color transitions are a bit complex. Especially with non-cube models.
It is on the TODO list with lower priority.

**Comment by Jiingy** [comment]
This has been implemented into the base game by Mojang with the "biome blend" feature.

Is this still needed?

**Comment by insomniacUNDERSCORElemon** [comment]
@Jiingy I haven't played MC in _at least_ 4 years, so I don't know.

Doing a search looks like it though, so I'll close.
