### ISSUE TITLE
[1.12.2] Cinflict with Thaumcraft SunScorned

### ISSUE THREAD

**Issue by Skaphegor** [sp614x/optifine#2782]
When Optifine is present and this effect appears on the player, the screen immediately turns black. 

This appeared in log:
[net.minecraft.client.shader.ShaderManager]: Could not find uniform named InSev the specified shader program.
[net.minecraft.client.shader.ShaderManager]: Could not find uniform named Time in the specified shader program.
[net.minecraft.client.shader.ShaderManager]: Could not find uniform named ScreenSize in the specified shader program.

https://ftbwiki.org/Sun_Scorned

**Comment by sp614x** [comment]
Are you using shaders?
Is Fast Render enabled?

**Comment by NickelHub** [comment]
I use no shader.
Fast Render is enabled.

**Comment by NickelHub** [comment]
Thaumcraft has some shaders by itself. I turned off in the config after that.

**Comment by sp614x** [comment]
You can try with Fast Render disabled, it can conflict with some mods.

**Comment by KaiAF** [comment]
Is this still an issue?
