### ISSUE TITLE
Color issue with optifine, vanilla textures

### ISSUE THREAD

**Issue by JeffD76** [sp614x/optifine#2783]
Hello, I am having an issue with optifine changing the color of some sand based blocks (sand, sandstone, smooth sandstone) while leaving others unchanged (smooth sandstone slabs/stairs).  It is really jarring and I can't seem to figure out why it is doing this.  Have tried changing multiple setting to no avail.  This is for the latest version.  Here is a picture of what I am talking about.

https://imgur.com/yUUOcNO

**Comment by nenuvutive** [comment]
It feels like its the shaders doing that depending on the light sources (torches etc)

**Comment by JeffD76** [comment]
I am not using any shaders though?  And the recolor is only happening with sand based blocks.

**Comment by nenuvutive** [comment]
I see. I have no idea and I can't check myself at the moment though, sorry.

**Comment by JeffD76** [comment]
Just did a bit more testing, and the issue seems to be specifically tied to the desert biome.  My real issue is that the smooth variants of stairs and slabs retain the white look even when placed in a desert biome.  I would be fine if they took on the same orange hue as the rest of the sand based blocks.  Here is a picture of what I am talking about.
![2019-08-16_10 52 58](https://user-images.githubusercontent.com/54183922/63184227-1c687f00-c014-11e9-824f-c7f739fda4a9.png)

**Comment by nenuvutive** [comment]
Are you using any texture packs?

**Comment by nenuvutive** [comment]
> Are you using any texture packs?

I mean, if it's an already made on or one you made yourself

**Comment by JeffD76** [comment]
Okay, now I feel a bit dumb.  I originally switched from the texture pack I was using and just flipped to default (changed the order).  Now after removing the texture pack completely the issues is fixed.  So looks like I get to figure this out from the texture pack angle.  Thanks for forcing me to do some trouble shooting.  Any idea how I would find what is doing this in the texture pack?

**Comment by nenuvutive** [comment]
hmm, are you able to share the texture pack? that way i can look into the files

**Comment by JeffD76** [comment]
[JeffD John Smith Pack 1.14.3.zip](https://github.com/sp614x/optifine/files/3510469/JeffD.John.Smith.Pack.1.14.3.zip)

Here you go.

**Comment by JeffD76** [comment]
Slightly modified a couple of individual textures in the John Smith legacy pack

**Comment by nenuvutive** [comment]
alright, ill check it out

**Comment by JeffD76** [comment]
Thank you

**Comment by nenuvutive** [comment]
Got it, as I thought, it's the colormap.
If you go to `assets/minecraft/optifine/colormap/blocks` you'll notice a sand.png with sand.properties
those 2 files apply an orange-ish overlay on top of the sand on different biomes
that's what's making the sand orange in the desert and default on the plains

**Comment by JeffD76** [comment]
That is what I was thinking as well, so if i just remove those it should be fine?

**Comment by nenuvutive** [comment]
Yes, but you won't have the orange sand (and it looks like some icy sand(?) too)
![image](https://user-images.githubusercontent.com/52083832/63185129-763f6800-c059-11e9-8308-8533c8f1fe49.png)

If you want to keep it (for all biomes) then you'll just have to color that grid, or edit the texture itself

**Comment by JeffD76** [comment]
Cool.  I am fine with not having the orange sand, lol.  May mess with it later to see if I can change it.   Thanks again for the assist.

**Comment by nenuvutive** [comment]
Sure thing!
