### ISSUE TITLE
Wolf's custom models getting dyed 

### ISSUE THREAD

**Issue by DraminOver** [sp614x/optifine#2785]
When adding a model using CEM and selecting a custom texture, those textures behave exactly like the wolf_collar.png.
Will this also affect cat models when they get added to CEM?

**Comment by sp614x** [comment]
What do you mean with "behave exactly like the wolf_collar.png"?

**Comment by DraminOver** [comment]
they will have the same color as the collar ingame, and will be dyeable.

**Comment by DraminOver** [comment]
![2019-08-29_22 41 43](https://user-images.githubusercontent.com/21205057/63987362-473fe200-caae-11e9-9371-f408068b9e97.png)
I made a model and an exclusive texture for the eyes so that the wolf textures and the wolf eye's textures can be randomized individually. but they ended up looking like this

**Comment by ewanhowell5195** [comment]
wolf collars are now a separate model and this is now fixed
