### ISSUE TITLE
Strange lighting glitch with Shaders on Optifine 1.9.4-1.12.2

### ISSUE THREAD

**Issue by ChipLordTuttle** [sp614x/optifine#2788]
My friends are working on a Minecraft video project we plan on filming in 1.12.2, due to certain mods. While setting up the game environment, we've come across a big lighting glitch when we load Shaders with Optifine. The original shadows at the corners of blocks are no longer present. This effect takes the depth out of the scenery. I've attached pictures below that highlight what is happening. The pictures show the glitch while using SEUS 11.0, but the glitch persists no matter what shaderpack is used. 

This glitch popped up on Optifine 1.9.4 HD Ultra D7. It is not present in 1.9.4 HD Ultra B6 or the versions before it. The glitch persists through every newer version of Optifine for 1.9.4-1.12.2.  We've run the game without any other mods while testing this and have tried turning on the "Old Lighting" setting. We've also run the game on two separate computers with clean copies of Minecraft and Optifine. The first is a gaming laptop from 2015 with a NVIDIA GeForce GTX 970M graphics card. The second computer is brand new. It has a NVIDIA GeForce RTX 2060 Super. The glitch stays the same on both. 

We haven't seen anyone else post about this issue online, and we're assuming it's not a widespread glitch, but having it pop up on two unrelated computers is bizarre. Could this be a NVIDIA glitch? If there's any other information we can provide about the hardware or mod versions we used, I'd be happy to share. Thank you for your time and for any help you can provide. 

![Glitch](https://user-images.githubusercontent.com/54219100/63217141-7bea8b80-c0f5-11e9-90a0-62d61361bb8a.PNG)
![Normal](https://user-images.githubusercontent.com/54219100/63217142-7bea8b80-c0f5-11e9-93a0-011ed0efc0ff.PNG)

**Comment by Nixel1324** [comment]
Looks like the smooth lighting level is set to 0. Maybe it's a problem with vertex shading?

**Comment by sp614x** [comment]
Options -> Video Settings -> Smooth Lighting -> 100%
Options -> Video Settings -> Shaders -> Old Lighting -> Default

**Comment by ChipLordTuttle** [comment]
Thanks for the help. I recently asked some folks who work on shaderpacks
and they informed me that Optifine changed how they manage lighting in that
update. I don't think it looks nearly as good, but it is more accurate to
real lighting. It also looks a lot better with newer 3d packs.

Anyway, thanks for responding. I didn't think that post was even still
visable.
