### ISSUE TITLE
Optifine 1.14.4 crashing on startup

### ISSUE THREAD

**Issue by StickmenRocks** [sp614x/optifine#2789]
i have installed everything correctly but every time i start up minecraft the mojang screen loads, and then crashes before it can boot up the main menu. 
[crash-2019-08-17_16.35.02-client.txt](https://github.com/sp614x/optifine/files/3512459/crash-2019-08-17_16.35.02-client.txt)
I have attached the crash log

**Comment by Vencorr** [comment]
Based on crash log, the beacon texture has an invalid image size of 128x16, which suggests it either should be animated, or something is wrong with the image. And below, it seems you have a resource pack named jetcraft.zip that looks incompatible. Are you using that?

**Comment by StickmenRocks** [comment]
I was using it, yes. I switched to the normal texture pack and everything seems to be in order now. Oversight on my part, thanks for the response.

**Comment by Vencorr** [comment]
I think the last time a pack change took place was in 1.13 and they renamed a bunch of stuff and made previous packs pretty much non-functional. So unless you want to update it yourself, then I don't think so.
