### ISSUE TITLE
Incorrect lighting on slanted blocks from blockcraftery.

### ISSUE THREAD

**Issue by KokSaker** [sp614x/optifine#2792]
Hello. It's been suggested in https://github.com/MysticMods/Blockcraftery/issues/31#issuecomment-521746286 to report this issue here. Basically, the lighting renders as a gradient on sides of slanted block from blockcraftery when optifine is installed.
https://user-images.githubusercontent.com/49584508/58410511-01bce480-807b-11e9-8c98-ceaf6c841b1c.png
Notice the incorrect lighting not only on the slanted side of the block but also the regular flat side.

**Comment by sp614x** [comment]
Most probably because OptiFine disables the Forge Lighting Pipeline as it breaks way too many OptiFine features.
