### ISSUE TITLE
Random entity files still loaded after deletion in the texture pack

### ISSUE THREAD

**Issue by bambo1510** [sp614x/optifine#2794]
I don't know how to fix this or even if this is a problem with other people as well. 1.14.4 latest version and im working on a mashup texture pack. I downloaded some random entities off the internet and loaded it into a Minecraft world. I saw some of the textures were either ugly or weird and I deleted them from the texture pack. I can't seem to get those textures I just deleted to not show on the mobs. I tried toggling and untoggling random entities. I tried restarting Minecraft, unloading and reloading the texture pack but nothing will change those textures. I completly replaced the textures but the mobs won't change and those files that are loaded are non existent.

Edit: I tried to removing the mob files only, in this case wolf folder, then turned off the texture pack and switched it back and its still there. I also tried changing the mcmeta from 4 to 3 to 4. nothing. I also restarted my computer but nothing has changed, even cleared my trash bin and the files are non existent.

**Comment by sp614x** [comment]
Check in `assets/minecraft/textures/entity`, `assets/minecraft/optifine/random` and in `assets/minecraft/optifine/mob`.
If still not working check the error log to see from where they are being loaded.
