### ISSUE TITLE
Optifine Hangs on Startup Vanilla 1.14.4

### ISSUE THREAD

**Issue by WinMister332** [sp614x/optifine#2796]
When attempting to load Optifine (1.14.4_U_F2) In a vanilla environment with 3GB of ram allocated to the Java environment, Optifine seems to hang during initialization. I provided images (screenshots) as well as the log file below. As far as I'm aware there's nothing on my end that could be causing this issue. A 1.12.2 Version of optifine works fine, and native 1.14.4 runs perfectly fine (Minus lag and loss of frames that is) without issue.

So, I'd assume this is an issue on Optifine's end, however, I could be mistaken.

I await a response on this matter.

Thanks, A fellow Minecrafter and developer.

![image](https://user-images.githubusercontent.com/18247831/63363766-d4aa6600-c339-11e9-9bc4-64bc04186ce1.png)
![image](https://user-images.githubusercontent.com/18247831/63365193-c27df700-c33c-11e9-99f4-99bf0819d107.png)

[latest.log](https://github.com/sp614x/optifine/files/3521607/latest.log)
[latest.log (Hastebin)](https://hastebin.com/pikicakufe.md)

**Comment by MsWolphie** [comment]
Same issue here, never had the problem with previous versions, nothing wrong with the Vanilla version, but (re)loading Minecraft seems to take a looooong time with OptiFine_1.14.4_HD_U_F3.

It gets loaded in the end, but I personnally can't use Optifine with this issue (working on textures I'm regularly reloading the game, and I just can't wait 5-10 minutes each time I launch it or I'm reloading the textures.

![image](https://user-images.githubusercontent.com/49898596/63806603-3eb7a200-c91c-11e9-903c-2d73bef55f40.png)

**Comment by sp614x** [comment]
From the log file:
- 22:30:08 - start game
- 22:30:23 - start loading world
- 22:30:26 - player joined world
- 22:31:00 - player left the world (closed)

It took 17s from game start to loading the world, seems reasonable.

**Comment by MsWolphie** [comment]
Excuse me, but how is it closed or reasonable?

I mean, heh, 10 minutes to load the game in my case?

![image](https://user-images.githubusercontent.com/49898596/63975010-4c049600-caae-11e9-8b78-4884a8916cd4.png)

**Comment by WinMister332** [comment]
Mine didn't get passed the Mojang loading screen dispite what the log states. It gets up to reloading resources then stalls, I hardly call that reasonable.

**Comment by WinMister332** [comment]
it also returned at the bottom of my log, a class not defined erroe, and I ran with 3 gigs of ram, so it's definitely NOT a performance issue.

**Comment by sp614x** [comment]
The `latest.log` link above shows a game startup time of 17 sec.
Can you post the correct log file?

**Comment by WinMister332** [comment]
Me or MsWolphie?

**Comment by sp614x** [comment]
@WinMister332 The `latest.log` link in the first post shows a game startup time of 17 sec.
It also shows starting a single-player world, the player joining the world and then exiting the world.
If the log is not correct, then post a log that shows the problem.

**Comment by WinMister332** [comment]
I 'm not sure if it was the correct log, I was on 1.12.2 just prior to loading the 1.14.4 optifine. it's possible I grabbed that log by mistake. I'll grab the old one and even load a new one.

**Comment by WinMister332** [comment]
[latest-old.log](https://github.com/sp614x/optifine/files/3557544/latest-old.log)
[latest.log](https://github.com/sp614x/optifine/files/3557545/latest.log) < NEW

**Comment by WinMister332** [comment]
I think Hastebin is broken right now, I can't post anything. So I provided the raw files.

**Comment by WinMister332** [comment]
@sp614x ^- :)

**Comment by sp614x** [comment]
There is one minute between these two lines:
```
[17:14:31] [main/INFO]: Setting user: jollygoodboy
[17:15:26] [main/INFO]: LWJGL Version: 3.2.2 build 10
```
Have you tried with OptiFine F3 for 1.14.4?
Are you using the official launcher or a custom launcher?

**Comment by WinMister332** [comment]
Official Launcher. I have not tested F3. Even if something loaded it doesn't seem to get past the loading screen, and if it does it doesn't update the screen. At least not for me.
If you think it'll help I can test F3.

**Comment by sp614x** [comment]
It looks like the loading is not blocked, just very slow so it may take some time (10 min?).
No idea why.

**Comment by WinMister332** [comment]
I doubt it's a performance issue, especially since the amount of allocated RAM is 3G, but I'll test F3 maybe it just loaded weird in F2.

**Comment by MsWolphie** [comment]
My install is configured with 2 gigs of ram too,

and I have the F3 version, so, I don't think it's linked?

**Comment by sp614x** [comment]
@MsWolphie can you post your log file?
From the screenshot above I see that the parsing of each CIT properties file is taking 30sec, this is not normal.

**Comment by WinMister332** [comment]
I don't have an issue with F3 just F2 odd...

**Comment by MsWolphie** [comment]
Sorry for the delay, it was night time here

Here it is (it's not the same one but, yeah, doesn't really matter)

[latest.log](https://github.com/sp614x/optifine/files/3558948/latest.log)

**Comment by MsWolphie** [comment]
Ah, well, seems like the issue was on my side, apparently, something done wrong. Woops, I'm sorry for the inconvenience, it's all fine now

**Comment by sp614x** [comment]
Looks like F3 is now working for everyone.
