### ISSUE TITLE
Fullscreen on Mac doesn't change the resolution

### ISSUE THREAD

**Issue by scribbler957** [sp614x/optifine#2799]
When changing the fullscreen resolution on a Mac, the image (at the correct resolution) displays in the lower left and leaves the rest of the screen black. The mouse continues to move on the entire screen and the smaller picture responds proportionately (if the mouse cursor is in the middle of the physical screen, the buttons in the middle of the picture are highlighted.
I've seen other java games actually change the resolution when in full screen. Could this be fixed in Optifine?

**Comment by sp614x** [comment]
Looks like a problem with the LWJGL library.
Can't be fixed by OptiFine.
If you are using a Retina display there may be some OS configuration options (half-resolution) that could fix it.
