### ISSUE TITLE
Hand goes through in 1.12.2

### ISSUE THREAD

**Issue by usernameOS** [sp614x/optifine#2801]
With Fast Render Off
https://www.youtube.com/watch?v=u_zfoyDCvF4
WIth Fast Render On
https://www.youtube.com/watch?v=wGnj0Y6Q5VI

Minecraft 1.12.2 with mods on the latest version supported(HDUE3)

Any help?

i7-5500U
5gb RAM allocated
Geforce 920M
java 8u51

**Comment by canarslan12** [comment]
it is not related to optifine i think. it is related to some kind of realistic sky plugin you use

**Comment by sp614x** [comment]
Fast Render is designed for underpowered PCs and it probably has conflicts with some mods.
