### ISSUE TITLE
Grey Grass

### ISSUE THREAD

**Issue by ASweetOldMan** [sp614x/optifine#2804]
I've searched "grey grass" and "gray grass", but don't see any open issues.  After installing optifine, everything is normal.  However, after loading a 256x texture pack, the grass turns grey in most areas, but is still somewhat green in others (maybe swamp areas?).  Changing to another texture pack or back to vanilla does not correct the issue.  A full reinstall fixes the issue, but it returns after using the 256x texture pack with optifine.

**Comment by ASweetOldMan** [comment]
Something additional that may not be related:  I don't seem to be able to use normal maps with any texture packs.  I have tried with 3 or 4 different shaders, but no luck on any of them.

**Comment by sp614x** [comment]
Can you post a F3 screenshot and the error log (game output)?

**Comment by KaiAF** [comment]
No response from the author, if you are still having this issue, create a new bug report, please.
