### ISSUE TITLE
Light Blue Glass Missing Texture in 1.14.4_HD_U_F2

### ISSUE THREAD

**Issue by XeMurder** [sp614x/optifine#2805]
There appears to be a missing texture when light blue glass glass is specifically placed in the shape shown in the attached screenshot.
I have all my settings turned up to fancy, and connected textures on.

![2019-08-23_04 09 09](https://user-images.githubusercontent.com/26593522/63539668-f3894200-c55d-11e9-8c91-a62ff0820ec4.png)

**Comment by Regnander** [comment]
Have you tried 1.14.4 HD U F3? It seems like it's not an issue there.

![bild](https://user-images.githubusercontent.com/17113053/63715659-83700a00-c844-11e9-943b-5703c5142e83.png)

_(Yes, this is light blue glass - the sunset is making it look darker than what it is.)_
