### ISSUE TITLE
CIT model not loading in 1.8.9, working fine in 1.9 and above

### ISSUE THREAD

**Issue by orchidalloy** [sp614x/optifine#2807]
I have this model that is specified in a CIT properties file:
`{
	"parent": "item/generated",
	"textures": {
		"layer0": "image"
	},
	"display": {
		"gui": {
			"scale": [1.125, 1.125, 1.125]
		}
	}
}`
Using the latest Optifine versions, the above works perfectly in Minecraft 1.9 and above, correctly making the item texture a little bit bigger. It does absolutely nothing in Minecraft 1.8.9, however.

**Comment by sp614x** [comment]
OptiFine 1.8.9 and below don't have support for CIT models.
