### ISSUE TITLE
I can't donate to the optifine page.

### ISSUE THREAD

**Issue by jdroo** [sp614x/optifine#2808]
Im trying to donate to you guys, I choose credit/debit [I even tried the fast pay version as well] , entered my card, and then it asks for something I can't do... wtf is 3d-secure? I've never in my life ran into this... 

also... Why can't I use my paypal?

Also I live like 50 miles away from any major store to get a prepaid card just to donate 10$... 

![2oW1IZc](https://user-images.githubusercontent.com/13055804/63623607-9cb45480-c5bf-11e9-9e48-2abbf04356e9.png)

**Comment by sp614x** [comment]
You should contact Paymentwall directly, only they could fix this.
