### ISSUE TITLE
Overlays do not work on blocks that have slab and stair variants

### ISSUE THREAD

**Issue by Klautos** [sp614x/optifine#2810]
In 1.12 overlays would work from grass, sand, dirt, gravel etc. overlaying on top of cobble, stone, stone brick, wood planks etc..  In 1.14 overlays only work on blocks that do not have slab and stair variants.  Even if you're trying to overlay on a full cobble block and not the cobble stair for example, it will not work.

Will Optifine be fixing this issue soon?

I've read that there is a "difficult" way to make it work and I'm wondering what that is.  I have no fear of difficulty!

Thanks
-Klautos

**Comment by sp614x** [comment]
Overlays on cobblestone blocks should work.
Can you post a minimal resource pack reproducing the problem?

**Comment by KaiAF** [comment]
No reply from the author of the issue
