### ISSUE TITLE
Crash due to insufficient memory 

### ISSUE THREAD

**Issue by Aman07K** [sp614x/optifine#2813]
Whenever i open any world/server with just optifine(since 1.14.4) , the  game says java virtual machine has run out of memory. I agree i dont have a good pc but 1200Mb of memory is usually more than enough to play vanilla survival minecraft. Also this problem does NOT occur while using normal vanilla OR even forge with 1-2 light mods like voxelmap. If they can work i see no reason why optifine cannot. Also when i go back to main menu due to this memory issue and again join a world/srver the game just crashes. here is one of the reoprts. Please help. played minecraft with optifine on 1.12.2 and 1.13.2 and also early 1.14

[crash-2019-08-25_11.06.07-client.txt](https://github.com/sp614x/optifine/files/3537883/crash-2019-08-25_11.06.07-client.txt)

**Comment by sp614x** [comment]
Does it work without a resource pack?
You can reduce the memory usage by reducing the render distance.
Is the OptiFine profile in the launcher using the same memory limit as vanilla?

**Comment by KaiAF** [comment]
No response from author
