### ISSUE TITLE
CTM in 1.12.2 on game start doesn't work properly

### ISSUE THREAD

**Issue by Darsenia** [sp614x/optifine#2816]
Optifine 1.12.2 HD U E3
Minecraft Forge 14.23.5.2814

CTM doesn't work after world/game restart,needs a refresh(apply resoursepack again, or toggle connected textures on/of,f or alternative blocks on/off etc).
I'm making a small resoursepack with biome-specific textures, colormaps etc work fine,ctm for leaves and plants doesn't.There are no capital letters anywhere(except biomes names).Here are ctm properties settings:

**- leaves2.properties**
method=fixed
tiles=1
matchBlocks=leaves2:0,1,4,5,8,9,12,13
biomes=ColdTaiga ColdTaigaHills
**- leaves.properties**
method=fixed
tiles=0
matchBlocks=leaves:0,2,3,4,6,7,10,11,12,14,8,15
biomes=ColdTaiga  ColdTaigaHills
**- fern.properties**
method=fixed
tiles=3
matchBlocks=31:2
biomes=ColdTaiga ColdTaigaHills
**- grass.properties**
method=fixed
tiles=2
matchBlocks=31:1
biomes=ColdTaiga ColdTaigaHills
**- largeferntop.properties**
method=fixed
tiles=5
matchTiles=double_plant_fern_top
biomes=ColdTaiga ColdTaigaHills 
**- largefernbot.properties**
method=fixed
tiles=4
matchTiles=double_plant_fern_bottom
biomes=ColdTaiga ColdTaigaHills

**Comment by Regnander** [comment]
Can you upload your resource pack so I (or someone else) can take a closer look at it?

**Comment by Darsenia** [comment]
I don't think that it would make any sense-I'm making it as an addition to my work-in-progress Open Terrain Generator biome pack,so it will be either not working correctly on vanilla (CTM is applying over OTG biome colors options),or not working at all (colormaps for custom OTG biomes).
As I said, colormaps for custom OTG biomes work fine. CTM- as for right now I'm just trying to make grassy things(tallgrass,double tallgrass,fern,large fern) and leaves(except spruce) in snowy biomes white.So those tiles from properties above are just slightly brightened vanilla textures.

**Comment by Darsenia** [comment]
However,I've just found,that similar features work correctly for 3DSeasons Winter resoursepack.So it's not an Optifine issue,just mine...I'll try to find,what i'm doing wrong:-)

**Comment by Darsenia** [comment]
[traveller's dream.zip](https://github.com/sp614x/optifine/files/3543024/traveller.s.dream.zip)

**Comment by Darsenia** [comment]
[traveller's dream.zip](https://github.com/sp614x/optifine/files/3543046/traveller.s.dream.zip)

**Comment by Darsenia** [comment]
I also have the same problem with other resousepack,which uses similar methods:
https://www.reddit.com/r/Minecraft/comments/61v6zz/biome_specific_stone_done_with_resource_pack/

**Comment by Darsenia** [comment]
Well,it's not funny( I tried Conquest 1.12.2,the same! Soo it's not the fault of my poor textures.

**Comment by Darsenia** [comment]
I found some information about issues with Conquest ctm and BiomeBundle(also OTG pack).And there is a post about the difference in biome registering between vanilla and OTG:
https://github.com/PG85/OpenTerrainGenerator/issues/300#issue-483143496
Maybe it's the reason why CTM is not working=(
Without OTG all is Ok.
