### ISSUE TITLE
Certain Layers of armor and body not loading when in Inventory

### ISSUE THREAD

**Issue by TekkStorm** [sp614x/optifine#2818]
What happens is when you aren't holding a block or an item in the last 4-5 slots of the hotbar, going into the inventory makes your character model lose some layers and the armor will lose some layers too. Hope this gets fixed.
![Screenshot_15](https://user-images.githubusercontent.com/54512114/63655211-76272280-c753-11e9-9cef-a586c00d7df1.png)
That is what happens. And player heads, weapons, and many other items in the last slots still won't fix the bug.

**Comment by sp614x** [comment]
Is this also happening in vanilla?

**Comment by KaiAF** [comment]
No reply from the author, assume it's fixed now.
