### ISSUE TITLE
Crashing randomly 

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [sp614x/optifine#282]
https://gist.github.com/anonymous/07e092c07d152b2732ae26dc5f4f7847

**Comment by sp614x** [comment]
It crashes at: "CookingPlus.blocks.CookingPlusCustomRopeCrop.checkRopeStatus()"
Not related to OptiFine.

**Comment by mindforger** [comment]
https://github.com/mrmoeman/CookingPlus/issues/3
