### ISSUE TITLE
Optifine account stolen

### ISSUE THREAD

**Issue by straykxxs** [sp614x/optifine#2820]
hello! 
firstly, sorry for my english, i'm brazilian. 
okay, i donated to optifine at the day 05/01/2016. at 2017, i stopped playing minecraft for a while, so i really don't cared about nothing in it because i was focused on school and it taked all my time. these days, i'm back on playing with my friends. i suddently remembered about my cape and i went to search about it. i opened optifine's site and tried to put my email on login, and was saying that was incorrect. later, i downloaded optifine again and when i tried to play with the cape, i couldn't. i tried to change how it was the style of it and i was redirectioned to the optifine's site again, saying this: http://prntscr.com/oxhomo
i again tried to recover it and when i put on the right email and account, it showed me this: http://prntscr.com/oxhqki

i already send a email to optifine, but they are not answering me. i'm really worried because of this. US$10 is a really big quantity on my country and i don't want this to be a waste of money. can someone help me, please? :(

**Comment by Vexed01** [comment]
The only thing I can say is what's in [#faq](https://canary.discordapp.com/channels/423430686880301056/531622141393764352/609545737939714068) in the Discord server ([invite link](https://discord.gg/3mMpcwW)).

![image](https://user-images.githubusercontent.com/51716387/64050507-2770f280-cb70-11e9-8006-dc00ddba96d5.png)

You are unable to change the donation email.

**Comment by straykxxs** [comment]
> The only thing I can say is what's in [#faq](https://canary.discordapp.com/channels/423430686880301056/531622141393764352/609545737939714068) in the Discord server ([invite link](https://discord.gg/3mMpcwW)).
> 
> ![image](https://user-images.githubusercontent.com/51716387/64050507-2770f280-cb70-11e9-8006-dc00ddba96d5.png)
> 
> You are unable to change the donation email.

but can i change the e-mail without remembering the old one? :(

**Comment by sp614x** [comment]
The donator email is "znekagamer@gmail.com".
