### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by Mantas4682** [sp614x/optifine#2824]
Opening **OptiFine_1.14.4_HD_U_F3.jar** with **Java(TM) Platform SE Binary (java.exe)** flashes the command prompt for a split second without any text and just closes. Nothing happens, nothing gets installed, the process just disappears.

**Comment by sp614x** [comment]
You can try JarFix:
https://download.cnet.com/Jarfix/3000-18512_4-77571216.html
If still not working you can reinstall java.
