### ISSUE TITLE
Anistropic filtering kills framerate

### ISSUE THREAD

**Issue by ProNoob135** [sp614x/optifine#2829]
In games like Portal 2 I can turn anistropic filtering to 16x with almost no performance impact(even on my crappy laptop). However, in Optifine, an anistropy level of just 2x takes my framerate from 60(vsync) to 7, on a desktop with a GTX 950. Is this something to do with the number of textures in minecraft or another limitation? I'm curious.

**Comment by Chocotea92** [comment]
Try to enable synchronization in the settings of the video card, and not in the game. Write how many frames per second you have now.

**Comment by sp614x** [comment]
The vanilla render engine is not compatible with anisotropic filtering and antialiasing (AF/AA).
To enable AF OptiFine has to use a different rendering mode which is not so efficient, but which can be used with AF and AA.
