### ISSUE TITLE
No "Chunk Loading" option in any optifine version I install

### ISSUE THREAD

**Issue by MrMortman** [sp614x/optifine#2830]
Hi,

I dont have the option do change the Chunk loading  option to Multi core anymore.
That option doesnt even exist, no matter what version I'm using.
I'm pretty sure that I had it just a wek ago, but I had to reinstall windows and now after I installed optifine again it isnt there anymore (and I was using the same installer).
I was using the newest version 1.14.4 and I tried 1.8.9 on which I want to play too.

**Comment by sp614x** [comment]
The vanilla chunk loading was switched to multithreaded long time ago.
The option is not needed anymore.

**Comment by MrMortman** [comment]
Oh Thanks for the answer. I was really thinking that I still hat that option last week.
It might have been just my imagination ^^.
