### ISSUE TITLE
My cape has been stoled

### ISSUE THREAD

**Issue by MrGuille** [sp614x/optifine#2833]
The problem is that my optifine cape was stolen, and I don't remember my donation email, how can I know which one it was? or if someone can tell me what it is
I have tried request password with all my emails and none is, I would like to change it to my main email, can someone help me?
Sorry for my english.
![ba276ee3a28a4553075d0403aa3201ab](https://user-images.githubusercontent.com/27928363/64057481-b92e2f00-cb73-11e9-8ecf-4acfe9da868a.png)

**Comment by Studio528-real** [comment]
you can not change your donation email

**Comment by sp614x** [comment]
The donation email is "emigas2001@gmail.com".
