### ISSUE TITLE
Cannot log into account.

### ISSUE THREAD

**Issue by Archiekel** [sp614x/optifine#2837]
A month or more ago I transferred my accounts cape from Karchie to my new account Karchie2.
Yesterday I change my name from Karchie2 to Barchie and now I can't log into the Optifine website. Attempting to log into the Optifine website gives me: "Invalid username or password.
Please login with your donation email and the password sent to your donation email."
I've tried to log into both the email I used for Karchie and the email I used for Barchie to no avail.
I have reset both Mojang passwords in attempt to fix this but that also didn't work.
Clicking the request password and prompt to use my donation email also just says: "No donation found from email" for both emails. I can reach and edit my cape through Minecraft skin customization but can't log in.
I'll give my emails and details on request when this is seen

Thanks in advance.

**Comment by Studio528-real** [comment]
you dont login with minecraft accounts anymore, if you donated with same email as your Karchie account then request a new *optifine* password, if its a different email do the same thing for that email

**Comment by sp614x** [comment]
The donation email is "pamkaykelly@gmail.com".
