### ISSUE TITLE
Won't Let Me Donate

### ISSUE THREAD

**Issue by BoysPickFlowers** [sp614x/optifine#2843]
I keep trying to donate for a cape but every time I do, it says there is an internal error or that my card cannot be read. It validates that it is a real card but it just won't go through.
User: _JE_

**Comment by Studio528-real** [comment]
contact your bank or let them call you and tell them its you and let it through

**Comment by BoysPickFlowers** [comment]
Its a pre-paid gift card

**Comment by Studio528-real** [comment]
for some reason paymentwall doent like those

**Comment by BoysPickFlowers** [comment]
Is there anything I can do then?

**Comment by sp614x** [comment]
You should contact Paymentwall diectly, only they can fix it.
