### ISSUE TITLE
crash with Extra Utilities, Random Thins and Flat Colored Blocks

### ISSUE THREAD

**Issue by Hypsellis** [sp614x/optifine#285]
I link these issues here because it seems that Optifine is linked to these issues.
https://github.com/lumien231/Random-Things/issues/142
https://github.com/AlgorithmX2/FlatColoredBlocks/issues/24

**Comment by sp614x** [comment]
Found the problem, it only happens with mods which use delayed sprite registration.
Updated preview OptiFine C4 with a bugfix.

**Comment by sp614x** [comment]
Resolved

**Comment by Hypsellis** [comment]
When will you publish the C4 preview ?
