### ISSUE TITLE
"gbuffers_entities_glowing" Isn't in being used in internal shaders

### ISSUE THREAD

**Issue by ZeLalo** [sp614x/optifine#2850]
![example of bug](https://user-images.githubusercontent.com/46088020/64190527-e4b46080-ce76-11e9-8e0a-65fc0eb8aaf7.png)

Version used: 1.14.4 HD U F4 pre3
The left of this screenshot is with the internal shaders and the right part is with no shaders. Same issue is present when using anti aliasing without shaders.

**Comment by sp614x** [comment]
The glowing (spectral) effect is not compatible with shaders and Fast Render.
