### ISSUE TITLE
OptiFine_1.14.4_HD_U_F3 won't install

### ISSUE THREAD

**Issue by cormiiiii** [sp614x/optifine#2851]
when i try to open it, a blank command prompt window displays for a split second before closing. nothing else happens. i've tried reinstalling java and adding an exception to my AV (was a stretch smh), and neither worked. i don't think there are any logs or whatever that it's leaving, it just seems to be doing nothing.

**Comment by Cyphall** [comment]
To get the error message, run a Command Prompt manually and execute the jar with the command "java -jar NameOfOptifineFile.jar"

**Comment by cormiiiii** [comment]
> To get the error message, run a Command Prompt manually and execute the jar with the command "java -jar NameOfOptifineFile.jar"

i ran that, and ended up with this:
C:\Users\c****>java -jar OptiFine_1.14.4_HD_U_F3.jar
Error: Unable to access jarfile OptiFine_1.14.4_HD_U_F3.jar

**Comment by Cyphall** [comment]
You need to set the working directory to be the one where the jar file is, using the CD command, before running it with the previous command.
Example: "cd C:\Users\YOURUSERNAME\Downloads" if it is located in your Download folder.

**Comment by cormiiiii** [comment]
i was able to install it after reinstalling java, going to the folder (using cd) and running java from there.
