### ISSUE TITLE
[preview_OptiFine_1.14.4_HD_U_F4_pre3] [w/ Forge 28.0.92] The game crashed whilst rendering overlay - but WORKS w/ Forge 28.0.91

### ISSUE THREAD

**Issue by Kovsian** [sp614x/optifine#2855]
OptiFine is installed as a Mod on Forge 28.0.92
**Error: java.lang.NoSuchMethodError: net.minecraftforge.common.model.ITransformation.rotate(Lnet/minecraft/util/Direction;)Lnet/minecraft/util/Direction;** - (something wrong with this _.rotate(Lnet/minecraft/util/Direction;)Lnet/minecraft/util/Direction;_ got duplicated , probably?)
Crash report: [crash-2019-09-05_19.02.41-client.txt](https://github.com/sp614x/optifine/files/3580181/crash-2019-09-05_19.02.41-client.txt)
After updating Forge from _1.14.4-forge-28.0.91_  to _1.14.4-forge-28.0.92_ I'm getting constant crash with the same exact error. Rollback to forge-28.0.91 helps me.
Any fixes for upcoming Forge versions?

**Comment by Cr4fTJuNkiE** [comment]
Just came here to report same thing.
And no, Forge isn't gonna change anything. They change things and Optilad plays "catch up."

**Comment by AlaDyn172** [comment]
Same for me

**Comment by jackmawer** [comment]
Just confirming that this is the case, if it was somehow still in doubt.
The Forge guys are really dropping the ball recently...

**Comment by MaxwellRU** [comment]
same with Forge 1.14.4-28.0.93

**Comment by Cyphall** [comment]
With the obfuscation mapping released by Mojang, Forge devs changed some method's names to match the official ones which means mods using these methods will need to update the name used when calling them.
This is pretty obvious with the NoSuchMethodError exception.

**Comment by sp614x** [comment]
OptiFine 1.14.4_HD_U_F4_pre4
 - compatible with Forge 28.0.93

**Comment by mrcoffee1026** [comment]
That version opti + that version forge == the exact same error: 
The game crashed whilst unexpected error
Error: java.lang.NoSuchMethodError: net.minecraft.entity.Entity.getEntityData()Lnet/minecraft/nbt/CompoundNBT;

**Comment by mrcoffee1026** [comment]
what forge version was pre2 supposed to have been compatible with?  after attempting an update of forge I can no longer find a version combination that does not produce this error.

**Comment by Cyphall** [comment]
@mrcoffee1026 Latest Forge version (28.0.102) with latest Optifine preview (F4 pre4) is working fine for me.

**Comment by mrcoffee1026** [comment]
I get this error when joining a server with that version combination:
The game crashed whilst unexpected error
Error: java.lang.NoSuchMethodError: net.minecraft.entity.Entity.getEntityData()Lnet/minecraft/nbt/CompoundNBT;
It happens later than it does with the other suggested version combination but still happens.  I've been having no trouble as long as I revert to forge version 1.14.4-forge-28.0.90 and optifine F4pre3, but updating either gives me this error every time.

**Comment by codingneko** [comment]
Still getting this error with F4 pre 4 and forge 28.1.1 (and 28.1.10)

**Comment by mrcoffee1026** [comment]
Same, having this on connect with server that has a resource pack specified in server properties (sh1 also specified, I don't know if this has any effect).  I can only assume that servers that do not specify a resource pack don't cause mc to crash on every attempt to connect to it since no additional release has been produced and there are not a billion other people saying they have the same issue here.

**Comment by mrcoffee1026** [comment]
Still happening with new version
OptiFine 1.14.4 HD U F4 pre5 with Forge 28.0.93 (version stated to be compatible in changelog). 

Joining world... First progress bar shows until about 20% and then:
```
The game crashed whilst unexpected error
Error: java.lang.NoSuchMethodError: net.minecraft.entity.Entity.getEntityData()Lnet/minecraft/nbt/CompoundNBT;
```

**Comment by Sergio823** [comment]
I saw the changelog, try using the Forge Version 28.0.23, it is because the optifine works with very specific versions of Forge in the case of the newest version of Optifine, is the forge 28.0.23. It is in the Changelog

**Comment by mrcoffee1026** [comment]
The changelog specifically states to use forge version 28.0.93 (opti F4 pre5, not opti F3), , NOT 28.0.23.  Again, the workaround was to downgrade to forge 28.0.90 and opti F4 pre3, not roll all the way down to 28.9.23.
