### ISSUE TITLE
OF crashes with Forge 1.14.4-28.0.92.

### ISSUE THREAD

**Issue by Cr4fTJuNkiE** [sp614x/optifine#2857]
* Crash Log ---> https://www.dropbox.com/s/qlwiuqsa0oua30o/crash-2019-09-05_18.45.14-client.txt?dl=0 <---- Crash Log*

 

Just Forge 1.14.4-28.0.92 and Optifine. No other mods. Doesn't happen in 1.14.4-28.0.91 Or earlier..? 
Forge Gods sent me your way. Optilad to the rescue...?

**Comment by Studio528-real** [comment]
#2855

**Comment by sp614x** [comment]
OptiFine 1.14.4_HD_U_F4_pre4
 - compatible with Forge 28.0.93
