### ISSUE TITLE
Optifine Crash on Luanch

### ISSUE THREAD

**Issue by popps73x** [sp614x/optifine#286]
Having an issue with optifine crashing packs on launch.

Pack is Hades Effect available on curse v1.8.7 (also happens with Hermitpack)

I disabled the following mods and the pack will launch without issue.

tconstruct 1.10.2 2.5.3
tinkers addons 1.10.x 1.0.3

this is the crash report from the full pack

https://www.dropbox.com/s/yfzlaggkk4u6cf8/crash-2016-10-10_08.56.51-client%20optifine%20crash.txt?dl=0

I believe forge was also updated between version 1.8.5 of hades effect (worked without any problem) and version 1.8.6 and 1.8.7 where i have had this issue.

Thanks for any help you can provide and thank you for the great mod.

**Comment by popps73x** [comment]
updated to tinkers 2.5.5 same/similar crash

https://www.dropbox.com/s/8uaqv5j7fv41n5h/crash-2016-10-10_08.56.51-client%20optifine%20crash%20and%20tink%202.5.5.txt?dl=0

**Comment by sp614x** [comment]
The crash is inside TConstruct, not related to Optifine:

=
java.lang.NullPointerException: Initializing game
	at **slimeknights.tconstruct.library.client.model.MaterialModel.bakeIt**(MaterialModel.java:75)
	at slimeknights.tconstruct.library.client.model.MaterialModel.bake(MaterialModel.java:51)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:182)

**Comment by popps73x** [comment]
thanks i will resubmit to tinkers.

**Comment by bonii-xx** [comment]
The crash happens because all the textures which are created [on texture stitching](https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/slimeknights/tconstruct/library/client/CustomTextureCreator.java#L95) are missing. I don't know what you're doing, but you're obviously causing it to not fire or be called in a wrong order or something. So no, this one is on you. ;o

**Comment by bonii-xx** [comment]
Note that this started happening once the data that is used to generate those textures was outsourced to json. They're loaded at postinit and the models aren't getting baked before that.

**Comment by sp614x** [comment]
You can try with the preview OptiFine C4, it should be compatible with latest Forge version.

**Comment by sp614x** [comment]
Tested Minecraft 1.10.2 + Forge #2099 + OptiFine C4 (preview) + TConstruct 2.5.5 + Tinkers Addons 1.0.3.
It does not crash and seems to work properly: http://i.imgur.com/DKIUhxm.png

**Comment by sp614x** [comment]
OptiFine C3 also does not crash. 
The crash may be dependant on several mods being installed. The problematic mods have to be isolated before it can be fixed.

**Comment by sp614x** [comment]
A similar bug was fixed, can you test it again with latest preview OptiFine C4 for 1.10.2?

**Comment by popps73x** [comment]
tested with 
Hades Effect 1.8.7
Hades Effect 1.8.7 (updated forge 2099 and tinkers 2.5.5)
Hermit pack 1.0.1
and a developmental pack.

All loaded and played without any issue.

Thank you for all your help.  :)  Love optifine and i hope you keep up the great work.
