### ISSUE TITLE
payments with fasterpay and direct debit don't work

### ISSUE THREAD

**Issue by FI3RYPHE0NIX11** [sp614x/optifine#2861]
im a long time user and i decided to donate. when i attempted purchasing with fasterpay, it was an infinite loading button when i pressed pay. when i tried to verify my debit card via visa card (not fasterpay) it keeps being declined.

**Comment by Vexed01** [comment]
This is an issue with FasterPay/Paymentwall/your bank. Contacting them is the only way to have this resolved.

**Comment by sp614x** [comment]
You should contact Paymentwall directly to solve this.

**Comment by FI3RYPHE0NIX11** [comment]
Ok thanks
