### ISSUE TITLE
I cannot install optifine on my windows 10 64 bit integer system.

### ISSUE THREAD

**Issue by NerfyZygon** [sp614x/optifine#2863]
the error reads as follows; 'the program or feature optifine-1.14.4-i1.exe cannot start or run due to incompatibility with 64-bit versions of windows. please contact the software vendor to ask if a 64-bit windows compatible version is abailable.'

I got windows 10 64 bit. and java 64 bit.

**Comment by SetantaLP** [comment]
As far as I know you can only download jar-files on the [official download page]( https://optifine.net/downloads), so where did you downloaded the installer?

**Comment by sp614x** [comment]
OptiFine is not available for download as EXE, only as JAR file on https://optifine.net/downloads.
Scan your computer for malware.

**Comment by NerfyZygon** [comment]
https://www.topminecraftmods.com/optifine-mod/download/?version=1.14.4&build=I1 this was the url. sorry for bothering, I didnt check if it was the real site or not. thanks for the help!
