### ISSUE TITLE
Optifine crash

### ISSUE THREAD

**Issue by FriedrichH** [sp614x/optifine#2878]
Hi,

I installed OptiFine 1.14.4 HD U F3.
It starts the game but within 1 minute of playing the game crashes. Sometimes it crashes my PC to a bluescreen.

I hope someone can help me out. Cheers!

[Latest.log](https://github.com/sp614x/optifine/files/3609070/Latest.log)

**Comment by FMHikari** [comment]
It seems the game is having problems reading your World's files, level.dat specifically, and with Mojang's authentication. This doesn't seem Optifine related though.

Here's the cut text from the errors:

" [Server thread/ERROR]: Exception reading C:\Users\YourUserName\AppData\Roaming\.minecraft\saves\Stranglethorn\level.dat
m: Loading NBT data "

" [22:33:43] [main/WARN]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@7b65c71a[id=a7e7b839-ebc9-3e77-a78a-c3eed46f86bb,name=abb3_1337,properties={},legacy=false]
com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time "

**Comment by sp614x** [comment]
The game save files are corrupted.
Not related to OptiFine.
