### ISSUE TITLE
Glass panes should use top texture for unconnected edges

### ISSUE THREAD

**Issue by muzikbike** [sp614x/optifine#2881]
Currently this is what iron bars edges look like:

![2019-09-14_12 51 47](https://user-images.githubusercontent.com/52297970/64907759-b6dce080-d6ee-11e9-9b8c-e7aa4902f03f.png)

And for glass panes:

![2019-09-14_12 51 54](https://user-images.githubusercontent.com/52297970/64907765-bcd2c180-d6ee-11e9-94cc-a8d0f5e590e7.png)

The panes look a bit weird like this. It'd probably be better if the edges of panes were to use the same texture as the top so they actually look like a proper edge.

It would also fix this odd inconsistency:
![2019-09-14_12 53 03](https://user-images.githubusercontent.com/52297970/64907782-e1c73480-d6ee-11e9-8a04-9749c6b80804.png)
![2019-09-14_12 53 07](https://user-images.githubusercontent.com/52297970/64907783-e1c73480-d6ee-11e9-8ba3-7839d78270e7.png)

**Comment by ZtereoHYPE** [comment]
I believe this is actually how minecraft made them, not optifine. So this should be a minecraft issue.

**Comment by KaiAF** [comment]
not an OptiFine issue, closing
