### ISSUE TITLE
Preview_1.14.4_HD_U_F4_pre4 isnt compatible with Forge 28.1.0

### ISSUE THREAD

**Issue by RyanCR03** [sp614x/optifine#2885]
optifine version: **Preview_1.14.4_HD_U_F4_pre4** isnt compatible with **Forge 28.1.0**

**Comment by sylvermist** [comment]
i'm using pre4 with forge 28.1.1 and was only seeing a overflow issue that may have been caused by one of the mods that i'm using

**Comment by bscout9956** [comment]
I recommend against using versions not recommended by sp614x. I tried 28.1.5 on F4 pre4 and noticed terrible bugs with map loading/saving. Don't do it.

**Comment by sp614x** [comment]
Fixed in latest preview.
