### ISSUE TITLE
Dont see the optifine download link

### ISSUE THREAD

**Issue by mich983** [sp614x/optifine#2888]
When I go on the Optifine website and select the version that I want I dont see the download link on the next page that show up. Can someone help me?

**Comment by SetantaLP** [comment]
That sounds strange, so can you post the url of the page where the download should be and the url of the page where you select the version.

**Comment by sylvermist** [comment]
probably seeing the adfly page. don't click anything on that page except the yellow "skip ad" button in the top right of the page in the blue bar after it becomes available, or just click the "mirror link" from the version page and skip over the potential malware that adfly "advertises"

**Comment by sp614x** [comment]
Some adblockers may hide the download link.
You can disable the adblocker.
