### ISSUE TITLE
Clock in QuickBar does not animate

### ISSUE THREAD

**Issue by JaedenRuiner** [sp614x/optifine#2889]
Well, first off:
Java Edition, v1.14.4
Forge: 28.0.55
OptiFine: 1.14.4 HD U F4_pre2 (F4 my minecraft says is not supported, and pre4 crashes)

As the title suggests, when I hold the clock in my hand it animates in my hand, but unlike native Minecraft the Clock does not animate while in the QuickBar or inventory.
Thanks
Jaeden "Sifo Dyas" al'Raec Ruiner

**Comment by Studio528-real** [comment]
Forge doesnt like those sorts of things in 1.14.4, also pre4 is for forge 28.0.93, otherwise it crashes on every other version. Aka forge has something broken with vanilla model things including optifine model things (anything thats not the orig texture will not work, but a retexture does. But like CIT or vanilla model files will not work)

**Comment by sylvermist** [comment]
this is an optifine with forge issue as with just forge, the clock behaves just fine. also, pre4 will work with any forge version after 28.0.93.

**Comment by JaedenRuiner** [comment]
Well, not really an OptiFine issue, but Forge 28.0.100 crashes my minecraft so i've rolled back to the .55 working verion.
As for the texture aspect, does this mean that if i get a 3rd party texture pack the clock will start working the QuickBar?
J"SD"a'RR

**Comment by sylvermist** [comment]
i'm using the latest version of forge (at this time 28.1.10) and not experiencing any issues with it. as for the texture pack, that won't work as i'm using a resource pack and it still isn't animating in inventory/toolbar. this issue is an interaction issue with forge and optifine.

**Comment by Dabombber** [comment]
This issue is still present with OptiFine 1.14.4 HD U F4 pre10/forge-1.14.4-28.1.56, and also applies to clocks/compasses in item frames and as dropped items.

**Comment by sp614x** [comment]
The dropped items are not dynamically updated in vanilla, they always show the default icon.
Compass in item frame is also static with default icon.

**Comment by sp614x** [comment]
Fixed, coming in next preview.
