### ISSUE TITLE
Weird torch block outline

### ISSUE THREAD

**Issue by mike406** [sp614x/optifine#2895]
An outline on the torch blocks can be seen at certain angles when Optifine is used. I've attached some screenshots showing this. I'm using default Optifine settings.

**First image shows the outline issue on the two top torches along the wall**
![Capture](https://user-images.githubusercontent.com/3455235/65366728-c4fe9580-dbf5-11e9-9f3b-0a8e228838d3.PNG)

**Second image shows same area but with Optifine disabled (completely vanilla minecraft 1.14.4)**
![Capture2](https://user-images.githubusercontent.com/3455235/65366733-cfb92a80-dbf5-11e9-95ca-fbe50acb7dee.PNG)

**For good measure, this is a closeup angle with Optifine**
![Capture3](https://user-images.githubusercontent.com/3455235/65366737-e52e5480-dbf5-11e9-826f-adf1c73f647d.PNG)

**Comment by sp614x** [comment]
Options -> Video Settings -> Other -> Reset Video Settings.

**Comment by mike406** [comment]
I did....I even stated I am using default Optifine settings
