### ISSUE TITLE
Rename Render- and Shadow-Quality to Resolution

### ISSUE THREAD

**Issue by rre36** [sp614x/optifine#2896]
I'd highly suggest to get rid of the very misleading names "Render Quality" and "Shadow Quality" and call them what they actually are instead, namely "Render Resolution" and "Shadow Resolution". Quality seems very obscure as a word to describe these settings and will inevitably lead people to just set it to 2x and then come to us shader developers and complain for bad performance.

**Comment by sp614x** [comment]
Resolution doesn't go from 0.5x to 2x.
The correct term would be Resolution Multiplier, but there is not enough place on the button for it.
The term Quality is a reasonable substitute.
