### ISSUE TITLE
[1.14.4 F4 pre4] Vanilla clouds settings bug with shader

### ISSUE THREAD

**Issue by 6ix7even** [sp614x/optifine#2899]
I noticed that when we set Clouds to Fast or Fancy , it goes beyond the "clouds=off" in the shader.properties

I'm using 1.14.4 F4 pre4

ps : I know they have to be disabled

![clouds off](https://user-images.githubusercontent.com/44172841/65379150-c6968f00-dcc3-11e9-89d5-1a03e518071d.jpg)

![2019-09-21_22 57 05](https://user-images.githubusercontent.com/44172841/65379153-ceeeca00-dcc3-11e9-9785-d6dd37dac38b.png)
![2019-09-21_22 57 15](https://user-images.githubusercontent.com/44172841/65379155-d6ae6e80-dcc3-11e9-823c-24440e04eae7.png)

**Comment by sp614x** [comment]
The shaders or resource packs define the default behaviour to be used.
The user can override this with by forcing a specific type of clouds in Video Settings -> Details -> Clouds.
