### ISSUE TITLE
java.lang.VerifyError: Inconsistent stackmap frames at branch target 55

### ISSUE THREAD

**Issue by pikkon38** [sp614x/optifine#29]
Updating optifine to latest 1.7.10 HD U D3 in my modpack causes crash to desktop

Crash report attached. If you need to test it in my modpack (its a dev pack on the ATLauncher right now, send me your ign and I can add you to the tester list.

[crash-2016-03-17_20.59.11-client.txt](https://github.com/sp614x/optifine/files/179064/crash-2016-03-17_20.59.11-client.txt)

**Comment by pikkon38** [comment]
This previously did not happen with D1, and nothing in the pack changed other than upgrading to D3

**Comment by sp614x** [comment]
Error log?
Which is the conflicting mod?
You can test by adding the mods one by one (or several at once) until it starts to crash.

**Comment by pikkon38** [comment]
Crash report attached. Do you want the latest log aswell? I am looking into which mod the issue. Unfortunately I have a lot of mods so testing will take some time. Once I find the problem combo I will post here with the info and the crash report/log

**Comment by pikkon38** [comment]
Sorry the crash report was attached to the first post. Im assuming you want the log. I will get to you a little later

**Comment by pikkon38** [comment]
I'm not sure what happened, but after a player downloaded D3 yesterday by mistake, everything started magically working for him. So we all downloaded it again and it worked for myself and the testers of my pack. Did you silently update optifine with the same version number?

**Comment by sp614x** [comment]
D3 was last updated on 20.03.2016 with new installer and Forge loader.
Maybe that was the reason.
