### ISSUE TITLE
Wrap sampling on 3D textures

### ISSUE THREAD

**Issue by rre36** [sp614x/optifine#2905]
Currently the raw textures only support clamped texture coordinate sampling, which leads to artifacts when sampling tiling volumetric textures (eg. 3d noise) and requires the usage of a fract() for tiling. An option to enable wrapped texture coordinate sampling to get rid of that limitation would be very useful here.

**Comment by sp614x** [comment]
Added wrap and filter modes loaded from ".mcmeta" file:
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.properties#L118
Coming in pre14 for 1.16.1.
