### ISSUE TITLE
What kind of Anti Aliasing does optifine use?

### ISSUE THREAD

**Issue by mhtvsSFrpHdE** [sp614x/optifine#2909]
By google this topic,  
I'm shocked that none of a document or discuss mentioned about it.  
For example MSAA SMAA FXAA TAA TXAA CSAA SSAA MFAA

(Edit: Removed useless issue description)

**Comment by Studio528-real** [comment]
I think optifine only uses FXAA and TAA for its AA methods.

**Comment by sp614x** [comment]
"Video Settings -> Quality -> Antialiasing" uses the default AA modes provided by the graphics driver. These are usually vendor specific variants of MSAA.
"Video Settings -> Shaders -> Antialiasing" uses two FXAA variants.

**Comment by mhtvsSFrpHdE** [comment]
@sp614x Thank you, got it.
