### ISSUE TITLE
CEM 3D armor and extruded armor/player skins?

### ISSUE THREAD

**Issue by insomniacUNDERSCORElemon** [sp614x/optifine#291]
Is 3D armor going to be a thing? 

If so, extruded armor would be a cool thing (like pre-generated items but for armor in 3D), it could also be added as a cool feature for player skins (things like eyes, glasses, headphones etc. would have depth. this could be a non-resourcepack setting).

**Comment by sp614x** [comment]
Custom armor models should be possible, but the textures are problematic.
Either the model should be limited to the vanilla textures or there should be a way to use different models per armor type.

**Comment by sp614x** [comment]
Custom models based on the entity properties (health, name, handheld items, etc) may be added at some point.

**Comment by insomniacUNDERSCORElemon** [comment]
I would honestly be very happy with simple pre-generated armor models based on the pack's armor textures, so long as the models propagate to the item model as well.

I'm sure that such a feature would please an incredible amount of people because the paper-thin armor and 2D item icons have really bad aesthetics. So it'd be a good start even before full custom models.

**Comment by insomniacUNDERSCORElemon** [comment]
Closing due to #561 and #1606 already existing. No point in having 3 issues up for the same basic idea.
