### ISSUE TITLE
[Discord] Set verification level to max

### ISSUE THREAD

**Issue by JackDotJS** [sp614x/optifine#2910]
![image](https://user-images.githubusercontent.com/31686191/65445886-0a82b480-dde8-11e9-8941-dd8a136f639f.png)

This is admittedly somewhat extreme, but this will almost guarantee the end of any potential raid, ending mass spam before it can occur.

Those who already have roles in the server don't have to worry about this, as anyone with roles bypass Discord's verification automatically. In addition, this will only apply to those who wish to participate in chat, so "lurkers" don't have to worry about this either.

**Comment by sp614x** [comment]
This is a quite extreme measure.

**Comment by ZenIsBestWolf** [comment]
No longer the correct place for this.
