### ISSUE TITLE
Potion colours don't appear to be working in 1.14.4

### ISSUE THREAD

**Issue by SkaliberWasTaken** [sp614x/optifine#2912]
using "potion.moveSpeed=X" or any of the other examples listed on https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/color.properties doesn't appear to change the colour of potions at all. Is the documentation out of date, or is this a genuine bug?

**Comment by MEEPofFaith** [comment]
Maybe the doc is outdated. Try numerical values maybe?

**Comment by MastaNub** [comment]
doesn't work in 1.14

**Comment by SkaliberWasTaken** [comment]
Duplicate
