### ISSUE TITLE
HELP OptiFine_1.14.4_HD_U_F3 is running way worse than vanilla

### ISSUE THREAD

**Issue by brandonecp** [sp614x/optifine#2914]
![Screenshot (1)](https://user-images.githubusercontent.com/55775766/65567963-fab0c080-df0c-11e9-852f-19f6e4b8fc0e.png)

![Screenshot (2)](https://user-images.githubusercontent.com/55775766/65567972-01d7ce80-df0d-11e9-90c1-e42e69d7010a.png)
these are screen shots of the same world with same settings except for some annoying weird reason optifine is running bad. i also do have smooth frames off. im using a razor laptop btw, and i have another laptop with worse hardware that runs optifine perfectly fine even with some weak shaders. i need help uninstalled and reinstalled java, minecraft and optifine already and it hasn't changed.

**Comment by sp614x** [comment]
Video Settings -> Other -> Reset Video Settings
Vanilla is running with VBOs.

**Comment by brandonecp** [comment]
That didn’t change anything, since I just got the computer I reset the whole laptop re installed my gpu drivers Minecraft, java, and optifine and it didn’t change it all

**Comment by sp614x** [comment]
In the above screenshots OptiFine is running with integrated GPU (Intel) and vanilla is running with dedicated GPU (NVidia).
In the graphics control panel you should be able to configure Java to always run with dedicated GPU.
