### ISSUE TITLE
Optifine 1.14.4_HD_U_F3 won't work with Forge 28.1.20

### ISSUE THREAD

**Issue by MS21GH** [sp614x/optifine#2916]
I just installed Optifine along with a few mods, and I get this when launching the game.
![image](https://user-images.githubusercontent.com/20264383/65664477-b242f100-e039-11e9-8944-3e85bfe68b8a.png)

I opened the Log, and found this, not sure it helps.
![image](https://user-images.githubusercontent.com/20264383/65664483-b707a500-e039-11e9-81df-4795003bcbf2.png)

**Comment by MS21GH** [comment]
I've tried other versions, and I get the same issue on Forge 28.1.22 and even 28.1.0

**Comment by MS21GH** [comment]
I've now also tried Optifine 1.14.4_HD_U_F2, still nothing.

**Comment by TimeHawk** [comment]
You need to download the preview versions of OptiFine.
https://media.discordapp.net/attachments/613497351298088962/623696704595689473/OF-Preview.gif

**Comment by MS21GH** [comment]
I did some time ago but forgot to close the issue, thank you for your response.
