### ISSUE TITLE
[REQUEST] Custom Sounds

### ISSUE THREAD

**Issue by SkaliberWasTaken** [sp614x/optifine#2919]
Probably a huge ask, but being able to make mobs sound different, to accompany multiple textures, would be brilliant.

**Comment by MEEPofFaith** [comment]
You can already change the sounds of everything in vanilla...
Unless you're saying that the mob's sounds are based on what CEM it is if said mob has multiple CEMs.

**Comment by SkaliberWasTaken** [comment]
Yeah, i'm talking about mobs with different skins (whether it be biome based, or height based, or just random) having their own unique sound pool to match their skin

**Comment by Prince-Ghast** [comment]
Basically a custom variety of the same mob with its own sound files. That would be brilliant.

**Comment by Xigzagamer** [comment]
I'm very much interested in this feature since my newest resource pack idea could benefit greatly from it. I wanted to give the Zombie like 40+ skins, most of which would be enhanced by the capability of adding custom mob sounds.

**Comment by SkaliberWasTaken** [comment]
Is there any update on this? Not sure if custom sound pools would be possible given the resource pack features have only been texture based traditionally.

**Comment by Xigzagamer** [comment]
Vanilla resource packs support custom sound files just fine. I can't say how difficult it'd be to have skin dependent custom sounds, but in theory it should be the same concept as the varied skins, so I'd say it is definitely possible.

**Comment by SkaliberWasTaken** [comment]
Still not sure if this is actually possible due to it's nature, but will re-open in a more up-to-date request megathread in the future.

**Comment by SkaliberWasTaken** [comment]
> so it is 2023, we can do custom animations, textures, and models, all by specific name setters but still no custom sounds? Specifically within Optifine.

I've given up on Optifine adding new features. If you're looking for more advanced resource pack development as I am, look to Fabric. https://lambdaurora.dev/optifine_alternatives/
