### ISSUE TITLE
CEM scale animation

### ISSUE THREAD

**Issue by insomniacUNDERSCORElemon** [sp614x/optifine#292]
Scale animation doesn't seem to exist as a general variable, although it was one of the first things I thought of (specifically for ender crystals).

It would be great for creepy packs (beating heart, breathing lungs, pulsating eye, or flaring nostrils) or sci-fi (sine-sized fireball, pulsating glow, or bellows... bellows only if it's added like sx sy sz rather than only scale). 

I'm sure others could likely think of more uses.

**Comment by sp614x** [comment]
Added scale "sx", "sy" and "sz", coming in preview D2.

**Comment by sp614x** [comment]
Preview D2 is released.
