### ISSUE TITLE
[Issue] OptiFine 1.14.4 HD U F4 pre5 breaks JEI interface

### ISSUE THREAD

**Issue by bscout9956** [sp614x/optifine#2921]
Using Forge 28.0.93 and the following mods:
![image](https://user-images.githubusercontent.com/24628639/65805682-e5ca6c00-e15c-11e9-80a2-25a6d8aa1b2a.png)
_
After upgrading from F4 **pre4** to F4 **pre5** I found weird bugs such as:
Graphical glitches (especifically on JEI, only happens with Optifine pre5 and is not a resource pack issue)...
![image](https://user-images.githubusercontent.com/24628639/65805590-92f0b480-e15c-11e9-9c26-95c7eeb1b3d0.png)

There is likely a regression on pre5 vs pre4.
EDIT: It wasn't breaking all mods, just JEI.

**Comment by sp614x** [comment]
Does it work with latest preview?

**Comment by GabrielAndreescu** [comment]
It's still the same on pre7

**Comment by sp614x** [comment]
Testing Forge 28.1.44 + OF F4 pre9 + JEI 6.0.0.18.

All JEI GUIs work correctly:

![image](https://user-images.githubusercontent.com/16635441/66749007-f717b600-ee88-11e9-9010-b9d0500a8e1d.png)

![image](https://user-images.githubusercontent.com/16635441/66749038-0b5bb300-ee89-11e9-9578-15323fe2d2df.png)
