### ISSUE TITLE
[Suggestion] UX enhancements for Invalid Cape Designs

### ISSUE THREAD

**Issue by JackDotJS** [sp614x/optifine#2924]
The website should really just tell you *why* a certain banner design is invalid. For us experienced users, we can pretty easily tell when a banner design will not work, but I very often see new users get horribly confused and angry about how their custom banner isn't working. 

There's currently about 2 (known) possible errors when a banner design is rejected:
1. Too many patterns (9 or more, not including base color)
2. Banner uses the Mojang pattern

To save everyone some more time, the cape change page should also just tell you these limits from the start.

**Comment by sp614x** [comment]
Added info "Up to 8 layers can be used, the Mojang logo is not allowed."

**Comment by KaiAF** [comment]
Since this was added, I think I am going to close the issue. If I am wrong, let me know
