### ISSUE TITLE
[Forge] Can't start forge+optifine in dev enviroment

### ISSUE THREAD

**Issue by Nightenom** [sp614x/optifine#2925]
Using local gradle dependency. Tried suggested (28.0.93) forge version, the newest (28.1.26) provides exactly the same crash. Used extract option in the installer producing this `OptiFine_1.14.4_HD_U_F4_pre5_MOD.jar`, gradle `implementation fg.deobf("net.optifine:OptiFine:1.14.4_HD_U_F4_pre5_MOD")`
<https://gist.github.com/Nightenom/84db00c5002abdbfd1ac9e904c93069d>

**Comment by Barteks2x** [comment]
OptiFine itself doesn't seem to support running it in dev environment.

That said, I'm working on an unofficial way to make it work https://github.com/OpenCubicChunks/OptiFineDevTweaker/tree/modlauncher
It needs a few more changes to be just drag&drop into mods, but if you want to you should be able to compile and run it yourself already (you need to set an environment variable for obfuscated MC jar location). You would also need to enable a special logging marker for modlauncher to dump transformed classes to be able to see optifine-patched code in your IDE.

**Comment by Nightenom** [comment]
Thanks, almost working, gonna dm you through discord

**Comment by sp614x** [comment]
The OptiFine 1.14.x JAR includes the SRG named classes so it should be relatively easy to get it running in a Forge dev environment. Especially when using ModLauncher.
