### ISSUE TITLE
[Fabric] (OptiFabric) i can't use shaders

### ISSUE THREAD

**Issue by Lucky-56** [sp614x/optifine#2926]
![2019-09-29_14 55 35](https://user-images.githubusercontent.com/55949451/65832882-73779a00-e2ca-11e9-8db3-9d65e1d33706.png)
With Sildurs Vibrant Shaders v1.22 High
![2019-09-29_15 02 50](https://user-images.githubusercontent.com/55949451/65832884-783c4e00-e2ca-11e9-9056-9ade14c61475.png)
With (internal)
![2019-09-29_15 08 23](https://user-images.githubusercontent.com/55949451/65832939-06b0cf80-e2cb-11e9-9be7-9a6ecd47f71b.png)
Without

mods:
-preview_OptiFine_1.14.2_HD_U_F1_pre15
-optifabric-0.2.0
-replaymod-1.14.2-2.2.0-b2
-Fabric 0.6.2+build.166(fabric-api-0.3.0+build.185)

**Comment by realjackasterisk** [comment]
Report this on OptiFabric's repo, not ours. https://github.com/modmuss50/OptiFabric
