### ISSUE TITLE
DynamicTexture allocates 3x the size [1.12.2]

### ISSUE THREAD

**Issue by stepsword** [sp614x/optifine#2927]
Hi,

You do something like this in the rewritten Dynamic Texture, I think:

`this.dynamicTextureData = new int[textureWidth * textureHeight * 3];`

I'm trying to read in an image from glGetTexImage(), and IntBuffer.get() throws a buffer underflow if the target array is too big. Is there a reason to allocate 3x the size in Dynamic Texture? What is the extra space for?

**Comment by sp614x** [comment]
The extra space is used for normal and specular textures.
This was reorganized in 1.13.x.
