### ISSUE TITLE
Purple haze Around Screen

### ISSUE THREAD

**Issue by TheTheTheTheTheTheVergebaby** [sp614x/optifine#2928]
The haze appears after about half an hour of playtime. Im on Optifine HD f4_pre5 Ultra. 
Vingette has been turned off, still there.
Shaders have been turned off, it's still there. (Picture 2)
Turning graphics on "Fast" removes the haze. (Picture 3)
Pressing F1 removes the haze. (Picture 4)

![15697828696291079652637932111799](https://user-images.githubusercontent.com/27711809/65837655-21ce1000-e2c8-11e9-913c-19aaed7e1eb4.jpg)
![15697829060051643535386922382077](https://user-images.githubusercontent.com/27711809/65837668-46c28300-e2c8-11e9-86c4-f2d558fcdf37.jpg)
![15697829476371230942513074363764](https://user-images.githubusercontent.com/27711809/65837672-5a6de980-e2c8-11e9-8805-eb5eefc94ca2.jpg)

**Comment by sp614x** [comment]
When OptiFine is running standalone and the shaders are off the only thing that could produce such effect is the vignette.
When running with Forge and especially with other mods installed, everything is possible.
