### ISSUE TITLE
Emissive Lighting on Specific Entities

### ISSUE THREAD

**Issue by SkaliberWasTaken** [sp614x/optifine#2929]
Emissive lighting doesn't appear to work if used on a spectral arrow. I'm not sure if this applies to any of the other "none living entities" such as boats, or the regular arrow, but I currently have emissive lighting working on zombies, skeletons, and drowned.

**Comment by Prince-Ghast** [comment]
I don't believe emissive.properties work on entities that aren't mobs.

**Comment by SkaliberWasTaken** [comment]
Duplicate
