### ISSUE TITLE
[Suggestion] Random Entity Textures based on Moon Phase, Time and Weather

### ISSUE THREAD

**Issue by bageldotjpg** [sp614x/optifine#2931]
### New Parameter: Weather
This parameter would be able to change the texture of an entity based on the weather cycle.

Examples:
weather=<clear|rain|thunder>
weather=clear : random texture would only appear during clear skies
weather=rain : random texture would only appear during rain
weather=thunder : random texture would only appear during thunderstorms
weather=rain thunder : random texture would only appear during rain and thunderstorms

### New Parameter: Moon Phase
This parameter would be able to change the texture of an entity based on the moon cycle.

Examples:
moonphase=<0-7>
moonphase=0 : random texture would only appear during a new moon
moonphase=5-6 : random texture would only appear during the 5th and 6th moon phases
moonphase=1 5 7 : random texture would appear during the 1st, 5th, and 7th moon phases

### New Parameter: Time
This parameter would be able to change the texture of an entity based on the day cycle.

time=<day|night>
time=day : random texture would only appear during the day
time=night : random texture would only appear during the night

**Comment by MEEPofFaith** [comment]
What if you could also put a number or range between 0 and 24000 for time?

Then it could be more than just day or night and can be the tick itself.

So maybe you could put 6000-8142 so that the random texture would appear between ticks 6000 and 8142.

**Comment by sp614x** [comment]
Coming in next preview.
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/random_entities.properties#L146
