### ISSUE TITLE
Force CUDA usage

### ISSUE THREAD

**Issue by wlp7s0** [sp614x/optifine#2933]
Hello,
Since [1.12](https://github.com/Askannz/optimus-manager/releases/tag/v1.2) version of optimus-manager and nvidia Linux driver version 435.17, we've got an option to use [hybrid mode](https://github.com/Askannz/optimus-manager/wiki/A-guide--to-power-management-options#configuration-1--built-in-power-management-inside-the-nvidia-driver) to use on dual-GPU Linux laptops. Now there is no need to relogin to switch GPU and at the same time it saves a lot of battery life. 

As the documentation stands - discrete GPU will be used automatically if external display is connected or application uses CUDA for rendering. I tested this configuration and it works flawlessly. Except OptiFine. When I start Minecraft launcher (I use TLauncher) it uses my Nvidia video card 

> Machine info: 
> Linux 5.3.1-arch1-1-ARCH, Java 1.8.0_222, jvm bit x64, 15899 MB RAM
> java path=/usr/lib/jvm/java-8-openjdk/jre/bin/java
> GP107M [GeForce GTX 1050 Mobile]
> 

But when I enter a game - OptiFine see only Intel GPU. 
Going through a lot of logs, I've noticed that LWJGL is used by OptiFine:

> [14:05:38] [Client thread/INFO] [minecraft/Minecraft]: LWJGL Version: 2.9.4
> [14:05:38] [Client thread/INFO] [Config]: [OptiFine] 
> [14:05:38] [Client thread/INFO] [Config]: [OptiFine] OptiFine_1.12.2_HD_U_E3
> [14:05:38] [Client thread/INFO] [Config]: [OptiFine] Build: 20181210-121000
> [14:05:38] [Client thread/INFO] [Config]: [OptiFine] OS: Linux (amd64) version 5.3.1-arch1-1-ARCH
> [14:05:38] [Client thread/INFO] [Config]: [OptiFine] Java: 1.8.0_222, Oracle Corporation
> [14:05:38] [Client thread/INFO] [Config]: [OptiFine] VM: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
> [14:05:38] [Client thread/INFO] [Config]: [OptiFine] LWJGL: 2.9.4
> [14:05:38] [Client thread/INFO] [Config]: [OptiFine] OpenGL: Mesa DRI Intel(R) UHD Graphics 620 (Kabylake GT2) , version 3.0 Mesa 19.1.7, Intel Open Source Technology Center
> [14:05:38] [Client thread/INFO] [Config]: [OptiFine] OpenGL Version: 3.0.0
> [14:05:38] [Client thread/INFO] [Config]: [OptiFine] Maximum texture size: 16384x16384
> [14:05:38] [VersionCheck/INFO] [Config]: [OptiFine] Checking for new version
> [14:05:38] [Client thread/INFO] [net.optifine.shaders.SMCLog]: [Shaders] OpenGL Version: 3.0 Mesa 19.1.7
> [14:05:38] [Client thread/INFO] [net.optifine.shaders.SMCLog]: [Shaders] Vendor:  Intel Open Source Technology Center
> [14:05:38] [Client thread/INFO] [net.optifine.shaders.SMCLog]: [Shaders] Renderer: Mesa DRI Intel(R) UHD Graphics 620 (Kabylake GT2) 
> [14:05:38] [Client thread/INFO] [net.optifine.shaders.SMCLog]: [Shaders] Capabilities:  2.0  2.1  3.0  -  - 
> [14:05:38] [Client thread/INFO] [net.optifine.shaders.SMCLog]: [Shaders] GL_MAX_DRAW_BUFFERS: 8
> [14:05:38] [Client thread/INFO] [net.optifine.shaders.SMCLog]: [Shaders] GL_MAX_COLOR_ATTACHMENTS_EXT: 8
> [14:05:38] [Client thread/INFO] [net.optifine.shaders.SMCLog]: [Shaders] GL_MAX_TEXTURE_IMAGE_UNITS: 32
> [14:05:38] [Client thread/INFO] [net.optifine.shaders.SMCLog]: [Shaders] Load shaders configuration.
> [14:05:38] [Client thread/INFO] [net.optifine.shaders.SMCLog]: [Shaders] Loaded shaderpack: SEUS-Renewed-1.0.0.zip

LWJGL [documentation](https://javadoc.lwjgl.org/org/lwjgl/system/Configuration.html) provides us with some options  it may be called with. But I don't understand how. 
`
-DConfigurationOPENCL_LIBRARY_NAME=nvcuda
`
Using this as a java option on startup does no impact on a LWJGL initialization.

Is it possible to force OptiFine to force LWJGL to use CUDA for Nvidia driver to realize that it is needed and launch an application on a discrete video?

**Comment by sp614x** [comment]
Vanilla Minecraft is also using LWJGL. 
CUDA is a computing platform, it is not a rendering API. Neither vanilla nor Optifine are using CUDA.
Most probably it is the NVidia driver that detects vanilla minecraft and enables a special GPU mode.

**Comment by wlp7s0** [comment]
I see. So, there is no way to do what I want.
Thank you for your time!
