### ISSUE TITLE
Just a quick question.

### ISSUE THREAD

**Issue by Furious1964** [sp614x/optifine#2934]
When will Optifine be compatible with the latest Forge?

**Comment by TimeHawk** [comment]
It is though in 1.14.4 according to the changelogs.

**Comment by Studio528-real** [comment]
![image](https://user-images.githubusercontent.com/52116771/65924119-852f6f00-e3a8-11e9-93c3-3a219df703b3.png)

**Comment by Furious1964** [comment]
OK, thanks. Looking forward to when it's fully released.
