### ISSUE TITLE
1.14.4: Crash on load due to mod particle

### ISSUE THREAD

**Issue by fredtargaryen** [sp614x/optifine#2935]
Optifine seems to have a problem with my particle factory registration.

Problem line (during handling of ParticleFactoryRegisterEvent):
`Minecraft.getInstance().particles.registerFactory(FIREWORK_TYPE, SquidFireworkParticle.SparkFactory::new);`

Stacktrace snippet:
`java.lang.BootstrapMethodError: java.lang.IllegalAccessError: tried to access class net.minecraft.client.particle.ParticleManager$IParticleMetaFactory from class com.fredtargaryen.rocketsquids.RocketSquidsBase
    at com.fredtargaryen.rocketsquids.RocketSquidsBase.registerFactories(RocketSquidsBase.java:259) ~[?:1.2] {re:classloading,pl:capability_inject_definalize:A}`

Likely cause (from Discord):
"forge makes ParticleManager$IParticleMetaFactory public, but optifine seems to revert this change somehow"

This is known to occur in Optifine F4 pre4, pre5 and pre6, and on Forge 28.1.26.

**Comment by sp614x** [comment]
Fixed in pre7.

**Comment by fredtargaryen** [comment]
I have received a similar crash log that uses pre7: https://pastebin.com/RERZ6aY4
