### ISSUE TITLE
1.12.2 Animations Stopped Working

### ISSUE THREAD

**Issue by Nightseer769** [sp614x/optifine#2936]
So I installed Optifine in conjunction with the Life in the Village Lite modpack, but only when I have Optfine enabled do the animations stop working. I turned on and off all the animation toggles and I turned on and off the "smart animations" toggle to no avail. I tried the modpack with both editions 1 and 2 and those flat out don't work with it. I was talking with the people who are using the same modpack with Optifine and they have no issues. Does anybody have any clue?

**Comment by sp614x** [comment]
Most probably a conflict with one of the mods.
