### ISSUE TITLE
Minecraft not detected by Discord when Optifine is installed

### ISSUE THREAD

**Issue by AaronBeaudoin** [sp614x/optifine#2941]
When I play vanilla Minecraft my friends can see in Discord what I'm playing and more importantly I am able to stream my game. However, with Optifine installed Discord does not detect my game at all. I'm leaning towards this being an Optifine issue because of how Discord has no issues at all with vanilla Minecraft.

**Comment by sp614x** [comment]
Discord is the one that detects Minecraft.
OptiFine can do nothing about it.

**Comment by MrJulius** [comment]
(In Discord) Go to Settings > Game activity > Add a game > Select Minecraft *[version] and it should fix it

**Comment by quinnell** [comment]
@MrJulius that only seems to work once.  You gotta do it again next time you run the game.

**Comment by Yaboi-solo** [comment]
Get a rich presence mod for Forge and it will show it in your status.

**Comment by decorativeben** [comment]
An easy way to fix this if you dont want the overlay is to go into the minecraft launcher settings and tick "keep the launcher open while games are running." next, select minecraft launcher as a game in discord and rename it to minecraft.
