### ISSUE TITLE
My Cape Randomly Stopped Showing .......

### ISSUE THREAD

**Issue by FearedDuck** [sp614x/optifine#2943]
I have no idea what the issue is here ...

I've had optifine for 2+ years without any problems but today when I changed my minecraft account name, the cape randomly deleted ... or atleast stopped showing. I can't even see it on namemc.

I tried logging into my optifine account but I can't remember my donation email because my account's current email is different to my donation one. This is really frustrating because I'd like to see the cape.

Anyone know how to fix this? Or atleast change my donation email?

**Comment by sp614x** [comment]
After you change the MC username it may take up to 24h until the cape is move to the name.
