### ISSUE TITLE
End sky with optifine changes

### ISSUE THREAD

**Issue by moseechev** [sp614x/optifine#2945]
With optifine End sky changes! I don't like it! It still pink color, but with some another textures. How can i disable it?

**Comment by realjackasterisk** [comment]
Screenshot...?

**Comment by MastaNub** [comment]
If color.properties has "sky.end=FFFFFF" then the endsky will turn into a pinkish colour.

http://prnt.sc/pntv9z - default
https://prnt.sc/pntv9z - sky.end=FFFFFF in color.properties

**Comment by sp614x** [comment]
The sky color shange is coming from either a resource pack or a shader pack.
Remove or edit the resource/shader pack and it would be fixed.
