### ISSUE TITLE
Twitch Launcher Not Finding Optifine

### ISSUE THREAD

**Issue by sinfulwaters** [sp614x/optifine#2946]
So I've used the Twitch launcher before and created modpacks all the time. Recently I've been playing on a new modpack that is in Minecraft version 1.14.4.  I was enjoying the pack until I wanted to install Optifine and use some shaders. I install like it should have been done in older packs, open folder drag and drop and play, plain and simple. For some reason, Twitch doesn't recognize that I've installed it and I've tried with other modpacks of this version and it also doesn't work. Am I doing something wrong?

**Comment by Suyashtnt** [comment]
Well, you need to install the preview version of optifine but it won’t show up but it’s installed, could you tell me the mod pack?

**Comment by sinfulwaters** [comment]
It's Minecolonies Getting Started by Kreezxil. Also whats the difference between the preview version and other versions?

**Comment by Suyashtnt** [comment]
preview is the beta version and it supports forge, but twitch wont pick it up try it
step 1)open your modpack folder
step 2)go into mods
step 3)place the preview optifine .jar in that folder

**Comment by sp614x** [comment]
Optifine doesn't appear in the Forge mod list as it is not a Forge mod. It is only compatible with Forge.
To verify that it is really installed, go to Video Settings, the Optifine version would be shown in the lower left corner and there would be more options.

**Comment by sinfulwaters** [comment]
That’s just it. It doesn’t appear there either it doesn’t change the setting, it doesn’t add a shaders folder it’s as if Minecraft/Forge doesn’t acknowledge it even being placed in the folder

**Comment by MissMary2** [comment]
ive been having the exact same problem with every pack i try to do this with.... it should be fairly straight forward but, it doesnt change any settings or anything when i go into the video settings. mildly frustrating.

**Comment by usafphoenix** [comment]
its the fact that it was manually installed. Twitch ONLY recognizes mods that were installed via it's portal. Even clicking "refresh" a jillion times won't SCAN for files in the mod folder. because twitch was designed by an idiot. 
In order to SEE in the modpacks installed mods folder that optifine is there, you have to manually edit the Instances' core file, which is dangerous, as doing it wrongly can irreparably corrupt your modpack.

**Comment by usafphoenix** [comment]
found in appdata/roaming/twitch/gameinstances

DO NOT ATTEMPT THIS IF YOU DON'T UNDERSTAND THE SYNTAX, AS ANY SMALL ERROR WILL RUIN IT
