### ISSUE TITLE
SEUS PTGI Beta 7.1 Crash

### ISSUE THREAD

**Issue by yugi1408** [sp614x/optifine#2952]
okay so I am running Minecraft using SEUS PTGI E7.1 and Pulchra 512x Texture pack along with the Aether Legacy Mod (Now called the aether) and I keep getting an out of memory error if I go into full screen (or just maximize the window)

My Specs:

i9-9900k
32 GB DDR4 RAM
MSI RTX 2080 Ti GAMING X TRIO (OC 2080 Ti)

Here is the log:

https://paste.ee/p/EpkcS

**Comment by sp614x** [comment]
The Out of Memory is coming from graphics driver.
No idea how it can be fixed, may be related to the mod.

**Comment by yugi1408** [comment]
> The Out of Memory is coming from graphics driver.
> No idea how it can be fixed, may be related to the Aether mod.

ok thanks
