### ISSUE TITLE
Optifine not supporting `IModelData` correctly. 

### ISSUE THREAD

**Issue by Wyn-Price** [sp614x/optifine#2955]
Forges `IModelData` system doesn't work with optifine, with the model data always being empty when passed to the baked model. 

`BlockModelRenderer#renderModel` has the correct model data passed in, but `renderModelSmooth` and `renderModelFlat` never have the model data sensitive version called with the passed in model data. It's always the non `IModelData` method called, which just delegates to the model data sensitive version but with the model data replaced with the empty data instance.

Causes https://github.com/AbrarSyed/SecretRoomsMod-forge/issues/283

More info:
[Tool used to debug](https://github.com/Cadiboo/OptiFineDeobf)
Mappings: mcp `20190922`,

**Comment by sp614x** [comment]
![image](https://user-images.githubusercontent.com/16635441/66484342-138daa00-eaa7-11e9-964d-f8ac31714681.png)

**Comment by sp614x** [comment]
Fixed, coming in next preview.
