### ISSUE TITLE
(1.13.2) Really intense lag:( 

### ISSUE THREAD

**Issue by megeben** [sp614x/optifine#2956]
![2019-10-08_20 09 30](https://user-images.githubusercontent.com/56331233/66449330-906a4680-ea09-11e9-9a52-5a76ff7a6e11.png)

Hello^_^

I've just gotten Minecraft Optifine 1.13.2 and it has greatly reduced my FPS to about 14-17 whereas vanilla Minecraft runs really well at about 60 FPS. I've gone through and updated my graphics cards and toggled in-game settings and I cant find a solution at this point.

**Comment by sp614x** [comment]
You are running Sildurs Shaders on integrated GPU (Intel), this is normal.

**Comment by megeben** [comment]
Okay cool^_^ Thank you
