### ISSUE TITLE
[Suggestion] Entity texturing based on damage/health

### ISSUE THREAD

**Issue by NitroCipher** [sp614x/optifine#2958]
I think that we should be able to use an entity's health as a factor for their "random" textures

**Comment by NitroCipher** [comment]
This is, of course, inspired by the Iron Golem damage textures in the latest 1.15 snapshot

**Comment by sp614x** [comment]
Coming in next preview.

**Comment by NitroCipher** [comment]
Whoa, that was quick! Thanks!
