### ISSUE TITLE
Hook in RenderGlobal.renderEntities()

### ISSUE THREAD

**Issue by Ordinastie** [sp614x/optifine#296]
I have a system that hooks in RenderGlobal.renderEntities() to allow animation rendering for blocks, without the need for a TE. But the instruction list I'm looking for can't be found when Optifine is installed.
What are the solutions ?

**Comment by sp614x** [comment]
ASM bytecode manipulation should not be used unless ABSOLUTELY required. Even simple access transformers can wreak havoc (#252).
The correct way would be Forge to add a general entity render hook that you can use. This can also be used by other mods and Optifine will automatically work with it in all future versions.
The RenderGlobal.renderEntities() method is changing constantly (by Forge and by OptiFine), so even if you manage to make it compatible with the current OptiFine, it could break in the next version.

**Comment by Ordinastie** [comment]
Forge is not going to add a hook for that.
I am ok with fixing it for the next version if it happens to change, but the problem is, I can't know what Optifine changes are...

**Comment by Ordinastie** [comment]
I refactored my whole system to use RenderWorldLastEvent instead. But with blending and shaders, I get that : http://puu.sh/rNpep.jpg.

**Comment by sp614x** [comment]
Blending and shaders are hard to mix.
Most shader packs have special handling for translucent objects (water, stained glass, etc) and it only works for blocks. There is no support for entities, tile entities or custom rendering.
The end result is different for each shader pack as they differ in their translucency handling.

**Comment by Ordinastie** [comment]
But is there a way to know if a shader pack is currently in use ?

**Comment by sp614x** [comment]
You could check "DefaultVertexFormats.BLOCK.getNextOffset() > 28".
The vanilla BLOCK vertex format has size 28, when shaders are active the size is 56.
