### ISSUE TITLE
Tridents can't be edited with CEM

### ISSUE THREAD

**Issue by SkaliberWasTaken** [sp614x/optifine#2960]
I'm not sure if there's a larger issue to this, or if it just got missed, but trident entities can't be changed via CEM currently?

**Comment by FrancescNosas** [comment]
No, you can currently change them only via json files

**Comment by Prince-Ghast** [comment]
Yeah. An entity with no JEM model file. I tried using the Json file to change the model, but it messed up everything.

**Comment by Nekzuris** [comment]
Yeah we can edit the trident model when it's held by the player via "trident_in_hand.json" and "trident_throwing.json" but when it's thrown the CEM is missing.

**Comment by SkaliberWasTaken** [comment]
Duplicate
