### ISSUE TITLE
[Suggestion] Add OptiFine logo to launcher profile

### ISSUE THREAD

**Issue by NitroCipher** [sp614x/optifine#2962]
You can really easily replace the icon for a profile on the MC launcher, so why not give the OptiFine profile its own image?

I tried doing it myself, and it works really well:
![image](https://user-images.githubusercontent.com/11393734/66622117-33f35c80-ebac-11e9-8723-d81b9bdcff9f.png)

All you need to do is replace the icon in the profile json with a base64 image:
[The image data I use is provided here](https://hastebin.com/raw/imeyumajag)
```json
"OptiFine" : {
      "created" : "2018-11-20T01:37:00.980Z",
      "icon" : "data:image/png;base64",
      "javaArgs" : "-Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M",
      "lastUsed" : "2019-10-11T03:18:22.437Z",
      "lastVersionId" : "1.14.4-OptiFine_HD_U_F4_pre8",
      "name" : "OptiFine",
      "type" : "custom"
    },
```

**Comment by sp614x** [comment]
Cool

**Comment by sp614x** [comment]
Updated installer to set OptiFine profile icon.
Coming in pre9.

**Comment by realjackasterisk** [comment]
@sp614x I know I'm a bit late here, but I'd like to suggest using a *much* higher quality icon for this. The icon @NitroCipher provided seems to have a very low resolution (32x32), and this becomes especially apparent on larger displays.

Here's the image data I've made. https://pastebin.com/3YmEaUcN
This one is, of course, the same image. The only difference is it is now 128x128. If it's ever needed, I could also make even higher resolutions.

Finally, here's a comparison. (before and after)
![image](https://user-images.githubusercontent.com/31686191/67128793-9d2d2e00-f1b1-11e9-8d08-99a0bf298f11.png)
![image](https://user-images.githubusercontent.com/31686191/67128800-a28a7880-f1b1-11e9-8ce9-8b4173418fbf.png)

**Comment by NitroCipher** [comment]
I agree on the front of using a higher resolution image!

(Just going to point out, my image is actually 64x64. The one actually used in the launcher profile however is 32x32)
