### ISSUE TITLE
Entity heads assume health is 0 when using health based random textures

### ISSUE THREAD

**Issue by NitroCipher** [sp614x/optifine#2963]
If you use health in your random entity texture file, and then try to use that same entities skull, you will find that the entity is assumed to have a health value of 0.

**Comment by sp614x** [comment]
Maybe it should have health -1?

**Comment by NitroCipher** [comment]
-1 sounds good to me. That way we can have a way to separate it

**Comment by NitroCipher** [comment]
I was trying to make a pack in which a zombie would lose its head at low health, but then I noticed that the skull was transparent. So anyone trying to make a pack like that would run into a similar issue

**Comment by sp614x** [comment]
Fixed, comin in next preview.

**Comment by NitroCipher** [comment]
Tried to use `heath = -1`, and I am getting this error logged to my console: `[OptiFine] RandomEntities: Invalid range: -1`

here is the snip from the properties file:
![image](https://user-images.githubusercontent.com/11393734/66669307-c6cbdf80-ec1c-11e9-8611-711334b46e8c.png)
