### ISSUE TITLE
Crash when trying to craft something in inventory

### ISSUE THREAD

**Issue by Leo40Git** [sp614x/optifine#2964]
**Java:** AdoptOpenJDK 13 HotSpot (installer version)

**Minecraft:** 1.14.4

**OptiFine:** Ultra F4 pre8

**Crash log:** [crash-2019-10-11_13.35.26-server.txt](https://github.com/sp614x/optifine/files/3717084/crash-2019-10-11_13.35.26-server.txt)

**Reproduction instructions:**
1. Grab the latest development version of [MultiMC](https://github.com/MultiMC/MultiMC5) (`0.6.7-develop-1394` at the time of writing).
2. Create a 1.14.4 instance.
3. Install OptiFine using [these steps](https://github.com/MultiMC/MultiMC5/wiki/MultiMC-and-OptiFine#the-jar-mod-way-any-version).
4. Run the game.
5. Create a Survival world.
6. Get some wood.
7. Try to craft some planks.
8. *Crash!*

**Comment by sp614x** [comment]
Looks like a problem with OpenJDK.
Similar to #2965.

**Comment by Leo40Git** [comment]
Opened an issue on the OpenJDK distro's repo.

**Comment by jlstout123** [comment]
Same issue but crashed using Oracle's Java 12.0.2 and 13.  Both work on Optifine F4 pre3 (don't have copies of pre4-6) and both crash on Optifine F4 pre7 to current.

	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 13, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation

**Comment by Brottweiler** [comment]
I am crashing on F4 but F3 was fine.

```java
The game crashed whilst mouseclicked event handler
Error: java.lang.IncompatibleClassChangeError: Inconsistent constant pool data in classfile for class java/util/stream/Stream. Method 'java.util.stream.Stream of(java.lang.Object)' at index 452 is CONSTANT_MethodRef and should be CONSTANT_InterfaceMethodRef
```
OpenJDK 13.u33 on Linux.

**Comment by rumickon** [comment]
Oracle Java 11.0.5, Otifine 1.14.4 HD U F4. Crash client when using stonecutter.
```
Description: mouseReleased event handler

java.lang.IncompatibleClassChangeError: Inconsistent constant pool data in classfile for class java/util/stream/Stream. Method of(Ljava/lang/Object;)Ljava/util/stream/Stream; at index 452 is CONSTANT_MethodRef and should be CONSTANT_InterfaceMethodRef
	at p.a(Util.java:299)
```

**Comment by sp614x** [comment]
The first crashing version is 1.14.4_F4_pre7.

**Comment by sp614x** [comment]
Java 9+ doesn't like the recompiled class `net.minecraft.util.Util`. 
The bytecode for method `func_215081_a` is valid in Java 8, but not in Java9+:
```
    public static <T> Stream<T> func_215081_a(Optional <? extends T > p_215081_0_)
    {
        return (Stream)DataFixUtils.orElseGet(p_215081_0_.map(Stream::of), Stream::empty);
    }
```
More details: https://bugs.openjdk.java.net/browse/CODETOOLS-7902333
Java 8 compiler problem?

**Comment by sp614x** [comment]
Updated OptiFine 1.14.4 F4 with a bugfix.
Please redownload.
