### ISSUE TITLE
Client crash when shift clicking furnace

### ISSUE THREAD

**Issue by x1p** [sp614x/optifine#2965]
Optifine 1.14.4 HD U F4 pre7 crashes when:

Open furnace
Shift click on some fuel in your inventory to put it into the furnace
Client crashes
Message box appears in launcher:
```
The game crashed whilst mouseclicked event handler
Error: java.lang.IncompatibleClassChangeError: Inconsistent constant pool data in classfile for class java/util/stream/Stream. Method 'java.util.stream.Stream of(java.lang.Object)' at index 452 is CONSTANT_MethodRef and should be CONSTANT_InterfaceMethodRef
```
[crash-2019-10-11_12.39.19-client.txt](https://github.com/sp614x/optifine/files/3717098/crash-2019-10-11_12.39.19-client.txt)
Native minecraft client is not affected

**Comment by sp614x** [comment]
Looks like a problem with OpenJDK.
Duplicate of #2964.
