### ISSUE TITLE
Problem with innerSeams on corner.

### ISSUE THREAD

**Issue by Spook2U** [sp614x/optifine#2966]
InnerSeams does not detect when diagonal a block is places above the "ctm-plane".

Small example: 
When I place 2x2 blocks and on one of these blocks another block, the ctm is not fitting anymore. The block diagonal to the block on top does not fit to the 2 blocks at the side of the diagonal one. So a gap comes up. If a different tile would be used, the gap would be gone.

I attach a small pack with ctm textures for sandstone and 2 pics showing the problem.
[InnerSeams_problem.zip](https://github.com/sp614x/optifine/files/3717822/InnerSeams_problem.zip)

**Comment by sp614x** [comment]
Is thisversion working better?
https://optifine.net/tmp/OptiFine_1.14.4_HD_U_F4_pre9_CTM.jar

**Comment by Spook2U** [comment]
Yes! This fixed the problem.

**Comment by sp614x** [comment]
Coming in next preview.
