### ISSUE TITLE
Donkey model issue

### ISSUE THREAD

**Issue by Tricksz74** [sp614x/optifine#2968]
I have a render issue with the donkey model. Same problem with horse and mule. Any solution to fix this?
![2019-09-16_12 36 12](https://user-images.githubusercontent.com/55388142/64951927-4addb200-d87f-11e9-9ba1-4d8702e2bf1f.png)

**Comment by NitroCipher** [comment]
Please do not post duplicate issues

**Comment by Tricksz74** [comment]
what? My last connection was 3 weeks ago.

**Comment by realjackasterisk** [comment]
you really don't need to post this 3 times in a row. stop it.

**Comment by sp614x** [comment]
Works for me:

![image](https://user-images.githubusercontent.com/16635441/66761438-51724000-eea4-11e9-864d-11ece5fcdef8.png)

**Comment by Tricksz74** [comment]
the problem is the cem and i don't know how to fix the model
