### ISSUE TITLE
Crash with Aether on getEmissiveTexture()

### ISSUE THREAD

**Issue by TimeConqueror** [sp614x/optifine#2969]
[latest.log](https://github.com/sp614x/optifine/files/3722162/latest.log) (Check the end of the file)
So when I entered aether second time, this error was appeared and it don't want to get away, it freezes the game on world init.

**Comment by sp614x** [comment]
Does it work with OptiFine 1.12.2 F4_pre3?

**Comment by TimeConqueror** [comment]
![image](https://user-images.githubusercontent.com/25156941/67622219-f5eb6f00-f820-11e9-806c-b95963479c20.png)
Can't see this preview version for 1.12.2

**Comment by TimeHawk** [comment]
It has been replaced by the stable build of F4.

**Comment by TimeConqueror** [comment]
Yes, all works! Thanks!
