### ISSUE TITLE
[REQUEST] Fast pre-rendered skyboxes

### ISSUE THREAD

**Issue by NickDoom-IDKFA** [sp614x/optifine#2973]
Please make pre-rendered skyboxes (for example, configurable for each 8x8x8 to 64x64x64 blocks).

It's possible to refresh them, for example, every time the local player is sleeping. They can use, for example, configurable distance from RenderDistance x 2 to RenderDistance x 64, and temporarily load those chunks for refreshing those skyboxes.

So the data chain will look like (for each M x M x M cube in RenderDistance x N):

- Temporarily loaded actual chunks in RenderDistance x N
- Rendered skybox in meta-colors (including, for example, the Artifical Light channel)
- Lossy compression (for example, a simple RLE)
- Resulting pre-rendered skybox stored for each M x M x M cube
- Decompressed data in meta-colors
- Applied effects (night, underwater etc; blocks with Artifical Light remain bright, others get dark etc)
- Actual skybox texture
- Actual chunks in RenderDistance which are rendered over the skybox the usual way.

It'll greatly increase the visible distance, taking nearly no CPU time (1..4 takes place while the player is sleeping, 5..7 must be calculated once per M x M x M cube when player is crossing the border). Of course, they can become obsolete but it's much better than the distance fog, and total devastation of huge mountains does not happen often ;) Near the edge of RenderDistance x N they also become single-sided, but bed will fix it as well.

Of course, you can use a better refreshing algorithm (I'm speaking about a simple one).

**Comment by sp614x** [comment]
`Temporarily loaded actual chunks in RenderDistance x N`

This is the problem. The chunks are loaded by the integrated server using a complicated logic. Anything related to custom chunk loading is going to be:
- complicated
- performance problem

**Comment by sp614x** [comment]
What may be possible is to create views for all sides of each cubic chunk (16x16x16). Up to render distance the cubic chunks are rendered full, above render distance the front view of the cubic chunk is rendered. This would need iteration over much more cubic chunks which would be slower. Also changing between front and side views would look strange.
