### ISSUE TITLE
Display image instead of model in inventory

### ISSUE THREAD

**Issue by Hax4Ever** [sp614x/optifine#2977]
Title explains it all, an option to display a custom image instead of a 3D model would be useful for making stylized packs, one could just make an image with a _inventory suffix in the items folder (blocks would also be put in the items folder ig)

Another useful thing would be the option to apply a downscaling filter for these that way we could make a 64x64 image and it could downscale to 32x32 based on the UI size without distorting and looking ugly, but that's more of a side feature.

**Comment by realjackasterisk** [comment]
Can't you already do this in vanilla...?

**Comment by asbyth** [comment]
![image](https://user-images.githubusercontent.com/36578995/66949746-0fbcd300-f025-11e9-8f32-cab35bd4302b.png)
not sure if this is really "possible" in vanilla @realjackasterisk, an example given by WantedRobot in the discord

**Comment by sp614x** [comment]
The vanilla block model format allows a different model for inventory (gui): https://minecraft.gamepedia.com/Model#Block_models

The model can be just a textured quad which is the same as an icon. The models are automatically downscaled with mipmaps (when enabled).
