### ISSUE TITLE
Forge v28.1.61 Breaks CTM Textures

### ISSUE THREAD

**Issue by WenXin20** [sp614x/optifine#2985]
Optifine vHD_U_F4_pre10
Forge v28.1.61

Newer Forge versions, tested with Forge v28.1.56 and v28.1.61 appear to have broken CTM textures that I had created. Below are two images being compared. The only thing I changed between images was the Forge version. Tested with only Optifine and Forge.

With Forge v28.1.46: 
![2019-10-18_11 01 42](https://user-images.githubusercontent.com/12000593/67123399-d36cac80-f1b5-11e9-8fac-8f248957afca.png)

With Forge v28.1.61:
![2019-10-18_13 59 40](https://user-images.githubusercontent.com/12000593/67123503-1890de80-f1b6-11e9-98f4-23ae0b96ed58.png)

**Comment by sp614x** [comment]
Should be working in pre11.
