### ISSUE TITLE
Opaque Objects in the Skybox

### ISSUE THREAD

**Issue by SkaliberWasTaken** [sp614x/optifine#2987]
I'm struggling to find a method of making objects in the skybox opaque, as can be seen in my screenshot.
As far as i can see, the blend methods are all designed for skyboxes changing based on time, and not for objects being in the skybox, disconnected from the main sky.
If i wanted to have secondary objects in the sky, such as this soon-to-be planet texture, which sits not rotating on the horizon, can i make it completely opaque all the time? Because currently the sun and stars look like they're infront of it.
Is this a thing we can already do, or do we need a new blend method such as "opaque" of "full"

Huge fan of your work (:

![2019-10-19_02 12 12](https://user-images.githubusercontent.com/50083260/67143778-e68b8500-f266-11e9-97e8-9c751bf5ffbe.png)

**Comment by SkaliberWasTaken** [comment]
Any update on this? It's still messy to add opaque objects to the skybox, and the multitude of blend methods we have are arguably useless.

**Comment by sp614x** [comment]
The sky and custom sky are rendered first. 
The sun and moon are rendered second, so they will always be in front of the sky.
