### ISSUE TITLE
Optifine Not Compatible With 1.12.2 Forge

### ISSUE THREAD

**Issue by TheGoldenCdr** [sp614x/optifine#2991]
I've been trying to load Optifine 1.12.2 E3, but it is not working. The error states, "Incompatible version, Use Optifine F series." Or something similar.

**Comment by TimeHawk** [comment]
Then use F series it's under the preview versions

**Comment by TheGoldenCdr** [comment]
But isn't F series for 1.14 though.

**Comment by Studio528-real** [comment]
and 1.12.2 there is a backport
https://optifine.net/adloadx?f=preview_OptiFine_1.12.2_HD_U_F4_pre3.jar

**Comment by TimeHawk** [comment]
![image](https://user-images.githubusercontent.com/55647109/67151837-57479700-f291-11e9-8bf6-59d2062fa23d.png)
well there are 1.12.2 versions

**Comment by TheGoldenCdr** [comment]
oh, thank you very much.
