### ISSUE TITLE
[1.12.2] Release OptiFine 1.12.2 F4 (crtical bugfix)

### ISSUE THREAD

**Issue by Speiger** [sp614x/optifine#2994]
Just to show the issue can be commented on and has not be hidden.
Referencing: #2990 #2991 
Dev you can leave this open. This is just for me. Not for you

**Comment by sp614x** [comment]
There are no private issues in the tracker, everone can contribute.
Renamed to properly reflect what is needed.

**Comment by sp614x** [comment]
Preview 1.12.2 F4_pre11 is out.

**Comment by sp614x** [comment]
Preview 1.12.2 F4_pre12 is out with more bugfixes.

**Comment by sp614x** [comment]
OptiFine 1.12.2_HD_U_F4 is out.

**Comment by Speiger** [comment]
@sp614x finally.
Next time. When you fix a crash bug.
What do you do?
Release it in a reasonable time and dont skip 6 versions. Ok?
Because next time I wont be that nice again if that happens ever again.
Are we clear?

**Comment by sp614x** [comment]
Bugfixes are released when they are ready.
If you aren't nice you will be banned from the github repo and you won't be able to comment any more.

**Comment by Speiger** [comment]
Released when ready? 6 version skipped and 10 months about releases. If that happens again then you warning is worth shit because everybody has a legit reason to be pissed at your mistake.

Don't let that happen again and we have a nice time.

**Comment by bageldotjpg** [comment]
literally just shut up Spieger, you got your release, now stop whining

**Comment by jjamess10** [comment]
Nobody has a reason to be pissed. It's a completely free performance mod. He doesn't owe anyone shit. Keep up the great work SP, appreciate all you do for the community

**Comment by sp614x** [comment]
Banned @Speiger.

**Comment by KaneHart** [comment]
Does this mean this was fixed? 

Don't care if someone got banned but it's a nice tool for worldgen / previewing. 

If not please re-open and take your drama elsewhere.

**Comment by NitroCipher** [comment]
Yes! OptiFine 1.12.2 F4 has been long released. We are now actually on version F5
