### ISSUE TITLE
Is it possible to use OptiFine's Dynamic Lighting on top of a shader? 

### ISSUE THREAD

**Issue by CartBeats** [sp614x/optifine#2996]
I'm using SEUS Renewed v1.0.0 and OptiFine 1.12.2 HD U E3 in a 1.12.2 modpack. 

I'm having some issues with SEUS in that it's not registering modded items as light sources. I tried figuring out how to add them in the source files but had no luck. 

I wanted to try using a different implementation of dynamic lighting rather than the buggy one that SEUS uses, so I disabled SEUS's dynamic lighting [as per this thread](https://www.reddit.com/r/Minecraft/comments/bcsuh1/seus_renewed_100_dynamic_light_question/). This was effective in disabling dynamic lighting completely.

I then went into the Optifine settings and enabled dynamic lighting. However it had no effect. I tried a game restart and that didn't help either. 

Is there a particular reason OptiFine's dynamic lighting won't work when a shader is installed?

**Comment by sp614x** [comment]
Dynamic Lights should work with most shader packs.
Some shaders (seus ptgi, mollyvx) ignore the MC lighting information and calculate it themselves.

**Comment by CartBeats** [comment]
I went into the optionsof.txt document in the .minecraft directory and manually changed the "ofDynamicLights" setting from 3 to 2. Reloading the game showed it working as intended, along with properly adding light to the modded items that weren't working with SEUS dynamic lighting. I was then able to enable and disable OptiFine dynamic lighting using the in-game options menu as well. Not sure why it didn't work the first time I tried it, but at least it seems to be working now.  

On the off chance that a modded item doesn't have lighting applied to it by default, is there a configuration file for specifying exactly which items should give off light when held or dropped?

**Comment by sp614x** [comment]
All blocks (vanilla or modded) that emit light are automatically recognized.
Mods can also use `dynamic_lights.properties` to add light emitting items and entities.
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/dynamic_lights.properties
