### ISSUE TITLE
Animals emit light for no reason

### ISSUE THREAD

**Issue by SepSol** [sp614x/optifine#2998]
**Namely:**
- Minecraft's vanilla Phantoms

![2019-10-22_15 52 29](https://user-images.githubusercontent.com/47871887/67285232-0d0a2400-f4e4-11e9-8b87-ef03c43a0bc5.png)

- [Better Animal Model](https://www.curseforge.com/minecraft/mc-mods/better-animal-models) mod's Spiders

![image](https://user-images.githubusercontent.com/47871887/67284320-4346a400-f4e2-11e9-8c37-69ff83bf30e2.png)

- [Better Animal Model](https://www.curseforge.com/minecraft/mc-mods/better-animal-models) mod's Cave Spiders

![image](https://user-images.githubusercontent.com/47871887/67285144-e64bed80-f4e3-11e9-85e1-9aa3db23be8c.png)

**Context:**
I reported the issue on their issue tracker and everybody said that it's a shader bug. And shader devs say it's because of an OptiFine bug. So I posted it here. (Somebody mentioned something as a "Glow Layer" being on top of these animals that is causing this issue.)

**Specs:**
Minecraft 1.14.4
Forge 28.1.0 (also tried 28.1.61)
OptiFine HD U F4 pre4 (tried pre9 and pre11)
_none-pre versions didn't load on Forge 28.1.0 (stable)_

**Shaders:**
I usually use one of these:
- SEUS Renewed v1.0.0
- Sildur's Vibrant Shaders v1.23

**Comment by sp614x** [comment]
The phantom eyes should glow in the dark. It is rendered similar to the spider and the enderman.
The glowing eyes are rendered on a separate shader program "gbuffers_spidereyes".
Curently the phantom glowing texture is not handled by OptiFine (like spider/enderman) so it shouldn't be glowing with shaders.
The shader pack may be trying to detect the glowing texture by other means (alpha, color, etc.).

**Comment by Phoenixdotexe** [comment]
So is there a workaround for this?
