### ISSUE TITLE
Overlay ctm doesn't work with transparent/translucent blocks

### ISSUE THREAD

**Issue by Flambou** [sp614x/optifine#300]
It seems like the ConnectBlock and ConnectTile specifications aren't working for transparent blocks e.g. glas or leaves. Also it would be nice to make it possible for all ctm methods to be overlayed with an own tintIndex

**Comment by sp614x** [comment]
CTM connect by tile and by block should work for transparent blocks. The error log may have more details.
Link to resource pack that is not working?

**Comment by Flambou** [comment]
I didn't meant the connect by tile for ctm. When you use the overlay method you can't specify a transparent block to be the neighbour as an "activator". Either way here is an example resourcepack which shows the problem. https://www.dropbox.com/s/r0x2xk7ao7jsjft/Testpack.zip?dl=0
Also it would be nice overlay (with specific tintIndex) textures when using methods like fixed or random.

**Comment by sp614x** [comment]
Currently the neighbour can not be a transparent cube. 
The limit could be removed, then it would look like this: http://i.imgur.com/ciN6xDP.png

**Comment by Flambou** [comment]
Is there a particular reason why the limit has been implemented? I would really appreciate if it would be removed.

**Comment by sp614x** [comment]
The limit is a performance optimization and also when the overlay is on a transparent block it is not visible from below which looks strange: 
- from above: http://i.imgur.com/QGcueIJ.png 
- from below: http://i.imgur.com/wScqcwn.png

If this is not a problem, the limit can be removed.

**Comment by sp614x** [comment]
Updated overlays to check for a full cube model instead of opaque cube. It should work for glass, stained glass and ice. Coming in next preview D3.

**Comment by Flambou** [comment]
Thank you very much :D
