### ISSUE TITLE
[1.14.4] `Config.isShaders()` returns false while switching shader packs

### ISSUE THREAD

**Issue by Cadiboo** [sp614x/optifine#3001]
*I'm pretty sure I also had this issue in 1.12.2 but I never tracked down the cause of it.*

`Config.isShaders()` returns the value of `Shaders.shaderPackLoaded` which is false while one shader pack is being unloaded and another is being loaded. If quads are rendered while the shader packs are being swapped, `BakedQuad#getVertexData()` will call `BakedQuad#fixVertexData()` which will call `BakedQuad#compactVertexData` because `Config.isShaders()` returns false. This results in the quad vertex data being half the size expected for use with the quad's vertex data.
##### Example:
```java
int[] vertexData = quad.getVertexData();
int formatSize = quad.getFormat().getIntegerSize();
```
In this example `quad.getVertexData()` causes the vertex data to be (wrongly) compacted, so it is half the expected size. However, `formatSize` is not effected as the format has not changed. Using formatSize to get data from the quad will return wrong data and cause an ArrayIndexOutOfBoundsException on the 3rd vertex as the vertex data is only half the size.

The following code code can be used as a workaround
```java
int[] vertexData = quad.getVertexData();
int formatSize = quad.getFormat().getIntegerSize();
// Work around a bug in OptiFine when switching shaders
if (formatSize * 4 > vertexData.length)
	formatSize /= 2;
```

This can be fixed in OptiFine by making a new field in `Shaders` called `shadersActive` and only changing that if shaders are actually unloaded rather than if they are swapped. `Config.isShaders()` would then use that value instead of `Shaders.shaderPackLoaded`

**Comment by sp614x** [comment]
Multi-threaded problem caused by chunk builder threads working in the background while the shader pack is reloaded on the main thread. Probably also affects the AO lighting.
The correct fix is to pause all chunk updates while reloading the shaders, thus fixing all multi-threaded race conditions.

**Comment by sp614x** [comment]
Fixed, coming in next version.
