### ISSUE TITLE
Latest preview Optifine version is missing on the website

### ISSUE THREAD

**Issue by marcvidalim** [sp614x/optifine#3004]
Hi there,

Excuse me for annoying with this, but I cannot download the latest Optifine preview version, it's missing on the website: https://optifine.net/downloads

In this thread (https://github.com/sp614x/optifine/issues/3003), which has been created a few hours ago, I could see a screenshot making reference to 1.14.4-Optifine_HD_U_F4_pre11.

How can I download it?

Thank you for your time.

**Comment by realjackasterisk** [comment]
You can't download it because it's not a preview anymore. It was literally released last night.

**Comment by sp614x** [comment]
OptiFine 1.14.4 F4 is already released.
