### ISSUE TITLE
Instant kick from server 1.14.4

### ISSUE THREAD

**Issue by ccar795** [sp614x/optifine#3007]
Forge Version: 28.1.56
Optifine Version: 1.14.4 HD U F4
So as the title says I get insta kicked but only when optifine is installed. This is what the kick message says https://imgur.com/a/LISZMfm
This only happens with spigot servers, vanilla servers are fine.

**Comment by sp614x** [comment]
Java 9+?
Can you post a screenshot?

**Comment by ccar795** [comment]
![2019-10-23_14 43 50](https://user-images.githubusercontent.com/21349871/67436601-a2202200-f5a3-11e9-8318-d684bb01ec77.png)

**Comment by sp614x** [comment]
You are running with Forge. It changes the client/server communication which is the problem.
You can install OF and run it standalone (no Forge).

**Comment by JoJoDeveloping** [comment]
Do you happen to know some more about this so that forge/spigot people can look into fixing it?

**Comment by sp614x** [comment]
No idea.
If the problem is identical with Forge only without OptiFine, then it is not related to OptiFine.
