### ISSUE TITLE
Crash when trying to put shaders back on

### ISSUE THREAD

**Issue by flyingyalie** [sp614x/optifine#3009]
MC 1.12.2
Optifine 1.12.2_HD_U_F4

Issue: I was using shaders and then turned them off (switched back to vanilla shader) so I could see better with a mod I was using. When I went to switch back to the shader the game crashed. I tried switching shaders on the home screen as well, same issue. Also tried multiple shaders inclduing the internal one. 

[crash-2019-10-23_23.55.18-client.txt](https://github.com/sp614x/optifine/files/3765648/crash-2019-10-23_23.55.18-client.txt)

**Comment by sp614x** [comment]
F4 is updated with a bugfix, please redownload it.
