### ISSUE TITLE
OptiFine 1.14.4 HD U F4 OpenGL Error 1281

### ISSUE THREAD

**Issue by Francy-Chan** [sp614x/optifine#3015]
-Disabling VBOs seems to stop the errors.
Log:
[latest.log](https://github.com/sp614x/optifine/files/3769713/latest.log)

**Comment by Studio528-real** [comment]
GL errors dont mean anything, go to "Other" in your video settings and click 
![image](https://user-images.githubusercontent.com/52116771/67538681-138fcb80-f69d-11e9-9b52-12c6f11ce354.png) to off

**Comment by Francy-Chan** [comment]
Already did it, but it stills display the errors on the log, so it's hard to read anything there, especially if I'm developing a resource pack.

**Comment by sp614x** [comment]
OpenGL errors from VBOs are usually a driver problem.
You can either disable VBOs or set "Show OpenGL errors" to OFF.
