### ISSUE TITLE
[Request] Random mobs breeding.

### ISSUE THREAD

**Issue by MastaNub** [sp614x/optifine#3016]
If I change the texture of a pig using optifine/random to a, let's say, a cow!... then breed the two cow-textured pigs together... The outcome is still randomized. Would it be possible to make two random mobs breed and make the outcome a randomized version of its parents?

**Comment by sp614x** [comment]
This is not possible. Each mob has a random ID which is created when it is spawned and it has no relation to the parents' IDs.

**Comment by MastaNub** [comment]
Would you be able to make them relate to their parents?

**Comment by sp614x** [comment]
No, mob spawning is handled by the (integrated) server and is part of the game mechanics.
Also it would be hard to define how one random ID would be dependant on two other random IDs.
