### ISSUE TITLE
Animated end sky causes minimum FPS to cap at 60.

### ISSUE THREAD

**Issue by MastaNub** [sp614x/optifine#3020]
What the title says.
![image](https://user-images.githubusercontent.com/35407179/67627445-8db68080-f854-11e9-9e7c-ef095398842f.png)
Turning animated textures fixes the issue. I have smart animations ON.

**Comment by sp614x** [comment]
The tick spikes are probably caused by the animated textures.
The end sky texture is probably too big and it needs too much resources.
