### ISSUE TITLE
OptiFine download page identified as unsafe by Norton

### ISSUE THREAD

**Issue by fakehero12211101** [sp614x/optifine#3021]
Hi, I'm trying to download Optifine 1.14.4 onto a Macbook with Chrome and the Norton SafeWeb extension. I go to the website "https://www.optifine.net/downloads", then select the "Download" option for OptiFine 1.14.4 HD U F4. The link address is identified as "http://adf.ly/404181/optifine.net/adloadx?f=OptiFine_1.14.4_HD_U_F4.jar&x=f2d7". However, when I try to go there, this happens:
In case the screenshot isn't loading, what happens is that Norton SafeWeb says:
"Malicious Site Blocked! 
You attempted to access: 
http://d1nmxiiewlx627.cloudfront.net/?ixmnd...
This web site is a known malicious web page. It is highly recommended that you do NOT visit this page."
![Screen Shot 2019-10-26 at 10 40 32 PM](https://user-images.githubusercontent.com/53795109/67628852-9dc56480-f842-11e9-8693-d59bb47dbd83.png)

**Comment by TimeHawk** [comment]
Yeah its because adfly is very weird and can probably give you viruses, just disable your antivirus and wait 5 seconds for the skip ad button on the top right, or use the mirror links provided.

**Comment by fakehero12211101** [comment]
Update: plugging the URL that the download link shunts me over to almost as soon as I click it (don't go here: http://d1nmxiiewlx627.cloudfront.net/?ixmnd=709056) into VirusTotal returns that three different databases identify the site as definite malware.
![Screen Shot 2019-10-26 at 10 59 49 PM](https://user-images.githubusercontent.com/53795109/67628928-563fd800-f844-11e9-92a8-bef2540119e9.png)

**Comment by Studio528-real** [comment]
few things, only download from the mirror link, Norton while good at doing that otherwise sucks pretty much, adfly is never safe. use ublock origin to skip adfly always fi there is no other alternative

**Comment by KaiAF** [comment]
I assume this was resolved a long time ago
