### ISSUE TITLE
[1.14.4] Patching over Forge ATs

### ISSUE THREAD

**Issue by itsmeow** [sp614x/optifine#3034]
So, this issue is quite a pain to me as it has caused quite a few issues (https://github.com/itsmeow/whisperwoods/issues/2 https://github.com/itsmeow/whisperwoods/issues/3)
Basically, as far as I can tell, Optifine is patching over classes that contain Forge Access Transformers and completely replacing them with a non-accessible version, causing any such attempts to access them to create illegal access exceptions (see crash https://pastebin.com/xndUKcyR from https://github.com/itsmeow/whisperwoods/issues/2)
I understand that Forge and Optifine may patch similar areas, but it seems Optifine is completely overwriting unnecessary parts (The `IParticleMetaFactory` class is a functional interface that I can most likely guarantee is not needed to be patched by Optifine)

**Comment by Barteks2x** [comment]
This should be already fixes starting with optifine pre9 if it's the same issue as https://github.com/sp614x/optifine/issues/2944

**Comment by itsmeow** [comment]
Ah, suppose it is. Okay, thanks for the fix. Sorry for the bother. I'll tell my users to use the preview versions.

**Comment by TimeHawk** [comment]
Hey, umm... you know the preview versions of 1.12.2 and 1.14.4 don't exist anymore right? The stable version of F4 is the replacement.

**Comment by itsmeow** [comment]
Huh. Okay. Maybe I should tell my users to stop using preview versions. I personally couldn't reproduce the crash on F4, maybe that's why.
