### ISSUE TITLE
Long startup time with Optifine, JEI, and Actually Additions

### ISSUE THREAD

**Issue by mezz** [sp614x/optifine#304]
- During startup (`FMLLoadCompleteEvent`), JEI grabs all the tooltips from items. 
- Actually Additions has a tooltip handler that checks if certain keys are pressed in order to decide if it should show extra information on the tooltip.
- For some reason, adding Optifine makes Actually Additions' tooltip handler incredibly slow.

Without Optifine:

![load-without-optifine](https://cloud.githubusercontent.com/assets/916092/19782946/e9d10012-9c44-11e6-9c36-aa2b03609942.png)

With Optifine: 

![load-with-optifine](https://cloud.githubusercontent.com/assets/916092/19782955/f262ba36-9c44-11e6-9ca4-8a4250bb91b4.png)

This profiling  was done on a regular pack, but it has also been confirmed using a minimal setup and latest versions:
Minecraft 1.10.2
Forge 12.18.2.2114
[JEI 3.13.0.334](https://minecraft.curseforge.com/projects/just-enough-items-jei/files)
Optifine HD_U_D2_pre
[Actually Additions r67](https://minecraft.curseforge.com/projects/actually-additions/files)

**Comment by sp614x** [comment]
OptiFine does not change anything related to keyboard handling.

The LWJGL "Keyboard.isKeyDown()" looks like:

    private static final ByteBuffer keyDownBuffer = BufferUtils.createByteBuffer(256);

    public static boolean isKeyDown(int key)
    {
      synchronized (OpenGLPackageAccess.global_lock) {
        if (!created)
          throw new IllegalStateException("Keyboard must be created before you can query key state");
        return keyDownBuffer.get(key) != 0;
      }
    }

The "OpenGLPackageAccess.global_lock" is only used by Keyboard and Mouse functions:

![](http://i.imgur.com/tSVTQhf.png)

And the "keyDownBuffer.get(key)" shuld be very fast, it is a ByteBuffer.

**Comment by mezz** [comment]
Thanks, I had hope you were doing something, because this issue is very difficult to pin down.

**Comment by mezz** [comment]
Looks like it has to do with the splash screen loading bars. If I disable the splash screen (`config/forge/splash.properties`), everything loads quickly.

**Comment by mezz** [comment]
This appears to be a conflict between vsync (set by Optifine by default), the splash screen, and checking the keyboard. I'm doubtful that Optifine is to blame here.

**Comment by mezz** [comment]
Confirmed that this is a complex issue involving those three things and Optifine is not the cause.

**Comment by sp614x** [comment]
Duplicate of #501.
