### ISSUE TITLE
Overlay Textures Not Working With Carpets

### ISSUE THREAD

**Issue by Klautos** [sp614x/optifine#3048]
Are overlay textures not possible with carpets?

I'm trying to get the carpets to overlay onto the blocks next to them but it's not working.  This is a little different because I don't necessarily want the overlay on the block exactly next to the carpet (because it would be up too high) but the block next to, and down one from the carpet, obviously.

all images and properties file seem to be in good shape but no results in-game.

Any help?
Thanks

**Comment by sp614x** [comment]
CTM overlays only work with full blocks.

**Comment by Klautos** [comment]
Ah!  Well that certainly explains it!  Thanks for the 411 :)

**Comment by Klautos** [comment]
Ah!  Well that certainly explains it.  Thanks for the 411 :)
