### ISSUE TITLE
CTM for Mod Textures not functioning

### ISSUE THREAD

**Issue by Megistus** [sp614x/optifine#305]
Below example is the .properties file for a tinkers construct block. This is just one example of many that I have in my pack that are non-functional. It does not break the game nor render pink/black texture, it just isn't running.

matchTiles=tconstruct:brownstone/road
tiles=0-3 4-7 8-11
method=repeat
width=4
height=3
faces=all

**Comment by sp614x** [comment]
TConstruct does not have a texture "assets/tconstruct/textures/brownstone/road.png".
You probably mean "matchTiles=tconstruct:blocks/brownstone/road".

**Comment by Megistus** [comment]
Syntax has changed from 1.7 to 1.10 ... good to know.

However, making that change to matchTiles=tconstruct:blocks/brownstone/road still does not function and base texture is still being used and not ctm textures.

**Comment by sp614x** [comment]
This works for me:
`matchTiles=tconstruct:blocks/brownstone/road`

Default: http://i.imgur.com/BtFARzz.png
CTM: http://i.imgur.com/PEzTJV8.png

**Comment by Megistus** [comment]
*hangs head in shame* ... Sorry, figured out where my issue was. Had mcpatcher folder in wrong location (what I get working with multiple resource packs.) Sorry for the trouble.
