### ISSUE TITLE
[CEM] Missing dolphin part

### ISSUE THREAD

**Issue by MushirMickeyJoe** [sp614x/optifine#3051]
I'd like to change the tail fin of dolphins, but the tail and the tail fin are merged into one part, even though they're clearly independent parts in the vanilla model. Not entirely sure how to describe this, but [here](https://i.gyazo.com/820894491ac653bc6d96f51546bc62f8.mp4) you see how the vanilla dophin's tail moves. There's two separate parts to the tail. An actual tail fin, and a tail/body part.

Currently it's only possible to replace the `tail` part, but that'd reduce some of the animations of the dolphin. pls fix

what it looks like when I try to replace the 'tail' part: 
![image](https://user-images.githubusercontent.com/31923214/68351782-c2ec8980-0104-11ea-82b2-4ae571ee22a3.png)

**Comment by DragendGhast** [comment]
This. I have encountered this problem myself and would love to see it fixed.
![2019-11-11_15 09 15](https://user-images.githubusercontent.com/49409042/68617475-5f13e900-0495-11ea-8971-aa1734e480be.png)

**Comment by jesver** [comment]
hey i am having the same problem. is there a solution found yet?

**Comment by sp614x** [comment]
Fixed in 1.16.2 pre4

**Comment by jesver** [comment]
i use blockbench and want to use .jpm. i saw in blockbench that there is a floder for tail and in that folder is a folder called tail_fin. but when i use tail_fin in my .jem it doesn't work. i think this is because it is in the tail folder. how do i attach a part to the tail_fin?
