### ISSUE TITLE
Add gbuffers_translucent

### ISSUE THREAD

**Issue by zombye** [sp614x/optifine#306]
This would be used for all translucent blocks except for water.

If it does not exist in a shaderpack, gbuffers_water is used instead, to maintain compatibility with older shaderpacks.

This would be nice to have, as I won't have to effectively put two different shader programs into one with the current plans I have for my shaderpack.

**Comment by sp614x** [comment]
All translucent blocks (water, ice, stained glass, etc) are rendered together in one pass so it is not possible to use different programs.
