### ISSUE TITLE
[suggestion] Weather, Moon Phase, Time of Day CTM methods 

### ISSUE THREAD

**Issue by bageldotjpg** [sp614x/optifine#3061]
CTM should add settings based on
- Moon Phase
- Time of Day
- Weather
Basically the same things as the random entities version, but for blocks too. I think more dynamic CTM stuff would be great. Moon phases could be used to create a season cycle based on a season every two moon phases or something. Or create a clock model that changes with the time.

**Comment by Studio528-real** [comment]
ctm would be good, random mobs one got added, though I think it would be a lot harder to add it for CTM

**Comment by sp614x** [comment]
The filters can be added, but the blocks won't change their textures until the chunk is reloaded. 
Forcing reload of all chunks on time/weather/moon_phase change is not practical and would look bad.
CTM can only use filters that are either fixed (position, biome) or automatically trigger a reload of the affected chunk (neighbours, light, etc.).

**Comment by sp614x** [comment]
The time/weather/moon_phase filters could be added to custom animations which would allow block textures to react to dynamic factors.
