### ISSUE TITLE
Custom Creeper heads(block) are not possible

### ISSUE THREAD

**Issue by DragendGhast** [sp614x/optifine#3063]
You can not change the model of the Creeper head using CEM at all, it will just refer to where it originally was on the texture and if you change the head model it will totally break.
![2019-11-11_15 40 28](https://user-images.githubusercontent.com/49409042/68619513-9c7a7580-0499-11ea-8bf2-b814979fb98e.png)

**Comment by Locxes** [comment]
creeper head is actually a block. They have separate models.

**Comment by LIUKRAST** [comment]
creeper head is not actually a block. I had some issues with this thing but then realized that the custom JEM file for the creeper head is `head_creeper.jem` and not `creeper_head.jem`

**Comment by DragendGhast** [comment]
> creeper head is not actually a block. I had some issues with this thing but then realized that the custom JEM file for the creeper head is `head_creeper.jem` and not `creeper_head.jem`

I can't tell you how happy I am for you telling me this, this so-called "bug' has been bothering me for SO LONG.
Thank you!
