### ISSUE TITLE
OBS crashes with any Minecraft OptiFine version

### ISSUE THREAD

**Issue by karl-police** [sp614x/optifine#3064]
OBS crashes with any Minecraft OptiFine version when Minecraft is using NVIDIA GPU and OBS too and in OBS you have to use Game Capture.

Issue does not happen when not in an OptiFine mod. To force the crash just click on the taskbar on the minecraft icon or alt tab out of it a couple of times.

https://obsproject.com/

**Comment by sp614x** [comment]
This is a native crash in the NVidia driver:
https://pastebin.com/pnj8fLti

Can't be fixed by OptiFine.
