### ISSUE TITLE
[Suggestion] Make dropped items blink before despawning

### ISSUE THREAD

**Issue by Regnander** [sp614x/optifine#3066]
Whenever dropped items in video games are about to disappear, they will usually start to blink as a way for the game to tell the player to hurry and pick them up if they still want to keep them.

In Minecraft, however, items despawn after 5 minutes (or 6000 ticks [according to the wiki](https://minecraft.gamepedia.com/Item_(entity))) with no warning what so ever. Why not bring this mechanic to Minecraft as well?

As far as when it should start blinking, I believe somewhere between 15 to 30 seconds before despawning should be enough.

![ezgif-4-e23e50bdc31e](https://user-images.githubusercontent.com/17113053/68804235-90411480-0661-11ea-915b-2340e717478d.gif)

**Comment by sp614x** [comment]
This could be added, but having the items blink in and out of existence is not very realistic.
It would also not work in multiplayer as the server doesn't send the entity age to the client.
