### ISSUE TITLE
Optifine does not install

### ISSUE THREAD

**Issue by Mackerrr** [sp614x/optifine#3067]
So I download any version of optifine for Minecraft 1.14.4 (no, I have not tested it for other versions but 1.14.4 is my main focus/concern) and run the .jar file with Java, and the installer pops up. I hit install, and it says the installation was successful, but then when I open the launcher the profile is not there. I used to have the profile there and accidentally deleted it, and now that is happening when I try to reinstall it. I have tried all versions of optifine 1.14.4, from F1-F4. I have permanently deleted the .jar files off my hard drive and reinstalled them, and the issue persists. I have an optifine profile for both 1.12.2 and 1.13.2 that was already installed before this issue started occurring. I can find no cause and I have even tried to export into the .minecraft folder using the export function. The profile has not shown up once. This issue started 2 days ago, and the last time I remember installing optifine was about 1-2 months ago, which went perfectly fine (version F4). I would be willing to provide more info and possibly footage if needed. And yes, I did install the profile off the optifine.net site. Help would be appreciated. Thanks, Macker

**Comment by TimeHawk** [comment]
Can't you make your own profile with OptiFine 1.14.4 as the version?

**Comment by Mackerrr** [comment]
Thank you so much! I feel dumb right now lol. Yes, it seems as if you can do that. Thanks!
