### ISSUE TITLE
1.8.9 L4 Bugs

### ISSUE THREAD

**Issue by asbyth** [sp614x/optifine#3068]
Making this so you can keep better track of bugs with the new pre-release
- Stretched out textures with shaders (BSL 7.1.04.1)
![image](https://user-images.githubusercontent.com/36578995/68908342-f8066680-0718-11ea-9a47-ec3c0b96ff7f.png)

- Resource pack setting doesn't save

**Comment by sp614x** [comment]
Is this with Forge installed or OptiFine standalone?
Other mods installed?
Is this fixed when reloading the resource pack?
What resource pack settings are not saved?

**Comment by asbyth** [comment]
> Is this with Forge installed or OptiFine standalone?
> Other mods installed?
> Is this fixed when reloading the resource pack?
> What resource pack settings are not saved?

Happens on both Forge & standalone
Reloading resources doesn't fix it
The currently selected pack you're using doesn't save, changes back to default when you restart the game

**Comment by asbyth** [comment]
Both issues are still present in pre3

**Comment by asbyth** [comment]
![image](https://user-images.githubusercontent.com/36578995/69015864-a8b57580-0966-11ea-830e-bba7fd94e908.png)
- Armor textures randomly delete themselves (using default pack)

**Comment by asbyth** [comment]
Armor textures & selected resource packs are fixed in latest pre, stretched out textures are still present though

**Comment by asbyth** [comment]
> Armor textures & selected resource packs are fixed in latest pre, stretched out textures are still present though

nvm armor textures isnt fixed lol

**Comment by asbyth** [comment]
Only issue now is the stretched out textures on stairs

**Comment by sp614x** [comment]
More models are affected: connected fences, connected walls, fence gate:

![image](https://user-images.githubusercontent.com/16635441/69432026-28fa2300-0d39-11ea-97bf-8ea981c08671.png)

**Comment by sp614x** [comment]
Upated OptiFine_1.8.9_HD_U_L5_pre4 with a bugfix for the stairs.
