### ISSUE TITLE
Forge breaks CIT models.

### ISSUE THREAD

**Issue by MastaNub** [sp614x/optifine#3070]
https://cdn.discordapp.com/attachments/425702172219408385/644916919094214674/mieczor.zip

^ pack for the reference. Using latest Optifine 1.14.4 (and tested on 1.14.2). Forge version 28.1.0.

**Comment by RaconteurDM** [comment]
I update the issue. Same problem with the last version of Optifine 1.15.2 (pre 30). It is provide to fix it ?

**Comment by sp614x** [comment]
Fixed in pre13 for 1.16.1.
1.14 and 1.15 will be fixed later.
