### ISSUE TITLE
forge 1.8.9 wont launch 

### ISSUE THREAD

**Issue by bemku** [sp614x/optifine#3072]
So my 1.8.9 forge won't open, with or without mods in it. I have tried re installing forge and nothing changed. I had 1.8.9 forge running for about 4 months until my hard drive broke and now it doesn't work. If i try any non forge versions like normal 1.1.14 it works and i can play. The mods i use all are on 1.8.9 and i cant find them all on another version together so i need this. When creating new profiles i get the same message in the image attached. Can anyone help??

**Comment by sp614x** [comment]
Forge issues should be posted on the Forge issue tracker: https://github.com/MinecraftForge/MinecraftForge/issues
