### ISSUE TITLE
HD_U_E7, Shaders button not showing up.

### ISSUE THREAD

**Issue by Mako-Aluveaux** [sp614x/optifine#3078]
Yeah I cant load any shaders at all on 1.7.10.

 when the mod is installed and the shaders mod, the thing that can actually get the folder to SHOW UP in the menus, causes the game to crash.

The Log says "Please remove the shaders mod optifine has built in shader support" 

This it would seem is a crock of shit.

I am running the tekkit legends mod pack
yes i have the shaderpacks folder in the correct mod pack folder. 
Yes it worked with other versions of optifine and the shader mod.

but for some reason it wont work with the latest one.

I would humbly request that this get fixed, or that i could receive some help to fix this.

**Comment by Mako-Aluveaux** [comment]
By latest one i mean the latest one that is compatible with 1.7.10

Before the YOU'RE AN IDIOT 
brigade shows up telling me to get the correct version or something else equally glib snarky and unhelpful.

**Comment by TimeHawk** [comment]
So you have the shaders mod and OptiFine installed, you only need OptiFine as the log stated because as the log stated OptiFine has shader support it basically has taken over the shaders mod.

**Comment by Mako-Aluveaux** [comment]
Since you clearly cannot read. 

I DO: have optifine installed. Version: HD_U_E7
I DO NOT: have The shaders mod installed.

The shaders mod is the only thing that makes the button appear in the menus.

My problem is that the button to activate the shaders is not showing up despite the "shaderpacks" folder existing and being in the correct directory.

**Comment by sp614x** [comment]
The Shaders Mod button Shaders is in the Options menu.
The OptiFine button Shaders is in the Video Settings menu.
Can you post a screenshot of the Video Settings menu?

**Comment by S-B99** [comment]
This can probably be closed due to inactivity

**Comment by Jiingy** [comment]
Issue has been innactive for 4 years, and a solution has very likely been found by now.
