### ISSUE TITLE
Optifine breaks the RailCraft textures

### ISSUE THREAD

**Issue by Hypsellis** [sp614x/optifine#308]
I link this issue here https://github.com/CovertJaguar/Railcraft/issues/924

**Comment by 4rz0** [comment]
Thanks, was about to add this.
Textures are invisible for me instead, tho.

**Comment by snurre0** [comment]
Having the same problem. Removing Optifine solves it.

**Comment by sp614x** [comment]
Analysis and solution posted in https://github.com/CovertJaguar/Railcraft/issues/924.

**Comment by sp614x** [comment]
Fixed field ordering in OptiFine to match Forge.
However it would be nice if Railcraft uses an official way to re-register sprites instead manipulating private fields via reflection.
