### ISSUE TITLE
Biom  Specific Polarbear issues

### ISSUE THREAD

**Issue by ItsRealezZ** [sp614x/optifine#3080]
I try to do some biom specific texture for polarbear, but, everytime I try, it seem to just randomize the texture insteed of put the texture in relation with the biom. 
This problem seems to happen only with the polarbear, my biom specific pig and creeper work perfectly with the same code.

**Comment by nenuvutive** [comment]
Can you show the .properties file?

**Comment by Monsterfisch** [comment]
when you follow this setup it will work =) https://i.imgur.com/Jz0xjef.png

**Comment by ItsRealezZ** [comment]
> when you follow this setup it will work =) https://i.imgur.com/Jz0xjef.png

Hi, my proprities file look very similar to yours, the only difference is that I don't have the ("name.3="insertaname") line, is this line very important ?
I'll try to send my proprities file as soon as possible !

**Comment by Monsterfisch** [comment]
you need to put "minecraft:" in front of every biomename as it otherwise will not recognise them

**Comment by ItsRealezZ** [comment]
My other biom specific mobs work without it, but I tried it.
As you can see there, it didn't work, I really don't know what to do...
https://imgur.com/a/kEX7pqQ

**Comment by Monsterfisch** [comment]
start by using skin.1 instead of 2

**Comment by ItsRealezZ** [comment]
It finally works !
Thanks a lot for helping !
Have a nice day ;)
By the way, I love your pack ;)

**Comment by Monsterfisch** [comment]
great =) glad I could help also make sure to close the issue ;)
