### ISSUE TITLE
1.8.9 emissive blocks are broken

### ISSUE THREAD

**Issue by MastaNub** [sp614x/optifine#3082]
What happens? https://prnt.sc/py50ar

What should happen? https://prnt.sc/py50ei

I'm basically trying to use emissive blocks, it's completely broken (https://prnt.sc/py50id).

**Comment by sp614x** [comment]
This only happens with shaders, without shaders the emissive textures should be OK.

**Comment by sp614x** [comment]
Fixed, coming in next preview.
