### ISSUE TITLE
1.8.9 animations only play when the time passes

### ISSUE THREAD

**Issue by MastaNub** [sp614x/optifine#3083]
What happens? Custom optifine animation freezes at one frame when pausing the game. http://prntscr.com/py5226

What should happen? Animation should play even if the game is paused. 
![ezgif-1-1edeb518ef45](https://user-images.githubusercontent.com/35407179/69009272-a8f44780-094b-11ea-99ca-6ad0ca1f7fa1.gif)

Note: this isn't affected by smart animations. 
When "Open to LAN" is ON then animation plays as normal.

**Comment by sp614x** [comment]
In all versions below 1.12 the animations are stopped when the game is paused.
