### ISSUE TITLE
[CEM] 1.14.4 F4 Villager, Wandering Trader, and Illusioner CEM broken

### ISSUE THREAD

**Issue by Locxes** [sp614x/optifine#3086]
Villager, Wandering Trader, and Illusioner broke CEM after F3 release.
Villager and Illusioner CEM in F2, Wandering Trader was already broken.
![2019-11-18_00 24 09](https://user-images.githubusercontent.com/56992420/69010476-2a26fb00-099b-11ea-8e07-d4c1f35bfb18.png)
![2019-11-18_00 24 01](https://user-images.githubusercontent.com/56992420/69010468-08c60f00-099b-11ea-87d4-b7a6273fdb81.png)
They look like this after F4
![2019-11-18_00 16 32](https://user-images.githubusercontent.com/56992420/69010482-3f038e80-099b-11ea-9afb-03f29be3512a.png)
![2019-11-18_00 16 36](https://user-images.githubusercontent.com/56992420/69010484-3f9c2500-099b-11ea-834a-ef60717c3447.png)

**Comment by Locxes** [comment]
Resourcepack:
[Player+Villagers+v1.2.zip](https://github.com/sp614x/optifine/files/3855818/Player%2BVillagers%2Bv1.2.zip)

**Comment by sp614x** [comment]
Fixed in latest preview.
