### ISSUE TITLE
1.13.2 Optifine HD U E7, E6, E5, E4 - all crashing on launch.

### ISSUE THREAD

**Issue by RiskyPenetrator** [sp614x/optifine#3089]
So I have been trying to get Optifine to work for the past few hours. It is immediately crashing when I press "play" on the profile I installed Optifine using the .jar installers.

It isn't generating a log in the log window, or a crash log in the crash logs directory. However, the [launcher_log.txt](https://pastebin.com/RRWkZGHF) file has a few things inside it that could help.

Honestly got no idea what is going on, fresh install of ubuntu 19.10, fresh Minecraft and Optifine downloads too. Previously on Ubuntu 18.04, it worked flawlessly so I'm not sure whats changed.

Any help would be great.

**Comment by sp614x** [comment]
```
Info Minecraft client 1.13.2-OptiFine_HD_U_E7 is ready to start.
...
Starting game in folder /home/kieran/.minecraft using java executable /usr/lib/jvm/java-11-openjdk-amd64/bin/java
...
java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader bootstrap)
    at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```
You are running with Java 11.
The preview OptiFine 1.13.2 F4 should be working with java 9+.
