### ISSUE TITLE
Optifine preview 1.12.2

### ISSUE THREAD

**Issue by kvanbiljon** [sp614x/optifine#3090]
I'm wanting to switch back to 1.12.2 on Minecraft and mod it.  I know in order to use forge and optifine together I need the preview version of optifine but I don't see the 1.12.2 version in the previews anymore.  Does anyone know how I can find it?

**Comment by asbyth** [comment]
not a preview version anymore, its the latest one

**Comment by sp614x** [comment]
OptiFine 1.12.2 F4 is released.
