### ISSUE TITLE
[BUG?] Skeleton head item shows up wrong in the inventory

### ISSUE THREAD

**Issue by MushirMickeyJoe** [sp614x/optifine#3091]
![image](https://user-images.githubusercontent.com/31923214/69196496-f5e44380-0b2e-11ea-8c48-212f01833987.png)
I changed the skeleton head using CEM, and it looks fine everywhere (even in-hand, as shown in the image above) but in GUI it's broken

**Comment by sp614x** [comment]
Which OptiFine version is this?

**Comment by MushirMickeyJoe** [comment]
1.14.4-OptiFine_HD_U_F4

**Comment by KaiAF** [comment]
This seems to be fixed now. If you are still having this issue, let me know, please.
