### ISSUE TITLE
1.8.9 HD U L5 broken the bow animations with CIT resourcepack

### ISSUE THREAD

**Issue by ZekerZhayard** [sp614x/optifine#3095]
I use the resourcepack called [MW Multiweapon Addon](https://hypixel.net/threads/mw-multiweapon-addon-v1-2-mc-1-8-add-different-weapons-for-every-class.1209742/). When you pull the bow named with `§bHunter Bow`, it will display the animations like this: (without the arrow!)
![](https://gist.githubusercontent.com/ZekerZhayard/80bca68143156c9ba049cfff644f3de3/raw/0838bdddf0f948e1e5037362f786d5e7eac80e4d/2019-11-23_23.07.15.png)

**Comment by sp614x** [comment]
Is this working in the release L5?

**Comment by ZekerZhayard** [comment]
No, but it works with I7.

**Comment by TimyAnimations** [comment]
I'm glad I'm not alone, I thought I messed something up with my resource pack.  It seems to also have this issue with fishing_rod_cast.
![image](https://user-images.githubusercontent.com/24994382/70576611-fccf0680-1b6e-11ea-8ed4-2d252f7494c7.png)
As an semi related but also unrelated bug, fishing_rod_cast seems to show the default texture in third person, I recall seeing this in I7 as well.
![image](https://user-images.githubusercontent.com/24994382/70577013-f55c2d00-1b6f-11ea-92eb-0ac1b40b5a5a.png)

**Comment by TBlazeWarriorT** [comment]
Can confirm CIT bows and rods animation broken, and sign text flickering visible/invisible when editing in MP on forge and 1.8.9 HD U L5, while I7 didn't have those issues
Bump

**Comment by TBlazeWarriorT** [comment]
Can confirm CIT bows and rods animation broken, and sign text flickering visible/invisible when editing in MP on forge and 1.8.9 HD U L5, while I7 didn't have those issues
Bump

**Comment by TBlazeWarriorT** [comment]
To add to the issue, the bug also affects Rods and Bows in 3rd person in a different way.
Vanillla bows/rods in all cases: works as expected
CIT bows/rods in all default states: works as expected

CIT rods when cast, 1st person: shows the standby texture for the rod instead of the cast one (texture.fishing_rod_cast=x.png is ignored, redirects to texture=x.png)
![image](https://user-images.githubusercontent.com/25572454/72857729-4dbd3900-3c9d-11ea-869d-effb084d35c9.png)
CIT rods when cast, 3rd person: shows the vanilla casted fishing rod texture (both texture.fishing_rod_cast=x.png and texture=x.png are ignored)
![image](https://user-images.githubusercontent.com/25572454/72857739-544bb080-3c9d-11ea-860f-9162fdc41820.png)
CIT bows when pulled, 1st and 3rd person: shows the standby texture instead of the pulled ones. (texture.bow_pulling_0=x.png, pulling_1 and pulling_2 are ignored, texture.bow_standby=x.png is used)
![image](https://user-images.githubusercontent.com/25572454/72857765-63caf980-3c9d-11ea-9b43-4ce9b0fe8100.png)
Note this is a "major" visual bug with CIT and needs a fix ASAP. has been making HD_U_L5 barely usable since release.

**Comment by TheDerpyMan** [comment]
Optifine please fix

**Comment by b1n4ryj4n** [comment]
Bump

**Comment by SirNapkin1334** [comment]
Can confirm this issue. The third person rod issue also happens in I7.

**Comment by IRONM00N** [comment]
Please fix, this issue is so annoying

**Comment by SteuerungZ** [comment]
Same Problem :(

**Comment by GamerNDS** [comment]
Does anyone know a solution to this?

**Comment by ElOxo** [comment]
PLS FIX THAT!!!!!!!!

**Comment by Traister101** [comment]
This issue still isn't fixed and its getting to the point where I'm thinking of just copying the code from I7 that is related so It'll at the very least work for me. It doesn't seem like a problem that'd be that difficult to fix seeing as it worked in the version before.

**Comment by Freeroomcow** [comment]
> This issue still isn't fixed and its getting to the point where I'm thinking of just copying the code from I7 that is related so It'll at the very least work for me. It doesn't seem like a problem that'd be that difficult to fix seeing as it worked in the version before.

please if you do that please send the file out i really want that

**Comment by Chaboi45** [comment]
Bumping, still isn't fixed.

**Comment by NinjaShuriken** [comment]
Please fix this as soon as possible, it seems to be a quick fix as it worked the previous version, playing Hypixel Skyblock without OptiFine working properly is quite frustrating and many people who play the game with custom texture packs would like to see it fixed.

**Comment by Traister101** [comment]
Bump still needs to be fixed and it doesn't seem like something difficult to fix seeing as it DID work in the version prior

**Comment by IRONM00N** [comment]
Bump, still a major issue for hypixel skyblock players. Please fix this as soon as possible.

**Comment by Freeroomcow** [comment]
bump not fixed and very annoying considering i either get cool models but no pullback and fishing rod or no models but pullback and fishing rod

**Comment by Pyroblocks** [comment]
bump If there is a fix please post it

**Comment by NinjaShuriken** [comment]
This is an issue that effects tens of thousands of players everyday. We would REALLY appreciate it if you could roll out a quick fix, as it has worked in a version prior, it is probably a minor bug but quite annoying, I know that you don't have to support a version this old but if u could all of us would be delighted.

**Comment by TheSeboh** [comment]
so, I'm here for the same problem, but I noticed that with Lunar client the custom bows and fishing rod work out, but with the imperial's  Hypixel Skyblock texture pack, but it don't work with something in the menu and with the pets, I understood that @Traister101 fixed that by own, I'm sure that everyone will be glad do see the fixed version because today optifine pubblicate the full version of 1.16.1 I don't think that they will fix this.

**Comment by Zordlan** [comment]
> so, I'm here for the same problem, but I noticed that with Lunar client the custom bows and fishing rod work out, but with the imperial's Hypixel Skyblock texture pack, but it don't work with something in the menu and with the pets, I understood that @Traister101 fixed that by own, I'm sure that everyone will be glad do see the fixed version because today optifine pubblicate the full version of 1.16.1 I don't think that they will fix this.

Fixing this would be nice. I'm actually staff on ImperiaL's skyblock pack's discord, and people tend to get annoyed that they can't both have pet models and bows working at the same time. The worst part is that bows work in I7, but not L5. Please fix this.

**Comment by TheSeboh** [comment]
I attempt to fix this but I just broken the optifine version

**Comment by Zordlan** [comment]
yea, imma learn java and make an unofficial patch (if SP is ok with me doing that ofc)

**Comment by TheSeboh** [comment]
Java is a difficult language, good luck fellow

**Comment by Zordlan** [comment]
ye ik, i never said i would do it quickly lol

**Comment by TheSeboh** [comment]
Too optifine has taken a lot of time for making 1.16.1 but i think that 1.8.9 is easier

**Comment by SirNapkin1334** [comment]
@Zordlan good luck but I doubt you'll be able to figure it out. Java is complicated. So is Forge. And Optifine even more so.

**Comment by TheSeboh** [comment]
so @Zordlan who is going learning of java?

**Comment by VictorGamerLOL** [comment]
bump Agree, needs fixing. Quite annoying that my runaans bow is not pulling

**Comment by Shuaiouke** [comment]
Just please, make a hotfix, or something, this annoys me so much

**Comment by sp614x** [comment]
Fixed in L6_pre1

**Comment by VictorGamerLOL** [comment]
Thank you.

**Comment by TimyAnimations** [comment]
custom bow models do not work in L6_pre1, the base model works but the pull back one will only use a texture.

**Comment by IRONM00N** [comment]
wdym? CIT bow models work now.

**Comment by TimyAnimations** [comment]
https://gyazo.com/220a39234e08ddc903049cfc221de626

properties file has
model.bow_standby=bow
model.bow_pulling_0=bow
model.bow_pulling_1=bow
model.bow_pulling_2=bow

they model isn't being used for the pulling back animations but works for the standby.
the unfinished model is named bow.json and is in the same folder as the properties file.

**Comment by yanlin41020** [comment]
CIT rod thrown broken in third person view even in L6_pre1

https://imgur.com/a/DOYMjbx
