### ISSUE TITLE
optifine does not appear in the version list

### ISSUE THREAD

**Issue by itsBBQ** [sp614x/optifine#3096]
Hi, I downloaded optifine but it doesn't appear in my version list I deleted the game and i install again  
and i installed optifine again but doesn't appear in my version list

**Comment by SetantaLP** [comment]
Installing optifine should work by double-clicking the jar file, but it will fail if the corresponding minecraft version is not found. So what happens when you double-click the jar file?

**Comment by seniorlonely** [comment]
i do everything right and finally successfully completed writes
