### ISSUE TITLE
only 1 optifine profile allowed in launcher

### ISSUE THREAD

**Issue by algamoda** [sp614x/optifine#3097]
Don't know if this is supposed to happen, i got optifine 1.8.9 and 1.12.2, and the previous got deleted.

**Comment by Studio528-real** [comment]
Create a new profile with the optifine version you want

**Comment by NitroCipher** [comment]
Just duplicate it, and change the optifine version 
![image](https://user-images.githubusercontent.com/11393734/69484372-14309480-0df8-11ea-8804-fd14484b79d8.png)
