### ISSUE TITLE
Suggestion: Server Api plugin

### ISSUE THREAD

**Issue by EPICSAURUSS** [sp614x/optifine#3098]
This has probably been asked multiple times but not specifically. Basically, what I am asking for is that there be a public server api plugin that servers can install. Why would someone need this? Say, for instance, someone has players install a resource pack on the server that uses things like custom items. Another **great** example: imagine a server having a hacker problem and they want people to stop using hacked clients. They can just turn on the server api and only people with the client can join. This would heavily reduce cheating. (obviously, someone could come up with vanilla hacks, but it would still stop a good percentage.) So yeah, this is why a server api plugin would be a good feature.

**Comment by MrCheeze446** [comment]
https://www.spigotmc.org/

**Comment by asbyth** [comment]
For cheaters to join, they'd just need to change their client brand to "vanilla" rather than whatever they have it set to. a server API is absolutely useless, as you can't force a player to use a mod without just kicking them when they don't have Optifine installed.

**Comment by sp614x** [comment]
Not related to OptiFine which is strictly a client mod.
Hacked clients look exactly like vanilla from the server side, otherwise they would be easy to block.
