### ISSUE TITLE
It is not contained in the translation file.

### ISSUE THREAD

**Issue by TimkaG** [sp614x/optifine#31]
![dynamic](https://cloud.githubusercontent.com/assets/17567951/13879083/898d57f0-ed26-11e5-89de-f10144154fd7.png)
![shader](https://cloud.githubusercontent.com/assets/17567951/13879082/898cb340-ed26-11e5-9506-50fedae99f77.png)
![shaderoptions](https://cloud.githubusercontent.com/assets/17567951/13879167/0758b1c0-ed27-11e5-8e9c-8da2308d3d6c.png)

**Comment by sp614x** [comment]
Added missing shader resources.
