### ISSUE TITLE
Railcraft Textures.

### ISSUE THREAD

**Issue by YOYOK9** [sp614x/optifine#310]
I've noticed that a few Items/Blocks are missing textures while looking through JEI. When placed some blocks are invisible or have a flat grey texture. 

Have written a report on Railcrafts guithub and have concluded it is optifine causing the issues.
Client Console:
https://gist.github.com/YOYOK9/4d529f6e3ca60ff6cc555a7a3c53cfb8

Picture of JEI:
http://puu.sh/s2XBQ/44423406a4.jpg

MC: 1.10.2
Forge: 2117
Railcraft: 1.10.2-10.0.0
JEI: 1.10.2-3.13.0.338
Optifine: 1.10.2_HD_U_D1

**Comment by Joshwoo70** [comment]
duplicate #308
