### ISSUE TITLE
Delete Donation Account Request

### ISSUE THREAD

**Issue by GarbageMan67** [sp614x/optifine#3103]
I would like to make a request for my donation account to be deleted. Please tell me what information I need to give you, in order for my donation account to be deleted. Forgive me for posting this here, I tried to get in contact via email, but you haven't gotten back to me in months. Thank you.

**Comment by sp614x** [comment]
You can request a refund from Paymentwall if the donation is recent, then the account will be closed automatically.
It is not possible to close the donation account for an active donation.
