### ISSUE TITLE
Does anyone know what's going on?This is 1.12.2

### ISSUE THREAD

**Issue by nulleqn** [sp614x/optifine#3104]
The game crashed whilst updating screen events
Error: java.lang.NoSuchFieldError: field_146501_h

**Comment by nulleqn** [comment]
![Uploading image.png…]()

**Comment by sp614x** [comment]
Most probably a conflict with one of the installed mods, for example Hardcore Darkness #2713.
You can remove the mods one by one or in groups to find which one conflicts with OptiFine.
