### ISSUE TITLE
Minecraft is unable to open once Optifine is installed

### ISSUE THREAD

**Issue by PEACEB0NE** [sp614x/optifine#3105]
When I download Minecraft, the program runs perfectly fine. However, once I installed Optifine, Minecraft was unable to launch, no pop-up message too. I checked the task manager to see if Minecraft was running, but no sign. 
I also tried reinstalling Minecraft to make sure if it was due to Optifine and again, Minecraft couldn't launch once Optifine was installed.
Not sure how to fix this, any help would be appreciated.

**Comment by sp614x** [comment]
You can delete the file `optionsof.txt` in the minecraft folder.
Can you post the file `logs/latest.log`, it should have more information.

**Comment by KaiAF** [comment]
Is this still an issue?
