### ISSUE TITLE
1.8.9 HD U L5 pre4 not saving resource packs

### ISSUE THREAD

**Issue by Teruxity** [sp614x/optifine#3106]
When restarting Minecraft with this OptiFine version, the resource pack used before closing the game will reset to the default one after you open Minecraft again.
(tested with Forge and just OptiFine from the installer)

**Comment by sp614x** [comment]
Only happens if the resource pack name contains non-ascii characters.

**Comment by sp614x** [comment]
Fixed, coming in L5 pre5.
