### ISSUE TITLE
Crouching, Zooming, and walking backwards doesn't work.

### ISSUE THREAD

**Issue by SuperSpy2016** [sp614x/optifine#3111]
I tried this all at one time, Input: Shift, C, and S. I did this all together and I did not move at all. Please fix :/

**Comment by MastaNub** [comment]
that's your keyboard. its called key ghosting

**Comment by Studio528-real** [comment]
yes, that is a keyboard thing,  some keyboard don't like more than 2 or 3 buttons pressed at a time or certain combos of keys

**Comment by sp614x** [comment]
Not related to OptiFine.
