### ISSUE TITLE
[Request] Disable Elytra texture being overwritten by cape texture

### ISSUE THREAD

**Issue by Frontear** [sp614x/optifine#3114]
I realize that issues like #241 specify that elytra textures were modified to be overwritten by the users cape, but I personally dislike it, and was hoping there was a way to disable it. If not, can it be considered to add an option that will disable that functionality? My cape really doesn't fit as an elytra wing, so it doesn't seem to good to me.

**Comment by NitroCipher** [comment]
duplicate of #2568 and #3039

**Comment by Frontear** [comment]
Duly noted.
