### ISSUE TITLE
ray tracing

### ISSUE THREAD

**Issue by matejmraz1** [sp614x/optifine#3123]
shader known as SEUS PTGI is path tracing shader which traces software side and not hardware. thats because there isnt something that would allow shader to use rtx ray tracing core and thats issue because if you have gtx 1080 and rtx 2080 it wont make much difference and will run very slow...

so im asking if you could allow it in future optifine versions if it works.

i hope it does.

ps i wont answer that quickly

**Comment by sp614x** [comment]
NVidia RTX is only available on Vulkan.
Minecraft is built on OpenGL and NVidia doesn't plan to add RTX support to OpenGL.
It is not possible to add RTX to Minecraft without rewriting the whole render engine to run on Vulkan.
