### ISSUE TITLE
Delete Donation Account

### ISSUE THREAD

**Issue by TemporaryUsername31** [sp614x/optifine#3124]
I am deleting my Minecraft account, and would like to delete my optifine cape / donation account as well. Is there anyway to do this?

**Comment by NitroCipher** [comment]
Why are you deleting your mc account?

**Comment by TemporaryUsername31** [comment]
I am deleting my Minecraft account due to personal reasons.

**Comment by sp614x** [comment]
Currently it is not possible to delete the donation account.
