### ISSUE TITLE
CIT: Compass

### ISSUE THREAD

**Issue by DragonmasterDaan** [sp614x/optifine#313]
When trying to work with CIT and changing compasses based on their name they indeed can change texture but when using it the compass keeps on making circles (http://imgur.com/lfqYYUx).
**Everything I used (1.8.8 Optifine):** 
-Texture: http://imgur.com/seDimNW
-McMeta:
{
"animation": {}
}
-Properties:
type=item
items=345
texture=blue_compass
nbt.display.Name=ipattern:*\u00a77 Pointing at \u00a79Blue*

**Comment by sp614x** [comment]
You are defining one animated texture, which automatically loops over all frames.
To properly redefine the compass textures in 1.9+ the compass model has to be changed. 
Currently OptiFine can not use custom models with CIT, but it is on the TODO list: https://github.com/sp614x/optifine/issues/146
