### ISSUE TITLE
Glitchy textures

### ISSUE THREAD

**Issue by kSt4rz** [sp614x/optifine#3130]
While playing Minecraft Java, the game textures keep glitching out, and I keep finding provisional fixes that barely even work. Are there any permanent fixes?
![2019-12-01 21 45 07](https://user-images.githubusercontent.com/58575865/70284916-c458b280-1793-11ea-9317-ab6ad61fba29.jpg)
![2019-12-05 18 40 38](https://user-images.githubusercontent.com/58575865/70284922-c753a300-1793-11ea-8d23-63e754b82988.jpg)

**Comment by Studio528-real** [comment]
Are you using any resource packs? Also you can take screenshots with f2, or if on windows alternatively use snipping tool to get certain areas of your screen

**Comment by kSt4rz** [comment]
Eh, it crashes when I try to take screenshots when the game glitches out. I don't use any resource packs atm

**Comment by Juesto** [comment]
Sounds like a issue with your graphics card instead of optifine.

**Comment by sp614x** [comment]
Not related to OptiFine.
