### ISSUE TITLE
weird ctm problems

### ISSUE THREAD

**Issue by steventylerseanherr** [sp614x/optifine#3133]
![2019-12-07_01 19 51](https://user-images.githubusercontent.com/48705919/70371071-3caa9b00-189c-11ea-8058-256e7e21569d.png)
![2019-12-06_23 41 36](https://user-images.githubusercontent.com/48705919/70371085-8abf9e80-189c-11ea-85e9-1efef70b4b1e.png)
is ctm supposed to be missing those corners around the center block?

id imagine it should look more like this
![2019-12-07_01 20 02](https://user-images.githubusercontent.com/48705919/70371103-fbff5180-189c-11ea-9e27-0848d1a3f233.png)

**Comment by Spook2U** [comment]
This has something to do with innerSeams. I requested a fix #2966, which got fixed. If you have the newest version (maybe preview from discord) and write innerSeams=true it should work properly.

**Comment by steventylerseanherr** [comment]
sorry it took so long to get back 
yep its fixed now
