### ISSUE TITLE
optifine chrashes

### ISSUE THREAD

**Issue by ADutchGamer** [sp614x/optifine#3135]
optifine cant save tings like the serverlist and when opening a single-player world it crashes
it also doesnt create crashreports or logs.
when i open a single-player world it says the followed thing in the minecraft game output:
[STDERR]: java.io.IOException: Access is denied

**Comment by sp614x** [comment]
`[STDERR]: java.io.IOException: Access is denied`
Minecraft can't write to the settings file in the minecraft folder.
Check the file permissions, make sure Minecraft has not been running as administrator, etc.

**Comment by ADutchGamer** [comment]
it always works, but a few days ago it started after some time giving that error, and now its gone
i no this sounds like a lie, but's real and it somehow seems to fix itself after a windows update
