### ISSUE TITLE
REFUND

### ISSUE THREAD

**Issue by AigleDev** [sp614x/optifine#3147]
I have sent an email for donation refund (i really need the money right now) if an optifine staff could respond please.
Eaglezledozo100@gmail.com

**Comment by blomer** [comment]
It's $10, you have got to be kidding.

**Comment by AigleDev** [comment]
Am afraid not, must be nothing for you guys in US but here in morocco it has a value

**Comment by blomer** [comment]
This is not the right place to ask for a refund, this is for issues regarding the software itself.

**Comment by AigleDev** [comment]
I'am not asking for a refund i'am just asking if the staff could respond to my mail

**Comment by Studio528-real** [comment]
There is only 1 staff and he's the one that created, manages, publishes, receives emails, replies to them. Aka he does a lot so it may take a while for him to respond, sorry

**Comment by kbartek05** [comment]
You know there are no refunds for **donations**, right? You are not paying for a service, you are donating to a person.
