### ISSUE TITLE
ReplayMod compatibility - How does Optifine change the the way RenderGlobal#setupTerrain works?

### ISSUE THREAD

**Issue by CrushedPixel** [sp614x/optifine#315]
NOTE: This post applies to the 1.8 version of Minecraft and Optifine, however everything should still apply to MC 1.9 and 1.10.

When rendering a sequence using the ReplayMod, we force Minecraft to render all the terrain from the very first frame of the video. Therefore, we do the following in RenderGlobal during rendering:

To force all chunks to be rendered, we

1) Make `RenderGlobal#isPositionInRenderchunk()` always return `true`

To completely take control of the chunk updates ourselves, we

2) Lock all background chunk updates by replacing `RenderGlobal.renderDispatcher.queueChunkUpdates` with a Jailing Queue that locks all threads trying to access it

3) Replace `RenderGlobal#updateChunks` with a method that synchronously calls 
`ChunkRenderDispatcher#runChunkUploads` and processes all chunk Updates in `renderDispatcher.queueChunkUpdates`, then calls `RenderChunk#updateChunkNow` for all chunks in `RenderGlobal#chunksToUpdate`.

To wait until all of the terrain is set up:

4) Replace `RenderGlobal#setupTerrain` with a loop that calls `RenderGlobal#setupTerrain` until `RenderGlobal.displayListEntitiesDirty` is `false`.

**Behaviour without Optifine**: Everything gets rendered with all of the terrain loaded.
**Behaviour with Optifine**: We're getting stuck in the `setupTerrain` loop, as `displayListEntitiesDirty` is never set to false. Disabling our modifications to `RenderGlobal` of course fixes this, but causes chunks not to be instantly loaded in the video.

I noticed that you added a `Set<RenderChunk> chunksToUpdateForced` to `RenderGlobal`, and add a chunk to it if `RenderChunk#isPlayerUpdate` returns false. Can you provide any insight what this does? For testing purposes, I made your `RenderChunk#isPlayerUpdate` method always return true so your code doesn't get executed. This resulted in `displayListEntitiesDirty` turning false and therefore unstuck the ReplayMod's setupTerrain loop, however no terrain was being rendered as a result of that.

Any insight on what you're changing in the way RenderGlobal does its terrain setup would be appreciated!

**Comment by sp614x** [comment]
If I understand correctly you are trying to force all chunks to be rendered before the first frame.

1. Making isPositionInRenderChunk() always return true - should be OK
2. Blocking the chunk update threads - should be OK
3. Replacing updateChunks() with an immediate update loop - it should probably work

The set chunksToUpdateForced contains chunks which are to be updated in the background, but with higher priority. If you change isPlayerUpdate() to always return true, then chunksToUpdateForced will not be used.

The flag displayListEntitiesDirty should automatically become false when there are no more chunks to be updated - chunksToUpdate is empty and for all visible chunks isNeedsUpdate() == false. This is done in setupTerrain(), before rebuilding the renderInfos the displayListEntitiesDirty is set to false and later if there are chunks to be updated it is set to true. This is vanilla functionality and OptiFine is not changing how it works.

The displayListEntitiesDirty is also set to true when the integrated server is still loading new chunks:

        // Check how many chunks are loaded
        int countLoadedChunks = getCountLoadedChunks();
        if(countLoadedChunks != countLoadedChunksPrev)
        {
          // The loaded chunks are changed, rebuild render infos
          countLoadedChunksPrev = countLoadedChunks;
          displayListEntitiesDirty = true;
        }

**Comment by CrushedPixel** [comment]
> If you change isPlayerUpdate() to always return true, then chunksToUpdateForced will not be used.

That's what I figured, however doing this modification essentially lets it load no chunks at all while setting displayListEntitiesDirty to false. That's not how it's supposed to work.

I understand the vanilla behaviour of displayListEntitiesDirty, as our code is fully functional in Vanilla MC, but are there any changes you do to the behaviour of displayListEntitiesDirty/any changes to code that affects the way chunks are updated?

**Comment by sp614x** [comment]
Maybe the modified version of updateChunks() is not working properly and the chunks are not uploaded to the GPU => not visible?

**Comment by CrushedPixel** [comment]
That's not really a possibility as the code works without Optifine installed.

**Comment by sp614x** [comment]
The displayListEntitiesDirty can only become false when chunksToUpdate is empty. And chunks are only removed from chunksToUpdate when they are updated. So all chunks have to be updated. If the chunks are not visible, then maybe the upload to GPU has a problem (updateChunks).

**Comment by CrushedPixel** [comment]
Here's the replacement for the setupTerrain() method (we're using SpongePowered Mixins to edit the Minecraft code).
To understand what's going on, replayModRender_hook is an instance of ChunkLoadingRenderGlobal (our own class that replaces some methods of RenderGlobal) which is null unless a video is being rendered.

```
@Inject(method = "setupTerrain", at = @At("HEAD"), cancellable = true)
    public void replayModRender_setupTerrain(Entity viewEntity, double partialTicks, ICamera camera,
                                               int frameCount, boolean playerSpectator, CallbackInfo ci) {
        if (replayModRender_hook != null && !replayModRender_passThroughSetupTerrain) {
            replayModRender_passThroughSetupTerrain = true;

            do {
                // this calls RenderGlobal's original setupTerrain method
                setupTerrain(viewEntity, partialTicks, camera, replayModRender_hook.nextFrameId(), playerSpectator);
            } while (displayListEntitiesDirty);

            replayModRender_passThroughSetupTerrain = false;
            ci.cancel();
        }
    }
```

Here's the whole ChunkLoadingRenderGlobal class:

```
public class ChunkLoadingRenderGlobal {

    private final RenderGlobal hooked;
    private final ChunkRenderDispatcher renderDispatcher;
    private final JailingQueue<?> workerJailingQueue;
    private final CustomChunkRenderWorker renderWorker;
    private int frame;

    @SuppressWarnings("unchecked")
    public ChunkLoadingRenderGlobal(RenderGlobal renderGlobal) {
        this.hooked = renderGlobal;
        this.renderDispatcher = renderGlobal.renderDispatcher;
        this.renderWorker = new CustomChunkRenderWorker(renderDispatcher, new RegionRenderCacheBuilder());

        int workerThreads = renderDispatcher.listThreadedWorkers.size();
        BlockingQueue<Object> queueChunkUpdates = renderDispatcher.queueChunkUpdates;
        workerJailingQueue = new JailingQueue<>(queueChunkUpdates);
        renderDispatcher.queueChunkUpdates = workerJailingQueue;
        ChunkCompileTaskGenerator element = new ChunkCompileTaskGenerator(null, null);
        element.finish();
        for (int i = 0; i < workerThreads; i++) {
            queueChunkUpdates.add(element);
        }

        // Temporary workaround for dead lock, will be replaced by a new (ShaderMod compatible) mechanism later
        //noinspection StatementWithEmptyBody
        while (renderDispatcher.runChunkUploads(0)) {}

        workerJailingQueue.jail(workerThreads);
        renderDispatcher.queueChunkUpdates = queueChunkUpdates;

        try {
            Field hookField = RenderGlobal.class.getField("replayModRender_hook");
            hookField.set(hooked, this);
        } catch (NoSuchFieldException | IllegalAccessException e) {
            throw new Error(e);
        }
    }

    @SuppressWarnings("unchecked")
    // this is what RenderGlobal#updateChunks gets redirected to while rendering
    public void updateChunks() {
        while (renderDispatcher.runChunkUploads(0)) {
            hooked.displayListEntitiesDirty = true;
        }

        while (!renderDispatcher.queueChunkUpdates.isEmpty()) {
            try {
                renderWorker.processTask((ChunkCompileTaskGenerator) renderDispatcher.queueChunkUpdates.poll());
            } catch (InterruptedException ignored) { }
        }

        Iterator<RenderChunk> iterator = hooked.chunksToUpdate.iterator();
        while (iterator.hasNext()) {
            RenderChunk renderchunk = iterator.next();

            renderDispatcher.updateChunkNow(renderchunk);

            renderchunk.setNeedsUpdate(false);
            iterator.remove();
        }
    }

    public void uninstall() {
        workerJailingQueue.freeAll();

        try {
            Field hookField = RenderGlobal.class.getField("replayModRender_hook");
            hookField.set(hooked, null);
        } catch (NoSuchFieldException | IllegalAccessException e) {
            throw new Error(e);
        }
    }

    public int nextFrameId() {
        return frame++;
    }

    /**
     * Custom ChunkRenderWorker class providing access to the protected processTask method
     */
    private static class CustomChunkRenderWorker extends ChunkRenderWorker {
        public CustomChunkRenderWorker(ChunkRenderDispatcher p_i46202_1_, RegionRenderCacheBuilder p_i46202_2_) {
            super(p_i46202_1_, p_i46202_2_);
        }

        @Override
        protected void processTask(ChunkCompileTaskGenerator p_178474_1_) throws InterruptedException {
            super.processTask(p_178474_1_);
        }
    }
}
```

**Comment by sp614x** [comment]
Looks ok. You can add some debug output to see which chunks are updated and which are uploaded.

**Comment by CrushedPixel** [comment]
Very interesting - I've added debug output to `ChunkRenderDispatcher#uploadChunk`, and during rendering, it's being called frequently as to be expected (I displayed the chunk position and they make sense), meaning that the chunks are actually being uploaded to the GPU.

I discovered that when turning on a simple Shader, the chunks were being displayed as to be expected, and my error lied in the fact that I was manually calling Shaders#beginRender all of the time before calling EntityRenderer#renderWorldPass regardless of the value of Config#isShaders. This was the fix required to get chunk rendering to work with optifine, so I have found the solution to the actual chunk loading already when I modified the isPlayerUpdate() method to always return true!

There's only one last thing that's broken: rendering now works flawlessly without shaders and with simple shaders that have no shadows, however when trying to render with a shader that needs a shadow pass, the ShadersRender#renderShadowMap method seems to get stuck in an endless loop, as my thread dump suggests:

```
"Client thread" #1 prio=10 os_prio=31 tid=0x00007faeeb001000 nid=0x1003 runnable [0x0000700000180000]
   java.lang.Thread.State: RUNNABLE
	at net.minecraft.client.renderer.RenderGlobal.func_174970_a(RenderGlobal.java:1078)
	at net.minecraft.client.renderer.RenderGlobal.replayModRender_setupTerrain(RenderGlobal.java:44)
	at net.minecraft.client.renderer.RenderGlobal.func_174970_a(RenderGlobal.java)
	at shadersmod.client.ShadersRender.renderShadowMap(ShadersRender.java:317)
	at shadersmod.client.Shaders.beginRender(Shaders.java:3659)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.replaymod.render.hooks.EntityRendererHandler.renderWorld(EntityRendererHandler.java:47)
	at com.replaymod.render.hooks.EntityRendererHandler.renderWorld(EntityRendererHandler.java:36)
	at com.replaymod.render.capturer.OpenGlFrameCapturer.renderFrame(OpenGlFrameCapturer.java:85)
[...]
```

I'll have a look into it.

**Comment by CrushedPixel** [comment]
Any thoughts on this?

**Comment by sp614x** [comment]
There are no loops in renderShadowMap(), it is linear. But it calls RenderGlobal.setupTerrain() which with your modifications may loop and wait for displayListEntitiesDirty. It also calls RenderGlobal.renderBlockLayer() and RenderGlobal.renderEntities().

**Comment by CrushedPixel** [comment]
I got this fixed by simply breaking out of said setupTerrain loop whenever we're in the Shadow Pass. I assume this doesn't make any difference, as all of the terrain should have been loaded by the normal rendering pass already. Is this correct?

**Comment by sp614x** [comment]
When called by renderShadowMap() the setupTerrain() does not update chunks and does not reset displayListEntitiesDirty.

**Comment by CrushedPixel** [comment]
Okay, so I was right to simply break out of the loop - `displayListEntitiesDirty` was being set to `true` by  our `ChunkLoadingRenderGlobal#updateChunks` and `RenderGlobal#setupTerrain` had no chance of setting it to `false` when being called by `renderShadowMap()`.

Thanks for all of your help and your patience, it really helped me getting to the bottom of Optifine compatibility. Have a great day 👍
