### ISSUE TITLE
Minecraft version 1.12.2 to 1.14.4 not found Issue

### ISSUE THREAD

**Issue by Josh-ai** [sp614x/optifine#3151]
Optifine gives me a message that says "Minecraft version ... not found. You need to start version ... manually once." I currently have the 1.5 released version and i want to play RLcraft and for this i need to download a version below 1.5 (since minecraft 1.5 optifine is not out yet) or the version that is compatible with RLcraft. I have tried Java fix and it does not work.

I need help please I have been trying to get this done for the past 6 hours and am still stuck.

Thank you so much for your help!

**Comment by MarioAndWeegee3** [comment]
Put the Optifine jar in the RLCraft mods folder
