### ISSUE TITLE
Phantom CEM Texture Glows

### ISSUE THREAD

**Issue by mexbotdude** [sp614x/optifine#3186]
![2019-12-28_19 07 00](https://user-images.githubusercontent.com/31808869/71548138-42cafd80-29aa-11ea-8fb1-b94b4ede31af.png)

![2019-12-28_20 09 41](https://user-images.githubusercontent.com/31808869/71548414-00a3bb00-29ae-11ea-9258-11cb04f31950.png)

Just get into some context about my issue

A few years ago I found a way to use different CEM models from the same Mob. As an example, I made 10 Custom models and all of them use the Spider CEM. I layered all 10 Models one over another, and the texture will highlight the specific jpm files based on the entity's name.

Its a cool technique cause the invisible JPMs stay invisible, until I faced the Phantom CEM.

Invisible JPMs are now white instead of invisible, I've used the same technique with the Ravager and it works fine, but the Phantom seems to display invisible textures white

The first picture shows a a Green Model as the Main one, and the JPM that should be invisible stays white, on the second picture. Im using the Silver/blue Texture as the main one and the invisible texture (the green one) stays white in this case

**Comment by Arboth** [comment]
I'm having the same issue with CEM phantom parts glowing for no reason
![Untitled1](https://user-images.githubusercontent.com/55228723/73597456-6bf02800-452c-11ea-8b01-e182d16228d7.png)
The grey parts are supposed to be as dark as the vanilla phantom wing bones, but it's even lighter than the texture itself painted. Making the eyes layer transparent does nothing too, and when I covered it with an solid color emission texture this happened
![Untitled2](https://user-images.githubusercontent.com/55228723/73597518-0cdee300-452d-11ea-8252-be56a9e1c2a8.png)
As if it picked the original texture and made a glowing overlay on it.
The shade under the vanilla wings is what it should suppose to look like like that.

**Comment by KaiAF** [comment]
This seems to be fixed. If you are still having any issues, let me know, please.
