### ISSUE TITLE
[OptiFine 1.14.4 HD U F5] Arrows do not travel despite being fully-charged.

### ISSUE THREAD

**Issue by Kirbyrocket** [sp614x/optifine#3188]
_[NOTE: This has **NOT** been tested in other servers yet or single player and should be looked into]_

**Method of Reproduction:** Join Mineplex (US), play any game that uses a Bow and Arrows (e.g. _Turf Wars_)
**Expected Result:** Arrows travel the distance they normally would according to the duration charged and are not stopped abruptly
**Actual Result:** Arrows when shot from a bow are stopped abruptly and fall immediately towards the ground when used.
**Logs:** [2018-10-15-1.log.gz](https://github.com/sp614x/optifine/files/4007721/2018-10-15-1.log.gz)

(See: Jade#6969 <@113410850508791808> as a witness-reference due to system limitations)

**Comment by asbyth** [comment]
this has been an issue on mineplex for the past 5 years, not an issue with optifine

**Comment by sp614x** [comment]
Not related to OptiFine.
