### ISSUE TITLE
Latest Optifine Version URL

### ISSUE THREAD

**Issue by asbyth** [sp614x/optifine#3200]
When redirecting our users to the latest Optifine version, it opens the latest version it finds from [this link](http://optifine.net/version/1.8.9/HD_U.txt). Obviously I7 is outdated by now. Hopefully, you'll end up updating the link to be L5.

Another thing, the page contains a whitespace character, making it appear as
`I7`
` `

This is an issue with our detection as it'd redirect to the URL including the whitespace character. This was easily fixable with doing `.readText().lines().first()` rather than just `.readText()`, but still an issue nonetheless.

**Comment by asbyth** [comment]
still an issue

**Comment by asbyth** [comment]
still an issue

**Comment by asbyth** [comment]
can you please update this?

**Comment by sp614x** [comment]
Only the first line is the OptiFine version.
The rest of the lines may be used for other purposes (custom update message) in the future.

**Comment by sp614x** [comment]
Updated versions.
