### ISSUE TITLE
Minecraft crashes when you try to run it with optifine(1 14 4)

### ISSUE THREAD

**Issue by Nil2334** [sp614x/optifine#3202]
[loh.txt](https://github.com/sp614x/optifine/files/4017616/loh.txt)
[2020-01-03-3.log.gz](https://github.com/sp614x/optifine/files/4017617/2020-01-03-3.log.gz)
When the game is almost loaded, it crashes.
I removed the optifin and installed it.
I deleted the resource packages.
at the top I left links to crash reports and log files.

**Comment by sp614x** [comment]
"Unable to fit: minecraft:burning_skull, size: 64x64, atlas: 0x0, atlasMax: 0x0 - Maybe try a lower resolution resourcepack?"
The resource pack is too big.
OptiFine recognizes much more resource pack features than vanilla.
