### ISSUE TITLE
Returning vanilla fog from a mod

### ISSUE THREAD

**Issue by stepsword** [sp614x/optifine#3203]
In my mod, I'm using a heavy fog underwater (like lava does) and also a fog outside of water. Even though my mod's fog code is running from the EntityViewRenderEvent.RenderFogEvent, when shaders are on, no fog is displayed at all, no matter what settings the fog options have. I assume this is intentional because the fog inside lava works fine with shaders. Could you shed some light on what is being used to disable fog so I can come up with a workaround? Is it the "standardFog" field being set to true?

**Comment by stepsword** [comment]
To be clear, I'm using RenderFogEvent and using setFogStart and setFogEnd with no effect at all when Shaders are on.

**Comment by sp614x** [comment]
Shader packs quite often implement their own fog and ignore the game fog settings.
