### ISSUE TITLE
Sky is completely white when using certain shaders (1.14.4 Optifine)

### ISSUE THREAD

**Issue by L3mur52** [sp614x/optifine#3215]
I have recently gotten a new computer and have downloaded shaders. BSL_v7.1.04.1 and Sildurs Vibrant Shaders(latest versions) are the main ones that I'm having problems with. (I use BSL for taking pictures so ignore the low fps) the sky and void are completely white, not sure what the problem is, I can't find any fix for it online either. I have tried reinstalling the shader as well and no fix. 
![BSL shaders](https://user-images.githubusercontent.com/59621383/71920426-902e3400-313b-11ea-904b-663852d05624.png) 

Sildurs Vibrant Shaders: The entire screen is completely black, no matter which version I use(lite, medium, extreme)      
![Sildurs Medium Shaders](https://user-images.githubusercontent.com/59621383/71920697-3417df80-313c-11ea-99c9-87e66829b367.png)

I got no idea why this is happening and its really annoying if someone could tell me the fix that would be wonderful, thanks.

**Comment by sp614x** [comment]
This is incompatibility between the shader pack and the graphics driver. 
Updating the graphics driver or using another shader pack could help.
Intel HD 2000 is pretty old.
