### ISSUE TITLE
Minecraft crashes when force loading chunks

### ISSUE THREAD

**Issue by robobo1221** [sp614x/optifine#3220]
Minecraft keeps crashing whenever I force load the chunks (F3 + L). It seems like this usually happends with high render distances. 

I checked the minecraft log and it seems like I have found the cause of this issue.
![image](https://user-images.githubusercontent.com/17679544/72173533-123a8900-33d8-11ea-959f-76a4b3e6bfbb.png)

As you can see, for some reason optifine decides to keep loading chunks. It never really stops doing this making the game crash.

I hope that this can be fixed as it's a nice thing to have if you want to render out big maps

**Comment by sp614x** [comment]
Depending on the render distance there may be A LOT of chunks.
Loading ALL of the chunks in the render distance which may cause a crash if MC does not have enough memory.

**Comment by ednellbasilio** [comment]
12 chunks if you front person he can show the exit code 1 
![Uploading Port-Vance-Map-Thumbnail.jpg…]()
