### ISSUE TITLE
1.15.1?

### ISSUE THREAD

**Issue by dehys** [sp614x/optifine#3221]
Idk if I found the actuall optifine mod for Minecraft repo, but if this is it, when is the 1.15.x update comming? Switched my survival server over to 1.15.1 and every day since ive been on the optifine page, refreshing the downloads/preview downloads.

**Comment by dallin1016** [comment]
This is the official Optifine Repo. Progress on the 1.15.1 update can be seen on the subreddit tho, https://www.reddit.com/r/Optifine/comments/d8nptg/optifine_115_progress_report/?st=k58hofp2&sh=1a8fd83b
