### ISSUE TITLE
[suggestion]  Animated cape

### ISSUE THREAD

**Issue by Hognosee** [sp614x/optifine#3231]
Movement to jump, walk...

**Comment by sp614x** [comment]
What exactly is this issue about?

**Comment by Omarelantil** [comment]
be more specific please

**Comment by KaiAF** [comment]
They could be talking about how badlion cloaks are. Like the "Wavy" style or whatever it's called. I could possibly find a video but probably not worth it.

**Comment by KaiAF** [comment]
I am going to close this as I am almost certain this is not going to be added.
