### ISSUE TITLE
[Feature Suggestion] Some form of server recognition that a user has logged in with Optifine.

### ISSUE THREAD

**Issue by ImEraze** [sp614x/optifine#3232]
This is a relatively vague suggestion in the form of an actual plan, purely since I’m assuming there are multiple methods of implementation.

The idea is that as someone who runs servers, I can detect that a user has logged in with optifine. Whether it be changing the client brand or sending some kind of packet that I can intercept, anything works really. 

The benefit of this being that I can offer perks and rewards for users who use Optifine. I run a server that forces a resource pack on users, so being able to use things like CIT as an expansion for those who use Optifine would be great, but not really viable unless I can tell exactly how many people are using it. I can’t think of any negative repercussions for this suggestion, but if there are any I’d love to be informed- thanks!

**Comment by sp614x** [comment]
OptiFine is a strictly client-side mod. It doesn't change anything in the server communication.
When loaded by Forge it may be possible that Forge reports the list of loaded mods to the server, including OptiFine. This hasn't been tested and depends only on Forge.

**Comment by ImEraze** [comment]
So based on this, just to confirm; there’s no simple and easy way (or plan) to allow people to detect Optifine clients on the servers end?
