### ISSUE TITLE
Banner Capes not allowing more than 6 layers

### ISSUE THREAD

**Issue by PortalTrap-Git** [sp614x/optifine#3237]
The banner site, Miners Need Cool Shoes, allows for capes with more than 6 layers, but warns users that they are impossible without basically using a cheat code (a command).
For some reason, trying to set an OptiFine Banner Cape to a banner with more than 6 layers returns an error and reverts back to whatever cape design you had previously.
OptiFine's cape page uses the code generated by Miners Need Cool Shoes, which means that it should theoretically support more than 6 layers with a bit of tinkering.
I would like to see more than 6 layers be possible, however I still think there should be a hard limit to prevent overloading OptiFine's servers, so I propose adding 10 layers to the max and making it be 16, or even possibly allowing 32 if that wouldn't be too troublesome.
I personally don't see it as much of a problem, but I'm not necessarily very good at this type of coding, so there could be some hurdles I'm unaware of.
Either way, I'd appreciate if you'd consider my idea. Thanks for reading, and have a good morning, noon, evening, or night, wherever you are.

**Comment by sp614x** [comment]
The OptiFine capes can use up to 8 layers currently.
Up to 16 layers may be added in the future.

**Comment by GreenBean4323** [comment]
Okay, I didn't know that. I'm trying to use a cape with 10 layers and failing, so I guess I'll just have to wait.

**Comment by MastaNub** [comment]
#2891 #2906 #2886 please 🙏
