### ISSUE TITLE
Option to use less video memory (with performance cost, implementation explained in description)

### ISSUE THREAD

**Issue by Barteks2x** [sp614x/optifine#3242]
Recently I've been made aware that Minecraft is using very excessive amount of video memory after some time of exploring the world. The issue is explained in this report: https://bugs.mojang.com/browse/MC-170134.

While if it's confirmed and accepted as a bug by mojang, it may be fixed in future releases, it affects 1.12.2 (and probably older), 1.13.x, 1.14.x and currently 1.15.x, and the difference in video memory usage is quite significant, which could certainly help players with older hardware, and it should be easy to implement as an optifine option.
Is this something that could be implemented in optifine?

Update:
One thing I just became aware of is that the fix/workaround I show in the linked report causes my linux nvidia drivers to cause a JVM crash when using any shaders (works fine without shaders). I haven't been able to figure out why.

**Comment by idnthvn** [comment]
^^^ Be great for 1.12.2 :)

**Comment by HeberonYT** [comment]
Wow! After a long time, now I find the cause.
I am using shaders in a modpack of 150 mods and I have fps drops constantly.
@Barteks2x  Could you release your test mod for 1.12.2?

**Comment by Barteks2x** [comment]
Same as #7475
