### ISSUE TITLE
No Optifine for Minecraft 1.15

### ISSUE THREAD

**Issue by codezinx** [sp614x/optifine#3246]
sp614x I did not find any Optifine releases for 1.15.
I went to the official site, [optifine.net](https://optifine.net/downloads)

sp614x, could you please release an Optifine for 1.15? Minecraft 1.15.1 has already been released.

**Comment by asbyth** [comment]
its not even done lol

**Comment by Regnander** [comment]
See https://twitter.com/optifinenews and https://www.reddit.com/r/Optifine/comments/d8nptg/optifine_115_progress_report/ for updates on 1.15.

**Comment by SlimeDog** [comment]
and today 1.15.2 released

**Comment by asbyth** [comment]
doesnt matter if versions of 1.15 are out, optifine itself isnt done and cant even run/build, these updates arent instant lol

**Comment by NitroCipher** [comment]
It will be done when it's done. Be patient and wait

**Comment by SlimeDog** [comment]
Understood. We are patient. Data are just data.

**Comment by sp614x** [comment]
It will be released when it is ready.

**Comment by Solid-Block** [comment]
OK. Hope it will be soon.
