### ISSUE TITLE
Optifine Cape

### ISSUE THREAD

**Issue by Exxxooo** [sp614x/optifine#3249]
Today I started playing minecraft and i saw that my optfine cape is deactivated. I restarted my pc and my launcher but it dont appear. I checked my cape status too but everything is fine

**Comment by youngclour** [comment]
same, came home, opened minecraft and my cape is gone. tried reinstalling, changing the cape design, using other versions, nothing works.

**Comment by asbyth** [comment]
cape servers are down

**Comment by sp614x** [comment]
The cape servers are back online.
