### ISSUE TITLE
Cape doesnt showing... 

### ISSUE THREAD

**Issue by mrkino99** [sp614x/optifine#3250]
I have my cape buyed, and i have all my settings "on" but i cant understand why my cape is not showing wtf? I mean, i tried in some versions and noothing, any idea?

**Comment by asbyth** [comment]
cape servers are down

**Comment by Zbychuuu** [comment]
mam dokladnie to samo

**Comment by Lerful** [comment]
When the capes going to get fixed ?

**Comment by Zbychuuu** [comment]
idk


śr., 22 sty 2020 o 19:21 Lerful <notifications@github.com> napisał(a):

**Comment by sp614x** [comment]
The cape servers are back online.
