### ISSUE TITLE
I filled in the wrong e-mail address, but I already paid, what should I do?

### ISSUE THREAD

**Issue by xuanxuan229** [sp614x/optifine#3254]
I am a Chinese player, I paid a US $ 10 fee through Alipay, but I did n’t pay attention to the correctness of the email. Now I ca n’t log in and modify my cloak.

**Comment by ilunp** [comment]
ohhhhhh meto，This is too bad.

**Comment by sp614x** [comment]
You can still edit the design of your cape, the donator email is not needed for this.
