### ISSUE TITLE
optifine outdated request optifine to finally release the next patch.

### ISSUE THREAD

**Issue by aurimilky** [sp614x/optifine#3260]
I am playing on minecraft 1.12.2 / forge and  your mod Opifine has say to report the following to you: 

"Optifine was Detected. Opifine may be outdated chunk pregen needs a experimelal Optifine version because the dev does not release important patches for over 10 months please request optifine to finally release the next patch."

Many Thanks
aurimilky
![2020-02-04_08 36 53](https://user-images.githubusercontent.com/42894633/73728906-0f5b5b80-472c-11ea-92d5-5dcb5d6dc042.png)

**Comment by asbyth** [comment]
this was solved in december with F5, update your optifine and dont come here for things like this, it's nothing but targeted harassment from another mod developer that caused a lot of issues awhile ago.

**Comment by D3monPixel** [comment]
This is the dumbest shit I have ever read a mod dev do... Uninstall his mod and play without it. A mod that makes people harass sp can't be good for anything. Maybe it's even a virus.

**Comment by aurimilky** [comment]
> 
> 
> this was solved in december with F5, update your optifine and dont come here for things like this, it's nothing but targeted harassment from another mod developer that caused a lot of issues awhile ago.

Oh okay thanks I will update optifine to F5 now. 

As for the mod developer that caused a lot of issues awhile ago, I have no idea what you are talking about, but that has nothing to do with me as that problem is Optifine own problem. I am only reporting a problem that was ask by the Optifine mod in game.


> 
> 
> This is the dumbest shit I have ever read a mod dev do... Uninstall his mod and play without it. A mod that makes people harass sp can't be good for anything. Maybe it's even a virus.

I am not sure what mod you are talking about, but I play on a modded server so I am not able to uninstall the mod unless the owner of the server removes it. What mod are you talking about?

**Comment by aurimilky** [comment]
asbyth and D3monPixel 

Also quick question are you both part of the optifine team or just players?

**Comment by asbyth** [comment]
Optifine is one person, and that is sp614x. That screen you see was created by the developer of Chunk Pregen to get people to harass sp614x to update Optifine to fix an issue.

**Comment by aurimilky** [comment]
> 
> 
> Optifine is one person, and that is sp614x. That screen you see was created by the developer of Chunk Pregen to get people to harass sp614x to update Optifine to fix an issue.

Okay thanks

I have checked the mod pack and i can see that mod Chunk Pregenerator is in the mod back. Is it safe? I am asking because you said the following: "Maybe it's even a virus."

**Comment by asbyth** [comment]
This isn't the place to ask about other mods, this is meant to be directly for issues, suggestions, etc. revolving around Optifine.

**Comment by aurimilky** [comment]
> 
> 
> This isn't the place to ask about other mods, this is meant to be directly for issues, suggestions, etc. revolving around Optifine.

Okay not a problem was just ask question about what you type in one for you posts.

**Comment by aurimilky** [comment]
Thank you both for the help. bb

**Comment by Studio528-real** [comment]
if anyone wants to read the drama, warning it's not kind. the dev was pretty much being very petty over something that if he had asked kindly he would be better off.

#2975
