### ISSUE TITLE
[SUGGESTION] Rendering engine changing option

### ISSUE THREAD

**Issue by Labiq** [sp614x/optifine#3262]
Add option to change new 1.15 rendering engine to 1.14 rendering

**Comment by NitroCipher** [comment]
That's... That's not...
That's not how any of this works 😒

**Comment by rre36** [comment]
![img](https://i.kym-cdn.com/entries/icons/original/000/031/425/Screen_Shot_2019-10-09_at_10.41.04_AM.png)

**Comment by realjackasterisk** [comment]
I love how the original title of this was literally just
> ### [SUGGESTION]

Really informative.

**Comment by sp614x** [comment]
This is not possible.
