### ISSUE TITLE
Error With Optifine 1.12.2 F5, preview F6 pre1

### ISSUE THREAD

**Issue by berkkrkc09** [sp614x/optifine#3263]
When the world is loading it loads into a blank screen then after 30(?) seconds a black screen appears. I tried these two versions of optifine. This wasn't happenning before and i didn't change anything. This came out of nowhere. My game version is 1.12.2 And i am playing on twitch desktop client with 4 GB RAM dedicated to the game.

Crash logs :

F5:
[https://pastebin.com/WjBzqp2B](https://pastebin.com/WjBzqp2B)

F6 pre1:
[https://pastebin.com/FnkKm3aH](https://pastebin.com/FnkKm3aH)

**Comment by berkkrkc09** [comment]
Today i tried the internal shaders and a CCL error occured. So i looked at the log and see that it's cause was "Covers" from "Thermal Expansion". (i forgot to tell that i was using shaders before.)

Here is the error part of the log:
https://pastebin.com/b1P3vaiB

**Comment by berkkrkc09** [comment]
Will someone look at this issue?

**Comment by berkkrkc09** [comment]
I've lost hope.

**Comment by Quavelen** [comment]
In all honesty @berkkrkc09, I'm going to blame your laptop's hardware. Especially the cpu.
The i5-7200U is nowhere near strong enough to load all those mods without issues.

If I'm wrong it truly is an OptiFine issue, then hopefully sp614x saw this already.

**Comment by berkkrkc09** [comment]
Thank you for ansvering @Quavelen. Iknow my hardware is old but i have played with around 300 mods and didn't have such issue because i have modified my laptop a bit. Now i have around 220 mods with mods like: Foam Fix, Performant etc. So i think it should be able to handle it. But this issue doesn't let me play with shaders wich i was using before with mods and it was fine.

**Comment by sp614x** [comment]
May be a conflict between shaders and some of the mods.
Internal shaders are only useful for testing, you can disable them as they may cause incompatibility issues.

**Comment by carotte317** [comment]
with an intel core I5 9600K, i have a problem near to it, it don't display the cover models/textures, and if i try to get a cover in my hand, to place it on a pipe, when i point the pipe with it in my hand, the game crashes
(I5 9600K, RTX 2060SUPER 8Go, 8Go RAM dedicated to the game)

**Comment by Quavelen** [comment]
Hey @carotte317, please open your own issue on the topic and follow the given template. This issue was closed back on the 17th of February.
