### ISSUE TITLE
[1.15 Bug] Artifact in clouds

### ISSUE THREAD

**Issue by Naeqirelle** [sp614x/optifine#3272]
![2020-02-13_17 26 08](https://user-images.githubusercontent.com/59464369/74461892-236b2f80-4e87-11ea-904e-fde26cbfb6d3.png)

Weird artifact in the clouds at night, not sure if this can be reproduced.

**Comment by rre36** [comment]
Can you elaborate this? As far as I can tell there is nothing wrong in that image unless you're talking about the clouds being cut off at a certain distance. Afaik this is a vanilla and not an optifine thing.

**Comment by Naeqirelle** [comment]
![74461892-236b2f80-4e87-11ea-904e-fde26cbfb6d3](https://user-images.githubusercontent.com/59464369/74465087-a80c7c80-4e8c-11ea-9aa3-fc6668539313.png)

**Comment by rre36** [comment]
Ah now I see I think, you mean that faint bright bar there?

**Comment by EternalMC** [comment]
I see nothing wrong that bar is the side of the cloud

**Comment by rre36** [comment]
![Unbenannt](https://user-images.githubusercontent.com/15215556/74474345-94b9db00-4ea5-11ea-9883-6f8dbd72b0c9.png)

**Comment by Those45Ninjas** [comment]
@rre36 I believe you might be experiencing colour banding. https://en.wikipedia.org/wiki/Colour_banding

I've taken some screenshots from for both Vanilla and OptiFine and I cannot find any discrepancies between the two.

*Vanilla Minecraft 1.15.2*
![vanilla](https://user-images.githubusercontent.com/13611308/74586327-7ed12500-5021-11ea-9508-6e83e52cde88.png)

*OptiFine 1.15.2 HD U G1 pre2*
![optifine](https://user-images.githubusercontent.com/13611308/74586325-7aa50780-5021-11ea-9411-dfebd3f4ba7f.png)

**Comment by rre36** [comment]
I didn't make the issue tho and I am well aware of color banding in vanilla minecraft. It has always been a thing because they don't dither the final image to avoid that.

**Comment by Those45Ninjas** [comment]
> I didn't make the issue tho and I am well aware of color banding in vanilla minecraft. It has always been a thing because they don't dither the final image to avoid that.

Sorry for the confusion referenced the wrong user :smile:

**Comment by sp614x** [comment]
The color banding is due to not sufficient color depth.
Can't be fixed by OptiFine.
