### ISSUE TITLE
[1.15 Bug] Lighting bug when two model blocks are placed ontop of each other

### ISSUE THREAD

**Issue by Naeqirelle** [sp614x/optifine#3274]
![2020-02-13_17 32 34](https://user-images.githubusercontent.com/59464369/74462047-66c59e00-4e87-11ea-8a9c-92f1c3231539.png)

I used a resource pack called 'Default 3D 1.15' link: https://know2good.com/high.html

Placing two blocks ontop of each other will cause an immediate lighting change on parts of the block compared to having the block on it's own

**Comment by sp614x** [comment]
Fixed, coming in next preview.
