### ISSUE TITLE
[1.15 bug] Model bug with glass (possibly connected textures related)

### ISSUE THREAD

**Issue by Naeqirelle** [sp614x/optifine#3275]
![2020-02-13_17 36 23](https://user-images.githubusercontent.com/59464369/74462378-0a16b300-4e88-11ea-99b1-a0af36308f3e.png)

when glass is placed next to each other it seems to break.

using Default 3D 1.15

**Comment by sp614x** [comment]
Which resource pack is this?

**Comment by Naeqirelle** [comment]
@sp614x Default 3D 1.15 https://know2good.com/high.html

**Comment by sp614x** [comment]
Tested with pre5, looks OK to me:

![image](https://user-images.githubusercontent.com/16635441/74855238-b81ad500-5340-11ea-8cab-add10e2e0b34.png)

**Comment by Naeqirelle** [comment]
ah it must have been fixed then, i made this issue with pre1 i think when that first came out
