### ISSUE TITLE
[1.15.2 HD U G1 pre1] Chunks dont render until you place a block to update it.

### ISSUE THREAD

**Issue by Legoman99573** [sp614x/optifine#3278]
Tested and happens in single player and multiplayer.
![image](https://user-images.githubusercontent.com/7460704/74463965-50ecb480-4e58-11ea-84c9-f7ac236d4d2c.png)

Place a block and it will render it as so:
![image](https://user-images.githubusercontent.com/7460704/74464051-75e12780-4e58-11ea-9411-9c2eb633e7db.png)

**Comment by FORTNITE-BAD** [comment]
Exact same happened to me
![2020-02-14_16 23 07](https://user-images.githubusercontent.com/61067175/74569124-a227a180-4f47-11ea-80ee-fce3ea1abf2b.png)

**Comment by Ink-33** [comment]
It happened to me when I used Optifabric, but it doesn't happen when I use Optifine installed on Vanilla.

**Comment by SiskooPOG** [comment]
Probably related to this https://github.com/sp614x/optifine/issues/3286#issuecomment-586565157

**Comment by sp614x** [comment]
Fixed, coming in next preview.
