### ISSUE TITLE
Support common archived folder structure

### ISSUE THREAD

**Issue by BruceKnowsHow** [sp614x/optifine#328]
When people zip things up, they often end up with this folder structure:
/ShaderName.zip/ShaderName/shaders/*files*

This is an extremely common error. Even downloading a repository from GitHub does this. It would be great if you added support for this kind of folder structure.

Something like this: when you check for a "/ShaderName/shaders/" folder, also check for a "/ShaderName.zip/ShaderName/shaders/" folder.

**Comment by HeartyYF** [comment]
Then if there is something in "/ShaderName.zip/shaders/" folder,and there is something in "/ShaderName.zip/ShaderName/shaders/" folder,what will happen?

**Comment by BruceKnowsHow** [comment]
Unless someone deliberately set it up like that, it wouldn't happen. I would probably have it use the default structure in that case.

**Comment by sp614x** [comment]
The same problem exists for resource packs (which are more popular) and no one is complaining so far. Mojang also does not plan to add support for this structure in the resource packs.

**Comment by BruceKnowsHow** [comment]
Mainly the issue is that I get a lot of people downloading straight from my github repo, who don't know what they're doing, who then come into my discord and post black screenshots complaining that my shaderpack is broken. Also whenever people send me shader edits, they only archive the "shaders" folder, so the structure is wrong and I have to unzip and fix it before I can run the shader.

This is not as common an issue with resourcepacks because resourcepacks have additional files such as the "pack.png" and "pack.mcmeta". When archiving multiple files, the structure is correct (at least with 7zip). For shaderpacks there are only occasionally additional files, such as a license, however these are normally ignored when just sharing edits over Skype, as has been my experience.

**Comment by sp614x** [comment]
Downloading a repo ZIP is not the way to install a shader pack. 
Or a resource pack or anything else hosted on github. 
There is probably not a single project on github that can be installed from the downloaded repo ZIP file.

**Comment by Dushess** [comment]
Problem solves so easy in this situation, just unzip content and repack correctly.

**Comment by BruceKnowsHow** [comment]
It's just an annoyance when you have to do it often, and have other uninitiated people complaining about it.
