### ISSUE TITLE
[1.15 bug] Graphics setting locked when editing settings in details

### ISSUE THREAD

**Issue by Naeqirelle** [sp614x/optifine#3280]
Basically, when you go into details and change some settings to fast or fancy and not default, it will cause the 'Graphics:' setting to become locked in place, so when you click it, it will not change between fast or fancy but instead just lock to a particular one

**Comment by sp614x** [comment]
Can't reproduce it.
Works for me.

**Comment by Naeqirelle** [comment]
![2020-02-14_14 58 18](https://user-images.githubusercontent.com/59464369/74542214-07c16100-4f3b-11ea-8554-c24bc3b4381d.png)

my settings in details

[optionsof.txt](https://github.com/sp614x/optifine/files/4204977/optionsof.txt)

^ also my config file

**Comment by sp614x** [comment]
Should be fixed in pre3.
