### ISSUE TITLE
Chunks won't load or show beyond 32 chunks.

### ISSUE THREAD

**Issue by zakattac** [sp614x/optifine#3282]
Any setting above 32 chunks won't show in OptiFine_HD_U_G1_pre1 running on Java_8_51.
![2020-02-13_12 33 03](https://user-images.githubusercontent.com/23201762/74465111-cc536380-4e62-11ea-9403-4fbacde7d066.png)
![2020-02-13_12 33 00](https://user-images.githubusercontent.com/23201762/74465114-cd849080-4e62-11ea-8255-6853c5f5ab52.png)

**Comment by sp614x** [comment]
Fixed, coming in next preview.
Also not working in 1.14.x, it would be fixed later.
