### ISSUE TITLE
[1.15] dynamic lighting does not work on signs, shulker boxes, mob heads and paintings.

### ISSUE THREAD

**Issue by Ratchet97** [sp614x/optifine#3283]
![2020-02-13_19 23 49](https://user-images.githubusercontent.com/48301568/74465892-831d0700-4e96-11ea-8295-016c34f1a10e.png)
![2020-02-13_19 24 16](https://user-images.githubusercontent.com/48301568/74465895-857f6100-4e96-11ea-92c9-b0ad2ffd4d0d.png)

**Comment by Ratchet97** [comment]
Banners and mob heads too

![2020-02-13_19 30 59](https://user-images.githubusercontent.com/48301568/74466391-659c6d00-4e97-11ea-9263-2ffb37c88cea.png)

**Comment by sp614x** [comment]
Fixed, coming next preview.
