### ISSUE TITLE
[1.15.2 HD U G1 pre1] Shaders aren't working.

### ISSUE THREAD

**Issue by kreffta** [sp614x/optifine#3284]

**Comment by derNiklaas** [comment]
![image](https://user-images.githubusercontent.com/12937331/74466333-430a5400-4e97-11ea-9cac-349a302c8fc7.jpg)

**Comment by Legoman99573** [comment]
this is known as per optifine updates channel in the discord

**Comment by sp614x** [comment]
This is known, shaders are disabled as they are completely broken.
