### ISSUE TITLE
[1.15.2 HD U G1 pre1] Reloading Resource Packs Glitch

### ISSUE THREAD

**Issue by AelinAnon** [sp614x/optifine#3286]
Whenever you reload resource packs (F3+T) all blocks disappear leaving only entities. If you break/place a block it loads only one chunk.
![2020-02-13_19 04 30](https://user-images.githubusercontent.com/61026138/74469427-8a431580-4e94-11ea-80e9-e16171da349a.png)
![2020-02-13_19 11 09](https://user-images.githubusercontent.com/61026138/74469459-9af38b80-4e94-11ea-951f-329d1a458f50.png)

**Comment by rizecookey** [comment]
This doesn't only happen with changing resource packs, it also seems to happen randomly when changing settings. It also just completely out of nowhere stops loading chunks sometimes.

**Comment by SiskooPOG** [comment]
Caused by `mc.worldRenderer.pauseChunkUpdates();` from loadShaderPack() in `net.optifine.shaders.Shaders` which is never resumed. (Shaders were probably on by default)

**Comment by sp614x** [comment]
Fixed, coming in next preview.
