### ISSUE TITLE
[1.15.2 HD U G1 pre1] crashed at start

### ISSUE THREAD

**Issue by timberzzman** [sp614x/optifine#3287]
The game just crashed when I try to launch it with the error "[net.minecraft.client.Minecraft/]: Unreported exception thrown!
java.lang.NoSuchMethodError: net.minecraft.client.renderer.entity.EntityRendererManager.validateRendererExistence()V"

Minecraft version: 1.15.2
Forge version: 31.1.1 and 31.1.0
Optifine version: 1.15.2 HD U G1 pre1
[2020-02-13-1.log](https://github.com/sp614x/optifine/files/4200660/2020-02-13-1.log)

**Comment by asbyth** [comment]
forge and optifine 1.15.2 arent compatible

**Comment by Nixuge** [comment]
Optifine 1.15 isn't compatible with forge

**Comment by sp614x** [comment]
Not compatible with Forge yet.

**Comment by Yoink3rs** [comment]
Does anyone have the website that shows when these will be avaliable?

**Comment by bonn2** [comment]
The official optifine discord has a channel that will tell you when it releases https://discord.gg/OptiFine just don't ask for an ETA there, the answer will be "When it's done"
