### ISSUE TITLE
Optifine capes on Ely.by

### ISSUE THREAD

**Issue by erickskrauch** [sp614x/optifine#329]
Hello.
My name is ErickSkrauch. I'm developer of [Ely.by](http://ely.by) project. [Ely.by](http://ely.by) is alternative Minecraft authorization service, which includes custom skin system for the people who want have additional features.

We also provide capes but we don't let our users to set their own ones. We just proxy cloak requests to Mojang.
Some users have donated to OptiFine, and that's fine, but we do not have complete list of OptiFine donators.

I suggest you to make some API that would return OptiFine donator list. I will cache it on my side and return proper cape on demand. After some time cache might be updated.

What do you think? Could you help solving this situation?

**Comment by sp614x** [comment]
You can check the user cape at "http://s.optifine.net/capes/<username>.png".
For example: http://s.optifine.net/capes/Notch.png
It will return 404 is the user has no cape.

**Comment by erickskrauch** [comment]
Yes, but response time is ~170ms (ping from Belarus to your server ~166ms).

I have a lot of textures requests (http://skinsystem.ely.by/textures/erickskrauch), where I should return additional field if cape exists. If I will make request to you server on each textures request it will significantly reduce performance of skinsystem server and will looks like http flood ddos atack for you.

**Comment by sp614x** [comment]
Currently there is no API for bulk checking of OptiFine capes. 
Requesting the cape file is the only way to check if the user has a cape.

**Comment by erickskrauch** [comment]
So I suggest you to make some API for this. It may be just text file, containing list of usernames, separated by EOL, which will update per time.

**Comment by Ghunghrooo** [comment]
I'd like a cape please. Anyone would do! My username for Ely.by is Ghunghrooo. It would be highly appreciated, for i am also a big fan of Ely.by! Thank you guys!

                         ~Ghunghrooo

**Comment by WRRealM7** [comment]
Merhaba! Ben ely.by bir hayranıyım. Bende pelerin istiyorum. Bana yardım ederseniz çok sevinirim! Ely.by adım WR_RealM7

**Comment by imjustlazybro** [comment]
Can anyone Put a Cape on my ely by account 
SenpaiSpider__ it's my ely by acc

**Comment by ZenithRogue** [comment]
Why are people trying to get free capes here????  That is not a thing

**Comment by VeriFried** [comment]
me too My name is VeriFried
