### ISSUE TITLE
[CEM] Mob skins are randomized based on distance?

### ISSUE THREAD

**Issue by DragendGhast** [sp614x/optifine#3290]
It seems that mobs will choose which skin to use (including skins set to only apply to babies) based on your distance from the mob. Pictured below is the same mob, the skin changed when I moved away
 and changed when I came back.
![2020-02-13_15 14 34](https://user-images.githubusercontent.com/49409042/74474794-332d4880-4e74-11ea-81ca-9ec268709c4c.png)
![2020-02-13_15 14 35](https://user-images.githubusercontent.com/49409042/74474800-37596600-4e74-11ea-8380-01a7916dfca8.png)

**Comment by sp614x** [comment]
Fixed, coming in next preview.
