### ISSUE TITLE
[1.15.2-OptiFine_HD_U_G1_pre1] Thrown eggs cause screen to momentarily go fully black.

### ISSUE THREAD

**Issue by Lucas7yoshi** [sp614x/optifine#3291]
When throwing eggs with the current pre release, the screen goes fully black for a moment.
[1.15.2-OptiFine_HD_U_G1_pre1](https://streamable.com/1uodi)

Compare this to 1.12.2 (just a version i have on hand), and you can see the effect (while still somewhat present) is not nearly as severe as it is in 1.15.2

[1.14.4 OptiFine](https://streamable.com/uao5h)

**Comment by sp614x** [comment]
It should behave better in next preview, it has some lighting fixes.
Probably 1.15.2 renders the egg a bit differently, looks like a vanilla problem.
