### ISSUE TITLE
[1.15.2-OptiFine_HD_U_G1_pre1] rendering issue, missing blocks etc.

### ISSUE THREAD

**Issue by chaosophy** [sp614x/optifine#3292]
Hi, had this odd issue just now.  
First two screens are from the same time at different angles.
F3+T to force a reload fix it for a bit.
But it happened soon after, screen shot #3.
Let me know if any more info needed.

Thanks.

![2020-02-13_20 31 54](https://user-images.githubusercontent.com/61028818/74476691-caf55b80-4ea1-11ea-8d2d-31bc13c5c5a2.png)

![2020-02-13_20 32 40](https://user-images.githubusercontent.com/61028818/74476706-d2b50000-4ea1-11ea-8a95-e738d989eae6.png)

![2020-02-13_20 35 29](https://user-images.githubusercontent.com/61028818/74476715-d9dc0e00-4ea1-11ea-871e-abc196042a27.png)

**Comment by chaosophy** [comment]
Sorry, didn't see the labels :(

First time here tbh, will try and remember in future. 👍 

Thanks again.

**Comment by TheRSC** [comment]
#3285

**Comment by chaosophy** [comment]
Just a quick update to say I've just tried the newer Pre2 build and the issue is still there but looking at the changelog I don't think it's been listed as fixed yet, so no biggy.
Oddly though it did seem to be a bit different this time, as in it seems to come and go now.  It appears and then disappears/fixes itself, where as before once it did it it seemed to stay there.
Though I could be mistaken as didn't test that thoroughly tbh.

Thanks again, I do appreciate all the work you put in on this.

**Comment by chaosophy** [comment]
Seems to be fixed in the Pre3 build.
Not extensively tested but didn't see the issue at all yet on the quick play around I've done with it.

thanks.
