### ISSUE TITLE
Natural Textures Causes Grass Side Overlay to be Misaligned

### ISSUE THREAD

**Issue by Arenovas** [sp614x/optifine#3297]
When natural textures are enabled in 1.15.2 G1 Pre1, grass renders with some odd bright pixels of grass on the sides, perhaps the overlay texture isn't being flipped as well?
![2020-02-13_13 52 11](https://user-images.githubusercontent.com/54878864/74482270-0c1d4980-4e69-11ea-831d-65e9a28bb9a1.png)

**Comment by iGalaxyYT** [comment]
Still present on 1.15.2 HD U G1 pre2

**Comment by sp614x** [comment]
Fixed, coming in next preview.
