### ISSUE TITLE
Smoke coming off from campfires is invisible when viewed through stained glass

### ISSUE THREAD

**Issue by VincyZed** [sp614x/optifine#3298]
Title pretty much says it all! This does not happen when viewed through normal glass.

**Comment by sp614x** [comment]
Is this the 1.15.2 preview?

**Comment by VincyZed** [comment]
Oh, yes sorry, forgot to mention! Yes 1.15.2 preview.

**Comment by sp614x** [comment]
This is a vanilla bug: https://bugs.mojang.com/browse/MC-170279

![image](https://user-images.githubusercontent.com/16635441/74839713-066eaa80-5326-11ea-856d-2f99175d535d.png)
