### ISSUE TITLE
Rainbow Stuff Coming Through Blocks

### ISSUE THREAD

**Issue by ShadowLove101** [sp614x/optifine#3300]
Don't know what this is but here ya go.
![2020-02-13_16 04 13](https://user-images.githubusercontent.com/61032152/74486949-85259c80-4e7b-11ea-9789-ef279676aee6.png)
![2020-02-13_16 04 37](https://user-images.githubusercontent.com/61032152/74486948-83f46f80-4e7b-11ea-91d0-b5dda46e5a53.png)

**Comment by renetame** [comment]
Yep! Just had a similar issue. Here is a couple views of the visual glitch, but upclose in the same time/location. It appeared while I was digging grass.
![2020-02-13_17 12 25](https://user-images.githubusercontent.com/61032180/74487049-890dea80-4e8c-11ea-92fa-42629754ff6b.png)
![2020-02-13_17 12 45](https://user-images.githubusercontent.com/61032180/74487053-8d3a0800-4e8c-11ea-91d7-f417492c84c9.png)

**Comment by chaosophy** [comment]
I posted the same issue here...

https://github.com/sp614x/optifine/issues/3292

that was while mining underground.

**Comment by sp614x** [comment]
Should be fixed in pre3.
