### ISSUE TITLE
chunk error?

### ISSUE THREAD

**Issue by thepatriotfox** [sp614x/optifine#3302]
is it just my pc or are others having this issue when turning the smooth lighting to maximum 
![2020-02-13_18 34 49](https://user-images.githubusercontent.com/61033780/74490969-dd669980-4e8f-11ea-8eca-bb4e462e70dc.png)

**Comment by Titaniumtown** [comment]
Same issue

**Comment by SiskooPOG** [comment]
Managed to reproduce this exact same rendering issue by toggling shaders on/off (although they don't work ofc). I don't know if this is the same origin of the bug but it's definitely the same result.

**Comment by erics19** [comment]
The same thing, I think it can only fix after they update?

**Comment by sp614x** [comment]
Fixed, coming in next preview.
