### ISSUE TITLE
polygons error when place some block and error chunk update

### ISSUE THREAD

**Issue by exfine** [sp614x/optifine#3305]
[
![2020-02-14_08 29 33](https://user-images.githubusercontent.com/54712907/74493390-9a92d900-4f04-11ea-9a2a-01e082ca6bd9.png)
](url)

**Comment by NitroCipher** [comment]
😶

**Comment by TheRSC** [comment]
#3292

**Comment by sp614x** [comment]
Should be fixed in pre3.
