### ISSUE TITLE
if you turn off bettergrass this happens

### ISSUE THREAD

**Issue by KaiAF** [sp614x/optifine#3306]
![Screenshot_85](https://user-images.githubusercontent.com/60985521/74498036-f0d02f80-4ea4-11ea-9ad0-ce4871a455ae.png)
This is not normal, i think

**Comment by KaiAF** [comment]
I just set it back to the normal settings and its still doing it, i have to restart too see blocks again!

**Comment by sp614x** [comment]
This is a bug in reloading textures or reloading chunks.

**Comment by mc76855** [comment]
i had the same issue but its because shaders were on and when i turned shaders off my game crashed and when i loaded back in the world loaded in

**Comment by sp614x** [comment]
Fixed, coming in next preview.

**Comment by KaiAF** [comment]
Thanks man, ly
