### ISSUE TITLE
Sides of grass blocks seem strange (1.15.2 HD U G1 pre1)

### ISSUE THREAD

**Issue by devereaux98** [sp614x/optifine#3309]
Attached is this screenshot that demonstrates what I mean.  Thank you guys for all you do :)

![image](https://user-images.githubusercontent.com/22154989/74500095-2247fb80-4ea3-11ea-8edf-0e7c3a4dd5f0.png)

**Comment by sp614x** [comment]
Caused by Natural Textures

**Comment by sp614x** [comment]
Duplicate of #3297.

**Comment by devereaux98** [comment]
> Caused by Natural Textures

Apologies, thanks for being patient haha
