### ISSUE TITLE
visual bug textures

### ISSUE THREAD

**Issue by Greddy38** [sp614x/optifine#3311]
![Screenshot_1](https://user-images.githubusercontent.com/61041824/74508291-a77def80-4f39-11ea-831f-3ea4d0ede4a7.png)
at a certain angle, a texture bug comes in

**Comment by ElGokuPez** [comment]
![2020-02-13_23 37 42](https://user-images.githubusercontent.com/61042273/74509211-afa94100-4edf-11ea-9100-31dc43976f51.png)
while mining i saw these black particles by breaking blocks
![2020-02-13_23 12 38](https://user-images.githubusercontent.com/61042273/74509242-c51e6b00-4edf-11ea-8f2e-8c21057dbdde.png)
and this

**Comment by illaoi1** [comment]
I have this problem too!
![image](https://user-images.githubusercontent.com/61083916/74587834-71706680-5032-11ea-9649-5c9747f79143.png)

**Comment by franiscoder** [comment]
I have this problem too, glad it's not just me!

**Comment by Harfeur** [comment]
I had the same problem on OptiFine 1.15.2 HD U G1 pre2
It appears when just after breaking a block
![2020-02-17_17 45 49](https://user-images.githubusercontent.com/22135449/74672697-224f4080-51ae-11ea-9327-352dc5af5898.png)
![2020-02-17_17 46 06](https://user-images.githubusercontent.com/22135449/74672704-254a3100-51ae-11ea-82f9-7160ff6f1d78.png)
![2020-02-17_17 46 00](https://user-images.githubusercontent.com/22135449/74672709-27ac8b00-51ae-11ea-8177-83c07ada60cf.png)
[latest.log](https://pastebin.com/z5vZj4qk)

**Comment by Harfeur** [comment]
It appears on the same block each time (breaking / placing) located at X:1615 Y:63 Z:1417 with seed : `-1193216783728684999` on a server (maybe also in solo)

**Comment by AngelKotik** [comment]
same

**Comment by sp614x** [comment]
Should be fixed in pre3.
