### ISSUE TITLE
Visual glitch

### ISSUE THREAD

**Issue by ludodv** [sp614x/optifine#3314]
![2020-02-13_17 52 49](https://user-images.githubusercontent.com/31469881/74524436-519c4e00-4f1f-11ea-82ac-f4bbb419a3ec.png)

**Comment by Quavelen** [comment]
Maybe try paying attention:

![image](https://user-images.githubusercontent.com/19168008/74527482-b787d600-4f1d-11ea-85be-a5888dd9e525.png)

**Comment by sp614x** [comment]
Should be fixed in pre3.
