### ISSUE TITLE
~Invalid

### ISSUE THREAD

**Issue by LapisDemon** [sp614x/optifine#3315]
~nvm, for some reason it works now, sorry, can be closed.

**Comment by Quavelen** [comment]
For future reference, it's also worth noting this, stated by sp614x: 

![image](https://user-images.githubusercontent.com/19168008/74527482-b787d600-4f1d-11ea-85be-a5888dd9e525.png)

Not all features work yet, and many things are broken and missing. The full release will resolve all of this.

**Comment by LapisDemon** [comment]
Yes, of course, I just thought it may be worth mentioning, but I'll hold back with any issue reports until the full release, sorry! It seems sometimes the double chest work, sometimes they don't, it's a bit funky, but nothing to worry about imo :)

E.g. my custom colours for a spawn egg doesn't work, so I would assume this is one of those features which aren't working yet.
Custom redstone wire colour does work though.

I'm just very happy OF is out now :)

Have a good day!
_Meri_
