### ISSUE TITLE
[1.15.2 G1 pre1] Block update rendering problem

### ISSUE THREAD

**Issue by cs127** [sp614x/optifine#3316]
Any changes made to blocks will not be rendered until a block is placed or broken adjacent to them. This includes:

- Explosions

- Using a hoe on dirt to make farmland

- Using a shovel on grass to make a path block

- Placing a block by using /setblock, /fill, or other commands

**Comment by SiskooPOG** [comment]
Happened to me when shaders were pre enabled because of an older optifine version. To reproduce just turn shaders on. To fix the issue just turn shaders to off and relaunch the game

**Comment by sp614x** [comment]
Fixed, coming in next preview.
