### ISSUE TITLE
OptiFine [1.15.2] HD U G1 pre1 placing grass/dirt block in the water

### ISSUE THREAD

**Issue by stiffidy** [sp614x/optifine#3317]
Well i was placing grass/dirt blocks in the water and this happened. Sometimes it seemed like when i placed down a dirt block, the glitch happened, and when it converted to grass, it went away.
![IMG-20200214-WA0010](https://user-images.githubusercontent.com/39996004/74533925-6686da80-4f3b-11ea-997a-24181b8104f0.jpeg)
e: i don't have any resource packs / shaders

**Comment by sp614x** [comment]
Should be fixed in pre3.
