### ISSUE TITLE
[1.15.2] CIT armor textures

### ISSUE THREAD

**Issue by sonyable** [sp614x/optifine#3318]
CIT item textures are working on this build but not armor textures.

**Comment by sp614x** [comment]
Version?

**Comment by AaronLieb** [comment]
The textures for the actual items of each armor piece (diamond helmet, iron boots) work correctly but the models for the armor while on a player or mob do not work. (custom texture does not display)

**Comment by HanFox** [comment]
OptiFine_1.15.2_HD_U_G1_pre4

I can confirm that the armour textures aren't working.

PureBDcraft has an addon that adds a handful of armour swaps via rename (diamond armour to things like "Neptune Boots", etc.) and the armour entity texture does not change.

No error in the log (in fact the log states it finds the file just fine).
`[08:35:59] [Server-Worker-7/INFO]: [OptiFine] CustomItems: optifine/cit/armour/neptune/boots.properties`

Example .properties (which works in MC1.14):
```
type=armor
items=diamond_boots
texture.diamond_layer_1=textures/models/armor_alt/neptune_layer_1.png
nbt.display.Name=pattern:Neptune Boots
```

**Comment by sp614x** [comment]
Custom armor textures and custom glint are disabled as they are broken currently.

**Comment by Helwdrokin** [comment]
buh, apparently the elytra texture works, i was finishing my slimeun texture ;~;

**Comment by sp614x** [comment]
Fixed, coming in pre20.
