### ISSUE TITLE
No Vanilla CTM after adding Chisel Mod

### ISSUE THREAD

**Issue by TheRealDadbeard** [sp614x/optifine#332]
Basically CTM for vanilla textures doesn't work, but chisel blocks behave correctly. This is their issue https://github.com/Chisel-Team/Chisel/issues/273

I added mod by mod that i use and that happens excactly after adding chisel.

**Comment by sp614x** [comment]
Further discussions: Chisel-Team/Chisel#273

**Comment by TheRealDadbeard** [comment]
Thank you for taking your time trying to resolve this.

**Comment by sp614x** [comment]
Fixed by Chisel by extending BlockStateBase: https://github.com/Chisel-Team/Chisel/issues/273#ref-commit-87da66b
