### ISSUE TITLE
[1.15.2] Placing translucent blocks in east-south neighbour chunk causes blocks to disappear

### ISSUE THREAD

**Issue by sp614x** [sp614x/optifine#3322]
Placing translucent blocks (stained glass) diagonally in the neighbour east-south chunk causes all translucent blocks in the chunk to disappear. They reappear after the player moves, only happens in east-south (diagonal) direction.

**Comment by sp614x** [comment]
The missing blocks also reappear if the nadheld item is changed to another block type.

**Comment by sp614x** [comment]
This only happens when holding a translucent block in any hand and the hand/hotbar is visible. 
Hiding the had/hotbar with F1 fixes the problem.

**Comment by SiskooPOG** [comment]
Seems to happen whenever you get the VertexBuilder with `getBuffer()` in `ItemRenderer` `renderItem()`
Changing the IVertexBuilder RenderType to `Atlases.getTranslucentCullBlockType()` fixes the issue. This render type is apparently already used for GUI's and is not used for hand render in vanilla, so I'm not 100% sure about how clean is that fix, however it doesn't seem to trigger any new rendering issues.

**Comment by sp614x** [comment]
Fixed it by running the immediate updates always on the render thread.
