### ISSUE TITLE
nosucherror crash report while trying to use mods

### ISSUE THREAD

**Issue by limitedlegend14** [sp614x/optifine#3323]
[crash-2020-02-14_20.51.18-client.txt](https://github.com/sp614x/optifine/files/4205095/crash-2020-02-14_20.51.18-client.txt)

**Comment by rkdrns4747** [comment]
same result

**Comment by Quavelen** [comment]
... @limitedlegend14, and @rkdrns4747 you *do* understand that reading is a basic requirement for just about everything, right?

![image](https://user-images.githubusercontent.com/19168008/74581406-fca41a80-4fa6-11ea-9843-3000e01f209b.png)

**Comment by rkdrns4747** [comment]
> ... @limitedlegend14, and @rkdrns4747 you _do_ understand that reading is a basic requirement for just about everything, right?
> 
> ![image](https://user-images.githubusercontent.com/19168008/74581406-fca41a80-4fa6-11ea-9843-3000e01f209b.png)

omg I didnt know that.
thanks for notifying btw :)

**Comment by sp614x** [comment]
Not compatible with Forge
