### ISSUE TITLE
Buggy dynamic lights [1.15.2 first preview]

### ISSUE THREAD

**Issue by Luis007lol** [sp614x/optifine#3325]
It's hard to explain, so i made a [video](https://www.youtube.com/watch?v=Ql48zPugwZs&feature=youtu.be)

**Comment by SiskooPOG** [comment]
Were your shaders pre-enabled because you used an older optifine version before ? That exact issue happened to me, fixing it was just a matter of changing your shader options to off and relaunching your game

**Comment by Luis007lol** [comment]
Thanks!
