### ISSUE TITLE
1.15.2 In-Game Glitch

### ISSUE THREAD

**Issue by NohjBalboa** [sp614x/optifine#3326]
So i was playing on a server and then this happened....the reason is unknown to me
![2020-02-14_19 19 55](https://user-images.githubusercontent.com/61061618/74554188-98129c80-4f61-11ea-976b-33dd1ebc48a3.png)
![2020-02-14_19 20 01](https://user-images.githubusercontent.com/61061618/74554197-9c3eba00-4f61-11ea-92a8-32f86acd0408.png)
![2020-02-14_19 20 10](https://user-images.githubusercontent.com/61061618/74554206-9f39aa80-4f61-11ea-8d66-a8c34d1301cc.png)

**Comment by cs127** [comment]
this has been happening to everyone.

**Comment by sp614x** [comment]
Should be fixed in pre3.
