### ISSUE TITLE
Mob flickering issue with biome/random based textures.

### ISSUE THREAD

**Issue by GamerGuy95953** [sp614x/optifine#3329]
So there's a weird thing with biome based/random textures for mobs. They seem to flicker based on a camera position and/or mob position. I kept the F3 menu open if there any information there to help. This is happening on 1.15.2 pre 2 on the default super flat world.

Couldn't send it as a video so here's a GfyCat link: https://gfycat.com/uniqueslimybream

**Comment by sp614x** [comment]
Fixed, coming in next preview.
