### ISSUE TITLE
Disappearing entities

### ISSUE THREAD

**Issue by mchorse** [sp614x/optifine#333]
Hello there!

I experience a really annoying issue with my mod and Optifine. My custom mod entities are disappearing sometimes for unknown reasons. This looks like an Optifine bug, because I cannot reproduce it with Forge and without Optifine. Here are some videos of issue:

* [Test 0](https://www.youtube.com/watch?v=CAWDLUZu1Io)
* [Test 1](https://youtu.be/pA1lRmDAyWU)
* [Test 2](https://youtu.be/SjtY6jAddzw)

Is there any workaround that you could think of? First, I thought it was some bug related to desynchronization of player rotation on server and client, or the Optifine's rendering optimization when an entity not rendered when it's stuck in the block.

If you need to see how those entities works, here are the classes that responsible for those entities' movement:

* [EntityActor.java](https://github.com/mchorse/blockbuster/blob/dev/src/main/java/mchorse/blockbuster/common/entity/EntityActor.java#L197)
* [RecordPlayer.java](https://github.com/mchorse/blockbuster/blob/dev/src/main/java/mchorse/blockbuster/recording/RecordPlayer.java#L79)
* [Frame.java](https://github.com/mchorse/blockbuster/blob/dev/src/main/java/mchorse/blockbuster/recording/data/Frame.java#L100)

This playback of frames is running on both sides. Just in case if you need that information.

I tested it with Optifine 1.10.2 HD C3 and D3. On D3 it happens only once, however, on C3 it happens occasionally.

Thanks!

**Comment by sp614x** [comment]
OptiFine D1 for 1.10.2 has a bugfix for disappearing entities when standing still.
The entites should appear immediately when moving a little (rotate, walk, etc).

**Comment by mchorse** [comment]
Thanks for reply. However, why is it happens? And, is there any other workaround?

**Comment by sp614x** [comment]
This is a side effect of one optimization which does not affect the normal play as the player is usually moving.

**Comment by mchorse** [comment]
Ok, thanks for clarification! :)

I hope moving even by 0.00001 will solve this issue.
