### ISSUE TITLE
Missing cell/bucket icon with tech reborn 

### ISSUE THREAD

**Issue by ahkui** [sp614x/optifine#3331]
<img width="1680" alt="Screen Shot 2020-02-15 at 2 18 08 PM" src="https://user-images.githubusercontent.com/14049597/74583046-00af5700-4ffe-11ea-931e-3a81ddb2ea40.png">

**Comment by sp614x** [comment]
Version?

**Comment by ahkui** [comment]
Tech reborn: 3.3.4

**Comment by oOLegendOo** [comment]
> Version?

optifine 1.15.2 preview with Techreborn 3.3.4-build.189(Fabric mod)
At present all of the optifine 1.15.2 preview versions have this bug

**Comment by KaiAF** [comment]
Is this still an issue?
