### ISSUE TITLE
[1.15.2-G1-pre2]Can't set graphic setting to fancy

### ISSUE THREAD

**Issue by oOLegendOo** [sp614x/optifine#3333]
When try to set graphic setting(Minecraft video setting,not graphic drivers) to fancy it will automatically return to fast.
I don't know whether just my Minecraft 1.15.2 with optifine has this bug
If it is a bug please fix it.Thanks
(I am sorry,my english is not good.I hope you can understand what I say)

**Comment by oOLegendOo** [comment]
Looks like it has become normal now.
So I close this

**Comment by oOLegendOo** [comment]
Looks like "Dropped Items" settings causes this problem.Set this to fancy or default could solve this problem.

**Comment by sp614x** [comment]
Fixed, coming in next preview.
