### ISSUE TITLE
[1.15.2] Get CustomSky working

### ISSUE THREAD

**Issue by SiskooPOG** [sp614x/optifine#3334]
To get custom sky working properly you need to translate the MatrixStack (or you could recode the render thingy and use an IVertexBuilder to render the textures into place).

To get it working with MatrixStacks with a few lines of code would be this adding this in the renderSky function in CustomSky (requires you to pass mc's MatrixStack into the function):
`RenderSystem.pushMatrix();
RenderSystem.multMatrix(matrixStackIn.getLast().getMatrix());`
and then pop the matrix at the end:
`RenderSystem.popMatrix();`

Oh and I don't know if it's on my end or not, but It had issues loading the ResourceLocation, was fixed easily tho

![2020-02-15_13 59 22](https://user-images.githubusercontent.com/61063886/74588311-87af0000-4ffb-11ea-9bcf-ae1f99596a8d.png)

**Comment by sp614x** [comment]
This is very helpful, I will check it out tomorrow.

**Comment by sp614x** [comment]
Fixed, coming in next preview.
