### ISSUE TITLE
[1.15.2 Prerelease-2] Crash while running with mekanism 1.15.2

### ISSUE THREAD

**Issue by term2112** [sp614x/optifine#3336]
**Forge: 31.1.0** 
**Optifine: 1.15.2 Prerelease-2** 
**Other relevant version: mekanism 9.9.9**

-I did not know if forge was still incompatible since this is now prerelease-2
-crashlog:
The game crashed whilst initializing game
Error: java.lang.IllegalStateException: **No renderer registered for mekanism:flame**

-it appears to be a conflict with the mekanism mod, not with forge

[crash-2020-02-15_11.14.29-client.txt](https://github.com/sp614x/optifine/files/4208734/crash-2020-02-15_11.14.29-client.txt)

**Comment by Studio528-real** [comment]
![image](https://user-images.githubusercontent.com/52116771/74591572-317b9600-4fd6-11ea-9078-9d65583bf1a0.png)

**Comment by term2112** [comment]
ok, thank you.
