### ISSUE TITLE
[OptiFine 1.15.2 HD U G1 pre2] glass pane in ctm have bug

### ISSUE THREAD

**Issue by Command1264** [sp614x/optifine#3337]
![2020-02-16_01 29 01](https://user-images.githubusercontent.com/50344708/74592423-47cc3500-505c-11ea-9de1-475d40069804.png)
![2020-02-16_01 29 09](https://user-images.githubusercontent.com/50344708/74592426-4bf85280-505c-11ea-976e-766db52ac7f5.png)
![2020-02-16_01 29 24](https://user-images.githubusercontent.com/50344708/74592430-4e5aac80-505c-11ea-908a-dab8948de81a.png)
![2020-02-16_01 29 29](https://user-images.githubusercontent.com/50344708/74592431-50247000-505c-11ea-8a6b-72d11ea9ce95.png)
when use optifine. Material that should be transparent. It Appeared white

Minecraft version:1.15.2
Optifine version:1.15.2 HD U G1 pre2
Other:None

**Comment by sp614x** [comment]
Works for me:

![image](https://user-images.githubusercontent.com/16635441/74843680-8dbf1c80-532c-11ea-9096-352899a39d76.png)

Also with Programmer Art:

![image](https://user-images.githubusercontent.com/16635441/74843768-b21af900-532c-11ea-99e5-c3f8892a3473.png)

The resource pack should not use custom pane models to avoid CTM problems.
