### ISSUE TITLE
when opening wooden door the animation does not happended and i looks closed but u can go through it.

### ISSUE THREAD

**Issue by alexrocketman** [sp614x/optifine#3338]

**Comment by chaosophy** [comment]
Are you using a resource pack?  I had this with doors and trapdoors when using a resource pack that replaced them but turning it off seemed to fix it.  Though tbh I haven't tried the pack again.

**Comment by alexrocketman** [comment]
> Are you using a resource pack? I had this with doors and trapdoors when using a resource pack that replaced them but turning it off seemed to fix it. Though tbh I haven't tried the pack again.

i dont remember if i used a pack tbh.

**Comment by sp614x** [comment]
Version?

**Comment by sp614x** [comment]
Should be fixed in last preview.
