### ISSUE TITLE
Chunks doesn't (re)load correctly

### ISSUE THREAD

**Issue by RootRobo** [sp614x/optifine#3339]
If you load chunks or reload (this includes changing some graphical options), all blocks turn invisible
Joining servers included. After a restart the chunks are loaded correctly.
An example (Hypixel Lobby):
![2020-02-15_20 06 59](https://user-images.githubusercontent.com/47434248/74593750-f8234480-502e-11ea-9bad-3a77db6d8a55.png)

**Comment by sp614x** [comment]
Fixed, coming in next preview.
