### ISSUE TITLE
Chests Gone (1.11 preview A1-A2)

### ISSUE THREAD

**Issue by GRAnimated** [sp614x/optifine#334]
So I am getting this weird issue, which doesn't happen in any other version of optifine. The issue is that whenever I unload chunks with any chests in it some of the chests are gone, creating some weird bugs, like 1 side of a double chest, and other things. Once I open the chest which was gone, it reappears. This only happens in multiplayer... (I've found the issue happening on servers such as, my vanilla server, my friend's server, mineplex, cubecraft, and primemc)

**Comment by sp614x** [comment]
Is this also happening in vanilla?

**Comment by GRAnimated** [comment]
nope, only with optifine, if i install it with forge, just found out it won't happen...

**Comment by sp614x** [comment]
Probably a Forge bug.
Does it happen with OptiFine standalone installed (no Forge)?

**Comment by sp614x** [comment]
I can not reproduce it. 
Tested with OptiFine A5 for 1.11, no Forge.

**Comment by GRAnimated** [comment]
I now am thinking that it's just my graphics driver or something, or maybe something you fixed on accident... I can only get it to happen in A1 and A2

**Comment by sp614x** [comment]
Then it should be resolved.
