### ISSUE TITLE
Weird when I place a pane glass

### ISSUE THREAD

**Issue by CyberRyan1** [sp614x/optifine#3340]
When I place a pane glass in between two blocks, this happens (I don't know how to describe it)

![2020-02-15_13 49 16](https://user-images.githubusercontent.com/52432798/74594314-5550d300-4ffa-11ea-8f3a-0df9cb6c03b5.png)

**Comment by ThePromisedLAN** [comment]
Press F3 + G to show chunk boundaries. Your problem is most likely related to https://github.com/sp614x/optifine/issues/3322

**Comment by CyberRyan1** [comment]
No, I moved around and it still stayed the same. Unfortunately I closed my mc to get rid of it, so I can't see it any longer (probably a stupid mistake on my part, sorry). I will try to recreate it, though.

**Comment by CyberRyan1** [comment]
Alright, I recreated it with my chunk borders enabled.
![2020-02-15_14 06 18](https://user-images.githubusercontent.com/52432798/74594470-76b2be80-4ffc-11ea-9880-643385966fe2.png)

**Comment by CyberRyan1** [comment]
^ Regarding that, I can move around and it won't change at all. I was on a server, so that may cause things. I don't know if this is related, but just in case.

**Comment by SiskooPOG** [comment]
Mind sharing your optifine settings/ressource pack ?

**Comment by CyberRyan1** [comment]
Of course!
(I have never done this before, so I might list some settings that are not optifine, or list some unneeded settings)
I am going to include screenshots of my settings to be more efficient.

https://gyazo.com/ebc46f78561a2eca506ab73cbe354215
https://gyazo.com/253a46983b3d7fb3952bf7d3e1ec224e
https://gyazo.com/419573dc3adf69c73a04707f0c69f15d
https://gyazo.com/9799abafd67ad2ee29253bf1e4e72285
https://gyazo.com/f586d99274b7a7eae48269dce3e78ee4
https://gyazo.com/8e25d24e3b42879ad65411df85513437
https://gyazo.com/b75b1aace22641f2d2f348767b1bd1ea

Texture Pack:
[VanillaTweaks_r990615.zip](https://github.com/sp614x/optifine/files/4209079/VanillaTweaks_r990615.zip)

**Comment by CyberRyan1** [comment]
If you want me to get rid of the links and put them as actual screenshots, lmk

**Comment by sp614x** [comment]
Should be fixed in pre3.
