### ISSUE TITLE
Light bug report 1.15.2 pre2

### ISSUE THREAD

**Issue by opysium** [sp614x/optifine#3341]
This problem occurs when I place torch or break blocks sometime.
![2020-02-15_23 30 51](https://user-images.githubusercontent.com/40427422/74595188-a17a3280-504f-11ea-8382-803ba57305ac.png)
![2020-02-15_23 30 55](https://user-images.githubusercontent.com/40427422/74595191-a2ab5f80-504f-11ea-92c2-6ccd0e5a7cf2.png)
![2020-02-15_23 31 35](https://user-images.githubusercontent.com/40427422/74595193-a3dc8c80-504f-11ea-8d8b-81091b932ce3.png)
![2020-02-15_23 31 39](https://user-images.githubusercontent.com/40427422/74595194-a4752300-504f-11ea-91b9-818cf095eeab.png)
![2020-02-15_23 31 44](https://user-images.githubusercontent.com/40427422/74595196-a50db980-504f-11ea-86f5-bcc1310b9630.png)
![2020-02-15_23 44 23](https://user-images.githubusercontent.com/40427422/74595198-a5a65000-504f-11ea-87d6-89ab6d78447c.png)
**IF YOU WANT GAME SETTINGS, CHECK HERE I TRIED DISABLE VBOs BUT NOTHING CHANGE**
![2020-02-16_00 21 21](https://user-images.githubusercontent.com/40427422/74595460-94ab0e00-5052-11ea-9cac-1d23c7bb12de.png)
![2020-02-16_00 21 34](https://user-images.githubusercontent.com/40427422/74595461-95dc3b00-5052-11ea-997e-2e8ba59f255b.png)
![2020-02-16_00 21 38](https://user-images.githubusercontent.com/40427422/74595462-95dc3b00-5052-11ea-8010-c1eb2e4859d4.png)
![2020-02-16_00 21 41](https://user-images.githubusercontent.com/40427422/74595463-9674d180-5052-11ea-8c7d-8c9091dab7bb.png)
![2020-02-16_00 21 43](https://user-images.githubusercontent.com/40427422/74595464-970d6800-5052-11ea-857c-6e5ce345b21e.png)
![2020-02-16_00 21 45](https://user-images.githubusercontent.com/40427422/74595465-97a5fe80-5052-11ea-9444-f3f73668059b.png)

**Comment by ElGokuPez** [comment]
Dynamic Lights Bug While Mining
![2020-02-16_03 48 30](https://user-images.githubusercontent.com/61042273/74600446-adc2b780-5070-11ea-8fe2-c52b614e4603.png)
![2020-02-16_03 48 34](https://user-images.githubusercontent.com/61042273/74600448-af8c7b00-5070-11ea-9004-8ee7caf0ea66.png)

**Comment by opysium** [comment]
i didn't use dynamic lights

**Comment by sp614x** [comment]
Should be fixed in pre3.
