### ISSUE TITLE
Screen Tearing

### ISSUE THREAD

**Issue by Thornog** [sp614x/optifine#3342]
Getting some sort of artifacting light issue when interacting with this gate. 

![Screen Tearing of sort 2](https://user-images.githubusercontent.com/61098391/74596909-3f9fd580-501b-11ea-92ec-120097b1a69e.png)
![Screen Tearing of sort](https://user-images.githubusercontent.com/61098391/74596910-40d10280-501b-11ea-8298-266439d9138a.png)

**Comment by AmbassadorLaZer** [comment]
Is this the 1.15.2 preview version?

**Comment by Sneakometer** [comment]
This isn't screen tearing. It's more like vertex explosions.

**Comment by sp614x** [comment]
Should be fixed in pre3.
