### ISSUE TITLE
crash on hacked clients

### ISSUE THREAD

**Issue by 40H4** [sp614x/optifine#3343]
so i use a hacked client (for anarchy servers not normal survival servers chill out) and i obviously wanted to use the new client no matter how bad so i installed it using the awesome in client addon adder it asked me to reset so i did and the next time i booted up and logged onto my anarchy server of choice it instantly froze up and then crashed might be the client might be the addon thing but still worth reporting imo everything helps right

**Comment by Brottweiler** [comment]
"Hacked clients" are against Mojang Terms of Service. I do not expect you to be able to get any support here for using Optifine with **illegal software**.

**Comment by sp614x** [comment]
OptiFine doesn't support hacked clients.
