### ISSUE TITLE
Chunks doesn´t (re)load correctly and other bugs

### ISSUE THREAD

**Issue by iViMaister** [sp614x/optifine#3344]
![2020-02-15_12 07 49](https://user-images.githubusercontent.com/61108053/74602173-593a2f00-50a6-11ea-827f-9767607f0d21.png)
![2020-02-15_21 59 56](https://user-images.githubusercontent.com/61108053/74602174-59d2c580-50a6-11ea-9875-522da84fd65e.png)
![2020-02-15_22 06 20](https://user-images.githubusercontent.com/61108053/74602176-5b03f280-50a6-11ea-81f8-65390fba6e93.png)
![2020-02-15_22 09 11](https://user-images.githubusercontent.com/61108053/74602177-5b9c8900-50a6-11ea-9a9c-63e4270afb9e.png)
![2020-02-16_00 16 36](https://user-images.githubusercontent.com/61108053/74602178-5b9c8900-50a6-11ea-894c-f36f0a439290.png)
![2020-02-16_00 17 09](https://user-images.githubusercontent.com/61108053/74602179-5ccdb600-50a6-11ea-8c52-cfc8bed656e6.png)

**Comment by sp614x** [comment]
Should be fixed in pre3.
