### ISSUE TITLE
Biome blend messes up texture loading

### ISSUE THREAD

**Issue by ZmetkovoDoupe** [sp614x/optifine#3346]
I don't think my settings are important on this. When adjusting the biome blend settings (was originally on 11x11), it just unloaded every texture and i had to update a block (by placing or destroying something) in the chunk to load it. And it didn't load the whole chunk, just a part of it.

I noticed this in pre-release 1, even restarting did not help, had to use version without optifine to fix it

**Comment by sp614x** [comment]
How is it in pre3?

**Comment by sp614x** [comment]
Fixed, coming in next preview.
