### ISSUE TITLE
This

### ISSUE THREAD

**Issue by Alex-M00re** [sp614x/optifine#3349]
I'm not super sure or super smart when it comes to these things, but I took a bunch of screenshots of the things I saw while playing with Optifine last night
![2020-02-15_13 12 03](https://user-images.githubusercontent.com/51332047/74609868-2b072000-50a3-11ea-9d9e-c2dea71e9b23.png)
![2020-02-15_13 36 41](https://user-images.githubusercontent.com/51332047/74609870-2c384d00-50a3-11ea-89d1-500271327662.png)
![2020-02-15_13 45 56](https://user-images.githubusercontent.com/51332047/74609871-2c384d00-50a3-11ea-98b3-1a46a4efbe36.png)
![2020-02-15_13 59 58](https://user-images.githubusercontent.com/51332047/74609872-2cd0e380-50a3-11ea-9a92-603c5b66b30f.png)

**Comment by sp614x** [comment]
Should be fixed in pre3.
