### ISSUE TITLE
1.15.2 HD U G1 pre2 - CIT with nbt.display.Name works only partially 

### ISSUE THREAD

**Issue by Thr0in** [sp614x/optifine#3351]
Custom model/texture is only applied in GUI not in mainhand, offhand, ...

CIT-properties file:
`type=item`
`items=minecraft:lantern`
`model=item/geisterlaterne.json`
`nbt.display.Name=Geisterlaterne`

![lantern](https://user-images.githubusercontent.com/61120415/74610275-100fcc80-50f2-11ea-952a-e6b6a520d284.png)
Default custom model

![geisterlaterne](https://user-images.githubusercontent.com/61120415/74610281-14d48080-50f2-11ea-9e71-9c5870a7035b.png)
CIT custom model; works the same way with uncolored, italic, ... display name

**Comment by naeqirelle2020** [comment]
@Thr0in is this still an issue in the latest preview?

**Comment by Thr0in** [comment]
@naeqirelle2020 I've tested it right now. Seems like it works now
