### ISSUE TITLE
Blocks not rendered + Glitchy triangles

### ISSUE THREAD

**Issue by Pitheca** [sp614x/optifine#3353]
Another report of the weird triangles with weird textures; they were only visible from one side each.  Also, all solid blocks in the chunk between certain y-levels were invisible, however, tile entities were rendered. Some of the triangles extended out of this chunk, though. This is on "OptiFine 1.15.2 HD U G1 pre2"
![2020-02-16_13 54 03](https://user-images.githubusercontent.com/61122061/74610951-d45f0d80-50c5-11ea-9c0d-50a616b063eb.png)
![2020-02-16_13 54 19](https://user-images.githubusercontent.com/61122061/74610952-d5903a80-50c5-11ea-99f4-5b8e5f71b4c0.png)
![2020-02-16_13 54 46](https://user-images.githubusercontent.com/61122061/74610953-d628d100-50c5-11ea-97cf-eb20ae008de8.png)
![2020-02-16_13 53 39](https://user-images.githubusercontent.com/61122061/74610954-d6c16780-50c5-11ea-9c7f-bc242f8d8a9b.png)

**Comment by sp614x** [comment]
Should be fixed in pre3.
