### ISSUE TITLE
F3+A not working in HD U G1 pre2

### ISSUE THREAD

**Issue by purringcat248** [sp614x/optifine#3354]
F3+A normally resets all the block rendering so that you can fix client-side rendering issues (such as a chunk refusing to render). On the new unstable release of OptiFine 1.15.2, F3+A resets all the block rendering but doesn't rerender anything.

**Comment by CleaveGodz** [comment]
> 
> 
> F3+A resets all the block rendering but doesn't rerender anything.

Can confirm F3+A works. Most render bugs are fixed with it. The problem is that there are some chunks that directly don't get _generated_ at all.

**Comment by Hellster90** [comment]
Works ok for me

**Comment by sp614x** [comment]
Fixed, coming in next preview.
