### ISSUE TITLE
Mod not working

### ISSUE THREAD

**Issue by FireGamesCZ** [sp614x/optifine#3355]
When I installed OptiFine as mode for Forge game has crached. With some error

**Comment by Geeeeri** [comment]
Version? 1.15+ not compatible.

**Comment by TheECanyon** [comment]
This bug happens with version 1.15.2 HD U G1 pre2

**Comment by Geeeeri** [comment]
It's simply not yet compatible.

**Comment by TheECanyon** [comment]
> It's simply not yet compatible.

Well, the mod shouldnt do anything different from the installer right? Anyways, its good to keep this list up to date.

**Comment by sp614x** [comment]
OptiFine is not compatible with Forge yet.
