### ISSUE TITLE
Visual issues in caves

### ISSUE THREAD

**Issue by Sydcrafter** [sp614x/optifine#3357]
Happened only few times mostly while below sea level.

1. While preparing farm around the spawner, placing glass panes around made a visual glitch (stripes of different colours all around the screen) while looking at the placed pane. If out of view world would come back to normal.

2. Exactly the same glitch. Making trenches around slime farms (already filled with 14 spawning platforms from from Y:6 to Y:30). Just removing blocks glitched the game. All insta-mined with haste 2 beacon.

**Comment by sp614x** [comment]
Which version?

**Comment by Sydcrafter** [comment]
My bad. The 1.15 preview you just released. I never used github. Literally just made an account to let you know about the glitch. Optifine for the win bro 👊🏼

**Comment by sp614x** [comment]
Should be fixed in pre3.

**Comment by Sydcrafter** [comment]
No rush man, Optifine’s epic. I just wanna give as much feedback as I can. Any more issues I notice with newer pre releases I’ll let you know here. Thank you for replies!
