### ISSUE TITLE
1.15.2 Beta

### ISSUE THREAD

**Issue by AngelKotik** [sp614x/optifine#3360]
https://imgur.com/T3qsX26
https://imgur.com/Eugave1

**Comment by AngelKotik** [comment]
it can be fixed by F3+A(reload chunks)

**Comment by AngelKotik** [comment]
https://www.youtube.com/watch?v=pWSlWQgS7gk

**Comment by franiscoder** [comment]
https://github.com/sp614x/optifine/issues/3311 

this is similar to this issue

**Comment by sp614x** [comment]
Should be fixed in pre3.
