### ISSUE TITLE
Ugly Lighting

### ISSUE THREAD

**Issue by blakedj012** [sp614x/optifine#3361]
Hello i have problems with optifine and the lightning.

Without Optifine

https://gyazo.com/d5816488619f401042dd90dedf2a6be7
https://gyazo.com/fb35906acbf35cc3397b29fce180bd8a

With Optifine

https://gyazo.com/505572ceac654035341cce3f9c2fe3cf
https://gyazo.com/b25b350c0a8ce4f96d42c63e3d7294e0

**Comment by ZtereoHYPE** [comment]
I’ve got the same issue. It seems to happen only in darker areas. There, it mixes smooth and old lighting (or it seems to) creating that effect

**Comment by sp614x** [comment]
OptiFine version?

**Comment by blakedj012** [comment]
its the same in all version i have tested OptiFine 1.12.2 HD U F5 and OptiFine 1.12.2 HD U F6 pre1

**Comment by ZtereoHYPE** [comment]
It happens to me in 1.15.2 pre 2

**Comment by Arenovas** [comment]
This is actually just a vanilla bug, but maybe whatever version of Optifine you're using accentuates it even more. Said bug can be seen in MC-71767 and MC-148689

**Comment by blakedj012** [comment]
It could be anything. Still, it's nicer without Optifine than with. And I don't think that's the point

**Comment by blakedj012** [comment]
Are you still fixing the bug for 1.12.2 or does it no longer have priority for you?

**Comment by EminGT** [comment]
I can confirm that this isn't a vanilla bug and is a problem with Optifine's 1.15.2 preview versions.

**Comment by blakedj012** [comment]
And 1.12.2

**Comment by blakedj012** [comment]
And does anything else happen here? What are the details needed? It's all said or not?

**Comment by blakedj012** [comment]
What is the current status? Will this be fixed or not?

**Comment by yezhiyi9670** [comment]
The issue still exists in pre13.

**Comment by naeqirelle2020** [comment]
can confirm still appears in latest preview (Pre-23

**Comment by blakedj012** [comment]
months later and no answer.....

**Comment by blakedj012** [comment]
Can you make a option to deactivate this part for lightning?

**Comment by KaiAF** [comment]
Is this still an issue on the latest 1.15 version?

**Comment by blakedj012** [comment]
its still present

**Comment by KaiAF** [comment]
could you send a F3 debug menu screenshot?

**Comment by blakedj012** [comment]
Its the same like here: https://github.com/sp614x/optifine/issues/5643#issuecomment-845095755

**Comment by KaiAF** [comment]
ok.Closing this as it's a duplicate and the other one is already labeled as a bug.
