### ISSUE TITLE
[1.15.2]Nether fog can't be removed completely

### ISSUE THREAD

**Issue by oOLegendOo** [sp614x/optifine#3366]
This bug exists in all optifine 1.15.2 pre.
Here is Minecraft 1.14.4 with optifine in the nether(Fog:off)
![2020-02-18_12 48 31](https://user-images.githubusercontent.com/44722752/74704982-3f871c00-524d-11ea-8340-85a296471d08.png)

And Minecraft 1.15.2 with optifine in the nether(Fog:off)
![2020-02-18_12 40 26](https://user-images.githubusercontent.com/44722752/74705005-57f73680-524d-11ea-9702-73c585ecd8a2.png)

**Comment by ZtereoHYPE** [comment]
Not only can’t it be removed, but the fog in the nether is WAY closed than the one in the overworld, with same render distance and settings. With render distance set to 8, the one in the nether almost seems like 2 chunks.

**Comment by sp614x** [comment]
Fixed, coming in next preview
