### ISSUE TITLE
[1.15.2 pre3] Chunk Reloads are broken

### ISSUE THREAD

**Issue by RinAndShizuka** [sp614x/optifine#3367]
changing the graphics settings unloads every chunk, until a blockupdate happens in every chunk

**Comment by RinAndShizuka** [comment]
this generally happens with anything chunk update related

**Comment by sp614x** [comment]
Single-player or multiplayer?

**Comment by RinAndShizuka** [comment]
I've observed this in single player, have not tested multiplayer yet, i shall do this now

**Comment by RinAndShizuka** [comment]
I also believe this is related to lighting in [#3368](https://github.com/sp614x/optifine/issues/3368) as updating a chunk fixes lighting and updates lava flowing, this does also not occur in multiplayer.

Multiplayer chunk updates function normally.

**Comment by RinAndShizuka** [comment]
Fixed in pre 4
