### ISSUE TITLE
CIT Enchantments not applying on CIT armor/elytra

### ISSUE THREAD

**Issue by steve6472** [sp614x/optifine#337]

**Comment by sp614x** [comment]
Example?

**Comment by steve6472** [comment]
![elytra bug](https://cloud.githubusercontent.com/assets/20379161/20497161/69d126b0-b028-11e6-9b6b-8a6bedc924b4.png)
And also custom elytra isn't visible on armor stand.

**Comment by EskiMojo14** [comment]
Also experiencing this issue. Any chance of a fix? :)

**Comment by sp614x** [comment]
Fixed, coming in next preview.

**Comment by sp614x** [comment]
OptiFine B7 for 1.11.2 is updated.
- fixed CIT for elytra on armor stand.
