### ISSUE TITLE
Custom Lightmap applies too for the user interface (1.15.2 pre1/2/3)

### ISSUE THREAD

**Issue by ItsRodrigoAl** [sp614x/optifine#3370]
I have a custom lightmap on my resource pack and everything looked to working fine as any optifine version, until the sunset. 

Then I realized the text, items, blocks, everything on the user interface was using the same lightmap color of the texture pack. This happens on the text of the settings buttons, on the hot bar items, basically all the user interface, bu not for the user interface files as inventory.png.

Also as I said, this only happens on night, at day the lightmap works normally

![2020-02-13_19 42 58](https://user-images.githubusercontent.com/57012631/74714826-b991b380-5201-11ea-8490-04eaa532ae94.png)
![2020-02-13_19 42 50](https://user-images.githubusercontent.com/57012631/74714836-be566780-5201-11ea-8782-62e15396463b.png)

**Comment by sp614x** [comment]
Should be working in latest preview.

![image](https://user-images.githubusercontent.com/16635441/74832812-7118e980-5318-11ea-9d6a-58ceace41712.png)

**Comment by sp614x** [comment]
Resource pack link?

**Comment by schrodingerspsycho** [comment]
[lightmap.zip](https://github.com/sp614x/optifine/files/4226628/lightmap.zip)
here is sample lightmaps - issue very noticeable when it rains (even in daytime) or at night

**Comment by JustCylon** [comment]
This is likely related to the introduction of the gui_light model property in 1.15.2

**Comment by sp614x** [comment]
Managed to reproduce it in thunderstorm.
Only items, blocks and text are affected, the GUI itself (menus, buttons) is not affected.

**Comment by sp614x** [comment]
Vanilla also uses the lightmap when rendering text, items and blocks in the GUI. It uses maximum block and sky light for this. The difference is that the vanilla lightmap is always using white color for maximum block/sky light.

**Comment by sp614x** [comment]
OptiFine can fix this by forcing the max block/sky light to be always white independent of the custom lightmap.

**Comment by schrodingerspsycho** [comment]
How It'll affect visuals in game?

**Comment by schrodingerspsycho** [comment]
So, it'll only noticeable if custom lightmap uses darker color for daytime?

**Comment by sp614x** [comment]
Only the combination 15 block + 15 sky would be affected. 
Block light 15 is pretty rare, only some light emiting blocks (glowstone, redstone lamp) render at 15. They would have a problem when having direct sky light (15).

**Comment by schrodingerspsycho** [comment]
What about a Jack o'Lantern? AFAIK it has 15lvl on front face and 13 on others.

**Comment by sp614x** [comment]
Fixed by disabling the custom lightmap when rendering the GUI.
Coming in next preview.
