### ISSUE TITLE
The inside texture of beacons doesn't render

### ISSUE THREAD

**Issue by AppleAuthority** [sp614x/optifine#3372]
When you go inside a beacon the inside texture doesn't render.
[video](https://youtu.be/n63yKbI0uqc)

Using OptiFine 1.15.2pre3

**Comment by sp614x** [comment]
This is a vanilla feature:

![image](https://user-images.githubusercontent.com/16635441/74735430-fd5fd980-5250-11ea-964b-fe94a82b4bc4.png)
