### ISSUE TITLE
1.15.2 pre3 Very-minor Visual Glitch

### ISSUE THREAD

**Issue by KevUndead** [sp614x/optifine#3374]
I know pre4 is out, I don't know if this is fixed in it or not but I'll be updating to it soon enough.
Figured I'd post this in case it's in that version as well.

https://puu.sh/FbZYw/c131ba06ed.gif

Like I said it's VERY minor, almost didn't notice it.

**Comment by thegamerx1** [comment]
yeah also saw that on chunks that coulnt render was like having xray

**Comment by KevUndead** [comment]
This is a bit different from that. I experienced that glitch in pre2, this one however is just a lingering little one that appeared in the middle of nowhere. The original one happened any time a block was placed/broken.

**Comment by sp614x** [comment]
Does it happen with pre4?
Can it be reproduced reliably?

**Comment by sp614x** [comment]
Fixed in next preview.
