### ISSUE TITLE
can anyone identify this issue

### ISSUE THREAD

**Issue by carlucci9660** [sp614x/optifine#3375]
Get a crash, when im in ocean i move through a temple block i removed with pickaxe then i get the crash

[crash-2020-02-18_17.48.47-client.txt](https://github.com/sp614x/optifine/files/4222207/crash-2020-02-18_17.48.47-client.txt)
[crash-2020-02-18_17.45.44-client.txt](https://github.com/sp614x/optifine/files/4222208/crash-2020-02-18_17.45.44-client.txt)

**Comment by sp614x** [comment]
at **com.buuz135.industrial.proxy.client.event.IFClientEvents.blockOverlayEvent**(IFClientEvents.java:76) ~[?:2.1.2] {re:classloading}

Something in Industrial Foregoing
