### ISSUE TITLE
[1.15 Preview 4] Fullscreen Mode Slider registering clicks outside the bar

### ISSUE THREAD

**Issue by Naeqirelle** [sp614x/optifine#3376]
If you click on the slider and then click anywhere outside the slider it'll still register that you clicked on the slider

![Untitled](https://user-images.githubusercontent.com/59464369/74804136-435f8080-52d7-11ea-91c1-95597f7866dd.png)

**Comment by RinAndShizuka** [comment]
I can confirm this happens with every slider, not just Fullscreen Mode.

**Comment by sp614x** [comment]
Fixed, coming in next preview.
