### ISSUE TITLE
[Suggestion] Add a crab to the code

### ISSUE THREAD

**Issue by Naeqirelle** [sp614x/optifine#3378]
Add a crab somewhere in the code please 🦀

also provide proof please? :)

**Comment by HiItsDevin** [comment]
🦀 crab in the code 🦀

**Comment by realjackasterisk** [comment]
🦀

**Comment by asbyth** [comment]
just a small little 
// 🦀

please

**Comment by justForDaCrab** [comment]
Dont get mad at them sp, Just a small crab in the code... Pls pls pls!

**Comment by ZtereoHYPE** [comment]
I don’t know if I should take this as a revolution from the OF server or just an innocent joke.

**Comment by sp614x** [comment]
Added crab to the code:
![image](https://user-images.githubusercontent.com/16635441/74820704-c0541f80-5302-11ea-84ce-2c4a3fce6ffc.png)
Too bad that the IDE doesn't support unicode.
Will be adding bugs instead, they are fully supported.

Further requests for similar features would probably lead to banned users.

**Comment by Cubxity** [comment]
@sp614x which IDE are you using?
