### ISSUE TITLE
Minecarts lag on powered rail

### ISSUE THREAD

**Issue by ghost** [sp614x/optifine#3379]

**Comment by sp614x** [comment]
What exactly is the problem?
Detailed description with screenshot/examples would be nice.

**Comment by XxASxX** [comment]
Same here when I sit on minecarts and go down ....there is a tremendous lag...it stops suddenly then again it starts

**Comment by KaiAF** [comment]
Closing as this is an invalid report if you are still having this issue, create a new valid report, please.
