### ISSUE TITLE
New option: Screenshot Resolution

### ISSUE THREAD

**Issue by Jerozgen** [sp614x/optifine#338]
I suggest you to make new option: "Screenshot Quality".
It increases screenshot resolution to make quality screenshots.
![screenshot-quality](https://cloud.githubusercontent.com/assets/17567951/20457990/7234ae38-aea9-11e6-9432-5bdda0a16173.jpg)

**Comment by Brottweiler** [comment]
Related, to an extent: [VoxelCam](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1292077-1-7-10-liteloader-voxelcam-minecraft-screenshot) mod.

**Comment by sp614x** [comment]
The screenshot size should be limited to something like 4x to avoid crashing due to not enough memory.
For example:
 - 1x = 1680 x 1050 (screen size)
 - 2x = 3360 x 2100
 - 3x = 5040 x 3150
 - 4x = 6720 x 4200

**Comment by Jerozgen** [comment]
> The screenshot size should be limited to something like 4x to avoid crashing due to not enough memory.

I suggest you to add the warning massage about this to the description of Screenshot Quality.

**Comment by sp614x** [comment]
Added option Screenshot Size to preview B2.
Range is 1x (default) to 4x.
