### ISSUE TITLE
[1.15.2-G1-pre4]Can't see entities clearly at a distance

### ISSUE THREAD

**Issue by oOLegendOo** [sp614x/optifine#3381]
![2020-02-19_22 42 51](https://user-images.githubusercontent.com/44722752/74844935-31c6b900-5369-11ea-8601-1ff026d21c53.png)
![2020-02-19_22 45 11](https://user-images.githubusercontent.com/44722752/74845137-8407da00-5369-11ea-9f7b-8667dfd91a40.png)
![2020-02-19_22 47 00](https://user-images.githubusercontent.com/44722752/74845375-e3fe8080-5369-11ea-91ab-4df098a8138d.png)
As shown in the pictures I can't see slime in the overworld,zombie pigman in the nether,and ender dragon in the end clearly
I guess it is a bug about fog,and this bug usually exists when player in high Y seeing entities in low Y

**Comment by sp614x** [comment]
Fixed, coming in pre5.
