### ISSUE TITLE
optifine [1.15.2-G1-pre4]chunks loading is super slow

### ISSUE THREAD

**Issue by Abdelrhman1512** [sp614x/optifine#3383]
i didn't open this preview on singleplayer yet but chunks loading is super slow when i open servers such as hypixel or mineplex thanks!
![2020-02-15_13 28 06](https://user-images.githubusercontent.com/61243312/74853712-f7e4bb00-5346-11ea-879b-cc40975b5c94.png)

**Comment by sp614x** [comment]
Should be fixed in pre5.
