### ISSUE TITLE
[1.15, pre1-21] Cape Stuttering

### ISSUE THREAD

**Issue by asbyth** [sp614x/optifine#3384]
When flying and moving side to side, cape stutters when moving. Not much of a problem, just annoying

**Comment by asbyth** [comment]
Decided I'd be at least somewhat useful & provide a gif of what's happening.
![stutter](https://user-images.githubusercontent.com/36578995/83922764-e933df80-a74e-11ea-81cd-8e27b2274316.gif)

**Comment by sp614x** [comment]
Fixed in pre22.

**Comment by defracted** [comment]
Fun fact: this bug was reported to Mojang back in April of 2018 -> [MC-127749](https://bugs.mojang.com/browse/MC-127749).
Huge thanks to sp614x for fixing that, it was kinda annoying bug...
