### ISSUE TITLE
Chunks don't load after you change Render Distance

### ISSUE THREAD

**Issue by Ivaannn** [sp614x/optifine#3385]
![2020-02-13_20 38 25](https://user-images.githubusercontent.com/61246545/74860078-578f9600-5348-11ea-98ef-197e171616a1.png)
Hello, there's a problem on the mod. If you change the Render Distance to whatever, the chunks don't load anymore, even if you reload all chunks, they don't load.
Your Welcome!

**Comment by sp614x** [comment]
Version?

**Comment by Ivaannn** [comment]
The latest 1.15.2 optifine pre5

**Comment by thepatriotfox** [comment]
same issue

**Comment by zakattac** [comment]
similar issue.
![2020-02-21_12 55 51](https://user-images.githubusercontent.com/23201762/75058866-d51ee780-54a9-11ea-8b95-d9c773deb91e.png)

**Comment by sp614x** [comment]
Should be working in latest preview.
