### ISSUE TITLE
[CEM] Sheep wool model is not working 1.15.2 pre-5

### ISSUE THREAD

**Issue by DragendGhast** [sp614x/optifine#3386]
![2020-02-19_13 21 22](https://user-images.githubusercontent.com/49409042/74863215-82172a00-531b-11ea-9ee3-dcb8104a2d74.png)

**Comment by sp614x** [comment]
Some other CEM models are also broken, to be fixed.

**Comment by sp614x** [comment]
Fixed in pre19.
