### ISSUE TITLE
The terrestria-1.2.1+build.29 crash with Pre5

### ISSUE THREAD

**Issue by walkeraguilar** [sp614x/optifine#3387]
I have this message when i try run the mod terrestria-1.2.1+build.29 with Pre5. Worked fine with Pre4.

The game crashed whilst initializing game
Error: java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.class_4722

**Comment by sp614x** [comment]
OptiFine pre5 is not compatible with Forge or other mods.
