### ISSUE TITLE
[CEM] Horse, Donkey, and Mule baby models are missing their legs. (still broken in 1.15.2 pre-5)

### ISSUE THREAD

**Issue by DragendGhast** [sp614x/optifine#3389]
In the changelog for 1.15.2_HD_U_G1_pre5 it says this was fixed but I don't see a change in-game.
![2020-02-19_14 03 03](https://user-images.githubusercontent.com/49409042/74866400-d4a71500-5320-11ea-86e2-238ba187d4e9.png)

**Comment by sp614x** [comment]
The 1.15 horse model has separate model parts for baby horse legs: "child_back_left_leg", "child_back_right_leg", "child_front_left_leg", "child_front_right_leg".
The documentation is not updated yet.

**Comment by sp614x** [comment]
Updated docs:
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/cem_model.txt#L53

**Comment by DragendGhast** [comment]
Ah gotcha, thanks!
