### ISSUE TITLE
1.11 Vanilla Worlds not showing with optifine 1.11 A1

### ISSUE THREAD

**Issue by SteamPunkNation** [sp614x/optifine#339]
In Title!
![saves](https://cloud.githubusercontent.com/assets/23602136/20459887/00dd432a-aea0-11e6-80ee-393af376e16c.PNG)
![2016-11-19_21 23 53](https://cloud.githubusercontent.com/assets/23602136/20459910/b2d43822-aea0-11e6-8730-e58bb6a020a3.png)

**Comment by sp614x** [comment]
Your OptiFine profile is probably configured to use a custom folder.
Go to "Options -> Resource Packs" and click "Open resource pack folder" then check if the folder is under "Appdata/Roaming/.minecraft".
