### ISSUE TITLE
1.15.2 Slow mouse movement

### ISSUE THREAD

**Issue by thegamerx1** [sp614x/optifine#3390]
I get some weird movement when moving the mouse doesnt happen in vanilla also doesnt seem to happen on servers. Its like the erratic movement on 1.12.2 but instead of it moving fast it moves slow

happens on pre2 and pre4

**Comment by Naeqirelle** [comment]
That is called Negative Acceleration i think

**Comment by thegamerx1** [comment]
looks fixed havent seen this anymore on newer previews
