### ISSUE TITLE
Invisible blocks

### ISSUE THREAD

**Issue by linkmain04** [sp614x/optifine#3393]
Basically, all entities load perfectly but blocks are just invisible, u can break them but they have no textures. But, if u refresh a single chunk, it will seem perfect. Btw, F3+A do nothing.
**PD:** sorry if my english isn't nice, its not my native language. And I'm now at progamming so sorry if i dont use the correct words.

**Comment by sp614x** [comment]
Which OptiFine version?

**Comment by SiskooPOG** [comment]
Happens to me on pre9. I do not know how to reproduce the issue, textures will begin loading after a few minutes (or never) and switching ressource packs gets frozen at about the middle of the progress bar if done while the textures are invisible.

**Comment by KaiAF** [comment]
Could be related to #5195? Are you still having this issue? @linkmain04

**Comment by KaiAF** [comment]
Assume it's resolved now.
