### ISSUE TITLE
Invisible Blocks

### ISSUE THREAD

**Issue by troleroz312** [sp614x/optifine#3394]
Hello, in the last update of optifine the OptiFine version 1.15.2_HD_U_G1_pre5, I had a mistake a friend and I while playing from one moment to another the blocks stopped being seen and they didn't load the chunks basically it was as if all the textures had been erased , which seemed odd since we have bunos components we do not need ram or anything like that, but we could not see the textures of the blocks we tried everything but we did not leave so we had to use the common mc, please if possible I would like who will report this error, Thank you for your attention keep it up

**Comment by sp614x** [comment]
Should work in latest preview.
