### ISSUE TITLE
cape optifine

### ISSUE THREAD

**Issue by hereieiint** [sp614x/optifine#3396]
Hello everyone I would like to know if it is possible to have a current OF cape, and another deactivated, but on the same account. Because I fear losing my cape for life if I do this. So if you haven't understood, I'm looking to put a cape aside on my account while having an active cape :)
PS: I know it will work but my question is: Will it really keep or delete it?

**Comment by sp614x** [comment]
There is only one cape per account and it can be active or inactive.
