### ISSUE TITLE
[1.15.2, pre5] Overlay CTM doesn't work in some chunks

### ISSUE THREAD

**Issue by sixfootblue** [sp614x/optifine#3398]
Overlay methods don't seem to be working in random cubic chunks. 

![image](https://user-images.githubusercontent.com/22923471/74962192-6f652980-53dd-11ea-8ab5-015d2bf776d3.png)

Sample resource pack:
[1.15.2 CTM Overlay Issue.zip](https://github.com/sp614x/optifine/files/4232170/1.15.2.CTM.Overlay.Issue.zip)

**Comment by sp614x** [comment]
Fixed, coming in pre7.
