### ISSUE TITLE
[1.15.2, pre6] Shadows on blocks with light lvl15

### ISSUE THREAD

**Issue by schrodingerspsycho** [sp614x/optifine#3399]
Blocks with block light lvl 15 cast off shadows, as seen on those screenshots. Torch, which is 14lvl doesn;t cast a shadow while jack-o-lantern and glowstone does.
https://imgur.com/a/ycXMmZj
Vanilla resource pack, no mods, only optifine.

**Comment by sp614x** [comment]
This is a vanilla problem.

![image](https://user-images.githubusercontent.com/16635441/75055711-d6660980-54d5-11ea-9f5b-f7f9820e2a9c.png)
