### ISSUE TITLE
Option to disable entity shadows in shaders.properties?

### ISSUE THREAD

**Issue by DeDelner** [sp614x/optifine#340]
Title says it all.

**Comment by sp614x** [comment]
The entity shadows are automatically disabled when a shadow buffer is used.

**Comment by DeDelner** [comment]
Hmm. But however, they come back in gbuffers_spidereyes. Especially when I try to modify the lightmaps for it.

**Comment by sp614x** [comment]
The vanilla shadows (round, on the block below the entity) are disabled when a shaders shadow buffer is used. 
The method Render.renderShadow() checks Shaders.shouldSkipDefaultShadow before rendering the vanilla shadow.

**Comment by DeDelner** [comment]
Ah whoops, stupid me. I didn't realized that I was talking for the dimension world1 and yeah.. there wasn't a shadow buffer.

All good. Issue can be closed.
