### ISSUE TITLE
1.15.2 HD U G1 pre6 Raid Outlines Not Showing

### ISSUE THREAD

**Issue by chunkymonekty** [sp614x/optifine#3400]
When you ring a bell during a village raid the outlines of the raiders are not shown at all. Works fine in vanilla but not in optifine 1.15.2 HD U G1 pre6.

**Comment by asbyth** [comment]
turn off fast render

**Comment by chunkymonekty** [comment]
> turn off fast render

Thanks, I should have checked that.
