### ISSUE TITLE
[1.15.2 pre 6] Elytra flying can cause character model to blink in and out of view

### ISSUE THREAD

**Issue by RinAndShizuka** [sp614x/optifine#3402]
Not observable all the time, but flying with an elytra and a rocket can cause your model to blink in and out of view. happens every so often.

**Comment by asbyth** [comment]
This is a vanilla bug, something I believe Forge previously/current has a patch for though

**Comment by RinAndShizuka** [comment]
Ahh thank you, never mind then i shall close this issue
