### ISSUE TITLE
[1.12.2] NVIDIA OpenGL Driver

### ISSUE THREAD

**Issue by poqdavid** [sp614x/optifine#3404]
Everything else is fine and sometimes randomly this happens and crashes my video driver
I use BSL for shader

```
An application has requested more GPU memory than is
available in the system.
The application will now be closed.


Error code: 6
 (pid=33648 tid=14524 javaw.exe 64bit)
```
Also i have a RTX 2070 with 8GB ram

**Comment by sp614x** [comment]
Probably due to a very big resource pack?
