### ISSUE TITLE
Overlay CTM from custom texture pack not working

### ISSUE THREAD

**Issue by Valzion** [sp614x/optifine#3405]
I have had a custom CTM overlay texture pack for a while and now when upgrading to 1.15.2 pre 6 it does not work.

[ValzionYT texture pack.zip](https://github.com/sp614x/optifine/files/4233547/ValzionYT.texture.pack.zip)

**Comment by sp614x** [comment]
Fixed, coming in pre7.

![image](https://user-images.githubusercontent.com/16635441/75035902-de5f8280-54b0-11ea-9294-df9b02812036.png)
