### ISSUE TITLE
Shaders Button Disabled

### ISSUE THREAD

**Issue by ZarinPeace** [sp614x/optifine#3406]
The Shaders Button in 1.15.2 HD U G1 pre6 is disabled.

![image](https://user-images.githubusercontent.com/61303197/75002030-250d9800-5431-11ea-8bfc-6783428c392e.png)

**Comment by asbyth** [comment]
here's 3 possible reasons why

![image](https://user-images.githubusercontent.com/36578995/75002060-3ce51c00-5431-11ea-996e-5011d0498a07.png)
![image](https://user-images.githubusercontent.com/36578995/75002076-48d0de00-5431-11ea-91e6-bf78961c05dd.png)
![image](https://user-images.githubusercontent.com/36578995/75002098-54bca000-5431-11ea-8b05-b2c35da403e2.png)

**Comment by ZarinPeace** [comment]
I see, Thx
