### ISSUE TITLE
Glass pane texture glitch

### ISSUE THREAD

**Issue by Wolfy02** [sp614x/optifine#3408]
Seen below, glass panes have a weird orange line between panes when viewed from most angles.
![2020-02-21_19 19 56](https://user-images.githubusercontent.com/61309999/75016492-37dea600-54df-11ea-9623-63a849cf45b7.png)

**Comment by sp614x** [comment]
Resource pack?

**Comment by Naeqirelle** [comment]
![2020-02-21_13 11 28](https://user-images.githubusercontent.com/59464369/75037286-b6b9eb80-54ab-11ea-9b42-85dc3fbbd035.png)

able to reproduce on Dokucraft High

**Comment by sp614x** [comment]
Fixed, coming in pre7.

**Comment by Wolfy02** [comment]
> Resource pack?

Yes, I am using a resource pack, didn't think about that. Will be using optifine and this pack together though, so will this be fixed in the full release? Didn't happen in the pack before I installed Optifine.

**Comment by Wolfy02** [comment]
> Fixed, coming in pre7.

Awesome! Thanks so much. Can't wait for the Optifine full realise with shaders and all!
