### ISSUE TITLE
[1.15.2 pre6] World generation/loading buggy

### ISSUE THREAD

**Issue by AthosBenther** [sp614x/optifine#3410]
Right off the bat the first time running it the game would not load a pregenerated chunk. CLosing then opening solved the issue.

But now I went exploring and new chunks are not being generated. I tried to continue into the void and feel off the map.

All settings are maxed out

Reloading the save in vanilla created the chunks.

i7 8th 16gb GTX1050TI, game running on an SSD.

Any log file i should send?

Save files: https://we.tl/t-VmZLze6duc

**Comment by sp614x** [comment]
Works for me.
I went flying 1km in the direction of the jungle that is visible from the stone tower. The chunks were most probably not explored and the world was generating fine.
![image](https://user-images.githubusercontent.com/16635441/75035106-02ba5f80-54af-11ea-913b-38840b7a05e9.png)

**Comment by AthosBenther** [comment]
Thanks for the fast response!

Upon further probing I realized the issue occurs while using large distance rendering. 64 chunks causes the issue. 32 doesn't.

If the issue happens and I go down to 2 chunks, get a little far so the chunk is forced to unload and reload again the issue is solved and I can go back to 32 chunks for stability. If I go above 55 the issue sure will happen again
