### ISSUE TITLE
When sitting, game crashes (pre7)

### ISSUE THREAD

**Issue by Eden333** [sp614x/optifine#3413]
Either on a horse, or with plugins sitting on carpet/stairs will result in a crash with pre7.

**Comment by Naeqirelle** [comment]
![2020-02-21_22 23 37](https://user-images.githubusercontent.com/59464369/75076754-e3e0bb00-54f8-11ea-8ff6-fe1b2462e17d.png)

can't confirm

**Comment by asbyth** [comment]
actual crash report/log would be useful

**Comment by Eden333** [comment]
[crash-2020-02-21_19.45.37-client.txt](https://github.com/sp614x/optifine/files/4238346/crash-2020-02-21_19.45.37-client.txt)
[crash-2020-02-21_19.48.23-client.txt](https://github.com/sp614x/optifine/files/4238347/crash-2020-02-21_19.48.23-client.txt)
[crash-2020-02-21_22.14.58-client.txt](https://github.com/sp614x/optifine/files/4238348/crash-2020-02-21_22.14.58-client.txt)

**Comment by asbyth** [comment]
ah, dupe of #3412

**Comment by sp614x** [comment]
Fixed, coming in pre8.
