### ISSUE TITLE
shaders not working at all

### ISSUE THREAD

**Issue by WolfieBiomech** [sp614x/optifine#3416]
the shaders option is not letting me click on it or use it at all and it is getting really annoying. I would like to use my shaders for 1.15 versions of Minecraft but the option isn't working. please help

**Comment by asbyth** [comment]
ahhhhhhhhh read changelogs before installing something/updating they're not enabled for now

**Comment by WolfieBiomech** [comment]
aw man

**Comment by HiItsDevin** [comment]
On the preview changelog
![](https://hiitsdevin.dev/no.png)
