### ISSUE TITLE
[1.15.2 pre-7] Sky and Fog colormaps don't work fully. (stuck on plains)

### ISSUE THREAD

**Issue by sixfootblue** [sp614x/optifine#3418]
The custom colormaps for sky, fog, and underwater fog don't seem to be working fully. Both grid and vanilla formats detect custom colors and change correctly according to height, but they don't detect the biome. The colors only stay on what was set for the plains biome.

Example resource pack: 
[Sky and Fog Colormap Issue.zip](https://github.com/sp614x/optifine/files/4238860/Sky.and.Fog.Colormap.Issue.zip)

**Comment by sp614x** [comment]
Fixed, coming in pre8.
