### ISSUE TITLE
Need a LUT in shaders

### ISSUE THREAD

**Issue by dotModded** [sp614x/optifine#342]
Can you add this as a uniform sampler please, its a LUT for a color curve http://filmicgames.com/Downloads/FilmicTonemapping/FilmLut.tga.

**Comment by Strum355** [comment]
+1

**Comment by DatWeirdPerson** [comment]
+1

**Comment by sp614x** [comment]
Should it be exactly this image or should it come with the shader pack?
Isn't it possible to compute it at run time?

**Comment by dotModded** [comment]
Well if you could allow images to be loaded from the shader that would be ideal, however just this image is fine, however it would be far more computationally more expensive to compute this

**Comment by sp614x** [comment]
Updated preview B7 for 1.11.2.
Added support for custom textures: https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.properties#L46
