### ISSUE TITLE
[1.15.2] CIT custom 3D textures not working.

### ISSUE THREAD

**Issue by Fixoroz** [sp614x/optifine#3420]
![image](https://user-images.githubusercontent.com/61342910/75087843-5f248a00-5556-11ea-9858-78a914e5f53b.png)
![2020-02-22_09 33 18](https://user-images.githubusercontent.com/61342910/75087847-6fd50000-5556-11ea-9fc9-7170e84ea264.png)
![image](https://user-images.githubusercontent.com/61342910/75087851-7bc0c200-5556-11ea-9ed4-8eec40855ceb.png)

**Comment by sp614x** [comment]
Also for items in item frames.

**Comment by sp614x** [comment]
Fixed, coming in pre20.
