### ISSUE TITLE
[1.15.2 PRE-7] Dynamic Lighting - Player not illuminated, but surrounding mobs are.

### ISSUE THREAD

**Issue by HiItsDevin** [sp614x/optifine#3421]
Reporting for playing "Len" on Discord

Have `Dynamic Lighting` on, go into a dark area with mobs, shoot a flaming arrow, and go into F5. The surrounding area and mob will be illuminated, but the player itself isn't.

![](https://i.hiitsdevin.dev/captures/hiitsdevin_new_281156.png)
![](https://i.hiitsdevin.dev/captures/hiitsdevin_new_336470.png)

**Comment by HiItsDevin** [comment]
So now, according to Len, the players around you are also illuminated, but not your player on your side.

**Comment by sp614x** [comment]
Fixed, coming in pre8.
