### ISSUE TITLE
[1.15.2 pre-7] CEM elements don't animate or apply custom textures

### ISSUE THREAD

**Issue by sixfootblue** [sp614x/optifine#3422]
Apologies in advance if this post is redundant.

It looks like all CEM is having this issue; not just select entities. CEM elements/models don't play custom animations, and also don't use any specified custom textures. They all default to using the same texture as the original entity they're attached to. 

Example pack:
[CEM Elements Issue.zip](https://github.com/sp614x/optifine/files/4238918/CEM.Elements.Issue.zip)

In the pack, pigs should have a pair of green ears and a tail that sways up and down. The new parts' texture is from a separate file. Instead the parts are static, and only use the base pig texture.

**Comment by sp614x** [comment]
Fixed in pre19.
