### ISSUE TITLE
Rain layering breaks when breaking blocks under leaves 

### ISSUE THREAD

**Issue by Dungeneer** [sp614x/optifine#3424]
optifine version - 1.15.2 pre7
gpu - nvidia geforce rtx 2070 super
when breaking non-transparent blocks under leaves rain ignores layering and flashes on the screen for a bit.
video proof: https://www.youtube.com/watch?v=BlV01lcGNTU&feature=youtu.be

**Comment by Trottero** [comment]
This is also a bug in vanilla Minecraft tested in 1.15.2

**Comment by sp614x** [comment]
This is a vanilla bug: "Rain and snow render through blocks when picking up items or experience orbs"
https://bugs.mojang.com/browse/MC-163575
