### ISSUE TITLE
Minecarts Lag

### ISSUE THREAD

**Issue by XxASxX** [sp614x/optifine#3425]
When I sit on minecarts on powered rail and go down there is a lag....it stops in the middle of the track and then again it starts
Next, the wandering Trader is invisible...only the llamas are visible

**Comment by asbyth** [comment]
wandering traders go invisible at night to protect themselves, that's a feature lol

**Comment by ZtereoHYPE** [comment]
As my colleague said, wandering traders becoming invisible at night/when near mobs is a feature. And please, report only one bug per thread. In this case the bug should be the lag when being in powered rails.

**Comment by XxASxX** [comment]
Yeah sorry....my bad....but the minecart one is really bad

**Comment by sp614x** [comment]
Which OptiFine version?

**Comment by XxASxX** [comment]
Ge 3 or 5

**Comment by XxASxX** [comment]
Preview 1.15 he 3

**Comment by XxASxX** [comment]
Actually it's fixed by now....so thanx

**Comment by XxASxX** [comment]
If there is some other bug I encounter ....I'll tell u
