### ISSUE TITLE
Chunk fails to load properly/erases partially

### ISSUE THREAD

**Issue by Boidushya** [sp614x/optifine#3427]
This wasn't happening in the previous version of 1.15.2 optifine and seems new on pre7. But when i loaded up my world in single-player, a part of my iron farm was not there and I was spawned in the next chunk outside the disturbed chunk.  Luckily I had a backup of the world and was able to recover most of it... 
Just wanted to let you know that this is happening.
Cheers.

**Comment by sp614x** [comment]
Is this still happening with latest preview?

**Comment by KaiAF** [comment]
No response from the Author, closing issue.
