### ISSUE TITLE
Clouds appearing through blocks when I enter 3rd person.

### ISSUE THREAD

**Issue by GorpDev** [sp614x/optifine#3428]
https://imgur.com/a/B5qsLKo

**Comment by sp614x** [comment]
OptiFine version?
How does it behave in vanilla?

**Comment by GorpDev** [comment]
OptiFine 1.15.2 HD U G1 pre7 and it doesn't show through blocks in vanilla
when going into 3rd person.

**Comment by sp614x** [comment]
Should be fixed in latest preview.
