### ISSUE TITLE
Crash Issue

### ISSUE THREAD

**Issue by Shayne2010** [sp614x/optifine#343]
Okay hey... i don´t really know what is happening too be honest.. but using HD_U_A3 for 1.11 i get random crashes every once in a while.. but only when using Optifine.
Maybe somebody can take a look at the crash report since i have no clue what´s in this crash report :D
[http://pastebin.com/U9LRXZaF](url)

**Comment by sp614x** [comment]
Can you post the error log?
The real error should be there.

**Comment by RViper80** [comment]
I'm having the same issue with JEI crashing as soon as I open my inventory, and only when using Optifine.  Exact same crash report.   According to the log it looks like it's stumbling when getting/assigning spawn egg colors?

> [13:35:51] [Client thread/INFO]: Setting user: RViper
> [13:35:59] [Client thread/WARN]: Skipping bad option: lastServer:
> [13:35:59] [Client thread/INFO]: LWJGL Version: 2.9.4
> [13:36:00] [Client thread/INFO]: [STDOUT]: ---- Minecraft Crash Report ----
> 
> WARNING: coremods are present:
> Contact their authors BEFORE contacting forge
> 
> // Hi. I'm Minecraft, and I'm a crashaholic.
> 
> Time: 11/18/16 1:36 PM
> Description: Loading screen debug info
> 
> This is just a prompt for computer specs to be printed. THIS IS NOT A ERROR
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.11
> 	Operating System: Windows 7 (amd64) version 6.1
> 	Java Version: 1.8.0_25, Oracle Corporation
> 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
> 	Memory: 99149472 bytes (94 MB) / 339484672 bytes (323 MB) up to 3207856128 bytes (3059 MB)
> 	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
> 	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
> 	FML: 
> 	Loaded coremods (and transformers): 
> 	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.14009 Compatibility Profile Context 21.19.151.3' Renderer: 'AMD Radeon (TM) R7 370 Series'
> [13:36:03] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Crafting Tweaks, FMLFileResourcePack:Gravestone, FMLFileResourcePack:Just Enough Items, FMLFileResourcePack:Mini HUD, FMLFileResourcePack:SlashBlade, Oerlis-RSEdit.zip
> [13:36:05] [Sound Library Loader/INFO]: Starting up SoundSystem...
> [13:36:05] [Thread-9/INFO]: Initializing LWJGL OpenAL
> [13:36:05] [Thread-9/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
> [13:36:05] [Thread-9/INFO]: OpenAL initialized.
> [13:36:05] [Sound Library Loader/INFO]: Sound engine started
> [13:36:10] [Client thread/INFO]: Created: 16x16 textures-atlas
> [13:36:15] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Crafting Tweaks, FMLFileResourcePack:Gravestone, FMLFileResourcePack:Just Enough Items, FMLFileResourcePack:Mini HUD, FMLFileResourcePack:SlashBlade, Oerlis-RSEdit.zip
> [13:36:16] [Client thread/INFO]: SoundSystem shutting down...
> [13:36:16] [Client thread/WARN]: Author: Paul Lamb, www.paulscode.com
> [13:36:16] [Sound Library Loader/INFO]: Starting up SoundSystem...
> [13:36:17] [Thread-11/INFO]: Initializing LWJGL OpenAL
> [13:36:17] [Thread-11/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
> [13:36:17] [Thread-11/INFO]: OpenAL initialized.
> [13:36:17] [Sound Library Loader/INFO]: Sound engine started
> [13:36:21] [Client thread/ERROR]: Using missing texture, unable to load minecraft:textures/soul.png.png, java.io.FileNotFoundException
> [13:36:21] [Client thread/INFO]: Created: 1024x512 textures-atlas
> [13:36:23] [Client thread/WARN]: Skipping bad option: lastServer:
> [13:36:31] [Client thread/INFO]: Connecting to 127.0.0.1, 25565
> [13:36:37] [Client thread/INFO]: [STDERR]: java.lang.reflect.InvocationTargetException
> [13:36:37] [Client thread/INFO]: [STDERR]: 	at sun.reflect.GeneratedMethodAccessor17.invoke(Unknown Source)
> [13:36:37] [Client thread/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [13:36:37] [Client thread/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:483)
> [13:36:37] [Client thread/INFO]: [STDERR]: 	at Reflector.callVoid(Reflector.java:333)
> [13:36:37] [Client thread/INFO]: [STDERR]: 	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1417)
> [13:36:37] [Client thread/INFO]: [STDERR]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1075)
> [13:36:37] [Client thread/INFO]: [STDERR]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:370)
> [13:36:37] [Client thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:124)
> [13:36:37] [Client thread/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> [13:36:37] [Client thread/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> [13:36:37] [Client thread/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [13:36:37] [Client thread/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:483)
> [13:36:37] [Client thread/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> [13:36:37] [Client thread/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> [13:36:37] [Client thread/INFO]: [STDERR]: Caused by: java.lang.NoSuchFieldError: field_191308_b
> [13:36:37] [Client thread/INFO]: [STDERR]: 	at EntityUtils.getEntityClass(EntityUtils.java:42)
> [13:36:37] [Client thread/INFO]: [STDERR]: 	at EntityUtils.getEntityId(EntityUtils.java:21)
> [13:36:37] [Client thread/INFO]: [STDERR]: 	at CustomColors.getSpawnEggColor(CustomColors.java:1609)
> [13:36:37] [Client thread/INFO]: [STDERR]: 	at CustomColors.getColorFromItemStack(CustomColors.java:1638)
> [13:36:37] [Client thread/INFO]: [STDERR]: 	at net.minecraft.client.renderer.RenderItem.func_175032_a(RenderItem.java:293)
> [13:36:37] [Client thread/INFO]: [STDERR]: 	at net.minecraft.client.renderer.RenderItem.func_175045_a(RenderItem.java:162)
> [13:36:37] [Client thread/INFO]: [STDERR]: 	at net.minecraft.client.renderer.RenderItem.func_175036_a(RenderItem.java:134)
> [13:36:37] [Client thread/INFO]: [STDERR]: 	at mezz.jei.gui.ingredients.GuiIngredientFast.renderItemAndEffectIntoGUI(GuiIngredientFast.java:120)
> [13:36:37] [Client thread/INFO]: [STDERR]: 	at mezz.jei.gui.ingredients.GuiIngredientFast.renderItemAndEffectIntoGUI(GuiIngredientFast.java:93)
> [13:36:37] [Client thread/INFO]: [STDERR]: 	at mezz.jei.gui.ingredients.GuiIngredientFastList.render(GuiIngredientFastList.java:164)
> [13:36:37] [Client thread/INFO]: [STDERR]: 	at mezz.jei.gui.ItemListOverlayInternal.drawScreen(ItemListOverlayInternal.java:303)
> [13:36:37] [Client thread/INFO]: [STDERR]: 	at mezz.jei.GuiEventHandler.onDrawBackgroundEventPost(GuiEventHandler.java:88)
> [13:36:37] [Client thread/INFO]: [STDERR]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_100_GuiEventHandler_onDrawBackgroundEventPost_BackgroundDrawnEvent.invoke(.dynamic)
> [13:36:37] [Client thread/INFO]: [STDERR]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
> [13:36:37] [Client thread/INFO]: [STDERR]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
> [13:36:37] [Client thread/INFO]: [STDERR]: 	at net.minecraft.client.gui.GuiScreen.func_146276_q_(GuiScreen.java:581)
> [13:36:37] [Client thread/INFO]: [STDERR]: 	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:73)
> [13:36:37] [Client thread/INFO]: [STDERR]: 	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
> [13:36:37] [Client thread/INFO]: [STDERR]: 	at net.minecraft.client.gui.inventory.GuiInventory.func_73863_a(SourceFile:47)
> [13:36:37] [Client thread/INFO]: [STDERR]: 	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
> [13:36:37] [Client thread/INFO]: [STDERR]: 	... 14 more
> [13:36:38] [Client thread/FATAL]: Unreported exception thrown!
> java.lang.IllegalStateException: Already building!
> 	at net.minecraft.client.renderer.VertexBuffer.func_181668_a(VertexBuffer.java:291) ~[bpw.class:?]
> 	at net.minecraft.client.shader.Framebuffer.func_178038_a(Framebuffer.java:264) ~[bqp.class:?]
> 	at net.minecraft.client.shader.Framebuffer.func_147615_c(Framebuffer.java:229) ~[bqp.class:?]
> 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1102) ~[beq.class:?]
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:370) [beq.class:?]
> 	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
> 	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
>

**Comment by sp614x** [comment]
@RViper80 your crash is different. It is caused by Forge rewriting the entity registry (not backwards compatible). Next OptiFine version will come with a workaround.

**Comment by RViper80** [comment]
Yeah, I can see now the 2nd one I posted is a bit different, and good that it's known what it's from.  But the first log I posted is the fml-client-latest.log counterpart to the crash report I have that is line-for-line, number-for-number, identical to Shayne2010's.  (for comparison, if you'd like http://pastebin.com/uVBTppfh )

**Comment by sp614x** [comment]
The problem is "Exception caught during firing event net.minecraftforge.client.event.GuiScreenEvent$BackgroundDrawnEvent@4c256ed6:
java.lang.NoSuchFieldError: field_191308_b"
Caused by Forge reorganizing the item registry.
Added workaround in preview A4.

**Comment by RViper80** [comment]
That stopped the 'already building' crash for me, thanks :)  Working just fine with JEI now.

**Comment by SilenXo** [comment]
Hey Im having these error when all the mods are load and the game crash after The game crashed whilst unexpected error
Error: java.lang.NoSuchFieldError: field_191308_b
Exit Code: -1
