### ISSUE TITLE
[1.15.2-G1 pre7]Game crash when player is trapped by blocks

### ISSUE THREAD

**Issue by oOLegendOo** [sp614x/optifine#3430]
When player is trapped by blocks it will cause a crash！
[crash-2020-02-22_23.18.11-client.txt](https://github.com/sp614x/optifine/files/4239506/crash-2020-02-22_23.18.11-client.txt)

**Comment by ochetski** [comment]
Maybe it's the same bug, so I will post here. Happens as well while using mine carts in filled corners. you get trapped for a moment.
[crash-2020-02-22_13.28.09-client.txt](https://github.com/sp614x/optifine/files/4239608/crash-2020-02-22_13.28.09-client.txt)

**Comment by Alfred7777** [comment]
I guess I've had same issue. Game crashed twice when I thrown enderpearl into slab in endcity. Happened twice.
[crash-2020-02-22_19.15.32-client.txt](https://github.com/sp614x/optifine/files/4239760/crash-2020-02-22_19.15.32-client.txt)
[crash-2020-02-22_19.19.35-client.txt](https://github.com/sp614x/optifine/files/4239761/crash-2020-02-22_19.19.35-client.txt)

**Comment by sp614x** [comment]
Fixed, coming in pre8.
