### ISSUE TITLE
[1.15.2] Random mob eye textures (enderman, phantom, spider, cave spider) not working

### ISSUE THREAD

**Issue by nemaele** [sp614x/optifine#3431]
They worked perfectly fine in pre4, now they're not working at all. They just show the default purple, green and red.

**Comment by nemaele** [comment]
I formulated this wrong - the alternative textures don't work. I've added multiple (green for endermen, red for phantoms, multiple colours of eyes for spiders.

**Comment by sp614x** [comment]
Duplicate of #3451
