### ISSUE TITLE
Crash on Start "NoSuchMethod"

### ISSUE THREAD

**Issue by TopherLude** [sp614x/optifine#3432]
Could very well be that I've got something wrong with my installation. I've installed it using Forge. With no other mods in the folder, it starts fine. Drop 1.15.2 pre7 in there and it gives this crash report.

[crash-2020-02-22_14.27.18-client.txt](https://github.com/sp614x/optifine/files/4239883/crash-2020-02-22_14.27.18-client.txt)

**Comment by iredmedia** [comment]
Changelogs here:
https://optifine.net/changelog?f=preview_OptiFine_1.15.2_HD_U_G1_pre7.jar

 - not compatible with Forge
(21.02.2020)

Cant wait for the stable release, sp614x your work is highly appreciated!

**Comment by sp614x** [comment]
Not compatible with Forge yet.

**Comment by TopherLude** [comment]
Ah, I knew I was doing something dumb. Sorry for wasting your time.
