### ISSUE TITLE
Optifine (1.15 U1 pre7) crashed

### ISSUE THREAD

**Issue by rbits0** [sp614x/optifine#3434]
I was playing, and it saved and then crashed. Whenever I tried to open that world, it saved, and then crashed. I tried opening another world and it didn't crash. I was able to fix it by loading the world in vanilla minecraft, moving, saving, and then loading it back in optifine.

Crash Log:
[crash-2020-02-23_08.54.42-client.txt](https://github.com/sp614x/optifine/files/4240085/crash-2020-02-23_08.54.42-client.txt)

World File (before I fixed it):
[Survival June 2019.zip](https://drive.google.com/uc?export=download&confirm=IXqK&id=14xQnOHna8bF8z2nV4juuIyOgMhJ-PrIs)

**Comment by asbyth** [comment]
update to pre8, this was fixed
