### ISSUE TITLE
[1.15.2] texture doesn't work

### ISSUE THREAD

**Issue by RedLoreStone** [sp614x/optifine#3435]
I use a texture pack from 1.12 to 1.14 and it works without problem but now in 1.15 the texture doesn't work. I know that optifine isn't complete but I don't now if it's the texture too much old  or it's optifine.

Texture link: https://www.reddit.com/r/Minecraft/comments/681zej/i_made_improved_cow_and_chicken_models_using/

**Comment by Studio528-real** [comment]
what optifine version?

**Comment by RedLoreStone** [comment]
> what optifine optifine 1.15.2 pre-8

**Comment by Studio528-real** [comment]
hmm yea, CEM might still be buggy/not working as intended. is it the texture thta's having the problem or the model?

**Comment by RedLoreStone** [comment]
the texture

**Comment by RedLoreStone** [comment]
> hmm yea, CEM might still be buggy/not working as intended. is it the texture thta's having the problem or the model?

the models are ok. The textures have problem

**Comment by RedLoreStone** [comment]
So what is the problem?

**Comment by sp614x** [comment]
CEM textures were fixed in latest preview.
