### ISSUE TITLE
[1.15.2 PRE 8] Lighting Bug

### ISSUE THREAD

**Issue by supertakeru** [sp614x/optifine#3439]
![2020-02-22_20 24 21](https://user-images.githubusercontent.com/50756584/75104315-c07f4400-55bc-11ea-911d-3c4a47a6c873.png)
![2020-02-22_20 24 22](https://user-images.githubusercontent.com/50756584/75104319-c2e19e00-55bc-11ea-9390-91dd8a3226f3.png)

**Comment by ThePieGuyWill** [comment]
Yea same thing, its really noticeable in dark areas with smooth lighting

**Comment by supertakeru** [comment]
![image](https://user-images.githubusercontent.com/50756584/75105050-60d96680-55c5-11ea-998b-a7c660031497.png)
![image](https://user-images.githubusercontent.com/50756584/75105051-646ced80-55c5-11ea-9a5c-403fe56ae179.png)

**Comment by sp614x** [comment]
Fixed, coming in pre9.
