### ISSUE TITLE
Crash with JustEnoughItems

### ISSUE THREAD

**Issue by oneskres** [sp614x/optifine#344]
When you open the inventory, the game crashes. For me, it only happens when I scroll through some pages. Removing opitfine fixed the crash.

[fml-client-2.log.txt](https://github.com/sp614x/optifine/files/606003/fml-client-2.log.txt)

**Comment by sp614x** [comment]
Duplicate of https://github.com/sp614x/optifine/issues/22.
Fixed in OptiFine D4 for 1.10.2.
