### ISSUE TITLE
Optifine 1.15.2 pre9 is still too lazy to load chunks once in servers.

### ISSUE THREAD

**Issue by NaiNonTH** [sp614x/optifine#3441]
![2020-02-23_17 01 10](https://user-images.githubusercontent.com/61338902/75110258-b1e96900-565e-11ea-82d8-c7a5a9e0113c.png)

![2020-02-23_17 01 50](https://user-images.githubusercontent.com/61338902/75110261-b3b32c80-565e-11ea-8f52-7975e56706fc.png)

**Comment by naeqirelle2020** [comment]
@NaiNonTH is this still an issue in the latest preview?

**Comment by sp614x** [comment]
Duplicate of #3612
