### ISSUE TITLE
bow is not shooting

### ISSUE THREAD

**Issue by XxASxX** [sp614x/optifine#3442]
my infinity bow is not shooting...when i right click with bow it is not aiming instead i am blocking with my shield

**Comment by XxASxX** [comment]
version OptiFine 1.15.2 HD U G1 pre8

**Comment by BBftw** [comment]
Do you have an arrow in your inventory?

**Comment by Brottweiler** [comment]
How did you come to the conclusion that Optifine caused this issue? Did you even try it in vanilla without optifine?

**Comment by XxASxX** [comment]
It had infinity enchantment on it

**Comment by BBftw** [comment]
You still need an arrow in your inventory

**Comment by XxASxX** [comment]
Thank for help.....u have an immense contribution towards Minecraft

**Comment by BBftw** [comment]
god.
