### ISSUE TITLE
Rain doesn't show through stained glass

### ISSUE THREAD

**Issue by chasejsutton49** [sp614x/optifine#3443]
As stated, rain doesn't show through stained glass. According to another issue, it's probably more than rain particles that can't be seen through stained glass. This MIGHT be yet another vanilla bug, though. But I wanted to let y'all know in case not. This is for Optifine 1.15.2 G1 pre9

![2020-02-22_12 30 56](https://user-images.githubusercontent.com/19761194/75114405-4631dc80-561b-11ea-91ab-53deb0242e39.png)
![2020-02-22_12 31 04](https://user-images.githubusercontent.com/19761194/75114409-4a5dfa00-561b-11ea-834e-276af839a17a.png)

**Comment by EminGT** [comment]
Sadly, it's a vanilla bug.

**Comment by sp614x** [comment]
Vanilla bug:
https://bugs.mojang.com/plugins/servlet/mobile#issue/MC-167826
