### ISSUE TITLE
Option to use someone else's cape by username

### ISSUE THREAD

**Issue by MushirMickeyJoe** [sp614x/optifine#3444]
In the cape customization part of OptiFine.net should be an option to enter somebody's username to use that cape. Currently if you see a cool cape in-game, you have to recreate it from scratch, which can be a pain. This feature would make designing a cape a bit easier.

**Comment by cameronos** [comment]
Implemented with recent banner website update - if you were trying to copy a custom-colored OF cape, you can just screenshot and get the hexes manually.

**Comment by Jiingy** [comment]
This has been added a while back in the new [banners page](https://www.optifine.net/beta/banners) of the website.
