### ISSUE TITLE
Use gbuffers_armor_glint for everything that is enchanted (gbuffers_enchanted)

### ISSUE THREAD

**Issue by SiIdur** [sp614x/optifine#345]
Instead of just using it for armor use it for everything that is enchanted.

**Comment by sp614x** [comment]
Should only the handheld items (first person, third person) use the "gbuffers_armor_glint" or all items (hotbar, inventory, etc)?

**Comment by SiIdur** [comment]
Hmm, all items I think. But the items should still be handled by gbuffers_entities. Like it is right now, gbuffers_armor_glint is only used for the effect itself, not the armor. (enchanted armor is still rendered in gbuffer_entities)

However there's no need for hotbar support. Items render just fine in it for every shaderpack.

**Comment by sp614x** [comment]
The items will still be rendered with "gbuffer_entities", only the glint efect will be affected. 
If the items in the hotbar, inventory, menus, etc. are OK, then I will only change the glint of the handheld (3D) items, which are rendered with the player model, to use "gbuffers_armor_glint".

**Comment by SiIdur** [comment]
I see, the reason why I said all items was because of dropped items. Essentially handheld items and dropped items are all I need.

**Comment by sp614x** [comment]
Correct, the dropped items are also 3D rendered in the world.

**Comment by sp614x** [comment]
Updated preview B3 to use "gbuffers_armor_glint" for dropped and handheld enchanted items.

**Comment by dotModded** [comment]
Thank you sp614x this will make life much easier.

**Comment by SiIdur** [comment]
Thanks, it's working perfectly fine now.
