### ISSUE TITLE
Redstone Animated setting does nothing (1.14.4 w/ fabric)

### ISSUE THREAD

**Issue by RedCMD** [sp614x/optifine#3450]
Turning Redstone Animated: OFF does not turn particles off for redstone dust, repeaters, comparators, torches, levers or redstone ore
Only setting Particles: Minimal will turn them off
This did work in 1.12 optifine

**Comment by sp614x** [comment]
Fabric is not supported.

**Comment by RedCMD** [comment]
IDK why I didn't just test pure 1.14.4 Optifine
But this bug does affect pure 1.14.4 & 1.15.2 Optifine
