### ISSUE TITLE
crash right before the title screen normally shows

### ISSUE THREAD

**Issue by Busrider2** [sp614x/optifine#3452]
Every time i open minecraft with optifine and forge with mods it crashes before i can even get to the title screen 

The crash report is:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  ForgelinPlugin (Forgelin-1.8.3.jar)
  LoadingPlugin (Xaeros_Minimap_20.3.1_Forge_1.12.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.5.6-core.jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 2/23/20 9:23 PM
Description: Unexpected error

java.lang.NoSuchFieldError: field_191308_b
	at net.optifine.config.ConnectedParser.parseEntities(ConnectedParser.java:1248)
	at net.optifine.shaders.EntityAliases.loadEntityAliases(EntityAliases.java:164)
	at net.optifine.shaders.EntityAliases.update(EntityAliases.java:89)
	at net.optifine.shaders.EntityAliases.resourcesReloaded(EntityAliases.java:61)
	at net.optifine.shaders.Shaders.resourcesReloaded(Shaders.java:5939)
	at net.optifine.util.TextureUtils.resourcesReloaded(TextureUtils.java:321)
	at net.optifine.util.TextureUtils$1.func_110549_a(TextureUtils.java:362)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.optifine.util.TextureUtils.registerResourceListener(TextureUtils.java:366)
	at net.minecraft.client.renderer.EntityRenderer.frameInit(EntityRenderer.java:2809)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1307)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1118)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 409317424 bytes (390 MB) / 1845493760 bytes (1760 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 Optifine OptiFine_1.12.2_HD_U_F5 20 mods loaded, 20 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                  | Version                  | Source                                        | Signature                                |
	|:------ |:------------------- |:------------------------ |:--------------------------------------------- |:---------------------------------------- |
	| UCHIJA | minecraft           | 1.12.2                   | minecraft.jar                                 | None                                     |
	| UCHIJA | mcp                 | 9.42                     | minecraft.jar                                 | None                                     |
	| UCHIJA | FML                 | 8.0.99.99                | forge-1.12.2-14.23.5.2768.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | forge               | 14.23.5.2768             | forge-1.12.2-14.23.5.2768.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | xaerominimap_core   | 1.12.2-1.0               | minecraft.jar                                 | None                                     |
	| UCHIJA | damageindicatorsmod | 1.0                      | [1.12.2]DamageIndicatorsMod-3.5.1.jar         | None                                     |
	| UCHIJA | bettercaves         | 1.12.2-1.0.2.1           | bettercaves-1.12.2-1.0.2.1.jar                | None                                     |
	| UCHIJA | forgelin            | 1.8.3                    | Forgelin-1.8.3.jar                            | None                                     |
	| UCHIJA | betterportals       | 0.3.4                    | betterportals-0.3.4.jar                       | None                                     |
	| UCHIJA | biomesoplenty       | 7.0.1.2444               | BiomesOPlenty-1.12.2-7.0.1.2444-universal.jar | None                                     |
	| UCHIJA | chiselsandbits      | 14.32                    | chiselsandbits-14.32.jar                      | None                                     |
	| UCHIJA | codechickenlib      | 3.2.3.358                | CodeChickenLib-1.12.2-3.2.3.358-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJA | cfm                 | 6.3.1                    | furniture-6.3.1-1.12.2 (1).jar                | None                                     |
	| UCHIJA | waila               | 1.8.24                   | Hwyla-1.8.24-B39_1.12.jar                     | None                                     |
	| UCHIJA | inventorytweaks     | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                      | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJA | jei                 | 4.15.0.268               | jei_1.12.2-4.15.0.268.jar                     | None                                     |
	| UCHIJA | jrftl               | 1.1                      | JRFTL[1.12.2]-1.1.jar                         | None                                     |
	| UCHIJA | nei                 | 2.4.3                    | NotEnoughItems-1.12.2-2.4.3.245-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJA | xaerominimap        | 20.3.1                   | Xaeros_Minimap_20.3.1_Forge_1.12.jar          | None                                     |
	| UCHIJA | thebetweenlands     | 3.5.6                    | TheBetweenlands-3.5.6-universal.jar           | 38067d6878811efb38b6a045521cfd80b9b60b38 |

	Loaded coremods (and transformers): 
ForgelinPlugin (Forgelin-1.8.3.jar)
  
LoadingPlugin (Xaeros_Minimap_20.3.1_Forge_1.12.jar)
  xaero.common.core.transformer.ChunkTransformer
  xaero.common.core.transformer.NetHandlerPlayClientTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.5.6-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
	GL info: ' Vendor: 'Intel' Version: '4.5.0 - Build 25.20.100.6519' Renderer: 'Intel(R) UHD Graphics 620'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2768
	LWJGL: 2.9.4
	OpenGL: Intel(R) UHD Graphics 620 GL version 4.5.0 - Build 25.20.100.6519, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: ThePewDiePack-v15.0.zip (incompatible)
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 10
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Sildurs Vibrant Shaders v1.262 Medium (1).zip
	OpenGlVersion: 4.5.0 - Build 25.20.100.6519
	OpenGlRenderer: Intel(R) UHD Graphics 620
	OpenGlVendor: Intel
	CpuCount: 8

**Comment by asbyth** [comment]
go into your shaderpacks folder and delete entity.properties

**Comment by Busrider2** [comment]
@asbyth thank you it no longer crashes and optifine works with shaders
![Screenshot (5)](https://user-images.githubusercontent.com/61398405/75130548-014e8a00-569d-11ea-8000-1d2ded1d3780.png)
