### ISSUE TITLE
is rudoplays shader owned by copatic13

### ISSUE THREAD

**Issue by anonymus411** [sp614x/optifine#3459]
i keep hearing different things,i just want to know,thanks!

**Comment by Naeqirelle** [comment]
this isn't really the place to be asking, try on the optifine discord under the #shaders channel https://discord.gg/3mMpcwW

**Comment by ZtereoHYPE** [comment]
Yeah this github page is to report optifine bugs. If you want to know more about shaders, go in the shaderlabs discord server (pinned in #shaders)

**Comment by anonymus411** [comment]
no,i just want to know if its stolen

**Comment by HiItsDevin** [comment]
Yeah but this isn't the place for that

**Comment by ZtereoHYPE** [comment]
As my colleague said, this is not the place for asking shader questions, not only because you are filling up uselessly the GitHub page, but because probably no one knows. As a reference, it’s like entering a bar and asking for some ink for your printer. The shaderlabs discord server would be the ink shop for the printer, the ideal place to go.

**Comment by anonymus411** [comment]
all i asked was a simple question was all, didnt mean to trigger anyone.

**Comment by anonymus411** [comment]
all i asked was simple question,didnt mean to trigger anyone.

**Comment by ZtereoHYPE** [comment]
The short answer is: we don’t know, go ask the shaderlabs discord

**Comment by anonymus411** [comment]
i did they helped.

**Comment by sp614x** [comment]
Not relevant to OptiFine.

**Comment by anonymus411** [comment]
you cant close my own post

**Comment by HiItsDevin** [comment]
it's sp's repository, he can do what he wants.

**Comment by anonymus411** [comment]
i was just asking,all the people all too harsh here, if you want to close this post fight me on it

**Comment by anonymus411** [comment]
oh and also have fun being reported bud, for closing my OWN post

**Comment by realjackasterisk** [comment]
Ladies and gentlemen, a prime example of what NOT to do on GitHub.

**Comment by Siuolthepic** [comment]
I didn't know a man with that few brain cells could comprehend shaders. Much less download Optifine.

**Comment by Siuolthepic** [comment]
Also, kindly unb!ock Devin.
He does not own the repo, nor blocked you.
Please learn to read a repo name better.

**Comment by rre36** [comment]
![bigbrain](https://i.postimg.cc/jj1GVK0b/bigbrain.jpg)

**Comment by anonymus411** [comment]
> I didn't know a man with that few brain cells could comprehend shaders. Much less download Optifine.

thank you i know i have no brain cells, i have multiple brain disorders, thank you for noticing!

**Comment by Naeqirelle** [comment]
Brain disorders require you to have a brain, which i doubt with you

**Comment by realjackasterisk** [comment]
@sp614x can you just lock this now?
