### ISSUE TITLE
Defining texture path replaces block destroy overlay

### ISSUE THREAD

**Issue by ShaunNoWay** [sp614x/optifine#346]
Defining a texture path for a model with `"texture"` makes that same texture overlay as if it were the block destroy overlay.
![normal](https://cloud.githubusercontent.com/assets/14033754/20665815/1ce3f858-b52f-11e6-9b7e-236c942f83f5.png)
![bugs](https://cloud.githubusercontent.com/assets/14033754/20665737/c51927b0-b52e-11e6-8ceb-35b9c79a8793.jpg)

Not defining a texture path makes the overlay work just fine.
![i](https://cloud.githubusercontent.com/assets/14033754/20665754/d76e6682-b52e-11e6-82f4-2120aeead8cc.jpg)

**Comment by ShaunNoWay** [comment]
This only happens with custom part models. The default ones work just fine.
![part](https://cloud.githubusercontent.com/assets/14033754/20634800/94261ae0-b322-11e6-8a62-22ecc634061c.jpg)

**Comment by ShaunNoWay** [comment]
This bug seems to be caused by defining a custom texture path with `"texture"`. Using the vanilla model texture (textures\entity\chest\normal.png) shows the destroy animation. Though it's a bit skewed.
![fix](https://cloud.githubusercontent.com/assets/14033754/20650975/c94f0de8-b4a9-11e6-9fef-d865a7190b68.jpg)

chest.jpm
```
{
    # Do not define texture path!
    # "texture": "chest",
    
    # Replace "textures\entity\chest\normal" with 48x16 custom chest texture
    "textureSize": [48, 16],
    
    "boxes":
    [
    {
        "coordinates": [-1.0, -6.0, -1.0, 16.0, 16.0, 16.0],
        
        "uvDown":  [0.0, 0.0, 16.0, 16.0],
        "uvUp":    [0.0, 0.0, 16.0, 16.0],
        
        "uvNorth": [32.0, 0.0, 48.0, 16.0], # Front
        "uvSouth": [16.0, 0.0, 32.0, 16.0],
        "uvWest":  [16.0, 0.0, 32.0, 16.0],
        "uvEast":  [16.0, 0.0, 32.0, 16.0]
    }
    ]
}
```

**Comment by ShaunNoWay** [comment]
![i](https://cloud.githubusercontent.com/assets/14033754/20660055/5901f3f4-b515-11e6-9fcc-2d32cd018206.jpg)

textures\entity\chest\normal.png:
![normal](https://cloud.githubusercontent.com/assets/14033754/20660182/2ab216cc-b516-11e6-9a3e-7506e382e304.png)


chest.jem:
```
{
    "models": 
    [
    {
        "part": "base",
        "attach": false,

        # Texture must be square so overlay doesn't get squashed
        # It also must be four times the model dimensions so the overlay doesn't tile
        "textureSize": [64, 64],
        "boxes":
        [
        {
            "textureOffset": [12.0, 12.0], # Offset to center overlay
            "coordinates": [-1.0, -6.0, -1.0, 16.0, 16.0, 16.0]
        }
        ]
    },
    {
        "part": "lid",
        "attach": false
    },
    {
        "part": "knob",
        "attach": false
    }
    ]
}
```

**Comment by sp614x** [comment]
Updated preview B4 with a bugfix.

**Comment by ShaunNoWay** [comment]
Thank you!
