### ISSUE TITLE
optifine preview 1.15.2 crash with forge

### ISSUE THREAD

**Issue by Caiobebebey** [sp614x/optifine#3461]
i try open optifine with forge 1.15.2 (31.1.0) and the game crashes.
http://prntscr.com/r7j8jy (not shows we have loaded the optifine)
and in the end, the game load at 50% ~70% and crash http://prntscr.com/r7j88l

**Comment by asbyth** [comment]
they're not compatible yet

**Comment by sp614x** [comment]
Not compatible with Forge yet.
