### ISSUE TITLE
Visual bug caused by destroying a placed block within a 5 second intervall and doing the same but on a different Y level

### ISSUE THREAD

**Issue by PappaKompis** [sp614x/optifine#3463]
![2020-02-25_18 48 50](https://user-images.githubusercontent.com/54662825/75343771-7090cd80-5899-11ea-99fb-e6ad13eaf153.png)
![2020-02-25_18 49 09](https://user-images.githubusercontent.com/54662825/75343780-7a1a3580-5899-11ea-97d3-08d98bcc922b.png)
![2020-02-25_18 49 16](https://user-images.githubusercontent.com/54662825/75343794-7e465300-5899-11ea-856f-7a7ea3e1c2c8.png)
![2020-02-25_18 49 25](https://user-images.githubusercontent.com/54662825/75343800-82727080-5899-11ea-8cc5-cf3b17638325.png)
![2020-02-25_18 49 37](https://user-images.githubusercontent.com/54662825/75343807-843c3400-5899-11ea-8f3a-166f780307fd.png)
![2020-02-25_18 49 43](https://user-images.githubusercontent.com/54662825/75343809-8605f780-5899-11ea-8b8e-11d8f96141a3.png)

**Comment by ZtereoHYPE** [comment]
What preview version are you using? This bug seems to have been fixed in pre4

**Comment by sp614x** [comment]
Should be fixed in pre3, make sure to use latest preview.
