### ISSUE TITLE
no starting

### ISSUE THREAD

**Issue by joenriq** [sp614x/optifine#3466]
https://paste.ee/p/jdzMB the minecraft crashes before te starting

**Comment by HiItsDevin** [comment]
Optifine 1.15.2 is currently not compatible with Forge.
![image](https://user-images.githubusercontent.com/30705254/75369307-0fa4cd80-5878-11ea-8853-2b8a64d084bf.png)

**Comment by Jarfeh** [comment]
oh hi it's devin

**Comment by AbsoluteFondant** [comment]
Oh hi Mark

**Comment by sp614x** [comment]
OptiFine is not compatible with Forge yet.
