### ISSUE TITLE
Can I use Optifine in my public modpack on CurseForge?

### ISSUE THREAD

**Issue by luciobortoletto** [sp614x/optifine#3467]
Can I use Optifine in my public modpack on CurseForge?

**Comment by YhvrWasTaken** [comment]
From the [FAQ](https://optifine.net/faq):

> **Can I include OptiFine in my modpack?**
> Generally no, unless you have an explicit permission from us.
 
Just FYI.

**Comment by asbyth** [comment]
why do you think hes asking for permission lol

**Comment by luciobortoletto** [comment]
ok, but can I add the download link from the official Optifine website?

**Comment by sp614x** [comment]
You can not add OptiFine to a public modpack.
You can add a link to the OptiFine website.
