### ISSUE TITLE
Minecraft 1.15.2 crashes when i load up the preview version.

### ISSUE THREAD

**Issue by conner123321123** [sp614x/optifine#3469]
Link to video of it happening: https://drive.google.com/file/d/1O7_3cEdas6pS9gn-mQyd7RlJKL09LGqZ/view?usp=drivesdk

Error message: 

Error: could not find Java Virtual Machine
Error: A fatal exception has occured. Program will exit.

**Comment by sp614x** [comment]
Should be fixed in latest preview.
