### ISSUE TITLE
[1.8.9] Optifine L5 Causing Crashes

### ISSUE THREAD

**Issue by Axizon** [sp614x/optifine#3471]
I play 1.8.9, I have been utilizing the stable I7 release, since L5 consistently causes the following error. I've narrowed it down, and it seems to be an incompatibility of some sort between OldAnimations and Optifine, but can someone please explain what the actual error codes are referencing, and if there is any fix? Thanks.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  Powns' Ghost Lava Fix ([1.8.9] Powns Ghost Liquid Fix - 1.1.jar)
  Main (OldAnimationsMod_v2.4.2_FORGE_MC1.8.9.jar)
  FMLLoadingPlugin (MemoryFix.jar)
  FMLLoadingPlugin (MouseDelayFix-1.0.jar)
  PlayerAPIPlugin (PlayerAPI-1.8.9-1.0.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 2/27/20 1:48 AM
Description: Initializing game

java.lang.IllegalAccessError: tried to access field net.minecraft.client.renderer.entity.RendererLivingEntity.field_77045_g from class net.minecraft.client.renderer.entity.layers.LayerMooshroomMushroom
	at net.minecraft.client.renderer.entity.layers.LayerMooshroomMushroom.<init>(LayerMooshroomMushroom.java:36)
	at net.minecraft.client.renderer.entity.RenderMooshroom.<init>(SourceFile:14)
	at net.minecraft.client.renderer.entity.RenderManager.<init>(RenderManager.java:152)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:481)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.renderer.entity.layers.LayerMooshroomMushroom.<init>(LayerMooshroomMushroom.java:36)
	at net.minecraft.client.renderer.entity.RenderMooshroom.<init>(SourceFile:14)
	at net.minecraft.client.renderer.entity.RenderManager.<init>(RenderManager.java:152)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:481)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 332598512 bytes (317 MB) / 939524096 bytes (896 MB) up to 5368709120 bytes (5120 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.1722 Optifine OptiFine_1.8.9_HD_U_L5 26 mods loaded, 26 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1722.jar) 
	UCH	Forge{11.15.1.1722} [Minecraft Forge] (forge-1.8.9-11.15.1.1722.jar) 
	UCH	lavafix{1.1} [Powns' Ghost Lava Fix] (minecraft.jar) 
	UCH	mousedelayfix{1.0} [MouseDelayFix] (minecraft.jar) 
	UCH	oldanimations{2.4.2} [OldAnimationsMod] (minecraft.jar) 
	UCH	PlayerAPI{1.0} [Player API] (minecraft.jar) 
	UCH	skyblockaddons{1.4.2} [SkyBlock Addons] (SkyblockAddons-1.4.2-for-MC-1.8.9.jar) 
	UCH	reachdisplaymod{1.0} [Reach Display Mod] (1.8.9_Reach_Display1.0.jar) 
	UCH	fpsdisplaymod{1.0} [FPSDisplayMod] ([1.8.9] CheatBreakerHUD v4.jar) 
	UCH	cpsmod{1.0} [CPSMod] ([1.8.9] CheatBreakerHUD v4.jar) 
	UCH	keystrokesmod{0.1} [KeystrokesMod] ([1.8.9] CheatBreakerHUD v4.jar) 
	UCH	pingtag{4.0} [pingtag] ([1.8.9] PingTag Mod - 4.0.jar) 
	UCH	Powns ArmorStatus HUD{1.0} [powns-armorhud] ([1.8.9] Powns ArmorStatus HUD - 1.1.jar) 
	UCH	pownscoordshud{1.0} [Powns' Coords HUD] ([1.8.9] Powns Coords HUD - 1.0.jar) 
	UCH	pownspotionhud{1.0} [pownspotionhud] ([1.8.9] Powns PotionEffect HUD - 1.0.jar) 
	UCH	ToggleSneak{3.1.4} [ToggleSneak] ([1.8.9] Powns ToggleSneak Edit.jar) 
	UCH	ChromaHUD{3.0} [Chroma HUD] (ChromaHUD-3.0.jar) 
	UCH	combodisplaymod{1.0} [Combo Display Mod] (Combo_Display_1.8.9.jar) 
	UCH	LunatriusCore{1.1.2.32} [LunatriusCore] (LunatriusCore-1.8.9-1.1.2.32-universal (1).jar) 
	UCH	memoryfix{0.3} [MemoryFix] (MemoryFix.jar) 
	UCH	orangesimplemod{1.0} [orangesimplemod] (Orange's+Simple+Mods-1.2.jar) 
	UCH	particlemod{1.02} [Particle Mod] (Particle Mod.jar) 
	UCH	alphahexmcmod{1.0} [Pot Alert] (PotAlert Port by OFP.jar) 
	UCH	Schematica{1.7.7.143} [Schematica] (Schematica-1.8.9-1.7.7.143-universal.jar) 
	UCH	timechanger1.8{1.0} [TimeChanger 1.8] (TimeChanger 1.8.jar) 
	Loaded coremods (and transformers): 
Powns' Ghost Lava Fix ([1.8.9] Powns Ghost Liquid Fix - 1.1.jar)
  me.powns.lavafix.asm.PlayerControllerMPTransformer
  me.powns.lavafix.asm.ItemBucketTransformer
Main (OldAnimationsMod_v2.4.2_FORGE_MC1.8.9.jar)
  com.spiderfrog.main.ClassTransformer
FMLLoadingPlugin (MemoryFix.jar)
  io.prplz.memoryfix.ClassTransformer
FMLLoadingPlugin (MouseDelayFix-1.0.jar)
  io.prplz.mousedelayfix.ClassTransformer
PlayerAPIPlugin (PlayerAPI-1.8.9-1.0.jar)
  api.player.forge.PlayerAPITransformer
	GL info: ' Vendor: 'Intel' Version: '4.5.0 - Build 24.20.100.6344' Renderer: 'Intel(R) UHD Graphics 620'
	Launched Version: 1.8.9-forge1.8.9-11.15.1.1722
	LWJGL: 2.9.4
	OpenGL: Intel(R) UHD Graphics 620 GL version 4.5.0 - Build 24.20.100.6344, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: ! #§6Axi §9v3 Simple §8[§c32x§8]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
	OptiFine Version: OptiFine_1.8.9_HD_U_L5
	OptiFine Build: 20191204-143016
	Render Distance Chunks: 6
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 - Build 24.20.100.6344
	OpenGlRenderer: Intel(R) UHD Graphics 620
	OpenGlVendor: Intel
	CpuCount: 8

**Comment by asbyth** [comment]
this is an issue with old animations being terribly coded, remove it and dont use any of orange's mods lol

**Comment by Axizon** [comment]
While this is true, there's not really an option for the majority of people using non client minecraft.
All the mods that provide these animations are horrendously old and unstable, as well as having no development anymore. I suppose the only option is to move to a private client or update?

**Comment by ZekerZhayard** [comment]
https://github.com/ZekerZhayard/OldAnimationsModFix

I wrote a mod to replace the horrible codes in OldAniamtionsMod,. It can solve this issue.

**Comment by Axizon** [comment]
@ZekerZhayard Absolutely phenomenal. Thank you very much for your contribution, this has been a thorn in some people for a long time.
