### ISSUE TITLE
Screen flashes Minecraft 1.15.2

### ISSUE THREAD

**Issue by BDdJ-12** [sp614x/optifine#3472]
As the title already indicated the screen flashes in the pre- versions of Optifine 1.15.2. Sadly enough I don't have any documentation of this as... well they're flashes. Even before you've realized you see one it's already gone before you can get any footage of it and being unable to record it I'll do my best to describe it. In the first minutes nothing is wrong, but they become more frequent the longer you play. The color of the flashes depend on the item you're holding for as far as I know. It's not the entire screen it's more like a randomly appearing smear on a random place of the screen. Most of the time the flashes appear when you're experiencing a fps drop. When you active a fairly complex redstone machine for instance. I've already taken a look at the similar issues, but those visual glitches are persistent. These are only flashes occurring more frequently over time.

**Comment by sp614x** [comment]
Fixed in latest preview.
