### ISSUE TITLE
Would it be possible to add a Saturation slider?

### ISSUE THREAD

**Issue by Trilasent** [sp614x/optifine#3477]
Sorry if this has been asked before, but I was wondering if it would be difficult/possible to add a saturation slider to Optifine in the "Details" or "Other" tabs.

**Comment by BBftw** [comment]
That's something for a shader developer to do, it wouldn't be an optifine feature

**Comment by yezhiyi9670** [comment]
I think it will more likely be added into "Shaders" as a completion of the current shader.

**Comment by sp614x** [comment]
A color correction usually needs a separate post-processing step, this can be best done in a shader pack.
