### ISSUE TITLE
 the button shader is not clickable 

### ISSUE THREAD

**Issue by Pulce69** [sp614x/optifine#3478]
why do you give me this problem? i use version 1.15.2 mincraft  and  OptiFine 1.15.2 HD U G1 pre9

I had no problems with this version OptiFine 1.14.2 HD U F1 pre15 to load the mods

https://ibb.co/t4gW16m

**Comment by asbyth** [comment]
consider reading changelogs

**Comment by HiItsDevin** [comment]
**_sigh_**

![changelog](https://i.hiitsdevin.dev/captures/hiitsdevin_new_104766.png)
![clearly there's no shaders](https://hiitsdevin.dev/no.png)

**Comment by Pulce69** [comment]
thanks for the info, I thought it was my problem.
When will the complete version come out?

**Comment by asbyth** [comment]
let us know when you figure that out

**Comment by HiItsDevin** [comment]
In case you haven't figured it out yet, the answer is

When it's done.

**Comment by cs127** [comment]
sp please close this

**Comment by NitroCipher** [comment]
Shaders are disabled in current optifine 1.15.2 previews
