### ISSUE TITLE
Inventory Flicker

### ISSUE THREAD

**Issue by MikeP9x** [sp614x/optifine#3479]
Hi, today I installed the latest preview version of Optifine, and noticed a bug. Whilst playing in fullscreen mode on a Radeon graphics card, whenever I open the inventory and move my mouse, the screen flickers black briefly a couple times a second. But instead of the whole screen, it is either the left half or right half that flickers, alternating between the two. I am running on a high refresh rate monitor (180Hz) with an Intel i5-8600K CPU and a Radeon RX5700 graphics card. This isn't a major bug or anything but it is rather annoying when in the inventory panel for an extended amount of time.

Hope this is enough information, if not let me know and I can try to provide more.

Note:
The issue does not occur whilst in Windowed mode, and does not occur when outside of an inventory menu. I have had this happen in older versions of minecraft using this same graphics card, but in that case it was ~1.14 and instead of the inventory screen flickering black, it was during regular gameplay and white.

**Comment by MikeP9x** [comment]
Further Notes:
- Locking framerate to 60fps decreases the frequency of the flickers, however they are still there.
- The issue only occurs whilst my mouse is moving, and does not happen when the cursor is still.
- This issue is not isolated to the player inventory, and also occurs within other inventory panels. However it does NOT occur in the main menu or pause screens. Only in inventory GUIs

**Comment by sp614x** [comment]
Does it happen in vanilla?
