### ISSUE TITLE
CIT doesn't take names for enchantmentIDs

### ISSUE THREAD

**Issue by ZwipZwapZapony** [sp614x/optifine#348]
This applies for the latest version of OptiFine as well as earlier versions, and sorry for not really thinking about reporting it sooner. However, I have a bow CIT, which I use to remove the arrow when pulling if the bow has the Infinity enchantment.

The below code works fine, but if "enchamentIDs=51" is replaced with "enchantmentIDs=minecraft:infinity", with or without "minecraft:", it applies regardless of whether the bow has Infinity or not.

`type=item`
`matchItems=minecraft:bow`
`enchantmentIDs=51`
`texture.bow_standby=bow_infinity_standby`
`texture.bow_pulling_0=bow_infinity_pulling_0`
`texture.bow_pulling_1=bow_infinity_pulling_1`
`texture.bow_pulling_2=bow_infinity_pulling_2`

The "/enchant" command in MineCraft supports "minecraft:infinity" as an enchantment, by the way, and even auto-fills to it when pressing Tab.

**Comment by sp614x** [comment]
Updated preview B3 to recognize enchantment names.
