### ISSUE TITLE
[Optifine 1.15.2 pre9]weather render bug

### ISSUE THREAD

**Issue by Command1264** [sp614x/optifine#3480]
https://www.youtube.com/watch?v=OS5IkND7go8

On rain or thunder weather.
In inside can see weather rander. 

Minecraft version: 1.15.2
Optifine version: 1.15.2 pre9
Other: None

**Comment by Regnander** [comment]
I can confirm this. Rain particles will briefly show up behind any blocks when you pick up items.

![ezgif-1-41d94e93b13c](https://user-images.githubusercontent.com/17113053/75820821-5aa17200-5d9d-11ea-87e7-1dd92b4e4fa3.gif)

![2020-03-03_22 00 37](https://user-images.githubusercontent.com/17113053/75819664-5f652680-5d9b-11ea-8292-fec555071658.png)

**Comment by realflow100** [comment]
I'm pretty sure this is a known bug
it's possibly a vanilla-related bug.

**Comment by asbyth** [comment]
it is a vanilla bug

**Comment by Regnander** [comment]
I just tested in vanilla and it is also affected, but I wasn't able to find a JIRA ticket about it.

**Comment by sp614x** [comment]
Vanilla bug.
https://bugs.mojang.com/browse/MC-163575
