### ISSUE TITLE
X-Ray cheat and WWE cheat client do not work (OptiFine 1.15.2 HD U G1 pre9)

### ISSUE THREAD

**Issue by WalkDark** [sp614x/optifine#3482]
Good afternoon.
WWE 3.0.4 cheat client does not work together with OptiFine for 1.15.2, error when opening the game.
The X-Ray cheat doesn't work. Chunks are updated and nothing else. Transparent textures do not work for viewing ores.
Please correct it. Many players are worried.

**Comment by HiItsDevin** [comment]
I don't think Optifine supports hacked clients, and never has supported hacked clients.

**Comment by HiItsDevin** [comment]
Also, using a Hack Client breaks Minecraft's TOS, so...

**Comment by WalkDark** [comment]
Well. Support for the cheat client is not an OptiFine problem.
The X-Ray cheat doesn't work. These are textures that make all but certain blocks transparent. May be used for legitimate purposes. OptiFine 1.14.4 HD U F3 supports these textures, but now they no longer work. Chunks are simply updated.

**Comment by HiItsDevin** [comment]
> The X-Ray cheat doesn't work. 

Still a hacked client issue, not optifine. Anyway, I'd suggest you stop using hacked clients for whatever reason you're using them, as they're against the Minecraft TOS.

**Comment by justForDaCrab** [comment]
Listen, hacked clients are against Minecraft TOS so why in the world would optifine fix em, so you ain't getting any help

**Comment by WalkDark** [comment]
> Still a hacked client issue, not optifine [pretty sure]. Anyway, I'd suggest you stop using hacked clients for whatever reason you're using them, as they're against the Minecraft TOS.

If you use 1.15.2-X-Ray works, if you run it together with OptiFine - it does not work. This means that the error is present in OptiFine.

**Comment by HiItsDevin** [comment]
> > Still a hacked client issue, not optifine [pretty sure]. Anyway, I'd suggest you stop using hacked clients for whatever reason you're using them, as they're against the Minecraft TOS.
> 
> If you use 1.15.2-X-Ray works, if you run it together with OptiFine - it does not work. This means that the error is present in OptiFine.

I don't think anyone is going to fix it..

**Comment by WalkDark** [comment]
> I don't think anyone is going to fix it..

Very sorry. The developers of the X-Ray cheat wrote that for 1.14.4, you need to use OptiFine 1.14.4 HDF 3, because it does not work on OptiFine 1.14.4 HD U F4 and OptiFine 1.14.4 HD U F5. For 1.15.2, I understand there will be no support at all...

**Comment by HiItsDevin** [comment]
> > I don't think anyone is going to fix it..
> 
> Very sorry. The developers of the X-Ray cheat wrote that for 1.14.4, you need to use OptiFine 1.14.4 HDF 3, because it does not work on OptiFine 1.14.4 HD U F4 and OptiFine 1.14.4 HD U F5. For 1.15.2, I understand there will be no support at all...

Alright then... have fun waiting for that buddy, but please remember that Optifine has no official support for things like this. That is up to the developers of such "cheats".

**Comment by realjackasterisk** [comment]
> Many players are worried.

Boo fucking hoo. Learn to play legitimately.

**Comment by ZtereoHYPE** [comment]
How do I close someone’s else thread

**Comment by MrCheeze446** [comment]
consider not cheating

**Comment by THEREALWWEFAN231** [comment]
This is a WWE bug, this can be closed, I currently already fixed the crash but Xray doesn't work yet, WalkDark will have to wait till the next WWE update for the "fix", also for some of you guys WWE isn't a hacked client, its a mod just like optifine, it does not distribute minecrafts code as hacked clients do.

**Comment by HiItsDevin** [comment]
Ah, they said "WWE Cheat Client" so I assumed it was a hack client

**Comment by HiItsDevin** [comment]
Nevermind. It is a hack client. Not a mod.

**Comment by THEREALWWEFAN231** [comment]
No, it is a mod, does it have "hacked client" features, yes, as I said "its a mod just like optifine, it does not distribute minecrafts code as hacked clients do". I can also show a screenshot, proving it doesnt distribute minecrafts code, 
![image](https://user-images.githubusercontent.com/21975901/75620253-6aba1700-5b3b-11ea-8f2a-481c93117b6e.png) a hacked client isn't going be 3.5mb it's going be around 10+mb, also there's no net package. Now if you want to call it a hacked client because it has "hacked client" features, you do you, but WWE in no way shape or form breaks minecrafts TOS. But if you are going do that a minimap is also a "hacked client". But let's not argue!(I'm not being sarcastic either)

**Comment by HiItsDevin** [comment]
Can someone just close this issue already.

**Comment by Draycia** [comment]
Your website's domain and reddit post(s) literally call it a client lmao.

**Comment by HiItsDevin** [comment]
literally a client lol

![](https://i.hiitsdevin.dev/captures/hiitsdevin_new_008057.png)
![](https://i.hiitsdevin.dev/captures/hiitsdevin_new_370747.png)
![](https://i.hiitsdevin.dev/captures/hiitsdevin_new_861552.png)

**Comment by THEREALWWEFAN231** [comment]
Well, thats true😳, not denying at one point it was a hacked client, also not admitting it :eyes:?!?!?!?! but its already to late to change the name/website domain.

**Comment by iTeoYT** [comment]
Broo.. Use Wurst mode client. Easy to install xD

**Comment by realjackasterisk** [comment]
@sp614x please close and lock this thread before more people start talking about cheat clients/mods.

**Comment by HiItsDevin** [comment]
please close and lock

**Comment by JeffaloBob** [comment]
Isn't optifine not even compatible with any mods right now? This is unessecary, close the thread.

**Comment by RealIndrit** [comment]
This whole thread is ♿️, Imagine asking Optifine dev to fix Xray because Optifine render breaks it 🤡, just fix it yourself.. How hard can it be? 🤡 (Don't come to me and say its impossible, Ive seen it working with xray and I literally gave you the key to the solution....)

**Comment by cs127** [comment]
why isn't this closed yet

**Comment by sp614x** [comment]
OptiFine doesn't support hacked/cheat clients.

**Comment by BlakeChanThePerson** [comment]
> 
> 
> OptiFine doesn't support hacked/cheat clients.

Hacked/Cheat clients are also used in offline/singleplayer worlds, it doesn't make sense to not support it.

**Comment by JackDotJS** [comment]
> dont worry guys cheating is ok because you can also do it in singleplayer

Please don't post in nearly year-old threads just to post monumentally stupid takes.
