### ISSUE TITLE
[1.15.2] Conflict with Terrestria mod causes game crash

### ISSUE THREAD

**Issue by Bineary** [sp614x/optifine#3489]
The Terrestria mod (https://www.curseforge.com/minecraft/mc-mods/terrestria) and Optine/Optifabric are causing a crash. This happens with only Fabric, Fabric API, Terrestria, Optifabric and Optifine 1.15.2 HD U G1 pre9. Running without Terrestria or without Optifine works. I've attached crash logs. 

[crash-2020-03-01_17.58.08-client.txt](https://github.com/sp614x/optifine/files/4272685/crash-2020-03-01_17.58.08-client.txt)

**Comment by asbyth** [comment]
optifine doesn't officially support fabric

**Comment by BBftw** [comment]
take this to the terrestria developer

**Comment by Bineary** [comment]
Brought it to them and the OptiFabric team as well.

**Comment by sp614x** [comment]
OptiFine doesn't support Fabric.

**Comment by RealIndrit** [comment]
Use Sodium and Phosphor Mods for fabric, they do the same as Optifine, they are better than Optifine when combined imo.
