### ISSUE TITLE
Pistons flash clear on retraction

### ISSUE THREAD

**Issue by PaperAviator** [sp614x/optifine#3496]
Pistons flash clear upon retraction, unlike vanilla pistons which stay opaque. (1.15.2_HD_U_G1_pre9)

**Comment by sp614x** [comment]
The vanilla pistons rely on immediate chunk updates for the proper rendering. 
These updates generate a lot of lag spikes and are optimized in OptiFine to work a bit differently.
As a side effect some fast switching blocks like pistons may not render 100% perfectly in the transition between base and extended state.
