### ISSUE TITLE
CEM for most minecarts is broken in 1.15.2 HD U G1 pre9

### ISSUE THREAD

**Issue by MushirMickeyJoe** [sp614x/optifine#3498]
![image](https://user-images.githubusercontent.com/31923214/75803380-9d078680-5d7e-11ea-99f7-aaf93a16f96c.png)
works in 1.14.4 HD U F5
![image](https://user-images.githubusercontent.com/31923214/75803442-b3addd80-5d7e-11ea-880f-e17b2366cd93.png)
not in 1.15.2 HD U G1 pre9

**Comment by naeqirelle2020** [comment]
@MushirMickeyJoe does this still occur in the latest preview?

**Comment by KaiAF** [comment]
This seems to be fixed. Let me know if you are still having issues, please.
