### ISSUE TITLE
Weird chunk loading issue

### ISSUE THREAD

**Issue by Rasqee** [sp614x/optifine#3501]
chunks will not load unless updated by a block being placed or updated

**Comment by HiItsDevin** [comment]
Can you provide a video or some sort of visual aid of this happening?

**Comment by asbyth** [comment]
also provide what optifine version you're using, seeing as i believe this was fixed awhile ago

**Comment by sp614x** [comment]
It was fixed in one of the previews, make sure to use latest preview.
