### ISSUE TITLE
Information in F3 screen flickering and duplicated 

### ISSUE THREAD

**Issue by bradwiggo** [sp614x/optifine#3502]
Occurs on preview 9 of 1.15.2. Can't see the flickering on the image but the lines that say "litematica" are the ones that are flickering, and they are also duplicated there should only be 2 lines not 10. Only the duplicates are flickering. 
![2020-03-05_16 16 51](https://user-images.githubusercontent.com/61841323/76001369-e8e03a00-5efc-11ea-8b1c-abc395b32da4.png)

**Comment by mrtomwolf** [comment]
For me as well.

**Comment by sp614x** [comment]
Should be redirected to OptiFabric: https://github.com/modmuss50/OptiFabric/issues
Fabric is not supported by OptiFine.
