### ISSUE TITLE
F3 screen and any other on screen text is grey when in spectator mode. 

### ISSUE THREAD

**Issue by bradwiggo** [sp614x/optifine#3503]
The F3 screen and any other text info (like chat or a scoreboard) will become grey if you go into spectator mode. 

Affects 

OptiFine 1.15.2 HD U G1 pre9
--

 
![2020-03-05_16 21 27](https://user-images.githubusercontent.com/61841323/76001820-981d1100-5efd-11ea-97ed-b88402093799.png)

**Comment by Shaynayna** [comment]
I am also having this problem with Optifabric. It also occurs when I am in /vanish, although it corrects itself when I have an item in my inventory, although unless the item is in my hand, the toolbar is darker than normal.

**Comment by sp614x** [comment]
Should be working in latest preview.
