### ISSUE TITLE
blocks and skins not showing up

### ISSUE THREAD

**Issue by RuthlessJailer** [sp614x/optifine#3506]
Whenever I go onto a server (any server), with OptiFine, skins and blocks do not load in.
OptiFine (pre9):
![2020-03-06_10 52 14](https://user-images.githubusercontent.com/57777932/76104788-956ff980-5f99-11ea-9c92-443d8fd53d19.png)
Vanilla:
![2020-03-06_10 57 54](https://user-images.githubusercontent.com/57777932/76104795-9a34ad80-5f99-11ea-8c93-5887b4515de0.png)
I have tried reloading chunks and textures; both do nothing.

**Comment by sp614x** [comment]
Can you post a F3 screenshot?

**Comment by realjackasterisk** [comment]
Assuming this is the 1.15.2 preview based on this:
> OptiFine (pre9)

**Comment by RuthlessJailer** [comment]
Sorry for the late response.
Yes 1.15.2
F3:
![2020-03-24_14 20 21](https://user-images.githubusercontent.com/57777932/77468066-0c4f2400-6ddb-11ea-87b1-b03dd6092d22.png)
Singeplayer worlds do not load at all.

**Comment by RuthlessJailer** [comment]
Installed pre13 and similar issues occur.
Singleplayer now loads:
![2020-04-04_15 08 07](https://user-images.githubusercontent.com/57777932/78460402-41366300-7686-11ea-9b59-4bf8b588020e.png)
With multiplayer, the same issue persists:
![2020-04-04_15 08 26](https://user-images.githubusercontent.com/57777932/78460406-501d1580-7686-11ea-970a-52e63abe4758.png)

**Comment by Zailer43** [comment]
I noticed that the chunks don't render until they **have loaded all the skins** (very rarely they load 2 or 4 chunks before the skins), **the skins take longer to load than normal.** Placing or breaking blocks renders that chunk (in case you do it on the edge of the chunk, the nearby ones are rendered) and if you try to reload them with f3+a seems to make it worse, the same goes for f3+t

Once in a while, when you get kicked for any reason, when you re-enter any server (or world), **you don't render chunks until you restart the game**, it has a characteristic touch that is that you never load the skins (but very few of those times when exiting and re-entering the server it is fixed)

(I am using the translator)

**Comment by cs127** [comment]
Still exists in 1.16.1 pre1 and pre2.

**Comment by Gavins38** [comment]
yep i get same issue!

**Comment by Gavins38** [comment]
on 1.15 optifine+

**Comment by sp614x** [comment]
Probably fixed with #4261
