### ISSUE TITLE
ANIM + menu panorama

### ISSUE THREAD

**Issue by SkaliberWasTaken** [sp614x/optifine#3508]
I recently tried applying ANIM to the menu panorama, and to my surprise, it worked, and it looks amazing, however, it's extremely slow, with the menu panorama blinking at 1-2FPS.

I tried massively reducing the size of the screenshots from 1024x1024 to a measly 256x256 but it was equally as bad, which leads me to believe that maybe something can be done about it? I've tried doing large scale ANIM things before, and had a similar outcome, but reducing the image size has generally helped the situation. Is the menu panorama a no-go, or is this something that could maybe be optimised in the future?

Thanks!

**Comment by BBftw** [comment]
I'd guess that it's something that would have to he fixed by sp614x. Have you tried reducing the number of frames?

**Comment by ZtereoHYPE** [comment]
I definitely have noticed that the panorama menu in minecraft is way heavier than it should be as my laptop’s fans start to spin up when I load it.

**Comment by SkaliberWasTaken** [comment]
@BBftw it was a test animation before a larger project consisting of only 2 frames per panorama image

**Comment by sp614x** [comment]
OptiFine version, standalone of Forge/Fabric?

**Comment by SkaliberWasTaken** [comment]
> OptiFine version, standalone of Forge/Fabric?

1.15.2 HD U G1 pre9
Standalone

**Comment by SkaliberWasTaken** [comment]
Having since encountered people running into the same issue, it seems the menu panorama is constantly loaded, and animating it takes up too much processing power - removing the animation from the menu panorama typically increases FPS by 300%.
