### ISSUE TITLE
graphics freeze when playing

### ISSUE THREAD

**Issue by sometimesiwander** [sp614x/optifine#3509]
i'm using the newest version of 1.12.2 optifine (F5) and the game's visuals freeze after a couple seconds of playing. i can still interact with the world (break blocks, walk, etc) and all sounds/music play as normal but i can't see anything that's going on. i have force minecraft to close because i cannot access any of the menus since the visuals are frozen. when i move the window is goes wonky (screenshots provided). this happens regardless of the version i'm using (i''ve tried it with several different 1.12.2 iterations). i am using optifine through forge since i'm also playing modded minecraft. optifine causes the game to freeze like this even when there are no other mods installed. my forge matches the forge that the optifine i'm currently using (F5) says is compatible.
![image](https://user-images.githubusercontent.com/61885931/76113823-a456ac00-5f99-11ea-966e-91ecc9c620fa.png)
![image](https://user-images.githubusercontent.com/61885931/76113851-b2a4c800-5f99-11ea-8fc9-d3aee0567a88.png)
![image](https://user-images.githubusercontent.com/61885931/76113931-e41d9380-5f99-11ea-9332-ab9caec7dc67.png)

**Comment by sp614x** [comment]
Why is the user view tilted to the right in the screenshot, some mod?
It may be a problem with the graphics driver when shaders are enabled.

**Comment by sometimesiwander** [comment]
i think i might have been moving when it froze? there's no mod i have that changes the fov

**Comment by KaiAF** [comment]
Is this still an issue?

**Comment by sometimesiwander** [comment]
i think i either managed to fix it/figured out what mod conflict was
causing it or just gave up and switched to a different version of
minecraft. it's been long enough that i don't remember, i'm sorry.
