### ISSUE TITLE
Crash on entering full screen for second time Linux

### ISSUE THREAD

**Issue by skrrtskrrtman** [sp614x/optifine#3512]
steps to reproduce:

1. have game start in full screen
2. load into server with a little bit of lag i.e zero tick farms
3. exit full screen with f11
4. click on different window
5. click back on Minecraft window
6. f11 to enter full screen again

[crash report](https://hastebin.com/xopexikeku.makefile)

this occurs only with Optifine and occurs using OpenJDK too.

specs:
OS: Manjaro Linux x86_64 
Kernel: 5.4.23-1-MANJARO 
Shell: bash 5.0.16 
Resolution: 1920x1080 
DE: GNOME 3.34.4 
WM: Mutter 
CPU: AMD Ryzen 5 1600 (12) @ 2.909GHz 
GPU: NVIDIA GeForce GTX 1060 6GB 
Memory: 7874MiB / 16028MiB
Java: `java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.241-b07, mixed mode)`

**Comment by sp614x** [comment]
The FPS limiter causes a crash in the graphics driver.
It could probably be fixed by setting "FPS Limit" to Max or enabling VSync.
Not related to OptiFine.
```
Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J 6308  org.lwjgl.system.JNI.invokeV(DJ)V (0 bytes) @ 0x00007f7805e855be [0x00007f7805e85520+0x9e]
==> J 17200 C1 com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(I)V (37 bytes) @ 0x00007f780679517c [0x00007f7806794fe0+0x19c]
J 18939 C1 dbn.d(Z)V (917 bytes) @ 0x00007f78077fcc1c [0x00007f78077f5040+0x7bdc]
j  dbn.d()V+41
j  net.minecraft.client.main.Main.main([Ljava/lang/String;)V+1305
v  ~StubRoutines::call_stub
j  sun.reflect.NativeMethodAccessorImpl.invoke0(Ljava/lang/reflect/Method;Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+0
j  sun.reflect.NativeMethodAccessorImpl.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+100
j  sun.reflect.DelegatingMethodAccessorImpl.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+6
j  java.lang.reflect.Method.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+56
j  net.minecraft.launchwrapper.Launch.launch([Ljava/lang/String;)V+661
j  net.minecraft.launchwrapper.Launch.main([Ljava/lang/String;)V+8
v  ~StubRoutines::call_stub
```
