### ISSUE TITLE
Show Capes causes lag.

### ISSUE THREAD

**Issue by SleepyCatGuy** [sp614x/optifine#3515]
When show capes is enabled in minecraft options it causes lag spikes sometimes minimal but very annoying to play or worse where every time you turn you get a huge lag spike. I think it also has to do with some mods like Journey Map that mod causes the game to lag a lot more.

### Versions:
Minecraft: 1.14.4

Forge: 28.2.0

Optifine: 1.14.4 HD U F5

### System:
CPU: Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz

GPU: Intel(R) HD Graphics 530

Memory: 8GB x2 (16GB)

### Minecraft Options:
JVM Args: -XX:+UseG1GC -Xmx6G -Xms6G -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M

**Comment by sp614x** [comment]
Single-player or multi-player?

**Comment by SleepyCatGuy** [comment]
Sorry for the very late replay. Single-player.

**Comment by KaiAF** [comment]
Is this still an issue?

**Comment by SleepyCatGuy** [comment]
I don't believe so. I have upgraded my PC since then and don't bother with capes anymore.
