### ISSUE TITLE
Optifine hides Main Menu splash text

### ISSUE THREAD

**Issue by Cobalt24** [sp614x/optifine#3517]
As the title says, when Optifine is installed there is no yellow splash text on the main menu. I am on 1.14.4, and using forge. Anyone else having the same issue?

**Comment by Boidushya** [comment]
No

**Comment by Regnander** [comment]
Do you have any other mods installed besides OF?

**Comment by Cobalt24** [comment]
> Do you have any other mods installed besides OF?

initially I did, but I removed every mod but OF, FML, and forge and it still happened. Haven't tested without forge yet.

**Comment by realjackasterisk** [comment]
Any resource packs? What version of Forge? What version of OptiFine?

**Comment by KaiAF** [comment]
No reply from the author, if you are still having this issue, let me know
