### ISSUE TITLE
[Website] Mirror page's download link blocked by DNT/adblocker due to CSS class name

### ISSUE THREAD

**Issue by mben42** [sp614x/optifine#3519]
Hi,

I have a problem that seems to be the same than #2888, but easy to fix: when using mirror page download with my DNT/adblocker (uBlock Origin) enabled, the download link doesn't appear. After using developers toolbox to rename "tableAds" CSS class into something without "ads" in it, it works without problem.

Steps to reproduce:
- Use Firefox 73.0.1
- Install uBlock Origin 1.25.0
- Go to optifine.net website, click downloads, then click on a "(mirror)" link

**Comment by WhiteWolfSV** [comment]
Turn of your Adblocker

**Comment by mben42** [comment]
> 
> 
> Turn of your Adblocker

Thanks Captain Obvious, I really couldn't think to do it alone!

I've taken time to reproduce the bug, not to open a ticket without a (very easy to implement) solution. Of course I have disabled it to download this time. However, many people use an adblocker anyway, and may just leave the website when then see it's doesn't work.

And you can note I said "DNT/adblocker", not only adblocker, because ads are actually not my main concern using this soft. If I don't really care about Optifine's usage of my date, it is annoying to disable it each time. There are other ways of supporting developpers, like buying capes, and I did it.

**Comment by sp614x** [comment]
Fixed.
