### ISSUE TITLE
cit question/issue

### ISSUE THREAD

**Issue by patrocinio-ptr** [sp614x/optifine#3520]
I’m not sure if this is just a matter of time to cit armor models(not items, those work perfectly) start working or if anything on the programming side is going to change, because on my custom resourcepack when I use the cit for an armor piece, it doesn’t work

**Comment by realjackasterisk** [comment]
What version of OptiFine? Link to resource pack?

**Comment by Sammyjoyplayz** [comment]
Hey I am working on stacking enchantments on tools and making them all show. How can I create a .Properties text doc that has multiple enchants. As an example, a folder for tools with BOTH silk touch and efficiency.

**Comment by sp614x** [comment]
Duplicate of #3276.
