### ISSUE TITLE
Biome blend slider says "add" instead of "and"

### ISSUE THREAD

**Issue by Creeper-Juice** [sp614x/optifine#3522]
![ooooooof](https://user-images.githubusercontent.com/61948724/76170495-6ea7f380-6150-11ea-88a5-1b2a02236579.png)

**Comment by Regnander** [comment]
There is a pull request to fix this, but it wasn't merged along with the others a few weeks ago: #3229

**Comment by sp614x** [comment]
Fixed, coming in next preview.
