### ISSUE TITLE
Click on Audio settings makes 2 click noises.

### ISSUE THREAD

**Issue by 20pero** [sp614x/optifine#3524]
as the title says, when i click on audio settings i hear click sound of the button twice. nothing special just annoying and makes you sometimes wonder if it actually clicked twice and changed one of the sliders.
happens only on that setting tho.

**Comment by Brottweiler** [comment]
It's because your cursor lands on a slider, and I think this is a vanilla bug.

**Comment by realjackasterisk** [comment]
what version is this in?

**Comment by 20pero** [comment]
OptiFine 1.15.2 HD U G1 pre9.

not sure if its in vanilla

**Comment by EleosOS** [comment]
Also happens on vanilla 1.14.4 and 1.15.2. Just as @Brottweiler described, this is no Optifine issue, holding down the mouse button and then releasing it makes it more clear.

**Comment by Brottweiler** [comment]
>not sure if its in vanilla

>Also happens on vanilla

**Always** when reporting bugs, make sure they don't happen on vanilla. Saves everyone a lot of time.

**Comment by 20pero** [comment]
unpon further investigation it appears that it also happens in the newest snapshot when click in on audio and chat settings button. and yea i will take note of that @Brottweiler.
these is no need to continue this "issue" anymore guess u can close it.

**Comment by Brottweiler** [comment]
You made the issue so you have the option to close it yourself. :)

**Comment by cs127** [comment]
this happens on vanilla, because when you click it, you also click the slider that appears. the same thing happens with chat settings
