### ISSUE TITLE
[1.15.2]Forge version？

### ISSUE THREAD

**Issue by EnterFor** [sp614x/optifine#3525]
Why is there no Forge version?
I really need this Mod!
I hope you're not angry. I'm just curious

Sorry, my English is poor. I'm Chinese

**Comment by WhiteWolfSV** [comment]
Plese join the discord server or check twitter where its clearly stated that OF is not compable with forge. This will save everyone time, you because you dont have to write this comment and wait for answers and us because we dont have to answer

**Comment by EnterFor** [comment]
I'm sorry, I mean maybe in the future?
