### ISSUE TITLE
[1.15 Bug] Unable to take screenshot

### ISSUE THREAD

**Issue by jonathan-durbin** [sp614x/optifine#3530]
Using OptiFine 1.15.2 HD U G1 pre9, I seem to be unable to take a screenshot. I'm using [multimc](https://multimc.org/), following the [instructions](https://github.com/MultiMC/MultiMC5/wiki/MultiMC-and-OptiFine) for installing optifine with fabric. 

I tried some basic troubleshooting, checked that vanilla 1.15 screenshots work, tried mapping to different keys on and off the `fn` row. The only difference as far as I can tell is that optifine is installed. 

It's possible that this is an issue with [optifabric](https://www.curseforge.com/minecraft/mc-mods/optifabric), which links fabric and optifine, and if it seems that way I'll contact the optifabric developer(s). Same goes for fabric. I doubt it's one of these, however, which is why I'm starting here. 

If anyone needs further information, feel free to ask.

**Comment by Donhorn** [comment]
Did you check the screnshots folder? I also use multimc and optifabric, and while I've had it not showing the screenshot text in game it is still saving the screenshots to the folder.

**Comment by jonathan-durbin** [comment]
There it is! The one thing I didn't try. Thanks.
