### ISSUE TITLE
[CEM] Full control over all mob heads

### ISSUE THREAD

**Issue by MushirMickeyJoe** [sp614x/optifine#3532]
I can easily add CEM for skeleton heads, but not for wither skeleton heads.
![image](https://user-images.githubusercontent.com/31923214/76559583-b8217700-649f-11ea-84fa-2125894dcbda.png)

Ideally each head should be its own editable entity in the game

**Comment by KaiAF** [comment]
This seems to be fixed. Let me know if you are still having any issues, please.
