### ISSUE TITLE
Optifine player models have 1 big flaw

### ISSUE THREAD

**Issue by NeedNot** [sp614x/optifine#3533]
This feature is so unknown but it's super cool well while I was making a model I dicoverd that the models still show if a player is invisible and first thing I thought was PvP, bedwars mostly 
If you see this video I made with my friend you can see just how much this could impact invis rushing
 https://youtu.be/WxyKICs2FEk please simply make the models go invisible so hackers can't take advantage of it

**Comment by ThePromisedLAN** [comment]
This ia not a feature of Optifine itself, that is an intentional effect in Hypixel's version of Bed Wars. Your armor can't be removed there and it wouldn't exactly do players much good to try and sneak around in full gear.

**Comment by BBftw** [comment]
@ThePromisedLAN it's not an armour model, it's a player model. It is an optifine thing

**Comment by NeedNot** [comment]
> @ThePromisedLAN it's not an armour model, it's a player model. It is an optifine thing

Although yes bedwars has a different kind of invisibility it works with vanilla invisibility too

**Comment by realjackasterisk** [comment]
not sure if CEM the right label for this issue, but there doesn't seem to be a label for custom player models. Given that CPM is supposed to be a sort of hidden, undocumented feature, it kinda makes sense. I'm amazed OptiFine allows you to put models on other players with this feature.

**Comment by ZenithRogue** [comment]
fixed per #5150
