### ISSUE TITLE
CEMs Bugged (Pre 9) 

### ISSUE THREAD

**Issue by Rixic** [sp614x/optifine#3534]
CEMs appear to be bugged in the latest previews, mobs will have their model overridden despite not being named and these models don't render correctly either.
![image](https://user-images.githubusercontent.com/24917910/76597079-90f69400-64f7-11ea-8246-2732ac6e48ff.png)

(RP being used to demo the probelm is TransMobifier)

Unless something changed from 1.14 with optifine in the way it handles CEMs this pack should work.

**Comment by sp614x** [comment]
Fixed in latest preview.
