### ISSUE TITLE
Aquaculture 2 and Optifine Rendering

### ISSUE THREAD

**Issue by DatrixTHLK** [sp614x/optifine#3538]
Hi, I seem to be getting a crash for Aquaculture 2 and this didn't crash before I put this mod into my mod list. Has to do with the Bobber item (rendering) in aquaculture and the crashlog is as follows: https://gist.github.com/DatrixTHLK/d57b93df878d5fdeda1735360de96ef2 Pre9

What I mean is that I didn't crash until I put optifine into my mod list.

Minecraft 1.15.2
Forge: 31.1.19
Optifine: HD_U_G1_pre9 (Preview)
Aquaculture 2: 2.0.9

**Comment by HiItsDevin** [comment]
Optifine currently doesn't support Forge in it's preview stages. Please wait until the full release, thank you.

**Comment by DatrixTHLK** [comment]
you're welcome

**Comment by realjackasterisk** [comment]
As stated above, OptiFine is not compatible with 1.15 Forge.
