### ISSUE TITLE
[1.15.2_pre10] Resource load failed / Block entity crash.

### ISSUE THREAD

**Issue by Quavelen** [sp614x/optifine#3540]
**Note:** I'm aware it's a development build, which is partly why I'm opening this issue - I hope that maybe I found a previously unknown issue with resource packs in the current version.

______

## Description of Issues

So, I've only encountered this once so far, and only with the ancient texture pack called 'Misa'. After enabling it, with its two patches for 1.15+, the loading bar disappears and all seems fine for a moment; I see the textures correctly applied ingame. Then after a second or two, the loading bar re-appears and it unloads the packs, and shows a "Resource load failed" toast in the top right corner.

A second issue I've encountered whilst enabling this same texture texture pack, is a crash regarding a null pointer exception for rendering a block entity.

It's also worth noting that this pack and its two patches work beautifully in vanilla. So I'm *mostly* certain it's an issue on OptiFine's end. Obviously there's a chance the pack is doing something that OptiFine doesn't support, but I want to be sure.

#### Resource load failure

1. Grab the three Misa patches from the official Discord's #pack-releases channel, [linked by Misa herself on her thread](https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/resource-packs/1223248-misas-realistic-texture-pack-updated-1jul13?comment=9233).
2. Enable them as shown and explained in the same channel. 
3. Watch as it enables briefly, and then fails.

#### Block entity crash

1. Follow step one above.
2. Place down a bell, or go near a bell.
3. Enable the patches with the bell on your screen, then watch as it crashes.

## OptiFine Version

The version in this report was initially `OptiFine_1.15.2_HD_U_G1_pre9`, however I've updated to `OptiFine_1.15.2_HD_U_G1_pre10` and confirmed it still occurs. As such, the log files and crash report have been updated as well.

## Installation Method
> *How did you install OptiFine? Did you use the included standalone installer, or did you drop the JAR file into your "mods" folder?*

The standalone installer was used; no other mods were being used.

## Log Files/Crash Reports
* Resource load failed: https://pastebin.com/mcuJ5vHP (latest.log file)
* Block entity crash: https://pastebin.com/3DHiLJqv (crash report)
  * Block entity crash: https://pastebin.com/zm3XRyKv (latest.log file)

<sup>*Note that despite the client complaining about missing classes from Forge, pre10 are not compatible with Forge and is thus not being launched with it. This note is for users who will make an assumption to the contrary regarding that.*</sup>

## F3 Debug Screenshot
> *Minecraft's built-in debug screen provides *a lot* of useful information, and should be included even if the issue is not something that can be captured in a still image.*

I mean, it's not exactly relevant in this situation, and the video I recorded has this displayed anyways. But, here:

![Debug menu](https://cdn.discordapp.com/attachments/689215119498018883/693290286805155902/javaw_28-03-2020_02-42-36.png)

## Prior Testing

> If you've installed standalone:
> - Does this happen in Vanilla without OptiFine?

As stated above, the texture pack functions flawlessly in Vanilla, without OptiFine.

## Additional Information

Here is a short video I recorded which showcases both above issues, and it functioning in vanilla: https://www.youtube.com/watch?v=Ju0JXr4KGN8

Hopefully this is helpful to sp614x, but if not, at least I gave it a shot.

**Comment by Quavelen** [comment]
Just confirmed both the resource load failure, and block entity crash continue to occur on pre10 in the same contexts as described and showcased above. I realise the move from pre9 to pre10 may have been entirely shader related, but I wanted to be certain.

**Comment by sp614x** [comment]
The problem is in `textures\entity\conduit\base.png.mcmeta`.
Because it exists, vanilla interprets `textures\entity\conduit\base.png` as an animation with sprite size 64x64 from image 64x128. This leads to problems later when OF adjusts the sprite size for the mipmap level, because OF doesn't expect the animation to be in horizontal format.
Without mcmeta the sprite size is 64x128 and it should work correctly.

**Comment by sp614x** [comment]
Because of this the conduit is rendered incorrectly:

![image](https://user-images.githubusercontent.com/16635441/78133212-527d3680-741e-11ea-8518-99aeb256315b.png)

**Comment by sp614x** [comment]
After the mcmeta crash is fixed the bell rendering also seems to work:

![image](https://user-images.githubusercontent.com/16635441/78133833-73925700-741f-11ea-9c5d-4eb3dd3370cf.png)

**Comment by sp614x** [comment]
Fixed, coming in pre13.

**Comment by Quavelen** [comment]
Thank you! I'm glad you figured out what was causing these two issues, and that you managed to resolve it. I've missed using Misa with Shaders, lol.
