### ISSUE TITLE
[1.15.2 G1 pre9] F3 screen is laggy / has low framerate

### ISSUE THREAD

**Issue by cs127** [sp614x/optifine#3541]
I was using pre9 with optifabric, and I realized that the numbers on the F3 screen (or maybe just the coordinates) update slowly, like their framerate is lower than what it's supposed to be.
It's not just fabric, I remember having the same problem without fabric, with like pre1, and I think pre7 or pre8 as well.

**Comment by sp614x** [comment]
OF reduces the F3 refresh speed so the fast changing text/numbers can be readable.
