### ISSUE TITLE
[1.15] Smooth FPS on Intel integrated graphics causes 0 FPS

### ISSUE THREAD

**Issue by proMan2020** [sp614x/optifine#3543]
The first time I used optifine was on 1.14.4 and the first launch was alright, but when I login the following day I was getting 0 FPS for 9 out of 10 seconds, even if I had the ESC menu open. But it resolved it self after a month or so. Now I have the same problem in 1.15.2. What to do?
And as a side question is using my dedicated GPU better then integrated. (My processor is intel i5 3210M and GPU is GT630M)

**Comment by sp614x** [comment]
Can you post a debug (F3) screenshot?

**Comment by proMan2020** [comment]
![B4BF297C-8A5F-4EA7-B073-F6E6302F2441](https://user-images.githubusercontent.com/62209600/77166920-84ada080-6ace-11ea-9ec4-11f01e11725a.jpeg)

**Comment by proMan2020** [comment]
You can just see the 0  
The issue seems to have resolved its self for the time being. I will send another photo here if the problem pops up again.

**Comment by proMan2020** [comment]
I have talked about this with devin on discord and I think a uploaded some better photos

**Comment by realjackasterisk** [comment]
Do you have "smooth FPS" enabled?

**Comment by proMan2020** [comment]
Yes

**Comment by proMan2020** [comment]
![IMG_0697](https://user-images.githubusercontent.com/62209600/77814494-fab39800-70ca-11ea-9e1c-9f55f0736f8c.jpeg)

**Comment by EroSennin12** [comment]
Me too.
![11](https://user-images.githubusercontent.com/62822181/77838693-70534e80-7133-11ea-9b98-5f08f7665317.png)

**Comment by TheJSHuA** [comment]
Pattern I've been noticing is that these bug reports are all coming from people with Intel HD integrated graphics, could be linked to the issue? Doesn't happen on my PC (with an RX 560), even with smooth FPS enabled.

**Comment by proMan2020** [comment]
But the thing is when I play with out optifine Minecraft uses GPU but with optifine it uses integrated

**Comment by TheJSHuA** [comment]
That's not an OptiFine issue, if you have an integrated graphics card and a dedicated graphics card you have to go to the GPU configuration and set up java to use the dedicated GPU.

**Comment by proMan2020** [comment]
Then why does it sometimes work flawlessly?
And I tried to make it work on GPU but optifine wouldn’t

**Comment by proMan2020** [comment]
And I think the problem was smooth fps because when I did turn it off the problem is no more
