### ISSUE TITLE
[1.15.2 pre 9]java.lang.NoSuchMethodError: com.mojang.blaze3d.platform.GLX.isUsingFBOs()Z

### ISSUE THREAD

**Issue by i9hdkill** [sp614x/optifine#3545]
Hi,
trying to use Optifine 1.15.2 pre 9 but it crashes with this error:
https://pastebin.com/XMX3bafu
Thats a custom modpack, but 1.14.4 F2 worked fine.
version.json
```
{
  "id": "1.15.2-OptiFine_HD_U_G1",
  "inheritsFrom": "1.15.2",
  "time":"2020-01-17T10:03:52+00:00",
  "releaseTime": "2020-01-17T10:03:52+00:00",
  "type": "release",
  "libraries": [
    {
      "name": "optifine:OptiFine:1.15.2_HD_U_G1"
    },
    {
      "name": "optifine:launchwrapper-of:2.1"
    }
  ],
  "mainClass": "net.minecraft.launchwrapper.Launch",
  "minimumLauncherVersion": "21",
  "arguments": {
    "game": [
      "--tweakClass",
      "optifine.OptiFineTweaker"
    ]
  }
}
```

1080ti - driver from 15.03.2020
128gb ram
i9 9900k

**Comment by goodideagiver** [comment]
Optifine 1.15.2 does not support forge yet read the changelog

**Comment by i9hdkill** [comment]
I am not using Forge, it's vanilla mc

**Comment by BBftw** [comment]
you said you're using a custom modpack... anyway, im no expert but try disabling VBOs in optionsof.txt in your game's installation folder.

**Comment by i9hdkill** [comment]
VBO != FBO. That different types of buffers. Both options and optionof are clean. 
Everything that is not vanilla is modded for me. Thats why I said modpack. Still, reading the logs before posting is always a good thing

**Comment by BBftw** [comment]
oh whoops, I misread. sorry about that

**Comment by sp614x** [comment]
Not compatible with forge yet.

**Comment by i9hdkill** [comment]
> Not compatible with forge yet.

Not using Forge

**Comment by sachk** [comment]
> > Not compatible with forge yet.
> 
> Not using Forge

I had this exact issue when using the installer jar from the website directly and not the one you get from using the extract button in the installer.

**Comment by Brittank88** [comment]
Can confirm that without any installation of Forge present I am also receiving this error. I do not have weak hardware either (GeForce RTX 2070 Super GPU & Ryzen 9 3900X CPU).

**Comment by ca1f** [comment]
I'm seeing the same stacktrace when I try to launch vanilla Minecraft without forge from MultiMC on Linux with the proprietary nvidia driver. Renderer: GeForce GTX 960/PCIe/SSE2 and AMD FX6300. The hardware is running Minecraft and other OpenGL and Vulkan Games just fine, so I don't think it's an underlying problem with the Hardware or the operating system.

**Comment by i9hdkill** [comment]
Ah, think using the optifine.OptiFineTweaker class to load the mod is not supported yet(what Forge uses)
