### ISSUE TITLE
1.12.2 | Low FPS from Chunk Animator and Shadows

### ISSUE THREAD

**Issue by Vatruvius** [sp614x/optifine#3546]
After doing some testing and isolating, I discovered the reason for the low FPS I was experiencing is due to the Optifine shadow settings paired with the Chunk Animator mod. My system is more than capable of rendering the game with max shadow distance and quality, however, Chunk Animator causes some problems. I assume this is due to the chunks animating into position requiring shadows and lighting to be rendered over and over every time the chunk moves. Is this a problem that can be resolved in Optifine/Chunk Animator or is this an issue that cannot be resolved? Either there will be low shadow quality/distance or no animated chunks?

**Comment by BBftw** [comment]
What shader are you using

**Comment by Vatruvius** [comment]
Sildur's Enhanced Default: https://sildurs-shaders.github.io/downloads/

I can try a different shader and see if there is a difference, but I suspect that this issue has to do with rendering shadows on the animating chunks irregardless of what shader is being used.

**Comment by Vatruvius** [comment]
I take it back. For whatever reason my computer/NVIDIA reset my designation for the program to run using High-Performance GPU to Auto meaning it was using my integrated graphics on my CPU. Switching it back solved the FPS issue significantly. Obviously the game lags when flying around in creative, however, after initially spawning into the world and just playing as I would normally there is no issue.
