### ISSUE TITLE
[1.14] IE font render breaks with Optifine

### ISSUE THREAD

**Issue by malte0811** [sp614x/optifine#3548]
IE version: BluSunrize/ImmersiveEngineering@b9679e5835ef7e2157f32f12e293a9e6b4540eaf (latest commit that doesn't require Forge 1.14.4-28.2.2+, which I can't get to work with OF)  
Optifine version: 1.14.4 HD U F5  
Forge version: 1.14.4-28.2.0  
Log: https://gist.github.com/malte0811/c22b8d427c37f4e297909f658a2e2f5c

I'm working on porting IE to 1.14 and ran into this issue in some early tests: Some IE items use a [custom font render](https://github.com/BluSunrize/ImmersiveEngineering/blob/b9679e5835ef7e2157f32f12e293a9e6b4540eaf/src/main/java/blusunrize/immersiveengineering/client/font/IEFontRender.java) to render the tooltips ([Example: Block items](https://github.com/BluSunrize/ImmersiveEngineering/blob/b9679e5835ef7e2157f32f12e293a9e6b4540eaf/src/main/java/blusunrize/immersiveengineering/common/blocks/BlockItemIE.java#L56-L61)). This works fine with just Forge. With Optifine this happens as soon as a tooltip using the custom render has been rendered:

Items using the default render:  
![bug-2](https://user-images.githubusercontent.com/10406104/76937607-66407d00-68f5-11ea-851b-0274441007ae.png)  
and sometimes  
![2020-03-18_08 52 47](https://user-images.githubusercontent.com/10406104/76937894-eebf1d80-68f5-11ea-8c99-8137bbe2b6cd.png)

Items using the IE font render:  
![bug-1](https://user-images.githubusercontent.com/10406104/76937634-735d6c00-68f5-11ea-8144-b2043986aeb5.png)

Reloading resources makes things even weirder. It fixes the bug until an item uses the IE render, then the vanilla render works correctly, but the IE render breaks completely:
![2020-03-18_08 55 29](https://user-images.githubusercontent.com/10406104/76938093-4f4e5a80-68f6-11ea-8556-684df406c4eb.png)

I have no idea where to even start with debugging this, and I have no idea whether it's a bug on the IE side or on the OF side.

**Comment by MorePortal** [comment]
Probably connected:
[crash](https://pastebin.com/Ya2C8Gn4)
I'm using Optifine HD U F4 with OptiForge&MixinBootstrap and forge 28.2.6
This happend after some time when I changed language

**Comment by malte0811** [comment]
Fixed in BluSunrize/ImmersiveEngineering@8bf94364decfd46e9f7c8bc38479f7916f2cbd7d
