### ISSUE TITLE
failed to start

### ISSUE THREAD

**Issue by JeshuaFlaco** [sp614x/optifine#3549]
Error is displayed when loading the game

OptiFine 1.15.2 HD U G1 pre9

**The game crashed whilst initializing game
Error: java.lang.IllegalStateException: No renderer registered for guardvillagers:guard**

[crash-2020-03-18_17.44.02-client.txt](https://github.com/sp614x/optifine/files/4351994/crash-2020-03-18_17.44.02-client.txt)

**Comment by HiItsDevin** [comment]
Optifine 1.15.2 does not support Forge yet.
