### ISSUE TITLE
Optifine uses integrated graphics and minecraft takes up all my gpu

### ISSUE THREAD

**Issue by entity493** [sp614x/optifine#3550]
so basically i opened minecraft after a while of not playing and my computer was actually laggy so I opened task manager and minecraft was using %7 of my cpu and %98 of my gpu i went to shaders and it was using my integrated graphics so what im thinking is somehow optifine and minecraft switched hardware

things i have tried:
I always have smooth fix off
I have set minecraft to run with my gpu and it still didn't do anything

**Comment by entity493** [comment]
A little more info
![2020-03-18_22 40 08](https://user-images.githubusercontent.com/24880594/77026222-8dd12d00-6969-11ea-88a8-5484f07c9609.png)
Client: Badlion

**Comment by Burrata-ex** [comment]
I had a similar if not the same problem, but it's not an optifine issue. The problem I think comes from the fact that the exe running when you play is the java runtime and not a Minecraft executable, so changing your preference only for Minecraft in your Nvidia Control panel (I'm assuming), is not going to actually change the GPU used to run Minecraft. For some reason, Minecraft prefers running on integrated graphics, so what I did to circumvent this I set the default GPU to my Nvidia for all processes in the Global Settings.

**Comment by entity493** [comment]
I'm on a laptop so I had to do that in my graphics settings and nothing changed

**Comment by sp614x** [comment]
If you have 2 GPUs (integrated and dedicated) you have to tell the graphics driver which one to use for MC. This is usually in the graphics control panel.
Not related to OptiFine.

**Comment by abodihagag2007** [comment]
I have the same issue except that I have an amd radeon r7 m256 as my dedicated gpu

**Comment by master-awesome** [comment]
I've made a video documenting this problem and the fix, follow the steps and you should be able to fix it.
Video Link:  https://www.youtube.com/watch?v=Wts8-30ygyw
