### ISSUE TITLE
Optifine Source

### ISSUE THREAD

**Issue by D9ED** [sp614x/optifine#3551]
Hello, my name is Adam, and I am a developer of a Minecraft client and would like to request to use your the source of your mod OptiFine so that our client can compete with clients such as Badlion and Lunar. We are hoping to give our users the best experience with this client and giving them a good first impression of the client by allowing them to have the best-optimized Minecraft experience. We would like to use this mod in particular, because it is the most popular Minecraft mod out there, alone. I know that since this is so popular, I figured I should ask for your permission, that way we do not go into legal action at a later date. We'd like to provide the top-tier experience for our users, as this is a huge deal for the client itself. Without OptiFine, this client would not function properly, and would most certainly cause issues with our users, who love OptiFine.We hope you oblige and allow us to use your client. We will list the name of it, and will not take ANY credit of the addition of OptiFine for our client.

Your's Truly,
Adam - Head Of Development and Owner of Obsidium Client

Contact: yt.d9ed@gmail.com

Why am I posting this here: It has been have a year since I sent an email and you have not responded (sorry if this sounds rude)

**Comment by ThePieGuyWill** [comment]
_sigh_ you have got to be kidding me rn -

First of - If sp was to share the code of OptiFIne it would be violating the terms of service set by Mojang

Second of all - sp doesn't even give it to you, not even in a million years or for money, sp doesn't want to share it, it is his and it is proud to be his

Finally - Most people tend to steal code off people mods and whatnot and take credit for themselves

So, there ya go! You will never have any code from OptiFine EVER!

**Comment by ThePieGuyWill** [comment]
Also, you just may as well download it and put it into your mod

**Comment by entity493** [comment]
Well what happened with badlion client?

**Comment by entity493** [comment]
Nevermind

**Comment by asbyth** [comment]
nah bro reclose 👎

**Comment by HiItsDevin** [comment]
please reclose this.

**Comment by D9ED** [comment]
Here it seems sp614x does not care about people decompiling his source:
https://github.com/sp614x/optifine/issues/1106

**Comment by asbyth** [comment]
> Here it seems sp614x does not care about people decompiling his source:
> #1106

decompiling it and viewing it is entirely different as opposed to physically using it without written permission.

**Comment by D9ED** [comment]
How come QClient was able to get his source and permission then? The creator isn't even known.

**Comment by D9ED** [comment]
Why was this closed

**Comment by asbyth** [comment]
> Why was this closed

because
optifine isnt being open sourced
and qclient likely took it without permission

please stop reopening this and give up, clients should die out anyway

**Comment by Studio528-real** [comment]
> First of - If sp was to share the code of OptiFIne it would be violating the terms of service set by Mojang
> 
> Second of all - sp doesn't even give it to you, not even in a million years or for money, sp doesn't want to share it, it is his and it is proud to be his
> 
> Finally - Most people tend to steal code off people mods and whatnot and take credit for themselves
> 
> So, there ya go! You will never have any code from OptiFine EVER!

The project is Closed Source and will continue to be closed source.

**Comment by D9ED** [comment]
The owner of QClient said he kindly asked with a few paragraphs

**Comment by D9ED** [comment]
I would also like to know how badlion & luner have it

**Comment by asbyth** [comment]
https://shutplea.se/

**Comment by D9ED** [comment]
@asbyth @Studio528-real

**Comment by Studio528-real** [comment]
As said multiple times, you will not be getting the source code, OptiFine is closed source, and will continue to be closed source.
