### ISSUE TITLE
View bobbing and shaders make things underwater bob as well

### ISSUE THREAD

**Issue by ssarinn** [sp614x/optifine#3552]

**Comment by entity493** [comment]
Maybe try using another shaderpack

**Comment by Gappysona** [comment]
What development build is this?

**Comment by ZtereoHYPE** [comment]
Pre9B is a DEVELOPMENT build, meant for SHADER DEVELOPERS. I would think that sp614x would appreciate if you didn't report bugs that are going to be fixed in the near future because they are obvious bugs.

**Comment by sp614x** [comment]
Pre9b is a dev build with many broken things.
Do not report issues for it.
