### ISSUE TITLE
1.15.2 Pre9B shader glitches

### ISSUE THREAD

**Issue by Yeetussss** [sp614x/optifine#3553]
The following issues only arise when I move, no matter what shader I'm using (with the internal shaders being an exception):

- Reflections acting up (moving, getting stretched/compressed, zooming in, etc.

- Strange triangles forming on the ceiling with blocklight (some light, some dark)

- Weird ghosting and noise with Chocapic Extreme shader (don't know if it's an Optifine problem or a shader problem so I added it)

**Comment by Gappysona** [comment]
No.

Pre9B is a **DEVELOPMENT** build, meant for **SHADER DEVELOPERS**. I would think that sp614x would appreciate if you didn't report bugs that are going to be fixed in the near future because **they are obvious bugs**.

**Comment by MrCheeze446** [comment]
These issues are obvious, and they are known. As stated before this build is generally meant for **SHADER DEVELOPERS**
