### ISSUE TITLE
visual glitches on "The 1.12.2 Pack"

### ISSUE THREAD

**Issue by sirNugg3ts** [sp614x/optifine#3556]
I'm having these weird fluid-like artifacts on the 1.12.2 pack

![2020-03-20_13 55 02](https://user-images.githubusercontent.com/28486181/77171708-c5002500-6ab4-11ea-9c1a-a6a382bf086d.png)

Using OptiFine_1.12.2_HD_U_F5Ja
Java: 1.8 64bits
Allocated RAM: 5GB

**Comment by realjackasterisk** [comment]
what is "the 1.12.2 pack"?? what other mods do you have installed

**Comment by sirNugg3ts** [comment]
It's a technic modpack.
Here's the [list of mods](https://www.technicpack.net/modpack/the-1122-pack.1406454/mods)

**Comment by sp614x** [comment]
Most probably a conflict with one of the installed mods.
You can find the conflicting mod by splitting the mods in two and testing. Keep the half that has the problem and repeat until there is only one mod left.
