### ISSUE TITLE
Parsing Multiple Uniform Declarations

### ISSUE THREAD

**Issue by jcm2606** [sp614x/optifine#3558]
I've noticed that Optifine allows certain uniforms to be declared together within the same statement, such as `uniform mat4 gbufferModelView, gbufferModelViewInverse;`, but not others.

Specifically, I've noticed that all but the shadow buffer uniforms can be declared together within the same statement.

I think it'd be beneficial to relax Optifine's parsing of uniform declarations, to allow any set of uniforms to be declared together within the same statement.

**Comment by sp614x** [comment]
The OptiFine configuration parser recognizes only one uniform per line, similar to attribute, const, etc.
It would be too complicated to extend it to recognize all valid ways to define uniforms that are recognized by GLSL.
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.txt#L357
