### ISSUE TITLE
Support OpenGL 4.0 in OptiFine 1.15.2

### ISSUE THREAD

**Issue by WantaSanchez** [sp614x/optifine#3559]
[latest.log](https://github.com/sp614x/optifine/files/4362630/latest.log)
Hey. I make my Minecraft installers in which the game is launched using the command line for complete control over the launch arguments. On the game version 1.15, OptiFine is update the graphics processing system (sorry if I could misunderstand this) and requires the OpenGL version not lower than 4.4 but my video adapter (Inte HD Graphics 4000) only supports 4.0. The funny thing is that in the licensed launcher, the game with your mod correctly starts up, but I can not find the differences in the launcher launch line. What do you say about this? How to I can start This version on my graphics card?

**Comment by realjackasterisk** [comment]
Might be worth noting that [*Vanilla* 1.15 lists OpenGL 4.4 as a minimum system requirement.](https://minecraft.gamepedia.com/Java_Edition_hardware_requirements)

**Comment by sp614x** [comment]
The class `com.mojang.blaze3d.platform.GLX` is not correctly patched.
Look in the profile that OptiFine installer creates for the vanilla launcher to see the needed libraries and arguments.
This has nothing to do with OpenGL versions.
