### ISSUE TITLE
[1.15.2] On Fabric mods Terrestria and Traverse, the game crashes when initializing.

### ISSUE THREAD

**Issue by TheJSHuA** [sp614x/optifine#3563]
This doesn't appear to be an issue with OptiFabric, as OptiFabric throws no error. On both Terrestria and Traverse, when they are initializing it causes an error which makes the game crash.
attatched are crash logs of both Terrestria's error and traverse's error. Both errors are called on the exact same java file, at the exact same line. Occurs with every preview so far.
[terrestria-crash.txt](https://github.com/sp614x/optifine/files/4366667/terrestria-crash.txt)
[traverse-crash.txt](https://github.com/sp614x/optifine/files/4366668/traverse-crash.txt)
edit: attached incorrect report files, fixed now

**Comment by sp614x** [comment]
The log files have no crash info inside.
Can you post the crash reports?

**Comment by TheJSHuA** [comment]
yes, just did so when editing

**Comment by TheJSHuA** [comment]
Closing as was fixed by OptiFabric.
