### ISSUE TITLE
Minecraft 1.5.2 moded  Valhelsia 2 V.2.1.3a

### ISSUE THREAD

**Issue by BenCG3** [sp614x/optifine#3566]
Bug initialising on lunch :
With the last version of optifine : OptiFine 1.15.2 HD U G1 pre9
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 3/23/20 2:46 PM
Description: Initializing game

java.lang.IllegalStateException: No renderer registered for doggytalents:dog
	at net.minecraft.client.renderer.entity.EntityRendererManager.<init>(EntityRendererManager.java:222) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins_client.json:MixinEntityRenderDispatcher,pl:mixin:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:425) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:customwindowtitle:CustomWindowTitle,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins_client.json:block_manipulation/MixinMinecraftClient_B,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins_client.json:MixinMinecraftClient,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:166) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.15.2-31.1.27.jar:31.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$464/1344345219.call(Unknown Source) [forge-1.15.2-31.1.27.jar:31.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.0.0-milestone.4.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.0.0-milestone.4.jar:?] {re:classloading}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.renderer.entity.EntityRendererManager.<init>(EntityRendererManager.java:222)
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:425)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$464/1344345219.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2778439104 bytes (2649 MB) / 3736076288 bytes (3563 MB) up to 11453595648 bytes (10923 MB)
	CPUs: 8
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx12288m -Xms256m -XX:PermSize=256m
	ModLauncher: 5.0.0-milestone.4+67+b1a340b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.0.0-milestone.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.1.27.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.27.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.0.4-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.1.27.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.27.jar runtimedistcleaner PLUGINSERVICE 
		/preview_OptiFine_1.15.2_HD_U_G1_pre9h.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.15.2-31.1.27.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.2.jar mixinbootstrap TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.2.jar mixin PLUGINSERVICE 
		/MixinBootstrap-1.0.2.jar mixinbootstrap PLUGINSERVICE 
	FML: 31.1
	Forge: net.minecraftforge:31.1.27
	FML Language Providers: 
		javafml@31.1
		minecraft@1
		kotlinfml@1.5.0
	Mod List: 
		NetherPortalFix_1.15.2-6.0.0.jar NetherPortalFix {netherportalfix@6.0.0 COMMON_SETUP}
		DoggyTalents-1.15.2-1.15.2.3.jar Doggy Talents {doggytalents@1.15.2.3 COMMON_SETUP}
		mcw-windows-1.0.0-mc1.15.1_1.15.2.jar Macaw's Windows {mcwwindows@1.0.0 COMMON_SETUP}
		SilentMechanisms-1.15.2-0.7.0+50.jar Silent's Mechanisms {silents_mechanisms@0.7.0+50 COMMON_SETUP}
		KleeSlabs_1.15.2-8.0.0.jar KleeSlabs {kleeslabs@8.0.0 COMMON_SETUP}
		essentials-1.15.2-2.7.0.jar Essentials {essentials@1.15.2-2.7.0 COMMON_SETUP}
		TerraForged-1.15.2-0.0.9.jar TerraForged {terraforged@0.0.9 COMMON_SETUP}
		BetterTitleScreen-1.15.2-1.9.jar Better Title Screen {bettertitlescreen@1.15.2-1.9 COMMON_SETUP}
		XaerosWorldMap_1.5.6_Forge_1.15.2.jar Xaero's World Map {xaeroworldmap@1.5.6 COMMON_SETUP}
		CookingForBlockheads_1.15.2-8.0.1.jar Cooking for Blockheads {cookingforblockheads@8.0.1 COMMON_SETUP}
		Controlling-6.1.1.jar Controlling {controlling@6.1.1 COMMON_SETUP}
		ReAuth-1.14-3.8.0.jar ReAuth {reauth@3.8.0 COMMON_SETUP}
		Placebo-1.15.2-3.0.2.jar Placebo {placebo@3.0.2 COMMON_SETUP}
		globaldatapack-1.15.2-1.3.jar Dark Roleplay - Global Datapacks {globaldatapack@1.15.2-0.1.0 COMMON_SETUP}
		Powah-1.15.2-1.1.10.jar Powah {powah@1.1.10 COMMON_SETUP}
		MutantBeasts-1.15.2-1.0.4.jar Mutant Beasts {mutantbeasts@1.15.2-1.0.4 COMMON_SETUP}
		Bookshelf-1.15.2-5.1.4.jar Bookshelf {bookshelf@5.1.4 COMMON_SETUP}
		u_team_core-1.15.2-2.11.0.156.jar U Team Core {uteamcore@2.11.0.156 COMMON_SETUP}
		randompatches-1.15.2-1.21.1.1.jar RandomPatches {randompatches@1.15.2-1.21.1.1 COMMON_SETUP}
		DarkUtilities-1.15.2-3.0.1.jar Dark Utilities {darkutils@3.0.1 COMMON_SETUP}
		Apotheosis-1.15.2-3.0.7.jar Apotheosis {apotheosis@3.0.7 COMMON_SETUP}
		ProgressiveBosses-2.1.4-mc1.15.2.jar Progressive Bosses {progressivebosses@2.1.4-mc1.15.2 COMMON_SETUP}
		Morpheus-1.15.2-4.2.50.jar Morpheus {morpheus@version COMMON_SETUP}
		MekanismGenerators-1.15.2-9.9.16.408.jar Mekanism: Generators {mekanismgenerators@9.9.16 COMMON_SETUP}
		Hwyla-forge-1.10.8-B72_1.15.2.jar Waila {waila@version COMMON_SETUP}
		refinedstorage-1.8.1.jar Refined Storage {refinedstorage@1.8.1 COMMON_SETUP}
		corpse-1.15.2-1.0.2.jar Corpse {corpse@1.15.2-1.0.2 COMMON_SETUP}
		mcw-bridges-1.0.4fix-mc1.15.2.jar Macaw's Bridges {mcwbridges@1.0.4 COMMON_SETUP}
		lightestlampsmod-3.3.0.jar Lightest Lamps {lightestlamp@3.3.0 COMMON_SETUP}
		industrial-foregoing-1.15.2-2.2.2-28d4a81.jar Industrial Foregoing {industrialforegoing@2.2.2 COMMON_SETUP}
		useful_backpacks-1.15.2-1.9.4.63.jar Useful Backpacks {usefulbackpacks@1.9.4.63 COMMON_SETUP}
		torchmaster-2.1.1-rc0.jar Torchmaster {torchmaster@2.1.1-rc0 COMMON_SETUP}
		embellishcraft-1.15.2-2.0.0.0.jar EmbellishCraft {embellishcraft@1.15.2-2.0.0.0 COMMON_SETUP}
		AmbientSounds_v3.0.19_mc1.15.2.jar Ambient Sounds {ambientsounds@3.0.3 COMMON_SETUP}
		BiomesOPlenty-1.15.2-10.0.0.352-universal.jar Biomes O' Plenty {biomesoplenty@1.15.2-10.0.0.349 COMMON_SETUP}
		phosphor-mc1.15.2-forge-0.4.2-rc2.jar Phosphor {phosphor@0.4.2-rc2 COMMON_SETUP}
		Blur-1.1.0-1.jar Blur {blur@1.1.0-1 COMMON_SETUP}
		valhelsia_structures-15.0.2a.jar Valhelsia Structures {valhelsia_structures@15.0.2a COMMON_SETUP}
		Lollipop-1.15.2-1.0.12.jar Lollipop {lollipop@1.0.12 COMMON_SETUP}
		SilentGear-1.15.2-1.5.4+79.jar Silent Gear {silentgear@1.5.4+79 COMMON_SETUP}
		simplefarming-1.15.2-1.2.7.jar Simple Farming {simplefarming@1.15.2-1.2.7 COMMON_SETUP}
		SolarFluxReborn-1.15.2-15.0.0.jar Solar Flux Reborn {solarflux@15.0.0 COMMON_SETUP}
		curios-FORGE-1.15.2-2.0.2.jar Curios API {curios@FORGE-1.15.2-2.0.2 COMMON_SETUP}
		extlights-2.0.jar Extended Lights {extlights@2.0 COMMON_SETUP}
		ClothConfig2-2.0.jar Cloth Config Forge v2 API {cloth-config2@2.0 COMMON_SETUP}
		libnonymous-1.15.2-1.1.1.5.jar Libnonymous {libnonymous@1.1.1.5 COMMON_SETUP}
		elevatorid-1.15.2-1.7.0.jar Elevator Mod {elevatorid@1.15.2-1.7.0 COMMON_SETUP}
		noRecipeBook_v1.5.2formc1.15.2.jar No Recipe Book {norecipebook@1.5.2 COMMON_SETUP}
		MekanismTools-1.15.2-9.9.16.408.jar Mekanism: Tools {mekanismtools@9.9.16 COMMON_SETUP}
		mcw-roofs-1.0.2-mc1.15.2_1.15.1.jar Macaw's Roofs {mcwroofs@1.0.2 COMMON_SETUP}
		furniture-7.0.0-pre16-1.15.1.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre16 COMMON_SETUP}
		curiouselytra-FORGE-1.15.2-2.0.jar Curious Elytra {curiouselytra@FORGE-1.15.2-2.0 COMMON_SETUP}
		cc-tweaked-1.15.2-1.86.2.jar CC: Tweaked {computercraft@1.86.2 COMMON_SETUP}
		AI-Improvements-1.15.2-0.3.0.jar AI-Improvements {aiimprovements@0.3.0 COMMON_SETUP}
		mcw-furnitures-1.0.0-mc1.15.2.jar Macaw's Furniture {mcwfurnitures@1.0.0 COMMON_SETUP}
		cherishedworlds-FORGE-1.15.2-3.0.jar Cherished Worlds {cherishedworlds@FORGE-1.15.2-3.0 COMMON_SETUP}
		CustomWindowTitle-1.15.2-v1.0.0.jar Custom Window Title {customwindowtitle@1.0.0 COMMON_SETUP}
		CraftPresence-1.15.2-1.6.1.jar CraftPresence {craftpresence@property(class java.lang.String, provider(?)) COMMON_SETUP}
		inventorysorter-1.15.2-17.0.0.jar Simple Inventory Sorter {inventorysorter@17.0.0 COMMON_SETUP}
		TrashSlot_1.15.2-11.0.0.jar TrashSlot {trashslot@11.0.0 COMMON_SETUP}
		torchslabmod-1.15.1_v1.5.jar Torch Slab Mod {torchslabmod@1.5.0 COMMON_SETUP}
		EquipmentTooltips-1.15.2-1.4.0+11.jar Equipment Tooltips {equipmenttooltips@1.4.0+11 COMMON_SETUP}
		mining-helmet-1.15.2-1.0.7.jar Mining Helmet {mining_helmet@1.0.7 COMMON_SETUP}
		jei-1.15.2-6.0.0.2.jar Just Enough Items {jei@6.0.0.2 COMMON_SETUP}
		buzzierbees-1.3.jar Buzzier Bees {buzzierbees@1.3 COMMON_SETUP}
		AttributeFix-1.15.2-7.0.1.jar AttributeFix {attributefix@7.0.1 COMMON_SETUP}
		Mekanism-1.15.2-9.9.16.408.jar Mekanism {mekanism@9.9.16 COMMON_SETUP}
		caelus-FORGE-1.15.2-2.0-beta1.jar Caelus API {caelus@FORGE-1.15.2-2.0-beta1 COMMON_SETUP}
		reap-1.12.2.jar Reap Mod {reap@1.12.2 COMMON_SETUP}
		Waystones_1.15.2-6.0.1.jar Waystones {waystones@6.0.1 COMMON_SETUP}
		Clumps-5.0.2.jar Clumps {clumps@5.0.2 COMMON_SETUP}
		LightOverlay-4.3.jar Light Overlay Forge {lightoverlay-forge@4.3 COMMON_SETUP}
		comforts-FORGE-1.15.2-2.0.jar Comforts {comforts@FORGE-1.15.2-2.0 COMMON_SETUP}
		NaturesCompass-1.15.2-1.8.5.jar Nature's Compass {naturescompass@1.15.2-1.8.5 COMMON_SETUP}
		FruitTrees-1.15.2-1.1.6.jar Fruit Trees {fruittrees@1.1.6 COMMON_SETUP}
		Kiwi-1.15.2-2.6.5.jar Kiwi {kiwi@2.6.5 COMMON_SETUP}
		SimpleStorageNetwork-1.15.2-0.3.1.jar Simple Storage Network {storagenetwork@1.15.2-0.3.1 COMMON_SETUP}
		SereneSeasons-1.15.2-3.0.0.68-universal.jar Serene Seasons {sereneseasons@1.15.2-3.0.0.68 COMMON_SETUP}
		decorative_blocks-6d.jar Decorative Blocks {decorative_blocks@1.6 COMMON_SETUP}
		BotanyPots-1.15.2-2.0.4.jar BotanyPots {botanypots@2.0.4 COMMON_SETUP}
		BonsaiTrees-2.1.2.6.jar Bonsai Trees 2 {bonsaitrees2@2.1.2.6 COMMON_SETUP}
		mcjtylib-1.15-4.0.3-alpha.jar McJtyLib {mcjtylib@1.15-4.0.3-alpha COMMON_SETUP}
		rftoolsbase-1.15-1.0.1-alpha.jar RFToolsBase {rftoolsbase@1.15-1.0.1-alpha COMMON_SETUP}
		xnet-1.15-2.0.2-alpha.jar XNet {xnet@1.15-2.0.2-alpha COMMON_SETUP}
		rftoolsstorage-1.15-1.0.3-alpha.jar RFToolsStorage {rftoolsstorage@1.15-1.0.3-alpha COMMON_SETUP}
		mapperbase-1.15.2-1.0.0.0.jar Mapper Base {mapperbase@1.15.2-1.0.0.0 COMMON_SETUP}
		ToastControl-1.15.2-3.0.1.jar Toast Control {toastcontrol@3.0.1 COMMON_SETUP}
		immersive-portals-0.8(forMc1.15withForge).jar Immersive Portals {immersive_portals@0.8 COMMON_SETUP}
		rftoolspower-1.15-2.0.1-alpha.jar RFToolsPower {rftoolspower@1.15-2.0.1-alpha COMMON_SETUP}
		extradisks-1.15.1-1.2.jar Extra Disks {extradisks@1.15.1-1.2 COMMON_SETUP}
		forge-1.15.2-31.1.27-universal.jar Forge {forge@31.1.27 COMMON_SETUP}
		Bountiful-3.0.0-1.15.2.jar Bountiful {bountiful@3.0.0-1.15.2 COMMON_SETUP}
		ironchest-1.15.2-10.0.3.jar Iron Chests {ironchest@1.15.2-10.0.1 COMMON_SETUP}
		CraftingTweaks_1.15.1-11.0.0.jar Crafting Tweaks {craftingtweaks@11.0.0 COMMON_SETUP}
		forge-1.15.2-31.1.27-client.jar Minecraft {minecraft@1.15.2 COMMON_SETUP}
		cofh_core-1.15.2-0.3.2b.jar CoFH Core {cofh_core@0.3.2b COMMON_SETUP}
		ensorcellation-1.15.2-0.3.0b.jar Ensorcellation {ensorcellation@0.3.0b COMMON_SETUP}
		rftoolsutility-1.15-2.0.1-alpha.jar RFToolsUtility {rftoolsutility@1.15-2.0.1-alpha COMMON_SETUP}
		EnchantmentDescriptions-1.15.2-2.0.4.jar EnchantmentDescriptions {enchdesc@2.0.4 COMMON_SETUP}
		swingthroughgrass-1.15.2-1.4.0.jar SwingThroughGrass {swingthroughgrass@1.15.2-1.4.0 COMMON_SETUP}
		MouseTweaks-2.13-mc1.15.1.jar Mouse Tweaks {mousetweaks@2.13 COMMON_SETUP}
		ToolBelt-1.15.2-1.14.1.jar Tool Belt {toolbelt@1.14.1 COMMON_SETUP}
		titanium-1.15.2-2.3.7.jar Titanium {titanium@2.3.7 COMMON_SETUP}
		SilentLib-1.15.2-4.6.0+48.jar Silent Lib {silentlib@4.6.0+48 COMMON_SETUP}
		forbidden_arcanus-1.15.2-1.2-beta-3.jar Forbidden & Arcanus {forbidden_arcanus@1.15.1-1.0-beta-1 COMMON_SETUP}
		archers_paradox-1.15.2-0.3.0b.jar Archer's Paradox {archers_paradox@0.3.0b COMMON_SETUP}
		rftoolsbuilder-1.15-2.0.1-alpha.jar RFToolsBuilder {rftoolsbuilder@1.15-2.0.1-alpha COMMON_SETUP}
		Xaeros_Minimap_20.5.2_Forge_1.15.2.jar Xaero's Minimap {xaerominimap@20.5.2 COMMON_SETUP}
		FastWorkbench-1.15.1-3.0.0.jar FastWorkbench {fastbench@3.0.0 COMMON_SETUP}
		StorageDrawers-1.15.2-7.0.2.jar Storage Drawers {storagedrawers@1.15.2-7.0.1 COMMON_SETUP}
		performant-1.15-1.7.jar Performant {performant@1.7 COMMON_SETUP}
		DoubleSlabs-1.15-2.0.2.jar Double Slabs {doubleslabs@2.0.2 COMMON_SETUP}
		HardcoreRevival_1.15.2-4.0.0.jar Hardcore Revival {hardcorerevival@4.0.0 COMMON_SETUP}
		tubesreloaded-1.15.2-1.3.0c.jar Tubes Reloaded {tubesreloaded@1.15.2-1.3.0c COMMON_SETUP}
		structurize-0.10.284-BETA.jar Structurize {structurize@0.10.284-BETA COMMON_SETUP}
		minecolonies-0.11.785-BETA-universal.jar Minecolonies {minecolonies@0.11.785-BETA COMMON_SETUP}
		FastFurnace-1.15.1-3.0.0.jar FastFurnace {fastfurnace@3.0.0 COMMON_SETUP}
		AppleSkin-mc1.15.2-forge-1.0.13.jar AppleSkin {appleskin@1.0.13 COMMON_SETUP}
		Aquaculture-1.15.2-2.0.11.jar Aquaculture 2 {aquaculture@1.15.2-2.0.11 COMMON_SETUP}
		refinedstorageaddons-0.6.1.jar Refined Storage Addons {refinedstorageaddons@0.6.1 COMMON_SETUP}
		CosmeticArmorReworked-1.15.2-v1a.jar CosmeticArmorReworked {cosmeticarmorreworked@1.15.2-v1a COMMON_SETUP}
		DefaultOptions_1.15.2-11.0.1.jar Default Options {defaultoptions@11.0.1 COMMON_SETUP}
	Kiwi Modules: 
		fruittrees:fruittrees
		fruittrees:hybridization
		kiwi:contributors
	Launched Version: forge-31.1.27
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 432.00, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	CPU: 8x Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
	OptiFine Version: OptiFine_1.15.2_HD_U_G1_pre9
	OptiFine Build: 20200223-095745
	Render Distance Chunks: 12
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 432.00
	OpenGlRenderer: GeForce GTX 1060 6GB/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by BBftw** [comment]
Optifine 1.15.2 is not compatible with forge.

**Comment by BenCG3** [comment]
Ok thanks ...
