### ISSUE TITLE
Chunk update lag spikes

### ISSUE THREAD

**Issue by HeyImXFF** [sp614x/optifine#3568]
When I place/destroy blocks near/on the ground, I get a huge red spike which is 'Chunk updates' This also happens for using buttons but not levers. Also when I load into my world after already being in it and the chunks being loaded, it takes a long time to load the surrounding chunks. -BTW this is on 1.15.2 HD_U_G1_pre9

**Comment by HeyImXFF** [comment]
And to be clear, I don't have these issues at all without Optifine.

**Comment by sp614x** [comment]
Can you post an F3 screenshot and the error log?

**Comment by HeyImXFF** [comment]
I've not done this before but I've pasted the log in here as well as a screenshot of my F3 screen.

![2020-03-25_15 19 01](https://user-images.githubusercontent.com/62572630/77552965-1ee55e00-6eac-11ea-8245-235720df6d29.png)
15:19:00.034`
Something's taking too long! 'root.gameRenderer.level.terrain_setup.rebuildNear' took aprox 187.3807 ms
15:19:00.034
Something's taking too long! 'root.gameRenderer.level.terrain_setup' took aprox 187.7528 ms
15:19:00.040
Something's taking too long! 'root.gameRenderer.level' took aprox 195.2724 ms
15:19:00.042
Something's taking too long! 'root.gameRenderer' took aprox 197.0339 ms
15:19:00.042
Something's taking too long! 'root' took aprox 199.9422 ms
15:19:00.541
Something's taking too long! 'root.gameRenderer.level.terrain_setup.rebuildNear.build near' took aprox 148.035 ms
15:19:00.590
Something's taking too long! 'root.gameRenderer.level.terrain_setup.rebuildNear' took aprox 197.5555 ms
15:19:00.591
Something's taking too long! 'root.gameRenderer.level.terrain_setup' took aprox 197.8427 ms
15:19:00.595
Something's taking too long! 'root.gameRenderer.level' took aprox 203.2868 ms
15:19:00.597
Something's taking too long! 'root.gameRenderer' took aprox 204.6505 ms
15:19:00.597
Something's taking too long! 'root' took aprox 206.9011 ms
15:19:01.255
Something's taking too long! 'root.gameRenderer.level.terrain_setup.rebuildNear.build near' took aprox 117.2229 ms
15:19:01.255
Something's taking too long! 'root.gameRenderer.level.terrain_setup.rebuildNear' took aprox 166.7486 ms
15:19:01.255
Something's taking too long! 'root.gameRenderer.level.terrain_setup' took aprox 167.0015 ms
15:19:01.259
Something's taking too long! 'root.gameRenderer.level' took aprox 171.8132 ms
15:19:01.261
Something's taking too long! 'root.gameRenderer' took aprox 173.281 ms
15:19:01.261
Something's taking too long! 'root' took aprox 175.6126 ms

**Comment by Jiingy** [comment]
This is a vanilla game isuse, and has been resolved as of [18w44a](https://bugs.mojang.com/browse/MC-137931)
