### ISSUE TITLE
Replacing an entity model with nothing

### ISSUE THREAD

**Issue by ShaunNoWay** [sp614x/optifine#357]
Is there any issues using `"attatch": false` to replace an entity part, but not supplying any model definition so the model gets replaced with nothing? This creates the effect that I want, but I'm not sure if it's causing any problems behind the scenes.
```
{
    "texture": "chest",
    "textureSize": [48, 16],
    "models": 
    [
    {
        "part": "base",
        "model": "chest.jpm",
        "attach": false
    },
    # Replace lid and knob with nothing so they don't show while opening
    # (is this legal?)
    {
        "part": "lid",
        "attach": false
    },
    {
        "part": "knob",
        "attach": false
    }
    ]
}
```

**Comment by sp614x** [comment]
This is the correct way to disable parts of the vanilla model and there should be no problems.

**Comment by ShaunNoWay** [comment]
@sp614x Thanks, that's just what I needed to know. One more question: What's the difference between `"translate":` and the xyz values in `"coordinates":`? They seem to do the exact same thing for me. Is there any reason to use one over the other?

**Comment by sp614x** [comment]
- "translate" moves the whole model (many boxes, submodels)
- "coordinates" specify the position and size of one box

**Comment by ShaunNoWay** [comment]
Thanks so much!
