### ISSUE TITLE
Cape editor not opening

### ISSUE THREAD

**Issue by MCUniversity** [sp614x/optifine#3573]
I keep pressing on the button and it says that it sould be open in a browser but its not. I the latest optifine version for 1.14.4. I tried switching default browsers. Didnt work. How do i acess the cape change page from the browser?

**Comment by realjackasterisk** [comment]
Please provide details as stated in the pinned issue.

**Comment by MCUniversity** [comment]
Which one is the pinned one?

**Comment by HiItsDevin** [comment]
> Which one is the pinned one?

#3564

**Comment by MCUniversity** [comment]
Description of Issue
When i try to open the cape editor from in-game, it says it should be open in a browser. It is not.
Steps to Reproduce
Open the game using optifine go to settings>skin>optifine cape
Press on the "edit cape" button
OptiFine Version
OptiFine 1.14.4 HD U F5
Self-explanatory.
Installation Method
Using the installer.
Fabric/Forge Version
Standalone.
OptiFabric Version
Standalone.
Other Installed Mods
Standalone.
Log Files/Crash Reports
Latest log: https://hasteb.in/ugiwuzaw.swift
The game didn't crash.
F3 Debug Screenshot
https://imgur.com/a/J7lrtFc
To open this menu, simply press F3 on your keyboard while in-game. Please ensure the text is easily readable. Depending on the size/resolution of your monitor, you may have to adjust your GUI scale for all text to be completely visible on-screen.
Additional Information
-

**Comment by MCUniversity** [comment]
I was able to resolve the issue by copying the link from the output log. After upgrading from F4 to F5 The button still didn't work but I saw that a copy link button was added. That works fine.

**Comment by realjackasterisk** [comment]
Always use the latest version.

Closing since this was solved.
