### ISSUE TITLE
Underwater Gravity Block Lag Spike + Graphical Bug

### ISSUE THREAD

**Issue by TethysBelowAverage** [sp614x/optifine#3574]
## Description of Issue
A graphical bug and lag spike. Causes gravity blocks to create ghost blocks while they fall underwater.
## Steps to Reproduce
Place any block affected by gravity underwater (Sands, gravel, anvils) and have them fall, or break a block beneath them. while it falls, a non-solid model of the block appears as if the block were not affected by gravity, until the falling block's model is completely out of the space it originally took up. Armor stands are not affected by this, however. 
## OptiFine Version
OptiFine 1.15.2 HD U G1 pre9
## Installation Method
Used the installer, standalone OptiFine 
## F3 Debug Screenshot
 https://imgur.com/a/tV5vDWK
## Prior Testing
 This frame drop/ghost block does not occur with any block affected by gravity underwater, only with OptiFine.
## Additional Information
In case you need it, I have an i7-8700K Engineering Sample, which is why it shows up as Genuine Intel(R) CPU 0000

**Comment by yezhiyi9670** [comment]
I cannot reproduce it in pre13.

**Comment by sp614x** [comment]
Should be working in latest preview.
