### ISSUE TITLE
Fancy Rain glitch

### ISSUE THREAD

**Issue by DeGameFinisher** [sp614x/optifine#3576]
When your turn on the Rain and Snow to Fancy and then destroy a block while it is raining the rain will show through the blocks. Any other settings are fine to what I've seen.

**Comment by EminGT** [comment]
Not an Optifine bug. This is a vanilla bug.

**Comment by realjackasterisk** [comment]
Please give us more details as stated in the pinned issue #3564

**Comment by DeGameFinisher** [comment]
It's NOT a vanilla glitch because when I installed the 1.15.2 optifine it
made the rain glitch.

**Comment by DeGameFinisher** [comment]
So explain to me how that's a vanilla glitch.

**Comment by realjackasterisk** [comment]
instead of starting an argument, can you please just give us all the details?

**Comment by sp614x** [comment]
Duplicate of #3424.
Should be fixed in one of the latest previews.
