### ISSUE TITLE
[1.15.2][preview 10][Shader issue] Animated blocks and fire don't animate at all when shaders are enabled

### ISSUE THREAD

**Issue by Legoman99573** [sp614x/optifine#3580]
This happens only with shaders being enabled. When they are disabled, fire animates just fine.

GIF (couldnt put on imgur since file size was large): https://drive.google.com/file/d/1BIfP-GkEc-6urHczQ6Reb983m8dTQFXr/view?usp=sharing

**Comment by OctopusProteins** [comment]
This is also an issue with flowing lava, campfires, and the breaking block animation. Enchanting table works just fine. Tested with Sildurs and SEUS renewed.

**Comment by Donhorn** [comment]
I believe this is an OptiFabric issue. I just encountered this on my own and in my testing I made sure to check with both my normal OptiFabric instance and a fresh Optifine only instance. I tested both instances with the internal Optifine shaders on and off as well as with my normal Sildur's Enhanced Default setup. The Optifine only instance had no animation problems that I could find, while the OptiFabric instance had the same issues you described. 

If you aren't using OptiFabric disregard, but if you are then it's important to remember that OptiFabric is a separate mod from Optifine and issues encountered while using it should be tested both with and without it. I've already posted this issue on OptiFabric's issue tracker based on my own testing.

**Comment by OctopusProteins** [comment]
I am not using OptiFabric.

**Comment by Donhorn** [comment]
Ah! I found the problem. It's issue #3591 that we're encountering. Turn Smart Animations off in performance settings and they animate.

**Comment by seeruk** [comment]
Doesn't help with the block breaking animations not working sadly; I'll make a separate issue for that as I can't see one already.

**Comment by akasnowmaaan** [comment]
I'm seeing this problem with the Optifine Internal shaders.
Specifically, the animated fire of an off-hand torch.

But, the animation stopping comes and goes. It's not a constant problem. 

Here are the steps I've taken to reproduce the issue:
- When I start the program without Shaders, then enable Internal Shaders, the fire animation persists - it doesn't stop immediately.
- When I have Internal Shaders enabled, then quit and restart Minecraft, the animation doesn't work when it starts again.
- If the animation doesn't work, restarting the program doesn't fix it while Internal Shaders remain turned on.

Here's a work-around I discovered:
- If the animation is not working, and I go to the Shaders selection screen, and Internal shaders is already selected - I can re-select them (basically forcing a video reboot as the shaders are re-enabled), then the animation starts working again.

I hope that helps.

**Comment by sp614x** [comment]
Should be fixed in latest preview.
