### ISSUE TITLE
Enabling shaders in pre10 causes game to immediately crash 

### ISSUE THREAD

**Issue by lsdxm** [sp614x/optifine#3581]
When I turn off shaders before joining a world or server it works fine, but when I enable any shader it crashes back to the launcher in a couple seconds. 

No error code or anything, just crashes.

**Comment by BBftw** [comment]
are you using optifabric?

**Comment by lsdxm** [comment]
> are you using optifabric?

No, it doesn't load at all with optifabric. This is with vanilla launcher.

**Comment by NitroCipher** [comment]
If you crash when enabling a shader, try to do it on the mc main menu instead of while in a world

**Comment by lsdxm** [comment]
> If you crash when enabling a shader, try to do it on the mc main menu instead of while in a world

I mean while shaders are enabled, not while engaged in the process of enabling them.
