### ISSUE TITLE
Emmisive Texture not working for animated mob textures

### ISSUE THREAD

**Issue by LadyHaley** [sp614x/optifine#3582]
### Description of Issue
I am trying to add Emmisive textures to an animation I created for a mob texture that I have animated but the Emmisive textures is not working for that. They are working for my armor, static mob textures, item icons, and block textures. I have not tested if it works as animated for the above texture types since I am currently trying to get it working for my mob skin.

### Steps to Reproduce

1. Create animated texture for a mob
2. Add an emmisive texture for that animation using the naming rules set by the emmisive.properties file
3. Load up the game and spawn the mob with the above mentioned texture.

### Optifine Version
OptiFine_1.14.4_HD_U_F5

### Installation Method
.jar installer

### Log Files
[latest.log](https://github.com/sp614x/optifine/files/4391624/latest.log)

### F3 Debug Screenshot
![image](https://user-images.githubusercontent.com/3754909/77724126-4bcd7880-7046-11ea-8f94-ba4abf94562a.png)

### Prior Testing
I verified that Emissive textures were working for the other items I mapped that out on but none of them were animated emmisive textures like im trying to do now. Im not really sure what other testing I can do for emissive textures.

**Comment by realjackasterisk** [comment]
Is the emissive texture also animated?

**Comment by LadyHaley** [comment]
Yes it is, I think I mentioned that in my op

**Comment by realjackasterisk** [comment]
where's the .mcmeta file?

**Comment by LadyHaley** [comment]
the pack.mcmeta? Thats in the root directory of the pack.
Also sorry for the very delayed response

**Comment by JackDotJS** [comment]
um, no. the mcmeta file for the animated texture.

**Comment by LadyHaley** [comment]
would that be the .properties file for the animation?

**Comment by JackDotJS** [comment]
no.... do you know how to make an animated texture in a vanilla resource pack...?

**Comment by LadyHaley** [comment]
I dont beleive so. The animation for the mob works fine using optifines method, its just not applying the emmisive texture to it
