### ISSUE TITLE
White Texture Bug for 1.15.2

### ISSUE THREAD

**Issue by jottgi** [sp614x/optifine#3583]
![bugopti](https://user-images.githubusercontent.com/62737586/77726548-8f849b80-6fce-11ea-8234-d54973acb5be.png)

Unloaded chunks appear as white I think, I am not fully sure what's happening here but it does seem broken.

**Comment by Jeypi00** [comment]
Experiencing the same problem with BSL Shaders (tried multiple versions).[
![2020-03-27_23 36 23](https://user-images.githubusercontent.com/62748623/77806373-cfa65580-7084-11ea-9c94-4ed9ad7a5970.png)
](url)

**Comment by Volasaurus** [comment]
Still experiencing this as well.

**Comment by fgRuslan** [comment]
This is still an issue :(

**Comment by sp614x** [comment]
Duplicate of #3659.
