### ISSUE TITLE
Light levels not updating on any blocks pre10

### ISSUE THREAD

**Issue by noxull** [sp614x/optifine#3587]
I've never reported an issue before so apologies if I'm a bit unclear. 

Using pre10 currently. On a windows laptop with a i5-9300H and 2gb 1660ti. Installed directly through the .jar file. 

None of my worlds have blocks which have updating light levels. In debug mode, on my previously created worlds, the light level of the sky changes and is accurate, the smooth/ambient lighting effects also seem to work. However the actual light levels of the blocks do not visibly change despite the light level number changing as expected. 

With smooth/dynamic lighting turned on things get a bit dimmer in caves etc but the actual blocks seem to stay at max light legvel. (If I turn smooth and dynamic lighting off then there is no darkness effects at all in the world and every block stays at max brightness) 

Weirdly, when I generated a new world the same issue was present but the light level number in debug mode stopped working altogether and just showed every block as 0. 

I hope this was helpful and I can try and elaborate if there was anything that didn't make sense.

**Comment by noxull** [comment]
just thought I'd add that this issue was also present when I tried pre9, its not something that popped up as of pre10. Not sure if that's relevant information or not but best to be clear.

**Comment by sp614x** [comment]
Should be working with latest preview.
