### ISSUE TITLE
[1.15.2] CIT Issues: Items/Armor

### ISSUE THREAD

**Issue by CampbellSoup077** [sp614x/optifine#3588]
I hate being one of those pushy people but I would also hate it if this is a legit problem and it never got brought up. 

I have started using CIT for misc things and I am so thankful for Optifine that it can do those things much better than CustomModelData. I have noticed that it seems this feature is only partly working. The custom textures for items show on the GUI and when on the ground, but do not show when holding the items in hand or in item frames. Here is an example image [https://imgur.com/a/k9O5L8H](url)

CIT Armor is the similar. The textures all work except when it is being worn. 
CIT Elytra seems to be 100% working on my end.

**Comment by TBlazeWarriorT** [comment]
I'm assuming this is related to https://github.com/sp614x/optifine/issues/3276 and still present in OptiFine 1.15.2_HD_U_G1_pre10?

**Comment by realjackasterisk** [comment]
Why does that imgur link lead to this url????
```
https://github.com/sp614x/optifine/issues/url
```

**Comment by CampbellSoup077** [comment]
Ya it does look like a same issue of CIT not being fully updated. I am new to git and didn't know how to search through the past bug reports. I figured its better to maybe have a second report and close it than not report it at all.

Ya the link works if you copy and paste it into a browser. Not sure why github isn't linking that correctly....

**Comment by KotoHacker** [comment]
It's not working on pre12 too

**Comment by Katalijst** [comment]
Still not working in pre15, hopefully it will be update before 1.16, a bit annoying for servers using it for custom armors, I know people are asking for shaders but on a technical side I would prefer that fixed.

**Comment by blek-id** [comment]
On pre16, still not working

**Comment by blek-id** [comment]
On pre17, still not working

**Comment by CarsonJF** [comment]
Bump. Really hoping to have this working again before 1.16 drops :(

**Comment by bloggy** [comment]
CIT and CEM issues seem to be the issues with most people are interested in to have them fixed. Hope sp614x can priorize them.

**Comment by engineer1109** [comment]
Really need armor CIT.
Specially chestplate leggings and boots that custommodeldata cannot do.

**Comment by sp614x** [comment]
Fixed, coming in pre20.
