### ISSUE TITLE
[OF 1.15.2 pre10] Shaders bug collection

### ISSUE THREAD

**Issue by Excederus** [sp614x/optifine#3589]
I'm having the following bugs with different shaders:
Kappa (version 2.2 tA):
- *throws OpenGL 1282 error*
- grass block top texture is invisible/not rendering (only when RP support is enabled)
- glass texture is invisible/not rendering (only when RP support is enabled)
- specular maps are not working
- normal maps are not working
- if there is a normal map the block will have 100% POM depth on the whole texture

BSL (latest 7.1Dev version):
- specular maps are not working
- normal maps are not working

Sildurs Enhanced Default (version 1.10):
- if there is a normal map the block will have 100% POM depth on the whole texture

If it's fine by you guys I would comment new issues I find onto this thread so I don't have to open 10 issues.

**Comment by StefanHolmes** [comment]
SEUS PTGI E12, throwing OpenGL 1282 errors infrequently, but regularly. Lighting is not working as expected.

**Comment by StefanHolmes** [comment]
![image](https://user-images.githubusercontent.com/21371956/77768134-f4c1a680-7039-11ea-9973-4923ff34ab3b.png)

Example of lighting error with SEUS PTGI E12

**Comment by OctopusProteins** [comment]
POM/PBR textures are not rendering properly. I've tested in SEUS Renewed and Sildurs. Screenshot from OF 1.15 pre10, SEUS Renewed 1.0.1, Vanilla PBR.

![2020-03-27_12 28 10](https://user-images.githubusercontent.com/17932127/77777907-97702a00-7026-11ea-833b-8ee855dbe340.png)

The textures are kind of "misaligned"? Not sure how to explain it best.

**Comment by azridere** [comment]
Fire animations don't work at all for me, even being set on fire.

**Comment by realjackasterisk** [comment]
It would *really* be better to post each issue separately, so they can be tracked much more easily.

**Comment by TheJSHuA** [comment]
Adressing fire animations being broken: If you have Smart Animations on, animations won't work. This is a known issue.
Specular and normal maps behaving strangely when enabled on a shaderpack that supports them is also an already known issue. This is also what is breaking POM completely.

**Comment by sp614x** [comment]
All of these should be fixed in pre22.
