### ISSUE TITLE
CIT doesn't work with Optifine 1.11

### ISSUE THREAD

**Issue by DeadPigman17** [sp614x/optifine#359]
I don't know why it doesn't work on 1.11,I tried 1.10 and it worked perfectly.

**Comment by ShaunNoWay** [comment]
Minecraft 1.11 only reads resource files with lower-case file names. I think this has been fixed in the latest Optifine preview. http://optifine.net/downloads

**Comment by DeadPigman17** [comment]
Still not working...

**Comment by DeadPigman17** [comment]
Nevermind,I could fix it.Thank you!
