### ISSUE TITLE
[OF 1.15.2 pre10] [SEUS-Renewed-v1.0.1] Banners flash white

### ISSUE THREAD

**Issue by BadCoder2** [sp614x/optifine#3590]
## Description of Issue
In any given sample world any banners will flash between their regular form and white.
## Steps to Reproduce
1. Generate a minecraft world in 1.15.2
2. Place a banner. White banners minimize the effect but it is still there

## OptiFine Version
OptiFine 1.15.2 HD U G1 pre10

## Installation Method
Standalone installer

## Log Files/Crash Reports
https://pastebin.com/RDrWBKM9

## F3 Debug Screenshot
https://imgur.com/a/0v48ySr

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?

No
## Additional Information
Lowering Gamma in shader options decreases the effect this has noticeably.

**Comment by Luna-the-dev** [comment]
Same issue for me as well. I have a GTX 1080 and an r5 3600x standard clock speed

**Comment by RedCarlos26** [comment]
Same issue with an rx 580 and bsl shader in preview 13

**Comment by sp614x** [comment]
Fixed in pre18.
