### ISSUE TITLE
[Settings] Smart-Animations not animating fire in view

### ISSUE THREAD

**Issue by DaRocketeer15** [sp614x/optifine#3591]
## Description of Issue
The smart-animations is not working properly. even if the animation is on you or in your fov. It won't animate. This is for fire and nether portals. 

## Steps to Reproduce
You go to the nether and turn on smart-animations. Look around or step in lava and there won't be animations. This also works in the overworld.  

## OptiFine Version

OptiFine 1.15.2 HD U G1 pre10

## Installation Method
I used the stand-alone jar

**Comment by meffewToo** [comment]
Having similar issues, however, absolutely none of my animated textures are working. The most common ones that I have seen are Fire and Nether Portals not being animated, and I am using default textures for those, both of which were working before pre10

**Comment by sp614x** [comment]
Should be working in latest preview.
