### ISSUE TITLE
[OF 1.15.2 pre10] Player Hands / Items Invisible with Shaders on

### ISSUE THREAD

**Issue by popejon** [sp614x/optifine#3592]
## Description of Issue
Whenever I turn on any type of shaders my players hands and items disappear. I tried both (internal) and BSL_v7.1.05p2 shaders and it happens on both. When I set the shader option to "OFF" the player hands and hand held items come back.

## Steps to Reproduce
1. Turn on any type of shaders ie. "(internal)" or "BSL_v7.1.05p2"

## OptiFine Version
preview_OptiFine_1.15.2_HD_U_G1_pre10.jar

## Installation Method
I dropped the .jar file into the mods folder

## Fabric/Forge Version
Fabric

## OptiFabric Version
optifabric-1.0.0-beta5.jar

## Other Installed Mods
fabric-api-0.5.1+build.294-1.15.jar
fabricmod_VoxelMap-1.9.15_for_1.15.1.jar
optifabric-1.0.0-beta5.jar
preview_OptiFine_1.15.2_HD_U_G1_pre10.jar

**If OptiFine is installed as standalone, remove this section.**

## Log Files/Crash Reports
No log files or crash reports

You can get logs from `.minecraft/logs`, and crash reports from `.minecraft/crash-reports`. 
Locating your `.minecraft` folder will depend entirely on your OS. See this page for details: https://minecraft.gamepedia.com/.minecraft

**DO NOT directly copy and paste log contents here on GitHub.**

## F3 Debug Screenshot
![Screen Shot 2020-03-27 at 1 03 15 PM](https://user-images.githubusercontent.com/31891728/77781180-7d851600-702b-11ea-92cd-21dcf6aceeac.png)

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
No

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   - Only OptiFine and Forge
   - Only OptiFine, OptiFabric, and Fabric
Yes

- Does this happen without any mods at all?
   - Only Forge/Fabric by itself.
No
- Does this happen in OptiFine standalone?
not sure
- Does this happen in Vanilla without OptiFine?
No
- Have you tried using a binary search to find which mods cause this issue?
   - To find conflicting mods, split your mods into 2 groups (not including OptiFine/OptiFabric, obviously). Remove one group, and test in-game. Keep the group that has the problem, and repeat until no more mods can be removed without the issue disappearing.
   - Does the issue still happen with only the remaining mods installed?
      - Forge/Fabric and remaining mods, without OptiFine

## Additional Information
I'm playing on a Macbook Pro with MacOS Mojave 10.14.6
Graphics Card: Radeon Pro 560X 4 GB
Processor: 2.6 GHz Intel Core i7
Memory: 32 GB 2400 MHz DDR4

**Comment by DaveyL2013** [comment]
The bug is in fact on fabric's side, and was fixed with optifabric beta 7.

**Comment by Panderine** [comment]
can confirm fix in optifabric beta7

**Comment by TheMadMattt** [comment]
yes

**Comment by realjackasterisk** [comment]
Closing as solved.

**Comment by h1z3y3** [comment]
Same problem here: 
https://discord.com/channels/423430686880301056/896862947480068137/947522640992669736
