### ISSUE TITLE
rays shine through ground into the caves

### ISSUE THREAD

**Issue by 508droid** [sp614x/optifine#3593]
![Untitledgggg](https://user-images.githubusercontent.com/21113184/77794041-8e408680-7041-11ea-96c4-9d2cfe191be7.png)

playing most recent version as of 3/27/2020

**Comment by joost00719** [comment]
Duplicate by 3589

**Comment by TheJSHuA** [comment]
This is a bug with how shaders calculate lighting and not an OptiFine bug. Due to certain blocks not being loaded, and the way shaders calculate lighting like this, the rays will "leak" through certain areas.

**Comment by Blite33** [comment]
> This is a bug with how shaders calculate lighting and not an OptiFine bug. Due to certain blocks not being loaded, and the way shaders calculate lighting like this, the rays will "leak" through certain areas.

Bro, I have this with every shader i have. I'm not sure it's just a shader bug. It has improved slightly when shaders are updated, but not all shaders improve, and i've tried everything. I've been wondering what has been causing it.

**Comment by joost00719** [comment]
Well, it does nice doesn't it?

**Comment by sp614x** [comment]
Fixed in pre22.
