### ISSUE TITLE
[OF 1.15.2 pre10] No environmental lighting with SEUS

### ISSUE THREAD

**Issue by Lanoma** [sp614x/optifine#3594]
## Description of Issue
Light emitting blocks or entities such as torches, fire, etc. are not emitting any environmental lighting when I am close (within 70~ blocks) to them. When I'm further than 70 blocks away they emit light, but everything in a 70 block radius from me does not emit environmental lighting. 

## Steps to Reproduce
1. Using SEUS PTGI E12
2. Be within 70 blocks of placed torches/fire/lanterns

## OptiFine Version
[OF 1.15.2 pre10]

## Installation Method
Installed using the installer, not manually.

## F3 Debug Screenshot
![2020-03-27_14 45 31](https://user-images.githubusercontent.com/62772712/77799088-a4e2df80-7039-11ea-9db5-55c341444ef8.png)

## Prior Testing
Does not happen in vanilla, does not happen when not using shaders, does not happen with continuum shaders.

No shaders: 
![2020-03-27_14 37 04](https://user-images.githubusercontent.com/62772712/77799156-cf349d00-7039-11ea-91db-f466ce61ab7a.png)

SEUS enabled when within 70 blocks:
![2020-03-27_14 37 19](https://user-images.githubusercontent.com/62772712/77799177-d65bab00-7039-11ea-8f25-26d7a63dcc8f.png)

SEUS enabled when past 70 blocks:
![2020-03-27_14 37 27](https://user-images.githubusercontent.com/62772712/77799189-dfe51300-7039-11ea-9db9-8e63098ac3bc.png)

**Comment by TheJSHuA** [comment]
The reason why this is happening is because geometry shaders are currently broken in the 1.15 previews, and SEUS PTGI relies on geometry shaders to be able to calculate lighting (global illumination that isn't done in screen space), and reflections.

**Comment by jdtriska** [comment]
I am also seeing this issue on OF 1.15.2 pre12.

**Comment by MangoDevStudio** [comment]
@TheJSHuA this is happening to me on optifine 1.14.4 f2 https://drive.google.com/file/d/1FEzKbUhlhwESukaEhmWiwK-TK_HzBk5d/view?usp=sharing

**Comment by Snubbsy** [comment]
I have this issue as well using pre13 and seus ptgi e12.

**Comment by kulius7** [comment]
Having the same issue using 1.15.2 pre13 and PTGI E12

**Comment by YannickAlthans** [comment]
Same issue using 1.15.2 pre16 and PTGI E11

**Comment by jdatopo814** [comment]
> The reason why this is happening is because geometry shaders are currently broken in the 1.15 previews, and SEUS PTGI relies on geometry shaders to be able to calculate lighting (global illumination that isn't done in screen space), and reflections.

So, are geometry shaders broken in all versions of OptiFine? This glitch happens to me on all versions of PTGI with all versions of OptiFine (1.8, 1.9, 1.10, 1.11, 1.12, 1.13, 1.14, 1.15). Environmental lighting is broken in either close range or long range. On default settings, environmental lighting is broken within 70 block radius. After I had tampered with the settings, environmental lighting was fixed inside the radius but broken outside of it. I am on a GTX 980 paired with Ryzen 5 2600X, and I've tested this glitch on an RX 580 as well.

**Comment by MangoDevStudio** [comment]
I think it’s just you man, I use SEUS PTGI e12 on 1.14.4 optifine e2 and it works great! It’s probably got something to do with your outdated hardware, I’ve got a gtx 1060 over here

**Comment by jdatopo814** [comment]
That may be the issue, but I honestly doubt it. The GTX 980 isn't really outdated as it is still pretty relevant today. I get that it's two different architectures, but a lot of videos and threads I'm seeing are saying/showing that PTGI is allowed to run fine as far back as the 970.

**Comment by Snubbsy** [comment]
> I think it’s just you man, I use SEUS PTGI e12 on 1.14.4 optifine e2 and it works great! It’s probably got something to do with your outdated hardware, I’ve got a gtx 1060 over here
> […](#)

It’s definitely not hardware, I have an RTX 2070 Super and I have this issue.

**Comment by jdatopo814** [comment]
> > I think it’s just you man, I use SEUS PTGI e12 on 1.14.4 optifine e2 and it works great! It’s probably got something to do with your outdated hardware, I’ve got a gtx 1060 over here
> > […](#)
> 
> It’s definitely not hardware, I have an RTX 2070 Super and I have this issue.

Snubbed, the come t was directed at me because I mentioned having a GTX 980, unless you’re getting this lighting glitch on all versions of optifine and PTGI too?

**Comment by Snubbsy** [comment]
> > > I think it’s just you man, I use SEUS PTGI e12 on 1.14.4 optifine e2 and it works great! It’s probably got something to do with your outdated hardware, I’ve got a gtx 1060 over here
> > > […](#)
> > 
> > 
> > It’s definitely not hardware, I have an RTX 2070 Super and I have this issue.
> 
> Snubbed, the come t was directed at me because I mentioned having a GTX 980, unless you’re getting this lighting glitch on all versions of optifine and PTGI too?

Yes, I also have the lighting glitch

**Comment by sp614x** [comment]
Fixed in pre22.
