### ISSUE TITLE
[1.15.2] With shaders mobs don't turn red when injured and creepers don't flash when expoding

### ISSUE THREAD

**Issue by GaleWings** [sp614x/optifine#3598]
## Description of Issue
As the title, when shaders are enabled (including the "internal" shader), mobs don't turn red when injured.

## OptiFine Version
1.15.2 pre10 

## Installation Method
Use the included standalone installer.

**Comment by realjackasterisk** [comment]
Isn't this normal for shaders?

**Comment by LucaDragon5** [comment]
> Isn't this normal for shaders?

some shaders let you disable/enable it, but it doesn't work

**Comment by rre36** [comment]
As far as I know this is a known issue with preview10.

**Comment by sp614x** [comment]
In 1.15 the entity overlay (entity hurt, creeper flash, etc.) is is implemented as an additional texture mapped on top of the model.
This is not compatible with the existing shaders and has to be reimplemented to work as 1.14.
The uniform entityColor is currently not working.

**Comment by sp614x** [comment]
Fixed in pre30.

**Comment by sp614x** [comment]
All shader packs that use `entityColor` should work correctly:
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.txt#L177
