### ISSUE TITLE
OptiFine 1.15.2 HD U G1 pre10 Cant use shaders due to anti aliasing but I cant turn off anti aliasing because its greyed out.

### ISSUE THREAD

**Issue by RyuAzuku** [sp614x/optifine#3599]
## Description of Issue
On an earlier preview of optifine for 1.15.2 I was bored and wanted to see if messing with the anti aliasing slider would affect anything in game(it didn't) and I just left the slider as it was. On a recent update these sliders are now greyed out and cannot be moved but is stuck at where I put it at on a previous preview meaning I cannot use shaders. 

EDIT 1: Going to my .minecraft folder and deleting all versions of optifine/reinstalling optifine does nothing.

## OptiFine Version
OptiFine 1.15.2 HD U G1 pre10 

## Installation Method
Used included installer

## Screenshot
https://imgur.com/a/DvptBm4

**Comment by HiItsDevin** [comment]
For now, Go to your .minecraft folder, and go into optionsshaders.txt and set your `antialiasingLevel=` to 0, so it should be `antialiasingLevel=0`

**Comment by RyuAzuku** [comment]
Was just about to post that I got it fixed that way. Issue will be closed.
