### ISSUE TITLE
[ 1.15.2] Hitboxes not visible on servers / Sildurs Shaders

### ISSUE THREAD

**Issue by Hendo-exe** [sp614x/optifine#3601]
## Description of Issue
When using Sildurs Shaders hitboxes are not visible, without the shaders (just Optifine) they are visible. This only appears to happen on servers, and the player hitbox is visible in the inventory window but not in third person.

## Steps to Reproduce
1. F3 + B to show hitboxes

## OptiFine Version
1.15.2 preview 10

## Installation Method
Standalone jar installer

## Prior Testing
If you've installed standalone:
Visible in standalone, visible in Optifine 1.14.4

**Comment by Hendo-exe** [comment]
Addition: Horses and donkeys have visible hitboxes.

**Comment by RandomGgames** [comment]
All UI lines are kinda messed up. Structure block lines choose when to render when running the shader sometimes, same with the breaking animation overlay.

**Comment by sp614x** [comment]
Fixed in pre 23.Fixed in pre23.
