### ISSUE TITLE
[1.15.2-pre10] Crashing when starting Minecraft

### ISSUE THREAD

**Issue by MaxMitter** [sp614x/optifine#3603]
<h1>Description of Issue</h1>

Minecraft crashes when starting with the newest Optifine preview.

<h1>Steps to Reproduce</h1>

1. Install Forge

2. Drop Optifine into the mod folder

3. Start Minecraft

4. Crash

<h1>Optifine version</h1>

preview OptiFine 1.15.2 pre10

<h1>Installation Method</h1>

Drop the JAR file into the mod folder

<h1>Forger Version</h1>

1.15.2-forge-31.1.30

<h1>Other installed Mods</h1>

None

<h1>Crash Report/Log File</h1>

[crash-2020-03-28_16.19.09-client.txt](https://github.com/sp614x/optifine/files/4397367/crash-2020-03-28_16.19.09-client.txt)

[latest.log](https://github.com/sp614x/optifine/files/4397369/latest.log)

<h1>Prior Testing</h1>

Error does not happen without OptiFine Mod. Forge works without mods and with other mods (tested JourneyMap and MouseTweaker)

**Comment by marvinjuette** [comment]
Jup same here

**Comment by LeoneScorne** [comment]
Forge compatibility isn't implemented in the current version yet.

**Comment by Donhorn** [comment]
Read the changelog. Last item for pre10. It's been this way for every 1.15 preview version. Looking at the 1.14 changelogs it was almost a month after the full release before we started seeing internal compatibility with Forge. 
https://optifine.net/changelog?f=preview_OptiFine_1.15.2_HD_U_G1_pre10.jar

**Comment by MaxMitter** [comment]
Ah my bad, I guess reading till the end would have helped. Thanks for clarifying.
