### ISSUE TITLE
[bug] [1.15] [Shader] Using BSL shades, dropped items, items in item frames, and items help by other players appear glitch, and a similar glitch appears when breaking blocks with the overlayed block-breaking texture

### ISSUE THREAD

**Issue by meffewToo** [sp614x/optifine#3606]
I don't know if this is specifical to BSL shades, but I have not heard reports of similar issues with different shaderpacks

**Comment by sp614x** [comment]
Should be working in latest preview.
Breaking block animation is duplicate of #3600.
