### ISSUE TITLE
[bug] [1.15 ] [Shaders] BSL Shader - Beacon Beam can be seen through walls

### ISSUE THREAD

**Issue by meffewToo** [sp614x/optifine#3607]
The beam from beacons can be seen through walls when looking up at certain angles

**Comment by HiItsDevin** [comment]
Can you please provide some sort of visual aide [screenshot?], along with your preview version, and everything in the Format please? Just telling us isn't really telling much.

**Comment by sp614x** [comment]
Should be working in latest preview.
