### ISSUE TITLE
Parallax Breaking

### ISSUE THREAD

**Issue by curlyi** [sp614x/optifine#3608]
## Description of Issue
Using POM or Bumpmapping on any shader with specular resource packs, that should work, breaks them. Showcase in the video, happens with any shader used. SEUS + Sildurs have the effect shown in the video, BSL just makes distant terrain really glitchy and POM doesn't work. Haven't tried continuum as it murders my PC.

https://www.youtube.com/watch?v=jGee2UBt5H0&feature=youtu.be (don't mind the music)

Also, the colours on blocks are off but this is likely an issue with SEUS in 1.15, this doesn't occur in BSL or Sildurs.

# OptiFine Version 1.15.2pre10

**Comment by rre36** [comment]
It is a known issue that resourcepack normal- or specular maps are not working as intended in preview 10.

**Comment by sp614x** [comment]
Works in latest preview.
