### ISSUE TITLE
[OF 1.15.2 Pre-release 10] Fabric Crash on Startup

### ISSUE THREAD

**Issue by RuntimeException6** [sp614x/optifine#3611]
## Description of Issue
Minecraft crashes, without an error message, and no crash report is generated.
However, there was a log file, which can be found under Log Files/Crash Reports.

## Steps to Reproduce
I started minecraft, with the fabric mods found in the Other Installed Mods section.

## OptiFine Version
1.15.2 Pre-release 10

## Installation Method
I dropped the jar into my mods folder. As shown in the attached picture, I have the latest version of OptiFabric

## Fabric/Forge Version
fabric-loader-0.7.8+build.189-1.15.2

## OptiFabric Version
optifabric-0.7.1

## Other Installed Mods
![mods](https://user-images.githubusercontent.com/54539900/77831980-02922d00-7109-11ea-8368-44ea67d1fabc.PNG)

## Log Files/Crash Reports
[latest.log](https://github.com/sp614x/optifine/files/4397781/latest.log)

## Prior Testing
The crash does not happen if the Optifine Pre-release 10 jar is not present in the mods folder. As expected, it shows the screen saying there is no optifine jar included.

## Additional Information
Here goes any final remarks and everything else that might not fit in the previous sections.

**Comment by Alternus** [comment]
Tor issues is you have the wrong version of optifabric 0.7.1 is for 1.14 you need 1.0.0-beta 7 for 1.15

**Comment by oOLegendOo** [comment]
Now you find the solution about this problem.
So close this yourself

**Comment by realjackasterisk** [comment]
Closing as solved.
