### ISSUE TITLE
[OF-pre10 Shaders] Motionblur is weird

### ISSUE THREAD

**Issue by EmeraldC0der** [sp614x/optifine#3615]
## Description of Issue
The items you are holding in 1st-person view are being blurred incorrectly if a motionblur shader is applied.

## How to Reproduce
I am using Sildurs Vibrant Shaders v1.25 with motionblur enabled.
On 1.14 the hand items are properly blurred (i was using the same shaders), while on 1.15.2 there are glitches, as seen on the video:
https://drive.google.com/open?id=1alUb6CLHARFaQZ0GN9-vFrUEHdF43gHn

## OptiFine Version
OptiFine 1.15.2-pre10

## Installation Method
I used the installer available at optifine.net/downloads -> Clicked 'Install'

## F3 Debug Screenshot
Here you go
![2020-03-29_14 08 50](https://user-images.githubusercontent.com/62828358/77843379-e1901180-71c6-11ea-9107-578cdb80ac34.png)

## Additional Information
The glitch is most visible when going backwards (at least for me)

**Comment by rre36** [comment]
This is a known issue with certain methods shaderpacks use to mask the hand for motionblur or DoF in the optifine preview version.

**Comment by sp614x** [comment]
Should be fixed in latest preview.
