### ISSUE TITLE
[Bug] Animations

### ISSUE THREAD

**Issue by MrOmniPlasma** [sp614x/optifine#3618]
## Description of Issue
the animations (portals, fire, water, lava etc.) are not working with shaders

## Steps to Reproduce
1. just started the game

## OptiFine Version
OptiFine 1.15.2 HD U G1 pre10

## Installation Method
installer

## Prior Testing
doesn't happen in vanilla or with shaders deactivated

## Additional Information
N/A

**Comment by BattleSpunk** [comment]
I had this too, it fixed by turning smart animations off for me.

**Comment by sp614x** [comment]
Fixed.
