### ISSUE TITLE
[Contribution] Make it Opensource

### ISSUE THREAD

**Issue by riddickx5000** [sp614x/optifine#3623]
Hi,
i really like your work. 
Why are you not allow us to contribute ?
This would make the progress much faster. 
If you have no time or its just to complicated to make optifine compatible with the new Minecraft versions. I think out there would be a lot of people love to help you getting things done.

Please lets us help you!

**Comment by RandomGuyJCI** [comment]
You should read the FAQ in the Optifine discord server.

> Q: **Why isn't OptiFine open-source?**
> A: OptiFine as a mod only stores the changes that are made to Minecraft. None of these changes make much sense on their own, only when they've been merged with vanilla. If OptiFine's source code was released, it would have to be embedded in Minecraft's source code for any part of it to be remotely comprehensible, which is against Mojang's EULA.
