### ISSUE TITLE
[1.15.2 pre1 to pre12] Rain splash particles glitched underwater

### ISSUE THREAD

**Issue by ItsRodrigoAl** [sp614x/optifine#3624]
## Description
When its raining and you're under water, you can see how the splash particles get glitched

## Steps
1 - Set /weather rain or /weather thunder
2 - Go underwater on a ocean

## OptiFine Version
1.15.2-OptiFine_HD_U_G1_pre10

## Additional Information
This is not normally because you can check the same issue on 1.16 or 1.15 vanilla and this doesn't happen. Actually I can't really show a picture about because it is showed like at 5 frames per second,  but if you look there's a splash particle that its at almost 2 blocks underwater, when it should not even go through the water

![2020-03-30_08 44 57](https://user-images.githubusercontent.com/57012631/77919347-105fc380-726b-11ea-8c79-11548c2d4a31.png)

**Comment by Futuremappermydud** [comment]
No idot

**Comment by ItsRodrigoAl** [comment]
> No idot @Futuremappermydud 

Was a mistake when I posted it without the real description (also that is an unnecessary comment) :s

**Comment by RandomGuyJCI** [comment]
Can you try updating to pre10 and seeing if the issue still persists?

**Comment by ItsRodrigoAl** [comment]
> Can you try updating to pre10 and seeing if the issue still persists?

Yep, still persists. From pre1 to pre10

**Comment by yezhiyi9670** [comment]
These seem to be underwater suspend particles, not glitched rain splash particles.

**Comment by sp614x** [comment]
The screenshot shows water suspend particle, not rain splash.
The only problem with rain splash underwater is that it apears one block below the surface, which is a vanilla bug: https://bugs.mojang.com/browse/MC-131770
