### ISSUE TITLE
[1.15.2 pre10] Screen Freezes While Using Shaders

### ISSUE THREAD

**Issue by MrKiwiBirb** [sp614x/optifine#3625]
## Description of Issue
Screen freezes, everything else works. I can move around and break blocks and enter the menu but the screen itself will be frozen

## Steps to Reproduce
Simply use a Shader

## OptiFine Version
1.15.2-OptiFine_HD_U_G1_pre10

## Installation Method
I used the standalone installer

## Prior Testing
This has not and does not occur on vanilla Minecraft, I've only encountered this issue using Shaders

## Additional Information
This bug occurs even on low-intensity shaders so I doubt it has to do with my own PC not handling the shaders I have.

**Comment by sp614x** [comment]
Caused by invisible entities with glowing effect.
Fixed in pre22.
