### ISSUE TITLE
[Shaders] Rainbow Bug with shaders

### ISSUE THREAD

**Issue by Cat371** [sp614x/optifine#3626]
## Description of Issue
When using shaders it causes certain blocks to become rainbow pixeled

## Steps to Reproduce
1. I used any shaders

## OptiFine Version
1.15.2 Pre-10

## Installation Method
I use Fabric client with optifabric.  

## Fabric/Forge Version
Idk most recent fabric client as of 3/30

## OptiFabric Version
Most recent as of 3/30

## Other Installed Mods
Block meter, fabric api, carpet mod, hwyla, litematic, malilib, minihud, modmenu, moenchantments, mo glass, optifabric, quick shulker, simplex terrain, skin swapper, tweakeroo, Wurst Client (For fast place btw)

**If OptiFine is installed as standalone, remove this section.**

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
No, cant use shaders in vanilla
If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   - Only OptiFine and Forge NA
   - Only OptiFine, OptiFabric, and Fabric Yes
- Does this happen without any mods at all?
   - Only Forge/Fabric by itself.
- Does this happen in OptiFine standalone? Idk
- Does this happen in Vanilla without OptiFine? Cant, no shaders in vanilla
- Have you tried using a binary search to find which mods cause this issue?
   - To find conflicting mods, split your mods into 2 groups (not including OptiFine/OptiFabric, obviously). Remove one group, and test in-game. Keep the group that has the problem, and repeat until no more mods can be removed without the issue disappearing. Not a mod issue im pretty certain
   - Does the issue still happen with only the remaining mods installed?
      - Forge/Fabric and remaining mods, without OptiFine Yes

**Comment by HiItsDevin** [comment]
> Wurst Client

Optifine doesn't support any hacked clients.

**Comment by MrCheeze446** [comment]
As Devin said, hacked client issues won't be fixed by OptiFine
