### ISSUE TITLE
OptiFine_HD_U_G1_pre10 crash with Fabric

### ISSUE THREAD

**Issue by Studio528-real** [sp614x/optifine#3627]
## Description of Issue
When I press Escape to bring the pause menu the game crashes

## Steps to Reproduce
Download a 1.15.2 Fabric Version
Download OptiFine 1.15.2 G1 pre10
Download OptiFabric 1.0.0-beta7
Download Tweakeroo-fabric-1.15.2-0.10.0-dev.20200320.230739
Launch a world, then bring up the pause menu, your game should crash

## OptiFine Version
OptiFine 1.15.2 G1 pre10

## Installation Method
OptiFine in the mods folder

## Fabric/Forge Version
0.7.8+Build.188 fabric

## OptiFabric Version
1.0.0-beta7

## Other Installed Mods
https://pastebin.com/XmGXiBQX

## Log Files/Crash Reports
https://pastebin.com/eZa1yQmR

## Prior Testing
It doesn't seem to happen to others, I've asked a few people.

And It only happens with tweakeroo, If I remove OptiFine or Tweakeroo it will not crash.

**Comment by sp614x** [comment]
Fabric is not supported.
