### ISSUE TITLE
Viewing snow underground

### ISSUE THREAD

**Issue by QuentinC974** [sp614x/optifine#3628]
Hi,

I'm viewing snow through the floor when I'm mining an ore

**Comment by HiItsDevin** [comment]
Can you please be more specific? What version? Any video or screenshots? Are you using mods? Etc.

**Comment by HiItsDevin** [comment]
Nevermind, this is a vanilla bug that was fixed in 1.16.

**Comment by QuentinC974** [comment]
Okay thanks. 
It was 1.15.2 with only optifine.
Have a nice day.
