### ISSUE TITLE
[sp624x/optifine] Issue opened: Optifine cannot detect GPU

### ISSUE THREAD

**Issue by Avacious** [sp614x/optifine#3629]
## Description of Issue
When using Optifine, it shows that my graphics is intel integrated graphics and not my gtx 1660ti. It results in roughly 10 fps while using shaders and 30-50 without. instead of 100+ constantly.

## Steps to Reproduce
I would assume it will only work on a laptop with a dedicated graphics card since they both use the same output unlike a desktop with separate outputs

## OptiFine Version
Optifine 1.15.2 G1 pre9 and pre10

## Installation Method
standalone installer

## Log Files/Crash Reports
Any relevant log files. Drag and drop text files here to upload to GitHub directly, OR upload the complete contents to Pastebin. https://pastebin.com/

You can get logs from `.minecraft/logs`, and crash reports from `.minecraft/crash-reports`. 
Locating your `.minecraft` folder will depend entirely on your OS. See this page for details: https://minecraft.gamepedia.com/.minecraft

**DO NOT directly copy and paste log contents here on GitHub.**

## F3 Debug Screenshot
with Optifine
![2020-03-31_09 17 24](https://user-images.githubusercontent.com/62953341/78050495-26d05280-7331-11ea-9de0-eff761bb85ed.png)
without
![2020-03-31_09 21 57](https://user-images.githubusercontent.com/62953341/78050510-2afc7000-7331-11ea-9a55-bba787f273a2.png)

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
no
If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   - Only OptiFine and Forge
   - Only OptiFine, OptiFabric, and Fabric
- Does this happen without any mods at all?
   - Only Forge/Fabric by itself.
- Does this happen in OptiFine standalone?
- Does this happen in Vanilla without OptiFine?
- Have you tried using a binary search to find which mods cause this issue?
   - To find conflicting mods, split your mods into 2 groups (not including OptiFine/OptiFabric, obviously). Remove one group, and test in-game. Keep the group that has the problem, and repeat until no more mods can be removed without the issue disappearing.
   - Does the issue still happen with only the remaining mods installed?
      - Forge/Fabric and remaining mods, without OptiFine

## Additional Information
Here goes any final remarks and everything else that might not fit in the previous sections.

**Comment by yezhiyi9670** [comment]
Check your video card settings. You should default Java instead of the Launcher to use the NVIDIA card.

**Comment by sp614x** [comment]
Which GPU is being used is controlled by the graphics driver control panel.
Not related to OptiFine.
