### ISSUE TITLE
Memory leak when window unfocused

### ISSUE THREAD

**Issue by DiamondIceNS** [sp614x/optifine#363]
Running vanilla Minecraft 1.10.2 + Optifine D4 in windowed mode on Windows 10.  Whenever I release the mouse by opening the inventory or chat window, and then minimize the game or switch to another window, the game will steadily leak memory until it caps out at about 4 GB.  If I catch the game after a few seconds of this leaking, the game will freeze for a few seconds and then resume normal function, except none of the memory will be released.  If I wait too long (about 5 seconds) the game will have leaked too much memory and will lock completely.  Can reproduce it every time without fail.

**Comment by sp614x** [comment]
Error log?

**Comment by mindforger** [comment]
he said it freezes and hangs but it does not crash

**Comment by sp614x** [comment]
The error log (not crash report) has many details which are needed to track down the problem (forge version, mods, errors, resource pack, shader pack, etc).

**Comment by DiamondIceNS** [comment]
Could you please tell me how to find the error log?

I am not using Forge, mods, or shaders.  I do have two custom resource packs that add only sounds, plus Faithful 32x32 for Minecraft 1.10.

**Comment by sp614x** [comment]
In the vanilla launcher this is the tab "Game Output".

**Comment by DiamondIceNS** [comment]
[Here's the error log.](http://pastebin.com/PxRSdd4z)

I tested this without all of my resource packs and it still occurs.  I did find out that if I can get the game to respond after the leak, the garbage collector *will* deallocate the leaked memory over time.

**Comment by sp614x** [comment]
There is a problem with the sound library:

    [Sound Library Loader/INFO]: Starting up SoundSystem...
    [Thread-6/INFO]: Initializing LWJGL OpenAL
    [Thread-6/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
    AL lib: (EE) MMDevApiOpenPlayback: Device init failed: 0x80004005
    AL lib: (EE) MMDevApiOpenPlayback: Device init failed: 0x80004005
    [Thread-6/ERROR]: Error in class 'LibraryLWJGLOpenAL'
    [Thread-6/ERROR]: Unable to initialize OpenAL.  Probable cause: OpenAL not supported.
    [Thread-6/WARN]: ERROR MESSAGE:
    [Thread-6/INFO]: Could not locate OpenAL library.
    [Thread-6/WARN]: STACK TRACE:
    [Thread-6/INFO]: org.lwjgl.openal.AL.create(AL.java:156)
    [Thread-6/INFO]: org.lwjgl.openal.AL.create(AL.java:102)
    [Thread-6/INFO]: org.lwjgl.openal.AL.create(AL.java:206)
    [Thread-6/INFO]: paulscode.sound.libraries.LibraryLWJGLOpenAL.init(LibraryLWJGLOpenAL.java:164)
    [Thread-6/INFO]: paulscode.sound.SoundSystem.CommandNewLibrary(SoundSystem.java:1576)
    [Thread-6/INFO]: paulscode.sound.SoundSystem.CommandQueue(SoundSystem.java:2572)
    [Thread-6/INFO]: paulscode.sound.CommandThread.run(CommandThread.java:121)
    [Sound Library Loader/WARN]: ERROR MESSAGE:
    [Sound Library Loader/INFO]: Could not locate OpenAL library.
    [Sound Library Loader/INFO]: Starting up SoundSystem...
    [Thread-8/INFO]: Switching to No Sound
    [Thread-8/INFO]: (Silent Mode)
    [Sound Library Loader/INFO]: Sound engine started

**Comment by sp614x** [comment]
Also the resource pack is default, not Faithful32x:

    [OptiFine] *** Reloading textures ***
    [OptiFine] Resource packs: Default

**Comment by sp614x** [comment]
Maybe the custom resource packs that add sounds have a problem when the sound system can not start?

**Comment by DiamondIceNS** [comment]
> I tested this without all of my resource packs and it still occurs.

The sound library may be a different issue.  I have noticed Minecraft will start with no sound active, though reloading the resources with F3 + T will reinstate them.  I'll create another log and detail my process.

**Comment by DiamondIceNS** [comment]
So I did some more testing and I did end up managing to reproduce in vanilla Minecraft without Optifine.  This probably isn't an Optifine issue.  I'll take this up with Mojang's support.  Thank you for your time.
