### ISSUE TITLE
Sea lanterns put out orange light.

### ISSUE THREAD

**Issue by BugsBeHere** [sp614x/optifine#3630]
## Description of Issue
Sea lanterns put out orange light.

## Steps to Reproduce
place a sea lantern down

## OptiFine Version
All

**DO NOT directly copy and paste log contents here on GitHub.**

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine? No.

## Additional Information
Here goes any final remarks and everything else that might not fit in the previous sections.

**Comment by MrCheeze446** [comment]
this isn't even a bug, all lights put out the same color of light in minecraft
