### ISSUE TITLE
[Bug] Incompatibility with Litematica and Possible Scematica

### ISSUE THREAD

**Issue by Cat371** [sp614x/optifine#3633]
## Description of Issue
Causes certain blocks to glitch out
See Issue: https://github.com/sp614x/optifine/issues/2032
## OptiFine Version
Pre release 10

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
NA
If you've installed using Forge/Fabric:
- Does this happen without any mods at all? Litematica and Schematica
- Does this happen in OptiFine standalone? NA
- Does this happen in Vanilla without OptiFine? 
## Additional Information

This incompatibility causes schematic blocks to glitch, and most other blocks to turn rainbow colored when using shaders.

**Comment by Cat371** [comment]
Sorry its not great explanation, but it is relatively self explanatory, once again see issue #2032

**Comment by TheJSHuA** [comment]
This is not an issue with OptiFine, but rather an issue of how mods like Litematica and Schematica handle rendering, which has a tendency to break a lot of shaders.

**Comment by Cat371** [comment]
ok thx
