### ISSUE TITLE
[1.15.2][Shaders] Lighting from sun still shows in caves with some shaders

### ISSUE THREAD

**Issue by Legoman99573** [sp614x/optifine#3634]
## Description of Issue
Please provide as much detail as possible.

## Steps to Reproduce
1. Switch to shader like sildurs
2. Go in a cave
3. Set the time to day

## OptiFine Version
1.15.2 preview 12

## Installation Method
How did you install OptiFine? Did you use the included standalone installer, or did you drop the JAR file into your "mods" folder? 
Standalone Installer

## F3 Debug Screenshot
Minecraft's built-in debug screen provides *a lot* of useful information, and should be included even if the issue is not something that can be captured in a still image.
With sildurs enabled:
![image](https://user-images.githubusercontent.com/7460704/78104518-f8945680-73b4-11ea-9be4-6707a081f883.png)
Without sildurs enabled:
![image](https://user-images.githubusercontent.com/7460704/78104617-19f54280-73b5-11ea-8957-d95120dc8a31.png)

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
No

## Additional Information
Here goes any final remarks and everything else that might not fit in the previous sections.

**Comment by sp614x** [comment]
Fixed in pre22.
