### ISSUE TITLE
[1.15.2] Texture glitches when placing blocks

### ISSUE THREAD

**Issue by NathanRomanos** [sp614x/optifine#3635]
## Description of Issue
Some times when opening doors and placing/mining blocks I get this weird texture glitch where certain blocks disappear (never entities though) and then these multi-coloured light ray looking objects appear. This can be seen [here](https://i.imgur.com/rpyAamq.jpg). 

## Steps to Reproduce
1. Open and close certain doors
2. 

## OptiFine Version
1.15.2

## Installation Method
I put the .jar file into my mods folder

## Other Installed Mods
Sildurs Vibrant Shaders v1.22 High
Sildurs Vibrant Shaders v1.262 Medium

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
-No

## Additional Information
Here goes any final remarks and everything else that might not fit in the previous sections.

**Comment by HiItsDevin** [comment]
Are you using OptiFabric or OptiForge at all?

**Comment by BBftw** [comment]
looks like you are on a very old preview version. update to the latest

**Comment by sp614x** [comment]
Fixed in the latest preview.
