### ISSUE TITLE
[1.15.2 pre9 / pre12] Sudden drop of FPS

### ISSUE THREAD

**Issue by besenheim** [sp614x/optifine#3636]
## Description of Issue
I have been using OptiFine 1.15.2 pre9 for about two weeks or something and everything went as it should (even with fancy settings). Then I stopped playing and after five days I logged in to Minecraft again just to find out that my FPS is suddenly drastically low (I am guessing 1 frame per 5 seconds). I was still using OptiFine pre9 so I installed pre12 but that didn't fix this issue. I even tried setting everything in Video Settings to fast or off so it would improve the performance but that did'nt help either. At this moment I am playing Minecraft without OptiFine and it works just fine. So how is it possible that OptiFine is supposed to improve the performance but does the exact opposite?
(My brother has the same issue on his computer as well.)
Note: I am not using any shaders.

## OptiFine Version
OptiFine 1.15.2 HD U G1 pre9 / pre12

## Installation Method
Standalone installer from optifine.net (for both versions).

## Forge Version
1.15.2 Forge 31.1.25

## Other Installed Mods
None.

**Comment by BBftw** [comment]
How much ram do you have allocated to Minecraft?

**Comment by RandomGuyJCI** [comment]
Can you show a screenshot of your f3 menu and/or a log file so the dev can identify the issue more easily?

**Comment by besenheim** [comment]
![2020-04-01_14 31 01](https://user-images.githubusercontent.com/62986430/78137415-9293e780-7425-11ea-8514-060f0058c938.png)
Here is the F3 menu.

**Comment by besenheim** [comment]
And here is the latest log.
[latest.log](https://github.com/sp614x/optifine/files/4415073/latest.log)

**Comment by sp614x** [comment]
Pre12 is not compatible with Forge.
Please test with latest preview.
