### ISSUE TITLE
[Issue] Activating Shaders with pre12 causing texture mix-ups

### ISSUE THREAD

**Issue by Seppelbert** [sp614x/optifine#3638]
## Description of Issue
With Optifine version HD_U_G1 pre 12 and Minecraft version 1.15.2, with a custom resource pack and shaders active blocks seem to load with the wrong texture used, for example: cut sandstone is shown with bricks texture, as well as diorite blocks. When deactivating shaders, those blocks are rendered with their correct texture.

## OptiFine Version
HD_U_G1_pre12

## Installation Method
Included installer executing the .JAR file

##F3 Overlay Screenshots
![2020-04-01_13 20 59](https://user-images.githubusercontent.com/62995183/78132532-3200ac80-741d-11ea-8b02-bdfbe4d289a7.png)
![2020-04-01_13 33 04](https://user-images.githubusercontent.com/62995183/78132663-6e340d00-741d-11ea-86cf-3c78e3f20a85.png)
![2020-04-01_13 33 28](https://user-images.githubusercontent.com/62995183/78132668-6ffdd080-741d-11ea-8755-928857b35ad0.png)

**Comment by sp614x** [comment]
Resource pack link?

**Comment by Seppelbert** [comment]
Work in progress pack by me. i could send you a download link via private message, if you want

**Comment by sp614x** [comment]
You can DM me on discord.

**Comment by sp614x** [comment]
This is 2k resource pack and it needs a lot of GPU memory.
The shaders need 3x more memory due to normal/specular textures.
Probably the GPU is getting out of memory and overwriting some textures.

**Comment by sp614x** [comment]
Not reproducible with a 256x pack.
Looks like a driver bug.
