### ISSUE TITLE
Strange behavior with "Smooth World" option

### ISSUE THREAD

**Issue by jk1895** [sp614x/optifine#364]
Hello,
I was told I should report that. I wrote about it here:
https://www.reddit.com/r/feedthebeast/comments/5f4xb1/optifine_does_not_work_with_the_ftb_chunk_loading/

In short: Claimed far away chunks don't work correctly (only half correctly) with the option "Smooth World" set to ON (default setting).

Thank you very much for this mod.

**Comment by sp614x** [comment]
This is what Smooth World does.
It ticks (updates) only the chunks near the player in order to reduce lag.

**Comment by jk1895** [comment]
Then everything is good. Only I needed weeks to find out what was going on. Perhaps it would be good to set the option to off by default?
Thanks again.

**Comment by sp614x** [comment]
It is enabled by default only for single-core CPUs. 
These are quite rare nowadays and they suffer a lot as the game is currently optimized for multi-core CPUs.

**Comment by jk1895** [comment]
Hmm.... i never toched this option and i have an quad core CPU. It was set to on.
