### ISSUE TITLE
[Issue] Mobs not flashing red when hitting

### ISSUE THREAD

**Issue by DJaq02** [sp614x/optifine#3640]
When hitting hostile mobs they are not flashing red as they should.
Optifine version is 1.15.2 HD U G1 pre12

**Comment by seeruk** [comment]
Issue also present in pre13

**Comment by NiemandTV** [comment]
Duplicate of https://github.com/sp614x/optifine/issues/3598
(This is because the uniform `entityColor` is currently not working.)

**Comment by sp614x** [comment]
Duplicate of #3598.
