### ISSUE TITLE
[Category] Short description

### ISSUE THREAD

**Issue by LongHorse2** [sp614x/optifine#3643]
## Description of Issue
Either they shine from the moment i join, or i need to equid a torch in the left hand first, then the tools stay bright even when not using the torch. Also the shaderpack im using is SeusRenewed.

## Steps to Reproduce
1. Not much, cant seem to remove it
2. Equip a torch in the left hand while having an enchanted tool in the right.

## OptiFine Version
Optifine HD U G1 pre12

## Installation Method
Used the .jar installer from optifine.net

## Other Installed Mods
Pretty sure shaders is a part of optifine, but ill write it here just in case.
Otherwise no other mods

## F3 Debug Screenshot
![2020-04-01_15 22 20](https://user-images.githubusercontent.com/62999975/78142003-9aa35580-742c-11ea-9ae8-328da5f4e3de.png)

**Comment by naeqirelle2020** [comment]
![2020-06-09_10 11 40](https://user-images.githubusercontent.com/63185833/84129328-bed96f00-aa39-11ea-9ec7-4f561ac845bb.png)

Can't reproduce in latest preview

**Comment by sp614x** [comment]
Should work in latest preview.
