### ISSUE TITLE
depthtex2 includes hand/handheld objects

### ISSUE THREAD

**Issue by NiemandTV** [sp614x/optifine#3646]
## Description of Issue
The depth buffer depthtex2 includes the hand/handheld objects and translucent objects, even though it shouldn't. This bug makes it equal to depthtex0.

## Steps to Visualize
I've made a [test shaderpack](https://www.mediafire.com/file/bi9vn8uoqan48tk/depth_test.zip/file) to visualize the differences between depthtex0 and depthtex2. If depthtex0 is equal to depthtex2, the pixel will be rendered white.

- Expected behaviour (1.7.10-1.14.4): everything except for the hand/handheld objects and translucent objects is white
- Current behaviour (1.15.2): everything is white

## OptiFine Version
1.15.2_HD_U_G1_pre12 (all 1.15.2 versions)

## Additional Information
[This](https://github.com/sp614x/optifine/issues/3615) issue might be related to this bug.

`EDIT: Changed depthtex1 to depthtex0 and updated the test shaderpack thanks to zombye's comment.`

**Comment by zombye** [comment]
`depthtex2` currently also incorrectly includes translucent objects, meaning that currently it's actually equal to `depthtex0`.

**Comment by sp614x** [comment]
Fixed, coming in pre17.
