### ISSUE TITLE
[1.15 pre12] Parallax mapping on rails not working

### ISSUE THREAD

**Issue by L0laapk3** [sp614x/optifine#3649]
## Description of Issue
Parallax mapping on rails is no longer working. In pre10, it did work on rails but not on normal blocks, now the other way around.

## OptiFine Version
1.15 pre12

## Installation Method
Standalone

**Comment by sp614x** [comment]
What resource pack and shaders?

**Comment by sp614x** [comment]
Should be fixed in latest preview.
