### ISSUE TITLE
[1.15.2] CIT Custom Models not appearing in item frames

### ISSUE THREAD

**Issue by MissGhouls** [sp614x/optifine#3657]
## Description of Issue
CIT items appear as normal in the hotbar, but when placed in an item frame they revert to the item they were before. (For example, I have a microwave created from an Iron Block. In my hotbar it appears as a microwave, but when placed in an item frame, it is only an iron block). 

## Steps to Reproduce
1. Turn on the Ghoulcraft Pack (https://bit.ly/2wMNnD5 -- it's a large file and may cause lag in certain computers, apologies) using 1.15.2 MC (Version OptiFine 1.15.2 HD U G1 pre13)
2. Using the microwave as an example -- Take an Iron Block and rename it "Block of Iron_Microwave1" (It should appear in the hotbar as a white microwave). 
3. Place an Item Frame flat on the ground, and place the "microwave" into the frame. It will now appear as a regular block of iron. In 1.14 and 1.13, this appears as a 3d model of a microwave. 

## OptiFine Version
OptiFine 1.15.2 HD U G1 pre13

## Installation Method
Standalone Installer

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
CIT relies on Optifine in order to display. It works in 1.13 and 1.14 versions of Optifine, though.

**Comment by sp614x** [comment]
Fixed, coming in pre20.
