### ISSUE TITLE
[1.15.2] Incompatibility with Ultimacraft resource pack (pre13). Previously worked on pre12.

### ISSUE THREAD

**Issue by ghost** [sp614x/optifine#3661]
## Description of Issue
When I try to use the Ultimacraft resource pack, it loads the pack and then unloads it. This only occurs with the latest pre13 1.15.2 version of Optifine, but works with the older pre12 version.

## Steps to Reproduce
1. Apply the [Ultimacraft](https://www.curseforge.com/minecraft/texture-packs/ultimacraft) resource pack on OptiFine 1.15.2 HD U G1 pre13.

## OptiFine Version
OptiFine 1.15.2 HD U G1 pre13

## Installation Method
Used jar in mods folder.

## Fabric/Forge Version
Fabric, latest.

## OptiFabric Version
optifabric-1.0.0-beta8

## Other Installed Mods
*Every* single mod you have installed, besides OptiFine. Please don't leave anything out, even if you think it has nothing to do with the issue at hand. For long lists of mods, use Pastebin. https://pastebin.com/

- Advancements enlarger
- Appleskin
- AuthMe Fabric
- Beenfo (Bee Info)
- Better enchanted books
- Clear skies
- Devworld
- Fabric api
- VoxelMap
- FrameThrough
- Held item info
- Horse stats vanilla
- Malilib
- Mambiance
- Minihud Fabric
- Mod Menu Fabric
- OkZoomer
- OptiFabric
- Pling
- random block placement
- Resource pack organizer
- Shulker box tooltip
- Smooth scrolling everywhere
- Void fog

## Log Files/Crash Reports
Any relevant log files. Drag and drop text files here to upload to GitHub directly, OR upload the complete contents to Pastebin. https://pastebin.com/

You can get logs from `.minecraft/logs`, and crash reports from `.minecraft/crash-reports`. 
Locating your `.minecraft` folder will depend entirely on your OS. See this page for details: https://minecraft.gamepedia.com/.minecraft

**DO NOT directly copy and paste log contents here on GitHub.**

## F3 Debug Screenshot
![image](https://user-images.githubusercontent.com/52900125/78300768-a7dc4500-74fd-11ea-8fe2-0a205c72084d.png)

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   Yes
- Does this happen without any mods at all?
   Yes
- Does this happen in OptiFine standalone?
  Yes
- Does this happen in Vanilla without OptiFine?
  No
- Have you tried using a binary search to find which mods cause this issue?
   No, it still doesn't work in OptiFine standalone.

## Additional Information
![image](https://user-images.githubusercontent.com/52900125/78301130-436db580-74fe-11ea-96b4-02a193dbf6e0.png) This pops up in the corner after attempting to load the resource pack.

**Comment by lsdxm** [comment]
Same thing happens to me with a bunch of different packs, mostly ones that change the UI. Can't use VanillaTweaks textures, Faithful's dark gui or bread hunger packs and a few others.

Happens with OptiFabric beta8 on MultiMC and also Vanilla launcher, only on pre13. All of these worked fine on pre12.

**Comment by sp614x** [comment]
Can you post the error log?

**Comment by KaiAF** [comment]
No reply from the author of the bug report
