### ISSUE TITLE
[Website] Adverts used on website are distributing Malware, Trojans & Virusses

### ISSUE THREAD

**Issue by Odysseius** [sp614x/optifine#3667]
At the moment, some of the ads shown when trying to download the mod link directly to malicious software, some of them disguising as large "DOWNLOAD" buttons. This is causing some users to distrust not just the website optifine.net itself, but also helpers trying to give the download link to users asking for it - and ultimately leading to us recommending users to use Adblock software.

**Comment by lsdxm** [comment]
I mean.... People should be using adblock software. Whether optifine or your favorite youtuber benefits from ads or not is not reason to expose yourself to tracking and mal/Spyware. 

It's easy for me to say as I'm not the maker of optifine, but as unfortunate as it may be, ads are a terrible and nefarious source of income and should be advised against at all costs. Recommended adblock to people whether you're aware of tracking/Spyware in ads or not.

**Comment by sp614x** [comment]
The adf.ly links were replaced with adfoc.us and a fixed Server Hosting ad. 
This should fix most ad problems.
