### ISSUE TITLE
[Shaders] 1.15.2 Pre-13 Transparent items when in bed

### ISSUE THREAD

**Issue by TheNev2847** [sp614x/optifine#3668]
## Description of Issue
Items in main hand and off hand appear transparent when sleeping in a bed while shaders are used

## Steps to Reproduce
1. Hold item in hand
2. sleep in a bed

## OptiFine Version
1.15.2 Pre-13

## Installation Method
Used installer from optifine.net

**Comment by sp614x** [comment]
Should be working in latest preview.
