### ISSUE TITLE
[installation] can't select the install or extract option

### ISSUE THREAD

**Issue by JustJerbotPLAYZ** [sp614x/optifine#3669]
## Description of Issue
so, I downloaded the new 1.15.2 pre13 optifine version, and wanted to install it. I install optifine by opening the .JAR application and installing it in the location optifine provides, this goes perfectly fine, until the pre13 version. when I try to download the pre12 version ir will let me, but when I try it with the pre13 version it won't, it just simply won't let me click install or extract. I use Mac OS, keep the version of my operating system up to date (as long as apple lets me) and I don't know why it won't let me, I've tried to change the installation folder, but that doesn't work either. hope this gives you enough information, however, it does work using OptiFabric beta8 for 1.15.2 and forge loader 0.7.9+build.190 1.15.2

## Steps to Reproduce
1. download the latest pre13 version of optifine 1.15.2
2. have Mac OS Catalina 10.15.3 installed
3. try to download optifine 1.15.2 pre13 via double clicking the .JAR file
4. be confused because it won't let you

## OptiFine Version
Preview_OptiFine_1.15.2_HD_U_G1_pre13.jar

## Installation Method
How did you install OptiFine? Did you use the included standalone installer, or did you drop the JAR file into your "mods" folder?

## Fabric/Forge Version
fabric works, normal way of installing without mod loader doesn't

## Other Installed Mods
none

## Log Files/Crash Reports
none, since it is an install thing

**DO NOT directly copy and paste log contents here on GitHub.**

## F3 Debug Screenshot
no F3 menu to use since it won't install

## Prior Testing
nothing to test

## Additional Information
I have no information, but I hope that this is enough information, if not, feel free to reach out to me, idk how, im new to GitHub

**Comment by JustJerbotPLAYZ** [comment]
ok, so I just tried it again after it worked using OptiFabric and fabric and it now seems to work (?), I don't know how, it seems to witchcraft to me...

**Comment by emmokey** [comment]
I am having the same problem and I tried OptiFabric and it has not helped, any other ideas?
