### ISSUE TITLE
Biome Specific Textures

### ISSUE THREAD

**Issue by Opptitronica** [sp614x/optifine#367]
I'm a texture developer, to be precise I'm the creator of Pulchra PurePBR. I'm remaking my textures and I was wondering if there is anyway to do biome specific textures. The biome tag does not seem to work with my testing. Am I doing something wrong or is it not avaliable/working anymore?

**Comment by sixfootblue** [comment]
It should still work. I've been using it in some of my resourcepacks with no issues so far. How are you writing up the biome list in your .properties file?

**Comment by Opptitronica** [comment]
Something like this, Biomes=Desert. I even copied the biome list from other resourcepacks properties files and was not able to do it (maybe they had it improperly setup also. Can you share the text of a properties file using the biome tag that's working? I'd really appreciate it.

**Comment by sixfootblue** [comment]
Sorry, I misinterpreted what I was seeing. The biome specific textures don't seem to be working for me either.

I think the rest of my CTM is broken too. The vertical ctm I had on some blocks isn't working anymore. I've removed all the capitalization from my folders and filenames too, so I'm not sure what the problem could be.

**Comment by Opptitronica** [comment]
Darn, well hopefully sp614x can get this fixed. My pack really relies on these features working. My random textures are working but not with shader support. In other words the textures are randomized but normal maps and specular are not being applied to the right textures anymore. They used to be locked to the specific texture even when they were randomized :/

**Comment by sixfootblue** [comment]
@sp614x Do you think it would also be possible to implement a display name tag for the container blocks that are able to keep their custom name when placed on the ground in 1.11? (Brewing stands, furnaces, dispensers, hoppers, enchanting tables, and beacons)

**Comment by sp614x** [comment]
Preview B2 for 1.11 has a bugfix for older resource packs (v2).
Alternatively change the resource pack version to 3 and it should work with B1.

**Comment by Opptitronica** [comment]
@sp614x um, what? Will this fix the biome textures or the normal maps applying to random textures? If so how do I do that? I'm not sure what you mean by resourcepack version.

**Comment by sixfootblue** [comment]
I don't mess around with normalmaps so I can't vouch for that, but switching to v3 fixed my ctm and colormap issues. Thanks!

**Comment by Opptitronica** [comment]
What is v3 @sixfootblue ? Is that the Optifine version please someone enlighten me.

**Comment by sixfootblue** [comment]
Is the version number listed in the pack.mcmeta when you open up a zipped resource pack (file in between the assets folder and pack.png). Just open it up with a text editor like notepad or notepad++ and change "pack_format": to 3

**Comment by sp614x** [comment]
Updated preview B2 with a 1.11 bugfix for custom potion colors and textures.
Is everything working now?

**Comment by sixfootblue** [comment]
Things seem to be working fine for me.

**Comment by Opptitronica** [comment]
Works perfectly now, but another question how do I change it so that for instance if I want my grass to be brown instead of green how would I do this? I think this would be a colormap tweak but I have no idea how to do that.

**Comment by sixfootblue** [comment]
There's a bunch of info on how to modify colormaps here.
https://bitbucket.org/prupe/mcpatcher/wiki/Biome_Palettes
