### ISSUE TITLE
[Category] Short description

### ISSUE THREAD

**Issue by LutherLucario** [sp614x/optifine#3671]
I am having an issue with my minecraft locking up and freezing after about 5 minutes of using optifine with shaders, my computer can support shaders so i know that isn't the issue, i would like to know if anybody else is having the same issue.

**Comment by Regnander** [comment]
Can you post a F3 screenshot so we can tell what version, settings and hardware you are using?

**Comment by sp614x** [comment]
No details given for 2 months.
Closed as stale.
