### ISSUE TITLE
Layered Custom Colourmaps

### ISSUE THREAD

**Issue by SkaliberWasTaken** [sp614x/optifine#3672]
Custom colormaps are really powerful, and I've been using them a lot recently, however, I can't help but feel like they're lacking, in that you can only use them to tint full blocks, and not part of a texture.

I would really like the possibility to tint stone, and not have the ore blocks look out of place, as currently, the best solution is to either make ore greyscale, which is obviously counter intuitive, or mimic the colourmap, by instead using biome detection with CTM to fill in where the colormap falls short.

This is a little frustrating, as the documentation even recommends using custom colourmaps to change stone, and the ore blocks.

![image](https://user-images.githubusercontent.com/50083260/78415974-35628680-761d-11ea-8d03-3418e67b51e7.png)

I'm also a massive fan of emissive textures, and like the way they work, and feel as though colourmaps should work very similarly, with an option for an overlay which has the colourmap tint applied, and a base texture which the colourmap ignores.

Needless to say I have no idea if this has been excluded due to a technical limitation, but it seems like a really obvious and (to me at least) helpful feature which would hugely improve custom colormaps!

**Comment by silentnoodlemaster** [comment]
did you know that you can do this on github :)  

https://github.com/sp614x/optifine/blob/d06503323e49e8fe042472eb7bc185de097be4a0/OptiFineDoc/doc/colormap.properties#L45-L46

**Comment by SkaliberWasTaken** [comment]
I did not know that, thank you

I'm not a regular GitHub user, I only use it for optifine

**Comment by SkaliberWasTaken** [comment]
Will re-open as part of a request megathread.
