### ISSUE TITLE
[Shaders] The horizon repeats with Chocapic13 V7.1.1 Lite shaders

### ISSUE THREAD

**Issue by PobbleBonk** [sp614x/optifine#3673]
## Description of Issue
The horizon repeats with Chocapic13 V7.1.1 Lite shaders

## Steps to Reproduce
1. Turn on Chocapic13 V7.1.1 Lite shaders 
2. Look in distance and see repeating background
Video showing Issue
![Screen-Recording-2020-04-04-at-1 2](https://user-images.githubusercontent.com/21999675/78416997-58228880-7679-11ea-9307-628ac8434d49.gif)

## OptiFine Version
OptiFine 1.15.2_HD_U_G1_pre13

## Installation Method
Standalone installer

## Other Installed Mods
Chocapic13 V7.1.1 Lite shaders 

## F3 Debug Screenshot
<img width="1280" alt="Screen Shot 2020-04-04 at 12 34 12 pm" src="https://user-images.githubusercontent.com/21999675/78415906-99626a80-7670-11ea-8f11-488a250d89ea.png">

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
No

## Additional Information
Here goes any final remarks and everything else that might not fit in the previous sections.

**Comment by EternalMC** [comment]
looks like a driver issue

**Comment by sp614x** [comment]
This is the missing void rendering. 
Best visible on a sky world:

![image](https://user-images.githubusercontent.com/16635441/83949769-da6c2c00-a825-11ea-8f96-bb82cb9e8ac0.png)

**Comment by sp614x** [comment]
Fixed in pre22.
