### ISSUE TITLE
[Cape] Haven't been able to see my cape or others' capes for a few years.

### ISSUE THREAD

**Issue by HEROproductions** [sp614x/optifine#3675]
## Description of Issue
I donated in February 2017 and received my cape and it worked fine. At some point, probably months later, I was no longer able to see capes, mine or anyone else's. I just ignored it for a couple years because the cape wasn't really the reason I donated, but recently I've decided I want to be able to see capes again.

So to summarize a bunch of stuff so we can skip the basic troubleshooting stuff:
- Options > Skin Customization > Cape is set to ON
  (This is properly reflected in options.txt)
- Options > Video Settings > Details > Show Capes is set to ON
    (This is properly reflected in optionsof.txt)
- Other people CAN see my cape, and it DOES display properly on optifine.net in the cape editor as well as [https://namemc.com/profile/HERO_25.2](https://namemc.com/profile/HERO_25.2)
- I have reinstalled the latest version of Optifine (which was `1.14.4 HD U F5` at the time)
- I have uninstalled the Minecraft launcher and reinstalled it
- I have tried disabling my firewalls
- I have tried older versions of Minecraft (with Optifine) without any luck
- The problem persists in any multiplayer server as well as singleplayer.

## Steps to Reproduce
1. I open Minecraft with Optifine

## OptiFine Version
I have this problem in every version of Optifine I've tried, including `1.14.4-OptiFine_HD_U_F3`, `1.13.2-OptiFine_HD_U_E4`, `1.8.9-OptiFine_HD_U_H6`, etc. Safe to say I don't think this is related to the version of Optifine or Minecraft.

## Installation Method
I have this problem with both standalone Optifine as well as Optifine running in Forge or Fabric. I mainly play in Fabric but I've done all of my troubleshooting for this issue in standalone Optifine so that Fabric couldn't affect it.

## Log Files/Crash Reports
[Here's a log file of me opening Minecraft and connecting to Hypixel](https://github.com/sp614x/optifine/files/4430935/2020-04-04-2.log)

## F3 Debug Screenshot
![Here's a screenshot I took just now](https://user-images.githubusercontent.com/60427702/78422022-3c839780-7611-11ea-92d1-598a46dd2467.png)

## Additional Information
My username is `HERO_25`. I feel like the issue is probably that my client can't connect to the cape servers properly, for some reason. I tried to ask for support in the Optifine Discord server, which they mentioned that they had a similar case previously but didn't really know how to help me, so I figured I try here. Searching online I've only seen three instances of very similar cases where they had all of their settings correct and other players could see their capes: https://hypixel.net/threads/i-cant-see-my-optifine-cape-but-others-can.1408139/ and https://hypixel.net/threads/optifine-cape-not-showing-solved.2215562/
the second of which was actually solved, but they just reinstalled the game (which I've already tried).
The third case I saw was on YouTube, but they solved it by just getting a new computer, which isn't an option for me.

Thank you very much for reading this and I really hope you can help me solve this issue! :)

**Comment by UkaszYTPolak** [comment]
Same

**Comment by Bqckstory** [comment]
Sameee

**Comment by KaiAF** [comment]
Is this still an issue? I feel like I remember helping you in Discord myself, if I am right. I may think I know what / how to fix the problem.

**Comment by HEROproductions** [comment]
Sorry for a late replay, I got the notification but then completely forgot for a few days :sweat_smile: Anyway, yes it is still an issue. Although unfortunately it doesn't seem to be an Optifine issue, because my internet also can't connect to other servers (Optifine capes, Among Us multiplayer, various other games) :frowning:

Our ISP has been very unhelpful and saying it's not on their end :<

If you do have any ideas/advice though, I'd love to hear it! Thanks! :)

**Comment by KaiAF** [comment]
Yeah, it most likely is your ISP. In that case, I am not really sure how to help you, unfortunately. But since most likely this is not an OptiFine issue, I am going to close the ticket.
