### ISSUE TITLE
Custom entity models

### ISSUE THREAD

**Issue by LoopyRuffian** [sp614x/optifine#3677]
I make a cem model and it doesn't work.
![Untitled](https://user-images.githubusercontent.com/63148602/78439772-dd0ca280-7677-11ea-8342-2e626187cc76.png)

Steps to Reproduce
I make a cem model put it in the cem folder in optifine with an image
I made a minecart cem model that is how you can find the bug

OptiFine Version
Recent optifine 1.15.2 version

Installation Method
I opened the .jar file and clicked install.

Other Installed Mods
No other mods installed

Log Files/Crash Reports
No log or crash files.

F3 Debug Screenshot
![2020-04-04_13 19 51](https://user-images.githubusercontent.com/63148602/78439605-cebe8680-7677-11ea-9494-b554e98d4a22.png)

Prior Testing
If you've installed standalone:
It is a minecart cem model and does not work in vanilla Minecraft.

Additional Information
I don't have anything else.

**Comment by HiItsDevin** [comment]
Do CEM testing in 1.14.4 buddy. 1.15.2 optifine resource pack related stuff doesn't fully work yet.

**Comment by KaiAF** [comment]
This seems to be fixed. Let me know if you are still having issues, please.
