### ISSUE TITLE
No way to scale internal render resolution while in fullscreen

### ISSUE THREAD

**Issue by AmphetamineRush** [sp614x/optifine#3679]
My display is 3440x1440 native, so while running advanced shaders, like SEUS PTGI, Optifine runs at very low fps in fullscreen even on a RTX 2080. I'd like to be able to run at an arbitrary resolution (or simply a percentage of fullscreen res) that's then scalled to my fullscreen resolution.

I've tried creating custom resolutions in nvidia cp, Optifine just doesn't list them in the resolution slider. I even tried changing my resolution to the custom one and then using "Fullscreen Mode: Current" but Optifine resolved to a 16:9 image with black borders and my cursor position didn't line up with where it actually was on screen.

Many thanks.

**Comment by EternalMC** [comment]
in the shader selection tab there is a res modifier.

**Comment by AmphetamineRush** [comment]
Ahh, thank you, that's not where I'd expected to find that setting!
