### ISSUE TITLE
CEM (pillagers not working)

### ISSUE THREAD

**Issue by Scarecrow-01** [sp614x/optifine#3681]
## Description of Issue
My resourcepack used to have custom pillager having the same model as the player (steve) but appear to be ignoring the custom model in 1.15.2

Same goes for some fishes but that might be my fault since I'm experimenting a lot with their model. The pillager, on the other hand, works perfectly in the latest 1.14.4 build.

## OptiFine Version
OptiFine 1.15.2 HD U G1 pre13

## Installation Method
I have used the .jar standalone  installer

**Comment by sp614x** [comment]
Fixed, coming in pre19.
