### ISSUE TITLE
Item Frame combined with Birch Pressure Plate doesn't fit properly

### ISSUE THREAD

**Issue by LuckDuracell** [sp614x/optifine#3682]
A fun trick I've always used in my builds has been to put a birch pressure plate on the same block as an item frame, since the border of the item frame has the same texture as birch. This way, the item simply looks like its sitting on the pressure plate, and the item frame is hidden. Though with the 1.15 optifine, it seems to be not aligning properly or something. Gif attached to show problem

![](https://im2.ezgif.com/tmp/ezgif-2-5e12ed8d2fa1.gif)

**Comment by Regnander** [comment]
Can you repost the gif? It seems to have disappeared.

**Comment by sp614x** [comment]
The item frame and pressure plate can be combined.
If you step on the pressure plate it stays down and there is z-fighting on the top side.
OptiFine works identically to vanilla 1.15.2
