### ISSUE TITLE
Weapons with enchantments not play the glow animation (is stopped)

### ISSUE THREAD

**Issue by SoyKappy** [sp614x/optifine#3684]
![2020-04-05_06 10 02](https://user-images.githubusercontent.com/63183913/78469528-fd8d3900-7719-11ea-800d-11f596969bd6.png)

there are some shaders (I personally have experienced this with the Chocapic Toaster Edition) in which the purple animation of the armors, weapons, or enchanted tools are frozen, and this in the 1.14 never happened to me

**Comment by EdwardNottingham** [comment]
It is the same for me whilst using shaders, however, they animate fine without shaders. I think this is known by the devs right now though, as I saw another open issue about something similar. 
![5TqtYSQk8R](https://user-images.githubusercontent.com/9078887/78617986-735be680-7879-11ea-8b37-19e2ec792527.gif)

**Comment by sp614x** [comment]
Should be working in latest preview.
