### ISSUE TITLE
[CEM] CEM textures not displaying/found by Optifine 1.15.2pre13

### ISSUE THREAD

**Issue by tagifford** [sp614x/optifine#3689]
## Description of Issue
CEM (for Cow, specifically), do not load the custom textures properly. The model itself loads fine, but tries to use the default texture instead of the provided texture. I have tested the files in stable releases of Optifine and they work as expected

## Steps to Reproduce
Try to use a CEM for Cow

## OptiFine Version
1.15.2pre13

## Installation Method
Used installer

**Comment by Fullgor** [comment]
I have the same issue with pigs and phantoms, optifine loads the models correctly but wants to use the mob texture instead of the provided ones. Guess it'll be the same with all mobs

**Comment by Norzeteus** [comment]
I have the same problem with my own txt-pack Future-Space.In 1.14.4 it works very well,but in vers.
1.15.2pre13 it seems, that the special textures inside the cem-folder could not be read.
Affected are bed, sheep and wolf, cow works as it takes original texturepath.

**Comment by Luke18033** [comment]
I have this issue with minecarts, using 1.15.2pre15.

**Comment by Norzeteus** [comment]
Using preview_OptiFine_1.15.2_HD_U_G1_pre19, my "lifebox" bed doesn`t work correct, model parts are pushed together and the texture is taken from normal bed and not it`s ow.
![wrong bed](https://user-images.githubusercontent.com/24456750/83404990-e9a93f00-a40b-11ea-8b53-d2bc905509e8.png)
so it should like...
![bed](https://user-images.githubusercontent.com/24456750/83404434-f2e5dc00-a40a-11ea-834a-673dab68dbcf.png)
also my wolf does not appear at all,so it should look like
![wolf](https://user-images.githubusercontent.com/24456750/83405183-44429b00-a40c-11ea-867d-c45d61444103.png)
Cow,sheep and spider are working correct.
My Cem test folder: 
[Norzeteus CEM test 1.15.zip](https://github.com/sp614x/optifine/files/4711024/Norzeteus.CEM.test.1.15.zip)

**Comment by Deviouslrd** [comment]
Pre19 fixes bed and wolf CEM, among numerous other fixes.

**Comment by heinrich26** [comment]
Seems that custom textures trough the model definition dont load on the model, as I tested arround, I found that you can use the random mob feature for that (just make a <mobname>.properties and add skins.1=2, so the <mobname>2.png is the new texture) {that doesnt support multiple textures on one Entity}, but in my case its not optimal!

**Comment by Norzeteus** [comment]
my wolf is still not working, I am currently using preview OptiFine_1.15.2_HD_U_G1_pre26, I have since been able to restore my lifebox, it works again now.

[wolf CEM.zip](https://github.com/sp614x/optifine/files/4787449/wolf.CEM.zip)

**Comment by Norzeteus** [comment]
Now I have finally got my wolf working again, but the problem is, if you want to tame it, this happens ...
Using preview_OptiFine_1.15.2_HD_U_G1_pre30, no other mods...
![wolf_tame](https://user-images.githubusercontent.com/24456750/86509554-21c7e700-bde9-11ea-87a3-86c4a2ad8839.png)
[wolf_cem.zip](https://github.com/sp614x/optifine/files/4872370/wolf_cem.zip)

**Comment by Luke18033** [comment]
Does this still happen? It's fixed for me, but I'm on 1.16.

**Comment by KaiAF** [comment]
This seems to be fixed. If it's still an issue, let me know, please.

**Comment by JavierOwnerMC** [comment]
the code or the location of each part of the wolf is wrong when counting the actions of the entity.
