### ISSUE TITLE
Linear Normal Map Filtering

### ISSUE THREAD

**Issue by robobo1221** [sp614x/optifine#369]
Hey sp614x!

I have a suggestion for the shaders part of optifine.
Can you maybe add back the option "linear and nearest" filtering for normal mapping?
This option i believe was availible at the time when 1.6.4 was released. It made the normal mapping not harsh but smooth.
We currently dont have this option and its been set to nearest. 

So, can you add this option back? Maybe add it to the shaders.propperties too?
Thank you very much.

Best regarts,

Robobo1221

**Comment by Strum355** [comment]
Did i hear...normal map filtering? i leik this

**Comment by sp614x** [comment]
The normal and specular textures should use the same filtering as the main texture.
The settings Mipmap Levels and Mipmap Type should control the filtering of main, normal and specular textures.
Normal textures with:
- mipmaps OFF: http://i.imgur.com/iCsF3OX.png
- mipmaps MAX: http://i.imgur.com/C5J58sq.png
