### ISSUE TITLE
[Rendering] Sign updates flashing

### ISSUE THREAD

**Issue by asbyth** [sp614x/optifine#3694]
## Description of Issue
Updating a sign through the server(?) causes the entire sign to flicker instead of the thing that's selected.

## Steps to Reproduce
Log into Hypixel, go to Skyblock, open the bankers menu, open the deposit/withdraw menu.

## OptiFine Version
1.8.9 L5

## Installation Method
Standalone & Forge.

## Fabric/Forge Version
1.8.9 - 11.15.1.2318

## F3 Debug Screenshot
![image](https://user-images.githubusercontent.com/36578995/78581971-9b5c3300-7802-11ea-9b56-d49ce471f980.png)

## Prior Testing
Doesn't happen in Vanilla, GIF provided.
![ezgif-5-ae7756479b2b](https://user-images.githubusercontent.com/36578995/78582137-d2324900-7802-11ea-861f-0ef1cdd5b713.gif)

**Comment by asbyth** [comment]
update: noticed that this is a dupe of #3132, keeping open as mine provides visual representation

**Comment by asbyth** [comment]
updating to mention that the bug may be caused by this method introduced in L5, not sure where the bug would lie in this, but it's the only thing that's changed in the `TileEntitySignRenderer` class besides L5 not replacing mc's lvt
![image](https://user-images.githubusercontent.com/36578995/94993646-861d5280-0560-11eb-87c7-ff54a84915cb.png)
![image](https://user-images.githubusercontent.com/36578995/94993673-b5cc5a80-0560-11eb-863c-27cee16d4765.png)

**Comment by asbyth** [comment]
fully fixed this in my own mod [Patcher](https://sk1er.club/mods/patcher)

the fix was done as such:

add a public static field in `GuiEditSign` called whatever, i went with `currentlyEditedSign`
assign `currentlyEditedSign` in the `GuiEditSign` constructor to the `teSign` parameter
add `currentlyEditedSign = null` to `GuiEditSign#onGuiClosed` to ensure it cleans itself up
in `TileEntitySignRenderer#isRenderText`, on the line `if (!Config.zoomMode && tileEntity.lineBeingEdited < 0)`, add `&& `tileEntity != GuiEditSign.currentlyEditedSign`

this issue is now fixed with those changes, perhaps get this into L6 along with #3474 as they're incredibly easy fixes and would essentially restore how i7 acted.

**Comment by DJtheRedstoner** [comment]
Please resolve this as well as #3616 and #1470 before 1.8.9 M8 pre2.

**Comment by sp614x** [comment]
Coming in M5_pre2.
