### ISSUE TITLE
Game crash while using shaders (1.15.2)- Batching chunks error.

### ISSUE THREAD

**Issue by iwillsnusnu** [sp614x/optifine#3695]
The following was the crash info:
The game crashed whilst batching chunks.
Error: java.lang.NullPointerException: Batching Chunks

The crash report is included below:
[Crash Report April 6th.txt](https://github.com/sp614x/optifine/files/4440747/Crash.Report.april.6th.txt)

Specs if needed:
Processor: 1.8 GHz Intel Core i5
Memory: 8 GB 1600 MHz DDR3
Graphics: Intel HD Graphics 6000 1536 MB

EDIT: Shaders used: Sildurs Vibrant Shaders v1.27 Lite

**Comment by Astropilot** [comment]
From the Sildurs shader download page for version 1.27:
> If minecraft is crashing delete "entity.properties" inside the shaderpack zip file. It's an optifine bug.

Have you tried this manipulation to see if it solves the crash problem?

**Comment by iwillsnusnu** [comment]
@Astropilot I'll try that and see what happens, thanks for the suggestion! I wish there were a way to reduce lag more than Optifine already does. I know that macs aren't made for gaming, but it's all I have right now :)

**Comment by iwillsnusnu** [comment]
> From the Sildurs shader download page for version 1.27:
> 
> > If minecraft is crashing delete "entity.properties" inside the shaderpack zip file. It's an optifine bug.
> 
> Have you tried this manipulation to see if it solves the crash problem?

So far no more crashes, so I'd say it worked :)
