### ISSUE TITLE
CRASH; Description: Unexpected error  java.lang.IndexOutOfBoundsException: index 16777301

### ISSUE THREAD

**Issue by WinterySnowfall** [sp614x/optifine#3697]
## Description of Issue
Please provide as much detail as possible.
**Will randomly crash my game as much as 15 minutes in to 4 hours.** 

## Steps to Reproduce
1. What do you do... 
2. ...to find this bug?
**Nothing, just walking around or even standing still** 

## OptiFine Version
 version 1.15.2 preview 
Self-explanatory. 

## Installation Method
How did you install OptiFine? Did you use the included standalone installer, or did you drop the JAR file into your "mods" folder?
dropped the jar folder into my mods folder, and opened and ran the installer (standard installation from the optifine website. 

## Fabric/Forge Version
**If OptiFine is installed as standalone, you can remove this section.**
forge?... i think

## OptiFabric Version
**If OptiFine is installed as standalone, or you're using Forge, you can remove this section.**

## Other Installed Mods
*Every* single mod you have installed, besides OptiFine. Please don't leave anything out, even if you think it has nothing to do with the issue at hand. For long lists of mods, use Pastebin. https://pastebin.com/
mods should be included within the crash report. 
**If OptiFine is installed as standalone, remove this section.**

## Log Files/Crash Reports
Any relevant log files. Drag and drop text files here to upload to GitHub directly, OR upload the complete contents to Pastebin. https://pastebin.com/

You can get logs from `.minecraft/logs`, and crash reports from `.minecraft/crash-reports`. 
Locating your `.minecraft` folder will depend entirely on your OS. See this page for details: https://minecraft.gamepedia.com/.minecraft

https://cdn.discordapp.com/attachments/423433009568546827/696832976863887410/crash-2020-04-06_14.49.27-client.txt

**DO NOT directly copy and paste log contents here on GitHub.**

## F3 Debug Screenshot
Minecraft's built-in debug screen provides *a lot* of useful information, and should be included even if the issue is not something that can be captured in a still image.

To open this menu, simply press `F3` on your keyboard while in-game. Please ensure the text is easily readable. Depending on the size/resolution of your monitor, you may have to adjust your GUI scale for all text to be completely visible on-screen.

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
no
If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   - Only OptiFine and Forge
   - Only OptiFine, OptiFabric, and Fabric
- Does this happen without any mods at all?
   - Only Forge/Fabric by itself.
- Does this happen in OptiFine standalone?
- Does this happen in Vanilla without OptiFine?
- Have you tried using a binary search to find which mods cause this issue?
   - To find conflicting mods, split your mods into 2 groups (not including OptiFine/OptiFabric, obviously). Remove one group, and test in-game. Keep the group that has the problem, and repeat until no more mods can be removed without the issue disappearing.
   - Does the issue still happen with only the remaining mods installed?
      - Forge/Fabric and remaining mods, without OptiFine

## Additional Information
Here goes any final remarks and everything else that might not fit in the previous sections.

**Comment by WinterySnowfall** [comment]
[crash-2020-04-06_14.49.27-client.txt](https://github.com/sp614x/optifine/files/4440939/crash-2020-04-06_14.49.27-client.txt)

**Comment by WinterySnowfall** [comment]
![image](https://user-images.githubusercontent.com/63265167/78608031-5eea0080-781d-11ea-825c-e530c28fc329.png)

**Comment by WinterySnowfall** [comment]
Also using Sildurs Shaders and John Smith Legacy Resource Pack

**Comment by TropheusJ** [comment]
Not sure if relevant but torch slabs is out of date

**Comment by WinterySnowfall** [comment]
Is it really? the latest file on curseforge sais that I have 1.6.5 (the newest version)

**Comment by TropheusJ** [comment]
You have it for 1.15.1

**Comment by WinterySnowfall** [comment]
lmao. good catch. I didn't see that

**Comment by WinterySnowfall** [comment]
thats so weird....that file on curseforge downloads as 1.15.2, but only downloads as 1.15.1
