### ISSUE TITLE
[Shaders][1.15.2 pre13] Drop Frames after a time playing.

### ISSUE THREAD

**Issue by OkamiFox** [sp614x/optifine#3699]
First of all, thank the existence of Optifine to the developer team, having say this i will explain a few things and problems that I am experiencing about playing Minecraft.
We have in home 2 PC, one INTEL and other AMD. 

*AMD Case:

FX8350 (8cores - 4.0GHZ)  Undervolted (a little and stable for temps) CPU, RX570 8GB, 16GB/DDR3 RAM(1600mhz), SSD´s and all you can imagine.

I have a very large loss of performance going from 90/100 FPS to 40 in approximately 5 minutes using shaders and 7/8 chunks, causing my gaming experience to be seriously affected, and not letting me record the screen or streaming.

*INTEL CASE:

Is a MSI Portable Laptop from 2017, 1050TI 4GB, I7 7700HQ (4cores 8 threads 3,4ghz), 16GB DDR4 RAM (2400mhz)
SSD´s and all you can imagine.

I have a similar problem with the drops no so aggressive, but they are not very stable, a few fall only in crowded places. Sometimes digging I go from having 100FPS to 70 or 60 at a time (the quantity shoots up and many times falls suddenly).

¿Can help me please?

-Things that i have done to try to solve, or find out that could be the cause of this problem.

1-Check hardware temps, and change the thermal paste from GPU/CPU.
2-Reinstall display drivers, before use DDU (display driver Utility)
3-Reinstall Minecraft.
4-Reinstall Optifine.
5-Erase Shaders and Reinstall.
5.1- Of course i try other packs, and devs.
6-Config in low, medium, high the shaders with the same result.
7-Give to JAVA more RAM, by default the game gave 2GB, I changed it to 4GB.
8-Change from complete screen to windowed mode.

***I add that before using shaders the game was going to 120 / 140FPS stable***

**Comment by naeqirelle2020** [comment]
@OkamiFox does this still occur in the latest preview?

**Comment by sp614x** [comment]
This looks like a CPU/GPU overheating and throttling frequency or some other OS/hardware problem.
It is normal for the FPS to be 5x lower with shaders, as they are much more demanding.

**Comment by sp614x** [comment]
Not related to OptiFine.
