### ISSUE TITLE
Custom colors not loading in 1.11 B1 ultra

### ISSUE THREAD

**Issue by robobo1221** [sp614x/optifine#370]
For some reason the custom colors in a resource pack are not working like they should. it worked in the latest 1.10.2 ultra optifine.

i have a GTX 750 2GB with a intel pentium core (i know it sucks)

**Comment by ShaunNoWay** [comment]
They work fine for me. I have the color file in `assets\minecraft\mcpatcher\color.properties` in my resource pack. Check to see the custom colors is on in video->quality settings.

**Comment by sixfootblue** [comment]
I found that my colormaps didn't work until I changed my resourcepack version from 2 to 3 in the pack.mcmeta. Assuming you haven't updated the file, try setting it to 3 and see if it works.

**Comment by sp614x** [comment]
Also fixed in preview B2.
