### ISSUE TITLE
Custom Colormaps appear to be TERRIBLY optimised

### ISSUE THREAD

**Issue by SkaliberWasTaken** [sp614x/optifine#3700]
I'm not sure if this is already common knowledge, or if it even comes under the category of a "bug" but i've recently created 5 custom colormaps for my resource pack, which are used across 12 blocks, and it's turned my game to complete mush.

This effect appears to be on every version of Optifine.

There were no other mods installed to produce this effect.

Again, i apologise if this is not a bug as such, but i did try asking in the discord group first, and was dismissed. I have since recorded a video showing a side-by-side comparison of chunk loading times when using and not using the colormaps, and I'm happy to link it if it's any help.

The video is quite simple however, and just shows Vanilla loading 16 chunks in approximately 3 seconds, whereas the resource pack never finishes loading the chunks in over 30 seconds.

**Comment by EternalMC** [comment]
A video would be nice

**Comment by sp614x** [comment]
Can you post a link to minimal resource pack that reproduces the problem?

**Comment by SkaliberWasTaken** [comment]
This was caused by a pre-release version of OptiFine in 1.15 and was probably erroneous, will report if it happens again in the future (:
