### ISSUE TITLE
[VSync] VSync not functioning in 1.15.2 G1 pre13

### ISSUE THREAD

**Issue by z500** [sp614x/optifine#3702]
# Description
When enabling VSync in video settings, the frames act as if they are capped at unlimited and the frames don’t match my refresh rate (60Hz) my frames are usually above this number (150-200). I have a VSync capable Nvidia graphics card. In previous stable versions of OptiFine, VSync worked perfectly.

## Steps to Reproduce
1. Go to video settings
2. Turn VSync on
3. Examine frame rate and see if it is matching your refresh rate, (mine was over my refresh rate)

## OptiFine Version
1.15.2 preview13

## Installation Method
Standalone installer

## Log Files/Crash Reports
Any relevant log files. Drag and drop text files here to upload to GitHub directly, OR upload the complete contents to Pastebin. https://pastebin.com/ no crash reports

You can get logs from `.minecraft/logs`, and crash reports from `.minecraft/crash-reports`. 
Locating your `.minecraft` folder will depend entirely on your OS. See this page for details: https://minecraft.gamepedia.com/.minecraft

**DO NOT directly copy and paste log contents here on GitHub.**

## F3 Debug Screenshot
Settings, Singleplayer F3, and Multiplayer F3:
**https://imgur.com/a/cA4srMa**

## Prior Testing
If you've installed standalone:
In vanilla 1.15.2, VSync is fully functional.

- Does this happen in OptiFine standalone?
Yes
- Does this happen in Vanilla without OptiFine?
No

## Additional Information
I hope this helps the OptiFine team!

**Comment by sp614x** [comment]
Not reproducible.
