### ISSUE TITLE
[Shaders] performance issues with shaders

### ISSUE THREAD

**Issue by notlucario** [sp614x/optifine#3703]
while running shaders performance will slowly drop down to 60 fps and below. Specs are i7 8700k, 2080 ti with 24gb of ram allocated to minecraft. Running shaders in 1.14.4 had no such performance issues, and would get upwards of 90 fps. F3+A fixes issue but only for a around a minute before performance degrades again.

## Steps to find issue
1. Installed optifine 
2. enabled shaders (Sildur's vibrant extreme 1.18)
3. Played for a few minutes

## OptiFine Version
OptiFine 1.15.2 HD U G1 pre13

## Installation Method
Standalone installer

## F3 Debug Screenshot
![2020-04-07_14 22 20](https://user-images.githubusercontent.com/63319796/78720877-5eb03a80-78db-11ea-8335-ae80bcf69c11.png)

**Comment by asbyth** [comment]
![image](https://user-images.githubusercontent.com/36578995/78721221-1aca2f00-78f5-11ea-9a8c-1b3114e14f3b.png)

**Comment by sp614x** [comment]
Should be fixed in pre22.
