### ISSUE TITLE
1.15.2 shader bug

### ISSUE THREAD

**Issue by P4nch0** [sp614x/optifine#3705]
## Description of Issue
Yes, I know pre13 is out, but this is the bug that made me check twitter and install the new version. 
Is a visual bug using shaders. While using the BSL shaders and then changing to the optifine internals it prevailed until turning them off and back on. All the lighting had a slight greenish/blueish hue giving a pretty eerie atmosphere to the game. And the blowstone behind my maps in frames was overlaying the maps as if they went completely transparent.

## Steps to Reproduce
I had no luck trying to reproduce it, it was kinda the perfect storm alignment. But I was in spectator mode, saw a spider jockey in the overworld and as i went into the "spider vision" everything changed. (the skeleton had enchanted gold armor) and actually the bsl shader show all the enchanted gear extremely pink bright, don't know if its on your side or theirs. 

## OptiFine Version
preview_OptiFine_1.15.2_HD_U_G1_pre12

## Installation Method
Standalone installer

**Comment by BBftw** [comment]
if it doesn't happen in pre13 then why are you submitting an issue?

**Comment by sp614x** [comment]
Should be working in latest preview.
