### ISSUE TITLE
[1.15.2] Selected block borders do not show with shaders

### ISSUE THREAD

**Issue by michaelpinnoo** [sp614x/optifine#3708]
**Problem**
When using any sildurs shaders (not tested any other ones), the black outline on blocks when looking at them does not render or is very faint and glitchy.

**Optifine version**
OptiFine 1.15.2 HD U G1 pre13

**Comment by TwoySenpai** [comment]
Same for me, SEUS shaders and Sildurs Vibrant

**Comment by meagle01** [comment]
same

**Comment by MrDangless** [comment]
I have the same issue, I have noticed that if you use a different version of the game it fixes, might also be the optifine version but they both change at the same time so I have know way of knowing until a new optifine version comes out.

**Comment by seeruk** [comment]
@MrDangless It's a bug in the 1.15.x versions of OptiFine.

Still experiencing this in pre15, but I've noticed it's only when facing roughly south east, I can see block outlines in all other directions.

**Comment by Aidowl** [comment]
Can confirm this is still an issue in 1.15.2 pre16
I've had this problem in Sildurs, BSL, Chocapic and SEUS

**Comment by Aidowl** [comment]
Still an issue in 1.15.2 HD U G1 pre17.

**Comment by Aidowl** [comment]
Still an issue in 1.15.2 HD U G1 pre18.

**Comment by sp614x** [comment]
Duplicate of #3600.
