### ISSUE TITLE
[BUG] Campfire Animation not moving while shaders are on

### ISSUE THREAD

**Issue by KingXigo** [sp614x/optifine#3709]
## Description of Issue
I've noticed while I'm playing with a shader pack (Chocapic), the campfires were not animated. Im not sure if its on OptiFine's end or Chocapic's, but its a bug nonetheless

## Steps to Reproduce
1. Use a shaderpack
2. Place the campfire

## OptiFine Version
OptiFine 1.15.2 HD G1_pre10

## Installation Method
Standalone Installer.

**Comment by rre36** [comment]
Afaik animated textures are not working when smart animations are enabled in the 1.15 preview version so I'd suggest checking if you have that setting enabled.

**Comment by WhiteWolfSV** [comment]
if you report bugs please do so in pre.13 (or the newest version) and don’t bug sp about bugs that are most likely fixed in newer versions

**Comment by sp614x** [comment]
Should be fixed in latest preview.
