### ISSUE TITLE
Optifine doesnt load my chunks correctly

### ISSUE THREAD

**Issue by Morasch** [sp614x/optifine#3711]
**Problem**
when i download any preview version of 1.15.2 version of optifine besides pre1, it loads only a few chunks and then it doesnt try to load anymore.
**Optifine version**
OptiFine 1.15.2 HD U G1 pre13
First photo is with shaders and second one is without and with fast render
![2020-04-08_12 47 04](https://user-images.githubusercontent.com/63363161/78811128-63d2bf80-7997-11ea-8457-bdd7e0745f3b.png)
![2020-04-08_12 50 09](https://user-images.githubusercontent.com/63363161/78811217-806ef780-7997-11ea-8ad2-ae1889ecb9b1.png)

**Comment by Cproductions** [comment]
Set your render distance to 32 chunks or under and it should fix your problem it did for me and every other setting but the grayed out ones should work fine for you

**Comment by InventorXtreme** [comment]
I am having this problem as well

**Comment by Morasch** [comment]
> Set your render distance to 32 chunks or under and it should fix your problem it did for me and every other setting but the grayed out ones should work fine for you

Thanks for the help! That worked great
