### ISSUE TITLE
Game crashes while attemtping to load mod

### ISSUE THREAD

**Issue by Minater247** [sp614x/optifine#3714]
I open the game, it gets through the initial small window, goes to fullscreen, loads about 60-75% of the way through and crashes with error:

> The game crashed whilst unexpected error
> Error: java.lang.NoSuchMethodError:
> net.minecraft.client.renderer.entity.EntityRendererManager..validateRendererExistence()V

The V at the end of the third line is intentional.

[From my limited knowledge, I'm guessing someone tried to pass it and accidentally added the V. ignore this if I'm just being the unexperienced thing I can be, just thought it might help in some way]

**Comment by asbyth** [comment]
V is a descriptor, for void, not an error.
Either way, this is from 1.15.2 not supporting Forge yet.

**Comment by sp614x** [comment]
Should be fixed in latest preview.
