### ISSUE TITLE
Shader rendering issue

### ISSUE THREAD

**Issue by StarMrGamer** [sp614x/optifine#3719]
<img width="960" alt="sad" src="https://user-images.githubusercontent.com/63405698/78896181-a7662000-7aa2-11ea-99ea-ef001d85775d.PNG">
  
So basically I don't know what is going on. My gpu is a Inten 620 UHD. I was just trying out Seus Renewed and this happened so

**Comment by KermitTheFrogerino** [comment]
You on Linux? My game also gives me those errors with Mesa 20.1.0 on my 5700XT.
Seus Renewed 1.01
![image](https://user-images.githubusercontent.com/35975961/78902628-504c5500-7a7a-11ea-8627-e31da0fb22b1.png)

BSL_v7.1.04.1
![image](https://user-images.githubusercontent.com/35975961/78902767-85f13e00-7a7a-11ea-8014-eb6456b325e5.png)

But works perfectly with Sildurs Vibrant Shaders v1.22 Extreme-VL (and all of the others from Sildur)
![image](https://user-images.githubusercontent.com/35975961/78902967-cea8f700-7a7a-11ea-8ca5-7bf5fdf5d422.png)

Works in Windows and in Linux with Nvidias proprietary drivers (a while ago but still Minecraft 1.14.4)

**Comment by StarMrGamer** [comment]
Nope on windows using a Amd M360 it's a low end gpu but same thing happens
to me.

**Comment by KermitTheFrogerino** [comment]
@StarMrGamer What driver are you running? Is the game running on your M360 or your IGPU(if you're running it on a laptop)?

**Comment by StarMrGamer** [comment]
Sorry I made a mistake. I was running a Intel 620 UHD on my other laptop. I
don't know the drivers but I know it was the latest version.

**Comment by StarMrGamer** [comment]
I am going to test the shader on my laptop with has an IGPU the version for
my driver is 20.4.1

**Comment by StarMrGamer** [comment]
[image: image.png]


Happened to my M360+ the sun is also tilted 45 degrees

**Comment by sp614x** [comment]
SEUS shaders don't support Intel integrated graphics.
Reference: https://shaders.fandom.com/wiki/Shader_Packs
