### ISSUE TITLE
No sound All 1.15.2 previews

### ISSUE THREAD

**Issue by josh1244** [sp614x/optifine#3720]
Normally 1.15.2 outputs sound fine but any configuration I use with optifine for this version, sound does not outputs at any time.

**Comment by Regnander** [comment]
Can you post a F3 screenshot? It would make it easier to identify the problem since it contains info about what settings and hardware you are using.

**Comment by josh1244** [comment]
![2020-04-09_18 23 03](https://user-images.githubusercontent.com/29608400/78945963-8f38d580-7a8f-11ea-8ffd-c242ca3f9224.png)

Alright, It would seem that it does output sound through headphones in the latest prerelease but not through the built in speakers.

**Comment by josh1244** [comment]
![2020-04-09_18 23 03](https://user-images.githubusercontent.com/29608400/78950266-33c11480-7a9c-11ea-9ca3-43281d06b870.png)
It would seem that headphones do work but the built in speakers do not work.

**Comment by sp614x** [comment]
The sound configuration is outside of OptiFine.
It is handled by native sound library.
