### ISSUE TITLE
[Crash] 1.15.2 Client startup crash

### ISSUE THREAD

**Issue by TheViperShow** [sp614x/optifine#3724]
## Description of Issue
I recently installed the latest optifine version and it's unable to start properly on Minecraft 1.15.2 with Forge version 31.1.0

## Steps to Reproduce
1: Start minecraft
2: It doesn't boot and it provides a crash-log file

## OptiFine Version
preview_OptiFine_1.15.2_HD_U_G1_pre13

## Installation Method
I used MultiMC install method, which I suppose adds the mod into the 'mods' folder

## Fabric/Forge Version
Forge version is 31.1.0

## Log Files/Crash Reports
Crash log -> https://pastebin.com/wgPJ0D0U
MultiMC console log -> https://pastebin.com/PVWZgMCq

## Prior Testing
If you've installed standalone:
- This does not happen in forge without Optifine, confirming that the issue is related to Optifine.
- I've also tried different JDKs and providers and none work (Amazon Corretto 11, Oracle 8, AdoptOpenJDK11)

If you've installed using Forge/Fabric:
- This happens with only OptiFine installed.

**Comment by HiItsDevin** [comment]
OptiFine doesn't support Forge yet
