### ISSUE TITLE
OptiFine 1.11 - Crashes

### ISSUE THREAD

**Issue by Azounstone** [sp614x/optifine#373]
Hello,

Firstly many thanks for this excellent product that makes Minecraft so much more enjoyable!

Since updating to 1.11 I am getting a lot of crashes whilst playing the game. Crash report below for your perusal. It is worth noting that if I do not use OptiFine then I do not get the crash, it only happens when using an OptiFine profile.

[OptiFine Crash.txt](https://github.com/sp614x/optifine/files/624706/OptiFine.Crash.txt)

This is just one example of this happening. In addition to this it is also rendering a lot of areas very slowly and even rendering some with parts being invisible as shown below:

![2016-12-01_13 13 52](https://cloud.githubusercontent.com/assets/9461336/20796033/27323032-b7cc-11e6-851c-565d59f1ae04.png)

When it is invisible like above it will normally crash the game a few moments later too.

Thanks for your attention to this and if you have any feedback or know when or how this will be fixed I would love to hear as currently it is really quite annoying.

Kind regards,

Andy

**Comment by Azounstone** [comment]
Since the last crash I am unable to log in to the game where I crashed when using OptiFine as it crashes upon loading in to the game. Crash report below:

[OptiFine Crash Constant.txt](https://github.com/sp614x/optifine/files/624725/OptiFine.Crash.Constant.txt)

I can however login provided OptiFine is not being used.

Regards,

**Comment by sp614x** [comment]
Does it happen in singleplayer or multiplayer or borh?
World download link, server IP?
Can you post the error log (tab "game output" in the vanilla launcher)?

**Comment by Azounstone** [comment]
Hello,

This is only happens in 1.11 it does not do it in 1.10.2

This is happening in both single player and multiplayer.

I copied the error logs from the tab you mentioned to both of my previous posts in the attached txt file.

If you need access to our server then please send me an email to admin@drobnovia.com with your minecraft name and I will add you to the whitelist and arrange a time to meet you on the server and take you to where it always happens.

**Comment by Azounstone** [comment]
Please note that it has also happened in other worlds as well.

**Comment by Azounstone** [comment]
The resource pack we are using is:

http://www.drobnovia.com/downloads/Drobnovia_KoS.zip

**Comment by sp614x** [comment]
It would be easier if it is reliably reproducible in single-player.
I am testing now the "Drobnovian Knights" map in singleplayer, maybe I can reproduce it.

**Comment by sp614x** [comment]
Flying around in creative mode on both downloadable maps, no crashes so far.
Teleporting to the crash coordinates 589,73,-391 also works (the above screenshot looks different).

**Comment by sp614x** [comment]
My IGN is sp614x if you want to whitelist me.

**Comment by sp614x** [comment]
Managed to crash once in "The Golden Chalice" at 980 91 -711, but cant repeat it.

**Comment by Azounstone** [comment]
Hi,

This is happening on our server where we are building our next adventure map. I will get you a download

**Comment by Azounstone** [comment]
I will remove the server info when you have seen it.

**Comment by Azounstone** [comment]
If you login and I am not there then teleport to 514 65 -441 and then go east and explore the buildings.

ALL of us working on the map can not use OptiFine here or we crash and once crashed each time we log back in we crash again before we can move away.

**Comment by sp614x** [comment]
Post the server info again, I will remove it.

**Comment by Azounstone** [comment]
drobnovia.playat.ch

**Comment by sp614x** [comment]
Nice, I crashed 3 times at this place, so quite reproducible.

**Comment by Azounstone** [comment]
Coming back?

I now have a save of the map if you want it:

http://www.drobnovia.com/downloads/KOS.zip

Any ideas?

**Comment by sp614x** [comment]
This is most probably a race condition between the chunk update threads and maybe the main thread. I was trying to pin down this bug for about a week and this is the first place where it is reliable to reproduce.

**Comment by sp614x** [comment]
The problem is triggered by the flower pots.

**Comment by Azounstone** [comment]
Hi,

How come flower pots do it where we were but not at other locations though?

**Comment by Azounstone** [comment]
Is this something you can fix?

**Comment by Azounstone** [comment]
This showed up in my crash report from the txt file in my 2nd post:

- Block model being tesselated --
Details:
	Block: minecraft:flower_pot[contents=fern,legacy_data=11]
	Block location: World: (589,73,-391), Chunk: (at 13,4,9 in 36,-25; contains blocks 576,0,-400 to 591,255,-385), Region: (1,-1; contains chunks 32,-32 to 63,-1, blocks 512,0,-512 to 1023,255,-1)
	Using AO: false
Stacktrace:
	at bra.a(BlockModelRenderer.java:74)
	at bra.a(BlockModelRenderer.java:54)

-- Block being tesselated --
Details:
	Block type: ID #140 (tile.flowerPot // ann)
	Block data value: 11 / 0xB / 0b1011
	Block location: World: (589,73,-391), Chunk: (at 13,4,9 in 36,-25; contains blocks 576,0,-400 to 591,255,-385), Region: (1,-1; contains chunks 32,-32 to 63,-1, blocks 512,0,-512 to 1023,255,-1)
Stacktrace:
	at bqy.a(SourceFile:65)

So it is referencing the flower pot too it would seem.

**Comment by sp614x** [comment]
Ninja updated version B2 with a bugfix.

**Comment by Azounstone** [comment]
FYI it says pre release on it when you run it.

**Comment by Azounstone** [comment]
AND.....

Thank you SO much for going out of your way to address this and fix it so quickly. It is very much appreciated!

Is it okay to use the ninja updated version even though it saus it is a pre release when running it?

**Comment by sp614x** [comment]
The problem was the BlockFlowerPot which was checking for a specific vanilla class and was behaving differently when OptiFine was installed. This was creating an endless update loop for the chunks containing flower pots AND it was causing multithreaded updates on the chunk which is not designed to be thread safe. This was leading to all sorts of sporadic multi-threaded crashes: NullPointerException, ConcurrentModificationException, and so on.

Updated B2 once again to report the correct version.

**Comment by Azounstone** [comment]
Strange how it only crashed it in certain locations.

Thanks again so much for sorting this and if you need a server to test things you are always welcome on ours where we build our maps if it helps at all. I will leave you whitelisted and op'd in case you need access.

Thanks again!!!!

Andy

**Comment by sp614x** [comment]
The multi-threaded crashes do not happen immediately, there is only a certain chance that the crash may happen. So it mostly works, but sometimes when the two threads reach each other in a very specific place it crashes. And if they reach each other at another place it crashes in a different way.

In summary, a very nasty bug, hard to reproduce and caused by a very obscure reason outside of OptiFine.

**Comment by Azounstone** [comment]
We would be lost without you!

Thanks!

Andy

**Comment by sp614x** [comment]
The world should also load much faster and some other crashes should also be fixed, all were having the same underlying issue. 

Nice bug report, being able to reproduce the bug was a big plus.
