### ISSUE TITLE
Underwater Lag spikes

### ISSUE THREAD

**Issue by zFerry98** [sp614x/optifine#3730]
Underwater when you place or break blocks (any type) lag spikes are generated. In the lag meter f3, each block removed or placed generates a red bar to the end of the screen.

## Steps to Reproduce
Install optifine 1.15.2 prev13 on fabric with optifabric beta8. (the fabric version is irrelevant because since the very first preview this problem was also present). Go underwater and break or place blocks with open f3 (show lag meter).

## OptiFine Version
1.15.2 Pre 13 also Pre 8 and 9

## Installation Method
Fabric with optifabric beta 8

## OptiFabric Version
Beta 8

## Other Installed Mods
Mods:
  [✔️] advancements-enlarger-1.0.0
  [✔️] appleskin-mc1.15-fabric-1.0.8
  [✔️] Autofish-0.8.5-fabric-mc1.15
  [✔️] borderless-mining-1.0.0
  [✔️] durabilityviewer-1.15.2-fabric0.4.23-1.7
  [✔️] dynamic-fps-1.1.1
  [✔️] easierchests-1.15-fabric0.4.23-1.4
  [✔️] fabric-api-0.5.1+build.294-1.15
  [✔️] fabricmod_VoxelMap-1.9.16_for_1.15.2
  [✔️] Hwyla-fabric-1.15.2-1.9.21-72
  [❌] immersive-portals-0.25(forMc1.15withFabric).jar (disabled)
  [✔️] LightOverlay-4.3
  [✔️] lithium-mc1.15.2-fabric-0.4.6-mod
  [📁] mamiyaotaru (folder)
  [✔️] MixinBootstrap-1.0.2
  [✔️] modmenu-1.10.2+build.32
  [✔️] notenoughcrashes-1.2.3+1.15.1
  [✔️] optifabric-1.0.0-beta8
  [✔️] orderly-1.2.1+build.4-1.15
  [✔️] phosphor-fabric-mc1.15.2-0.5.2+build.6
  [✔️] preview_OptiFine_1.15.2_HD_U_G1_pre13
  [✔️] rer-1.3.2
  [✔️] RoughlyEnoughItems-3.6.7
  [✔️] shulkerboxtooltip-1.4.5+1.15
  [✔️] suppress-unknown-item-2.0.0+mc1.15.2

## F3 Debug Screenshot

![ferry298 on SonoTornatoMERDE!! 2020-04-11 16-04-57_2](https://user-images.githubusercontent.com/17975351/79047580-d6ea6900-7c17-11ea-9654-b15873435439.gif)

## Additional Information
This only happens if optifine is active. If I remove optifine no lag spikes are generated underwater. Regardless of the other mods.
It happens both on the home PC (i5 4460 gtx1070ti 10gb ram 6gb dedicated to java) and on the laptop (i7 7700hq gtx1060m 16gb ram 10gb dedicated java).
I want to specify that I did some tests removing phosphor and lithium (two mods that optimizing one the engine of lights and the other in general minecraf). in spite of this, the problem is solved only by removing optifine and I repeat, it has been happening since the preview for 1.15 of optifine exists.

**Comment by XxKoltronxX** [comment]
Please check if Biome Blending is turned on, then try to switch off Biome Blending to see if it makes a difference.

**Comment by zFerry98** [comment]
> Please check if Biome Blending is turned on, then try to switch off Biome Blending to see if it makes a difference.

Biome Blending on (maxed):
![image](https://user-images.githubusercontent.com/17975351/79051446-99460a00-7c30-11ea-86aa-025956144016.png)

Biome Blending off: 
![image](https://user-images.githubusercontent.com/17975351/79051504-e4f8b380-7c30-11ea-9b39-737e48610b60.png)


Wow, as a temporary fix I'm happy.
Thanks for the quick support. Do I close or leave open?

**Comment by XxKoltronxX** [comment]
I think keep it open because I also have same issue when I place/break blocks near water. Biome Blending is not optimised near water.
