### ISSUE TITLE
Fix 1.14-1.15 chunk border lag spike

### ISSUE THREAD

**Issue by zPirroZ3007** [sp614x/optifine#3733]
I wonder if optifine developers can fix the bug reported here:
https://bugs.mojang.com/browse/MC-162253

Mojang seems to ignore it, so that would be a good improvement.

Thanks in advance.

**Comment by Sneakometer** [comment]
Agree. This is caused by light update. It's especially noticable on amplified worlds or in general worlds with tall buildings. Mojang doesn't care.

**Comment by basedAF** [comment]
Agree optifine should do this since mojang staff arent capable @sp614x 
This is patched by paper and can be seen here 
https://github.com/PaperMC/Paper/blob/3d43c5e50077ac7fa1e68cf7a7add0ac77768a61/patches/removed/1.17/0438-Workaround-for-Client-Lag-Spikes-MC-162253.patch
