### ISSUE TITLE
[ChunkLoading] Only loads chunks by toggling Smart Animatiins

### ISSUE THREAD

**Issue by DblRnbwDsh** [sp614x/optifine#3737]
Running Pre13 1.15.2
 Vanilla
 No shaders
 Having issue with rendering, no matter how long I wait for it to load, as soon as I leave the chunk I logged in on, all blocks are transparent. I can see all entities, I can tell whether or not I'm under water, and the meshes are all present. I will occasionally see a cave load in below me, as if I was in spectator mode, and this issue is present on servers as well.
 I can reload them by toggling Smart Animations either on or off, doesn't matter which one. Always reloads the chunk I'm in and solves the issue until I try to load a new chunk. I've toggled everything else, and looked all over Google, but there doesn't seem to be any other fix.

**Comment by Cproductions** [comment]
I found as long as your render distance is set to 32 or below it will start rendering chunks properly

**Comment by AndyPandy05** [comment]
See https://github.com/sp614x/optifine/issues/3752 I think these people have the same problem?

**Comment by sp614x** [comment]
Should be working in latest preview.
