### ISSUE TITLE
[1.11] Unable to change screenshot size when using antialiasing

### ISSUE THREAD

**Issue by Managarmr719** [sp614x/optifine#374]
I don't know if it's intended or if it's a bug but if it is a limitation of using antialiasing I think there should be a warning in the screenshot size tooltip like there is for fast render.

EDIT: I'm able to "use" both at the same time by changing the screenshot size first and then the antialiasing but the taken screenshot still has the default size and when trying to change it it goes to default.

Version: OptiFine_1.11_HD_U_B2

**Comment by sp614x** [comment]
Extended tooltip, added "not compatible with Antialiasing"
