### ISSUE TITLE
[Category] optimise (ver 1.15.2) keeps crashing minecraft when paired with forge (ver 1.15.2)

### ISSUE THREAD

**Issue by senseal** [sp614x/optifine#3742]
## Description of Issue
whenever I try to launch forge (1.15.2) it keeps crashing whenever I have optifine (ver 1.15.2 preview 13) in my mods folder

## Steps to Reproduce
1 install forge 1.15.2 
2 download the 1.15.2 ver of optifine 
3 put the optifine file in the "mods" folder
4 launch Minecraft in optifine

## OptiFine Version
1.15.2 HD U G1 pre13

## Installation Method
 dropped the JAR file into  "mods" folder

## Fabric/Forge Version
1.15.2-forge-31.1.44

## Other Installed Mods
- world edit (1.15.2)

## Log Files/Crash Reports
[crash-2020-04-14_14.33.19-client.txt](https://github.com/sp614x/optifine/files/4480757/crash-2020-04-14_14.33.19-client.txt)=

## F3 Debug Screenshot
![debug screenshot](https://user-images.githubusercontent.com/63717302/79329814-57f37a00-7f10-11ea-8b4a-844cce4dab9c.png)

**Comment by TropheusJ** [comment]
not compatible with forge yet. you can use optiforge as a temporary fix though

**Comment by laurentksh** [comment]
I also am having this issue.

**Comment by Deviouslrd** [comment]
Its a unfinished feature with optifine. Sp is currently working on adding compatibility, but it is not ready yet. And yes I did just repeat the above comment.

**Comment by sp614x** [comment]
Should be fixed in latest preview.

**Comment by senseal** [comment]
It is thanks
