### ISSUE TITLE
[Category] Game crashes when opened pre-written book and quill

### ISSUE THREAD

**Issue by Eden333** [sp614x/optifine#3743]
## Description of Issue
When I opened a Book and quill that someone had something written in it, the game kept crashing.

## Steps to Reproduce
Open the book, then i went on page 2 and then it crashed, was able to replicate everytime i tried, (5x)

## OptiFine Version
1.15.2 G1_pre13

## Installation Method
I installed it with the jar, no other mods.

## Log Files/Crash Reports
https://pastebin.com/6Be77DA1

## Prior Testing
It did not happen on Vanilla, only with optifine

**Comment by sp614x** [comment]
Looks like a vanilla bug.
OptiFine doesn't change the EditBookScreen class where it crashes.
