### ISSUE TITLE
[Shader] Chunks never unload when using a shader pack

### ISSUE THREAD

**Issue by dr0p** [sp614x/optifine#3744]
## Description of Issue and Steps to Reproduce
I am trying to use.. basically any shader packs and noticed that when a shader packs is just loaded the performance is good and it stays this way until I start exploring. After some fiddling with different shader packs and video options different combinations of packs and video options.. resolutions.. shadow quality.. render quality.. and whatever I can think of I noticed that the `C: xxxx` (chunk renderers) starts at a low value ~500 at pack load (or some video setting change) and starts climbing once I start exploring.. which is normal as more chunks get loaded and rendered. The problem is that it never decreases. If I go far away from my home base and go back to the base and than look at the direction where I was exploring the number of chunk renderers jumps to something verry high - over 5000 and If i do some more exploring it gets worst. I repeated the same experiment on the same world with no shaders enabled (the off value for shaders) and `C: ` value never goes above 2000 and quite rapidly decreases to around 1000 after several seconds of looking at the explored land. As a third experiment I repeated the above with shaders set to `Internal` and the result were even worst than when using some random shader pack - the number of chunk renderers rises and does not decrease and the performance is even worst than most of the shader packs I tried.

## OptiFine Version
1.15.2 HD_U_G1_pre13

## Installation Method
Installer

## Other Installed Mods
No mods, just shader packs

## F3 Debug Screenshot
Minecraft's built-in debug screen provides *a lot* of useful information, and should be included even if the issue is not something that can be captured in a still image.

To open this menu, simply press `F3` on your keyboard while in-game. Please ensure the text is easily readable. Depending on the size/resolution of your monitor, you may have to adjust your GUI scale for all text to be completely visible on-screen.

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine? - *nope* vanilla and shaders to `off` it seems to work properly

## Additional Information
After some additional testing I found out that looking straight at the ground for several seconds forces the chunk renderers count to drop a lot, BUT this does not fix the performance - it is still laggy as as hell. If I change any option that forces blocks to reload the performance skyrockets and the number of renderers to decrease a bit compared to after looking at the ground. And one last note - the render distance have no effect on the performance 20 or 48 chunks performance starts pretty much the same level and deteriorates.

**Comment by dr0p** [comment]
One last thing I forgot to mention - the tests are done in multiplayer and the server is NOT hosted on the client machine.

**Comment by sp614x** [comment]
Should be working in latest preview.
