### ISSUE TITLE
[BUG] Skin does not load properly

### ISSUE THREAD

**Issue by MegaNoam** [sp614x/optifine#3745]
## Description of Issue
`OptiFine_1.6.4_HD_C6` version, the skin does not load properly

## Steps to Reproduce
I turned Minecraft on by default and added the mod and found that it was not loading properly

## OptiFine Version
`OptiFine_1.6.4_HD_C6`

## Installation Method
drop the JAR file into your "mods" folder

## Additional Information **(Please read everything before responding)**
**I know this is a version that you probably don't support anymore**
I think I can solve the problem with using dedicated texture, I would love to learn more about this solution

![Untitled-21](https://user-images.githubusercontent.com/18356302/79356775-fd761000-7f47-11ea-9130-063e98b38395.png)

**Comment by asbyth** [comment]
this is probably from using a 1.8 skin setup, with it being 64x64 rather than 64x32 and 1.7 likely being the only version prior to 64x64 support to actually have thought that idea through for compatibility

**Comment by MegaNoam** [comment]
Do you know a way to convert it? @asbyth 
By the way, this is my skin: https://namemc.com/profile/MegaNoam

**Comment by Regnander** [comment]
> Do you know a way to convert it?

You only need to remove the bottom part of the skin. Here you go:

|![skin](https://user-images.githubusercontent.com/17113053/79637114-cfc5dc80-817c-11ea-87ef-7c640cbc3d28.png)|
|--|

**Comment by MegaNoam** [comment]
It still doesn't work unfortunately, I'm left with the same result @Regnander

**Comment by sp614x** [comment]
Version 1.6 is not supported anymore.

**Comment by MegaNoam** [comment]
> Version 1.6 is not supported anymore.

Pay attention to the next what they write in the post
![image](https://user-images.githubusercontent.com/18356302/83290110-c81f3c00-a1ee-11ea-83d2-72af9706e8c1.png)

**Comment by LARSS03** [comment]
hi, i have the same problem but in version 1.7.10, can anyone help me?

**Comment by ZekerZhayard** [comment]
@LARSS03 There already exists a mod can help you load skins with 64*64 size: https://www.curseforge.com/minecraft/mc-mods/skinport
