### ISSUE TITLE
Shaders not registering.

### ISSUE THREAD

**Issue by r1ckrck** [sp614x/optifine#3747]
## Description of Issue
I am playing on a Mac, and the shaders don't show up on the shaders menu, its just off and internal. I am trying to load 'Shidur's Shaders'. I have checked the name of the folder, the versions of everything.

## Steps to Reproduce
1.Just turn on the game and open shaders menu.

## OptiFine Version
Self-explanatory. 

## Installation Method
I installed optifine and also tried using fabric loader using optifabric.

## Fabric/Forge Version
fabric-loader-0.7.8+build.189-1.15.2 / also standalone

## OptiFabric Version
optifabric-1.0.0-beta8

## Other Installed Mods
I have tried various combinations. and just optifine as well.

**Comment by NitroCipher** [comment]
You can't just leave OptiFine version as `self explanatory`. We need this information in other to help you.

Additionally, what folder are you putting shaders in?

**Comment by r1ckrck** [comment]
> You can't just leave OptiFine version as `self explanatory`. We need this information in order to help you.
> 
> Additionally, what folder are you putting shaders in?


Sorry about  that.
The Version is: 1.15.2-OptiFine_HD_U_G1_pre13

Also the folder name is: 'shaderpacks'
which I got by clicking the in game option to open the folder.

**Comment by TropheusJ** [comment]
dont unzip the shaders

**Comment by r1ckrck** [comment]
Lol, thanks that did it. 

For other Mac users, when you download it automatically unzips the downloaded file and puts the zipped file in the trash.
