### ISSUE TITLE
Lock normal/specular maps to randomized textures

### ISSUE THREAD

**Issue by Blockstate** [sp614x/optifine#375]
Two things, the way to specify Biomes in property files is extremely tedious and takes to much time. If you could make it so instead of listing each biome name out you could have options like biome=all which will place the texture in all Biomes and then have the ability to omit Biomes by typing there names. Possibly like this biome=all-River This way if you have more than half the Biomes being affected by a texture you don't have to remember as many specific names and have to type them all.

Secondly, when using random textures and shaders it's impossible to lock a normal map or specular map to the texture is designed for. Right now it randomizes all textures, this leads to mismatched textures. I'm not sure if there is a way to lock normals and specular maps to certain textures being randomized. But it would be a very helpful thing. Here's an example of what's happening (I have 1 1_n 1_s 2 2_n and 2_s. With random textures 1 may end up with 2_n or 2_s when it should be locked to using 1_n and 1_s)

**Comment by sp614x** [comment]
Updated preview B3, added negative biome check "biomes=!Biome1 Biome2 ..." - all biomes except the given ones

    # All biomes except "Desert" and "Savanna"
    biomes=!Desert Savanna

**Comment by Opptitronica** [comment]
Great thanks! Now just need the normal and specular maps to be locked to there textures when using random textures. Thanks again

**Comment by sp614x** [comment]
Just tested random CTM textures with normal/specular maps.
The N and S texture are always matching the main texture.
