### ISSUE TITLE
[Query] Special request

### ISSUE THREAD

**Issue by HeberonYT** [sp614x/optifine#3758]
Hi @sp614x , sorry for writing here, but I couldn't find a private place.

We are carrying out a large project on a Minecraft 1.12.2 server with the top youtubers in Spain, but we have a performance problem when using shaders, everything points to the excessive consumption of VRAM, even with RTX 2080TI graphics there are fps drops and an average average of 30fps , which is not normal.
If you can help us privately, we will appreciate it, even the expenses we can cover, the important thing is to repair the performance.

Greetings.

**Comment by sp614x** [comment]
You can DM me on discord.
