### ISSUE TITLE
Item's don't appear in the inventory

### ISSUE THREAD

**Issue by Zettin** [sp614x/optifine#3759]
## Description of Issue
The items in my inventory don't properly appear whenever I have shaders enabled, I have removed texture packs and mods from the world's but it still doesn't fix it.

## Steps to Reproduce
1. Been like this since I installed it

## OptiFine Version
1.15.2

## Installation Method
The stand alone

The world in the picture has no nods installed

**DO NOT directly copy and paste log contents here on GitHub.**

## F3 Debug Screenshot

![IMG_20200418_124144578](https://user-images.githubusercontent.com/63922977/79644981-04806680-8172-11ea-9b2e-26b9381b4468.jpg)

## Prior Testing
No only with shaders enabled optifine

## Additional Information
![IMG_20200418_122427943](https://user-images.githubusercontent.com/63922977/79645032-54f7c400-8172-11ea-9df6-78e079b81e7c.jpg)

**Comment by sp614x** [comment]
Should be fixed in latest preview.
