### ISSUE TITLE
Replace/disable skeleton bow?

### ISSUE THREAD

**Issue by ShaunNoWay** [sp614x/optifine#376]
Is there a way to replace or disable the skeletons bow sprite with CEM? The documentation doesn't list any "bow" part for the skeleton. I thought I could do it by disabling the "right_arm" part, but apparently not.
![help2](https://cloud.githubusercontent.com/assets/14033754/20824983/f4fb720a-b82e-11e6-83c0-a0a0f4535574.jpg)

**Comment by sp614x** [comment]
The bow is not a part of the skeleton model, it is the currently handheld item. Skeletens can also hold a sword in hand.

Currently it is not possible to disable the handheld item model.

**Comment by ShaunNoWay** [comment]
Oh, okay. Thank you.
