### ISSUE TITLE
[Bug] Specular and Normal maps not working with shaders

### ISSUE THREAD

**Issue by Aclamendo** [sp614x/optifine#3761]
## Description of Issue
Upon loading a resource pack with specular maps and normal maps, the pack will unload and an error message will display "Resource Reload Failed."

In some cases—usually when the player is in game—it can result in a crash.

## Steps to Reproduce
1. Have a shader enabled (I used Sildurs enhanced default V1.10)
2. Ensure normal maps and specular maps are on in the shaders menu
3. Load a resource pack with normal maps and specular maps

## OptiFine Version
1.15.2-OptiFine_HD_U_G1_pre13

## Installation Method
Standalone installer

## Log Files/Crash Reports
Crash report made when following steps to reproduce when in a new world
https://pastebin.com/utHEGi2X

## Other Info
No issues to report when normal maps and specular maps are disabled or not present in the resource pack.

I have attached a resource pack that will reproduce the error when used.
[Specular-Normal-Test.zip](https://github.com/sp614x/optifine/files/4498313/Specular-Normal-Test.zip)

**Comment by naeqirelle2020** [comment]
Still occurs in latest preview (Pre-19)

**Comment by sp614x** [comment]
The N/S textures for `green_glazed_terracotta` are 64x, the `green_glazed_terracotta.png` is 16x.

**Comment by sp614x** [comment]
The normal/specular textures should have the same size as the original textures.
If not they are automatically rescaled to match the original size.

**Comment by sp614x** [comment]
Fixed in pre22.
