### ISSUE TITLE
[1.15.2] Optifine Crashes With Forge

### ISSUE THREAD

**Issue by Tammark** [sp614x/optifine#3762]
Game Crashes immediately when using optifine + forge, doesn't make it to main menu screen
-Occurs with or without other mods installed

Optifine Version: preview_OptiFine_1.15.2_HD_U_G1_pre13

Forge Version: forge-1.15.2-31.1.27
Crash Report:
[crash-2020-04-19_08.20.44-client.txt](https://github.com/sp614x/optifine/files/4498978/crash-2020-04-19_08.20.44-client.txt)

**Comment by SetantaLP** [comment]
According to [the changelog](https://optifine.net/changelog?f=preview_OptiFine_1.15.2_HD_U_G1_pre13.jar) this version is not yet compatible with forge.

**Comment by DreiPixel** [comment]
use this mod with optifine for now
https://www.curseforge.com/minecraft/mc-mods/optiforge

**Comment by sp614x** [comment]
Should be fixed in latest preview.
