### ISSUE TITLE
[Visual Glitch] shadows not displaying properly without smooth lighting

### ISSUE THREAD

**Issue by Michael18751** [sp614x/optifine#3764]
## Description of Issue
shadows are completely black on top of blocks

## Steps to Reproduce
Go to video settings and drag the smooth lighting slider to 0% and set smooth lighting to off. Then the shadows won't display correctly on top of blocks (completely black)

## OptiFine Version
1.15.2 pre13

Opifine clean installation (vanilla)

![image](https://user-images.githubusercontent.com/53535277/79699322-e6436500-825c-11ea-9884-35b0228b28f8.png)

Also affects shaders https://www.reddit.com/r/Optifine/comments/g3vs5b/anyone_know_how_to_fix_my_grass_its_the_only/

**Comment by sp614x** [comment]
Should be working in latest preview.
