### ISSUE TITLE
[Optifine Cape] Transferring capes

### ISSUE THREAD

**Issue by NuckerTheDev** [sp614x/optifine#3765]
## Description of Issue
I have been doing a lot of transferring capes but sometimes they dont go over. I've lost quite a few due to this.

## Steps to Reproduce
I transferred a cape to one account then transferred that cape to another and it didn't work. I then transferred another cape to another account and that didn't work.

## OptiFine Version
Latest version of 1.14 optifine
## Installation Method
First time I did it through the optifine client and second time I did it through Badlion.

## Fabric/Forge Version
**If OptiFine is installed as standalone, you can remove this section.**

## OptiFabric Version
**If OptiFine is installed as standalone, or you're using Forge, you can remove this section.**

## Additional Information
I am on a mac

**Comment by Siuolthepic** [comment]
I mean Badlion might be at fault here I dunno.
Can I just ask why have you, in your own words. "have been doing a lot of transferring capes"
Not meaning to be rude just curious. Its ok if you dont wanna answer.

**Comment by sp614x** [comment]
Badlion is not supported.
