### ISSUE TITLE
Lightning. No Emissives.

### ISSUE THREAD

**Issue by Fr3nzy91** [sp614x/optifine#3766]
## Description of Issue
There's no light coming from torches or lanterns when placed. works fine when being held.

## Steps to Reproduce
1: Run Minecraft with OptiFine 1.15.2 HD U G1 pre13.
2: place Torch/lantern on any eligible surface.
3: swich to night.

## OptiFine Version
1.15.2 HD U G1 pre13.

## Installation Method
Installed it by double clicking the .jar. then put the .jar in the''mods'' folder.

## Fabric/Forge Version
Forge-31.1.46

## Other Installed Mods
-OptiForge-MC1.15.2-0.1.8
-Mixin Bootstrap-1.0.2
-Xaeros_Minimap_20.7.1:Forge_1-15-2
-XaerosWorldMap_1.5.7:Forge:1.15.2
-CreativeCore-1-15-2
-ItemPhysic-Mod-Full-1.15.2
-Xray Mod 1-15.2

**If OptiFine is installed as standalone, remove this section.**

## Log File
[latest.log](https://github.com/sp614x/optifine/files/4505113/latest.log)

## F3 Debug Screenshot

![Minecraft F3 screenshot 20-4-2020](https://user-images.githubusercontent.com/64033526/79782454-693cec00-833f-11ea-8466-927e41009b1c.png)

## Prior Testing
If you've installed standalone:
No. lightning works fine in Vanilla.

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? yes.
   - Only OptiFine and Forge: yes.
   - Only OptiFine, OptiFabric, and Fabric
- Does this happen without any mods at all?
   - Only Forge/Fabric by itself. No.
- Does this happen in OptiFine standalone? yes.
- Does this happen in Vanilla without OptiFine? No.
- Have you tried using a binary search to find which mods cause this issue? No.

## Additional Information
None.

**Comment by Snubbsy** [comment]
I have this issue as well with the same optifine and shader combination.

**Comment by giorov** [comment]
You know, forge is not yet compatible with any preview build. Next one should have it. 
Emissiveness of placed objects is definitely a big issue though. Thanks for reporting that. Definitely going to wait till it's fixed before I start previewing.

**Comment by sp614x** [comment]
Should be fixed in latest preview.
