### ISSUE TITLE
Insane Frame Drope

### ISSUE THREAD

**Issue by Dak2001** [sp614x/optifine#3768]
so, i`ve optifine U F5 with Forge 28.2.0 and my game has frame dropes like 120 FPS to 1 FPS 

How can I fix this? is awefull play like this

## Installation Method
I droped the JAR file inside the mods folder
## Fabric/Forge Version
Forge: 28.2.0

## Other Installed Mods
BetterCaves-1.14.4-1.1.1
Cooking-for-Blockheads-Mod-1.14.4
Double-Doors-Mod-1.14.4
FastFurnace-1.14.4-2.2.4
Harvest-Mod-1.14.4
Hwyla-forge-1.10.5-B66_1.14.4
jei-1.14.4-6.0.0.13
journeymap-1.14.4-5.7.0b1
Ma-Essentials-Mod-1.14.4
OresAboveDiamonds+1.14.4+v3.3
Placebo-1.14.4-2.3.5
practicaltools-1.14.4-1.4
tombstone-4.3.3-1.14.4
ToolUpgrades-1.14-(v.3.0.0)
worldedit-forge-mc1.14.4-7.0.1
## Log File/Crash Reports
[2020-04-20-4.log](https://github.com/sp614x/optifine/files/4507266/2020-04-20-4.log)

## Prior Testing
No, if i`ve installed alone doesn`t do this
If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   - Only OptiFine and Forge
- Does this happen without any mods at all?
yes
- Does this happen in OptiFine standalone?
yes
- Does this happen in Vanilla without OptiFine?
no

**Comment by ftheriachab** [comment]
There seems to be a known issue with JourneyMap that causes this.  I recommend to disable JourneyMap until it's fixed.

**Comment by Dak2001** [comment]
It works thanks. Do you know if there is any minimap that work with optifine?
