### ISSUE TITLE
CEM and mobs variation

### ISSUE THREAD

**Issue by tomaxed** [sp614x/optifine#377]
Hey,
Do the variation for the mobs that have a similar modelwill be a thing? (ex: the skeleton ears of your example pack don't fit with the wither skeleton)
My problem is that I've made a villager head because I don't like the default one, but the every villagers have the same head, so I can't add more variations for them.

Thanks

**Comment by sp614x** [comment]
Custom models depending on the entity properties may be added in the future.

**Comment by ewanhowell5195** [comment]
random entity models has been added to optifine https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/cem_model.txt#L206
