### ISSUE TITLE
[Crash] Got a crash using fresh latest Minecraft 1.15.2 + latest Forge

### ISSUE THREAD

**Issue by vv7v7** [sp614x/optifine#3771]
## Description of Issue
Just tried to run the Minecraft with Forge and Optifine on board.

## Steps to Reproduce
1. Install MultiMC 5 (`0.6.11-1430 on win32`);
    Using MultiMC:
2. Install Forge using MultiMC;
3. Add Optifine mod (`preview_OptiFine_1.15.2_HD_U_G1_pre13.jar`);
4. Run Minecraft.

## OptiFine Version
preview_OptiFine_1.15.2_HD_U_G1_pre13.jar

## Installation Method
I've used the included standalone installer of MultiMC.
[](https://i.imgur.com/Qhm5ANo.png)
https://i.imgur.com/Qhm5ANo.png

## Fabric/Forge Version
Forge 31.1.47

## Log Files/Crash Reports
https://paste.ee/p/WXto5

## Additional Information
What might this be? How to fix that? Does that mean that Optifine or Forge do not support each other currently? Then when they will approximately?

Thank you very much :)

**Comment by asbyth** [comment]
i long for the day people read changelogs
they're not compatible

**Comment by vv7v7** [comment]
> i long for the day people read changelogs
> they're not compatible

I thought that only for `Minecraft versions 1.13-1.14.3`:
[](https://i.imgur.com/cjWCUSL.png)

**Comment by IainColledge** [comment]
Use the preview version of forge, but this works for the interim https://www.curseforge.com/minecraft/mc-mods/optiforge
