### ISSUE TITLE
CEM modeling gone wrong. Horse variant turns white when attacked.

### ISSUE THREAD

**Issue by specs1396** [sp614x/optifine#3772]
https://imgur.com/a/CGRk8IY

Hello! I have been experiencing issues while trying to get the amazing JEM / JPM files to work. Whenever I attack the custom horse model (horse renamed as "deer") it reverts to an all white texture. As you can see in the imgur link, the parts for both the deer and the horse are merged. 

P.S. Excuse the spacing between the bones, for I have not messed with the translation variables yet.

Any help would be so greatly appreciated, because I have been attempting to solve this issue for over a week.

**Comment by sp614x** [comment]
Which OptiFine version?

**Comment by specs1396** [comment]
1.14.4
I solved the solution for my server though, when I make the mob spawn with a mythicmob display name the mob is consistent!

P.S. I bought an optifine cape for myself and some friends, thank you for all you do :D

**Comment by specs1396** [comment]
Although, anytime I nametag a mob, or name the spawn egg the unique name, in this case "deer" the problem persists. I will be of any help to you, if you want to test or anything.

**Comment by KaiAF** [comment]
This seems to be fixed in a recent OF version. If it's still an issue, let me know please.
