### ISSUE TITLE
Unencrypted Request to optifine.net

### ISSUE THREAD

**Issue by Bixilon** [sp614x/optifine#3775]
My Minecraft (OptiFine 1.12.2 HD U F5) send an unencrypted request to https://optifine.net/version/1.12.2/HD_U.txt. Please use https

**Comment by Regnander** [comment]
(Kinda) related #1358

**Comment by sp614x** [comment]
By default Minecraft runs with java 1.8_051 which is quite old (2015) and which may have problems with validating SSL certificates now or in the future when some SSL ciphers or certificates are deprecated.
The "version.txt" doesn't leak any sensitive information, so it isn't high priority to be fixed.
