### ISSUE TITLE
[Connected Textures] Vertical separators on glass panes do not connect/disappear one block in from the edges.

### ISSUE THREAD

**Issue by depwl9992** [sp614x/optifine#3777]
## Description of Issue
When viewed from either the east or the south, connected glass panes of the same color display a visible vertical separator at their left or right edges. These edges appear to be defined as panes with either another block, air, or a different colored glass pane on the side edges. The lines also appear when the pane turns a corner.

I also noticed and disabled all resource packs and still observed the issue. Additionally, this happened on two instances over two machines, both in single-player and on an SMP server.

## Steps to Reproduce
Create a minimum 1H x 2W grid of glass panes of the same color horizontally. View from either the East (+X) or the South (+Z) and observe.

## OptiFine Version
1.15.2_HD_U_G1_pre13

## Installation Method
Loader mod in MultiMC 5 v0.6.11-1430 instance (tested both preview and unpacked *_MOD jars).

## Fabric/Forge Version
Fabric Loader 0.7.8+build.184

## OptiFabric Version
1.0.0-beta8

## Other Installed Mods
BoundingBoxOutlineReloaded 1.0.14-1.15.1

## Log Files/Crash Reports
[Here's one](https://pastebin.com/fXJJ1PkM)

## F3 Debug Screenshot
![East](https://user-images.githubusercontent.com/1482452/80143247-c2886380-8569-11ea-9c1c-eccfb9c2a83c.png)
![South](https://user-images.githubusercontent.com/1482452/80143272-c87e4480-8569-11ea-8b84-229e02d9d807.png)
![West](https://user-images.githubusercontent.com/1482452/80143282-cc11cb80-8569-11ea-8e15-d2b666c45cb2.png)
![North](https://user-images.githubusercontent.com/1482452/80143294-cfa55280-8569-11ea-8c2a-6429027f6261.png)

## Prior Testing
If you've installed using Forge/Fabric:
- Does this happen without other mods installed? Yes.
- Does this happen without any mods at all? Irrelevant, as this is an Optifine feature.
- Does this happen in OptiFine standalone? **NO!**
- Does this happen in Vanilla without OptiFine? Irrelevant (connected textures and all that..).

**Comment by stricq** [comment]
I do not have this issue when using OptiForge, only when using OptiFabric.  Using the same Resource Pack (Monsterly HD) with both.

**Comment by SpudworksGIT** [comment]
This seemes to be an optifabric issue, as it does not seem to be affected with optifabric beta7.

**Comment by sp614x** [comment]
Fabric is not supported.
