### ISSUE TITLE
Hat layer not visible

### ISSUE THREAD

**Issue by TrueReassembly** [sp614x/optifine#3779]
## Description of Issue
Sometimes when i come online with OF, i cant see the hat layer on my skin (or any other layers). Just the base layer

## Steps to Reproduce
I dont know how to do it, it just happens

## OptiFine Version
1.15.2 pre6

## Installation Method
Standard

**If OptiFine is installed as standalone, remove this section.**

## Log Files/Crash Reports
Any relevant log files. Drag and drop text files here to upload to GitHub directly, OR upload the complete contents to Pastebin. https://pastebin.com/

You can get logs from `.minecraft/logs`, and crash reports from `.minecraft/crash-reports`. 
Locating your `.minecraft` folder will depend entirely on your OS. See this page for details: https://minecraft.gamepedia.com/.minecraft

**DO NOT directly copy and paste log contents here on GitHub.**

## F3 Debug Screenshot
[Here](https://imgur.com/a/MfeBrRz)

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   - Only OptiFine and Forge
   - Only OptiFine, OptiFabric, and Fabric
- Does this happen without any mods at all?
   - Only Forge/Fabric by itself.
- Does this happen in OptiFine standalone?
- Does this happen in Vanilla without OptiFine?
- Have you tried using a binary search to find which mods cause this issue?
   - To find conflicting mods, split your mods into 2 groups (not including OptiFine/OptiFabric, obviously). Remove one group, and test in-game. Keep the group that has the problem, and repeat until no more mods can be removed without the issue disappearing.
   - Does the issue still happen with only the remaining mods installed?
      - Forge/Fabric and remaining mods, without OptiFine

## Additional Information
Here goes any final remarks and everything else that might not fit in the previous sections.

**Comment by BBftw** [comment]
why are you using pre6? and why are you submitting a bug report for it without trying the latest version?

**Comment by sp614x** [comment]
Do you have the glowing effect on your player?

**Comment by naeqirelle2020** [comment]
Tested, Can't Reproduce

**Comment by KaiAF** [comment]
Closing as there has been no response from the author.
