### ISSUE TITLE
[Bug] Wolf cem broken

### ISSUE THREAD

**Issue by RyanCR03** [sp614x/optifine#3787]
## Description of Issue
Please provide as much detail as possible.
Wolf cem parts are named incorrectly

## Steps to Reproduce
Make a wolf cem model
Spawn Wolf

## OptiFine Version
OptiFine 1.15.2 HD U G1 pre13

## Installation Method
Extracted and placed into mods with optifabric

## Fabric/Forge Version
0.7.8+build.186-1.15.2

## OptiFabric Version
1.0.0 beta7

## Other Installed Mods
XenchantFabric-1.0.6
authme_fabric-1.14_1.15-1.1.1
nomoreglowingpots-1.0.2+1.15
borderless-mining-1.0.2+1.15
PresenceFootsteps-r24+ 1.15.2
held-item-info-1.1.1
pistoncontrol-1.2.0
pling-1.1.0
FrameThrough-1.0.1+1.15.2
tweakeroo-fabric-1.15.2-0.10.0-dev.20200320.230739
chat-up-1.0.0
Mambience-1.0.0
fabric-api-0.5.1+build.294- 1.15
BlockMeter-1.15-fabric0.4.23-1.3
appleskin-mc1.15-fabric-1.0.8
Runoroma-Mod-Fabric-1.15
malilib-fabric-1.15.2-0.10.0-dev.20+arne.4
litematica-fabric-1.15.2-0.0.0-dev.20200302.233247
phosphor-mc20w06a-fabric-0.4.0
modmenu-1.10.1+build.30
MinecraftCapesFabric 1.15.2

If you've installed using Forge/Fabric:
   - Only OptiFine, OptiFabric, and Fabric
Yes
- Have you tried using a binary search to find which mods cause this issue?
   - To find conflicting mods, split your mods into 2 groups (not including OptiFine/OptiFabric, obviously). Remove one group, and test in-game. Keep the group that has the problem, and repeat until no more mods can be removed without the issue disappearing.
Yes

## Additional Information
Here goes any final remarks and everything else that might not fit in the previous sections.
mane->tail | tail->body | body->head | head->head

**Comment by NitroCipher** [comment]
Please clean up and this issue, removing irrelevant information, and changing the title to something recognizable and appropriate

**Comment by RyanCR03** [comment]
> Please clean up and this issue, removing irrelevant information, and changing the title to something recognizable and appropriate

I will try but I don't know how to change the title...

**Comment by Regnander** [comment]
> I will try but I don't know how to change the title...

There should be a white button next to the title that reads "Edit".

**Comment by sp614x** [comment]
Fixed, coming in pre19.
