### ISSUE TITLE
[Elytra] Rockets not stopping function

### ISSUE THREAD

**Issue by crazycga** [sp614x/optifine#3789]
## Description of Issue
When using a rocket with Elytra the animation for the rocket firing does not stop after the rocket should be finished.  Additionally, the elytra continues to act as though the rocket is still firing when staying in the same chunk.  It appears that crossing a chunk boundary changes this behavior and appropriately stops the rocket.  Also, (this is weird) it seems that vertical speed is unaffected, only horizontal while this rocket issue is happening.

## Steps to Reproduce
1. Use rocket with elytra and cross into visible, but different chunk than starting chunk.
2. Land, and look down; rocket still firing.
3. Jump and fly horizontally; observe speed.

## OptiFine Version
OptiFine 1.15.2 HD U G1 pre13

## Installation Method
Used native installer.

## Fabric/Forge Version
Standalone.

## OptiFabric Version
Standalone.

## Other Installed Mods
No other mods.

## Log Files/Crash Reports
None.

## F3 Debug Screenshot
None.

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine? - **No, changing to vanilla fixes issue.**

If you've installed using Forge/Fabric:
N/A

## Additional Information
N/A

**Comment by naeqirelle2020** [comment]
tested, can't reproduce
