### ISSUE TITLE
[BUG] Ender chest CEM does not work

### ISSUE THREAD

**Issue by Andrew6rant** [sp614x/optifine#3790]
## Description of Issue
In Optifine version 1.15.2 HD U G1 pre13, .jem models for the Ender Chest do not change the ender chest at all.

## Steps to Reproduce
I tried to use a CEM model (one that worked in previous versions) in Optifine 1.15.2 HD U G1 pre13

## OptiFine Version
1.15.2 HD U G1 pre13

## Installation Method
This problem persists in both the Jar download and in Mods folder of Fabric (with OptiFabric)

## Log Files/Crash Reports
No crash reports

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
No, Vanilla cannot modify the ender chest model

If you've installed using Forge/Fabric:
- Does this happen without other mods installed?
No, other mods cannot modify the ender chest model

   - Only OptiFine and Forge
Yes, this problem happens

   - Only OptiFine, OptiFabric, and Fabric
Yes, this problem happens

- Does this happen without any mods at all?
   - Only Forge/Fabric by itself.
No, Forge/Fabric cannot modify the ender chest model

- Does this happen in OptiFine standalone?
Yes, this problem happens

- Does this happen in Vanilla without OptiFine?
No, Vanilla cannot modify the ender chest model

- Have you tried using a binary search to find which mods cause this issue?
This is not a mod issue

**Comment by sp614x** [comment]
Fixed, coming in pre19.
In 1.15 the chest models are changed.
