### ISSUE TITLE
[Crash] by enchanted item shader

### ISSUE THREAD

**Issue by Roxy654** [sp614x/optifine#3791]
optifine crash when turning on shaders in game settings

## Steps to Reproduce
1.Putting a enchanted shield with banner in offhand
2.Apply shaders
## OptiFine Version: 
OptiFine_1.15.2_HD_U_G1_pre13
Build: 20200401-232147

## Installation Method
Ran the installer

## Log Files/Crash Reports
Pastebin. https://pastebin.com/ZRaMr5wD

## Prior Testing
If you've installed standalone:
- No caused by shaders 

## Additional Information
None

**Comment by sp614x** [comment]
Should be working in latest preview.
