### ISSUE TITLE
[Security...?] Require in-game confirmation before activating capes

### ISSUE THREAD

**Issue by JackDotJS** [sp614x/optifine#3793]
Currently, when making a new donation or simply moving a cape to another account, there is no verification process at all. That Minecraft account has that cape now, whether they like it or not. Unfortunately, this creates a MAJOR flaw in how capes are distributed. It is *hilariously* easy to simply donate and put ANY cape on a random username at will.

This results in things like this...
![image](https://user-images.githubusercontent.com/31686191/80301498-671cc800-8759-11ea-9df7-ebbd54c57f93.png)

We have an "OptiFine Cape" menu in many of the modern versions of OptiFine, located at `Options > Skin Customization > OptiFine Cape`. I think this menu should include an "Activate Cape" button, which **only shows when there is a cape waiting to be activated on that particular account.**

Here's a ~~crappy~~ mockup:
![image](https://user-images.githubusercontent.com/31686191/80301709-85cf8e80-875a-11ea-9f96-6a4dd9c66cab.png)

**Comment by realjackasterisk** [comment]
added the website label since, thinking about it now, it would make sense. besides updating OptiFine itself, this would definitely require some back-end changes on the web server to work.

**Comment by JackDotJS** [comment]
five months later id like to make a quick amendment to this suggestion.

to simplify implementation of this feature (and make it essentially backwards compatible with older versions of OptiFine), this "activation button" could be located on the cape edit page instead of in-game.

**Comment by ZenIsBestWolf** [comment]
This is done now.
