### ISSUE TITLE
[1.15.2] Breaking crops/blocks and placing blocks cause massive lag spikes/frame drops in certain areas.

### ISSUE THREAD

**Issue by Warkeb** [sp614x/optifine#3797]
## I started recently my new survival world and noticed that breaking/placing blocks/crops cause massive lag spikes in certain areas.

When I started my new survival world few days ago, I didn't notice any unplayable lag until I moved to a nice village. First I started noticing a lot of lag from breaking/planting sugarcane and other crops. but that was OK to me. Then when my tools got faster, I started noticing massive lag spikes from breaking and placing blocks. That on the other hand is not okay for me. So I'm now in a point where playing in my survival world is basically unplayable. 

This bug does not happen in every single area and this bug occurs much harder in some places than others as seen in pictures below. Vanilla 1.15.2 version without OF does not have this bug and it runs much smoothier when breaking blocks/crops.

I would recommend checking this village out.
Seed is 795360538 and lag place XYZ -783 64 -409

Sorry my English.

## Steps to Reproduce
1. New world
2. Find a village / just do step 3
3. Plant crops, break crops, place blocks and break blocks.

## OptiFine Version
OptiFine 1.15.2 HD U G1 pre13

## Installation Method
I installed OptiFine through official website with included standalone installer.

## Log Files/Crash Reports

Here are all the warns/some info that occurs when I launch my Minecraft with OptiFine and go to my world break some carrots and leave the game. These warns did not happen when I did the same thing in the same world without OptiFine except for this this "Ambiguity between arguments....".

Only warns
https://paste.ubuntu.com/p/dKHyRKD9Zx/

Warns + additional info
https://paste.ubuntu.com/p/F9WHV8Zg56/
https://paste.ubuntu.com/p/9V9gXsXd3F/
https://paste.ubuntu.com/p/Tm43zPsYXx/

## F3 Debug Screenshot

![Breaking carrots v2](https://user-images.githubusercontent.com/64354410/80307712-7d676a00-87d3-11ea-9abc-309cc4a39d06.png)

Heres much clearer picture me breaking blocks at the village.

![Breaking blocks](https://user-images.githubusercontent.com/64354410/80307735-9ec85600-87d3-11ea-84b6-9cb8ebe37347.png)

Heres picture where I'm breaking blocks 100 blocks away from the village.

![Breaking blocks not lag](https://user-images.githubusercontent.com/64354410/80307771-e18a2e00-87d3-11ea-9527-194ce0e900e9.png)

This picture is taken in the same place and in the same seed, but in different world. (not a copy)

![Breaking blocks in copy (lag)](https://user-images.githubusercontent.com/64354410/80307775-e6e77880-87d3-11ea-88f5-6f33b889cd3c.png)

This picture is also taken in same seed. I just teleported to a random location and started diggin.

![Breaking blocks in copy (not that much lag)](https://user-images.githubusercontent.com/64354410/80308046-6d508a00-87d5-11ea-8cd9-090d5252b74a.png)

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
No.

## Additional Information
I have nothing more to tell, but if additional info about this bug or if this bug has already been fixed... please let me know :)

**Comment by AbrasiveAlmond** [comment]
I get identical lag spikes but in different circumstances.
-In or above water
-Placing and breaking blocks
-Lag is a lot more intense at corner chunk boundaries.

**Comment by naeqirelle2020** [comment]
Tested, Still Occurs (Pre-18)

**Comment by JamieBrassel** [comment]
Still present in pre-19.

**Comment by sp614x** [comment]
Should be fixed in pre27.
