### ISSUE TITLE
[Bug] End outer islands not loading

### ISSUE THREAD

**Issue by matteocalisti** [sp614x/optifine#3800]
## Description of Issue
When I enter the end gateway portal to the outer islands I'm teleported to an empty world. There are no blocks, no mobs, I can't move or use items, attack, etc...
Restarting does not solve the issue.
Game works fine when not using OptiFine. Going back to OptiFine brings back the issue.

## Steps to Reproduce
1. Enter End Gateway to outer islands

## OptiFine Version
OptiFine 1.15.2 HD U G1 pre13

## Installation Method
JAR into the mods folder

## F3 Debug Screenshot
![2020-04-27_23 24 08](https://user-images.githubusercontent.com/64440579/80422491-85f89700-88de-11ea-875c-9babd177204a.png)

## Prior Testing
The issue is not present in vanilla.

**Comment by sp614x** [comment]
Should be working in latest preview.
