### ISSUE TITLE
1.14.4 forge and optifine they are not compatible

### ISSUE THREAD

**Issue by StenaLeonny** [sp614x/optifine#3801]
I have already entered several forums to ask for help because I thought the problem was with the modpack but even the creators of the modpacks told me that in 1.14.4 optifine do not support forge. can you fix it please?

**Comment by realjackasterisk** [comment]
1.14.4 OptiFine *is* compatible with Forge. Please do your research.
![image](https://user-images.githubusercontent.com/31686191/80442361-8df60e00-88c1-11ea-98fb-c329a4e871d8.png)

**Comment by StenaLeonny** [comment]
the problem is there. because optfine does not work in the latest versions of forge.

today forge is in the most recent version - "28.2.5" and in all modpacks with the version of forge 28.2.x optifine does not work. when you put the optifine in the mods folder the game before the initial screen the error game and the error message and this

"The game crashed whilst rendering overlay
Error: java.lang.NullPointerException: Rendering overlay "

**Comment by MeinKraft** [comment]
As a temporary fix download OptiForge and MixinBootstrap.

I tested Forge 28.2.18 with OptiForge-MC1.14.4-0.1.1, MixinBootstrap-1.0.3 and OptiFine_1.14.4_HD_U_F5 and everything worked perfect, inc Shaders
