### ISSUE TITLE
[1.15][CEM] CEM of skeleton skull has issues

### ISSUE THREAD

**Issue by GeForceLegend** [sp614x/optifine#3803]
## Description of Issue
1. CEM of skeleton skulls can not load textures from "optifine/cem". Texture being used is always "textures/entity/skeleton/skeleton.PNG".
2. "scale" value couldn't rescale model.
Here is the difference between 1.14 and 1.15
![2020-04-28_16 14 54](https://user-images.githubusercontent.com/41003546/80465983-7aed4780-896e-11ea-97b2-3720c5e686b7.png)
![2020-04-28_16 35 37](https://user-images.githubusercontent.com/41003546/80465881-5b561f00-896e-11ea-920d-49342e915afe.png)

## Steps to Reproduce
1. Load a resourcepack with skeleton skull CEM;
2. See the skull in GUI and place it.

## OptiFine Version
1.15.2 G1 Pre13

## Installation Method
Standalone

## Log Files/Crash Reports
[launcher_log.txt](https://github.com/sp614x/optifine/files/4544358/launcher_log.txt)

## F3 Debug Screenshot
![2020-04-28_16 35 37](https://user-images.githubusercontent.com/41003546/80465881-5b561f00-896e-11ea-920d-49342e915afe.png)

**Comment by sp614x** [comment]
Fixed in pre19.
