### ISSUE TITLE
Unrendered chunks are rendered weirdly

### ISSUE THREAD

**Issue by RonyCommitment** [sp614x/optifine#3805]
Basically unrendered chunks will render the last thing you saw can screen and stretch it out like how someone would stretch something out in photoshop
![Screen Shot 2020-04-29 at 1 34 51 PM](https://user-images.githubusercontent.com/56228603/80586857-46d15f80-8a1e-11ea-94f6-98299233270d.png)

**Comment by Regnander** [comment]
Can you upgrade to pre14 (assuming you are running 1.15.2) and take a F3 screenshot?

**Comment by sp614x** [comment]
Duplicate of #3673
