### ISSUE TITLE
CIT Naming Bug (Probably)

### ISSUE THREAD

**Issue by KingHector** [sp614x/optifine#3806]
So I wanted to make a custom recourcepack with optifine cit. I wanted written books that have a specific name to be different textures. This wouldn't work and the only way for this to work is if in the properties file i did this:

nbt.display.Name=ipattern:* R1                       (R1 is example)

Which means that i would have to rename the book in an anvil so in the end it will have R1.

This wouldn't work:

nbt.display.Name=item_name

## Steps to Reproduce
Make a cit for a book. 

## OptiFine Version
OptiFine 1.15.2 HD U G1 pre13

## Installation Method
I used forge to install. With the optiforge mod since this is a pre-release.

## OptiFabric Version
Forge 31.1.46

## Other Installed Mods
Optiforge (as said above)
WorldEdit
ClothConfig2
LightOverlay
MixinBootstrap
ReAuth

**Comment by sp614x** [comment]
Fixed, coming in pre20.
