### ISSUE TITLE
Damage Flash and Cracks in blocks disappear.

### ISSUE THREAD

**Issue by Stormtrooper065** [sp614x/optifine#3810]
Whenever I hit a mob normally, it would flash red... Now when I use a shader pack (Sildurs Shaders)
They don't, but it still does damage. Also, when I try to break a block the cracks do not appear when breaking...

**Comment by sp614x** [comment]
Is this with OptiFine for 1.15?

**Comment by Stormtrooper065** [comment]
Yes for the preview for 1.15.2

**Comment by Stormtrooper065** [comment]
Sorry that it took so long to reply. The only reason I would like to get this fixed is for competitive games on servers like hypixel bedwars cuz then I cant see the breaking progress of the blocks surrounding the bed...

**Comment by sp614x** [comment]
Duplicate of #3958 and #3600.
