### ISSUE TITLE
Crash upon startup 1.15.2 (If reported already then sorry for repeat.)

### ISSUE THREAD

**Issue by RepoDraghon** [sp614x/optifine#3811]
Crash upon startup 1.15.2

## OptiFine Version
OptiFine_1.15.2_HD_U_G1_pre13_MOD

## Installation Method
Download from Official site, tried DL and drop, tried installer by extract as I use the Twitch App to play

## Fabric/Forge Version
Forge only version 1.62

## Other Installed Mods
![Screenshot (45)](https://user-images.githubusercontent.com/8423696/80740130-7dfe4a00-8acc-11ea-8b56-a9dd5d60931e.png)
![Screenshot (46)](https://user-images.githubusercontent.com/8423696/80740133-7f2f7700-8acc-11ea-88c2-9180c2192d77.png)
![Screenshot (47)](https://user-images.githubusercontent.com/8423696/80740136-7fc80d80-8acc-11ea-8bda-37764ffb9d24.png)
![Screenshot (48)](https://user-images.githubusercontent.com/8423696/80740140-8060a400-8acc-11ea-811e-a41e5d0146e9.png)
![Screenshot (49)](https://user-images.githubusercontent.com/8423696/80740142-80f93a80-8acc-11ea-9b84-457c44bc3d42.png)
![Screenshot (50)](https://user-images.githubusercontent.com/8423696/80740144-822a6780-8acc-11ea-9305-5f712d217595.png)
![Screenshot (51)](https://user-images.githubusercontent.com/8423696/80740146-82c2fe00-8acc-11ea-8956-04e07a783cdf.png)

**If OptiFine is installed as standalone, remove this section.**

## Log Files/Crash Reports
[crash-2020-04-30_10.15.05-client.txt](https://github.com/sp614x/optifine/files/4560012/crash-2020-04-30_10.15.05-client.txt)
[latest.log](https://github.com/sp614x/optifine/files/4560014/latest.log)
[thutcore.log](https://github.com/sp614x/optifine/files/4560015/thutcore.log)
[thutessentials.log](https://github.com/sp614x/optifine/files/4560016/thutessentials.log)

**DO NOT directly copy and paste log contents here on GitHub.**

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine? Not Tested on standalone

If you've installed using Forge/Fabric: Forge only
- Does this happen without other mods installed? Yes
   - Only OptiFine and Forge
   
- Does this happen without any mods at all? Yes
   - Only Forge
- Does this happen in OptiFine standalone? Untested
- Does this happen in Vanilla without OptiFine? No
- Have you tried using a binary search to find which mods cause this issue? Yes

## Additional Information
There may be mods mot listed in the pictures but the ones not present are core mods needed for some of the other mods and Forge will let you know what mods those are. Just trying to help here.

**Comment by TropheusJ** [comment]
![#optifine-updates-⭐ - Discord 4_30_2020 2_12_11 PM_LI](https://user-images.githubusercontent.com/60247969/80744500-c594ce00-8aec-11ea-8aba-b2e7b49c3e5d.jpg)

**Comment by RepoDraghon** [comment]
Thanks, I know this but I figured this would help out figuring out how to make it compatible...

**Comment by TropheusJ** [comment]
you can use optiforge for now. its a mod that adds compatibility but can be glitchy

**Comment by sp614x** [comment]
Should be working in latest preview.
