### ISSUE TITLE
[Internal (LAN) Server] To make things faster, you build a cluster

### ISSUE THREAD

**Issue by NickDoom-IDKFA** [sp614x/optifine#3812]
I have another idea about skyboxes. It's a "skybox spectator mode" for the internal (A. K. A. LAN) server.
First, I set far rendering distance on my server PC and near rendering distance on my client PC.
Second, I load a world on my server PC and click the "Share to LAN" button. I select the Survival mode for other players and check the new "skybox spectator mode" checkbox (this is the option I'm asking for).
This option must switch the game mode (for the server) to Spectator, and also lower the priority of the rendering thread (totally sacrificing FPS for having smooth game physics). After first player (my client PC) connects to the server, the spectator camera begins following the client POV. It renders each frame for more than a second because server (physics) thread have much bigger priority and also the render distance is too far.
Frames rendered by the server-side spectator go by LAN and can be used by the first client as skyboxes. So the first client can have tiny rendering distance but still can see far areas (which update every few seconds or even slower. Smooth physics is more important!). The angle of area to update can also be adjusted by setting the FOV width on the server side.
That means, both PCs work as a cluster. The server one runs physics on a bigger area, and also renders a view from time to time. The client one is free from running physics and rendering distant areas, so it keeps great FPS.

**Comment by sp614x** [comment]
This is quite complicated and goes outside of the scope of OptiFine.
