### ISSUE TITLE
[1.12.2]Modded blocks in block.properties

### ISSUE THREAD

**Issue by Blue-Beaker** [sp614x/optifine#3816]
## Description of Issue
Shaderpack block.properties config works incorrectly for modded blocks

## Steps to Reproduce
Add some modded blocks into the block.properties of a shaderpack to make them waving, reload the shaderpack, it worked.
Then restart Minecraft, some other blocks from these mod instead of expected blocks waving.
Then reload shader by switching to another pack and switch back, all works as intended,
## OptiFine Version
Optifine_1.12.2_HD_U_F5.jar

## Installation Method
Dropped Optifine_1.12.2_HD_U_F5.jar directly into mods folder

## Fabric/Forge Version
Forge 14.23.5.2838

## Other Installed Mods
Mods:
  [✔️] [1.12.2]+VersionChecker-1.4.0
  [📁] 1.12 (folder)
  [✔️] AdditionalBanners-1.12.2-1.1.76
  [✔️] AdditionalEnchantedMiner-1.12.2-1.0.5-universal
  [✔️] Advanced+Solar+Panels-4.3.0
  [✔️] ae2stuff-0.7.0.4-mc1.12.2
  [✔️] AE2WTLib-1.12.2-1.0.34
  [✔️] AkashicTome-1.2-12
  [✔️] antighost-1.12-forge14.21.1.2387-1.1
  [✔️] appliedenergistics2-rv6-stable-7
  [✔️] AutoRegLib-1.3-32
  [✔️] base-1.12.2-3.13.0
  [✔️] Baubles-1.12-1.5.2
  [✔️] bdlib-1.14.3.10-mc1.12.2
  [✔️] BetterBuildersWands-1.12-0.11.1.245+69d0d70
  [✔️] BiomesOPlenty-1.12.2-7.0.1.2444-universal
  [✔️] blockdrops-1.12.2-1.4.0
  [✔️] BrandonsCore-1.12.2-2.4.12.205-universal
  [✔️] BringMeTheRings-0.4
  [✔️] buildcraft-all-7.99.24.1
  [✔️] Chameleon-1.12-4.1.3
  [✔️] ChickenChunks-1.12.2-2.4.1.73-universal
  [✔️] Chisel-MC1.12.2-0.2.1.35
  [✔️] chiselsandbits-14.33
  [✔️] Clumps-3.1.2
  [✔️] CodeChickenLib-1.12.2-3.2.3.357-universal
  [✔️] CoFHCore-1.12.2-4.6.3.27-universal
  [✔️] CoFHWorld-1.12.2-1.3.1.7-universal
  [✔️] ContentTweaker-1.12.2-4.9.1
  [✔️] CraftTweaker2-1.12-4.1.19
  [✔️] CreativeCore_v1.10.7_mc1.12.2
  [✔️] CTM-MC1.12.2-0.3.3.22
  [✔️] CustomSelectionBox-1.12.2-1.4.6
  [✔️] Cyclic-1.12.2-1.19.11
  [❌] demagnetize-1.12.2-1.1.0.jar (disabled)
  [✔️] demagnetize-1.12.2-1.1.1
  [📁] disabled (folder)
  [✔️] EnderCore-1.12.2-0.5.68
  [✔️] EnderIO-1.12.2-5.1.51
  [✔️] EnderIO-endergy-1.12.2-5.1.51
  [✔️] EnderStorage-1.12.2-2.4.5.136-universal
  [✔️] energyconverters_1.12.2-1.3.0.15
  [✔️] engineers_doors-1.12.2-0.8.0
  [✔️] ExtraBitManipulation-1.12.2-3.4.1
  [✔️] ExtraCells-1.12.2-2.6.2a
  [✔️] extrautils2-1.12-1.9.9
  [✔️] FancyBlockParticles-1.12.x-2.4.1
  [✔️] flatcoloredblocks-mc1.12-6.6
  [✔️] FloodLights-1.12.2-1.3.2-14
  [✔️] forestry_1.12.2-5.8.2.387
  [✔️] Forgelin-1.8.4
  [✔️] ForgeMultipart-1.12.2-2.6.2.83-universal
  [✔️] FpsReducer-mc1.12.2-1.14.1
  [✔️] FTBLib-5.3.1.60
  [✔️] FTBUtilities-5.3.0.56
  [✔️] GalacticraftCore-1.12.2-4.0.1.181
  [✔️] Galacticraft-Planets-1.12.2-4.0.1.181
  [✔️] gendustry-1.6.5.8-mc1.12.2
  [✔️] gendustryjei-1.0.2
  [✔️] generators-0.9.20.12-mc1.12.2
  [✔️] Guide-API-1.12-2.1.8-63
  [✔️] Headcrumbs-1.12.2-2.0.5.17
  [✔️] hiddenarmor-1.12.2-1.0
  [✔️] IC2CropBreeding+Plugin+V1.12-1.1 (1)
  [✔️] ic2-tweaker-0.2.0
  [✔️] ImmersiveEngineering-0.12-89
  [✔️] immersivepetroleum-1.12.2-1.1.9
  [✔️] immersivetech-1.12-1.3.10
  [✔️] industrialcraft-2-2.8.187-ex112
  [✔️] industrialforegoing-1.12.2-1.12.8-232
  [✔️] IndustrialWires-1.7-36
  [✔️] instantunify-1.12.2-1.1.2
  [✔️] IntegrationForegoing-1.12.2-1.9
  [✔️] InventoryTweaks-1.63
  [✔️] ItemPhysic_Full_1.4.32_mc1.12.2
  [✔️] itemscroller-1.12.2-0.12.0
  [✔️] ItemSearch_V1.0.1_MC1.12.2
  [✔️] jei_1.12.2-4.15.0.268
  [✔️] jeibees-0.9.0.5-mc1.12.2
  [✔️] jepb-1.12-1.2.1
  [✔️] journeymap-1.12.2-5.5.4
  [✔️] JustEnoughCalculation-1.12.2-3.0.0
  [✔️] JustEnoughEnergistics-1.12.2-1.0.6
  [✔️] JustEnoughPetroleum-0.1
  [✔️] JustEnoughResources-1.12.2-0.8.5.27
  [✔️] keywizard-1.12.2-1.5.4
  [✔️] LagGoggles-FORGE-1.12.2-4.1
  [✔️] librarianlib-1.12.2-4.20-release
  [✔️] LootBags-1.12.2-2.5.7
  [✔️] LootTableTweaker-1.12.2-1.1.14
  [✔️] Mantle-1.12-1.3.3.55
  [✔️] mcjtylib-1.12-3.5.3
  [📁] memory_repo (folder)
  [✔️] MicdoodleCore-1.12.2-4.0.1.181
  [✔️] MineralTracker-0.5.1
  [✔️] MineTweakerRecipeMaker-1.12.2-1.2.2.30
  [✔️] modtweaker-4.0.18
  [✔️] Morph-o-Tool-1.2-21
  [✔️] MrTJPCore-1.12.2-2.1.4.38-universal
  [✔️] MTLib-3.0.6
  [❌] music_player-1.12.2-2.0.0.9.jar (disabled)
  [✔️] music_player-1.12.2-2.0.8.71
  [✔️] NaturesCompass-1.12.2-1.5.1
  [✔️] NBTEdit-0.7
  [✔️] NoMoreRecipeConflict-0.13(1.12.2)
  [✔️] OfflineSkins-1.12.2-v6
  [❌] OpenComputers-MC1.12.2-1.7.4.153.jar (disabled)
  [✔️] OpenComputers-MC1.12.2-1.7.5.192
  [✔️] OpenEye-1.12.2-0.8
  [❌] OptiFine_1.12.2_HD_U_E3.jar (disabled)
  [✔️] OptiFine_1.12.2_HD_U_F5
  [✔️] p455w0rdslib-1.12.2-2.3.161
  [✔️] Placebo-1.12.2-1.4.1
  [✔️] PotionFingers-r1.0-2
  [✔️] ProjectIntelligence-1.12.2-1.0.5.21-universal
  [✔️] ProjectRed-1.12.2-4.9.1.92-mechanical
  [✔️] ProjectRed-1.12.2-4.9.2.110-Base
  [✔️] ProjectRed-1.12.2-4.9.2.110-compat
  [✔️] ProjectRed-1.12.2-4.9.2.110-fabrication
  [✔️] ProjectRed-1.12.2-4.9.2.110-integration
  [✔️] ProjectRed-1.12.2-4.9.2.110-lighting
  [✔️] ProjectRed-1.12.2-4.9.2.110-world
  [✔️] Psi-r1.1-77
  [✔️] Quark-r1.5-159
  [✔️] randompatches-1.12.2-1.15.0.2
  [✔️] randomtweaks-1.12.2-2.7.1.0
  [✔️] RedstoneArsenal-1.12.2-2.6.3.18-universal
  [✔️] RedstoneFlux-1.12-2.1.0.6-universal
  [✔️] redstoneigniter-0.1b
  [✔️] rftools-1.12-7.71
  [✔️] rftoolsctrl-1.12-2.0.2
  [✔️] rftoolsdim-1.12-5.71
  [✔️] rftoolspower-1.12-1.2.0
  [✔️] rpsideas-2.4.2
  [✔️] simpleworldtimer-1.12.2-1.1.0
  [✔️] SimplyJetpacks2-1.12.2-2.2.7.45
  [✔️] spatialservermod-1.3
  [✔️] stacksize-1.12.2-1.0
  [✔️] StorageDrawers-1.12.2-5.3.8
  [✔️] TConstruct-1.12.2-2.12.0.135
  [✔️] tesla-core-lib-1.12.2-1.0.15
  [✔️] theoneprobe-1.12-1.4.28
  [✔️] ThermalCultivation-1.12.2-0.3.3.12-universal
  [✔️] ThermalDynamics-1.12.2-2.5.5.21-universal
  [✔️] ThermalExpansion-1.12.2-5.5.4.43-universal
  [✔️] ThermalFoundation-1.12.2-2.6.3.27-universal
  [✔️] ThermalInnovation-1.12.2-0.3.3.12-universal
  [✔️] tinkersjei-1.0
  [✔️] tmel-1.12.2-1.3.2.2
  [✔️] Toast+Control-1.12.2-1.7.0
  [✔️] topaddons-1.12.2-1.12.0
  [✔️] Treecapitator-1.12-at_0.9a
  [❌] u_team_core-1.12.2-2.2.4.107.jar (disabled)
  [✔️] u_team_core-1.12.2-2.2.5.147
  [✔️] UniDict-1.12.2-2.9.3
  [✔️] VanillaFix-1.0.9-97
  [✔️] WanionLib-1.12.2-2.4
  [✔️] WHAT-0.2
  [✔️] WirelessCraftingTerminal-1.12.2-3.12.97
  [✔️] WirelessFluidTerminal-1.12.2-1.0.4
  [✔️] WirelessInterfaceTerminal-1.12.2-1.0.2
  [✔️] WirelessPatternTerminal-1.12.2-1.0.3
  [✔️] wirelessutils-1.12.2-1.10.136-universal
  [✔️] woot-1.12.2-1.4.10
  [✔️] worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist
  [✔️] worldprimer-1.12.2-0.6.0-dev.20200122.211517
  [✔️] yoyos_1.12.2-1.3.3.25

**If OptiFine is installed as standalone, remove this section.**

## Log Files/Crash Reports
Any relevant log files. Drag and drop text files here to upload to GitHub directly, OR upload the complete contents to Pastebin. https://pastebin.com/
[latest.log](https://github.com/sp614x/optifine/files/4567096/latest.log)

You can get logs from `.minecraft/logs`, and crash reports from `.minecraft/crash-reports`. 
Locating your `.minecraft` folder will depend entirely on your OS. See this page for details: https://minecraft.gamepedia.com/.minecraft

**DO NOT directly copy and paste log contents here on GitHub.**

## F3 Debug Screenshot
Minecraft's built-in debug screen provides *a lot* of useful information, and should be included even if the issue is not something that can be captured in a still image.
![2020-05-02_12 43 12_2](https://user-images.githubusercontent.com/17115547/80855289-96a86480-8c72-11ea-8714-a76ab09f1da4.png)

To open this menu, simply press `F3` on your keyboard while in-game. Please ensure the text is easily readable. Depending on the size/resolution of your monitor, you may have to adjust your GUI scale for all text to be completely visible on-screen.

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
Shaders unavaliable without optifine.
If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   - Only OptiFine and Forge
No blocks from other mods avaliable to reproduce issue.
- Does this happen without any mods at all?
   - Only Forge/Fabric by itself.
No shaders avaliable, and no modded blocks avaliable.
- Does this happen in OptiFine standalone?
No blocks from other mods avaliable to reproduce issue.
- Does this happen in Vanilla without OptiFine?
No shaders avaliable, and no modded blocks avaliable.
- Have you tried using a binary search to find which mods cause this issue?
   - To find conflicting mods, split your mods into 2 groups (not including OptiFine/OptiFabric, obviously). Remove one group, and test in-game. Keep the group that has the problem, and repeat until no more mods can be removed without the issue disappearing.
No.

## Additional Information
Here goes any final remarks and everything else that might not fit in the previous sections.
here's my mofidied block.properties(renamed to .txt to upload)
[block.properties.txt](https://github.com/sp614x/optifine/files/4567097/block.properties.txt)
Shaderpack is Sildurs Vibrant Shaders v1.22 High.zip. I replaced all block.properties file with the block.properties file.
Launcher: MultiMC 5 0.6.7.1375.

**Comment by Blue-Beaker** [comment]
Maybe it's a problem of the initial loading order. load shaders after forge loading completed may solve the problem.

**Comment by Phoenixdotexe** [comment]
any fix for this?

**Comment by sp614x** [comment]
Fixed, coming in next preview.
