### ISSUE TITLE
Chunk Borders not showing

### ISSUE THREAD

**Issue by HighExplosiv** [sp614x/optifine#3818]
When using shaders in the newest optifine preview version the chunk boundaries (f3+G) are not being displayed correctly. 
The chunk boundaries are only being shown when looking in a specific direction or looking at a specific area

## Steps to reproduce
1. install a shader
2. use f3+G to show chunk boundaries
3. move your crosshair 360 degrees around you should see a spot where the chunk boundaries flicker into existence
4. if 3. doesn't work try stepping a bit closer to the edge of the chunk

## OptiFine Version
newest preview release

## Installation Method
integrated/standalone installer

## Other Installed Mods
No other mods present

## Log Files/Crash Reports
The game doesn't crash

## Prior Testing
This bug does not occur in vanilla minecraft
Furthermore it doesn't occur when using optifine normaly the bug only shows when using shaders

## Additional Information
Shaders used to test:
Kuda
Continuum
BSL

**Comment by naeqirelle2020** [comment]
Still occurs (Pre-18)

**Comment by abouteiller** [comment]
Still occurs (pre-19)
* Silgur Vanilla
* Seus

'Internal' shader works as expected. 

This also affects the rendering of accurate placement block overlays in 'Tweakeroo' and other addons that draw shapes, for example to represent spawn boundaries and spheres (like Grid, miniHUD).

**Comment by sp614x** [comment]
Fixed in pre23.
