### ISSUE TITLE
[Crash] pre14 Rendering entity in world crash

### ISSUE THREAD

**Issue by Brottweiler** [sp614x/optifine#3820]
## Description of Issue
Opened my world, game crashes after looking a certain direction.

## Steps to Reproduce
1. What do you do... 
2. ...to find this bug?

## OptiFine Version
OptiFine 1.15.2 HD U G1 pre14

## Installation Method
Extract MOD and add it to minecraft.jar via MultiMC.

## Log Files/Crash Reports
https://gist.github.com/84bad4696e972bf69e4e01974e8512a5

## F3 Debug Screenshot
![2020-05-02_23 59 12](https://user-images.githubusercontent.com/1613137/80893253-02211f00-8cd1-11ea-869c-db299f6b4a8b.png)

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?

No. Also does not happen in pre13.

**Comment by redl0l** [comment]
Getting the exact same issue. pre13 works fine but this just crashes.

**Comment by espen96** [comment]
Getting the same error.

**Comment by DarkSamus9000** [comment]
Minecraft 1.15.2, OptiFine pre-14. 
I have custom armor in my resource pack that uses CIT to give diamond armor a special appearance when specially named. The special diamond armor renders correctly as an item, but when I equip the special armor the game immediately crashes.

https://pastebin.com/g2uEsA9V

Custom armor rendering worked with OptiFine 1.14.4-HD-U-F3. In 1.15.2-pre13, the armor rendered with the default texture. In 1.15.2-pre14, trying to render the custom armor crashes the game.

**Comment by Brottweiler** [comment]
Fixed in the latest hotfix.
