### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by WyntreBlossom** [sp614x/optifine#3822]
## Description of Issue
Im not entirely sure what the issue was, but when i updated the 1.14 preview, and logged into the server I staff on, using the texture pack I made (which works fine with 1.13. it would crash my game every single time i went to the server spawn. 

## Steps to Reproduce
You would have to join the server, download my personal texture pack, use it, and come to the server spawn. 

## OptiFine Version
1.15 preview 14

## Installation Method
Java through discord/official site for windows.

## Log Files/Crash Reports
https://pastebin.com/5D8TTWuq - crash report

## Prior Testing
Does not happen without optifine. Works fine with optifine 1.15 preview 13 but not preview 14

**Comment by sp614x** [comment]
Is it still happening in latest preview?

**Comment by WyntreBlossom** [comment]
No it is not
