### ISSUE TITLE
Crash when loading world with Xaero's World Map

### ISSUE THREAD

**Issue by ImpSpy2** [sp614x/optifine#3823]
## Description of Issue
The game crashes to the launcher when after loading into a world with Xaero's world map.

## Steps to Reproduce
1. Load Minecraft with Optifine Pre 14 and Xaero's world map
2. Load a world

## OptiFine Version
preview_OptiFine_1.15.2_HD_U_G1_pre14

## Installation Method
Dropped the JAR file into "mods" folder

## Fabric/Forge Version
Forge - 1.15.2 - 31.1.63

## Other Installed Mods
XaerosWorldMap_1.5.7_Forge_1.15.2
preview_OptiFine_1.15.2_HD_U_G1_pre14

## Log Files/Crash Reports
https://pastebin.com/TnnQMCez

## Additional Information
Optifine has worked previously with Xaeros world map using Optiforge.

**Comment by AnarchoLemons** [comment]
Crash also occurs when using the most recent version of Xaeros MiniMap. All other factors are the same.

**Comment by ugiskremens** [comment]
Same issue here. Works fine without Optifine

**Comment by Fastfingered** [comment]
Same issue here, also with the minimap mod, Seems to be related to TextureAtlasSprite

`java.lang.NoSuchMethodError: net.minecraft.client.renderer.model.BakedQuad.func_187508_a()Lnet/minecraft/client/renderer/texture/TextureAtlasSprite;`

**Comment by ImpSpy2** [comment]
Fixed in Pre 15
