### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by floShio** [sp614x/optifine#3824]
## Description of Issue
Game crashes upon launch

## Steps to Reproduce
1. Launch game

## OptiFine Version
Self-explanatory. 

## Installation Method
Standalone installer

## Log Files/Crash Reports
https://pastebin.com/1f3hnL1R

## F3 Debug Screenshot
Can't do that, as it won't let me launch it

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
- No

**Comment by HiItsDevin** [comment]
> Self-explanatory.

Please provide the version of OptiFine and the Game version you're using.

**Comment by sp614x** [comment]
Is this still happening in latest preview?

**Comment by sp614x** [comment]
Fixed in pre20.
