### ISSUE TITLE
Rendering a Entity (Stray)

### ISSUE THREAD

**Issue by NeftalyRayas** [sp614x/optifine#3825]
## Description of Issue
Please provide as much detail as possible.

**- i enter a server an i  have a stray as a pet, and the game insta crash, the crash info says its because it cant render the stray**

## Steps to Reproduce
1. What do you do... 
2. ...to find this bug?

## OptiFine Version
Self-explanatory. 
 
- **preview_OptiFine_1.15.2_HD_U_G1_pre14**

## Installation Method
How did you install OptiFine? Did you use the included standalone installer, or did you drop the JAR file into your "mods" folder?

-**doble click in the archive using java**.

## Log Files/Crash Reports
Any relevant log files. Drag and drop text files here to upload to GitHub directly, OR upload the complete contents to Pastebin. https://pastebin.com/

https://pastebin.com/srBKpgZX

**Comment by sp614x** [comment]
Can you post the full error log in pastebin?

**Comment by KaiAF** [comment]
If this is still an issue please create a new ticket
