### ISSUE TITLE
[1.15.2] Broken Iron Golems CEM texture

### ISSUE THREAD

**Issue by Aideck** [sp614x/optifine#3826]
## Cracking Iron Golems
In 1.15, by damaging iron golems, they change their texture, could you add something so that damaging an iron golem with a custom CIT skin can also break it?

![image](https://user-images.githubusercontent.com/64392432/80894092-ce7ccf80-8ca5-11ea-92d4-edbdae77c805.png)
That's what I mean

**Comment by ewanhowell5195** [comment]
these are seperate textures. just use random entities on them
