### ISSUE TITLE
Visual bug when using shaders **old graphics card**

### ISSUE THREAD

**Issue by miceol1** [sp614x/optifine#3829]
## Description of Issue
I'm using Badlion Client's 1.15.2 version with Optifine enabled. I ran Chocapic's Toaster V7.1.1 shaders in a Skyblock world and there was a bunch of stuttering and frames lingering. I was on a LAN world.

## Steps to Reproduce
1. Run Badlion
2. Turn on shaders
3. Look around
4. Wamo bamo, there ya go.

## OptiFine Version
OptiFine 1.15.2 HD U G1 pre14

## Installation Method
Badlion Client, probably using the installer.

## Fabric/Forge Version
Badlion Client v2.13.3

## Other Installed Mods
**ALL ARE BUILT IN BADLION MODS**
Minimap
Coordinates
Ping
Clock
FPS
ToggleSprint
ArmorStatus
AutoText
BossBar
Chat
ClearWater
EnchantGlint
HitColor
Particles
Perspective
PotionStatus
Scoreboard
Zoom

## F3 Debug Screenshot
![2020-05-02_20 13 29](https://user-images.githubusercontent.com/64716603/80896988-70ee8000-8cb1-11ea-842a-e3774821275a.png)

## Prior Testing
Same thing when using the launcher with Optifine.

## Additional Information
I have an old graphics card, Nvidia GeForce GT 630. Just thought I should mention that. I also use Badlion Client if that wasn't obvious enough.

**Comment by asbyth** [comment]
maybe dont use something that isnt officially supported?

**Comment by sp614x** [comment]
Badlion is not supported.
