### ISSUE TITLE
CEM bug and enhancement

### ISSUE THREAD

**Issue by Ryugo0** [sp614x/optifine#383]
hey,
i have an issue with CEM and a request of enhancement:
bug -> The CEM for some mob does not work in 1.11, for example the enderdragon can be replaced in 1.10 but not in 1.11 (may be because of the change from EnderDragon to ender_dragon)

enhancement -> When I create a .jpm with cubik studio, some parts are not of the right color because of  "UV mapping rotation", it would be fine if optifine would support it

comment -> The tail of the wolf can be replaced but there is no part "tail" in the documentation (cem_model.txt)

thank you for your awesome mod

**Comment by sp614x** [comment]
The ender dragon and enderman are fixed in preview B3.
Updated documentation for wolf, added tail and mane.
What is the "UV mapping rotation"?

**Comment by Ryugo0** [comment]
Thanks for the fix and i'm not a pro in 3D or with cubik studio so i made some images to explain the "UV mapping rotation" [posted on imgur](http://imgur.com/a/DREen)

**Comment by sp614x** [comment]
The UV mapping rotation should be corrected by Cubik Studio when exporting to JPM.
