### ISSUE TITLE
Items in inventory are darker than they should be.

### ISSUE THREAD

**Issue by truekaerf** [sp614x/optifine#3830]
## Description of Issue
Many items are darker than they should be.  About half of the items are dark, the rest are fine.  Look at golden carrots, torches etc in screenshot.  They render correctly when held in hand, as also visible in screenshot.

## Steps to Reproduce
Open any inventory or look at hot-bar.

## OptiFine Version
1.15.2 HD U G1 pre14

## Installation Method
Copied jar file into mods folder.

## Fabric/Forge Version
Forge 31.1.63

## Other Installed Mods
None.

## F3 Debug Screenshot
![2020-05-02_22 44 32](https://user-images.githubusercontent.com/38256419/80897517-853d7780-8cc7-11ea-8947-f3f6ea451425.png)

## Prior Testing
Issue did not exist with Optifine pre13 + OptiForge yesterday.
Removed all other mods, made sure no shaders were enabled, made sure no resource packs were enabled.

**Comment by imodre** [comment]
Also got exactly the same problem. It disappears when enabling any shader (even internal one)

**Comment by BeastyGit** [comment]
Same issue here using OptiFine pre4 & Forge 31.1.0

**Comment by MightyFilipns** [comment]
same issue

**Comment by ocram9** [comment]
This issue also occurs in OptiFine 1.15.2 HD U G1 pre15.

**Comment by lesterlo** [comment]
I have this problem too, most of the thing in the inventory is dark.

I am using OptiFine 1.15.2 HD U G1 pre15, with forge 31.1.63

**Comment by RXJpaw** [comment]
Version: `1.15.2 HD U G1 pre15` (Forge-31.1.74)
Strange. Many people say shaders cause this issue (in pre13+)
In pre15 its the opposite.

![wqdfijefegfsdrg](https://user-images.githubusercontent.com/45784529/81055692-81794300-8ec9-11ea-9f71-a60d81342ae4.gif)

**Comment by sp614x** [comment]
Fixed, coming in pre16.

**Comment by truekaerf** [comment]
> 
> 
> Fixed, coming in pre16.

I can confirm that it is fixed for me with pre16!
