### ISSUE TITLE
[OptiFine 1.5.2 pre14] Startup Crashes with some other mods

### ISSUE THREAD

**Issue by cambiniric** [sp614x/optifine#3835]
## Description of Issue
Startup crash when OptiFine is not the only mod to be loaded

## Steps to Reproduce
Minecraft 1.15.2 + Forge 31.1.63
preview_OptiFine_1.15.2_HD_U_G1_pre14.jar in mods folder
one other mod in mods folder
launch Minecraft
just 2 mods in mods folder (OptiFine and another one)

## Xaeros_Minimap_20.10.0_Forge_1.15.2_20.10.0_Forge_1.15.2 (crashes loading a saved world)
[Xaeros_Minimap_ERROR.txt](https://github.com/sp614x/optifine/files/4569837/Xaeros_Minimap_ERROR.txt)

## Aquaculture-1.15.2-2.0.13
[Aquaculture_ERROR.txt](https://github.com/sp614x/optifine/files/4569838/Aquaculture_ERROR.txt)

## gravestone-1.15.2-1.17.3
[gravestone_ERROR.txt](https://github.com/sp614x/optifine/files/4569839/gravestone_ERROR.txt)

## XaerosWorldMap_1.5.7_Forge_1.15.2 (crashes loading a saved world)
[XaerosWorldMap_ERROR.txt](https://github.com/sp614x/optifine/files/4569845/XaerosWorldMap_ERROR.txt)

## BiomesOPlenty-1.15.2-10.0.0.352-universal
[BiomesOPlenty_ERROR.txt](https://github.com/sp614x/optifine/files/4569848/BiomesOPlenty_ERROR.txt)

## MrCrayfish's Furniture Mod 7.0.0-pre16-1.15.1
[Furniture_ERROR.txt](https://github.com/sp614x/optifine/files/4569854/Furniture_ERROR.txt)

## Additional Information  (Minecraft 1.15.2 + Forge 31.1.63)
OptiFine pre 14 works well with the following set of mods in "mods folder"
preview_OptiFine_1.15.2_HD_U_G1_pre14
ironfurnaces-1.15.2-2.0.3
jei-1.15.2-6.0.0.4
OreExcavation-1.7.151
Vanilla+ Tools-1.15.2-1.0
Hwyla-forge-1.10.8-B72_1.15.2
StorageDrawers-1.15.2-7.0.2
ironchest-1.15.2-10.0.3
SereneSeasons-1.15.2-3.0.0.68-universal
MrCrayfish's Backpacked Mod 1.4.1-1.15.2

**Comment by MightyFilipns** [comment]
use journeymap mod

**Comment by ocram9** [comment]
Have your tried pre 15? It has just been released and it fixed the crashing issues for me.

**Comment by cambiniric** [comment]
Yessss.... all these crashes have been solved with OptiFine pre15.... I'll have a look to journeymap too.... Huge THX
