### ISSUE TITLE
Item/Block Lighting Issues

### ISSUE THREAD

**Issue by MeinKraft** [sp614x/optifine#3838]
## Description of Issue
Some items/blocks in inventory/creative menus appear too dark

## OptiFine Version
preview_OptiFine_1.15.2_HD_U_G1_pre15

## Installation Method
drop the JAR file into your "mods" folder

## Fabric/Forge Version
Forge 31.1.63

## Other Installed Mods
jei-1.15.2-6.0.0.4

## F3 Debug Screenshot
[https://imgur.com/a/XAWFtI7](https://imgur.com/a/XAWFtI7)

## Prior Testing
Items in inventory still appear dark, creative, normal and inside JEI

**Comment by lesterlo** [comment]
I have this problem too, most of the thing in the inventory is dark.

**Comment by MeinKraft** [comment]
so the YAMDA thing appears not to be Optifine,  But the inventory items still appear dark when Optifine is installed

**Comment by sp614x** [comment]
Duplicate of #3830.
