### ISSUE TITLE
[1.15.2 pre 15] Glitched enchantment glint

### ISSUE THREAD

**Issue by Papas338** [sp614x/optifine#3842]
## Description of Issue
Using enchanted items with Chocapic13 shaders will make the items look completely purple and they bright a lot, this does not happen on 1.14

## Steps to Reproduce
1. Install Optifine lastest pre-release
2. Install Chocapic13 shaders.
3. Enter any world and equip enchanment equipment or end crystals.

## OptiFine Version
OptiFine 1.15.2 HD U G1 pre15

## Installation Method
I installed optifine with the installer

## Log Files/Crash Reports
https://pastebin.com/UFgrTiv3

## F3 Debug Screenshot
https://imgur.com/SNI0G5q

## Prior Testing
- Does this happen in Vanilla without OptiFine?
No

**Comment by sp614x** [comment]
Should be working in latest preview.
