### ISSUE TITLE
Optifine continues crashing me with forge 1.15.2

### ISSUE THREAD

**Issue by OskiGmer** [sp614x/optifine#3843]
I recently installed the pre14 and pre15 versions of optifine 1.15.2 and none has worked for me with forge 31.1.63.
In the mods folder I have only added the optifine when testing, therefore the failure cannot be due to an incompatibility with other mods, the inconvenience is caused by the optifine, as has always happened since the version  Minecraft 1.13.2.
I would appreciate a solution, good afternoon.

**Comment by gwingle** [comment]
If this _always_ happens when you are using Optifine, it sounds to me like you are placing the installer jar in the mod folder. You should be opening the installer and using the "extract" option to get the Forge-compatible mod file.

**Comment by OskiGmer** [comment]
hello, thanks for your answer, but unfortunately that method has not worked for me either

**Comment by vikenemesh** [comment]
Having the same Problem. I properly installed a fresh 1.15.2 version. Used the Forge 31.1.63 installer and then used the OptiFine 1.15.2_HD_U_G1_pre15 Installer to extract the MOD.jar to the .minecraft/mods folder.

That should've worked, right?

**Comment by sp614x** [comment]
Does the game crash or doesn't start?
Can you post the crash report?
Have you tried finding which other mod is conflicting with OptiFine.

**Comment by KaiAF** [comment]
no response from the author.
