### ISSUE TITLE
[1.15.2] The block breaking animation only appears on one block side

### ISSUE THREAD

**Issue by vapaternina** [sp614x/optifine#3845]
## Description of Issue
When I try to take a block, only the animation appears for one of the surfaces.

## Steps to Reproduce
Pick a block

## OptiFine Version
The last 1.15.2 pre14 for today, May 3. pre15 (May 3) too.

## Installation Method
JAR file into your "mods" folder

## Fabric/Forge Version
forge-31.1.63

## Other Installed Mods
None

## Log Files/Crash Reports
debug.log: https://pastebin.com/RabDW2n9
latest.log: https://pastebin.com/2AuXf0qw

## F3 Debug Screenshot
![image](https://user-images.githubusercontent.com/16907375/80921374-9cb64800-8d3b-11ea-9846-5811be5f731f.png)

## Prior Testing
- Only OptiFine and Forge
Does not work fine
- Does this happen without any mods at all?
Only forge-31.1.63 without mods works fine
- Does this happen in OptiFine standalone?
Works fine
- Does this happen in Vanilla without OptiFine?
Works fine

![image](https://user-images.githubusercontent.com/16907375/80920927-94104280-8d38-11ea-9b1a-755c66bab3f7.png)

**Comment by sp614x** [comment]
Should be fixed in latest preview.
