### ISSUE TITLE
Shaders-Sunlight goes thru blocks (only sunlight)

### ISSUE THREAD

**Issue by PSFSlina** [sp614x/optifine#3847]
It randomly goes thru blocks in caves and etc.

on the 1.15.2-Optifine_HD_U_G1_pre13

**Comment by asbyth** [comment]
known, this is due to blaze3d removing what's called "shadowmap backface culling", which is also a part of the reason as to why performance hasnt been so great according to some members of the discord, and is likely out of sp614x's capability to add back into the game

**Comment by Deviouslrd** [comment]
Is there really any way to make a workaround to fix this issue by the time the full release comes out?
Or is the only way to remove the sunlight in caves by having the "shadowmap backface culling" or something similar added back?

**Comment by sp614x** [comment]
Same as #3634.

**Comment by sp614x** [comment]
Fixed in pre22.
