### ISSUE TITLE
optifine 1.14.4 not compatible with forge later than 28.2.0

### ISSUE THREAD

**Issue by wraith3690** [sp614x/optifine#3848]
optifine does not work with forge newer than 28.2.0 for 1.14.4 newer versions are needed for many popular mods like immersive engineering

**Comment by djcraft** [comment]
hello,
I have a similar problem. I saw an issue that said it was ok but no version of Optifine works with Forge 28.2.0 and above. I am attaching an already existing log file. I specify that I do not play in crackeret that I play ave a completely official version of MC
[crash-2020-05-05_21.32.21-client.txt](https://github.com/sp614x/optifine/files/4600506/crash-2020-05-05_21.32.21-client.txt) 
[debug-5.log.gz](https://github.com/sp614x/optifine/files/4600514/debug-5.log.gz)

I also specify that this bug with or without mod on MultiMC or the official launcher.

Thanks for your help

**Comment by wraith3690** [comment]
I have found a way to get it running I used optiforge mod https://www.curseforge.com/minecraft/mc-mods/optiforge
