### ISSUE TITLE
Optifine pre15 not compatible with Structurize mod

### ISSUE THREAD

**Issue by Residentj3553** [sp614x/optifine#3849]
## Description of Issue
Error loading mod:
"Structurize (structurize) encountered an Error during the sided_setup event phase"
https://imgur.com/a/wBuLDU2

## Steps to Reproduce
https://www.curseforge.com/minecraft/mc-mods/structurize/files
1. Install latest Structurize mod (structurize-0.10.311) with Optifine in the same mods folder.
Structurize works fine without Optifine installed.

## OptiFine Version
OptiFine 1.15.2 HD U G1 pre15

## Installation Method
Dropped the Optifine JAR file into forge "mods" folder?

## Fabric/Forge Version
 Minecraft Forge 1.15.2 - 31.1.63

## If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   Removed every mod except Structurize and Optifine and it still persists.

**Comment by AlMasque** [comment]
fixed in the latest structurize update
