### ISSUE TITLE
Inventory with Screenshot Size

### ISSUE THREAD

**Issue by Jerozgen** [sp614x/optifine#385]
It works not correct.
![2016-12-04_13 52 29](https://cloud.githubusercontent.com/assets/17567951/20865658/3509689c-ba29-11e6-9d94-b6f2ce182ab6.png)

**Comment by TheHADILP** [comment]
Related to:
https://github.com/sp614x/optifine/issues/352

**Comment by sp614x** [comment]
Duplicate of #352
