### ISSUE TITLE
[Performance] CPU usage at 100% when loading a world and loading chunks

### ISSUE THREAD

**Issue by FreshwaterShrimp** [sp614x/optifine#3850]
## Description of Issue
Whenever I load into a world or server OR load chunks, the games CPU usage maxes out and all my other applications freeze up. This doesn't happen when playing without Optifine.

## Steps to Reproduce
1. Load the game with optifine
2. Load into a server/word or load chunks.

## OptiFine Version
OptiFine 1.15.2 HD U G1 pre15

## Installation Method
I used the standalone installer.

## F3 Debug Screenshot
![image](https://user-images.githubusercontent.com/36347138/80924900-c72bf380-8d83-11ea-9e97-35b2106f1d9f.png)

## Prior Testing
This does NOT happen in vanilla

**Comment by sp614x** [comment]
OptiFine is optimizing the game to use all available CPU resources to increase the performance.
The operating system should balance the CPU usage between the different applications.
Can't be fixed by OptiFine.
