### ISSUE TITLE
Banner bug.

### ISSUE THREAD

**Issue by JrShellBullets** [sp614x/optifine#3853]
## Description of Issue
Banners having grid-like texture on them.

## Steps to Reproduce
1. Get a banner. 
2. Place it down or hang it.

## OptiFine Version
Minecraft 1.15.2. Optifine pre15

## Installation Method
I went to the official site and clicked 'Downloads' Then preview versions. After that, I clicked Download. For version 1.15.2 pre15. Then once I got it installed. I double tapped the .jar file in my downloads. And started downloading it using the .jar file.

![image](https://user-images.githubusercontent.com/64763690/80934458-1f132c00-8d7d-11ea-99aa-fb5c288b252b.png)

**Comment by BBftw** [comment]
you need to say you're using shaders. also, have you tried another shader besides BSL?

**Comment by sp614x** [comment]
Should be working in latest preview.
