### ISSUE TITLE
Inventory bar texture bugs

### ISSUE THREAD

**Issue by Rangel777** [sp614x/optifine#3854]
![2020-05-04_01 15 11](https://user-images.githubusercontent.com/64765346/80936031-bee4b000-8da5-11ea-895a-0539dabd9dca.png)

**Comment by Rangel777** [comment]
forge last upd + optfine last upd (1.15.2)

**Comment by asbyth** [comment]
known

**Comment by yezhiyi9670** [comment]
Duplicate of #3837

**Comment by Regnander** [comment]
>Duplicate of #3837 

Which in turn is a duplicate of #3830

**Comment by Rangel777** [comment]
i didnt know, sorry

**Comment by Regnander** [comment]
> i didnt know, sorry

No harm done. Don't worry about it.

**Comment by sp614x** [comment]
Duplicate of #3830.
