### ISSUE TITLE
BUG Breaking Block Animation and hitting mob animation do not work.

### ISSUE THREAD

**Issue by Stormtrooper065** [sp614x/optifine#3860]
When I try to break a block the cracks are not there and when I hit a mob it does not flash red, however the breaking animation does appear on some blocks such as beds, bells, and chests. Possibly others.

## Steps to Reproduce
1. Open Minecraft
2.Use optifine (Sildurs Shaders)
3. Find blocks or mobs and break or kill...
## OptiFine Version 1.15.2 peview 13 and 15
Self-explanatory. 

## Installation Method
I use the default installer.

## Other Installed Mods
Modern Warefare mod and custom NPC mod

## F3 Debug Screenshot
![image](https://user-images.githubusercontent.com/64605758/80981328-ae046080-8dde-11ea-96d5-9bec74b1593a.png)

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
no.

**Comment by asbyth** [comment]
known, duplicate of [insert 20 other github issues]

**Comment by Cheetopants1111** [comment]
Yeah with the pre 19 it does this to me where only certain blocks show breaking animations and selection outlines.

**Comment by sp614x** [comment]
Duplicate of #3600 and #3598.
