### ISSUE TITLE
Bug with transparent texture and shaders

### ISSUE THREAD

**Issue by qba567** [sp614x/optifine#3862]
Hi, I m making a resource pack, that is using CEM for making new mobs, but I ve found an issue with transparent texture, that is showing as black, when Im using shaders, i ve tried to update my shader packs, but without result (testing on SILDURS and SEUS).

## OptiFine Version
1.14.4 HD_U_F5

I ve used standalone installer.

![2020-05-04_23 06 40](https://user-images.githubusercontent.com/60390430/81014076-805dfc80-8e5c-11ea-9d0a-2020b2a7fd47.png)
![2020-05-04_23 06 57](https://user-images.githubusercontent.com/60390430/81014077-80f69300-8e5c-11ea-93bf-fa24847eb28f.png)
![2020-05-04_23 07 12](https://user-images.githubusercontent.com/60390430/81014080-818f2980-8e5c-11ea-9f85-bcb632c08d96.png)

**Comment by ewanhowell5195** [comment]
this isnt an issue with shaders and is an issue with your texture. you need to make your texture transparent where you want it to be transparent, and need to make sure the alpha channel of the texture there is set to 0.

**Comment by KaiAF** [comment]
@ewanhowell5195 provided the fix, try that. If you are still having any issues, let us know.
