### ISSUE TITLE
[Bug][1.15.2] Emissive particles on item pickup with Forge + Shaders|OptiForge

### ISSUE THREAD

**Issue by yezhiyi9670** [sp614x/optifine#3863]
## Description of Issue

Emissive particles on item pickup (randomly). See ZekerZhayard/OptiForge#20.

## Steps to Reproduce

1. Install Forge and Optifine.
2. Install OptiForge, or enable the internal shaders in Optifine. 
3. Create a new world, set to night, peaceful, survival.
4. Mine some dirt. Note that the destruction particles may become emissive for a few frames while picking up the dirt item.
5. If this does not occur, restart the game and try again. Generally, it will occur in 3 tries.

## OptiFine Version

1.15.2 G1 pre15

## Installation Method

Both

## Fabric/Forge Version

Forge 31.1.74, OptiForge 0.1.17

## F3 Debug Screenshot

Will add soon.

## Prior Testing

Optifine, Forge, OptiForge or Optifine, Forge, Shaders is the minium set to reproduce this issue.

**Comment by yezhiyi9670** [comment]
Workaround:

Toggle Fast Math before each startup. This can be done by editing `optionsof.txt`.

It can be automated with a little code (PHP is the only lightweight language I master so far):

```php
<!-- modify-optifine-settings.php under Minecraft runtime directory -->
<?php

define("DIR",str_replace("\\",'/',__DIR__) . '/');

$file = DIR . "optionsof.txt";

$data = file_get_contents($file);

if(strstr($data,'ofFastMath:true')) {
	$data = str_replace('ofFastMath:true','ofFastMath:false',$data);
} else {
	$data = str_replace('ofFastMath:false','ofFastMath:true',$data);
}

file_put_contents($file,$data);

/*
    Set this as Minecraft pre-launch command:
        php D:\[redacted]\.minecraft\versions\1.15.2\modify-optifine-setting.php
*/
```

**Comment by sp614x** [comment]
Should be fixed in latest preview.
OptiForge is not needed anymore.
