### ISSUE TITLE
[Bug] gbufferModelView goes wrong in Composite Vertex Shader

### ISSUE THREAD

**Issue by Cmyna** [sp614x/optifine#3866]
It is impossible to use two uniform matrices` gbufferModelView` and `gbufferModelViewInverse` in composite vertex shader, because they will gives completely wrong results if apply them in any computations
For example:
```
gl_Position = gl_ProjectionMatrix * gbufferModelView * gbufferModelViewInverse * gl_ModelViewMatrix * gl_Vertex;
```
this code transforming vertices to clip space works perfactly in other vertex shaders such as gbuffers_terrain, but if it is used in composite or final shaders, it will causes flashing when moving camera.
This bug also makes it impossible to get worldspace position in composite vertex shader, as I have mentioned in the last issue I posted. I don't know what the hell I got from the code below but it definitely not the world space position:
```
vec4 position = gbufferModelViewInverse * gl_ModelViewMatrix * gl_Vertex;
position += vec4(cameraPosition.xyz,0.0);
```

**Comment by rre36** [comment]
The composite passes do not have any world geometry. You have to calculate the positions of the geometry based on the depth buffer in the fragment stage.

**Comment by sp614x** [comment]
The composite pass renders a single quad as big as the screen with no relation to world geometry.
