### ISSUE TITLE
Dark item icons and weird looking block while destroying

### ISSUE THREAD

**Issue by Kubagf** [sp614x/optifine#3867]
im using few mods but without them the problem appears too

![2020-05-05_13 34 45](https://user-images.githubusercontent.com/59142622/81061808-4b41c080-8ed5-11ea-93aa-729b47030fc9.png)

![2020-05-05_13 35 08](https://user-images.githubusercontent.com/59142622/81061857-5f85bd80-8ed5-11ea-81cc-a4d05b601341.png)

**Comment by Kubagf** [comment]
my resolution is 1920x1080, but i'm using 2x screenshot feauture in minecraft

**Comment by yezhiyi9670** [comment]
Use [OptiForge](https://www.curseforge.com/minecraft/mc-mods/optiforge) to fix these compatibility issues.

**Comment by yezhiyi9670** [comment]
Related to #3830

**Comment by sp614x** [comment]
Duplicate of #3830.
