### ISSUE TITLE
CIT Armor doesn't work any

### ISSUE THREAD

**Issue by Nayx91** [sp614x/optifine#3872]
The CIT for armor does not work any !

I did create a pack where i have like ruby diamond armor. it works by just naming a armor ruby but when i try it the armor doesn't look like what i want !

In 1.14.4 with optifine it works perfectly and in the preview 14 of optifine 1.15.2 my game crashed multiple times !

**Comment by Pumpking0108** [comment]
I know! so frustrating!

**Comment by Nayx91** [comment]
> I know! so frustrating!

yeah

**Comment by sp614x** [comment]
Duplicate of #3588.
