### ISSUE TITLE
[BUG] Banners glitching out

### ISSUE THREAD

**Issue by criticboi420** [sp614x/optifine#3874]
## Description of Issue
Not sure if this is with optifine or with the shaders I use but when I place any type of banner it flashes white. (In the screenshot It might look like I'm crazy but I can't post videos so that'll have to do)

## Steps to Reproduce
Place a banner down while using SEUS shaders

## OptiFine Version
1.15.2 pre15

## Installation Method
Standalone

## F3 Debug Screenshot
![2020-05-05_22 25 36](https://user-images.githubusercontent.com/64885405/81140764-705b2100-8f1f-11ea-93ae-b4c76328b74b.png)

## Prior Testing
- Does this happen in Vanilla without OptiFine?
No

**Comment by sp614x** [comment]
Fixed, coming in pre18.
