### ISSUE TITLE
[1.15.2pre-16] Rain displays through all other blocks when picking up an item.

### ISSUE THREAD

**Issue by FrankenBobbo** [sp614x/optifine#3875]
Pick up a block while it is raining, then the rain will display through all other blocks for a split second

## Steps to Reproduce
1. Set weather to rain
2. Pick up a block while standing behind other blocks, and you will be able to see the rain through them momentarily

## OptiFine Version
OptiFine 1.15.2 preview 16

## Installation Method
Used OptiFine installer.

## F3 Debug Screenshot
![2020-05-06_16 28 26](https://user-images.githubusercontent.com/64887834/81144091-adbebd80-8fb6-11ea-8c7c-ebe59ad9c68f.png)

## Prior Testing
This issue does not happen in vanilla 1.15.2 WITHOUT OptiFine, only happens WITH OptiFine

**Comment by Regnander** [comment]
Vanilla bug: https://bugs.mojang.com/browse/MC-163575

If you want to, you can create an account there and click "Start watching this issue" to get email notifications when it is resolved.

**Comment by sp614x** [comment]
Vanilla bug.
