### ISSUE TITLE
[1.15.2] CTM with blocks 0-46 doesn`t work correctly

### ISSUE THREAD

**Issue by Norzeteus** [sp614x/optifine#3876]
Preview_OptiFine_1.15.2_HD_U_G1_pre16 installed allone(the included standalone installer) or using with Forge 1.15.2-forge-31.1.63 and
worldedit-forge-mc1.15.2-7.1.0 causes the same problem: CTM with blocks 0-46 do not connect correctly, the "T" block does not work.

**Comment by sp614x** [comment]
Can you post a screenshot showing the problem and a small resource pack that triggers it?

**Comment by Norzeteus** [comment]
This problem has been only in 1.15.2_HD_U_G1_pre16, in pre 1.15.2_HD_U_G1_pre18 it works correct again,thx... 👍
