### ISSUE TITLE
Shader bugs and effective slow down in 1.15.2 PRE16

### ISSUE THREAD

**Issue by tenshiaka** [sp614x/optifine#3879]
## Description of Issue
Mostly with SEUS shaders, once activated the shaders togheter with a parallax resource pack, some blocks that should not reflect in any way will do so, and will take the Shader's water texture as a layer of their's. I also noticed a slow down (fps) from when i downloaded the last version 

## Steps to Reproduce
1. Activate SEUSV11 shaders
2. Activate UltimaCraft resource pack

## OptiFine Version
PRE16 of 1.15.2
## Installation Method
Classic WIZARD optifine installer

![image](https://user-images.githubusercontent.com/64901373/81170581-3b8caf80-8f9b-11ea-8451-56bb2cecef37.png)

## Prior Testing
If you've installed standalone:
- only with optifine and shaders

## Additional Information
Also did reset my chunk pregeneration values

**Comment by sp614x** [comment]
Should be fixed in pre22.
