### ISSUE TITLE
[1.15.2] Shader block breaking texture is transparent

### ISSUE THREAD

**Issue by tenshiaka** [sp614x/optifine#3880]
## Description of Issue
When breaking a block instead of the classic animation will show the block as transparent

## Steps to Reproduce
1. Activate SEUSV11 shaders
2. Break an oak_wood block

## OptiFine Version
PRE16 1.15.2

## Installation Method
CLASSIC WIZARD OPTIFINE INSTALLER

## F3 Debug Screenshot
![image](https://user-images.githubusercontent.com/64901373/81171352-878c2400-8f9c-11ea-9d3a-9d7af54c8fe0.png)

## Prior Testing

- with OptiFine

**Comment by sp614x** [comment]
Fixed in pre23.
