### ISSUE TITLE
Leaves not being shaded with Sildurs

### ISSUE THREAD

**Issue by NolaNorth** [sp614x/optifine#3882]
## Description of Issue
When on optifine pre16 Sildurs shaded leaves for a couple hours and then the leaves suddenly stopped being shaded. Every tree just has the wood blocks shaded

## Steps to Reproduce
1. I'm not sure how to reproduce, no one else ive talked to has had this issue.

## OptiFine Version
Pre 16
## Installation Method
I used the standalone launcher

## F3 Debug Screenshot
![2020-05-06_13 06 47](https://user-images.githubusercontent.com/64919163/81206742-8b1eab80-8f9a-11ea-8fbc-90b820d53d08.png)

![2020-05-06_13 10 27](https://user-images.githubusercontent.com/64919163/81207047-f799aa80-8f9a-11ea-938c-4b6e4fa04d17.png)

## Prior Testing
Does this happen in vanilla?
No

**Comment by naeqirelle2020** [comment]
@NolaNorth does this occur on the latest preview?

**Comment by sp614x** [comment]
Should be fixed in latest preview.
