### ISSUE TITLE
[1.15pre] Crash after eating a steak.

### ISSUE THREAD

**Issue by Bellwar** [sp614x/optifine#3889]
## Description of Issue
I don't even know if it crashed because of optifine or something else. I can't tell. I ate a steak and the game crashed afterwards.

## Steps to Reproduce
Can't reproduce since part of my chunk got deleted.

## OptiFine Version
OptiFine 1.15.2 HD U G1 pre16

## Installation Method
Dropped in mods folder

## Fabric/Forge Version
Forge 31.1.37

## Other Installed Mods
In the crash report

## Log Files/Crash Reports
https://pastebin.com/k0763eVt

## F3 Debug Screenshot
![2020-05-07_11 35 39](https://user-images.githubusercontent.com/9407653/81279291-3ab95380-9057-11ea-8eeb-981bb40dfe75.png)

## Prior Testing
Since I can't reproduce this I can't do testing. But I never came across this crash before and it happened 10 minutes into playing with optifine.

## Additional Information
I can't tell much more. I don't even know if it is Optifine, but it happened after I got this in.
EDIT: I could add that part of my world is deleted (one whole redstone contraption). I wasn't looking at it or that way when it happened.

**Comment by sp614x** [comment]
Redstone update triggers a block update which writes an invalid value in the chunk palette.
Not related to OptiFine, either Forge or vanilla problem.
