### ISSUE TITLE
Seus Shader geometry bug

### ISSUE THREAD

**Issue by JeffreyHansen** [sp614x/optifine#3894]
Within 70 meters of a block, all lighting from light sources are invisible.

**Comment by sp614x** [comment]
Which OptiFine version?

**Comment by yoyotam3** [comment]
I believe JeffreyHansen is referring to SEUS PTGI in Optifine 1.15.2. Apparently this is caused by geometry shaders not working in the current Optifine 1.15.2 prereleases, but I'm not sure.

**Comment by Jiingy** [comment]
Closing as this issue is 3 years old with no update to the vague information provided.
