### ISSUE TITLE
[Cape] Name Changed Cape Gone

### ISSUE THREAD

**Issue by Kepy7** [sp614x/optifine#3896]
## Description of Issue
Please provide as much detail as possible.

## Steps to Reproduce
1. What do you do... 
2. ...to find this bug? I changed my name on Minecraft from xKEPYx To Kreepy7 and my cape has vanished, I reloaded the cape, twice and made sure cape was on. It was a custom type banner it looked like this https://www.planetminecraft.com/banner/radioactive-banner-94983/.

## OptiFine Version
Self-explanatory. Latest 1.15.2

## Installation Method
How did you install OptiFine? Did you use the included standalone installer, or did you drop the JAR file into your "mods" folder? I downloaded optifine 1.15.2 mirror JAR and installed it, it still works and has for a while, but my cape vanished when I changed my name from xKEPYx to Kreepy7

## F3 Debug Screenshot
Minecraft's built-in debug screen provides *a lot* of useful information, and should be included even if the issue is not something that can be captured in a still image.

To open this menu, simply press `F3` on your keyboard while in-game. Please ensure the text is easily readable. Depending on the size/resolution of your monitor, you may have to adjust your GUI scale for all text to be completely visible on-screen.

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
No I only have an optifine cape.

- Does this happen in Vanilla without OptiFine? Again no I only have an optifine cape.

## Additional Information
Here goes any final remarks and everything else that might not fit in the previous sections.
My previous name in which I got the cape was xKEPYx my new name is Kreepy7 the pattern is https://www.planetminecraft.com/banner/radioactive-banner-94983/ please help!

**Comment by asbyth** [comment]
this is normal, you can open the cape editor ingame and it should be back.

**Comment by fishfriend0food** [comment]
This happened to my friend a few days ago and he got it back. All you have to do is move your cape to your username you have right now and reload your cape or relaunch minecraft and it should work.

**Comment by Kepy7** [comment]
Thank You It Worked :D
