### ISSUE TITLE
[Texture Bug] Loading Impact Client Causes Screen to Blank

### ISSUE THREAD

**Issue by H4LCY0N-4G3** [sp614x/optifine#3897]
When optifine is installed next to impact versions, optifine causes texture glitch to make the screen freeze on loading texture.

Unknown if some code clash or what.

Might not be relevant, but an issue that could be of interest.

**Comment by asbyth** [comment]
optifine doesnt support hacked clients

**Comment by H4LCY0N-4G3** [comment]
I know it doesn't directly support hack clients in any way shape or form, but the visual bugs seem concerning as they exist inconsistently on the base version without client active.

**Comment by Deviouslrd** [comment]
If it only happens using the hacked client, then its an issue with the client. Use the official launcher.

**Comment by sp614x** [comment]
OptiFine doesn't support and doesn't do anything related to hacked clients.
