### ISSUE TITLE
CIT Not working for clock and compass

### ISSUE THREAD

**Issue by sixfootblue** [sp614x/optifine#390]
Hello!

I've recently tried using CIT on clock and compass items and found that the textures are not changing. Is this a bug? Or is this currently not possible due to the nature of these items.

**Comment by sp614x** [comment]
The CIT dial animations (compass and clock) are not implemented.
Vanilla allows custom clock and compass models to be used:
- assets/minecraft/models/item/clock.json
- assets/minecraft/models/item/compass.json
