### ISSUE TITLE
Optifine not loading textures custom armour when wearing

### ISSUE THREAD

**Issue by gladmountain** [sp614x/optifine#3900]
Custom armor doesn't show the custom texture when wearing the custom armor. 
the custom texture is showing in inventory and on armour stands. 
See picture

![texture pack](https://user-images.githubusercontent.com/64728649/81433536-ff0caf80-9164-11ea-9eb7-aacba609fcc6.png)

**Comment by Regnander** [comment]
Which version?

**Comment by gladmountain** [comment]
1.15.2-optifine_HD_U_GI_pre14

Op za 9 mei 2020 om 08:50 schreef A. Regnander <notifications@github.com>:

**Comment by Regnander** [comment]
Pre16 was released a few days ago. Can you upgrade and check if the bug still is there?

**Comment by gladmountain** [comment]
Hello

The problem is still the same.

Op za 9 mei 2020 om 09:32 schreef A. Regnander <notifications@github.com>:

**Comment by sp614x** [comment]
Duplicate of #3588.
