### ISSUE TITLE
[1.15.2 pre16] CEM problem

### ISSUE THREAD

**Issue by Day-OS** [sp614x/optifine#3901]
![guardian](https://user-images.githubusercontent.com/43686351/81447701-83eecd80-9153-11ea-9dc2-4653b88c6893.png)
![donkey](https://user-images.githubusercontent.com/43686351/81447705-851ffa80-9153-11ea-8b55-b6839160eaf6.png)

Transmobifier prints:
![Screenshot_4](https://user-images.githubusercontent.com/43686351/81479285-aedf2d00-91f8-11ea-8582-88433e32e368.png)
![Screenshot_3](https://user-images.githubusercontent.com/43686351/81479286-b0105a00-91f8-11ea-82f8-8a59f2992af2.png)

## Description of Issue
Custom textures doesn't work with CEM. This same problem happens when I combine the random entities texture feature with the CEM.

## Steps to Reproduce
Use some Resourcepack that has CEM (Ex: Transmobifier and Mickey Joe's RID).
Edit1: I doesn't happens with Mickey Joe's texture as I thought, but it does happens with the Transmobifier one.

## OptiFine Version
OptiFine 1.15.2 HD U G1 pre16

**Comment by MushirMickeyJoe** [comment]
> Custom textures doesn't work with CEM. This same problem happens when I combine the random entities texture feature with the CEM.

What does that mean? My pack combines custom textures and CEM (in zombies, skeletons, pigs, for example), which works fine.

**Comment by Day-OS** [comment]
Are you using the same version?

**Comment by DvojiteV** [comment]
Yeah I found also this bug with wolf mob other mobs that use custom CEM are normal as they were on 1.14 optifine (pig, cow 100% sure they are fine) so I have issue only with wolf.

**Comment by RobinBoers** [comment]
Is it already fixed?

**Comment by Day-OS** [comment]
Yep

**Comment by RobinBoers** [comment]
Ok, tnx
