### ISSUE TITLE
Minecraft 1.8.9 with Forge and Optifine 1.8.9_HD_U_H6 will crash at startup

### ISSUE THREAD

**Issue by ErikSteiner** [sp614x/optifine#391]
Hi guys,

I recently tried to get an answer at the forum, but it looks like I've been overlooked.
My problem is, that I am unable to use Optifine. I had this problem with Minecraft 1.7.10 and 1.6.4., but I was able by adding the required custom argument. This time on 1.8.9, I am out of ideas..

[Crash log.txt](https://github.com/sp614x/optifine/files/644803/Crash.log.txt)

**Comment by sp614x** [comment]
Which launcher are you using?
How is OptiFine installed?
What were the needed custom arguments?

**Comment by Jerozgen** [comment]
![image](https://cloud.githubusercontent.com/assets/17567951/21087605/6ebfa456-c038-11e6-8045-9f0695df65a1.png)

**Comment by ErikSteiner** [comment]
Hi there,
thank you for your reply. I am using Magic Launcher 1.3.4. I installed Optifine like I always did, I clicked on Setup in Magic Launcher and added Optifine with the "Add-Button". As far as I can see it at your thread, the custom argument should be "-Dfml.ignorePatchDiscrepancies=true".

I did the following:
I started with no Minecraft folder. Executed Minecraft.exe and created immediately a new Profile:
![profile](https://cloud.githubusercontent.com/assets/2684018/21090594/0afdad56-c041-11e6-98d1-97d66823cae7.jpg)

I then started the game and closed Minecraft when I entered the main menu.
I then installed Forge 1.8.9 - 11.15.1.1902 (latest), after it I started Magic Launcher, hit Setup and changed the environment to 1.8.9-forge1.8.9-11.15.1.1902-1.8.9. At this point I clicked Login to start Minecraft with no mods installed and I didn't add Optifine. When I entered the main menu, I closed the game, added my Mods and Optifine. I navigated to advanced to enter the Parameter "-Dfml.ignorePatchDiscrepancies=true". I don't know why, but Magic Launcher will tell me that Forge isn't installed, even if I can launch the game with Forge and my mods..

![ml1](https://cloud.githubusercontent.com/assets/2684018/21090852/d5f4ee1a-c042-11e6-89ea-19ef4c21b8f8.jpg)

![ml2](https://cloud.githubusercontent.com/assets/2684018/21090854/d9d14222-c042-11e6-890b-689d5c3fc6f4.jpg)

**Comment by sp614x** [comment]
You can try to double-click the OptiFine JAR, then select Extract and save the MOD file.
Add the MOD file in MagicLauncher and it should be recognized correctly.

**Comment by ErikSteiner** [comment]
I extracted the file and clicked "Add" to add it to the Mods tab. Do you mean that, or should I move the extracted MOD file to the mods folder?

So if I add the MOD file to Magic Launcher with the Add button, I will get a massiv error log at startup
[Crashed.txt](https://github.com/sp614x/optifine/files/645890/Crashed.txt)

**Comment by ErikSteiner** [comment]
I tried to move the MOD file to the Mods folder and I don't know if this was intended, but it is working now.

**Comment by sp614x** [comment]
Maybe there are several copies of OptiFine:
- in the Forge's "mods" folder
- in the Magoc Luancher mod list

The game may crash if it tries to load several mod copies at once.
