### ISSUE TITLE
[Bug Texture] Custom Texture cit

### ISSUE THREAD

**Issue by Flagiel** [sp614x/optifine#3911]
## Description of Issue
**I created a custom item with blockbench the model appears perfectly in the inventory, but my itemp does not change in the hand or in an itemp frame.
_ps: I tried in 1.14.2 everything works perfectly_
Sorry for my english.**

## Steps to Reproduce
**1: create a personalized model with blockbench
2: import with optifine
3: change the name of the desired item
4: take the object in the hand**

## OptiFine Version
**OptiFine 1.15.2 HD U G1 pre16**

## Installation Method
Did you use the included standalone installer: **Yes**

## F3 Debug Screenshot
![2020-05-10_11 03 00](https://user-images.githubusercontent.com/53080651/81495147-6e41eb00-92ae-11ea-9c8f-a7edd286ef5c.png)
![2020-05-10_11 07 04](https://user-images.githubusercontent.com/53080651/81495154-769a2600-92ae-11ea-9d07-832e9a87aad2.png)
![2020-05-10_11 12 51](https://user-images.githubusercontent.com/53080651/81495246-44d58f00-92af-11ea-924b-d1b0f241dd03.png)

**Comment by MrVenom0** [comment]
Custom item textures dont work in 1.15.2 preview you will have to wait for the full release of it.
Just work in 1.14 as thats the same thing and you can just move to 1.15.2 when its done

**Comment by bloggy** [comment]
Same issue here.

**Comment by sp614x** [comment]
Fixed, coming in pre20.
