### ISSUE TITLE
[1.15.2_pre16] Glowing effect not working when Shaders or Fast Render are enabled

### ISSUE THREAD

**Issue by FranJose13** [sp614x/optifine#3914]
Glowing effect is simply not worging and its annoying the bug is in OptiFine 1.15.2 HD U G1 pre16

**Comment by Mickael97o** [comment]
Same here, but turning off fast render will solve the problem. (at least it worked for me)

**Comment by Aeltumn** [comment]
Bump, would really like to see this fixed! Really annoying that some users are completely unable to see the glowing effect.

**Comment by sp614x** [comment]
Is the glowing effect missing with shaders or without shaders?

**Comment by Aeltumn** [comment]
The glowing effect is missing when using shaders, but this issue is rather about the glowing effect not working when using the Fast Render setting.

**Comment by sp614x** [comment]
Duplicate of #3662.
