### ISSUE TITLE
[1.15.2 pre16] Silver shulker GUI not working

### ISSUE THREAD

**Issue by VloBoo** [sp614x/optifine#3917]
Sorry for the errors in the text, I do not know English well
## Description of Issue
I made my texture pack for the GUI. And he noticed that the silver shalker has not changed.
(all other colors work)

## Steps to Reproduce
1.  test my texture
2.  open silver shalker

## OptiFine Version
1.15.2 pre16

## Installation Method
I use the included standalone installer

## Log Files/Crash Reports
https://gist.github.com/VloBoo/9c9834a0b59fa1d8fd65d0ae1020f879

on line 492 writes that there is find such color

## F3 Debug Screenshot

![image](https://user-images.githubusercontent.com/60321021/81568760-e5f34100-93a6-11ea-9c00-d910747000ed.png)

## Additional Information

Here is the texture pack that I made for the test

[testOF(vloboo).zip](https://github.com/sp614x/optifine/files/4609928/testOF.vloboo.zip)

**Comment by naeqirelle2020** [comment]
Wrong name for the color, it's not silver it's 'light gray'

![2020-06-05_05 17 36](https://user-images.githubusercontent.com/63185833/83836640-fb306680-a6eb-11ea-9d0d-3de03e3af266.png)

**Comment by VloBoo** [comment]
The documentation mentions the color is silver, not light gray

https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/custom_guis.properties

**Comment by sp614x** [comment]
Updated documentation:
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/custom_guis.properties#L162
