### ISSUE TITLE
[website] Invalid E-Mail adress?

### ISSUE THREAD

**Issue by DrLuchs** [sp614x/optifine#3919]
I was planning on donating to Optifine in order to get a cape and to support the developers, but in the process, my E-Mail is seen as "invalid". It's also the correct E-Mail that's tied to the username I've given for the cape. 
The error says "Invalid E-Mail adress: " and then my adress.

**Comment by sp614x** [comment]
What is the email address?

**Comment by ZenIsBestWolf** [comment]
Should be resolved; If not, please contact Support via Discord, Twitter, or Email.
