### ISSUE TITLE
DynamicLights >> Burning Entities radiate Light through Blocks

### ISSUE THREAD

**Issue by StunterLetsPlay** [sp614x/optifine#3922]
In the example down below I have created a Custom Ore using a Plugin I have written.
This Custom Ore uses a Armor Stand which is constantly on fire overlayed with an Iron Ore Block to create the illusion of a Custom Block.

The problem here: An Entity which is set on fire actually radiates light through Blocks.

![image](https://user-images.githubusercontent.com/36774926/81667373-7aab7c80-9443-11ea-9fb5-36b04589b4b3.png)

![image](https://user-images.githubusercontent.com/36774926/81667398-8303b780-9443-11ea-8fc2-9041b0373b7a.png)

**Comment by sp614x** [comment]
This can't be fixed without significant performance problems.
