### ISSUE TITLE
[1.15.2 pre16] CEM problem

### ISSUE THREAD

**Issue by Kreepir** [sp614x/optifine#3928]
## Description of Issue
Please provide as much detail as possible.
I created a custom Iron golem using blockbench and when i added it to my custom resource pack i get this result..... left side is in-game right side is the build in Block Bench.

![Untitled](https://user-images.githubusercontent.com/65251072/81734389-6aa29580-9461-11ea-88d0-4f7b5ca7a14b.png)

## Steps to Reproduce
1. exported project as optifine JEM, 
2. move it to the optifine/cem folder as iron_golem.jem
3.ensured textures were in the appropriate folder
4.placed in my resource pack with the other files(all of which work)

## OptiFine Version
1.15.2-Optifine_HD_U_G1_pre16

## Installation Method
Standalone

## Other Installed Mods
I dont have other mods installed, just general resource packs that should work with optifine such as sapix craft. 

Here's the entity data if that's of used
/summon minecraft:iron_golem -5800.16 69.00 -3614.77 {Brain: {memories: {}}, HurtByTimestamp: 0, Attributes: [{Base: 100.0d, Name: "generic.maxHealth"}, {Base: 1.0d, Name: "generic.knockbackResistance"}, {Base: 0.25d, Name: "generic.movementSpeed"}, {Base: 0.0d, Name: "generic.armor"}, {Base: 0.0d, Name: "generic.armorToughness"}, {Base: 16.0d, Name: "generic.followRange"}, {Base: 0.0d, Name: "generic.attackKnockback"}, {Base: 15.0d, Name: "generic.attackDamage"}], Invulnerable: 0b, FallFlying: 0b, PortalCooldown: 0, AbsorptionAmount: 0.0f, FallDistance: 0.0f, DeathTime: 0s, WorldUUIDMost: 6605677085970091413L, HandDropChances: [0.085f, 0.085f], Bukkit.Aware: 1b, PersistenceRequired: 1b, Spigot.ticksLived: 295978, Motion: [0.0023068071243408303d, -0.005d, -4.5885248403321747E-4d], Health: 100.0f, Bukkit.updateLevel: 2, PlayerCreated: 1b, LeftHanded: 0b, Paper.SpawnReason: "BUILD_IRONGOLEM", Air: 300s, OnGround: 1b, Rotation: [258.7514f, -40.0f], HandItems: [{}, {}], ArmorDropChances: [0.085f, 0.085f, 0.085f, 0.085f], Fire: -1s, ArmorItems: [{}, {}, {}, {}], CanPickUpLoot: 0b, HurtTime: 0s, WorldUUIDLeast: -6398962707638109974L, Paper.Origin: [-5769.5d, 72.05d, -3620.5d]}

## F3 Debug Screenshot

![2020-05-12_15 24 48](https://user-images.githubusercontent.com/65251072/81736567-c7ec1600-9464-11ea-8cdc-2aa3237a3782.png)

Minecraft's built-in debug screen provides *a lot* of useful information, and should be included even if the issue is not something that can be captured in a still image.

To open this menu, simply press `F3` on your keyboard while in-game. Please ensure the text is easily readable. Depending on the size/resolution of your monitor, you may have to adjust your GUI scale for all text to be completely visible on-screen.

## Additional Information
i've been updating my servers resource pack with general textures but this is my first time attempting to modify an entity with optifine adding unique visual features.

**Comment by DvojiteV** [comment]
I think there is some problem with CEM since I have trouble with wolf model that worked fine on 1.14 but some of mob models are working such as pig or cow also someone else reported this some days ago. :)

**Comment by diotodd** [comment]
Still have the same problem on Iron Golem in 1.16.3

**Comment by ewanhowell5195** [comment]
cant reproduce. can you check your output log for errors
