### ISSUE TITLE
Mark blocks as emmisive

### ISSUE THREAD

**Issue by Blockstate** [sp614x/optifine#393]
Basically this would be a way to mark blocks to act as glowstone causing them to emit light. It would be done in the .properties file something like this..

LightSource= true
LightPower= 1-10 or 100 being max strength

It would basically tell the block to act as a light source then emit at the given power. The main purpose would be to have it read an _e texture which would basically act as a mask to the texture designating the emissions color. It could ignore transparency so that it will only emit out of where there is a texture in the _e image file. If this were to be implemented it would be very useful to have for texture developers such as myself.

**Comment by sp614x** [comment]
Which light should be affected: world light, dynamic light, shaders?
The world light should not be changed by a resource pack, because then the light levels for all chunks will have to be recalculated, which is a VERY expensive operation. There is also the problem with updating the chunks which are currently not loaded. but their lighting is already calculated.
What exactly is the "_e" texture?

**Comment by dotModded** [comment]
An _e texture is not needed especially if it is a mask, it can be put in the specular texture. However the update to the lightmao would be cool.

**Comment by sp614x** [comment]
Which light should be affected: world light, dynamic light, shaders?

**Comment by Opptitronica** [comment]
Well considering the world light calculations are taxing then I would say dynamic and shaders both. As long as the block affects the area around it like glowstone, torches, etc. do. If dotModded has anymore input I'd take his knowledge over mine since Im not a shader dev. But for simplicity I would like to have the emmisive texture be separate from _s.

**Comment by dotModded** [comment]
Well you could pack emmisivity in something like the alternate texture I requested a while ago, that's where I was going to put it anyways. It would be essentially the same thing.

**Comment by Opptitronica** [comment]
But what if people want the emmisive blocks and don't want to use a shader specifically coded to read them?

**Comment by zombye** [comment]
For the emission texture, here's my input:

It should stay in its own texture. Better for artists as it's pretty much just another color texture to use, and that way it won't require shaders that were coded specifically to read it. 
Format should be RGB, as an alpha channel is not needed.
Rendering with it would be something like this (simplified, obviously): `(texture * lightmap) + texture_e`

**Comment by dotModded** [comment]
It should have an alpha in case someone wants to use it for myself

**Comment by dotModded** [comment]
I worded that poorly, it should have an alpha in case someone wants to use it for something other than just emmisive color. And this texture should always be loaded, even if the texture does not cause blocks to update lightmaps

**Comment by Opptitronica** [comment]
I think it should have an alpha channel to determine what parts of the block are emmisive. If you don't do that I can see this having problems with shaders. Since your basically saying the whole block is emmisive, the whole block will glow in shaders. The alpha channel would tell shaders to only glow at certain spots and not the whole block; even when the whole block is technically emitting light.

**Comment by dotModded** [comment]
The RGB can be black, if black not emmisive if 0.5 half emmisive

**Comment by Opptitronica** [comment]
Perfect!

**Comment by mindforger** [comment]
this could be relevant to resourcepack-maker to compensate for the missing native glow effects of Applied Energistics :)

**Comment by sp614x** [comment]
The "glow" effect of Applied Energistics is just the texture ignoring the lightmap and rendering at 100% brightness: http://i.imgur.com/fIo1acE.png
Is this what we are talking about?

**Comment by sp614x** [comment]
Relevant AE discussion:
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2489/#issuecomment-255772498

**Comment by Opptitronica** [comment]
No I want it to actually affect the area around the block so again it acts as a lightsource.

**Comment by mindforger** [comment]
ok my fault then :)

**Comment by sp614x** [comment]
To light the other blocks like this: http://i.imgur.com/Dmv8zIx.png, the world light has to be changed. 
This is very expensive and can not be done by a resource pack.

**Comment by Opptitronica** [comment]
What about if it were done in shaders. So for people who don't use shaders it looks like the AE block but for people who have shaders, it tells the shaders to make the block act as an emmisive which in turn affects the environment the same way they do with vanilla lamps. Is this also very expensive?

**Comment by sp614x** [comment]
The shaders can simulate one or two fixed light sources (handheld item, etc), but having a potentially unlimited number of light sources is too much for them.
This is something that Dynamic Lights could do, but it may have performance problems with too many light sources. There is an open issue for adding a configuration to Dynamic Lights: https://github.com/sp614x/optifine/issues/182, but it should only work with items, not blocks.

**Comment by Opptitronica** [comment]
Well then Ill settle for the _e texture to ignore the lightmap and render at 100% brightness

**Comment by sp614x** [comment]
Experimenting with "_e" textures. The straightforward solution to render the block twice (once normal, once emmisive) does not work as most solid blocks are rendered without alpha (layer SOLID), so the emmisive texture can not be transparent.
A more complex solution would be to use the CTM overlay mechanic, something like "method=overlay_fixed" which uses 1 fixed texture.

**Comment by Opptitronica** [comment]
I'd prefer the method dotModded suggested, using the black level as the emmisive amount. "The RGB can be black, if black not emmisive if 0.5 half emmisive" and if 0 not emmisive. Let me know if this will work.

**Comment by Opptitronica** [comment]
How about this,  using the black/white level to determine the emmisive amount. Fully black will emit no "light", fully white will emit 100% "light", and 50% black will result in half the amount of emisiveness. It will still use rgb to determine the emission color.  Hopefully I explained that will enough.

**Comment by sp614x** [comment]
This looks like a normal alpha blending ignoring light levels (fullbright)
- the base is dark (night time)
- the 100% pixels are bright 
- the 50% pixels are half-bright
- the 0% pixels are dark (base texture)
Of course this also blends the RGB colors, but the resource pack can fix it.

**Comment by sp614x** [comment]
Separating the emissive alpha and using it to control the brightness of the base texture can only be done in shaders. for this the "_e" texture will have to be loaded like the normal and specular textures.

**Comment by Opptitronica** [comment]
As long as its easy to use, can be loaded with or without shaders, doesn't require CTM mechanics and can use colors I'm fine with it. If theres no way to specify the brightness of the "emission" than leave it at 100%. Im not to sure what you meant in this message--

This looks like a normal alpha blending when using maximum light level (fullbright).

the base is dark (night time)
the 100% emissive pixels are bright
the 50% emissive pixels are half-bright
the 0% emissive pixels are dark (base texture)
Of course this also blends the RGB colors, but the resource pack can fix it.

I think however this is a method that will determine the emission brightness??

**Comment by sp614x** [comment]
Experimenting with emmissive textures: https://gfycat.com/UnfortunatePinkIndianpalmsquirrel

**Comment by sp614x** [comment]
Alpha blending: https://streamable.com/nt4fv

**Comment by Blockstate** [comment]
Looking very nice!

**Comment by sp614x** [comment]
The current plan is to add a property `suffix.emissive=_e` to `color.properties`.
When the suffix is enabled each block texture would get an emissie twin with the same name + suffix.
For example `bedrock.png` and `bedrock_e.png`. The emissive texture will be rendered as CUTOUT on top of the base texture and will always have brightness 100%. This should also work for CTM replacement textures.

**Comment by sp614x** [comment]
![image](https://user-images.githubusercontent.com/16635441/32739834-51c5bad0-c8a1-11e7-80eb-8197c19664d2.png)
![image](https://user-images.githubusercontent.com/16635441/32739935-a1b42bb2-c8a1-11e7-93d6-6d7c416ec839.png)

**Comment by Blockstate** [comment]
Looks good, so it's been a while this will be shader side like normals and specular or no?

**Comment by sp614x** [comment]
Currently it is a cutout overlay, shaders not needed. I am looking for a way to pass it to the shaders so thay can handle it as a glowing texture.

**Comment by sp614x** [comment]
Looks like the shaders dont need the emissive flag, the sky/torch brightness is enough for the bloom effect.

**Comment by sp614x** [comment]
Currently the emissive overlays are rendered as CUTOUT_MIPPED, only translucent textures get their overlay as TRANSLUCENT.

**Comment by sp614x** [comment]
Does it make sense to allow overlays to explicitely select a layer?
Like:
*_e.png -> automatic (cutout_mipped or trnslucent)
*_ec.png -> cutout
*_em.png -> cutout_mipped
*_et.png -> translucent
or with custom properties?

**Comment by Blockstate** [comment]
I like that, it would make less work for resourcepack artists so they don't have to have a bunch of property files laying around for it, overall a cleaner approach.

**Comment by Blockstate** [comment]
Nevermind, doing it in the properties file would be better :p

**Comment by sp614x** [comment]
updated preview C7 for 1.12.2 
 - extended Custom Colors with support for emissive texture overlays

```
###############################################################################
# Emissive textures
###############################################################################
# It is possible to add overlays to block textures which are always rendered 
# with full brightness, simulating light emitting parts of the textures.
# The emissive overlays have the same name as the base texture + custom suffix.
# For example:
#   bedrock.png   - base texture
#   bedrock_e.png - emissive overlay
# The emissive overlays are rendered in the same block layer as the base texture,
# except overlays for textures from layer SOLID, which are rendered as CUTOUT_MIPPED.
suffix.emissive=_e
```
Custom Colors  may not be the best place for emissive, but there it is now

**Comment by sp614x** [comment]
Moved configuration to emissive.properties:
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/emissive.properties
