### ISSUE TITLE
non funziona il cape

### ISSUE THREAD

**Issue by LowerArtic** [sp614x/optifine#3934]
Io ho comprato il cape un paio di anni fa, ad un certo punto apro la versione di MC Optifine1.7.10 e non vedo più il cape e neanche quelli dei altri.
potete darmi una mano ho darmi una risposta per il mio problema.
 Name: LowerArtic
email: ironrig200@gmail.com

**Comment by sp614x** [comment]
Please use english: https://translate.google.com/
The cape for LowerArtic is already active.
