### ISSUE TITLE
[1.12.2] Shader looks strange

### ISSUE THREAD

**Issue by yunomic** [sp614x/optifine#3937]
[Forge version]14.23.5.2854
[Optifine version]Optifine_1.12.2_HD_U_F5
[Shader]SEUS-Renewed-v1.0.1
No other installed mods

↓This is the world which is applied SEUS shader
![2020-05-14_04 41 57](https://user-images.githubusercontent.com/65309248/81858988-96c43080-959f-11ea-9ad2-bd687bfb55bb.png)

↓This is the log when I applied SEUS shader
[shaderlog.txt](https://github.com/sp614x/optifine/files/4624451/shaderlog.txt)

In the log,there are many "WARNING" words but I cant find the way to fix them.
Please help

**Comment by NiemandTV** [comment]
The warnings can be safely ignored and are 100% caused by SEUS Renewed, not by OptiFine. Some of them exist due to bad code/laziness (e.g. not removing old keys from the shader settings), some because Sonic Ether uses features which are deprecated in the used version of GLSL.

**Comment by yunomic** [comment]
Thanks telling that.
Now I understood SEUS shader is not an issue.
But why my shader looks strange?There is no shadow on blocks.

SEUS-Renewed-v1.0.1
![2020-05-14_17 12 23](https://user-images.githubusercontent.com/65309248/81910202-9743e200-9606-11ea-8a92-5fd3867f7ef2.png)
Flank of blocks look like painted.
With F3
![2020-05-14_17 17 57](https://user-images.githubusercontent.com/65309248/81915764-f9ecac00-960d-11ea-9c75-28aa5d0a3167.png)

But maybe not all of shaderpacks arent working
BSL_v7.1.04.1.1
![2020-05-14_17 12 36](https://user-images.githubusercontent.com/65309248/81912991-51891880-960a-11ea-9c8d-9068ec00cafb.png)
I think no irregular points are there

There was someone encounted a similar problem
https://github.com/sp614x/optifine/issues/2788#issue-481924941
He solved by setting old lighting to default and smooth lighting to 100%
My setting is same from that,but nothing changed

**Comment by NiemandTV** [comment]
There are shadows. I think you mean ambient occlusion/AO. Enable SSAO in the shader options of SEUS Renewed. Try it without other mods as they can cause bugs/issues and make sure that old lighting is set to default (on the right side in the menu where you can select shaderpacks). If nothing works, try deleting `optionsof.txt` in your `.minecraft` folder to reset all settings related to OptiFine.

**Comment by yunomic** [comment]
SSAO enabled
![2020-05-14_19 00 18](https://user-images.githubusercontent.com/65309248/81924093-97011200-9619-11ea-8ad5-51e3d1844e91.png)
only optifine is in mods folder and this is mod list
![2020-05-14_19 10 00](https://user-images.githubusercontent.com/65309248/81924253-d891bd00-9619-11ea-9910-24b4fc2f39a3.png)
old lighting is setted to default
![2020-05-14_19 00 57](https://user-images.githubusercontent.com/65309248/81924372-0119b700-961a-11ea-951d-b352430a54a1.png)
But nothing changed and deleted optionsof.txt in my .minecraft
And this is the result
![2020-05-14_19 13 07](https://user-images.githubusercontent.com/65309248/81925401-7043db00-961b-11ea-9d57-a55e0023fd88.png)
Is shader working?

**Comment by realjackasterisk** [comment]
This is not an OptiFine bug. This is how the shader pack was made.
