### ISSUE TITLE
(1.12.2) The game barely runs

### ISSUE THREAD

**Issue by DatCoolBoi** [sp614x/optifine#3938]
ok so when I launch up optifine or put it in to other versions of Minecraft It takes like a minute and a half to move or look around,etc. so WHAT DO I DO?

**Comment by GreenAndEievui** [comment]
You should probably give more information if you want help. Also, this is for bugs, not help.

**Comment by MicherGit** [comment]
you have way too much crap open, close everything and try again. I see it has been 4 days is it better now?

**Comment by sp614x** [comment]
May be caused by many factors:
- when using a resource pack OptiFine would recognize much more RP features than vanilla
- the game may have too little memory assigned and the GC struggles
- the game may have too much memory assigned and the OS has to swap memory to disk
