### ISSUE TITLE
[1.15.2] ItemPhysic compatibility

### ISSUE THREAD

**Issue by CreativeMD** [sp614x/optifine#3939]
Hey there,
I'm the author of ItemPhysic. A small mod which enhance the EntityItem rendering (remove the hover effect and makes them lay on the ground). Unfortunately Optifine "overwrites" this effect entirely (in 1.15.2). This has never been an issue in prior versions of minecraft. 

How does it work?
ItemPhysic adds a method call to `net.minecraft.client.renderer.entity.ItemRenderer.render` ([source](https://github.com/CreativeMD/ItemPhysic/blob/1.15/src/main/resources/META-INF/itemtransformer.js#L12)). The method renders the item, with a few exceptions and eventually returns a boolean whether the item was rendered or not. If not the render method will continue and render the items the vanilla way.

Issue with Optifine
I suspect the `dropped items` option interferes with the rendering. I can't look at the source code or the patched minecraft classes, so I don't know if I can fix it from my end.

If there is anything I can do from my mind let me know!

In Regards
CreativeMD

**Comment by yezhiyi9670** [comment]
Optiforge seems to fix this issue (but it's just a workaround).

**Comment by yezhiyi9670** [comment]
Related to cpw/modlauncher#37

**Comment by sp614x** [comment]
You can extract the OptiFine mod from the JAR file (double click -> extract -> save).
The extracted MOD file has the patched SRG classes in the "srg" folder.

**Comment by CreativeMD** [comment]
@sp614x yes and that is a very good change! But still I would need the patched minecraft files (maybe there is an easy way to get them?). 

Anyway, looks like the issue is the class transformer as a couple of people have already stated.

**Comment by CreativeMD** [comment]
Fixed in the newest preview version for 1.16
