### ISSUE TITLE
Mouse sensitivity problems

### ISSUE THREAD

**Issue by AdrianGut21** [sp614x/optifine#394]
Since the first version of Optifine 1.11 (OptiFine 1.11 HD U B1) I have noticed that the sensitivity of the mouse is unstable because sometimes it moves normal and suddenly it moves extremely fast (I hope and it is explaining). I thought it was my mouse problem and I change it but it stays the same; I tried to play with a version of vanilla and there is no such problem. I would like to receive a solution in the next versions.

First of all, thank you

**Comment by sp614x** [comment]
Which is the last working version?

**Comment by AdrianGut21** [comment]
The last version where the sensitivity works correctly is "
OptiFine 1.10.2 HD U D4 "

In the versions in which it fails are "OptiFine 1.11 HD U B1 - B2 & B3"

**Comment by tenten8401** [comment]
This appears to be an issue in 1.10.2 (all versions, including D4) for me. If possible, could you re-release a fixed version for 1.10.2?

A temporary fix for the problem is reducing the priority in task manager to "below normal", but that's annoying and has to be done every restart.

If you'd like to use the pack I'm testing on, you can use IndustrialBox 0.3-BETA on ATLauncher (I'll have to enroll you as a tester)

**Comment by tenten8401** [comment]
This is what it's like trying to kill a pig when the mouse is randomly spazzing. It gets a lot worse at times, to the point of doing 360s when moving the mouse a tiny bit.

https://youtu.be/ZqtijwApNNg

**Comment by sp614x** [comment]
Is this happening without other mod installed?
Also without Forge on a standalone OptiFine profile?

**Comment by tenten8401** [comment]
I'll give it a shot when I get home. From my experience its just the sheer
amount of mods

**Comment by AdrianGut21** [comment]
I just had Optifine installed, the only solution was to reset my PC.

**Comment by sp614x** [comment]
How do you reset the PC? Do you mean restart?

**Comment by AdrianGut21** [comment]
Yes, I had to reinstall Windows because I did not find any solution.

**Comment by tenten8401** [comment]
Something tells me that wasn't the problem

**Comment by tenten8401** [comment]
@sp614x So I did some testing, and it only happens with a ton of mods installed. Doesn't matter which ones, but it just seems to have issues. On a semi-unrelated note, would there be a way to put mouse movement on a separate thread? That probably sounds very stupid but in my mind, it might fix the problem.

**Comment by sp614x** [comment]
OptiFine does not change the mouse handling in any way. It also does not change anything related to the mouse. This is probably a side effect of some other change.

**Comment by tenten8401** [comment]
Updated like 20 mods and the problem magically vanishes. I don't know what was up with that.

**Comment by sp614x** [comment]
Most probably a conflict with some of the mods.

**Comment by sp614x** [comment]
@AdrianGut21 is OptiFine 1.10.2 HD U D6 working correctly?

**Comment by AdrianGut21** [comment]
Yes, all working in 1.10.x
