### ISSUE TITLE
Random Entity NBT Check

### ISSUE THREAD

**Issue by SkaliberWasTaken** [sp614x/optifine#3940]
Something that works along the lines of:

skins.1=2
nbt.1={PersistenceRequired:1}

This feature would obviously allow for crazy potential for dynamic mob textures, such as:
Entities that have just exited a nether portal
Entities that have been made invulnerable
Entities that have just taken damage (hurt time)
Entities that are drowning (using {Air:X}}
Countless other entity specific NBT tags

**Comment by CreeperMagnet** [comment]
This would be incredibly useful for datapack development. I know I'd use it for sure.

**Comment by ChaosDogG** [comment]
i second that, id love to be able to make random textures work on an NBT level. At the very least it could work with checking for specific tags given to the entity, granted this wouldnt work with tile entities such as chests

**Comment by SkaliberWasTaken** [comment]
NBT has recently been addressed I believe, and it's been confirmed that my recommendation of how to read the NBT would not work. Will reopen this issue if anything related doesn't get added.
