### ISSUE TITLE
Sides of glass blocks don't render properly 

### ISSUE THREAD

**Issue by bradwiggo** [sp614x/optifine#3946]
## Description of Issue
The sides of glass blocks do not render when not right next to the player (difficult to describe so I attached some screenshots) 
![2020-05-15_16 49 26](https://user-images.githubusercontent.com/61841323/82070014-0f281000-96cc-11ea-831f-aafd3b9b8d4d.png)

## Steps to Reproduce
Place a pathway of glass and look at the edges ahead of you when running forward and back on it

## OptiFine Version
Latest (preview 16)

## Installation Method
Used the regular installation method of double clicking on jar file 

## Fabric/Forge Version
The first screenshot attached is using optifabric (and also an older version of optifine (13)) as that allows me to use tweakeroo to turn the gamma up so the effect is easier to see, and I use a 32x texture pack which seems to exaggerate the problem. The same effect happens without optifabric and with the latest version however, as can be seen in the second screenshot. 

## OptiFabric Version
8 but as mentioned also happens without this. 
## Other Installed Mods
None on the second screenshot 

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
No
![2020-05-15_16 33 59](https://user-images.githubusercontent.com/61841323/82069929-ee5fba80-96cb-11ea-82c5-b5c32320f24a.png)
![2020-05-15_16 43 58](https://user-images.githubusercontent.com/61841323/82069936-f1f34180-96cb-11ea-9536-09810116fedf.png)

**Comment by sp614x** [comment]
This is a side effect of the mipmaps. Textures which are far from the player or vieweed at steep angles use textures with lower resolution to reduce aliasing. Textures which have too little opaque pixels may start to disappear when scaled to 4x4 or 2x2 pixels.
You can fix it by decreasing the mipmap level or disabling mipmaps.
