### ISSUE TITLE
[Bug] Chest CET (Custom Entity Textures) does not work

### ISSUE THREAD

**Issue by Pumpking0108** [sp614x/optifine#3948]
The CEM of chests don't work you can rename the chest that the property file list but It won't change

## OptiFine Version
1.15.2 pre-17  1.15.2 pre-18

## Installation Method
Jar download

**Comment by sp614x** [comment]
Fixed, coming in pre19.
The CEM for chests in 1.15 is changed:
- changed "chest_large": lid_left, base_left, knob_left, lid_right, base_right, knob_right
- added "trapped_chest" and "trapped_chest_large", similar to normal chests
