### ISSUE TITLE
Animated normal maps, POM, and specular

### ISSUE THREAD

**Issue by Opptitronica** [sp614x/optifine#395]
Not sure if it's possible but I'd like to see POM, normal maps and specular be able to be affected by animation. I've animated the textures but the maps show no animation other than the base texture.

**Comment by Opptitronica** [comment]
Also same thing goes for the emmisive texture I talked about in my other request.

**Comment by sp614x** [comment]
Updated preview B6 for 1.11.2.
Added support for animated normal and specular maps.

**Comment by Opptitronica** [comment]
Works with POM also?

**Comment by sp614x** [comment]
POM uses the normal maps so is should also work.
