### ISSUE TITLE
Banners flash white with SEUS shaders

### ISSUE THREAD

**Issue by itsvinniethepooh** [sp614x/optifine#3954]
## Description of Issue
banners flash white hundreds of times a second as if there is a double texture going on

## OptiFine Version
1.15.2 G1 pre17

## Installation Method
Installed from link on twitter

## F3 Debug Screenshot
Minecraft's built-in debug screen provides *a lot* of useful information, and should be included even if the issue is not something that can be captured in a still image.

To open this menu, simply press `F3` on your keyboard while in-game. Please ensure the text is easily readable. Depending on the size/resolution of your monitor, you may have to adjust your GUI scale for all text to be completely visible on-screen.

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
no it does not

![2020-05-15_21 15 03](https://user-images.githubusercontent.com/65431034/82106793-4826ab80-96f1-11ea-9f0d-ddb16bca41ad.png)

![2020-05-15_21 16 14](https://user-images.githubusercontent.com/65431034/82106798-5379d700-96f1-11ea-893e-12d6d5ff810b.png)

## Additional Information
Here goes any final remarks and everything else that might not fit in the previous sections.

**Comment by sp614x** [comment]
Fixed in pre18
