### ISSUE TITLE
[1.15.2 pre17 Bug] Smart Animation is broken

### ISSUE THREAD

**Issue by NaiNonTH** [sp614x/optifine#3955]
## Description of Issue
Instead of animate the textures which visible on the screen, It just disables the texture's animation. Only reconnect to the world can solve the problem. But when you disable it and enable it again, It won't work again.

## Steps to Reproduce
1. Enabled the Smart Animation option.
2. You'll see that the texture's animation won't work.
**P.S. But if you still enable the Smart Animation option before joining the world, Disable and Enable it again will cause this issue.

## OptiFine Version
1.15.2 HD Ultra G1 pre17

## Installation Method
Optifine Standalone installer.

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
  Ans: No. Because the Smart animation option only available in Optifine.

**Comment by NaiNonTH** [comment]
The Video with this issue

----> https://imgur.com/jIJCpL5

**Comment by sp614x** [comment]
Should be working in latest preview.
