### ISSUE TITLE
[Optifine 1.15.2 pre17 Linux] Server connection fails due to incorrect version reported

### ISSUE THREAD

**Issue by jsmurray2** [sp614x/optifine#3959]
## Description of Issue
When logging into a 1.15.2 server connection fails because of "outdated server". I am server owner, server is latest version on 1.15.2 (Running Paper-284) Running Minecraft on PopOS using bundled java runtime. Server connects just fine using vanilla minecraft. No other mods in use.

## Steps to Reproduce
1. Install Optifine using installer
2. Try to connect to server
## OptiFine Version
1.15.2 pre17

## Installation Method
Installed using installer

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
No
- Does this happen in OptiFine standalone?
Yes

**Comment by jsmurray2** [comment]
I have done some more testing, this bug is present in java 11 and 14, switching to java 8 fixes issue. Open vs Oracle JDK makes no difference. If anyone has any ideas for a fix I would love to get java 11 working for the performance benefits.

**Comment by sp614x** [comment]
Fixed in 1.16.2 pre4
