### ISSUE TITLE
[CEM 1.15.2 G1 pre17] Boat modeling does not work

### ISSUE THREAD

**Issue by omkhamsa** [sp614x/optifine#3960]
## Description of Issue
I'm using the third party program "Block Bench" to create entity models. I've made a model for an armor stand and it worked, however when I tried making a model for a boat (as a car) it did not work and the model did not load (the texture did though)

## Steps to Reproduce
1. Download and install the resourcepack in attachments
2. Try opening a world and placing a boat

## OptiFine Version
1.15.2-Optifine_HD_U_G1_pre17

## Installation Method
standalone installer

## Prior Testing

- Does this happen in Vanilla without OptiFine? Of course. Vanilla does not have cem.

## Additional Information
I've spent hours trying to fix this. I tried removing "bottom_no_water", I tried looking up examples that are already working, couldn't find any.
[The pack.zip](https://github.com/sp614x/optifine/files/4639337/The.pack.zip)

**Comment by sp614x** [comment]
Fixed, coming in pre19.
