### ISSUE TITLE
[CEM] Skeleton and Zombie Horse CEM crash the game! (pre17)

### ISSUE THREAD

**Issue by ewanhowell5195** [sp614x/optifine#3965]
## Description of Issue
Use a CEM model of a skeleton horse or a zombie horse, and once spawned in, the game will crash. See video here: [https://imgur.com/a/KlrDiBO](https://imgur.com/a/KlrDiBO) (I use shaders in the clip but it does it with and without)

## Steps to Reproduce
Use any correctly formatted CEM model for them (the doc is wrong and lists parts that don't exist, causing them not to load) and summon/spawn them in game with the resource pack enabled. I have attached some models for testing.
[skeleton_zombie_horse.zip](https://github.com/sp614x/optifine/files/4644628/skeleton_zombie_horse.zip)

## OptiFine Version
1.15.2 HD U G1 pre17

## Installation Method
Included standalone installer

## Log Files/Crash Reports
https://pastebin.com/7hZiytnt

## F3 Debug Screenshot
![2020-05-18_15 13 08](https://user-images.githubusercontent.com/48070995/82223247-51df2780-991a-11ea-8338-ed62ae805e4a.png)

**Comment by sp614x** [comment]
Fixed, coming in pre18.
