### ISSUE TITLE
[Suggestion] Is it possible to optimize the render of entities by using openGL Instancing?

### ISSUE THREAD

**Issue by Cmyna** [sp614x/optifine#3966]
## Using openGL instancing to improve performance?
Minecraft has terrible performance of render the entites. The fps will seriously decrease if there are thousands of entities in the view. I think maybe one of the reason to this issue is calling to much glDrawArray() during the process. It seems that in vanilla minecraft, one glDrawArray() will be called if it render only one part of an entity, which means if there are thousands of entites, at least the glDrawArray() will be called thousands of times!
I am thinking is it possible to use openGL instancing in minecraft to improve performance? Not long ago I just learned about openGL's instancing technology, which can greatly reduce the number of sending vertices to GPU. Maybe for a kind of entities, the draw calls can be reduce to once by instancing?

I am not sure if optifine mod have done some of optimization in this part, but I haven't saw anyone post the same suggestion in the Issue.

**Comment by sp614x** [comment]
Instancing is only useful with custom shaders.
Minecraft currently doesn't use shaders and changing the render engine to use shaders is a big and complex task.
