### ISSUE TITLE
[Shaders] Block outline is white with shaders

### ISSUE THREAD

**Issue by Spherey** [sp614x/optifine#3967]
## Description of Issue
If you hover your crosshair over any block, the outline of the block appears white instead of black

## Steps to Reproduce
1. Go into a game with a shader (I use SEUS v11.0)
2. Look at a block with your crosshair, the outline should be white instead of black

## OptiFine Version
1.15.2 pre16

## Installation Method
Go to Tlauncher, click "Optifine" or "ForgeOptifine" in the 1.15.2 category, Launch game

## Other Installed Mods
Mr. Crayfish Furniture
Immersive Portals
Mixinbootstrap
Tlauncher Skins
(the white outline bug also works without mods)

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
   - No, there are no shaders in Vanilla

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   - Only OptiFine and ForgeOptifine
- Does this happen even without any mods at all?
   - Yes
- Does this happen in OptiFine standalone?
   - Yes
- Does this happen in Vanilla without OptiFine?
   - No, there are no shaders in Vanilla

## Additional Information
N/A

**Comment by realjackasterisk** [comment]
Shaders have the ability to change the block selection box. This is not a bug.

https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.txt#L71
