### ISSUE TITLE
[CRASH] OptiFine with Forge on Minecraft 1.14.4 always crash on macOS

### ISSUE THREAD

**Issue by FellFromTheSky** [sp614x/optifine#3968]
Read the crash report [here on PASTEBIN](https://pastebin.com/ZDn0LPHX).
The game crash on macOS but also do me the same exact thing on WIndows 10.
The game doesn't crash with vanilla Minecraft OptiFine profile.
My hardware :
```
MOTHERBOARD : 
Gigabyte GA-Z77-HD3
RAM : 
32 Gb DDR4 SDRAM
PSU : 
Corsair CX650M
CPU : 
Intel Octa Core i7 on LGA1155 SOCKET
GPU : 
GTX 760 2 Gb (as fast than a GeForce 10 series)
```
```
MOTHERBOARD : 
Gigabyte GA-H97M-HD3
RAM :
20 Gb DDR3 SDRAM
PSU : Corsair CX600
CPU : Quad Core Xeon on LGA1150 SOCKET
GPU : ZOTAC GT1030
```

My software :
```
Operating Sytem : 
Windows 10 or macOS Catalina 10.15.4 
For macOS Catalina see the OpenCore tutorials here, https://dortania.github.io
Java : 
Oracle JDK 1.8.0_251 64 bit
Minecraft Launcher Version : 
Legacy Java Launcher 1.6.93
Minecraft Version : 
1.14.4
Forge Version : 
28.2.16
OptiFine Version : 
OptiFine HD U F5
```

Also, I saw in the changelog that you made [OptiFine HD U F6 for 1.14.4](https://optifine.net/changelog?f=preview_OptiFine_1.15.2_HD_U_G1_pre17.jar), but there's no download link for it at https://optifine.net/downloads

**Comment by sp614x** [comment]
F6 for 1.14.4 is the next development version, it is not released yet.
The crash happens outside of OptiFine when reloading vanilla resources (lava and water textures).

**Comment by FellFromTheSky** [comment]
Yes, [this is the link](https://gist.github.com/FellFromTheSky/b3af526bbdab4b9f1d31eade8add2abd) of the logs and crash reports.
As I said it also happens on Windows too.
By the way, I also have to old computers at home, both on old AMD Athlon x64 3000+ and 3500+ CPUs. Those two computers have good GPU even if they're old from 2005 era.
However, even with Optifine, Minecraft wont start with 1.13.# to 1.15.2.
It will freeze at 50 to 75 % loading screen.
Those both computer have only DDR1 SDRAM.

**Comment by FellFromTheSky** [comment]
@sp614x 
Sorry for the ping. By the way Optifine is working well on vanilla 1.14.4 on macOS.
So it's just an issue with Forge I think.

**Comment by ZekerZhayard** [comment]
optifine will crash with forge-1.14.4-28.2.2 or higher version,  
there is a mod fixing it: https://www.curseforge.com/minecraft/mc-mods/optiforge

**Comment by FellFromTheSky** [comment]
Ok thanks.

**Comment by FellFromTheSky** [comment]
@sp614x
It's bad to use OptiForge, since it's editing vanilla OptiFine code.
It's also bad to reposting Mojang source code in a mod, so instead, please use Partial Modification Loader or ASM.
Thanks.

**Comment by asbyth** [comment]
> @sp614x
> It's bad to use OptiForge, since it's editing vanilla OptiFine code. It's also bad to reposting Mojang source code in a mod, so instead, please use Partial Modification Loader or ASM.
> Thanks.

sp614x is not the developer of optiforge, @ZekerZhayard is

**Comment by FellFromTheSky** [comment]
OptiFine is reposting Minecraft code since it edits it, not OptiForge.
