### ISSUE TITLE
centerDepthSmooth incompatible with gaux4

### ISSUE THREAD

**Issue by Strum355** [sp614x/optifine#397]
You told Sergeant Sarcasm to make an issue, so here it is. centerDepthSmooth doesnt work when gaux4 is being used. Its a bug thats been around for a long time and needs to be fixed. Sgt Sarcasm can tell you more.

**Comment by SergeantSarcasm** [comment]
Basically even the presence of gaux4 in any file, it doesn't have to be the file centerDepthSmooth is used or defined in or anything like that, gaux4 doesn't even have to be written to or used, it will cause centerDepthSmooth to be locked at the depth read at the point of initialization. Even if you re-initialize shaders it will stay at this depth, the only way to reset it to another depth will be to completely restart the game. For developers like me who center their pack around the use of lens effects, it completely removes the ability to use an entire sampler and I really don't think we should need to encode or pack our color and avoid using a whole sampler just to use a nice and convenient feature.

**Comment by sp614x** [comment]
This looks like a simple copy-paste error, should be trivial to fix:

    ...
    else if (usedColorBuffers < 8 && line.matches("uniform [ _a-zA-Z0-9]+ gaux4;.*"))
    {
      usedColorBuffers = 8;
    }
    ...
    else if (usedColorBuffers < 8 && line.matches("uniform [ _a-zA-Z0-9]+ colortex7;.*"))
    {
      usedColorBuffers = 8;
    }
    else if (usedColorBuffers < 8 && line.matches("uniform [ _a-zA-Z0-9]+ centerDepthSmooth;.*"))
    {
      centerDepthSmoothEnabled = true;
    }

**Comment by Strum355** [comment]
Sicc, if that can be fixed ASAP that would be perfect. Cheers man

**Comment by Strum355** [comment]
is the first part the new code and the second part the old code?

**Comment by sp614x** [comment]
Both are old code, the line with "centerDepthSmooth" should not have a check for usedColorBuffers. The smoothing of center depth has nothing to do with used color buffers.

**Comment by sp614x** [comment]
Updated preview B4 with a bugfix.
