### ISSUE TITLE
[CEM][1.15.2 pre18] Complete list of all CEM issues currently in OptiFine

### ISSUE THREAD

**Issue by ewanhowell5195** [sp614x/optifine#3971]
## Description of Issue
There might be duplicates from other issues here, but this will be a complete list of all CEM issues in the latest preview. The 1.14.4 screenshots are to show the edited model I used for testing, and the 1.15 one is to show it not loading. This is the pack i used for testing: 
[CEM Test.zip](https://github.com/sp614x/optifine/files/4653744/CEM.Test.zip)

## Cat

 - Cannot model the collar. Follows original model

## Drowned

- Cannot model the outer clothes layer.

## Llama

 - Cannot model the carpets. Follows original model
 
## Slime

 - Missing outer cube bone name from documentation

## Stray

- Cannot model the outer clothes layer.

## Unsupported Entities

These are the Entities that currently do not support CEM:

 - Armor
 - Arrow 
 - Bee
 - Bell
 - Elder Guardian
 - Elytra
 - Trader Llama
 - Trident
 - Wandering Trader

## Banner [MARKED AS FIXED]

1.14.4:
![2020-05-19_20 20 47](https://user-images.githubusercontent.com/48070995/82369138-787e8a80-9a0e-11ea-8026-516074f3da00.png)

1.15.2:
![2020-05-19_20 20 59](https://user-images.githubusercontent.com/48070995/82369148-7d433e80-9a0e-11ea-8efe-09c17fa73bca.png)

Other issues:
 - In 1.14.4, you can't model the `slate` and `stand` bones

## Bed [MARKED AS FIXED]

1.14.4:
![2020-05-19_20 29 19](https://user-images.githubusercontent.com/48070995/82369775-779a2880-9a0f-11ea-94c4-ddd585c0aad6.png)

1.15.2:
![2020-05-19_20 28 38](https://user-images.githubusercontent.com/48070995/82369796-7f59cd00-9a0f-11ea-961f-f2cd83289ab7.png)

## Boat [MARKED AS FIXED]

1.14.4:
![2020-05-19_20 38 14](https://user-images.githubusercontent.com/48070995/82370598-ba103500-9a10-11ea-9e66-586362236b8c.png)

1.15.2:
![2020-05-19_20 38 19](https://user-images.githubusercontent.com/48070995/82370617-bf6d7f80-9a10-11ea-89d9-6802f90c619a.png)

##  Chest [MARKED AS FIXED]

1.14.4:
![2020-05-19_20 43 47](https://user-images.githubusercontent.com/48070995/82371123-900b4280-9a11-11ea-9860-91c897a9d22f.png)

1.15.2:
![2020-05-19_20 44 25](https://user-images.githubusercontent.com/48070995/82371143-96012380-9a11-11ea-9e15-2b143d92aa77.png)

## Chest Large [MARKED AS FIXED]

1.14.4:
![2020-05-19_20 46 18](https://user-images.githubusercontent.com/48070995/82371314-e5475400-9a11-11ea-90d8-f8a56de98b72.png)

1.15.2:
![2020-05-19_20 46 54](https://user-images.githubusercontent.com/48070995/82371331-eaa49e80-9a11-11ea-8eb2-a67915b20dd5.png)

## Dolphin [MARKED AS FIXED]

1.14.4:
![2020-05-19_20 54 59](https://user-images.githubusercontent.com/48070995/82372014-196f4480-9a13-11ea-9332-ff0cd352cd77.png)

1.15.2:
![2020-05-19_20 54 36](https://user-images.githubusercontent.com/48070995/82372021-1d02cb80-9a13-11ea-87f0-6b966e42f52c.png)

Other issues:
 - Incorrect documentation. The `head` bone and the bone for the back of the tail are not listed.

## Donkey [MARKED AS FIXED]

 - No bone for chests listed in the documentation.

## Dragon [MARKED AS FIXED]

 - 1.14.4 is custom normal model, 1.15.2 the model loads but is broken.

1.14.4:
![2020-05-19_21 18 52](https://user-images.githubusercontent.com/48070995/82373995-5a1c8d00-9a16-11ea-8d31-260747d494cd.png)

1.15.2:
![2020-05-19_21 10 44](https://user-images.githubusercontent.com/48070995/82374005-5db01400-9a16-11ea-9343-b0621f41cecc.png)

## End Crystal & End Crystal No Base [MARKED AS FIXED]

1.14.4
- Doesn't revert back after removing resource pack.
- Model is scaled too large in game.

1.14.4 vanilla:
![2020-05-19_21 34 02](https://user-images.githubusercontent.com/48070995/82375430-7e796900-9a18-11ea-8c07-dd63d98be519.png)

1.14.4 with CEM:
![2020-05-19_21 26 26](https://user-images.githubusercontent.com/48070995/82375456-8507e080-9a18-11ea-8d7e-1b88411c8492.png)

1.15.2:

 - Model doesn't load at all

## Ender Chest [MARKED AS FIXED]

1.14.4:
![2020-05-19_21 40 24](https://user-images.githubusercontent.com/48070995/82377579-c8b01980-9a1b-11ea-8748-604044c8475f.png)

1.15.2:
![2020-05-19_21 57 40](https://user-images.githubusercontent.com/48070995/82377592-ccdc3700-9a1b-11ea-87fe-7b9e251a4a67.png)

## Evoker [MARKED AS FIXED]

1.14.4:
![2020-05-19_22 02 04](https://user-images.githubusercontent.com/48070995/82378032-6d325b80-9a1c-11ea-9726-ab87a0eafbd7.png)

1.15.2:
![2020-05-19_22 02 11](https://user-images.githubusercontent.com/48070995/82378046-715e7900-9a1c-11ea-91a2-83aa566520d8.png)

## Ghast [MARKED AS FIXED]

1.14.4:
![2020-05-19_22 06 33](https://user-images.githubusercontent.com/48070995/82378488-18431500-9a1d-11ea-8ae9-4c597eff03f6.png)

1.15.2:
![2020-05-19_22 06 58](https://user-images.githubusercontent.com/48070995/82378499-1b3e0580-9a1d-11ea-80d4-ee4e9875d8c9.png)

## Head Dragon [MARKED AS FIXED]

- Doesn't revert back after removing resource pack.

## Head Humanoid [MARKED AS FIXED]

- Doesn't revert back after removing resource pack.

## Head Skeleton [MARKED AS FIXED]

- Doesn't revert back after removing resource pack.

## Illusioner [MARKED AS FIXED]

 - Missing `hat` bone from documentation

1.14.4:
![2020-05-19_22 36 42](https://user-images.githubusercontent.com/48070995/82381030-6bb76200-9a21-11ea-8714-725bc444e24d.png)

1.15.2:
![2020-05-19_22 37 03](https://user-images.githubusercontent.com/48070995/82381025-6823db00-9a21-11ea-835e-a3c7e78db7ee.png)

## Mule [MARKED AS FIXED]

 - No bone for chests listed in the documentation.

## Phantom [MARKED AS FIXED]

1.14.4:
![2020-05-19_23 00 36](https://user-images.githubusercontent.com/48070995/82382896-b4bce580-9a24-11ea-9bd8-9ae54c4e1d62.png)

1.15.2:
![2020-05-19_23 01 15](https://user-images.githubusercontent.com/48070995/82382907-bab2c680-9a24-11ea-8b07-871f9856f75d.png)

## Pillager [MARKED AS FIXED]

1.14.4:
![2020-05-19_23 04 30](https://user-images.githubusercontent.com/48070995/82383147-29901f80-9a25-11ea-82a5-f73a15bf5b58.png)

1.15.2:
![2020-05-19_23 04 38](https://user-images.githubusercontent.com/48070995/82383163-2dbc3d00-9a25-11ea-8a5d-2c3a95e15287.png)

## Pufferfish [Small] [MARKED AS FIXED]

1.14.4:
![2020-05-19_23 07 46](https://user-images.githubusercontent.com/48070995/82383403-a02d1d00-9a25-11ea-81f5-73e5b5a230bd.png)

1.15.2:
![2020-05-19_23 07 40](https://user-images.githubusercontent.com/48070995/82383420-aae7b200-9a25-11ea-9a28-65a59fefe3cc.png)

## Pufferfish [Medium] [MARKED AS FIXED]

1.14.4:
![2020-05-19_23 10 10](https://user-images.githubusercontent.com/48070995/82383585-0ade5880-9a26-11ea-9ef0-982436d18c0c.png)

1.15.2:
![2020-05-19_23 10 18](https://user-images.githubusercontent.com/48070995/82383594-0e71df80-9a26-11ea-9129-882e863b42d4.png)

## Pufferfish [Big] [MARKED AS FIXED]

1.14.4:
![2020-05-19_23 10 06](https://user-images.githubusercontent.com/48070995/82383598-116cd000-9a26-11ea-89c6-585644dd556c.png)

1.15.2:
![2020-05-19_23 10 15](https://user-images.githubusercontent.com/48070995/82383606-16ca1a80-9a26-11ea-8f83-558045fa93f3.png)

## Salmon [MARKED AS FIXED]

1.14.4:
![2020-05-19_23 16 23](https://user-images.githubusercontent.com/48070995/82383994-d28b4a00-9a26-11ea-878c-b47b78c517a0.png)

1.15.2:
![2020-05-19_23 16 35](https://user-images.githubusercontent.com/48070995/82384000-d4eda400-9a26-11ea-9804-c981d7cbbd98.png)

## Sheep Wool [MARKED AS FIXED]

1.14.4:
![2020-05-19_23 18 47](https://user-images.githubusercontent.com/48070995/82384158-28f88880-9a27-11ea-8caf-a0dc00fe065e.png)

1.15.2:
![2020-05-19_23 18 31](https://user-images.githubusercontent.com/48070995/82384150-2433d480-9a27-11ea-8bc8-476f0619ecff.png)

## Tropical Fish [A&B] [MARKED AS FIXED]

1.14.4:
![2020-05-19_23 33 56](https://user-images.githubusercontent.com/48070995/82385141-4af30a80-9a29-11ea-8f8b-1b7c608a603b.png)

1.15.2:
![2020-05-19_23 34 00](https://user-images.githubusercontent.com/48070995/82385144-4e869180-9a29-11ea-9b03-d1c7aa4862a8.png)

Other issues:
 - In 1.14.4, you can't model the overlay textures
![2020-05-19_23 37 49](https://user-images.githubusercontent.com/48070995/82385348-cc4a9d00-9a29-11ea-8bb6-d3243cff2179.png)

## Vindicator [MARKED AS FIXED]

1.14.4:
![2020-05-19_23 43 03](https://user-images.githubusercontent.com/48070995/82385705-9fe35080-9a2a-11ea-9b6c-d3e4016d90e8.png)

1.15.2:
![2020-05-19_23 42 37](https://user-images.githubusercontent.com/48070995/82385708-a245aa80-9a2a-11ea-9b26-77b86c34be7d.png)

## Wolf [MARKED AS FIXED]

 - 1.14.4 is custom normal model, 1.15.2 the model loads but is broken.

1.14.4:
![2020-05-20_00 00 25](https://user-images.githubusercontent.com/48070995/82386736-108b6c80-9a2d-11ea-968e-877ba581bc82.png)

1.15.2:
![2020-05-20_00 00 09](https://user-images.githubusercontent.com/48070995/82386747-14b78a00-9a2d-11ea-871b-dbfda8e3e110.png)

## Unsupported Entities

 - Head Creeper [ADDED]
 - Head Wither Skeleton [ADDED]
 - Head Zombie [ADDED]

**Comment by sp614x** [comment]
Fixed CEM for boat, dolphin, ghast, illagers, phantom, puffer fish, salmon, sheep, tropical fish, wolf, banner, bed, chests and ender crystal.

Changes in 1.15:
- removed "end_crystal_no_base"
- changed "chest_large": lid_left, base_left, knob_left, lid_right, base_right, knob_right
- added "trapped_chest" and "trapped_chest_large", similar to normal chests

**Comment by sp614x** [comment]
Fixed head models reverting after removing resource pack. 
Added head_creeper, head_wither_skeleton and head_zombie.
Fixed ender dragon.
Fixed model textures

**Comment by sp614x** [comment]
Added CEM donkey and mule chest models.

**Comment by ewanhowell5195** [comment]
What are the bone names for the new chest models on the donkey and mule?

Also my dragon model from 1.14 doesnt seem to be loading in 1.15. Did the bone names of that model change?

**Comment by ewanhowell5195** [comment]
closing issue as ive updated in a new issue #4781
