### ISSUE TITLE
[Copyright issue] a renamed reupload

### ISSUE THREAD

**Issue by Zack7292** [sp614x/optifine#3972]
## Description of Issue
ngl jsut look there and you'll understand, this is literally optifine renamed

https://www.curseforge.com/minecraft/mc-mods/bens-fps-enhancer

**Comment by IceCruelStuff** [comment]
That project was created 11 hours ago
![Screenshot](https://user-images.githubusercontent.com/50642756/82389221-6988df80-99f0-11ea-8c83-bbc16f3ee500.png)

**Comment by Zack7292** [comment]
and???

**Comment by HiItsDevin** [comment]
Reported to sp614x already. Thank you for letting us know

**Comment by sirfozz** [comment]
Why do people try things like this

**Comment by sirfozz** [comment]
Also, everyone reported them on curseforge so it should get taken down soon

**Comment by sp614x** [comment]
Reported to CurseForge, they should take it down.
