### ISSUE TITLE
[1.15.2 pre18 - pre23] Colored Banner Shield Flickering in Shaders with TAA enabled (SEUS Renewed 1.0.1)

### ISSUE THREAD

**Issue by G4M1NG-N1NJ4** [sp614x/optifine#3973]
## Description of Issue
Similar to the Banner Flickering issue that was fixed with the pre18 build, Banners applied to shields still appear to exhibit this flickering when using advanced graphics shaders such as SEUS with Temporal Anti-Aliasing (TAA) enabled in Shader Options. A gif demonstrating the issue is linked here: https://1drv.ms/u/s!AlzCHZDR3GRkulz6H0qHM_Cf4qWI?e=oQEGhO

## Steps to Reproduce
1. Craft a colored banner with a shield 
2. Equip shield
3. Enter Third-Person view with shaders and shader TAA enabled

## OptiFine Version
1.15.2-OptiFine_HD_U_G1_pre18 - pre23

## Installation Method
Downloaded the .jar file of this build from the "Preview Versions" section on Optifine.net Downloads. "Double-clicked" the downloaded file to bring up the installation GUI. Clicked "Install."

## F3 Debug Screenshot
Link to gif demonstrating issue with the debug screen enabled here: https://1drv.ms/u/s!AlzCHZDR3GRkul1rtX9_pd5EB6sq?e=wsMSQq

## Prior Testing
With the SEUS shader enabled, this issue has happened in earlier preview builds of Optifine 1.15.2. This issue does not occur with TAA disabled in Shader Options, or with shaders disabled / "Internal" shader enabled.

**Comment by G4M1NG-N1NJ4** [comment]
EDIT: The flickering on colored shields does not occur when TAA is disabled in Shader Options. I don't know if that was also a solution for colored banner flickering before the pre18 build patched it.

**Comment by G4M1NG-N1NJ4** [comment]
Issue fixed with 1.15.2-OptiFine_HD_U_G1_pre24

**Comment by Qwerty-Space** [comment]
Amazing, thanks
