### ISSUE TITLE
[Crash Report] Crash Upon Start Up 

### ISSUE THREAD

**Issue by Fritz2003** [sp614x/optifine#3977]
Pastebin Link: 
https://pastebin.com/Rm4YJznP

Im thinking that im running something outdated. I dont have forge so that shouldnt be a problem.

**Comment by asbyth** [comment]
optifine doesnt support hacked clients

**Comment by Fritz2003** [comment]
ohhh makes sense. Thanks for clearing that up!

**Comment by realjackasterisk** [comment]
> Wurst Client v7.0-MC1.15.2

Cheat and hacked clients are not supported.
