### ISSUE TITLE
[1.15.2] Shaders just render textures as black when loading in to other dimension that is not overworld 

### ISSUE THREAD

**Issue by oliver911** [sp614x/optifine#3978]
<img width="1920" alt="Base Profile Screenshot 2020 05 21 - 10 00 18 96" src="https://user-images.githubusercontent.com/14276446/82537202-e8456000-9b49-11ea-8f7e-9d6ddce6b56d.png">

**Comment by realjackasterisk** [comment]
Does this happen with other shader packs?

**Comment by TheoCGaming** [comment]
I have a similar issue where in the vanillaplus shaders, all enchanted tools, weapons, and armor are rendered as black silhouettes, with only the glint.

**Comment by naeqirelle2020** [comment]
@oliver911 what shaderpack are you using?

I've tested on 4 seperate shaderpacks

Vanilla Plus
Sildurs Vibrant Shaders 1.27
BSL 7.1.05
Chocapic 7.1.1

And i cannot reproduce this issue

**Comment by oliver911** [comment]
I'm using Sildurs Vibrant Shaders 1.27

Running with 32 GB DDR5 ram on a i7 9900 k and a rtx2080 s

**Comment by naeqirelle2020** [comment]
yeah i can't reproduce this bug at all, are you sure it's still happening on the latest preview?

**Comment by oliver911** [comment]
This seems to have been fixed in the latest version

**Comment by OfficialFezzman** [comment]
I get this bug on Sildur's Shaders 1.24 High Is there a way to fix it as I am playing on 1.14.4
