### ISSUE TITLE
[1.15.2] Worldborder doesn't render properly with shaders enabled

### ISSUE THREAD

**Issue by BauwenDR** [sp614x/optifine#3979]
## Description of Issue
The worldborder stops rendering if it collides with the sky on top of the nether roof ![2020-05-21_17 48 56](https://user-images.githubusercontent.com/65725037/82577949-02079700-9b8c-11ea-90e1-60d8c2e6fd99.png)
So if there is about 10 block in height of bedrock past the border the border appears to be one block high, but when the whole screen is filled with anything but the sky the border renders properly.
![2020-05-21_17 49 04](https://user-images.githubusercontent.com/65725037/82577985-1186e000-9b8c-11ea-9d7b-9ee71ca8d660.png)
I have tried 2-3 different shaderpacks, so I think it has to do with OptiFine.

## Steps to Reproduce
1. Walk up to the worldborder on the nether roof.
2. Look at the border from different angles.

## OptiFine Version
1.15.2 pre-18

## Installation Method
Through the standalone OptiFine installer

## Fabric/Forge Version
**If OptiFine is installed as standalone, you can remove this section.**

## F3 Debug Screenshot
![2020-05-21_17 52 38](https://user-images.githubusercontent.com/65725037/82577898-ef8d5d80-9b8b-11ea-8fd1-3f9f966f6781.png)

## Prior Testing
If you've installed standalone:
- Bug only appears when there is a shaderpack selected, so not if the selected shaders are off or on internal. And does not happen on a vanilla build of the game.

## Additional Information
I was using a texture pack in the screenshots, the bug also appears when not using one.

**Comment by sp614x** [comment]
Depends on the shader pack and how it blends the  world border with the sky.
Some shaders work correctly:

Sildur's Vibrant
![image](https://user-images.githubusercontent.com/16635441/85225985-29dd5b00-b3d5-11ea-9335-961ca0275bc7.png)

Chocapic13 v8.1
![image](https://user-images.githubusercontent.com/16635441/85226012-5db88080-b3d5-11ea-933a-78882ec4d47f.png)

**Comment by sp614x** [comment]
Probably has to do with the rendering order which is a bit different in 1.15.
