### ISSUE TITLE
Intel IGP doesn't change frequency.

### ISSUE THREAD

**Issue by UDPSendToFailed** [sp614x/optifine#398]
Hi!

I have a laptop with Intel HD3000, on Linux, it does 100+ FPS, but on Windows it won't change the frequency up to 1100Mhz when many chunks are loaded. I think this will be a Minecraft problem, because it works good in other games. Here is a video:

https://www.youtube.com/watch?v=VoCA5DQIe3U

Minecraft 1.11
OptiFine HD U B3
IGP driver - 9.17.10.4459

**Comment by nexitem** [comment]
This is not a OptiFine issue. Make sure your pc is running in High Performance mode and you got "Energy Saving" options disabled.

**Comment by sp614x** [comment]
This is an Intel driver problem. The driver tries to recognize if the running program need full GPU performance and controls the IGP frequency accordingly. The vanilla launcher adds a special runtime parameter for the Intel driver. Updating the IGP driver may help.
