### ISSUE TITLE
[shaders] Shulker Box odd lighting

### ISSUE THREAD

**Issue by Zenypher** [sp614x/optifine#3980]
## Description of Issue
When I use internal shader with 'Old Lighting' and 'Old Hand Light' off, the shulker boxes in my world are having some odd lighting effect. They become darker, even if is all lit up. On normal shader (the default one) it doesn't do this strange bug. Sorry for misspelling, but I don't speak english so often. Have a good day!

## Steps to Reproduce
1. Go to the Shaders Option
2. Set the shader to 'Internal'
3. Set the 'Old Lighting' and 'Old Hand Lighting' off

## OptiFine Version
OptiFine HD G1_pre17 Ultra for Minecraft 1.15.2

## Installation Method
standalone installer

## F3 Debug Screenshot
![2020-05-22_09 44 20](https://user-images.githubusercontent.com/65756061/82639885-4b022e80-9c12-11ea-8fcf-7eded87aed2f.png)
![2020-05-22_09 44 34](https://user-images.githubusercontent.com/65756061/82639892-4c335b80-9c12-11ea-8c89-329a5644cbcb.png)

## Prior Testing
- It does not happen in Vanilla Minecraft without OptiFine.

**Comment by realjackasterisk** [comment]
The shulker boxes are not darker, the world around them is brighter. By disabling "Old Lighting", the world visually becomes brighter on "internal" shaders, because this option disables Minecraft's default shading. This is just what "Old Lighting" does. This is not an OptiFine bug.
