### ISSUE TITLE
Permission Request for use on modpack OptiFine 1.12.2

### ISSUE THREAD

**Issue by imartinezgregori** [sp614x/optifine#3982]
I want to do a public modpacks (3 exactly) on my network, and I want the modpacks can enter ALL people without have a good PC and I want to can add optifine, with the use of optifine the modpack loads at 2.5G and whitout it at 3G, the modpacks I want to upload on Curse and Technic.

**Comment by sp614x** [comment]
Sorry, no.

**Comment by yezhiyi9670** [comment]
You can add instructions for players to install Optifine, without adding it to your modpack.
