### ISSUE TITLE
[Account Reset] Not sending account reset email.

### ISSUE THREAD

**Issue by liciousgamer** [sp614x/optifine#3986]
I've been trying to contact support but no one has seemed to get back to me. I know that sounds a little pushy but I would appreciate if they didn't just ignore it. I was trying to get my Optifine Cape back and i couldn't remember my password, I clicked on request new password, no email was sent. I would really appreciate if I could get a reset password email sent, as I did pay $10 for the cape. Sorry to bother you all, just very impatient, as I have been waiting a very long time for a response. Thanks ~ Licious

**Comment by MrCheeze446** [comment]
Are you sure that you're entering the correct email? If so, have you checked your spam folder?

**Comment by sp614x** [comment]
Please contact me on discord with details.
