### ISSUE TITLE
Option to not have framebuffer textures clear at the beginning of a frame

### ISSUE THREAD

**Issue by sonicether** [sp614x/optifine#399]
It would be incredibly useful if we could define an option that would disable the clearing of a texture at the beginning of a frame in order to retain texture data across frames (for things like temporal anti-aliasing and smooth exposure based on average luminosity).

I propose that this be done by having the following line of code in any composite shader:

`const bool [texture]Clear = false;`

where [texture] is the name of the texture (composite, gaux1, etc.). Of course, this would default to "true" for all framebuffer textures. 

So, in order to tell the Shaders Mod not to clear the gaux1 texture at the beginning of a frame,

`const bool gaux1Clear = false;`

could be defined in any composite*.fsh shader file. The correct handling of this behavior would be up to the shaderpack author.

For an example of this, I'll demonstrate how this functionality would be used for automatic exposure adjustment based on average luminosity of the final shaded image.

Imagine that in `composite4.fsh`, you're finished rendering and write to `gcolor`. However, inside `composite4.fsh` you also calculate the average luminosity of the screen during this frame and write the result to `composite`.

Then, in `composite5.fsh`, you would read from `composite` and write its contents to `gaux1`, and have `const bool gaux1Clear = false;` defined. 

You can imagine then that, in the next frame, `gaux1` would contain the average luminosity from the previous frame. So, a modification is made in `composite4.fsh` where we read from `gaux1` and blend that with the calculation of the average luminosity for the current frame and write the result to `composite`. 

Here's some pseudocode to demonstrate this.

composite4.fsh:
```
/* DRAWBUFFERS:03 */

void main()
{
	vec3 result = CalculateFinalResult();
	float averageCurrentLuminosity = CalculateAverageLuminosity();
	float averagePreviousLuminosity = texture2D(gaux1, texcoord.st).x;

	float averageLuminositySmooth = mix(averagePreviousLuminosity, averageCurrentLuminosity, 0.5);

	gl_FragData[0] = vec4(result, 1.0); 		//final write to gcolor
	gl_FragData[1] = vec4(averageLuminositySmooth, 0.0, 0.0, 1.0); 		//write exponential moving average to intermediate buffer
}
```

composite5.fsh:
```
/* DRAWBUFFERS:4 */

const bool gaux1Clear = false;	//Make sure that gaux1 isn't cleared so its data is visible on the next frame

void main()
{
	gl_FragData[0] = texture2D(composite, texcoord.st);		//write exponential moving average from intermediate buffer to gaux1
}
```

**Comment by Choca13** [comment]
In my opinion it would be better to export the framebuffer to a texture (ex: previousTexture1,previousTexture2) when it's called on the shader code. I'm using a lot of differents framebuffers currently in my shaders and I can't use another one to store something temporally dependent.

For example : 
`
/* DRAWBUFFERS:03 */
/* PREVBUFFERS:X0 */

void main()
{
	vec3 result = CalculateFinalResult();
	float averageCurrentLuminosity = CalculateAverageLuminosity();
	float averagePreviousLuminosity = texture2D(previousTexture1, texcoord.st).x;

	float averageLuminositySmooth = mix(averagePreviousLuminosity, averageCurrentLuminosity, 0.5);

	gl_FragData[0] = vec4(result, 1.0); 		//final write to gcolor
	gl_FragData[1] = vec4(averageLuminositySmooth, 0.0, 0.0, 1.0); 		//write exponential moving average to intermediate buffer
}
`

**Comment by sonicether** [comment]
Yeah, ideally that'd be even better. We'd need ping-pong buffers to avoid issues with reading from and writing to the same texture in the same pass, though.

**Comment by Choca13** [comment]
Additionnally is there a way to have the frame number (resetting after a set number to avoid very high numbers) to make temporal offsets possible?

Off-topic : SonicEther and sp614x, we have a discord channel for shaders, with nearly all active shaders devs and 100 members, if by any chance you are interested in joining.

**Comment by zombye** [comment]
Time since last frame should also be available, for the purpose of smooth autoexposure.

You can't really have the adjustment time depend on the current framerate, as that would end up being too fast in some scenes and too slow in other scenes.

**Comment by Strum355** [comment]
what zombye said would be good too. Otherwise things would be too framerate dependant. Needs some consistency across hardware

**Comment by dotModded** [comment]
I can whole heartedly agree with this, I've setup a complete photometric pipeline, can't really use the stuff available now, and no one is going to play with a manual camera.

**Comment by sp614x** [comment]
Updated preview B6 for 1.11.2, added option to skip the framebuffer texture clear.
Configure it by adding "const bool \<texture\>Clear = false;" to any of the composite fragment shaders.
Example:

    const bool gaux1Clear = false;

Should the option also work from "final.vsh"?

**Comment by sp614x** [comment]
The mapping to texture "[texture]Previous" may also be added later.

**Comment by sp614x** [comment]
@Choca13 how is the frame counter going to help? It is dependant on the framerate and it varies a lot.
The frame time should be more useful for temporal transitions.

**Comment by sp614x** [comment]
Updated preview B6 for 1.11.2.
Added uniform "frameTime" - last frame time in seconds.

**Comment by sonicether** [comment]
The frame counter could serve as an index for a sequence of sample offsets for temporal anti-aliasing.

**Comment by sp614x** [comment]
Maximum value for frameCounter is 720720, then wrap around to 0?
Then "frameCounter % N" will cleanly wrap around for all N between 1 and 16.
Also fits in a float with enough precision.

**Comment by sp614x** [comment]
Updated preview B6 for 1.11.2.
Added uniform "frameCounter".
