### ISSUE TITLE
[1.15.x] glowing effects with shaders freezes screen

### ISSUE THREAD

**Issue by resinate** [sp614x/optifine#3994]
when using any shader pack on 1.15.x if a mob has glowing white effect on, screen freezes. this doesnt happen if optifine is by itself with no shaders. no other mods or forge installed.

**Comment by sp614x** [comment]
Running with Forge, Fabric or standalone?
GPU or integrated graphics?
OS?
Have you tried updating the graphics drivers?

**Comment by yezhiyi9670** [comment]
Is it #3996? It sometimes cause the game to freeze.

**Comment by sp614x** [comment]
This only happens for invisible entities with glowing effect.
Duplicate of #3996.
