### ISSUE TITLE
[1.15.2] Invisible glowing entities with shaders freezes the screen

### ISSUE THREAD

**Issue by Zunderstormgg** [sp614x/optifine#3996]
## Description of Issue
Optifine seems to currently be unable to correctly render invisible entities with outline effect (Such as those caused by the Spectral Arrow). In such an event, the client will diplay a major graphical error for the user and any other user who has the entity within render distance and has optifine shaders enabled. Issue does not occour if shaders are OFF.

![OptifineError](https://user-images.githubusercontent.com/65973683/82935064-62c81280-9f84-11ea-9fe9-55cd6c161cfb.jpg)

## Steps to Reproduce
1. Find/Spawn entity
2. Shoot the entity with a spectral arrow or otherwise apply the outline effect.
3. Use a splash potion of weakness to make the enitity invisible, or otherwise cause it to have invisibility
4. Error Occours. 

## OptiFine Version
preview_OptiFine_1.15.2_HD_U_G1_pre13

## Installation Method
Error has been reproduced on both Optifine Via Fabric and Standalone Optifine.

## Fabric Version
0.5.2.40

## OptiFabric Version
optifabric-1.0.0-beta8.jar

## Other Installed Mods
Personally I use ReplayMod, however this has occoured with another user who does not use the Mod.

## Log Files/Crash Reports
[latest.log](https://github.com/sp614x/optifine/files/4684151/latest.log)

## F3 Debug Screenshot
![f3Debug](https://user-images.githubusercontent.com/65973683/82935042-5d6ac800-9f84-11ea-920c-f59c41c9792d.jpg)

**Comment by yezhiyi9670** [comment]
The bug makes the client freeze in my case (Builder's QOL).

**Comment by naeqirelle2020** [comment]
Tested, Still Occurs Pre-19

**Comment by sp614x** [comment]
Fixed in pre22.
