### ISSUE TITLE
Optifine won't run (MC Java 1.15.2), Linux Ubuntu

### ISSUE THREAD

**Issue by CompleteAirhead** [sp614x/optifine#3997]
I am completely new to Optifine, watched a tutorial explaining how to install it, proceeded to download it, and when double-clicked a window opens and states that it is not marked as executable. After a bit of research, turns out this is what Linux does to software that it does not trust. Right-clicking doesn't help as it doesn't even give me the option of opening it with Java. I've also read stuff about jarfix, not entirely sure whether it would help with the issue. Any suggestions ?

**Comment by ayush06feb** [comment]
Hello, it looks like you have not made the file executable. To do so, you need to set the executable bit.
To do so follow these steps:
1) Open terminal
2) Type in `sudo chmod +x ~/home/path/to/the/file/OptiFine.jar`
3) Type in your password (it would not be visible & also wouldn't be represented) and press `Enter`
4) now open the java file by double clicking it. It should launch and you are good to go!

PS: [Optional] Also learn the use of chmod for future use by typing in terminal `man chmod`

**Comment by JPaalman** [comment]
I never had to make a .jar executable to run it. I think your system is not recognizing the file needs to be opened in Java. Instead, it is trying to execute it as a program itself.

You can open the .jar in Java manually using:
`java -jar "/path/to/OptiFine.jar"` # you only need to include the "" if the path contains spaces

Additionally, make sure Java is installed. You can do this using the software manager, or use the following command:
`sudo apt update && sudo apt install openjdk-[the java version you want, 8 is often recommended]-jre`

**Comment by thecoder-001** [comment]
> I never had to make a .jar executable to run it. I think your system is not recognizing the file needs to be opened in Java. Instead, it is trying to execute it as a program or script.
> 
> You can open the .jar in Java manually using:
> `java -jar "/path/to/OptiFine.jar"` # you only need to include the "" if the path contains spaces
> 
> Additionally, make sure Java is installed. You can do this using the software manager, or use the following command:
> `sudo apt update && sudo apt install openjdk-[the java version you want, 8 is often recommended]-jre`
> 
> Normally, Minecraft wouldn't be able to run without Java, but nowadays it comes with bundled Java. However, your system won't recognize the bundled Java when you try to run a .jar.

Well it really depends on what your system configuration is. Mine required to chmod the file (which is default ubuntu behavior).
According to CompleteAirhead, when he tries to open the .jar, he got the error from the system that the file is not marked as executable. This clearly points towards the fact that the executable bit of the file is not set.
Also the chances of missing java installation is quite rare (unless a custom install) as ubuntu ships with openjdk (mine did, at least)

**Comment by CompleteAirhead** [comment]
> Hello, it looks like you have not made the file executable. To do so, you need to set the executable bit.
> To do so follow these steps:
> 
>     1. Open terminal
> 
>     2. Type in `sudo chmod +x /home/path/to/the/file/OptiFine.jar`
> 
>     3. Type in your password (it would not be visible & also wouldn't be represented) and press `Enter`
> 
>     4. now open the java file by double clicking it. It should launch and you are good to go!
> 
> 
> PS: [Optional] Also learn the use of chmod for future use by typing in terminal `man chmod`
> Also read: https://wiki.ubuntu.com/Security/ExecutableBit

Sir, you just my day. Worked a treat. Optifine up and running. Thank you so much (as well as JPaalman for that matter) for taking the time to help me out. Cheers!

**Comment by The-Maestrean** [comment]
when right clicking select properties > permissions. 
under that tab there is a check box that you will have to click to allow it to be run as a program. 
Before doing this to a program or executable of any type please make sure it is from a source you trust. If your issue is resolved please close it to let others know that this issue is fixed
