### ISSUE TITLE
glass pane texture flipped

### ISSUE THREAD

**Issue by Stac-J** [sp614x/optifine#3999]
the glass pane texture on the edge of windows is the wrong way round

**Comment by Stac-J** [comment]
![2020-05-28_11 34 53](https://user-images.githubusercontent.com/66066188/83132404-412c6f80-a0d9-11ea-9125-2dd0fe60467e.png)

**Comment by sp614x** [comment]
Which Minecraft and OptiFine version?
With Forge, Fabric or standalone?

**Comment by Stac-J** [comment]
It's on HD Ultra G1 pre 18
On fabric

**Comment by TheRedstoneRazor** [comment]
This has been an issue with OptiFine on fabric for quite a while. It's visible on glass panes and all colours of stained glass panes when viewed from the north or west side. Glass blocks are fine. Hope this helps.

![2020-05-29_23 32 49](https://user-images.githubusercontent.com/30379173/83310672-ba74b100-a204-11ea-8184-8f310d1db2fa.png)

**Comment by EdgyPotato** [comment]
use this resource pack, it fixes the glass panel
![Annotation 2020-05-30 233002](https://user-images.githubusercontent.com/64056626/83332410-a1840280-a2cd-11ea-9b41-9b2f74fffd81.png)

**Comment by sp614x** [comment]
You can use the OptiFabric resource pack to fix it.
Fabric is not supported.
