### ISSUE TITLE
Invisible chunk for specific camera distances and viewing angles

### ISSUE THREAD

**Issue by LigH-de** [sp614x/optifine#400]
Similar to [MC-63020](https://bugs.mojang.com/browse/MC-63020), the OptiFine renderer sometimes ignores chunks as well, making more distant chunks visible, for a certain range of camera distances and viewing angles.

If interested, I can provide a demo world.

**Comment by sp614x** [comment]
Can you post a link to the demo world and how to reproduce it?

**Comment by LigH-de** [comment]
[MediaFire shared folder](https://www.mediafire.com/folder/tklqvsdi75mtp/Minecraft) with 7-zip packed world and a preview how it looks for me right after loading this world.

**Comment by sp614x** [comment]
Here is a test world that demonstrates the vanilla chunk visibility problem: http://optifine.net/tmp/FlatCreative.zip. Stay on the stone block at (14, 10, -10) and rotate around to see some chunks disappear and reappear.

**Comment by sp614x** [comment]
This looks like a chunk visibility problem. The chunk is loaded, but it is not considered visible.
When zooming and moving the mouse around the missing chunk should appear.

**Comment by LigH-de** [comment]
Confirming for your demo: Both vanilla MC and OptiFine miss these chunks at different angles. Would you add this to JIRA, or shall I quote your URL there?

**Comment by sp614x** [comment]
The "optifine.net" URL is temporary, you can upload the FlatCreative.zip to MediaFire and post it to JIRA.

**Comment by sp614x** [comment]
Minecraft uses the "Advanced Cave Culling" algorithm: https://tomcc.github.io/2014/08/31/visibility-1.html
For better performance it uses a simplified model that generally works, but sometimes it fails to detect visible chunks. The wall in the test world was built specifically to trigger the problem.

**Comment by sp614x** [comment]
This is a vanilla problem and it is not easy to fix.
OptiFine tweaks the visibility detection a little and this results in different problematic cases.
There are cases which work in OptiFine and don't work in vanilla. And there are cases that work in vanilla and don't work in OptiFine.
