### ISSUE TITLE
Some specific linear chunks not rendering

### ISSUE THREAD

**Issue by JakaasJai** [sp614x/optifine#4000]
## Description of Issue
I downloaded Minecraft 1.15.2 Forge and then added some mods to forge including forge but when i turn on optifine after playing for a while and going 8 or 9 chunks away from my home and after coming back some chunks were not rendering
![2020-05-29_13 36 45](https://user-images.githubusercontent.com/65359852/83238191-b79da000-a1b3-11ea-899f-d553c1867238.png)
![2020-05-29_13 36 54](https://user-images.githubusercontent.com/65359852/83238198-b9fffa00-a1b3-11ea-8263-d36e44d9cc89.png)
![2020-05-29_13 37 22](https://user-images.githubusercontent.com/65359852/83238204-ba989080-a1b3-11ea-9275-216f56684b09.png)
![2020-05-29_13 37 30](https://user-images.githubusercontent.com/65359852/83238209-bb312700-a1b3-11ea-94f9-8cb61dd03036.png)
![2020-05-29_13 29 40](https://user-images.githubusercontent.com/65359852/83238213-bc625400-a1b3-11ea-8681-88221f5d2821.png)
![2020-05-29_13 36 32](https://user-images.githubusercontent.com/65359852/83238216-bcfaea80-a1b3-11ea-94b7-e9cc4fc7ce78.png)

## OptiFine Version
preview_OptiFine_1.15.2_HD_U_G1_pre18

## Installation Method
From adding mods in forge with tlauncher

## Other Installed Mods
1. branders-enhanced-mob-spawners-v1.15.2-1.5.4
2. furniture-7.0.0-pre16-1.15.1
3. gravestone-1.17.3
4. invtweaks-1.15.2-1.0.1
5. jei-1.15.2-6.0.0.3
6. journeymap-1.15.2-5.7.0beta1
7. OreExcavation-1.7.151
8. tlskincape1.15.2-1.11

**Comment by yezhiyi9670** [comment]
~~Congratulations, you've got No. 4000!~~

Journeymap has issues with Optifine. This has been reported a dozen of times.

**Comment by JakaasJai** [comment]
Thanks a lot for figuring this out.  ;)

**Comment by yezhiyi9670** [comment]
You can use Xaero's Minimap and Worldmap as a replacement if you don't need advanced features.
