### ISSUE TITLE
[CEM] Improvements to CEM animation

### ISSUE THREAD

**Issue by ZenithRogue** [sp614x/optifine#4008]
## Random entity seeds
Each entity should be assigned a random integer as a "seed" of sorts. This could be based off the entity's UUID, and could allow you to create animations for entities that are offset from each other:
**Example:** `"part:leg1.rx": "time+seed",`
This would make it incredibly simple to create variation in your entity animations.

## Persistent variables
Each entity could store variables that would persist between each frame of animation. This would allow more complex animations that can evolve based on other parameters, yet persist after those parameters change.
**Example:** `"variable": "variable/2",`

**Comment by NitroCipher** [comment]
[Moving my idea from issue #4033 ](https://github.com/sp614x/optifine/issues/4033#issuecomment-639814108)to this thread.

CEM animation should have access to an entity's rotation via `rot_x, rot_y, rot_z`. This could be used in a variety of situations, including locking a entity part to a specific rotation, etc.
