### ISSUE TITLE
[BUG] [Pre 19] CEM model textures said to be fixed but still not working

### ISSUE THREAD

**Issue by ewanhowell5195** [sp614x/optifine#4010]
## Description of Issue
The CEM model textures were said to be fixed in pre 19, but are still not working. They still do not load if they are in the CEM folder

## Steps to Reproduce
Put on this pack and summon a cow or a pig or something
[PlayerModelMobs 1.15 Test.zip](https://github.com/sp614x/optifine/files/4708764/PlayerModelMobs.1.15.Test.zip)

## OptiFine Version
1.15.2 HD U G1 pre19

![2020-06-01_01 26 23](https://user-images.githubusercontent.com/48070995/83366506-6950f280-a3a7-11ea-870f-f933d8378d70.png)

**Comment by sp614x** [comment]
Fixed, coming in pre20.
