### ISSUE TITLE
[Cit, Pre18] Cit Model Error

### ISSUE THREAD

**Issue by Jimmy-sheep** [sp614x/optifine#4011]
##Bug report
I put model in cit, it can work when item on ground or in inventory (picture 1, picture2) , but it dont work when it's in my hand (picture 3, the skull in my hand is original server design, not comes from resourcepack).

I'm sure it can work very well in OptiFine_1.14.4_HD_U_F5 :
Picture 4: It actually work in thirdpersonhand (Armor stand righthand).   1.14.4
Picture 5, picture 6: It actually work in my righthand.    1.14.4

Sorry about my poor English, and I'm first time to use Github, hope you can understand what i'm talking about.

## OptiFine Version
preview_OptiFine_1.15.2_HD_U_G1_pre18

## Other Installed Mods
No other mods.

## Additional Information
Here goes any final remarks and everything else that might not fit in the previous sections.

##Pictures (The top 3 pictures is in 1.15.2, the last 3 pictures is in 1.14.4)

![image](https://user-images.githubusercontent.com/65125836/83366885-688a8180-a3e4-11ea-9b4b-619865fb6901.png)
![image](https://user-images.githubusercontent.com/65125836/83366916-8952d700-a3e4-11ea-9214-99f2833b7dc3.png)
![image](https://user-images.githubusercontent.com/65125836/83366932-a12a5b00-a3e4-11ea-95f0-774436b5eaf2.png)
![image](https://user-images.githubusercontent.com/65125836/83367381-d59f1680-a3e6-11ea-8d16-b3a4c8a3cccd.png)
![image](https://user-images.githubusercontent.com/65125836/83367448-231b8380-a3e7-11ea-8ee6-28421a878514.png)
![image](https://user-images.githubusercontent.com/65125836/83367488-4c3c1400-a3e7-11ea-9231-8039391dba47.png)

**Comment by sp614x** [comment]
Fixed, coming in pre20.
