### ISSUE TITLE
[Category] Short description

### ISSUE THREAD

**Issue by satoru101** [sp614x/optifine#4012]
## Description of Issue
it didn't load using Forge from 1.13.2-1.15.2, maybe it just me

## Steps to Reproduce
1. i down load forge, set it up, the install Optifine in to the mod folder
2. when load the game up, i look in the mods section, cant find Optifine, in game i cant access any of Optifine stuff

## OptiFine Version
OptiFine_1.15.2_HD_U_G1_pre19_MOD

## Installation Method
download it from Optifine website, then open it up and clicked the extract button, and chose the mods file to extract it to

## Fabric/Forge Version
i'm using 1.15.2-forge-31.2.5
i did use Fabric which work fine
but i want to play some Forge mods with it

## Other Installed Mods
Upgrade 
[2020-05-31-1.log.gz](https://github.com/sp614x/optifine/files/4708874/2020-05-31-1.log.gz)
[debug.log](https://github.com/sp614x/optifine/files/4708875/debug.log)
[latest.log](https://github.com/sp614x/optifine/files/4708876/latest.log)

Aquatic
The Endergetic Expansion
Quark
Mantle
Just enough item
Inspirations
extraboats
Buzzier Bees
AutoRegLib
Abnormals Core

## F3 Debug Screenshot
Minecraft's built-in debug screen provides *a lot* of useful information, and should be included even if the issue is not something that can be captured in a still image.

To open this menu, simply press `F3` on your keyboard while in-game. Please ensure the text is easily readable. Depending on the size/resolution of your monitor, you may have to adjust your GUI scale for all text to be completely visible on-screen.

## Prior Testing

   - Only OptiFine and Forge

- Does this happen without any mods at all?
   - Only Forge by itself.

i did run it alone with forge, still didn't load
alone it work fine, fabric work

**Comment by YhvrWasTaken** [comment]
You are dropping `OptiFine_1.15.2_HD_U_G1_pre19.jar` straight into the folder with your other mods, right?

**Comment by satoru101** [comment]
no, when i download Optifine i click it and extract it in to the mod file. the it Optifine file is my mod folder have a MOD in it

**Comment by realjackasterisk** [comment]
1. Please fix the issue title.
2. You're not using the compatible Forge version. Install Forge `31.1.63` as stated by the OptiFine changelog here: https://optifine.net/changelog?f=preview_OptiFine_1.15.2_HD_U_G1_pre19.jar and let us know if the issue persists.

**Comment by satoru101** [comment]
It work, thank you very much.
