### ISSUE TITLE
[Servers and Multiplayer] Server-Side Optifine

### ISSUE THREAD

**Issue by AverageComet250** [sp614x/optifine#4013]
I KNOW THIS HAS ALREADY BEEN ASKED A FEW TIMES, BUT IT'S SOMETHING THAT WOULD HELP HOME MC SERVERS BECOME MORE POPULAR

I know this is a feature that has already been asked for, but it's something that would help the minecraft server hosting community alot, and would make it more popular. A server side version could also be created in the form of a bukkit/spigot plugin, thus allowing big public servers to use it as well. A good plan would be a lag reducer, connected textures and possibly even shader support.

I's also recommend making versions for 1.12.2, 1.13.2 and 1.14.4 as well as 1.15.2 as people do still use those versions  to play old mods.

**Comment by AverageComet250** [comment]
Just to make it clear this is a feature request and not a bug

**Comment by TropheusJ** [comment]
please share your infinite wisdom and tell us how shader support or connected textures would work on something that doesnt even have any rendering?

a server side optifine will never happen because:
1. other mods like lithium exist
2. most of optifine's performance comes from rendering
3. server types like spigot and bukkit already do a ton for increasing server performance. compare a vanilla server to a spigot one.

**Comment by AverageComet250** [comment]
Sorry, I'm not much of a mod developer and I'm still learning how to make the mods, BUT:
1. Basic rendering does exist, in the form of server-side resource packss
2. With the introduction of mc rtx on windows 10, we can be hopeful that the mc rendering system will be improved (This means that this idea will have to wait for more mc updates though)
3. The reason I mentioned bukkit and spigot because they're a lot more popular than forge when it comes to server type
4. I own a big, loud, electricity eating dell poweredge r610 at home. It's OS is ESXi (Ask google what that is, not me) and it has roughly 5 ubuntu VMs (ask google) running on it at all times. One of those VMs hosts my personal MC server, which is spigot and lags even though there's never more 3 people on it at one time. Switching to forge would cause issues, as my friends, computer can't run more than 3 mods at a time (Xaero's World map and minimap, along with Optifine). I can't find anything out there on the internet that suits my need. BUT, the lag reducing systems that OF have are what I think would be best for my server. I find that with OF, and minimal settings, the slow 4GB PC that I use for purposes that I would prefer to keep to myself, runs mc near perfectly.

Sorry for the big answer @TropheusJ

**Comment by TropheusJ** [comment]
Counter-points:
1. No? The server itself does not render anything. All it does in that scenario is tell clients what resource packs to use. Want proof? Look at the screen. Do you see Minecraft? No? Then I can almost guarantee there is no rendering.
2. Hopefully, but one of the reasons Minecraft still uses old rendering methods is to support more hardware and at this point getting native RTX/ray tracing of any kind would require basically a full rewrite. That’s why bedrock edition exists. 
3. Ok
4. That lag could be caused by many things. Main thing is probably the fact that you’re running 6 VMS at once. Have you checked system usage? Is the internet connection good? Is everyone else’s connection good? First of all, why would you switch to forge? Second of all, if you do for whatever reason, your friend doesn’t have to use mods if they can’t. Unless you add mods to the server.

**Comment by TropheusJ** [comment]
In conclusion, optifine for servers will probably never happen.

**Comment by AverageComet250** [comment]
I guess you're right, but here's the deal with mods and my friend

1. the two Xaero mods basically allows us to sync up when we need too. Our checkpoints and chunk data is also synced via a private git repo and a py script.
2. The py script creates a lot of lag with the Xaero mods, as it syncs every 10 seconds
3. the mods thing was because of lithium, and he'd have to install it too. His minecraft would end up very laggy and he'd probably encounter more game crashes as well.

@TropheusJ Should I close this thread now, as the outcome of this idea has already been decided

**Comment by TropheusJ** [comment]
Probably should close it. Also, lithium should reduce lag. Look into that.

**Comment by AverageComet250** [comment]
yeah I know, but won't my friend has to install it too? I also have roughly 10 bukkit plugins running on my server, so how will I deal with that? I'll close the thread when you have an answer to that.

**Comment by TropheusJ** [comment]
Just like optifine, lithium is client side. (I think)
And what about the bukkit plugins?

**Comment by AverageComet250** [comment]
I'll send you a list with the plugins I use later. Would you know any mods to replace them?

**Comment by TropheusJ** [comment]
Why are you switching to forge?

**Comment by TropheusJ** [comment]
And I definitely don’t know any replacements. I don’t use server forge mods.

**Comment by AverageComet250** [comment]
In that case I won't be switching, but my lag will probably end up going up I'll be closing this thread now

**Comment by AverageComet250** [comment]
I can always re-open the issue if required

**Comment by Thorinair** [comment]
It sounds like you want to have a system similar to game streaming (like NVidia GeForce Now, Stadia, etc), but host it yourself. That way, you can literally run whole clients on your server. xD

**Comment by npgoalkeeper** [comment]
I'm over a month late but there's lots of server-side performance mods, and if you don't mind giving up some vanilla functionality, you can use something like YAPFA or papermc. 

Optifine touches MC's rendering, which is all client-side. As such, it probably wouldn't help as a server-side mod.

**Comment by AverageComet250** [comment]
I know this thread is practically EOL, but one way of implementing this might just be by making it so that you NEED optifine to join the server, In the same way badlion anti-cheat servers can say that players need badlion to play.

**Comment by npgoalkeeper** [comment]
...That's just eliminating options for normal users

**Comment by InfinityZ25** [comment]
Sorry for the necroposting, but I think what he meant was to create a server-side api to tell the user's client what settings to use, Sort of like spigot currently has with player#setTexturePack(URL) but for shaders if present. Imagine being able to change user's shaders on-demand server-side. Of course, it would be optional and I doubt if it is even possible right now. Maybe creating a custom communication channel for the server and client to talk directly, sort of like this https://github.com/SmylerMC/BungeeCord2ForgeChannels but built into optifine.

Methods for api could look like this
`
    private static String MAGIC_CHECKSUM = "yourmom";

    /**
     * Brief example, the idea is that the Optifine API would verify the user's
     * instalation with a simple function based on the user's UUID and return an
     * object with methods to manipulate the user's video settings etc.
     * 
     * Also, I'm being explicit with my variables to make it easier to understand, I
     * normally just user var keyword for everything haha.
     */
    public static void changeShaderExample(UUID player) {
        /** Make the request using the hypothetical OptifineAPI. */
        Optional<OptifinePlayer> check = OptifineAPI.verifyUserById(player);
        /**
         * Check if the optional is present. Is empty, then the user doesn't have
         * optifine installed, no big deal.
         */
        if (check.isPresent()) {
            final OptifinePlayer optifinePlayer = check.get();
            /**
             * This method looks at the installed shaders and choses the one that matches
             * the server's demand. Maybe a regex expression would be cool? The function
             * returns a CompletableFuture<Boolean> to know when the change is completed by
             * the client's game.
             */
            CompletableFuture<Boolean> changeRequest = optifinePlayer.changeShaderPack("SuperCustomShader");
            /**
             * The task might take long time on all computers, so maybe add a timeout to
             * assume the client crash if it takes longer than x seconds?
             * 
             * Also since Java16 will be required in 1.17, all users will have the
             * java.util.concurrent.Flow class which makes the implementation of all of this
             * easier with reactive streams.
             */
            changeRequest.thenAccept((Boolean result) -> {
                if (result)/** The change succeded */
                {
                    /** Verify by asking the client again what shader pack it is currently using. */
                    var shaderPackRequest = optifinePlayer.getCurrentShaderPack();
                    /**
                     * This also will be a completable future since the client will take however
                     * long it needs to respond.
                     */
                    shaderPackRequest.thenAccept((Optional<ShaderPack> sp) -> {
                        if (sp.isPresent()) {
                            ShaderPack shader = sp.get();
                            if (shader
                                    .getChecksum() == MAGIC_CHECKSUM) /** The user has the shaderpack that you wanted */
                            {
                                optifinePlayer.sendMessage(
                                        "Your shaderpack was changed to by the server " + shader.getShaderPackName());

                                /** And then change the users video settings just cause you can. */
                                optifinePlayer.setRenderDistance(8);
                                optifinePlayer.setVisualQuality(VisualQuality.FABULOUS);
                            }

                        } else {
                            /** The shaderpack request failed for whatever reason. */
                        }
                        ;
                    });

                } else {
                    /** The request failed for whatever reason. */
                }

            });
        }
    }

`

**Comment by AverageComet250** [comment]
This isn't what the original post was for, but that would be a good idea.

Make a new thread for it though.

**Comment by InfinityZ25** [comment]
I guess I miss understood you then. Oh well, it is a good idea regardless haha.

So I guess what you did want was something like google stadia but for minecraft haha?
