### ISSUE TITLE
[BUG] [1.15.2-pre-19] CEM of Chest Broken after said to be fixed

### ISSUE THREAD

**Issue by Pumpking0108** [sp614x/optifine#4015]
## Description of Issue
CEM Chest is broken.

## Steps to Reproduce
1. Use this resource pack in 1.14.4 Optifine 
[BUG PACK 1.14.4.zip](https://github.com/sp614x/optifine/files/4712083/BUG.PACK.1.14.4.zip)
2. Now try this Same Resource Pack except for 1.15.2 pre-19 
[BUG PACK 1.15.2.zip](https://github.com/sp614x/optifine/files/4712085/BUG.PACK.1.15.2.zip)

## OptiFine Version
1.15.2 pre-19

## Installation Method
Jar file

## Images
1.14.4 Optifine
![2020-06-01_11 23 08](https://user-images.githubusercontent.com/64932087/83424631-a85c6380-a3fa-11ea-8698-9a8ca56edd48.png)
1.15.2 pre-19 Optifine
![2020-06-01_11 24 54](https://user-images.githubusercontent.com/64932087/83424650-ae524480-a3fa-11ea-8a1a-816717c18cbf.png)

**Comment by ewanhowell5195** [comment]
it is fixed but the uv mappings and bones changed. Here are some templates that i made
[chest_templates.zip](https://github.com/sp614x/optifine/files/4712311/chest_templates.zip)
