### ISSUE TITLE
1.15.2 pre19

### ISSUE THREAD

**Issue by Roma4kaaaa** [sp614x/optifine#4016]
ITEM BUG, RENAMED ITEMS DON't SHOWING,
![image](https://user-images.githubusercontent.com/66267666/83429943-87693200-a43d-11ea-8627-1e8f38332852.png)
![image](https://user-images.githubusercontent.com/66267666/83430012-9ea81f80-a43d-11ea-9f69-c314f6320133.png)

**Comment by Roma4kaaaa** [comment]
PLS FIX

**Comment by Deviouslrd** [comment]
CIT isn't fully implemented or working yet.

**Comment by Doots2521** [comment]
Yes, hi I would like to report that SEUS PTGI's Torch and Block Lighting is still not working. I'm quite sure that the devs are already aware of this, put just wanted to put it out there to reiterate that the change will still need to be fixed in later updates. Thanks!

**Comment by Pumpking0108** [comment]
CIT is working for me fine

**Comment by realjackasterisk** [comment]
@Doots2521 What does that have *anything* to do with this issue?

**Comment by sp614x** [comment]
Fixed, coming in pre20.
