### ISSUE TITLE
Shadows/Sun Lighting weird bug in a Cave 

### ISSUE THREAD

**Issue by ChristofuPH** [sp614x/optifine#4018]
Latest Version Preview of Optifine
Shadows & lighting from the Sun are showing inside of Cave 
![2020-06-02 (1)](https://user-images.githubusercontent.com/66296069/83486575-090f9d00-a4dc-11ea-8886-e5282bddd2b0.png)
![2020-06-02 (4)](https://user-images.githubusercontent.com/66296069/83486590-12006e80-a4dc-11ea-80b6-7063bd7b2370.png)
![2020-06-02 (5)](https://user-images.githubusercontent.com/66296069/83486598-17f64f80-a4dc-11ea-926e-0172083c1b8f.png)

**Comment by F1b3rDEV** [comment]
Are you sure this is related to Optifine and not to your shader?

**Comment by ChristofuPH** [comment]
> Are you sure this is related to Optifine and not to your shader?

Yes i tried some Shaders but still the same problem

**Comment by realjackasterisk** [comment]
This is a common issue with shaders, and it's simply due to how shaders interact with unloaded Minecraft terrain. Some shader packs fix this by disabling sunlight/shadows at certain depths. Not an OptiFine bug.
