### ISSUE TITLE
1.12.2 forge crash

### ISSUE THREAD

**Issue by Vincent98740** [sp614x/optifine#4019]
[crash-2020-06-02_16.21.53-client.txt](https://github.com/sp614x/optifine/files/4715838/crash-2020-06-02_16.21.53-client.txt)

**Comment by realjackasterisk** [comment]
Please give us more details. A crashlog alone isn't gonna be too useful. You can use the issue template for reference: https://github.com/sp614x/optifine/issues/new/choose
