### ISSUE TITLE
You can see your shadow when in spectator mode

### ISSUE THREAD

**Issue by Etomic-Studios** [sp614x/optifine#4022]

**Comment by realjackasterisk** [comment]
ANY details? please?
use the bug report template for reference: https://github.com/sp614x/optifine/issues/new/choose

**Comment by Etomic-Studios** [comment]
Oh Sorry, so I am in pre release 19 and I am just using optifine

**Comment by realjackasterisk** [comment]
so it's standalone? is this a shaders thing? what shader pack are you using? have you tried multiple shader packs? was this ever an issue on previous versions of optifine?

**Comment by Ioxom** [comment]
I get this issue with any shader in pre19. Not sure if it's even a bug though.

**Comment by sp614x** [comment]
Fixed in pre20.
