### ISSUE TITLE
[Bug] [Pre 19] Random Entity not working with custom CEM textures

### ISSUE THREAD

**Issue by DraminOver** [sp614x/optifine#4025]
## Description of Issue
The Random Entity feature is not working with custom CEM textures.

## Steps to Reproduce
1. Create a CEM model and specify a custom texture.
2. Try to use the Random Entity feature to create variants of that custom texture.

Or

Use [this resourcepack](https://drive.google.com/file/d/1SoqQimuI-qWdf_eZsPaJ50wuljY8pEE2/view?usp=sharing) to see the issue. It's working fine in Optifine 1.14.
The Creeper it's supposed to be crying when it's raining above Y 50. (in 1.14)

The added CEM model to the Creeper's head is using the specified ".png" texture (a provisional black texture), but it's ignoring the actual textures that are implemented with the Random entity feature.

## OptiFine Version
OptiFine 1.15.2_HD_U_G1_pre19

## Installation Method
Standalone installer

**Comment by sp614x** [comment]
Fixed in pre20.
