### ISSUE TITLE
World wont load it

### ISSUE THREAD

**Issue by joefy200** [sp614x/optifine#4026]
Whenever I try to join one particular world it wont load the terrain, but it will work with my other maps. Ive had this issue every preview

**Comment by Ioxom** [comment]
Have you tried f3 + A after joining?

**Comment by realjackasterisk** [comment]
more details please. what version are you on?

**Comment by The-Maestrean** [comment]
and if modded what mods are you using

**Comment by Unownisgod** [comment]
is this the problem you had?
![image](https://user-images.githubusercontent.com/66778864/84376258-1f56e080-abe1-11ea-9343-a1a6e24fc82e.png)

**Comment by Unownisgod** [comment]
looks like the world only generates correctly a 21x21 chunks area with centre in the spawnchunk
![2020-06-11_12 49 09](https://user-images.githubusercontent.com/66778864/84377195-89bc5080-abe2-11ea-96dd-377b77557c58.png)

**Comment by KaiAF** [comment]
Is this still an issue? I believe this was fixed already.
