### ISSUE TITLE
[bug] [1.15.2-pre19] random entity textures don't work on .jpm body part models

### ISSUE THREAD

**Issue by iNkoR-the-2nd** [sp614x/optifine#4027]
## Description of Issue
The .jpm models that used to work in 1.14 using random entity textures no longer display the appropriate texture, only the original texture, despite having a file that specifies the conditions under which the skin should be different.

## Steps to Reproduce
1. Create a working .jpm model, with a texture path to textures/entity and wherever that goes
2. Make an alternative texture in optifine/random/entity/ same folder. Essentially the exact same thing as random entity textures, just for .jpm models.
3. Make sure it works in 1.14 and check in 1.15 where it doesn't work anymore.

## OptiFine Version
1.15.2-pre19

## Installation Method
Preview downloads

## Log Files/Crash Reports
The log acts as if this actually works:
[OptiFine] RandomEntities: textures/entity/spider/nether_spider_head.png, properties: optifine/random/entity/spider/nether_spider_head.properties

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
This feature wouldn't work in vanilla to begin with

- Does this happen in OptiFine standalone?
Yes
- Does this happen in Vanilla without OptiFine?
No

## Additional Information
Used to work in 1.14, no longer does in current latest preview versions.
![2020-06-03_19 05 59](https://user-images.githubusercontent.com/64202096/83702196-91bc3500-a5d1-11ea-914b-e9307f4b7f51.png)

**Comment by Sydnxt** [comment]
Can confirm

**Comment by sp614x** [comment]
Fixed in pre20.
