### ISSUE TITLE
Disconnected glass textures with Connected Textures enabled.

### ISSUE THREAD

**Issue by DesktopTested** [sp614x/optifine#4028]
Large planes of glass such as in the [screenshot](https://drive.google.com/file/d/14oRnmvpzblartfyW8fY3MVlD7Ip_XfTZ/view?usp=sharing) have lines between them, though it can be fixed by reloading chunks

**Comment by realjackasterisk** [comment]
What do you mean they have "lines between them"? Please elaborate.

**Comment by sp614x** [comment]
This is a problem with resorting of translucent blocks, not related to connected textures.
Looks like a vanilla problem.
