### ISSUE TITLE
Incompatibility with Lucraft: Core Mod

### ISSUE THREAD

**Issue by WenXin20** [sp614x/optifine#403]
Forge 2185
I get an InvocationTargetException Crash with [Speedster Heroes Mod](https://minecraft.curseforge.com/projects/speedster-heroes) and it's [Core Mod.](https://minecraft.curseforge.com/projects/lucraft-core)
It crashes before the game can even luanch. Is this possible to fix?
[Crash Log](http://pastebin.com/L4gqC9vr)
[Report on Mod Pg](https://minecraft.curseforge.com/projects/lucraft-core/issues/1)

**Comment by sp614x** [comment]
It crashes because it fails to properly patch the Entity class.
The Entity class is not modified by OptiFine. 
The crash does not seem to be related to OptiFine.

**Comment by WenXin20** [comment]
Ok, thanks, I'll report that.
