### ISSUE TITLE
[Bug?] Custom Textures

### ISSUE THREAD

**Issue by Squishy8206** [sp614x/optifine#4031]
## Description of Issue
Custom textures not having animations such as custom rods for gamemodes such as Hypixel Skyblock.

## Steps to Reproduce
1. Turn on Custom Items option in Quality settings
2. Use a custom Hypixel Skyblock texture pack
3. Use any items such as the grappling hook, or any custom rod.

## OptiFine Version
OptiFine 1.8.9 HD U L5 (Badlion Client)

## Installation Method
Badlion Client

## OptiFabric Version
Badlion Client (HD U L5)

## Other Installed Mods
https://pastebin.com/yT5Y0U5a

## Log Files/Crash Reports
No Crash Files

## F3 Debug Screenshot
https://i.badlion.net/hMxfk8SsbXetGKapdkwAw9.png

## Prior Testing
Not much testing although I have found turning Custom Items off fixes the issue so I presume the issue has something to do with the Custom Items module of the mod.

**Comment by sp614x** [comment]
Badlion is not supported.
