### ISSUE TITLE
[BUG] CEM Custom textures not working for chest

### ISSUE THREAD

**Issue by Pumpking0108** [sp614x/optifine#4032]
## Description of Issue
The custom textures do not work for the chest after saying they fixed CEM custom textures

## Steps to Reproduce
1. Get a CEM custom texture resource pack
2. try to use it in optifine 1.15.2 pre-20

## OptiFine Version
optifine 1.15.2 pre-20.

## Installation Method
jar file

**Comment by sp614x** [comment]
The chest models were changed in 1.15.
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/cem_model.txt#L28
