### ISSUE TITLE
[CEM] Animation entity pos variables have inconsistent capitalization 

### ISSUE THREAD

**Issue by NitroCipher** [sp614x/optifine#4033]
## Description of Issue
Entity position coordinates in CEM animation are incorrectly labelled in the doc as `pos_x, pos_y, and pos_z`. In actual function, these are `pos_x, pos_Y, pos_Z`.
The capitalization does matter, and the model fails to load if capitalized incorrectly

## Additional Information
Entity rotation variables would be a nice addition as well, if this is fixed. (Not talking about bone rotation)

**Comment by sp614x** [comment]
What would be the entity rotation variables: yaw, pitch?

**Comment by sp614x** [comment]
Fixed in pre21.

**Comment by NitroCipher** [comment]
The rotation should probably be something like `rot_x, rot_y, rot_z`

Not sure how many entities would use all of those, but they would be very useful in animation
