### ISSUE TITLE
[BUG REPORT]Crash with obfuscate

### ISSUE THREAD

**Issue by The-Maestrean** [sp614x/optifine#4036]
## Description of Issue
crash when Rendering entity in world

## Steps to Reproduce
1. Install optifine and Obfuscate
2. launch world and crash

## OptiFine Version
1.15.2 pre 20
## Installation Method
jar in mods folder

## Fabric/Forge Version
31.2.0

## Other Installed Mods
![image](https://user-images.githubusercontent.com/62222154/83915878-baf7d500-a739-11ea-8482-5f31b2f80fd2.png)

## Log Files/Crash Reports
[crash-2020-06-05_14.26.48-client.txt](https://github.com/sp614x/optifine/files/4738115/crash-2020-06-05_14.26.48-client.txt)

**Comment by sp614x** [comment]
Fixed in pre20.
