### ISSUE TITLE
[1.15.2] Shaders cause chest CEM to render dark

### ISSUE THREAD

**Issue by ItsChawk** [sp614x/optifine#4038]
## Description of Issue
Please provide as much detail as possible.

## Steps to Reproduce
[chest_large.zip](https://github.com/sp614x/optifine/files/4738839/chest_large.zip)
[BSL_v7.1.04.1.zip.zip](https://github.com/sp614x/optifine/files/4738841/BSL_v7.1.04.1.zip.zip)
Use the jem model with this shader for the same effect

## OptiFine Version
1.15.2 Pre 21
![2020-06-05_23 45 36](https://user-images.githubusercontent.com/66498400/83928783-dfc76900-a788-11ea-8d9a-6f1e67680152.png)
![2020-06-05_23 46 08](https://user-images.githubusercontent.com/66498400/83928785-e229c300-a788-11ea-8069-cc9dc170e475.png)

**Comment by sp614x** [comment]
Can you post a sample resource pack to reproduce the problem?
The `chest_large.jpm` is missing the texture.

**Comment by ewanhowell5195** [comment]
cant recreate when using the pack

**Comment by sp614x** [comment]
Should be fixed in latest preview.
