### ISSUE TITLE
[Bug] [CEM] [1.15.2 Pre 21] Child Horse `leg` bones don't scale correctly along the Y axis

### ISSUE THREAD

**Issue by ewanhowell5195** [sp614x/optifine#4039]
## Description of Issue
When custom modelling the child horse legs, they do not scale correctly along the y axis.
Havent tested but this probably happens on the other horse like models (zombie, skeleton, donkey, mule)

## Steps to Reproduce
Use this model in game and summon a baby horse 
`/summon minecraft:horse ~ ~ ~ {NoAI:1,Silent:1,Tame:1,Age:-12000}`
[horse.zip](https://github.com/sp614x/optifine/files/4739024/horse.zip)

## OptiFine Version
1.15.2 pre 21

## Vanilla Model:
![2020-06-06_00 51 18](https://user-images.githubusercontent.com/48070995/83930611-69c70000-a790-11ea-8011-9425cd75d7de.png)

## CEM Model:
![2020-06-06_00 51 02](https://user-images.githubusercontent.com/48070995/83930629-7ea39380-a790-11ea-827e-fbd1d5ec49bb.png)

## One Leg Modelled:
![2020-06-06_00 42 25](https://user-images.githubusercontent.com/48070995/83930658-9418bd80-a790-11ea-92f1-36f923334164.png)

**Comment by sp614x** [comment]
The vanilla model is created with asymetric scaling.
Can only be fixed in the CEM model.
