### ISSUE TITLE
Any form of change in resolution in Final to gcolor causes issues

### ISSUE THREAD

**Issue by SergeantSarcasm** [sp614x/optifine#404]
Back at it again with another problem. Not sure if there is a way around it, there probably is but I don't exactly know what it is.
K so more information on the issue, whenever I do any form of biasing through texture2D, any lodding in texture2DLod, any downscaling in composite2 and carrying over to final, or even any multiplications to the texcoord when sampling gcolor will cause a variety of issues:
One, my raytracer for reflections just stops showing up. No reflections, nothing. Just water SSS.
Two, the sky mixes in with it's background image EVEN WHEN it was applied 2 files back. This means it gets darker and the default sun shows up, so just the resulting image from having gbuffers_skybasic return 0.0 only.
Not sure what could be causing this, but it puts a bit of a damper on my development process as the option to downscale in final would be nice.

**Comment by DatWeirdPerson** [comment]
Same types of issues for me, I can enable mipmapping on colortex4 in composite, and it will break it in final.

**Comment by SergeantSarcasm** [comment]
![image](https://cloud.githubusercontent.com/assets/24683817/21701640/85e09e8c-d36c-11e6-9c67-f7a73e85c4ad.png)
In case you actually needed a picture, that's what happens when i simply offset the texcoord. But clearly you don't care that much about it, so take your time I guess.

**Comment by sp614x** [comment]
What is the minimal resource pack that reproduces the problem?
