### ISSUE TITLE
[1.15.2 Pre21] Shaders not working correctly

### ISSUE THREAD

**Issue by devereaux98** [sp614x/optifine#4040]
Currently using Optifine 1.15.2 Pre21 attempting to use updated shaders that others have been using successfully (SEUS Renewed 1.01).  My graphics card (Geforce 1070Ti) has been updated and yet the graphics seem very odd.  I have also tried a clean install of the shader.  Here is a screenshot of what I'm talking about:

![image](https://user-images.githubusercontent.com/22154989/83932312-ee992600-a75e-11ea-9325-abf7eaa62a49.png)

![image](https://user-images.githubusercontent.com/22154989/83932320-f658ca80-a75e-11ea-8331-7d16b463041a.png)

Everything seems to have fuzzy rim lighting and weird jagged edges in places.  I am unsure of what the issue is.  Any help would be greatly appreciated, thank you.

**Comment by Ioxom** [comment]
Have you tested in earlier previews?

**Comment by devereaux98** [comment]
> Have you tested in earlier previews?

Yup, i've been trying since whichever version first introduced shader support

**Comment by devereaux98** [comment]
Here are my settings if it helps:

![image](https://user-images.githubusercontent.com/22154989/83933356-f8258c80-a764-11ea-9a71-64239f1c4765.png)

![image](https://user-images.githubusercontent.com/22154989/83933369-08d60280-a765-11ea-8ec8-6df118843e4e.png)

![image](https://user-images.githubusercontent.com/22154989/83933379-1b503c00-a765-11ea-8149-144bf7ebc7dc.png)

![image](https://user-images.githubusercontent.com/22154989/83933385-2a36ee80-a765-11ea-8f6c-c60cbe05aa26.png)

![image](https://user-images.githubusercontent.com/22154989/83933390-391da100-a765-11ea-9c48-e4b2723a7bcc.png)

**Comment by Ioxom** [comment]
Try turning all the performance stuff off (smooth FPS, fast math, smooth world).

**Comment by devereaux98** [comment]
> Try turning all the performance stuff off (smooth FPS, fast math, smooth world).

It yields the same result unfortunately :/ deleting or resetting the startup options doesn't change anything either.

**Comment by devereaux98** [comment]
Is there any sort of log i can provide you?

**Comment by devereaux98** [comment]
Okay for some reason, installing a different shader seemed to fix ALL shaders.
