### ISSUE TITLE
[Bug] [CEM] [1.15.2 Pre24] "scale" CEM feature is broken

### ISSUE THREAD

**Issue by DraminOver** [sp614x/optifine#4044]
## Description of Issue
The baby fox CEM model seems to have different values compared to 1.14.
edit: The scale feature seems to be the problem here, it's not working properly in any of the mobs I tested
## Steps to Reproduce
Resource Pack for testing [HERE](http://www.mediafire.com/file/e0y6xylyjy981wf/Better_Vanilla_Babies_Fox_Issue.zip/file)
1.14
![2020-06-06_12 55 42](https://user-images.githubusercontent.com/21205057/83948772-15566b80-a7f6-11ea-8618-67cabb42d19e.png)
1.15
![2020-06-06_12 57 10](https://user-images.githubusercontent.com/21205057/83948782-230bf100-a7f6-11ea-9a7c-7486e9d3bf92.png)

## OptiFine Version
OptiFine 1.15.2_HD_U_G1_pre24

## Installation Method
Installer

**Comment by ewanhowell5195** [comment]
works fine for me
![2020-06-07_23 03 15](https://user-images.githubusercontent.com/48070995/83981131-23e67500-a913-11ea-9baf-7555e167550c.png)

**Comment by DraminOver** [comment]
I think I found out the problem. The "scale" CEM feature might be broken. My model was using it and that must be the reason why those body parts are smaller in 1.15

**Comment by ewanhowell5195** [comment]
You need to edit the description of the issue as well then

**Comment by DraminOver** [comment]
Done

**Comment by heinrich26** [comment]
I'm using pre23 as well, and scale works fine for me. 
`{
  "models": 
  [
	{
      "model": "ravager_horn.jpm",
      "part": "head", 
	  "attach": true,
      "translate": [0, -10, -14.5],
      **"scale": 0.75**,
      "rotate": [5, 0, 0]
    }
  ]
}`
thats a .jem file, I think you cannot use "scale" in jpm, theres only "sizeAdd", which wasnt inserted correctly by blockbench for me.

**Comment by DraminOver** [comment]
Oh, no it's not hidden, the model is there. You can see a little bit of the body if you look closer, it's behind the head. So it's the same issue as yours
Also it's still present in Pre24, so I'm updating the tile and description.

**Comment by ewanhowell5195** [comment]
scaling has now been fixed
