### ISSUE TITLE
[CIT] [1.15.2 Pre22] .json file : Absolute path VS ./

### ISSUE THREAD

**Issue by cricri211** [sp614x/optifine#4046]
## Description of Issue
It seems like relative path `./` is not working on `.json` file. It always searches on `textures/` folder.
**Before** (1.14) `./` made it change into the current folder, to search an item, worked well.
**Now** (1.15) it looks for the texture in `textures/./`, the `./` is not recognized as command to change the current directory.

Now we necessarily need to use absolute path from `optifine/`. For example, if I put the entire path, like
`"optifine/cit/general/nourriture/nourriture_tag/boire/bouteille/bouteille_liquide"`
instead of
`"./bouteille_liquide"`
it works perfectly...

But it is not described on any changelogs I have read so far (optifine or vanilla 1.15). So I cannot know if it is a bug or a change. I have already tried to use other prefix instead of `./`, like `~/` or `$/` but nothing works. Nothing weird happened like this in 1.14.x.

## Steps to Reproduce
A custom model texture, with `.properties`, `item_custom.png` and `.json` in the same folder. The `.json` contains thing like : 
```
    "textures": {
        "item": "./item_custom",
    }
```

## OptiFine Version
Optifine 1.15.2 preview22

## Installation Method
Downloaded on running the `.jar` file to create the new version, on standalone.

## Log Files/Crash Reports

**Minecraft game output report** when i put `"./item_custom"` : 
```
Using missing texture, unable to load minecraft:textures/./item_custom.png : java.io.FileNotFoundException: minecraft:textures/./item_custom.png
```

## Prior Testing
It does not happen without optifine because it uses CIT from optifine.

**Comment by Inposa** [comment]
This still occur in pre26.

**Comment by sp614x** [comment]
Fixed in pre29.
