### ISSUE TITLE
[Shaders] separateAo doesn't separate AO

### ISSUE THREAD

**Issue by zombye** [sp614x/optifine#4047]
## Description of Issue
separateAo doesn't actually separate AO from color (as of OptiFine 1.15.2 G1 pre22), instead leaving them merged.

## Steps to Reproduce
1. Load [this shaderpack](https://github.com/sp614x/optifine/files/4741416/vertexColor.zip), which has separateAo enabled and shows `gl_Color.rgb` and `gl_Color.a` on the left and right half of the window/screen, respectively
2. Observe the left & right half of the window/screen.

## OptiFine Version
1.15.2 G1 pre22

## Installation Method
Standalone installer.

## F3 Debug Screenshot
![2020-06-07_07 05 23](https://user-images.githubusercontent.com/9051920/83960809-5188db00-a88d-11ea-9a2d-0e3341e8e52f.png)

**Comment by sp614x** [comment]
Fixed in pre23.

![image](https://user-images.githubusercontent.com/16635441/83966946-c8d66300-a8bd-11ea-9f2b-17137832a56e.png)
