### ISSUE TITLE
[pre-release22] gridlines appear ingame

### ISSUE THREAD

**Issue by Thatengineerl** [sp614x/optifine#4049]
## Description of Issue
gridlines separationg blocks appear while in minecraft

## Steps to Reproduce
join the game

## OptiFine Version
prerealse22 1.15

## Installation Method
dropped jar into mods folder

## Fabric/Forge Version
latest

## OptiFabric Version
latest

## Other Installed Mods
worldedit carpet mod replay mod

## Log Files/Crash Reports
none

You can get logs from `.minecraft/logs`, and crash reports from `.minecraft/crash-reports`. 
Locating your `.minecraft` folder will depend entirely on your OS. See this page for details: https://minecraft.gamepedia.com/.minecraft

**DO NOT directly copy and paste log contents here on GitHub.**

## F3 Debug Screenshot
Minecraft's built-in debug screen provides *a lot* of useful information, and should be included even if the issue is not something that can be captured in a still image.

To open this menu, simply press `F3` on your keyboard while in-game. Please ensure the text is easily readable. Depending on the size/resolution of your monitor, you may have to adjust your GUI scale for all text to be completely visible on-screen.

## Prior Testing
If you've installed standalone:
yes

If you've installed using Forge/Fabric:
no, it does happen when oterh mods are not installed

## Additional Information
none

**Comment by sp614x** [comment]
Lines between the blocks usually appear if there is forced antialiasing or anisotropic filtering in the graphics card control panel. Make sure all settings are set to "Application controlled".
Fabric is not supported.
