### ISSUE TITLE
[1.12.2][shaders] Sky through block cracks / no block breaking animations / wrong animation side when using dynamic trees

### ISSUE THREAD

**Issue by Phoenixdotexe** [sp614x/optifine#4050]
## Description of Issue
With certain shaders enabled, block breaking animations on certain blocks don't trigger or the sky can be seen through them on the incorrect face of the block. They appear on oak wood for me, but not on things like stone, dirt, etc. so far.

## Steps to Reproduce
1. Enable any shaders (tested with Sildur's Vibrant Extreme & Extreme with VL v1.22 where there's no block breaking animation for oak wood and with SEUS renewed 1.0.1 where you can see the sky through the wood cracks on the wrong cube face) and install dynamic trees 0.9.8.

2. Go punch some oak wood.

## OptiFine Version
1.12.2_HD_U_F5

## Installation Method
Dropped the JAR file into my "mods" folder.

## Other Installed Mods
Dynamic trees 0.9.8

## F3 Debug Screenshot
https://imgur.com/YdTuOIX

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
No.

## Additional Information
I'm opening this as an OptiFine issue because these same shaders are working fine on older versions of Minecraft, so I'm assuming it's an OptiFine issue, not a shader issue.

**Comment by sp614x** [comment]
Fixed in pre23.

**Comment by Phoenixdotexe** [comment]
But that's for 1.15.2 not for 1.12.2, right?
