### ISSUE TITLE
[BUG][CEM][Pre 23] Evoker Fangs don't load CEM textures

### ISSUE THREAD

**Issue by ewanhowell5195** [sp614x/optifine#4052]
## Description of Issue
Evoker Fangs do not load textures from the CEM folder

## Steps to Reproduce
Use this model and texture in game and you will see
[evoker_fangs.zip](https://github.com/sp614x/optifine/files/4742862/evoker_fangs.zip)

## OptiFine Version
1.15.2 Pre 23

## 1.14.4
![2020-06-07_21 04 55](https://user-images.githubusercontent.com/48070995/83979345-b1bb6380-a905-11ea-8e88-f28fc0117f3c.png)

## 1.15.2
![2020-06-07_20 38 26](https://user-images.githubusercontent.com/48070995/83979347-b6801780-a905-11ea-8600-89c1a03278fd.png)

**Comment by realjackasterisk** [comment]
title
> [BUG][CEM]**[PRE 22]**

description
> 1.15.2 Pre 20

🤔
which one is it?

**Comment by realjackasterisk** [comment]
100% able to reproduce. still an issue as of pre23

**Comment by ewanhowell5195** [comment]
i wrote the wrong version its pre 22/23 yea

**Comment by ewanhowell5195** [comment]
closing as included in newer issue #4096
