### ISSUE TITLE
Impossible to load Immersive portal 0.20 with optifine pre release 23

### ISSUE THREAD

**Issue by Blugori** [sp614x/optifine#4053]
I tried to launch minecraft with optifine pre release 23 and the mod immersive portal 0.20, but when the game is finishing loading I get this message "error loading mods, 1 error has occured durong loading, immersive portals encountered an error during the sided_setup event phase"
I'm wondering if this is coming from optifine, since it was working with older pre release 22 and with the same mods installed.

I installed optifine by putting the .jar in the mod folder, I'm playing with forge 31.2.0

I tried launching the game with only Forge 31.2.0 / MixinBootstrap 1.0.3 and Immersive portals 0.20, but immersive portal wont load

(Its my 1st time using pastebin and github)
I'll open an issue on the github for immersive portals too

![immersiveportalbug](https://user-images.githubusercontent.com/66573974/83981557-5302e380-a91f-11ea-8d4b-ab797879fe56.PNG)
[my_list_of_mods.txt](https://github.com/sp614x/optifine/files/4743140/my_list_of_mods.txt)

thanks for your concern

**Comment by realjackasterisk** [comment]
please provide `latest.log`

**Comment by Deviouslrd** [comment]
Can confirm its a optifine/immersive portals mod conflict.
Tested on a clean installation of forge, with optifine pre23/mixin 1.0.3/immersive portals 0.20.
Same error appears.

**Comment by Blugori** [comment]
Forgot the latest.log sorry
When I tried to launch it again to get the latest.log I got this screen : 
![crashimmersiveportal](https://user-images.githubusercontent.com/66573974/84016477-9f7d0c00-a97d-11ea-8a92-4c57232e294d.png)

Deviouslrd already provided the log but here's mine 
[latest.log](https://github.com/sp614x/optifine/files/4745163/latest.log)

**Comment by sp614x** [comment]
The Immersive Portals mod would need to be updated to match latest shaders fixes in OptiFine.

```
java.lang.NoSuchMethodError: net.optifine.shaders.Shaders.nextEntity(Lnet/minecraft/entity/Entity;)V
	at java.lang.invoke.MethodHandleNatives.resolve(Native Method)
	at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:962)
	at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:987)
	at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1390)
	at java.lang.invoke.MethodHandles$Lookup.linkMethodHandleConstant(MethodHandles.java:1746)
	at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:477)
	at com.qouteall.immersive_portals.optifine_compatibility.OFInterfaceInitializer.init(OFInterfaceInitializer.java:95)
	at com.qouteall.immersive_portals.ModMainClient.init(ModMainClient.java:85)
```
