### ISSUE TITLE
Multiple textures in one CEM model

### ISSUE THREAD

**Issue by MichalTygrys** [sp614x/optifine#4057]
Hello, I have a little question. Can I somehow use more then one texture in a single CEM file? For example if I wanted to have a 2 layer texture of a pig, where I have a few color textures and a few making textures, that mix reandomly, can I do it by using CEM to have a different mesh overlay normal mesh slightly, with a second texture?

**Comment by ewanhowell5195** [comment]
you can add multiple textures by putting `"texture": ` on each bone you want a different texture on
