### ISSUE TITLE
[CIT] Enchanted Custom Items with animation

### ISSUE THREAD

**Issue by Matteoki** [sp614x/optifine#4062]
## If i make a custom animated texture for swords ecc... and i enchant them, the animation will stop
In "cit" i have:

Sword.png (multiple frames)

Sword.properties=
> type=item
items=minecraft:diamond_sword
nbt.display.Name=ipattern:*OkiSword*

Sword.png.mcmeta=
> { "animation": { "frametime": 3, "frames": [ { "index": 0, "time": 1 }, 1, 2, 3, 4, 5 ] } }

Non-enchanted sword will be animated fine, but if i enchant it with any enchant, the animation (of the sword) stops

## Steps to Reproduce
1. Enchant an item with a custom animated texture
2. The animation will stop

## OptiFine Version

OptiFine 1.15.2 HD U G1 pre23
OptiFine 1.15.2 HD U G1 pre13

## Installation Method
.jar file (optifine.net)

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
You can't do it with Vanilla so...

## Additional Information
I don't speak english very well and this is my first time using github, so...

**Comment by DataCrusade** [comment]
Can confirm, happening to me too

**Comment by Matteoki** [comment]
> may be related to #3753

Thanks you! But  the problem is that I cannot select "render Regions" (it appears dark gray)

**Comment by Matteoki** [comment]
Also, why i can't enable "render regions" "antialiasing" and "anisotropic filtering"?

**Comment by Ioxom** [comment]
They're not working in the 1.15 previews yet.

**Comment by DataCrusade** [comment]
should rename the issue to Enchanted Custom Items with an animation don't play the animation when Smart Animations enabled
