### ISSUE TITLE
AMD RX 580 Seus Shader Crash

### ISSUE THREAD

**Issue by RedCarlos26** [sp614x/optifine#4065]
## Description of Issue
Impossible to load the Seus shader in the 1.15 previews of OpfiFine with an AMD RX 580 graphics card

## Steps to Reproduce
1. Install latest preview on a pc with an AMD RX 580 graphics card
2. Install the latest Seus shader
3. Enable the shader in game
4. The game will crash

## OptiFine Version
All 1.15.2 previews

## Installation Method
Standalone installer

## Prior Testing
Happens with OptiFine only

**Comment by sp614x** [comment]
Crash report, error log?

**Comment by tsl0922** [comment]
Same here,  unresponsive forever, have to force closing it.

Log: https://gist.github.com/tsl0922/76cb2423bf27aea56d04844dadb687f1

**Comment by SARankDirector-Minecraft** [comment]
I am experience the same issue, I can DM sp614x my logs if necessary

**Comment by AhmetEsad** [comment]
I had the same issue, I think disabling RAIN_SPLASH_EFFECT to false fixes that.

**Comment by Mimi4Craft** [comment]
Well actually with the latest drivers from amd 20.8.1 i managed to use :
-The internal shaders
-Continuum-2.0.3
-Sildurs Vibrant Shaders v1.28 Lite to Medium (High instantly crash)

So it seems they fixed a chunk of it but i think that the amd drivers are not compatible with an option on some shaders.

**Comment by RedCarlos26** [comment]
I think this is issue is resolved. I'm no longer crashing.

**Comment by Mimi4Craft** [comment]
Do you know what changed ? Like new amd drivers and/or SEUS/optifine version that fixed that bug ? would be usefull to other people that have the same bug as we did (i cannot confirm because i changed my cg to something else)
