### ISSUE TITLE
[Bug] [1.15.2] [pre-23] CEM Animations not working

### ISSUE THREAD

**Issue by heinrich26** [sp614x/optifine#4067]
## Description of Issue
Defined animations do not apply to the mob in any way

## Steps to Reproduce
1.  Origin translate: `{ "models": [ { "part": "#part", "attach": true, "animations": [ { "#part.ty": 2 } ] } ] }`
moves the origin by 2, works in 1.14.4, but not in 1.15.2

2. random example: `..."animations": [ { "#part:#submodel_id.rx": "sin(time/16)*10" } ]...`
makes the submodel of #part spin with some unknown behavior in 1.14.4, in 1.15.2 nothing happens

I feel thats simple enough, so I don't add images (if you want, i'll add some)

## OptiFine Version
1.15.2 pre-23 and below

## Installation Method
Installer

**Comment by sp614x** [comment]
Fixed in latest preview.
