### ISSUE TITLE
[Random Entities] Custom Optifine EnderDragon Textures Not Working In 1.15

### ISSUE THREAD

**Issue by MANIMANOCAS** [sp614x/optifine#4074]
## Description of Issue
I have an texture pack that changes the dragon texture if it has a certain name in 1.14 it works perfectly but in 1.15 it doenst work the textures dont show up and the dragons appear normal.

## Steps to Reproduce
1. Load a resource pack with a custom enderdragon texture in 1.15 test [HERE](https://www.mediafire.com/file/818s76sywdy7i5h/TEST.zip/file)
2. summon a dragon with the custom name. Commands: /summon minecraft:ender_dragon ~ ~ ~ {NoAI:1b,CustomName:"\"Red\""} and /summon minecraft:ender_dragon ~ ~ ~ {NoAI:1b,CustomName:"\"Orange\""}
3.Test in 1.14 with the same commands and it works in 1.14 but not in 1.15

## OptiFine Version
1.15

## Installation Method
Installed clicking the jar file provided from the optifine site

## F3 Debug Screenshot
1.14
![1 14](https://user-images.githubusercontent.com/42978255/84312137-60f17800-ab5c-11ea-94a4-00820939e1bd.png)
1.15
![1 15](https://user-images.githubusercontent.com/42978255/84312148-63ec6880-ab5c-11ea-9382-e86f0981e753.png)

## Prior Testing
The textures only works with optifine

## Additional Information
the files are all correct because they work in 1.14

**Comment by sp614x** [comment]
The ended dragon model was changed in 1.15:
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/cem_model.txt#L33
