### ISSUE TITLE
[1.15.2 pre24 - 1.16.1 pre13] Colored Banners no longer rendering colors in shaders (SEUS Renewed 1.0.1)

### ISSUE THREAD

**Issue by G4M1NG-N1NJ4** [sp614x/optifine#4084]
## Description of Issue
As of the 1.15.2 pre24 build, Colored Banners are no longer displaying their set colors and are instead rendering in default white.

## Steps to Reproduce
1. Craft and place a Colored Banner. 
2. Enable shaders

## OptiFine Version
1.15.2-OptiFine_HD_U_G1_pre24 - 1.16.1-OptiFine_HD_U_G2_pre13

## Installation Method
Downloaded the .jar file of this build from the "Preview Versions" section on Optifine.net Downloads. "Double-clicked" the downloaded file to bring up the installation GUI. Clicked "Install."

## F3 Debug Screenshot
- Debug Screenshot of Red Banner with shaders disabled: https://1drv.ms/u/s!AlzCHZDR3GRkumw1NRc_XYO6ibQf?e=nQgBfx
- Debug Screenshot of Red Banner with SEUS Renewed 1.0.1 shader enabled: https://1drv.ms/u/s!AlzCHZDR3GRkum36irVrzKCpvc0c?e=Ip0YF7

## Prior Testing
- This issue does not occur with shaders disabled or with the "Internal" shader enabled.
- This issue is present in other shaders (e.g. I also tested Sildurs Enhanced Default 1.11 with the same results)

**Comment by EdgyPotato** [comment]
same with BeyondBeliefLegacy_Final_V1.1

**Comment by naeqirelle2020** [comment]
![2020-06-15_02 24 22](https://user-images.githubusercontent.com/63185833/84609562-67128c00-aeaf-11ea-8c9b-04a441994364.png)

Cannot Reproduce on SEUS however can reproduce on BeyondBeliefLegacy_Final_V1.1

**Comment by G4M1NG-N1NJ4** [comment]
Issue has been resolved with 1.16.1-OptiFine_HD_U_G2_pre14
