### ISSUE TITLE
[Enhancement] Add an option which uses screenspace shaders to render transcluent quads

### ISSUE THREAD

**Issue by yezhiyi9670** [sp614x/optifine#4085]
## Description of the new feature

In 1.16 Mojang added a fabulous graphics option which uses screenspace shaders to render transcluent quads. This fixes most issues about transcluency rendering. The shaders blends every pixel by comparing the depths.

This look fairly simple, and it makes sense (it at least prevents the player's boat from being knocked over by an invisible bubble column).

**Comment by sp614x** [comment]
This is not simple in any way.
Also it is included in vanilla 1.16, no need for OptiFine to add it.

**Comment by yezhiyi9670** [comment]
Yes. After some researches I found it requires major changes.
