### ISSUE TITLE
[1.15.2 pre24] bed texture is broken

### ISSUE THREAD

**Issue by EdgyPotato** [sp614x/optifine#4086]
## Steps to Reproduce
use BBL v1.1 shaders

## OptiFine Version
OptiFine 1.15.2 pre24

## Installation Method
standalone

## F3 Debug Screenshot
![2020-06-13_22 32 09](https://user-images.githubusercontent.com/64056626/84571470-de6bf100-adc5-11ea-9c11-fda816f7c109.png)

## Prior Testing
If you've installed standalone:
no

## Additional Information
Shaders: BeyondBeliefLegacy_Final_V1.1

Pre 23:
![2020-06-13_22 23 38](https://user-images.githubusercontent.com/64056626/84571487-03f8fa80-adc6-11ea-8e9a-8d0524e3ed82.png)

Pre 24:
![2020-06-13_22 21 45](https://user-images.githubusercontent.com/64056626/84571491-078c8180-adc6-11ea-8f90-b54315643c24.png)

**Comment by naeqirelle2020** [comment]
Related to #4084 seems to trigger under the same circumstances (bug triggers depending on angle looked at) can confirm still in latest preview (Pre-26)

**Comment by KdRWaylander** [comment]
Similar texture bug with BSL Shaders (v7.1.04.1) and Optifine pre16/23/26, this time with chest and shulker box texture (top face):

Shader OFF:
![2020-06-15_23 03 39](https://user-images.githubusercontent.com/20188575/84706029-a519b980-af5c-11ea-9a94-1273ccd79cf0.png)

Shader ON:
![2020-06-15_23 03 58](https://user-images.githubusercontent.com/20188575/84706040-aba83100-af5c-11ea-97b2-0984fd2cb16f.png)

**Comment by EdgyPotato** [comment]
> Similar texture bug with BSL Shaders (v7.1.04.1) and Optifine pre16/23/26, this time with chest and shulker box texture (top face):
> 
> Shader OFF:
> ![2020-06-15_23 03 39](https://user-images.githubusercontent.com/20188575/84706029-a519b980-af5c-11ea-9a94-1273ccd79cf0.png)
> 
> Shader ON:
> ![2020-06-15_23 03 58](https://user-images.githubusercontent.com/20188575/84706040-aba83100-af5c-11ea-97b2-0984fd2cb16f.png)

causes by advanced materials

On:
![2020-06-16_10 49 22](https://user-images.githubusercontent.com/64056626/84726378-52bdb480-afbf-11ea-8845-92f3d6ad0f07.png)

Off:
![2020-06-16_10 49 41](https://user-images.githubusercontent.com/64056626/84726389-55200e80-afbf-11ea-8c01-7be95c4e003e.png)
