### ISSUE TITLE
[Suggestion] Block Break Animation Toggle

### ISSUE THREAD

**Issue by XxKoltronxX** [sp614x/optifine#4090]
**Suggestion**
Add "Breaking Particles" and/or "Block Broken Animation"

**Why for this suggestion?**
Helps improve fps and overall smoothness when mining blocks for low-end pcs. It can be optional to switch it on or off. 

**Is this necessary?**
This could help with players disliking or reducing usage on RAM on the client from the Animation where the block breaks/particle it generates when being broken. When mining a block, 2 animations are being used for the block. The small mining particles jumping around and the breaking animation, the crack animation or how long till it breaks. 

**Another Issue**
When mining a block, at random times when block breaks the shadow of the block is whitish than being dark/shadow colour. Not sure if it's Mojang or Optifine side.

**Comment by sp614x** [comment]
The block breaking animation shouldn't affect the performance at all, it is very simple.
The lag spike when mining a block comes from rebuilding the chunks around the player.
