### ISSUE TITLE
[1.15.2] "File not found."

### ISSUE THREAD

**Issue by KTeaBean** [sp614x/optifine#4091]
On the website, under "OptiFine 1.15.2 HD U G1 pre24" Download or (mirror) it says "File not found." and can't be downloaded.

## Steps to Reproduce
1. Go to https://optifine.net/downloads 
2. Click "Preview versions"
3. Click OptiFine 1.15.2 HD U G1 pre24 "Download" or "(mirror)"
4. Click " Download preview_OptiFine_1.15.2_HD_U_G1_pre24.jar"
5. Blank HTML screen saying "File not found."

## OptiFine Version
1.15.2

## Installation Method
Could not install or download.

## Log Files/Crash Reports
None generated

## F3 Debug Screenshot
Error not in game.

## Additional Information
OptiFine 1.14.4 HD U F5 download page works

**Comment by sp614x** [comment]
Pre24 was replaced by pre25.
Reload the download page.
