### ISSUE TITLE
[1.15.2 pre25] Enchanted tridents crash the game

### ISSUE THREAD

**Issue by kimoVoid** [sp614x/optifine#4092]
## Description of Issue
On the latest preview for 1.15.2 (pre25), the game instantly crashes when it has to render an enchanted trident in any inventory/hotbar. Doesn't matter which enchantment is it, it always crashes.

## Steps to Reproduce
1. Get a trident and enchant it with any enchantment (gamemode doesn't matter)
2. Crash!

## OptiFine Version
1.15.2 pre25

## Installation Method
Normal method on Windows. Downloaded the jar, opened it, clicked on Install.

## Log Files/Crash Reports
https://pastebin.com/1p0X3ZSS

## F3 Debug Screenshot
![2020-06-14_18 13 09](https://user-images.githubusercontent.com/29529059/84604228-d3b76780-ae6a-11ea-9ff8-441176326f52.png)

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
No. Not even in pre24.

## Additional Information
This crash only happens on pre25, so even in pre24 it's fine. I've tried resetting my settings too and it still crashes. It crashes every time you render the enchanted trident, no matter where it is (hotbar, inventory, chest, etc)

**Comment by Surawsome** [comment]
Based on the crash log: "Resource Packs: vanilla, file/NewDefault - kimo's edit, file/Void Modifies vTest" are you using a resource pack? If so, try without it and see if you still crash

**Comment by Surawsome** [comment]
I also noticed: "Anisotropic Filtering: 1" This isn't supported yet by the new versions and might be why you're crashing when you're using the resource packs. Go into your .minecraft folder and delete optionsof.txt NOT options.txt and see if this fixes your issue

**Comment by sp614x** [comment]
Fixed in pre26.
