### ISSUE TITLE
[CEM] CEM Animations do not work.

### ISSUE THREAD

**Issue by Beksim** [sp614x/optifine#4093]
## Description of Issue
CEM Animations do not work. Relevent to issue #3422 

## Steps to Reproduce
Try to give a chest a CEM Animation.
[Chest Test.zip](https://github.com/sp614x/optifine/files/4777233/Chest.Test.zip)

## OptiFine Version
Pre25

## Installation Method
Standalone Installer

## F3 Debug Screenshot
![2020-06-14_14 24 45](https://user-images.githubusercontent.com/8078728/84604439-f6398880-ae4a-11ea-9348-bf8c081068d4.png)

## Prior Testing
If you've installed standalone:
No CEM Animations in vanilla.

## Additional Information
Download the pack and try to use it. The lid will not open as its made via a custom animation. Only the Knobs open as they use the vanilla animation at the moment.

**Comment by sp614x** [comment]
Fixed in pre26.
