### ISSUE TITLE
[1.15.2] All CEM issues as of Pre 26

### ISSUE THREAD

**Issue by ewanhowell5195** [sp614x/optifine#4096]
## Description of Issue
This is a list of CEM issues that are exclusive to the 1.15 pre releases. These issues have been introduced within the pre releases themselves as they were working in the past. These issues are not in my previous list: #3971 

## Steps to Reproduce
Here is a link to the pack used for testing: 
[CEM Template.zip](https://github.com/sp614x/optifine/files/4781048/CEM.Template.zip)

## OptiFine Version
1.15.2 Pre 26

## Evoker

`nose` bone doesn't render

![image](https://user-images.githubusercontent.com/48070995/84672406-6e25b280-af20-11ea-96d5-b8e55b07e5e0.png)

## Evoker Fangs

Doesn't load textures from the CEM folder
Models for this one: [evoker_fangs.zip](https://github.com/sp614x/optifine/files/4742862/evoker_fangs.zip)

1.14.4:
![image](https://user-images.githubusercontent.com/48070995/84672596-a1684180-af20-11ea-9f95-847cadba98b2.png)

1.15.2:
![image](https://user-images.githubusercontent.com/48070995/84672609-a62cf580-af20-11ea-8682-b56af0ec8637.png)

## Illusioner

`nose` bone rendering in the wrong position

![image](https://user-images.githubusercontent.com/48070995/84672856-ebe9be00-af20-11ea-8566-64798583f5e7.png)

## Phantom

`head` bone doesn't render

![image](https://user-images.githubusercontent.com/48070995/84672958-06bc3280-af21-11ea-8978-c2482d31ef19.png)

## Pillager

`nose` bone doesn't render

![image](https://user-images.githubusercontent.com/48070995/84673166-3a975800-af21-11ea-9e34-aba3a4c9fe20.png)

## Vindicator

`nose` bone doesn't render

![image](https://user-images.githubusercontent.com/48070995/84673237-5864bd00-af21-11ea-81e5-ca97239397ad.png)

## Other Issues

The `"scale"` tag does not work on JEM models

**Comment by sp614x** [comment]
The end crystal model is rendered scaled:
- base (optional) - scaled 2x
- glass (outer) - scaled 2x
- glass (inner) - scaled 1.75x
- cube - scaled 1.5x

**Comment by sp614x** [comment]
The CEM scaling is currently not working.
