### ISSUE TITLE
CEM animation parser does not recognize the modulo (%) operator

### ISSUE THREAD

**Issue by SN777Divinus** [sp614x/optifine#410]
Associated error message:
[<time>] [Client thread/WARN]: [OptiFine] Error parsing expression: <expression>
[<time>] [Client thread/WARN]: [OptiFine] net.optifine.entity.model.anim.ParseException: Invalid character: '%', in: <expression>

Received error in version: 1.11.2_HD_U_B5

Looking through code, it seems that the percent character is not included in OPERATOR in net.optifine.entity.model.anim.EnumTokenType. I hope this observation helps.

**Comment by sp614x** [comment]
Updated preview B6 for 1.11.2.
Fixed EnumTokenType.OPERATOR to include "%".

**Comment by SN777Divinus** [comment]
The issue seems to be fixed, now. Thanks!
