### ISSUE TITLE
Some emissive textures not working on cross modeled blocks [1.15.2 pre-26]

### ISSUE THREAD

**Issue by CreatorsWorld** [sp614x/optifine#4104]
**Minecraft Version:** 1.15.2
**Optifine Version:** OptiFine 1.15.2 HD U G1 pre26
**Issue:** Some sides of the cross modeled blocks e.g. mushroom, grass etc don't always have an emissive texture.

Custom mushroom texture not showing the emissive layer on one side.
![2020-06-16_16 11 38](https://user-images.githubusercontent.com/32624595/84731158-210f1280-afec-11ea-87db-457961aff286.png)

The same mushroom but from a different angle.
![2020-06-16_16 11 42](https://user-images.githubusercontent.com/32624595/84731164-240a0300-afec-11ea-95b8-42949a00fc7b.png)

This is my configuration for the mushroom:
`matchTiles=brown_mushroom`
`method=random`
`tiles=0-1`
`biomes=Plains`

Both tiles have a regular texture and then a supporting emissive texture with the defined prefix "_e"
Photo of files:
![files](https://user-images.githubusercontent.com/32624595/84731481-14d78500-afed-11ea-9936-1669a626cfe8.png)

**Comment by CreatorsWorld** [comment]
Just thought i'd mention that the textures appear to be working correctly as of pre27.

![2020-06-19_14 16 40](https://user-images.githubusercontent.com/32624595/85089855-c79b2380-b237-11ea-8901-b19d6611cbb7.png)

![2020-06-19_14 16 46](https://user-images.githubusercontent.com/32624595/85089865-ccf86e00-b237-11ea-9f0c-d23466548fe0.png)

**Comment by sp614x** [comment]
Fixed in pre27.
