### ISSUE TITLE
[1.15.2 pre26] No support for Husk CEM?

### ISSUE THREAD

**Issue by Colin-Mueller** [sp614x/optifine#4105]
## Description of Issue
Optifine CEM doesn't seem to support custom models for the Husk mob. They also aren't in the list of entity names and parts in the cem_model doc.

## Steps to Reproduce
1. Create custom jem file for the Husk which includes the parts from the normal model as well as the custom model
2. Use random entity features to make the custom model only shown when given a certain name (I used 128x128 textures, I checked to make sure that the texture size was properly defined)

## OptiFine Version
1.15.2 pre26

## Installation Method
Standalone Installer

## F3 Debug Screenshot
![2020-06-16_02 17 24](https://user-images.githubusercontent.com/59672700/84743952-3d716780-af78-11ea-827d-8e200ba165f8.png)

## Prior Testing
If you've installed standalone:
- No cem support in vanilla

**Comment by ewanhowell5195** [comment]
works fine for me
![image](https://user-images.githubusercontent.com/48070995/92502939-7415f180-f1f8-11ea-8cd0-7024ff1cf965.png)
[husk.zip](https://github.com/sp614x/optifine/files/5189616/husk.zip)

**Comment by ewanhowell5195** [comment]
lol didnt realise how old this was

**Comment by ZenithRogue** [comment]
lol

**Comment by Colin-Mueller** [comment]
ah yea it was never actually broken sorry, I just messed something up in
jem file and never followed up woops

**Comment by ewanhowell5195** [comment]
probably should close the issue then
