### ISSUE TITLE
[1.15.2 pre26] Memory Dump Lag Spikes

### ISSUE THREAD

**Issue by iReebu** [sp614x/optifine#4108]
**Description of Issue**
Every 10 - 20 seconds the memory dumps are causing lag spikes. The minimum FPS often drops down to 10 - 15 for the quarter of a second and it seems to freeze for a moment. It's on every world or server, it's lagging in Single- and Multiplayer.

![OptiFine Lag Spikes](https://user-images.githubusercontent.com/67023706/84822995-e8882c80-b01d-11ea-800d-51e974b02027.gif)

**Steps to Reproduce**
1. Install OptiFine (No changes at Java arguments or settings)
2. Join world/server
3. Play Minecraft and the after the first few dumps the lag spikes will come

**OptiFine Version**
preview_OptiFine_1.15.2_HD_U_G1_pre26

**Installation Method**
standalone installer

**Prior Testing**
Does this happen in Vanilla without OptiFine?
No, everything's smooth in Vanilla, just in OptiFine there're these Lag Spikes.

**Comment by naeqirelle2020** [comment]
this is normal behaviour, it's just how GC works, if you lower the amount of ram you have you can minimize it

**Comment by iReebu** [comment]
Oh, okay. But is the Garbage Collector working in a so different way in OptiFine? Because the issue isn’t in Vanilla, just OptiFine.

**Comment by sp614x** [comment]
The garbage collector is part of the java virtual machine. It can't be controlled by OptiFine. 
You could try to tweak the GC parameters, the results may vary.
