### ISSUE TITLE
After pre24 leads started having a glowing texture

### ISSUE THREAD

**Issue by O-d-i-n-n** [sp614x/optifine#4111]
## Description of Issue
This happens when I use SEUS Renewed 1.0.1

## Steps to Reproduce
1. Turn on SEUS Renewed 1.0.1
2. Use lead on any animal

## OptiFine Version
pre24+

## Installation Method
Standalone installer.

## Other Installed Mods
None.

## Prior Testing
If you've installed standalone:
-This doesn't happen in vanilla OptiFine.

## Additional Information
This bug wasn't present before pre24.

**Comment by EdgyPotato** [comment]
please provide details, not just throw a title and copy the whole description.

**Comment by O-d-i-n-n** [comment]
> please provide details, not just throw a title and copy the whole description.
Just did.

**Comment by sp614x** [comment]
Before pre24 the lead was rendered fully black (no texture) as it was using the wrong program.
This was fixed and now the lead is rendered with texture (brown stripes) as it should be.
No idea why SEUS Renewed renders it brighter as it should be.
Other shaders (SEUS 11, SEUS PTGI, etc.) render it with correct brightness.
