### ISSUE TITLE
[1.15.2] Emissive Textures not working on Activator, Powered and Detector rail

### ISSUE THREAD

**Issue by JustTimmNL** [sp614x/optifine#4117]
Emissive textures for Activator, Powered and Detector rail doesn't work in pre27. https://github.com/sp614x/optifine/issues/4094

**Comment by sp614x** [comment]
Working in pre27.

![image](https://user-images.githubusercontent.com/16635441/85141098-878f6d00-b246-11ea-8001-c5677847556f.png)

**Comment by sp614x** [comment]
Duplicate of #4094.

**Comment by JustTimmNL** [comment]
weird. it doesn't work in my pack and i double checked it..
