### ISSUE TITLE
[CIT] Custom Model in CIT doesn't work.

### ISSUE THREAD

**Issue by JustTimmNL** [sp614x/optifine#4118]
It shows the model but doesn't load the texture. https://imgur.com/a/v2udkhV

**Comment by sp614x** [comment]
Resource pack link?

**Comment by sp614x** [comment]
Relevant #4080, #4046

**Comment by JustTimmNL** [comment]
@sp614x https://wetransfer.com/downloads/4697f9d0a4a468e8cc3460f8223271a320200619134851/4ba60d

**Comment by sp614x** [comment]
Fixed in pre29.
