### ISSUE TITLE
[1.15.2 HD U G1 pre27] Chocapic V8.1 Mipmapping Bug

### ISSUE THREAD

**Issue by naeqirelle2020** [sp614x/optifine#4120]
## Description of Issue
Turning off Mipmapping breaks Chocapic V8.1, tall grass appears invisible and so do leaves

## Steps to Reproduce
1. Turn on Chocapic V8.1_Ultra_Beta
2. Turn off Mipmapping

## OptiFine Version
Optifine Pre_27

## Installation Method
Standalone Installer

## Log Files/Crash Reports
[latest.log](https://github.com/sp614x/optifine/files/4802660/latest.log)

## F3 Debug Screenshot
![2020-06-19_06 51 29](https://user-images.githubusercontent.com/63185833/85101013-56d51680-b1f9-11ea-87fd-6f074307eb86.png)

**Comment by sp614x** [comment]
Chocapic V8.1_beta works correctly in 1.14.4 with mipmaps off.

**Comment by sp614x** [comment]
Are there other shaders with the same problem?

**Comment by naeqirelle2020** [comment]
in my testing i've not been able to find one, i'll give you a list of the shaders i've tried

BeyondBeliefLegacy_Final_V1.1
BSL 7.1.04 & 7.1.05
Chocapic13 V7.1.1
Oceano Shaders
SEUS Renewed
Sildurs Vibrant Shaders V1.26 & 1.27

**Comment by naeqirelle2020** [comment]
tried a few more and the only one else that had an issue was one based on Chocapic 8.1 so i think it's just isolated to that shaderpack

**Comment by Choca13** [comment]
For some reason the alpha cutoff is set to 0.5 instead of 0.1 only when mipmaps are disabled on 1.15

**Comment by sp614x** [comment]
Fixed in pre29.
