### ISSUE TITLE
[1.15.2][Forge] Won't load mod in symbolic link folder

### ISSUE THREAD

**Issue by Passolargo76** [sp614x/optifine#4127]
## Description of Issue
I play Minecraft in multiple PCs, so I created a symbolic link for the mods folder. If I remove the symlink and create mods folder, game loads without issues.

## Steps to Reproduce
1- Create the symbolic link for the mods folder.
2- Run game with forge.

## OptiFine Version
preview_OptiFine_1.15.2_HD_U_G1_pre28
But previus 1.15.2 versions have the same issue.

## Installation Method
Dropped in the mods folder.

## Fabric/Forge Version
Forge 31.1.63

## Other Installed Mods
inventorysorter-1.15.2-17.0.0
LightOverlay-4.6.1
config-2-3.0
Xaeros_Minimap_20.14.0_Forge_1.15.2

Tested with Optifine only, same issue.

## Log Files/Crash Reports
[latest.log](https://github.com/sp614x/optifine/files/4808011/latest.log)

## F3 Debug Screenshot
Minecraft's built-in debug screen provides *a lot* of useful information, and should be included even if the issue is not something that can be captured in a still image.

## Prior Testing
- Does this happen without other mods installed? 
Yes
- Does this happen without any mods at all?
No
- Does this happen in OptiFine standalone?
No
- Does this happen in Vanilla without OptiFine?
No
- Have you tried using a binary search to find which mods cause this issue?
Only happens with OptiFine in the mods folder, any other combination and no issues.

**Comment by sp614x** [comment]
This is a problem of the Forge mod launcher.
Can't be fixed by OptiFine.
