### ISSUE TITLE
[CEM] head_zombie

### ISSUE THREAD

**Issue by RyanCR03** [sp614x/optifine#4128]
## Description of Issue
when changing head_zombie ctm attach is forced true even if explicitly set to false

## Steps to Reproduce
1. create a custom model for zombie head cem (preferably thin and long), set attach to true or not (it doesn't change)
2. place zombie head and see the original model over the custom one

## OptiFine Version
OptiFine HD G1_pre28 Ultra

**Comment by heinrich26** [comment]
Attach has to be false to override the model
