### ISSUE TITLE
[1.15.2 pre-28] Glowing Effect resets CEM defined textures

### ISSUE THREAD

**Issue by heinrich26** [sp614x/optifine#4129]
## Description of Issue
When a Mob has glowing, the texture is defaulted to the vanilla one, even if specified to use another. (CEM)

See:
![2020-06-20_18 08 35](https://user-images.githubusercontent.com/65970327/85206471-b24ef380-b322-11ea-8893-014f6ca5cee0.png) normal CEM model without Glowing
![2020-06-20_18 08 27](https://user-images.githubusercontent.com/65970327/85206473-b9760180-b322-11ea-819a-ec8750475de5.png) corrupeted texture on the same mob

## Steps to Reproduce
1. Make a mob with non-defaulted textures
2. penetrate your mob with spectral arrows

## OptiFine Version
1.15.2

**Comment by ewanhowell5195** [comment]
cant reproduce

**Comment by KaiAF** [comment]
Is this still an issue? Try updating to the recent version of 1.15.
