### ISSUE TITLE
Crash with Cyclops Core (C4, 1.10.2)

### ISSUE THREAD

**Issue by LovelyFlare** [sp614x/optifine#413]
While it happened with an update for Cyclops Core, I thought I'd at least put this issue on here.

CyclopsMC/CyclopsCore#36

**Comment by sp614x** [comment]
Looks like one of the core mods is incorectly patching the TextureAtlasSprite class.
The loaded core mods are:

    SurgeLoadingPlugin (Surge-1.10.2-1.1.0.61.jar)
    FMLPlugin (InventoryTweaks-1.62-dev-66.jar)
    ForgelinPlugin (Forgelin-1.2.0.jar)
    LoadingPlugin (RandomThings-MC1.10.2-3.7.7.jar)
    LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
    AppleCore (AppleCore-mc1.10.2-2.1.0.jar)
    NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
    BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.3.338.jar)
    ChiselCorePlugin (Chisel-MC1.10.2-0.0.7.7.jar)
    EnderCorePlugin (EnderCore-1.10.2-0.4.1.62-beta.jar)
    llibrary (llibrary-1.7.2-1.10.2.jar)
    RebornCoreASM (RebornCore-1.10.2-2.12.1.96-universal.jar)
    SFRCore (SolarFluxReborn_1.10.2-2.4r.jar)
    Brandon's Core (BrandonsCore-1.10.2-2.1.3.82-universal.jar)
    Default Options (DefaultOptions_1.10.2-6.1.5.jar)
    CCLCorePlugin (CodeChickenLib-1.10.2-2.5.1.185-universal.jar)
    ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.6.jar)
    NEICorePlugin (NotEnoughItems-1.10.2-2.1.3.182-universal.jar)
    TransformerLoader (OpenComputers-MC1.10.2-1.6.1.6.jar)
    literalascension (literalascension-1.10.2-1.0.0.3.jar)
    BiomeTweakerCore (BiomeTweaker-1.10.2-2.1.230.jar)

There is a warning about FoamFixAPI, it may be the problem:

    Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again (foamfix-0.5.0-anarchy.jar)

To isolate the problematic mod the crash has to be reproduced with only one core mod installed.

**Comment by LovelyFlare** [comment]
Not caused by CyclopsCore, closing mod.
