### ISSUE TITLE
[1.15.2 pre29] Optifine fails to install

### ISSUE THREAD

**Issue by MisterMcKinney** [sp614x/optifine#4134]
I've tried to install Optifine via Optifine.net, however, when I try to run the .jar file a cmd prompt appears briefly and then disappears. this happens every time I try to run the .jar. I've been thinking that this is either an issue with the optifine Installer or with my Java install. 

I've tried to download  Optifine using both the download button and the Mirror button. I'm not entirely sure what the difference is but I've tried both. I opened the .jar file with my java installation but nothing aside from a cmd prompt appears. 

I've tried this in both the 1.15 pre-releases and in the stable 1.14.2 releases. 

I don't know if I have a mods folder, so I've just been trying to launch the file just as the download. 
I don't use Fabric or forge, and I don't have any mods loaded, including Optifine. 
I haven't gotten to the point where I could get crash logs from either Minecraft or the Minecraft launcher. 
I don't know if I'm somehow installing a fake version of Optifine from what I thought was the official website.

**Comment by Jorkles** [comment]
Run this: https://johann.loefflmann.net/en/software/jarfix/index.html

**Comment by sp614x** [comment]
JarFix should make it work.
