### ISSUE TITLE
[1.15.2 pre29] Chunks not loading with shaders

### ISSUE THREAD

**Issue by SkyeRise** [sp614x/optifine#4135]
## Description of Issue
When moving beyond a certain distance from spawn, chunks won't load beyond a rectangular area. This can reliably be "fixed" with F3+A, creating a new mostly rectangular area around which at a certain distance chunk loading will fail.
This is a new issue because, unlike before, it does NOT affect optifine without shaders anymore, which seems work perfectly fine now.

## Steps to Reproduce
1. Activate any shaders
2. Enter MC world and move away from spawn
3. Chunks won't load beyond a certain area until F3+A is used and then that is the center of a new area beyond which chunks won't load

## OptiFine Version
OptiFine 1.15.2 HD U G1 pre29

## Installation Method
dropped the jar into the mods folder of a Twitch profile

## Fabric/Forge Version
Forge 31.2.21

## Other Installed Mods
Tried it with and without other mods installed. Happens even if it is just Optifine. Using other mods like RandomPatches or Lithium also won't fix the issue.

**Comment by naeqirelle2020** [comment]
Related to #4064

**Comment by SkyeRise** [comment]
@naeqirelle2020 I agree but as stated above the chunk view range won't affect it and it ONLY happens with shaders enabled now which means the issue is far more limited now.

**Comment by SkyeRise** [comment]
There still is the occasional (very rare) chunk hole that can be fixed with F3+A but other than that the chunk loading with shaders is successfully fixed in pre30! Great work Optifine team!
