### ISSUE TITLE
Can't launch any game, crashes before load finishes.

### ISSUE THREAD

**Issue by sibraxlis** [sp614x/optifine#4141]
## Description of Issue
See title.

## Steps to Reproduce
open game, launch a multiplayer server, or a single player world.
## OptiFine Version
1.15.2-OptiFine_HD_U_G1_pre30

## Installation Method
downloaded the file, hit install, let if finish

## Log Files/Crash Reports
https://pastebin.com/t1Jrx1i7

## F3 Debug Screenshot
Can't get that far.

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
No.

It also didn't happen with version pre18

**Comment by sp614x** [comment]
Fixed with a ninja-update, please download pre30 again.
