### ISSUE TITLE
[Bug] Purple and black texture appears when going into first person

### ISSUE THREAD

**Issue by MineDash123** [sp614x/optifine#4144]
## Description of Issue
Going into first person makes the purple and black texture appear
https://user-images.githubusercontent.com/63759839/85236416-5bf5b980-b3e3-11ea-8b60-e31479a54cff.png
https://user-images.githubusercontent.com/63759839/85236417-5c8e5000-b3e3-11ea-823a-993fa9d33363.png

## Steps to Reproduce
1. Go into Minecraft 
2. Go into first person

## OptiFine Version
OptiFine 1.15.2 HD U G1 pre30

## Installation Method
I installed OptiFine by going to https://optifine.net/downloads then clicking preview versions, downloaded the most recent one, waited for ad, then downloaded client.

## Fabric/Forge Version
Forge 31.2.21

## Other Installed Mods
I have WorldEdit and Simple Inventory Sorter installed

## F3 Debug Screenshot
https://user-images.githubusercontent.com/63759839/85236303-87c46f80-b3e2-11ea-973a-5b60dca3f30c.png

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
No

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
Yes

- Does this happen in OptiFine standalone?
No
- Does this happen in Vanilla without OptiFine?
No

**Comment by Deviouslrd** [comment]
Additional note that wasn't included, only appears on pre30 ninja update 1.

**Comment by ocram9** [comment]
Can confirm this wasn't happening before the hotfix. I was able to join my server without crashing and the first person was working correctly.

**Comment by sp614x** [comment]
Fixed in pre33 ninja update 2.
