### ISSUE TITLE
[1.15 pre29] Optifine Preventing Day/Night Cycle

### ISSUE THREAD

**Issue by cat303** [sp614x/optifine#4146]
## Description of Issue
When Optifine is in my mods folder, the day/night cycle in my worlds will break. The sun will progress normally, but then will jump around to other positions in the sky instead of setting. This occurs regardless of other mods, even if Optifine is the only thing in my mods folder, and this occurs regardless of whether or not I have enabled any shaders. Time set commands do not work in this state either, with any commands that would cause the sun to set instead resetting it to the same position as /time set day. The game itself does not recognize anything past this point to be night, effectively rendering several mods unusable.

## Steps to Reproduce
1. Install Optifine to Forge.
2. Load world.
3. Wait for sun to set or use commands.

## OptiFine Version
1.15 pre29, 1.15 pre28, and past versions

## Installation Method
Dropped the JAR file into my mods folder.

## Fabric/Forge Version
1.15.2-forge-31.2.20
I have had this same issue on previous versions as well.

## Other Installed Mods
As stated, this occurs regardless of whether or not other mods are present in the folder.

## F3 Debug Screenshot
Screenshot taken after using /time set midnight
![image](https://i.imgur.com/4o7VcAs.png)

## Prior Testing
I learned that the issue was caused by Optifine by splitting my mods folder repeatedly.

**Comment by asbyth** [comment]
if you press escape, go to video settings, go to other, is time set to day? if so, change it to default

**Comment by cat303** [comment]
It was. Thank you, I don't know how it got set like that unless it's a default for the mod version of Optifine.

**Comment by sp614x** [comment]
The default is "Default" which is the normal day-night cycle.

**Comment by Regnander** [comment]
I guess this is a good time to selflessly promote my suggestion at #1859.
