### ISSUE TITLE
[1.15.2 pre30] "particle.water" in color.properties not working

### ISSUE THREAD

**Issue by SkaliberWasTaken** [sp614x/optifine#4148]
When adding the line "particle.water=X" in color.properties, the texture of water particles is simply not changed. The resource pack I'm using has a custom water colourmap which is being applied correctly to water.

This bug was discovered whilst playing on Optifine 1.15.2 HD U G1 pre30, however, upon further testing it doesn't appear to work on the most recent version of 1.14.4 either.

The documentation appears to be out of date, referencing a "watercolorX.png" in the misc folder, which doesn't appear to exist, at least any more. This extract from the [documentation ](https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/color.properties#L35)can be seen below.

> Base water particle (splashes, bubbles, drops) color.  Biome water color
> multiplier is applied to this value.  The value should match the color of
> your base water texture.  If your base water texture is grey so that you do
> coloring via misc/watercolorX.png, you should set this to ffffff.

![2020-06-22_02 15 09](https://user-images.githubusercontent.com/50083260/85240246-5f169700-b42f-11ea-885c-4b531098e43c.png)

When this screenshot was taken, the file "color.properties" had the line:
`particle.water=FFFFFF
`

Unfortunately I don't have an example of the feature working, and not working, because I cannot get it to work in either the most recent 1.15.2 preview version, or the most recent 1.14.4 full release.

**Comment by Spherey** [comment]
same problem

**Comment by SkaliberWasTaken** [comment]
This was addressed in the colour.properties megathread that was recently closed.
