### ISSUE TITLE
"Optifine cape not found"

### ISSUE THREAD

**Issue by 1azer** [sp614x/optifine#4149]
When ever I try to change or deactivate my optifine cape I keep getting this error
![image](https://user-images.githubusercontent.com/67243793/85241892-34f2b400-b3f2-11ea-8757-fe89c0788995.png)
How do I fix this?

**Comment by ZenIsBestWolf** [comment]
According to the database this is resolved. If you need more assistance, join the Discord for support or shoot us an email.
