### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by SpartanSamuel** [sp614x/optifine#415]
https://github.com/CovertJaguar/Railcraft/issues/1063

When viewing Alloy Smelter recipes in JEI, I crash. Specifically, when I look at the recipes that use the Smelter and I hit page 61-ish. Running without Optifine allows me to see all recipes fine.

MC: 1.10.2
Forge: 12.18.3.2202
Optifine: 1.10.2_HD_U_D4
Crash Log: http://pastebin.com/YrkyscAC

**Comment by sp614x** [comment]
The crash only happens when Anisotropic Filtering or Antialiasing is enabled.
Most probably related to the sprites with custom loader, looking for a bugfix.

**Comment by sp614x** [comment]
Railcraft is manipulating private fields of TextureMap via reflection. Not good.
OptiFine D6 for 1.10.2 is out with a workaround.
