### ISSUE TITLE
[1.15.2 pre30] Block breaking animation not connected to the block

### ISSUE THREAD

**Issue by LarryTheLobster318** [sp614x/optifine#4151]
## Description of Issue
After turning on any shaders, when breaking a block from the side, the breaking animation is shown not connected to the block.

## Steps to Reproduce
1. Load up any world with shaders on.
2. Try breaking some blocks from the side (preferably from an angle)
3. Issue is shown

## OptiFine Version
OptiFine 1.15.2 HD U G1 pre30

## F3 Debug Screenshot
![2020-06-22_03 35 16](https://user-images.githubusercontent.com/23109481/85260913-6e9add80-b439-11ea-87eb-c717c9fe3bcb.png)

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
--No

**Comment by naeqirelle2020** [comment]
![2020-06-23_07 52 38](https://user-images.githubusercontent.com/63185833/85370400-8e5bff80-b526-11ea-9a10-3da3358802fc.png)

can't reproduce

**Comment by Jaari** [comment]
> can't reproduce

You appear to be attempting to break the block from the front, please retry breaking from the side.

**Comment by naeqirelle2020** [comment]
![2020-06-23_14 53 24](https://user-images.githubusercontent.com/63185833/85412273-50300180-b561-11ea-8b4d-e1e4d787e758.png)

done, still can't reproduce

**Comment by LarryTheLobster318** [comment]
> ![2020-06-23_14 53 24](https://user-images.githubusercontent.com/63185833/85412273-50300180-b561-11ea-8b4d-e1e4d787e758.png)
> 
> done, still can't reproduce

Ok, I just tried to recreate the issue again, but it appears to be fixed. I'm pretty sure it was because of a memory leak on my end.

**Comment by sp614x** [comment]
There may have been a ghost block due to server lag or something similar.
Seems to be fixed.

**Comment by LarryTheLobster318** [comment]
![2020-06-23_20 10 58](https://user-images.githubusercontent.com/23109481/85480273-bb8fc880-b58d-11ea-840d-87976fbb50f8.png)
Just found out that it only happens when you have chunk borders showing (F3 +G)

And the breaking texture kinda snaps back into place shown [here](https://gyazo.com/a799f0e7654b5f52857f6e662695da5e)
