### ISSUE TITLE
[1.15.2 pre30] Missing vignette? texture

### ISSUE THREAD

**Issue by HexedHero** [sp614x/optifine#4152]
## Description of Issue
Missing texture overlay in-game
![tU1nPLZ](https://user-images.githubusercontent.com/6012891/85263588-4924c880-b467-11ea-8581-5160eb5897e0.jpg)

## Steps to Reproduce
1. Load into the game

## OptiFine Version
1.15.2 pre30

## Installation Method
Dropped into mods folder using forge

## Fabric/Forge Version
1.15.2 - 31.2.21

## Other Installed Mods
Nothing.

**Comment by BBftw** [comment]
this was fixed in a ninja update to pre30, redownload it to get the fix

**Comment by HexedHero** [comment]
Hmm, I re-downloaded to make sure maybe it's cached for me.

**Comment by HexedHero** [comment]
Cached download
