### ISSUE TITLE
[1.15.2 Preview 30] Turning off Normal Maps breaks Sildurs V1.27

### ISSUE THREAD

**Issue by naeqirelle2020** [sp614x/optifine#4156]
## Description of Issue
Turning off Normal mapping inside the shader selection menu seems to break sildurs v1.27 causing it to have a strange sliding texture effect when moving

## Steps to Reproduce
Turn off Normal Map setting inside shader selection menu
turn on RP Support: Parallax inside normal map settings in sildurs shaders
Turn on Sildurs Vibrant Shaders v1.27 Medium

## OptiFine Version
Pre-30

## Installation Method
Standalone

## Log Files/Crash Reports
[latest.log](https://github.com/sp614x/optifine/files/4817528/latest.log)

## F3 Debug Screenshot
![2020-06-23_07 37 29](https://user-images.githubusercontent.com/63185833/85369299-c7937000-b524-11ea-925a-240573532dcb.png)

## Additional Screenshot
![2020-06-23_07 36 29](https://user-images.githubusercontent.com/63185833/85369366-e7c32f00-b524-11ea-9efb-e81d0da8f15a.png)

**Comment by sp614x** [comment]
The Parallax option in Sildur's Vibrant needs the normal maps in order to work.
It could be fixed by the shader pack if it che checks for macro "MC_NORMAL_MAP".
