### ISSUE TITLE
"uniform sampler2D depthtex0, depthtex1;" does not enable depthtex1

### ISSUE THREAD

**Issue by zombye** [sp614x/optifine#416]
`uniform sampler2D depthtex0, depthtex1;` defines two uniforms, one for depthtex0 and one for depthtex1.
Using this does not result in dephtex1 being enabled.

Defining depthtex1 separately at some point (can be commented out) results in depthtex1 being enabled.

---

This works:
```
uniform sampler2D depthtex0;
uniform sampler2D depthtex1;
```
This also works:
```
/*
uniform sampler2D depthtex1;
*/
uniform sampler2D depthtex0, depthtex1;
 ```
This does not:
```
uniform sampler2D depthtex0, depthtex1;
```

**Comment by sp614x** [comment]
The option parser is relatively simple, it can only recognize single-line definitions of one variable.
It can not recognize:
 - multi-line options
 - several variables at one line
 - lines deactivated by multi-line comments
 - lines deactivated by #ifdef blocks

Single line comments can be used to deactivate an option.

For example the option "depthex1" is detected like this:

    if (line.matches("uniform [ _a-zA-Z0-9]+ depthtex1;.*")
    ...
