### ISSUE TITLE
[Installation] Optifine 1.16?

### ISSUE THREAD

**Issue by Bear73tx** [sp614x/optifine#4162]
## Description of Issue
I am trying to install Optifine 1.16 for Minecraft from https://minecraftupdate.com/optifine/ , which also led me here. The download provided from this link does not seem legitimate. First it asks if I'd like to install "Premier Opinion." Which, through a quick Google search, others have said is a virus. A second additional program also asks to install, and creates a permanent web bar. After all that, whether I agree to those malicious downloads or not, an error occurs and I am asked to try again. I have tried multiple times with no success. 

## Steps to Reproduce
1. Downloaded Optifine 1.16 from link: https://minecraftupdate.com/optifine/
2. Run the installer
3. Decline/Accept Premier Opinion
4. Decline/Accept WebDiscover
5. "Sorry! Error occurred during download process. There was an error while downloading OptiFine_1.16_HD_U_H1 We are sorry for any inconvenience. Please try again later."
6. Close installer; a browser window automatically opens to http://modsfire.download/mods/

## OptiFine Version
1.16

## Installation Method
Standalone installer from link: https://minecraftupdate.com/optifine/

## Other Installed Mods
OptiFine 1.15.2 , Forge 1.15.2

## Additional Information
Why does https://minecraftupdate.com/optifine/ provide a download link when https://optifine.net/downloads does not?

**Comment by michaelts1** [comment]
This is a scam website. There is no Optifine for 1.16.

From the [Optifine subreddit](https://www.reddit.com/r/Optifine/comments/eb73s9/welcome_to_roptifine_please_read_before_posting/):
## Fake Website Warning

This is a reminder that there are only TWO genuine websites to download OptiFine from, and that is
https://optifine.net

and
https://optifined.net

Note the **.net** at the end of both these links. There are several websites that may attempt to copy OptiFine's website design with the usage of incredibly similar URLs and web design. There are also other sites that plainly redistribute OptiFine illegally. The files these sites provide may be packaged with malware, adware, trojans, and many other bad things. Be aware of what sites you're visiting, and always try to check/scan your downloads before using them. Note that all versions of OptiFine are packaged as JAR applications, and not as EXE applications. If you download OptiFine and it comes as a seemingly ordinary EXE, **DO NOT RUN IT.**

Stay safe, everyone.

If you have time, and you happen to come across one of these fraudulent websites, please take a minute to report them to Google Safe Browsing! You can do so via these links:

[Report Malware Pages](https://safebrowsing.google.com/safebrowsing/report_badware/) | [Report Phishing Pages](https://safebrowsing.google.com/safebrowsing/report_phish/)

**Comment by sp614x** [comment]
There is no OptiFine for 1.16 yet.
