### ISSUE TITLE
1.16.1 nether update

### ISSUE THREAD

**Issue by JandJ101** [sp614x/optifine#4164]
Any idea on when optifine will be ready for the nether update?

**Comment by Kassicus** [comment]
Currently sitting at 5%.

You can follow the progress here: https://www.reddit.com/r/Optifine/comments/heho1q/update_116_progress_summary/

**Comment by TheoCGaming** [comment]
OF is now at 8%. Latest progress reports [https://twitter.com/OptiFineNews](here).

**Comment by TheoCGaming** [comment]
WAit a minute

**Comment by yezhiyi9670** [comment]
This can be closed now. Optifine 1.16 preview version has come out.
