### ISSUE TITLE
[CEM] CEM fails to scale in 1.15.2

### ISSUE THREAD

**Issue by ZenithRogue** [sp614x/optifine#4166]
## Description of Issue
CEM models cannot be scaled in any of the preview versions of 1.15.2. Either by means of using `"scale": 2,` or by use of `part.sx, part.sy, or part.sz` in an animation script

## OptiFine Version
OptiFine 1.15.2 previews

**Comment by NitroCipher** [comment]
## Scale Float is present missing from 1.15.2 and 1.16.1:
![image](https://user-images.githubusercontent.com/11393734/86546160-efa5aa80-bef8-11ea-8175-09b1cac6197f.png)

## Present in 1.14.4:
![image](https://user-images.githubusercontent.com/11393734/86546193-1fed4900-bef9-11ea-87b6-beae9e320132.png)

**Comment by Clashbestie** [comment]
It's months and 2 Major Minecraft Versions since this feature is missing how is this still not added back?

**Comment by sp614x** [comment]
The custom model scaling will be added in next 1.18.1 version.
The parameter "scale" will not be added because the vanilla rendering doesn't use scaling anymore.
