### ISSUE TITLE
[1.15.2] Nametag makes the water invisible

### ISSUE THREAD

**Issue by ItzDidoko** [sp614x/optifine#4168]
## Description of Issue
When a player sneaks the nametag makes the water invisible

## Steps to Reproduce
1. You need two players
2. Make the other player sneak
3. Look to the water through his nametag

## OptiFine Version
OptiFine 1.15.2_HD_U_G1_pre30

## Installation Method
Installed via the standalone installer.

## F3 Debug Screenshot
Minecraft's built-in debug screen provides *a lot* of useful information, and should be included even if the issue is not something that can be captured in a still image.

To open this menu, simply press `F3` on your keyboard while in-game. Please ensure the text is easily readable. Depending on the size/resolution of your monitor, you may have to adjust your GUI scale for all text to be completely visible on-screen.

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
No.

## Additional Information
Here are some pics of the bug:
![2020-06-25_14 20 56](https://user-images.githubusercontent.com/36193824/85710731-3d4b3780-b6ef-11ea-995e-4bfb345357bb.png)
![2020-06-25_14 21 00](https://user-images.githubusercontent.com/36193824/85710739-40462800-b6ef-11ea-8a89-e63628b6b053.png)
![2020-06-25_14 21 06](https://user-images.githubusercontent.com/36193824/85710743-41775500-b6ef-11ea-8ddf-a4773f643559.png)
![2020-06-25_14 21 08](https://user-images.githubusercontent.com/36193824/85710755-43d9af00-b6ef-11ea-931d-badf8e543327.png)

**Comment by sp614x** [comment]
This is a vanilla bug.

**Comment by sp614x** [comment]
https://bugs.mojang.com/browse/MC-170252
