### ISSUE TITLE
[1.15.2 pre30] Forge Multi-Layer Models Render Issues

### ISSUE THREAD

**Issue by CyanideX** [sp614x/optifine#4170]
## Description of Issue
Forge multi-layer models to not render correctly; they're missing textures/are invisible.

## Steps to Reproduce
1. Load a forge multi-layer json model.

## OptiFine Version
preview_OptiFine_1.15.2_HD_U_G1_pre30.jar

## Installation Method
MultiMC - mods folder.

## Fabric/Forge Version
Forge 31.2.27

## Other Installed Mods
Mekanism-1.15.2-9.10.8.298-all.jar

## Log Files/Crash Reports
[latest.log](https://github.com/sp614x/optifine/files/4838717/latest.log)
[debug.log](https://github.com/sp614x/optifine/files/4838720/debug.log)

## F3 Debug Screenshot
![2020-06-26_11 31 45](https://user-images.githubusercontent.com/3106700/85890036-73e18a80-b7a1-11ea-9a03-8ad69089cc30.png)
![2020-06-26_11 32 51](https://user-images.githubusercontent.com/3106700/85890044-7512b780-b7a1-11ea-86d3-2baad39c98cf.png)

## Prior Testing
Doesn't occur in vanilla without OptiFine installed (see above screenshots for vanilla vs OptiFine).

## Additional Information
Sample model file: https://pastebin.com/Gw8z3B5h

**Comment by aidancbrady** [comment]
It'd _really_ be awesome if y'all could look into this.

**Comment by CyanideX** [comment]
Issue is resolved with **OptiFine 1.16.1_HD_U_G2_X**.
