### ISSUE TITLE
[1.15.2 pre30] Forge Experimental Light Pipeline - Oversized JSON Models

### ISSUE THREAD

**Issue by CyanideX** [sp614x/optifine#4171]
## Description of Issue
OptiFine appears to override Forge's experimental light pipeline which fixes shading issues on oversized json blocks. This issue occurs with a vanilla json model and is **_not_** using the forge multi-layer json from issue #4170.

## Steps to Reproduce
1. Open Forge config file and set: `experimentalForgeLightPipelineEnabled = true` then run Minecraft.
2. Place oversized json model (1x1x2, for example).

## OptiFine Version
preview_OptiFine_1.15.2_HD_U_G1_pre30.jar

## Installation Method
MultiMC - mods folder.

## Fabric/Forge Version
Forge 31.2.27

## Other Installed Mods
Mekanism-1.15.2-9.10.8.298-all.jar

## Log Files/Crash Reports
[debug.log](https://github.com/sp614x/optifine/files/4839000/debug.log)
[latest.log](https://github.com/sp614x/optifine/files/4839001/latest.log)

## F3 Debug Screenshot
![2020-06-26_12 56 51](https://user-images.githubusercontent.com/3106700/85896740-e6586780-b7ad-11ea-9787-fdbac7998475.png)
![2020-06-26_12 57 44](https://user-images.githubusercontent.com/3106700/85896742-e6f0fe00-b7ad-11ea-9c9c-96092bf0fbd1.png)

## Prior Testing
- Occurs in Vanilla without OptiFine and Forge.
- Models render with lighting issues with just Forge installed, no OptiFine, and `experimentalForgeLightPipelineEnabled = false`.
- When `experimentalForgeLightPipelineEnabled = true`, the models render without lighting issues.
- When OptiFine is installed alongside forge, the lighting issues reappear.

## Additional Information
n/a

**Comment by CyanideX** [comment]
![image](https://user-images.githubusercontent.com/3106700/87213528-8815a380-c2da-11ea-8066-1b2f213936c9.png)

Well, that explains why the issue is occurring. 😅

**Comment by sp614x** [comment]
OptiFine disables the Forge lighting pipeline as it breaks way too many OptiFine features.

**Comment by Biciklee** [comment]
why did u close it if u did not proved any solution? 😤😤😤😤

**Comment by Jkosio23** [comment]
> why did u close it if u did not proved any solution? 😤😤😤😤

because "it breaks way too many OptiFine features." and having an option to disable that override would break the mod entirely
