### ISSUE TITLE
[1.16.5] Broken color.properties megathread

### ISSUE THREAD

**Issue by SkaliberWasTaken** [sp614x/optifine#4173]
Following my previous bug report about the colour of water particles, I've since gone through and checked every single possible entry on color.properties. The simple conclusion is that many of the features are currently broken, and have been since 1.13.

I haven't included any information about the colormap formatting, but I can confirm that those are all currently working fine to my knowledge.

**Working:**
`particle.portal=`
`fog.nether=`
`fog.end=`
`sky.end=`
`lilypad=`
`potion.water=`
`text.xpbar=`
`text.sign=`
`xporb.time=`

All map colours, sheep colours, and collar colours appear to be working, however, it's worth noting that a number of new blocks (such as lanterns) aren't accounted for if trying to change map colours.

For the following demonstrations, I've set the colours of each item to #FFFF00 (yellow) as an easy indicator.

**Not Working:**
`particle.water=`
![2020-06-27_14 29 38](https://user-images.githubusercontent.com/50083260/85923418-be870380-b882-11ea-8b46-61ddd1d5fe73.png)
Rain splash particles appear green, due to the mixing of the yellow, and the additional water colour. My assumption with this issue is that the way that water colouring works changed in 1.13, and therefore this feature is now useless, as it can only be used to haphazardly alter the now fixed splash particle colour.

Potions
![image](https://user-images.githubusercontent.com/50083260/85923473-39501e80-b883-11ea-91fe-3819dd8c3e1f.png)
As mentioned above, the colour for water potions, or the basic default potions does work, however, every other potion is simply not coloured. My guess for this one, is that the flattening brought new ID's for each of the potions, and the naming convention listed on the documentation is simply outdated.

```
potion.absorption=FFFF00
potion.blindness=FFFF00
potion.confusion=FFFF00
potion.damageBoost=FFFF00
potion.digSlowDown=FFFF00
potion.digSpeed=FFFF00
potion.fireResistance=FFFF00
potion.harm=FFFF00
potion.heal=FFFF00
potion.healthBoost=FFFF00
potion.hunger=FFFF00
potion.invisibility=FFFF00
potion.glowing=FFFF00
potion.jump=FFFF00
potion.levitation=FFFF00
potion.luck=FFFF00
potion.moveSlowdown=FFFF00
potion.moveSpeed=FFFF00
potion.nightVision=FFFF00
potion.poison=FFFF00
potion.regeneration=FFFF00
potion.resistance=FFFF00
potion.saturation=FFFF00
potion.unluck=FFFF00
potion.waterBreathing=FFFF00
potion.weakness=FFFF00
potion.wither=FFFF00
potion.water=FFFF00
```

Naming such as "potion.moveSpeed" is very reminiscent of how ID's were handled before the flattening, so I tried simply converting it to "potion.speed" and "potion.movement_speed" and couldn't seem to find anything that worked.

`text.boss=`
![image](https://user-images.githubusercontent.com/50083260/85923547-c4c9af80-b883-11ea-800e-b80082f56e5f.png)
The colouring of signs, and the XP bar seems to work fine, so I imagine this is just a simple inconsistency in naming once again.

`clouds=`
![2020-06-27_14 39 44](https://user-images.githubusercontent.com/50083260/85923568-0e19ff00-b884-11ea-93e3-404bf9aacdc0.png)
It's not inherently clear how this feature is supposed to work, as it's unclear if it simply changes the option for whether clouds are enabled on startup, or if it overrides the setting regardless of whether it's changed by the user. Either way, this feature doesn't seem to work, as clouds are not changed by this line.

Spawn Eggs
![image](https://user-images.githubusercontent.com/50083260/85923593-415c8e00-b884-11ea-86f3-7d25f1f3862c.png)
I imagine this issue is simply the same as with the potions, but for reference, I typed out every mobs ID as it is used in the game, so for example "creeper" "trader_llama" "polar_bear" and none seem to work.

Thank you for taking the time to read through this list. We as a resource pack community hugely appreciate what Optifine brings to the table, and look forward to Optifine for 1.16!

**Comment by sp614x** [comment]
Can you update it for 1.16.1?

**Comment by SkaliberWasTaken** [comment]
![2020-07-12_01 29 31](https://user-images.githubusercontent.com/50083260/87236285-29861d80-c3df-11ea-9bda-5f2d1b606bd3.png)
Water particles are still combining water + the assigned colour

![image](https://user-images.githubusercontent.com/50083260/87236302-63572400-c3df-11ea-89c2-450672f569a6.png)
All potions except water are still broken

![image](https://user-images.githubusercontent.com/50083260/87236348-2c354280-c3e0-11ea-8130-83bb133fa258.png)
Boss text still broken

![image](https://user-images.githubusercontent.com/50083260/87236352-3ce5b880-c3e0-11ea-95ee-9c04ae5dc112.png)
Spawn eggs still broken

From what I can see, nothing has changed, the post is still completely up to date (:

**Comment by SkaliberWasTaken** [comment]
Can confirm that these issues still exist in 1.16.2.

**Comment by IgorEstevao** [comment]
any updates on this issue?

**Comment by Cart3r1234** [comment]
spawn eggs are still broken, but I am not sure about potion colors

**Comment by EliasDev1** [comment]
Spawn eggs still seem to be broken, aswell as potion colors.

Somehow my white sheeps changed color, but the rest didn't, without modifying the texture...

Working on this for some time now.

**Comment by TheHardew** [comment]
> \# Banners use the general map colors.
> \# The banner colors can not be configured separately from the map colors.

My banners did not change colors, but maps did.

**Comment by ChaosDogG** [comment]
Custom spawn eggs worked in 1.14.4 ik that for a fact, but in the latest version they mega broken

**Comment by ewanhowell5195** [comment]
bump

**Comment by ThisGreenDingo** [comment]
This problem seems to stem to banners as well, general map colors are not effecting them in the slightest.

**Comment by thiagogebrim13** [comment]
please fix this

**Comment by calcastor** [comment]
> 
> 
> This problem seems to stem to banners as well, general map colors are not effecting them in the slightest.

I'm having this issue in 1.12, however not in 1.8 with the latest possible versions of Optifine.

**Comment by sp614x** [comment]
The base water particle color was white before, now it is blue from the biome.
Fixed the custom color to overwrite the biome color:
![image](https://user-images.githubusercontent.com/16635441/111197316-a1d05e80-85be-11eb-8d6d-66288df50d08.png)

When rendering the color is multiplied with the texture color. 
This is why the red particles have black parts, in the particle texture the red channel is near zero:
![image](https://user-images.githubusercontent.com/16635441/111197666-08557c80-85bf-11eb-9924-da53f699207c.png)

**Comment by sp614x** [comment]
The `clouds` setting works as expected. 
It controls the clouds when the GUI option "Clouds" is set to `Default`.

**Comment by sp614x** [comment]
The potion colors control the color of the potion effect particles, the potion item can be changed by CIT.
In 1.16 the potion particle format has been changed to "potion.minecraft.<name>=<color>".
Fixed the parsing to recognize the extended format.

**Comment by sp614x** [comment]
Fixed spawn egg colors

**Comment by sp614x** [comment]
Fixed the boss text color

**Comment by SkaliberWasTaken** [comment]
This is all very good to see! Will the nether fog colour be moved to the colourmap as opposed to being a single set value?

It's worth noting that the end also has multiple biomes, so a colourmap for fog would make more sense than a single set value.

**Comment by sp614x** [comment]
Added terracotta and nether blocks in map colors.
Fixed dye colors and banner colors.

**Comment by sp614x** [comment]
@SkaliberWasTaken please make a new issue for the nether/end fog colormaps.
The end sky color can also get a colormap.
