### ISSUE TITLE
[1.8.9 L5] Turning off sky in settings while using shaders makes sky white

### ISSUE THREAD

**Issue by neb15161718** [sp614x/optifine#4177]
## Description of Issue
Please provide as much detail as possible.

I used Sildurs Enchanced Default 1.11 and turned off sky in optifine settings and the sky and void turned white. 

I used version 1.8.9 L5

It happens with forge and standalone installer

Forge 1.8.9 2318 or just optifine

![2020-06-28_20 37 44](https://user-images.githubusercontent.com/49074896/85956688-59650800-b97f-11ea-9445-a97ecee69af8.png)

It happens with most shaders i tried

**Comment by sp614x** [comment]
This depends on the specific shader pack. Some need the sky to be rendered, others can render the sky at the end.
Can't be fixed by OptiFine.
