### ISSUE TITLE
[every Version] [CEM] CEM Animation entity parameters (floating) not useable

### ISSUE THREAD

**Issue by heinrich26** [sp614x/optifine#4181]
## Description of Issue
Simple as the header, it's not possible to work with (some of) the floating parameters. 

Example: I'm tryna use `move_forward` for a movement animation, so I tried couple methods: 
```"model:submodel.variable": "if(move_forward == 1, some numbers, other numbers)"```

```"model:submodel.variable": "if(move_forward > 0, some numbers, other numbers)"```

```"model:submodel.variable": "if(move_forward = 1, some numbers, other numbers)"``` not working cause of the =

If I'm just doing it wrong, it would be cool to have better documentation on that part of animating, same for the booleans, as its not clear how to use them (is_wet == true, or however it works) ;)

## Steps to Reproduce
Use Floating ones

## OptiFine Version
I tested 1.14.4 and 1.15.2

**Comment by ewanhowell5195** [comment]
these have been removed from the documentation now. these values are server side only and never sent to the client
