### ISSUE TITLE
GeForce Experience not working

### ISSUE THREAD

**Issue by agentwildfire** [sp614x/optifine#4188]
I noticed that my GeForce experience is not working ingame in minecraft on the 1.15.2 pre_17 optifine or newer.( The oldest version of 1.15.2 optifine i had was pre_17 and the newest pre_30).
When i launch minecraft without optifine, it works fine without any hassle.
Also as a side issue, my Logitech G Hub software is not working with only minecraft so if there is a fix for that please let me know.(I did add the path of the game to the java executables as well.)
![Screenshot (416)](https://user-images.githubusercontent.com/57621403/86221474-01541e80-bb96-11ea-901d-aeb4461dcab1.jpg)

**Comment by sp614x** [comment]
No idea how GeForce Experience or Logitech G Hub detect Minecraft.
Experimenting with their settings could help.
