### ISSUE TITLE
[1.15.2 Pre30] spider_eyes random texture not working

### ISSUE THREAD

**Issue by xProBomb** [sp614x/optifine#4189]
I've tried getting spider eye varients to work and they simply do not, I've tried many ways to get it to work in Pre30 and it does not, I've also tried the same texture pack in 1.14 and it does work, however.

Optifine HD G1_pre30 Ultra 1.15.2

Installer and forge with mods and without
Forge version 1.15.2 - 31.2.29

Other mods, Biomes o' plenty Quark

**Comment by xProBomb** [comment]
Apon further testing, Enderman Eyes have the same problem

**Comment by fyreaken** [comment]
Can confirm this still happens in 1.16.1 pre1 and pre2. Been messing with it for a few days with no working spider_eye texture change.

**Comment by Kid-Justice** [comment]
phantom eyes dont work either

**Comment by AndrewIdot** [comment]
can confirm this also doesn't work in 1.19 pre4.
