### ISSUE TITLE
Texture replace do not work with any other language [Bug]

### ISSUE THREAD

**Issue by WhiteWolfy** [sp614x/optifine#419]
Hello guys! I hope it is a bug and could be fixed! I already sent a letter to optifinex@gmail.com, but I think here is more chance to my problem will be noticed. So!  I have very terrible problem and I hope you will answer me and fix that! http://www.planetminecraft.com/texture_pack/blue-haven-items-v11-item-customization-using-optifine/  this one I watned to use this way to my server, but it seems like it does not work with Russian language! It only works with English names of items for me. I renamed "nbt.display.Name=ipattern" line with russian symbols and it does not work in the game.. So with English all fine. I also using color code, but with English its still fine with that :( So I hope you can fix that guys! Or.. I just do not know what I should do then :(

**Comment by WhiteWolfy** [comment]
Heeey? I need to know, should I hope you will fix that or not :(

**Comment by WhiteWolfy** [comment]
So enchancement? If you mean that way to fix my problem then I cannot agree that.. Because it is not good way. I don't need any enchantment on these items :( And also it will be stupid, because we have only few enchantments, so we cannot make as much items as we want.. Also.. No words to say, it will be just stupid to use only enchants for custom textures. So can you please answer fine, can you fix that and make other languages support? May be it is encoding problem or something.. I just REALLY need to know, and I REALLY cannot use only enchants :(

**Comment by WhiteWolfy** [comment]
So as I can notice by your label it is not bug? oO.. So.. When it will come? :(

**Comment by sp614x** [comment]
Which items are not working with russian language?
Do you want to use russian language for the "nbt.display.Name" matching?
Example properties which are not working?

**Comment by WhiteWolfy** [comment]
Thank you for an answer! Give me a moment, I will find that example which did not work. Here it is! 

http://rgho.st/private/8vcrrVthN/ef88a4369b196975f24e6d71ebd2f5b5

So I tried to change texture by name from this texture pack 

http://www.minecraftforum.net/forums/mapping-and-modding/resource-packs/2646006-itembound-v1-4-winter-holiday-update-custom-item

So with English I got all fine even with color code, but with Russian I did not have any result, texture just still as default :(

**Comment by WhiteWolfy** [comment]
So if you can't (have no time for example) to test it out by yourself I can send you some screenshots, but I think you have no reason to do not believe me. I just wanted that way to change texture working on any language, but with Russian it does not :(

**Comment by WhiteWolfy** [comment]
Can you answer please? This thing is really important for my server :( I can see you answering to other people and ignoring my question :( Sorry for being such officious, but it is reeeally important and I cannot decide some things without your answer :(

**Comment by sp614x** [comment]
The properties files use by default encoding ISO-8859-1 which can not be used with cyrillic characters.
You can use "\uXXXX" escape to add cyrillic or other unicode characters.
For example "Юя" can be given as "\u042E\u044F".
Online convertor: http://www.freeformatter.com/java-dotnet-escape.html

**Comment by WhiteWolfy** [comment]
Yeah, I tested it now with your way, it works fine! Thank you very much! <333
