### ISSUE TITLE
Game Crashes when trying to load shaders (1.12.2)

### ISSUE THREAD

**Issue by weerab301** [sp614x/optifine#4191]
shaders - Seus v11.0 
have also tried Seus renewed but it also crashed
Optifine - OptiFine 1.12.2 HD U F5
Modpack - MC eternal 
Errors - .... i got over 200 errors when i tried to load the shaders

**Comment by Podrock-ian** [comment]
I think this is fixed in 1.12.2 HD U F6 pre1

**Comment by weerab301** [comment]
i think it may be something to do with my mod pack as it works when i apply the shaders to vanilla 1.12.2
