### ISSUE TITLE
[BUG][1.16.1 Pre 1] Custom Loading Logo doesn't load

### ISSUE THREAD

**Issue by ewanhowell5195** [sp614x/optifine#4192]
Replacing the `mojangstudios.png` logo located in `assets/minecraft/textures/gui/title/` doesnt work in 1.16

![image](https://user-images.githubusercontent.com/48070995/86486832-4aea6800-bd54-11ea-990a-432d0c4f7383.png)

![image](https://user-images.githubusercontent.com/48070995/86486850-50e04900-bd54-11ea-8676-a102971b3ad2.png)

Optifine 1.16.1 pre 1

**Comment by sp614x** [comment]
Fixed in pre2.
