### ISSUE TITLE
[Bug] Fabulous not there for shaders and Entity Distance not there at all

### ISSUE THREAD

**Issue by Gaukh** [sp614x/optifine#4194]
## Description of Issue
**With OptiFine for 1.16.1 I cannot select the "Fabulous" graphics option if shaders enabled, there is only Fast and Fancy available. Also, the entity distance slider is not there.**

## Steps to Reproduce
**1. Try to switch the graphics option with shaders**
**1. ... try to find the entity distance slider? :D**

## OptiFine Version
**OptiFine 1.16.1 pre1**

## Installation Method
**Normal installation via "install" option of the .jar**

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
**No**

**Comment by AbsolofDarkness** [comment]
I think it does explicitly say that shaders are not supported with the Fabulous graphics option. I assume this is because of how the Fabulous setting works

**Comment by sp614x** [comment]
Fabulous graphics is not compatible with shaders.

**Comment by sp614x** [comment]
Entity Distance added in pre2 under Performance.
