### ISSUE TITLE
[BUG] Custom skies not working in 1.16.1 optifine,

### ISSUE THREAD

**Issue by Borous** [sp614x/optifine#4195]
Custom skies appear to not be functional,

I've tried on multiple resourcepacks that had custom skies working in 1.15.2,

Optfine Version:
1.16.1-Optifine_HD_U_G2_pre1

Installation Method
Tried both the standalone installer and via forge,

Fabric/Forge Version
Forge 32.0.25

No other mods installed during

![2020-07-03_18 51 08](https://user-images.githubusercontent.com/55432790/86487407-3e6b0d00-bd5e-11ea-8383-cc3e8375eacf.png)

**Comment by schrodingerspsycho** [comment]
![2020-07-03_21 08 11](https://user-images.githubusercontent.com/61247526/86488328-b7279480-bd71-11ea-83e4-fe87f475200a.png)
![2020-07-03_21 07 31](https://user-images.githubusercontent.com/61247526/86488358-d0c8dc00-bd71-11ea-9633-915f2790b435.png)

![2020-07-03_21 06 42](https://user-images.githubusercontent.com/61247526/86488347-c6a6dd80-bd71-11ea-880a-e90aec154456.png)
mine works alright, installer, no forge, shaders on

**Comment by AbsolofDarkness** [comment]
Are you running a resource pack that supports custom sky-boxes? With the image you provided it looks like you aren't running a resource pack. Have you also updated any of the resource packs you tested?

Also... Forge is out for 1.16.1 already???

**Comment by sp614x** [comment]
Works for me:

![image](https://user-images.githubusercontent.com/16635441/86499278-a6374d00-bd8a-11ea-892a-a9f44fadafc0.png)

**Comment by Borous** [comment]
Alright, I sort of found out what was happening, but it doesn't make it more clear to me, 

apperantly, it works fine on singleplayer, and multiplayer servers, 
but just not on my private paper spigot server,

I honestly don't have the slightest clue how a server, that doesn't even have a server resourcepack setup in the server.properties, is affecting this.
