### ISSUE TITLE
[Bug] Antialiasing makes hotbar completely white

### ISSUE THREAD

**Issue by Goat2442** [sp614x/optifine#4201]
## Description of Issue
Please provide as much detail as possible. I Turned on AntiAliasing and it made the hotbar completely white

## Steps to Reproduce
1. What do you do... Turn on antialiasing
2. ...to find this bug? Turned on antialiasing

## OptiFine Version
Self-explanatory. 1.16.1 pre 1

## Installation Method
How did you install OptiFine? Did you use the included standalone installer, or did you drop the JAR file into your "mods" folder? Standalone

## Log Files/Crash Reports
Any relevant log files. Drag and drop text files here to upload to GitHub directly, OR upload the complete contents to Pastebin. https://pastebin.com/

You can get logs from `.minecraft/logs`, and crash reports from `.minecraft/crash-reports`. 
Locating your `.minecraft` folder will depend entirely on your OS. See this page for details: https://minecraft.gamepedia.com/.minecraft

**DO NOT directly copy and paste log contents here on GitHub.**

## F3 Debug Screenshot
Minecraft's built-in debug screen provides *a lot* of useful information, and should be included even if the issue is not something that can be captured in a still image.

To open this menu, simply press `F3` on your keyboard while in-game. Please ensure the text is easily readable. Depending on the size/resolution of your monitor, you may have to adjust your GUI scale for all text to be completely visible on-screen.

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine? no

## Additional Information
Here goes any final remarks and everything else that might not fit in the previous sections.

**Comment by sp614x** [comment]
Fixed in pre2.
