### ISSUE TITLE
Optifine pure white hotbar

### ISSUE THREAD

**Issue by waterlemon1667** [sp614x/optifine#4203]
Hi I recently installed the preview version of optifine 1.16.1 and my Hotbar is entirely white I'm not sure why I've tried multiple things like uninstalling and reinstalling optifine and etc I'm fully aware there can be many bugs and things like that but I'm wondering if there's any way to fic as I've asked other people and they have not had the same issue 
Thanks!

**Comment by TropheusJ** [comment]
Turn off antialiasing in shader settings or press f4

**Comment by sp614x** [comment]
Fixed in pre2.
