### ISSUE TITLE
[Bug] Some Shaders not displaying enchanted items properly

### ISSUE THREAD

**Issue by shal0l** [sp614x/optifine#4205]
## Description of Issue
SEUS Renewed v1.0.1 and Chocapic13 V8
> SEUS Having issues displaying enchanted Crossbows and Potions
> Chocapic Having issues with all enchanted items

## Steps to Reproduce
Hold any item/certain items that have an enchantment / enchantment animation with the mentioned shaders.

## OptiFine Version
OptiFine 1.16 HD G2 pre_1 Ultra

## Installation Method
Mod folder

## Forge Version
Forge 32.0.25

## Other Installed Mods
None

## F3 Debug Screenshot
![2020-07-03_16 53 55](https://user-images.githubusercontent.com/67803583/86495070-2d1a0480-bd4e-11ea-9aab-694ccd415729.png)
![2020-07-03_16 56 02](https://user-images.githubusercontent.com/67803583/86495080-360ad600-bd4e-11ea-87ed-1ce155eb8f9e.png)

## Prior Testing
- Does this happen without other mods installed? 
Yes
- Does this happen in Vanilla without OptiFine?
No

## Additional Information
Sildurs Vibrant Shaders seems to be fine. Haven't tested any other shader.
AA is off.

**Comment by Piko72** [comment]
Is it only that shader?

**Comment by shal0l** [comment]
> Is it only that shader?

These are two major shaders with the issue. I haven't tested but there might be others with this issue.
