### ISSUE TITLE
[Bug] (1.16) Error when opening game.

### ISSUE THREAD

**Issue by sirbnjmn** [sp614x/optifine#4207]
The game crashed whilst rendering screen
Error: org.spongepowered.asm.mixin.injection.throwables.InjectionError: LVT in net/minecraft/class_757::method_3192(FJZ)V has incompatible changes at opcode 549 in callback net/minecraft/class_757::renderScreen.

something to do with the game background?

**Comment by sp614x** [comment]
Looks like a conflict with some other mod, running with Fabric.
Can't be fixed by OptiFine. Fabric is also not supported.

**Comment by schrodingerspsycho** [comment]
Are you using RoughlyEnoughItems by a chance? If so - it gives the same crash.
