### ISSUE TITLE
(Small Bug) Shaders doesn't save when you use ESC to close the screen.

### ISSUE THREAD

**Issue by IBinary1337** [sp614x/optifine#421]
When you select your shaderpack, and then you use ESC to close your shaders screen, the shaders doesn't save to optionsshaders.txt.
This is because the shaders is only saved when you press "Done", but not when you ESC out.
A possible fix would be to save the shaders when you select it.

**Comment by essem2** [comment]
its the same for ressourcepacks and everything else because ESC is a cancel button. so i would say: works as intended

**Comment by dotModded** [comment]
You could make the argument saying then why is it when I click a shader from off it loads the shaders mod before clicking done locking up your game for a bit.

**Comment by essem2** [comment]
and this argument would be a feature request and not a "bug"-report like the reporter reported. the reporter said that the cancel-feature is a bug and should be removed.

**Comment by sp614x** [comment]
Updated preview B7 for 1.11.2.
Fixed shaders to save optios on ESC.
