### ISSUE TITLE
[Rendering] 1.16.1 Nether Portal makes chunk borders obvious (With shaders)

### ISSUE THREAD

**Issue by descisgay** [sp614x/optifine#4210]
## Description of Issue
When standing infront or behind a nether portal and looking through the portal block(s) everything turns a purple hue, this is fine and to be expected, however the "fog" completely disappears and the render distance fog breaks, dont know if this is how my shader is working or if it's optifine. (I wasnt having this issue in older versions of optifine/minecraft) Maybe i'm just being nit picky, i dont know

## Steps to Reproduce
1. Go to the nether with any shaders (I use Seus Renewed)
2. Look through the portal blocks and observe your render distance.

## OptiFine Version
1.16.1 G2 pre1

## Installation Method
Standalone version.

## Log Files/Crash Reports
Can't think of any logs that'd be of use.

## F3 Debug Screenshot
![image](https://user-images.githubusercontent.com/28230233/86496147-09ed5600-bd4a-11ea-99fb-4fbf3c7e5350.png)

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
No.

## Additional Information
Like I said earlier, dunno if it's just the shader being buggy, or if it's just optifine being an early version. I dont experience this in older optifine versions.

**Comment by sp614x** [comment]
This depends on the shader pack. 
It controls how the translucency is calculated and how the fog is applied.
