### ISSUE TITLE
Parrot death causes crash in optifine 1.16.1 pre1.

### ISSUE THREAD

**Issue by ZeroNoey** [sp614x/optifine#4214]
I was playing on a creative realm when one of the members decided to make a contraption that spans and explodes parrots. All of us kept on crashing except the one non-optifine user in the realm. We tested it for a bit and it seems that parrot death in any way causes the crash.

Version: 1.16.1-Optifine_HD_U_G2_pre1

**Comment by fyreaken** [comment]
Can confirm this is happening on optifine 1.16.1 pre2 aswell

**Comment by eiglow** [comment]
I can also confirm this on 1.16.1 pre2. The crash isn't immediate, it happens about 1 second after the parrot death.

**Comment by yezhiyi9670** [comment]
[Crash Report](https://pastebin.ubuntu.com/p/rgqvvp8b6M/)

It's about random entities.

**Comment by yezhiyi9670** [comment]
> I can also confirm this on 1.16.1 pre2. The crash isn't immediate, it happens about 1 second after the parrot death.

It's the time when the parrot entity disappears.

**Comment by sp614x** [comment]
Fixed in pre3.
