### ISSUE TITLE
[BUG] Stuck in Elytra in Nether

### ISSUE THREAD

**Issue by 2438gray** [sp614x/optifine#4218]
## Description of Issue
While using the Elytra in the Nether it kept me in flying mode. Things that I tried to fix it... Taking off Elytra, Opening to LAN to get into creative mode and fly back home. 
It recognized that I was walking though which was weird. Gravity seemed like it was halved too, didn't feel like the usual way Elytra's fly. Good thing I backed up first. 

## Steps to Reproduce
Flying in the Nether with Elytra and rockets.

## OptiFine Version
1.16.1

## Installation Method
Standalone I believe but not sure

## Fabric/Forge Version
**If OptiFine is installed as standalone, you can remove this section.**

## OptiFabric Version
**If OptiFine is installed as standalone, or you're using Forge, you can remove this section.**

## Other Installed Mods
Nothing
![Screenshot (35)](https://user-images.githubusercontent.com/67809577/86501076-58efb700-bd5b-11ea-8940-144701c438c5.png)

**If OptiFine is installed as standalone, remove this section.**

## Log Files/Crash Reports
Any relevant log files. Drag and drop text files here to upload to GitHub directly, OR upload the complete contents to Pastebin. https://pastebin.com/

You can get logs from `.minecraft/logs`, and crash reports from `.minecraft/crash-reports`. 
Locating your `.minecraft` folder will depend entirely on your OS. See this page for details: https://minecraft.gamepedia.com/.minecraft

**DO NOT directly copy and paste log contents here on GitHub.**

## F3 Debug Screenshot
Minecraft's built-in debug screen provides *a lot* of useful information, and should be included even if the issue is not something that can be captured in a still image.

To open this menu, simply press `F3` on your keyboard while in-game. Please ensure the text is easily readable. Depending on the size/resolution of your monitor, you may have to adjust your GUI scale for all text to be completely visible on-screen.

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   - Only OptiFine and Forge
   - Only OptiFine, OptiFabric, and Fabric
- Does this happen without any mods at all?
   - Only Forge/Fabric by itself.
- Does this happen in OptiFine standalone?
- Does this happen in Vanilla without OptiFine?
- Have you tried using a binary search to find which mods cause this issue?
   - To find conflicting mods, split your mods into 2 groups (not including OptiFine/OptiFabric, obviously). Remove one group, and test in-game. Keep the group that has the problem, and repeat until no more mods can be removed without the issue disappearing.
   - Does the issue still happen with only the remaining mods installed?
      - Forge/Fabric and remaining mods, without OptiFine

## Additional Information
Here goes any final remarks and everything else that might not fit in the previous sections.

**Comment by 2438gray** [comment]
Also, I can't die if I jump in lava

**Comment by 2438gray** [comment]
Game froze when Saving world too lol

**Comment by 2438gray** [comment]
After force quitting and getting back into the world it spawned me in a place I was in earlier just before I used the Elytra.

**Comment by Ioxom** [comment]
Optifine doesn't affect gameplay, this is definitely not an OptiFine-related issue.

**Comment by yezhiyi9670** [comment]
Can you reliably reproduce it?

It's very likely a rare internal server lag.

**Comment by sp614x** [comment]
Most probably a vanilla bug: https://bugs.mojang.com/browse/MC-90026
OptiFine generally doesn't change the gameplay mechanics.
