### ISSUE TITLE
[Bug] Error trying to switch graphics to fabulous

### ISSUE THREAD

**Issue by WantaSanchez** [sp614x/optifine#4219]
## Description of Issue
Error trying to switch graphics to fabulous

## Steps to Reproduce
1. Change graphics type to fabulous

## OptiFine Version
1.16.1 Pre 2/Pre 1

## Installation Method
Standalone installer

## Log Files/Crash Reports
[latest.log](https://github.com/sp614x/optifine/files/4871856/latest.log)
[crash-2020-07-04_02.25.01-client.txt](https://github.com/sp614x/optifine/files/4871855/crash-2020-07-04_02.25.01-client.txt)

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
- No.

**Comment by kyraex** [comment]
Does it crash? If you meant you can't switch to Fabulous (as in not available as you clicked through) that means you have your shaders enabled. Fabulous settings are not compatible with shaders thus if you need to switch to it you have to disable your shaders first and vice versa.

**Comment by sp614x** [comment]
Fabulous graphics is not compatible with shaders, as it says in the tooltip.
