### ISSUE TITLE
[Emissive Textures] Enchantment Glint doesn't render on emissive textures at all

### ISSUE THREAD

**Issue by SeaOfPixels** [sp614x/optifine#4222]
## Description of Issue
The enchanting glint doesn't render over the emissive glow on items in all perspectives. It also does not render in the inventory, or on armor/elytra models.

## Steps to Reproduce
1. Enchant an item/armor that uses emissive textures.

## OptiFine Version
Optifine 1.15.2 pre30, OptiFine 1.16.5 HD U G6

## Installation Method
optifine.net > double left click > install

## Other Installed Mods
None

## Additional Information
Really want to see this fixed, because it ruins the aesthetic of enchanted emissive items.

**Comment by SeaOfPixels** [comment]
Can someone please bump this? I feel like this is a very important visual bug to be fixed but this bug report hasn't garnered much attention.

**Comment by SeaOfPixels** [comment]
If it helps, this feature seems to work correctly in 1.14 Optifine. I suggest the reason it is broken now is because the vanilla enchantment glint was made emissive in 1.15 (thus breaking the Optifine's emissive overlay). No idea why it is only a problem in first person & the inventory though.

**Comment by SeaOfPixels** [comment]
Has any progress been made towards patching this?

**Comment by SeaOfPixels** [comment]
Will this bug be fixed any time soon?

**Comment by SeaOfPixels** [comment]
I'd really like to see this finally fixed for 1.16.4 G6, as it really plagues my popular resource pack New Default+.

**Comment by PrimoTuyo** [comment]
**please fix it!**

**Comment by PrimoTuyo** [comment]
please fix it!

**Comment by Aurelien30000** [comment]
Please try to fix it, thanks :)

**Comment by SeaOfPixels** [comment]
Thank you for adding this bug to the "todo" section. I hope to see it fixed soon, that would be super awesome.

**Comment by sp614x** [comment]
I tried to fix it once, but it was too complicated.

**Comment by SeaOfPixels** [comment]
By making the emissive layer transparent, the enchanted layer starts to show through. This means that the emissive layer is being rendered above the enchantment glint rather then below. I assume this is the issue because in 1.15 the enchantment glint was made emissive, thus breaking the interaction with OptiFine's emissive textures. If you're able to somehow switch the emissive layer to rendering under the vanilla enchantment glint, I believe this theoretically would solve the issue.

**Comment by SeaOfPixels** [comment]
Or maybe try having OptiFine disable the emissive-ness of the vanilla enchantment glint, so that the OptiFine emissive can work properly with no conflictions.

**Comment by sp614x** [comment]
Fixed emissive enchanted items and emissive bed.
Coming in next preview.
