### ISSUE TITLE
[CIT] Custom models don't work with CIT

### ISSUE THREAD

**Issue by SeaOfPixels** [sp614x/optifine#4223]
## Description of Issue
Custom models don't work with CIT items.

## Steps to Reproduce
1. Create a custom model for a CIT item

## OptiFine Version
***This is an issue in 1.16.1 pre1 (both with standalone Optifine and Forge), but is ONLY an issue in 1.15.2 pre30 when playing with Forge***

## Installation Method
optifine.net > double left click > install

## Other Installed Mods
None

## Additional Information
Really want to see this fixed. You're awesome sp614x.

**Comment by FrancescNosas** [comment]
Can confirm, I've been having the same issue

**Comment by V4L0R0US** [comment]
Myself and many others can also confirm this and it happens in 1.14.4 as well.

**Comment by JustTimmNL** [comment]
> Myself and many others can also confirm this, and it happens in 1.14.4 as well.

It works in 1.14. This is 1.16 what we are talking about.

**Comment by V4L0R0US** [comment]
> > Myself and many others can also confirm this, and it happens in 1.14.4 as well.
> 
> It works in 1.14. This is 1.16 what we are talking about.

Oh my bad, it actually doesn’t work in 1.14.4 when you try to use CIT packs and forge mods at the same time, I should’ve clarified. You’re 100% right though, it does work when using Optifine alone.

**Comment by JustTimmNL** [comment]
You didn't say that but your right. I see it. I never use mods :P

**Comment by Beksim** [comment]
Bumping this. Hopefully this gets fixed soon.

**Comment by sp614x** [comment]
Fixed CIT models (standalone and with Forge).
Coming in pre13.
