### ISSUE TITLE
[Bug] Cannot enable Fabulous! graphics option with Optifine 1.16.1

### ISSUE THREAD

**Issue by mistershkolnik** [sp614x/optifine#4226]
I can't enable Fabulous! graphics option with optifine 1.16.1. That's it.

**Comment by XenonZed** [comment]
What's your GPU? If using a graphics card unsupported by Fabulous graphics, the game normally displays a warning that must be accepted before switching modes. This screen doesn't show up when using OptiFine's menu, preventing the graphics setting from being switched. Another consequence of this is that it also prevents users from switching the game's default graphics setting from Fancy to Fast if their graphics card doesn't support Fabulous graphics.

**Comment by david92003** [comment]
I have the same issue. In G2 pre1 the Fabulous option isn't even listed in that setting's description. In pre2 it is, however I still can use it, it only switches between fast and fancy. There was no warning pop-up with or without OptiFine. I'm using a 1650S.

**Comment by ewanhowell5195** [comment]
you have to turn off shaders to access it

**Comment by sp614x** [comment]
Fabulous graphics is not available when shaders are enabled.
