### ISSUE TITLE
Certain blocks not rendering with Fabulous Graphics

### ISSUE THREAD

**Issue by Beatso1** [sp614x/optifine#4227]
## Description of Issue
Chests, shulker boxes, signs and ender chests do not render and are just invisible with the Fabulous graphics option turned on. Their hitboxes are still there and I can interact with them. This is not just non-opaque blocks, because redstone dust and repeaters do render. This works fine in fast and fancy graphics.

## Steps to Reproduce
Place down one of the blocks listed above. It will be invisible

## OptiFine Version
OptiFine 1.16.1_HD_U_G2_pre2

## Installation Method
Using OptiFabric. Dropped both OptiFabric and OptiFine .jar files into my mods folder.

## Fabric/Forge Version
fabric-loader-0.8.9+build.203-1.16.1

## OptiFabric Version
optifabric-1.1.0-beta2

## Other Installed Mods
fabric-api-0.14.1+build.372-1.16
malilib-fabric-1.16.1-0.10.0-dev.21+arne.1
minihud-fabric-1.16.1-0.19.0-dev.20200701.005153

## F3 Debug Screenshot
[link to image](https://www.dropbox.com/s/ffuvm7ls4mfb1k2/2020-07-04_11.02.12.png?dl=0)

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine? No
- Does this happen without other mods installed? 
   - Only OptiFine, OptiFabric, and Fabric: Yes
- Does this happen without any mods at all?
   - Only Forge/Fabric by itself: No
- Does this happen in Vanilla without OptiFine? No

**Comment by yezhiyi9670** [comment]
Can't reproduce with OptiFine only or with Forge.

**Comment by sp614x** [comment]
Problem with OptiFabric.
OptiFabric is not supported.

**Comment by yezhiyi9670** [comment]
It's not only Fabulous which causes the issue. It's Fabulous and Fast Render.

Maybe they should be marked as incompatible temporarily.
