### ISSUE TITLE
[BUG] Swimming bug

### ISSUE THREAD

**Issue by Frozi334** [sp614x/optifine#4228]
## Description of Issue
So, when I swim in water and try to use **SPRINT** to swim faster, I just can't do that. My character can't swim forward with sprint and this is only in optifine. 

## Steps to Reproduce
1. Go into the water **(exactly deeper)**
2. Try to swim forward with sprint

## OptiFine Version
preview_OptiFine_1.16.1_HD_U_G2_pre2 (32.0.14)

## Installation Method
When I downloaded optifine, I just put the file in the “mods” folder

## Fabric/Forge Version
Forge

## Other Installed Mods
I only had optifine installed

## F3 Debug Screenshot
file:///C:/Users/Илья/AppData/Roaming/.minecraft/screenshots/2020-07-04_14.06.15.png

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
_- No_

**Comment by sp614x** [comment]
Works for me, when pressing Left-Control underwater the character starts swimming faster:

![image](https://user-images.githubusercontent.com/16635441/87229702-b4005a00-c3aa-11ea-9357-93270a643668.png)
