### ISSUE TITLE
Negative worldTime values for worlds older than MAX_INT ticks

### ISSUE THREAD

**Issue by Builderb0y** [sp614x/optifine#423]
This works out to ~3.4 years, and a server that I play on happens to have a world this old. I suspect this may be caused by the cast to int on line 3076 in Shaders.class (according to JD-GUI). `setProgramUniform1i("worldTime", (int)worldTime % 24000);` I'm no java expert, so I'm not entirely sure what happens when casting a long this large to an int, but the value I get according to shaders is inaccurate at best and negative at worst, which can screw up a lot of things. This can be reproduced by opening your level.dat file and setting "DayTime" to a ridiculously large value like 1 trillion.

**Comment by sp614x** [comment]
Really interesting.

**Comment by sp614x** [comment]
Updated preview B7 for 1.11.2 with a bugfix.
