### ISSUE TITLE
[Shaders] Applying shaders in Optifine 1.16.1 Pre2 causes crash

### ISSUE THREAD

**Issue by TomTomTomTomTo** [sp614x/optifine#4230]
## Description of Issue
Applying shaders in optifine 1.16.1 Pre2 causes a crash.

## Steps to Reproduce
1. Apply shader, in menu or in-game
2. Wait for it to load during the Mojang screen (enter a world if done in menu) and it will crash.

## OptiFine Version
release 1.16.1-Optifine_HD_U_G2_pre2

## Installation Method
Used java installer, installed into minecraft directory.

## Log Files/Crash Reports
[hs_err_pid6156.log](https://github.com/sp614x/optifine/files/4872881/hs_err_pid6156.log)

## F3 Debug Screenshot
![2020-07-04_15 23 09](https://user-images.githubusercontent.com/67829962/86513414-513b1b80-be0a-11ea-82c2-fc7b7a9a9ff5.png)

## Prior Testing
If you've installed stand-alone:
This does not happen in vanilla (no shader support in vanilla)

## Additional Information
I'm not sure if there are any specific shader packs available that work with this version, but I'm just trying to use the latest version of SEUS renewed.
After a game restart with certain shaders, they do manage to apply in-game, but switching shaders will cause another crash, so does changing ANY shader settings.

**Comment by sp614x** [comment]
```
# Problematic frame:
# C  [atio6axx.dll+0xb42e80]
```
This is a crash in the AMD graphics driver.
Upgrading or downgrading the graphics driver may help.
Can't be fixed by OptiFine.
