### ISSUE TITLE
Buggy Mess After CLosing F-3

### ISSUE THREAD

**Issue by Thatengineerl** [sp614x/optifine#4232]
## Description of Issue
Buggy mess after closing F3

## Steps to Reproduce
1. SHIFT + F3
2. F + 3

## OptiFine Version
1.16 pre 2

## Installation Method
jar mods

## Fabric/Forge Version
latest

## OptiFabric Version
latest

## Other Installed Mods
replay mod
chat up
carpet mod
litematica
malib
shulker box tool tip

## Log Files/Crash Reports
no crash files

## F3 Debug Screenshot
![2020-07-04_09 37 58](https://user-images.githubusercontent.com/66556390/86513849-8bd98f80-bddb-11ea-92d3-a7a945e0180b.png)

To open this menu, simply press `F3` on your keyboard while in-game. Please ensure the text is easily readable. Depending on the size/resolution of your monitor, you may have to adjust your GUI scale for all text to be completely visible on-screen.

## Prior Testing
If you've installed standalone:
No

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
yes

## Additional Information
no

**Comment by sp614x** [comment]
Fabric is not supported.
Any bugs should be fixed by OptiFabric.
