### ISSUE TITLE
Crimson and warped forest terrain particle don't work

### ISSUE THREAD

**Issue by olek128** [sp614x/optifine#4233]
## Description of Issue
Crimson and warped forest terrain particle don't work

## OptiFine Version
1.16.1 pre2

## Installation Method
standalone installer

## F3 Debug Screenshot
![Zrzut ekranu (71)](https://user-images.githubusercontent.com/30731835/86514760-569d6380-be14-11ea-9751-e6693df76a4a.png)

**Comment by sp614x** [comment]
Duplicate of #4253
