### ISSUE TITLE
[BUG] Custom skies not fuctioning in 1.16.1 multiplayer servers

### ISSUE THREAD

**Issue by Borous** [sp614x/optifine#4237]
yesterday, I posted a report on custom skies not functioning properly in optifine 1.16.1, However, I did not test if it worked on singleplayer, and it, infact did.

However, from what I have found until now, it seems as if custom skies do not function within a multiplayer inviorment, 
though, I am uncertain if this is with all 1.16.1 multiplayer servers, or perhaps spigot servers specifically, as the only 1.16 servers I've managed to find so far all use a multitude of plugins. 

I tested all this with both OptiFine 1.16.1 HD U G2 pre2, and OptiFine 1.16.1 HD U G2 pre1.
both via the installer, and via forge,

**Comment by Borous** [comment]
as an addition, with 1.16.1 servers, I mean servers that actually run 1.16.1, so not servers such as hypixel, that allow 1.16.1 users to play, but internally run on older versions,

**Comment by sp614x** [comment]
Some servers like hypixel report the dimension as "minecraft:overworld" and custom sky works correctly there.
Other servers report it as "minecraft:spawn" or "custom:lobby" so it can't be identified as overworld (world0).
Not something that OptiFine can fix.

**Comment by Borous** [comment]
I see, and how exactly is that documented within server files, is it in the overall world properties or such?

**Comment by Borous** [comment]
But this confuses me, 

Before 1.16.1, I had a server running on 1.15.2, which has several worlds on it using the multiverse plugin, 

Only one of those worlds is actually named in file minecraft:world, the rest all had different uniqe names, 
and yet, custom skies worked there, it seems like this issue has only arisen since 1.16.1
