### ISSUE TITLE
[Bug] CEM biome entity works improperly with the new nether biomes

### ISSUE THREAD

**Issue by Pizzachu22** [sp614x/optifine#4239]
## Description of Issue
When trying to use CEM per biome with an entity, one texture is applied to all models

## Steps to Reproduce
1. Install OF 1.16 pre2
2. Create a biome-based entity using CEM
3. set the biome to one of the new nether biomes
4. Spawn the entity in any biome

## OptiFine Version
1.16 pre2

## Installation Method
Standalone optifine

## F3 Debug Screenshot
Minecraft's built-in debug screen provides *a lot* of useful information, and should be included even if the issue is not something that can be captured in a still image.

To open this menu, simply press `F3` on your keyboard while in-game. Please ensure the text is easily readable. Depending on the size/resolution of your monitor, you may have to adjust your GUI scale for all text to be completely visible on-screen.

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
No, as it requires optifine.
![2020-07-04_13 17 19](https://user-images.githubusercontent.com/62914638/86517676-ce5d9500-bdf8-11ea-8eef-ede176ba1653.png)

## Additional Information
The texture in the image is supposed to be reminiscent of the "moobloom" from Minecraft Earth, not resembling the warped fungus.

**Comment by ewanhowell5195** [comment]
give him the pack to test with

**Comment by Pizzachu22** [comment]
[pack.zip](https://github.com/sp614x/optifine/files/4873635/pack.zip)
This is the pack in question, the only issue right now is with the aforementioned CEM entities

**Comment by ewanhowell5195** [comment]
also test it without cem because i think this is just a random entities issue and has nothing to do with cem. if it still happens without, it is unrelated to cem, if its fixed, its cem related

**Comment by olek128** [comment]
I think problem is in texture pack in
[red_mooshroom.properties]
where

skins.3=4
_**biomes.4**_=warped_forest

should be

skins.3=4
_**biomes.3**_=warped_forest

**Comment by Pizzachu22** [comment]
> I think problem is in texture pack in
> [red_mooshroom.properties]
> where
> 
> skins.3=4
> _**biomes.4**_=warped_forest
> 
> should be
> 
> skins.3=4
> _**biomes.3**_=warped_forest

what are you, some kind of genius? That's what the issue was apparently.
