### ISSUE TITLE
Shaders: Skip clear buffers doesn't work

### ISSUE THREAD

**Issue by DethRaid** [sp614x/optifine#424]
@dotmodded and I have been working on temporal raytracing by using the ability to not clear some buffers to accumulate ray samples. In doing this, we have discovered that not clearing buffers is somehow not working in the slightest.

You can see all our code at https://github.com/Continuum-Shaders/Pure_PBR/tree/broke. Specifically, check out https://github.com/Continuum-Shaders/Pure_PBR/blob/broke/shaders/composite2.fsh#L261 and on. You'll see that we read in the color from the previous frame buffer (which in our case is colortex2), mix it with the current frame's color, and write the result to colortex0, which finds its way onto the screen. You'll also see that we write a pure white color to the previous frame buffer.

The expected behavior of this is that we'll see an image that is a 50/50 mix of the current frame's color and a pure white color. What we see instead looks like motion blur. You can see a screenshot at http://i.imgur.com/5EHsDs0.png. You'll notice that you can see three or four ghosts of the lime green wool block in my hand. This result makes no sense to either me or @dotmodded, and we're really hoping you can help us out.

**Comment by williammalo** [comment]
[reduced-test-case.zip](https://github.com/sp614x/optifine/files/715414/reduced-test-case.zip)
I have the same problem

**Comment by dotModded** [comment]
[temporal not working.zip](https://github.com/sp614x/optifine/files/715434/temporal.not.working.zip)

This should cause a tail however it does not. I have for some reason been able to get this working however.

In this example I am writing 0.5 to the buffer however it is just showing previous frame data. 
[temporal working but not with the correct data at all.zip](https://github.com/sp614x/optifine/files/715438/temporal.working.but.not.with.the.correct.data.at.all.zip)

**Comment by zombye** [comment]
Here's a minimized version of the "sort of working but wrong data" test case @dotModded provided 
[temporal working but not really.zip](https://github.com/sp614x/optifine/files/715504/temporal.working.but.not.really.zip)

I've changed buffer formats to RGBA8 as for some reason that produces pretty much endless trails, changing them to RGBA16 or RGBA32F (and probably other formats) fixes it. I guess this might have to do with reading and writing to the same buffer, but buffer formats shouldn't affect that.

**Comment by zombye** [comment]
I've done a bit more testing, here's what I've found out:

It actually works. In one specific situation.

Here's what I was using: 
[temporal actually working.zip](https://github.com/sp614x/optifine/files/716995/temporal.actually.working.zip)

It appears that you need to write whatever you want on the next frame in the last composite pass before final, provided that pass is not also the first time you write that data to that buffer.

I suppose it makes sense that you'd need to write it in the last composite pass, but you definitely shouldn't need to write it in more than one pass.

**Comment by Strum355** [comment]
+1
we shader devs are confused about some of the features you've added in Optifine. Could you come to our Discord server and help clear some things up? We think if youre going to work on optifine and working on giving the shader community features, we very highly recommend that you join the discord server. It would be most benificial to us, as you will better understand our needs, and you will recieve faster feedback as well as more precise requests. We hope you dont ignore this, as we would very much like to work with you closer on integrating useful features for shader devs into optifine
Link: [https://discord.gg/RpzWN9S](url)

**Comment by sp614x** [comment]
The optional clear is implemented like this:

    for (int i = 2; i < usedColorBuffers; ++i)
    {
      // Check clear disabled
      if(!gbuffersClear[i])
        continue;
      // Clear
      glDrawBuffers(GL_COLOR_ATTACHMENT0_EXT + i);
      glClearColor(0.0f, 0.0f, 0.0f, 0.0f);
      glClear(GL_COLOR_BUFFER_BIT);
    }

**Comment by sp614x** [comment]
Minimal working case: 
[SkipClearWorkingMin.zip](https://github.com/sp614x/optifine/files/743436/SkipClearWorkingMin.zip)

**Comment by sp614x** [comment]
Adding additional composite stages does not affect the clear, it still works: [SkipClearComposite3.zip](https://github.com/sp614x/optifine/files/743478/SkipClearComposite3.zip)

**Comment by sp614x** [comment]
Currently the skip clear is not implemented for gcolor and gdepth (0 and 1).

**Comment by sp614x** [comment]
Implemented skip clear for gcolor and gdepth (0 and 1) in OptiFine 1.11.2_HD_U_B7.
