### ISSUE TITLE
[Bug] I can't activate Fabulous graphics.

### ISSUE THREAD

**Issue by luciobortoletto** [sp614x/optifine#4242]
## Description of Issue
When I click on "Graphics" I can only select Fast and Sophisticated, not Fabulous.

## Steps to Reproduce
1. Click on "Options...".
2. Click on "Video Settings...".
3. Click on "Graphics": You can only select Fast and Sophisticated.

## OptiFine Version
OptiFine 1.16.1 HD U G2 pre2. 

## Installation Method
I installed OptiFine using the included standalone installer.

## Log Files/Crash Reports
Log: https://pastebin.com/Qf2jffbv

## F3 Debug Screenshot
https://imgur.com/a/dl6psLC

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine? No, it doesn't happen.

## Additional Information
I think I've put in all the necessary information.

**Comment by kyraex** [comment]
You need to disable your shaders. Shaders are not compatible with fabulous graphic settings. I disabled and it allowed me to switched to Fabulous.

**Comment by luciobortoletto** [comment]
Thank you!
