### ISSUE TITLE
Torch in offhand turns black with shaders

### ISSUE THREAD

**Issue by Bagel-kun** [sp614x/optifine#4243]
![image](https://user-images.githubusercontent.com/67841940/86520424-05cc4180-bdf9-11ea-8e75-250791e54c18.png)

I was in the nether at a low level and my torch turned black.

**Comment by sp614x** [comment]
More details needed:
- OptiFine version
- installed standalone or with Forge/Fabric
- other mods installed
- debug screenshot (F3)
- etc.

**Comment by KaiAF** [comment]
If this is still an issue, let me know. Please provide the needed details that sp614x listed.
