### ISSUE TITLE
[Bug] Player Model Invisible with Third-Person Toggled.

### ISSUE THREAD

**Issue by drewisbad** [sp614x/optifine#4245]
## Description of Issue
Please provide as much detail as possible.
When third person is toggled, the player model is not visible. 
## Steps to Reproduce
1. toggle perspective in-game. The default button is F5.

## OptiFine Version
OptiFine 1.16.1_HD_U_G2_pre2

## Installation Method
I used the standalone installer.

## F3 Debug Screenshot
Minecraft's built-in debug screen provides *a lot* of useful information, and should be included even if the issue is not something that can be captured in a still image.

To open this menu, simply press `F3` on your keyboard while in-game. Please ensure the text is easily readable. Depending on the size/resolution of your monitor, you may have to adjust your GUI scale for all text to be completely visible on-screen.
[https://imgur.com/a/4WzK8um](url)
## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
No.

## Additional Information
Here goes any final remarks and everything else that might not fit in the previous sections.

**Comment by sp614x** [comment]
Fixed in latest preview.
