### ISSUE TITLE
[Bug] Running optifine with lithium on fabric crashes singleplayer world (MacOS)

### ISSUE THREAD

**Issue by 1Krista** [sp614x/optifine#4248]
## Description of Issue
Optifine (with/without shader) with lithium crashes singleplayer world. Multiplayer works fine though.

## Steps to Reproduce
1. Open a game on OSX with optifine, optifabric, lithium, and fabric api installed.
2. Open a single player world created in vanilla minecraft or create a new world with mods above.
3. Game load up to 100%, Says 'Saving world', and crashes

OptiFine 1.16.1 HD U G2 pre2
Optifabric 1.1.0 beta 2
Lithium mc1.16.1 0.5.0
Fabric api 0.14.1 build 372 1.16
fabric loader 1.16.1 0.8.8 build 202
OSX Catalina 10.15.5

## Log Files/Crash Reports
[crash-2020-07-05_13.48.02-client copy.txt](https://github.com/sp614x/optifine/files/4874530/crash-2020-07-05_13.48.02-client.copy.txt)

**DO NOT directly copy and paste log contents here on GitHub.**

## F3 Debug Screenshot
Debug screenshot is not possible.

## Prior Testing
Lithium works without optifine.

## Additional Information
Here goes any final remarks and everything else that might not fit in the previous sections.

**Comment by Miros77** [comment]
me too

**Comment by Miros77** [comment]
on Windows

**Comment by MrVenom0** [comment]
Sadly fabric is not supported.

**Comment by sp614x** [comment]
Fabric is not supported.
Has to be fixed by OptiFabric.

**Comment by LeWolfYT** [comment]
Will we have to work around this using all mods that optifine is made of?
