### ISSUE TITLE
Some way to know the current day in shaders

### ISSUE THREAD

**Issue by zombye** [sp614x/optifine#425]
Or at least a way to know how old a world is if it's older than 8 days.

Having something like `uniform int worldDay;` would be great for persistent effects that don't snap back to the start after a fairly short amount of time (~2.66 hours).

**Comment by sp614x** [comment]
There is "moonPhase" which is similar, it loops after 7 days.

**Comment by mindforger** [comment]
there is an NBTTag Time on the level.dat counting in ticks

**Comment by sp614x** [comment]
The world age in ticks is too big for the shaders (long).
World age in days (float) makes more sense.
What kind of effect do you want to use it for?

**Comment by zombye** [comment]
The main thing this would be used for is varying conditions over time, for example some days being very foggy compared to other days. That sort of effect would ideally be done over a very long time, longer than what you can get from moonPhase.

But it would be used for anything that needs to take place over a long time, or occurs rarely and shouldn't happen on a clear pattern.

**Comment by Builderb0y** [comment]
> The world age in ticks (long) is too big for the shaders.

Irrelevant, since MAX_INT minecraft days is roughly 81,716 real-life years. Even the last issue I made that had issues with worlds older than MAX_INT ticks doesn't come anywhere close to this. This is a day counter after all, not a tick counter.

> World age in days (float) makes more sense.

Assuming floats in GLSL are 32-bit, then you'd actually get LESS precision than an int here since some of those bits are used to store the exponent.

**Comment by Strum355** [comment]
@zombye  use moonPhase and then add/subtract random numbers from a 1D noisetex, or procedural noise.
also quick note i looked at your tonemap in ozius, should look at the graph it makes. It aint working like a proper tonemap, values going above 1.0

**Comment by zombye** [comment]
@Strum355 That only works for 8 day long cycles. As I have already stated, I want something that's longer than that. Also, I'm already using moonPhase for time.

As for the tonemap I'm using in ozius, [this is a graph of it.](https://www.desmos.com/calculator/wbgskwfwk6) It's really just a basic reinhard with a power applied to the input and output.

**Comment by sp614x** [comment]
Updated preview B7 for 1.11.2.
Added uniform worldDay = worldTicks / 24000L.
