### ISSUE TITLE
[Bug] Clouds keep sticking to the screen when you turn clouds off (Optifine 1.16.1 HD U G2 pre2)

### ISSUE THREAD

**Issue by NaiNonTH** [sp614x/optifine#4251]
## Description of Issue
Whenever you turn off the clouds setting, Clouds don't get away and keep sticking to the screen unless you relaunch Minecraft again.

## Steps to Reproduce
1. Go to Options > Video Settings > Set Graphics into _Fabulous!_
2. Go to Options > Video Settings > Details... > Set Clouds into Off
3. You'll see that clouds keep sticking to the screen unless you relaunch Minecraft again.
## OptiFine Version
Optifine 1.16.1 HD U G2 pre2. 

## Installation Method
Optifine Standalone installer

**Comment by NaiNonTH** [comment]
This may along to Optifine's source code. So no logs include.

**Comment by sp614x** [comment]
Fixed in pre3.

**Comment by NaiNonTH** [comment]
> Fixed in pre3.

Thank you sp614x.

Also, take your time. I'll wait.
