### ISSUE TITLE
Optifine 1.14.4 crashes after loading

### ISSUE THREAD

**Issue by Czeczen1113** [sp614x/optifine#4252]
After i start Minecraft 1.14.4 or 1.15.2 with optifine, right after the mojang logo the game crashes. It says it's something about texture packs, i tried everything, including default minecraft texture pack, the game runs fine without OF, and it was all ok until about a week ago, when the game just crashed, and i was forced to play without OF. Is there anything i can do about it?

here is the crash log
[crash-2020-07-05_15.00.18-client.txt](https://github.com/sp614x/optifine/files/4874948/crash-2020-07-05_15.00.18-client.txt)

**Comment by sp614x** [comment]
```
Unable to fit: minecraft:burning_skull, size: 128x128, atlas: 0x0, atlasMax: 0x0 - Maybe try a lower resolution resourcepack?
```
The maximum supported texture size is reported as 0.
Upgrading/downgrading the graphics drivers may help.
