### ISSUE TITLE
[1.16.1-pre2] Nether particles not appear

### ISSUE THREAD

**Issue by OverBrave** [sp614x/optifine#4253]
## Description of Issue
Orginal Minecraft
![image](https://user-images.githubusercontent.com/47111280/86533689-78ade900-bedb-11ea-9b92-8756459139ed.png)

Optifine
![image](https://user-images.githubusercontent.com/47111280/86533668-56b46680-bedb-11ea-9db4-23116dd63195.png)

Nether particles not appear

All particles are open.

## OptiFine Version
[1.16.1-pre2]

## F3 Debug Screenshot
![2020-07-05_16 22 57](https://user-images.githubusercontent.com/47111280/86533729-d3dfdb80-bedb-11ea-8018-f6ccf6e102fa.png)

**Comment by yezhiyi9670** [comment]
I cannot reproduce it.

**Comment by Exolirating** [comment]
I have also had no issues. Maybe try and reinstall the game and optifine???

**Comment by espen96** [comment]
got the same issue

**Comment by pibblepower** [comment]
got the same problem.

**Comment by ginganinjacat** [comment]
For me, soulsand valley and basalt delta ambient particles still appear as normal. Only the crimson forest and warped forest particles are missing.

**Comment by sp614x** [comment]
Fixed in pre3.
