### ISSUE TITLE
[Issue] Optifine crashes minecraft on fabric with mods that use mixinlibrary

### ISSUE THREAD

**Issue by by-moan** [sp614x/optifine#4256]
## Description of Issue
When I try to use mods with optifine with optifabric minecraft doesnt start because there is mods that use mixin library and when i remove the optifine starts normally but it says there is missing optifine

## Steps to Reproduce
1. Install fabric with optifabric and some mods that use mixin library itself
2. start minecraft

## OptiFine Version
preview_OptiFine_1.16.1_HD_U_G2_pre1
preview_OptiFine_1.16.1_HD_U_G2_pre2 

## Installation Method
Dropped the JAR file into your "mods" folder?
Also tried the extracted version

## Fabric/Forge Version
fabric-loader-0.8.9+build.203-1.16.1

## OptiFabric Version
optifabric-1.1.0-beta2

## Other Installed Mods
https://cdn.discordapp.com/attachments/634813023105581057/729363293281714197/unknown.png
https://cdn.discordapp.com/attachments/634813023105581057/729363477319385161/unknown.png
https://cdn.discordapp.com/attachments/634813023105581057/729364552076230666/unknown.png
https://cdn.discordapp.com/attachments/634813023105581057/729364690425348176/unknown.png
https://cdn.discordapp.com/attachments/634813023105581057/729364915416072253/unknown.png

**If OptiFine is installed as standalone, remove this section.**

## Log Files/Crash Reports
Any relevant log files. Drag and drop text files here to upload to GitHub directly, OR upload the complete contents to Pastebin. https://pastebin.com/SJwkAn08

**Comment by robertfwallis** [comment]
This probably won't be fixed. @sp614x himself has stated he doesn't plan on official Fabric support at all, and OptiFabric isn't maintained by him so there's nothing that will be done to fix it.

**Comment by sp614x** [comment]
Fabric is not supported.

**Comment by Deviouslrd** [comment]
Optifabric beta2 is also known to be really buggy with lots of mods.

**Comment by iuyte** [comment]
From [Optifabric README](https://github.com/modmuss50/OptiFabric/blob/master/README.md):
> I have no plans to continue updating OptiFabric going forward.

Apparently Optifabric is actually done for at this point.
