### ISSUE TITLE
The problem of launching minecraft for optifine and forge

### ISSUE THREAD

**Issue by Potato-S** [sp614x/optifine#4259]
When launching minecraft with forge and optifine, minecraft throws an error after 3 seconds, maybe it’s not connected with optifine, but I decided to write here

.2020 00:53:12.304] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, VAL1K_, --version, 1.16.1-forge-32.0.47, --gameDir, C:\Users\val1k\AppData\Roaming\.minecraft, --assetsDir, C:\Users\val1k\AppData\Roaming\.minecraft\assets, --assetIndex, 1.16, --uuid, c0756aa1dd7741b98947240faf6a4bce, --accessToken, ????????, --userType, mojang, --versionType, release, --launchTarget, fmlclient, --fml.forgeVersion, 32.0.47, --fml.mcVersion, 1.16.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20200625.16.2020 00:53:12.320] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 5.1.0+69+master.79f13f7 starting: java version 1.8.0_51 by Oracle Corporation
.2020 00:53:12.648] [main/INFO] [optifine.OptiFineTransformationService/]: OptiFineTransformationService.onLoad
.2020 00:53:12.648] [main/INFO] [optifine.OptiFineTransformationService/]: OptiFine ZIP file: C:\Users\val1k\AppData\Roaming\.minecraft\mods\preview_OptiFine_1.16.1_HD_U_G2_pre2.jar
.2020 00:53:13.195] [main/INFO] [net.minecraftforge.fml.loading.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
.2020 00:53:13.242] [main/INFO] [optifine.OptiFineTransformationService/]: OptiFineTransformationService.initialize
.2020 00:53:13.367] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: com.electronwill.nightconfig.core.io.ParsingException: Not enough data available
.2020 00:53:13.367] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.electronwill.nightconfig.core.io.ParsingException.notEnoughData(ParsingException.java:22)
.2020 00:53:13.367] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.electronwill.nightconfig.core.io.ReaderInput.directReadChar(ReaderInput.java:36)
.2020 00:53:13.382] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.electronwill.nightconfig.core.io.AbstractInput.readChar(AbstractInput.java:49)
.2020 00:53:13.382] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.electronwill.nightconfig.core.io.AbstractInput.readCharsUntil(AbstractInput.java:123)
.2020 00:53:13.382] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.electronwill.nightconfig.toml.TableParser.parseKey(TableParser.java:166)
.2020 00:53:13.382] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.electronwill.nightconfig.toml.TableParser.parseDottedKey(TableParser.java:145)
.2020 00:53:13.382] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.electronwill.nightconfig.toml.TableParser.parseNormal(TableParser.java:55)
.2020 00:53:13.382] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:44)
00:53:13.382] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:37)
.2020 00:53:13.382] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:113)
.2020 00:53:13.382] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:219)
.2020 00:53:13.382] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:202)
.2020 00:53:13.382] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.electronwill.nightconfig.core.file.WriteSyncFileConfig.load(WriteSyncFileConfig.java:73)
.2020 00:53:13.382] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.electronwill.nightconfig.core.file.AutoreloadFileConfig.load(AutoreloadFileConfig.java:41)
.2020 00:53:13.382] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.electronwill.nightconfig.core.file.AutosaveCommentedFileConfig.load(AutosaveCommentedFileConfig.java:85)
.2020 00:53:13.414] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.FMLConfig.loadFrom(FMLConfig.java:57)
.2020 00:53:13.414] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.FMLConfig.load(FMLConfig.java:69)
.2020 00:53:13.429] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.FMLServiceProvider.initialize(FMLServiceProvider.java:81)
.2020 00:53:13.429] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServiceDecorator.onInitialize(TransformationServiceDecorator.java:68)
.2020 00:53:13.429] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$initialiseTransformationServices$7(TransformationServicesHandler.java:107)
.2020 00:53:13.429] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler$$Lambda$85/2109798150.accept(Unknown Source)
.2020 00:53:13.429] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.HashMap$Values.forEach(HashMap.java:972)
.2020 00:53:13.429] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.initialiseTransformationServices(TransformationServicesHandler.java:107)
.2020 00:53:13.429] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:59)
.2020 00:53:13.429] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:75)
.2020 00:53:13.429] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

**Comment by sp614x** [comment]
Probably a conflict with some of the installed mods.
