### ISSUE TITLE
[Bug] Rendering issue between 36 and 37 render distance (1.16.1 pre 2)

### ISSUE THREAD

**Issue by SlayerOverlord** [sp614x/optifine#4261]
## Description of Issue
Please provide as much detail as possible.

Rendering entities and chinks appears to halt if a world is opened when the Render distance is set to 37 chunks and above. This issue only seems to occur in worlds created in Vanilla Minecraft and later opened using optifine. However, clouds, skybox, and sun/moon appear normally.

Render distance set to 36 before world Launch:
![2020-07-05_15 47 04](https://user-images.githubusercontent.com/67876131/86541061-d04a5580-bed7-11ea-89be-7b286ab9fb57.png)

![2020-07-05_15 46 51](https://user-images.githubusercontent.com/67876131/86541059-caed0b00-bed7-11ea-9ec6-8f08f42df1aa.png)

Render distance set to 37 before world Launch:
![2020-07-05_15 47 26](https://user-images.githubusercontent.com/67876131/86541074-f243d800-bed7-11ea-9e2c-4a65d833b3ad.png)

![2020-07-05_15 47 38](https://user-images.githubusercontent.com/67876131/86541075-f40d9b80-bed7-11ea-9c78-b90362c800af.png)

## Steps to Reproduce
1. Create a world before running/ installing optifine
2. Run/ install optifine
3. Set Render distance to 37 chunks
4. Launch the previously created world
(Note, Launching a world at 36 chunks then increasing the render distance does not produce this effect and the world renders as expected)

## OptiFine Version
1.16.1 HD U G2 pre2

## Installation Method
The standalone installer was used for installation.

## Installed Shaders
Sildurs Vibrant Shaders v1.27 Extreme-VL (Note, shaders set to off in the above images)
![2020-07-05_15 47 57](https://user-images.githubusercontent.com/67876131/86541117-5bc3e680-bed8-11ea-9d3d-beb1161ba600.png)

## F3 Debug Screenshot
37 Render F3:
![2020-07-05_15 59 19](https://user-images.githubusercontent.com/67876131/86541143-975eb080-bed8-11ea-91fa-4a12fa5a8395.png)

36 Render F3:
![2020-07-05_15 59 48](https://user-images.githubusercontent.com/67876131/86541154-a5accc80-bed8-11ea-8ac9-ae5e8ac727c3.png)

(Note, this occurs at the 6 GB I normally use, 8 GB was for the shader to self-test memory usage)

## Prior Testing
This does not occur in Vanilla Minecraft, 64 chunk render distance on world startup is done successfully.

**Comment by sp614x** [comment]
Fixed in pre5.
