### ISSUE TITLE
[Category] Short description

### ISSUE THREAD

**Issue by domajzino** [sp614x/optifine#4264]
Hi, I want to report a bug regarding item borders. You can see through them through the blocks (see photo). I don't know if it's a purely Minecraft bug or Optifine, so I apologize in advance if I'm wrong.
It does this for all items.

## Steps to Reproduce
I noticed it by accident.

## OptiFine Version
In version 1.16.1 HD U G2 pre2

## Installation Method
With "Install" button

![2020-07-05_23 43 14](https://user-images.githubusercontent.com/67878854/86543033-47eda400-bf1b-11ea-9035-040e5f64466b.png)
![2020-07-05_23 43 38](https://user-images.githubusercontent.com/67878854/86543034-48863a80-bf1b-11ea-9646-c940c733acda.png)

**Comment by sp614x** [comment]
Isn't this a vanilla problem?

**Comment by sp614x** [comment]
This is a vanilla problem:

![image](https://user-images.githubusercontent.com/16635441/87153826-5e4b8500-c2b8-11ea-8b36-2cbaa1a0922a.png)
