### ISSUE TITLE
[Category] Short description

### ISSUE THREAD

**Issue by loganlamothe** [sp614x/optifine#4265]
I don't know how it happened but my gravel is falling then refalling when I move in the block also block a not loading and have no hitbox

OptiFine Version
OptiFine 1.16.1 HD U G2 pre2

**Comment by sp614x** [comment]
What exactly is the problem?

**Comment by NitroCipher** [comment]
Sounds like a vanilla bug relating to server/client desync

**Comment by KaiAF** [comment]
No response from the Author, closing issue.
