### ISSUE TITLE
[Category] Visual bug

### ISSUE THREAD

**Issue by Hellster90** [sp614x/optifine#4268]
## Description of Issue
Please provide as much detail as possible.
During Raids, hitting the bell will show the particle effects around the bell, but doesn't show the silhouette of the raiders, tested close and far from raiders.

## Steps to Reproduce
1. What do you do... 
2. ...to find this bug?
Start a raid (Bad Omen)

## OptiFine Version
preview_OptiFine_1.16.1_HD_U_G2_pre2

## Installation Method
How did you install OptiFine? Did you use the included standalone installer, or did you drop the JAR file into your "mods" folder?
Used the installer

## Log Files/Crash Reports
Any relevant log files. Drag and drop text files here to upload to GitHub directly, OR upload the complete contents to Pastebin. https://pastebin.com/
No crash just visual bug

You can get logs from `.minecraft/logs`, and crash reports from `.minecraft/crash-reports`. 
Locating your `.minecraft` folder will depend entirely on your OS. See this page for details: https://minecraft.gamepedia.com/.minecraft

**DO NOT directly copy and paste log contents here on GitHub.**

## F3 Debug Screenshot
Minecraft's built-in debug screen provides *a lot* of useful information, and should be included even if the issue is not something that can be captured in a still image.
![2020-07-06_14 39 04](https://user-images.githubusercontent.com/61074300/86557976-1dd9c780-bf97-11ea-9e99-ca349c85146e.png)
![2020-07-06_14 38 58](https://user-images.githubusercontent.com/61074300/86558001-31852e00-bf97-11ea-9c29-d44336fea883.png)

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
No it doesn't, the silhouettes show up fine

## Additional Information
Here goes any final remarks and everything else that might not fit in the previous sections.

**Comment by sp614x** [comment]
The glowing effect is not compatible shaders.
Turn shaders OFF to enable it.
