### ISSUE TITLE
Optifine 1.8.9 L5 crash

### ISSUE THREAD

**Issue by Misha-133** [sp614x/optifine#4269]
Game + Launcher crashes if assign \ ( | ) button to zoom 

Latest java
xeon e3-1270 v2
12 gb ram (8 for minecraft)
gtx 960 2 gb
Latest Win 10

**Comment by Misha-133** [comment]
UPD:
Just realized that i forgot to say that game crashes only if bind zoom to Backslash key near L.Shift. It has different code than another Backslash key near Enter, and in some versions of minecraft if I bind it to any controls it says "NONE" instead "\"

**Comment by karmette** [comment]
someone close this

**Comment by KaiAF** [comment]
@Misha-133 If you are still having this issue, please create a new bug report that follows the current format.
