### ISSUE TITLE
[Request] Auto-Maximize Window On Start-Up

### ISSUE THREAD

**Issue by Emperor-Koala** [sp614x/optifine#427]
I am just wondering if it is possible to add a setting to automatically maximize the window when the game starts up (similar to how auto-fullscreen works, just for windowed mode instead). I have been looking for a way to do this without mods, though it looks like that is the only way. I just don't want to have all of Forge installed for one feature. Just an idea that I'm sure plenty of lazy people like me would appreciate. :stuck_out_tongue:

**Comment by Builderb0y** [comment]
MultiMC has an option to do this.

**Comment by sp614x** [comment]
Controlling the window size is outside of the Optifine scope.
Maximizing a window is platform specific. It works differently on Windows, MacOS and Linux.
The launcher can control the default window size by giving the "width" and "height" arguments.
