### ISSUE TITLE
[Bug] [1.16.1 Pre 2] Horse CEM wrong way around

### ISSUE THREAD

**Issue by ewanhowell5195** [sp614x/optifine#4274]
Zombie horse jem changes skeleton horse and skeleton horse cem changes zombie horse

Just looks like they are the wrong way around in the code
![image](https://user-images.githubusercontent.com/48070995/86610720-a3fd0a80-bfa5-11ea-989c-5efc5a04278b.png)

**Comment by sp614x** [comment]
Fixed in pre3.
