### ISSUE TITLE
[1.16] Invisible items with Forge > 32.0.43 and shaders

### ISSUE THREAD

**Issue by edpimble** [sp614x/optifine#4277]
## Description of Issue
As stated in the title, all items appear invisible inside the inventory and hotbar. In addition, the held textures for items are broken as well.

## Steps to Reproduce
1. Launched the game, enabled "Sildur's Vibrant Shaders v2.162 Extreme", and this visual glitch happened. 
2. I used different resource packs and had no issues when shaders was disabled.

## OptiFine Version
OptiFine 1.16.1 HD U G2 pre2
## Installation Method
I downloaded the .jar file and added it directly to my mods folder in 1.16.1 forge and MultiMC

## Fabric/Forge Version
Forge 32.0.47

## Other Installed Mods
Optiforge 1.16.1-0.1.0 and MixinBootstrap-1.0.3

## Log Files/Crash Reports

https://pastebin.com/WxfnxCkP

## F3 Debug Screenshot

https://imgur.com/a/3Wd16L4

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   - Only OptiFine and Forge
  
## Additional Information
Thank you for letting me submit the bug to help the mod.

**Comment by Sleaker** [comment]
Also verified the same issue with SEUS-Renewed-v1.0.1 and Silder's 1.27 Extreme. 

OptiFine: 1.16.1 HD U G2 pre2
Forge: 32.0.47

**Comment by Feanor7463** [comment]
Same issue, Don't know if it's an Optifine or a Forge Problem, but : 

  - Forge 32.0.47 + Mods : Fine
  - Forge 32.0.47 + Mods + Optifine + No Shaders : Fine
  - Optifine + Shaders (No Forge) : Fine
  - Forge 32.0.47 + Mods + Optifine + Shaders : Bug...

**Comment by willyde33** [comment]
use forge .39 for now.

**Comment by jestifizzle** [comment]
Can confirm that Forge 32.0.39 is working with inventory textures and shaders enabled

**Comment by Feanor7463** [comment]
Yes, can cofirm too

**Comment by rizkuwu** [comment]
Can confirm that Forge 32.0.43 is working.
Anything above is broken.

**Comment by yezhiyi9670** [comment]
The title should be changed. The bug is introduced in Forge 32.0.44 because Optifine is not conpatible with Forge's "model system improvements".

**Comment by sp614x** [comment]
Forge 32.0.44 is adding multi-layer item rendering, which shouldn't affect vanilla items.
It should be changing something the default item rendering that breaks the shaders, but I can't find what it is.

**Comment by yezhiyi9670** [comment]
Have you checked the commit history of Forge?

**Comment by sp614x** [comment]
Fixed in pre3.

**Comment by NaomiPaigeBreeze** [comment]
Fixed in Pre3? what does that mean? My textures still look bad and I'm on the most recent version of forge. When I downgrade to below 32.0.44 to remove the bug, optifine is no longer compatible so that's not a solution either. I tried looking at other threads but they were all closed due to this thread, but I see no solution here. Maybe I'm dumb?? Help!!

**Comment by jestifizzle** [comment]
Working for me with shaders using forge 32.0.63. @NaomiPaigeBreeze make sure you have that version of forge and are using preview_OptiFine_1.16.1_HD_U_G2_pre3.

**Comment by Feanor7463** [comment]
Works perfectly for me with preview_OptiFine_1.16.1_HD_U_G2_pre3 and forge 32.0.63, and with shaders  on, Thank you sp614x, you made my day !
