### ISSUE TITLE
Optifine Installer Wont let me click INstall (HELP)

### ISSUE THREAD

**Issue by Pofasdf** [sp614x/optifine#4279]
I have been trying to install Optifine but Optifine Installer wont let me click install.

1.16.1

I used the optifine installer

Image:
https://imgur.com/a/r1rcmEX

**Comment by OfficialAlexM** [comment]
You have invalid characters in your Windows account name. Try making a new Windows account named "Test" and see if it works on that.

**Comment by Pofasdf** [comment]
> You have invalid characters in your Windows account name. Try making a new Windows account named "Test" and see if it works on that.

Can you help me do that pls

**Comment by ZenIsBestWolf** [comment]
If this is still an issue, please contact Support via Discord, Twitter, or Email.
