### ISSUE TITLE
Signs are invisible! (and probably other blocks as well)

### ISSUE THREAD

**Issue by FireGB** [sp614x/optifine#4280]
Signs are invisible, and I assume that that other blocks are as well. I can see its hotbox when my cross hair is on it, but the actual texture is completely transparent.

**Comment by MunchkinMiester** [comment]
is this an optifine issue? try f3+a or place a block

**Comment by fresnizky** [comment]
This happened to me with chests on Fabulous graphic settings. Using Fancy textures show correctly

**Comment by yezhiyi9670** [comment]
This happens only when using Fast Render + Fabulous. The problem that "some blocks are invisible" is actually "Entities and TileEntities are invisible".

**Comment by FireGB** [comment]
Well, it’s gonna be fixed before the main release, right?

**Comment by FireGB** [comment]
> is this an optifine issue? try f3+a or place a block

Yes, it’s definitely an Optifine issue, I triple checked!

**Comment by sp614x** [comment]
Duplicate of #4289
