### ISSUE TITLE
[Textures] Glass colors wrong on 1.16.1-pre2

### ISSUE THREAD

**Issue by Person1425** [sp614x/optifine#4282]
## Description of Issue
Stained glass colors and some textures like acacia stairs and dark oak trapdoors are messed up.

## Steps to Reproduce
1. Install Optifine
2. Look at stained glass or certain textures

## OptiFine Version
1.16.1-pre2

## Installation Method
I installed it using Fabric

## Fabric/Forge Version
0.14.1 Build 372

## OptiFabric Version
1.1.0 Beta 2

## Other Installed Mods
None

**If OptiFine is installed as standalone, remove this section.**

## F3 Debug Screenshot
Minecraft's built-in debug screen provides *a lot* of useful information, and should be included even if the issue is not something that can be captured in a still image.

To open this menu, simply press `F3` on your keyboard while in-game. Please ensure the text is easily readable. Depending on the size/resolution of your monitor, you may have to adjust your GUI scale for all text to be completely visible on-screen.

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine? No

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? No
   - Only OptiFine and Forge
   - Only OptiFine, OptiFabric, and Fabric
- Does this happen without any mods at all?
   - Only Forge/Fabric by itself.
- Does this happen in OptiFine standalone?
- Does this happen in Vanilla without OptiFine?
- Have you tried using a binary search to find which mods cause this issue?
   - To find conflicting mods, split your mods into 2 groups (not including OptiFine/OptiFabric, obviously). Remove one group, and test in-game. Keep the group that has the problem, and repeat until no more mods can be removed without the issue disappearing.
   - Does the issue still happen with only the remaining mods installed?
      - Forge/Fabric and remaining mods, without OptiFine

**Comment by sp614x** [comment]
Stained glass colors, acacia stairs and dark oak trapdoors are OK.

![image](https://user-images.githubusercontent.com/16635441/87042921-98ebe980-c1f4-11ea-80e5-fdfb4aa7527f.png)

Fabric is not supported.
