### ISSUE TITLE
[Bug] random Snow Golem variants not working

### ISSUE THREAD

**Issue by fyreaken** [sp614x/optifine#4283]
trying to create Snow Golem variants does not work,
nametags and random spawns don't work either.

I'm using only Optifine 1.16.1 pre2.

posted properties below, I'm using this same format
for many other mobs without issue:

snow_golem.properties:
skins.2=2
name.2=iregex:(Melon|Melon Golem)

skins.3=1 2
weights.3=19 1

**Comment by sp614x** [comment]
Random snow golems are working:

![image](https://user-images.githubusercontent.com/16635441/87045331-0ea58480-c1f8-11ea-94da-b85201c302c6.png)

The pumpkin is not part of the snow golem texture.
