### ISSUE TITLE
[Sky] Option to assign sky textures / settings for all worlds of the same environment type.

### ISSUE THREAD

**Issue by mibby** [sp614x/optifine#4287]
With 1.15.2 and below, ``optifine/sky/world0/...`` use to apply sky settings and textures in all available server worlds with the exception of the nether and end. Now with 1.16.1 MC and Optifine 1.16.1 HD U G2 pre2, ``world0`` only applies to the primary overworld (singular ``world`` world). It no longer applies to other worlds of the same type.

Would it be possible to add a setting to allow sky textures to work in all worlds of the same environment type? (NORMAL vs NETHER/THE_END) That way you can have global sky textures in all worlds again without having to duplicate textures / settings for every single world you want the custom sky on.

**Comment by sp614x** [comment]
There are 3 types of worlds in vanilla - overworld, nether and the_end.
What is a world "of the same type"?

**Comment by mibby** [comment]
Of the same dimension type, i.e. being overworld. I have a server with multiple worlds.

- world (Dimension Type: NORMAL)
- world_nether (Dimension Type: NETHER)
- world_the_end (Dimension Type: THE_END)
- spawn (Dimension Type: NORMAL)
- void (Dimension Type: NORMAL)
- wonders (Dimension Type: NORMAL)
- creative (Dimension Type: NORMAL)

Since 1.16 and optifine, the sky replacement _only_ works in the ``world`` overworld. All other worlds with the same dimension (overworld / normal) no longer use the textures. This wasn't the case with 1.15 optifine / game version and prior. 

Either it's a bug or I'm assuming ``world0`` folder is now only correlating settings to be used on the first world existing (world).

**Comment by mibby** [comment]
@sp614x No ideas of the possible cause? :(

**Comment by mibby** [comment]
@sp614x You can use my resource pack for testing if needed. You will however need a Spigot / Paper 1.16.1 test environment with multiple worlds (multiverse-core) to test numerous world with the same dimension type (overworld).

[Resource Pack](http://play.eoscraftmc.com/serverpack/eospack.zip)

This issue only started to happen with Optifine 1.16.1.

**Comment by sp614x** [comment]
In 1.16 the dimensions don't have types anymore, only names like `minecraft:overworld`. The dimension check has been updated to recognize the vanilla dimension names.
The servers often use dimension names which are not the same as vanilla, for example `hypixel:lobby` and OF can't recognize their type.

**Comment by mibby** [comment]
Would it be possible to allow having a setting to default sky settings for every world by default and be able to exclude specific names so nether/end can be avoided?

**Comment by sp614x** [comment]
Fixed to use overworld as default for unknown dimensions.
Coming in pre13.

**Comment by HMU59** [comment]
Hello,
Following this issue, i'm having troubles because when i create custom dimension with "END" environnement type, i see the "end sky" with Custom Sky : OFF, but the Overworld Sky with Custom Sky : ON
Any way to fix this ?
