### ISSUE TITLE
[1.16] Fast render + Fabulous causes entities to disappear

### ISSUE THREAD

**Issue by JeffyBoi95** [sp614x/optifine#4289]
## Description of Issue##
Every time I turn on fast render, all the players disappear

**Comment by MrVenom0** [comment]
Use the template for reporting a bug.

**Comment by yezhiyi9670** [comment]
Only when Fast Render + Fabulous. In fact, all Entities and TileEntities will disappear.

**Comment by sp614x** [comment]
Fixed in pre3.
