### ISSUE TITLE
DPI scaling support

### ISSUE THREAD

**Issue by acterhd** [sp614x/optifine#429]
Hello. Will Optifine support extended DPI scaling for Minecraft? I now using 4K monitor with 24 inches. For vanilla solved with my MCP mod-patch. 

Here is some materials and docs about scaling of Minecraft. 
https://1drv.ms/f/s!AgEr-N6c2tdUhKdR9vjgiZFZ0U-pfg

- Support for latest version of Minecraft (1.11.2)
- Support adaptive scaling (ScaledResolution.java)
- Support for 4K displays

**Comment by sp614x** [comment]
Added GUI scale 4x to 7x for 4k displays: http://imgur.com/eeMOi3H
GUI scale 1x, 3x, 5x and 7x are not compatible with unicode, this is a vanilla limit: https://bugs.mojang.com/browse/MC-41685

**Comment by acterhd** [comment]
Where I can load Optifine snapshot?

**Comment by sp614x** [comment]
Go here: http://optifine.net/downloads
Click on "Preview versions" at the top.
Here is the direct link: http://optifine.net/adloadx?f=preview_OptiFine_1.11.2_HD_U_B7_pre.jar

**Comment by acterhd** [comment]
I suggest add scale down by shift key.

2017-01-24 20:20 GMT+08:00 sp614x <notifications@github.com>:

**Comment by sp614x** [comment]
Updated preview B7 for 1.11.2.
Added Shift to scale down.

**Comment by acterhd** [comment]
I also have code for experimental dynamic scaling. Scales can changes by
resize window/resolution. Can be changed options for scaling by usable
area. Limited by 800x600.

**Comment by sp614x** [comment]
I don't want to add dynamic scaling (for example 50% of window size) because the option will become very confusing. Some values will be absolute (small, normal, 4x, 6x) and other will be relative (50%, 60%, etc).

**Comment by sp614x** [comment]
The optimal GUI scale is generally depending on the monitor DPI.
If the GUI scale is optimal in a window it will also be optimal in a fullscreen.

**Comment by acterhd** [comment]
Sorry for extra proposals. I also want right click for scaledown as
alternative of click+shift. Also have cons for touch-screens.

**Comment by sp614x** [comment]
What do you mean with "cons for touch-screens"?

**Comment by acterhd** [comment]
I mean that right click for scaledown usable not only for mouse...

**Comment by sp614x** [comment]
How should right-click for touch screen work?
The shader options GUI also supports only Shift for reverse selection.

**Comment by acterhd** [comment]
By press and houlding.

**Comment by sp614x** [comment]
Is this working anywhere else in Minecraft?

**Comment by acterhd** [comment]
Don't know how answer... Tap and hold more state function of platforms (alternative of right click in mouse), than game features. If review multi-touch features (and not only), they uses, for example, swipe, or touch optimize buttons.

**Comment by sp614x** [comment]
Right-click is already used in the shader options to reset the value to default.
So it can not be used for reverse change of GUI Scale.

**Comment by sp614x** [comment]
Updated preview B7 for 1.11.2.
Right click selects previous value, shift+click resets to default (Auto)
