### ISSUE TITLE
[1.16] CEM chest in minecart textures missing

### ISSUE THREAD

**Issue by Norzeteus** [sp614x/optifine#4295]
Description of Issue
I have created my own chest for my txtpack with CEM and it works ( textures had to be placed in MC chest folder to work), but the chest is not rendered on chest_minecart
I also wanted to create a new ender chest, construction works, but the texture is taken from "normal chest" and not from "ender"

 Steps to Reproduce
Using chest in MC

[chest_cem.zip](https://github.com/sp614x/optifine/files/4889641/chest_cem.zip)

 OptiFine Version
1.16.1_HD_U_G2_pre2 (also preview_OptiFine_1.15.2_HD_U_G1_pre30)

 Installation Method
 standalone installer

No Other Installed Mods

![minecart_chest](https://user-images.githubusercontent.com/24456750/86899158-ea6b7a00-c109-11ea-8a41-541c9cf6825f.png)

**Comment by sp614x** [comment]
Chest textures in 1.16 are packed in a texture atlas, which is not supported by CEM yet.

**Comment by ewanhowell5195** [comment]
tried your models works fine for me
