### ISSUE TITLE
 NBT tag texture is incompatible

### ISSUE THREAD

**Issue by sdadad4aq1** [sp614x/optifine#4301]
## Description of Issue
Please provide as much detail as possible.

## Steps to Reproduce
1. Use a texture pack which works with NBT tags on a server with version 1.16.1
2. The texture pack works only with Optifine installed

## OptiFine Version
OptiFine 1.16.1_HD_U_G2_pre2 and pre1

## Installation Method
JAR Standalone Installer

A texture pack that works with Optifine and only changes the texture of objects in a plugin called Slimefun thanks to NBT tags, stopped working on servers running 1.16.1, but even if it has texture pack 1.15.2 or 1.16.1 of optifine, it continues to work only if the server is 1.15.2 or earlier until 1.13, therefore, there is evidence that it is an Optifine error, it is worth clarifying that the server even if it is 1.16, I can enter with 1.15. 2, and the error continues to occur for the sole reason the server runs at 1.16.1

Below I leave some images of what it looks exactly so that it is easier to understand: 

1. https://prnt.sc/tedrnk
2. https://prnt.sc/tedsx6

The texture pack used is: http://www.mediafire.com/file/heoit5rilucqn5g/SlimeFun_Texture_v2.3.2_%2528MC_1.13%252B%2529.zip/file

To test the error, you can access a server with the Slimefun plugin (minepixel.org is recommended, since it is a network and you can quickly go from one server to another with /earth "Server 1.15.2 and / urvival" Server 1.16.1) "and see how in /earth the Slimefun textures change but in /survival (1.16.1) they do not change

**Comment by sp614x** [comment]
CIT is working when the items are correctly named:

![image](https://user-images.githubusercontent.com/16635441/87039613-b36f9400-c1ef-11ea-9f19-166668a20628.png)

![image](https://user-images.githubusercontent.com/16635441/87039628-bff3ec80-c1ef-11ea-99af-82a4c1f52aeb.png)

MC 1.16 doesn't allow text formatting (§) to be given for item names, this may be the problem.
