### ISSUE TITLE
[Lighting] Always full-bright

### ISSUE THREAD

**Issue by baronjutter** [sp614x/optifine#4303]
I'm using the latest preview build of optifine along with optifabric on 1.16.1 and night or day, all blocks are at full brightness all the time.  I can load a shader and lighting suddenly works again, but without a shader on all blocks are fully lit.  I've dug through all the options but nothing seems to fix this.

**Comment by cs127** [comment]
I remember having a fullbright bug using optifine and I fixed it by just changing the brightness to something else and back to what it was. Have you tried changing the brightness option?

**Comment by sp614x** [comment]
Fabric is not supported.
