### ISSUE TITLE
[1.16.1] Invisible Items

### ISSUE THREAD

**Issue by ELG-Icefish** [sp614x/optifine#4304]
All Items get Invisible if i use any shader, even the internal one,

**Comment by sp614x** [comment]
Running with Forge, Fabric or standalone?

**Comment by FireGB** [comment]
I have the same problem, and I'm using forge. Perhaps it doesn't occur on standalone or fabric though?

**Comment by SoullessShadow** [comment]
Sames happening to me, currently using Forge with it. Haven't tested without it but seems to be a little buggy. Here's how it looks for me:
https://imgur.com/gallery/omTXoqZ

**Comment by jennasisis** [comment]
Hola, optifine 1.16.1 pre 2, no invisible items on internal shaders running standalone

**Comment by Feanor7463** [comment]
Seems to be the same that #4277

**Comment by sp614x** [comment]
Duplicate of #4277
