### ISSUE TITLE
Support for multiple shaders

### ISSUE THREAD

**Issue by SidMinecraft** [sp614x/optifine#4312]
Support for multiple shaders just like resourcepacks

**Comment by Deviouslrd** [comment]
How would htis be beneficial?

**Comment by yezhiyi9670** [comment]
I remember someone suggested this before. sp614x says this is not possible because unlike resourcepacks, different shaders work in different ways and cannot be combined automatically without errors.

**Comment by sp614x** [comment]
Shader packs can't be stacked on top of each other because every one organizes the rendering pipeline in a different way.
