### ISSUE TITLE
[Shaders] Mobs don't flash red/white with internal shaders

### ISSUE THREAD

**Issue by yezhiyi9670** [sp614x/optifine#4313]
## Description of Issue

Mobs don't flash red and Creeper/TNT don't flash white with internal shaders.

(Clones #3598, but only with internal shaders)

## OptiFine Version

1.16.1_G2_pre2

## Installation Method

Tried both.

## Fabric/Forge Version

Forge 32.0.43 (I use this to avoid inventory glitch with shaders)

## F3 Debug Screenshot

![image](https://user-images.githubusercontent.com/39194383/87108483-04859380-c295-11ea-832c-6154464568c8.png)

## Prior Testing

Only with shaders. Can reproduce without Forge.

**Comment by yezhiyi9670** [comment]
Also 1.15.2

**Comment by sp614x** [comment]
Internal shaders are for testing the rendering pipeline, not for gameplay.
Shader packs can render the entity hurt efect with the `entityColor` uniform:
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.txt#L177

**Comment by yezhiyi9670** [comment]
Shouldn't internal shaders work correctly? I just want to use 2x graphics. (maybe #4302 is a better solution for this...)

**Comment by yezhiyi9670** [comment]
This should be reopened and fixed as Internal Shaders can be used in gameplay.

If a dimension-specific shaders does not have the files for a certain dimension, the Internal Shaders will be used.
