### ISSUE TITLE
[Shaders] Light strips across block

### ISSUE THREAD

**Issue by minerman5777** [sp614x/optifine#4314]
## Description of Issue
Using Vanilla Plus by RRe36 v2.2, it seems that these strips of light that look like leaks from something like godrays appear on blocks underground. The strips move with the sun and adjusting Vanilla Plus's shader option "Sun Path Rotation" does change the position of the strips and in some extreme settings removes/hides them.

## Steps to Reproduce
1.  Acquire Vanilla Plus
2. Go underground
3. Maybe mine a bit, use torches to light your way, the strips appeared after placing some torches.

## OptiFine Version
1.16.1 HD U G2 pre2

## Installation Method
Standalone installer

## Log Files/Crash Reports
[latest.log(Likely irrelevant, but maybe there's something I can't see?)](https://github.com/sp614x/optifine/files/4900436/latest.log)

## F3 Debug Screenshot
![2020-07-09_19 19 18](https://user-images.githubusercontent.com/19852608/87109310-29d4bc00-c219-11ea-8d9a-8a667d468732.png)

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
Requires shaders, so I assume no.

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   - Only OptiFine and Forge
   - Only OptiFine, OptiFabric, and Fabric
- Does this happen without any mods at all?
   - Only Forge/Fabric by itself.
- Does this happen in OptiFine standalone?
- Does this happen in Vanilla without OptiFine?
- Have you tried using a binary search to find which mods cause this issue?
   - To find conflicting mods, split your mods into 2 groups (not including OptiFine/OptiFabric, obviously). Remove one group, and test in-game. Keep the group that has the problem, and repeat until no more mods can be removed without the issue disappearing.
   - Does the issue still happen with only the remaining mods installed?
      - Forge/Fabric and remaining mods, without OptiFine

**Comment by sp614x** [comment]
This is a side effect of the shadow bias applied by the shader pack.
Could be fixed by increasing the render distance.

**Comment by Kosobrazik** [comment]
enabling the "lightleak prevention" feature in the "lighting" section helped me.
