### ISSUE TITLE
1.16.1 pre3 CTM for logs not working correctly.

### ISSUE THREAD

**Issue by JimStoneCraft** [sp614x/optifine#4320]
## Description of Issue
All the logs display incorrectly in the South West directions, North East, Up and Down all work correctly.

The new Crimson and Warped Stem both work fine.

This logs work fine in OptiFine 1.15.2 HD U G1 pre30 on Minecraft 1.15.2 (apart from the Crimson and Warped Stem as they are not in that version of Minecraft).

## Steps to Reproduce
1. Put some logs down and they don't CTM correctly.

## OptiFine Version
OptiFine_1.16.1_HD_U_G2_pre3

## Installation Method
Standalone installer.

## Additional Information
Resource packs used - John Smith Legacy 1.16.1 v2 and John Smith Legacy JSC 1.16.1 v2

https://www.johnsmithlegacy.co.uk/

![Logs North East](https://user-images.githubusercontent.com/42512910/87182603-64535d00-c2dc-11ea-8f33-b76fed7d794c.jpg)
![Logs South West](https://user-images.githubusercontent.com/42512910/87182607-64ebf380-c2dc-11ea-9b7b-3c775432cd4c.jpg)

**Comment by sp614x** [comment]
Fixed in pre4.

**Comment by JimStoneCraft** [comment]
This fixed all the wood logs bu then broke the Crimson and Warped stems.

North East is fine, it's only in the South West direction.

![Stems South West](https://user-images.githubusercontent.com/42512910/87239018-f4d78d80-c401-11ea-9ac0-28a484c4ac00.png)

**Comment by JimStoneCraft** [comment]
I've updated my 1.16.1 development map if that's of any help to you.

JimStoneCraft Presentation Map - Minecraft 1.16.1 - Nether Update.
https://www.johnsmithlegacy.co.uk/jimstonecraft.php
