### ISSUE TITLE
My shaders and messing with my enchanted items

### ISSUE THREAD

**Issue by WetWipee** [sp614x/optifine#4321]
they're just solid purple... idk if this is optifines fault or my shaders but I'm submitting this anyway

**Comment by TheoCGaming** [comment]
It happens when VanillaPlus shaders are enabled, are you using 1.16 versions?
The reason why I am asking is because it might be an incompatibility? I use the 1.12 version of those shaders, and the same problem arises. It does not seem to happen with SEUS renewed.

**Comment by sp614x** [comment]
Can you post a debug screenshot (F3)?

**Comment by TheoCGaming** [comment]
Took me an hour to notice the message and I had to do some other stuff but here are the files.

Logs are also submitted. This also happens in 1.15.2.

![2020-07-10_18 17 09](https://user-images.githubusercontent.com/65421262/87213438-cb234700-c2d9-11ea-91f7-d2c267e89f08.png)

[latest.log](https://github.com/sp614x/optifine/files/4906088/latest.log)

**Comment by WetWipee** [comment]
I'll also send a screenshot then 
![brokelol](https://user-images.githubusercontent.com/48190204/87213916-295a2500-c2ee-11ea-81c9-5fa9e1155e82.png)

**Comment by TheoCGaming** [comment]
Hmm, it happens with chaopaic too...?

**Comment by TheoCGaming** [comment]
are the shaders for 1.12.2?

**Comment by WetWipee** [comment]
I'm pretty sure they're for 1.14

**Comment by TheoCGaming** [comment]
Ok, if 1.16 chaopaic shaders are available, try using those and send screenshots of the same world. Then that'll prove whether or not it's the shaders.

**Comment by WetWipee** [comment]
Turns out I did have shaders for 1.12.2, but I went ahead and installed shaders from 1.14 (the newest ones I could find), and the same things happened. (Chaopaic v7.1 Extreme to Chaopaic V8 Ultra). 
![brokelol2](https://user-images.githubusercontent.com/48190204/87214439-29f4ba80-c2f2-11ea-92ee-158cf40d8908.png)

**Comment by TheoCGaming** [comment]
I'll try with my Seus Renewed.

**Comment by TheoCGaming** [comment]
The same bug doesn't occur, but something far more interesting happens. The glint doesn't move, and a very odd lighting bug occurs. Look at this.

![2020-07-10_19 17 22](https://user-images.githubusercontent.com/65421262/87214537-56a0d600-c2e2-11ea-874c-debb4670bb62.png)
![2020-07-10_19 17 29](https://user-images.githubusercontent.com/65421262/87214541-5accf380-c2e2-11ea-92ab-f9258e34e2ba.png)
![2020-07-10_19 17 15](https://user-images.githubusercontent.com/65421262/87214542-5d2f4d80-c2e2-11ea-8859-9ba1be9536e3.png)

**Comment by TheoCGaming** [comment]
Look at the helmet tops on the diamond and gold armors. They occasionally turn into black voids. The bug doesn't occur on the un-enchanted ones.

**Comment by TheoCGaming** [comment]
It appears to be an instability in how the glint is rendered while certain types of shaders are enabled.

**Comment by TheoCGaming** [comment]
I assume the bug is getting worked on.

**Comment by Mourdraug** [comment]
Problem seems to be fixed for me in preview 15.

**Comment by KaiAF** [comment]
If this is still an issue, please let me know. I believe this was fixed already
