### ISSUE TITLE
Feeding a parrot a cookie crashes the game

### ISSUE THREAD

**Issue by josephash** [sp614x/optifine#4323]
When I feed a parrot a cookie, the parrot dies and then the game crashes. I don't know if it's caused by the item drops or what but it crashes my game every time.
[crash-2020-07-10_17.20.15-client.txt](https://github.com/sp614x/optifine/files/4905472/crash-2020-07-10_17.20.15-client.txt)

**Comment by Ioxom** [comment]
Update to pre3.

**Comment by TheoCGaming** [comment]
Pre-3 is out, cookie bug is fixed, and the issue needs to be closed. @sp614x ?

**Comment by NitroCipher** [comment]
User reported crash is fixed in pre3
