### ISSUE TITLE
[Bug] chunks don't load when flying

### ISSUE THREAD

**Issue by PhoenixAlpha204** [sp614x/optifine#4325]
## Description of Issue
F3 shows 0 chunk updates yet large sections of the world do not load in. This only occurs while flying (stationary or moving) - if I land everything seems to load correctly. Zooming in on unloaded sections will also load them, but this is tedious to do.

## Steps to Reproduce
1. Fly and reload all chunks. Might need to fly up fairly high.

## OptiFine Version
Attached screenshot is 1.16 pre3, but this also happens in 1.15 pre30 and 1.14 F5.

## Installation Method
Standalone

## F3 Debug Screenshot
![2020-07-10_16 01 39](https://user-images.githubusercontent.com/68132454/87210778-acb64f00-c2cb-11ea-8499-5cc2f7f428db.png)

## Prior Testing
If you've installed standalone:
This does not happen in vanilla.

## Additional Information
I have tried adjusting everything in the performance tab hoping that one of them caused this. No luck.
As this seems to be altitude based perhaps it is intended and optifine is only loading the tops of chunks. If so I would suggest an option to disable this.

**Comment by sp614x** [comment]
Probably fixed with #4261

**Comment by PhoenixAlpha204** [comment]
Seems so!
