### ISSUE TITLE
[Bug] 1.16 Night lighting is as bright as day.

### ISSUE THREAD

**Issue by Crispynuggety** [sp614x/optifine#4326]
Its fairly simple. Whenever i open my world with 1.16 at night its consistently a 15 sky light (though was getting 13 under solid blocks and 14 under transparent.). Day is normal 15 and block light is 0 at night, but everything is rendered as if its all totally lit up.

No fancy settings, everything is on fast if possible (except trees) and custom sky doesnt affect it.

Installed using the .jar's built in installer.
 
![2020-07-10_21 47 58](https://user-images.githubusercontent.com/68136268/87215077-8e1a7d00-c2f8-11ea-976f-7c55ed96a3e2.png)

Doesnt happen in vanilla. Only with the 1.16 pre.

Havent seen any posts about this, hope it helps. The potato pc race thanks you optifine.

**Comment by sp614x** [comment]
Are you using a resource pack?

**Comment by Crispynuggety** [comment]
No resource packs. Other than optifine, its purely vanilla.

**Comment by TygreWolf** [comment]
I'm also seeing this issue.  No resource packs, and pure vanilla under the optifine jar installer.  This also affects flying in spectator mode; you can see that underground caves appear completely lit, even though there are no torches or lighting at all.  This was under prerelease 3.
![2020-07-12_08 01 28](https://user-images.githubusercontent.com/8293997/87245755-07f45880-c416-11ea-8b36-3abcb2c44d24.png)

**Comment by TygreWolf** [comment]
This issue still exists in G2 pre5.

**Comment by Crispynuggety** [comment]
issue is gone, no more lighting issues. Beats me why its gone but eh all good for me.

**Comment by TygreWolf** [comment]
This issue is not gone for me.  Should I open another issue?  Still happening in pre11.

![2020-07-29_18 49 39](https://user-images.githubusercontent.com/8293997/88861657-708c5500-d1cc-11ea-9ee5-2ef64ed757a4.png)

**Comment by Crispynuggety** [comment]
id say yes, sorry for closing it a bit prematurely. Make sure that you dont have multiple resource packs active at the same time (ie programmer and vanilla textures). I ended up messing with the packs (enabling and disabling) but idk what i did, all i know is today it quit.
