### ISSUE TITLE
[Bug] Blue fire isn't animated unlike regular fire unless you turn on Terrain Animated

### ISSUE THREAD

**Issue by kapper-git** [sp614x/optifine#4328]
## Description of Issue
Blue fire isn't animated even with Fire Animated turned on, unless you turn on Terrain Animated which makes all new animated textures animated.
## Steps to Reproduce
1. Turn off Terrain Animated and turn on Fire Animated
2. Observe the bug

## OptiFine Version
Optifine 1.16.1 HD G2_pre3 Ultra

## Installation Method
Dropped the .jar file into mods folder

## Fabric/Forge Version
Fabric 1.16.1 version 0.8.9+build.203

## OptiFabric Version
OptiFabric version 1.1.0-beta2

## Other Installed Mods
Fabric API, Lithium, Phosphor, Shulker Box Tooltip

## Log Files/Crash Reports
https://pastebin.com/tHnX1Mdt

## F3 Debug Screenshot
[Debug screenshot](https://imgur.com/a/gauF7FV)

## Prior Testing
This only happens with Optifine itself, Vanilla isn't affected as it does not have a turn on/off animations menu.

**Comment by Regnander** [comment]
Related #4260

**Comment by sp614x** [comment]
Fixed in pre4
