### ISSUE TITLE
[1.16]CEM wolf tamed shows duplicate above  preview_OptiFine_1.16.1_HD_U_G2_pre4

### ISSUE THREAD

**Issue by Norzeteus** [sp614x/optifine#4335]
Description 
Finally got my  CEMwolf   working again but when Itry to tame, a duplicate of it´s legs appears above
issue #3689 
[wolf_cem.zip](https://github.com/sp614x/optifine/files/4908220/wolf_cem.zip)
 

 Steps to Reproduce
taming wolf

 OptiFine Version
preview_OptiFine_1.16.1_HD_U_G2_pre4 (also pre 2 + 3)

Installation Method
 standalone installer

No Other Installed Mods
![wolf](https://user-images.githubusercontent.com/24456750/87242253-3fb9cb00-c42b-11ea-95af-734e549ec988.png)

**Comment by Norzeteus** [comment]
This issue happens also in newer versions of optifine...I hope sp614x would be so kind to fix it....

**Comment by Norzeteus** [comment]
This issue happens also in 1.16.5....

**Comment by Norzeteus** [comment]
@KaiAF : Tried it in preview_OptiFine_1.16.5_HD_U_G8_pre11 but it`s always the same issue, duplicated legs above...
(red color is ok, it`s an alien.... :)

**Comment by ewanhowell5195** [comment]
seems to be a bug with optifine and jpm files. 

I have combined the model into a single JEM file and it works fine, so i recommend using this instead. The UV map is broken you will have to fix it.

Also i recommend not using Cubik Studio as Blockbench is a much better free bit of software that makes the process of making CEM models a lot easier.

[wolf.zip](https://github.com/sp614x/optifine/files/6217706/wolf.zip)
