### ISSUE TITLE
[Visual] Mojang logo becomes jagged

### ISSUE THREAD

**Issue by WikLemon** [sp614x/optifine#4337]
In OptiFine 1.16.1 HD U G2 pre4 the Mojang logo appears jagged.

## Steps to Reproduce
1. Launch Minecraft with OptiFine 1.16.1 HD U G2 pre4

## OptiFine Version
OptiFine 1.16.1 HD U G2 pre4

## Installation Method
Used the included standalone installer

## Prior Testing
If you've installed standalone:
- Does not occur in Vanilla
![vanilla](https://user-images.githubusercontent.com/52998448/87243830-6ed73900-c439-11ea-89e2-fd47c054de36.png)
- Occurs in OptiFine 1.16.1 HD U G2 pre4
![optifine](https://user-images.githubusercontent.com/52998448/87243831-6f6fcf80-c439-11ea-8c11-ef95ebc8e79c.png)

**Comment by RedCarlos26** [comment]
It is happening for me two when using the OptiFine Pre4

**Comment by jxaumees** [comment]
It is still happening with optifine 1.16.1 pre8

**Comment by WikLemon** [comment]
Still happning with optifine 1.16.1 pre15

**Comment by RedCarlos26** [comment]
Still happening in 1.16.1 full OptiFine release.

**Comment by RedCarlos26** [comment]
Still happening in 1.16.1 U G2 full OptiFine release

**Comment by Eastah** [comment]
Still happens with OptiFine 1.16.2 HD U G3 pre5.

**Comment by sp614x** [comment]
Fixed in pre6.
