### ISSUE TITLE
[Shaders] Entity per-element previous modelview matrix as uniform for generating entity motion data

### ISSUE THREAD

**Issue by sonicether** [sp614x/optifine#4350]
Motion data for entities would be incredibly useful for shaders that rely on temporal reprojection. As entity elements are rendered via the gbuffers_entities program, if we could have a uniform that contains the previous frame's modelview matrix for each particular element that's being rendered, we could generate motion data.

I'm unsure of the performance impact this would have, especially when many entities are present. It may be useful to have an option in shaders.properties to enable or disable this functionality. This would also allow us to test the performance impact of the feature.

**Comment by sp614x** [comment]
Entity motion data should be available with the velocity map in latest preview:
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.txt#L154
