### ISSUE TITLE
[Performance] Issues with fps on high-end computer

### ISSUE THREAD

**Issue by AuroYT** [sp614x/optifine#4358]
## Description of Issue
Vanilla Minecraft runs around 100 fps with the graphics settings at max on my computer in an infinite world, however, Optifine runs MUCH slower. For some reason, even with the settings ALL the way down, the fps sits at a solid 20-40 fps. That's about the max, maybe 50 if I'm lucky. 

## Steps to Reproduce
1. Have a computer with an intel i7, RTX 2060, and 64GB of RAM.
2. To find the bug, simply open up an infinite world.

## OptiFine Version
OptiFine 1.16.1 HD U G2 pre4

## Installation Method
Installed Optifine via built in installer of the jar file.

## Other Installed Mods
No additional mods.

**If OptiFine is installed as standalone, remove this section.**

## Log Files/Crash Reports
Any relevant log files. Drag and drop text files here to upload to GitHub directly, OR upload the complete contents to Pastebin. https://pastebin.com/

You can get logs from `.minecraft/logs`, and crash reports from `.minecraft/crash-reports`. 
Locating your `.minecraft` folder will depend entirely on your OS. See this page for details: https://minecraft.gamepedia.com/.minecraft

**DO NOT directly copy and paste log contents here on GitHub.**

## F3 Debug Screenshot

Without Optifine
[image](https://drive.google.com/file/d/1Z8S33kg_mKvYDVAgJ2_H9E1W7z-rrS2B/view?usp=sharing)

With Optifine
[image](https://drive.google.com/file/d/1wJQ3YoSXyobHobiyDe0FvXRVPTnZTcml/view?usp=sharing)

## Prior Testing
This fps issue does NOT occur in vanilla Minecraft, just in Optifine. It happened in the first pre-build of Optifine 1.16, all the way through the current fourth build.

## Additional Information
No other games have any issues on my computer, except for Java with Optifine for some odd reason. I have 64GB of RAM, speed at 3200 (information gathered by typing "wmic memorychip get devicelocator, speed" into command prompt) with an intel i7 and an RTX 2060, which aren't the BEST out there, but the computer still doesn't slouch. With the Optifine and Vanilla versions, 8GB of RAM were allocated. All video and graphics settings were the exact same between the two screenshots and their respective versions.

**Comment by TheoCGaming** [comment]
It seems to be a driver problem. Using optifine, if you look in the upper right, you will notice it says "Intel(R) UHD Graphics 630" instead of "GeForce RTX 2060/PCIe/SSE2"

**Comment by AuroYT** [comment]
Didn't even pick up on that. Would I need to address that with NVIDIA products?

**Comment by TheoCGaming** [comment]
You might just need to reinstall either OptiFine or your NVIDIA drivers.

**Comment by TheoCGaming** [comment]
I'll check if it happens with mine, too.

**Comment by AuroYT** [comment]
I've reinstalled a couple times, so it might be drivers. I'm also reinstalling NVIDIA drivers. Since I sent out this thread, I get nearly 200 fps with max graphics on the overworld, 300+ underground. Seems weird that the issue is happening with Optifine only...

**Comment by TheoCGaming** [comment]
![2020-07-14_13 14 36](https://user-images.githubusercontent.com/65421262/87472052-2dc75c00-c5d4-11ea-8eb0-178e83cd652d.png)
Seems to be drivers. The world I'm using is an OptiFine test world I used to test enchantments. Was OptiFine working okay on Pre-3 and earlier?

**Comment by AuroYT** [comment]
Figured it out! I actually went into NVIDIA control panel and changed global settings to always use RTX for every program. I opened up Optifine on it and got 133 fps instantly. Debug mode showed the 2060! Thank you for leading me in the right direction.

**Comment by TheoCGaming** [comment]
You're welcome.

**Comment by TheoCGaming** [comment]
Make sure to close the issue, though.
