### ISSUE TITLE
[Bug] Broken Fog on AMD/Intel GPUs

### ISSUE THREAD

**Issue by SirBobb** [sp614x/optifine#4363]
## Description of Issue
Having an AMD/Intel GPU forces fog on fast instead of fancy which looks awful, especially when moving the camera and seeing chunk edges

## Steps to Reproduce
Use AMD/Intel Card
Set low render distance so it's most visible.

## OptiFine Version
All

## Installation Method
Standalone

## Log Files/Crash Reports
is it needed?

**DO NOT directly copy and paste log contents here on GitHub.**

## F3 Debug Screenshot
![2020-07-15_11 21 44](https://user-images.githubusercontent.com/35657425/87528142-6a0ac300-c68d-11ea-9df6-3f52ce6028f8.png)

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
Yes

## Additional Information
If for some reason you can't fix it yourself in optifine, please provide a shader that's exactly like internal shaders (doesn't add ANY extra effects, especially not bright entities)

Fast Fog
![2020-07-15_11 17 54](https://user-images.githubusercontent.com/35657425/87527873-0a141c80-c68d-11ea-8bfe-462ca2a15126.png)

Radial Fog
![2020-07-15_11 17 58](https://user-images.githubusercontent.com/35657425/87527888-0e403a00-c68d-11ea-9033-d126e0ed32a0.png)

**Comment by sp614x** [comment]
Radial fog on AMD/Intel can only be added with shaders. For example a simple shader pack can only radial fog.

**Comment by yezhiyi9670** [comment]
I've written one without bright entities or other effects, but some fog distances are tweaked. It's coming s∞n™.

**Comment by yezhiyi9670** [comment]
[Here](https://wmsdf.cf/cloud/index.php?share/fileDownload&user=4&sid=KEQBAzId&path=/McMap/Radial%20Fog/Radial%20Fog.zip)'s the shaderpack. It works on both 1.12.2 and 1.16.3.

The formulas may not be accurate, so diffuse lighting will not be exactly like Vanilla. Also I don't know whether the formula for Tile Entities is correct or not. Tell me if it's wrong.

**Comment by SirBobb** [comment]
> [Here](https://wmsdf.cf/cloud/index.php?share/fileDownload&user=4&sid=KEQBAzId&path=/McMap/Radial%20Fog/Radial%20Fog.zip)'s the shaderpack. It works on both 1.12.2 and 1.16.3.
> 
> The formulas may not be accurate, so diffuse lighting will not be exactly like Vanilla. Also I don't know whether the formula for Tile Entities is correct or not. Tell me if it's wrong.

you're my hero and savior <3

**Comment by SirBobb** [comment]
Hey if you happen to see this, I found a bug in your shader. When killing the dragon, it doesn't do these purple light thingies. So far that's the only bug and you've done a superb job! Could you please just fix that? I would appreciate it :D

**Comment by KidCodes** [comment]
Hey i know its a bit late, but do you still have the shader file? The link is broken.
