### ISSUE TITLE
[Bug] Can't switch between Fast or Fancy

### ISSUE THREAD

**Issue by Gergoo007** [sp614x/optifine#4367]
## Description of Issue
I can't switch to Fabulous.

## Steps to Reproduce
1. Go to Settings 
2. Video Settings
3. Try to change Visual Quality

## OptiFine Version
1.16.1 HD U G2 pre4

## Installation Method
Ran the jar file using java -jar OptiFine-preview... .jar (Simple installer)

## Log Files and options
https://pastebin.com/i2tb2fUj

## F3 Debug Screenshot
[Imgur](https://i.imgur.com/ne2eYJM.png)

## Prior Testing
In vanilla mc it looks like:
[Imgur](https://i.imgur.com/h1JaAVD.png)
(Fabulous is buggy both in vanilla and OptiFine, clouds are rendered while they are behind something, Fast works without any bug)

btw sorry for my english, if it have any problems, it's not my main language...

**Comment by XenonZed** [comment]
Seems to be because the warning screen that shows up when switching to Fabulous on unsupported GPUs doesn't appear when using OptiFine. I have the same problem on my old macbook.

**Comment by sp614x** [comment]
Fixed in pre9
