### ISSUE TITLE
[1.16.1 preview] [Rendering] Invisible mobs

### ISSUE THREAD

**Issue by nathanh01** [sp614x/optifine#4369]
I encountered an invisible vindicator and an invisible evoker in a woodland mansion, and then on another occasion, an invisible piglin in a bastion and also an invisible witch. Most mobs in the mansion and bastion were visible, I saw plenty of vindicators, evokers and piglins before encountering the invisible ones. Some of the vex that the evoker spawned were invisible but not all.
I saw another report about invisible and invulnerable piglins in bastions however I was able to hurt the vindicator and I killed the witch.
I tried travelling away from the mansion and going back to reload the chunks but nothing changed. I'm not using any mods, texture packs or external shaders, I think I may have had optifine's internal shaders on at the time.
I installed Optifine using the standalone installer and this occurred on an external server owned by a friend, but no one else on the server has said they've experienced this.

**Comment by pfeurean** [comment]
i've had the same thing happen with a zombie in the wild. i was able to make it reappear by disconnecting and then reconnecting back to the server.

**Comment by Regnander** [comment]
Related #4322

**Comment by vican94** [comment]
I have had the same thing happen to me with a zombie and also partly with a spider but then I could still see the red in the face.

**Comment by CDarklock** [comment]
> I have had the same thing happen to me with a zombie and also partly with a spider but then I could still see the red in the face.

Spiders can spawn with random potion effects applied, as part of the vanilla game. So the almost-invisible spider where you can still see the eyes is intentional game design, not related to this bug.

**Comment by oscarkool** [comment]
Also encountering invisible mobs while using Sildur's shaders. Really annoying

**Comment by sp614x** [comment]
Seems to be fixed with 1.16.2 pre6.
