### ISSUE TITLE
[Suggestion] Presets

### ISSUE THREAD

**Issue by Argentum047** [sp614x/optifine#4371]
Have the ability to use/create custom presets, i.e. a performance/fps based preset where everything is optimized for smooth gameplay, or a Max quality preset that instantly sets all settings to be quality based. You would be able to name and create your own presets, and have them saved for later use.

**Comment by Mikilis** [comment]
this is not issue

**Comment by DavidWGEdge** [comment]
Wait you're right. I can delete this, but do you know where people can suggest changes to Optifine?
