### ISSUE TITLE
Campfire smoke causing major rendering issues

### ISSUE THREAD

**Issue by Oscaross** [sp614x/optifine#4372]
Whenever something like a campfire or campfire smoke is present, it makes the Sildur's Vibrant Shaders (High) go all buggy, and render the world in an ugly yellow light & incorrectly render shadows. Seems to occur in biomes like Jungles & Taiga, visible with trees. Occured in 1.16.1, Optifine prerelease 4.

See attached files for an example of the error, the only known fixes I have are changing the render distance a lot and flying to different biomes where it snaps back and corrects it, though, when I go back to the jungle village with campfires (which I think are the cause) it flickers back to the bug.
![2020-07-16_12 39 16](https://user-images.githubusercontent.com/44754250/87667029-94c64b80-c761-11ea-9a05-3931a2ab1cfd.png)

**Comment by britnuka** [comment]
I have the exact same problem with campfires, after placing a few campfires in my world, the tree shadows dissappeared and my player shadow (apart from my shield) was no longer visible. Messing around with the render distance or changing the shadow settings seems to fix the problem, but the problem reappears once you go back near camp fires. This issue appears to exist on every version of sildurs shaders, even older versions.

Without campfires: 
![trees2](https://user-images.githubusercontent.com/68449708/87838968-b96d1100-c890-11ea-84cc-f13590a057e1.png)

With campfires nearby:
![trees3](https://user-images.githubusercontent.com/68449708/87838919-89be0900-c890-11ea-8ba2-69d61249f682.png)

**Comment by sp614x** [comment]
Fixed, coming in 1.16.3 G4_pre2.
