### ISSUE TITLE
[1.16] CIT Color Codes no working

### ISSUE THREAD

**Issue by VulkanoTG** [sp614x/optifine#4375]
## Description of Issue
I went to redo my texture to 1.16.1 and ended up not working, after some tests find that the color code (\u00A70, in this format) is not working version on this, is this bug or you modified how it works?

## Steps to Reproduce
use color codes for example: \u00A70
## OptiFine Version
OptiFine 1.16.1 HD U G2 pre4

## Installation Method
installer

## Additional Information
prints:
https://imgur.com/dHASOzF
https://imgur.com/uQitMgo

**Comment by cs127** [comment]
That's working perfectly fine in the screenshot.

**Comment by VulkanoTG** [comment]
I created texture of an item so that when its name is blue and written Copper Ingot it would change the texture of the brick to that of copper, in 1.15.2 worked then I decided to redo it and it happens that when I put color codes it does not work, I've tried all the ways, with HEX colors, with the code & and with § and with \u00A7b (that was what I used in the old days)

as I used on 1.15.2 and that no longer works
https://imgur.com/B3OeWH1
https://imgur.com/ZPfNXvH

without the color code it works, however I needed it to work with the color code
https://imgur.com/KkRhmy0
https://imgur.com/a/BZnnVG4

**Comment by unicornbloods** [comment]
Is this only an issue on 1.15?

**Comment by lexikiq** [comment]
Can confirm on 1.16.2 OptiFine G2. Trying to change entity color based on color code name, but I'm guessing from the changes in 1.16 to allow any RGB value that some things broke. To match an entity named `§0​§1​§rLargo§0​§2​` (don't ask), you should be able to use `\u00a70​\u00a71​\u00a7rLargo\u00a70​\u00a72​`, or at the very least `pattern:*0*1*Largo*0*2*`, but neither of these work. However, `\u200b\u200bLargo\u200b\u200b` works perfectly, as if the color codes weren't in the entity's name at all. Hopefully this explanation makes more sense as my project heavily depends on this ^^

**Comment by ThatsCube** [comment]
Exactly my kind of problem .. and I can't find a solution anywhere, so I think Optifine needs to update to fit and add alternatives to enter colors.

**Comment by verlixis** [comment]
Is it possible that the newly added hexadecimal color support in 1.16 broke the CIT Color Codes?

Quoted from minecraft.gamepedia:
>- Added text component `font`.
>- The color component can now contain a hexadecimal RGB value prefixed by # (Example: "color":"#ff0088")

**Comment by sp614x** [comment]
Since 1.16 the NBT text tag isn't using color codes. 
Instead the text styles are applied as JSON fields.
