### ISSUE TITLE
[1.16.1] Random Crashes

### ISSUE THREAD

**Issue by ModCritic** [sp614x/optifine#4378]
## Description of Issue
At random times, when on servers/realms (Edit: it also can happen in singleplayer), my fps drops drastically fast to zero, everything freezes, and the last sound that was playing repeats until it crashes. This never happened with 1.15 and below optifine versions.

## Steps to Reproduce
Play a few minutes on a server (Edit: or singleplayer) with the latest preview version of optifine (as of posting this).

## OptiFine Version
OptiFine 1.16.1 HD U G2 pre4 (Edit: Still happens in pre5) (Second Edit: Still happens in pre8) (Now pre10) (Now pre12) (Now full 1.16 release)
## Installation Method
I was playing it on my chromebook when this happened, so on that I had to put the optifine version .jar into the linux files folder, use the terminal to do the command `java -jar [name of .jar file]` to install it like I'd properly installed all prior optifine versions before, and they all worked fine.

## Crash Report
[latest.log](https://github.com/sp614x/optifine/files/4974388/latest.log)

**Comment by sp614x** [comment]
Can you post the crash report or the error log after the crash?

**Comment by ModCritic** [comment]
> Can you post the crash report or the error log after the crash?

Okay, I shall when it comes up again, though it seems logs are saved as .log.gz besides the latest.log on this device, and I don't remember if you can do anything with those since they just have a ton of hex code or something which is not plain english. So I guess I'll put the latest.log once it happens again.

**Comment by Deviouslrd** [comment]
Yes you want to post the latest.log directly after the crash, because the file gets reset everytime you open the game

**Comment by ModCritic** [comment]
Hm, well I attached the log to the issue, but when I click on the link it created it just opens an untitled tab without anything and then closes right after. It's not a blocked pop-up though because my browser would tell me if it blocked one.

**Comment by ModCritic** [comment]
Oh wait, that makes sense. It just downloads really fast. Duh, *facepalm*.

**Comment by ModCritic** [comment]
By the way, I've noticed that after the first time it crashes each day, the crashes end up being really frequent. It takes a while for the first crash of the day, and then it just does it every 10-40 minutes.

**Comment by Deviouslrd** [comment]
Still post the log, so we can try help

**Comment by ModCritic** [comment]
But, I _did_ post the log. Did you not read my comments? Look at the issue post under the header **Crash Report**. It shows the hyperlink to the latest.log I uploaded yesterday.

**Comment by sp614x** [comment]
No errors in the log, seems normal.

**Comment by ModCritic** [comment]
Do you think that would be something to do with the fact that I'm running it on a chromebook with a linux crostini vm? Because, whenever the launcher shows up after crashing, the "view crash report" button doesn't open any log file, but instead opens the terminal (empty) and then does nothing, so maybe it doesn't produce crash logs correctly? I guess I can try just describing it with as much detail as possible then so maybe it helps; It only happens on servers, though specifically realm servers since I haven't been on a normal server since the beginning of 1.16, but even before then optifine never crashed like this, and neither did vanilla minecraft, so I determined it must be these 1.16 preview versions which are creating the problem. Basically, for the first time after turning the chromebook on for the day, I play for a couple hours on a realm, and then it just starts slowing down the fps. To clarify, I normally hover around 26-30 fps with optifine (yes, this chromebook is a potato... because it's a chromebook). Sometimes it takes around 2 minutes to slow down gradually to about 5 fps, then it freezes, and whatever sound was playing when it freezes repeats several times until it crashes, which is very similar to most crashes I've ever had with other games on other PCs. However, I've never seen crashes like this in Minecraft before, even when I first got the game years ago when I had a potato PC then. Anyway, after the first crash of the day, every time I load up the game again, it can take anywhere from 5-40 minutes to crash again, and it's even crashed in the menu in the same way completely randomly. So that's all I know so far with the 60 or so crashes I've had in total since I started playing with the optifine preview versions. There doesn't seem to be a specific ingame cause like with using an item or block since it always happens randomly seemingly at any time. I was thinking maybe it could be a problem with the chromebook's memory, but since it only happens with optifine on, when the point of the mod is to optimize the game, I think it's got to be something to do with the mod.

**Comment by HiItsDevin** [comment]
Last I've tried, Crostini is still very finiky with Minecraft, so that could be it honestly.

**Comment by sp614x** [comment]
This looks like a native crash in the graphics drivers or in java itself.
There should be a "hs_err_pidXXX.log" file in the minecraft folder with more information inside.

**Comment by ModCritic** [comment]
Oh, yeah there are 34 of those. I guess it would make sense. Here's the latest one:
[hs_err_pid2272.log](https://github.com/sp614x/optifine/files/5013550/hs_err_pid2272.log)

**Comment by sp614x** [comment]
Crash in Java.
Doesn't seem to be related to OptiFine.

```
Stack: [0x00007f34f4b25000,0x00007f34f4c26000],  sp=0x00007f34f4c23990,  free space=1018k
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libc.so.6+0x39d57]

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J 7115  org.lwjgl.system.JNI.invokeV(J)V (0 bytes) @ 0x00007f34e06e9602 [0x00007f34e06e9560+0x00000000000000a2]
J 20000 c1 dlx.e(Z)V (946 bytes) @ 0x00007f34da2d16ec [0x00007f34da2caaa0+0x0000000000006c4c]
j  dlx.e()V+68
j  net.minecraft.client.main.Main.main([Ljava/lang/String;)V+1366
```
