### ISSUE TITLE
Crash (Graphics Driver Related)

### ISSUE THREAD

**Issue by ShortsNJacket** [sp614x/optifine#4385]
**Description of Issue**
When Optifine is installed, Minecraft crashes randomly, every 5ish to 15ish minutes. This only happens when I'm on a server, and weirdly on single-player it is fine.

**Steps to Reproduce** (This may be related to my graphics driver, which I did update, so it is unlikely you'll be able to reproduce)
1. Download Optifine
2. Go onto a Server
3. Wait a while

**OptiFine Version**
OptiFine 1.15.2 HD U G1 pre30

**Installation Method**
Mods Folder

**Forge Version**
Forge 31.2.23

**Optiforge Version**
OptiForge-MC1.15.2-0.1.27

**Other Installed Mods**
https://pastebin.com/EUUcVePY

**Log File**
https://pastebin.com/u0trLMu6

**F3 Debug Screenshot**
Cannot do this atm as the server is not running, and it only happens on a server. Will do this if this is needed.

**Prior Testing**
- Removing Optifine fixes the issue
- Does not happen in Single Player, and have tested that for extended periods of time.
- I tried removing Phosphor in the past , but this didn't fix the issue

**Additional Information**
The server is self-hosted on my friends PC, though I doubt this would affect it.

**Comment by Deviouslrd** [comment]
1: what are your specs 
2: how much ram have you allotted 
3: does the crash happen without warning and instantly? Also what else might you be running other than minecraft

**Comment by ShortsNJacket** [comment]
**Specs**:
i5-7300u with intel HD graphics 620
4GB of Ram
128GB of SSD storage

**Ram allocated**: 3.5GB (Should I try lowering this?)

The crash happens without warning, and the only other thing running is discord in chrome.

**Comment by sp614x** [comment]
The crash is inside the graphics driver:
```
Stack: [0x0000000002b00000,0x0000000002c00000],  sp=0x0000000002bfb960,  free space=1006k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [ig9icd64.dll+0x3dcf73]
C  [ig9icd64.dll+0x3e42b6]
C  [ig9icd64.dll+0x98041]
C  [ig9icd64.dll+0x88a79]
C  [ig9icd64.dll+0x517b23]
C  [ig9icd64.dll+0x1c475c]
C  [ig9icd64.dll+0x9745cc]
C  0x0000000081191466
 
Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J 5329  org.lwjgl.opengl.GL11C.glDrawArrays(III)V (0 bytes) @ 0x00000000811913c9 [0x0000000081191380+0x49]
J 23857 C2 net.minecraft.client.renderer.vertex.VertexBuffer.func_227874_a_(Lnet/minecraft/client/renderer/Matrix4f;I)V (57 bytes) @ 0x00000000847aa094 [0x00000000847a9ce0+0x3b4]
J 26770 C2 net.minecraft.client.renderer.WorldRenderer.func_228441_a_(Lnet/minecraft/client/renderer/RenderType;Lcom/mojang/blaze3d/matrix/MatrixStack;DDD)V (527 bytes) @ 0x0000000085d2dfe0 [0x0000000085d2d240+0xda0]
J 26140 C2 net.minecraft.client.renderer.WorldRenderer.redirect$zfc000$redirectRenderLayer(Lnet/minecraft/client/renderer/WorldRenderer;Lnet/minecraft/client/renderer/RenderType;Lcom/mojang/blaze3d/matrix/MatrixStack;DDD)V (122 bytes) @ 0x00000000857885c0 [0x00000000857883e0+0x1e0]
J 30497 C2 net.minecraft.client.renderer.WorldRenderer.func_228426_a_(Lcom/mojang/blaze3d/matrix/MatrixStack;FJZLnet/minecraft/client/renderer/ActiveRenderInfo;Lnet/minecraft/client/renderer/GameRenderer;Lnet/minecraft/client/renderer/LightTexture;Lnet/minecraft/client/renderer/Matrix4f;)V (3484 bytes) @ 0x0000000085dd1a10 [0x0000000085dd0940+0x10d0]
J 28888 C2 net.minecraft.client.renderer.GameRenderer.func_228378_a_(FJLcom/mojang/blaze3d/matrix/MatrixStack;)V (881 bytes) @ 0x0000000086384740 [0x0000000086382ea0+0x18a0]
J 30593 C2 net.minecraft.client.renderer.GameRenderer.func_195458_a(FJZ)V (1094 bytes) @ 0x000000008309d42c [0x000000008309b8c0+0x1b6c]
```

**Comment by sp614x** [comment]
Some other mod is manipulating the layer rendering which may contribute to the crash:
```
net.minecraft.client.renderer.WorldRenderer.redirect$zfc000$redirectRenderLayer(Lnet/minecraft/client/renderer/WorldRenderer;Lnet/minecraft/client/renderer/RenderType;Lcom/mojang/blaze3d/matrix/MatrixStack;DDD)V (122 bytes) @ 0x00000000857885c0 [0x00000000857883e0+0x1e0]
```

**Comment by sp614x** [comment]
Can't be fixed by OptiFine.
