### ISSUE TITLE
Add custom banner colors

### ISSUE THREAD

**Issue by AmberWat** [sp614x/optifine#439]
It's currently not possible to change banner colors within a resource pack. This means that the banner colors will almost always be different from the wool and this mismatch can be somewhat jarring in builds.

I'd like to suggest adding settings to `color.properties` for each of the 16 colors.

**Comment by sp614x** [comment]
It looks like the banners are reusing the map colors. 
Configuring the map colors should also change the banner colors.

Here is the banner color mapping:
```
    WHITE(0, 15, "white", "white", MapColor.SNOW, TextFormatting.WHITE),
    ORANGE(1, 14, "orange", "orange", MapColor.ADOBE, TextFormatting.GOLD),
    MAGENTA(2, 13, "magenta", "magenta", MapColor.MAGENTA, TextFormatting.AQUA),
    LIGHT_BLUE(3, 12, "light_blue", "lightBlue", MapColor.LIGHT_BLUE, TextFormatting.BLUE),
    YELLOW(4, 11, "yellow", "yellow", MapColor.YELLOW, TextFormatting.YELLOW),
    LIME(5, 10, "lime", "lime", MapColor.LIME, TextFormatting.GREEN),
    PINK(6, 9, "pink", "pink", MapColor.PINK, TextFormatting.LIGHT_PURPLE),
    GRAY(7, 8, "gray", "gray", MapColor.GRAY, TextFormatting.DARK_GRAY),
    SILVER(8, 7, "silver", "silver", MapColor.SILVER, TextFormatting.GRAY),
    CYAN(9, 6, "cyan", "cyan", MapColor.CYAN, TextFormatting.DARK_AQUA),
    PURPLE(10, 5, "purple", "purple", MapColor.PURPLE, TextFormatting.DARK_PURPLE),
    BLUE(11, 4, "blue", "blue", MapColor.BLUE, TextFormatting.DARK_BLUE),
    BROWN(12, 3, "brown", "brown", MapColor.BROWN, TextFormatting.GOLD),
    GREEN(13, 2, "green", "green", MapColor.GREEN, TextFormatting.DARK_GREEN),
    RED(14, 1, "red", "red", MapColor.RED, TextFormatting.DARK_RED),
    BLACK(15, 0, "black", "black", MapColor.BLACK, TextFormatting.BLACK);
```

**Comment by AmberWat** [comment]
I can confirm that setting the map colors also changes banners.

Thank you. I had tried every setting I could find but my `color.properties` template was too old to list map colors for dyed blocks.

**Comment by sp614x** [comment]
The shulker boxes also use the map colors, so they should also be configurable in this way.

**Comment by sp614x** [comment]
Updated the map and banner colors: https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/color.properties
