### ISSUE TITLE
Killing Parrots Crashes the Game

### ISSUE THREAD

**Issue by Maxerhex** [sp614x/optifine#4394]
I wanted to get a nice red parrot, but when I killed a few my game crashed, it only happens when I'm running minecraft with OptiFine on, please fix it.

**Comment by Deviouslrd** [comment]
What minecraft and optifine version are you using?

**Comment by Ioxom** [comment]
An old one.
https://optifine.net/changelog?f=preview_OptiFine_1.16.1_HD_U_G2_pre5.jar

**Comment by Regnander** [comment]
Related #4214
