### ISSUE TITLE
ender dragon CEM not working

### ISSUE THREAD

**Issue by pibblepower** [sp614x/optifine#4395]
The CEM feature that allows for custom mob models in a resource pack doesn't,t seem to work with the ender dragon. I'm playing on optifine hd g2_pre5 ultra, and when I install a pack that edits the ender dragons model (specifically the Ender Dragon Reforged resource pack, you can find it on curseforge), the texture breaks, and the model doesn't change. I'm not a hundred percent sure if its not because of the pack being outdated, but I have a hunch that its a problem with this optifine version. can this issue be fixed? (I installed optifine via the standalone installer, I'm not using forge, and to reprise the issue install the ender dragon reforged resource pack alongside this version of optifine.
![2020-07-20_19 28 17](https://user-images.githubusercontent.com/47405209/87996065-3a115480-cabf-11ea-809a-9020a8b0c118.png)

**Comment by ManWithoutTaste** [comment]
Yeah Idk what either, I'm attempting the same but no luck.

**Comment by CrownVortex** [comment]
It still doesn't seem to have been fixed yet.
I was so ready to check out my new dragon cem but it turned out it doesn't work.

**Comment by ewanhowell5195** [comment]
maybe it was broken at the time of this issues creation, but it works fine now
