### ISSUE TITLE
Add shader macros OS_NAME, GL_VENDOR, GL_RENDERER and GL_VERSION

### ISSUE THREAD

**Issue by sp614x** [sp614x/optifine#440]
For OS one of: 
  OS_WINDOWS, OS_MAC, OS_LINUX, OS_OTHER

For vendor one of: 
  GL_VENDOR_NVIDIA, GL_VENDOR_ATI, GL_VENDOR_INTEL, GL_VENDOR_XORG, GL_VENDOR_OTHER

For driver one of: 
  GL_RENDERER_RADEON, GL_RENDERER_GEFORCE, GL_RENDERER_QUADRO, GL_RENDERER_GALLIUM, GL_RENDERER_MESA, GL_RENDERER_OTHER

GL_VERSION as int: 300, 330, 400, 450, etc
GLSL_VERSION as int: 130, 330, 400, 450, etc

The defines are added immediately after "#version XYZ"

**Comment by sp614x** [comment]
The OS check could be like:

    #if defined(OS_WINDOWS)
    ...
    #elif defined(OS_MAC)
    ...
    #else
    ...
    #endif`

version check:

    #if GL_VERSION > 400
    ...
    #elif GL_VERSION > 330
    ...
    #else
    ...
    #endif

**Comment by sp614x** [comment]
Check for GL extensions.

For example if the shader source contains anywhere the string "GL_ARB_shader_texture_lod" then OF will add "#define EXT_GL_ARB_shader_texture_lod" if it is supported.

If the extension is not supported the #define will not be added.

**Comment by zombye** [comment]
Isn't GL_VERSION going to be redundant?

GLSL already defines \_\_VERSION\_\_ as the version of GLSL that is being compiled, and I can't see how knowing which version of OpenGL is being used on CPU-side code would be useful.
#version still needs to be the first line that isn't empty or a comment, so unless OF gains its own preprocessor for that it's still not going to be useful for version-specific code.

**Comment by dotModded** [comment]
It's the maximum supported version of your system. Very useful

**Comment by dotModded** [comment]
This isn't for changing the version, it's detecting if certain extentions can be loaded or not. Making a lib for this to assure compatibility with everything

**Comment by sp614x** [comment]
__VERSION__ is the GLSL version being compiled (as requested by #version)
GL_VERSION will be the maximal supported OpenGL version - can be used for extension detection.
GLSL_VERSION will be the maximal supported GLSL version - can be used for language features.

**Comment by sp614x** [comment]
updated preview B7 for 1.11.2 
- added shader defines for OS, GL_VENDOR, GL_RENDERER, GL_VERSION and GLSL_VERSION

**Comment by sp614x** [comment]
updated preview B7 for 1.11.2 
- added shader macros for OpenGL extensions

D. OpenGL extensions
 Macros for the supported OpenGL extensions are named like the extension with a prefix "EXT_".
 For example the macro "EXT_GL_ARB_shader_texture_lod" is defined when the extension "GL_ARB_shader_texture_lod" is supported.
 Only the macros which are being checked are added to each shader file.
the final shader looks like this:

```
#version 120
#define GL_VERSION 400
#define GLSL_VERSION 400
#define OS_WINDOWS
#define GL_VENDOR_INTEL
#define GL_RENDERER_INTEL
#define EXT_GL_EXT_blend_func_separate
#line 2 0

#ifdef EXT_GL_EXT_blend_func_separate
// Enabled
#else
// Disabled
#endif

#ifdef EXT_GL_ARB_shader_texture_lod
// Enabled
#else
// Disabled
#endif
```
apparently GL_ARB_shader_texture_lod is not supported on Intel

**Comment by dotModded** [comment]
Shaders no longer compile on AMD, GL_ is reserved and causes all of the shaders to fail.

**Comment by sp614x** [comment]
Updated preview B7 for 1.11.2
- changed macro prefix to "MC_"
- current macro names: https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.txt#L362
