### ISSUE TITLE
[Initialization] Using missing texture, unable to load minecraft:optifine/ctm/default/empty.png.png

### ISSUE THREAD

**Issue by mibby** [sp614x/optifine#4404]
## Description of Issue
```
[10:45:03] [Worker-Main-12/ERROR]: Using missing texture, unable to load minecraft:optifine/ctm/default/empty.png.png : java.io.FileNotFoundException: minecraft:optifine/ctm/default/empty.png.png
```

## Steps to Reproduce
1. Start Optifine 1.16.1-Optifine_HD_U_G2_pre5 profile.
2. Enable / auto-load resource pack that has optifine settings.
2. Check start-up latest.log.
3. See error.

## OptiFine Version
OptiFine 1.16.1 HD U G2 pre5

## Installation Method
Standalone installer / profile method.

## Log Files/Crash Reports
Full start-up log.
https://paste.gg/p/anonymous/dbc271cbf9ff4b2684502a10c31dac80/files/6ac8f07ce9504379a626683447e20527/raw

## Additional Information
I do not have a optifine/ctm/default folder or any files in the resource pack that reference empty.png. The error happens only when a resource pack is loaded. Having no resource pack enabled doesn't seem to trigger the error.

You can download my resource pack for testing if needed here.
[Resource Pack](http://play.eoscraftmc.com/serverpack/eospack.zip)

**Comment by sp614x** [comment]
Fixed in pre9.
