### ISSUE TITLE
[1.16.1 Pre5] Shadow texture strange behaviour

### ISSUE THREAD

**Issue by SkaliberWasTaken** [sp614x/optifine#4405]
Having a custom shadow.png (in textures/misc/) within a texture packs creates a very strange tiling effect as seen below:

### **Custom Texture:**
![2020-07-22_01 22 28](https://user-images.githubusercontent.com/50083260/88120230-59d97300-cbba-11ea-888a-212c54d85c15.png)

From my testing, this can be seen with all entities that create a shadow.

### **Original Texture:**
![2020-07-22_01 23 13](https://user-images.githubusercontent.com/50083260/88120241-6362db00-cbba-11ea-8e97-948ade6012c4.png)

Including the original shadow.png within a texture pack with no changes whatsoever creates the exact same tiling effect.

### **No Texture:**
![2020-07-22_01 25 39](https://user-images.githubusercontent.com/50083260/88120256-6eb60680-cbba-11ea-93f1-7b8934f4c318.png)

Removing the texture from the texture pack (allowing it to default to vanilla) will remove the effect.

**Comment by MrCheeze446** [comment]
Does this still happen with the full release?

**Comment by SkaliberWasTaken** [comment]
> Does this still happen with the full release?

I've discovered this was actually a vanilla thing, and have since found the solution.
