### ISSUE TITLE
[Category] Short description

### ISSUE THREAD

**Issue by BelmoDoll** [sp614x/optifine#4409]
## Description of Issue
Glass does not fully connect when on a diagnol
## Steps to Reproduce
1. You place glass, not in a full square/rectangle
2. You LOOK

## OptiFine Version
1.16.1 Pre 7

## Installation Method
Mod folder

## Fabric/Forge Version
Latest Fabric

## OptiFabric Version
Latest

## Other Installed Mods
Optifabric, Shulker Tooltips

**If OptiFine is installed as standalone, remove this section.**

## Log Files/Crash Reports
Any relevant log files. Drag and drop text files here to upload to GitHub directly, OR upload the complete contents to Pastebin. https://pastebin.com/

You can get logs from `.minecraft/logs`, and crash reports from `.minecraft/crash-reports`. 
Locating your `.minecraft` folder will depend entirely on your OS. See this page for details: https://minecraft.gamepedia.com/.minecraft

**DO NOT directly copy and paste log contents here on GitHub.**

## F3 Debug Screenshot
Minecraft's built-in debug screen provides *a lot* of useful information, and should be included even if the issue is not something that can be captured in a still image.

To open this menu, simply press `F3` on your keyboard while in-game. Please ensure the text is easily readable. Depending on the size/resolution of your monitor, you may have to adjust your GUI scale for all text to be completely visible on-screen.

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
![2020-07-22_12 44 44](https://user-images.githubusercontent.com/68659894/88210769-4d850280-cc1a-11ea-8356-5acd0c5d8b4c.png)

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   - Only OptiFine and Forge
   - Only OptiFine, OptiFabric, and Fabric
- Does this happen without any mods at all?
   - Only Forge/Fabric by itself.
- Does this happen in OptiFine standalone?
- Does this happen in Vanilla without OptiFine?
- Have you tried using a binary search to find which mods cause this issue?
   - To find conflicting mods, split your mods into 2 groups (not including OptiFine/OptiFabric, obviously). Remove one group, and test in-game. Keep the group that has the problem, and repeat until no more mods can be removed without the issue disappearing.
   - Does the issue still happen with only the remaining mods installed?
      - Forge/Fabric and remaining mods, without OptiFine

## Additional Information
Here goes any final remarks and everything else that might not fit in the previous sections.

**Comment by Pizzachu22** [comment]
This seems to be working properly

**Comment by Deviouslrd** [comment]
I dont see why it is working properly. the connected glass should be completely flawless with borders, but as you can see, it isn't in the screenshot.

**Comment by sp614x** [comment]
OptiFabric is not supported.
https://github.com/modmuss50/OptiFabric/issues
