### ISSUE TITLE
Better support for surround gaming

### ISSUE THREAD

**Issue by Blockstate** [sp614x/optifine#441]
Basically will remove the stretching that occurs when running Minecraft on multiple displays. Either rendering with multiples cameras or rendering as equirectangular should solve this issue.

**Comment by sp614x** [comment]
If the monitors are in one line the default projection should be correct. 
If the monitors are rotated to the player ([example](https://ofryaw-bn1306.files.1drv.com/y2poFveBweFEXy7LfO5USaisAr1qiKUD_9xViXVIszreF64o_XW3zJBe03r3IKVw4IoyqSWebWyIm3xWXO518nDNIEij-k5DPbqPK_Ikttm3Ok/SimMonitorsetup.png?psid=1)) then the game will have to be rendered several times with different camera rotations.
How does MC on a multi-monitor setup currently look like? 
How does it look with a smaller and larger FOV?

**Comment by Opptitronica** [comment]
Adjusting the FOV does not help with the issue. When you take a screenshot it looks fine but during game play things on the side monitors looked stretched. Not only that but when moving the players camera it causes objects to warp/look like there falling/rushing towards the user and looks very unnatural.

**Comment by sp614x** [comment]
Rendering the scene several times with rotation will probably break the stitching between the monitors.
A custom shader pack may be able to decrease the distortion on the side monitors. 

See also:
  https://www.gamecrate.com/pc-gaming-samsungs-curved-monitors/10117
  https://www.gamecrate.com/wp-content/uploads/2015/02/Minecraft-Curved-Monitor.jpg

**Comment by Opptitronica** [comment]
Okay, it must be something purely on my side and I'll look into the custom shader pack, but I would like to see that the UI is locked to the middle monitor. It's annoying to have to look all the way to the left or right when in F3, same with chat. Other than that there's no issues with surround.
