### ISSUE TITLE
Cape glitch in 1.16.1 PRE7

### ISSUE THREAD

**Issue by tenshiaka** [sp614x/optifine#4410]
## Description of Issue
When wearing cape and armour, the cape will display as black
## Steps to Reproduce
Activate Custom Coloured Cape, then wear any type of armour

## OptiFine Version
1.16.1 PRE7

## Installation Method
 included standalone installer

## F3 Debug Screenshot

![image](https://user-images.githubusercontent.com/64901373/88222191-e0975a00-cc65-11ea-8d4b-4ec0d4395fdb.png)

## Prior Testing
If you've installed standalone:
- No cape in Vanilla

![image](https://user-images.githubusercontent.com/64901373/88222272-ff95ec00-cc65-11ea-9dbc-53832c850011.png)
![image](https://user-images.githubusercontent.com/64901373/88222282-06246380-cc66-11ea-981c-00d6070d5a68.png)

**Comment by sp614x** [comment]
Fixed in pre9.
