### ISSUE TITLE
[1.16.1-pre7][Bug] Respawning causes entities to visually desync/become invisible

### ISSUE THREAD

**Issue by XenonZed** [sp614x/optifine#4414]
### Description of Issue
Dying and respawning in the Nether (EDIT: happens in the overworld too, I presume it would also occur in the end) causes any nearby entities (mobs, dropped items, etc.) to either:
a) Visually appear to stand in place, even if they are moving
b) Become completely invisible
Reloading the world or reloading resource packs via F3+T causes them to appear normally again. Issue appears to occur regardless of whether fast render is on or whether fabulous graphics are on.

This is possibly randomly occurring; I've noticed other invisible mobs without any trigger for it, but respawning is by far the most reliable way I've found to replicate this issue.

Using OptiFine 1.16.1-pre7, standalone installation. This bug does not occur in vanilla Minecraft.

### Steps to Reproduce
1. Start a new world
2. Set your spawn near some entities (using /spawnpoint, a bed, or a respawn anchor)
3. Kill the player and respawn

### Debug screenshots
![2020-07-22_18 08 28](https://user-images.githubusercontent.com/66463691/88242277-f39c3100-cc49-11ea-8f1c-fdb6b2c61063.png)
![2020-07-22_18 10 39](https://user-images.githubusercontent.com/66463691/88242183-b9cb2a80-cc49-11ea-946f-65939e06a74c.png)
![2020-07-22_18 10 45](https://user-images.githubusercontent.com/66463691/88242187-bc2d8480-cc49-11ea-98ff-2535d7521d47.png)
![2020-07-22_18 13 14](https://user-images.githubusercontent.com/66463691/88242206-c485bf80-cc49-11ea-849e-83991d199542.png)
![2020-07-22_18 13 20](https://user-images.githubusercontent.com/66463691/88242207-c64f8300-cc49-11ea-8425-c0814ab881ca.png)

**Comment by LexBoosT** [comment]
Same problem on Pre6 and Pre8 for me. Invisible entity by moment.

**Comment by XenonZed** [comment]
Tested more. Confirmed this doesn't just occur in the nether; it happens when respawning in any dimension (provided it's the same on you died in)

![2020-07-22_22 10 10](https://user-images.githubusercontent.com/66463691/88251482-281ee580-cc68-11ea-95ce-19c87179af16.png)
![2020-07-22_22 11 03](https://user-images.githubusercontent.com/66463691/88251521-41279680-cc68-11ea-98c3-78f674e1b1fa.png)

**Comment by sp614x** [comment]
Fixed in pre9
