### ISSUE TITLE
adfoc.us almost gave me a virus! DETAILS BELOW.

### ISSUE THREAD

**Issue by TheoCGaming** [sp614x/optifine#4415]
@sp614x this is ABSOLUTELY URGENT. The downloads redirect me to adfoc.us, which is usually safe, but adfoc.us now redirects me to a page that may (or may not) be trying to give me a virus! Upload your files to github for now, as I don't want anyone to risk their computer for a download of the most popular mod in minecraft.

**Comment by Studio528-real** [comment]
Use the "Mirror" option to the right of the download button, it will skip adfoc.us and bring you to the download page.

**Comment by MrCheeze446** [comment]
If you want to avoid getting a virus ignore everything you see on your screen when going through an adfoc.us link, use an adblocker or just user the mirror link.

**Comment by Deviouslrd** [comment]
If you on adfoc.us, just focus on the skip button, and close the tab it redirects to.
Or use the mirror.

**Comment by lukemagdalin** [comment]
> If you want to avoid getting a virus ignore everything you see on your screen when going through an adfoc.us link, use an adblocker or just use the mirror link.
for me adfocus doesn't let me by if I have an ad blocker on. I usually have to disable 4 adblockers before I can actually download it.

**Comment by TheoCGaming** [comment]
> 
> 
> If you want to avoid getting a virus ignore everything you see on your screen when going through an adfoc.us link, use an adblocker or just use the mirror link.

It straight up redirects me w/out me even touching anything.

**Comment by Studio528-real** [comment]
Use Ublock Origin, it will block everything on adfoc.us except the Skip button and will stop redirects except the destination, at least that is my experience with it. the mirror option is also there in case adfoc.us is giving problems or you don't want to go through adfoc.us

**Comment by TheoCGaming** [comment]
I used the mirror link. (however the destination page still redirects me to a page like roblox or MTG arena)

**Comment by Studio528-real** [comment]
That's just built-in ad thing, it doesn't actually download anything besides optifine, just creates a new tab/window with that URL. Ublock Origin will block this redirect also.

**Comment by TheoCGaming** [comment]
Is UBlock Origin paid?

**Comment by Jorkles** [comment]
No.

**Comment by TheoCGaming** [comment]
ok. thanks!

**Comment by Studio528-real** [comment]
It is not paid,
for Chrome, you can find it here: https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm
for Firefox, you can find it here: https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/
