### ISSUE TITLE
[1.16.1 pre8] I can't see the fish rod

### ISSUE THREAD

**Issue by ActiveXTi** [sp614x/optifine#4416]
Even if it has no resourcepacks, when I run minecraft with optifine, I can't see fish rod: only bubbles.
screenshots: [https://i.postimg.cc/Pf05BHrK/2020-07-23-10-27-30.png](url)

**Comment by sp614x** [comment]
Works for me:

![image](https://user-images.githubusercontent.com/16635441/88275703-1a0bac00-ccde-11ea-8c05-f20a7980402a.png)
