### ISSUE TITLE
[cem] Phantom.jem doesn't render the head in-game

### ISSUE THREAD

**Issue by iNkoR-the-2nd** [sp614x/optifine#4418]
## Description of Issue
If a phantom.jem file exists the head of the Phantoms will not render even if you change nothing. Phantom_eyes stop working too.

## Steps to Reproduce
1. Load a phantom model from the CEM template loader
2. save it as "phantom.jem" in assets/Minecraft/optifine/cem

## OptiFine Version
1.16-pre4

## Installation Method
Preview versions

## Log Files/Crash Reports
Output log only says that the cem model was loaded

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
No

- Does this happen in OptiFine standalone?
Yes

- Does this happen in Vanilla without OptiFine?
No

**Comment by sp614x** [comment]
The phantom head is rendered as a part of the body.
If you replace the body (as CEM Template Loader does) then the new head will not be rendered. In this case the new body should also add a new head model.
