### ISSUE TITLE
Entities randomly become invisible but can still be interacted with

### ISSUE THREAD

**Issue by ChocoMC** [sp614x/optifine#4424]
This bug happens at random. dropped items are invisible and so are mobs. the mobs can still move and hurt you but you cannot see them. the version of optifine that i am using is 1.16.1. The issue occurs when i am using shaders or a resource pack

**Comment by Regnander** [comment]
Maybe related #4322

**Comment by Regnander** [comment]
Which OptiFine version do you have? This sounds similar to #4414, which was fixed in version pre9.

**Comment by ChocoMC** [comment]
i am using 1.16 preview

**Comment by ChocoMC** [comment]
> Which OptiFine version do you have? This sounds similar to #4414, which was fixed in version pre9.

i am using preview 1.16

**Comment by sp614x** [comment]
Fixed in pre9.
