### ISSUE TITLE
Nether Chunk 

### ISSUE THREAD

**Issue by Yolopick** [sp614x/optifine#4428]
## Description of Issue
the first chunk infront of the nether portal doesnt load
## Steps to Reproduce
1.Enter a nether portal
2. 1 chunk in front didnt load

## OptiFine Version
1.16.1 pre 9 

## Installation Method
download it click it hit install

![2020-07-23_22 42 58](https://user-images.githubusercontent.com/68710414/88331690-0ab84d00-cd36-11ea-83b9-9bb1a46ff2c9.png)
![2020-07-23_22 43 02](https://user-images.githubusercontent.com/68710414/88331694-0d1aa700-cd36-11ea-8df5-4c3dae5139b5.png)
![2020-07-23_22 43 06](https://user-images.githubusercontent.com/68710414/88331696-0e4bd400-cd36-11ea-85c2-4d79402aef42.png)
![2020-07-23_22 43 07](https://user-images.githubusercontent.com/68710414/88331704-10ae2e00-cd36-11ea-85f6-c862242bcb3b.png)
![2020-07-23_22 43 09](https://user-images.githubusercontent.com/68710414/88331707-1277f180-cd36-11ea-8923-8eb844a64821.png)
![Uploading 2020-07-23_22.43.15.png…]()

## Other Installed Mods
*Every* single mod you have installed, besides OptiFine. Please don't leave anything out, even if you think it has nothing to do with the issue at hand. For long lists of mods, use Pastebin. https://pastebin.com/

**If OptiFine is installed as standalone, remove this section.**

## Log Files/Crash Reports
Any relevant log files. Drag and drop text files here to upload to GitHub directly, OR upload the complete contents to Pastebin. https://pastebin.com/

You can get logs from `.minecraft/logs`, and crash reports from `.minecraft/crash-reports`. 
Locating your `.minecraft` folder will depend entirely on your OS. See this page for details: https://minecraft.gamepedia.com/.minecraft

**DO NOT directly copy and paste log contents here on GitHub.**

## F3 Debug Screenshot
Minecraft's built-in debug screen provides *a lot* of useful information, and should be included even if the issue is not something that can be captured in a still image.

To open this menu, simply press `F3` on your keyboard while in-game. Please ensure the text is easily readable. Depending on the size/resolution of your monitor, you may have to adjust your GUI scale for all text to be completely visible on-screen.

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   - Only OptiFine and Forge
   - Only OptiFine, OptiFabric, and Fabric
- Does this happen without any mods at all?
   - Only Forge/Fabric by itself.
- Does this happen in OptiFine standalone?
- Does this happen in Vanilla without OptiFine?
- Have you tried using a binary search to find which mods cause this issue?
   - To find conflicting mods, split your mods into 2 groups (not including OptiFine/OptiFabric, obviously). Remove one group, and test in-game. Keep the group that has the problem, and repeat until no more mods can be removed without the issue disappearing.
   - Does the issue still happen with only the remaining mods installed?
      - Forge/Fabric and remaining mods, without OptiFine

## Additional Information
Here goes any final remarks and everything else that might not fit in the previous sections.

**Comment by sp614x** [comment]
Fixed in pre9 ninja update.
Please redownload pre9.
