### ISSUE TITLE
[Visual glitch] Invisible entities

### ISSUE THREAD

**Issue by udavid98** [sp614x/optifine#4429]
## Description of Issue
Entities randomly turn into invisible. Mobs, dropped items, falling gravel/sand, boats, even the player itself.

## Steps to Reproduce
1. Just play a couple minutes.

## OptiFine Version
1.16.1-Optifine_HD_U_G2_pre6
1.16.1-Optifine_HD_U_G2_pre8

## Installation Method
I make the jar file executable, run the installer and choose "Install".

## F3 Debug Screenshot

![2020-07-23_23 43 08](https://user-images.githubusercontent.com/48321649/88341824-96ce7280-cd3e-11ea-8924-039b05a6505b.png)

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine? No, just with OptiFine.

## Additional Information
Funfact: Being chased by two invisible hoglins while an invisible ghast is shooting invisible firecharges towards you is NOT fun :D

**Comment by sp614x** [comment]
Fixed in pre9.
