### ISSUE TITLE
[Bug] Banner renders texturless while holding shield

### ISSUE THREAD

**Issue by MrD4RKF0X** [sp614x/optifine#4430]
When wearing a banner on your head, if you have a shield in either your main or offhand, the designed portion of the banner will render as a black texture rather than the banner design/base.

## Steps to Reproduce
1. You have to run /replaceitem entity @s armor.head white_banner
2. Get out a shield, and hold it in either your main or offhand while in third person and watch the banner texture

## OptiFine Version
1.16.1 pre-9

## Installation Method
Installed using the standalone .jar installer

## F3 Debug Screenshot
![2020-07-23_17 43 38](https://user-images.githubusercontent.com/68713328/88341783-3b838c80-cd0c-11ea-9fc1-4345ad6a158a.png)
## Prior Testing
This does NOT happen in vanilla minecraft without optifine

## Additional Information
This was tested on a realm.
Here are a few screenshots from vanilla minecraft compared to screenshots from optifine 1.16.1 pre-9

Vanilla:
![2020-07-23_17 25 07](https://user-images.githubusercontent.com/68713328/88342035-a5039b00-cd0c-11ea-91f5-9c68cc6c6c3c.png)

Optifine:
![2020-07-23_17 42 49](https://user-images.githubusercontent.com/68713328/88342096-c8c6e100-cd0c-11ea-851e-3861d67ee9ab.png)

(They are the same banner)

**Comment by sp614x** [comment]
Fixed in pre11.
