### ISSUE TITLE
[Suggestion] Ability to save the past 30 seconds of gameplay to a video file.

### ISSUE THREAD

**Issue by DitDitGitHub** [sp614x/optifine#4431]
## Description of the new feature
Please provide as much detail as possible

After hitting a customisable keybind, the past 30 seconds of gameplay will be saved to a video file that can be accessed in the .minecraft folder.

**Comment by sp614x** [comment]
This is outside of the OptiFine's scope.
Probably already done by other mods (Replay Mod).
