### ISSUE TITLE
Random invisible entities

### ISSUE THREAD

**Issue by CountVien** [sp614x/optifine#4433]
Before I was using OptiFine 1.16.1 HD U G2 pre4 and everything is fine so far from my side but when I updated to pre8, there are instances of invisible entities.
Like when I'm rowing the boat, the boat somethimes disappear though I'm still rowing and would eventually appear back.
Passive mobs as well like cows or pigs would be disappear sometimes but they are there mooing.

UPDATE1: When I updated to pre9. I've encountered less bugs like this but still face invisible blocks like Clay when I was mining it. I then updated to pre10 and still encountered similar issue this time in Nether where invisible Hoglins attacking me - tried to attack randomly but can't hit them.
 - Temporary solution: Save and Exit world then login back.  The invisible entities seems to appear back once restarted.

**Comment by LateTTG** [comment]
I'm getting the same thing. From experience, it's worse when using a resource pack with CEM / variated mob textures. It's annoying when I can't see hostile mobs…

**Comment by Regnander** [comment]
I believe this was fixed in pre9.

**Comment by LateTTG** [comment]
@Regnander The first time I experienced this was on pre9, it also happened even back to version pre6. I'c currently running pre4 and I haven't encountered this bug since the 3 hours I've been playing.

**Comment by diablo050189** [comment]
Yea I'm having the issue on pre9 as well.

**Comment by CountVien** [comment]
Just edited and updated my main post. Now using pre10.

**Comment by sp614x** [comment]
Should be fixed.
