### ISSUE TITLE
Terrain unloads when going back to a previously loaded area

### ISSUE THREAD

**Issue by firun90** [sp614x/optifine#4434]
## Description of Issue
When I play on a server, fly away in one direction, turn around and fly back, the whole terrain disappears as I approach my starting point. In the distance, I can still see the previously loaded terrain.

## Steps to Reproduce
1. Play on my server
2. Fly away
3. Fly back

## OptiFine Version
OptiFine 1.16.1 HD U G2 pre9

## Installation Method
Standalone installer

## Fabric/Forge Version
On the server: fabric-0.6.1.45 + lithium-0.5.1
(But also happens on a testserver without any modifications)

## Log Files/Crash Reports
Client logfile : https://pastebin.com/BZXdXdZj
Server debug file: https://pastebin.com/inL9q6S8

## F3 Debug Screenshot
![2020-07-24_10 41 52](https://user-images.githubusercontent.com/68732209/88376880-89e16b80-cd9e-11ea-8c1e-0fa6101dde5d.png)

## Prior Testing
ALSO happens with a completely new set up, pure vanilla Server!

Does NOT happen in
- Vanilla client
- OptiFine 1.16.1 HD U G2 pre8 and pre7 (But with them I get invisible entitys after sleeping)
- OptiFine 1.16.1 HD U G2 pre6 (latest fully working release for me)
- Seems to be no issue in singleplayer (can't test completely, since I still have the problem, that the game won't load *any* chunks)

/EDIT: Fixed in pre10 ... Working finde now...

**Comment by sp614x** [comment]
The problem was render distance > 36.
Fixed in 1.16.2 pre6.
