### ISSUE TITLE
Taskbar Image[Category] Short description

### ISSUE THREAD

**Issue by dravenclarke** [sp614x/optifine#4435]
## Steps to Reproduce
1. What do you do... Open optifine 1.16.1 HD U G2 pre9
2. ... there is never an image

## OptiFine Version
optifine 1.16.1 HD U G2 pre9

## Installation Method
How did you install OptiFine? Did you use the included standalone installer, or did you drop the JAR file into your "mods" folder?
standard download, double clicked and it was sent to my launcher

**DO NOT directly copy and paste log contents here on GitHub.**

## F3 Debug Screenshot
Minecraft's built-in debug screen provides *a lot* of useful information, and should be included even if the issue is not something that can be captured in a still image.

To open this menu, simply press `F3` on your keyboard while in-game. Please ensure the text is easily readable. Depending on the size/resolution of your monitor, you may have to adjust your GUI scale for all text to be completely visible on-screen.

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine? - No

- Does this happen in OptiFine standalone? - Yes
- Does this happen in Vanilla without OptiFine? - No

## Additional Information
Here goes any final remarks and everything else that might not fit in the previous sections.

**Comment by sp614x** [comment]
I suppose this is the Windows 10 taskbar.
This is a launcher problem, can't be fixed by OptiFine.
