### ISSUE TITLE
Hotbar icon bug

### ISSUE THREAD

**Issue by NathZen** [sp614x/optifine#4438]
## Description of Issue
Offhand and 9th hotbar icon bug. Offhand Icon merged with 9th item on hotbar. **Fast Render Enabled**

## Steps to Reproduce
1. Turn on Fast Render
2. Put something on Offhand 

## OptiFine Version
1.16.1 G2 pre10

## Installation Method
Standalone

## F3 Debug Screenshot
![2020-07-25_01 25 50](https://user-images.githubusercontent.com/61259322/88423328-d025e180-ce15-11ea-86a5-935624e2d113.png)

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine? **No**

## Additional Information
![2020-07-25_01 28 02](https://user-images.githubusercontent.com/61259322/88423539-1c712180-ce16-11ea-8589-d17089a842fd.png)
![2020-07-25_01 28 06](https://user-images.githubusercontent.com/61259322/88423545-1ed37b80-ce16-11ea-90de-2f0844b4d3f2.png)

**Comment by NathZen** [comment]
Forgot to add this
![2020-07-25_01 17 34](https://user-images.githubusercontent.com/61259322/88423639-46c2df00-ce16-11ea-81e6-d013d6e90579.png)

**Comment by NathZen** [comment]
I think it only happened for Wither Skull (have not tested with other skull) and if it's only 1 item, not stacked.

**Comment by NathZen** [comment]
okay.. any hotbar but only for single Wither Skull
![2020-07-25_13 34 37](https://user-images.githubusercontent.com/61259322/88450799-d8b10300-ce7b-11ea-8146-c5706b66dc15.png)
![2020-07-25_13 34 44](https://user-images.githubusercontent.com/61259322/88450800-da7ac680-ce7b-11ea-855a-33944526fbff.png)
![2020-07-25_13 34 51](https://user-images.githubusercontent.com/61259322/88450802-dd75b700-ce7b-11ea-8121-f8c2d42efeb2.png)
![2020-07-25_13 35 04](https://user-images.githubusercontent.com/61259322/88450804-df3f7a80-ce7b-11ea-966a-4930754eb508.png)

**Comment by sp614x** [comment]
Fixed in pre11.
