### ISSUE TITLE
[Render] Issue with rendering slim players

### ISSUE THREAD

**Issue by TheScrimsKnight** [sp614x/optifine#4440]
## Description of Issues
My player will sometimes glitch out and not display when I go and change perspective. I wonder if it's something to do with a slim character or if it even happens to regular characters.

## Steps to Reproduce
1. What do you do... 
2. ...to find this bug?

## Installation Method
I downloaded optifine by clicking "mirror" on the preview versions tab to start the download. When it had downloaded I clicked it to open it, as you do, to bring up the installer and I hit "install" and I launched Minecraft as usual with the correct optifine version selected.

## Log Files/Crash Reports
It says something about player not rendering correctly or something along those lines. 

## F3 Debug Screenshots
I didn't have any lagometers or the F3 menu open at all when the Issue occured. 

## Prior Testing
This Issue occured when I installed optifine 1.16.1. It has never happened before. 

## Additional Information
I wrote this on a phone so I don't think I can add any screen shots or anything. By the way I recorded the whole thing. I might upload it to TT but I'm unsure.

**Comment by sp614x** [comment]
There shouldn't be adifference if the character is slim or not.
Can you post a debug screenshot (F3)?

**Comment by KaiAF** [comment]
no response from the author.
