### ISSUE TITLE
[Render] X-ray glitch with water & fast render+shaders

### ISSUE THREAD

**Issue by AstronTheWolf** [sp614x/optifine#4442]
## Description of Issue
**_When shaders are enabled with fast render attempting to break a block causes water to X-ray through any surrounding blocks/entities.
Internal shaders are the worst offender.
Actual shaders only suffer from entity X-ray_**

## Steps to Reproduce
**_1. Have shaders and fast render enabled, it also works with the internal shaders.
2. Try breaking a block._**

## OptiFine Version
**_HD G2_pre10_**

## Installation Method
**_Standalone installer_**

## Log Files/Crash Reports
[2020-07-24-2.log](https://github.com/sp614x/optifine/files/4974040/2020-07-24-2.log)

## F3 Debug Screenshot
![2020-07-24_15 06 15](https://user-images.githubusercontent.com/68669212/88431610-51528980-cdc0-11ea-8b3c-3f8c47fb35ba.png)
![2020-07-24_15 29 03](https://user-images.githubusercontent.com/68669212/88432748-6c25fd80-cdc2-11ea-9b11-2413488aa33c.png)
![2020-07-24_15 22 00](https://user-images.githubusercontent.com/68669212/88432259-77c4f480-cdc1-11ea-8fef-0836df7f03c8.png)
![2020-07-24_15 30 51](https://user-images.githubusercontent.com/68669212/88432894-b5764d00-cdc2-11ea-80d9-814d90834ddd.png)

## Prior Testing
- Does this happen in Vanilla without OptiFine?
**No**

## Additional Information
**_This issue does not occur with shaders set to "Off" and fast render on_**

**Comment by EvanSandBacon** [comment]
This also happens with portals

**Comment by sp614x** [comment]
Should be fixed in pre11.
