### ISSUE TITLE
[Render] Some Item doesn't render correctly

### ISSUE THREAD

**Issue by df-f** [sp614x/optifine#4445]
## Description of Issue
Yellow shulker box doesn't render correctly while in the hotbar, and rotten flesh while on the ground before picking up in some angle renders like a simple white square
![2020-07-24_23 40 36](https://user-images.githubusercontent.com/68758105/88438930-12e1bc80-ce0a-11ea-9d16-ea6b1606c4ce.png)

## Steps to Reproduce
1. Go in creative mode
2. Put a yellow shulker box in your hotbar
3. Pick some rotten flesh use Q key to throw some away

## OptiFine Version
Optifine 1.16 pre10

## Installation Method
Standalone installer

## Other Installed Mods
Spawning Spheres by Vanilla Tweaks

## F3 Debug Screenshot
![2020-07-24_23 55 01](https://user-images.githubusercontent.com/68758105/88438465-1f194a00-ce09-11ea-80d1-bd3e1531e19a.png)

## Prior Testing

It didn't happen in vanilla without optifine
![2020-07-24_23 58 21](https://user-images.githubusercontent.com/68758105/88438866-ef1e7680-ce09-11ea-87a3-e5de0d1a4208.png)

**Comment by velexkraian** [comment]
Same problem here

**Comment by sp614x** [comment]
Fixed in pre11.
