### ISSUE TITLE
Can see water through the world when looking at specific angles

### ISSUE THREAD

**Issue by Davidkill257** [sp614x/optifine#4446]
I'm on pre10 for 1.16 and using Internal shaders, it stops happening when Fast Render is DISABLED. So I believe it's a Fast Render Issue
![Untitled](https://user-images.githubusercontent.com/62726130/88441547-a6959780-cdce-11ea-8c2e-916a465d69a8.png)

**Comment by ITCMD** [comment]
Same issue here.

**Comment by EvanSandBacon** [comment]
I also have this problem :(

**Comment by Qawaka** [comment]
Happens to me with water as well as glass.

**Comment by JasonHorkles** [comment]
Water seems to be buggy with internal shaders and fast render as water appears bright at night as well
![image](https://user-images.githubusercontent.com/51760372/88492930-9d8dfd00-cf6b-11ea-9167-956475c05b85.png)

**Comment by sp614x** [comment]
Fixed in pre11.

**Comment by ITCMD** [comment]
This issue exists for 1.15.2, should I make a seperate section?
