### ISSUE TITLE
[Render] flowing water glitches with render regions

### ISSUE THREAD

**Issue by fayer3** [sp614x/optifine#4447]
## Description of Issue
flowing water is more transparent on some spots from different viewing angles when enabling render regions.

## Steps to Reproduce
1. enable render regions
2. look at flowing water

## OptiFine Version
1.16.1_HD_U_G2_pre10

## Installation Method
standalone installer

## F3 Debug Screenshot
![2020-07-25_01 10 38](https://user-images.githubusercontent.com/8282299/88442353-7ffa4f80-ce14-11ea-8c60-3632b3580301.png)
![2020-07-25_01 09 26](https://user-images.githubusercontent.com/8282299/88442360-84bf0380-ce14-11ea-8ac4-769ab86d4312.png)

## Prior Testing
does not happen with vanilla. 
only happens when enabling render regions.
graphics option fast/fancy/fabulous doesn't affect this.

**Comment by MichaelsoftBinbows** [comment]
This also occurs with stained glass underwater
![2020-07-28_14 22 35](https://user-images.githubusercontent.com/68920879/88707618-802e6f80-d0e0-11ea-9ec3-efa1cce07352.png)

**Comment by sp614x** [comment]
Fixed in pre11.

**Comment by fayer3** [comment]
not fixed in pre11, still happens
also that's not a fast render problem, but a render regions Problem
![2020-07-29_12 48 29](https://user-images.githubusercontent.com/8282299/88791375-e6c39400-d199-11ea-9593-001e76f326a8.png)
![2020-07-29_12 48 37](https://user-images.githubusercontent.com/8282299/88791385-e9be8480-d199-11ea-8611-c3504d9bd54d.png)
