### ISSUE TITLE
[1.16.1] Geometry Trace (seus ptgi e12) Bug on AMD graphics (rx580)

### ISSUE THREAD

**Issue by SomeApples09** [sp614x/optifine#4449]
## Description of Issue
Deep black shadows on some blocks when geometry trace is set to 2 and 1, bug seems to disapear when set to 0 

## OptiFine Version
OptiFine 1.16.1 HD U G2 pre10
--

## Installation Method
Installed by exe file

## F3 Debug Screenshot
Geometry trace set to 0

![2020-07-24_21 08 25](https://user-images.githubusercontent.com/68762884/88446716-d30edb00-cdf1-11ea-8342-22d02ece76c6.png)

Geometry trace set to 1

![2020-07-24_21 06 33](https://user-images.githubusercontent.com/68762884/88446685-a8bd1d80-cdf1-11ea-937f-ea381d00d940.png)

Geometry trace set to 2

![2020-07-24_21 07 41](https://user-images.githubusercontent.com/68762884/88446700-bc688400-cdf1-11ea-89b4-708b2a5d1d34.png)

**Comment by Rmdhn1** [comment]
Same problem, it'll also sometimes have blocks kinda surrounded by dark even on geometry trace 0

**Comment by Rmdhn1** [comment]
> Same problem, it'll also sometimes have blocks kinda surrounded by dark even on geometry trace 0

oh yeah, I have RX 570

**Comment by cellos51** [comment]
I had that problem too until I downgraded my video drivers to 20.5.1

**Comment by N2O-yt** [comment]
I have the same bug i have an AMD R9 280X

**Comment by SnaveSutit** [comment]
I have the same issue with my AMD RX Radeon 5700XT

**Comment by S3BLtv** [comment]
Same issue i have a rx570 i think its only an AMD bug. got any one a solution

**Comment by SnaveSutit** [comment]
I was able to fix the issue by downgrading my graphics driver to
version 20.5.1

**Comment by avanishsubbiah** [comment]
I'm having the same issue with a 6800XT. I can't downgrade the drivers because then it wouldn't support my card, the newest 20.11.2 Adrenaline drivers are the only drivers that work with the 6000 series.

**Comment by S3BLtv** [comment]
I won´t downgrade it is there any other solution

**Comment by Rmdhn1** [comment]
Lucky!!

**Comment by avanishsubbiah** [comment]
Btw this problem is still happening on the 1.16.4 version as well. My current Radeon drivers are 20.11.3

**Comment by Juxive** [comment]
Also having the issue with the 5600XT, definitely an AMD thing.

**Comment by iToxic9** [comment]
Yes it is an AMD thing, the creator says on his Patreon that it is not compatible with AMD graphic cards and he will be looking into integrating it later

**Comment by sp614x** [comment]
This is a SEUS issue with AMD, fixable by downgrading graphics drivers.
Not related to OptiFine.
