### ISSUE TITLE
[Category] Capes

### ISSUE THREAD

**Issue by Exfiltrations** [sp614x/optifine#4455]
## Description of Issue
my cape won't load on any version before optifine 1.16.1 and im not even sure if it loads on that version because optifine 1.16.1 doesn't work for me. and obviously, I checked my settings to make sure show capes was on and I tried changing my cape design and reloaded it on 1.13.2 but it wont show up.

## Steps to Reproduce
load optifine in any version before 1.16.1 (I usually use 1.13.2 e7)

## OptiFine Version
the version I use all the time is 1.13.2 e7, but I also tested 1.14.3 f1 to make sure it wasn't just 1.13

## Installation Method
standalone launcher

## Log Files/Crash Reports
Any relevant log files. Drag and drop text files here to upload to GitHub directly, OR upload the complete contents to Pastebin. https://pastebin.com/

You can get logs from `.minecraft/logs`, and crash reports from `.minecraft/crash-reports`. 
Locating your `.minecraft` folder will depend entirely on your OS. See this page for details: https://minecraft.gamepedia.com/.minecraft

**DO NOT directly copy and paste log contents here on GitHub.**

no relevant log files

## F3 Debug Screenshot
Minecraft's built-in debug screen provides *a lot* of useful information, and should be included even if the issue is not something that can be captured in a still image.

To open this menu, simply press `F3` on your keyboard while in-game. Please ensure the text is easily readable. Depending on the size/resolution of your monitor, you may have to adjust your GUI scale for all text to be completely visible on-screen.

![f3 for cape bug](https://user-images.githubusercontent.com/68782938/88460517-c37fa880-ce6a-11ea-9e50-92c9e927dbe1.png)

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?

not possible because its an optifine cape

## Additional Information
(I zoomed to show that I have optifine enabled and the cape wont appear) and just to be sure I did 2 different versions 
Top picture is 1.13.2 e7 | Bottom picture is 1.14.3 f1
![cape bug](https://user-images.githubusercontent.com/68782938/88460518-ca0e2000-ce6a-11ea-9d7b-ab495dcf33f7.png)
![cape bug 1 14](https://user-images.githubusercontent.com/68782938/88460629-82d45f00-ce6b-11ea-99c3-e8fbd7b1a58a.png)

**Comment by Deviouslrd** [comment]
Its an issue with the optifine cape servers.

**Comment by Exfiltrations** [comment]
> Its an issue with the optifine cape servers.

oooh ok was making sure it wasn't just me, ty for letting me know
