### ISSUE TITLE
Opti cape not showing after changing it

### ISSUE THREAD

**Issue by Brucewastaken** [sp614x/optifine#4457]
I bought the cape a few days ago, and it was working fine, but today i wanted to change the pattern on it, so i logged on with 1.16 and I went to settings -> skin customization -> cape -> open cape editor and changed it. When I came back after saving it, i pressed reload cape, but it still didn't show. I then went on to 1.8.9 on badlion client with optifine and tried reloading the cape, but it still didn't work. Is it because I have to wait a little while or log off before the cape shows/updates? im a little confused. Help would be appreciated C:

**Comment by Deviouslrd** [comment]
Issue with the optifine cape servers atm.

**Comment by Brucewastaken** [comment]
ok the cape is back on C:
