### ISSUE TITLE
[1.16.1 HD U G2 pre10] Colouring error in hotbar due to fast render

### ISSUE THREAD

**Issue by spacepill0w** [sp614x/optifine#4458]
## Description of Issue
Heyo. Noticed that there's some strange colour affecting some items. It's appeared on beds in my hotbar, and on some tools once the durability bar is showing. This only occurs when *not* viewing one's inventory. This happens only on 1.16.1 optifine, and not in vanilla.
**EDIT: This seems to be an issue with 'fast render'. Turning off fast render fixes this issue.**
## Steps to Reproduce
1. Have a tool with less than 100% durability in your hotbar, or other(?) items.
2. (EDIT) Have fast render turned on

## OptiFine Version
1.16.1 HD U G2 pre10

## Installation Method
Installed via installer.

## Log Files/Crash Reports

[https://pastebin.com/Lv3vSpiU](url)

## Additional Information
Here goes any final remarks and everything else that might not fit in the previous sections.
![hotbar error](https://user-images.githubusercontent.com/68788165/88464092-f08d8480-ce85-11ea-8516-7cafcf76afcd.png)
![okay in inventory](https://user-images.githubusercontent.com/68788165/88464094-f4210b80-ce85-11ea-8e68-1d51fb6ef14c.png)
![F3 hotbar error](https://user-images.githubusercontent.com/68788165/88464096-f6836580-ce85-11ea-8326-6a83df0c36f6.png)

**Comment by Josslyn81** [comment]
I'm experiencing the exact same problem. Definitely makes it hard to play! <3 Optifine

**Comment by unknowngamer2005** [comment]
Yeah pretty annoying but i found that _fast math_ option does this

**Comment by spacepill0w** [comment]
> Yeah pretty annoying but i found that _fast render_ option does this

Yup, seems like a fast render issue.

**Comment by sp614x** [comment]
Fixed in pre11.
