### ISSUE TITLE
[CEM] You can't change the model of Minecart with Command Block/Hopper/Furnace/Chest

### ISSUE THREAD

**Issue by LorenzoF06** [sp614x/optifine#4459]
## Description of Issue
I made a custom model for the Minecart (which is a sort of bulldozer). I can use that model for Minecart, Minecart with TNT and Minecart with Spawner. It doesn't work with other Minecarts.
![2020-07-25_21 04 18](https://user-images.githubusercontent.com/37110006/88464671-fd799a80-cebc-11ea-8142-e7831ed527cd.png)

## Steps to Reproduce
1. Use in your resource pack a custom model named "minecart.jem"
2. Just log in-game and see that only that one changed (apart from TNT and Spawner which have a different model)

## OptiFine Version
Minecraft 1.16.1 with OptiFine 1.16.1 HD U G2 pre09.

## Additional Information
It works well with OptiFine 1.14.2 HD U F5, it doesn't in 1.16.1. I haven't tried with 1.15 but I'm pretty sure it doesn't work well the same.

## Installation Method
Installed via the standalone installer.

**Comment by KaiAF** [comment]
I believe this was fixed in 1.16.5 G8 pre10
- added CEM for all minecarts (chest, command block, furnace and hopper)
