### ISSUE TITLE
Force load chunks

### ISSUE THREAD

**Issue by Opptitronica** [sp614x/optifine#446]
I'm sure many people who take screenshots will like this feature. Basically what it would do is force render all the chunks in. Maybe have an option to only force render in chunks that are in front of the camera reducing the strain so it doesn't have to force load chunks that aren't being seen. This would be very useful for people like Past Life Pro who do cinematics and people who take ridiculously far render distance screenshots. Possibly could achieve this by freezing other in game processes and forcing the memory and cpu to load chunks resulting in a temporary freeze which goes away once all chunks are rendered returning Minecraft to its usual state.

**Comment by HeartyYF** [comment]
I'd love to say I like this feature, but in multi-player world, I don't think this will work...Is there any way to force load chunks in servers?

**Comment by mindforger** [comment]
well, you could probably fyl around the region and stop the client from unloading the cached chunks but this would consume a lot memory

**Comment by sp614x** [comment]
You can set Chunk Updates -> 5 and Dynamic Updates -> ON, then waiti a little without moving.
The game will be effectively loading 10 chunks per frame, so with 50 FPS this gives 500 chunks per second.
On Render Distance 32 there are about 10000 visible 3d chunks so it should take 20 sec to load them all.

**Comment by Opptitronica** [comment]
Okay then how about increased render distance such as 64 or 128?

**Comment by sp614x** [comment]
Updated preview B7 for 1.11.2.
- added F3+L to force load all visible chunks
