### ISSUE TITLE
[CEM] Spider/Cave Spider custom model color not working properly 

### ISSUE THREAD

**Issue by DeathEskol** [sp614x/optifine#4460]
## Description of Issue
If make a resourcepack with .jmp with custom texture .png file to spider or cave spider the colors will not correspond to .png file.

![example](https://user-images.githubusercontent.com/37559744/88465571-792b1580-cec4-11ea-8ea5-a0c173c3bdf2.png)
![example_2](https://user-images.githubusercontent.com/37559744/88465641-f5bdf400-cec4-11ea-9c3b-d6c1d4e0732e.png)

## Steps to Reproduce
Using custom .jmp with custom texture .png file to spider or cave spider. You can use [this example resourcepack and world](https://github.com/sp614x/optifine/files/4976359/test_spider.zip) to reproduce it. 

## OptiFine Version
1.16.1_HD_U_G2_pre5

## Installation Method
Installed with "preview_OptiFine_1.16.1_HD_U_G2_pre5.jar", using standalone installer.

## Prior Testing

- Does this happen in Vanilla without OptiFine?
No, only with CEM.

- Does this happen to other entities?
I only find this error on spider and cave spider.

## Additional Information
Works perfectly in Optifeine 1.14.4_HD_U_F4_pre2.

**Comment by sp614x** [comment]
Is it working in latest pre12 ?

**Comment by ewanhowell5195** [comment]
cant recreate
![image](https://user-images.githubusercontent.com/48070995/112700182-733b6900-8e85-11eb-806f-8590046f05e3.png)

**Comment by KaiAF** [comment]
Is this still an issue? @DeathEskol
