### ISSUE TITLE
[Shaders] Portal frames, Top of water etc. show when mining a block with shaders turned on

### ISSUE THREAD

**Issue by zeven1707** [sp614x/optifine#4461]
When the "destroying" texture is shown on a block being mined, the top layer of water, portal frames and more appear through the world.

## OptiFine Version
OptiFine 1.16.1 HD U G2 pre10

## Installation Method
Opened with JAVA.

## F3 Debug Screenshot
Internal Shaders: https://imgur.com/a/2MBGGag
Sildurs Shaders 1.28 High: https://imgur.com/a/R34u4NI

This only happens when a shaderspack is "on".

**Comment by mbalc** [comment]
I just noticed that this does happen for me with `BSL 1.15 EDIT` shader pack; it looks like a temporary fix for me is to disable `Performance > Fast Render` when using shaders.

**Comment by zeven1707** [comment]
> I just noticed that this does happen for me with `BSL 1.15 EDIT` shader pack; it looks like a temporary fix for me is to disable `Performance > Fast Render` when using shaders.

**Comment by zeven1707** [comment]
> I just noticed that this does happen for me with `BSL 1.15 EDIT` shader pack; it looks like a temporary fix for me is to disable `Performance > Fast Render` when using shaders.

The Fast Render was the issue, good to know. Thanks.

**Comment by sp614x** [comment]
Fixed in pre11.
