### ISSUE TITLE
[Lighting] Smooth light dont work in warm ocean biomes

### ISSUE THREAD

**Issue by MrmaximoExcssum** [sp614x/optifine#4462]
![2020-07-26_01 00 57](https://user-images.githubusercontent.com/49599905/88467865-05950280-cedc-11ea-8825-7b8627f53769.png)
Light issue in warm oshien biome. Smooth light dont fix this.

**Comment by muzikbike** [comment]
This is a general underwater lighting issue

**Comment by sp614x** [comment]
Should work now
