### ISSUE TITLE
Massive Blocklag when breaking/placing blocks that use connected textures

### ISSUE THREAD

**Issue by Lucipo** [sp614x/optifine#4464]
## Description of Issue
There is huge lag spikes when breaking/placing blocks with a resource pack that uses connected textures often (In this case, bettervanillabuilding 1.16)

## Steps to Reproduce
1. Take a resource pack that uses connected textures to blend natural blocks or any block
2. Place or break block, will cause massive lag spikes in most chunks

## OptiFine Version
1.16.1 pre10

## Installation Method
Standalone, vanilla 1.16.1 w/ optifine profile

## F3 Debug Screenshot
![image](https://user-images.githubusercontent.com/36358294/88470952-674b7180-cec8-11ea-97b3-da0c4c903f3a.png)

## Prior Testing
- Does this happen in Vanilla without OptiFine?
No, it does not, due to vanilla not having connected textures.

## Additional Information
I know that a lot of texture changes has to be done when a lot of blocks are being destroyed, but any resource pack that tries to take advantage of connected textures will suffer from huge lag. I also noticed that if you are, for instance, insta-breaking a ton of dirt that is not connected to any other block and does not use connected textures, it will still have a lot of lag. Maybe some sort of system to reduce lag with blocks that do not use connected textures with adjacent blocks could fix some of the lag experienced by many Optifine users. This is the resource pack in question that I used to test, since nearly all of it's features use connected textures: https://www.planetminecraft.com/texture-pack/bettervanillabuilding-v-6-1-12-and-1-13-4105787/ 
FPS walking around: 110-150
FPS when constantly breaking blocks: 46-70. Turned off connected textures and kept same resource packs and the lag disappeared. Same results for fast and fancy connected textures.

**Comment by sp614x** [comment]
Better Vanilla Building uses a lot of overlays and this needs a lot of block checks when generating the overlays.

**Comment by sp614x** [comment]
Added some optimizations to the overlay checks, coming in pre12.
