### ISSUE TITLE
[Emmessive -CEM] CEM Spider emmesive doesn`t work with preview_OptiFine_1.16.1_HD_U_G2_pre10 any more

### ISSUE THREAD

**Issue by Norzeteus** [sp614x/optifine#4467]
Description of Issue
My new  CEM-spider emmesive overlay doesn`t work with preview_OptiFine_1.16.1_HD_U_G2_pre10,
versions before it did...

 OptiFine Version: preview_OptiFine_1.16.1_HD_U_G2_pre10

 Installation Method
standalone installer, no other mods

![spider cem emmessive](https://user-images.githubusercontent.com/24456750/88474887-2cc6f080-cf2b-11ea-8126-7ed115c987f5.png)

**Comment by sp614x** [comment]
Does it work in pre11?

**Comment by Norzeteus** [comment]
Fast render was disabled, doesn`t work...
[spider-cem.zip](https://github.com/sp614x/optifine/files/4999747/spider-cem.zip)

**Comment by sp614x** [comment]
Fixed in pre13.
