### ISSUE TITLE
[CIT] Custom texture/model when all the specified nbt tags are missing.

### ISSUE THREAD

**Issue by Lassebq** [sp614x/optifine#4468]
Basically, if the item doesn't have an nbt tag, it'll use a different texture/model

`type=item`
Leather Helmet
`items=298`
Dye color
`nbt.display.color=`
or
`nbt.display.color=regex:!*`
 I expected it to check if the nbt tag is missing with the condition above, but instead it's not applied to any item.
`texture=./undyed_leather_helmet`

**Comment by sp614x** [comment]
This should be working `nbt.display.color=!regex:*`
