### ISSUE TITLE
Bar under the tools kinda broken dont know  how to name  it

### ISSUE THREAD

**Issue by SAPET123** [sp614x/optifine#4470]
![Bez ](https://user-images.githubusercontent.com/63538256/88480961-5565df00-cf59-11ea-8170-aa9ced009116.png)
![Bezu](https://user-images.githubusercontent.com/63538256/88480963-572fa280-cf59-11ea-94a4-e5af5070de0e.png)
![vu](https://user-images.githubusercontent.com/63538256/88480964-57c83900-cf59-11ea-8107-7ae7d09c5c2f.png)
![u](https://user-images.githubusercontent.com/63538256/88480965-5860cf80-cf59-11ea-8fb8-f69697fcd540.png)

**Comment by Dragon8oy** [comment]
Same issue on Linux, with preview 10 of 1.16.1.

**Comment by zan3tr** [comment]
Also having this issue on Windows, preview 10 of 1.16.1

**Comment by SAPET123** [comment]
Btw forgot to mension that this happens when I generate a new world in my other worlds that I created in older versions this isnt happening

**Comment by sp614x** [comment]
Fixed in pre11.
