### ISSUE TITLE
OpenGL Error: 1281 (Invalid value) when fabulous graphics are on.

### ISSUE THREAD

**Issue by Sk3l3tr0n2** [sp614x/optifine#4474]
When I turn on fabulous graphics, my minecraft chat is spammed with "OpenGL Error: 1281 (Invalid value)

The optifine version is Optifine 1.16.1 pre10 and I installed it the regular way, downloading it from the site, opening it, then clicking install, and I have no other mods installed when it happens.

**Comment by Nickzz-exe** [comment]
Same here, do u have a fix?

**Comment by sp614x** [comment]
Duplicate of #4692
