### ISSUE TITLE
Screen Flickering issue

### ISSUE THREAD

**Issue by Titan-Warrior** [sp614x/optifine#4475]
## Description of Issue
Screen flickering issue on Minecraft Java Edition 1.12+.
Currently on version 1.14.4 and using "1.14.4-Optifine_HD_U_F5" but this also happens on 1.15.x pre-versions. 
I have changed my settings in game from FANCY = FAST.. but it is still an ongoing issue. 
I also updated my drivers to my latest versions.. and so forth. I am also running Java 8 on my laptop.

## OptiFine Version
1.12.2-OptiFine_HD_U_F5, 1.14.4-Optifine_HD_U_F5, 1.15.2-Optifine_HD_U_G1_pre30

## Installation Method
Standalone installer

## Log Files/Crash Reports
Latest Log file (1.14.4):
https://pastebin.com/8XnwPAYN

## F3 Debug Screenshot
(1.14.4)
![2020-07-27_16 49 52](https://user-images.githubusercontent.com/68863502/88562952-45b5cb80-d029-11ea-997d-caadbec1709b.png)

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
Very rarely without Optifine

## Additional Information
This has been an ongoing issue since January 31st 2020

**Comment by sp614x** [comment]
Looks like a driver problem.
Disabling VBO and VSync may help.

**Comment by Titan-Warrior** [comment]
I have no idea what VBO or Vsync is.. or how to enable and/or disable it?
All my drivers are Upto date.. and so is my Operating System
