### ISSUE TITLE
Mob head texture glitches in the hotbar when fast render is turned on.

### ISSUE THREAD

**Issue by Shymon184** [sp614x/optifine#4477]
## Description of Issue
When you put skull/head in your hotbar and you put any item/block right of the skull, the skull takes the texture of said item and merges it with its own texture, then the texture of the item disappears (this happens instantly when you place it in the hotbar), yet it is still present in the hotbar and when you select it, you can see the item in your hand and you can normally use it. If you put multiple skulls in your hotbar; the first skull from the left takes the texture of the first non-head item right of the skull, other skulls are invisible along with the non-head item (if there are multiple non-head items right of the skull, the other items are visible). If there are no non-head items right of the skull, the skull texture remains correct; if there are only other skulls right of the said skull, they remain invisible. This issue only affects hotbar, when you open inventory, everything displays correctly in the inventory window.
  
![Screen Shot 2020-07-27 at 17 53 48](https://user-images.githubusercontent.com/68184212/88569302-88cc6a80-d03a-11ea-8ea2-e7d836c96e4f.png)
      
![Screen Shot 2020-07-27 at 17 55 22](https://user-images.githubusercontent.com/68184212/88569347-9b46a400-d03a-11ea-9afa-77f3b6650bc2.png)

![Screen Shot 2020-07-27 at 17 55 53](https://user-images.githubusercontent.com/68184212/88569422-b3b6be80-d03a-11ea-9824-a8355a4effe1.png)

## Steps to Reproduce
1. Put any kind of vanilla head/skull (even the dragon head) in your hotbar.
2. Put any block/item to the right of the skull.

## OptiFine Version
OptiFine 1.16.1 HD U G2 pre10

## Installation Method
I installed OptiFine using the installer.

## Log Files/Crash Reports
[2020-07-27-5.log.gz](https://github.com/sp614x/optifine/files/4983196/2020-07-27-5.log.gz)

[debug.log](https://github.com/sp614x/optifine/files/4983201/debug.log)

https://pastebin.com/ij95kPdD

## F3 Debug Screenshot
![Screen Shot 2020-07-27 at 18 24 01](https://user-images.githubusercontent.com/68184212/88566509-66385280-d036-11ea-9a36-af7b8fd36ba2.png)

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
**No, it does not happen in Vanilla.**

## Additional Information
Custom skulls are not affected by this issue.
This only happens when Fast Render is turned **on**.

**Comment by sp614x** [comment]
Fixed in pre11.
