### ISSUE TITLE
Optifine bug.

### ISSUE THREAD

**Issue by mikolps** [sp614x/optifine#4478]
Hello, i have found a optifine bug. this bug is actually ruining the whole game, i cannot play.
So basically, the Background for the title screen is completely Gray.
Sound does not work either, i made a video about the problem.
i highly suggest you watch that. Thanks, RMYT
https://anonfiles.com/nchc38I2o5/2020-07-27_19-45-29_mkv
/\ The Video /\

**Comment by mikolps** [comment]
nevermind, i just forgot to download 1.16 propoerly :)

**Comment by sp614x** [comment]
ok
