### ISSUE TITLE
[Visual Bug] Digging effect shows at a strange angle and not on the block I am mining

### ISSUE THREAD

**Issue by MrMelon54** [sp614x/optifine#4485]
## Steps to Reproduce
1. Mine for a while
2. Bug happens

I have tried restarting my game and the bug still occurs.

## OptiFine Version
OptiFine 1.16.1 HD U G2 pre10

## Installation Method
Dropped in the mods folder

## Fabric/Forge Version
Fabric installed using MultiMC install button

## OptiFabric Version
v1.1.0-beta2

## Other Installed Mods
CraftPresence
OptiFabric
Optifine
ModMenu
Shulker Box Tooltip

## F3 Debug Screenshot
![2020-07-28_17 30 40](https://user-images.githubusercontent.com/48031324/88694188-17eb8800-d0f8-11ea-9534-626a81984d7f.png)

## Prior Testing
Occurs in both singleplayer and multiplayer.
In the screenshot I am using a customised vanilla tweaks pack but it also occurs without any texture packs.
I have tested vanilla and the bug doesn't seem to occur.

## Update
After further testing I realised it only occurs if chunk boarders are showing.

**Comment by sp614x** [comment]
Disable integrated shaders, they are only for testing.
