### ISSUE TITLE
[Bug Report] Parallax Occlusion Mapping Bug

### ISSUE THREAD

**Issue by DayneTreader** [sp614x/optifine#4486]
## Description of Issue
With this new release, activating Parallax Occlusion Mapping (POM) in a shader (namely SEUS) causes items in the right hand to disappear, and items in the left hand to severely plummet in texture resolution. I am not sure what the trigger is, whether it is specific lighting conditions or specific view angles or even something else.

## Steps to Reproduce
1. Updated Optifine from pre4 to pre10
2. Download and install any shader that supports POM
3. Turn on POM

## OptiFine Version
OptiFine 1.16.1 HD U G2 pre10

## Installation Method
Standalone Installer

## F3 Debug Screenshot
![MC_Optifine_Report](https://user-images.githubusercontent.com/57878576/88726398-81f93280-d0e2-11ea-8f7f-263d9ec46dc5.png)

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
No

## Additional Information
This issue does not occur without a shader

**Comment by sp614x** [comment]
Have you tried with pre11?

**Comment by DayneTreader** [comment]
I just updated to pre11 and the issue has been resolved. I have however discovered a related issue - the texture for the bed is completely black. The shape is there and is correct, but the texture itself is completely black.

**Comment by sp614x** [comment]
Should be fixed in pre14.
