### ISSUE TITLE
[Visual Bug] Glass pane CTM problem

### ISSUE THREAD

**Issue by JediMaster211** [sp614x/optifine#4493]
## Description of Issue
I use a resource pack that changes certain glass textures.
CTM on unchanged glass panes doesn't connect up properly on north and west sides
I am aware that the problem is caused by an issue with glass pane template models and is fixed by optifine normally with different models.
Is it possible to edit the glass pane template model in the resource pack to make it work with CTM, and if so how?

## OptiFine Version
Self-explanatory. 

## Installation Method
Default Installer

## Other Installed Mods
Nothing

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
- Vanilla doesn't have CTM capability

## Screenshot
![2020-07-29_12 17 32](https://user-images.githubusercontent.com/68950792/88793922-87638500-d195-11ea-9577-53ce52985722.png)

**Comment by JediMaster211** [comment]
Never mind, I fixed it.

**Comment by Prodeathbomb** [comment]
Im having this issue on every glass connected texture pack that has a boarder ive looked up different ways to fix it and i just cant. im on optifine 1.19.4 https://www.planetminecraft.com/texture-pack/kemiu-s-medieval-glass-but-connected/ this is the texture pack i would like to use but all similar ones are doing the same thing
