### ISSUE TITLE
[CEM] OptiFine isn't loading .jem file 

### ISSUE THREAD

**Issue by Dight67** [sp614x/optifine#4495]
![javaw_wY04sIREY1](https://user-images.githubusercontent.com/68953332/88798523-4f643e00-d1a5-11ea-9ee4-6a773b95b25c.png)
## Description of Issue
Wolf CEM dependent on tametag isn't loading

## OptiFine Version
1.16.1 OptiFine HD U G2 pre11

## Installation Method
Standalone installer

## F3 Debug Screenshot
![javaw_PxIygZ3ydj](https://user-images.githubusercontent.com/68953332/88799026-242e1e80-d1a6-11ea-9ef6-06da871336c5.png)

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine? 
  CEM only work with OptiFine

## Additional Information
Works with <1.14.4, not work with any of 1.15.2 and any of 1.16.1

**Comment by Dight67** [comment]
[UPDATE] still bugged on official release OptiFine_1.16.1_HD_U_G2

**Comment by Po-C4** [comment]
I tried to transform boats in karts, the model shows up but it uses the vanilla texture instead of the provided texture. So I'm guessing it might be the same issue

**Comment by ewanhowell5195** [comment]
as far as i can tell, there is no issue with wolf cem. (i use it a lot and have never encountered an issue). Most likely something changed in the model. I recommend using the CEM Template Loader plugin for blockbench to load a template model, and then build a working wolf model off of that.
