### ISSUE TITLE
[optifine bug] Slimeblock doesn't work right with pistons

### ISSUE THREAD

**Issue by Randallsthename** [sp614x/optifine#4496]
## Description of Issue
If a player stands on a slimeblock on top of a piston and activates it, it won't send the player up the right amount of block height

## Steps to Reproduce
1. stand on top slimeblock with piston under it
2. activate piston, vanilla minecraft sends you higher in the air then in optifine 1.16.1 pre11 version

## OptiFine Version
1.16.1 pre11

## Installation Method
Standard optifine installer obtained through optifine.net

## Other Installed Mods
No other mods just sildur's vibrant shaders pack

## Log Files/Crash Reports
n/a

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
                                      
                        **No, this issue is only in optifine 1.16.1 in ALL pre-release versions (1.15.1 pre-releases didn't have this issue)**

## Additional Information
From my tests it seems like sometimes the piston slime blocks send you the correct jump height but its rare and it breaks A LOT of redstone devices and elevators

**Comment by sp614x** [comment]
This is really strange as OptiFine shouldn't affect the game mechanics.

**Comment by Randallsthename** [comment]
> This is really strange as OptiFine shouldn't affect the game mechanics.

I know, I have a bunch of elevators using slime blocks and I was really confused because they worked fine using 1.15.1 optifine pre-releases but using the 1.16.1 optifine breaks it no matter what settings i use and SOMETIMES it works fine, ive gotten max 3 consecutive correct height achieved but never more, VERY inconsistant for some reason.

**Comment by fayer3** [comment]
this is probably this(https://bugs.mojang.com/browse/MC-190849) vanilla bug. Can you test it in vanilla 1.16.1.
It was marked as fixed in one of the snapshots after 1.16.1 came out.

**Comment by Randallsthename** [comment]
> this is probably this(https://bugs.mojang.com/browse/MC-190849) vanilla bug. Can you test it in vanilla 1.16.1.
> It was marked as fixed in one of the snapshots after 1.16.1 came out.

I can 100% confirm that the bug is only related to optifine as vanilla 1.16.1 DOES NOT have this bug, I was running day 1 vanilla minecraft 1.16 and it didn't have the bug either, this issue only happens when running any optifine 1.16 pre-release

**Comment by Randallsthename** [comment]
> this is probably this(https://bugs.mojang.com/browse/MC-190849) vanilla bug. Can you test it in vanilla 1.16.1.
> It was marked as fixed in one of the snapshots after 1.16.1 came out.

I swear I did tests in vanilla and optifine and was certain it was optifine, but after trying it again today, I feel like an idiot. THIS BUG HAPPENS IN VANILLA TOO
