### ISSUE TITLE
[Visual Bug] Charged creeper effect frozen

### ISSUE THREAD

**Issue by Dragon8oy** [sp614x/optifine#4497]
## Description of Issue
 - The charged effect of a charged creeper is frozen on the first frame of its animation when using a shaderpack. I tested with SEUS Renewed and Sildurs' Vibrant Medium, and the issue was present on both of these, so I'm fairly sure it's an Optifine issue.

## Steps to Reproduce
1. Install OptiFine
2. Enable shaders
3. Load a world
4. Spawn a charged creeper

## OptiFine Version
 - 1.16.1 pre 9-11 (May effect earlier versions, I haven't tested)

## Installation Method
 - Standalone installer

## Log Files/Crash Reports
[latest.log](https://github.com/sp614x/optifine/files/4996683/latest.log)

## F3 Debug Screenshot
![2020-07-29_19 19 44](https://user-images.githubusercontent.com/33733427/88838042-de3a8000-d1d0-11ea-99cf-7bc99e9bbde2.png)

## Prior Testing
If you've installed standalone:
- No, because shader packs aren't supported without OptiFine

**Comment by sp614x** [comment]
Works for me in pre12.
The creeper glowing layer is randered strange with Sildur's Vibrant shaders, but the animation is working.

**Comment by Dragon8oy** [comment]
I tried this again with a fresh copy of Sildurs, a fresh installation of Minecraft and a fresh installation of OptiFine pre 12, and the issue is still present with both Sildurs and SEUS.
If it helps, I'm running Debian Unstable with Linux 5.7.9-generic, and using openjdk 11.0.8.

**Comment by Cat-Lady** [comment]
Having exactly same issue with latest opptifine for 16.4, also using linux builds. Optifine on linux specific issue?
