### ISSUE TITLE
opti fine Zoom Cinematic mode bug

### ISSUE THREAD

**Issue by Maximus10yt** [sp614x/optifine#4500]
So I already submitted a bug report using preview 9 saying that when I used the zoom feature the game would switch to cinematic mode. Well I got a response and on the change log for previews 10 and 11 it said that it was fixed but I'm still experiencing the same problem. I have a good computer that works well but I haven't see this problem with anyone else. I'm using an HP Pavilion Windows 10 Java Edition if that helps at all I just wanted to let you know that it's still there seeing that the change log said it was fixed. Hopefully you figure it out.

**Comment by sp614x** [comment]
What was fixed was that zoom was disabling the cinematic camera if it was already enabled.
The zoom using cinematic camera is working as intended.
