### ISSUE TITLE
[shaders] Game crash when changing shaders

### ISSUE THREAD

**Issue by DEM2215** [sp614x/optifine#4506]
## Description of Issue
i ussually use Sildurs shaders, but, when i want to change to another shaders. for example, chocapic (any version) or SEUS, my game just crash, y have an CPU AMD Ryzen 5 2400g, and a graphic card RX 580 8GB.

## OptiFine Version
al previews of 1.16.1

## Installation Method
i used the included installer

## Fabric/Forge Version
none, i dont use mods

## Other Installed Mods
none

[hs_err_pid936.log](https://github.com/sp614x/optifine/files/5003886/hs_err_pid936.log)
![image](https://user-images.githubusercontent.com/69017500/88976998-6ed99480-d293-11ea-8885-a058780429b2.png)

**Comment by sp614x** [comment]
The AMD graphics driver crashes when trying to compile the shaders.
Updating/downgrading the drivers may help.

```
# Problematic frame:
# C  [atio6axx.dll+0xb6edf1]
#
...
Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  org.lwjgl.opengl.ARBShaderObjects.nglShaderSourceARB(IIJJ)V+0
j  org.lwjgl.opengl.ARBShaderObjects.glShaderSourceARB(ILjava/lang/CharSequence;)V+38
J 23218 C1 net.optifine.shaders.Shaders.createVertShader(Lnet/optifine/shaders/Program;Ljava/lang/String;)I (390 bytes) @ 0x000001b847c64f8c [0x000001b847c62520+0x2a6c]
j  net.optifine.shaders.Shaders.setupProgram(Lnet/optifine/shaders/Program;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V+38
```
