### ISSUE TITLE
[BUG] Enchanted items and Shader SEUS

### ISSUE THREAD

**Issue by Demyx64** [sp614x/optifine#4509]
## Description of Issue
Hello guys with the shader SEUS the enchanting items shine enormously , it's really very annoying.

## OptiFine Version
OptiFine 1.16.1 HD U G2 pre13

## F3 Debug Screenshot

![2020-07-31_15 05 45](https://user-images.githubusercontent.com/68199466/89037714-53c45e80-d33f-11ea-9705-8e5a57573136.png)

**Comment by sp614x** [comment]
Does it happen with other shaders?

**Comment by Demyx64** [comment]
i think yeah

**Comment by sp614x** [comment]
Duplicate of #4512
