### ISSUE TITLE
[Bug] OptiFine will not let me set my fullscreen resolution as 1280x720 while vanilla does.

### ISSUE THREAD

**Issue by Eastah** [sp614x/optifine#4510]
## Description of Issue
OptiFine will not let me set my fullscreen resolution to 1280x720 while vanilla does.

## Steps to Reproduce
1. Mess around with the fullscreen resolution slider in both vanilla and OptiFine.

## OptiFine Version
OptiFine 1.16.1_HD_U_G2_pre13 and earlier (possibly).

**Comment by sp614x** [comment]
Fixed in pre15.
