### ISSUE TITLE
Error with enchant glint on shaders

### ISSUE THREAD

**Issue by OffTheRockers** [sp614x/optifine#4512]
## Description of Issue
I was using slidur shaders and everything looks fine except for enchanted items used and worn by mobs and players. instead of moving around the enchanting image to make it look shiny, it just displays the image of the enchanting thing. It seems to carry over to other shaders too, as I used that sonic one. its also only confined to shaders, as without it, it looks ok

## Steps to Reproduce
1. have shaders
2. look at something enchanted via item frame or armor stand. 

## OptiFine Version
optifine 1.16.1 pre 13
## Installation Method
i used the installer 
![enchant error](https://user-images.githubusercontent.com/69058562/89078331-11981e80-d339-11ea-83b4-12a0a291a347.png)

**Comment by sp614x** [comment]
Fixed in pre15
