### ISSUE TITLE
Optifine 1.16.1 Shaders Change Nothing

### ISSUE THREAD

**Issue by Cwcat232** [sp614x/optifine#4513]
I've installed every new version of the preview since it came out, and even watched videos to make sure I was using it correctly but have found that the new Optifine shaders only change the look of glass and absolutely nothing else. I understand it's in the preview stages still, but I did want to bring attention to this.

**Comment by HiItsDevin** [comment]
did you put your shaderpack in the shaders folder

**Comment by Beksim** [comment]
Shaders work just fine. Are you sure you are installing the shaders properly?

**Comment by Cwcat232** [comment]
Yes to both of these questions. I'm quite certain that if they weren't installed properly I would get zero change whatsoever. I've never had an issue with Optifine in the past, but with these shaders they only seem to change the texture of glass. 

> Shaders work just fine. Are you sure you are installing the shaders properly? Also please use the proper format for reporting issues.



> did you put your shaderpack in the shaders folder

**Comment by sp614x** [comment]
Can you post a debug screenshot (F3)?

**Comment by Cwcat232** [comment]
> Can you post a debug screenshot (F3)?

Sorry, I just recently saw this. 
![2020-08-04_01 17 17](https://user-images.githubusercontent.com/63317332/89259745-919bde00-d5f0-11ea-9cab-4b8c7c5725fc.png)

**Comment by HiItsDevin** [comment]
Internal shaders don't change anything, you need to actually download the shaders and put them in your shaderpacks folder. Go to Options -> Video Settings -> Shaders and pick your shader.

![](https://i.hiitsdevin.dev/captures/hid_331532.png)

**Comment by Cwcat232** [comment]
> Internal shaders don't change anything, you need to actually download the shaders and put them in your shaderpacks folder. Go to Options -> Video Settings -> Shaders and pick your shader.
> 
> ![](https://camo.githubusercontent.com/1e09937ff082b7b0bb4092d6d6945a75ff526b72/68747470733a2f2f692e6869697473646576696e2e6465762f63617074757265732f6869645f3333313533322e706e67)

I've actually downloaded them, placed them in my shaders folder, but they don't show up in the actual minecraft settings menu. I've even tried extracting them to my shaders folder but it doesn't seem to work that way either.

**Comment by AepokkVulpex** [comment]
Okay well can you provide a screenshot of your folder and of the shader menu in settings?

**Comment by KaiAF** [comment]
This doesn't seem to be an issue. Looks like user error. If you need support, please either [email](mailto:optifinex@gmail.com) us or go to our [Discord server](https://optifine.net/discord).
