### ISSUE TITLE
[1.16] New Forge modlauncher transformer system and other things about Forge compatibility.

### ISSUE THREAD

**Issue by ZekerZhayard** [sp614x/optifine#4515]
There are some new forge things from 32.0.62 to 32.0.98 which optifine didn't applied.

1. CPW has [updated modlauncher](https://github.com/cpw/modlauncher/commit/ec2b00285d6e809d877862bfbd036f94cb877598) and fixed cpw/modlauncher#37 which almost caused by optifine since [32.0.90](https://github.com/MinecraftForge/MinecraftForge/commit/532d153d33611bb0c02684c638a994d5d81fa06d). He added [`Target.targetPreClass(...)`](https://github.com/cpw/modlauncher/blob/966c6986244239e51f22b91eb0acce6d7c37de7c/src/main/java/cpw/mods/modlauncher/api/ITransformer.java#L164) which can transformer class before javascript coremod system.
1. A new event named `EntityLeaveWorldEvent` was added in `net/minecraft/client/world/ClientWorld.func_217414_d` since [32.0.81](https://github.com/MinecraftForge/MinecraftForge/commit/9d84b5df319b5fb2aba7de7e09f8ee6d1bc4fe3f)
1. In `net/minecraft/client/gui/screen/MainMenuScreen.func_230430_a_`, `ForgeHooksClient.renderMainMenu` [should return void](https://github.com/MinecraftForge/MinecraftForge/blob/8f9e52c26030e1033e66517271131c02dcb5e02f/patches/minecraft/net/minecraft/client/gui/screen/MainMenuScreen.java.patch#L41), but optifine return it as String. And this caused #4004 which can also be confirmed in 1.14.4 and 1.16.1.
1. In `net/minecraft/client/gui/IngameGui.func_238444_a_`, optifine invokes [`IForgeEffectInstance.renderHUDEffect`](https://github.com/MinecraftForge/MinecraftForge/blob/8f9e52c26030e1033e66517271131c02dcb5e02f/patches/minecraft/net/minecraft/client/gui/IngameGui.java.patch#L17) with incorrect arguments.
1. In `net/minecraft/client/gui/IngameGui.func_238453_b_`, `i` should be get from [`this.getFontRenderer().func_238414_a_(highlightTip)`](https://github.com/MinecraftForge/MinecraftForge/blob/8f9e52c26030e1033e66517271131c02dcb5e02f/patches/minecraft/net/minecraft/client/gui/IngameGui.java.patch#L27), but optifine get it from `this.getFontRenderer().func_238414_a_(iformattabletextcomponent)`.
1. In `net/minecraft/client/gui/IngameGui.func_73831_a`, `stackTip` and `highlightTip` should be [`ITextComponent`](https://github.com/MinecraftForge/MinecraftForge/blob/8f9e52c26030e1033e66517271131c02dcb5e02f/src/main/java/net/minecraftforge/common/extensions/IForgeItemStack.java#L354), but optifine defines them as String.
1. In `net/minecraft/client/renderer/BlockRendererDispatcher`, the method `renderModel` which is after `func_228792_a_` and before `func_228793_a_` should be named [`renderBlockDamage`](https://github.com/MinecraftForge/MinecraftForge/blob/8f9e52c26030e1033e66517271131c02dcb5e02f/patches/minecraft/net/minecraft/client/renderer/BlockRendererDispatcher.java.patch#L24).
1. In `net/minecraft/client/renderer/BlockRendererDispatcher.renderBlock`, optifine didn't apply [these codes](https://github.com/MinecraftForge/MinecraftForge/blob/8f9e52c26030e1033e66517271131c02dcb5e02f/patches/minecraft/net/minecraft/client/renderer/BlockRendererDispatcher.java.patch#L70-L72) which allow mods use there custom ISTER.
1. In `net/minecraft/client/renderer/OverlayRenderer.func_228734_a_`, the logic of [`ForgeEventFactory.renderBlockOverlay`](https://github.com/MinecraftForge/MinecraftForge/blob/8f9e52c26030e1033e66517271131c02dcb5e02f/patches/minecraft/net/minecraft/client/renderer/OverlayRenderer.java.patch#L12-L13) is incorrect, `RenderBlockOverlayEvent` will never be cancelled.

**Comment by sp614x** [comment]
1. Todo
2. Fixed
3. Fixed
4. Fixed
5. Fixed
6. Fixed
7. Can't find `renderBlockDamage` in the 1.16.x patch: https://github.com/MinecraftForge/MinecraftForge/blob/1.16.x/patches/minecraft/net/minecraft/client/renderer/BlockModelRenderer.java.patch
8. Fixed
9. The OF logic seems to match the Forge patch: https://github.com/MinecraftForge/MinecraftForge/blob/1.16.x/patches/minecraft/net/minecraft/client/renderer/OverlayRenderer.java.patch#L12

**Comment by ZekerZhayard** [comment]
\7. `renderBlockDamage` is in `BlockRendererDispatcher`, not in `BlockModelRenderer`: https://github.com/MinecraftForge/MinecraftForge/blob/1.16.x/patches/minecraft/net/minecraft/client/renderer/BlockRendererDispatcher.java.patch#L24

\9. by using CFR/Procyon/FernFlower, the results are all like this:
![image](https://user-images.githubusercontent.com/41327811/89105340-cf630000-d452-11ea-9290-d6814095ca22.png)

the correct logic should be:
```java
if (!Reflector.ForgeEventFactory_renderBlockOverlay.callBoolean(new Object[]{playerentity, matrixStackIn, overlayType, overlay.getLeft(), overlay.getRight()})) {
    OverlayRenderer.renderTexture(minecraftIn, minecraftIn.getBlockRendererDispatcher().getBlockModelShapes().getTexture((BlockState)overlay.getLeft()), matrixStackIn);
}
```

**Comment by sp614x** [comment]
1. Todo
7. Fixed
9. Fixed

**Comment by sp614x** [comment]
2 to 9 are fixed in pre16.

**Comment by sp614x** [comment]
@ZekerZhayard are the points 2 to 9 correct now?

**Comment by ZekerZhayard** [comment]
ah, it works fine!

**Comment by sp614x** [comment]
When the class transformer is changed to use `Target.targetPreClass(...)` it crashes with:
```
Invalid target CLASS for transformer optifine.OptiFineTransformer@2e185cd7
java.lang.IllegalArgumentException: The transformer contains invalid targets
	at cpw.mods.modlauncher.TransformationServiceDecorator.gatherTransformers(TransformationServiceDecorator.java:97)
	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$initialiseServiceTransformers$6(TransformationServicesHandler.java:101)
	at cpw.mods.modlauncher.TransformationServicesHandler$$Lambda$366/1562764987.accept(Unknown Source)
	at java.util.HashMap$Values.forEach(HashMap.java:972)
	at cpw.mods.modlauncher.TransformationServicesHandler.initialiseServiceTransformers(TransformationServicesHandler.java:101)
	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:64)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:75)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

```
Probably `TransformTargetLabel` is not updated to use `PRE_CLASS` or the decorator check has to be fixed.

**Comment by ZekerZhayard** [comment]
This issue has been fixed by https://github.com/cpw/modlauncher/commit/f69414e55c94ce6c8972ae3dc87c79d39e062cdd and applied since forge-1.16.2-33.0.40

**Comment by sp614x** [comment]
Added support for Target.PRE_CLASS in the OF class transformer.
It is only active for ModLauncher version 7+, otherwise fallback to Target.CLASS.
Coming in next preview.
