### ISSUE TITLE
Cannot install optifine 1.16.1 pre15 for cracked client

### ISSUE THREAD

**Issue by slumdawggy** [sp614x/optifine#4518]
## Description of Issue
not able to download it for a crack version 

## Steps to Reproduce
1. just downloaded optifine and tried to install like other previous versions
2. when installing it says open official launcher to install

## OptiFine Version
OptiFine 1.16.1 HD U G2 pre15

## Installation Method
How did you install OptiFine? Did you use the included standalone installer, or did you drop the JAR file into your "mods" folder?
- standalone installer

**Comment by ZenithRogue** [comment]
OptiFine does not, and will never support cracked versions of Minecraft.

**Comment by slumdawggy** [comment]
so it stopped after 1.15.2?

**Comment by Studio528-real** [comment]
It never did, Hacked Clients steal OptiFine.
