### ISSUE TITLE
Glow effect doesn't show up

### ISSUE THREAD

**Issue by geekainthere** [sp614x/optifine#4522]
Mobs receive the glowing effect, but they don't actually glow; I can't see them through blocks like normal. The potion effect shows up, but they aren't outlined. This bug persisted through every preview version of 1.16.1, including the release.

You can recreate this bug by either shooting something with a spectral arrow, or ringing a bell while an Illager mob is within a 32 block radius of said bell. I use the latter method a lot, and it eliminates the purpose when I can't actually see where any remaining Illagers are during a raid.

I'm currently using OptiFine 1.16.1 HD U G2.

I use the standalone installer to install OptiFine.

The only other things I have installed are the Fabric API and the Wurst client. I also have the Technic Launcher on my computer somewhere, I'm sure.

## F3 Debug Screenshot
![2020-08-01_20 03 08](https://user-images.githubusercontent.com/69094643/89112566-9dda3c80-d432-11ea-9379-bf1a770827ad.png)

With prior testing, before and after installing Fabric, this issue does not happen in regular vanilla Minecraft, nor does it happen with Fabric.

(Also, this isn't nearly as important, but as shown in the F3 screenshot, my experience number is purple. I don't mind this; it's just odd. This doesn't happen with Fabric or in vanilla, and also only happens with 1.16 versions of OptiFine.)

**Comment by sp614x** [comment]
You have shaders enabled.
The glowing effect is not compatible with shaders.
