### ISSUE TITLE
dosen´t work

### ISSUE THREAD

**Issue by Lallaren30** [sp614x/optifine#4526]
Dosen´t work for me at all

**Comment by EdgyPotato** [comment]
What doesn't work? Please explain

**Comment by OgdenLeGrand** [comment]
close this.

**Comment by Lallaren30** [comment]
it doesn´t pop up in my launcher

**Comment by MatthyPlayz** [comment]
I'm guessing when they installing OF, the launcher profile for OF didn't show up in the launcher.
If you're on Windows, go in the Command Prompt and do:
`cd C:\Users\%username%\AppData\Roaming\.minecraft\versions`
then 
`dir`.
If you're on Linux, run Terminal and run:
`cd /~/.minecraft/versions`
then 
`ls`.
Is "OptiFine" somewhere in the response?

If not, try to install it again, via terminal/cmd in the .jar's folder by opening a command prompt, changing your directory to the .jar's folder, and then doing this command:
`java -jar <FILENAME>.jar`
Replace <FILENAME> with the name of the file.

Then, follow the regular installation process.

**Comment by KaiAF** [comment]
If you are having any issues still, let me know.
