### ISSUE TITLE
Game ended with bad state (exit code -1073741819)

### ISSUE THREAD

**Issue by Antoninzz** [sp614x/optifine#453]
Minecraft crash in a midle of the gameplay only with optifine.
only on multiplayer: not reamls
servers : hypixel, cubecraft,
and my friends have no this problem.
with shaders.
[game output.txt](https://github.com/sp614x/optifine/files/737172/game.output.txt)
[Optifine bug.txt](https://github.com/sp614x/optifine/files/737155/Optifine.bug.txt)
 - I have the latest version of java

**Comment by sp614x** [comment]
This is the launcher log.
Please post the crash report or the game output.

**Comment by Antoninzz** [comment]
i don't have the crash report :/
only this

**Comment by Antoninzz** [comment]
[game output.txt](https://github.com/sp614x/optifine/files/737169/game.output.txt)

**Comment by CrafterKina** [comment]
I think this issue is the same as what this [tweet](https://twitter.com/Minecraft/status/824548998581288962) says.
