### ISSUE TITLE
[Crash]Optifine pre-5+ crashes with carpet mod

### ISSUE THREAD

**Issue by mdboy** [sp614x/optifine#4538]
When I load carpet mod with a newer version of Optifine, it crashes without giving a crash report.

1. I load carpet mod with fabric 
2. When I launch Minecraft, it crashes without giving a crash report

## OptiFine Version
Pre-4 works fine, newer versions crash

## Installation Method
I use fabric loader

## Fabric/Forge Version
Latest Fabric launcher

## OptiFabric Version
Beta 2, 1.16

## Other Installed Mods
Carpet mod
Litematica
Malilib
Fabric api
Modmenu

## Log Files/Crash Reports
No crash reports, only standard ‘game has crashed’ from the launcher

You can get logs from `.minecraft/logs`, and crash reports from `.minecraft/crash-reports`. 
Locating your `.minecraft` folder will depend entirely on your OS. See this page for details: https://minecraft.gamepedia.com/.minecraft

**DO NOT directly copy and paste log contents here on GitHub.**

## F3 Debug Screenshot
Can’t show debug if game crashes

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine? No

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? No
   - Only OptiFine and Forge
   - Only OptiFine, OptiFabric, and Fabric
- Does this happen without any mods at all? No
   - Only Forge/Fabric by itself. No
- Does this happen in OptiFine standalone? No
- Does this happen in Vanilla without OptiFine? No
- Have you tried using a binary search to find which mods cause this issue? No
   - To find conflicting mods, split your mods into 2 groups (not including OptiFine/OptiFabric, obviously). Remove one group, and test in-game. Keep the group that has the problem, and repeat until no more mods can be removed without the issue disappearing. Did this an found out carpet mod was the conflicting mod
   - Does the issue still happen with only the remaining mods installed? No
      - Forge/Fabric and remaining mods, without OptiFine No

## Additional Information
Here goes any final remarks and everything else that might not fit in the previous sections.

**Comment by MrCheeze446** [comment]
Unfortunately OptiFabric isn't supported anymore and OptiFine doesn't have native fabric support. You can try and ask around in other communities but unfortunately this isn't an OptiFine issue.

**Comment by mdboy** [comment]
But it works fine without carpet, with my other fabric mods

**Comment by unicornbloods** [comment]
Carpet go yeet
