### ISSUE TITLE
Random entity textures not working with CEM in 1.15.2

### ISSUE THREAD

**Issue by RemiHesky** [sp614x/optifine#4540]
## Description of Issue
Although I've only tested with chickens so far, I can't get random entity textures to work, the .properties file is correct, and the additional textures are named "chicken#.png"

## Steps to Reproduce
Enabled random entity textures and spawned in dozens of chickens

## OptiFine Version
OptiFine 1.15.2 HD U G1 pre30

## Installation Method
Mods folder

## Fabric/Forge Version
Forge 31.2.0

## Other Installed Mods
B3M, Biomes O Plenty 10.0.0.366, BluePower 0.4.190, Create 0.2.4d, JEI 6.0.2.12, Gender 1.7.0, Mekanism 9.10.9.422 and it's addons, Pam's Harvestcraft 2 1.0.5 and it's addons, StorageDrawers 7.0.2, Xaeros Minimap 20.17.0

## Log Files/Crash Reports
[latest.log](https://github.com/sp614x/optifine/files/5012947/latest.log)

## F3 Debug Screenshot
![2020-08-02_16 08 00](https://user-images.githubusercontent.com/55678044/89132519-658e3900-d4da-11ea-9cf6-8519db05eab1.png)

## Prior Testing
I've also tested with just Optifine and Forge + no other mods and get the same result

**Comment by RemiHesky** [comment]
After doing further testing, I found that random entities does work, but not with Custom Entity Models, when using CEM all of my Chickens seem to be forced to use the base CEM texture (And if the CEM texture is removed, their model turns solid black and purple)

**Comment by ewanhowell5195** [comment]
this is not an issue and is just how it works.

removing the cem texture is not enough, you will also need to remove the `"texture"` line from the model, and then it should work fine

**Comment by KaiAF** [comment]
What Ewan said ^
