### ISSUE TITLE
Smooth lighting doesn't work on concrete. Optifine 1.16.1 HD U G2

### ISSUE THREAD

**Issue by Alazu** [sp614x/optifine#4541]
I had to report that smooth lighting doesn't work on concrete.
![2020-08-02_19 25 17](https://user-images.githubusercontent.com/13079847/89134918-16a2cc80-d4f7-11ea-9edd-65ffdad78251.png)
![2020-08-02_19 29 45](https://user-images.githubusercontent.com/13079847/89134919-17d3f980-d4f7-11ea-8946-a5bd56b8b816.png)

**Comment by Alazu** [comment]
This may be a vanilla bug I'm not sure I have to probably go to vanilla and show this to Mojang.

**Comment by Alazu** [comment]
It's a vanilla bug I will be reporting it to Mojang.

**Comment by bscout9956** [comment]
Close this.

**Comment by Alazu** [comment]
Fine... but the lead mod developers told me a hotfix patch was In way.
