### ISSUE TITLE
Glowing effect doesn't work.

### ISSUE THREAD

**Issue by Catsuku** [sp614x/optifine#4545]
It just doesn't work

I added glowing effect to stuff, and it didn't work

I use OptiFine 1.16.1 HD U G2
By the installer

**Comment by MrCheeze446** [comment]
that's not very helpful, can you explain a bit more in detail what exactly doesn't work and what exactly you mean by the glowing effect, and can you please provide some screenshots

**Comment by RootRobo** [comment]
I can confirm this issue.
Steps to reproduce:
1. Spawn any mob
2. use the command /effect give @e glowing 10 1
You will see that the glowing works without shaders, but not with.

**Comment by RootRobo** [comment]
With Shaders: https://i.imgur.com/VmGA6nO.png
Without Shaders: https://i.imgur.com/8afszig.png

**Comment by sp614x** [comment]
The glowing effect needs shader support in order to work.
Not all shaders are updated to use it.
