### ISSUE TITLE
CIT enchantment glint doesn't behave like the default glint

### ISSUE THREAD

**Issue by plexigras** [sp614x/optifine#455]

**Comment by sp614x** [comment]
Can you post some examples?

**Comment by plexigras** [comment]
```
type=enchantment
enchantmentIDs=0-255
texture=textures/misc/enchanted_item_glint
```

it doesn't scale correctly and it blends weirdly and just overlays wrongly and there is no animation and even with speed and blend set its no where near the default behavior

**Comment by sp614x** [comment]
The vanilla glint has special handling, it is rendered 2 times with different transforms to make the animation.
The custom glint has to provide the animation itself. For an example take a look at Misa's resource pack. There is "mcpatcher\cit\enchantment\misafireenchant1.properties" for the static image and "mcpatcher\anim\misafireenchant1.properties" for the animation.
