### ISSUE TITLE
[CEM] Vanilla textures of boats override cem's textures

### ISSUE THREAD

**Issue by Po-C4** [sp614x/optifine#4550]
## Description of Issue
When making a cem for a boat it will load the texture from `assets/minecraft/textures/entity/boat/oak.png` for an oak boat instead of the texture provided inside the cem with the `texture` parameter

## Steps to Reproduce
1. Use this texture pack: [test.zip](https://github.com/sp614x/optifine/files/5017248/test.zip) (it's supposed to add smiley faces on the bottom part of boats)
2. Remove the `.off` from `assets/minecraft/textures/entity/boat/oak.png.off` (inside test.zip) and reload resource packs with `F3+T` to see the smiley faces

## OptiFine Version
1.16.1-Optifine_HD_U_G2

## Installation Method
Installer

## F3 Debug Screenshot
![2020-08-03_18 44 16](https://user-images.githubusercontent.com/24886086/89206324-7366bb80-d5b9-11ea-96ad-34dec8427678.png)

**Comment by nindzia3** [comment]
Can confirm the same for custom chest knob model part. The designated texture just won't apply. It applies in 1.14 though.

**Comment by ZenithRogue** [comment]
If you want to overwrite the optifine textures, without effecting the vanilla ones do this:
* place your textures in `optifine/random/entity/boat`
* name each texture `[woodtype]2.png`
* create `[woodtype].properties`
* add the following to the created file:

> ```
> skins.2=2
> weights.2=100
> ```

**Comment by Luke18033** [comment]
This happens with chests as well, and is pretty annoying. The random entities workaround also didn't seem to work.

**Comment by sp614x** [comment]
Fixed in latest preview.

**Comment by Dk-de-Eternalia** [comment]
@ZenithRogue, sorry for the inconvenience, but could you give me a more concrete example of how to do it? I have tried it the way you say, but I have not succeeded.
