### ISSUE TITLE
[Suggestion][Performance] Dynamic Resolution addition

### ISSUE THREAD

**Issue by Alazu** [sp614x/optifine#4556]
I would like to be able to have the option of accessing a per-frame dynamic resolution setting. What already helps for me is the internal resolution size toggle under shader options. It would be nice if that internal resolution setting could be matched in real-time according to fps to be variable . I think this would be a wonderful addition to the game and would benefit others with mid-range to weak hardware. I will add a picture of where the button should be placed with a gray blotch. IMO the button should be marked as DRS short for dynamic resolution scaling and as you mouse over it will explain details.
![Annotation 2020-08-04 024424](https://user-images.githubusercontent.com/13079847/89265161-104d4700-d602-11ea-8361-a287fbc0c73f.jpg)

Here is a video discussing it: https://youtu.be/180nuQJccTA 

IMO the game that did it the best was Titanfall 2

**WARNING! Next paragraph is slightly off-topic. I am using it for brevity relating to the YouTube video.**
_Also maybe later implement Adaptive Super Sampling for the reverse affect of having frames to spare but that is another feature that could be asked later._
Also like the video said this will also be useful for GPU related bottlenecks and currently the author of SEUS PTGI Sonic Ether is trying to implement another GPU resource saving feature which is temporal upscaling/upsampling. 

https://www.patreon.com/m/1205892

**Comment by sp614x** [comment]
Dynamic Resolution is only useful for games that are GPU limited and more specifically resolution limited.
Minecraft is usually CPU limited, exception may be integrated graphics and using shader packs. The screen resolution is rarely the limiting factor.

**Comment by Alazu** [comment]
I'm sorry but I was GPU limited. I was using a shaderpack and I was running my fullscreen window at 4K downrezzing to 1080p. I don't think the reason you premised was a good one. Like you said, when you are GPU limited E.G. running shaders and having a high resolution that puts strain on the GPU not CPU. Maybe I should show you the a listing with Rivatuner Statistics server instead. 

I was specifically using a voxel raytraced shader.

**Comment by Alazu** [comment]
So dynamic resolution is bad?

**Comment by Alazu** [comment]
Fine... then at least add more stair-stepped control with the shader internal resolution button.

**Comment by sp614x** [comment]
Heavy shaders like SEUS PTGI are mostly resolution limited and the dynamic resolution is not going to help as the terrain or entities have very little impact on the FPS. In this case the fixed shaders render quality would be enough.
