### ISSUE TITLE
CIT: NBT check for enchantment count

### ISSUE THREAD

**Issue by plexigras** [sp614x/optifine#456]
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/cit_single.properties#L145

> Currently, only the following NBT types are supported:
> - String, Integer, Short, Long, Double, Float - match exact value only
> - Compound - Can match a specific tag or any tag (*).
> - List - Can match a specific index (starting at 0) or any index (*).

**Comment by sp614x** [comment]
What exactly is missing?

**Comment by plexigras** [comment]
i want to do something like `nbt.ench.1=undefined` so to only select items with a single enchantment

**Comment by sp614x** [comment]
More like `nbt.ench.count=1`?

**Comment by sp614x** [comment]
Added support for list size named "count".
Coming in next preview.

**Comment by sp614x** [comment]
Updated preview B7 for 1.11.2
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/cit_single.properties#L156

**Comment by plexigras** [comment]
thanks, keep up the good work.
