### ISSUE TITLE
Broken item models with AA/AF (Mekanism, Architecturecraft)

### ISSUE THREAD

**Issue by Gugagamer135** [sp614x/optifine#457]
I created a modpack with optifine, is it bugging the texture of the mekanism and architecturecraft mods, what can I do?

![mekanism 2](https://cloud.githubusercontent.com/assets/25434469/22427866/f8a3e806-e6eb-11e6-94e1-6bd54d0ae0e9.png)
![mekanism 3](https://cloud.githubusercontent.com/assets/25434469/22427870/ff10bf16-e6eb-11e6-8640-996fbb0526f2.png)
![mekanism 4](https://cloud.githubusercontent.com/assets/25434469/22427875/09076bbe-e6ec-11e6-8cdf-d737e1e88142.png)
![mekansim 5](https://cloud.githubusercontent.com/assets/25434469/22427881/0d6dee3a-e6ec-11e6-8bbe-53577348e3c1.png)
![mekanism 1](https://cloud.githubusercontent.com/assets/25434469/22427856/f174f228-e6eb-11e6-959f-f5ff81cb71ea.png)
![architecturecraft](https://cloud.githubusercontent.com/assets/25434469/22427887/126b666a-e6ec-11e6-8863-ade223f822e4.png)

**Comment by mindforger** [comment]
maybe attach some screenshoits as "bugging out" is a very unclear explnanation of the situation :)

**Comment by sp614x** [comment]
Which Forge version, Mekanism version, Architecturecraft version?
Error log or game output?

**Comment by sp614x** [comment]
Tested Forge #2209 + Mekanism 9.2.1.298 + MekanismGenerators 9.2.1.298 + MekanismTools 9.2.1.298.
Everything seems to work, the Atmic Disassembler is looking fine: http://i.imgur.com/GgSsPQi.png

**Comment by Builderb0y** [comment]
Try reloading textures with F3+T as well. Lots of things can break textures like this, including forge itself. Reloading them after your game has finished loading can usually fix it.

**Comment by Gugagamer135** [comment]
Sp614x I already did everything you said I changed forge, mekanism and optifine and did not fix anything there so I took all mods from modpack and left only mekanism optifine and architecturecraft, what I think and has another mod q is leaving the textures like this

**Comment by sp614x** [comment]
Can you reproduce it with only Forge + OptiFine + Mekanism?
Using a custom resource pack?
Are Antialiasing or Anisotropic Filtering active?
Are shaders active?
Debug screenshot (F3)?

**Comment by StuardBr** [comment]
I can confirm this. Using only Forge (12.18.3.2281) + Meknaism (9.2.2) + MCMultipart (1.4.0)+ Optifine (1.10.2_HD_U_D8) is easy to reproduce. 

Log: 
https://pastebin.com/nmH3NXYD

Screnshots:
http://imgur.com/a/UR8ON

**Comment by sp614x** [comment]
Testing Forge #2297 + OptiFine D8 for 1.10.2 + Mekanism 9.2.2 + MCMultiPart 1.4.0.
So far all models are rendered correctly:

![image](https://cloud.githubusercontent.com/assets/16635441/26554414/3af7372e-4490-11e7-8a63-31524f90961d.png)
![image](https://cloud.githubusercontent.com/assets/16635441/26554426/46bb4050-4490-11e7-822f-703b9bf9906c.png)
![image](https://cloud.githubusercontent.com/assets/16635441/26554437/5c65137c-4490-11e7-81e4-d3401ee5520e.png)
![image](https://cloud.githubusercontent.com/assets/16635441/26554459/77affbb0-4490-11e7-91bb-274a5ea79e3e.png)

**Comment by sp614x** [comment]
Managed to reproduce it with Antialiasing enabled.

**Comment by sp614x** [comment]
Disabling Anisotropic Filtering and Antialiasing should fix it for now.

**Comment by sp614x** [comment]
The broken items are not using the standard BakedModel, but something else.

**Comment by sp614x** [comment]
Mekanism is using not supported rendering: https://github.com/aidancbrady/Mekanism/blob/master/src/main/java/mekanism/client/render/item/BakedCustomItemModel.java#L404

The method getQuads() should return a list of quads, nothing else. 
It should not:
- manipulate OpenGL state: https://github.com/aidancbrady/Mekanism/blob/master/src/main/java/mekanism/client/render/item/BakedCustomItemModel.java#L438
- bind textures: https://github.com/aidancbrady/Mekanism/blob/master/src/main/java/mekanism/client/render/item/BakedCustomItemModel.java#L438
- manipulate the default Tessellator: https://github.com/aidancbrady/Mekanism/blob/master/src/main/java/mekanism/client/render/item/BakedCustomItemModel.java#L447, https://github.com/aidancbrady/Mekanism/blob/master/src/main/java/mekanism/client/render/MekanismRenderer.java#L254

The BakedCustomItemModel looks like a big hack and it should not be expected to be compatible with anything else.

**Comment by StuardBr** [comment]
Thank You for your time to discover the problem.

**Comment by piousminion** [comment]
As mentioned on the Mekanism tracker, a workaround is to install OptiForge [Curse Link](https://www.curseforge.com/minecraft/mc-mods/optiforge)
No more issues with that installed.
