### ISSUE TITLE
Cape Editor Button not working

### ISSUE THREAD

**Issue by mauritsf15** [sp614x/optifine#4579]
Hi there, when i try to click on the Optifine Cape Editor button it doesn't open any webpage. Also, the cape doesn't show when playing. I've tried to reload it several times and I checked that optifine works (zoom check) and that capes are on in the video settings.

Thanks in advance for your response!

**Comment by mauritsf15** [comment]
My IGN is inqredible and i bought the cape a few months ago, by the way

**Comment by sp614x** [comment]
There should be an error in the error log (game output) which contains the cape editor URL.
You can copy/paste it in a browser and it should work.
