### ISSUE TITLE
Oak Trapdoors are blue when placed. [Fixed]

### ISSUE THREAD

**Issue by Xalaroner** [sp614x/optifine#4585]
When I place down a oak trapdoor it becomes blue.
I am using mods but checked if optifine was the causer and it was. (It might be compatibility a issue though).

![2020-08-09_15 45 41](https://user-images.githubusercontent.com/48140645/89735044-a0065180-da57-11ea-9765-0b531b694062.png)

**Comment by Docteh** [comment]
![image](https://user-images.githubusercontent.com/190571/89836341-66971a00-db1b-11ea-9852-cac15859756c.png)

I think you should try placing an oak trap door with optifine and no mods. To me it looks like there is an unintended interaction between the as-yet unnamed mods and optifine.

**Comment by Xalaroner** [comment]
Ok I'll try. there is a high possibilty that's the case

**Comment by Xalaroner** [comment]
Yes that was the problem, sorry.

**Comment by Regnander** [comment]
Did you figure out which mod it was? If you haven't already, you could report this to the developer of that mod.
