### ISSUE TITLE
(Feature Request) Adjustable lighting and ilumination

### ISSUE THREAD

**Issue by Jamelos** [sp614x/optifine#4586]
Hello Optifine! if you go to .minecraft and change a setting, from 1 to 100, the lighting will change, this is very good for the videos and for the people who are watching them to see better, so I suggest that the lighting is adjustable, from 0 to 100 , Thanks and have a nice good day! Bye Sp614x

Sorry for my bad english.

**Comment by sp614x** [comment]
OptiFine is trying to stay as close to vanilla as possible.
Gamma over 1.0 is not going to be supported.
