### ISSUE TITLE
[Visual] items look like white squares

### ISSUE THREAD

**Issue by Microwavessss** [sp614x/optifine#4587]
dropped items are blank, white squares
some items it will only happen on one side, this also may be a problem with custom items, such as those on hypixel skyblock

## Steps to Reproduce
1. join hypixel skyblock craft items with the custom crafting table gui
2. drop sticks, diamonds, bones on the ground in hypixel skyblock 

## OptiFine Version
1.16.1 -OptiFine_HD_U_G2_pre10

## Installation Method
installed with standalone launcher

## Log Files/Crash Reports
doesn't crash minecraft but hard to tell what items are and somewhat annoying

![Screen Shot 2020-08-10 at 4 35 24 pm](https://user-images.githubusercontent.com/69450367/89757171-dd3a1480-db27-11ea-94e0-fd9e6cf87b39.png)

this issue has not occured to me when using regular 1.16.1 in hypixel or any hypixel minigames

**Comment by Docteh** [comment]
Looks like the transparency isn't working. Does hypixel make their resource pack freely available, or can it only be accessed via the server? Due to copyright on their textures, you might want to also report this bug to hypixel as they'll have proper access to their files to investigate

At the very least for a developer  to look at this they would need some files to look at. maybe ask hypixel for a resource pack that just modifies one item like the stick? How do the items look in the inventory? are they fine there?

**Comment by Microwavessss** [comment]
at the time of creating this screenshot I was using the default texture pack

**Comment by Docteh** [comment]
The custom items are implemented somehow, and I'd guess that they'd use a server resource pack for that. 

Oh, your screenshot says Pre10. how come you're not using the full release of optifine for 1.16.1?

Without a shader there is a white outline around the sticks. with a shader its got an effect on those pixels

**Comment by Microwavessss** [comment]
the custom items only have custom stats, hypixel does not have a texture
pack as far as I know.

the reason i had the pre 10 version is because it was the only version i
found online (https://optifine.net/downloads didn't have it but instead had
a file called player.dmg, so i downloaded it from
http://www.mediafire.com/file/ejknc97mjcfezir/Optifine_1.16.1_HD_U_G2.jar/file

**Comment by Microwavessss** [comment]
correction:
http://www.mediafire.com/file/yezorsb2hulqsdr/OptiFine_1.16_HD_U_G1_.jar/file

**Comment by Microwavessss** [comment]
do not remember where I got it but it is still bugged

**Comment by Docteh** [comment]
Ah. Try the (mirror) next time you download a copy of optifine.

The first mediafire link looks like a copy of pre10 and the second
mediafire link has a changelog entry for OptiFine 1.16.1_HD_U_G2_pre2

Yeah, both of those mediafire links appear to be misrepresenting
themselves. Try the (mirror) link on the optifine site. It should avoid any
sketchy advertising

**Comment by Microwavessss** [comment]
oh
