### ISSUE TITLE
[Random Entities Issue] Chests not working with random entities feature?

### ISSUE THREAD

**Issue by PabloMCPootis** [sp614x/optifine#4589]
## Description of Issue
So, Im making a resourcepack where chests are suposed to have random textures, problem comes when I can't manage for the Random Entities feature to work with them, it works with mobs but not with chests (normal, double, trapped, end...).

## Steps to Reproduce
1. Create a resourcepack file hierarchy
2. Create custom textures for the normal chest and name them normal2.png, normal3.png...
3. Create normal.properties with `textures.1=2 textures.2=3` etc

## OptiFine Version
1.16.1-Optifine_HD_U_G2

## What I've tried
Rename files to chest (chest.properties, chest2.png...)
Rename files to chest_normal (chest_normal.properties, chest_normal2.png...)
Trying random pig (to see if it was a typo or something in any of the files, but pigs worked just fine with the same code)

## Additional Information
Here's a picture of the file setup
![File setup](https://imgur.com/UkBAfzH.png)

Here's the normal.properties file
`#Oak`
`textures.1=2`
`#Spruce`
`textures.2=3`
`#Birch`
`textures.3=4`

**Comment by PabloMCPootis** [comment]
Any help?

**Comment by redstonerblast** [comment]
Yeah I'm having this issue too, either they changed the format and didn't update the docs or tile entities are just not working...

**Comment by AnimalMace** [comment]
"In 1.15 the paintings and some other entities (chests, banners, etc.) were changed to use a texture atlas which breaks the current Random Entities implementation."

**Comment by LuckyDanCZ** [comment]
Well, I was having the same issue recently. Any idea when it will be fixed?

**Comment by sp614x** [comment]
Fixed, coming in next 1.19 preview
