### ISSUE TITLE
[REQUEST] CIT add a Slot selector in the properties.

### ISSUE THREAD

**Issue by Ahnnilater** [sp614x/optifine#459]
I was asking if it was possible to add it, for purpose off the off hand or texture change considering the slot where they are in inventory.

**Comment by sp614x** [comment]
How can this be useful?

**Comment by Ahnnilater** [comment]
Texture pack purpose for adventure map, server, etc..  the variable for the slot of an item is not a nbt, so it's not reachable by the nbt.<Tag> parameters, this is why I was just asking if it was possible to add a parameter for it

**Comment by sp614x** [comment]
Do you need the information in which hand the item is (main/off hand) or in which slot number it is placed (0-9)?

**Comment by Ahnnilater** [comment]
Information in which hand the item is, this is why I m talking about the slot variable the off hand values is -106 if i'm not mistaking

**Comment by sp614x** [comment]
Internally the off hand is not using a slot number. Also CIT does not have information about the current slot being rendered.
CIT can be extended to include check for `hand=main|off|any`, this should work for both the handheld item and the hotbar.

**Comment by Ahnnilater** [comment]
Nice! 

For the "slot" thing it was just the location off the information like size of a stack and durability (i found it in nbt explorer).

So this will be in added soon?

**Comment by sp614x** [comment]
Should the hotbar item also change or should only the handheld item change?
Currently the item looks strange when different in hotbar: http://i.imgur.com/EKlvjxX.png
Do you need to show the item differently in an item frame, when dropped, etc?

**Comment by Ahnnilater** [comment]
Now i have my computer. This is an example about earlier.

![inventory](https://cloud.githubusercontent.com/assets/17747483/22521820/a576f6e4-e8b9-11e6-9f6c-713cf510e8ef.PNG)
![tag](https://cloud.githubusercontent.com/assets/17747483/22521829/a8735cf2-e8b9-11e6-948a-0169fc9922e9.PNG)

You can see the Slot (with the count and damage next to it) tag I was speaking earlier and an example of "change".

**Comment by Builderb0y** [comment]
> Should the hotbar item also change or should only the handheld item change?

Why not make that configurable too? I can think of use cases both for and against having it change in your hotbar.

**Comment by sp614x** [comment]
Updated preview B7 for 1.11.2.
Added "hand=any|main|off": https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/cit_single.properties#L131
