### ISSUE TITLE
0 FPS Startup

### ISSUE THREAD

**Issue by jfletcherlsc** [sp614x/optifine#4590]
When I open Minecraft with Optifine and get into a world, it will usually say 0/0 fps and I will only get a frame every few seconds. It works fine on vanilla, and Optifine will sometimes work normally, but not often. I don't know whats causing it, but I cant even navigate the pause menu with it.

**Comment by Regnander** [comment]
Are you able to take a screenshot of your F3 screen? It would help a lot if we knew what version of OptiFine you are running.

**Comment by jfletcherlsc** [comment]
![2020-08-12_16 11 16](https://user-images.githubusercontent.com/55815493/90062993-a34b4880-dcb6-11ea-8d31-97a651991e52.png)

**Comment by jfletcherlsc** [comment]
This issue also happened when I started using OptiFine in 1.14.

**Comment by KaiAF** [comment]
Do you have fast render on? If so try to turn that off, its located at Video Settings > Performance > Fast Render.

**Comment by jfletcherlsc** [comment]
It was on, but turning it off didn't help.

**Comment by jfletcherlsc** [comment]
I figured it out. Turning smooth FPS fixed it.

**Comment by sp614x** [comment]
Smooth FPS shouldn't cause such a massive FPS drop.
Looks like a graphics driver bug.
