### ISSUE TITLE
"s.optifine.net/capes/[username].png" doesnt support https

### ISSUE THREAD

**Issue by tanpug** [sp614x/optifine#4597]
## Description of Issue
The Cape API doesn't support https

## Steps to Reproduce
1. get a link such as "http://s.optifine.net/capes/tanpug.png", this shows a cape
2. replace http with https, and it gives a "refused to connect" error

## OptiFine Version
N/A

## Additional Information
None

**Comment by Regnander** [comment]
See #1358

**Comment by sp614x** [comment]
Duplicate of #1358.
You can always use "https://optifine.net/capes/tanpug.png" if you want a secure connection.
