### ISSUE TITLE
Crash when starting up

### ISSUE THREAD

**Issue by Imnuts7** [sp614x/optifine#46]
I get this startup crash with Forge 1804 & Optifine A4 1.9.
[https://gist.github.com/Imnuts7/92ab7936c621caa19651](url)

**Comment by sp614x** [comment]
Some of the core mods is manipulating one of the OptiFine classes and fails.
Probably BetterFoliage is trying to patch RenderChunk.

**Comment by sp614x** [comment]
Fixed in Better Foliage 2.0.5: https://github.com/octarine-noise/BetterFoliage/issues/51
