### ISSUE TITLE
CIT and nbt tags:

### ISSUE THREAD

**Issue by DragonmasterDaan** [sp614x/optifine#460]
Hey,,

I was wondering if I could get some help with something, I saw that with CIT you can change textures based on their NBT tag acording to the documentation, I saw that you could do it using the display tag so I tried out if the display.color tag worked too.

type=armor
items=301
texture.leather_layer_1=pyro_armor_layer_1
texture.leather_layer_1_overlay=pyro_armor_layer_1_overlay
nbt.display.Color=#993333

This is my file, it isn't working though, any clue why it isn't? Is there actually already a way to change textures based on their color? The documentation makes it sound like there is. :(.

Thanks!

**Comment by AmberWat** [comment]
The armor color value is actually stored as a number. You can use a command generator to convert the color or you can just throw the item on the ground and use `/entitydata @e[type=item,c=1] {}` to quickly get a dump of its NBT data.

The NBT tag is also case sensitive and if we correct both these issues we get the following working NBT rule for the color #993333:
```
nbt.display.color=10040115
```

**Comment by DragonmasterDaan** [comment]
Thanks! It works =)

**Comment by sp614x** [comment]
I could add parsing of hex numbers like "#993333" or "0x993333" to make it more readable.

**Comment by sp614x** [comment]
Parsing of hex numbers is not possible as the NBT values are compared as strings and the decimal form is the default way to convert an integer to sring.

**Comment by Builderb0y** [comment]
So why not do it the other way around then, and convert the value specified by CIT to decimal if it happens to be in hex, then compare that value to NBT the normal way?

**Comment by sp614x** [comment]
When parsing the properties file it is not clear if the value should be an int or a string. The type of the NBT tag is only available when running and it is even possible (but not realistic) that two different items use different types for the same tag.

**Comment by sp614x** [comment]
Added parsing for hex colors in NBT values (prefix "#" + 6 lowercase hex digits).
Coming in next preview.
