### ISSUE TITLE
[CEM] Custom Models for Piglin/Zombified Piglin not working

### ISSUE THREAD

**Issue by vertex235** [sp614x/optifine#4600]
## Description of Issue
When using a resource pack with custom models for Piglins/Zombified Piglins the models do not appear in game. Instead, they use the default texture and the default model. There also might be the same issue for other new 1.16 mobs but I am not sure.

## Steps to Reproduce
1. Apply a resource pack with custom Piglin/Zombified Piglin models and textures.
2. Spawn a Piglin or Zombifed Piglin

## OptiFine Version
OptiFine 1.16.1 HD U G2 

## Installation Method
Standalone Installer

## Log Files/Crash Reports
N/A

## F3 Debug Screenshot
https://drive.google.com/file/d/1HiZdkHUYrre0vpwCnde1L0VgLdRhZ3F7/view?usp=sharing

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
This also happens in vanilla but only because vanilla doesn't support custom models.

## Additional Information
I'm 95% sure that the resource pack is set up correctly but just in case it isn't: here it is.
https://drive.google.com/file/d/1tMl9OjHtVVAtMW4oxE41-X86Xhw3VB70/view?usp=sharing
An image of what the model looks like can be found here
https://drive.google.com/file/d/1SkLojbYRfBDD3sbcHgQx0fUcmvR1OPsN/view?usp=sharing

**Comment by sp614x** [comment]
Fixed in pre6.
