### ISSUE TITLE
1.8.9 Optifine crashes after a few seconds on any world or server

### ISSUE THREAD

**Issue by Kaliistic** [sp614x/optifine#4601]
## Description of Issue
Once I run 1.8.9 optifine, I can only be on any world or server for a few seconds, and then it crashes, leaving me with a similar bug report each time. The first time I used it, it was fine, but then after, I am not sure how, but it is messed up. I attempted to reinstall it, but I have no clue if I did it properly. I also reinstalled minecraft, to no avail.

## Steps to Reproduce
1. Go on any world or server
2. That's it, I get the crash screen after a few seconds

## OptiFine Version
I tried using both U_I7 and U_L5. Bear in mind 1.16 optifine works perfectly.

## Installation Method
Installed via the standalone installer

## Log Files/Crash Reports
https://pastebin.com/UhemJj4f every one of them looks similar to this

## F3 Debug Screenshot
![2020-08-12_20 00 53](https://user-images.githubusercontent.com/69601200/90056525-ed442680-dcd6-11ea-943c-4c76c0d6bf48.png)

## Prior Testing
It does not happen in vanilla

**Comment by Kaliistic** [comment]
Nevermind! I fixed this myself, after fiddling with some settings. I turned smooth lighting and particles off and VBOs on and somehow that was fine after?

**Comment by Kaliistic** [comment]
No nevermind it has started again. Please help.

**Comment by asbyth** [comment]
this is the same as #4685, issue outside of optifine

**Comment by sp614x** [comment]
Crash in graphics driver (intel integrated).
You can try:
- updating/downgrading driver
- use VBOs ON/OFF
- use smaller resource pack
- reset video settings
