### ISSUE TITLE
[bug] color.properties not changing spawn egg colors

### ISSUE THREAD

**Issue by Eilux** [sp614x/optifine#4606]
## Description of Issue
Please provide as much detail as possible.
The file reads:
`egg.shell.bat=f5f5f5
egg.spots.bat=e1e1e1`

## Steps to Reproduce
1. try to change the spawn egg color

## OptiFine Version
1.16.1 HD U G2

## Installation Method
Installer

**Comment by schrodingerspsycho** [comment]
#4173

**Comment by sp614x** [comment]
Duplicate of #4173
