### ISSUE TITLE
[MC1.16.2] Optifind Version

### ISSUE THREAD

**Issue by Robertpuggle** [sp614x/optifine#4607]
Can the makers of the mod go to 1.16.2 visions

**Comment by Deviouslrd** [comment]
Its in development right now

**Comment by Robertpuggle** [comment]
ok

**Comment by Aurumaker72** [comment]
Please do not rush the development, people like you are annoying.

**Comment by Docteh** [comment]
I'm not sure where they're getting their information, but the reddit for optifine [tracks progress](https://www.reddit.com/r/Optifine/comments/eb73s9/welcome_to_roptifine_please_read_before_posting/). It says 20% as of this comment.

**Comment by sp614x** [comment]
There is a 1.16.2 preview.
