### ISSUE TITLE
OptiFine with Fabric

### ISSUE THREAD

**Issue by QingKe233** [sp614x/optifine#4609]
I want to get a 1.16.2OptiFine with Fabric directly.Not through optifabric.Because he has stopped updating.

**Comment by schrodingerspsycho** [comment]
#4561

**Comment by rbits0** [comment]
This will work for now https://github.com/Andrews54757/OptiFabric-updated

**Comment by sp614x** [comment]
More active forks of OptiFabric:
- https://github.com/Chocohead/OptiFabric
- https://github.com/CDAGaming/OptiFabric.

**Comment by sp614x** [comment]
Duplicate of #4561
