### ISSUE TITLE
MalisisCore crashing on FontRenderer.charWidths not being float[]

### ISSUE THREAD

**Issue by kenijey** [sp614x/optifine#461]
[malisis crash.txt](https://github.com/sp614x/optifine/files/743070/malisis.crash.txt)
please help :( game won't start. and please inform me if it is caused by only malisis doors. thanks.

**Comment by sp614x** [comment]
MalisisCore has a workaround for #438 and now that #438 is fixed MalisisCore has to be updated in order to work: https://github.com/Ordinastie/MalisisCore/blob/1.11/src/main/java/net/malisis/core/renderer/font/MinecraftFont.java#L91

**Comment by kenijey** [comment]
thanks
