### ISSUE TITLE
[1.16.1] [Shader] rain.depth toggle not working

### ISSUE THREAD

**Issue by fayer3** [sp614x/optifine#4611]
## Description of Issue
changing rain.depth in shaders.properties to true doesn't work, rain depth is never written to the depth buffer

## Steps to Reproduce
1. create a shader with rain.depth=true in shaders.properties
2. draw depthtex0 to screen, and see that during rain the raindrops are not drawn to the depthbuffer

## OptiFine Version
OptiFine 1.16.1 HD U G2

## Installation Method
standalone installer

## F3 Debug Screenshot
![2020-08-14_23 47 22](https://user-images.githubusercontent.com/8282299/90295227-aac24b80-de88-11ea-9c0e-f3bfc39ee6a6.png)
for reference the same scene with Minecraft 1.14.4:
![2020-08-14_23 46 50](https://user-images.githubusercontent.com/8282299/90295248-bc0b5800-de88-11ea-93f8-daaaf6beb10d.png)

## Additional Information
here is the shaderpack used for the screenshots: 
[test rain depth.zip](https://github.com/sp614x/optifine/files/5077440/test.rain.depth.zip)

**Comment by sp614x** [comment]
Fixed, coming in next 1.19.2 preview
