### ISSUE TITLE
1.14.4 to 1.16.2 with optifine takes like 20 minutes to start up. stuck at mojang loading screen

### ISSUE THREAD

**Issue by realflow100** [sp614x/optifine#4613]
32GB ram
i7 3770k quad core processor 3.5ghz
GTX 1650 graphics card
256GB SSD and 2TB external USB 3.0 HDD
im on windows 7 and also have a 144hz 1080p 1ms gaming monitor
computer specifications

[latest.log](https://github.com/sp614x/optifine/files/5080163/latest.log)
the only relevent log file with anything in it.

Ive already tried literally everything but nothing fixes it.
not even a completely fresh .minecraft folder with running 1.16.2 once and installing optifine.
same problem there too.

**Comment by realflow100** [comment]
idk what I did. I just took went to bed for the night came back and its working and not taking 20 minutes to get past the mojang screen anymore.

WEIRD! because I already tried restarting my computer a few times too and it didnt fix it.

**Comment by sp614x** [comment]
No idea what this may be.

**Comment by realflow100** [comment]
Aw dang closed :( I wish I knew what caused this so I can fix it next time it happens.

**Comment by AepokkVulpex** [comment]
Try turning off mipmap levels?

**Comment by realflow100** [comment]
Changing that has no effect. it doesnt matter even if I let the game re-create the options files completely or manually set it to off in the options files myself. 
or start vanilla minecraft and disable it then restart with optifine. Same problem happens. so its not related to mipmap level.
