### ISSUE TITLE
[1.16.2] [BSL Shader] Player model disappears when changing perspective 

### ISSUE THREAD

**Issue by elewho** [sp614x/optifine#4614]
My friend is using BSL Shaders when this bug occurs. When he  changes perspective, the model flashes white before disappearing completely in all POVs. 

## Steps to Reproduce
https://youtu.be/8sJJDtKzZGA
1. Change perspectives with BSL enabled

## OptiFine Version
OptiFine 1.16.2 HD U G3 pre1

## Installation Method
He used the standalone installer.

## Prior Testing
No

**Comment by NateslPlayzzz** [comment]
I am having the same issue

**Comment by sp614x** [comment]
Duplicate of #4640.
