### ISSUE TITLE
Optifine Cape Stolen

### ISSUE THREAD

**Issue by 4Remains** [sp614x/optifine#4617]
Hey, i don't know how to start this but, my cape was somehow stolen, i don't have my donation password because i bought my cape for a cheaper price in a ''minecraft store'' I don't have any idea how to get it back. I already send an email to the support and nothing, it happened a year ago, i didn't noticed it, until my friend told me, please, help me with this

https://prnt.sc/u0iy6e

**Comment by KaiAF** [comment]
If you bought it from a "minecraft store" you got scammed, do not trust those. There is no way for us or you to get it back unless you had access to the email and password.

**Comment by sp614x** [comment]
You can always recover the cape with your donator email: https://optifine.net/login
