### ISSUE TITLE
[Crash 1.14.4] Optifine crashes even with recommended forge version

### ISSUE THREAD

**Issue by embermctillhawk** [sp614x/optifine#4624]
## Description of Issue
Optifine 1.14.4 crashes before main menu. Other issues have been opened with the same crash error, `net.minecraft.client.renderer.FluidBlockRenderer.func_178268_a`. Recommended fix was to use forge version 28.2.20

Fix did not work.

## Steps to Reproduce
1. Create new Minecraft 1.14.4 installation through twitch desktop app, using forge version 28.2.20
2. Download Optifine 1.14.4 HD U F5 into /mods folder
3. Run
4. Crash

## OptiFine Version
1.14.4 HD U F5

## Installation Method
Jar drop into mods folder

## Fabric/Forge Version
28.2.20

## Other Installed Mods
Nothing yet.

## Log Files/Crash Reports
[latest.log](https://github.com/sp614x/optifine/files/5081868/latest.log)
[crash-2020-08-16_20.35.31-client.txt](https://github.com/sp614x/optifine/files/5081870/crash-2020-08-16_20.35.31-client.txt)

## Prior Testing
Prior testing can't really be done in this situation. Nothing has been added besides Optifine. I was going to add a certain infamous texture pack, but I haven't even moved it into the resourcepacks folder yet because I can't reach the main menu.

## Additional Information
why me

**Comment by Bilibox** [comment]
@embermctillhawk from the changelog it seems that 1.14.4 optifine's compatible forge version is 28.1.56. If i remember right it works until 28.2.0
So try Forge 28.1.118 and if that doesnt work go down to 28.1.56
https://optifine.net/changelog?f=OptiFine_1.14.4_HD_U_F5.jar

**Comment by embermctillhawk** [comment]
28.1.56 does seem to work fine

An amendment should probably be made to issue #3490 which is where I read the incorrect recommendation.

**Comment by Bilibox** [comment]
The post in that issue says to use build 28.2.0
From your OP it looks like you're using 28.2.20 which is 20 builds higher

**Comment by embermctillhawk** [comment]
Ah, I see. I have tested 28.2.0, it works.

The last 28.2 is 28.2.23, there's too many 2's in the version number, it was just sheer coincidence that the version number was so visually similar. Good catch. I think we're done here.
