### ISSUE TITLE
[1.16.2, crash] crash when loading world

### ISSUE THREAD

**Issue by bluesillybeard** [sp614x/optifine#4629]
## Description of Issue
Hello there!

Optifine crashes in the latest version of forge (1.16.2 - 33.0.5)

It gets to the menu just fine, but when I load/generate a world, it crashes when it finishes the loading/generating process

I'll also make sure to contact the creators of Forge as well (directly copied from this, obviously removing this line)

I have these mods:

[OptiFine_1.16.1_HD_U_G2](https://optifine.net/adloadx?f=OptiFine_1.16.1_HD_U_G2.jar&x=4a3e)

[VoxelMap-Mod-1.16.2](http://www.dl2.9minecraft.net/index.php?act=dl&id=1597662242)

here is the crash report (I added the options files at the end, in case they are needed)
[https://pastebin.com/aKy8NjDK](https://pastebin.com/aKy8NjDK)

I also removed optifine and tried it: sure enough, my problem was fixed

## Steps to Reproduce
1. make sure all of your mods are actually installed
2. load minecraft
3. create new world OR load an existing one
4. wait until world loads
5. ...aaaaand minecraft is gone

## OptiFine Version
OptiFine_1.16.1_HD_U_G2

## Installation Method
dropped into mods folder

## Forge Version
1.16.2 - 33.0.5

## Other Installed Mods
VoxelMap-Mod-1.16.2

## Log Files/Crash Reports
https://pastebin.com/aKy8NjDK

## F3 Debug Screenshot
impossible to collect (game crashes too early)

## Prior Testing
The rest of the mods work if optifine is not installed
Optifine & forge only also crashes

## Additional Information
you should, like, watch [this video](https://www.youtube.com/watch?v=dQw4w9WgXcQ)

**Comment by KaiAF** [comment]
OptiFine 1.16.1 cant be launched on 1.16.2 

_also nice rick roll_

**Comment by Jobiir** [comment]
Ran into the same issue with the 1.16.2 preview.
Was trying to launch it with the modpack Valhesia 3.
[crash-2020-08-18_11.26.53-client.txt](https://github.com/sp614x/optifine/files/5089504/crash-2020-08-18_11.26.53-client.txt)

**Comment by bluesillybeard** [comment]
oh yes, that would help lol

I honestly have no idea why I didn't notice I put in the wrong jar file xD

_also thx_
