### ISSUE TITLE
In optifine 1.16.2 the 'internal' shaders are not working properly, whenever i hit a mob it doesn't turn red.

### ISSUE THREAD

**Issue by NovaLegend26** [sp614x/optifine#4632]
In optifine 1.16.2 the 'internal' shaders are not working properly, whenever i hit a mob it doesn't turn red. i play on windows 10. no forge or fabric i directly downloaded optifine.

**Comment by Zordlan** [comment]
that's a known thing with internal shaders, if you don't like it you don't have to use them. also they don't change anything other than that

**Comment by NovaLegend26** [comment]
no, the reason i use internal is cause normal java rendering is very grainy for some reason, and internal shaders fixes it. So is there any way to add the feature in?
