### ISSUE TITLE
[Colormap] Colormaps not working in 1.16.2?

### ISSUE THREAD

**Issue by FoonyFoxacoon** [sp614x/optifine#4633]
I was trying to use a resource pack that adds a water color map in 1.16.2 but it didn't work. The pack works in 1.16.1. Is this a bug or did I miss a change? Do I need to modify the .properties files?

**Comment by SkaliberWasTaken** [comment]
Can confirm, colourmaps are broken in 1.16.2 - I'd be interested to know how colourmaps are going to be handled going forward...?

**Comment by sp614x** [comment]
Fixed in pre3.

**Comment by ThePandoroxTP** [comment]
Colormap (specifically for water and only water) appears to be broken in 1.19.0, all other colormaps work fine; current version: 
OptiFine HD U H8 09.07.2022
