### ISSUE TITLE
[1.16.2] Changing Perspective Causes Full-White Screen.

### ISSUE THREAD

**Issue by VibingGod** [sp614x/optifine#4640]
Changing your perspective will cause the screen to go full-white, but only if camera is angled in certain positions.

1. First, change perspective to third person front/back
2. Move camera around until screen turns white.

1.16.2-Optifine_HD_U_pre1

Installed Optifine using the standalone installer.

Can't find any relevant logs for this issue, but I am not good with code, so I'm not sure.

(Whiteworld is _not_ on.)

**Comment by dbrighthd** [comment]
I'm having the same problem, but the world also turns white when using F1 (hiding UI)

**Comment by joglr** [comment]
Same problem. Also, if I do either F1 or F5, a texture glitch occurs and afterwards, you can't see your hand/held items or dropped items.

**Comment by sp614x** [comment]
I can't reproduce the problem so far (F1, F5, etc.)
Is there some option or specific shader/resource pack which triggers it?

**Comment by sp614x** [comment]
Fixed, coming in pre2.
