### ISSUE TITLE
[1.16.1] Flame Animated does not affect soul flame particles

### ISSUE THREAD

**Issue by PartyBabies** [sp614x/optifine#4642]
## Description of Issue
Soul flame particles continue to emit from soul torches after Flame Animated is set to OFF.

## Steps to Reproduce
1. Have Flame Animated OFF and set Particles to All or Decreased

Flame Animated ON
![2020-08-19_14 00 27](https://user-images.githubusercontent.com/51533836/90598060-e82a2e80-e224-11ea-983e-57c3adaaae81.png)

Flame Animated OFF
![2020-08-19_14 00 43](https://user-images.githubusercontent.com/51533836/90598103-fb3cfe80-e224-11ea-96a4-13120086650d.png)

Particles Minimal
![image](https://user-images.githubusercontent.com/51533836/90598121-03953980-e225-11ea-8fed-871535f21517.png)

## OptiFine Version
OptiFine 1.16.1 HD U G2

## Installation Method
Standalone

## Additional Information
For some reason, the soul_fire_flame particle spawned in using a command will still show even if Particles is set to Minimal (still the same for Flame Animated).

Particles Minimal
![image](https://user-images.githubusercontent.com/51533836/90599067-c9c53280-e226-11ea-98e3-cc556c187815.png)

**Comment by sp614x** [comment]
Fixed in pre2 for 1.16.2
