### ISSUE TITLE
[1.16.1] Chunks aren't loading during the world start

### ISSUE THREAD

**Issue by AlexVashchenkov** [sp614x/optifine#4643]
## Description of Issue
While you load your Minecraft world, you spawn "in the sky", surrounded by air. If you try to use "/setblock ~ ~ ~ minecraft:nether_portal", then you spawn in your nether, but only in the spawn chunk. If you try to go through your portal in your spawn chunk, you also load just one chunk. 

## Steps to Reproduce
1. Load your world
2. Set the portal
3. Go through your portal
4. See the thing
## OptiFine Version
1.16.1-Optifine_HD_U_G2 

## Installation Method
JAR installer

**Comment by sp614x** [comment]
Make sure that Render Distance is set below 37.
Currently values above 37 may cause the world to load only partially.

**Comment by sp614x** [comment]
Duplicate of #4261
