### ISSUE TITLE
[1.16.1 Modded] Missing textures/incompatibility with a few mods

### ISSUE THREAD

**Issue by Shlock-Konn** [sp614x/optifine#4646]
## Description of Issue
When OptiFine is installed alongside Essentials, Inspirations, Iron Jetpacks and JustAnotherOreProcessingAttempt, the Essential's Guidebook, Iron Jetpack's jetpacks, Inspirations' enlightened bushes, and JAOPCA's items' textures are replaced by the missing texture pattern. Additionally, the same happens with enchanted books and cauldrons in item form, and the Nether portal, as all are altered by Inspirations.

## Steps to Reproduce
1. Install the latest versions of Forge and OptiFine
2. Install the mods Essentials, Inspirations, Iron Jetpacks and JAOPCA, and their respective dependencies
3. In-game, look at the aforementioned items/blocks

## OptiFine Version
1.16.1 HD U G2

## Installation Method
JAR put into /mods folder.

## Forge Version
Forge 32.0.108

## Other Installed Mods
Essentials, Iron Jetpacks, JustAnotherOreProcessingAttempt, Inspirations, Mantle, Cucumber (the last 2 are libraries)

## Log Files/Crash Reports
Log created while playing the same instance as the F3 debug screenshot originates from:
[latest.log](https://github.com/sp614x/optifine/files/5098474/latest.log)

## F3 Debug Screenshot
![image](https://user-images.githubusercontent.com/69794809/90674021-d498bb00-e258-11ea-861b-070ceea60d4f.png)

## Prior Testing
- The issue with vanilla blocks and items only occurs if Inspirations is also installed.
- The issue does not occur without OptiFine or mods, in standalone Optifine, nor in Vanilla without OptiFine.
- A binary search was not carried out, as the conflict is between OptiFine itself and other mods.

## Additional Information
The same issue was experienced on a different version of Forge with Iron Jetpacks and JAOPCA, and fixed by turning off Custom Items and Colors. This fix was, however, in this case unsuccessful.
The chat is semi-spammed with 1281 GL errors while playing. Doors sometimes turn invisible.

**Comment by Stereo528** [comment]
You can fix this with OptiForge i learned, also related to #4639
I'm fairly certain some rendering in Forge changed and it messes with OptiFine model loading.

**Comment by Shlock-Konn** [comment]
> You can fix this with OptiForge i learned, also related to #4639
> I'm fairly certain some rendering in Forge changed and it messes with OptiFine model loading.

Yes, I found that out some time after starting this thread. Either way, thank you for the help.
