### ISSUE TITLE
Add 0.85x Render Quality

### ISSUE THREAD

**Issue by SuspiciousLookingOwl** [sp614x/optifine#4651]
Sometimes I want to get a bit FPS boost by reducing the render quality from 1x to something lower, but using 0.7x render quality gives very blurry result, so I think it would be nice to add render quality value between 0.7x and 1x, like 0.85x

**Comment by sp614x** [comment]
Fixed in pre5.
New quality options are: 0.5x, 0.6x, 0.66x, 0.75x, 0.83x, 0.9x, 1x, 1.16x, 1.33x, 1.5x, 1.66x, 1.8x and 2x.

**Comment by MrSlimeOfSlime** [comment]
I hope its a slider then

**Comment by sp614x** [comment]
Fixed values for now as the scaling has best quality when using fixed ratios: 2:3, 4:5, etc.

**Comment by MrSlimeOfSlime** [comment]
Well the fps slider has fixed values I meant like that

**Comment by MrSlimeOfSlime** [comment]
also, instead of decimal the ratios would make more sense imo

**Comment by sp614x** [comment]
The ratios are not readable: 1/2, 3/5, 2/3, 3/4, 5/6, 9/10, 1/1, 7/6, 4/3, 3/2, 5/3, 9/5, 2/1
