### ISSUE TITLE
[Category] Smooth Lighting Level Does Nothing

### ISSUE THREAD

**Issue by Luracasmus** [sp614x/optifine#4652]
## Description of Issue
The grapics option `Smooth Lighting Level` does nothing.

## Steps to Reproduce
1. Change the `Smooth Lighting Level` option
2. Nothing changes

## OptiFine Version
`OptiFine 1.16.1 HD U G2`

## Installation Method
Standalone Installer

## Log Files/Crash Reports
[latest.log](https://github.com/sp614x/optifine/files/5104707/latest.log)

## F3 Debug Screenshot
![image](https://user-images.githubusercontent.com/60381935/90808474-57d11400-e320-11ea-803d-a5cf657abd2f.png)

## Prior Testing
This does not happen in Vanilla as it's not a Vanilla feature

**Comment by sp614x** [comment]
Smooth Lighting Level controls the darkening of the inner terrain corners (ambient occlusion).

100% (vanilla)
![изображение](https://user-images.githubusercontent.com/16635441/90811149-cae08780-e32c-11ea-8e65-06c7e583e1b8.png)

50%
![изображение](https://user-images.githubusercontent.com/16635441/90811177-d764e000-e32c-11ea-8da1-5c8106d57c34.png)

0%
![изображение](https://user-images.githubusercontent.com/16635441/90811199-df248480-e32c-11ea-920e-c44cfd4c411e.png)
