### ISSUE TITLE
No matter what I try whenever I open Optifine it keeps on saying "This file does not have an app associated with it." How can I fix this?

### ISSUE THREAD

**Issue by Fir3Sage** [sp614x/optifine#4653]
I'm not sure if it is because of the computer I'm using but when I open Optifine it keeps on saying "This file does not have an app associated with it." I've tried multiple versions of the game and but none of them work. I used Optfine.net which is what I was told to do but it's not working for me.

I've tired preview_OptiFine_1.16.2_HD_U_G3_pre1, OptiFine_1.16.1_HD_U_G2, preview_OptiFine_1.16.1_HD_U_G2_pre10 and preview_OptiFine_1.16.1_HD_U_G2_pre11

**Comment by Jorkles** [comment]
Make sure you have java installed. https://www.java.com/en/download/ works, or you could go with https://adoptopenjdk.net/. Any versions works. 
With AdoptOpen all you need is the JRE, which is a lot smaller and quicker to download, so click on "Other platforms," select which version you want, then scroll down until you find the right JRE installer for your OS/system.
![javaversion](https://user-images.githubusercontent.com/64293495/90822761-c646af80-e2e9-11ea-8caa-959fa931db13.png)
installer for your OS/system.

**Comment by Fir3Sage** [comment]
How do I know what version to get or does it not matter?

**Comment by Fir3Sage** [comment]
Thank you so much!!! It's my first time using this website. Thank you for helping me!

**Comment by Ogastan** [comment]
> Make sure you have java installed. https://www.java.com/en/download/ works, or you could go with https://adoptopenjdk.net/. Any versions works.
> With AdoptOpen all you need is the JRE, which is a lot smaller and quicker to download, so click on "Other platforms," select which version you want, then scroll down until you find the right JRE installer for your OS/system.
> ![javaversion](https://user-images.githubusercontent.com/64293495/90822761-c646af80-e2e9-11ea-8caa-959fa931db13.png)

I have java downloaded, but when I click on optifine to download it, it does not open. (I am having the same issue Fir3Sage is/was having) I've used optifine before and never had this issue I am assuming its something with the computer, but I am not sure. I just downloaded the AdoptOpenJDk thing, i tried to downlaod the jre one but it has the same issue as optifne where it says "This file does not have an app associated with it."

**Comment by Jorkles** [comment]
I'm going to assume that this is a file association problem. There's a manual way to fix this, and jarfix. https://johann.loefflmann.net/en/software/jarfix/index.html download and run this.
The manual way is right clicking the optifine jar, open with, choose another app, then scroll down until you see "Look for another app on this pc." Navigate to C;\Program files\[Java or Adoptopenjdk, depending on what you installed]\bin\javaw.exe and run it with that.

**Comment by Ogastan** [comment]
> I'm going to assume that this is a file association problem. There's a manual way to fix this, and jarfix. https://johann.loefflmann.net/en/software/jarfix/index.html download and run this.
> The manual way is right clicking the optifine jar, open with, choose another app, then scroll down until you see "Look for another app on this pc." Navigate to C;\Program files[Java or Adoptopenjdk, depending on what you installed]\bin\javaw.exe and run it with that. This is windows, I don't have any experience with MacOS or Linux.

That worked thank you!
