### ISSUE TITLE
[Forge] Mod license requirement

### ISSUE THREAD

**Issue by coraunderhill** [sp614x/optifine#4654]
## Description of Issue
Forge for Minecraft 1.16.2 added a new requirement for mod developers to include a license file as of v32.0.90 (later undone for previous versions in v33.0.93)

## Steps to Reproduce
1. Extract the Optifine mod JAR to the Minecraft mods directory
2. Launch Minecraft using the Forge profile
3. ???
4. Death

## OptiFine Version
OptiFine 1.16.2 HD U G3 pre2

## Installation Method
JAR file to mods directory

## Fabric/Forge Version
Forge v33.0.7

## Other Installed Mods
None

## Log Files/Crash Reports
`[main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.loading.moddiscovery.InvalidModFileException: Missing License, please supply a license. (OptiFine_1.16.2_HD_U_G3_pre2_MOD.jar)`

## F3 Debug Screenshot
<img src="https://user-images.githubusercontent.com/868416/90832822-85579680-e2fb-11ea-99f7-d1755058f159.png">

## Prior Testing
If you've installed using Forge/Fabric:
- Does this happen without other mods installed? **Yes**
- Does this happen without any mods at all? **No**
- Does this happen in OptiFine standalone? **No**
- Does this happen in Vanilla without OptiFine? **No**
- Have you tried using a binary search to find which mods cause this issue? **Yes**
   - Does the issue still happen with only the remaining mods installed? **No**

**Comment by sp614x** [comment]
This was reverted for 1.16.1 in 32.0.93 and was never active for 1.16.2.

**Comment by coraunderhill** [comment]
The pre-3 release for 1.16.2 doesn't fix it either. I've included the full log file
[latest.log](https://github.com/sp614x/optifine/files/5120844/latest.log)

**Comment by sp614x** [comment]
Forge 32.0.20 works for me, doesn't crash with pre3.
Added the licence in pre4.
