### ISSUE TITLE
[1.16.2 Multiplayer] Can not connect to some servers on AdoptOpenJDK Java 14 HotSpot

### ISSUE THREAD

**Issue by musabagriyanik** [sp614x/optifine#4656]
## Description of Issue
If you use OptiFine with AdoptOpenJDK Java 14 HotSpot, you can not get ping from some servers (on Multiplayer tab) and you can not connect them. But on some servers you can still connect.

## Steps to Reproduce
1. Install 1.16.2 previews, save those server ips to your multiplayer server list.
Server 1: play.datblock.com
Server 2: earthmc.net
Server 3: hypixel
2. and check these servers ping and player count, you can refresh your multiplayer list much time, you can only get ping, player count data and motd data from datblock server, you can not connect or get data from Server 2 and Server 3

## OptiFine Version
1.16.2 pre1 and pre2 (not sure about other versions, i didn't tried them)

## Installation Method
How did you install OptiFine? Did you use the included standalone installer, or did you drop the JAR file into your "mods" folder?

Standalone, just started the .jar file and press install.

## Log Files/Crash Reports
Any relevant log files. Drag and drop text files here to upload to GitHub directly, OR upload the complete contents to Pastebin. https://pastebin.com/
-no log file

You can get logs from `.minecraft/logs`, and crash reports from `.minecraft/crash-reports`. 
Locating your `.minecraft` folder will depend entirely on your OS. See this page for details: https://minecraft.gamepedia.com/.minecraft

**DO NOT directly copy and paste log contents here on GitHub.**

## F3 Debug Screenshot
Minecraft's built-in debug screen provides *a lot* of useful information, and should be included even if the issue is not something that can be captured in a still image.

To open this menu, simply press `F3` on your keyboard while in-game. Please ensure the text is easily readable. Depending on the size/resolution of your monitor, you may have to adjust your GUI scale for all text to be completely visible on-screen.

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
+No, it's not happening on Vanilla with Java 14 HotSpot

## Additional Information
Here goes any final remarks and everything else that might not fit in the previous sections.

**Comment by sp614x** [comment]
Fixed in 1.16.2 pre4
