### ISSUE TITLE
[1.16.2][Custom Sky] Sky doesn't show on the whitelisted biomes.

### ISSUE THREAD

**Issue by Francy-chan** [sp614x/optifine#4658]
If there's the biome flag in the sky#.properties, the sky doesn't show on the whitelisted biomes.

This started happening on the OF 1.16.2 G3 pre-1 and persists in the pre-2. Works fine on 1.16.1
(all vanilla + OF)
 
[world0 example](https://github.com/sp614x/optifine/files/5106654/world0.zip)

**Comment by sp614x** [comment]
Fixed in pre3
