### ISSUE TITLE
[1.12.2 Modded] Optifine crashing on startup for Twitch modpacks //MacOs 10.15.6

### ISSUE THREAD

**Issue by PCdaBEST** [sp614x/optifine#4662]
Whenever I install a modpack with twitch it works perfectly. That's until I want to add optifine. So I download optifine from the website and the correct version and then I add it to the mods folder. After starting the modded Minecraft it crashes on startup. i tried this on 1.12.2. How I installed it was I dropped in into the mods folder. I did not use the installer. Forge version 14.23.5.2854

Mods installed in mod pack:
[ANGRY PIXEL] The Betweenlands | oily_oli | TheBetweenlands-3.6.0-universal.jar
-- | -- | --
AbyssalCraft | Shinoow | AbyssalCraft-1.12.2-1.9.19.jar
AbyssalCraft Integration | Shinoow | AbyssalCraft Integration-1.12.2-1.11.0.jar
AppleSkin | squeek502 | AppleSkin-mc1.12-1.0.9.jar
ArmorPlus | sokratis12GR | armorplus-1.12.2-11.28.0.69.jar
AtomicStryker's Battle Towers | atomicstrykergrumpy | BattleTowers-1.12.2.jar
AtomicStryker's Infernal Mobs | atomicstrykergrumpy | InfernalMobs-1.12.2.jar
AutoRegLib | Vazkii | AutoRegLib-1.3-32.jar
BetterFps | Guichaguri | BetterFps-1.4.8.jar
BiblioCraft | Nuchaz | BiblioCraft[v2.4.5][MC1.12.2].jar
Biomes O' Plenty | Forstride | BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar
Bookshelf | DarkhaxDev | Bookshelf-1.12.2-2.3.590.jar
Chameleon | Texelsaur | Chameleon-1.12-4.1.3.jar
Chisel | tterrag1098 | Chisel-MC1.12.2-1.0.2.45.jar
Chisels & Bits | AlgorithmX2 | chiselsandbits-14.33.jar
ChocoCraft 3 | TheSlayer5934 | chococraft_1.12.2-0.9.8.0.jar
Classic Combat | WildBamaBoy | ClassicCombat-1.0.1.jar
ConnectedTexturesMod | tterrag1098 | CTM-MC1.12.2-1.0.2.31.jar
Construct's Armory | TheIllusiveC4 | conarm-1.12.2-1.2.5.4.jar
DimensionalDoors | DimensionalDevelopment | DimensionalDoors-3.0.9-287.jar
Doomlike Dungeons | JaredBGreat | DoomlikeDungeons-1.13.2-MC1.12.2.jar
Dungeon Tactics | PegBeard | DungeonTactics-1.12.2-0.16.6.jar
Enchanting Plus | DarkhaxDev | EnchantingPlus-1.12.2-5.0.176.jar
FastFurnace | Shadows_of_Fire | FastFurnace-1.12.2-1.3.1.jar
FastWorkbench | Shadows_of_Fire | FastWorkbench-1.12.2-1.7.3.jar
Foam​Fix | asiekierka | foamfix-0.10.10-1.12.2.jar
Future Versions | tiptopmtg | FutureVersionsV1.2.2.jar
Hexxit Gear | Shadows_of_Fire | Hexxit Gear-1.12.2-2.8.0.jar
Inventory Tweaks | JimeoWan | InventoryTweaks-1.63.jar
Iron Chests | ProgWML6 | ironchest-1.12.2-7.0.72.847.jar
IvToolkit | Ivorforce | IvToolkit-1.3.3-1.12.jar
JJ Meteor | JdiJack_ | JJ Meteor 1.12-1.12.2-v1.0.10.jar
JourneyMap | techbrew | journeymap-1.12.2-5.7.1.jar
Just Another Rotten Flesh to Leather Mod | alexdaum1 | JRFTL[1.12.2]-1.1.jar
Just Enough Items (JEI) | mezz | jei_1.12.2-4.15.0.291.jar
Login Shield | Glasspelican | Login_Shield-1.12.2-3-g7c6e7ac.jar
LootBags | Malleah | LootBags-1.12.2-2.5.8.5.jar
MalisisCore | Ordinastie | malisiscore-1.12.2-6.5.1.jar
MalisisDoors | Ordinastie | malisisdoors-1.12.2-7.3.0.jar
MalisisSwitches | Ordinastie | malisisswitches-1.12.2-5.1.0.jar
Mantle | mDiyo | Mantle-1.12-1.3.3.55.jar
More Libs | PanSzelescik | morelibs-1.12.2-1.2.2.jar
More Plates | PanSzelescik | moreplates-1.12.2-5.5.2.jar
Natura | mDiyo | natura-1.12.2-4.3.2.69.jar
Neat | Vazkii | Neat 1.4-17.jar
Ore Tweaker | EwyBoy | Ore Tweaker-1.0.2-1.12.0.jar
Placebo | Shadows_of_Fire | Placebo-1.12.2-1.6.0.jar
Quark | Vazkii | Quark-r1.6-179.jar
RandomPatches | TheRandomLabs | randompatches-1.12.2-1.21.0.3.jar
Recurrent Complex | Ivorforce | RecurrentComplex-1.4.8.2.jar
Reliquary v1.3 | P3pp3rF1y | Reliquary-1.12.2-1.3.4.796.jar
SecretRoomsMod | AbrarSyed | secretroomsmod-1.12.2-5.6.4.jar
Soul Shards Respawn | TehNut | SoulShardsRespawn-1.12.2-1.1.1-13.jar
Spartan Shields | ObliviousSpartan | SpartanShields-1.12.2-1.5.4.jar
stimmedcow : NoMoreRecipeConflict | GotoLink | NoMoreRecipeConflict-0.13(1.12.2).jar
Storage Drawers | Texelsaur | StorageDrawers-1.12.2-5.4.2.jar
The Aether | GildedGames | aether_legacy-1.12.2-v1.4.4.jar
The Erebus | vadis365 | Erebus-1.0.31.jar
The One Probe | McJty | theoneprobe-1.12-1.4.28.jar
The Twilight Forest | Benimatic | twilightforest-1.12.2-3.10.1013-universal.jar
TheDragonLib | sokratis12GR | thedragonlib-1.12.2-5.3.0.jar
Tick Dynamic | The_Fireplace | TickDynamic-1.12.2-1.0.2.jar
Tinkers Aether | Shnupbups | tinkersaether-1.3.0.jar
Tinkers Construct | mDiyo | TConstruct-1.12.2-2.13.0.183.jar
Tinkers' Complement | KnightMiner | TinkersComplement-1.12.2-0.4.3.jar
Toast Control | Shadows_of_Fire | Toast Control-1.12.2-1.8.1.jar
Tomb Many Graves 2 | M4thG33k | TombManyGraves-1.12-4.2.0.jar
Tree Chopper | MrDuchy | TreeChopper-1.12.2-1.2.4.jar
VanillaFix | Runemoro | VanillaFix-1.0.10-99.jar
Waddles | Girafi | Waddles-1.12.2-0.6.0.jar
Wearable Backpacks | HeckinChloe | WearableBackpacks-1.12.2-3.1.4.jar
Worley's Caves | super_fluke | worleycaves-1.5.1.jar

Crash report: [https://pastebin.com/QHF8TRxk]
Launcher log: [https://pastebin.com/U8uUnd4q]

Could not get debug info because Minecraft cant open

This does not happen when I use it in vanilla and I use the installer, not the mods folder.

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? - No
- Does this happen without any mods at all?- No
- Does this happen in OptiFine standalone? - No
- Does this happen in Vanilla without OptiFine?
 
This also seems to happen with multiple other modpacks if not all of them.

**Comment by sp614x** [comment]
Caused by #4824
