### ISSUE TITLE
Crash with silent mechanisms mod drying rack and optifine 1.15.2 pre 30

### ISSUE THREAD

**Issue by Fireworkstars46** [sp614x/optifine#4664]
I have optifine for 1.15.2 pre 30 and silent mechanisms mod for 1.15.2 and whenever a creeper or any explosion destroys the drying rack from silent mechanisms while an item is in the drying rack, my game crashes. Here’s the log file link for proof https://cdn.discordapp.com/attachments/595404284720447491/746420660288356472/latest.log

**Comment by Fireworkstars46** [comment]
Is anyone going to do anything about it it's been awhile and no comments yet

**Comment by ZenIsBestWolf** [comment]
If this is still an issue please contact the mod developers.
