### ISSUE TITLE
Invisibility bug

### ISSUE THREAD

**Issue by JinJuuzou** [sp614x/optifine#4666]
## Description of Issue
I play in realms, and both I and my friend (who is also using the same version of optifine) have experienced a bug where a monster will be invisible and attack us. In both cases it was a zombie. I have also experienced all the beds in-game turning invisible for me (though they were still usable). Both times, the issue was fixed when we quit the game and restarted. Neither of us use any mods other than optifine 1.6.2 preview and the BSL shader. 

## Steps to Reproduce
None, it happens at random

## OptiFine Version
1.6.2 preview

## Installation Method
Installer

## Other Installed Mods
No mods other than shader pack BSL

## Prior Testing
If you've installed standalone:
No

- Does this happen in OptiFine standalone? Yes
- Does this happen in Vanilla without OptiFine? No

**Comment by Regnander** [comment]
Related #4322

**Comment by sp614x** [comment]
Seems to be fixed with 1.16.2 pre6.

**Comment by dbrighthd** [comment]
Hi, I am having the same problem again in the release version of 1.16.2_HD_U_G3

Like I was killed by invisible pigmen, and later some ocelots disappeared in my creative world, I had to relog for them to appear
