### ISSUE TITLE
Connect method for adjacent blocks isnt working exactly?

### ISSUE THREAD

**Issue by Thregollas** [sp614x/optifine#467]
It looks like if i want to use this method, i have to understand a little more about it. So i am using a block17.properties and inside the file i have put tiles=0-46, connect type which is material:connect if block material oak wood = block material iron block of neighbor, faces=sides and metadata=0. Game launcher doesnt show any errors in the game output and accepts the method, thing is inside the game it doesnt connect these 2 blocks but instead block17 is using ctm method. What do i need to do in this case?

**Comment by sp614x** [comment]
Can you post the block17.properties?

**Comment by Thregollas** [comment]
What do u mean, the code or the texture, i could show u both np, 
![33](https://cloud.githubusercontent.com/assets/25563766/22631078/fd15cc2e-ec0e-11e6-8142-cbdda20154a6.png)
![34](https://cloud.githubusercontent.com/assets/25563766/22631079/fd18500c-ec0e-11e6-9f30-6c90df15387a.png)
![35](https://cloud.githubusercontent.com/assets/25563766/22631080/fd1b0ea0-ec0e-11e6-9b36-a0b6c6179dd3.png)
![36](https://cloud.githubusercontent.com/assets/25563766/22631081/fd1e43b8-ec0e-11e6-8737-2b49a306ad2e.png)
![37](https://cloud.githubusercontent.com/assets/25563766/22631082/fd23b636-ec0e-11e6-9a25-c7cc52b3be2a.png)
![38](https://cloud.githubusercontent.com/assets/25563766/22631083/fd251c88-ec0e-11e6-8c99-6916f6e3cb7d.png)
![39](https://cloud.githubusercontent.com/assets/25563766/22631084/fd313fae-ec0e-11e6-9256-622eda407b7f.png)
![40](https://cloud.githubusercontent.com/assets/25563766/22631085/fd34c89a-ec0e-11e6-8d38-4038b2a60ad8.png)
![41](https://cloud.githubusercontent.com/assets/25563766/22631086/fd39bcec-ec0e-11e6-86b7-06ac7dcc9d8b.png)
![42](https://cloud.githubusercontent.com/assets/25563766/22631087/fd3aeeaa-ec0e-11e6-8fdd-47f8b6887dfc.png)
![43](https://cloud.githubusercontent.com/assets/25563766/22631088/fd3e8100-ec0e-11e6-93f7-ae9185e98392.png)
![0](https://cloud.githubusercontent.com/assets/25563766/22631089/fd417f90-ec0e-11e6-9037-282465c59e2c.png)
![1](https://cloud.githubusercontent.com/assets/25563766/22631090/fd4cff6e-ec0e-11e6-8dce-f02cbcd8d379.png)
![2](https://cloud.githubusercontent.com/assets/25563766/22631091/fd53a31e-ec0e-11e6-83d2-3b467685461c.png)
![3](https://cloud.githubusercontent.com/assets/25563766/22631092/fd559e9e-ec0e-11e6-8889-4e00ef0d1506.png)
![4](https://cloud.githubusercontent.com/assets/25563766/22631093/fd59bfec-ec0e-11e6-801c-8757cea1701a.png)
![5](https://cloud.githubusercontent.com/assets/25563766/22631094/fd5b3e94-ec0e-11e6-9bd0-74d9494448ea.png)
![6](https://cloud.githubusercontent.com/assets/25563766/22631095/fd5d7920-ec0e-11e6-9f2f-a17987048051.png)
![7](https://cloud.githubusercontent.com/assets/25563766/22631096/fd6b2bb0-ec0e-11e6-80c4-078dc6d1a50e.png)
![8](https://cloud.githubusercontent.com/assets/25563766/22631097/fd6f4fc4-ec0e-11e6-8ed4-892991e1cf82.png)
![9](https://cloud.githubusercontent.com/assets/25563766/22631098/fd719c16-ec0e-11e6-8b7e-5db49254fbae.png)
![10](https://cloud.githubusercontent.com/assets/25563766/22631100/fd78ff56-ec0e-11e6-8abe-cb56d1572175.png)
![11](https://cloud.githubusercontent.com/assets/25563766/22631099/fd778ac2-ec0e-11e6-819c-d5ecb2793745.png)
![12](https://cloud.githubusercontent.com/assets/25563766/22631101/fd7ae028-ec0e-11e6-9c71-730ad201bfc3.png)
![13](https://cloud.githubusercontent.com/assets/25563766/22631102/fd893704-ec0e-11e6-8784-71d68ba9071a.png)
![14](https://cloud.githubusercontent.com/assets/25563766/22631103/fd8a2362-ec0e-11e6-9066-ee3d13e0bf85.png)
![15](https://cloud.githubusercontent.com/assets/25563766/22631104/fd8cdd46-ec0e-11e6-83f2-c56957018a32.png)
![16](https://cloud.githubusercontent.com/assets/25563766/22631106/fd95eb3e-ec0e-11e6-889c-0e85cb83fb09.png)
![17](https://cloud.githubusercontent.com/assets/25563766/22631105/fd958ebe-ec0e-11e6-9b3a-efc7cc8d4cb0.png)
![18](https://cloud.githubusercontent.com/assets/25563766/22631107/fd9e1598-ec0e-11e6-9606-6eb78f76df69.png)
![19](https://cloud.githubusercontent.com/assets/25563766/22631108/fda4c988-ec0e-11e6-963f-a3fe912329ae.png)
![20](https://cloud.githubusercontent.com/assets/25563766/22631109/fda6e45c-ec0e-11e6-99c5-d98d0e2133a3.png)
![21](https://cloud.githubusercontent.com/assets/25563766/22631110/fdaa3990-ec0e-11e6-8e39-932b222d255b.png)
![22](https://cloud.githubusercontent.com/assets/25563766/22631111/fdb20e2c-ec0e-11e6-8ba6-6ddcd0853b1d.png)
![23](https://cloud.githubusercontent.com/assets/25563766/22631112/fdb4660e-ec0e-11e6-9d83-6a57799d1724.png)
![24](https://cloud.githubusercontent.com/assets/25563766/22631113/fdbf5618-ec0e-11e6-8ebd-56bd9e546a93.png)
![25](https://cloud.githubusercontent.com/assets/25563766/22631114/fdbfca80-ec0e-11e6-9045-ec3e2abd861c.png)
![26](https://cloud.githubusercontent.com/assets/25563766/22631115/fdc2ab38-ec0e-11e6-9efd-1509f0e52621.png)
![27](https://cloud.githubusercontent.com/assets/25563766/22631116/fdc54f28-ec0e-11e6-8244-95a85c9ff01d.png)
![28](https://cloud.githubusercontent.com/assets/25563766/22631117/fdcd3e0e-ec0e-11e6-8d0c-4bd9e19a8dcb.png)
![29](https://cloud.githubusercontent.com/assets/25563766/22631118/fdd1e8aa-ec0e-11e6-8b8e-13690b36c7f2.png)
![30](https://cloud.githubusercontent.com/assets/25563766/22631120/fddcae2a-ec0e-11e6-9d67-f880e000f52f.png)
![31](https://cloud.githubusercontent.com/assets/25563766/22631119/fddcda30-ec0e-11e6-950b-c274ffd6ceba.png)
![32](https://cloud.githubusercontent.com/assets/25563766/22631121/fddf88b6-ec0e-11e6-96fb-1274baa85e65.png)

**Comment by Thregollas** [comment]
![44](https://cloud.githubusercontent.com/assets/25563766/22631127/1af6efa2-ec0f-11e6-9cf4-e55a3ed95fb9.png)
![45](https://cloud.githubusercontent.com/assets/25563766/22631128/1b126cc8-ec0f-11e6-9b94-160e5ebe8c72.png)
![46](https://cloud.githubusercontent.com/assets/25563766/22631129/1b282658-ec0f-11e6-9515-050fdb2147b2.png)
![47](https://cloud.githubusercontent.com/assets/25563766/22631130/1b29c076-ec0f-11e6-9378-3ec5e07302bc.png)

**Comment by Thregollas** [comment]
tiles=0-46
material:connect if block material oak wood = block material iron block of neighbor
faces=sides
metadata=0

**Comment by sp614x** [comment]
The line `material:connect if block material oak wood = block material iron block of neighbor` does not make any sense. The default method is "ctm" if not specified.
Here is the CTM description: https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/ctm.properties

**Comment by Thregollas** [comment]
How can i specify how 2 blocks will look if they are next to each other?

**Comment by sp614x** [comment]
"method" defines how the blocks are to be connected
"method=ctm" connects in all directions, uses 47 textures: 
  https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/images/ctm_template.png
"method=horizontal" connects only horizontally, uses 3 textures: 
  https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/images/horizontal_template.png
"method=vertical" connects vertically, uses 4 textures: 
  https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/images/vertical_template.png
and so on...

**Comment by Thregollas** [comment]
So i use method=ctm and connect=blocks then matchblocks or what, i dont understand that well. Ik how method works for blockid.properties, this method tho i cant understand.
