### ISSUE TITLE
[Lag/Tearing] Unusual screen lag/tearing when using connected-texture heavy resource packs.

### ISSUE THREAD

**Issue by Lucipo** [sp614x/optifine#4670]
## Description of Issue
Whenever I put on a resource pack that uses lots of connected textures (EX: Better Vanilla Building) and have connected textures on either fast or fancy, my FPS average stays the same, but my screen becomes stuttery and almost feels like its tearing, even though my fps stays above 200 (144hz monitor). I turned on and off VSync ingame and in the AMD settings to no avail. The stutters arent lag spikes either.
## Steps to Reproduce
1. Use a resource pack that takes heavy advantage of connected textures
2. Go into a normal world and turn on connected textures and watch as your screen stutters without stopping.

## OptiFine Version
OptiFine 1.16.2 HD U G3 pre2

## Installation Method
Auto-install from opening jar

## F3 Debug Screenshot
![image](https://user-images.githubusercontent.com/36358294/90971943-5e0af000-e4da-11ea-94ab-dd996b2c4d4e.png)

## Prior Testing
It does not occur in vanilla with no Optifine, even with the resourcepack on. However with connected textures on with optifine and resource pack, the stutters occur.

## Additional Information
The huge world of the things you are able to do with connected textures has yet to be expanded upon in a lot of popular packs and it wont be able to take off if its as un-optimized as it is currently.

**Comment by sp614x** [comment]
Better Vanilla Building uses A LOT of CTM overlays.
This slows down the chunk loading and may create micro stutter.
This is specific to CTM overlays which work differently than normal CTM. The same amount of normal CTM would not be a problem as they can be checked much more efficiently.
