### ISSUE TITLE
CEM model scale option isnt working

### ISSUE THREAD

**Issue by mexbotdude** [sp614x/optifine#4673]
{
      "model": "nuijagabody.jpm",
      "part": "body",
      "scale": 7.0, 
      "attach": false,
      "translate": [-53.2, 10, 46.5],
      "rotate": [180, 0, 0]
    },

it simply ignores the scale option
It was working fine back in 1.14.4 and early 1.15 dev builds.

## OptiFine Version
OptiFine 1.16.2_HD_U_G3_pre2

**Comment by KaiAF** [comment]
Seems to be a duplicate for #4166. If this is a mistake, let me know.
