### ISSUE TITLE
[Quality Menu] Can't change anti aliasing values 

### ISSUE THREAD

**Issue by optfineplayer** [sp614x/optifine#4676]
## Description of Issue
One day I decided to create a world to play with my friends in version 1.16.1, and as always, I installed OptiFine to make the game more optimized and to put shaders. Only when I pressed the button to activate the shaders, I was saying that it was incompatible with anti aliasing. When I try to disable anti aliasing,
I find that I can't. I change the Mipmap Type settings, but anti aliasing remains on and at maximum. I've seen another post by a guy who had the same problem, only in version 1.15.2 (if I'm not mistaken) of OptiFine. I tried to solve the problem the way he says he did it,
changing the values ​​of the anti aliasing in the text document "optionsshaders.txt" to "antialiasingLevel = 0", it was already written "antialiasingLevel = 0" in the text document, and copying and pasting and then saving did not change anything. Please I need help

## Steps to Reproduce
1. Installed OpftiFine 
2. Tried to toggle off anti aliasing 
## OptiFine Version
1.16.2-OptFine_HD_U_G3_pre2
1.16.1-OptiFine_HD_U_G2

## Installation Method
Used the included standalone installer

## Log Files/Crash Reports
I don't know which / if Log Files could be relevant, correct me if I'm wrong and I'll put them here in the post

## F3 Debug Screenshot
![2020-08-23_13 03 36](https://user-images.githubusercontent.com/70104368/90982976-4024a600-e541-11ea-9c3f-63ccad5543bd.png)

## Prior Testing
- Does this happen in Vanilla without OptiFine?
No.

**Comment by sp614x** [comment]
Antialiasing is not working yet.
It has to be rewritten due to the render engine changes in 1.16

**Comment by optfineplayer** [comment]
But one of my friends can use shaders in 1.16.2 using OptiFine, and this issue doesn't happen with him

**Comment by Jorkles** [comment]
Go into optionsof.txt in your .minecraft folder, find ofAalevel and set it to 0.

**Comment by optfineplayer** [comment]
> Go into optionsof.txt in your .minecraft folder, find ofAalevel and set it to 0.

![2020-08-23 (4)](https://user-images.githubusercontent.com/70104368/90992955-34f56880-e589-11ea-959d-6d032ec0a4b6.png)

**Comment by Jorkles** [comment]
**optionsof.txt**

**Comment by optfineplayer** [comment]
> Go into optionsof.txt in your .minecraft folder, find ofAalevel and set it to 0.

I just found ofAoLevel
