### ISSUE TITLE
[1.16.1] Whenever I hit a mob, they don't turn red to show the hit landed

### ISSUE THREAD

**Issue by FandomsHateMe** [sp614x/optifine#4677]
## Description of Issue

A mob usually has a red overlay whenever you attack it. I don't know if it is me specifically but I dont know if a mob is getting hurt because it isn't turning red. I have accidentaly killed so many villagers accidentally because I cant tell if they are getting hurt or not.
I know it's an optifine issue because it only happens when I turn on optifine and I don't have any shaders.

**With Optifine:**
![2020-08-23_09 26 26](https://user-images.githubusercontent.com/70105322/90983634-743d9e00-e524-11ea-938e-debb7634a28a.png)

**Without Optifine:**
![2020-08-23_09 30 19](https://user-images.githubusercontent.com/70105322/90983643-7d2e6f80-e524-11ea-83c4-a4c16c6da65c.png)

## Steps to Reproduce

1. Hit a mob

## OptiFine Version

1.16.1

## Installation Method
How did you install OptiFine? Did you use the included standalone installer, or did you drop the JAR file into your "mods" folder?

standalone installer

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?

No 

## Additional Information
If there is a fix, please tell me

**Comment by SaumitraVerma** [comment]
can you please upload a gif or video

**Comment by y3th** [comment]
I can confirm that this occurs on 1.16.1-Optifine_HD_U_G2, though I'm not sure if settings have anything to do with it.
![demonstration](https://cdn.discordapp.com/attachments/280852949046132737/747791212840222740/minecrrrrrrr.gif)

**Comment by sp614x** [comment]
You are using internal shaders which are only for testing.
With shaders the red mob overlay have to be implemented in the shader pack.
