### ISSUE TITLE
[Feature request] Texture Cache

### ISSUE THREAD

**Issue by Luracasmus** [sp614x/optifine#4679]
## Description of the new feature
Save the `Texture Atlas` to disk for faster loading instead of generating a new `Texture Atlas` every time.

In order to keep track of changes to textures, OptiFine could save the `Last Modified` date of the resource pack and compare it to the new `Last Modified` date on load to decide if a reload is necessary.

**Comment by sp614x** [comment]
The atlas generation is complicated and depends on many factors.
When running with Forge/Fabric all mods use their own settings to decide which sprites to add to the atlas.
This makes it very hard to recognize if the cached atlas texture can be used or not.
