### ISSUE TITLE
Max Framerate option shows "0 FPS" instead of "VSync" [1.16.2]

### ISSUE THREAD

**Issue by xDeuiii** [sp614x/optifine#4680]
VSync still works perfectly, it simply doesn't show as "VSync", but rather shows "0 FPS"
![optifine](https://user-images.githubusercontent.com/55028626/90986850-17c79680-e597-11ea-917b-ef0cd39dc1d1.png)
"

**Comment by sp614x** [comment]
Fixed in pre3.
