### ISSUE TITLE
[Bug]Donation doesn't recognize Mojang accounts

### ISSUE THREAD

**Issue by Rh0des** [sp614x/optifine#4682]
## Description of Issue
Whenever I attempt to donate to get a cape on a new account I just bought it doesn't recognize the account as a Mojang account. Example: I want to put a cape on my account Ramada, I enter the name and choose my cape design and when I click on the payment wall it redirects me to an error message page that states that my Mojang account doesn't exist which (obviously) isn't true.

## Steps to Reproduce
1. Attempt to donate
2. Click on payment wall
3. Receive error message

**Comment by Cart3r1234** [comment]
Parts of Mojang's API down right now, there is a post about it in the Announcements channel on the discord

**Comment by sp614x** [comment]
The Mojang API is back online.
