### ISSUE TITLE
Not seeing any optifine capes on my pc, seeing them on my friend's pc

### ISSUE THREAD

**Issue by mirkonamore** [sp614x/optifine#4683]
## Description of Issue
I've recently donated to optifine and recieved an optifine cape. But I didn't see it on my pc. I went to a friend's house and logged into my account and i was seeing it there.

## OptiFine Version
1.8.9 and above. I have tried multiple versions both on mine and my friend's pc. Same problem.

## Installation Method
I had it installed in forge and I tried it as an installation aswell, still doesn't work.

## F3 Debug Screenshot
![2020-08-24_14 34 34](https://user-images.githubusercontent.com/70143026/91040450-f4dcc700-e616-11ea-88dc-836b693ee99b.png)

## Additional Information
![2020-08-24_14 36 31](https://user-images.githubusercontent.com/70143026/91040636-3f5e4380-e617-11ea-88ac-b18caf4b674e.png)
![2020-08-24_14 36 37](https://user-images.githubusercontent.com/70143026/91040639-41c09d80-e617-11ea-863e-3ff5dc5e2dd3.png)
I am on Windows 7 Ultimate

**Comment by sp614x** [comment]
Please check if:
- OptiFine is correctly installed
- the option Video Settings -> Details -> Show Capes is ON
- the option Multiplayer Settings -> Show Cape is ON
- no firewall/router/antivirus is blocking OptiFine from accessing the OptiFine server where the cape is located

In some cases the internet provider may cache the cape images.
