### ISSUE TITLE
1.16.2 Pre 3 not working with Forge 33.0.20

### ISSUE THREAD

**Issue by rogerari** [sp614x/optifine#4686]
I dropped the .jar file into the mods section and, when starting the game I am greeted with a popup saying that "File 1.16.2-OptiFine_HD_U_G3_pre3.jar is not a valid mod file"
The only other mod I have installed is SoundFilters-0.14_for_1.16.2.jar

Update: When checking the latest it says "1.16.2-OptiFine_HD_U_G3_pre3.jar is missing mods.toml file" and when opening the .jar file and looking through META-INF the mod.toml file is, indeed, absent.

**Comment by rogerari** [comment]
The only other mod I have installed is SoundFilters-0.14_for_1.16.2.jar

**Comment by HiItsDevin** [comment]
Checking through around, the mods.toml file is missing.

**Comment by sp614x** [comment]
The `mods.toml` should be inside `META-INF` folder.
Please redownload it and check again.
