### ISSUE TITLE
Crashing in Shaders settings screen

### ISSUE THREAD

**Issue by Alphaltz** [sp614x/optifine#4687]
So I was trying to use Optifine with forge but whenever I open the shaders setting page Minecraft crashes and says this.
java.lang.NullPointerException: Rendering screen
Here is the Error Log.

 ---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 8/24/20 1:18 PM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at shadersmod.uniform.ShaderExpressionResolver.registerExpressions(ShaderExpressionResolver.java:65)
	at shadersmod.uniform.ShaderExpressionResolver.<init>(ShaderExpressionResolver.java:29)
	at shadersmod.client.ShaderPackParser.parseCustomUniform(ShaderPackParser.java:805)
	at shadersmod.client.ShaderPackParser.parseCustomUniforms(ShaderPackParser.java:769)
	at shadersmod.client.Shaders.loadShaderPackProperties(Shaders.java:1077)
	at shadersmod.client.Shaders.loadShaderPack(Shaders.java:963)
	at shadersmod.client.Shaders.setShaderPack(Shaders.java:872)
	at shadersmod.client.GuiSlotShaders.func_148144_a(GuiSlotShaders.java:72)
	at net.minecraft.client.gui.GuiSlot.func_148128_a(GuiSlot.java:209)
	at shadersmod.client.GuiShaders.func_73863_a(GuiShaders.java:392)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1455)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at shadersmod.uniform.ShaderExpressionResolver.registerExpressions(ShaderExpressionResolver.java:65)
	at shadersmod.uniform.ShaderExpressionResolver.<init>(ShaderExpressionResolver.java:29)
	at shadersmod.client.ShaderPackParser.parseCustomUniform(ShaderPackParser.java:805)
	at shadersmod.client.ShaderPackParser.parseCustomUniforms(ShaderPackParser.java:769)
	at shadersmod.client.Shaders.loadShaderPackProperties(Shaders.java:1077)
	at shadersmod.client.Shaders.loadShaderPack(Shaders.java:963)
	at shadersmod.client.Shaders.setShaderPack(Shaders.java:872)
	at shadersmod.client.GuiSlotShaders.func_148144_a(GuiSlotShaders.java:72)
	at net.minecraft.client.gui.GuiSlot.func_148128_a(GuiSlot.java:209)
	at shadersmod.client.GuiShaders.func_73863_a(GuiShaders.java:392)

-- Screen render details --
Details:
	Screen name: shadersmod.client.GuiShaders
	Mouse location: Scaled: (234, 132). Absolute: (938, 488)
	Screen size: Scaled: (480, 255). Absolute: (1920, 1017). Scale factor of 4

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['mjdd27574'/409, l='MpServer', x=246.93, y=72.62, z=120.06]]
	Chunk stats: MultiplayerChunkCache: 545, 554
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (188,64,256), Chunk: (at 12,4,0 in 11,16; contains blocks 176,0,256 to 191,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 2207 game time, 2207 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 38 total; [EntityChicken['Chicken'/321, l='MpServer', x=313.47, y=70.00, z=196.50], EntityChicken['Chicken'/322, l='MpServer', x=313.66, y=70.00, z=196.41], EntityChicken['Chicken'/323, l='MpServer', x=312.50, y=70.00, z=197.50], EntityItem['item.item.seeds'/196, l='MpServer', x=183.28, y=70.13, z=99.94], EntityChicken['Chicken'/324, l='MpServer', x=312.50, y=70.00, z=195.50], EntityAnt['Ant'/260, l='MpServer', x=209.53, y=66.00, z=198.44], EntityWaypointContainer['unknown'/518, l='MpServer', x=0.00, y=0.00, z=0.00], EntityTrail['unknown'/713, l='MpServer', x=246.93, y=72.62, z=120.06], EntityChicken['Chicken'/266, l='MpServer', x=232.22, y=66.00, z=199.06], EntityChicken['Chicken'/267, l='MpServer', x=235.44, y=66.00, z=199.44], EntityChicken['Chicken'/268, l='MpServer', x=236.56, y=67.00, z=198.53], EntityBat['Bat'/721, l='MpServer', x=256.61, y=34.97, z=110.34], EntityPig['Pig'/337, l='MpServer', x=320.06, y=92.00, z=191.50], EntityButterfly['Butterfly'/274, l='MpServer', x=263.37, y=73.58, z=116.06], EntityPig['Pig'/338, l='MpServer', x=322.50, y=91.00, z=187.47], Cockateil['Bird'/275, l='MpServer', x=252.33, y=76.85, z=127.40], EntityPig['Pig'/339, l='MpServer', x=322.50, y=90.47, z=188.50], EntityChicken['Chicken'/214, l='MpServer', x=200.56, y=68.00, z=175.63], EntityChicken['Chicken'/278, l='MpServer', x=242.88, y=68.00, z=197.69], EntityButterfly['Butterfly'/279, l='MpServer', x=266.14, y=79.88, z=122.34], EntityChicken['Chicken'/215, l='MpServer', x=202.63, y=68.00, z=180.78], EntityItem['item.item.ESeeds'/280, l='MpServer', x=265.81, y=70.13, z=150.59], EntityChicken['Chicken'/216, l='MpServer', x=202.50, y=68.00, z=178.50], EntityBat['Bat'/729, l='MpServer', x=256.69, y=35.76, z=111.53], EntityChicken['Chicken'/217, l='MpServer', x=198.63, y=68.00, z=178.56], EntityAnt['Ant'/218, l='MpServer', x=204.53, y=65.00, z=194.34], EntityAnt['Ant'/219, l='MpServer', x=202.50, y=66.00, z=192.50], EntityAnt['Ant'/220, l='MpServer', x=196.53, y=68.00, z=199.47], EntityBat['Bat'/733, l='MpServer', x=249.38, y=31.00, z=181.47], EntityClientPlayerMP['mjdd27574'/409, l='MpServer', x=246.93, y=72.62, z=120.06], EntityHat['unknown'/420, l='MpServer', x=246.93, y=72.62, z=120.06], EntityHat['unknown'/804, l='MpServer', x=322.50, y=91.00, z=187.47], RockBase['Rock'/239, l='MpServer', x=220.50, y=71.00, z=91.50], EntityChicken['Chicken'/240, l='MpServer', x=215.75, y=69.00, z=117.35], EntityChicken['Chicken'/241, l='MpServer', x=221.50, y=69.00, z=110.50], EntityChicken['Chicken'/242, l='MpServer', x=220.50, y=70.00, z=108.50], EntityChicken['Chicken'/243, l='MpServer', x=218.50, y=69.00, z=112.50], EntityPig['Pig'/318, l='MpServer', x=319.50, y=90.00, z=190.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:425)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 488885864 bytes (466 MB) / 1509949440 bytes (1440 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 3, tcache: 1, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.3.1407 Optifine OptiFine_1.7.10_HD_U_E7 32 mods loaded, 32 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.3.1407-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.3.1407} [Minecraft Forge] (forge-1.7.10-10.13.3.1407-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	RenderPlayerAPI{1.4} [Render Player API] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	TooManyItems{1.7.10} [TooManyItems] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FamiliarsAPI{1.7.10} [Familiars API] (FamiliarsAPI-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	imsm{1.7.10} [Instant Massive Structures Mod] (1.7.10.InstantMassiveStructuresMod2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	legends{3.4} [Legends Mod] (1Legends-1.7.10-3.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4 (1).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	animalbikes{1.7.10} [Animal Bikes] (AnimalBikes_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Backpack{2.0.1} [Backpack] (Backpacks-Mod (1).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FLabsBF{4.3} [Better Furnaces] (Better-Furnaces-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	DamageIndicatorsMod{3.3.2} [Damage Indicators] (Damage-Indicators-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	emeraldmod{3.5.1} [EmeraldMod] (Emerald-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	eplus{3.0.2-d} [Enchanting Plus] (EnchantingPlus-1.7.10-3.0.2-d.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	DefaultMobPack{1.7.10} [DefaultMobPack] (FamiliarsDefaultMobPack-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ExtendedFamPack{1.7.10} [ExtendedFamPack] (FamiliarsExtendedFamPack-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	HerobrineFamPack{1.7.10} [HerobrineFamPack] (FamiliarsHerobrineFamPack-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	iChunUtil{4.2.3} [iChunUtil] (iChunUtil-4.2.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	GraviGun{4.0.0-beta} [GraviGun] (GravityGun-4.0.0-beta.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Hats{4.0.1} [Hats] (Hats-4.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	lootplusplus{0.24_for_1.7} [Loot++] (Loot-Plus-Plus-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	lucky{5.1.0} [Lucky Block] (Lucky-Block-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	malisiscore{1.7.10-0.13.1} [MalisisCore] (malisiscore-1.7.10-0.13.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	malisisdoors{1.7.10-1.12.0} [Malisis' Doors] (malisisdoors-1.7.10-1.12.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	cfm{3.4.7} [§9MrCrayfish's Furniture Mod] (MrCrayfishs-Furniture-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	OreSpawn{1.7.10.20.3} [OreSpawn] (orespawn-1.7.10-20.3 (1).zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	PortalGun{4.0.0-beta-6} [PortalGun] (PortalGun-4.0.0-beta-6 (1).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	rivalrebels{1.7.10Z1} [Rival Rebels] (rivalrebels-1.7.10Z1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	voxelmap{1.7.10} [VoxelMap No Radar] (VoxelMap-No-Radar-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	nolpfij_wildycraft{1.7.4} [Wildycraft] (wildycraft-1.7.10-1.7.4 (3).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 417.35' Renderer: 'GeForce GTX 1050 Ti/PCIe/SSE2'
	Launched Version: 1.7.10-Forge10.13.3.1407-1.7.10
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 417.35, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by sp614x** [comment]
Fixed in pre4
