### ISSUE TITLE
Better Grass Occurring on All Grass Blocks, Not Just Adjacent 1-Level-Higher Blocks

### ISSUE THREAD

**Issue by pmackni** [sp614x/optifine#4688]
As the title suggests, there's an issue I've noticed with my preferred resource pack: Conquest. It could be an issue with how Optifine reads the info from the pack that change from 1.15 (current build of his pack) to 1.16, but I find that doubtful.

ISSUE: 

When I turn on Better Grass in my options (it's defaulted to off), all grass blocks get a full side of grass, rather than a blend of the resource pack's grass block side texture and provided Better Grass textures, depending on if a given grass block is located a single block higher and directly adjacent to another, as expected. 

ADDITIONAL INFO:

Optifine Version: 1.16.1 HD U G2

I am also receiving an "OpenGL Error: 1281 (Invalid value)" message display. As I'm no longer very familiar with early Optifine builds for each version (for a while I waited for later, more stable builds before hopping in), I don't know if this is just a standard error that throws frequently due to the nature of this mod, or if this somehow is/could be related to the Better Grass option. However, this message appears regardless of the on/off state for Better Grass. If the info could be of help, I can update/reply with the output log info for the game when I get the message.

Admittedly, I haven't played MC for a few updates, so my last experience with Optifine and his pack was ≈1.12 or so, and with a more flushed out version of Optifine at that (≈4th build for the patch I was playing at the time). As such, this may just be something that's already in the works or addressed and awaiting the next build drop on the website, but I'd like to know for sure to put my mind at ease. It's a little disappointing to play without Better Grass, but I can put up with it until Optifine gets an update to patch it.

If this is not an Optifine issue, please let me know and I'll pass word on to the RP author to let him know of the potential/upcoming issues with Better Grass for his next version release.

**Comment by pmackni** [comment]
Okay, I may have prematurely posted this. I started having the same issue with a 1.16.2 preview, but then realized I hadn't yet set Better Grass to Fancy. I will have to investigate later when I have time, and will mark this as closed due to my own lack of research if this is also the case for 1.16.1.

**Comment by KaiAF** [comment]
Is this still an issue?
