### ISSUE TITLE
[1.16.2] OpenGL Error: 1281 when graphics on Fabulous!

### ISSUE THREAD

**Issue by DasteWasTaken** [sp614x/optifine#4692]
## Description of Issue
OpenGL Error: 1281 occurring when graphics on Fabolous!

## Steps to Reproduce
1. Set Graphics On Fabolous!

## OptiFine Version
1.16.2 pre 3

## Installation Method
Via the installer

## Other Installed Mods
None

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine? No

**Comment by Regnander** [comment]
Related#4474

**Comment by sp614x** [comment]
Have you tried to reset video settings (Video Settings -> Other -> Reset)?
Is there a specific option or resource pack which triggers the error?

**Comment by DasteWasTaken** [comment]
Just tried resetting it, still happening.

**Comment by Sinxar** [comment]
I am getting this with 1.16.3 with optifine version OptiFine_1.16.3_HD_U_G3.
This also occurred with 1.16.2. I have tried to reset all graphics settings and it still happens.
I am using the standalone jar installer. No other mods are in use.

I can reproduce it by opening my inventory while in fullscreen mode. Then pressing the "Windows" key to get out of the game. When I maximize the game again, it will give me the error twice.

Attached is the full latest.log. It is also shown in the launcher_log.txt so im including that as well. Let me know if you need more information.

[latest.log](https://github.com/sp614x/optifine/files/5238997/latest.log)
[launcher_log.txt](https://github.com/sp614x/optifine/files/5239016/launcher_log.txt)

**Comment by Hazmi35** [comment]
I have the same problem here, tried resetting video settings, using default settings, but it is still happening

**Comment by PyricDemon** [comment]
I'm using Optifine 1.16.5 not sure what version had a problem here https://bugs.mojang.com/browse/MC-197328 and fixed it with switching to fabulous, but now I'm having this issue. Very annoying.

**Comment by KaiAF** [comment]
Is this still an issue?
