### ISSUE TITLE
Curseforge mod copies OptiFine

### ISSUE THREAD

**Issue by KenyMylankca** [sp614x/optifine#4693]
you must see this
https://www.curseforge.com/minecraft/mc-mods/openviwer

**Comment by KenyMylankca** [comment]
it does EVEN generates optionsof.txt file in the game folder xD

**Comment by cycle00** [comment]
So, uhh, what's the bug?

**Comment by KenyMylankca** [comment]
oh so it'll be the official optifine right away to future?

**Comment by HiItsDevin** [comment]
what? can you please explain

**Comment by KenyMylankca** [comment]
i just didn't think OP team gonna be ok with it, but it's ok if it's not a "bug" or an issue

**Comment by cycle00** [comment]
What? You said biggest bug ever, I would like to know where the bug is? You posted a link to a separate mod, with no further information. I would simply like to know more.

**Comment by KenyMylankca** [comment]
just install the mod and see it's a copy of optifine, but idk if you guys ok with it xD like i said, it does even generate the "optionsof.txt" file. but i think you don't care at all.

**Comment by HiItsDevin** [comment]
Oh wait, i see what's going on, literally a renamed OptiFine jar uploaded to curseforge.

**Comment by cycle00** [comment]
Ohh

**Comment by KenyMylankca** [comment]
actually a modified jar.

**Comment by HiItsDevin** [comment]
it's still taking optifine's code im pretty sure.

**Comment by KenyMylankca** [comment]
cus it crashes on selecting shaders, etc. it doesn't work very stable. but yeah it has all the features of optifine. just read the mod description page, or just install the mod and see. EVEN the explanation is the SAME with optifine XD they say doubling the FPS in common, just like optifine says in homepage. lol

**Comment by KenyMylankca** [comment]
and sorry for the funny issue name. lol

**Comment by HiItsDevin** [comment]
checking through it with JD-GUI, they literally took optifine code and class files. nice.
![image](https://user-images.githubusercontent.com/30705254/91206512-22c81700-e6bc-11ea-953e-bd8b3ecd12c3.png)
![image](https://user-images.githubusercontent.com/30705254/91206538-2d82ac00-e6bc-11ea-8ea4-13f880ac3637.png)
![image](https://user-images.githubusercontent.com/30705254/91206554-33788d00-e6bc-11ea-9b4f-1f90755d1e71.png)

**Comment by KenyMylankca** [comment]
yeah i noticed this first and i want to be awarded or something 
![fetchimage](https://user-images.githubusercontent.com/41585837/91206693-3735ff00-e710-11ea-9966-53f1b1b8a3c8.png)

**Comment by Jorkles** [comment]
this is so funny

**Comment by KenyMylankca** [comment]
lol he rageclosed comments section. KEKW

**Comment by sp614x** [comment]
Reported as stolen. It should be taken down shortly.

**Comment by KenyMylankca** [comment]
it's still up... they didn't take it down. seems like they ignore something about optifine's licence things xD

**Comment by yezhiyi9670** [comment]
The mod is not taken down. Please consider reporting to the staff.

**Comment by Jorkles** [comment]
It is known, and I believe sp himself has reported it.
