### ISSUE TITLE
[Bug] 1.10.2 Malisis Core crashes game on startup with Optifine loaded, without Optifine loaded it loads fine.

### ISSUE THREAD

**Issue by spiral6** [sp614x/optifine#4694]
## Description of Issue
Malisis Core crashes game on startup with Optifine loaded, without Optifine loaded it loads fine.

## Steps to Reproduce
1. Added `malisisdoors-1.10.2-5.2.0` and `malisiscore-1.10.2-4.4.0`. 
2. Added `OptiFine_1.10.2_HD_U_H5`.
3. Launched game in MultiMC.
4. Crashed.

## OptiFine Version
OptiFine_1.10.2_HD_U_H5

## Installation Method
Mods folder.

## Fabric/Forge Version
OptiFine_1.10.2_HD_U_H5 Forge

## Other Installed Mods
*Every* single mod you have installed, besides OptiFine. Please don't leave anything out, even if you think it has nothing to do with the issue at hand. For long lists of mods, use Pastebin. https://pastebin.com/
https://pastebin.com/715M2dK4

## Log Files/Crash Reports
Any relevant log files. Drag and drop text files here to upload to GitHub directly, OR upload the complete contents to Pastebin. https://pastebin.com/715M2dK4

## Prior Testing
Optifine works fine by itself. Malisis Doors and Malisis Core work fine by themselves. When both Optifine and Malisis Core is added, the game crashes stating an error due to Malisis Core. This error was apparently evident in earlier versions of Optifine, and updating Optifine fixed it. This bug seems to have regressed in newer versions of Optifine.

## Additional Information
Here goes any final remarks and everything else that might not fit in the previous sections.

**Comment by sp614x** [comment]
There are many core mods installed, anyone of them could be the problem:
```
WARNING: coremods are present:
  PlusTiC (PlusTiC-Mod-1.11.2.jar)
  BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.4.347.jar)
  CoreMod (Aroma1997Core-1.9.4-1.1.1.2.jar)
  SFRCore (SolarFluxReborn_1.10.2-2.17r.jar)
  MalisisCorePlugin (malisiscore-1.10.2-4.4.0.jar)
  LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.66-beta.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.7.2-anarchy.jar)
  AppEngLoadingPlugin (appliedenergistics2-rv4-stable-1.jar)
  IC2core (industrialcraft-2-2.6.252-ex110.jar)
  Brandon's Core (BrandonsCore-1.10.2-2.1.13.133-universal.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.283-universal.jar)
  HammerCoreCore (HammerCore-1.10.2-1.9.4.3.jar)
  RebornCoreASM (RebornCore-1.10.2-2.13.6.142-universal.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  AdvancedRocketryPlugin (AdvancedRocketry-1.10.2-1.0.19.jar)
  CTMCorePlugin (CTM-MC1.10.2-0.2.3.26.jar)
Contact their authors BEFORE contacting forge
```

**Comment by sp614x** [comment]
To find the conflicting mod:
- split mods in two groups
- test one group with OptiFine, keep the group that has the problem
- repeat until only one other mod is left

**Comment by DarthDuroq** [comment]
I completed the above steps and replicated the issue with only MalisisDoors, Malisis Core, and Optifine Installed, exact same crash:
https://pastebin.com/atjXQDFC

**Comment by sp614x** [comment]
```
Caused by: java.lang.NullPointerException
	at net.malisis.core.asm.AsmUtils.changeFieldAccess(AsmUtils.java:343)
	at net.malisis.core.asm.AsmUtils.changeFieldAccess(AsmUtils.java:314)
	at net.malisis.core.util.blockdata.BlockDataHandler.<clinit>(BlockDataHandler.java:75)
	... 41 more
```
MalisisCore tries to ASM patch some OptiFine classes and fails.
Can't be fixed by OptiFine.

**Comment by spiral6** [comment]
https://github.com/sp614x/optifine/issues/3238 is another open issue that references the same mod.

After some testing, it seems as though `OptiFine_1.10.2_HD_U_E7.jar` does indeed work but `Optifine_1.10.2_HD_U_H5.jar` does not work. Some sort of regression occurred.

**Comment by sp614x** [comment]
Probably the OptiFine class is changed in H5 and the patch that MalisisDoors tries to apply is not updated.
