### ISSUE TITLE
Crash on startup with Forge and Resourcepack

### ISSUE THREAD

**Issue by stendler** [sp614x/optifine#47]
Similar to #46 my Minecraft crashes when loading OptiFine via Forge. But only when a resourcepack other than default is selected. The error itself seems to be different.
[crash report gist](https://gist.github.com/stendler/cef8a6e7e658310364fc) & [game output](https://gist.github.com/stendler/cef8a6e7e658310364fc#file-game-output-txt).

Also noting that the game starts fine when OptiFine is removed from the mods folder.

Additionally, when starting with the default resourcepack and I change it to a different ones it _sometimes_ crashes with an OutOfMemory error. Which could be something on my side but strangely doesn't happen on a profile without forge.

**Comment by sp614x** [comment]
Fixed in A5_pre.
