### ISSUE TITLE
[1.16] [Shaders] Glowing Entities Don't Work At All With Shaders

### ISSUE THREAD

**Issue by EminGT** [sp614x/optifine#4700]
## Description of Issue
Glowing entities don't work with shaders, including "(internal)". This includes:
- They don't show up in front of things.
- They can't be dedected using "is_glowing".
- They don't seem to be rendered in "gbuffers_entities_glowing" and always rendered in "gbuffers_entities".

## Steps to Reproduce
1. Select "(internal)" as your shader.
2. Shoot an entity with a spectral arrow.
3. Notice how there is nothing changed about the entity.

## OptiFine Version
OptiFine 1.16.2 HD U G3 pre5

## Installation Method
Standalone installer.

## F3 Debug Screenshot
https://cdn.discordapp.com/attachments/744999695515910245/748234352772775947/unknown.png

**Comment by sp614x** [comment]
Fixed in pre7.
Glowing entities should be rendered with program `gbuffers_entities_glowing`.
