### ISSUE TITLE
[Website] HTTPS cape request support

### ISSUE THREAD

**Issue by rtm516** [sp614x/optifine#4701]
## Description of the new feature
I'm from the GeyserMC project and we use this URL to get player capes `http://s.optifine.net/capes/%s.png` and I'm working on porting this to Android. The issue is that Android won't send requests to HTTP sites only HTTPS and trying to make a HTTPS request to `s.optifine.net` fails. Any chance you could allow HTTPS request to that domain?

**Comment by sp614x** [comment]
You can use `https://optifine.net/capes/%s.png`
