### ISSUE TITLE
World created in 1.16.2 pre3 takes forever to load in pre5

### ISSUE THREAD

**Issue by K-n1ght1** [sp614x/optifine#4703]
## Description of Issue
I made a world in pre3 and tried loading it in pre5. I was just left sitting in a void watching the day/night cycle happen and if I looked down I could see my character's hand down near the middle of the screen like it would be right when a world is loaded. Initially, I tried saving a quitting and that also took forever so I always ended up trying to close the game and it never worked so I had to do it through task manager. After attempting to load the world and just letting it sit for 4-5 minutes, it finally loaded.

## Steps to Reproduce
1. Create a world in 1.16.2 pre3 
2. Load that world in 1.16.2 pre5

## OptiFine Version
Optifine HD G3_Pre5 Ultra

## Installation Method
Standalone Installer

## Other Installed Mods
No other mods

## Additional Information
Here goes any final remarks and everything else that might not fit in the previous sections.

**Comment by sp614x** [comment]
Pre5 allows render distance over 37 to work correctly.
If you render distance is set at 64 the world loading may take longer than before.
In this case reduce the render distance to 16 or lower.
