### ISSUE TITLE
Crash On 1.8.9 HD U L5

### ISSUE THREAD

**Issue by ExDiggers** [sp614x/optifine#4704]
When launching forge with optifine U L5 installed, it crashes. This happens with no other mods besides optifine. A redownload does not fix this.

## OptiFine Version
1.8.9

## Installation Method
Put it in my mods folder

## Fabric/Forge Version
Forge version 1.8.9-11.15.1.1722

## Other Installed Mods
None

## Log Files/Crash Reports
https://pastebin.com/J4ubKPvV - Log
https://pastebin.com/976CCTZr - Crash Report

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   - Only OptiFine and Forge
- Does this happen without any mods at all?
   - No
- Does this happen in OptiFine standalone?
- No
- Does this happen in Vanilla without OptiFine?
  - No
- Have you tried using a binary search to find which mods cause this issue?
  - No
   - To find conflicting mods, split your mods into 2 groups (not including OptiFine/OptiFabric, obviously). Remove one group, and test in-game. Keep the group that has the problem, and repeat until no more mods can be removed without the issue disappearing.
   - Does the issue still happen with only the remaining mods installed?
      - No

Thanks

**Comment by Trimpsuz** [comment]
Having the exact same issue. Have you found anything yet?

**Comment by ExDiggers** [comment]
Yeah I forgot to post, I cleared my optifine folder in .minecraft and it worked again
