### ISSUE TITLE
Right click to choose previous value on Shader options

### ISSUE THREAD

**Issue by SuspiciousLookingOwl** [sp614x/optifine#4706]
Since you added more Render Quality options from #4651, I think you should also allow us to choose previous value by right clicking on the button. 

![image](https://user-images.githubusercontent.com/32597776/91400752-66608380-e86a-11ea-9914-0214aaae4608.png)

I need to traverse to higher value then go back to lower value if I want to choose anything lower than 1x. If you added this feature, say I want to choose 0.9x, I just need to right click once.

I saw this being implemented on `Shader Options...` menu on many Shaders.

**Comment by sp614x** [comment]
Lower values for Render Quality and Shadow Quality can be selected with Shift + right click.

**Comment by SuspiciousLookingOwl** [comment]
Ahh good to know that, is it possible to add right click too? Since most menu on `Shader Options...` also use right click.

**Comment by sp614x** [comment]
Fixed in pre6 to behave like the shader pack options.
Right click selects previous value, Shift + click resets to default value.
