### ISSUE TITLE
OptiFine 1.16.2 HD U G3 pre5 emissive textures black shields and banners.

### ISSUE THREAD

**Issue by JimStoneCraft** [sp614x/optifine#4707]
## Description of Issue
If you hold an item or block that has emissive textures in you main hand then Shields and Banners held in your off hand are completely black when viewed in the third person view.

## Steps to Reproduce
1. Hold and item or block in your main hand (that has emissive textures)
2. Hold a banner or shield on you off hand, it will appear completely black

## OptiFine Version
OptiFine 1.16.2 HD U G3 pre5

## Installation Method
Standalone installer.

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
No it only happens if emissive textures are present for a block or item.

For example in the John Smith Legacy packs, I have put emissive textures on all the Netherite tools and armor items.

netherite_sword.png (normal texture)
netherite_sword_e.png (emissive texture)
etc...

https://www.johnsmithlegacy.co.uk/

![Black Shield and Banners 01](https://user-images.githubusercontent.com/42512910/91418172-b3802d80-e849-11ea-88eb-14685188c617.png)
![Black Shield and Banners 02](https://user-images.githubusercontent.com/42512910/91418177-b418c400-e849-11ea-8c19-bf01f41b74a4.png)
![Black Shield and Banners 03](https://user-images.githubusercontent.com/42512910/91418178-b4b15a80-e849-11ea-990c-07d769279d61.png)
![Black Shield and Banners 04](https://user-images.githubusercontent.com/42512910/91418179-b4b15a80-e849-11ea-8309-3134db79e88c.png)

**Comment by sp614x** [comment]
Fixed in pre6
