### ISSUE TITLE
Barrier block shader bug

### ISSUE THREAD

**Issue by yitzy299** [sp614x/optifine#4708]
## Description of Issue
![image](https://user-images.githubusercontent.com/66269211/91435669-99047f00-e85e-11ea-8b9b-71877f431fe6.png)

The barrier blocks seem to render behind the water

## Steps to Reproduce
1. I found a tree and destroyed the lower 3 blocks. 
2. Used Silders Lite shaders

## OptiFine Version
1.16.2 pre4

## Installation Method
Used the installer

## F3 Debug Screenshot
![image](https://user-images.githubusercontent.com/66269211/91435489-4fb42f80-e85e-11ea-8b3b-6c5f050c465c.png)

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
This is with shaders, can't run shaders without optifine. Without the shaders, the barrier blocks render above the water

## Additional Information
Here goes any final remarks and everything else that might not fit in the previous sections.

**Comment by sp614x** [comment]
The ordering of translucent blocks and entities (barrier) is handled by the shader pack.
Can't be fixed in OptiFine.
