### ISSUE TITLE
1.16.2 pre 5 invisible piglins and piglin brutes inside bastions

### ISSUE THREAD

**Issue by MacGyver4** [sp614x/optifine#4710]
## Description of Issue
Any time you launch the game in OptiFine 1.16.2_HD_U_G3_pre5 and enter a bastion for the first time all the piglins and piglin brutes are invisible. You cannot see them with hitboxes or giving every entity the glowing effect. The problem is they can still hit and kill, but can't be hit and can only be killed by thorns on the armor.

## Steps to Reproduce
1. Launch 1.16.2 in OptiFine 1.16.2_HD_U_G3_pre5 
2. open a new world
3. go to the nether
4. go into a bastion
5. equip yourself with gold armor
6. change gamemode to survival (if in creative) it doesn't matter what you start with it has done it with both
7. walk around and try and find a brute
8. you have probably died due to an invisible brute

## OptiFine Version
OptiFine 1.16.2_HD_U_G3_pre5

## Installation Method
Used the stand alone installer

## Log Files/Crash Reports
None

**DO NOT directly copy and paste log contents here on GitHub.**

## F3 Debug Screenshot
![2020-08-27_12 20 10](https://user-images.githubusercontent.com/70336597/91468287-c43b9e00-e85f-11ea-81ed-e0aab480a597.png)

Minecraft's built-in debug screen provides *a lot* of useful information, and should be included even if the issue is not something that can be captured in a still image.

To open this menu, simply press `F3` on your keyboard while in-game. Please ensure the text is easily readable. Depending on the size/resolution of your monitor, you may have to adjust your GUI scale for all text to be completely visible on-screen.

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
Does not happen if in pure vanilla without optifine.

## Additional Information
Tried in multiple worlds with same results
if you go into the bastion in pure vanilla and then log out, then go back into the world with optifine you can see the brutes that you generated, but you won't see any new piglin spawns. Don't reccomend changing from pure to optifine because then it makes the game really laggy around the pre loaded bastion.

**Comment by sp614x** [comment]
How are the player coordinates visible in the middle of the screen? Custom launcher?

![image](https://user-images.githubusercontent.com/16635441/91483672-59628500-e8a8-11ea-8993-7e1cc29e10c2.png)

**Comment by sp614x** [comment]
Can't reproduce the invisible mobs so far.
Create new world, make portal, equip golden armor, switch to survival, go to nether => piglins and brutes are visible.
Repeated several times, same result.

**Comment by MacGyver4** [comment]
It's a datapack from VanillaTweaks. The issue was resolved with version pre6. I don't know why they never showed up. It was doing it in all the 1.16.2 pre versions until 6. They now show up on version pre 6.Thanks for trying. I really appreciate what you do.
