### ISSUE TITLE
[GUI] Loading Screen Blending Mode

### ISSUE THREAD

**Issue by SyndiShanX** [sp614x/optifine#4712]
Add an option to change the Loading Screen Blending mode as the current Blending Mode breaks some Logos
Source Image:
![mojangstudios](https://user-images.githubusercontent.com/23367120/91501833-7ee59380-e894-11ea-8d52-34058542c534.png)
Loading Screen:
![Logo](https://user-images.githubusercontent.com/23367120/91501861-90c73680-e894-11ea-8fed-79767363502f.png)

**Comment by sp614x** [comment]
Fixed in pre7.
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/color.properties#L253

**Comment by ItzNathaniel** [comment]
Turning blend mode off introduces artifacts around the logo. Do you want me to make a new issue over this?
![unknown](https://user-images.githubusercontent.com/11449808/91911745-95aa3280-ec66-11ea-95d4-16cd9bb27ba0.png)

**Comment by Michael18751** [comment]
Can someone tell me what the blending mode for 1.15x and below uses? (or the string)
@sp614x 
@ItzNathaniel 

screen.loading.blend=<off|src dst srcA dstA>?
