### ISSUE TITLE
Important Support to a Simple Mod

### ISSUE THREAD

**Issue by kenijey** [sp614x/optifine#472]
the mod is **Real First-Person Render**. It just removes the hand hud and adds the real body on the screen, it is a pretty nice mod. but what is the problem?
it works fine with default options, but when i activate ANY shader (even **internal**) the old hand becomes on the screen. so i am getting 1 extra hand in total. can you add a shader setting about disabling the hand please? i really want to use that mod with optifine. i hope you help.
using optifine b_7, forge 2227, minecraft 1.11.2.

**Comment by sp614x** [comment]
Preview B7 for 1.11.2 is updated.
- fixed Forge RenderHandEvent to work with shaders

**Comment by kenijey** [comment]
thanks a lot ^^
