### ISSUE TITLE
[Bug/Poblem] Black/white lines between blocks, only with optifine

### ISSUE THREAD

**Issue by hercaa** [sp614x/optifine#4721]
## Description of Issue
Doesn't matter which version, lines are always there. Don't know what to do at this point. I tried
many versions and with optifine, it's always there. Now when i think about it, it started when i messed about with GeForce settings and Anisotropic filtering. At first i couldn't turn the AF off, only on optifine but I somehow managed it. The lines are still there.
![2020-08-28_18 52 44](https://user-images.githubusercontent.com/70395689/91594532-5c21b080-e962-11ea-8102-575498726e27.png)
![2020-08-28_18 53 03](https://user-images.githubusercontent.com/70395689/91594547-60e66480-e962-11ea-945c-ce255baa05d8.png)
![2020-08-28_18 55 30](https://user-images.githubusercontent.com/70395689/91594567-6774dc00-e962-11ea-8bc5-c7de1e1093f8.png)
![2020-08-28_18 57 17](https://user-images.githubusercontent.com/70395689/91594581-6c399000-e962-11ea-8504-2199730e04cc.png)

## OptiFine Version
Tried 1.14, 1.15, 1.16.

## Installation Method
Standalone installer.

## F3 Debug Screenshot
![2020-08-28_19 05 55](https://user-images.githubusercontent.com/70395689/91594148-b0786080-e961-11ea-8288-8391c032956e.png)

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
No.

## Additional Information
I guess it's something to do with my graphic card settings, but i tried everything that came to my mind and now i'm hopeless.

**Comment by Jorkles** [comment]
Go into Nvidia control panel and set Antialiasing and anisotropic filtering to “Application controlled.”

**Comment by hercaa** [comment]
Right when I submited this, I managed to sort it out. Sorry if I bothered you with this or took your time. Have a nice day and sorry!
