### ISSUE TITLE
[Bug] OptiFine 1.16.3_G3 Ultra generates extra region files upon saving world

### ISSUE THREAD

**Issue by Evtema3** [sp614x/optifine#4722]
## Description of Issue
When trying to save/load a singleplayer world with only 4 total region files, OptiFine generates an extra 12 region files for areas that have not been occupied or explored, and even when these are deleted, they regenerate themselves upon reload.

The region files I only need are r.0.0, r.0.-1, r.-1.-1, and r.-1.0, but OptiFine creates r.0.1, r.0.-2, r.1.0, r.1.1, r.1.-1, r.-1.1, r.1.-2, r.-1.-2, r.-2.0, r.-2.1, r.-2.-1, and r.-2.-2. The extra region files are always 1,800 KB, 1,672 KB, 736 KB, or 684 KB in size, but I can't imagine what they contain, and deleting them has no visible effect on the world.

## Steps to Reproduce
1. Load world in OptiFine HD G3 Ultra for 1.16.2
2. Save world (this takes significantly longer in these versions)
3. Inspect region folder for extra region files
4. Delete extra region files, repeat steps 1-3, and see extra region files again

## OptiFine Version
OptiFine HD G3 Ultra for 1.16.2

## Installation Method
Standalone installer.

## Log Files/Crash Reports (Outdated, see comment)
[latest.log](https://github.com/sp614x/optifine/files/5144023/latest.log)

## F3 Debug Screenshot (Outdated, see comment)
![2020-08-28_16 14 07](https://user-images.githubusercontent.com/63302963/91611845-1eb12900-e94a-11ea-91d0-748430bc3626.png)

## Prior Testing
This doesn't happen in Vanilla without OptiFine. This also doesn't happen as recently as OptiFine 1.16.2 pre2, but I only noticed it to be a problem as of pre5 and it is still a problem as of the full release of OptiFine 1.16.2_G3. I am not using any other mods or Forge or Fabric..

## Additional Information
This world is not a conventional survival world, but is instead for a minigame map. There is only a certain number of chunks needed in the whole world (which are forceloaded and contained in a world border), and it would be ideal to keep world size to a minimum. The server ticks have also been running behind more than usual in the latest OptiFine prereleases, but this is not as great of a concern to me as the extra region files. For now, I will probably stick to 1.16.2 pre2, and I can provide a log file and screenshot for that too if necessary.

**Comment by Evtema3** [comment]
This is also a problem as of the full release of OptiFine 1.16.2_G3 Ultra, and so I've updated the title and steps to reproduce. Here's a log file and screenshot to go along with that:
[latest.log](https://github.com/sp614x/optifine/files/5145397/latest.log)
![2020-08-29_11 04 04](https://user-images.githubusercontent.com/63302963/91639904-e5c79180-e9e7-11ea-8bb6-7473aea10990.png)

Also, here's a screenshot of the region folder after loading/saving the world in OptiFine: 
![image](https://user-images.githubusercontent.com/63302963/91639919-01cb3300-e9e8-11ea-9e35-9fc16af67449.png)
Note that the only region files I need have sizes of 4,000KB or greater.

If necessary, I can try to attach a copy of the world in question (without the extra region files) to assist in finding the root cause. Thanks for your correspondence!

**Comment by Evtema3** [comment]
This is still a problem as of the latest prerelease of OptiFine 1.16.3_G3 Ultra.

**Comment by Evtema3** [comment]
This issue no longer occurs as of OptiFine 1.16.4 G5. Not sure when or how it got fixed, but everything's working as expected again.

**Comment by sp614x** [comment]
It was fixed in v1164_G5_pre2.
