### ISSUE TITLE
[Feature/Compatibility] Add fancy fog support for AMD/Intel GPUs

### ISSUE THREAD

**Issue by yezhiyi9670** [sp614x/optifine#4731]
## Description of the new feature

Indicated as a bug in #4363.

Please add fancy fog (this should include atmospheric effects such as underwater fog) support for AMD/Intel GPUs. This should not be impossible because it's just a simple calculation in screenspace. It's possible that some AMD cards support it (some of them use OpenGL 4.6) but Optifine refuses to render it.

**Comment by sp614x** [comment]
Radial fog on AMD/Intel can only be added with shaders. For example a simple shader pack can add only radial fog.

**Comment by yezhiyi9670** [comment]
Can you provide such a pack?

**Comment by yezhiyi9670** [comment]
Why not possible?

**Comment by sp614x** [comment]
I made a shader pack for radial fog long time ago, but can't find it now.

**Comment by yezhiyi9670** [comment]
> I made a shader pack for radial fog long time ago, but can't find it now.

I think writing such a pack is not a big deal, but I can't make it work correctly. I'll be very thankful if you can give me the pack.

My issues:

- Bright entities - Entities does not respect angle-based lighting.
- Incorrect fog in water and lava (especially lava)
- Emissive textures on mobs do respect sky lighting. For example, spider eyes are alaways dark during the night.

**Comment by Birevan** [comment]
> Radial fog on AMD/Intel can only be added with shaders.

Hey @sp614x. I have two systems on my AMD device: Windows and Linux Mint. I found that Fancy Fog is available for AMD on Linux. Is it just because it's Linux that this "solution" can't be ported to Windows?

**Comment by yezhiyi9670** [comment]
> > Radial fog on AMD/Intel can only be added with shaders.
> 
> Hey @sp614x. I have two systems on my AMD device: Windows and Linux Mint. I found that Fancy Fog is available for AMD on Linux. Is it just because it's Linux that this "solution" can't be ported to Windows?

Linux has the native support for `gl_NV_fog_distance` (which Minecraft uses) with Intel/AMD cards while Windows does not. It's because on Linux the devices are handled by the system instead of Intel/AMD's drivers. [See here](https://feedback.wildfiregames.com/report/opengl/feature/GL_NV_fog_distance).

@sp614x says this is impossible simply because he doesn't want to do it, thinking shaders are a perfect solution of it (while they aren't). This should be able to be done within half an hour and the mods Sodium and Canvas Renderer have already done it (however they both forgot the clouds and skybox).

**Comment by Cjnator38** [comment]
Seems like a really odd issue. On Windows, fancy fog doesn't work at all, but on Linux with the open source OpenGL/Mesa drivers it works perfectly.

**Comment by sp614x** [comment]
Simple shaderpack that enables fancy fog: [RadialFog.zip](https://github.com/sp614x/optifine/files/5996195/RadialFog.zip)

**Comment by AppuCodes** [comment]
Thank

> Simple shaderpack that enables fancy fog: [RadialFog.zip](https://github.com/sp614x/optifine/files/5996195/RadialFog.zip)

Thank you!!
