### ISSUE TITLE
Optifine Cape Issue

### ISSUE THREAD

**Issue by cinnahun** [sp614x/optifine#4734]
My friend accidentally moved his cape to my account and I tried to give it back but it won't work. It keeps saying that his username is invalid. Is there any way you could fix this?

**Comment by Cart3r1234** [comment]
Read the announcements channel in the discord, the Mojang API is down

**Comment by cinnahun** [comment]
What discord?

**Comment by Cart3r1234** [comment]
the optifine discord, they have a post about the issue in the announcements channel, and will post a message when it is fixed there as well

**Comment by splatboy20081** [comment]
https://discord.gg/OptiFine <-- discord link

**Comment by sp614x** [comment]
The website uses the Mojang API to verify the MC usernames.
In the last days the Mojang API have been down several times.
Now it seems to work.
