### ISSUE TITLE
[1.16.2] World fails to load and occasionally crashes with Optifine

### ISSUE THREAD

**Issue by SteampunkSquid** [sp614x/optifine#4737]
Every time I try to open my worlds with Optifine, it loads to 100% and either freezes, or outright crashes. The crash pop-up says
"The game crashed whilst unexpected error
Error: java.lang.IllegalStateException: Lock is no longer valid
Exit Code: -1"
and the full crash report is here: https://pastebin.com/e9b09Wym
I've been having this issue since I believe pre2, but each time there was a way to "fix" it. Before, only some of my worlds would crash, and I could fix it by simply loading a different world, exiting, then trying the crash prone world. Every time I closed and reopened Minecraft, the worlds would crash again, however.
Now it seems that none of my worlds will load with Optifine.

Optifine version 1.16.2-Optifine_HD_U_G3
No other mods are installed, nor am I using shaders or texture packs
This bug does not occur in vanilla Minecraft

**Comment by LuckyOwl1105** [comment]
I've been having this problem for a couple of months now.

**Comment by KaiAF** [comment]
Seems to be related to #4996. This issue has been reported a few times, and little to no fixes have been found, unfortunately.
