### ISSUE TITLE
game crashes 1.7.10

### ISSUE THREAD

**Issue by KiraLinux** [sp614x/optifine#474]
[crash-2017-02-07_10.48.07-client.txt](http://pastebin.com/Cx6d7wiD)

**Comment by sp614x** [comment]
Can you post the game output, it should show the real problem.

**Comment by KiraLinux** [comment]
how to do it?
I understand very little English

**Comment by sp614x** [comment]
In the minecraft launcher:
1. Click on Edit Profile
2. Set "Launcher visibility" to "Keep the launcher open"
3. When the game starts the game output is shown in the tab "Game Output"

The game output is also saved in the file ".minecraft/logs/latest.log"
To find it, in the launcher:
1. Click on Edit Profile
2. Click on "Open Game Dir"
3. Go to "logs" and open "latest.log"

**Comment by KiraLinux** [comment]
[fml-client-2.log.txt](https://github.com/sp614x/optifine/files/757495/fml-client-2.log.txt)

**Comment by sp614x** [comment]
This is the problem: http://pastebin.com/hcUtJJLp

**Comment by sp614x** [comment]
You can try to:
  A. Set Chunk Loading to Default
  B. Disable Shaders

Also EnderIO is complaining about incompatible APIs:
```
  EnderIO: Found the following problem(s) with your installation:
   * Optifine is installed. This is NOT supported.
   * An unknown AE2 API is installed (rv3 from appliedenergistics2-rv3-beta-6.jar).
     Ender IO was build against API version rv2 and may or may not work with a newer version.
   * An unsupportted old RF API is installed (1.7.10R1.0.0 from funky-locomotion-1.7.10-beta-7.jar).
     Ender IO needs at least 1.7.10R1.0.2 and will NOT work with older versions.
  This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
```

**Comment by KiraLinux** [comment]
Ok, i will try
