### ISSUE TITLE
Glass not rendering water properly

### ISSUE THREAD

**Issue by Edoggiedog** [sp614x/optifine#4743]
When looking through glass water doesn't render properly
Looking through glass/glass panes and facing North and only North causes water to not appear. Looking around the glass or looking at glass from the other side will not produce the glitch.
I'm on OptiFine version 1.16.2-OptiFine_HD_U_G3
I installed using the download.

![2020-08-30_20 33 21](https://user-images.githubusercontent.com/70493892/91673052-11d63600-eb00-11ea-8e3f-19877cc4db41.png)

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
No
- Does this happen without any mods at all?
no
- Does this happen in OptiFine standalone?
Yes
- Does this happen in Vanilla without OptiFine?
No
- Have you tried using a binary search to find which mods cause this issue?
No

When troubleshooting I tried going to other places in the world, reloading the game, turning shaders on and off, and was able to recreate this a different world

**Comment by Regnander** [comment]
This sounds like #4504, which was fixed in an earlier version. 😕
