### ISSUE TITLE
[Bug] Torch not emitting light in off-hand

### ISSUE THREAD

**Issue by mickyyman** [sp614x/optifine#4752]
## Description of Issue
The torch doesn't seem to be emitting light anymore, only when placed.
My apologies if this was already reported, but I really couldn't find anything.

## Steps to Reproduce
1. Dig down.
2. Grab a torch and put it on offhand.

## OptiFine Version
OptiFine 1.16.2 HD U G3

## Installation Method
Standalone installer on a fresh minecraft installation.

## F3 Debug Screenshot
[Image](https://i.imgur.com/ZtGvEAn.png)

**Comment by Jorkles** [comment]
Do you have dynamic lights on?

**Comment by mickyyman** [comment]
> Do you have dynamic lights on?

I did not. Turned it on, and voila.

Thanks :P 

Case closed.
