### ISSUE TITLE
Lava CTM Not Working

### ISSUE THREAD

**Issue by zcorcoran** [sp614x/optifine#476]
I'm not sure if this qualifies as a bug or a feature request, but CTM for Lava doesn't appear to be working. I'm using OptiFine 1.10.2 HD U D6

The resource pack for reference: https://dl.dropboxusercontent.com/u/13396372/Painterly%20-%20SHEOL.zip

This is the .properties file I'm using for lava:

```
#Flowing Lava
method=fixed
matchTiles=lava_flow
tiles=2
biomes=Hell

#Lava Still
method=fixed
matchTiles=lava_still
tiles=1
biomes=Hell
```

I've also tried .properties files for each block individually (block10 and block11) without using matchTiles, and that doesn't work either, nor does matchBlocks=lava/matchBlocks=flowing_lava

Other biome-specific blocks (non-fluids) are working just fine.

The last time I tried this was with MCPatcher in 1.7.10, and it worked then, so I'm not sure if this is something OF doesn't do yet (although nothing related seems to be on the todo list), if it's a bug, or if there's something else going on.

**Comment by zcorcoran** [comment]
I forgot to mention that I am running Forge, but can confirm that this happens both with other mods and with just Forge and OF.

**Comment by sp614x** [comment]
CTM is currently not working for fluids (water, lava).

**Comment by zcorcoran** [comment]
I thought that might be the case, but couldn't find any similar issues or official word on it, so I wasn't sure. Thanks for letting me know!
