### ISSUE TITLE
1.16.2 Custom Biome Detection

### ISSUE THREAD

**Issue by SkaliberWasTaken** [sp614x/optifine#4761]
![2020-09-02_13 50 54](https://user-images.githubusercontent.com/50083260/91984338-1418da00-ed24-11ea-962d-4f84a46d75f6.png)
While using the new 1.16.2 world generation, I ran into an issue where custom biomes would use an unknown column within the grid formatted colourmap. The image below is of the colourmap I was previously using, where I had black blank space where columns weren't being used.

My assumption, is that the custom biomes are using the first available column, or a random column based on their parameters. The issue is however, if you're using multiple, or simply different World Generation Datapacks, 2 completely different biomes could easily use the same column, or even end up exceeding the 256 biomes that could be specified in the grid colourmap.

**Grid Format Colourmap:**
![image](https://user-images.githubusercontent.com/50083260/91985711-6eb23600-ed24-11ea-9b41-10286ea415a0.png)

**Potential Fix:**
![image](https://user-images.githubusercontent.com/50083260/91986609-d072a000-ed24-11ea-9606-0c012ce4f83d.png)
As seen in the above image, you can simply fill in the black space with a colour (a "neutral" colour in a working example) and any custom biomes will use a column of that colour.

The unfortunate downside for this fix, is that this will now affect all custom biomes, that could be in the nether, end, and overworld. In order to give us maximum control, I propose that a new method of specifying custom biomes is added.

![image](https://user-images.githubusercontent.com/50083260/91987476-019fa000-ed26-11ea-8540-2a0ece793fd7.png)
Given that we already have optifine/colormap/custom, I feel as though we could have a new sub-folder which could be used for specifying individual biomes.

For example, within this folder, we'd have a single splice of a grid colourmap (a 1x256 image) with an accompanying .properties file, with the following contents:

```
biome=starmute:crimson_forest_s
blocks=netherrack
```

As shown in the images above, a really easy fix for the time being is to make sure that grid type colourmaps simply have their blank spaced filled in with a neutral colour, so that all biome based colours would be "neutral", but this alternate way of specifying individual unique biomes (without using their dynamic numerical ID) would allow us for more control over new custom biomes.

**Comment by StrideyGH** [comment]
please and thank you

**Comment by sixfootblue** [comment]
Would definitely love a fix or workaround for this to be implemented. This would also prevent custom colormaps from interfering with new biomes that are added with mods.

**Comment by SkaliberWasTaken** [comment]
This might be worth addressing when 1.17 comes out, as colourmaps will need to change to fit the new dynamic world height. Will re-open as part of a colourmap specific megathread,
