### ISSUE TITLE
[Bug - 1.16.2 Multiplayer] Custom dimentions/biomes seem to be crashing the game.

### ISSUE THREAD

**Issue by StackDoubleFlow** [sp614x/optifine#4769]
## Description of Issue
Joining a server utilizing Minecraft's new ability to make custom dimensions/biomes in 1.16.2 seems to crash the client when running OptiFine. Vanilla seems to handle it just fine. The issue seems to happen on a variety of different hardware and operating systems.

## Steps to Reproduce
1. Start the game
2. Try joining the server
3. Crash

## OptiFine Version
1.16.2-OptiFine_HD_U_G3_pre4

## Installation Method
Standalone Installer

## Log Files/Crash Reports
[Crash Report](https://hb.stackdoubleflow.net/rowutimemu)
[latest.log](https://github.com/sp614x/optifine/files/5171914/latest.log)

## F3 Debug Screenshot
Crashes before I'm able.

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
No

## Additional Information
[Source code of the server](https://github.com/MCHPR/MCHPRS)
I am the maintainer of the project and my users have complained about not being able to use OptiFine. If you'd like to test joining the server but want to skip the hassle of spinning one up, you can message me on discord @StackDoubleFlow#7833 and I can give you access to my test server. Please be sure to let me know if any information is needed or there is some way I can help, and thanks for all the great work you're doing!

**Comment by chaosophy** [comment]
_pre4 is outdated, try the release version of OF.  

May or may not help but you should probably be on the latest one for support.

**Comment by StackDoubleFlow** [comment]
Just tested latest release(OptiFine_1.16.2_HD_U_G3); still crashing with same report.

**Comment by luciobortoletto** [comment]
The same thing happens to me
