### ISSUE TITLE
[Bug Report] Resourcepack texture file test.png.mcmeta Stop working when using Optifine

### ISSUE THREAD

**Issue by benzkungx10** [sp614x/optifine#4774]
version OptiFine 1.16.2 HD U G3 pre4

example using Optifine
https://imgur.com/sh1FjFV

example Vanilla 1.16.2
https://imgur.com/EUAFxCb

**Comment by Regnander** [comment]
Can you upload your resource pack with only the necessary files so we can reproduce the bug and see what's wrong?

**Comment by KaiAF** [comment]
If you are still having this issue, please create a new ticket
