### ISSUE TITLE
[Category] Allow float in #if and #elif

### ISSUE THREAD

**Issue by Luracasmus** [sp614x/optifine#4776]
## Description of the new feature
`#if` and `#elif` preprocessor directives currently only allow `int` values.
Please add support for `float` values too

**Comment by sp614x** [comment]
According to GLSL Language Specification v4.20, page 16:
```
Expressions following #if and #elif are further restricted to expressions operating on literal integer constants
```
https://www.khronos.org/registry/OpenGL/specs/gl/GLSLangSpec.4.20.pdf

**Comment by Luracasmus** [comment]
Ok, thanks
