### ISSUE TITLE
Bee Custom Entity Model

### ISSUE THREAD

**Issue by CynicalZombie** [sp614x/optifine#4778]
I'm currently getting into custom entity models, experimenting with various mobs. The one that doesn't work at all is bees. I tried naming the .jem file "bee", "bees", putting it into a subfolder named "bee", but without any success. Then I took a look at the documentation to see what the error was and as it turns out, bees aren't even listed for cem despite seemingly every other entity present. So this appears to be an overlooked mob and thus missing feature.

**Comment by ZenithRogue** [comment]
Bee CEM is not currently supported. For a current list of all supported CEM entities, check out #4781

**Comment by CynicalZombie** [comment]
> Bee CEM is not currently supported. For a current list of all supported CEM entities, check out #4781

Well yes, that's exactly why I made the suggestion to add it. An answer among the likes of "we'll look into adding it" or "we decided against it" would be more appreciated than just closing the topic without any info.

**Comment by ZenithRogue** [comment]
First off, this issue was not formatted like a suggestion
Second, the issue was closed to eliminate clutter of duplicate issues
And finally, it is unclear when/if this entity will be supported. (I am still waiting on it myself ☺️)
