### ISSUE TITLE
[Help wanted] Chicken CEM

### ISSUE THREAD

**Issue by SLimeyMC** [sp614x/optifine#4779]
## Descriptions
So when I try to make a custom entity model (more like animation but yeah) and changing a chicken model. But when I am done rigging and load it into Resource pack it is bugged. I don't know what caused this but there an image.

## Steps to Reproduce
1. Make chicken models.
2. Put it on cem folder also the textures.
3. Load it on Minecraft.

## OptiFine Version
Optifine 1.16.2 HD G3

## Installation Method
Standalone

## Log Files/Crash Reports
[2020-09-06-3.log](https://github.com/sp614x/optifine/files/5179694/2020-09-06-3.log)

**DO NOT directly copy and paste log contents here on GitHub.**

## F3 Debug Screenshot
![herelel](https://cdn.discordapp.com/attachments/689131011484942338/752158319317352458/2020-09-06_20.26.43.png)

## Additional Information
Here a cem file: 

[<img src="https://discord.com/assets/985ea67d2edab4424c62009886f12e44.svg" width="40"/>](https://cdn.discordapp.com/attachments/689131011484942338/752160336483975219/chicken.jem)

**Comment by ZenithRogue** [comment]
If you want some help with CEM, check out the [#help-optifine](https://discord.gg/fZQbxbg) channel in the blockbench discord server: https://discord.gg/fZQbxbg

**Comment by SLimeyMC** [comment]
Tehnically i am on that server but thank you!

**Comment by ZenithRogue** [comment]
Heyo, just checking in. Did you ever solve this issue?
