### ISSUE TITLE
[CEM] CEM missing for Striders and Hoglins

### ISSUE THREAD

**Issue by ewanhowell5195** [sp614x/optifine#4781]
There is currently no CEM for Striders and Hoglins.

Other missing entities include:

arrow
bee
bell
chest_minecart
command_block_minecart
elder_guardian
elytra
furnace_minecart
hopper_minecart
llama_carpet
llama_spit
shield
spectral_arrow
trader_llama
trident
wandering_trader
zoglin

**Comment by ItsChawk** [comment]
Elder Guardian Entity Model! We have the Guardian model but not the elder? thats like giving me a cheese burger without the cheese! also give me bees! sweet little bees!

**Comment by ewanhowell5195** [comment]
added
