### ISSUE TITLE
[CPM] more detailed infos about initialization

### ISSUE THREAD

**Issue by heinrich26** [sp614x/optifine#4785]
You might know these launchers using Java jars used by small servers...
they dont have a launcher-profiles.json and stuff like that, so the optifine jav args cannot be read from there. (i think thats how its working).
So now I ask myself the question, how do I do this then? Am I right with the Launcher-Profiles.json and I just need to create one and optifine is fine or is there another workarround?

Hope to get some tipps ;=)

**Comment by sp614x** [comment]
What is CPM and what exactly is the question?

**Comment by heinrich26** [comment]
CPM CustomPlayerModels, that feature u can use to modify someones playermodel, which needs activation over JVM Arguments. I want to use ist on 1.12.2 with an external Launcher, so I need to know where optifine takes that JVM Argument from

**Comment by KaiAF** [comment]
Seems to be addressed here already: #4726.
