### ISSUE TITLE
[Documentation] No hoglin model in cem_model.txt

### ISSUE THREAD

**Issue by RandomAnnoyingGuy** [sp614x/optifine#4795]
You somehow put piglins here but forgot hoglin, i have been waiting for this for a while now :(

**Comment by ZenithRogue** [comment]
They weren't forgotten. Piglins are Zombified Piglins were just quick and easy to add. Hopefully we will get Hoglins and Zoglins soon.

For a full list of incompatible 1.15/16 mobs, check out #4781
