### ISSUE TITLE
[Bug] Local Singleplayer World Not Loading when changing to a Optifine version that is not from 1.16.2 HD U G3 pre4

### ISSUE THREAD

**Issue by CiberTurtle** [sp614x/optifine#4800]
## Description of Issue
Singleplayer world doesn't load it's chunks an the integrated server appears to crash.

- Chunks don't load
- Chunk Bounds are not centered on the player and instead seam to be at `0 0`
- `Waiting for chunk...` appears in the F3 menu
- Integrated Sever TPS appears to crash
- When movement keys are pressed players XYZ position doesn't change
- The player's hand is not oriented with the camera and instead is at player's feet and not rotating with the camera.
- World doesn't Save when Quitting out of the world and instead you have to manual end the Minecraft process

## Steps to Reproduce
When updating from OptiFine version `1.16.2 HD U G3 pre4` to OptFine `1.16.3 HD U G3 pre2` or `OptiFine 1.16.2 HD U G3`.

## OptiFine Version
(Initial World Creation) `OptiFine 1.16.2 HD U G3 pre4`
(Versions being updated to)   `OptiFine 1.16.3 HD U G3 pre2` and  `OptiFine 1.16.2 HD U G3`

## Installation Method
The OptiFine installer from the [official OptiFine website](https://optifine.net/downloads) using the mirror link.

### Data Packs
(All from [https://vanillatweaks.net](https://vanillatweaks.net))
```
afk display v1.1.0
anti creeper grief v1.1.0
anti enderman grief v1.1.0
anti ghast grief v1.1.0
armored elytra v1.0.3
cauldron concrete v2.0.3
coordinates hud v1.2.0
count mob deaths v1.1.0
double shulker shells v1.3.0
dragon drops v1.3.0
durability ping v1.1.0
fast leaf decay v2.0.3
more mob heads v2.8.1
multiplayer sleep v2.4.0
player head drops v1.1.0
silence mobs v1.1.0
spectator conduit power v1.1.0
spectator night vision v1.1.0
unlock all recipes v2.0.0
villager death messages v1.2.1
villager workstation highlights v1.1.0
wandering trades v1.4.0
```

## Log Files/Crash Reports

[2020-09-12-7.log](https://github.com/sp614x/optifine/files/5212914/2020-09-12-7.log)

## F3 Debug Screenshot
![Screenshot](https://i.imgur.com/MLEe3qU.png)

## Prior Testing
The world seams to load, play and save perfectly fine in Vanilla Minecraft but Updating to a different OptiFine version results in these problems.

- Optimizing the world with `Delete Cache` enabled doesn't solve the problem
- Teleporting to different locations doesn't solve the problem
- Reloading chunks doesn't solve the problem

**Comment by Ecdragonz** [comment]
I'm attempting to isolate the issue, I believe it it is caused by one of the vanilla tweaks datapacks. Running further testing as this is really starting to frustrate me

**Comment by Ecdragonz** [comment]
Upon testing every pack, its not vanilla tweaks. something in the world is mildly broken for both you and me. I don't know what it is

**Comment by Xaenot** [comment]
Same issue here. It's 100% a VanillaTweaks datapack. Tomorrow i'll test one by one.
I did create a new world with 20 datapacks from VanillaTweaks (craft tweak also) and same issue, stucked in 100% or loading slow chunks, textures, etc.

**Comment by CiberTurtle** [comment]
I have tried deleting all the datapacks from the world, it still has the same errors.

**Comment by Xaenot** [comment]
Yeah, your world stays "damaged" i think. You can make a test world put all the datapacks except the elytra one, play around a little bit, then install the elytra dapack, wait for all the chunks to load, log out, delete the datapack and you'll see that the world will take a long time to load even with the datapack disabled.

**Comment by agentpaint** [comment]
I think I found a way to fix the world staying "damaged" after uninstalling the datapack. The Armored Elytra and the Cauldron Concrete datapack both make use of the "forceload" command, which as the name implies, forces a chunk to stay loaded at all times. For some odd reason, the uninstallation function, while it has a command that is supposed to stop the chunks from being loaded, does not seem to run. So if you are able to load into your world, try typing in the command:

> "/forceload query" first, to check if there are any chunks being forceloaded (typically they are very far away, into the 10000+ coords)

Then type

> "/forceload remove all" to unmark the chunks from being forceloaded.

After I did this in a singleplayer version of my server world, which uses a lot of vanillatweaks datapacks, the chunks loading were back to normal, although I cannot guarantee that this method will work for everyone.

Regardless it's still a bug that SP should try to fix since this behavior doesn't happen in Vanilla and I'm sure there are people who want to use Armored Elytra or similar datapacks.

**Comment by Xaenot** [comment]
Yup, you're right!
Now it takes just 4-5 seconds to open the world AND load the chunks. That's the fix!

![optifine-forceload](https://user-images.githubusercontent.com/58130260/95667258-16dbcb80-0b29-11eb-92d7-d722638acd1a.png)

**Comment by CiberTurtle** [comment]
Thanks! This fixed my world!
There was some bad performance at the start, the world but optimizing the world seamed to solve the problem.

**Comment by Xaenot** [comment]
Here's the official thread from Grant (VanillaTweaks): https://github.com/sp614x/optifine/issues/4832

Btw, after i did the forceload commands, it keeps happening, we have to disable all datapacks that forceload a chunk.
