### ISSUE TITLE
[Bug] Banner item GUI lighting is broken for 1.16.2+

### ISSUE THREAD

**Issue by jaylawl** [sp614x/optifine#4806]
## Description of Issue
Banners are being lit incorrectly; see this screenshot: https://i.gyazo.com/1a5300cf7c9c8c25f02719c5ee7c1e46.png

## Steps to Reproduce
1. Open the creative inventory and look at banners

## OptiFine Version
1.16.3-OptiFine-HD_U_G3_pre2
this is also present in the latest OptiFine release for 1.16.2

## Installation Method
Installed with the executable jar from OptiFine.net

## Other Installed Mods
No other mods

## F3 Debug Screenshot
https://i.gyazo.com/ad81011071e253ac716954647a38795b.png

## Additional Information
I have tested to make sure that this is not caused by resource packs. There is nothing else that i could imagine would influence this. And apart from that im only on vanilla minecraft anyway.

**Comment by Francy-chan** [comment]
It's a vanilla bug, see [MC-196500](https://bugs.mojang.com/browse/MC-196500).

**Comment by jaylawl** [comment]
> 
> 
> It's a vanilla bug, see [MC-196500](https://bugs.mojang.com/browse/MC-196500).

My bad, thank you for clarifying.

Closing
