### ISSUE TITLE
[Optifine 1.8.9 and 1.12.2 Crash] idk why tho

### ISSUE THREAD

**Issue by Buttercomb** [sp614x/optifine#4809]
I have been trying to find every conceivable solution to this, old animation fixes, redownloading my launcher, and deleting all my versions and mods; and it still won't work!!! 1.16's Optifine and 1.14 works perfectly but the others won't! Yes, I am using Tlauncher cause I'm broke but there seems to be no difference between the technical issues. I even logged in with an alt on my official MC launcher and it still won't work... 

I am on a macOS and I copy-pasted the error to a .txt from the dev console; all the clutter in the crash-report and logs folder is killing me. I hope this helps.
[Optifine-Crash.txt](https://github.com/sp614x/optifine/files/5215579/Optifine-Crash.txt)

I have asked some people in the shaderlabs discord group, and there seemed to be an error "NSInternalInconsistencyException" that replaces the Win 10 error message... 
 
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow drag regions should only be invalidated on the Main Thread!'

**Comment by dscalzi** [comment]
Caused by https://github.com/sp614x/optifine/issues/4824
