### ISSUE TITLE
[Exrtra lag] gameRenderer rendering finish

### ISSUE THREAD

**Issue by Finnegan16** [sp614x/optifine#4812]
## Description of Issue
With optifine I normally run just fine, but one day it was just at 0 fps, and didn't go up, I went to vanilla 1.16.3, and it ran just fine, so I know it's something wrong with either my pc or optifine.

## Steps to Reproduce
1. This I'm not sure about, one day I logged on and I was just at 1 fps

## OptiFine Version
1.16.2-Optifine_HD_U_G3

## Installation Method
I went to optifine.net and when it downloaded I just installed it to minecraft

## Log Files/Crash Reports
No crash, just 0 fps

## F3 Debug Screenshot
![image](https://user-images.githubusercontent.com/71274598/93101006-c7b09100-f677-11ea-96c2-8e9ab63b0b49.png)

## Additional Information
Here goes any final remarks and everything else that might not fit in the previous sections.
Here's a picture of the pie graph as far as it goes:
![image](https://user-images.githubusercontent.com/71274598/93101616-7ead0c80-f678-11ea-9a08-6a24063a81a9.png)

**Comment by Finnegan16** [comment]
If any more info is needed let me know (I have no other mods and installed it directly to minecraft, so optifine is one of the launchers

**Comment by sp614x** [comment]
Set Performance -> Smooth FPS to OFF.
The Intel graphics may have problems with it.
