### ISSUE TITLE
Memory Leak. Optifine using all ram.

### ISSUE THREAD

**Issue by 7ym3** [sp614x/optifine#4815]
## Steps to Reproduce
1. set jvm arguments to use half your installed ram.
2. Open your game.

## OptiFine Version
1.16.2 HD U g3, but this also happens on other versions of optifine.

## Installation Method
I used the standalone installer.

## Other Installed Mods
I have Seus ptgi hrr shaders on. This does not affect the ram usage though because even when I take it off the ram usage stays the same. The ram usage even happens in the menu screen.

## F3 Debug Screenshot
https://imgur.com/1UuTet1

## Prior Testing
If you've installed standalone:
This does not happen in vanilla.

**Comment by Vrael0n** [comment]
I'm also getting this leak. I have it set to 8GB and It's using 16.5GB. But I'm using the latest Forge, not standalone.

**Comment by 7ym3** [comment]
> I'm also getting this leak. I have it set to 8GB and It's using 16.5GB. But I'm using the latest Forge, not standalone.

odd... If you find any fixes let me know!

**Comment by guestds** [comment]
im having the same issue, allocated 3 gb 

i had the same issue whether using optifabric or just optifine (installed through itself) 

theres no noticeable effect when on multiplayer, but in singleplayer, the world will not load at all unless im in the spawn chunks 

i set chunk updates to 1 and it seems to have helped, but after a certain amount of time the tps freezes, chunk loading still worked visually, though in the spawn chunks and i was at 2 render distance 

if i try save and quit, it gets stuck on saving world

**Comment by sp614x** [comment]
The maximum RAM setting controls the amount of heap memory that the Java program can use.
Additionally the JVM may allocate approximately the same amount of RAM for other purposes: JVM runtime, GC, native buffers, etc.
Minecraft is loading textures and terrain vertex data in native buffers which are not part of the heap memory.
Using twice as much RAM as configured is normal for MC.

**Comment by sp614x** [comment]
Giving more RAM to Minecraft is not going to make it run faster or smoother.
Usually 1-2 GB for vanilla and 3-4 GB for big modpacks is optimal.

**Comment by guestds** [comment]
i did some testing with just 1.16.1 G2 and it worked, changed back to only 1.16.2 G3, for some reason the chunkloading issue (loading into the world while outside of the spawnchunks) and the memory issue seems to be gone

i should also reword what i said above, maximum allocation is 3gb, initial allocation is 512MB


i dont actually know why its working now, the only change seems to be swapping to G2 and then back to G3, as well as the launcher updating for me, but im not sure what those would change 

even optifabric works and im not sure why

**Comment by jmdev91** [comment]
Not sure if it's the exact same issue or a new one, but in version 1.16.5 HD G7 Ultra under Forge if I turn off Render Regions the game hangs and uses up all 24GB of installed ram (I have Minecraft set to use 8GB). I did recently add some command line options to reduce garbage collection lag, specifically "-XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M". I wouldn't be surprised if that's the main cause, but other options result in a fresh VBO (I'm guessing that's what it is, quicker than loading chunks from file but they pop in one-by-one) and don't cause this issue.
