### ISSUE TITLE
[CEM] Mule models not changing for cem

### ISSUE THREAD

**Issue by BlevinsTyler** [sp614x/optifine#4818]
## Description of Issue
The mule model is not loading, other custom models are loading

## Steps to Reproduce
1. I created a .jem file to change the model of the mule along with a texture change
2. I saved them both in .minecraft\resourcepacks\Test_Resource_Pack\assets\minecraft\optifine\cem
3. I reloaded the texture pack and the mule model and texture did not change

## OptiFine Version
1.16.2 

## Installation Method
I did the normal installer?

## Log Files/Crash Reports
![2020-09-14_20 35 20](https://user-images.githubusercontent.com/71296972/93159027-91503180-f6ca-11ea-8c4f-59c8af63bb81.png)

on the left, a custom model loaded correctly, on the right the mule's model and texture did not change at all

![image](https://user-images.githubusercontent.com/71296972/93159275-16d3e180-f6cb-11ea-9ab2-fedb3e6e0afa.png)

what the model should look like

## F3 Debug Screenshot
![2020-09-14_20 42 00](https://user-images.githubusercontent.com/71296972/93159130-c492c080-f6ca-11ea-8489-63f38b4034cd.png)

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
NA

## Additional Information
I used block bench and a block bench plugin called "CEM template loader"

**Comment by backAir** [comment]
did you manage to fix your problem ? I have the same problem

**Comment by niewiemwad** [comment]
the ".jem" file needs to have the same name as the mob you are changing.

**Comment by ewanhowell5195** [comment]
mule cem works fine now
