### ISSUE TITLE
latest Optifine using outdated launchwrapper

### ISSUE THREAD

**Issue by IsaiahPatton** [sp614x/optifine#482]
Optifine 1.11.2 uses Mojang's launchwrapper version 1.7 when the latest version is 1.12

because of this Optifine misses the commits:
https://github.com/Mojang/LegacyLauncher/commit/9b583972acf11090e2df84ef242c84956515ee0b
https://github.com/Mojang/LegacyLauncher/commit/da7b564c26e8b5834ae53f17177c10fe34047365
https://github.com/Mojang/LegacyLauncher/commit/b829d6f5697f4590c40be0596a998d285575cb94
https://github.com/Mojang/LegacyLauncher/commit/12bb371e6875a30c4475edf0ae45454b261c2e89
https://github.com/Mojang/LegacyLauncher/commit/46401b94ac6035b426dfa41cbe2029ab5a93c2b2
https://github.com/Mojang/LegacyLauncher/commit/bc443e2cf9e2b4aa6246998d483597a4afe667d7
https://github.com/Mojang/LegacyLauncher/commit/03cbf02cd689b45c5535d20b3f9a8a1d10661d17
https://github.com/Mojang/LegacyLauncher/commit/80d792e217abee096b8428828c112917e18a3692
https://github.com/Mojang/LegacyLauncher/commit/489b2bd23be7d6865770cf1371febfd04eaa964b
https://github.com/Mojang/LegacyLauncher/commit/2abc4a777c03d69c815cd40430b1d3580511f68a

**Comment by sp614x** [comment]
Updated preview C1 for 1.11.2
 - updated installer to use launchwrapper 1.12
