### ISSUE TITLE
Fishing Rod animations do not play when in third person

### ISSUE THREAD

**Issue by MotorGorilla1** [sp614x/optifine#4823]
## Description of Issue
In the most recent preview, fishing rod animations were fixed, but only for first person mode. If I were to press f5 and cast a fishing rod, the custom cit texture would not appear, instead it would just default to the vanilla cast fishing rod. If I were to press f5 again to go into the front view of third person and then cast my rod, the same thing would happen.

## Steps to Reproduce
1. Press f5 either once or twice if you are currently in first person
2. Cast a fishing rod with a custom item texture

## OptiFine Version
**OptiFine 1.8.9 HD U L6 pre1**
## Installation Method
**I extracted OptiFine 1.8.9 HD U L6 pre1 into the mods folder of the most recent forge**

## Fabric/Forge Version
**Forge 1.8.9 - 11.15.1.2318**

## Other Installed Mods
**NotEnoughUpdates-1.3.1-REL
SkyblockAddons-1.5.2-for-MC-1.8.9**

**If OptiFine is installed as standalone, remove this section.**

## Log Files/Crash Reports
No crash log as this bug is not a crash

## Prior Testing
If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   - Only OptiFine and Forge **Yes**
   - Only OptiFine, OptiFabric, and Fabric **Wasn't using fabric at all**
- Does this happen without any mods at all?
   - Only Forge/Fabric by itself. **Yes**
- Does this happen in OptiFine standalone? **Yes**
- Does this happen in Vanilla without OptiFine? **No**
- Have you tried using a binary search to find which mods cause this issue?
   - To find conflicting mods, split your mods into 2 groups (not including OptiFine/OptiFabric, obviously). Remove one group, and test in-game. Keep the group that has the problem, and repeat until no more mods can be removed without the issue disappearing.
   - Does the issue still happen with only the remaining mods installed?
      - Forge/Fabric and remaining mods, without OptiFine **The issue is exclusive to optifine as it uses optifine's CIT feature**

## Additional Information
I have linked a video of me testing out the fishing rod in 3rd person views, you can ignore the bow shot at the end as I was testing out that fix as well, but I haven't tested if bows have the same issue when it comes to f5.
https://streamable.com/bsw1nz

**Comment by IRONM00N** [comment]
Would be nice if fixed

**Comment by IRONM00N** [comment]
The enchantment glint also disappears in third person.
