### ISSUE TITLE
[SEVERE] [Bug] The `/forceload` command loads a 69x69 area of chunks instead of 5x5 as in vanilla

### ISSUE THREAD

**Issue by GrantGryczan** [sp614x/optifine#4832]
## Description of Issue
In vanilla, `/forceload add` will only load a single chunk with ticket level 31, the single ring of chunks around that with 32, the ring around that with 33, and so on. [More info about the details of how forceloaded chunks work on the wiki.](https://minecraft.gamepedia.com/Chunk#Forced_ticket)
In OptiFine, `/forceload add` will load all the chunks in a 67x67 area centered at the forceloaded position with ticket level 32 or less, the ring around that area with level 33, and so on.
It should be obvious why this is a severe issue. If anyone has data packs installed on their world using `/forceload` to load a number of chunks far apart, that's an enormous amount of loaded chunks. **I've had a number of reports from people using my data packs saying their world is unjoinable from this.** Un-forceloading the chunks or switching to vanilla always fixes it.

## Steps to Reproduce
1. In a singleplayer test world in vanilla, be sure your world spawn is not set anywhere near (10000, 0), no players are anywhere near (10000, 0), and that area is not loaded anyhow else.
2. Run `/setblock 10000 0 0 minecraft:stone`. You will get an error: "That position is not loaded."
3. Run `/forceload add 10000 0` to forceload the chunk at the block coordinates (10000, 0) with ticket level 31.
4. Run `/setblock 10000 0 0 minecraft:stone`. It will _not_ say "That position is not loaded."
5. Run `/setblock 10000 0 32 minecraft:stone`. This is two chunks away from the forceloaded chunk, at ticket level 33. It will be loaded enough to set blocks as well.
6. Run `/setblock 10000 0 48 minecraft:stone`. Three chunks away will _not_ be loaded, because that is ticket level 34 in vanilla, and `/setblock` only works in ticket level 33 and below.
7. Join the world in OptiFine instead. Run `/setblock 10000 0 48 minecraft:stone` again. This time it will _not_ say "That position is not loaded." because OptiFine loads way too many chunks around the forceloaded chunk.
8. 16 times 34 is 544. Run `/setblock 10000 0 544 minecraft:stone`, which is 34 chunks away from the forceloaded chunk. You will see that this position is loaded.
9. 544 plus 16 is 560. Run `/setblock 10000 0 560 minecraft:stone`. This is 35 chunks away. You will see "This position is not loaded." because OptiFine only loads chunks around a forceloaded chunk in a 34 chunk radius. The diameter of the loaded area is thus 1+2*34 = 69 chunks, so the loaded area is 69x69 chunks. That's 4761 loaded chunks, and from only one forceloaded chunk, let alone a number of them spread around the world.

## Possible Explanations
* I didn't look at the source code, but it's possible OptiFine is loading a 3x3 area around each forceloaded chunk with ticket level 0 instead of ticket levels 31 and 32. (Or, if it's possible, perhaps it's loading the single forceloaded chunk with ticket level -1, and then the ring around that becomes level 0.) The ring around that area is then level 1, around that is 2, and so on. That expands 34 chunks outward from the forceloaded chunk to reach level 33, and then 35 chunks outward it reaches level 34. This would explain why `/setblock` works up to 34 chunks away from a forceloaded chunk, because `/setblock` only works in ticket levels 33 and lower.
* Alternatively, perhaps OptiFine just loads the whole 67x67 area around the forceloaded chunk with ticket levels 31 and/or 32. Then the ring around it is 33.

## OptiFine Version
OptiFine 1.16.3 HD U G3
(Also tested on some older 1.16 versions, and from several other people's computers. The issue does not exist earlier than 1.16, though I'm not sure in exactly which 1.16 version it was introduced.)

## Installation Method
Standalone installer

## F3 Debug Screenshot
![2020-09-18_15 03 08](https://user-images.githubusercontent.com/14056899/93635342-1e8fd080-f9c0-11ea-997d-d2ca89994ccc.png)

## Additional Information
* Since OptiFine's Performance Settings have a lot to do with chunks, I figured it was possible that this issue is contingent on those settings, but I could not find any combination of those settings which fixed the issue.
* Also note that the `/setblock` command can say either "Changed the block" or "Could not set the block" if the position being set is loaded. The position being set is loaded as long as the command is valid and it does _not_ say "That position is not loaded."
* It's also worth noting that I know only the outermost ring of the loaded area in OptiFine is ticket level 33 while the inner 67x67 area is level 32 or less, because I have tested by seeing if repeating command blocks run in that area, and repeating command blocks require ticket level 32 or less to run.

**Comment by GrantGryczan** [comment]
@sp614x Sorry for the notification, but could you recognize this please? It's a severe issue that needs to be fixed, and yet it hasn't even been labeled. Lots of data packs are unplayable with OptiFine because of this.

**Comment by ZombeeeePikachu** [comment]
nice

**Comment by sp614x** [comment]
Should be fixed in pre2 for 1.16.4
