### ISSUE TITLE
[1.16.3] Can't turn render quality lower than 1.

### ISSUE THREAD

**Issue by dragon3025** [sp614x/optifine#4834]

**Comment by Deviouslrd** [comment]
Please actually provide the needed info if you want actual help.

**Comment by dragon3025** [comment]
What info do you need? I couldn't think of anything other than that. I guess I could tell you what I did:

There are a couple of shader packs that I was able to go below render quality one in 1.16.2, but with optifine 1.16.3 if I shift click on the render quality button the game freezes for a second like it's loading a new render quality, but it stays at 1.

If I regular click the render quality to make it go up, it goes from 1 to ~1.66 (I don't remember the exact number, but it wasn't a multiple of 5 which is what happens in 1.16.2).

**Comment by dragon3025** [comment]
I just discovered that right clicking will lower it while shift clicking will reset to 1 no mater the size. It didn't work that way previously so I didn't expect that.
