### ISSUE TITLE
Shaders: uniform for night vision

### ISSUE THREAD

**Issue by Builderb0y** [sp614x/optifine#484]
Either the added brightness value, or simply time remaining (preferably the latter, since it allows for more control over how to handle it). Normally, night vision information is stored in the lightmap sampler, but this isn't available in the composite program, where I handle lighting. While gbuffers could theoretically just write this data to one of the gaux buffers, this is annoying and inconvenient. Plus, that sampler doesn't seem to contain useful information in skybasic, so it's not possible to say, make the sky brighter when night vision is enabled.

**Comment by sp614x** [comment]
Should uniforms for blindness and screen brightness (gamma) also be added?

**Comment by sp614x** [comment]
OptiFine 1.11.2_HD_U_B8_pre 
- added shaders uniforms "nightVision", "blindness" and "screenBrightness" 

```
uniform float nightVision;                      night vision (0.0-1.0)
uniform float blindness;                        blindness (0.0-1.0)
uniform float screenBrightness;                 screen brightness (0.0-1.0)
```

**Comment by sp614x** [comment]
The "nightVision" value flickers between 0.4 and 1.0 in the last 10sec.
The "blindness" value fades smooth to 0 in the last second.
The "screenBrightness" is "Video Settings -> Brightness".
