### ISSUE TITLE
[1.16.3] Mod Interaction: Spamming log with "Unknown Biome ID"

### ISSUE THREAD

**Issue by Excederus** [sp614x/optifine#4843]
So I didn't notice that this is an already known issue. This can be closed if wanted I'm just gonna wait for a fix.

## Description of Issue
The log is spammed with 150-200 *thousand* lines of "Unknown Biome ID" when using Oh the Biomes You'll Go together with Optifine.

## Steps to Reproduce
1. Install latest version of Forge, Optifine, Oh the Biomes You'll Go
2. Create a world
3. Watch your latest.log become 20MB

## OptiFine Version
1.16.3 HD_U_G3

## Installation Method
JAR install under Forge

## Fabric/Forge Version
Forge 34.0.9

## Other Installed Mods
Oh the Biomes You'll Go v1.0.5

## Log Files/Crash Reports
Log is 20MB big!!!
[latest.log](https://github.com/sp614x/optifine/files/5263034/latest.log)

## F3 Debug Screenshot
![2020-09-22_19 27 02](https://user-images.githubusercontent.com/29584262/93916311-9dab3e80-fd09-11ea-83c5-e2357dc332f2.png)

## Prior Testing
If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   No
- Does this happen without any mods at all?
   No
- Does this happen in OptiFine standalone?
   No
- Does this happen in Vanilla without OptiFine?
   No
- Have you tried using a binary search to find which mods cause this issue?
   Irrelevant

## Additional Information
I don't know if this is specifically an OptiFine issue. I have also created an issue on Oh the Biomes You'll Go's github.

**Comment by CorgiTaco** [comment]
Also occurs with Biomes O' Plenty

**Comment by Forstride** [comment]
> Also occurs with Biomes O' Plenty

Can confirm, but it only seems to happen when launching Minecraft while OptiFine has a shaderpack selected.  If I disable the shaderpack and restart Minecraft, it seems to work fine again (Although existing worlds with modded biomes will still be screwed up of course).
