### ISSUE TITLE
(Bug Report) Blurry textures of some blocks when far away

### ISSUE THREAD

**Issue by legendaryWalter** [sp614x/optifine#4856]
Blocks such as leaves, grass, vines, cobwebs and other similar blocks become blurry if you are far way from them.

Just was in a plains biome and the grass I looked at from far away became blurry.
To find this, just make sure you have a far view of the blocks said above.

Version: OptiFine_1.16.1_HD_U_G2

I put the file into my mods folder to use with OptiForge.

This also happened in the 1.16.2 and 1.16.3 versions.

**Comment by sp614x** [comment]
Options -> Video Settings -> Quality ->Mipmaps -> 3 or lower.
