### ISSUE TITLE
[Screen tilt] Directional damage tilting effect

### ISSUE THREAD

**Issue by Regnander** [sp614x/optifine#4866]
## Description of the new feature

In the beginning of this month [MC-26678](https://bugs.mojang.com/browse/MC-26678) was closed as "Won't Fix", which was a suggestion to bring back a 1.2.5 feature where the screen tilting effect that occurs when a player takes damage would tilt in a direction based on which direction the player takes damage from.

### Demonstration (½ speed)
Edit: To demonstrate this properly I used the [Ascribe](https://www.curseforge.com/minecraft/mc-mods/ascribe) mod for 1.8.9 which re-adds this functionality.
|Damage taken from the left|Damage taken from the right|
|-|-|
|![w](https://user-images.githubusercontent.com/17113053/95653062-ff371f80-0af5-11eb-8483-bc4403e9df41.gif)|![e](https://user-images.githubusercontent.com/17113053/95653542-c4cf8180-0af9-11eb-8b70-239a5ec5ddcd.gif)

|Damage taken from the front|Damage taken from behind|
|-|-|
|![n](https://user-images.githubusercontent.com/17113053/95653061-fe9e8900-0af5-11eb-9ba1-0114f4aa5ce1.gif)|![s](https://user-images.githubusercontent.com/17113053/95653060-fe05f280-0af5-11eb-93be-c0ed6c295544.gif)

**Comment by SirBobb** [comment]
PLEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASE

**Comment by JimStoneCraft** [comment]
Maybe tilting forward when shot in the back and tilting back when shot from the front.

**Comment by Regnander** [comment]
> Maybe tilting forward when shot in the back and tilting back when shot from the front.

According to the description at [MC-26678](https://bugs.mojang.com/browse/MC-26678), that's how it originally worked. I just wasn't able to produce convincing-looking GIFs of it. 😄

**Comment by KaiAF** [comment]
I think this could be added to optifine. I'm sure you are already aware, but there is this mod that fixes this. https://www.curseforge.com/minecraft/mc-mods/damage-tilt.

**Comment by Regnander** [comment]
Mojang fixed this in [23w03a](https://www.minecraft.net/sv-se/article/minecraft-snapshot-23w03a), so I'm closing this issue.
