### ISSUE TITLE
Enchanted items background with Forge and Vignette Fast

### ISSUE THREAD

**Issue by VoltisArt** [sp614x/optifine#487]
![temp](https://cloud.githubusercontent.com/assets/25761473/22941973/910b9b96-f2b5-11e6-80be-281a5cf309df.png)

I previously posted this on the MineCraft forum, as I wasn't sure what mod was causing it.  I now believe it's OptiFine, as disabling it fixed the icon.  It also, however, killed all the pretty rendering.  :(  I've since updated my OptiFine version, (to B7) with no change to my problem.  The MC Launcher is also updated to 2.0.806.

I'm leaving most of what's below as it was before I narrowed it down.
_ _ _

Have searched several times here [MineCraft forum,] on Google, and on the MC bug tracker. Either this issue isn't common, isn't bothering anyone else very much, or some critical technical word is escaping me in my search strings.

As the attached image shows, the left-most enchanted item in my inventory seems to have its glow unclipped, i.e., no alpha channel. It matters not which slot that first item is in, but it will always be only the closest enchanted item to the left.

I generally use resource packs, but they seem to make no difference, even when all of them are unloaded. None that I use alter the default tool or glimmer images. The effect stays the same in creative or survival modes.

This clearly isn't a debilitating bug, but it is an annoyance. If anyone is able to pin down a likely cause – or better yet, a solution – it would be much appreciated. If there's a shader setting I can edit, rather than disabling a mod altogether, that would be ideal. I really do like all of the mods I use, heh. I've tried flipping through settings within the MC options and haven't found anything that helps.

Currently running:

OS Win10pro x64 1607 build 14393.693
MC Windows/Java 1.11.2, Launcher 1.6.76
Forge 1.11.2-13.20.0.2226
Liteloader 1.11.2-00-SNAPSHOT
OptiFine 1.11.2_HD_U_B5
VillageInfo 1.11-2.1
VoxelMap 1.6.21 for 1.11.2

**Comment by sp614x** [comment]
![image](https://cloud.githubusercontent.com/assets/16635441/22971765/1801f1c4-f377-11e6-8f30-85856292a232.png)
Tested Forge #2226 + OptiFine B7 for 1.11.2, the enchanted items are correct.
Most probably caused by some other mod.

**Comment by VoltisArt** [comment]
![temp-6](https://cloud.githubusercontent.com/assets/25761473/22983992/011d76b8-f372-11e6-8c35-52656067cb3f.png)
I have disabled every other mod and resource pack besides Forge and get no change.  I don't know how it could be another mod, since only removing OptiFine fixes it.

**Comment by sp614x** [comment]
You also have shaders loaded.
Testing Forge #2226 + OptiFine B7 for 1.11.2 + Sildurs Shaders, the enchanted items are still OK.

![image](https://cloud.githubusercontent.com/assets/16635441/22986798/e93e197c-f3ac-11e6-8872-f497ff1e836b.png)

**Comment by VoltisArt** [comment]
Thank you.  Killing antialiasing in the SEUS shader did the trick.  I'll have to browse other shaders and see how they perform.

**Comment by sp614x** [comment]
This seems to be specific to SEUS 11 and all enchanted items are affected:

![image](https://cloud.githubusercontent.com/assets/16635441/22992160/12a178ba-f3bf-11e6-8579-1a2825ea5d97.png)

**Comment by VoltisArt** [comment]
This is weird.  I tried Sildur's and the (internal) sets.  With AA (Antialiasing FXAA 2x or 4x) off, the icon problem goes away, but so does a lot of what makes the render engine a value to me.  Then I tried setting the shader to OFF, and the icon problem comes back regardless of AA.  I'm still only getting the leftmost icon, but the effect is the same as you've shown.

**Comment by VoltisArt** [comment]
SEUS currently removed:
![temp-7](https://cloud.githubusercontent.com/assets/25761473/22992416/a7576e56-f38d-11e6-9526-bbfb664915a6.png)

**Comment by sp614x** [comment]
The problem appears when enablihg FXAA 2x or 4X.

**Comment by sp614x** [comment]
After testing different configurations it looks like the problem is linked to Forge.
When running OptiFine standalone (no Forge), all possible combinations of shader packs and FXAA are working correctly.
When running with Forge #2226 the problem appears immediately even when no shader pack and no FXAA is active. When a shader pack is activated the problem disappears until FXAA is enabled.

**Comment by sp614x** [comment]
The problem only appears when running with Forge, Graphics is set to Fancy and Vignette is set to Fast.
To fix it, set Details -> Vignette to Fancy or Default.

**Comment by sp614x** [comment]
Updated preview B8 for 1.11.2 with a bugfix.
