### ISSUE TITLE
[Bug] Crouching while in inventory

### ISSUE THREAD

**Issue by Lordshaithis** [sp614x/optifine#4875]
I have no idea if this is a bug or not but when i go into my inventory to shift click things into stacks etc, i crouch. Its doing my head in and i dont like it. Is there a way to turn it off? or is it a bug.

Optifine Version: 1.16.3 G4 Preview

I have optiforge installed so ive put it into my mods folder

Forge Version

Other Mods Installed:
Optiforge
Mixinbootstrap
JEI

This issue only happens when optifine is installed forge or not.

**Comment by SyndiShanX** [comment]
That's definitely on your end, I'm using Optifine_1.16.3_G4_pre1 and I don't crouch when shift clicking

**Comment by asbyth** [comment]
are you sure you dont have toggle sneak enabled, thats the only explanation i could think of

**Comment by SmashPortal** [comment]
This is a Forge 34.1.0 bug.
