### ISSUE TITLE
[Question] 1.15.2 version

### ISSUE THREAD

**Issue by riskybisky** [sp614x/optifine#4878]
Hi, 

I have been having an issue with the 1.15.2 version. Usually, what I do is I take the Optifine jar and put it into the mods folder when I'm trying to load optifine and shaders. But when I do this with 1.15, a bunch of textures from the mods I play with don't seem to work. I think someone said Optiforge fixes it but I think it should be part of Optifine dont you?

**Comment by KaiAF** [comment]
Let me know if you are still having this issue. Assuming this was resolved in recent 1.15 versions, so I'm closing it.
