### ISSUE TITLE
[Bug] Underwater is clear on mods with shaders on

### ISSUE THREAD

**Issue by puingin** [sp614x/optifine#4879]
## Description of Issue
When I go underwater in some mods, the water is like totally clear.

## Steps to Reproduce
1. Download mods with custom water and have shaders on
2. Go underwater and look around, you  can see everything much clearer than its supposed to be. Is this intentional??

## OptiFine Version

OptiFine HD U G3

## Installation Method
Dropped it into the mods folder on forge

## Fabric/Forge Version
Forge 1.16.3

**Comment by sp614x** [comment]
Both mods and shaders can change how underwater is rendered.
You should compare it to vanilla or test with other shaders.
