### ISSUE TITLE
[1.16.3][ctm random] flower pots

### ISSUE THREAD

**Issue by Rog360** [sp614x/optifine#4881]
## Description of Issue
flower pots only random with plants. put a plant and it goes back to default texture

## Steps to Reproduce
1. place flower pot with random design works.
2. add flower and bam.

## OptiFine Version
OptiFine 1.16.3_HD_U_G4_pre1 

## Installation Method
installer

## Other Installed Mods
None

## F3 Debug Screenshot
![2020-10-04_20 11 34](https://user-images.githubusercontent.com/681811/95030469-f4a40280-067d-11eb-8c50-2ef2b5dd00fa.png)
![2020-10-04_20 11 48](https://user-images.githubusercontent.com/681811/95030477-fec60100-067d-11eb-94ee-39458f2cbf5b.png)

**Comment by sixfootblue** [comment]
are you doing matchBlocks=flower_pot in your CTM file and nothing else?

Flower pots with flowers in them use a different block ID. (In your second screenshot it says the block ID is now potted_wither_rose)

Also if that's not the case, you should post an example resource pack with the issue so people can take a look at it.

**Comment by Rog360** [comment]
I'm Using the below properties file. Figured the potted flowers would use the same pot.

matchBlocks=minecraft:flower_pot
tiles=0-19
method=random
symmetry=all

Test Resource pack
http://www.mediafire.com/file/xexr0uwgc2z9nre/Test_1.16.3.zip/file

**Comment by sp614x** [comment]
The blockstate `minecraft:flower_pot` matches only the empty flower pot.
When a flower is placed the blockstate changes to `potted_wither_rose` - it is visible in your screenshot.

![image](https://user-images.githubusercontent.com/16635441/95378742-a2184f80-08e4-11eb-8f0b-0ca60fc64310.png)

you should add `matchBlocks=potted_wither_rose` to match the flower pot with wither rose inside

**Comment by Rog360** [comment]
Had to use below for it to work. Thanks for your work... :)

matchTiles=flower_pot potted_acacia_sapling potted_allium potted_azure_bluet potted_bamboo potted_birch_sapling potted_blue_orchid potted_brown_mushroom potted_cactus potted_cornflower potted_crimson_fungus potted_crimson_roots potted_dandelion potted_dark_oak_sapling potted_dead_bush potted_fern potted_jungle_sapling potted_lily_of_the_valley potted_oak_sapling potted_orange_tulip potted_oxeye_daisy potted_pink_tulip potted_poppy potted_red_mushroom potted_red_tulip potted_spruce_sapling potted_warped_fungus potted_warped_roots potted_white_tulip potted_wither_rose
tiles=0-18
method=random
symmetry=all
