### ISSUE TITLE
World corruption and random crashing with RTX 3080

### ISSUE THREAD

**Issue by alanESV2** [sp614x/optifine#4886]
## Description of Issue
Usually after some minutes of gameplay, Minecraft may randomly crash and sometimes (not always) make my PC immediately restart, other times it crashed and sent me to desktop. Hours can go by without a crash so I had a whole world with many hours of gameplay that corrupted. When this happened, I was in the nether when it suddenly crashed. I reopened the world and my pc instantly restarted but Minecraft couldn't find that world again (It got corrupted).

I can only assume this is an issue with the new 3000 series Nvidia GPUs and Optifine as I had no other mods installed and vanilla Minecraft works just fine. 

## Steps to Reproduce
1. Play with RTX 3080 GPU
2. Play some more but don't get attached to your world.

## OptiFine Version
1.16.3-OptiFine_HD_U_G3

## Installation Method
Default installer

## Log Files/Crash Reports
Any relevant log files. Drag and drop text files here to upload to GitHub directly, OR upload the complete contents to Pastebin. 

You can get logs from `.minecraft/logs`, and crash reports from `.minecraft/crash-reports`. 
Locating your `.minecraft` folder will depend entirely on your OS. See this page for details: https://minecraft.gamepedia.com/.minecraft

**DO NOT directly copy and paste log contents here on GitHub.**

## F3 Debug Screenshot
Minecraft's built-in debug screen provides *a lot* of useful information, and should be included even if the issue is not something that can be captured in a still image.

To open this menu, simply press `F3` on your keyboard while in-game. Please ensure the text is easily readable. Depending on the size/resolution of your monitor, you may have to adjust your GUI scale for all text to be completely visible on-screen.

## Prior Testing
If you've installed standalone:
- No.

## Additional Information
Here goes any final remarks and everything else that might not fit in the previous sections.
I was using SEUS PTGI shader pack and the normal SEUS for the nether. I've had crashes with both of them. Also I was using the 256x Faithful PBR texture pack.

**Comment by Beksim** [comment]
As most people do not own a 3080 can you try the same thing without Optifine and see if the issue remains. and then report back on that.

**Comment by alanESV2** [comment]
> As most people do not own a 3080 can you try the same thing without Optifine and see if the issue remains. and then report back on that.

I have no issues running vanilla Minecraft at all. To be fair though, it might’ve just been the higher load that made it crash, so I down clocked the GPU by 50Mhz to see if that helps. I read this is recommended for cases like this.

**Comment by sp614x** [comment]
Looks like a GPU driver problem or overheating issue.
Minecraft + OptiFine shouldn't be able to crash and restart your PC.
