### ISSUE TITLE
Campfires causing major lighting issues

### ISSUE THREAD

**Issue by britnuka** [sp614x/optifine#4888]
## Description of Issue
I'm on Sildurs Shaders Extreme, every time a campfire in nearby leaves completely lose their shadows.

Trees normally;
![image](https://user-images.githubusercontent.com/68449708/95255691-afb4d300-0819-11eb-9bae-bcc32b304c45.png)

Trees with campfire nearby;
![image](https://user-images.githubusercontent.com/68449708/95255621-94e25e80-0819-11eb-8b8c-80d658855af9.png)

## Steps to Reproduce
1. Using Sildurs Shaders Extreme
2. Place a campfire near some trees
3. Watch the shadows in the leaves dissappear

## OptiFine Version
1.15.2

## Installation Method
Used installer

## Other Installed Mods
None

**Comment by sp614x** [comment]
Fixed, coming in G4_pre2.
