### ISSUE TITLE
Legacy support

### ISSUE THREAD

**Issue by dalek955** [sp614x/optifine#4889]
How far back does support run? I have a 1.7.10 issue.

**Comment by Docteh** [comment]
I don't know. I know that there was a 1.8.9 version released recently to fix some bugs. You can edit every part of your issue, why not make this issue your 1.7.10 issue?

**Comment by dalek955** [comment]
When I put any of the 1.7.10 versions in my mod folder, the game seems to load correctly, but then gives me a single frame of the title screen and then crashes.

The game crashed whilst unexpected error
Error: java.lang.VerifyError: Bad local variable type
Exit Code: -1
[crash-2014-09-05_19.43.03-client.txt](https://github.com/sp614x/optifine/files/5345568/crash-2014-09-05_19.43.03-client.txt)

**Comment by sp614x** [comment]
Looks like a conflict with one of the installed mods, most probably Highlands.
https://www.curseforge.com/minecraft/mc-mods/highlands

**Comment by dalek955** [comment]
My bad, I accidentally posted the oldest crash report in the folder instead of the latest. Here is the report for the crash actually caused by Optifine.
[crash-2020-10-07_22.55.30-client.txt](https://github.com/sp614x/optifine/files/5352609/crash-2020-10-07_22.55.30-client.txt)
