### ISSUE TITLE
Shadow Map Viewing Volume Optimization

### ISSUE THREAD

**Issue by BruceKnowsHow** [sp614x/optifine#489]
The shadow pass can be optimized by culling chunks which are outside the player's viewing volume, and which do not have the potential of casting shadows onto the player's viewing volume.

**Comment by sp614x** [comment]
Also optional shadow render distance may be added:

    const float shadowRenderDistance = 120.0f;

in this case the shader pack should implement a smooth shadow fade out to smooth the transition.

**Comment by sp614x** [comment]
Many shader packs already have a variable shadow distance as an user option. 
Some of them use custom shadow map transformation, so the effective render distance is different from the `shadowMapDistance`.

A better solution would be to add:

    const float shadowRenderDistanceMul = 1.0f;

Then `shadowRenderDistance = shadowMapDistance * shadowRenderDistanceMul`. 
If `shadowRenderDistanceMul` is not defined the render distance will not be limited.

**Comment by BruceKnowsHow** [comment]
So shadowRenderDistanceMul would allow the user to increase the finite chunk loading distance? That is reasonable, but I still think the chunk culling should be an explicit option. If it is just determined by whether or not the constant shadowRenderDistanceMul is defined, then there is no way to bind it to a user setting.

The shadow bias that SEUS popularized actually does not increase the maximum shadow draw distance. Many shaderpacks now scale the deformed terrain by a small constant after the bias is applied, this is part of what I introduced with "extended shadow distance". Right now my shaderpack has an option to not scale the biased shadow map, and therefore the maintain the shadow distance endpoints. All I'm waiting for is an explicit option to enable chunk culling.

**Comment by sp614x** [comment]
When shadowRenderDistanceMul is not defined there will be no culling (default).
With `shadowRenderDistanceMul = 1.0` the culling will be enabled with limit `shadowMapDistance`.
The user option should be `shadowMapDistance` and `shadowRenderDistanceMul` can be used to tweak the culling for a custom transform.

**Comment by sp614x** [comment]
OptiFine 1.11.2_HD_U_B8_pre
 - added shaders shadow optimization "shadowDistanceRenderMul" (#489) 

When "shadowDistanceRenderMul > 0" the shadow optimization is enabled with "shadowRenderDistance = shadowDistance * shadowDistanceRenderMul"
