### ISSUE TITLE
[Memory Bug / Crash] Optifine maxes out memory when loading an existing world with multiple datapacks.

### ISSUE THREAD

**Issue by pianoboy8** [sp614x/optifine#4896]
## Description of Issue
I've started a world that uses multiple datapacks together while trying out the new features in the latest MC version (1.16.3), and whenever I tried running it with Optifine after initially creating it, it maxes my allocated RAM for MC (2GB max), causing my computer to freeze up from a lack of general RAM accessibility & eventually requires a force close of MC to get control over my computer again.

## Steps to Reproduce
-Create a new world with the list of datapacks below.
-Save and quit out of the world, then reopen it with Optifine installed in some way.

## OptiFine Version
OptiFine HD U G3

## Installation Method

Tested using the standalone installer & using forge, both cases caused the issue described above.

## Fabric/Forge Version
When testing with Forge, I used forge-1.16.3-34.1.0.

## Other Installed Mods
Mods when using Forge:
-Xaero's Minimap Mod v20.25.0
-Xaero's World Map Mod (latest as of 2020/10/09).

Datapacks used:
-Timber v2.1.0
-BlazeandCave's Advancements Pack (latest as of 2020/10/09).
-auto-utilities vein mining datapack v2.0
-datapackutilities v2.2.1d
-cavebiomes v1.1.2a
-immersive soundscapes datapack v2.3
-seasonal calendar datapack v2.0.2

## Log Files/Crash Reports
[2020-10-09-4.log.gz](https://github.com/sp614x/optifine/files/5358271/2020-10-09-4.log.gz)
[2020-10-09-5.log.gz](https://github.com/sp614x/optifine/files/5358272/2020-10-09-5.log.gz)
[latest.log](https://github.com/sp614x/optifine/files/5358273/latest.log)
[2020-10-09-1.log.gz](https://github.com/sp614x/optifine/files/5358274/2020-10-09-1.log.gz)
[2020-10-09-2.log.gz](https://github.com/sp614x/optifine/files/5358275/2020-10-09-2.log.gz)
[2020-10-09-3.log.gz](https://github.com/sp614x/optifine/files/5358276/2020-10-09-3.log.gz)

## Prior Testing
I did some general testing to see if it was in regards to a specific datapack (creating a new world using a small # of datapacks from the main world i'm in, running the world and seeing if it causes issues after loading, repeat with new datapacks), but in every test I did when breaking up the datapacks, I was able to load up my MC world without massive frame lag due to high memory usage, as the actual % memory used never went past 60%-70%. But whenever I used them all together in a new world, quit out and then joined back, it forced the frame spike and maxes my memory / causes the game to get stuck at loading the world. Also in general, saving maps that have datapacks takes a very long while to process when using optifine in some way.

I want to also note that running MC with all of the datapacks together, plus forge and xaero's minimap/world map mods (but excluding optifine) does NOT cause the major frame issues / memory issues. I've also tested this through just the optifine launcher and not through forge but with the full datapack list, and it causes the same issue.

## Additional Information
I'm really unsure on why optifine's inclusion would impact my memory so greatly, especially as I've not had issues regarding optifine in the past. This is also the first time I've been using optifine in 1.16.3 (and in the past week is the first time i've played 1.16 in general, I tend to play on 1.8.9 / multiplayer servers). I don't think it is related to optifine's extra settings either in terms of quality, as my laptop is pretty low end and therefore I tend to use low optifine settings to begin with. Yet I don't have the memory issues described when playing w/o optifine, with the mods previously mentioned, and the full list of datapacks, at standard/high vanilla mc quality settings.

Computer Specs:
Dell Inspiron 15 5567
CPU: i7-7500U
GPU: Radeon R7 M445
RAM: 8GB
JVM Arugments: -Xmx2G -Xms1G -Xmn128m -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+UseNUMA -XX:+CMSParallelRemarkEnabled -XX:MaxTenuringThreshold=15 -XX:MaxGCPauseMillis=30 -XX:GCPauseIntervalMillis=150 -XX:+UseAdaptiveGCBoundary -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=15 -Dfml.ignorePatchDiscrepancies=true -Dfml.ignoreInvalidMinecraftCertificates=true -XX:+UseFastAccessorMethods -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+AggressiveOpts -XX:ReservedCodeCacheSize=2048m -XX:+UseCodeCacheFlushing -XX:SoftRefLRUPolicyMSPerMB=2000 -XX:ParallelGCThreads=10

**Comment by GrantGryczan** [comment]
I would bet that this is caused by #4832

**Comment by pianoboy8** [comment]
Yo sorry for the late response, here's a list of the files
[cavebiomes-v1-1-2a.zip](https://github.com/sp614x/optifine/files/5394875/cavebiomes-v1-1-2a.zip)
[coordinates hud v1.2.0.zip](https://github.com/sp614x/optifine/files/5394876/coordinates.hud.v1.2.0.zip)
[datapackutilities-v2-2-1d.zip](https://github.com/sp614x/optifine/files/5394877/datapackutilities-v2-2-1d.zip)
[immersive-soundscapes-datapack-v2.3.zip](https://github.com/sp614x/optifine/files/5394878/immersive-soundscapes-datapack-v2.3.zip)
[nether portal coords v1.1.0.zip](https://github.com/sp614x/optifine/files/5394879/nether.portal.coords.v1.1.0.zip)
[seasonal-calendar-datapack-v2.0.2.zip](https://github.com/sp614x/optifine/files/5394880/seasonal-calendar-datapack-v2.0.2.zip)
[Timber_v2.1.0.zip](https://github.com/sp614x/optifine/files/5394881/Timber_v2.1.0.zip)
[auto-utilities-vein-mining-datapack-v2.0.zip](https://github.com/sp614x/optifine/files/5394882/auto-utilities-vein-mining-datapack-v2.0.zip)
[bac_advancements.zip](https://github.com/sp614x/optifine/files/5394884/bac_advancements.zip)
(For reference: bac_advancements is a folder in a zip, in my datapacks folder I only run the folder itself without it being zipped)







:

**Comment by GrantGryczan** [comment]
Yes, it appears the following data packs are in fact triggering the issue I referenced above:
auto-utilities-vein-mining-datapack-v2.0.zip
datapackutilities-v2-2-1d.zip
seasonal-calendar-datapack-v2.0.2.zip

**Comment by pianoboy8** [comment]
Ah, thanks.
