### ISSUE TITLE
FPS increase?

### ISSUE THREAD

**Issue by SlimeDog** [sp614x/optifine#49]
I am running OptiFine 1.9 and CustomSky on a reasonably powerful Mac laptop (i7 cores). The sky is very pretty, but I am wondering about the claims of up-to-double FPS. I see a little higher FPS with OptiFine, but not double. Am I missing something?

**Comment by sp614x** [comment]
To compare vanilla and OptiFine you have to disable all OptiFine features which are not present in vanilla. For example: custom sky, connected textures, better grass, better snow, custom colors, etc.
Also every computer reacts differently depending on its specific hardware.

**Comment by SlimeDog** [comment]
Thanks. I am happy with OptiFine. Just always looking for more. :)

**Comment by sp614x** [comment]
I always enable Smooth FPS, it can make 30 FPS playable, while vanilla 60 FPS can be very choppy and annoying. Also Vignette: Fast and Trees: Smart can be added for more FPS. 
For low-level GPUs Fast Render can make significant difference.

**Comment by SlimeDog** [comment]
Thanks. For a laptop, my NVIDIA GeForce GT is pretty good. I'll try the suggested settings that I haven't done already.
