### ISSUE TITLE
Chunks not loading properly

### ISSUE THREAD

**Issue by Deadflame26** [sp614x/optifine#4901]
## Description of Issue
Nothing loades beyond render distance 6.

## Steps to Reproduce
1. Play on Optifine

## OptiFine Version
    Idk

## Installation Method
I use TLauncher it automatically downloads the newest version

## F3 Debug Screenshot
![2020-10-11_18 48 28](https://user-images.githubusercontent.com/72704337/95685146-5fad8600-0bf6-11eb-92db-81c81aad4595.png)

## Prior Testing
It does not happen without optifine

**Comment by Jorkles** [comment]
TLauncher is not supported here.

**Comment by Cart3r1234** [comment]
Tlauncher is a pirated launcher, so you will not get any support for it since it is illegal.
