### ISSUE TITLE
[Feedback] Bug report issue template

### ISSUE THREAD

**Issue by Regnander** [sp614x/optifine#4902]
I wanted to give my feedback on the bug template.

### Description

Since the instructions are meant to help people create bug reports, I think it's unnecessary for the readers to see them. By embedding them with `<!--` and `-->` they are parsed as comments and will only be visible when editing.

### Pros/Cons

➕ Makes issues look less "busy" when people are too lazy to remove the instructions before posting.

➖ You won't be able to click any links.

➖ Someone might try to write inside the comments. Although I find that very unlikely.

### Description

Instead of having two separate sections for the Fabric/Forge and OptiFabric version, I think it should be more appropiate to have both in one section.

(Alternatively, the OptiFine version could also be in the same section as well.)

### Pros/Cons

➕ You only have to remove one section if OptiFine is installed as standalone (or no sections at all if all versions are in one section).

➕ Makes it look like there is less stuff to worry about when there is one less section, which I doubt is a bad thing.

### Description

At the moment, we have the binary search instruction (_"To find conflicting mods, split..."_) inside the bullet list, which can be moved down to a footnote below the list.

|  Before   |  After   |
| :-------: | :------: |
| ![before] | ![after] |

[before]: https://user-images.githubusercontent.com/17113053/95661788-5eb32080-0b32-11eb-82ea-5820902f90dc.png
[after]: https://user-images.githubusercontent.com/17113053/95661786-5e1a8a00-0b32-11eb-87b2-79c92f11440c.png

### Pros/Cons

➕ Separates the instruction from the questions.

**Comment by KaiAF** [comment]
This seems to be added now. If not, let me know.

**Comment by Regnander** [comment]
#4945 fixed everything except the last thing, but I'm more or less satisfied since bug reports won't be filled with instructions if the reporter is too lazy to remove them anymore.
