### ISSUE TITLE
[Suggestion] 3D Armor

### ISSUE THREAD

**Issue by MoonTheBird** [sp614x/optifine#4907]
I just want to be able to use custom models for armor

**Comment by Regnander** [comment]
Duplicate of #1606, #561 and #291

**Comment by MajorMoonjump** [comment]
those were literal years ago and appear to have been abandoned

**Comment by Cart3r1234** [comment]
It does still have the to-do list tag

**Comment by MastaNub** [comment]
Bedrock already has 3D armour. Nice.

**Comment by KaiAF** [comment]
Already suggested #1606, #561 and #291.
