### ISSUE TITLE
[CIT] Custom Item Textures not working with tools

### ISSUE THREAD

**Issue by grahamverchere** [sp614x/optifine#4909]
## Description of Issue
Custom item textures are not working in game with tools. Formatted correctly, using the information on github, elytra, armor, and enchantment textures work just fine. I personally couldn't get tool textures to work, even though to the best of my knowledge the files are correct. I also downloaded a few popular CIT resource packs that use both tool CIT and the other types and had the same issue.
Specifically, the issue came up when using nbt.display.Name -- I'm not sure if the other nbt conditions work.

## Steps to Reproduce
1. Set up a CIT on any tool
2. The custom texture does not appear in game.

## OptiFine Version
1.16.3 HD U G3

## Installation Method
Standalone installer from the website

## Other Installed Mods
None

## F3 Debug Screenshot
![2020-10-13_01 42 54](https://user-images.githubusercontent.com/43447121/95837516-8dc5bf80-0cf5-11eb-9532-f12324486c73.png)

## Prior Testing
If you've installed standalone:

- Does this happen in Vanilla without OptiFine?
N/A

## Additional Information
I don't really do this kind of thing often, but I'm almost certain I did everything right - especially because the other types of items worked.
I'm attaching the resource pack i was trying to make, called SWORD.TEST.zip. It's possible I did something wrong, in which case help is also appreciated, but the uploaded file is also after trying everything I could think of to fix it.
[SWORD TEST.zip](https://github.com/sp614x/optifine/files/5370176/SWORD.TEST.zip)

Thanks so much

**Comment by SolarSupremacy** [comment]
I'm having a similar issue. If I spawn an item with a name matching the file I have setup, it doesn't have the custom texture. If I put it in a chest and rejoin the server, it still doesn't have the custom texture.

However, if I spawn the item, go into my inventory, click it and put it back into a slot, the texture works. If I put the item into a chest after this and rejoin the server, the texture still works.

This doesn't many any sense to me. Somehow clicking on the item is affecting it server-side and that is affecting the appearance of the texture locally.

Quite irritating.

**Comment by FantasyPvP** [comment]
ive got this same issue

when i get the custom texture to replace an item it works fine but if i try it with a tool it just wont work

**Comment by Cart3r1234** [comment]
> I'm having a similar issue. If I spawn an item with a name matching the file I have setup, it doesn't have the custom texture. If I put it in a chest and rejoin the server, it still doesn't have the custom texture.
> 
> However, if I spawn the item, go into my inventory, click it and put it back into a slot, the texture works. If I put the item into a chest after this and rejoin the server, the texture still works.
> 
> This doesn't many any sense to me. Somehow clicking on the item is affecting it server-side and that is affecting the appearance of the texture locally.
> 
> Quite irritating.
> 
> Edit:
> optifine/cit/dagger.png
> optifine/cit/dagger.properties:
> 
> ```
> matchItems=stone_sword
> nbt.display.Name=iregex:(dagger)
> tile=dagger
> ```

This is something I had an issue with but was able to fix using different command syntax.  apparently there are two different syntaxes for named items in 1.16, and only one of them works for CIT for some reason.  Switching to the other syntax worked fine for me.

**Comment by sp614x** [comment]
Apparently the game generates different names depending on how the item is created:
- command
![image](https://user-images.githubusercontent.com/16635441/111161301-4b055d80-859b-11eb-84c9-ac386a741213.png)
- anvil
![image](https://user-images.githubusercontent.com/16635441/111161375-63757800-859b-11eb-9252-987e1f7da65e.png)

**Comment by sp614x** [comment]
Fixed, coming in next preview.

**Comment by FantasyPvP** [comment]
for some reason custom textures dont render on any tools but if i change the name to the name of a regular item it works fine
