### ISSUE TITLE
Changing resolution with i3 window manager

### ISSUE THREAD

**Issue by ChrisLane** [sp614x/optifine#491]
I currently use the i3 window manager on Arch Linux and was trying to get the fullscreen resolution changing feature working in 1.11.2 Optifine.

My monitor is 3200x1800 on my laptop and I don't want to be running at that resolution all the time (loud fan). When the window is fullscreen, the full resolution is used, no matter what I set in the Minecraft settings.

Is there a way for Optifine to be changed so that I can in fact set 1080p resolution to be stretched across the fullscreen in my environment?
I can change the window to float instead and change the window size in my window manager but then it's 1080p and doesn't fill the screen.

**Comment by plexigras** [comment]
maybe seting ofFullscreenMode in ~/.minecraft/optionsof.txt to 1920x1080 works

**Comment by ChrisLane** [comment]
Returned to try this again with the latest forge and optifine and it seems to be fixed for when I select fullscreen in-game.
Closing the issue.
