### ISSUE TITLE
1.16.3 optifine not showing as status in discord ONLY 1.16.3

### ISSUE THREAD

**Issue by ImBlueYoshi** [sp614x/optifine#4911]
## Description of Issue
My smp server recently updated to .3 of 1.16 so I downloaded optifine for that version and it doesn't show mc as my discord status and I want people to know if I'm playin or not and it shows my status in every other version of optifine I've downloaded this also crashes my game when using overlay.
## Steps to Reproduce
1,2. What do you do... Download 1.16.3 optifine and see that discord does not detect it as a game.\

## OptiFine Version
Self-explanatory. 1.16.3

## Installation Method
How did you install OptiFine? Did you use the included standalone installer, or did you drop the JAR file into your "mods" folder?
I used the included installer which always works for me.

## F3 Debug Screenshot
Minecraft's built-in debug screen provides *a lot* of useful information, and should be included even if the issue is not something that can be captured in a still image.
![image](https://user-images.githubusercontent.com/68860760/95882712-a2c74080-0d3f-11eb-8b3c-49acf629c74c.png)

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
no vanilla 1.16.3 shows I'm on

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   - Only OptiFine and Forge
   - Only OptiFine, OptiFabric, and Fabric
- Does this happen without any mods at all?
   - Only Forge/Fabric by itself.
- Does this happen in OptiFine standalone?
- Does this happen in Vanilla without OptiFine?
- Have you tried using a binary search to find which mods cause this issue?
   - To find conflicting mods, split your mods into 2 groups (not including OptiFine/OptiFabric, obviously). Remove one group, and test in-game. Keep the group that has the problem, and repeat until no more mods can be removed without the issue disappearing.
   - Does the issue still happen with only the remaining mods installed?
      - Forge/Fabric and remaining mods, without OptiFine

## Additional Information
Here goes any final remarks and everything else that might not fit in the previous sections.

**Comment by sp614x** [comment]
This is a problem with Discord.
No idea how it detects the Minecaft status.
