### ISSUE TITLE
Problem downloading Optifine

### ISSUE THREAD

**Issue by BuckingBroncsYT** [sp614x/optifine#4915]
<img width="323" alt="Optifine_not_downloading" src="https://user-images.githubusercontent.com/72840566/95929862-e0e15600-0d79-11eb-84e1-7b536058d825.PNG">

Whenever I try to download the newest version of Optifine this pops up [image above]. If I hit keep it then says it can't download because it contains a virus.

**Comment by Cart3r1234** [comment]
just press keep, windows does that for all .jar and .exe files.
