### ISSUE TITLE
[Website] Can't get into optifine website

### ISSUE THREAD

**Issue by heh372** [sp614x/optifine#4916]
![Screen Shot 2020-10-14 at 9 19 08 AM](https://user-images.githubusercontent.com/66488498/95994454-52fb7e80-0dfe-11eb-9e4b-799e9163d02c.png)
whenever I tried to get into the website it says chedcking my brower but after 5 seconds it refreshes and still in the same page checking my brower, please let me know how to solve this issue, is it the server or is it my browser

**Comment by sp614x** [comment]
That was a temporary problem with CloudFlare.
Works now.
