### ISSUE TITLE
[Category] Short description

### ISSUE THREAD

**Issue by jaxbline** [sp614x/optifine#4917]
## Description of Issue
Seems like installing only Biomes o' Plenty and Optifine seems to cause a crash apon making a world or starting one. 

I've reported this crash to the [BOP issue tracker](https://github.com/Glitchfiend/BiomesOPlenty/issues/1703) but thought i should tell the bug here too.

## Steps to Reproduce
1. Install Optifine with BOP
2: Create or start a world with BOP
3: Profit

## OptiFine Version
1.16.3 Optifine HD U G3 (and G4)

## Installation Method
Drag and drop

## Fabric/Forge Version
1.16.3 - 34.1.19 - FORGE

## Other Installed Mods
BiomesOPlenty-1.16.3-12.0.0.409-universal

**If OptiFine is installed as standalone, remove this section.**

## Log Files/Crash Reports
[crash-2020-10-14_12.25.35-server.txt](https://github.com/sp614x/optifine/files/5379935/crash-2020-10-14_12.25.35-server.txt)

## F3 Debug Screenshot
N/A
Unable to get into a game.

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
Nope

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   -Nope
- Does this happen without any mods at all?
   - It only happens with BOP installed
- Does this happen in OptiFine standalone?  No
- Does this happen in Vanilla without OptiFine?
Nope
- Have you tried using a binary search to find which mods cause this issue?
   - To find conflicting mods, split your mods into 2 groups (not including OptiFine/OptiFabric, obviously). Remove one group, and test in-game. Keep the group that has the problem, and repeat until no more mods can be removed without the issue disappearing.

I tried running all my mods without optifine and it worked just fine, As soon as i installed Optifine, im unable to play a created world or create one at all
   - Does the issue still happen with only the remaining mods installed?
      - Forge/Fabric and remaining mods, without OptiFine

## Additional Information
Here goes any final remarks and everything else that might not fit in the previous sections.

**Comment by KaiAF** [comment]
Closing this as I believe this was fixed recently. If you are still having any issues, let me know.
