### ISSUE TITLE
[crash] the game crashes when trying to load a world

### ISSUE THREAD

**Issue by samsoumX** [sp614x/optifine#4924]
## Description of Issue
when loading a world when it reaches 100% it crashes living this at the luncher
The game crashed whilst unexpected error
Error: java.lang.IllegalStateException: Lock is no longer valid
Exit Code: -1

## OptiFine Version
1.16.x
## Installation Method
doesn't work with optifine alone
doesn't work with optifabric
...

## Log Files/Crash Reports
https://pastebin.com/qFnw6zUE

## F3 Debug Screenshot
can't load any world to get that

## Prior Testing
- Does this happen in Vanilla without OptiFine?
NO only with optifine

## Additional Information
https://pastebin.com/qFnw6zUE
that's the crash report I won't paste it in here like you said "eyes rolling"

**Comment by LuckyOwl1105** [comment]
I have been having this problem for a couple of months now.

**Comment by KaiAF** [comment]
Seems to be related to #4996. This issue has been reported a few times, and little to no fixes have been found, unfortunately.
