### ISSUE TITLE
[Crash] Game crashes irregularly cannot rule out hardware issue

### ISSUE THREAD

**Issue by JeffKerman** [sp614x/optifine#4933]
## Description of Issue
While playing crashes at seemingly random points.

## Steps to Reproduce
1. Play on multiplayer server
2. Wait for crash

## OptiFine Version
1.16.3-Optifine_HD_U_G3

## Installation Method
Standalone Installer

## Crash Reports
https://pastebin.com/r4vncxzX

## Prior Testing
- Does this happen in Vanilla without OptiFine?
Not sure

Could be hardware problem.

**Comment by Jorkles** [comment]
Please verify that this is an optifine problem before submitting here.

**Comment by KaiAF** [comment]
This doesn't seem like it's an OptiFine issue. I honestly, cannot tell.
