### ISSUE TITLE
More render distance!

### ISSUE THREAD

**Issue by Namnodorel** [sp614x/optifine#494]
Hey,

it'd be really useful if I could adjust the render distance to even higher levels - 32 ist enough for normal playing, but when recording scenes (especially when the camera is located very high) things would look much better if I could set the render distance even higher. I don't care about any lag or memory usage problems with this, using the ReplayMod there is no such thing as "lag" in the final video. But there is unfortunaley a thing "awesome scene is ruined by unloaded chunks". 

I hope to hear from you soon!

**Comment by sp614x** [comment]
Render distance up to 64 chunks was added inC7 for 1.12.2.
