### ISSUE TITLE
[Category] Optifine installation error

### ISSUE THREAD

**Issue by Pettexd** [sp614x/optifine#4942]
## Description of Issue
Please provide as much detail as possible.

## Steps to Reproduce
1. What do you do i try to intall Optifine but a error message everytime i try to
2. ...to find this bug?

## OptiFine Version
Self-explanatory. 1.161

## Installation Method
How did you install OptiFine? Did you use the included standalone installer, or did you drop the JAR file into your "mods" folder?
I downloaded Optifine file started the version that i was gonna install closed the minecraft window double clicked The opifine intallation file

## Log Files/Crash Reports
Any relevant log files. Drag and drop text files here to upload to GitHub directly, OR upload the complete contents to Pastebin. https://pastebin.com/HjxG7wZ9

You can get logs from `.minecraft/logs`, and crash reports from `.minecraft/crash-reports`. 
Locating your `.minecraft` folder will depend entirely on your OS. See this page for details: https://minecraft.gamepedia.com/.minecraft

**DO NOT directly copy and paste log contents here on GitHub.**

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
I cant even install it

## Additional Information
Here goes any final remarks and everything else that might not fit in the previous sections.

**Comment by KaiAF** [comment]
Has this issue happened recently?

**Comment by KaiAF** [comment]
I assume this is resolved now, if not, let me know.
