### ISSUE TITLE
[Bug] Normal maps dont work on items that entities are holding 1.15+

### ISSUE THREAD

**Issue by a-cpu-a** [sp614x/optifine#4943]
## Description of Issue
Please provide as much detail as possible.

Normal maps dont work on items that item frames are holding or armor stands are holding

## Steps to Reproduce
1. What do you do... 
2. ...to find this bug?

i installed OptiFine 1.16.3_HD_U_G3
i then installed some shaders (https://www.curseforge.com/minecraft/customization/bsl-shaders/)
i then installed a resourcepack with normal maps (https://www.curseforge.com/minecraft/texture-packs/vanilla-pbr)
i placed a item frame
then i put a dead tube coral block in the item frame
then i placed a dead tube coral block
i looked at the block and item frame
i then tried this on 1.14.4-OptiFine_HD_U_F5

## OptiFine Version
Self-explanatory. 
OptiFine_1.16.3_HD_U_G3
1.14.4-OptiFine_HD_U_F5

## Installation Method
How did you install OptiFine? Did you use the included standalone installer, or did you drop the JAR file into your "mods" folder?

i used the standalone installer

## Log Files/Crash Reports
Any relevant log files. Drag and drop text files here to uplo
ad to GitHub directly, OR upload the complete contents to Pastebin. https://pastebin.com/

You can get logs from `.minecraft/logs`, and crash reports from `.minecraft/crash-reports`. 
Locating your `.minecraft` folder will depend entirely on your OS. See this page for details: 
https://minecraft.gamepedia.com/.minecraft

[latest.log](https://github.com/sp614x/optifine/files/5428565/latest.log)

**DO NOT directly copy and paste log contents here on GitHub.**

## F3 Debug Screenshot
Minecraft's built-in debug screen provides *a lot* of useful information, and should be included even if the issue is not something that can be captured in a still image.

![2020-10-23_12 12 28](https://user-images.githubusercontent.com/54659787/96985839-81c5d300-1529-11eb-8fbd-f818a312e646.png)

To open this menu, simply press `F3` on your keyboard while in-game. Please ensure the text is easily readable. Depending on the size/resolution of your monitor, you may have to adjust your GUI scale for all text to be completely visible on-screen.

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?

No it cant since there arent normal maps in vannila

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   - Only OptiFine and Forge
   - Only OptiFine, OptiFabric, and Fabric
- Does this happen without any mods at all?
   - Only Forge/Fabric by itself.
- Does this happen in OptiFine standalone?
- Does this happen in Vanilla without OptiFine?
- Have you tried using a binary search to find which mods cause this issue?
   - To find conflicting mods, split your mods into 2 groups (not including OptiFine/OptiFabric, obviously). Remove one group, and test in-game. Keep the group that has the problem, and repeat until no more mods can be removed without the issue disappearing.
   - Does the issue still happen with only the remaining mods installed?
      - Forge/Fabric and remaining mods, without OptiFine

## Additional Information
Here goes any final remarks and everything else that might not fit in the previous sections.

This bug makes it so i cant use normal maps on my custom blocks wich makes them look trash

I did find this back when 1.15 came out but i was too lazy to report it

**Comment by fayer3** [comment]
probably related to #3808

**Comment by a-cpu-a** [comment]
seems like it but idk anything about shader stuff
