### ISSUE TITLE
CEM add support for Llama

### ISSUE THREAD

**Issue by Whetu-Paitai** [sp614x/optifine#495]
Hi there, great work here.

It seems there is no current support for Llama models. Is this the case? And if so, do you intend on adding Llama models to CEM?

Thank you.

**Comment by sp614x** [comment]
Updated preview C1 for 1.11.2
- added CEM support for husk, stray, wither skeleton, llama, mooshroom and zombie_villager

**Comment by mahimaina** [comment]
You are absolute magic!
