### ISSUE TITLE
[Bug] Change cape button dosent open the website when chrome is defalut browser

### ISSUE THREAD

**Issue by marvhus** [sp614x/optifine#4950]
## Steps to Reproduce
1. Set chrome as the default brobser
2. press the button to change cape

## OptiFine Version
ive tested with the latest 1.16.3 version (1.16.3-Optifine-HD-U-G3) and i tested (1.16.1-Optifine_HD_U_G2_pre2)

## Installation Method
i used the standalone instaler

## Log Files/Crash Reports
latest.log file https://pastebin.com/ZeYPz6kU

## Additional Information
when i put Firefox or microsoft edge as the default browser it works fine.

I think there might be some issue with suport for chrome with the new website

**Comment by KaiAF** [comment]
No idea what actually causes this, if there was an error in OptiFine, it would show in the logs the link. OptiFine uses the same method that vanilla uses to open links. This issue could be something with the browser. I assume this issue is nothing actually related to OptiFine itself, I don't know.
