### ISSUE TITLE
[Bug] Textures are missing.

### ISSUE THREAD

**Issue by btpwdb365** [sp614x/optifine#4953]
## Description of Issue
When connecting to the server, textures sometimes disappear, and no OpenGL errors are displayed. 
The bug is reproducible on any texture pack and without it.

## Steps to Reproduce
1. Run a game.
2. Join server (or switch between BungeeCoed servers).

## OptiFine Version
Since 1.15.

## Installation Method
Standalone installer.

## Other Installed Mods
No other mods installed.

## Log Files/Crash Reports
[latest.log](https://github.com/sp614x/optifine/files/5434614/latest.log)

## F3 Debug Screenshot
![2020-10-25_14 30 06](https://user-images.githubusercontent.com/71988601/97105785-b626c400-16ce-11eb-8c58-bdbe73045bd8.png)

## Prior Testing
- Does this happen in Vanilla without OptiFine?
- No.

## Additional Information
Screenshots:
![2020-10-25_13 57 48](https://user-images.githubusercontent.com/71988601/97105671-d1450400-16cd-11eb-8c0a-a611db3b8f81.png)
![2020-10-25_13 57 53](https://user-images.githubusercontent.com/71988601/97105672-d2763100-16cd-11eb-853e-5470a6198117.png)

**Comment by sp614x** [comment]
Fixed, coming in next preview.
