### ISSUE TITLE
[BUG] Minecolonies 1.16.1 Optifine Right Click Yet not Fixed

### ISSUE THREAD

**Issue by W00P4** [sp614x/optifine#4955]
The issue reported here https://github.com/sp614x/optifine/issues/4582  hasnt been fixed yet on Optifine for 1.16.1, any predictions to when it will be fixed?

**Comment by thiagowaw** [comment]
It's happening to me too. I tried all ways and stil not working.

**Comment by KaiAF** [comment]
This is fixed now.
