### ISSUE TITLE
[Suggestion] Coordinates without having to press f3 or extra mods

### ISSUE THREAD

**Issue by BusterBean** [sp614x/optifine#4958]
Hi, I don't know if this has been suggested yet but I think it would be cool if there was an option kind of like the optifine fps hud but with coordinates where we had a hud that it could show the world coordinates and maybe even the direction you're facing without having to press f3 or without having to run extra mods

**Comment by Regnander** [comment]
If you're okay with using datapacks, I'd recommend Vanilla Tweaks: https://vanillatweaks.net/picker/datapacks/

**Comment by BusterBean** [comment]
I don't mind in single player worlds but on servers and realm worlds

**Comment by KaiAF** [comment]
Related #2389.
