### ISSUE TITLE
Optifine crashing on Biomes O Plenty world gen

### ISSUE THREAD

**Issue by mike1000195** [sp614x/optifine#4962]
## Description of Issue
Optifine crashes minecraft when generating world with biomes o plenty setting enabled. 

## Steps to Reproduce
1. create new world, biomes o plenty world type, gets to 0% generated, crashes 
2. vanilla mc and optifine = works
    vanilla mc and BOP = works
    optifine and BOP = crashes

    those are the only 2 mods that i had narrowed it down to through testing

## OptiFine Version
HD_U_G4_pre2

## Installation Method
JAR file into mods folder

## Other Installed Mods
exempt, only narrowed it down strictly to a confliction to optifine and how it handles other mods' biomes worldgen

## Log Files/Crash Reports

LOG:                   https://pastebin.pl/view/a745d96c
Crash Report:     https://pastebin.pl/view/79e5667a

## F3 Debug Screenshot
not able to get into the debug, crashing on world gen

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
   no, only when optifine and BOP are installed together. works perfectly fine with Quark's "realistic biomes" preset when tested. narrowed down to confliction between BOP and Optifine. BOP on github issues page blames optifine rendering.

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   - Only OptiFine and Forge

    no

- Does this happen without any mods at all?
   
    no

- Does this happen in OptiFine standalone?

   yes, with BOP installed

- Does this happen in Vanilla without OptiFine?

   no

- Have you tried using a binary search to find which mods cause this issue?

   no, narrowed down to BOP and optifine
   - Does the issue still happen with only the remaining mods installed?
      
     BOP

## Additional Information

when clicking to proceed to world generation, the following message appears:

"Worlds using Experimental Settings are not supported. This world uses experimental settings that could stop working at any time. We cannot guarantee it will load or work. Here be dragons!"

                                           [Proceed]      [Cancel]

**Comment by Dario1404** [comment]
Same for me

**Comment by Corvus20** [comment]
Just popping in to say that I am also having this issue.

**Comment by Dario1404** [comment]
> 
> 
> Just popping in to say that I am also having this issue.

I solved it by updating both optifine and forge and BoP and now it works with minecraft latest version

**Comment by KaiAF** [comment]
I believe this was fixed recently, if you are still having issues, let me know.
