### ISSUE TITLE
OptiFine 1.17.1 HD U G9 pre26 emissive textures in off hand make entities show no texture

### ISSUE THREAD

**Issue by JimStoneCraft** [sp614x/optifine#4964]
![2020-10-27_15 43 45](https://user-images.githubusercontent.com/42512910/97328055-85c95c00-186d-11eb-863c-948664e20f15.jpg)
![2020-10-27_15 43 49](https://user-images.githubusercontent.com/42512910/97328056-8661f280-186d-11eb-816f-a435877f982a.jpg)

## Description of Issue
If you hold an item or block that has emissive textures in your off hand then entities held in the main hand (Chest, Ender Chest, Trapped Chest, Shulker Box and Bed) do not display a texture and show the black-purple no texture.

## Steps to Reproduce
    Hold an item or block in your off hand (that has emissive textures)
    Hold a Chest, Ender Chest, Trapped Chest, Shulker Box or Bed in your main hand, it will show the black-purple missing texture.

## OptiFine Version
OptiFine 1.16.5 HD U G8 pre10

## Installation Method
Standalone installer.

## Prior Testing
If you've installed standalone:

    Does this happen in Vanilla without OptiFine?
    No it only happens if emissive textures are present for a block or item.

For example in the John Smith Legacy packs, I have put emissive textures on glowstone blocks and other items.

glowstone.png (normal texture)
glowstone_e.png (emissive texture)
etc...

https://www.johnsmithlegacy.co.uk/

**Comment by JimStoneCraft** [comment]
Note that the texture is missing only in third person view.

**Comment by JimStoneCraft** [comment]
Still an issue in OptiFine 1.16.5 HD U G8 pre10, I updated the title.

**Comment by drathmorgh** [comment]
I have been having the same issue. glad I'm no the only one!
