### ISSUE TITLE
open gl error 1286

### ISSUE THREAD

**Issue by agentprime123** [sp614x/optifine#4965]
## game freezez after 1 minutes
using optifine for more than one minute after starting a world the game freezes to 0 fps and without optifine it is running about 40 ish fps and getting a open gl error 1286

## Steps to Reproduce
installing optifine causes freezes
2.standing for a minute after generating a world causes this problem

## OptiFine Version
OptiFine HD U G3

## Installation Method
using forge so i dropped the latest 1.16.3 optifine version to mods folder

## Fabric/Forge Version
forge

## Other Installed Mods
i tried running without any mods it doesent fixed the problem

## Additional Information

i am using kind of an old machine with an integrated graphics at dx 10 but without optifine it is running smooth

**Comment by KaiAF** [comment]
If this is still an issue, please send the latest.log.
Go to .minecraft\logs\latest.log.
