### ISSUE TITLE
No "handy" installer for minecraft 1.7.10

### ISSUE THREAD

**Issue by LordVarnox** [sp614x/optifine#497]
I recently had issues with my minecraft, Launching and relaunching so i clicked "remove" from the minecraft installer set up. I went to go back to 1.7.10 optfine. Then, it gave me a message saying it cannot be run. Please help

**Comment by LordVarnox** [comment]
Note that I do not want to install forge just to run optifine. forge makes my games run very slow and I want to avoid installing it just to install optifine.

**Comment by sp614x** [comment]
The OptiFine installer needs Java in order to run.
1. Install Java, if not already installed
2. Double-click the OptiFine jar, this will start the installer.
3. Click Install
4. Open the Launcher and select the OptiFine profile
