### ISSUE TITLE
Invisible GUI

### ISSUE THREAD

**Issue by Gaber373** [sp614x/optifine#4970]
On 1.12.2 if you play with mods the ingame Ui becomes invisible

**Comment by Regnander** [comment]
What other mods do you have installed?

**Comment by Gaber373** [comment]
i "fixed" the problem by going back to OptiFine HD U F4
this are the other mods

> 	| State  | ID                         | Version              | Source                                        | Signature                                |
> 	|:------ |:-------------------------- |:-------------------- |:--------------------------------------------- |:---------------------------------------- |
> 	| LCHIJA | minecraft                  | 1.12.2               | minecraft.jar                                 | None                                     |
> 	| LCHIJA | mcp                        | 9.42                 | minecraft.jar                                 | None                                     |
> 	| LCHIJA | FML                        | 8.0.99.99            | forge-1.12.2-14.23.5.2854.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
> 	| LCHIJA | forge                      | 14.23.5.2854         | forge-1.12.2-14.23.5.2854.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
> 	| LCHIJA | foamfixcore                | 7.7.4                | minecraft.jar                                 | None                                     |
> 	| LCHIJA | obfuscate                  | 0.4.2                | minecraft.jar                                 | None                                     |
> 	| LCHIJA | randompatches              | 1.12.2-1.22.1.7      | randompatches-1.12.2-1.22.1.7.jar             | None                                     |
> 	| LCHIJA | aether_legacy              | 1.5.2                | aether-1.12.2-v1.5.2.jar                      | None                                     |
> 	| LCHIJA | aether_legacy_addon        | 1.12.2-v1.3.0        | Aether+Continuation+v1.3.0.jar                | None                                     |
> 	| LCHIJA | jei                        | 4.16.1.301           | jei_1.12.2-4.16.1.301.jar                     | None                                     |
> 	| LCHIJA | quark                      | r1.6-179             | Quark-r1.6-179.jar                            | None                                     |
> 	| LCHIJA | autoreglib                 | 1.3-32               | AutoRegLib-1.3-32.jar                         | None                                     |
> 	| LCHIJA | baubles                    | 1.5.2                | Baubles-1.12-1.5.2.jar                        | None                                     |
> 	| LCHIJA | caves                      | 1.0.0                | Caves+.jar                                    | None                                     |
> 	| LCHIJA | clumps                     | 3.1.2                | Clumps-3.1.2.jar                              | None                                     |
> 	| LCHIJA | damagetilt                 | 0.1.0                | DamageTilt-1.12.2-0.1.0.jar                   | None                                     |
> 	| LCHIJA | deathnote                  | 1.0.0                | DeathNote-2.3.jar                             | None                                     |
> 	| LCHIJA | dldungeonsjbg              | 1.13.2               | DoomlikeDungeons-1.13.2-MC1.12.2.jar          | None                                     |
> 	| LCHIJA | ebwizardry                 | 4.3.1                | ElectroblobsWizardry-4.3.1-MC1.12.2.jar       | None                                     |
> 	| LCHIJA | foamflower                 | 1.12.2-1.0.0.0-beta1 | foamflower-1.12.2-1.0.0.0-beta1.jar           | None                                     |
> 	| LCHIJA | enderpay                   | 1.12.2-1.0.1.0       | enderpay-1.12.2-1.0.1.0.jar                   | None                                     |
> 	| LCHIJA | foamfix                    | 0.10.10-1.12.2       | foamfix-0.10.10-1.12.2.jar                    | None                                     |
> 	| LCHIJA | cgm                        | 0.15.3               | guns-0.15.3-1.12.2.jar                        | None                                     |
> 	| LCHIJA | waila                      | 1.8.26               | Hwyla-1.8.26-B41_1.12.2.jar                   | None                                     |
> 	| LCHIJA | ironchest                  | 1.12.2-7.0.67.844    | ironchest-1.12.2-7.0.72.847.jar               | None                                     |
> 	| LCHIJA | journeymap                 | 1.12.2-5.7.1         | journeymap-1.12.2-5.7.1.jar                   | None                                     |
> 	| LCHIJA | jeresources                | 0.9.2.60             | JustEnoughResources-1.12.2-0.9.2.60.jar       | None                                     |
> 	| LCHIJA | llibrary                   | 1.7.19               | llibrary-1.7.19-1.12.2.jar                    | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
> 	| LCHIJA | mowziesmobs                | 1.5.8                | mowziesmobs-1.5.8.jar                         | None                                     |
> 	| LCHIJA | patchouli                  | 1.0-22               | Patchouli-1.0-22.jar                          | None                                     |
> 	| LCHIJA | quickhomes                 | 1.2.2                | QuickHomes-1.2.2.jar                          | None                                     |
> 	| LCHIJA | quickteleports             | 1.1.1                | quickteleports-1.12.2-1.1.1.jar               | None                                     |
> 	| LCHIJA | roguelike                  | 1.8.0                | RoguelikeDungeons-1.12.2-1.8.0.jar            | None                                     |
> 	| LCHIJA | spectrite                  | 1.7.1                | spectrite-1.7.1.jar                           | 00119cfc089819bbcd2f9166a50c7f3df88ded78 |
> 	| LCHIJA | survivalplus               | 0.1.4                | SurvivalPlus-1.12.2-0.1.4.jar                 | None                                     |
> 	| LCHIJA | lightsaber                 | 0.1.5                | SurvivalPlus-Lightsabers-1.12.2-0.1.5.jar     | None                                     |
> 	| LCHIJA | tlauncher_custom_cape_skin | 1.4                  | tlskincape_1.12.2-1.4.jar                     | None                                     |
> 	| LCHIJA | travelersbackpack          | 1.0.34               | TravelersBackpack-1.12.2-1.0.34.jar           | None                                     |
> 	| LCHIJA | twilightforest             | 3.11.1021            | twilightforest-1.12.2-3.11.1021-universal.jar | None                                     |
> 	| LCHIJA | vending                    | 1.12.2-3.0.1.2       | vending-1.12.2-3.0.1.2.jar                    | None                                     |
> 	| LCHIJA | warpbook                   | 1.12.2-3.3.4         | Warpbook-1.12.2-3.3.4.jar                     | None                                     |
> 	| LCHIJA | wawla                      | 2.5.273              | Wawla-1.12.2-2.5.273.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |
> 	| LCHIJA | betteranimalsplus          | 9.0.1                | betteranimalsplus-1.12.2-9.0.1.jar            | None                                     |

**Comment by KaiAF** [comment]
Related probably #5383. This issue most likely was with Journymap. This should be fixed, if not, let me know.
