### ISSUE TITLE
[BUG] Excessive cape requests causes unloadable world textures

### ISSUE THREAD

**Issue by SiskooPOG** [sp614x/optifine#4976]
## Description of Issue
Every time an AbstractClientPlayerEntity is created, optifine makes a requests to its server, if there are too many requests being made or the users internet is poor, the requests hang, causing the entire texture manager to freeze and therefore the world blocks will not appear loaded.
This issue apparently wasn't present before 1.15, apparently this is due to a game design change.

## Steps to Reproduce
Get a poor internet connection or Make too many cape requests to optifine servers to get temporarily blocked to make requests hang
Load a world

## OptiFine Version
1.16.3 HD U G3

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine? : No

## Additional Information

Capes should be ideally be loaded with the game skins, therefore I suggest you take a look at `loadProfileTextures()` in `SkinManager`, reusing the implementation should most probably fix the texture loading freeze issue, and also prevent stagnating requests from mods creating AbstractClientPlayerEntities as NCPs with the same uuid frequently

**Comment by SiskooPOG** [comment]
I tend to believe this is the issue that is causing many texture issues such as https://github.com/sp614x/optifine/issues/4953#issue-729000167

**Comment by cs127** [comment]
I'm pretty sure I have the same problem.
I've been having it since 1.15, only in multiplayer servers with lots of players in the lobby, and I also have a poor internet connection. So it most likely is the same issue.

**Comment by sp614x** [comment]
Fixed, coming in next preview.

**Comment by NickWilde263** [comment]
how this related to performance? (im not attempt to reopen it)
