### ISSUE TITLE
I'm stuck on my loading screen

### ISSUE THREAD

**Issue by vinnyg0621** [sp614x/optifine#4979]
![stuck_on_loading_screen](https://user-images.githubusercontent.com/57818441/97760658-e69ca280-1ac0-11eb-949d-aaa99295d0e0.PNG)

**Comment by Regnander** [comment]
What version do you have? G3?

**Comment by vinnyg0621** [comment]
yes I have G3

**Comment by Regnander** [comment]
Can you try G4 pre2 and see if you have the same problem?

**Comment by KaiAF** [comment]
If you are still having this problem, send a latest.log, please.
`.minecraft\logs\latest.log`
