### ISSUE TITLE
[Tooltips] No tooltips for Distortion Effects and FOV Effects

### ISSUE THREAD

**Issue by Regnander** [sp614x/optifine#4981]
## Description of Issue
In vanilla we have tooltips for the Distortion Effects (`options.screenEffectScale.tooltip`) and FOV Effects (`options.fovEffectScale.tooltip`) sliders, but they don't show up in the OF settings.

||Distortion Effects|FOV Effects|
|-|-|-|
|Vanilla|![VAN_DIST](https://user-images.githubusercontent.com/17113053/97779827-0a272200-1b81-11eb-9b1a-1356dcd80bc8.png)|![VAN_FOV](https://user-images.githubusercontent.com/17113053/97779826-098e8b80-1b81-11eb-8340-186ab618fa36.png)|
|OptiFine|![OF_DIST](https://user-images.githubusercontent.com/17113053/97779828-0a272200-1b81-11eb-870f-e0db8cf3361c.png)|![OF_FOV](https://user-images.githubusercontent.com/17113053/97779825-08f5f500-1b81-11eb-9ab8-3aa644c5c750.png)|

## Steps to Reproduce
1. Open Options -> Quality
2. Hover mouse on Distortion Effects or FOV Effects

## OptiFine Version
OptiFine_1.16.3_HD_U_G3

## Installation Method
Dropped the JAR file into my "mods" folder

## F3 Debug Screenshot
_Not needed_

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine? No

**Comment by KaiAF** [comment]
No clue when this was added, but apparently it was.
![image](https://user-images.githubusercontent.com/60985521/144898175-56b0fca1-457c-4491-a32a-c9bf447e3685.png)
