### ISSUE TITLE
Add The Migration Cape As A Design For OptiFine Cape

### ISSUE THREAD

**Issue by AmphetaIsAlwaysTaken** [sp614x/optifine#4989]
Account Migration Is Getting Some Hype And I Think Letting People Use It Until The Migration Happens Would Be Awesome!

![Migration Cape](https://user-images.githubusercontent.com/73853073/97914104-59a25500-1d1d-11eb-83c3-1d607b56f35d.png)

**Comment by Cart3r1234** [comment]
This would likely break mojang's eula in some way or another due to the design probably being copyrighted

**Comment by AmphetaIsAlwaysTaken** [comment]
I don't think it would break the eula since this its just a recreation and these are not sold, they are rewarded. banners are a design choice but they are made by mojang

**Comment by IMS212** [comment]
anyway it’s not a good idea, it gives people a cape that’s supposed to be rewarded to players before the migration, making them even more worthless and not knowing who is an player that got it legit and who isn’t.

**Comment by AmphetaIsAlwaysTaken** [comment]
make it only available as a design until early 2021

**Comment by ZenithRogue** [comment]
Yeah, this is certainly not happening. It would violate Mojang ToS in a big way.
