### ISSUE TITLE
[Bug] [1.16.4_pre1] Incorrect Culling Of Dragon Beams & Elder Guardian Effect

### ISSUE THREAD

**Issue by EminGT** [sp614x/optifine#4994]
## Description of Issue
Dragon beams & elder guardian effects get incorrectly removed from rendering when looked at certain angles.

## Steps to Reproduce
Elder Guardian Effect:
1. Do "/particle minecraft:elder_guardian"
2. Notice that it doesn't show up at all unless you turn your head to very specific angles

Dragon Beam:
1. Go to the end
2. Do "/kill @e[type=minecraft:ender_dragon]" to kill the dragon
3. Place 4 end crystals in the fountain like this to initiate the dragon beams
![image](https://user-images.githubusercontent.com/52270338/97975196-caa74280-1dd9-11eb-80b6-5925d433052f.png)
4. Turn your head up to see that beams stop showing up when the fountain isn't in your screen

## OptiFine Version
1.16.4_HD_U_G4_pre1

## Installation Method
Standalone installer.

## F3 Debug Screenshot
![image](https://user-images.githubusercontent.com/52270338/97975597-6cc72a80-1dda-11eb-92d3-def26b41dbfd.png)

## Prior Testing
- Does this happen in Vanilla without OptiFine?
No.

## Additional Information
The fix *should* be as easy as not doing culling on these two things. It won't affect performance since these aren't common stuff.

**Comment by sp614x** [comment]
The particle culling is a Forge feature, it was added with the Forge compatibility.

**Comment by sp614x** [comment]
Fixed, coming in next preview.
