### ISSUE TITLE
[Bug] [1.16.4_pre1] [Shaders] gbuffers_beaconbeam Is Not Being Used

### ISSUE THREAD

**Issue by EminGT** [sp614x/optifine#4995]
## Description of Issue
gbuffers_beaconbeam seems to not work at all.

## Steps to Reproduce
1) Set the color to vec3(1.0, 0.0, 1.0) in gbuffers_beaconbeam
2) Notice that beacon beams are still white even though you just set the color to magenta.

## OptiFine Version
1.16.4_HD_U_G4_pre1

## Installation Method
Standalone installer.

## F3 Debug Screenshot
![image](https://user-images.githubusercontent.com/52270338/97976083-30e09500-1ddb-11eb-9525-e0c99460eca4.png)

**Comment by fayer3** [comment]
I already reported this in #4905
