### ISSUE TITLE
My cape still getting stolen

### ISSUE THREAD

**Issue by ShinkDragon** [sp614x/optifine#4997]
I've been victim of this for a whole year, everytime I recover my cape it gets stolen again and again and I don't know what to do, I don't know if something about the cookies of Chrome or my email... In that case I want to change my email...

I don't really know what's the real problem but I need help because I tried everything.

My minecraft username is "ShinkUwU" if you wanna know.

**Comment by IMS212** [comment]
you should: delete all the cookies from your browser, run a thorough virus scan on your pc, and reset all your passwords (including your email password), someone probably has access to your email.

**Comment by ShinkDragon** [comment]
Username: ShinkUwU

The cape was moved from "ShinkUwU" to "Killer_ss" by the cape owner on 12.11.2020 07:24h.

I did everything you said and still getting stolen...

**Comment by IMS212** [comment]
“By the cape owner”? did you actually donate 10$ to optifine, or did you buy the cape from someone else?

**Comment by ShinkDragon** [comment]
I donated 10$ to the official optifine page.

**Comment by KaiAF** [comment]
Unfortunately optifine doesn't change emails. When you transfer it back, make sure to lock your cape. If its locked no one can move it unless they have log in.

**Comment by ShinkDragon** [comment]
So... when should I lock the cape? Should I move the cape to my MC account first and then lock it or do it both at once? Because when I did that it said "The cape can't be moved because it is locked" but if I unmark that option it let me do it.

**Comment by KaiAF** [comment]
You move it to your account. Then you lock it

**Comment by ZenIsBestWolf** [comment]
If this is still an issue, please contact Support via Discord, Twitter, or Email.
