### ISSUE TITLE
[Bug] [Render Regions] Glass textures glitch across chunk borders

### ISSUE THREAD

**Issue by SimonAltrogge** [sp614x/optifine#4999]
## Description of Issue
Glass glitches across chunk border (also without connected textures). Issue seems to be related to Render Regions, since it disappears once Render Regions is turned off.

## Steps to Reproduce
See screenshot

## OptiFine Version
OptiFine HD U G5 (but also before)

## Installation Method
standalone installer

## Screenshot
![2020-11-03_16 48 10](https://user-images.githubusercontent.com/8720147/98139297-52697b80-1ec4-11eb-8bfe-321e446ef6ef.png)

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine? No

**Comment by KaiAF** [comment]
Seems to be related to #5390. If you think otherwise, let me know.
