### ISSUE TITLE
Forge Compatability

### ISSUE THREAD

**Issue by chrisk123999** [sp614x/optifine#50]
Attempting to run Optifine on a Forge version newer than 1797, results in this crash:
http://pastebin.com/SRAEGDkS
However downgrading Forge to 1797 results in having a very annoying Forge caused crash:
https://github.com/MinecraftForge/MinecraftForge/commit/1d25d9ff493c926735f7aa9016c8eb8676e82900

**Comment by sp614x** [comment]
There are several DynamicLights exceptions:

[21:27:57] [Client thread/ERROR]: Caught exception from DynamicLights_entityClasses
java.lang.IllegalAccessError: tried to access field net.minecraftforge.common.config.Property.comment from class atomicstryker.dynamiclights.client.modules.EntityClassLightSource

**Comment by sp614x** [comment]
For me OptiFine seems to work with Forge #1811.
