### ISSUE TITLE
Overlay CTM, causing texture glitch

### ISSUE THREAD

**Issue by Qmodo** [sp614x/optifine#500]
![2017-02-08_15 00 25](https://cloud.githubusercontent.com/assets/18293675/23183402/e1c58206-f849-11e6-87fc-ff00c1770574.png)
![2017-02-08_15 03 26](https://cloud.githubusercontent.com/assets/18293675/23183405/e6be5a44-f849-11e6-98a9-cc38686ed900.png)
![2017-02-19_18 12 13](https://cloud.githubusercontent.com/assets/18293675/23183413/eb48bab4-f849-11e6-9e1f-a4815074421f.png)

I'm getting these sort of buggy looking textures instead of the textures I am supposed to see on the blocks beside the grass... I can make it go away(until i restart my game) by swapping through the better grass settings. Hit me up if you need anything!

**Comment by sp614x** [comment]
Resource pack, steps to reproduce?

**Comment by Qmodo** [comment]
RP: https://www.dropbox.com/s/0xpwtcf0hfaipyi/Qmodo%20assets%20pack%202.zip?dl=0

Im not sure about steps... All I do is open a world, and look at dirt/stone. As long as the resource pack is loaded, and i dont change my video settings it happens (if i change either of these, i have to relog before it happens again).

**Comment by sp614x** [comment]
Relevant line from the game output:

[WARN]: [OptiFine] No matchBlocks or matchTiles specified: mcpatcher/ctm/1_grass_overlay/grass.properties

The "matchBlock" in "grass.properties" should be "matchBlocks"

**Comment by Qmodo** [comment]
oh, i guess its weird that it worked at all then... Thanks!
