### ISSUE TITLE
[1.16.3] Forge-34.1.42 and below(?) mixin problem

### ISSUE THREAD

**Issue by berkkrkc09** [sp614x/optifine#5002]
## Description of Issue
OptiFine won't let the game launch because of some mixin error And it doesn't happen when OptiFine is NOT installed. I tried with OptiForge too, still the same.

## Steps to Reproduce
1. Launch the game.
2. See the launcher log filled with exceptions.

## OptiFine Version
OptiFine HD U G4.

## Installation Method
OptiFine is installed as a Forge mod.

## Fabric/Forge Version
Forge-34.1.42.

## Other Installed Mods
Modlist: https://pastebin.com/z2uAsyrt

## Log Files/Crash Reports
[2020-11-04-2.log](https://github.com/sp614x/optifine/files/5494017/2020-11-04-2.log)

## Prior Testing
If you've installed using Forge/Fabric:
- Does this happen without other mods installed?  - NO
   - Only OptiFine and Forge - NO
   - Only OptiFine, OptiFabric, and Fabric - I USE FORGE
- Does this happen without any mods at all? - NO
   - Only Forge/Fabric by itself. - NO
- Does this happen in OptiFine standalone? - NO
- Does this happen in Vanilla without OptiFine? - NO
- Have you tried using a binary search to find which mods cause this issue? - YES
   - To find conflicting mods, split your mods into 2 groups (not including OptiFine/OptiFabric, obviously). Remove one group, and test in-game. Keep the group that has the problem, and repeat until no more mods can be removed without the issue disappearing.
   - Does the issue still happen with only the remaining mods installed? YES (but when i seperated mods in half both halves launched without any issue) So i don't know what to write here.

      - Forge/Fabric and remaining mods, without OptiFine (basically all of them)

## Additional Information
I posted a bug report to Forge forum before here(because i thought it's because of mixins) and they told me to launch the game without OptiFine and it launched without any issue. I am very confused. I use Curse client and I have OptiForge installed too: OptiForge-MC1.16.3-0.3.5.

**Comment by jazzmina1** [comment]
I think the version of forge is too new and optifine hasn't created a compatible version yet

**Comment by berkkrkc09** [comment]
I jut tried Forge 34.1.33 / 34 / 35 and unfortunately another error popped up but it is still about mixin.
Log: https://pastebin.com/0GwAYZi4 (this is the error log that 34.1.34 gives me)

**Comment by berkkrkc09** [comment]
Umm... I need some attention. Please? @sp614x

**Comment by sp614x** [comment]
OptiFine G5 for 1.16.3 is compatible with Forge 34.1.42 and should work.

**Comment by berkkrkc09** [comment]
Oh. New version is already out? Sorry. I will be closing this issue now.
