### ISSUE TITLE
games freezes

### ISSUE THREAD

**Issue by agentprime123** [sp614x/optifine#5004]
## Description of Issue
the game starts with 0 fps with optifine and spamming openGL error 1286 (invalid framebuffer operation)

## Steps to Reproduce
i dont have to do anthing just creating a new world or playing an exsisting world makes this problem

## OptiFine Version
OptiFine HD U G4

## Installation Method
i copies optifine to the  mods folder

## Fabric/Forge Version
forge-34.1.35

## Other Installed Mods
first i tried to run optifine with a bunch of mods but then i tried to run only optifine and the problem is still there

**If OptiFine is installed as standalone, remove this section.**

## Log Files/Crash Reports

[latest.log]
https://pastebin.com/EjyLPfxE

## F3 Debug Screenshot

![2020-11-06_10 58 27](https://user-images.githubusercontent.com/73553239/98330014-80170780-201f-11eb-9336-76e77abf30e6.png)

## Prior Testing
If you've installed standalone:
no it only happens when i use optifine

If you've installed using Forge/Fabric:
- Does this happen without other mods installed?  
   - Only OptiFine and Forge
- Does this happen without any mods at all? 
         no
  
- Does this happen in OptiFine standalone? yes
- Does this happen in Vanilla without OptiFine? NO in vanilla i am getting 40 fps
- Have you tried using a binary search to find which mods cause this issue? 
   - To find conflicting mods, split your mods into 2 groups (not including OptiFine/OptiFabric, obviously). Remove one group, and test in-game. Keep the group that has the problem, and repeat until no more mods can be removed without the issue disappearing.
   - Does the issue still happen with only the remaining mods installed?
      -the only mod is optifine
## Additional Information
Here goes any final remarks and everything else that might not fit in the previous sections.

**Comment by KaiAF** [comment]
This could be caused by outdated / broken graphics card drivers. If you are still having this issue, update them, and *if* you are still having the issue, let me know.
