### ISSUE TITLE
[Installer | Feature Request] Allow user to select a minecraft .jar for extraction of optifine .jar

### ISSUE THREAD

**Issue by inf1425** [sp614x/optifine#5005]
Currently, if you ask the installer to extract Optifine to a .jar, it will look in %appdata%\\.minecraft\versions.
If someone is using a launcher such as MultiMC, it becomes very annoying to constantly create a new folder per update, and then move the .jar file.
It would be much easier if the user could just select the Minecraft .jar file that is needed.

**Comment by sp614x** [comment]
The installer works only with the vanilla launcher.
It can't create a profile for any other launcher.

**Comment by inf1425** [comment]
This is not about launcher profiles though. This is a feature request for extraction of the optifine jarmod.
