### ISSUE TITLE
[Bug] VSync not capping at correct framerate

### ISSUE THREAD

**Issue by gojiria** [sp614x/optifine#5009]
## Description of Issue
Vsync capping at 30 fps instead of 60

## Steps to Reproduce
turn VSync on with a laptop with Radeon vega 8 

## OptiFine Version
1.16.4 HD U G5

## Installation Method
Standalone Installer

## F3 Debug Screenshot
![image](https://user-images.githubusercontent.com/70024091/98429605-9ea7ed80-2075-11eb-9ddc-95b3e0dc7334.png)

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
No. It caps at 60 fps in vanilla

**Comment by Lythael** [comment]
I have issue with Optifine vsync too but instead capping to 30 fps or 60 fps (my correct refresh rate) it doesn't cap the framerate at all and ignores GPU framerate cap settings.

Still fixes screen tearing tho.

**Comment by VonifyQF** [comment]
> I have issue with Optifine vsync too but instead capping to 30 fps or 60 fps (my correct refresh rate) it doesn't cap the framerate at all and ignores GPU framerate cap settings.
> 
> Still fixes screen tearing tho.

Same with me, i wanna use VSync to cap my FPS at 75 but still wanna fixe screen tearing. I mean whenever i play minecraft with extreme shaders my PC just gets loud as a jet engine, i dont want that. Is there any solution?

**Comment by sp614x** [comment]
You are running with internal shaders. The integrated GPU probably can't reach 60 FPS with shaders so it falls down to next possible (30FPS). 
VSync is implemented in the graphics drivers, OptiFine can only enable or disable it.
