### ISSUE TITLE
game crash

### ISSUE THREAD

**Issue by azzayu** [sp614x/optifine#5012]
## Description of Issue
my game crashes.

## Steps to Reproduce
this is because of connected textures.
1.have connected textures.
2.move some smooth granite next to some iron bars
3.gg u crashed

## OptiFine Version
preview.Optifine_1.8.9_HD_U_L6_pre1
or just the prerelease of the latest optifine for 1.8.9

## Installation Method
drop jar file into folder

## Fabric/Forge Version
1.8.9-forge1.8.9-11.15.1.2318-1.8.9

## Other Installed Mods
ModTweaker (Patcher-1.4.1 (1.8.9).jar)
  FMLLoadingPlugin (Scrollable Tooltips-1.3 (1.8.9).jar)
  PatcherTweaker (Patcher-1.4.1 (1.8.9).jar)
  SkyblockAddonsLoadingPlugin (SkyblockAddons-1.5.4-for-MC-1.8.9.jar)
  CTJSLoadingPlugin (ctjs-1.3.0-1.8.9.jar)

## Log Files/Crash Reports

[crash-2020-11-08_17.40.12-client.txt](https://github.com/sp614x/optifine/files/5506827/crash-2020-11-08_17.40.12-client.txt)

**DO NOT directly copy and paste log contents here on GitHub.**

## F3 Debug Screenshot
Minecraft's built-in debug screen provides *a lot* of useful information, and should be included even if the issue is not something that can be captured in a still image.

To open this menu, simply press `F3` on your keyboard while in-game. Please ensure the text is easily readable. Depending on the size/resolution of your monitor, you may have to adjust your GUI scale for all text to be completely visible on-screen.

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   - Only OptiFine and Forge
   - Only OptiFine, OptiFabric, and Fabric
- Does this happen without any mods at all?
   - Only Forge/Fabric by itself.
- Does this happen in OptiFine standalone?
- Does this happen in Vanilla without OptiFine?
- Have you tried using a binary search to find which mods cause this issue?
   - To find conflicting mods, split your mods into 2 groups (not including OptiFine/OptiFabric, obviously). Remove one group, and test in-game. Keep the group that has the problem, and repeat until no more mods can be removed without the issue disappearing.
   - Does the issue still happen with only the remaining mods installed?
      - Forge/Fabric and remaining mods, without OptiFine

## Additional Information
Here goes any final remarks and everything else that might not fit in the previous sections.

**Comment by KaiAF** [comment]
Are you still having this issue?
