### ISSUE TITLE
[Discord] Look into adding automatic Discord recognition and overlay

### ISSUE THREAD

**Issue by WhatALegend27** [sp614x/optifine#5014]
Although it may be difficult, it is somewhat annoying that Discord does not automatically detect Optifine and that overlay crashes the game. Whether that is a problem clientside or on Discord's I don't know, but it would be a nice feature to have. 

I know that the Optifine Discord server's FAQ channel says that you don't know why Discord doesn't recognize Optifine and the overlay crashes the game. However, I also don't know if you are looking into these problems, so I decided it wouldn't be a bad idea to put this feature request here.

Whether you look into my request or not, good luck!

**Comment by KaiAF** [comment]
Could be related to this? #2941 #5351
