### ISSUE TITLE
[Category] Short description

### ISSUE THREAD

**Issue by DisPie** [sp614x/optifine#5015]
## Description of Iss
i hit enemy. causes light to go dark. fog and everything else is fine. but all blocks seem to go dark. 
## Steps to Reproduce
1. hit enemy with any shader pack. 
ambient sound v3.0.16

## OptiFine Version
1.12.2 F6 pre

## Installation Method
dropped jar file into the mod folder and letting forge do its thing.

## Fabric/Forge Version
latest forge version 8.0.99.99

## Other Installed Mods
ambient sound v3.0.16
betterburning
betterfoliage
betterfps
creativecore
dynamicsourroundigs
forgelin
mobends
orelib
phosphor
placebo
preview  optinfe 1.12.2 hd u f6 pre1
shouldersurfing
toast+control
vanillafix
wynntills

**Comment by KaiAF** [comment]
This is a really old GitHub issue, sorry about no response. If you are still having any issues, let me know and I will re-open this. But this could have been fixed in the latest update for 1.12.2
