### ISSUE TITLE
Players become invisible when you look at them up close at around there name tag leavel

### ISSUE THREAD

**Issue by WildAshYT** [sp614x/optifine#5018]
I was sneaking up to someone on my server and they turned invisible i did this yesterday with an older optifine and it was fine but now there disappearing wen at a -69 around angel.
(was not able to keep on doing it i think only when its day maybe

1.16.4 hd u g5

fabric 0.10.6 build 2.14 1.16.4

dynamic fps 1.2.1
fabric api 0.25.1 build 416 - 1.16
modmenu 1.14.6 build 31
optifabric 1.8.0
shulkerboxtooltip 2.2.1 1.16.3

Not sure if it's only in optifine don't have a chance to test sorry but just downloaded the new one.

this entire thing might not be an issue at all just me being dumb.

**Comment by WildAshYT** [comment]
So doing so more stuff today i see that there is an issue 5016 about mobs so yes this is with mobs when you lob at the entity in a way and at a time of day i thing they become invisible (when i turn on hit boxs i dont see it at all)

**Comment by Jiingy** [comment]
Old issue, very vague.
