### ISSUE TITLE
Compatibility Issues&Language Missing in 1.7.10 D7 pre

### ISSUE THREAD

**Issue by HeartyYF** [sp614x/optifine#502]
![ow 7 pabyc4tz0m5 8 4 0j](https://cloud.githubusercontent.com/assets/17660052/23205110/b332c5ae-f923-11e6-899b-3e16e41632a9.png)
![v4 e0 mq8u7m8_ z l4 99](https://cloud.githubusercontent.com/assets/17660052/23205112/b33aa026-f923-11e6-9250-27da1782da0c.png)
![y g 7h fs42ddwc k q f](https://cloud.githubusercontent.com/assets/17660052/23205111/b33a7c0e-f923-11e6-8074-64ca7e52d4e1.png)
![w 2r5zr ufk chyc7474ckc](https://cloud.githubusercontent.com/assets/17660052/23205113/b33b39d2-f923-11e6-909b-e45c1cc65c65.png)
![bd5 9a5tt27 5ucsjeo736x](https://cloud.githubusercontent.com/assets/17660052/23205114/b33b9116-f923-11e6-96e0-7c9eee4a480c.png)
![w bu tjtlx t 9py7 6 wo](https://cloud.githubusercontent.com/assets/17660052/23205115/b343d4c0-f923-11e6-85a8-8faa55af2db9.png)

Crash with Fastcraft 1.23:
[crash-2017-02-22_16.53.45-client.txt](http://pastebin.com/v9FcZnZP)
Crash with Waila 1.5.10:
[crash-2017-02-22_16.55.21-client.txt](http://pastebin.com/Q810wUUr)

**Comment by HeartyYF** [comment]
PS:
I'm glad that OptiFine 1.7.10 finally began to use language files, because we were modifying jar file so that more can use it before...
And when I'm using OptiFine 1.7.10 D6, the crashes didn't occur.

**Comment by sp614x** [comment]
Waila is working for me:

![image](https://cloud.githubusercontent.com/assets/16635441/23213924/279c0d2c-f90d-11e6-8d3a-a435700669f8.png)

also with other languages:

![image](https://cloud.githubusercontent.com/assets/16635441/23214018/84619ef0-f90d-11e6-8887-4f69b1f095d7.png)

**Comment by sp614x** [comment]
Fastcraft seems to be crashing when ASM patching the base classes. Optifine can do nothing about it.

**Comment by sp614x** [comment]
The Waila crash happens here: https://github.com/MinecraftForge/FML/blob/master/src/main/java/net/minecraftforge/fml/client/FMLClientHandler.java#L622
This is part of the normal mod initialization and there are no OptiFine classes involved. No idea why the LanguageManager or the current language can be NULL.

**Comment by HeartyYF** [comment]
I think I know why when I'm using Waila it crashes, that's becuase in my environment there aren't assets...Now this doesn't happen anymore...
