### ISSUE TITLE
[Suggestion] Make nylium connect with better grass

### ISSUE THREAD

**Issue by vinnyg0621** [sp614x/optifine#5021]
I'd really like to see crimson and warped nylium have the top texture on the sides with better grass
![2020-11-10_19 14 35](https://user-images.githubusercontent.com/57818441/98760972-47619000-2389-11eb-9300-261aec28f2f8.png)

**Comment by Regnander** [comment]
#4212

**Comment by KaiAF** [comment]
Closing this as it's a duplicate of #4212.
