### ISSUE TITLE
[1.16.3 U G5 + FORGE 34.1.42] Using tools on any block causes the block break animation to cover the screen.

### ISSUE THREAD

**Issue by 247Tossing** [sp614x/optifine#5023]
Whenever i use a tool on a block while using any shader it covers the screen in whatever block break animation is being used. This does not happen if i try to break something barehanded.

This is the latest log file i have to attatch.
[latest.log](https://github.com/sp614x/optifine/files/5531722/latest.log)

**Comment by seanimusprime** [comment]
Sounds like you have CoFH core mod. Open "cofh_core-client.toml" config and set ""Render Area Effect Block Breaking" to false

https://github.com/sp614x/optifine/issues/4088

**Comment by 247Tossing** [comment]
Looks like i did and didn't realize it. I thought i didn't install COFH core. problem solved.
