### ISSUE TITLE
[Shaders] Option to render particles before "deferred" programs

### ISSUE THREAD

**Issue by sonicether** [sp614x/optifine#5027]
Depending on how each shader author wants to handle particles, it would be useful to be able to choose whether particles are rendered after deferred programs, with water and other transparent objects (as is the latest functionality), or before deferred programs, with opaque objects (as was the case for versions of OptiFine before Minecraft 1.15).

My own shader work requires that particles be rendered before deferred programs to properly light them. However, I do see how rendering particles after deferred programs could be useful to other shader authors.

**Comment by sp614x** [comment]
Added property `particles.before.deferred`.
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.properties#L82
