### ISSUE TITLE
[Crash] OptiFine crashes on launch.

### ISSUE THREAD

**Issue by JustMatteh** [sp614x/optifine#5029]
## Description of Issue
The game doesn't start with Optifine installed

## Steps to Reproduce
1. Just starting the game and then it crashes.

## OptiFine Version
OptiFine_1.16.3_HD_U_G5

## Installation Method
I dropped the Optifine jar in it.

## Fabric/Forge Version
Forge 34.1.42

## Other Installed Mods

https://pastebin.com/kwNb3CLq

## Log Files/Crash Reports
Any relevant log files. Drag and drop text files here to upload to GitHub directly, OR upload the complete contents to Pastebin. 

https://pastebin.com/4rv7tQW3

## F3 Debug Screenshot
Minecraft's built-in debug screen provides *a lot* of useful information, and should be included even if the issue is not something that can be captured in a still image.

To open this menu, simply press `F3` on your keyboard while in-game. Please ensure the text is easily readable. Depending on the size/resolution of your monitor, you may have to adjust your GUI scale for all text to be completely visible on-screen.

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine? -- No it doesn't, it works just fine...

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   - Only OptiFine and Forge -- No
   - Only OptiFine, OptiFabric, and Fabric -- No
- Does this happen without any mods at all?
   - Only Forge/Fabric by itself. -- No
- Does this happen in OptiFine standalone? -- No
- Does this happen in Vanilla without OptiFine? -- No
- Have you tried using a binary search to find which mods cause this issue?
   - To find conflicting mods, split your mods into 2 groups (not including OptiFine/OptiFabric, obviously). Remove one group, and test in-game. Keep the group that has the problem, and repeat until no more mods can be removed without the issue disappearing.
   - Does the issue still happen with only the remaining mods installed?
      - Forge/Fabric and remaining mods, without OptiFine

-- Yes and nothing changed... It works with client sided mods only

## Additional Information
Here goes any final remarks and everything else that might not fit in the previous sections.

**Comment by KaiAF** [comment]
Are you still having this issue?

**Comment by KaiAF** [comment]
No response from author, assume its resolved.
