### ISSUE TITLE
A little help here please

### ISSUE THREAD

**Issue by KuroNekoGin** [sp614x/optifine#5032]
I ran the SEUS renewed shaders pack and here's what happened: the message "error 1282" was showing up all the time, the sky was entirely black but the sun was there still, there was no shades or reflections, like the default minecraft.
The thing is: my PC is pretty trashy in terms of graphics (I cant play Valorant, Minecraft Dungeons and Overwatch) so idk if this is a fixable error or just my PC again. Here are the properties btw, Intel(R) Core(TM) i3-2100 CPU @ 3.10GHz, can it even load shaders?

**Comment by DeerUwU** [comment]
when I still played on a laptop, most shaders refused to load aswell. might be lack of feature support from your gpu, if your pc even has one.

**Comment by KaiAF** [comment]
This could have been caused by outdated drivers. Are you still having this issue?

**Comment by KaiAF** [comment]
No response from author, assume its resolved.
