### ISSUE TITLE
[Shader] Add the FOV uniform

### ISSUE THREAD

**Issue by GeForceLegend** [sp614x/optifine#5036]
Requested Feature: Add an uniform to get FOV setting. 
Because of MC-161150, ambient occlusion of quaope emitting blocks will darken skylight level. I tried to fix it by dfdx and dfdy of skylight, and it works almost perfectly with default FOV (70). But if I change the FOV setting, my skylight fixing wont work correctly. If there is an uniform that can import FOV, I can make the shader adjusts the fixing itself, but not need an other shader option that must be adjusted by users.

**Comment by ColdIce1605** [comment]
You can calculate the fov though I forgot how you can go to ebin's repo to find out how but it still would be nice to have.
