### ISSUE TITLE
Optifine not being able to tell wether im right clicking or left clicking on mac.

### ISSUE THREAD

**Issue by ascenxded** [sp614x/optifine#5037]
Sometimes when I left click on optifine, optifine will mistake it as a right click for some reason. I am on Mac OS version 11.01 big sur. Help!!!11

**Comment by Elestrat** [comment]
It's not Optifine, it's probably your Apple Magic Mouse.

**Comment by ascenxded** [comment]
> It's not Optifine, it's probably your Apple Magic Mouse.

i have a normal mouse

**Comment by Elestrat** [comment]
If so, then I don't think the problem has to do with Optifine.

**Comment by ZenIsBestWolf** [comment]
We need more details about this issue, and are you sure this only happens on OF?

**Comment by KaiAF** [comment]
No response from author, assume its resolved.
