### ISSUE TITLE
[Extreme Bug 15.2] Entities shadow duplicate, freeze, and become persistent after player respawn. 

### ISSUE THREAD

**Issue by Churchexe** [sp614x/optifine#5039]
## Description of Issue
In a singleplayer world (have not yet tested multiplayer due to a lack of available hardware) when the player dies entities have a chance to "shadow duplicate" where a phantom version of that entity as it was at time of respawn is visible without existing. Seemingly at random this shadow duplicate will disappear but if you then kill the real mob that created it the body of that mob will never despawn. 

## Steps to Reproduce
1 : create a 1.15.2 instance with forge version 31.2.45 (in gdlauncher if it matters, I doubt it but I figured I would list it just in case) 
2 : put optifine version preview_OptiFine_1.15.2_HD_U_G5_pre1.jar in the mods folder of that instance
3 : boot game
4 : start singleplayer creative world
5 : give yourself a sword and spawn eggs for a preferably hostile mob and turn on keep inventory (this is mostly just for ease of testing and I do not believe it has any impact on the bug itself)
6 : go into survival, spawn the mob, swipe at it once, (to agro it, once again, I do not believe this has any impact on the bug itself) let it hit you and kill you.
7 : respawn and return to the location where the mod was and there is a good chance you will see two mobs standing in the same place. Once the real mob sees you it will walk out of the "shadow duplicate" and try to kill you again.
8 : try fighting off the mob; at some point during the fight the shadow dupe typically goes invisible/deletes itself/you get the idea and after you kill the real mob its corpse never despawns.

## OptiFine Version
optifine version preview_OptiFine_1.15.2_HD_U_G5_pre1.jar

## Installation Method
Forge installation (put it, and it alone, in mods folder)

## Fabric/Forge Version
31.2.45 

## Other Installed Mods
This occurs standalone

## Log Files/Crash Reports
https://pastebin.com/iyKfGuCi

## F3 Debug Screenshot #Yes my rig is very crap, I asked my friend to test it on his stronger rig and he said he had similar issues although I don't know how valid those are since I did not personally see them. (I believe he has an Nvidia 1080 8gm ram, etc, mid-high teir computer)
![image](https://user-images.githubusercontent.com/39103942/99278326-e577af00-27fc-11eb-8b72-538475028e77.png)

## Prior Testing
In forge with no mods it does not happen.
In forge with optifine alone it does happen. 
In complete Vanilla it does not happen.
Only tested on forge and occurs with optifine alone.
As stated, a forge instance with no mods does not have this issue. 
(most other sections of Prior Testing all appear to just be reiterations of the above 5 lines.)

## Additional Information
Similar effects occur with items however I don't really know how to better test that. From the death cam it appears the big only occurs on respawn and not on death. (in my initial testing it also appears clear that the entity does not despawn even after the chunk unloads however I have not done more testing with this)
Note : This only seems to effect entities alive WHEN the player hits respawn

**Comment by Komerad** [comment]
Apologies if there's a format to follow,

I'm pretty sure I have the same issue, although I would describe it differently. With only `OptiFine_1.15.2_HD_U_G5_pre1` installed in mods with Forge version 31.2.47 this bug occurs for me, and I'm assuming others. Like the OP, I have not tested in MP. Not sure if 1.15 is still a huge concern, but I definitely would have use for a stable version.

Basically, when the player dies mobs and or items can have "duplicates" appear, that are not actually functionable or do anything. IE: The "fake" items/mobs will not animate normally and will just glitch in place. I think a side effect is FPS loss and stuttering, but I can't be sure it's not from something else with my setup at this point. 

Steps to reproduce:
 - Start a new Singleplayer game (Worldgen, etc do not matter, but bonus chest/cheats makes it easier and more apparent)
 - Grab items from the bonus chest
 - Use the `/kill` command to suicide
 - Dropped items will be duplicated, but cannot be grabbed.

Here's also a video of it (F3 debug is shown, along with installed mods, and video settings):
https://youtu.be/FoR5GUDEmtA

**Comment by martinsebik** [comment]
It happens with both mobs and items. The issue isn't present in g1 pre30.

**Comment by sp614x** [comment]
Also happens without Forge.

**Comment by sp614x** [comment]
Fixed, coming in next preview.
