### ISSUE TITLE
OptiFine overwriting BoPs leaf colors

### ISSUE THREAD

**Issue by Reael** [sp614x/optifine#5041]
## Description of Issue
Biomes O'Plenty adds a bunch of new natural things. The thing is, as soon as OptiFine is installed, all the pink and white cherry leaves are lime green. I already reported this to BoP but they can't do anything about it since OptiFine seems to overwrite some colormap properties

## Steps to Reproduce
1. Put BoP for 1.16.4 in my mod folder 
2. Put OptiFine in my mod folder or install it via double-click
3. Create game. Doesn't even have to be the BoP world built, one can just plant a cherry sapling and mature it and it will have green leaves.

## OptiFine Version
OptiFine_1.16.4_HD_U_G5

## Installation Method
Tried both, neither did chang anything

## Fabric/Forge Version
1.16.4

## Other Installed Mods
Technically I have a lot of mods but I removed them all after BoP pinpointed me to OptiFine being the culprit so it's only Forge, OptiFine, and Biomes O'Plenty.

## F3 Debug Screenshot
https://i.ibb.co/zmPnzfV/screeny.png

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
No

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   - Only OptiFine and Forge
And BoP, yes. Without BoP there are no special trees it could affect so if it's ONLY OptiFine and Forge and no other mod the answer is no, because... it's a problem with BoP.

- Does this happen without any mods at all?
   - Only Forge/Fabric by itself.
No

- Does this happen in OptiFine standalone?
Yes (with BoP)

- Does this happen in Vanilla without OptiFine?
Only BoP without OptiFine - No.

## Additional Information
First, this issue occurs with and without resourcepack, I just tried to solve it with a resourcepack, so don't tell me to disable it. I did.
I TRIED my hardest to adjust the colormaps and I guess I'm just too dumb to understand how to alter them in 1.16.4. Everything I did back for previous Versions doesn't work anymore. I can load completely pink colormaps into my resource pack to try. Every colormap and colorgrid is neon pink in every single folder I could find, mc vanilla folder, BoP folder, OptiFine folder, and nothing affects my game the slightest. So I might very well be able to sort this problem out if I know how to set up a resourcepack for 1.16.4.
(I'm sorry to brag but after 6 hours of searching a dummy friendly tutorial I'm just pissed by now and devastated and I wanna cry... I'm even too stupid to understand where the fluff this is supposed to be (assets/minecraft/optifine/colormap/custom/grass.png). What's this asset folder? Where does it start? Is it in the resourcepack like back in the days, is it in the OptiFine file, are there folders that should generate but just don't? How do I get there. Is it
appdata/roaming/.minecraft/asset/minecraft (there isn't even a minecraft folder in asset, am I supposed to make one?) or is it
appdata/roaming/.minecraft/resourcepack/asset/minecraft (like we used to do it for 1.12. and I believe this still worked for 1.15.) or is it
appdata/roaming/.minecraft/mods/OptiFine_1.16.4_HD_U_G5.jar/assets/minecraft
I wish I needn't fix it myself self but I would do it if I knew where to even start because /asset/minecraft is just a path that has like 3 or 4 options, and I dunno which one we are talking about. So if this issue can't be solved on OptiFines side at least point me to a complete-dummy-friendly-tutorial and I'll figure something out myself. Like okay, all the descriptions you provide are great but if I can't put it into the right folder to start with there is no point in it.

**Comment by hootaran** [comment]
I can confirm I have the same issue. Tried enabling and disabling swamp colors, custom colors, deleted and changed the color properties file in the resource pack and then BOP’s .jar file itself....nothing. Did the same thing as above and tried it out on forge without optifine loaded; colors were fine. All the BOP leaves are following the biome-specific colors when they shouldn’t. 

For comparison, here is what the leaves should look like compared to the picture in the link above:
![C31D0FE5-C9CC-4B83-B157-D3E0757B4131](https://user-images.githubusercontent.com/55056693/99989648-dd7db900-2d80-11eb-9635-e9b3b1b5299f.jpeg)

**Comment by KaiAF** [comment]
Is this still an issue? Looks like this could have been fixed already.

**Comment by vediis** [comment]
This is still an issue with Minecraft 1.16.5 OptiFine HD U G8 and BoP, but **turning Swamp Colors ON and Custom Colors OFF fixes this!!!** Posting this for anyone who was still struggling with this.

**Comment by sp614x** [comment]
Fixed in next 1.20.1 preview.
