### ISSUE TITLE
[Bug Report] Partial Resource Pack Loading?

### ISSUE THREAD

**Issue by Axylons** [sp614x/optifine#5045]
I am having an issue where some of my newer resource pack files are not loading or working properly. I have double checked formatting, .png file sizes, etc. I have not noticed anything that would cause this in the files.

Assume the .png files are properly named and are 64x64. For the sake of this, File A is the issue, and File B is the working one. 

Path: AppData\Roaming\\.minecraft\resourcepacks\ResourcePackName\assets\minecraft\optifine\cit\items

File A contains: 
type=item
items=minecraft:ender_chest
nbt.display.Name=ipattern:*christmas crate*

File B contains:
type=item
items=minecraft:cookie
nbt.display.Name=ipattern:*candy cane*

If you notice anything I am doing wrong, please please please tell me!

EDIT: Apparently the * around the two item names italicized them, but they are there.

**Comment by Regnander** [comment]
I cannot see anything wrong with the code you posted. Can you upload the resource pack?

**Comment by Regnander** [comment]
Regarding the disappearing *, try surrounding any code with ``` like this:
```
type=item
items=minecraft:ender_chest
nbt.display.Name=ipattern:_christmas crate_
```

```
type=item
items=minecraft:cookie
nbt.display.Name=ipattern:_candy cane_
```

**Comment by Axylons** [comment]
[Elements.zip](https://github.com/sp614x/optifine/files/5574199/Elements.zip)

**Comment by Axylons** [comment]
Thanks for the time Regnander. Weirdly, the Candy Cane Sword, Candy Cane Pickaxe, and Santa Hat were not working previously but they just decided to magically work today. I am using the latest version of Optifine, if that is relevant.

**Comment by Regnander** [comment]
No problem. #4973 has a similar problem where there the CIT also suddenly started working, so it's a known bug.

I wasn't able to get either the Cookie or the Ender Chest to work myself, but I'm glad it worked out for you. If you don't have any questions you can close this issue.

**Comment by KaiAF** [comment]
Related to #4973? Closing as there hasn't been any response from the Author.
