### ISSUE TITLE
[BUG] Extracting not possible

### ISSUE THREAD

**Issue by Gandalf360one** [sp614x/optifine#5048]
## Description of Issue
I want to extract and not install Optifine with the installer but I always get the same message like when I try to install it.

## Steps to Reproduce
1. What do you do... 
2. ...to find this bug?
Downloading Optifine from the offically hompage.
Hitting extract.
Getting the same message like when you hit install.

## OptiFine Version
1.16.4_HD_UG_5

## Installation Method
Want to extract Optifine so I can import it to MultiMC

**Comment by KaiAF** [comment]
What is the error that it gives?

**Comment by Gandalf360one** [comment]
Cannot find Minecraft 1.16.4
You must download and start Minecraft 1.16.4 once in the official launcher

**Comment by KaiAF** [comment]
> Cannot find Minecraft 1.16.4
> You must download and start Minecraft 1.16.4 once in the official launcher

You need to install Minecraft on the official launcher. There is no other way of bypassing this. As far as I know.

**Comment by Gandalf360one** [comment]
Yes when I want to install it BUT I want to extract it and normally when you extract it you just get it and it does not say you that you need to install it

**Comment by KaiAF** [comment]
Closing this as it seems like no further issues happened.

**Comment by LarveyOfficial** [comment]
This is still an issue, Even if Minecraft is installed properly with the official launcher, you cannot extract the Optifine.jar
