### ISSUE TITLE
Optifine HD U G5 pre1 not fully compatible with Minecolonies (missing textures/models/item picture)

### ISSUE THREAD

**Issue by GodGMN** [sp614x/optifine#5049]
As said in the title, the block textures, inventory textures and hand textures all disappear.

In the inventory and hand it appears invisible. In the world, it appears with the typical checkerboard pattern.

Screenshot with the Optifine version and the item on it:
![image](https://user-images.githubusercontent.com/48182403/99719531-b2f3dd80-2aac-11eb-9f23-4aea09fa27bc.png)

The block itself:
![image](https://user-images.githubusercontent.com/48182403/99719567-c1da9000-2aac-11eb-91be-1289be9fd1b1.png)

Without optifine: 
![image](https://user-images.githubusercontent.com/48182403/99719585-c99a3480-2aac-11eb-8bc7-519b5c46a748.png)

**Comment by KaiAF** [comment]
Are you still having any issues? Could have sworn this could have been fixed.
