### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by rectiscoool5** [sp614x/optifine#5054]
So I'm currently on a windows 7 and it is out of service I use my phone to transfer files to my pc for minecraft I did the same with optifine and my .jar files are messed up they take my to internet explorer (which needs internet) and my internet only works for some applications I would like to know how to fix this or how to download optifine asap please and thank you

**Comment by Cart3r1234** [comment]
Run the program jarfix, which can be found at https://johann.loefflmann.net/downloads/jarfix.exe

**Comment by SpookyGrian** [comment]
you can right click the .jar, hit open with, and select another program. Then you hit java and select Open by default.

**Comment by rectiscoool5** [comment]
> Run the program jarfix, which can be found at https://johann.loefflmann.net/downloads/jarfix.exe.
> It will fix the file association and stop the jars from opening with internet explorer

Thank you this fixed it your amazing my dude
