### ISSUE TITLE
[Bug?] I can't find Optifine 1.16 on the website

### ISSUE THREAD

**Issue by Arch201** [sp614x/optifine#5055]
## Description of Issue
I tried to find Optifine 1.16 on the website, but I couldn't find 1.16. I could only see 1.16.1 or higher versions. Is it deleted?

**Comment by embeddedt** [comment]
I'm not sure that OptiFine was ever released for 1.16.0. In any case, no one is using this version on servers and there have been lots of fixes in newer 1.16 releases, so there is no reason to use that version.

**Comment by KaiAF** [comment]
1.16.0 was not released on the site, probably won't.
