### ISSUE TITLE
please update optifine.

### ISSUE THREAD

**Issue by Kuktar** [sp614x/optifine#5062]
im using the shadder pack continuum and the devs literaly put a message when minecraft loads that reads the following.

The optifine devs only release a non preview/beta version every 10 months so please go to this link (links to this page) to request them to update.

i thought it was funny but in case it matters. also thank you optifine is awesome and it makes minecraft worthty of my lifetime spent.

**Comment by KaiAF** [comment]
Hello, sp614x updates OptiFine when he can. He also doesn't update OptiFine for preview versions.

But if you are willing to, can you provide a screenshot of the continuum devs saying to report a bug telling people to update OptiFine?
