### ISSUE TITLE
FPS decreasing over time with shaders/in F5/in inventory

### ISSUE THREAD

**Issue by Shimor1** [sp614x/optifine#5069]
Without shaders I get 100fps easily, but when I put them on it goes from 70fps to 20fps in ~10 minutes. It used to work well.
Specs :
- Ryzen 7 2700
- 2x8gb ram 3200mhz
- RTX 2070
Temps are very good, I allocated 6-8gb of ram for mc. I use Forge 1.16.1 and the last optifine update

**Comment by Shimor1** [comment]
No way to up my post ?

**Comment by HiItsDevin** [comment]
Try allocating just 4GB of RAM, and see if anything changes?

**Comment by ZenithRogue** [comment]
What shaders are you using?

**Comment by Shimor1** [comment]
Hi,
I couldn't test with 4gb of ram bc I had exams to study, I'll test asap. I use the last version of BSL shaders

**Comment by VoidCortech** [comment]
You have the literal exact same system as me and this also happens with me

**Comment by Shimor1** [comment]
> You have the literal exact same system as me and this also happens with me

That's weird, what NVIDIA Drivers are you using ?

**Comment by VoidCortech** [comment]
the most up to date drivers and I think the problem is just that your pc fills up with lots of clutter over time and start up processes take up precious resources for your gpu so I think closing any startup services/programs should fix the problem in theory

**Comment by Shimor1** [comment]
> Try allocating just 4GB of RAM, and see if anything changes?

I tried this weekend, didn't fix it

**Comment by Shimor1** [comment]
Btw I just switched to 1.16.4 and I have the same problem

**Comment by sp614x** [comment]
What is your render distance?

**Comment by Shimor1** [comment]
It used to be 12 chuncks but it does the same thing at 6

**Comment by Shimor1** [comment]
Forgot to say that I have the same problem when in F5, when launching the game I have 100fps but after a few minutes I'm more at 40-30fps

**Comment by Shimor1** [comment]
Please help, it's so annoying...

**Comment by Shimor1** [comment]
Sorry for the spam but I realized that I didn't mention something.
When playing with shaders the amount of ram used is very strange, it increases from ~5.5gb to ~9.5gb (the video was taken when I allocated 12gb of ram, since I decreased that to 8, 6 or 4gb) after reaching 9.5 there's a lag spike and it starts again.
Video : https://1drv.ms/u/s!AqZOXwVsadYSg44NI2QWZnmVHFJlfQ?e=J4TntW

**Comment by TerminalHash** [comment]
The answers do not give any benefit at all - there is no problem in the RAM or third-party load, these are problems of the very bad code of the optifein itself. Top-end computer and such lags? I don’t believe that Optifine doesn’t reduce performance. Especially considering that versions up to 1.12-1.16 just fly with shaders on such computers and the weakest ones. 
Also, I am very interested in the answer of the developer himself. Although I think it will be " Won't Fix, upgrade PC/Make a barrel/Walk away.

**Comment by TerminalHash** [comment]
Already, I think, more than one user of both weak computers and powerful ones noticed that performance on modern versions (as opposed to 1.7.10) with Optifine and with shaders goes nowhere, but everyone yells (especially on Reddit) that this is good, fit mod and don't want to admit the obvious. It is high time to rewrite renders from scratch and with the highest quality, and not drag heaps of rudiments from hoary antiquity.

**Comment by TerminalHash** [comment]
Also, the render distance has nothing to do with it - it does, yes, but the performance equally drops to the same values and it doesn't matter which shader is in power - even the weakest, even the most powerful. If this mod is really well written - why is the performance artificially lowered ON TOP COMPUTER CONFIGURATION ?!

**Comment by Shimor1** [comment]
Despite its flaws I can't play without Optifine tho, I donated money when I played on 1.8.8. I'm so sad it doesn't work very well :(

**Comment by Shimor1** [comment]
Hi,
I don't think it'll be fixed but please help me. It really annoys me and I'm not the only one in this case

**Comment by Shimor1** [comment]
Hi,
I'd really appreciate some help. This issue is still not fixed in 1.16.5 and it's becoming unplayable even without shaders because my inventory would go from 140fps to 20-10fps in an hour

**Comment by sp614x** [comment]
If you get 100 FPS without shaders and 20 FPS with shaders, then it is normal. Shaders usually decrease the FPS significantly.
Why are you getting only 100 FPS without shaders on Ryzen 7 with RTX 2070. I would expect 300+ on this hardware with 12 chunks render distance.
Can you post a F3 screenshot?

**Comment by Shimor1** [comment]
I'll take a screenshot for you

But the problem is not the fps with shaders, it's the decreasing of fps over time. Without any shaders I'm constantly at 144fps (limited by my monitor), with shaders I used to be at a constant 80fps. Since a few days before I made this thread, every time I play my fps will decrease over time but only when in F5, in an inventory, or with shaders.

I'll record my game a bit at the moment when I join my world and then 1h later because I really can't explain it properly

**Comment by Shimor1** [comment]
Hi,
I recorded this yesterday, while recording I lose ~20fps and I'm in a room full of complex modded blocks, that's why I don't always get 144fps 
https://1drv.ms/u/s!AqZOXwVsadYSg70TAxKsyh5SuMF5rQ?e=ZllsuQ

**Comment by sp614x** [comment]
This is Badlion, not OptiFine.
Can you reproduce it with OptiFine only (standalone)?

**Comment by Shimor1** [comment]
It's not Badlion, it's just my screenrecording software that names every mc version Badlion but in the F3 menu it's written Forge 1.16.5

**Comment by sp614x** [comment]
There are 144 other mods installed.
Can you reproduce it with OptiFine only, no other mods?

**Comment by Shimor1** [comment]
I managed to isolate a mod that caused problems with Optifine, I updated it and reinstalled Optifine. Everything works now !
