### ISSUE TITLE
Contact Owner

### ISSUE THREAD

**Issue by mastergberry** [sp614x/optifine#507]
Hey. I have been trying to reach out to you via email by the email on your website. I sent an original email on January 21st and a followup on February 10th. Would it be possible to get in touch with you?

My email is adam [at] badlion [dot] net

Thanks.

**Comment by Tsoccerguy3** [comment]
This is Really !!! , the wrong place to deal with this. For Optifine Bug issues Only .

**Comment by mastergberry** [comment]
I am very aware that this is the wrong area, but when the email for contacting the owner is giving me no results for over a month...gotta get creative lol

**Comment by sp614x** [comment]
Response sent to adam [at] badlion [dot] net

**Comment by ehhthing** [comment]
Hello. I have also attempted to contact you via email, could you please respond to me? My email was sent just yesterday, but I have attempted to contact you before and never got a response. Just search for Larry.

Thanks.
