### ISSUE TITLE
[minecraft v 1.12.2 - Forge #2854] Game crashes on startup

### ISSUE THREAD

**Issue by Derpkovsky** [sp614x/optifine#5074]
I'm trying to play on a server with a bunch of mods, but only when the Optifine file is in the mod folder, the game crashes.
Crash report is attached

[crash-2020-11-30_12.14.09-client.txt](https://github.com/sp614x/optifine/files/5615612/crash-2020-11-30_12.14.09-client.txt)

**Comment by KaiAF** [comment]
Are you still having this issue?

**Comment by Derpkovsky** [comment]
I'm not sure. When I was having this issue, i found a workaround (I think it had something to do with it not working with other mods?)
But it's been a while since i've played minecraft, so i couldn't tell you.

________________________________
Van: Iris ***@***.***>
Verzonden: zaterdag 27 maart 2021 19:56
Aan: sp614x/optifine ***@***.***>
CC: Derpkovsky ***@***.***>; Author ***@***.***>
Onderwerp: Re: [sp614x/optifine] [minecraft v 1.12.2 - Forge #2854] Game crashes on startup (#5074)


Are you still having this issue?

**Comment by KaiAF** [comment]
Closing this as it seems like it's not an issue anymore.
