### ISSUE TITLE
Entering cinematic camera, then holding zoom and then pressing cinematic camera keeps cinematic camera movement even with normal HUD

### ISSUE THREAD

**Issue by enyoukai** [sp614x/optifine#5075]
Version OptiFine HD U G5

How to reproduce:
Tap key for cinematic camera
Hold zoom button
While still holding zoom, press key for cinematic camera again
Game now has normal HUD but still has cinematic camera movement. Can only be fixed by repeating the same steps.

**Comment by KaiAF** [comment]
I don't think this is a bug / Issue. This I believe is intentional as when you zoom in, it just enables the cinematic camera. So pressing the keybind just disables it. If I'm wrong, let me know.
