### ISSUE TITLE
[BUG] Anti-Aliasing Causing Problems (#1 - Causes Upside-Down Recordings)

### ISSUE THREAD

**Issue by Archeol** [sp614x/optifine#5076]
## Description of Issue
Turning on Anti-Aliasing (I've only used 2x) results in recordings (I've used OBS and Overwolf's Outplayed) of the game being upside-down; however, the mouse cursor is still upright and moves accurately.

## Steps to Reproduce
Download 1.8.9 versions and turn on anti-aliasing then record.

## OptiFine Version
1.8.9 U L5
1.8.9 U L6 pre1
^ (Only ones I've used)

## Installation Method
Standalone (no dragging into mod folders)

## Log Files/Crash Reports
Not sure if relevant, but here is the Log File
[latest.log](https://github.com/sp614x/optifine/files/5619277/latest.log)

**DO NOT directly copy and paste log contents here on GitHub.**

## F3 Debug Screenshot
![image](https://user-images.githubusercontent.com/46249833/100676865-c1a58480-3337-11eb-8c9e-bd0fc0a027a1.png)

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
Nope, it does not.

## Additional Information
Here goes any final remarks and everything else that might not fit in the previous sections.

**Comment by sp614x** [comment]
No idea what OBS and Overwolf's Outplayed are using to record when AA is enabled.
Can't be fixed by OptiFine.
