### ISSUE TITLE
 (Bug) Textures breaking when bold format codes are used

### ISSUE THREAD

**Issue by Endlesskeks** [sp614x/optifine#5078]
## Description of Issue
Updated to OptiFine for mc 1.16 recently, and items that had bold names broke.

## Steps to Reproduce
The properties file links to textures this way:
nbt.display.Name=ipattern:*Queen*Strategy*

This is how the item looks:
![unknown](https://user-images.githubusercontent.com/75287838/100690797-9b0f3a00-3387-11eb-8396-2eae06ec6c9e.png)

## OptiFine Version
OptiFine HD U G3 for 1.16.3

## F3 Debug Screenshot
![New2](https://user-images.githubusercontent.com/75287838/100691575-4cfb3600-3389-11eb-9a99-94494494324c.png)

**Comment by Endlesskeks** [comment]
We are using Bold Format Codes in all our custom Items, so none of them are Textured anymore. I think it might be an easy fix for you guys. Hope to hear from you soon. Lg Endlesskeks.

**Comment by sp614x** [comment]
Related to #4909.
Should be fixed in latest preview as long as the whole matched text uses the same formatting.
`nbt.display.Name=ipattern:QueenStrategy*` should now match `<b>QueenStrategy</b>`, but it wouldn't match `<b>Queen</b>Strategy`
