### ISSUE TITLE
[Copyright issue] Cheatbreaker illegally redistributes optifine + possible malicious code

### ISSUE THREAD

**Issue by IMS212** [sp614x/optifine#5079]
**Description of issue:**

After decompiling a client known as "Cheatbreaker offline" for 1.7.10 and 1.8.9 after a report from a user detailed below, I have discovered multiple optifine references in the code, and Optifine is still included in the program itself. It also includes lots of code from Lunar Client, another client that does this exact thing, however I believe cheatbreaker is also malicious for possibly attempting something else that is explained below. 

**Possible malicious intent:**

This situation happened on the Optifine discord server in #support on December 1, 2020, at 2:36 PM PST. A user was asking for help in a situation where any client except Lunar would not show their Optifine cape, and after some testing we determined there was a edit to the hosts file redirecting the optifine cape server to a different IP. This IP was 51.161.35.208, which seems to be an API for Cheatbreaker cosmetics. I believe the intent is to either hijack the optifine system to show a different cape, or sabotage the optifine cape server forcing users to use their capes. Either way, the system was built to not just change the cheatbreaker's cape functions but all Minecraft launcher functions (except Lunar which is presumably using a proxy.) The user may believe that they were scammed by optifine (case in point the user on discord) and go back to using Cheatbreaker or in this case, Lunar since the user had it. The code for Cheatbreaker is not open source, however they are using a github repo to detail things like the API. I would like to see @Offline-Cheatbreaker 's response to this situation.

**Comment by sp614x** [comment]
OptiFine doesn't support custom launchers and "Cheatbreaker offline" doesn't have a permission to distribute OptiFine.
You can report "Cheatbreaker offline" to GitHub.

**Comment by sp614x** [comment]
Hijacking the hosts file to redirect traffic to different servers is definitely malicious.
This is generally done by malware and viruses in order to spy on the traffic or to avoid detection by blocking OS/Antivirus updates.
The hosts file is protected and can only be changed by admin users, which means that at some point the malware has received admin rights and was in capacity to make any changes on the computer.

**Comment by rbuh** [comment]
I found this issue stupid, the client is obfed when giving your code out. pointless ill give you a jar you find it and report back to me. 

Contact me on discord @ rbuh#0001

**Comment by ShonP40** [comment]
1. That IP you provided points to [this cosmetics system](https://github.com/ItsVops/CB-Cosmetics-API) which has nothing to do with us.

2. We have our own cosmetics system (in addition to Optifine capes) which utilized Websockets (Like Lunar's system) and doesn't even touch a single system file on the user's system.

**Comment by ItsVops** [comment]
I own that server and want to clarify that it currently has no affiliation with Optifine. This is my server intended for testing my code. This server is probably in the user's hosts file due to it being the old server of a service called Mantle. You can learn more about mantle at https://mantle.gg. I currently have no more affiliation with Mantle and suggest the user remove this from his hosts file.

**Comment by IMS212** [comment]
Interesting, I did not know about this, thanks! I just assumed it was cheatbreaker causing this for multiple reasons including it pointing to that API and the user previously using CheatBreaker.

**Comment by kristibektashi** [comment]
Wait, isn't Optifine code also copyrighted by Mojang (and by extension, Microsoft)? Isn't that the reason why Optifine can't go open source? Cheatbreaker offline messed up big time

**Comment by ShonP40** [comment]
Offline CheatBreaker's code is obfuscated and not open to the public (same as any other client).

Mojang/Microsoft only really cares about people open sourcing MC's code.

**Comment by GoXLR** [comment]
hows this bullpoop still active 💀
