### ISSUE TITLE
[Bug] Not loading with Conquest Reforged texture pack

### ISSUE THREAD

**Issue by Evandir45** [sp614x/optifine#5082]
## Description of Issue
Game does not get passed initial loading screen when using conquest reforged texture pack, does not crash, it just doesn't finish loading.

## Steps to Reproduce
Launch game without a texture pack, loads fine with optifine, activate conquest reforged texture pack, does not load

## OptiFine Version
OptiFine 1.16.4 HD U G5

## Installation Method
Used standalone version java installer

## Other Installed Mods
no other mods, just the texture pack

[latest.log](https://github.com/sp614x/optifine/files/5632947/latest.log)

**Comment by CreativeRealms** [comment]
Fixed in OptiFine HD U G6 pre1

**Comment by mitsune69** [comment]
This can be resolved by using OptiFine HD U G6 pre1 or pre2 instead of OptiFine 1.16.4 HD U G5
