### ISSUE TITLE
[Perfoemance] Low performance and with/without shaders using optifine. Also getting crashes when trying to load shaderspack

### ISSUE THREAD

**Issue by Borsa-too** [sp614x/optifine#5085]
## Description of Issue
Performance with Optifine are not good using shaders, and are the same as Vanilla game. The fps while using shaders are alway around 30-50 fps. I'm using a radeon rx580 and ryzen 5 2400g, so not a bad rig and can't explain why this bad performance. Doesn't matter if I'm using heavy or light shaders, performances remain the same.

## OptiFine Version
1.16.4 HD U G5

## Installation Method
Installed using standalone file, not using Forge or any Mod Loader

## Log Files/Crash Reports
Crash report, caused by trying to lad a shader pack: https://pastebin.com/bLSPYTQr

## F3 Debug Screenshot
Vanilla debug: https://imgur.com/MyiaqhW
Optifine debug: https://imgur.com/jnOiz6j
Optifine with shaders debug: https://imgur.com/8NzUEr8

**Comment by sp614x** [comment]
The crash is in the graphics driver:
```
# Problematic frame:
# C  [atio6axx.dll+0xbbc052]
```
Your FPS is limited by VSync.
Disable VSync by setting the FPS Limit to maximum.
