### ISSUE TITLE
Overlay texture not applying to the side of path and farmland.

### ISSUE THREAD

**Issue by BrokenDoop** [sp614x/optifine#5090]
I'm using the overlay method to apply a texture to the side of blocks to make it look the grass is connected a bit more on the side, you can see in the image it works for other blocks, and the top texture works on path and farmland but the side texture doesn't.

![2020-12-06_16 48 39](https://user-images.githubusercontent.com/45373918/101298821-9cf05780-37e4-11eb-9d28-62e6f3f8bd82.png)

Using OptiFine 1.16.4_HD_U_G5

Here is the .properties file I have (made it a .txt so it will upload) in case I simply am missing something.
[grass_block_side.txt](https://github.com/sp614x/optifine/files/5649904/grass_block_side.txt)

**Comment by sp614x** [comment]
Overlay textures can only be applied to full blocks.
The farmland and grass path side texture is one pixel smaller than a full block.
