### ISSUE TITLE
Crashing when choosing more deamanding shaders (AMD)

### ISSUE THREAD

**Issue by uselence** [sp614x/optifine#5098]
When I try to load shaders even in a small window I get crash. It is fine if I pick something like Chocapic V9 Medium, but as soon as I get my hands on High version, it crashes. This happens with any shaders, obviously, SEUS does not load at all due to lack of presets. I tried it with different versions of the game (1.14.4, 1.16.4) with the latest OptiFine versions, the same result. OptiFine was used without any other modifications. I am sure it is related to drivers, because it was fine a couple of months ago.

Specs(if it can help):
Ryzen 3 2200G, RX570 4GB
Driver version: 20.11.2

Logs:
[hs_err_pid10672.log](https://github.com/sp614x/optifine/files/5672154/hs_err_pid10672.log)

Is it going to be fixed at some point? Or the only way back is to install old drivers?

**Comment by LetMeUseThisName** [comment]
I got the same problem only with the 8gb version of the card and only with chocapic shaders.

**Comment by LetMeUseThisName** [comment]
Using chocapic from [This](http://www.mediafire.com/file/c7sea7dexuyu76h/Chocapic13_V9_Ultra.zip/file) link solved the problem for me all the other versions still crash but this one works.

**Comment by uselence** [comment]
> Using chocapic from [This](http://www.mediafire.com/file/c7sea7dexuyu76h/Chocapic13_V9_Ultra.zip/file) link solved the problem for me all the other versions still crash but this one works.

well the version you sent worked once on 1.14.4, but after I tried 1.16.4 with it (which didn't work), it refused to work even on 1.14.4. thanks for help, but I guess this is it, no shaders for us. amd starts to really dissapoint me. meanwhile nvidia owners have no troubles of such kind and get seus ptgi e13...

**Comment by sp614x** [comment]
This is a crash in the graphics drivers, can't be fixed by OptiFine.

    # Problematic frame:
    # C  [atio6axx.dll+0xbbc052]
