### ISSUE TITLE
mc_Entity does not get set for TESRs

### ISSUE THREAD

**Issue by Builderb0y** [sp614x/optifine#510]
Always seems to be 0.0 for x/y/z, and 1.0 for w (not that w is used for anything, but thought it was interesting that it wasn't 0 like it was for x/y/z). This is the case in both gbuffers_terrain and gbuffers_block.

**Comment by Builderb0y** [comment]
Just found the "blockEntityId" uniform, and it also seems to return 0. Tested in gbuffers_terrain/block, and in preview B8. If it's relevant, "entityId" works properly in preview B8.

**Comment by Builderb0y** [comment]
blockEntityId now works properly in the latest B8 preview released earlier today.

**Comment by Builderb0y** [comment]
Or, it did… now it's back to 0 again. And I'm getting spammed with `GL error 0x0502: Invalid operation at blockEntityId` even after switching to the internal shader pack. I'm not entirely sure what I did to trigger this, but it persists until the client is restarted.

**Comment by sp614x** [comment]
The "mc_Entity" is only set for blocks.
Tile entities use "blockEntityId" and entities use "entityId".
