### ISSUE TITLE
[Bug] Large chest option in custom GUI not working properly.

### ISSUE THREAD

**Issue by ColonelOverspel** [sp614x/optifine#5100]
## Description of Issue
Toggle for large chest in custom_guis.properties works inverted. large = false option make it apply to large chests. Large = true options make it apply to small chests.

## Steps to Reproduce
1. Create a custom gui for a chest
2. Set the container to be a chest
3. Set the large option to false

## OptiFine Version
OptiFine 1.16.4 HD U G5Download

## Installation Method
Standalone Installer

**Comment by sp614x** [comment]
Fixed, coming in next preview.
