### ISSUE TITLE
[Bug Report] java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by Luracasmus** [sp614x/optifine#5108]
## Description of Issue
When starting the game, it takes longer than with vanilla and this appears in the log:
![image](https://user-images.githubusercontent.com/60381935/102455582-22270800-4040-11eb-8bbf-d03e3b7499f2.png)

## Steps to Reproduce
1. Install Fabric
2. Add OptiFine and OptiFabric
3. Start the game

or

1. Install OptiFine
2. Start the game

## OptiFine Version
OptiFine HD U G5

## Installation Method
Fabric + OptiFabric

## Fabric/Forge Version
fabric-loader-0.10.8-1.16.4

## OptiFabric Version
optifabric-1.8.13

## Mods
 - dynamic-fps-1.2.1
 - fabric-api-0.28.1+1.16
 - krypton-0.1.0
 - optifabric-1.8.13
 - OptiFine_1.16.4_HD_U_G5_MOD

## Log Files/Crash Reports
[latest.log](https://github.com/sp614x/optifine/files/5707593/latest.log)

## F3 Debug Screenshot
![image](https://user-images.githubusercontent.com/60381935/102456601-b34aae80-4041-11eb-9120-868afbdcc2ec.png)

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
   - No

If you've installed using Forge/Fabric:
- Does this happen without other mods installed?
   - Yes
- Does this happen without any mods at all?
   - No
- Does this happen in OptiFine standalone?
   - Yes
- Does this happen in Vanilla without OptiFine?
   - No

## Additional Information
Java: jdk-15.0.1_windows-x64

**Comment by sp614x** [comment]
The loading takes longer because OptiFine has to fix the textures while loading them.
The reflection error is normal when using Java 9 or newer.

**Comment by linux-leo** [comment]
Could you explain what the other 3 errors are?
