### ISSUE TITLE
[Resource pack problem] Resource reload failed

### ISSUE THREAD

**Issue by DhruvMitna** [sp614x/optifine#5109]
## Description of Issue
Whenever I enable all my resourcepacks, it loads and then loads again and then switches to default and says -'resource reload failed' I have pinpointed all the ones which dont work

## Steps to Reproduce
1. Download the attached resource packs
2. Start minecraft
3. Enable the resource packs
4. Wait for it to load and then reload and the error will be there

## OptiFine Version
OptiFine_1.16.4_HD_U_G5

## Installation Method
I put the jar file in my mods folder along with optifabric mod file.

## Fabric/Forge Version
0.10.8

## OptiFabric Version
1.8.10

## Other Installed Mods

1. fabric-api-0.25.1+build.416-1.16
2. Hwyla-fabric-1.16.2-1.9.23-79
3. malilib-fabric-1.16.4-0.10.0-dev.21+arne.2
4. minihud-fabric-1.16.4-0.19.0-dev.20201103.184029
5. modmenu-1.14.5+build.1
6. optifabric-1.8.10
7. OptiFine_1.16.4_HD_U_G5

## Log Files/Crash Reports

[2020-12-17-3.log](https://github.com/sp614x/optifine/files/5708160/2020-12-17-3.log)

## F3 Debug Screenshot

![2020-12-17_14 46 12](https://user-images.githubusercontent.com/75002001/102468012-fe32e900-4076-11eb-8b74-8f65937f7a5d.png)

## Prior Testing

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
 Yes
- Does this happen without any mods at all?
Yes
- Does this happen in OptiFine standalone?
Yes
- Does this happen in Vanilla without OptiFine?
Yes
   - Does the issue still happen with only the remaining mods installed?
 Yes

## Additional Information

This issue only seems to happen with resource packs that use optifine features like ctm, cem, cit, custom gui, etc

Here are the resource packs which cause this error (only the ones which dont work are attatched)

[Better GUI.zip](https://github.com/sp614x/optifine/files/5708273/Better.GUI.zip)
[Blackstone Furnace+Coloured Redstone Lamps.zip](https://github.com/sp614x/optifine/files/5708284/Blackstone.Furnace%2BColoured.Redstone.Lamps.zip)
[Chillager and Hovering Inferno.zip](https://github.com/sp614x/optifine/files/5708287/Chillager.and.Hovering.Inferno.zip)
[Emissive Pack.zip](https://github.com/sp614x/optifine/files/5708288/Emissive.Pack.zip)
[Fmailiar Pack.zip](https://github.com/sp614x/optifine/files/5708289/Fmailiar.Pack.zip)
[Miniboss Healthbars.zip](https://github.com/sp614x/optifine/files/5708296/Miniboss.Healthbars.zip)
[Packommunity.zip](https://github.com/sp614x/optifine/files/5708297/Packommunity.zip)
[3D Pack.zip](https://github.com/sp614x/optifine/files/5708307/3D.Pack.zip)

**Comment by sp614x** [comment]
The resource pack is too big.

    Caused by: net.minecraft.class_1054: Unable to fit: minecraft:item/egg_llama, size: 920x920, atlas: 7356x7516, atlasMax: 8192x8192 - Maybe try a lower resolution resourcepack?
        at net.minecraft.class_1055.method_4557(class_1055.java:70) ~[intermediary-fabric-loader-0.10.8-1.16.4.jar:?]

**Comment by DhruvMitna** [comment]
> The resource pack is too big and can't be loaded.
> 
> ```
> Caused by: net.minecraft.class_1054: Unable to fit: minecraft:item/egg_llama, size: 920x920, atlas: 7356x7516, atlasMax: 8192x8192 - Maybe try a lower resolution resourcepack?
>     at net.minecraft.class_1055.method_4557(class_1055.java:70) ~[intermediary-fabric-loader-0.10.8-1.16.4.jar:?]
> ```

thank you! ill try with the other resource packs

**Comment by mememcdank69** [comment]
I have the same problem but I want to use a higher texture pack, and It wont even let me run the lowest resolution version of this texture pack, it happens no matter what now and its even more annoying that I could use this texture pack previously but all of a sudden its saying "resource reload failed" please help me!

**Comment by JamingDE** [comment]
i have the same problem but with The Expansion Resources v1.6
i dont even use optifne please help

**Comment by shinenodes** [comment]
Can Anyone tell me when i use the texture pack in 1.20 it works fine but it shows the error "Resource Reload failed" in minecraft 1.21

**Comment by Emfire12345** [comment]
> Can Anyone tell me when i use the texture pack in 1.20 it works fine but it shows the error "Resource Reload failed" in minecraft 1.21 in fabric

If you have issues with resourcepack reload in fabric, the optifine issues page is not the right place to ask

**Comment by uTa4u** [comment]
> Can Anyone tell me when i use the texture pack in 1.20 it works fine but it shows the error "Resource Reload failed" in minecraft 1.21 in fabric

did you solve it somehow? I also have issues on 1.21.1 specifically

**Comment by Niskasha** [comment]
> > Can Anyone tell me when i use the texture pack in 1.20 it works fine but it shows the error "Resource Reload failed" in minecraft 1.21 in fabric
> 
> did you solve it somehow? I also have issues on 1.21.1 specifically

I believe I found a solution, at least it worked for me when everything else would not.

Go into the resource pack's folder after you unzip it, go into assets, then minecraft, then delete the shaders file in the resource pack. Same for realms, and hopefully it should work.

**Comment by RaneKun** [comment]
note - if you're using the famous resource pack "Recolourful Containers GUI + HUD" - https://modrinth.com/resourcepack/recolourful-containers-gui then the error will show up when enabling the pack unless you follow this step here - https://github.com/Vi-Tul/Recolourful-Containers-GUI/issues/22
I hope this helps someone :)
