### ISSUE TITLE
[Bug] [1.16.4] [Help] Blocks are invisible on servers

### ISSUE THREAD

**Issue by HEROproductions** [sp614x/optifine#5111]
## Description of Issue
Blocks on any servers aren't rendering. This issue isn't present in singleplayer or when playing Vanilla on servers. The only way to make blocks visible is for me to place or break a block, which causes all of the blocks in that sub-chunk (16x16x16 blocks, instead of the full 16x256x16 blocks) to be visible for a while. Of course this is no real solution and makes it impossible to play on servers. Interestingly enough the blocks still exist and I can walk on them.

## Steps to Reproduce
1. I open the Optifine 1.16.4 HD U G5 installation of Minecraft
2. I log onto a server, and can't see any blocks.

## OptiFine Version
Optifine 1.16.4 HD U G5

## Installation Method
Standard standalone installer that comes with the .JAR download.

## Log Files/Crash Reports
I generated this log file by running Minecraft and logging onto Hypixel and immediately disconnecting to help narrow down the search. It seems there are some errors relating to textures? Could this be related?
[latest.log](https://github.com/sp614x/optifine/files/5712730/latest.log)

## F3 Debug Screenshot
Here's a screenshot from Hypixel's arcade lobby. As you can see no blocks are visible and skins are also not rendering, including my own, which I think is related. I should also mention that these are NPCs in the background, actual players do not render at all.
![2020-12-17_15 47 37](https://user-images.githubusercontent.com/60427702/102557107-4950fa00-407f-11eb-9f64-4de358b8e92a.png)

## Prior Testing
- I have tried resetting all of my settings & deleting the `optionsof.txt` file
- I tried turning Lazy Chunk Loading on/off, which didn't make a difference
- I tried starting with a fresh `.minecraft` folder
- I tried playing on a LAN world on my own machine with two instances of Minecraft, which oddly enough worked fine; the issue was not present
- I tried logging onto a free Aternos server with a flatworld to get a log file, but was surprised to find that the issue is not present there! Does this mean it's an issue on the end of all major servers? I've tried: `mc.hypixel.net`, `play.hivemc.com`, `us.mineplex.com`, `play.becto.net`, `play.cubecraft.net`, and other servers, all of which have the issue where I can't see any blocks.

## Additional Information
Thank you for taking the time to read this, I really appreciate it and any help you can offer! :)

**Comment by btpwdb365** [comment]
_Same problem: [#4953](https://github.com/sp614x/optifine/issues/4953)_

**Comment by Laurenshup** [comment]
Also have this problem. Sometimes, after waiting a few minutes, everything "loads" as usual: all textures are visible and skins are loaded.

**Comment by sp614x** [comment]
Fixed, coming in next preview.
