### ISSUE TITLE
Problems running Optifine 1.8.9 on Apple M1

### ISSUE THREAD

**Issue by galacticrepublic1** [sp614x/optifine#5117]
## Description of Issue
Hey I just got the new MacBook Air with the M1 processor it works great while running optifine for 1.16.4 but when I tried to do it on 1.8.9 it failed. On vanilla 1.8.9 Minecraft it works but yet it doesn't on optifine is their anything I can do to make it compatible ARM structure thanks. Also it just has a white screen and doesn't even load. I also just tried the new 1.8.9 pre version 2 and and it doesn't have an unusable white screen but instead the game seems to be running but now the entire screen is black and I can't see anything but I can hear the audio from clicking the buttons.
## Steps to Reproduce
1. What do you do... run 1.8.9 optifine on an M1 Mac.
2. ...to find this bug?
## OptiFine Version
 OptiFine 1.8.9 HD U L5 and  1.8.9_HD_U_M5_pre2

## Installation Method
How did you install OptiFine? Did you use the included standalone installer, or did you drop the JAR file into your "mods" folder?
I just installed it the usual MacOS way and allowed it to intergrate with Minecraft after I had to let it go past security. I believe this is the .jar way.

I believe optifine is standalone and not with forge.
[2020-12-19-6.log White Screen.log](https://github.com/sp614x/optifine/files/5720362/2020-12-19-6.log.White.Screen.log)
[2020-12-19-7.log Black Screen.log](https://github.com/sp614x/optifine/files/5720363/2020-12-19-7.log.Black.Screen.log)

## Log Files/Crash Reports
Any relevant log files. Drag and drop text files here to upload to GitHub directly, OR upload the complete contents to Pastebin. https://pastebin.com/

You can get logs from `.minecraft/logs`, and crash reports from `.minecraft/crash-reports`. 
Locating your `.minecraft` folder will depend entirely on your OS. See this page for details: https://minecraft.gamepedia.com/.minecraft

**DO NOT directly copy and paste log contents here on GitHub.**

## F3 Debug Screenshot
Minecraft's built-in debug screen provides *a lot* of useful information, and should be included even if the issue is not something that can be captured in a still image.

To open this menu, simply press `F3` on your keyboard while in-game. Please ensure the text is easily readable. Depending on the size/resolution of your monitor, you may have to adjust your GUI scale for all text to be completely visible on-screen.
N/A
## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
No

**Comment by AwesomestCode** [comment]
Duplicate of #5034. Unrelated to ARM.

**Comment by galacticrepublic1** [comment]
Thanks
