### ISSUE TITLE
[Bug Report] Background Moves When Opening Resource Packs Menu

### ISSUE THREAD

**Issue by Luracasmus** [sp614x/optifine#5118]
## Description of Issue
The background moves when opening the Resource Packs menu

Correct background:
![image](https://user-images.githubusercontent.com/60381935/102711477-645b7e00-42ba-11eb-8a76-73f1f9d333b7.png)

Broken Background:
![image](https://user-images.githubusercontent.com/60381935/102711529-a84e8300-42ba-11eb-9868-3df150416765.png)
![image](https://user-images.githubusercontent.com/60381935/102711533-b00e2780-42ba-11eb-99da-fe3e1eb50b8d.png)
![image](https://user-images.githubusercontent.com/60381935/102711538-b56b7200-42ba-11eb-8fc0-799e5e526386.png)

## Steps to Reproduce
1. Start the game
2. Open the Resource Packs menu

## OptiFine Version
1.16.4 OptiFine HD U G5

## Installation Method
Standalone Installer

## Log Files/Crash Reports
[latest.log](https://github.com/sp614x/optifine/files/5720804/latest.log)

## F3 Debug Screenshot
![image](https://user-images.githubusercontent.com/60381935/102711338-30cc2400-42b9-11eb-8492-75cf32279c40.png)

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine? Yes

**Comment by Regnander** [comment]
> * Does this happen in Vanilla without OptiFine? Yes 

Is this a vanilla bug or did you mean to say "No"?

**Comment by sp614x** [comment]
OptiFine doesn't change the resource pack menu rendering.
This is vanilla behaviour.
