### ISSUE TITLE
fullscreen compressed into corner

### ISSUE THREAD

**Issue by findanother1** [sp614x/optifine#512]
I'm using a 1920x1080 resolution and wanted to adjust the fullscreen to 1280x720, but it doesn't fullscreen properly. It compresses directly into a corner and doesn't cover the entire monitor.
![erro9r](https://cloud.githubusercontent.com/assets/26083350/23398625/23eabf2c-fd52-11e6-97e3-faad8797d1fe.png)

**Comment by Tsoccerguy3** [comment]
I found this to happen in Mincraft 1.7.10 , using Linux Mint 18.1 OS 64 bit , nvidia proprietary drivers

At any resolution No Opifine installed , it may be a Mojang bug or Driver bug

**Comment by KaiAF** [comment]
Closing this as it's an old issue. If you are still having any issues, please let me know.
