### ISSUE TITLE
Being able to see through transparent objects

### ISSUE THREAD

**Issue by r0xANDt0l** [sp614x/optifine#5120]
## Description of Issue
Being able to see through transparent blocks when you're in spectator mode & 3rd person, and you're looking at your head

## Steps to Reproduce
1. Put yourself in Spectator mode
2. Press F5 to put yourself in 3rd person
3. Look through your head next to a transparent block

## OptiFine Version
Optifine 1.16.4 HD U G5

## Installation Method
I dropped into the "Mods" folder

## Fabric/Forge Version
Fabric 0.10.8 1.16.4

## OptiFabric Version
Optifabric 1.8.10

## Other Installed Mods
Litematica, Malilib and Optifabric.

## Log Files/Crash Reports
Any relevant log files. Drag and drop text files here to upload to GitHub directly, OR upload the complete contents to Pastebin. https://pastebin.com/

You can get logs from `.minecraft/logs`, and crash reports from `.minecraft/crash-reports`. 
Locating your `.minecraft` folder will depend entirely on your OS. See this page for details: https://minecraft.gamepedia.com/.minecraft

**DO NOT directly copy and paste log contents here on GitHub.**

## F3 Debug Screenshot
![image](https://user-images.githubusercontent.com/41841903/102716236-da6fdd00-42da-11eb-9f1d-c4523ee0cf7c.png)

## Prior Testing
If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   yes
- Does this happen without any mods at all?
  yes
- Does this happen in OptiFine standalone? yes
- Does this happen in Vanilla without OptiFine? yes
- Have you tried using a binary search to find which mods cause this issue?
  yes, no other mods were interfering 
   - Does the issue still happen with only the remaining mods installed?
      - Forge/Fabric and remaining mods, without OptiFine

## Additional Information
Nothing more

**Comment by sp614x** [comment]
This is vanilla behavior and can't be fixed easily.
