### ISSUE TITLE
[FEATURE REQUEST] being able to keep the normal map working during falling of block

### ISSUE THREAD

**Issue by Yato202010** [sp614x/optifine#5122]
![image](https://user-images.githubusercontent.com/61349049/102724706-c1cee980-4311-11eb-80f1-8e2cc6483c3b.png)
hiii
X) it would be very cool if you can make that optifine can keep the _n texture of a static block like sand , gravel or concrete powder during their fall it will look very cool or perhaps give the hability to set a separate normal map as this block is ( as i can understant ) a entity during is fall . thanks for reading this and hope you will work on this feature one day ( and if it's already implemented can you send me a link because i have found nothing in the doc about something like that X) ). have a nice day and byeee X)

**Comment by sp614x** [comment]
Which version is this?
Can you post an F3 screenshot?

**Comment by Yato202010** [comment]
![2020-12-24_00 17 59](https://user-images.githubusercontent.com/61349049/103043591-b5e75f80-457d-11eb-8a8e-eebe0a4430d6.png)
my optifine version is 1.16.3_HD_U_G5 this happen with all my shaders who support labpbr ( bsl 7.2 ,bsLex 5.7 , chocapic13 , complementary 3.05 and seus renewed 1.0.1 ) i have try to downgrade my amd drivers but nothing change and it break some of my other game so i upgrade it again
