### ISSUE TITLE
[1.16.4] Crash with Fabric and Shutter

### ISSUE THREAD

**Issue by AeternumStudios** [sp614x/optifine#5124]
## Description of Issue
My team and I are developing a modern camera recording mod. Upon executing this [ line ](https://github.com/Studio-Archetype/Shutter-Fabric/blob/d3a19f35552d74de741662c4343943cd59798998/src/main/java/studio/archetype/shutter/client/PathFollower.java#L41) an exception is thrown resulting in the world saving, then the game crashes.

## Steps to Reproduce
Load world with contents of mods.zip below.
Create path nodes by default using NUM5 2 nodes minimum. Press Num Enter to start path following.

## OptiFine Version
OptiFine_1.16.4_HD_U_G5

## Installation Method
Jar dropped into mods.

## Fabric/Forge Version
Fabric 0.10.8

## OptiFabric Version
OptiFabric 1.8.13

## Other Installed Mods
Optifabric
Fabric API
[Shutter](https://github.com/Studio-Archetype/Shutter-Fabric)

## Log Files/Crash Reports
[crash-2020-12-22_08.05.39-client.txt](https://github.com/sp614x/optifine/files/5730672/crash-2020-12-22_08.05.39-client.txt)

## F3 Debug Screenshot
![image](https://user-images.githubusercontent.com/19141757/102905211-02248980-4430-11eb-9db5-3e2fa2f20347.png)

## Prior Testing
Not applicable.

## Additional Information
Mods.zip including build of Shutter.
[mods.zip](https://github.com/sp614x/optifine/files/5730684/mods.zip)

**Comment by sp614x** [comment]
The linked line is a method definition, it is not really executed: 
https://github.com/Studio-Archetype/Shutter-Fabric/blob/d3a19f35552d74de741662c4343943cd59798998/src/main/java/studio/archetype/shutter/client/PathFollower.java#L41

The crash report show the crash in `EntityRendererManager.getPackedLight()`:
`        int combinedLight = this.getRenderer(entityIn).getPackedLight(entityIn, partialTicks);`

Maybe the given entity doesn't have a renderer?

**Comment by AeternumStudios** [comment]
> The linked line is a method definition, it is not really executed:
> https://github.com/Studio-Archetype/Shutter-Fabric/blob/d3a19f35552d74de741662c4343943cd59798998/src/main/java/studio/archetype/shutter/client/PathFollower.java#L41
> 
> The crash report show the crash in `EntityRendererManager.getPackedLight()`:
> ` int combinedLight = this.getRenderer(entityIn).getPackedLight(entityIn, partialTicks);`
> 
> Maybe the given entity doesn't have a renderer?

This looks like the case, ill close when I confirm.

**Comment by AeternumStudios** [comment]
> The linked line is a method definition, it is not really executed:
> https://github.com/Studio-Archetype/Shutter-Fabric/blob/d3a19f35552d74de741662c4343943cd59798998/src/main/java/studio/archetype/shutter/client/PathFollower.java#L41
> 
> The crash report show the crash in `EntityRendererManager.getPackedLight()`:
> ` int combinedLight = this.getRenderer(entityIn).getPackedLight(entityIn, partialTicks);`
> 
> Maybe the given entity doesn't have a renderer?

No entities are registered.

**Comment by AeternumStudios** [comment]
We had an issue where the FOV was becoming NaN while setting up the ability to zoom, we thought that was most likely to be the problem causing optifine to throw a fatal exception. We fixed that by implementing a separate system for handling subticks for path interpolation down to double precision. But the same issue now arises, except this time, after the first crash in a fresh installation, the install never boots again throwing exitcode -1073740771. We are hoping we can have some more in depth discourse with @sp614x to determine a solution. We want to play nice with optifine so our product is actually useful. Since everyone uses optifine.

**Comment by sp614x** [comment]
Is MC initialized properly, any other errors in the error log?

**Comment by AeternumStudios** [comment]
We made the camera entity return the EntityType of player
https://github.com/Studio-Archetype/Shutter-Fabric/blob/8d5892be733f55bf71ca423bf7518455409db016/src/main/java/studio/archetype/shutter/client/entities/FreecamEntity.java#L59

but we still get the same crash 
[crash.txt](https://github.com/sp614x/optifine/files/5778609/crash.txt)

**Comment by sp614x** [comment]
Player entities are recognized by their class and not by render type. 
Using another render type (any mob) could work.
```
    public <T extends Entity> EntityRenderer <? super T > getRenderer(T entityIn)
    {
        if (entityIn instanceof AbstractClientPlayerEntity)
        {
            String s = ((AbstractClientPlayerEntity)entityIn).getSkinType();
            PlayerRenderer playerrenderer = this.skinMap.get(s);
            return (EntityRenderer <? super T >)(playerrenderer != null ? playerrenderer : this.playerRenderer);
        }
        else
        {
            return (EntityRenderer <? super T >) this.renderers.get(entityIn.getType());
        }
    }
```

**Comment by AeternumStudios** [comment]
Solved, thank you so much for your help <3
