### ISSUE TITLE
[Feature Request] Collar Color on CEM

### ISSUE THREAD

**Issue by Clashbestie** [sp614x/optifine#5125]
## Description of the new feature

I haven't found any tutorial or other info about it, so I assume that this feature is not available. If it is, please correct me.

I am talking about using the collar color of a dog/cat in a CEM. It might just be a category whose elements get this color.

And again if this feature already exists feel free to correct me and show me how to use it.

**Comment by ewanhowell5195** [comment]
this is not cem this is random entities.

https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/random_entities.properties#L124

**Comment by Clashbestie** [comment]
Ok, thanks seems like I looked at the wrong place.
