### ISSUE TITLE
[Bug Report] (1.16.4) Massive FPS drops and too high RAM usage.

### ISSUE THREAD

**Issue by berkkrkc09** [sp614x/optifine#5126]
## Description of Issue
FPS drops start right after any world loads and RAM usage doesn't even go under _4.2GB(if i remember correctly)_ in any world. If i give more ram to the game RAM usage just goes up and up and up and up... Thested with a used and a new generated world, tested with and without "Terra Forged" mod and nothing diffrent.(I did this because it was the last new mod i added) F3 screenshot was taken when "Terra Forged" was loaded. I am saying that the ram usage is too much because i played with about 215 mods with the same machine and same amount of ram given to the game but unfortunately i don't have that mod list so i can't narrow the mods.

## Steps to Reproduce
1. Just load a world
2. Oh, my frames!..

## OptiFine Version
OptiFine HD U G5 (1.16.4)

## Installation Method
Dropped the JAR file into mods folder.

## Forge Version
forge-35.1.13

## Other Installed Mods
https://pastebin.com/2WKWkW7z
Sorry for the unnecessary info, I had to use a cmd command to get the list. There are more than 250 mods. 😮😐

## Log Files/Crash Reports
[latest.log](https://github.com/sp614x/optifine/files/5736551/latest.log)
[debug.log](https://github.com/sp614x/optifine/files/5736552/debug.log)

## F3 Debug Screenshot
![javaw_AZ5BFRKsMY](https://user-images.githubusercontent.com/57318309/103023895-d9031680-455f-11eb-902d-bdaf6c464638.png)

## Prior Testing
If you've installed using Forge:
- Does this happen without other mods installed?
   - Only OptiFine and Forge --> _**no**_
- Does this happen without any mods at all?
   - Only Forge by itself. --> _**no**_
- Does this happen in OptiFine standalone? --> _**no**_
- Does this happen in Vanilla without OptiFine? --> _**no**_
- Have you tried using a binary search to find which mods cause this issue? --> _**no** (There is more than 250 mods. Sorry!)_
   - To find conflicting mods, split your mods into 2 groups (not including OptiFine/OptiFabric, obviously). Remove one group, and test in-game. Keep the group that has the problem, and repeat until no more mods can be removed without the issue disappearing.
   - Does the issue still happen with only the remaining mods installed? --> _**?**_
      - Forge and remaining mods, without OptiFine --> _**I don't know because i literrally don't have the hardware to play with this amount of mods without OptiFine. :(**_

## Additional Information
I didn't use any shaderpack or resourcepack. Playig singleplayer.

I am using CurseForge client, if you need i can export the profile for you so you don't have to find all of the specific versions of the mods by hand and you can just import it.

Yesterday i tried to use "Eclipse memory Analyzer" for the possibility of a memory leak. The Program found 2 possible causes but i am not familliar with java so i didn't understand anything.

**Comment by sp614x** [comment]
Looks like a conflict with one of the installed mods.
To find the problematic mod
1. Test with half of the mods and OptiFine
2. Keep the mods that have the problem
3. Repeat from 1 until only one mod and OptiFine are left

**Comment by GlowTimeHD** [comment]
I also got memory leak issues in 1.16.4, not happening in 1.16.3.

**Comment by berkkrkc09** [comment]
I split mods to about half(excluding coremods and libmods). Both halves are playable and has low RAM usage. I didn't expect this outcome. 😶

**Comment by berkkrkc09** [comment]
> I also got memory leak issues in 1.16.4, not happening in 1.16.3.

yeah It didn't happen to me on 1.16.3 either.
