### ISSUE TITLE
[1.16.4] CIT Custom Named items not work

### ISSUE THREAD

**Issue by Dariusz17** [sp614x/optifine#5127]
Affected versions 1.16.4 OptiFine HD U G5/OptiFine HD U G6 pre1
Naming any item using nbt.display.Name or nbt.display.Name=iregex will not change texture 
Example 1
type=item
items=minecraft:string
nbt.display.Name=iregex:.*(\u00a7e\u00a7lW\u0142os z brody Merlina|Merlina).*
nbt.display.Lore.0=\u00a7aMagiczna waluta poszukiwana
nbt.display.Lore.1=\u00a7aprzez wielu handlarzy
texture=string.png
enchantments=thorns
enchantmentLevels=10
weight=1

Example 2 
matchItems=diamond_sword
tile=rapier
nbt.display.Name=Rapier
model=rapier

![Bez tytułu2](https://user-images.githubusercontent.com/42091569/103031094-7577e980-455d-11eb-8764-1b0d030e1f2d.png)
![Bez tytułu3](https://user-images.githubusercontent.com/42091569/103031265-cbe52800-455d-11eb-9d84-7f09727e21d5.png)

I checked 1.15.2 but it seems to work in this version.

**Comment by botpebble** [comment]
Hey! Did you find a fix since you closed it? I am struggling with this myself, so it would be nice if someone found a solution. :)

**Comment by Dariusz17** [comment]
No I'm not find any fix. Only solution is a waiting for official fix....

**Comment by TheFuryBumblebee** [comment]
What is the path of your files?
