### ISSUE TITLE
Crash (with a mod)

### ISSUE THREAD

**Issue by ghost** [sp614x/optifine#513]
it is very steady to be crashed.
[crash-2017-03-01_18.23.36-client.txt](https://github.com/sp614x/optifine/files/811159/crash-2017-03-01_18.23.36-client.txt)
[crash-2017-03-01_18.16.52-client.txt](https://github.com/sp614x/optifine/files/811160/crash-2017-03-01_18.16.52-client.txt)
[crash-2017-03-01_18.14.26-client.txt](https://github.com/sp614x/optifine/files/811161/crash-2017-03-01_18.14.26-client.txt)

https://github.com/octarine-noise/BetterFoliage/issues/119

**Comment by KaiAF** [comment]
Deleted user, also crash is caused by out of memory
