### ISSUE TITLE
1.16.3/4 Solid Blocks became transparent

### ISSUE THREAD

**Issue by ink717** [sp614x/optifine#5132]
Concrete, stone, terracotta, and some other modded asphalt textures became transparent. It only happened in this city in the entire map where a large number of solid pavement blocks were used. 
![2020-10-30_22 19 43](https://user-images.githubusercontent.com/72815511/103107888-c0066e00-4610-11eb-8ffd-ed3f708f8fd4.png)
![2020-10-30_22 20 16](https://user-images.githubusercontent.com/72815511/103107890-c0066e00-4610-11eb-84b3-c48541a6814c.png)
![2020-10-30_22 20 20](https://user-images.githubusercontent.com/72815511/103107891-c09f0480-4610-11eb-9c90-eb0407ee5015.png)
![2020-10-30_22 20 36](https://user-images.githubusercontent.com/72815511/103107892-c09f0480-4610-11eb-8535-f0effdfe4983.png)

**Comment by KaiAF** [comment]
If you still have this issue, please send a F3 screenshot.
