### ISSUE TITLE
Optifine site not working

### ISSUE THREAD

**Issue by fullhousecast** [sp614x/optifine#5137]
![image](https://user-images.githubusercontent.com/73658217/103139767-a8061b80-46f0-11eb-9110-ed5293e9575a.png)

**Comment by HiItsDevin** [comment]
Be patient, it'll be back up, most likely just completely overwhelmed at the moment.

**Comment by MrCheeze446** [comment]
Sp614x is aware of the issue, updates will be posted on the twitter account and in our discord server.
