### ISSUE TITLE
[Question] [1.12.2]

### ISSUE THREAD

**Issue by TheRedCreations** [sp614x/optifine#5138]
I have a Question. I have 2 texture packs. Both have TESR-Textures. The second one has alternate TESR-Textures. is it possible to use the alternate textures in specific bioms?

**Comment by sp614x** [comment]
With Random Entities you can enable textures depending on biome:
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/random_entities.properties#L75

**Comment by TheRedCreations** [comment]
Thanks. I'll try that.
