### ISSUE TITLE
invis

### ISSUE THREAD

**Issue by 420lechxis** [sp614x/optifine#5139]
I played hyoixel and som1 whas going ibvis and when they  whas invis i coud se ther christmas hat

**Comment by Regnander** [comment]
What OptiFine version? Does this happen without OptiFine?

**Comment by Pizzachu22** [comment]
The issue is caused by the santa hat, which is an OptiFine donator feature.

**Comment by PyICoder** [comment]
Very bannable, I was playing a bedwars game and it was easy to find invis player with a hat floating.

**Comment by sp614x** [comment]
Currently the santa hat behaves like armor and is shown when the player is inivisible.
You can disable the hat in the cape editor.
