### ISSUE TITLE
Feature Request: Api and bukkit plugin to utilize optifine capes on servers. 

### ISSUE THREAD

**Issue by Sephiths** [sp614x/optifine#5147]
## As a server owner it'd be nice to assign players capes for our various game modes. 
IT's also be really nice if the api could be used for other installed plugins. Like towny and factions. 

Uses for this include. 
Official server banner cape in the server hub. 
Red Vs Blue cape customization. 
Clan style groups using the clan/town/nation/faction cape.

Optifine is the best home for something like this. By already having banner custom cape support, and having a huge userbase. It may even benefit Optifine as it will attract new users by saying "Our clan/faction/etc has a custom cape! Download optifine to view!". 

These capes would be server / plugin api specific and wouldn't carry outside of specific servers. Donations for capes would still be relevant with the option to override server provided cape, and vice versa. 

The cape option in skin customization could switch from Mojang (if available), Server (if available), Optifine donation (if available) and none.

**Comment by sp614x** [comment]
How should this work?
OptiFine calls the server to ask if the user has a server-specific cape?

**Comment by Sephiths** [comment]
Yep! Ideally it'd be the server calling the the client somehow. But either works. As long as it's functional.

**Comment by sp614x** [comment]
This is not realistic.
OptiFine is primary a client mod and doesn't communicate with the server.

**Comment by Pekly** [comment]
Bro got rejected 😭

**Comment by enqorman** [comment]
communicate with deez @sp614x
