### ISSUE TITLE
[suggestion] custom capes

### ISSUE THREAD

**Issue by lavadaragon15396** [sp614x/optifine#5149]
It would be nice to be able to upload a cape texture for a completely custom cape/elytra of only a resolution of 64x32 similar to other mods like [minecraftcapes.net](https://minecraftcapes.net/download) or 92x44 like the optifine banner capes 

Example cape for upload 64x32:
![2011](https://user-images.githubusercontent.com/68852782/103170986-6c7a6700-4840-11eb-88d3-cf347a65ea2b.png)

Example cape for upload 92x44:
![Untitled](https://user-images.githubusercontent.com/68852782/103171033-d6930c00-4840-11eb-98c3-c99b4cc5170f.png)

**Comment by sp614x** [comment]
This is not realistic as it would need automated or manual verification of the uploaded capes to avoid NSFW and Mojang content.
Your example is the Minecon 2011 cape which is exactly why this shouldn't be added.

**Comment by lavadaragon15396** [comment]
ok thanks for the answer. I didn't think about that

**Comment by muriloog3020** [comment]
but why dont make when put a minecon cape or official capes turn into default capes?
