### ISSUE TITLE
Santa Hat Showing When Invisible

### ISSUE THREAD

**Issue by BlackHummingBird** [sp614x/optifine#5150]
(Discovered in Hypixel Bedwars) When I drank an invisibility potion (45s), I was visible due to the santa hat not going invisible with my character. I have disabled the Santa hat due to this bug.

**Comment by sp614x** [comment]
Currently the hat behaves like armor and is shown on invisible players.

**Comment by sp614x** [comment]
Fixed, coming in next preview.
