### ISSUE TITLE
[Bug?] Transparency

### ISSUE THREAD

**Issue by xmssss** [sp614x/optifine#5151]
With Forge, latest OF at 1.16.4 but same problem at 1.15.2. Another MCVersions not tested. Any capes don't have transparency in game. If you do transparent png, in game transparent parts fill with white color

How look in PS:
![image](https://user-images.githubusercontent.com/9090102/103179634-1557af00-489f-11eb-8c5a-4e130b1e265a.png)

In viewer:
![image](https://user-images.githubusercontent.com/9090102/103179644-21437100-489f-11eb-8226-906db391b353.png)

In game:
![image](https://user-images.githubusercontent.com/9090102/103179655-39b38b80-489f-11eb-90c8-e35d2a3c1959.png)

**Comment by sp614x** [comment]
This is not a bug, cape transparency is not supported.

**Comment by xmssss** [comment]
Why?
