### ISSUE TITLE
Dynamic light from a single frame of an animated texture?

### ISSUE THREAD

**Issue by TheSexyYeti** [sp614x/optifine#5155]
I guess this is kind of a feature request. It's more of a "Can it be done?" kind of thing. I'm working on a resource pack. And in this pack I want certain items like torches and sword with the fire aspect enchantment to emit a dynamic light. Even further I want these items to have an animated texture and I want the light levels to change between animation frames so the light flickers like a realistic flame would. Would it be possible to do this without coding a entire mod for this purpose?. Can this be stored within a textures properties to call up the dynamic light function during the frame of an animated texture?.

**Comment by sp614x** [comment]
The dynamic light level is dependent on the item itself, not on its texture.
It is not possible to make the light level depending on the animation.
