### ISSUE TITLE
Cape just.. disappeared?

### ISSUE THREAD

**Issue by jxcksad** [sp614x/optifine#5157]
A guy bought me a cape about 1-2 years ago and I've had it ever since, however today I noticed it's just disappeared. 

It just says the cape can't be found but I've transferred the cape to my alt before (and transferred it back) and when I go on "Cape Editor" with that it says it was transferred to my old minecraft username. But I can remember having the cape with this current username but apparently it just doesn't exist? Something to note; I don't think the guy took back the cape since he already had one himself at the time.

**Comment by sp614x** [comment]
The issue tracker is for problems with OptiFine only.
You can write to "optifinex@gmail.com" for help with the cape.
