### ISSUE TITLE
[Shaders] Optifine Crashes with Shaders

### ISSUE THREAD

**Issue by StanCEmpire** [sp614x/optifine#5158]
So in the latest optifine install, every time I load a world with shaders on the game crashes.

To reproduce this, open up MC with optifine installed and shaders enabled (I was using Sildur's Vibrant, I'm not sure if it happens with other shaders). Shortly after the world has started loading, the game crashes.

Optifine Version: 1.16.4-Optifine_HD_U_G6_pre3

Installation by running the .jar installation file

Crash Reports: 
[crash-2020-12-30_10.10.30-client.txt](https://github.com/sp614x/optifine/files/5752516/crash-2020-12-30_10.10.30-client.txt)
[crash-2020-12-30_10.11.12-client.txt](https://github.com/sp614x/optifine/files/5752517/crash-2020-12-30_10.11.12-client.txt)

Logs:
[latest.log](https://github.com/sp614x/optifine/files/5752521/latest.log)

Debug Screenshot taken without shaders because I could not load the world with shaders
![2020-12-30_10 25 43](https://user-images.githubusercontent.com/59638278/103320434-73e08100-4a89-11eb-8665-031e256f4af3.png)

Have tested in vanilla. Obviously there are no external shaders in vanilla and so from my testing this does not occur in vanilla.

As mentioned I haven't tested with other shaders to I'm not sure if its a bug with sildurs or not.

**Comment by sp614x** [comment]
Fixed in 1.16.4 pre4.
