### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by drgnswllkllusall** [sp614x/optifine#516]
So I'm using OptiFine 1.11.2 HD U B7 and when looking in water I just see white and OpenGL Error 1281 pops up please help
Underwater
![2017-03-05_16 09 36](https://cloud.githubusercontent.com/assets/26207391/23591460/d639fc54-01be-11e7-9615-f08a93473027.png)
Above Water
![2017-03-05_16 09 41](https://cloud.githubusercontent.com/assets/26207391/23591461/df9cabd4-01be-11e7-821b-e6af71c08be8.png)

**Comment by sp614x** [comment]
Can you post the game output (error log)?

**Comment by drgnswllkllusall** [comment]
Here it is
![image](https://cloud.githubusercontent.com/assets/26207391/24068183/9f911990-0b5e-11e7-95d3-adb6a808775f.png)

**Comment by KaiAF** [comment]
Looks like this could have been fixed already. If you are still having any issue, let us know.
