### ISSUE TITLE
[1.8.x - 1.7.x] Weird Mouse stutter / acceleration when on Optifine

### ISSUE THREAD

**Issue by MogManek** [sp614x/optifine#5162]
I have an issue that when i play on fullscreen my mouse weirdly "jumps" from place to place like fps drops but my fps are stable. When im on windowed this problem does not exist.

**Comment by Piipperi** [comment]
I was having this issue too a while back on 1.8.9 if I had programs open in the background taxing my CPU/GPU. I have not seen this issue tho since upgrading my GPU, but after upgrading my GPU I also turned off VSync, maybe VSync is conflicting with this (if you have it turned on, that is)

**Comment by MogManek** [comment]
Nope, have VSync turned off. Even without any programs in BG.

**Comment by karmette** [comment]
Follow the format of reporting a bug

**Comment by KaiAF** [comment]
Most likely this bug is not actually related to OptiFine. Seems like it's a mouse issue? If you are still having this issue, create a new bug report with the right format.
