### ISSUE TITLE
[Shaders] anisotropic filtering with shaders break normal and specular maps and item rendering

### ISSUE THREAD

**Issue by fayer3** [sp614x/optifine#5175]
## Description of Issue
Enabling anisotropic filtering with shaders breaks item/block rendering in gui, hand and dropped items.
Also if a shader uses normal or specular maps, they are also broken.

## Steps to Reproduce
1. enable shaders and anisotropic filtering
2. see that items in HUD and hand show the complete atlas
3. use a shader that supports normal and specular maps, look at a block against the sun, you will also see the complete atlas

## OptiFine Version
1.16.4 HD U G6 pre6

## Installation Method
standalone installer

## F3 Debug Screenshot
hand/GUI /dropped Items broken even on internal:
![2021-01-02_18 08 19](https://user-images.githubusercontent.com/8282299/103462446-81b23280-4d25-11eb-897a-8195b40f4798.png)

specular/normals broken, here with Kappa v3 and vanillaccurate x16:
![2021-01-02_16 04 10](https://user-images.githubusercontent.com/8282299/103462353-fb95ec00-4d24-11eb-8d7c-6b8d17fa01ae.png)

## Prior Testing
- only happens with AF and shaders

**Comment by sp614x** [comment]
Fixed item rendering.

**Comment by sp614x** [comment]
Fixed in 1.16.4 pre7
