### ISSUE TITLE
OpenGL Error: 1281 (Invalid Issue) happens when using Mekanism machines

### ISSUE THREAD

**Issue by StressfulHamster** [sp614x/optifine#5176]
that error happens on every world when placing some machines and my world becomes transparent like in the picture below
![image](https://user-images.githubusercontent.com/24390001/103466077-d95e9700-4d41-11eb-9a82-5d52c80fe22e.png)

**Comment by KaiAF** [comment]
Do you have fast render enabled? Could be something with graphics drivers?

**Comment by KaiAF** [comment]
Assuming this is resolved now.
