### ISSUE TITLE
Fullscreen issue

### ISSUE THREAD

**Issue by DonaldDoc** [sp614x/optifine#5178]
## Description of Issue
If you have macOS Big Sur and you go fullscreen on 1.8.9, the game will show you a white screen.

## Steps to Reproduce
1. Install macOS Big Sur, download Optifine for 1.8.9, go fullscreen

## OptiFine Version
OptiFine HD U L5

## Installation Method
Installed from optifine.net 

## F3 Debug Screenshot
Cant capture.

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
- No, it happens only in optifine.

**Comment by Regnander** [comment]
Related #5028 and #5034

**Comment by ZenIsBestWolf** [comment]
Duplicate of #5028
