### ISSUE TITLE
Key binding bug?

### ISSUE THREAD

**Issue by sp614x** [sp614x/optifine#518]
By  LinguaOccultus:

Found a strange "bug" (?) in OptiFine that resets the key binding of a mod somehow. I added ItemZoom from mezz to our mods and set its key binding to just "X". But each time i restarted the game, the key binding (just that one) is reset to "Shift + X". So i spoke to mezz and he said it must be another mod. I then removed everything (including OptiFine which is running as mod since i use Forge; see below) from "mods" and "config" aside from the two ItemZoom files, removed the modifier offline directly in the "optioins.txt" and restarted again and it is NOT happening anymore. I then thought i have to go through all the mods one by one and started with OF but after restarting the game again, the key binding is reset immediately again. Mezz told me there was a Forge bug with the modifier keys but all other key bindings with and without modifiers are working. However, i also sometimes saw MC complaining about double use of keys (marking them red in the options) when i use for example "A" and "Shift + A" which normally should work. Other combinations like that work. I cannot say if that happens when setting keys for vanilla and mods that use one of the same keys or just mod keybindings under each other.

**Comment by sp614x** [comment]
By LinguaOccultus:

Tech is currently:

- Java 1.8.0.121 (x64)

- Minecraft 1.11.2

- Forge 13.20.0.2252 (MC 1.11.2)

- OptiFine HD U B7 (MC 1.11.2)

- Conquest Ressource Pack

- Several mods

My "options.txt" is (the lines in qiestion are "key_key.itemzoom.toggle:45:SHIFT" and "key_key.itemzoom.toggle:45"):

version:922
invertYMouse:false
mouseSensitivity:0.5
fov:0.0
gamma:0.5
saturation:0.0
renderDistance:24
guiScale:3
particles:0
bobView:true
anaglyph3d:false
maxFps:260
fboEnable:true
difficulty:2
fancyGraphics:true
ao:2
renderClouds:false
resourcePacks:["Conquest_1.11.zip"]
incompatibleResourcePacks:[]
lastServer:
lang:de_de
chatVisibility:0
chatColors:true
chatLinks:true
chatLinksPrompt:false
chatOpacity:1.0
snooperEnabled:false
fullscreen:true
enableVsync:true
useVbo:true
hideServerAddress:false
advancedItemTooltips:false
pauseOnLostFocus:true
touchscreen:false
overrideWidth:0
overrideHeight:0
heldItemTooltips:true
chatHeightFocused:1.0
chatHeightUnfocused:0.44366196
chatScale:1.0
chatWidth:1.0
showInventoryAchievementHint:false
mipmapLevels:4
forceUnicodeFont:false
reducedDebugInfo:false
useNativeTransport:true
entityShadows:true
mainHand:right
attackIndicator:0
showSubtitles:false
realmsNotifications:false
enableWeakAttacks:false
autoJump:false
key_key.attack:-100
key_key.use:-99
key_key.forward:17
key_key.left:30
key_key.back:31
key_key.right:32
key_key.jump:57
key_key.sneak:42
key_key.sprint:19
key_key.drop:-96
key_key.inventory:16
key_key.chat:28
key_key.playerlist:0
key_key.pickItem:0
key_key.command:14
key_key.screenshot:68
key_key.togglePerspective:67
key_key.smoothCamera:0
key_key.fullscreen:0
key_key.spectatorOutlines:0
key_key.swapHands:-97
key_key.hotbar.1:2
key_key.hotbar.2:3
key_key.hotbar.3:4
key_key.hotbar.4:5
key_key.hotbar.5:6
key_key.hotbar.6:7
key_key.hotbar.7:8
key_key.hotbar.8:9
key_key.hotbar.9:10
key_of.key.zoom:46
key_Toggle SelectionBox:0
key_Toggle Light Level:47
key_key.openNotes:35
key_mod.chiselsandbits.chiselmode.single:0
key_mod.chiselsandbits.chiselmode.snap2:0
key_mod.chiselsandbits.chiselmode.snap4:0
key_mod.chiselsandbits.chiselmode.snap8:0
key_mod.chiselsandbits.chiselmode.line:0
key_mod.chiselsandbits.chiselmode.plane:0
key_mod.chiselsandbits.chiselmode.connected_plane:0
key_mod.chiselsandbits.chiselmode.cube_small:0
key_mod.chiselsandbits.chiselmode.cube_medium:0
key_mod.chiselsandbits.chiselmode.cube_large:0
key_mod.chiselsandbits.chiselmode.same_material:0
key_mod.chiselsandbits.chiselmode.drawn_region:0
key_mod.chiselsandbits.chiselmode.connected_material:0
key_mod.chiselsandbits.positivepatternmode.replace:0
key_mod.chiselsandbits.positivepatternmode.additive:0
key_mod.chiselsandbits.positivepatternmode.placement:0
key_mod.chiselsandbits.positivepatternmode.impose:0
key_mod.chiselsandbits.tapemeasure.bit:0
key_mod.chiselsandbits.tapemeasure.block:0
key_mod.chiselsandbits.tapemeasure.distance:0
key_mod.chiselsandbits.other.mode:33
key_mod.chiselsandbits.other.rotate.ccw:0
key_mod.chiselsandbits.other.rotate.cw:34
key_mod.chiselsandbits.other.pickbit:0
key_mod.chiselsandbits.other.undo:0
key_mod.chiselsandbits.other.redo:0
key_mod.chiselsandbits.other.add_to_clipboard:0
key_key.betterHud.open:88
key_waila.keybind.wailaconfig:0
key_waila.keybind.wailadisplay:18
key_waila.keybind.liquid:0
key_waila.keybind.recipe:0
key_waila.keybind.usage:0
key_key.itemzoom.toggle:45:SHIFT
key_key.itemzoom.hold:0
key_key.itemzoom.zoom.in:0
key_key.itemzoom.zoom.out:0
key_key.jei.toggleOverlay:33:SHIFT
key_key.jei.focusSearch:33:CONTROL
key_key.jei.showRecipe:0
key_key.jei.showUses:0
key_key.jei.recipeBack:0
key_key.jei.toggleCheatMode:0
key_gui.xaero_minimap_settings:0
key_gui.xaero_switch_waypoint_set:0
key_gui.xaero_instant_waypoint:0
key_gui.xaero_toggle_slime:44
key_gui.xaero_toggle_grid:0
key_gui.xaero_toggle_waypoints:0
key_gui.xaero_toggle_map:0
key_gui.xaero_enlarge_map:43
key_gui.xaero_waypoints_key:20
key_gui.xaero_zoom_in:0
key_gui.xaero_zoom_out:0
key_gui.xaero_new_waypoint:0
key_gui.xaero_open_map:15
key_gui.xaero_open_settings:0
soundCategory_master:1.0
soundCategory_music:0.0
soundCategory_record:1.0
soundCategory_weather:1.0
soundCategory_block:1.0
soundCategory_hostile:1.0
soundCategory_neutral:1.0
soundCategory_player:1.0
soundCategory_ambient:1.0
soundCategory_voice:1.0
modelPart_cape:true
modelPart_jacket:true
modelPart_left_sleeve:true
modelPart_right_sleeve:true
modelPart_left_pants_leg:true
modelPart_right_pants_leg:true
modelPart_hat:true

**Comment by mezz** [comment]
I am getting reports from this.

To support key modifiers, Forge alters the save format for key bindings slightly to include the modifier.
You can see some keys with modifiers in the report above: 
```
...
key_key.itemzoom.toggle:45:SHIFT
key_key.itemzoom.hold:0
key_key.itemzoom.zoom.in:0
key_key.itemzoom.zoom.out:0
key_key.jei.toggleOverlay:33:SHIFT
key_key.jei.focusSearch:33:CONTROL
...
```
Loading keybinds in `GameSettings.java` has been changed to this:
```java
for (KeyBinding keybinding : this.keyBindings)
{
    if (s1.equals("key_" + keybinding.getKeyDescription()))
    {
        if (s2.indexOf(':') != -1)
        {
            String[] t = s2.split(":");
            keybinding.setKeyModifierAndCode(net.minecraftforge.client.settings.KeyModifier.valueFromString(t[1]), Integer.parseInt(t[0]));
        } else
        keybinding.setKeyModifierAndCode(net.minecraftforge.client.settings.KeyModifier.NONE, Integer.parseInt(s2));
    }
}
```

I assume Optifine is replacing the whole GameSettings file or something? Seems very odd that Optifine is involved at all, I'd like to know more.

**Comment by sp614x** [comment]
Updated preview C1 for 1.11.2
- fixed compatibility with Forge key modifiers (#518)
