### ISSUE TITLE
[Bug] Anisotropic Filtering with glass

### ISSUE THREAD

**Issue by JOHN30011887** [sp614x/optifine#5181]
Using latest 1.16 optifine OptiFine HD U G6 pre9 and tried OptiFine HD U G5.

Super easy to reproduce - 
When turning on Anisotropic Filtering (doesnt matter which number used) the glass blocks and glass panels any colors both end up with gaps and flicker from visible to invisible depending how you look at them (i was in creative mode to notice)

When i turn Anisotropic Filtering off then bug goes away with glass but then i notice the game world has shimmering effect on everything, especially grass blocks and plants, noticed it more when using any texture pack so Anisotropic Filtering needs to be on to fix that

Glass seems to be the only issue with Anisotropic Filtering that iv come across so far...

**Comment by Redstone-Ghost** [comment]
i am having the same issue
so here is a picture ![optifine anisotropic filtering problem](https://user-images.githubusercontent.com/37518781/110843453-4cbae280-8276-11eb-9cb9-4d9fd020f100.png)

**Comment by JOHN30011887** [comment]
Yup thats exactly how the issue looks in that pic, still does it in the latest 1.16.5_HD_U_G8_pre5

**Comment by sp614x** [comment]
Fixed, coming in next preview.
