### ISSUE TITLE
[MipMap] Full Nearest generation and filtering.

### ISSUE THREAD

**Issue by null511** [sp614x/optifine#5182]
Filing a formal ticket for the issues discussed in the ShaderLabs discord: For mipmapping to work properly with non-blending values such as metals, two features will be required:

## Nearest MipMap Generation
First would be to prevent blending in the mipmaps themselves, which would require the option to use nearest sampling when generating mipmaps. The most ideal option would be to allow configuration per color channel, so other packed channels can still benefit from blending; but at a minimum this should be per texture-type (color, normal, specular).

## Nearest MipMap Filtering
The current "nearest" mipmapping option uses `GL_LINEAR_MIPMAP_NEAREST`, which uses _linear_ pixel blending at the _nearest_ mipmap level. Adding support for using `GL_NEAREST_MIPMAP_NEAREST` will allow shaders to properly sample mipmaps without _any_ pixel blending.

---

The current workaround is to disable mipmapping entirely, but the cost of this increases with texture resolution. MipMaps with nearest filtering should reduce the "pixel jump" that occurs with these high-res textures at distance. The same blending issue can be much more easily seen with wrapped/clipped channels such as LabPbr emissives; with this format, values increase lumination from 0 to 254, and 255 is completely unlit. When a dimly lit pixel [8] is blended with a clipped value [255]. it creates a very bright area [128] instead of ~4. In this scenario either [4] or [255] would be preferred, even if flickering is introduced.

![2021-01-05_00 27 15](https://user-images.githubusercontent.com/17755767/103611485-65aebc80-4ef0-11eb-958f-ce26c86836da.png)

**Comment by sp614x** [comment]
If I understand correctly, the problem is that some texture formats (LabPbr) want to use specific values as discrete values which are not to be mixed with the normal continuous colors.

For example: 

LabPbr Specular.Green
- values 0 to 229 represent f0 - linear, can be mixed with other f0 values
- values 230 to 255 are various discrete metals - can't be mixed with anything else

LabPbr Specular.Blue
- values 0 to 64 is porosity - can be mixed with other porosity
- values 65 to 255 is subsurface-scattering - can only be mixed with other subsurface-scattering

**Comment by sp614x** [comment]
The main problem is that the mipmap generation has to follow some rules when mixing the colors. 
The runtime hardware mixing is not configurable, so it has to be turned off (gl_nearest_mipmap_nearest).
The mipmap color mixing always takes 4 input colors and produces one output color. These could use different strategy per channel.

The general mixing strategy would be:
A. Select which type (range) the output should be
B. Mix the input colors of this type (if mixable) and produce the output

Selecting the output type is to be done by counting colors by type and the type with most values wins. Undecided is 2 vs 2 in which case it could use a random choice to avoid having a bias towards a specific type or ordering.

When the output type is discrete and there is no clear majority, the output discrete value would also have to be randomly selected to avoid having a bias.

For example (Fx = f0, Mx = discrete metal, "|" = either)

`F1 + F2 + F3 + M1 => (F1 + F2 + F3) / 3`  - type by majority, value mixed
`M1 + M1 + M2 + F1 => M1` - type by majority, value by majority
`M1 + M2 + M3 + F1 => M1 | M2 | M3` - type by majority, value by random
`F1 + F2 + M3 + M4 => ((F1 + F2) / 2) | (M3 | M4)` - type by random, value mixed or random

**Comment by null511** [comment]
I was trying to aim low, I believe most would be happy with simple rounding down to top-left; but yes that sounds perfect. I have been wanting to test the idea of "dominant" pixels when multisampling (for resource pack publishing), but I haven't had time to test it myself. In theory that should help preserve a bit more detail. Unfortunately I don't have a specification to propose for configuring such options, but clearly you fully understand the requirements.

**Comment by sp614x** [comment]
Ideally the texture format should be configured in the resource pack and OptiFine should add a macro that shaders can use. 
For example `#define MC_TEXTURE_FORMAT_LAB_PBR`.

**Comment by sp614x** [comment]
Example for LabPbr split mipmaps + nearest filtering:

![image](https://user-images.githubusercontent.com/16635441/104079173-f7386a00-5221-11eb-90b2-11c70c02cc94.png)

Dark green (0 to 150) are f0 pixels and they are blend with other f0 pixels.
Light green (230 and 255) are binary metals and they don't blend with f0 pixels or other metals.

**Comment by sp614x** [comment]
With type bias towards first pixel the mipmaps tend to shift in the distance:

![image](https://user-images.githubusercontent.com/16635441/104079519-d53fe700-5223-11eb-886a-9aaf04113137.png)

**Comment by sp614x** [comment]
The RP configuration would look like:
```
###############################################################################
# Sample configuration for texture properties
# Location: /assets/minecraft/optifine/texture.properties
###############################################################################
# Format
# Texture format used for normal and specular shader textures
# LabPbr: https://github.com/rre36/lab-pbr/wiki 
format=lab-pbr
```

**Comment by null511** [comment]
Given the expected issues, your first screenshot looks like a much cleaner result. In my opinion it is much safer to discard these metals rather than applying a metal effect to a non-metal albedo pixel.

**Comment by sp614x** [comment]
Coming in pre11.
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/texture.properties
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.txt#L664
