### ISSUE TITLE
Crash With Forestry

### ISSUE THREAD

**Issue by kenijey** [sp614x/optifine#519]
I don't know why this happened.
[crash-2017-03-10_15.46.47-client.txt](https://github.com/sp614x/optifine/files/833951/crash-2017-03-10_15.46.47-client.txt)
i was in a jungle.

**Comment by kenijey** [comment]
still crashing :( 
[crash-2017-03-12_13.41.00-client.txt](https://github.com/sp614x/optifine/files/836445/crash-2017-03-12_13.41.00-client.txt)

**Comment by kenijey** [comment]
and it'as solved when i disable connected textures. but i want to use connected textures feature :( ...

**Comment by kenijey** [comment]
please fix this :(

**Comment by sp614x** [comment]
Forestry crashes in TileUtil because the world is NULL:
https://github.com/ForestryMC/ForestryMC/blob/mc-1.11/src/main/java/forestry/core/tiles/TileUtil.java#L54

**Comment by sp614x** [comment]
The world is taken from IExtendedState:
https://github.com/ForestryMC/ForestryMC/blob/mc-1.11/src/main/java/forestry/arboriculture/models/ModelLeaves.java#L94

OptiFine is not changing the IExtendedState.

**Comment by sp614x** [comment]
The BLOCKASSESS property is a non-standard Forestry feature:
https://github.com/ForestryMC/ForestryMC/blob/mc-1.11/src/main/java/forestry/core/blocks/properties/UnlistedBlockAccess.java#L17

This can not be fixed in OptiFine.

**Comment by kenijey** [comment]
So? Forestry should fix it?

**Comment by sp614x** [comment]
It should be fixed in Forestry.
