### ISSUE TITLE
[CRASH] Worlds cannot be created or loaded

### ISSUE THREAD

**Issue by Gravity10** [sp614x/optifine#5190]
## "Unexpected Errors" occur when any world is created or loaded with shaders
In the past few days (no updates or changes to any settings to prompt this), Optifine has started crashing Minecraft and returning to the launcher with an "Unexpected Error" message. Uninstalling and reinstalling Optifine doesn't fix the issues, reinstalling Minecraft and installing G5 or G6 pre10 versions of Optifine still result in the crash. Forge was tested as well, and with a stable installation of Forge and Optifine in the "mods" folder the crash still occurred. I tried resetting my graphics drivers to factory settings and clearing the shader cache, neither worked.

Attempting to create a world with a shader pack enabled in any of the above situations results in the Unexpected Error. Loading a previously created world with a shader pack enabled also results in the error, and loading the world without one and changing it in-game does the same.

### OptiFine Versions:
OptiFine HD U G6 pre10
OptiFine HD U G5

### Installation Method
Both the standalone installer and dropping into the Forge "mods" folder were tried.

### Fabric/Forge Version
Forge 1.16.4 - 35.1.4

### Other Installed Mods
No other installed mods

### Log Files/Crash Reports
[hs_err_pid4784.log](https://github.com/sp614x/optifine/files/5778874/hs_err_pid4784.log)

### F3 Debug Screenshot
Cannot get the screenshot in-game with shaders enabled, here's it with them off:
![2021-01-06_19 47 36](https://user-images.githubusercontent.com/76815426/103836805-1b484f80-5058-11eb-9f0a-48472f4209e4.png)

Here's the screen about 1 second before crashing when loading a shader in-game:
![2021-01-06_19 49 17](https://user-images.githubusercontent.com/76815426/103836918-6cf0da00-5058-11eb-90b8-540faf27240a.png)

### Prior Testing
Occurs with and without other mods in Forge
Occurs from the Optifine standalone installation
Crash doesn't occur in Vanilla Minecraft without Optifine

### Additional Information
Started occurring when I added gbuffers_entities.vsh and fsh into my shader pack? Not sure if that helps at all.

**Comment by Gravity10** [comment]
So far I've figured out that certain shaders work, most likely due to errors not caught by Optifine and just crashing OpenGL.

Reported working shaders:
Builders Shaders
GravityShade

**Comment by KaiAF** [comment]
The error is due to an AMD Driver. Most likely it's an issue with AMD, and if that's the case, we cannot fix this.
