### ISSUE TITLE
Minecraft keeps crashing every few minutes with shaders

### ISSUE THREAD

**Issue by vinnyg0621** [sp614x/optifine#5191]
Shaders have been crashing my game for no exact reason because of Java. It says I need to update my driver card, but I already did

## OptiFine Version
1.16.4 HD U G6 pre10

## Log Files/Crash Reports
https://hastebin.com/egefilenef.yaml

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine? no

**Comment by Gravity10** [comment]
Same, I think it's a new issue that just came up. Not sure if Minecraft or Optifine had a random update in the past day or two? But something's up, I've been getting crashes too

**Comment by vinnyg0621** [comment]
it doesn't crash with Builder's Modded shaders

**Comment by Gravity10** [comment]
After a LOT more testing, it looks like there are a couple of things that are included in shaders that aren't "GLSL errors", but Optifine will fatally crash while running. One such thing is:
#### #include "lib/light.glsl";
as opposed to
#### #include "lib/light.glsl"
The semicolon at the end of the line will result in a fatal crash? Unsure as to why Optifine won't just report an error and not run, but maybe that's something that could be addressed at some point.

**Comment by EnderHunter14** [comment]
I've been getting crashes too, and I think it's Optifine, they need to update Optifine

**Comment by EnderHunter14** [comment]
It works alone, but on Forge, it doesn't

**Comment by Gravity10** [comment]
Good news, a couple shaders are more reliable than others. There may be a weird file reading error on Optifine's part...?

GravityShade: Works 100% of the time in my testing, reloading shaders/creating worlds doesn't crash it.
[https://gravityshade.netlify.app/](https://gravityshade.netlify.app/)

Builder's Modded Shaders: As stated above, it is said to work. I haven't tested it fully yet, but it seems to be somewhat stable.
[https://www.dropbox.com/sh/bko0b0ctaovdwda/AACStbybl9uhCkP6TtFfFPIAa?dl=0](https://www.dropbox.com/sh/bko0b0ctaovdwda/AACStbybl9uhCkP6TtFfFPIAa?dl=0)

**Comment by KaiAF** [comment]
If you are still having any issues, please edit your post and put in a working Pastebin link.
