### ISSUE TITLE
[Category] Minecraft crashing

### ISSUE THREAD

**Issue by lilsitrus** [sp614x/optifine#5192]
## Description of Issue
Every time i turn on shaders or turn off shaders minecraft crashes sometimes before i get it on / off

## Steps to Reproduce
1. just turn on shaders or off.

## OptiFine Version
Self-explanatory. 

## Installation Method
How did you install OptiFine? Did you use the included standalone installer, or did you drop the JAR file into your "mods" folder?
- Standalone innstaler

## Other Installed Mods
*Every* single mod you have installed, besides OptiFine. Please don't leave anything out, even if you think it has nothing to do with the issue at hand. For long lists of mods, use Pastebin. https://pastebin.com/

## Log Files/Crash Reports
Any relevant log files. Drag and drop text files here to upload to GitHub directly, OR upload the complete contents to Pastebin. https://pastebin.com/

You can get logs from `.minecraft/logs`, and crash reports from `.minecraft/crash-reports`. 
Locating your `.minecraft` folder will depend entirely on your OS. See this page for details: https://minecraft.gamepedia.com/.minecraft

**DO NOT directly copy and paste log contents here on GitHub.**

## F3 Debug Screenshot
Minecraft's built-in debug screen provides *a lot* of useful information, and should be included even if the issue is not something that can be captured in a still image.

To open this menu, simply press `F3` on your keyboard while in-game. Please ensure the text is easily readable. Depending on the size/resolution of your monitor, you may have to adjust your GUI scale for all text to be completely visible on-screen.

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   - Only OptiFine and Forge
   - Only OptiFine, OptiFabric, and Fabric
- Does this happen without any mods at all?
   - Only Forge/Fabric by itself.
- Does this happen in OptiFine standalone?
- Does this happen in Vanilla without OptiFine?
- Have you tried using a binary search to find which mods cause this issue?
   - To find conflicting mods, split your mods into 2 groups (not including OptiFine/OptiFabric, obviously). Remove one group, and test in-game. Keep the group that has the problem, and repeat until no more mods can be removed without the issue disappearing.
   - Does the issue still happen with only the remaining mods installed?
      - Forge/Fabric and remaining mods, without OptiFine

## Additional Information
Here goes any final remarks and everything else that might not fit in the previous sections.

**Comment by Gravity10** [comment]
Same, it's become really common in the past few days. Maybe a broken patch to MC or Optifine?

**Comment by Gravity10** [comment]
Hi, quick question out of curiosity, what shader pack are you turning on and off? There might be an issue with Optifine not catching errors due to semicolons.

**Comment by caillou15** [comment]
For me Minecraft crash when i use a shader other than 'internal' and the log output say 'EXCEPTION_ACCESS_VIOLATION'

**Comment by sp614x** [comment]
Which OptiFine version?
Which shader pack?
Error log, crash report?

**Comment by caillou15** [comment]
version:1.16.4-Optifine-HD_U_G6_pre12
shader pack: Sildur's Vibrant Shaders v1.22 High
(I changed to a newer version (1.28) and it worked fine)
crash report:
[hs_err_pid4688.log](https://github.com/sp614x/optifine/files/5831963/hs_err_pid4688.log)

I found on the internet that it can be a problem with my graphic drivers
but I am unable to reproduce the situation that crash

**Comment by KaiAF** [comment]
No response from the author. 
@caillou15 Looks like it could be something with your GPU drivers
