### ISSUE TITLE
Ran Minecraft 1.16.4 previously, but Optifine can't find it

### ISSUE THREAD

**Issue by SpiritOfWrath** [sp614x/optifine#5193]
## Description of Issue
Have ran Minecraft 1.16.4 everyday for the past week. Tried to install Optifine with the installation going to Appdata\Roaming\.minecraft, but it comes up with the error message "Cannot find Minecraft 1.16.4. You must download and start Minecraft once in the official launcher."

## Steps to Reproduce
None specific

## OptiFine Version
For 1.16.4

## Installation Method
Standalone installer. No other mods. Also tried to install forge to use that method, but forge can't find 1.16.4 either.

## Log Files/Crash Reports
Image of 1.16.4 definitely being there. Censored bit is my real life name.
![image](https://user-images.githubusercontent.com/33721041/103898807-66607200-50ed-11eb-98e8-2c67464e70ec.png)

Latest log available. I think it may be from while I was playing vanilla minecraft, before attempting installation.
[latest.log](https://github.com/sp614x/optifine/files/5781880/latest.log)

## F3 Debug Screenshot
![image](https://user-images.githubusercontent.com/33721041/103899839-e63b0c00-50ee-11eb-80b4-2d30c4566251.png)

## Prior Testing
N/A

## Additional Information
If you need more info, I am best emailed on thespirit.of.wrath@gmail.com, or messaged on Discord SpiritOfWrath#6515. I rarely use github. May need to explain where I can get the information, as I am a bona fide idiot.

**Comment by MennoGamed** [comment]
Try to completely uninstall minecraft 1.16.4 and install it again. Or you can update to 1.16.5 in the meantime.

**Comment by KaiAF** [comment]
Are you still having this issue?

**Comment by gginc1745** [comment]
Same problem, but my forge works.

**Comment by MennoGamed** [comment]
Optifine and forge have both been out for 1.16.5, Download the optifine version [here](https://optifine.net/downloads).

If that version doesn't work, there are beta versions of optfine.
I myself use the beta version together with fabric and optibric. This is going to be no problem.

**Comment by gginc1745** [comment]
I got it to work. I tried installing as a mod, but idk why it didnt work before, but it works now

**Comment by KaiAF** [comment]
No reply from author, closing.
