### ISSUE TITLE
Optifine only giving small JAR file

### ISSUE THREAD

**Issue by TheHitchhiker1** [sp614x/optifine#5194]
## Description of Issue
As i went to down load the optifine thing it would only download a file i can only open with notepad. That is the problem it is not a bug with optifine it is there is an absence of it

## Steps to Reproduce
1. I downloaded the file
2. and it gave me the wrong file
## OptiFine Version
Self-explanatory. 

## Installation Method
I got it from your website and it did not give me an installer

## Other Installed Mods
I have no mods for 1.16.4

## Log Files/Crash Reports
I did not get any crash reports while having this problem

## F3 Debug Screenshot
well i cant get the installer so this cant help

## Prior Testing
tried before for 1.8.9 but i had to use forger for that version

## Additional Information
it happened with forge too for 1.16.4

**Comment by berkkrkc09** [comment]
1. Download and run Jarfix: https://johann.loefflmann.net/en/software/jarfix/index.html     (Asuming Java is installed on your device)
2. Try to run OptiFine installer again.

**Comment by KaiAF** [comment]
Are you still having this issue?

**Comment by TheHitchhiker1** [comment]
No I found a thing called JARFIX and that fixed it!
