### ISSUE TITLE
Textures not loading

### ISSUE THREAD

**Issue by Oukej21** [sp614x/optifine#5195]
## Description of Issue
If im playing with optifine, block textures are invisible and skins are not loaded. 

## Steps to Reproduce
1. Run Optifine. (with Forge or alone)
2. Join to any server

## OptiFine Version
OptiFine HD U G5 (1.16.3 or 1.16.4)
## Installation Method
Used the executable .jar and installed directly on the laucher
Also tried put to mods folder and run with Forge.

## Fabric/Forge Version
Forge 1.16.4 - 35.1.32

Collective-Library-1.16.4
forgemod_VoxelMap-1.10.11_for_1.16.3
fullbrightnesstoggle_1.16.4-1.1
Inventory-HUD+-Mod-1.16.4

## Log Files/Crash Reports
[latest.log](https://github.com/sp614x/optifine/files/5782670/latest.log)

## F3 Debug Screenshot
![2021-01-07_17 06 40](https://user-images.githubusercontent.com/77114726/103915070-ffea4c80-510a-11eb-8240-1e978a2f67ab.png)

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine? - No

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? - Yes
   - Only OptiFine and Forge
- Does this happen without any mods at all? - No
   - Only Forge/Fabric by itself.
- Does this happen in OptiFine standalone? - Yes
- Does this happen in Vanilla without OptiFine? - No
- Have you tried using a binary search to find which mods cause this issue? - Yes
   - Does the issue still happen with only the remaining mods installed? - No
      - Forge/Fabric and remaining mods, without OptiFine

## Additional Information
I think it's not caused by the internet connection, because this does happen although i was trying different internet sources.
I have this mods for several times and this has been happening since last week.

**Comment by sp614x** [comment]
Fixed, coming in 1.16.4 pre13.
