### ISSUE TITLE
"OptiFine_1.9.0_HD_U_B1.jar" wont be loaded by MagicLauncher

### ISSUE THREAD

**Issue by Jumpy91** [sp614x/optifine#52]
Hey,
"OptiFine_1.9.0_HD_U_B1.jar" wont be loaded by MagicLauncher. While adding it says "no mods found" please fix this issue in newer versions.

Ty
Jumpy

**Comment by sp614x** [comment]
Double-click the jar file and select Extract, the extracted jar can be used with Magic Launcher.
Alternatively you can install Forge and put OptiFine in the mods folder.
Magic Launcher is going to be updated so it can load the jar directly.

**Comment by Jumpy91** [comment]
Thank you for the really fast reply. It worked.
