### ISSUE TITLE
[Cape issue] Optfine cape not showing up.

### ISSUE THREAD

**Issue by Haleien** [sp614x/optifine#5205]
The problem is that my optifine cape does not show up, not on anyone else either. i have tried uninstalling minecraft but it does not work either.

**Comment by amime-dev** [comment]
No Optifine cape for you

**Comment by KaiAF** [comment]
Are you still having this issue? If so, try resetting your video settings. 
If that doesn't help, go to our support channel on discord. https://optifine.net/discord
