### ISSUE TITLE
[Category] Short description

### ISSUE THREAD

**Issue by peterbarn123890** [sp614x/optifine#5206]
## Description of Issue
Optifine isnt working for me, when i put it in my mods folder for forge 35.1.36, it doesnt say any errors but the mod is not working. The video settings is completley vanilla and theres no zoom keybind

## Steps to Reproduce
1. Put preview optifine in my mods folder
2. launched minecraft

## OptiFine Version
Preview G6 Pre 12

## Installation Method
drop the JAR file into your "mods" folder?

## Fabric/Forge Version
Forge

## OptiFabric Version
**If OptiFine is installed as standalone, or you're using Forge, you can remove this section.**

## Other Installed Mods
Better Advancements
Biomes O' Plenty
Clumps
Dynamic Surroundings
Fast Leaf Decay
Mouse Tweaks
Nature's Compass
Sophisticated Backpacks
Storage Drawers
TerraForged
Waystones
[latest.log](https://github.com/sp614x/optifine/files/5793176/latest.log)
## Log Files/Crash Reports

![2021-01-10_14 21 17](https://user-images.githubusercontent.com/63478469/104133062-23053e00-534f-11eb-88e2-e6b4577ee7a2.png)

**Comment by sp614x** [comment]
You are not running with Forge. When Forge is active it should display this:

![image](https://user-images.githubusercontent.com/16635441/104133362-6da0ad80-5383-11eb-9b19-fdff251482cb.png)
