### ISSUE TITLE
[ALL DOCS] Showing ^M

### ISSUE THREAD

**Issue by barraIhsan** [sp614x/optifine#5210]
So this is a bug that I found annoying. When I read the official docs from this GitHub (https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/). So there is `^M` with red color
![image](https://user-images.githubusercontent.com/57800056/104328567-87c2c300-551e-11eb-9331-0431272561aa.png)

**Comment by Regnander** [comment]
You can remove them and make a pull request.

**Comment by sp614x** [comment]
This is a GitHub problem and only for properties files.
Compare `shaders.properties` and `shaders.txt`, both use the same line endings:
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.properties
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.txt
