### ISSUE TITLE
Optifine 1.12.2 keeps crashing instantly.

### ISSUE THREAD

**Issue by PixelHeadOfficial** [sp614x/optifine#5212]
## Description of Issue
OptiFine 1.12.2 Keeps crashing instantly after it finished opening up Minecraft.

## Steps to Reproduce
1. Click "Play"
2. Wait until the game finishes booting up.

## OptiFine Version
Optifine 1.12.2 HD U F5 

## Installation Method
Downloading the installer from optifined.net (or something) then running the jar

## Other Installed Mods
No mod has been installed.

**If OptiFine is installed as standalone, remove this section.**

## Log Files/Crash Reports
[hs_err_pid1100.log](https://github.com/sp614x/optifine/files/5806281/hs_err_pid1100.log)

You can get logs from `.minecraft/logs`, and crash reports from `.minecraft/crash-reports`. 
Locating your `.minecraft` folder will depend entirely on your OS. See this page for details: https://minecraft.gamepedia.com/.minecraft

**DO NOT directly copy and paste log contents here on GitHub.**

## F3 Debug Screenshot
Minecraft's built-in debug screen provides *a lot* of useful information, and should be included even if the issue is not something that can be captured in a still image.

To open this menu, simply press `F3` on your keyboard while in-game. Please ensure the text is easily readable. Depending on the size/resolution of your monitor, you may have to adjust your GUI scale for all text to be completely visible on-screen.

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   - Only OptiFine and Forge
   - Only OptiFine, OptiFabric, and Fabric
- Does this happen without any mods at all?
   - Only Forge/Fabric by itself.
- Does this happen in OptiFine standalone?
- Does this happen in Vanilla without OptiFine?
- Have you tried using a binary search to find which mods cause this issue?
   - To find conflicting mods, split your mods into 2 groups (not including OptiFine/OptiFabric, obviously). Remove one group, and test in-game. Keep the group that has the problem, and repeat until no more mods can be removed without the issue disappearing.
   - Does the issue still happen with only the remaining mods installed?
      - Forge/Fabric and remaining mods, without OptiFine

## Additional Information
Here goes any final remarks and everything else that might not fit in the previous sections.

**Comment by PixelHeadOfficial** [comment]
Update: This happens also in vanilla without OptiFine

**Comment by Gravity10** [comment]
Minecraft version 1.12 reportedly had issues with some graphics cards and chipsets, notably AMD graphics drivers. If that turns out to be the case, the only thing that I can think of would be updating Minecraft to a newer version or updating your drivers. Good luck!

**Comment by vinnyg0621** [comment]
who even plays on older versions for no reason at all? :P

**Comment by sp614x** [comment]
This is a native crash in the graphics driver:
```
# Problematic frame:
# C  [graphics-hook64.dll+0xe707]
```
Can't be fixed by OptiFine.

**Comment by ednellbasilio** [comment]
But my Minecraft JAVA edition android 

I enter the city map with render distance 5 it's seems crash again the forge crash again 
![Uploading Port-Vance-Map-Thumbnail.jpg…]()

**Comment by ednellbasilio** [comment]
![Uploading Port-Vance-Map-Thumbnail.jpg…]()

**Comment by ednellbasilio** [comment]
#5028
