### ISSUE TITLE
OF wont show/use custom resolution

### ISSUE THREAD

**Issue by x35gaming** [sp614x/optifine#5217]
yesterday, i had just upgraded to an rtx 3070 from my rx 580, and i had to redo my monitor overclock. i had done the overclock via nVidia contol panel and other games recognise the custom resolution.
the custom resolution i had previously used was set via amd's "adrenalin" tool, and had worked ever since my overclock.
## Steps to Reproduce
1. create a custom (overclocked) resolution on nVidia control panel 
2. run minecraft
3. have the fullscreen resolution set to "current"

## OptiFine Version
1.16.4-OptiFine-HD-U-G5

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine? yes

**Comment by KaiAF** [comment]
Are you still having this issue? Could have been something with GPU Drivers?

**Comment by x35gaming** [comment]
using cru it works, but i haven't gone back to nVidia control panel yet
