### ISSUE TITLE
optfine mekanism mod flamethrower crash

### ISSUE THREAD

**Issue by FullMetalMaster** [sp614x/optifine#5218]
anytime you load into a new world with OptiFine and mechanism and it's add-ons it will crash the game instantly same with servers

to reproduce use 1.16.4 For Forge with OptiFine HD U G5 and up make a world it will load saving world and hard crash the game.

## OptiFine Version
OptiFine HD U G5 and
OptiFine HD U G6 pre12
OptiFine HD U G6 pre11
OptiFine HD U G6 pre10

using the latest 1.16.4 Forge in a mods folders 

forge

## Other Installed Mods
https://pastebin.com/A2HkDiZZ

## Log Files/Crash Reports
https://www.mediafire.com/file/0cq085fjpohzgzh/logs_and_the_crash.zip/file (thought it better to use MediaFire so you can see all the logs)

## F3 Debug Screenshot
this is an image without OptiFine installed because obviously crashes on log in to any world.

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine? and no it works fine with out other mods

If you've installed using Forge
- Does this happen without other mods installed? 
 no
- Does this happen without any mods at all?
 no
- Does this happen in OptiFine standalone? no
- Does this happen in Vanilla without OptiFine? no
- Have you tried using a binary search to find which mods cause this issue? 
   Mekanism mod and Mekanism tools flamethrower Unfortunately they don't support OptiFine so I came here because of Crash wasn't happening it came out of nowhere. they were working together same verions recently till yesterday
   - Does the issue still happen with only the remaining mods installed?
      -no

https://www.curseforge.com/minecraft/mc-mods/mekanism 
you'll need this and all of the add-ons in the description to recreate the crash and see what's going on, I can only assume OptiFine doesn't agree with the particles from the flamethrower but I have no idea. Hope this gets fixed!

**Comment by FullMetalMaster** [comment]
forgot the f3 with no optifine in it my bad.

![image](https://user-images.githubusercontent.com/52523300/104816542-ebccdc00-57e9-11eb-9077-7664981dd592.png)

**Comment by TechniumUnlimited** [comment]
I too have this issue appearing but it only started appearing when I started a server and connected to the game with a client (w/ optifine) - kicks me from server on loadin with the same crash in crash log

**Comment by TechniumUnlimited** [comment]
@AshenGaming I have an update on this that someone in Mekanism github told me, that if your using forge 35.1.37, downgrade to 35.1.36 to fix this issue - I havent tried, instead, I removed all the logic from the flamethrower check that crashes the game, and built a custom version of mekanism, but the previous method might work for you lol

**Comment by AshenGaming** [comment]
> @AshenGaming I have an update on this that someone in Mekanism github told me, that if your using forge 35.1.37, downgrade to 35.1.36 to fix this issue

This did in fact work, even though I only changed the forge version on the client (Client was 35.1.36, Server was 35.1.37).

**Comment by KaiAF** [comment]
Is this still happening?

**Comment by Nydid** [comment]
> 
> 
> Is this still happening?

Still is on latest
