### ISSUE TITLE
[Shaders] Shadow Buffer improvements

### ISSUE THREAD

**Issue by WoMspace** [sp614x/optifine#5221]
Control over shadowcolor format in shaders, i.e. `const int shadowcolor0Format = RGBA32U;`
- Would allow much better voxelisation data packing
- Would allow shader developers to pack more data into the currently available shadow textures without losing too much precision.

This suggestion came through from shaderLABS as a result of the discussion around new buffer additions. Multiple shader devs have registered interest, including but not limited to Jessie, Builderb0y, and SixSeven.

I am WoMspace#7331 on discord, one of the liasons regarding the buffer conversation on shaderLABS

**Comment by sp614x** [comment]
Relevant #2780, #1712, #944.

**Comment by sp614x** [comment]
Coming in next preview.
