### ISSUE TITLE
glow effect does not work with the internal shaders

### ISSUE THREAD

**Issue by thunayzinho** [sp614x/optifine#5223]
## Description of Issue
when entities including the player receive the glowing effect it does not work on the internal shaders.

## Steps to Reproduce
1. if you use the command "/ effect give @e glowing 10" no mob or player will have the effect visible
2. it doesn't work if you hit entities with spectral arrows.

## OptiFine Version
Optifine HD U G5 1.16.4

## Installation Method
Mods folder

**Comment by sp614x** [comment]
Internal shaders are for testing only.
Using a shader pack can show the glow effect, it depends on the shader pack

**Comment by lajawi** [comment]
> 
> 
> Internal shaders are for testing only.
> Using a shader pack can show the glow effect, it depends on the shader pack

I love playing with the internal shader, because it has a little better lighting, why not update it? It's really annoying.
