### ISSUE TITLE
[Bug] Loading a world or creating a new world ends up on a black screen

### ISSUE THREAD

**Issue by InterestingError0** [sp614x/optifine#5227]
## Description of Issue
Loading a world or creating a new world ends up on a black screen.

## Steps to Reproduce
1. Start Minecraft with OptiFine
2. Load a world or create a new world

## OptiFine Version
OptiFine HD U G7 pre4

## Installation Method
I tried with the installer and with Forge. Both have the issue.

## Forge Version
Forge 1.16.5 - 36.0.1

## Other Installed Mods
WorldEdit

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
   No.

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   - Only OptiFine and Forge
      Yes.
- Does this happen without any mods at all?
   No.
- Does this happen in OptiFine standalone?
   Yes.
- Does this happen in Vanilla without OptiFine?
   No.
- Have you tried using a binary search to find which mods cause this issue?
   Yes. WorldEdit is not causing this issue.
   - Does the issue still happen with only the remaining mods installed?
      No.

## Additional Information
Here is a screen capture of the issue:

https://user-images.githubusercontent.com/63620497/105252546-a42cb400-5b4b-11eb-88b2-bf5260396168.mp4

**Comment by sp614x** [comment]
Can you post a debug screenshot (F3)?

**Comment by InterestingError0** [comment]
@sp614x No I can't. Pressing F3 doesn't do anything.

**Comment by InterestingError0** [comment]
Updated to OptiFine HD U G7 pre2, and it still has the issue.

**Comment by Gravity10** [comment]
Hi! I was having the **same** issue a little while ago. Optifine updated to G7 and it fixed it (kind of), but it might be dependant on what shader you have selected.

@sp614x, I don't know what my issue was last time but it might still be applicable here? I have debug screenshots attached to my issue

**Comment by InterestingError0** [comment]
@Gravity10 I'm not using any shaders...

**Comment by Gravity10** [comment]
![image](https://user-images.githubusercontent.com/76815426/105251814-33d16300-5b4a-11eb-9072-5b99525775c8.png)
Here's what shows up for me when I run MinecraftInstaller.msi, would you mind sharing what yours looks like?

**Comment by InterestingError0** [comment]
@Gravity10 This is what mine looks like:
![Screenshot (73)](https://user-images.githubusercontent.com/63620497/105252071-c1ad4e00-5b4a-11eb-9ed5-2686d481d7e6.png)

**Comment by InterestingError0** [comment]
Here is a screen capture of the issue:

https://user-images.githubusercontent.com/63620497/105252341-3bddd280-5b4b-11eb-9ad2-3de507bb85ec.mp4

**Comment by Gravity10** [comment]
Try going back to the normal version of Optifine instead of the Forge version, that's what worked for me in the past.

Also, that's really odd that the installer is like that. Maybe consider backing up your worlds and doing a clean install of Minecraft? The installer should be able to detect that you have the game installed, which (at the minimum) isn't helping he issue.

**Comment by InterestingError0** [comment]
@Gravity10 As you can see in the bug report, I already tried the installer, but it still had a black screen.

**Comment by InterestingError0** [comment]
@Gravity10 I just reinstalled Minecraft and it seemed to fix the issue.

**Comment by Gravity10** [comment]
Awesome! Glad I could help

**Comment by RedyAu** [comment]
This is happening to me as well. No other tips, just reinstall?
