### ISSUE TITLE
Screenshot (F2) crashes with "Division by 0" when Antialiasing is enabled

### ISSUE THREAD

**Issue by StalePhish** [sp614x/optifine#5228]
Optifine 1.16.5 HD U G6 gives a `Couldn't save screenshot: / by zero` error when F2 is pressed, and creates a 0 byte file on disk where the screenshot was expected to be produced. The vanilla 1.16.5 client does not exhibit this behavior.

![ScreenHunter_1619 2021 01 18 16 05](https://user-images.githubusercontent.com/2631979/104963081-c1288200-59a7-11eb-848b-d38196515f1f.png)

**Comment by FernandoSerio** [comment]
I started having that problem today, but I didn't remember that I had activated the antialiasing(Video settings>Quality), if you turn it off if I let you take screenshots

![2021-01-19_16 15 44](https://user-images.githubusercontent.com/30819881/105099687-afabac80-5a71-11eb-9141-1774ed696b18.png)

**Comment by StalePhish** [comment]
> I started having that problem today, but I didn't remember that I had activated the antialiasing(Video settings>Quality), if you turn it off if I let you take screenshots

That's a very strange but valid workaround! I have tested that changing the Antialiasing slider to 0 and restarting the game client did fix it, and changing it back and restarting did reproduce the issue again. Hopefully that will make it easier for the developers to fix.

**Comment by sp614x** [comment]
Fixed, coming in next preview.
