### ISSUE TITLE
[Bug] Minecraft crashes after alt+tab

### ISSUE THREAD

**Issue by PixenKnight** [sp614x/optifine#5229]
## Description of Issue
When playing in fullscreen in a singleplayer world or a multiplayer server, minecraft will crash after alt-tabbing to another window with exit code: 0. However, the launcher log says the process exited with code -1073740771.

## Steps to Reproduce
1. Enter a singleplayer world or multiplayer server.
2. Set window to fullscreen.
3. Press Alt+TAB.
4. Re-focus the minecraft window.
5. Crash.

## OptiFine Version
Minecraft 1.16.5 OptiFine HD U G6

## Installation Method
Standalone installer

## Log Files/Crash Reports
Minecraft game output: https://pastebin.com/BhztWCkX

There is no crash log.

## F3 Debug Screenshot
https://imgur.com/a/unMtI3V

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine? No

## Additional Information
This also happened with optifine on 1.16.4 Optifine HD U G5 and 1.16.3 Optifine HD U G3.

**Comment by KaiAF** [comment]
Judging from past Minecraft bug reports, this could be something due to your graphics card drivers? Try updating them if you still have this issue.

**Comment by KaiAF** [comment]
I assume you are not having this issue still. If I am wrong, please let me know

**Comment by 01000110-1** [comment]
im having this problem too.

**Comment by SimonYuuki** [comment]
I also have this problem on any version of the game (above 1.16.5) and I confirm that it comes from the graphics card because I tested with the graphics part of my processor and everything works fine, I specify that I have a Nvidia Geforce GTX 1650ti mobile.

**Comment by SimonYuuki** [comment]
In fact I solved the problem, it came from my mouse software that allows me to make game clips!
