### ISSUE TITLE
[1.12.2] With shaders, huge memory leak when minimized.

### ISSUE THREAD

**Issue by waltersamson** [sp614x/optifine#5231]
## Setup
- Windows 10
- Java 1.8.0_201
- Minecraft 1.12.2
- Optifine 1.12.2 HD_U_F5

## Steps to Reproduce
1. Prepare a clean install of Minecraft 1.12.2 with Optifine HD U F5, with no other addons;
2. Start Minecraft in **windowed mode**, load SEUS Renewed 1.0.1 or SEUS v11; (Leaks fastest with SEUS Renewed)
3. Create a new singleplayer world and start playing;
4. Press Windows+D to show desktop;

## Actual behavior
After pressing Windows+D, memory leak immediately begins. In ~60 seconds it fills the entire 16 GBs of RAM. The process might get killed by OS OOM handler. If it's not killed, memory usage will slowed decrease to normal in ~30 minutes.

However, directly switching to another workspace without pressing Windows+D will significantly reduce the chance of an immediate memory leak.

During the memory leak, GPU usage spikes to 100%.

## Expected behavior
A common pattern of playing Minecraft is planting or breeding something, then wait while doing other stuff on the computer. Thus the window losing focus is pretty common.

Also 1.12.2 is still quite popular in the modding community, so fixing this for 1.12.2 is greatly appreciated!

## Log Files/Crash Reports
http://paste.debian.net/plain/1181848

The last lines in the log shows the game pausing after losing focus at 00:07:28, the memory leak afterwards is not visible in the log.

![leak](https://user-images.githubusercontent.com/68768852/105063796-1e5f2900-5ab7-11eb-9685-9a0b72fe2f57.png)

## F3 Debug Screenshot
During the memory leak, game window is not responsive, thus not possible to capture debug screenshot.

**Comment by sp614x** [comment]
OptiFine doesn't know when the game is minimized and it doesn't do anything differently when minimized.
Looks like a bug in the graphics drivers.

**Comment by radonize** [comment]
Enabling "smooth fps" under performance settings fixes the issue for me

**Comment by 4194304** [comment]
encountered this and the other day it nearly crashed my computer with 32GB of RAM with Tea 2.0.0-dev5
