### ISSUE TITLE
I Can see entities through chests

### ISSUE THREAD

**Issue by DonkeyKing282** [sp614x/optifine#5235]
## Description of Issue
When I use any shaders i can see passive and hostile mobs through chests and player head blocks, it only happens when i use shaders but when i dont have them i cant see them

## OptiFine Version
1.16.5

## Installation Method
I downloaded it from the website

## Fabric/Forge Version
Forge

## F3 Debug Screenshot
Minecraft's built-in debug screen provides *a lot* of useful information, and should be included even if the issue is not something that can be captured in a still image.

To open this menu, simply press `F3` on your keyboard while in-game. Please ensure the text is easily readable. Depending on the size/resolution of your monitor, you may have to adjust your GUI scale for all text to be completely visible on-screen.

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   - Only OptiFine and Forge
   - Only OptiFine, OptiFabric, and Fabric
- Does this happen without any mods at all?
   - Only Forge/Fabric by itself.
- Does this happen in OptiFine standalone?
- Does this happen in Vanilla without OptiFine?
- Have you tried using a binary search to find which mods cause this issue?
   - To find conflicting mods, split your mods into 2 groups (not including OptiFine/OptiFabric, obviously). Remove one group, and test in-game. Keep the group that has the problem, and repeat until no more mods can be removed without the issue disappearing.
   - Does the issue still happen with only the remaining mods installed?
      - Forge/Fabric and remaining mods, without OptiFine

## Additional Information
Here goes any final remarks and everything else that might not fit in the previous sections.

**Comment by Gravity10** [comment]
Hi! It sounds like this might be an issue of the shaderpack that you are using.
If it's a public shader, I'd be interested to know which one so we can pinpoint whether the issue is Optifine or the Shader (or something else(
If it's a private/personal one, I'd recommend checking over the composite.fsh and final.fsh files if you're using a gdepth or depthtex sampler.
Good luck!

**Comment by DonkeyKing282** [comment]
> Hi! It sounds like this might be an issue of the shaderpack that you are using.
> If it's a public shader, I'd be interested to know which one so we can pinpoint whether the issue is Optifine or the Shader (or something else)
> If it's a private/personal one, I'd recommend checking over the composite.fsh and final.fsh files if you're using a gdepth or depthtex sampler.
> Good luck!

All the shaders i use cause me to see through chests, ive tried Sildurs Vibrant and continuum, if needed i can provide a screen shot if needed

**Comment by Gravity10** [comment]
A screenshot of the F3 debug screen while the entity is showing through would be the most helpful, I'm guessing.

With the current info, I'd say that your graphics drivers may be out of date and need updating. I'd recommend checking the provider's website for any updates or new software. If that doesn't fix your problem, check your Windows Update page for "Optional Updates", and install any that pertain to your graphics.

**Comment by KaiAF** [comment]
Are you still having this issue? @DonkeyKing282
