### ISSUE TITLE
[bug with shaders] the "glowing" effect doesnt have any colors with shaders on

### ISSUE THREAD

**Issue by mistershkolnik** [sp614x/optifine#5236]
## Description of Issue
BSL shader added "glowing" effect vanilla feature and it also supposed to have colored glowing variations which BSL shaders doesn't have.

this is how it should look vs how its not supposed to:
https://imgur.com/a/Q0orLcZ

## Steps to Reproduce
1. For example, go to hypixels server on 1.16.5
2. enter the TNT Lobby
3. you should find that glowing outline effect called "glowing"
4. check if it's white for BSL Shader and if its colored without.

## OptiFine Version
G6 Ultra 1.16.5

## Installation Method
included standalone installer

## Log Files/Crash Reports
none

## F3 Debug Screenshot
https://imgur.com/a/KGpJOYw

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?

nope

## Additional Information
none

**Comment by KaiAF** [comment]
Fast render and shaders are not compatible with the spectral arrow effect (Glowing effect). Disable fast render, and it should be fixed.
