### ISSUE TITLE
NBT matching does not work when keys have spaces

### ISSUE THREAD

**Issue by Tendrid** [sp614x/optifine#524]
I cant seem to add nbt flags with spaces in the keys to properties files.  I have verified that identical items (except for the namespace of the nbt flag) work without a space, but do not work with a space.  For instance, in the following examples, the first example works, while the second one fails:
 
works:
nbt.DenizenNBT.mid=bone
 
does not work:
nbt.Denizen NBT.mid=bone
 

Note:
Spaces in NBT tags are valid, but not used by the core Minecraft code base:
"The name of tags may contain spaces, although Minecraft itself never saves tags with spaces in the names." - http://minecraft.gamepedia.com/NBT_format

UPDATE:
After writing this ticket, i had the amazing idea to escape the space, and it worked!
works:
nbt.Denizen\ NBT.mid=bone

So, i'd like to alter this bug to simple update the docs to reflect this, because i spent a lot of time altering code before i figure this one out :D

**Comment by sp614x** [comment]
Have you tried this?

    nbt.Denizen\u0020NBT.mid=bone

**Comment by Tendrid** [comment]
I haven't, however the "\ " worked, and i'm fine with that syntax.
