### ISSUE TITLE
[Bug With Shaders] The spectral arrow "glowing" effect doesn't appear with any shaders

### ISSUE THREAD

**Issue by Disruption9900** [sp614x/optifine#5240]
## Description of Issue
Regardless of what shaders I use, The effect does not appear but if I select "off" on shaders, it works just fine.

## Steps to Reproduce
1.) Have optifine
2.) Activate a shader pack and shoot something with a spectral arrow

## OptiFine Version
OptiFine_1.16.3_HD_U_G5

## Installation Method
Standalone Installer

## Log Files/Crash Reports
None

## F3 Debug Screenshot
https://i.imgur.com/Vzvt0FO.png

## Prior Testing
- Does this happen in Vanilla without OptiFine?
No

**Comment by mistershkolnik** [comment]
check BSL Shaders, they work. So its just you need to implement it which seus didnt

**Comment by KaiAF** [comment]
Possibly related to this #4315.
