### ISSUE TITLE
[Bug] Changing Shaders on Main Menu Causes Refresh Loop

### ISSUE THREAD

**Issue by BBloom81** [sp614x/optifine#5244]
## Description of Issue
When changing shaders on the main menu, the game goes into a reload/refresh loop and has to be killed.

## Steps to Reproduce
1. Go to main menu
2. Change shaders (from BSL to internal) (From internal to SEUS) etc...

## OptiFine Version
OptiFine HD U G6

## Installation Method
Mod folder install

## Fabric/Forge Version
Fabric

## OptiFabric Version
OptiFabric-v1.8.16 ("patched" to run with 1.16.5)

## Other Installed Mods
AnvilFix, BoundingBoxOutlineReloaded, Carpet Extra, Carpet, Cloth Config, Dark Loading Screen, Fabric API, Light Level, Litematica, MaLiLib, MiniHUD, Mod Menu, OptiFabric, Shulker Box Tooltip, VoxelMap.

## Log Files/Crash Reports
Any relevant log files. Drag and drop text files here to upload to GitHub directly, OR upload the complete contents to Pastebin. https://pastebin.com/
[latest.log](https://github.com/sp614x/optifine/files/5859489/latest.log)

![2021-01-22_21 52 09](https://user-images.githubusercontent.com/65408805/105566803-21972680-5cfc-11eb-95a8-d50f65eacd8c.png)

## Prior Testing
If you've installed standalone:
- No shaders in Vanilla

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   - No Forge
   - Yes
- Does this happen without any mods at all?
   - No shaders without Optifine
- Does this happen in OptiFine standalone? Didn't try
- Does this happen in Vanilla without OptiFine? No shaders in vanilla
- Have you tried using a binary search to find which mods cause this issue? No.
   - To find conflicting mods, split your mods into 2 groups (not including OptiFine/OptiFabric, obviously). Remove one group, and test in-game. Keep the group that has the problem, and repeat until no more mods can be removed without the issue disappearing.
   - Does the issue still happen with only the remaining mods installed?
      - Forge/Fabric and remaining mods, without OptiFine  - Need Optifine for shaders

## Additional Information
Here goes any final remarks and everything else that might not fit in the previous sections.

**Comment by KaiAF** [comment]
If you update optifabric and optifine, does this still happen?

**Comment by KaiAF** [comment]
I cannot reproduce this. I have OptiFabric version 1.9.6, and Fabric-API version 0.32.5. OptiFine 1.16.5 G8 pre11. 

Without fabric-api, when switching shaders the loading screen shows up 100% of the time, with Fabric-API it only shows the loading screen 70% of the time. Maybe it's something with another mod / fabric? I don't know.

**Comment by BBloom81** [comment]
> I cannot reproduce this. I have OptiFabric version 1.9.6, and Fabric-API version 0.32.5. OptiFine 1.16.5 G8 pre11.
> 
> Without fabric-api, when switching shaders the loading screen shows up 100% of the time, with Fabric-API it only shows the loading screen 70% of the time. Maybe it's something with another mod / fabric? I don't know.

If you can't reproduce it, it's gotta be with something else, possibly even MultiMC (the weird issues I've encountered with that are pretty high).

Thank you for taking the time to look into it.  Apologies for wasting your time.
