### ISSUE TITLE
[BUG]Water turns light brown

### ISSUE THREAD

**Issue by jsr1976** [sp614x/optifine#5245]
Hi guys I patched Optifabric 1.8.6 to work with 1.16.5. All owrked fine but today water turns to light brown.
I tryed several resourcepacks but same issue.
![Captura de pantalla 2021-01-23 a las 9 44 43](https://user-images.githubusercontent.com/56472151/105575136-2b06aa00-5d61-11eb-9138-8a69cd441602.png)
thanks for the help

**Comment by KaiAF** [comment]
If you are still having this issue, send a F3 screenshot.

**Comment by jsr1976** [comment]
Not anymore thank you
Best Regards
Saludos Cordiales
