### ISSUE TITLE
[bug] Mesa 20.2 and 20.3 aren't targetable with MC_GL_RENDERER_MESA

### ISSUE THREAD

**Issue by platyple** [sp614x/optifine#5246]
trying to target Mesa using the `MC_GL_RENDERER_MESA` macro does not work on Mesa 20.2 and 20.3, neither does `MC_GL_VENDOR_XORG`. `MC_GL_VENDOR_OTHER ` does, however, work.

## Steps to Reproduce
1. Install Linux on a system with an AMD graphics card (i. e. Fedora 32 or Arch)
2. Install Minecraft and OptiFine, and write a shader to test `#ifdef MC_GL_RENDERER_MESA`

## OptiFine Version
1.16.4 G5

## Installation Method
OptiFabric

## Fabric Version
0.10.8

## OptiFabric Version
1.8.13

## F3 Debug Screenshot
![2021-01-23_14 32 19](https://user-images.githubusercontent.com/64314256/105579644-f9550980-5d87-11eb-80da-f4c0f585ebd9.png)
same thing on newer hardware, I also tested this on a 5600XT using Mesa 20.3

**Comment by sp614x** [comment]
Can you post the error log?

**Comment by sp614x** [comment]
The GL_RENDERER describes what GPU is used for the rendering.
MC_GL_RENDERER_MESA is a software renderer when a GPU is not available.

The current known Mesa renderers are:
```
      1 Mesa DRI Intel(R) HD Graphics 4000 (IVB GT2)
      1 Mesa DRI Intel(R) HD Graphics 4400 (HSW GT2)
      1 Mesa DRI Intel(R) HD Graphics 4600 (HSW GT2)
      8 Mesa DRI Intel(R) HD Graphics 500 (Broxton 2x6) 
      3 Mesa DRI Intel(R) HD Graphics (BYT)
      1 Mesa DRI Intel(R) UHD Graphics 600 (Geminilake 2x6) 
      1 Mesa Intel(R) HD Graphics 520 (SKL GT2)
      2 Mesa Intel(R) UHD Graphics 600 (GLK 2)
      1 Mesa Intel(R) UHD Graphics 620 (WHL GT2)
```
In your case the renderer is a real GPU.

**Comment by rre36** [comment]
```
E. GPU
 One of the following:
  #define MC_GL_VENDOR_ATI
  #define MC_GL_VENDOR_INTEL
  #define MC_GL_VENDOR_NVIDIA
  #define MC_GL_VENDOR_XORG
  #define MC_GL_VENDOR_OTHER

F. Driver
 One of the following:
  #define MC_GL_RENDERER_RADEON 
  #define MC_GL_RENDERER_GEFORCE
  #define MC_GL_RENDERER_QUADRO
  #define MC_GL_RENDERER_INTEL
  #define MC_GL_RENDERER_GALLIUM
  #define MC_GL_RENDERER_MESA
  #define MC_GL_RENDERER_OTHER
```

  I feel like the docs are misleading then since the GL_RENDERER defines are listed as drivers and the GL_VENDOR ones as GPUs.

**Comment by platyple** [comment]
honestly i would expect anything that runs under the mesa driver stack (i.e. intel graphics and amd cards if you're not using amdgpu-pro) to be covered by GL_RENDERER_MESA since they all run under the same driver, mesa.
