### ISSUE TITLE
Incredibly low FPS

### ISSUE THREAD

**Issue by JoshZuaa** [sp614x/optifine#5247]
## Description of Issue
OptiFine has always been fine before, but one day, I run OptiFine with the same settings as always, and the FPS is, and this is no exaggeration, around 1/10 of a frame per second. This was happening before 1.16.5. Once OptiFine for 1.16.5 came out, I installed it in hopes the new version would work. At first, it was just regular low FPS, but then it went back down to the fractions.

## Steps to Reproduce
I'm not sure how to reproduce this, or what information to give. Plus, all my setting used to work just fine. My laptop is kind of bad, but it should be able to run OptiFine with no shaders just fine.

## OptiFine Version
1.16.4 and 1.16.5 OptiFine HD U G6

## Installation Method
I installed OptiFine standalone.

## Log Files/Crash Reports
[latest.log](https://github.com/sp614x/optifine/files/5860974/latest.log)

## F3 Debug Screenshot
![F3 screen](https://user-images.githubusercontent.com/59930108/105613107-6e2b4200-5d8e-11eb-8684-62bb02d99204.png)

## Prior Testing
This does not happen in vanilla without OptiFine.

## Notes
Just figured out, Minecraft is lying to me.
![image](https://user-images.githubusercontent.com/59930108/105713565-4d2b3400-5ee9-11eb-8c21-b9d6c70b61a4.png)
![image](https://user-images.githubusercontent.com/59930108/105713570-4f8d8e00-5ee9-11eb-9678-0e86f8e13a5b.png)
It says it's not using as much RAM as it actually is.

**Comment by sp614x** [comment]
The game is using your integrated graphics (Intel HD 4000).
You can try "Options - Video Settings - Other - Reset Settings".

**Comment by Gravity10** [comment]
Your laptop is actually pretty decent, the issue is the integrated graphics. Your Intel CPU has a solid clock speed and you're running with 4GB of RAM (Minecraft typically only needs 2GB), the likely cause is the integrated graphics.

NOTE: There are some optimizations that you can do. While you aren't using a shader, this page may still be able to help (specifically the Minecraft Optimizations section near the bottom):
[https://gravityshade.netlify.app/help](https://gravityshade.netlify.app/help)

Past that, make sure you shut down programs running in the background! Discord likes to run with hardware acceleration which just munches on graphics, RAM, AND cpu cycles. Chrome is also a RAM hog, so before settling down to play just open up task manager and close some heavier-usage stuff.

Good luck!

**Comment by JoshZuaa** [comment]
> *Just a note: Your game display resolution is VERY non-standard. Either your monitor is _wide_ or you're not running Minecraft full screen (which can help with performance).

It's a clipped screenshot, of only the F3 menu. My monitor is not that wide. Minecraft is run maximized, but not full screen.

**Comment by Gravity10** [comment]
Oh, that is cropped, I totally missed that.

The display resolution listed in the debug screen is 1366x705 though, but maximized but not full screen still doesn't explain the very non-standard dimensions.

In any case, running full screen is something I'd recommend unless you're needing to change between Minecraft and some other program constantly. It's a good way to save some frames, my laptop is pretty meh and I get +20fps by going full screen.

**Comment by JoshZuaa** [comment]
Turns out, resetting my video settings fixed the problem. And yes, my monitor has a really weird resolution, 1366 by 768.

**Comment by Gravity10** [comment]
Great to hear, and what a monitor!

**Comment by JoshZuaa** [comment]
I think one of the reasons that it was taking so much RAM is because the screenshot scale was 4x, but I don't know why that would cause the RAM amount to be so high. I wasn't taking screenshots every millisecond. Is there something I don't understand?

**Comment by Gravity10** [comment]
I'm going to place a bet on the debug info saying your computer managed 4 chunk updates in 1 frame? That seems a little weird, but try increasing the amount of RAM available to Minecraft since it's using so much. It might run smoother.
