### ISSUE TITLE
Crashing Exit Code 0, no crash logs

### ISSUE THREAD

**Issue by naddison** [sp614x/optifine#5248]
Hi,

So I am looking for some insight into an issue I am having trying to play Minecraft 1.16.5 with Optifine and Sildurs shaders. I am constantly crashing (sometimes immediately loading into the world, sometimes I get 30 seconds to move), and all I have is the message "Sorry process exited with exit code 0". There are no crash logs in my .minecraft folder. When I first installed Optifine and Sildurs I was able to play for about 2 days without issue, and then on the third day, I have this 100% reproducible crash. There was no system change of note, no new software installed, no new drivers installed or updated.

Latest.log https://pastebin.com/PLQSxmdT
Launcher.log https://pastebin.com/e9hPA9D4

Minecraft Version: 1.16.5
Optifine: OptiFine_1.16.5_HD_U_G6
Sildurs: Sildurs Vibrant Shaders v1.283 High.zip

I have tried the following with no change in behavior:
- Tried NVIDIA drivers 461.09, 460.89, 460.79
- Reinstalled cleanly drivers.
- Reinstalled Minecraft and minecraft launcher completely.
- Reinstalled Optifine and Sildurs

The only logline that seems to give any indication as to what is happening may be from the launcher log, but the exit code is cryptic and no searches on Google are resulting in anything for this line in particular.

[Info: 2021-01-23 23:50:29.2792100: GameCallbacks.cpp(162)] Launcher/monitor (Process Monitor) Fatal Process crashed with exit code -1073740791

My friends have the same installation and very nearly identical specs of PC's the difference between us is that they have either 10 or 20 series cards and I am running a 3080. Circumstantial evidence leads me to believe my problem is related to the 30' series cards and optifine with shaders.

**Comment by sp614x** [comment]
There may be a "hs_err_pidXXX.log" in the ".minecraft" folder. 
Can you post it here (pastebin)?

**Comment by naddison** [comment]
Unfortunately, there is no file following that naming pattern.

This is a SS of the contents of my .minecraft folder.
![image](https://user-images.githubusercontent.com/3034767/105638291-b8f89880-5e26-11eb-8e26-23d7bb8fd4c0.png)

This one is really baffling, and I have no leads or ideas beyond it's something optifine vs nvidia 30's series related. I have since tried all previous drivers compatible with my card as well without luck.

I'm curious if you collect user hardware data, and could look to see if anyone is running optifine with 30's series cards with similar problems.

**Comment by archie426** [comment]
Could possibly be your modloader version being annoying, are you sure you've specified the correct entrypoint in the version configuration etc?

**Comment by naddison** [comment]
I'm using the standalone installer from optifine.net, I would assume this is a task done by it? If not, what do you mean by entry point, and which version configuration are you referring to so I can check?

**Comment by archie426** [comment]
Go to %appdata%\.minecraft\versions, then depending on what version you are using, open the json file containing the information about it. It should contain an entrypoint property that the launcher calls to start the game. What version are you using?

**Comment by naddison** [comment]
I've looked through the .json files in the versions folder, and nothing looks amiss. I cannot find a specific property called entrypoint. But I did find a property for mainclass for each version.json, which makes sense being java, the main class is the entry point for a java application.

[1.16.5 Version JSON](https://pastebin.com/fkVqCaRm)
[Optifine Version JSON](https://pastebin.com/0f4zRAH5)

Above are the raw version files incase there is something you can see I missed, but it all looks gucci to me.

**Comment by vinceingithub** [comment]
Was this ever resolved? I'm having the same issue.

**Comment by Cart3r1234** [comment]
> Was this ever resolved? I'm having the same issue.

yeah, the beta version oft the launcher causes the crash

**Comment by Fake300** [comment]
> > Was this ever resolved? I'm having the same issue.
> 
> yeah, the beta version oft the launcher causes the crash

How do I make it not the beta launcher???

**Comment by sp614x** [comment]
![image](https://user-images.githubusercontent.com/16635441/109404336-75cda000-7965-11eb-8c0d-9c15783388bf.png)

**Comment by BryanM2204** [comment]
I'm also having this exact same issue and switching it off the beta version does not resolve the issue

**Comment by zlyuk131** [comment]
I am having the same issue that Minecraft 1.16.5 with optifineHD_U_G7 crashes after some 5 or sometimes 30 mins of gameplay. I did not have beta launcher option enabled any way. Previously I have tried to fix this issue by completely reinstalling the game and but this did not help. Also launcher compatibility setting with Windows vistas failed almost immediately.
I have set up path to the game directory and in installed Java bin file in program files. But none of those work.
Game runs fine without optifine.
![2021-03-07_18-00-37](https://user-images.githubusercontent.com/8394145/110249764-a1591780-7f6f-11eb-9319-7cd33349b1de.png)

I have attached the crash log. Perhaps it is a Graphic card driver issue rather than the game?   
[launcher_log.txt](https://github.com/sp614x/optifine/files/6097678/launcher_log.txt)

**Comment by KaiAF** [comment]
Okay, yeah we are aware of another issue. Which is not related to the Minecraft launcher, or the beta version at all it seems. Seems like it's java? When you have it launched from a java version that isn't the bundled version, it crashes. So press the X and try to launch, see if it works.
![image](https://user-images.githubusercontent.com/60985521/110251162-e3209880-7f44-11eb-8149-f14d429d8183.png)

*sorry if that makes no sense*

**Comment by zlyuk131** [comment]
I have initially run it without any options bit it still had crushed. The only difference is if I reboot my pc it runs for around 30 mins before crashing subsequent runs crash after around 5 -10 mins. I have also tried to use java executable provided with the game eg C:\Program Files (x86)\Minecraft Launcher\runtime\jre-x64\bin\javaw.exe but this had failed as well. This begun to happen after Minecraft update from 1.16.4 to 1.16.5 plus I update my NVidea drivers rather regularly so not sure which one had caused the breakage. It is so sad because without Optifine and shaders game feels rather plain. (((

**Comment by sp614x** [comment]
@zlyuk131 the crash is in the nvidia drivers:
"Faulting module name: **nvoglv64.dll**, version: 27.21.14.6172, time stamp: 0x6035730c"

**Comment by nnnn12ff** [comment]
Hello i have the same problem but i dont use optifine just 16.4 or 16.5 but if i start it, it is stuck in the loading screen of mojang
I dont have beta version on, idk whats happening please respond thank you!
![Minecraft 1 16 4 25_03_2021 17_26_19](https://user-images.githubusercontent.com/81378391/112507777-3c832700-8d8f-11eb-8c42-c40763400537.png)

**Comment by KaiAF** [comment]
@nnnn12ff If you are still having this issue, create a new ticket. Closing this issue as it should be resolved now.
