### ISSUE TITLE
[CRASH] crash with betterweather1.2.4.jar

### ISSUE THREAD

**Issue by CodedWithInsulin** [sp614x/optifine#5253]
## Description of Issue
when clicking on a optifine button (Like in performance tab when clicking in there on any button) in freezes and crashes 

## Steps to Reproduce
1. load trhe game and open the video settings and navigate to performance tab and click fast render
2. then is wil freez and chrash

## OptiFine Version
MCC 1.16.5
preview G7 pre4 with forge 36.0.0

and

MC 1.16.5
G6 with forge 36.0.0

## Installation Method 
i put the jar in my modpack i did not installed it 

## Fabric/Forge Version
i used forge

## Other Installed Mods
https://pastebin.pl/view/91cfb63f

**If OptiFine is installed as standalone, remove this section.**

## Log Files/Crash Reports

crash log:
  https://pastebin.pl/view/21a1a645

latest log:
  https://pastebin.pl/view/f40adc5b

## F3 Debug Screenshot
i can't get an f3 screen image 

## Prior Testing
If you've installed standalone:

- Does this happen in Vanilla without OptiFine?
  no i s does not happen in vanilla.

If you've installed using Forge/Fabric:
  
- Does this happen without other mods installed? 
     no is does not

   - Only OptiFine and Forge
    is does work owhen only istalling optifine and forge
     
    optiforge does not work correctly with 1.16.5.
   
- Does this happen without any mods at all?
   - Only Forge/Fabric by itself.
   
- Does this happen in OptiFine standalone?

- Does this happen in Vanilla without OptiFine?
  no it dos not happen in vanilla

- Have you tried using a binary search to find which mods cause this issue?
  i have searched a bit but could not find my awnser

   - To find conflicting mods, split your mods into 2 groups (not including OptiFine/OptiFabric, obviously). Remove one group, and test in-game. Keep the group that has the problem, and repeat until no more mods can be removed without the issue disappearing.
   - did this turns out its colflicting with betterweather1.2.4.jar
   
  - Does the issue still happen with only the remaining mods installed?
    no it only does it when i put in betterweather1.2.4.jar
   
   - Forge/Fabric and remaining mods, without OptiFine
   - it works without optifine

if theree is any other things files or what so ever i will happply provide them!

greeting: insulin

**Comment by KaiAF** [comment]
1. Is this still an issue?
2. The Pastebin links you provided seem to be not working.
