### ISSUE TITLE
Random Crashes during gameplay 

### ISSUE THREAD

**Issue by CakeAKANiko** [sp614x/optifine#5254]
## Description of Issue
Please provide as much detail as possible.

## Steps to Reproduce
1. What do you do... 
2. ...to find this bug? I just played Minecraft and then i just started craashing i don't know if its because i formated my drive. just started crashing after i formated it.

## OptiFine Version
Self-explanatory. 

## Installation Method
How did you install OptiFine? Did you use the included standalone installer, or did you drop the JAR file into your "mods" folder?

I Just Installed Optifine EDIT: And JarFix and Java Ofcourse

## Log Files/Crash Reports
Any relevant log files. Drag and drop text files here to upload to GitHub directly, OR upload the complete contents to Pastebin. https://pastebin.com/

You can get logs from `.minecraft/logs`, and crash reports from `.minecraft/crash-reports`. 
Locating your `.minecraft` folder will depend entirely on your OS. See this page for details: https://minecraft.gamepedia.com/.minecraft

.
- Does this happen in OptiFine standalone? Yes 

## Additional Information
Here goes any final remarks and everything else that might not fit in the previous sections.

**Comment by sp614x** [comment]
More details needed:
- crash report
- error log

**Comment by KaiAF** [comment]
no response from the author.
