### ISSUE TITLE
[Feature Request] Glow squid light emission

### ISSUE THREAD

**Issue by AsthenicConch** [sp614x/optifine#5257]
#[1.17]
Dear optifine,
We the Minecraft players ,who voted for the glow squid, got jabaited.
We thought that it will give out light like sea pickles does which will make the deep oceans brighter. But it doesn't do so. I hope you will understand us and help us about this matter.
 
Yours faithful,
AsthenicConch 
   (Microsoft gamertag : AsthenicConch50)
YouTube: https://youtube.com/channel/UCH_fHbdxO6r0krJ5jJK-C1Q
#CavesAndCliffs

**Comment by Kroppeb** [comment]
> We the Minecraft players ,who voted for the glow squid, got jabaited.

Kinda your own fault tbh. But I think most people are assuming that mods like optifine and lambdynamiclights would make these creatures automatically emit light anyway.

**Comment by Jiingy** [comment]
Added

**Comment by AsthenicConch** [comment]
Umm I already  have got a ans like a year ago 😅...
Btw u can add me as a community representative, I'll work for free. Plz
