### ISSUE TITLE
Memory leak in cape downloader

### ISSUE THREAD

**Issue by prplz** [sp614x/optifine#526]
The IImageBuffer CapeUtils$1 keeps hold of player objects after it is done with them. This causes every player you have seen who has an optifine cape to be kept in memory forever. 

When playing on minigames servers with constant world changes this also causes many worlds to be kept in memory.

As an example, after playing hypixel for about two hours my game was at 90% memory usage, causing unplayable gc spikes.

Suggested fix: instead of using a final player in the anonymous class, use the player's name to find the relevant player in the world's player list.

**Comment by sp614x** [comment]
Updated preview C5 for 1.12
- fixed memory leak in cape download
