### ISSUE TITLE
Zoom resets the cinematic camera.

### ISSUE THREAD

**Issue by dotmyrame** [sp614x/optifine#5262]
Bug disables the cinematic camera when using the zoom.

# Steps to reproduce:
1. Turn on Cinematic Camera
2. Use Zoom (default C)

## Tested on:
1.8.9 - Optifine HD L5 Ultra (LabyMod)
1.16.4 - Optifine HD G5 Ultra (Vanilla)

**Comment by Cart3r1234** [comment]
![image](https://user-images.githubusercontent.com/69820300/106037956-56f99680-60a5-11eb-9b21-65ea512919d7.png)
![image](https://user-images.githubusercontent.com/69820300/106038016-67aa0c80-60a5-11eb-8064-c6723cdb95ae.png)

**Comment by Cart3r1234** [comment]
Just tested it on 1.16.4/.5 and it does work, and cinematic camera stays enabled after using zoom

**Comment by dotmyrame** [comment]
maybe bug only for me
