### ISSUE TITLE
[CRASH-ish] Minecraft will not load     blocks.png-atlas

### ISSUE THREAD

**Issue by BeansBeefBroccoli** [sp614x/optifine#5264]
## Description of Issue
Minecraft will wait forever while "loading" at "[Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas"

## Steps to Reproduce
1. Launch Minecraft 
2. Wait

## OptiFine Version
OptiFine_1.16.5_HD_U_G6

## Installation Method
I selected it as a mod for ATLauncher (not TLauncher)

## Fabric/Forge Version
Forge 36.0.7

## Other Installed Mods
If you want "mods" according to ATLauncher (which includes mods shaderpacks and resourcepacks), than here:

"mods" folder:

OptiFine_1.16.5_HD_U_G6.jar (I can't upload .jars)

"resourcepacks" folder:

[!              §bAnglerfish 1.16.zip](https://github.com/sp614x/optifine/files/5883704/bAnglerfish.1.16.zip)

[x32 Clear Glass 1.16.2.zip](https://github.com/sp614x/optifine/files/5883705/x32.Clear.Glass.1.16.2.zip)

"shaderpacks" folder:

[Sildurs Vibrant Shaders v1.283 Medium.zip](https://github.com/sp614x/optifine/files/5883702/Sildurs.Vibrant.Shaders.v1.283.Medium.zip)

disabledmods:

[Bytecraft.zip](https://github.com/sp614x/optifine/files/5883696/Bytecraft.zip)

[Marshmallow.zip](https://github.com/sp614x/optifine/files/5883697/Marshmallow.zip)

[orc-pvp-pack.zip](https://github.com/sp614x/optifine/files/5883698/orc-pvp-pack.zip)

[Sildurs Vibrant Shaders v1.283 Lite.zip](https://github.com/sp614x/optifine/files/5883699/Sildurs.Vibrant.Shaders.v1.283.Lite.zip)

[Xray_Ultimate_1.16_v3.7.3.zip](https://github.com/sp614x/optifine/files/5883700/Xray_Ultimate_1.16_v3.7.3.zip)

## Log Files/Crash Reports
https://pastebin.com/HFkibASZ

## F3 Debug Screenshot
I am not able to log into any worlds

## Prior Testing
If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   - yes, it happened with a large modpack too, but I gave up on that pack

- Does this happen without any mods at all?
   - no, it works different mods
- Does this happen in OptiFine standalone?
   - yes, I tried it on the vanilla launcher standalone, it did not work, but it made it to shulker_boxes.png-atlas
- Does this happen in Vanilla without OptiFine?
   - idk
- Have you tried using a binary search to find which mods cause this issue?
   - I only have OptiFine

## Additional Information
None

**Comment by Aurumaker72** [comment]
Works for me. Are you sure it's not just taking a lot of time to finish stitching the atlas?

**Comment by BeansBeefBroccoli** [comment]
One time I left it there fi hours, it still wasn't any further.

**Comment by BeansBeefBroccoli** [comment]
*for

**Comment by BeansBeefBroccoli** [comment]
Update:
This is in vanilla Minecraft too. I am sorry for wasting your time. I will try reinstalling it.

**Comment by BeansBeefBroccoli** [comment]
just figured out it was radeon software, everything works now, YAY!
