### ISSUE TITLE
[Crash] Client crashes upon joining server.

### ISSUE THREAD

**Issue by Zilch00** [sp614x/optifine#5267]
## Description of Issue
Please provide as much detail as possible.
I'm playing with the Minecolonies & Structurize mod and everytime a client joins the server and they have Optifine installed, the client crashes. I posted it on the Minecolonies github and they said to post it here. Removing Optifine fixes the issue and obviously removing the mods fixes the issue, but I would like to play with Optifine for shaders if possible.

## Steps to Reproduce
1. Install Optifine, Minecolonies and Structurize on 1.16.4
2. Install Minecolonies and Structurize onto a forge 1.16.4 server
3. Attempt to join the server

## OptiFine Version
OptiFine_1.16.4_HD_U_G6

## Installation Method
How did you install OptiFine? Did you use the included standalone installer, or did you drop the JAR file into your "mods" folder?
I put the jar file in mods

## Fabric/Forge Version
**If OptiFine is installed as standalone, you can remove this section.**
forge-1.16.4-35.1.37

## Other Installed Mods
*Every* single mod you have installed, besides OptiFine. Please don't leave anything out, even if you think it has nothing to do with the issue at hand. For long lists of mods, use Pastebin. https://pastebin.com/
structurize-0.13.100-RELEASE-universal
minecolonies-0.13.480-BETA-universal

**If OptiFine is installed as standalone, remove this section.**

## Log Files/Crash Reports
Any relevant log files. Drag and drop text files here to upload to GitHub directly, OR upload the complete contents to Pastebin. https://pastebin.com/

Log: https://pastebin.com/G4g6eFtw
Crash Report: https://pastebin.com/qAMVJpPZ

## F3 Debug Screenshot
Minecraft's built-in debug screen provides *a lot* of useful information, and should be included even if the issue is not something that can be captured in a still image.

To open this menu, simply press `F3` on your keyboard while in-game. Please ensure the text is easily readable. Depending on the size/resolution of your monitor, you may have to adjust your GUI scale for all text to be completely visible on-screen.

(Doesn't even give a chance to press it)

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? No
   - Only OptiFine and Forge No
   - Only OptiFine, OptiFabric, and Fabric
- Does this happen without any mods at all? No
   - Only Forge/Fabric by itself. No
- Does this happen in OptiFine standalone? No
- Does this happen in Vanilla without OptiFine? No
- Have you tried using a binary search to find which mods cause this issue? Yes
   - To find conflicting mods, split your mods into 2 groups (not including OptiFine/OptiFabric, obviously). Remove one group, and test in-game. Keep the group that has the problem, and repeat until no more mods can be removed without the issue disappearing.
   - Does the issue still happen with only the remaining mods installed?No
      - Forge/Fabric and remaining mods, without OptiFine

## Additional Information
Here goes any final remarks and everything else that might not fit in the previous sections.

**Comment by archie426** [comment]
This does not seem to be to do with optifine judging by the following:
Details:
	Mod File: minecolonies-0.13.592-ALPHA-universal.jar
	Failure message: Mod minecolonies requires structurize 0.13.113-ALPHA
		Currently, structurize is 0.13.116-ALPHA
	Mod Version: 0.13.592-ALPHA
	Mod Issue URL: https://github.com/ldtteam/minecolonies/issues/new
	Exception message: MISSING EXCEPTION MESSAGE

**Comment by Zilch00** [comment]
Oh I'm really sorry, thats the wrong crash report

Here: https://pastebin.com/qAMVJpPZ

**Comment by Aznlilly** [comment]
I also get this same error with the Direwolf 20 1.16.4 modpack

**Comment by Zilch00** [comment]
Just found and this issue was discussed on the Minecolonies github with a possible reason as to why this happens.

[https://github.com/ldtteam/minecolonies/issues/6415](url)

**Comment by KaiAF** [comment]
This should have been fixed in a recent version
