### ISSUE TITLE
[color.properties] 1.8.9 M5 No Lilypad Color

### ISSUE THREAD

**Issue by BrushStrokesMC** [sp614x/optifine#5269]
## Description of Issue
Liliypads display as gray on 1.8.9 M5

## Steps to Reproduce
1. Use Optifine 1.8.9 M5 (any method of installation)
2. Liliypads are gray

## OptiFine Version
1.8.9 M5

## Installation Method
Forge, no other mods installed.

## Fabric/Forge Version
Forge 1.8.9 - 11.15.1.2318 (latest)

## Other Installed Mods
None

## Log Files/Crash Reports
Log file if needed: https://pastebin.com/TUMySwUy

## F3 Debug Screenshot
![image](https://user-images.githubusercontent.com/34098679/106301206-0e64e900-621d-11eb-99fb-b475c4b044f1.png)

## Prior Testing
All tested. Bug only persists with Optifine present.

Bug also persists in the installation version.

## Additional Information
You can find me on discord at BrushStrokes#3368, I am bound to be more diligent in checking updates there.

Here are my options.txt and optionsof.txt
[optionsof.txt](https://github.com/sp614x/optifine/files/5894992/optionsof.txt)
[options.txt](https://github.com/sp614x/optifine/files/5894993/options.txt)

**Comment by KaiAF** [comment]
This *could* be related to #4173 just on an older version?

**Comment by BrushStrokesMC** [comment]
That would be strange, this didn't start happening until this (fairly recent) update.

**Comment by KaiAF** [comment]
Interesting.I assume this is still happening then. Labeling it as a bug. What resource pack are you using? Does this happen on single player?

**Comment by BrushStrokesMC** [comment]
I opened up the game in vanilla optifine (no resource pack) to test Single Player, but the bug seems to be gone, even though I am unaware of any changes to settings/my system since I opened this? 

Strangely enough, the bug is present with my personal texture pack, despite the fact that the bug originally persisted with vanilla (as seen in the initial report). 

When persisting with my personal pack, it does happen in Single Player, as it did with the vanilla pack with the initial report. To make sure I haven't gone insane, the bug does not persist when running vanilla 1.8.9 with my resource pack.

I've attached a Single Player screenshot with my texture pack/optifine, and one with no optifine.
![image](https://user-images.githubusercontent.com/34098679/112737182-85211880-8f26-11eb-9ba4-b61dc7c3d8af.png)
![image](https://user-images.githubusercontent.com/34098679/112737185-894d3600-8f26-11eb-8f16-9b2f384ac0a1.png)

**Comment by ewanhowell5195** [comment]
This isn’t an issue with OptiFine. In your pack you have set the lily pad colormap to white, and therefore everything is working as it should.

**Comment by BrushStrokesMC** [comment]
Is there something within my Optifine-specific settings that would make it persist with Optifine but not Vanilla?

**Comment by ewanhowell5195** [comment]
OptiFine color.properties

**Comment by BrushStrokesMC** [comment]
Out of curiosity, why did this only starting existing after the newest update?

**Comment by ewanhowell5195** [comment]
color.properties just had a large bug fix in recent 1.16, so I assume he backported the fixes

**Comment by BrushStrokesMC** [comment]
Much appreciated! Thanks for the help.

**Comment by ewanhowell5195** [comment]
You can close this now by the way
