### ISSUE TITLE
[Animation] Terrain Animation setting affecting Animated Textures

### ISSUE THREAD

**Issue by Jkosio23** [sp614x/optifine#5275]
When using items with animated textures, turning off Terrain Animated turns off item textures, whereas turning off textures animated does nothing.

## Steps to Reproduce
1. Have an item with an animated texture. Examples include: Blazing Immolation Blade [Wither Skeleton Tweaks], Energized Steel [Powah], Overgrowth Seed [Botania]. (A notable exception that I found was the mod Ars Nouveau, which doesn't respond to either setting)
2. Toggle Terrain Animated Off.
3. Observe.
4. Toggle Terrain Animated On and Textures Animated Off.

## OptiFine Version
OptiFine HD G6 Ultra 1.16.5

## Installation Method
JAR File

## Fabric/Forge Version
36.0.1

## Other Installed Mods
https://pastebin.com/wi0sr1GG

## Log Files/Crash Reports
N/A

## F3 Debug Screenshot
https://i.imgur.com/WUcY4Pv.png

## Prior Testing
If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   Not Applicable, Vanilla has no animated textures.
- Does this happen without any mods at all?
   - N/A See Above
- Does this happen in OptiFine standalone?
- N/A See Above
- Does this happen in Vanilla without OptiFine?
- N/A See Above
- Have you tried using a binary search to find which mods cause this issue?
   - No.

**Comment by sp614x** [comment]
Minecraft stores block and item textures together in the block atlas texture. The option "Animated terrain" controls the animation of the block atlas texture, so it also affects the item animations.
The option "Animated textures" controls custom animations which can be used for textures which are not in the block atlas (mobs, entities, gui, sun, etc.). : https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/custom_animations.txt

**Comment by Jkosio23** [comment]
Maybe there could be a tooltip that explains that terrain means blocks and items? Because I wouldn't have ever drawn that connection as a user.
