### ISSUE TITLE
[Weird Issue/Request] Performance Hit in the Latest Update

### ISSUE THREAD

**Issue by Gravity10** [sp614x/optifine#5276]
The latest version of Optifine had great stability improvements and I'm very grateful for that. However, performance has taken a sizable hit. My testing world shows an average of 20+ fps loss since the previous version (90+ fps down to ~58fps). No setup changes have been made on my end, it's just a curious note that I thought I would bring up.

I totally understand that balancing bugs and performance is a difficult task, and thanks for all of the great work that you guys do!

Version with 90+ fps performance: Any Optifine version (preview or normal) for Minecraft 1.16.4

Newest slower version: Any Optifine version (preview or normal for Minecraft 1.16.5

[F3 screenshots in progress, trying to get Minecraft to go back an update]

**Comment by ZenIsBestWolf** [comment]
Please post which OptiFine versions are tested, F3 screenshots for them and other relevant info: logs, etc. If you'd like, you can close and repost your issue with a provided template for better organization.

**Comment by Gravity10** [comment]
Hi! The performance issue was fixed by reinstalling Minecraft and Optifine. Not sure why but thanks for the great mod and support 👍
