### ISSUE TITLE
[resourcepack] Albedo, not synced with _s and _n, exept when taking screenshots

### ISSUE THREAD

**Issue by BentoGambin** [sp614x/optifine#5279]
So, I experienced this issue before when doing an animated texture that had _s and _n support.
(https://github.com/sp614x/optifine/issues/4967 the issue seems to have gone under the radar)
Now I tried to setup a repeatable testing environment and confirmed the issue:
I used these files to test:

[optifinegh.zip](https://github.com/sp614x/optifine/files/5901563/optifinegh.zip)
the "chanfer" in the normal map and the reflective squares of the _s are supposed to always be on top of the numbers drawn in the albedo.
![image](https://user-images.githubusercontent.com/41645690/106409389-3328ae80-641f-11eb-91b6-f5099a1d635d.png)
they all have the same contents in the mcmeta file.
IN GAME:
albedo frames are not aligned with _n and _s, but _n is aligned with _s.
This results in this (
https://user-images.githubusercontent.com/41645690/106409567-94508200-641f-11eb-9bf3-8dd0a8b906f6.mp4
)
If you watch the video frame by frame you will see that when the albedo is in frame X , the _n and _s are on frame (X+1)

So easy fix right? just offset the _n and _s animation by one frame to compensate, right?
Wrong, the weird part is:
When taking a screenshot the animations are correctly aligned:
(the following screens were taken by spamming f2)
![2021-01-31_23 33 59_8](https://user-images.githubusercontent.com/41645690/106409985-9f57e200-6420-11eb-8976-3e8ef91eefc9.png)
![2021-01-31_23 34 00_4](https://user-images.githubusercontent.com/41645690/106410001-a383ff80-6420-11eb-8881-40ef0a72f4ab.png)
![2021-01-31_23 34 01](https://user-images.githubusercontent.com/41645690/106410002-a5e65980-6420-11eb-8d89-f0517be1ed09.png)
![2021-01-31_23 33 58_3](https://user-images.githubusercontent.com/41645690/106410008-a8e14a00-6420-11eb-911f-e385def4725c.png)
.
I sent one of each animation frame but this is taken from about 18 screenshots I took ( and obviously they werent in the right animation order)
So I concluded it was a bug, since to fix it in game, I'd need to break screenshots, and vice-versa
I think it's not important but:
I'm using Optifine G7 pre 4 on 1.16.5, but this also happened on 1.16.4 and probably back but I can't remember

**Comment by sp614x** [comment]
This only happens when anisotropic filtering is active.
Fixed, coming in next preview.
