### ISSUE TITLE
Crash with FTB Infinity Evolved

### ISSUE THREAD

**Issue by Mortemium** [sp614x/optifine#528]
[crash-2017-03-15_08.38.37-client.txt](https://github.com/sp614x/optifine/files/843588/crash-2017-03-15_08.38.37-client.txt)
Game crashed with updated optifine. HD_U_D6 was worked good.

**Comment by Mortemium** [comment]
After removing FastCraft Optifine working

**Comment by sp614x** [comment]
Looks like FastCraft is trying to patch the class TextureMap which OptiFine has changed and it fails.
The FastCraft patch needs to be updated.
