### ISSUE TITLE
[Crash] Creating an infinite loop in the shader menu crashes Minecraft

### ISSUE THREAD

**Issue by bestsoft100** [sp614x/optifine#5285]
To reproduce put this in the shaderpacks folder and click on it:
[Crash.zip](https://github.com/sp614x/optifine/files/5905490/Crash.zip)

OptiFine_1.16.5_HD_U_G6

StackOverflowError at net.optifine.shaders.config.ShaderPackParser.parseGuiScreen(ShaderPackParser.java:603)

Crash Report: https://pastebin.com/4FHJg52L

**Comment by ZenIsBestWolf** [comment]
Please upload the crash log to Pastebin or some sort of paste site, and also provide steps to reproduce this.

**Comment by Nigelrex** [comment]
yes this thing happened to me also,

i tried the internal shaders and smth buggy like when i open my inventory there are lines of transparency here and there making it hard(really hard) for the eyes to see what is going on in the screen!

**Comment by sp614x** [comment]
Fixed, coming in next preview.
