### ISSUE TITLE
[Shaders] TAA in sildurs vibrant shaders break on window resize

### ISSUE THREAD

**Issue by fayer3** [sp614x/optifine#5294]
## Description of Issue
resizing the window breaks TAA in sildurs vibrant shaders.
by breaking I mean, that the screen starts to jitter

## Steps to Reproduce
1. load sildurs vibrant shaders
2. enable TAA in shader settings
3. resize the window
4. screen jitters

## OptiFine Version
1.16.5 G7 pre5/6/7

## Installation Method
standalone installer

## F3 Debug Screenshot
![2021-02-05_02 08 52](https://user-images.githubusercontent.com/8282299/106975654-32fa1d00-6757-11eb-9864-cb9b51c6ea23.png)

## Prior Testing
started happening since 1.16.5 G7 pre5, pre4 worked fine

**Comment by sp614x** [comment]
Fixed, coming in next preview.
