### ISSUE TITLE
[Compute] Image 2D buffers

### ISSUE THREAD

**Issue by helixd-2k18** [sp614x/optifine#5295]
I thought my idea would not be appropriate, because I had a similar idea in my head before, and even in Discords it was mentioned and flashed from my lips. Considering that you are already going to implement compute shaders in Optifine, I suggest the following buffers: [image2D](https://www.khronos.org/opengl/wiki/Image_Load_Store). Please insert such buffers into the geometry  (and fragment) shaders in the shadow pass (better voxelization).

**Comment by helixd-2k18** [comment]
Although it seems I changed my mind over the original idea. Now I think that there should be NOT only a version of `image2D` (for the frame size), but also` imageBuffer` (configurable size), and even formats not only float, but also int.

**Comment by sp614x** [comment]
One buffer can be bound as texture or as image.
The existing buffers can be used as image via "colorimgN", where N is currently limited from 0 to 5.
