### ISSUE TITLE
[Shaders] circular reference detection to sensitve?

### ISSUE THREAD

**Issue by fayer3** [sp614x/optifine#5298]
## Description of Issue
With OptiFine 1.16.5_HD_U_G7_pre7 some shader screens get flagged with 'Screen circular reference' even if they don't contain circular references.
to be specific: if two different screens reference the same sub-screen, the sub-screen gets flagged as a 'Screen circular reference' and removed from the second screen

## Steps to Reproduce
1. make a shaderpack with 2 screens that link to the same sub screen
2. the sub-screen is missing from one of the screens

## OptiFine Version
OptiFine 1.16.5_HD_U_G7_pre7

## Installation Method
standalone installer

## Log Files/Crash Reports
log with the test shader
[latest.log](https://github.com/sp614x/optifine/files/5936849/latest.log)

## Additional Information
shaderpack used for testing:
[test circular references.zip](https://github.com/sp614x/optifine/files/5936850/test.circular.references.zip)
this shaderpack has two valid circular references: [CIRCLE1]->[CIRCLE] and [CIRCLE3]->[CIRCLE]
[CIRCLE] is here a parent of both [CIRCLE1] and [CIRCLE3]
it also has 2 screens which get flagged as cirular reference even though they aren't: [CONNECTING1]->[CONNECTING] and [CONNECTING2]->[CONNECTING]
[CONNECTING] is only a sub screen and not a parent of [CONNECTING1] or [CONNECTING2]

**Comment by EminGT** [comment]
This issue hurts the latest version of Complementary Shaders.
Shader Options -> Sky:
![image](https://user-images.githubusercontent.com/52270338/107296572-b6cb4680-6a82-11eb-9c60-fd21b2d2792f.png)

**Comment by sp614x** [comment]
Fixed, coming in next preview.
