### ISSUE TITLE
Block breaking animation off block[Category] Short description

### ISSUE THREAD

**Issue by PreposterouSpraq** [sp614x/optifine#5299]
When i am underground by Y=10 the animation for block breaking is either not displayed or displayed elsewhere on the screen. I have moved around and broke blocks and seems to only appear where at times when looking near the edge of the block being mined. 

## Steps to Reproduce
1. I am underground around y=10
2. I start mining in places a few blocks work like they are supposed to 
3. If that block works fine stand place and look around at other blocks at that same location since this bug seems to be also affected by player look angle and pitch seems like
4. Looks like when facing west the bug doesn't appear 

## OptiFine Version
1.16.5 HD_U_G6 

## Installation Method
I installed it through the installer

## Other Installed Mods
I don't have these mods activated on the server but here are the mods that the game has
https://pastebin.com/Ma7KCYRz

## F3 Debug Screenshot

![2021-02-06_19 52 55](https://user-images.githubusercontent.com/42391622/107133318-f0e6ed80-68b4-11eb-8c7f-ebd203471eeb.png)

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
- No it does not

- Does this happen without any mods at all?
   - Yes
- Does this happen in OptiFine standalone?
- Yes
- Does this happen in Vanilla without OptiFine?
- No
-

**Comment by PreposterouSpraq** [comment]
I just went above ground too and this still happens here too

**Comment by Cart3r1234** [comment]
Are you using internal shaders?  This sounds similar to a bug with internal shaders.

**Comment by PreposterouSpraq** [comment]
I didnt think about that. Just checked and yes its the shaders

**Comment by Cart3r1234** [comment]
Yeah, internal shaders cause a lot of visual bugs since they are not meant to be used for gameplay.  I suggest turning off internal shaders to get rid of the visual bug and closing the issue report

**Comment by PreposterouSpraq** [comment]
ok thanks

**Comment by PreposterouSpraq** [comment]
oh wait it wasnt the (internal) but a different shader pack I put in but I will still close since its not optifines issue

**Comment by Cart3r1234** [comment]
Yeah, you'd likely be better off reporting it to the developer of the shader that causes the issue
