### ISSUE TITLE
[Bug] Optifine brands its self as a vanilla client

### ISSUE THREAD

**Issue by itsfsnow** [sp614x/optifine#5300]
## Description of Issue
When a player logs into a server, Minecraft sends a packet to the server with the client's branded version. Optifine still sends 'vanilla', disallowing servers to differentiate between vanilla & optifine users.

## Steps to Reproduce
Spigot can listen to `minecraft:brand` channel, and then log it's result when a packet is recieved. Testing on both Vanilla & Optifine it produces 'vanilla', while forge produces 'forge/fml'

On the client, it can be seen in the F3 Menu at the top left of the screen (attached image)
![image](https://user-images.githubusercontent.com/33494766/107146550-f853d880-6940-11eb-92d6-fc67b1216918.png)

## OptiFine Version
1.16.5-Optifine_HD_U_G6

## Installation Method
Direct installation via opening the .jar file

## F3 Debug Screenshot
![image](https://user-images.githubusercontent.com/33494766/107146593-30f3b200-6941-11eb-98bf-c3eeeeeff2de.png)

## Additional Information
I believe this could be solved by changing the string returned in ClientBrandRetriever#getClientModName to "optifine" rather than "vanilla".

This would be useful in allowing servers to only allow Optifine users if they are taking advantage of CIT/Custom textures, and don't want non-optifine users to not see them.

**Comment by iGabyTM** [comment]
👍🏼

**Comment by Siuolthepic** [comment]
Im assuming that on Forge (And on Fabric as well with Optifabric) the mod loader would override something like this?
If not, this may cause some problems.

**Comment by HiItsDevin** [comment]
This is cool and all, and I think it should be added, but as Siuol said, the modloader might override it, and that's concerning

**Comment by itsfsnow** [comment]
Modloaders (like forge) already offer ways of detecting if Optifine is a present mod, however Optifine when installed standalone has no way of checking.

I believe this should be implemented for when Optifine is installed standalone, regardless of it's going to be overridden or not.

Server developers will be able to work with this and other functions (like checking modloaders) to see if Optifine is present, however currently there is no available solution, which this would fix.

**Comment by asbyth** [comment]
> 
> 
> Modloaders (like forge) already offer ways of detecting if Optifine is a present mod, however Optifine when installed standalone has no way of checking.

OptiFine uses Reflection when transforming something that Forge also transforms while Forge is present anyway, so it wouldn't be an issue on OptiFine's end either to make it something like `forge-optifine` on OptiFine's end, though same thing is of course possible on Forge's end

**Comment by KaiAF** [comment]
I do not think this is a bug. Going to label this as a "enhancement" as this could be changed later? I'm sure sp has his reasons

**Comment by ZenIsBestWolf** [comment]
Consolidating into #1631
