### ISSUE TITLE
[CIT] CIT blend methods do not work, despite being mentioned in the docs are supported

### ISSUE THREAD

**Issue by Cart3r1234** [sp614x/optifine#5304]
## Description of Issue
In the optifine docs, Blend methods are mentioned to be supported by CIT.  Upon investigating this, they do not work.

## Steps to Reproduce
1. Set up a CIT pack that has a setup for each blend method (I provided the one I used in testing.  Naming a diamond pickaxe to the name of the blend method activated the CIT.  The test texture is a plain green square.)
2. Activate the CIT, and watch as the blend method does not take into effect, and the default 'add' method is applied

Resource Pack I used to test:
[CIT_Blend_testing.zip](https://github.com/sp614x/optifine/files/5945705/CIT_Blend_testing.zip)

## OptiFine Version
Tested on 1.14.4 and 1.16.5

## Installation Method
Standalone

## Images
CIT Docs:
![image](https://user-images.githubusercontent.com/69820300/107261113-e93a5c80-6a0c-11eb-911d-0f72c2c240ab.png)
Bettersky Docs:
![image](https://user-images.githubusercontent.com/69820300/107260716-65807000-6a0c-11eb-9852-963bd97e83a0.png)
Gameplay Screenshots:
![image](https://user-images.githubusercontent.com/69820300/107260249-ef7c0900-6a0b-11eb-98d6-8dc340dcd069.png)
![image](https://user-images.githubusercontent.com/69820300/107260275-f60a8080-6a0b-11eb-982f-24d8680db96d.png)
Properties file Setups:
![image](https://user-images.githubusercontent.com/69820300/107260575-3ff36680-6a0c-11eb-874e-b86ed8f3dd75.png)

## F3 Debug Screenshot
![image](https://user-images.githubusercontent.com/69820300/107260638-513c7300-6a0c-11eb-8d44-cd3cc57fccb1.png)

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
No, since it is a CIT bug

**Comment by sp614x** [comment]
Not implemented:
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/todo.txt#L8
