### ISSUE TITLE
See-thru issue with ice/glass at edges of chunks

### ISSUE THREAD

**Issue by INeedAwesome1** [sp614x/optifine#5308]
## Description of Issue
When I am walking to the edges of chunks, sometimes, very often, I see this really annoying lightning bug.
https://ibb.co/vJyJtYd
https://ibb.co/jMYgqZK

## Steps to Reproduce
1. Walk to edge of chunk with ice or glass, I have multiple layers of glass
2. Walk between the chunks back ond forward

## OptiFine Version
1.16.5

## Installation Method
I installed it by downloading the Mirror Jar file on your website https://optifine.net/downloads

## F3 Debug Screenshot
https://ibb.co/HCsHT9D

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
- no it does not.

**Comment by fayer3** [comment]
probably the same issue as #5107

**Comment by KaiAF** [comment]
Seems like it's related to #5107. If you think otherwise, let me know.
