### ISSUE TITLE
Feature request - the ability to change the loading screen logo

### ISSUE THREAD

**Issue by lavadaragon15396** [sp614x/optifine#5309]

**Comment by KaiAF** [comment]
If I'm not wrong I believe you can do this in resource packs. Please provide more information if you weren't talking about that

**Comment by lavadaragon15396** [comment]
this is exactly what I was talking about and I have seen a pack that does this but I couldn't figure out how to get it to work like in the screenshot of the pack but it didnt work

**Comment by KaiAF** [comment]
This already exists, you can probably find tutorials online, and or on our discord. https://optifine.net/discord
