### ISSUE TITLE
I cant see my Optifine Cape.

### ISSUE THREAD

**Issue by HelloitsRoFi** [sp614x/optifine#5312]
I am using Optifine 1.16.5 and I am using it directly without Forge, I have proof I purchased it and everything, I spelt the name right, and I have all my settings to show capes turned ON. The weird thing is when I use Lunar Client 1.8.9 for bedwars I can see it on Hypixel, but when I used Optifine 1.16.5 or even Lunar Client 1.16 I can’t see the cape.. I don’t think it’s a firewall/router thing because how would it work only in Lunar 1.8.9 then? Anyways I don’t know how firewalls/routers work so that might be it who knows. But please if you know what’s happening tell me😂

**Comment by KaiAF** [comment]
This seems to be something related to the cape servers. Our FAQ on our Discord server shows this: 
Q: I can't access the cape servers/Mojang servers.
A: Follow these instructions to unblock the servers. If these don't work, you may need to reset your firewall.
- Open Notepad with Administrator (Search "Notepad" in your Windows Search Bar, right click on it and press Run as Administrator.) Accept the prompt that comes up.
- Press File -> Open
- In the bottom right corner of the file window, change Text Documents (*.txt) to All Files (*.*)
- Navigate to C:\Windows\System32\drivers\etc
- Double click on hosts
- Delete the entire line that contains s.optifine.net or anything that contains mojang.
- Press Control + S to save.
- Close Notepad and restart your computer.

If you did this and it's still happening, please go to our discord for support. https://optifine.net/discord
