### ISSUE TITLE
[1.16.5] Custom Items Do Not Work

### ISSUE THREAD

**Issue by TommyTheG** [sp614x/optifine#5315]
Whenever I use a custom item resource pack whether that be my own or a public one (Hypixel skyblock etc) they do not work(as in the custom items do not show at all.

**Comment by PixelatedVolume** [comment]
Are you sure Custom Items are turned on?  Check that Settings->Video Settings->Quality->Custom Items is set to `ON`

**Comment by TommyTheG** [comment]
It turns out using the launcher version doesn’t work but using it as a mod does

**Comment by KaiAF** [comment]
If you are still having this issue, create a new valid ticket, please.
