### ISSUE TITLE
Weather does not render to any depth map

### ISSUE THREAD

**Issue by BruceKnowsHow** [sp614x/optifine#532]
It's causing this issue in my shader:
https://github.com/BruceKnowsHow/Ebin-Shaders/issues/17

Weather isn't rendering to either the front or back depth maps. My shader uses the depth maps to determine if a pixel is sky or not. Other particles, such as rain drop splashes, are still rendered to the depth map, which makes me think this is unintentional.

**Comment by sp614x** [comment]
What are the front/back depth masks?

Currently there are 3 depth buffers: https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.txt#L431
- `depthtex0`  - everything
- `depthtex1`  - no translucent objects (water, stained glass, ice)
- `depthtex1`  - no translucent objects (water, stained glass, ice), no handheld objects

**Comment by zombye** [comment]
In addition to rain, most particles from fireworks are also not rendered into any depth buffers, only the firework itself and part of the flash when it explodes.

**Comment by BruceKnowsHow** [comment]
I consider depthtex0 to be the front depth, and depthtex1 to be the back. I currently don't use depthtex2.

**Comment by Strum355** [comment]
+1

**Comment by sp614x** [comment]
The rain/snow is rendered with `glDepthMask(FALSE)` so it is not writing to the depth buffer:

![image](https://cloud.githubusercontent.com/assets/16635441/26299709/19f67be8-3edc-11e7-80d8-b7ca1a9e12ec.png)

Enabling the depth mask breaks the water and stained glass rendering:

![image](https://cloud.githubusercontent.com/assets/16635441/26299742/3b6dd7b2-3edc-11e7-86e0-384d2b11ce03.png)

**Comment by sp614x** [comment]
The raindrop splashes are not translucent, they are rendered as normal particles:

![image](https://cloud.githubusercontent.com/assets/16635441/26300068/58823dce-3edd-11e7-89f9-3596f5d7f542.png)

**Comment by sp614x** [comment]
Updated preview C9 for 1.12.2
 - added shaders configuration for rain/snow depth (#532)
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.properties#L49
