### ISSUE TITLE
[BUG] Optifine slows game down when installed

### ISSUE THREAD

**Issue by KoromaruKoruko** [sp614x/optifine#5320]
## Description of Issue
Optifine mearly isntalled makes minecraft run at sub 20fps.
even without shaders/ changing default settings.

## Steps to Reproduce
1. install Optifine 1.16.4_HD_U_G6
2. start game
3. observe potato pc fps

## OptiFine Version
1.16.4_HD_U_G6

## Installation Method
droped optifine into mod's folder

## Fabric/Forge Version
Forge_35.1.37

## Prior Testing
tried it
with/without shaders
with/without optimization settings

**Comment by KoromaruKoruko** [comment]
note:
note the mod Optiforge fixes the issue

version: MC1.16.4-0.4.6

**Comment by KaiAF** [comment]
Are you still having any issues?

**Comment by KoromaruKoruko** [comment]
the latest version fixes this.
