### ISSUE TITLE
Crash:  OptiFine_1.16.4_HD_U_G6.jar - Mekanism-1.16.4

### ISSUE THREAD

**Issue by kurotom** [sp614x/optifine#5321]
## Description of Issue
When entering the world, I get an error with OptiFine code `255`, adding` Mekanism-1.16.4-10.0.19.446.jar` generates the error, without OptiFine it works fine, but it does not run smoothly so I must use the `mod`.
I can't take a screenshot because I can't enter the world.

## Steps to Reproduce
I tested the mods one by one until I found the one that conflicts with the OptiFine, `Mekanism-1.16.4-10.0.19.446.jar`.
I leave an image with an error message.
![Captura de pantalla de 2021-02-12 21-18-10](https://user-images.githubusercontent.com/55354389/107836672-b978b500-6d7c-11eb-8b80-95eec2da08a4.png)

## OptiFine Version
OptiFine_1.16.4_HD_U_G6.jar

## Installation Method
OptiFine JAR file into your "mods" folder with others mods.

## Forge Version
Forge-1.16.4-35.1.37

## Mods
abnormals_core-1.16.4-3.0.6.jar
AI-Improvements-1.16.2-0.3.0.jar
AppleSkin-mc1.16.2-forge-1.0.14.jar
Aquaculture-1.16.4-2.1.11.jar
astikorcarts-1.16.4-1.1.0.jar
astralsorcery-1.16.4-1.13.9.jar
Attained-Drops-1.16.3-7.2.0.jar
backpacked-1.7.0-1.16.3.jar
betteranimalsplus-1.16.4-10.1.0.jar
BiomesOPlenty-1.16.4-13.0.0.430-universal.jar
blood-particles-1.16.3-1.0.1.jar
Bookshelf-1.16.4-9.3.25.jar
BotanyPots-1.16.4-6.0.17.jar
carryon-1.16.3-1.15.1.7.jar
citadel-1.5.3.jar
cloth-config-forge-4.1.3.jar
cofh_core-1.16.3-1.1.6.jar
Craftable+Saddles+[1.16.4]-1.3.jar
CreativeCore_v2.0.10_mc1.16.4.jar
CTM-MC1.16.1-1.1.2.6.jar
curios-forge-1.16.4-4.0.3.5.jar
Disenchanting-forge_1.16.3-1.6.0-alpha.jar
Druidcraft-1.16.4-0.4.5.jar
DungeonCrawl-1.16.3-2.2.4.jar
dungeons_plus-1.16.4-1.1.2.jar
DynamicSurroundings-1.16.4-4.0.3.8.jar
elevatorid-1.16.5-1.7.12.jar
embellishcraft-1.16.4-3.3.0.0.jar
embellishcraft-bop-1.16.4-3.3.0.jar
enchantedgoldenapplecrafting-1.16.4-1.0.jar
EnchantmentDescriptions-1.16.4-6.0.3.jar
endercompass-3.1.jar
endergetic-1.16.4-3.0.0.jar
EnhancedVisuals_v1.3.20_mc1.16.4.jar
exnihilosequentia-1.16-2.0.0.1.jar
Gobber2-Forge-1.16.4-2.3.45.jar
gravestone-1.16.4-1.0.8.jar
Hwyla-forge-1.10.11-B78_1.16.2.jar
iceandfire-2.1.5-1.16.4.jar
industrial-foregoing-1.16.4-3.2.8.1-f2c848c.jar
inventorypets-2.0.11.jar
jei-1.16.4-7.6.1.65.jar
Lollipop-1.16.4-3.2.4.jar
LostTrinkets-1.16.4-0.1.13.jar
mapperbase-1.16.4-2.3.0.0.jar
masonry-1.16.3-0.3.6.jar
mcw-furniture-2.0.1-mc1.16.5.jar
mcws-roofs-2.0.0-mc1.16.4.jar
mcw-windows-1.0.2-mc1.16.4.jar
Mekanism-1.16.4-10.0.19.446.jar
minecolonies-0.13.437-RELEASE-universal.jar
mining-helmet-1.16.4-2.0.0.jar
MutantBeasts-1.16.4-1.1.3.jar
mysticalworld-1.16.4-0.3.1.6.jar
observerlib-1.16.4-1.5.1.jar
occultism-1.0.4.jar
OptiFine_1.16.4_HD_U_G6.jar
OptiForge-MC1.16.4-0.4.6.jar
pamhc2crops-1.16.3-1.0.1.jar
pamhc2foodcore-1.16.3-1.0.1.jar
pamhc2foodextended-1.16.3-1.0.0.jar
pamhc2trees-1.16.3-1.0.0.jar
Patchouli-1.16.4-48.jar
Placebo-1.16.3-4.3.3.jar
RingOfAttraction-1.16.4-1.2.11.jar
RingOfBlink-1.16.4-1.2.7.jar
RingOfGrowth-1.16.4-1.2.6.jar
RingOfMiner-1.16.4-1.2.9.jar
RingOfRepair-1.16.4-1.2.10.jar
RingOfReturn-1.16.4-1.1.6.jar
RingOfTeleport-1.16.4-1.2.6.jar
RingOfUnseen-1.16.4-1.0.6.jar
scuba-gear-1.16.4-1.0.1.jar
SereneSeasons-1.16.4-4.0.0.86-universal.jar
simpleplanes-1.16.3-3.2.0.3.jar
sleeping_bags-1.16.4-1.0.1.jar
SpartanShields-1.16.4-2.1.0.jar
spiders-2.0-1.16.4-1.0.4.jar
structure_gel-1.16.4-1.7.5.jar
structurize-0.13.96-ALPHA-universal.jar
TheAbyss+2.0.0+1.16.4.jar
the_bumblezone-1.16.5-2.2.11.jar
thermal_cultivation-1.16.3-1.1.6.jar
thermal_expansion-1.16.3-1.1.6.jar
thermal_foundation-1.16.3-1.1.6.jar
thermal_innovation-1.16.3-1.1.7.jar
thermal_locomotion-1.16.3-1.1.6.jar
titanium-1.16.4-3.2.5.jar
towers_of_the_wild-1.16.4-2.0.1.jar
Undefeatables+1.1.jar
valhelsia_structures-16.0.5.jar
WaterStrainer-1.16.3-10.0.0.jar
WAWLA-1.16.4-7.0.2.jar
Waystones_1.16.3-7.3.1.jar
Xaeros_Minimap_21.1.0_Forge_1.16.5.jar
xptome-1.16.4-v2.0.1.jar

## Log Files/Crash Reports
[crash-2021-02-12_19.20.27-client.txt](https://github.com/sp614x/optifine/files/5974821/crash-2021-02-12_19.20.27-client.txt)

## F3 Debug Screenshot
I can't take in-game capture using F3 since when trying to enter the world it gives me an error.

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
No, it loads the world normally, but I need to use OptiFine for smooth gameplay.

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
No, work normaly, only OptiFine and Forge.

- Does this happen without any mods at all?
No.

- Does this happen in OptiFine standalone?
No.

- Does this happen in Vanilla without OptiFine?
No.

- Have you tried using a binary search to find which mods cause this issue?
Yes, all 'mods' work fine, when I integrate 'Mekanism-1.16.4-10.0.19.446.jar' it conflicts with OptiFine and gives the error.

- Does the issue still happen with only the remaining mods installed?
Without 'Mekanism-1.16.4-10.0.19.446.jar' and with OptiFine everything works fine.

With 'Mekanism-1.16.4-10.0.19.446.jar' and without OptiFine everything works fine.

- Forge/Fabric and remaining mods, without OptiFine
Works well.

**Comment by Churchexe** [comment]
the fact that this is still an issue is kind of a major bummer to be honest, mek is one of the like baseline required tech mods, especially with things like the cardboard box and persistent tanks.
