### ISSUE TITLE
I Cant Login Into My Cape account

### ISSUE THREAD

**Issue by F0stylele** [sp614x/optifine#533]
Even though i legittimatly bought a cape i cant get access to my cape account and i've tried to reset my email and password aswell What do i need to do?
and btw i can see my cape in game but as i said i cant get into my cape account

**Comment by sp614x** [comment]
What error is returned?

**Comment by F0stylele** [comment]
the error that is raeturned is invalid credentials but my cape shows in game i could give u a screenshot

**Comment by sp614x** [comment]
The "Invalid credentials" error comes from the Mojang authentication servers.
