### ISSUE TITLE
OptiFine Won't Download to My Computer

### ISSUE THREAD

**Issue by Qauppi** [sp614x/optifine#5332]
## Description of Issue
When I try to download OptiFine (of any version) I can get through all of the steps, up until it's supposed to be downloaded. At that point, an error message with [message below] pops up.
"Unable to install Java

There are errors in the following switches:
(fill in file position here) 

Check the the commands are valid and try again."

## Steps to Reproduce
1. I went to https://optifine.net/downloads
2. Clicked on (Mirror)
3. Clicked on Download
4. Download file said "This type of file can harm your computer" as usual. I clicked Keep
5. Right clicked file and clicked Open
6. "Do you want to allow this to make changes to your device?" Clicked Yes
7. Error message popped up after a few seconds

## OptiFine Version
I tried with 1.16.4, 1.16.5, and 1.8.4

## Installation Method
I used the standalone installer.

## Prior Testing
If you've installed standalone:
Well I can't open the OptiFine version so... no it only happens with OptiFine?

## Additional Information
Here's the error message:
![image](https://user-images.githubusercontent.com/79272275/108388197-62d80480-71dc-11eb-960b-6833e115dc6d.png)
Because it's not OptiFine itself and it's just my computer, I completely understand if no one knows how to fix this ^^;

**Comment by ButterSpreadBread720** [comment]
do you have this installed?

https://www.java.com/en/download/

**Comment by PixelatedVolume** [comment]
There's a way to use the Java installation that comes with your Minecraft in order to install Optifine, but it's a little complicated.  See if [this](https://www.ravbug.com/tutorials/optifine-no-java/) gets you anywhere.

**Comment by Qauppi** [comment]
> do you have this installed?
> 
> https://www.java.com/en/download/

Thanks for helping, but I tried that and it didn't help.


> There's a way to use the Java installation that comes with your Minecraft in order to install Optifine, but it's a little complicated. See if [this](https://www.ravbug.com/tutorials/optifine-no-java/) gets you anywhere.

Same to you. Like you said, it's a little complicated xD
I tried going through the instructions multiple times but couldn't figure out what I was doing wrong. I just kept getting the message "The system cannot find the path specified".

**Comment by KaiAF** [comment]
A bit late and I dont know if you ever resolved the issue, but try installing [Jarfix](https://johann.loefflmann.net/jarfix). If that helps let me know.

**Comment by KaiAF** [comment]
Closing this as it doesn't seem like any new issues have occurred.
