### ISSUE TITLE
Optifine isn't loading my worlds at all.

### ISSUE THREAD

**Issue by TheAwesomeRip** [sp614x/optifine#5333]
## Description of Issue
When I use optifine, all of my worlds don't even load. When I go into the single player menu, it acts like I don't have any worlds at all, and takes me to the "Create new world" menu. When I have a world, and go back the world selection screen, I see only that world.
## Steps to Reproduce
On Bing, type "Optifine.net" at the URL. Go to downloads, press Download next to "Optifine HD U G6", and wait past the ad foc.us, and then press skip, then Download, wait, press "Keep" next to my computer's antivirus, then press "open file",  and then press "install" without the minecraft launcher open. Open the minecraft launcher, use Optifine 1.16.5, and open the singleplayer menu.

## OptiFine Version
Optifine HD U G6 1.16.5.
## Installation Method
Optifine.net downloads
## Other Installed Mods
None
## Log Files/Crash Reports
None
## F3 Debug Screenshot
Here's a screenshot I took in the version, in creative mode. The (admittedly beautiful) landscape has nothing to do with it.
![image](https://user-images.githubusercontent.com/79292833/108448362-69836d80-7216-11eb-9023-12363b03cd46.png)
## Prior Testing
When I don't Use optifine, my worlds load normally. But whenever I do, I can't load my worlds. This bug only works with optifine on.
## Additional Information 
I am using Windows 10 Home.

**Comment by L33Tech** [comment]
Are you using a different install folder for the optifine instance?

**Comment by KaiAF** [comment]
Are you still having this issue? If so, answer the first question.

**Comment by KaiAF** [comment]
No response from author, assume its resolved.
