### ISSUE TITLE
CIT issue with lores and colored names

### ISSUE THREAD

**Issue by Thomas11127** [sp614x/optifine#5343]
## Description of Issue
To have a custom armor i wanted the texture to appear when a netherite armor have a lore but it didn't work. I tried with names and it works but it don't work with colored names

## Steps to Reproduce
For Lores : I used all the possibilities from the documentation https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/cit_single.properties nothing work.
For Names i followed this doc too.

## OptiFine Version
1.16.4

## Installation Method
I used the standalone installer

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
- CIT is an Optifine fonctionnality so no.

## Additional Information
Here goes any final remarks and everything else that might not fit in the previous sections.

It would be so cool if we can combine CIT and CustomModelData ^^

Thank You

**Comment by Helwdro** [comment]
in 1.16 minecraft changed how colored name works, to suport names in hex color.
now the nbt.display.Name does not work with multiple colored names 
there a thread on reddit explaning the ploblem
link:  https://www.reddit.com/r/Optifine/comments/i0wgs1/custom_item_textures_not_working_on_colored_item/

and about cit with CustomModelData, it already works, in fact I'm using it in a resoucepack.

**Comment by sp614x** [comment]
Latest preview fixes CIT with colored names.
The CIT text can be given without color codes and it will match the colored text.
