### ISSUE TITLE
no gui

### ISSUE THREAD

**Issue by Theiromia** [sp614x/optifine#5345]
i am using the G7 version of the mod, 1.16.5, and i can't see my GUI, i can see the items in my hand but i can't see any form of GUI like inventory, escape menu, clicking a crafting table, or opening a book.

**Comment by j-rodshub** [comment]
Are you using Xaero's Minimap mod?  I have this issue as well, and narrowed it down to Xaero's Minimap mod being the culprit in my Mod stack.

**Comment by j-rodshub** [comment]
there is an issue in that repository as well https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap/issues/341

**Comment by JOHN30011887** [comment]
Thanks so dam much @j-rodshub 
i was getting annoyed i couldnt figure what was going on with the no gui at all when i used the updated optifine
i just removed the mod Xaero's Minimap and now it works properly again, thanks so much

**Comment by j-rodshub** [comment]
No problem.  By the way, updating to the latest Minimap and World map from Xaero fixed the issue entirely, and I can now use all mods + this G7 branch!

**Comment by KaiAF** [comment]
Closing this as it seemed to be axaeros minimap issue. Correct me if I am wrong, please.
