### ISSUE TITLE
[1.16.5] Invisible Mobs (Still)

### ISSUE THREAD

**Issue by James-Fosterz** [sp614x/optifine#5346]
## Description of Issue
This issue has been around for a while but still persists in the most recent version. I should note with a few hundred hours of playing the only mob that has appeared invisible is the piglin brute. However this has occurred pretty much all the time. They appear invisible and what appears to be invenureably more than they can actually be seen 

## Steps to Reproduce
Start a world (playing hard mode) go find any bastion in survival pilin brutes will commonly appear invisible, very easy to hear when they are after you which helps.

## OptiFine Version
1.16.5 
OptiFine_1.16.5_HD_U_G6.jar (primarily)

## Installation Method
I have tried both as well as running through fabric using OptiFabric, results are the same for all.

## Fabric/Forge Version
1.16.5 (when used)
0.6.1.51 Fabric

## OptiFabric Version
1.9.2 (when used)

## Other Installed Mods
None

**If OptiFine is installed as standalone, remove this section.**

## Log Files/Crash Reports
N/A

## F3 Debug Screenshot
N/A

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
NO
If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   - Only OptiFine and Forge
(NOT TESTED)
   - Only OptiFine, OptiFabric, and Fabric
YES
- Does this happen without any mods at all?
   - Only Forge/Fabric by itself.
NO
- Does this happen in OptiFine standalone?
YES
- Does this happen in Vanilla without OptiFine?
NO
- Have you tried using a binary search to find which mods cause this issue?
NO
   - To find conflicting mods, split your mods into 2 groups (not including OptiFine/OptiFabric, obviously). Remove one group, and test in-game. Keep the group that has the problem, and repeat until no more mods can be removed without the issue disappearing.
   - Does the issue still happen with only the remaining mods installed?
NO
      - Forge/Fabric and remaining mods, without OptiFine

## Additional Information
Pretty self explanatory, I know many other people have had this in some form and is some what of a persisting issue

**Comment by berkkrkc09** [comment]
When they say they need OptiFine version, they really mean it.

**Comment by bionicleFanatic** [comment]
Same problem for me: but it’s not just with piglin brutes, it can happen to any “unique” mob, too - specifically ones that have been renamed. It might be to do with how they’re tagged in the chunk saves.

**Comment by Regnander** [comment]
> Same problem for me: but it’s not just with piglin brutes, it can happen to any “unique” mob, too - specifically ones that have been renamed. It might be to do with how they’re tagged in the chunk saves.

What OptiFine version are you using? G8 pre1?

**Comment by bionicleFanatic** [comment]
> What OptiFine version are you using? G8 pre1?

HD U G3 for 1.16.2, actually. It's an older version, but given the issue's persistence across releases I'd assume they come from the same source.

**Comment by KaiAF** [comment]
> OptiFine_1.16.5_HD_U_G6.jar (primarily)

This bug was fixed in G7 [(Changelog)](https://optifine.net/changelog?f=OptiFine_1.16.5_HD_U_G7.jar). If you are having this issue on that version as well, please let me know. Until then, I am going to close this ticket as it was fixed in another version.
