### ISSUE TITLE
[1.16.5 G7] Huge input lag

### ISSUE THREAD

**Issue by Dark11Void** [sp614x/optifine#5348]
## Description of Issue
It takes a considerable amount of time for attack inputs on NPCs and other players to register. This is more prominent on servers (500-1000 ms), but still very noticeable in singleplayer. This issue doesn't appear in G6 nor vanilla Minecraft.

## Steps to Reproduce
No necessary steps required. Just play.

## OptiFine Version
Self-explanatory. 

## Installation Method
Standalone.

## Other Installed Mods
None

## Log Files/Crash Reports
[latest.log](https://github.com/sp614x/optifine/files/6020352/latest.log

## Video Link
https://www.youtube.com/watch?v=m1aYzQlOM08

**Comment by HexedHero** [comment]
Same issue here, updated my preview version and noticed some weird lag even when doing a command that sends the player 10-20 lines back of information it'll show each line every like 5-10ms instead of all at once like vanilla or unmodded forge.

**Comment by KaiAF** [comment]
Weird, can you provide an F3 debug menu screenshot? It seems like it isn't reproducible by me. I even tried what HexedHero said

**Comment by albertboettger** [comment]
I am seeing a similar effect.  I have rolled back to G6 for now as the lag made my game difficult to play.  A quick example that I noticed immediately was breaking a bed.  With G6 as soon as the bed broke the sound was instant and the bed was ready to pick up.  In G7 there is a 1/2 second or more delay, then the sound and then bed then appears.  A half second is a HUGE delay in a game like this.  I also noticed other similar slowdowns with G7, like opening gates or doors, that were delayed.

**Comment by KaiAF** [comment]
Are you able to send a video of it happening, possibly even the settings you have enabled?

**Comment by Dark11Void** [comment]
> Are you able to send a video of it happening, possibly even the settings you have enabled?

I put a video on YouTube showcasing the issue. First with G7 and then vanilla Minecraft. Debug info and capture of my in-game settings are included. This is not just audio delaying; when playing in Singleplayer I would notice mobs taking additional time to take damage along with hit sound registry. I haven't played extensively with G7, as I couldn't tolerate it for long; so my testing isn't exhaustive.

Link:
https://www.youtube.com/watch?v=m1aYzQlOM08

**Comment by KaiAF** [comment]
Thank you for the video. I was able to reproduce it. 
I copied all your settings and it was happening to me. I then narrowed it down to the setting "Lazy chunk Loading". Turn that setting off, and see if it helps.

**Comment by HexedHero** [comment]
Can also confirm turning off LCL fixes the issue.

**Comment by Dark11Void** [comment]
> Thank you for the video. I was able to reproduce it.
> I copied all your settings and it was happening to me. I then narrowed it down to the setting "Lazy chunk Loading". Turn that setting off, and see if it helps.

Disabling Lazy Chunk loading seems to have done the trick.

**Comment by sp614x** [comment]
Fixed, coming in next preview.
