### ISSUE TITLE
Iron Tools give off dynamic light and interfere with normal vision.

### ISSUE THREAD

**Issue by Zarepheth** [sp614x/optifine#535]
As the title says, when playing with Optifine (and a ton of other mods) my iron tools become dynamic light sources. Worse, they are colored (a bit towards purplish-red) and interfere with normal vision. For that matter, even torch light interferes with normal vision, making the whole screen very bright.

By adjusting atmospheric effects (SEUS-v11.0 shader options), the glow can be reduced but does not go away.

I just switched from SEUS to the Internal shader and the weird lighting went away. Of course, so too did the other effects of that shader - I'm not sure if that is good or bad... (everything is now brighter).

**Comment by sp614x** [comment]
Screenshot?

**Comment by Vwhbj2003** [comment]
I'm having a similar issue with different items. What can be done to help.
