### ISSUE TITLE
[Shaders] it doesnt work

### ISSUE THREAD

**Issue by INeedHelP2007** [sp614x/optifine#5350]
## Description of Issue
shaders just dont work on my pc for some reason i get an error that says "Error Invalid Program"

## Steps to Reproduce
1. What do you do... 
2. ...to find this bug?

## OptiFine Version
Newest 1.16.4 version

## Installation Method
How did you install OptiFine? Did you use the included standalone installer, or did you drop the JAR file into your "mods" folder?
I just intalled optifine from the official site and installed it

## Other Installed Mods
/

## Log Files/Crash Reports
"Error Invalid Program:"

## F3 Debug Screenshot
![2021-02-22_16 02 57](https://user-images.githubusercontent.com/79464101/108726368-a063c700-7527-11eb-902c-8db39ab36c45.png)

## Prior Testing
/
## Additional Information
/

**Comment by TerminalHash** [comment]
Components of PC?

**Comment by INeedHelP2007** [comment]
> Components of PC?

PC

**Comment by Stereo528** [comment]
as shown in the f3 screenshot, an i7-4702HQ and an iGPU HD Graphics 4600, which is fairly old and can't support the features shaders have it seems
