### ISSUE TITLE
[Potential Fix] Trick Discord into detecting OptiFine as Minecraft

### ISSUE THREAD

**Issue by rizecookey** [sp614x/optifine#5351]
After some testing, I have figured out how Discord detects Minecraft: It scans any running javaw.exe executable and checks if that process is running with the argument "net.minecraft.client.main.Main" passed onto it (to check if the main class matches the one used in vanilla). However, it doesn't matter where in the arguments that string is - as long as it is found, Discord will detect that javaw.exe process as Minecraft.
Therefore, simply adding "net.minecraft.client.main.Main" to the game argument array in the version's .json file would make Discord detect OptiFine as Minecraft. It could also possibly improve compatibility with other programs like the GeForce Experience Overlay that interact with Minecraft - I haven't tested that yet though.

**Comment by ZenIsBestWolf** [comment]
Can you provide steps to produce?

**Comment by KyriaBirb** [comment]
Tested, works
just go to %appdata%/.minecraft/versions/[version name] open the json file and add ``"net.minecraft.client.main.Main"`` to 
``"arguments": {
    "game": [``
    or `` "minecraftArguments":`` depending on the game version

**Comment by chasejsutton49** [comment]
This does fix the Discord issue, but does not fix Xbox Game Bar not being supported when fullscreen.

**Comment by JudgeRay** [comment]
> Tested, works
> just go to %appdata%/.minecraft/versions/[version name] open the json file and add `"net.minecraft.client.main.Main"` to
> `"arguments": { "game": [`
> or ` "minecraftArguments":` depending on the game version

I did this and the game crashes

**Comment by rizecookey** [comment]
> This does fix the Discord issue, but does not fix Xbox Game Bar not being supported when fullscreen.

For me the Xbox Game Bar doesn't work with vanilla Minecraft either.

**Comment by pokkopit** [comment]
> > Tested, works
> > just go to %appdata%/.minecraft/versions/[version name] open the json file and add `"net.minecraft.client.main.Main"` to
> > `"arguments": { "game": [`
> > or ` "minecraftArguments":` depending on the game version
> 
> I did this and the game crashes

it should look like this: (thank god for my very entry level coding knowledge)
 "arguments": {
    "game": [
	"net.minecraft.client.main.Main",
(hit enter once after the [ bracket, then hit tab once, then paste "net.minecraft.client.main.Main" and add a comma)

**Comment by pokkopit** [comment]
> > Tested, works
> > just go to %appdata%/.minecraft/versions/[version name] open the json file and add `"net.minecraft.client.main.Main"` to
> > `"arguments": { "game": [`
> > or ` "minecraftArguments":` depending on the game version
> 
> I did this and the game crashes

hit enter once after the bracket, then hit tab once, then paste "net.minecraft.client.main.Main" and add a comma.

**Comment by satriamjati** [comment]
works well on my 1.14.4 and 1.16.5 optifine, but doesn't work for my 1.17 pre21.

**Comment by pokkopit** [comment]
i only have really entry level knowledge about coding but it seems like the net.minecraft.client.main.Main string is what discord uses to detect the game. so as long as it's present in the json and formatted properly to fit into the code, it should work. but, like i said, only very entry level knowledge, so idk

**Comment by rizecookey** [comment]
> works well on my 1.14.4 and 1.16.5 optifine, but doesn't work for my 1.17 pre21.

Works fine for me on 1.17 as well. If you're testing with Discord, make sure the overlay is activated for Minecraft under the "Activity Status" menu in the Discord settings (1.17 uses a different runtime directory due to the switch to Java 16, so it might be disabled again). You can see that it's been detected if it shows up above your username and profile picture in Discord.

**Comment by chasejsutton49** [comment]
An update correlating to the Xbox Game Bar issue: it's not Optifine-related. I just believed so because I used to have a computer where it worked without Optifine, but didn't with. As I'm playing without Optifine, the Xbox Game Bar is not working while I'm fullscreen. I don't know how to fix it or how it's been fixed before, but I can say with certainty that Optifine is not a factor in the Xbox Game Bar issue.

**Comment by satriamjati** [comment]
After playing on 1.16.5 and see this github. I tried on 1.17 today, it works well without change anything. I'm not sure why.  Not even changing "Activity Status", it was already enabled. But I'm sure, discord couldn't detected as "Minecraft" nor "Minecraft* 1.17" on my past 1.17 experience. Discord detected no game.

**Comment by byter11** [comment]
On 1.17.1, it kept removing the "net.minecraft.client.main.Main" string, so I had to do it like this (just followed the format of other values in the "game" object) :
`"game": [
      {
        "values": [
          "net.minecraft.client.main.Main"
        ],
        "rules": []
      },
      {. ...`

**Comment by JamieBrassel** [comment]
Somewhat related. If you are using the Curseforge launcher, Optifine or no, changing the profile folder's name to "net.minecraft.client.main.Main" also does the trick. I imagine changing the game folder to be called that would also work with the default launcher.

**Comment by mastermig1705** [comment]
> 
> 
> > > Tested, works
> > > just go to %appdata%/.minecraft/versions/[version name] open the json file and add `"net.minecraft.client.main.Main"` to
> > > `"arguments": { "game": [`
> > > or ` "minecraftArguments":` depending on the game version
> > 
> > 
> > I did this and the game crashes
> 
> hit enter once after the bracket, then hit tab once, then paste "net.minecraft.client.main.Main" and add a comma.

tried placing the string in every possible position I could think of that would fit and my game still crashed, can you describe what bracket you mean (theres like 10)

**Comment by mastermig1705** [comment]
made it work in versions where it says "arguments": { "game": [, cant manage to get it to work on "minecraftArguments": versions like 1.8.9, the game crashes with a "unexpected error" message.

**Comment by mastermig1705** [comment]
made it work in 1.8.9, had to add:
--ignoreThis: net.minecraft.client.main.Main
in the arguments and remove all mods, then reload with mods and worked fine.

**Comment by kulaid** [comment]
Doesn't seem to work for me on 1.18

**Comment by NontTheKiller** [comment]
> Doesn't seem to work for me on 1.18

I confirm that it working on 1.18.1

**Comment by robertfwallis** [comment]
Can confirm this works with OptiFine HD Ultra H4 on Minecraft 1.18.1. As long as you add

> net.minecraft.client.main.Main

to the top of the list, like so...

```
    "game": [
      "net.minecraft.client.main.Main",
      "--tweakClass",
      "optifine.OptiFineTweaker"
    ]
```

Make sure that your text editor isn't adding widespaces as opposed to normal spaces, and that you add a comma at the end of the line.

**Comment by robertfwallis** [comment]
Tagging @sp614x ^

**Comment by iAtog** [comment]
Hi, I would like to know how I could do that with the MultiMC launcher.

**Comment by TheSiZaGaming** [comment]
> Can confirm this works with OptiFine HD Ultra H4 on Minecraft 1.18.1. As long as you add
> 
> > net.minecraft.client.main.Main
> 
> to the top of the list, like so...
> 
> ```
>     "game": [
>       "net.minecraft.client.main.Main",
>       "--tweakClass",
>       "optifine.OptiFineTweaker"
>     ]
> ```
> 
> Make sure that your text editor isn't adding widespaces as opposed to normal spaces, and that you add a comma at the end of the line.
> 
> ![image](https://user-images.githubusercontent.com/11021224/153590461-62958c14-f82c-4f75-9b26-f4b6a888f64e.png)

I cannot thank you enough. This is the proper fix for this issue. Works with OptiFine HD U H4 on Minecraft 1.18.1.
Still, I reckon this is fixable by OptiFine devs.

**Comment by V4LLE** [comment]
@TheSiZaGaming thanks, it works for me in 1.18.2!

**Comment by LoganTann** [comment]
Adding the string to JVM arguments works too

In my case, I edited the optifine config

![image](https://user-images.githubusercontent.com/28659185/161115599-d66a7c84-5551-4e10-920a-dee8221a9510.png)

Then, appended this string : `-Ddiscordrichpresence=" net.minecraft.client.main.Main "`

![image](https://user-images.githubusercontent.com/28659185/161115993-c1d73106-f3a3-4aa9-ba0b-d5272033742d.png)

I'm not sure that setting our own -D flag (system property value) is dangerous, I think it shouldn't be since it have to be ignored.

**Comment by ZenIsBestWolf** [comment]
The above comment about using a JVM argument is likely the best solution, as this general argument can be added to any form of Minecraft (works for me in ManyMC, which I can have configured for anything including OptiFine).

**Comment by NontKrub** [comment]
> Adding the string to JVM arguments works too
> 
> In my case, I edited the optifine config
> 
> ![image](https://user-images.githubusercontent.com/28659185/161115599-d66a7c84-5551-4e10-920a-dee8221a9510.png)
> 
> Then, appended this string : `-Ddiscordrichpresence=" net.minecraft.client.main.Main "`
> 
> ![image](https://user-images.githubusercontent.com/28659185/161115993-c1d73106-f3a3-4aa9-ba0b-d5272033742d.png)
> 
> I'm not sure that setting our own -D flag (system property value) is dangerous, I think it shouldn't be since it have to be ignored.

   Confirm working on MultiMC and normal Minecraft Launcher

**Comment by itschelbro** [comment]
> 

Do i justneed to add `-Ddiscordrichpresence=" net.minecraft.client.main.Main "` to the end of the JVM arguments?

**Comment by itschelbro** [comment]
> > Adding the string to JVM arguments works too
> > In my case, I edited the optifine config
> > ![image](https://user-images.githubusercontent.com/28659185/161115599-d66a7c84-5551-4e10-920a-dee8221a9510.png)
> > Then, appended this string : `-Ddiscordrichpresence=" net.minecraft.client.main.Main "`
> > ![image](https://user-images.githubusercontent.com/28659185/161115993-c1d73106-f3a3-4aa9-ba0b-d5272033742d.png)
> > I'm not sure that setting our own -D flag (system property value) is dangerous, I think it shouldn't be since it have to be ignored.
> 
> Confirm working on MultiMC and normal Minecraft Launcher

Does this need to be put back in after new minecraft/optifine updates?

**Comment by TheSiZaGaming** [comment]
> > > Adding the string to JVM arguments works too
> > > In my case, I edited the optifine config
> > > ![image](https://user-images.githubusercontent.com/28659185/161115599-d66a7c84-5551-4e10-920a-dee8221a9510.png)
> > > Then, appended this string : `-Ddiscordrichpresence=" net.minecraft.client.main.Main "`
> > > ![image](https://user-images.githubusercontent.com/28659185/161115993-c1d73106-f3a3-4aa9-ba0b-d5272033742d.png)
> > > I'm not sure that setting our own -D flag (system property value) is dangerous, I think it shouldn't be since it have to be ignored.
> > 
> > 
> > Confirm working on MultiMC and normal Minecraft Launcher
> 
> Does this need to be put back in after new minecraft/optifine updates?

Yes, I think you will. Like I said earlier, since this is such a super easy fix I wonder why the OptiFine developers haven't fixed this already.

**Comment by ZenIsBestWolf** [comment]
> > > > Adding the string to JVM arguments works too
> > > > In my case, I edited the optifine config
> > > > ![image](https://user-images.githubusercontent.com/28659185/161115599-d66a7c84-5551-4e10-920a-dee8221a9510.png)
> > > > Then, appended this string : `-Ddiscordrichpresence=" net.minecraft.client.main.Main "`
> > > > ![image](https://user-images.githubusercontent.com/28659185/161115993-c1d73106-f3a3-4aa9-ba0b-d5272033742d.png)
> > > > I'm not sure that setting our own -D flag (system property value) is dangerous, I think it shouldn't be since it have to be ignored.
> > > 
> > > 
> > > Confirm working on MultiMC and normal Minecraft Launcher
> > 
> > 
> > Does this need to be put back in after new minecraft/optifine updates?
> 
> Yes, I think you will. Like I said earlier, since this is such a super easy fix I wonder why the OptiFine developers haven't fixed this already.

I will raise this directly with sp614x to be added to the JVM Arguments when a new OptiFine profile is created.

**Comment by sp614x** [comment]
I suppose any system property would work as long as the value is " net.minecraft.client.main.Main ".
In this case I would use something more descriptive like `-Ddiscordfix= "net.minecraft.client.main.Main "`

**Comment by sp614x** [comment]
Also seems to work without the spaces `-Ddiscordfix="net.minecraft.client.main.Main"`

**Comment by sp614x** [comment]
Fixed, coming in next preview.

**Comment by TheSiZaGaming** [comment]
> Fixed, coming in next preview.

Thank you very much. Glad that this issue can finally be resolved.

**Comment by F-fengzi** [comment]
> Fixed, coming in next preview.

As far as I know it hasn't been working by default for some time if this ever got implemented.

**Comment by TheSiZaGaming** [comment]
> > Fixed, coming in next preview.
> 
> As far as I know it hasn't been working by default for some time if this ever got implemented.

Working for me on OptiFine HD U I3 for Minecraft 1.19.4.
![image](https://user-images.githubusercontent.com/86504702/227874940-d9a052a3-4ef0-44c9-be37-c9a66b52f38b.png)
