### ISSUE TITLE
[BUG] Lazy Chunk Loading causes multiplayerside mobs inconsistent

### ISSUE THREAD

**Issue by Darwin1546** [sp614x/optifine#5353]
## Description of Issue
Multiplayer servers can have custom modeled mobs by utilizing armorstand mechanics. This works buy sending packets to the player. But when Lazy Chunk Loading is turned ON (which is default state), this armorstand motion becomes inconsistent and looks desynced.
This doesn't happen with vanilla or Lazy Chunk Loading turned OFF

## Steps to Reproduce
1. Make server with custom mob (Model Engine or similar) https://www.spigotmc.org/resources/conxeptworks-model-engine%E2%80%94ultimate-entity-model-manager-1-14-1-16-5.79477/
2. Look at moving parts of the mob

## OptiFine Version
OptiFine_1.16.5_HD_U_G7

## Fabric/Forge Version
Forge 36.0.42

## Additional Information
Description of this option says that it's only useful for local worlds, but looks like it's not.

**Comment by KaiAF** [comment]
A bit late, but this should have been fixed #5348. If you are still having issues, let me know.
