### ISSUE TITLE
achievements gone

### ISSUE THREAD

**Issue by heckrum** [sp614x/optifine#5355]
i made a new minecraft world about a month ago and was doing pretty well in it, when my game crashed. i reopened minecraft and went into my world, and all of my achievements in the pause menu were gone. i got like five when i got into the world because of what was in my inventory, but other than that there werent any achievements. now you may be wondering 'hey! if this is true, then wouldnt it be a minecraft glitch?' and normally youd be right, but i already have went to minecraft and they responded with "your games modded so we cant fix it." so i came over here.

**Comment by TestowyTest456** [comment]
Hi, it does not look like an issue with Optifine, it looks that Your UUID has changed. Make sure that You are using same account that You used to create a new world, or if You are using cracked/offline launcher, make sure that You are using same username and launcher that You used to start a game for a first time. You can check "advancements" folder in Your world save, if it is really an UUID issue, You will find 2 or more .json files each with different UUID. Such issue is possible to reproduce when You create a world with for example Shiginima launcher and  load same world using for example SKLauncher, as they give different UUID for same username. Of course if You use official launcher  and premium account and You have this issue, please ignore this comment, as there can be real issue with Optifine

**Comment by KaiAF** [comment]
as the user above said, I don't know if this is an OptiFine issue. I believe the achievements are set to the player's UUID. And if it's changed, then it would reset.

**Comment by KaiAF** [comment]
Closing this as you haven't responded. If you have any issues, let us know.

**Comment by heckrum** [comment]
the thing about that is that i went to minecraft first, and they said because i had a mod they wouldnt look into it

**Comment by minthousebuilder** [comment]
Sounds like the file got corrupted when the game crashed
