### ISSUE TITLE
[OptiFine] Invalid grid V

### ISSUE THREAD

**Issue by CarsonJF** [sp614x/optifine#5356]
## Description of Issue
Console spammed with [OptiFine] Invalid grid V. I'm aware that its resource pack related, however the pack looks and feels fine in game, and this bug is mostly hindering the ability to read any use info from the log file for pack errors. I've been unable to find any documentation on this issue.

## Steps to Reproduce
1. launch game. enable pack.

## OptiFine Version
1.16.5 G6

## Installation Method
Installer

**Comment by KaiAF** [comment]
What pack are you using? What's the log?

**Comment by KaiAF** [comment]
No reply from the author, assume it's fixed now.
