### ISSUE TITLE
 OptiFine HD U G7 crashes on launch.

### ISSUE THREAD

**Issue by F3lizxad** [sp614x/optifine#5365]
I have recently been wanting to load Minecraft, and it was working beautifully yesterday. But as soon as I tried to load Optifine, my game crashed and didn't even launch Minecraft. I tried also on my second laptop, but the same happened. Hope you fix this problem. :[

**Comment by TerminalHash** [comment]
Yesterday played - all works. Search problems on your side.

**Comment by TerminalHash** [comment]
Or give crashlog, please.

**Comment by F3lizxad** [comment]
Checked the crash-reports folder, but nothing appeared.

**Comment by Cian-R** [comment]
Having the same problem. Was working totally fine yesterday. Updated/reinstalled graphics drivers. Minecraft crashes before it can even open with "Error Code: 0"

**Comment by F3lizxad** [comment]
I found a solution, as soon as unchecked "Use beta version of the Launcher" in settings, I am able to load Optifine again.

**Comment by Cian-R** [comment]
Oh lmao that actually fixed it. Thanks. Hopefully they fix this issue :/

**Comment by F3lizxad** [comment]
I'll send optifinex@gmailo.com a report of the situation. Peace!

**Comment by Hundr** [comment]
I was having the same issue as reported here. Using Java 8 build 281. In the launcher settings I do not have the beta version checked, or installed. Switching to the built in version of Java allowed 1.16.5-OptiFine_HD_U_G7 to launch without issue.

**Comment by shbz1** [comment]
My issue is still not fixed even after i unticked the use beta launcher
