### ISSUE TITLE
Optifine 1.16.5 G7 error Code 0

### ISSUE THREAD

**Issue by Lennmonade** [sp614x/optifine#5366]
minecraft lanucher shows code 0 while I tried to play. But while I didn't use optifine. it allows me in

1.16.5 G7

## Installation Method
from the website

## Log Files/Crash Reports

[latest.log](https://github.com/sp614x/optifine/files/6035149/latest.log)

**DO NOT directly copy and paste log contents here on GitHub.**

it doesn;t even into minecraft. I am just stuck in minecraft lanucher

![Screenshot (638)](https://user-images.githubusercontent.com/79574233/108985530-1f920000-76cc-11eb-9062-bdb24a641f1f.png)
![Screenshot (637)](https://user-images.githubusercontent.com/79574233/108985536-20c32d00-76cc-11eb-93cc-ecbbfd07d2e7.png)

oh and yes there were no crash reports

**Comment by F3lizxad** [comment]
Uncheck in settings, "Use beta version of Launcher."

**Comment by Lennmonade** [comment]
thanks g

**Comment by F3lizxad** [comment]
Knew it.
