### ISSUE TITLE
1.16.4 & 1.165 Optifine keeps crashing

### ISSUE THREAD

**Issue by LotsaNames** [sp614x/optifine#5368]
## Description of Issue
Before my minecraft launcher updated optifine 1.16.4 and 5 was working perfectly but after the update it just started crashing my launcher like when I press "PLAY" it loads for a bit and just tell me "unexpected error, exit code: 0"

## Steps to Reproduce
Launch optifine

## OptiFine Version
1.16.4, 1.16.5

## Installation Method
I used the jar setup

## Log Files/Crash Reports
https://pastebin.com/xeNRgczd

You can get logs from `.minecraft/logs`, and crash reports from `.minecraft/crash-reports`. 
Locating your `.minecraft` folder will depend entirely on your OS. See this page for details: https://minecraft.gamepedia.com/.minecraft

**DO NOT directly copy and paste log contents here on GitHub.**

## F3 Debug Screenshot
Minecraft's built-in debug screen provides *a lot* of useful information, and should be included even if the issue is not something that can be captured in a still image.

To open this menu, simply press `F3` on your keyboard while in-game. Please ensure the text is easily readable. Depending on the size/resolution of your monitor, you may have to adjust your GUI scale for all text to be completely visible on-screen.

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
No when I launch Vanilla minecraft it works perfectly fine it just crashes when I use Optifine

## Additional Information
Here goes any final remarks and everything else that might not fit in the previous sections.

**Comment by TerrinX** [comment]
Same here. Nothing works. I've uninstalled all versions of MC and Optifine and redownloaded them all to no avail

**Comment by TK5380** [comment]
IM having the exact same problem, I press play and after it "Loads" the installation for it, it crashes immediately, doesnt even open the minecraft window, just stays on the launcher

**Comment by seanisobsessedwithgwen** [comment]
I just did this right now so I'm not sure if its a permanent fix but go to setting and on general I unselected use beta version of the launcher and it launched right away without crashing.

**Comment by CodingCodre** [comment]
@seanisobsessedwithgwen  Thanks! This worked!

**Comment by KaiAF** [comment]
This seems to be fixed by either Mojang or OptiFine's recent update. If you are still having any issues, let me know.

**Comment by SlimeDog** [comment]
Still having this issue with
launcher 933 (1)
1.16.5-OptiFine_HD_U_G8_pre3 and 1.16.5-OptiFine_HD_U_G8_pre2
then changed component is the launcher -- those OptiFine versions worked fine until yesterday.
