### ISSUE TITLE
Game is not launching

### ISSUE THREAD

**Issue by Lawfix** [sp614x/optifine#5371]
## Description of Issue
I just wanted to play Minecraft this morning. I just clicked to play and the launcher downloaded a update. After update was done, game didn't launched and launcher came back with an error, "Error Code: 0". After that, I tried to launch the game with Preview version but same thing showed up again.

## Steps to Reproduce
Just tried to launch the game.

## OptiFine Version
HD U G7

## Installation Method
Just installed with normal JAR installation file with no mods, no forge or anything else.

## Log Files/Crash Reports
I couldn't find the crash report.

## Prior Testing
No, only happens with OptiFine
- Does this happen in Vanilla without OptiFine?

## Additional Information
I couldn't find latest crash report, only crash reports of G6 and G5 version was in ".minecraft" file. There wasn't any "crash-reports" file.

**Comment by Astro244** [comment]
I am also experiencing this problem with my game not opening as well

**Comment by IceCreeper28** [comment]
My optifine installation keeps crashing as well. The moment I press "Play" in the launcher it loads for a second and then crashes, while printing a javaw usage message in the game output.

**Comment by IceCreeper28** [comment]
Apparently this issue occurs with the Beta Version of the Launcher. You can opt-out of the Beta Launcher by unticking this checkbox in the Launcher settings.
![grafik](https://user-images.githubusercontent.com/31723351/109044406-a9dd6280-76d2-11eb-9bd4-796a74fe212b.png)

**Comment by Lawfix** [comment]
> Apparently this issue occurs with the Beta Version of the Launcher. You can opt-out of the Beta Launcher by unticking this checkbox in the Launcher settings.
> 
> ![grafik](https://user-images.githubusercontent.com/31723351/109044406-a9dd6280-76d2-11eb-9bd4-796a74fe212b.png)
> 
> This resolved the issue for me

Thanks! Game has launched, and I can play again!

![2021-02-24_20 08 57](https://user-images.githubusercontent.com/66887435/109045405-9509ca80-76e4-11eb-9a4e-6c0343873dd8.png)

**Comment by klokwert** [comment]
Great, also just stumbled upon the same problem, the fix works great!

**Comment by Astro244** [comment]
> Apparently this issue occurs with the Beta Version of the Launcher. You can opt-out of the Beta Launcher by unticking this checkbox in the Launcher settings.
> 
> ![grafik](https://user-images.githubusercontent.com/31723351/109044406-a9dd6280-76d2-11eb-9bd4-796a74fe212b.png)
> 
> This resolved the issue for me
you are a legend thank you so much dude

**Comment by MrKrakenied** [comment]
#5368

**Comment by ll4master** [comment]
> Apparently this issue occurs with the Beta Version of the Launcher. You can opt-out of the Beta Launcher by unticking this checkbox in the Launcher settings.
> 
> ![grafik](https://user-images.githubusercontent.com/31723351/109044406-a9dd6280-76d2-11eb-9bd4-796a74fe212b.png)
> 
> This resolved the issue for me

THANK YOU SO MUCHHHHH. I've had to just play normal without OptiFine and I was laggy.

**Comment by KaiAF** [comment]
Closing this as this has been fixed by mojang.
