### ISSUE TITLE
[Lag] Lag-Spikes

### ISSUE THREAD

**Issue by Half-Pace** [sp614x/optifine#5374]
## Description of Issue
Momentarily I get lags just roaming around both in a Single-Player as well as a Multi-player server
## Steps to Reproduce
1. Just roam around do normal stuff until Minecraft just stops working...the screen shows Not Responding and then after 8-10 seconds the FPS changes to 0/0 and then it goes back to normal.
2. This is happening to all my friends both on our multiplayer server as well as single player worlds

## OptiFine Version
Optifine 1.16.5 HD U G7 Pre8

## Installation Method
Standalone Installer/Tlauncher

## F3 Debug Screenshot
![image](https://user-images.githubusercontent.com/61351284/109145529-9987bf00-7788-11eb-8e68-96d5039a6eda.png)
![image](https://user-images.githubusercontent.com/61351284/109145547-9db3dc80-7788-11eb-8556-83ce25aa29fa.png)
![image](https://user-images.githubusercontent.com/61351284/109145559-a1dffa00-7788-11eb-921d-d8bb1eedda29.png)

## Additional Information
Its Only client side i think because there was no error or warning in the server log.

**Comment by KaiAF** [comment]
Did this issue stop when you updated OptiFine? If not, then it could be your hardware affecting it?

**Comment by Half-Pace** [comment]
well kinda...i updated it to the latest release...it still lagged...but it
was an improvement so then i removed one of the datapacks (Armored Elytra
-VanillaTweaks) and the game didnt lag anymore.
So Issue Resolved. Thank You
