### ISSUE TITLE
[Crash] Crash on startup every version

### ISSUE THREAD

**Issue by TreeV2** [sp614x/optifine#5381]
I launch my minecraft with op but on launch up its crash and its crash on every version. In logs or crash logs folders it don t create anything when its crash on startup. 

![image](https://user-images.githubusercontent.com/69603592/109198408-19685600-7796-11eb-9193-810368c3b815.png)

**Comment by Cart3r1234** [comment]
The beta version of the launcher causes a crash.

**Comment by TreeV2** [comment]
> The beta version of the launcher causes a crash.

ok so when i disable beta version of the laucher its fix.
