### ISSUE TITLE
[Bug] Texture Issue

### ISSUE THREAD

**Issue by Breadabix** [sp614x/optifine#5382]
## Description of Issue
A group of people, me included, are playing an old 1.5.2 modpack, and when optifine is installed textures on mods atomic science, ICBM, mekanism and mffs to stop working. We have narrowed it down to a bio.class but none of us know java, so we guessed this was the best palce to ask for help.

## Steps to Reproduce
1. Install voltz on the technic launcher
2. Install Optifine and look at textures from mods above

## OptiFine Version
Any 1.5.2 version, im specifically using HD_U_D5

## Installation Method
Standard installation for 1.5.2, add the optifine files into modpack.jar

## Fabric/Forge Version
forge-1.5.2-7.8.1.738

## Other Installed Mods
https://pastebin.com/rqqR4VAz

## Log Files/Crash Reports
No relevant crashes

## F3 Debug Screenshot
![2021-02-25_22 17 20](https://user-images.githubusercontent.com/19786108/109226844-4c6f1180-77b7-11eb-833f-8439967b63ea.png)

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine? No

This is with forge and other mods, it is definetely an issue caused by optifine. Without optifine the tectures work fine, https://gyazo.com/5b9818b345f7c23e9c5c30a2cc0629b6
and after adding optifine the textures stop working like this
https://gyazo.com/801baea90b5d9c787b60fb83a9db1a70

**Comment by KaiAF** [comment]
OptiFine versions before 1.7 are not supported.
