### ISSUE TITLE
guis' won't render

### ISSUE THREAD

**Issue by VanimaPermai** [sp614x/optifine#5383]
OptiFine HD U G7 1.16.5
OptiFine HD U G8 pre1 1.16.5
None of the in game guis' render whether its the hot bar or a chest the f3 menu or even the in game options menu
makes the game unplayable

**Comment by KaiAF** [comment]
Please provide more information. Like screenshots or if you have any other mods, or if you are using shaders / any resource packs.

**Comment by VanimaPermai** [comment]
screenshots taken in preview_OptiFine_1.16.5_HD_U_G8_pre3
![chest gui](https://user-images.githubusercontent.com/30294744/110536209-19167600-8119-11eb-8fe8-cc85ad8f8cb2.png)
The Chest Gui
![hotbar](https://user-images.githubusercontent.com/30294744/110536261-2af81900-8119-11eb-8d26-4ba5574833ac.png)
hotbar
![f3 screen](https://user-images.githubusercontent.com/30294744/110536312-3b0ff880-8119-11eb-9ab0-c53a4ed42381.png)
f3 screen
![chat](https://user-images.githubusercontent.com/30294744/110536368-495e1480-8119-11eb-8f2f-66f118cc039a.png)
the Chat 
![escmenu](https://user-images.githubusercontent.com/30294744/110536419-58dd5d80-8119-11eb-99ab-22e9e39938ac.png)
the esc menu
this screen shot was taken in OptiFine_1.16.5_HD_U_G6
![2021-03-07_02 25 22](https://user-images.githubusercontent.com/30294744/110536698-ac4fab80-8119-11eb-9096-9fc806a60c7e.png)
spider jockey

Mods
I'm using Create with a few other vanilla enhancing mods such as Quark
Texture pack 
modified version of vanilla tweaks
Shaders
N/A

**Comment by KaiAF** [comment]
I believe this was an issue with Journymap. This should have been fixed, if not, let me know.
