### ISSUE TITLE
OptiFine won't load with Forge

### ISSUE THREAD

**Issue by Canadianistic** [sp614x/optifine#5384]
## Description of Issue
I have OptiFine in my mods folder, Forge loads perfectly fine but when I look at the mods list, OptiFine isn't in there with the rest of my mods.

## Steps to Reproduce
1. Move OptiFine to my mods folder.
2. Press play with Forge.

## OptiFine Version
OptiFine HD U G7

## Installation Method
How did you install OptiFine? Did you use the included standalone installer, or did you drop the JAR file into your "mods" folder?
- I dropped the jar file into my folder, I also tried using the installer to extract it into my mods folder.

## Fabric/Forge Version
Forge 36.0.42 and Forge 36.0.43

## Other Installed Mods
journeymap-1.16.5-5.7.1b3

## Log Files/Crash Reports
https://pastebin.com/0niSmPQh

You can get logs from `.minecraft/logs`, and crash reports from `.minecraft/crash-reports`. 
Locating your `.minecraft` folder will depend entirely on your OS. See this page for details: https://minecraft.gamepedia.com/.minecraft

**DO NOT directly copy and paste log contents here on GitHub.**

## F3 Debug Screenshot
![2021-02-26_04 21 53](https://user-images.githubusercontent.com/79697647/109294359-4e9e9380-77ea-11eb-8b29-6311cba78e8b.png)

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
- Doesn't, it works perfectly fine standalone.

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   - Only OptiFine and Forge
   - Only OptiFine, OptiFabric, and Fabric
- Does this happen without any mods at all?
   - Only Forge/Fabric by itself.
   - It does
- Does this happen in OptiFine standalone? No, It doesn't.
- Does this happen in Vanilla without OptiFine?
- Have you tried using a binary search to find which mods cause this issue? **No, I'm not sure how to do that.**
   - To find conflicting mods, split your mods into 2 groups (not including OptiFine/OptiFabric, obviously). Remove one group, and test in-game. Keep the group that has the problem, and repeat until no more mods can be removed without the issue disappearing.
   - Does the issue still happen with only the remaining mods installed?
      - Forge/Fabric and remaining mods, without OptiFine

## Additional Information
Here goes any final remarks and everything else that might not fit in the previous sections.

**Comment by Jorkles** [comment]
Optifine does not show up in the mods list. Check video settings to make sure it’s installed, but the F3 screenshot already says it is.

**Comment by KaiAF** [comment]
Closing this, reason is above by Jorkles. If there is any other issue, let us know.
