### ISSUE TITLE
[Bug] Piston Delays

### ISSUE THREAD

**Issue by SmashPortal** [sp614x/optifine#5385]
## Description of Issue
Pistons are delayed and quasi-connected pistons are delayed further.

See `Prior Testing` section for recorded interactions in vanilla vs OptiFine.

## Steps to Reproduce
A) Use pistons. They're slower to activate compared to vanilla.
or
B) Normal power one piston and [quasi-power](https://minecraft.gamepedia.com/Tutorials/Quasi-connectivity) another. The quasi-powered one will activate later than the normal powered one.

## OptiFine Version
1.16.5-Optifine_HD_U_G7

## Installation Method
Installer.

## Log Files/Crash Reports
https://pastebin.com/TyKZNVdD

## F3 Debug Screenshot
![image](https://user-images.githubusercontent.com/15202464/109293852-6251f600-77fa-11eb-9f01-8e91f7b36794.png)

## Prior Testing
Vanilla:
https://youtu.be/J1QGuFXNZk4

OptiFine:
https://youtu.be/K2Z1XqHwwbQ

## Additional Information
I haven't tested this issue with other releases of OptiFine.

**Comment by KaiAF** [comment]
I went and tested it, enabling fast math for me seemed to make it happen less frequently? 

Even setting the chunk updates to 5 doesn't help.

**Comment by SmashPortal** [comment]
> I went and tested it, enabling fast math for me seemed to make it happen less frequently?
> 
> Even setting the chunk updates to 5 doesn't help.

Fast math is enabled in the video. It's one the of first things I turn on when I launch Minecraft with Optifine for the first time.

**Comment by IMS212** [comment]
Can you confirm this is not only visual? It's possible that the pistons are just getting updated slower on the client.

**Comment by Stereo528** [comment]
> 
> 
> Can you confirm this is not only visual? It's possible that the pistons are just getting updated slower on the client.

In the OptiFine video, you can see that even going at the same speed (walking) he walks slightly over the pistons and moves the camera up, and sprinting gets him stuck on the blocks. In the vanilla video, he does not walk over the pistons unless he is sprinting. I feel that's enough proof to show that it's not only visual.

**Comment by Cart3r1234** [comment]
When I upgraded to G7 I definitely noticed a delay on pistons as well, with some firing at different timings than others that used to fire at the same time previously.

**Comment by Stereo528** [comment]
I'm now wondering if this was related to #5348. if it was this might be fixed in the next update.

**Comment by Stereo528** [comment]
@SmashPortal Quick Question, does this happen without Lazy Chunk Loading enabled? (assuming you had it on in the first place)

**Comment by SmashPortal** [comment]
> @SmashPortal Quick Question, does this happen without Lazy Chunk Loading enabled? (assuming you had it on in the first place)

Disabling Lazy Chunk Loading immediately resolves the issue. It's like a toggle between broken and working.

**Comment by KaiAF** [comment]
If that's the issue, then this bug seems to be related to #5348 which is resolved and coming next preview.
