### ISSUE TITLE
Possible broken lighting? and Invisible Items

### ISSUE THREAD

**Issue by leepad6** [sp614x/optifine#5386]
## Description of Issue
Black blocks, Invisible items.

## Steps to Reproduce
Unknown.
(It only happened when i bumped up my allocated ram to 10GB)

## OptiFine Version
Self-explanatory. 

## Installation Method
Standalone Installer

## Other Installed Mods
None

## Log Files/Crash Reports
None

## F3 Debug Screenshot
Minecraft's built-in debug screen provides *a lot* of useful information, and should be included even if the issue is not something that can be captured in a still image.

To open this menu, simply press `F3` on your keyboard while in-game. Please ensure the text is easily readable. Depending on the size/resolution of your monitor, you may have to adjust your GUI scale for all text to be completely visible on-screen.

## Prior Testing
If you've installed standalone:
- Q : Does this happen in Vanilla without OptiFine? A : No

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
Yes it does, it happened with a mod called : Sodium
- Does this happen without any mods at all?
  No.
- Does this happen in OptiFine standalone? A : Yes
- Does this happen in Vanilla without OptiFine? A : No
   - Does the issue still happen with only the remaining mods installed?
      - Forge/Fabric and remaining mods, without OptiFine A : Only with mods.

**Comment by KaiAF** [comment]
Can you provide more details? You said "Self-explanatory." on the OF version, so I assume the latest version (G7).  
>

**Comment by KaiAF** [comment]
Closing as there has been no response from the author.
