### ISSUE TITLE
[MajorBug] epilepsy bug

### ISSUE THREAD

**Issue by kgkukik** [sp614x/optifine#5387]
### When im downloading optifine on forge im seeing this after ###
Also there's list of mods, and one of those are MAYBE the reason(100% not botania twilight forest and immersive engineric, im tried deleting them)
![2](https://user-images.githubusercontent.com/79718661/109341162-7130bb00-7883-11eb-9b87-42120f01ec37.png)
![1](https://user-images.githubusercontent.com/79718661/109341166-71c95180-7883-11eb-9ed5-760ea6c0bb91.png)
![whyoptifine](https://user-images.githubusercontent.com/79718661/109341598-1186df80-7884-11eb-8f22-c70bb3025b59.png)

**Comment by Stereo528** [comment]
What minecraft version?

**Comment by KaiAF** [comment]
Closing this as the author hasn't responded in 23 days. If you still have any issues, let me know.
