### ISSUE TITLE
Crashes (EXIT CODE 0, HD U G7)

### ISSUE THREAD

**Issue by ll4master** [sp614x/optifine#5389]
I start Minecraft with Optifine HD U G7 and it comes up with Game Crashed EXIT CODE 0. I installed this from OptiFine.net/home and I ran it with java but when I try to run it it always comes up with EXIT CODE 0. Please reply with this on how to fix.
![image_2021-02-27_151054](https://user-images.githubusercontent.com/74486341/109398979-fe205680-790d-11eb-8c64-9c2a158aaf30.png)

**Comment by Cart3r1234** [comment]
Turn off the beta version of the launcher, the beta launcher causes this crash

**Comment by KaiAF** [comment]
This bug was related to the Minecraft launcher and was fixed.
![image](https://user-images.githubusercontent.com/60985521/110012801-8758d400-7ce6-11eb-8445-7221bcc17cdb.png)
