### ISSUE TITLE
getting 0 fps with optifine in mods folder

### ISSUE THREAD

**Issue by typicalstrafes** [sp614x/optifine#539]
i get 0 fps when i have optifine in my mods folder when i try to join a server someone please help me

**Comment by sp614x** [comment]
Can you post the error log (game output)?

**Comment by sp614x** [comment]
You can try to delete "optionsof.txt" and "optionsshaders.txt".

**Comment by typicalstrafes** [comment]
i cant post the error log because it just drops to 0 fps and i have to force quit my minecraft

**Comment by sp614x** [comment]
The error log (game output) is visible in the launcher. 
It can be accessed even when the game is frozen or not responsive.

**Comment by sp614x** [comment]
Singleplayer or multiplayer?

**Comment by RovertS** [comment]
I'm having a similar issue, Minecraft is at a constant 1/0 fps and I'm unable to even force a crash report. I have to close the game with task manager each time I join a world or server

**Comment by sp614x** [comment]
If Smooth FPS causes problems then it looks like a driver bug.

**Comment by sp614x** [comment]
The Smooth FPS issue #583 is caused by Windows using wrong graphics card after Win10 update.
