### ISSUE TITLE
[Gui Scale] Make it so that the hotbar scale can be more customizable, instead of Small Medium Large and Auto.

### ISSUE THREAD

**Issue by AStrangePotato** [sp614x/optifine#5391]
## In Options> Video Settings> Gui Scale maybe have 1x 2x 3x -1x -2x -3x etc instead of small medium large
or maybe a slider for more precise scaling?
something along the lines of that because the default settings are either too large or too small

**Comment by KaiAF** [comment]
This could be related to #1560, #2684. Closing this as it's been suggested before.

**Comment by Lentern** [comment]
Considering you used the terms small medium and large, you probably play on 1.8. Try [this mod](https://youtu.be/pPnjWv6VXoU).
