### ISSUE TITLE
When ever I try to change or deactivate my optifine cape I keep getting this error: 

### ISSUE THREAD

**Issue by Clickzy123** [sp614x/optifine#5397]
**##** Description of Issue
When i try to change or deactivate my cape, it says that my cape was not found

![unknown (34)](https://user-images.githubusercontent.com/79926399/109673699-f4515a00-7b7e-11eb-910b-bacd7d2bd1d8.png)

**Comment by Clickzy123** [comment]
Please help me quick!

**Comment by KaiAF** [comment]
The developer has already been notified. I am going to close the ticket as I am fairly certain you contacted one of our support members already
