### ISSUE TITLE
stuck on the dirt screen but still in the server

### ISSUE THREAD

**Issue by vithp** [sp614x/optifine#5398]
https://user-images.githubusercontent.com/62474658/109720364-e234e300-7ba1-11eb-9deb-2e785dcaf079.mp4

when i join something like hypixel i get stuck on the screen with the dirt background it stays on the dirt screen and and i can hear noises from in game also my friends can see i am in the server and i know its optifine because it worked fine on my release 1.16.5 
and i even downloaded the G8 after thinking that it was optifine G7 was broken but G8 was still broken.

if you can help me then please do.

**Comment by KaiAF** [comment]
Do you have any shaders enabled, any resource packs? Are you able to send a latest.log?

**Comment by vithp** [comment]
i did put on chocapic13's low shaders because recently i reset my pc so needed to get my resoure packs and shaders back and thinking back the dirt screen started coming after a applied the shaders

**Comment by vithp** [comment]
i will see if turning off the shaders helps

**Comment by vithp** [comment]
it worked thanks
