### ISSUE TITLE
[Bug] Lightning Bolt Invisible

### ISSUE THREAD

**Issue by BlubberSealClubber** [sp614x/optifine#5399]
## Description of Issue
Please provide as much detail as possible.

## Steps to Reproduce
1. Spawn lightning in the world
2. Sound and fire spawns, but no bolt is seen

## OptiFine Version
1.15.2 OptiFine HD U G6

## Installation Method
Used the installer, and also extracted into .jar. Confirmed optifine was installed.

## Fabric/Forge Version
Installed in standalone

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
- **No, this works on Vanilla**

## Additional Information
Here goes any final remarks and everything else that might not fit in the previous sections.

**Comment by KaiAF** [comment]
Could be related to #5488. If not, let me know.
