### ISSUE TITLE
Optifine on same machine running DedicatedServer AND Client

### ISSUE THREAD

**Issue by Rumpelstiltskinny** [sp614x/optifine#54]
Server crashes when attempting to load Optifine from mods folder that the client ALSO uses

This setup is running a DedicatedServer **AND** a client from the SAME mods folder. NO, I do not wish to duplicate the mods folder (one for server and one for client) No, I cannot utilize a dedicated machine for the server install.

Your software SHOULD utilize checks to ONLY load if the instance is CLIENT.
[fml-server-3.log.txt](https://github.com/sp614x/optifine/files/192823/fml-server-3.log.txt)

**Comment by sp614x** [comment]
Fixed in preview B3 for 1.9.
OptiFine now skips the classloader injection when loaded in a Forge server
