### ISSUE TITLE
Shaders fail to parse block ID mappings when they contain unknown blocks

### ISSUE THREAD

**Issue by Builderb0y** [sp614x/optifine#540]
This makes it impossible to add official support for modded blocks because if I add

`block.31=minecraft:yellow_flower minecraft:red_flower botania:flower`

to block.properties, then anyone who isn't playing with botania installed will just get an error that says

>[OptiFine] Shaders: Block not found for name: botania:flower
[OptiFine] [Shaders] Invalid block ID mapping: block.31=minecraft:yellow_flower minecraft:red_flower botania:flower

and none of the vanilla blocks that I specify will be recognized either.

**Comment by sp614x** [comment]
Updated preview C2 for 1.11.2 
- fixed CTM, Custom Colors and Shaders block matching to better handle missing blocks
