### ISSUE TITLE
"Resource Reload Failed"

### ISSUE THREAD

**Issue by Holfrisky** [sp614x/optifine#5402]
I created a texture pack following the Minecraft Wiki's texture pack tutorial. After the mcmeta test, it worked perfectly fine. 
The resource pack was named Orilore and the mcmeta read: 
{
  "pack": {
    "pack_format": 6,
    "Description": "Orilore SMP Texture Pack"
  }
}
The pack was for 1.16.5, the current latest version. There are only two textures in the pack as of now, a retexture of the turtle helmet's model and the turtle helmet's icon. While testing each texture, whether separately or as a whole, it would load up and then load again with the error "Resource Reload Failed" on the top right. I've tried different variations of the pack, complete redoes, and retexturing the items to be more simple for testing purposes.
The zip is imported below. It is important for this texture pack to work out as it is crucial for a server I am partaking in.
[Orilore.zip](https://github.com/sp614x/optifine/files/6080216/Orilore.zip)

**Comment by Regnander** [comment]
What OptiFine version are you using?

**Comment by Holfrisky** [comment]
No mods, no Optifine. This is meant for a fabric server which is incompatible with Optifine so I have to test it without any mods or add ons.

**Comment by KaiAF** [comment]
> No mods, no Optifine.

You aren't using optifine? If not, then...? I am confused, sorry

**Comment by sp614x** [comment]
This issue tracker is only for OptiFine issues.
