### ISSUE TITLE
I make a big mistake with optifine donation.

### ISSUE THREAD

**Issue by Hekze** [sp614x/optifine#5405]
I made a big mistake, when donating I entered an email address that does not exist. Is there any way to get my money back or change my email address to the correct one? My nickname: HekzeToNieTy My incorrect email: kokscow@interia.com My correct email: kokscow@gmail.com. @sp614x

**Comment by KaiAF** [comment]
Okay, don't post your email here. But please email us at support@optifine.net regarding this issue

**Comment by JackDotJS** [comment]
edited to remove personal info

**Comment by Hekze** [comment]
Can I send what I wrote to this email or should I not include my emails there?
