### ISSUE TITLE
Optifine Cape doesn't work

### ISSUE THREAD

**Issue by OhSqubana** [sp614x/optifine#5406]
My cape is active but I can't see it.When I try to change my nick it shows a server error.The day before I changed my nick in mc after 24h optifine automatically transferred my nick to the new one.Now I can't even deactivate it.I have two capes on this e-mail, but only this one is not working.I tried to deactivate it on other browsers but nothing worked.Now I can't even buy a new cape on my account because I am writing that it is already active.

**Comment by KaiAF** [comment]
What is your Minecraft username?

**Comment by OhSqubana** [comment]
> What is your Minecraft username?

Now OhSqubana but before _SiMpMe_

**Comment by KaiAF** [comment]
Sorry for redirecting you after you just answered, but support request usually go through our support channel on discord, or our email. If you want, email us at optifinex@gmail.com. Thank you
