### ISSUE TITLE
Cape Editor Feature Request - Custom Colors on Banner Cape

### ISSUE THREAD

**Issue by AidanLCB** [sp614x/optifine#5407]
I think it would be a good idea (if possible) to let players use Hex codes to change the color of each layer in a banner. Right now I am using the OF design because banner colors don't work well with many skins including mine. 

I think the interface should have an "Advanced Options" dropdown menu so people can still easily just use a normal banner and there would probably be a "Reset Colors" button.

I am NOT saying that there should be an entire cape editor on the Optifine site, while this would be great I understand that it could be somewhat hard to do. Instead I'm just suggesting something like what shows when you select the "Custom" option but instead of having "top","bottom","text","shadow" it would have layers 1 - 8. It doesn't have to let you rearrange or change layers, just colors.

If this idea was implemented it would make it possible to make banner capes that look good with all skins which would be really great.

**Comment by KaiAF** [comment]
This, unfortunately, isn't possible at the moment, so I'm going to close it.
