### ISSUE TITLE
[Bug] Forge 1.15.2 Crash

### ISSUE THREAD

**Issue by BD103** [sp614x/optifine#5410]
## Description of Issue
Hello, I have found, after a bit of testing, that Optifine crashes Minecraft with Exit Code 0. After enabling the logs, I have found the error:

```
JRE version: Java(TM) SE Runtime Environment (8.0_25-b18) (build 1.8.0_25-b18)
Java VM: Java HotSpot(TM) Client VM (25.25-b02 mixed mode windows-x86 )
Problematic frame:
C  [ig4dev32.dll+0x3e88]

Failed to write core dump. Minidumps are not enabled by default on client versions of Windows

If you would like to submit a bug report, please visit:
  http://bugreport.sun.com/bugreport/crash.jsp
The crash happened outside of Java Virtual Machine in native code.
See problematic frame for where to report bug.
```

## Steps to Reproduce
1. Run Minecraft
2. Join a server (this doesn't seem to happen on single player)
3. Play around, and then after about 20 minutes it will crash

## OptiFine Version
Latest version of Optifine for 1.15 (it's a preview version, I believe)

## Installation Method
I put the jar into the mods folder.

## Fabric/Forge Version
Forge 31.2.49 for 1.15.2

## Other Installed Mods
- Biomes O'Plenty (10.0.0.366)
- Bookshelf (5.6.40)
- Clumps (5.0.2.6)
- CodeChickenLib (3.3.4.402)
- Dark Utilities (3.1.9)
- EnderMail (1.1.3)
- Ender Storage (2.5.1.160)
- Just Enough Resources (0.10.1.77)
- Kiwi (2.8.5)
- Serene Seasons (3.0.0.75)
- SlimyBoyos (2.0.1.2)
- Snow Real Magic (1.7.5)
- Storage Drawers (7.0.3)
- Waystones (6.0.2)
- Applied Energistics 2 (7.0.5)
- Backpacked (1.7.0)
- Corpse (1.0.10)
- Create Mod (0.3b)
- Immersive Portals (0.24)
- Just Enough Items (6.0.3.15)
- JourneyMap (5.7.0b3)
- Refined Storage (1.8.8)
- Xerca's Music Mod (3.0)

## Log Files/Crash Reports
Main log is pasted above, stating how it failed to write core dumps.

## Prior Testing
I do not believe this happens on Vanilla with standalone OptiFine, though I can confirm that it has happened to others playing on the same server. (I believe it is Windows only, but that may be wrong.)

I have not had the chance to test with individual mods yet, so it may be one of those messing up Optifine.

This does not happen in Vanilla without Optifine.

## Additional Information
Like I said, this seems to be Windows only. I did some of the following already:

- Restart computer
- Update OS
- Update Java
- Redownload Optifine JAR file
- Update / change graphics driver
- Allocate more RAM
- Changing a bunch of graphics settings in Minecraft

Currently the only fix is removing Optifine.

Thanks for helping.
~BD103

**Comment by sp614x** [comment]
The crash is in the graphics driver:
```
Problematic frame:
C  [ig4dev32.dll+0x3e88]
```
You can try to reset the video settings: Options -> Video Settings -> Other -> Reset Video Settings
