### ISSUE TITLE
I need help.

### ISSUE THREAD

**Issue by Hekze** [sp614x/optifine#5411]
If I buy a donation to the same nickname for the second time, it will all work?

**Comment by KaiAF** [comment]
If there is a cape linked to it already, the second donation would turn into some sort of "credit". You can log in and activate the cape on another user if you'd like. But it would not overwrite the current cape that is linked to the account. 

Also, please do not come here for support. This is usually for bug reports / Suggestions. Go to our Discord server's support channel, or email us at optifinex@gmail.com instead :)

**Comment by Hekze** [comment]
I sent an email to this address. Thank you for your help.
