### ISSUE TITLE
[Shaders] [1.16.5 G7] Shadow pass not disabled if not used

### ISSUE THREAD

**Issue by fayer3** [sp614x/optifine#5412]
## Description of Issue
if a shadow shader is included in a shaderpack, it is always executed, even if not used.
if the shadow shader is not included it gets disabled correctly.

## Steps to Reproduce
1. load the shaderpack 'shader_with_shadow_shader.zip'
2. enable/disable 'SHADOWS' in the shaders settings, the framerate doesn't change
3. load the shaderpack 'shader_without_shadow_shader.zip'
4. enable/disable 'SHADOWS' in the shaders settings, the framerate increases significantly when disabling shadows

## OptiFine Version
1.16.5 G7
didn't happen with 1.16.5 G6

## Installation Method
standalone installer

## F3 Debug Screenshot
with shadow shader, SHADOWS enabled:
![2021-03-05_17 13 50](https://user-images.githubusercontent.com/8282299/110142370-61126180-7dd6-11eb-918a-07ef1ac9e0aa.png)
with shadow shader, SHADOWS disabled:
![2021-03-05_17 13 58](https://user-images.githubusercontent.com/8282299/110142404-6bccf680-7dd6-11eb-96c1-b645bf711ecc.png)

without shadow shader, SHADOWS enabled:
![2021-03-05_17 14 11](https://user-images.githubusercontent.com/8282299/110142450-77202200-7dd6-11eb-8ef8-ecd15a681c08.png)
without shadow shader, SHADOWS disabled:
![2021-03-05_17 14 19](https://user-images.githubusercontent.com/8282299/110142476-7e473000-7dd6-11eb-8f0c-4697895c6b6b.png)

## Additional Information
shaders used for testing:
[shader_with_shadow_shader.zip](https://github.com/sp614x/optifine/files/6091741/shader_with_shadow_shader.zip)
[shader_without_shadow_shader.zip](https://github.com/sp614x/optifine/files/6091742/shader_without_shadow_shader.zip)

**Comment by sp614x** [comment]
If the shadow shaders are included then the shadow program will be used.
Disabling the "#define SHADOWS" doesn't make the shadow shader disappear.

To disable a program use:
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.properties#L469
or
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.properties#L227
