### ISSUE TITLE
[Bug] The optifine cape is not working.

### ISSUE THREAD

**Issue by Hekze** [sp614x/optifine#5415]
My optifine version: 1.16.5-Optifine_HD_U_G7. Optifine cape is not working for me. I have it unlocked, restarted minecraft, did a reload, pressed the cape button to off and on, and it still doesn't work. Can anyone help me

**Comment by Hekze** [comment]
Pls help

**Comment by KaiAF** [comment]
Make sure both these settings are enabled. Skin Customization > Cape: ON & Video Settings > Details > Show Capes: ON.

**Comment by Hekze** [comment]
it's all on @KaiAF

**Comment by Hekze** [comment]
yes i checked a few more times and everything is on

**Comment by Hekze** [comment]
@KaiAF it still doesn't work

**Comment by KaiAF** [comment]
yeah sorry. For general support like this it's best to either email us at "optifinex@gmail.com" or in our support channel on discord. "optifine.net/discord"
