### ISSUE TITLE
[Feature Suggestion] Less Loading Screens

### ISSUE THREAD

**Issue by Veggieoskibroski** [sp614x/optifine#5423]
If you'd like to change certain video settings that affect the renderer (like the Mipmap types), there is a loading screen that appears when you click anywhere on the adjustment bar.
I'd like it if I was able to do change this without a loading screen appearing right when I click on the adjustment bar, but rather when I click "Done" on that page.
This makes it easier to change it by simply sliding it and easily figuring out which setting you want to use, instead of guessing where in the bar that the setting you want to use is found, then waiting for the loading screen, until you found out that where you clicked didn't get the one you wanted. It's a quality-of-life update that I would VERY MUCH appreciate.

**Comment by sp614x** [comment]
Fixed the dragging of option sliders, coming in next preview.
Reloading the resources when the button Done is pressed is currently not possible as there are internal dependencies that need the resources to be reloaded when some options are changed.
