### ISSUE TITLE
Optifine not working with forge 1.8.9

### ISSUE THREAD

**Issue by wwweeeiiirrrddd000** [sp614x/optifine#5426]
Whenever I put optifine in the mods folder, forge crashes either while loading, or after I join a world. I tried with the latest release for forge and the recommended version. 
The other mods that I use are here:
![image](https://user-images.githubusercontent.com/64565319/110399560-ff414880-80b0-11eb-9e21-8b2017ac1c5d.png)

**Comment by Regnander** [comment]
Does this crash generate any error log that you can post?

**Comment by karmette** [comment]
This isn't an Optifine Issue, but I know how to fix this. First, make sure you're using the latest version of optifine. next, join https://discord.gg/moulberry and get the latest pre-release in #neu-prereleases. I also dont recommend Oranges Simple mods as it is outdated and can cause many problems. 
Here are some replacements to this mod:
https://www.youtube.com/watch?v=lfwrIUWI10s - directionhud
https://download.powns.dev/potionhud189 - potion hud
https://download.powns.dev/togglesneak189 - togglesneak/sprint
https://download.powns.dev/armorhud189 - armorhud

also, make sure you're using the LATEST version/prerelease of every mod on here. it seems sba and scrollable tooltips are already up-to-date, so make sure you update DSM and whatever ctjs is. if these solutions dont work and it crashes, navigate to .minecraft/logs/latest.log, and open it. Press ctrl+a, and copy it, then paste it to https://hastebin.com/ or https://pastebin.com/ and save the paste, then link it here.

**Comment by KaiAF** [comment]
Did you try what was stated above? Did it help?
