### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by gvbrielle** [sp614x/optifine#5427]
Hi so I'm trying to download a mod and it needs opti fine to run, I have it downloaded and in my mods folder, but now what?  It doesn't show up when I'm selecting a game mode like its supposed to, so now I'm confused.  Thanks!

**Comment by sp614x** [comment]
You can install OptiFine with Forge by placing the OptiFine JAR file in the mods folder. 
If not working, please check if the Forge version matches the one supported by OptiFine.

You can also install OptiFine standalone (no Forge) by double-clicking the OptiFine JAR file and clicking Install.
