### ISSUE TITLE
Crash when join game/server

### ISSUE THREAD

**Issue by slossgaming** [sp614x/optifine#543]
When I join a server after about 2 - 5 seconds I start lagging then go away to 0 fps. I have tried increasing the ram, and more things nothings working. I believe it's something in optifine, as it does not do it in the normal version of Minecraft< Vanilla.
V7
V6
V5,
Please fix ASAP, I want to get things finished.

**Comment by sp614x** [comment]
More details needed.
Running with Forge or standalone?
Which other mods are installed?
Error log (game output)?

**Comment by slossgaming** [comment]
No forge.
No mods.
It says **NOTHING** about Optifine in the error log

**Comment by sp614x** [comment]
Video Settings -> Performance -> Smooth FPS -> OFF ?
Can you post the game output or the error log?

**Comment by OGChriss** [comment]
hey, this might work.
