### ISSUE TITLE
[Bug] Fabulous graphic bug

### ISSUE THREAD

**Issue by Grufoony** [sp614x/optifine#5431]
## Description of Issue
Let's suppose you use antialising with optifine, with a value > 0. If you use another installation of minecraft (example: snapshots) turning on fabulous graphic, then you come back to optifine you will notice you have antialiasing > 0 (as before) and fabulous graphic turned on, so your game will start with black screen and you have to close the game with alt+f4 and re-open it to change settings.

## Steps to Reproduce
1. Open minecraft with optifine and set antialiasing > 0
2. Close minecraft
3. Open another version of minecraft (without optifine) and turn on fabulous graphics
4. Close minecraft
5. Re-open minecraft with optifine and enter any world -> your screen will be black

## OptiFine Version
1.16.5 HD U G6 - G7

**Comment by KaiAF** [comment]
I am able to reproduce this.

**Comment by Grufoony** [comment]
UPDATE

Cannot replicate it in OptiFine HD U I3, I think is due to a minecraft's update.
However, I don't know from which version this bug does not appear.
