### ISSUE TITLE
[Bug] Optifine crashes with new launcher when using Java 15.0.2.7 (AdoptOpenJDK)[Category] Short description

### ISSUE THREAD

**Issue by CloudeLecaw** [sp614x/optifine#5432]
Well the threas sais it.. with vanilla it runs but since the new launcher is there Optifine crashes when Java OpenJDK 15.0.2.7 is used

I hope optfine can fix this issue, it was working fine before too... (im using J15 since a long time now...)
Vanilla clients works with the Java 15.0.2.7

The Problem accours with all newer versions of Jaba and the new launcher  Java 8_281 15.0.1,  and 11+
With the Minecraft installed one 1.8.0_51 it works... why ever...

Currently it just help to disable the optional java and take the java8 that is devlivert with minecraft.

I hope this can be fixed soon :)

Note - Optifine is NOT Farbic i know they have their beta allready---

------------------------------------------------------------------------------------

I opened a new ticket because a supporter called sp614x closed this after he found a beta for farbic that has nothing to do with optifine.. 
I am not using farbic. i was JUST testing it because the first answer of my thread asked me if farbic and forge work nothing else.
but ok. problem still accour and thanks sp614x for closing an unsloved ticket because a problem is sloved that other users have with other midifications (not optifine).. 

well what ever.. i ohpe a fix Pre4 can be made soon :)

Old original - cllosed by sp614x for found out that farbic is fixed.. (lol same about u didnt noticed this is an optifine ticket not a farbic one..sorry man..@.@)  https://github.com/sp614x/optifine/issues/5428

So my only change was to open a new ticket and post aggain

-------------------------------------------------------------------------------------

**Comment by HiItsDevin** [comment]
Duplicate  #5428, please close

**Comment by CloudeLecaw** [comment]
NO DUPLICATE the mid closed a Optifine ticket because farbic has a new veison

**Comment by HiItsDevin** [comment]
It is a duplicate because Mojang already fixed this in their new launcher beta as I said.

**Comment by Cart3r1234** [comment]
> NO DUPLICATE the mod closed a Optifine ticket because farbic has a new veison
> 
> You see whats wrong here? correct the desission of this mod/supporter or what ever he is to close an optifine ticket just because farbic found his beta solution that has nothing to do with optifine
> So problem is still there and ticket not closes. i close this ticket when the other one may reopens

Not all issues need a new optifine preview to fix.  This is an issue with the launcher, therefore it doesn't need a new preview.

**Comment by CloudeLecaw** [comment]
do its fixed?--ok

**Comment by HiItsDevin** [comment]
Yes, if you read what I said, you would've known. In the future, do not create duplicate reports and please actually read what others have said to help. Thank you.

**Comment by Cart3r1234** [comment]
> do its fixed?--ok

You were told at least twice it was fixed

**Comment by HiItsDevin** [comment]
For the record, sp614x create optifine. He's not a random.

**Comment by ZenIsBestWolf** [comment]
nothing useful, locking
