### ISSUE TITLE
WTAF

### ISSUE THREAD

**Issue by ZoruaBit** [sp614x/optifine#5434]
with the latest 2 preview shaders this happens with ray traced shaders and forge. (atleast on amd idk about nividia or other)
![image](https://user-images.githubusercontent.com/39221658/110755869-1007d080-820f-11eb-9a8f-c2e4ac553995.png)

this was made with the molly VX raytraced shader on Pre 4 and Pre 3 when using forge 36.0.42 note no mods are used

**Comment by BentoGambin** [comment]
Happens with many models overlays in modded blocks as-well

**Comment by sp614x** [comment]
Looks very similar to #5448
