### ISSUE TITLE
rendering error, causes the game to close

### ISSUE THREAD

**Issue by harmalom** [sp614x/optifine#5439]
I happened to stand in front of a spawner of skeletons.

Crash Report
  https://pastebin.com/bhTQKpCW

log
https://pastebin.com/g8aFyftz

 Installation Method
 OptiFine  drop the JAR file into mods folder 

 OptiFine Version
preview_OptiFine_1.16.5_HD_U_G8_pre5

Forge Version
forge-1.16.5-36.0.46

**Comment by KaiAF** [comment]
Are you using any other mods? I tested it, and it is not reproducible.

**Comment by harmalom** [comment]
Mod List
https://pastebin.com/TatypQRJ

**Comment by harmalom** [comment]
in the latest versions of OptiFine this happens as well.

some images
![2021-03-20_13 30 23](https://user-images.githubusercontent.com/67077986/111882060-71534080-8981-11eb-8b21-44543485592f.png)
![2021-03-20_13 30 32](https://user-images.githubusercontent.com/67077986/111882064-757f5e00-8981-11eb-9163-ea23a67d0513.png)
![2021-03-20_13 31 03](https://user-images.githubusercontent.com/67077986/111882067-787a4e80-8981-11eb-92fb-0f9e13b3c8e4.png)
![2021-03-20_13 32 06](https://user-images.githubusercontent.com/67077986/111882069-7c0dd580-8981-11eb-82ea-7d904d077562.png)
![2021-03-20_13 35 02](https://user-images.githubusercontent.com/67077986/111882070-7e702f80-8981-11eb-8b29-d76eab2a35f1.png)

Optifine Version
preview_OptiFine_1.16.5_HD_U_G8_pre8

Forge Version
1.16.5 - 36.1.0

Resources Pack
ComplementaryResources 3.12

**Comment by sp614x** [comment]
The broken Molten Stone with shaders is a bug in Subterranean Wilderness #5448.

**Comment by harmalom** [comment]
That's strange, because even with the OptiFine HD U G6 version, it worked very well with Subterranean Wilderness, no error occurred, and it also happens with Forbidden and Arcanus, as you can see in one of the images, and it's exactly the same error, but Ok, no problem.

**Comment by KaiAF** [comment]
Are you still having any issues? From the github issue sp mentioned, it says that it should have been fixed.

**Comment by KaiAF** [comment]
Closing as I assume this has been fixed.
