### ISSUE TITLE
Weird Download

### ISSUE THREAD

**Issue by Nolqn** [sp614x/optifine#544]
Every time I download Optifine, it just downloads a shortcut to internet explorer, and it says If i want to run it or save it, then whenever I press save, it just redownloads the exact same shortcut. I have java so I dont know why this is happening. I am also using Chrome.

**Comment by sp614x** [comment]
You should install Java, then double click on the downloaded file should work.
You can also use right-click, "Run with..." and select Java, or similar depending on your OS.
