### ISSUE TITLE
[Feature Request] Add support for the 'GL_EXT_geometry_shader4' extension to fix Geometry Shaders on M1

### ISSUE THREAD

**Issue by IsaacMarovitz** [sp614x/optifine#5442]
The current geometry shader extension `GL_ARB_geometry_shader4` is not supported on M1 Macs, which breaks support for geometry shaders. Adding support for the `GL_EXT_geometry_shader4` extension should allow them to work again.

[Docs](https://www.khronos.org/registry/OpenGL/extensions/EXT/EXT_geometry_shader4.txt)

**Comment by sp614x** [comment]
Added support for GL_EXT_geometry_shader4 in pre6.
