### ISSUE TITLE
[Category] Shaders don't render items correctly in JEI and FTBQuests

### ISSUE THREAD

**Issue by jinkhya** [sp614x/optifine#5443]
## Description of Issue
With any kind of shaders, JEI has some reversed lighting on items/blocks
With shaders : https://i.imgur.com/sXuo3VV.png
Without shaders : https://i.imgur.com/9POxi2z.png

## Steps to Reproduce
1. Install Optifine, any kind of shaders and JEI
2. open inventory to look at items/blocks in JEI

## OptiFine Version
preview_OptiFine_1.16.5_HD_U_G8_pre5

## Installation Method
optifine jar in mods folder

## Fabric/Forge Version
36.0.45

## Other Installed Mods
JEI

## F3 Debug Screenshot
https://i.imgur.com/vTMFajT.png

**Comment by sp614x** [comment]
The normal GUI items are lit correctly, it should be something on the JEI side:

![image](https://user-images.githubusercontent.com/16635441/111180508-62e5dd00-85ad-11eb-8d5b-e0fdffeecfdb.png)
