### ISSUE TITLE
[Rendering] Lines Rendering around player

### ISSUE THREAD

**Issue by CodingCodre** [sp614x/optifine#5444]
## Description of Issue
When using Optifine, I get lines outlining the player, and in 1.8.9, the text is messed up, with lines above the O's. I have already updated my graphics drivers. This started happening after I used an external monitor from my laptop.

## Steps to Reproduce
1. I installed Optifine
2. Used a monitor (1920 x 1200 res)

## OptiFine Version
All Versions

## Installation Method
I installed using the installer from optifine.net

## Fabric/Forge Version
I used lunar client with 1.8.9

## Other Installed Mods
Any other mods lunar client has

## Prior Testing
Yes

## Additional Information
I believe that it has something to do with the resolution.
![2021-03-07_11 09 18](https://user-images.githubusercontent.com/70117286/111077385-d1437600-84ad-11eb-8c05-1b3ba0e58710.png)
![2021-03-07_11 27 20](https://user-images.githubusercontent.com/70117286/111077387-d1dc0c80-84ad-11eb-809a-70e6163739ac.png)
![2021-03-07_11 39 37](https://user-images.githubusercontent.com/70117286/111077390-d274a300-84ad-11eb-9f92-a9a68ae75722.png)
![2021-03-14_09 32 50](https://user-images.githubusercontent.com/70117286/111077391-d30d3980-84ad-11eb-8778-14b8a7050569.png)
![2021-03-14_10 03 48](https://user-images.githubusercontent.com/70117286/111077393-d30d3980-84ad-11eb-9dc0-f45782f95573.png)

**Comment by sp614x** [comment]
Very thin lines around the player may be visible when antialiasing is enabled.
Currently this can't be fixed.
