### ISSUE TITLE
[Category] Cape Problems

### ISSUE THREAD

**Issue by GJungle1** [sp614x/optifine#5447]
## Description of Issue

When Im on a certain server my cape in not connected to my body, on the other servers its fine.
## Steps to Reproduce
1. Join the server
2. click F5?
3.And voila. Bug.

## OptiFine Version
1.16.4 HD U G7

## Installation Method
Lunar Client(It has nothing to do with it, I tested on the normal client. Opened .jar file and installed it that way.)

## F3 Debug Screenshot

https://i.imgur.com/sGCaAjL.jpg

**Comment by GJungle1** [comment]
![image](https://user-images.githubusercontent.com/54341728/111220691-be58a080-8596-11eb-8a91-ac99dbf39b88.png)

**Comment by Cart3r1234** [comment]
if I'm not mistaken, this is an issue with certain clients that have their own capes; try it on the vanilla client and see if it still happens

**Comment by GJungle1** [comment]
> if I'm not mistaken, this is an issue with certain clients that have their own capes; try it on the vanilla client and see if it still happens

if you'd reread the thread info, I mentioned that In a normal client everything is the same.

**Comment by sp614x** [comment]
Can you reproduce it with OptiFine only (no Lunar, no Forge, no other mods)?
The screenshot above doesn't look like vanilla at all.

**Comment by GJungle1** [comment]
> Can you reproduce it with OptiFine only (no Lunar, no Forge, no other mods)?
> The screenshot above doesn't look like vanilla at all.
The problem was the texture pack for some reason It completely mess up capes for some reason. Im so sorry to bother you. Have a good day.

**Comment by KaiAF** [comment]
In the image, it looks like there are custom models for armor. That could have been the cause, most likely.

**Comment by GJungle1** [comment]
> In the image, it looks like there are custom models for armor. That could have been the cause, most likely.

Yes, so sorry to bother thanks for the help!!!
