### ISSUE TITLE
[Bug] Subterranean Wilderness mod texture glitch with Complementary Shaders

### ISSUE THREAD

**Issue by arBorghi** [sp614x/optifine#5448]
## Description of Issue
Just a texture glitch while using, at least, this shaderpack. If the shader is disabled it's rendered correctly.

## Steps to Reproduce
1. Install Subterranean Wilderness mod ( https://www.curseforge.com/minecraft/mc-mods/subterranean-wilderness ) and Complementary Shader ( https://www.curseforge.com/minecraft/customization/complementary-shaders )
2. Activate the shaders. 
3. Place a Molten Stone block

## OptiFine Version
G8 Pre6 for Minecraft 1.16.5

## Installation Method
Downloaded from optifine.net and placed in "mods" folder. 

## Fabric/Forge Version
Forge 36.0.46

##Screenshot
![Subterranean Wilderness texture bug](https://user-images.githubusercontent.com/63486777/111235826-3c856900-85d0-11eb-9afa-0bd6b9732337.png)

**Comment by sp614x** [comment]
The Subterranean-Wilderness BrightnessBakedModel is writing at fixed offsets in the vertex data.
https://github.com/Melonslise/Subterranean-Wilderness/blob/master/src/main/java/melonslise/subwild/client/model/BrightnessBakedModel.java#L47

The shaders use extended vertex format with larger size. 
The correct way to manipulate the vertex data is to calculate the step from the vertex data size:
```
    int step = vertexData.length / 4;
    vertexData[6] = 0x00F000F0;
    vertexData[6 + step] = 0x00F000F0;
    vertexData[6 + 2 * step] = 0x00F000F0;
    vertexData[6 + 3 * step] = 0x00F000F0;
```

**Comment by BentoGambin** [comment]
Can confirm the issue. Also the same happens with some Refined storage's blocks.

**Comment by sp614x** [comment]
The bug has to be fixed in Subterranean-Wilderness.

**Comment by PaintNinja** [comment]
Fixed in https://github.com/Melonslise/Subterranean-Wilderness/commit/f1281ea3759c2830c2ef851760132f2efd488597#diff-b03ae71172b632a9a97b2f9da052ffcd2c8a44750644608ece0678571c5d5608 , the fix will be included in the next update of SubWild.
