### ISSUE TITLE
Optifine deletes other keybinds

### ISSUE THREAD

**Issue by DalekCraft2** [sp614x/optifine#5453]
## Description of Issue

If an OptiFine keybind shares a key with another keybind, even if the other keybind involves two keys, the other keybind will have the shared key removed upon restarting the game. The key will become the default if it has been changed.

E.G. Zoom and Save Hotbar are both C. Upon reloading, it will have no keybind, because C is the default. If one changes the keybind of Save Hotbar to CTRL+C, the keybind will be displayed as "CTRL + " in the controls menu.

## Steps to Reproduce
1. Have a keybind share a key with an OptiFine keybind
2. Restart the game
3. The keybind for the non-OptiFine key has either been reset if it was changed before, or has been unbound if it was already default

## OptiFine Version

1.16.5 HD U G7

## Installation Method

OptiFine is in the mods folder.

## Fabric/Forge Version

Forge.

## Other Installed Mods

I am lazy. Here:
[mods.zip](https://github.com/sp614x/optifine/files/6158220/mods.zip)

## Log Files/Crash Reports

[debug.log](https://github.com/sp614x/optifine/files/6158228/debug.log)

## F3 Debug Screenshot

![2021-03-17_13 11 21](https://user-images.githubusercontent.com/50336832/111508723-68b0ff00-8722-11eb-8634-7157fdd79cb2.png)

## Prior Testing

The issue happens with no other mods.
The issue does not happen with no mods.
The issue happens in OptiFine standalone.
The issue does not happen in Vanilla.
The issue does not happen if OptiFine is removed from the mods folder, so it is definitely the cause.

## Additional Information

If this is intended to happen, it would be convenient to have an option to disable it. It is currently limiting my controls.

**Comment by KaiAF** [comment]
Normally you aren't able to set a keybind that is "CTR + C". If I press Left control it will only set it as Left control. Other mods allow you to set a "Double key" keybind. Could be caused by whatever mod doing that?

If there is an existing keybind for Save Hotbar and the keybind is "c" it will be changed to blank. This is due to the zoom key.

**Comment by DalekCraft2** [comment]
The double-keybind feature I believe is from Forge.

It is also annoying to have OptiFine constantly changing my keybinds. I would prefer to deal with conflicts myself.

**Comment by KaiAF** [comment]
I could reproduce this. Going to mark this as a bug as I don't think this was intentional. Simple fix - Use another keybind. I guess wait until sp614x fixes this (If it wasn't intentional).

**Comment by Xetaxheb** [comment]
Still an issue and has been for a fair bit... any other keybind vanilla or not that optifine decides is in its way is just removed for no reason on booting up the game. Rebinding the missing key works fine until next restart.

**Comment by sp614x** [comment]
Fixed, coming in next preview.
