### ISSUE TITLE
Optifine + Shaders = Dark Items in Jei/FTB Quests

### ISSUE THREAD

**Issue by CrimsonFluff** [sp614x/optifine#5458]
## Description of Issue
When using Optifine and Silders Shaders all item are incredibly dark. Happens in JEI, FTB Quests
Im not sure if this is an Optifine issue or not, but the mod authors are most likely to say it is...
Sildurs Vibrant Shaders v1.283 Extreme-VL (from their website)

## Steps to Reproduce
1. Load Minecraft with Optifine, Silders Shaders, FTB Quests and JEI
2. Open JEI or FTB Quests

## OptiFine Version
preview_OptiFine_1.16.5_HD_U_G8_pre8

## Installation Method
Drop into Mods folder

## Fabric/Forge Version
Forge 36.0.58

## Log Files/Crash Reports
No Crash

## F3 Debug Screenshot
https://imgur.com/a/pGKDn6p   <- screenshots of the problem and debug info

## Prior Testing
Tried just Forge, JEI, Optifine and Sildurs Shaders, problem still happens

**Comment by Therandus93** [comment]
I get this issue on all shader packs. It doesnt darken every item though. Im on the latest forge version 36.1.31. Happens on earlier forge version too and any shaders, so i think it might be an optifine issue. I have not yet tried the G6 or G7 version for 1.16.5 and if it still persists.

**Comment by MeinKraft** [comment]
to be honest, it happens with item models without Optifine in a Dev environment, so its probably forge. for me anyways

**Comment by Kqmu** [comment]
I had a few of these rendering issues with just Optifine, and the mods, in 1.16.5 and especially with Tinkers Construct Tools it shows the untextured purple and black cubes, but once you download Optiforge and run it with shaders it works 100%
https://www.curseforge.com/minecraft/mc-mods/optiforge

**Comment by Therandus93** [comment]
oh yeah i forgot to mention, parts of certain items, especially modded fences, has purple and black parts to them, but when you place them in the world, they are fine, its just in JEI. Honestly that part doesnt bother me, only the dark icons, as it makes it really hard to see the difference between ingots, or things are simular colour.

**Comment by quentinrossetti** [comment]
Hi,
I got the same bug on MC 1.16.5, Forge 36.2.1, Optifine HD U G8.
On Optifine HD U G7 all is working as expected.
![2021-11-09_22 18 09](https://user-images.githubusercontent.com/805805/141006323-efec69b5-1848-4c0a-b9ed-44a0d929bc34.png)

**Comment by DTM96** [comment]
Hi, 
I've got the same bug as well, I tried Optiforge with Optifine HD U G8 but that does not fix anything.
I can confirm that Optifine HD U G7 does indeed not have this issue as the person above noted.
