### ISSUE TITLE
My Thing wont work 

### ISSUE THREAD

**Issue by Rectiscool5** [sp614x/optifine#5459]
## Steps to Reproduce
1. What do you do...
2. ...to find this bug?

## Additional Information

Ok so my optifine loads and everything fine but when I join a server or load a world the screen is blurry and the guis overlap such as my inventory chests and the esc menu

**Comment by KaiAF** [comment]
Can you send a F3 menu screenshot? Please give us more information.

**Comment by KaiAF** [comment]
Closing this as there hasn't been any new information. If you are still having any issues, let me know.
