### ISSUE TITLE
Invisible Entities

### ISSUE THREAD

**Issue by ExoticPlayzz** [sp614x/optifine#5461]
## Description of Issue

Blocks/items that are destroyed or dropped are invisible (I noticed it only with a few different items). I would mine some iron ore but occasionally, I would break the iron ore block and nothing would drop (was mined with a diamond pickaxe). I noticed that happen a few times so I made sure to keep an eye on my count of iron ore in my inventory. After mining a few iron blocks, I saw that nothing dropped but the count of iron ore in my inventory went up. I also noticed this while trading with Piglins in the Nether. When I drop the gold ingot, my arm does the drop animation and it looks like nothing is dropped. But then the Piglin runs over to what seems like nothing and picks up the invisible gold ingot. (Both of these happened in a Hardcore world).
## Steps to Reproduce
1. Mine any blocks
2. Drop anything out of your inventory

## OptiFine Version

HD U G7 for 1.16.5
## Installation Method

I used the standalone installer

## F3 Debug Screenshot

![2021-03-20_11 28 06](https://user-images.githubusercontent.com/81033529/111877064-7ad3ad00-896f-11eb-9d46-a82feab69b5c.png)
## Prior Testing

This does not happen in Vanilla and I have no mods, no Fabric, and no Forge installed. This only happens in Optifine. 
## Additional Information

This only happens every once in a while. I also tried this with cooked porkchops and it happened only once out of the 29 that I dropped (Hence why there's cooked porkchops in my hand in the screenshot).

**Comment by Cart3r1234** [comment]
#5349
