### ISSUE TITLE
G7 and  G8_pre8 Causing Minecraft Launcher crash exist code 1

### ISSUE THREAD

**Issue by Toddah777** [sp614x/optifine#5465]
## Description of Issue
G7 and  G8_pre8 Causing Minecraft Launcher crash exist code 1 when trying to call Minecraft 1.16.5-forge-36.1.0
Crash occurs before Minecraft is called by the Launcher

## Steps to Reproduce
1. Launching Minecraft Forge 1.16.5-forge-36.1.0
2. Crashes before calling Minecraft

## OptiFine Version
Optifine_1.16.5_HD_U_G7.jar
preview_Optifine_1.16.5_HD_U_G8_pre8.jar

## Installation Method
Mod drop

## Fabric/Forge Version
1.16.5-forge-36.1.0

## Other Installed Mods
https://pastebin.com/iB6RHrXS

## Log Files/Crash Reports
https://pastebin.com/c69jH37E

Please Note: Both versions of the Optifine *.jar produce the same errors

## F3 Debug Screenshot
Occurs before Launcher calls Minecraft

## Prior Testing
Does this happen without other mods installed? N/A - Crash occurs before Launcher calls Minecraft

**Comment by Toddah777** [comment]
::Face Palm::
Just noted my forge is a version above what the two *.jars are for.
Will try against the recommended Forge version

**Comment by KaiAF** [comment]
I assume updating the forge version solved it? If not, let me know.
