### ISSUE TITLE
[Bug] The game crashed while tesselating the world when disable shaders - IndigoRenderer

### ISSUE THREAD

**Issue by NaiNonTH** [sp614x/optifine#5466]
## Description of Issue
Almost every time I disable the shader while the chunks are loading, The game crashed.

## Steps to Reproduce
1. Enable the shader (I used Chocapic13's V9 shader)
2. ...then disable the shader before chunks are completely generated, or when you disable the shader, Chunks regenerated. And you will see that the game crashed and show the error reason.

## OptiFine Version
1.16.5 OptiFine HD U G8 pre8

## Installation Method
Drop the JAR file into the mod folder. I was using fabric.

## Fabric/Forge Version
Fabric 0.11.1 - 1.16.5

## OptiFabric Version
OptiFabric 1.9.6

## Other Installed Mods
- Better Biome Blend - 1.1.1
- Better Dropped items - 1.2.4
- Better F3 - 1.1.2
- Bobby - 1.1.0
- Chat heads - 0.2.2
- Cloth Config - 4.11.15
- Cull Leaves - 2.1.0
- Damage Tilt - 0.1.1
- Dynamic FPS - 2.0.1
- Enhanced Block Entities - 0.1
- Entity Culling - 1.0.4
- Fabric API - 0.32.0
- Falling Leaves - 1.5.0
- First Person Mod - 2.0.0
- Item Model fix - 1.0.0
- ModMenu - 1.16.8
- Not Enough Animations - 1.2.0
- Phosphor 0.7.0+build.10
- Pling - 1.3.0
- Presence Footsteps - r29
- TRansliterationLib - 1.0.3
- Ugly Scoreboard Fix - 2.1.2

## Log Files/Crash Reports
- https://pastebin.com/FFd4gj3Y

## Prior Testing
If you've installed using Forge/Fabric:

- Does this happen without other mods installed? 
   _Ans._ Not sure.

- Does this happen without any mods at all?
   _Ans._ Not sure.

- Does this happen in OptiFine standalone?
   _Ans._ No.

- Does this happen in Vanilla without OptiFine?
   _Ans._ No.

- Have you tried using a binary search to find which mods cause this issue?
   _Ans._ Mmmm...I don't think that is the source of this problem, So no.

   - Does the issue still happen with only the remaining mods installed?
   _Ans._ No.

**Comment by sp614x** [comment]
Can you reproduce it with Forge and OptiFine, but no other mods?
