### ISSUE TITLE
[1.16.5]  OptiFine_HD_U_G7- CTM 0-46 doesn`t work correctly

### ISSUE THREAD

**Issue by Norzeteus** [sp614x/optifine#5467]
I have a lot of CTM_Blocks in my ressourcepack but with the 1.16 vers. and up they will not work correctly.
"T" and"+" blocks are not showing up correct.
I´m using  OptiFine_HD_U_G7 in vers.  1.16.5
 OptiFine is installed as standalone, no other mods are used

![CTM-Issue 0-46](https://user-images.githubusercontent.com/24456750/111910335-3fb1a680-8a61-11eb-86c9-627fd2b51eff.png)

**Comment by sp614x** [comment]
What are these blocks?

**Comment by Norzeteus** [comment]
Thx, with preview_OptiFine_1.16.5_HD_U_G8_pre9 it works again!
