### ISSUE TITLE
[Preformance] 2D items setting no longer works in 1.16.5

### ISSUE THREAD

**Issue by Pythagoras-314** [sp614x/optifine#5468]
## Description of Issue
Items still appear as they do in Vanilla when the 2D items option is enabled. It applies to when the item is held or thrown on the ground, not sure about item frames.

## Steps to Reproduce
1. Turn 2D items option on
2. Throw an item on the ground, it doesn’t appear 2D.

## OptiFine Version
1.16.5 G7

**Comment by Regnander** [comment]
Related #401
