### ISSUE TITLE
SmoothFPS stops the world from loading

### ISSUE THREAD

**Issue by KombatDesigns** [sp614x/optifine#547]
Whenever I join a server or single player with optifine for some reason the world won't load and I stay at 0 fps? I have been trying for about 4 hours to find out what the problem was but I just couldn't find it. PLease help!

**Comment by Xrainiel** [comment]
Same here, I can play my world with regular Vanilla Minecraft, but not with optifine :(

**Comment by KombatDesigns** [comment]
Let me try

**Comment by sp614x** [comment]
Which OptiFine version?
Forge, other mods installed?

**Comment by Xrainiel** [comment]
I tried both OptiFine 1.11.2 HD U B7 and B6, no other mods, or forge.

**Comment by TheHADILP** [comment]
I can confirm this issue (version 1.11.2-OptiFine_HD_U_B7, no other mods).

**Comment by sp614x** [comment]
The Smooth FPS issue #583 is probably caused by Windows using wrong graphics card after Win10 update.
