### ISSUE TITLE
Game crashes due to driver uncompatibility with OptiFine

### ISSUE THREAD

**Issue by Xeorth** [sp614x/optifine#5470]
I have problem running OptiFine , it crashes every time I enter the game with or without mods, shaders or no shaders. It says I have bad video drivers on AMD Radeon R9 380. I have been updating it to the point I got yesterdays new update so I think Optifine needs to update this and not me. Question I have is whether I should downgrade or this will be fixed soon. 

A fatal error has been detected by the Java Runtime Environment:

EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffbe2317666, pid=18220, tid=0x0000000000005170

JRE version: Java(TM) SE Runtime Environment (8.0_281-b09) (build 1.8.0_281-b09)
Java VM: Java HotSpot(TM) 64-Bit Server VM (25.281-b09 mixed mode windows-amd64 compressed oops)
Problematic frame:
C  [atio6axx.dll+0x16a7666]

Failed to write core dump. Minidumps are not enabled by default on client versions of Windows

An error report file with more information is saved as:
C:\Users\Viral\AppData\Roaming.minecraft\hs_err_pid18220.log

If you would like to submit a bug report, please visit:
 http://bugreport.java.com/bugreport/crash.jsp
The crash happened outside the Java Virtual Machine in native code.
See problematic frame for where to report the bug.

AL lib: (EE) alc_cleanup: 1 device not closed
Here I am!
[VersionManager] Refreshing versions locally...
[VersionManager] Versions has been refreshed (11 ms)
[Launcher] Launcher exited.
[Launcher] Minecraft closed with exit code: 1
flush now
[Launcher] [Crash] Signature "Bad video drivers" matches!
[Crash] Signature "Bad video drivers" matches!
[Launcher] [Crash] Crash has been recognized!
[Crash] Crash has been recognized!
flush now

Hope we can resolve this soon!

**Comment by Xeorth** [comment]
Fixed it with rollback to novembers update. Hope this gets updated.

**Comment by sp614x** [comment]
Can't be fixed by OptiFine when the driver crashes.
Newer AMD drivers quite often have problems with shaders.
