### ISSUE TITLE
[Category] 1.16.5 emissive.properties causing missing texture in chests when held

### ISSUE THREAD

**Issue by drathmorgh** [sp614x/optifine#5473]
## Description of Issue
I have found that the emissive textures packs are causing Chests, Shulkers, Beds to show as no texture when held in hand, this is visible to the player via the inventory preview and via F5 mode and any onlookers with an emissive pack active.
I use a fair few emissive textures in my pack and my pack is quite popular so have had numerous reports of this bug.
I have tested about 3 other emissive packs from PlanetMinecraft and the missing texture is guaranteed with any one of them.
I tested this on fabric and paper servers not tested on a vanilla server (don't have one to test on) this is not an issue on single player worlds to my knowledge but I do not play single player worlds or other than pack making and or basic testing have not had this issue that I remember while testing thus far.

## Steps to Reproduce
1. enable resource pack with emissive textures. 
2. remove emissive.properties issue goes away, replace file issue returns.

## OptiFine Version
1.16.5 HD U G7 and HD U G8 pre9

## Installation Method
Via the Optifine installer

## Other Installed Mods
No other mods as I don't use any

## Prior Testing
This only happens with Optifine as emissive textures are an Optifine only available via Optifine

## Additional Information
This has been plaguing me for a while now and finally narrowed it down to the emissive.properties file with the same result every time without fail.

**Comment by sp614x** [comment]
Latest 1.16.5 preview has some bugfixes for emissive textures.
Is the bug still present there?

**Comment by drathmorgh** [comment]
I have downloaded the latest version and the texture is still missing

**Comment by sp614x** [comment]
Which specific resource pack?

**Comment by drathmorgh** [comment]
Mine, or any pack that offers emissive textures.
This is mine https://www.mediafire.com/file/10mp5gv0dncuuxi/Nebula_V10.5.zip/file
But I searched or emissive textures and enabled the first few I found all having the same issue.

**Comment by drathmorgh** [comment]
Just downloaded the latest G8 pre10 and I'm still getting the same thing.

**Comment by drathmorgh** [comment]
also im not seeing the screenshots in the original post so here are some more incase 
![2021-03-24_03 29 14](https://user-images.githubusercontent.com/81181296/112250354-21120200-8c51-11eb-8303-649efdbd1900.png)
![2021-03-24_03 28 48](https://user-images.githubusercontent.com/81181296/112250427-43a41b00-8c51-11eb-9309-77209df9cb08.png)
![2021-03-24_03 28 45](https://user-images.githubusercontent.com/81181296/112250431-44d54800-8c51-11eb-8607-01ec2fd2d261.png)

**Comment by drathmorgh** [comment]
and someone
![2021-03-25_21 23 34](https://user-images.githubusercontent.com/81181296/112539065-6e54b780-8da8-11eb-89c5-aead45c1277c.png)
 just sent me this from a single player world!!!

**Comment by drathmorgh** [comment]
as of 1.16.5_HD_U_G8 still the same.

**Comment by drathmorgh** [comment]
same all the way up to the now preview_OptiFine_1.18.1_HD_U_H4_pre1

**Comment by drathmorgh** [comment]
Haven't seen the issue in a while.
SO I will close this as I think its been solved
