### ISSUE TITLE
mysterious problem, shaders!

### ISSUE THREAD

**Issue by wtfbaby** [sp614x/optifine#5475]
self explanatory
https://user-images.githubusercontent.com/80798837/112071324-4407bd80-8b4e-11eb-8f4c-f3c2878f8b6a.mp4

 -->

## Steps to Reproduce
still and a mystery it happens in all shaders,

in 1.12.2 works normal
more than 1.16, this problem started!

## OptiFine Version
OptiFine_1.16.4_HD_U_G7

## Installation Method
I put it in the mods folder, and already installed it in the installer, but regardless of the way I installed it, it keeps happening!

## F3 Debug Screenshot
:/

## Prior Testing
(??)

## Additional Information
sorry i don't have more information! :/

**Comment by Stereo528** [comment]
Do you have any more info on this? Is the Mojang screen staying up when you load the shader, or is something else happening, the video is too short for me to really tell.

**Comment by wtfbaby** [comment]
sorry for the delay
also sorry for the closings

after trying several times to resolve the error / bug, and also waiting for your answer, it made me give up waiting for a solution, (I just stayed on the site only one day waiting for an answer, sorry)

I'm sorry for not using the site frequently, I'm not very active on that site so I didn't answer! : /

**Comment by wtfbaby** [comment]
> Do you have any more info on this? Is the Mojang screen staying up when you load the shader, or is something else happening, the video is too short for me to really tell.

sorry for the delay
also sorry for the closings

after trying several times to resolve the error / bug, and also waiting for your answer, it made me give up waiting for a solution, (I just stayed on the site only one day waiting for an answer, sorry)

I'm sorry for not using the site frequently, I'm not very active on that site so I didn't answer! : /
