### ISSUE TITLE
Frame rate dropping

### ISSUE THREAD

**Issue by Maratons4** [sp614x/optifine#5478]
When i launch Minecraft everything is fine. Better frame rate, as usual. But like 3-5 minutes into playing, and out of nowhere my frames drop to 0 for 2 seconds or so, then it refreshes, and then again 0 fps. It fixes once i wait around 30 sec-1min, but it continues happening. I havethis issue on 1.8.9, and 1.16.4 (I haven't tested other versions)

**Comment by Lentern** [comment]
Can you take a screenshot of your F3 menu and video settings?

**Comment by Maratons4** [comment]
![Screenshot_12](https://user-images.githubusercontent.com/81237150/112452806-af74a980-8d5f-11eb-8db7-15353ccdf505.png)

All the video sttings are put onminimum (render distance 2, particles off

**Comment by KaiAF** [comment]
Do you have a graphics card? If so, then OptiFine isn't using it.

**Comment by Maratons4** [comment]
I have an intergrated graphics card. Intel Graphics 3000

**Comment by KaiAF** [comment]
Since you have an iGPU, there could be a few OptiFine settings enabled that could be causing this. i.e. Render Regions, Smooth FPS.
If you want to take the time, you can see if disabling those settings (Which are found at video settings > Performance Settings) helps any.

**Comment by Maratons4** [comment]
Thank you! It seems to work normally after changing the settings!
