### ISSUE TITLE
Outer part of Slime CEM is not replaced with custom one.

### ISSUE THREAD

**Issue by Stardust178** [sp614x/optifine#5490]
## Description of Issue
I created CEM to replace the model of Slime and noticed there's no way to change the outer layer.

![image](https://i.imgur.com/saFRGyE.png)

## Minecraft Version
1.16.5

## OptiFine Version
HD U G7

**Comment by Regnander** [comment]
> HD U G7

This is 1.16.5, right?

**Comment by Stardust178** [comment]
> > HD U G7
> 
> This is 1.16.5, right?

Yes

**Comment by sp614x** [comment]
Duplicate of #5481
