### ISSUE TITLE
[Chest Bug] Broken Chest Texture & Interior

### ISSUE THREAD

**Issue by TrailBlaize** [sp614x/optifine#5501]
When Optifine of any recent download is activated, I completely lose the texture for all chests.
All I see is either a white chest, or a black and pink flickering chest.
The interior texture seems to be cut in half as well, with the top half showing while the bottom is not.
I can still place items in the bottom half but they appear to be floating.
I have reinstalled Minecraft totally and reinstalled optifine to check if it was just an install problem, it isn't.
If Optifine is turned off, no bug! If it's turned back on, back to ugly chest central.

I've included two photographs further illustrating the problem.

![0e7b5ffb34a131c8c84fbb9290389b9c](https://user-images.githubusercontent.com/81487037/112731327-23e44f80-8efc-11eb-97e0-6ab9e7228dcf.png)
![qxU2zEU](https://user-images.githubusercontent.com/81487037/112731328-247ce600-8efc-11eb-9561-0e60a4fefe5c.png)

**Comment by KaiAF** [comment]
Can you send an F3 screenshot? If you are using any other mods, what are they? Could be something with the resource pack?

**Comment by TrailBlaize** [comment]
Not using any other mods or resource packs, just Optifine.

![2021-03-27_17 15 10](https://user-images.githubusercontent.com/81487037/112737554-0b3a6080-8f21-11eb-92da-f8f08a389f18.png)
