### ISSUE TITLE
Optifine 1.16.5 (latest version) wont load.

### ISSUE THREAD

**Issue by derp14noob** [sp614x/optifine#5508]
When I start up Optifine 1.16.5 HD U G7 I will just get an error:
"ERROR
Game crashed
An unexpected issue occurred and the game has crashed. We're sorry for the inconvenience.
Exit Code: 0"

Other Optifine versions (1.8.9 Optifine HD U H8) still load and so does vanilla minecraft.
Also, this just started to happen about one hour ago. I could play Optifine 1.16.5 just fine before.

**Comment by KaiAF** [comment]
Can you send the crash log?

**Comment by derp14noob** [comment]
10:51:52.599
-da[:<packagename>...|:<classname>]
10:51:52.599
-disableassertions[:<packagename>...|:<classname>]
10:51:52.599
disable assertions with specified granularity
10:51:52.599
-esa | -enablesystemassertions
10:51:52.599
enable system assertions
10:51:52.599
-dsa | -disablesystemassertions
10:51:52.599
disable system assertions
10:51:52.599
-agentlib:<libname>[=<options>]
10:51:52.599
load native agent library <libname>, e.g. -agentlib:hprof
10:51:52.599
see also, -agentlib:jdwp=help and -agentlib:hprof=help
10:51:52.599
-agentpath:<pathname>[=<options>]
10:51:52.599
load native agent library by full pathname
10:51:52.599
-javaagent:<jarpath>[=<options>]
10:51:52.600
load Java programming language agent, see java.lang.instrument
10:51:52.600
-splash:<imagepath>
10:51:52.600
show splash screen with specified image
10:51:52.600
See http://www.oracle.com/technetwork/java/javase/documentation/index.html for more details.
10:51:52.733
Process crashed with exit code 1

**Comment by KaiAF** [comment]
Are you using any other mods? Try resetting the JVM Arguments? 
I am not able to reproduce this issue.

**Comment by KaiAF** [comment]
Assume this is resolved now, if not, let me know.
