### ISSUE TITLE
[shaders] Sildurs sky glitch

### ISSUE THREAD

**Issue by idkimanerd** [sp614x/optifine#5509]
## Description of Issue
 When using sildur vibrant shaders on a modpack (project ozone 3), the sky is split in half. I tried disabling astral sorcery weaksky, nothing happpened 

## Steps to Reproduce
1. install optifine, forge po3, and sildur vibrant lite shaders
2. activate shaders and load up world

## OptiFine Version
 1.12.2_HD_U_G5. 

## Installation Method
dropping JAR file into mods folder

## Forge Version
14.23.5.2584

## Other Installed Mods
https://pastebin.com/PfqkbCmh 

## F3 Debug Screenshot
[2021-03-29_11 28 41](https://user-images.githubusercontent.com/81585709/112882638-0d680080-9082-11eb-9f5c-ae690fe22dc7.png)
  

## Prior Testing
 If you've installed standalone:
- Does this happen in Vanilla without OptiFine? No

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? No
   - Only OptiFine and Forge
   - Only OptiFine, OptiFabric, and Fabric
- Does this happen without any mods at all? No
   - Only Forge/Fabric by itself.
- Does this happen in OptiFine standalone? No
- Does this happen in Vanilla without OptiFine? No
- Have you tried using a binary search to find which mods cause this issue? I'll start doing that
   - To find conflicting mods, split your mods into 2 groups (not including OptiFine/OptiFabric, obviously). Remove one group, and test in-game. Keep the group that has the problem, and repeat until no more mods can be removed without the issue disappearing.
   - Does the issue still happen with only the remaining mods installed?
      - Forge/Fabric and remaining mods, without OptiFine 

## Questions
can I use binary search methods with a mod pack that may have conflicting issues?

**Comment by KaiAF** [comment]
What happens when you up your render distance? This looks like it's something related to the skybox.

**Comment by idkimanerd** [comment]
Nothing changed. How high should I turn it and should I change any settings?

**Comment by idkimanerd** [comment]
> What happens when you up your render distance? This looks like it's something related to the skybox.
I turned it up to 24, nothing changed. I messed around with settings and it didn't change either.

**Comment by sp614x** [comment]
You should try with a binary search to find the conflicting mod.
Test with half of the mods, keep the half that has the problems, repeat until only one mod left.

**Comment by idkimanerd** [comment]
> You can try with a binary search to find the conflicting mod.
> Test with half of the mods, keep the half that has the problems, repeat until only one mod left.

a large amount of the mods require other mods to be installed, and that is making it difficult to remove half

**Comment by KaiAF** [comment]
Is this still an issue? If it is, it would be helpful if you could go through and try to find the mod that is causing this. If not, I am going to close the issue.

**Comment by idkimanerd** [comment]
Sorry, I no longer play this pack.
