### ISSUE TITLE
Fix to Mac OS Big Sur White Screen when trying to go Full Screen

### ISSUE THREAD

**Issue by LilBeefSteak** [sp614x/optifine#5510]
It’s actually very easy, just uninstall Minecraft. Go to Finder, Applications, Find Minecraft, Right Click and choose (Move to trash) then empty your trash. Then go to Minecraft.net and you want to sign in. Once signing in go to games, and go to Minecraft, Click (Get Minecraft) then (Computer) then (Mac) And there will be a green button saying download and you can just download it again. Yes it’s free.

**Comment by KaiAF** [comment]
Would this be related to #5028? If so, this should have been fixed already.

**Comment by LilBeefSteak** [comment]
> Would this be related to #5028? If so, this should have been fixed already.

Wait fr? Tbh I thought I solved it and then 2 mins later it stopped working. Can you copy and paste what the guy commented?

**Comment by KaiAF** [comment]
What version are you using? If it's 1.8 then update the recent pre release. If not, let me know.

**Comment by LilBeefSteak** [comment]
> What version are you using? If it's 1.8 then update the recent pre release. If not, let me know.

Well it works fine if I launch Minecraft it’s self without optifine etc on any version. But it doesn’t work with Optifine or Lunar Client on any version.

**Comment by sp614x** [comment]
Fixed in in M6_pre1 for 1.8.9.
