### ISSUE TITLE
[Rendering] stained glass flickering behind other glass

### ISSUE THREAD

**Issue by SmajloSlovakian** [sp614x/optifine#5511]
## Description of Issue
from some angles glass behind other glass flickers between rendered and unrendered state
video demonstration Optifine then Vanilla: [https://youtu.be/-9HEZRPsZdY](url)
github doesnt allow files bigger than 10MB :/

settings didnt help nor changed anything
settings tested: fast render, general graphics, render regions, translucent blocks and maybe more

## Steps to Reproduce
1. place stained glass so you can see them behind each other
2. look from another angles

## OptiFine Version
1.16.5

## Installation Method
standalone (with custom launcher which only changes the name from Optifine 1.16.5 U2 (or something like that) to only  
Optifine 1.16.5

image for reference without the need of video:
![2021-03-30_13 36 50](https://user-images.githubusercontent.com/16209307/112982990-6a84b480-915d-11eb-897e-2781514c001d.png)

**Comment by KaiAF** [comment]
Seems to be related to #5390. If you think otherwise, let me know.
