### ISSUE TITLE
Minecraft crashes when a splash screen finishes loading

### ISSUE THREAD

**Issue by Matteoki** [sp614x/optifine#5512]
Whenever i change texturepack, change some shaders, or when a **loading screen appears**, the game crashes
it only occurs on 1.12 to 1.16+ 
_(it doesn't occur on versions where there's no loading screen)_

With other mods and vanilla works

**Pc Specs:**
RX560
Ryzen 5 2600
Drivers are updated

**Comment by KaiAF** [comment]
Can you provide a crash log?

**Comment by Matteoki** [comment]
> Can you provide a crash log? What shaders are you using?

Crap it doesn't send the email, btw im using the internal shaders and sometimes i take them off, it happens with or without shaders. Not only that

Here's the log: https://www.mediafire.com/file/6s1ps7s4fkv3wjx/tl-logger6976308279423328178.txt/file

**Comment by KaiAF** [comment]
Could be something with graphics card drivers. 
> Problematic frame:
> C  [atio6axx.dll+0xbd07f0]

Update them, see if that helps any.

**Comment by Matteoki** [comment]
I updated them to the latest version (even if it gives me rendering errors in Blender)
Same issues, even driver easy says that it doesn't need an update

2021 Amd drivers sucks, the old ones were better, there's no download for them

**Comment by KaiAF** [comment]
Closing this as this isn't an optifine issue. We can't fix AMD Drivers, unfortunately.
