### ISSUE TITLE
[shaders] renderer macros need an overhaul

### ISSUE THREAD

**Issue by platyple** [sp614x/optifine#5515]
Hey there!
I have previously raised this issue and you addressed it, with the minor drawback that you didn't actually fix it (context: #5246). In hindsight I could've explained it better so allow me to try again:

At the moment, the MC_GL_RENDERER_MESA macro only targets Intel integrated graphics running Mesa, linux' open source graphics drivers. 
This is fine, but Mesa is also the graphics driver for AMD cards on linux and _it behaves identically regardless of hardware._
AMD also releases their own drivers for linux which behave the same as the drivers found on windows, but in my experience, these are very rarely used.

At the moment, the only way to target Mesa as a whole is `#if (defined MC_GL_RENDERER_MESA || (defined MC_GL_RENDERER_OTHER && defined MC_OS_LINUX))`. This isn't very elegant and noone's gonna put this in their shader.

I would propose that anything that actually runs through Mesa (both Intel and AMD graphics) is included in MC_GL_RENDERER_MESA, and AMD cards running AMD's proprietary drivers are included in MC_GL_RENDERER_RADEON. This is the only solution that makes sense considering the featureset of the different drivers, as well as the name of the two macros.

## Steps to Reproduce
1. Have an AMD card in a system running Linux with Mesa
2. Try to target it with MC_GL_RENDERER_MESA

## OptiFine Version
doesn't matter

## Installation Method
doesn't matter

## Fabric/Forge Version
doesn't matter

## OptiFabric Version
doesn't matter

## Other Installed Mods
doesn't matter

If you need any help with figuring out what cards to target internally or how to target them I would be happy to help in any capacity I can.
Cheers!

**Comment by sp614x** [comment]
The `MC_GL_RENDERER_XXX` is detected from the OpenGL `GL_RENDERER`:
```
  public static String getRenderer()
  {
    String renderer = GL11.glGetString(GL11.GL_RENDERER);
    if(renderer == null)
      return MC_GL_RENDERER_OTHER;
    // Lowercase
    renderer = renderer.toLowerCase(); 
    // Radeon
    if(renderer.startsWith("amd"))
      return MC_GL_RENDERER_RADEON;
    if(renderer.startsWith("ati"))
      return MC_GL_RENDERER_RADEON;
    if(renderer.startsWith("radeon"))
      return MC_GL_RENDERER_RADEON;
    // Gallium
    if(renderer.startsWith("gallium"))
      return MC_GL_RENDERER_GALLIUM;
    // Intel
    if(renderer.startsWith("intel"))
      return MC_GL_RENDERER_INTEL;
    // Geforce
    if(renderer.startsWith("geforce"))
      return MC_GL_RENDERER_GEFORCE;
    if(renderer.startsWith("nvidia"))
      return MC_GL_RENDERER_GEFORCE;
    // Quadro
    if(renderer.startsWith("quadro"))
      return MC_GL_RENDERER_QUADRO;
    if(renderer.startsWith("nvs"))
      return MC_GL_RENDERER_QUADRO;
    // Mesa
    if(renderer.startsWith("mesa"))
      return MC_GL_RENDERER_MESA;
    // Other
    return MC_GL_RENDERER_OTHER;
  }
```

**Comment by sp614x** [comment]
The OpenGL `GL_RENDERER` shows what GPU is doing the rendering.
It should be MESA only for software rendering (no GPU acceleration).
When using a dedicated GPU it should contain the ID of the GPU.

**Comment by platyple** [comment]
That does make sense, but if you're writing code specifically for Mesa then having one macro that identifies all GPUs running on Mesa would make things significantly easier. Again, Mesa's output is the same regardless of hardware (or software) so no shader developer would care whether the game is being rendered through software or hardware.

If you don't want to budge on what renderer belongs in what macro, say I want to write an exception in a shader for all cards running on Mesa. How would I target that apart from the code snippet I already posted?

**Comment by sp614x** [comment]
OptiFine only exposes the information that OpenGL reports as GL_RENDERER.
What is the GL_RENDER for AMD on Linux?
You can find it in the log file or create a manual crash dump and it would be at the end of the crash report.

**Comment by platyple** [comment]
For a 5600XT that line would be `AMD Radeon RX 5600 XT (NAVI10, DRM 3.40.0, 5.11.11-200.fc33.x86_64, LLVM 11.0.0) GL version 4.6 (Compatibility Profile) Mesa 20.3.5, AMD` 

However, by that logic it would fall under MC_GL_RENDERER_RADEON, which it does not as far as I can tell.

**Comment by sp614x** [comment]
The `GL_RENDERER` string is only the GPU, it doesn't include the driver details.
It should be `AMD Radeon RX 5600 XT` and it would fall under `MC_GL_RENDERER_RADEON`

**Comment by platyple** [comment]
That still runs into the problem that Mesa behaves differently to AMD's proprietary drivers and AMD cards running Mesa would be better fit in `MC_GL_RENDERER_MESA`

**Comment by sp614x** [comment]
The AMD + Mesa should use `MC_GL_VENDOR_XORG`, while the AMD driver should use `MC_GL_VENDOR_AMD`.

**Comment by platyple** [comment]
that's not the case, my setup falls under `MC_GL_VENDOR_AMD`

**Comment by sp614x** [comment]
Can you post a test crash report (F3+C for 10sec)?

**Comment by platyple** [comment]
Sure thing
[crash-2021-04-03_21.39.55-client.txt](https://github.com/sp614x/optifine/files/6257845/crash-2021-04-03_21.39.55-client.txt)

**Comment by sp614x** [comment]
Backend API: AMD Radeon RX 5600 XT (NAVI10, DRM 3.40.0, 5.11.11-200.fc33.x86_64, LLVM 11.0.0) GL version 4.6 (Compatibility Profile) Mesa 20.3.5, AMD
```
GL_RENDERER: AMD Radeon RX 5600 XT (NAVI10, DRM 3.40.0, 5.11.11-200.fc33.x86_64, LLVM 11.0.0)
GL_VERSION: 4.6 (Compatibility Profile) Mesa 20.3.5
GL_PROVIDER: AMD
```
According to OpenGL this is an AMD GPU with an AMD driver.
How should OF detect it as something else?

**Comment by sp614x** [comment]
All other AMD + Mesa driver combinations that I have found so far report the vendor as X.org, for example: 
```
OpenGlVersion: 4.6 (Compatibility Profile) Mesa 20.0.8
OpenGlRenderer: AMD Radeon (TM) RX 480 Graphics (POLARIS10, DRM 3.35.0, 5.4.0-70-generic, LLVM 10.0.0)
OpenGlVendor: X.Org

OpenGlVersion: 4.6 (Compatibility Profile) Mesa 20.2.6
OpenGlRenderer: AMD RAVEN (DRM 3.38.0, 5.8.0-7630-generic, LLVM 11.0.0)
OpenGlVendor: X.Org

OpenGlVersion: 3.0 Mesa 20.2.6
OpenGlRenderer: AMD RS880 (DRM 2.50.0 / 5.8.0-48-generic, LLVM 11.0.0)
OpenGlVendor: X.Org

OpenGlVersion: 3.1 Mesa 20.2.6
OpenGlRenderer: AMD TURKS (DRM 2.50.0 / 5.4.0-70-generic, LLVM 11.0.0)
OpenGlVendor: X.Org
```

**Comment by platyple** [comment]
That's odd, I'll file a bug report with the Mesa devs then.

**Comment by platyple** [comment]
Have you per chance had any vendors for other Navi cards?

**Comment by platyple** [comment]
Navi has a vendor string for AMD because the code handling them was almost exclusively written by AMD employees, meaning this might become a reoccuring issue.

Different idea:
GL_VERSION ends with Mesa followed by a version number, so for ease of use (and since the current macro defining Mesa isn't very useful), would it be possible for you to check for that and return `MC_GL_RENDERER_MESA` if true? It's not a particularly clean solution but it would be more future-proof, plus it would make Mesa compatibility alot more intuitive for shader devs.

**Comment by sp614x** [comment]
The renderer (GPU) is not Mesa (software), it should be RADEON as the rendering is accelerated.
I could detect Mesa and change the vendor to `X.org` as an alternative.

**Comment by platyple** [comment]
Sure, but from a functionality perspective my option would make more sense...

**Comment by sp614x** [comment]
Is there a description of the mess that are the OpenGL drivers on Linux?
Also for nvidia and intel drivers.

**Comment by platyple** [comment]
No public one, but I'll give it a shot:
NVidia has their own proprietary drivers and nouveau (which noone uses), which is part of Mesa. The vendor string for the proprietary drivers is `NVIDIA`, nouveau's vendor string is either `nouveau` or `NVIDIA`, don't quote me on that, though.

Intel cards exclusively run through Mesa, they should have the vendor string `Intel`.

AMD has Mesa and AMDGPU-pro (AMD's proprietary driver stack), the vendor string for Mesa is (apparently) either `X.Org` or `AMD`, for AMDGPU-pro it's `AMD`.
~I think Qualcomm GPUs etc. also fall under Mesa but I think we can leave those out of the question~

**Comment by sp614x** [comment]
The NVidia Mesa driver shows as:
```
OpenGlVersion: 3.3 (Compatibility Profile) Mesa 20.2.6
OpenGlRenderer: NVA5
OpenGlVendor: nouveau
```

**Comment by platyple** [comment]
Anything older than nv30 has a different vendor string, i don't know what it is, though.

**Comment by sp614x** [comment]
There is also this one:
```
OpenGlVersion: 2.1 Mesa 10.0.2 (git-675cd84)
OpenGlRenderer: Gallium 0.4 on llvmpipe (LLVM 3.4, 128 bits)
OpenGlVendor: VMware, Inc.
```

**Comment by platyple** [comment]
I feel like making a vendor macro for Mesa and defining it by a regexp search for `Mesa` in the version string would be the smartest way forward, unless you're concerned about Gallium

**Comment by sp614x** [comment]
Added `MC_GL_VENDOR_MESA`, returned when version string contains `Mesa`.

**Comment by platyple** [comment]
\o/

**Comment by sp614x** [comment]
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.txt#L721
