### ISSUE TITLE
Download Issue

### ISSUE THREAD

**Issue by Nolqn** [sp614x/optifine#552]
When I download any Optifine, it downloads this. https://gyazo.com/4f0329ec0ea259e3bb56acf461af0a9f. Then when I click on it, it brings me here. https://gyazo.com/2352510b53d99d86dd7b266f240317a2. Whether I click Open, Save, or Save As, it redownloads the first file, and the same thing happens over and over again. And dont tell me I need java, because I have Java, I redownloaded Java 3 times over.

**Comment by timvanbavel** [comment]
Click here:
![image](https://cloud.githubusercontent.com/assets/24352731/24324828/c2c8fba0-118d-11e7-823d-bb609ba03eb5.png)

**Comment by Ristovski** [comment]
You seem to have set `.jar` files to open with Internet Explorer. You should change this to "Java" by right-clicking the `.jar` file, going to Properties, and changing the "Opens with" field.

**Comment by Nolqn** [comment]
I am not sure how to do that Ristovski, Can you help me further. Also not which which file to switch.

**Comment by Nolqn** [comment]
@Ristovski

**Comment by Ristovski** [comment]
@Nolqn I just noticed what you're actually trying to do. You don't **open** OptiFine, you need to add it to your mods folder. Once you install Forge you can read on how to install Forge mods [here](http://minecraft.gamepedia.com/Mods/Installing_forge_mods).

**Comment by Nolqn** [comment]
@Ristovski https://www.youtube.com/watch?v=PxZM1nYHorw I made a video showing my problem, this also happens to anything else I download with Java so I cant download Forge either.

**Comment by sp614x** [comment]
@Nolqn Right click -> Open With -> Java (TM) Platform SE Binary

**Comment by Nolqn** [comment]
@sp614x @Ristovski https://www.youtube.com/watch?v=r90eP0ss3ig thats what happens

**Comment by timvanbavel** [comment]
@Nolqn maybe reinstalling java will reset the file allocations. Try reinstalling it with https://ninite.com/java8/

**Comment by Nolqn** [comment]
@timvanbavel @sp614x @Ristovski I found a thread on hypixel and a guy gave me a link to fix all jar programs and I have everything fixed now. Thanks for your help anyways! :D
