### ISSUE TITLE
[Rendering] When shaders are enabled, Refined Storage mod blocks render issue

### ISSUE THREAD

**Issue by fekke** [sp614x/optifine#5521]
## Description of Issue
When shaders are activated the rendering of Refined Storaged blocks have a rendering issue. 
With no shaders activated, they are fine. 

Tried version OptiFine HD U G7 and works without a issue. 

Seams to be something about this rendering issue, experimentalForgeLightPipelineEnabled? 
https://github.com/refinedmods/refinedstorage/issues/2727

## Steps to Reproduce
Activate shader when Refined Storage mod version 1.9.12 are installed.

## OptiFine Version
OptiFine HD U G8 pre11

## Installation Method
Drop the Jar in mod folder.

## Other Installed Mods
Valhelsia 3 modpack
https://pastebin.com/AXhdiT8y

![2021-04-03_12 10 07](https://user-images.githubusercontent.com/3190732/113476014-e1c98980-9478-11eb-878e-4e2f23620fb6.png)

**Comment by sp614x** [comment]
Relevant: https://github.com/sp614x/optifine/issues/5448

Refined Storage needs a bugfix:
https://github.com/refinedmods/refinedstorage/issues/2919#issuecomment-806936887
