### ISSUE TITLE
[Bug] Weird Glitches on Multiplayer

### ISSUE THREAD

**Issue by jonathancurits2006** [sp614x/optifine#5523]
## Description of Issue

DOES NOT HAPPEN ON OPTIFINE G8

I host a PaperMC Server and I've been encountering issues when joining it using Optifine 1.16.5.
The server is survival, and every now and then items will disappear and then re-appear in my inventory. Sometimes when I break blocks, the items "disappear" only to re-appear in my inventory a few moments later. At first I thought it was server lag, but I soon found this to not be the case. I rejoined on plain 1.16.5 and the issue went away. I went back on Optifine, and it came back. Either this is a very odd coincidence, or something is wrong here.

tl;dr:
When using Optifine on multiplayer servers, the game feels sluggish. Not FPS drops, but things such as:
- When switching to an item with a cooldown, it gets halfway through the cooldown then resets before it goes back to normal.
- Blocks sometimes disappear and re-appear randomly
- Some actions, such as right clicking on a bed, take more time to register.
- None of this happens in vanilla.

## Steps to Reproduce
1. Join a survival server (My server runs on Paper, not sure if that makes a difference.)
2. Break blocks, move things around in your inventory, etc. (Or just play the game, if the bug occurs you'll probably notice that the game feels a little off)

## OptiFine Version
1.16.5-Optifine_HD_U_G7

## Installation Method
Standalone Installer

## Log Files/Crash Reports

[latest.log](https://github.com/sp614x/optifine/files/6252610/latest.log)

## F3 Debug Screenshot
![image](https://user-images.githubusercontent.com/77545656/113479358-a15c1280-945c-11eb-8933-4409c0327687.png)

## Prior Testing
<!-- If you've installed standalone:
- Does this happen in Vanilla without OptiFine? **No**

**Comment by sp614x** [comment]
Looks like a bug that was fixed in G8.
Can't find the issue, but it was affecting the stonecutter GUI.
