### ISSUE TITLE
[wandering traders] goes back to the default skin

### ISSUE THREAD

**Issue by Shojisl** [sp614x/optifine#5528]
## Steps to Reproduce
1. What do you do...
2. ...to find this bug? I used random textures and CEM model for wandering traders. When leaving and entering the save they return to the default texture. I will leave a video in this post.

## OptiFine Version
 OptiFine HD U G8 pre11

## Installation Method
 Both

## Fabric/Forge Version
 no

## OptiFabric Version
 no

## Other Installed Mods

 no

 I will leave a short video

## Additional Information
  I will leave a short video
The message I wrote on discord: Hello sir optifine's creator
I think I found a little problem, but I'm not sure, look
the left has a villager, the right a wandering trader
when you leave and enter your save the wandering trader goes back to the default skin
it doesn't happen with other mobs

https://user-images.githubusercontent.com/78093675/113510802-e3578800-9532-11eb-8b3c-b829c4bd6058.mp4

**Comment by ZenithRogue** [comment]
Not a bug, biome based entity textures are not persistent. Biome tracking is done by looking at where the entity first loads
