### ISSUE TITLE
[1.16.5] "Mojang" logo has issues with rendering if screen.loading is set to any white color in (color.properties)

### ISSUE THREAD

**Issue by jockeyxmc** [sp614x/optifine#5530]
as title says, if you change the mojang logo and try to use any form of white as the loading color it does not display correctly

**Comment by jockeyxmc** [comment]
left is ingame, right is a mockup of what it should look like
![image](https://user-images.githubusercontent.com/79340336/113536933-e6875e00-959c-11eb-9068-febcddc4f756.png)

**Comment by minthousebuilder** [comment]
You need to add `screen.loading.blend=off` to color.properties, doing that should fix it.
