### ISSUE TITLE
[Shaders] Rename "texture" sampler uniform in gbuffers

### ISSUE THREAD

**Issue by rre36** [sp614x/optifine#5537]
The "uniform sampler2D texture" in the gbuffers passes collides with modern GLSL syntax (as texture() is a reserved function call). This makes it mandatory to rely on the driver binding the first bound image (the texture atlas) to whatever undefined uniform sampler2D one decides to use (e.g. I use "gcolor"). This might work in most cases but is still not a good solution as its relying on undefined behavior on the driver side.
I suggest having an alternative binding (similar to how colortex-images are also bound to legacy names like gaux1) called "baseColor" or "albedo" as these terms do not collide with GLSL syntax and are more descriptive of the data stored in the bound image (although "albedo" technically means flat base color without baked in shading or ambient occlusion, so I'd prefer "baseColor" as a more universally applicable term).
This also applies to shadow gbuffers.

**Comment by sp614x** [comment]
Renamed `"sampler2D texture"` to `"sampler2D gtexture"`.
Legacy shaders would be fixed by the compatibility mode.

**Comment by ColdIce1605** [comment]
@sp614x you seem to have forgot adding that to the docs

**Comment by sp614x** [comment]
Fixed in docs
