### ISSUE TITLE
Custom particles

### ISSUE THREAD

**Issue by SoniEx2** [sp614x/optifine#554]
The `/particle` command should be modified to take an optional JSON as the last argument. Particles should have paths and properties. `assets/minecraft/particles/paths` should contain path JSONs and `assets/minecraft/particles/properties` should contain property JSONs.

Property JSONs should map variants to properties. Properties include things like color, path, texture, etc. 

Things should be modified to use properties, e.g. noteblocks should be modified to pass the note and the instrument as properties:

```
/particle note [etc] {note:/*a value from 0 to 24*/,instrument:/*one of "piano" "bassguitar" "drums" "clicks" "snare"*/}
```

That way I can use piano keys for the piano particle, a drum for the drums particle, etc. And each note can have separate color.

And this is simple enough that it can be encoded in shaders.

(Also, can you make this open source? Or at least have an API for it, so mods can depend on optifine for their own particles.)

**Comment by sp614x** [comment]
Extending commands with new parameters is outside of the OptiFine scope.
Also how should the extended particles be implemented in shaders?

**Comment by SoniEx2** [comment]
You load the path into the shader and make the shader trace the path. Using paths makes it doable.

Same paths you'd find in things like SVG and stuff, but in 3D.

**Comment by sp614x** [comment]
OptiFine does not have built-in shaders, except FXAA (post-processing).

**Comment by SoniEx2** [comment]
I don't understand rendering, so I can't mod this in myself. And mojang refuses to.
