### ISSUE TITLE
Minecraft 1.8.9 Crash

### ISSUE THREAD

**Issue by LuluDodo123** [sp614x/optifine#5540]
## Description of Issue
If I minimize Minecraft my Game crashes.

## Steps to Reproduce
1. Start Minecraft
2. Join Server or single-player World
3. Minimize Minecraft

## OptiFine Version
1.8.9

## Installation Method
I used the included standalone Installer

## Log Files/Crash Reports
Exit Code: 0
I can't find any crash report. All it say is Exit-Code:0

## Prior Testing
It happens in Vanilla.

## Additional Information
I play Minecraft 1.9.8 a lot and this bug never happened to me before.

**Comment by Cart3r1234** [comment]
> It happens in Vanilla.
if it happens in vanilla then it shouldn't be reported here

**Comment by KaiAF** [comment]
This isn't an optifine issue if it happens in vanilla also
