### ISSUE TITLE
Crash with a CodeChicken mod on 1.10.2

### ISSUE THREAD

**Issue by Nosiphus** [sp614x/optifine#555]
Whenever I attempt to view the third tab of my Minecraft 1.10.2 environment, OptiFine crashes the game. I believe that Project Red may be at fault, as it does have rendering issues with OptiFine present, however I cannot be certain.

[https://pastebin.com/gVveuJ3c](https://pastebin.com/gVveuJ3c)

I do know that whenever OptiFine is not present, I can view the third page of tabs without issue. I did place a wire from Project Red down, and it loaded fine, but framed wires tell another story entirely:

[https://pastebin.com/fq2Y7Gz1](https://pastebin.com/fq2Y7Gz1)

**Comment by sp614x** [comment]
It crashes in the ProjectRed FWireModelGen class, no idea what may be wrong there.

**Comment by Nosiphus** [comment]
I think the issue seems to be in the loading sequence. When I did not install OptiFine, Project Red loaded up a whole bunch of wire models. When OptiFine is installed, I never saw those wires get loaded. I will report this error to the Project Red GitHub and see if they know what's going on.

**Comment by Nosiphus** [comment]
I've evaluated the situation, and it turns out that the culprit is neither OptiFine nor Project Red: it's actually Sphax PureBDcraft. I have no clue why the standard textures work but whenever Sphax is introduced, it crashes.
