### ISSUE TITLE
[Modsplit] Optilite? Optifine features?

### ISSUE THREAD

**Issue by SmajloSlovakian** [sp614x/optifine#5553]
## Description of the new feature
Separate mod which containes features of optifine like: CBT, CIT, CEM, compact chat, optifine cape, maybe shaders and features like that... NO OPTIMIZATION, just features...

Why? for compatibility or change of fps boost mods (without giving up on features optifine has)
I know there are mods which are essentially the same but there are not so many! zoom can be installed without optifine but if i would like to use CIT and found a mod, it uses another format...
or if you would like to go vanilla and only wanted features from optifine

Or if there is new minecraft version, we dont have to wait so long for optifine features because this mod will definitely be easier to update

**Comment by KaiAF** [comment]
I am closing this as i am almost certain this would not get done. I believe sp614x used to do this on really old versions. But he stopped because it was too stressful to maintain them all.

**Comment by SmajloSlovakian** [comment]
i would like to have just one... one mod for all the features ... or if there is another mod which changes the rendering then it would turn its rendering changes off @KaiAF

**Comment by SmajloSlovakian** [comment]
i would like it even if it got lower priority
