### ISSUE TITLE
[Mouse] Mouse randomly accelerates when looking

### ISSUE THREAD

**Issue by iamdoms** [sp614x/optifine#5555]
## Description of Issue
So I am having this issue that my mouse randomly accelerates WHEN MOVING. Not because of my sensitivity (which is always low, 60-70%), but because of some random bug which occurs when playing with optifine. It is only happening in Minecraft, and it's not because of "enhance mouse" option in Windows because (as I said) it is not happening outside of Minecraft. Setting javaw.exe priority to below normal doesn't help either. I have tried several ways and have been looking for a solution for hours and still nothing. I have a speedlink mouse and I do not have the driver sadly.
My system specs are very low (4GB RAM, Intel Pentium Inside, ASUS Laptop), but I think that does not matter as it is only happening inside of Minecraft.
I couldn't play with my friends for months now, and it is annoying, so please help me!

## Steps to Reproduce
1. Launch OptiFine 1.8.9
2. Go in multiplayer
3. Just look around

## OptiFine Version
1.8.9-OptiFine_HD_U_L5 or 1.8.9-OptiFine_HD_U_M5 (unsure because I'm playing with LabyMod and Badlion and I played with Lunar)

## Installation Method
Installed through launcher installer

## Other Installed Mods
lithium-fabric-mc1.16.1-0.5.1, phosphor-fabric-mc1.16.1-0.6.0+build.7, sodium-fabric-mc1.16.1-0.1.0, autotip
LabyMod: https://media.discordapp.net/attachments/662717656918523914/831124671670910986/unknown.png?width=157&height=135

## Log Files/Crash Reports
Can't show you because pastebin is showing me [https://media.discordapp.net/attachments/662717656918523914/831125421583237150/unknown.png?width=817&height=77](this) stupid error

## F3 Debug Screenshot
https://media.discordapp.net/attachments/662717656918523914/831126553605570570/unknown.png?width=841&height=473

## Prior Testing
- Does this happen in Vanilla without OptiFine? **No**

**Comment by karmette** [comment]
I'm not really support but I just want to point out that - lithum, phosphor, and sodium are 1.16 mods made for the modloader fabric, which means they are not even present in your game.
also, Labymod causes tons of problems, so try removing that.

**Comment by KaiAF** [comment]
What Karmette said could help
