### ISSUE TITLE
Optifine 1.11.2 Game Freezes when joining server (Optifine 1.11.2 B7)

### ISSUE THREAD

**Issue by DerpStar85** [sp614x/optifine#556]
Whenever I join a server when I have optifine on, the game will open, but will stop at 0fps before it has rendered anything, and I cannot access any options settings. The game does not, however, officially crash and show the crash log, but I have to shut the game down with Task Manager. This started happening once I added optifine to forge once, but still affects the game without having forge loaded. I have atempted to delete optifine from my computer, even directly from versions, but when I reinstall optifine, it still shows my optimiations (I know this because it shows the fps in the top corner) and I do not know how to fix this. Any help I can get?

**Comment by TheHADILP** [comment]
You can go to the .minecraft folder and delete the optionsof.txt file (but probably save it somewhere in case you want to restore your settings).
Then all your Optifine settings will be reset to default settings on next game start.

**Comment by TheHADILP** [comment]
Or you can try to turn off Smoth FPS in Optifine settings and see if that helps.

**Comment by sp614x** [comment]
The Smooth FPS issue #583 is caused by Windows using wrong graphics card after Win10 update.
