### ISSUE TITLE
[Category] Cinematic camera is getting players banned

### ISSUE THREAD

**Issue by MWHunter** [sp614x/optifine#5579]
## Description of Issue
When making combat checks, cinematic disobeys vanilla mouse movement.  This messes up anticheats because it disobeys the vanilla mouse movement grid.  This has gotten players banned on practice servers before and is still an issue.

## Steps to Reproduce
1. Move the mouse
2. Calculate the greatest common denominator
3. There is no greatest common denominator as cinematic camera disobeys vanilla mouse movement

## OptiFine Version
Any optifine version with cinematic camera

## Installation Method
Standalone installer

## F3 Debug Screenshot
Not relevant.

## Prior Testing
<!-- If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
No, because vanilla obeys the vanilla GCD system

## Additional Information
Please rework the cinematic camera to obey vanilla mouse movement, or just remove it entirely

**Comment by Technosword** [comment]
This is a vanilla feature...

**Comment by MWHunter** [comment]
I've been playing minecraft for 8 years and somehow I have never noticed that.
