### ISSUE TITLE
My game always crashes whenever I turn shaders off

### ISSUE THREAD

**Issue by PapiDimmi** [sp614x/optifine#558]
I can change between different shader mods just fine, but if I turn shaders off, my game crashes.

[Crash report.](https://pastebin.com/raw/WCYtUn0R)

**Comment by Ristovski** [comment]
Does this happen even when turning shaders off while **not** in-game?

**Comment by sp614x** [comment]
Crashes at 
`net.darkhax.bookshelf.client.render.item.RenderItemWrapper.func_184391_a(RenderItemWrapper.java:293)`

**Comment by sp614x** [comment]
The crash is outside of OptiFine, in the Bookshelf mod.
