### ISSUE TITLE
If the anticheat fails due to a position difference of 1e-4m (1mm), then it has some problems.

### ISSUE THREAD

**Issue by Tecnio** [sp614x/optifine#5582]
If the anticheat fails due to a position difference of 1e-4m (1mm), then it has some problems.
It should have a tolerance for player actions that is well above 1mm, probably 10cm or something.

_Originally posted by @sp614x in https://github.com/sp614x/optifine/issues/5578#issuecomment-823665612_

**Comment by Tecnio** [comment]
The issue got locked but that doesn't really make sense prediction should flag 1E-4 differences and this is just calling making an actual proper check wrong. Any good anticheat with good enough predictions can flag 1E-12 no problems with Vanilla Minecraft this is just calling a proper check the only way of making a proper check wrong which really doenst make sense. And 10 cms in ur wording cant even flag 80% velocity nor flag 20% speed bypasses which is just weird of you to tell

**Comment by Tecnio** [comment]
I need a good predicted location to run my collisions on which 1E-4 can really effect it and this makes 1:1 movement prediction impossible as a lot of players do use OptiFine but fair enough I guess.

**Comment by Tecnio** [comment]
And brute forcing the values for sin and cos and movements for 200 players concurrently can hit the performance by a bit. But calling sin and cos every 50 ms on a modern cpu it really doesn't effect a lot of stuff.

**Comment by Tecnio** [comment]
Btw kudos for listening and actually caring about peoples problems I appreciate it.

**Comment by KaiAF** [comment]
I will unlock the original issue, sorry. (Copying what you said here and pasting it in the issue)
