### ISSUE TITLE
Entities Textures (Villagers)

### ISSUE THREAD

**Issue by RuddiMinecraft** [sp614x/optifine#5584]
## Villagers textures disappear when they wake up when changed by time (dayTime)

<Villager textures work fine when the time of day is changed with commands, but when villagers sleep and wake up the textures stop working, they just disappear.
I tried G8pre10, G8pre11 and G8pre12 and got the same result, the textures disappear when the villagers wake up.
I tried, changing the parameters of dayTime

texture 1 .. 2000-9000
texture 2 .. 0-1999 9001-23999
I changed it to:

texture 1 .. 2000-9000
texture 2 .. 5-1999 9001-23999

texture 1 .. 2000-9000
texture 2 .. 0-1999 9001-24000

etc

and many more combinations and none worked, whenever the villagers wake up the textures disappear

I reiterate, when the time is changed with commands everything works perfectly, but when the villagers wake up all the textures disappear and do not reappear even if they must change by time>

Forge installed

mods installed
preview_OptiFine_1.16.5_HD_U_G8_pre12
jei-1.16.4-7.6.1.66
u_team_core-1.16.4-3.1.17.192
useful_backpacks-1.16.4-1.11.6.87
worldedit-forge-mc1.16.3-7.2.2-dist 
journeymap-1.16.5-5.7.1

picture
https://ibb.co/44myggL

**Comment by CHanzyLazer** [comment]
I just have had the same situation, guessing that Minecraft dayTime doesn't work in cycles, so when it's over a day (24000), dayTime is out of the range, making it no longer working.

**Comment by Rakiw** [comment]
I am also in the same situation, and I'm writing this comment to give this bug some more attention.

**Comment by sp614x** [comment]
Fixed in latest 1.19.4 preview.
