### ISSUE TITLE
[CRASH] Optifine Crashes Forge whenever i start it up

### ISSUE THREAD

**Issue by mariobrosmania** [sp614x/optifine#5586]
## Description of Issue
Minecraft Forge 1.14.4 crashes whenever I have optifine HD_U_G5 loaded into my mods folder. I can't figure out why its crashing

## Steps to Reproduce
1. run Minecraft forge with optifine installed
2. game crashes after fml early loading process

## OptiFine Version
1.14.4 HD_U_G5

## Installation Method
placed in mods folder

## Fabric/Forge Version
forge-1.14.4-28.2.23

## Other Installed Mods
mcw-bridges-1.0.5-mc1.14.4.jar Macaw's Bridges
GunMod-1.18.1.jar GunMod
useful_backpacks-1.14.4-1.7.6.60.jar Useful Backpacks 
BasicNetherOres-1.14.4-3.2.6.jar Basic Nether Ores
tombstone-4.3.6-1.14.4.jar Corail Tombstone
u_team_core-1.14.4-2.8.2.150.jar U Team Core
TheAbyss+3.6.6+1.14.4.jar TheAbyss
Wyrmroost-1.14.4-1.1.0.jar Wyrmroost
furniture-7.0.0-pre15-1.14.4.jar MrCrayfish's Furniture Mod
jei-1.14.4-6.0.1.30.jar Just Enough Items
CarryOn+MC1.14.4+v1.12.4.jar Carry On
Tardis-Mod-1.14.4-1.4.1.jar TARDIS Mod
Regeneration-1.14.4-4.0.8.jar Regeneration
Neat+1.5-19.jar Neat
Xaeros_Minimap_21.7.0_Forge_1.14.4.jar Xaero's Minimap
NetherEx-1.14.4-3.1.1.jar NetherEx
NoCubes-1.14.4-0.4.0-pre9.jar NoCubes
[1.14.4]+SecurityCraft+v1.8.21.1.jar SecurityCraft
LibraryEx-1.14.4-2.1.1.jar LibraryEx

## Log Files/Crash Reports
[crash-2021-04-22_02.30.20-client.txt](https://github.com/sp614x/optifine/files/6357249/crash-2021-04-22_02.30.20-client.txt)

**Comment by mindforger** [comment]
by the stack trace this is an issue for https://github.com/WhoCraft/Regeneration/

but 1.14 has not been done by the current mod owner and he outright "HATES" the old code
see last update message on that branch :) 
https://github.com/WhoCraft/Regeneration/tree/1.14.4/

**Comment by mariobrosmania** [comment]
oof and here i thought it was NoCubes because i removed that mod and minecraft started to work again. Thanks

**Comment by mindforger** [comment]
well cross mod interaction is not ruled out :D it was just the obvious hin in the crash log

**Comment by mariobrosmania** [comment]
Thanks so much for the help mindforger I'm going to see if I can figure this out so I can use the better version of no cubes. I'm going to close this now since my issue is basically solved. I hope you have a good day.
