### ISSUE TITLE
[Bug/Error Report] When i select an option, FPS go to zero.

### ISSUE THREAD

**Issue by Aquarware** [sp614x/optifine#5587]
## **I selected "Smooth FPS" option, but didn't went well at all**
I have a bad, but super bad PC, Celeron N2840, 2GB RAM 800mHz, iGPU, HDD, but i decided to play Minecraft, which is a "low spec" game. And i did my usuals at it, download version, install Forge, install OptiFine, configurate, play. But i put the option "Smooth FPS", that i were used to select when i played on another PC's. And suddenly, when i selected it. FPS went to a total zero, not even a change to one or some updates of the screen, and it seemed weird to me because i played with that option on another computers, with no troubles at all.

## **Steps of the Error**
1. What do you do...
2. ...to find this bug?: Just selected the option while i were in-game, and done. It happened, also out from game it happens nothing, i mean, on main screen, FPS keep as common.

## **OptiFine Version**
Ultra I7, and i don't remember exactly but i think it was HD M5.

## **Installation Method**
My launcher came with it, it was part of the versions list.

## **Log Files/Crash Reports**
I checked, there is not anything of matter for this on the logs.

## **F3 Debug Screenshot**
I tried to, but game didn't reacted. By the way, i disabled the option and now i play normally, but i had to report the bug/error.

## **Prior Testing**
If you've installed standalone:
- ¿Does this happen in Vanilla without OptiFine?: Never. Vanilla goes at 10FPS on my PC, OptiFine goes at 40-60.

## **Additional Information**
Well, nothing else to say, i use 1.8.9, my PC is shit, drivers are updated, and without the option im okay, by the way. I appreciate so much your work at this, if i could i'd tip you guys out, because i have been using this mod since 2014, and stills great.

**Comment by KaiAF** [comment]
Smooth FPS isn't really good for integrated GPUs. With how people talk about smooth fps, it really just gives worse results than it should. Really depends on the hardware. The best bet is to not use smooth fps.
