### ISSUE TITLE
[Shaders Bug] Shadows will flicker if cast from a chunk behind you

### ISSUE THREAD

**Issue by JasonHorkles** [sp614x/optifine#5588]
## Description of Issue
When using the Chocapic13_V9 shaders and the latest OptiFine preview, shadows will start to flicker and look all weird if cast from a chunk that's behind you

## Steps to Reproduce
1. Use the OptiFine preview
2. Activate the Chocapic13_V9 shaders (any quality)
3. Look around and see it start to happen (most visible by mountains)

## OptiFine Version
OptiFine HD U G8 pre12

## Installation Method
Standalone installer and using the jar in the Forge mods will both create the issue

## Log Files/Crash Reports
https://paste.gg/p/JasonHorkles/6a085bb8d7934cd58df9b63023ef0e4a

## F3 Debug Screenshot
![image](https://user-images.githubusercontent.com/51760372/115779818-ab937180-a375-11eb-9d97-fb47b64abf94.png)

## Prior Testing
- Does this happen in Vanilla without OptiFine? No

## Additional Information

[G7 (what it should look like)](https://youtu.be/l8is_ssS5xU)
[G8 pre12 (what's happening)](https://youtu.be/aRFRY_wRUvg)

**Comment by JasonHorkles** [comment]
This continues to happen on the stable G8 release

**Comment by sp614x** [comment]
This is caused by the fix of #5134.
The Chocapic13 shaders have to be updated to use the correct projection.

**Comment by sp614x** [comment]
A temporary fix is to disable shadow frustum culling in chocapic13 options: Shading -> Shadows -> Shadow Frustum Culling
