### ISSUE TITLE
Optifine 1.11.2 B7/8 drops fps

### ISSUE THREAD

**Issue by archiesholland** [sp614x/optifine#559]
Vanilla 1.11.2 gives great fps, but using Optifine 1.11.2 B7 or B8 drops fps to 10 or less.
Win10, Java 1.8, Intel HD Graphics 5500 / NVIDIA GeForce 920M.

**Comment by Ristovski** [comment]
Have you tried tweaking the OptiFine settings? OptiFine _should_ give some performance gain out-of-the-box but if you want anything further than that you will need to experiment with the settings yourself.

**Comment by archiesholland** [comment]
> OptiFine should give some performance gain out-of-the-box....
Yes, and it does - been using it for years - but this time, not.  I'll keep experimenting and post anything I discover.
