### ISSUE TITLE
Crash upon clicking anywhere during the loading screen, Minecraft 1.16.5 +  OptiFine HD U G7

### ISSUE THREAD

**Issue by SubatomicScale** [sp614x/optifine#5595]
## Description of Issue
It appears that upon clicking anywhere on the red "MOJANG" loading screen of Minecraft while in fullscreen, the game will freeze for a second or two, then forcibly close. The launcher reports a crash, but does not provide a crash log. 

## Steps to Reproduce
1. Install OptiFine HD U G7 for 1.16.5 
2. Set game to launch in full screen
3. Click anywhere during the red loading screen, sometimes one click will trigger it and sometimes you have to click rapidly. 
4. The game should freeze, then crash. 

## OptiFine Version
OptiFine HD U G7 for 1.16.5 is what I discovered this bug in, but it also occurs with OptiFine HD U G8 pre12.

## Installation Method
I used the included standalone installer to install OptiFine. 

## Log Files/Crash Reports
No crash reports are created, but I do have a crash log from this kind of crash on OptiFine HD U G8 pre12. 
https://pastebin.com/qUkbH6Ab

## F3 Debug Screenshot

![image](https://user-images.githubusercontent.com/80282292/116006802-7172db80-a5d2-11eb-9eea-91df5214b954.png)

## Prior Testing
This crash does not occur in Vanilla. 

## Additional Information
Occasionally, the game will crash even without clicking, but clicking seems to be the most surefire way of triggering it.

**Comment by KaiAF** [comment]
Whenever it crashes, can you send a crash report? The log you provided doesn't really give much information

**Comment by SubatomicScale** [comment]
> Whenever it crashes, can you send a crash report? The log you provided doesn't really give much information

[latest.log](https://github.com/sp614x/optifine/files/6410295/latest.log)

**Comment by KaiAF** [comment]
Interesting. Never seen that before, but looks like java itself is crashing. Looking it up, seems to be something related with user permissions?? 

> `EXCEPTION_ACCESS_VIOLATION (0xc0000005)`

Google shows this: 

> There is a possibility that the EXCEPTION_ACCESS_VIOLATION (0xc0000005) error when starting Minecraft could have occurred due to a conflict with Account Control in your Windows operating system. To test this probability, you need to disable User Account Control, and then try again to run Minecraft.

**Comment by SubatomicScale** [comment]
> Interesting. Never seen that before, but looks like java itself is crashing. Looking it up, seems to be something related with user permissions??
> 
> > `EXCEPTION_ACCESS_VIOLATION (0xc0000005)`
> 
> Google shows this:
> 
> > There is a possibility that the EXCEPTION_ACCESS_VIOLATION (0xc0000005) error when starting Minecraft could have occurred due to a conflict with Account Control in your Windows operating system. To test this probability, you need to disable User Account Control, and then try again to run Minecraft.
> 
> > `Problematic frame: V  [jvm.dll+0x2cd580]`
> 
> jvm is crashing

I disabled both UAC and reverted to the bundled version of Java, both of which didn't stop the crashes. I also noticed that this issue only occurs in fullscreen mode.

**Comment by Jiingy** [comment]
As Iris previously stated, the crash logs sent indecate that this is unrelated to OptiFine, but rather is an issue with either windows, or java. It's also never stated whether or not this happens with vanilla Minecraft aswell.

If this issue is still a problem for the original poster, it can be reopened.
