### ISSUE TITLE
Unloaded parts of the world 1.8.9 - M5

### ISSUE THREAD

**Issue by dairenhell** [sp614x/optifine#5596]
Sorry already wrote about this problem but in beta version. Now, on the actual M5, the problem with unloaded textures remains.
The error appears in 90% of the launches of the world. And this is repaired by re-entering the world.

![2021-04-18_21 23 14](https://user-images.githubusercontent.com/31137522/116116221-95fab080-a6c3-11eb-945a-14b3dd8b9931.png)
![2021-04-18_21 15 09](https://user-images.githubusercontent.com/31137522/116116226-972bdd80-a6c3-11eb-95f6-000cc49f7ede.png)
![2021-04-18_21 15 18](https://user-images.githubusercontent.com/31137522/116116230-985d0a80-a6c3-11eb-9baf-02f9a8bcd3d6.png)
![2021-04-18_21 15 25](https://user-images.githubusercontent.com/31137522/116116234-98f5a100-a6c3-11eb-9462-ecd5fedd5ef0.png)
![2021-04-18_21 23 11](https://user-images.githubusercontent.com/31137522/116116236-998e3780-a6c3-11eb-8f68-f48003ce6c83.png)

**Comment by Antoliper** [comment]
For me the same

**Comment by KaiAF** [comment]
Does this happen without the resource pack?

**Comment by dairenhell** [comment]
> Does this happen without the resource pack?

No 
I entered the world 5 times without a resource pack, there was no bug.
But when I entered with resource pack again and a bug appeared with loading part of the world, replacing the resource pack or disabling it removes the bug

**Comment by KaiAF** [comment]
Try disabling antisitropic filtering and antialiasing. That could help.
Or if that doesn't help, you can update to 1.8.9 M6 pre1 to see if that helps

**Comment by KaiAF** [comment]
Did disabling antisitropic filtering or antialiasing help? Was it resolved?
