### ISSUE TITLE
GPU Usage issue with shaders active

### ISSUE THREAD

**Issue by RafayK-code** [sp614x/optifine#5598]
Hey, I am using optifine with shaders right now, and for some reason, the GPU usage is inconsistent between the overworld and the nether.

While in the overworld, the GPU is barely used, at ~35% and in the nether, the GPU gets used to its full extent ~95%.

The issue can be recreated by travelling between the realms whilst using shaders.

I am using BSL shaders.

**Comment by KaiAF** [comment]
This seems to be normal, not an actual issue.
