### ISSUE TITLE
World-embedded resources (resources.zip inside a world folder) doesn't work when OptiFine is activated via Forge

### ISSUE THREAD

**Issue by wbxshiori** [sp614x/optifine#56]
World-embedded resources (resources.zip inside a world folder) doesn't work
Affecting versions for Minecraft 1.8 and 1.8.9.

It's a vanilla feature added in Minecraft 14w07a (1.8), which allows specified resources(sounds, textures, etc) be embedded into a world folder.
During OptiFine being active, resources.zip will NOT be loaded. (For example, narrations in Alice's Wonderland by rsmalec)
Currently, the only way I know to load resources.zip normally is to deactivate/remove OptiFine.

**Comment by sp614x** [comment]
Testing OptiFine H4 for 1.8.9 - the resources are loaded (signs are white), sounds work
Testing OptiFine B2_pre for 1.9.2 - the resources are loaded (signs are white), sounds do not work. 
In Minecraft 1.9 the "playsound" command has been changed, it requires a new parameter "source": http://minecraft.gamepedia.com/Commands#playsound
The world has to be updated for 1.9 in order the sounds to work.

**Comment by wbxshiori** [comment]
The bug is still present on certain conditions.  The embedded resources will not be loaded if optifine is activated through forge.  Only using optifine installer will work normally.  There are people using optifine with other mod more than using optifine only, so this bug affects much.

**Comment by sp614x** [comment]
To be tested with Forge + OptiFine on 1.8.9.

**Comment by sp614x** [comment]
Fixed, coming in preview H6.

**Comment by wbxshiori** [comment]
1.9 B1 has the same problem working with Forge 1.9 - 12.16.0.1865.  Will it get fixed too?
I added argument "music" into the command block myself, and now it works on both vanilla 1.9 and Optifine only enviroment.  
Although Forge 1.9.2 is yet to out, maybe you also need to prepare the solution for 1.9.2 B1.

**Comment by sp614x** [comment]
Versions 1.8, 1.8.8, 1.9 and 1.9.2 will be updated too.

**Comment by sp614x** [comment]
Updated previews 1.8, 1.8.8 and 1.9. 
Version 1.9.2 will be updated when 1.9 B2 is released.
