### ISSUE TITLE
[Bug]Problems with getting block alias

### ISSUE THREAD

**Issue by amandexspeed** [sp614x/optifine#5601]
## Description of Issue
Optifine crashes with some modded blocks in getting block allias

## Steps to Reproduce
1. Use some mods

## OptiFine Version
G8 Preview 1.16.5

## Installation Method
It's in mods folder

## Forge Version
36.1.2 1.16.5

## Other Installed Mods
               forge-1.16.5-36.1.2-client.jar                   
               Minecraft 1.16.5              
		Lucky-Block-Mod-1.16.4.jar  
		useful_backpacks-1.16.4-1.11.6.87.jar     
		repurposed_structures-1.16.4-2.3.1.jar
		more+recipes+mod+1.16.4.jar 
		EU_1.16.5_1.0.3.jar Easy Updates   
		Craftable+Elytras+Mod+1_16_x.jar 
		jei-1.16.4-7.6.1.65.jar 
		Falling-Tree-Mod-1.16.4.jar  
		DoggyTalents-1.16.5-2.0.1.4.jar    |
		coffee-mod_1.16.4-1.1.1.jar  |Coffee mod  
		car-1.16.5-1.0.5.jar |Ultimate Car Mod (**Pay attencion in that mod)**
		plane-1.16.5-1.0.0.jar  |Ultimate Plane Mod **(Pay attencion in that mod)**
		caelus-forge-1.16.5-2.1.3.0.jar 
		RingsOfAscension-1.16.4-1.6.0.jar 
		curios-forge-1.16.5-4.0.5.0.jar  
		obfuscate-0.6.0-1.16.3.jar   
		vehicle-mod-0.45.2-1.16.3.jar  |MrCrayfish's Vehicle Mod
		Curio-Of-Undying-Mod-1.16.5.jar   
		Uncrafted-1.16-4.0.0pre1.jar  
		guardvillagers-1.16.4-1.1.10 .jar
		u_team_core-1.16.4-3.1.17.192.jar 
		MyFirstMod 1.16.4.jar (I made that mod)
		simpleplanes-1.16.3-3.2.0.3.jar |Simple Planes 
		cfm-7.0.0-pre19-mc1.16.3.jar  |MrCrayfish's Furniture Mod
		curiouselytra-forge-1.16.5-4.0.2.3.jar 
		Craftable+[7.0].jar  
		walljump-forge-1.16.4-1.3.7.jar  
		cloth-config-4.10.13-forge.jar  
		inventorypets-2.0.12.jar 
		Fallout+Inspired+Power+Armor+raider+hotfix+1.16.ja
		BetterPvP_21.4.5_Forge_1.16.5.jar
		forge-1.16.5-36.1.2-universal.jar 
		goprone-1.16.4-1.3.5.jar  
		MoreCraftingTables+-+1.16.4.jar   
		CosmeticArmorReworked-1.16.5-v1b.jar   
		controllable-0.11.0-mc1.16.3.jar 
		cgm-1.0-1.16.4.jar |MrCrayfish's Gun Mod 
		GameMenuModOption-1.16.4-1.4.jar
		SuperTools-1.1.jar
		emotecraft-0.12.4_for_MC1.16.2+.jar
		lootbagmod-1.16.5-1.6.6.jar 
		dungeons_gear-1.16.4-3.0.6.jar  
		smarthud-1.1-1.16.3.jar  
(Pastebin was in maintenance)
## Log Files/Crash Reports
[crash-2021-04-28_10.12.34-client.txt](https://github.com/sp614x/optifine/files/6392225/crash-2021-04-28_10.12.34-client.txt)

## Additional Information
The developer of the mods that it's marked with (Pay attencion in that mod) wants help to fix his mods

**Comment by KaiAF** [comment]
Are you able to find the mod that is causing this issue? 
Split your mods into two groups and disable one group and then do this until you find the mod that is causing the crash.
