### ISSUE TITLE
Optifine problem

### ISSUE THREAD

**Issue by kakakakuts** [sp614x/optifine#5602]
Hello, i have been having problems with the 1.8.9 optifine versions. The optifine HD I7 mod is working kinda bad. Basically the mod would give me a mouse acceleration problem but when the optifine mod is removed the is no problem. And the second problem is that only I7 version of optifine is working, i have tried all of them and it would just crash mid loading.

Here is the Crash Log: https://paste.ee/p/1XjbA

**Comment by KaiAF** [comment]
update the optifine version to M5 or M6 pre 1. This could fix it
