### ISSUE TITLE
Playermodels doesn't work

### ISSUE THREAD

**Issue by SuperIsakSwahn** [sp614x/optifine#5603]
## Description of Issue
i'm making a player model using blockbench, and it just doesn't work. Its in the playermodels folder (in the .minecraft folder) and I have the users and items, and im pretty sure I did what the tutorial told me to, I even downloaded their example models yet it still doesn't work. I'm using optifine, and i got the weird jvm arguement that you need.

## Steps to Reproduce
Everything explained up there

## OptiFine Version
1.16.1 HD U G5

## Installation Method
I used the installer

## Other Installed Mods
Only optifine. Uno optifine

**Comment by ewanhowell5195** [comment]
playermodels work fine you most likely havent set it up correctly

**Comment by SuperIsakSwahn** [comment]
you guys are hella stupid lmao

**Comment by Ari-RERA-43** [comment]
If anyone knows what they are talking about when it comes to resource packs and related features like player models, Ewan does.

**Comment by SuperIsakSwahn** [comment]
If thats what you believe ig
