### ISSUE TITLE
[CIT] Would like to be able to override model-specified textures with CIT

### ISSUE THREAD

**Issue by PixelatedVolume** [sp614x/optifine#5604]
I've created a model for a shield and I'd like to be able to use that model with several different textures.  Right now, if an item's custom model includes a texture, it can't be overridden with CIT `texture= `.

I could make a new model extending the base shield model for each texture I'd like to apply, and specify the textures in each of those, but it seems to break the pattern expected from CIT .properties files and would mean I have to clutter up my pack with both properties and model .json files that don't feel necessary.

This might be a pointless quibble but it would really make my life a lot easier if CIT .properties files took priority over what's given in the custom model file.

Thanks!

**Comment by Cart3r1234** [comment]
You can do this with parent models.  A few of my packs do exactly what you are talking about by including both a model= and texture= line in the .properties file, and they work fine as long as the model is either a parent model or doesn't have an assigned texture.

**Comment by PixelatedVolume** [comment]
Do you have an example you could show me?  I don’t know what you mean by parent model other than “something another model extends” and that doesn’t really make sense for this. 

Also I’ve tried not specifying a texture in the model file, which for my custom shield always causes it to appear with the magenta and black texture error.  Models descended from `builtin/item` don’t have that problem, but my shield model files that includes new elements do.

**Comment by KaiAF** [comment]
Going to close this issue as it doesn't seem to be an actual bug report. You can go to our Discord server if you would like to learn how to do this. https://optifine.net/discord.
