### ISSUE TITLE
[Bug] Minecraft world creation freezes the game.

### ISSUE THREAD

**Issue by GlitchSprite** [sp614x/optifine#5607]
## Description of Issue
Whenever I try to make a new world with OptiFine active, the game will freeze at either 0% or 100%. If I use task manager to end minecraft's process, the fully generated world will be there.

## Steps to Reproduce
1. Use Optifine on 1.16.5 
2. Create world

## OptiFine Version
OptiFine_1.16.5_HD_U_G7

## Installation Method
I have two installations of OptiFine, one on forge for playing mods, and one standalone install to play vanilla. 
This problem occurs on both of them.

## Fabric/Forge Version
Forge

## Other Installed Mods
Immersive Portals and Create.

## Prior Testing
- Does this happen in Vanilla without OptiFine?
- no
- Does this happen in OptiFine standalone?
- yes
- Does this happen in Forge with OptiFine?
- yes
- Have you tried using a binary search to find which mods cause this issue?
- no

**Comment by KaiAF** [comment]
What is your hardware? Could be something related to that?

**Comment by GlitchSprite** [comment]
It's an IdeaPad S145-15AST with a AMD A6 RADEON R4 processor.
It has 4gigs of ram, and is 64-bit.
Hope this helps!

**Comment by GlitchSprite** [comment]
...

**Comment by KaiAF** [comment]
This most likely isn't an optifine bug. It could easily be something hardware. For general support you can email us (With better response time) at optifinex@gmail.com. Or you can go to our Discord support channel. https://optifine.net/discord.
