### ISSUE TITLE
Fov becomes very small with dynamic Fov on

### ISSUE THREAD

**Issue by uhhhggg** [sp614x/optifine#5608]
When I turn on dynamic Field of view my field of view becomes very small. At higher speeds this can result in being too far zoomed in to actually see anything

**Comment by KaiAF** [comment]
Can you provide more information? i.e. screenshots

**Comment by uhhhggg** [comment]
Minecraft version is forge 1.12.2 14.23.5.2854 optifine version is 1.12.2 HD_U_F5 and i am playing with mods

**Comment by CrazyWords1** [comment]
> 
> 
> Minecraft version is forge 1.12.2 14.23.5.2854 optifine version is 1.12.2 HD_U_F5 and i am playing with mods

List of mods, and what a dynamic fov?

**Comment by uhhhggg** [comment]
i was trying to place a folder containing all of my mods but github will not allow files that exceed 10MB in size

**Comment by uhhhggg** [comment]
[Mods (1).zip](https://github.com/sp614x/optifine/files/6422543/Mods.1.zip)

**Comment by uhhhggg** [comment]
thats not all of them btw

**Comment by uhhhggg** [comment]
[New WinRAR ZIP archive (2).zip](https://github.com/sp614x/optifine/files/6422656/New.WinRAR.ZIP.archive.2.zip)
[New WinRAR ZIP archive (3).zip](https://github.com/sp614x/optifine/files/6422662/New.WinRAR.ZIP.archive.3.zip)
[New WinRAR ZIP archive (4).zip](https://github.com/sp614x/optifine/files/6422675/New.WinRAR.ZIP.archive.4.zip)

**Comment by uhhhggg** [comment]
[New WinRAR ZIP archive (2).zip](https://github.com/sp614x/optifine/files/6422685/New.WinRAR.ZIP.archive.2.zip)
[New WinRAR ZIP archive (2).zip](https://github.com/sp614x/optifine/files/6422691/New.WinRAR.ZIP.archive.2.zip)
[New WinRAR ZIP archive (3).zip](https://github.com/sp614x/optifine/files/6422707/New.WinRAR.ZIP.archive.3.zip)

**Comment by uhhhggg** [comment]
[New WinRAR ZIP archive (4).zip](https://github.com/sp614x/optifine/files/6422727/New.WinRAR.ZIP.archive.4.zip)
[New WinRAR ZIP archive (5).zip](https://github.com/sp614x/optifine/files/6422734/New.WinRAR.ZIP.archive.5.zip)

and the last mod i have installed is techguns

**Comment by uhhhggg** [comment]
[New WinRAR ZIP archive.zip](https://github.com/sp614x/optifine/files/6422781/New.WinRAR.ZIP.archive.zip)
[New WinRAR ZIP archive.zip](https://github.com/sp614x/optifine/files/6422791/New.WinRAR.ZIP.archive.zip)

**Comment by uhhhggg** [comment]
and i have techguns installed too
latest version
and why github refuses to allow files over 10MB i dont know, and i dont care but i DO think that they should get rid of that limit

**Comment by KaiAF** [comment]
Judging since there are multiple folders filled with mods, I would think that this would be caused by another mod. Not OptiFine. Does this happen without all the other mods but with only optifine?

Dynamic FOV should look like this: https://streamable.com/6uhi76

**Comment by uhhhggg** [comment]
hmm
i think there might be a few missing so im going to try something

**Comment by uhhhggg** [comment]
https://mega.nz/fm/H6g1FQAZ
This should be a link to a mega folder with all of my mods

**Comment by uhhhggg** [comment]
also i thought that it was probably some other mod as well but i was hoping that someone would be able to help me narrow it down

**Comment by mindforger** [comment]
while ingame, press and hold f3 + c until your game crashes, them open the crashlog (not the game log) and paste it on pastebin. Then post the link here. This is both safe and well readable for everyone and shows all relevant infos

**Comment by uhhhggg** [comment]
Closed because after removing my mods and then putting them back in somehow i no longer zoom in with dynamic fov. very strange
