### ISSUE TITLE
[Category] Short description

### ISSUE THREAD

**Issue by MinecrafterSH1** [sp614x/optifine#5611]
## Description of Issue
 On 1.8.9 with Optifine I get an error when i try to play on multiplayer "java.netConnectionException: Connection timed out: no further information". I tried after to go on normal version of 1.8.9 (without Optifine) and works fine. Please I need help

## Steps to Reproduce
1. What do you do...
2. ...to find this bug?

## OptiFine Version
1.8.9

**Comment by KaiAF** [comment]
I am not sure how OptiFine would be causing this issue? Would you be using any pvp client, or any other mods? Is this issue even still happening?

**Comment by MinecrafterSH1** [comment]
Yes, I still have this issue but it works on singleplayer.I do not have any
mods excepting optifine.

lun., 31 mai 2021, 05:18 Iris ***@***.***> a scris:

**Comment by KaiAF** [comment]
I am not really sure how to help you. I do not know what would be causing this, and it seems like you are the only person who is experiencing it. Very interesting. Sorry that I can't help you
