### ISSUE TITLE
[Bug] Scoreboard flickers when lazy chunk loading is enabled

### ISSUE THREAD

**Issue by Pugabyte** [sp614x/optifine#5615]
## Description of Issue
I use [lucko/helper](https://github.com/lucko/helper/)'s [packet based scoreboard API](https://github.com/lucko/helper/tree/master/helper/src/main/java/me/lucko/helper/scoreboard) to [display a sidebar to my users](https://github.com/Pugabyte/Nexus/blob/master/src/main/java/me/pugabyte/nexus/features/scoreboard/ScoreboardCommand.java), and we noticed that users with optifine installed and lazy chunk loading enabled have very glitchy scoreboards, lots of flickering. I have not tested with bukkit's scoreboard API.

## Steps to Reproduce
- Install the latest 1.16.5 optifine on a vanilla client
- Enable lazy chunk loading in the performance screen
- Connect to server `bnn.gg`
- Observe flickering on scoreboard
- Disable lazy chunk loading 
- Observe no flickering on scoreboard

## OptiFine Version
![image](https://user-images.githubusercontent.com/12417961/116934131-8a166d80-ac32-11eb-979b-4483d82bee0e.png)

## Installation Method
**Both** fabric (optifabric) and standalone installations are known to be affected

## Fabric/Forge Version
![image](https://user-images.githubusercontent.com/12417961/116934209-a914ff80-ac32-11eb-94df-92560163d3e5.png)

## OptiFabric Version
![image](https://user-images.githubusercontent.com/12417961/116934254-b631ee80-ac32-11eb-9354-048ae8974b87.png)

## Other Installed Mods
![image](https://user-images.githubusercontent.com/12417961/116934310-d06bcc80-ac32-11eb-80c3-322e222f823e.png)

## F3 Debug Screenshot
![image](https://user-images.githubusercontent.com/12417961/116934655-3fe1bc00-ac33-11eb-9df7-2fc58949e394.png)

**Comment by sp614x** [comment]
Should be fixed in the G8 preview.
