### ISSUE TITLE
[Category] Short description

### ISSUE THREAD

**Issue by octooli** [sp614x/optifine#5616]
## Steps to Reproduce
1. What do you do...im not sure
2. ...to find this bug? im still not sure

## OptiFine Version
hdu_m5 1.8.9

## Installation Method
from optifine website

## Other Installed Mods
none 

## Log Files/Crash Reports
none

none

## Additional Information
So the issue is that when i load into a game it will be fine for like a minute then it will start flickering 

https://user-images.githubusercontent.com/83660637/117032810-b34e0100-acf9-11eb-8d57-2759affc7dd3.mp4

**Comment by KaiAF** [comment]
Can you provide more information? Like does it only happen when you are on that menu? What is the resource pack (or shader if you are using one)? Maybe it could be outdated hardware / drivers?

**Comment by octooli** [comment]
> Can you provide more information? Like does it only happen when you are on that menu? What is the resource pack (or shader if you are using one)? Maybe it could be outdated hardware / drivers?
ive tried everything it still happens without a texture pack this pc is only a few months old

**Comment by Jiingy** [comment]
Closing this issue as it does not provide any information that could be used to troubleshoot.
