### ISSUE TITLE
[Crash] Optifine crashes the game on Forge 1.16.5

### ISSUE THREAD

**Issue by HenrikoMagnifico** [sp614x/optifine#5617]
## Description of Issue
Optifine crashes when loaded as a Forge mod on 1.16.5

## Steps to Reproduce
* Use Java 8 1.8.0_291 and Forge for 1.16.5 (1.16.5-36.1.16)
* Place Optifine 1.16.5_HD_U_G7 in the mods folder.
* Start the game.

## OptiFine Version
OptiFine_1.16.5_HD_U_G7

## Installation Method
JAR into the mods folder

## Fabric/Forge Version
Forge 1.16.5-36.1.16

## Log Files/Crash Reports
[crash-2021-05-04_21.24.05-client.txt](https://github.com/sp614x/optifine/files/6423470/crash-2021-05-04_21.24.05-client.txt)

## Prior Testing
The issue occurs no matter what I do.

**Comment by KaiAF** [comment]
Weird, it doesn't really look like optifine is the one that is causing the crash. Could be another mod? Kind of looks likei it's actually forge itself
