### ISSUE TITLE
[Better Snow]  certain non-full blocks should have Better snow with them

### ISSUE THREAD

**Issue by apicella1** [sp614x/optifine#5626]
It seems like that there's some blocks that have forgotten or missed the chance to have Better Snow with them.  
Especially those in the last updates.  but the ones I wanted to make note of certain ones such as:
Torches, Banners, Signs,  End rods, and Tripwire Hooks.  

These blocks and the ones waiting since their update release, have been in limbo for a while and I just wanted to shine some light on this problem.

**Comment by Regnander** [comment]
Torches and End Rods [melts any surrounding snow](https://minecraft.fandom.com/wiki/Snow#Melting) while Banners and Signs are tile entities which according to sp614x ["currently can't use better snow"](https://github.com/sp614x/optifine/issues/2015#issuecomment-439714233).

**Comment by KaiAF** [comment]
Closing this as sp614x already said that these wouldn't get implemented
