### ISSUE TITLE
[Dynamic Lights] Add Glow Berries, Glow Ink Sac, and Glow Item Frames

### ISSUE THREAD

**Issue by Jiingy** [sp614x/optifine#5628]
## Description of the new feature
Glow Item Frames and Glow Ink Sacs come from the glow squid which is planned to have dynamic lighting, and glow berries emit light when grown.

**Comment by apicella1** [comment]
and Glow Lichen

**Comment by apicella1** [comment]
> Would also like to add on the idea of placed Glow Item Frames also emitting light, although this could possibly be confusing to the player as they may think that it actually changes in-game light.

I think This One may be a bit too much as it Takes over what the Glow item frame was meant to show off in general, It's just supposed to glow, not to illuminate.

**Comment by Jiingy** [comment]
> I think This One may be a bit too much as it Takes over what the Glow item frame was meant to show off in general, It's just supposed to glow, not to illuminate.

To be fair though, technically it's the same case for the glowsquid

**Comment by Jiingy** [comment]
Added
