### ISSUE TITLE
Optifine FOV changes.

### ISSUE THREAD

**Issue by MyNameIsLaugher** [sp614x/optifine#563]
Hello, I have an issue involving the use of Optifine. Whenever I sprint in normal vanilla my FOV changes a little bit, but with any version of Optifine that I install and run my FOV never changes. If anyone knows how to fix this please reply to this thread, thank you very much!

**Comment by iRo4DRunn3R** [comment]
i have the same issue please help

**Comment by iRo4DRunn3R** [comment]
i reseted video setting by mistake and now its like it doesnt work! i dont get the fps boost i was getting and my FOV never changes

**Comment by Builderb0y** [comment]
Video settings > dynamic FOG > on.

**Comment by MyNameIsLaugher** [comment]
Omg, thank you so much Builderb0y, you saved me a lot of stress.
