### ISSUE TITLE
game crashes at some points of the World

### ISSUE THREAD

**Issue by XenoxYT** [sp614x/optifine#5630]
## Steps to Reproduce
1. Fly a bit around in the MC World
2. And wait for the crash

## OptiFine Version

Optifine G9 21w08 Pre2

## Installation Method

Standalone

## Log Files/Crash Reports
 
[crash-2021-05-08_14.04.26-client.txt](https://github.com/sp614x/optifine/files/6445826/crash-2021-05-08_14.04.26-client.txt)

## F3 Debug Screenshot

![Badlion Client Screenshot 2021 05 08 - 14 18 31 64](https://user-images.githubusercontent.com/78287711/117538943-62475100-b008-11eb-86b3-c4d6124ce5b3.png)

**Comment by KaiAF** [comment]
Update to the recent version of snapshot previews. I believe this bug was already fixed
