### ISSUE TITLE
Add Discord Rich Presence

### ISSUE THREAD

**Issue by Peppy8651** [sp614x/optifine#5636]
Apparently, Discord doesn't recognize when Optifine is open and doesn't set your game activity as Minecraft.  Currently, the only way to set your game activity as Minecraft while Optifine is open is to go into your game activity settings and manually set it yourself. However, you have to repeat this every time you open the game, making it very inconvenient. A more convenient and automatic way would be to add support for Discord Rich Presence. This would update the activity from Optifine instead of having the player change their activity manually. To add Discord Rich Presence, you can use this [file from Discord](https://dl-game-sdk.discordapp.net/2.5.6/discord_game_sdk.zip). However, you would need to make or use a library for it to work in Java. It could be a small but significant enhancement to the mod. Preferably, the activity could look like the game activity used when Discord detects vanilla Minecraft.

**Comment by sp614x** [comment]
Discord detects Minecraft by the launch arguments, not via a library.
Can't be fixed by OptiFine.

**Comment by Peppy8651** [comment]
Not sure why this is closed. Discord doesn't detect Optifine normally, but you can use the rich presence to add an activity so it's like the game is detected and shows the activity.

**Comment by Peppy8651** [comment]
Here's an example of a custom activity created using Rich Presence:

![image](https://user-images.githubusercontent.com/73673342/118313362-41737580-b4b8-11eb-912b-65306b292907.png)

**Comment by Peppy8651** [comment]
Nevermind, I found a fix. https://github.com/sp614x/optifine/issues/5351 use this to fix the thing and trick Discord into detecting Optifine as vanilla Minecraft.
