### ISSUE TITLE
[BUG] Seeing Chests & Signs through walls.

### ISSUE THREAD

**Issue by Silverhand1317** [sp614x/optifine#5639]
## Description of Issue
Upon installing OptiFine HD U G7 and dragging It Into my minecraft mods folder, whilst opening minecraft with 1.16.5, I load up onto my server and I can see through walls and see things like beds, signs, banners and chests.

## Steps to Reproduce
1. I don't know, install OptiFine HD U G7 with Forge and joining a server.

## OptiFine Version
OptiFine HD U G7

## Installation Method
I dropped the .jar file Into my mods folder.

## Fabric/Forge Version
Forge

## Other Installed Mods
Xaero's Minimap - https://chocolateminecraft.com/minimapdownload.php (top, 1.16.5 and select mirror instead of the .jar)
Gun Mod - https://www.curseforge.com/minecraft/mc-mods/mrcrayfishs-gun-mod
Space Bosstools - https://www.curseforge.com/minecraft/mc-mods/space-bosstools/files
Obfuscate https://www.curseforge.com/minecraft/mc-mods/obfuscate/files
Create - https://www.curseforge.com/minecraft/mc-mods/create
Mrcrayfish's Vehicle Mod - https://www.curseforge.com/minecraft/mc-mods/mrcrayfishs-vehicle-mod
Corpse -  https://www.curseforge.com/minecraft/mc-mods/corpse
Curios Api - https://www.curseforge.com/minecraft/mc-mods/curios
Mrcrayfish's Furniture Mod - https://www.curseforge.com/minecraft/mc-mods/mrcrayfish-furniture-mod/download/3081350
Economy Inc - https://www.curseforge.com/minecraft/mc-mods/economy-inc/files

## Log Files/Crash Reports
N/A

## F3 Debug Screenshot
![image](https://user-images.githubusercontent.com/84103608/118043747-d5452480-b386-11eb-9114-b882bd8d4faa.png)

## Prior Testing
- Does this happen in Vanilla without OptiFine? No.

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? Yes.
   - Only OptiFine and Forge
   - Only OptiFine, OptiFabric, and Fabric
- Does this happen without any mods at all? No.
   - Only Forge/Fabric by itself.
- Does this happen in OptiFine standalone? No.
- Does this happen in Vanilla without OptiFine? No.
- Have you tried using a binary search to find which mods cause this issue? No.
   - To find conflicting mods, split your mods into 2 groups (not including OptiFine/OptiFabric, obviously). Remove one group, and test in-game. Keep the group that has the problem, and repeat until no more mods can be removed without the issue disappearing.
   - Does the issue still happen with only the remaining mods installed? No.
      - Forge/Fabric and remaining mods, without OptiFine -->

**Comment by KaiAF** [comment]
Could you send a F3 debug menu screenshot?
