### ISSUE TITLE
[1.16.5] Startup time grossly extended

### ISSUE THREAD

**Issue by MarioSMB** [sp614x/optifine#5645]
## Description of Issue
This is an issue I've noticed going on for some time; with OptiFine installed, startup times are more than doubled in modded environments. Timing results are below.

## Steps to Reproduce
1. Install OptiFine
2. Launch the game with a timer running, measure the difference without

## OptiFine Version
HD_U_G7

## Installation Method
Dropped the .jar file into the "mods" folder

## Fabric/Forge Version
Forge

## Other Installed Mods
https://paste.ubuntu.com/p/c5ppNnc6Tg/

## Log Files/Crash Reports
If it's at all relevant, here's the startup log: 
[latest.log](https://github.com/sp614x/optifine/files/6483339/latest.log)

## Prior Testing
I've performed some measurements based on when the game window first appears until the main menu is displayed:  
- 13.03 No OptiFine or other mods (only Forge installed)
- 17.10 Only OptiFine and Forge
- 1:43.87 Modded setup with OptiFine
- 51.99 Modded setup without OptiFine
All these tests were performed on the same hardware, with the game installed on a M.2 SSD.

**Comment by KaiAF** [comment]
I believe this is normal, not entirely sure if it would be considered an issue. But I would still label it just incase.

**Comment by MarioSMB** [comment]
For what it's worth, slowdowns in the game are as much an issue as any bug, perhaps this might have existed long enough to be considered the norm.
If I understand correctly, OptiFine is reloading all the resources at a later stage of the startup process, hence the effectively doubled loading time. If there were a way to prevent Forge from performing an initial load of all the resources or to include OptiFine at that stage, that would bring it down to almost on par with vanilla (non-OptiFine) loading times.

**Comment by sp614x** [comment]
OptiFine processes all textures that are loaded, checks and fixes their dimensions and contents depending on the current settings.
I suppose the mods are adding a lot of new textures and animations and they all have to be processed and fixed.
Without mods the loading time increases with 30%, with mods it increases with 100%, which is probably normal.
