### ISSUE TITLE
[Multiplayer] Blocks don't load

### ISSUE THREAD

**Issue by BugsAreBad** [sp614x/optifine#5649]
## Description of Issue

When I join Servers, the blocks won't load, until I break/place one, but the players and NPCs load. After breaking a block, only the Blocks in the chunk loads but the other chunks seem empty. The Hitbox (Outline) from Blocks still shows when i aim at them. Also changing Resourcepacks doesn't finish and I have to close Minecraft in the Loadingscreen.
## Steps to Reproduce
1. I open Minecraft 1.16.4/1.16.5 with Optifine 
2. I join Servers like Hypixel
3. I don't see Blocks

## OptiFine Version
1.16.4 HD U G5

## Installation Method
Standalone Installer, mod (in lunarclient)

## Log Files/Crash Reports
[latest.log](https://github.com/sp614x/optifine/files/6493899/latest.log)

## F3 Debug Screenshot
![2021-05-17_14 21 03](https://user-images.githubusercontent.com/84326766/118493078-0031ce80-b721-11eb-854c-ea6ba3ef8cbf.png)

## Prior Testing

This does not happen in Vanilla

## Additional Information
none

**Comment by KaiAF** [comment]
Try updating the OptiFine version. I believe this was fixed in a later version
