### ISSUE TITLE
Optifine

### ISSUE THREAD

**Issue by iRo4DRunn3R** [sp614x/optifine#565]
whenever i download a new optifine version and click on PLAY the minecraft launcher crushes and when the game starts nothing happens. i dont get the fps boost i was getting and my FOV doesnt change! is it because i reseted my minecraft video setting this morning? everything started when i did this

**Comment by Ristovski** [comment]
Please don't create duplicate issues (#564).

This is normal behavior - resetting the video settings also resets the OptiFine settings to default. You will need to tweak the OptiFine settings again for any performance gain.

**Comment by iRo4DRunn3R** [comment]
so how do i tweak the Optifine setting again?

**Comment by sp614x** [comment]
Go to "Options -> Video Settings" and configure the settings as you wish.
