### ISSUE TITLE
[Shaders] Minecraft freezes using Kappa v4.1 E1

### ISSUE THREAD

**Issue by FlatJim** [sp614x/optifine#5653]
## Description of Issue
Loading into any world using the Kappa v4.1 E1 shaderpack will cause the game to freeze. Shaderpack was zipped and unmodified. As far as I've tested, it doesn't happen with any other shaderpack.

## Steps to Reproduce
1. Open Minecraft and load Kappa_v4.1_E1.zip 
2. Load into any singleplayer or multiplayer game

## OptiFine Version
1.16.5 G8 pre12

## Installation Method
Standalone

## Log Files/Crash Reports
https://ghostbin.co/paste/p2cr
^ log

## F3 Debug Screenshot
![2021-05-19_21 39 01](https://user-images.githubusercontent.com/67615785/118806654-b09efe80-b8ea-11eb-9e50-4e70d16d42b3.png)
screenshot taken with kappa v4.0 loaded, for obvious reasons

## Prior Testing
I'm reporting this for a standalone install, but I previously tried it using Optifabric, and quite a lot of mods ([here is a list](https://ghostbin.co/paste/ak2tph)), which made my whole PC freeze. Doing this made it briefly show an error message mentioning something about the application trying to access unavailable memory. This doesn't happen when using the standalone install, instead the game window can be alt-tabbed out of easily on Windows and closed using task manager.

## Additional information
Using AMD driver version 20.4.2

**Comment by KaiAF** [comment]
If it's giving you an error mentioning it couldn't access unavailable memory, probably allocating more memory could help.

**Comment by KaiAF** [comment]
Closing the ticket as it seems like it's not an issue with optifine.
