### ISSUE TITLE
[Animations] Make Every Entity Compatible With Render Parameters Like "Limb_Speed"

### ISSUE THREAD

**Issue by Xerehm** [sp614x/optifine#5659]
I am trying to make my custom boat model have wheels that spin at the speed of the boat. I have found that the parameter "limb_speed" does not work with boats and find it strange.

I would like to know if this could be implemented or not.

![2021-05-20_23 58 59](https://user-images.githubusercontent.com/57718861/119054111-62136200-b9c7-11eb-9ec7-4521f6b17782.png)

**Comment by 0verC0der** [comment]
Did you solve that problem? Cause i have same (On pic is my boat model)
![image](https://user-images.githubusercontent.com/90970704/177279543-d9c68813-2ddf-4fab-be00-180ee6ce4e26.png)

**Comment by 0verC0der** [comment]
"animations": [
				{
					"front_right.ry": "(paddle_right.ry - 136) * 60",
					"lear_right.ry": "(paddle_right.ry - 136) * 60",
					"front_left.ry": "(paddle_right.ry - 136) * 60",
					"lear_left.ry": "(paddle_right.ry - 136) * 60"
				}
			]
		},

Try this case!

**Comment by sp614x** [comment]
The "limb_speed" parameter is only available for mobs as only they have limb movement.
The existing parameters "move_forward" and "move_strafing" could be implemented for all entities.

**Comment by sp614x** [comment]
Fixed in pre8, added CEM parameter "limb_swing" for boat and minecart.
