### ISSUE TITLE
1.10.2 U-D7 Vanilla glass Tesselating block model

### ISSUE THREAD

**Issue by braingkk** [sp614x/optifine#566]
have had multiple crashes with the header 
"java.lang.NullPointerException: Tesselating block model"
one was a block of glass with a botania floating flower above it
https://pastebin.com/3n6ndBWd
as well as when using architecturecraft blocks skinned to look like glass
https://pastebin.com/xrETNDtp

both were fixed by removing the affected blocks.
playing FTB Beyond with shaders and the "32x32 default" resource pack

**Comment by lemonyslash** [comment]
I started experiencing this issue error as well. It occurred when I placed a block on top of a Ender IO conduit. I can only get the game to stop crashing by removing Optifine.

https://pastebin.com/bjbbzxYv

**Comment by braingkk** [comment]
2 workarounds for now:
it seems to be triggered by proximity to an oak log in your case, try breaking it and then putting optifine back in. good to know that im not the only one who experienced this tho.

your other option is to disable connected textures in optifine, as this is a connected textures issue.

**Comment by lemonyslash** [comment]
Ah, I see. I'll give that a go here in a bit and report back. Thanks.

**Comment by lemonyslash** [comment]
Yep, disabling connected textures did the trick. Thanks!
