### ISSUE TITLE
Extremely low FPS

### ISSUE THREAD

**Issue by BleepFTB** [sp614x/optifine#5660]
Hello, recently purchased an asus tuf a15 with ryzen 5 4800, 8GB ram and GTX 1660TI. 
Using vanilla minecraft i can achieve 100 fps, using optifnine the max i can achieve is 30.
Using fabric i am able to achieve 200+

please help me troubleshoot the issue. Thanks

**Comment by sp614x** [comment]
You can try Options -> Video Settings -> Other -> Reset Video Settings

**Comment by sp614x** [comment]
If you are using a resource pack OptiFine can recognize and use much more resource pack features which may lower the FPS.
You can also try the options in Performance menu, for exmaple Render Regions, Fast Render and Smart animations.
