### ISSUE TITLE
[Shaders] The screen turns into black when press F11 while using shaders

### ISSUE THREAD

**Issue by YukiJr** [sp614x/optifine#5662]
## Description of Issue
The screen turns into black when I press F11 in a server while using shaders

## Steps to Reproduce
1. Be using a shaderpack
2. Go to any server and press F11

## OptiFine Version
Optifine_1.16.5_HD_U_G7

## Installation Method
Dropped the JAR file into "mods" folder

## Fabric Version
0.11.3-1.16.5

## OptiFabric Version
1.9.6

## Log Files/Crash Reports
https://pastebin.com/kFNw6WM8

## Prior Testing
- Does this happen in Vanilla without OptiFine?
   - No

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   - Only OptiFine, OptiFabric, and Fabric
- Does this happen in OptiFine standalone?
   - Yes
- Does this happen in Vanilla without OptiFine?
   - No

**Comment by KaiAF** [comment]
Could you send a F3 debug menu screenshot?

**Comment by YukiJr** [comment]
![2021-05-31_17 55 53](https://user-images.githubusercontent.com/63476664/120241687-ae696800-c239-11eb-86cd-d4623ec7265e.png)

**Comment by KaiAF** [comment]
Do you have a graphics card? The one that Minecraft is using is the integrated GPU. 
If you don't have a GPU, you would probably need to update the iGPU drivers.

**Comment by YukiJr** [comment]
I'm using a computer, and I have a Intel Graphics HD 2000 with the newest drivers.
This bug didn't exist in Optifine G6 and below. I tested it.

**Comment by KaiAF** [comment]
it could honestly be hardware that is causing this. I am not able to reproduce this. You could try disabling smooth fps and fastrender to see if that helps.

**Comment by YukiJr** [comment]
Unfortunately, disabling Fast Render and Smooth FPS didn't work. Should be my hardware then.
Thank you anyway.
