### ISSUE TITLE
Many letters are invisible

### ISSUE THREAD

**Issue by TheTongPro** [sp614x/optifine#5667]
help this is happening after i downloaded the 21w08b snapshot optifine and it appened to both versions (as seen in bottom left corner)
![2021-05-24_14 54 32](https://user-images.githubusercontent.com/84638084/119350955-38488c80-bca0-11eb-839c-3a8c54d8abf0.png)

**Comment by Cart3r1234** [comment]
It seems to only apply to the letter U when capitalized and the number 0.  If you have an active resource packs, try disabling them to see if its a bug with fonts in resource packs.
