### ISSUE TITLE
[Website] Optifine should use PMC banners instead of needcoolshoes

### ISSUE THREAD

**Issue by AidanLCB** [sp614x/optifine#5668]
Needcoolshoes has lately been down a lot and the owners haven't seemed to do much since 2014. I think it would be a good idea to use a different editor such as PMC which can export with similar urls, is more user friendly, and always up to date with the latest versions of mc. I don't see why optifine has to be stuck with such an outdated website when there is a better alternative which is most likely easy to switch to.

**Comment by KaiAF** [comment]
I am unable to find another issue regarding this, but this has been suggested before. Right now, I don't think it's entirely possible changing sites, it would definately require a lot of work.

**Comment by Jiingy** [comment]
The needcoolshoes website has unforunately shut down as of this year with no warning, so naturally the website will likely be moved off of it in due time.
