### ISSUE TITLE
Antialiasing causes tiny pixels to appear next to the crosshair

### ISSUE THREAD

**Issue by PapiDimmi** [sp614x/optifine#567]
![optifine crosshair glitch](https://cloud.githubusercontent.com/assets/25916106/24539204/ab153438-15ed-11e7-97d2-34b928fbf259.png)

Turning off antialiasing and restarting the game fixes this.

**Comment by sp614x** [comment]
This is a known side effect of antialiasing and it is not easy to fix.

**Comment by PapiDimmi** [comment]
Oh well. I barely notice it anyway.

**Comment by sp614x** [comment]
This is a known side effect of antialiasing and it is not easy to fix.

**Comment by PapiDimmi** [comment]
Yes, you said that already.
