### ISSUE TITLE
[Category] Short description

### ISSUE THREAD

**Issue by Hvngaro** [sp614x/optifine#5672]
## Description of Issue
With the lastest version Optifine 1.16.5 the end sky color change to purple. Im need use the sky of end with texturepack, and dont works because optifine overrides it. Is not a texturepack o shader because I dont use nothing and without optifine the sky changes.

## Steps to Reproduce
1. Intall optifine
2. Go to END

## OptiFine Version
OPTIFINE 1.16.5 UG8

## Installation Method
OPTIFINE INSTALLED

## Fabric/Forge Version
VANILA

**Comment by KaiAF** [comment]
Could you provide a F3 debug menu screenshot? This could help out a bit. And I'm also not entirely sure what the issue is.
