### ISSUE TITLE
[visual bug] My minecraft is invisible 

### ISSUE THREAD

**Issue by bluehadron27** [sp614x/optifine#5674]
## Description of Issue
When i load my minecraft, Everything but players and entities are invisible, and if you go like 5-10 blocks away they dissapear
including literally every block.
its like being in the void but theres barrier blocks and stuff
if i break a block in a chunk the chunk appears but dissapears if refreshed

## Steps to Reproduce
1. launch the game
2.  ?? ? ? ? ???

## OptiFine Version
1.16.5

## Installation Method
i installed it using the installer, but i tried deleting and installing MANY times

## Other Installed Mods
none are in my mods folder but i do have forge mod loader 1.12.2 forge mod loader 1.7.10 and fabric loader 1.16.5 all standalone and not being used

also optifine is installed as a standalone

## Log Files/Crash Reports
i do not know how to do this

## F3 Debug Screenshot
no idea how to do this

## Prior Testing

- Does this happen in OptiFine standalone? yes
- Does this happen in Vanilla without OptiFine? no
- Have you tried using a binary search to find which mods cause this issue? i dont have any mods in my mods folder
  
 

## Additional Information
i really just want to play hypixel :(

**Comment by Regnander** [comment]
> ## OptiFine Version
> 
> 1.16.5

There are multiple versions of OptiFine for 1.16.5. As I'm writing this, OptiFine HD U G8 is the latest version for 1.16.5.

> ## Log Files/Crash Reports
> 
> i do not know how to do this 

[You can read about reports here on the Minecraft Wiki](https://minecraft.fandom.com/wiki/Tutorials/How_to_get_a_crash_report)

> ## F3 Debug Screenshot
> 
> no idea how to do this

Press F3 in-game to display info about your settings and hardware, then press F2 to take a screenshot and finally upload the screenshot here by drag-and-drop it into the textbox.

[You can read about where to find the screenshot folder on the Minecraft Wiki](https://minecraft.fandom.com/wiki/Screenshot#Storage)

**Comment by KaiAF** [comment]
Please could you provide a picture of the F3 debug menu? This could help a bit.
