### ISSUE TITLE
Twilight forest Naga and Hydra (please please fix this)

### ISSUE THREAD

**Issue by BlueRosen** [sp614x/optifine#5677]
The models for nagas body and hydras heads and necks are gone, the developers of TWF have said this is an issue on optifines side this is really just making me so bummed I cant run mods AT ALL with out optifine

**Comment by Corvus20** [comment]
I have the exact same problem. I can hardly run anything without optifine. Another issue is currently open covering this same problem, #5535 .

**Comment by KaiAF** [comment]
Closing this as it's a duplicate.
