### ISSUE TITLE
Additionnal composite programs.

### ISSUE THREAD

**Issue by Choca13** [sp614x/optifine#568]
I would need a few additional composite programs to add SMAA, but just to be sure there is enough passes for the future going up to composite15 would be nice.

**Comment by Choca13** [comment]
If you add variable resolution outputs, i would still be interested. (Bloom could take 10-12 passes)

**Comment by sp614x** [comment]
OptiFine 1.12.2_HD_U_E1
 - increased composite and deferred shader programs to 16 

https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.txt#L85
