### ISSUE TITLE
GUI Issue with camera mod and optifine

### ISSUE THREAD

**Issue by TVCJ13** [sp614x/optifine#5682]
Hello,

So my friend and I downloaded camera mod for our server, now for some reason when he joined, he was not able to view his hotbar, chat, inventory or any sort of GUI (besides the journey map on top of his screen)

We realised that this was because optifine was clashing with the camera mod for some reason and we have no clue on why. We’ve had to remove this mod because he prefers to have optifine but I was really hoping we could somehow come to figure out a solution so I can get the camera mod can on our server again.

**Comment by Regnander** [comment]
Can you post a screenshot with debug info (F3) enabled, so we at least can see what version you are using?
