### ISSUE TITLE
[Crash] Mixin apply failed

### ISSUE THREAD

**Issue by Kroko1337** [sp614x/optifine#5683]
## Description of Issue
When i start the game its crashs

## Steps to Reproduce
1. Start the game with few mods

## OptiFine Version
G8

## Installation Method
 
mods folder

## Other Installed Mods

https://pastebin.com/52nVAhGL

## Log Files/Crash Reports

https://pastebin.com/1MmkTmkK

**Comment by KaiAF** [comment]
This crash is most likely caused by another mod that is incompatible with OptiFine. You could try taking half the mods out and put it into groups. And continue doing that until you find what mod might be causing the crash.
