### ISSUE TITLE
[Shaders] Reflections in Path Traced Shaders (such as SEUS PTGI) Broken

### ISSUE THREAD

**Issue by supersnaketate** [sp614x/optifine#5686]
## Description of Issue

Path Traced(ray tracing) shader packs such as SEUS PTGI E11 & HHR 2.1 have broken reflections
This only started happening within the last 24 hours (1/June/2021)

Root cause could be related to AMD Drivers, or Nvidia drivers, as this issue has appeared on the same day both companies have announced new products, each with their new software. I didn't manually update any drivers when this started happening so I would guess its driver installed in the background. Updating to Nvidia's latest driver didn't fix the issue

## Steps to Reproduce
1. What do you do...
load up Minecraft with:
- Optifine
- Forge
- A resource pack that supports specular PBR (preferably suitable for SEUS type PBR), 
- A shader pack such as SEUS PTGI E11, or SEUS PTGI HHR 2.1 (any SEUS PTGI would result the same I would guess)

2. ...to find this bug?
- use any reflective block such as ones with full reflections, (make sure in shader options for SEUS the texture resolution is set correctly). or check the edges of the water surface where blocks would naturally be reflected.
**reflections in SEUS are best done with a resource pack that has most if not all textures completed, SEUS has trouble reflecting default texutres**
- observe the reflections in the block, move about to see they are changing reflected textures based on your position (as in video below).

## OptiFine Version

tried on:
- 1.16.4 G5 Ultra - Issue occurred
- 1.16.5 G7 HD Uand G8 HD U - Issue occurred

## Installation Method

I tried both:
- Vanilla installation using optifine's "install" method - Issue occurred visually different (reflections weren't as erratic, and textures weren't incorrect but water was fully clear, leaves were missing and overlays were shown as full textures. These could be a SEUS Issue (see imgur screenshots below))
- Using multiMC launcher, installed forge 36.1 and optifine G7 or G8 (extracted MOD) (using MultiMC basically installs optifine in the .minecraft directory mods folder) - Issue occurred (see pictures & video)

## Fabric/Forge Version

1.16.4 - Forge 35.1.4
1.16.5 - Forge 36.1.0 & also tried 36.1.1

## Other Installed Mods

- Voxelmap 1.10.12 for FORGE, which I removed, the issue continued
- Worldedit 7.2.5 for FORGE

- my resource pack, which includes a lot of specular CTM texctures
- Conquest 32x texture pack (not required but used in this situation)

## Log Files/Crash Reports

console window for 1.16.5 With Forge & Optifine, - https://paste.ee/p/Pz4lg

## F3 Debug Screenshot

https://imgur.com/a/IwAqBLo
https://youtu.be/dXihoeM96Ts

## Prior Testing
- Does this happen in Vanilla without OptiFine?

- cannot recreate without optifine
- this issue did not occur yesterday with the same settings as today

## Additional Information

Current PC Specs:
- AMD Ryzen 7 5800x 
- Nvidia GTX 1080 Founders Edition, with AIO installed
- 32gb HyperX ram (4x8gb) 2666Mhz

- NVIDIA Driver Version 466.47
- AMD driver 10.0.19041.546
- JAVA driver Version 8 Update 291 Build (1.8.0_291-b10)

you're welcome to download my texture pack featuring only the fully reflective block shown in my pictures and video: the block is gray_concrete_powder (set SEUS texture resolution to 32)
https://www.mediafire.com/file/r2hd6wjblumt1xk/SCA_gray_concrete_powder.zip/file

I just have a hunch it is related to drivers, because I haven't personally updated optifine, forge or SEUS in the last few days. unfortunately because this issue is so recent google and bing have been no help finding other people experiencing the same or similar issue.

**Comment by supersnaketate** [comment]
Update:
after reinstalling an older version of NVIDIA drivers, no change, issue still exists

**Comment by supersnaketate** [comment]
Update: 
This issue has gone away with the Optifine Preview version of 1.17_HD_U_G9_pre24 for 1.17 minecraft

**Comment by NALAFX** [comment]
I downloaded the shader pack from [Seus shaders for Minecraft](https://www.seusshaders.org/) and it's working perfectly fine

**Comment by supersnaketate** [comment]
> 
> 
> I downloaded the shader pack from [Seus shaders for Minecraft](https://www.seusshaders.org/) and it's working perfectly fine

SEUS PTGI is not the same as SEUS RENEWed, v11, or 10.2 ultra

either way as i mentioned above this issue in no longer a problem as over 1.17 onwards

**Comment by yohlimem** [comment]
change the render quality and shadow quality to 1 nice day, everyone! :D
