### ISSUE TITLE
Cape Problems, my friend has optifne and he cant see my cape. I see the cape but he dosnt.

### ISSUE THREAD

**Issue by GJungle1** [sp614x/optifine#5689]
## Steps to Reproduce
1. Log into the game
2. umm, he cants see the came.

## OptiFine Version
1.16.5 G8

## Installation Method
Fabric, optifabric, optifine.

## Fabric/Forge Version
Fabric 0.11.3 1.16.5

## OptiFabric Version
1.9.6 1.16.5

## Other Installed Mods
https://i.imgur.com/ZWAsHHO.png

[latest.log](https://github.com/sp614x/optifine/files/6589288/latest.log)

   
## F3 Debug Screenshot
https://i.imgur.com/5Bu4ULj.jpeg

**Comment by KaiAF** [comment]
If you are able to see your cape, there isn't any issue with OptiFine. Your friend would have an issue with (*Assuming*) something blocking the OptiFine cape servers. I would suggest getting your friend to contact our support team for help. [Email](https://www.optifine.net/contact), [Discord](https://optifine.net/discord).

**Comment by GJungle1** [comment]
He can see other players cape, but not mine
