### ISSUE TITLE
Blocks not visible

### ISSUE THREAD

**Issue by Mario-Cu** [sp614x/optifine#5696]
Hi, Ice blocks, honey blocks and tainted cristal are not visible in the game, you can just see the hitbox

**Comment by arnonGPMC** [comment]
Try to Remove The Block And Replace It

**Comment by KaiAF** [comment]
Closing this issue as there is another issue with more information. This is caused by Render Regions.

**Comment by KaiAF** [comment]
https://github.com/sp614x/optifine/issues/5698
