### ISSUE TITLE
Tinted Glass not connecting textures

### ISSUE THREAD

**Issue by Scorpion34** [sp614x/optifine#5702]
Connecting textures are set to fancy here's screenshots
![2021-06-08_13 40 33](https://user-images.githubusercontent.com/15971924/121239719-36b1c380-c85f-11eb-909b-ee60822eb06d.png)
![2021-06-08_13 40 36](https://user-images.githubusercontent.com/15971924/121239722-374a5a00-c85f-11eb-92b0-c71057bbccb1.png)
![2021-06-08_13 41 01](https://user-images.githubusercontent.com/15971924/121239724-37e2f080-c85f-11eb-844e-468c5d111420.png)

**Comment by sp614x** [comment]
Added in pre18.
