### ISSUE TITLE
[Blocks Not Rendering] Tinted Glass and Honey Blocks arent rendering

### ISSUE THREAD

**Issue by RhythmbutBetter** [sp614x/optifine#5707]
## Description of Issue
 From what I have seen the honey blocks and (stained + tinted glass/glass panes) are not rendering, they still have the particle effects but the actual blocks dont render at all.

## Steps to Reproduce
I just placed down the blocks

## OptiFine Version
1.17 Preview

## Installation Method
I used the standalone installer.

## F3 Debug Screenshot

![image](https://user-images.githubusercontent.com/50062319/121246979-b6478e80-c86f-11eb-8758-cce6996fe959.png)

## Prior Testing

There may be more blocks but I dont know any more yet

**Comment by KaiAF** [comment]
#5698 Allready reported.
