### ISSUE TITLE
 Stained glass invisible

### ISSUE THREAD

**Issue by alexaaak** [sp614x/optifine#5711]
## Description of Issue
The stained glass is invisible completely 

## Steps to Reproduce
1. What do you do...
2. ...to find this bug?

## OptiFine Version
OptiFine HD U G9 pre16

## Installation Method
Installed optifine Jar file from optifine/net and opened it with Java to create new version of optifine

## F3 Debug Screenshot

-

**Comment by Cart3r1234** [comment]
Already addressed in #5698
