### ISSUE TITLE
[1.17] Fire isn't animated

### ISSUE THREAD

**Issue by MysteriousSquid** [sp614x/optifine#5712]
## Description of Issue
Fire just displays as a still texture in the new 1.17 version of optifine instead of being animated.

## OptiFine Version
1.17-Optifine_HD_U_G9_pre16

## Installation Method
I used the standalone installer.

## F3 Debug Screenshot
![2021-06-08_13 33 52](https://user-images.githubusercontent.com/85586447/121253677-4086f700-c85e-11eb-99c3-be5a8d6103c9.png)

## Prior Testing
Does not occur in Vanilla.

**Comment by KaiAF** [comment]
Seems to be related to #5701. Turn off Smart Animations and see if that helps. If it does, let me know.
