### ISSUE TITLE
[Bugs] No animations work

### ISSUE THREAD

**Issue by JediSlayer19** [sp614x/optifine#5713]
Animations are completely broken in the first 1.17 build for optifine. There are no water, fire, lava, or portal animations. Particles still work.

Laptop specs:
 
Intel Core i3-4012Y 1.50GHz
Intel(R) HD 4200
4 GB RAM

As you can see, optifine is especially needed for someone like me, with a literal toaster

**Comment by KaiAF** [comment]
This seems to be related to #5701. So Turn off Smart Animations and see if that helps. If it helps, let me know.

**Comment by sp614x** [comment]
Fixed in pre17
