### ISSUE TITLE
Multiple rendering issues in Optifine 1.17

### ISSUE THREAD

**Issue by Baboobraz** [sp614x/optifine#5719]
## Description of Issue
I have found multiple render issues so far in 1.17 optifine and checked to make sure it was just optifine and it was. Here is a list so far:
* Chunks refuse to load when entering a new dimension
* Birch leaves won't render from far away (how does this even work all other leaves are fine)
* Water and Lava textures are not animated
* Entities do not render properly far away (mainly noticed with chests and crops, yes I know they dont render at a certain point but it was fine in vanilla but not in optifine. Also the slider to change the distance they stop rendering at in optifine seems to be broken

## Steps to Reproduce
I mean its rendering issues so just check them in game

## OptiFine Version
OptiFine HD U G9 pre16
OptiFine HD U G9 pre17 (only dimensions one)

## Installation Method
Standalone installer

## F3 Debug Screenshot
![2021-06-08_16 41 39](https://user-images.githubusercontent.com/85592003/121271410-71742580-c878-11eb-897a-248927e57f71.png)

## Prior Testing
<!-- If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
No

## Additional Information
As I was writing this I saw a new version came out, all bugs have been fixed EXCEPT the chunks refusing to load in new dimensions one.

**Comment by reatmon** [comment]
I see the same issue with leaves on acacia as well, not just birch.  And I'm seeing the same dimension transition chunk loading problem that others have reported.

**Comment by g0thian** [comment]
I'm having rendering issues too, chunks not loading.

**Comment by WindiestJack** [comment]
There are also rendering issues with Ice, it was rendering in the sky above the Frozen Ocean biome and I don't know why, version pre16.
![2021-06-09_21 56 03](https://user-images.githubusercontent.com/85659481/121458699-7798fd80-c96f-11eb-9064-c0b8e70e3b23.png)

**Comment by KaiAF** [comment]
Are these all still an issue on the recent preview?

These all should be fixed now: 
- Chunks refuse to load when entering a new dimension
- Birch leaves won't render from far away (how does this even work all other leaves are fine)
- Water and Lava textures are not animated

Probably was fixed: 
- Entities do not render properly far away (mainly noticed with chests and crops, yes I know they dont render at a certain point but it was fine in vanilla but not in optifine. Also the slider to change the distance they stop rendering at in optifine seems to be broken
