### ISSUE TITLE
[Request] Custom entity models per biome

### ISSUE THREAD

**Issue by Dovahrt** [sp614x/optifine#572]
Can you help me creating a very simple resource pack? I'd like to have different chests' texture per biome but I don't know how to do it. Here they are: http://i.imgur.com/nKd9bQu.png I created them with Little Tiles mod... but I'd like them in the "vanilla" game, using a resource pack with Optifine (game version 1.11.2). How can I do it? I have the textures, but I don't know if I have to create a .properties file or something like that. Please help me and consider that I'm a beginner (aka noob) with resource packs creation, so don't give anything for granted while you help me.
To be more precise, for example I'd like the "Oak chest" (the first one on the left in the screenshot) in the following biomes: Plains, Sunflower Plains, Forest, Swampland, Swampland M... their appearance, does not depend on the planks used for crafting them, but depends by the biome in which they are placed.
Thanks in advance :D

**Comment by Dovahrt** [comment]
This didn't work: /minecraft/texture/entity/chests/3.properties
texture=textures/entity/chest/normal3.png
biomes=Plains, Sunflower Plains, Forest, Swampland,

**Comment by sp614x** [comment]
Currently this is not possible.
Custom Entity Models have to be extended with biome check to make it happen.

**Comment by Dovahrt** [comment]
Okay :c thanks anyway

**Comment by Avereniect** [comment]
I've personally been able to achieve something to this effect using both the custom entity textures and models features provided. In short, place all the geometry from all the different models which you have in mind into one single model which will be the only one used. Now, you can use the custom texture features to assign a texture where all unwanted geometry is made invisible through a transparent texture which is assigned only under the conditions you want.
.

**Comment by madtomic** [comment]
@Dovahrt 

Can you please share you chest texture pack?
