### ISSUE TITLE
1.17 Nether portal is invisable

### ISSUE THREAD

**Issue by Eyebqll** [sp614x/optifine#5720]
when i created a nether portal the portal was invisable but it still functioned

- ## Steps to Reproduce
Create a nether portal

## OptiFine Version
OptiFine HD U G9 pre17

## Installation Method
used multimc and installed by extracting and used the "Add to Minecraft.jar" option

## Fabric/Forge Version
fabric 0.11.3

## OptiFabric Version
none

## F3 Debug Screenshot
![2021-06-08_19 40 37](https://user-images.githubusercontent.com/73678300/121275952-54008500-c893-11eb-9a4a-5e63a2c7282f.png)

## Prior Testing
this doesnt happen in vanilla minecraft
this still happens with standalone optifine

**Comment by Regnander** [comment]
#5698 
Update to pre17

**Comment by KaiAF** [comment]
This bug was fixed in pre 17
