### ISSUE TITLE
Water is static 1.17

### ISSUE THREAD

**Issue by Eyebqll** [sp614x/optifine#5721]
## Description of Issue
water is static even with "Water Animated" on in animations

## Steps to Reproduce
find flowing water

## OptiFine Version
OptiFine HD U G9 pre17

## Installation Method
standalone installer with extract

## Fabric/Forge Version
Fabric 0.11.3

## OptiFabric Version
none (used "Add to Minecraft.jar" with multimc)

## Other Installed Mods
none

## F3 Debug Screenshot
![2021-06-08_19 50 53](https://user-images.githubusercontent.com/73678300/121275719-e81e1c80-c892-11eb-8359-2fc1656bd053.png)

## Prior Testing
does not happen in vanilla
happens with standalone optifine

**Comment by Regnander** [comment]
#5701
You mention pre17, but the screenshot says pre16.

**Comment by KaiAF** [comment]
this bug was fixed in pre 17
