### ISSUE TITLE
Linux - MInecraft with optifine crashes

### ISSUE THREAD

**Issue by UlisesToMa** [sp614x/optifine#5723]
## Description of Issue
I use KDE Plasma(linux), i can open minecraft vanilla, but if i try to use the Optifine version, it crashed showing GLFW error: 65543: GLX: Failed to create context: GLXBadFBConfig
Image of the error: https://imgur.com/a/nEn0LSw

## Steps to Reproduce
Just intall the optifine version of minecraft 1.17, start the game that it.

## OptiFine Version
OptiFine HD U G9 pre17
OptiFine HD U G9 pre16

## Installation Method
i've used the downloable .Jar in the download section of Optifine.net, there's no problem or errors at the installation.

## Log Files/Crash Reports

/.minecraft/logs/

https://pastebin.com/wVbXFHJx

LAUNCHER LOG
https://pastebin.com/uemSU5Zh

## Prior Testing
- Does this happen in Vanilla without OptiFine? No, i can open vanilla Minecraft without problems 

## Additional Information
I use Linux, i've the latest updates of Mesa and my Drivers so there's no problem there and like i said before, i can open minecraft vanilla, i can play o change settings so i thing is a problem with Optifine.

**Comment by strich3** [comment]
Same problem! I am not alone haha

**Comment by 0-x-2-2** [comment]
#5739

**Comment by KaiAF** [comment]
Closing this as its addressed in #5739.
