### ISSUE TITLE
[1.17] Tinted glass' texture doesn't connect

### ISSUE THREAD

**Issue by superscratch444tre** [sp614x/optifine#5729]
## Description of Issue
The texture of the new tinted glass type doesn't connect.
*(See screenshot in the "Additional Information" section)*

## Steps to Reproduce
1. Place 2 or more tinted glass blocks one next to another; *(See screenshot in the "Additional Information" section)*
2. See that the texture does not connect.

## OptiFine Version
OptiFine HD U G9 pre17

## Installation Method
Just double-clicked the .jar file, then optifine got installed.

## F3 Debug Screenshot
![2021-06-09_13 56 54](https://user-images.githubusercontent.com/69812464/121342708-d0d64200-c919-11eb-9656-f537060d6aed.png)
(the background is a wall of black concrete)

## Prior Testing
- Does this happen in Vanilla without OptiFine? 
 No, it is not even supposed to happen.

## Additional Information

![2021-06-09_13 50 36](https://user-images.githubusercontent.com/69812464/121341948-15151280-c919-11eb-8e90-7b10a618d0e4.png)

**Comment by Scorpion34** [comment]
This issue is already addressed in #5702

**Comment by KaiAF** [comment]
closing as it's already been addressed.
