### ISSUE TITLE
it keep crashing when click on play

### ISSUE THREAD

**Issue by weaksou** [sp614x/optifine#5731]
Minecraft has not started because of an unknown error! A popular solution to the problem:  - Try to install another version of Java. (For example, Java 8 Update 45 after uninstalling) - Try to update the video card drivers.  

here is the log:
flush now
[Loading] INITIALIZING
Starting TLauncher 2.79 RELEASE
For more information, visit https://tlauncher.org/
Startup time: Jun 9, 2021 1:42:11 PM
---
[Loading] LOADING_CONFIGURATION
Machine info: -------------------------------------------------------
Windows 10 10.0, Java 1.8.0_281, jvm bit x64, 7938 MB RAM
java path=C:\Users\soufi\AppData\Roaming\.tlauncher\jvms\jre1.8.0_281\bin\javaw.exe
Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
 Intel(R) UHD Graphics 620, Intel(R) UHD Graphics Family, 4097 MB, NVIDIA GeForce MX250, NVIDIA GeForce MX250, 5952 MB
-------------------------------------------------------
Selected locale: en_US
[Loading] LOADING_CONSOLE
[Downloader2] Loaded configuration: good
[Updater] Requesting an update...
[Updater] Requesting from: http://repo.tlauncher.org/update/lch/update_2.0.json
[Updater] Making request: http://repo.tlauncher.org/update/lch/update_2.0.json?version=2.79&client=4d20835d-26b7-405b-a9f7-3d7478e8fa15
[Browser] Loading resources...
[Updater] Request time: 217 ms
[Updater] Successfully requested from: http://repo.tlauncher.org/update/lch/update_2.0.json
[Browser] Loading background...
[Browser] Cleaning up after loading:
Starting garbage collector: 39 / 107 MB
Garbage collector completed: 17 / 140 MB
[Loading] LOADING_MANAGERS
[JFXStartPageLoader]  start load page: http://page.tlauncher.org/update/downloads/configs/client/eng.html
[LocalVersionList] Base directory: C:\Users\soufi\AppData\Roaming\.minecraft
[ProfileManager] Refreshing profiles from: C:\Users\soufi\AppData\Roaming\.minecraft\TlauncherProfiles.json
[Browser] Running in JavaFX Thread
[Browser] Preparing JavaFX...
[AdvertisingStatusObserver]  started to get ad information
[GsonUtil]  request to http://repo.tlauncher.org/update/downloads/libraries/org/tlauncher/authlib/libraries-1.7.json
[Browser] Initializing...
[AdvertisingStatusObserver]  finished to get add information
save profiles
[Loading] LOADING_WINDOW
[Swing] Favicons loaded: 256px, 128px, 96px, 64px, 48px, 32px, 24px, 16px
[Loading] PREPARING_MAINPANE
[REPO][SERVER_LIST_REPO] Success: Reached the repo in 139 ms.
[Downloader2] Loaded configuration: good
[JFXStartPageLoader]  succeeded load page: http://page.tlauncher.org/update/downloads/configs/client/eng.html during 1
[Browser@2143531996] Loaded successfully: "http://page.tlauncher.org/update/downloads/configs/client/eng.html"
[Browser] add listens into server_choose
[Browser] finished listens into server_choose
[Loading] POSTINIT_GUI
[Frame] Packing main frame...
[Frame] Resizing main pane...
Updater is already closed. Showing up...
Visibility set.
[Loading] REFRESHING_INFO
[VersionManager] Refreshing versions remotely...
[REPO][EXTRA_VERSION_REPO] Attempt #1; timeout: 20000 ms; url: http://repo.tlauncher.org/update/downloads/versions/new3/
Started! (3061 ms.)
[Loading] SUCCESS
[TLauncher] show tlauncher!!!
[REPO][OFFICIAL_VERSION_REPO] Attempt #1; timeout: 20000 ms; url: https://launchermeta.mojang.com/mc/game/
[REPO][EXTRA_VERSION_REPO] Attempt #1; timeout: 20000 ms; url: http://repo.tlauncher.org/update/downloads/versions/new3/
[REPO][SKIN_VERSION_REPO] Attempt #1; timeout: 20000 ms; url: http://repo.tlauncher.org/update/downloads/versions/new3/skin/versions/
[REPO][EXTRA_VERSION_REPO] Success: Reached the repo in 531 ms.
[ExtraVersionList] Got in 569 ms
[REPO][SKIN_VERSION_REPO] Success: Reached the repo in 752 ms.
[SkinVersionList] Got in 764 ms
[REPO][OFFICIAL_VERSION_REPO] Success: Reached the repo in 1290 ms.
[OfficialVersionList] Got in 1350 ms
[VersionManager] Versions has been refreshed (1386 ms)
[Version:1.17-OptiFine_HD_U_G9_pre17] Resolving...
[Version:1.17-OptiFine_HD_U_G9_pre17] Inherits from 1.17
[Version:1.17-OptiFine_HD_U_G9_pre17] Resolving...
[Version:1.17-OptiFine_HD_U_G9_pre17] Inherits from 1.17
local server started
[Version:1.17-OptiFine_HD_U_G9_pre17] Resolving...
[Version:1.17-OptiFine_HD_U_G9_pre17] Inherits from 1.17
[REPO][ADD_HOT_SERVERS_REPO] Attempt #1; timeout: 20000 ms; url: http://repo.tlauncher.org/update/lch/additional_hot_servers-1.0.json
[REPO][HOT_SERVERS_REPO] Attempt #1; timeout: 20000 ms; url: http://repo.tlauncher.org/update/lch/servers/hot_servers-1.0.json
[REPO][ADD_HOT_SERVERS_REPO] Success: Reached the repo in 83 ms.
[REPO][EXTRA_VERSION_REPO] Success: Reached the repo in 1710 ms.
[Double running] clear time label
[REPO][HOT_SERVERS_REPO] Success: Reached the repo in 1793 ms.
AccountComboBox.validte pre game launch username Account{displayName=weaksou, type=TLAUNCHER, accessToken=(not null), userid=weaksou, uuid=d9ca9066649c11ea88ceb42e996a7d7a, username=weaksou} TLAUNCHER
[TlauncherAuthenticator] Staring to authenticate: Account{displayName=weaksou, type=TLAUNCHER, accessToken=(not null), userid=weaksou, uuid=d9ca9066649c11ea88ceb42e996a7d7a, username=weaksou}
[TlauncherAuthenticator] hasUsername: weaksou
[TlauncherAuthenticator] hasPassword: false
[TlauncherAuthenticator] hasAccessToken: true
[TlauncherAuthenticator] Loggining in with token
[TlauncherAuthenticator] Log in successful!
[TlauncherAuthenticator] hasUUID: true
[TlauncherAuthenticator] hasAccessToken: true
[TlauncherAuthenticator] hasProfiles: false
[TlauncherAuthenticator] hasProfile: false
[TlauncherAuthenticator] hasProperties: true
onAuthPassed
saved account Account{displayName=weaksou, type=TLAUNCHER, accessToken=(not null), userid=weaksou, uuid=d9ca9066649c11ea88ceb42e996a7d7a, username=weaksou}
save profiles
[LoginForm] Login was OK. Trying to launch now.
[Launcher] Running under TLauncher 2.79
[Launcher] Collecting info...
[TLauncherManager] before clearLibrary 
[TLauncherManager] written:  []
[TLauncherManager] after clearLibrary 
[Launcher] Force update: false
[Launcher] Selected version: 1.17-OptiFine_HD_U_G9_pre17
[Launcher] Selected account: Account{displayName=weaksou, type=TLAUNCHER, accessToken=(not null), userid=weaksou, uuid=d9ca9066649c11ea88ceb42e996a7d7a, username=weaksou}
[Version:1.17-OptiFine_HD_U_G9_pre17] Resolving...
[Version:1.17-OptiFine_HD_U_G9_pre17] Inherits from 1.17
[Launcher] Version sync info: VersionSyncInfo{id='1.17-OptiFine_HD_U_G9_pre17',
local=CompleteVersion{id='1.17-OptiFine_HD_U_G9_pre17', time=Wed Jun 09 13:42:03 WEST 2021, release=Tue Jun 08 12:00:40 WEST 2021, type=release, class=net.minecraft.launchwrapper.Launch, minimumVersion=21, assets='1.17', source=LOCAL_VERSION_REPO, list=net.minecraft.launcher.updater.LocalVersionList@45edc27c, libraries=[Library{name='optifine:OptiFine:1.17_HD_U_G9_pre17', rules=null, natives=null, extract=null, packed='null'}, Library{name='optifine:launchwrapper-of:2.2', rules=null, natives=null, extract=null, packed='null'}, Library{name='com.mojang:blocklist:1.0.5', rules=null, natives=null, extract=null, packed='null'}, Library{name='com.mojang:patchy:2.1.6', rules=null, natives=null, extract=null, packed='null'}, Library{name='com.github.oshi:oshi-core:5.7.4', rules=null, natives=null, extract=null, packed='null'}, Library{name='net.java.dev.jna:jna:5.8.0', rules=null, natives=null, extract=null, packed='null'}, Library{name='net.java.dev.jna:jna-platform:5.8.0', rules=null, natives=null, extract=null, packed='null'}, Library{name='org.slf4j:slf4j-api:1.8.0-beta4', rules=null, natives=null, extract=null, packed='null'}, Library{name='org.apache.logging.log4j:log4j-slf4j18-impl:2.14.1', rules=null, natives=null, extract=null, packed='null'}, Library{name='com.ibm.icu:icu4j:66.1', rules=null, natives=null, extract=null, packed='null'}, Library{name='com.mojang:javabridge:1.1.23', rules=null, natives=null, extract=null, packed='null'}, Library{name='net.sf.jopt-simple:jopt-simple:5.0.3', rules=null, natives=null, extract=null, packed='null'}, Library{name='io.netty:netty-all:4.1.25.Final', rules=null, natives=null, extract=null, packed='null'}, Library{name='com.google.guava:guava:21.0', rules=null, natives=null, extract=null, packed='null'}, Library{name='org.apache.commons:commons-lang3:3.5', rules=null, natives=null, extract=null, packed='null'}, Library{name='commons-io:commons-io:2.5', rules=null, natives=null, extract=null, packed='null'}, Library{name='commons-codec:commons-codec:1.10', rules=null, natives=null, extract=null, packed='null'}, Library{name='net.java.jinput:jinput:2.0.5', rules=null, natives=null, extract=null, packed='null'}, Library{name='net.java.jutils:jutils:1.0.0', rules=null, natives=null, extract=null, packed='null'}, Library{name='com.mojang:brigadier:1.0.18', rules=null, natives=null, extract=null, packed='null'}, Library{name='com.mojang:datafixerupper:4.0.26', rules=null, natives=null, extract=null, packed='null'}, Library{name='com.google.code.gson:gson:2.8.0', rules=null, natives=null, extract=null, packed='null'}, Library{name='com.mojang:authlib:2.3.31', rules=null, natives=null, extract=null, packed='null'}, Library{name='org.apache.commons:commons-compress:1.8.1', rules=null, natives=null, extract=null, packed='null'}, Library{name='org.apache.httpcomponents:httpclient:4.3.3', rules=null, natives=null, extract=null, packed='null'}, Library{name='commons-logging:commons-logging:1.1.3', rules=null, natives=null, extract=null, packed='null'}, Library{name='org.apache.httpcomponents:httpcore:4.3.2', rules=null, natives=null, extract=null, packed='null'}, Library{name='it.unimi.dsi:fastutil:8.2.1', rules=null, natives=null, extract=null, packed='null'}, Library{name='org.apache.logging.log4j:log4j-api:2.14.1', rules=null, natives=null, extract=null, packed='null'}, Library{name='org.apache.logging.log4j:log4j-core:2.14.1', rules=null, natives=null, extract=null, packed='null'}, Library{name='org.lwjgl:lwjgl:3.2.1', rules=[Rule{action=ALLOW, os=OSRestriction{name=OSX, version='null'}, features=null}], natives=null, extract=null, packed='null'}, Library{name='org.lwjgl:lwjgl:3.2.2', rules=[Rule{action=ALLOW, os=null, features=null}, Rule{action=DISALLOW, os=OSRestriction{name=OSX, version='null'}, features=null}], natives=null, extract=null, packed='null'}, Library{name='org.lwjgl:lwjgl-jemalloc:3.2.1', rules=[Rule{action=ALLOW, os=OSRestriction{name=OSX, version='null'}, features=null}], natives=null, extract=null, packed='null'}, Library{name='org.lwjgl:lwjgl-jemalloc:3.2.2', rules=[Rule{action=ALLOW, os=null, features=null}, Rule{action=DISALLOW, os=OSRestriction{name=OSX, version='null'}, features=null}], natives=null, extract=null, packed='null'}, Library{name='org.lwjgl:lwjgl-openal:3.2.1', rules=[Rule{action=ALLOW, os=OSRestriction{name=OSX, version='null'}, features=null}], natives=null, extract=null, packed='null'}, Library{name='org.lwjgl:lwjgl-openal:3.2.2', rules=[Rule{action=ALLOW, os=null, features=null}, Rule{action=DISALLOW, os=OSRestriction{name=OSX, version='null'}, features=null}], natives=null, extract=null, packed='null'}, Library{name='org.lwjgl:lwjgl-opengl:3.2.1', rules=[Rule{action=ALLOW, os=OSRestriction{name=OSX, version='null'}, features=null}], natives=null, extract=null, packed='null'}, Library{name='org.lwjgl:lwjgl-opengl:3.2.2', rules=[Rule{action=ALLOW, os=null, features=null}, Rule{action=DISALLOW, os=OSRestriction{name=OSX, version='null'}, features=null}], natives=null, extract=null, packed='null'}, Library{name='org.lwjgl:lwjgl-glfw:3.2.1', rules=[Rule{action=ALLOW, os=OSRestriction{name=OSX, version='null'}, features=null}], natives=null, extract=null, packed='null'}, Library{name='org.lwjgl:lwjgl-glfw:3.2.2', rules=[Rule{action=ALLOW, os=null, features=null}, Rule{action=DISALLOW, os=OSRestriction{name=OSX, version='null'}, features=null}], natives=null, extract=null, packed='null'}, Library{name='org.lwjgl:lwjgl-stb:3.2.1', rules=[Rule{action=ALLOW, os=OSRestriction{name=OSX, version='null'}, features=null}], natives=null, extract=null, packed='null'}, Library{name='org.lwjgl:lwjgl-stb:3.2.2', rules=[Rule{action=ALLOW, os=null, features=null}, Rule{action=DISALLOW, os=OSRestriction{name=OSX, version='null'}, features=null}], natives=null, extract=null, packed='null'}, Library{name='org.lwjgl:lwjgl-tinyfd:3.2.1', rules=[Rule{action=ALLOW, os=OSRestriction{name=OSX, version='null'}, features=null}], natives=null, extract=null, packed='null'}, Library{name='org.lwjgl:lwjgl-tinyfd:3.2.2', rules=[Rule{action=ALLOW, os=null, features=null}, Rule{action=DISALLOW, os=OSRestriction{name=OSX, version='null'}, features=null}], natives=null, extract=null, packed='null'}, Library{name='org.lwjgl:lwjgl:3.2.1', rules=[Rule{action=ALLOW, os=OSRestriction{name=OSX, version='null'}, features=null}], natives={OSX=natives-macos}, extract=null, packed='null'}, Library{name='org.lwjgl:lwjgl:3.2.2', rules=[Rule{action=ALLOW, os=null, features=null}, Rule{action=DISALLOW, os=OSRestriction{name=OSX, version='null'}, features=null}], natives={LINUX=natives-linux, WINDOWS=natives-windows}, extract=null, packed='null'}, Library{name='org.lwjgl:lwjgl-jemalloc:3.2.1', rules=[Rule{action=ALLOW, os=OSRestriction{name=OSX, version='null'}, features=null}], natives={OSX=natives-macos}, extract=null, packed='null'}, Library{name='org.lwjgl:lwjgl-jemalloc:3.2.2', rules=[Rule{action=ALLOW, os=null, features=null}, Rule{action=DISALLOW, os=OSRestriction{name=OSX, version='null'}, features=null}], natives={LINUX=natives-linux, WINDOWS=natives-windows}, extract=null, packed='null'}, Library{name='org.lwjgl:lwjgl-openal:3.2.1', rules=[Rule{action=ALLOW, os=OSRestriction{name=OSX, version='null'}, features=null}], natives={OSX=natives-macos}, extract=null, packed='null'}, Library{name='org.lwjgl:lwjgl-openal:3.2.2', rules=[Rule{action=ALLOW, os=null, features=null}, Rule{action=DISALLOW, os=OSRestriction{name=OSX, version='null'}, features=null}], natives={LINUX=natives-linux, WINDOWS=natives-windows}, extract=null, packed='null'}, Library{name='org.lwjgl:lwjgl-opengl:3.2.1', rules=[Rule{action=ALLOW, os=OSRestriction{name=OSX, version='null'}, features=null}], natives={OSX=natives-macos}, extract=null, packed='null'}, Library{name='org.lwjgl:lwjgl-opengl:3.2.2', rules=[Rule{action=ALLOW, os=null, features=null}, Rule{action=DISALLOW, os=OSRestriction{name=OSX, version='null'}, features=null}], natives={LINUX=natives-linux, WINDOWS=natives-windows}, extract=null, packed='null'}, Library{name='org.lwjgl:lwjgl-glfw:3.2.1', rules=[Rule{action=ALLOW, os=OSRestriction{name=OSX, version='null'}, features=null}], natives={OSX=natives-macos}, extract=null, packed='null'}, Library{name='org.lwjgl:lwjgl-glfw:3.2.2', rules=[Rule{action=ALLOW, os=null, features=null}, Rule{action=DISALLOW, os=OSRestriction{name=OSX, version='null'}, features=null}], natives={LINUX=natives-linux, WINDOWS=natives-windows}, extract=null, packed='null'}, Library{name='org.lwjgl:lwjgl-stb:3.2.1', rules=[Rule{action=ALLOW, os=OSRestriction{name=OSX, version='null'}, features=null}], natives={OSX=natives-macos}, extract=null, packed='null'}, Library{name='org.lwjgl:lwjgl-tinyfd:3.2.2', rules=[Rule{action=ALLOW, os=null, features=null}, Rule{action=DISALLOW, os=OSRestriction{name=OSX, version='null'}, features=null}], natives={LINUX=natives-linux, WINDOWS=natives-windows}, extract=null, packed='null'}, Library{name='org.lwjgl:lwjgl-tinyfd:3.2.1', rules=[Rule{action=ALLOW, os=OSRestriction{name=OSX, version='null'}, features=null}], natives={OSX=natives-macos}, extract=null, packed='null'}, Library{name='org.lwjgl:lwjgl-stb:3.2.2', rules=[Rule{action=ALLOW, os=null, features=null}, Rule{action=DISALLOW, os=OSRestriction{name=OSX, version='null'}, features=null}], natives={LINUX=natives-linux, WINDOWS=natives-windows}, extract=null, packed='null'}, Library{name='com.mojang:text2speech:1.11.3', rules=null, natives=null, extract=null, packed='null'}, Library{name='com.mojang:text2speech:1.11.3', rules=null, natives={LINUX=natives-linux, WINDOWS=natives-windows}, extract=net.minecraft.launcher.versions.ExtractRules@61af80e4, packed='null'}, Library{name='ca.weblite:java-objc-bridge:1.0.0', rules=[Rule{action=ALLOW, os=OSRestriction{name=OSX, version='null'}, features=null}], natives={OSX=natives-osx}, extract=net.minecraft.launcher.versions.ExtractRules@217c348a, packed='null'}, Library{name='ca.weblite:java-objc-bridge:1.0.0', rules=[Rule{action=ALLOW, os=OSRestriction{name=OSX, version='null'}, features=null}], natives=null, extract=null, packed='null'}]},
remote=null, isInstalled=true, hasRemote=false, isUpToDate=true}
[GsonUtil]  request to https://res.tlauncher.org/b/jvm/java_configuration.json
[Launcher] Checking conditions...
[Launcher] Comparing assets...
[AssetsManager] Checking resources...
[AssetsManager] Reading indexes from file C:\Users\soufi\AppData\Roaming\.minecraft\assets\indexes\1.17.json
[AssetsManager] Fast comparing: true
[Launcher] finished comparing assets: 168 ms.
[TLauncherManager] add required libraries: 1.17-OptiFine_HD_U_G9_pre17
[VersionManager] Required for version 1.17-OptiFine_HD_U_G9_pre17: []
[TLauncherManager] add required libraries: 1.17-OptiFine_HD_U_G9_pre17
path C:\Users\soufi\AppData\Roaming\.minecraft\runtime\jre-legacy\windows\jre-legacy
Java version 8 path: C:\Users\soufi\AppData\Roaming\.minecraft\runtime\jre-legacy\windows\jre-legacy\bin\javaw.exe
[Launcher] Unpacking natives...
[Launcher] Constructing process...
[Launcher] Constructing classpath...
[Launcher] Getting Minecraft arguments...
[Launcher] Full command: C:\Users\soufi\AppData\Roaming\.minecraft\runtime\jre-legacy\windows\jre-legacy\bin\javaw.exe -Djava.net.preferIPv4Stack=true -Dos.name=Windows 10 -Dos.version=10.0 -Xmn128M -Xmx2759M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Djava.library.path=C:\Users\soufi\AppData\Roaming\.minecraft\versions\1.17-OptiFine_HD_U_G9_pre17\natives -Dminecraft.launcher.brand=minecraft-launcher -Dminecraft.launcher.version=2.0.1003 -cp C:\Users\soufi\AppData\Roaming\.minecraft\libraries\optifine\OptiFine\1.17_HD_U_G9_pre17\OptiFine-1.17_HD_U_G9_pre17.jar;C:\Users\soufi\AppData\Roaming\.minecraft\libraries\optifine\launchwrapper-of\2.2\launchwrapper-of-2.2.jar;C:\Users\soufi\AppData\Roaming\.minecraft\libraries\com\mojang\blocklist\1.0.5\blocklist-1.0.5.jar;C:\Users\soufi\AppData\Roaming\.minecraft\libraries\com\mojang\patchy\2.1.6\patchy-2.1.6.jar;C:\Users\soufi\AppData\Roaming\.minecraft\libraries\com\github\oshi\oshi-core\5.7.4\oshi-core-5.7.4.jar;C:\Users\soufi\AppData\Roaming\.minecraft\libraries\net\java\dev\jna\jna\5.8.0\jna-5.8.0.jar;C:\Users\soufi\AppData\Roaming\.minecraft\libraries\net\java\dev\jna\jna-platform\5.8.0\jna-platform-5.8.0.jar;C:\Users\soufi\AppData\Roaming\.minecraft\libraries\org\slf4j\slf4j-api\1.8.0-beta4\slf4j-api-1.8.0-beta4.jar;C:\Users\soufi\AppData\Roaming\.minecraft\libraries\org\apache\logging\log4j\log4j-slf4j18-impl\2.14.1\log4j-slf4j18-impl-2.14.1.jar;C:\Users\soufi\AppData\Roaming\.minecraft\libraries\com\ibm\icu\icu4j\66.1\icu4j-66.1.jar;C:\Users\soufi\AppData\Roaming\.minecraft\libraries\com\mojang\javabridge\1.1.23\javabridge-1.1.23.jar;C:\Users\soufi\AppData\Roaming\.minecraft\libraries\net\sf\jopt-simple\jopt-simple\5.0.3\jopt-simple-5.0.3.jar;C:\Users\soufi\AppData\Roaming\.minecraft\libraries\io\netty\netty-all\4.1.25.Final\netty-all-4.1.25.Final.jar;C:\Users\soufi\AppData\Roaming\.minecraft\libraries\com\google\guava\guava\21.0\guava-21.0.jar;C:\Users\soufi\AppData\Roaming\.minecraft\libraries\org\apache\commons\commons-lang3\3.5\commons-lang3-3.5.jar;C:\Users\soufi\AppData\Roaming\.minecraft\libraries\commons-io\commons-io\2.5\commons-io-2.5.jar;C:\Users\soufi\AppData\Roaming\.minecraft\libraries\commons-codec\commons-codec\1.10\commons-codec-1.10.jar;C:\Users\soufi\AppData\Roaming\.minecraft\libraries\net\java\jinput\jinput\2.0.5\jinput-2.0.5.jar;C:\Users\soufi\AppData\Roaming\.minecraft\libraries\net\java\jutils\jutils\1.0.0\jutils-1.0.0.jar;C:\Users\soufi\AppData\Roaming\.minecraft\libraries\com\mojang\brigadier\1.0.18\brigadier-1.0.18.jar;C:\Users\soufi\AppData\Roaming\.minecraft\libraries\com\mojang\datafixerupper\4.0.26\datafixerupper-4.0.26.jar;C:\Users\soufi\AppData\Roaming\.minecraft\libraries\com\google\code\gson\gson\2.8.0\gson-2.8.0.jar;C:\Users\soufi\AppData\Roaming\.minecraft\libraries\com\mojang\authlib\2.3.31\authlib-2.3.31.jar;C:\Users\soufi\AppData\Roaming\.minecraft\libraries\org\apache\commons\commons-compress\1.8.1\commons-compress-1.8.1.jar;C:\Users\soufi\AppData\Roaming\.minecraft\libraries\org\apache\httpcomponents\httpclient\4.3.3\httpclient-4.3.3.jar;C:\Users\soufi\AppData\Roaming\.minecraft\libraries\commons-logging\commons-logging\1.1.3\commons-logging-1.1.3.jar;C:\Users\soufi\AppData\Roaming\.minecraft\libraries\org\apache\httpcomponents\httpcore\4.3.2\httpcore-4.3.2.jar;C:\Users\soufi\AppData\Roaming\.minecraft\libraries\it\unimi\dsi\fastutil\8.2.1\fastutil-8.2.1.jar;C:\Users\soufi\AppData\Roaming\.minecraft\libraries\org\apache\logging\log4j\log4j-api\2.14.1\log4j-api-2.14.1.jar;C:\Users\soufi\AppData\Roaming\.minecraft\libraries\org\apache\logging\log4j\log4j-core\2.14.1\log4j-core-2.14.1.jar;C:\Users\soufi\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl\3.2.2\lwjgl-3.2.2.jar;C:\Users\soufi\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl-jemalloc\3.2.2\lwjgl-jemalloc-3.2.2.jar;C:\Users\soufi\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl-openal\3.2.2\lwjgl-openal-3.2.2.jar;C:\Users\soufi\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl-opengl\3.2.2\lwjgl-opengl-3.2.2.jar;C:\Users\soufi\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl-glfw\3.2.2\lwjgl-glfw-3.2.2.jar;C:\Users\soufi\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl-stb\3.2.2\lwjgl-stb-3.2.2.jar;C:\Users\soufi\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl-tinyfd\3.2.2\lwjgl-tinyfd-3.2.2.jar;C:\Users\soufi\AppData\Roaming\.minecraft\libraries\com\mojang\text2speech\1.11.3\text2speech-1.11.3.jar;C:\Users\soufi\AppData\Roaming\.minecraft\versions\1.17-OptiFine_HD_U_G9_pre17\1.17-OptiFine_HD_U_G9_pre17.jar -Dminecraft.applet.TargetDirectory=C:\Users\soufi\AppData\Roaming\.minecraft -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -Dfml.ignoreInvalidMinecraftCertificates=true -Dfml.ignorePatchDiscrepancies=true net.minecraft.launchwrapper.Launch --username weaksou --version 1.17-OptiFine_HD_U_G9_pre17 --gameDir C:\Users\soufi\AppData\Roaming\.minecraft --assetsDir C:\Users\soufi\AppData\Roaming\.minecraft\assets --assetIndex 1.17 --uuid d9ca9066649c11ea88ceb42e996a7d7a --accessToken null --userType mojang --versionType release --width 925 --height 530 --tweakClass optifine.OptiFineTweaker
[Launcher] Launching Minecraft...
I'm hiding!
[TLauncherManager] mods after 
[InnerMinecraftServersImpl]  search changers of the servers
read servers from servers.dat [Server(name=chyma2, address=gimmethesauce.aternos.me, ip=gimmethesauce.aternos.me, port=null, hideAddress=false, acceptTextures=0)]
[InnerMinecraftServersImpl]  prepare inner servers
save servers to servers.dat
[Launcher] Starting Minecraft 1.17-OptiFine_HD_U_G9_pre17...
[Launcher] Launching in: C:\Users\soufi\AppData\Roaming\.minecraft
Starting garbage collector: 213 / 314 MB
Garbage collector completed: 40 / 314 MB
[Launcher] Processing post-launch actions. Assist launch: true
===============================================================================================
[13:42:33] [main/INFO]: Loading tweak class name optifine.OptiFineTweaker
[13:42:33] [main/INFO]: Using primary tweak class name optifine.OptiFineTweaker
[13:42:33] [main/INFO]: Calling tweak class optifine.OptiFineTweaker
OptiFineTweaker: acceptOptions
OptiFineTweaker: injectIntoClassLoader
OptiFine ClassTransformer
OptiFine ZIP file: C:\Users\soufi\AppData\Roaming\.minecraft\libraries\optifine\OptiFine\1.17_HD_U_G9_pre17\OptiFine-1.17_HD_U_G9_pre17.jar
OptiFineTweaker: getLaunchArguments
OptiFineTweaker: getLaunchTarget
[13:42:33] [main/ERROR]: Unable to launch
java.lang.ClassNotFoundException: net.minecraft.client.main.Main
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:186) ~[launchwrapper-of-2.2.jar:2.2]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_51]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:155) [launchwrapper-of-2.2.jar:2.2]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30) [launchwrapper-of-2.2.jar:2.2]
Caused by: java.lang.UnsupportedClassVersionError: net/minecraft/client/main/Main has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_51]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760) ~[?:1.8.0_51]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:177) ~[launchwrapper-of-2.2.jar:2.2]
	... 6 more
Here I am!
[VersionManager] Refreshing versions locally...
[VersionManager] Versions has been refreshed (9 ms)
[Launcher] Minecraft closed with exit code: 1
[Launcher] Launcher exited.
flush now
flush now

**Comment by mrktospl** [comment]
you need to install java 16 and make your minecraft installation use it. i don't know how would you do it though because you're using a cracked launcher

**Comment by weaksou** [comment]
> you need to install java 16 and make your minecraft installation use it. i don't know how would you do it though because you're using a cracked launcher

I did it, but it keeps crashing idk why

**Comment by KaiAF** [comment]
we dont provide support for cracked launchers.
