### ISSUE TITLE
No tinted glass connected tecture

### ISSUE THREAD

**Issue by Julnz** [sp614x/optifine#5733]
Tinted glass does not connect texture. I placed some down for a build and still saw the lines. This may be intentional, or it could be something yet to be added, or someone could have already reported this. Just thought I would let you know lol

**Comment by KaiAF** [comment]
It's going to be fixed in the next preview. #5702.

**Comment by Julnz** [comment]
> It's going to be fixed in the next preview. #5702.

ok thanks lol
