### ISSUE TITLE
[Bug] Entities not visible when taking a screenshot

### ISSUE THREAD

**Issue by KegaroUwU** [sp614x/optifine#5734]
## Description of Issue

No entities are shown, not mobs, no arrows, no items, not even the player or the item they hold
## Steps to Reproduce
1. Take a screenshot

## OptiFine Version

OptiFine HD U G9 pre17
## Installation Method

Standalone Installer

## F3 Debug Screenshot

![2021-06-09_11 23 08](https://user-images.githubusercontent.com/85635677/121393048-8f439800-c915-11eb-9994-e07e8432df51.png)
As seen, it shows i'm looking at a pig which is in fact not visible
![2021-06-09_11 23 30](https://user-images.githubusercontent.com/85635677/121393200-be5a0980-c915-11eb-9d73-0e5df306e7c0.png)
And that is what it looks like if i put the camera on 3rd person

## Prior Testing

Does this happen in OptiFine standalone? Yes
Does this happen in Vanilla without OptiFine? No

**Comment by KaiAF** [comment]
Can you provide a screenshot? And also one with the f3 menu open?

**Comment by KegaroUwU** [comment]
> Can you provide a screenshot? And also one with the f3 menu open?

Just updated the issue with it

**Comment by CorentinMouchel** [comment]
https://www.youtube.com/watch?v=1w7wdRGdBss
Check out, I recorded the bug if you wonna see

**Comment by KaiAF** [comment]
This bug is caused by changing your screenshot size to anything but default and taking a screenshot

**Comment by KaiAF** [comment]
I am pinning this issue because so many people are reporting it and it's causing a lot of duplicates. This does not mean that its a bug that is a huge priority for 1.17. In fact, sp614x might ask me to unpin it, I do not know.

**Comment by sp614x** [comment]
Fixed, coming in next preview.
