### ISSUE TITLE
[BUG] Major chunk loading issues when switching dimensions

### ISSUE THREAD

**Issue by T43omen** [sp614x/optifine#5737]
## Description of Issue
Chunks stop loading after leaving the nether? 

## Steps to Reproduce
load world (my render distance was 22 here)
enter nether
leave nether
bad chunk loading

## OptiFine Version
Latest version for 1.17 at the time of writing (1.17 G6 pre18)

## Installation Method
opened .jar and clicked install

## F3 Debug Screenshot
![2021-06-09_14 08 47](https://user-images.githubusercontent.com/85641984/121406811-9f1aa680-c92c-11eb-9c45-44f18c2b8963.png)

## Prior Testing
Does this happen in Vanilla without OptiFine? no.

## Additional Information
none that I can think of

**Comment by reatmon** [comment]
I see the same thing.  In fact, I see it both entering and leaving the nether.  Exiting the game (not quitting completely) and coming back in fixes the issue, but I am having to do that every time I gate travel.

**Comment by Optifineuser246** [comment]
I had this happen without travelling between dimensions sometimes as well

**Comment by mckellen98** [comment]
Also having this issue! Hopefully it gets fixed soon considering how severe it is.

**Comment by SeaOfPixels** [comment]
I've encountered this too. Pretty huge issue, though notably seems to only happen in singleplayer worlds.

**Comment by bigsoda2005** [comment]
I am also having this issue.

**Comment by KaiAF** [comment]
Also this seems to be already reported: #5757. And the other issue sp responded too and has a bit more information I think.
