### ISSUE TITLE
When hit and supposed to be dimmed, glow squids continue to have dynamic lighting

### ISSUE THREAD

**Issue by dragonsflame246** [sp614x/optifine#5741]
## Description of Issue

When you hit a glow squid and its supposed to be dimmed, it continues to emit light when dynamic lighting is on.

## Steps to Reproduce
Spawn a glow squid in a dark area and punch it

## OptiFine Version
OptiFine HD U G9 pre18

## Installation Method
Standalone installer

## F3 Debug Screenshot
![optifine bug](https://user-images.githubusercontent.com/85643968/121414793-0ccad080-c935-11eb-9659-bb22f20a537a.png)

**Comment by sp614x** [comment]
Fixed
