### ISSUE TITLE
Vine texture is completely missing 

### ISSUE THREAD

**Issue by tenshiaka** [sp614x/optifine#5742]
## Description of Issue
Vine texture appears to be missing 

## OptiFine Version
Pre 18 for 1.17

## Installation Method
Standalone installer

![2021-06-09_21 00 29](https://user-images.githubusercontent.com/64901373/121415277-d9556980-c967-11eb-97e5-236a4592275d.png)

## Prior Testing
<!-- If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
- No

**Comment by KaiAF** [comment]
turn off your resource pack, does that help?

**Comment by tenshiaka** [comment]
> e

it does not

**Comment by Zedanity** [comment]
I had this issue a while back but I believe it was fixed in newer pre-versions.

**Comment by KaiAF** [comment]
Seems to be fixed in the recent preview version.

**Comment by tenshiaka** [comment]
> Seems to be fixed in the recent preview version.

it has not though
![2021-06-15_20 48 37](https://user-images.githubusercontent.com/64901373/122107253-2aa7a200-ce1b-11eb-8519-da959f15a905.png)
