### ISSUE TITLE
[Bug / Missing Feature] CIT Support for Axolotl Buckets

### ISSUE THREAD

**Issue by SeaOfPixels** [sp614x/optifine#5746]
There is no support for Axolotl Bucket cit like there is for Tropical Fish Bucket cit.

**Properties file layouts that should be making this work:**
type=item
matchItems=axolotl_bucket
texture=wild
nbt.tag.Variant=1

type=item
matchItems=axolotl_bucket
texture=gold
nbt.tag.Variant=2

type=item
matchItems=axolotl_bucket
texture=cyan
nbt.tag.Variant=3

type=item
matchItems=axolotl_bucket
texture=blue
nbt.tag.Variant=4

**The only way to make these show in-game is to run the commands:**
/give @s axolotl_bucket{tag:{Variant:1}}
/give @s axolotl_bucket{tag:{Variant:2}}
/give @s axolotl_bucket{tag:{Variant:3}}
/give @s axolotl_bucket{tag:{Variant:4}}

**Comment by DMgaming100** [comment]
you are using the worong entity paramiter, it's 
 
 nbt.EntityTag.Variant=4
 
 and not
 
 nbt.tag.Variant=4

**Comment by SeaOfPixels** [comment]
That doesn't work either.

**Comment by Exspactor** [comment]
I have made a pack that has it and it works if you have nbt.Variant=1 etc
