### ISSUE TITLE
[1.17 Bug] Dimensional Loading Screens are broken

### ISSUE THREAD

**Issue by SeaOfPixels** [sp614x/optifine#5747]
When using a resource pack with dimension-exclusive loading screens, the texture bugs out and shows the "icons.png" texture from said resource pack instead of the designated loading screen texture from "optifine/gui/loading".

**Comment by pellomc** [comment]
true coño

**Comment by SeaOfPixels** [comment]
Would like to bump this since the visual glitches in place of the dimensional loading screens have gotten worse as Optifine 1.17 has developed. Instead of using the "icons.png" texture it's now using various font textures which is visually staggering/jarring for some users of my resource pack, especially since it happens every time you load into a world or change dimensions.
