### ISSUE TITLE
[Bug] Entities disappear after taking an screenshot

### ISSUE THREAD

**Issue by EdgarsFeic69** [sp614x/optifine#5749]
## Description of Issue
Entities disappear after taking an screenshot with screenshot size 2x

## Steps to Reproduce
1. Take an screenshot with screenshot size 2x

## OptiFine Version
Optifine HD G9_pre18 Ultra

## Installation Method
Using installer and also with the mod version

## Fabric/Forge Version
It also happens with Fabric
I used Fabric 0.11.3-1.17

## OptiFabric Version
Optifabric 1.11.1

## F3 Debug Screenshot

<blockquote class="imgur-embed-pub" lang="en" data-id="a/Hu8OYs2"  ><a href="//imgur.com/a/Hu8OYs2">Optifine-Bug-1.17</a></blockquote>

**Comment by KaiAF** [comment]
#5734
