### ISSUE TITLE
Entities Disappearing when taking enhanced screenshots.

### ISSUE THREAD

**Issue by WingedHarmony** [sp614x/optifine#5752]
Unsure on whether this has been addressed or not, but it seems that **when taking a screenshot with 2x the resolution (and I assume higher) on the newest versions, all entities become invisible, including the player, and there is no way to fix it outside of restarting Minecraft.** It happens on both of the computers I tested it on, and it worked before updating to 1.17, so I'm unsure what's causing it.

https://user-images.githubusercontent.com/64495513/121446278-24b84980-c961-11eb-864f-739cff72313e.mp4

**Comment by KaiAF** [comment]
Already addressed #5734
