### ISSUE TITLE
Minecraft crashes when exiting to another app

### ISSUE THREAD

**Issue by JarrodLJS** [sp614x/optifine#5754]
## Description of Issue
When exiting minecraft fullscreen to another app e.g "chrome" game will close and mention Unexpected error has occurred and game has crashed, exit code: 0.

## Steps to Reproduce
1. Open minecraft
2. Alt+tab to another app
3. Minecraft crashed

## OptiFine Version
OptiFine HD U G9 pre18

## Installation Method
Used the standalone installer

## Log Files/Crash Reports
https://drive.google.com/file/d/1sSNrU8WiQPrax_H4CwXfUfn9JUAqfEPR/view?usp=sharing

## F3 Debug Screenshot
![image](https://user-images.githubusercontent.com/85662175/121465305-26792000-c9e8-11eb-906a-4283ab36b113.png)

## Prior Testing
Only happens when in optifine

**Comment by Husselbeh** [comment]
I get a similar issue to this. Doesn't just happen in Optifine for me. Usually for me though it's after a while of being AFK in another app with Minecraft minimised in the background.

**Comment by hollmanovec** [comment]
This bug has occured to me too, often after longer period of inactivity ingame

**Comment by KaiAF** [comment]
I am closing this as the author of the issue has not replied to it.
