### ISSUE TITLE
Possibility for alpha support for font

### ISSUE THREAD

**Issue by EskiMojo14** [sp614x/optifine#576]
Is it possible to support alpha (transparency) for the font? It would allow for use of antialiasing which would make fonts look much smoother. It appears to be supported in the advancements dialog (added in 1.12 snapshots) and nowhere else.
Universal support for alpha in fonts would allow fonts to look much cleaner.

**Comment by sp614x** [comment]
Using smooth filters (bilinear) when downscaling HD fonts and GUI elements can also be added.

**Comment by sp614x** [comment]
No blend vs blend

![image](https://user-images.githubusercontent.com/16635441/28415653-f43bf966-6d50-11e7-893c-7af9eb6358a0.png)

**Comment by sp614x** [comment]
a bit subtle: 
![image](https://user-images.githubusercontent.com/16635441/28416451-54e85c2a-6d54-11e7-9b2c-dfc8f3913049.png)

**Comment by EskiMojo14** [comment]
Subtle, but I'd say a definite improvement :)

**Comment by sp614x** [comment]
Option OK?

```
Alpha Blending
==============

When enabled the font will use alpha blending

  # Alpha blending
  blend=<true|false>
```

**Comment by EskiMojo14** [comment]
Looks fine :) Will it be an option per client, or resourcepack?

**Comment by sp614x** [comment]
The option is in `ascii.properties`

**Comment by EskiMojo14** [comment]
Great 👌

**Comment by sp614x** [comment]
Updated preview C5 for 1.12
 - added font alpha blending
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/hd_fonts.txt#L54

**Comment by sp614x** [comment]
Smooth font scaling can be enabled with `ascii.png.mcmeta`
```
{ 
   "texture": {
      "blur": true,
      "clamp": true
   }
}
```
