### ISSUE TITLE
Custom Sky doesn't work in version 1.17

### ISSUE THREAD

**Issue by Rotmans0258** [sp614x/optifine#5761]
Hey,
I downloaded a texture pack (dramatic sky 1.17) and it doesn't show me the clouds and the stars.
It just changed the sun and moon.
I went into options > video settings > quality > custom sky: ON.
And it still doesn't work. 
I downloaded a different texture pack and still don't see the clouds and stars.
I'm not sure if I did something wrong or it just doesn't work in version 1.17.
Thank You :)

**Comment by KaiAF** [comment]
Already reported I believe #5748.
