### ISSUE TITLE
[BUG] Chunks fail to load when render distance set above 32 chunks

### ISSUE THREAD

**Issue by bigsoda2005** [sp614x/optifine#5762]
## Description of Issue
Chunks fail to load when render distance set above 32 chunks. "Waiting for chunk" message appears in f3 menu

## Steps to Reproduce
1. Set render distance over 32
2. try to travel in any direction

## OptiFine Version
1.17 preview 18 - 19

## Installation Method
double click .jar. click install

## Other Installed Mods
Merged-Damage-Sounds.zip

## F3 Debug Screenshot
[screenshot](https://imgur.com/0jZamP9)

- Does this happen in Vanilla without OptiFine?
No

**Comment by KaiAF** [comment]
I could reproduce this

**Comment by KaiAF** [comment]
Related #5757
