### ISSUE TITLE
[Graphics] Entities turn permanently invisible upon Screenshooting with the Spyglass with increased screenshot size

### ISSUE THREAD

**Issue by OfficialPixelBrush** [sp614x/optifine#5763]
## Description of Issue
All entities but also the Player's hand and similar turn invisible upon screenshotting while zoomed in using the spyglass, if the Screenshot Size is increased above default

## Steps to Reproduce
1. Set Screenshot scale to 4x
2. Zoom in using Spyglass
3. Take a screenshot
4. All entities and even the player's hand turns invisible

## OptiFine Version
1.17 Optifine HD U G9 pre18

## Installation Method
Standalone

## F3 Debug Screenshot
![2021-06-10_19 48 08](https://user-images.githubusercontent.com/23031327/121573023-0ddb2b00-ca25-11eb-9c81-9cca81ba681c.png)

## Prior Testing
This does not occur in Vanilla

**Comment by KaiAF** [comment]
Already addressed here: #5734
