### ISSUE TITLE
Failure to load past 80%

### ISSUE THREAD

**Issue by JonCrafting** [sp614x/optifine#5764]
## Description of Issue
I'm having an issue with running Optifine 1.17 pre18 with the latest 1.17 Minecraft release.
I can load my vanilla single player world fine without Optifine, but if I try to load it with Optifine 1.17 pre18, it stalls at 80% on the red Mojang loading screen.

## Steps to Reproduce
1. With the Minecraft Launcher, select Optifine 1.17-OptiFine_HD_U_G9_pre18
2. Select Play
3. Red Mojang loading screen appears and status bar gradually fills up and then stops about 80% of the way.

## OptiFine Version
Optifine 1.17-OptiFine_HD_U_G9_pre18

## Installation Method
1) Downloaded from Optifine Page
2) double clicked the .jar file
3) selected install

## Fabric/Forge Version
n/a

## OptiFabric Version
n/a

## Other Installed Mods
none

## Log Files/Crash Reports
https://paste.ubuntu.com/p/kJGMjTnH4W/

## F3 Debug Screenshot
Minecraft does not load, so unable to get to this step.

## Prior Testing
Vanilla Minecraft 1.17 without Optifine loads successfully. 
Vanilla Minecraft 1.16.5 with Optiine 1.16.5 loads successfully. 

## Additional Information
Not using Forge/Fabric, or any other mods

**Comment by JonCrafting** [comment]
Thanks for the quick response. I miss wrote, and should have said .jar file (I have edited the OP).

Regarding the resource packs, I have not installed any specific resource packs. Prior to updating my 1.16.5 world to 1.17 I did use MCA Selector to delete certain unused, but previously loaded in chunks so that they would reload with new 1.17 content. This is the only "non-vanilla" thing I have done to the game other than use optifine.

**Comment by JonCrafting** [comment]
How does one, fix how texture loading?

**Comment by KaiAF** [comment]
try going on vanilla and sibling the resource pack, then try launching optifine 1.17 again. See if that helps

**Comment by JonCrafting** [comment]
I have uninstalled/reinstalled minecraft and am now able to get past the 80% load-screen and launch the game. Game performance on the other hand is a miserable comparison to what it had been on 1.16.5 and I'm still trouble shooting things to try and restore performance. I've downgraded all settings to as minimal as I can and still suffering.
Anyhow, thanks for the help and advice. Wish me luck.
