### ISSUE TITLE
[Bug] No CEM support for glow squid

### ISSUE THREAD

**Issue by hg456wilkos** [sp614x/optifine#5765]
## Steps to Reproduce
Adding a glow_squid.jem block model in a resource pack
Doesn't register in game and won't change the glowsquid model

## OptiFine Version
1.17 G6 pre18

## Installation Method
stand alone installer to create an optifine profile

## F3 Debug Screenshot
![2021-06-10_21 37 50](https://user-images.githubusercontent.com/85708541/121593778-2bfc5780-ca34-11eb-87aa-da60eebefc63.png)

## Prior Testing
Optifine exclusive feature

**Comment by sp614x** [comment]
Added support for glow_squid.
