### ISSUE TITLE
[1.17] My spyglass is broken it shows the border of it but it wont zoom

### ISSUE THREAD

**Issue by kevik66** [sp614x/optifine#5767]
## Steps to Reproduce
1. What do you do...
2. ...to find this bug?

## Additional Information

![2021-06-10_21 31 57](https://user-images.githubusercontent.com/85717446/121617965-f5bed800-ca33-11eb-80d6-3399ca09859b.png)

**Comment by KaiAF** [comment]
Make sure Dynamic Fov is enabled

**Comment by KaiAF** [comment]
#5736 Reported here.
