### ISSUE TITLE
[crash] error: could not create java virtual machine

### ISSUE THREAD

**Issue by pesegolsson** [sp614x/optifine#5771]
## Description of Issue
optifine g9 pre18 wont start, getting 
error: could not create java virtual machine
error: a fatal exeption has occurred, program will exit.

and then minecraft gives a kod :0

have tried installing java 16, and pointed optifine at it and same issue.

never had this issue with any other version of optifine so i'm at a loss what might cause this.

## Steps to Reproduce
1. installed optifine and tried to launch it
2. i have no idea, but it happens every time for me?

## OptiFine Version
optifine_hd_u_g9_pre18

## Installation Method
stand alone and in mod folder, same result on both

## Fabric/Forge Version
tried the latest fabric

## OptiFabric Version
1.11.1

## Log Files/Crash Reports
as it never launches there are no log files

**Comment by KaiAF** [comment]
Go to the installation settings and make sure that the java version is set to 16

**Comment by pesegolsson** [comment]
done that, same issue. i even uninstalled java 8 to make sure that it wouldn't interfere. the only .log file that gets updated when i try to run optifine is the launcher_cef_log.txt and it contains these lines:

[0611/155736.150:INFO:main_context.cpp(136)] CEF initialized successfully.
[0611/155736.150:INFO:main_context.cpp(138)] CEF version: 85.3.13+gcd6cbe0+chromium-85.0.4183.121
[0611/155741.026:WARNING:angle_platform_impl.cc(48)] compileToBinary(257): 
C:\fakepath(107,1-13): warning X3557: loop only executes for 1 iteration(s), forcing loop to unroll
C:\fakepath(102,1-13): warning X3557: loop only executes for 1 iteration(s), forcing loop to unroll

and not all the time, just sometimes which i also find wierd! not sure if that is helpful though?

**Comment by Team-Nemezis** [comment]
same issue

**Comment by pesegolsson** [comment]
finally got it running, i was playing around with the jvm arguments and the G1HeapRegionSize was set to 64M and that was a no go, changed it to G1HeapRegionSize=32M and it started just fine even using the bundled runtime.

hopefully this might help someone else as well
