### ISSUE TITLE
[1.17 Chunks] Chunks Flicker

### ISSUE THREAD

**Issue by by-moan** [sp614x/optifine#5772]
## Steps to Reproduce
1. I used a modified datapack that allows getting more than -200 blocks on 1.17
2. When I go to another chunk it flashes like its reloading chunks

## OptiFine Version
1.17 HD G9_pre18 Ultra
## Installation Method
I extracted the mod file and added the jar to mc

## Fabric/Forge Version
Standalone

## Other Installed Mods
None

## Log Files/Crash Reports
https://pastebin.com/Vx4JbPub

## F3 Debug Screenshot
![2021-06-11_04 02 23](https://user-images.githubusercontent.com/67838092/121676863-038f5000-ca6a-11eb-9ebb-2d68a9bb0e91.png)

## Prior Testing
No it doesn´t happen without optifine

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
  Yes
- Does this happen without any mods at all?
   Yes
- Does this happen in OptiFine standalone?
- Yes
- Does this happen in Vanilla without OptiFine?
- No
   - Does the issue still happen with only the remaining mods installed?
     Doesn´t happen with optifine

https://cdn.discordapp.com/attachments/423433009568546827/852861689866747925/video0.mov

I recorded on phone because it freezes while recording the issue

**Comment by KaiAF** [comment]
I cant download the video, but this could be related to #5768?
