### ISSUE TITLE
[1.17] Taking a screenshot in F1 mode hides hand forever

### ISSUE THREAD

**Issue by CherryDotBTW** [sp614x/optifine#5774]
I noticed this bug while playing in a 1.17 SMP server with the latest optifine preview version, OptiFine HD U G9 pre19. Your hand is hidden when you hide your ui (F1 by default), and this is normal. But, when I take a screenshot while my hud is hidden, the hand doesn't return after bringing back the hud. The only way that I have found to restore the hand, is to restart my game. The problem also occurs in SSP worlds.

This happens every time for me, so it should be pretty easy to reproduce. Just press F1 to hide the hud, F10 to take a screenshot, and F1 again to restore the hud, and the player's hand will stay invisible.

I am not using any mods other than optifine which I installed using the standalone installer.

I don't believe there are any log files since this isn't a crash? Not entirely sure.

I have tested this in purely vanilla 1.17 release, and it doesn't happen there.

![image](https://user-images.githubusercontent.com/62699431/121710318-6831c580-cad1-11eb-9430-913eccad1ffd.png)

I realise that this is only a minor issue, but it is annoying because I enjoy taking screenshots, and I thought you might want to be made aware of it. I hope this is helpful :)

**Comment by KaiAF** [comment]
This bug is caused by having the screenshot size anything more than default. #5734
