### ISSUE TITLE
[Chunks] [1.17] Chunks not loading after leaving spawn area

### ISSUE THREAD

**Issue by PainApp1e** [sp614x/optifine#5775]
## Description of Issue

in optifine pre17-19 in singleplayer, if you load up the world no matter the settings, chunks beyond the spawn area dont generate, it is especially visible in creative mode.

## Steps to Reproduce
1. Create a new world on optifine 1.17
2. Go in one direction

## OptiFine Version
optifine 1.17 pre19

## Installation Method
Open installer jar

## F3 Debug Screenshot
![2021-06-11_18 11 01](https://user-images.githubusercontent.com/85756033/121716563-74714f00-cae0-11eb-8148-affea5d91e73.png)

## Prior Testing
Does not happen in vanilla or in optifine 1.16.5

**Comment by KaiAF** [comment]
Already addressed here: #5757
