### ISSUE TITLE
[REQUEST] Allow PNGs to be used as capes

### ISSUE THREAD

**Issue by ili-codes** [sp614x/optifine#578]
I'm trying to use a PNG cape texture I downloaded as an Optifine cape, but there is no option for that. Why? Can you add that, please?

**Comment by MisterQuiggly** [comment]
I think the answer to your "why" part is because people would abuse it. People already use banners to have reproductive organs on them. With this ability it would get too abused, but it would be nice.

**Comment by BlazyDoesDev** [comment]
I say they should do it.

**Comment by ili-codes** [comment]
@MisterQuiggly If people are already using banners to draw reproductive organs, wouldn't they be drawn either way? If it's only banners vs. having PNGs enabled? They could add something like "Don't abuse the banners or PNGs, please don't draw: " to the TOS and have a list of things that can not be shown on banners / pngs. If they don't follow that, then they could get their cape deactivated.

**Comment by sp614x** [comment]
The reasons for not allowing custom PNG is:
- to avoid conflicts with the official capes (the mojang logo is also not allowed on a banner)
- the banner capes are creative and their style matches the game design

**Comment by ili-codes** [comment]
I'll just find a similar banner design to the MineCon 2016 cape then. Also... it'd be nice to have a way to preview how your cape looks on your skin before you apply it. Thanks for the help!

**Comment by sp614x** [comment]
A 3D preview with the current skin is on the TODO list.

**Comment by ili-codes** [comment]
Wonderful! Let me know when it's out! Thanks for the help, as well!
