### ISSUE TITLE
dynamic FOV with spyglass issue

### ISSUE THREAD

**Issue by AshFox** [sp614x/optifine#5780]
when dynamic FOV is off spyglass wont work
![image](https://user-images.githubusercontent.com/82912380/121752270-ae098080-cb07-11eb-9abb-1cf2d370a9f8.png)
![image](https://user-images.githubusercontent.com/82912380/121752191-874b4a00-cb07-11eb-83b7-9b602d25f337.png)

**Comment by KaiAF** [comment]
Already addressed here: #5736
