### ISSUE TITLE
[Category] Short description

### ISSUE THREAD

**Issue by prorbo** [sp614x/optifine#5784]
MInecraft Not Starting(GLFW error 65543)
Vinella Minecraft is Working fine but OptiFine is not working.
I use TLauncher and using Alredy provided verson of Optifine.(I use Linux) 

## OptiFine 1.17

![Screenshot from 2021-06-12 17-16-16](https://user-images.githubusercontent.com/85790163/121774883-23c22a80-cba2-11eb-9b76-ed3e37dc88e7.png)

**Comment by fayer3** [comment]
probably the same as #5739

**Comment by KaiAF** [comment]
We do not provide support for TLancher
