### ISSUE TITLE
[1.17] Connected Texture for Tinted Glass

### ISSUE THREAD

**Issue by AxeGt2802** [sp614x/optifine#5785]
## Description of the new feature
Make a connected texture for the Tinted Glass , like the others glasses.

**Comment by Zedanity** [comment]
This already exists for Optifine since pre18 of Optifine. Update to latest pre-version for this.

**Comment by KaiAF** [comment]
Tinted already has connected textures In recent previews

**Comment by AxeGt2802** [comment]
Oh Sorry ! I delete this
