### ISSUE TITLE
[1.17 Bug] Spyglass not zooming when right-clicked

### ISSUE THREAD

**Issue by StrixTyphoon** [sp614x/optifine#5786]
## Description of Issue
The spyglass will not zoom if right-clicked

## Steps to Reproduce
Use a spyglass

## OptiFine Version
pre21 version of 1.17 optifine

## Installation Method
included install

## Log Files/Crash Reports
https://pastebin.com/kirMGybP

## F3 Debug Screenshot
see screenshot attached [
![Badlion Client Screenshot 2021 06 12 - 23 23 08 33](https://user-images.githubusercontent.com/85808692/121790245-52a5c400-cbd5-11eb-93aa-90fbc45a7611.png)
](url)
the filename says im using badlion but thats just nvidia geforce experience bugging out 

## Prior Testing
it works as normal on vanilla

## Additional Information
i am using a resource pack that changes the look of the spyglass when right-clicked 
resource pack:
[VanillaTweaks_r395324.zip](https://github.com/sp614x/optifine/files/6643000/VanillaTweaks_r395324.zip)

**Comment by KaiAF** [comment]
Do you have Dynamic FOV enabled?

**Comment by StrixTyphoon** [comment]
no i do not

**Comment by KaiAF** [comment]
Reported here: #5736. I am not sure if thos is a bug, or intentional to be honest.
