### ISSUE TITLE
i cant log in into my optifine cape account

### ISSUE THREAD

**Issue by F0stylele** [sp614x/optifine#579]
whenever i try to get in my optifine cape account it wouldnt work i tried all the solutions possible including reseting my email  BTW i reset my email only cuz my old one wouldnt work. Even though i cant log in into my cape account my cape would show in game,
the error returned when trying to get into my cape account is the invalid credentials one

**Comment by sp614x** [comment]
To change the cape design
1. Go to: https://optifine.net/cape
2. Login with the Minecraft email(username) and password
The username/password are verified by the Mojang login servers, they decide if the login is valid or not.
After several failed attempts the Mojang login server may temporarily block the account, up to 24h.

**Comment by 32Hat** [comment]
Can Anyone get me a cape LMao not gonna happen
