### ISSUE TITLE
[1.17] Stained and Tinted glass textures are entirely transparent

### ISSUE THREAD

**Issue by TessAbess** [sp614x/optifine#5792]
## Description of Issue
Stained and tinted glass blocks and panes are invisible; they are placeable, and an outline appears where one is placed, but there is no notable difference in the game. As if there's nothing there at all.

## Steps to Reproduce
1. grab/craft stained or tinted glass
2. place it down

## OptiFine Version
I'm using the newest version, for 1.17

## Installation Method
I used the included standalone installer

## F3 Debug Screenshot

![2021-06-13_09 07 57](https://user-images.githubusercontent.com/85838917/121814644-ff5c6180-cc26-11eb-80e9-1f8c9da155af.png)

## Prior Testing
This does not happen in vanilla without optifine

**Comment by fayer3** [comment]
could you retest with pre21. It does work for me.

**Comment by KaiAF** [comment]
this bug was fixed in pre 18 or something and now we are on pre 21.
