### ISSUE TITLE
[CEM] [1.17] Cannot attach multiple parts to a single bone

### ISSUE THREAD

**Issue by DraminOver** [sp614x/optifine#5793]
## Description of Issue
Attaching multiple parts (or `.jpm` files) to a single bone does not work as it should when compared with 1.16.
When used, it will instead replace the previous models, and only render the bottom most attachment.

## Steps to Reproduce
1. Try the provided testing resource pack in both 1.16 and 1.17 to see the issue.
[Test.zip](https://github.com/sp614x/optifine/files/6644266/Test.zip)

## OptiFine Version
OptiFine HD U G9 pre21

## Installation Method
Standalone installer

**Comment by ewanhowell5195** [comment]
this isn't a bug with attach, that works fine. This is a bug where optifine only loads the last part if you have more than one. 

In this example model however, you can bypass this, by doing:

```json
{
	"part": "head",
	"id": "head",
	"invertAxis": "xy",
	"translate": [0, -18, 0],
	"boxes": [
		{"coordinates": [-4, 18, -4, 8, 8, 8], "textureOffset": [0, 0]}
	],
        "model": "creeper_head.jpm",
	"attach": "true"
}```

**Comment by TheVoyde** [comment]
I can confirm that this is an issue I'm having as well. Many mob custom models are only displaying one element if attached to the same part.

**Comment by ZenithRogue** [comment]
Updated the issue title and description to describe the underlying issue

**Comment by w11shes** [comment]
How do I add another jpm head model in this case?

**Comment by w11shes** [comment]
> Updated the issue title and description to describe the underlying issue

In my duplicate #6251, the problem is slightly different. This release shows how to attach just one jpm model, and I have several.

**Comment by TheVoyde** [comment]
In order to build upon existing parts you would use sub-models instead of multiple parts. For example, pre-1.17 a two-part head may have looked like this:
`{
	"part": "head",
	"id": "skull",
	# Part Model Definition
},
{
	"part": "head",
	"id": "jaw",
	# Part Model Definition
}`

You would now write it as
`{
	"part": "head",
	"id": "skull",
	# Part Model Definition,
	"submodels":
	[
		{
			"id": "jaw",
			# Part Model Definition
		}
	]
}`

**Comment by sp614x** [comment]
Fixed, coming in next preview.
