### ISSUE TITLE
3d Armor model

### ISSUE THREAD

**Issue by MrTvistYT** [sp614x/optifine#5799]
Please, many people, including me, need to create 3d models of the armor, and link it to cit.

**Comment by MrTvistYT** [comment]
I know that this request is already there, there is a mark "to do".  But the request is already too old, it was created in 2017.

**Comment by Peca21** [comment]
#561 
Is this it?

**Comment by MrTvistYT** [comment]
> [# 561](https://github.com/sp614x/optifine/issues/561)
> Это оно?
Yes

**Comment by KaiAF** [comment]
This was already suggested, it's probably still on sp614x's to-do list. #561
