### ISSUE TITLE
Glowing effect glitch with OptiFine for 1.9

### ISSUE THREAD

**Issue by Fanawtik** [sp614x/optifine#58]
The glowing effect is a new effect added in 1.9 that's supposed to surround all players/entities that have it in a glowing frame which can be seen through walls. However, when I use OptiFine, it becomes more than just a frame and covers every single pixel on their body.

**Comment by sp614x** [comment]
The glowing outline effect is not compatible with shaders and Fast Render.
As a workaround when shaders or Fast Render are enabled OptiFine uses a simpler version of the effect which makes the whole entity glow. With shaders the entity is visible through blocks, but it may or may not glow depending on the shader pack.
