### ISSUE TITLE
[Armor] 3d

### ISSUE THREAD

**Issue by MrTvistYT** [sp614x/optifine#5802]
## I need to create 3d armor

I need to rename the armor (for example the chestplate) in the anvil, after the armor to replace the model. A similar request was via CEM, request # 561.

**Comment by KaiAF** [comment]
Is this a suggestion? If so, it's already suggested and on the to do list.

**Comment by MrTvistYT** [comment]
If this is possible to implement, then the question, if this cannot be done, then you need to create.  I saw that there is something similar to # 516, but there seems to be a different principle.  There through the entity (cem).

**Comment by KaiAF** [comment]
This is already considered on the to-do list. There are a bunch of other things on the to-do list that needs to be worked on also, including OptiFine 1.17. #561
