### ISSUE TITLE
[1.17] Entities goes invisible when taking screenshots with x2, x3 and x4 screenshot size

### ISSUE THREAD

**Issue by imjohne** [sp614x/optifine#5804]
## Description of Issue
Entities becomes invisible when taking screenshots if you set the screenshot size anything other then default

## Steps to Reproduce
Take a screenshot with x2, x3 or x4 Screenshot size and all the entities will become invisible
(Must restart game to get entities visible again) Singleplayer and Multiplayer.
https://www.youtube.com/watch?v=nTPQn8FO4uk Me showing how I recreated it.
## OptiFine Version
preview_OptiFine_1.17_HD_U_G9_pre21

## Installation Method
Standalone from the website

## F3 Debug Screenshot
https://imgur.com/a/YwIQikj doesn't come up any errors

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
nope cause the screenshot size can't be changed in vanilla...

**Comment by KaiAF** [comment]
Already addressed here: #5734.
