### ISSUE TITLE
[1.17] GLXBadFBConfig

### ISSUE THREAD

**Issue by MangyCat** [sp614x/optifine#5805]
## Steps to Reproduce
1. Run Minecraft Optifine 1.17
2. Wait for it to start.
3. Crash, and it didn't even get to the title screen it just gave me an error message
## OptiFine Version
I'm sorry, but I don't know which optifine version I'm using. I assume its 1.17 Optifine OptiFine HD U G9 pre21, And I tested it by installing OptiFine HD U G9 pre21 and the manually installed version had the same problem as that automatically installed one from tlauncher.

## Installation Method

To be completely honest with you, I'm using TLauncher 2.8.
I installed Optifine by going into the versions menu and clicking Optifine 1.17 which is a version included in TLauncher.
I installed Vanilla 1.17 before Optifine 1.17, because if you did that the Optifine 1.17 installation would reuse the vanilla 1.17 files.

## Log Files/Crash Reports
https://paste.ubuntu.com/p/fyS9hTqxrQ/

## F3 Debug Screenshot
How am I supposed to get that, if I cannot even run the optifine version?
Heres the 1.17 vanilla screenshot.
[https://imgur.com/tMnDkVm.png](url)

## Prior Testing
It works without issues in VANILLA 1.17, but optifine doesn't work in 1.17 it just gives me a error GLXBadFBConfig

## Additional Information
I'm using an Intel HD 2000 with a Intel celeron G530 on Ubuntu 21.04, It supports up to opengl 3.3, 1.17 works but optifine 1.17 doesn't work.
I'm using Kisak Mesa

**Comment by Dozer257** [comment]
I can confirm that this issue doesn't only happen tlauncher. I have the full version of Minecraft Java Edition on Ubuntu 16.04 (Xfce Desktop) and I do get this issue as well. I am running Ubuntu on a Chromebook using crouton just so you know.

**Comment by KaiAF** [comment]
#5739 already addressed there.
