### ISSUE TITLE
[Graphics] XP orbs display through blocks

### ISSUE THREAD

**Issue by tenshiaka** [sp614x/optifine#5809]
## Steps to Reproduce
Get some xp orbs with a surface behind them, move behind the surface

## OptiFine Version
PRE21 1.17

## Installation Method
included standalone installer

![2021-06-15_23 29 02 - Copia](https://user-images.githubusercontent.com/64901373/122134079-3a84ad80-ce3e-11eb-8003-0b23494c3988.png)
![2021-06-16_00 57 43 - Copia](https://user-images.githubusercontent.com/64901373/122134083-3c4e7100-ce3e-11eb-8467-18014e926a57.png)
![2021-06-15_22 42 23 - Copia](https://user-images.githubusercontent.com/64901373/122134086-3ce70780-ce3e-11eb-90cc-96c25365c50d.png)

**Comment by KaiAF** [comment]
Can you send a F3 debug menu screenshot?

**Comment by tenshiaka** [comment]
![2021-06-20_01 58 13](https://user-images.githubusercontent.com/64901373/122658231-06292e00-d16b-11eb-8ff1-3ed117d20e3d.png)
here

**Comment by KaiAF** [comment]
Does this happen on single player? Turn off your resource pack? I am not able to reproduce this.
![image](https://user-images.githubusercontent.com/60985521/122660976-60b29200-d14b-11eb-89fa-200b26eba78c.png)

**Comment by tenshiaka** [comment]
it was a texturepack, not really sure how changing the spyglass texture can make xp orbs render through blocks though?

**Comment by KaiAF** [comment]
could have been caused by fast render or render regions. I dont know
