### ISSUE TITLE
[1.17] Shaders unavailable

### ISSUE THREAD

**Issue by Promixius** [sp614x/optifine#5810]
## Description of Issue
Latest version of optifine for 1.17 unable to activate shaders as the button is greyed out and thus unavailable 
tried to create folders manually and relaunch the game but this did not work.

## Steps to Reproduce
Install latest optifine and launch it

## OptiFine Version
OptiFine HD U G9 pre21

## Installation Method
included standalone installer

## Other Installed Mods
No other mods installed.

**Comment by Cart3r1234** [comment]
Shaders do not work yet in 1.17; it says this in the changelog for all 1.17 optifine previews

**Comment by KaiAF** [comment]
This is because shaders are not yet available for 1.17, They are being worked on currently so that they could be

**Comment by nstringham** [comment]
@KaiAF is there an issue I can follow to be updated about 1.17 shaders

**Comment by KaiAF** [comment]
No github issue that I know of, but you can follow our twitter account for general updates. Or you can follow the discord optifine updates channel for them.
