### ISSUE TITLE
[1.17] pre21 - Chunks unloading differently - no "trails" [vanilla]

### ISSUE THREAD

**Issue by NaggingGullible** [sp614x/optifine#5811]
OS: Windows 10 x64 
Minecraft version: 1.17 
OptiFine build: OptiFine HD U G9 pre21 
Other mods?: No 
Shaders?: No 
Resource packs?: Rarely - happens without 
Last build 

I am playing vanilla Minecraft (aside from OptiFine) on a Realm. 
In the past, though the realm would only serve so many chunks to the player (12?), having the view distance set higher in OptiFine would prevent chunks from disappearing from view until the set distance (so trails of chunks would be left behind when flying, etc.). 
This no longer happens - instead, the chunks immediately unload when past the Realm's set distance - we cannot fly from one place to another, and look back at the starting location. 

I have attached photos showing the FORMER behavior, as well as a YouTube link showing the CURRENT behavior. 
![2020-12-10_14 46 56](https://user-images.githubusercontent.com/4163802/122134639-a0ecda00-ce04-11eb-87fd-9d57227ea552.png)

![2020-12-12_13 33 58](https://user-images.githubusercontent.com/4163802/122134607-92062780-ce04-11eb-918d-269ca9e60321.png)

![2020-12-14_14 48 33](https://user-images.githubusercontent.com/4163802/122134568-79960d00-ce04-11eb-8cca-5db663ecd90c.png)

Current behavior: 
https://www.youtube.com/watch?v=PDlZooeFRgI 

Thank y'all so much!

**Comment by NaggingGullible** [comment]
Sorry about the sub-par formatting, by the way. 

Here's my F3 screen: 
![2021-06-15_19 17 01](https://user-images.githubusercontent.com/4163802/122139332-58d2b500-ce0e-11eb-84e3-4b1a8ac27153.png)

**Comment by Cart3r1234** [comment]
I've noticed this too, the old behavior was a lot nicer IMO, so hopefully this new behavior is the unintended result.

**Comment by NaggingGullible** [comment]
> 
> 
> I've noticed this too, the old behavior was a lot nicer IMO, so hopefully this new behavior is the unintended result.

Yes!! Here's hoping :)

**Comment by Soft-Brick** [comment]
I was also very dissapointed to find this feature missing. I hope it will return! :)

**Comment by KaiAF** [comment]
Just a question. But wouldn't this cause more performance issues if it just has all the other chunks rendered in? 
And how the chunks are being unloaded, it seems like it's vanilla behavior

**Comment by Soft-Brick** [comment]
> 
> 
> Just a question. But wouldn't this cause more performance issues if it just has all the other chunks rendered in?
> And how the chunks are being unloaded, it seems like it's vanilla behavior

Regarding performace;
I have GTX1060 and 16GB of ram, which is the most common setup according to Steam Hardware Survey.
And with no shaders or recource packs I can play with 32 chunk render distance on single player at around 60fps.
So clearly performace is not that big of a deal

I am currently playing on a server that has view-distance of 10 (which is standard setting). 10 is quite low. When you play in such server, you can only see 10 chunk distance at any given moment. As soon as chunks leave that range they are immediantly unloaded. That indeed does appear to be vanilla behavior.

But in the past optifine would keep loaded chunks in cache, even if player leaves the area. And how many chunks are being kept  depends on render distance in video settings.

So, if you have reasonably powerful computer you can have render distance of 32 chunks. When you log in to a server with view distance of 10, you initially can see only 10 chunks far. But you can run around and old chunks are saved into cache instead of unloaded. Allowing you to see much farther - up to 32 chunks.

At least that is how I assume this works.

**Comment by NaggingGullible** [comment]
Sorry for the late response - I had a busy week. 

That's exactly it, Soft-Brick! You explained it way better than I did, haha. 

And yeah, performance is a non-issue, since it still depends on client-side render distance settings to determine how far out the chunks will stay cached. Also, if it makes any difference, I've been playing on a (non-gaming) laptop, and I get about 20-30 FPS normally (with OptiFine, anyway), and it's not noticeably lower when that feature is enabled and I have render distance set to 32. (64 did tend to cause framerate drops for me, though.) 

If it is getting put back, I wouldn't expect it to be back already (that'd be very unreasonable), but, for documentation purposes, I figure I should note that the issue is still present in OptiFine 1.17 HD U G9 pre23. 

If I had to guess, I'd say that maybe it's related to this pre21 changelog entry: " - fixed chunks not loading when changing dimension (#5757)" 
Of course, as weirdly sad as I am about this issue, that issue is clearly **WAY** more serious, haha. 

@KaiAF @Soft-Brick

**Comment by LoyalDeserter** [comment]
Also really missing this feature and hoping it gets added back.

**Comment by NovaPixell** [comment]
Are there some news about this? We have a survival server and all players need it D:

**Comment by NovaPixell** [comment]
Any updates?

**Comment by LoyalDeserter** [comment]
Is this being looked into?

**Comment by NovaPixell** [comment]
Will this feature implemented into optifine? As always

**Comment by LupusVirtute** [comment]
Was this fixed?

**Comment by Cart3r1234** [comment]
according to SP its not an optifine issue

**Comment by KaiAF** [comment]
Yeah the developer said that this isnt an optifine issue and because of that I'm just going to close this. There are fabric mods that allow chunk caching.

**Comment by lynrayy** [comment]
Send link to chaching mod please

**Comment by Luky584** [comment]
Fabric mod called Bobby might be the right solution for you.

> Bobby is a Minecraft mod which allows for render distances greater than the server's view-distance setting.
> 
> It accomplishes this goal by recording and storing (in .minecraft/.bobby) all chunks sent by the server which it then can load and display at a later point when the chunk is outside the server's view-distance.
> 
> Optionally, it can also use an existing single player world to load in chunks which the server has never sent before. To make use of this feature, simply rename the world folder (not the name of the world! the name of its folder!) to "bobby-fallback".

**Comment by NaggingGullible** [comment]
Shoot, sorry, I should have updated the ticket! I've been using Bobby since
it had about 10000 downloads, and it's been fantastic :)
