### ISSUE TITLE
Water source not extending flow of water

### ISSUE THREAD

**Issue by NonOfficial352** [sp614x/optifine#5812]
i had an area full of 1 deep water sources and then the flow was going down. but when i added blocks at the flowing point the water didnt extend to flow from the new last block position.

## Steps to Reproduce
1. create an area full of water sources 
2. let the water flow after few blocks.
3. add few blocks at the last

## OptiFine Version
1.17 Optifine HD U G9 pre21

## Installation Method
installed by clicking the downloaded jar file and then clicking install

## Log Files/Crash Reports
no crashes

![2021-06-16_13 31 05](https://user-images.githubusercontent.com/85988121/122181754-45275d00-cea7-11eb-8912-65675324c724.png)

## Prior Testing
<!-- If you've installed standalone:
-have not tested in vanilla

![2021-06-16_13 13 04](https://user-images.githubusercontent.com/85988121/122181903-66884900-cea7-11eb-9c45-43d13392c4ec.png)

**Comment by KaiAF** [comment]
I am not able to reproduce this

**Comment by NonOfficial352** [comment]
Well as you can see in the image. The area with dripstone block underneath had water sources above it. And the water was flowing down from the end. But as I put stone at the end the flow did not extend. The image proves it

**Comment by KaiAF** [comment]
Does this not happen in vanilla?

**Comment by NonOfficial352** [comment]
Have not tried in vanilla. I think it should not happen in vanilla

**Comment by KaiAF** [comment]
It's not exact, but it's similar enough. It happens in Vanilla, probably a bug with 1.17 or that's just how it is. I believe this can be reproduced in 1.16 also.
![image](https://user-images.githubusercontent.com/60985521/122661285-28f91980-d14e-11eb-8910-7efc92f9f842.png)
