### ISSUE TITLE
Text on signs disappears from some disstance

### ISSUE THREAD

**Issue by PotworekPL** [sp614x/optifine#5813]
## Description of Issue
From about 18 blocks you can't see text on signs

## Steps to Reproduce
First place sign with text on it, get some blocks away (DON'T USE OPTIFINE ZOOM TOO LOOK AT SIGN, IT BREAK EFFECT) and you will see text disappears. After you zoom by optifine you can see text from the distance, after unzooming it gets invisible again.

## OptiFine Version
Optifine_1.17_HD_U-G9_pre21

## Installation Method
into my mod folder, by fabric.

## Fabric/Forge Version
fabric-loader-0.11.3-1.17

## OptiFabric Version
optifabric-1.11.1

## Other Installed Mods
no more mods

## Log Files/Crash Reports
never crashed

## Prior Testing
this don't happen in vanilla

If you've installed using Forge/Fabric:
- Does this happen without other mods installed?
   - Only OptiFine, OptiFabric, and Fabric
- Does this happen without any mods at all?
   - Only Forge/Fabric by itself.
- Does this happen in OptiFine standalone?
   - Yes
- Does this happen in Vanilla without OptiFine?
   - No
- Have you tried using a binary search to find which mods cause this issue?
   - No more mods, only optifine

## Additional Information
I have only optifine installed, mc version: 1.17, tested on 1.16.5(newest optifine), my operating system: debian 10 backports. Happens on standalone too. I turned off every option of optifine, and it's not caused by some of them but simply by optifine itself.

Pictures with debug screen and also bug introduced:
![2021-06-16_11 51 21](https://user-images.githubusercontent.com/85993262/122199000-f2937400-ce99-11eb-81cb-37e57729385b.png)
![2021-06-16_11 51 24](https://user-images.githubusercontent.com/85993262/122199003-f32c0a80-ce99-11eb-967c-1f94377ef822.png)

**Comment by Regnander** [comment]
Related #1452
