### ISSUE TITLE
Insane fps drop

### ISSUE THREAD

**Issue by Tobotron1** [sp614x/optifine#5814]
Whenever i use optifine my fps drops to 0 and crahses, this is true for clients with optifine too. the ones i have used that dont work are: badlion, labymod and lunar. it also doesnt work with optiforge (with optiforge it just doesnt load hsaders and makes it so only shows 1/4 of the screen the resit is white) thnx

**Comment by KaiAF** [comment]
Don't use optiforge and see if that helps. All you need to do is just drop the OptiFine installer in the mods folder. The clients problem could be a client issue directly. 
If it crashes again, please send a crash log

**Comment by Tobotron1** [comment]
It hasn't crashed since and it's not a client problem as when I remove
optifine it works + my optimise 1.16 installation is bugged too

**Comment by Jiingy** [comment]
> It hasn't crashed since
Closing as the Issue seems to no longer be a problem, as well as no crash log being provided

**Comment by Tobotron1** [comment]
this was 2 years ago dude

**Comment by Jiingy** [comment]
Yes. Which is exactly why it is being closed.
