### ISSUE TITLE
Error : Cant donate 3D Secure verification failed.

### ISSUE THREAD

**Issue by PyroTheLemon** [sp614x/optifine#5815]
Cant purchase cape

I tried to donate with my card (visa) on https://optifine.net/donate when i enter all details and press pay $10 it says 3D Secure verification failed. i called my credit card company they said "there is no problem with your credit card, may be sourced from the site contact with site"

Im trying to pay with
credit cards visa and Terminal3 thing.

**Comment by KaiAF** [comment]
I am not entirely sure why paymentwall does this, but it's a security thing I'm sure. Contact paymentwall's support team as this is an issue on their end. 

Email support@paymentwall.com.
