### ISSUE TITLE
21w14a Optifine for those who wish to use the world Gen

### ISSUE THREAD

**Issue by HughSparks** [sp614x/optifine#5816]
I understand that you do not do snapshots, however I really need fps. I created a world on the 1.17 snapshots and got decent way into the world. Along come 21w14a which was the last snapshot to guarantee support with the snapshot world generation in the full release of 1.17. So this puts me in a position where I have no real optimization and I am stuck till Christmas without being able to use 1.17 optifine. I honestly don't need the shaders just the fps settings and optimization.

**Comment by FlapJacky** [comment]
I have a world before the split and would like this too!

**Comment by Jiingy** [comment]
Priorities are to finish 1.17 OptiFine, going back to older snapshot versions is not planned.
