### ISSUE TITLE
[Visual] Honey blocks, slime blocks, ice and colored glass not rendering

### ISSUE THREAD

**Issue by rosemunn** [sp614x/optifine#5817]
## Description of Issue
Just like the title says, honey blocks, slime blocks, ice and colored glass blocks are all not showing up, they're completely invisible. 

## Steps to Reproduce
1. Has happened ever since installing Optifine preview version, I did not change any video settings.

## OptiFine Version
1.17 G9 pre21

## Installation Method
Included installer

## Other Installed Mods
Since shaders are not yet supported, I have no other mods running.

## F3 Debug Screenshot
The chunk of missing water shown here is where invisible ice is.
![2021-06-16_18 33 22](https://user-images.githubusercontent.com/86031497/122317189-f511c000-ced1-11eb-8025-21866fc2395e.png)

<!-- If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
No

**Comment by KaiAF** [comment]
you are currently using pre16. Which is why the bug is still showing up. Update optifine
