### ISSUE TITLE
1.17 Not loading shaders

### ISSUE THREAD

**Issue by echoKrinkLe** [sp614x/optifine#5818]
Optifine 1.17 is not showing any shaders and the entire button "Shaders" is grayed out. My current shaders are:
- Chocapic V9.1 Extreme
- Seus Renewed v1.0.1
-All of Sildurs vibrant shaders
Thanks.

**Comment by Stereo528** [comment]
yea thats cause shaders are broken and disabled in 1.17 because of the opengl upgrade
