### ISSUE TITLE
Entities disappear when taking screenshot

### ISSUE THREAD

**Issue by AtomRation** [sp614x/optifine#5819]
## Description of Issue
When taking a screen shot, entities disappear and the game has to be quit and reloaded for entities to reappear. Example, after taking a screenshot, the hand or item in hand disappears. Broken blocks disappear, boats disappear. Newly created 1.17 Hardcore World

## Steps to Reproduce
1. Press F2 to take a screenshot

## OptiFine Version
1.17-OptiFine_HD_U_G9_pre21

## Installation Method
Used the included standalone installer.

**Comment by KaiAF** [comment]
This is caused by taking a screenshot in any other quality higher than 1x. Already addressed here: #5734
