### ISSUE TITLE
Can't log in into my Optifine Account!

### ISSUE THREAD

**Issue by Disqualifizierte** [sp614x/optifine#582]
Well, so..
Since today I can't log in into my Optifine Account. Sometimes it works and sometimes I have to wait (like 10, 20 or 40 minutes), because I entered an "invalid username or password".. 
I got hacked like 3 times because of that, so I had to change my password. I'm really sure that I entered the valid username and the correct password.. I'm afraid to try it again, 'cause I don't want me to got hacked again. :(
Does somebody know what is the problem? Please help me. ;-;
P.S.: I'm sorry for my bad grammar, I'm from germany.

Waiting for your help! - Disqualifizierte

**Comment by sp614x** [comment]
The username/password are sent to the Mojang login server, which decides if the login is valid or not.
After severail failed attempts the Mojang login server may lock the account temporary (24h) or permanently (requires password change).  The temporary block (10/20/40 min) is to avoid the block by the login server.

The only possible solution is to try again later or to change the password. Trying many times with wrong password may lead to the account being locked temporarily or permanently.
