### ISSUE TITLE
[1.17] All Players and Entities turn invisible when taking screenshots on size x2/x4

### ISSUE THREAD

**Issue by Pidroxx** [sp614x/optifine#5820]
## Description of Issue
Basically, when you try and take a screenshot with the Screenshot size option enabled to any value, every player (including yourself) and entities turn invisible.
Leaving the world/server doesn't fix it, nor does turning off the Screenshot size option or reloading the resource pack
Only solution is to restart the game

## Steps to Reproduce
1. Load into a world or server, and turn on Screenshot Size option to x2 or x4
2. Press F2 to take screenshot

## OptiFine Version
OptiFine HD U G9 pre21

## Installation Method
Normal executable Jar installation

No other mods installed

## Log Files/Crash Reports
https://pastebin.com/GL1LiKQr

## Screenshots:
In the first screenshot, everything looks normal, second screenshot shows the bug's effects. Third one shows OpenGL errors that manifested shortly afterwards 
![2021-06-17_02 54 03](https://user-images.githubusercontent.com/68068829/122339368-63c53c80-cf17-11eb-96ce-39916f8ea859.png)
![2021-06-17_02 54 07](https://user-images.githubusercontent.com/68068829/122339372-64f66980-cf17-11eb-89e5-fe86137de0a8.png)
![2021-06-17_02 58 17](https://user-images.githubusercontent.com/68068829/122339856-efd76400-cf17-11eb-8b7c-2669390cc10f.png)

**Comment by Pidroxx** [comment]
![2021-06-17_02 58 17](https://user-images.githubusercontent.com/68068829/122339991-1b5a4e80-cf18-11eb-840f-a0e74ca5ddde.png)
This showed up on chat shortly afterwards minimizing the game

**Comment by KaiAF** [comment]
Already addressed here: #5734
