### ISSUE TITLE
Buggy Emmisives

### ISSUE THREAD

**Issue by Rhythm7845** [sp614x/optifine#5822]
## Description of Issue
When using Faithful 32x from https://faithful.team and using the Emissives addon the blocks which the emisives effect show a tinted 1*1 texture when the block is more than 2 blocks away from the camera. X shaped blocks like Crimson Mushroom disappear when they are 2 blocks further than the camera.

## Steps to Reproduce
1. Install Faithful 32x from https://faithful.team
2. Install Faithful emissive addon from https://faithful.team
3. Go to a crimson forest in the Nether
4. Install and activate both of these resource packs
5. Observe 

## OptiFine Version
1.17 OptiFine HD U G9 pre21

## Installation Method
Standalone

## F3 Debug Screenshot
![image](https://user-images.githubusercontent.com/66195447/122402956-94e75080-cf9b-11eb-9880-dd3d9df821a7.png)

## Prior Testing
<!-- If you've installed standalone:
No

## Additional Information
Optifine is really good

**Comment by KaiAF** [comment]
Try turning off smooth fps, fast render, Anisotropic filtering and Antialiasing

**Comment by KaiAF** [comment]
Closing this in favor of #5847. It has more information regarding the issue.
