### ISSUE TITLE
[Crash] Game crash when turning on/switching shaders pack (maybe AMD driver conflicts?)

### ISSUE THREAD

**Issue by Borsa-too** [sp614x/optifine#5824]
## Description of Issue
When I turn on shaders or just try to switch one to compare them, the game crashes. It's happening since 1.15. It's very annoying because i have to restart my game everytime I want to try a new shaders pack that I downloaded, and takes a couple of minutes for a thing that usually should take a couple of seconds. It happens both when I turn them on while playing in a world and in the menu. I tried to update my RX580 driver (currently using 21.5.2) and never solved the problem, uninstalling optifine and didn't solve the problem too.

## Steps to Reproduce
1. Turn on/switch shaders pack
2. game crashes

## OptiFine Version
optifine 1.16.5 HD U G8

## Installation Method
Installed using the standalone pack, not forge or fabric

## Log Files/Crash Reports
[crash.log](https://github.com/sp614x/optifine/files/6675801/crash.log)

## F3 Debug Screenshot
![2021-06-18_10 42 16](https://user-images.githubusercontent.com/63447221/122533529-f7832f80-d021-11eb-97ea-71f7c2a221f1.png)

## Additional Information
That's just it

**Comment by KaiAF** [comment]
Yeah, unfortunately this really seems like it's an AMD Driver issue. AMD Drivers seem to be really bad for OptiFine shaders. This isn't an OptiFine issue, and cannot be fixed by optifine.
