### ISSUE TITLE
Screenshots transperant when using optifine

### ISSUE THREAD

**Issue by JFoxStargazer** [sp614x/optifine#5826]
So when I take a screenshot, the image I get is completely transparent, I don't know what could be causing this but maybe I have enabled a setting or something.

1. Open MC with optifine
2. Take a screenshot and find resault in the screenshots folder

OptiFine HD U G9 pre21

I used the included standalone installer

Here's my sister base when I took a screenshot with Optifine installed
https://i.imgur.com/2UvMRGQ.png

I took this using the Snipping Tool and this is how the screenshot was supposed to look (don't judge my sister)
https://i.imgur.com/as6Eo2d.png

This doesn't happen in Vanilla Minecraft

**Comment by fayer3** [comment]
looks like it's an issue with antialiasing

**Comment by JFoxStargazer** [comment]
And can I do something or do you need to fix it?

Den fre. 18. jun. 2021 kl. 20.34 skrev fayer3 ***@***.***>:

**Comment by fayer3** [comment]
It's an issue sp614x needs to fix.
In the meantime if you want to take screenshots disable Antialiasing.

**Comment by KaiAF** [comment]
Already addressed here: #5770
