### ISSUE TITLE
Optifine seems to be hanging after Win 10 Creators Update

### ISSUE THREAD

**Issue by ArcaniX5696** [sp614x/optifine#583]
The game doesn't actually crash so I don't have a crash log, but my game with the dw20 1.10 modpack worked perfectly fine* with optifine before I updated to Windows 10 Creators Update (averaging 45-50 fps), and afterwards I'm experiencing an EXTREMELY low framerate - a flat out zero FPS if Java is on normal priority, and if on real-time I might get a single frame redraw every 5-7 seconds, but never drawing the world, just my hotbar and journey map and the flat sky color (no details/textures, etc).  After leaving it for a minute or two, hoping it would kick to life, I realized the world is ticking normally as the flat sky color started turning to night at a fairly normal transition speed.

Since I don't have an actual crash, I've tried a few different things to try and help.  The above issue occurs as long as I have optifine (HD_U_D7) installed, and happens in both my existing world and a brand new world. (In the brand new world, the items in my hotbar never even completed their 'pickup' animations...). As soon as Optifine is removed, the game runs normally, albeit at 20-30fps.  Enabling / disabling the new Game Mode in Windows had no effect on the situation with optifine installed.

I'll keep an eye on this post and will be happy to provide any further information I can on the problem.

* (there is technically a repeatable crash condition between optifine and super circuit maker for me when I have tiny glowing redstone in my hand and I look at a circuit, but I'm not convinced it's optifine's issue)

**Comment by TheHADILP** [comment]
Is Smooth FPS disabled in Optifine Settings? If not try it out.

**Comment by ArcaniX5696** [comment]
I am so sorry and feel rather silly at this point, but thank you for your suggestion as it lead me to the real problem...

Disabling the Smooth FPS option did get things moving again but only at 14-15 FPS, but I noticed something wrong with the graphics card being used while on the debug screen this time... I game on a Nvidia 660M laptop, which enables the nvidia only when needed.  I had an override for Java before the Windows update, as it always "detects" java as not needing the nvidia and gives it the Intel 4000 instead.

So, back on the Nvidia, with Optifine in (smooth FPS enabled), java priority jacked up, and back to 35+ fps...
