### ISSUE TITLE
Cant buy Optifine cape, please help

### ISSUE THREAD

**Issue by MrOoran** [sp614x/optifine#5831]
The verification process we have in place is to combat fraudulent activity and to make sure there are no problems. We apologize for all the inconvenience this may have caused. This is what shows up when i try to donate to get a cape. ive tried disabling my adblocker and other extensions but still doesnt work. Please help, i really want a cape :(

**Comment by KaiAF** [comment]
You have to verify through paymentwall. It should tell you how. Regardless, this is not an OptiFine issue, this is related to Paymentwall.

Email: support@paymentwall.com for support regarding this issue.
