### ISSUE TITLE
[Crash] Debian-based Linux system doesn't let OptiFine launch

### ISSUE THREAD

**Issue by PaulPare** [sp614x/optifine#5832]
## Description of Issue
Operating System: Pop!_OS 20.10 [Non-LTS] (Ubuntu based and Debian based)
Crash Error (Minecraft Launcher): 

    GLFW error 65543: GLX: Failed to create context: GLXBadFBConfig.
    Please make sure you have up-to-date drivers (see aka.ms/mcdriver for instructions).

## Steps to Reproduce
Launch Minecraft while OptiFine is in the mods folder(even if there's Optifabric only) or installed as a client.

## OptiFine Version
preview_OptiFine_1.17_HD_U_G9_pre21

## Installation Method
Install it as a client/standalone setup. Also gives the same error when dropped into mods folder.

## Fabric/Forge Version
Fabric Loader 0.11.6-1.17

## OptiFabric Version
optifabric-1.11.1

## Other Installed Mods
optifabric-1.11.1

## Prior Testing
<!-- If you've installed standalone:
- Does this happen in Vanilla without OptiFine? Nope.

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   - Only OptiFine, OptiFabric, and Fabric
- Does this happen in OptiFine standalone?
   - Yeah
- Does this happen in Vanilla without OptiFine?
   - Nope
- Have you tried using a binary search to find which mods cause this issue?
   - Doesn't Conflict with any mods.

**Comment by Regnander** [comment]
Maybe related to #5739

**Comment by KaiAF** [comment]
Seems to be addressed here: #5739.
