### ISSUE TITLE
[BUG REPORT] Short description

### ISSUE THREAD

**Issue by EndermanHackerVN** [sp614x/optifine#5833]
## Description of Issue
Optifine just show error when I click on Install.

## Steps to Reproduce
Downloaded Optifine installer from optifine.net

## OptiFine Version
Optifine 1.17 pre21 version

## Installation Method
Open the installer .jar downloaded from Optifine.net

## Log Files/Crash Reports
https://pastebin.com/v78ABnuw

**Comment by KaiAF** [comment]
I am not able to reproduce this. Does this happen on any other versions? Are you changing the Install location?

**Comment by KaiAF** [comment]
No reply from the author of the issue
