### ISSUE TITLE
character turns completely invisible

### ISSUE THREAD

**Issue by logoslabz** [sp614x/optifine#5835]
## Description of Issue
Character turns completely invisible. Re logging doesn't fix it. Restarting the launcher does.

## Steps to Reproduce
1. What do you do...   
2. ...to find this bug?  Press F2 + F3 really quickly

## OptiFine Version
<release 1.17-Optifine_HD_U_G9_pre21>

## Installation Method
     standalone version

## F3 Debug Screenshot
 attaching a video

## Prior Testing
<!-- If you've installed standalone:
- Does this happen in Vanilla without OptiFine? - doesn't happen without optifine based on my testing 

## Additional Information
Pressed F2 + F3 and then switched cameras using F5 to show missing camera

https://user-images.githubusercontent.com/86167505/122653367-f4676c80-d111-11eb-845d-28faeee573d6.mp4

>

**Comment by PhysonicYT** [comment]
Same, but all I had to do was press f2 quickly.

**Comment by fayer3** [comment]
have you changed the screenshot size to other than default?

**Comment by logoslabz** [comment]
Yes to 3x, for editing reasons

**Comment by fayer3** [comment]
then its probably the same bug as #5820

**Comment by KaiAF** [comment]
Already addressed here: #5734
