### ISSUE TITLE
[bug report] optfine doesn’t allow the spy glass zoom

### ISSUE THREAD

**Issue by CutePyro0** [sp614x/optifine#5836]
## Description of Issue
if you have optfine 1.17 installed on your client and attempt to zoom using the spy glass you will find that while you get the spyglass fov you don’t actually zoom

## Steps to Reproduce
1. install optifine 1.17 load up a world make/give yourself a spyglass and attempt to use
2. the bug is visible when your try it

## OptiFine Version
OptiFine HD U G9 pre21 and before

## Installation Method

i did both methods 

## Fabric/Forge Version

fabric Version: 0.7.4

## OptiFabric Version

optifabric-1.11.1.jar

## Prior Testing

i tried using a fabric mod using lithium and the spyglass worked as intended

**Comment by KaiAF** [comment]
turn on dynamic fov

**Comment by CutePyro0** [comment]
ah thanks im such a dummy 😂
