### ISSUE TITLE
[Crash] Crash when starting

### ISSUE THREAD

**Issue by EloKrone** [sp614x/optifine#5839]
## Description of Issue
When I launch the preview of Optifine for 1.17, I get this error : 
![image](https://user-images.githubusercontent.com/46350785/122684953-e6484780-d208-11eb-86c1-c28d56c9472c.png)

## Steps to Reproduce
1. Open Minecraft launcher
2. Launch with preview Optifine for 1.17

## OptiFine Version
OptiFine HD U G9 pre21

## Installation Method
I used the standalone installer

## Log Files/Crash Reports
No Log Files/Crash Report is generated when I get the error

## Prior Testing
It works fine in Vanilla

**Comment by DaCoolKitty** [comment]
The terror:image that you uploaded makes me think that you should try reinstalling Java

**Comment by sp614x** [comment]
Reinstalling Java should fix it.
