### ISSUE TITLE
With MCPatcher Cannot Change Lava Color PNG File

### ISSUE THREAD

**Issue by jredfox** [sp614x/optifine#584]
Path: minecraft\mcpatcher\colormap\underlava.png
Resalution: 256x256

Made Texture Black blue and lighter colors for lava but, the overlay remains the same. MCPatcher might have quit but, that doesn't mean you shouldn't stop updating it for him. For example you have dynamic lights and shaders fix this one as well.

**Comment by sp614x** [comment]
Updated preview C5 for 1.12
 - added custom underlava fog colors

**Comment by jredfox** [comment]
nice
