### ISSUE TITLE
[Installation] Optifine (any version)

### ISSUE THREAD

**Issue by Zach256** [sp614x/optifine#5840]
## Description of Issue
 I am on an M1 Mac 2020 and I am trying to download Optifine, I download the file and go through the process of opening it but then when I try to open the file after the process of allowing it to be opened by the computer it just shows an opening animation but not the installation window at all.

## Steps to Reproduce
1. Download Optifine off an official website, open file, It says “OptiFine_1.16.5_HD_U_G8 (4).jar” cannot be opened because it is from an unidentified developer. press OK, Go to "Security and Privacy, press open anyway, press OK again and then the file makes an opening animation but does not open to the installation window.

2. ...to find this bug?

**Comment by DaCoolKitty** [comment]
Go to system preferences, security and privacy, then go to the main/first tab. Select "open anyway".

**Comment by Jiingy** [comment]
Solution was provided to this problem, closing
