### ISSUE TITLE
[1.17] [Graphic] [Blocks] End Gateway

### ISSUE THREAD

**Issue by IranMine123** [sp614x/optifine#5841]
Hello... just playing and this happend... it get a bad quality

/setblock ~ ~-2 ~ end_getway
and rotate around this block

1.17 HD U G9 Pre17

just installing optifine client

https://user-images.githubusercontent.com/74745380/122690276-cda65480-d23d-11eb-8d34-6366f1adbfcf.mp4

**Comment by Ari-RERA-43** [comment]
This is an issue with vanilla 1.17. It's getting fixed in 1.17.1

**Comment by DaRealMinecraftexpert** [comment]
Found this with Regular End Portal Blocks too

**Comment by IranMine123** [comment]
oh ok THX

**Comment by lllDeathlll** [comment]
> This is an issue with vanilla 1.17. It's getting fixed in 1.17.1.
> 
> Also, it won't fix this but you should update to to OptiFine pre21. It contains some fixes for other bugs.

I didnt find it nor on vanilla 1.17 nor on vanilla 1.17.1, only on optifine versions
