### ISSUE TITLE
[Category] Short description

### ISSUE THREAD

**Issue by KoPlayz** [sp614x/optifine#5844]
## Description of Issue

Chunks not loading
## Steps to Reproduce
1. What do you do...
2. ...to find this bug?
You go into chunks that are currently not loaded and they do not load at all/it takes 10m to load a chunk
## OptiFine Version

1.17 G9 Pre21
## Installation Method

standalone installer

## F3 Debug Screenshot

https://imgur.com/a/evjkYqH

**Comment by KaiAF** [comment]
In the screenshot you provided, it does not show that you are using OptiFine. Either this problem is happening in Vanilla, or you sent the wrong image.
