### ISSUE TITLE
[BUG] Install Optifine On Ubuntu 20.04

### ISSUE THREAD

**Issue by arnonGPMC** [sp614x/optifine#5848]
## Description of Issue
When I'm Installing THe .jar Of Optifine I'm getting an error

## Steps to Reproduce
1. Download Optifine From Website
2. Run it With Java

## OptiFine Version
all Of Them

## Installation Method
Installer

## Log Files/Crash Reports
This is The error:
https://pastebin.com/y5Zf5hcG

## Prior Testing
Regular Vanilla Works

## More Info
I Can Download Just With BadLion Client

**Comment by Regnander** [comment]
"Optifine_ver.jar" sounds like a strange filename. From where did you download this file?

**Comment by arnonGPMC** [comment]
> "Optifine_ver.jar" sounds like a strange filename. From what website did you download this file?

the _ver
its make a explain to the all versions,
i've downloaded it from
optifine.net/download

**Comment by fayer3** [comment]
try opening it manually from the terminal with:
`java -jar Optifine_ver.jar`

**Comment by arnonGPMC** [comment]
> try opening it manually from the terminal with:
> `java -jar Optifine_ver.jar`

Thanks!
