### ISSUE TITLE
optifine crashes my minecraft server when i launch it

### ISSUE THREAD

**Issue by unbentfatpuppy** [sp614x/optifine#5850]
## Description of Issue
when I install optifine my Minecraft server crashes it cant load even but without optifine it is fine even with optifine by itself it crashes.

## Steps to Reproduce
1. put optifine in mods folder for forge server
2. load server crashes

## OptiFine Version
OptiFine_1.16.5_HD_U_G8

## Installation Method
the file was extracted and put in the mods folder

## Fabric/Forge Version
forge

## Other Installed Mods
[https://imgur.com/a/R8LuX3S](url)

## Log Files/Crash Reports
https://pastebin.com/KfzvAx60

## Prior Testing

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   - Only OptiFine and Forge: yes
- Does this happen without any mods at all?
   - Only Forge/Fabric by itself: no
- Does this happen in OptiFine standalone?
- no
- Does this happen in Vanilla without OptiFine?
- no
- Have you tried using a binary search to find which mods cause this issue?
   - To find conflicting mods, split your mods into 2 groups (not including OptiFine/OptiFabric, obviously). Remove one group, and test in-game. Keep the group that has the problem, and repeat until no more mods can be removed without the issue disappearing. yes
   - Does the issue still happen with only the remaining mods installed?
      - Forge/Fabric and remaining mods, without OptiFine -->no

**Comment by KaiAF** [comment]
OptiFine is a client side mod only. It does not work for servers.
