### ISSUE TITLE
[Category] Short description

### ISSUE THREAD

**Issue by tnkv** [sp614x/optifine#5851]
## Steps to Reproduce
1. I make screenshot in 4x mode

## OptiFine Version
1.17 pre21

## Installation Method
i use only optifine, without forge/fabric

entity bug

![image](https://user-images.githubusercontent.com/67426242/123093084-e4160100-d433-11eb-8e94-74f65fa3f80e.png)

**Comment by Ari-RERA-43** [comment]
This was already reported in #5734

**Comment by Jiingy** [comment]
Closing in favor of #5734
