### ISSUE TITLE
[Crash] AMD crash on recent drivers with provided workaround

### ISSUE THREAD

**Issue by BalintCsala** [sp614x/optifine#5852]
## Description of Issue
AMD drivers have a bug, where both normal glShaderSource and glShaderSourceARB have problems when passing in the length of the string explicitly instead of using a null-terminator. Although this issue is a bug on AMDs side, it's been around for more than 1.5 years and so a workaround would be ideal.

This also came up with vanilla with the introduction of the core shaders and was "resolved" in 1.17 pre-1. [Bug report](https://bugs.mojang.com/browse/MC-223021)

Proof of solution is in [this PDF](https://github.com/sp614x/optifine/files/6851684/Getting.optifine.shaders.working.on.AMD.cards.without.special.launchers.or.downgrading.pdf)

## Steps to Reproduce
1. Install optifine on a system with an AMD graphics card using the latest drivers
2. Install a shaderpack and try to enable it

## OptiFine Version
OptiFine_1.16.5_HD_U_G7

## Installation Method
Through the usual installer

## Prior Testing
This crash can occur in both net.optifine.shaders.Shaders.createVertShader and net.optifine.shaders.Shaders.createFragShader

## Additional Information
I edited the bytecode of lwjgl-opengl-3.2.2.jar to confirm this fix. By replacing the calls to glShaderSourceARB, the crash can be fixed

Fix for this is "simple". Instead of glShaderSourceARB, use:

```java
MemoryStack stack = stackGet();
int stackPointer = stack.getPointer();
try {
    ByteBuffer sourceBuffer = MemoryUtil.memUTF8(string, true);
    PointerBuffer pointers = stack.mallocPointer(1);
    pointers.put(sourceBuffer);
    long stringAddress = org.lwjgl.system.APIUtil.apiArrayi(stack, MemoryUtil::memUTF8, string);
    nglShaderSourceARB(shaderObj, 1, pointers.address0(), 0);
    org.lwjgl.system.APIUtil.apiArrayFree(stringAddress, 1);
} finally {
    stack.setPointer(stackPointer);
}
```

Alternatively there's a slightly different solution in  com.mojang.blazed3d.platform.GlStateManager in glShaderSource, should be easy to adapt

**Comment by BalintCsala** [comment]
[Getting_Optifine_shaders_working_on_some_AMD_cards (1).pdf](https://github.com/sp614x/optifine/files/6702265/Getting_Optifine_shaders_working_on_some_AMD_cards.1.pdf)

**Comment by BalintCsala** [comment]
Sorry, accidental close

**Comment by 0i5** [comment]
Hi, I'm really new to these sorts of things so I'm pretty confused. 
Where is glShaderSourceARB located and where do I put the string of code?

**Comment by BalintCsala** [comment]
This is not a fix you can do outside of optifine, so unless you are modifying the code. this is not a solution you can use. If you want to fix the crashing temporarily, follow these instructions:
[PDF](https://github.com/sp614x/optifine/files/6844438/Getting.optifine.shaders.working.on.AMD.cards.without.special.launchers.or.downgrading.pdf)

**Comment by 0i5** [comment]
Thanks, it worked perfectly for me. Appreciate it

**Comment by BalintCsala** [comment]
This was fixed in the latest preview release
