### ISSUE TITLE
[Crash] Crashing when opening a chest or using a crafting table

### ISSUE THREAD

**Issue by warmworms** [sp614x/optifine#5854]
## Steps to Reproduce
1. Join a world
2. Open a chest/use crafting table

## OptiFine Version
1.16.5

## Installation Method
Standalone installer.

## Other Installed Mods
I only have optifine and sildurs shaders installed.

## Log Files/Crash Reports
Crash Log 1: https://pastebin.com/NsuFyFXN
Crash Log 2: https://pastebin.com/BgJ7XnEh

## F3 Debug Screenshot
![image](https://user-images.githubusercontent.com/86377517/123154575-ad88b800-d42c-11eb-8f82-7c5a410972c9.png)

## Prior Testing
<!-- If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
- No

**Comment by warmworms** [comment]
oops... for the prior testing the answer is supposed to be no (:

**Comment by warmworms** [comment]
A brand new one, happened RIGHT after I crafted a cobblestone slab.

https://pastebin.com/RPyT3pRz

**Comment by DaCoolKitty** [comment]
Does this happen when you open any menu, for example a furnace? And does this happen when shaders/texture pack are not activated?

**Comment by warmworms** [comment]
I can't believe I didn't try taking off my resource pack first. And that's exactly what the issue is. For some reason, when I'm running the game on optifine with my Mizuno's resource pack, anytime I try to close the recipe book and craft something, the game crashes. I'm so sorry for wasting your time!
