### ISSUE TITLE
Render regions causing transparent blocks to be invisible.

### ISSUE THREAD

**Issue by Conn2243** [sp614x/optifine#5855]
![image](https://user-images.githubusercontent.com/51893947/123199197-a59c3880-d46b-11eb-8a04-ae2c7190c8cd.png)
![image](https://user-images.githubusercontent.com/51893947/123199214-aa60ec80-d46b-11eb-8eb6-5786e389bb2d.png)

**Comment by Ari-RERA-43** [comment]
I'm unable to reproduce this. My video settings are set to default besides Render Regions being enabled
![Screenshot (128)](https://user-images.githubusercontent.com/80327369/123201063-f7e75480-d47f-11eb-93e8-5ee1071d6d1f.png)

**Comment by KaiAF** [comment]
can you send a F3 debug menu screenshot?

**Comment by Ari-RERA-43** [comment]
> can you send a F3 debug menu screenshot?

Me, Conn2243, or both?

**Comment by KaiAF** [comment]
Conn2243

**Comment by Conn2243** [comment]
> Conn2243

![image](https://user-images.githubusercontent.com/51893947/123210763-b6ef4000-d47f-11eb-91d0-58d1d0c675d3.png)

**Comment by Ari-RERA-43** [comment]
Update to pre21: https://optifine.net/adloadx?f=preview_OptiFine_1.17_HD_U_G9_pre21.jar

**Comment by Conn2243** [comment]
> Update to pre21: https://optifine.net/adloadx?f=preview_OptiFine_1.17_HD_U_G9_pre21.jar
That seemed to fix it. Thank you.
![image](https://user-images.githubusercontent.com/51893947/123211369-9ffd1d80-d480-11eb-8076-8d195e7c24f8.png)
