### ISSUE TITLE
[1.17] World not loading

### ISSUE THREAD

**Issue by BeamerBacon** [sp614x/optifine#5858]
## Description of Issue
When going through nether portals my world stops loading, cannot kill mobs or render new chunks, tried playing without it

## Steps to Reproduce
1. What do you do...
2. ...to find this bug?

## OptiFine Version
release 1.17-Optifine_HD_U_G9_pre16

## Installation Method
I used the standalone installer

## Prior Testing
<!-- If you've installed standalone:
- Does this happen in Vanilla without OptiFine? No it doesn't

## Additional Information
Streamable clip showing the issue:
https://streamable.com/9tzj86

**Comment by fayer3** [comment]
use pre21 this should be fixed

**Comment by KaiAF** [comment]
This was fixed in pre21.
