### ISSUE TITLE
[Bug] Particles are no longer aligned

### ISSUE THREAD

**Issue by EireNero** [sp614x/optifine#5859]
## Description of Issue

Smoke does not align with campfires when you move around aka it the smoke just appears in to be coming from another place.
Actually, it's the same with all particles ingame

## Steps to Reproduce
1.  Place Campfire, move around, look at the smoke. Or anything else that produces particles (breaking blocks, torches etc etc)

## OptiFine Version

1.17 G9 PRE22 

## Installation Method

 Used the installer

## Additional Information

See Example (Is worse than this, but this is the easiest way to understand
![2021-06-26_00 58 03](https://user-images.githubusercontent.com/62108781/123495232-cf479200-d61a-11eb-91f3-cea7fb6f5f2a.png)

![2021-06-26_01 09 03](https://user-images.githubusercontent.com/62108781/123495314-28172a80-d61b-11eb-9d6d-a838ded90481.png)

**Comment by KaiAF** [comment]
This was fixed in pre23
