### ISSUE TITLE
[Bug] Pre22 Flames from torches, campfire smoke and glowsquid sparkles can be seen through walls with some shaders on

### ISSUE THREAD

**Issue by Husselbeh** [sp614x/optifine#5861]
## Description of Issue
Loaded up the shaders with the new update both BSL and Complementary. The flames are detached from the torches and you are able to see those flames, the smoke from the campfires and sparkles from glowsquids through blocks. Also shows Enderman "aura" 

## Steps to Reproduce
Literally just loaded MC up with Optifine and Shaders enabled. 

## OptiFine Version
OptiFine 1.17_HD_U_G9_pre22

## Installation Method
Used the standalone installer.

## Log Files/Crash Reports
[latest.log](https://github.com/sp614x/optifine/files/6719305/latest.log)

## F3 Debug Screenshot

![2021-06-26_01 07 50](https://user-images.githubusercontent.com/85703239/123495291-1897e180-d61b-11eb-983d-8512395e5c11.png)
You can see the torch flames, campfire smoke and glowsquid sparkles all in the screenshot also. 

![2021-06-26_01 12 51](https://user-images.githubusercontent.com/85703239/123495469-bab7c980-d61b-11eb-8141-a887e3fc703e.png)
You are able to see the enderman particles or "Aura" here also.

## Prior Testing

This doesn't happen with Vanilla

## Additional Information

If you need anymore info just shout.

**Comment by LwkyLion** [comment]
Happens with every shaderpack I tried so far, just give them time, after all, it is a preview version. And The new optifine update is nearly complete.

**Comment by LwkyLion** [comment]
I found out what you can do, you can set all your particles to *Decreased* if you really want to use shaders that badly.

Go to Game Menu > click *Options* > click *Video Settings...* > click on *Animations...* > click "All OFF" at the bottom left > Then click *Particles* until you get to *Particles: Decreased*.

**Comment by rabbitbest** [comment]
were you okay with creatures' shades? They are NOT where they should be :(

**Comment by Husselbeh** [comment]
> Happens with every shaderpack I tried so far, just give them time, after all, it is a preview version. And The new optifine update is nearly complete.

I'm aware, that's why I reported the bug. To inform them.

**Comment by liivya** [comment]
Adding on to this, all shaders do the above, in making particles/smoke visible through walls and also displaced, however mine are also all black/dark, even when I reset all the shaders to basics. 
![2021-06-26_22_optimized 14 26](https://user-images.githubusercontent.com/86520802/123512968-b946d980-d6cd-11eb-85ca-eda8941c3b5e.png)


Also not sure if this is how I should be doing it but I didn't want to open a new one since it's related :)

**Comment by Jiingy** [comment]
[Fixed in 1.17 pre23](https://optifine.net/changelog?f=preview_OptiFine_1.17_HD_U_G9_pre23.jar)
