### ISSUE TITLE
Patticles showing through blocks

### ISSUE THREAD

**Issue by m00nsandwich** [sp614x/optifine#5863]
## Description of Issue
Using Sildur's shaders, particles show through blocks. Can see the bubbles in my bubble elevator throug the grass blocks on the surface, particles from the candles through the wall, etc. Shown in attached f3 screenshot.

## Steps to Reproduce
Just loaded the shaders up.

## OptiFine Version
1.17 G9 pre22

## Installation Method
Standalone installer

## Fabric/Forge Version
Standalone

## Other Installed Mods
No other mods, just some VanilaTweaks datapacks.

## F3 Debug Screenshot
![2021-06-25_22 27 14](https://user-images.githubusercontent.com/86505977/123500565-97cdeb00-d604-11eb-9f6a-f862c16552d1.png)

**Comment by Kitt3yL0v3r66** [comment]
Having the same issue even with Internal Shaders, I've tried messing with some settings and nothing seems to make it go away. Most particles are affected, seems to be an issue with Optifine not the shaders though.
![2021-06-26_00 25 14](https://user-images.githubusercontent.com/86507256/123501768-41b57380-d615-11eb-90fa-3a08242d56c4.png)

**Comment by ButterSpreadBread720** [comment]
![2021-06-25_22 30 14](https://user-images.githubusercontent.com/76714781/123503003-001ccc80-d605-11eb-8805-c7baa2de7f63.png) Same thing. 
Enhanced default shader

**Comment by KaiAF** [comment]
Already addressed here: #5861
