### ISSUE TITLE
Game Crash when loading world

### ISSUE THREAD

**Issue by Jay2876** [sp614x/optifine#5864]
## Description of Issue
I was only using a resource pack and was able to access world before I installed the updated preview. When I downloaded pre22 the game would crash anytime I tried accessing a world. I was not using any form of shaders.

## Steps to Reproduce
1. Installed preview pre22
2. tried accessing world
3. game would crash

## OptiFine Version
OptiFine HD U G9 pre22

## Installation Method
I used the standalone installer

## Log Files/Crash Reports

<img width="1003" alt="Screen Shot 2021-06-25 at 11 32 05 PM" src="https://user-images.githubusercontent.com/86505784/123500698-e59b2100-d60d-11eb-837c-2f144265a625.png">
<img width="892" alt="Screen Shot 2021-06-25 at 11 32 18 PM" src="https://user-images.githubusercontent.com/86505784/123500699-e7fd7b00-d60d-11eb-8122-9246df90bcf6.png">
<img width="888" alt="Screen Shot 2021-06-25 at 11 32 29 PM" src="https://user-images.githubusercontent.com/86505784/123500700-e9c73e80-d60d-11eb-88bb-b3089da4f85d.png">

**Comment by Ari-RERA-43** [comment]
Can you send the log in .minecraft/logs/latest.log

**Comment by skehokin** [comment]
[latest.log](https://github.com/sp614x/optifine/files/6719829/latest.log)
I've gotten a very similar issue when trying to load worlds - I'm on a mac.

**Comment by Jay2876** [comment]
[latest.log](https://github.com/sp614x/optifine/files/6720108/latest.log)

**Comment by DaCoolKitty** [comment]
> [latest.log](https://github.com/sp614x/optifine/files/6720108/latest.log)

Does this happen with vanilla mc?

**Comment by Jay2876** [comment]
yes

**Comment by DaCoolKitty** [comment]
> yes

Try reinstalling minecraft, since it looks like it's an error with the JRE

**Comment by Jay2876** [comment]
But then wouldn't it crash without pre22 if that was the case? Since it only crashed with pre22 and not pre21 or just Minecraft itself. Or am I missing something?

**Comment by DaCoolKitty** [comment]
> But then wouldn't it crash without pre22 if that was the case? Since it only crashed with pre22 and not pre21 or just Minecraft itself. Or am I missing something?

You said that MC crashed when using vanilla as well

**Comment by Jay2876** [comment]
I am so sorry I read it wrong. It doesn't happen with just minecraft. I read it as do you have vanilla. I'm sorry

**Comment by Jay2876** [comment]
> > But then wouldn't it crash without pre22 if that was the case? Since it only crashed with pre22 and not pre21 or just Minecraft itself. Or am I missing something?
> 
> You said that MC crashed when using vanilla as well

No I read it wrong. Sorry about that. It doesn't happen in Vanilla.

**Comment by KaiAF** [comment]
Shaders are currently not compatible with MacOS apparently. Addressed here: #5900

**Comment by Whitelisted1** [comment]
> Shaders are currently not compatible with MacOS apparently. Addressed here: #5900

Under "description of issue" it says they are not using shaders. I think this is a separate problem
_I was not using any form of shaders._


Also just for future reference:
I can use shaders just fine (I use mac), I think shaders are just incompatible with the new M1 macs

**Comment by KaiAF** [comment]
They are using Internal shaders. This is from their log: `[Render thread/INFO]: [Shaders] Loaded shaderpack: (internal)`

**Comment by Whitelisted1** [comment]
ohh, sorry for taking up your time then

**Comment by Jay2876** [comment]
I didn't use shaders than that was automatic. Even when I had no shaders it would crash. It's not the shaders it was optifine. I only opened this so the actual optifine wouldn't be buggy.
