### ISSUE TITLE
OptiFine Shader FPS Drops

### ISSUE THREAD

**Issue by Olvanium** [sp614x/optifine#5865]
I used to get 100+ FPS using shaders. Now I'm getting 40 FPS and it's the same exact shaders. Version is Pre22

**Comment by Xeleche** [comment]
Me too

**Comment by BlueDemonTR** [comment]
please provide more info with Alt + Shift + f3 open in both versions in similar environments

**Comment by KaiAF** [comment]
You would have to provide more information about this bug. Send F3 debug screenshot? What shader are you using? Any resource packs?
Remember. 1.17 shaders are still being worked on

**Comment by KaiAF** [comment]
Closing in favor for: #5878
