### ISSUE TITLE
[Bug] World reset after going through nether portals

### ISSUE THREAD

**Issue by achimnol** [sp614x/optifine#5867]
## Description of Issue

The overworld got reset to its initial state when I went through the nether portal to go to the nether and came back to the overworld using the same portal.

## Steps to Reproduce

Tried to reproduce after loosing my world, but not successful unfortunately. 😞 
(e.g., creating a new world in 1.16/1.17, modify some blocks, load in on 1.17-OptiFine, and create nether portal to go back and forth...)

I have created the world in 1.17 vanilla, built some houses, loaded and played it in 1.17-OptiFine_HD_U_G9-pre21.
And loaded and played it in 1.17-OptiFine_HD_U_G9_pre22, then got the world reset.
However, it does not happen when I first create the world in 1.17 and load directly in the OptiFine pre22, or create the world in the OptiFine pre22.

## OptiFine Version
1.17-OptiFine_HD_U_G9_pre22

## Installation Method
Installed the latest JRE from java.com and double-clicked jar file. Just clicked the install button right away.

## Fabric/Forge Version
None.

## OptiFabric Version
None.

## Prior Testing
It was the first time to go to the nether with the corrupted world.
I've never been gone to the nether before updating OptiFine.

**Comment by itzB2** [comment]
u could get infinite diamonds

**Comment by Ari-RERA-43** [comment]
This is for bug reporting, not finding ways to abuse bugs.

**Comment by KaiAF** [comment]
I am not able to reproduce this. I created a world in 1.17 vanilla. Walked around broke some blocks. Then went on 1.17 OptiFine pre 21 and did the same. Then I went on 1.17 OptiFine pre 22. Created a nether portal and went in, went back to the overworld. Nothing was changed.

**Comment by KaiAF** [comment]
Cant reproduce this, and no one else has reported this issue. Not sure what would have originally caused this.
