### ISSUE TITLE
Broken Particles in OptiFine 1.17_HD_U_G9_pre22 (only with shaders)

### ISSUE THREAD

**Issue by srslyBySirus** [sp614x/optifine#5868]
## Description of Issue
> broken particles in OptiFine 1.17_HD_U_G9_pre22 (only when using sahders)
> particles changes location as you adjust the fov (only when using shaders)

## Steps to Reproduce
![2021-06-26_11 50 29](https://user-images.githubusercontent.com/81144349/123502781-e31fe200-d674-11eb-90a2-ef33eaedcc80.png)
![2021-06-26_11 51 53](https://user-images.githubusercontent.com/81144349/123502798-077bbe80-d675-11eb-898c-8d49c522ef35.png)
![2021-06-26_11 52 06](https://user-images.githubusercontent.com/81144349/123502802-09458200-d675-11eb-9835-ce748c5edaa8.png)

## OptiFine Version
OptiFine 1.17_HD_U_G9_pre22

## Installation Method
i used the optifine installer

## Log Files/Crash Reports
[latest.log](https://github.com/sp614x/optifine/files/6719624/latest.log)

## F3 Debug Screenshot
![2021-06-26_11 55 48](https://user-images.githubusercontent.com/81144349/123502874-7bb66200-d675-11eb-8e8d-42fdb7e62b52.png)

## Prior Testing
happens only when using shaders

**Comment by KaiAF** [comment]
Already addressed here: #5861
