### ISSUE TITLE
[1.17 BUG] Particles and Weathers not Affected by FOV and Spyglass

### ISSUE THREAD

**Issue by kaniol-lck** [sp614x/optifine#5871]
## Description of Issue
it is only rendered correctly when FOV set to 70 (default) and not in flying mode.

## Steps to Reproduce
1. Adjust FOV other than 70
2. Particles animate weirdly bc its not changed corresponding to fov changing 

or

1. Switch to Creative mode
2. Double tap whitespace
3. Particles animate weirdly bc its not changed corresponding to fov changing 

## OptiFine Version
 preview OptiFine 1.17 HD U G9 pre22 

## Installation Method
Standalone

**Comment by KaiAF** [comment]
Can you send a F3 screenshot?

**Comment by kaniol-lck** [comment]
![2021-06-27_00 07 29](https://user-images.githubusercontent.com/29243443/123519106-e26e6680-d6db-11eb-926d-b70516dfac53.png)

**Comment by KaiAF** [comment]
This bug is caused by shaders. Disable internal shaders and that fixes it. Addressed here: #5861
