### ISSUE TITLE
[Bug][1.17][G9_pre22] All light sources not working with shader

### ISSUE THREAD

**Issue by MisterNoNameLP** [sp614x/optifine#5872]
### Issue
With the `Sildurs Vibrant Shaders v1.283-v1.29 Medium` all light sources apart from the sky are not emitting any light.
Neither torches, lava or anything else.

### Instalation method
Ive testet it with the fabric as well as the standalone version with the same result.

### OptiFine version
OptiFine_1.17_HD_U_G9_pre22

### Logs
Logfile: https://pastebin.com/2WKb7D35

![2021-06-26_10 43 09](https://user-images.githubusercontent.com/49952271/123507810-d8ad1a80-d66b-11eb-9eab-ed8969f595cc.png)

**Comment by KaiAF** [comment]
Fixed in latest pre version
