### ISSUE TITLE
Candle flame glitch

### ISSUE THREAD

**Issue by Ibuildstuff832YT** [sp614x/optifine#5873]
## Issue
if you light a candle, the flame goes all over the place

## OptiFine Version
g9 pre22

## Installation Method
via optifine.net

## Prior Testing
this doesn't happen in vanilla.

**Comment by Ibuildstuff832YT** [comment]
no shaders btw. just "vanilla" optifine

**Comment by Ari-RERA-43** [comment]
Can you attach a screenshot?

**Comment by righter** [comment]
I'm using OptiFine HD G9_pre22 Ultra. To reproduce, I go to Video Settings / Shaders and select (internal).

In the screenshot, you can see the flames clipping through the blocks.

![2021-06-26_10 07 42](https://user-images.githubusercontent.com/1621194/123515678-5ff78f80-d666-11eb-898a-530952a9ea7c.png)

**Comment by Ari-RERA-43** [comment]
This isn't the problem reported in this issue. Go to #5861

**Comment by KaiAF** [comment]
Already addressed here: #5861
