### ISSUE TITLE
[1.17][OptiFine HD U G9 pre22] Glow squid incident

### ISSUE THREAD

**Issue by TheBranchPuzzle** [sp614x/optifine#5874]
## Description of Issue
Glow squid particles are rendering on top of the all blocks.

## Steps to Reproduce
Start the world. See underneath. Watch for glowsquid particles

## OptiFine Version
OptiFine HD U G9 pre22

## Installation Method
installed by executing .jar file to standart minecaft path

## F3 Debug Screenshot
![image](https://user-images.githubusercontent.com/77299316/123509931-1ec0a900-d681-11eb-9c33-2401e680d8e4.png)

## Prior Testing
it's only happening with optifine. No mods. In vanilla it's ok.

## Additional Information
Happened only on this version. In pre21 it worked like it should be.

**Comment by Ari-RERA-43** [comment]
This is the same bug as #5861. You should close this issue because it's a duplicate.
