### ISSUE TITLE
[Category] Smoke visible if he closed

### ISSUE THREAD

**Issue by hapeshiva** [sp614x/optifine#5876]
## Description of Issue

the smoke visible if he closed by blocks

## Steps to Reproduce
1. What do you do...
2. ...to find this bug?
go to the mob farm
## OptiFine Version

G9 PRE 22
## Installation Method

standalone

## F3 Debug Screenshot

![image](https://user-images.githubusercontent.com/59057758/123511309-f72a0a80-d699-11eb-89d9-42ec96b15bb6.png)

## Prior Testing

![image](https://user-images.githubusercontent.com/59057758/123511349-30627a80-d69a-11eb-8ac5-93bd1c7301db.png)

**Comment by Ari-RERA-43** [comment]
This is a duplicate of #5861. You should close this issue.

**Comment by KaiAF** [comment]
Already addressed here: #5861
