### ISSUE TITLE
[BUG][1.17] Game crashes when launching on low-end hardware

### ISSUE THREAD

**Issue by dayhub123** [sp614x/optifine#5877]
## Description of Issue
The game crashes when i launch it and it says something like this:
![Screenshot from 2021-06-26 19-20-26](https://user-images.githubusercontent.com/84165227/123512795-a9ba9700-d6b3-11eb-8ebd-c79ad7f7b494.png)

I'm running this on an old machine running Linux Mint with an Intel Celeron 1007U  and using its own integrated GPU(HD Graphics 2500)
I haven't tried running it on Windows yet. It might have been a driver issue.

## Steps to Reproduce
1. Launch the game with the same hardware as above
2. And it crashes

## OptiFine Version

1.17 HD U G9 pre22
## Installation Method

I executed the installer by running `java -jar` command

## Log Files/Crash Reports

https://pastebin.com/FKUFvzzD

## F3 Debug Screenshot
I can't provide any screenshot of the debug menu with optifine but here's one on vanilla:
![2021-06-26_20 28 02](https://user-images.githubusercontent.com/84165227/123514492-80066d80-d6bd-11eb-8c39-7f6fc30b509c.png)
## Prior Testing

It does work in vanilla but it also used to work with optifine prior to 1.17.

**Comment by Ari-RERA-43** [comment]
This was reported in #5739. I think there is a temporary fix in that issue's comments

**Comment by KaiAF** [comment]
Already addressed here: #5739
