### ISSUE TITLE
[Bug][1.17] Pre22 has a huge fps drop with shaders 

### ISSUE THREAD

**Issue by Xeleche** [sp614x/optifine#5878]
Same shaders but 1.16.5 goes 90+ fps 
and 1.17 goes 20 fps, and water make it worse (10 fps)

I don't speak English, hope someone understand this

**Comment by KaiAF** [comment]
You would have to provide more information about this bug. Send F3 debug screenshot? What shader are you using? Any resource packs? 
Remember. 1.17 shaders are still being worked on

**Comment by DaCoolKitty** [comment]
Same as #5865

**Comment by Xeleche** [comment]
> You would have to provide more information about this bug. Send F3 debug screenshot? What shader are you using? Any resource packs?
> Remember. 1.17 shaders are still being worked on

Sorry, I did not realize that I had not put the screenshot

What happens is this:
The new worlds work decently
![2021-06-26_13 54 35](https://user-images.githubusercontent.com/86524351/123523055-e9b75500-d686-11eb-8b4a-fca4d46c4a96.png)

But those created in previous versions (1.16.5) go very bad regardless of the shader, the render distance or the settings.
![2021-06-26_13 56 54](https://user-images.githubusercontent.com/86524351/123523072-0a7faa80-d687-11eb-9a6e-318be5841419.png)
![2021-06-26_13 55 46](https://user-images.githubusercontent.com/86524351/123523074-0c496e00-d687-11eb-97ff-cb4fa2eb84a1.png)
![2021-06-26_13 56 03](https://user-images.githubusercontent.com/86524351/123523078-0fdcf500-d687-11eb-99a5-9e8fff6bdb90.png)

I think that in the final version this will be fixed but for now it is unplayable with shaders with a 1070

**Comment by Xeleche** [comment]
> You would have to provide more information about this bug. Send F3 debug screenshot? What shader are you using? Any resource packs?
> Remember. 1.17 shaders are still being worked on

I think it is a somewhat complex problem because the use of the GPU is like 30% or 40% even 20% when I have massive FPS drops

No mod, no resource pack only shaders my friend

My PC suck?

**Comment by KaiAF** [comment]
Try updating to pre23, there was a few shaders bug fixes.

**Comment by sp614x** [comment]
Please provide screenshot from both 1.16.5 and 1.17 using identical conditions - same world, player position, view direction, shaders, render distance, etc.

**Comment by Xeleche** [comment]
> Please provide screenshot from both 1.16.5 and 1.17 using identical conditions - same world, player position, view direction, shaders, render distance, etc.

Sorry for the delay, eeehh so right, the difference between 1.16 and 1.17 is brutal, I don't understand why, I hope you do.

Sorry again for my bad english

1.16
![2021-06-28_01 36 39](https://user-images.githubusercontent.com/86524351/123592196-86c2dc80-d7b2-11eb-9feb-fd346a4da1a3.png)
![2021-06-28_01 36 59](https://user-images.githubusercontent.com/86524351/123592198-875b7300-d7b2-11eb-8d91-9257d29d197c.png)

1.17

![2021-06-28_01 40 17](https://user-images.githubusercontent.com/86524351/123592215-8d515400-d7b2-11eb-8764-db0eda858810.png)
![2021-06-28_01 40 33](https://user-images.githubusercontent.com/86524351/123592221-8de9ea80-d7b2-11eb-8007-6be48de5ee84.png)

**Comment by Xeleche** [comment]
> Please provide screenshot from both 1.16.5 and 1.17 using identical conditions - same world, player position, view direction, shaders, render distance, etc.
