### ISSUE TITLE
Optifine D7 1.7.10 crashes with Fastcraft installed.

### ISSUE THREAD

**Issue by mfabio00** [sp614x/optifine#588]
I have created a 1.7.10 Modpack in which I play everyday. Today I downloaded and "installed" Optifine D7 but when I click on Play on MultiMC it gives the error that you can find in the log attached. 
Optifine D6 or previous don't give this error.
[2017-04-09-2.log.gz](https://github.com/sp614x/optifine/files/908078/2017-04-09-2.log.gz)

**Comment by skmedix** [comment]
Try the [latest version of FastCraft](http://forum.industrial-craft.net/index.php?page=Thread&postID=207199#post207199) with fix for OF D7

**Comment by mfabio00** [comment]
Thanks skmedix. It solved my problem.

**Comment by WesCook** [comment]
Please mark the issue as closed if it's been resolved.
