### ISSUE TITLE
lags right in the main menu.

### ISSUE THREAD

**Issue by Broung** [sp614x/optifine#5880]
My problem started with the 1.17 pre20 version, and this problem did not exist before. When I go to minecraft, I start lags right in the main menu. And when I tried to enter the world, it was loaded endlessly with the inscription "reading world data" please help with this problem.

**Comment by Whitelisted1** [comment]
Does this happen with vanilla as well?

**Comment by KaiAF** [comment]
No response from the author of the issue, closing
