### ISSUE TITLE
Some dark things with shaders

### ISSUE THREAD

**Issue by Juan8616** [sp614x/optifine#5884]
That's it. Just some black on particles and shadows 
![2021-06-26_14 58 01](https://user-images.githubusercontent.com/76629257/123524414-b62cf880-d68f-11eb-9eb8-de89f9dbc568.png)
![2021-06-26_14 55 50](https://user-images.githubusercontent.com/76629257/123524415-b7f6bc00-d68f-11eb-9f99-bbed00bb36fe.png)
![2021-06-26_14 57 51](https://user-images.githubusercontent.com/76629257/123524416-b927e900-d68f-11eb-96d2-0c0ea9518dbb.png)

**Comment by Juan8616** [comment]
New: I used Tea shaders and the black things aren't, i think it's because Tea shaders doesn't add shadows.
![2021-06-26_15 38 19](https://user-images.githubusercontent.com/76629257/123525585-723df180-d697-11eb-89a8-a4b6a1f3080a.png)

**Comment by KaiAF** [comment]
Fixed in latest pre version
