### ISSUE TITLE
[1.12.2] Shows of.options in video settings

### ISSUE THREAD

**Issue by TheMictick** [sp614x/optifine#5885]
When I use optifine 1.12.2 with a specific mod it shows that there is a of.options randomly all over the video settings and with this here it doesnt allow my shaders to work.

![unknown](https://user-images.githubusercontent.com/86535662/123525206-fba3f280-d69c-11eb-8230-5edbab33b5db.png)

**Comment by Whitelisted1** [comment]
What mods are you using and which one is messing it up?

**Comment by TheMictick** [comment]
Jurassic  world reborn.

**Comment by Whitelisted1** [comment]
I assume this adds new mobs/items, so the mod might automatically apply a resource pack that conflicts with the optifine menu. I'm not sure why this would be the case, but that's what I think is happening

**Comment by TheMictick** [comment]
It’s odd cause this just started happing.

**Comment by TheMictick** [comment]
Nvm I got it fixed.

**Comment by RogeVenham** [comment]
> Nvm I got it fixed.

how did you do that?
