### ISSUE TITLE
1.17 bugs as of 6.26.2021 Black patches

### ISSUE THREAD

**Issue by pajamacrew** [sp614x/optifine#5887]
## Description of Issue
Smoke in 1.17 is fully black. Smoke also shows thru map terrain even if your far away or underwater it shows black smoke particles showing through the blocks.

- anything with smoke shows up as black particles
- glowing signs do not show
- player usersnames show up as all black
- in game maps show as black
- breaking any blocks shows dark particles

## Steps to Reproduce
1. created a frame with a map and shows black
2. just create anything that has an ordinary map in-game and post it on any frame. Create anything that produces smoke and shows black smoke instead of grey. 
3. glow signs show as black
4. player usernames above their names are also black

## OptiFine Version
Lastest version 1.17 pre22

## Installation Method
just installed as normally would like i did all previous versions

## OptiFabric Version
shilders lite shaders with latest optifine 

## Other Installed Mods
no Mods

## F3 Debug Screenshot
https://drive.google.com/file/d/19L_sHSh8drXwfHtPUWCmEBS4o7lGk0B2/view?usp=sharing

## Prior Testing
<!-- If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
No, only when using optifine latest version

**Comment by KaiAF** [comment]
This should be fixed in the latest preview, try updating to that
