### ISSUE TITLE
Disabling Vignette breaks some 3D models

### ISSUE THREAD

**Issue by WesCook** [sp614x/optifine#589]
It only occurs when visible in your hotbar, not when the regular E menu is open.

I noticed this specifically with [Cooking for Blockheads](https://minecraft.curseforge.com/projects/cooking-for-blockheads), and [Advanced Chimneys](https://minecraft.curseforge.com/projects/advanced-chimneys).

Default Vignette

![2017-04-09_18 09 37](https://cloud.githubusercontent.com/assets/792101/24842693/fd8b3cee-1d4f-11e7-8526-58a84940f05a.png)

Fast Vignette

![2017-04-09_18 09 52](https://cloud.githubusercontent.com/assets/792101/24842696/0005afa4-1d50-11e7-9971-eac4f3b1edb4.png)

**Comment by sp614x** [comment]
This should be fixed in OptiFine B8 for 1.11.2.
The bugfix was also backported to:
- OptiFine D8 for 1.10.x
- OptiFine D8 for 1.9.x
- OptiFine H8 for 1.8.x
