### ISSUE TITLE
[Bug] Pre23 entity shadows...all over

### ISSUE THREAD

**Issue by TheOnyxus** [sp614x/optifine#5890]
## Description of Issue
With shaders on, I have entity shadows teleporting everywhere.

## OptiFine Version
1.17 PRE 23

## Installation Method
Standalone

## Log Files/Crash Reports
no crash

## F3 Debug Screenshot
![2021-06-26_21 37 06](https://user-images.githubusercontent.com/86540852/123530309-b8f71000-d6c6-11eb-81f7-ca33f40766e5.png)

## Additional Information
Entities shadows are teleporting around.  Using BSL shaders 8.0.01

**Comment by mjbenninghofen** [comment]
I am seeing a similar issue. Here's a clip: 

https://user-images.githubusercontent.com/32240897/123533429-2876fa80-d6db-11eb-8da5-89a03e1cb645.mp4

This happened to be with Silder's shaders but I confirmed it happens with BSL as well.

**Comment by KaiAF** [comment]
Addressed here: #5883
