### ISSUE TITLE
Pre 23 bug. Block outline in incorrect position.

### ISSUE THREAD

**Issue by MOGOLITO** [sp614x/optifine#5892]
![2021-06-27_12 56 41](https://user-images.githubusercontent.com/86545040/123533364-7de8f100-d747-11eb-8759-fca54cbf8de0.png)

**Comment by Whitelisted1** [comment]
Does this happen without shaders?

If that doesn't fix it please send an f3 screenshot

**Comment by Fahkeet** [comment]
Same issue with every shader pack. Issue isn't present with internal/off shaders.

**Comment by KaiAF** [comment]
Addressed here: #5897.
