### ISSUE TITLE
Glow Squid Particles

### ISSUE THREAD

**Issue by Maisa85** [sp614x/optifine#5893]
## Description of Issue
Glow Squid particles shine over everything even when they are deep underground.

## OptiFine Version
OptiFine HD U G9 pre23

## Installation Method
Standalone installer, no forge/fabric etc.

## Other Installed Mods
Texture packs; JermsyBoys vanilla edits, better connected glass and sildur's enhanced default shaders (turning shaders&textures on/off made no difference)

![squidglow](https://user-images.githubusercontent.com/29552408/123535327-c692b100-d72b-11eb-8bec-c3dee72ed8a4.png)
![squidglow1](https://user-images.githubusercontent.com/29552408/123535328-c72b4780-d72b-11eb-9726-5bc5d3320f3e.png)

**Comment by Cy4Shot** [comment]
For me this also occurs with torches and drip particles

**Comment by Whitelisted1** [comment]
Could you please send an f3 screenshot?

**Comment by Whitelisted1** [comment]
If you haven't updated to Pre23, try updating (as addressed in #5861)

**Comment by Maisa85** [comment]
Oh hi! The issue is solved with pre23! My bad, I had the pre22, I thought I had the latest because I downloaded it yesterday, seemingly just before the update.
