### ISSUE TITLE
[1.8.9] Optifine cape not loading correctly

### ISSUE THREAD

**Issue by BlackHummingBird** [sp614x/optifine#5898]
## Description of Issue
Certain optifine capes/ banners are not showing as on the website
not sure if this is minecraft or optifine tho

## Steps to Reproduce
set this as optifine cape: shows different on the link as on the actual cape https://www.needcoolshoes.com/banner?=eapupoeLfK
On the website:
![image](https://user-images.githubusercontent.com/60234159/123545021-f81c7400-d74d-11eb-9941-c937f26e97ab.png)
in game:
![image](https://user-images.githubusercontent.com/60234159/123545034-079bbd00-d74e-11eb-97cc-2928fd00fa10.png)

## OptiFine Version
1.8.9 latest

## Installation Method
Lunar client / tested on vanilla optifine same as well

## Log Files/Crash Reports
none / non applicable

## F3 Debug Screenshot
https://i.imgur.com/liBbFf4.png

## Prior Testing
tried in both lunar client 1.8.9 and the latest optifine standalone and both produced the same issue

**Comment by Whitelisted1** [comment]
Optifine does not allow the Mojang logo to be on capes, and so it automatically removes it in game
