### ISSUE TITLE
[1.17] spam in logs

### ISSUE THREAD

**Issue by Michael1297** [sp614x/optifine#5899]
## Description of Issue
spamming "Failed to load texture: minecraft:capeof"   in logs

## Steps to Reproduce
1. Join the server (for example mc.hypixel.net)
2. look in the logs

## OptiFine Version
preview_OptiFine_1.17_HD_U_G9_pre23

## Installation Method
drop the JAR file into "mods" folder

## Fabric/Forge Version
Fabric

## OptiFabric Version
optifabric-1.11.9

## Other Installed Mods
fabric-api-0.36.0+1.17
modmenu-2.0.0-beta.7

## Log Files/Crash Reports
https://paste.ee/p/okDnT

## F3 Debug Screenshot
<details><summary>F3 Debug Screenshot:</summary>

![2021-06-27_17 38 44](https://user-images.githubusercontent.com/38764610/123548722-af28e780-d76e-11eb-91a2-5e9e9b1baa12.png)
</details><br/>

## Prior Testing

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   - Only OptiFine, OptiFabric, and Fabric: yes
- Does this happen in OptiFine standalone?  yes
- Does this happen in Vanilla without OptiFine?  no
- Does the issue still happen with only the remaining mods installed?
   - Fabric and remaining mods, without OptiFine:  no

**Comment by Whitelisted1** [comment]
When is says "Failed to load capeof/_username_" I think the client is able to retrieve the information that that player has a cape, but for whatever reason can't get the specific cape texture. 

Can you see other players capes in-game?

**Comment by Ari-RERA-43** [comment]
>I think the client is able to retrieve the information that that player has a cape, but for whatever reason can't get the specific cape texture.

I checked some users in the log and they did not have capes

**Comment by Whitelisted1** [comment]
> > I think the client is able to retrieve the information that that player has a cape, but for whatever reason can't get the specific cape texture.
> 
> I checked some users in the log and they did not have capes

If you can't see them in-game and they have an optifine cape, then I would assume something like an antivirus is blocking the cape textures

**Comment by Michael1297** [comment]
> Вы можете увидеть плащи других игроков в игре?

yes
<details><summary>Screenshot:</summary>

![2021-06-27_18 12 54](https://user-images.githubusercontent.com/38764610/123549903-a1299580-d773-11eb-8ca0-0436cbd8f2dd.png)
</details><br/>

The error occurs even with my account
<details><summary>Screenshot:</summary>

![1](https://user-images.githubusercontent.com/38764610/123550002-03829600-d774-11eb-802e-0734822bda42.png)
</details><br/>

**Comment by Ari-RERA-43** [comment]
> If you can't see them in-game and they have an optifine cape, then I would assume something like an antivirus is blocking the cape textures

The cape servers are unblocked on my PC and I do not have an antivirus. I also just checked NameMC and they do not have capes displayed there either. Capes showing on NameMC are not affected by blocked cape servers.

**Comment by Whitelisted1** [comment]
> > If you can't see them in-game and they have an optifine cape, then I would assume something like an antivirus is blocking the cape textures
> 
> The cape servers are unblocked on my PC and I do not have an antivirus. I also just checked NameMC and they do not have capes displayed there either. Capes showing on NameMC are not affected by blocked cape servers.

Then I would assume this would happen because they DON'T have a cape, which I guess also makes sense

**Comment by Michael1297** [comment]
I do not have an antivirus and host files are empty.
1.16.4 mc works fine

> Then I would assume this would happen because they DON'T have a cape, which I guess also makes sense

I think this happens to all players

**Comment by sp614x** [comment]
Fixed, coming in next preview.
