### ISSUE TITLE
Resource Pack Blurry Textures

### ISSUE THREAD

**Issue by FunAverage57** [sp614x/optifine#59]
I created a resource pack which adds a lot of weapons. Some weapons use a 19x19 grid instead of the usual 16x16 grid for a sword. In normal Minecraft 1.9 the texture is good, however when I'm using Optifine the image is now blurred.
![2016-04-02_22 22 41](https://cloud.githubusercontent.com/assets/18238769/14230375/d077b96a-f921-11e5-806e-b9aa3055d0a5.png)
Minecraft 1.9
![2016-04-02_22 21 53](https://cloud.githubusercontent.com/assets/18238769/14230376/d57c0eac-f921-11e5-8f7b-6a13546e3e12.png)
Minecraft 1.9 with Optifine

**Comment by sp614x** [comment]
Not power of 2 (Po2) textures are not compatible with mipmaps.
OptiFine upscales non-Po2 textures to Po2 when mipmaps are enabled.
Vanilla disables mipmaps when non-Po2 textures are loaded (look at the vanilla grass).
To fix the non-Po2 textures being upscaled you can disable mipmaps.
