### ISSUE TITLE
[Optifine 1.17 pre23] Broken Sheep CEM & Broken Squid CEM w/ randomized textures

### ISSUE THREAD

**Issue by BellPepperBrian** [sp614x/optifine#5902]
## Description of Issue
Sheep CEM and maybe squid CEM is broken.  For the sheep, the body won't appear in 1.17, while it does in 1.16.5.  I'm using a pack where all the sheep's white part of the wool is the same color as the colored parts.  The squid in the other hand, it has a random file where the texture is randomized, but it also has CEM.  In 1.16.5 there is no problem with the squids changing textures randomly and with CEM as well, but in 1.17 the squid only shows its default texture.  I'm not sure if it's a randomized texture issue or broken CEM.

## Steps to Reproduce
1. I tried both on 1.16.5 and 1.17 and noticed that 1.17's sheep CEM and maybe squid CEM is broken.
2. I didn't change any files between the 2 versions besides for moving the normal squid texture to its new spot in its folder like in 1.17.  The texture isn't bugged.  I'm not sure how else I'm suppose to reproduce it besides for testing it in two different versions.

## OptiFine Version
1.17

## Installation Method
I double left clicked optifine and I installed it (standalone).

## Log Files/Crash Reports

This problem doesn't crash my game or anything, but I'll put it up here if it helps.

[2021-06-27-3.log](https://github.com/sp614x/optifine/files/6721955/2021-06-27-3.log)

## F3 Debug Screenshot

![2021-06-27_12 40 00](https://user-images.githubusercontent.com/74277198/123552624-fac69b80-d744-11eb-93ec-28c290ecc6fe.png)

## Prior Testing

- Does this happen in Vanilla without OptiFine?
The things I'm using are not possible in Vanilla.  You cannot have randomized mob textures, nor can you have cem in Vanilla.
- Does this happen in OptiFine standalone?
Yes, as far as I know, this is only an Optifine standalone problem.

**Comment by KaiAF** [comment]
I am adding the Details needed label so that maybe someone can help and try to reproduce this bug. Until then, im just going to label this as a bug because I don't know how CEM works.

**Comment by BellPepperBrian** [comment]
I figured out why they don't work.  Apparently the sheep cem was broken and that's why it worked in 1.16, and the squid filed changed in 1.17 which is why the random textures with the squid didn't work.  So basically these aren't problems and don't need to be fixed.  Sorry for wasting time.
