### ISSUE TITLE
[Shaders] Error: Invalid program "gbuffers_ 

### ISSUE THREAD

**Issue by joshuakiryu** [sp614x/optifine#5909]
## Description of Issue

Invalid Program shaders errors
"gbuffers_basic"
"gbuffers_textured"
"gbuffers_terrain"
"gbuffers_block"
"gbuffers_entities"
"gbuffers_entities_glowing"
"gbuffers_hand"
"gbuffers_weather"
"gbuffers_water"
![Minecraft_ 1 17 6_27_2021 7_46_00 PM](https://user-images.githubusercontent.com/73140747/123563108-d092cf00-d780-11eb-9697-6909e57902a6.png)

## Steps to Reproduce
using BSL shaders, had tested multiple versions of the shader itself to see if that was the problem, but using the current 8.0.01, and previous v 8.0 that I had working fine in minecraft 1.16.5, both show the same message and do not display correctly

## OptiFine Version

pre 24, but also has been the same issue using every pre version that had shaders

## Installation Method

used the installer

## Fabric/Forge Version

fabric 0.7.3 with api 0.34.9 
though running through optifine instead has the problem still

## OptiFabric Version

optifabric 1.11.9

## Other Installed Mods

custom skin loader
death controls
flytrelib
inventory pause
mod menu
respawnable pets
voxelmap

running without the mods still doesn't fix the issue though

## Log Files/Crash Reports

[2021-06-27-2.log](https://github.com/sp614x/optifine/files/6722496/2021-06-27-2.log)

## F3 Debug Screenshot

![Minecraft_ 1 17 6_27_2021 8_10_25 PM](https://user-images.githubusercontent.com/73140747/123563620-c8885e80-d783-11eb-8c88-b14397643ad1.png)

## Prior Testing

happens every time shader is loaded using optifine, other mods or not
specifically BSL shader

**Comment by fayer3** [comment]
this info is for sp614x:
the error comes from the fact, that bsl uses the same shader files for vertex and fragment shaders which causes your shader patching to include inputs in the fragment shader, which are only meant for the vertex shader.
to be exact they are the following: 
```
uniform mat4 modelViewMatrix;
uniform mat4 projectionMatrix;
uniform mat4 textureMatrix = mat4(1.0);
uniform vec3 chunkOffset;
in vec3 Position;
in vec4 Color;
in vec2 UV0;
in ivec2 UV1;
in vec3 Normal;
```
from these `in ivec2 UV1;` causes the compile error, since integer inputs cant be interpolated between vertices and need a 'flat' qualifier.
the NVIDIA driver seems to ignore these since they are not actually used in the final shader, but AMD seems to not do that.
to fix the problem, you should only add these inputs to the `.vsh` shaders, where they are actually needed.

**Comment by fayer3** [comment]
can you test with pre25, it should work now

**Comment by joshuakiryu** [comment]
ah it has been fixed with pre25

**Comment by amawdiin** [comment]
[fayer3](https://github.com/fayer3) hey 

> from these `in ivec2 UV1;` causes the compile error, since integer inputs cant be interpolated between vertices and need a 'flat' qualifier. the NVIDIA driver seems to ignore these since they are not actually used in the final shader, but AMD seems to not do that. to fix the problem, you should only add these inputs to the `.vsh` shaders, where they are actually needed. this also causes the shader to fail to compile with intel.

its alright, but can you explain me how exactly are you going to do this??

**Comment by fayer3** [comment]
not sure what you want, that was an optifine bug, that got fixed.

**Comment by StraxGC** [comment]
![Screenshot_20240806-230802_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/user-attachments/assets/25e14799-7957-47b3-b20f-4a358181b610)
Como lo puedo solucionar uso la verzion 1.16.5

**Comment by PallzPOJAV** [comment]
echo "# deferred1.vsh-deferred1.vsh-0-213-L0003-Keyword-noperspective-is-reserved" >> README.md
git init
git add README.md
git commit -m "first commit"
git branch -M main
git remote add origin https://github.com/PallzPOJAV/deferred1.vsh-deferred1.vsh-0-213-L0003-Keyword-noperspective-is-reserved.git
git push -u origin main

**Comment by PallzPOJAV** [comment]
![Screenshot_2024-09-14-11-54-19-225_net kdt pojavlaunch](https://github.com/user-attachments/assets/95301991-47e8-4cea-a084-8f313d3e54f4)
bagaimana cara mengatasi nya di versi 1.21

**Comment by fayer3** [comment]
@PallzPOJAV you are using Iris, not optifine

**Comment by PallzPOJAV** [comment]
@fayer3 sodium iris

**Comment by PallzPOJAV** [comment]
@fayer3 im sodium and iris

**Comment by PallzPOJAV** [comment]
@fayer3 I use sodium and iris, all shaders can't be used

**Comment by Ari-RERA-43** [comment]
> @fayer3 I use sodium and iris, all shaders can't be used

This issue tracker is for OptiFine issues, not Iris and/or Sodium.
