### ISSUE TITLE
Smart tree (leaves) culling issue.

### ISSUE THREAD

**Issue by Dashsmashing** [sp614x/optifine#591]
When two leaves of the same type are next to each other but the decay state is different, the inner leaf faces will be rendered. Both leaf faces will be rendered at the same time causing double planing.

**Comment by Dashsmashing** [comment]
Wow the Godly creator of Optifine added a label to my bug report. My lyfe is complete.

**Comment by sp614x** [comment]
Added a second label, I like to make the people happy.

**Comment by sp614x** [comment]
Updated preview C5 for 1.12
 - fixed Smart Leaves not culling when decayable state is different
