### ISSUE TITLE
Sildurs dark sky oddity

### ISSUE THREAD

**Issue by Sparkthecat** [sp614x/optifine#5910]
## Description of Issue
 When i jumped in a water source or river the sky goes dark for a few short seconds

## Steps to Reproduce
1.Jump in water and in a few seconds the sky goes pitch black.

## OptiFine Version
 1.17 pre 24

## Installation Method
Standalone
![2021-06-27_18 07 31](https://user-images.githubusercontent.com/86541733/123565862-15176e00-d773-11eb-9af7-dd45f0aeebd9.png)

**Comment by KaiAF** [comment]
Addressed here: #5925.
