### ISSUE TITLE
Shader Bugs: Performance issues (lower than expected FPS), Block highlight glitches

### ISSUE THREAD

**Issue by JiggBone** [sp614x/optifine#5911]
## Description of Issue
 Shader bug reports, Chocapic shader shadow issues, spamming shadows of trees and entities, seeming to do with the way shadows are rendered in front of player.  Shader issue where enchanted items/armor glow effect stays static, no movement for enchanted item effect. MOST CRITICAL ISSUE: Block highlight with many shaders seems glitched, either appearing transparent, removing block outline altogether or causing the highlight to appear far from highlighted block (See Picture)
![2021-06-27_21 19 11](https://user-images.githubusercontent.com/86579644/123570544-0ab69d80-d78e-11eb-98aa-e57aa1b0632f.png)

## Steps to Reproduce
1. What do you do...
2. ...to find this bug?
regular shader enable
## OptiFine Version
 Newest, pre24

## Installation Method
 optifine.com, no issues here

## Prior Testing
 Only shader issues with newest optifine version

## Additional Information
 The only issues here are with the shaders i have noticed issues with, Chocapic V9 and BSL as well as BSL edits. I've tried 11 shaders in total, with the enchatnted item effect appearing with every shader, and Chocapic shadow glitching.
![2021-06-27_20 19 24](https://user-images.githubusercontent.com/86579644/123566471-64ff3080-d785-11eb-91d7-67687c3c0a75.png)
![2021-06-27_20 19 36](https://user-images.githubusercontent.com/86579644/123566488-6df00200-d785-11eb-953f-67877bde6a45.png)
![2021-06-27_20 18 22](https://user-images.githubusercontent.com/86579644/123566499-721c1f80-d785-11eb-9cb5-9e19b302df43.png)
![2021-06-27_20 18 50](https://user-images.githubusercontent.com/86579644/123566516-77796a00-d785-11eb-85a6-eafb6cba212e.png)

**Comment by KaiAF** [comment]
Hitbox issue is already reported here: #5897. Performance issues have been reported everywhere. Takes time to fix that.
