### ISSUE TITLE
1.17 pre24 on Linux some objects are black.

### ISSUE THREAD

**Issue by deathbird909** [sp614x/optifine#5912]
Following objects are solid black: llamas, mules, beds, signs, chests, shields, myself. Not barrels though. 
Maybe more things too. 
Issue was not present on pre21, but was also present on pre22 and pre23
Seems fine on Windows.

**Comment by MintMellowCat** [comment]
Same with me.

**Comment by KaiAF** [comment]
Addressed here: #5891
