### ISSUE TITLE
[Shaders] Performance issues and static enchanted animation

### ISSUE THREAD

**Issue by CRIMS0NN** [sp614x/optifine#5913]
## Description of Issue
Depending on the shaders I am using as well as just having shaders enabled (wether it be on internal or any that I have) my performance is greatly decreased. I am usually able to get around 200+ fps with render distance on 10 and FOV on 100 WITH using shaders in previous versions. That is not the case here. I am just about limited to 60 with an RTX 2080 and 32GB of RAM. 

Along with that, I noticed that with using any shader the enchant animation in 3rd person is frozen and static. 

I will add to this if I find any more bugs. Thanks for looking!

## Steps to Reproduce
1. Turn on shaders to internal or any other shader of your choice
2. set FOV to 100 and watch your FPS drop!

## OptiFine Version
preview_OptiFine_1.17_HD_U_G9 pre24

## Installation Method
download Installer and click Install!

## Fabric/Forge Version
None

**Comment by CheeseLouise1** [comment]
I have the same issue, shader performance feels much worse lately, maybe because we're still in pre-releases, but still, hoping it improves soon

**Comment by Whitelisted1** [comment]
The performance issue is everywhere with shaders, and the static enchanted animation problem is noted about in #5846

**Comment by KaiAF** [comment]
Pretty much what whitelisted said
