### ISSUE TITLE
[Bug] Charged Creeper Forcefield not animated.

### ISSUE THREAD

**Issue by Killercat103** [sp614x/optifine#5916]
## Description of Issue
The Charged Creeper forcefield is not animated with shaders.

## Steps to Reproduce
1. Enable Shaders
2. Charge a Creeper (I.E. with lightning).

## OptiFine Version
OptiFine 1.17_HD_U_G9_pre24

## Installation Method
The standalone installer from [Optifine](https://optifine.net/downloads).

## Other Installed Mods
None.

## F3 Debug Screenshot
![Screenshot](https://user-images.githubusercontent.com/75360760/123619371-64a87900-d809-11eb-94dd-8993fdff89df.png)

[Video](https://user-images.githubusercontent.com/75360760/123619684-b4874000-d809-11eb-8ced-a607dccaaf99.mp4)

## Prior Testing
This happens only on Optifine 1.17 pre release with shaders. 1.16 shaders are completely fine. Also no resource packs or mods affect this.

**Comment by Killercat103** [comment]
I figured out that this bug also applies to enchantment glints

**Comment by Whitelisted1** [comment]
Haven't tested this out myself, but make sure that you have all your animations enabled, and if that doesn't work this is the same problem as #5846 and #5913
