### ISSUE TITLE
[Bug] BDcraft crashes with mipmap levels high

### ISSUE THREAD

**Issue by NecrochildK** [sp614x/optifine#5918]
## Description of Issue
Crashes with texture resource pack, or at least with Chroma Hills as soon as world is loaded.

## Steps to Reproduce
1. Start up program
2. Make sure Chroma Hills is turned on in resource packs
3. Start up world, single or multiplayer

## OptiFine Version
OptiFine HD U G9 pre24 and OptiFine HD U G9 pre23

## Installation Method
Used the stand alone installer

## Other Installed Mods
SEUS shaders and Chroma Hills resource pack

## Log Files/Crash Reports
[latest.log](https://github.com/sp614x/optifine/files/6726017/latest.log)

## F3 Debug Screenshot
Game doesn't run long enough to be able to access.

## Prior Testing
- Does this happen in Vanilla without OptiFine? No

## Additional Information
I tested to see if it happened with another resource pack I use and it seems to be fine, only Chroma Hills as far as I know.

**Comment by fayer3** [comment]
does this also happen without shaders?

**Comment by albertboettger** [comment]
I am experiencing the same issue.  Using the latest video drivers, latest Optifine (G9 pre 24) and latest Chroma Hills (which is for 1.16) and the built-in Minecraft Java version (reported as OpenJDK 64-bit Server VM Microsoft-22300); I tried the following:

Minecraft Vanilla with Chroma Hills - OK
Minecraft Optifine with NO texture pack and NO shaders - OK
Minecraft Optifine with NO texture pack with shaders (Sildurs enchanced default) - OK
Minecraft Optifine with Chroma Hills and NO shaders - crash within a few seconds of loading the world.
Minecraft Optifine with Chroma Hills with shaders (Sildurs enhanced default) - crash within a few seconds of loading the world

The crash reports EXCEPTION_ACCESS_VIOLATION (0xc0000005).  The Problematic frame is C [nvoglv64.dll+0xe9c940].  So the crash only occurs for me when Chroma Hills is enabled.

**Comment by NecrochildK** [comment]
> does this also happen without shaders?

It happens with or without shaders in Optifine, but is fine without Optifine.

**Comment by fayer3** [comment]
did some testing, looks like the option 'Terrain Animated'  causes the game to crash with Chroma Hills.

**Comment by albertboettger** [comment]
Disabling "Terrain Animated" works for me as well, including with shaders.

**Comment by NecrochildK** [comment]
> did some testing, looks like the option 'Terrain Animated' causes the game to crash with Chroma Hills.

Thanks, that did help. Though what does that option even do? I don't see a visual difference.

**Comment by Whitelisted1** [comment]
> > did some testing, looks like the option 'Terrain Animated' causes the game to crash with Chroma Hills.
> 
> Thanks, that did help. Though what does that option even do? I don't see a visual difference.

Not 100% sure but I would assume that if the resource pack has it available you can has block textures cycle through to animate them, like with some resource packs it shows the discs spinning instead of them just staying still, except for the blocks instead of items

**Comment by harucy** [comment]
i have this problem too, but it persists even when terrain animated is off and no resource packs are applied

**Comment by harucy** [comment]
update : it works with or without any resource packs when i have no shaders on, but if i select any of them the game crashes when i load worlds

**Comment by harucy** [comment]
[crash log.txt](https://github.com/sp614x/optifine/files/6737195/crash.log.txt) i hope this helps

**Comment by fayer3** [comment]
> 
> 
> [crash log.txt](https://github.com/sp614x/optifine/files/6737195/crash.log.txt) i hope this helps

your are on mac, see this issue #5900

**Comment by fayer3** [comment]
@KaiAF why was this closed, the issue is not fixed?

**Comment by KaiAF** [comment]
Did not mean to. I thought this was harucy's issue and thought this was a duplicate

**Comment by ActualCody** [comment]
This is also happening to me but literally all I have is optifine and it was working earlier today but now with the same optifine version it doesn't work

**Comment by chasejsutton49** [comment]
Crashes while using PureBDcraft with Animated Terrain. Can confirm this issue is exclusive to Optifine 1.17+. Managed to get a screenshot within the 3 seconds before crashing. This occurs in Singleplayer and Multiplayer worlds and Realms.
![terrain_animated_crash](https://user-images.githubusercontent.com/19761194/130691988-030102a5-d57a-4c96-b930-e05d7560231a.png)

**Comment by fayer3** [comment]
did some further testing, and it seems for both PureBDcraft/Chroma hills the crash has something to do with one of the conduit animations. both resourcepacks tested with the 128x version
the crash happens only in one of these cases:
- mipmaps to max and smart animations disabled
- mipmaps to max and smart animations enabled and a conduit is in a loaded chunk

the crash does not happen if:
- mipmaps is on something below max
- smart animations enabled and no conduit is in a loaded chunk
- terrain animated is disabled in the animation settings
   - this disables the wind animation of the conduit, maybe this has something to do with it?

**Comment by chasejsutton49** [comment]
Deleting the textures/entity/conduit folder or textures/particle/nautilus.png in the resource packs doesn't help, so reverting the conduit textures doesn't do anything. I'm guessing it is the strands of blue line surrounding the conduit, or the "wind" that's causing it, which is bizarre since resource packs can't change that. My current thought is that there's something in the optifine folder of these resource packs (hence this issue only happening with optifine) but I can't find a single file tied to the conduit or anything related.
Also, just tested the issue with John Smith Legacy (32x) and no crashes with that at all.

**Comment by fayer3** [comment]
will do further testing, maybe it's some other texture which only causes problems when the conduit is there.

**Comment by chasejsutton49** [comment]
I played with BDcraft on a Mac and it doesn't crash at all. I have mipmaps at max level, Terrain Animated ON, and a conduit present. The only problem here is the conduit wind animation being super glitchy. Attached are screenshots of the Mac specs and a glitchy conduit.
![2021-08-31_08 14 27](https://user-images.githubusercontent.com/19761194/131510015-ef950e7b-c859-4062-803d-377eec71c5ac.png)
![2021-08-31_08 15 42](https://user-images.githubusercontent.com/19761194/131510029-f8ede5df-1b4e-43a9-bf1a-d15cffc5671c.png)

**Comment by HanFox** [comment]
If this is all one and the same issue it's definitely an issue with mipmaps, and it only seems to effect Nvidia cards.

Almost every day via the BDcraft Discord and forum I have to advise people to disable mipmaps to workaround crashes.

@sp614x Can you take a look? Maybe some feedback about why it's happening?

Here's the forum thread with lots of reports: https://bdcraft.net/community/bug-reports-f3/purebdcraft-117-crashing-with-optifine-nvidia-t8363.html

You can also just search "mipmap" on the BDcraft Discord and see how often with the advice and see that everyone says that disabling them fixes the crash.

**Comment by sp614x** [comment]
@HanFox is this still happening with G9 release and latest H1_pre3?

**Comment by HanFox** [comment]
@sp614x I've asked someone who did get the crash to re-test (as I never personally did) and it seems to have fixed.

I guess it'd be prudent if people in this issue itself could also check to verify.

@NecrochildK ?

**Comment by chasejsutton49** [comment]
@HanFox sorry to argue the contrary, but I just retried BDcraft with H1_pre3, turned Mipmaps to Max, and then it crashes, just like before. Using NVIDIA GeForce RTX 2070, assuming that it really does happen exclusively with NVIDIA.

**Comment by chasejsutton49** [comment]
![crash_proof](https://user-images.githubusercontent.com/19761194/135466752-04418efc-1451-41f4-b48d-d890168773ca.PNG)
As proof that this happened today while using H1_pre3. After googling "nvoglv64.dll" it definitely is NVIDIA related.
@HanFox did the person who said it's been fixed use Mipmaps at max level, and Terrain Animated on?

**Comment by sp614x** [comment]
Tested BDCraft 32x 1.17 + OF H1_pre3 on NVidia with animated terrain ON, no crashes.
Can someone post the full crash log (`hs_err_pid*. log`)?

**Comment by fayer3** [comment]
didn't happen with he 32x or 64x version, but with the 128x version
[latest.log](https://github.com/sp614x/optifine/files/7274222/latest.log)
[hs_err_pid12684.log](https://github.com/sp614x/optifine/files/7274224/hs_err_pid12684.log)

**Comment by sp614x** [comment]
Crash when uploading the animated sprite `minecraft:entity/conduit/wind`.
The conduit wind animation is loaded from default RP and is using using frame height, which got messed when resizing the sprite.
Fixed, coming in next preview.
