### ISSUE TITLE
OptiFine fullscreen mode is black

### ISSUE THREAD

**Issue by yoctomentric** [sp614x/optifine#592]
Upon installing optifine and entering the game, if I enter fullscreen and then exit it, the window goes pitch black and I cannot interact with it further other than closing it. If I close the window while it is black, all, ALL versions of the game become greyed out. The only solution I have found is to reinstall minecraft.

It makes the game unplayable, but I need optifine.

**Comment by jredfox** [comment]
What versions have you tried 1.7.10? 1.8? The crashing the game going black on going into full screen is a vanilla bug

**Comment by yoctomentric** [comment]
Thanks for responding! I haven't tried other versions, but the game going black never happens without optifine. My solution is to only enter windowed fullscreen mode when I have optifine installed.

**Comment by sp614x** [comment]
You can try to set the fullscreen mode to Default.
Video Settings -> Other -> Fullscreen Mode -> Default

**Comment by Tsoccerguy3** [comment]
Duplicate of Minecraft's window turns black after leaving fullscreen mode #428 

Fixed in Newer version see issue 428 . Close
