### ISSUE TITLE
[Bug] Using SHADERS BSL Almost everything is really bright with SHADERS ON

### ISSUE THREAD

**Issue by metooyt** [sp614x/optifine#5920]
## Description of Issue

When using any version of opfitine 1.17 (from the **"OptiFine 1.17_HD_U_G9_pre22"** to the **"OptiFine 1.17_HD_U_G9_pre24"**) AND the shaders BSL v8.0.01 (and previous) everything looks really bright

## Steps to Reproduce
to find this bug i just installed optifine (pre24, then tested with other versions of 1.17 as i found the bug) and installed from the main source the BSL shaders 8.0.01, (also tested with 8.0, same thing happened), then i saw everything as i just described it, also i moved a lot of shader and video options and nothing fixed it.

## OptiFine Version
any 1.17

## Installation Method
i installed optifine with the installer

## F3 Debug Screenshot

![2021-06-28_11 15 15](https://user-images.githubusercontent.com/86618508/123671094-86066680-d803-11eb-813d-cd1d104f8a25.png)

## Prior Testing
it doesn't happen on vanilla standalone

**Comment by fayer3** [comment]
duplicate pf #5909

**Comment by metooyt** [comment]
okay... but how do i fix it exactly? (i read the reply, but i actually didn't understand how to fix it, if you said it)

**Comment by Whitelisted1** [comment]
No solution yet, unless if I overlooked it

**Comment by KaiAF** [comment]
Addressed here: #5909.
