### ISSUE TITLE
Enchanted items still black

### ISSUE THREAD

**Issue by Juan8616** [sp614x/optifine#5927]
## Description of Issue
I was using Sildurs Vibrant shaders, and my enchanted items were black, again.

## Steps to Reproduce
1. Use Sildurs Vibrant Shaders, that's all

## OptiFine Version
Optifine 1.17 pre24

## Installation Method
Standalone

## Other Installed Mods
I don't have mods

## Additional Information
A photo:
![2021-06-27_11 53 26](https://user-images.githubusercontent.com/76629257/123712378-d5ff2080-d837-11eb-87dc-bf84067ba3ce.png)

**Comment by geo3p** [comment]
Duplicate of or similar to #5894

**Comment by Juan8616** [comment]
Uhm, that was with the pre23 version. and, supposedly, it was fixed in the pre24, and I'm running that version

**Comment by Whitelisted1** [comment]
> Uhm, that was with the pre23 version. and, supposedly, it was fixed in the pre24, and I'm running that version

For 1, it was the pre 24 version (in title)

And 2, where did you get the info that it was fixed in pre24?

I also would like to know what operating system you are running

**Comment by Juan8616** [comment]
1. I mean, the error was with the pre23.
2. They closed my last issue (it was exactly this issue), and they wrote "Duplicate to # 5891". The changelog say that the issue was fixed.
(sorry, if I did a mistake writing it's because my native language isn't english)

**Comment by Juan8616** [comment]
I was confused, it was another error (5891). Sorry
