### ISSUE TITLE
[Category] Weird FPS drops while using shader and switching windowed/fullscreen

### ISSUE THREAD

**Issue by boofiboi** [sp614x/optifine#5931]
## Description of Issue
While having any shader enabled (I prefer SEUS PTGI HRR or Sildurs Vibrant Extreme) the game performs as expected in windowed mode. PTGI - 40-50FPS Sildurs - 90-110 FPS
However after switching into fullscreen mode the FPS drops immidiately. PTGI - 20-25 Sildurs - 40-45

## Steps to Reproduce
1. Load Optifine
2. Load shaders
3. Enter game
4. Toggle between fullscreen/windowed.

## OptiFine Version
Optifine 1.16.5 HD G8 Ultra

## Installation Method
Installed via. TLauncher

## Log Files/Crash Reports
I don't think you need logs for this.

## F3 Debug Screenshot
![2021-06-29_08 48 06](https://user-images.githubusercontent.com/79476279/123829777-9546ec00-d8b7-11eb-9fa9-421222a670b7.png) - Fullscreen
https://shibe.host/snYqUVy.png - Windowed

Testing was done in my base on my favourite minecraft server, the render distance is forced on 6 by the server, and I have a huge cactus farm and iron golem farm the direction im facing.

## Prior Testing
No, Only on optifine with shaders

## Additional Information
I used 2 driver versions, Regular AMD drivers that get auto downloaded, and AMD Pro drivers. Both drivers yielded same results.

This also ties into my first issue here, about the shader renderer prefering NVidia cards, my suspicion in that issue is completely invalid, I believe it is not caused by the drivers/card, but due to this weird shader renderer bug.

**Comment by edbefee3-3888-462a-9411-741b7e9eb54e** [comment]
when it's windowed, is it just a small window?

**Comment by boofiboi** [comment]
It's a Fullscreen window

**Comment by boofiboi** [comment]
I see optifine devs dont care about optifine, thats good to know. Switched to a better alternative than this unoptimized shit. its called iris shaders, check it out.  https://irisshaders.net/
