### ISSUE TITLE
[Bug] openGL error on Linux

### ISSUE THREAD

**Issue by Dorus06** [sp614x/optifine#5932]
## Description of Issue

i keep getting this error when i start minecraft with optifine:
GLFW error 65543: GLX: Failed to create context: GLXBadFBConfig.

Please make sure you have up-to-date drivers (see aka.ms/mcdriver for instructions).

i only have this problem with optifine and on amd and intel GPU's
if i start minecraft normal then i dont get this error
almost no one has this issue beacause i use linux instead of windows
## Steps to Reproduce
1. What do you do...
2. ...to find this bug?

## OptiFine Version

all the 1.17 preview versions
## Installation Method

the normal installer

## Log Files/Crash Reports

GLFW error 65543: GLX: Failed to create context: GLXBadFBConfig.

Please make sure you have up-to-date drivers (see aka.ms/mcdriver for instructions).

[latest.log](https://github.com/sp614x/optifine/files/6735266/latest.log)

## F3 Debug Screenshot

mc doesn't even start

## Additional Information

my specs and OS name:
Ubuntu 21.04 and it also happens  on Ubuntu 20.04 and OpenSuse

'4th gen mobile intel i5 with intergrated graphics' in my laptop
'core 2 quad Q6600 with a amd HD 5450' for my mothers pc
'7th gen intel i5 with intergrated graphics' in my sisters laptop

it does not only happen on old systems

**Comment by Dorus06** [comment]
it works fine on my gaming pc with a Nvidia GPU

**Comment by fayer3** [comment]
duplicate of #5739

**Comment by Dorus06** [comment]
ok, thanks for letting me know that this bug already has been reported!

**Comment by kureshio** [comment]
I also have the same problem.

**Comment by onlytruejames** [comment]
I have the same problem
