### ISSUE TITLE
Clear Water option missing from video settings/details

### ISSUE THREAD

**Issue by Maisa85** [sp614x/optifine#5937]
## Description of Issue
Shouldn't there be a clear water option in details?

## OptiFine Version
OptiFine HD U G9 pre24

## Installation Method
standalone installer

**Comment by Whitelisted1** [comment]
It's in the quality settings, not details.

**Comment by Maisa85** [comment]
![nope](https://user-images.githubusercontent.com/29552408/123997534-2c579500-d9d9-11eb-959c-d185fab3150b.png)

**Comment by Whitelisted1** [comment]
It's at least there in 1.8

![clear water](https://user-images.githubusercontent.com/77711834/123998522-cc3c0100-d98e-11eb-97ae-8ac87bc00108.png)

**Comment by Maisa85** [comment]
1.8 what? I play MC 1.17 and the latest pre version of optifine. Went through every section and can't find it.

**Comment by Whitelisted1** [comment]
I don't think there is an option for clear water for 1.17 then

**Comment by mrktospl** [comment]
The "Clear Water" behaviour (water decreasing the light level by 1 and not 3) is a vanilla thing since 1.13

**Comment by KaiAF** [comment]
Closing since this is not an OptiFine issue
