### ISSUE TITLE
The Selection box when you hover over blocks is off to the right.

### ISSUE THREAD

**Issue by Buzzbee2019** [sp614x/optifine#5939]
## Steps to Reproduce
1. What do you do...
2. ...to find this bug? It is just there

## OptiFine Version
version 24

## Installation Method
standalone installer

## Log Files/Crash Reports
I dont know how to get logs

## F3 Debug Screenshot

![Untitled-2](https://user-images.githubusercontent.com/54824327/123992339-8a648800-d999-11eb-8bc7-0c19e61dcb06.png)
![Untitled-4](https://user-images.githubusercontent.com/54824327/123992348-8c2e4b80-d999-11eb-9616-899bac879a00.png)

**Comment by KaiAF** [comment]
Already addressed here: #5897.
