### ISSUE TITLE
White Screen/Frozen Game

### ISSUE THREAD

**Issue by bgreenlaw** [sp614x/optifine#594]
I have been using multiMC to load my mods for a longtime with no issue. All of my modpacks have optifine installed and ran without an issue. Recently, when i joined a sever or a world I was super zoomed in or the screen was white except for the GUI and my FPS was 0-1. I let my computer sit for 10 minutes and there was no change in the FPS. This issue was the same for all modpacks that I had on multiMC. I had not installed anything new recently. So, thinking MultiMc was the problem I began loading up my modpacks manually with Forge, this fixed the problem for a few days but then the same issues began happening again. I removed optifine from the modpacks and they worked fine without issues. Again, I had not installed anything new. While trying to solve the problem on my own, I tried joining a vanilla server with Optifine and found that the same problems were occurring. I should also mention that the game doesn't crash on its own, it just freezes or lags so bad that I have to force quit it.  I have tried reinstalling Optifine but to no avail. I have window 10 installed. 
Does anyone know how to solve the problem I'm having? or maybe tell me what might be conflicting with optifine?

**Comment by sp614x** [comment]
Does this happen with only Forge and OptiFine (no other mods installed)?

**Comment by Builderb0y** [comment]
Does disabling smooth FPS help? Framerate issues like this have been reported with it before.

**Comment by sp614x** [comment]
The Smooth FPS issue #583 is caused by Windows using wrong graphics card after Win10 update.
