### ISSUE TITLE
[Bug] Gray blocks on Optifine

### ISSUE THREAD

**Issue by Kyevky** [sp614x/optifine#5941]
## Description of Issue
There is an outline of gray blocks when I play. If the block is broken, it disappears. If a block is placed on top, it generally disappears. However if it is broken and replaced, it comes back. I think a render issue of some sort.

## Steps to Reproduce
N/A, it just spawns when I come onto game.

## OptiFine Version
OptiFine HD U G8

## Installation Method
I dropped the JAR file into my "mods" folder.

## Fabric/Forge Version
Forge 1.16.5-36.1.12

## Other Installed Mods
(This bug happened in 1.17 when I had no mods and no shaders)
Alexs Mobs 1.11.0
Biomes O Plenty
Builders Addition
Citadel
Collective
Doggy Talents
Fairy Lights
Just Enough Items
Journey Map
Mushroom Quest
Mystical World
Optifine
Pathoucli
Straw Golem
Travelers BAckpack
Tree Harvester

## F3 Debug Screenshot

[
![2021-06-30_13 54 18](https://user-images.githubusercontent.com/86739982/124009338-79bd0d80-d9ab-11eb-81f5-e589ad06baf8.png)
](url)

## Prior Testing
Does not happen in Vanilla without Optifine.
This still happens with Optifine standalone.
This happens regardless of whether or not I have mods installed.
This happens regardless of whether or not I am using forge.

**Comment by Whitelisted1** [comment]
I am unsure about what you are describing, could you please clarify? What you have described should be normal unless if I read it wrong

**Comment by Kyevky** [comment]
> I am unsure about what you are describing, could you please clarify? What you have described should be normal unless if I read it wrong

There is a gray outline on the blocks, sorry for my poor description. But if you can see in the screenshot there's an outline on top of the dirt (not caused by any texture pack)

**Comment by Kyevky** [comment]
I think it might be a render issue, but I don't know how to fix.

**Comment by Kyevky** [comment]
nevermind, it was my resource packs
