### ISSUE TITLE
Issue with optifine 1.17 pre on Manjaro-Linux

### ISSUE THREAD

**Issue by Mujaahid70** [sp614x/optifine#5942]
I seem to be having an issue with all of the optifine per-releases for minecraft 1.17 and they all give me the same error. That states 

GLFW error 65543: GLX: Failed to create context: GLXBadFBConfig.
Please make sure you have up-to-date drivers (see aka.ms/mcdriver for instructions).

Please be aware that i am running Linux-manjaro KDE.
Please advise, should it be a problem on my end that I should fix, or if it is a problem that will be fixed once the full release comes out.

![image](https://user-images.githubusercontent.com/69517853/124026792-67b28d80-d9f2-11eb-903f-3e1f24e93069.png)

**Comment by KaiAF** [comment]
Addressed here: #5900
