### ISSUE TITLE
Shadow in Shaders

### ISSUE THREAD

**Issue by eassym0ney** [sp614x/optifine#5947]
When I use SEUS shaders, I can see the chests, black objects when they are at home or in a closed place, I don't know if they are the leftovers or it is not well optimized or is it me?
![2021-06-30_20 19 19](https://user-images.githubusercontent.com/86752087/124046967-24035800-d9e1-11eb-96a0-0c2f994b71b2.png)

**Comment by KaiAF** [comment]
Addressed here: #5895
