### ISSUE TITLE
Cannot run any optifine version

### ISSUE THREAD

**Issue by wistfullyunaware** [sp614x/optifine#5948]
## Description of Issue
I have downloaded java SE and optifine but it wont launch. I tried to download another version, same issue. I ran minecraft on the required version prior to attempting. I tried redownloading everything. I tried cmd execution. I tried letting it through the antivirus.

## OptiFine Version
1.16.5 1.17

## Installation Method
included standalone installer

**Comment by edbefee3-3888-462a-9411-741b7e9eb54e** [comment]
so, the installer won't run?

**Comment by KaiAF** [comment]
Try installing [Jarfix](https://johann.loefflmann.net/jarfix). This could help with this issue

**Comment by ZenIsBestWolf** [comment]
This is a support issue and not a bug, for further assistance please contact us over Discord or feel free to send us an email at optifinex@gmail.com
