### ISSUE TITLE
[Shaders] WTF

### ISSUE THREAD

**Issue by Timtaran** [sp614x/optifine#5949]
![2021-07-01_10 34 09](https://user-images.githubusercontent.com/60805088/124070982-22c14200-da58-11eb-8fd9-f638d3c427db.png) SEUS v11
![2021-07-01_10 34 09](https://user-images.githubusercontent.com/60805088/124071112-51d7b380-da58-11eb-8d13-c76322b61718.png) SEUS v10.2-ULTRA
![2021-07-01_10 38 24](https://user-images.githubusercontent.com/60805088/124071221-79c71700-da58-11eb-8c9c-a27b4ee4ffee.png) SEUS Renewed v1.0.1
![2021-07-01_10 39 39](https://user-images.githubusercontent.com/60805088/124071376-a713c500-da58-11eb-91ca-2e12aae9121b.png) continuum_2.1_alpha_build_10
![2021-07-01_10 40 21](https://user-images.githubusercontent.com/60805088/124071499-d591a000-da58-11eb-9c7f-c8522bced88e.png) bsl_v7.1.05p2

## Steps to Reproduce
1. Enable Shaders

## OptiFine Version
<html>
<body>

OptiFine HD U G9 pre24

</body>
</html>

## Fabric/Forge Version
Fabric 0.11.6 1.17

## OptiFabric Version
1.16-1.17

## Other Installed Mods
fabric-api

**Comment by Ari-RERA-43** [comment]
> OptiFabric Version
> 1.16-1.17
That's supposed to be the OptiFabric version (latest is 1.11.9) not the Minecraft version OptiFabric is for.

**Comment by Timtaran** [comment]
https://user-images.githubusercontent.com/60805088/124073936-2b1b7c00-da5c-11eb-8468-873f7e2d9f8f.mp4
BSL Light Bug
