### ISSUE TITLE
[Category] Minecraft Crash Optifine 1.17 pre24

### ISSUE THREAD

**Issue by MrTheFunColas974** [sp614x/optifine#5954]
hello, i have a crash when i'm launch Minecraft with optifine 1.17 pre24

**Comment by Whitelisted1** [comment]
If you are using a mac, and are using shaders this is a duplex cate of #5900

**Comment by KaiAF** [comment]
Can you provide more information? Crash logs? Other mods? shaders? etc

**Comment by MrTheFunColas974** [comment]
Crash log : [hs_err_pid16492.log](https://github.com/sp614x/optifine/files/6752624/hs_err_pid16492.log)

OS : Windows 10
Ram : 32GO
Processor : i7 8700k

**Comment by KaiAF** [comment]
Java is crashing: 
`Problematic frame: C  [nvoglv64.dll+0xe9c940]`
It is caused by Nvidia Drivers, either update them or reinstall them. Unfortunately since this is caused by drivers I do not think OptiFine can fix this issue

**Comment by fayer3** [comment]
are you using a resource pack? this crash looks similar to #5918

**Comment by MrTheFunColas974** [comment]
ok i go to delete my texture pack

**Comment by fayer3** [comment]
no need to delete it, disabling "Terrain Animated" in the animation settings should keep it from crashing.

**Comment by aricxo** [comment]
@fayer3 thank you sooo much
