### ISSUE TITLE
Null armor on optifine 1.17

### ISSUE THREAD

**Issue by Iman05Rz** [sp614x/optifine#5957]
My pc is win7 32bit, i installed optifine from Tlauncher and all of armors are null for me when I wear them but I can see them when they are in my inventory.

**Comment by Iman05Rz** [comment]
![20210628_004321](https://user-images.githubusercontent.com/79393663/124239207-b2d1bb00-db2e-11eb-99fa-44cfb8421f8e.jpg)

**Comment by Ari-RERA-43** [comment]
You won't get help with an TLauncher here. Also, this has already been reported (using the vanilla launcher) so you should close this issue.

**Comment by Iman05Rz** [comment]
So I should use Minecraft launcher and download optifine from optifine.com/download to don't see this again?

**Comment by Ari-RERA-43** [comment]
Yes, while it probably won't fix the bug, you should download it from the official OptiFine site and use the vanilla launcher because TLauncher is illegal. You should also close this issue because it's already been reported.

**Comment by Iman05Rz** [comment]
Ok thx

**Comment by Ari-RERA-43** [comment]
Just for reference, here is the issue I was referring to: #5806

**Comment by IranMine123** [comment]
Please Close this page and Continue on #5806
