### ISSUE TITLE
[Bug] Entities and several items appears black when shaders are on

### ISSUE THREAD

**Issue by clementtttttttt** [sp614x/optifine#5958]
Entities and several items (door, shield, sign) appears black when any shader is used (including internal). 

Optifine version: 1.17 g9 pre24
OS: Debian testing x86_64
OpenGL version: mesa 4.5 compatibility profile

**Comment by edbefee3-3888-462a-9411-741b7e9eb54e** [comment]
shaders are said to still have issues
also, why are you using OpenGL 4.5 and not 4.6?

**Comment by KaiAF** [comment]
Already addressed here: #5891
