### ISSUE TITLE
Adding one incorrect block name into the 'block=' code line for colormap properties makes the biome ignore all specified blocks

### ISSUE THREAD

**Issue by babbajagga** [sp614x/optifine#596]
**I have changed the topic title based on the results of my investigation. See my last post on this topic.**

_(former topic description below)_
I got stuck on this today, when I tried to fix my color maps.
I think I got similar issue with water, which would explain why it looks the same across all biomes, but this is not confirmed yet, I have to investigate this first. *edit* confirmed: 'block=water_flow water_still' bugs out but at least 'block=water' works
I guess the same will be the issue with all my other colormaps for blocks like leaves, etc.
*confirmed: using 'blocks=leaves:0,4,8,12' nor 'blocks=leaves' is not working :/ colormaps are ignored

This is how it should look like, except the slabs being ignored...
![2017-04-14 6](https://cloud.githubusercontent.com/assets/2865693/25055701/b90b5ac2-2164-11e7-9826-b67fe9f2daef.png)

However after adding slabs to the properties file, it bugs out? and instead of making the slabs being colored according to the colormap it makes all the blocks being ignored by colormap O_o
![2017-04-14 7](https://cloud.githubusercontent.com/assets/2865693/25055702/b90c959a-2164-11e7-9854-b32360a9cb15.png)

**Comment by zombye** [comment]
IIRC you should use `stone_slab:variant=sandstone` for sandstone slabs. They use the same block as stone slabs.

**Comment by babbajagga** [comment]
thanks for the hint, I will try that one out for sure, any idea for the leaves?

**Comment by babbajagga** [comment]
Alright, I got it to work, not sure yet which part exactly was the troublemaker, but I will investigate it closer today. Seems the naming of the blocks was incorrect, either that or the missing source specified.

**Comment by sp614x** [comment]
OptiFine 1.11.2_HD_U_C2
 - fixed CTM, Custom Colors and Shaders block matching to better handle missing blocks
