### ISSUE TITLE
Optifine HD U G9 pre24 crashing Macbook air 2019

### ISSUE THREAD

**Issue by Hottentom1** [sp614x/optifine#5963]
## Description of Issue
I recently installed Optifine HD U G9 pre24 on my macbook. When I launch Minecraft it works perfectly fine, but the moment I join a server or a world my game crashes.

## Steps to Reproduce
1. I turn on minecraft
2. I join a world/server
3. The game crashes

## OptiFine Version
HD U G9 pre24

## Installation Method
I clicked the download and installed it normally through java.

## F3 Debug Screenshot
Cannot show as I cannot join a world

## Prior Testing
<!-- If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
This only happens with the newest optifine, older optifine versions work fine.

## Additional Information
I do not know what to do and would love to use optifine 1.17

**Comment by fayer3** [comment]
do you have shaders enabled? they currently don't work on macOS

**Comment by edbefee3-3888-462a-9411-741b7e9eb54e** [comment]
logs are kinda required for knowing what happen

**Comment by KaiAF** [comment]
Shaders are currently broken on MacOS. Addressed here: #5900.
