### ISSUE TITLE
Minecraft Crashes to Desktop

### ISSUE THREAD

**Issue by Thatsaidan1** [sp614x/optifine#5964]
When running any form of shader with pre24, the game will hard crash to desktop when I get within a certain proximity of an active nether portal. The problem stops when I turn shaders off, but starts again the moment I turn them back on. The game tells me “the game crashed whilst rendering chunk”

**Comment by edbefee3-3888-462a-9411-741b7e9eb54e** [comment]
could you give a log file? (doesn't matter if you edit out your user info and things like that)

**Comment by drnixon** [comment]
[latest.log](https://github.com/sp614x/optifine/files/6760243/latest.log)
Same. Immediate crash on load. I am only using the internal shaders, multiplayer server.

**Comment by Feel65** [comment]
I'm having the same issue, although it complains about having not enough memory

**Comment by mrktospl** [comment]
> 
> 
> [latest.log](https://github.com/sp614x/optifine/files/6760243/latest.log)
> Same. Immediate crash on load. I am only using the internal shaders, multiplayer server.

you're on a mac and shaders don't work on macs yet ( #5900 )
