### ISSUE TITLE
[Bug report] Furnace doing grass wave 

### ISSUE THREAD

**Issue by Oj-Studbone** [sp614x/optifine#5965]
## Steps to Reproduce
switched from 1.15.2 to 1.16.4 

## Installation Method
dropped the jar file into the mods folder 

## Fabric/Forge Version
forge 

## Other Installed Mods
ice and fire 
citadel 
jei
mowzie mobs 
xaeros minimap 
XP tome 

https://user-images.githubusercontent.com/74216562/124369900-830dda80-dc36-11eb-93fb-eda5584301f7.mp4
pretty weird huh

**Comment by KaiAF** [comment]
Happens on all shaders?

**Comment by KaiAF** [comment]
Closing because there hasn't been any reply from the author of the issue.
