### ISSUE TITLE
Performance issues and CTD

### ISSUE THREAD

**Issue by Maisa85** [sp614x/optifine#5966]
## Description of Issue
MC is taking literally everything out of my PC with optifine and this should not be the case. Is there some settings I can change to make it run better? Also crashes from lack of memory if I raise render distance to 20-28 which used to be normal.

## OptiFine Version
1.17 pre24

## Installation Method
Standalone

## Other Installed Mods
Sildurs Enhanced Default Shaders and Mizuno's 16x Texture Pack

![deta](https://user-images.githubusercontent.com/29552408/124377394-657f5600-dcb4-11eb-8b5b-73b5ed38558c.png)
![optifinestats](https://user-images.githubusercontent.com/29552408/124377395-6617ec80-dcb4-11eb-82db-4d0008bb9318.png)
![other](https://user-images.githubusercontent.com/29552408/124377396-67e1b000-dcb4-11eb-8b48-fb6eb4d7aca4.png)
![perf](https://user-images.githubusercontent.com/29552408/124377397-687a4680-dcb4-11eb-81ff-333a46e21a9f.png)
![qua](https://user-images.githubusercontent.com/29552408/124377399-6912dd00-dcb4-11eb-883d-e03a8d1515ac.png)
![vid](https://user-images.githubusercontent.com/29552408/124377402-6912dd00-dcb4-11eb-8f24-6f854097209f.png)

## Additional Information
Screenshots included of debug and settings.

Help, I can't live without shaders.

**Comment by jaxellis** [comment]
Remove shaders or limit your framerate. Since it seems like you really want shaders so limiting your framerate or turning down settings (either shader settings or optifine) would be the way to go. I know with BSL and optifine unconfigured I get 20fps, with them both configured I sit easily at my Max Framerate (60 FPS).

**Comment by Maisa85** [comment]
Ok, thank you. So the shaders are the main problem with my performance here? Is BSL lighter to run than Sildurs? I had some lag problems with another similar game to MC and weirdly with that the unlimited framerate was the way to go and fixed the lag. Is there some site where I can find readily made config options for BSL & Optifine? Recommends are welcome!

**Comment by jaxellis** [comment]
For me personally I've found BSL configured works better than Sildurs, but everyone's computer is different and Optifine still hasn't had the official stable 1.17 release yet so there may still be performance issues that can be resolved. But only SP614x knows that.

These are the settings I use. Haven't really had any client lag.
optionsof.txt (Optifine Settings): https://pastebin.com/ggRNcD7M
BSL_v8.0.01.zip.txt (BSL Settings): https://pastebin.com/LxwRQWvx

**Comment by Maisa85** [comment]
Good to know, I've played since 2012 but I just recently reinstalled Java version, I played BedRock a few years in between.
Dropping the framerate to 60fps almost halved the GPU load, so that worked great! I'll also test the BSL next.
This was very helpful, I'll close the thread since my problem is somewhat solved, thank you and have a great summer!
