### ISSUE TITLE
[Category] Short description

### ISSUE THREAD

**Issue by Aikaz** [sp614x/optifine#5973]
## Description of Issue
 **1) there are no storm visible , 2) blocks in my inventory are black**

## Steps to Reproduce
1. What do you do...
2. ...to find this bug?

## OptiFine Version
 the latest previev 24

## Installation Method
 
<img width="960" alt="2021-07-06" src="https://user-images.githubusercontent.com/86989877/124524447-c4071a00-de03-11eb-8c4d-6f5956b3fd35.png">

**Comment by ZenIsBestWolf** [comment]
This makes no sense.

**Comment by fayer3** [comment]
to be hones it's probably connected to #5891

**Comment by Aikaz** [comment]
Thanks



Отправлено из мобильной Почты Mail.ru


вторник, 6 июля 2021 г., 14:55 +0300 от ***@***.***  ***@***.***>:
