### ISSUE TITLE
[Bug] Crash in Nether

### ISSUE THREAD

**Issue by EdgarsFeic69** [sp614x/optifine#5976]
## Description of Issue

Minecraft crashes when I go to the Nether and I start mining, with Optifine/Optifabric
OpenGL Error [1282] (Invalid Operation)

## Steps to Reproduce
1. Go to the Nether
2. Start mining

## OptiFine Version
OptiFine_1.17_HD_U_G9_pre24_MOD

## Installation Method
Installed as mod with Optifabric, It doesn't happen with Optifine installed alone

## Fabric/Forge Version
Fabric 0.11.6-1.17

## OptiFabric Version
Optifabric 1.11.9

## Other Installed Mods
1. fabric-api-0.36.0+1.17
2. itemscroller-fabric-1.17.0-0.15.0-dev.20210608.211652
3. litematica-fabric-1.17.0-0.0.0-dev.20210608.211719
4. malilib-fabric-1.17.0-0.10.0-dev.22+beta.1
5. MinecraftCapes+Fabric+1.17-v10
6. minihud-fabric-1.17.0-0.19.0-dev.20210608.211830
7. modmenu-2.0.0-beta.7
8. optifabric-1.11.9
9. OptiFine_1.17_HD_U_G9_pre24_MOD
10. tweakeroo-fabric-1.17.0-0.10.0-dev.20210608.211857
11. Xaeros_Minimap_21.12.2_Fabric_1.17

## Log Files/Crash Reports
[hs_err_pid13384.log](https://github.com/sp614x/optifine/files/6771917/hs_err_pid13384.log)

## Prior Testing
- It doesn't happen with Optifine Installed alone or in Minecraft Vanilla, or when I remove Optifine and Optifabric, and I only use the other mods

**Comment by KaiAF** [comment]
Seems like a Nvidia driver is causing the crash. Try updating your drivers, or re-installing them. If that doesn't work, revert it to the last version I guess. This is not really an OptiFine issue or something we can fix.

`Problematic frame: C  [nvoglv64.dll+0xf3f122]`
