### ISSUE TITLE
I launch optifine, but minecraft launches a plain version of the version I was launching with optifine.

### ISSUE THREAD

**Issue by locosoy** [sp614x/optifine#598]
Warns and errors on the output logs:

14:27:20	launcher	main	warn	Couldn't get hash for optifine/OptiFine/1.11.2_HD_U_B7/OptiFine-1.11.2_HD_U_B7.jar from https://libraries.minecraft.net/optifine/OptiFine/1.11.2_HD_U_B7/OptiFine-1.11.2_HD_U_B7.jar.sha1: HTTP 404: Not Found
14:27:20	launcher	main	warn	Have local file C:/Users\Guillaume\AppData\Roaming\.minecraft\libraries\optifine/OptiFine/1.11.2_HD_U_B7/OptiFine-1.11.2_HD_U_B7.jar but don't know what size or hash it should be. Have to assume it's good.
09:27:22	game		error	abr 16, 2017 2:27:21 PM net.minecraft.launchwrapper.LogWrapper log
INFORMACI�N: Loading tweak class name optifine.OptiFineTweaker
abr 16, 2017 2:27:21 PM net.minecraft.launchwrapper.LogWrapper log
INFORMACI�N: Using primary tweak class name optifine.OptiFineTweaker
abr 16, 2017 2:27:21 PM net.minecraft.launchwrapper.LogWrapper log
INFORMACI�N: Calling tweak class optifine.OptiFineTweaker
OptiFineTweaker: acceptOptions
OptiFineTweaker: injectIntoClassLoader
OptiFine ClassTransformer
OptiFine URL: file:/C:/Users/Guillaume/AppData/Roaming/.minecraft/libraries/optifine/OptiFine/1.11.2_HD_U_B7/OptiFine-1.11.2_HD_U_B7.jar
OptiFine ZIP file: C:\Users\Guillaume\AppData\Roaming\.minecraft\libraries\optifine\OptiFine\1.11.2_HD_U_B7\OptiFine-1.11.2_HD_U_B7.jar
OptiFineTweaker: getLaunchArguments
OptiFineTweaker: getLaunchTarget
abr 16, 2017 2:27:21 PM net.minecraft.launchwrapper.LogWrapper log
INFORMACI�N: Launching wrapped minecraft {net.minecraft.client.main.Main}
  <log4j:Event logger="bes" timestamp="1492370842638" level="INFO" thread="Client thread">
    <log4j:Message><![CDATA[Setting user: MrMysticHD05]]></log4j:Message>
  </log4j:Event>
09:27:22	monitor	Process Monitor	error	expected <

Please help me out.

**Comment by sp614x** [comment]
Can you post the game output (error log)?
