### ISSUE TITLE
[Bug] portal and glass rendering issue

### ISSUE THREAD

**Issue by Raeven1327** [sp614x/optifine#5986]
## Description of Issue
Nether portal and stained glass renders on different coordinates than placed.

## Steps to Reproduce
n/a

## OptiFine Version
preview_OptiFine_1.17_HD_U_G9_pre16

## Installation Method
Jar file in mods folder

## Fabric/Forge Version
fabric-loader-0.11.6-1.17

## OptiFabric Version
optifabric-1.11.1

## Other Installed Mods
fabric-api-0.34.9+1.17
FallingTree-1.17-2.12.1

## Log Files/Crash Reports
[latest.log](https://github.com/sp614x/optifine/files/6779473/latest.log)

## F3 Debug Screenshot
![2021-07-07_19 51 03](https://user-images.githubusercontent.com/87092406/124813372-b74a0980-df5c-11eb-918a-7aaa03842134.png)

## Prior Testing

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   - Only OptiFine, OptiFabric, and Fabric - yes
- Does this happen in Vanilla without OptiFine?- no
   - Does the issue still happen with only the remaining mods installed?
      - Forge/Fabric and remaining mods, without OptiFine --> no

## Additional Information
![2021-07-07_19 36 13](https://user-images.githubusercontent.com/87092406/124814219-a5b53180-df5d-11eb-99fc-65b2716e67d5.png)

**Comment by mrktospl** [comment]
you're using a very outdated version on optifine

**Comment by Ari-RERA-43** [comment]
use pre25

**Comment by PyroTheLemon** [comment]
you should download latest version of optifine

**Comment by KaiAF** [comment]
This was fixed
