### ISSUE TITLE
[Bug] Errors with complementary shaders in pre25

### ISSUE THREAD

**Issue by dbrighthd** [sp614x/optifine#5988]
## Description of Issue
Ok so this is going to get a bit complicated, my apologies in advance:
aside from #5960 , I found complementary shaders to be working perfectly with optifine pre24. once pre25 dropped I installed that and I was greeted with a handful of openGL errors and a lot of things malfunctioning and looking incorrect (e.g. brightness)

## Steps to Reproduce
Updated from preview_OptiFine_1.17_HD_U_G9_pre24 to preview_OptiFine_1.17_HD_U_G9_pre25
turned on complementary shaders

## OptiFine Version
preview_OptiFine_1.17_HD_U_G9_pre25

## Installation Method
Heres where it gets a bit complicated, I play mainly with fabric, but this bug shows itself differently with optifabric and standalone.

with optifabric 1.11.9 and 1.11.6, the issue is much more clear with 5 openGL errors, and none of the PBR is working.
![2021-07-07_19 20 03](https://user-images.githubusercontent.com/68525639/124851999-75b75f80-df58-11eb-90c6-39188d809eb4.png)

while standalone only had two errors.
![2021-07-07_19 12 45](https://user-images.githubusercontent.com/68525639/124852055-8d8ee380-df58-11eb-80a4-62436e710242.png)

## Fabric/Forge Version
Fabric version is 0.11.3, api version 0.36.0

## OptiFabric Version
1.11.6 & 1.11.9

## F3 Debug Screenshot
Here is the debug screenshot for optifabric 1.11.9: 
![2021-07-07_19 23 47](https://user-images.githubusercontent.com/68525639/124852252-e6f71280-df58-11eb-9ef8-21ecd39c6211.png)

and here is the screenshot for standalone:
![image](https://user-images.githubusercontent.com/68525639/124852473-363d4300-df59-11eb-8f51-58baf44475f9.png)

Let me know if you need any more information!

**Comment by Whitelisted1** [comment]
If this does not happen with pre24, and only with pre25 I recommend deleting optifine and reinstalling pre24

**Comment by dbrighthd** [comment]
yep, thats what I did, but I want to have this here for documentation just so it's a known thing

**Comment by dbrighthd** [comment]
fixed with pre26, thank you!
