### ISSUE TITLE
Game crashes whenever i try to enter a server. 

### ISSUE THREAD

**Issue by souufle** [sp614x/optifine#5989]
## Description of Issue
<I tried to enter a server, and the game crashed. I tried 3 more times, to no avail.>

## Steps to Reproduce
1. What do you do...
2. ...to find this bug?

**Comment by fayer3** [comment]
please post the latest.log from when it crashes.

**Comment by KaiAF** [comment]
Closing as this provides almost zero detail about the issue. Once you can provide the details just create a new issue
