### ISSUE TITLE
White Points in dark places

### ISSUE THREAD

**Issue by SpiCrafter** [sp614x/optifine#599]
There are white points in dark places, if its daytime. This problem occures with and without shaders.
(Sry for my english :/ )

![2017-04-16_17 25 21](https://cloud.githubusercontent.com/assets/27677937/25086594/17ff2e18-2369-11e7-8e8b-0053d83d61c4.png)

**Comment by sp614x** [comment]
Most probably a vanilla bug: https://bugs.mojang.com/browse/MC-1794
