### ISSUE TITLE
Texture bug on framed block slopes

### ISSUE THREAD

**Issue by LowcaX** [sp614x/optifine#5991]
## Description of Issue
Every block from Framed Block mod with slope or with slope element have a weird texture bug. 

## OptiFine Version
1.16.5 HD U G8

## Installation Method
JAR file in to mods folder

## Fabric/Forge Version
forge 36.1.32

## Other Installed Mods
It is a AlltheMods6 1.6.14 modpack +optifine + Sildurs Vibrant shaders v1.29 High

## F3 Debug Screenshot
![2021-07-08_11 51 43](https://user-images.githubusercontent.com/41991876/124902186-020e6480-dfe3-11eb-9ea3-912fb5b0711b.png)

(https://user-images.githubusercontent.com/41991876/124898412-73e4af00-dfdf-11eb-9323-9ad148bf20f3.png)

Someone had the same bug
![image](https://user-images.githubusercontent.com/41991876/124900035-f9b52a00-dfe0-11eb-872b-0bfff7ad15ed.png)

**Comment by fayer3** [comment]
this is an issue with the mod not supporting optifines extended vertex format. not much optifine can do, needs to be fixed from the mod.
there was a similar issue with an other mod here: #5448, with a proposed solution from sp614x, this might be a similar issue.
