### ISSUE TITLE
[Optifine 1.17 pre25] The texture of axolotls cannot be changed using random entity

### ISSUE THREAD

**Issue by fori00** [sp614x/optifine#5994]
## Description of Issue
The texture of axolotls cannot be changed using random entity.
I tested with cows and pufferfish, the files are ok but cannot be applied to axolots.

## OptiFine Version
1.17

## Installation Method
standalone installer

##  Debug Screenshot
![2021-07-08_17 18 16](https://user-images.githubusercontent.com/87138723/124948106-b2469200-e010-11eb-88cb-fb55dacc57a8.png)

**Comment by dbrighthd** [comment]
thats odd, I got it to work for me

**Comment by fori00** [comment]
For me it doesn't work can you confirm the following elements for me.
Path
assets\minecraft\optifine\random\entity\axolotl
File name
axolotl.properties
