### ISSUE TITLE
Game crashes in 1.17

### ISSUE THREAD

**Issue by AaronTheLeopard** [sp614x/optifine#5995]
I have a problem since few days with minecraft andwhen i play with optifine, i can play like 1 minute then the game crashes :( here is the [log of the error](https://drive.google.com/file/d/1nYzUXvh4zdrL6lVP0FKbFWozAc1YgXIi/view)
If someone could help me to find what is the problem..

**Comment by KaiAF** [comment]
This crash is caused by Nvidia drivers.
`nvapi64.dll+0x2030ce`
To help fix this, try updating your drivers, or if they are up to date, re-install them. Unfortunately I don't think that optifine can fix this issue as it's not caused by us.
