### ISSUE TITLE
(Optifine 1.17 pre25) [Shaders] invalid program: shadow. Shaders broken. Shaders work fine on 1.16.5

### ISSUE THREAD

**Issue by eidhernan** [sp614x/optifine#5996]
Shaders: [Shaderpack.zip](https://github.com/sp614x/optifine/files/6793047/Shaderpack.zip) (extract the zip and place the "Robobo1221Shaders" folder in the shaderpacks folder
Log: [latest.log](https://github.com/sp614x/optifine/files/6793054/latest.log)
Screenshot: [2021-07-09_13 31 48](https://user-images.githubusercontent.com/60356211/125116420-b16a3a80-e0ba-11eb-9a0c-0c3bacec7be0.png)

**Comment by eidhernan** [comment]
[spec](https://user-images.githubusercontent.com/60356211/125117651-897bd680-e0bc-11eb-9e70-cd9db910f786.PNG)

This might be useful

**Comment by Whitelisted1** [comment]
I'm not experienced with shaders, like if this happens with every shader pack, but I think that it is outdated since you continue to get this error:

warning C7555: 'varying' is deprecated, use 'in/out' instead

**Comment by eidhernan** [comment]
I just used Continuum Shaders, same exact issue.
https://continuum.graphics/downloads

**Comment by eidhernan** [comment]
It seems to be an issue for all "realistic" shader packs that generate the world as a section of a procedural globe to make lighting more realistic. For all the shaders affected, if you teleport 3 million blocks out, you will see the world as a globe
![2021-07-09_14 11 03](https://user-images.githubusercontent.com/60356211/125119778-90581880-e0bf-11eb-9c5f-2dcffe0df867.png)

**Comment by eidhernan** [comment]
> I'm not experienced with shaders, like if this happens with every shader pack, but I think that it is outdated since you continue to get this error:
> 
> warning C7555: 'varying' is deprecated, use 'in/out' instead

I am going to try something out: I will replace varying with in/out and see if it fixes anything in the shader files.

**Comment by eidhernan** [comment]
That did not work and instead broke the entire shader pack, making the entire screen white. So the varying is not the issue

**Comment by eidhernan** [comment]
OKAY GUYS! I FIXED IT.

Go into the shadow.vsh file and replace all "varying" with "out"

GO into shadow.fsh file and replace "varying" with "in"

**Comment by eidhernan** [comment]
Fixed Shaderpack (extract and send the Robobo1221Shaders folder to the shaderpacks folder): [Shaderpack.zip](https://github.com/sp614x/optifine/files/6793318/Shaderpack.zip)
