### ISSUE TITLE
when I try enter to my world with shaders the game crashes and says code 0, I have a Mac m1 8gb and always that I try always the same happens 

### ISSUE THREAD

**Issue by Samu123D** [sp614x/optifine#5998]
## Steps to Reproduce
1. What do you do...
2. ...to find this bug?

## I INSTALLED JAVA  and then install the optifine version, finally I just go to Minecraft and I try to enter 
 I use the standalone installer I guess

**Comment by Whitelisted1** [comment]
Mac's are apparently incompatible with shaders as of now (As said so in #5900)

**Comment by Ari-RERA-43** [comment]
Close this issue because it's a dupe. The shader & Mac incompatability is likely not permanent.

**Comment by omerien** [comment]
`$ sudo close-issue`
