### ISSUE TITLE
[Category] Short description

### ISSUE THREAD

**Issue by Infernoyt1** [sp614x/optifine#5999]
## Description of Issue
 Crashes with Error Code 0 Whenever I Use Any Shaderpack

## Steps to Reproduce
1. Launch Any Shaderpack

## OptiFine Version
--> 1.17.1 HD U G9 pre26

## Installation Method
 Stand-alone Installer

**Comment by Whitelisted1** [comment]
Are you using mac?

**Comment by Infernoyt1** [comment]
> Are you using mac?

Yes. 2017 Macbook Pro :)

**Comment by Ari-RERA-43** [comment]
Shaders do not work on Mac right now.

**Comment by Whitelisted1** [comment]
^

says so in #5900

**Comment by Infernoyt1** [comment]
> Shaders do not work on Mac right now.

Ah, didn’t know that. Thanks for letting me know! :)

**Comment by Ari-RERA-43** [comment]
#5900. It's not juts M1 Macs
