### ISSUE TITLE
Thaumcraft 5 glitch

### ISSUE THREAD

**Issue by Majestyc2k1** [sp614x/optifine#6]
When I get the Un-natural Hunger warp debuff from Thaumcraft 5 (1.8.9), the screen goes black. The game is still running, and I was able to close the game. When I removed Optifine, the view was normal. This happened on both H1 and H2 (1.8.9).

**Comment by sp614x** [comment]
Does "Fast Render -> OFF" help?

**Comment by Majestyc2k1** [comment]
I'll try that. The debuff is random so I will report back when it happens again.

**Comment by Majestyc2k1** [comment]
That worked, thanks.
