### ISSUE TITLE
Custom Items textures not working

### ISSUE THREAD

**Issue by Lemente** [sp614x/optifine#600]
So, I'm using a ressource pack with custom items which is working on Minecraft 1.10 with Optifine HD U C3, but not version HD U D7. And in minecraft 1.11.2 it is not working in version HD U B5 and B7 (I havn't verified any other version).

I guess it has somehow been deactivated/broken. Or maybe the mothod for custom items changed between these versions?

ps: I did set Custom Items: ON (another problem: whern I try to switch from _off_ to _on_ ingame with my custom ressource pack, it freeze the game. It doesn't without any custom ressource pack.)
pps: I tried with and without Forge.

Anyone have the same issue?

**Comment by Lemente** [comment]
After some tests, it seems that only items with a colored name are not working.
Custom textures based on:
- custom name (without color)
- enchantmentIDs
- damage
- stackSize
are working.

**Comment by Lemente** [comment]
After much more tests, I found the problem !

I'm not sure how to properly explain it though ...


My custom textures were in a subfolder with their .properties. Their name was the same, so I didn't needed the "texture=" line.
It is working after:

- moving all files in the "cit" folder

OR

- adding the path to the texture (just "texture=name" actually, since it is in the same folder)


So I guess this is still a bug, I let you decide to close this or not.

**Comment by sp614x** [comment]
Since Minecraft 1.11 the resource packs have to use lowercase letters only.
This is a vanilla requirement: http://minecraft.gamepedia.com/16w32a#Changes
