### ISSUE TITLE
[Crash] When I open and launch minecraft, then use a shader, I joined a multiplayer server, I crashed and got Exit Code 0.

### ISSUE THREAD

**Issue by MEEEE7** [sp614x/optifine#6006]
## Description of Issue
I basically used chocapic lite and BSL, I tried both but they did not work when I joined multiplayer, I just crashed instead.

## Steps to Reproduce
1. Launch Minecraft.
2. get a shader and use it.
3. go to multiplayer, join any server. I joined minehut.
4. I crashed.

## OptiFine Version
1.17, pre release 26

## Installation Method
I already downloaded it before by following the JAR's instructions.

## Other Installed Mods
I used BSL shader and chocapic lite seperatly.

## Prior Testing
- Does this happen in Vanilla without OptiFine?: No, I used shaders, so It's not possible to use shaders without optifine.

## Additional Information
I never experienced a crash before not even once SO I'm confused.

**Comment by dgattey** [comment]
Are you using macOS? If so, then this is your problem - shaders don't work on macOS with version 1.17 yet #5900

**Comment by Jiingy** [comment]
Closing for lack of response from original issue poster.
