### ISSUE TITLE
Game doesnt launch

### ISSUE THREAD

**Issue by Spartac69** [sp614x/optifine#6008]
My optifine 1.17 does not work it gives this error but when i launch vanilla 1.17 it works perfectly fine
![image](https://user-images.githubusercontent.com/87254357/125182607-cb3e8580-e252-11eb-943d-048f651292fd.png)

Launch the game

## OptiFine Version
1.17-Optifine_HD_U_G9_pre25

## Installation Method
I clicked on the .jar file to install

## Log Files/Crash Reports
]
[latest.log](https://github.com/sp614x/optifine/files/6796339/latest.log)

**Comment by Ari-RERA-43** [comment]
This is a dupelicate of #5739. Close this issue. Updating your drivers may solve it but that doesn't always work.

**Comment by KaiAF** [comment]
Already addressed here: #5739
