### ISSUE TITLE
Crash during Launch

### ISSUE THREAD

**Issue by SpyEnnX** [sp614x/optifine#601]
Always like optifine but just made a new computer and when i install optifine on 1.10.2 modpack then start the game it just crash. Here a link of the latest crash [https://pastebin.com/zJRs9Z2J](url)  Hopefully you could help me out. Using version OptiFine 1.10.2 HD U D7

**Comment by Lemente** [comment]
I can't help you, but I think you should add some information. (modpack? OS? ...)

**Comment by mindforger** [comment]
The link is broken

**Comment by SpyEnnX** [comment]
[crash-2017-04-17_20.26.20-client.txt](https://github.com/sp614x/optifine/files/931095/crash-2017-04-17_20.26.20-client.txt)

Using Windows 10 as my os and the modpack is FoolCraft

**Comment by sp614x** [comment]
This is a problem with MalisisDoors. 
There is a newer version of MalisisCore with a bugfix.
