### ISSUE TITLE
Entities turning black when i look near them

### ISSUE THREAD

**Issue by LordTsesar** [sp614x/optifine#6010]
## Description of Issue
when i look at entities they sometimes all turn black at random points

## Steps to Reproduce
you just go on and look at some entities for a while

## OptiFine Version
1.17/1.17.1 all

## Installation Method
standalone installer

<!-- **If OptiFine is installed as
## Log Files/Crash Reports
no crashes>
![2021-07-11_18 32 28](https://user-images.githubusercontent.com/85031577/125204738-ac51ea80-e276-11eb-91bd-8827913738d1.png)

- Does this happen in Vanilla without OptiFine?
-no

**Comment by fayer3** [comment]
Post a F3 Screenshot of the issue

**Comment by KaiAF** [comment]
Addressed here: #5891. Plus no information provided
