### ISSUE TITLE
[Multiplayer] Render Distance Limited Online Since 1.17

### ISSUE THREAD

**Issue by LoyalDeserter** [sp614x/optifine#6019]
## Description of Issue
The maximum render distance for online play is now very short, same as vanilla regardless of the render distance setting.  In previous versions, the immediate render distance when you logged in would still be the same as vanilla, but if you moved around, previously-loaded chunks would stay loaded even if they were further away than that vanilla render distance.  So, if you travelled in a straight line for some time, you could look back and see a long mass of land that was as wide as vanilla render distance extending far off into the horizon.  Now, online render distance in optifine is identical to vanilla online render distance.  I've tested this in multiple servers and multiple computers.

## Steps to Reproduce
1.  Log into a server
2. .Move in a straight line for a few hundred blocks and look back towards where you came.

## OptiFine Version
1.17 pre26

## Installation Method
I used the standalone installer.

## Other Installed Mods
No other mods.

**Comment by velnias75** [comment]
Same as https://github.com/sp614x/optifine/issues/5811?

**Comment by LoyalDeserter** [comment]
> Same as #5811?

Yep, same issue.  Didn't see that, sorry.

**Comment by KaiAF** [comment]
Already addressed: #5811
