### ISSUE TITLE
[1.17] OptiFine crashes the game on Linux with Intel Integrated graphics card used with error GLFW 65543

### ISSUE THREAD

**Issue by whitebear60** [sp614x/optifine#6020]
## Description of Issue
When trying to start the game with OptiFine installed, it crashes with error GLFW 655453: Failed to create context: GLXBadFBConfig

Vanilla Minecraft 1.17.1 starts and works fine

Tested on MultiMC, Mojang Minecraft launcher, with Fabric and with pure Minecraft, result is the same in all dour cases.

GPU: Intel HD Graphics 3000

Under macOS on the same computer everything works fine

## Steps to Reproduce
1. Install Minecraft launcher
2. Run 1.17.1 for the first time
3. Install OptiFine
4. Run the game with OptiFine
5. See error

## OptiFine Version
HD U G9 pre27

## Installation Method
Used the included standalone installer or put the downloaded JAR file from optifine.net to mods folder together with OptiFabric

## Fabric/Forge Version
Fabric 1.17.1-0.11.6

## OptiFabric Version
1.11.18

## Log Files/Crash Reports

[latest.log](https://github.com/sp614x/optifine/files/6809536/latest.log)

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine? **No**

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   - Only OptiFine, OptiFabric, and Fabric **Yes**
- Does this happen without any mods at all?
   - Only Forge/Fabric by itself. **No**
- Does this happen in OptiFine standalone? **Yes**
- Does this happen in Vanilla without OptiFine? **No**

## Additional Information
Tested on 
![Screenshot from 2021-07-13 17-44-22-1](https://user-images.githubusercontent.com/42472132/125472661-201361e3-54b3-4154-b99a-be22c2b9df9f.png)

**Comment by fayer3** [comment]
already reported here: #5739

**Comment by Ari-RERA-43** [comment]
You should close this because it's a dupe, as @fayer3 said

**Comment by whitebear60** [comment]
Closing as duplicate of #5739
