### ISSUE TITLE
[CTM] connectBlocks=soul_sand & mud don't work

### ISSUE THREAD

**Issue by Polydot** [sp614x/optifine#6021]
when using overlay ctm on soulsand it doesn't do anything.
Interestingly you CAN use another block to overlay onto soulsand.

Steps to Reproduce:
make an overlay ctm with connectBlocks(or Tiles)=soul_sand

Version:
OptiFine 1.17.1_HD_U_G9_pre27
Standalone installer
![Untitled](https://user-images.githubusercontent.com/5259390/125474123-6509d62b-d210-40a7-b39e-997aafde17fd.png)

**Comment by Polydot** [comment]
still in OptiFine 1.20.1_HD_U_I6_pre3
Also affects Mud

**Comment by JimStoneCraft** [comment]
[Soul Sand TEST.zip](https://github.com/sp614x/optifine/files/14622892/Soul.Sand.TEST.zip)
![Soul Sand 1](https://github.com/sp614x/optifine/assets/42512910/05825569-931d-42d8-ac2d-332a932ef72a)
![Soul Sand 2](https://github.com/sp614x/optifine/assets/42512910/4224afb7-38b9-47c4-9c00-63f5ea98947d)
Working on resource pack OptiFine overlays and I found that Soul Sand doesn't work.

I've made a small test pack with Soul Soil and Sand Sand to show that Soul Sand doesn't work so it's still an issue with 1.20.4 OptiFine HD U I7 pre7.

**Comment by JimStoneCraft** [comment]
This is still an issue in OptiFine_1.21.1_HD_U_J1_pre14.

**Comment by Emfire12345** [comment]
Thats because they are not considered "full blocks" by the game, this would mean general overlay support for any non-full blocks, so currently it works as intended

**Comment by Polydot** [comment]
Overlay is supported on path blocks  though, so I don't think this statement holds up.

**Comment by Emfire12345** [comment]
> Overlay is supported on path blocks though, so I don't think this statement holds up.

You cant overlay from a path block to another block, because it isnt a full block, you can however overlay a full block onto a path block.
I tested the path block with my own pack and it didnt work, do you have a screenshot of it working?
