### ISSUE TITLE
[Settings] No Tooltips for graphic setting.

### ISSUE THREAD

**Issue by JustTimmNL** [sp614x/optifine#6023]
## Description of Issue
Minecraft "Graphics" setting tooltips don't show up with Optifine.

## Steps to Reproduce
1. Go to options -> video settings. There you will find the graphics option in the top left corner.

## OptiFine Version
1.17.1 G9_pre26

## Installation Method
i installed it with the .jar file. Not in a mods folder.

## Fabric/Forge Version
No Fabric/Forge.

## OptiFabric Version
No OptiFabric.

## Other Installed Mods
No other mods.

## Log Files/Crash Reports
No logs

## F3 Debug Screenshot
XXXX

## Prior Testing
This is only when I have Optifine installed.

## Additional Information
XXXX

Screenshots:

With optifine: https://i.imgur.com/7W5YP48.png

Without optifine (Vanilla): https://i.imgur.com/Jzfk7Rm.png

**Comment by Whitelisted1** [comment]
The tooltips work with every submenu, so either the tooltips for the main settings weren't implemented or this is a bug. I can confirm this functionality as I tested it myself

**Comment by JustTimmNL** [comment]
> The tooltips work with every submenu, so either the tooltips for the main settings weren't implemented or this is a bug. I can confirm this functionality as I tested it myself

Dude check screenshots. I don’t post this without testing it. I didn’t see the tooltips for that setting.

**Comment by Whitelisted1** [comment]
Sorry if I was unclear, but I am confirming what you said, and I was saying that this is a problem for all settings in the "main video settings". All I was saying above is that the tool tips work for every submenu, such as the "performance" category it works for the settings in there

**Comment by JustTimmNL** [comment]
> Sorry if I was unclear, but I am confirming what you said, and I was saying that this is a problem for all settings in the "main video settings". All I was saying above is that the tool tips work for every submenu, such as the "performance" category it works for the settings in there

Oh I thought that you meant that it wasn't true.

**Comment by Whitelisted1** [comment]
I can confirm that this IS a problem with 1.17 as it works with 1.16
![Tooltips](https://user-images.githubusercontent.com/77711834/125957983-50f5e71c-18ef-4bf1-babb-8b6e6a26ce2e.png)

**Comment by KaiAF** [comment]
Fixed in 1.18 full release.
