### ISSUE TITLE
inventory blocks turn black

### ISSUE THREAD

**Issue by BumbleBelle947** [sp614x/optifine#6024]
every block in my inventory turns black until i place it. This issue is fixed as soon as i disable shaders, but changes back as soon as i enable them again. I've tried using different shaders, starting a new world, rebooting everything, deleting and reinstalling optifine, but nothing has worked.
![shader_bug](https://user-images.githubusercontent.com/87393220/125518118-fb0ecf92-6cdd-4799-b4bb-b5d14a8a9ebb.png)

**Comment by Ari-RERA-43** [comment]
This is a duplicate of #5891. Close this isse.

**Comment by Ari-RERA-43** [comment]
This issue has been fixed in pre28
