### ISSUE TITLE
[Bug] Shulker Boxes and Chests render as a solid color in inventory with shaders

### ISSUE THREAD

**Issue by InQuognito** [sp614x/optifine#6025]
## Description of Issue
When using Optifine pre-28 with shaders (BSL particularly) Shulker boxes turn a solid purple color in the inventory, and chests turn a solid maroon color in the inventory. No problems with any other form of rendering these items, only inside the inventory and only with shaders on.

## Steps to Reproduce
1. Launch OptiFine
2. Enable (BSL?) Shader
3. Voila?

## OptiFine Version
1.17.1, pre-28 (latest at time of posting)

## Installation Method
Dropped OptiFine into mods folder

## Fabric/Forge Version
Fabric 1.17.1, 0.11.6

## OptiFabric Version
v1.11.18

## Other Installed Mods
AppleSkin
Auth Me
BetterF3
Enchantment Descriptions
I Know What I'm Doing
Inventory HUD+
Litematica
MaLiLib
Mod Menu
OptiFabric
Roughly Enough Items
Shulker Box Tooltip
ToroHealth Damage Indicators
Xaero's Minimap
Xaero's World Map

## F3 Debug Screenshot
![2021-07-14_00 43 57](https://user-images.githubusercontent.com/44120299/125569324-99b7a76d-f736-46a0-8381-bbf3eb6a1605.png)

**Comment by LuckyOwl1105** [comment]
I'm also having this problem! I thought I was just seeing things.. thanks for sharing this

**Comment by LmaoBLT** [comment]
I'm experiencing the same issue, however its using Sildur's Enhanced Default.

**Comment by fayer3** [comment]
this should be fixed with pre29

**Comment by InQuognito** [comment]
@fayer3 thats what the change log says. haven't been able to update, waiting on optifine if

**Comment by KaiAF** [comment]
Was fixed in latest preview.
