### ISSUE TITLE
I can’t install optifine

### ISSUE THREAD

**Issue by Lloydclaw9** [sp614x/optifine#6027]
I can’t install optifine I can open the actual installer but whenever I press install it says “cannot find 1.17 you must download and start minecraft 1.17 once in the official launcher”. This wouldn’t be a problem if I hadn’t already launched minecraft already and played but it still says that, I tried creating a new 1.17 instance, deleting my .minecraft folder, even uninstalling minecraft and re-downloading but nothing. Is there anyway to fix this I really want to use optifine

**Comment by Ari-RERA-43** [comment]
Were you using the vanilla launcher to run 1.17?

**Comment by Lloydclaw9** [comment]
Yes I was using the official minecraft launcher

**Comment by Ari-RERA-43** [comment]
Are you sure you were launching 1.17 and not 1.17.1?

**Comment by Lloydclaw9** [comment]
I was going to say does that actually matter but I am in utter disbelief that it worked thank you

**Comment by Ari-RERA-43** [comment]
You should close this issue
