### ISSUE TITLE
OptiFine 1.10.2 + Just Enough Dimensions Mod

### ISSUE THREAD

**Issue by Aschy2** [sp614x/optifine#603]
My problem is that 50% of the time my game crashes when entering a custom dimension. The Author of that mod had pointed out that it is something with optifine, and I'm just wondering if you can help.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CXLibraryCore (CustomStuff3-1.10.2-0.11.7 .jar)
  LoadingPlugin (Quark-r1.1-70.jar)
  TANLoadingPlugin (ToughAsNails-1.9.4-1.1.1.jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 4/20/17 12:58 PM
Description: Unexpected error

java.lang.ArrayIndexOutOfBoundsException: 11
	at CustomColors.getWorldSkyColor(CustomColors.java:1586)
	at net.minecraft.client.renderer.EntityRenderer.func_78466_h(EntityRenderer.java:2224)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1591)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1566)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1345)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at CustomColors.getWorldSkyColor(CustomColors.java:1586)
	at net.minecraft.client.renderer.EntityRenderer.func_78466_h(EntityRenderer.java:2224)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1591)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1566)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Aschy'/510, l='MpServer', x=-73.50, y=47.00, z=-165.50]]
	Chunk stats: MultiplayerChunkCache: 0, 0
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 370657386 game time, 457336 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityPlayerSP['Aschy'/510, l='MpServer', x=-73.50, y=47.00, z=-165.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:524)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:400)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 580441024 bytes (553 MB) / 1250676736 bytes (1192 MB) up to 4281597952 bytes (4083 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 9, tallocated: 61
	FML: MCP 9.32 Powered by Forge 12.18.3.2254 Optifine OptiFine_1.10.2_HD_U_D7 41 mods loaded, 41 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAAAAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAAAAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2254.jar) 
	UCHIJAAAAAAAAA	Forge{12.18.3.2254} [Minecraft Forge] (forge-1.10.2-12.18.3.2254.jar) 
	UCHIJAAAAAAAAA	JEI{3.14.7.417} [Just Enough Items] (jei_1.10.2-3.14.7.417.jar) 
	UCHIJAAAAAAAAA	CustomStuff3{0.11.7} [Custom Stuff 3] (CustomStuff3-1.10.2-0.11.7 .jar) 
	UCHIJAAAAAAAAA	1{1.0.0} [RoughCraft Pack] (1) 
	UCHIJAAAAAAAAA	Quark{r1.1-70} [Quark] (Quark-r1.1-70.jar) 
	UCHIJAAAAAAAAA	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar) 
	UCHIJAAAAAAAAA	babymobs{1.5.4} [Baby Mobs] (BabyMobs-1.10.2-1.5.4.jar) 
	UCHIJAAAAAAAAA	XaeroBetterPvP{1.11.4} [Better PVP Mod] (BetterPvP_1.11.4_Forge_1.10.2.jar) 
	UCHIJAAAAAAAAA	betterquesting{2.3.217} [Better Questing] (BetterQuesting-2.3.217.jar) 
	UCHIJAAAAAAAAA	Bullseye{1.0.3} [Bullseye] (Bullseye-1.9.4-1.0.3.jar) 
	UCHIJAAAAAAAAA	crafttweakerjei{1.0.1} [CraftTweaker JEI Support] (CraftTweaker-1.10.2-3.0.20.jar) 
	UCHIJAAAAAAAAA	MineTweaker3{3.0.20} [MineTweaker 3] (CraftTweaker-1.10.2-3.0.20.jar) 
	UCHIJAAAAAAAAA	ctgui{1.0.0} [CT-GUI] (CraftTweaker-1.10.2-3.0.20.jar) 
	UCHIJAAAAAAAAA	customnpcs{1.10.2} [CustomNPCs] (CustomNPCs_1.10.2(17mar17).jar) 
	UCHIJAAAAAAAAA	excore{1.6.2} [EXCore] (Excore-1.6.2-1.10.2.jar) 
	UCHIJAAAAAAAAA	llor{1.1.0-mc[1.9-1.10.2]} [Light Level Overlay Reloaded] (Light-Level-Overlay-Reloaded-Mod-1.10.2.jar) 
	UCHIJAAAAAAAAA	FEI{1.0.17.2} [Forever Enough Items] (ForeverEnoughItems-1.0.17.2-1.10.2.jar) 
	UCHIJAAAAAAAAA	ftbl{0.0.0} [FTBLib] (FTBLib-1.10.2-3.5.3.jar) 
	UCHIJAAAAAAAAA	ftbu{0.0.0} [FTBUtilities] (FTBUtilities-1.10.2-3.5.1.jar) 
	UCHIJAAAAAAAAA	gemcraft{1.2.5} [Gem Craft] (gemcraft-1.10.2-1.2.5.jar) 
	UCHIJAAAAAAAAA	gravestone{1.5.12} [Gravestone] (GraveStone Mod 1.5.12.jar) 
	UCHIJAAAAAAAAA	justenoughdimensions{1.3.6} [Just Enough Dimensions] (justenoughdimensions-1.10.2-1.3.6.jar) 
	UCHIJAAAAAAAAA	levelup{${version}} [Level Up!] (LevelUp!-0.12.9-1.10.2.jar) 
	UCHIJAAAAAAAAA	mtrm{1.2.1.20} [MineTweakerRecipeMaker] (MineTweakerRecipeMaker-1.10.2-1.2.1.20.jar) 
	UCHIJAAAAAAAAA	morematerials{1.10.2-1.9.20160723.0} [More Materials] (morematerials-1.10.2-1.9.20160723.0.jar) 
	UCHIJAAAAAAAAA	Neat{GRADLE:VERSION-GRADLE:BUILD} [Neat] (Neat 1.3-10.jar) 
	UCHIJAAAAAAAAA	bq_npc_integration{2.3.19} [NPC Integration] (NPCIntegration-2.3.19.jar) 
	UCHIJAAAAAAAAA	recallstones{0.6.3} [Recall Stones] (RecallStones-1.10.2-0.6.3.jar) 
	UCHIJAAAAAAAAA	bq_rf{2.3.24} [RF Expansion] (RFExpansion-2.3.24.jar) 
	UCHIJAAAAAAAAA	roughMobs{1.0} [Rough Mobs] (roughMobs1.0.9-1.10.2.jar) 
	UCHIJAAAAAAAAA	RTG{4.1.2.4} [Realistic Terrain Generation] (RTG-1.10.2-4.1.2.4.jar) 
	UCHIJAAAAAAAAA	spartanshields{1.1b} [Spartan Shields] (SpartanShields-1.10.2-1.1b.jar) 
	UCHIJAAAAAAAAA	bq_standard{2.3.124} [Standard Expansion] (StandardExpansion-2.3.124.jar) 
	UCHIJAAAAAAAAA	beneath{1.2.0} [The Beneath] (The Beneath-1.10.2-1.2.0.jar) 
	UCHIJAAAAAAAAA	ToughAsNails{@MOD_VERSION@} [Tough As Nails] (ToughAsNails-1.9.4-1.1.1.jar) 
	UCHIJAAAAAAAAA	treechopper{1.1.1a} [Tree Chopper] (TreeChopper-1.10.2-1.1.1a.jar) 
	UCHIJAAAAAAAAA	worldedit{6.1.4} [WorldEdit] (worldedit-forge-mc1.10.2-6.1.4-dist.jar) 
	UCHIJAAAAAAAAA	examplemod{1.0} [examplemod] (WTF-Expedition_1.10.2_v1.5Beta1.jar) 
	UCHIJAAAAAAAAA	wtfcore{1.10.2_v1.5} [WTFs-Expedition] (WTF-Expedition_1.10.2_v1.5Beta1.jar) 
	Loaded coremods (and transformers): 
CXLibraryCore (CustomStuff3-1.10.2-0.11.7 .jar)
  cubex2.cs3.asm.CoreModTransformer
LoadingPlugin (Quark-r1.1-70.jar)
  vazkii.quark.base.asm.ClassTransformer
TANLoadingPlugin (ToughAsNails-1.9.4-1.1.1.jar)
  toughasnails.asm.transformer.BlockCropsTransformer
  toughasnails.asm.transformer.EntityRendererTransformer
  toughasnails.asm.transformer.WorldTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 376.53' Renderer: 'GeForce GTX 760/PCIe/SSE2'
	Launched Version: 1.10.2-forge1.10.2-12.18.3.2254
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 760/PCIe/SSE2 GL version 4.5.0 NVIDIA 376.53, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Norzeteus Space 1.11 [64x](Optifine_Forge).zip (incompatible)
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x AMD FX(tm)-8320 Eight-Core Processor 
	OptiFine Version: OptiFine_1.10.2_HD_U_D7
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 376.53
	OpenGlRenderer: GeForce GTX 760/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by sp614x** [comment]
The line which crashes is `switch(dimensionType)`, which is very strange. Looks like someone is extending the DimensionType enum at run time.
This seems to be a known limitation of Forge when extending enums: https://github.com/MinecraftForge/MinecraftForge/issues/2787
To fix it the enum should be extended as early as possible, for example in a static block in the main mod file.
