### ISSUE TITLE
Entities turn black

### ISSUE THREAD

**Issue by PoompkinPlayer** [sp614x/optifine#6033]
## Description of Issue
 entities and other things turn black when i look at them

## Steps to Reproduce
1. What do you do...
2. ...to find this bug?

## OptiFine Version
 OptiFine HD U G9 pre29 1.17.1

## Installation Method
 Standalone

## F3 Debug Screenshot
 ![image](https://user-images.githubusercontent.com/87291231/125710943-1411142c-fe3e-4404-9a32-e7aeb635c6c7.png)

## Prior Testing
 No doesnt happen in vanilla

**Comment by Whitelisted1** [comment]
#6016 and #6010 have similar effects, so look there for answers

**Comment by KaiAF** [comment]
Can you provide more information? Like what the issue actually looks like?
