### ISSUE TITLE
[BUG] When holding a torch in hand with the dynamic lights on, the light the torches reproduce pass through tinted glass (glass of the new update that isnt supposed to let light through) this is only when placing the torch in hand, when placed the light doesnt pass through.

### ISSUE THREAD

**Issue by Orsaien** [sp614x/optifine#6034]
## Steps to Reproduce
Hold a torch in your hand in front of a dark space that is visible by tinted glass.    

## OptiFine Version
1.17 OptiFine HD U G9 pre26

## Installation Method
I clicked on mirror and then on download after that the download started, then I opened it and gave the permissions from the computer and then a window opened and I clicked on install

## F3 Debug Screenshot

![2021-07-14_21 13 59](https://user-images.githubusercontent.com/87456823/125717393-9b55ede2-01e7-4731-81f0-dd7961f908b3.png)

**Comment by Whitelisted1** [comment]
This shouldn't affect spawn rates, since dynamic lights doesn't affect the actual light level, this is likely an oversight, since nobody else has reported it yet

**Comment by KaiAF** [comment]
Already addressed here: #5783. And yeah, this would not affect spawn rates, or anything. It's just client side.
