### ISSUE TITLE
[Screenshots] Screenshots corrupted/ fully black

### ISSUE THREAD

**Issue by GaNgOuTrAge** [sp614x/optifine#6035]
optifine 1.17 G9 pre 21

Installed by running the optifine jar file. No other mods loaded but a texture pack (faithful)

When I take a screenshot with F2, the image says the normal on screen in chat (something like "image saved as 2021-xxxx")  but upon opening the screenshots folder, every screenshot is black. When switching to vanilla, screenshots work perfectly. This is a pretty big issue nobody is adressing!

Attatched is an example file. Thanks for the consideration, hope this gets fixed!

*****EDIT****** Just dowloaded the most recent optifine and this IS still an issue via downloading optifine the normal way by running the file as a java file to install.

![2021-06-16_20 42 54](https://user-images.githubusercontent.com/87464193/125737775-e81364f9-e083-4910-b268-9cf2c64ff990.png)

**Comment by fayer3** [comment]
it's a bug with Antialiasing/Anisotropic Filtering
already reported here: #5770

**Comment by KaiAF** [comment]
duplicate
