### ISSUE TITLE
Weird item frame glitching

### ISSUE THREAD

**Issue by AndPhil97** [sp614x/optifine#6038]
Whenever I have any amount of item frames (in the vid I used 25, but it does this with only 1 as well) all nearby entities glitch in and out. I'm not sure if this is an optifine or a Minecraft thing, but I have gotten this problem in the past on modpacks with optifine on it.

https://user-images.githubusercontent.com/78433813/125868063-cb0e5998-7ed9-47b5-9905-cd363190654a.mp4

**Comment by Whitelisted1** [comment]
This is likely similar to #6033, since item frames are considered entities

**Comment by Whitelisted1** [comment]
Sorry wrong issue - correct one would be #6013

**Comment by KaiAF** [comment]
Addressed here: #6013
