### ISSUE TITLE
[Bug] Turning on Shaders causes a colored box around dropped items

### ISSUE THREAD

**Issue by Shocklord** [sp614x/optifine#6040]
## Description of Issue
When I have shaders on (I tried it with 2 different shaderpacks) Dropped 2D items have a box around them corresponding to the items color. This goes away if Hitboxes are turned on with F3+B. 

## Steps to Reproduce
1. have Shaders
2. Drop a 2D item on the ground

## OptiFine Version
Optifine_1.16.5_HD_U_G8 

## Installation Method
Jar File Dropped in mods folder

## Fabric/Forge Version
forge 1.16.5-36.1.23 

## Other Installed Mods
https://ftb.fandom.com/wiki/Direwolf20_1.16 

![2021-07-16_03 06 58](https://user-images.githubusercontent.com/26064060/125900307-015eccee-50a0-4573-a26c-7b81a48de6db.png)

**Comment by Shocklord** [comment]
It's probably a mod conflict with Optifine. So I'll just deal with it, as I'm using a modpack the process of trying to isolate the conflict would be too much for me

**Comment by KaiAF** [comment]
Unable to reproduce this, most likely is caused by some sort of mod incompatibility.
