### ISSUE TITLE
[Shaders] Game crashes when I try to load shaders (M1 Mac)

### ISSUE THREAD

**Issue by iGhostii** [sp614x/optifine#6041]
## Description of Issue
I'm on an M1 Mac. When I try to use shaders on the latest version of Optifine 1.17, my game crashes without any error.

## Steps to Reproduce
1. On an M1 Mac and 1.17 Optifine, open the shaders menu.
2. Click one of the shaders you want to use.
3. Watch as your game crashes.

## OptiFine Version
HD U G9 pre24

## Installation Method
I used the installer and installed Optifine normally.

## Log Files/Crash Reports
There wasn't a crash report.

## Prior Testing
- Does this happen in Vanilla without OptiFine?
It cannot happen in Vanilla since shaders can't be used without Optifine.

## Additional Information
Remember, this bug happened on an M1 Mac and my friend with a Windows PC did not have this issue whatsoever.

**Comment by Ari-RERA-43** [comment]
This is a duplicate on #5900. Close this issue.

**Comment by iGhostii** [comment]
Actually, to argue that statement, it is not a duplicate since I am not on MacOS Monterey. I am in fact on MacOS Big Sur and being on the newest beta may cause issues in games like Minecraft, since the version isn't fully released to the public yet.
