### ISSUE TITLE
[Bug] Entity Turned Black in Inventory / Menu Only

### ISSUE THREAD

**Issue by KendryKen** [sp614x/optifine#6042]
## Description of Issue
I have this weird issue regarding the item in menu and inventory only. The item turned pitch black, but there's no issue when already dropped/put in the world

![2021-07-16_17 47 33](https://user-images.githubusercontent.com/47950516/125936851-09147d41-a009-46c8-9842-f58c841adf46.png)

![2021-07-16_17 47 35](https://user-images.githubusercontent.com/47950516/125937872-39fbd653-feec-44b8-961e-053c2dd47ff4.png)

## Steps to Reproduce
1. Intalled the game with both Optifine 1.17.1 Pre 26 (T-launcher built in) or Pre 29 (latest) have this issue
2. Load the shaderpacks

## OptiFine Version
Optifine 1.17.1 Pre 26 and Pre 29

## Installation Method
 
Both, still have the issue

## Other Installed Mods
Only Optifine, and Shaders :
- Complementary Shaders
- SEUS PTGI HRR Test 2 & 2.1
- SEUS PTGI E1.16.4
- SEUS Renewed v1.0.1
- Sildurs Vibrant Shaders v1.29

## Log Files/Crash Reports
None

## F3 Debug Screenshot
![2021-07-16_17 55 40](https://user-images.githubusercontent.com/47950516/125937551-eeb394da-74ee-45e7-8ec5-57a39c7bf742.png)

## Prior Testing
<!-- If you've installed standalone:
- Does this happen in Vanilla without OptiFine? No

## Additional Information
My PC
Intel Core i5 - 11400
16 GB RAM
AMD Radeon RX Vega 64 (driver AMD 21.6.2)

**Comment by KaiAF** [comment]
Already addressed here: #5891
