### ISSUE TITLE
[Bug] Render distance is capped by server

### ISSUE THREAD

**Issue by basedAF** [sp614x/optifine#6043]
## Description of Issue
If I set my client view distance to 32 and the server has view distance of 6, moving away will unload the chunks forcefully like in vanilla, this is extremely ugly and disorientating, the persistent chunks were one of optifine's best features, why was this removed in 1.17?

## Steps to Reproduce
Go on server 
use client distance higher than server view distance
move around, render distance is forced to server's

## OptiFine Version
1.17

**Comment by KaiAF** [comment]
Reported here: #5811. Probably was unintentional.
