### ISSUE TITLE
Not allowing alternate textures

### ISSUE THREAD

**Issue by clxwn** [sp614x/optifine#605]
Hi so I was trying to use this resource pack https://minecraft.curseforge.com/projects/vaders-alternative-block-pack-vanilla-add-on
And it works fine with the minecraft latest version so it isn't the pack, but when I try to use the latest version of optifine (OptiFine 1.11.2 HD U B7) alternate textures do not appear. I've also tried B6 and B5, still no luck.
I've also tried applying alternate textures in my resource pack that I know works fine with optifine, but same problem as with the above pack.

**Comment by Builderb0y** [comment]
Are "alternate blocks" enabled? (under video settings > details)

**Comment by clxwn** [comment]
Yeah sorry, it wasn't. Totally my fault, I was looking under another set of settings. Thanks!
