### ISSUE TITLE
Changing entity textures based on mob name

### ISSUE THREAD

**Issue by InfernoDigital** [sp614x/optifine#6050]
There was a link to the code showing how to check for entity names to change textures in this thread

https://github.com/sp614x/optifine/issues/620

but the link broke. I'm trying to make a resource pack that changes dog textures depending on what the dog's name is, and would like to look at that link.

**Comment by KaiAF** [comment]
The issue tracker is to report bugs or suggest things. Not general support. You can join our Discord server for that. [https://optifine.net/discord ](https://optifine.net/discord)
