### ISSUE TITLE
Dynamic light doesnt illuminate blocks with ambientocclusion off

### ISSUE THREAD

**Issue by GeForceLegend** [sp614x/optifine#6052]
## Description of Issue
Dynamic light doesnt illuminate blocks with "ambientocclusion":false in block model

## Steps to Reproduce
Create a block model with "ambientocclusion":false
Load this model in a resource pack
Place this block in darkness, and hold a light source in hand

## OptiFine Version
1.16.5 G8

## Installation Method
Included standalone installer

## Log Files/Crash Reports
Nothing special in log and no crashes

## F3 Debug Screenshot
Ambientocclusion on:
![2021-07-18_09 52 03](https://user-images.githubusercontent.com/41003546/126053253-b386414e-6fa2-4dc2-8035-82d79fe08c36.png)
Ambientocclusion off:
![2021-07-18_09 51 38](https://user-images.githubusercontent.com/41003546/126053256-d31ec4a2-8262-43f0-b041-b45f11b37d7b.png)

**Comment by sp614x** [comment]
Many vanilla models use `"ambientocclusion":false` and work correctly with dynamic lights.
For example: door, lever, ladder, etc.

**Comment by GeForceLegend** [comment]
Appears in 1.17 G9 Pre35 too. Maybe only affect full or/and opaque blocks?

**Comment by GeForceLegend** [comment]
Still exist in latest 1.21.1 previews. Looks like only full opaque blocks (or blocks that will create ambient occlusion around themselves) are affected? Using a same model for glass block and note block, only note block is not affected by dynamic light.

Resourcepack in testing: 
[Test.zip](https://github.com/user-attachments/files/17037303/Test.zip)

![2024-09-18_09 52 13](https://github.com/user-attachments/assets/205f8d84-4f79-4144-8ccd-a8b2725367ce)

**Comment by sp614x** [comment]
Fixed in 1.21.1 previews
