### ISSUE TITLE
[Bug] Shulkers and banner shields render with missing texture when wearing emissive elytra

### ISSUE THREAD

**Issue by dbrighthd** [sp614x/optifine#6054]
## Description of Issue
Shulkers show as missing textures and banner shields show as all black when using an emissive elytra
With elytra:
![image](https://user-images.githubusercontent.com/68525639/126055568-b9cd938b-a965-4773-8aa2-0771af0bb0f0.png)
No elytra:
![image](https://user-images.githubusercontent.com/68525639/126055580-90cbc483-e70e-46a2-9178-00d94d1b3079.png)

## Steps to Reproduce
Apply a texture pack with an emissive elytra or armor texture
## OptiFine Version
I noticed it on 1.16 through 1.17.1pre29

## Installation Method
This happens standalone and with the latest (1.11.18) optifabric

## F3 Debug Screenshot
![image](https://user-images.githubusercontent.com/68525639/126055590-ac6acf9d-7e82-41b0-a706-60c23ff67138.png)

**Comment by dbrighthd** [comment]
This might be the same as #4571 , although they do not mention the shulker part

**Comment by dbrighthd** [comment]
still present in full release

**Comment by dbrighthd** [comment]
still present in H1_pre1

**Comment by MinecraftMinun** [comment]
Unsurprisingly an issue for ender chests and trapped chests too.

**Comment by dbrighthd** [comment]
Fixed in H7 pre3
