### ISSUE TITLE
Optifine Cape,Skins

### ISSUE THREAD

**Issue by Wymiana** [sp614x/optifine#6055]
Hello, I encountered a problem that I do not see capes or skins at home, I do not have an antivirus, I reset the computer to factory settings and nothing worked, I contacted the help desk on discord and nobody asked for it, maybe someone will help me here, in the window hosts doesn't know anything about optifine either.

I use a translator..

**Comment by Whitelisted1** [comment]
Do you have a firewall? Try whitelisting the cape and skin servers if you do,

**Comment by Wymiana** [comment]
nothing worked

**Comment by ZenIsBestWolf** [comment]
Hey there, please reach out again via Discord or email us at optifinex@gmail.com for support (GitHub is for bug reports)
