### ISSUE TITLE
1.17.1 pre29: Game stalls/crashes after multiple dimension changes/Nether portal entries

### ISSUE THREAD

**Issue by thraeryn** [sp614x/optifine#6059]
Sometimes it takes two or three times, but eventually OptiFine HD U G9 pre29 will cause Minecraft to stall during the Nether portal shift from one dimension to the next. Minecraft never recovers, instead requiring a force close; the Minecraft Launcher offers the less-than-helpful "Exit code: 0".

OS: Linux Mint 20.02 Cinnamon

Please let me know what logs might help pinpoint the issue and where I can find them.

**Comment by Jiingy** [comment]
Closing for lack of response from original issue poster.
