### ISSUE TITLE
Adding a NOT function to CIT

### ISSUE THREAD

**Issue by reinder-s** [sp614x/optifine#606]
i was wondering if it could be possible to add a not function to cit.
for example nbt.display.Name=!yes, would change the texture only if the name is anything but yes

**Comment by Sparqey** [comment]
you could do that already,
by just making the "custom item texture" to change when its yes to the old one
For example you want it to be texture 1 when it says yes in it and texture 2 if yes is not in there
then you make it so that texture 2 changes to texture 1 when it has yes in it

**Comment by reinder-s** [comment]
Maybe i should explain my intention. I have an animated 3d json model for a sword and because optifine does not support json for cit yet I thought i would, like you said make the 3d model the standard. But i need the model to be for a sword with a specific item name. And that is not possible or maybe it is and i haven't looked good enough

**Comment by Sparqey** [comment]
after thinking a bit i know something that would be intresting,
just blend 2 or more models in a single item
and just make parts transperant that aren't used ill make a example in a min for you ;)

**Comment by reinder-s** [comment]
Would it be helpfull if i were to give you the model i want the sword to have?

**Comment by sp614x** [comment]
Updated preview C1 for 1.11.2
- extended CIT NBT rules, values starting with "!" perform a negative match (#606)
