### ISSUE TITLE
[1.17] Shaders doesn't load in lower PCs and OpenGL 1282 error

### ISSUE THREAD

**Issue by SirLimee** [sp614x/optifine#6060]
Shaders in 1.17 are not loading in lower PCs, in 1.16, the shaders load with small FPS range because of the bad settings of the pc, but in 1.17 the Mojang loading screen doesn't even get out, so because of that other people cant take screenshots or render cinematics with their favorite shader

I just clicked to activate the shaders, but this bug only works with lower PCa

I feel bad becaus this thing happened, but i dont know if this bug is because of the wheigh of 1.17 version or just an actual Optifine bug

## Installation Method
I have installed Optifine by the official site, in the mirror link. I have installed by opening the jar file

At first i used optifine as standalone but now im using fabric because of replaymod

**Comment by fayer3** [comment]
Could you post a log file of when this happens?

**Comment by Jiingy** [comment]
Closing for the following reason by sp614x in another issue 
https://github.com/sp614x/optifine/issues/2114#issuecomment-903301355
