### ISSUE TITLE
[suggestion] Better Grass for nylium

### ISSUE THREAD

**Issue by 4EPBRK6RK6RK** [sp614x/optifine#6068]
In 1.16, the nylium blocks were added. In fact, they are grass and I would like to have a Better Grass function for the crimson_nylium/warped_nylium blocks as well.
I would also suggest adding the ability to add Better Grass for all blocks using resourcepacks
I'm sorry, I don't speak English and I use a translator
![image](https://user-images.githubusercontent.com/60979145/126633959-00bf00b7-3404-4a5d-84d6-fb6acf7c630e.png)

**Comment by Regnander** [comment]
#4212

**Comment by 4EPBRK6RK6RK** [comment]
Thank you for your help Regnander
Closing the topic
