### ISSUE TITLE
[Can't Create New World] Ingame causes void world with errors

### ISSUE THREAD

**Issue by GatK0ng** [sp614x/optifine#6071]
## Steps to Reproduce
When trying to make a new world (survival, creative, and hardcore tested), gets into the "world" but there is nothingness, and the chat keeps spamming:

OpenGLError 1282 (Invalid Operation)

or:

No EXT_framebuffer_object
[Shaders] Error: Invalid program "final"

## OptiFine Version
OptiFine HD U G9 pre30

## Installation Method
Used the included standalone installer

## Log Files/Crash Reports
Dragged and dropped as instructed.

## F3 Debug Screenshot
Dragged and dropped as instructed.

## Prior Testing
Does not happen in vanilla, I am able to successfully make a new world in vanilla.

## Additional Information

macOS 11.4 (20F71)
[latest.log](https://github.com/sp614x/optifine/files/6866342/latest.log)
![2021-07-22_21 52 41](https://user-images.githubusercontent.com/60089284/126732575-28dd2707-b9e2-4562-8ebc-d3d79aff8dbf.png)

**Comment by Jiingy** [comment]
Closing for following reason in a comment by sp614x on another issue 
https://github.com/sp614x/optifine/issues/2114#issuecomment-903301355
