### ISSUE TITLE
Make Item Frames Render as Blocks instead of Entities

### ISSUE THREAD

**Issue by CheeseLouise1** [sp614x/optifine#6073]
When playing minecraft, I noticed that whenever I go near an area with a large amount of item frames my frames very quickly drop, and I know for a fact it's because item frames render as entities instead of blocks and I was wondering if Optifine could make it so item frames are rendered as block entities instead of regular entities to improve performance

Just to add on, Bedrock already has this feature, (it renders item frames as blocks as apposed to entities)

**Comment by sp614x** [comment]
Item frames can't be rendered as blocks without changing a lot of the internal game mechanics.
For example item frames can occupy the same space as another block:

![image](https://user-images.githubusercontent.com/16635441/132217528-44e7be4d-149f-4a45-9fd3-ee7c1f99ef61.png)
