### ISSUE TITLE
[Rendering/texture bug] texture not appearing correctly

### ISSUE THREAD

**Issue by JeremyFano** [sp614x/optifine#6074]
## Description of Issue

Sorry for incorrect spelling or grammar i'm not a verry great english speaker.

some texture are glitching (doesn't appear correctly or doesn't appear at all) (the texture change with the POV) 

![2021-07-24_01 50 39](https://user-images.githubusercontent.com/87453698/126850978-7254cc85-1066-41d9-b808-c656d758244b.png)
![2021-07-24_01 51 15](https://user-images.githubusercontent.com/87453698/126850990-7f23a74a-66a1-4dae-ae1a-ff06857df18f.png)
![2021-07-24_01 51 23](https://user-images.githubusercontent.com/87453698/126850993-b8b75f11-7af0-4b55-b48f-110b0b2c9b62.png)
![2021-07-24_01 51 31](https://user-images.githubusercontent.com/87453698/126850997-fd571987-4f28-40b6-bbf8-e63b69995120.png)

## Steps to Reproduce
nothing special, simply lauching the game and loading a world (solo or multiplayer)

## OptiFine Version
OptiFine 1.17.1_HD_U_G9_pre31 and older

## Installation Method
standalone

## Other Installed Mods
Shader : Complementary Shaders v4.2 Development Version 1
RP : UltimaCraft_PBR_(v.1.0)_(1.17)_lab and Sama_Faithful v1.9 [Minecraft 1.17.x]

## Log Files/Crash Reports
[latest.log](https://github.com/sp614x/optifine/files/6871612/latest.log)

## F3 Debug Screenshot
![2021-07-24_01 50 11](https://user-images.githubusercontent.com/87453698/126850972-2fd543e0-e7cb-45d0-b28c-c575f932647a.png)

## Prior Testing
Do not append in Vanilla (only with optifine and since the first 1.17.1(maybe even since 1.17.x i'm not sure) version (do not append with 1.16.x version)

I have custom jvm : -Xmx23G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M

**Comment by BaileyKay** [comment]
I have the same issue basically on 1.16.5 G7, and have more or less isolated it to being Connected Textures related myself. If I turn of Connected Textures the issue goes away.

**Comment by JeremyFano** [comment]
> 
> 
> I have the same issue basically on 1.16.5 G7, and have more or less isolated it to being Connected Textures related myself. If I turn off Connected Textures the issue goes away.

you are right ! it's Connected Texture that make this bug append ! doesn't matter if it is fast or detailed ! should i make a new post to report this issue ?
