### ISSUE TITLE
[Optifine 1.17.1 pre_31] M1 Macbook crashes with any shaders enabled (with the exception of internal)

### ISSUE THREAD

**Issue by hyoink** [sp614x/optifine#6076]
**Description of Issue**

All shaders, with the exception of the internal shaders, seem to crash upon loading.

**Steps to Reproduce**

Load any shaders with an M1 Macbook. No shaders run perfectly, but enabling any shader seems to crash the game while in a world.

**OptiFine Version**

OptiFine_HD_U_G9_pre_31

**Installation Method**

Standalone installer

**Other Installed Mods**

None

**Comment by sp614x** [comment]
Crash report, error log, error messages?

**Comment by Jiingy** [comment]
Closing for lack of response from original issue poster.
