### ISSUE TITLE
[1.17.1 Optifine HD U G9 pre31] bettergrass.properties needs updating.

### ISSUE THREAD

**Issue by BellPepperBrian** [sp614x/optifine#6077]
## Description of Issue
For resource packs, if you include the grass_path textures in 1.17.1 Optifine, the better grass breaks.  Even though the grass_path texture is not used in 1.17.X.  It's called dirt_path in 1.17.X, and if you include that texture without having the grass path texture in your resource pack, then the better grass path won't break.  If you do include the grass path texture without the dirt path texture, it will still break the better grass path.  It will use the 16x texture, but won't apply the better grass path.

## Steps to Reproduce
1. I added the grass path texture in a 1.17 resource pack and the better grass broke.

## OptiFine Version
1.17.1 Optifine HD U G9 pre31

## Installation Method
I used the included standalone installer.

## Log Files/Crash Reports
[latest.log](https://github.com/sp614x/optifine/files/6872757/latest.log)

## F3 Debug Screenshot
![2021-07-24_12 22 35](https://user-images.githubusercontent.com/74277198/126875062-592f9bb3-ca57-4111-869c-e27cf3aa5f89.png)

## Prior Testing
<!-- If you've installed standalone:
Bettergrass is an Optifine feature and I presume this problem occurs when using forge and fabric.

**Comment by ZenithRogue** [comment]
fixed per https://github.com/sp614x/optifine/commit/fd63b9cc03a7d731621e904b5e8653c947245326
