### ISSUE TITLE
[1.10.2_HD_U_D7] Random Red Tint to Screen

### ISSUE THREAD

**Issue by MokahTGS** [sp614x/optifine#608]
https://www.dropbox.com/s/necfkv7g4zvusdt/2017-04-22_09.07.49.png?dl=0

The screen will tint red randomly.

I'm getting this odd red tint on my screen with the 1.10.2_HD_U_D7 version of Optifine and I'm not sure what is causing it.  I searched for the issue and there are old posts talking about a 1.8.7 optifine bug that did this.  Did the issue resurface?

**Comment by Brottweiler** [comment]
Disable your resourcepack first of all.

**Comment by MokahTGS** [comment]
And this does nothing...anyone have any idea?

**Comment by sp614x** [comment]
Which mods are installed?
Have you tried to reset the video settings (Video Setting -> Other -> Reset)?
