### ISSUE TITLE
[1.17.1 PRE32] PROPERTY Specific GUI's Don't Work

### ISSUE THREAD

**Issue by JustAHuman-xD** [sp614x/optifine#6080]
If you try to make for example, each shulker box have a custom gui per color. It Doesnt work, each one is the exact same color. Same thing for normal to ender chests. And each villager type.

## Steps to Reproduce
I got the Colorful Containers Dark mode texture pack. It didn't work. I went through the settings to see if there was anything wrong, there wasnt. (you do have to change the pack version to 1.17)

## OptiFine Version
1.17.1 Pre32

## Installation Method
I used the standalone installer.

## F3 Debug Screenshot
![2021-07-25_01 25 55](https://user-images.githubusercontent.com/65748158/126889919-e8be870b-d752-4b1a-81c9-99a689adb6be.png)

**Comment by KaiAF** [comment]
yeah custom gui is broken in 1.17: Reported here: #6094.
