### ISSUE TITLE
Frames

### ISSUE THREAD

**Issue by TheRebelYell315** [sp614x/optifine#6084]
I haven't ever had an issue with running shaders with high frames, but pre 32 has been causing frame issues for me. It runs fine on pre 31 though.

**Comment by Lythael** [comment]
I have performance issues on all 1.17.1 Optifine releases.
The performance boost over vanilla Minecraft is almost non existent.
And with shaders it's a tragedy.

Compared to 1.16.5 where i got considerably large performance boost over vanilla to the point i could run shadders with 60 fps (40~ in busiest areas)

**Comment by KaiAF** [comment]
pretty much duplicate of: #6085
