### ISSUE TITLE
it was an issue on my side, please delete it

### ISSUE THREAD

**Issue by T-Matyi** [sp614x/optifine#6088]
it was an issue on my side

**Comment by Whitelisted1** [comment]
> it was an issue on my side

@T-Matyi You can close the issue by clicking the "close" button on this issue (right next to the comment button)
![Screen Shot 2021-07-26 at 8 06 56 AM](https://user-images.githubusercontent.com/77711834/127002517-abfa54f9-bbb2-4309-b7b7-42908824ac94.png)

**Comment by T-Matyi** [comment]
Yeah, I knew that, but thought you can delete it too. Nevermind.
