### ISSUE TITLE
Optifine Bug

### ISSUE THREAD

**Issue by jttkross** [sp614x/optifine#609]
I was able to load minecraft perfectly despite I have different mods on it. I use a 1.7 forge version to load my mods and I have optifine added there. Then all of a sudden it doesn't work and the launcher is able to load minecraft but whenever I go to any server (single or multiplayer) it just has a black screen and I'm not able to move or do anything. I went to the 1.8 update to play a server (the version is solely an optfiine version and no other mods added). I did the same thing and went to try a couple different servers and it's done the same thing where the black screen would happen. Then I went on a regular 1.8 version without optifine and it works perfectly, I don't know what's the problem. My computer is somewhat bad and it's just a laptop and optifine helps immensely with my fps. Please help!

**Comment by sp614x** [comment]
Probaly the same as #588.

FastCraft 1.25 should work:
https://forum.industrial-craft.net/thread/10820-wip-1-7-10-fastcraft-1-23-note-all-posts-of-new-members-need-to-be-approved-firs/?postID=207199#post207199
