### ISSUE TITLE
[CEM] Illusioner model hat layer error

### ISSUE THREAD

**Issue by CynicalZombie** [sp614x/optifine#6092]
I'm currently updating a resourcepack using custom entity models to 1.17.1 and found that the illusioner model doesn't work the same as before anymore. Somehow the original hat layer gets rendered in addition to the defined cem cubes, using its original location in the texture file. All other illagers, using the same custom model, work fine just as expected. Tested in the latest OptiFine HD U G9 pre32.

**Comment by sp614x** [comment]
Fixed
