### ISSUE TITLE
[Bug Custom GUI] Custom gui wont work for 1.17.x

### ISSUE THREAD

**Issue by GenralFluffs** [sp614x/optifine#6094]
## Description of Issue
I have been making and updating a resource pack since 1.15. This packs includes MANY optifine features. One of these features is custom GUI's. The new 1.17 Optifine seems to have broken custom GUI's. I have tested my pack in real time in 1.16 and 1.17 and the guis only dont work in 1.17.

## Steps to Reproduce
1. Use my resourcepack

## OptiFine Version
1.17 pre 26

## Installation Method
Optifine.net

## Image
[https://i.imgur.com/UJZIGuH.png](url)
## My Resource-pack
https://www.planetminecraft.com/texture-pack/better-vanilla-survival-pack-1-15/

**Comment by KaiAF** [comment]
Pinning the issue because a lot of people seem to be talking about it, and so that the developer can see it. This doesn't mean that this bug has a priority compared to others.

**Comment by sp614x** [comment]
Fixed, coming in next preview.
