### ISSUE TITLE
[Cape] Is there a way to copy other's cape design?

### ISSUE THREAD

**Issue by layou233** [sp614x/optifine#6095]
## Description of the new feature
I search for many times and get the same result as that there is no official way to copy / get other's cape banner code but you can easily recreate it.  
Even then, it is difficult for me banner noob to do that all so I am asking for a cape code API, etc.  
Thanks!

**Comment by XxMr1234GamerzxX** [comment]
theres mods for this.......

**Comment by layou233** [comment]
> theres mods for this.......

whats the mod's name? where can i get it pls?

**Comment by XxMr1234GamerzxX** [comment]
minecraftcapes 

it has its own website and available on curseforge for forge/liteloader/fabric it supports other capes aswell such as optifine

https://minecraftcapes.net/

**Comment by layou233** [comment]
> minecraftcapes
> 
> it has its own website and available on curseforge for forge/liteloader/fabric it supports other capes aswell such as optifine
> 
> https://minecraftcapes.net/

emm so just now i browsed that website but it seems to be no way to get the banner code of other's optifine cape?

**Comment by KaiAF** [comment]
At the moment, there is not a way. Soon there might be.
