### ISSUE TITLE
Lodestone Compass Visual Glitch (1.17.1)

### ISSUE THREAD

**Issue by SrTopster** [sp614x/optifine#6097]
Version: OptiFine HD U G9 pre32
![2021-07-27_11 47 46](https://user-images.githubusercontent.com/85837528/127181824-1d0ba974-de90-4b87-bd2b-2a72bda79818.png)

**Comment by KaiAF** [comment]
Can you send a f3 debug menu screenshot? Are you susing a shader pack? Or a resource pack?

**Comment by SrTopster** [comment]
No Shaderpack or Resourcepack
![2021-07-31_12 41 12](https://user-images.githubusercontent.com/85837528/127745204-a52991c4-bdd3-45fa-b6db-7f4661631616.png)

**Comment by QuinStudios** [comment]
This is still present for me in 1.18 as well, as far as I can tell.

**Comment by LaShids** [comment]
Still bugged in 1.18.1

**Comment by sp614x** [comment]
Fixed, coming in next preview
