### ISSUE TITLE
0 fps after 3-4 minutes of gameplay

### ISSUE THREAD

**Issue by xAddd** [sp614x/optifine#610]
When I load up OptiFine, it works properly for about 3-4 minutes then my fps becomes 0 for like 10 minutes then I have another 30seconds of 70-80 fps then it goes to 0 again.
It worked properly for about 2 years. Is this a sign for a new computer? Please help.
(Edit) It does this with any version of OptiFine and tried restarting my laptop and it still didn't solve anything. I've been trying to find answers forever and I couldn't find any solutions.

**Comment by sp614x** [comment]
More details needed:
- other mods installed?
- resource pack?
- shaders enabled?
- error log (game output)?

Have you tried "Video Settings -> Other -> Reset"?

**Comment by KaiAF** [comment]
Closing this as there has been no response from the author.
