### ISSUE TITLE
Minecraft Unplayable 

### ISSUE THREAD

**Issue by boyproO19** [sp614x/optifine#6100]
Minecraft is unplayable in single player FPS is fine but the TPS is really low and the computer heats up really fast.
![2021-07-28_12 46 16](https://user-images.githubusercontent.com/86196413/127278526-5de2788e-c1f2-46f6-978b-c7686ae9017e.png)
EDIT: pictures with optifine only installed
![2021-07-30_07 16 30](https://user-images.githubusercontent.com/86196413/127586390-940c66c2-2558-40c1-8dea-7b3b263358eb.png)
![2021-07-30_07 16 32](https://user-images.githubusercontent.com/86196413/127586394-6787b15d-eed6-46f7-8b56-cebd0666198e.png)
![2021-07-30_07 16 49](https://user-images.githubusercontent.com/86196413/127586400-33ed5999-f0e3-4068-add4-e2be225539d5.png)

**Comment by XxMr1234GamerzxX** [comment]
its seems that you have other mods?...... doubt this is optifine......

**Comment by boyproO19** [comment]
I've tried optifine only too.

**Comment by SirreStrange** [comment]
You should replace the picture to be one without the other mods..

**Comment by boyproO19** [comment]
ok

**Comment by KaiAF** [comment]
Try lowering your current settings, like turn off smooth fps, render regions and fast render. See if that might help. Also, do you have a GPU? If so, looks like minecraft is using the integrated graphics card.

**Comment by boyproO19** [comment]
basically turning off all the the options you said doesn't help in TPS either.

**Comment by boyproO19** [comment]
UPDATE: I found something strange if there is a lagspike in frames the tps seems to increase more FPS seems to kill TPS with Vsync the TPS is always high. 
![2021-08-02_07 04 41](https://user-images.githubusercontent.com/86196413/127792384-c0f26f68-cf5a-4352-bbaf-2bad9ec1a40e.png)
The TPS on the left side is with Vsync on and the one on the right is with FPS capped to 70.

**Comment by XxMr1234GamerzxX** [comment]
dude you are still running with a environment that's got other mods/modloaders, 

run optifine properly E.G without (Optifabric) and try again, you are running preview software in a non validated way (EG non production ready software on third party loaders it was not designed to run on)

**Comment by XxMr1234GamerzxX** [comment]
> UPDATE: I found something strange if there is a lagspike in frames the tps seems to increase more FPS seems to kill TPS with Vsync the TPS is always high.
> ![2021-08-02_07 04 41](https://user-images.githubusercontent.com/86196413/127792384-c0f26f68-cf5a-4352-bbaf-2bad9ec1a40e.png)
> The TPS on the left side is with Vsync on and the one on the right is with FPS capped to 70.

TPS is supposed to be at 20........... i see spikes but this is normal as some biomes and minecraft generating terrain will eat ot TPS

**Comment by Jiingy** [comment]
Issue is very likely unrelated to OptiFine as the posted debug screenshots are in a Fabric enviornment with other mods.
