### ISSUE TITLE
Custom Horse models (saddle & head) are slightly broken

### ISSUE THREAD

**Issue by ghost** [sp614x/optifine#6105]
## Description of Issue
Custom horse models for "saddle" and "head" do not render in 1.17 versions
(Both effect zombie horses, & skeleton horses. Saddle issues also effect donkey & mule)
[Worked in 1.16.zip](https://github.com/sp614x/optifine/files/6904339/Worked.in.1.16.zip)

![2021-07-29_20 24 28](https://user-images.githubusercontent.com/88169922/127581716-443f2e5e-2410-463d-be78-9e06b2afc50d.png)

## Steps to Reproduce
1. Use a resource pack that modifies the model for a horse's head and/or saddle
2. Watch the modified saddle/head not render in

## OptiFine Version
1.17+ preview versions

## Installation Method
 I used the included standalone installer

## Prior Testing
Custom models don't exist in vanilla: So "irrelevant".

## Additional Information
This is super annoying. Please fix

**Comment by ewanhowell5195** [comment]
horse cem works fine now
