### ISSUE TITLE
I am unable to open minecraft 1.17.1 with any OptiFine installed

### ISSUE THREAD

**Issue by BluFox185** [sp614x/optifine#6106]
It just says: "The game crashed! Error code: 0"

What do I do?

**Comment by KaiAF** [comment]
Can you send a crash log

**Comment by CobaltHail** [comment]
> Can you send a crash log

Not OP But I have the same problem. It doesn't make a crash log per say, it just updates the [Latest](https://pastebin.com/w3Kcy7Bd) and [Debug](https://pastebin.com/9nCZLvMF) logs. Any Ideas what it could be?

**Comment by KaiAF** [comment]
No reply from OP. @CobaltHail I believe the crash was caused by optifine not having support for forge yet. You would have to wait until it does have support.
