### ISSUE TITLE
[Category] Short description

### ISSUE THREAD

**Issue by DeoTime** [sp614x/optifine#6110]
## Description of Issue
"The error is caused by an incompatibility between optifine, lwjgl and apple's API, optifine tries to access some address in RAM and java throws an exception because it can't access it."

## Steps to Reproduce
1. install the version of optifine listed below
2. on the installation, try to connect to mc.hypixel.net; the installation will crash. (running on Apple)

## OptiFine Version
1.17.1 pre26 HD U G9

## Installation Method
Installer

## Log Files/Crash Reports
[message.txt](https://github.com/sp614x/optifine/files/6911297/message.txt)

## F3 Debug Screenshot
(f3 cannot be accessed, *the game crashes before i am able to enter the server.*)

## Prior Testing
- Does this happen in Vanilla without OptiFine?
- No.

**Comment by fayer3** [comment]
does this also happen with pre32?

**Comment by DeoTime** [comment]
pre32 works
