### ISSUE TITLE
[Custom Colormap] tinting a potted fern also tints the dirt and pot textures

### ISSUE THREAD

**Issue by h3oCharles** [sp614x/optifine#6117]
## Description of Issue

when I'm tinting a potted fern using the grid format, I seem to also tint the dirt and the pot, which shouldn't happen, considering that targeting the grass block with the same properties file ignores dirt and grass block side textures

## Steps to Reproduce
uuh idk I made a resource pack with a custom colormap, the colormap properties file is a grid format that targets grass blocks, grass, tall grass, ferns, large ferns, potted ferns, and sugar cane

## OptiFine Version

OptiFine_1.17.1_HD_U_G9_pre31_MOD.jar

## Installation Method

extracted the downloaded jar, then put jar file in the mods folder

## Fabric/Forge Version

fabric loader 0.11.6
fabric API 0.37.0+1.17

## OptiFabric Version

1.11.8

## Other Installed Mods

![image](https://user-images.githubusercontent.com/8020330/127785632-ae7fb84a-e04e-40ba-82a1-9958f4a81a7a.png)

## Log Files/Crash Reports

not applicable

## F3 Debug Screenshot

![2021-08-01_23 21 52](https://user-images.githubusercontent.com/8020330/127785678-947dc453-4bd0-4018-af81-a32c2045062d.png)
![2021-08-01_23 21 54](https://user-images.githubusercontent.com/8020330/127785683-9ecfe915-5a33-4f6c-9d69-d952713f1569.png)

## Prior Testing

- not applicable

## Additional Information

ignore black leaves, I'm in the middle of making another colormap pallete

**Comment by KaiAF** [comment]
Does this happen with optifine without any other mods?

**Comment by Jiingy** [comment]
Closing for lack of response from original issue poster.
