### ISSUE TITLE
[PlayerModels] Make playermodels visible to others

### ISSUE THREAD

**Issue by LightslicerGP** [sp614x/optifine#6118]
In optifine, the player models are only seen by the user. There should be a way to use player models and let others that use optifine to see them as well. I don't think there is a way to do it as of right now (I've searched far and wide and haven't found this issue anywhere) and if it is possible I would like to know-how.

You can add player models and make them work by using _ -Dplayer.models.local=true_ but it's only on the user's side. It doesn't show for others using optifine

**Comment by Regnander** [comment]
On #823 you can find a discussion about this.

**Comment by KaiAF** [comment]
Relevant #823
