### ISSUE TITLE
[Crash] Crash when charged with forge

### ISSUE THREAD

**Issue by miguerubsk** [sp614x/optifine#6119]
## Description of Issue
It crashes when i try to cherge it with forge, minecraft launcher gives error code 0.
![image](https://user-images.githubusercontent.com/26636866/127838301-f62b5a2e-0c67-43f2-bcfd-39f3f2a6f1d0.png)

## Steps to Reproduce
1. Install forge
2. Put optifine in mods folder

## OptiFine Version
preview_OptiFine_1.17.1_HD_U_G9_pre32

## Installation Method
droped the JAR file into my "mods" folder

## Fabric/Forge Version
forge-1.17.1-37.0.18

## Other Installed Mods
gravestone-1.17.1-1.0.2
ironchest-1.17.1-12.0.2
Xaeros_Minimap_21.14.1_Forge_1.17.1

[latest.log](https://github.com/sp614x/optifine/files/6915860/latest.log)

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
-- No

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   - Only OptiFine and Forge

- Does this happen in OptiFine standalone?
-- No, with optifine installation
- Does this happen in Vanilla without OptiFine?
-- No
- Have you tried using a binary search to find which mods cause this issue?
-- Yes

**Comment by MeowMC** [comment]
OptiFine 1.17 is not yet compatible with Forge
