### ISSUE TITLE
[Shaders] Specular and normal for mod  textures

### ISSUE THREAD

**Issue by Grimmspecter** [sp614x/optifine#612]
hi its not an issue i was told you might be able to help me, i want to get shaders to target _n and _s in folders other than resourcepacks\(packname)assets\minecraft   eg \resourcepacks\RD3 Craft\assets\arsmagica2 and \resourcepacks\RD3 Craft\assets\embers this is not an issue you with normals in general the do work they do load the issue lies in the fact that there only seen on vanilla block and i can assure you that every file is named and placed corectly as the textures work just not the normals eg oreblockbluetopaz.png shows up but oreblockbluetopaz_n.png does not

**Comment by sp614x** [comment]
Testing with OptiFine E1 for 1.12.2 and Immersive Engineering. 
Configured normal/specular textures for `immersiveengineering:ore (type:copper)`

Default texture:
![image](https://user-images.githubusercontent.com/16635441/41649230-5dce5df6-747b-11e8-904d-27c501bce128.png)

Normal texture:
![image](https://user-images.githubusercontent.com/16635441/41649176-35e13f34-747b-11e8-9556-20fdfbbf971e.png)

Specular texture:
![image](https://user-images.githubusercontent.com/16635441/41649193-453030da-747b-11e8-8620-ff67e92a24e0.png)

Normal and specular textures seem to work correctly.
