### ISSUE TITLE
[Category] Short description missing ''fast'' mode for fog

### ISSUE THREAD

**Issue by thuanvlin** [sp614x/optifine#6120]
## Steps to Reproduce
1. What do you do...
2. ...to find this bug?

**Comment by Regnander** [comment]
Please upload a F3 screenshot, so it's possible to figure out what hardware you are using and which OptiFine version you have.

**Comment by mrktospl** [comment]
fast fog was a vanilla bug and was fixed in 1.17 so the option is gone

**Comment by sp614x** [comment]
In 1.17 the fog is implemented using shaders and the Fast setting is not available anymore.
