### ISSUE TITLE
Entities like dropped items, chests, animals, boats, players, beds, and item frames flicker black when world stutters

### ISSUE THREAD

**Issue by PoompkinPlayer** [sp614x/optifine#6123]

**Comment by KaiAF** [comment]
Can you provide more details? Send a F3 debug menu screenshot, mention if you are using other mods or not, any shaders?

**Comment by PoompkinPlayer** [comment]
> Can you provide more details? Send a F3 debug menu screenshot, mention if you are using other mods or not, any shaders?

i am not using any shaders or other mods

**Comment by KaiAF** [comment]
that still doesn't provide much detail about the bug

**Comment by KaiAF** [comment]
Reported here: #6013.
