### ISSUE TITLE
[SHADERS] Enchanted Items issues 

### ISSUE THREAD

**Issue by 100skay** [sp614x/optifine#6124]
I'm actually playing minecraft with a famous modpack called better minecraft (on curseforge). But this problem seems to only affect me so i created this topic.

Minecraft Version 1.16.5
Optifine ver 1.16.5 HD_U_G7 (same on G8)

All my enchanted item are black. It look like that.
![Armor](https://user-images.githubusercontent.com/88389003/128032561-a1add79e-4b31-4e79-b9a8-b5c6024d0662.png)
![e86jtvf3wns41](https://user-images.githubusercontent.com/88389003/128032589-dbf0ef88-2eab-44ce-a6aa-8f94b6b508d7.png)

If anyone know a fix, feel free to tell me : )

**Comment by KaiAF** [comment]
Can you provide a f3 menu screenshot and send a latest.log file?

**Comment by CinnamonRollFoxi** [comment]
I have the same issue with a different modpack but made from the same dude who made better minecraft.

**Comment by Jiingy** [comment]
This is very likely a mod conflict, or the specific shader you are using is outdated/causing the issue.
