### ISSUE TITLE
[Custom GUI] Custom GUIs for Loading Screens always show Icons.png

### ISSUE THREAD

**Issue by SergeantDelio** [sp614x/optifine#6128]
## I tried making custom loading screens for dimensions, but it always shows the icons.png texture.
![unknown](https://user-images.githubusercontent.com/85892695/128183393-98bfe91a-897f-4edd-8878-b8a7d85019bb.png)

## Steps to Reproduce
1. to recreate this bug, put a 16x16 texture in assets/minecraft/optifine/gui/loading and name it background-1.png (it works with the other dimensions too, tho)
2. If you then walk thru a Nether Portal, and the loading screen appears, it will appear as icons.png

## OptiFine Version
1.17.1-Optifine_HD_U_G9_pre32

## Installation Method
I used the standalone version

## F3 Debug Screenshot
![2021-08-04_14 54 14](https://user-images.githubusercontent.com/85892695/128184142-04a294ee-01dc-405b-ba3b-7e353785df36.png)

## Prior Testing
- This does not happen in Vanilla minecraft, because it requires Optifine to work. It does however work in Optifine 1.16, thats why I know its a bug in Optifine and not my computer.

## Additional Information
The Optifine Discord was very helpful. The icons.png texture is at assets/minecraft/textures/gui/icons.png, so it could have something to do with that two diffrerent folders are named gui.

**Comment by Whitelisted1** [comment]
are you changing the base file texture, or are you creating a resource pack? It works for me just fine (or did when I last played mc)

**Comment by SergeantDelio** [comment]
> 
> 
> are you changing the base file texture, or are you creating a resource pack? It works for me just fine (or did when I last played mc)

I am creating a resource pack based on sp64x's tutorial. https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/loading.properties

**Comment by luckydoggo** [comment]
I ran into this issue the same way that you did, hopefully it gets fixed soon

**Comment by Inxity** [comment]
I have the issue too 
![2021-08-07_12 51 32](https://user-images.githubusercontent.com/61350916/128596392-2f11322e-97c1-4dc2-8482-cfb5b1fd0e33.png)

**Comment by sp614x** [comment]
Fixed, coming in next version.
