### ISSUE TITLE
Strange visual glitches during weather events in Optifine 1.17.1 preview versions, related to Clouds : Fancy

### ISSUE THREAD

**Issue by DTM06** [sp614x/optifine#6130]
## Description of Issue
During weather events (rain, snow), the visuals start to break down with major graphical tearing around large bodies of water.
This only seems to happen with Clouds on Fancy. Setting them to "Fast" or simply turning them off will fix the issue.
Screenshots, taken in version 1.17.1 Pre-32 : https://imgur.com/a/0Y923Te

## Steps to Reproduce
Set Clouds to "Fancy"
Summon rain through commands (or just wait for natural rain)
Visit a large body of water such as an ocean biome or rivers.
*Effect is more noticeable if you use an Elytra and fireworks to quickly fly around the world. 

## OptiFine Version
1.17.1, Pre-release 32

## Installation Method
Included standalone installer, no other mods.

## Log Files/Crash Reports
[latest.log](https://github.com/sp614x/optifine/files/6933518/latest.log)

## F3 Debug Screenshot
![2021-08-04_14 12 47](https://user-images.githubusercontent.com/88454555/128233117-cec664df-319b-487d-b62e-802a7fd78ae9.png)

## Prior Testing
Did not experience this issue in Vanilla or Optifine 1.16.5 and below. 

## Additional Information
Resetting my video settings to their default values and running a clean installation of the game did not fix this issue.
I suspect this has something to do with Minecraft's recent implementation of OpenGL 3.2, or AMD's awful drivers. Perhaps a combination of the two.

Edit : This has not been fixed in Pre-release 33 or 34.

**Comment by sp614x** [comment]
Can't reproduce it on AMD/Win10.
Disabling Render Regions or using pre34 may help.
Probably caused by AMD drivers.

**Comment by DTM06** [comment]
After further testing, I found that the higher the framerate is, the more this issue would occur. Capping the frame rate at 60 (though you might get away with higher frame rates such as in the 85-90 range) completely fixes the issue.
