### ISSUE TITLE
[Bug] Crashing when using nether portal

### ISSUE THREAD

**Issue by creepjax** [sp614x/optifine#6131]
## Description of Issue
Crashing on multiplayer server when traveling through to or from nether randomly

## Steps to Reproduce
1. Load into multiplayer server with optifine
2. use a nether portal

## OptiFine Version
1.17.1-optifine_HD_U_G9_pre32

## Installation Method
used the installer included with optifine

## Log Files/Crash Reports
[hs_err_pid20588.log](https://github.com/sp614x/optifine/files/6934450/hs_err_pid20588.log)

## F3 Debug Screenshot

![2021-08-04_17 22 26](https://user-images.githubusercontent.com/88461140/128256782-66669f1c-8c0c-4c74-94cd-fc7cfb9b693d.png)

## Prior Testing
- Does this happen in Vanilla without OptiFine?

No. I was able to use the portal without problem.

## Additional Information
small server usually just myself, and at most 4 other people
using "sildur's enhanced default" shaders

**Comment by Lucipo** [comment]
Same issue only when using shaders (Sildur's Enhanced) on 1.17.1-optifine_HD_U_G9_pre32 w/ Optifabric.  

Crashes 100% of the time when going into another dimension from the overworld, not from another dimension to the overworld.

**Comment by sp614x** [comment]
Should be fixed in pre33.
