### ISSUE TITLE
[Bug] Non-Full / Transparent blocks rendered incorrectly on 1.16.5 (ATM6)

### ISSUE THREAD

**Issue by Sooperfish** [sp614x/optifine#6132]
# Description of Issue
Non-full blocks or blocks with transparency aren't rendered correctly when using optifine on All The Mods 6.
Only happens at certain camera angles.

Weird thing is it sometimes seems to have fixed itselves temporarily (without doing anything), and then comes back later.

# Steps to Reproduce
Download the newest ATM6
Add optifine and optiforge manually

# Optifine Version
OptiFine_1.16.5_HD_U_G8

# Optiforge Version
OptiForge-MC1.16.5-0.5.7

# AllTheMods 6 Version
All the Mods 6-1.7.6

# Options
[optionsof.txt](https://github.com/sp614x/optifine/files/6935193/optionsof.txt)
[optionsshaders.txt](https://github.com/sp614x/optifine/files/6935194/optionsshaders.txt)
[options.txt](https://github.com/sp614x/optifine/files/6935195/options.txt)

# Screenshots
Using Complementary Shaders
![2021-08-05_01 42 43](https://user-images.githubusercontent.com/5457984/128273809-8c962f01-b265-49bd-81fd-5154c6f2b4c0.png)

Using Seus PTGI
![2021-08-05_01 42 09](https://user-images.githubusercontent.com/5457984/128273868-bebeb6d6-0d87-405f-955f-08ee88962bf8.png)

**Comment by KaiAF** [comment]
Can you send a F3 menu screenshot?

**Comment by Sooperfish** [comment]
My apologies, I fixed this but forgot to update. I had to set CC:Tweaked's monitor renderer to VBO in its config https://github.com/SquidDev-CC/CC-Tweaked/wiki/Monitor-renderers
