### ISSUE TITLE
[Category] Short description

### ISSUE THREAD

**Issue by SwagJunkertun** [sp614x/optifine#6136]
## Description of Issue
Every time I open Minecraft with a forge client (Optifine in the "mods" folder) it crashes with an Exit Code: 0. This happens with or without other mods in the folder however if I use optifine as it's own installation it works fine

## Steps to Reproduce
1. What do you do...
2. ...to find this bug?

## OptiFine Version
OptiFine HD U G9 pre32

## Installation Method
Dropping the file in the "mods" folder

## Fabric/Forge Version
Forge

## Other Installed Mods
Xaero's Minimap and Xaero's Worldmap

## Log Files/Crash Reports
Exit Code 0

## F3 Debug Screenshot
![4742367236](https://user-images.githubusercontent.com/88556247/128554490-b60e4506-f4a1-459e-9235-2d2341c4f1e7.png)

**Comment by fayer3** [comment]
Optifine for 1.17.1 is not compatible with forge yet.

**Comment by KaiAF** [comment]
OptiFine will be updated at somepoint to support forge
