### ISSUE TITLE
OptiFine Crashes Minecraft - won't load

### ISSUE THREAD

**Issue by JaedenRuiner** [sp614x/optifine#6137]
## Description of Issue
I have been on 1.16.5 for some time now becuase Forge had yet to release a version for Minecraft 1.17.
I recently saw that Force 37.0.27 for Minecraft 1.17.1 had been release so I went about updating my mods.

## Steps to Reproduce
1. Downloaded & Installed Forge 37.0.27
2. Downloaded & Installed Xaero's MiniMap 21.14.1 
3. Downloaded & Installed Xaero's WorldMap 1.16.0
4. Downloaded & Installed OptiFine 1.17.1 HD U G9 pre32
5. Ran Minecraft through Launcher.  Game crashed before load.
6. Tried on OptiFine versions:
     1.17 pre25
     1.17 pre26
     1.17 pre30
     1.17 pre31

All versions of OptiFine post the 1.16.5 HD U G8 crashed MineCraft.  
Without OptiFine my regular setup works just fine.  

## OptiFine Version
OptiFine 1.17.1 HD U G9 pre32
  &   1.17 pre25
  &   1.17 pre26
  &   1.17 pre30
  &   1.17 pre31

## Installation Method
First like with previous version I simply copied the .jar into the Mods folder.  After this failed for all version, I tried to revert to the 1.16.5 version just incase backwards compatibility would suffice in the meantime.  this too crashed.  So when I saw this entry on your form, I tried simply running the .jar file and it offered to "install" it.  Which it did, as a standalone, not as a part of my forge profile.  Now this standalone seemed to be able to actually load, but of course without any of my other Mods.  

## Fabric/Forge Version
Forge 1.17.1_37.0.27

## Other Installed Mods
Xaero's MiniMap 21.14.1 for Forge 1.17.1 Minecraft
Xaero's WorldMap 1.16.0 for Forge 1.17.1 Minecraft

No log that i could discern.  it tried to load and just "Stopped!"

## F3 Debug Screenshot
![LoaderError](https://user-images.githubusercontent.com/36714687/128587892-d6934567-db6e-457c-82fb-2a0c5ee10ef4.jpg)

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   - Only OptiFine and Forge

## Additional Information
I am begining to believe that the version you have available is a "Standalone" only, not ready yet to work with Forge.  I will revert my current setup to 1.16.5 until further information is available. 

THanks
Jaeden "Sifo Dyas" al'Raec Ruiner

**Comment by james090500** [comment]
As clearly stated, in the optifine change log on every version you have tested...

https://optifine.net/changelog?f=preview_OptiFine_1.17.1_HD_U_G9_pre31.jar

![image](https://user-images.githubusercontent.com/20372645/128604812-f778ad4b-9ae4-4fcf-a27f-2a2a7be3274f.png)

**Comment by JaedenRuiner** [comment]
Ah.  Okay.  My Bad.  
I will wait for the forge compatible version to be released.

Thanks!
