### ISSUE TITLE
[Crash with optifabric]

### ISSUE THREAD

**Issue by GagetGaming7** [sp614x/optifine#6144]
##Description
Game crashess with error code 0 when launching minecraft with both optifabric and optifine.

## Steps to Reproduce
1. Downoad fabric mod loader
2. Download optifabric and optifine
3. Launch with both mods in the mod folder using the fabric profile.

## OptiFine Version
Pre33

## Installation Method
dropped into mods

## Fabric/Forge Version
0.11.6
## OptiFabric Version
1.11.17

## Other Installed Mods
cloth-config
fabric api
fallingleaves
illuminations
iluminations uninstaller
modmenu
shulkerboxtooltip

**Comment by KaiAF** [comment]
You can try updating optifabric. If it continues, there is nothing we can do as we aren't the developers of optifabric.
