### ISSUE TITLE
Sky keeps flickering

### ISSUE THREAD

**Issue by PoompkinPlayer** [sp614x/optifine#6148]
## Description of Issue
 The sky flickers black 

## Steps to Reproduce
1. What do you do...
2. ...to find this bug?

## OptiFine Version
 Optifine HD G9_pre33 Ultra

## Installation Method
 Standalone

## F3 Debug Screenshot
 https://user-images.githubusercontent.com/87291231/128755449-18a32b85-ba41-4a76-83e9-f5769a490635.png

**Comment by KaiAF** [comment]
Already addressed here: #5925. Try disabling fast render and render regions to see if this helps.
