### ISSUE TITLE
Graphic flickering to Grey

### ISSUE THREAD

**Issue by RoronoaDroagon** [sp614x/optifine#615]
Hello
So a buddy of mine and i is haveing a wierd flickering that turns every block grey.
It looks like we do a quick teleport to vampire land.
I turned off/disabled optifine and the grey flickering is gone.
It happens with and without resourcepacks.
Java is updated to latest and same is my graphic card.
I'm useing the D7 for 1.10.2. and i'm playing on the Direwolf20 pack.
I have had the issue since i changed to curse.
does anyone have a idea what is causing the problem??

**Comment by sp614x** [comment]
Screenshot or video to demonstrate the problem?

**Comment by RoronoaDroagon** [comment]
![2017-04-29_06 06 35](https://cloud.githubusercontent.com/assets/28124456/25552829/37b69bd0-2ca4-11e7-8dc3-6a24ed30236d.png)
this is how it looks like.

**Comment by sp614x** [comment]
Fast Render -> OFF ?
Video Settings -> Other -> Reset ?
