### ISSUE TITLE
The compass glint does not work well

### ISSUE THREAD

**Issue by Fernandg66** [sp614x/optifine#6155]
## Description of Issue
Compass glint does not reproduce well like vanilla minecraft, it looks like a mosaic.

## Steps to Reproduce
1. You need a compass
2. You need a lodestone
3. Place the lodestone on the ground
4. You need to link the compass to the lodestone
5. And the glitch is reproduced

## OptiFine Version
OptiFine HD U G9 pre33 (1.17.1)

## Installation Method
I download optifine from the official website, run the .jar file and install the optifine for the official Minecraft launcher.

## Additional Information
The glitch looks like this

Vanilla 1.17.1:
![2021-08-10_21 46 01](https://user-images.githubusercontent.com/88755254/128961704-c05546dd-c79f-469d-b4d6-dd90a8743092.png)

Optifine 1.17.1:
![2021-08-10_20 42 40](https://user-images.githubusercontent.com/88755254/128961326-5a650816-c6ba-4a0c-9ed6-b235dc1c9ea9.png)

**Comment by Regnander** [comment]
#6097
