### ISSUE TITLE
[Shaders] Crash when enabling shaders (shader-dependent)

### ISSUE THREAD

**Issue by MKBastler** [sp614x/optifine#6156]
## Description of Issue
Enabling shaders results, dependent on the shader, in a minecraft crash.

## Steps to Reproduce
1. Download and install Optifine 1.16.5 HD U G8
2. Enable a previously downloaded shader
3. The crash will happen dependent on what shader is used

## OptiFine Version
Optifine 1.16.5 HD U G8

## Installation Method
Standalone installer

## Log Files/Crash Reports
[hs_err_pid16088.log](https://github.com/sp614x/optifine/files/6968714/hs_err_pid16088.log)
[latest.log](https://github.com/sp614x/optifine/files/6968716/latest.log)
No crash report relating to this issue found

## F3 Debug Screenshot
![2021-08-11_15 22 53](https://user-images.githubusercontent.com/49870446/129036720-9ad86bf1-a02a-4c44-98a1-614103a087e4.png)

## Prior Testing
- Does this happen in Vanilla without OptiFine?
Irrelevant since issue is shaderrelated

## Additional Information
hs_err_pid16088.log says that minidumps are not allowed by this Windows Client, which might be a reason for the crash.

**Comment by KaiAF** [comment]
The crash is being caused by outdated/broken AMD drivers. So you can update them or reinstall them. If it continues to happen, you would just have to wait for AMD to fix it. Unfortunately, this is just something that OptiFine can't fix.
