### ISSUE TITLE
[Category] Fast math makes my overflow anticheat false flag

### ISSUE THREAD

**Issue by GladUrBad** [sp614x/optifine#6157]
hello i have minecraft anticheat
it has very cool and nice overflow predictions
but the problem is!
when i turn on the fastmath the prediction offset goes from 1e-8 to 1e-3 and sometimes 1e-2
obviously this is a problem because 1e-2 is well in the range of motion modifications
please fix, my whole server is getting spoofed alert ban
with new addition of another table i have gained nearly 1e-8 more fps, ironically that's how accurate overflow predictions could be if fast math didn't exist

**Comment by KaiAF** [comment]
#5578
