### ISSUE TITLE
[1.17.1 pre33] Getting error every time I try to install 1.17.1 Optifine (Mac)

### ISSUE THREAD

**Issue by CottonSpotten** [sp614x/optifine#6158]
## Description of Issue
"Cannot find Minecraft 1.17.1. You must download and start Minecraft 1.17.1 once in the official launcher." is the error I keep receiving, whenever I try to download Optifine. I have already launched (and played) 1.17.1 vanilla. I have also launched 1.17 vanilla and attempted to download Optifine pre26 + pre25, but gotten the same error. 1.16.5 Optifine works fine

## Steps to Reproduce
1. Download OptiFine HD U G9 pre33 jar file (standalone) 
2. Open in /minecraft/versions folder (through users/[name]/library/application support/minecraft/versions)
3. Get error

## OptiFine Version
OptiFine 1.17.1 HD U G9 pre33

## Installation Method
Attempt to open .jar file in versions folder

## F3 Debug Screenshot
![2021-08-12_10 00 37 2](https://user-images.githubusercontent.com/88806438/129118769-6b5a1062-8594-491f-8527-04b19970f672.png)

**Comment by fayer3** [comment]
is your minecraft installation in the default location?
if not you will need to point the installer to the location of your minecraft folder with the `...` button

**Comment by CottonSpotten** [comment]
> is your minecraft installation in the default location?
> if not you will need to point the installer to the location of your minecraft folder with the `...` button

i'm pretty sure it is anyway, but i do point the installer to the folder all the way through users/[name]/library/application support/minecraft/versions already. i'll edit the post to clarify that ty!

**Comment by CottonSpotten** [comment]
> you need to point it to the minecraft folder, not the versions folder

i can't believe it was actually that simple. thank you!!
