### ISSUE TITLE
[1.17.1] OptiFine Console spam due to net.minecraft.class_442.field_32272

### ISSUE THREAD

**Issue by Stereo528** [sp614x/optifine#6160]
## Description of Issue
OptiFine will spam the console with `Can not set static final java.lang.String field net.minecraft.class_442.field_32272 to java.lang.String`

## Steps to Reproduce
1. I have seen the bug from 2 people in the Support channel in the discord, I am unsure how to reproduce it, however, I am putting it here to be more noticeable

## OptiFine Version
1.17.1 G9 pre32 and pre33 from what has been said

## Log Files/Crash Reports
https://cdn.discordapp.com/attachments/423433009568546827/875970567902224384/error.gif
![image](https://user-images.githubusercontent.com/52116771/129437288-fd0a5b1d-7ad2-4552-ab24-cb4a2f8836c8.png)
from the OptiFine Support Channel

[latest.log](https://github.com/sp614x/optifine/files/6986015/latest.log)
log from someone else in the support channel

## Additional Information
I have used a discord bot called "Linkie" to determine that it is trying to do something with the TitleScreen class, and more specifically the DEMO_LEVEL_ID. I can also determine that it's trying to set a static final field to non static final if I'm reading the error messages correctly 

these images list from the 2 screenshots of the console
![image](https://user-images.githubusercontent.com/52116771/129437343-0f1c74fe-c5b1-4240-a8d9-ebdb0c0ff26b.png)
![image](https://user-images.githubusercontent.com/52116771/129437346-7b0b2796-982c-4d77-8d6c-814f9ee81c2e.png)

This image is the same field as the latest.log
![image](https://user-images.githubusercontent.com/52116771/129437353-df4056de-8ed1-4f33-b4d6-cb7193eebfd3.png)

**Comment by HiItsDevin** [comment]
After taking a look, there's a chance that setFieldValue *might* be getting the completely wrong value in updateMainMenu() in the GameRenderer class. This seems to only happen on sp614x's and OptiFine's birthday. As this only happens two days a year, this could be easily ignored, but when it does happen, pretty major log spam. This seems to also only happen on 1.17.x on Pre32+ as far as I can tell.

**Comment by HiItsDevin** [comment]
Should've mentioned that there's no workaround, you just have to wait for sp614x's birthday to be over.

**Comment by XxMr1234GamerzxX** [comment]
this cant be serious.......

**Comment by HiItsDevin** [comment]
> this cant be serious.......

No, it's real, that also why it explains why the splash doesnt say "Happy birthday sp614x!" today when using OptiFine 1.17.x

**Comment by HiItsDevin** [comment]
As of 00:01 on August 15th, the log spam has stopped. So yeah, something wrong with trying to set a custom splash text on a specific date.

**Comment by sp614x** [comment]
Fixed, coming in next preview.
