### ISSUE TITLE
Overlay CTM causes flashing between different CTM images

### ISSUE THREAD

**Issue by RalphOfficialYT** [sp614x/optifine#6163]
## Description of Issue
Basically, Sometimes making a Overlay CTM can result in flashing of the different CTM images whenever you move. Here is a video so you can understand: https://streamable.com/04eixo

## Steps to Reproduce
1. I'm not sure whether everyone faces this bug, so I don't really know whether this can be reproduced, But:
2. Make an Overlay CTM (i chose dirt in the video)
3. Test it out in-game

## OptiFine Version
Optifine HD U G9 pre33 (1.17.1)

## Installation Method
I downloaded Optifine on https://optifine.net/downloads , then I went to 1.17.1 Versions, and downloaded the latest pre33 version.

## Fabric/Forge Version
None

## OptiFabric Version
None

## Other Installed Mods
None

## Log Files/Crash Reports
I don't know whether this is relevant or not but here are the logs: 
[2021-08-06-1.log](https://github.com/sp614x/optifine/files/6986772/2021-08-06-1.log)

## F3 Debug Screenshot
![2021-08-14_21 37 28](https://user-images.githubusercontent.com/74642894/129452420-b92d0b1c-c1e9-45c7-84dd-c395e25a1060.png)

## Additional Information
Again, I'm not sure whether everybody faces this issue. So yeah. Also sorry if this was a bit unproffesional.

**Comment by KaiAF** [comment]
No response from the author of the issue, closing
