### ISSUE TITLE
possible virus

### ISSUE THREAD

**Issue by lehelpme** [sp614x/optifine#6165]
when I download oftifine my computer warns me that the file may hurt my computer, is this normal?

**Comment by XxMr1234GamerzxX** [comment]
if it is from http://optifine.net/ YES 

if it is from a third party i wouldn't trust it

**Comment by KaiAF** [comment]
I assume you are talking about this: 
![image](https://user-images.githubusercontent.com/60985521/129461794-ad596470-95e9-4ed7-a341-c82d2078e359.png)
If you are, yes, this is normal. Most browsers does this on all .jar and .exe files because they are executables. Just press "Keep"
