### ISSUE TITLE
[1.17.1/Forge] Crash using Forge and OptiFine

### ISSUE THREAD

**Issue by Haceau-Zoac** [sp614x/optifine#6167]
## Description of Issue
Minecraft 1.17.1.
It's OK to use Forge(37.0.33) or OptiFine(G9 Pre33) only, but using them at the same time will crash.

## Steps to Reproduce
1. Use PCL2 to download minecraft, forge and optifine.
2. Start game and crash.

## OptiFine Version
OptiFine G9 pre33

## Installation Method
Use PCL2 to download.

## Fabric/Forge Version
Forge 37.0.33

## Other Installed Mods
Only installed OptiFine.

## Log Files/Crash Reports
PCL2 report: Logs:
[ErrorReport-2021-8-15_18.11.30.zip](https://github.com/sp614x/optifine/files/6987933/ErrorReport-2021-8-15_18.11.30.zip)

## Prior Testing

- Does this happen without other mods installed? 
  Yes.
- Does this happen without any mods at all?
  No.
- Does this happen in OptiFine standalone?
  No.
- Does this happen in Vanilla without OptiFine?
  I don't know.
- Have you tried using a binary search to find which mods cause this issue?
  I only installed OptiFine.

**Comment by XiaoPangxie732** [comment]
Currently, OptiFine 1.17.1 doesn't compatible with Forge. The only way to use OptiFine with Forge currently is to use [OptiForge](https://github.com/ZekerZhayard/OptiForge)

**Comment by ZekerZhayard** [comment]
> Currently, OptiFine 1.17.1 doesn't compatible with Forge. The only way to use OptiFine with Forge currently is to use [OptiForge](https://github.com/ZekerZhayard/OptiForge)

OptiForge is under beta for now.

**Comment by Haceau-Zoac** [comment]
> Currently, OptiFine 1.17.1 doesn't compatible with Forge. The only way to use OptiFine with Forge currently is to use [OptiForge](https://github.com/ZekerZhayard/OptiForge)

I know. Thanks!

**Comment by KaiAF** [comment]
Closing this because this isn't a bug. OptiFine just isn't compatible with forge yet.

**Comment by mantlefox** [comment]
it doesnt happen without optifine i checked

**Comment by mantlefox** [comment]
also the full release isnt compatible but the first pre releases do because i was playing
