### ISSUE TITLE
Screen turns white/black by joining 

### ISSUE THREAD

**Issue by BeugelBekkie** [sp614x/optifine#617]
Hello everyone I have a question.

If I play minecraft with optifine and I join world or a server,
the screen turns white / black and only see the hud.

But if I don't play with optifine its all fine but then my fps is verry,
so I need optifine, can u people help me?

greetings from BeugelBekkie.

**Comment by bgreenlaw** [comment]
I have this same problem. I have used optifine for months on this computer and it worked fine when all of a sudden this started happening. I hope this fix this bug :/

**Comment by sp614x** [comment]
More details needed:
- other mods installed?
- custom resource pack?
- shaders enabled?
- error log (game output)?

Have you tried to reset the video settings "Video Settings -> Other -> Reset"

**Comment by BeugelBekkie** [comment]
That didnt work

**Comment by BeugelBekkie** [comment]
and now my collors are weard even in no optifine minecraft :(

**Comment by sp614x** [comment]
If the same is happening without OptiFine, then the problem is not in OptiFine.

**Comment by BeugelBekkie** [comment]
its fixed by reinstalling mc but still optifine doent work
