### ISSUE TITLE
[1.17.1 Pre34] Enchantment glint on lodestone compasses appear weirdly

### ISSUE THREAD

**Issue by Kevedsa4esan** [sp614x/optifine#6173]
## Description of Issue
The purple enchanted "glint" effect of a compass locked onto a lodestone does not appear to render correctly. It looks as if the normal texture is zoomed out a lot. This does not happen in vanilla.

![image](https://user-images.githubusercontent.com/88814793/130217551-751d41e1-05b5-4d8d-a24e-f392875d102c.png)

## Steps to Reproduce
Any compass locked onto a lodestone whilst playing in an optifine version shows this.

## OptiFine Version
Optifine 1.17.1 HD G9 pre34

## Installation Method
Installed via the jar file.

## F3 Debug Screenshot
![image](https://user-images.githubusercontent.com/88814793/130217295-50c0b1e7-219f-4cda-aef8-8f0bab48f114.png)

**Comment by fayer3** [comment]
dupllicate of #6097 and #6155
