### ISSUE TITLE
[1.17.1 Pre 34] Resource pack textures bugging (pack is New Default + 1.43

### ISSUE THREAD

**Issue by X-KILLAAAAA** [sp614x/optifine#6174]
## Description of Issue
New default + resource pack textures bugging out

## Steps to Reproduce
1. Use New Default + 1.43
2. Maybe run around light sources and other blocks? if you place a line of sea lanterns and move around them this should happen.

## OptiFine Version
1.17.1 Pre34

## Installation Method
Using Optifabric v1.11.20 (have tried reinstalling and bug persists)

## Fabric/Forge Version
Fabric 0.7.4

## OptiFabric Version
See above

## Other Installed Mods
Falling leaves v1.7.3 Charmonium 3.3.0 MaLiLib v0.10.0 Minihud 0.19.0 Mod Menu v2.0.4 And optifabric v1.11.20

## F3 Debug Screenshot
![image](https://user-images.githubusercontent.com/89323132/130337255-fa9b6a02-0597-4d34-9d3c-d590d8d77427.png)

## Prior Testing
 without optifine it works fine

## Additional Information
Not sure whats causing this and not sure how to fix it but thought posting this would be helpful :)

**Comment by X-KILLAAAAA** [comment]
ah i forgot to add screenshots sorry 
![image](https://user-images.githubusercontent.com/89323132/130337349-0f42c7b3-08f6-4248-96b7-dfde98f44db0.png)



![image](https://user-images.githubusercontent.com/89323132/130337372-958d1e70-dc24-4651-8932-ec6ce04952e3.png)

**Comment by fayer3** [comment]
Maybe related to #6093.
Also, please add a short summary to the issue title.

**Comment by KaiAF** [comment]
Try disabling anti-aliasing and anisotropic filtering

**Comment by X-KILLAAAAA** [comment]
Turning off Emissive Textures fixes this

**Comment by KaiAF** [comment]
Closing in favor of: #6174.
