### ISSUE TITLE
Optifine 1.17.1 pre 34 does not start

### ISSUE THREAD

**Issue by ItsYisusUwU** [sp614x/optifine#6175]
## Description of Issue
The game does not start with Optifine

## Steps to Reproduce
Start minecraft with the latest version of Optifine

## OptiFine Version
OptiFine HD U G9 pre34

## Installation Method
Java installation

**Comment by KaiAF** [comment]
Can you send more details? Does it crash? If so, send a crash log.

**Comment by ItsYisusUwU** [comment]
Well when starting minecraft with the Optifine pre 34 it made the game crash, and with vanilla it did not happen, I tried to start with Optifabric but the same thing happened, but with pre 35 it allows me to start minecraft and on the crash report I do not have any capture

**Comment by ftab** [comment]
Optifabric 1.11.20 fixes this for me. Is that the version of Optifabric you're running?

"Fixes running with OptiFine 1.17.1 G9_pre33 and Fabric API"

https://www.curseforge.com/minecraft/mc-mods/optifabric/files

**Comment by KaiAF** [comment]
closing this as this isnt an optifine issue, it's something with optifabric, which seems to be fixed already.
