### ISSUE TITLE
[1.13.2] OptiFine reducing FPS all of a sudden

### ISSUE THREAD

**Issue by MisterVideosoEx** [sp614x/optifine#6177]
## Description of Issue
After two days ago I only get 5FPS from OptiFine, but before that I was getting 60+ FPS. I don't know why I all of a sudden have a massive FPS drop, especially with a good PC.

## Installation Method
Optifine.net, added to mods folder

## Modloader Version
Rift v1.0.4-106

## Other Installed Mods
-MaLiLib
-Rift Mod List
-Roughly Enough Items
-Tweakeroo
-VoxelMap

## F3 Debug Screenshot (Without OptiFine)
![image](https://i.imgur.com/iKJNXHH.jpg)

## F3 Debug Screenshot (With OptiFine)
![image](https://i.ibb.co/5xKmphW/with-optifine.png)

## Additional Information
-OptiFine was working perfectly prior to two days ago, all of a sudden it started reducing FPS so I can't use OptiFine anymore
-This also seems to be happening on 1.16.5 as well (Fabric loader)

**Comment by sp614x** [comment]
Rift is not supported.
Probably a conflict with one of the mods.
