### ISSUE TITLE
[Error in chat]  OpenGL Error: 1282 (Invalid operation)

### ISSUE THREAD

**Issue by ajs256** [sp614x/optifine#6178]
## Description of Issue
In chat, I sometimes recieve a message from Optifine: `OpenGL Error: 1282 (Invalid operation)`

## Steps to Reproduce
1. Use [my VanillaTweaks resource pack](https://vanillatweaks.net/share#FD3zkV) (maybe optional)
2. Connect to a creative server or start a creative world
3. See error in chat

## OptiFine Version
OptiFine HD G9_pre34 Ultra

## Installation Method
I used the JAR installer and the vanilla launcher.

## Other Installed Mods
No other mods

## Log Files/Crash Reports
Logs are in a gist: https://gist.github.com/ajs256/06869a99c64139e7f21b9bd0893eb094

## F3 Debug Screenshot

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/67526318/130378479-48c30479-cbff-4fab-8ee1-30773b54bb54.png">

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine? **N/A, it's an optifine-specific issue**

## Additional Information
Was told to create a new issue from #2114

**Comment by Wesley51** [comment]
Settings > Video > Other > Turn "Show OpenGL errors" off.

**Comment by ajs256** [comment]
> Settings > Video > Other > Turn "Show OpenGL errors" off.

I know that, but a permanent fix would be nice.

**Comment by sp614x** [comment]
Linked to Render Regions:
```
[18:25:08] [Render thread/ERROR]: [OptiFine] OpenGL error: 1282 (Invalid operation), at: Copy VBO range
```

**Comment by Jiingy** [comment]
Closing in favor of #2548
