### ISSUE TITLE
[1.17.1 Pre34] CTD on loading chunks on launch

### ISSUE THREAD

**Issue by mrWAWAA** [sp614x/optifine#6179]
## Description of Issue
My game is crashing whenever I try and use Optifine to load saves or create a new world. It loads the game to 100% but once it gets in game and starts loading chunks it gets to a certain point and then crashes to the desktop/launcher. Launcher says it's an Exit Code 0. 

## Steps to Reproduce
1. Load Save/Create New World
2. Loads chunks to a certain point before stopping and 
3. Crashing.

## OptiFine Version
OptiFine HD U G9 pre34 (although also did this on pre32).

## Installation Method
Installed via executable file.

## Log Files/Crash Reports
[latest.log](https://github.com/sp614x/optifine/files/7031598/latest.log)
[hs_err_pid29656.log](https://github.com/sp614x/optifine/files/7031602/hs_err_pid29656.log)

## F3 Debug Screenshot
![2021-08-23_19 58 41](https://user-images.githubusercontent.com/89392201/130443404-73416a62-6310-406d-b64f-efef53ea6cce.png)

## Prior Testing
- Does this happen in Vanilla without OptiFine?
No.

## Additional Information
At first I thought it may be the Shaders, so I turned them off (although I've used these previously over a year ago with Optifine and had no issues. I also tried updating my graphics card and assigning more ram to the launcher, which didn't resolve the issue. Any help would be appreciated, I'm terrible at reading crash logs.

**Comment by Whitelisted1** [comment]
It looks like you are using a texture pack, maybe try disabling it?

**Comment by fayer3** [comment]
this looks similar to #5918, which is an issue with the resourcepack and the "Terrain Animated" option
check if this still happens with "Terrain Animated" disabled or without the resourcepack.

**Comment by mrWAWAA** [comment]
> 
> 
> this looks similar to #5918, which is an issue with the resourcepack and the "Terrain Animated" option
> check if this still happens with "Terrain Animated" disabled or without the resourcepack.

I did see this in another thread and tried this, but I still had crashes. I'll try without the texture pack and see if it helps.

**Comment by sp614x** [comment]
You can try to use a lower resolution resource pack.
