### ISSUE TITLE
[Category] Glowing effect not functioning

### ISSUE THREAD

**Issue by GatK0ng** [sp614x/optifine#6185]
## Description of Issue
Entities don't glow when given the effect.

## Steps to Reproduce
1. Launch Minecraft with OptiFine HD U G9 pre35 (and as early as at least pre33)

## OptiFine Version
OptiFine HD U G9 pre35 (and as early as at least pre33)

## Installation Method
Standalone installer on MacOs 11.5.2 (20G95)

## F3 Log
see attached

## F3 Debug Screenshot
see attached

[latest.log](https://github.com/sp614x/optifine/files/7042385/latest.log)
![2021-08-24_17 17 15](https://user-images.githubusercontent.com/60089284/130697399-8a00a2a9-7116-4151-9aff-051bd88e22a4.png)

## Prior Testing
- Does NOT happen in Vanilla without OptiFine.

**Comment by KaiAF** [comment]
Yeah this is an issue with shaders, the bug has been reported here: #6039.

**Comment by elbohrio72** [comment]
the same happens to me but I am Shure that I deactivated the shaders
![2022-12-07_01 08 45](https://user-images.githubusercontent.com/119988812/206086122-31bdbaf2-15d1-4807-b3a8-af40d3fc22cb.png)
