### ISSUE TITLE
[1.17.1 Shaders] Beacon beam and chests don't layer correctly

### ISSUE THREAD

**Issue by itzfiiishboi** [sp614x/optifine#6191]
## Description of Issue
When standing within a beacon beam while using shaders, chests+ender chests appear as if they are not being seen through a beacon beam, they appear as 8f being viewed normally

## Steps to Reproduce
1. Use optifine+shaders (I've tested with multiple)
2. position yourself within a activated beacon beam and look outwards at a chest

## OptiFine Version
Latest preview (#35)

**Comment by KaiAF** [comment]
Can you send a F3 debug screenshot? Can you send a picture of the bug?
