### ISSUE TITLE
Visual bug

### ISSUE THREAD

**Issue by reelreamy** [sp614x/optifine#6193]
I have 1 issue with minecraft i see like these cross things on signs and player names when i'm far away the closer it looks okay but the farther i go it looks weird. (the name is like weird looking i swear its not me)
![Untitled](https://user-images.githubusercontent.com/88373083/131218589-67d3b6eb-5340-4de3-a37b-d6ac67953e0d.png)
![Untitled](https://user-images.githubusercontent.com/88373083/131218627-158af0da-64ae-4778-8bef-f2d917e08775.png)

**Comment by KaiAF** [comment]
This is normal, not a visual bug. Even happens in Vanilla, its just how Minecraft renders text.

![image](https://user-images.githubusercontent.com/60985521/132047656-0e0e4720-88bd-412f-b1d2-94b6126fdca9.png)

**Comment by reelreamy** [comment]
@KaiAF no there are like x's in the names and signs, on optifine when i go in vanilla is perfectly fine. you just don't understand or dont see
