### ISSUE TITLE
[Category] Short description

### ISSUE THREAD

**Issue by Pr3data2021** [sp614x/optifine#6194]
## I cannot guarantee that the reproduction will work. However, I use a Fire Aspect I diamond sword when killing animals for food. Often I see black cows running around with completely black fire.
Walking around in the upper world and approaching animals. In the Nether Pigman, which are most often invisible.

## 
![2021-08-28_16 34 24](https://user-images.githubusercontent.com/77070960/131221600-3348426e-bcd0-4ed4-9c18-47d1e094d623.png)

## 
![2021-08-28_16 34 03](https://user-images.githubusercontent.com/77070960/131221685-4b7ad8fc-18a6-4ca7-aea7-a1eb31e4761c.png)

![2021-08-28_16 33 15](https://user-images.githubusercontent.com/77070960/131221694-46c6c0e9-4db3-4484-8cce-834de8e4bd3f.png)

**Comment by KaiAF** [comment]
Reported here: #6013
