### ISSUE TITLE
[REQUEST] Chunk cache render on Optifine 1.17.1

### ISSUE THREAD

**Issue by NovaPixell** [sp614x/optifine#6196]
In all versions of optifine there was a function that kept all chunks loaded on the client, thus bypassing the view-distance of the server.

Please add it as there was this feature in all versions of optifine

**Comment by NovaPixell** [comment]
In a discussion on your Discord it emerged that the chunk cache was never on Optifine (ok?) And that it is a vanilla feature of Minecraft, so removed.

I tried in 1.16.5 Vanilla and the Chunk Cache doesn't exist, with Optifine yes.
In 1.17.1 Optifine the Chunk Cache does not exist.

Take this issue as a request, because it is very annoying to play with the chunks that are immediately unloaded by the client.

**Comment by EireNero** [comment]
Yeah, it's awful on servers with like 6 render distance, in 1.16 you can easily take nice screenies

**Comment by sp614x** [comment]
Fixed the chunk rendering in 1.17 to behave like 1.16.5 in multiplayer.
Coming in next preview.
