### ISSUE TITLE
Feature: change mob texture based on name

### ISSUE THREAD

**Issue by CyberFoxar** [sp614x/optifine#620]
Hello,
I've been wondering if it would be possible to change the texture on a mob without altering it's model based only on its name ?
It seems to be possible using CEM, but I'm not sure.

An example would be: Naming a wolf "Dark" would replace its texture with a texture of my choice (like a an inverted color scheme).

Thanks !

**Comment by MisterQuiggly** [comment]
You can do this by making a mobs folder in a mcpatcher folder which is located in the minecraft folder in your resourcepack. all you have to do is, for example, make multiple files for the mob like a wolf or anything. You cannot do it with custom names though. You can do randomized, by biome, by height, and stuff like that. 
More info: https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/mob.properties

**Comment by CyberFoxar** [comment]
Yes, I've seen that. And it led me to think that, adding a name property wouldn't be too hard. Heck, I might try and add it to the repo here, when I'll be better.

I actually have a use case for such a feature, and it would be nice to see it added.

**Comment by sp614x** [comment]
Updated preview C7 for 1.12.2
- added Random Mobs check by name: https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/mob.properties#L82
