### ISSUE TITLE
 Constant Framerate drops due to OpenGL Error: 1282 (Invalid operation) 

### ISSUE THREAD

**Issue by seednhy346** [sp614x/optifine#6201]
## Description of Issue
 Starting from pre34, pre35 and then HD U G9 I keep getting framerate drops due to OpenGL Error: 1282 (Invalid operation) It doesn't matter if I turned off Show OpenGL errors because even with that option turned off, I still get sudden freezes. For now I would stick to pre33 because it is the most stable for me. I would upgrade to the latest version if this bug would be fixed.

## OptiFine Version
 1.17.1 pre34,pre35 and 1.17.1 HD U G9

## Installation Method
 Standalone

## F3 Debug Screenshot
 
![2021-08-31_16 29 56](https://user-images.githubusercontent.com/81794140/131471304-d1ca8225-8d35-45ef-aa35-d317ed54e4af.png)
![2021-08-31_15 45 26](https://user-images.githubusercontent.com/81794140/131471512-63d05827-41f9-449a-bdfc-f75238abaeb6.png)
![2021-08-31_15 46 57](https://user-images.githubusercontent.com/81794140/131474750-cd928902-e158-42bc-bd05-62752b61f2cf.png)

**Comment by KaiAF** [comment]
this is most likely happening due to outdated drivers. You can try updating them to see if that helps, but old integrated GPU's like that usually have issues like this. Not something optifine can fix, unfortunately

**Comment by seednhy346** [comment]
No. It can be fixed! OpenGL Error: 1282 (Invalid operation) isn't spamming on my chat if I'm on Optifine 1.17.1 pre 33. Somehow versions like pre 34 pre 35 and HD U G9 have this type of error. But they're both the same 1.17.1 versions. And in fact the vanilla version is unironically less laggy for me and has more fps. All my drivers are updated. I think this has something to do with https://github.com/sp614x/optifine/issues/6187 https://github.com/sp614x/optifine/issues/6178 Same issue for me. I will provide some logs here 
[2021-08-31-2.log.gz](https://github.com/sp614x/optifine/files/7087373/2021-08-31-2.log.gz)
[2021-08-31-5.log.gz](https://github.com/sp614x/optifine/files/7087375/2021-08-31-5.log.gz)

**Comment by seednhy346** [comment]
Update https://github.com/sp614x/optifine/issues/6205
