### ISSUE TITLE
[UPDATED] [CHAT ERROR] OpenGL Error: 1282 (Invalid operation)

### ISSUE THREAD

**Issue by seednhy346** [sp614x/optifine#6205]
## Description of Issue
 The problem is OpenGL Error: 1282 (Invalid operation) keeps spamming in my chat if I'm on pre34 pre35 and HD U G9. But if I'm on pre33 and below no such problem would happen. It doesn't matter if I ever  turn off open gl errors because they would be still logged in the error log and cause framerate drop.

## OptiFine Version
 1.17.1 HD U G9

## Installation Method
 Standalone

## Log Files/Crash Reports
 https://pastebin.pl/view/c41f7c3d

## F3 Debug Screenshot

![2021-09-01_16 32 55](https://user-images.githubusercontent.com/81794140/131643629-71c6d030-5516-4a46-8a28-210719955edb.png)
![2021-09-01_16 36 33](https://user-images.githubusercontent.com/81794140/131643750-71325cd9-9189-4178-a72a-134b514f3f8f.png)
![2021-09-01_16 47 16](https://user-images.githubusercontent.com/81794140/131643840-552fb16e-0422-47f3-a625-1983d59aa3da.png)

## Prior Testing
 Q: Does this happen in Vanilla without OptiFine? A: No

**Comment by Regnander** [comment]
I'd recommend to continue posting on your previous issue at #6201 instead of creating new issues on the same subject. If you just want to add more information, you can edit the original post on said issue.

**Comment by seednhy346** [comment]
Can you remove or delete https://github.com/sp614x/optifine/issues/6201? Just don't delete https://github.com/sp614x/optifine/issues/6205 because it is the final. Sorry I'm just new to this.

**Comment by Regnander** [comment]
Don't worry about it! If you scroll down to the bottom of the page you can find a button that says "Close Issue".

**Comment by seednhy346** [comment]
Thank you I now closed it.

**Comment by KaiAF** [comment]
If you are not having any actual visual issue, you can disable the error. The reason why it wasn't happening in pre33 was because the developer removed the fallback for OpenGL in later versions.

> https://github.com/sp614x/optifine/issues/5739#issuecomment-902901134

I am going to close the issue as this isn't something that OptiFine can fix.

**Comment by Derpercoaster** [comment]
I know this issue is closed, but I do have a solution. At least one that worked for me.
In the "Performance" tab, disable "Render Regions" and "Smooth FPS". Both of these conflicted with my PC (the former with the graphics card, the latter with software), and turning them off fixed the issue, both in terms of lag and the GL error messages.
