### ISSUE TITLE
[Grahpical Glitch] Leash is connected to entities it shouldn't be.

### ISSUE THREAD

**Issue by MenschenToaster** [sp614x/optifine#6207]
## Description of Issue
When you and another player leash two different invisible entities(in my case two different chickens) they are leashed correctly but there is another leash connecting the two entites that should not be there and is not there on vanilla.

Here is an Image: ![Download](https://user-images.githubusercontent.com/54715954/131723427-0335be84-97f1-4218-bb8a-448474af9750.png)

## Steps to Reproduce
1. Spawn a chicken
2. Make it invisible
2. Leash it
3. Go to the second account
4. Spawn a second chicken
5. Make it invisible
6. Leash it
7. Make sure both players are visible and you will see the line connecting the two that should not be there

## OptiFine Version
1.17 Optifine HD G9 Ultra

## Installation Method
Standalone installer

## Log Files/Crash Reports
There are no releavant information in the logs. Only join, creative mode etc.

## F3 Debug Screenshot
![image](https://user-images.githubusercontent.com/54715954/131724044-c89dec5c-64a6-41bd-9a5d-1dab8da815e3.png)

## Prior Testing
- Does this happen in Vanilla without OptiFine?
  Could not reprocude.

**Comment by KaiAF** [comment]
If this was reproducible in vanilla, then it is a Minecraft bug
