### ISSUE TITLE
Model rendering issue

### ISSUE THREAD

**Issue by p4ndepravity** [sp614x/optifine#621]
Minecraft version 1.10.2
Forge 12.18.3.2254
OptiFine_1.10.2_HD_U_D7

console paste https://paste.ee/p/vv9Np

picture of issue: http://imgur.com/a/SeO4W
  wireless redstone transmitters and receivers are not rendering

another picture: http://imgur.com/a/SeO4W
  this block should be a malisis door factory

Everything was working fine after I installed Optifine for about a week. Suddenly several models would not render in the world or in inventory. I have tried disabling custom items, tweaking chunk rendering settings, etc. to no avail. Not sure what to try from here. When I remove OptiFine, everything renders correctly, but I prefer to use OptiFine because of immense lag without it. Any suggestions would be greatly appreciated.

Thanks

**Comment by sp614x** [comment]
You can try to reset the Video Settings.
"Video Settings -> Other -> Reset"

**Comment by sp614x** [comment]
The console paste has many, MANY errors from different mods complaining about missing textures, broken models, invalid configurations, etc. It is not possible to find what went wrong.

**Comment by mindforger** [comment]
he could possibly update it's GFX driver, it is from 08.2016 i remember an driver issue in that time area
