### ISSUE TITLE
Crash on 1.17.1 launch

### ISSUE THREAD

**Issue by rbrajcich** [sp614x/optifine#6210]
Just picked up the new 1.17.1 stable "OptiFine HD U G9" to upgrade, since I've been running 1.16.5. Without optifine, 1.17.1 runs fine. Once I installed optifine and selected it in the launcher, the game consistently fails to launch, with this as the only error message:

![image](https://user-images.githubusercontent.com/22357699/131904714-52d00396-ac9e-43ac-99e7-d29dc338224e.png)

It doesn't even make it to the point of displaying the menu screen. It occurs very quickly after clicking play in the launcher before the game window even opens.

I'm not sure how to acquire appropriate logs- there is no folder in my ./.minecraft called crash-reports.
I modified the launcher options to show the logs window and this is all I see:

13:28:08.483 launcher main Preparing to launch minecraft client for 1.17.1-OptiFine_HD_U_G9
13:28:08.484 launcher main Prepared asset index
13:28:08.926 launcher main Have 3072 total files to check or download
13:28:08.930 launcher main Waiting for 3072 futures
13:28:09.230 launcher main Couldn't fetch SHA1 checksum for https://libraries.minecraft.net/optifine/launchwrapper-of/2.2/launchwrapper-of-2.2.jar
13:28:09.232 launcher main Couldn't fetch SHA1 checksum for https://libraries.minecraft.net/optifine/OptiFine/1.17.1_HD_U_G9/OptiFine-1.17.1_HD_U_G9.jar
13:28:09.240 launcher main Have local file C:\Users\\\<me>\AppData\Roaming\.minecraft\libraries\optifine\OptiFine\1.17.1_HD_U_G9\OptiFine-1.17.1_HD_U_G9.jar but don't know what size or hash it should be. Have to assume it's good.
13:28:09.259 launcher main
Have local file C:\Users\\\<me>\AppData\Roaming\.minecraft\libraries\optifine\launchwrapper-of\2.2\launchwrapper-of-2.2.jar but don't know what size or hash it should be. Have to assume it's good.
13:28:09.260 launcher main Checking installations.
13:28:09.261 launcher main Minecraft client 1.17.1-OptiFine_HD_U_G9 is ready to start.
13:28:09.261 launcher main Starting!
13:28:09.261 launcher main Nothing to download!
13:28:09.261 launcher main Downloading Java Runtime java-runtime-alpha:16.0.1.9.1
13:28:09.390 launcher main Extracting 8 files!
13:28:09.845 launcher main Using default game log configuration client-1.12.xml (outputs XML)
13:28:09.845 launcher main Installing versions!

**Comment by TwelvianZeta** [comment]
I'm guessing this is what happens when you try installing optifine using java 8

**Comment by fayer3** [comment]
does vanilla 1.17.1 run? from the error it sounds like your java runtime is corrupted.

**Comment by rbrajcich** [comment]
> I'm guessing this is what happens when you try installing optifine using java 8

Just tried re-installing optifine running the installer with java 16. The error still occurs

> does vanilla 1.17.1 run? from the error it sounds like your java runtime is corrupted.

Vanilla 1.17.1 runs fine, this is only an issue when I use the optifine launcher configuration

**Comment by KaiAF** [comment]
Interesting. Try going to the Minecraft launcher and editing the OptiFine installation to use Java 16, not the pre-bundled version.

**Comment by rbrajcich** [comment]
Sorry for the delay, I just tried forcing the optifine installation to use java 16 but the issue persists

**Comment by KaiAF** [comment]
Does it still happen when you open command prompt and paste this: `"C:\Program Files\Java\jdk-16.0.1\bin\javaw.exe" -jar OptiFine-1.17.1_HD_U_G9.jar`?

You have to open command prompt wherever the OptiFine jar file is located in.

**Comment by rbrajcich** [comment]
Thanks for getting back on this. Yes, I just tried reinstalling optifine using the above command (completely identical except that my 'jdk-16.0.1' is 'jdk-16.0.2', but I can't imagine that would matter) and I still experience the crash on startup.

**Comment by rbrajcich** [comment]
I was able to solve this with a reinstall of minecraft (wiping out my %appdata%/.minecraft folder and then booting up the launcher to let it re-download all the game data), then re-installing optifine.
