### ISSUE TITLE
[Settings] Description of options in settings GONE

### ISSUE THREAD

**Issue by epic-person** [sp614x/optifine#6211]
## Description of Issue
 In 1.17.1 HD U G9, when you open video settings ingame and hover over an option, the description of the option will not appear unlike 1.16.5 OptiFine.

## Steps to Reproduce
1. open settings ingame
2. go to video settings
3. hover the mouse over an option

## OptiFine Version
 1.17.1 HD U G9

## Installation Method
included standalone

## Prior Testing
 it existed in the latest 1.16.5 version but its gone

**Comment by KaiAF** [comment]
You seem to be correct.

**Comment by sp614x** [comment]
Fixed in H3 for 1.18

**Comment by sp614x** [comment]
1.17 will be fixed on next update
