### ISSUE TITLE
[LIGHTING] Textures flickering black in 1.171.1 U G9

### ISSUE THREAD

**Issue by Punity122333** [sp614x/optifine#6212]
## Description of Issue
Sometimes, the textures of entities flicker black and my skin (+items in first person view) turn invisible. This happens randomly with no pattern to it at all.

## Steps to Reproduce
1. Turn internal shaders off.
2. It happens for me, theres no other steps

## OptiFine Version
Optifine 1.17.1 HD U G9

## Installation Method
I used the standalone installer.

## Log Files/Crash Reports
No log files.

## F3 Debug Screenshot
![2021-09-03_09 32 02](https://user-images.githubusercontent.com/66818808/131948891-adb0e0e5-8f4f-4dc1-a2be-6bd139c56db0.png)

## Prior Testing
No, this doesn't happen in Vanilla.

**Comment by KaiAF** [comment]
With what you are describing with, it's already reported here: #6013.
