### ISSUE TITLE
Immediate crash on modded 1.17.1

### ISSUE THREAD

**Issue by perfectpear** [sp614x/optifine#6214]
## Description of Issue
When starting OptiFine 1.17.1 HD U G9 it immediately crashes with exit code 0 i am using CurseForge with 2 mods installed on the CurseForge launcher i have tried disabling both mods but it still crashes

## Steps to Reproduce
1. Launch OptiFine HD U G9 using CurseForge launcher
2. Crash

## OptiFine Version
OptiFine 1.17.1 HD U G9

## Installation Method
Went to optifine.net downloaded the newest version and moved it to my mods folder

## Fabric/Forge Version
Forge 37.0.53 (Currently Newest)

## Other Installed Mods
WorldEdit 7.2.6
World Handler - Command GUI 2.12.6

## Log Files/Crash Reports
[2021-09-03-4.log](https://github.com/sp614x/optifine/files/7108979/2021-09-03-4.log)

## F3 Debug Screenshot
Can't get in-game

## Prior Testing
 Yes

## Additional Information
I am using the CurseForge/Overwolf launcher if it helps i have a dell optiplex 7010 with a core i7 and AMD HD 7570 and 16 GB of ram and 2tb of storage and the latest version of Java and OpenGL

**Comment by Cart3r1234** [comment]
Optifine currently isn't compatible with forge (unless you use [optiforge](https://www.curseforge.com/minecraft/mc-mods/optiforge))

**Comment by perfectpear** [comment]
> 
> 
> Optifine currently isn't compatible with forge (unless you use [optiforge](https://www.curseforge.com/minecraft/mc-mods/optiforge))

Thanks!
