### ISSUE TITLE
Optifine hides my migration cape even though I don't have an optifine one

### ISSUE THREAD

**Issue by SuperDuggy117** [sp614x/optifine#6224]
My ign is the same as my GitHub username.
I migrated from a mojang account to a microsoft account recently and got my free migration cape. However, if I play with the optifine mod installed, it hides the cape from my view. I've heard that going to the cape editor and disabling your optifine cape fixes this, but I don't _own_ an optifine cape, so I can't even access the menu. Please help.

**Comment by KaiAF** [comment]
Go to settings > Video Settings > Details > Show Capes. See if it is set to ON

**Comment by SuperDuggy117** [comment]
oh... I didn't even realize that was a setting...
well THAT fixes the issue. Thanks! :)
