### ISSUE TITLE
cit is not working

### ISSUE THREAD

**Issue by TomXel** [sp614x/optifine#6226]
i really don't know what to explain or to do, i've tried everything and i am using the latest 1.17.1 optifine version, hd u g9
[pack.zip](https://github.com/sp614x/optifine/files/7115862/pack.zip)

**Comment by Exspactor** [comment]
I have looked into your pack and basically you need to make sure that "nbt.display.name" in the .properties file is written like "nbt.display.Name" other than that i think you are doing everything correctly

**Comment by ZenIsBestWolf** [comment]
Not a bug, contact support if the above reply does not help you.
