### ISSUE TITLE
Different GUIs for the different colors of shulker boxes

### ISSUE THREAD

**Issue by sp614x** [sp614x/optifine#623]
Each color shulker box could get a different GUI texture.

**Comment by Madis0** [comment]
Apparently doable in vanilla: https://www.curseforge.com/minecraft/texture-packs/shulker-box-guis

**Comment by sp614x** [comment]
Already implemented: https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/custom_guis.properties#L165

@Madis0 the resource pack uses OptiFine's CustomGuis, vanilla doesn't have GUI customization.
