### ISSUE TITLE
Crashes On Alt Tab

### ISSUE THREAD

**Issue by Supacrafter** [sp614x/optifine#6233]
## Steps to Reproduce
1. Once ingame I alt tab
2. End

## OptiFine Version

1.17.1
## Installation Method

Used the .jar file installer

## Log Files/Crash Reports

[2021-09-07-7.log.gz](https://github.com/sp614x/optifine/files/7125057/2021-09-07-7.log.gz)

## F3 Debug Screenshot

![2021-09-07_21 14 36](https://user-images.githubusercontent.com/61219283/132430039-46bc3764-2427-4d2a-99e1-65d1c52348b1.png)

## Additional Information

Anytime I alt tab I get exit code 0, Doesnt happen while in windowed mode

**Comment by KaiAF** [comment]
Is the log the right one? Looks like (maybe shaders?) is trying to load modded items. Like biomes o' plenty and farmersdelight. Weird

**Comment by Supacrafter** [comment]
Sorry for late response, super busy with school. Prob from my shaders, might be also from server I was playing on.
