### ISSUE TITLE
[Random Entities][Suggestion]New Random Entity Condition: saddle

### ISSUE THREAD

**Issue by WeegeeTheDoggo** [sp614x/optifine#6234]
This would work for any mob that can be saddled, changing their texture if they have a saddle equipped.
The documentation would be something like this:

Saddle (optional)
Only valid for mobs which can be saddled
saddle.\<n>=\<true/false>

**Comment by ZenithRogue** [comment]
iirc you should be able to use a saddle with random entities already?

**Comment by WeegeeTheDoggo** [comment]
> iirc you should be able to use a saddle with random entities already?

Yes, you can. However I'm thinking of an instant texture change whenever the mob is saddled. Let's say.. You make a robot horse texture. Adding a saddle would add a "seat", but with this new condition, the horse would also change its base texture (not the saddle) to look Powered on and ready to be "driven"

**Comment by ewanhowell5195** [comment]
you can now use the nbt detection to detect when a saddle is applied
