### ISSUE TITLE
[1.17.1 Shaders] Shaders significantly drops fps

### ISSUE THREAD

**Issue by Phoenix00Birb** [sp614x/optifine#6239]
## Description of Issue
On all 1.17.1 OptiFine versions, shaders lag my game enough to the point where its hard to play. The fps bounces around a lot and its rather frustrating. My fps without shaders has dropped too, but not enough to change gameplay much. I'm currently using AstraLex shaders and The Find Overground 1.17 resource pack, and have experimented with different shaders and resource packs with no luck. For some reason also, it runs better underground than on the surface? When looking straight down my frames get better, but as soon as I look back up they drop again.

## Steps to Reproduce
1. Load any 1.17.1 OptiFine version
2. Apply any shader

## OptiFine Version
Tested with OptiFine HD U G9 and preview_OptiFine_1.17.1_HD_U_G9_pre33

## Installation Method
Included installer

## F3 Debug Screenshot
In preview_OptiFine_1.17.1_HD_U_G9_pre33
Flying
![2021-09-09_18 08 01](https://user-images.githubusercontent.com/87458710/132784428-d682b37f-ad16-4dd6-a1a1-ebdca0b149ae.png)
On ground
![2021-09-09_18 08 30](https://user-images.githubusercontent.com/87458710/132784450-070acad4-0043-4226-8b7d-518f5f636678.png)
Underground
![2021-09-09_18 08 52](https://user-images.githubusercontent.com/87458710/132784469-4b0d3ce7-59f6-45ed-9ed6-c5fce9b890f0.png)

In preview_OptiFine_1.17.1_HD_U_G9_pre33 with AstraLex shaders
Flying
![2021-09-09_18 10 03](https://user-images.githubusercontent.com/87458710/132784531-5756b56e-c648-41b8-b2c7-cd4b2f8de02c.png)
On ground
![2021-09-09_18 10 13](https://user-images.githubusercontent.com/87458710/132784575-9adce358-bfc7-4fe9-802a-5fab71b591ff.png)
Underground
![2021-09-09_18 11 26](https://user-images.githubusercontent.com/87458710/132784631-03821ace-be23-4cb4-bb90-374d3f181b22.png)

In OptiFine HD U G9
Flying
![2021-09-09_18 17 45](https://user-images.githubusercontent.com/87458710/132784716-cb5c7a17-5ba1-4e5d-b30d-3d58caee98c2.png)
On ground
![2021-09-09_18 18 03](https://user-images.githubusercontent.com/87458710/132784734-38286e6d-c8ab-4d29-9476-2ae1b72af75e.png)
Underground
![2021-09-09_18 18 26](https://user-images.githubusercontent.com/87458710/132784782-a5fc1d6d-1320-4119-a1a7-e273330a9382.png)

In OptiFine HD U G9 with AstraLex shaders
Flying
![2021-09-09_18 20 43](https://user-images.githubusercontent.com/87458710/132784833-a5295b2e-3d09-4022-aee6-3c18bfdd71e1.png)
On ground
![2021-09-09_18 22 24](https://user-images.githubusercontent.com/87458710/132784858-6dac9e0c-f5d7-4574-9408-8446cb2fcd86.png)
Underground
![2021-09-09_18 22 52](https://user-images.githubusercontent.com/87458710/132785099-743e5d60-2d78-45e9-ae23-f2c8f2c572b0.png)

## Prior Testing
In vanilla
Flying
![2021-09-09_18 03 46](https://user-images.githubusercontent.com/87458710/132785147-b9f1c06c-dbe3-4433-93be-567587bcc7cf.png)
On ground
![2021-09-09_18 04 12](https://user-images.githubusercontent.com/87458710/132785159-dbfc1695-5942-483c-96c6-5aa510201992.png)
Underground
![2021-09-09_18 04 38](https://user-images.githubusercontent.com/87458710/132785184-f4ac2861-9c84-443a-91fe-07e83ebb3216.png)

## Additional Information
Before 1.17, I'd get around 60 average frames at all times, occasional lag spikes on servers caused by my poor WiFi, but perfect other than that. I used mostly Sildur's Vibrant shaders v1.283 Medium then, but when tested with this issue, I had the same problem.

**Comment by eljugador003** [comment]
Your problem is that if you see what graphics card the optifine Minecraft is using is not the same that the vanilla one. Try to make the Java you use with optifine,run with the high performance one.

**Comment by eljugador003** [comment]
https://discord.com/channels/423430686880301056/531622141393764352/870841901178322985 here is the fix. If you click the link is gonna take to the #Faq of optifine discord.

**Comment by Lythael** [comment]
> https://discord.com/channels/423430686880301056/531622141393764352/870841901178322985 here is the fix. If you click the link is gonna take to the #Faq of optifine discord.

Something is wrong with that link cause it takes me to a blank channel with nothing in it.

**Comment by eljugador003** [comment]
Q: **I have a powerful graphics card, but Minecraft keeps using integrated graphics. How do I fix this?**

A: These instructions will only work for Windows 10.

The solution to this changes slightly based on what version of Minecraft you are running.

1. Open Settings.
2. Press System.
3. Press Display.
4. Scroll to "Graphics settings".
5. Press Browse.

6. Determine your Minecraft version.
- If you want to play on **1.17+**: Add Minecraft's Java under ``C:\Program Files (x86)\Minecraft Launcher\runtime\java-runtime-alpha\windows-x64\java-runtime-alpha\bin\javaw.exe``
- If you want to play on anything **below 1.17**: Add Minecraft's Java under ``C:\Program Files (x86)\Minecraft Launcher\runtime\jre-legacy\windows-x64\jre-legacy\bin\javaw.exe``

7. Press Options and select "High Performance".

For video instructions, select the video based on your version. A copy of text instructions are found in the description.

On 1.16 or below? Go here: https://youtu.be/x1bX0tR-rUo
On 1.17 or above? Go here: https://youtu.be/gSJW4ici8pQ

**Comment by Phoenix00Birb** [comment]
> https://discord.com/channels/423430686880301056/531622141393764352/870841901178322985 here is the fix. If you click the link is gonna take to the #Faq of optifine discord.

Oh my god its so much better, thank you so much. I've been having this issue for a while and its been driving me insane. Again, thank you so much! Have an amazing rest of your day/night (:
