### ISSUE TITLE
Worlds not opening with Optifine

### ISSUE THREAD

**Issue by YellowRabbit647** [sp614x/optifine#6240]
## Steps to Reproduce
1. Open Minecraft with Optifine/a loader with Optifine installed
2. Load a Minecraft world

**Comment by Regnander** [comment]
What version of OptiFine are you using? Is it G9 for 1.17.1?

**Comment by YellowRabbit647** [comment]
Yes, I am using G9 for 1.17.1

Em dom, 12 de set de 2021 07:50, A. Regnander ***@***.***>
escreveu:

**Comment by KaiAF** [comment]
Can you send a latest.log file? Go to `.minecraft\logs`. This could help

**Comment by YellowRabbit647** [comment]
I've solved the problem already. Sorry not to inform you about this, it was
a problem with Java that I installed a newer version and Optifine stopped
working. I had to reinstall both in order for them to work.

Em qua, 15 de set de 2021 19:52, Iris ***@***.***> escreveu:

**Comment by KaiAF** [comment]
Okay
