### ISSUE TITLE
[1.17.1] The letters on the sign are covered with black.

### ISSUE THREAD

**Issue by BLT-08** [sp614x/optifine#6241]
## Description of Issue
 The ttf font resource pack and shader cover the sign in black. Also, the color of NameTag is red.

## OptiFine Version

Release OptiFine 1.17.1_HD_U_G9

## Installation Method
 standalone installer

## Prior Testing
 Does this happen in Vanilla without OptiFine? No

**Comment by Regnander** [comment]
Please upload a screenshot with the F3 screen activated. A screenshot of a sign to depict the problem at hand could also be helpful.

**Comment by BLT-08** [comment]
![2021-09-13_02 50 17](https://user-images.githubusercontent.com/90527736/132997696-d79ff673-ae51-43ed-bd53-8fa21fb4ec38.png)
![2021-09-13_02 51 31](https://user-images.githubusercontent.com/90527736/132997698-56166ade-83e1-423c-af62-a2a24fd3bfb1.png)

This is a screenshot of the bug I described.

**Comment by BLT-08** [comment]
> Please upload a screenshot with the F3 screen activated. A screenshot of a sign to depict the problem at hand could also be helpful.

![2021-09-13_02 50 17](https://user-images.githubusercontent.com/90527736/132997696-d79ff673-ae51-43ed-bd53-8fa21fb4ec38.png)
![2021-09-13_02 51 31](https://user-images.githubusercontent.com/90527736/132997698-56166ade-83e1-423c-af62-a2a24fd3bfb1.png)

This is a screenshot of the bug I described.

**Comment by KaiAF** [comment]
Addressed here: #6138.

**Comment by MRuNanM** [comment]
In #6241, the text on the sign looks red, but the sign is completely black here.
