### ISSUE TITLE
Optifine not working with Forge

### ISSUE THREAD

**Issue by MeMadMax** [sp614x/optifine#6242]
## Description of Issue
Minecraft 1.17.1 with forge 1.17.1 profile crashes with Optifine 1.17.1 jar in mods folder

## Steps to Reproduce
Install Forge
Install optifine
Run minecraft with forge profile and optifine jar in the forge mods folder
Minecraft crashes at the very beginning of startup (exit code 0)

## OptiFine Version
1.17.1

## Installation Method
Both, in order to use forge

## Fabric/Forge Version
1.17.1

## Other Installed Mods
None 

## Log Files/Crash Reports
Included

## Prior Testing

- Does this happen in Vanilla without OptiFine?
- No

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   - Only OptiFine and Forge Yes
   
- Does this happen without any mods at all?
   - Only Forge/Fabric by itself. Yes
   - 
- Does this happen in OptiFine standalone?
- No
- Does this happen in Vanilla without OptiFine?
- No

   - Does the issue still happen with only the remaining mods installed?
      - Forge/Fabric and remaining mods, without OptiFine -->

## Additional Information
Clean install of  latest minecraft java and java 64bit
[debug-1.log.gz](https://github.com/sp614x/optifine/files/7148555/debug-1.log.gz)
[debug.log](https://github.com/sp614x/optifine/files/7148556/debug.log)

Will test Java 32bit just in case
[launcher_cef_log.txt](https://github.com/sp614x/optifine/files/7148551/launcher_cef_log.txt)

**Comment by Cart3r1234** [comment]
Optifine is currently incompatible with forge 1.17; you need to use [optiforge ](https://www.curseforge.com/minecraft/mc-mods/optiforge)

**Comment by MeMadMax** [comment]
> 
> 
> Optifine is currently incompatible with forge 1.17; you need to use [optiforge ](https://www.curseforge.com/minecraft/mc-mods/optiforge)

Ok, thanks a bunch, you can close this or delete if needed.
