### ISSUE TITLE
[Bug] Entities turning black. Players turning invisible.

### ISSUE THREAD

**Issue by KatCoder9** [sp614x/optifine#6243]
## Description of Issue
In newer versions of OptiFine, there's this annoying glitch where entities (and tile entities!) turn black and all players turn invisible except for items they are holding and armour, and translucent blocks and other entities don't render behind these invisible players. The glitch appears to happen mostly in newly loaded chunks and doesn't seem to happen when the chunk has been loaded for long enough by the client, and the camera and player isn't moving.

## Steps to Reproduce
1. Download OptiFine 1.17/1.17.1
2. Go into a creative world in F5, then fly far away and spawn entities in, the entities should turn black and the player should turn invisible.

## OptiFine Version
1.17, 1.17.1

**Comment by KaiAF** [comment]
Duplicate issue of the current pinned one: #5891.
