### ISSUE TITLE
Hangs on Building Terrain 1.11.2-forge1.11.2-13.20.0.2296

### ISSUE THREAD

**Issue by schismatix** [sp614x/optifine#625]
Originally when upgraded to 1.11.2-forge1.11.2-13.20.0.2296 it crashed with all mods present. Removed all mods added them 1 by one and found optifine causing crash. Now hangs as Building terrain and have to alt tab out. It gave the following crash report:

https://pastebin.com/wLZc44bL

1.11.2-forge1.11.2-13.20.0.2294 works ok

This post on forge forums reports same crash: http://www.minecraftforge.net/forum/topic/56039-1112-ticking-block-entity-crash-on-spawn/

**Comment by mben42** [comment]
I confirm this issue, using MultiMC launcher.
[crash-2017-05-07_16.01.35-server.txt](https://github.com/sp614x/optifine/files/981633/crash-2017-05-07_16.01.35-server.txt)

**Comment by Endmateria** [comment]
Does this still happen with the newest optifine preview (1.11.2 HD U B9)?  It was happening to me yesterday (Forge 2296, Optifine 1.11.2 HD U B8)

**Comment by schismatix** [comment]
Using  optifine preview (1.11.2 HD U B9) with forge 2296 still hangs on building terrain.

**Comment by sp614x** [comment]
Updated preview B9 with a fix.
The relevant Forge change: https://github.com/MinecraftForge/MinecraftForge/pull/3873

**Comment by mezz** [comment]
@sp614x out of curiosity, how did change this conflict with Optifine?

**Comment by sp614x** [comment]
OptiFine overwrites some base classes and in order to work with Forge it has to add all Forge changes.
In this case Forge added a new method to the Profiler class which was missing in the OptiFine version.

**Comment by mezz** [comment]
Hm ok. Can you use ASM hooks instead of overwriting base classes, for compatibility?

**Comment by sp614x** [comment]
The changes are too complex for ASM.

**Comment by mezz** [comment]
Uh sure. I guess I won't worry about it then.
This is caused by the same thing, replacing the class and not updating for Forge changes: https://github.com/sp614x/optifine/issues/518
