### ISSUE TITLE
[CEM, jpm] Not all jpm parts are displayed 1.17.1

### ISSUE THREAD

**Issue by w11shes** [sp614x/optifine#6251]
## Description of Issue

In version 1.17.1, all additional jpm parts of the object, except for the last one, are no longer displayed. I tried to write to the Discord server and look for a solution to the problem on GitHub, but I couldn't find a solution.

## Steps to Reproduce

Here is the resource pack for this issue, you need to rename the iron golem to "Goblin Boss":
[goblin_boss.zip](https://github.com/sp614x/optifine/files/7165096/goblin_boss.zip)

## OptiFine Version

OptiFine HD U G9

## Installation Method

optifine.net/downloads

![IMG_20210821_223240_428](https://user-images.githubusercontent.com/90721388/133333538-e20a96e2-3af4-45a8-9c6e-2e25f60b6503.jpg)

**Comment by Sonlein** [comment]
I have the same issue

**Comment by ZenithRogue** [comment]
duplicate of #5793
