### ISSUE TITLE
Shadowplay (Geforce Experience) cant record with optifine

### ISSUE THREAD

**Issue by Tehqy** [sp614x/optifine#6256]
## Description of Issue
Hi

Here is the problem. I wanted to record using Geforce Experience, but every time I try to record it says "A supported game is required to use this feature" But when I use Vanilla everything works....

## Steps to Reproduce
I press Alt+F9

## OptiFine Version
Optifine HG G9 Ultra

## Installation Method
Standalone

## Prior Testing
-No. Only happens with optifine

## Additional Information
Sorry if this is the wrong place

**Comment by fayer3** [comment]
works for me without issues. Are you using the vanilla launcher?
it also might be that the game is not using your nvidia gpu. can you post a F3 screenshot so we can see what the game is using?

**Comment by Tehqy** [comment]
Hey! Here is the screenshot 
![2021-09-19_13 29 09](https://user-images.githubusercontent.com/90979039/133924160-00289c5d-3817-4f2c-b053-66321d2be514.png)

**Comment by fayer3** [comment]
here from the otifine discord FAQ, that should help:
```
Q: I have a powerful graphics card, but Minecraft keeps using integrated graphics. How do I fix this?

A: These instructions will only work for Windows 10.

The solution to this changes slightly based on what version of Minecraft you are running.

1. Open Settings.
2. Press System.
3. Press Display.
4. Scroll to "Graphics settings".
5. Press Browse.

6. Determine your Minecraft version.
- If you want to play on 1.17+: Add Minecraft's Java under C:\Program Files (x86)\Minecraft Launcher\runtime\java-runtime-alpha\windows-x64\java-runtime-alpha\bin\javaw.exe
- If you want to play on anything below 1.17: Add Minecraft's Java under C:\Program Files (x86)\Minecraft Launcher\runtime\jre-legacy\windows-x64\jre-legacy\bin\javaw.exe

7. Press Options and select "High Performance".

For video instructions, select the video based on your version. A copy of text instructions are found in the description.

On 1.16 or below? Go here: https://youtu.be/x1bX0tR-rUo
On 1.17 or above? Go here: https://youtu.be/gSJW4ici8pQ
```

**Comment by Tehqy** [comment]
Hello

actually a minute before you replyed I figured it out. Eveyrhing works now. I switched to Nvidia GPU now I used this video: https://www.youtube.com/watch?v=Wts8-30ygyw

**Comment by fayer3** [comment]
good, if it works now you can close this issue
