### ISSUE TITLE
[1.17-  1.17.1 Bug] Optifine: BetterGrass texture not found

### ISSUE THREAD

**Issue by Silmarost** [sp614x/optifine#6259]
## Description of Issue
Hi, This bug is an error of optifine on the latest version of minecraft 1.17.1 that we can see in the "minecraft game output".
The problem is precisly this line wich could break a function of optifine in this version:
[OptiFine] BetterGrass: Parsing default configuration optifine/bettergrass.properties
17:18:50.348
net.optifine.Config
Worker-Main-51
[OptiFine] BetterGrass texture not found: minecraft:textures/block/grass_path_top.png
17:18:50.349
net.optifine.Config
Worker-Main-51
[OptiFine] BetterGrass texture not found: minecraft:textures/block/grass_path_side.png

The problem occurs because mojang have change in 1.17 this ID of **grass_path** into **dirt_path** so like the texture have changed into **dirt_path_side** & **dirt_path_top** this error occurs.

## Steps to Reproduce
We can see it on minecraft 1.17.1 (or 1.17) with "minecraft game output" open.

## OptiFine Version
OptiFine HD U H1 pre1

## Installation Method
Use the included standalone installer

## Log Files/Crash Reports

https://pastebin.com/yjUpWDmK

**Comment by sp614x** [comment]
Fixed, coming in next preview
