### ISSUE TITLE
Optifine 1.8.8 HD U h8 keeps crashing.

### ISSUE THREAD

**Issue by VorexGaming** [sp614x/optifine#626]
Hi there, my Optifine keeps crashing on mc version 1.8.8 HD U H8 i cant seem to find a fix or find the standard version, im not sure if it my pc specs or not (Nvidia GTX 960, I7 2600 3.4ghz, 16GB ddr3 ram, 2tb, 140gb ssd) could someone possibly help me? Heres the log.
 
(right click link and click open in new tab) https://pastebin.com/sr9qixas

**Comment by sp614x** [comment]
Does not seem to be related to OptiFine.
I can not reproduce it by using OptiFine H8 for 1.8.8 and connecting to "mc.hypixel.net".

**Comment by sp614x** [comment]
The "ArrayIndexOutOfBoundsException" at "amy.a(SourceFile:976)" seems to be a vanilla problem with some servers (hypixel?): https://www.google.com/search?q="amy.a(SourceFile%3A976)"
