### ISSUE TITLE
[1.17- 1.17.1 Bug] Optifine: blockstates variants doesn't work anymore (but works on vanilla...)

### ISSUE THREAD

**Issue by Silmarost** [sp614x/optifine#6260]
## Description of Issue
Hi, This bug is an error of optifine on the latest version of minecraft 1.17.1 but there are no errors in the "minecraft game output".
The problem is precisly that all blockstates variants for blocks include in a ressource pack doesn't appears, only the first texture appears, wich break a function of minecraft (with default launcher) in this version.
This a exemple of blockstates file that i mention that work well on vanilla but doesn't work anymore on optifine :
File: poppy.json

{
    "variants": {
        "normal": [
            { "model": "poppy0", "weight": 25},
            { "model": "poppy1", "weight": 10 },
            { "model": "poppy2", "weight": 50 },
            { "model": "poppy3" }
        ]  
    }
}
In this exemple only the model poppy0 works, poppy1 to poppy3 doesn't appear on optifine ...

## Steps to Reproduce
We can see it on minecraft 1.17.1 (or 1.17) and use a ressource pack that includes blockstates variants for blocks.

## OptiFine Version
OptiFine HD U H1 pre1 & OptiFine_1.17.1_HD_U_G9

## Installation Method
Use the included standalone installer

**Comment by sp614x** [comment]
The given blockstate definition `poppy.json` is not valid, vanilla reports this error:
```Exception loading blockstate definition: 'minecraft:blockstates/poppy.json' in resourcepack: 'Test' for variant: 'normal': Unknown blockstate property: 'normal'```

**Comment by sp614x** [comment]
Works fine for me:

![image](https://user-images.githubusercontent.com/16635441/134490278-08526be4-c4ae-4c9d-a9af-2ab8a64f8fbe.png)
