### ISSUE TITLE
1.17.1 minecraft launcher crashes instantly (due to optifine)

### ISSUE THREAD

**Issue by Lilzie** [sp614x/optifine#6265]
## Description of Issue
I have been trying for hours now to try and get 1.17.1-OptiFine_HD_U_G9 to work but everytime I have tried to run Minecraft using optifine, it immediately crashes. I have no other mods or anything. I have tried to use forge, optiforge and everytime, no matter what I am using, the launcher crashes immediately and doesn't even begin to load the game.

## Steps to Reproduce
All I have done is downloaded optifine. When that didn't work, I also installed forge to try it with that and it also crashed. If I deleted optifine, however, forge ran the game and it loaded like normal. So, I uninstalled everything and tried optiforge to see if that would work but it crashed yet again.

## OptiFine Version
I downloaded the newest version 1.17.1-OptiFine_HD_U_G9

## Installation Method
I have tried both methods of optifine. I downloaded it and used it in my launcher and, as I said before, when that didn't work, I used forge and put it into my mods folder. Both methods have made my game crashed.

## Other Installed Mods
I have no other mods installed from 1.17.1 or other versions of minecraft. Except for optifine, my mods folder is empty.

## Log Files/Crash Reports
I have looked for crash reports and logs but I cannot find one for my problem since it is a crash that occurs before the game can even begin to load. All it says is, "An unexpected issue occurred and the game has crashed. We're sorry for the inconvenience. Exit Code:0"

Update: I kept trying to run the game and it gave me a log so I've attached it here: https://pastebin.com/9M2kSRh2 

## Prior Testing
This error does not happen normally when I play in-game without optifine.

## Additional Information
I have the most recent Java version, as I have heard that this can cause the issue for some. I have also tried freeing up RAM and that wasn't the issue. I have restarted my computer several times so I don't know what the problem could be. Please help if you can. It would be greatly appreciated.

**Comment by ZekerZhayard** [comment]
![image](https://user-images.githubusercontent.com/41327811/134135330-f0662483-e9a8-4696-9599-5bc9d672ce1a.png)

**Comment by sp614x** [comment]
H1_pre2 is compatible with Forge.
