### ISSUE TITLE
[1.17] preview_OptiFine_1.17.1_HD_U_H1_pre2.jar not compatible with forge

### ISSUE THREAD

**Issue by Arcticzomb** [sp614x/optifine#6267]
## Description of Issue
preview_OptiFine_1.17.1_HD_U_H1_pre2.jar is not compatible with forge. It crashes as soon as I launch mc from the launcher.
Exit Code: 0

## Steps to Reproduce
1. Download preview_OptiFine_1.17.1_HD_U_H1_pre2.jar
2. Place file into mods folder
3. launch forge with preview_OptiFine_1.17.1_HD_U_H1_pre2.jar not compatible with forge

## OptiFine Version
preview_OptiFine_1.17.1_HD_U_H1_pre2

## Installation Method
Dropped the jar file into the mods folder

## Fabric/Forge Version
1.17.1 - 37.0.70

## Log Files/Crash Reports
[2021-09-21-9.log](https://github.com/sp614x/optifine/files/7206989/2021-09-21-9.log)

## Prior Testing
I've toyed with other mods that were in the folder and optifine is the root of the crashing.

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   Yes
- Does this happen without any mods at all?
   No
- Does this happen in OptiFine standalone?
   No
- Does this happen in Vanilla without OptiFine?
   No
- Have you tried using a binary search to find which mods cause this issue?
   Already have and optifine is the issue

**Comment by ZekerZhayard** [comment]
https://github.com/sp614x/optifine/issues/6216#issuecomment-924577082

**Comment by sp614x** [comment]
Fixed in H1_pre3.
