### ISSUE TITLE
chunks are getting transparant?

### ISSUE THREAD

**Issue by BibiBaggins** [sp614x/optifine#6268]
i was just playin minecraft and then everything went black chucks got bugged and only "came back" when i broke block in them or updated them
![2021-09-23_11 33 20](https://user-images.githubusercontent.com/86521917/134515660-8229347c-17f4-41b1-a68f-c6c0dad94c34.png)
 this is suposed to be a ravine

**Comment by KaiAF** [comment]
Can you send a f3 screenshot if this is still an issue?

**Comment by Jiingy** [comment]
Issue does not well enough describe the problem at hand, how to replicate it, or any additional helpful information and has had no follow up in almost 2 years.
