### ISSUE TITLE
Visual problem while viewing chunk borders with F3+G

### ISSUE THREAD

**Issue by Jerpadurr** [sp614x/optifine#6271]
## Description of Issue
Whenever I have shaders on and I view chunk borders (Something I do quite often), anytime I click/mine blocks, the screen fills up with the whole chunk border grid (even seeing it through the blocks I'm clicking/mining, all the way to the bottom. The grid also seems to offset slightly depending on your location in the chunk while clicking. This has been tested with different shaders with the same results and this does not occur when shaders are off.

## Steps to Reproduce
1. Load a world or log into a server. Have shaders enabled.
2. Press F3+G to show chunk borders.
3. Left click on any block with any tool or bare hand.

## OptiFine Version
1.17.1-OptiFine-HD_U_H1_pre3

## Installation Method
Executable JAR installation

## Log Files/Crash Reports

[2021-09-25-1.log.gz](https://github.com/sp614x/optifine/files/7230528/2021-09-25-1.log.gz)

## F3 Debug Screenshot
![2021-09-25_19 42 19](https://user-images.githubusercontent.com/90990505/134789420-117b1604-b0de-45cd-8d58-191ddbaa0acd.png)
## Prior Testing
If you've installed standalone:
Does this happen in Vanilla without OptiFine? No

**Comment by KaiAF** [comment]
Could reproduce. 
![image](https://user-images.githubusercontent.com/60985521/136637776-b6f28348-b87f-4316-8e8c-b1da8dbb0334.png)

**Comment by fayer3** [comment]
if it matters, this only happens, when a shader has gbuffers_basic. and it seems when the lines show through the blocks, that they also don't write to the depth buffer

**Comment by sp614x** [comment]
The chunk border lines don't write to the depth buffer, enabling it also doesn't fix the problem.

**Comment by fayer3** [comment]
it does seem to write to the depthbuffer when they work, son maybe it using the wrong shader?
working:
![grafik](https://user-images.githubusercontent.com/8282299/146039863-529dcdf4-0fa5-4329-bb5f-ed1be7ce3392.png)

not working:
![grafik](https://user-images.githubusercontent.com/8282299/146039898-ec7a8497-b768-417a-b050-5db73f199eca.png)

**Comment by fayer3** [comment]
did some tests with nvidia nsight, and it seems there is a different pipeline used between working correctly and not
working:
![working](https://user-images.githubusercontent.com/8282299/146050734-860029e1-780f-4cbb-b47b-441e6e8cc35f.png)

not working:
![not_working](https://user-images.githubusercontent.com/8282299/146050756-de341daf-b56a-43fd-a4c7-026d786e5ea3.png)

**Comment by fayer3** [comment]
that's with 1.18.1 HD U H4

**Comment by sp614x** [comment]
The block breaking animation is the problem.

**Comment by fayer3** [comment]
hm, but there are no breaking blocks?

**Comment by sp614x** [comment]
For me it only happens in survival mode when breaking a block.
Found the problem and fixed it, the depth check was disabled by the breaking animation.
The line offset problem is not fixed yet.

**Comment by sp614x** [comment]
Fixed, coming in next preview.
