### ISSUE TITLE
[Bug] Dragging and dropping Optifine into the Curseforge mods folder prevents game from loading.

### ISSUE THREAD

**Issue by WoahdangJr142** [sp614x/optifine#6272]
## Steps to Reproduce
1. Make a default 1.17.1 profile on curseforge, with Forge selected as modloader.
2. Open mods folder
3. Drag and drop Optifine into mods folder
4. Launch profile to open launcher
5. Press play

## OptiFine Version
OptiFine_1.17.1_HD_U_G9

## Installation Method
Drag and drop

## Fabric/Forge Version
37.0.71

## Other Installed Mods
I have worldEdit, JEI, and World Handler - Command GUI, but it does the same thing even without these mods installed.

## Log Files/Crash Reports
[latest.log](https://github.com/sp614x/optifine/files/7231400/latest.log)

## F3 Debug Screenshot
Can't even load game

## Prior Testing
 Yes. This only happens when Optifine is installed. It doesn't matter what other mods I have. I can leave everything else and just remove Optifine, and it starts working fine.

## Additional Information

Error code: 
![image](https://user-images.githubusercontent.com/68622581/134809092-7243fb41-42e2-49d9-a8d9-b9b8a8cceaf1.png)

**Comment by Cheeky974** [comment]
Already resolved in the pre releases

**Comment by WoahdangJr142** [comment]
Can you share a link? after a quick glance I didn't see those. Or is there a way for me to fix it by myself? (My java is screwed up so I can't install normally)

**Comment by sp614x** [comment]
H1_pre3 should be compatible with Forge.
