### ISSUE TITLE
[Bug] Visual glitch with the top of glass panes

### ISSUE THREAD

**Issue by Jiingy** [sp614x/optifine#6282]
## Description of Issue
Top of glass panes are displayed incorrectly from an angle

## Steps to Reproduce
Look at the top of glass panes at an angle, the top won't display properly.

Without zoom
![2021-09-29_16 51 28](https://user-images.githubusercontent.com/69827559/135364173-8668d238-5620-4074-b56f-2431394af10d.png)

With zoom
![2021-09-29_16 51 30](https://user-images.githubusercontent.com/69827559/135364190-32e74ca4-2f40-4887-8f5c-0074f2710dcc.png)

## OptiFine Version
preview_OptiFine_1.17.1_HD_U_H1_pre2

**Comment by sp614x** [comment]
What GPU, can you post an F3 screenshot?

**Comment by Jiingy** [comment]
I have an RX 580

![2021-10-03_14 15 57](https://user-images.githubusercontent.com/69827559/135771799-c7caba6e-eae2-42a2-8970-2b54afee3361.png)

**Comment by sp614x** [comment]
Fixed, coming in next preview.
