### ISSUE TITLE
崩溃collapse

### ISSUE THREAD

**Issue by aaaapai** [sp614x/optifine#6288]
直接启动Direct start

optifine版本 OptiFine Version （OptiFine_1.17.1_HD_U_G9）

正常安装，再在安装程序里提取jar。再把jar放入mods文件夹
Install normally, and then extract the JAR from the installer.Then put the jar into the mods folder

[崩溃文本Crash text](https://www.laogoupan.com/wap.php?action=view&file_id=26216) 
点击"移动下载"即可！
click"移动下载"
PC click"普通下载"

**Comment by ZekerZhayard** [comment]
![image](https://user-images.githubusercontent.com/41327811/135755069-b6d553a0-0fc3-4f53-be0e-efe98480432f.png)

**Comment by aaaapai** [comment]
不好意思，现在可以了

**Comment by aaaapai** [comment]
> 现在可以下载了Now you can download

**Comment by aaaapai** [comment]
> https://user-images.githubusercontent.com/41327811/135755069-b6d553a0-0fc3-4f53-be0e-efe98480432f.png

You can download it now

**Comment by aaaapai** [comment]
文件不存在，只是一个小小的失误，现在可以下载了The file doesn't exist. It's just a small mistake. You can download it now

**Comment by ZekerZhayard** [comment]
do you use resource packs or shader packs? it may caused by the difference
between standard OpenGL and OpenGL ES
