### ISSUE TITLE
Issues with Forge Dynamic Buckets with packs over 16x

### ISSUE THREAD

**Issue by HanFox** [sp614x/optifine#63]
The issue has been outlined in this post:
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1272953-optifine-hd-b1-fps-boost-hd-textures-shaders-and?comment=50829

I'm aware the Dynamic Buckets can be turned off, but that's not really a "fix". I'm also aware it could technically be seen as Forge's fault due to the fact it forces the liquid mask to be 16x regardless of resolution.

**Comment by sp614x** [comment]
Details from BDCraft: http://bdcraft.net/community/pbdc-patches-rel/forge-t5118.html

**Comment by sp614x** [comment]
Dynamic buckets work properly when mipmaps are OFF and with mipmap levels 1-3.

**Comment by HanFox** [comment]
Whilst what you've stated is true for MC1.9, MC1.8.9 is broken regardless of changing Mipmap settings.

**Comment by sp614x** [comment]
OptiFine 1.8.9 + Forge #1855 + 64x resource pack + mipmap level 3  seems to work.
Mipmap level 4 breaks the dynamic bucket, like in 1.9.

**Comment by sp614x** [comment]
It looks like the Forge ModelDynBucket has a problem, it calls ItemTextureQuadConverter.convertTexture() with two sprites (template and sprite) and it does not generate the model properly if one of the sprites has been scaled up. The generated model has UV outside of the UV of the sprite.

**Comment by sp614x** [comment]
This one of the generated model quads, the U range of the sprite is 0.4218 to 0.4375, the quad uses U=0.4686.

[OptiFine]   Quad: net.minecraftforge.client.model.pipeline.UnpackedBakedQuad, type: General, face: south, tint: -1, sprite: TextureAtlasSprite{name='minecraft:blocks/water_still', frameCount=64, rotated=false, x=864, y=352, height=32, width=32, u0=0.421875, u1=0.4375, v0=0.34375, v1=0.375}
[OptiFine]     Length: 28, step: 7
[OptiFine]     0 xyz: 0.625,-0.25,0.468625 col: -1 u,v: 0.43164062,0.3828125
[OptiFine]     1 xyz: 0.625,0.625,0.468625 col: -1 u,v: 0.43164062,0.35546875
[OptiFine]     2 xyz: 1.375,0.625,0.468625 col: -1 u,v: 0.44335938,0.35546875
[OptiFine]     3 xyz: 1.375,-0.25,0.468625 col: -1 u,v: 0.44335938,0.3828125

**Comment by mezz** [comment]
Is this the same issue? It was fixed recently.
https://github.com/MinecraftForge/MinecraftForge/issues/2858

**Comment by sp614x** [comment]
This looks like the same problem. 
Tested with Forge #1907 and a 32x resource pack, the Forge buckets now render properly.
