### ISSUE TITLE
Request: allow lower shader Render Quality

### ISSUE THREAD

**Issue by Ellisthion** [sp614x/optifine#630]
I've got a 4k screen which is way too high and makes shaders do too much work. Dropping the shader Render Quality from 1.0 to 0.5 gives a huge performance boost with negligible difference in quality. Unfortunately, that's as low as it goes. If I change it in the config, it reverts itself to 0.5.

I would really like to be able to reduce the shader Render Quality to 0.25.

**Comment by gerardvanschip** [comment]
Just an idea, why not change the resolution of your screen?

**Comment by Ellisthion** [comment]
Changing the desktop resolution messes with some apps, along with things like text crispness etc, so I can't leave it like that. Changing the desktop resolution without restarting causes issues (especially because DPI scaling messes stuff up), so it's inconvenient to do it for just Minecraft.

Ideally, optifine's resolution-changing should fix this, but it's broken as per #512, and fixing that sounds hard. Whereas tweaking the render quality min seems relatively straightforward.

The 'simple' fix, of course, is just "don't use shaders" :-)

**Comment by sp614x** [comment]
A 4K monitor has resolution 3840×2160. 
Then Render Quality 0.5x has effective resolution 1920×1080 which is acceptable.
With Render Quality 0.25 the resolution would be 960×540 which most probably would not look good.

**Comment by Ellisthion** [comment]
Gotta remember that this is 4k on a normal-sized screen, with dpi scaling. Regular HD at 0.5 is also 960x540, just the same as 4k at 0.25.

It _might_ look terrible, but it's hard to tell without testing, and if 960x540 for an hd screen is 'okay', then 960x540 for a 4k screen might also be 'okay'.

**Comment by sp614x** [comment]
For me 960x540 is not playable:

![image](https://cloud.githubusercontent.com/assets/16635441/26064800/4e4de254-3992-11e7-9972-bd29b8a9e301.png)

The edge aliasing is quite bad, especially when moving. Maybe with proper antialiasing (4x) it may be acceptable, but AA is currently not compatible with shaders. Enabling FXAA only helps a little.

The GUI is not scaled down and the contrast between the sharp GUI and the blurred terrain is annoying.

**Comment by Ellisthion** [comment]
Wow, that's surprisingly bad. I guess that makes sense, and the existing 0.5 setting is really _already_ for 'my' use case and not 'normal' sized screens, since anything that small will look terrible on everything.

Well, thank you for taking the time on this. I clearly didn't quite understand the implications of what I was asking. :-)

**Comment by twoco** [comment]
A few years later... Where can I edit the value to 0.25? Without official support for this moment. Is it done with a value change or does it require a deeper implementation? I just want to try 0.25 scale. I cannot change the native resolution. The screen looks terrible then it's not on native resolution. Native resolution changes is something for 1998 or early 2000. ^^ Modern games has internal resolution and borderless windowed fullscreen. I wish Minecraft has an intern resolution scale factor from beginning from 0.25. It that a problem to just allow it? My graphics card gets extremely hot. And the framerate is low. Even the GPU is about 50%. It's werid, but I see that the change of the resolution scale increases the performance. For such a lowres block game, low resolutions works great I think.

For now, can someone please tell me where I can change the limit from 0.5 to 0.25? Is it just a quick change with an editor?

**Comment by fayer3** [comment]
in `optiosshaders.txt` change the renderResMul, you can set it to 0.25
this gets loaded, when the game starts up, don't know if it resets if you change shader or something though.

**Comment by twoco** [comment]
Thanks it works. I've changed `renderResMul=0.25` in `%APPDATA%\.minecraft\optionsshaders.txt`.

But now it looks like a Nintendo Switch Game. :D JK With TAA it looks much better. Great anti aliasing. But it makes the screen very blurry. My graphics card is now much cooler and frames are more stable. But yes, it's not the nices quality. Btw. at this moment I use SEUS Renewed 1.0.1 with Vanilla-PBR-1-2-0 and Borderless Gaming. I wish Minecraft uses DLSS or FSR. Anyway, ...
