### ISSUE TITLE
No Snout Cape Design

### ISSUE THREAD

**Issue by wilsoffer** [sp614x/optifine#6300]
I have tried again and again to implement a snout banner design to my cape; however, no matter which letters I jumbled from the alphabet—upper and lower-case—it does not exist. Please add this feature to the capes!

**Comment by KaiAF** [comment]
Right now we use https://www.needcoolshoes.com/ for the banners. We can't add the snout design, they have to. 
We are working on implementing our own cape editor, so maybe in the future there will be new designs.
