### ISSUE TITLE
[Category] Invisible mobs/tiles floating in the air.

### ISSUE THREAD

**Issue by thatdude69420** [sp614x/optifine#6301]
## Description of Issue
Invisible mobs/tiles floating in the air in the place of the mob. They can attack you. I can attack them. Its just a visual bug.

## Steps to Reproduce
1. I dont know
2. I just have a whole lotta mod and resource packs.
3. version 1.16.5
4. I use ely.minecraft. So its a free version of minecraft. Idk if that matters wrt a paid version.
5. Solution: My solution was to simply disable fast render. The mobs then appear as normal. Just wanted to put this here in case anyone has this issue. So this is solved for me. Hope it can help.

## OptiFine Version
<!--latest as of the (10/10/2021)

**Comment by KaiAF** [comment]
Could be related to: #5016. Since you are using an illegal version of Minecraft that could also be the issue. If this happens on a legit version, we can re-open the issue.
