### ISSUE TITLE
[OpenGL Error] My GL Errors

### ISSUE THREAD

**Issue by Medatur76** [sp614x/optifine#6317]
## Description of Issue
So I was playing with my friend then I have to go for the day. Nothing rong there. Then I find this cool new patron mod, get, run it on a single player world and everything is fine. But then I join one of my fav server deadmc
 and I get the OpenGL errors 1280 and 1282
## Steps to Reproduce
1. Get that lattest version of Optifine for 1.17.1
2. Load it with optifabric on a fabric client
3. run the game and join a server (I just uesed DeadMc)

## OptiFine Version
OptiFine HD U G9 1.17.1 30.08.2021

## Installation Method
I went to [The Offical Optifine Website](https://optifine.net/downloads.php) and downloaded Optifine. Then I droped the JAR file into your "mods" folder with Optifabric and loaded a Fabric client

## Fabric/Forge Version
fabric-loader-0.11.6-1.17.1

## OptiFabric Version
1.11.20

## Other Installed Mods
[physics-mod-pro-v15-fabric](https://www.patreon.com/Haubna)

## Log Files/Crash Reports
[Get It Here](https://cdn.discordapp.com/attachments/896185412836536351/899145150058614834/latest.log)

## F3 Debug Screenshot

![2021-10-16_23 05 23](https://user-images.githubusercontent.com/90143210/137610752-7a672b9f-0e54-40e8-9520-bf94a2191863.png)

## Prior Testing
Have not done any

## Additional Information
I live in Houston, TX so depense on where you live, I might not get back to you right away

**Comment by Medatur76** [comment]
Also I cant Collect Exp in-game

**Comment by Jiingy** [comment]
Closing as this is likely a conflict with the physics mod, or more likely an error with render regions.
