### ISSUE TITLE
OpenGL Error: 1282 (Invalid Operation) with completely vanilla Minecraft 1.17.1

### ISSUE THREAD

**Issue by benwins123** [sp614x/optifine#6318]
I get this message in my textbox every few seconds:  OpenGL Error: 1282 (Invalid Operation)

Latest Minecraft and Optifine version (1.17.1), freshly installed. Vanilla with no shaders, no resource packs, no mods.
All drivers are up to date, also tried with Java 16 and Java 17, both fresh installs.

I've also tried everything in this guide. https://mostechtips.com/fix-opengl-error-1282-invalid-operation/

Disabling OpenGL errors is not a solution as the game still lags every few seconds. At this point I'm just playing without Optifine because it's broken.

**Comment by KaiAF** [comment]
Can you send a latest.log file? Go to `.minecraft\logs`.

OpenGL errors can happen on lots of things, most of the time it is just caused by broken or outdated graphics card drivers.

**Comment by little-bud** [comment]
I've seen this happen when render regions is enabled on my mac in the performance tab. Try disabling render regions and see if you still get the lag spikes.

**Comment by KaiAF** [comment]
yeah the error log suggests its coming from render regions, glad it got fixed for you
