### ISSUE TITLE
[Visual Bug] My real Cape isn't showing up

### ISSUE THREAD

**Issue by JoChLi** [sp614x/optifine#6327]
## Description of Issue
I just got my migration cape in Minecraft, I was all exited but when I joined a world it wasen't showing up. So I check if I actived it and I did, then I started Minecraft without Optifine and it worked. So what I think happend was, since I dont own any Optifine capes, Optifine overwrites my normal cape with a standart one and it is shown like I don't have a cape. On the Optifine Website you can only disable capes if you have one, and I don't. Pls fix this since I want to use Optifine again, with a cape.

## Steps to Reproduce
1. Have a Minecraft acc. with no Optifine cape, but an official one
2. Start Minecraft and see, you don't hava a cape and you can't disable the optifine one, since you dont have one.

## OptiFine Version
OptiFine HD U G9

## Installation Method
Installer

## Log Files/Crash Reports
just visual, there are no Logs/Crash Reports

## F3 Debug Screenshot
![2021-10-20_12 44 46](https://user-images.githubusercontent.com/92858191/138079113-1c2aefac-47e4-46fa-a96c-2faf507faa44.png)

## Prior Testing
- Does this happen in Vanilla without OptiFine?
- no

**Comment by KaiAF** [comment]
This is not a bug, this is intended. You have to disable your optifine cape to see the mojang cape.

Someone already suggested an ingame toggle to see mojang capes over OF. #6206

**Comment by JoChLi** [comment]
ok thank you, that fixed it
