### ISSUE TITLE
Request: use custom (simplified) renderer for end portals when shaders are enabled

### ISSUE THREAD

**Issue by Builderb0y** [sp614x/optifine#633]
Since end portals don't render correctly with shaders enabled (specifically any shader pack which uses gbuffers_block, terrain, textured_lit, textured, or basic), I decided to apply my own effects to them. This causes problems because they seem to have ~16 different polygons all rendering on top of each other using additive blending. There are 2 solutions to this that I've come up with so far:

Option 1: Reduce the brightness of all effects that I apply by 16x, so that the final color ends up being what it should be. The main problem with this method is that re-applying said effects 16x more than necessary is extremely taxing on performance.

Option 2: Sample the depth buffer when rendering, and discard fragments if there's already something at the same depth as the portal itself. The main problem with this method is that it's hardware/driver-dependent, and [doesn't always work properly](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2778752-builders-quality-of-life-shaders?comment=64) for some people.

Neither of these options are particularly desirable, so I'd like to request that optifine overwrite the renderer for end portals to use a simplified model which only has one square polygon instead of 16 whenever shaders are enabled. (or at least whenever a shader pack is loaded which contains a program for them)

**Comment by sp614x** [comment]
Updated preview B9, added shaders compatible rendering for end portals. 
It uses the end portal texture and lookes similar to the vanilla rendering.

![image](https://cloud.githubusercontent.com/assets/16635441/26060183/885bda72-3984-11e7-91af-b733b4fd2581.png)

**Comment by Builderb0y** [comment]
Works great! Thanks!
