### ISSUE TITLE
Powered Conduit game crash

### ISSUE THREAD

**Issue by Solrac2021** [sp614x/optifine#6330]
## Steps to Reproduce
1. activate conduit underwater with prismarine around it for full power
2. game crashes 
3. I log back in without optifine and it works
4. in "latest version" I remove the conduit and then log out and go back to optifine 
5. game works, if I place the conduit again, it crashed again but only with optifine 
6. I can use the conduit fully powered with "latest version" but not with optifine 
7. it's a server and even other players crash if they are using optifine and I have the powered conduit 
8. non fully powered conduit doesn't cause the crash, only when fully powered 

## OptiFine Version

the latest

## Installation Method

installer

## Prior Testing

I don't use mods

**Comment by fayer3** [comment]
I assume you use a resourcepack, in which case this issue is fixed with the latest preview OptiFine HD U H1 pre7.
