### ISSUE TITLE
optifine 1.16.5 v8 causing exit code: 0 crash 

### ISSUE THREAD

**Issue by PrinceJaxonHellsing** [sp614x/optifine#6331]
Hello! So recently I tried adding optifine to my mods for 1.16.5 v8 but when I launch minecraft it causes the exit code 0 crash to happen, I've tried it without any other mods but it still happens to give me the exit code 0 crash without any crash logs.

I'm using a bunch of mods so I'll send photo's of the ones I'm using

![my minecraft mods pt 1](https://user-images.githubusercontent.com/48263377/138378298-a23629c4-4f11-40d3-a9ef-0863d5c36764.png)
![my minecraft mods pt  2](https://user-images.githubusercontent.com/48263377/138378630-5231df79-5381-459a-81eb-93023113585d.png)
![my minecraft mods pt  3](https://user-images.githubusercontent.com/48263377/138378637-57bcfbd0-dcad-4076-9a5c-a298efb8aca4.png)

so I have all of this but it won't work with optifine 1.16.5 v8 some reason.

I've been using it with forge 1.16.5 v8 but also just updated java so I wonder if that's the cause, but I'm unsure.

I would give a crash log if I could but it's not giving me one so I don't know what else to do.

I have tried it with basically only one mod without optifine and it works but if I add optifine it crashes with exit crash 0 without any logs.

**Comment by KaiAF** [comment]
Can you try to find the mod that would be causing this? Take out mods slowly and test it, then figure out the mod that causes the crash. Other than that, this report does not help at all

**Comment by Jiingy** [comment]
Closing this as there was no follow up to try and find the mod causing the conflict
