### ISSUE TITLE
[Connected texture] Translucent glass and connected

### ISSUE THREAD

**Issue by Yupoman** [sp614x/optifine#6335]
It always bothered me that the most "transparent" block in the game is not completely transparent and has those horrible pixels then i saw that you can convert a block to translucent with a block.properties (layer.translucent = glass), I add that and the glass texture with transparency and it works, but doing so I lose the connected textures.

I guess I have to redo them and make them transparent or can I add this property directly to the connected textures?
As it is something internal to optifine, I don't know how to do it, nor can I find the original textures to change them myself (only with a strange format that I can't even open)

![image](https://user-images.githubusercontent.com/70600879/138613860-e92e5963-c99a-4776-adcf-493e34ebf1ce.png)

**Comment by Jiingy** [comment]
Seems to be working fine
