### ISSUE TITLE
[Website] A little credits update

### ISSUE THREAD

**Issue by Brandonbr1** [sp614x/optifine#6337]
Hi i am  suggesting to update the credits to put the creator of the Optimine mod(Scaevolus) in the credits as it was the original mod and Optifine is just  an  updated version of Optimine/the Optimine creator gave sp614x to update the mod

![1](https://user-images.githubusercontent.com/74426342/138709248-93a26a65-ca56-48ee-bccf-e44a65cfb92c.PNG)

**Comment by sp614x** [comment]
In the current OptiFine there is nothing left from the original OptiMine.
The rendering pipeline has undergone so many reorganizations that all of the code is fully rewritten.
