### ISSUE TITLE
Crash when loading world with Forge 1.11.2-13.20.0.2292

### ISSUE THREAD

**Issue by aim-gaming** [sp614x/optifine#634]
The game crashes when I attempt to load a world with Forge 1.11.2-13.20.0.2292. Removing Optifine fixes the issue.
The changelog for OptiFine_1.11.2_HD_U_B8 says that it supports Forge 2294, but I need 2296 for other mods I have installed.

Crash log is as follows:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.62+beta.85.jar)
  IC2core (industrialcraft-2-2.7.9-ex111.jar)
Contact their authors BEFORE contacting forge

// Everything's going to plan. No, really, that was supposed to happen.

Time: 5/10/17 3:27 PM
Description: Ticking block entity

java.lang.NoSuchMethodError: net.minecraft.profiler.Profiler.startSection(Ljava/lang/Class;)V
	at net.minecraft.world.World.func_72939_s(World.java:1801)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1801)

-- Block entity being ticked --
Details:
	Name: minecraft:forestry.swarm // forestry.apiculture.tiles.TileHive
	Block type: ID #378 (tile.for.beehives // forestry.apiculture.blocks.BlockBeeHives)
	Block data value: 6 / 0x6 / 0b0110
	Block location: World: (-179,64,-36), Chunk: (at 13,4,12 in -12,-3; contains blocks -192,0,-48 to -177,255,-33), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Actual block type: ID #378 (tile.for.beehives // forestry.apiculture.blocks.BlockBeeHives)
	Actual block data value: 6 / 0x6 / 0b0110
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1801)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)

-- Affected level --
Details:
	Level name: Again___
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 625 Drop: 0
	Level seed: 158473082
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-16,64,104), Chunk: (at 0,4,8 in -1,6; contains blocks -16,0,96 to -1,255,111), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 871 game time, 871 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 108251 (now: false), thunder time: 63933 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 835683360 bytes (796 MB) / 2049536000 bytes (1954 MB) up to 2134114304 bytes (2035 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 96
	FML: MCP 9.38 Powered by Forge 13.20.0.2296 Optifine OptiFine_1.11.2_HD_U_B8 24 mods loaded, 24 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2296.jar) 
	UCHIJAAAA	forge{13.20.0.2296} [Minecraft Forge] (forge-1.11.2-13.20.0.2296.jar) 
	UCHIJAAAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.2.jar) 
	UCHIJAAAA	buildcraftlib{7.99.3} [BuildCraft Lib] (buildcraft-7.99.3.jar) 
	UCHIJAAAA	buildcraftcore{7.99.3} [BuildCraft] (buildcraft-7.99.3.jar) 
	UCHIJAAAA	buildcraftfactory{7.99.3} [BC Factory] (buildcraft-7.99.3.jar) 
	UCHIJAAAA	buildcrafttransport{7.99.3} [BC Transport] (buildcraft-7.99.3.jar) 
	UCHIJAAAA	buildcraftbuilders{7.99.3} [BC Builders] (buildcraft-7.99.3.jar) 
	UCHIJAAAA	buildcraftenergy{7.99.3} [BC Energy] (buildcraft-7.99.3.jar) 
	UCHIJAAAA	buildcraftrobotics{7.99.3} [BC Robotics] (buildcraft-7.99.3.jar) 
	UCHIJAAAA	buildcraftsilicon{7.99.3} [BC Silicon] (buildcraft-7.99.3.jar) 
	UCHIJAAAA	ic2{2.7.9-ex111} [IndustrialCraft 2] (industrialcraft-2-2.7.9-ex111.jar) 
	UCHIJAAAA	forestry{5.3.3.94} [Forestry] (forestry_1.11.2-5.3.3.94.jar) 
	UCHIJAAAA	gravestone{1.7.2} [Gravestone] (GraveStone Mod 1.7.2.jar) 
	UCHIJAAAA	inventorytweaks{1.62+beta.85.4b3a8f6} [Inventory Tweaks] (InventoryTweaks-1.62+beta.85.jar) 
	UCHIJAAAA	ironchest{1.11.2-7.0.18.800} [Iron Chest] (ironchest-1.11.2-7.0.18.800.jar) 
	UCHIJAAAA	jei{4.3.3.266} [Just Enough Items] (jei_1.11.2-4.3.3.266.jar) 
	UCHIJAAAA	jeresources{0.6.2.104} [Just Enough Resources] (JustEnoughResources-1.11.2-0.6.2.104.jar) 
	UCHIJAAAA	mantle{1.11.2-1.2.0.26} [Mantle] (Mantle-1.11.2-1.2.0.26.jar) 
	UCHIJAAAA	tconstruct{1.11.2-2.7.0.12} [Tinkers' Construct] (TConstruct-1.11.2-2.7.0.12.jar) 
	UCHIJAAAA	xaerominimap{1.12.8} [Xaero's Minimap] (Xaeros_Minimap_1.12.8_Forge_1.11.jar) 
	UCHIJAAAA	xaeroworldmap{1.9} [Xaero's World Map] (XaerosWorldMap_b1.9_Forge_1.11.jar) 
	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.62+beta.85.jar)
  invtweaks.forge.asm.ContainerTransformer
IC2core (industrialcraft-2-2.7.9-ex111.jar)
  
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.11.2_HD_U_B8
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Sildurs Vibrant Shaders v1.161 Lite.zip
	OpenGlVersion: 4.5.0 NVIDIA 382.05
	OpenGlRenderer: GeForce GTX 860M/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by sp614x** [comment]
This should be fixed in latest preview B9.

**Comment by Medusalem** [comment]
Where do I find that preview to test it?

**Comment by 0142929** [comment]
support for the forge 2296 could be very great )

**Comment by skmedix** [comment]
@Medusalem http://optifine.net/downloads.php

**Comment by Medusalem** [comment]
That is up till B8
He Said: This should be fixed in latest preview B9. that is something that is not be there for publik download!

**Comment by sp614x** [comment]
Install latest preview B9
Go to http://optifine.net/downloads, click on "Preview Versions" -> download B9

**Comment by 0142929** [comment]
it works :)

**Comment by Medusalem** [comment]
It Seems, with shaders enabled, there is no Day/Night circle but the crash is gone :)

**Comment by sp614x** [comment]
The shaders should not affect day/night cycle.
Check if  "Video Settings -> Other -> Time" is Default
