### ISSUE TITLE
[Feature Request] OpenGL 4.6

### ISSUE THREAD

**Issue by CanerKaraca23** [sp614x/optifine#6340]
## Description of the new feature

OpenGL 4.6 support. My graphics card supports it and add a setting to enable it.

**Comment by IMS212** [comment]
This makes no sense. Should probably be closed.

**Comment by CanerKaraca23** [comment]
> This makes no sense. Should probably be closed.

Why?

**Comment by IMS212** [comment]
OpenGL 4.6 is not a feature. It is a set of API’s. It’s like saying a new highway exists and you’ve upgraded, even though you’re not taking that highway.

OpenGL 4.6 is always on.

**Comment by CanerKaraca23** [comment]
> 

I know it's not a feature. OpenGL 4.6 is not on. OptiFine using the old version of OpenGL 3.2.

**Comment by IMS212** [comment]
If OpenGL 4.6 was “turned on”, literally nothing would change because OpenGL versions mean nothing. They provide extra functions, not make existing functions any better.
