### ISSUE TITLE
Nether portal chunk loaders are broken

### ISSUE THREAD

**Issue by Yadokingu** [sp614x/optifine#6346]
## Description of Issue
I built ilmango's shulker farm in my local world. https://www.youtube.com/watch?v=RRSnya62snY
It depends on nether portals chunk-loading the farm while I'm somewhere else in the overworld doing other things. Vanilla behaviour would be it staying loaded and I have confirmed that it does. With optifine it unloads after about 30 soconds. It's a bit hard to time.
I should mention that my load-portal is, different from mango's tutorial, at the bottome of the world at Y 5, while the farm is still at Y 200. Just in case Optifine does something weird with subchunks.
There were no Optifine-settings I could find that would change the behaviour.

## Steps to Reproduce
Turn on the farm, leave the area.

## OptiFine Version
Tested in HD U G9 and HD U H1 pre8

## Installation Method
Standalone Installer

## F3 Debug Screenshot

![2021-10-30_02 01 17](https://user-images.githubusercontent.com/11133215/139512766-b692b76f-c33d-43d4-a5bb-d5aa4eb6e205.png)
![2021-10-30_01 59 16](https://user-images.githubusercontent.com/11133215/139512763-64c45d28-7906-4509-8087-9f4e02d72f92.png)

## Prior Testing
This Issue does not happen in Vanilla, without Optifine.

**Comment by Jiingy** [comment]
1. is your chunk loader in the overworld?
2. Do you have smooth world turned on?

Smooth world disables the spawn chunks in favor of game preformance. Could be causing issues.

**Comment by Yadokingu** [comment]
1. It is by its nature in the overworld and in the nether. 

2. The smooth world setting seems to have been the problem. Even though these chunk loaders are not in the spawn chunks. Thank you. I could have sworn I tested it, but maybe not long enough.
That setting should really have a warning that it unloads chunks that should usually stay loaded.

Also are you sure it disables spawn chunks? My mob switch in the spawn chunks and the iron farm there seemed to be working fine with this setting on. But I guess it does something to chunk loading, when it breaks nether portal loaders...

**Comment by Jiingy** [comment]
Problem seems to be resolved, closing issue.

A suggestion to change the description of the settings could be made as another post if desired
