### ISSUE TITLE
Any way to remove the Halloween hats while preserving Optifine capes?

### ISSUE THREAD

**Issue by AndrewDTR** [sp614x/optifine#6348]
Hello,

I have a rather niche issue with Optifine, so any help would be greatly appreciated. I have a video that I've been working on that I've been using replay mod for. The footage was recorded a few weeks ago, but I'm continuing to pull from that one file. I have a huge amount of shots finished without the hats, so if I were to just continue taking shots as normal right now, there would be a weird continuity where halfway through the video people randomly started wearing Halloween hats. If I were to completely disable Optifine, everybody would lose their capes and cause yet another continuity error.

Is there any way around this, even jankily? I tried changing my system's date and time but that didn't seem to do anything. Is there any way I can at least trick the mod into thinking that it isn't Halloween?

Thank you in advance.

**Comment by KaiAF** [comment]
No, there is not. Unless you use another mod that supports optifine capes. The hats will be disabled on the 7th
