### ISSUE TITLE
MAC Issues

### ISSUE THREAD

**Issue by Riiven** [sp614x/optifine#635]
I can't seem to open the .jar file with Java. I've downloaded Java and did the detection and it says I have it. I downloaded the .jar from Optifine and downloads as a zip but with the .jar ending. I open the zip/.jar and it just gives me a folder. This is what it looks like http://image.prntscr.com/image/a6a6b2f0a44c4fa7ace11ebd90b28ea1.png

I'm on Mac/OSX and I use to have Optifine many moons ago.

**Comment by Builderb0y** [comment]
That's a .jar.zip file, and you apparently have it configured to hide the .zip part of the extension. To show it again, go to finder > preferences > advanced > show all filename extensions. Once it shows the correct extension, simply remove the .zip part from the end by renaming it, and put the .jar file in your mods folder like normal.
