### ISSUE TITLE
Installer popup blurry on use.

### ISSUE THREAD

**Issue by Thisisniceygy** [sp614x/optifine#6352]
## Description of Issue
OptiFine installer blurry when opened

## Steps to Reproduce
1. Download Optifine from optifine.net
2. Run installer
3. Installer popup goes blurry.

## OptiFine Version
1.17.1 HD U G9

## Installation Method
Standalone .jar Installer

## Log Files/Crash Reports

https://pastebin.com/rW0wz8eW

## F3 Debug Screenshot

Unable to complete.

## Prior Testing
 https://photos.app.goo.gl/xwTajv7qds9f4Gpj7

**Comment by Jiingy** [comment]
Does this happen with any other program installers or other OptiFine installer versions?

**Comment by Thisisniceygy** [comment]
I've tested all 1.17.1 versions. If it helps I am on a Ryzen 7 & Vega 10 graphics

**Comment by mindforger** [comment]
not sure what display resolution you use, but can you try (only if using 2 o 4k display) to disable the upscaling in your desktop/display settings or try running with a 1080p resolution, there seems to be an upscaling issue for swing and AWT apps ... albeit i have not seen such an extrem blur in combination with that bug, but maybe you are an extreme example for the case

**Comment by Thisisniceygy** [comment]
![image](https://user-images.githubusercontent.com/80964340/140552064-4702fbbf-0cef-4e2b-bd29-fa8552391b3e.png)
This is (i think) what you want. You are going to have to give me a few days on the graphics settings one though, it is being stubborn. Thanks for your help though!

**Comment by Thisisniceygy** [comment]
Update: I have set my display to 100% (from 125%) and it seems to have fixed the problem. Thanks for your help!
