### ISSUE TITLE
[visual glitch] flashing hands and handheld items

### ISSUE THREAD

**Issue by Waffels08** [sp614x/optifine#6353]
## Description of Issue
My hands and all handheld items flash irregularly and turn blue when looking at the sun. 
## Steps to Reproduce
1. What do you do...
2. ...to find this bug?

## F3 Debug Screenshot

https://aka.ms/snapshotbugs?ref=game

## Prior Testing

      - no

## Additional Information
https://aka.ms/snapshotbugs?ref=game

**Comment by fayer3** [comment]
please post a F3 screenshot, you only added a link to the mojang bug tracker

**Comment by Jiingy** [comment]
Please provide more information, there is nothing to go off of here.

**Comment by KaiAF** [comment]
No response from the issue author, closing
