### ISSUE TITLE
[Visual Glitch] Enchantment glint bugged on certain items (Only on Optifine)

### ISSUE THREAD

**Issue by Lythael** [sp614x/optifine#6354]
## Description of Issue
So after i made a Lodestone compas on my current 1.17.1 world (Optifine version 1.17.1 HD U G9)
And noticed the glint is really glitchy. I couldn't see it on any other enchanted item i made just this compas for some reason is acting up.

I am 100% sure it's caused by Optifine cause when switching to vanila or sodium it looks fine as it should.
I don't have any texture packs active.

## Steps to Reproduce
1. Make a Lodestone compass.
2. Look at it.

## OptiFine Version
 1.17.1 HD U G9

## Installation Method
Installed via JAR

## F3 Debug Screenshots

Optifine (with the glitch happening)
https://i.imgur.com/75i6Uqt.png

Vanilla (no glitch , working fine)
https://i.imgur.com/1RDCqHJ.png

**Comment by Jiingy** [comment]
Duplicate; closing in favor of #6097
