### ISSUE TITLE
[Installer] add support for the new Windows Store Launcher

### ISSUE THREAD

**Issue by fayer3** [sp614x/optifine#6355]
## Description of the new feature
currently the installer only adds the Optifine profile to `launcher_profiles.json`, but the new launcher uses `launcher_profiles_microsoft_store.json` instead.
would be nice if the installer would also add a profile to that version

**Comment by Tencryn** [comment]
Wish I had realised this before removing the old launcher. Le sigh.

**Comment by Feiioury** [comment]
It's worth noting that the only thing 'broken' is the automatic profile creation. It still installs and functions properly, without any issues. I always delete that auto-generated profile anyways, and use my own.

https://user-images.githubusercontent.com/19168008/139944487-ffd9c744-645a-4194-a0db-c1d25888b073.mp4

**Comment by sp614x** [comment]
Fixed in H1 pre9, older major versions will also be updated.

**Comment by ZenithRogue** [comment]
> Wish I had realised this before removing the old launcher. Le sigh.

![image](https://user-images.githubusercontent.com/11393734/140354789-23767bcc-b46f-4d32-980e-fdad35c838d4.png)
You can still download the old version here
https://launcher.mojang.com/download/MinecraftInstaller.msi

**Comment by MsKiller01** [comment]
Try to put in your launcher a second player, and have that everytime at your fingertips, seems that you have to login everytime any new user into the launcher (Msoft) and that is so annoying. So, if you play with two accounts, make notice that logging into the Msoft accounts EVERYTIME you want to play.... Idiots.... (pardon my French)
