### ISSUE TITLE
[crash] Trying to start OptiFine in the new Launcher on Windows 11 reboots my PC.

### ISSUE THREAD

**Issue by codedotspirit** [sp614x/optifine#6356]
## Description of Issue
If I try to start the newest OptiFine Version on my PC, it reboots. No crash, no error, just reboot. 

## Steps to Reproduce
1. Install OptiFine over the .jar File
2. Start Minecraft with the new Launcher

## OptiFine Version
OptiFine HD U H1 pre9

## Installation Method
Standalone Installer

## Log Files/Crash Reports
I dont get a crash report/ No crash report comes up in the launcher and the folder.

## F3 Debug Screenshot
I dont get to start Minecraft.

## Additional Information
OS: Windows 11
Launcher: New Microsoft Store Launcher

**Comment by zSan1** [comment]
I have the same problem.
Neither version works after installing Optifine, all reboot the PC when starting the game.
To get back to normal without Optifine, I have to delete .minecraft and uninstall Microsoft's launcher.

**Comment by kaboomgf** [comment]
I'm having problems installing optifine in the new launcher, since the other people in this thread have managed i'd appreciate some help with it

**Comment by fayer3** [comment]
you need the latest preview version of optifine (H1 pre9) to install it with the new launcher

**Comment by Str4ky** [comment]
I have the same problem, even with the latest version of optifine

**Comment by Lorenzo0111** [comment]
Same problem

**Comment by CrossingBridges** [comment]
Does it make sense to state, that I suffer, too? 
No version works. 
But I found, that it might be caused by the JDK, while Oracle Java simply only crashes, it reboots the PC with the openJDK.

**Comment by Str4ky** [comment]
> Does it make sense to state, that I suffer, too? 
> No version works. 
> But I found, that it might be caused by the JDK, while Oracle Java simply only crashes, it reboots the PC with the openJDK.

It's not optifine of Oracle Java/Open JDK it's just the New launcher, i have java 17 (open JDK things by a link i got on the optifine Discord server) and works fine on the previous launcher

**Comment by CrossingBridges** [comment]
Thanks, so I just get back to the old launcher?

*Mit herzlichen Grüßen*

*Daniel Schwark*


Am Mo., 8. Nov. 2021 um 12:36 Uhr schrieb Tim ***@***.***>:

**Comment by CommandoEchino** [comment]
I had the same issue, here's a work-around for the interim until the devs can figure out what's going wrong:

1. Go to here: **https://www.oracle.com/java/technologies/downloads/#jdk17-windows**
2. Download the **installer** and run it. Use the default options.
3. Open the Minecraft launcher. Click **Installations** (next to skins)
4. Click on your **Optifine** Installation
5. Click "**MORE OPTIONS**" at the bottom
6. Click "**BROWSE**" under "JAVA EXECUTABLE"
7. Navigate to **C:\Program Files\Java\jdk-17.0.1\bin** 
_(Go to C: --> Program Files --> Java --> jdk-17.x.x --> bin)_
8. Scroll down and **select javaw.exe**
9. Click "**Save**"
10. Go play Minecraft! : )

**Credit to /u/bl8demast3r on [Reddit](https://www.reddit.com/r/windowsinsiders/comments/qljzl4/windows_11_bsod_from_launching_minecraft_on/hj3zxab/).**

**_He also posted [this](https://www.youtube.com/watch?v=juiwBb251To) video tutorial if you're not sure how to go about it._**

**Comment by keydoch** [comment]
Yeah this is still a problem. The fix Commando gave works from what I'm getting.
