### ISSUE TITLE
Optifine 1.17.1 H1 causes blue screen

### ISSUE THREAD

**Issue by ItsYisusUwU** [sp614x/optifine#6362]
## Description of Issue
When starting optifine in the new launcher causes blue screen

## Steps to Reproduce
Start Optifine 1.17.1 H1 in the new launcher

## OptiFine Version
Optifine 1.17.1_HD_U_H1

## Installation Method
Java installation

**Comment by KaiAF** [comment]
I personally do not believe this is caused by OptiFine, it still works fine on the old launcher so you can install that one again. OptiFine has not changed at all so it makes no sense. Anyways, it's already reported here: #6356.

**Comment by ItsYisusUwU** [comment]
Pus really gives me a blue screen, only when starting with optifine, and it is something weird since the previous versions did not pass

**Comment by fayer3** [comment]
as far as I know it's some incompatibility with the new launcher and windows 11

**Comment by zSan1** [comment]
I have the same problem, the computer automatically restarts when starting the game.
