### ISSUE TITLE
[BUG] No effect from breaking blocks

### ISSUE THREAD

**Issue by jagyCZ** [sp614x/optifine#6363]
## Description of Issue
With optifine, there are no particle effect from breaking blocks

## Steps to Reproduce
1. Destroy a block while having optifine installed

## OptiFine Version
OptiFine HD U H1

## Installation Method
.jar in mods folder

## Forge Version
1.17.1 - 37.0.104

## Other Installed Mods
Xaeros minimap

## Log Files/Crash Reports
https://dl.dropboxusercontent.com/s/0brik37lgwsseia/latest.log
https://dl.dropboxusercontent.com/s/gnh17olrz86f8jj/debug.log

## F3 Debug Screenshot
https://dl.dropboxusercontent.com/s/k4z440qzqfd42l8/javaw_Ez7xjFLHlM.png

## Prior Testing

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? YES
   - Only OptiFine and Forge

- Does this happen in Vanilla without OptiFine? NO

- Have you tried using a binary search to find which mods cause this issue? NO
   - To find conflicting mods, split your mods into 2 groups (not including OptiFine/OptiFabric, obviously). Remove one group, and test in-game. Keep the group that has the problem, and repeat until no more mods can be removed without the issue disappearing.
 
   - Does the issue still happen with only the remaining mods installed?
      - Forge/Fabric and remaining mods, without OptiFine -->

## Additional Information
nothing more to say

**Comment by KaiAF** [comment]
Should be fixed in H2_pre1 #6363

**Comment by Nuanulla** [comment]
Just for record's sake, copy of #6349
