### ISSUE TITLE
Optifine Halloween hats (and Christmas ones last year) showing while invisible 

### ISSUE THREAD

**Issue by Flame625** [sp614x/optifine#6368]
## Description of Issue
I love the hats a lot but whenever you are invisible your hats will still be showing, so people can still find you which is extremely annoying.

## Steps to Reproduce
Be invisible 

I assume you would kind of get mad over me not filling up the next segments because it's just for all versions lol.

**Comment by KaiAF** [comment]
The issue has been fixed for 1.16 and up, we back ported to 1.8.9 also specifically because that's where everyone was wanting it to be fixed. We are aware of the issue
