### ISSUE TITLE
Particles not rendering = Forge 37.0.95 --- 37.0.104 | OptiFine HD U G9 --- H1

### ISSUE THREAD

**Issue by SSProgrammer00** [sp614x/optifine#6370]
I'm observing Minecraft particles not rendering properly when Optifine is added.
I have tested different versions from 2 of last month's releases until newly released ones. None of them are rendering properly.
I'm using Fabric [except the latest release as it won't run due to optifabric outdated mod] in a different machine and it works fine but in my newly installed machine with newly installed Minecraft plus Forge, it doesn't render. [I'm testing out some mods that are not supported in a forge like the replay mod that is why I'm using Fabric]
But, for the default optifine's image, it works properly. It only doesn't work when optifine is installed as a mod under Forge.
 

Links to the video can be found below:
> Forge installed + Optifine installed

https://drive.google.com/file/d/1-0zStY-e496KDB_-tPADsa8zKO0eWLC5/view?usp=sharing 

> Optifine installed

https://drive.google.com/file/d/1ig7yMx0aTIyjQtztgmG5RJKaPfQR9eTp/view?usp=sharing

## Steps to Reproduce
1. Optifine installed as a mod under Forge
2. No shaders are enabled
3.  All settings are configured based on the video provided.

## OptiFine Version
OptiFine HD U G9 --- H1

## Installation Method
I installed it using the downloaded installer from Optifine page

## Fabric/Forge Version
Forge 37.0.95 --- 37.0.104

## Log Files/Crash Reports
https://pastebin.com/tYt2cPnP
https://pastebin.com/hfMGPpxm

## F3 Debug Screenshot
Please see Google Drive for screen recording

## Prior Testing
- Does this happen in Vanilla without OptiFine? Nope

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   - Only Forge
- Does this happen without any mods at all?
   - Only Forge by itself.
- Does this happen in OptiFine standalone? Nope
- Does this happen in Vanilla without OptiFine? Nope
- Have you tried using a binary search to find which mods cause this issue? I have but not necessary as I don't install other mods to check this one

**Comment by SSProgrammer00** [comment]
I have submitted the same report to Forge but according to the moderator.
"Optifine is notoriously invasive and just as notoriously closed-source.
If Optifine doesn't work properly when combined with Forge it is their issue to sort out as they can see exactly what happens inside Forge but we cannot do the same with Optifine." - from one of the moderators of Forge

"that's not a forge related error,
report this bug to Optifine but note Optifine is still in a preview version (the Forge compatible version you are using)" - from one of the members of the forum

**Comment by fayer3** [comment]
update to `OptiFine 1.17.1_HD_U_H2_pre1`, this was fixed recently

**Comment by Nuanulla** [comment]
Copy of #6349
