### ISSUE TITLE
[Error] Optifine Installer

### ISSUE THREAD

**Issue by Dawid102** [sp614x/optifine#6372]
On installer OptiFine_1.8.9_HD_U_M5.jar

Error:
File not found C:\Users\...\AppData\Roaming\.minecraft\launchers_profiles.json

Solution:
After installing minecraft launcher from microsoft store file have name: launcher_profiles_microsoft_store.json

Changing file name to launchers_profiles.json worked
And I had to change name back to launcher_profiles_microsoft_store.json

**Comment by WhoAteMyButter** [comment]
Duplicate of #6355
