### ISSUE TITLE
[Cape] Changed my username, swapped my cape and got a cape that wasnt even mine and I cant change or use my own cape.

### ISSUE THREAD

**Issue by DotScotts** [sp614x/optifine#6377]
## Description of Issue
I recently changed my username to "flxws" upon changing my cape user in the optifine login I went to use the cape editor to activate my cape. the name is spelt perfectly.
![image](https://user-images.githubusercontent.com/94135780/141348041-e92de263-ec94-4e7f-b6e6-8c6f1c6f0b68.png)
![image](https://user-images.githubusercontent.com/94135780/141348101-b4e6bbe8-07e8-4ab1-9fc0-4e0015467d0d.png)
![image](https://user-images.githubusercontent.com/94135780/141348150-5b0e35d9-69b4-4130-99b3-a84e53f1cf5c.png)
![image](https://user-images.githubusercontent.com/94135780/141348177-1c79e303-9dc3-4997-9eab-1fb2a15a0428.png)

I also now in game have a cape that doesn't belong to me.
![image](https://user-images.githubusercontent.com/94135780/141348246-e64decac-8624-4d4f-a309-0d023c817c72.png)
As upon going to my cape profile, It says my cape is invalid meaning I shouldn't be able to see this cape ingame
![image](https://user-images.githubusercontent.com/94135780/141348364-cc6a58ca-8e31-49d5-9561-e9ac99263d5a.png)
the cape set to my old mc name/account "Wopped" was a pure pink cape I've never created or used a cape like the one I can see ingame.

Ive looked for quick fixes or fixes in general, they either have no response or tell me the username is spelt wrong - its not.
I think I have a cape that belongs to someone else linked to my account and if there is no quick fix I wish for it to be removed from my current mc account.

**Comment by KaiAF** [comment]
I contacted the developer

**Comment by DotScotts** [comment]
> I contacted the developer

How long do they normally take? I can wait, im going to try again tmr

**Comment by KaiAF** [comment]
cape fixed on its own.
