### ISSUE TITLE
Optifine installer version is 3 dots

### ISSUE THREAD

**Issue by happyfied** [sp614x/optifine#6379]
I tried to install Optifine recently (and 1 month ago) and i can not install it because the version in the installer does not show up on all installers on my PC. I tried re-downloading them, and they still do not work. Could anyone help me?

![image](https://user-images.githubusercontent.com/91791966/141507568-9585d9d7-a98e-4d5c-9168-db5a0958cc77.png)

**Comment by fayer3** [comment]
for what version is that installer?

**Comment by happyfied** [comment]
> for what version is that installer?

1.17.1

**Comment by fayer3** [comment]
can you open the installer in the command line with `java -jar your_optifine_installer.jar`(replace that with the version you are trying to install)

**Comment by KaiAF** [comment]
If I remember right, this usually happens whenever the Windows user has a weird character like a space in it's username.

**Comment by fayer3** [comment]
I get it if my `.minecraft` is a symlink that has a non existing target, which then throws this error 
```
java.lang.RuntimeException: The working directory could not be created: C:\Users\Florian\AppData\Roaming\.minecraft
        at optifine.Utils.getWorkingDirectory(Utils.java:79)
        at optifine.Utils.getWorkingDirectory(Utils.java:52)
        at optifine.InstallerFrame.customInit(InstallerFrame.java:71)
        at optifine.InstallerFrame.initialize(InstallerFrame.java:401)
        at optifine.InstallerFrame.<init>(InstallerFrame.java:56)
        at optifine.InstallerFrame.main(InstallerFrame.java:115) ```
so it somehow cant create the .minecraft folder

**Comment by happyfied** [comment]
I don't have any

**Comment by happyfied** [comment]
> If I remember right, this usually happens whenever the Windows user has a weird character like a space in it's username.

I don't have any

**Comment by happyfied** [comment]
> can you open the installer in the command line with `java -jar your_optifine_installer.jar`(replace that with the version you are trying to install)

this shows up (i tried to open it with cmd)
![image](https://user-images.githubusercontent.com/91791966/141614386-1cf5608f-5447-45d8-b695-63884ac5a37f.png)

**Comment by happyfied** [comment]
Issue closed, i just had to put the installer into my C: drive.

**Comment by fayer3** [comment]
ah, so it was a permission issue
