### ISSUE TITLE
Shadercrash

### ISSUE THREAD

**Issue by Medusalem** [sp614x/optifine#638]
Forge: 13,20,0,2296
Optifine: 1,11,2_HD_U_B8

Crashlog: https://pastebin.com/ZaTsBCs0

Tested With Kuda Shaders and Sildur Shader, Game seems to be crashing because of a Vanilla Chest.

If i can offer anymore Information, i am willing to Search for them :)

**Comment by skmedix** [comment]
That's a result of latest changes in forge profiler

@sp614x
1.10.2:
https://github.com/MinecraftForge/MinecraftForge/pull/3887
https://github.com/MinecraftForge/MinecraftForge/commit/261313a682121aeb009fbaecfc0ec11c3c0eccfd

1.11.2:
https://github.com/MinecraftForge/MinecraftForge/pull/3873
https://github.com/MinecraftForge/MinecraftForge/commit/61d00dd05f918acf77dcfa96464a4d103bc243f2

**Comment by Builderb0y** [comment]
#634

**Comment by sp614x** [comment]
Install latest preview B9
