### ISSUE TITLE
[Entity] Hand/other entities flickering

### ISSUE THREAD

**Issue by IAmHasAGitHub** [sp614x/optifine#6382]
## Description of Issue
My character's first-person hand (and sometimes other entities) will flicker black when I use optifine.

## Steps to Reproduce
1. It kinda just happens when I'm in the game
## OptiFine Version
OptiFine HD U H1

## Installation Method
I was originally using Badlion Client with optifine when the bug started happening but i tested with just normal Optifine (normal installation method) and it still did the bug

## F3 Debug Screenshot
![2021-11-12_16 27 55](https://user-images.githubusercontent.com/94204965/141598235-566e0709-290a-4c27-ad52-596fb248c416.png)

## Prior Testing
- Does this happen in Vanilla without OptiFine?
no

## Additional Information
I have looked online for solutions to this issue but it seems like this hasnt happened to anyone else

**Comment by KaiAF** [comment]
This is most likely related to #6013 or #5891. I will close this. If it's not related please let me know, and show a video of the issue you are experiencing.
