### ISSUE TITLE
Optfine Resets/Changes Non-Optifine Keybinds

### ISSUE THREAD

**Issue by bmemike** [sp614x/optifine#6383]
## Description of Issue
If Optifine sees that its zoom keybind shares a key with another keybind -- even if that other key has a modifier -- it will remove that key from the keybind.

Ex 1: I have a keybind mapped to "c" and changed zoom to "ctrl+c". When I restart the game or reload textures (F3+T), the first keybind is removed and zoom remains as "ctrl+c". 

Ex 2: I set keybind 1 to "c". I set keybind 2 to "ctrl+o". I set zoom to "o". When I restart or reload textures, keybind 1 is fine (set to "c"), zoom remains bound to "o" and keybind 2 is simply "ctrl+" (yes, the "+" is still on the keybind!). The "o" has been removed. 

## Steps to Reproduce
See the above description for steps to reproduce.

## OptiFine Version
OptiFine_1.16.5_HD_U_G8

## Installation Method
Optifine is simply dropped into the mods folder.

## Fabric/Forge Version
Forge 36.2.2

## Other Installed Mods
https://pastebin.com/YPHC2UJT

## Log Files/Crash Reports
There are no crashes or references that I found in any of the logs.

## F3 Debug Screenshot
*attached*
![f3](https://user-images.githubusercontent.com/29279375/141664241-98fcf005-53d2-45c7-be7e-284918ee537c.png)

## Prior Testing
This is the only time I've experienced a keybind getting reset and it seems to be directly related to the key that optifine zoom is bound to (regardless of modifiers). I tested that this behavior persists when the zoom keybind both does and does not have modifiers and if zoom is bound to a key besides the default ("c").

## Additional Information
While I understand the logic behind why you'd want to avoid a keybind mismatch, the check should validate the presence of modifiers to DTRT (or this check could simply be disabled entirely).

**Comment by sp614x** [comment]
Fixed, coming in next preview.
