### ISSUE TITLE
optifine won't make new instalations anymore

### ISSUE THREAD

**Issue by distributer-on-discord** [sp614x/optifine#6385]
it's the same thing that happened in #1113, I have to seperatly install optifine every time I want to play a different version. When I install 1.8.9 for hypixel it deletes my 1.17.1 version, and vice versa. The name stays the same though. I can't find anything telling how to fix it.

**Comment by fayer3** [comment]
you can just make a separate installation profile with the other version.
go to the installation menu, press `new installation` and then select the optifine version in the version drop down
![grafik](https://user-images.githubusercontent.com/8282299/141679611-c0aebdda-a6e7-4aa1-b4df-32fd519df129.png)

**Comment by Jiingy** [comment]
Read above comment

**Comment by distributer-on-discord** [comment]
It wasn't there before, just went to go take a screenshot, now it is, weird
