### ISSUE TITLE
[Bug] My cape don't showing up in servers

### ISSUE THREAD

**Issue by MrCh4T** [sp614x/optifine#6388]
## Description of Issue
When i connect to a server like extremecraft, blockdrop, blockmc my cape isn't showing.

## Steps to Reproduce
just go on a server like extremecraft, blockdrop, blockmc.

## OptiFine Version
Badlion optifine version.

**Comment by TheKodeToad** [comment]
This sounds like a Badlion issue, so you may need to report it to Badlion. See [this support page](https://support.badlion.net/hc/en-us/articles/360013931400-Submit-a-Bug-Report) for more info.

**Comment by ZenIsBestWolf** [comment]
Invalid, contact support.
