### ISSUE TITLE
optifine 1.11.2 is crashing when open a world

### ISSUE THREAD

**Issue by 0142929** [sp614x/optifine#639]
minecraft 1.11.2
forge 13.20.0.2296
using default optifine configuration
trying OptiFine_1.11.2_HD_U_B7.jar and OptiFine_1.11.2_HD_U_B8.jar

[fml-client-latest.log](https://pastebin.com/fT516B8S)
[latest.log](https://pastebin.com/s4rGGRUG)
[crash-2017-05-13_16.23.45-server.txt](https://pastebin.com/wnUVvEUd)

**Comment by 0142929** [comment]
looks like this is compatibility problem, with forge 13.20.0.2228 working fine.
what forge version is 100% support now by OptiFine_1.11.2_HD_U_B8 ?

**Comment by 0142929** [comment]
" - compatible with Forge #2294" found in changelog of OptiFine_1.11.2_HD_U_B8
so better use 2294 for better compatibility?
trying with forge 2294 now...

**Comment by Builderb0y** [comment]
#634

**Comment by sp614x** [comment]
Install latest preview B9
