### ISSUE TITLE
[Bug] 1.17 - Optifine custom shaders overriding vanilla resourcepack shaders

### ISSUE THREAD

**Issue by LoneDev6** [sp614x/optifine#6391]
## Description of Issue
Seems Optifine is prioritizing its own shader system even if a shader is included in the resourcepack, this breaks functionality of some servers, mods and adventure maps which use vanilla shaders (remember that not everyone is using Optifine.)

In this case seems Optifine is overriding `rendertype_armor_cutout_no_cull` shader even if it's inside the resourcepack.

## Steps to Reproduce
1. install an Optifine shader which adds some lighting effects or similar.
2. install this vanilla shader resourcepack https://github.com/LoneDev6/VanillaCustomArmors
3. get one leather or normal armor and see its texture bugged because the VanillaCustomArmors shader is overridden by Optifine shader.

## OptiFine Version
OptiFine HD U G9

## Installation Method
mods folder

## Fabric/Forge Version
Fabric

## OptiFabric Version
OptiFabric-v1.11.20

## Other Installed Mods
None

## Prior Testing
If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   - Only OptiFine, OptiFabric, and Fabric
- Does this happen without any mods at all?
   - No
- Does this happen in Vanilla without OptiFine?
No
- Have you tried using a binary search to find which mods cause this issue?
 Yes

### Solutions
Just avoid loading a shader if it's already included in the resourcepack.

### With Optifine and an Optifine custom shader
![immagine](https://user-images.githubusercontent.com/27242001/142182633-a419ac4a-9176-4fd5-957f-3063bc6d93d4.png)

### Without Optifine
![immagine](https://user-images.githubusercontent.com/27242001/142182718-4be22e29-422f-4ee9-8ad5-2947c6c17115.png)

**Comment by purejosh** [comment]
@sp614x this has been open for over 2 months and hasn't had a single comment on it. What's going on?

**Comment by LoneDev6** [comment]
I doubt this can be fixed if this works the same way Iris Shaders work: https://github.com/IrisShaders/Iris/issues/1042#issuecomment-997032292

I have another solution for this and will be implemented in the next weeks

**Comment by sp614x** [comment]
The OptiFine shaders don't overwrite single render types or vanilla shaders. Instead they use separate programs for different rendering tasks (blocks, entities, environment) regardless of the render types that those may be using.

**Comment by PystoyPlayer** [comment]
> ## Description of Issue
> Seems Optifine is prioritizing its own shader system even if a shader is included in the resourcepack, this breaks functionality of some servers, mods and adventure maps which use vanilla shaders (remember that not everyone is using Optifine.)
> 
> In this case seems Optifine is overriding `rendertype_armor_cutout_no_cull` shader even if it's inside the resourcepack.
> 
> ## Steps to Reproduce
> 1. install an Optifine shader which adds some lighting effects or similar.
> 2. install this vanilla shader resourcepack https://github.com/LoneDev6/VanillaCustomArmors
> 3. get one leather or normal armor and see its texture bugged because the VanillaCustomArmors shader is overridden by Optifine shader.
> 
> ## OptiFine Version
> OptiFine HD U G9
> 
> ## Installation Method
> mods folder
> 
> ## Fabric/Forge Version
> Fabric
> 
> ## OptiFabric Version
> OptiFabric-v1.11.20
> 
> ## Other Installed Mods
> None
> 
> ## Prior Testing
> If you've installed using Forge/Fabric:
> 
> * Does this happen without other mods installed?
>   
>   * Only OptiFine, OptiFabric, and Fabric
> * Does this happen without any mods at all?
>   
>   * No
> * Does this happen in Vanilla without OptiFine?
>   No
> * Have you tried using a binary search to find which mods cause this issue?
>   Yes
> 
> ### Solutions
> Just avoid loading a shader if it's already included in the resourcepack.
> 
> ### With Optifine and an Optifine custom shader
> ![immagine](https://user-images.githubusercontent.com/27242001/142182633-a419ac4a-9176-4fd5-957f-3063bc6d93d4.png)
> 
> ### Without Optifine
> ![immagine](https://user-images.githubusercontent.com/27242001/142182718-4be22e29-422f-4ee9-8ad5-2947c6c17115.png)

Personally, I have a bug without shaders either (but with OptiFine mod installed)
![Uploading 70E4CED1-84AC-4636-B539-15BD7F7FBDBE.png…]()

**Comment by PystoyPlayer** [comment]
> I doubt this can be fixed if this works the same way Iris Shaders work: [IrisShaders/Iris#1042 (comment)](https://github.com/IrisShaders/Iris/issues/1042#issuecomment-997032292)
> 
> I have another solution for this and will be implemented in the next weeks

Personally, I have a bug without shaders either (but with OptiFine mod installed)
![4B28014B-26EC-4451-85E6-146D0FAC473D](https://user-images.githubusercontent.com/88878911/169607908-89c41ed9-dcb9-4582-962f-7ba38b22757c.png)

**Comment by bladeRR** [comment]
any update?

**Comment by LoneDev6** [comment]
Developer of Optifine already answered.

> Vanilla shaders and OptiFine shaders can't be mixed together.
If the vanilla shader is overwritten then the geometry is probably rendered in a custom buffer or multiple buffers with custom format/projection/encoding/etc.
The shader packs can organize the rendering pipeline in many different ways and vanilla shaders couldn't know where they should write to and in which format.
