### ISSUE TITLE
[Optifine Installer] Allow extracting Optifine MOD jar with the absence of Minecraft Official Launcher versions

### ISSUE THREAD

**Issue by minhngoc25a** [sp614x/optifine#6393]
## Description of the new feature

It's currently hard to install Optifine on an instance-based launcher like MultiMC because MultiMC uses a different file handling system. To install OptiFine on MultiMC without any dependence on modding systems, it's required to use the Optifine MOD jar. The way sp614x designs the OptiFine installer makes it impossible to extract the MOD jar file with the absence of an official Minecraft version installation. 

I'm against using the official launcher because it's such bloatware and time-consuming when I have to change the files to play older servers. MultiMC disabled Forge installation for 1.17 because of major code changes. On Fabric, OptiFabric is currently broken with the latest OptiFine. So the only way left to install Optifine is the MOD jar way. I don't want to be forced to download 1.17.1 just to extract the MOD jar, because that's redundant. Therefore, my suggestion is to allow extracting Optifine MOD jar with the absence of official Minecraft versions as a default option for Optifine installers from now on.

**Comment by treysis** [comment]
How is this issue still open?

**Comment by uforek** [comment]
Because it was never fixed

**Comment by IMS212** [comment]
That’s not how it works, though.

The MOD jar mixes an official version jar with the optifine patches to get what you would normally get pre-1.6, a fully patched game.

It is impossible to do this extraction without a jar file.

**Comment by MoustacheOff** [comment]
Still, it's possible with a launcher like MultiMC to download official jars from Minecraft's servers.
This issue should be re-opened.

**Comment by cryolithic** [comment]
> > Still, it's possible with a launcher like MultiMC to download official jars from Minecraft's servers. This issue should be re-opened.
> 
> This is requesting a different enhancement; allowing you to select a custom jar file in the absence of the MC one.
> 
> This is already possible with command line flags as well.

For us coming here from google, it'd be nice if you had included the flags necessary.

**Comment by DiiaBlood** [comment]
Found another method:

1. Create ``.minecraft/versions/1.X.X`` folder in your Appdata folder
2. From ``Appdata/Roaming/Prism/instances``, copy all the content of the version of minecraft your optifine is specified for and dump it in the newly created folder from step 1.
3. From ``Appdata/Roaming/Prism/libraries\com\mojang\minecraft\1.X.X``, get the ``minecraft-1.X.X.jar`` and dump it into the folder from step 1.
4. Rename the file from ``minecraft-1.X.X.jar`` to just ``1.X.X.jar``.
5. Run Optifine extracter, and if everything went smoothly, you should get the functioning MOD jar file.
6. Delete the entire folder from step 1 and enjoy.

**Comment by Cheddarness** [comment]
> Found another method:
> 
>     1. Create `.minecraft/versions/1.X.X` folder in your Appdata folder
> 
>     2. From `Appdata/Roaming/Prism/instances`, copy all the content of the version of minecraft your optifine is specified for and dump it in the newly created folder from step 1.
> 
>     3. From `Appdata/Roaming/Prism/libraries\com\mojang\minecraft\1.X.X`, get the `minecraft-1.X.X.jar` and dump it into the folder from step 1.
> 
>     4. Rename the file from `minecraft-1.X.X.jar` to just `1.X.X.jar`.
> 
>     5. Run Optifine extracter, and if everything went smoothly, you should get the functioning MOD jar file.
> 
>     6. Delete the entire folder from step 1 and enjoy.

k i tried this and it didnt work :(
