### ISSUE TITLE
[Bug][1.17.1] Key Modifiers are unable to be used

### ISSUE THREAD

**Issue by jmg302** [sp614x/optifine#6399]
## Description of Issue
When logging in all Modifiers are stripped from keybinds.  
Unable to map a Modifier to keybind after loading in either.

Example 1: CTRL+1 is bound to an action once logging in the mapping is reverted to just 1.  
Example 2: Attempt to map CTRL+1 and reverted to 1.

Options file is rewritten with all of the additional modifiers stripped.

## Steps to Reproduce
1. Set Keybinding in Options-> Controls with a Modifier without Optifine loaded but with Forge Loaded
2. Close and load in with Optifine. 
3. Go to Options-> Controls and see modifiers have been stripped
4. Attempt to rebind with Modifier and modifier is not saved.

## OptiFine Version
OptiFine_1.17.1_HD_U_H1

## Installation Method
Dropped Jar into Mods folder

## Fabric/Forge Version
37.0.103

## Other Installed Mods
None, reproduced on fresh installation with just Forge

## F3 Debug Screenshot
![image](https://user-images.githubusercontent.com/6303488/143078236-86f2a450-ec8e-4b73-9cc7-8e9ac935bafd.png)

## Prior Testing
- Does this happen without other mods installed? 
      Only OptiFine and Forge
- Does this happen without any mods at all?
      Only Forge by itself.
- Does this happen in OptiFine standalone? 
      Unable to test as Forge provides the key modifier capability

**Comment by bmemike** [comment]
I reported similar behavior: #6383

In your situation, are all modifiers being affected even for keybinds that are unrelated to optifine actions?

**Comment by jahirtrap** [comment]
Same in 1.18

**Comment by KaiAF** [comment]
Addressed at #6383
