### ISSUE TITLE
1.18 pre 1 optifine bug

### ISSUE THREAD

**Issue by zTwinBrosMC** [sp614x/optifine#6400]
## Description of Issue

there's no view bobbing option + chunk doesn't render properly with fast render on and lag with optifine
## Steps to Reproduce
install 1.18 pre 1 optifine

## OptiFine Version
 1.18 pre 1 optifine

## Installation Method
 from optifine.net

**Comment by fayer3** [comment]
The view bobbing option was moved to the details submenu.

**Comment by Jiingy** [comment]
See previous comment for closure reason
