### ISSUE TITLE
[bug] 1.18 pre-release-1 Pressing F3+A causes some blocks in the chunk the player is standing in to load in slower

### ISSUE THREAD

**Issue by fayer3** [sp614x/optifine#6401]
## Description of Issue
the optimized chunk culling from OptiFine 1.18-pre1_HD_U_H3_pre2 seems to be having difficulties loading the chunk the player is in.
it can take a pretty long time with lower frame rate to load the current chunk.

## Steps to Reproduce
1. press F3+A to reload chunks
2. see all blocks in the current chunk are invisible

## OptiFine Version
OptiFine 1.18-pre1_HD_U_H3_pre2

## Installation Method
standalone installer,

## F3 Debug Screenshot

![2021-11-25_20 28 03](https://user-images.githubusercontent.com/8282299/143492930-a2dce34e-1725-4f29-89cf-11d93946296d.png)

video reloading chunks:

https://user-images.githubusercontent.com/8282299/143492958-76fe700b-bb5d-47c1-aadf-ed3c429412c6.mp4

**Comment by zTwinBrosMC** [comment]
Same 
Laptop Specs

Intel Core i3 6006U
8gb ram
Allocated Minecraft Ram - 4 gb
Intel Graphics 520

**Comment by fayer3** [comment]
seems fixed with OptiFine 1.18-pre1_HD_U_H3_pre3
