### ISSUE TITLE
[Optifine 1.17.1 Bug] Entities and buildings taller than the 256 limit glitch and start to flicker

### ISSUE THREAD

**Issue by JinxLaJoker** [sp614x/optifine#6404]
## Description of Issue
I found a bug with 1.17.1 Optifine when using datapacks that exceed the traditional build height limit of 256 and I think it could possibly happen with 1.18, Any blocks and entities that are placed taller than 256 block height seem to flicker, the datapack I'm using has a Y of -128 to 512, the flickering starts around the height of 128 where the normal max height would be if -128 was 0

## Steps to Reproduce
1. use any datapack that has a modified Y build limit and Optifine
2.  build something above the standard 256 limit to find this bug, the flickering may appear lower than 256 if the datapack allows generation below 0

## OptiFine Version
<Optifine HD U H1

## Installation Method
 I use the standalone installer.

**Comment by KaiAF** [comment]
Reported here #5768
