### ISSUE TITLE
[Feature Request] nbt matching for Random Entities

### ISSUE THREAD

**Issue by Decrepitdoors** [sp614x/optifine#6406]
Currently CEM is limited to a few set matches, would it be possible to match nbt, like in CIT? If not full NBT, at least just CustomModelData? This would make creating custom mobs a lot easier as we can set data using a datapack.

**Comment by TheSweatyYeti** [comment]
Yes please

**Comment by Decrepitdoors** [comment]
I meant to say Random_Entities not CEM, CEM seems to have no way to match NBT for the model. RE has a few already, but I'd love to be able to match a custom tag with Random Entities and CEM

**Comment by ZenithRogue** [comment]
Added nbt checks to random entities in OptiFine 1.19.2_HD_U_I1_pre1
