### ISSUE TITLE
I can't use shaders. What do I do?

### ISSUE THREAD

**Issue by Gamingwithmoji** [sp614x/optifine#6407]
I installed optifine looking to use it for shaders. After a while of having optifine installed  the shader button was gray and I couldn't click it. What do I do?

1. Have optifine installed for a while
2. Go to the shaders button in setting

OptiFine Version 1.17

Installed optifine with standalone 

Forge is the only thing I can recall

I don't know if it's happened on Vanilla because I don't have it.

**Comment by fayer3** [comment]
what optifine version are you using, it sounds like you are using an outdated version, that didn't have shaders yet.

**Comment by Jiingy** [comment]
Early pre-versions had shaders disabled while they were being implimented, try updating to the latest version, and that should solve your issue.
