### ISSUE TITLE
Entity shadows sometimes use different shader programs than normal

### ISSUE THREAD

**Issue by Builderb0y** [sp614x/optifine#641]
Normal mobs use gbuffers_entities for their shadows, but spiders and endermen use gbuffers_spidereyes. Additionally, players and enchanted dropped items use gbuffers_hand. It would be much easier to deal with shadows if they were all using the same program. Given that I'm currently detecting shadows based on gl_Color.a, it may even be worthwhile to add a dedicated program for them; since some entities (like XP orbs) actually have a semi-transparent color multiplier, and therefore I have to add custom support for them.

**Comment by sp614x** [comment]
Looks like a bug

**Comment by Builderb0y** [comment]
After a bit more testing, I found a few more things which are using inconsistent programs: (not related to shadows though, so not sure if this should be a separate issue or not)

Normal armor uses gbuffers_entities when equipped on players, but elytras and pumpkins use gbuffers_hand. Technically all blocks/items which can render on the player do this, but elytras and pumpkins are the only two that I know of which can be equipped normally without using commands or inventory editors. All items use gbuffers_entities when equipped as armor on non-player entities regardless of weather or not they are actually armor-type items.

Held items use gbuffers_entities when held by non-player entities, but gbuffers_hand when held by other players.

Lastly, dropped items and XP orbs both use gbuffers_entities normally, but gbuffers_textured_lit during their pickup animation.

**Comment by sp614x** [comment]
Interesting

**Comment by sp614x** [comment]
Updated preview B9
- fixed entity shadows using wrong shader programs (spiders, players, enchanted items)

All of the problems should be fixed except maybe the pickup animation.

**Comment by Builderb0y** [comment]
You would be correct. All of them are fixed except the pickup animation. Also just discovered that the pickup animation bug also applies to other entities picking up items, not just the player in first person.

**Comment by sp614x** [comment]
The pickup animation is implemented as a particle effect, not as a real entity. Looking into it.

**Comment by sp614x** [comment]
Updated preview B9
- fixed item pickup animation using wrong shaders program

**Comment by Builderb0y** [comment]
Can confirm it works now. Thanks!
