### ISSUE TITLE
[Variated Entities] random_entities.properties doesn't support new 1.18 negative height values

### ISSUE THREAD

**Issue by bennyd87708** [sp614x/optifine#6413]
## Description of Issue
If you try to use a negative height in the range for the random_entities.properties since 1.18 worlds can now go below y = 0, the range doesn't work. For instance "heights.1=-64-0" should apply to mobs in the range between y = -64 and y = 0, but it instead applies to mobs in the range y = 0 to y = 64.

## OptiFine Version
1.18 OptiFine HD U H3 pre4

**Comment by ZenithRogue** [comment]
fixed in `1.18.1_HD_U_H5_pre2`

**Comment by ZenithRogue** [comment]
oops, not resolved, fix was for CTM

**Comment by sp614x** [comment]
Negative values have to be put in brackets: `"heights.1=(-64)-0"`.
It was fixed in one of the 1.18.1_HD_U_H5 previews for random entities, custom sky, CTM and custom GUIs.
