### ISSUE TITLE
[1.18] Crash after joining the world

### ISSUE THREAD

**Issue by juliocoliveira** [sp614x/optifine#6414]
## Description of Issue
If I put optifine to load it crashes, just after opening a single player world.

## Steps to Reproduce
1. What do you do...
Just use optifine on 1.18 world

## OptiFine Version
OptiFine HD U H3 pre4

## Installation Method
I'm using Optifabric + Optifine on mods folder

## Fabric/Forge Version
Fabric 0.12.6

## OptiFabric Version
1.12.6 (Modified to load 1.18 minecraft)

## Other Installed Mods
 architectury-3.0.39
  [✔️] cloth-config-6.0.42-fabric
  [✔️] collective-fabric-1.18.x-3.9
  [✔️] cr-compass-ribbon-fabric-2.7.5+1.18
  [✔️] fabric-api-0.43.1+1.18
  [✔️] modmenu-3.0.0
  [✔️] optifabric-1.12.6
  [✔️] preview_OptiFine_1.18_HD_U_H3_pre4
  [✔️] replantingcrops-fabric_1.18.x-2.5
  [✔️] RoughlyEnoughItems-fabric-7.0.339
  [✔️] wthit-fabric-4.2.0
  [✔️] Xaeros_Minimap_21.22.3_Fabric_1.18
  [✔️] XaerosWorldMap_1.18.4_Fabric_1.18

## Log Files/Crash Reports
(https://pastebin.com/bbgHBdga)

## F3 Debug Screenshot
Can't hit F3 the game crashes before it.

## Prior Testing
No, without optifine it works just fine.

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   - Only OptiFine and Forge
   - Only OptiFine, OptiFabric, and Fabric No
- Does this happen without any mods at all?
   - Only Forge/Fabric by itself. No
- Does this happen in OptiFine standalone? It works fine.
- Does this happen in Vanilla without OptiFine? No
- Have you tried using a binary search to find which mods cause this issue? No
   - To find conflicting mods, split your mods into 2 groups (not including OptiFine/OptiFabric, obviously). Remove one group, and test in-game. Keep the group that has the problem, and repeat until no more mods can be removed without the issue disappearing.
   - Does the issue still happen with only the remaining mods installed?
      - Forge/Fabric and remaining mods, without OptiFine --> No

## Additional Information
![crash](https://user-images.githubusercontent.com/6606725/144246477-f6c2857e-8d96-40a7-9988-986ffc8697ed.png)

**Comment by TheKodeToad** [comment]
It seems that OptiFabric hasn't been updated yet.

**Comment by juliocoliveira** [comment]
Yes it does not, Still it works for 1.18-pre1, so it should work fine for 1.18, I just modified the jar to load 1.18.
The issue seams a Optfine issue not a Optifabric issue.

**Comment by UnderseaKnight** [comment]
How did you modify optifabric to work for 1.18 optifine? I didn't know you could do that.

**Comment by juliocoliveira** [comment]
You have to modify the file "fabric.mod.json" inside the optifabric jar on the "depends": {
    "fabricloader": ">=0.8.0",
    "minecraft": [
      "1.16.1",
      "1.16.2",
      "1.16.3",
      "1.16.4",
      "1.16.5",
      "1.17-alpha.21.8.b",
      "1.17-beta.4",
      "1.17",
      "1.17.1",
      "1.18-beta.1"``
and add , on the last line, And add "1.18" on a new line.

**Comment by juliocoliveira** [comment]
But this is definitively a OptiFabric outdated issue, I just loaded a standalone optifine installation and it loads the world just fine.
I'll wait for a official OptiFabric update.
Thanks anyway.
