### ISSUE TITLE
[bug] [1.18] placing blocks into an empty sub chunk doesn't immediately render it

### ISSUE THREAD

**Issue by fayer3** [sp614x/optifine#6415]
## Description of Issue
when placing blocks into an empty sub chunk (16x16x16 area) the sub chunk doesn't get rendered immediately, even with chunk builder set to `Fully Blocking`

## Steps to Reproduce
1. get into a completely empty sub chunk (16x16x16 area), with only air
2. place a block
3. see that it's invisible, and will only render after some time

## OptiFine Version
OptiFine_1.18_HD_U_H3_pre4

## Installation Method
standalone installer

## F3 Debug Screenshot
![grafik](https://user-images.githubusercontent.com/8282299/144259714-2d5e7ae9-a252-4fc8-8770-5909bab9ce4c.png)

https://user-images.githubusercontent.com/8282299/144260919-ceb497d7-6cd7-464d-87ed-a2961c266263.mp4

## Additional Information
maybe connected to #6401

**Comment by sp614x** [comment]
Fixed, coming in next preview.

**Comment by fayer3** [comment]
might not be completely fixed, but happens less.
building a tower can still produce the issue
here a video with the release 1.18 H3 and fully blocking chunk builder

https://user-images.githubusercontent.com/8282299/144932471-729ae68b-270c-420e-aac9-be15d1faaa52.mp4

**Comment by sp614x** [comment]
Seems to happen more often when the game is actively loading chunks.
Pressing F3+A and immediately placing a block in an empty chunk triggers it more often, but always.

**Comment by Tencryn** [comment]
I'm facing this issue every time I build into an empty chunk on version HD U H5 pre2
