### ISSUE TITLE
audio menu frezing

### ISSUE THREAD

**Issue by MinecraftedGaming** [sp614x/optifine#6417]
## Description of Issue
i was trying to link both my computers audio from spotify together and i had to mute mc and when i tabbed back a few minutes later it was on (not responding) status and i waited a few min and it would not unfreze has to force close it

## Steps to Reproduce
1. launch {optifine_1.18_HD_U_H3_pre4}
2. tab to other app for a few seconds
3. tab back and go to options>audio and mute master volume with all other sliders at 100% (device: system default)
4. tab out for about 5 minutes
5. tab back and stare at it not responding

## OptiFine Version
{optifine_1.18_HD_U_H3_pre4}

## Installation Method
optifine_website > 1.18_catagory > download > open {preview_OptiFine_HD_U_H3_pre4.jar} > (download 1.18 update because i didnt have it before) > press install button > open on launcher

## Log Files/Crash Reports
not crash just frozen

## F3 Debug Screenshot
never opened a world this was first time launch

## Prior Testing
<!-- If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
no

## Additional Information
if you need any more info try to dm Minecrafted Gaming#5536 on discord because i never really go on github unless i have to
(app i tabbed over to was opera gx)

**Comment by KaiAF** [comment]
Can you go to `.minecraft\logs` and send the log called "latest.log" after reproducing this? There may be errors in the log file that might help. I tried what you said and I was not able to reproduce this.

**Comment by Jiingy** [comment]
Not able to reproduce, and no follow-up with original poster in almost 2 years.
