### ISSUE TITLE
[1.18 OptiFine HD U H3 pre5] Dynamic Lights Lag

### ISSUE THREAD

**Issue by HenkoHallows** [sp614x/optifine#6420]
## Description of Issue
When turning on Dynamic Lights, the game get's massive lag/stutter

## Steps to Reproduce
1. Turn on Fancy Dynamic lights.

## OptiFine Version
1.18 OptiFine HD U H3 pre5

## Installation Method
Through .jar

## Prior Testing
<!-- If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
- No the option isn't there in vanilla

**Comment by fayer3** [comment]
whats your chunk builder setting set to? threaded, semi blocking or fully blocking?

**Comment by HenkoHallows** [comment]
It's Fully Blocking.

**Comment by Sanans1337** [comment]
Had the same issue. These lags only appear if your chunk builder setting is set to fully blocking. When I set it to semi blocking or threaded, it works perfectly for me. No lags/stutters at all. Thanks to @fayer3 for giving me an idea of what to do.

**Comment by HenkoHallows** [comment]
Ah thank you ^^

**Comment by sp614x** [comment]
Fixed, coming in next preview.
