### ISSUE TITLE
Game crashes when using a portal.

### ISSUE THREAD

**Issue by Smichealkelly** [sp614x/optifine#6421]
## Description of Issue

Whenever I enter or leave the nether, my game crashes.
## Steps to Reproduce
1. What do you do...
2. ...to find this bug?
Enter or leave the nether, the end portal does the same thing.
## OptiFine Version

1.18 pre5, same thing happened with 1.17.2
## Installation Method

I used the included standalone installer. 

## Log Files/Crash Reports

Not sure if there are any relevant log files

## F3 Debug Screenshot

![Debug Screenshot](https://user-images.githubusercontent.com/95453624/144527123-0fe7c121-219e-46a7-9564-649693b2ae4c.png)
## Prior Testing
<!-- If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
No it does not

**Comment by Smichealkelly** [comment]
Prior testing and additional comments would not show up, but it does not happen with vanilla Minecraft. I have also made sure all my drivers are up to date.

**Comment by fayer3** [comment]
does it happen without shaders?

**Comment by Smichealkelly** [comment]
No it does not happen without shaders.

**Comment by fayer3** [comment]
Does it also happen with the recommended driver, instead of latest?

**Comment by Smichealkelly** [comment]
Hey, so i noticed it only crashes when I am using Sonic's unbelievable shaders so I just started using BSL thank you though

**Comment by KaiAF** [comment]
Could you provide a crash log?

**Comment by Jiingy** [comment]
No crash log provided in almost 2 years, closing.
