### ISSUE TITLE
Sometimes blocks don't render.

### ISSUE THREAD

**Issue by Krone9891** [sp614x/optifine#6423]
## Description
Sometimes when I place a block it does not render, this has happened way to many times.

## Steps to get the Bug
So I was bridging in the end and i changed my window to discord from minecraft, after I changed back to minecraft and i started placing blocks, some did not render. (they eventually rendered)

## OptiFine Version
OptiFine HD U H3 pre5

## Installation Method
I just use OptiFine without anything else, i downloaded OptiFine when double clicked the jar then clicked install, and it installed normally.

## Fabric/Forge Version
I use OptiFine standalone.

## OptiFabric Version
I use OptiFine standalone.

## Other Installed Mods
No mods installed, I use OptiFine standalone.

## Log Files/Crash Reports
The game doesn't crash.

## Prior Testing
No, i have never noticed it happen in vanilla.

**Comment by fayer3** [comment]
sounds similar to #6415 and #6419

**Comment by KaiAF** [comment]
Related #6415 and #6419
