### ISSUE TITLE
[1.18 Forge] The game instantly crashes on startup

### ISSUE THREAD

**Issue by StrixTyphoon** [sp614x/optifine#6424]
## Description of Issue
When i launch forge with optifine installed it instantly crashes before the game even opens fully

## Steps to Reproduce
1. Launch Minecraft with Forge and optifine

## OptiFine Version
1.18 HD U H3 pre5

## Installation Method
extracted the mod and put it into my mods folder

## Fabric/Forge Version
 Forge 1.18 38.0.10

## Other Installed Mods
Clumps - 1.18 8.01
journeymap - 1.18 5.8.0alpha2
MouseTweaks - 1.18 2.16

## Log Files/Crash Reports
https://pastebin.com/r79S6Tin

## F3 Debug Screenshot
unable to even get into the game

## Prior Testing
If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   - Only OptiFine and Forge
   Yes, The problem still persists
- Does this happen without any mods at all?
   No
- Does this happen in OptiFine standalone?
   Yes when i install it with forge but No when i install with included installer
- Does this happen in Vanilla without OptiFine?
   No
- Have you tried using a binary search to find which mods cause this issue?
   Yes they all work until i add optifine
   - Does the issue still happen with only the remaining mods installed?
      No

## Additional Information
![image](https://user-images.githubusercontent.com/85808692/144610726-9888c1c9-9cd2-46f1-84c3-4a1d431fa510.png)

**Comment by fayer3** [comment]
Optifine 1.18 is not yet compatible with forge

**Comment by StrixTyphoon** [comment]
I had no idea thanks for telling me.
