### ISSUE TITLE
[Category] Short description

### ISSUE THREAD

**Issue by dannyxxv** [sp614x/optifine#6428]
My Cape doesn't work as has glitched since i changed my ign and is showing the follow glitch:

![image](https://user-images.githubusercontent.com/95513923/144695220-92f6e7d2-d34b-471d-b733-9ad1e8e9d61a.png)

## OptiFine Version
1.17.1

**Comment by dannyxxv** [comment]
donator email: dannyxxv005@gmail.com

**Comment by KaiAF** [comment]
Contacted the developer about this. I deleted the comment with your email as that is not needed

**Comment by dannyxxv** [comment]
Ok, thanks!

**Comment by KaiAF** [comment]
cape should be fixed
