### ISSUE TITLE
Lighting Errors in Certain Shaders / Texture+Block rendering errors in others.

### ISSUE THREAD

**Issue by JairusBGit** [sp614x/optifine#6431]
## Description of Issue
There are lighting errors in certain shaders and texture/block rendering errors in others.

## Steps to Reproduce
1. Use the respective shaders mentioned
2. Regularly play Minecraft

## OptiFine Version
OptiFine HD U H3 pre5

## Installation Method
Standalone installer.

## F3 Debug Screenshot
Shaders listed in F3 details

![2021-12-04_21 16 28](https://user-images.githubusercontent.com/90632513/144710925-efe44f18-2428-4981-ac2b-117d907a6bde.png)

![2021-12-04_21 15 13](https://user-images.githubusercontent.com/90632513/144710927-c33327a2-8567-4156-80d0-661f1ab6baf7.png)

## Prior Testing
<!-- If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
It does not.

- Does this happen in Vanilla without OptiFine?
It does not.

## Additional Information
N/A

**Comment by JairusBGit** [comment]
The bug has also been reported to occur on the "pre6" version
![2021-12-04_21 30 37](https://user-images.githubusercontent.com/90632513/144711376-e9939c7e-5a4c-4d64-9a8d-9cdcc7e247e9.png)
![2021-12-04_21 31 02](https://user-images.githubusercontent.com/90632513/144711377-607cfdd1-669e-4839-b2fa-17f35cebd665.png)
.

**Comment by fayer3** [comment]
are you using any resourcepack?

**Comment by JairusBGit** [comment]
I am only using the "Programmer Art" default texturepack.

**Comment by fayer3** [comment]
do you maybe have normal maps disabled in the shader settings?
![grafik](https://user-images.githubusercontent.com/8282299/144711665-5d859825-c408-45c3-a9ec-afb94a714895.png)

**Comment by JairusBGit** [comment]
I have normal maps disabled in the settings. I'll try turning it on and report my results.

**Comment by JairusBGit** [comment]
Turning on Normal Maps appeared to fix the problem. Thank you
![2021-12-04_21 43 45](https://user-images.githubusercontent.com/90632513/144711751-719252d7-c478-4c36-9e7f-3f1b5d4dc4c6.png)
.

**Comment by sp614x** [comment]
@fayer3 Cool fix
