### ISSUE TITLE
[Random Texture] Random textures of bee are broken

### ISSUE THREAD

**Issue by LeBonhommeBleu** [sp614x/optifine#6437]
## Description of Issue
When bees get angry or pollinate (when they change state), the could change their texture.

Exemple : a bee with texture bee.png is hit, its texture change from bee.png to bee_angry.png. If I add random textures, the texture could change from bee1.png to bee_angry2.png and it has to change from bee1.png to bee_angry1.png every time. The issue is clearest in this vidéo : https://youtu.be/arQQrGpyYYw

And here's the texture pack:
![Optifine issue](https://user-images.githubusercontent.com/81906404/144738572-58848510-0860-412e-a471-9bd0718149b3.png)

**Comment by MinecraftMinun** [comment]
You just need to make separate .properties files for `bee_angry`, `bee_nectar` and `bee_angry_nectar`

**Comment by LeBonhommeBleu** [comment]
> You just need to make separate .properties files for `bee_angry`, `bee_nectar` and `bee_angry_nectar`

Thank you ! It work !

**Comment by MinecraftMinun** [comment]
> 

No worries! It's an issue I've run into previously, though with wolves.
