### ISSUE TITLE
[CEM Support] Glow Squid not supported

### ISSUE THREAD

**Issue by hg456wilkos** [sp614x/optifine#6438]
## Steps to Reproduce
Use a texturepack using a custom glow_squid.jem model but wont be used in rendering in game

## OptiFine Version
1.18 H3 pre7

## Installation Method
Stand Alone

**Comment by ka128tte** [comment]
Optifine 1.18 HD U H3

![2021-12-07_18 42 51](https://user-images.githubusercontent.com/41300721/145079718-1eee1f7f-66b3-4c38-9f37-330a76b37c74.png)

![blockbench](https://user-images.githubusercontent.com/41300721/145079638-67d02237-8c6b-4fcb-92e0-a0249a743305.png)
Same model in blockbench

**Comment by ZenithRogue** [comment]
Added in latest optifine preview
