### ISSUE TITLE
[Bug] Text in game isn't sharp.

### ISSUE THREAD

**Issue by Entity2702** [sp614x/optifine#6439]
Text in game has like blur effect on it and it's not sharp.
![Text](https://user-images.githubusercontent.com/88882861/144749859-d3929fdf-ff12-40e2-a5e1-e297685f4816.png)

**Comment by fayer3** [comment]
Do you have JourneyMap installed?

**Comment by Entity2702** [comment]
Yes, I'm playing on All the mods 7

**Comment by fayer3** [comment]
then this is probably the same as #6281

**Comment by sp614x** [comment]
Duplicate of #6281
