### ISSUE TITLE
Blurred text when used with JourneyMap

### ISSUE THREAD

**Issue by joe1587joe** [sp614x/optifine#6441]
All minecraft text (chat, item names etc) become blurred when using Optifine HD U H3 Pre7 and Journeymap

**Comment by KaiAF** [comment]
Duplicate of #6281

**Comment by mysticdrew** [comment]
@joe1587joe 
I believe I fixed the issue, if you would like to verify it is fixed. Can you please head to the Journeymap discord and I can give you a test version.
