### ISSUE TITLE
[1.18] No tooltip for Chunk Builder option with Optifine, but in Vanilla yes. 

### ISSUE THREAD

**Issue by Axeloune** [sp614x/optifine#6442]
## Description of Issue
In Video Settings | Performance | the option Chunk Builder has no tooltip (black window with informations about the option) with OptiFine but in Vanilla, there is one.
If you can add it.

## Steps to Reproduce
Just go on Video Settings | Performance and let his mouse in the option button.

## OptiFine Version
1.18 pre8

## Installation Method
Just with the .jar, install.

## Prior Testing
This not happen in Vanilla.

**Comment by sp614x** [comment]
Fixed in OptiFine for 1.18.1
