### ISSUE TITLE
[Bug] Screenshots are 480p transparent images when antialiasing is enabled

### ISSUE THREAD

**Issue by h3oCharles** [sp614x/optifine#6443]
## Description of Issue

with antialiasing enabled, taking a screenshot produces a 480p transparent image

## Steps to Reproduce
enable antialiasing
restart
take a screenshot
look at screenshots folder

## OptiFine Version

OptiFine_1.18_HD_U_H3_pre7_MOD.jar

## Installation Method

fabric, in mods folder

## Fabric/Forge Version

fabric loader 0.12.8
fabric API 0.44.0 1.18

## OptiFabric Version

1.12.7

## Other Installed Mods

![image](https://user-images.githubusercontent.com/8020330/144770827-125731b9-2b68-466a-a780-bbd1ee4730f4.png)

## Log Files/Crash Reports

not applicable

## F3 Debug Screenshot

not applicable

## Prior Testing
not applicable...?

## Additional Information

for some dumb reason, this reddit post helped me get to this point
https://www.reddit.com/r/Optifine/comments/la77su/cant_screenshot_in_minecraft_by_zero_error/

**Comment by fayer3** [comment]
that was fixed with 1.18 pre8

**Comment by h3oCharles** [comment]
thx
