### ISSUE TITLE
[Shaders] Bug with world borders

### ISSUE THREAD

**Issue by lodo4nik** [sp614x/optifine#6444]
## Description of Issue
When I turning on shaders, world border turns yellow

## Steps to Reproduce
1. Enable shaders
2. Go to world borders

## OptiFine Version
1.18 HD_U_H3_pre8

## Installation Method
Standalone installer

## Log Files/Crash Reports
https://pastebin.com/QkatmrvT

## F3 Debug Screenshot
https://imgur.com/a/ZHEsosK

## Prior Testing
No

**Comment by sp614x** [comment]
This is a problem with the specific shader pack, can't be fixed by OptiFine.
