### ISSUE TITLE
[1.18] Biome grid template height

### ISSUE THREAD

**Issue by Guide1997** [sp614x/optifine#6445]
## Description of Issue

Changes to textures relative to biomes do not completely work on version 1.18

When will they be updated to version 1.18?
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/images/biome_grid_template.png
## Steps to Reproduce
1. What do you do...
2. ...to find this bug?
I put a picture and tried to increase its size up to 384 pixels.
It still works with Y coordinates = 0

All changes below 0 are accepted as the very last pixel of the picture from the bottom and from there the counting starts.
## OptiFine Version

OptiFine HD U H3 pre8

**Comment by sp614x** [comment]
Fixed, coming in next preview.
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/color.properties#L337
