### ISSUE TITLE
[1.18] Optifine mod jar not working with MultiMC

### ISSUE THREAD

**Issue by Lexian-droid** [sp614x/optifine#6448]
## Description of Issue

When trying to install optifine to MultiMC (MultiMC is a legal minecraft launcher that allows you to have multiple instances of the game installed separately, rather then the use of profiles in the actual launcher.)

You would install the other versions of optifine by creating an instance, opening "Edit instance" menu, and going to versions. You would extract Optifine and use that jar, you would click "Add to minecraft jar" and select the optifine mod file.

With optifine 1.18, this has caused the issue, optifine is installed the same way, but there aren't any error messages, the mod simply doesn't load.

## Steps to Reproduce
1. Extract optifine
2. Create a MultiMC instance
3. Right click on the newly created instance, and select "Edit instance"
4. Select "Version"
5. Select "Add to Minecraft.Jar"
6. in the file selector, select the extracted optifine mod.

## OptiFine Version
All versions of Optifine 1.18 these issues are present.

## Installation Method
I extracted the mod, and added it to my minecraft.jar (with MultiMC)

## Log Files/Crash Reports
There are none.

## F3 Debug Screenshot
The mod doesn't load in the first place.

## Additional Information
The mod would work fine on 1.17, this is the only version that doesn't work.
Additionally, there is a way to fix it, somewhat, it will break the mod, though.
The way to fix is to go to the notch folder within optifine's jar mod, and move all of those files into the main directory of optifine.
This will break most shaders.

**Comment by Lexian-droid** [comment]
Additionally, this wouldn't technically count as me asking for support in a third party launcher.
This is probably an issue with the jar mod itself. As stuff like forge might not be able to load the mod either.
This mod simply doesn't work anymore, suddenly.

**Comment by KaiAF** [comment]
Related, #6433

**Comment by LexBoosT** [comment]
Hello !, for MultiMC you have to do:

1-Double click on Optifine.jar, Extract Optifine to have Optifine Mod version.
2-Open Optifine Mod version with 7-zip.
3-Copy the "notch" folder to the desktop and delete it from Optifine Mod version.jar.
4-Copy the contents of the "notch" folder to the root of Optifine Mod version.jar.
5-Close 7-zip Optifine Mod version.jar.
6-On MultiMC, add to Minecraft.jar.
7-let's go!

**Comment by Lexian-droid** [comment]
> Hello !, for MultiMC you have to do:
> 
> 1-Double click on Optifine.jar, Extract Optifine to have Optifine Mod version. 2-Open Optifine Mod version with 7-zip. 3-Copy the "notch" folder to the desktop and delete it from Optifine Mod version.jar. 4-Copy the contents of the "notch" folder to the root of Optifine Mod version.jar. 5-Close 7-zip Optifine Mod version.jar. 6-On MultiMC, add to Minecraft.jar. 7-let's go!

Hello, i tried this already, however, doing this seems to break optifine, as when i did it, it seems to have caused a memory leak. Also, the console got spammed with errors, about missing dependencies and such.
Additionally, it breaks shaders, SEUS shaders get broken, a lot of lag issues will be in place when performing this fix.

I did exactly as mentioned, but it doesn't work unfortunately.
