### ISSUE TITLE
Crash eport with optifine w/ cleint side modset

### ISSUE THREAD

**Issue by Kylebartaous** [sp614x/optifine#645]
Mine craft version: 1.11.2

forge build: 13.20.0.2298

(Client side mods ) modset: ![minecraft cleint side modset](https://cloud.githubusercontent.com/assets/11208209/26080525/97205a3a-398c-11e7-9e94-52e1787bd029.PNG)

The Crash report log: [crash-2017-05-15_16.28.26-server.txt](https://github.com/sp614x/optifine/files/1002570/crash-2017-05-15_16.28.26-server.txt)

The Latest logs: [latest log.zip](https://github.com/sp614x/optifine/files/1002573/latest.log.zip)

It seems then trying to run optifine with that modset it it crashing then trying to load up a single player world or join a server.

**Comment by Kylebartaous** [comment]
Fixed in be release

**Comment by skmedix** [comment]
Duplicate of https://github.com/sp614x/optifine/issues/634
