### ISSUE TITLE
Optifine 1.18_HD_U_H3 crashes with Forge 1.18-38.0.14.

### ISSUE THREAD

**Issue by Cr4fTJuNkiE** [sp614x/optifine#6450]
## Description of Issue
The latest OF for 1.18 crashes Minecraft when used with Forge 1.18-38.0.14.

## Steps to Reproduce?
1) Drop Optifine 1.18_HD_U_H3 .jar into mods folder.
2) Run Forge Forge 1.18-38.0.14
3) Instantly crashes the launcher.

## OptiFine Version
Optifine 1.18_HD_U_H3

## Installation Method
Drop Optifine .jar into Forge "mods" folder.

## Fabric/Forge Version
Forge 1.18-38.0.14

## Other Installed Mods
NONE. Just Optifine!

## Log Files/Crash Reports
Crash Report:
[latest.log](https://github.com/sp614x/optifine/files/7676560/latest.log)
>

**Comment by fayer3** [comment]
works fine for me with forge 38.0.16, try re downloading optifine, maybe it's corrupted.

**Comment by Ari-RERA-43** [comment]
Are you putting the installer in the mods folder or extracting first and putting the extracted file in the mods folder?

**Comment by fayer3** [comment]
me? I put the installer directly in the mods folder.

**Comment by Ari-RERA-43** [comment]
> me? I put the installer directly in the mods folder.

I was addressing both of you. Maybe (if the issue creator) is using the extracted file it's an issue related to #6448

**Comment by Cr4fTJuNkiE** [comment]
No, I dropped the .jar file right into the mods folder. Just like I've always done. I'll try to redownload it.

**Comment by Cr4fTJuNkiE** [comment]
Even extracting the .jar to get OptiFine_1.18_HD_U_H3_MOD.jar crashes the launcher? No idea why?

**Comment by fayer3** [comment]
maybe its because of the spaces in your folder tree, can you try removing the spaces, and replacing the, with underscores for example, so it's `G:/Forge_1.18_Baby_/mods/OptiFine_1.18_HD_U_H3.jar`

**Comment by Cr4fTJuNkiE** [comment]
Nope. Still crashed. No difference. I do appreciate everyones help so far!

**Comment by Cr4fTJuNkiE** [comment]
Oh wat! I took out the "!" replaced it with "_" and it worked! Didn't notice that Fayer. Thank you sir!! Much appreciated.

**Comment by CatoConroy** [comment]
> Oh wat! I took out the "!" replaced it with "_" and it worked! Didn't notice that Fayer. Thank you sir!! Much appreciated.

Where do you see an "!"?

**Comment by fayer3** [comment]
> Where do you see an "!"?

it's their folders, they will know how they are called, I think the "!" got replaced with an "_" in the log. the log says `G:/Forge%201.18%20Baby_/mods/OptiFine_1.18_HD_U_H3.jar` which probably was `G:/Forge 1.18 Baby!/mods/OptiFine_1.18_HD_U_H3.jar`

**Comment by verbw001** [comment]
This is still an issue in Feb 2022 - Cannot get Optifine working to save my life.
