### ISSUE TITLE
Game crashes with latest Optifine release

### ISSUE THREAD

**Issue by iep1000** [sp614x/optifine#6452]
I would like to start by saying that the game loads fine when I am using Optifine HD U H3 pre7 installed. But with Optifine HD U H3 my world will crash. 

I am using CurseForge v. 0.187.2.0. I have installed Optifine HD U H3 as well as the latest Fabric API and OptiFabric. But whenever I try to open my world the game crashes and gives an error message. 

The game crashed whilst unexpected error
Error: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_6850 failed
Exit Code: 255

This is the full crash report - https://justpaste.it/9qbky

**Comment by Gerboa** [comment]
I had the same problem and reverting to pre7 works. I am also using latest Optifabric and Fabric API but am not using the CurseForge app.
[Optifine U H3 release crash.txt](https://github.com/sp614x/optifine/files/7683860/Optifine.U.H3.release.crash.txt)

**Comment by hg456wilkos** [comment]
I've got the same issue. It appears to start loading the world because my character gets a glimpse of the game with no blocks rendered in then boots me

**Comment by sp614x** [comment]
OptiFabric is updated and should work with OptiFine for 1.18.1.
