### ISSUE TITLE
CTM negative values in the heights parameters are read as positive values

### ISSUE THREAD

**Issue by Yekul10** [sp614x/optifine#6464]
## Description of Issue
Negative values in the `heights` parameters are read as positive values. The "-" before the number is read as a dash instead of a negative sign.

## Example:
```
method=fixed
tiles=deep_gravel
heights=-64-5
matchTiles=gravel
```

## Specifications
OptiFine Version:
OptiFine 1.18 HD U H3

Installation Method:
Standalone

## F3 Debug Screenshot
https://i.imgur.com/XynkMCt.png

**Comment by sp614x** [comment]
Duplicate of #6475
