### ISSUE TITLE
[CTM] CTM Textures for Red and Blue Stained Glass on Optifine 1.18 and 1.18.1 are not updated.

### ISSUE THREAD

**Issue by CasualWolfGamer** [sp614x/optifine#6465]
So I noticed that for Minecraft's patch notes for 1.18 that for the changes for blocks that it says, 
"Stained Glass 
Changed textures of blue stained glass and red stained glass, to match transparency of other types of stained glass."

So when I load up Optifine in 1.18, The textures for these two are still the old ones before the change. Here's some images to show that I'm not lying. I had my connected blocks off and on "fast" for these images. What you need to focus on is the outline of both blocks. The outline on the image that has connected blocks off is more transparent/translucent and the middle of the red and blue are less dark too. The one with connected blocks Fast has more of a solid outline and alot darker in the middle.
Connected Blocks On - Fancy is the same result as Fast btw with this.
![2021-12-10_15 50 03](https://user-images.githubusercontent.com/67299330/145655619-de03d189-e9fa-48e7-98fd-c5acdae9a012.png)
![2021-12-10_15 50 21](https://user-images.githubusercontent.com/67299330/145655624-5aa716a1-f9b6-4628-8ab3-e2fca91a760b.png)

**Comment by CasualWolfGamer** [comment]
You can notice the outline being solid better on the Red one.

**Comment by sp614x** [comment]
Fixed, coming in next preview.
