### ISSUE TITLE
(Fixed, what causes it?) [Loading Bug] Infinite loop on startup

### ISSUE THREAD

**Issue by OFlexan** [sp614x/optifine#6467]
## Description of Issue
So, I've found this bug randomly. Everything worked fine today as normal, but now when I start up OptiFine again after an hour or so it's stuck loading at 80%-ish and does not get further. It also hangs all networking processors on the computer (no internet available) without the internet icon changing. When I click the close button on Minecraft everything network-related I did on the computer instantly starts loading again and after a few seconds Minecraft closes (indicating that it was busy). After looking at the logs it was indeed stuck at an infinite loop: `Using missing texture, unable to load minecraft:textures/item/diamond_sword.png : java.io.FileNotFoundException: minecraft:textures/item/diamond_sword.png` (for every texture in the game). I have no idea how to fix this, so I can't really play on it right now.

## Steps to Reproduce
Unknown, as it randomly appeared

## OptiFine Version
1.17.1-OptiFine_HD_U_G9

## Installation Method
JAR installer, client

## Log Files/Crash Reports
[latest.log](https://github.com/sp614x/optifine/files/7697851/latest.log)
No crash report generated

## F3 Debug Screenshot
Cannot get in game to take screenshot

## Prior Testing
Does this happen in Vanilla without OptiFine?
- No, tested on latest release of 1.17.1

**Comment by OFlexan** [comment]
It suddenly works again, I did not do anything except for start it 2 more times:
- First time: No network hang, still errors and not loading
- Second time: Loaded fine and no errors

If someone could tell me why this error occurred suddenly and how it fixed itself, that would be great.

**Comment by sp614x** [comment]
On start Minecraft tries to authenticate the user via the Mojang authentication servers, this may be blocking for some reason. OptiFine shouldn't cause network traffic, except for a simple version check which is asynchronous and doesn't block.
