### ISSUE TITLE
[CTM] Unable to do Negative Numbers for hieghts, minHeight, and maxHeight in 1.18

### ISSUE THREAD

**Issue by TimmyChips** [sp614x/optifine#6475]
## CTM has a "heights" feature, and you can specify the height range where the ctm will take effect. However, it doesn't appear to work with negative heights.

If you were to have `heights=-64-0`, the affected blocks are not in the desired range, but rather it ranges from 0 to 64. There might be another way to specify one value is negative, but using the standard hyphen does not work.

I've also tried `maxHeight=0`, but that also doesn't work, in which case no block is affected on any y-level.

![height range no workey](https://user-images.githubusercontent.com/96088156/145899033-6b7d4dfd-9208-4608-aacc-ebcab2f675e7.png)

In this picture, the oak planks should look vastly different (old and cracked). But it's using the default textures since it doesn't recognize being below y-level 0.

**Comment by Regnander** [comment]
#6464

**Comment by sp614x** [comment]
Fixed CTM `minHeight` and `maxHeight` to accept negative values.
The property `heights` will be fixed later.

**Comment by sp614x** [comment]
Extended `heights` to allow negative values.
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/properties_files.txt#L174
