### ISSUE TITLE
[CEM] Elytra support for custom entity models

### ISSUE THREAD

**Issue by Shizzins** [sp614x/optifine#6492]
## Description of the new feature

I would really love it if elytra CEM would be supported soon. It would allow for many creative and amazing possibilities

**Comment by ewanhowell5195** [comment]
cem elytra falls under the same category as cem armor, so i don't think it will happen.

**Comment by ewanhowell5195** [comment]
also duplicate of #788

**Comment by ZenithRogue** [comment]
closed as duplicate
