### ISSUE TITLE
[Bug/OpenGL Error] 1.18 OpenGL Error "1282 (Invalid operation)"

### ISSUE THREAD

**Issue by QuatschVirus** [sp614x/optifine#6494]
## Description of Issue
Optifine throws OpenGL Error 1282 repeatedly. The error doesn't create a noticable lag spike or visual change of the game.

## Steps to Reproduce
1. Create new 1.18 instance in launcher.
2. Run the instance and close after the game finished loading
3. Run the downloaded JAR-file to install
4. Run the just created Optifine instance.
5. Join any world

## OptiFine Version
OptiFine_1.18_HD_U_H3 standalone

## Log File
[latest.log](https://github.com/sp614x/optifine/files/7740584/latest.log)

## F3 Debug Screenshot
[F3 Screenshot](https://imgur.com/a/INkWn1O)

## Prior Testing
The error only gets thrown when using Optifine. (Vanilla and Fabric)

**Comment by Ari-RERA-43** [comment]
This is probably due to your graphics driver. You haven't noticed any issues so you can disable the error displaying in other video settings.

**Comment by QuatschVirus** [comment]
I just updated the GeForce Experience Driver, just for side information.
