### ISSUE TITLE
[Settings] Add ability to toggle cinematic camera when zoomed

### ISSUE THREAD

**Issue by FireSquid6** [sp614x/optifine#6496]
## Description of the new feature
Right now there's no option to turn of cinematic camera while using zoom, which makes it a pain for zooming to aid bow aiming. Is it possible to add a feature to be able to just toggle it? I understand that it's there to make the zooming more smooth, but there's no harm in adding an option.

**Comment by ewanhowell5195** [comment]
the cinematic keybind already toggles it

**Comment by ZenithRogue** [comment]
This is already a feature. I typically have my cinematic camera bound to F6. Check your options

**Comment by fayer3** [comment]
I think they wanted an option, so it doesn't automatically switch to cinematic camera when zooming.

**Comment by FireSquid6** [comment]
> 

what this guy said. I know you can bind cinematic camera to it but turning it on and off whenever you go into zoom is a pain.

**Comment by Regnander** [comment]
> > 
> 
> what this guy said. I know you can bind cinematic camera to it but turning it on and off whenever you go into zoom is a pain.

![](https://user-images.githubusercontent.com/51716387/59556804-1f69d380-8fc1-11e9-9a7a-73556528de04.jpg)
Grabbed from https://github.com/sp614x/optifine/issues/2495#issuecomment-502402544
