### ISSUE TITLE
OptiFine_1.11.2_HD_U_B8 crashing

### ISSUE THREAD

**Issue by Kzitold** [sp614x/optifine#650]
Optifine is the only thing in mods folder, I open the launcher, launch the latest Forge, it loads, menu screen, select world/server, it crashes.

[crash-2017-05-17_19.00.57-server.txt](https://github.com/sp614x/optifine/files/1009332/crash-2017-05-17_19.00.57-server.txt)

**Comment by Fogrits** [comment]
Some people say downgrading Forge to .2228 fixes this problem.

**Comment by sp614x** [comment]
Duplicate of #634.

Latest preview B9 should fix it.
