### ISSUE TITLE
[Category] Short description

### ISSUE THREAD

**Issue by CorruptionHades** [sp614x/optifine#6505]
## Description of Issue
I was playing on hypixel and I drank an invisiblity potion, but the enemy was able to see my santa hat floating in the air

## Steps to Reproduce
1. What do you do...
2. ...to find this bug?

## OptiFine Version
1.8.9 Lunar client

## Installation Method
Lunar client

## Other Installed Mods
Um heres a list of all Lunar client mods https://gyazo.com/d852831f4fa9291ad64790951aaa4d8f

**Comment by KaiAF** [comment]
Bug was fixed back in October, Lunar client has not updated optifine versions.
