### ISSUE TITLE
this weird flashy texture glitch keeps happening pls help

### ISSUE THREAD

**Issue by AlexcropSuS** [sp614x/optifine#6515]
iv'e been trying to fix this for a month now and it just wont disappear 
whenever i use optifine it always happens but when i remove it it disappears
i tried to tampered with the settings already and nothing seems to fix it either something new will happen or it will just get worst
also for some reason this only seem to happens to version 1.16.4 and above 
![2021-12-26_21 21 31](https://user-images.githubusercontent.com/96706823/147425496-d57dc514-1447-46bd-a88c-6e807d86dc0e.png)

**Comment by Regnander** [comment]
Can you post a F3 screenshot so we can see your setttings and PC specs?

**Comment by KaiAF** [comment]
No reply from the issue author
