### ISSUE TITLE
Optifine makes my UI Glitch when I play 1.17 and 1.18

### ISSUE THREAD

**Issue by etyad** [sp614x/optifine#6516]
The issue I have started in 1.17 where my UI looked like absolute crap. Every button in the start menu was glitched and the title was stretched. When I went in my survival world, my health bar was missing but everything else was there. In 1.12, there was no problem. My pc specs are Intel core i3-4005u 1.7 ghz, Intel hd 4400, 8gb ram, 

![2021-12-28_14 04 15](https://user-images.githubusercontent.com/87635425/147534083-a2091da1-e443-45d2-b51f-47133fb79933.png)
![2021-12-28_14 04 18](https://user-images.githubusercontent.com/87635425/147534088-f7a1dbba-9c57-48ce-bd8a-5fbb5b3dd6ac.png)
![2021-12-28_14 04 25](https://user-images.githubusercontent.com/87635425/147534090-f750d7c7-3481-4a52-8ada-664c60a1602f.png)

**Comment by Regnander** [comment]
Are you using a resource pack and do you have any other mods installed?

**Comment by etyad** [comment]
> Are you using a resource pack and do you have any other mods installed?

I don't have a resource pack and the only mod I have installed other than optifine is fps reducer.

**Comment by Regnander** [comment]
> I don't have a resource pack and the only mod I have installed other than optifine is fps reducer.

Can you temporarily remove that mod and see if this problem occurs when you only have OptiFine installed?

**Comment by etyad** [comment]
> > I don't have a resource pack and the only mod I have installed other than optifine is fps reducer.
> 
> Can you temporarily remove that mod and see if this problem occurs when you only have OptiFine installed?
> 
> I want to rule out the possibility that there might be a conflict between these two mods.

I removed fps reducer and my issue with optifine still happens.

**Comment by mooishere** [comment]
I have the same issue but it messes all of my game

**Comment by KaiAF** [comment]
Related #6548
