### ISSUE TITLE
Buggy 1.8.9 Anisotropic Filtering

### ISSUE THREAD

**Issue by TheOdd1sOutYesRiceGumNo** [sp614x/optifine#6517]
Hey Optifine, I would like to report a very annoying issue with the Anisotropic Filtering in Minecraft 1.8.9. I was turning it off in Hypixel because my internet is crappy. However, when I turned it off (and this was already hard enough), it started to lag, and now I have been waiting for hours. Please make it so you it is automatically set to off.

**Comment by TheOdd1sOutYesRiceGumNo** [comment]
I meant on the last sentence, please default it to off.

**Comment by TheOdd1sOutYesRiceGumNo** [comment]
Oh wait never mind its fixed

**Comment by fayer3** [comment]
the default should be off.
