### ISSUE TITLE
Shaders Crashing

### ISSUE THREAD

**Issue by RavenholmZombie** [sp614x/optifine#652]
Crash Log: https://paste.ee/p/H3RIk

Minecraft Version: 1.7.10
Forge Version: 10.13.4.1614-1.7.10
Optifine Version: D8

The game will run fine with SEUS shaders (v11.0) active for about one minute, then the game locks up and crashes.

**Comment by sp614x** [comment]
Can the crash be reproduced with a minmal number of mods installed?
Ideally only Forge, OptiFine and one conflicting mod.

The conflicting mod can be found relatively fast with a binary search:

    Split the mods in 2 groups, test with each group
    Keep the group that crashes, repeat step 1

At the end there should be one mod left which reproduces the crash.

**Comment by KaiAF** [comment]
Author of the issue has not responded, closing
