### ISSUE TITLE
Improvement of the creation of custom capes

### ISSUE THREAD

**Issue by DelofJ** [sp614x/optifine#6529]
When you go to the OptiFine site and want to change your cape, you can choose the default cape or use the designs from the minecraft banners with third party sites to make a custom cape but it's too limited
The minecraft banners are not made for create textures, the minecraft vanilla capes use png files like for the [Migrator](http://textures.minecraft.net/texture/2340c0e03dd24a11b15a8b33c2a7e9e32abb2051b2481d0ba7defd635ca7a933) cape and you can see with the preview of the cape when making a OptiFine custom cape with the banners that the site converts it to png and that the optifine capes use the png to put the textures of the custom capes in the game
Why not let us import our custom capes in png, this gives us a lot more possibilities on the creation of the cape and elytra
Other sites like [MinecraftCapes](https://minecraftcapes.net/) use this filesystem
I know that it is possible to add to the site the option to import our cape, this option would change everything, I don't want to use any other mod than OptiFine I want to keep OptiFine
Also, I know this is what keeps a lot of people from not donate for a cape
I hope this suggestion will be listened

**Comment by KaiAF** [comment]
Custom imaged capes are not happening. Sorry
