### ISSUE TITLE
Biome specific Cocoa beans

### ISSUE THREAD

**Issue by Qmodo** [sp614x/optifine#653]
Is there an easy way to change cocoa bean textures based on biomes? or even randomise multiple textures on the bean? The plan is to have multiple types of fruit that can be grown on trees.

**Comment by sp614x** [comment]
The cocoa beans (item) can not be changed per biome.
The cocoa pods (block) can be changed per biome with connected textures: https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/ctm.properties#L123
