### ISSUE TITLE
[Shaders] Raising shadowcomp/deferred/composite number limit to 99

### ISSUE THREAD

**Issue by sonicether** [sp614x/optifine#6530]
Yes, 99 is a silly number of programs to have running! But giving the option for developers to weigh the cost of more lightweight passes vs fewer, heavier passes would be freeing!

It would also allow us to group our passes by logic and not require us to rename all programs if we add an additional pass into a logical section, such as: 

Lighting: composite0x
Godrays: composite1x
Bloom: composite2x

**Comment by sp614x** [comment]
Extended shaders composite programs to 99:
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.txt#L139
