### ISSUE TITLE
Optifine 0 fps bug

### ISSUE THREAD

**Issue by SandyVerse1** [sp614x/optifine#654]
I can't leave my pause screen, and when I can, it constantly keeps me at 0 fps. This is not a computer side thing, it's just optifine for me. I'm using the HD8 and HD5 releases. This happens on every version.

**Comment by sp614x** [comment]
Smooth FPS -> OFF ?

**Comment by BeugelBekkie** [comment]
sp614x should you turn off or turn on smooth fps with this bug?

**Comment by Builderb0y** [comment]
Off. #583

**Comment by mastersquidYT** [comment]
> Off. #583

Thank you sooo much!

**Comment by KaiAF** [comment]
Closing this as it seems to be resolved.
