### ISSUE TITLE
Absolutely not a clue

### ISSUE THREAD

**Issue by pineappleandstuffs** [sp614x/optifine#6540]
## Description of Issue
Well... im not sure the textures are just... so messed up, even after a restart of minecraft the problem exists, ONLY in this world, or any other i do this in.

https://streamable.com/qim7fc

## Steps to Reproduce
1. Enable alternate textures, disabling it does nothing to fix the issue

## OptiFine Version
Latest as of this date

## Installation Method
mods folder

## Fabric/Forge Version
latest as of this date

## Other Installed Mods
Create mod and flywheel mod, the installed mods dont affect it, i checked

## Log Files/Crash Reports
(too large for pastebin) https://mega.nz/file/QB0W0ZgI#O6_HUFun7xFKksIxERz5pq1-pX5dQLu6z_N0MseB-9E

## F3 Debug Screenshot
https://streamable.com/gxfki7

## Additional Information
Happens any way i install optifine, standalone or not, mods or not which is very odd.

**Comment by fayer3** [comment]
can you post a log with optifine standalone, since it happens there as well?

**Comment by KaiAF** [comment]
Could be related to #6549? Disable emissive textures in the settings or anisotropic filtering

**Comment by Jiingy** [comment]
No follow-up from poster in over a year, as well as a solution given in previous comment
