### ISSUE TITLE
Axolotl Model does not change. (1.18.1, jem file issue?)

### ISSUE THREAD

**Issue by Craftedkit** [sp614x/optifine#6542]
I'm attempting to change the models of Axolotls in 1.18.1, while the texture changes the model does not. I'm using optifine version 1.18.1-Optifine_HD_U_H4. I've checked that all the parts are in their correct folders, and the new part I've added is in the "snout" in the head folder. My file directory that the axolotl .JEM is in is shown in one of the screenshots. 

![image](https://user-images.githubusercontent.com/97142349/148156931-4d0dfb44-aa6e-45d5-9fea-da5bc13f90a4.png)
a cropped screenshot of my axolotl blockbench model, a new cube, labeled "snout" has an arrow pointing to it
![image](https://user-images.githubusercontent.com/97142349/148156944-30eb78f0-a4ac-41b4-b866-d96277f6cbbe.png)
a cropped screenshot showing the file directory where the file "axolotl.jem" is located
![image](https://user-images.githubusercontent.com/97142349/148157077-82398823-32ff-4520-94fb-ce7272c347fc.png)
![image](https://user-images.githubusercontent.com/97142349/148157085-144f2cc8-9eb3-40d4-b1d7-7e693abff849.png)
two screenshots showing my axolotls in game, their textures are changed, but the models aren't.

**Comment by KaiAF** [comment]
Try updating to OptiFine 1.18.1 H5 pre4, axolotl model support was added in that version.

**Comment by Craftedkit** [comment]
This solved my issue, many thanks!
