### ISSUE TITLE
OptiFine HD U H5 pre4 causes infinite loading Screen with Fabric

### ISSUE THREAD

**Issue by Chris6ix** [sp614x/optifine#6543]
## Description of Issue
I just updated my mods (Fabric) to 1.18(.1) and when I started MC, I was greeted by an infinite loading screen (The loading bar finished very quickly and then goes right back to start, and then does this all over again infinitely without the game even starting).
I stopped the Game and looked at the latest log to see what's going on and saw that the end of the file is just [this](https://pastebin.com/XdcwW7XN) Error from Optifine just repeating itself over and over again...

I tested this again only with Fabric, OptiFabric and OptiFine and I got the same result.

## Steps to Reproduce
1. Load OptiFine HD U H5 pre4 with Fabric (0.12.12-1.18.1) and OptiFabric (1.12.10) I guess? (All the latest versions as of now)

## OptiFine Version
OptiFine HD U H5 pre4

## Installation Method
Mods Folder with Fabric and OptiFabric

## Fabric/Forge Version
Fabric 0.12.12-1.18.1

## OptiFabric Version
OptiFabric 1.12.10

## Other Installed Mods
None

## Log Files/Crash Reports
[latest.log](https://github.com/sp614x/optifine/files/7824159/latest.log)

## F3 Debug Screenshot
Game does not start, so no debug Screenshot...

## Prior Testing
If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   - Only OptiFine, OptiFabric, and Fabric
 
**Yes**

- Does this happen without any mods at all?
   - Only Forge/Fabric by itself. 

**No**
 
- Does this happen in OptiFine standalone?

**I guess not**

- Does this happen in Vanilla without OptiFine?

**Nope**

- Have you tried using a binary search to find which mods cause this issue?
   - To find conflicting mods, split your mods into 2 groups (not including OptiFine/OptiFabric, obviously). Remove one group, and test in-game. Keep the group that has the problem, and repeat until no more mods can be removed without the issue disappearing.
   - Does the issue still happen with only the remaining mods installed?
      - Forge/Fabric and remaining mods, without OptiFine -->

**Not tried as the issue doesn't come from other mods?**
## Additional Information
None

**Comment by KaiAF** [comment]
OptiFine does not support fabric, please report this issue to OptiFabric

**Comment by Chris6ix** [comment]
Ah yes... then why does the issue template from OptiFine even ask for the Fabric and OptiFabric versions used, and what has been tested with them if it's "Not Supported"?

Doesn't really make much sense asking so much about what specific setup has been used /  what has been tested if you're not even supporting it...

If you guys don't support Fabric then just write into the issue Template that if Fabric/OptiFabric was used, then no support will be given instead of making us fill out this huge thing to just get it closed with a one line answer...
