### ISSUE TITLE
[Bug] Glitched Minecraft when I install OptiFine 1.17.1 and 1.18

### ISSUE THREAD

**Issue by mooishere** [sp614x/optifine#6546]
## OptiFine Version

![image](https://user-images.githubusercontent.com/97305887/148582698-f8ee67c7-2564-4d7d-b737-8e5d2192c4d2.png)
![image](https://user-images.githubusercontent.com/97305887/148582764-b54aa0fc-9eeb-43d6-9ae1-25573450bb92.png)

**Comment by Ironic11111** [comment]
I have the same bug, a complete graphical glitch that makes the game unplayable. I have a feeling it is because I am using windows 8 (as it looks like what you are using too). I really hope it gets fixed soon as its bee going on for a long time.

**Comment by KaiAF** [comment]
Closing: #6548.
