### ISSUE TITLE
[Bug] Mouse button 4 registers as mouse button 5 when shifting or holding control in Optifine 1.8.9

### ISSUE THREAD

**Issue by Monchiemon** [sp614x/optifine#6550]
## Description of Issue
 When I play OptiFine 1.8.9 and try to press side mouse button 4 while sprinting with control or crouching with shift it registers as mouse button 5. This bug is fixed in later OptiFine Minecraft versions but not 1.8.9.

## Steps to Reproduce
1. What do you do... 
2. ...to find this bug? 
Bind the front (mouse button 5) and back (mouse button 4) side mouse buttons to inventory slots, then hold control to sprint or hold shift to crouch and when you press mouse button 4 to go to that slot, it'll go to the mouse button 5 slot.

## OptiFine Version
 OptiFine HD U M5 1.8.9

## Installation Method
 I tried both and the bug remained

**Comment by KaiAF** [comment]
This is not an OptiFine bug, Mojang had fixed this in later versions.
