### ISSUE TITLE
[BUG] Shader water texture in Biomes O' Plenty

### ISSUE THREAD

**Issue by faelBrunnoS** [sp614x/optifine#6551]
## Description of Issue
I'm having a problem with the surface texture of the water when using the "Biomes O Plenty" mod.

If I use the mod and the shader at the same time, the water loses the shader surface texture and is normal and not realistic.

Without "Biomes O' Plenty" installed
![2022-01-08_21 11 25](https://user-images.githubusercontent.com/83606488/148664551-8f02887b-8e10-4773-bf32-8313ebafb65a.png)

With "Biomes O' Plenty" installed
![2022-01-08_21 08 47](https://user-images.githubusercontent.com/83606488/148664558-9142563f-0f6e-4a29-a8b8-7b1436a9ac64.png)

## Steps to Reproduce
Start the game with the shader "SEUS Renewed 1.0.1" and "Biomes O' Plenty"
Set the default shader configuration
Open any world
Go to the water and see its surface texture

## My configs

Asus TUF B360M
i7 9700KF
RTX 2060 Super 8GB
32GB RAM DDR4 2666mhz
NVMe EVO 970 Plus 1TB

Minecraft Java Edition
Version: 1.18.1
Launcher: Microsoft Launcher
Forge: 39.0.10
Optifine: HD U H4 - 1.18.1
Shader: SEUS Renewed 1.0.1

**Used mods**
TerraBlender (Required mod to use "Biomes O' Plenty"): 1.0.0.24 - 1.18.1
Biomes O Plenty: 15.0.0.91 - 1.18.1

## Log and Debug Files
https://gist.github.com/faelBrunnoS/3f253ee627ad6d1a1476f42339904eac

Debug Print
![2022-01-08_21 55 48](https://user-images.githubusercontent.com/83606488/148665038-5565b922-9804-490b-ad86-d41ac5cada97.png)

## Prior Testing
I've already done the possible tests:

I just installed Optifine: The shader texture worked
Installed Optifine and Terrablender: The shader texture worked
Installed Optifine, Terrablender and Biomes: The shader texture didn't work

## Aditional Information
I have already changed all Optifine and Shader settings, nothing has changed!
This is the only mod that happens that!
I've installed other mods that change water color (ColoredWater) and that didn't happen.

**The developer of "Biomes O' Plenty" said this:**
> This is an issue that would need to be resolved on either Optifine or the shader's side. BOP only changes the colour of water which is a normal aspect of biomes, it doesn't make any rendering changes.

**And this:**
> If I had to have a guess at what it might be - The shader may include names of some old blocks of ours that may cause Optifine to fail to parse it or silently fail. So either the shader should update, or Optifine should handle failure more gracefully. However, this is purely speculation.

**Comment by IMBArator** [comment]
@faelBrunnoS hi ... this is pretty old. Were you able to solve the problem? ... I have the same problem here.
