### ISSUE TITLE
1.16.5 pre 9

### ISSUE THREAD

**Issue by DARK1WAVE** [sp614x/optifine#6557]
There's so many versions of forge I can't run Optifine with,
from  36.1.1  to  36.2.22
it says :
(required: Optifine_1.16.5_HD_U_G8_pre9 or newer)

Please help me cuz i really want Optifine with forge

**Comment by DARK1WAVE** [comment]
![Screenshot 2022-01-11 130516](https://user-images.githubusercontent.com/84902721/148931595-07e711a0-3fec-4531-b937-afc6b0075f9d.png)

**Comment by fayer3** [comment]
Which Optifine version did you use?
Also this looks more like an optiforge issue, optifine should work standalone with forge.

**Comment by DARK1WAVE** [comment]
I am useing Optifine HD U G8 pre2
i will try close optiforge and run the game
thanks 👍

**Comment by DARK1WAVE** [comment]
i cant

**Comment by DARK1WAVE** [comment]
the last 1.16.5 when i download it it says pre2

**Comment by fayer3** [comment]
where are you downloading it from?
get it from https://optifine.net/downloads

**Comment by DARK1WAVE** [comment]
yea i get it from there 
i go down to 1.16.5 and press download

**Comment by fayer3** [comment]
there are only full releases there, maybe you renamed the download, make sure you keep the name the same.
![grafik](https://user-images.githubusercontent.com/8282299/148986282-94676220-dcc6-4487-9ba6-88b8761940ee.png)

**Comment by DARK1WAVE** [comment]
i just pressed download on the first one :/
i am playing on forge 36.2.22
as you can see it says 36.1.0 on the right

do you have discord i can screen share you
cuz my friends also have this problem

**Comment by fayer3** [comment]
do you maybe have an old optifine as well in the mods folder?

**Comment by fayer3** [comment]
That doesn't look like it's in your mods folder. The search only shows the optifine in the versions folder

**Comment by DARK1WAVE** [comment]
i just want to screen share on discord

**Comment by DARK1WAVE** [comment]
DARK1WAVE#9103 
you can call me 
no voice if you want

**Comment by fayer3** [comment]
issue was that the mod pack installed g8 pre2, and when replaced crashed because of sodium.

**Comment by DARK1WAVE** [comment]
Thanks
