### ISSUE TITLE
[CTM] Fifth texture not used in connected textures

### ISSUE THREAD

**Issue by ElSpringos** [sp614x/optifine#6561]
## Description of Issue
The number 4 texture is not used when i try to create or use a ressource pack with connected textures .

## Steps to Reproduce
Put a ressourcepack using connected textures with te compact method and place the blocks and watch where the number 4 texture should be

## OptiFine Version
All versions from the latest 1.17 released version to the last 1.18.1 pre-released version

## Installation Method
I did drop the jar file in the mod folder

## Forge Version
1.17.1-forge-37.0.45 and 1.18.1-forge-39.0.14

**Comment by JimStoneCraft** [comment]
Set Connected Textures to Fancy for the corners to display correctly (texture 4).

Options - Video Settings - Quality - Connected Textures: Fancy

**Comment by Ari-RERA-43** [comment]
If that solved your problem, close this issue.
