### ISSUE TITLE
[1.11.2] Crash after getting into a new world

### ISSUE THREAD

**Issue by Ushupiuck** [sp614x/optifine#657]
To be precise, 1-2 mins right after... Mod list included in the crashfile. Tried without optifine and still crashes.
[crash-2017-05-19_19.24.17-client.txt](https://github.com/sp614x/optifine/files/1016516/crash-2017-05-19_19.24.17-client.txt)
Happens with latest build too

**Comment by sp614x** [comment]
The Forestry ModelBlockDefault is crashing when "Trees: Smart" is enabled.
"Video Settings -> Details -> Trees -> Default" should fix it.

**Comment by sp614x** [comment]
Updated preview C1 for 1.11.2
 - fixed crash with Forestry when Smart Trees (leaves) is enabled

**Comment by Ushupiuck** [comment]
thanks! keep up the great work ='3
