### ISSUE TITLE
Entity Flickering when too many are on screen. going onto normal minecraft removes this.

### ISSUE THREAD

**Issue by FXBrennan** [sp614x/optifine#6574]

**Comment by 777-Scorpion-777** [comment]
I have the same issue, it's present on versions 1.17.x - 1.18.x, I don't know about earlier ones. Turning on/off Optifine parameters does nothing with it.

**Comment by KaiAF** [comment]
I assume you are talking about #5891. If not, please provide more details.

**Comment by fayer3** [comment]
if you thing this is different, please provide evidence and info.
- a video showing the issue
- a F3 screenshot
- info on what version that happens
- and a log might also help
