### ISSUE TITLE
[Bug] Short description

### ISSUE THREAD

**Issue by Lunacion** [sp614x/optifine#6575]
## Description of Issue
My game game keeps crashing every time I use Optifine. But doesn't crash without using Optifine. 

## Steps to Reproduce
1. installed Optifine.
2. Opened/Launched the game.

## OptiFine Version

I used both Optifine HD U H1and OptiFine HD U G9

## Installation Method
1. I got it from https://optifine.net/downloads and used the auto installer

2. I used both Optifine HD U H1and OptiFine HD U G9

## Log Files/Crash Reports
Crash Report: https://mclo.gs/y7KBq0a

Log Files: [2022-01-24-7.log.gz](https://github.com/sp614x/optifine/files/7924614/2022-01-24-7.log.gz)

[2022-01-24-4.log.gz](https://github.com/sp614x/optifine/files/7924618/2022-01-24-4.log.gz)

[2022-01-24-5.log.gz](https://github.com/sp614x/optifine/files/7924620/2022-01-24-5.log.gz)

[2022-01-24-4.log.gz](https://github.com/sp614x/optifine/files/7924622/2022-01-24-4.log.gz)

**Comment by fayer3** [comment]
can you try if it also crashes without the resourcepack you are using?

**Comment by Lunacion** [comment]
It crashes with and without resource packs and texture packs well. This is a bug.

**Comment by Jiingy** [comment]
The crash seems to be an issue with Java, not OptiFine
