### ISSUE TITLE
[Shaders] Add fogShape uniform for 1.18.2

### ISSUE THREAD

**Issue by IMS212** [sp614x/optifine#6577]
Mojang has added a fog shape uniform to dictate if the fog should be spherical or cylindrical in 22w03a. Once 1.18.2 releases, OptiFine should preferably pass this to shader packs.

**Comment by IMS212** [comment]
To keep a stable interface, I am currently defining 0 as cylindrical and 1 as spherical in Iris, even if Mojang's index changes. I recommend the same change be done for OptiFine.

**Comment by sp614x** [comment]
Coming in next preview.
