### ISSUE TITLE
Shaders: how to tell if in lava or not

### ISSUE THREAD

**Issue by Strum355** [sp614x/optifine#658]
Continuing on from what was discussed on discord.
Making a whole new uniform wouldnt be ideal, isEyeInWater=2 sounds like a much better idea, given that we (shader devs) have noticed that uniforms have a noticable hit on performance (cleaning out unused uniforms out of shaders has given many of us around 5fps back)
isEyeInWater=1 (in water)
isEyeInWater=2 (in lava)
isEyeInWater=0 (neither)

**Comment by Silvia-Thorne** [comment]
Pls do this.

**Comment by SergeantSarcasm** [comment]
pls do this x2

**Comment by robobo1221** [comment]
Pls do this x3

**Comment by sp614x** [comment]
Updated preview C1
- extended isEyeInWater, added value 2 when the camera is in lava
