### ISSUE TITLE
[Crash] Incompatibility with Forge armor model commit (39.0.57+)

### ISSUE THREAD

**Issue by maxanier** [sp614x/optifine#6581]
## Description of Issue
With https://github.com/MinecraftForge/MinecraftForge/commit/fd522d38b00f6b7e8021fa75634a9aec74c5c301 Forge allows using `net.minecraft.client.model.Model` as an armor model instead of `HumanoidModel`.
When a mod makes use of this the game crashes with a class cast exception when Optifine is installed.
I assume some Optifine patches/code still expect the model to be a `HumanoidModel`

## Steps to Reproduce
Probably enough to compile against Forge 39.0.57+
Otherwise:
1. Install Forge 39.0.59+ and Optifine and [Vampirism-1.18.1-1.8.0-beta.2](https://www.curseforge.com/minecraft/mc-mods/vampirism-become-a-vampire/files/3620459)
2. Equip a vampire cloak and switch to third person view

## OptiFine Version
OptiFine_1.18.1_HD_U_H4

## Installation Method
MultiMC

## Fabric/Forge Version
Forge 39.0.59

## Log Files/Crash Reports
https://paste.ee/p/gNXCw

**Comment by sp614x** [comment]
Fixed, coming in next preview.
