### ISSUE TITLE
[Loading process in Forge] Support for custom mod locators

### ISSUE THREAD

**Issue by Chaos02** [sp614x/optifine#6583]
## Support (and documentation) for custom mod locators in Forge (see debug.log ~line 70)
I have recently developed a custom mod locator for Minecraft Forge v39+ (MC 1.18+) which enables loading of custom subdirectories of the `\mods` folder called **_SML_** ([Source](https://github.com/Chaos02/SubFolderLoader)).
I have had the idea to add back Forge's old version folder loading to support having multiple modded Minecraft versions inside the regular .minecraft folder but to make that possible to work with Forge I need to know what class/method to call to start Optifine's Forge loading process!

### Research:
I have already done some research through the debug.log where I found it that Optifine uses a transformation service!
Now the question arises:
Is it possible for Optifine to load AFTER the modlauncher has initiated the mod scan through FMLServiceProvider?
If so: is it *already* possible?
I would like my mod to be cross-version compatible so it is the only mod in the mods directory from newer versions than 1.12 on (after Forge removed subfolder loading), in earlier versions it would probably need to be inside the version folders themselves aswell.

Looking forward to work together and
Kind regards: Markus

**Comment by sp614x** [comment]
Generally OptiFine has to be loaded as early as possible as the OptiFine patches can only work on top of the Vanilla/Forge classes.
OptiFine can't be loaded later when other mods have been loaded.

**Comment by Chaos02** [comment]
Thank you, I would have thought that.
tho custom mod locators get called before the default /mods folder is traversed, so it would be before any other mods are loaded by forge (SML provides the mod locator as a service to forge and is (currently) not loaded as a forge mod.

**Comment by Chaos02** [comment]
if you could give me any methods to call or give me insight on how optifine *IS* loaded, I might be able to figure something out myself

**Comment by Wedge1453** [comment]
> Generally OptiFine has to be loaded as early as possible as the OptiFine patches can only work on top of the Vanilla/Forge classes. OptiFine can't be loaded later when other mods have been loaded.

is that the reason modded connected textures only work after resources are reloaded after the game is fully loaded?

**Comment by Chaos02** [comment]
![https://i.imgur.com/0YNHLuC.png](https://i.imgur.com/0YNHLuC.png)
Would've only needed to point me at this..
