### ISSUE TITLE
Cape not found

### ISSUE THREAD

**Issue by idkappaa** [sp614x/optifine#6586]
From one moment to another the cape stopped working. I looked at the optifine.net cape page and it showed the typical image error where the design of my cape should be. When trying to change it it said "Cape not found for: IDontThinkIWill" I tried to deactivate it but it said the same, I tried to move it to another user but it said "Server Error". Help me please! Thank you
![1](https://user-images.githubusercontent.com/98607266/151587216-507219fd-c0ed-482d-92dc-368c35caf2f4.PNG)
![2](https://user-images.githubusercontent.com/98607266/151587227-b6fff3ae-226a-4687-b7e5-b016919ef0ad.PNG)
![3](https://user-images.githubusercontent.com/98607266/151587229-b312747a-d72b-417d-9bee-cae648410ccc.PNG)
.

**Comment by KaiAF** [comment]
You have a broken cape, I will message the developer to fix it.

**Comment by idkappaa** [comment]
ty (:

**Comment by KaiAF** [comment]
Cape is fixed, sorry for the wait.
