### ISSUE TITLE
[Downloading Error] Whenever I try to download OptiFine it downloads a minecraft launcher

### ISSUE THREAD

**Issue by BouncyBonBon** [sp614x/optifine#6588]
Ive been scouring the internet for 3 hours trying to find out why whenever I download it, it gives me a minecraft launcher under the same name instead of a .jar file, I have java installed so i have no clue why.
![image](https://user-images.githubusercontent.com/98642405/151657063-16f1c6e8-3fa6-4dcd-9c46-8353a10a398c.png)

There aren't really any steps, i just download OptiFine and it gives me an mc launcher instead of a .jar file.

The OptiFine version is 1.18 HD U H4.

I downloaded it from the page?

No log files, because it gives me a launcher instead of the .jar file ._.

I can't open F3 on OptiFine BECAUSE IT ISNT INSTALLED!

This doesn't happen with any other .jar files ive downloaded.

I have no other mods installed either.

**Comment by fayer3** [comment]
Try running jarfix from here: https://johann.loefflmann.net/en/software/jarfix/index.html#Download

**Comment by BouncyBonBon** [comment]
> Try running jarfix from here: https://johann.loefflmann.net/en/software/jarfix/index.html#Download

That's all in a different language i dont know what to do

**Comment by fayer3** [comment]
click the blue `jarfix.exe` text, and download the software, then run it.
should then show a message, that java got successfully registered.
then try running the optifine installer again.
