### ISSUE TITLE
Cannot Transfer Cape

### ISSUE THREAD

**Issue by noxaly** [sp614x/optifine#6593]
## Description of Issue
When I go to the Optifine website and log in with my donation email, I attempt to transfer the cape to my account "n0xaly" which in return is met with a blank white page with the words "Server error." written at the top left of the page.

## Steps to Reproduce
1. Log in to the donation email
2. Uncheck the "Locked" option, enter a new username to transfer, and hit "Continue"

## OptiFine Version
1.8.9, but the issue was on the website.

## Installation Method
Lunar Client built-in, but this should not relate to the problem.

## Other Installed Mods
Lunar Client

## Log Files/Crash Reports
NA
![image](https://user-images.githubusercontent.com/98672459/151681688-dd63796d-3a9e-4fbc-ae9d-794031396898.png)

**Comment by KaiAF** [comment]
You have a broken cape. I'll message the developer to fix it, once I get a response I'll reply here.

**Comment by noxaly** [comment]
Hey Kai, any updates?

**Comment by KaiAF** [comment]
Cape is fixed, sorry for the wait.
