### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by Kasia1403** [sp614x/optifine#6594]
[crash-2022-01-31_09.32.41-client.txt](https://github.com/sp614x/optifine/files/7969794/crash-2022-01-31_09.32.41-client.txt)
[crash-2022-01-31_09.32.40-client.txt](https://github.com/sp614x/optifine/files/7969797/crash-2022-01-31_09.32.40-client.txt)

**Comment by Kasia1403** [comment]
Hello Optifine Developers, could You help me and fix my crashes ?

**Comment by Kasia1403** [comment]
HELP ME PLEASE !!!

**Comment by Ari-RERA-43** [comment]
Does this happen with only OptiFine in the mods folder?

**Comment by Kasia1403** [comment]
I think that is a conflict with a mod ( or mods ), but I don't know which. My computer is so slow that I don't want to test it alone.

**Comment by Kasia1403** [comment]
After removing Optifine Minecraft randomly crashes with Camping Mod 2.

**Comment by Ari-RERA-43** [comment]
Head to #support in the discord server. We can help you further there.

**Comment by KaiAF** [comment]
this is for bug reporting. Not support. Once you find the full issue you can report if you would like, and use the template.
