### ISSUE TITLE
[Forge] 39.0.40+ make errors

### ISSUE THREAD

**Issue by MrScautHD** [sp614x/optifine#6595]
## Description of Issue
Hi
i found a bug
mods that mixin the armor renderer
does not compatible if the mod is on forge 39.0.40+
because forge changed something on it
so the mixin mix a thing by optifine that is not existing
pls update the forge version of optifine

## OptiFine Version
OptiFine HD U H5 pre4

## Fabric/Forge Version
Forge 39.0.40+

## Other Installed Mods
Beyond Earth (they mixin the armor renderer)

## Log Files/Crash Reports
[latest.log](https://github.com/sp614x/optifine/files/7970805/latest.log)

**Comment by Ari-RERA-43** [comment]
Is this an issue without Beyond Earth installed?

**Comment by MrScautHD** [comment]
no but we want it that forge update to a newer forge version pls

**Comment by MrScautHD** [comment]
(that fix this bug with  other mods)

**Comment by sp614x** [comment]
Fixed, coming in next preview.
