### ISSUE TITLE
[Suggestion] Atlas Upscaling

### ISSUE THREAD

**Issue by debugman18** [sp614x/optifine#660]
How difficult would it be to have an in-game implementation for scaling resource pack resolution by multipliers?

**Comment by sp614x** [comment]
Upscaling without adding details only increases the GPU load and drop the FPS without visible change.

Upscaling with added details (vanilla -> Faithful 32x) has been tried many times. The automatic algorithms (https://en.wikipedia.org/wiki/Pixel_art_scaling_algorithms) do not work well and the results are strange. The seams between the textures are usually broken. Upscaling in this way always requires a manual fix to make it acceptable.

Here is one resource pack created with automatic upscaling: http://www.minecraftforum.net/forums/mapping-and-modding/resource-packs/1245311-1-6-2-128x-xbr-default
