### ISSUE TITLE
Optifine bootloading 

### ISSUE THREAD

**Issue by hg456wilkos** [sp614x/optifine#6617]
## Description of Issue
Optifine boot loops on startup, with the progress bar loading then starting again

## Steps to Reproduce
Load the game

## OptiFine Version
1.18.1_HD_U_H5_pre5

## Installation Method
Optifarbic and fabric
## Fabric/Forge Version
Fabric 0.12.12

## OptiFabric Version
1.12.10

**Comment by fayer3** [comment]
this is most likely an optifabric issue, see here: https://github.com/Chocohead/OptiFabric/issues/540

**Comment by sp614x** [comment]
Fabric is not directly supported.
