### ISSUE TITLE
[OpenGL Error] OpenGL spams my chat with OpenGL Error: 1280 (Invalid enum)

### ISSUE THREAD

**Issue by virushater111** [sp614x/optifine#6622]
## Description of Issue
i am playing in a paper server with loads of plugins on then out of no where it just starts spamming : OpenGL Error: 1280 (Invalid enum)

## Steps to Reproduce
1. go on a paper server with loads plugins

## OptiFine Version
OptiFine_H5_pre5

## Installation Method
drop the JAR file into mods folder

## Fabric/Forge Version
1.18.1-Forge_39.0.76

## Other Installed Mods
non

## Log Files/Crash Reports
[latest.log](https://github.com/sp614x/optifine/files/8066726/latest.log)

## F3 Debug Screenshot
![2022-02-15_14 30 49](https://user-images.githubusercontent.com/78138919/154013588-f5c0b598-d1eb-40e5-8168-dd044cbaac4b.png)

## Prior Testing
no

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   - Only OptiFine and Forge
   - Does this happen without any mods at all?
   - Only Forge/Fabric by itself.
- Does this happen in OptiFine standalone?
   - idk
- Does this happen in Vanilla without OptiFine?
   -no 
- Have you tried using a binary search to find which mods cause this issue?
   - there is no mods

## Additional Information
it spams at a slow speed like 10s/per

**Comment by KaiAF** [comment]
Updating your graphics drivers may help. Other than that I am not sure if there is any way to "Fix" this, other than disabling the errors.
You can disable the errors by going to settings > video settings > other > show opengl errors: off.
