### ISSUE TITLE
[Visual] Glint Bug

### ISSUE THREAD

**Issue by michcia321** [sp614x/optifine#6624]
## Description of Issue
My glint is out of item

## Steps to Reproduce
I enchant item

## OptiFine Version
1.8.9

## Installation Method
From Feather Client

## Fabric/Forge Version
Feather Forge

## Other Installed Mods
Tnt timer, Resource Pack Organizer, replay mod and Patche

## Log Files/Crash Reports
[

](https://pastebin.com/NPC61vq2)

## F3 Debug Screenshot
[

](https://imgur.com/a/KK1DfMz)

## Prior Testing
<!-- If you've installed standalone:
- Does this happen in Vanilla without OptiFine?

I use Feather Client

**Comment by KaiAF** [comment]
What? Are you talking about this?
![image](https://user-images.githubusercontent.com/60985521/154812164-64358cc2-cc6e-42b9-b5fd-af05c7fcf9a6.png)

**Comment by michcia321** [comment]
yes

**Comment by KaiAF** [comment]
That is not an OptiFine bug. That is either a resource pack or another mod with feather client called
