### ISSUE TITLE
[1.19] New shader feature requests

### ISSUE THREAD

**Issue by IMS212** [sp614x/optifine#6627]
Best solution would likely be:
"darknessFactor" uniform: float with the current "factor" of darkness, used in game for the fog scaling.
“darknessLightFactor”: the factor subtracted from the light value in lighttexture per frame
Warden emissives: just eyes with a 0.1 alpha
Will be updates as dev continues

**Comment by IMS212** [comment]
Reliable way to add darknessLightFactor:
Inject right before getSkyDarken in LightTexture's updateLightTexture and reset the value
Inject at the end of calculateDarknessScale, multiply the return value by the darkness scale option (mc.options.darknessEffectScale), and use that as the value for shaders

**Comment by sp614x** [comment]
Added shader uniforms `darknessFactor` and `darknessLightFactor`:
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.txt#L248
