### ISSUE TITLE
[Bug report] CPU Temp/Utilization

### ISSUE THREAD

**Issue by Dat1ScrubLord** [sp614x/optifine#6629]
## Description of Issue
When launching Minecraft using optifine 1.18.1 HD U H4, CPU usage jumps from idle to 100%, causing issues with lower end coolers where the CPU will reach over 100c

## Steps to Reproduce
1. Open the Minecraft launcher, click play when using optifine version stated above and below
2. Watch CPU utilization and temps soar on the mojang splash-text (pre-main menu)

## OptiFine Version
 optifine 1.18.1 HD U H4

## Installation Method
Standalone

## Log Files/Crash Reports
I'm unsure if this log file is relevant, but it was last edited today.
[2022-02-16-1.log.gz](https://github.com/sp614x/optifine/files/8102833/2022-02-16-1.log.gz)

## F3 Debug Screenshot
[2022-02-19_14 03 12](https://user-images.githubusercontent.com/16126607/154815195-b86bf6de-531b-4740-8b91-b4a9c284751a.png)

## Prior Testing
- Does this happen in Vanilla without OptiFine?
No

## Additional Information
This may not be an issue for most people, it could be entirely my setup however I do have a noctua cooler and my temps still soar to a whopping 78+ degrees on my 5800x which, if I'm not mistaken, really shouldn't be happening. My temps don't even reach that when playing PUBG or Battlefield 2042.

**Comment by Peca21** [comment]
If your CPU is reaching 100C, them something is wrong with the cooler, no cpu should reach 100C under any load

**Comment by fayer3** [comment]
are you sure this doesn't happen with vanilla for you? from me both optifine and vanilla have the same 100% cpu usage during startup.

**Comment by Dat1ScrubLord** [comment]
> are you sure this doesn't happen with vanilla for you? from me both optifine and vanilla have the same 100% cpu usage during startup.

I was not reaching 100⁰c in vanilla on my old cooler, but it could be an issue of faster loading in vanilla

**Comment by sp614x** [comment]
OptiFine doesn't change the CPU load in the game menus.
However OptiFine recognizes much more resource pack features and it may take longer to load the resource pack, which may cause the CPU temperature to go higher than vanilla when loading a resource pack.
