### ISSUE TITLE
[Bug Report] Dynamic light sources shown through blocks

### ISSUE THREAD

**Issue by Dat1ScrubLord** [sp614x/optifine#6632]
## Description of Issue
Some dynamic light sources are showing light through blocks. The most noticeable, in my recent experience, is glow squids through stone.

## Steps to Reproduce
1. Have glowsquid on one side of a thin, opaque wall
2. Check the other side of the wall

## OptiFine Version
1.18.1 OptiFine HD U H4

## Installation Method
Standalone

## Log Files/Crash Reports
[2022-02-20-1.log.gz](https://github.com/sp614x/optifine/files/8104774/2022-02-20-1.log.gz)

## F3 Debug Screenshot
![2022-02-20_14 18 18](https://user-images.githubusercontent.com/16126607/154860439-3ada9259-b1d7-4d53-a666-6620ec69fd01.png)

## Prior Testing
- Does this happen in Vanilla without OptiFine?
No

## Additional Information
This is, obviously, a minor issue and should be treated as such. It's just something I noticed while strip mining in my hardcore world.

**Comment by sp614x** [comment]
This is how the dynamic lights work, it can't be fixed.
