### ISSUE TITLE
[1.18.x] [CEM] Witch's Broken CEM

### ISSUE THREAD

**Issue by JATT98** [sp614x/optifine#6639]
## Description of Issue
the CEM for Witch no longer works

![cem](https://user-images.githubusercontent.com/31095919/155817756-398939e4-4be6-4c1b-8a06-1d7823aa22bc.PNG)
The CEM created

![cem2](https://user-images.githubusercontent.com/31095919/155817754-1a3a55c5-e731-460b-971c-01829f8ac05e.PNG)
In Game

In 1.16.5 OptiFine HD U G8 works
![1165](https://user-images.githubusercontent.com/31095919/155818133-7ebb5d6e-a22f-4ff7-aa08-9524348cb803.PNG)

## OptiFine Version
- 1.18.1 OptiFine HD U H4
- 1.18.1 OptiFine HD U H5 pre6
- 1.18.1 OptiFine HD U H5 pre5
- 1.18 OptiFine HD U  H3

## Installation Method
Standalone installer

**Comment by ewanhowell5195** [comment]
nothing is broken here.

that cube is part of the vanilla model. it is showing because you have its uv space textured, and you most lilely deleted the empty `headwear2` folder
