### ISSUE TITLE
[Crash] Minecraft Crashes with many Entities

### ISSUE THREAD

**Issue by L3-N0X** [sp614x/optifine#6643]
## Description of Issue
I have a stacking Raid farm and whenever I use it, Minecraft crashes in several seconds.

## Steps to Reproduce
Use a stacking Raid farm

## OptiFine Version
1.18.1 HD_U_4

## Installation Method
Standalone Installer

## Other Installed Mods
I have the same Bug with Badlion and Optifine enabled, but I don´t know if this Bug also appears in Vanilla Minecraft.

## Log Files/Crash Reports

https://pastebin.com/7Kf0e3pS   Crash Report

https://pastebin.com/21FhGfS8 Logs

**Comment by Ari-RERA-43** [comment]
It would be helpful if you tested this in vanilla first so we know if it's actually an OptiFine issue.

**Comment by L3-N0X** [comment]
So, I'm running the farm since  15min without a crash in Vanilla Minecraft, but yesterday in Optifine it also worked like 20min without a crash and then I stopped the farm. 

In my ressourcepack I have custom entity models for pillagers and what may also be good to know is, that my PC is very bad, I have never more than 40FPS and with the farm running I get like 12FPS.

**Comment by ZenithRogue** [comment]
This is an issue with your PCs capabilities, it is not dependent on OptiFine
