### ISSUE TITLE
Game crashes when loading into a world/server [FIXED]

### ISSUE THREAD

**Issue by BingXhz** [sp614x/optifine#6644]
I have a issue while joining a world/server. YES it's only after I install optifine to my 1.16.5 forge modpack.

**Optifine Ver:** 1.16.5_HD_U_G7
**Modpack Forge:** forge-36.2.20

G8 ver crashes my game so that I cannot even enter main menu so I have to only use G7.
I'll leave my crashlog down below too! Please help!

**Error When Game Crashes:**
The game crashed whilst unexpected error
Error: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
Exit Code: -1

**Crashlog:** https://www.pastebin.com/3Tu2Q26r

**Comment by BingXhz** [comment]
> What are the other mods? Does it happen without them? You may want to remake this issue using the template.

Wym other mods? You can look at the changelog pastebin link.

**Comment by BingXhz** [comment]
**Fixed it. Better Foilage mod was the issue!!!!!**

**Comment by Ari-RERA-43** [comment]
Close the issue
