### ISSUE TITLE
[Texture] Water texture of waterlogged blocks appears gray

### ISSUE THREAD

**Issue by dmfrnkln** [sp614x/optifine#6646]
Description of Issue
Surface waterlogged blocks have their water texture appearing the wrong color, this also seems to affect shaders.

Steps to Reproduce
1. Place down a slab or other block that can be waterlogged on a surface water block
2. Notice how the water texture turns to a gray color

OptiFine Version
1.18.2_HD_U_H6_pre1

Installation Method
Standalone installer

Screenshots

![2022-03-03_16 35 12](https://user-images.githubusercontent.com/47154011/156656599-e301a332-72b1-4be4-a3a6-28879e11e61d.png)

![2022-03-03_16 35 30](https://user-images.githubusercontent.com/47154011/156656632-7eef4acc-b09a-44c7-b153-02e3c0b31e3b.png)

![2022-03-03_16 40 53](https://user-images.githubusercontent.com/47154011/156657417-c65d93b9-6b8f-42d1-905d-717c67c6d9a3.png)

Shaders are BSL_v7.1.04

Prior Testing
This does not happen in vanilla or previous OptiFine versions

![2022-03-03_16 37 35](https://user-images.githubusercontent.com/47154011/156657962-3ba06944-4d25-43fb-b33c-abeb5850176b.png)

**Comment by Soham52** [comment]
same here

**Comment by mateimarica** [comment]
Can confirm it's a `OptiFine HD U H6 pre1` issue

**Comment by astiengreenhart** [comment]
Same here.

**Comment by StarTheDrawer** [comment]
Yeah, I also have this issue. Didn't think about it being an OptiFine issue so I reported it to Mojang thinking it was a Minecraft issue and not OptiFine.

**Comment by Tsoccerguy3** [comment]
![2022-03-07_11 06 54](https://user-images.githubusercontent.com/22108822/157077249-949233af-ecc4-47fa-9982-93253e1c6a18.png)
![2022-03-07_11 08 46](https://user-images.githubusercontent.com/22108822/157077256-e495504d-a4a0-4899-8eab-f0345067d2a5.png)

**Comment by Tsoccerguy3** [comment]
With and without Optifine

**Comment by juliocoliveira** [comment]
Same here
![2022-03-07_20 43 52](https://user-images.githubusercontent.com/6606725/157118332-c0e9b88c-5247-4eb7-9f7e-a1d093ba1642.png)

**Comment by CommandoEchino** [comment]
Seeing it as well, both with and without Forge:

![2022-03-07_19 09 39](https://user-images.githubusercontent.com/64720141/157139827-d0efe134-0c49-4ef5-986c-c90cb25617dc.png)

**Comment by sp614x** [comment]
Fixed, coming in next preview

**Comment by Alex-jonas012** [comment]
![image](https://user-images.githubusercontent.com/74257824/163670346-23c48611-fb5d-4b1f-901e-c101eb8da19f.png)
:?

**Comment by fayer3** [comment]
Are you in the latest optifine? H7 should definetly not have that

**Comment by Philip1435** [comment]
> Fixed, coming in next preview

Wait what do you mean 'Fixed'? Did someone already mention the solution?

**Comment by Ari-RERA-43** [comment]
> > Fixed, coming in next preview
> 
> 
> 
> Wait what do you mean 'Fixed'? Did someone already mention the solution?

The solution is updating OptiFine. It was a bug that has now been fixed.
