### ISSUE TITLE
[Category] Short description

### ISSUE THREAD

**Issue by AnkerFung** [sp614x/optifine#6650]
## Steps to Reproduce
Load a resource pack that contains emissive textures, the go into a cave. You will see that some blocks with emissive textures in a different chunk section are bugged.

## OptiFine Version
All the versions for 1.18.x, didn't check for prior versions.

## Installation Method
Standalone installer.

## Prior Testing
The emissive texture is an Optifine feature

## Texture pack used:
[b_-_16x.zip](https://github.com/sp614x/optifine/files/8190353/b_-_16x.zip)

## Screenshots
![unknown](https://user-images.githubusercontent.com/48397950/156877003-ecd9c7d5-b62c-4ada-9af9-74651a49bf2c.png)
![unknown (1)](https://user-images.githubusercontent.com/48397950/156877007-05f9a59b-1966-4e8c-9b68-360af12bd95e.png)
.

**Comment by fayer3** [comment]
probably the same as #6549 
disabling antialiasing and anisotropic filtering should fix it.

**Comment by Jiingy** [comment]
closing, see previous comment
