### ISSUE TITLE
Optifine jar file keeps appearing on my desktop

### ISSUE THREAD

**Issue by Sn-0-w** [sp614x/optifine#6652]
## Description of Issue
The file is an optifine 1.8.9 jar file with 0kb and can be deleted. Though after opening other games like valorant and genshin impact, the file reappears on my desktop. It is likely a corrupted file

## Steps to Reproduce
1. Download Bad Lion client
2. Download Optifine 1.8.9 on Bad Lion

## OptiFine Version
1.8.9

## Installation Method
Through the bad lion client

## Log Files/Crash Reports
None

**Comment by fayer3** [comment]
this sounds more like a bad lion client issue, report it to them.

**Comment by Sn-0-w** [comment]
> this sounds more like a bad lion client issue, report it to them.

OK thank you Ive alrdy reported it
