### ISSUE TITLE
[Website] Optifine website has been downed for hours.

### ISSUE THREAD

**Issue by pickaxe828** [sp614x/optifine#6654]
## Steps to Reproduce
1. Open up Google Chrome
2. Enter optifine.net in the search bar

## Additional Information
Cannot download optifine.

**Comment by vulture001** [comment]
I get the necessity of the website, but making a ticket for it being down for a period shorter than a day is overtly extreme and draws attention away from actual bugs they are trying to fix. Why can't people wait?

**Comment by KaiAF** [comment]
We are aware, thanks
