### ISSUE TITLE
Optifine website not working

### ISSUE THREAD

**Issue by Midnightiscooler** [sp614x/optifine#6655]
## Description of Issue

The optifine.net is not working it says "Service Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.
Additionally, a 503 Service Unavailable error was encountered while trying to use an ErrorDocument to handle the request."
## Steps to Reproduce
1. What do you do...
2. ...to find this bug?
Go to optifine.net

**Comment by Ari-RERA-43** [comment]
The OptiFine staff are aware of this. You should close this issue.

**Comment by Midnightiscooler** [comment]
Okay, thank you!

**Comment by arduinka55055** [comment]
Hi. Site works but i can't use cape editor. it stuck on ddos cloudflare protection
