### ISSUE TITLE
[Shaders] Invisible Entities in Fog

### ISSUE THREAD

**Issue by jayhillx** [sp614x/optifine#6660]
hi!
I’m using Rudoplays Beta, which updated a few things including lighting and fog. I had to tweak some things to get it to be visible, but then I noticed parts of mobs turn invisible in the fog.
![334744E6-C178-476C-8961-41283ABC71A8](https://user-images.githubusercontent.com/69263647/157068265-023c07f0-dc9d-407b-842b-a896e2b6e9e8.jpeg)
I’ve only checked in a few versions, and Im guessing it’s an issue related to the shader and not optifine. I was wondering what I could do to fix this in the code and what’s causing it? Any help would be extremely appreciated!! :)

**Comment by sp614x** [comment]
Rudoplays is a very old shader pack. It probably needs updating to work correctly with recent MC versions.
Maybe someone in the shaderlabs discord can help: https://discord.com/invite/RpzWN9S
