### ISSUE TITLE
[Bug Report] NullPointer when running vanilla 1.18.2 with Optifine and JEI

### ISSUE THREAD

**Issue by hfingler** [sp614x/optifine#6662]
## Description of Issue
Using Optifine breaks Just Enough Items (JEI) GUI on vanilla 1.18.2
Issue was reported to JEI too https://github.com/mezz/JustEnoughItems/issues/2744

## Steps to Reproduce
New 1.18.2 profile on CurseForge, install latest JEI. JEI works on single player.
After adding the latest Optifine, JEI breaks and doesn't work anymore, but it shows as loaded.

## OptiFine Version
OptiFine HD U H6 pre1

## Installation Method
Dropped the jar in the mods folder.

## Other Installed Mods
Just JEI

## Log Files/Crash Reports

latest.log is here:

https://pastebin.com/qUC9WZR3

Main parts are `[21:51:22] [Render thread/ERROR]: Exception caught during firing event: Cannot invoke "net.minecraft.tags.TagKey.f_203868_()" because "this.f_43959_" is null`

## Prior Testing

 Only happens after installing Optifine.

**Comment by PooPooSkin** [comment]
It also does the same on servers and with other mods. Once Optifine was removed JEI worked properly with everything else.

**Comment by sp614x** [comment]
Updated Forge compatibility to #40.0.24.
Tested with latest JEI-1.18.2-9.5.3.149. 
Can't reproduce the problem, no exceptions in log and JEI seems to work correctly.
Forge compatibility coming in next preview.
