### ISSUE TITLE
[1.18.2 Bug] Added shaders cause going into various worlds to take a longer time than usual

### ISSUE THREAD

**Issue by calvizgaming** [sp614x/optifine#6667]
## Description of Issue
I have the latest 1.18.2 pre release of Optifine, I usually use the Complimentary Shaders, after installing the pre release, I found that loading into the nether or back to the OW or the End takes a lot longer than usual, usually it's instant, I can hear that I've been teleported however it's stuck onto the loading terrain screen. I've tried various shaders like Sildur's Vibrant, BSL and it still did the same exact thing. It worked fine before on 1.18.1 release. 

## Steps to Reproduce
1. Start Optifine 1.18.2 pre 
2. load in any shaders
3. Walk through any portals and takes around 4-5 seconds to load into the terrain
4. take away any shaders
5. instant load to all terrain
6. repeat

## OptiFine Version
1.18.2

## Installation Method
Java installation file

**Comment by sp614x** [comment]
If the shaderpack has different shaders for the different dimensions then the game has to reload shaders on each dimension change, which needs some time.

**Comment by fayer3** [comment]
> If the shaderpack has different shaders for the different dimensions then the game has to reload shaders every time the dimension is changed. This needs some time and can't be fixed.

this might not be what's happening here. Since 1.18.1 H5 pre5 shaders need way longer to reload.
with H5 pre4 internal shaders take ~1 second to reload with F3+R
with H5 pre5 and higher it tkaes ~5 seconds.
