### ISSUE TITLE
[Bug] Armor Set

### ISSUE THREAD

**Issue by Tanerx** [sp614x/optifine#6668]
## Description of Issue
Hello.
I'm using multiple armors set with fancyPants core shader. All of them is 16x. 
I add all of them in optifine and it works fine. All 16x

One of the armor sets have 32x version. I'm replacing this one optifine only. (can't do it for core shader they all have to same size)
32x version armor sets looking wrong. If i enable any shader it look right. 

The problem is armor sets have to same size as core shader. If not without enabled any shader in optifine armor look wrong. 

Optifine Same size as core shader. (No shaders enabled)
https://i.imgur.com/mk3iwPr.png

Optifine Same size as core shader. (Shaders enabled)
https://i.imgur.com/T1S91fx.png

-------------------------------------------

Optifine is 32x Core shader 16x. (No shaders enabled)
https://i.imgur.com/3TgJgH0.png

Optifine is 32x Core shader 16x. (Shaders enabled)
https://i.imgur.com/rsz1Gvj.png

## OptiFine Version
OptiFine_1.18.1_HD_U_H4

## Installation Method

Jar in the mods folder
## Fabric/Forge Version

Fabric 0.13.12

## OptiFabric Version

optifabric-1.12.10

## Other Installed Mods

Mods:
  [✔️] BetterCmdBlockFabric-1.18.1-2.5.10
  [✔️] BetterF3-1.2.2-Fabric-1.18
  [✔️] BetterThirdPerson-Forge-1.18-1.6.0
  [✔️] cloth-config-6.2.57-fabric
  [✔️] cmdkeybind-1.5.3-1.18
  [✔️] collective-fabric-1.18.x-4.9
  [✔️] fabric-api-0.46.4+1.18
  [✔️] fabric-language-kotlin-1.7.1+kotlin.1.6.10
  [✔️] fullbrightnesstoggle-fabric_1.18.x-1.3
  [✔️] hotbar-switcher-1.0.6_21w42a
  [✔️] lazydfu-0.1.2
  [✔️] litematica-fabric-1.18.1-0.10.2
  [✔️] malilib-fabric-1.18.1-0.11.7
  [✔️] modmenu-3.0.1
  [✔️] optifabric-1.12.10
  [✔️] OptiFine_1.18.1_HD_U_H4
  [✔️] seethroughlava-2.2
  [✔️] smoothboot-fabric-1.18-1.7.0
  [✔️] ThirdPersonCrosshair-1.18.1-1.2.1
  [✔️] WorldEditCUI-1.18.1+01
  [✔️] wthit-fabric-4.5.3
  [✔️] Xaeros_Minimap_22.3.0_Fabric_1.18
  [✔️] XaerosWorldMap_1.20.3.1_Fabric_1.18

## F3 Debug Screenshot

https://i.imgur.com/N8vnWLj.jpeg

**Comment by sp614x** [comment]
Core shaders and OptiFine shaders don't mix well with each other.
This is a general problem that can't be fixed easily.
