### ISSUE TITLE
[1.18.2] [Shaders] waterlogged water not mapped to water ID

### ISSUE THREAD

**Issue by fayer3** [sp614x/optifine#6672]
## Description of Issue
water from waterlogged blocks is not mapped to the water block ID
probably connected to #6646 which got fixed. the color is working now, but the ID mapping not.

## Steps to Reproduce
1. load a shader that has effects for water, I used Sildurs Enhanced Default
2. find a waterlogged block
3. see that it's missing the water effects.

## OptiFine Version
1.18.2 HD U H6

## Installation Method
standalone installer

## F3 Debug Screenshot
![grafik](https://user-images.githubusercontent.com/8282299/158025768-222bb0da-9514-4fc3-8142-e04131444b62.png)

**Comment by peanutpupper** [comment]
I am also having this issue. While waterlogged blocks now have the correct color, they still do not cooperate with shaders.
![2022-03-12_14 14 39](https://user-images.githubusercontent.com/101478359/158033605-b117444e-5add-4b41-8ce5-e0f352d5748b.png)
![2022-03-12_14 14 53](https://user-images.githubusercontent.com/101478359/158033608-973e83fe-3895-44b1-859f-2d7f19dd281e.png)

**Comment by IMS212** [comment]
Just to note the ID mapping isn't -1, it's whatever the waterlogged block is. There's likely a push/pop missing.

**Comment by Jolbrunner** [comment]
i have the same bug with optifine..

**Comment by sp614x** [comment]
Ninja updated H6 with a bugfix, please redownload it.
