### ISSUE TITLE
[Bug] Render distances maxes around 10 chucks

### ISSUE THREAD

**Issue by Jadeeeeen** [sp614x/optifine#6674]
Im not sure if this is problem for others but its been happening for me

**Comment by Ari-RERA-43** [comment]
I'm not sure if you intended to close this issue, but if you haven't solved it, it's probably because you're on a server. The default server render distance is 10 chunks.

**Comment by Jadeeeeen** [comment]
> I'm not sure if you intended to close this issue, but if you haven't solved it, it's probably because you're on a server. The default server render distance is 10 chunks.

Yeah, i meant to close it because i realised it had to do with servers. I upped the render distance so its good now. Before I was confused because my friend could see more than me and he has a crap pc. all good now though, thanks
