### ISSUE TITLE
[Visual] Water logged blocks make water white at one block height

### ISSUE THREAD

**Issue by PeterC43** [sp614x/optifine#6675]
If you place down a water loggable block (ex. slabs, trapdoors, seagrass) in one block high water, the water turns white

Place down water and put a slab, trapdoor, ect. at the source

1.18.2

I installed Optifine with the standalone installer

This doesn't happen in vanilla
![2022-03-13_11 49 28](https://user-images.githubusercontent.com/101515706/158067986-43574e55-42c8-4b30-843c-a7e5e5235aed.png)

**Comment by Ari-RERA-43** [comment]
Update to full H6. This has been fixed.
