### ISSUE TITLE
Optifine does not open with java/ just crashes after try

### ISSUE THREAD

**Issue by AlphasnakeHD** [sp614x/optifine#6677]
## Description of Issue
I downloaded Optifines newest version and tried to open it but when i Open via Java it shows a black square for a nano sec and disappears afterwards

## Steps to Reproduce
download java for windows
Install newest optifine version 
try to open Optifine with java

## OptiFine Version
OptiFine_1.18..1_HD_U_H5

## Installation Method
just downloaded the file from the browser

## Other Installed Mods
no other mods

**Comment by fayer3** [comment]
Try running jarfix (https://johann.loefflmann.net/en/software/jarfix/index.html#Download) seems like a messed up java install.

**Comment by sp614x** [comment]
JarFix should fix it.
