### ISSUE TITLE
[1.18.2] Water is Grey

### ISSUE THREAD

**Issue by Dawson-Reum** [sp614x/optifine#6680]
## Steps to Reproduce
Place any blog that can be water logged in a water block touching air, and it will turn grey. 

## OptiFine Version
OptiFine HD U H6

## Installation Method
 I dropped the JAR file into my mods folder.

## F3 Debug Screenshot

![optifine bug](https://user-images.githubusercontent.com/101536665/158095962-907f00e3-064e-44a2-855e-2ca314c84652.jpg)

**Comment by KaiAF** [comment]
Update your OptiFine to the main release, this was fixed.

**Comment by Dawson-Reum** [comment]
Thank You.
