### ISSUE TITLE
[Render Quality] Nearest Filtering

### ISSUE THREAD

**Issue by locque** [sp614x/optifine#6683]
Is there any way to set the filtering type for the Render Quality when upscaling from 0.5x? I would add the option myself, but it seems like there are no sources files or compilation instructions here.

Using 0.5x can make the difference between being able to use a shader or not, but unfortunately it looks pretty bad with the blurring. Here's a comparison with a mockup of what nearest filtering would look like:

![2022-03-15_10 43 06](https://user-images.githubusercontent.com/29549891/158354720-15c7067d-fc94-4591-bee1-87d4f0dd33cb.png)

**Comment by fayer3** [comment]
If you use a shader, then edit final.fsh. This shader always runs at full resolution, and is responsible for the upscaling.

**Comment by locque** [comment]
Could you give an example how replacing a texture2D call in final.fsh with with texelFetch? I don't have any GLSL experience and don't understand how I am supposed to convert from the normalized coordinates to texel space.

**Comment by fayer3** [comment]
in theory you would do it like this:
if you for example have `texture2D(colortex0, texcoord)`, you would replace it with `texelFetch(colortex0, ivec2(texcoord * vec2(viewWidth,viewHeight)), 0)`
you need to make sure that `uniform float viewWidth;` and `uniform float viewHeight;` are there, and probably only replace the texture2D, which reads the color.

**Comment by sp614x** [comment]
Can be done with shaders in the final program.
