### ISSUE TITLE
[Occlusion] Block neighbor occlusion breaks with empty occlusion shapes

### ISSUE THREAD

**Issue by XFactHD** [sp614x/optifine#6684]
## Description of Issue
When two neighboring blocks have an empty occlusion shape, then the shape-based occlusion check in `Block.shouldRenderFace()` determines that they occlude each other. This is technically a Vanilla bug and was fixed in 1.17 or 1.18 by adding an early exit when the first shape is empty. Without OptiFine I can work around this issue with a simple Mixin (https://github.com/XFactHD/FramedBlocks/blob/1.16.x/src/main/java/xfacthd/framedblocks/client/util/mixin/MixinBlock.java#L52-L74) that backports that fix but this Mixin doesn't do anything when OptiFine is installed.

For context: In FramedBlocks I return an empty occlusion shape when the camo applied to the block can itself not occlude (things like glass, leaves, etc.) as their is no non-empty and universal occlusion shape I could return on all blocks in this case.

## Steps to Reproduce
1. Place two Framed Slabs as a double slab and place a single Framed Slab right next to it
2. Observe that the face of the double slab pointing towards the single slab is completely culled

## OptiFine Version
OptiFine HD U G8

## Installation Method
Forge mod

## Forge Version
1.16.5-36.0.31

## Other Installed Mods
FramedBlocks

## Prior Testing
This is technically also an issue in Vanilla. Without OptiFine I have the ability to work around it though by the virtue of a simple Mixin.

## Additional Information
See related issue report (which includes relevant screenshots) on the FramedBlocks repo: https://github.com/XFactHD/FramedBlocks/issues/88

**Comment by sp614x** [comment]
This is the decompiled `Block.shouldRenderFace()`: https://pastebin.com/Y3bqiL95.
How should the patch look like?

**Comment by XFactHD** [comment]
The issue is that the `VoxelShape#isEmpty()` check (lines 23-26 in your paste) is missing in 1.16.
The patch should basically backport that check from 1.18 to 1.16, which is what I did for the vanilla implementation in the Mixin I linked.
