### ISSUE TITLE
Game Crash 1.18.2 OptiFine_1.18.2_HD_U_H6

### ISSUE THREAD

**Issue by manzipan** [sp614x/optifine#6685]
## Description of Issue
Game Crash With Waystones but not in vanilla only while using optifine
latest OptiFine_1.18.2_HD_U_H6

Fabric/Forge Version
Latest  40.0.17
Prior Testing
- Does this happen in Vanilla without OptiFine?
no in vanilla without optifine the mod is perfectly usable

**Comment by Ari-RERA-43** [comment]
Can you put the log in a paste in if some kind? The log seems like it may be cut off due to a character limit.

**Comment by manzipan** [comment]
yes would you want just with only that mod installed

Ari RERA 43 ***@***.***> schrieb am Mi., 16. März 2022, 15:05:

**Comment by SiderBright** [comment]
Are you actually getting into your game? Mine won't even launch.

**Comment by manzipan** [comment]
https://pastebin.com/ZpvT4guc

**Comment by manzipan** [comment]
> Can you put the log in a paste in if some kind? The log may be cut off due to a character limit.

https://pastebin.com/ZpvT4guc

**Comment by manzipan** [comment]
has ben resolved by the mod creator with an update but i still pasted the full crashlog if it helps you in anyway
