### ISSUE TITLE
Can't change the texture of tile entities like shulkers and chests by renaming them.

### ISSUE THREAD

**Issue by ThatCrazyDude** [sp614x/optifine#6691]
## Description of Issue
I'm trying to create a resource pack where the texture of a shulker box changes to a custom texture when named, however it doesn't seem to work on shulker boxes that are placed on the ground. The textures do appear on live shulkers when named with a name tag though. I went all the way back to version 1.14.4 and found that the textures do appear on placed shulker boxes however they do not on any version later than that.

## OptiFine Version
OptiFine HD U H6

## Installation Method
Standalone Installer

**Comment by sp614x** [comment]
The server doesn't send the name of the chest/shulker box to the client until it is opened (the GUI has to show the name).
This is a server/client limitation of the game and can't be fixed by OptiFine.
