### ISSUE TITLE
Can't change optifine cape

### ISSUE THREAD

**Issue by TheZ7** [sp614x/optifine#6692]
## Description of Issue

I cannot change my cape. When i try to change it i either get a screen saying server error, cape was not found for [user], or  this page isn't working

## Steps to Reproduce
I changed my optifine cape to the one shown in the screen shot 
Try using the cape and changing you cape afterwords

## OptiFine Version
Optifine HD M6_pre2 Ultra

## Installation Method
I use lunar client

## Additional Information
![Capture](https://user-images.githubusercontent.com/86207242/159135395-160081d6-7588-4ba4-b2dc-973b89687cce.PNG)
![Capture2](https://user-images.githubusercontent.com/86207242/159135396-00e7d000-abe6-412a-bfa2-01df7e804f75.PNG)

**Comment by scentrik** [comment]
Tt is happening to me as well Idk what do to to fix it

**Comment by sp614x** [comment]
The broken capes were fixed and the website is back online.
