### ISSUE TITLE
[New feature] Boss Battle Uniform

### ISSUE THREAD

**Issue by LexBoosT** [sp614x/optifine#6697]
Hello!

Possible to add a Boss Battle Uniform with different values ​​for different bosses?

This will allow not to disable the rendering of the sky in the End (for example) when the Ender Dragon appears.

Thanks very much!

**Comment by sp614x** [comment]
Added shaders property bossBattleSky:
```
# Boss battle sky
# Render the sky when the boss battle uses near fog
# Default is false
bossBattleSky=true|false
```
and uniform bossBattle:
```
uniform int bossBattle;                         1 = custom, 2 = ender dragon, 3 = wither, 4 = raid
```

**Comment by sp614x** [comment]
Removed the property `bossBattleSky` and fixed the sky to always render in the boss battle.
This was also breaking Custom Sky and now it behaves like 1.17.
