### ISSUE TITLE
[Bug (?)] Custom End Sky Disabled When Ender Dragon is Alive

### ISSUE THREAD

**Issue by SeaOfPixels** [sp614x/optifine#6698]
## Description of Issue
Not sure if this is a remnant of vanilla behavior, but custom end skies disable when an ender dragon is present in the end.

## Steps to Reproduce
1. Either generate a new world and go to the end with a resource pack that has a custom end sky, or respawn the ender dragon using ender crystals in an existing world with a resource pack that has a custom end sky.

## OptiFine Version
Release OptiFine 1.18.1_HD_U_H5
Release OptiFine 1.18.2_HD_U_H6

## Additional Notes
If this is a remnant of vanilla's end sky behavior, I'd really like to see it overwritten by OptiFine as it's very immersion breaking and jarring (a similar issue happens when it rains in the Overworld).

**Comment by sp614x** [comment]
The game doesn't render the sky when a boss battle uses near fog.
