### ISSUE TITLE
[CEM] [Animation] is_in_item_frame and is_on_head variable

### ISSUE THREAD

**Issue by ewanhowell5195** [sp614x/optifine#6699]
At the moment, there exists `is_in_hand`, `is_in_ground` and `is_in_gui` which allow you to animate tile entities differently based on where they are.

Would it be possible to add `is_in_item_frame` and `is_on_head` as variables?

`is_in_item_frame` would return `true` when the tile entity is inside of an item frame.

`is_on_head` would return `true` when the tile entity is worn on the armor slot of a player/mob. For example when a banner is worn on the head of a pillager.

thanks

**Comment by sp614x** [comment]
Added `is_in_item_frame` and `is_on_head`.
Coming in next preview.
