### ISSUE TITLE
Is there a way to install from the command line without the GUI?

### ISSUE THREAD

**Issue by MEMESCOEP** [sp614x/optifine#6700]
Hi, I'm trying to make my own custom minecraft launcher. I need the launcher to install optifine (for performance reasons) but the launcher uses a custom directory. I don't want users to have to manually find the game directory, so is there a way to install or change the default directory through the command line?

**Comment by Ari-RERA-43** [comment]
Does your launcher use a mod loader or directly modify the Minecraft jar?

**Comment by MEMESCOEP** [comment]
It doesn't do either;

My launcher gives the user the option of using the official launcher, or using a Java JRE to run supply the proper arguments for the Minecraft jar file, and the start Minecraft.

**Comment by Ari-RERA-43** [comment]
How do you intend to add mod support? Also, keep in mind, redistributing OptiFine is illegal; you'll need to download it from the official site on the user's device.

**Comment by MEMESCOEP** [comment]
I plan to add mod loader support (Most likely fabric). This way, users can just drag and drop mods into the mods folder.

As for the redistributing aspect, I wasn't aware of this, so thanks for letting me know. Good thing the launcher just takes the user to the download page!

**Comment by Ari-RERA-43** [comment]
In the case of FabricMC, installing OptiFine can be done as easily as copying OptiFine and OptiFabric into the mods folder - no need to run the OptiFine installer. 

Some notes:
For 1.18.1 with OptiFabric: OptiFine H4 must be used.
For 1.18.2 with OptiFabric: There is currently no official OptiFabric release. A community experimental version must be used.

**Comment by MEMESCOEP** [comment]
Thanks for the reply! Unfortunately I made a mistake when I said fabric. I actually meant forge, which from my understanding is already used by Optifine. The only problem is that I'm not sure (or if it's even possible) to install forge through the command line. If this IS possible and I get it working, I think I should be able to install Optifine using the command line.

Sorry I accidentally said Fabric :)

**Comment by Ari-RERA-43** [comment]
For that, you should ask in a place more specifically focused on Minecraft Forge.

**Comment by MEMESCOEP** [comment]
Ahhh ok. I'll do that now!

Thanks for helping :)
