### ISSUE TITLE
[Shaders] Shaders need 5x the time to load, since 1.18.1 H5 pre5

### ISSUE THREAD

**Issue by fayer3** [sp614x/optifine#6701]
## Description of Issue
since 1.18.1 H5 pre5, which bumped the composite stages to 99, shaders take roughly 5x the time to load.

## Steps to Reproduce
1. load a shader
2. notice that it takes longer to load compared to previous versions.

## OptiFine Version
1.18.1 H5 pre5 and onward

## Installation Method
standalone installer

**Comment by fayer3** [comment]
both, but a zipped shader seems to be slightly faster, by 0.2 seconds or so.

**Comment by sp614x** [comment]
Optimized shaders loading time, it should be significantly faster now.
