### ISSUE TITLE
[Feature Request / Long-Standing Bug] Overworld Custom Sky disappears when raining or thundering

### ISSUE THREAD

**Issue by SeaOfPixels** [sp614x/optifine#6702]
## Description of the new feature
Vanilla Minecraft's sky gets darker when it begins to rain, however when using a custom sky with OptiFine this "darkness" effect removes the skybox rather than darkening it. I'm aware of how long it's been like this, but I genuinely believe this to be a bug and not how it should work. In the event this is more a feature request than a bug report, I've marked it as both. A fix for this would help with immersion breaking when it rains/thunders.

**Comment by SeaOfPixels** [comment]
Issue is similar to the boss fight darkness effect that also removes custom sky boxes.

**Comment by fayer3** [comment]
this sounds like a miss configured resourcepack.
if nothing is specified, the custom sky in only displayed during clear weather.
this can be changed, by specifying `weather=clear rain thunder` in the sky.properties file, see https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/sky.properties#L125

**Comment by SeaOfPixels** [comment]
Thank you for the information.
