### ISSUE TITLE
Optifine!

### ISSUE THREAD

**Issue by iRo4DRunn3R** [sp614x/optifine#671]
I used to have optifine and playing all the time using it! Once i started using Optifine i was walking like i was flying ( i dont know how else to say that) i mean i wasnt running or walking like i used to run! But once i reset my minecraft video settings and i dont get it anymore! Dinamic FOV is on but i dont get the same sprinting or walking like i used to have before i reseted the video settings! So please help me fix this and get it like it did before! I also tried removing optifine and redownload it but it still didnt work... So please HELP ME!

**Comment by sp614x** [comment]
It is not clear what you mean.
You may have changed the FOV or Dynamic FOV for example.

**Comment by GRAnimated** [comment]
In your .minecraft delete the options.txt and optionsof.txt files
