### ISSUE TITLE
[1.18.2] fog distance doesn't change during ender dragon fight

### ISSUE THREAD

**Issue by fayer3** [sp614x/optifine#6710]
## Description of Issue
the fog distance should be limited during the ender dragon fight, and the end sky not visible.

## Steps to Reproduce
1. go to the end
2. start an ender dragon fight, if there is not one already.
3. see that the fog is not near, like it should be, and the end sky is still visible

## OptiFine Version
1.18.2 H7 pre2

## Installation Method
standalone installer

## F3 Debug Screenshot
optifine:
![2022-03-24_18 06 41](https://user-images.githubusercontent.com/8282299/159973305-6c02cfb9-e962-48e4-8e27-fbb84399358b.png)

vanilla:
![2022-03-24_18 08 49](https://user-images.githubusercontent.com/8282299/159973335-0ff02ee8-2539-45c9-8f28-82db06f337b0.png)

## Prior Testing
didn't happen with 1.18.2 H6

**Comment by sp614x** [comment]
Fixed
