### ISSUE TITLE
[CEM Anim] is_on_head parameter render incorrectly

### ISSUE THREAD

**Issue by GrandMagus02** [sp614x/optifine#6713]
## Description of Issue
It is hard to explain... seams like is_on_head state is disappearing sometimes and sometimes not. Just watch:

https://user-images.githubusercontent.com/57040793/160031619-c41a26c3-b2ac-44db-856d-1b31340fdc39.mp4

![2022-03-25_02 53 44](https://user-images.githubusercontent.com/57040793/160033956-b0811cce-0594-4293-b8d3-b6ef64944977.png)

## Steps to Reproduce
Resource pack with `optifine/cem/banner.jem`:
```
{
	"textureSize": [64, 64],
	"models": [
		{
			"part": "top",
			"id": "top",
			"invertAxis": "xy",
			"translate": [0, -12, 0],
			"boxes": [
				{"coordinates": [-10, 42, -1, 20, 2, 2], "textureOffset": [0, 42]}
			],
			"animations": [
				{
					"top.ry": "(if(is_on_head, torad(90), 0))",
					"top.tz": "(if(is_on_head, 9, 0))"
				}
			]
		},
		{
			"part": "slate",
			"id": "slate",
			"invertAxis": "xy",
			"translate": [0, -44, 0],
			"boxes": [
				{"coordinates": [-10, 4, -2, 20, 40, 1], "textureOffset": [0, 0]}
			],
			"animations": [
				{
					"slate.ry": "(if(is_on_head, torad(90), 0))",
					"slate.tx": "(if(is_on_head, 1.5, 0))",
					"slate.ty": "(if(is_on_head, -30, -32))",
					"slate.tz": "(if(is_on_head, 9.1, 0))"
				}
			]
		},
		{
			"part": "stand",
			"id": "stand",
			"invertAxis": "xy",
			"translate": [0, -12, 0],
			"boxes": [
				{"coordinates": [-1, 0, -1, 2, 42, 2], "textureOffset": [44, 0]}
			]
		}
	]
}
```

## OptiFine Version
OptiFine 1.18.2_HD_U_H7_pre2

## Installation Method
Standalone installer

## Log Files/Crash Reports
[latest.log](https://github.com/sp614x/optifine/files/8346595/latest.log)

## F3 Debug Screenshot
![2022-03-25_02 36 11](https://user-images.githubusercontent.com/57040793/160031878-8ab2335d-a2a1-4613-aed2-4855fb098660.png)

**Comment by ewanhowell5195** [comment]
This is not an issue with the `is_on_head` parameter, but is instead an issue with the banner model.

This issue occurs when you directly animate the main parts of the banner model. The work around for this issue is simple. You just need to make subbones and animate those.

```
{
	"textureSize": [64, 64],
	"models": [
		{
			"part": "top",
			"id": "top",
			"invertAxis": "xy",
			"translate": [0, -12, 0],
			"submodels": [
				{
					"id": "top2",
					"invertAxis": "xy",
					"translate": [0, 12, 0],
					"boxes": [
						{"coordinates": [-10, 30, -1, 20, 2, 2], "textureOffset": [0, 42]}
					]
				}
			],
			"animations": [
				{
					"top2.ry": "(if(is_on_head, torad(90), 0))",
					"top2.tz": "(if(is_on_head, 9, 0))"
				}
			]
		},
		{
			"part": "slate",
			"id": "slate",
			"invertAxis": "xy",
			"translate": [0, -44, 0],
			"submodels": [
				{
					"id": "slate2",
					"invertAxis": "xy",
					"translate": [0, 44, 0],
					"boxes": [
						{"coordinates": [-10, -40, -2, 20, 40, 1], "textureOffset": [0, 0]}
					]
				}
			],
			"animations": [
				{
					"slate2.ry": "(if(is_on_head, torad(90), 0))",
					"slate2.tx": "(if(is_on_head, 1.5, 0))",
					"slate2.ty": "(if(is_on_head, -30, -32))",
					"slate2.tz": "(if(is_on_head, 9.1, 0))"
				}
			]
		},
		{
			"part": "stand",
			"id": "stand",
			"invertAxis": "xy",
			"translate": [0, -12, 0],
			"boxes": [
				{"coordinates": [-1, 0, -1, 2, 42, 2], "textureOffset": [44, 0]}
			]
		}
	]
}
```

**Comment by sp614x** [comment]
Mini RP for testing?

**Comment by GrandMagus02** [comment]
> Mini RP for testing?
[bugged_banner.zip](https://github.com/sp614x/optifine/files/8374447/bugged_banner.zip)
This is what I used in video

**Comment by GrandMagus02** [comment]
@ewanhowell5195 solved my problem, so should I close this issue or it still need to be fixed ?

**Comment by ewanhowell5195** [comment]
This is still an issue. sp614x is currently looking into it

**Comment by sp614x** [comment]
Fixed, coming in next preview.
