### ISSUE TITLE
[Shaders] [1.18.2] fog not working

### ISSUE THREAD

**Issue by fayer3** [sp614x/optifine#6714]
## Description of Issue
fog stopped working with the H7 previews. can't test pre1, since I didn't download it.
but I assume it has to do with the  `added shader uniforms fogStart, fogEnd and fogShape (#6577)` change

## Steps to Reproduce
1. load sildurs enhanced default shader
2. see that the sky is messed up, and fog is missing

## OptiFine Version
1.18.2_HD_U_H7_pre2

## Installation Method
standalone installer

## F3 Debug Screenshot
1.18.2_HD_U_H7_pre2, not working:
![2022-03-25_02 20 11](https://user-images.githubusercontent.com/8282299/160036725-36f79a5f-78b8-4013-81da-7c7aec2a9724.png)
1.18.2_HD_U_H6, working:
![2022-03-25_02 21 17](https://user-images.githubusercontent.com/8282299/160036746-14b561af-7174-4948-9fe4-75a7e71acd1d.png)

**Comment by sp614x** [comment]
Fixed.
