### ISSUE TITLE
[Bug] Emissive textures break banners and shield banners

### ISSUE THREAD

**Issue by SeaOfPixels** [sp614x/optifine#6719]
## Description of Issue
Reappearence of https://github.com/sp614x/optifine/issues/4707, when holding/wearing an item that has an emissive texture, all banners and shield banners turn black.

## Steps to Reproduce (1)
1. Hold a banner or a banner shield and hold a emissive item.

## OptiFine Version
OptiFine 1.18.1_HD_U_H6
OptiFine 1.18.2_HD_U_H7_pre2

**Comment by sp614x** [comment]
Using New Default+ RP, holding a blaze rod in one hand and a banner in the other hand, then the banner shows the missing texture (black/purple).

**Comment by sp614x** [comment]
Fixed, coming in next preview.
