### ISSUE TITLE
[BUG] Bug Introduced in H6 for 1.18.1 and 1.18.2. 

### ISSUE THREAD

**Issue by mysticdrew** [sp614x/optifine#6731]
## Description of Issue
Getting a ton of 1282 OpenGL Errors on the first RenderSystem, no matter what order they are in when rendering journeymap's waypoint icon in the world. I have tried switching up the order to no avail.
Several issues here. This is how I set up the waypoint icon. 
While I do not need the rendersystem calls here, if I remove them optifine makes all minecraft text blurry and then I get 1282 errors on depthTest call later down the line. Moving the vertexbuilder logic to after the RenderSystem calls makes text blurry.

`        VertexConsumer vertexBuilder = buffers.getBuffer(WaypointRenderTypes.getIcon(waypoint.getTextureResource()));
        RenderSystem.setShaderTexture(0, waypoint.getTexture().getId());
        RenderSystem.setShader(GameRenderer::getPositionColorTexShader);
        RenderSystem.bindTexture(waypoint.getTexture().getId());
        RenderSystem.activeTexture(33984);`

This was not an issue and I cannot replicate this issue in H5.

## Steps to Reproduce
make a bunch of waypoints in journeymap, press Z a bunch to make them appear and disappear is the fastest way to make it happen.

## OptiFine Version
H6 and H7 preview builds for 1.18.1 1.18.2

## Installation Method
Put it in mods folder

## Fabric/Forge Version
Recommended forge versions for every optifine version I tested. 

## Other Installed Mods
Journemap

## Log Files/Crash Reports
I added a ton of extra logging when a GL error occurs, you can see in the log
[latest.log](https://github.com/sp614x/optifine/files/8393397/latest.log)

**Comment by gregs007** [comment]
Seeing this issue as well. As soon as I remove optifine from mod folder issue doesn't happen anymore.
https://github.com/TeamJM/journeymap/issues/412

Switched to fabric/lithium/sodium, etc for now, but would love to get back to Forge/OF as I just love it love it love it. Can't live without my journeymap beacons/waypoints tho since I'm old and get easily lost!!! 

Love the work you all do. Thank you so much!

**Comment by Endarz** [comment]
I am having the exact same issue; I had the notion that resource packs contributed to the issue, but it seems that this bug persists regardless of what I do. This bug has occurred silently most of the time, but Optifine has and will throw a "generic error" message up from time to time.

Running Optifine HD U H6 on 1.18.1 in addition to JourneyMap 5.8.1.

**Comment by wolvyreen** [comment]
Having the exact same issue.  Running JourneyMap latest and optifine 1.18.2 H7

The moment I interact with waypoints I start getting opengl error 1282 and it screws up my textures

**Comment by mysticdrew** [comment]
These issues are resolved as of Journeymap 5.9.0 for 1.18.2 and 1.19.1
