### ISSUE TITLE
[Bug/Regression] shaderpacks take 5x longer to reload (H5_pre5+)

### ISSUE THREAD

**Issue by Kneemund** [sp614x/optifine#6740]
## Description of Issue
Shaderpacks need 5s to (re)load; they (re)loaded in about 1 second before. This is most likely due to extending the amount of composite programs and seems to be the cause of #6667.

## Steps to Reproduce
change dimensions, (re)spawn or press F3 + R

## OptiFine Version
H5_pre5 and above (version in which more programs were added)

**Comment by fayer3** [comment]
I already reported that #6701, and with the latest preview of 1.18.2(H7_pre3), it's now much faster again

**Comment by Kneemund** [comment]
Oh, nvm then. I didn't find that while I was looking through the issues for some reason.
