### ISSUE TITLE
[name bades model] for tridents...

### ISSUE THREAD

**Issue by maxipetri05** [sp614x/optifine#6742]
I know you get requested for the name-based trident models a lot but I just wanted to know if it is somehow possible and if it will be comming soon, it would be pretty grattifying and a lot of people would make use of it. But if it is not possible then we have to live with it :/. Great job on everything tho.

**Comment by Ari-RERA-43** [comment]
Duplicate of #2703. Close this issue. If you would like to discuss this issue, do so there.
