### ISSUE TITLE
[Category] Short description

### ISSUE THREAD

**Issue by Jazumes22** [sp614x/optifine#6761]
## Description of Issue
Maps in item frames causes entities (like item frames, chests, armor stands, players, etc) to flicker, players flicker in and out of visibility while other entities that I have noticed flicker black.

I made a video showing off the issue here. (Warning! Please if you have Epilepsy, do not watch this video!)
                    V  V  V  V
https://youtu.be/RCnZLc1YAA0

## Steps to Reproduce
1. Place an item frame or several on any surface (ceiling, wall, floor all work) 
2. Place a map into the item frame (Placing multiple DIFFERENT maps causes the issue to become more intense)
3. Place down a tile entity (Chests, Beds, Skulls, Etc) or place a regular entity such as an Armor Stand, Item frame, Etc. You can also Press F5 to see the player flicker.

## OptiFine Version
1.18.1-OptiFine_HD_U_H6

## Installation Method
Standalone

## F3 Debug Screenshot
![2022-04-21_12 54 05](https://user-images.githubusercontent.com/36134555/164511747-1dd3aad1-f90c-4e5d-89f0-237250e66584.png)

## Prior Testing
- Does this happen in Vanilla without OptiFine?
No, This issue does not appear in Vanilla Minecraft.

**Comment by Ari-RERA-43** [comment]
Likely related to #5891. Also your YouTube link is broken.

**Comment by Jazumes22** [comment]
> Likely related to #5891. Also your YouTube link is broken.

Really? Works for me, try copy and pasting it into a new tab.

**Comment by Ari-RERA-43** [comment]
It seems to be fixed now

**Comment by KaiAF** [comment]
Has been reported here #6013, was not labeled as fixed. Someone did mention that there may be a simple fix? Switching to internal shaders seemed to help them in single player.

> Switching to Internal Shaders seems to fix the issue on singleplayer, but I am not certain if it fixes it on multiplayer. The settings of the shaders do not seem to make a difference. I also did a test with Sildur's Vibrant Shaders and I did not experience any flickering while using that.

**Comment by Ari-RERA-43** [comment]
Sorry for the confusion about the "fixed" thing. I was referring to the YouTube link.
