### ISSUE TITLE
with the better minecraft mod the mobs keep dissapering and then coming back its very annoying and needed to be fixed thank you

### ISSUE THREAD

**Issue by alfie123456789** [sp614x/optifine#6762]
## Steps to Reproduce
1. What do you do...
2. ...to find this bug?

**Comment by KaiAF** [comment]
Can you follow the format that is provided? Just saying the issue without providing any logs or screenshots or more details is not helpful

**Comment by L-time** [comment]
I like a saying from Apacha:

**_Troubleshooting any problem without the error log is like driving with your eyes closed._**

So please follow the rules and provide everything inneed?

**Comment by Jiingy** [comment]
Issue is barebones and has not been updated or clarified since posting.
