### ISSUE TITLE
[CEM Animations] rot_x, rot_y, and rot_z entity parameters

### ISSUE THREAD

**Issue by ewanhowell5195** [sp614x/optifine#6770]
we already have `pos_x`, `pos_y`, and `pos_z`, which give you the coordinates of the entity in the world, but there is currently no way to detect the rotation of the entity in the world.

`rot_x`, `rot_y` and `rot_z` would get the current rotation of the entity in the world, allowing you to detect which direction it is currently facing.

Current uses of these rotations in game that I am aware of:

- `rot_y` is used when an entity turns normally

- `rot_x` is used when villagers lie down in beds. cant think of any other examples

- `rot_z` may be used for the `Dinnerbone` and `Grumm` easter eggs

**Comment by justseska** [comment]
I very much like this idea

**Comment by sp614x** [comment]
Added, coming in pre10.
