### ISSUE TITLE
[CEM Animations] player_pos_x, player_pos_y, player_pos_z, player_rot_x, player_rot_y, and player_rot_z entity parameters

### ISSUE THREAD

**Issue by ewanhowell5195** [sp614x/optifine#6771]
`player_pos_x`, `player_pos_y`, and `player_pos_z` would give you the current coordinates of the player in the world.

`player_rot_x`, `player_rot_y`, and `player_rot_z` would give you the current rotation of the player in the world.

These could be used in combination with `pos_x`, `pos_y`, `pos_z` and `rot_x`, `rot_y`, `rot_z` (#6770) to make animations based off a player to entity relationship, such as distance from the player, or if the player is facing an entity.

**Comment by justseska** [comment]
i like this

**Comment by sp614x** [comment]
Added `player_pos_x`, `player_pos_y`, `player_pos_z`, `player_rot_x` and `player_rot_y`.
The `rot_z` is not used for entities.
Coming in pre10.
