### ISSUE TITLE
Not downloading properly

### ISSUE THREAD

**Issue by Dr0irdCat** [sp614x/optifine#6774]
I am trying to download optifine for 1.18.2 and instead of doing what it should (and what I've seen in the past) It's downloading a series of symbols that look like they are meant to be code

![heh](https://user-images.githubusercontent.com/104736398/166163149-b2316fe7-4341-47dd-bee2-34cc322190a0.png)

anyone know what this is?

**Comment by Ari-RERA-43** [comment]
This GitHub isn't for support. 
Try using [Jarfix](https://johann.loefflmann.net/downloads/jarfix.exe). If that doesn't work, join the [OptiFine Discord](https://optifine.net/discord) and request help in #support-:fire:.

**Comment by KaiAF** [comment]
what ari said
