### ISSUE TITLE
[Crash] Optifine world crashes on 100% load, M1 iMac

### ISSUE THREAD

**Issue by programVeins** [sp614x/optifine#6778]
## Description of Issue
Using the 24" iMac running on M1 Chip, on macOS 12.3.1. Minecraft launcher loads well with optifine 1.18.2 but when I try to open a world, after the world loads 100%, the game crashes and Launcher reports it as exit code 6.

## Steps to Reproduce
1. Open MC Launcher
2. Choose Optifine 1.18.2 and run the game
3. Create new world / open existing world
4. Crashes when world loads 100% 

## OptiFine Version
1.18.2 (HD U H7)

## Installation Method
Downloaded the `.jar` file from [here](https://optifine.net/downloads) and clicked on 'install'

## Other Installed Mods
No other mods, just vanilla MC with Optifine

## Log Files/Crash Reports
Crash report can be found [here](https://pastebin.com/RuSnJaaa)

## Prior Testing
- Does this happen in Vanilla without OptiFine?
   It does not. Error only occurs with OptiFine. Crash occurs on standalone OptiFine with no other mods whatsoever.

**Comment by fayer3** [comment]
You are using shaders, which crash your gpu driver.
I suspect you are using Complementary, that one is currently not compatible with the M1 macs.

**Comment by programVeins** [comment]
Damn, I forgot I had shaders on, even on reinstalling the launcher / optifine, it retained the shaders, this was the reason for the crash. On removing the shader, it works as expected 😁
