### ISSUE TITLE
3D texture / volume storing light map data for shaders to use.

### ISSUE THREAD

**Issue by jcm2606** [sp614x/optifine#678]
If we could get access to light map data in a 3-dimensional way, it would make certain things a ton easier to do, better to do, and it would allow us to do new things, such as block light scattering and screen-space block light shadows (if we knew the position of blocks, or could derive the position by querying the block light value from the volume).

**Comment by sp614x** [comment]
inputs:
```
uniform sampler3D lightTex3D;
uniform vec3 lightTexOffset;
```

**Comment by sp614x** [comment]
Light texture size could be configurable, up to render distance

**Comment by sp614x** [comment]
Moved to https://github.com/sp614x/optifine/issues/1120
