### ISSUE TITLE
[Help Wanted] Emissive Texture not working

### ISSUE THREAD

**Issue by kimdongwhi** [sp614x/optifine#6785]
## Description of Issue

Emissive texture with tripwire does not work.
## Steps to Reproduce
1. What do you do... : Always happens.
2. ...to find this bug? : Just place tripwire.

## OptiFine Version
1.18.2 HD U H7

## Installation Method
 Both installations occurs this bug.

## Fabric/Forge Version

fabric 0.13.3

## OptiFabric Version

1.13.0

**Comment by Ari-RERA-43** [comment]
Send your files

**Comment by Jiingy** [comment]
Closing this issue for lack of response from the original poster.
