### ISSUE TITLE
Coded atlasMax 

### ISSUE THREAD

**Issue by EskiMojo14** [sp614x/optifine#68]
I'm not entirely sure this belongs here, but I guess it's a good a place as any to alert you to it. 
Basically, in MC, there is a coded in maximum atlas size (16384x16384), which means that no matter how good your PC is, you can only use a certain amount of textures. An example of a crash caused by this is here: http://pastebin.com/RC8hz2cr 
Is it possible for this maximum size to be modified/disabled? Currently we (the BDcraft team) have had to disable CTM for the 512x pack, as this increased amount of textures means the necessary atlas size exceeds this limit.

**Comment by sp614x** [comment]
The limit 16384x16384 is not hard coded, it comes from the graphics driver and depends on the hardware capabilities of the GPU. Most current graphics cards have a limit of16384x16384.

**Comment by EskiMojo14** [comment]
Ah, I see. Thank you for your time.

**Comment by EskiMojo14** [comment]
Sorry to bother you again @sp614x, but I was wondering. Is it possible to have a second atlas, thus bypassing this limit? Would that work?

**Comment by sp614x** [comment]
A second atlas is not possible without a total rewrite of the rendering system.

**Comment by EskiMojo14** [comment]
I understand. Thank you again.
