### ISSUE TITLE
[Bug Report] What Turned From Trying To Troubleshoot Optifine with BLC to being unable to install on Vanilla

### ISSUE THREAD

**Issue by VoidPelt** [sp614x/optifine#6806]
## Description of Issue
With the BLC side of the issue, with Optifine enabled from the players perspective the world seems displaced, but in reality it isn't. The Vanilla side is that I was suggested to try using Optifine without BLC to further troubleshoot the issue, but it refuses to install and gives me this giant string of an error code. Will provide text dump.

## Steps to Reproduce
BLC: Used latest version of BLC on 1.18,2 with Optifine enabled.
Vanilla Install: Just used the latest JAR file to install Optifine and clicked install.

## OptiFine Version
1.18.2_HD_U_H7

## Installation Method
For BLC, just clicked the Optifine Slider, for Vanilla used the JAR installer.

## Log Files/Crash Reports
[Optifine Install Error.txt](https://github.com/sp614x/optifine/files/8793856/Optifine.Install.Error.txt)

## F3 Debug Screenshot
![2022-05-29_12 12 40](https://user-images.githubusercontent.com/54515396/170882904-730a6bda-0b8c-4932-87de-02b8066044f2.png)

## Prior Testing
Happens only with Optifine when using BLC, unable to test via Vanilla as installer refuses to work

## Additional Information
Personally I can live without shaders, I just want to submit this to get it fixed so others don't have to deal with these problems.

Also apologies if it's sloppy, It's been a while since I've used GitHub let alone making an issue.

**Comment by Ari-RERA-43** [comment]
I sent you the fix for the install error on Discord. If you don't encounter this shader issue with stand-alone OptiFine, close this issue and report it to Badlion instead.

**Comment by VoidPelt** [comment]
> 

Thanks, will do.

**Comment by VoidPelt** [comment]
Closing Issue due to it being exclusive to BLC. Bringing up issue with BLC.
