### ISSUE TITLE
[Crash] Using the ARM binary from Oracle

### ISSUE THREAD

**Issue by omerien** [sp614x/optifine#6810]
## Description of Issue
I replaced the version of java in the Minecraft Launcher by the ARM version here ([oracle.com](https://www.oracle.com/java/technologies/downloads/#java8-mac)). It works fine with vanilla 1.8.9 but OptiFine 1.8.9 (last version displayed on the website) keeps crashing with it.

## Steps to Reproduce
1. Replace the version of java in the Minecraft Launcher with the one in the link above
2. Start OptiFine

## OptiFine Version
OptiFine HD U M5, redownloaded and tested today

## Installation Method
I used the installer.

## Log Files/Crash Reports
[Here](https://github.com/omerien/omerien/blob/main/optifine.1)

## F3 Debug Screenshot
The game crashes so no screenshot

## Prior Testing
- Does this happen in Vanilla without OptiFine?
No

## Additional Information
Here's the screenshot of my Mac version : 

<img width="579" alt="screenshot of my Mac version" src="https://user-images.githubusercontent.com/53191414/171686266-6c1c776d-607b-4bf2-b3bf-2f5e353dab40.png">

**Comment by omerien** [comment]
Wait no I used the wrong version of Java don't notice this issue please

**Comment by Ari-RERA-43** [comment]
Does the Minecraft launcher's built-in Java installation have this issue?

**Comment by omerien** [comment]
No, but anyway that was not the binary I wanted to use
