### ISSUE TITLE
RGBA16F and RGB16F formats

### ISSUE THREAD

**Issue by Choca13** [sp614x/optifine#682]
As said in the title is possible to add RGBA16F and RGB16F formats? Floating point number distribution is much better for rendering hdr values, and does not requires to work in gamma space which needs some costly power operations.

**Comment by MathGeniusJodie** [comment]
hehe, I was just about to suggest this, good job @Choca13

**Comment by MathGeniusJodie** [comment]
RGB9_E5 would be nice as well

**Comment by sp614x** [comment]
Updated preview C3 for 1.12:
- added shader texture formats R16F, RG16F, RGB16F, RGBA16F and RGB9_E5

**Comment by MathGeniusJodie** [comment]
Marry me @sp614x

**Comment by sp614x** [comment]
@MathGeniusJodie later...
