### ISSUE TITLE
cannot loaded twilightforest mod on Optifine

### ISSUE THREAD

**Issue by Yue-cn** [sp614x/optifine#6834]
## Steps to Reproduce
i Install twilightforest mod and Optifine mod on Forge Loader
it's will crash before loading page

## OptiFine Version
OptiFine_1.18.2_HD_U_H7

## Installation Method
Move in Mods Folder

## Fabric/Forge Version
40.1.51

## OptiFabric Version
Null

## Other Installed Mods
twilightforest-1.18.2-4.1.1056-universal.jar

## Log Files/Crash Reports
https://pastebin.com/eGHx2AdN

## F3 Debug Screenshot
Null

## Prior Testing
<!-- If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
- NO

**Comment by shadowoxide** [comment]
I'd like to also confirm - using optifine and ATM7 1.18.2 modpack worked fine until they added Twilight Forest with version 0.4.10. Now the modpack crashes with exit code 1 before any useful logs are created. Optifine version OptiFine_1.18.2_HD_U_H7.

**Comment by CanBoy67** [comment]
I also have this problem in my custom modpack with optifine and twilight forest, it may be more benficial to report it on twilight github forest

**Comment by lele92007** [comment]
just use rubidium and oculus instead

**Comment by lele92007** [comment]
> twilight team just rage-close all issues about Optifine on their github it doesn't help at all

they do this because optifine breaks most mods anyways

**Comment by GordonHollow** [comment]
> just use rubidium and oculus instead

it has lack of some cool graphic features, so currently optifine not replaceable

**Comment by lele92007** [comment]
> it has lack of some cool graphic features, so currently optifine not replaceable

what additional features do you need ?

**Comment by GordonHollow** [comment]
> > it has lack of some cool graphic features, so currently optifine not replaceable
> 
> what additional features do you need ?

full PBR resourcepack support and 3d-custom-blockmodel resourcepack support

**Comment by GordonHollow** [comment]
> i know these mods exist for fabric, but i can't find an alternative for forge and optifine breaks the entity rendering method twillight uses

not even on fabric
full PBR support planned in Iris, but currently not implemented
maybe about 3-4 months until it updates to this feature

so i better don't use twilight now, if they acting like shitheads, instead of coop with OF and fix it

**Comment by lele92007** [comment]
> instead of coop with OF and fix it
you are saying the entire community should try to understand how a closed source mod works, juste because it totally breaks forge rendering engine ?

**Comment by Yue-cn** [comment]
now shall we ?
