### ISSUE TITLE
[Bug] The latest Nvidia driver breaks all shaderpacks

### ISSUE THREAD

**Issue by Isuewo** [sp614x/optifine#6839]
## Description of Issue
The latest Nvidia driver (516.40 / 515.48.07 on Linux) breaks all shaderpacks on OptiFine

## Steps to Reproduce
1. Install the latest Nvidia driver (516.40 / 515.48.07 on Linux)
2. Play with any shaderpack

## OptiFine Version
Every Version afaik

## Installation Method
Doesn't matter

## Log Files/Crash Reports
The log doesn't contain useful information

## Additional Information
![image](https://user-images.githubusercontent.com/53264315/173909206-42e3310e-4a8e-47b0-95ee-8af6f4170673.png)

**Comment by fayer3** [comment]
this also affects the shadowtex1, shadowtex0 is fine
tested with supertester shader
shadowtex0:
![2022-06-15_21 43 30](https://user-images.githubusercontent.com/8282299/173914544-89bf1178-a827-46e3-b44c-3ab51b0549f3.png)
shadowtex1.
![2022-06-15_21 43 35](https://user-images.githubusercontent.com/8282299/173914609-f868674e-6f8d-4227-99bf-1811b8f30930.png)

**Comment by fayer3** [comment]
can you please stop recommending sodium+iris or the forge alternatives all the time?

**Comment by lele92007** [comment]
even if they lack some advanced features, they work and are more optimized than optifine
read [this](https://web.archive.org/web/20210131212246/https://gist.github.com/jellysquid3/e46882e37907dfbb3d03d26f589b1c6a)
note : sodium and iris don't have a lot of features, you need to install other mods on top of them, like [continuity](https://www.curseforge.com/minecraft/mc-mods/continuity) for connected textures.

**Comment by fayer3** [comment]
This is unrelated to the issue though.

**Comment by lele92007** [comment]
not at all
using sodium and iris instead of optifine fixes the shaders

**Comment by fayer3** [comment]
this issue is not to ask for help, but to state an issue that needs to be fixed
it's like if someone had a broken tire on their car, and you would recommend getting another car.

**Comment by EminGT** [comment]
Can be closed now as its fixed by Nvidia in their latest drivers
