### ISSUE TITLE
Crash on heavily modded 1.16.5 Forge

### ISSUE THREAD

**Issue by biauk** [sp614x/optifine#6840]
## Description of Issue
I'm recently having regular crashes, which seem to be related to rendering and Optifine.

## Steps to Reproduce
They appear completely randomly.

## OptiFine Version
OptiFine_1.16.5_HD_U_G8

## Installation Method
In mods folder

## Fabric/Forge Version
1.16.5-forge-36.2.35

## Other Installed Mods
![lista 16 06 22](https://user-images.githubusercontent.com/58109852/174047177-fb8fce12-0cce-4964-a7b0-1efd0e87e6fc.PNG)

## Log Files/Crash Reports
https://pastebin.com/Lw735YQf
https://pastebin.com/ULWwFiZv
https://pastebin.com/Yjt5qa8B
https://pastebin.com/KcGnQKH2

## F3 Debug Screenshot
![2022-06-09_18 09 03](https://user-images.githubusercontent.com/58109852/174047395-f0484635-0f59-4975-b6d7-d99de42a421a.png)

## Prior Testing
 - propably no

**Comment by biauk** [comment]
Something went bad at last section, so I add it here

## Prior Testing
If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   - Only OptiFine and Forge - no
- Does this happen without any mods at all?
   - Only Forge/Fabric by itself. - no
- Does this happen in Vanilla without OptiFine? - no
   - Does the issue still happen with only the remaining mods installed?
      - Forge/Fabric and remaining mods, without OptiFine --> - propably not

**Comment by lele92007** [comment]
optifine breaks most forge mods
try using rubidium and oculus instead

**Comment by biauk** [comment]
Nice, didn't experienced any crash after short testing on various worlds, thank you and goodbye Optifine, forever :)
