### ISSUE TITLE
Forge 1.18.2 - Optifine + Twilight Forest 

### ISSUE THREAD

**Issue by TheExotik** [sp614x/optifine#6841]
So, i was having some problems in ATM 7 modpack so i try to use optifine, and i see if i have Twilight forest + Optifine in mods folders, cause a crash and i can't open the game. So just to make sure the problem was about Twilight + Optifine i run just these guys, and the same crash happen

I'm using forge 40.1.31 / Optifine HD_U_H7 / Twilight Forest 4.1.11.02
Minecraft version 1.18.2
I'm using MultMC, but i try in minecraft launcher but the same thing happen.

Crash log / When i run launch (From MultMC):

https://pastebin.com/DEC6C4Au

**Comment by lele92007** [comment]
optifine breaks twillight forest
try using rubidium and oculus instead

**Comment by ShamblerDK** [comment]
I tried with Rubidium and Oculus instead but it turns out those are incompatible with the Flywheel mod, which is required for the mod pack I'm playing.

**Comment by TheExotik** [comment]
oh sorry, i left this open...
btw thanks, i've seen your answer and works with rubidium and oculus... thanks ^^
