### ISSUE TITLE
[Category] i cant se my optifine cape

### ISSUE THREAD

**Issue by BigBoyJuicy** [sp614x/optifine#6843]
## Description of Issue
 i cant se my optifine cape in minecraft but others can please help my ign is BigBoyJuicy

## Steps to Reproduce
1. What do you do...
2. ...to find this bug?

## OptiFine Version
 idk i play on luner so i guees the newest

**Comment by KaiAF** [comment]
There has not been a cape on the user "BigBoyJuicy" (0fb0e11de460454791647ce63d78ed7d). You need to donate to get a cape.
