### ISSUE TITLE
Shaders issue, black lines and flashing

### ISSUE THREAD

**Issue by pebble820** [sp614x/optifine#6845]
## Description of Issue
Using any sort of shaders creates these weird black lines. Every shader I've tried does this and every version I've tried has done this as well.

## Steps to Reproduce
1. What do you do...
2. ...to find this bug?

## OptiFine Version
Optifine 1.12.2 HD U G5

## Installation Method
Dropped JAR into mods folder
## Fabric/Forge Version
Forge 14.23.5.2860

## Other Installed Mods
https://pastebin.com/dUFB1jWV

## F3 Debug Screenshot
![image](https://user-images.githubusercontent.com/99370827/174508757-f65c1d0f-747a-4349-ab21-f693f39d8ca4.png)

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? - Yes
   - Only OptiFine and Forge
   - Only OptiFine, OptiFabric, and Fabric
- Does this happen without any mods at all? - No
   - Only Forge/Fabric by itself. 
- Does this happen in OptiFine standalone? - Yes
- Does this happen in Vanilla without OptiFine? - No
- Have you tried using a binary search to find which mods cause this issue? - Yes
   - To find conflicting mods, split your mods into 2 groups (not including OptiFine/OptiFabric, obviously). Remove one group, and test in-game. Keep the group that has the problem, and repeat until no more mods can be removed without the issue disappearing.
   - Does the issue still happen with only the remaining mods installed? - Yes
      - Forge/Fabric and remaining mods, without OptiFine --> All of the mods listed

Is it possibly a drivers issue? I recently updated my drivers and this has never happened before so I'm wondering if the new driver update screwed something up? Shaders work fine when in windowed mode.

**Comment by lele92007** [comment]
try using rubidium and oculus instead
if i remmeber correctly, this is an issue with nvidia's antialiasing
try changing the setting in the drivers

**Comment by fayer3** [comment]
This is an issue with the latest Nvidia driver, downgrading to version  512.95 should fix that.
You can get it here: https://www.nvidia.com/en-gb/geforce/drivers/

**Comment by pebble820** [comment]
> This is an issue with the latest Nvidia driver, downgrading to version 512.95 should fix that. You can get it here: https://www.nvidia.com/en-gb/geforce/drivers/
