### ISSUE TITLE
[Bug] Transparent Modded Blocks Become Solid

### ISSUE THREAD

**Issue by Randy3216** [sp614x/optifine#6850]
## Description of Issue

When playing optifine with mods often transparent blocks become solid textures.

With optifine:
![image](https://user-images.githubusercontent.com/57848332/175138811-27713fa5-1f49-4e7f-8537-49b9ee031b76.png)

Without optifine:
![image](https://user-images.githubusercontent.com/57848332/175138874-739eea16-f527-4b83-bc31-6f68b9ea123f.png)

## Steps to Reproduce
1. download any mod with translucent blocks 
(for the example I am using one in the modpack that im currently playing with envirocore, envirotech, and valkyrielib)
2. place any transparent block (I am using the clear structure panel from the mod above)
3. it may or may not result as a solid block texture rather then the desired transparent effect

## OptiFine Version

OptiFine_1.16.5_HD_U_G8
OptiForge-MC1.16.5-0.5.7
## Installation Method

I installed optifine by putting both Optiforge, and optifine within the mods folder
## Fabric/Forge Version

1.16.5-forge-36.2.0
## Other Installed Mods

- envirocore-1.16.5-3.0.9.3
- envirotech-1.16.5-3.0.9.4
- valkyrielib-1.16.5-3.0.9.5

## F3 Debug Screenshot

Without Optifine:
![image](https://user-images.githubusercontent.com/57848332/175142896-16cffe48-50b3-47d8-95f4-1e3b1f79b653.png)

With Optifine:
![image](https://user-images.githubusercontent.com/57848332/175143940-32570bee-d1b4-44a1-ba81-f83ffb8ebc66.png)
## Prior Testing

Testing has been done, modded blocks work as shown in images without optifine.

It has been found that this can happen with other mods, as I remember having this issue previously and initially ignoring it, however I don't remember what mods specifically.
## Additional Information

Any help, even if only a client side fix would be appreciated.

**Comment by lele92007** [comment]
optifine break forge's rendering engine
you can fix this by : 
- playing without optifine
- using rubidium and oculus instead
