### ISSUE TITLE
[Project Licensing] Why did you choose to go the route of closed source?

### ISSUE THREAD

**Issue by Brickmaster1** [sp614x/optifine#6852]
I would like to know why optifine was started and continues as a closed source and locked down licensing.  
  
When many modders have tried to fix issues they are having caused by optifine they have to figure it out with the painstaking process of trial and error, to the point that many have given up and either said to just use the ever growing optifine forge and fabric replacement suite, or just not use optifine at all. Why is it that you remain closed source, to the point where new mods such as sodium and iris for fabric and rubidium and oculus for forge are starting to make you obselete. I realize that optifine still offers many completed features, however soon the modders will figure out how to replicate the whole optifine suite. Here's a quick list:
Dynamic Lights, Check
Zoom, Check
Performance, Check
Shaders, WIP, but still, Check (Works but a little buggy and not all shaderpacks supported)
Connected Textures/ CTM, Check
Animated Block Textures, Check
CEM/Other Animation Related Features: Still quite WIP but has very good potential. 
EDIT: 
CIT is also complete.

**Comment by clevertoucan** [comment]
Yeah, it is rather disappointing - the community is full of people who'd love to make optifine better if given the chance

**Comment by aroxred** [comment]
Honestly, they're killing themselves. They had such great potential but now they're completely overshadowed. Sad.

**Comment by Brickmaster1** [comment]
Completely agree.

**Comment by FallCheetah7373** [comment]
https://discord.com/channels/423430686880301056/531622141393764352/706276224523042857

**Comment by GordonHollow** [comment]
There is one feature missing in cheklist

Full PBR\POM support still don't have alternative, only Optifine
