### ISSUE TITLE
Emissive blocks don't work  (1.19-preview)

### ISSUE THREAD

**Issue by BudgieGit671** [sp614x/optifine#6854]
The emissiveblocks only work when an item with emissive textures is being held in hand.
Issue present in the latest optifine preview (Preview OptiFine 1.19_HD_U_H8_pre1).
![2022-06-29_14 27 22](https://user-images.githubusercontent.com/67115598/176427868-e53d7897-5b89-45a5-bb06-4c33966ac2fe.png)

**Comment by SeaOfPixels** [comment]
Seconding this, emissive textures do not work for blocks. They work for everything else seemingly, only placed blocks don't render emissives.

**Comment by SeaOfPixels** [comment]
I recommend clarifying this repository to say emissive *blocks* don't work properly, not emissives in general.

**Comment by BudgieGit671** [comment]
> I recommend clarifying this repository to say emissive _blocks_ don't work properly, not emissives in general.

Alright, my bad

**Comment by ReiaTheGeia** [comment]
This persists in pre2

**Comment by DTT213** [comment]
![2022-07-05_12 21 49](https://user-images.githubusercontent.com/96983902/177255357-c0005958-24e3-4424-8d99-ca0c6708421c.png)

This bug is still happen in pre4

**Comment by BudgieGit671** [comment]
still not fixed in pre5

**Comment by sp614x** [comment]
Fixed, coming in pre6.
