### ISSUE TITLE
[Bug] Chrash with optifine when loading with forge

### ISSUE THREAD

**Issue by Gixelman** [sp614x/optifine#6855]
## Description of Issue
When you start the Game with optfine installed in the Forge mods folder it chrashes when you start Minecraft

## Steps to Reproduce
1. Install Optifine 
2. install forge 
3. Put Optifine in Mods folder
4. Start the Game

## OptiFine Version
Preview OptiFine 1.19_HD_U_H8_pre1

## Installation Method
Dropped it into the Mods folder

## Fabric/Forge Version
Forge 1.19 - 41.0.62

## Log Files/Crash Reports
https://pastebin.com/asaVeNTm

## Prior Testing
Its Standalone and Vanilla works just fine

If you've installed using Forge/Fabric:
   - Only OptiFine and Forge : *Yes*
   - Only OptiFine, OptiFabric, and Fabric : *Yes*
- Does this happen without any mods at all?
   - Only Forge/Fabric by itself. : *Yes*
- Does this happen in OptiFine standalone? : *Yes*
- Does this happen in Vanilla without OptiFine? : *No*

## Additional Information
                     /

**Comment by Ari-RERA-43** [comment]
OptiFine is not compatible with Forge on 1.19 yet and sp614x stated that. Close this issue.

**Comment by Gixelman** [comment]
> sp614x stated that OptiFine is not compatible with Forge on 1.19 yet. Close this issue.

Oh my god should've read the description 🤦‍♂️
