### ISSUE TITLE
[Bug] VSync forced when creating a new instance

### ISSUE THREAD

**Issue by UnknownTheLad** [sp614x/optifine#6857]
## Description of Issue
Framerate slider is stuck on VSync no matter what you set it to

## Steps to Reproduce
1. After installing OptiFine, go into the Minecraft launcher and make a new instance with a brand new game directory folder.
2. Launch the game and try to change the Max Framerate slider to anything that isn't VSync.

## OptiFine Version
OptiFine HD H8_pre1 Ultra

## Installation Method
Standalone installer.

## Log Files/Crash Reports
[https://gist.github.com/UnknownTheLad/f12ca327be01b47670a6fdf52232dcca](https://gist.github.com/UnknownTheLad/f12ca327be01b47670a6fdf52232dcca)

## F3 Debug Screenshot
[https://i.imgur.com/iAqzmfV.png](https://i.imgur.com/iAqzmfV.png)

## Prior Testing
If the user has changed the setting in vanilla beforehand then the user will not experience the issue.

EDIT:
After further testing this doesn't seem to be the case, or at least it's inconsistent.

**Comment by KaiAF** [comment]
Should be fixed in the latest preview
