### ISSUE TITLE
[Bug] Ticking Entity

### ISSUE THREAD

**Issue by NeverlandSMP** [sp614x/optifine#6859]
## Description of Issue
So I have been playing a server. And when I add in Opti I can a crash for ticking entity. First it was a boat so I took it out and removed the boat now its a Zombie.. 

## Steps to Reproduce
1. Add Opti to the files

## OptiFine Version
Prerelease 1.19

## Installation Method
Drop in mods folder and start game

## Fabric/Forge Version
Forge

## Other Installed Mods
https://pastebin.com/WYjTKcZH

## Log Files/Crash Reports
Boat Crash
https://pastebin.com/0NCtQ0sf
Zombie Crash
https://pastebin.com/MPcwCkPm
Zombie Log
https://pastebin.com/9aCxgrbM

## Additional Information
There where Alley in the Boat two of them

**Comment by sp614x** [comment]
Fixed in pre6.
