### ISSUE TITLE
[1.7.10] Ctm_Compact Compatiblity

### ISSUE THREAD

**Issue by IronPiston** [sp614x/optifine#687]
I'm currently trying to create connected textures using ctm_compact on the 1.7.10 D8 version. Textures successfully generated in 1.11.2, but not in 1.7.10. Because 1.7.10 just received an update, I was wondering if ctm_compact functionality could be backported to 1.7.10? 

If this isn't possible/feasable, is there anyway to export the textures that the 1.11.2 version generates when using 1.11.2(ie download the extrapolated textures from ctm_compact). Basically, creating textures using the traditional 47 tile format is quite time consuming, and this is specifically for a mod on 1.7.10.

**Comment by Fabboz** [comment]
i want ctm_compact on 1.7.10 me too.

**Comment by sp614x** [comment]
CTM compact will not be ported to 1.7.x because its code base is way too different.
