### ISSUE TITLE
How do i install optifine?

### ISSUE THREAD

**Issue by HarrisonB0i** [sp614x/optifine#6870]
I don't know what is happening but when i try to download this it does not appear, like is it supposed to be somewhere because i don't know where it is...

**Comment by UnknownTheLad** [comment]
Not an issue. Feel free to close.

If you need help with installing OptiFine then head over to the support channel in the OptiFine Discord server instead.

Cheers
UnknownTheLad

**Comment by HarrisonB0i** [comment]
ok thx
