### ISSUE TITLE
crash when loading as a forge mod

### ISSUE THREAD

**Issue by KCGD** [sp614x/optifine#6876]
## Description of Issue
When loading optifine as a forge mod, the game will hang several times during startup, then crash around when the main menu would start rendering.

## Steps to Reproduce
When installing optifine, choose the option to "extract", put the resulting .jar file in the mods folder, launch the game with forge.

## OptiFine Version
1.19_HD_U_H8_pre1

## Installation Method
Dropped the jar in the mods folder

## Fabric/Forge Version
Forge 1.19-41.0.62

## Other Installed Mods
No other mods installed

## Log Files/Crash Reports
https://pastebin.com/8FZ7vaNG

## F3 Debug Screenshot
Couldnt launch the game

## Prior Testing
This error doesnt happen in standalone or vanilla. 

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
Yes
- Does this happen without any mods at all?
No
- Does this happen in OptiFine standalone?
No
- Does this happen in Vanilla without OptiFine?
No
- Have you tried using a binary search to find which mods cause this issue?
No other mods were active

## Additional Information
<details>
<summary>Exit code, if it helps</summary>
<br>
```
The game crashed whilst unexpected error
Error: java.lang.NoSuchMethodError: 'void net.minecraft.client.Options.load(boolean)'
Exit Code: 255
```
</details>

**Comment by UnknownTheLad** [comment]
1.19-pre1 is not yet compatible with forge as stated by the release notes.

**Comment by KCGD** [comment]
ah ok. nevermind then.
