### ISSUE TITLE
When using Forge

### ISSUE THREAD

**Issue by jcain341** [sp614x/optifine#6878]
## Description of Issue

When I saved Optifine to the MOD folder in Forge, I attempted to load game with only the optifine and it crashed with a -1 exit error. 
## Steps to Reproduce
1. Install Forge
2. Create 1.19 Profile with Forge setting
3. Select the ... and open MOD folder
4. Copy and paste OPTIFINE to Inside mod folder
5. Load game
6. CRASH EXIT ERROR -1

## Fabric/Forge Version

41.0.62
## OptiFabric Version

preview_OptiFine_1.19_HD_U_H8_pre1

## Prior Testing
 Due to crash, have not tested with additional mods.

**Comment by Ari-RERA-43** [comment]
The current prerelease doesn't have Forge support.

**Comment by jcain341** [comment]
Thanks for letting me know. Respect.

Best Regards,

Jerry J. Cain
(408) 480-9177

________________________________

**Comment by MarcPG1905** [comment]
Optifine 1.19_HD_U_H8_pre1 is not working with shaders, antialiasing, anisotropic filtering, render regions AND IS NOT CAMPATIBLE WITH FORG
![Untitled](https://user-images.githubusercontent.com/87030363/176643711-454ccd7a-0c85-474e-aa7f-d82cf5cbbdbc.png)
E

**Comment by jcain341** [comment]
Thanks for letting me know. I must of overlooked it when I downloaded the program.

Best Regards,

Jerry J. Cain
(408) 480-9177

________________________________
