### ISSUE TITLE
Why are there no Custom Skies in lower Render Distances in older versions than 1.11.2? 

### ISSUE THREAD

**Issue by Batman5300** [sp614x/optifine#688]
Hey, I just have a quick question to ask about Custom Skies being in any render render distances for older versions of Minecraft. On December 28th, plexigras asked a question why there are no Custom Skies for lower render distances, and the next day sp614x replied, "The shorter render distances are for weaker GPUs and they also have problems with Custom Sky." The day after that, sp614x replies stating, "Updated preview B6 for 1.11.2. Fixed Custom Sky to be visible for all render distances." I**f sp614x can make Custom Skies for version 1.11.2, why can't he do versions 1.10.x, 1.9.x, 1.8.x, 1.7.x, etc.? Is there a different coding for Custom Skies?**

**Disclaimer**: I am not disagreeing or want to start an argument with the creator, and I agree with his claim that weaker GPUs may have problems with Custom Skies. He is a good mod creator that the Minecraft community uses his mods every day to play Minecraft like me. 

**Source**: https://github.com/sp614x/optifine/issues/405

**Comment by sp614x** [comment]
The Custom Sky render distance check was backported to all 1.10.x and 1.9.x versions and it should work there. Older versions (1.8.x and 1.7.x) only got a shaders update as their code base is way too different.

**Comment by sp614x** [comment]
The fix can be backported to 1.8.x and 1.7.x on the next round of updates.

**Comment by sp614x** [comment]
Updated preview for 1.8.x and 1.7.x with bugfix.
