### ISSUE TITLE
[Crash] Crash on 1.19

### ISSUE THREAD

**Issue by Zano1999** [sp614x/optifine#6880]
## Description of Issue
The game crash on startup with only Optifine installed

## Steps to Reproduce
1. Install Optifine
2. Open the game

## OptiFine Version
OptiFine HD U H8 pre1

## Installation Method
.jar dropped into mods

## Fabric/Forge Version
Forge 1.19-41.0.62

## Other Installed Mods
None, only Optifine installed

## Log Files/Crash Reports
Log file: https://pastebin.com/8yKcijLb
Crash report: https://pastebin.com/fzsEDsXF

## Prior Testing

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   - Only OptiFine and Forge installed
- Does this happen without any mods at all?
   - No
- Does this happen in Vanilla without OptiFine?
   - No

**Comment by Ari-RERA-43** [comment]
OptiFine doesn't work with Forge yet. This was in the release notes.
