### ISSUE TITLE
Game Crashes "Accessing LegacyRandomSource from multiple threads" OptiFine HD U H8 pre1

### ISSUE THREAD

**Issue by Sparr0w0** [sp614x/optifine#6882]
[crash-2022-06-30_12.28.59-client.txt](https://github.com/sp614x/optifine/files/9022071/crash-2022-06-30_12.28.59-client.txt)
no idea what caused this

**Comment by Ari-RERA-43** [comment]
This has already been reported. Close this issue and check for duplicates before making future issues.

**Comment by KaiAF** [comment]
#6858
