### ISSUE TITLE
[1.19] Bugs

### ISSUE THREAD

**Issue by WhenCato** [sp614x/optifine#6884]
It has a few bugs on my survival world on 1.19 vanila it ran at 74 fps fullscreen (no taskbar visible) but since i downloaded it got around 60 to 59 but when i played it with taskbar visible i got 344 which is rather odd also my cape litterally dosen't work

**Comment by sp614x** [comment]
Please add more specific details about what is broken.
Performance depends on many factors, check the options in menu "Video Settings -> Performance"
