### ISSUE TITLE
1.19 bug 0 fps

### ISSUE THREAD

**Issue by LeadPancake2413** [sp614x/optifine#6887]
Basically i was testing out the new version (with optifine obv) and i went to turn on vsync so i get more stable framerate and stuff and so i do what i normally do sliding the bar all the way to the left, normally here it would set it to vsync but instead it set it to 0FPS as the max framerate and my game crashed

Load Optifine
Load up a world or a server
open pause menu
go to options
video settings
move max framerate slider down to 0 (normally it would set to vsync instead of 0)

## OptiFine Version
Optifine 1.19 preview 1 (i just tested it and it also does this on preview 2)

I downloaded it then clicked the jar file and clicked install

i dont remember since it was yesterday but i think it was error code -1 or 0 (which normally happends when i crash from 0 framerate)

## Prior Testing
no this didnt happen when i tried it on vanilla mc

## Additional Information
plz fix

**Comment by PurlzBeforeSwine** [comment]
Phew I thought I was the only one

**Comment by KaiAF** [comment]
Should be fixed in the latest preview
