### ISSUE TITLE
Issue with Thaumcraft 4 (1.7.10) Warp. "Sun Blind" effect and Fast renderer.

### ISSUE THREAD

**Issue by Nio9345** [sp614x/optifine#689]
I have MC 1.7.10 SkyFactory 2.5 and I'm using Optifine HD 6 U and whenever I get "Sun Blind" Warp effect the screen goes black. I can't even see the Pause menu. I got around it by disabling the Fast renderer in another map I had. This effect applies a filter that oversaturates the colors and has very bright white and for some reason the fast renderer causes the problem with only this effect. I tried Optifine HD 8 U but it crashes the game at loading and when it tries to load the second stage of mod loading.

**Comment by sp614x** [comment]
The Fast Render option is not compatible with mods which use special render effects.
