### ISSUE TITLE
[Bug] Emissive Items Emit Light Despite Options Being Turned Off

### ISSUE THREAD

**Issue by RhodeyCode** [sp614x/optifine#6891]
## Description of Issue
Loaded up pre2 today after installing it, and noticed that torches were emitting light from my hand, which is not an option I've ever had turned on.

## Steps to Reproduce
1. Load up Minecraft with an Optifine 1.19 HD U H8 pre2 profile
2. Ensure you have Dynamic Lights and Emissive Textures off

## OptiFine Version
preview_OptiFine_1.19_HD_U_H8_pre2

## Installation Method
Standalone installer

## Additional Information
I'm using Sildur's Vibrant Shaders v1.32 High, and the early 1.19 release of the oCd resource pack continuation by AntonLandaoALVQ.

First screenshot, in a dirt box, holding a non emissive item
![Java-runtime-gamma Screenshot 2022 07 01 - 11 20 34 33](https://user-images.githubusercontent.com/108501460/176806846-657b9378-3ba1-4a16-ac96-94f6cab2113e.png)

Second screenshot, in a dirt box, holding a torch
![Java-runtime-gamma Screenshot 2022 07 01 - 11 20 41 91](https://user-images.githubusercontent.com/108501460/176806987-c1bcc03c-a477-41f0-98e9-1a4f84195890.png)

Screenshots from my Video Settings and Quality Settings menus
![Java-runtime-gamma Screenshot 2022 07 01 - 11 24 19 86](https://user-images.githubusercontent.com/108501460/176807057-dcd95d6c-7fe9-4377-89a1-ca97f8d1bbe8.png)
![Java-runtime-gamma Screenshot 2022 07 01 - 11 25 25 82](https://user-images.githubusercontent.com/108501460/176807064-ac0d25fb-cf95-45c4-8ab5-c631759c93b4.png)

**Comment by EAZYBLACK** [comment]
if u have nvidia graphic driver 516.40 is buggy with shaders
update driver

**Comment by RhodeyCode** [comment]
> if u have nvidia graphic driver 516.40 is buggy with shaders update driver

I've updated to 516.59, issue is still present.

F3 screen:
![Java-runtime-gamma Screenshot 2022 07 02 - 11 58 28 83](https://user-images.githubusercontent.com/108501460/176982602-b1304702-c6ef-47d8-ba0e-2e9a33ad5c1c.png)

**Comment by Norzeteus** [comment]
I`ve the same problem but I´m not using shaders. As you see on screenshot, my lapis_block and mushroom held in hand, emmesive is working and placed down don`t. ( emmesive always worked also on blocks !) The next Ifound, some monsters as
spiders, skeleton etc. emmesive animation works, but on warden does not...
![2022-07-02_11 05 33](https://user-images.githubusercontent.com/24456750/176994411-b551c836-e728-48f4-8609-2143f83e99aa.png)

**Comment by sp614x** [comment]
Some shaders add own support for handheld lights, check the shaders options.
The emissive textures on placed blocks is fixed in pre6.
