### ISSUE TITLE
Game crashing whenever i zoom or it just crashes randomly without using a resource pack or shaders

### ISSUE THREAD

**Issue by Piliii** [sp614x/optifine#6893]
## Description of Issue
Idk why but for some reason whenever i zoom the game just crashes or when i just mind my own business it also crashes randomly???

## Steps to Reproduce
1. Playing multiplayer normally.
2. zooming.

## OptiFine Version
OptiFine HD U H8 pre2.

## Installation Method
Opening the .jar file and installing optifine 1.19 pre2.

## Log Files/Crash Reports
https://pastebin.com/p1ZwB9n9

## F3 Debug Screenshot
I cant' even open the game for a while to actually take a screenshot.

## Prior Testing
No

**Comment by UnknownTheLad** [comment]
Duplicate of #6858

**Comment by Piliii** [comment]
didnt find the solution :(

**Comment by UnknownTheLad** [comment]
Disable connected textures for now

You can do this in Video settings -> Quality -> Connected textures: Off

**Comment by Piliii** [comment]
Well that worked :)

Thanks for helping me!
