### ISSUE TITLE
[Bug] Connected Texture Issue with Resource Pack

### ISSUE THREAD

**Issue by SalvieMundi** [sp614x/optifine#6904]
## Description of Issue
When moving about the world, crashes occur using the data packs listed in the attached crash report. This is likely something to do with CTM Overhaul or Re-imagined, if I could take a stab in the dark. The crash report specifically zeroes in on net.optifine.ConnectedTextures. Same resource packs work in Optifine for 1.18.2.

## Steps to Reproduce
1. Add the below resource packs
2. Walk around the world til crash. Doesn't seem to take long.

## OptiFine Version
1.19 pre2.

## Installation Method
Standalone jar installer. Just like previous versions.

## Other Installed Mods
None. Issue happens in single player, so not a modded server either.

## Log Files/Crash Reports
[crash-2022-07-01_22.59.13-client.txt](https://github.com/sp614x/optifine/files/9032307/crash-2022-07-01_22.59.13-client.txt)
[crash-2022-07-01_23.02.29-client.txt](https://github.com/sp614x/optifine/files/9032308/crash-2022-07-01_23.02.29-client.txt)
[2022-07-01-1.log.gz](https://github.com/sp614x/optifine/files/9032312/2022-07-01-1.log.gz)
[2022-07-01-2.log.gz](https://github.com/sp614x/optifine/files/9032310/2022-07-01-2.log.gz)
[latest.log](https://github.com/sp614x/optifine/files/9032311/latest.log)

## F3 Debug Screenshot
Can't really do this, I often log into the world and almost immediately crash.

## Prior Testing
- Does this happen in Vanilla without OptiFine?
No. Here is the list of resource packs, in the order which I placed them in Minecraft.
* 200IQ Big Brain GUI
* Colorful Containers
* Fancy: GUI Overhaul
* Improved Variated Connected Bookshelves
* Connected Textures Overhaul
* Enchanted Armor
* Enchanted Weapons
* Enchanted Tools
* Xali's Enhanced Jungle Wood
* Xali's Potions
* Xali's Enchanted Books
* Better Illagers
* Better Skeletons
* Plants Plus
* Visual Target Levels
* Authentic Shadows
* Dimensional Bedrock
* Ore Variants
* Re-imagined
* Monster Diversity Pack
* Creature Variety
* Vanilla Tweaks
* Default

And here are the exact resource packs so you don't have to scour them down. I've also customized a few of them and in case that winds up being an issue, I want you to have *exactly* what I do.

[DimensionalBedrock.zip](https://github.com/sp614x/optifine/files/9032317/DimensionalBedrock.zip)
[EnchantedArmors.zip](https://github.com/sp614x/optifine/files/9032318/EnchantedArmors.zip)
[EnchantedTools.zip](https://github.com/sp614x/optifine/files/9032319/EnchantedTools.zip)
[EnchantedWeapons.zip](https://github.com/sp614x/optifine/files/9032320/EnchantedWeapons.zip)
[FancyGuiOverhaul.zip](https://github.com/sp614x/optifine/files/9032321/FancyGuiOverhaul.zip)
[ImprovedVariatedConnectedBookshelves.zip](https://github.com/sp614x/optifine/files/9032322/ImprovedVariatedConnectedBookshelves.zip)
[MonsterDiversityPack.zip](https://github.com/sp614x/optifine/files/9032323/MonsterDiversityPack.zip)
[OreVariants.zip](https://github.com/sp614x/optifine/files/9032324/OreVariants.zip)
[PlantsPlus.zip](https://github.com/sp614x/optifine/files/9032325/PlantsPlus.zip)
[Re-Imagined.zip](https://github.com/sp614x/optifine/files/9032326/Re-Imagined.zip)
[VanillaTweaksNoGui.zip](https://github.com/sp614x/optifine/files/9032327/VanillaTweaksNoGui.zip)
[VisualTargetLevels.zip](https://github.com/sp614x/optifine/files/9032328/VisualTargetLevels.zip)
[XalisEnchantedBooks.zip](https://github.com/sp614x/optifine/files/9032329/XalisEnchantedBooks.zip)
[XalisEnhancedJungleWood.zip](https://github.com/sp614x/optifine/files/9032330/XalisEnhancedJungleWood.zip)
[XalisPotions.zip](https://github.com/sp614x/optifine/files/9032331/XalisPotions.zip)
[200IqBigBrainGui.zip](https://github.com/sp614x/optifine/files/9032332/200IqBigBrainGui.zip)
[AuthenticShadows.zip](https://github.com/sp614x/optifine/files/9032333/AuthenticShadows.zip)
[BetterIllagers.zip](https://github.com/sp614x/optifine/files/9032334/BetterIllagers.zip)
[BetterSkeletons.zip](https://github.com/sp614x/optifine/files/9032335/BetterSkeletons.zip)
[ColorfulContainers.zip](https://github.com/sp614x/optifine/files/9032336/ColorfulContainers.zip)
[CreatureVariety.zip](https://github.com/sp614x/optifine/files/9032337/CreatureVariety.zip)
[CtmOverhaul.zip](https://github.com/sp614x/optifine/files/9032338/CtmOverhaul.zip)

**Comment by NotADinosaur** [comment]
Connected textures seems to be broken in the prerelease, try just disabling it for now.

**Comment by SalvieMundi** [comment]
Well, yeah. That's why I'm reporting it as a bug lol. But I appreciate the advice.

**Comment by KaiAF** [comment]
Reported #6858
