### ISSUE TITLE
Vsync not available

### ISSUE THREAD

**Issue by Ryguy10712** [sp614x/optifine#6906]
## Description of Issue
When attempting to set the refresh rate to vsync (setting the framerate slider to its lowest setting) you'll see that there isn't a vsync option, and instead sets the max framerate to 0fps which will make the game crash

## Steps to Reproduce
Set the framerate slider all the way down to its lowest value

## OptiFine Version
OptiFine HD U H8 pre2

## Installation Method
The standalone installer opened the jar

## Other Installed Mods
None

## Log Files/Crash Reports
Exit Code: -805306369

## Prior Testing
<!-- If you've installed standalone:
No, vanilla lets you select vsync

**Comment by lucasrueda01** [comment]
Same issue

**Comment by lov3juan** [comment]
same here

**Comment by KaiAF** [comment]
Related to #6857, only difference is it does not display the vsync option
