### ISSUE TITLE
[Bug] Crash at startup with MultiMC on 1.19 preview

### ISSUE THREAD

**Issue by mben42** [sp614x/optifine#6907]
## Description of Issue
Hi, I got a crash at startup with MultiMC. I followed the step by step tutorial in Discord #faq channel to install the mod.

## Steps to Reproduce
1. Download and extract OptiFine HD U H8 pre2 (and MultiMC if you don't have it)
2. Extract with 7zip
3. Move all classes from the notch folder to the main directory or "root" of the folder
4. Compress back the extracted folder into .zip and rename the archive to OptiFine_1.19_HD_U_H2_pre1_MOD_MMC.jar
5. Edit the instance (or create one in 1.19) you want to install OptiFine to, and press "Add to Minecraft.jar"
6. Add OptiFine_1.19_HD_U_H2_pre2_MOD_MMC.jar
7. Start the instance

## OptiFine Version
OptiFine HD U H8 pre2

## Installation Method
Add to Minecraft.jar with MultiMC following FAQ tutorial

## Log Files/Crash Reports
https://paste.ee/p/ABKfS

## F3 Debug Screenshot
Impossible

## Prior Testing
- Does this happen in Vanilla without OptiFine? No

**Comment by Ari-RERA-43** [comment]
> 4. Compress back the extracted folder into .zip and rename the archive to OptiFine_1.19_HD_U_H2_pre1_MOD_MMC.jar
> 6. Add OptiFine_1.19_HD_U_H2_pre1_MOD_MMC.jar

> OptiFine Version:
> OptiFine HD U H8 pre2

Are you using pre1 or pre2?

**Comment by mben42** [comment]
It is written: pre2.

**Comment by mben42** [comment]
I renamed the file with the correct name just to be sure, it doesn't change anything.

**Comment by KaiAF** [comment]
When I try, it does not seem to crash. Are you doing this? https://cdn.discordapp.com/attachments/423433009568546827/916761234987171890/2021-12-02_16-44-59.mp4

**Comment by mben42** [comment]
In the FAQ on Discord it is written to move *classes* from notch to root folder, not to move com and net folders also.

Indeed, once done, it works, thank you.
