### ISSUE TITLE
[Game Crashes] Repeated Crashes in Realms

### ISSUE THREAD

**Issue by aacozy** [sp614x/optifine#6908]
## Description of Issue
In Realms the game crashes after only a few minutes

## Steps to Reproduce
Log in, play. Crash occurs within 3-5 minutes

## OptiFine Version
1.19-Optifine_HD_U_H8_pre2

## Installation Method
Installer

## Other Installed Mods
- BSL shaders (v8.1.02.3)
- Better Leaves Addon (v2.9-1.19)
- Mizunos 16 Craft (v1.19-1.0)

## Log Files/Crash Reports
The game crashed whilst accessing legacyrandomsourse from multiple threads
Error: java.lang.IllegalStateException: Accessing LegacyRandomSourse from multiple threads
Exit Code: *1

## Prior Testing
<!-- If you've installed standalone:
- Does this happen in Vanilla without OptiFine? It doesn't occur in vanilla.

**Comment by UnknownTheLad** [comment]
Duplicate of #6858

**Comment by UnknownTheLad** [comment]
Disable connected textures as a temporary solution.

**Comment by KaiAF** [comment]
Reported #6858
