### ISSUE TITLE
Optifine 1.19 H8 pre2 Crashes upon joining a server 

### ISSUE THREAD

**Issue by Wise-II** [sp614x/optifine#6911]
hello, i have a bug with 1.19 pre2 of optifine,

**steps to reproduce**
join a minecraft on said optifine H8 pre2
ex play.earthmc.net
wait a couple of seconds or open a menu
and it should crash
 **error text**
`The game crashed whilst accessing legacyrandomsource from multiple threads
Error: java.lang.IllegalStateException: Accessing LegacyRandomSource from multiple threads
Exit Code: -1`
i hope this helps with the bug hunting
**installation method**
standalone installer

**Comment by KaiAF** [comment]
Reported #6858
