### ISSUE TITLE
putting a "t" in chat when opening chat

### ISSUE THREAD

**Issue by BaerLKR** [sp614x/optifine#6914]
## Description of Issue
When I press "t" to open chat it sometimes puts a "t" in the input field even though I pressed the key only once. I am on Linux so maybe it is a linux issue but in older versions of Optifine it doesn't happen (tested it in 1.18.2).

## Steps to Reproduce
Open chat on the 1.19 prerelease

## OptiFine Version
1.19 OptiFine HD U H8 pre2

## Installation Method
I used the official launcher and installed via the jar installer

## Log Files/Crash Reports
nothing crashed or anything 

## F3 Debug Screenshot
![2022-07-03_11 29 51](https://user-images.githubusercontent.com/83340886/177033808-524d9db3-7df4-4323-b656-4f76a6803ccb.png)

## Prior Testing
i tested it in 1.18.2 (added to jar in MultiMC)

## Additional Information
it doesn't happen every time but on average every second time

**Comment by Ari-RERA-43** [comment]
This is a vanilla Minecraft bug: [MC-122477](https://bugs.mojang.com/browse/MC-122477)

**Comment by BaerLKR** [comment]
you really know everything, wow
thanks
