### ISSUE TITLE
[Category] Short description

### ISSUE THREAD

**Issue by atlock34** [sp614x/optifine#6916]
Trying to turn on vsync, instead it says "Max Framerate: 0 fps"

## Steps to Reproduce
1. Go to video settings
2. turn max framerate all the way down to vsync

## OptiFine Version
Optifine HD H8_pre2 1.19

## Installation Method
Installed from optifines website

![image](https://user-images.githubusercontent.com/77686019/177050200-e50bbc96-93a7-4bd5-a8f4-78f87fb9bfda.png)

- Does this happen in Vanilla without OptiFine?
No, it does not

**Comment by KaiAF** [comment]
Reported #6857
