### ISSUE TITLE
[Category] Short description

### ISSUE THREAD

**Issue by IwispyI** [sp614x/optifine#6917]
## Description of Issue

crash on start up
## Steps to Reproduce
1. launch the game

## OptiFine Version
preview_OptiFine_1.19_HD_U_H8_pre2

## Installation Method
manual

## Fabric/Forge Version
forge

## Other Installed Mods
none

## Log Files/Crash Reports
[crash-2022-07-03_18.36.21-client.txt](https://github.com/sp614x/optifine/files/9035659/crash-2022-07-03_18.36.21-client.txt)

**Comment by Ari-RERA-43** [comment]
OptiFine doesn't work with Forge on 1.19 yet. This was in the release notes.
