### ISSUE TITLE
[Category] Short description

### ISSUE THREAD

**Issue by YoTempzZ** [sp614x/optifine#6918]
## Description of Issue
 i can not change me frame rate when i go to adjust it it stays on vsync

## Steps to Reproduce
1. What do you do... press settings 
2. ...to find this bug? move the frame rate slider

## OptiFine Version
 HD H8 pre2

## Installation Method
i used the installer 

## Prior Testing
 everything else is great it’s just that my frame rate is locked to what my monitor can run because it’s stuck on vsync

**Comment by KaiAF** [comment]
Reported #6857
