### ISSUE TITLE
[Category] Short description

### ISSUE THREAD

**Issue by jameschou0810** [sp614x/optifine#6919]
## Description of Issue
The game crashes when I enter multiplayer server 

## Steps to Reproduce
1. Enter hypixel
2. game crashes(exit code: -1)

## OptiFine Version
OptiFine HD U H8 pre2

## Fabric/Forge Version
forge-1.19-41.0.63

## Other Installed Mods

[ComplementaryReimagined_r1.1.1.zip](https://github.com/sp614x/optifine/files/9037278/ComplementaryReimagined_r1.1.1.zip)

## Log Files/Crash Reports

[crash-2022-07-04_14.49.39-client.txt](https://github.com/sp614x/optifine/files/9037229/crash-2022-07-04_14.49.39-client.txt)
[crash-2022-07-04_14.54.38-client.txt](https://github.com/sp614x/optifine/files/9037230/crash-2022-07-04_14.54.38-client.txt)
[crash-2022-07-04_15.12.10-client.txt](https://github.com/sp614x/optifine/files/9037231/crash-2022-07-04_15.12.10-client.txt)
[crash-2022-07-04_14.45.05-client.txt](https://github.com/sp614x/optifine/files/9037232/crash-2022-07-04_14.45.05-client.txt)

**Comment by KaiAF** [comment]
Reported #6858
