### ISSUE TITLE
[bug] Water not rendering properly with internal shaders

### ISSUE THREAD

**Issue by RedPride** [sp614x/optifine#6921]
## Description of Issue
while internal shaders is running and building with water it will flicker in and out when placing more block. When water is not rendering properly the only way to get it back is to update the chunk or turn off internal shaders.

## Steps to Reproduce
1. Place standing/flowing water anywhere within world
2. Update chunk water is place in

## OptiFine Version
OptiFine HD U H8 pre3

## Installation Method
Standalone Install

## Log Files/Crash Reports

[latest.log](https://github.com/sp614x/optifine/files/9041365/latest.log)

## F3 Debug Screenshot

![2022-07-04_13 36 47](https://user-images.githubusercontent.com/108690491/177199569-97088122-bd84-4948-b419-150bd02d38ff.png)
![2022-07-04_13 36 33](https://user-images.githubusercontent.com/108690491/177199571-0fd68317-314c-4232-aae2-2e1d02489dc4.png)

**Comment by sp614x** [comment]
Most probably fixed in pre6.
