### ISSUE TITLE
Game crash in Jungle biome

### ISSUE THREAD

**Issue by WIDirt** [sp614x/optifine#6922]
## Description of Issue
While moving in Jungle biome game will freeze. Have to Hard close game to exit.

## Steps to Reproduce
1. Close game completely.
2. Restart game, and move. If vine crosses near center of vision, game freezes.

## OptiFine Version
OptiFine HD U H8 pre2

## Installation Method
Drop the JAR file into your "mods" folder. Yes

## Fabric/Forge Version
Fabric version.

## OptiFabric Version
Optifabric v1.13.4

## Other Installed Mods
Advanced-xray-fabric-1.19-1.10-build.12
AllArrowsInfinityFix-FABRIC-1.3-mc1.19
Architecturyarchitectury-5.7.27-fabric
cloth-config-7.0.72-fabric
collective-fabric-1.19.x-4.27
diggusmaximus-1.5.6-1.19
fabric-api-0.56.0+1.19
Falling-Tree-Mod-Fabric-1.19
fixedanvilrepaircost-fabric_1.19.x-1.8
nametagtweaks-fabric_1.19.x-1.9
roughly-enough-items-1.19.x-fabric-9.0.458
SimpleBackpack_Fabric-1.19.0-1.3.15
wooltostring-fabric-1.19-v1.0.2
Xaeros_Minimap_22.10.1_Fabric_1.19
XaerosWorldMap_1.24.0_Fabric_1.19
Xtra+Arrows+Fabric+MC1.19+v1.9

 No

## Log Files/Crash Reports
[crash-2022-07-04_09.09.13-client.txt](https://github.com/sp614x/optifine/files/9040403/crash-2022-07-04_09.09.13-client.txt)

## F3 Debug Screenshot
![2022-07-04_09 58 08](https://user-images.githubusercontent.com/108682256/177179662-424e57c8-f7f3-432f-b679-96a62f4c7b94.png)

## Prior Testing
No

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? No
   - Only OptiFine, OptiFabric, and Fabric
- Does this happen without any mods at all?
   - Only Forge/Fabric by itself.
- Does this happen in OptiFine standalone? Not Installed
- Does this happen in Vanilla without OptiFine? No
- Have you tried using a binary search to find which mods cause this issue? No
   - To find conflicting mods, split your mods into 2 groups (not including OptiFine/OptiFabric, obviously). Remove one group, and test in-game. Keep the group that has the problem, and repeat until no more mods can be removed without the issue disappearing.
   - Does the issue still happen with only the remaining mods installed? No
      - Forge/Fabric and remaining mods, without OptiFine --> All work as planned

**Comment by KaiAF** [comment]
Reported #6858
