### ISSUE TITLE
very high gpu usage in the debug screen

### ISSUE THREAD

**Issue by mj34261** [sp614x/optifine#6923]
## Steps to Reproduce
1. What do you do...
2. ...to find this bug?

**Comment by vinc3nz** [comment]
Where is the problem? The GPU Usage is lower without Optifine? Are you using an shaders/texturepacks? Any changed settings from Vanilla to Optifine?

**Comment by mj34261** [comment]
> Where is the problem? The GPU Usage is lower without Optifine? Are you using an shaders/texturepacks? Any changed settings from Vanilla to Optifine?

yeah, the gpu usage is lower in vanilla but on the pre the debug screen shows high gpu  usage ( but the gpu usage is the same in windows task manager )

**Comment by fayer3** [comment]
can you post a f3 screenshot?

**Comment by mj34261** [comment]
> can you post a f3 screenshot?

absolutely, just give me a minute

**Comment by fayer3** [comment]
render regions are made to use the gpu to speed up the game. on low end gpus that doesn't really help, so try disabling those.

**Comment by vinc3nz** [comment]
It is the same for me, I don't see a problem here. For me having 100% GPU is better than using my CPU, as I have other programs open to

**Comment by sp614x** [comment]
Turning off Smooth FPS may fix it.
The way MC measures the GPU load is not reliable and Smooth FPS confuses it for some reason.
You can check the real GPU load in TaskManager or with external programs like GPU-Z.

**Comment by mj34261** [comment]
> Turning off Smooth FPS may fix it. The way MC measures the GPU load is not reliable and it looks like Smooth FPS confuses it for some reason. You can check the real GPU load in TaskManager or with external programs like GPU-Z. For me the GPU Load shown in the debug menu jumps with 20% when Smooth FPS is ON, but the real GPU load stays the same.

yeah thats why i got confused, cause in the task manager its much lower, thanks tho i will turn smooth fps off and see if it fixes it
