### ISSUE TITLE
[Natural Textures] Natural Textures for deepslate/nether variants of ores. 

### ISSUE THREAD

**Issue by ghost** [sp614x/optifine#6925]
## Description of the new feature
Natural textures for the deepslate/nether variants of ores, along with adding it for Copper Ore and Emerald Ore as they are left out. A nice feature to have for consistency :)

Attached is a picture of what it currently looks like; normal variants have natural textures while the deepslate/nether variants do not.

![2022-07-05_02 28 39](https://user-images.githubusercontent.com/80747390/177228572-b4d99c76-6190-4554-b3c4-398e4036d535.png)

**Comment by Jiingy** [comment]
This has been implimented, closing this issue.
