### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by TheGreedyPineapple** [sp614x/optifine#6927]
## Description of Issue
The game loads perfectly except for exactly before it hits the loading screen and then suddenly crashes with the following error (I am using curseforge to load the mods)

## Steps to Reproduce
1. Make a modpack using CurseForge with only optifine
2. attempt to load the game

## OptiFine Version
preview OptiFine 1.19 HD U H8 pre4

## Installation Method
Dropped into mods folder

## Fabric/Forge Version
Forge Version

## Log Files/Crash Reports
https://pastebin.com/3JkJbaDD Full Crash Log

## Prior Testing
It occurs with only optifine added with forge. Removing it allows it to load

## Additional Information
Error given from the launcher:
The game crashed whilst unexpected error
Error: java.lang.NoSuchMethodError: 'void net.minecraft.client.Options.load(boolean)'
Exit Code: -1

**Comment by KaiAF** [comment]
OptiFine 1.19 is not compatible with Forge yet.
