### ISSUE TITLE
[BUG] Emissive Textures don't work on placed blocks

### ISSUE THREAD

**Issue by AndrewIdot** [sp614x/optifine#6928]
## Description of Issue
When using emissive textures and adding emissiveness to blocks, placing them will result in the emissive textures not appearing.

![image](https://user-images.githubusercontent.com/78974994/177263252-11158cd2-396e-4289-8c39-340ee2f3b4eb.png)

## Steps to Reproduce
1. Turn on Emissive Textures
2. Add an emissive texture to a block
3. Place it down

## OptiFine Version
Preview 1.19 HD U H8 pre4

## Installation Method

I ran the .jar installer.

**Comment by EAZYBLACK** [comment]
duplicate of #6854

**Comment by sp614x** [comment]
Duplicate of #6854
