### ISSUE TITLE
[Shaders] Shader packs not working correctly

### ISSUE THREAD

**Issue by Drommedhar** [sp614x/optifine#6929]
## Description of Issue
Shader packs seem to flicker and not really work correctly. Water is not rendering too. See attached video.
This happens on all 3 Shader packs I tried, namely:
- SEUS PTGI HRR 3
- SEUS PTGI HRR 2.1
- SEUS Renewed v1.0.1

## Steps to Reproduce
1. Run Minecraft (with Optifine Prev4) and a shader pack

## OptiFine Version
preview_OptiFine_1.19_HD_U_H8_pre4

## Installation Method
Installer

Does this happen in Vanilla without OptiFine?
- No

## Additional Information
GPU: RTX 3080
Driver Version: 516.40
OS: Windows 11 21H2

https://user-images.githubusercontent.com/11786314/177273864-67bb50ba-46a3-4f00-9971-c74675998b57.mp4

**Comment by sp614x** [comment]
Probably Nvidia bug.
