### ISSUE TITLE
[CTM] Overlay not working

### ISSUE THREAD

**Issue by Polydot** [sp614x/optifine#6932]
## Description of Issue
Overlay CTM seems to not work for any block

## Steps to Reproduce
1. Enable a resourcepack that uses overlay CTM
2. Enable connected textures
3. ???
4. don't profit

## OptiFine Version
OptiFine 1.19_HD_U_H8_pre4

## Installation Method
Standalone installer

## F3 Debug Screenshot
![image](https://user-images.githubusercontent.com/5259390/177340382-6fd5dc8d-577f-4180-ba0e-8071b8634683.png)

**Comment by sp614x** [comment]
Should be fixed in pre6.
