### ISSUE TITLE
Complete white and green textures with Nostalgia shaders

### ISSUE THREAD

**Issue by Gixelman** [sp614x/optifine#6933]
## Description of Issue
When using the Nostalgia shaders 4.0 with optifine 1.19 prev4 all the Textures change to white except grass blocks, they are greeen

## Steps to Reproduce
1. Play on Optifine version prev4
2. Use Nostalgia shaders 4.0 

## OptiFine Version
Prev4

## Installation Method
Standalone

## F3 Debug Screenshot
![! Nostalgia shader issue](https://user-images.githubusercontent.com/98358348/177346278-e0a8ce27-d31a-4e79-97f9-0fdb4ad2c302.png)

## Additional Information
The Sky is black but the Clouds from the shader work fine. This happens only on the 1.19 Versions of optfine

**Comment by SynchroniceYT** [comment]
I dont get this with any shader. They simply mess up the UV map for me

**Comment by sp614x** [comment]
Works for me with pre6, probably already fixed.

![image](https://user-images.githubusercontent.com/16635441/177540622-bd232124-0be1-43c7-bd7c-aa387c766da8.png)

**Comment by fayer3** [comment]
as far as I can reproduce it, this seems to be caused by resourcepack shaders interfering with optifine shaders.
@Gixelman are you using any resourcepack?

**Comment by Gixelman** [comment]
@fayer3
Yes I'm using one **but** if I remove it the issue is still the same

**Comment by fayer3** [comment]
have you checked if pre7 still causes this?

**Comment by fayer3** [comment]
did you change anything in the shader, since you extracted it?

**Comment by fayer3** [comment]
does it throw any errors when loading the shader?
and can you send your latest .log when loading the shader, and if possible also your settings files
```
options.txt
optionsof.txt
optionsshaders.txt
```

**Comment by Gixelman** [comment]
Is this it?
[options.txt](https://github.com/sp614x/optifine/files/9066039/options.txt)
?

**Comment by fayer3** [comment]
hm, works all fine for me, can you try resetting your video settings?
`options > video settings > other > reset video settings`

**Comment by Gixelman** [comment]
Nope, still not working

**Comment by fayer3** [comment]
can you try re downloading nostalgia? maybe your copy is defective.

**Comment by SynchroniceYT** [comment]
@fayer3 @Gixelman pre7 seems to have fixed it

**Comment by fayer3** [comment]
as they said, it was something with their copy of nostalgia, nothing specific to the optifine version.
