### ISSUE TITLE
Game Crashes Apon Using A Riptide Trident To Fly 

### ISSUE THREAD

**Issue by TheCaptainTurtle** [sp614x/optifine#6936]
## Description of Issue
The game will crash when i attempt to fly with a trident 

## Steps to Reproduce
1. get a trident with riptide
2. try to fly from water with it 

## OptiFine Version
OptiFine HD U H8 pre5 (1.19) 

## Installation Method
Optifine added to my mod folder 

## Fabric/Forge Version
1.19-forge-41.0.63

## Log Files/Crash Reports
[latest.log](https://github.com/sp614x/optifine/files/9048351/latest.log)
[crash-2022-07-05_13.23.30-client.txt](https://github.com/sp614x/optifine/files/9048356/crash-2022-07-05_13.23.30-client.txt)

## F3 Debug Screenshot
![2022-07-05_13 35 16](https://user-images.githubusercontent.com/103788295/177384390-8c5c945b-5602-473a-b870-1f6ae3fab838.png)

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? yes it does 
- Does this happen without any mods at all?
   - Only Forge/Fabric by itself.  No it doesnt 
- Does this happen in OptiFine standalone? no 
- Does this happen in Vanilla without OptiFine? no 

## Additional Information
the game crashes when i use the riptide trident to fly. only does it when optifines loaded with forge. 

on 1.19  OptiFine HD U H8 pre5

**Comment by TheCaptainTurtle** [comment]
here is a video showcasing what happens

https://user-images.githubusercontent.com/103788295/177387087-e6ea34ae-4789-4657-81f3-04a49cbcc373.mp4

**Comment by cerisuu** [comment]
this happens to me too

**Comment by CyclonXT** [comment]
To me as well
