### ISSUE TITLE
360 FPS Limit

### ISSUE THREAD

**Issue by Poldus87** [sp614x/optifine#6938]
Hello I propose to be able to set its FPS at 360 because people who have a 360Hz screen (like me) are obliged to set the fps to unlimited which drastically increases the use of the graphics card.
The vsync set the FPS to the refresh rate of the screen but vsync has too much input lag

I made a preview of what it might look like
![Capture d’écran 2022-07-05 212511](https://user-images.githubusercontent.com/52009517/177401638-08738dc9-4378-4f69-86fb-3d266cc8bf1d.png)

**Comment by Peca21** [comment]
Input lag depends on framerate so at 360fps there is not input lag, there may be some with vsync+gsync but not at 360 fps. Also this is minecraft, not sure why you need every millisecond of no input lag. If I could have played Rainbow 6 Ranked and get to gold with vsync I think you will survive with 360fps vsync. Also minecraft works at 20 ticks/s so everything has a delay of like 50ms anyway.

**Comment by GABRlEL** [comment]
> Input lag depends on framerate so at 360fps there is not input lag, there may be some with vsync+gsync but not at 360 fps. Also this is minecraft, not sure why you need every millisecond of no input lag. If I could have played Rainbow 6 Ranked and get to gold with vsync I think you will survive with 360fps vsync. Also minecraft works at 20 ticks/s so everything has a delay of like 50ms anyway.

what a bad take, let's all play at 50 fps because everything has a delay of 50 ms anyways. you don't even know what the issue poster does in minecraft

anyways: have you tried setting a different value, then modifying your options file?

**Comment by Poldus87** [comment]
> > Input lag depends on framerate so at 360fps there is not input lag, there may be some with vsync+gsync but not at 360 fps. Also this is minecraft, not sure why you need every millisecond of no input lag. If I could have played Rainbow 6 Ranked and get to gold with vsync I think you will survive with 360fps vsync. Also minecraft works at 20 ticks/s so everything has a delay of like 50ms anyway.
> 
> what a bad take, let's all play at 50 fps because everything has a delay of 50 ms anyways. you don't even know what the issue poster does in minecraft
> 
> anyways: have you tried setting a different value, then modifying your options file?

I tried but it automatically resets the fps settings.

**Comment by Poldus87** [comment]
> Input lag depends on framerate so at 360fps there is not input lag, there may be some with vsync+gsync but not at 360 fps. Also this is minecraft, not sure why you need every millisecond of no input lag. If I could have played Rainbow 6 Ranked and get to gold with vsync I think you will survive with 360fps vsync. Also minecraft works at 20 ticks/s so everything has a delay of like 50ms anyway.

BTW i see the difference with and without VSYNC at 360fps :D

**Comment by Ebaad69** [comment]
Have you tried using other apps like afterburner to cap your FPS?

and he is right Vsync does cause huge input lag

**Comment by sp614x** [comment]
The limit 255 should be close enough to 360 for all practical purposes.
Visually it would not make a noticeable difference and for input lag it would be 3.9ms vs 2.7ms = 1.2ms difference, which is nothing.

**Comment by Poldus87** [comment]
> Have you tried using other apps like afterburner to cap your FPS?
> 
> and he is right Vsync does cause huge input lag

Thanks it work for me :D
