### ISSUE TITLE
[Crash] Feeding Goats  -  Cannot read field "f_19853_" because "entity" is null Exit Code: -1

### ISSUE THREAD

**Issue by osdeibi** [sp614x/optifine#6943]
## Description of Issue
 Cannot read field "f_19853_" because "entity" is null Exit Code: -1

## Steps to Reproduce
1) any world (Server or Offline)
2) Find or generate Goats
3) Feed them

## OptiFine Version
OptiFine HD U H8 pre5

## Installation Method
Drop the Jar on the mod folder

## Fabric/Forge Version
1.19 - 41.0.63

## Other Installed Mods
No extra mods, even with extra mods have the same error

## Log Files/Crash Reports
https://pastebin.com/Wn9dPV7N

**Comment by DonZekane** [comment]
+1 Experiencing it too!

**Comment by sp614x** [comment]
Fixed, coming in pre6.
