### ISSUE TITLE
Emissive textures don't work

### ISSUE THREAD

**Issue by PsykaaX** [sp614x/optifine#6945]
## Description of Issue
With my texture pack, diamond ores textures were emissive with all previous optifine versions.
Now it works only with the item in the hand but when I place the block, his not emissive.

## Steps to Reproduce
Install a pack with emissive textures for diamond ores
Take a diamond ore in your hands (deepslate or classic)
Place it !

## OptiFine Version
OptiFine HD U H8 pre6 (preview 1.19)

## Installation Method
Standalone

![Capture d’écran de 2022-07-06 14-44-20](https://user-images.githubusercontent.com/108810975/177555674-940742f1-48b1-4e81-9628-7db79a46fda4.png)
![Capture d’écran de 2022-07-06 14-44-23](https://user-images.githubusercontent.com/108810975/177555679-a41d50ee-a395-4d40-b776-3e25e999d570.png)
![Capture d’écran de 2022-07-06 14-44-29](https://user-images.githubusercontent.com/108810975/177555680-da003ec6-b8c7-4c6e-ba40-a0e493cbe38d.png)

**Comment by PsykaaX** [comment]
> Fixed in pre6.

I used pre6 too.. i'll try to make some changes in the pack and maybe it will work.. 

> it works for me though, maybe emissive blocks don't work with 32x textures. ![2022-07-06_16 19 17](https://user-images.githubusercontent.com/67115598/177559765-e7a98cfb-ce71-4d2a-b794-97b5363c3d66.png)

Thanks for the time you spent for me (and sorry for my bad French's english speaking)

**Comment by fayer3** [comment]
if you still have that issue with pre6/7 make a F3 screenshot that shows the issue
