### ISSUE TITLE
[Bug] The game crashed whilst rendering chunk

### ISSUE THREAD

**Issue by MightyElemental** [sp614x/optifine#6946]
## Description of Issue
Game crashed while using Optifine's internal shaders

## Steps to Reproduce
1. Use internal shaders
2. High render distance

## OptiFine Version
OptiFine_1.19_HD_U_H8_pre6

## Installation Method
Standalone installer

## Log Files/Crash Reports
`The game crashed whilst rendering chunk
Error: java.lang.OutOfMemoryError: Unable to allocate 9565928 bytes
Exit Code: -1`

https://pastebin.com/gcj4G68j

## F3 Debug Screenshot
N/A

## Prior Testing
Has not happened previously without Optifine

**Comment by EAZYBLACK** [comment]
that means u dont have available ram
maybe 1.19 eats more ram
or it can even be a optifine ram bug

**Comment by sp614x** [comment]
You can:
- allocate more memory for MC
- reduce render distance
- disable shaders, AA/AF, render regions
