### ISSUE TITLE
[1.19] Lightmaps make the darkness effect pitch black

### ISSUE THREAD

**Issue by SeaOfPixels** [sp614x/optifine#6949]
## Description of Issue
The fix of #6873 in pre7 seems to have resulted in Lightmaps making the darkness effect completely black. The lightmap in the screenshot makes darkness lighter than normal and yet with the darkness effect everything is pitch black.

## OptiFine Version
1.19 pre7

**Comment by SeaOfPixels** [comment]
![2022-07-06_12 38 13](https://user-images.githubusercontent.com/62183036/177629888-7a58b377-982a-4bcd-a5f5-407e846af151.png)
![2022-07-06_12 38 18](https://user-images.githubusercontent.com/62183036/177629932-e6eb94db-bb00-43b7-b4e2-a50ee4533d27.png)

**Comment by SeaOfPixels** [comment]
First is without Lightmaps (aka with Custom Colors off), and 2nd is with.

**Comment by sp614x** [comment]
Fixed, coming in pre8.

**Comment by SeaOfPixels** [comment]
Still not fixed in OptiFine_1.19.2_HD_U_H9. Lightmaps still mess with the darkness effect.
![2022-09-04_08 28 29](https://user-images.githubusercontent.com/62183036/188321308-f61899c1-da4d-450e-a1c7-72a5469f51ca.png)
![2022-09-04_08 28 33](https://user-images.githubusercontent.com/62183036/188321309-de0434f7-dd5f-4f1a-bd90-712f553a4231.png)

**Comment by SeaOfPixels** [comment]
(2nd screenshot is with Custom Colors disabled).

**Comment by SeaOfPixels** [comment]
Requesting repos be re-opened.
