### ISSUE TITLE
[CTM] Block with custom model doesn't use the tiles assigned by ctm_compact method

### ISSUE THREAD

**Issue by rger0** [sp614x/optifine#6951]
## Description of Issue
Hi,

I'm using a custom model for leaves as a vanilla replacement of the better foliage mod.
To get more of a bushy look, one of the textures leveraged by the custom model has cropped corners :

![](https://www.zupimages.net/up/22/27/tenn.jpg)

Problem is : when placed side by side, the cropped corners form ugly holes in trees :
(I've added a red dot in the middle of the hole for clarity)

![](https://www.zupimages.net/up/22/27/i1ga.jpg)

To get rid of those holes, I tried to use a ctm_compact method targeting the file with the cropped corners, but it isn't picked up by the game/optifine.

Am I doing it wrong? Or am I trying to achieve something that Optifine cannot do?
**If it's just some mistake from my part, I apologize in advance.**

## OptiFine Version
OptiFine_1.18.2_HD_U_H7

## Installation Method
Problem is present with both Forge and Standalone installations

## Additional Information
**Here's the location of the file that is used by the custom model :**
\assets\minecraft\textures\blocks\leaves\acacia.png

**Here's the location of the properties file that targets the tile mentioned above :**
\assets\minecraft\optifine\ctm\blocks\leaves_acacia\acacia_leaves.properties"

**And here's the content of the properties file :**
matchTiles=textures\blocks\leaves\acacia.png
method=ctm_compact
tiles=0-4

**Comment by sp614x** [comment]
The compact CTM method only works with the default block model.
It needs the model to have exactly predefined size and orientation, otherwise the texture stitching will not work or it will have visible seams.

**Comment by rger0** [comment]
> The compact CTM method only works with the default block model. It needs the model to have exactly predefined size and orientation, otherwise the texture stitching will not work or it will have visible seams.

Thank you very much for the clear answer,
Have a nice day
