### ISSUE TITLE
[Rendering] End Portal Renders Incorrectly From Some Angles

### ISSUE THREAD

**Issue by Deebz96** [sp614x/optifine#6955]
## Description of Issue
From certain angles, end portals do not render correctly. It is difficult to describe the look, so I have some images below. It will look correct if you stand from some spots, but break when looking from other spots. Happens with no other mods installed.

Interestingly, this does not seem to happen with shader packs I have tested, such as Complementary Shaders. Only with shaders disabled.

## Steps to Reproduce
1. Install Optifine.
2. Find end portal, walk around it while looking at it.

## OptiFine Version
OptiFine 1.19_HD_U_H8_pre8

## Installation Method
Standalone Installer

## F3 Debug Screenshot

Vanilla 1.19:
![2022-07-07_14 10 12](https://user-images.githubusercontent.com/23617228/177841329-53ad6f2e-284f-4f42-a708-26a2181e04a0.png)

Optifine 1.19:
![2022-07-07_14 04 31](https://user-images.githubusercontent.com/23617228/177841355-08f97aeb-056e-4453-bdee-50ac2686a30b.png)

**Comment by sp614x** [comment]
Seems to be caused by Fast Render.

**Comment by sp614x** [comment]
Fixed.

**Comment by Lolothepro** [comment]
Affects Optifine 1.19.4
