### ISSUE TITLE
[Rendering] Black sky when using shaders

### ISSUE THREAD

**Issue by krzysirk** [sp614x/optifine#6958]
## Description of Issue
Black sky during sunset when looking at specific angle with shaders

## Steps to Reproduce
1. Turn on shaders (I tested only on sildurs vibrant)
2. Wait for sunset

## OptiFine Version
preview_OptiFine_1.19_HD_U_H8_pre7

## Installation Method
dropped .jar file into mods folder

## Fabric/Forge Version
0.14.8

## OptiFabric Version
1.13.4

## Other Installed Mods
Mod Menu

## F3 Debug Screenshot
![2022-07-07_23 01 56](https://user-images.githubusercontent.com/108900634/177870816-09476e5f-1e40-4b3a-8e9a-47dedb2390a3.png)
![2022-07-07_23 02 00](https://user-images.githubusercontent.com/108900634/177870820-b3f945eb-f943-42ed-b92b-92552a6cf03c.png)

**Comment by fayer3** [comment]
can you check without fabric?

**Comment by krzysirk** [comment]
Same issue

**Comment by fayer3** [comment]
update the shader, that was a bug in that version

**Comment by krzysirk** [comment]
Yeah it was a shader bug. Updated from 1.29 to 1.31 and it fixed
