### ISSUE TITLE
Perpetual freezing while loading worlds or joining servers

### ISSUE THREAD

**Issue by TxTalonTx** [sp614x/optifine#696]
There was another, similar issue posted recently, but I'm creating a separate thread just in case this isn't the same one;

The issue started about a month ago and I don't know what caused it. I run Windows 10 and have been doing so since August of 2015.

Whenever I try to load a world or join a server, the framerate drops to 0 before the loading screen changes to the in-game screen. The frame updates once every 5-10 seconds but the game is never able to load any chunks. This _solely_ happens on OptiFine; Vanilla versions are fine.

So far, I have tried updating my video drivers, changing my Java version, changing my OptiFine version, changing my Minecraft version, and reinstalling Minecraft; reinstalling fixed it for a day, but it's back again and I don't know why.

[Here's a pastebin of my previous log file](https://pastebin.com/hzAp61pN); be warned that it's 3051 lines (which I'm pretty sure is abnormally long) over about 74 seconds of the game running. Thanks to anybody who is able to help.

**Comment by Builderb0y** [comment]
Smooth FPS? #583

**Comment by TxTalonTx** [comment]
That certainly fixed it. Thank you!
