### ISSUE TITLE
Game crashes (Minecraft: 1.19, Forge: 41.0.64, OptiFine: preview_OptiFine_1.19_HD_U_H8_pre9)

### ISSUE THREAD

**Issue by SonicGamer27** [sp614x/optifine#6962]

**Comment by MaxiH-AGM** [comment]
Error: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_778 failed
Exit Code: -1

**Comment by sp614x** [comment]
Most probably a conflict with some of the installed mods.

**Comment by ZerdoX-x** [comment]
@sp614x nope. check this out: https://github.com/MinecraftForge/MinecraftForge/pull/8786
