### ISSUE TITLE
[CEM Animation] 'is_on_shoulder' for parrots

### ISSUE THREAD

**Issue by FFreshLX** [sp614x/optifine#6968]
Boolean `is_on_shoulder` would allow us to give a different animation specifically when a parrot is on the player's shoulder, left and right.

In the parrot's vanilla animation, the tail swings a bit as the player walks, which I assume uses sin(limb_swing)*limb_speed expression as a typical walking animation would. 
Currently in 1.19 OptiFine HD U H8 pre10, any custom animation that uses limb_swing and limb_speed plays when the player moves. `is_on_shoulder` could be used to separate the animations and solve the issue. 

It also _seems_ to randomly pick whether `is_on_ground` is true or false when it sits on the player's shoulder.

![2022-07-09_17 13 47](https://user-images.githubusercontent.com/74279625/178094340-baa0a0e2-1ddf-4ce8-82df-0f69e5ef62a0.png)
^ Parrot animations while the player walks - one flying and one walking - `if(is_on_ground, [walk], [fly])`

**Comment by FFreshLX** [comment]
Doing a fantastic job with CEM this update btw, appreciate it 🙏

**Comment by ewanhowell5195** [comment]
`is_on_head` could also be used. it doesnt make 100% sence, but its kinda close and already exists as a parameter (if you dont want to add a new one)
