### ISSUE TITLE
[CTM Bug] Biome depedant block textures not working 

### ISSUE THREAD

**Issue by Ratriq** [sp614x/optifine#6971]
## Description of Issue
As titel implies, CTM biome dependant textures for blocks in resource packs does not work. For example a spruce crafting table in a spruce biome or a special berry bush in certain biomes simply doesn't change said block texture. There no colormap or tinting involved for this to not work. Just pure texture replacements, which doesn't work in the current version.
Here is an example of my spruce leaves and berry bushes of what they look like, and what they are supposed to look like:
Not working: https://gyazo.com/52654f5de76d754aff2fcfe509bd1c80
Working: https://gyazo.com/9ee76826607e95245fbb8bf00d9f8b99

## Steps to Reproduce
1. Use a pack that has CTM biome dependant textures which changes the texture of a block depending on the biome
2. Have optifine installed
3. Go to a biome where said block in the pack should change it's texture depending on which biome it's placed in.

## OptiFine Version
1.19 optifine HD U H8

## Installation Method
Installed with installer

## Additional Information
[Link](https://www.curseforge.com/minecraft/texture-packs/minecraft-reimagined/files) to pack used in the provided images to recreate this issue.

**Comment by sp614x** [comment]
Works for me:

![image](https://user-images.githubusercontent.com/16635441/178121954-61020f9e-106b-4fe1-b54c-d69358ac7797.png)

OF is installed standalone, resource pack is Reimagined. 
The left biome is `taiga`, the right one is `snowy_taiga`

**Comment by Ratriq** [comment]
> Works for me:
> 
> ![image](https://user-images.githubusercontent.com/16635441/178121954-61020f9e-106b-4fe1-b54c-d69358ac7797.png)
> 
> OF is installed standalone, resource pack is Reimagined. The left biome is `taiga`, the right one is `snowy_taiga`

Oh actually that's completely my bad so sorry, I had forgotten the CTM option in the menu was still disabled since it's been crashing my game in the pre-releases and, ironically, forgot the CTM option also affects the biome dependant blocks.
