### ISSUE TITLE
[Crash] Minecraft crashes with Forge and Optifine

### ISSUE THREAD

**Issue by BlueberryYum** [sp614x/optifine#6975]
## Description of Issue
Minecraft immediately crashes when having Optifine as a mod for Forge.

## Steps to Reproduce
1. Place Optifine in the mods folder.
2. Play Minecraft from the Windows 7/8 version of the Minecraft Launcher with Forge selected as the Version.

## OptiFine Version
OptiFine 1.19 HD U H8

## Installation Method
Optifine dropped into the mods folder.

## Forge Version
Forge version 41.0.87

## Other Installed Mods
https://pastebin.com/DbG9T1Pi

## Log Files/Crash Reports
[latest.log](https://github.com/sp614x/optifine/files/9078272/latest.log)
[debug.log](https://github.com/sp614x/optifine/files/9078271/debug.log)
[CrashReport.txt](https://github.com/sp614x/optifine/files/9078265/crash-2022-07-09_18.28.52-client.txt)

## Prior Testing
-Doesn't happen in Vanilla
-Happens when Optifine is in the mods folder
-Doesn't happen in standalone
-Placed only mod libraries in the mods folder with Optifine. Minecraft crashes.

## Additional Information
The first instances of this happening was when I put Optifine with my other mods. Minecraft crashed... I guess. The launcher didn't even open. After removing some mods, the launcher finally opened when Minecraft crashed. Then, I removed all of the mods except Optifine. It worked one time, and after that, Minecraft just crashes.

**Comment by TheRealJacker** [comment]
Optifine is not compatible with Forge version 41.0.87

Use Forge version 41.0.63 instead!
Please be carefull next time and read the webpage before opening an issue, saves everyone time :D

**Comment by elestedt** [comment]
Do you have any timeline on an updated OptiFine that supports Forge 41.0.94 and later? Apparently there was a breaking change in forge at that time, so now that mods are upgrading more and more are incompatible with current version supported by OptiFine :(

**Comment by sp614x** [comment]
Latest preview supports 41.0.105, but older Forge versions would probably not work as Forge is in the process of making many internal changes.
