### ISSUE TITLE
[Bug] OptiFine not loading in 1.19

### ISSUE THREAD

**Issue by omerien** [sp614x/optifine#6978]
WARNING : NOT AS MANY ISSUES, MY GAME DOESN'T CRASH.

## Description of Issue
When I load OptiFine with Forge, OptiFine doesn't load, although another mod installed in the same mod repository is loading perfectly (NoChatReports). OptiFine doesn't appear in the mod menu, but NoChatReports does.

## Steps to Reproduce
1. Install OptiFine as a mod
2. Launch Forge with OptiFine

## OptiFine Version
OptiFine : 1.19_HD_U_H8.

## Installation Method
Dropped in mods folder.

## Fabric/Forge Version
Forge : 41.0.63, alias the version reported as working in the Changelog.

## Other Installed Mods
NoChatReports : [Latest stable](https://curseforge.com/minecraft/mc-mods/no-chat-reports/files/3855258).

## Log Files/Crash Reports
[2022-07-10-1.log.gz](https://github.com/sp614x/optifine/files/9078915/2022-07-10-1.log.gz). (Simple start and quit. No server joining.)

## F3 Debug Screenshot
I think it can't help, but...
![2022-07-10_13 09 13](https://user-images.githubusercontent.com/53191414/178142409-bee4d736-b146-4493-9a7e-c1264818254b.png)

## Prior Testing
- Does this happen without other mods installed? 
   - Yes, without any mod it still happens
- Does this happen in OptiFine standalone?
   - No

## Additional Information
macOS 12.4, M1 Pro computer.

**Comment by fayer3** [comment]
that doesn't look like a complete log, just some chat in there, and server icons being invalid

**Comment by UnknownTheLad** [comment]
1. OptiFine does not show in the mod menu, you can see if OptiFine has been successfully loaded by going to the video settings.
2. Your f3 screen suggests that OptiFine has indeed loaded judging by that fact that OptiFine F3 components are present.

**Comment by RohanGoyalDev** [comment]
> 1. OptiFine just does not show in the mod menu, you can see if OptiFine has been successfully loaded by going to the video settings.
> 
>     2. Your f3 screen suggests that OptiFine has indeed loaded judging by the fact that OptiFine F3 components are present.

Yes, it does load on version `41.0.63`. `41.0.64` introduced a breaking change that prevents it from working. OP specified that. In the screenshot, he is using `41.0.63`.

On `41.0.64` it crashes with this [crash-report](https://www.toptal.com/developers/hastebin/ibixivipok.yaml)

Please reopen the issue
