### ISSUE TITLE
Can't find shaders

### ISSUE THREAD

**Issue by Quadro64** [sp614x/optifine#699]
Can't find shaders; i have sildurs shaders in shaderpacks folder in a folder named sildur. in OptiFine 1.11.2 HD U C2 i only find the shader called (internal) which just is normal minecraft. laptop information: 
DELL LATITUDE 3350
OS            Microsoft Windows 10 Enterprise 10.0.14393 Build 14393
CPU          Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz, 1995 Mhz, 2 Core(s), 4 Logical Processor(s)
GPU          Intel(R) HD Graphics 5500
RAM         4.00 GB
STORAGE  SanDisk Z400s 2.5 7MM 128GB

**Comment by SetantaLP** [comment]
I think shaders have to be packed as a zip file (in contrast to resourcepacks where you can also use a folder), with a folder named shaders in the base directory of the zip-file. And don't forget to place all shader-components that are directly used by optifine in this folder.

**Comment by Builderb0y** [comment]
No, shader packs can be folders too. They just have to be in the right place. For zipped shader packs, they must be placed in `.minecraft/shaderpacks/(pack name).zip`. For folders: `.minecraft/shaderpacks/(pack name)/shaders/(all the .fsh/vsh files)`.

**Comment by SetantaLP** [comment]
Ah okay. So it's only important that the shaderpack's internal structure fits the pattern `/shaders/(all .fsh/vsh files)`, no matter if the pack itself is a zip-file or a directory.

**Comment by Builderb0y** [comment]
Correct.
