### ISSUE TITLE
[Category] Short description game crashes because of specific block

### ISSUE THREAD

**Issue by HeartKiro** [sp614x/optifine#6991]
## Steps to Reproduce
1. What do you do... when you walk out of render distance then back into it
2. ...to find this bug?

## OptiFine Version
 OptiFine_1.19_HD_U_H8_pre1

## Installation Method
 Standard

## Log Files/Crash Reports

-- Block model being tesselated --
Details:
	Block: Block{minecraft:sandstone}
	Block location: World: (-81,58,-2168), Section: (at 15,10,8 in -6,3,-136; chunk contains blocks -96,-64,-2176 to -81,319,-2161), Region: (-1,-5; contains chunks -32,-160 to -1,-129, blocks -512,-64,-2560 to -1,319,-2049)
	Using AO: true

## F3 Debug Screenshot

![image](https://user-images.githubusercontent.com/109238107/178792643-2783c5cf-3017-493f-bc1b-5509e408c557.png)

## Additional Information

I've noticed it is only happening with sandstone blocks, and I'm on a multiplayer server. It's a vanilla server, a non-integrated multiplayer server. Once I remove the block it doesn't happen again until another block causes the crash.

**Comment by UnknownTheLad** [comment]
Please update your god damn optifine

**Comment by UnknownTheLad** [comment]
This is fixed in the full release/H9 pre1

**Comment by HeartKiro** [comment]
Oh, sorry. I wasn't aware of that. I thought I had the full version
