### ISSUE TITLE
[Visual Bug] Z Coordinate blocked in F3 Debug

### ISSUE THREAD

**Issue by QuickyTime** [sp614x/optifine#6992]
## Description of Issue

In the F3 Debug screen the Z coordinate is blocked by adjacent text detailing system info, It only shows this way
with Optifine.
## Steps to Reproduce
I'm not sure, I just Installed Optifine normally, Launched the game and it was like that.

## OptiFine Version

All 1.19 Builds, current one being, OptiFine HD U H9 pre1

## Installation Method

Used the Installer.

## F3 Debug Screenshot

Without Optifine
![2022-07-13_12 14 32](https://user-images.githubusercontent.com/108911610/178816110-bfd846c0-41c2-4a31-aa4d-802393bee2d7.png)
With Optifine
![2022-07-13_12 16 12](https://user-images.githubusercontent.com/108911610/178816262-928271f4-d32f-4729-ab69-589e59765083.png)

## Prior Testing

     
Happens with Optifine but does not in Vanilla, no mods currently installed nor shader packs.

## Additional Information

F3 Debug doesn't show native resolution so mine is 1920x1080@144Hz

**Comment by fayer3** [comment]
not really an issue imo, since even vanilla has overlapping elements with their Noise router and block info.

**Comment by sp614x** [comment]
You can fix it by reducing the font size, for example GUI Scale: 2.
