### ISSUE TITLE
[Revert Recommended Forge Version for 1.19] Is it possible to revert to an earlier forge version of 1.19?

### ISSUE THREAD

**Issue by JKaiya** [sp614x/optifine#6993]
## Description of the new feature
I noticed that forge 41.0.63 or whatever version optifine recommended says to use for 1.19 seems to possess many game breaking bugs that corrupts the world. Unless if I am very unlucky case. This isn't really a bug report for Optifine, but I was wondering how long Optifine will take to update to a new version, or if it is possible to downgrade the forge version. My world keeps getting corrupted, and every time I thought I finally fixed it, I find a new game breaking bug...

I know that it take for ever to update Optifine for new versions, however, is it possible to do a quick update if the forge version is reverted to an earlier version of 1.19? Or is it possible to just run Optifine with an earlier veresion? As although I attempted new versions (which did not work) I have not tried the older versions.

The bugs I discovered were the folowing. First bookshelves didnt work, and were super glitchy with having infinite placement and invisible/disapearing textures, then I finally fixed by deleting a mod that caused it (terrablender & Biomes O Plenty [which worked perfectly fine before forge update]) due to the forge version (as every mod I had worked perfectly fine before I updated forge for the optifine version). Then I noticed the Nether Portal wouldn't teleport... This took way way way longer to to fix and didn't even have to do with my mods, just due to world corruption. Now when I FINALLY thought I fixed everything, I noticed that some generating chests are corrupted, causing game to break, and need to close by task manager as you can not exit the game, all the ai breaks, while youc an still move around but no items drops, et cetera... I feel like when I finally fix this problem, that is taking even longer than the two before, I'll just find another world corruption bug due to the forge version, which I suspect to cause high incompatibility/bugs in mods. I'm tempeted to start a new world at this point as it might also be due to all the left over corruption, but I already put days into this world...

**Comment by sp614x** [comment]
Forge 1.19 is still in beta and not recommended for normal gameplay. It is undergoing a lot of internal reorganizations right now so it is possible that there may be bugs. OptiFine will be updated to support latest Forge in one of the next previews.
