### ISSUE TITLE
I can't zoom using button 4

### ISSUE THREAD

**Issue by LirekPL** [sp614x/optifine#700]
When I set button 4 for zoom it didn't worked. I tested for example sneak for button 4 and it worked. Zoom    worked with any other button. Button 4 is button to back pages in browser. In 1.10 and 1.11 zoom with button 4 works.

**Comment by sp614x** [comment]
The buttons 1 to 3 are generating separate press and release events so the zoom can activate and deactivate.
The mouse buttons 4 and 5 (browser back and forward) are generating one single click event when pressed, therefore the zoom is activated and deactivated immediately. 
The buttons work identically in versions 1.10 and 1.11, they have the same problem with buttons 4 and 5.

**Comment by sp614x** [comment]
Sneak is also not working with buttons 4 and 5. It activates and deactivates immediately.
