### ISSUE TITLE
[Category] Crashing on startup with Ragnamod VI

### ISSUE THREAD

**Issue by ndlanier** [sp614x/optifine#7003]
## Description of Issue
Ragnamod VI: https://www.curseforge.com/minecraft/modpacks/ragnamod-vi
Forge Version: 36.2.22

## Steps to Reproduce
1. Install OptiFine HD U G8 into the mods folder of your Ragnamod VI instance
2. Launch the mod

## OptiFine Version
HD U G8 for Minecraft 1.16.5

## Installation Method
Manually downloaded and copied to mods folder

## Fabric/Forge Version
36.2.22

## Other Installed Mods
These are all a part of the mod pack
https://pastebin.com/YfAjxgcm

## Log Files/Crash Reports
https://pastebin.com/RRUmbA8y

## F3 Debug Screenshot
N/A Unable to successfully start

## Prior Testing
Logged out
Rebooted
Made sure java was up to date
Pointed cursforge mods folder to a different drive to start fresh
Fresh install of ragnamod vi
Tried loading into a world without optifine and then added optifine on the next launch

## Additional Information
This is a large mod pack, I know, but it is almost impossible to run without optifine.
Opened an issue on the cursforge page for Ragnamod VI (also a bit of a feature request): https://www.curseforge.com/minecraft/modpacks/ragnamod-vi/issues/1179

**Comment by Xplodin** [comment]
anything that can get this working?
