### ISSUE TITLE
Uncompatible With Emojiful

### ISSUE THREAD

**Issue by kenijey** [sp614x/optifine#701]
using forge 2333, optifine pre release for 1.12 (latest that posted on 17.06.2017) and using custom main menu 2.0.6
this is my normal main menu (without optifine)
![23](https://user-images.githubusercontent.com/24831406/27255574-fa99121a-53a8-11e7-85b8-cadcabea60db.PNG)
and this is with optifine:
![22](https://user-images.githubusercontent.com/24831406/27255586-37d6d838-53a9-11e7-9ac6-5a0d26e64b63.PNG)
dunno what causes. (maybe not CMM)

**Comment by ElectricBlue1** [comment]
Yea same this is with Preview A1 and when i click on a button (at random spot as i cant see them) the screen flashes.

**Comment by kenijey** [comment]
yeah, options menu is amazing (i think it's options menu)

**Comment by sp614x** [comment]
Can you post the CustomMainMenu configuration (json and textures)?

**Comment by kenijey** [comment]
[Desktop.zip](https://github.com/sp614x/optifine/files/1083059/Desktop.zip)

**Comment by ElectricBlue1** [comment]
I still have the same issue with "OptiFine 1.12 HD U C2" where the text/buttons and gui aren't showing. I think its CMM. 
**Regular:** 
![capture1](https://user-images.githubusercontent.com/14302401/27261333-07f3c142-540f-11e7-87a2-6e398e995178.PNG)
**Optifine:**
![capture2](https://user-images.githubusercontent.com/14302401/27261342-1f6a2104-540f-11e7-8a26-90f032faf612.PNG)
![capture3](https://user-images.githubusercontent.com/14302401/27261343-1f70c7d4-540f-11e7-9f32-5067e6ad1420.PNG)

**Comment by kenijey** [comment]
oh nooooooooooo, it's not CMM, see this:
![123](https://user-images.githubusercontent.com/24831406/27332273-e014e4a0-55c9-11e7-90a8-a8f391c8ba97.PNG)
really wondering what causes :/

**Comment by kenijey** [comment]
okay i've found the mod, it's Emojiful. what should we do?

**Comment by sp614x** [comment]
So CustomMainMenu works with OptiFine?

**Comment by sp614x** [comment]
Emojiful tries to patch the FontRenderer and fails:
```
 Caused by: java.lang.NoSuchMethodError: net.gegy1000.emojiful.render.EmojiFontRenderer.doDraw(F)V
 	at net.gegy1000.emojiful.render.EmojiFontRenderer.func_78255_a(EmojiFontRenderer.java:129)
 	at net.minecraft.client.gui.FontRenderer.func_180455_b(FontRenderer.java:683)
```

**Comment by sp614x** [comment]
Updated preview C3 for 1.12:
- fixed conflict with Emojiful
