### ISSUE TITLE
optifine 19.1

### ISSUE THREAD

**Issue by tails1974seeyounextgame** [sp614x/optifine#7010]
optifine 19.1 hd u 8
OptiFine and Immersive Engineering crash instantly on launch, need a workaround please

https://www.reddit.com/r/feedthebeast/comments/k2eo6h/immersive_engineering_and_shaders/

**Comment by AzhaI114514** [comment]
1.19.2什么时候能更新

**Comment by sp614x** [comment]
Should be fixed in 1.19.2 release.
