### ISSUE TITLE
Cape Issue (Cape Not found error)

### ISSUE THREAD

**Issue by tanonmc** [sp614x/optifine#7011]
<img width="830" alt="Screen Shot 2022-07-20 at 8 17 53 AM" src="https://user-images.githubusercontent.com/76269856/179992796-98b4a0d7-5d1b-44eb-b72f-00db6c2a6a6e.png">
<img width="429" alt="Screen Shot 2022-07-20 at 8 18 02 AM" src="https://user-images.githubusercontent.com/76269856/179992824-4df7e0c2-6ee6-4b17-b76d-d9a24a3ca86e.png">
<img width="301" alt="Screen Shot 2022-07-20 at 8 18 10 AM" src="https://user-images.githubusercontent.com/76269856/179992839-705bb6fe-fde3-4cf7-825a-b96221bc19c5.png">

IGN: MoiraMerker the cape is giving not found error.

**Comment by tanonmc** [comment]
update, it's MojiraMerker lol sorry

**Comment by sp614x** [comment]
Fixed
