### ISSUE TITLE
[Suggestion] Add dithering to reduce color banding

### ISSUE THREAD

**Issue by xCuri0** [sp614x/optifine#702]
During sunrise , sunset and caves with lighting you can see some banding artifacts.
[Screenshots]
Using dithering can reduce or even completely remove color banding from the game.Dithering should available as an option in the optifine menu and the user should be able to configure the type of dithering.

This maybe be useful http://www.anisopteragames.com/how-to-fix-color-banding-with-dithering/

IGN : Curi0

**Comment by sp614x** [comment]
The banding around the sun is visible because the sun texture is low-resolution. The banding in caves with lighting is visible because the lightmap is low resolution. You can replace both with high-resolution textures to fix the banding.

**Comment by xCuri0** [comment]
@sp614x I mean this
![banding o_o](https://user-images.githubusercontent.com/29529557/27288691-1521e706-5525-11e7-8208-1f7389d04cde.png)

You can see it better if you ```/time set 23000``` in game and watch the banding :P

**Comment by sp614x** [comment]
I don't see any banding in the circled region.
Checked with GIMP, the color is absolutely smoot (61,74,109) to (64,75,108).
The problem may be with your monitor.

**Comment by xCuri0** [comment]
@sp614x maybe your monitor can show smooth colors without banding but mine and many others can't

**Comment by GreyAsteroid** [comment]
@sp614x  Nah there's banding, check it out, 
![27288691-1521e706-5525-11e7-8208-1f7389d04cde 1](https://user-images.githubusercontent.com/4615298/27314436-87188928-5539-11e7-92e0-01adab4f5c7d.png)
Here's the same screenshot with a bit more color saturation. You can see the corner of the cube near the bottom left.
It's a lot more noticeable actually seeing it happen compared to a static image.

**Comment by xCuri0** [comment]
@GreyAsteroid yep you can see it very well when actually playing the game.

If it matters my GPU is Radeon HD 7640G drivers are Mesa 17.3 and Linux 4.10

**Comment by sp614x** [comment]
The banding is visible on sunset/sunrise and is caused by not enough color precision. 
Currently the dithering can only be added with a custom shader pack (not post-processing).

**Comment by sp614x** [comment]
A custom shader is going outside of the OptiFine scope.
It is possible to make a shader pack which adds sky dithering.

**Comment by SuicSoft** [comment]
@xCuri0 I think the cave banding is also caused by this because it looks very similar to https://stackoverflow.com/questions/16005952/opengl-gradient-banding-artifacts

**Comment by sp614x** [comment]
Vanilla and OptiFine do not use any shaders by default (compatibility with older hardware).
Vanilla has some optional post-processing shaders which OptiFine uses to implement FXAA. The post-processing shaders can't implement the dithering as the color information is already lost.
Implementing dithering without shaders is not possible.

**Comment by xCuri0** [comment]
@sp614x It probably is possible but hard (and laggy) to implement it without shaders.

Also I don't think everyone uses potatoes (old hardware) these days so maybe you should add it as an option and say "Hardware support for shaders is required for dithering". If you can't do that maybe you could write a post processing shader that interpolates the missing color information and then apply the dithering (like FXAA)

What is the minumum OpenGL version required for Minecraft / OptiFine ?

**Comment by xCuri0** [comment]
@sp614x ?

**Comment by sp614x** [comment]
Dithering can't be implemented without shaders. 
OpenGL has a dithering functionality when rendering to low dynamic range displays (256 and 16k colors), but it is not active on true color (32bit) displays.

**Comment by xCuri0** [comment]
@sp614x Will interpolating the missing color information and then applying the dithering in a post processing shader work ?

If that won't work what about a custom shader pack ?

**Comment by sp614x** [comment]
Interpolating the color means to apply a slight blur filter. It will make the screen blurry because the post-processing shader does not know which pixels are sky and which are blocks. The effect will be similar to FXAA and the transitions will still be there, their edge will be a little bit blurred.

Creating a custom shader pack with dithering should be easy. It could fix both block and sky gradients. However this goes outside of the OptiFine's scope.

**Comment by xCuri0** [comment]
@sp614x thx do you know a guide for writing optifine shaderpacks from scratch ?

**Comment by sp614x** [comment]
You could look at an existing shaderpack and see how it works, a bit GLSL knowledge is required. 
Sildur's [Basic Shaders](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1291396-1-6-4-1-12-sildurs-shaders-pc-mac-intel-vibrant) are simple and easy to understand.
For the sky you should use "gbuffers_skybasic.vsh" and "gbuffers_skybasic.fsh". The first one is a vertex shader, the second one is a fragment shader.

Reference:
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.txt
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.properties
