### ISSUE TITLE
Fence Crash Issue

### ISSUE THREAD

**Issue by MarioDiamondYT** [sp614x/optifine#7024]
## Description of Issue
Mining a fence causes the game to crash and sometimes make me have an invalid session

## Steps to Reproduce
Mining a fence or a group randomly crashes minecraft

## OptiFine Version
OptiFine HD U H9 pre3

## Installation Method
Dropped it into my mods folder

## Fabric/Forge Version
forge-1.19-41.0.110

## Other Installed Mods
Journey map and JEI (Note: Disabled them and crash issue still applies

**Comment by sp614x** [comment]
Fixed, coming in next preview.
