### ISSUE TITLE
[sp614x/Optifine] Some textures appear invisible

### ISSUE THREAD

**Issue by CursedDitto** [sp614x/optifine#7025]
## Description of Issue
Texture for vines,sculk veins and fire are missing

## Steps to Reproduce
Self explanitory
Image for proof:
![2022-07-24_12 12 34](https://user-images.githubusercontent.com/105383054/180644707-74392266-3d0b-456e-85f7-a8f00eb7dd43.png)

![2022-07-24_12 12 50](https://user-images.githubusercontent.com/105383054/180644711-764986ce-fc22-4777-88ba-de7d441045c4.png)

## OptiFine Version
Optifine: preview_OptiFine_1.19_HD_U_H9_pre3

## Installation Method
Dragged into MultiMC's mod folder

## Fabric/Forge Version
41.0.103

## Other Installed Mods
Biomes O' Plenty(17.0.0.143)
Dungeon Crawl(2.3.11)
Terrablender(2.0.0.120)

## Log Files/Crash Reports
no crashes,just missing textures

## F3 Debug Screenshot
![2022-07-24_12 35 07](https://user-images.githubusercontent.com/105383054/180645069-e80ebbe7-8e24-48c2-8ab2-f6daba30b48a.png)

## Prior Testing
idk I didn’t 

## Additional Information
no

**Comment by KaiAF** [comment]
It appears that many other blocks are invisible. 

- fire
- soul_fire
- glow_lichen
- vine
- brewing_stand
- chorus_plant
- bamboo
- skulk_vine

**Comment by sp614x** [comment]
Fixed, coming in next preview.
