### ISSUE TITLE
Crash when mining vines. Vines appear invisible.

### ISSUE THREAD

**Issue by METEOROW** [sp614x/optifine#7026]
## Description of Issue
All vine blocks appear invisible, if mined the game crashes. Doesn't matter if natural or command generated, it still happens.

## Steps to Reproduce
Find a vine and left click it.
## OptiFine Version
OptiFine_1.19_HD_U_H9_pre3

## Installation Method
Dropped JAR into mods folder.

## Fabric/Forge Version
forge-1.19-41.0.100

## Other Installed Mods
**(All removed from mods folder and still happens.)** JEI, Xaero's minimap, SophisticatedBackpacks, SophisticatedCore, Waypoints, balm.

## Log Files/Crash Reports
**Crash report:** https://pastebin.com/ZTMzrRs9
**Log:** https://pastebin.com/dGy4UXEF

## Prior Testing
- Does this happen without other mods installed? 
  Yes.
- Does this happen without any mods at all?
   No.
- Does this happen in OptiFine standalone?
   No.
- Does this happen in Vanilla without OptiFine?
   No.

**Comment by KaiAF** [comment]
Seems to be related to #7025
