### ISSUE TITLE
[BUG] Fast Math Not Removed

### ISSUE THREAD

**Issue by ViaBackwards** [sp614x/optifine#7027]
## Description of Issue
The changelog for 1.19_HD_U_H9 states:
 - removed fast math due to multiple movement issues (#5578)

but when I launch the game, fastmath can still be found under the performance tab: https://i.imgur.com/MHF3Q77.png

## Steps to Reproduce
ESC -> Options -> Video settings -> Performance... -> Fast math button present

## OptiFine Version
1.19_HD_U_H9

## Installation Method
Downloaded directly from site

**Comment by modern158** [comment]
bump

**Comment by LewUwU** [comment]
bump

**Comment by DuoClip** [comment]
I didn't read the changelog at the time of your writing but at the moment that statement is not present, I suggest closing the issue or changing it to a request rather than a bug.

**Comment by KaiAF** [comment]
Fast math was never removed and was never mentioned in any changelog that it was removed.
