### ISSUE TITLE
[Crash] Crash on world load

### ISSUE THREAD

**Issue by Catomax262** [sp614x/optifine#7031]
## Description of Issue
It just crashes when i load ANY world.

## Steps to Reproduce
1. Launch the game.
2. Wait for it to load...
3. Load any world.
4. Crash!

## OptiFine Version
Optifine_1.18.2_HD_U_H6

## Installation Method
JAR file into mods folder.

## Fabric/Forge Version
Forge 40.1.60

## OptiFabric Version
n/a

## Other Installed Mods
https://pastebin.com/dUWC64nm

## Log Files/Crash Reports
https://crashy.net/YZRhQ4byLtrsUAasKPMN

## F3 Debug Screenshot
n/a

## Prior Testing
It doesn't happen without OF.
It only crashes when i load a world with this installed.

## Additional Information
n/a

**Comment by nirzh** [comment]
same with 1.18.2-OptiFine_HD_U_H7

**Comment by labradoe** [comment]
Not the latest version of OF, but most likely the same issue. See #7009.

**Comment by Catomax262** [comment]
Was it fixed tho?

**Comment by labradoe** [comment]
> Was it fixed tho?

No. H7 (the latest OF for 1.18.2) still crashes upon world load with a ticking error. Hopefully the author can fix this issue.

**Comment by sp614x** [comment]
Fixed in latest preview.

**Comment by Catomax262** [comment]
Which one? HD U9? Or is it for 1.19?
