### ISSUE TITLE
[CEM] Warden loses special effects when using CEM

### ISSUE THREAD

**Issue by RyanCR03** [sp614x/optifine#7033]
## Description of Issue
When using a cem model for the warden, it loses it's heartbeat and emissive effects.

## Steps to Reproduce
1. Create Custom Warden Model
2. Notice lack of effects

## OptiFine Version
HD_H9_pre4

## Installation Method
installer

## Additional Files
![Dead Warden](https://user-images.githubusercontent.com/32957560/181580962-33fa3400-63bf-4a9c-b541-f8641f8e8565.png)

**Comment by FFreshLX** [comment]
Was just going to report this myself, so here's my addition:
Warden's extra texture overlays (bioluminescent, heart, pulsating spots) don't work properly with CEM.

- Warden has no overlays for parts that are present in the model. Parts that are missing from the model do have overlays.
https://imgur.com/rltMzL8
_Torso part present. Missing heart (I've made the overlays red so they're easier to see)_

- Animations like this work fine
https://imgur.com/uum8ABv

- Animations with references seem to multiply the overlays. The pulsating spots move more than the bioluminescent and heart.
https://imgur.com/dRUDcIn
https://imgur.com/tGgRDW3 < video

**Comment by sp614x** [comment]
Fixed in I6_pre2 for 1.20.1
