### ISSUE TITLE
[CIT] CIT doesn't seem to work on newer versions of Optifine

### ISSUE THREAD

**Issue by Spittys** [sp614x/optifine#7035]
Not sure about this, but CIT doesn't seem to work atm. I've turned on custom items and everything. I'm using OptiFine 1.19 HD U H9 pre4 with Forge 41.1.0 I'm using xali's enchanted books and it doesn't work, several people have also commented on that texture pack referencing the issue. Custom borders from the Legendary tooltips mod also doesn't work, but that could probably me my problem. Thanks!

**Comment by sp614x** [comment]
Fixed, coming in next preview.

**Comment by Yekul10** [comment]
It seems that it doesn't work using OptiFine 1.19.2 HD U H9.
