### ISSUE TITLE
Optifine crashes with the new forge version(42.0.1)

### ISSUE THREAD

**Issue by amandexspeed** [sp614x/optifine#7036]
## Description of Issue
When I try to load forge+optifine it crashes and it's says that it's a personalized Java runtime setting that is causing the problem. But I don't have any mods that changes these settings and I didn't changed anything.
When I tried to use a older version of forge for 1.19, optifine runs, but all my other mods crashes because of the older version of java.  

## Steps to Reproduce
1. What do you do to find this bug?
 Just open minecraft.

## OptiFine Version
HD U H9 pre4 and HD U H8

## Installation Method
I downloaded the jar for optifine, ran it and drop the file in mods folder

## Fabric/Forge Version
forge 42.0.1

## Other Installed Mods
https://pastebin.com/5qMNGYQC

## Log Files/Crash Reports
It doesn't gives me crash report files. but if the latest.log file helps...
[latest.log](https://github.com/sp614x/optifine/files/9224168/latest.log)

## F3 Debug Screenshot
![image](https://user-images.githubusercontent.com/60000299/181866957-271ed3c9-b7d1-4eeb-8650-c4af84da9d96.png)

## Prior Testing

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   - Only OptiFine and Forge -> Yes

- Does this happen without any mods at all?
   - Only Forge/Fabric by itself. -> No
- Does this happen in OptiFine standalone? ->No
- Does this happen in Vanilla without OptiFine? ->no
- Have you tried using a binary search to find which mods cause this issue?->Yes(I removed all other mods and it didn't solved)
  
   - Does the issue still happen with only the remaining mods installed?
      - Forge/Fabric and remaining mods, without OptiFine --> No

**Comment by fayer3** [comment]
this should be fixed with Optifine 1.19.1 HD U H9 pre1?

**Comment by sp614x** [comment]
Should be fixed in H9 release.
