### ISSUE TITLE
optfine render blocks glitch

### ISSUE THREAD

**Issue by MofoWinsky** [sp614x/optifine#704]
When I load into the optifine profile the installer creates it loads all my blocks in a colorful glitchy way ive tried everything and i came to the conclusion its optifine because i switch profiles and it works fine, thank you , please fix this asap.

**Comment by sp614x** [comment]
More details needed:
- OptiFine version?
- Forge installed, version?
- list of other mods installed?
- shaders active?

**Comment by sp614x** [comment]
This should be fixed in latest versions.
