### ISSUE TITLE
Minecraft crash everytime I launch the game

### ISSUE THREAD

**Issue by huyhhuy1410** [sp614x/optifine#7040]
## Description of Issue
This not happen when I played the 1.18.2 version. Only with 1.19
## Steps to Reproduce
1. Start the game with minecraft launcher.
2. Crash the game with the crash log.
## OptiFine Version
OptiFine_1.19_HD_U_H9

## Installation Method
Just drop the optifine into the mods folder.

## Fabric/Forge Version
Forge 1.19-41.1.0

## Other Installed Mods
https://pastebin.com/bdaeWB5E

## Log Files/Crash Reports
https://pastebin.com/ZcMeSidc

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   - No

**Comment by fayer3** [comment]
Looks like chunk animator needs to update their optifine mixin.

**Comment by huyhhuy1410** [comment]
> Looks like chunk animator needs to update their optifine mixin.

I tried to remove Chunk Animation mod and updated all others mods then i could enter the game, but it crash as soon as i connect to a server.
Here a crash report: https://pastebin.com/rbCkwxJW

**Comment by fayer3** [comment]
looks to be caused by shoulder surfing now:
```
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Mixin shouldersurfing.mixins.json:MixinShadersRender contains non-private static method updateActiveRenderInfo(Lnet/minecraft/client/Camera;Lnet/minecraft/client/Minecraft;F)V [ -> MAIN Applicator Phase -> shouldersurfing.mixins.json:MixinShadersRender -> Apply Methods -> (Lnet/minecraft/client/Camera;Lnet/minecraft/client/Minecraft;F)V:handler$zzc000$updateActiveRenderInfo]
```

**Comment by mindforger** [comment]
and maybe iceberg

**Comment by huyhhuy1410** [comment]
> looks to be caused by shoulder surfing now:
> 
> ```
> Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Mixin shouldersurfing.mixins.json:MixinShadersRender contains non-private static method updateActiveRenderInfo(Lnet/minecraft/client/Camera;Lnet/minecraft/client/Minecraft;F)V [ -> MAIN Applicator Phase -> shouldersurfing.mixins.json:MixinShadersRender -> Apply Methods -> (Lnet/minecraft/client/Camera;Lnet/minecraft/client/Minecraft;F)V:handler$zzc000$updateActiveRenderInfo]
> ```

Yes, now it works. Thank for your help!
