### ISSUE TITLE
Optifine move cape Server Error

### ISSUE THREAD

**Issue by yoogus** [sp614x/optifine#7049]
hello, I changed my nickname in the game and am trying to transfer the cloak to my new nickname
Old nickname - IAMNOOBXDDDDDD
New nickname - yoogus_
And when I try to change the nickname on the raincoat, Server Error will come out to me 
 
please help me if you need to provide information about the ownership of the cloak, then I am ready

P.S I used to have an account with the nickname Yoogus_, but they changed the nickname there a long time ago and I don't understand what the problem is

1. ![image](https://user-images.githubusercontent.com/110523242/182599872-73f23ac3-11ba-4350-811a-85c8c00ea9b1.png)
2. ![image](https://user-images.githubusercontent.com/110523242/182599993-1c18e8fd-2adc-4baa-9d95-9bf660780273.png)
3. ![image](https://user-images.githubusercontent.com/110523242/182600037-df527e88-a159-4aeb-aef1-8e0805c472e7.png)

**Comment by KaiAF** [comment]
you emailed support, I replied to it. Closing this.
