### ISSUE TITLE
Dynamic lighting lag

### ISSUE THREAD

**Issue by Greenlazer15** [sp614x/optifine#705]
When turning on dynamic lighting, my game imminently drops from 65 fps to about 30, this only happens when a torch is held or any other dynamic light is moved around on screen. i have a pretty beefy PC and this never happened to me before the latest full release of optifine. (i run a heavy shader usually so 65 fps is the norm) (CPU: 8x Intel(R) Core(TM) i7-6820HK CPU @ 2.70GHz) this is with VSynce on, so the fps doesn't fluctuate either.

**Comment by xCuri0** [comment]
@Greenlazer15 I have this same problem but I think it might be my laptop and not a bug. Also 65 fps is low  for a beefy PC (i get 70 - 100 in local world and i don't think my pc is beefy) so it might be another problem. What are your PC specs ?

**Comment by Greenlazer15** [comment]
@xCuri0 i forgot to mention that i run a very heavy shader at all times, even thyough the bug still happens without it, just less noticable.

**Comment by sp614x** [comment]
Dynamic Lights have to constantly update the nearby chunks when the player holds a handheld light. Usually this causes minimal FPS drop. In yor case the chunk updates may be too slow which causes the significant FPS drop.
Are there warnings/errors in the error log (game output)?

**Comment by Greenlazer15** [comment]
I do not have any mods accept optimize and the shader downloaded to it. This never used to happen but now it seems to be glitching with this update.

**Comment by Greenlazer15** [comment]
i accidentally turned off "Use VBO's" it now lags less, sorry for the inconvenience.
