### ISSUE TITLE
Custom colors is broken when using Optifabric with the Fabric API

### ISSUE THREAD

**Issue by jordan-trempert** [sp614x/optifine#7051]
## Steps to Reproduce
1. Install optifabric, optifine, fabric api
2. use a pack with custom colors

## OptiFine Version
OptiFine_1.19_HD_U_H8

## Installation Method
Drag and drop

## Fabric/Forge Version
fabric-laoder-0.14.7-1.19

## OptiFabric Version
1.13.5

## Other Installed Mods
Xareo's Minimap
Xareo's Worldmap
Fabric API

**Comment by sp614x** [comment]
Fabric is not supported natively by OptiFine.
Please post it in the OptiFabric tracker.
