### ISSUE TITLE
[CRASH](Fixed) Can't start on MacOS Ventura

### ISSUE THREAD

**Issue by vladimirtemnikov** [sp614x/optifine#7053]
FIXED

Was using outdated BSL shaders.

## Description of Issue
Installed vanilla Minecraft and patched with OptiFine.
When the world begins to render the crash is happening.

## Steps to Reproduce
1. Get Minecraft 1.19.1
2. Patch with OptiFine
3. Start game
4. Select world
5. Wait

## OptiFine Version
OptiFine HD U H9 pre1

## Installation Method
Standalone installer

## Log Files/Crash Reports
[hs_err_pid48051.log](https://github.com/sp614x/optifine/files/9259847/hs_err_pid48051.log)

## Prior Testing
- Does this happen in Vanilla without OptiFine?
- No

**Comment by fayer3** [comment]
close the issue, if you fixed it
