### ISSUE TITLE
i think optifine should an option to increase the gamma in game

### ISSUE THREAD

**Issue by mj34261** [sp614x/optifine#7058]
i think optifine should have a feature that allows the player to increase the gamma level in game, since you can no longer modify the gamma level  form the game files, it would be neat if its a setting in the game

**Comment by ZenithRogue** [comment]
you can change your gamma with shaders

**Comment by mj34261** [comment]
> you can change your gamma with shi dont use shaders

**Comment by mj34261** [comment]
> you can change your gamma with shaders

i dont use shaders
