### ISSUE TITLE
vanilla tweaks resource reload failed

### ISSUE THREAD

**Issue by Naofumisa** [sp614x/optifine#7061]
## Description of Issue
https://youtu.be/-0wwyuLTvTg

## OptiFine Version
1.18.1

## Installation Method
included standalone installer

## Fabric/Forge Version
1.18.1

## Other Installed Mods
xareos minimap

## Log Files/Crash Reports
https://pastebin.com/kBKnwr7w

## F3 Debug Screenshot
(https://user-images.githubusercontent.com/110975258/183877130-4c35f5a5-3827-45b6-98a5-c705bc39ba5b.png)

## Prior Testing

- Does this happen in Vanilla without OptiFine?
yes

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
yes
 
- Does this happen without any mods at all?
yes

- Does this happen in OptiFine standalone?
yes
- Does this happen in Vanilla without OptiFine?
yes
- Have you tried using a binary search to find which mods cause this issue?
no
   - Does the issue still happen with only the remaining mods installed?
   yes
      
## more
this is the resource pack that i used from vanilla tweaks resource
https://vanillatweaks.net/share/#TFKSOi

and im sorry if there's anything wrong this is my first time doing this

**Comment by fayer3** [comment]
from the error it looks like the resourcepack is made for an other minecraft version.
the resourcepack uses vanilla shaders and these are not alway compatible with different minecraft versions.

**Comment by Naofumisa** [comment]
thx
