### ISSUE TITLE
OptiFine not allowing you to hit the dragon with any melee weapon

### ISSUE THREAD

**Issue by FullMetalMaster** [sp614x/optifine#7062]
## Description of Issue
Minecraft 1.18.2
forge 40.1.57
OptiFine HD U H7

## Steps to Reproduce
hitting the dragon with any melee weapon does no damage

## Other Installed Mods
<tested with no mod and still has the issue>

## F3 Debug Screenshot
[latest.log](https://github.com/sp614x/optifine/files/9305367/latest.log)

![image](https://user-images.githubusercontent.com/52523300/184049161-d5051e3f-f614-46c1-9ddc-a6d68c10e31d.png)

## Prior Testing

<!-- If you've installed standalone:
- Does this happen in Vanilla without OptiFine?

If you've installed using Forge/Fabric:
[latest.log](https://github.com/sp614x/optifine/files/9305369/latest.log)

- Does this happen without other mods installed? yes
   - Only OptiFine and Forge yes

**Comment by FullMetalMaster** [comment]
along with this OptiFine still has an issue crashing with versions of Forge higher than this on world load so if this can't be fixed then OptiFine is useless and 1.18.2 just about ive tried everything

**Comment by fayer3** [comment]
are you sure that's not just this vanilla bug?
https://bugs.mojang.com/browse/MC-158205

**Comment by FullMetalMaster** [comment]
yes im sure running in the same environment there are no issues with Forge when dealing damage or crashing. also that is only to 1.15 this is 1.18 and again melee weapons do damage without the mod in the mods folder

**Comment by FullMetalMaster** [comment]
the issue the issue isn't even hitting it from a certain way either from the same angle I can hit it from the exact same loading it up with and with out in the same spot WithOut OptiFine a sword and an axe to damage and With OptiFine they do not there are no other mods while this bug happens as stated

**Comment by tuturox91** [comment]
Please update 1.18.2 version optifine to newer version forge. In current suppurted version of optifine and forge dragon don't get damage in melee. Video: 
https://youtu.be/Ont1rz8k5gQ

Last version what supported optifine is froge 4.1.57 but in this version dragon broken too.

**Comment by tuturox91** [comment]
Yep dragon don't get damage from melee weapons. 

Im tested on forge 4.1.50 - 5.1.57 Dragon broken in all tested wersions.
In the newer version of forge 4.1.58 optifine crash world on generation.

And im tested clear forge 4.1.73 without OptiFine and dragon get damage normal like need.

Video making in forge 4.1.50:
https://youtu.be/Ont1rz8k5gQ

**Comment by sp614x** [comment]
Should be fixed in latest preview.

**Comment by KRWCLASSIC** [comment]
the same thing happened on 1.16.5, I tested every available optifine version, playing with many forge mods on 36.2.39. maybe something on forge side (version) because I never had this issue on 1.16.5 with optifine.

**Comment by KRWCLASSIC** [comment]
yeah, on forge 36.2.35 works without any issue, weird

**Comment by TheCurano** [comment]
Same happened in the 1.16.5 with 36.2.39 (ATM 6 Modpack)

**Comment by KRWCLASSIC** [comment]
> Same happened in the 1.16.5 with 36.2.39 (ATM 6 Modpack) as addition

ig .39 is just bugged, .35 works without issue
