### ISSUE TITLE
Dragon don't get melle damage in 1.18.2 Forge 4.1.57

### ISSUE THREAD

**Issue by tuturox91** [sp614x/optifine#7063]
Dragon don't get damage from melee weapon.

Im tested on forge 4.1.54 - 4.1.57 Dragon broken in all tested wersions. 
In the newer version of forge 4.1.58 optifine crash world on generation.

And im tested clear forge 4.1.73 without OptiFine and dragon get damage normal like need.

Video making in forge 4.1.54:
https://youtu.be/Ont1rz8k5gQ

**Comment by tuturox91** [comment]
Now 1.18.2 is the more popular version, because the big mods just updated to it.

**Comment by Regnander** [comment]
#7062

**Comment by vinc3nz** [comment]
Please close this issue.

**Comment by sp614x** [comment]
Should be fixed in latest preview.
