### ISSUE TITLE
OptiFine 1.18.2 crashes with forge 40.1.73

### ISSUE THREAD

**Issue by CinderyAlpaca** [sp614x/optifine#7064]
I tried making a modpack and it crashes, i removed it and it worked fine

Error Message:
The game crashed whilst initializing game
Error: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
Exit Code: -1

**Comment by CinderyAlpaca** [comment]
Oh i also tried without any mods other than optifine and it didnt work either

**Comment by UnknownTheLad** [comment]
#7009

**Comment by DaDiGui** [comment]
same.
https://pastebin.com/GB7yEhH5

**Comment by sp614x** [comment]
Fixed in latest preview.
