### ISSUE TITLE
Light flickering issue - OptiFine 1.12 HD U C2

### ISSUE THREAD

**Issue by dar-irl** [sp614x/optifine#707]
I've noticed this issue in the Optifine build for 1.12. All blocks or entities with any kind of light shining on them will have an awful effect where the lighting doesn't stay constant and flickers the entire time. It's subtle, but noticeable enough to be an issue. It's very apparent with brightness set to Moody. I've gone through every setting in Optifine, and nothing seems to fix it.

**Comment by sp614x** [comment]
Is OptiFine installed with or without Forge?
Screenshot (video) to show the problem, F3 debug screenshot?
Shaders active? Other mods installed?

**Comment by xCuri0** [comment]
I'm also using OptiFine 1.12 HD U C2 and I don't have any lighting problems. What other mods are you using and what is your GPU / drivers ?

**Comment by dar-irl** [comment]
@sp614x I'm using OptiFine with Forge. No other mods or shaders are installed. [Here's a quick recording of the issue](https://u.teknik.io/h4ALQ.mp4), if you look closely you can see the lit blocks flicker or pulse. I found a resource pack that makes the issue more noticeable, but I can confirm that it also happens without the resource pack.

Here's a debug screenshot, too.
![2017-06-20_13 13 00](https://user-images.githubusercontent.com/18043024/27346306-c2170960-55ba-11e7-97b0-e53e2fd73193.png)

**Comment by sp614x** [comment]
Do you mean the normal torch flicker? 
http://minecraft.gamepedia.com/Beta_1.8#Gameplay_2
http://minecraft.gamepedia.com/Light#History (see the 1,8 section)

Resource packs can change the lightmap which controls the torch flicker.

**Comment by dar-irl** [comment]
@sp614x Huh, never noticed that before, that seems to be it! Thanks for the help.
