### ISSUE TITLE
[Enhancement] Reduced Debug Info with Coordinates (QoL)

### ISSUE THREAD

**Issue by Scorpion34** [sp614x/optifine#7070]
Reduced Debug Info was recently added as of 1.18 due to the amount of text on the screen being too much, however, this has also removed Coordinates upon turning the option from OFF to ON 

Java Edition of Minecraft the F3 button is your best friend to find your home, your nether portal and other useful jargon that other people actually know what it means; however, for me I use 2 things with F3; the FPS and the XYZ Coordinates now this is a very minor enhancement or at least from a idiosyncratic normie like myself, more than anything it's a quality of life enhancement.

I propose instead of OFF or ON, to Reduced Debug Info: ON (No XYZ Coordinates), Reduced Debug info: ON-XYZ (With XYZ Coordinates)

This addition would simply make it so I can travel around with F3 on with Coordinates without seeing the mess of the screen I was figuring you could simply replace the Chunk-relative for XYZ Coordinates as it seems that separated space is focused on relative position but I really know very little of programming or Mojang's TOS on modding but I do know this change would make me very happy without needing to use Fabric or Forge or data packs or anything just OptiFine-Vanilla Minecraft so again purely QoL enhancement that I would love to see added.

**Comment by sp614x** [comment]
Replaced Show FPS with customizable Quick Info, coming in next 1.20.4 preview.
