### ISSUE TITLE
Whater bug

### ISSUE THREAD

**Issue by TrestoXD** [sp614x/optifine#7071]
## Description of Issue
the water disappears from time to time

## Steps to Reproduce
1. move
2. open new chunks or stand still

## OptiFine Version
Optifine HD H9_pre1 Ultra

## Installation Method
Jar file into the mod flie

## Fabric/Forge Version
Forge 43.0.2

## Other Installed Mods
Farmer's delight, Simple voice chat, Repurpused Structures, Epic Knights armor and weapons, Better animal plus Corail tombstone, Singpost, World edit, mr catfish furniture mod, architectury, Creative core,Jei, Terralith, Guns whitout roses, pehkui, Domum ornamentu, aquaculture2,  player revive, emotecraft, Camera mod and Security craft.

If you've installed using Forge/Fabric:
- Does this happen without other mods installed?  Yes
   - Only OptiFine and Forge no
   - Only OptiFine, OptiFabric, and Fabric no
- Does this happen without any mods at all? Yes
   - Only Forge/Fabric by itself. No
- Does this happen in OptiFine standalone? Yes
- Does this happen in Vanilla without OptiFine? No
- Have you tried using a binary search to find which mods cause this issue? No
   - To find conflicting mods, split your mods into 2 groups (not including OptiFine/OptiFabric, obviously). Remove one group, and test in-game. Keep the group that has the problem, and repeat until no more mods can be removed without the issue disappearing.
   - Does the issue still happen with only the remaining mods installed? No
      - Forge/Fabric and remaining mods, without OptiFine -->

## Additional Information
![2022-08-18_11 56 26_4](https://user-images.githubusercontent.com/111501558/185373455-4bf459f5-3940-40e2-ac96-0915d43d3196.png)
![2022-08-18_11 56 26_5](https://user-images.githubusercontent.com/111501558/185373465-46ca49d6-8098-40c8-b1f8-928b376dea73.png)

**Comment by UntouchedOdin0** [comment]
Whater lol

**Comment by sp614x** [comment]
Most probably a conflict with one of the mods.
- split the mods in two groups
- test one group and continue with the group that has the problem
- repeat until only one mod is left
