### ISSUE TITLE
You must download and start minecraft 1.19 once in the official launcher

### ISSUE THREAD

**Issue by nmdgithub** [sp614x/optifine#7073]
## Steps to Reproduce
1. What do you do...
2. ...to find this bug?

## Additional Information

i just cant figure out how to install optifine because of this prompt that appears each time i try to install

**Comment by KaiAF** [comment]
Open the Minecraft launcher, create a new instance for the Minecraft version "1.19" then launch it once.

**Comment by nmdgithub** [comment]
sorry im a bit confused

**Comment by nmdgithub** [comment]
i dont have that much experience with this

**Comment by fayer3** [comment]
![grafik](https://user-images.githubusercontent.com/8282299/185524428-ceb0184a-6c1f-4422-b8ad-fb834690507f.png)
