### ISSUE TITLE
optifine install issue

### ISSUE THREAD

**Issue by nmdgithub** [sp614x/optifine#7074]
Description of Issue .You must download and start minecraft 1.19 once in the official launcher
OptiFine Version 1.19.1
Installation Method. double click

i just cant figure out how to install optifine because of this prompt that appears each time i try to install

Open the Minecraft launcher, create a new instance for the Minecraft version "1.19" then launch it once. is what ive been told but im having trouble understanding what a new instance is and more issues apper
<img width="614" alt="Screen Shot 2022-08-18 at 6 28 07 PM" src="https://user-images.githubusercontent.com/83084006/185524341-8b5db06e-8679-4e41-9c08-18ad8d39cdf1.png">

**Comment by KaiAF** [comment]
Go to the instance tab
![image](https://user-images.githubusercontent.com/60985521/185524533-5f2928e7-410a-4429-b0d1-209f19893382.png)
Press new Installation
![image](https://user-images.githubusercontent.com/60985521/185524545-a64861c8-0c84-48a7-a3fd-a2bc4760b7ea.png)
Search "1.19" then scroll down to "release 1.19"
![image](https://user-images.githubusercontent.com/60985521/185524636-51ca0a18-e7c5-4ef9-aa9f-fa61afbf1d14.png)
Create
![image](https://user-images.githubusercontent.com/60985521/185524659-e6ddcc45-cc76-451f-847e-fe943bc87082.png)
Play
![image](https://user-images.githubusercontent.com/60985521/185524669-68927707-c7aa-4fb5-a3e4-a3551862b125.png)


Then, close the game. And then the OptiFine installer will work. You said that the OptiFine version you have installed is "1.19.1", which it's not. It is for the version 1.19. You would need to install the preview version for 1.19.1 on https://optifine.net. Also, there is no optifine version for the latest release 1.19.2

**Comment by nmdgithub** [comment]
THANK YOU SO SO SO MUCH
Norma

Norma Mendoza-Denton, Ph.D.
Professor, Department of Anthropology
University of California at Los Angeles
Los Angeles, CA 90024
www.norma-mendoza-denton.com/

Preferred pronouns: (she/ they)

*Please forgive any errors possibly originating in autocorrect and speech
recognition.*

Acknowledgment:



UCLA American Indian Studies acknowledges the Tongva peoples as the
traditional land caretakers of Tovaangar (Los Angeles basin, So. Channel
Islands) and are grateful to have the opportunity to work for the
taraaxatom (indigenous peoples) in this place. As a land grant institution,
we pay our respects to Honuukvetam (Ancestors), ‘Ahiihirom (Elders), and
'eyoohiinkem (our relatives/relations) past, present and emerging.



Personal reflection:



I am a descendant of the Ópata people, Uto-Aztecans ancestrally of Sonora
and Chihuahua as well as Arizona: in those lands in which we were separated
by a border,  we are neighbors of the Yaqui, the Pima and the Tohono
O’odham. I personally mourn the loss of my ancestral language and share
with the Tongva a history of colonization and dispossession, as well as the
complex circumstances of needing to find one’s way in the current context.

 *******************************************
