### ISSUE TITLE
I bought a cover but it says that there were no donations in my email and it still arrived on my card statement

### ISSUE THREAD

**Issue by xxSynapse** [sp614x/optifine#7078]
[](url)recently I tried to make a purchase for the optfine cover, the purchase supposedly went wrong, so I gave up on buying, however I went to see my credit card bill and it was charged, right, I went to see if I received the product in my account and simply it wasn't in my account, and on top of that the invoice says it was approved, I paid for something I won't use????

![image](https://user-images.githubusercontent.com/111712749/185816095-de6b3fd9-0a11-4e71-b167-15b2cc973486.png)
![da31a418-c533-43af-9013-d2fe1c2c1265](https://user-images.githubusercontent.com/111712749/185816334-a21ddebe-57a4-47ef-8d44-a098fd6fcea5.jpg)

**Comment by sp614x** [comment]
Please contact support@optifine.net with details.

**Comment by xxSynapse** [comment]
thank you sp614x
