### ISSUE TITLE
Resourcepack loading

### ISSUE THREAD

**Issue by Zwangi** [sp614x/optifine#708]
Resourcepacks with names that contain special charakters will kicked out after starting/restarting the game.
While playing the resourcepack will stay loaded. this bug will only appear in zip files. extracted resourcepacks in folders 📁will load fine after restarting the game.

Example name (will not load):"§aA colorful §eResourcepack.zip"
Example name (will load):📁"§aA colorful §eResourcepack"
Example name (will load):"A not so colorful Resourcepack.zip"

Installed with forge and lightloader
(issue appears still without these two)

**Comment by sp614x** [comment]
This is a vanilla 1.12 problem: https://bugs.mojang.com/browse/MC-117449

**Comment by sp614x** [comment]
Updated preview C3 for 1.12:
- fixed options to be saved in UTF-8 (MC-117449)
