### ISSUE TITLE
[1.8.9] Random mouse acceleration only inside Minecraft

### ISSUE THREAD

**Issue by Pearoo-XD** [sp614x/optifine#7080]
## Description of Issue
So I've been playing with Minecraft for quite a long time, around 6 years to be exact, and I've had this issue only once. The problem is that whenever I'm using any Optifine related game version, regardless of whether it's the official Minecraft launcher or a modded launcher such as Lunar or Feather, my mouse randomly accelerates even with mouse pointer precision disabled. My mouse is specifically for gaming and the polling rate is at 1000 Hz. When I change it to 500Hz, it becomes a bit more usable, but then it changes in other games too, which I don't want it to.

## Steps to Reproduce
1. Launch minecraft using Optifine 1.8.9 HD M5 and just look around.

## OptiFine Version
1.8.9 HD M5

## Installation Method
I installed Optifine with Skyclient.

## Fabric/Forge Version
Forge 11.15.1.2318

## Other Installed Mods
BazaarNotifier-1.4.12
betterchat-1.5
CrashPatch-1.4.0
Danker.s.Skyblock.Mod-1.8.7-hotfix1
dungeonsguide-3.7.8
Hypixel Autocomplete-1.1 (1.8.9)
Hytils-Reborn-1.5.0
LevelHead-8.2.2 (1.8.9)
NotEnoughUpdates-2.1-Watching-3
Optibye-1.0.0-dep
OptiFine_1.8.9_HD_U_M5
Patcher-1.8.3 (1.8.9)
Scrollable Tooltips-1.4 (1.8.9)
SkyblockAddons-1.7.0-for-MC-1.8.9
SkyblockClient-Updater-1.3.1
SkyClientCosmetics-1.1.9
Skytils-1.2.6

## F3 Debug Screenshot
![image](https://user-images.githubusercontent.com/63553775/186865787-be1c5247-2d37-4cf5-ad33-2fd7437ab9fd.png)

## Prior Testing
- Does this happen in Vanilla without OptiFine?
- No.

**Comment by ZenIsBestWolf** [comment]
This is not an OptiFine bug, this is a vanilla issue.
