### ISSUE TITLE
[Feature] Can you make load-times longer?

### ISSUE THREAD

**Issue by KyrDerz** [sp614x/optifine#7095]
## Description of Issue
I don't think I am satisfied with the half-hour initial load time, let's double it!
Nay, triple it!
That will show Sodium/Rubidium and other pretentious-metal-name lovers.

## Steps to Reproduce
a. Start the game with OptiFine
b. Change ResourcePacks
c. Change Shaders
d. All of the above

## OptiFine Version
OptiFine HD U H9 pre1

## Installation Method
mods/preview_OptiFine_1.18.2_HD_U_H9_pre1.jar

## Fabric/Forge Version
1.18.2 / 40.1.73

## Other Installed Mods
https://pastebin.com/phjLtFd3

## Additional Information
[OptiFine] BetterGrass: Parsing default configuration optifine/bettergrass.properties
[Worker-Main-18/INFO]: [OptiFine] Mipmap levels: 4

Between these two lines, I manage to get married, have kids, see them graduate, get my pension and finally retire.
Thank you for all the time you guys gave me to live my life to it's fullest.

**Comment by KaiAF** [comment]
No
