### ISSUE TITLE
Changing Shaders Causes...

### ISSUE THREAD

**Issue by kenijey** [sp614x/optifine#711]
![222](https://user-images.githubusercontent.com/24831406/27350513-3949d416-5603-11e7-9d9c-2694eed6a534.png)
used preview-OptiFine_1.12_HD_U_C3_pre.jar
and forge 2337
i just changed my shader option (BEST.zip is sildurs, LOW.zip is seus) 
to internal.(default)
and it also happens if i change to OFF.

**Comment by kenijey** [comment]
and, it is happening since 1.11.2 and i think 1.10 too

**Comment by kenijey** [comment]
aaaaand ah, it also causes my all resource packs being disabled(deactivated)

**Comment by sp614x** [comment]
Error log, game output?

**Comment by kenijey** [comment]
hey ah, it's not happening anymore with the latest preview of C3.
