### ISSUE TITLE
[Bug] On main menu and F3 in 1.12.2, Optifine labels itself as: "Optifine Optifine_1.12.2_...."

### ISSUE THREAD

**Issue by CozyMeli-gitv2** [sp614x/optifine#7111]
## Description of Issue
Optifine mod displays its name on the main menu bottom left and the F3 menu incorrectly, having the word Optifine repeat twice, for a message reading Optifine Optifine_1.12.2_...insert specific 1.12.2 version name, as it applies to all of them.

Unaware if this effects other versions. However, it's a text mistake that would be sick to see fixed, because as it's on F3 and main menu all day, it would be nice to have it corrected.

## Steps to Reproduce
1. Launch game
2. Look at the bottom left of main menu
3. See issue

## OptiFine Version
Applies to every single Optifine version under 1.12.2, including the latest stable and preview build. 

## Installation Method
Installed Optifie via the website, and added the jar to my forge mod folder.

## Fabric/Forge Version
Forge version is 1.12.2 - 14.23.5.2860, the latest version available.

## Log Files/Crash Reports
There is no relevant logs to display this issue.

## F3 Debug Screenshot
https://imgur.com/a/w7rxTtD 

## Prior Testing
- Does this happen in Vanilla without OptiFine?
As this is an Optifine labeling issue, the answer is no.

## Additional Information
A small issue, but it would be lovely to see fixed! 

And just incase, even though F3 shows the duplicate Optifine naming, here is an attachment of the misprint on the main menu bottom left. https://imgur.com/a/RDesmrx

Thanks.

**Comment by CozyMeli-gitv2** [comment]
Correction. This does not show on F3. My bad. Please refer to https://imgur.com/a/RDesmrx to see the duplicate naming on main menu.

**Comment by ZenIsBestWolf** [comment]
its ok, we all make mistakes

**Comment by CozyMeli-gitv2** [comment]
"Closed this as not planned"
What the hell? You don't plan to fix a typo? Why is this not planned? This is such a small thing, it would take a second to do for someone to fix this.

**Comment by CozyMeli-gitv2** [comment]
You could have at least flared it as non priority. But not planned? Cmon man. I'm a little frustrated at that.

**Comment by IMS212** [comment]
It’s 1.12…

**Comment by CozyMeli-gitv2** [comment]
> It’s 1.12…
FYI Optifine updates older versions with popularity. 1.8.9, and 1.12.2. Both got an update sometime 2021.

**Comment by ZenIsBestWolf** [comment]
I misread your comment as if you had claimed the issue was non-existent in the first place.

I'm not the developer, I'm a repo maintainer. I'll reopen this as low priority.

**Comment by ZenIsBestWolf** [comment]
Upon further inspection this is intended behavior. Said OptiFine label is from Forge, not us (which is why it's incorrectly typed as "Optifine" and not "OptiFine"), and the version string is intended to include OptiFine.

**Comment by CozyMeli-gitv2** [comment]
Gotcha, so it's a forge sided issue? Lmfao, shoutout forge for not updating old popular versions, this won't get fixed for sure. Thanks for the help though.

**Comment by ZenIsBestWolf** [comment]
its not even an issue this is just a weird nitpick. this is quite literally intended behavior. dont go bother the forge devs with this please.
