### ISSUE TITLE
Swamp water color not changing

### ISSUE THREAD

**Issue by pasi123567** [sp614x/optifine#712]
Title says everything, trees, grass is changing but water stays dark
Version: OptiFine 1.12 HD U C3 pre

**Comment by sp614x** [comment]
F3 screensht of swamp?

**Comment by pasi123567** [comment]
[http://i.imgur.com/4BGOc3w.jpg](Swamp)

**Comment by pasi123567** [comment]
http://i.imgur.com/4BGOc3w.jpg

**Comment by sp614x** [comment]
Video Settings -> Quality -> Swamp Colors -> ON ???

**Comment by pasi123567** [comment]
Video Settings -> Quality -> Swamp Colors -> OFF
I want them off
But water is still dark

**Comment by sp614x** [comment]
Updated preview C3 for 1.12
- fixed swamp water color when Swamp Colors is OFF
