### ISSUE TITLE
0 FPS quand je joue à MC

### ISSUE THREAD

**Issue by lightnight95** [sp614x/optifine#713]
Bonjour, depuis que je joue a minecraft 1.11.2 avec OptiFine 1.11.2 HD U B7 et les versions d'apres j'ai 0 FPS en jeu. Je suis pas trés fort en informatique alors si vous pouvez me guider ca serait cool. Merci.

J'ai un acer aspire, i5, nvidia geforce 710m

Hello, since I play minecraft 1.11.2 with OptiFine 1.11.2 HD U B7 and the versions after I have 0 FPS in game. I am not very strong in computing so if you can guide me it would be cool. Thank you.

I have an acer aspire, i5, nvidia geforce 710m

**Comment by Builderb0y** [comment]
Smooth FPS? #583

**Comment by lightnight95** [comment]
yes i'm put smooth fps

**Comment by sp614x** [comment]
You should turn "Smooth FPS" off and try again.

**Comment by lightnight95** [comment]
nice thank you
