### ISSUE TITLE
OptiFine has made every texture in the game show up on every block!

### ISSUE THREAD

**Issue by StupidRepo** [sp614x/optifine#7143]
![image](https://user-images.githubusercontent.com/69256931/196899425-df95aee8-014a-43ef-a2df-b72bc4f2e920.png)
What the hell! I have no shaders on and I am using an AMD GPU (maybe it requires additional setup).

What's happening?

**Comment by ZenIsBestWolf** [comment]
Please re-create with a proper bug report.
And I mean **please**, I was previously unaware it was Anisotropic Filtering causing this, it's nice to have a temporary workaround, but we need details on your machine (F3 screenshots would be nice) alongside a proper bug report.

This is legitimately a bug, please just fill out the provided template.
