### ISSUE TITLE
[1.19.2/Visual] Held Item Models Have Gaps in Them

### ISSUE THREAD

**Issue by CaveMiner1215** [sp614x/optifine#7146]
## Description of Issue
The models of held items (anything with only a 2-D texture, such as a diamond sword) appears to have gaps in them along the edges.
![DiamondSwordBoundaryGaps](https://user-images.githubusercontent.com/30667792/197419471-ef663828-b49b-4dec-bfc5-c7af0afcd2b4.png)

## Steps to Reproduce
1. Load a world with OptiFine installed.
2. Place an item in your hotbar, and hold it.
3. Look closely at the edges of the item model against a contrasting background, and you should see slim gaps.

## OptiFine Version
OptiFine HD U H9 for MC 1.19.2

## Installation Method
The issue was tested and found to be present both when it was installed via the installer and when it was in the mods folder for Forge (separately, of course).

## Fabric/Forge Version
1.19.2-forge-43.1.47

## Other Installed Mods
Architechtury 6.3.49 for Forge
Cloth Config 8.2.88 for Forge
Nostalgic Tweaks 1.2.2 for Forge

## Log Files/Crash Reports
![latest.log](https://github.com/sp614x/optifine/files/9847581/latest.log)

## F3 Debug Screenshot
![DiamondSwordBoundaryGapsF3Debug](https://user-images.githubusercontent.com/30667792/197419385-c8dc4ec8-e242-4c32-a25e-0e8f8a81ae38.png)

## Prior Testing
As mentioned above, this was tested both with OptiFine installed via the installer and when it is installed via the Forge mods folder, and it was found to be present in both cases.  

The issue was tested in vanilla Minecraft (without OptiFine), and it was not present.  It was also tested in my small modpack (mod list above) with OptiFine removed, and the issue again disappeared.

**Comment by fayer3** [comment]
not sure how you didn't see it, but this is clearly a vanilla issue 
![grafik](https://user-images.githubusercontent.com/8282299/197420963-7ee5383e-8d87-4d97-9a1d-32e6328009bb.png)
https://bugs.mojang.com/browse/MC-73186

**Comment by CaveMiner1215** [comment]
Huh, I was sure I didn't see it when I loaded Vanilla.  This is my bad.

My apologies, and thanks for pointing it out.

**Comment by Regnander** [comment]
I'd recommend that you check out [Vanilla Tweaks](https://vanillatweaks.net/picker/resource-packs/), which offers an option (named "Item Stitching Fix" under the _Fixes_ section) to fix this problem.
