### ISSUE TITLE
Optifine support/compatibility for Vulkan API and FidelityFX Super Resolution?

### ISSUE THREAD

**Issue by LiberteIV** [sp614x/optifine#7152]
## Description of the new feature
Hello,

I'm here to mention this mod https://github.com/xCollateral/VulkanMod which allows to start minecraft with the Vulkan API instead of OpenGL, chances are if the mod get's enough attention.. it might support FidelityFX Super Resolution which will drastically improve performance.
As an example this mod https://www.nexusmods.com/aplaguetalerequiem/mods/9 replaces DLSS with FSR in A Plague Tale Requiem, without the mod i had an average of 40 FPS on a GTX 1080 Ti 1440p ultra settings. With the FSR mod on Quality mode i had an average 80 FPS with the same settings while the image still looked even better then native.
Those results are crazy.
I beleve this (DLSS and FSR) are the future and will be supported by all major upcomming games.
The potential is to much to be ignored, my opinion.

Taking a look at VulkanMod's github page it clearly says this: **"This is a fabric mod that rewrites Minecraft OpenGL renderer to use Vulkan API."**
With 12,163 downloads the mod is still pretty smal compared to fabric / optifine / sodium, then again **imagine what Fabric, VulkanAPI, Optifine, and FidelityFX Super Resolution could do together**, i have no doubt minecraft's performance would skyrocket.

Seus Shader and Patrix Resourcepack are very performance hungry, getting an average 60 FPS with both enabled, i consider them both mandatory for playing minecraft as they look really good.
**With Vulkan and FSR those 60 FPS could easily turn into 120.**
At this moment using optifine with fabric requires optifabric, combining those mods with vulkanmod results in a game-crash.
By creating this "issue" i hope to bring more attention to the vulkanmod and it's potential for FSR.
If fabric, optifine, and optifabric would officialy support vulkanmod...

![Seus PTGI + Patrix](https://user-images.githubusercontent.com/116210112/198883634-3385e0d5-6827-4812-bf89-1e477ca1e6dd.png)

**Comment by LiberteIV** [comment]
Alright seems like sadly you don't intend to support FSR https://github.com/sp614x/optifine/issues/6398
Shaders do have a massive performance impact, so maybe after all FSR would make a difference, anyway i want to ask what are chances that optifine will support vulkanAPI instead of OpenGL, the performance difference is about 400-600 FPS, i see no logic in using OpenGL it's just wasted performance.

**Comment by FasterMars** [comment]
> using optifine with fabric requires optifabric, combining those mods with vulkanmod results in a game-crash. 

Optifabric with VulkanMod will obviously crash as Optifine is based on OpenGL and VM tries to run some Vulkan stuff at the same time so it tries running two different APIs which results in game crash

**Comment by IMS212** [comment]
Vulkan by itself does not improve performance. The reason Vulkan Mod is so fast is because it changes the underlying code to be faster, not because it’s on Vulkan.

**Comment by ZenIsBestWolf** [comment]
#5440 please search before creating new issues
