### ISSUE TITLE
Floating Santa/Witch Hat Bug

### ISSUE THREAD

**Issue by OrLavi** [sp614x/optifine#7154]
I found an Issue in Optifine in which any hat cosmetic on servers cause the cosmetic to float above you and dance for some reason

Optifine Version Used: OptiFine HD U M5
Client: Forge
Minecraft Version: 1.8.9

Screenshot:
![image](https://user-images.githubusercontent.com/90257497/199213973-d4719015-c663-47ea-a938-d736cba374e0.png)
![image](https://user-images.githubusercontent.com/90257497/199214141-8cf46225-b88a-40f5-8712-212506d2d96e.png)

**Comment by Ari-RERA-43** [comment]
Does this happen in single player?

**Comment by Jiingy** [comment]
Please provide more information. 
1. Are you on a client? ex- Feathered, Labymod, etc
2. Does this happen in singleplayer?
3. Does this happen on newer versions for you?
