### ISSUE TITLE
[Random] Chests don't work

### ISSUE THREAD

**Issue by LimeDev8756** [sp614x/optifine#7155]
## Description of Issue
When using Random Entities, wolfs can be random and works perfectly fine but when applying to a chest it won't work

## Steps to Reproduce
1. Make a random entity for chests

## OptiFine Version
1.19.2 H9 Ultra

## Installation Method
Both with Optifabric and Normal Optifine (not in mod folder)

## Fabric/Forge Version
Fabric 0.14.9

## OptiFabric Version
1.13.16

## Log Files/Crash Reports
https://pastebin.com/0VD0Cu4Y

## F3 Debug Screenshot
![Image](https://user-images.githubusercontent.com/100384210/200119381-e2d1c7cd-eb9e-4acc-86ad-5bcfdd7fdc14.png)

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   - Only OptiFine and Optifabric
- Does this happen without any mods at all?
   - Only Forge/Fabric by itself.
- Does this happen in OptiFine standalone?
  - Yes
- Does this happen in Vanilla without OptiFine?
  - It can't

## Additional Information
Just Chests and Paintings, no other entities

**Comment by Jiingy** [comment]
AFAIK chests currently are not supported entities for resourec pack features, I could be wrong

**Comment by omnihil33** [comment]
It works if you have a custom chest model, I don't know about vanilla. You can take a look at this:
https://drive.google.com/drive/folders/1nGCqARTKKyub2sJF6teirQF0zT7zTDR1?usp=sharing

**Comment by LimeDev8756** [comment]
It works, thanks for the help.

It shouldn't work like that though.
