### ISSUE TITLE
1.12 Update blocks vanilla feature

### ISSUE THREAD

**Issue by pughpunk** [sp614x/optifine#716]
While using the new 1.12 optifine, i noticed the Shift+Double Click to move many stacks of items at once feature was not working. I moved back to the 1.11.2 release, where it works. Not sure why, let me know what i could try differently.

**Comment by sp614x** [comment]
The Shift+double click works correctly with OptiFine.
```
To Shift + double click, get one item in your hand and then while holding shift, double click on another item type that you want to move.
```
http://minecraft.gamepedia.com/Controls#Computer
