### ISSUE TITLE
[Bug/Performance] Abysmal load times in 1.18.2 (Stoneblock 3)

### ISSUE THREAD

**Issue by Inrixia** [sp614x/optifine#7175]
## Description of Issue
When attempting to load the game OptiFine's loading its abysmally slow. I waited over a hour and only got up to here:
![image](https://user-images.githubusercontent.com/6373693/204168115-37261703-f104-4b70-89d9-c67065f5d952.png)

Without OptiFine and/or using Rubidium+Oculus this issue does not occur.

## Steps to Reproduce
1. Add OptiFine to Stoneblock 3
2. Launch

## OptiFine Version
```preview_OptiFine_1.18.2_HD_U_H9_pre2.jar```
also
```OptiFine_1.18.2_HD_U_H7.jar```

## Installation Method
Dropped jar into mods folder.

## Fabric/Forge Version
40.1.84

## Other Installed Mods
See Stoneblock 3 version 1.4.2
https://www.feed-the-beast.com/modpacks/100-ftb-stoneblock-3

## Log Files/Crash Reports
[debug.log](https://github.com/sp614x/optifine/files/10099546/debug.log)

**Comment by Siqust** [comment]
Hello, I have the same problem.
Did you manage to find a solution?

**Comment by Inrixia** [comment]
> Hello, I have the same problem. Did you manage to find a solution?

Nope, I'm just using Rubidium+Oculus now

**Comment by Siqust** [comment]
What version do you use?
I installed rubidium - 0.5.4 and oculus - 1.2.5a then launched new world and it crashed.

**Comment by Inrixia** [comment]
@Siqust Looks like you removed your commend about Rubidium+Oculus breaking on Stoneblock 3. Just adding for reference to others, follow this reddit comment on how to fix that https://www.reddit.com/r/feedthebeast/comments/yjkmhj/comment/ivufns0
