### ISSUE TITLE
1.19.3 preview version

### ISSUE THREAD

**Issue by Danjhop4** [sp614x/optifine#7185]
can you put up a 1.19.3 preview version

**Comment by SilentWhisperer** [comment]
I actually can't believe you're asking here
It takes time to uodate Optifine, and 1.19.3 came out yesterday
sp614x has his own life and a job.
So be patient. It's not that hard

**Comment by Danjhop4** [comment]
sure he already has a version it cant hurt to ask

**Comment by Danjhop4** [comment]
easy h as i say a lot of devs have previews ready

**Comment by SilentWhisperer** [comment]
sp614x cannot get a team for legal reasons, and he is using a custom thing to create Optifine, which isn't apparently updated yet

**Comment by Danjhop4** [comment]
i put nothing about a team

**Comment by PurpleWolfMC** [comment]
Sry I don't know what's going on and I have no place in knowing but why can't he make a team? What legal reasons? Sry if I am being a bit intrusive or something I am just confused

**Comment by SilentWhisperer** [comment]
copied from faq entry on OF discord
Q: How come sp614x doesn't have a team to work on OptiFine?
A: First off, legality. This would require them to distribute the source code to OptiFine, which violates the terms of service set by Mojang. 
Second, this allows for updates to be finished at the highest quality possible;  This means that sp614x would know all the innerworkings of each feature, and can fix any bugs without needing to pull apart more code then necessary.

**Comment by KaiAF** [comment]
It's being worked on, closing as this isnt an issue
