### ISSUE TITLE
Narrator Settings cannot be changed via menu

### ISSUE THREAD

**Issue by Baradar67** [sp614x/optifine#719]
1.12 - OptiFine 1.12 HD U C2
Options > Chat Settings > Narrator
Clicking this should change between disabled > narrates all > narrates chat > narrates system
Button is not disabled but does not click (ie, not greyed out).  Using control-b still works so just button functionality that is broken.
Does not work in single or multiplayer.
Does not work with "installed" Optifine or liteloaded.

**Comment by sp614x** [comment]
Updated preview C3 for 1.12
- fixed option Narrator not working
