### ISSUE TITLE
[Crash] "Batching chunks" error when piston update too often

### ISSUE THREAD

**Issue by Wolphwood** [sp614x/optifine#7190]
## Description of Issue
When pistons are updating quickly, the game crash.

## Steps to Reproduce
Having updating pistons (like ilmango's tree farm)

## OptiFine Version
1.18, 1.18.1, 1.18.2, 1.19.2, 1.19.2-HD-U-I1-pre4

## Installation Method
- Jar file in mod folder (Optifabric v1.13.6 + Optifine 1.19.2)
- Standalone

## Fabric/Forge Version
Fabric loader 0.14.9 - 1.19.2

## OptiFabric Version
Optifabric v1.13.6

## Other Installed Mods
- appleskin fabric mc1.19 2.4.1
- Autofish 0.9.5 fabric mc1.19
- emoji type 2.0.1+1.19
- fabric api 0.62.0+1.19.2
- horse stats vanilla 4.2.2
- itemscroller fabric 1.19.2 0.17.1
- litematica fabric 1.19.2 0.12.4
- litematica printer 1.19.2 2.5
- malilib fabric 1.19.2 0.13.0
- minihud fabric 1.19.2 0.23.3
- modmenu 4.1.1
- optifabric 1.13.16
- preview_OptiFine_1.19.2_HD_U_I1_pre4
- seedcrackerX 2.13
- tweakeroo fabric 1.19.2 0.14.4 pre.5
- worldedit mod 7.2.12
- XaerosWorldMap 1.28.1 Fabric 1.19.1
- Xaeros_Minimap 22.15.1 Fabric 1.19.1

## Log Files/Crash Reports
- [Crash Report 1](https://pastebin.com/raw/5fTNCNsF)
- [Crash Report 2](https://pastebin.com/raw/5bJfgNpL)
- [Latest Log](https://pastebin.com/raw/mPMiEMTE)

## F3 Debug Screenshot
![2022-12-12_18 09 55](https://user-images.githubusercontent.com/83301261/207110084-e9c409d8-2e95-479d-a526-ae27d9695721.png)
![2022-12-12_18 10 37](https://user-images.githubusercontent.com/83301261/207110096-09e878a9-6432-446d-8755-1ac484cd1874.png)

## Prior Testing
It's not happen in vanilla or modded without OF.
It's happening too with only OF, OptifFabric and Fabric.

**Comment by Hax-Inkling** [comment]
**I'm in exactly the same situation.**

[crash-2022-12-31_16.11.44-client.txt](https://github.com/sp614x/optifine/files/10326984/crash-2022-12-31_16.11.44-client.txt)

**Comment by Wolphwood** [comment]
> **I'm in exactly the same situation.** **Any fix idea?**
> 
> [crash-2022-12-24_16.14.57-client.txt](https://pastebin.com/LDbwCRbr)

@Hax-Inkling The only way i found to avoid crashes is to not use Optifine when you use redstone contraption with lot of piston 😕 
 When i want to farm, i need to restart Minecraft without OF 😢

**Comment by sp614x** [comment]
Fixed in 1.20.4 preview, to be backported.
