### ISSUE TITLE
[Bug] Z-fighting between Emissive and Base texture layer

### ISSUE THREAD

**Issue by Nuanulla** [sp614x/optifine#7193]
## Description of Issue
Z-fighting occurs between the Emissive and Base texture layer when a CEM element is moving at an inconsistent (non-linear) rate. For example, an element affected by a .rx function "sin(time * 0.14) / 28" will exhibit this issue. Z-fighting between the two mentioned layers do not occur with the following conditions:
- Entity is static
- Entity doesn't have CEM animations
- Entity's animation simply maintains a transformation or rotation (e.g. "bone1.rx": "torad(-4)")
- Entity is using a set of animations that doesn't jolt it in one or more axis in a rapid and non-linear rate

Obviously, with the nature of z-fighting, the issue occurs but is only visible when pixels at the same UV location on both layers are of different colors. Issue still occurs if entity isn't affected by any scaling animation.

Mobs that I've noticed this issue affecting:
Blaze, Vindicator, Ghast

## Steps to Reproduce
1. Assign specific animations to a bone
2. Provide different colors to the same UV space in emissive and base textures

Here are some animations you could use to test by applying them to the same group:
    "bone1.rx": "cos(time * 0.14) / 28",
    "bone1.ry": "sin(time * 0.14) / 28",
    "bone1.rz": "cos(time * 0.14) / 28"

## OptiFine Version
preview_OptiFine_1.19.2_HD_U_I1_pre4

## Installation Method
Dropped .jar into Mods folder

## Fabric/Forge Version
Forge 1.19.2 43.2.0

## Other Installed Mods
ShoulderSurfing-Forge-1.19.2-2.2.16
mobsunscreen-forge-1.19.2-3.0.8

## Log Files/Crash Reports
[none]

## F3 Debug Screenshot
![2022-12-15_17 56 41](https://user-images.githubusercontent.com/88032550/207829234-32da056c-26e6-439b-b9e7-9297bd740fd9.png)

## Prior Testing
[none]

## Additional Information
Video: https://cdn.discordapp.com/attachments/425702172219408385/1052882981561323550/test.mov

**Comment by Nuanulla** [comment]
Any status on this bug?

**Comment by Nuanulla** [comment]
This is still an issue on I3 pre7.

Test Environment:
- Minecraft 1.19.4;
- OptiFine HD U I3 pre7;
- Forge 45.0.19;
- JDK 17.0.6.

**Comment by Nuanulla** [comment]
https://www.curseforge.com/minecraft/texture-packs/nier-automata-resource-pack

Test with my resource pack. Issue should be evident with my Blaze and Ghast CEMs.

**Comment by Nuanulla** [comment]
I've released 4.2.9 of my resource pack here, which uses physical cubes rather than just emissive layers for the eyes:
https://modrinth.com/resourcepack/nier-automata-resource-pack/version/4.2.9-50

These eye cubes are moved by 0.025 units. And, depending on closeness to head, still manages to exhibit z-fighting. What this shows is that OptiFine's emissive layer shares this relevant property with the model's physical elements. OptiFine is not capable of updating elements at the same rate, even if these elements belong to the same bone. We can consequently infer that the issue isn't limited to emissive layers.

**Comment by sp614x** [comment]
The blaze animation order is not correct. 
The two marked lines should be in reverse order:

![image](https://github.com/sp614x/optifine/assets/16635441/6e359d73-6492-42a6-a367-4f7f2cc0aa78)

What happens is:
- `head_st.rx` uses the old value of `flyer_base.rx`
- a new value is assigned to `flyer_base.rx`

That would lead to `head_st.rx` always lagging one frame behind `flyer_base.rx` which causes the z-fighting.

**Comment by Nuanulla** [comment]
Using 4.2.7 as a test base since 4.2.10 uses separate eye elements, your solution did fix the eyes. Thank you.

But when using 4.2.10 as my test base, it seems there's something else causing z-fighting with the circular flight unit itself, and I cannot see how my animations would lead to this issue. 

https://github.com/sp614x/optifine/assets/88032550/4f1cd16d-f1c6-4c36-8d0e-28310f94f97b

This is admittedly straying into project-specific issue territory, but I'd like to understand similarities in these issues so I can apply fixes to my other models by myself.

**Comment by sp614x** [comment]
Generally the order of animation updates matter.
If one variable uses the value of a second variable and later the second variable is changed then the first one will lag with one frame.
