### ISSUE TITLE
White Screen Flashes

### ISSUE THREAD

**Issue by mandm635** [sp614x/optifine#72]
Using the Optifine 1.9.2 B1, I seem to get a wierd white screen during any loading screen(creating/loading worlds, connecting to servers, anywhere that normally has the dirt background). A small bug but it would be nice if it was fixed.

**Comment by sp614x** [comment]
Does it work with smaller resource pack or disabled connected textures?

**Comment by mandm635** [comment]
Its the default resource pack, no shaders, and I didn't change the connected textures setting from the default when I loaded it, I don't currently have access to a computer to double check though.

**Comment by sp614x** [comment]
Is it reproducible, error log?

**Comment by sp614x** [comment]
No details.
