### ISSUE TITLE
Optifine santa hat

### ISSUE THREAD

**Issue by Niek194** [sp614x/optifine#7202]
## Description of Issue
in the discord they say if you go to in-game Options -> Skin Customization -> OptiFine Cape -> Open Cape Editor
they say there will be a free santa hat for chrismas

## Steps to Reproduce
and i did follow the steps corectly
so maby it's just a bug 

## OptiFine Version
1.19.2

## F3 Debug Screenshot
![screenshot](https://user-images.githubusercontent.com/121336663/209428401-b5059eb8-1ecf-40cb-862b-bd097fa349ae.png) 

## Additional Information
i play on a mac (idk if that's the problem)

**Comment by Ari-RERA-43** [comment]
As far as I know, the hat is only for people who have donated. This doesn’t appear to be a bug.

**Comment by KaiAF** [comment]
It can only be given to donators, sorry. I will update the announcement

**Comment by Niek194** [comment]
> As far as I know, the hat is only for people who have donated. This doesn’t appear to be a bug.

ooowwh i din'd know that (thx btw)
