### ISSUE TITLE
[Technical] Unable to launch Minecraft using Optifine

### ISSUE THREAD

**Issue by PlaceReporter99** [sp614x/optifine#7205]
## Description of Issue
When I try to launch Optifine, It says 'Unable to launch minecraft'

## Steps to Reproduce
I don't know as it didn't happen until today.

## OptiFine Version
Optifine for MC version 1.19.2

## Installation Method
Used the standalone installer

## Other Installed Mods
Baritone, Fabric mod loader

## Log Files/Crash Reports
None

## F3 Debug Screenshot
N/A

## Prior Testing
When I tried this in vanilla, it worked perfectly fine.

## Additional Information
I did not use the Fabric mod loader.
I am unable to give some info as this issue is about not being able to launch Minecraft.

**Comment by TryhardDoge** [comment]
Hey place reporter, I'm a little late but wanted to let you know that to get optfine working on fabric you need optifabric: https://www.curseforge.com/minecraft/mc-mods/optifabric (UNOFFICAL AND NOT AFFILIATED WITH OPTIFINE, DONT REPORT ITS BUGS HERE)

**Comment by omerien** [comment]
He didn't use the fabric loader, it's not hard to understand
