### ISSUE TITLE
CTM "matchBlocks" does not work with blockstates 

### ISSUE THREAD

**Issue by CarJem** [sp614x/optifine#721]
I have tried to use blockstates to identify which block to be used, yet I am forced to use metadata because blockstates are not recognized.

Ex.

matchBlocks=minecraft:observer:powered=true

This doesn't work while this does

matchBlocks=minecraft:observer
metadata=6-11

**Comment by sp614x** [comment]
Updated preview C3 for 1.12
- fixed CTM for observer power state

The problem was that the observer block was not converting the powered state to metadata.
The correct metadata for powered is 8-13.
