### ISSUE TITLE
Completing OptiFine HD U M6 [1.8.9]

### ISSUE THREAD

**Issue by IntMarco** [sp614x/optifine#7213]
It would be possible to complete **Optine M6 [1.8.9]** in the future. I understand that it is an old version of the game but there are many PvP clients using it and many people still playing it. In case **sp614x** you have some free time to complete it would be a great thing.
Thank u, see u.

**Comment by omerien** [comment]
What do you mean by complete ?

**Comment by IntMarco** [comment]
I mean the M6 version is still in preview and has not been released as a stable version.

**Comment by omerien** [comment]
Can you use it ? Do you encounter any problem ? A version in pre-release doesn't mean you can't use it
It's just a version ID
