### ISSUE TITLE
[1.20.1/1.20.4 Bug] Random painting variants not working

### ISSUE THREAD

**Issue by SeaOfPixels** [sp614x/optifine#7234]
## Description of Issue
Random painting variants stopped working in OptiFine 1.19.3, while other entity variants are. Normally I would dismiss this as "oh I guess the OptiFine 1.19.2 I1 features aren't in the 1.19.3 builds yet", however the biome chests are working, so I've opted to make a bug report for the paintings.

## OptiFine Version
1.19.3 I3, 1.19.4 l4, OptiFine 1.20-pre4_HD_U_I5_pre1, OptiFine 1.20_HD_U_I5_pre3, OptiFine 1.20.1_HD_U_I5_pre6, OptiFine 1.20.1_HD_U_I5_pre7, OptiFine 1.20.1_HD_U_I6_pre6, OptiFine 1.20.4_HD_U_I7_pre2, OptiFine 1.20.4_HD_U_I7_pre4, OptiFine 1.20.4_HD_U_I7_pre5

**Comment by SeaOfPixels** [comment]
Really hoping this gets fixed soon, I keep getting messages on my end complaining about how this doesn't work in 1.19.4/1.20.1.

**Comment by Jiingy** [comment]
Can you send an example resource pack to debug?

**Comment by SeaOfPixels** [comment]
> Can you send an example resource pack to debug?

[NewDefault+OnlyPaintings.zip](https://github.com/sp614x/optifine/files/12285366/NewDefault%2BOnlyPaintings.zip)

**Comment by SeaOfPixels** [comment]
Would be nice to see this fixed for 1.20.4's release. Fabric mods that replicate random entities support this just fine.

**Comment by sp614x** [comment]
Fixed, coming in next 1.20.4 preview.
To be ported to 1.19.x versions on next round of updates.
