### ISSUE TITLE
[1.19.3] Glass Pane not merging correctly with other Panes

### ISSUE THREAD

**Issue by cxtuveri05** [sp614x/optifine#7236]
Description of Issue

## Steps to Reproduce
1. Place more than 1 Glass-Pane behind each other.
2. Place Them in different Directions
3. See The Issue

## OptiFine Version
OptiFine HD U I2 pre2

## Installation Method
included standalone installer

![2023-01-23_13 05 18](https://user-images.githubusercontent.com/123374784/214036026-fa7cfbdc-c27f-4bcb-aa38-1a2b660c8ea9.png)
![2023-01-23_13 03 38](https://user-images.githubusercontent.com/123374784/214036030-ac5c9fce-f9cb-40e7-9c61-499d4b15d50e.png)
![2023-01-23_13 03 49](https://user-images.githubusercontent.com/123374784/214036035-d6a207ee-be20-475e-b863-60e107c55cd6.png)
![2023-01-23_13 04 08](https://user-images.githubusercontent.com/123374784/214036039-1b0db33d-db55-4285-891b-a71d4752c593.png)

**Comment by KaiAF** [comment]
Fixed in pre3
