### ISSUE TITLE
[1.19.3] Crash with Forge on startup

### ISSUE THREAD

**Issue by tawan475** [sp614x/optifine#7237]
## Description of Issue
Immediately crash after starting the game with optifine as mod on forge

## Steps to Reproduce
1. Install forge  forge-1.19.3-44.1.5
2. Download optifine 1.19.3_HD_U_I2_pre2
3. Open it
4. Click extract
5. Drag generated JAR into mods folder
6. Start the game

## OptiFine Version
1.19.3_HD_U_I2_pre2

## Installation Method
1. Download optifine
2. open it
3. click extract
4. drag generated JAR into mods folder

## Fabric/Forge Version
forge-1.19.3-44.1.5

## Other Installed Mods
None. I've deleted everything else and the issue still occur, but that does not happen in reverse. 

## Log Files/Crash Reports
[crash-2023-01-23_20.34.34-client.txt](https://github.com/sp614x/optifine/files/10480214/crash-2023-01-23_20.34.34-client.txt)

## Prior Testing
Optifine standalone works fine
Forge without mods can be launch just fine
Delete old configs

## If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
Yes.
- Does this happen without any mods at all?
Yes, Only Forge/Fabric by itself.
- Does this happen in OptiFine standalone?
No.
- Does this happen in Vanilla without OptiFine?
No.

- Does the issue still happen with only the remaining mods installed?
No.

**Comment by SilentWhisperer** [comment]
Optifine 1.19.3 isn't compatible with Forge yet

**Comment by tawan475** [comment]
I see

**Comment by SteveMelons** [comment]
Is there any workaround for the moment? Manual installation or something?

**Comment by SilentWhisperer** [comment]
if you wanna play on Forge with Optifine 1.19.3, then you can't as the prerelease is simply not compatible with Forge yet
you can however just use standalone installation if you aren't planning on using mods

**Comment by KaiAF** [comment]
pre5 is now compatible with forge

**Comment by Firestar1291** [comment]
I still have this problem even though it should work, I use the only optifine available for 1.19.3., and the current Forge version. Still, the game doesn't launch with the Exit Code 1. What can I do to prevent that and use Forge with optifine?

**Comment by SilentWhisperer** [comment]
wdym mean by current?
any other mods that you're using?

**Comment by Firestar1291** [comment]
1.19.3-forge-44.1.0

I first installed it with other mods, but when I removed optifine 1.19.3, it worked again. Then I tried using only optifine (still on forge though), and the problem still occured. Also, the other mods worked without optifine, so the problem is clearly optifine.

**Comment by mindforger** [comment]
maybe you should link a crash report so one could check your issue

you report is equivalent with telling a mechanic that you car wont start without bringing the car to the garage :D

**Comment by Firestar1291** [comment]
haha ok
ill just add the file in a sec

**Comment by Firestar1291** [comment]
Ok well, there is not really a crash report. It just says exit code: 1
![Screenshot_20230405_151330](https://user-images.githubusercontent.com/93722932/230091323-0ce6882d-6c60-4667-8634-eea90cada8bf.png)

**Comment by Firestar1291** [comment]
Ok I managed to make it work. For some reason, I needed the preview version of Forge, the stable one was not enough. Still don't know why though...
