### ISSUE TITLE
Crash on start up

### ISSUE THREAD

**Issue by TwitchNatural** [sp614x/optifine#7239]
When I go to launch Minecraft with optifine it will crash after loading up the window

**Comment by SilentWhisperer** [comment]
how exactly are you loading optifine and which version

**Comment by TwitchNatural** [comment]
the newest version I tried both and I use the minecraft launcher

**Comment by omerien** [comment]
Telling us "it crashes" isn't helpful.
Redo the crash for the standalone version of OptiFine, and send us the "latest.log" file in your minecraft folder

**Comment by omerien** [comment]
I love asking for more information and never getting an answer :)
