### ISSUE TITLE
1.12 texturepack - ctm orientation not enforced

### ISSUE THREAD

**Issue by rivitoz** [sp614x/optifine#724]
Blocks 43 and 44 defined as follows - slabs stacked to produce columns 

tiles=48-51
metadata=3
method=vertical

produce columns in vertical and NS orientation but not EW  should be vertical only.

![ctmbug1](https://user-images.githubusercontent.com/13307413/27513328-75ece502-59a5-11e7-9668-b24b4ebd86a7.png)
![ctmbug2](https://user-images.githubusercontent.com/13307413/27513329-7ab9c442-59a5-11e7-9772-5a33b27ec5a3.png)

**Comment by sp614x** [comment]
You can limit CTM to side faces only by adding:
```
faces=sides
```
