### ISSUE TITLE
Grass rendered incorrectly

### ISSUE THREAD

**Issue by SlimeDog** [sp614x/optifine#7240]
## Description of Issue

Grass is rendered as various shades of solid green.

## Steps to Reproduce
1. Install Optifine OptiFine_1.19.3_HD_U_I2_pre2
2. Connect to a 1.19.3 server

## OptiFine Version

OptiFine_1.19.3_HD_U_I2_pre2

## Installation Method

- Download preview_OptiFine_1.19.3_HD_U_I1_pre2.jar 
- java -jar preview_OptiFine_1.19.3_HD_U_I1_pre2.jar 

## Other Installed Mods

Dramatic+Skys+Demo+1.5.3.2

## Log Files/Crash Reports

[server log](https://whitedog.straight8.com/drops/of-latest.log)

## Screenshot

![Screen Shot 2023-01-23 at 6 22 19 PM](https://user-images.githubusercontent.com/17748923/214217577-cba04cf2-b406-4c14-ae56-12a8764ebef4.png)

**Comment by GGus99** [comment]
Turning off Anisotropic Filtering in Video->Quality Settings fixed this for me.

**Comment by SlimeDog** [comment]
Thanks for the information. I'm not sure "fixed" is the correct term, since anisotropic filtering should work (and has done, in previous OptiFine releases).

**Comment by omerien** [comment]
The issue is fixed in pre3, please close this

**Comment by SlimeDog** [comment]
> The issue is fixed in pre3, please close this

True that.
