### ISSUE TITLE
Stuck on mojang red screen when trying to go in a third party server

### ISSUE THREAD

**Issue by Thepoorgamer** [sp614x/optifine#7241]
## Description of Issue
When I join a third party server the Monjang red loading screen just refreshes infinitely

## Steps to Reproduce
1.I log into minecraft java
2.i went into the server page
3.1 typed in the ip adress in the third party server section 
4.And it just looped the red Mojang loading screen

## OptiFine Version
1.19.3 pre-1 and pre-2

## Installation Method
By standalone installer

## Prior Testing
<!-- If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
- No

## Additional Information
Exit code is 1

https://user-images.githubusercontent.com/123459088/214286469-da02c488-fb22-47ef-8aff-592477f51883.mp4

**Comment by SilentWhisperer** [comment]
does it happen without optifine?
does it happen on any other server?

**Comment by IPeredero** [comment]
I faced the same issue.
If the server requests a resource pack, then a splash loop occurs.

**Comment by Thepoorgamer** [comment]
> does it happen without optifine? does it happen on any other server?

-It doesn't happen without optifine on the same verstion(1.19.3) 
-It happens on any other server when using optifine

**Comment by omerien** [comment]
Quit Minecraft, then go into your .minecraft, and send us the file "latest.log" so we can see if there's error messages

**Comment by Thepoorgamer** [comment]
> Quit Minecraft, then go into your .minecraft, and send us the file "latest.log" so we can see if there's error messages

https://drive.google.com/file/d/1GnLDPLHSAGkGIRJcN-oKv3R99eD-33r8/view?usp=drivesdk
Here, I uploaded it to google drive as github doesn't support log files

**Comment by Thepoorgamer** [comment]
> > does it happen without optifine? does it happen on any other server?
> 
> -It doesn't happen without optifine on the same verstion(1.19.3) -It happens on any other server when using optifine

And a bit of correction to my previous reply
It doesn't happen with servers which doesn't require resource packs to be downloaded.(e.g hypixel)

**Comment by Ari-RERA-43** [comment]
1.19.3 OptiFine has issues with loading into worlds while using resource packs in general. This might be related. 

Also, you can just upload the latest.log file by dragging it over your comment box, no need for Google Drive.

**Comment by Thepoorgamer** [comment]
> 1.19.3 OptiFine has issues with loading into worlds while using resource packs in general. This might be related.
> 
> Also, you can just upload the latest.log file by dragging it over your comment box, no need for Google Drive.

[latest.log](https://github.com/sp614x/optifine/files/10528865/latest.log)

**Comment by KaiAF** [comment]
Should be fixed in pre3
