### ISSUE TITLE
the bookshelves and grass are textured all fucky

### ISSUE THREAD

**Issue by CrystllCnxl** [sp614x/optifine#7242]
## Steps to Reproduce
1. joined a realm in 1.19.3 
2. ...looked at a book shelf and grass

## OptiFine Version
OptiFine HD U I2 pre2

## Installation Method
stand alone installer

- Does this happen in Vanilla without OptiFine? 
no

also tried it with multiple texture packs, same result. also tried a fresh restart and an older version, and it only and always happens on optifine HD U I2 pre2
![2023-01-24_18 00 07](https://user-images.githubusercontent.com/123517001/214440882-d83aa459-2c84-4fa2-bcf4-dd15503602ea.png)
![2023-01-24_18 00 26](https://user-images.githubusercontent.com/123517001/214440891-373ca241-9ac0-4ffd-8161-6c5c34a83496.png)
![2023-01-24_18 03 28](https://user-images.githubusercontent.com/123517001/214440918-b1723fe1-e566-48e8-8f85-46df8cec8a91.png)

**Comment by BAM06** [comment]
Same thing happened to me, glass textures also broken as well as all types of grass like nylium and nether blue and red ones that I don't remember the name of, the sides of path blocks I can see through

**Comment by omerien** [comment]
Can you send us the resource packs you tried ?

**Comment by omerien** [comment]
PS: seems related to #7238 and #7240

**Comment by BAM06** [comment]
> Can you send us the resource packs you tried ?

No, resource packs didn't do this, it just happens on its own plain Java with optimise HD U I2 pre2 nothing else

**Comment by omerien** [comment]
They said they tried multiple resource packs, so maybe these aren’t compatible with 1.19.3 ; I just wanted to check, it’s worth checking

**Comment by CKaylis** [comment]
This happens for me under these circumstances (Steps To Reproduce):
- Run Minecraft 1.19.3 with OptiFine HD U I2 pre2
- Turn Anistropic Filtering on, 2-16
- Enable Connected Textures, Fast or Fancy

![2023-01-29_15 36 24](https://user-images.githubusercontent.com/5816420/215354930-4f48eb65-b582-42c3-8809-e6986507ba99.png)

Issue does not happen when Anistropic Filtering is off or Connected Textures is off or both.

**Comment by CKaylis** [comment]
I've confirmed the issues with my previous post above are resolved as of the 1.19.3-pre3 release. No grass, glass, bookshelf or sandstone connected texture issues with Anistropic Filtering on. Thank you

**Comment by omerien** [comment]
(= Please close this)

**Comment by KaiAF** [comment]
Should be fixed in pre3 and above
