### ISSUE TITLE
[Crash] Client crashes when joining a server.

### ISSUE THREAD

**Issue by TomasGnG** [sp614x/optifine#7244]
## Description of Issue

When I try to join a server the client connects but as the custom texturepack from the server gets loaded it crashes the game.
## Steps to Reproduce
1. Start MC with Optifine
2. Join on a server that uses a custom texturepack

## OptiFine Version

OptiFine-1.19.3_HD_U_I2_pre2
## Installation Method

Installed it via the included standalone installer.

## Log Files/Crash Reports

Latest log: https://pastebin.com/XdssuLJM
Crash log: https://pastebin.com/YyREjQme

## Prior Testing

It only happens on servers with a custom server texturepack.

**Comment by SAVEVI** [comment]
I have the same issue,too

**Comment by omerien** [comment]
Does the bug still happens with pre3 ?

**Comment by SAVEVI** [comment]
This error no longer occurs,thanks :)))))))))))))))

**Comment by TomasGnG** [comment]
> 

No, it got fixed. :)

**Comment by TomasGnG** [comment]
This error got fixed in `OptiFine HD U I2 pre3`.
