### ISSUE TITLE
[Category] Crash Report

### ISSUE THREAD

**Issue by NoHere32** [sp614x/optifine#7247]
## Description of Issue

1. Connection to a server containing a custom texture pack

## Prior Testing
<!-- If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
answer : No

**Comment by NoHere32** [comment]
[hs_err_pid74316.log](https://github.com/sp614x/optifine/files/10509644/hs_err_pid74316.log)

**Comment by omerien** [comment]
Please, redo the method you did and send us the file named "latest.log" in your minecraft folder.
That way we can help you better.

**Comment by omerien** [comment]
Does the bug still happens with pre3 ?

**Comment by NoHere32** [comment]
Hello, sorry for not having followed up, after testing the bug is not present in pre3

**Comment by NoHere32** [comment]
I also give this info now that I can join a 1.19.3 server with a pack the logo put to replace mojang studios on the display loading 
screen does not load.

**Comment by Ari-RERA-43** [comment]
Close this issue since it’s been fixed
