### ISSUE TITLE
[Category] Forge 1.19.3-44.0.0 crashes

### ISSUE THREAD

**Issue by silver7hawk** [sp614x/optifine#7248]
## Description of Issue
Windows 10 running Minecraft Java with Forge 44 which works fine on its own and with JourneyMap connecting to a private server on the same network. When I put Optifine pre1 or pre2 in the mods folder launching crachs with error code 1.

## Steps to Reproduce
Install forge 1.19.3-44.0.0
add optifine pre1 or pre2 to mods folder 
run launcher, launch forge
the Mojang red screen will start to come up and then it crashes after a few seconds returning to the launcher.

## OptiFine Version
preview_OptiFine_1.19.3_HD_U_I2_pre2

## Installation Method
I have tried both, the installed version works. Running it as a mod under Forge is where I get the error.

## Fabric/Forge Version
Forge 1.19.3-44.0.0

## Other Installed Mods
Journeymap is the only other mod and I have tried it without it and no change

## Log Files/Crash Reports
[crash-2023-01-26_20.53.23-client.txt](https://github.com/sp614x/optifine/files/10514854/crash-2023-01-26_20.53.23-client.txt)

## Prior Testing

      -If I remove Optifine and keep everything else, everything works with no errors.

**Comment by Ari-RERA-43** [comment]
OptiFine on 1.19.3 is not yet compatible with Forge. Close this issue.

**Comment by omerien** [comment]
You can use the latest 1.19.2 OptiFine version in the meantime, which is only compatible with Forge 43.1.52

**Comment by sp614x** [comment]
Not compatible with Forge yet.
