### ISSUE TITLE
White lines in the clouds.

### ISSUE THREAD

**Issue by Cha0sPudd1ng** [sp614x/optifine#7249]
In the clouds are some white lines.
The old way does not work anymore: [https://bugs.mojang.com/browse/MC-1794](https://bugs.mojang.com/browse/MC-1794)
Its possible to fix that with Optifine in the future, or exist a another possibility?

![2023-01-27_04 01 31](https://user-images.githubusercontent.com/1367047/215008370-a2450c6a-fce5-42f8-8499-d0e6f8a6ecd7.png)

**Comment by omerien** [comment]
In which version of Minecraft did you have this problem ?
Does the bug happens in vanilla ?

**Comment by Cha0sPudd1ng** [comment]
I have this in Fabric 1.19.2 and in Vanilla 1.19.2+.

**Comment by omerien** [comment]
OptiFine isn’t here to fix vanilla bugs
Please close this issue
