### ISSUE TITLE
[Bug] Infinitely recharging client 

### ISSUE THREAD

**Issue by Thenegal-Marie** [sp614x/optifine#7252]
## Description of Issue
I've download OptiFine HD U I2 pre2 today and started minecraft with it. I connected to a server, the server said that i'm connected but the client just reload and reload and reload... 

## Steps to Reproduce
1. Start minecraft luncher with OptiFine HD U I2 pre2
2. Connect to the server play.monartis.fr
3. Watch client reload

## OptiFine Version
OptiFine HD U I2 pre2 on classic luncher

## Installation Method
Downloaded optifine on https://www.optifine.net/downloads and double click on jar

## Prior Testing
- Not happening in Vanilla without OptiFine 

## Additional Information
Video and screenshots of the bug : https://mega.nz/folder/gNZjWRjS#5JmvpVjhyC3DExTrMVY_iw

**Comment by Ari-RERA-43** [comment]
Disable server resource packs for that server

**Comment by omerien** [comment]
And close this issue, it is already being tracked in #7244

**Comment by KaiAF** [comment]
Fixed in pre3
