### ISSUE TITLE
[Bug] Server Resource Pack Won't Load

### ISSUE THREAD

**Issue by IAmNamedJosh** [sp614x/optifine#7254]
## Description of Issue
When joining a server with a server resource pack, it repeats the loading screen forever

## Steps to Reproduce
Join Wynncraft

## OptiFine Version
1.19.3 I2 pre-2

## Installation Method
Standalone installer

## Log Files/Crash Reports
[latest.log](https://github.com/sp614x/optifine/files/10528197/latest.log)

## Prior Testing
<!-- If you've installed standalone:
- Does this happen in Vanilla without OptiFine? No

## Additional Information
I don't know if it goes forever, but I gave it like 30 seconds. Vanilla loads in 1 second.

**Comment by omerien** [comment]
Please, close this issue, it is already being tracked in #7244

**Comment by KaiAF** [comment]
Fixed in pre3
