### ISSUE TITLE
[CIT] [1.19.3] Item cit does not load the texture

### ISSUE THREAD

**Issue by SporeHarvest** [sp614x/optifine#7255]
## Description of Issue
I have created a pack that gives enchanted books unique textures. It worked fine on 1.19.2 but when I tried the 1.19.3 loader the items show as purple and black squares. 

I get them to show up sometimes when I fiddle with the properties file on one item and it fixes them all but then on a fresh relaunch it breaks again.

## Steps to Reproduce
1. I installed my texture pack and it showed the missing textures
2. Fiddled with the properties files and it got fixed
3. Fresh relaunch breaks the textures all over again

## OptiFine Version
release 1.19.3-optiFine_HD_U_I2_pre2

## Installation Method
I used the installer

**Comment by Ari-RERA-43** [comment]
OptiFine 1.19.3 does not yet support CIT. Close this issue.

**Comment by SporeHarvest** [comment]
Ah okay then thank you for telling
