### ISSUE TITLE
[Crash] Crash when joining server with custom resource pack

### ISSUE THREAD

**Issue by MrKinau** [sp614x/optifine#7256]
## Description of Issue
Crash on loading custom server resource pack.

## Steps to Reproduce
1. Start Minecraft with Optifine 1.19.3 I2 pre-2 installed
2. Connect to `mc.cytooxien.de`
3. The client may crash (tested on different devices, not every device fails)

## OptiFine Version
Optifine 1.19.3 I2 pre-2

## Installation Method
Installer

## Log Files/Crash Reports
[hs_err_pid35216.log](https://github.com/sp614x/optifine/files/10530284/hs_err_pid35216.log)
[latest - 2023-01-29T172900.926.log](https://github.com/sp614x/optifine/files/10530285/latest.-.2023-01-29T172900.926.log)

## Additional Information
Maybe related to https://github.com/sp614x/optifine/issues/7247 or https://github.com/sp614x/optifine/issues/7244 just close this if the issue is the same and already tracked there.

**Comment by omerien** [comment]
Close it, it seems to be the same issue.
