### ISSUE TITLE
Low FPS on 4000 Series 

### ISSUE THREAD

**Issue by theoddcoconut** [sp614x/optifine#7262]
## Description of Issue
I have a 4070TI Asus ROG edition. I noticed that I was barely keeping an fps of over 50 without any shaders or mods installed. I did some testing and my results are as follows: (Note all of this was done standing in the same spot facing the same direction) When I revert back to vanilla I am sitting at about 120fps (the cap I have set within Minecraft).

Edit:
I just stumbled across this thread (https://github.com/sp614x/optifine/issues/7013) that seemed to have similar issues. I disabled Antistrophic filtering as suggested by one of the comments and the issue is completely fixed as seen in this image. Hopefully, this helps.
![No AA](https://user-images.githubusercontent.com/114507672/215969121-1fa7276a-3451-45c3-adb9-57a0b6ca4ec9.png)

I have also noticed that my GPU registers as nearly maxed out in the F3 menu, despite actually being at less than 35% usage 

## Steps to Reproduce
Play with a 4070 TI

## OptiFine Version
1.19.3 pre 3

## Installation Method
Official installer

## Log Files/Crash Reports
No Crashes have occurred

## F3 Debug Screenshot
![1 19 3 pre2](https://user-images.githubusercontent.com/114507672/215967350-d0f575cc-7e2a-4fb1-b92d-b496db9651a0.png)
![1 19 3 pre3](https://user-images.githubusercontent.com/114507672/215967354-96cbc717-ed3b-4f88-a622-38b8d2bfab1d.png)
![Vanilla](https://user-images.githubusercontent.com/114507672/215967357-67343608-ee82-4b3e-9ecb-ddfcabaed026.png)
![1 19 2](https://user-images.githubusercontent.com/114507672/215967359-f32a2d6a-a0c5-4fc5-a072-a11d0d69c21d.png)

## Prior Testing
Increasing ram allotment for Minecraft from 2 to 6 - roughly 3 fps increase, no effect on %
changed many of the performance settings - No effect on fps or %
Applied an OC on my CPU - No effect on fps or %
Reinstalling optifine - No effect on fps or %
Install 1.19.3 pre2 - No effect on fps or %
Revert back to vanilla Minecraft - fps jumps to 120+, usage drops to 30% - 60%
          These numbers do not perfectly correlate with my actual usage, however they are much more realistic than when using the 
          optifine Release

**Comment by omerien** [comment]
Note : the solution for recent versions of Minecraft isn’t entirely false ; Sodium/Lithium/Phosphor are better for 1.15+

**Comment by sp614x** [comment]
The screenshots show different settings, one has Anisotropic Filtering and the other has Render Regions active.
Anisotropic Rendering uses a different rendering mode which can be significantly slower.
Render Regions is an optimization which can increase FPS on longer render distances.
