### ISSUE TITLE
[Bug] Optifine crash with Immersive garden cloche

### ISSUE THREAD

**Issue by VannaKarenina** [sp614x/optifine#7265]
## Description of Issue

If you load a working garden cloche block, the game immediately crashes

## Steps to Reproduce

1. Setup immersive and optifine
2. Place garden cloche from immercive and make him work
3. See how game is the crashes

## OptiFine Version

OptiFine HD U I1

## Installation Method

Place mod file in mods folder

## Fabric/Forge Version

1.19.2-forge-43.2.3

## Other Installed Mods

Other mods are from FTB Presents Direwolf20 1.19

## Log Files/Crash Reports

https://pastebin.com/KUK84D1k

## F3 Debug Screenshot

![image](https://user-images.githubusercontent.com/46137062/216813711-4346d2a0-b5d2-43b7-b459-74444667c63b.png)

## Prior Testing
If you've installed using Forge/Fabric:
- Does this happen without other mods installed? No
- Does this happen without any mods at all? No
- Does this happen in OptiFine standalone? No
- Does this happen in Vanilla without OptiFine? No
- Have you tried using a binary search to find which mods cause this issue? Yes and find there is conflict between immersive and optifine 
- Does the issue still happen with only the remaining mods installed?  If delete optifine game will work normaly

## Additional Information

None

**Comment by omerien** [comment]
Already saw and tracked in #7257, please close this issue
