### ISSUE TITLE
[OptiFine Installation] Cannot find Minecraft 1.19.2

### ISSUE THREAD

**Issue by odysseuskir** [sp614x/optifine#7271]
## Description of Issue
On my laptop running Zorin OS (Ubuntu-based Linux distro) I try to install OptiFine for Minecraft 1.19.2 but when I click install I get a "Cannot find Minecraft 1.19.2" error, even though I have it installed. **I have checked that I have intalled Minecraft 1.19.2 and not 1.19.3**

## Steps to Reproduce
1. Install OptiFine from the official website 
2. Opened ~/Downloads/ directory
3. Right clicked on OptiFine file and selected properties
4. Selected "Permissions"
5. Selected "Allow executing file as program"
6. Double clicked on OptiFine file
7. Clicked "Install"
8. Error occurs

## OptiFine Version
1.19.2

## Installation Method
Steps to reproduce -> Step 1 to 7

## Log Files/Crash Reports
Error: Cannot find Minecraft 1.19.2

**Comment by toutlamer** [comment]
At which path is your Minecraft installation located ?

**Comment by SilentWhisperer** [comment]
did you run Minecraft 1.19.2

**Comment by odysseuskir** [comment]
As I mentioned, yes I have.

**Comment by Ari-RERA-43** [comment]
How is Minecraft installed? Is it a flatpak, official deb, a 3rd party launcher, etc?

**Comment by odysseuskir** [comment]
> How is Minecraft installed? Is it via a flatpak, snap, official deb, 3rd party launcher, etc?

flatpak

**Comment by odysseuskir** [comment]
> At which path is your Minecraft installation located ?

/home/odysseus/.var/app/com.mojang.Minecraft/.minecraft

**Comment by odysseuskir** [comment]
> And can you show us the content of the versions/1.19.2 folder in your Minecraft folder ?

[![1.19.2 folder screenshot](https://i.postimg.cc/s2qdsBhV/Screenshot-from-2023-02-14-15-04-16.png)](https://postimg.cc/FfynxHpq)

**Comment by Ari-RERA-43** [comment]
> > How is Minecraft installed? Is it via a flatpak, snap, official deb, 3rd party launcher, etc?
> 
> 
> 
> flatpak

Point OptiFine to the flatpak's versions folder

**Comment by odysseuskir** [comment]
> > > How is Minecraft installed? Is it via a flatpak, snap, official deb, 3rd party launcher, etc?
> > 
> > 
> > flatpak
> 
> Point OptiFine to the flatpak's versions folder `/home/odysseus/.var/app/com.mojang.Minecraft/.minecraft/versions`

got a file not found error

**Comment by Ari-RERA-43** [comment]
Can you verify that's actually where the versions folder is?

**Comment by Ari-RERA-43** [comment]
Can you send an image of the OptiFine installer with the proper directory entered so I can see if there are issues?

Also, when uploading images, upload them directly to GitHub. The site you used makes it difficult to view the images.
