### ISSUE TITLE
Setting to increase the render distance of the sign

### ISSUE THREAD

**Issue by alphasize123** [sp614x/optifine#7276]
Currently, OptiPine automatically cannot see the letters in the sign if they are away from a certain distance.

I want you to create a setting that can change this.

Please let me know if there's a setting. thanks

**Comment by Ari-RERA-43** [comment]
Like making the text smaller when you go past the edge?

**Comment by alphasize123** [comment]
I don't know the content, but if you apply OptiPine, you can't see it if it's about 20 blocks away.
It is very uncomfortable to see images using Unicode.

**Comment by Regnander** [comment]
#1452

**Comment by alphasize123** [comment]
So you're saying you need a 4k monitor after all?

**Comment by KaiAF** [comment]
This depends on screen resolution and FOV
