### ISSUE TITLE
A lot of screen tearing when in full screen using the cpu 

### ISSUE THREAD

**Issue by WickedOddball525** [sp614x/optifine#7278]
## Steps to Reproduce
1. What do you do...
2. ...to find this bug?

## OptiFine Version
 1.19.3 l2 pre3

## Installation Method
 I used the standalone installer

## Additional Information

This only happens when I use the integrated card (Intel UHD Graphics) but works perfectly fine using the gpu (Nvidia MX230)

**Comment by omerien** [comment]
F3 debug screenshot ? Latest.log ?

**Comment by KaiAF** [comment]
Not enough information. Likely just an issue with the iGPU
