### ISSUE TITLE
[1.19][bug]Optifine Breaks Botania

### ISSUE THREAD

**Issue by Crystallyne** [sp614x/optifine#7294]
SOLVED: I failed to realize that Optifine is not updated for Forge 43.2.0. Botania requires a more updated version of Forge, so the two mods simply aren't compatible.

## Description of Issue
With Optifine, Botania no longer functions properly.

## Steps to Reproduce
1. Have both Optifine and Botania installed.
2. Set up a Mana Spreader, Mana Pool, and Mana Generating Flowers. (I used the ones that work with water, something like Hydrangea flowers, but spelled differently.)
3. The Mana Generating Flowers appear to be working, making the correct noises. I can't tell if the Mana Spreader is actually "picking up" the mana from the flowers, but it definitely isn't "shooting" the mana into the Mana Pool.

(Additionally, if you're holding a Botania wand, you see no User Interface when holding it over the Mana Spreader or Mana Pool.)

## OptiFine Version
Version 1.19.2_HD_U_I1

## Installation Method
I downloaded it and placed the JAR manually into my Mods folder.

## Fabric/Forge Version
Forge 43.2.0

## Other Installed Mods
I took a [screenshot](https://i.imgur.com/s5I4Tsx.png) of my Mods folder, as it isn't super long. But here's the list:
Appleskin
Architectury
AutoRegLib
Balm-Forge
BetterControls
Botania
Cloth-Config
Comforts
ConnectedGlass
ConstructionWand
Controlling
CoordinatesDisplay
CraftingTweaks
Curios
ElevatorID
FastLeafDecay
JEI
JustEnoughResources
Light-Overlay
MouseTweaks
Neat
Patchouli
Quark
ShutUpExperimentalSettings
SuperMartijn642configlib
SuperMartijn642corelib
TheOneProbe

## Log Files/Crash Reports
Added my [latest.log](https://github.com/sp614x/optifine/files/10903676/latest.log) file. This issue does not cause my game to crash, so not sure if it will help, but trying to help as much as I can.

## F3 Debug Screenshot
This screenshot was taken with ONLY Optifine and Botania installed, on the same version of Forge and Minecraft.
![2023-03-06_14 56 26](https://user-images.githubusercontent.com/32418385/223275597-b278e1d7-d912-4dc1-9faa-82d80059cfad.png)

## Prior Testing
I have tested this with ONLY Botania installed, as well as with ONLY Botania and Optifine installed. Please see the screenshots below:
![2023-03-06_15.01.18.png](https://user-images.githubusercontent.com/32418385/223276723-809304d4-2809-4c03-b5d8-1d8630757f00.png) This screenshot shows what it should look like. I ONLY have Botania installed, here.
![2023-03-06_15.04.34.png](https://user-images.githubusercontent.com/32418385/223276741-074ea637-366d-474b-921c-480ab9929777.png) This screenshot shows what I'm seeing when I only have Botania and Optifine installed. The onscreen information is completely missing, and the mana spreader no longer shoots mana into the mana pool.
![2023-03-06_15.01.42.png](https://user-images.githubusercontent.com/32418385/223276993-4a602528-8cd9-434d-80d6-67f6f84c26ca.png) I don't know if it would help at all, but  this is a screenshot of the Debug screen when I ONLY have Botania installed.

## Additional Information
I humbly apologize if this has already been reported as an issue, here. I did do a search, and was really surprised when I found no reports at all, especially when I found [this post on Reddit](https://www.reddit.com/r/botania/comments/10um0ov/why_is_the_ui_not_show_up/) that indicated Optifine is breaking Botania for 1.19, and is already a known issue to some in the community. I hope I have been able to provide enough information to fix this problem, and will try to add anything else if needed.

PS: Edits were to fix formatting, and add a little bit more information for clarification.

**Comment by omerien** [comment]
OptiFine 1.19.2 isn't yet compatible with Forge 43.2, but only with Forge 43.1.52, as stated [here](https://optifine.net/downloads).
Please redo your bug report, with tests in Forge 43.1.52.

**Comment by Crystallyne** [comment]
Ah, my apologies, I somehow completely missed that. Botania requires an updated version of Forge in order to work, so the two mods require two different versions.

I will say that Optifine seems to be working just fine for me in all other respects. The main reason I wanted it was for the Fresh Animations resource pack to function correctly. The only conflict I've found is with Botania's mana generation. But it's good to know that there might be other issues that I hadn't noticed before.

Thanks for letting me know. I'll update my original post, and close this issue.
