### ISSUE TITLE
[Bug] Optifine breaks Security craft mod 1.19.3

### ISSUE THREAD

**Issue by Theuslo0** [sp614x/optifine#7296]
## Description of Issue
Optifine makes itens on Security craft mod useless because you cant read or use the item

## Steps to Reproduce
1. Put an Keypad door per example or any other item that uses codes to use
2. Right click on the door
3. Now you cant open or use because you cant read or simple digit the code

## OptiFine Version
1.19.3 HD U I2 pre5

## Installation Method
dropped the JAR file into "mods" folder 

## Fabric/Forge Version
Forge 44.1.21

## Other Installed Mods
The problem happen with only Optifine + Security craft mod, without any shaders, resources packs or any other mods installed

## Prior Testing
If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   - Only OptiFine and Forge - A: Yes, It does
     
- Does this happen in Vanilla without OptiFine?
A: No, it does not 

## Bug image

![Captura de tela 2023-03-07 133620](https://user-images.githubusercontent.com/127230812/223488968-a55b702f-dfff-43ce-9e78-171ff5c460da.png)

**Comment by omerien** [comment]
Does the bug still happens in the Forge recommended version for OptiFine, Forge 44.1.17 ? (as stated [here](https://optifine.net/downloads))

**Comment by Theuslo0** [comment]
I just tried it now with the recommended forge version 44.1.0 the problem doesn't happen. Thanks!!
