### ISSUE TITLE
[1.9, 1.9.2, Shaders] Ender Portal Artefacts & The End Lighting Flickering

### ISSUE THREAD

**Issue by AnEvilVegetable** [sp614x/optifine#73]
Hello,

When using shaders the lighting in The End is flickering a lot and the portal to the dimension is a huge mess.

The only way to fix it is to turn shaders off. Multiple shaders (SEUS, MrMeep's and so on... have been tested with the same result. Resource Packs do not impact this. I'm not running any mods except for the Optifine and its merged Shaders Mod, it's completely vanilla.

**Comment by sp614x** [comment]
OptiFine allows the shader pack to control which shaders are used in the different dimensions.

# Shaders can be separated by world dimension by placing them in folder "/shaders/world<id>" where "id" is the world dimension.
# When the world folder is present the shaders will be loaded only from there ignoring the default folder.
# Creating an empty world folder effectively disables the shaders for this world dimension.
# Mod world dimensions should also work.
# Only ".vsh" and ".fsh" files are loaded from the dimension folder.
# Example
#   /shaders         - default shaders
#   /shaders/world-1 - nether shaders
#   /shaders/world1  - end shaders

**Comment by AnEvilVegetable** [comment]
Ah, I see! I did not know that! Thanks. I've disabled shaders in the nether and end because it's almost pitch black in the nether and the lighting like mentioned behaves rather strange in the end. A screencap of the portal issue I'm talking about is here:

http://imgur.com/wrRBlaf

**Comment by sp614x** [comment]
Most shader packs have problems with end portals and show them fully black.
