### ISSUE TITLE
Sandstone causes a crash; "Tesselating block model"

### ISSUE THREAD

**Issue by Mrminesheeps** [sp614x/optifine#730]
A crash seems to occur with sandstone when blocks from a variety of mods (including open modular turrets, extra utilities 2, etc.) are placed next to it. one example that occurred was I had placed a tier 2 turret base on a piece of sandstone, and I crashed right thereafter. 
[crash-2017-06-26_11.22.54-client.txt](https://github.com/sp614x/optifine/files/1104296/crash-2017-06-26_11.22.54-client.txt)

here is one crash report in relation to the sandstone crash.
It seems to happen to many people, on many different computers and OS's, and has not been fixed. It'd be greatly appreciated if you could look into this, as it gets quite frustrating having to uninstall optifine just to leave the area or delete the block at fault, then reinstall optifine so I can actually play.

**Comment by sp614x** [comment]
The crash is in ExtraUtilities2:
```
java.lang.NullPointerException: Tesselating block model
	at com.rwtema.extrautils2.backend.model.PassthruModelBlock.func_188616_a(PassthruModelBlock.java:37)
	...
```

**Comment by Mrminesheeps** [comment]
but if it was extra utilities, then how is it the same crash with the same error code occurs when I place a block from open modular turrets?

**Comment by sp614x** [comment]
The reported crash is inside the PassthruModelBlock from ExtraUtils2. 
The Modular Turrets may crash in a different way.
