### ISSUE TITLE
[Bug] CIT Not Working On 1.19

### ISSUE THREAD

**Issue by MMT007** [sp614x/optifine#7304]
## Description of Issue

I Was Trying to Make an Item Change Its Texture, But When I Got To Testing It, Optifine Didn't Render My Texture Into The Item

## Steps to Reproduce
Using CIT As Normal

## OptiFine Version

HD I1 Ultra

## Installation Method

Placed Jar Into Mods Folder

## Fabric/Forge Version

Forge 43.2.0

## Other Installed Mods

Freecam
Inventory Hud+
Shulkerbox Tooltip
Neat
Xaeros Minimap
Advanced Xray

## Log Files/Crash Reports

[latest.log](https://github.com/sp614x/optifine/files/10975113/latest.log)

## F3 Debug Screenshot

![2023-03-14_20 32 25](https://user-images.githubusercontent.com/67060689/225180157-d4d64a97-ea22-442b-a175-79dc428d4d12.png)

**Comment by Ari-RERA-43** [comment]
CIT is not supported in 1.19.3 yet. In the future, test without any other mods or resource packs.

**Comment by MMT007** [comment]
Im Using 1.19.2 As Seen On The Minecraft Screenshot

**Comment by Ari-RERA-43** [comment]
> Im Using 1.19.2 As Seen On The Minecraft Screenshot

You’re using an old OptiFine version for 1.19.2. In any case, close this issue because it’s already very well known.

**Comment by MMT007** [comment]
> > Im Using 1.19.2 As Seen On The Minecraft Screenshot
> 
> You’re using an old OptiFine version for 1.19.2. In any case, ~~close this issue because it’s already very well known. ~~
> 
> Edit: Oh nvm, sorry for the confusion and ignore that. That is an old version of OptiFine for 1.19.2 though.

So.. The Cit Is Still Not Working.. despite Updating the game.

**Comment by SeaOfPixels** [comment]
This happens when using an old Forge version, update your Forge version from the "recommended" to the "latest" instead. This should fix invisible CIT items.

**Comment by MMT007** [comment]
> This happens when using an old Forge version, update your Forge version from the "recommended" to the "latest" instead. This should fix invisible CIT items.

The Thing is. The Items are not Invisible, The Textures Are Just Not being replaced. But I'll Try Changing The Forge Version, Thanks for the Advice!

**Comment by MMT007** [comment]
> This happens when using an old Forge version, update your Forge version from the "recommended" to the "latest" instead. This should fix invisible CIT items.

The Recomended Forge Versoin is 43.2.0 wich is the same forge version that I used when i took the F3 Screenshot

**Comment by sp614x** [comment]
Fixed in latest 1.19.4 preview.
The 1.19.3 versions will be updated later.
