### ISSUE TITLE
[1.19.4 - Crash] Pressing F3+V crashes the game.

### ISSUE THREAD

**Issue by Lolothepro** [sp614x/optifine#7306]
## Description of Issue
Pressing F3+V crashes the game.

## Steps to Reproduce
1. Press F3+V

## OptiFine Version
1.19.4 PRE 1 I3

## Installation Method
Prism Method

## Log & Crash report
[latest.log](https://github.com/sp614x/optifine/files/11009412/latest.log)
[crash-2023-03-18_20.29.06-client.txt](https://github.com/sp614x/optifine/files/11009413/crash-2023-03-18_20.29.06-client.txt)

**Comment by TryhardDoge** [comment]
I can confirm this happens on both pre2 and pre3

**Comment by sp614x** [comment]
Fixed, coming in next preview.
