### ISSUE TITLE
Extremely Low FPS

### ISSUE THREAD

**Issue by lzdg** [sp614x/optifine#7307]
## Description of Issue
Low FPS only when using shaders.

## Steps to Reproduce
1. Use shaders.

## OptiFine Version
OptiFine HD U I3 pre1 (1.19.4)

## Installation Method
Installed using standalone JAR executable directly from the OptiFine website.

## Log Files/Crash Reports
[latest.log](https://github.com/sp614x/optifine/files/11009530/latest.log)

## F3 Debug Screenshot
![2023-03-18_15 36 28](https://user-images.githubusercontent.com/8569686/226137966-4730d409-3276-4971-b162-8443e073e485.png)

## Prior Testing
This does not happen in OptiFine without shaders and the issue is persistent across multiple shaderpacks.
Resourcepack is irrelevant.
This is not an issue in the latest preview version for 1.19.3.
Adjusting RAM has no affect.

## Additional Information
I'm playing on PopOS (Nvidia version) Linux with the following specs:
Nvidia RTX 4070 Ti
Intel i7 13700k
Corsair Vengeance 32GB

I typically get 144 FPS with my shaderpack of choice, Complementary  (frame limit set to monitor refresh rate).

**Comment by Lolothepro** [comment]
Currently, Minecraft does not seem to use your Nvidia RTX 4070 Ti.

**Comment by lzdg** [comment]
> Currently, Minecraft does not seem to use your Nvidia RTX 4070 Ti.

I noticed this and fixed that, however I'm still getting relatively lower FPS and as I said this wasn't an issue in the previous version.

**Comment by sp614x** [comment]
The operating system (graphics driver) decides which graphics chip to use (dedicated or integrated). 
In this case it runs with Intel integrated graphics, which is too slow for shaders.
Check the driver configuration for possible settings.
OptiFine can't fix this.
