### ISSUE TITLE
1.12 Optifine causing game MAJOR lag

### ISSUE THREAD

**Issue by hbanana123** [sp614x/optifine#731]
I have never had a problem with optifine before, but the 1.12 optifine is causing my game to lag so much. Without the optifine, I have pretty good fps and no problems. I don't know what's wrong.

**Comment by sp614x** [comment]
You can try:
- VSync -> OFF
- Smooth FPS -> OFF

**Comment by Minecrafter112** [comment]
Im having the same problem but those options are off and the game gets around 30 frames. When I don't use Optifine though, I get around 130 frames, but with constant hiccups that optifine fixed

**Comment by sp614x** [comment]
Video Settings -> Other -> Reset Video Settings ?

**Comment by CraftyTar** [comment]
> Video Settings -> Other -> Reset Video Settings ?

Im so glad I found this. you helped my problem. thank you so much it had been bugging me for ages, I had updated my optifine to 1.16.3 to 1.16.5 and it just wouldnt stop lagging even when  I went back to 1.16.3 so Im so glad I found this and fixed my little problem thank you so much

**Comment by KaiAF** [comment]
No response from the author of the issue and it's an outdated version.
