### ISSUE TITLE
[1.19.3/1.19.4] CIT using custom models not working

### ISSUE THREAD

**Issue by SeaOfPixels** [sp614x/optifine#7311]
## Description of Issue
Custom item textures that have a custom model render as missing textures. I am aware that this is a known bug, however there wasn't a report here on github so I thought it would be helpful to make one. Please let me know if this report is undesired due to the bug being known, and I will close it. Also, it seems CIT armor models have been fixed in 1.19.4 l3 pre1, they were previously missing textures in the 1.19.3 previews.

## OptiFine Version
1.19.3 I2 pre2, 1.19.4 l3 pre1

![2023-03-19_00 36 00](https://user-images.githubusercontent.com/62183036/226160979-50078f4c-03e8-488e-8b8e-c977aab647b8.png)
1.19.4 l3 pre1 only:
![2023-03-19_00 36 46](https://user-images.githubusercontent.com/62183036/226161359-b4bcb043-00a9-46ba-bf64-53934c4f8d43.png)

**Comment by sp614x** [comment]
Should be fixed in latest preview.
