### ISSUE TITLE
[1.19.3/1.19.4] Custom grid colormaps are incorrect

### ISSUE THREAD

**Issue by SeaOfPixels** [sp614x/optifine#7312]
## Description of Issue
Custom grid colormaps use the incorrect biome IDs. I am aware that this is a known bug, however there wasn't a report here on github so I thought it would be helpful to make one. Please let me know if this report is undesired due to the bug being known, and I will close it.

## OptiFine Version
1.19.3 I2 pre2, 1.19.4 l3 pre1

1.19.2 I1:
![2023-03-19_01 05 25](https://user-images.githubusercontent.com/62183036/226162006-59acb515-bec3-423d-b85a-70e0548a50db.png)
1.19.3 I2 pre2, 1.19.4 l3 pre1:
![2023-03-19_01 02 39](https://user-images.githubusercontent.com/62183036/226162010-ba24bc63-a159-4a8d-955f-66ebd5e2c548.png)

**Comment by sp614x** [comment]
Which resource pack is this?
