### ISSUE TITLE
Naturual Textures Breaks Shadows

### ISSUE THREAD

**Issue by TryhardDoge** [sp614x/optifine#7313]
Turning on Naturaul Textures makes shadows not appear as expected

## Steps to Reproduce
Use Optifine 1.19.4 Pre2 and look at shadowed blocks

## OptiFine Version
Optifine1.19.4Pre2

## Installation Method
I used forge

## Fabric/Forge Version
Forge

## Other Installed Mods
Xearos Minimap and Xearos Worldmap, though i have pinpointed the issue to optifine, im 99% sure its not my other mods

## Log Files/Crash Reports
Nope! Doesnt Crash just shows weird shadows

## Prior Testing
 Xearo's Minimap and Worldmap, are not causing issues
Here are SS to show it
WIth Naturual Tex
![2023-03-19_08 05 44](https://user-images.githubusercontent.com/105992137/226175218-4407bf4f-aae7-4e33-a15f-28a4f401903f.png)
![2023-03-19_08 18 23](https://user-images.githubusercontent.com/105992137/226175141-26c0d557-6579-4765-b10a-b99876717b43.png)
![2023-03-19_08 05 47](https://user-images.githubusercontent.com/105992137/226175142-18f09664-3545-488e-abdb-321a086c735c.png)
Without
![2023-03-19_08 18 06](https://user-images.githubusercontent.com/105992137/226175144-cbd07ae6-754b-41e2-bdfe-7bead399e31e.png)
![2023-03-19_08 18 10](https://user-images.githubusercontent.com/105992137/226175145-53cb4251-105c-4048-a0d1-2b97706fd19c.png)

**Comment by TryhardDoge** [comment]
I can confirm the same issue on pre3
F3
![2023-03-19_09 19 52](https://user-images.githubusercontent.com/105992137/226177804-5aeba5ee-3eaf-42be-bf63-7ce050386a50.png)
Without
![2023-03-19_09 19 49](https://user-images.githubusercontent.com/105992137/226177800-c3b84c41-8492-4264-90b3-d4241703c23e.png)
With
![2023-03-19_09 19 36](https://user-images.githubusercontent.com/105992137/226177795-e6a0c8b6-234e-45c3-bdd5-198b49d26c7d.png)

**Comment by TryhardDoge** [comment]
That's strange, might be a gpu rendering error, my gpu is quite old.

**Comment by sp614x** [comment]
Does it happen when OptiFine is running standalone?
When running with Forge only (no other mods)?
Single-player, multi-player?

**Comment by xAli0yx** [comment]
Yes, it already duplicated my issue #7285

**Comment by TryhardDoge** [comment]
> Does it happen when OptiFine is running standalone? When running with Forge only (no other mods)? Single-player, multi-player?

I can't be sure now but I will test later

**Comment by xAli0yx** [comment]
Yes, all any. It happens to me, if I turn on and off the nature texture, I already tested that I used the singleplayer and multiplayer, it likes to same 1.19.3 and 1.19.4 so.

**Comment by TryhardDoge** [comment]
Issue has been fixed in pre6
