### ISSUE TITLE
[Bug] Black glass pane make me see through chest ect.

### ISSUE THREAD

**Issue by dolnar** [sp614x/optifine#7314]
## Description of Issue
Glass pane make me see through chest and shulker

## Steps to Reproduce
1. I dropped black glass pane on the floor next to my chest and shulker, and with that i can see through them

## OptiFine Version
OptiFine HD U I3 pre3

## Installation Method
I used the standalone included installator.

## F3 Debug Screenshot

![2023-03-19_15 59 03](https://user-images.githubusercontent.com/44147660/226184544-67a4d312-0698-4151-80c3-73262d565678.png)

## Prior Testing
It doesn't happen with vanilla minecraft.

## Additional Information
I use a faithfull ressource pack alongside optifine.

**Comment by TryhardDoge** [comment]
Does it occur without the resource pack? Might be a problem with faithfully textures

**Comment by sp614x** [comment]
You are using internal shaders. They are for testing only, not for gameplay.
Either disable shaders or use a shaderpack.
