### ISSUE TITLE
CTM not working since Optifine update

### ISSUE THREAD

**Issue by JonasCiss** [sp614x/optifine#732]
I updated Optifine 1.10.2_C1 to E3 today, However CTM textures are not working anymore. I made a test version of my resourcepack to find the bug but I can't resolve it.

[Collection Complete CTM Test.zip](https://github.com/sp614x/optifine/files/1110561/Collection.Complete.CTM.Test.zip)

**Comment by sp614x** [comment]
Fixed, please redownload Optifine E3 for 1.10.2.
