### ISSUE TITLE
[1.19.4] Crash with Forge 45.0.22

### ISSUE THREAD

**Issue by fuzzyfurry069** [sp614x/optifine#7322]
## Steps to Reproduce
Anytime I load into my server running the latest optifine i receive a crash message. 

## OptiFine Version
OptiFine HD U I3 pre7 to OptiFine HD U I3 pre9

## Installation Method
I did drag and drop for both my server and installation

## Fabric/Forge Version
Forge 45.0.22

## Other Installed Mods
AmbientSounds
Appleskin
BlockUI
Doubledoors
Excavar
Gravestone
journymap
treeharvester
Useful Backpacks
Vanilla Plus Tools
Rex's Additional Structures
Curios
Geckolib
Citadel
Collective
CreativeCore

## Log Files/Crash Reports
Error Message: 
java.lang.NoSuchMethodError: 'void net.minecraftforge.client.ItemDecoratorHandler.render(net.minecraft.client.gui.Font, net.minecraft.world.item.ItemStack, int, int, float)'

Crash log in a Pastebin
https://pastebin.com/dQ9sEUay

## F3 Debug Screenshot
Can't load into server to get debug screenshot.

## Prior Testing
Without Optifine I encounter no issues.

If you've installed using Forge/Fabric:
- Does this happen without other mods installed?  Yes
   - Only OptiFine and Forge

- Does this happen in OptiFine standalone?
- No
- Does this happen in Vanilla without OptiFine?
- No
- Have you tried using a binary search to find which mods cause this issue?
   - To find conflicting mods, split your mods into 2 groups (not including OptiFine/OptiFabric, obviously). Remove one group, and test in-game. Keep the group that has the problem, and repeat until no more mods can be removed without the issue disappearing.
   - Does the issue still happen with only the remaining mods installed?
      - Forge/Fabric and remaining mods, without OptiFine -->

## Additional Information

Running a standalone optifine install and joining a forge server does not appear to cause any crashes. There could be a mod issue.

**Comment by sp614x** [comment]
Latest Forge #45.0.22 is not compatible with OF.
To be fixed in next preview.
