### ISSUE TITLE
[BUG] Crash on joining/creating a world (Forge 40.2.1 1.18.2)

### ISSUE THREAD

**Issue by SkyKingPX** [sp614x/optifine#7329]
## Description of Issue
Game crashes if you open a world

## Steps to Reproduce
1. Install OptiFine
2. create/join a world

## OptiFine Version
OptiFine HD U H7

## Installation Method
dropped .jar

## Fabric/Forge Version
40.2.1

## Other Installed Mods
IN CRASH REPORT

## Log Files/Crash Reports
Minecraft Launcher: The game crashed whilst exception in server tick loop
Error: java.lang.NoSuchMethodError: 'void net.minecraft.server.level.DistanceManager.addRegionTicket(net.minecraft.server.level.TicketType, net.minecraft.world.level.ChunkPos, int, java.lang.Object, boolean)'

[crash-2023-03-25_09.37.17-server.txt](https://github.com/sp614x/optifine/files/11068408/crash-2023-03-25_09.37.17-server.txt)

**Comment by omerien** [comment]
OptiFine, as stated on the download page, only supports the Forge 40.0.24 for 1.18.2 H7. Please retry your bug with this version of Forge. You can also download the latest preview version for 1.18.2, H9 pre3, which supports Forge 40.2.1.

**Comment by SkyKingPX** [comment]
Thank you I will try it

**Comment by SkyKingPX** [comment]
It is now working, thanks
