### ISSUE TITLE
1.12 Forge + Optifine crash

### ISSUE THREAD

**Issue by Raf2k** [sp614x/optifine#733]
Game crashes on start when I'm using latest Forge + latest optifine.
Sorry if duplicate, but I don't found any related issues...
[crash-2017-06-29_11.56.30-client.txt](https://github.com/sp614x/optifine/files/1111258/crash-2017-06-29_11.56.30-client.txt)

**Comment by hhiru** [comment]
Same problem here. Latest recommended version of Forge and Optifine 1.12 C2 and C3

**Comment by sp614x** [comment]
Preview C4 for 1.12 is out
- compatible with Forge #2387
