### ISSUE TITLE
[RP] Chests have a strange texture with some resource packs.

### ISSUE THREAD

**Issue by Lolothepro** [sp614x/optifine#7330]
## Description of Issue
Chests have a strange texture with some resource packs.

## Steps to Reproduce
1.Apply Sama Faithful
2.Place a chest

## Installation Method
Prism Method

## Screenshot

![2023-03-24_20 46 32](https://user-images.githubusercontent.com/68275908/227707693-ff3e53f3-bf23-4df8-aea4-20bc1f62ca2e.png)

**Comment by omerien** [comment]
Does the bug still happens in Vanilla with the same texture pack, and if not, please provide us an image of the default behavior.

**Comment by Lolothepro** [comment]
> Does the bug still happens in Vanilla with the same texture pack, and if not, please provide us an image of the default behavior.

It's normal
Why report a Minecraft Vanilla bug on the Optifine Github?

**Comment by toutlamer** [comment]
Because I want to see if the bug is linked with OptiFine or not

**Comment by toutlamer** [comment]
And please send the normal screenshot I personally don’t see the problem

**Comment by Lolothepro** [comment]
> Because I want to see if the bug is linked with OptiFine or not

But it is related to Optifine, since it is an Optifine bug

**Comment by Lolothepro** [comment]
Note: The reason I reported a bug on the Optifine Github is because I had already tried it with Minecraft Vanilla.
If it had happened with Minecraft Vanilla/other mods that do the same thing as Optifine, I would have obviously reported the bug to the resource pack creator...

**Comment by Lolothepro** [comment]
Vanilla:
![2023-03-27_15 05 15](https://user-images.githubusercontent.com/68275908/227947271-99093edd-aba7-43be-a8d9-8c78f3d0cb57.png)
Optifine:
![2023-03-27_15 06 47](https://user-images.githubusercontent.com/68275908/227947286-e6423123-929f-4749-941e-c53b1c13dfd0.png)

**Comment by sp614x** [comment]
Vanilla doesn't have CEM so it isn't loading the custom chest model.
What model is the resource pack using and is it updated to 1.19.4?
There have been some changes in the chest rendering in 1.19.x.

**Comment by ewanhowell5195** [comment]
this is not a bug. the CEM model changed in 1.19.3. you need to update your model
