### ISSUE TITLE
Double trapped chest CEM using the Christmas chest

### ISSUE THREAD

**Issue by MushirMickeyJoe** [sp614x/optifine#7331]
Resource pack: mine, Barely Default - https://www.curseforge.com/minecraft/texture-packs/mickey-joes-relatively-improved-default/files/4446803

Title. My double trapped chest CEM uses the double Christmas chest texture for no obvious reason.
None of my files reference the Christmas chest. It just seems completely random, and I don't think I can fix it so it must be a bug.
![image-12](https://user-images.githubusercontent.com/31923214/227712722-e7f8a66e-87a4-4dcf-a2d0-e83b97a7b164.png)

**Comment by omerien** [comment]
What version are you using on the screenshot ? Did it worked on previous versions ? Can you send us a screenshot of the expected behavior ?

**Comment by MushirMickeyJoe** [comment]
Turned out my UV had shifted off the UV grid with crazy high coordinates, and chests are on an atlas so it just shifted to the christmas chest. Interesting, but user error. Sorry
