### ISSUE TITLE
[1.19.4/1.20.1 - FAST RENDER - SHADERS] Text displays are not rendered correctly with all shaders.

### ISSUE THREAD

**Issue by Lolothepro** [sp614x/optifine#7333]
## Description of Issue
Text displays are not rendered correctly with some shaders.

## Steps to Reproduce
1. Summon a text display using this command
	+ `/summon minecraft:text_display ~ ~ ~ {text:'{"text":"Did you know that France is the best country in the world?","color":"red"}',billboard:"center",background:4291598592L}`
2. Apply this shader: https://github.com/Lolothepro/maples-retro-extravaganza/tree/1+2%3D3

## OptiFine Version
OptiFine 1.19.4_HD_U_I3_pre11

## Installation Method
Prism Method

## F3 Debug Screenshot

![2023-03-26_17 54 43](https://user-images.githubusercontent.com/68275908/227787763-97daffb1-0e5c-42ba-9080-8bb0e6d0782d.png)

## Screenshot

The text displayed should look like this:

![2023-03-26_17 57 36](https://user-images.githubusercontent.com/68275908/227788013-72efa442-6c14-40fb-bcfe-857434185f70.png)

But with Optifine it looks like this:

![2023-03-26_17 59 24](https://user-images.githubusercontent.com/68275908/227788103-621eaee7-c331-4ba4-b343-3ff0e266dbe2.png)

**Comment by omerien** [comment]
You just duplicated your own issue (#7309), since this one is more recent, I'd suggest you delete your old one.

**Comment by Lolothepro** [comment]
I will close this bug report, but if the Kappa bug is fixed, but still occurs, I will reopen it.

**Comment by Lolothepro** [comment]
Ok, it's not the same bug

**Comment by Lolothepro** [comment]
Fast Render ON:
![2023-04-03_20 44 12](https://user-images.githubusercontent.com/68275908/229598868-857080ca-95ea-47f6-a25d-d83bea91c593.png)
Fast Render OFF:
![2023-04-03_20 44 06](https://user-images.githubusercontent.com/68275908/229598905-b1f76dbd-35a4-4983-b1d9-2c1246c5f084.png)

**Comment by Lolothepro** [comment]
it would be good to have this fixed before the release of Optifine for Minecraft 1.20.1

**Comment by sp614x** [comment]
Tested with Sildurs Vibrant and SEUS Renewed, text display works correctly.

![image](https://github.com/sp614x/optifine/assets/16635441/23ff4ccc-ee67-4047-8657-7a30cf7b9a81)

![image](https://github.com/sp614x/optifine/assets/16635441/14c7d0ec-99ff-4321-b0af-c413e464b14b)

This is a shader pack problem.

**Comment by Lolothepro** [comment]
Seus Renewed + Fast Render:
![2023-06-26_17 21 54](https://github.com/sp614x/optifine/assets/68275908/a94ecae2-b6c5-4052-887b-c66590688830)

SEUS Renewed without Fast Render:
![2023-06-26_17 22 02](https://github.com/sp614x/optifine/assets/68275908/30170d75-22a2-4642-9d0f-da96c000ca72)

**Comment by sp614x** [comment]
Is this 1.19.4 or 1.20.1?
I can't reproduce it in 1.20.1 with or without Fast Render.

**Comment by Lolothepro** [comment]
> Is this 1.19.4 or 1.20.1? I can't reproduce it in 1.20.1 with or without Fast Render.

1.20.1

**Comment by Lolothepro** [comment]
![image](https://github.com/sp614x/optifine/assets/68275908/178cd12f-2e5a-4b07-9bc5-9da51b9d3204)

**Comment by sp614x** [comment]
Managed the reproduce a difference with Fast Render ON. At some vieweing angles the text background is missing (BSL v8.1).

**Comment by Lolothepro** [comment]
The bug occurs even more frequently with OptiFine 1.20.1_HD_U_I6_pre3
