### ISSUE TITLE
Optifine Can't Run With Xaeros Minimap

### ISSUE THREAD

**Issue by LegoCollecter14** [sp614x/optifine#734]
It Was Fine Last version But Its Broken Now Here Is The Crash Report.
Everything Is Up To The Last Stable Release
[crash-2017-06-29_12.25.57-client.txt](https://github.com/sp614x/optifine/files/1112813/crash-2017-06-29_12.25.57-client.txt)
[crash-2017-06-29_12.28.49-client.txt](https://github.com/sp614x/optifine/files/1112816/crash-2017-06-29_12.28.49-client.txt)
[crash-2017-06-29_12.35.20-client.txt](https://github.com/sp614x/optifine/files/1112814/crash-2017-06-29_12.35.20-client.txt)
[crash-2017-06-29_12.39.21-client.txt](https://github.com/sp614x/optifine/files/1112815/crash-2017-06-29_12.39.21-client.txt)

**Comment by LegoCollecter14** [comment]
I Really Hope This Gets Fixed Soon 
I Posted Here Because I Ran Forge Without Mods / And Without Optifine And It Ran Fine.
The Crash usually occurs right before it finishes

**Comment by sp614x** [comment]
Preview C4 for 1.12 is out
- compatible with Forge #2387
