### ISSUE TITLE
[1.19.3/1.19.4/1.20 Feature] Support for Camel/Sniffer CEM & Random Entities

### ISSUE THREAD

**Issue by SeaOfPixels** [sp614x/optifine#7348]
## Description of the new feature
I suspect this will come eventually, but these 1.20 features are already able to be enabled with the experimental pack, so if it's possible to  allow CEM & Random Entities support for Camels/Sniffers for 1.19.4 that would be great.

## OptiFine version
1.19.3 I3, 1.19.4 l4, OptiFine 1.20-pre4_HD_U_I5_pre1, OptiFine 1.20_HD_U_I5_pre3, OptiFine 1.20.1_HD_U_I5_pre6, OptiFine 1.20.1_HD_U_I5_pre7

**Comment by ewanhowell5195** [comment]
this can be closed. they are now added
