### ISSUE TITLE
Suggestion: Option to change emails

### ISSUE THREAD

**Issue by games4681** [sp614x/optifine#7362]
I want you to add new options to the optifine account:
1. Option to change email if you lost access through security questions
2. Add 2FA to secure the optifine account
3. Option to change password when I logged in
4. option to change email when i logged in
Please do the following it is important. Thanks.

**Comment by games4681** [comment]
sp614x solved my problem so i closed this issue

**Comment by Bachsau** [comment]
Happy for you, but that doesn't solve the problem in general.
