### ISSUE TITLE
Can I change Loading screen Mojang logo?

### ISSUE THREAD

**Issue by Gametron303** [sp614x/optifine#7369]
I tried to find information online about changing it but only found outdated guides. I can't figure out if I can change it in the resource pack or not? Thank you in advance.

**Comment by Regnander** [comment]
According to this [bug ticket](https://bugs.mojang.com/browse/MC-227719), the Mojang logo can no longer be overridden with `\assets\minecraft\textures\gui\title\mojangstudios.png` in a resource pack since 1.17.

**Comment by Dewaxel** [comment]
> According to this [bug ticket](https://bugs.mojang.com/browse/MC-227719), the Mojang logo can no longer be overridden with `\assets\minecraft\textures\gui\title\mojangstudios.png` in a resource pack since 1.17.

That's awesome, but this IS OptiFine. Changing the logo always worked. This is completely VALID ISSUE. In fact, it stopped working just in 1.19.3, before even in 1.19.2 it worked! And now it still doesn't work in OptiFine 1.20, so it needs to be fixed quickly.

**Comment by sp614x** [comment]
Fixed, coming in next 1.20.1 preview.

**Comment by Dewaxel** [comment]
> Fixed, coming in next 1.20.1 preview.

That was quicker than I expected, you're golden ❤
