### ISSUE TITLE
CEM & CIT Bug report transparent trident texture being black

### ISSUE THREAD

**Issue by TheOneMunch** [sp614x/optifine#7381]
So basically, I want to make a custom trident model that changes into a wooden stake when given the right name. Everything has been working up until now by placing the regular trident model and the stake model over one another. But in-game the parts of the texture that are meant to be transparent are instead black. I've already tried it on a fox, and there it worked flawlessly with to transparent textures being black.

## Steps to Reproduce
1. Use blockbench to make a cem model for the trident overlaying the regular model and the custom model each with their own part of the uv texture.
2. Make different textures depending on what model you want active. 
3. Use CIT to make name-dependant variants where each part of the texture is transparent in one of the variants.
4. Go in-game, and see that the textures that are supposed to be transparent are instead black, the same way a shulkers head turns black when you give it a transparent texture.

Optifine for 1.19.4

## Installation Method
JAR file into "mods" folder

## Fabric/Forge Version
Forge for 1.19.4

## Other Installed Mods
Worldedit

## F3 Debug Screenshot

![image](https://github.com/sp614x/optifine/assets/118776408/953f1540-af4b-4e66-a819-4364a3f1847a)

If you've installed using Forge/Fabric:
   - Only OptiFine and Forge
- Does this happen without any mods at all?
   - Only Forge/Fabric by itself.

## Additional Information
I am somewhat scared that the problem lies with minecraft's use of the trident model/texture, and therefor is not a simple fix, but I couldn't find this issue anywhere online or in an faq, so that's why I posted this.

**Comment by ewanhowell5195** [comment]
this is not a bug and is how the trident renders. you can fix this by modifying the resource packs shaders, but i cannot help you with that
