### ISSUE TITLE
[SUGGESTIONS] Change entity's texture based on data tags (For RandomMobs) / Full compatibily with CEM and all the feature of RandomMob 

### ISSUE THREAD

**Issue by HRudyPlayZ** [sp614x/optifine#739]
Hello,
I have some suggestions for you, sp614x.

It will be cool if we could change texture based on mob name.

(For exemple:
`mob.nbt.name = "Harry"
`)

Another cool things will be to have a full compatibilty with CEM & RandomMobs features
(like changing model when in a certain biome, in a certain height, or just have random models)

Thanks you for reading my suggestions.
(Sorry for my english)

**Comment by eccentricdevotion** [comment]
+1 for CEM entities with a custom name

**Comment by ZenithRogue** [comment]
Ooh, just became aware of this issue. This was actually released as a feature that for both CEM and entity textures
