### ISSUE TITLE
Unable to have the run effect

### ISSUE THREAD

**Issue by RemixiRemixia** [sp614x/optifine#7393]
When the player tries to run, the effect will not appear, which makes the player confused about if they were running or not.

Version: OptiFine HD U I4

**Comment by Despical** [comment]
If you disable `Dynamic-Fov` option then you won't see the FOV effect. In newer versions there is also a vanilla option called `FOV Effects` which changes effect strength.

**Comment by RemixiRemixia** [comment]
I though that is a bug. Thanks.
