### ISSUE TITLE
[CEM] NBT-Tags not Working on Tile Entities

### ISSUE THREAD

**Issue by heinrich26** [sp614x/optifine#7397]
## Description of Issue
Trying to select a RandomModel based on NBT-Tags doesn't work for tile entities. I tried it with chests and, for example with:
```properties
models.1=2
nbt.1.CustomName=Name
models.2=1
```
but the chest was unaffected! (I tried `exists:true`, but the tag always existed; I tried matching agains the `Items.count` list, but nothing) Using `name.1=Name` (instead of NBT.n.CustomName) and basic random models would however fine.
Doing the same with normal entites does however work, as I demonstrated in #7109.

Could you provide a example NBT-Tag, maybe we're just missing some kind of root element here?

## OptiFine Version
1.19.4 I4

## Additional Log Files/Crash Reports
This might be related; querying nbt Tags on a `player_head` would crash the game. (I guess it's Fabric (1.19.4) related)
[crash-2023-05-25_16.37.25-client.txt](https://github.com/sp614x/optifine/files/11616719/crash-2023-05-25_16.37.25-client.txt)

There is an additional Bug, where the `player_head` doesn't support random/multiple models, instead always the last referenced model in the `.properties` file is used. (probably overriding each other)

**Comment by ewanhowell5195** [comment]
server side nbt is not supported.

changing the chest model/texture based on name is impossible

**Comment by sp614x** [comment]
The chest custom name is not sent to the client until the chest is opened, so it will not work.
The chests the NBT should also have the contents as Item/Slot, but not sure if it is sent to the client.
