### ISSUE TITLE
[SHADERS] 1.20pre4: Minecraft GUI is broken when shaders (AstraLEX) are enabled

### ISSUE THREAD

**Issue by Lolothepro** [sp614x/optifine#7401]
## Installation Method
Prism Method

## Screenshot

![2023-06-03_22 20 59](https://github.com/sp614x/optifine/assets/68275908/fb44c435-3698-4d98-ae65-0055be78ef41)

https://github.com/sp614x/optifine/issues/7375 ?

**Comment by sp614x** [comment]
Resource pack?

**Comment by Lolothepro** [comment]
> Resource pack?

Faithful

**Comment by sp614x** [comment]
The item lighting seems to be wrong
