### ISSUE TITLE
[1.20] Armor Trims Glow whenever the player interacts with any emissive object

### ISSUE THREAD

**Issue by richardatsley** [sp614x/optifine#7402]
## Description of Issue
The title explains most of it, this includes items, armor, blocks, shields, and just anything held or on the player's body that has an emissive property.

## Steps to Reproduce
1. Apply trims to some armor (CIT or not)
2. Hold or put on a piece of armor or item with an emissive texture (usually with the suffix _e)

## OptiFine Version
The latest Optifine 1.20 snapshot (very kind that you put this out before 1.20 btw, glad I could catch this before it had effect :) )

## Installation Method
Jar installation

![2023-06-04_15 49 38](https://github.com/sp614x/optifine/assets/110047599/3507eb0a-864f-476d-bc58-80efcc0cdc22)
![2023-06-04_15 49 40](https://github.com/sp614x/optifine/assets/110047599/9aae773c-f8b4-41cb-be2e-176b90755793)

Here's two images showing the issue at hand :)

## Prior Testing
<!-- If you've installed standalone:
- Does this happen in Vanilla without OptiFine?

No

Thank you for your time :)))

**Comment by richardatsley** [comment]
> Fixed, coming in next preview.

thank you!! :)!

**Comment by sp614x** [comment]
@ManuelXXVI yes, but there has to be a separate texture per material.
For example: `dune_quartz_e.png`

**Comment by ManuelXXVI** [comment]
@sp614x That's great! Out of curiosity, will those separate textures also work with the "tinting" system that the trims use? (Can I leave them in black and white?)
