### ISSUE TITLE
1.20: [F3/GUI] The F3 menu is not rendered correctly

### ISSUE THREAD

**Issue by Lolothepro** [sp614x/optifine#7409]
## OptiFine Version
OptiFine 1.20_HD_U_I5_pre3

## Installation Method
Prism/MultiMC

## Screenshot

Vanilla 1.20:

![2023-06-08_16 57 03](https://github.com/sp614x/optifine/assets/68275908/19126804-c15d-4bcb-b299-be53cc227965)

Optifine 1.20:

![2023-06-08_17 04 09](https://github.com/sp614x/optifine/assets/68275908/3004d007-69d5-4a2e-8bdb-6e575523d541)

Optifine 1.19.4:

![2023-06-08_17 06 12](https://github.com/sp614x/optifine/assets/68275908/9c8ad44d-c12f-4669-a82f-650ee50fd26b)

As you can see, the items in the inventory bar do not interact correctly with the F3 menu.

**Comment by sp614x** [comment]
Fixed, coming in next preview
