### ISSUE TITLE
[1.11.2] crash when using "wearable backpacks" and unloading shaders

### ISSUE THREAD

**Issue by Seth0067** [sp614x/optifine#741]
From https://github.com/copygirl/WearableBackpacks/issues/31

When both Optifine (1.11.2 C3 for me) and Wearable Backpacks are installed, shaders will load/display, but on unloading, the game will crash or textures will not display properly leading to a crash shortly thereafter.

[visual reference](http://imgur.com/a/ADrqk)

A crash log of mine produced by this sort of thing is at [this link](https://pastebin.com/fwrZMDiC)

The backpack mod authors are keeping this open but don't know what to do to fix this, perhaps you can help them out?

**Comment by Seth0067** [comment]
Hi spx614 - in case this helps, I have tracked this behavior down to 1.11.2 Biomes o' Plenty as well.  Loading Optifine C3 and BoP, laoding/unloading shaders will result in this problem.  If you can figure out why this is, may be worth passing onto the Glitchfiend team as well.  They are a pretty big/popular mod, so a fgix on that fronmt will be very impactful.  Thanks.

**Comment by sp614x** [comment]
Tested Forge #2712 + OptiFine E1 for 1.12.2 +WearableBackpacks-1.12.2-3.1.3.
Loading and unloading shaders works fine.

**Comment by sp614x** [comment]
Tested Forge #2588 + OptiFine E1 for 1.11.2 + WearableBackpacks-1.11.2-2.5.0.
Loading and unloading shaders is OK, no crashes.
