### ISSUE TITLE
[1.20] The "Swamp Colors" setting breaks the texture of the cherry trees when it is set to "Off". 

### ISSUE THREAD

**Issue by Lolothepro** [sp614x/optifine#7410]
## Description of Issue
The "Swamp Colors" setting breaks the texture of the cherry trees when it is set to "Off". 

## OptiFine Version
OptiFine 1.20_HD_U_I5_pre3

## Screenshot

On:
![2023-06-09_10 33 41](https://github.com/sp614x/optifine/assets/68275908/a3294d27-eb5b-44a2-8da9-7f43324f3ca3)

Off:
![2023-06-09_10 33 54](https://github.com/sp614x/optifine/assets/68275908/3632a484-2ffc-4206-b3d4-078cc9d216fa)

**Comment by RozettaRosee** [comment]
this doesn't fix the issue. They are still green.

**Comment by Lolothepro** [comment]
> this doesn't fix the issue. They are still green.

Disable Colormaps

**Comment by sp614x** [comment]
Fixed, coming in next preview.

**Comment by Lolothepro** [comment]
@sp614x Does fixing the cherry leaves bug also fix the leaves in other mods?
https://github.com/Chocohead/OptiFabric/issues/121

**Comment by Gurnoor31** [comment]
happening in 1.21.7 as well
