### ISSUE TITLE
[Colormaps] Some named colormaps make cherry leaves tinted

### ISSUE THREAD

**Issue by kavast** [sp614x/optifine#7413]
## Description of Issue
Having birch.png, pine.png, swampfoliage.png or swampgrass.png present in ~/colormap makes cherry leaves receive a tint.

![colormap-bug](https://github.com/sp614x/optifine/assets/5574006/ac9fc38a-1e0d-45cd-ae2f-5b190a4e42d6)

## Steps to Reproduce
1. Activate a resource pack with ~/colormap/birch.png

## OptiFine Version
1.20_HD_U_I5_pre3,
1.19.4_HD_U_I4

## Installation Method
Standalone installer

**Comment by KaiAF** [comment]
Reported here: #7410

**Comment by space-3456** [comment]
я не понимаю что делать, помогите пожалуйста
