### ISSUE TITLE
[Category] Short description

### ISSUE THREAD

**Issue by JonotarTheTyranitar** [sp614x/optifine#7416]
## Description of Issue

When I go to download any version of Optifine, adfoc.us come back with an error message. I just want to use Optfine for 1.20, please got adfocus to fix their server or use a different service. 
## Steps to Reproduce
1. Go to Optifine.net
2. Go to Downloads section
3. Hit download with any version. 
## Prior Testing

I tried it on 1.20, 1.19, and 1.12, all came back with the same error

**Comment by SilentWhisperer** [comment]
use mirror link next to download button
