### ISSUE TITLE
[Optifine crashing/website not working] 

### ISSUE THREAD

**Issue by mincraftyoniii06** [sp614x/optifine#7418]
DUDE I literally can't even download optifine at first, I was trying to make it work with forge and every time I put optifine in mods it would crash it use to work but once Minecraft updated everything started falling apart. so I tried uninstalling and reinstalling DID NOT WORK. I erased the data DID NOT WORK, I updated it DID NOT WORK, THEN once I tried all that I uninstalled optifine and went to reinstall it NOW IT KEEPS SAYING THE WEBSITE IS OVERLOADING SO I CAN'T EVEN USE OPTIFINE I DONT KNOW WHAT TO DO I TRIED EVERYTHING is something off on their end? because forge is working fine they even updated, and it works just optifne is the issue for me

**Comment by SilentWhisperer** [comment]
use mirror link next to download button

**Comment by vinc3nz** [comment]
Close this please.
