### ISSUE TITLE
optifine cannot find 1.20

### ISSUE THREAD

**Issue by dinonuggss** [sp614x/optifine#7419]
everytime I try to install the new version it comes up with the error of it can't find 1.20. 

I've used jarfix, went in and out of normal 1.20 to make sure it was installed, i reset my computer, I checked to make sure the version was right in the launcher and ive tried redownloading from mirror link. I'm not sure what else to do

**Comment by Tencryn** [comment]
Are you 100% sure you're launching 1.20 and not the latest version which is 1.20.1?

**Comment by dinonuggss** [comment]
> 

it was in 1.20.1 thank you, it works now
