### ISSUE TITLE
[FORGE] Some potion effects crash the game

### ISSUE THREAD

**Issue by Lolothepro** [sp614x/optifine#7425]
## Description of Issue
Invisible entities crash Minecraft

## OptiFine Version
Optifine 1.20.1 HD U I5 pre4

## Installation Method
Forge

## Fabric/Forge Version
47.0.3

Logs:

[latest.log](https://github.com/sp614x/optifine/files/11818645/latest.log)

Crash report:

[crash-2023-06-21_16.14.19-client.txt](https://github.com/sp614x/optifine/files/11818652/crash-2023-06-21_16.14.19-client.txt)

21:
https://mclo.gs/cnZwapn

**Comment by spenceuh** [comment]
I'm getting the same problem. I'm using forge 47.0.3 and 1.20.1 OptiFine HD U I5 pre4. Any sort of potion or mob induced effect crashes the game.

**Comment by sp614x** [comment]
Fixed, coming in next preview
