### ISSUE TITLE
The "Swamp Colors" setting breaks the texture of particles when set to "Off".

### ISSUE THREAD

**Issue by Lolothepro** [sp614x/optifine#7431]
## Steps to Reproduce
1. Break flowers

## OptiFine Version
1.20.1_HD_U_I5_pre5

## Installation Method
Prism

## Screenshot

On:
![2023-06-22_20 06 22](https://github.com/sp614x/optifine/assets/68275908/2a50a45c-23d5-4caf-8780-2eeb02eb4975)
Off:
![2023-06-22_20 06 30](https://github.com/sp614x/optifine/assets/68275908/13063b52-fc18-4d07-8a86-60d7fd720f5a)

No pink texture

**Comment by sp614x** [comment]
Fixed, coming in next preview.
