### ISSUE TITLE
1.20: [F3/GUI] The F3 menu is not rendered correctly (number of items in an inventory slot)

### ISSUE THREAD

**Issue by Lolothepro** [sp614x/optifine#7432]
## Description of Issue
The F3 menu is not rendered correctly (number of items in a case)

## Steps to Reproduce
1. Press F3 with a stack of items

## OptiFine Version
OptiFine 1.20.1_HD_U_I5_pre5

## Installation Method
Prism

## Screenshot:
![2023-06-22_20 45 38](https://github.com/sp614x/optifine/assets/68275908/160aab08-d5da-4bde-9c38-4122660360ea)

![image](https://github.com/sp614x/optifine/assets/68275908/349f150e-bca4-46b6-90eb-179e92f7581d)

**Comment by sp614x** [comment]
Fixed, coming in next preview.
