### ISSUE TITLE
[Natural Textures] Optifine creates z-fighting with walls

### ISSUE THREAD

**Issue by Lolothepro** [sp614x/optifine#7439]
## OF Version

1.20.1 I5 pre6

## Screenshot

![2023-06-24_12 22 15](https://github.com/sp614x/optifine/assets/68275908/dc898089-ea86-46ac-a6f0-daac636354df)
![2023-06-24_12 22 24](https://github.com/sp614x/optifine/assets/68275908/925b917f-a5eb-4cd5-bc04-d089af77815c)

## //

https://github.com/sp614x/optifine/assets/68275908/5313933d-ede3-40f6-879a-b3629572b643

**Comment by sp614x** [comment]
Fixed, coming in next preview
