### ISSUE TITLE
[Bug] Game crashes opening any world if any shader is in shaderpacks folder.

### ISSUE THREAD

**Issue by amsmartrobber** [sp614x/optifine#7441]
## Description of Issue
Basically, my game immediately crashes whenever I drop any shader into shaderpacks and attempt to play, I'm quite new to this but it has happened on both Sildurs Shaders as well as Wisdom Shaders, so I dont believe this is a shader issue. I've dropped them in zipped, unzipped and even dragging the folders of the zip into shaderpacks. All do absolutely no changes to my situation.  Its loading completely fine, but as soon as I join a world, it breaks.

## Steps to Reproduce
1. Download any shader
2. Drop it into shaderpack folder
3. Start Minecraft
4. Click Singleplayer
5. Play or create any world
6. Watch as you immediately crash

## OptiFine Version
OptiFine_1.18.2_HD_U_H7_1

## Installation Method
I dropped it into my mods folder as well as opening the jar file and clicking install whilst my desired installation was open.

## Fabric/Forge Version
Forge 40.2.9

## Other Installed Mods
https://pastebin.com/rKU9UD2m

## Log Files/Crash Reports
https://pastebin.com/2YyXc6y2

## F3 Debug Screenshot
I cant even get ingame how do you expect me to get this?

## Prior Testing
If there is nothing in shaderpacks, it works perfectly fine. Thats all I can tell you.

I have not tested any mods being off or on, so everything on the list is on.

## Additional Information
Notin

**Comment by sp614x** [comment]
OptiFine H7 for 1.18.2 is compatible with Forge 40.0.24.
You are running with Forge 40.2.9.

**Comment by sp614x** [comment]
Released OptiFine H9 for 1.8.2, compatible with Forge 40.2.9.

**Comment by amsmartrobber** [comment]
Thank you very much going out of your way to release a compatible version!
