### ISSUE TITLE
[SCULK SENSOR] Sculk sensors emit too much light

### ISSUE THREAD

**Issue by Lolothepro** [sp614x/optifine#7445]
## OptiFine Version
1.20.1_HD_U_I5_pre6

## Screenshot

Vanilla:
![2023-06-27_17 46 59](https://github.com/sp614x/optifine/assets/68275908/fab7d7f0-5e31-4377-8a13-78cfe677cb53)
[Sodium](https://github.com/CaffeineMC/sodium-fabric/issues/1852):
![2023-06-27_17 47 39](https://github.com/sp614x/optifine/assets/68275908/c4dfa550-3149-4368-ba0d-4a25e688539b)
Optifine:
![2023-06-27_17 48 16](https://github.com/sp614x/optifine/assets/68275908/8334bb69-df02-41dd-996b-6f56731d30ca)
this also happens with [Indigo](https://github.com/FabricMC/fabric/issues/3153) (FRAPI)

For Sodium, see PR 1855

## If you want more information on this bug, you can read #dev-sodium on the CaffeinMC Discord.

**Comment by sp614x** [comment]
Can't reproduce it, vanilla and OF behave identically. 

Test with max brightness:

- vanilla

![image](https://github.com/sp614x/optifine/assets/16635441/3b8e4b6c-2593-4414-a6fa-3b1c045b3be0)

- OptiFine

![image](https://github.com/sp614x/optifine/assets/16635441/839c12de-1720-4cf9-8b31-3e6c7a817fb8)

**Comment by Lolothepro** [comment]
> Can't reproduce it, vanilla and OF behave identically.
> 
> Test with max brightness:
> 
> * vanilla
> 
> ![image](https://user-images.githubusercontent.com/16635441/250069688-3b8e4b6c-2593-4414-a6fa-3b1c045b3be0.png)
> 
> * OptiFine
> 
> ![image](https://user-images.githubusercontent.com/16635441/250069994-839c12de-1720-4cf9-8b31-3e6c7a817fb8.png)

You need to be in a sunless environment (e.g. a cave).

**Comment by sp614x** [comment]
Only happens when skylight is 0.

**Comment by Lolothepro** [comment]
If you want more information on this bug, you can read #dev-sodium on the CaffeinMC Discord.

**Comment by sp614x** [comment]
Fixed, coming in pre8.
