### ISSUE TITLE
[Crash] Optifine crashes forge in 1.20.1

### ISSUE THREAD

**Issue by winXwinFT** [sp614x/optifine#7446]
## Description of Issue
Launching minecraft 1.20.1 with forge 47.0.34 consistently crashes the game with any version of optifine for 1.20.1. Ocassionally the game would boot but the "mod loader" wouldn't close and pressing on any tab opened a weird version of the tab that upon exiting with "esc" would give me a black screen.

## Steps to Reproduce
Install optifine through the mods folder
Launch the game using a forge profile
Profit (or not)

## OptiFine Version
All versions for 1.20.1 aka:
OptiFine HD U I5 pre4
OptiFine HD U I5 pre5
OptiFine HD U I5 pre6

## Installation Method
Installed through the mods folder

## Fabric/Forge Version
1.20.1 - 47.0.34

## Other Installed Mods
I isolated each mod and only optifine would crash even if it was alone

## Log Files/Crash Reports
As far as I can tell, the crash reports look the same for every optifine version

[Minecraft optfine crash 1 (pre6).txt](https://github.com/sp614x/optifine/files/11891827/Minecraft.optfine.crash.1.pre6.txt)

[Minecraft optifine crash 2 (pre5).txt](https://github.com/sp614x/optifine/files/11891828/Minecraft.optifine.crash.2.pre5.txt)

[Minecraft optine crash 3 (pre4).txt](https://github.com/sp614x/optifine/files/11891829/Minecraft.optine.crash.3.pre4.txt)

[latest.log](https://github.com/sp614x/optifine/files/11891854/latest.log)

## Prior Testing
If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   - Only OptiFine and Forge
   * **Yes**
- Does this happen without any mods at all?
   - Only Forge/Fabric by itself.
   * **No**
- Does this happen in OptiFine standalone?
* **No**
- Does this happen in Vanilla without OptiFine?
* **No**
- Have you tried using a binary search to find which mods cause this issue?
   - To find conflicting mods, split your mods into 2 groups (not including OptiFine/OptiFabric, obviously). Remove one group, and test in-game. Keep the group that has the problem, and repeat until no more mods can be removed without the issue disappearing.
   - Does the issue still happen with only the remaining mods installed?
      - Forge/Fabric and remaining mods, without OptiFine -->
      * **No**

## Additional Information
![Minecraft optine bug with forge](https://github.com/sp614x/optifine/assets/137991172/5d2cc257-7895-4705-9811-afe223190ce3)
I've loaded into the game (I haven't loaded a world) but the mod loader is still not closed and the screen turns to black if I exit out to the title screen again.

My computer is not great but I don't think forge + optifine should be enough to break it.

**Comment by Lolothepro** [comment]
You are not using the correct version of Forge (compatible with Optifine), please use Forge 47.0.3.

**Comment by zyphlar** [comment]
Here's the crash log from when I tried to run `preview_OptiFine_1.20.1_HD_U_I5_pre6` on Forge 47.0.35.
Installing Forge 47.0.3 instead worked fine, thanks for the tip.

[crash-2023-06-29_20.06.08-client.txt](https://github.com/sp614x/optifine/files/11912455/crash-2023-06-29_20.06.08-client.txt)

**Comment by Ariel-Rozen** [comment]
Been having the same issue, how to I move the launcher setup from forge 47.1.47 to 47.0.3?

**Comment by Ari-RERA-43** [comment]
Download the older installer from the Forge website and run it.

**Comment by Ariel-Rozen** [comment]
thanks, where does this file need to go?

**Comment by Ari-RERA-43** [comment]
> thanks, where does this file need to go?

It's the Forge installer. You run it and then play the profile for the corresponding Forge version from the launcher.

**Comment by BucheVision** [comment]
thanks guys i can play optifine with forge now :)

**Comment by skelso01** [comment]
Have the same issue on Forge 47.2.18 and optifine OptiFine_1.20.1_HD_U_I6
