### ISSUE TITLE
[BUG] Programmer's Art glass doesn't connect.

### ISSUE THREAD

**Issue by JaxOrSmthng** [sp614x/optifine#7450]
## Description of Issue
When you choose the programmer's art texture pack, most if not all of the glass textures don't connect.

## Steps to Reproduce
1. Use Programmer's Art Texture Pack
2. Turn on connected textures
3. Place down 2x2 glass
![image](https://github.com/sp614x/optifine/assets/98616398/85fc6090-2ea5-41ed-86b2-937e0e0d60ca)

## OptiFine Version
OptiFine HD U I5 pre4

## Installation Method
Dropped Jar into mods folder

## Fabric/Forge Version
Forge 47.0.3

## Other Installed Mods
![image](https://github.com/sp614x/optifine/assets/98616398/ae77bf93-7674-48b8-96b0-4efc0713283d)

## Log Files/Crash Reports
no log files

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
Yes
- Does this happen without any mods at all?
Yes (connected textures aren't vanilla)
- Does this happen in OptiFine standalone?
Yes
- Does this happen in Vanilla without OptiFine?
Yes (connected textures aren't vanilla)
- Have you tried using a binary search to find which mods cause this issue?
Mods don't cause this issue, happens without any other mods.

## Additional Information
None

**Comment by sp614x** [comment]
Relevant  #7332

**Comment by sp614x** [comment]
Fixed in I5_pre8 for 1.20.1
