### ISSUE TITLE
BSL Shaders Broken Sky while using Optifine 1.20.1

### ISSUE THREAD

**Issue by peterdachicken** [sp614x/optifine#7453]
## Description of Issue
When using BSL shaders, the sky seems to break visually under the crosshair. When the crosshair is moved any higher than the horizon, a gap that reveals the vanilla sky is created from the crosshair to the horizon, while the sky above the crosshair is fine. Note: the sky below the horizon is normal.

## Steps to Reproduce
1. Open Optifine 1.20.1
2. Turn on BSL Shaders (v8 2.04)
3. Move your crosshair above the horizon of the sky

## OptiFine Version
Optifine 1.20.1

## Installation Method
I used a standalone installer for Optifine.

## Log Files/Crash Reports
OpenGl Error 1282. It hasn't crashed my game before.

## F3 Debug Screenshot
<img width="1458" alt="Screenshot 2023-07-01 at 8 47 25 am" src="https://github.com/sp614x/optifine/assets/138264763/c448c1c4-cc61-4a98-8231-265ff5c25157">

## Prior Testing
- Does this happen in Vanilla without OptiFine?
- No it does not, because I can't use shaders in Vanilla.

## Additional Information
The broken sky seems to be a cube of some sort, following the sky shape in game. This bug is produced with my singleplayer worlds, and when playing servers.

**Comment by Jiingy** [comment]
I cannot find the version of OptiFine you are using on the website. The latest is `1.20.1-OptiFine HD U I6 pre3`. Can you verify that this happens on the newest version?

I myself tested it on the same BSL version on `1.20.1-OptiFine HD U I5` and I do not see the issue.

**Comment by Jiingy** [comment]
Closing for lack of response from original issue poster.
