### ISSUE TITLE
[Performance] Lower Fps than Vanilla and very high GPU usage (90%)

### ISSUE THREAD

**Issue by Kaelig2102** [sp614x/optifine#7463]
## Description of Issue
When playing on Vanilla, i get 1.5 to 2 times more Fps than w/ optifine. Some other players seems to be affected by this exact same issue.
 No wrong graphic component selected and default MC settings without shaders.
Also, F3 menu displays an absurdely high GPU usage, around 90% on Optifine and only 20% on vanilla.
Tried reinstalling optifine on a new blank Mc folder and nothing changed.

## Steps to Reproduce
Sadly, i don't know anything about this bug. I think it can appears by using specific components or PCs.
Pc specs:
16 Go RAM
NVIDIA GeForce RTX 3050 Ti Laptop GPU
12th Gen Intel(R) Core(TM) i7-12700H

## OptiFine Version
ANY version of Optifine. Tested on 1.8.9, 1.12.2, 1.19.4 and 1.20/1.20.1 previews

## Installation Method
Official website, classic .minecraft folder

## Log Files/Crash Reports
[2022-08-31-2.log.gz](https://github.com/sp614x/optifine/files/11951776/2022-08-31-2.log.gz)

## F3 Debug Screenshot
![2023-06-12_21 15 56](https://github.com/sp614x/optifine/assets/138615826/85c74248-d2eb-40be-a27e-08dce4442cbe)
![2023-06-12_20 09 18](https://github.com/sp614x/optifine/assets/138615826/15cb004b-803a-428d-8c66-2a7e9fed2b0b)

## Prior Testing
Don't happen on vanilla since there is normal GPU usage
Haven't tested on Forge or Fabric loader.

## Additional Information
If anyone needs more information, i can add more details. Also available on discord : kaelig2102
Sorry if there isn't that much details, i haven't tested this a lot.
And sorry if there's bad English, I'm French :P Ty for your help

**Comment by sp614x** [comment]
Disable Smooth FPS?

**Comment by ZenithRogue** [comment]
Optimizations added in `OptiFine 1.20.1_HD_U_I6_pre1`

**Comment by Kaelig2102** [comment]
Hi, did the test with fast render ON and smooth fps Off. little boost but still anormal GPU usage
![2023-07-09_00 48 17](https://github.com/sp614x/optifine/assets/138615826/cfdae586-790d-40a9-8bfe-50dcadb4f9e9)

**Comment by sp614x** [comment]
This looks like a driver issue. 
When GPU usage is 98% OF is getting out everything that the hardware can provide. 
For some reason OF is running with the driver in power-saving mode or is otherwise restricted.
Looks like this is a laptop, so there should be a setting in the graphics driver control panel which programs should run in power-saving mode.
