### ISSUE TITLE
[LIGHTING] Optifine 1.20.1 HD U I5 pre8 causes a regression in light rendering

### ISSUE THREAD

**Issue by Lolothepro** [sp614x/optifine#7464]
## Screenshot

Optifine I5 pre7:
![2023-07-05_12 25 15](https://github.com/sp614x/optifine/assets/68275908/7f2351af-24e2-43eb-b197-e54a3c47c5ff)

**Optifine I5 pre8**:
![2023-07-05_12 26 22](https://github.com/sp614x/optifine/assets/68275908/c36f7a11-d21b-484e-a6b1-d4068dcb450d)

Vanilla:
![2023-07-05_12 27 14](https://github.com/sp614x/optifine/assets/68275908/79e4cbd2-bc91-4afa-b49d-beffb5e91635)

**Comment by sp614x** [comment]
Side effect of the  #7445 bugfix
