### ISSUE TITLE
[Custom Sky] Midnight sky bugged out with view bobbing on

### ISSUE THREAD

**Issue by Firefox37** [sp614x/optifine#7469]
## Description of Issue
When you use a resource pack that changes the overworld sky with the latest version of optifine (1.19.4), during night time in game the sky tends to speed up, and if you have player bobbing enabled, the sky will move along with the player.

## Steps to Reproduce
1. Find a resource pack that changes the sky textures
2. enable player bobbing (Options> Video Settings> Details> View Bobbing: ON)
3. use /time set midnight, or wait until night time in game

## OptiFine Version
1.20.1 HD I5 Ultra

## Installation Method
standalone installer

## Prior Testing
As stated by another user @UsernameGeri yes I have seen the fix to change the axis from `0.0 -0.2 0.0` in the properties file to `0.0 -1.0 0.0` to fix the bugged out sky, however it seems to compensate you also need to add `speed=0.2` as it seems the axis value also contributes to the speed somehow. But also, the only file that seems to be affected by this is `sky6.properties` and it only occurs during the night (at precisely midnight the view bobbing affects the sky the most), even though most of the property files also do contain the `axis=0.0 -0.2 0.0` line. For example, precisely at noon the daytime skybox is not affected at all by view bobbing, which is correct.

## Additional Information
similar to #7352 and #7235 
attached zip for sky.properties files 
[sky.zip](https://github.com/sp614x/optifine/files/11987350/sky.zip)

**Comment by roro1506HD** [comment]
I wrote an answer in #7235 which explains why this is happening

**Comment by Jiingy** [comment]
Closing this issue in favor of #7235
