### ISSUE TITLE
[Bug] Minecraft fails to open when running 1.20.1 versions of Optifine on Mac

### ISSUE THREAD

**Issue by DawnCourtHarper** [sp614x/optifine#7470]
## Description of Issue
When running Optifine for Minecraft 1.20.1 on a Mac laptop Minecraft simply fails to launch - there is no error message just once you leave the launcher it acts like it's going to open Java and then nothing happens. This only happens with 1.20.1 versions, both pre-releases and OptiFine HD U I5, I have been using OptiFine for 1.19.2 and 1.19.4 for a while without issue. It appears almost as if the instance of Minecraft simply closes itself as there are no crash files and the Minecraft launcher doesn't reopen.

## Steps to Reproduce
1. Launch a 1.20.1 Optifine-enabled enabled installation and wait. 

## OptiFine Version
OptiFine HD U I5

## Installation Method
OptiFine was installed using the included installer as were previous versions.

## Log Files/Crash Reports
No log files are available, as Minecraft doesn't crash it seems like it closes itself.

## Prior Testing
No issues in vanilla or with fabric.

**Comment by fahlman** [comment]
What model Mac are you using?

**Comment by DawnCourtHarper** [comment]
Mac Book Pro, MacOS 13.4.1

**Comment by Jiingy** [comment]
Unable to confirm this issue as I do not have a Mac OS. More Mac users confirming this issues would be appreciated.

**Comment by fahlman** [comment]
> Mac Book Pro, MacOS 13.4.1

Need a little more detail of what model of MacBook Pro you're using. Use the instructions found at the link below.

https://support.apple.com/en-us/HT201581

Also need the latest.log file. Let me know if you need help finding it.

**Comment by Jiingy** [comment]
Closing issue for lack of response from the original poster. Can be reopened if more information is provided.
