### ISSUE TITLE
[Bug] All placed banners are white

### ISSUE THREAD

**Issue by TheEpicCubeoidal** [sp614x/optifine#7471]
## Description of Issue
When placing a banner block down, despite having a color/pattern in the inventory, appears as blank white

## Steps to Reproduce
Place down any type of banner into the world

## OptiFine Version
1.20.1 I6 pre1

## Installation Method
Standalone installer

## Other Installed Mods
None

## F3 Debug Screenshot
![2023-07-08_18 58 50](https://github.com/sp614x/optifine/assets/66644808/50a4a0ce-0079-45ec-9658-13c7b7dfe652)

## Prior Testing
This bug does not appear in any version prior to 1.20.1 I6 pre1

**Comment by Lolothepro** [comment]
Fast Render bug

**Comment by Jiingy** [comment]
Can confirm this behavior (screenshots attatched) 
![2023-07-10_20 08 29](https://github.com/sp614x/optifine/assets/69827559/65cf1030-6066-43f0-9f7e-8453557c7088)
![2023-07-10_20 10 25](https://github.com/sp614x/optifine/assets/69827559/18cdaf96-46a9-430b-ae53-e2d93e0c68df)

**Comment by sp614x** [comment]
Fixed in I6_pre3 for 1.20.1.

**Comment by Lolothepro** [comment]
Appears to be only partially fixed.

**Comment by Jiingy** [comment]
> Appears to be only partially fixed.

Can you provide a screenshot?

**Comment by Lolothepro** [comment]
> > Appears to be only partially fixed.
> 
> Can you provide a screenshot?

#7484

**Comment by Jiingy** [comment]
Thank you. Will keep this issue closed in favor of the new issue post.
