### ISSUE TITLE
[1.20.1] Horse armor is not rendered with Fast Render enabled

### ISSUE THREAD

**Issue by Lolothepro** [sp614x/optifine#7473]
## OptiFine Version
Optifine 1.20.1 HD U I6

## Screenshot
![2023-07-09_15 01 46](https://github.com/sp614x/optifine/assets/68275908/2d20fae5-e375-496f-a57d-4dd236de51de)

**Comment by sp614x** [comment]
Works for me:

![image](https://github.com/sp614x/optifine/assets/16635441/622c8667-38da-47e6-a800-061d80492c11)

Maybe there is some specific condition which triggers the bug.

**Comment by Lolothepro** [comment]
> Works for me:
> 
> ![image](https://user-images.githubusercontent.com/16635441/253812639-622c8667-38da-47e6-a800-061d80492c11.png)
> 
> Maybe there is some specific condition which triggers the bug.

Try with "Internal" shaders?
Or a horse with different patterns/colors
Or with the villagers' tunics

**Comment by Lolothepro** [comment]
Note: https://claritypack.com/restworld/RestWorld_1.20.zip
This map is extremely useful for reproducing the bug

**Comment by sp614x** [comment]
Internal shaders, different horses with "RestWorld_1.20", still seem to work correctly:

![image](https://github.com/sp614x/optifine/assets/16635441/47f258a3-b195-4192-b259-dda49c5d8a09)

**Comment by sp614x** [comment]
The villager professions were broken, fixed them.

**Comment by Lolothepro** [comment]
![2023-07-16_18 48 37](https://github.com/sp614x/optifine/assets/68275908/f2f949ba-48b1-4f2d-8f3b-3e12cceb824a)

Go here instead

**Comment by sp614x** [comment]
The horses that I see there have no armor.
How do you turn the horse armor on?

**Comment by Lolothepro** [comment]
> The horses that I see there have no armor. How do you turn the horse armor on?

You can add armor manually by right-clicking on horses with armor in the player's hands.

**Comment by sp614x** [comment]
Fixed horse armor, coming in I6_pre3.
