### ISSUE TITLE
[Bug] Lava Bucket Fuel Indicator Not Decreasing Gradually

### ISSUE THREAD

**Issue by JohnReedV** [sp614x/optifine#7474]
## Description of Issue
When using a lava bucket as a fuel source in a furnace there is a discrepancy between the actual fuel consumption and the visual representation of the same. The fuel gauge erroneously remains full during the entire duration of fuel consumption and only updates to show an empty state when the lava bucket is completely depleted. This results in the furnace abruptly turning off, without any prior visual indication of the fuel nearing exhaustion.

## Steps to Reproduce
1. Insert a stack of cobblestone into the top slot of the furnace.
2. Place a lava bucket into the bottom slot (fuel source slot) of the furnace.
3. Monitor the furnace operation and observe the fuel indicator for the lava bucket.

## OptiFine Version
OptiFine 1.20.1_HD_U_I6_pre1

## Installation Method
Standard Installation on linux. 

## Other Installed Mods
None

## Additional Information
Running linux popOS.

![Screenshot from 2023-07-09 10-43-21](https://github.com/sp614x/optifine/assets/87283488/5b571195-b225-4751-9d02-78bba479ae35)

**Comment by Jiingy** [comment]
![image](https://github.com/sp614x/optifine/assets/69827559/4d2bdcb0-cd2a-4c0c-874f-280b8cc1b9a3)
On pre3 (this issue has not been addressed anywhere as fixed yet) I was unable to replicate this behavior. Are you able to provide more information such as your game settings, resource packs, shaders (if applicable)-- or try and replicate the issue again yourself?

**Comment by Jiingy** [comment]
Closing as this cannot be reproduced
