### ISSUE TITLE
CEM Spider texture broken?

### ISSUE THREAD

**Issue by Norzeteus** [sp614x/optifine#7477]
When I opened my world today, I saw that the textures from my  Cem Spiders and cave spiders did not work correct.
The interesting thing was that some worked correct and some didn't...!

Only use  a spider spawn egg

Using preview_OptiFine_1.20.1_HD_U_I6_pre1 with the included standalone installer
In the meantime I tried the OptiFine_1.20.1_HD_U_I5 and this one works correct, it must be a bug in the I6_pre1

my resourcepack: [https://www.curseforge.com/minecraft/texture-packs/norzeteus-space-1-13-128x128-ctm-3d-optifine/files](url)
At the left you see the correct texture and the others...?

![2023-07-10_18 00 23](https://github.com/sp614x/optifine/assets/24456750/9e4fe19d-c04a-4e7a-90ec-556acb96fcee)

**Comment by Jiingy** [comment]
The resource pack link is broken.

In the mean time, does this happen with any other resource packs that change the spider model?

**Comment by Norzeteus** [comment]
[https://legacy.curseforge.com/minecraft/texture-packs/norzeteus-space-1-13-128x128-ctm-3d-optifine](url)
I don`t know, but as you see in OptiFine_1.20.1_HD_U_I5 and bevore it worked correct!

**Comment by sp614x** [comment]
Fast Render = OFF?

**Comment by Norzeteus** [comment]
ok,this seemed to be the problem, now it works, thank you  👍
