### ISSUE TITLE
Crash on Optifine 1.11.2 HD U C3, Forge 13.20.1.2393

### ISSUE THREAD

**Issue by drinfernoo** [sp614x/optifine#748]
I'm running a slightly modified instance of ATM2, and am getting [this crash](https://hastebin.com/axudiwoyiq) on startup. I'm not exactly sure what mod is causing it, but it doesn't happen *unless* I am using Optifine. I can furnish a full mod list if necessary.

**Comment by sp614x** [comment]
Wrong versions.
OptiFine for 1.11 will not work with Minecraft 1.11.2.
```
Forge Mod Loader version 13.20.1.2393 for Minecraft 1.11.2 loading
... OptiFine_1.11_HD_U_C3.jar
```

**Comment by drinfernoo** [comment]
Wow, I can't believe I messed that up. Thanks!
