### ISSUE TITLE
[Bug] Incompatibility with Create on 1.20.1

### ISSUE THREAD

**Issue by SilentSimulacrum** [sp614x/optifine#7480]
## Description of Issue
Crash on startup with create mod.

## Steps to Reproduce
1. Install create and optifine together
2. Launch minecraft
3. Crash

## OptiFine Version
Optifine 1.20.1_HD_U_I5

## Installation Method
Drop jar into mods folder

## Fabric/Forge Version
Forge version 47.0.35

## Other Installed Mods
Create 1.20.1-0.5.1.d
JEI-1.20.1-forge-15.2.0.22

## Log Files/Crash Reports
https://pastebin.com/0sRHpVxt

## F3 Debug Screenshot
Cannot enter game so n/a

**Comment by Jiingy** [comment]
Unfortunately, for the two to be compatible, the Create mod would have to fix the interference with OptiFine on their side as OptiFine very likely overwrites whatever is casuing the issue.

**Comment by blunderbust** [comment]
[https://github.com/Creators-of-Create/Create/issues/5240](https://github.com/Creators-of-Create/Create/issues/5240)

Here is the same issue thread on the Create github.
