### ISSUE TITLE
[Random Entity Textures Bug] Iron Golem Crackiness is randomizing 

### ISSUE THREAD

**Issue by MincedRaft** [sp614x/optifine#7481]
## Description of Issue
In previous versions, Iron golem textures without an accompanying variant of the crackiness textures would default back to the vanilla one. In the latest release, it randomizes the crackiness texture and they don't adhere to their accompanying textures at all. Here is an example image, none of the pictured golems have the correct crackiness texture applied:

![2023-07-12_23 07 47](https://github.com/sp614x/optifine/assets/22252470/a01a991e-c303-4eba-858c-0e697d4f5fa1)

## Steps to Reproduce
Have a texture pack with iron golem variants and have only some of the variants have a unique crackiness texture. 

## OptiFine Version
OptiFine_1.20.1_HD_U_I5

## Installation Method
JAR file in mods folder

## Fabric/Forge Version
Force 47.0.3

## Other Installed Mods
No Chat Reports 1.20.1-v2.2.1
Xaero's Minimap 23.5.0
Xaero's World Map 1.30.6

## Prior Testing
Happens even if only optifine and forge are installed.

## Additional Information
Textures are designed to work with Fresh Animations v1.8.1 but the textures will still render without it installed. Attached is an example pack with just the iron golem textures

[Iron Golem Test.zip](https://github.com/sp614x/optifine/files/12035065/Iron.Golem.Test.zip)

**Comment by sp614x** [comment]
The resource pack needs `iron_golem_crackiness_xxx.properties` with the same rules as `iron_golem.properties`.
If the rules are identical then the crackiness and iron golem textures will match each other.
