### ISSUE TITLE
[shader] Enchantment overlay uses nearest filter when loaded shader once

### ISSUE THREAD

**Issue by GeForceLegend** [sp614x/optifine#7482]
## Description of Issue
Enchantment overlay looks correct (smoothed) when launching with shaders off, but will turn pixels after loading shaders. After load shaders, disable the shader will not make it normal again unless restart the game.

## OptiFine Version
1.20.1 I5, standalone installer

## F3 Debug Screenshot
The normal look before loading shaders:
![2023-07-13_16 17 53](https://github.com/sp614x/optifine/assets/41003546/71375a1b-77a2-494b-b7a4-ee862ed89ff0)

After load shaders (tested 2 shaders)
![2023-07-13_16 18 55](https://github.com/sp614x/optifine/assets/41003546/25b68fb6-8677-4bd7-9e56-94e1a5e9f003)
![2023-07-13_16 17 04](https://github.com/sp614x/optifine/assets/41003546/c1b8b12b-17f7-4607-a7cd-6f74115a35bb)

After disable shaders:
![2023-07-13_16 19 14](https://github.com/sp614x/optifine/assets/41003546/111ac415-70f8-42da-afc1-17db0255b136)

**Comment by Jiingy** [comment]
Does this occur with all shaders or just one?

**Comment by GeForceLegend** [comment]
It occurs with all shaders I have tested. And if launching game with shaders on, disable shaders will cause this bug too. Looks like the switching between shaders on and shaders off (vanilla) is the way to get this bug.

**Comment by Jiingy** [comment]
Can confirm this behavior. 

More related issues noticed (Shader used is BSL_v8.2.04):
1. An enchanted shield behaves inconsistently in an item frame
2. Armor glint is not working at all
![2023-07-17_19 19 20](https://github.com/sp614x/optifine/assets/69827559/1996f8b5-2b05-4533-8275-2d25095cb03c)
![2023-07-17_19 19 22](https://github.com/sp614x/optifine/assets/69827559/7dab1bd4-55a9-479d-9d48-6343a0ece638)

**Comment by GeForceLegend** [comment]
Still exist in latest 1.21.1 preview.
![2024-09-18_09 57 59](https://github.com/user-attachments/assets/a6cf10cd-b631-4fff-ae31-22310ae1c4bf)

**Comment by sp614x** [comment]
Fixed, coming in next preview
