### ISSUE TITLE
[Bug] Warden CEM Animations bugged random()?

### ISSUE THREAD

**Issue by Nuanulla** [sp614x/optifine#7486]
## Description of Issue
The same animation script applied to the same model elements of the same transformations and translations result in different results between Warden and all other entities I've observed. The issue comes down to either OptiFine's random() function or an unintentional multiplier 

## Steps to Reproduce
See below. Watch the below videos for examples. I'll upload an affected version of my resource pack when possible.

## OptiFine Version
preview_OptiFine_1.20.1_HD_U_I6_pre3

## Installation Method
mods folder

## Fabric/Forge Version
Forge 47.0.35

## Other Installed Mods
mobsunscreen-forge-1.20.1-3.1.0
no-telemetry-1.7.0
ShoulderSurfing-Forge-1.20.1-2.4

## Additional Information
Same code:
https://github.com/sp614x/optifine/assets/88032550/f6bdd8e6-cf52-407c-b539-a927cbdd0e72
`"var.blink_counter": "if(!varb.blink && var.blink_delay <= 0, clamp(450 * random(), 100, 450), var.blink_counter - 0.5)",`
`"var.blink_delay": "if(varb.blink, 5, var.blink_delay - 0.5)",`

Warden code mult. 4:
https://github.com/sp614x/optifine/assets/88032550/0e06478a-fa87-4a46-9af9-3185a561940a
`"var.blink_counter": "if(!varb.blink && var.blink_delay <= 0, clamp(1800 * random(), 400, 1800), var.blink_counter - 0.5)",`
`"var.blink_delay": "if(varb.blink, 20, var.blink_delay - 0.5)",`

**Comment by Jiingy** [comment]
Can you provide more context to this statement? It's a bit vague as to what is different here with the warden, and other mobs. The video is appreciated but without knowing what to look out for, they look relatively the "same".

> result in different results between Warden and all other entities I've observed.

**Comment by sp614x** [comment]
The warden model rendering is unique, it enables/disables parts of the model and uses the main model to render the emissive layers. This enabling/disabling of model bones may be the problem.

**Comment by Nuanulla** [comment]
> Can you provide more context to this statement? It's a bit vague as to what is different here with the warden, and other mobs. The video is appreciated but without knowing what to look out for, they look relatively the "same".

Sorry, I should clarify that you should be looking at the blinking eyes, which are already implied by with the animation statements I include with the two videos. Of course, the difference will not look as drastic due to video framerate and resolution, which is why testing in-person (so to say) would be best. But I can't release my project's next version yet as I'm not done with a couple things.

Left "Small Stubby" entity is your constant. Eye Blinking animation statement remains constant for Small Stubby. 
Right "Goliath Biped" entity is your variable. Its corresponding Eye Blinking animation statements are revealed in the post above.

Beyond that, there's not much else context I can provide.

> The warden model rendering is unique, it enables/disables parts of the model and uses the main model to render the emissive layers. This enabling/disabling of model bones may be the problem.

That would explain it and solve this mystery. Thanks again for replying to my GitHub reports. Can OptiFine adjust for this unique rendering or must authors adapt to this 'unique rendering' by themselves, per model?
If OptiFine adjusts to maintain rendering and variable consistency amongst its CEM-available entities, I'll release my version as seen with video 1 with copy-pasted code. Else, I'll have to leave my model as seen with video 2 with adapted statements.

**Comment by Nuanulla** [comment]
Closing this issue because, as Ewan says, the mentioned issue is not a bug. The apparently different refresh timing is due counter increments being affected by the entity model's number of layers. Animation equations have to account for the number of layers if they are to be consistently applied across all CEMs.
