### ISSUE TITLE
[Crash] Minecraft crashing upon joining a world

### ISSUE THREAD

**Issue by TheEpicGamer920** [sp614x/optifine#7491]
## Description of Issue
**Upon joining a world, Minecraft crashes with Exit Code 1**

## Steps to Reproduce
**1. Launch Forge from the Minecraft Launcher
2. Let Minecraft load up
3. Join a world (can be singleplayer or multiplayer)
*Game crashes with this message:*

The game crashed whilst unexpected error
Error: java.lang.NoSuchMethodError: 'void net.minecraftforge.client.gui.overlay.ForgeGui.renderSelectedItemName(net.minecraft.client.gui.GuiGraphics, int)'**

## OptiFine Version
**OptiFine HD U I6 pre3**

## Installation Method
**Dropped the JAR file into mods folder**

## Fabric/Forge Version
**Forge 1.20.1 - 47.1.33**

## Other Installed Mods
**Essential 12933+deploy-staging+gf941de5ac**

## Log Files/Crash Reports
**Crash Report: [crash-2023-07-18_11.18.38-client.txt](https://github.com/sp614x/optifine/files/12083109/crash-2023-07-18_11.18.38-client.txt)
Log File: [2023-07-18-2.log.gz](https://github.com/sp614x/optifine/files/12083176/2023-07-18-2.log.gz)**

## F3 Debug Screenshot
**N/A, game crashes upon joining a world, therefore it is not possible to capture the screenshot with OptiFine in the mods folder**

## Prior Testing
**Vanilla without OptiFine = _No crash_
Forge without any mods = _No crash_
Forge with Essential = _No crash_
Forge with OptiFine = _Crash_
Forge with Essential and OptiFine = _Crash_
Standalone OptiFine (no Forge) = _No crash_**

## Additional Information
**Windows specifications
Edition - Windows 10 Home
Version - 22H2
OS Build - 19045.3208**

**Comment by YourAverageHuman** [comment]
Exact same thing happens with me. Both my device, Java and graphics driver are fully updated, so I'm also unsure what to do.

**Comment by SilentWhisperer** [comment]
yea it doesn't work for the version you stated Because it wasn't made for it

**Comment by YourAverageHuman** [comment]
What do you mean? I originally tried Optifine with the updated version of Forge, **47.1.33, and it didn't work**, which it should. I then tried Optifine with the version stated next to on the download website, **47.0.35 and it worked**. So I think the main problem is that they haven't updated Optifine to work with the updated versions of Forge or they made a mistake which made **1.20.1 Optifine only compatible with 47.0.35**.

**Comment by SilentWhisperer** [comment]
I'm talking about 47.1.33
the Optifine version you're using will only work on 47.0.35

**Comment by YourAverageHuman** [comment]
I have just tried it with the recommended version of Forge, 47.1.0 and it works. So it looks like it will work with versions between 47.0.35 and 47.1.0, but not any versions after. The solution to this issue is to just use 47.1.0 and wait a while to see if there are any updates.
