### ISSUE TITLE
[Bug/Crash] 1.20.1 LittleTiles incompability with Optifine

### ISSUE THREAD

**Issue by Thomarius214** [sp614x/optifine#7495]
## Description of Issue
Game crashing while joining a world with LittleTiles installed

## Steps to Reproduce
1. Download LittleTiles+CreativeCore (lib) and Optifine
2. put into mods folder
3. start game
4. join world
5. crash

## OptiFine Version
1.20.1 OptiFine HD U I5

## Installation Method
Dropped the jar file directly into the mods folder

## Fabric/Forge Version
47.1.39

## Other Installed Mods
https://pastebin.com/S5seAdMf

## Log Files/Crash Reports
https://pastebin.com/eBcTs2zm

## F3 Debug Screenshot
without Optifine
![2023-07-20_21 35 58](https://github.com/sp614x/optifine/assets/122040621/309ef6aa-aa33-4c18-a65e-ac9f7949b8bd)

with Optifine not possible to join world

## Prior Testing
Optifine works fine with the other listed mods
When LittleTiles is installed the game crashes while joining a world
(The same also happens with the create mod)

**Comment by SilentWhisperer** [comment]
Forge 47.1.39 is not officially supported, check if it works in Forge 47.0.35

**Comment by Thomarius214** [comment]
> Forge 47.1.39 is not officially supported, check if it works in Forge 47.0.35

The Owner of LittleTiles told me that the mod stopped supporting optifine, that's why it wasn't working.

So I'll close this now.
Sorry for the inconveniece, but thanks though.
