### ISSUE TITLE
Weird Text error on main menu

### ISSUE THREAD

**Issue by Horrid-12** [sp614x/optifine#7500]
## Steps to Reproduce
Just load up the latest verions of optifine and optifabric 

## OptiFine Version
OptiFine HD U I5

## Installation Method
drop the JAR file into your "mods" folder? 

## Fabric/Forge Version
Fabric verion: 0.14.21

## OptiFabric Version
1.13.25

## Other Installed Mods
Architectury
Cloth Config API
Mod Menu
Fabric API
Optifabric
Optifine

## Log Files/Crash Reports
https://mclo.gs/CqT4chp
## Prior Testing
<!-- If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
no
If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   - Only OptiFine, OptiFabric, and Fabric
- Does this happen without any mods at all?
No

![image_2023-07-23_231943380](https://github.com/sp614x/optifine/assets/96373496/c0a5aca8-2f27-424c-9930-9f56d24bb76d)

**Comment by TheUnknownCod3r** [comment]
Change to Fabric API 0.85, and in future these should be on Optifabric github as Optifine doesn't support Fabric by default.

**Comment by Jiingy** [comment]
See previous comment
