### ISSUE TITLE
[NeoForge] Trying to break a block in survival mode crashes the game.

### ISSUE THREAD

**Issue by Lolothepro** [sp614x/optifine#7505]
Crash report:
[crash-2023-07-26_22.01.48-client.txt](https://github.com/sp614x/optifine/files/12176856/crash-2023-07-26_22.01.48-client.txt)

OptiFine 1.20.1_HD_U_I6_pre5

Trying to break a block in survival mode crashes the game.

***A note about compatibility with NeoForge and Forge: no one knows what the future holds.***

**Comment by sp614x** [comment]
Fixed in pre6.

**Comment by Lolothepro** [comment]
fixed
