### ISSUE TITLE
OpenGL error: 1280

### ISSUE THREAD

**Issue by Pugmaster04** [sp614x/optifine#7507]
## Description of Issue
The modpack I used worked fine. I opened the game for 1.19.2 today and I got the following error over and over: "[26/07/2023 17:54:06 PM] [Render thread/ERROR] OpenGL API ERROR: 1280 (Error has been generated. GL error GL_INVALID_ENUM in (null): (ID: 173538523) Generic error)
[26/07/2023 17:54:09 PM] [Render thread/ERROR] [OptiFine] Suppressed 112 OpenGL errors: 1280."

## Steps to Reproduce
N/A

## OptiFine Version
https://optifine.net/adloadx?f=OptiFine_1.19.2_HD_U_I2.jar&x=724e

## Installation Method
I dropped the zip file into the mod folder, replacing a similar file for 1.19.2. (Same issue with both, the already placed file and the new one)

## Other Installed Mods
[](https://pastebin.com/Kq1d59w2)

## Log Files/Crash Reports
[](https://pastebin.com/raL916Wf)

## F3 Debug Screenshot

![image](https://github.com/sp614x/optifine/assets/73559998/dbb99ee5-7dbc-442c-ab09-dab1f15f9f10)

## Prior Testing
Got the modpack from a friend, it worked for 2 days, and then today I got that error. Replaced the Optifine file with the same one from the Optifine site, to see if updating it could fix it. Updating it did not fix it.

## Additional Information
I uploaded the modpack straight into ATLauncher. Those files use Forge 43.2.0. The game version is Java 1.19.2.

**Comment by SilentWhisperer** [comment]
do you see any graphical issues?
if no, you can disable OpenGL errors under Other... in video settings

**Comment by Pugmaster04** [comment]
> do you see any graphical issues? if no, you can disable OpenGL errors under Other... in video settings

If there's an issue, I'm not going to just ignore it.

**Comment by ZenIsBestWolf** [comment]
please see SilentWhisperer's comment

**Comment by Pugmaster04** [comment]
> 

"Please See" Of course I saw that comment. If there's an issue, it can get worse. Ignoring it causes more problems in the future.

**Comment by SilentWhisperer** [comment]
but do you see any graphical errors?

**Comment by Jiingy** [comment]
This is very common to get in OptiFine, and very often does not actually cause any visual issues. Turning off the OpenGL warnings is the best 'fix' for it as you likely do not need to see the errors.

Regardless, because this error is very commong there are many more issues with this error. 

Please stop continuing conversation on this issue unless you can find a visual discrepency, it is resolved.

**Comment by Pugmaster04** [comment]
A visual discrepancy is that shaders crash the game when you try to turn
them off.

**Comment by Pugmaster04** [comment]
> but do you see any graphical errors?

Something I forgot to add to this report is that any shader I use with this version of optifine crashes the game if I attempt to turn off the shader.

**Comment by Jiingy** [comment]
Locking issue for continued unnecessary conversation.
