### ISSUE TITLE
banners are all white with fast render and shaders on

### ISSUE THREAD

**Issue by azdudue** [sp614x/optifine#7508]
## Description of Issue
Banners are white with Complementary Reimagined and BLS shaders on. Worked fine before OptiFine 1.20.1.

## Steps to Reproduce
1. Download and install any of the OptiFine 1.20.1 update or previews.
2. Turn on shaders.
3. Look at any colored banner.

## OptiFine Version
OptiFine HD U I5 - OptiFine HD U I6 pre 6

## Installation Method
<! Used standalone installer

## Additional Information

[Screenshot 2023-07-27 at 6.48.12 AM.zip](https://github.com/sp614x/optifine/files/12182938/Screenshot.2023-07-27.at.6.48.12.AM.zip)

**Comment by Lolothepro** [comment]
#7484

**Comment by Jiingy** [comment]
Duplicate
