### ISSUE TITLE
[Bug] single player doesnt works

### ISSUE THREAD

**Issue by giganigeria** [sp614x/optifine#7510]
## Description of Issue
i cant play single player and i dont know why maybe because of mods. anyways if i try then it loads normally and if it finished it goes completely grey and then i get kicked , after that it says **_Invalid_ _player_ _data_** and if i go back then im in server list idk what to do

## Steps to Reproduce
1. starting / creating singleplayer game
2. idk how to find bug

## OptiFine Version
 OptiFine HD U H9

## Installation Method
 put the jar file in the mods folder

## Fabric/Forge Version
 forge 1.18.2 40.2.9

## Other Installed Mods
 [mods](https://pastebin.com/wDwa9wat)

## Log Files/Crash Reports
the latest log [latest_log.zip](https://github.com/sp614x/optifine/files/12194437/latest_log.zip)

## F3 Debug Screenshot
 cant because i get kicked

## Prior Testing
 it works only without mods

## Additional Information

i didnt tried all of these that were standing in this but i would like to get better tips from you guys

**Comment by Jiingy** [comment]
This is not an issue with OptiFine.
`[28Juli2023 13:36:00.906] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: LazyOptional is empty or otherwise returned null from getValue() unexpectedly
	Index: 1
	Listeners:
		0: NORMAL
		1: ASM: class de.budschie.bmorph.events.Events onDatapackSyncing(Lnet/minecraftforge/event/OnDatapackSyncEvent;)V
		2: net.minecraftforge.eventbus.EventBus$$Lambda$4448/0x0000000100ca71f0@15bf4cf1
		3: ASM: class com.mrcrayfish.guns.common.NetworkGunManager onDatapackSync(Lnet/minecraftforge/event/OnDatapackSyncEvent;)V
		4: ASM: class com.simibubi.create.foundation.events.CommonEvents onDatapackSync(Lnet/minecraftforge/event/OnDatapackSyncEvent;)V
		5: LOWEST
		6: ASM: class com.github.mechalopa.hmag.AddSpawnerDataEvents onDatapackSync(Lnet/minecraftforge/event/OnDatapackSyncEvent;)V`

Looks like it's an issue with mrcrayfish guns mod. Please report the issue there.

**Comment by giganigeria** [comment]
thanks so much bro
