### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by LuziferSenpai** [sp614x/optifine#7511]
## Description of Issue
Crashed when installed with Sophisticated Backpacks.

## Steps to Reproduce
1. Install Optifine
2. Install Sophisticated Backpacks
3. Start Minecraft

## OptiFine Version
OptiFine HD U I6 pre6

## Installation Method
Mods Folder

## Forge Version
Forge - 47.1.43

## Other Installed Mods
https://pastebin.com/V0JmH6SK

## Log Files/Crash Reports
https://pastebin.com/gjcc5JDP

If you've installed using Forge/Fabric:
It happens with a few mods, like Supplementaries.

**Comment by Jiingy** [comment]
Please report to Sophisticated Backpacks instead of OptiFine as this is not an OptiFine issue.
 
 From your crash:
 `net.minecraftforge.fml.ModLoadingException: Sophisticated Backpacks (sophisticatedbackpacks) encountered an error during the common_setup event phase`
