### ISSUE TITLE
OptiFine HD U I5 (1.20.1) crashing with forge (47.1.43)

### ISSUE THREAD

**Issue by Admant3x** [sp614x/optifine#7512]
## Description of Issue
Hi i have a problem with the optifine when installed in forge.

## Steps to Reproduce
1 install forge 47.1.43 on the launcher
2 put OptiFine HD U I5 (1.20.1) in the mods folder

## OptiFine Version
OptiFine HD U I5 (1.20.1)

## Installation Method
I put optifine in the mods folder of forge

## Fabric/Forge Version
forge ver. 47.1.43

## Other Installed Mods
the installed mods are:

Female-Gender-Mod-forge-1.20.1-3.0.1

MouseTweaks-forge-mc1.20-2.25

Xaeros_Minimap_23.6.0_Forge_1.20

[debug.log](https://github.com/sp614x/optifine/files/12205934/debug.log)

[latest.log](https://github.com/sp614x/optifine/files/12205935/latest.log)

[2023-07-29-17.log.gz](https://github.com/sp614x/optifine/files/12205936/2023-07-29-17.log.gz)

**Comment by Jiingy** [comment]
OptiFine 1.20.1_HD_U_I5 is stated to only support Forge 47.0.35. Please try and update your OptiFine version and Forge version to the latest and see if that helps.
