### ISSUE TITLE
Incompatibility with Controllable

### ISSUE THREAD

**Issue by TheKevlarKnight** [sp614x/optifine#7515]
## Description of Issue
When using optifine with forge, the game will crash on startup and spit out an exit code: 1 when loaded with controllable, works when only loading framework, the requirement of controllable, but will not start with all of them.

## Steps to Reproduce
1. Download Forge and install it
2. Download Optifine and install it with forge
3. Download Framework and install it with forge
4. Download Controllable and install it with Forge
5. Run the game through the forge installation in the launcher

## OptiFine Version
OptiFine HD U I6 pre6

## Installation Method
 Jar file into mods folder with Forge.

## Fabric/Forge Version
47.1.43

## Other Installed Mods
Controllable
Framework

## Log Files/Crash Reports
[latest.log](https://github.com/sp614x/optifine/files/12226276/latest.log)

## Prior Testing

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   - Only OptiFine and Forge - No
- Does this happen without any mods at all? - No
   - Only Forge/Fabric by itself. - No
- Does this happen in OptiFine standalone?
- Does this happen in Vanilla without OptiFine?
- Have you tried using a binary search to find which mods cause this issue?
   - To find conflicting mods, split your mods into 2 groups (not including OptiFine/OptiFabric, obviously). Remove one group, and test in-game. Keep the group that has the problem, and repeat until no more mods can be removed without the issue disappearing.
   - Does the issue still happen with only the remaining mods installed?
      - Forge/Fabric and remaining mods, without OptiFine -->

**Comment by CrippledCowboy** [comment]
I'm experiencing the same problem which sucks because I just got a new computer and can only play with a controller due to a disability

**Comment by Avrution** [comment]
And... same thing.  Wondered why things kept crashing and this seems to be it.

**Comment by KaiAF** [comment]
I made a pull request for Controllable. https://github.com/MrCrayfish/Controllable/pull/465

Will be fixed when they merge

**Comment by MaxedOut655** [comment]
Hello! I am trying to compile your pull request, however it seems I am unable to do so, is there any other way to have it? Thanks!
