### ISSUE TITLE
Minecraft account stolen, cape locked so cannot move it to my new account

### ISSUE THREAD

**Issue by wmp71** [sp614x/optifine#7521]
Note: I asked this via E-mail mentioned in the optifine site, but no response for days so retrying it here.

my Minecraft account was stolen by a scammer. I had an OptiFine cape that my friend gifted. However it's locked and the friend won't respond my request of unlocking the cape. In this case will it be possible to move my cape to my new account? I know my friend's email address.

**Comment by SilentWhisperer** [comment]
you have to wait for your friend's response as you don't own the cape, your friend does
plus sp doesn't reply to emails quickly, it takes over 2 weeks from what i heard

**Comment by wmp71** [comment]
I kinda fighted with him about a year ago, and I haven't talked to him after that. I tried asking if he can unlock the cape, but he did read my message but didn't respond.

**Comment by Jiingy** [comment]
This is not the place for cape or account support, please refer to the discord support channel if you have not gotten a response yet from emails.
