### ISSUE TITLE
[Bug] Crash with Farmers Delight, ...

### ISSUE THREAD

**Issue by SkyKingPX** [sp614x/optifine#7526]
## Description of Issue
The game crashes on startup after you add optifine

## Steps to Reproduce
1. Download my Modpack "CreatePX" on CurseForge
2. add OptiFine (any Version)

## OptiFine Version
Minecraft 1.20.1 OptiFine HD U I6 pre6

## Installation Method
dropped the JAR file into "mods" Folder

## Fabric/Forge Version
43.1.3 - 47.1.43

## Other Installed Mods
In the Crash log

## Log Files/Crash Reports

https://github.com/vectorwing/FarmersDelight/files/12329796/crash-2023-08-13_17.27.26-client.txt

## F3 Debug Screenshot
Can't do that

## Prior Testing
Crashes Only with the Mods

**Comment by SilentSimulacrum** [comment]
Create not compatible

**Comment by SkyKingPX** [comment]
What does this mean @SilentSimulacrum ?

**Comment by SilentSimulacrum** [comment]
Optifine is not compatible with Create on 1.20.1. They cannot currently function together
