### ISSUE TITLE
[Crash] Forge crash

### ISSUE THREAD

**Issue by BaconDave312** [sp614x/optifine#7529]
## Description of Issue
Any version of optifine crashes

## Steps to Reproduce
1. install latest forge on 1.20.1
2. go play multiplayer
3. profit

## OptiFine Version
OptiFine_1.20.1_HD_U_I5

## Installation Method
downloaded from website and dropped into mods
## Fabric/Forge Version
47.1.44

## Other Installed Mods
WTHIT
badpackets
jei
journeymap

## Log Files/Crash Reports
[log.txt](https://github.com/sp614x/optifine/files/12378401/log.txt)

## F3 Debug Screenshot
no can do. crashes as soon as i join.

## Prior Testing
 No

## Additional Information
it happens either when i join anything, or multiplayer. for now i only did multiplayer, so i dont know.

**Comment by Lolothepro** [comment]
You're using the wrong version of Forge.
![image](https://github.com/sp614x/optifine/assets/68275908/70660afc-c325-429d-a508-a2fd80f6b065)

**Comment by BaconDave312** [comment]
thanks

**Comment by Algiuxs** [comment]
Close the issue
