### ISSUE TITLE
Random mob texture changes each time I log in

### ISSUE THREAD

**Issue by kcrca** [sp614x/optifine#753]
I have a bunch of villager textures, and villagers have attributes that distinguish them from each other. Specifically in my usage, it is which trades each knows, but for other players it might be names. And then there are dogs, cats, and other specific animals I might have around my home.

Each time I log in, a new random texture is assigned to each villager. This is conceptually confusing. I would like to recognize the mob by its texture within the same texture pack.

I think it is a pretty easy fix, actually. Each entity has a uuid. Use the lower bits of that uuid to seed a new random number generator for that entity for choosing textures and anything else randomly. Then, without storing any new info in the world save, you will always get the same texture chosen (unless someone changes the textures, of course.)

This would make this feature much more natural. Thanks!

**Comment by sp614x** [comment]
Updated preview C5 for 1.12
- fixed Random Mobs to use entity UUID in multiplayer

**Comment by kcrca** [comment]
Wow, that was fast! :-)

OOC, why only multiplayer? Aren't uuids available on singleplayer also?

**Comment by sp614x** [comment]
Single-player was already using the UUID. 
The UUID was not working for multiplayer because the server was not sending the UUID to the client. This have been fixed at some point, so now Random Mobs can use it.

**Comment by kcrca** [comment]
Ah, thanks!

		Ken
		健
