### ISSUE TITLE
[Bug] Anti-Aliasing crashes client

### ISSUE THREAD

**Issue by averagevideogamedude** [sp614x/optifine#7539]
## Description of Issue
I decided to increase the Anti-Aliasing slide a little bit just to make the textures smoother.. but once I restarted the game, it didn't show me a crash report, it showed me a error window. The window wouldn't close, so I had to end task in the Task Manager.

## Steps to Reproduce
1. Went to OptiFine's graphic control
2. Increased Anti-Aliasing from OFF to 6

## OptiFine Version
OptiFine HD U I5 for 1.20.1
Forge version: 47.0.35
Forge version I'm using: 47.1.0

## Installation Method
Dropped the JAR file to the mods folder.

## Fabric/Forge Version
Forge Version

## Other Installed Mods
https://pastebin.com/AJmAJ8RU

## Log Files/Crash Reports
Crash report wasn't in any notepad or in the minecraft's launcher, but it was a little message window saying: GFWL error: 65544: WGL: Failed to make context current: Controller not valid. Please make sure you have up-to-date drivers.

## Prior Testing
<!-- If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
No.

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
This wasn't an occasional bug, so I can't really tell.

- Does this happen without any mods at all?
This wasn't an occasional bug.

- Does this happen in OptiFine standalone?
This wasn't an occasional bug.

- Does this happen in Vanilla without OptiFine?
This wasn't an occasional bug.

- Have you tried using a binary search to find which mods cause this issue?
No conflicting mods as far as I know.

## Additional Information

**Comment by averagevideogamedude** [comment]
update: setting the anti-aliasing to ANY scale would just straight up crash the thing..

**Comment by KetchupGames** [comment]
I had the same problem.

These are my specs if they are possibly similar.
GPU: GTX 1080
CPU: AMD Ryzen 5 5600G 6 cores
RAM: 16gb

**Comment by Lolothepro** [comment]
![image](https://github.com/sp614x/optifine/assets/68275908/c7d5768f-0050-4059-9f12-d3777e45b667)
* not working: custom font widths, **AA with Forge above 47.0.3**

**Comment by KaiAF** [comment]
It's known, and in newer versions the setting is entirely disabled when launching with forge
