### ISSUE TITLE
[1.20.1]Create mod crash

### ISSUE THREAD

**Issue by jacobczn** [sp614x/optifine#7540]
## Description of Issue

Optifine crashes with create mod installed
## Steps to Reproduce
1. install optifine
2. install create
3. start the game
4. crash

## OptiFine Version

1.20.1 HD U I5
## Installation Method

mods folder installation
## Fabric/Forge Version

47.0.35
## Other Installed Mods

create
create: steam and rails
just enough items
storage drawers

## Prior Testing
 just enough items, storage drawers

**Comment by Regnander** [comment]
Maybe related to #7518

**Comment by Jiingy** [comment]
With no debug information to work off of, I'm closing this in favor of other Create Mod crash issues
