### ISSUE TITLE
JEI and Optifabric incompatible

### ISSUE THREAD

**Issue by SphoofXD** [sp614x/optifine#7553]
I have a small modpack that I made (containing about 11 mods), 2 of which are optifabric (including optifine) and JEI. When I try to launch the game I get the error message of "1" as in incompatible mods. I've tried almost every combination of mods and it's mainly JEI and Optifabric that reproduces this issue.

**Steps to Reproduce**
> Open the curseforge website
> Download Optifabric 1.18.2 to the CurseForge client
> Open the Optifine website
> Download the Optifine 1.18.2 mod
> Cut and Paste it into curseforges mod directory
> Launch the launcher
> Press play
> Get error message

**OptiFine Version**
OptiFine HD U H9

**Fabric/Forge Version**
Fabric 

**OptiFabric Version**
1.13.16

**Other Installed Mods**
Appleskin
Bad packets
Fabric API
JourneyMap
Just Enough Items (JEI)
Nature's Compass
Optifabric
Optifine
Origins
Simple voice chat
WTHIT

**Prior Testing**
Only happens when optifine, optifabric and Just Enough Items activated, this issue does not change if I add/remove mods, change the version; nothing else.

**Comment by omerien** [comment]
OptiFabric errors should be reported [here](https://github.com/Chocohead/OptiFabric). OptiFabric isn't supported by OptiFine.

**Comment by Jiingy** [comment]
Closing for previous comment
