### ISSUE TITLE
Getting Crashes when using your Optifine.

### ISSUE THREAD

**Issue by SirTwsted** [sp614x/optifine#7554]
When I turn on Optifine it crashes, when I turn it off its fine.
I talk to Sponge/Forge/Mixin , and they say its not them.

Crash Log
https://pastebin.com/d6vEfE6J

Mods List Used
https://pastebin.com/p4qRpyUw

Forge version 47.1.46  and also v47.1.47 (tried on both versions)

**Comment by SilentWhisperer** [comment]
first, try on forge version 43

**Comment by SirTwsted** [comment]
> first, try on forge version 43

Nope, still does not work.
I get this 
`The game crashed whilst unexpected error
Error: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered`

And this is the crash log.
https://pastebin.com/ettKyYGd

🤷‍♀️

**Comment by Jiingy** [comment]
You are using a substantial amount of mods. Please deduce which one is causing the issue, and where.
