### ISSUE TITLE
[CTM] ctm_compact doesn't work properly

### ISSUE THREAD

**Issue by Urartian1** [sp614x/optifine#7557]
Hello! I'm working on my own texture pack. Now I'm trying to make connected textures, but I have a problem with it. I don't know, how to fix it. Can someone help me? (look at the screenshots). (Java 1.17)

![obraz_2023-09-27_162302698](https://github.com/sp614x/optifine/assets/146207402/b7ca44b2-4df0-4e5b-8fe1-ca2b746e5686)

![obraz_2023-09-27_162316200](https://github.com/sp614x/optifine/assets/146207402/9eb13ea0-7745-41b1-bec4-a62b67643198)

**Comment by Urartian1** [comment]
> matchBlocks=minecraft:bedrock
> method=ctm_compact
> tiles=0-4
> connect=block
> faces=all

Sadly it's still dosen't work :/

**Comment by JimStoneCraft** [comment]
I believe the properties files have to be in lower case only or they don't load.

**bedrockconnect.properties** and not **BedrockConnect.properties**

**Comment by JimStoneCraft** [comment]
The errorlog shows this error:-

`[16:03:05] [Worker-Main-8/WARN]: [OptiFine] Skipping non-lowercase path: optifine/ctm/bedrock/Bedrockconnect.properties`

**Comment by Urartian1** [comment]
> The errorlog shows this error:-
> 
> `[16:03:05] [Worker-Main-8/WARN]: [OptiFine] Skipping non-lowercase path: optifine/ctm/bedrock/BedrockConnect.properties`

Still the same effect, but can you explain, where I can see the errorlog? It can help me to solve this.

**Comment by JimStoneCraft** [comment]
Logs are essential for pack development, I'm not sure in the official launcher as I use the MultiMC [https://multimc.org/](url), this is an alternative game launcher that's great for running multiple game version at once, this helps me with resource pack development.

Also turning on file extensions in Windows helps with your files too.

![Windows Filename Extension](https://github.com/sp614x/optifine/assets/42512910/ed76b577-4c9c-4bb3-9e83-09b0ce7ba707)

**Comment by saturnux** [comment]
hello,
all are in the log :

`[16:03:05] [Worker-Main-8/WARN]: [OptiFine] Skipping non-lowercase path: optifine/ctm/bedrock/BedrockConnect.properties`

**non-lowercase** path ==> optifine/ctm/bedrock/**B**edrock**C**onnect.properties 

enjoy

**Comment by ewanhowell5195** [comment]
the block has random rotations. you need to remove the random rotations from its blockstate

**Comment by Urartian1** [comment]
> the block has random rotations. you need to remove the random rotations from its blockstate

Thank you very match!
