### ISSUE TITLE
[Category] Short description

### ISSUE THREAD

**Issue by Sto3IV** [sp614x/optifine#7564]
## Description of Issue
Crash with Aether mod 1.3 for neoforge.
## Steps to Reproduce
1. NeoForge 1.20.1-47.1.79
2. Launch Minecraft with Aether mod 1.3 beta.

## OptiFine Version
OptiFine HD U I6 pre6, but I tried all versions for 1.20.1 and also tried to switch from neoforge to forge.

## Installation Method
mods folder

## Fabric/Forge Version
NeoForge 1.20.1-47.1.79

## Log Files/Crash Reports
https://pastebin.com/g2FEf7Xn
https://pastebin.com/1xFe78zC

## Does this happen without OptiFine?
- No

## Additional Information
In Aether Discord they said that they dont even know what is causing the crash, even less since optifine is closed source.

**Comment by Lolothepro** [comment]
Please change the name of your bug report

**Comment by KaiAF** [comment]
I fixed this in the [latest commit](https://github.com/The-Aether-Team/The-Aether/commit/893167639f0297370099143cc374c58ee0b4e374) for Aether. I have no idea when the version will be released, but eventually it will be.

**Comment by KaiAF** [comment]
The fixed jar file is [aether-1.20.1-1.0.0-beta.1.3-neoforge.jar](https://output.circle-artifacts.com/output/job/f2606d2b-c2f2-4d60-9b9b-5c5b3f67840e/artifacts/0/~/project/build/libs/aether-1.20.1-1.0.0-beta.1.3-neoforge.jar)
