### ISSUE TITLE
Minecraft Yellowish Filter

### ISSUE THREAD

**Issue by Keeper149** [sp614x/optifine#7568]
## Steps to Reproduce

I just launch Minecraft with Optifine. It doesnt matter if its only Optifine via the Minecraft Launcher or Lunar Client with Optifine enabled.

## OptiFine Version

All OptiFine Versions

## Installation Method

Executed the jar File, Lunar Client

## Log Files/Crash Reports

https://drive.google.com/file/d/1DJso4C2XnBj3A_X8z0Fow87R82Sk5lUu/view?usp=sharing

## F3 Debug Screenshot

![javaw_lShaaYK9lK](https://github.com/sp614x/optifine/assets/129172685/496fa171-7fd4-4853-a8d8-7618cca757a4)

## Prior Testing

<!-- If you've installed standalone:
- Does this happen in Vanilla without OptiFine?

No

- Does this happen in OptiFine standalone?

Yes

## Additional Information

Already tried Support on Discord but @Ari43 couldnt help me there sadly :c

**Comment by omerien** [comment]
Can you retry with OptiFine HD U I5?

**Comment by Ari-RERA-43** [comment]
Have you tested to see if this happens in Vanilla Minecraft?

**Comment by Keeper149** [comment]
Vanilla Minecraft works just fine :c

**Comment by Jiingy** [comment]
You're on lunar client.
