### ISSUE TITLE
Optifine works like normal, until...

### ISSUE THREAD

**Issue by Halogamer104** [sp614x/optifine#7569]
I only have BSL shaders installed +Forge 1.20.1 +Optfine 1.20.1 . I load into the main menu and everything works normal. Then I click a world, it loads, it pauses, and then without even seeing the actual game, it says "saving world" and exit outs the game. 

What I did to install:
 first I installed it via the install button, loaded up forge, no Optifine.
Then I put it in the mods folder, optfine is there, but it crashes (crash log underneath)

<html>
<body>

1 | ---- Minecraft Crash Report ----
-- | --
2 | // This doesn't make any sense!
3 |  
4 | Time: 2023-10-22 09:12:52
5 | Description: Unexpected error
6 |  
7 | java.lang.NoSuchMethodError: 'void net.minecraftforge.client.gui.overlay.ForgeGui.renderSelectedItemName(net.minecraft.client.gui.GuiGraphics, int)'
8 | at net.minecraftforge.client.gui.overlay.VanillaGuiOverlay.lambda$static$15(VanillaGuiOverlay.java:147) ~[forge-1.20.1-47.2.1-universal.jar%23163!/:?] {re:classloading}
9 | at net.minecraftforge.client.gui.overlay.ForgeGui.lambda$render$0(ForgeGui.java:126) ~[forge-1.20.1-47.2.1-universal.jar%23163!/:?] {re:classloading}
10 | at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.1-jre.jar%23109!/:?] {}
11 | at net.minecraftforge.client.gui.overlay.ForgeGui.m_280421_(ForgeGui.java:121) ~[forge-1.20.1-47.2.1-universal.jar%23163!/:?] {re:classloading}
12 | at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:1343) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
13 | at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
14 | at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
15 | at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-forge-47.2.1.jar:?] {re:classloading,pl:runtimedistcleaner:A}
16 | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
17 | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
18 | at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
19 | at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
20 | at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.1.jar:?] {}
21 | at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.1.jar:?] {}
22 | at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.1.jar:?] {}
23 | at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
24 | at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
25 | at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
26 | at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
27 | at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
28 | at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
29 | at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
30 | at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
31 |  
32 |  
33 | A detailed walkthrough of the error, its code path and all known details is as follows:
34 | ---------------------------------------------------------------------------------------
35 |  
36 | -- Head --
37 | Thread: Render thread
38 | Stacktrace:
39 | at net.minecraftforge.client.gui.overlay.VanillaGuiOverlay.lambda$static$15(VanillaGuiOverlay.java:147) ~[forge-1.20.1-47.2.1-universal.jar%23163!/:?] {re:classloading}
40 | at net.minecraftforge.client.gui.overlay.ForgeGui.lambda$render$0(ForgeGui.java:126) ~[forge-1.20.1-47.2.1-universal.jar%23163!/:?] {re:classloading}
41 | at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.1-jre.jar%23109!/:?] {}
42 | at net.minecraftforge.client.gui.overlay.ForgeGui.m_280421_(ForgeGui.java:121) ~[forge-1.20.1-47.2.1-universal.jar%23163!/:?] {re:classloading}
43 | -- Affected level --
44 | Details:
45 | All players: 1 total; [LocalPlayer['HaloGamer7784'/230, l='ClientLevel', x=175.06, y=68.00, z=-114.49]]
46 | Chunk stats: 4225, 737
47 | Level dimension: minecraft:overworld
48 | Level spawn location: World: (0,61,0), Section: (at 0,13,0 in 0,3,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
49 | Level time: 235713 game time, 415726 day time
50 | Server brand: forge
51 | Server type: Integrated singleplayer server
52 | Stacktrace:
53 | at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:590) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?] {re:classloading,xf:OptiFine:default}
54 | at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2319) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
55 | at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:740) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
56 | at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-forge-47.2.1.jar:?] {re:classloading,pl:runtimedistcleaner:A}
57 | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
58 | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
59 | at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
60 | at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
61 | at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.1.jar:?] {}
62 | at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.1.jar:?] {}
63 | at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.1.jar:?] {}
64 | at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
65 | at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
66 | at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
67 | at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
68 | at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
69 | at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
70 | at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
71 | at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
72 |  
73 |  
74 | -- Last reload --
75 | Details:
76 | Reload number: 1
77 | Reload reason: initial
78 | Finished: Yes
79 | Packs: mod_resources, vanilla
80 |  
81 | -- System Details --
82 | Details:
83 | Minecraft Version: 1.20.1
84 | Minecraft Version ID: 1.20.1
85 | Operating System: Windows 10 (amd64) version 10.0
86 | Java Version: 17.0.8, Microsoft
87 | Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
88 | Memory: 853678928 bytes (814 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
89 | CPUs: 32
90 | Processor Vendor: GenuineIntel
91 | Processor Name: 13th Gen Intel(R) Core(TM) i9-13900K
92 | Identifier: Intel64 Family 6 Model 183 Stepping 1
93 | Microarchitecture: unknown
94 | Frequency (GHz): 3.00
95 | Number of physical packages: 1
96 | Number of physical CPUs: 24
97 | Number of logical CPUs: 32
98 | Graphics card #0 name: NVIDIA GeForce RTX 3090 Ti
99 | Graphics card #0 vendor: NVIDIA (0x10de)
100 | Graphics card #0 VRAM (MB): 4095.00
101 | Graphics card #0 deviceId: 0x2203
102 | Graphics card #0 versionInfo: DriverVersion=31.0.15.4584
103 | Graphics card #1 name: Intel(R) UHD Graphics 770
104 | Graphics card #1 vendor: Intel Corporation (0x8086)
105 | Graphics card #1 VRAM (MB): 1024.00
106 | Graphics card #1 deviceId: 0xa780
107 | Graphics card #1 versionInfo: DriverVersion=31.0.101.4577
108 | Memory slot #0 capacity (MB): 16384.00
109 | Memory slot #0 clockSpeed (GHz): 5.60
110 | Memory slot #0 type: Unknown
111 | Memory slot #1 capacity (MB): 16384.00
112 | Memory slot #1 clockSpeed (GHz): 5.60
113 | Memory slot #1 type: Unknown
114 | Virtual memory max (MB): 37401.82
115 | Virtual memory used (MB): 17724.46
116 | Swap memory total (MB): 4864.00
117 | Swap memory used (MB): 130.07
118 | JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
119 | Launched Version: 1.20.1-forge-47.2.1
120 | Backend library: LWJGL version 3.3.1 build 7
121 | Backend API: NVIDIA GeForce RTX 3090 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 545.84, NVIDIA Corporation
122 | Window size: 854x480
123 | GL Caps: Using framebuffer using OpenGL 3.2
124 | GL debug messages: id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. Texture name does not refer to a texture object generated by OpenGL.' x 1
125 | Using VBOs: Yes
126 | Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
127 | Type: Integrated Server (map_client.txt)
128 | Graphics mode: fancy
129 | Resource Packs: vanilla
130 | Current Language: en_us
131 | CPU: 32x 13th Gen Intel(R) Core(TM) i9-13900K
132 | Server Running: true
133 | Player Count: 1 / 8; [ServerPlayer['HaloGamer7784'/230, l='ServerLevel[Best ever]', x=175.06, y=68.00, z=-114.49]]
134 | Data Packs: vanilla, mod:forge
135 | Enabled Feature Flags: minecraft:vanilla
136 | World Generation: Stable
137 | OptiFine Version: OptiFine_1.20.1_HD_U_I5
138 | OptiFine Build: 20230707-211226
139 | Render Distance Chunks: 29
140 | Mipmaps: 4
141 | Anisotropic Filtering: 1
142 | Antialiasing: 0
143 | Multitexture: false
144 | Shaders: BSL_v8.2.06 (3).zip
145 | OpenGlVersion: 4.6.0 NVIDIA 545.84
146 | OpenGlRenderer: NVIDIA GeForce RTX 3090 Ti/PCIe/SSE2
147 | OpenGlVendor: NVIDIA Corporation
148 | CpuCount: 32
149 | ModLauncher: 10.0.9+10.0.9+main.dcd20f30
150 | ModLauncher launch target: forgeclient
151 | ModLauncher naming: srg
152 | ModLauncher services:
153 | mixin-0.8.5.jar mixin PLUGINSERVICE
154 | eventbus-6.0.5.jar eventbus PLUGINSERVICE
155 | fmlloader-1.20.1-47.2.1.jar slf4jfixer PLUGINSERVICE
156 | fmlloader-1.20.1-47.2.1.jar object_holder_definalize PLUGINSERVICE
157 | fmlloader-1.20.1-47.2.1.jar runtime_enum_extender PLUGINSERVICE
158 | fmlloader-1.20.1-47.2.1.jar capability_token_subclass PLUGINSERVICE
159 | accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE
160 | fmlloader-1.20.1-47.2.1.jar runtimedistcleaner PLUGINSERVICE
161 | modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE
162 | modlauncher-10.0.9.jar OptiFine TRANSFORMATIONSERVICE
163 | modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE
164 | FML Language Providers:
165 | minecraft@1.0
166 | lowcodefml@null
167 | javafml@null
168 | Mod List:
169 | client-1.20.1-20230612.114412-srg.jar             \|Minecraft                     \|minecraft                     \|1.20.1              \|DONE      \|Manifest: ****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****
170 | forge-1.20.1-47.2.1-universal.jar                 \|Forge                         \|forge                         \|47.2.1              \|DONE      \|Manifest: ****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****
171 | Crash Report UUID: e6aa9879-899d-4ab1-b43f-338635a7ffb0
172 | FML: 47.2
173 | Forge: net.minecraftforge:47.2.1

</body>
</html>---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2023-[1](https://mclo.gs/UOkEb7t#L1)0-[2](https://mclo.gs/UOkEb7t#L2)2 09:12:52
Description: Unexpected error

java.lang.NoSuchMethodError: 'void net.minecraftforge.client.gui.overlay.ForgeGui.renderSelectedItemName(net.minecraft.client.gui.GuiGraphics, int)'
	at net.minecraftforge.client.gui.overlay.VanillaGuiOverlay.lambda$static$15(VanillaGuiOverlay.java:147) ~[forge-1.20.1-47.2.1-universal.jar%2[3](https://mclo.gs/UOkEb7t#L3)163!/:?] {re:classloading}
	at net.minecraftforge.client.gui.overlay.ForgeGui.lambda$render$0(ForgeGui.java:126) ~[forge-1.20.1-[4](https://mclo.gs/UOkEb7t#L4)7.2.1-universal.jar%23163!/:?] {re:classloading}
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.1-jre.jar%23109!/:?] {}
	at net.minecraftforge.client.gui.overlay.ForgeGui.m_280421_(ForgeGui.java:121) ~[forge-1.20.1-47.2.1-universal.jar%23163!/:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:1343) ~[client-1.20.1-20230612.114412-srg.jar%231[5](https://mclo.gs/UOkEb7t#L5)8!/:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:114[6](https://mclo.gs/UOkEb7t#L6)) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_913[7](https://mclo.gs/UOkEb7t#L7)4_(Minecraft.java:71[8](https://mclo.gs/UOkEb7t#L8)) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-forge-47.2.1.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.1.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:[9](https://mclo.gs/UOkEb7t#L9)9) ~[fmlloader-1.20.1-47.2.1.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-[10](https://mclo.gs/UOkEb7t#L10).0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraftforge.client.gui.overlay.VanillaGuiOverlay.lambda$static$15(VanillaGuiOverlay.java:147) ~[forge-1.20.1-47.2.1-universal.jar%23163!/:?] {re:classloading}
	at net.minecraftforge.client.gui.overlay.ForgeGui.lambda$render$0(ForgeGui.java:126) ~[forge-1.20.1-47.2.1-universal.jar%23163!/:?] {re:classloading}
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.1-jre.jar%23109!/:?] {}
	at net.minecraftforge.client.gui.overlay.ForgeGui.m_280421_(ForgeGui.java:121) ~[forge-1.20.1-47.2.1-universal.jar%23163!/:?] {re:classloading}
-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['HaloGamer7784'/230, l='ClientLevel', x=175.06, y=68.00, z=-[11](https://mclo.gs/UOkEb7t#L11)4.49]]
	Chunk stats: 4225, 737
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,61,0), Section: (at 0,13,0 in 0,3,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 235713 game time, 415726 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:590) ~[client-1.20.1-202306[12](https://mclo.gs/UOkEb7t#L12).114412-srg.jar%23158!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.m_9[13](https://mclo.gs/UOkEb7t#L13)54_(Minecraft.java:2319) ~[client-1.20.1-20230612.1[14](https://mclo.gs/UOkEb7t#L14)412-srg.jar%23[15](https://mclo.gs/UOkEb7t#L15)8!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:740) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-forge-47.2.1.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.1.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.1.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: mod_resources, vanilla

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 853678928 bytes (814 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 32
	Processor Vendor: GenuineIntel
	Processor Name: 13th Gen Intel(R) Core(TM) i9-13900K
	Identifier: Intel64 Family 6 Model 183 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 3.00
	Number of physical packages: 1
	Number of physical CPUs: 24
	Number of logical CPUs: 32
	Graphics card #0 name: NVIDIA GeForce RTX 3090 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2203
	Graphics card #0 versionInfo: DriverVersion=31.0.15.4584
	Graphics card #1 name: Intel(R) UHD Graphics 770
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0xa780
	Graphics card #1 versionInfo: DriverVersion=31.0.101.4577
	Memory slot #0 capacity (MB): [16](https://mclo.gs/UOkEb7t#L16)384.00
	Memory slot #0 clockSpeed (GHz): 5.60
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 5.60
	Memory slot #1 type: Unknown
	Virtual memory max (MB): 37401.82
	Virtual memory used (MB): [17](https://mclo.gs/UOkEb7t#L17)724.46
	Swap memory total (MB): 4864.00
	Swap memory used (MB): 130.07
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=[20](https://mclo.gs/UOkEb7t#L20) -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.20.1-forge-47.2.1
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: NVIDIA GeForce RTX 3090 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 545.84, NVIDIA Corporation
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. Texture name does not refer to a texture object generated by OpenGL.' x 1
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla
	Current Language: en_us
	CPU: 32x 13th Gen Intel(R) Core(TM) i9-13900K
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['HaloGamer7784'/230, l='ServerLevel[Best ever]', x=175.06, y=68.00, z=-114.49]]
	Data Packs: vanilla, mod:forge
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	OptiFine Version: OptiFine_1.20.1_HD_U_I5
	OptiFine Build: 20230707-[21](https://mclo.gs/UOkEb7t#L21)1[22](https://mclo.gs/UOkEb7t#L22)6
	Render Distance Chunks: 29
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: BSL_v8.2.06 (3).zip
	OpenGlVersion: 4.6.0 NVIDIA 545.84
	OpenGlRenderer: NVIDIA GeForce RTX 3090 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 32
	ModLauncher: 10.0.9+10.0.9+main.dcd20f30
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.5.jar eventbus PLUGINSERVICE 
		fmlloader-1.20.1-47.2.1.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.20.1-47.2.1.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.20.1-47.2.1.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.20.1-47.2.1.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.20.1-47.2.1.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar OptiFine TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.20.1-20[23](https://mclo.gs/UOkEb7t#L23)0612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |DONE      |Manifest: ****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****
		forge-1.20.1-47.2.1-universal.jar                 |Forge                         |forge                         |47.2.1              |DONE      |Manifest: ****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****
	Crash Report UUID: e6aa9879-899d-4ab1-b43f-[33](https://mclo.gs/UOkEb7t#L33)86[35](https://mclo.gs/UOkEb7t#L35)a7ffb0
	FML: [47](https://mclo.gs/UOkEb7t#L47).2
	Forge: net.minecraftforge:47.2.1

**Comment by Lolothepro** [comment]
Wrong version of Forge, caused by the user, not by Optifine

**Comment by Halogamer104** [comment]
> Wrong version of Forge, caused by the user, not by Optifine

if not Forge 1.20.1, then which one?

**Comment by Lolothepro** [comment]
There are different versions of Forge for Minecraft 1.20.1...

**Comment by Halogamer104** [comment]
> There are different versions of Forge for Minecraft 1.20.1...

Dude, i am extremely new to modding minecraft, so which one would work? Or, which optfine version would work with the current forge version I have?

**Comment by Lolothepro** [comment]
You are using OptiFine HD_U_I5, which is not compatible with Forge 47.2.1.
![image](https://github.com/sp614x/optifine/assets/68275908/daa03983-4603-4347-8ce4-04bf6ad84461)

**Comment by Halogamer104** [comment]
> You are using OptiFine HD_U_I5, which is not compatible with Forge 47.2.1. ![image](https://user-images.githubusercontent.com/68275908/277172344-daa03983-4603-4347-8ce4-04bf6ad84461.png)

So which  optfine do I use then?

**Comment by Lolothepro** [comment]
No Optifine version is compatible with Forge 47.2.1

**Comment by Halogamer104** [comment]
> No Optifine version is compatible with Forge 47.2.1

Okay, so how I install the proper version of forge?

**Comment by Lolothepro** [comment]
![sifgs](https://github.com/sp614x/optifine/assets/68275908/1a0d834a-e4c3-43d0-bc50-a5bd738a0e81)

**Comment by Halogamer104** [comment]
> ![sifgs](https://user-images.githubusercontent.com/68275908/277172543-1a0d834a-e4c3-43d0-bc50-a5bd738a0e81.jpg)

ok, then I choose the one optfine says should work?

**Comment by Lolothepro** [comment]
Yes, and close the bug report

**Comment by Halogamer104** [comment]
> Yes, and close the bug report

I dont see a forge 47.0.35?

**Comment by Lolothepro** [comment]
![image](https://github.com/sp614x/optifine/assets/68275908/13de09d5-f38e-4ad2-af1a-fdb35ad8dcfa)
.............

**Comment by Halogamer104** [comment]
> ![image](https://user-images.githubusercontent.com/68275908/277172856-13de09d5-f38e-4ad2-af1a-fdb35ad8dcfa.png) .............

oh I was looking at the wrong version
oops
