### ISSUE TITLE
[bug] custom blocks don't react to optifine custom grid colormap

### ISSUE THREAD

**Issue by gadyushnik** [sp614x/optifine#7572]
## Description of Issue

Hey. I have more like a question than a bugreport, but still I really need some help. 
So, I have baked blocks that I added and I've attached connected textures to them, which work as expected https://i.imgur.com/wNEdHag.png
And I also created a custom colormap in grid format and attached it to vanilla grass blocks and my custom blocks, but while with vanilla grass the colormap works as it should, my custom blocks are colored by the colormap only after **reloading the resources using hotkeys (I mean F3+T)**. I guess the problem is that custom colormaps define the blocks they should color by block id, not by tiles (like ctm methods can do), but maybe you can tell me something that might help me?

before the reloading
https://i.imgur.com/UN7J2CL.png
after the reloading
https://i.imgur.com/IKQwscL.png

**Comment by Jiingy** [comment]
This is not a help desk for OptiFine. Please direct questions to the OptiFine discord community server for help: discord.gg/OptiFine
