### ISSUE TITLE
1.12 Secret rooms mod bug

### ISSUE THREAD

**Issue by MintyGalaxyIces** [sp614x/optifine#7576]
In minecraft secret rooms mod if i use a ghost block the top of the block is always stone no matter what blocks are nearby and i discovered this issue by placing the block

**Comment by omerien** [comment]
- Does the error still happens if OptiFine is disabled?
- What is the list of mods you installed?
 - If you remove all of these mods to only keep OptiFine and Secret Rooms, does the bug still happen?
- Since it's a visual bug, do you have any shader/resource pack?
