### ISSUE TITLE
Minecraft Sound doesn't work with optifine c4

### ISSUE THREAD

**Issue by NBAKing0** [sp614x/optifine#758]
Whenever I launch minecraft and click the options it doesn't make sounds whenever I go to a normal account with no optofine sound works great! Pls help

**Comment by sixfootblue** [comment]
Been having the same issue too, but I found if you reload textures (press and hold down F3 + T) it fixes it.

**Comment by NintendoBest** [comment]
This is a issue that i already countered in the past, just the sound manager fail to lauch when the game is starting and loading everything, like say above, just reload your texture pack [ Or F3 + T ]

**Comment by sp614x** [comment]
Are you using the vanilla launcher?

**Comment by TrademarkTM** [comment]
Still happening in 1.12.2 (C5).
`F3 + T` works, but it's annoying because you have to wait all textures to load again.

Currently using vanilla launcher, with ONLY optifine.
Happens in about 75% of the cases. In pure vanilla the sounds works fine.

**Comment by sp614x** [comment]
This is strange, OptiFine does not change the loading of the sound resources.
Can you post the output log: http://hopper.minecraft.net/help/guides/minecraft-logs/

**Comment by TrademarkTM** [comment]
https://hastebin.com/voyoyeyipo.hs

Sorry, took a while to respond.
I used `F3 + T` after joining the server (after my join message), if it's important.

**Comment by sp614x** [comment]
The sound library OpenAL can't initialize properly:
```
chm	Starting up SoundSystem...
chm	Initializing LWJGL OpenAL
chm	(The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
game	AL lib: (EE) MMDevApiOpenPlayback: Device init failed: 0x80004005
AL lib: (EE) MMDevApiOpenPlayback: Device init failed: 0x80004005
  <log4j:Event logger="chm" timestamp="1506645157694" level="ERROR" thread="Thread-4">
    <log4j:Message><![CDATA[Error in class 'LibraryLWJGLOpenAL']]></log4j:Message>
  </log4j:Event>
monitor	expected <
chm	Unable to initialize OpenAL.  Probable cause: OpenAL not supported.
chm	ERROR MESSAGE:
chm	Could not locate OpenAL library.
chm	STACK TRACE:
chm	org.lwjgl.openal.AL.create(AL.java:156)
chm	org.lwjgl.openal.AL.create(AL.java:102)
chm	org.lwjgl.openal.AL.create(AL.java:206)
chm	paulscode.sound.libraries.LibraryLWJGLOpenAL.init(LibraryLWJGLOpenAL.java:164)
chm	paulscode.sound.SoundSystem.CommandNewLibrary(SoundSystem.java:1576)
chm	paulscode.sound.SoundSystem.CommandQueue(SoundSystem.java:2572)
chm	paulscode.sound.CommandThread.run(CommandThread.java:121)
chm	ERROR MESSAGE:
chm	Could not locate OpenAL library.
chm	Starting up SoundSystem...
chm	Switching to No Sound
chm	(Silent Mode)
```

**Comment by sp614x** [comment]
The low-level library can't open the sound device: 
```
AL lib: (EE) MMDevApiOpenPlayback: Device init failed: 0x80004005
```

**Comment by TrademarkTM** [comment]
Could you add a shortcut to reload only the sound library (if possible)? Like `F3 + Y`.
I usually use 64x64+ textures and shaders, and it takes an entire year to reload.

Thanks.

**Comment by NerfyZygon** [comment]
Hey, I got a problem with my sound too, dont know what the problem is, can anyone look into it?
[latest.log](https://github.com/sp614x/optifine/files/1948291/latest.log)

**Comment by Fixer-007** [comment]
Same problem on 1.12.2 with Optifine D3, Windows 7, MultiMC 0.6.2, VIA HDA sound, default textures, pastebin of logs: https://pastebin.com/raw/mqUCyqxh 
Somewhere in console I've seen "Device init failed: 0x80004005"

F3 + T ingame restores sound, sound then somehow works even after restarts, weird.

**Comment by ryankhart** [comment]
I can confirm this is still an issue on OptiFine 1.12.2 HD E3 Ultra. I was playing Enigmatica 2: Expert for many hours. Then I installed Optifine, changed nothing else, and the second time the game loaded, I no sound. I tried F3 + T, but that took about 10 minutes and when I finally had control again, I was looking at a death screen.

**Comment by KaiAF** [comment]
If anyone is still having this issue, please create a new bug report. This doesn't seem to be an OptiFine issue anyways
