### ISSUE TITLE
[Texture Issue] Leggings Appear Enchanted Without Enchants

### ISSUE THREAD

**Issue by NexOccisor** [sp614x/optifine#7580]
I was using OptiFine HD U I5 pre5 and noticed all the leggings have the enchanted overlay when equipped, only the 3d model has the enchanted texture, and it's only the leggings.

**Comment by Ari-RERA-43** [comment]
- Are you using any resource packs?
- Are you on a server?
- What's the Minecraft version you're on? If it's 1.20.1, test the latest version (pre6).

**Comment by Jiingy** [comment]
Closing for Details Needed
