### ISSUE TITLE
[Bug] Smooth Lightning not working

### ISSUE THREAD

**Issue by 2Sloow** [sp614x/optifine#7586]
Im using Forge OptiFine_1.19.2_HD_U_I2 with other mods and the smooth lightning (with and without shaders) is bugged with some blocks. PC Specs: RTX 3060 Laptop, I7-11800H, 16gb ram (8gb assigned to minecraft)

WITH shaders
![2023-12-15_18 59 12](https://github.com/sp614x/optifine/assets/143907774/527de78a-5865-467a-b373-6e9af82bf029)
![2023-12-15_19 04 19](https://github.com/sp614x/optifine/assets/143907774/5fa9b452-5e62-4d30-b09a-f36e5473ab8d)

WITHOUT shaders
![2023-12-15_18 59 41](https://github.com/sp614x/optifine/assets/143907774/9b83df23-c669-4140-bfce-604d7f3f728a)
![2023-12-15_19 04 57](https://github.com/sp614x/optifine/assets/143907774/fd231e4f-8f13-4104-8adf-2f1339a165d7)

## Other Installed Mods

appleskin-forge-mc1.19-2.4.2.jar
artifacts-1.19.2-5.0.4.jar
AutoRegLib-1.8.2-55.jar
bettercombat-forge-1.7.1+1.19.jar
BetterThirdPerson-Forge-1.19-1.9.0.jar
caelus-forge-1.19.2-3.0.0.6.jar
canary-mc1.19.2-0.2.8.jar
carryon-forge-1.19.2-2.1.1.22.jar
charmofundying-forge-6.2.1+1.19.2.jar
cloth-config-8.3.103-forge.jar
Clumps-forge-1.19.2-9.0.0+14.jar
comforts-forge-6.0.6+1.19.2.jar
connectivity-1.19.2-4.6.jar
create_enchantment_industry-1.19.2-for-create-0.5.1.f-1.2.7.d.jar
create-1.19.2-0.5.1.f.jar
cupboard-1.19.2-2.1.jar
curios-forge-1.19.2-5.1.4.3.jar
customizableelytra-1.19.0-1.7.4.jar
deeperdarker-forge-1.19.2-1.2.2.jar
DiagonalFences-v4.2.6-1.19.2-Forge.jar
EasyAnvils-v4.0.11-1.19.2-Forge.jar
EasyMagic-v4.3.3-1.19.2-Forge.jar
effective_fg-1.3.4.jar
ElytraPhysicsForge-1.1.1.jar
elytraslot-forge-6.1.1+1.19.2.jar
EnchantingInfuser-v4.2.2-1.19.2-Forge.jar
Entity_Collision_FPS_Fix-forge-1.19-2.0.0.0.jar
entityculling-forge-1.6.1-mc1.19.2.jar
Essential-forge_1-19-2.jar
Fallingleaves-1.19.1-1.3.1.jar
FallingTree-1.19.2-3.10.1.jar
FramedBlocks-6.8.6.jar
Highlighter-1.19.1-1.1.4.jar
Iceberg-1.19.2-forge-1.1.4.jar
Incendium_1.19.3_v5.1.6.jar
invhud.forge.1.19-3.4.7.jar
Jade-1.19.1-forge-8.9.1.jar
jei-1.19.2-forge-11.6.0.1018.jar
JustEnoughResources-1.19.2-1.2.3.243.jar
lootr-1.19-0.4.24.64.jar
moonlight-1.19.2-2.3.5-forge.jar
MouseTweaks-forge-mc1.19-2.23.jar
Paraglider-1.19.2-1.7.0.5.jar
ParCool-1.19.2-3.1.0.6-R.jar
PickUpNotifier-v4.2.4-1.19.2-Forge.jar
player-animation-lib-forge-1.0.2.jar
polymorph-forge-0.46.5+1.19.2.jar
PuzzlesLib-v4.4.3-1.19.2-Forge.jar
Quark-3.4-418.jar
smoothchunk-1.19.2-3.5.jar
sophisticatedbackpacks-1.19.2-3.19.4.977.jar
sophisticatedcore-1.19.2-0.5.109.516.jar
starlight-1.1.1+forge.cf5b10b.jar
supplementaries-1.19.2-2.4.13.jar
tempad-forge-1.19.2-1.4.5.jar
Throwability-1.19.2-2.0.0.0-R.jar
tombstone-8.2.12-1.19.2.jar
toms_storage-1.19-1.5.9.jar
ToolBelt-1.19.2-1.19.7.jar
visuality-forge-2.0.2.jar
VisualWorkbench-v4.2.4-1.19.2-Forge.jar
weaponmaster-multiplayer-forge-1.19.2-3.0.5.jar
Xaeros_Minimap_23.9.3_Forge_1.19.1.jar
XaerosWorldMap_1.37.2_Forge_1.19.1.jar
xlpackets-1.18.2-2.1.jar
YungsApi-1.19.2-Forge-3.8.10.jar
YungsBetterDesertTemples-1.19.2-Forge-2.2.2.jar
YungsBetterDungeons-1.19.2-Forge-3.2.2.jar
YungsBetterEndIsland-1.19.2-Forge-1.0.jar
YungsBetterJungleTemples-1.19.2-Forge-1.0.1.jar
YungsBetterMineshafts-1.19.2-Forge-3.2.1.jar
YungsBetterNetherFortresses-1.19.2-Forge-1.0.6.jar
YungsBetterOceanMonuments-1.19.2-Forge-2.1.1.jar
YungsBetterWitchHuts-1.19.2-Forge-2.1.0.jar
YungsBridges-1.19.2-Forge-3.1.0.jar
YungsExtras-1.19.2-Forge-3.1.0.jar

**Comment by Jiingy** [comment]
Please ensure the vanilla "smooth lighting" options are set properly/to their respective maximums, and also try to reproduce this in regular OptiFine with no mods, or forge installed. It's impossible to tell what could cause this issue with so many mods.
