### ISSUE TITLE
1.20.2: OptiFine causes some flickering in the F3 menu

### ISSUE THREAD

**Issue by Lolothepro** [sp614x/optifine#7587]
OptiFine:

https://github.com/sp614x/optifine/assets/68275908/2b2494e3-f841-4cb8-b7c8-39697f6a7dbf

Vanilla:

https://github.com/sp614x/optifine/assets/68275908/c4ba740c-9a13-4571-bacc-d281468ed39a

Discord conv (OptiKai): https://discord.com/channels/423430686880301056/471762249476734977/1159566755056857179

**Comment by KawaMood** [comment]
How did you even manage to use F3 on Optifine 1.20.2? 
For me it just crashes the game.
[crash-2024-01-12_19.24.05-client.txt](https://github.com/sp614x/optifine/files/13922785/crash-2024-01-12_19.24.05-client.txt)

**Comment by Lolothepro** [comment]
> How did you even manage to use F3 on Optifine 1.20.2? For me trying to open the F3 screen just crashes the game. [crash-2024-01-12_19.24.05-client.txt](https://github.com/sp614x/optifine/files/13922785/crash-2024-01-12_19.24.05-client.txt)

![image](https://github.com/sp614x/optifine/assets/68275908/9831170e-6785-49ab-a886-c94ccbc2dd47)
***not compatible with Forge***

**Comment by Vilo659** [comment]
dang i forgot its not compatible

**Comment by sp614x** [comment]
Fixed, coming in next preview.
