### ISSUE TITLE
[CIT] CIT renaming on anvil doesn't work on OptiFine 1.20.4

### ISSUE THREAD

**Issue by Alexander-alt-creator** [sp614x/optifine#7598]
version : OptiFine 1.20.4 HD U I7 pre2 . 
When renaming items on the anvil to change models and textures, nothing happens.
But if you install a later version (OptiFine_1.20.1_HD_U_I6). And do the same thing with the same texture pack, then everything will work.
When installing a new version, things with new models remain, but creating the same items is no longer possible. if a CIT item is returned to its original name, its texture is reset, but when it is renamed back to CIT, the texture does not change.
I am attaching a video on youtube   https://youtu.be/odP4QdzqVVw
![CIT reanaming on anvil dosent work on OptiFine 1 20 4](https://github.com/sp614x/optifine/assets/77934731/30d17042-42b0-4b88-bdcb-8dbe8c745b99)

**Comment by ZeonBT** [comment]
can confirm this the newest update (OptiFine HD U I7 pre5) all the items from 1.20.1 have stayed in but spawning CIT items using the anvil will result it converting back to the og item. 

*temp fix* Incidentally i found that when spawning a mob using tellraw and placing the CIT item with 100% in the name and the item material... on killing the mob the item gen will work and you get the item

**Comment by sp614x** [comment]
Test resource pack?

**Comment by ZeonBT** [comment]
do you want to test it as im sure the pack is up to date as well as the properties are correct... i tried to reach out on discord first but i got sent here

https://github.com/sp614x/optifine/assets/44127152/80fd8e7c-d420-495f-a2f8-90b3dc6261d5

**Comment by ZeonBT** [comment]
If it helps i did look at the first release of 1.20.4 pre 2 and the CIT renaming on an anvil is fully broken...so what fix you did slightly worked when renaming the item.. but the ntb doesnt stay when the item is touched or placed in the inv 

on top of the way i found by spawning the items using mobs....i noticed it works by using a item generator and both worked and can see the item

**Comment by ZeonBT** [comment]
i take it this has something to do with  my texture pack ? or my version of MC ?

**Comment by ZeonBT** [comment]
I have have done very through testing on this and the problem isnt my pack... i have been making pack for the past 13 years 

I have tested very version of the Pre versions of Optifine pre 2 and on wards till Pre 5 where I found this bug where the anvil CIT wouldn't spawn but the CIT items in the world in 1.20.1 where still there. 
I tested Pre 6 and Pre 7 with the realised version as well as pre 8 would spawn the items but when click they will disappear back to the default item with the CIT name on it... like in the video above

If this is pack related then something from 1.20.1---1.20.4 has changed but why would they continue to keep the old CIT items but not allow new items spawn ...and  what do i need to do to fix this as i have un-installed mc, re installed every optifine version... cleaned my pack of any thing thats not working and even downloaded a NTB plugin... nothing still but the fact the models dont show in pre 2 - pre5 and then from pre 6 and onwards i can see the models but they revert back to the item means its something optifine codes then on my end...


if you need the texture pack to confirm this i will be more then happy to send it over 
and if there anything i can help with please let me know
