### ISSUE TITLE
[CEM - Feature request] add a new part to the bat.jem part list for the new 1.20.4 bat model

### ISSUE THREAD

**Issue by Traben-0** [sp614x/optifine#7599]
1.20.4 should probably add the `feet` part to the bat.jem CEM model parts

with the new vanilla bat model the feet have an additional animation separate from the body and people might want to capture that in simple models.

Resourcepack makers have to change their models anyway as pivots, texture uvs, and boxes have changed. 
So there isn't a legacy support concern here

**Comment by sp614x** [comment]
Added
