### ISSUE TITLE
Invisible Blocks (1.10.2 HD U E3)

### ISSUE THREAD

**Issue by SoloCoburn** [sp614x/optifine#760]
So I've been playing with Optifine in FTB Beyond. And some blocks seem to be invisble...

**Currently these blocks seem to be missing (will update if found more):**
- Ardite Ore (Tinkers' Construct)
- Cobalt Ore (Tinkers' Construct)
- Storage Drawers, Any (Storage Drawers) (However, you can still see when blocks are inside it)

When optifine is removed, the blocks are visible again.

**Screenshots:**
https://puu.sh/wG5ud/bcd65235ad.png
https://puu.sh/wG5wI/a4799f73a3.png

**Specs:**
- Nvidia GTX1060
- Ryzen 1600x
- 16gb ram (6gb allocated)
- Windows 10

**Other information:**
- Forge version 12.18.3.2316
- FTB Beyond version 1.10.00
- Optifine 1.10.2 HD U E3

**Additional Notes:**
- Optifine 1.10.2 HD U D8 has same issue

_If you need any more information, let me know. I will provide if possible._

**Comment by SetantaLP** [comment]
That looks very strange. So it might help if you post the log-file, because if something went wrong, mods often show warnings in the log.

**Comment by SoloCoburn** [comment]
After reinstall of the pack, I could not reproduce the same issue.
It might be because Better Foliage and Dynamic Surroundings are installed, so I'm going to look into it more. I'll report when I know something.

**Comment by SoloCoburn** [comment]
After another run, I can confirm that it's also the blame of Better Foliage. I presume it's some kind of weird compatibility issue, so I can't exactly blame Optifine.

In any case, it's fixed so...

**Comment by SetantaLP** [comment]
Okay. So maybe you should check if this issue also happens in other better foliage versions and then report it to their issue-page, so that they can check if they maybe accidentally changed something between the versions, which might cause the issue.
