### ISSUE TITLE
[Bug] Clean Glass not working with Optifine

### ISSUE THREAD

**Issue by Rydein8** [sp614x/optifine#7600]
## Description of Issue

When using the resource packs from Vanilla Tweaks Clean Glass, Clean Stained Glass and Clean Tinted Glass are not showing as connected within Minecraft. I have tried on a normal local game world without the resource pack the connected glass does work with Optifine, however when the resource pack contains the above 3 options the Glass is clean but it is not connecting. 

## Steps to Reproduce

As above, resource pack compatibility issue, I have confirmed with a more complex resource pack and a resource pack with just the 3 above mentioned options and the issue is the same.

## OptiFine Version

1.20.4 (OptiFine HD U I7 pre2)

## Installation Method

Standard installer

## Log Files/Crash Reports

Not relevant.

## F3 Debug Screenshot

Not relevant

## Prior Testing

<!-- If you've installed standalone:
- Does this happen in Vanilla without OptiFine?

Not an option for the mod compatibility

## Additional Information

As above, the issue relates to the compatibility with Vanilla Tweaks.

**Comment by sp614x** [comment]
Fixed, coming in next 1.20.4 preview.

**Comment by Rydein8** [comment]
Amazing thank you!
