### ISSUE TITLE
I'm trying to do something with optifine models but it doesn't work.

### ISSUE THREAD

**Issue by 3geETR** [sp614x/optifine#7603]
[test.zip](https://github.com/sp614x/optifine/files/13932815/test.zip)

I tried all kinds of things, I tried with tags, I tried with names, but I can't do it, I can't put 2 textures.
What's wrong with this texture pack?

**Comment by Jiingy** [comment]
This repo is for bug reports, and is not intended to function as a help desk. Please refer to the community Discord server for resource pack help: https://discord.gg/optifine
