### ISSUE TITLE
Is it possible to open source versions that are no longer maintained(1.12.2 and below)?

### ISSUE THREAD

**Issue by jiongjionger** [sp614x/optifine#7607]
Hello,

I hope this message finds you well. I wanted to bring something to your attention regarding the older versions of Optifine, specifically versions 1.12.2 and below. It appears that there are no plans for further updates on these versions. I would like to suggest considering the possibility of open-sourcing these older versions, allowing the community to continue updating them. This would not only benefit the community but also make it easier for other mod authors to ensure compatibility with Optifine.

Thank you for your time and consideration.

Best regards

**Comment by Jiingy** [comment]
Open sourcing OptiFine is not possible, or at least not planned for the forseeable future.

**Comment by AngelOfCreation** [comment]
> Open sourcing OptiFine is not possible, or at least not planned for the forseeable future.

Why? Every other mod manages to do it, what's so special about you?
