### ISSUE TITLE
Whole computer slowdown after launch.

### ISSUE THREAD

**Issue by supadoom** [sp614x/optifine#761]
After adding OptiFine 1.10.2 HD U E3, launching Minecraft causes my computer to lockup for 500MS every second. As soon as the Minecraft window opens ( After 30-45 seconds) the issues ceases and doesn't hamper game play. Even the desktop and mouse are affected. I have tested with other Optifine versions and they are fine. Tried both vanilla and modded MC. Both MultiMC launcher and vanilla launcher. Finally tried rolling back my GPU drivers to ones that I had a previous modpack with Optifine running. So far the only thing that makes it not do it is removing Optifine or using an older version. My system specs are as follows:

i7 4790k Stock speeds.
AMD RX 480 Stock speeds.
12 Gb's of ram. (5 Being given to Minecraft in the modded tests and 4 in vanilla.)
Stock MC settings and stock Optifine settings.

**Comment by sp614x** [comment]
Vanilla Minecraft does not need more than 1GB RAM.
Can you try with less RAM allocated to MC?
Is OptiFine D8 for 1.10.2 working?

**Comment by supadoom** [comment]
I know vanilla MC doesn't need much but didn't want to change the tests in significant ways.
I'll test vanilla with 1-2 Gb's of ram. Probably 1 first.
D8 works fine without the issue.

**Comment by supadoom** [comment]
Any update on this? I forgot to mention that my above edit, I had tested it on vanilla with 1Gb of ram with no luck.

**Comment by mindforger** [comment]
last time my PC locked up repeatedly was an strange driverbug with intel rapid storage ... updating my chipset and the rapid storage driver fixed the issue ... it was causing an unmaskable interrupt that stopped time on my PC every couple of seconds for a few milliseconds when the pagefile was used heavily

**Comment by supadoom** [comment]
This however is not random or repeating oddly. This occurs only during the point when java initializes the render window. After the Minecraft window pops up it locks up the computer. Also I have linked it to Optifine causing this through process of elimination.

**Comment by sp614x** [comment]
This my be related to https://github.com/sp614x/optifine/issues/501 and https://github.com/mezz/JustEnoughItems/issues/746
You can try to disable VSync or use newer Forge version (if running with Forge).

**Comment by supadoom** [comment]
Tested with Vsync off. (Set FPS cap to unlimited) No luck. I tested this with Forge 2239-2316 with no luck. I'm going to update to the new AMD driver and will get back to you with that. On a side note during this lockup if I have any other hardware accelerated application, Discord for example it will make each element in the discord UI flash briefly one by one.

**Comment by supadoom** [comment]
New AMD driver version 17.7.1 did not fix the issue.

**Comment by supadoom** [comment]
So I found that the issue triggers on this section of log output every time: 
[02:50:31] [Client thread/INFO] [NowWithRendering]: renderBlockDamage patched
[02:50:31] [Client thread/INFO] [NowWithRendering]: renderBlock patched
[02:50:51] [Client thread/WARN]: Skipping bad option: lastServer:
[02:50:51] [Client thread/INFO]: LWJGL Version: 2.9.1

**Comment by sp614x** [comment]
The log output is not from OptiFine, some other mod is patching base classes and has problems.
The line "NowWithRendering" may come from "Redstone Paste" or "HopperDucts".

**Comment by supadoom** [comment]
Will try removing redstone paste and hopper ducts one by one with optifine installed.

**Comment by supadoom** [comment]
Any updates or idea's on what I can do at this point?

**Comment by sp614x** [comment]
You can try to reproduce it with minmal amount of mods installed to find the problematic mod.
Remove half of the mods, test again, repeat until it stops making problems, then continue with the last removed mods until there is only one mod left which still reproduces the problem.

**Comment by supadoom** [comment]
Well I have already done that. To the point of having it be vanilla with optifine.

**Comment by sp614x** [comment]
So OptiFine standalone (no Forge) has the same problem?

**Comment by supadoom** [comment]
Correct

**Comment by sp614x** [comment]
Running in fullscreen or windowed?

**Comment by supadoom** [comment]
Windowed. Already tried disabling window's 10 "Fullscreen Optimazations"

**Comment by supadoom** [comment]
So assuming the same functionality is there in OpenGL, then nothing is hooking.

**Comment by sp614x** [comment]
Have you tried with another launcher, for example the classic one (https://minecraft.net/en-us/download/alternative)?
The new modern launcher has a badly designed console and struggles with mods which generate a lot of log entries.

**Comment by supadoom** [comment]
Using the legacy launcher worked perfect! Also lowering ram is something we have already tried.

**Comment by sp614x** [comment]
Looks like the problem is with the new launcher.
You can post a launcher bug report: https://bugs.mojang.com/projects/MCL/issues
