### ISSUE TITLE
Token Dynamic Lighting

### ISSUE THREAD

**Issue by lotsofland** [sp614x/optifine#7611]
Really like the handheld feature of torches glowing as you walk. When playing hard core you must trade off the ability for the permanent token in worlds that have been alive a while. 

Could you guys add a setting to add dynamic lighting to tokens just like the torches?

**Comment by KaiAF** [comment]
What is a token?

**Comment by lotsofland** [comment]
well i meant the totem of undying, but after posting this i realized the
glow effect of torches comes from shaders rather than optifine.

appreciate your help but i think i came to the wrong place for suggestions.

**Comment by KaiAF** [comment]
Well, OptiFine does have a dynamic lighting feature.
Since the Totem of undying item does not emit any light, it can't have dynamic lighting.

**Comment by lotsofland** [comment]
what could i do to cause it to emit light? could i change a texture pack to
mirror the glow of the torches?
