### ISSUE TITLE
[Bug Report]My PC Crashes when I open Optifine

### ISSUE THREAD

**Issue by Kraycek511** [sp614x/optifine#7613]
My Optifine Crashes

When I start Minecraft 1.20.4 with Optifine everything its OK but a few a seconds it crashes and I have to restart the PC

## Steps to Reproduce

1. Open MInecraft Launcher
2. Open Optifine 
3. Open a World
4. It crashes...

## OptiFine Version
Optifine_1.20.4

## Installation Method

It's an unmeasured optifine folder is as good as new-->

##

**Comment by KaiAF** [comment]
Send the latest.log file. It can be found in the .minecraft\logs folder.

**Comment by Kraycek511** [comment]
For what?

**Comment by KaiAF** [comment]
So I can see why it crashed

**Comment by Kraycek511** [comment]
OK

**Comment by Kraycek511** [comment]
[latest.log](https://github.com/sp614x/optifine/files/14133263/latest.log)
This?

**Comment by KaiAF** [comment]
No, this shows as using sodium and iris. Try to reproduce the crash then re-send latest.log. That file just shows the *latest* log for the game.

**Comment by Kraycek511** [comment]
[latest.log](https://github.com/sp614x/optifine/files/14133397/latest.log)

**Comment by Kraycek511** [comment]
[latest.log](https://github.com/sp614x/optifine/files/14133611/latest.log)

**Comment by Kraycek511** [comment]
Did you figure it out?

**Comment by KaiAF** [comment]
The log you showed doesn't display any errors. Go to .minecraft and see if you have a file that starts with `hs_error`, if so, send that.

**Comment by Kraycek511** [comment]
For Optifine to work, do I have to put its file in the mods folder?

**Comment by RealmKebab** [comment]
> For Optifine to work, do I have to put its file in the mods folder?

what modloader are you even using man

**Comment by RealmKebab** [comment]
if you're using fabric, optifine wont work on fabric and instead is recommend to use sodium
if you're using forge, then optifine will work

**Comment by Kraycek511** [comment]
Yeah it is working

**Comment by Kraycek511** [comment]
Thanks
