### ISSUE TITLE
Why this cit optifine minecraft code don't working with color? 

### ISSUE THREAD

**Issue by Conefka** [sp614x/optifine#7619]
matchItems=minecraft:netherite_boots
nbt.display.Name=ipattern:*§2§lKrólicze Buty*
model=buty.json

this is code from properties code cit optifine 
what I have to change it?

I also have a second json file that looks like this:

{
  "parent": "minecraft:item/handheld",
  "textures": {
    "layer0": "minecraft:item/buty"
  }
}

**Comment by Conefka** [comment]
> what version

1.19.2

**Comment by Jiingy** [comment]
This repo is not a resource pack helpdesk. If you would like resource pack help, please refer to our community run discord server, where we have a select channel to talk about resource pack making.

discord.gg/optifine
