### ISSUE TITLE
[CIT] Elytra textures are broken

### ISSUE THREAD

**Issue by Polda18** [sp614x/optifine#7620]
## Description of Issue
I've made a server resource pack that uses Optifine's CIT features for custom elytra textures (given majority of our players use Optifine). The issue is the elytra textures are broken. All of them. I do not use Optifine personally (because I'm playing on Fabric and I use mods that are incompatible with Optifine), but I've decided to give it a shot after number of players complained about the elytra textures being broken, and all of them reported they've got Optifine installed. Turns out they're right and the RP doesn't work properly with Optifine. It's strange tho, because the CIT format is specifically made for Optifine, and it works just fine with CIT Resewn mod I use, which is compatible with Optifine's CIT format. Not to mention that players have to disable their cape if they want to use the custom elytra texture with Optifine (which is not needed with CIT Resewn).

## Steps to Reproduce
1. Install Optifine
2. Enable server resource pack (or if you have the resource pack locally, enable that)
3. Equip custom elytra item with specified predicates in the CIT config files (in my case, the CustomModelData NBT)

## OptiFine Version
Optifine HD U I6 for MC 1.20.1

## Installation Method
Standalone, but players reported issues with Forge version and OptiFabric with the installer JAR in mods folder as well. The point is, the standalone mod breaks the textures as well, which is what most players use.

## Used resource pack
[camellot_rp.zip [108 kB]](https://camellot.eu/uploads/resource-pack/camellot_rp.zip)

## Screenshots
Elytras with Optifine:
![All of the elytras used with Optifine](https://czghost.is-a-virg.in/6s079zu0p.png)
![Equipped elytra with Optifine](https://czghost.is-a-virg.in/6s07qSNNV.png)

Elytras with CIT Resewn (Fabric):
![All of the elytras used with CIT Resewn](https://czghost.is-a-virg.in/6s07zW6Qy.png)
![Equipped elytra with CIT Resewn](https://czghost.is-a-virg.in/6s07JvZpH.png)

Note: I did no changes to the resource pack between mods switch. It is the same resource pack.

**Comment by sp614x** [comment]
The resource pack properties uses texture path relative to the current folder:
```
type=elytra
nbt.CustomModelData=350204
texture=entity/elytra_phantom.png
```
The resolved path is `assets/minecraft/optifine/cit/entity/elytra_phantom.png`.

To use absolute texture path:
```
texture=textures/entity/elytra_phantom.png
```
Then the resolved path would be `assets/minecraft/textures/entity/elytra_phantom.png`.

The path resolving rules: https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/properties_files.txt#L29

**Comment by Polda18** [comment]
So Optifine expect the texture to be in the CIT directory if the leading `textures/` directory specification is ommited? Cool. I hope it doesn't break compatibility with CIT Resewn, which is what I'm using. It shouldn't, as it's designed to work with Optifine resource packs. Well, thank you, I'll try it out tomorrow with both CIT Resewn (to make sure the compatibility isn't broken), and most notably with Optifine to verify it helped. If anything, I can reopen the issue or open a new one.

**Comment by Polda18** [comment]
Everything's fine, the resourcepack is fixed. Thank you for your help.
