### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by rxznve** [sp614x/optifine#7623]
Can I change some settings in Optifine to make Minecraft render even those blocks that are covered by other blocks on all sides?
Can I add geometry to an object without changing its original geometry? For example, draw a circle of lines around the player.

**Comment by Ari-RERA-43** [comment]
- No, rendering every face of every block would tank performance on even the most powerful of computers 
- That would probably be better done with a mod, or possibly a shader.

**Comment by rxznve** [comment]
> or possibly a shader.
But I already wanted to write a shader, the problem is that I don't know how to do this (add geometry to an object without breaking the original geometry of the object)

**Comment by sp614x** [comment]
For some blocks it is possible to use custom block models (https://minecraft.fandom.com/wiki/Tutorials/Models#Block_models).
The check if block sides are to be rendered depends on the block type and a custom model can't help for solid blocks.
Adding other geometry can be added with mods (easier) or shaders (complex).

**Comment by Lolothepro** [comment]
*https://minecraft.wiki/w/Tutorials/Models#Block_models
