### ISSUE TITLE
[Random Entities] heights.X property isn't working correctly

### ISSUE THREAD

**Issue by DraminOver** [sp614x/optifine#7624]
## Description of Issue

the _**heights.X**_ property stopped working as it should in the last few releases.

i created a test pack. in it i applied a gray texture (3) for all creepers under Y=60 and left the normal creeper (2) for Y=60 and above
```
## Caves ##
skins.1=  3
heights.1=(-64)-60

## Surface ##
skins.2=  2
heights.2=60-320
```
using that example, optifine seems to only pull the textures from "caves" at every height

```
## Surface ##
skins.1=  2
heights.1=60-320

## Caves ##
skins.2=  3
heights.2=(-64)-60
```
even when you switch the order of the parameters optifine seems to always favor the one with lowest height, as in this example the only texture appearing is still the one from "caves"
## Steps to Reproduce

-- create a pack using heights.X parameter
or
-- use the test resourcepack i added
[Test.zip](https://github.com/sp614x/optifine/files/14411262/Test.zip)

## OptiFine Version

the issue starts from _**OptiFine 1.20.2 HD U I7 pre1**_  up to _**OptiFine 1.20.4 HD U I7 pre2**_. it worked fine in the version before.

## Installation Method

installer

**Comment by enqorman** [comment]
How is it completed?
