### ISSUE TITLE
[Shader] Normal texture of held map item is incorrect

### ISSUE THREAD

**Issue by GeForceLegend** [sp614x/optifine#7627]
## Description of Issue

Normal texture sample for held map item always be (0.5, 0.5, 0.5, 0.5) without resource packs. Only the real map content is affected, edge of map is working fine.

## Steps to Reproduce

1. Using sp614x's [SuperTester shaderpack](https://github.com/sp614x/SuperTester)
2. Set setting GBUFFER_DEBUG to NORMALS_TEXTURE, COLOR_WEIGHT to 1.0
3. Hold a map item and see its content is gray
4. Change line 31 of `shaders/gbuffers_common.glsl` to get the alpha channel of normal texture, reload shaders, and see content of held map item is still gray
```glsl
#elif GBUFFER_DEBUG == NORMALS_TEXTURE
	debug = texture2D(normals, texcoord).www;
```

## OptiFine Version

1.20.1 I6

## Installation Method

Standalone

## F3 Debug Screenshot

Setting GBUFFER_DEBUG to NORMALS_TEXTURE, COLOR_WEIGHT to 1.0
![2024-03-10_09 37 42](https://github.com/sp614x/optifine/assets/41003546/fa4eb26c-12ee-44fd-974b-01fe77ef34b6)

Modified code to get alpha channel of normal texture
![2024-03-10_09 38 35](https://github.com/sp614x/optifine/assets/41003546/416db288-0a5d-422d-b640-4f8eaf9ca1f4)

## Additional Information

Nsight Graphics capture showing the normal texture is all pure 0x7f
![20240310104444](https://github.com/sp614x/optifine/assets/41003546/688eee02-685d-4fd0-a976-05e94275e921)

**Comment by sp614x** [comment]
Fixed, coming in next preview.
