### ISSUE TITLE
[1.20.4 Bug] Suspicious stew CIT is not working in 1.20.4

### ISSUE THREAD

**Issue by SeaOfPixels** [sp614x/optifine#7628]
## Description of Issue
CIT support for suspicious stew seems to have broken in the transition from OptiFine 1.20.1 to OptiFine 1.20.4.

## OptiFine Version
OptiFine 1.20.4_HD_U_I7_pre2, OptiFine 1.20.4_HD_U_I7_pre4, OptiFine 1.20.4_HD_U_I7_pre5

![OptiFine 1 20 4 Suspicious Stew CIT](https://github.com/sp614x/optifine/assets/62183036/15914f83-08eb-4ba2-a907-5310d2e3c53e)

**Comment by sp614x** [comment]
Test resource pack?

**Comment by SeaOfPixels** [comment]
[NewDefault+OnlyStew.zip](https://github.com/sp614x/optifine/files/14620715/NewDefault%2BOnlyStew.zip)

**Comment by sp614x** [comment]
The NBT format has been changed and the RP has to be updated:
- 1.20.1 - `{Effects:[{EffectDuration:7,EffectId:23}]}`
- 1.20.4 - `{effects:[{duration:7,id:"minecraft:saturation"}]}`

**Comment by SeaOfPixels** [comment]
What does the new properties file string look like for this new NBT? The existing one is `nbt.Effects.0.EffectId=iregex:(23)`.
