### ISSUE TITLE
[1.20.4] Block-breaking overlay is darker with OptiFine (with Chest??)

### ISSUE THREAD

**Issue by Lolothepro** [sp614x/optifine#7629]
## Description of Issue

Block-breaking overlay is darker with OptiFine

## Steps to Reproduce

1. Try to break a chest in survival mode with OptiFine
2. Try to break a chest in survival mode in Minecraft Vanilla
Compare

## OptiFine Version

OptiFine 1.20.4_HD_U_I7_pre6

## Installation Method

Prism Method

## Screenshot

With OptiFine:

![2024-03-15_17 16 42](https://github.com/sp614x/optifine/assets/68275908/701cbbfc-7802-456b-89ab-781735aae812)

With Vanilla:
![2024-03-15_17 17 59](https://github.com/sp614x/optifine/assets/68275908/cf2448dd-eb47-486c-806b-1712ce42b930)

**Comment by sp614x** [comment]
Fixed
