### ISSUE TITLE
1.11.2 installation problem

### ISSUE THREAD

**Issue by SmallEnderman** [sp614x/optifine#763]
I tried to install optifine but whenever i open the jar an BAT run appears says something about an error and then closes i tried everything but it somehow doesnt work.... i even watched some videos on how it might work but nope... they didnt work i even tried to do this with multiverse (an program that allows you to create modpacks) and guess what's not working? optifine.... now idk if this is the program or my laptop/pc but... pls help

**Comment by SmallEnderman** [comment]
Note: the file that i download is a jar file and whenever i start it says something about error... cant find something

**Comment by HeartyYF** [comment]
I just wonder if your downloaded jar file is complete, or if you have installed JRE.
By the way, if you don't paste your error information then I don't think someone can help you.

**Comment by SmallEnderman** [comment]
welp the download was complete and even before i can notice the error it's already gone... like within 1 milisecond it's already gone.... so cant easly say the error... and the download jar is completed i even downloaded all the links that were available for 1.11.2

**Comment by sp614x** [comment]
Make sure to install Java first: https://java.com/en/download/

**Comment by SmallEnderman** [comment]
i have java already installed...  to be exactly java 8 update 73 (64x bit)

**Comment by SmallEnderman** [comment]
i even updated the newest one and still doesnt work

**Comment by sp614x** [comment]
If you are using Windows:
- right click on jar -> open with -> choose program... -> select "Java (TM) Platform SE binary".
- optionally, check the "Always use the selected programm to open this kind of file".

**Comment by NintendoBest** [comment]
"welp the download was complete"
If it's on Window, then window's download " complete" can show has complete even though the file doesn't have everything it need to work properly, so it can happen peoples believe it's complete when it's more like uncompleted.
So try to redownload it.

**Comment by HeartyYF** [comment]
You can try to open the jar file using 7-zip or some other compression softwave.If you can't open it either, then it can be broken.

**Comment by SmallEnderman** [comment]
@NintendoBest i redownloaded all the 1.11.2 links that were available on the optifine site... i even did what @sp614x told me to do... to open it with java (TM) Platform SE Binary with no success...  i even tried with 7-zip that heartyYF told me... with no success either

**Comment by SmallEnderman** [comment]
Note: i have discovered what it says as error it says following

Error: could not find or load main class C:\Users\(name)\Downloads\Optifine_1.11.2_HD_U_C3 (3).jar

**Comment by sp614x** [comment]
Make sure to use Java 8, it is required since Minecraft 1.11.

**Comment by SmallEnderman** [comment]
java 8 update 73 (64x bit) is what i use... i even deleted it and installed Java 8 update 131 and yet doesnt work

**Comment by puuska** [comment]
shift+ppm and choose open command prompt here. type java -jar filename.jar and press enter. it will show entire log

**Comment by SmallEnderman** [comment]
how do i shift+ppm... srry but i cant find that "ppm" part

**Comment by puuska** [comment]
Right mouse button

**Comment by Barteks2x** [comment]
Just a note: ppm is only in polish, not english. English probably has RMB or something like that.

**Comment by HeartyYF** [comment]
Oh...I mean if you can't open the jar through a compression softwave(e.g. 7-zip and Winrar)then the jar file can be broken.

**Comment by SmallEnderman** [comment]
one question tho which forge do you use for the latest 1.11.2 optifine? just the latest forge or? (btw still havent fixed it)

**Comment by SmallEnderman** [comment]
NVM i found another solution to people who have this problem use this
http://bit.ly/jarfix
