### ISSUE TITLE
[1.20.4] The "Fog Start" setting does not work in the Nether

### ISSUE THREAD

**Issue by Lolothepro** [sp614x/optifine#7630]
## Description of Issue

The "Fog Start" setting does not work in the Nether

## Steps to Reproduce

1. Go in Nether
2. Try to change the "Fog Start" value
3. Nothing happens

## OptiFine Version

OptiFine 1.20.4_HD_U_I7_pre7

## Installation Method

Prism Method

## Screenshot

Fog Start: 0.2

![2024-03-16_14 25 09](https://github.com/sp614x/optifine/assets/68275908/de842ee8-cecb-4c91-8f6f-cbae32a2b8c9)

Fog Start: 0.8

![2024-03-16_14 25 21](https://github.com/sp614x/optifine/assets/68275908/ca62a9c1-9af9-47b6-9264-a535dcd0e4ac)

## Video

https://github.com/sp614x/optifine/assets/68275908/8a6c0d42-70fc-4383-891c-5a476417c43a

**Comment by sp614x** [comment]
This is by design, the nether is supposed to be gloomy and scary.
