### ISSUE TITLE
[1.20.4] In some OptiFine settings, text can be displayed in the text background of another.

### ISSUE THREAD

**Issue by Lolothepro** [sp614x/optifine#7632]
## Description of Issue

In some OptiFine settings, text can be displayed in the text background of another.

## Steps to Reproduce

Go to performance settings
Click on "Chunk Builder"
The two texts overlap"

## OptiFine Version

OptiFine 1.20.4_HD_U_I8_pre1

## Installation Method

Prism

## Screenshot

![2024-03-18_17 52 27](https://github.com/sp614x/optifine/assets/68275908/b9cd8e9e-4089-4b49-8340-5a6260a70654)
![2024-03-18_17 52 35](https://github.com/sp614x/optifine/assets/68275908/f2f7fe93-7c89-4eea-8696-5a7e2776a170)

**Comment by sp614x** [comment]
Fixed, coming in next preview.
