### ISSUE TITLE
[1.20.4] Using the mouse wheel to change the GUI scale does nothing

### ISSUE THREAD

**Issue by Lolothepro** [sp614x/optifine#7634]
## Description of Issue

Using the mouse wheel to change the GUI scale does nothing

## OptiFine Version

OptiFine 1.20.4_HD_U_I8_pre1

## Installation Method

Prism

## Video

https://github.com/sp614x/optifine/assets/68275908/685e63e6-468e-4ba1-b1d7-b39ef208a564

**Comment by sp614x** [comment]
Fixed, coming in next preview
