### ISSUE TITLE
Anvil not Renaming CIT items 

### ISSUE THREAD

**Issue by ZeonBT** [sp614x/optifine#7635]
I have have done very through testing on this and the problem isnt my pack... i have been making pack for the past 13 years

I have tested very version of the Pre versions of Optifine pre 2 and on wards till Pre 5 where I found this bug where the anvil CIT wouldn't spawn but the CIT items in the world in 1.20.1 where still there.
I tested Pre 6 and Pre 7 with the realised version as well as pre 8 would spawn the items but when click they will disappear back to the default item with the CIT name on it... like in the video below

If this is pack related then something from 1.20.1---1.20.4 has changed but why would they continue to keep the old CIT items but not allow new items spawn ...and what do i need to do to fix this as i have un-installed mc, re installed every optifine version... cleaned my pack of any thing thats not working and even downloaded a NTB plugin... nothing still but the fact the models dont show in pre 2 - pre5 and then from pre 6 and onwards i can see the models but they revert back to the item means its something optifine codes then on my end...

I can spawn the items when using a Mob gen and item spawner from command blocks but when renaming in the anvil the items bug out 

if you need the texture pack to confirm this i will be more then happy to send it over
and if there anything i can help with please let me know
## Fabric/Forge Version

Java 1.20.4

## Other Installed Mods

Only Optifine

## Log Files/Crash Reports

no error logs showing 

https://github.com/sp614x/optifine/assets/44127152/bbb656d8-3bcf-4511-acfc-5c0470369b67

**Comment by ZeonBT** [comment]
https://www.dropbox.com/scl/fi/x9mma7tdgfu719zvy8cqs/Mindcorp-1.20.4-V1.0.0.2.zip?rlkey=6asyaygssqrck26vktiuvvfel&dl=0

**Comment by sp614x** [comment]
Works for me:

![image](https://github.com/sp614x/optifine/assets/16635441/8fd5d1c1-e96b-40e1-83df-c73594413ce3)

![image](https://github.com/sp614x/optifine/assets/16635441/f833f641-e4b0-4ccb-a9ea-e4e07d99b03c)

![image](https://github.com/sp614x/optifine/assets/16635441/5fc8a139-21d0-46ca-abeb-1d3a69751dc5)

![image](https://github.com/sp614x/optifine/assets/16635441/e677f795-a7bb-4793-ae36-eb8b2430765b)

**Comment by sp614x** [comment]
Is OptiFine running standalone or with Forge?

**Comment by ZeonBT** [comment]
> Is OptiFine running standalone or with Forge?
 standalone only optifine is the only mod installed

**Comment by sp614x** [comment]
Tested with Forge, also works.

**Comment by sp614x** [comment]
Tested in the given test world, works fine.

**Comment by ZeonBT** [comment]
what jar are you using btw may be it could be that as im using paper and purpur

**Comment by sp614x** [comment]
The official launcher + OptiFine 1.20.4 I8_pre2.

**Comment by sp614x** [comment]
Can you post the whole error log?
OF/MC complains about a lot of missing textures/models.

**Comment by ZeonBT** [comment]
sure thing

**Comment by ZeonBT** [comment]
is this an error log from my server or the .minecraft folders ?

**Comment by ZeonBT** [comment]
[latest.log](https://github.com/sp614x/optifine/files/14672986/latest.log)
this is the latest log from the .minecraft folders

**Comment by sp614x** [comment]
The `.minecraft/logs/latest.log`
If you play on a server then the server may be manipulating the item NBT tag in some way.

**Comment by Jiingy** [comment]
If it helps, I cannot reproduce this either.
https://github.com/sp614x/optifine/assets/69827559/6f325c6f-0332-4ff6-9d1e-193803134899

**Comment by ZeonBT** [comment]
so this could be plugin related or jar related then ?

**Comment by ZeonBT** [comment]
mmmh i tested it on single player and it worked so now begs the question is jar related or plugin related... ive never had this problem with any other version of mc or optifine so its new to me... sorry for the hassle

**Comment by ZeonBT** [comment]
okay i found it is Items adder that interfering with it... again i so sorry... didnt expect a plugin to interfere with optifine in this way... love the new FPS info look btw and with this ill close this down
