### ISSUE TITLE
[CTM] <default> tile produces warning in log

### ISSUE THREAD

**Issue by Polydot** [sp614x/optifine#7640]
## Description of Issue

if you use the <default> tile for a texture in CTM it works as intended, but produces a warning in the log

## Steps to Reproduce

1. use <default> as a tile in a CTM properties file
2. check logs

## OptiFine Version

at least OptiFine HD U I7 & OptiFine HD U I8 pre1

## Installation Method

included installer

## Log Line
[12:29:18] [Render thread/WARN]: [OptiFine] Missing CTM sprite: minecraft:default, properties: optifine/ctm

## F3 Debug Screenshot

![314479425-919cdfc6-2e3a-40e7-a166-5134fdd209b0](https://github.com/sp614x/optifine/assets/5259390/3626f1fd-f1ae-4b38-8d1d-d520c8fca794)

## Final remark

The default textures DO work normally, so there doesn't seem to be anything I can change

**Comment by sp614x** [comment]
Fixed, coming in next preview.
