### ISSUE TITLE
[BUG] Quick info "All: OFF" setting turns framerate option to `Compact` instead of `OFF`

### ISSUE THREAD

**Issue by Jiingy** [sp614x/optifine#7645]
The `All: OFF` setting will turn the framerate setting to `Compact` instead of `OFF`, leaving it on the screen.
https://github.com/sp614x/optifine/assets/69827559/af0f61ce-4709-46d2-9b1b-0a203fba23c0

**Comment by SyndiShanX** [comment]
The Setting also doesn't impact Labels at all

**Comment by sp614x** [comment]
Fixed to set Framerate to OFF.
Labels and Background are not affected by design.
