### ISSUE TITLE
[1.20.4 Bug] Arrow CEM is not working in 1.20.4

### ISSUE THREAD

**Issue by SeaOfPixels** [sp614x/optifine#7646]
## Description of Issue
The new CEM support for arrows and spectral arrows in OptiFine 1.20.4_HD_U_I8_pre3 seems to not be working.

## OptiFine Version
OptiFine 1.20.4_HD_U_I8_pre3

Test resource pack:
[NewDefault+OnlyCemArrows.zip](https://github.com/sp614x/optifine/files/14718066/NewDefault%2BOnlyCemArrows.zip)

![OptiFineCemArrowBug1](https://github.com/sp614x/optifine/assets/62183036/56bb6bc5-4991-4571-b9a0-ef0bafd6ab8b)
![OptiFineCemArrowBug2](https://github.com/sp614x/optifine/assets/62183036/0999243d-4933-4389-819e-dff4375654de)

**Comment by sp614x** [comment]
The JEMs use the wrong bone name `arrow`, the correct one is `body`.
```
[OptiFine] CustomEntityModel: optifine/cem/arrow.jem
[OptiFine] Model part not found: arrow, model: net.optifine.entity.model.ArrowModel@2d628a7d
[OptiFine] CustomEntityModel: optifine/cem/spectral_arrow.jem
[OptiFine] Model part not found: arrow, model: net.optifine.entity.model.ArrowModel@2809e8ea
```
