### ISSUE TITLE
你好！我想请你帮我看看这个是怎么回事

### ISSUE THREAD

**Issue by xiaolaiya** [sp614x/optifine#7657]
请你帮我看看

_Originally posted by @xiaolaiya in https://github.com/sp614x/optifine/issues/7654#issuecomment-2057758815_

**Comment by xiaolaiya** [comment]
一启动就出现错误报告

**Comment by xiaolaiya** [comment]
和模组用

**Comment by xiaolaiya** [comment]
[Uploading 错误报告-2024-4-16_19.30.43.zip…]()

**Comment by xiaolaiya** [comment]
[latest.log](https://github.com/sp614x/optifine/files/14996225/latest.log)

**Comment by CyanurePV** [comment]
Did you try without the Embeddium mod as said on this [issue ](https://github.com/sp614x/optifine/issues/7654#issuecomment-2058943978)?
Embeddium is not compatible with OptiFine (source [here](https://github.com/embeddedt/embeddium#:~:text=OptiFine%20is%20not%20supported%20for%20obvious%20reasons))

**Comment by Jiingy** [comment]
Please only report issues in English.
