### ISSUE TITLE
[Render Regions] Render Regions makes terrain rendering performance worse

### ISSUE THREAD

**Issue by GeForceLegend** [sp614x/optifine#7660]
## Description of Issue

FPS drops a lot when enable Render Regions, caused by reduced terrain rendering performance

## Steps to Reproduce

1. Load a Minecraft world
2. Enable/Disable `Options > Video Settings > Performance > Render Regions` and see the framerate difference

## OptiFine Version

1.20.4 I8 Pre3

## Installation Method

Standalone

## F3 Debug Screenshot

With Render Regions on:
![2024-04-27_18 43 58](https://github.com/sp614x/optifine/assets/41003546/2797da66-6b47-4a70-9170-f52491ec566a)

With Render Regions off:
![2024-04-27_18 44 26](https://github.com/sp614x/optifine/assets/41003546/95a8666d-ee3c-4c4f-bbff-024b2a200ec0)

## Prior Testing

Captured some frames using Nsight Graphics' GPU Trace method, and found that when enable render regions, terrain rendering is sliced to pieces, making terrain rendering comsumes much more time. Captured over 5 frames on each situation and terrain rendering part is almost same.
Render regions off:
![RenderRegionsOff](https://github.com/sp614x/optifine/assets/41003546/8747f971-7578-4aba-896d-9057c8a9e842)
Render regions on:
![RenderRegionsOn](https://github.com/sp614x/optifine/assets/41003546/c87de89d-e5a3-4a5b-884b-63fd043c62e9)

## Additional Information

Optifine setting file:
[optionsof.txt](https://github.com/sp614x/optifine/files/15137929/optionsof.txt)

**Comment by GeForceLegend** [comment]
Found that Smooth FPS will also drop the framerate. In almost same scene as above, disable Smooth FPS makes framerate raise from about 900 to 1400+. If those things do not have a positive effect on high versions, it might be better deleting them

**Comment by sp614x** [comment]
Render Regions can help when the CPU is slower or the upload bandwidth is not enough and as a result the GPU is not working at 100%. In your case the GPU is loaded at 100% so Render Regions is not going to help.
Smooth FPS is designed to stabilize the framerate, not to increase it. In fact it usually decreases it a little, but removes the fluctuations. For example without Smooth FPS the framerate may vary between 80 and 200 fps (average 140) and with Smooth FPS it may be stable 120. The minimum FPS defines how the game feels (lag spikes), so increasing it from 80 to 120 is a significant improvement.
