### ISSUE TITLE
Custom Model Data (Or other NBT) for CEM items

### ISSUE THREAD

**Issue by el-piedras** [sp614x/optifine#7668]
I know this must've been suggested to death but surprisingly I didn't find anything specifically for this:

The ability to choose *exactly* when and which CEM models will be used on CEM models.
For example, the trident entity model can be edited with CEM, but doing so replaces *every* trident in the world, with no ability (To my knowledge) of changing that since it isn't a "real" entity in the world.

This could be done by setting a specific NBT tag such as `CustomEntityModel:number`, similar to how `CustomModelData` works, and a new list property in the model.jem file named similarly that only applies the model to entities or item entities with given tag.

**Comment by ewanhowell5195** [comment]
this simply isnt possible. that is why it isn't a thing

**Comment by Jiingy** [comment]
Closing for the reason provided by ewan
