### ISSUE TITLE
[Render Distance Bug] Render distance slider not updating distance properly or consistently

### ISSUE THREAD

**Issue by Jiingy** [sp614x/optifine#7675]
When changing the value of the render distance slider option, it will not properly update the render distance in game. Notably, closing the settings menu with ESC directly after changing the slider will just keep the value the same.

Here is a video showing the issue:
https://github.com/sp614x/optifine/assets/69827559/d96e1509-522f-4845-9d1b-a0f244edb707

**Comment by sp614x** [comment]
Fixed, coming in next preview

**Comment by SeaOfPixels** [comment]
Still not fixed in pre13.
