### ISSUE TITLE
Custom colors colormaps get randomized (optifine 1.20.6)

### ISSUE THREAD

**Issue by Emfire12345** [sp614x/optifine#7676]
Tested with OptiFine 1.20.6_HD_U_I9_pre1
Features in question are custom colors colormaps, tested with grid colormaps.

Issue is that the colormap doesnt choose the right color that it should, even worse is that this changes every time i restarted the game.

Test1:
![try1](https://github.com/sp614x/optifine/assets/108950145/d9dee0cc-bc38-4490-9a0d-6b406e07ec6b)
Test2:
![try2](https://github.com/sp614x/optifine/assets/108950145/96c32760-b669-4864-aff9-7f6fd62bcf19)

**Comment by SeaOfPixels** [comment]
Can confirm, colormaps are currently incorrect.
![2024-06-08_14 39 31](https://github.com/sp614x/optifine/assets/62183036/4700ba33-206f-4cc4-8eeb-d63d92e6cf34)

**Comment by SnobbyBlobby** [comment]
Can also confirm : 
![t1](https://github.com/sp614x/optifine/assets/172203111/0e3e59fa-af2d-47d7-969f-ca2c22e430f8)
![t2](https://github.com/sp614x/optifine/assets/172203111/9dc095f4-7966-4077-b539-eb5c39107193)

Also randomizes everytime I close the game.

**Comment by Pineapple71717** [comment]
While it does randomize the colormaps, atleast on my end they dont seem to change every time I re-launch the game
![2024-06-15_18 44 53](https://github.com/sp614x/optifine/assets/158485824/48886943-eba9-4833-b65b-6f5cb884c2f9)
![2024-06-15_18 40 55](https://github.com/sp614x/optifine/assets/158485824/0f644147-cfe9-48ca-9407-362c50328b08)
![2024-06-15_18 37 44](https://github.com/sp614x/optifine/assets/158485824/774b41bb-49ac-4d89-88af-c4b56d5e7f74)
![2024-06-15_18 33 23](https://github.com/sp614x/optifine/assets/158485824/93aee03e-1e55-466c-b890-7c2c3551be3d)
![2024-06-15_18 32 05](https://github.com/sp614x/optifine/assets/158485824/8f6194c3-82dd-41bb-94d3-d601b905a502)
![2024-06-15_18 31 20](https://github.com/sp614x/optifine/assets/158485824/52c207c4-2c1c-414c-9c62-6beb6b2cb815)
![jlkhjghsdgb](https://github.com/sp614x/optifine/assets/158485824/d37a94da-75cd-47cc-b2cf-73146b6bf18f)

**Comment by SeaOfPixels** [comment]
It's not that the colormaps are randomizing, it's that the gridmap IDs are incorrect. This happens all the time during OptiFine development when updating to new whole number versions.

**Comment by Emfire12345** [comment]
> It's not that the colormaps are randomizing, it's that the gridmap IDs are incorrect. This happens all the time during OptiFine development when updating to new whole number versions.

In the last few version that happend because they added new biomes which offset the IDs, 1.21 didnt add a single new biome and the IDs are not shifted, they are shuffled all over the place, if the plains biome gets the wrong color you know something is messed up badly.

**Comment by SeaOfPixels** [comment]
> > It's not that the colormaps are randomizing, it's that the gridmap IDs are incorrect. This happens all the time during OptiFine development when updating to new whole number versions.
> 
> In the last few version that happend because they added new biomes which offset the IDs, 1.21 didnt add a single new biome and the IDs are not shifted, they are shuffled all over the place, if the plains biome gets the wrong color you know something is messed up badly.

No, this has happened multiple times before in update transitions that had no new biomes or changes to the IDs.

**Comment by SyndiShanX** [comment]
It would be nice if we could specify the columns using the Biome Namespace ID in the .properties file

**Comment by Emfire12345** [comment]
> It would be nice if we could specify the columns using the Biome Namespace ID in the .properties file

I wish we could have 256x256 colormaps for each biome, were 1 pixel = 1 block, similar to how colormaps were applied pre beta 1.8, then you could literally paint the landscape

**Comment by SeaOfPixels** [comment]
I think the current method would be fine if gridmaps didn't keep extending past the farthest vanilla ID (End Barrens) into the unused IDs. This currently breaks grid colormap compatibility with mods that use unused biome IDs for their modded biomes. The gridmaps should only apply the columns that are actually used by vanilla (currently that's ID 0 to 63, so ID 64 onward would ignore gridmaps).

**Comment by SyndiShanX** [comment]
But mod compatibility is something we want

**Comment by SeaOfPixels** [comment]
The current method breaks when multiple sources (datapacks/mods) use the same biome IDs anyways, which is very likely to happen.

**Comment by SyndiShanX** [comment]
Namespace IDs would fix that

**Comment by SeaOfPixels** [comment]
Ye just doing everything in a file would be best, however I think that's way less likely to happen since it'd be way more work for SP, so I tried suggesting something that I thought would be less taxing.

**Comment by Baby-FarkMcGeezax** [comment]
Besides the randomising (which is weird), grass colormaps don't seem to work AT ALL for me. Only displaying the vanilla colours, while water and fog and all is still recoloured (randomly).
Could be related to [#7259](https://github.com/sp614x/optifine/issues/7259) and/or [#7699](https://github.com/sp614x/optifine/issues/7699) ?

**Comment by SeaOfPixels** [comment]
Can confirm in OptiFine 1.21_HD_U_J1_pre6.

**Comment by sp614x** [comment]
Fixed, coming in next 1.21 preview
