### ISSUE TITLE
[1.20.6] Entity culling is broken with the minecraft:generic.scale attribute

### ISSUE THREAD

**Issue by Lolothepro** [sp614x/optifine#7677]
## Steps to Reproduce

1. `/time set midnight`
2. `/summon minecraft:zombie ~ ~10 ~ {NoAI:1}`
3. `/attribute @e[type=minecraft:zombie,limit=1] minecraft:generic.scale base set 3`

## Video

https://github.com/sp614x/optifine/assets/68275908/9dbd81bf-9ed4-4fd7-baaa-1189580340e0

**Comment by Lolothepro** [comment]
Affects Minecraft 1.21.1

**Comment by sp614x** [comment]
Fixed, coming in next preview.
