### ISSUE TITLE
[1.20.6 - Quick Info] Gamerule "Reduceddebuginfo" and optifine's quick info

### ISSUE THREAD

**Issue by ThatOneMeganium** [sp614x/optifine#7678]
In game, it is possible to disable viewing coordinates through f3 if the gamerule "reduceddebuginfo" is enabled, which is very convenient if you are, for example, making a map and don't want players to cheat using coordinates.
However, quick info shows coordinates regardless of if you have Reduceddebuginfo enabled or not, which kinda defeats the purpose of the gamerule.
This should be changed, so that enabling Reduceddebuginfo also affects Quick info.

**Comment by sp614x** [comment]
Fixed, coming in next preview.
