### ISSUE TITLE
[BUG] CIT Does Not Respect Main Hand Customization when Matching Offhand

### ISSUE THREAD

**Issue by RhyGPU** [sp614x/optifine#7680]
## Description of Issue
Cit for off hand is broken when main hand is set to left hand in skin customization option.

When main hand = right hand:
Works perfectly
The cit shows up on off hand
![2024-06-08_20 07 07](https://github.com/sp614x/optifine/assets/112733980/56bc0032-bcdf-478e-84d8-74498c93373f)
![2024-06-08_20 07 17](https://github.com/sp614x/optifine/assets/112733980/a3fe3357-b617-47dc-a81e-ad2e09f060b5)
![2024-06-08_20 07 14](https://github.com/sp614x/optifine/assets/112733980/d88580ff-38df-4786-bd92-3a9fd92fe181)

When main hand = left hand:
The cit appears on main hand while the icon on the hot bar gui appears as a non cit texture
The cit doesn't appear on off hand while the hot bar gui appears as a cit texture.
![2024-06-08_20 07 04](https://github.com/sp614x/optifine/assets/112733980/dd2e656e-05d3-4ad5-9bad-e7656ff03d50)
![2024-06-08_20 06 35](https://github.com/sp614x/optifine/assets/112733980/38bd6ff8-9529-46dc-bb59-daca53f900bd)
![2024-06-08_20 06 46](https://github.com/sp614x/optifine/assets/112733980/53ee83a6-5062-4f11-a653-6b1350010297)
![2024-06-10_13 42 08](https://github.com/sp614x/optifine/assets/112733980/a92cca67-d771-4654-a2d1-d184cb72c19a)
![2024-06-10_13 42 20](https://github.com/sp614x/optifine/assets/112733980/29ca270d-8fdf-4794-9f7a-6750421ec935)

## Steps to Reproduce

1. make a properties file as following under the cit file:
type=item

items=diamond_sword

model=diamond_sword_scabbard

hand=off

2. Make a custom model where the sword is on the back of the character and name it diamond_sword_scabbard.
3. Load resource pack in-game.
4. Change the main hand to left hand in the skin customization option.

## OptiFine Version

OptiFine HD U I8 pre2, OptiFine HD U I9 pre1, OptiFine HD U I5, OptiFine HD U I7. All versions I tried using to see if it was across multiple versions.

## Installation Method

I have downloaded optifine as a standalone from the optifine download site.

## Log Files/Crash Reports

No crashes or logs for it.

## F3 Debug Screenshot
![2024-06-10_13 43 14](https://github.com/sp614x/optifine/assets/112733980/1eea4870-86d0-484b-9903-573586218214)
![2024-06-10_13 43 36](https://github.com/sp614x/optifine/assets/112733980/3fab89b0-3b72-47b5-9e34-4fd0a337401e)

## Prior Testing

Vanilla dose not support this feature as it is an CIT feature.

**Comment by sp614x** [comment]
Fixed, coming in next preview

**Comment by RhyGPU** [comment]
Thanks!!!!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
