### ISSUE TITLE
[Crash] Exit code 2

### ISSUE THREAD

**Issue by Riot-coder024** [sp614x/optifine#7683]
While I did remove over 99.9% of the log messages, it does state that I may have a driver issue, despite being able to run more intensive minecraft packs of both forge and fabric. It also doesn't make much sense because I am running just the base optifine mod and no others on a forge loader

Native libraries:

Mods:
  [✔] preview_OptiFine_1.20.6_HD_U_I9_pre1

Params:
  --username  --version 1.20.6 --gameDir C:/Users/-----/AppData/Roaming/PrismLauncher/instances/1.20.6(1)/.minecraft --assetsDir C:/Users/-----/AppData/Roaming/PrismLauncher/assets --assetIndex 16 --uuid  --accessToken  --userType  --versionType release --launchTarget forge_client --fml.forgeGroup net.minecraftforge --fml.forgeVersion 50.1.0 --fml.mcVersion 1.20.6

Window size: 854 x 480

Launcher: standard

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx4096m, -Duser.language=en]

Possible solutions:
A) Make sure Minecraft is set to prefer high performance graphics in the OS and/or driver control panel
B) Check for driver updates on the graphics brand's website
C) Try reinstalling your graphics drivers
D) If still not working after trying all of the above, ask for further help on the Forge forums or Discord

Exiting with ERROR
Process exited with code 2.
Clipboard copy at: 19 Jun 2024 01:30:47 -0600

**Comment by McSquizzleswag** [comment]
OptiFine for 1.20.6 doesn’t support Forge yet
