### ISSUE TITLE
Optifine coming up as a word document

### ISSUE THREAD

**Issue by jamesluvsminecraft** [sp614x/optifine#7685]
I tried downloading optifine for 1.19.2 but after i downloaded and looked at it in my files, it came up as a word document. When I opened the document it just came up as an unreadable page that just showed a black screen. How do I fix this??

**Comment by Regnander** [comment]
From where did you download this? The reason I'm asking is just to make sure you didn't get this from a spyware website.

**Comment by Ari-RERA-43** [comment]
> From where did you download this? The reason I'm asking is just to make sure you didn't get this from a spyware website.

@Regnander This is usually just cased by messed up file association (.jar files associated with something that isn't Java). They probably didn't download spyware.

**Comment by Ari-RERA-43** [comment]
> I tried downloading optifine for 1.19.2 but after i downloaded and looked at it in my files, it came up as a word document. When I opened the document it just came up as an unreadable page that just showed a black screen. How do I fix this??

@jamesluvsminecraft Can you try downloading and running [Jarfix](https://johann.loefflmann.net/downloads/jarfix.exe)?

**Comment by FluffyPuppyKasey** [comment]
> I tried downloading optifine for 1.19.2 but after i downloaded and looked at it in my files, it came up as a word document. When I opened the document it just came up as an unreadable page that just showed a black screen. How do I fix this??

Sounds like file associations are messed up or you don't have Java installed. However, something I've noticed is Optifine really doesn't do much for performance these days, so I genuinely recommend trying out Sodium. I usually get about a 4x performance increase with it

**Comment by jamesluvsminecraft** [comment]
i downloaded it from the official optifine website

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jamesluvsminecraft** [comment]
> > I tried downloading optifine for 1.19.2 but after i downloaded and looked at it in my files, it came up as a word document. When I opened the document it just came up as an unreadable page that just showed a black screen. How do I fix this??
> 
> @jamesluvsminecraft Can you try downloading and running [Jarfix](https://johann.loefflmann.net/downloads/jarfix.exe)? If that doesn't solve your issue, ask for help in the support channel of the [OptiFine Discord](https://optifine.net/discord).

**Comment by jamesluvsminecraft** [comment]
@Ari-RERA-43 omg yes it worked! i downloaded optifine and its now finally the real thing, also wanted to ask does it work for modded minecraft? because im playing minecraft with the help of the forge app for mods

**Comment by jamesluvsminecraft** [comment]
> > I tried downloading optifine for 1.19.2 but after i downloaded and looked at it in my files, it came up as a word document. When I opened the document it just came up as an unreadable page that just showed a black screen. How do I fix this??
> 
> @jamesluvsminecraft Can you try downloading and running [Jarfix](https://johann.loefflmann.net/downloads/jarfix.exe)? If that doesn't solve your issue, ask for help in the support channel of the [OptiFine Discord](https://optifine.net/discord).

@Ari-RERA-43 omg yes it worked! i downloaded optifine and its now finally the real thing, also wanted to ask does it work for modded minecraft? because im playing minecraft with the help of the forge app for mods

**Comment by Ari-RERA-43** [comment]
> > > I tried downloading optifine for 1.19.2 but after i downloaded and looked at it in my files, it came up as a word document. When I opened the document it just came up as an unreadable page that just showed a black screen. How do I fix this??
> 
> > 
> 
> > @jamesluvsminecraft Can you try downloading and running [Jarfix](https://johann.loefflmann.net/downloads/jarfix.exe)? If that doesn't solve your issue, ask for help in the support channel of the [OptiFine Discord](https://optifine.net/discord).
> 
> 
> 
> @Ari-RERA-43 omg yes it worked! i downloaded optifine and its now finally the real thing, also wanted to ask does it work for modded minecraft? because im playing minecraft with the help of the forge app for mods 

I assume by the Forge app, you mean a modpack in CurseForge. Forge and CurseForge are (confusingly) different things. 
If the modpack uses Forge, you can drop OptiFine into the modpack's mods folder and make sure you are using a compatible Forge version. If the modpack uses Fabric, you will need to also add OptiFabric to the mods folder alongside OptiFine. 
If you run into issues with using OptiFine with other mods, run the `!tm` command in the #bot-commands channel of the [OptiFine Discord server](https://optifine.net/discord).

**Comment by jamesluvsminecraft** [comment]
> > > > I tried downloading optifine for 1.19.2 but after i downloaded and looked at it in my files, it came up as a word document. When I opened the document it just came up as an unreadable page that just showed a black screen. How do I fix this??
> > 
> > 
> > > 
> > 
> > 
> > > @jamesluvsminecraft Can you try downloading and running [Jarfix](https://johann.loefflmann.net/downloads/jarfix.exe)? If that doesn't solve your issue, ask for help in the support channel of the [OptiFine Discord](https://optifine.net/discord).
> > 
> > 
> > @Ari-RERA-43 omg yes it worked! i downloaded optifine and its now finally the real thing, also wanted to ask does it work for modded minecraft? because im playing minecraft with the help of the forge app for mods
> 
> I assume by the Forge app, you mean a modpack in CurseForge. The Forge mod loader and CurseForge app are (confusingly) different things. If the modpack uses Forge mod loader, you can drop OptiFine into the modpack's mods folder and make sure you are using a compatible Forge version. If the modpack uses the Fabric mod loader, you will need to also add OptiFabric to the modpack's mods folder alongside OptiFine. If you run into issues with using OptiFine with other mods, run the `!tm` command in the #bot-commands channel of the [OptiFine Discord server](https://optifine.net/discord).

THANK YOU!! it worked, really appreciate your help :)

**Comment by Jiingy** [comment]
Closing this.
