### ISSUE TITLE
[Category] Short description

### ISSUE THREAD

**Issue by Tixctes** [sp614x/optifine#7697]
## Description of Issue

SEUS PTGI E11 AND E12 Produce the same visual errors and show no opengl error output, this is regardless of version.
I can demonstrate the image

## Steps to Reproduce

Use CachyOS. ZNVER4 Optimised Repository 
On 7900XT Ryzen 7 7800X3D
1. What do you do...
2. ...to find this bug?
(
![11111](https://github.com/user-attachments/assets/619fcdb5-3369-4109-8ac1-644ea6fa18a2)
https://github.com/user-attachments/assets/bb7a0c38-e088-4e68-9383-76ed70424768)

## F3 Debug Screenshot

If you've installed using Forge/Fabric:
- Does this happen without other mods installed?
   - Only OptiFine
- Does this happen in OptiFine standalone? Yes. But it's not exclusive to it.

## Additional Information
https://github.com/user-attachments/assets/473919d1-1d97-44ad-b5e6-57e1f4b4e80a)

Hoping this can be resolved as no one knows why, the resolution not being clear to what is the definitive problem

**Comment by IMS212** [comment]
(For reference, this bug can also be replicated on Iris; it is a driver bug.)

**Comment by Tixctes** [comment]
Yeah i've tried git and that worked. VEry strange isn't it?

**Comment by CodingWithAnxiety** [comment]
Fixed on arch and arch linux derivatives by updating mesa.

**Comment by IMS212** [comment]
This can now be closed; Mesa 24.2 has been released.

**Comment by Tixctes** [comment]
New mesa is quite good
