### ISSUE TITLE
[Copyright issues]OptiFine on "Minecraft China Edition(agented by Netease)"

### ISSUE THREAD

**Issue by HeartyYF** [sp614x/optifine#770]
Recently, on the "Minecraft China Edition"agented by Netease platform, we found OptiFine inside without any signs of copyright, uploaded by someone we don't know.
![zimjfd t7di7xjxo0 z7f8](https://user-images.githubusercontent.com/17660052/28239450-f64217dc-699e-11e7-95a6-b824a2f4c5d2.png)
![s6sp 3 kp 4 _mn9 4fb](https://user-images.githubusercontent.com/17660052/28239451-00e28f14-699f-11e7-96d1-9b045d69eadb.png)
I just wonder if it has obtained the copyright, or I'm just too nervous.

By the way, I also want to reprint this mod to mcbbs(because the original reprinter( @muink ) has been missing for a really long period)(the address is www.mcbbs.net/thread-606019-1-1.html)(certainly I marked out the author, the origin release address and the Homepage of OptiFine), may I?

**Comment by HeartyYF** [comment]
NOTE:It can be considered that Netease has used OptiFine for business.If they don't have copyright, it's high time to rip them off.

**Comment by mgdgfbhevdyeh** [comment]
u can't rip them off
because the have MOJANG support,MOJANG is Minecraft owner
so sad :(

**Comment by ShangJixin** [comment]
So,how to deal with netease?
Ask for Mojang?
(sorry to my English)

**Comment by HeartyYF** [comment]
I don't think Mojang can give any help, but in this aspect if Netease didn't obtain the copyright it must be in the wrong.

**Comment by mgdgfbhevdyeh** [comment]
Netease has not been allowed by LexManos, I think also have not allowed to pass sp614x.
I try to contact both sides of the Isseus, if there is an error I can delete.

**Comment by Mrkwtkr** [comment]
It's not a good idea to hold a part as the whole, especially when you want to use it as a chip to ask for your reprint permission. In fact, you can just open a single issue and ask for permission. By the way, as I known, Netease does have sp614x's permission. So it's going to be funny then.

**Comment by sp614x** [comment]
NetEase can use OptiFine in the chinese launcher, at least until it is in beta testing.

GreyWang from NetEase contacted me and he has permission to upload OptiFine in the chinese launcher while it is in beta testing.

**Comment by xfl03** [comment]
Does it means Netease could not use OptiFine in the release version?

**Comment by mgdgfbhevdyeh** [comment]
@xfl03 no NetEase could wse Optifine in the release

**Comment by TheozoveDas** [comment]
Hello, I'm having problems in my minecraft china edition, it shows these message:https://imgur.com/a/F6I9Xlm

**Comment by DataCrusade** [comment]
> Hello, I'm having problems in my minecraft china edition, it shows these message:https://imgur.com/a/F6I9Xlm

Do you think you could make a new issue for this? Also, translating what that says to english if you can would be very helpful

**Comment by TheozoveDas** [comment]
> > Hello, I'm having problems in my minecraft china edition, it shows these message:https://imgur.com/a/F6I9Xlm
> 
> Do you think you could make a new issue for this? Also, translating what that says to english if you can would be very helpful

sorry, the first one probably says something about the official websites and the second is about internet and DNS (This is what I know.).

**Comment by Mrkwtkr** [comment]
> Hello, I'm having problems in my minecraft china edition, it shows these message:https://imgur.com/a/F6I9Xlm

It seems not to be Optifine's issue, and this is not a repository for minecraft china edition.

**Comment by sp614x** [comment]
@TheozoveDas this is not related to OptiFine.
