### ISSUE TITLE
[custom color] Short description

### ISSUE THREAD

**Issue by Steve8MC** [sp614x/optifine#7707]
## Steps to Reproduce

1. What do you do...
2. ...to find this bug?

**Comment by SilentWhisperer** [comment]
that's.... extremely useful

**Comment by blryface** [comment]
Why is it all headers... And what the hell is the issue

**Comment by kyoshuske** [comment]
thank you so much for providing so much useful information about this issue

**Comment by Ari-RERA-43** [comment]
@Steve8MC Please either edit your issue title and description to describe the problem you're encountering, or close this issue.
