### ISSUE TITLE
[1.21pre5 Crash] Enchantment-based CIT (like enchanted books) causes a crash

### ISSUE THREAD

**Issue by SeaOfPixels** [sp614x/optifine#7709]
## Description of Issue
Attempting to enable my resource pack New Default+ (https://minecraft.curseforge.com/projects/newdefaultplus) in OptiFine 1.21_HD_U_J1_pre5 results in a crash, even on the main menu. It is seemingly caused by CIT that uses the `enchantments=` parameter, as removing any CIT that uses this prevents the crash. Crash report: 
[Crash Report.txt](https://github.com/user-attachments/files/16737790/Crash.Report.txt)

## Steps to Reproduce

1. Open Minecraft
2. Enable resource pack in the resource packs menu that contains enchantment-based CIT

## OptiFine Version

OptiFine 1.21_HD_U_J1_pre1, OptiFine 1.21_HD_U_J1_pre2, OptiFine 1.21_HD_U_J1_pre3, OptiFine 1.21_HD_U_J1_pre4, OptiFine 1.21_HD_U_J1_pre5

**Comment by REV3RSE-408** [comment]
Got the same issue with my resource pack. Maybe there is something wrong with emissive textures on blocks. As soon as I removed the _e texture, the game did not crash anymore. I tested around ten different blocks, and it happened on every single one of them. As soon as there is an emissive texture involved, the game just crashes.

**Comment by SeaOfPixels** [comment]
Mine crashed before I could even get into a world though, on the main menu, where no emissives were loaded.

**Comment by AliolyMader** [comment]
Same Issue, still not work in optifine 1.21 pre2

**Comment by richardatsley** [comment]
Problem persists in Pre2, praying this gets fixed asap

**Comment by Romanlab1** [comment]
Same issue here, tested with different texture packs, crashes everytime, I tried with New Default + and Great Shrimpsby's texture pack

**Comment by SeaOfPixels** [comment]
Fixed in pre6, new bug created: https://github.com/sp614x/optifine/issues/7734
