### ISSUE TITLE
Optifine unnecessarily replaces GuiVideoSettings implementation

### ISSUE THREAD

**Issue by Barteks2x** [sp614x/optifine#771]
In vanilla mods are able to add new video settings options by adding it directly to GuiVideoSettings (either via reflection or AccessTransformer, I know generally mods shouldn't do that, but I feel like in cases like optifine itself or cubic chunks this is the most reasonable option). It also works just fine, because there is a scrollbar.

Optifine seems to unnecessarily replace the implementation and graphics, which at least for me requires special [optifine specific code, and a bit of layout hacks to make it all actually fit on the screen](https://github.com/OpenCubicChunks/CubicChunks/blob/fd6da38c416a40eed475cd1f48a8c047f9e73558/src/main/java/cubicchunks/client/ClientEventHandler.java#L72-L103). Is there any chance Optifine could just add new buttons to the vanilla one instead of replacing it entirely?

**Comment by sp614x** [comment]
Forge has support for mod-specific options which does not conflict with OptiFine:

![image](https://user-images.githubusercontent.com/16635441/28269465-721c152e-6b02-11e7-8d0b-0571e5c15d7a.png)

**Comment by sp614x** [comment]
OptiFine uses fixed size option screens and there are no plans to use the vanilla scrollbar.

**Comment by Barteks2x** [comment]
Yes, forge does allow it. I know. But it's more cumbersome to find these optiosn if there are a lot of mods. If you recommend me to use this, why doesn't optifine also use it? It could. And it wouldn't cause any conflicts.

**Comment by sp614x** [comment]
OptiFine is by default a standalone mod, it does not require Forge so it can't use the Forge features.
The OptiFine's Video Settings screen has been with a fixed size for a very long time and currntly there are no plans to change it.

**Comment by Barteks2x** [comment]
There is no way I'm moving that slider to forge config screen. Only like 5% of users would find it. So I guess I will need to keep hacking into optifine's gui screen for now.

**Comment by sp614x** [comment]
OptiFine can't use Forge features when the Forge classes are not available.

**Comment by Barteks2x** [comment]
But it can when they are available. And it is possible to detect it and use forge features only whe  forge is insalled.
