### ISSUE TITLE
OptiFine 1.21_HD_U_J1_pre1 Biome dependent textures not working

### ISSUE THREAD

**Issue by Emfire12345** [sp614x/optifine#7710]
Like the titel says, textures with biome dependencies do not work, colormaps do not work either (#7676), just wanted to mention it since these issues might be related.

Tested with OptiFine 1.21_HD_U_J1_pre1 (not working):
![2024-08-24_22 28 17](https://github.com/user-attachments/assets/0d458aac-1eb9-4a10-b163-5779f4cbaf06)

Tested with OptiFine 1.20.4_HD_U_I8_pre4:
![2024-08-24_22 30 36](https://github.com/user-attachments/assets/affa7a8e-3a27-4997-bcd8-8261131de30b)

**Comment by SeaOfPixels** [comment]
Can confirm in 1.20.1pre9, screenshots for comparison:
1.20.4 (correct):
![2024-09-04_17 26 12](https://github.com/user-attachments/assets/ceb72784-d6c0-4dd7-b712-2a4956bb404f)

1.21.1 (incorrect):
![2024-09-04_17 30 59](https://github.com/user-attachments/assets/c7cbdaa5-4e59-4a1c-a091-7abbeab94c17)

**Comment by Emfire12345** [comment]
Fixed in pre12
