### ISSUE TITLE
Red dye and blue dye

### ISSUE THREAD

**Issue by JoelSonic199** [sp614x/optifine#7712]
So when I was dying 2 signs and when I pulled out red dye it turned blue and when I pulled out blue dye it TURNED RED! AND IT WAS ON 1.21 PRE1 and that was the newest verison

**Comment by andreastande** [comment]
Yup, experiencing the same with many other dyes, including yellow and cyan which are switched. 

Interestingly, this extends not only to dies but to all text-color! When I am holding my diamond sword, the text above the HUD is yellow instead of cyan! Weird...

**Comment by KaiAF** [comment]
Issue is with all text colours, I'm sure it will be fixed soon

**Comment by ZenithRogue** [comment]
Fixed in 1.21_HD_U_J1_pre2
