### ISSUE TITLE
[Shader] A small part of vertex does not have mc_Entity.x in 1.21

### ISSUE THREAD

**Issue by GeForceLegend** [sp614x/optifine#7713]
## Description of Issue

`mc_Entity.x` of a small part of vertex are 0 instead of expected value, causing some issue on hardcoded blocks, especially water

## Steps to Reproduce

1. Using SEUS PTGI HRR 2.1
2. Standing near water
3. See strange line caused by this bug in shadow program. It's not very visible in gbuffers.

## OptiFine Version

1.21 J1 Pre1

## Installation Method

Standalone

## F3 Debug Screenshot

![2024-08-25_14 23 45](https://github.com/user-attachments/assets/97ecd450-6b6f-4bf1-a8cc-c1682c08f291)

## Additional Information

Renderdoc capture reference, showing a certain vertex losing correct `mc_Entity.x`

![QQ20240825-141417](https://github.com/user-attachments/assets/60f491a2-64c9-49e3-9ef1-95a2a59334e6)

**Comment by GeForceLegend** [comment]
Looks like `mc_Entity` is fixed in 1.21 J1 Pre4. However, #7714 is not fixed, which marks attributes is still not get ALL fixed

**Comment by sp614x** [comment]
Fixed in latest previews.
