### ISSUE TITLE
Colors Bug

### ISSUE THREAD

**Issue by Lukasz1342** [sp614x/optifine#7716]
In newest optifine version (1.21) some colors are swapped 
splashes , commands and some items are cyan and blue instead of normal colors
![image](https://github.com/user-attachments/assets/3af407b4-f4dd-4b77-92b8-dcedd93a0141)
bad and good potion effects are swapped too (good effects has a red color , and bad has a blue color)
![222](https://github.com/user-attachments/assets/25b9e012-a375-4162-8ebb-7d0e2d565a49)
and xp number has a different color 
![1](https://github.com/user-attachments/assets/105bc969-fc29-4402-b084-99d554c025da)

**Comment by andreastande** [comment]
Fixed in the new version released (pre2), check https://optifine.net/downloads
