### ISSUE TITLE
Crash upon logging in or laying blocks crash report -1

### ISSUE THREAD

**Issue by BA4TA** [sp614x/optifine#7717]
## Description of Issue

Can't log in to game most of the time and if i can it will crash when laying a block. Crash report attached:
[crash-2024-08-25_15.08.04-client.txt](https://github.com/user-attachments/files/16741628/crash-2024-08-25_15.08.04-client.txt)

The game crashed whilst tesselating block model
Error: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 5
I am sorry if there is another like this.. I looked and couldn't find one...but this is my first time in this forum so go easy eh?

## Steps to Reproduce

1. What do you do... Log in using Optifine 9 crash white screen upon initializing terrain. then if i do get in ...it will randomly crash when i go to set any random block...it was a couple hours this time before it crashed.. 
2. ...to find this bug?

## OptiFine Version

 preview_OptiFine_1.21_HD_U_J1_pre1.jar

## Installation Method

downloaded zip... moved to desk top,,,,Right click on jar and opened with java to install

## Log Files/Crash Reports
[crash-2024-08-25_15.08.04-client.txt](https://github.com/user-attachments/files/16741647/crash-2024-08-25_15.08.04-client.txt)

## F3 Debug Screenshot
![2024-08-25 15_17_23-Greenshot](https://github.com/user-attachments/assets/cf0fcc66-7807-4b6d-8ede-b88bd6588eaf)

CAn't get back in to get screenshot

**Comment by BA4TA** [comment]
![2024-08-25 16_45_23-Greenshot](https://github.com/user-attachments/assets/d509e900-1067-4856-a733-5cb439e3712f)
This new version is working so far! Could get right in!! I LOOOOOOOVVE OPTIFINE!! often imitated but never duplicated!!

**Comment by BA4TA** [comment]
and it just crashed.. lolz..

**Comment by BA4TA** [comment]
I could get right back in though!

**Comment by KaiAF** [comment]
If you want the crash to stop, you can try to disable the resource pack.

**Comment by sp614x** [comment]
Fixed in 1.21.1 previews.
