### ISSUE TITLE
[Crash] Crash with Vanilla Tweaks Fully Aged Crop/Amethyst Cluster Markers

### ISSUE THREAD

**Issue by AJWRDiamonds** [sp614x/optifine#7718]
## Description of Issue

Honestly I have no clue what the real issue is. I was going to the spawn of the server i was playing on and all of a sudden my game crashed. I didnt even get to load into the spawn. It just crashed outright. When I looked in the crash logs it said tessalating block model which i have no idea what that means, but I looked further into the logs and it said wheat age 7 as the cause. i still dont fully understand the issue.

## Steps to Reproduce

1. What do you do...
2. ...to find this bug?
3. I dont even know how to reproduce it.

## OptiFine Version

 OptiFine 1.21_HD_U_J1_pre1

## Installation Method

 I used the standalone installer

## Log Files/Crash Reports

 https://pastebin.com/iuurU1MT

## Additional Information

 I found a temp solution by disabling one of my texture packs called vanilla tweaks, but i have no idea which one of the addons in it would be related to the crash.

**Comment by AJWRDiamonds** [comment]
I found what the issue was and was able to fix it

**Comment by ZenithRogue** [comment]
@AJWRDiamonds can you add details of what exactly was causing the crash, and what the solution was?

**Comment by AJWRDiamonds** [comment]
it was my vanilla tweaks texture pack, and the specific part was showing fully grown crops and by proxy fully grown amethyst clusters by showing a marker. I disabled those 2 specific parts and it fixed the crashing.

**Comment by ZenithRogue** [comment]
Please share the parts of the pack that were causing the crash, as this is not expected behavior, and does not affect older versions of OptiFine

**Comment by AJWRDiamonds** [comment]
![image_2024-08-25_225856153](https://github.com/user-attachments/assets/42468afd-3a40-4938-9ded-3891b629471e)
in the utility tab of vanilla tweaks these were the 2 causing the crash

**Comment by ZenithRogue** [comment]
Uploading current versions for archive/testing
[VanillaTweaks_r137945_MC1.21.x.zip](https://github.com/user-attachments/files/16743472/VanillaTweaks_r137945_MC1.21.x.zip)

**Comment by AJWRDiamonds** [comment]
Fixed in OptiFine 1.21_HD_U_J1_pre5
