### ISSUE TITLE
[1.10.2] [E3] Crashes a few seconds after loading world.

### ISSUE THREAD

**Issue by ireece1** [sp614x/optifine#772]
After i recently updated the mod pack i use, Optifine stopped working correctly. The world would load and play normally for a few seconds and then immediately crash with a "Rendering Chunk" error.

At first i thought it was a mod conflict but the stack trace is all vanilla/java stuff.

https://pastebin.com/hqMbCSmr

**Comment by sp614x** [comment]
Some of the mods is conflicting with Antialiasing or Anisotropis Filtering.
Either remove the problematic mod or disable Antialiasing and Anisotropis Filtering.
