### ISSUE TITLE
Parrot not dancing AND FLAPPING!

### ISSUE THREAD

**Issue by JoelSonic199** [sp614x/optifine#7720]
So I put in the music disc cat and noticed my parrot not dancing so I was like huh? Your not dancing? I thought. So I took out the disc and Yup it was a bug and they werent flapping. and the verison it was on was.

1.21 pre2

**Comment by JoelSonic199** [comment]
THE PARROT ISNT FLAPPING

**Comment by KaiAF** [comment]
Tested, they are dancing and flapping. Not able to reproduce it.
![image](https://github.com/user-attachments/assets/91287dcd-2fff-4cdb-b5cd-7af24325a848)
