### ISSUE TITLE
[Category] Moving grass

### ISSUE THREAD

**Issue by PawTattoo** [sp614x/optifine#7723]
## Steps to Reproduce

Just spawned and saw moving grass/ Like leaves

## OptiFine Version

1.21 J1 pre2

## Installation Method

I opened jar file and installed

![2024-08-28_00 10 54](https://github.com/user-attachments/assets/13a08b05-db34-4b89-b407-1628b0d4c533)
![2024-08-28_00 10 55](https://github.com/user-attachments/assets/dd14db25-af93-461c-83aa-12086d0c4294)
![2024-08-28_00 17 16](https://github.com/user-attachments/assets/ab3cfc32-726b-45a8-a1fb-af101ee8ba66)

**Comment by GeForceLegend** [comment]
Might related to #7713

**Comment by sp614x** [comment]
Should be fixed with #7713
