### ISSUE TITLE
[Crash] Minecraft crashing when OptiFine HD U J1 pre2 its installed

### ISSUE THREAD

**Issue by FabinDoPineu** [sp614x/optifine#7724]
## Description of Issue

When i start minecraft forge with the OptiFine HD U J1 pre2 (last version), the minecarft crashes and give the error code 1

## Steps to Reproduce

1. Drop the optifine jar in mods folder
2. open the minecraft

## OptiFine Version

OptiFine HD U J1 pre2

## Fabric/Forge Version

1.21.1 - 52.0.9

**Comment by KaiAF** [comment]
The recent previews do not support forge yet.
