### ISSUE TITLE
[1.21.1 CIT] CIT armor models are not working

### ISSUE THREAD

**Issue by SeaOfPixels** [sp614x/optifine#7727]
## Description of Issue
CIT armor models are not functioning correctly, however other CIT like items are working.

## Steps to Reproduce
1. Open Minecraft
2. Enable resource pack in the resource packs menu that contains CIT armor models
3. Attempt to rename the armor in-game

## OptiFine Version
OptiFine 1.21_HD_U_J1_pre5, OptiFine 1.21_HD_U_J1_pre6, OptiFine 1.21.1_HD_U_J1_pre9, OptiFine 1.21.1_HD_U_J1_pre12

## Screenshot
![2024-09-01_15 49 45](https://github.com/user-attachments/assets/88bfaaa4-d754-4eab-ac41-ac28c7646ba7)

**Comment by sp614x** [comment]
Fixed, coming in next preview.

**Comment by DarkChromaMC** [comment]
It appears to still be broken in the latest `1.21.1_HD_U_J1_pre13`
