### ISSUE TITLE
Crashing before I even load into the game.

### ISSUE THREAD

**Issue by ItsRiseXcel** [sp614x/optifine#7729]
## Steps to Reproduce

1. I load into the game with 1.21 installed and a few mods, and it gets the crash code: 1

## OptiFine Version

 newest preview version. pre-e1

## Installation Method

 I dropped it directly into the mods folder

## Fabric/Forge Version

 1.21-forge-51.0.33

## Other Installed Mods

 https://pastebin.com/Zd1qsjDv

## F3 Debug Screenshot

 I can't even get into the game

**Comment by Emfire12345** [comment]
Optifine is currently not compatible with forge

**Comment by ItsRiseXcel** [comment]
oh thats great to know, thank you
