### ISSUE TITLE
About Netease

### ISSUE THREAD

**Issue by mgdgfbhevdyeh** [sp614x/optifine#773]
First you can see here:https://www.zhihu.com/question/62429177 (sorry it's Chinese)
I heard Netease reproduced Optifine, but did not get your approval
And boldly reproduced a some Shader

Netease did not respond at present
But the players over there argue endlessly
All i have to ask Netease to reprint whether Optifine got your consent?
Edit:sorry for my English

**Comment by HeartyYF** [comment]
Same issue:https://github.com/sp614x/optifine/issues/770
I have pulled the issue, but by now I don't get any reply from sp614x.

**Comment by mgdgfbhevdyeh** [comment]
OK i know
