### ISSUE TITLE
[Category] Game wont launch with optifine 1.21 pre5

### ISSUE THREAD

**Issue by Unknown-Rac-N** [sp614x/optifine#7730]
## Description of Issue

i've tried all pre versions of optifine as they have been released but all say the same error code when launching, the text it gives me in the launcher is:

_The game crashed whilst initializing game
Error: java.lang.ExceptionInInitializerError_

with the exit code -1

i'm not using any mods just base minecraft but the only support i can find online is for mods which doesn't apply to me.

## Steps to Reproduce
1. Open minecraft launcher with the optifine version and launch 
2. Get the crash message with the exit code and text 

## OptiFine Version

all Versions of 1.21 Pre. 

## Log Files/Crash Reports

[crash-2024-09-02.txt](https://github.com/user-attachments/files/16836154/crash-2024-09-02.txt)

## Additional Information

So no mods and just a base game yet it will never launch and cant find anyone else who has had this problem only those who have it with mods.

**Comment by Zahhpapii** [comment]
Hey not sure if you solved it on your own yet but i figured out that for the 1.21 versions certain resource packs make the game crash with optifine

**Comment by sp614x** [comment]
Should be fixed in latest 1.21.1 preview.
