### ISSUE TITLE
optifine 1.21 pre J1 pre5

### ISSUE THREAD

**Issue by richiemilos** [sp614x/optifine#7732]
In the latest release of optifine 1.21 J1 pre5 the swamp water bug was not fixed, all the water in the game is the same color
![2024-09-02_13 57 34](https://github.com/user-attachments/assets/8345e102-40fd-4b64-9123-54eb06eba896)
![2024-09-02_13 57 55](https://github.com/user-attachments/assets/97c995b6-b07c-45ed-8181-47dba1913fbb)
![2024-09-02_13 59 30](https://github.com/user-attachments/assets/43b7753a-082e-439a-b102-f879e1d7e5d6)
![2024-09-02_14 06 32](https://github.com/user-attachments/assets/ff6bffeb-c3be-4626-812f-f3e0177b7535)

**Comment by JoelSonic199** [comment]
You probably had a setting changed in your game that had the option to change the swamp water color.

**Comment by JoelSonic199** [comment]
So u should double check

**Comment by richiemilos** [comment]
I don't know, but I only get that error in versions of Optifine 1.21.
I already tried it in a previous version like 1.20.6 and everything is fine. If anyone knows the solution, please help me.
![2024-09-02_23 30 35](https://github.com/user-attachments/assets/9208efe2-28cc-4c10-9002-70fb9ea3c9fd)

**Comment by sp614x** [comment]
Fixed in latest preview.
