### ISSUE TITLE
[Crash pre7] Crashes in J pre7

### ISSUE THREAD

**Issue by SeaOfPixels** [sp614x/optifine#7737]
## Description of Issue
I'm aware that this version was taken down due to crashes, but I thought it'd be helpful to SP to provide a crashlog in this report for debugging:

## OptiFine Version
OptiFine 1.21_HD_U_J1_pre7

## Crash Log
[crashlog.txt](https://github.com/user-attachments/files/16856250/crashlog.txt)

**Comment by SeaOfPixels** [comment]
Seemingly fixed in pre8.

**Comment by sp614x** [comment]
Yep, fixed.
