### ISSUE TITLE
[Shader] cutout and cutout_mipped are splitted in gbuffer rendering in 1.21

### ISSUE THREAD

**Issue by GeForceLegend** [sp614x/optifine#7738]
## Description of Issue

Don't know if this is work as intended, or it's an issue in Optifine 1.21. In almost all versions before 1.21, cutout and cutout_mipped blocks are rendered together with mipmap enabled. But in Optifine 1.21, cutout blocks are rendered after all cutout_mipped blocks, with their mipmap disabled.

This causes AF implemented in shaders a bit more worse, as it cannot use lod greater than 0 anymore. Other possible effects are not tested.

## Steps to Reproduce

Loading any shader, and using rederdoc or similar software to capture a frame, and see how terrain is rendered.

Before Optifine 1.21, cutout blocks (like short grass and glass block) and cutout_mipped block (like grass block) are rendered together
![20240904-104018](https://github.com/user-attachments/assets/e1b9bc00-2a68-4b3d-ab85-95fb89a81665)

In Optifine 1.21, cutout blocks are rendered after cutout_mipped blocks. Grass blocks (cutout_mipped) are already get all rendered, while short grass and glass block is not fully rendered.
![20240904-104034](https://github.com/user-attachments/assets/1aa15363-51ec-4c53-9bed-4098160a0265)

## OptiFine Version

1.21 J1 Pre8

## Installation Method

Standalone

## Prior Testing

This matches vanilla behavior, but not match behavior in previous Optifine versions, so I created this issue.

**Comment by sp614x** [comment]
Fixed, coming in next preview
