### ISSUE TITLE
[1.21.1 pre9 Colormaps] Colormaps are still broken

### ISSUE THREAD

**Issue by SeaOfPixels** [sp614x/optifine#7741]
## Description of Issue
1.21.1 pre9 claims to have fixed biome colormaps, however all that's happened now is that all biomes seemingly use ID 0 for all colormaps.

For debugging purposes, the pack in the screenshots is my resource pack New Default+: https://legacy.curseforge.com/minecraft/texture-packs/newdefaultplus/files/all?filter-status=1&filter-game-version=2020709689:11779

## Steps to Reproduce
1. Open Minecraft
2. Enable resource pack in the resource packs menu that contains grid colormaps
3. View the biomes in-game

## OptiFine Version
OptiFine 1.21.1_HD_U_J1_pre9

## Screenshot version comparison
1.20.4 (correct):
![2024-09-04_17 17 18](https://github.com/user-attachments/assets/fad7446a-86fc-413f-93e4-cb14999c35ed)

1.21.1 pre9 (incorrect):
![2024-09-04_17 15 51](https://github.com/user-attachments/assets/31142049-705e-4e2a-b11b-258583edf70d)

**Comment by CloverCorp** [comment]
Can confirm this is still broken as of 1.21.1_HD_U_J1_pre9.

**Comment by Emfire12345** [comment]
Still broken for me as well, odly, some work some dont, my sky and fog colormaps seam to work, while my water colormap doesnt work at all and the grass colormap just works in some biomes...

**Comment by Baby-FarkMcGeezax** [comment]
For me, fog/sky appears to work but water is stuck on one colour (seemingly biome ID 1 on the grid colourmap from what I can see?), and grass doesn't work in any way at all

**Comment by SeaOfPixels** [comment]
Fixed in pre12
