### ISSUE TITLE
Game crashes on startup when using optifine

### ISSUE THREAD

**Issue by nikoflora** [sp614x/optifine#7745]
## Description of Issue

I am trying to use optifine 1.21 U J1 pre9 and it crashes on startup, i am using it alongside forge
## Steps to Reproduce

Extract the mod using the installer and drop the result from that into the mods folder, while using forge

## OptiFine Version

optifine 1.21 U J1 pre9 

## Installation Method

I extracted OptiFine using their installer

## Fabric/Forge Version

Forge 5.1.0.33

## Log Files/Crash Reports

https://mclo.gs/PtDjVmL

## Prior Testing
Only happens when optifine is installed with forge as a mod, if i use standalone it runs fine

**Comment by cutiegin** [comment]
![Screenshot_20240907_031944_Firefox](https://github.com/user-attachments/assets/78471cf2-057b-4d9c-91f1-ca5458e98cf9)
are you see "forge n/a" that means optifine isn't compatible with forge for now

**Comment by cutiegin** [comment]
> and use it



> So how do we install it?

just use standalone, you mentioned that you already used.

**Comment by sp614x** [comment]
The latest 1.21.1 previews are compatible with Forge.

**Comment by Suundumused** [comment]
Still crashing...
