### ISSUE TITLE
[1.21.1 pre9 CIT] CIT components that use an array/list (like suspicious stew) do not function

### ISSUE THREAD

**Issue by SeaOfPixels** [sp614x/optifine#7746]
## Description of Issue
Attempting to give CIT components to components that use an array/list (like suspicious stew) does not display the CIT in-game.

## Steps to Reproduce
1. Open Minecraft
2. Enable resource pack in the resource packs menu that contains CIT suspicious stew
3. View the items in-game

## OptiFine Version
OptiFine 1.21.1_HD_U_J1_pre9

## Properties file
The `.*` should be accounting for the array, but it doesn't work:
```
type=item
items=suspicious_stew
components.suspicious_stew_effects.*.id=minecraft:blindness
```

Other component line variants attempted that don't work:
`components.suspicious_stew_effects.id.*=minecraft:blindness`
`components.suspicious_stew_effects=minecraft:blindness`
`components.suspicious_stew_effects.id=minecraft:blindness`

## Screenshots
What it's supposed to look like when applying in-game:
![2024-09-07_16 54 22](https://github.com/user-attachments/assets/3e1ebefb-5c0a-4022-b577-ea1f9a6b92a2)

What it looks like due to not applying in-game:
![2024-09-07_16 55 54](https://github.com/user-attachments/assets/080b1201-ec7f-4b4a-bd58-1776b2d7be9d)

**Comment by SeaOfPixels** [comment]
Closing, the line `components.suspicious_stew_effects:[{id:"minecraft:wither"}]` works for array/list components.

**Comment by ewanhowell5195** [comment]
this is still a bug

**Comment by sp614x** [comment]
Currently the wildcard `*` only works for the last component.
Another workaround is:
`components.suspicious_stew_effects.0.id=minecraft:blindness`

**Comment by sp614x** [comment]
Fixed wildcard `*` to work in all components, coming in next preview.
