### ISSUE TITLE
[CIT] Component Namespace Parsing Issue When Using Tilde Shortcut

### ISSUE THREAD

**Issue by ZenithRogue** [sp614x/optifine#7750]
## Description of Issue
When using `~` as a shortcut for `minecraft:` in CIT component checks, `components.~custom_name` appears it may be parsed as `components.minecraft:minecraft:custom_name`

## Steps to Reproduce
![image](https://github.com/user-attachments/assets/c290bb15-8661-428c-9846-9e559acf7e0d)

**Comment by sp614x** [comment]
Fixed, coming in next preview
