### ISSUE TITLE
[Visual bug] Some blocks/item sides not rendering

### ISSUE THREAD

**Issue by Demirath** [sp614x/optifine#7756]
## Description of Issue

Most/all flat items do not render the top face (the one seen in inventories, or facing towards the player's center line when held in hand).
Examples:
![image](https://github.com/user-attachments/assets/851d38ee-0834-469e-a91d-6047b76f6cbe)
![image](https://github.com/user-attachments/assets/06ff6d8e-51d0-4ffa-871e-f1888b016f48)

## Steps to Reproduce

1. Install Optifine 1.21.1 pre versions
2. Open singleplayer or multiplayer world

## OptiFine Version

OptiFine HD U J1 pre11
OptiFine HD U J1 pre12
OptiFine HD U J1 pre13
OptiFine HD U J1 pre14

## Installation Method

Standalone

## F3 Debug Screenshot

![image](https://github.com/user-attachments/assets/955177ad-6a61-422a-85bc-1243dd130def)

## Prior Testing

- Does this happen in Vanilla without OptiFine? No.
- Also does not happen in 1.21 with OptiFine HD U J1 pre9.

## Additional Information

I also noticed a single, transparent, solid block in the corner of my build while taking screenshots (should be a tuff variant):
![image](https://github.com/user-attachments/assets/69d41a8a-a1af-4af7-95e0-1c41c25b43f9)

**Comment by mascio99** [comment]
![photo_2024-09-20_12-55-24](https://github.com/user-attachments/assets/0e7b0892-5948-4de0-99a0-5ed271963b6f)
![photo_2024-09-20_12-55-02](https://github.com/user-attachments/assets/e548d798-abdb-4cb3-970a-2bfc8ac5f29c)
I have the same problems

**Comment by sp614x** [comment]
Fixed, coming in next preview.
