### ISSUE TITLE
Optifine D8D7D6 not letting me switch resource packs.

### ISSUE THREAD

**Issue by Zweiinger** [sp614x/optifine#776]
Minecraft goes on a forever not responding whenever I try switch to any texturepack. It worked before but today it doesn't. I don't know why,

**Comment by sp614x** [comment]
Which resource pack?
Running with Forge or standalone?
Other mods installed?

**Comment by Zweiinger** [comment]
Forge, all of the texture packs, I removed all and slowly added them to find out optifine is the cause.

**Comment by sp614x** [comment]
Can you reproduce the problem with ONLY Forge and OptiFine?

**Comment by Zweiinger** [comment]
Yes, thats what I said.

**Comment by Zweiinger** [comment]
bump

**Comment by Zweiinger** [comment]
Any help?

**Comment by Zweiinger** [comment]
No help?

**Comment by sp614x** [comment]
Can you post the game output (error log)?
