### ISSUE TITLE
[BUG] Black sky (sugar cane, sea grass, wheat) when the menu background blur is enabled and Vignette is set to Fast.

### ISSUE THREAD

**Issue by iamsyne** [sp614x/optifine#7760]
## Steps to Reproduce

1. join hypixel skyblock/singleplayer
2. press ESC key
3. see black sky, sugar cane, sea grass, grass & wheat
![image](https://github.com/user-attachments/assets/d4801463-5112-45bc-802a-68a03e11f342)
![image](https://github.com/user-attachments/assets/e85e6624-2b38-4329-a4e5-7286cc6f7f4b)

## OptiFine Version
Release candidate OptiFine 1.21.1_HD_U_J1_pre16

## Installation Method

standalone installer

## F3 Debug Screenshot
![image](https://github.com/user-attachments/assets/9664d9a9-564d-4ccf-94fe-a697381824af)

## Prior Testing

- Does this happen in Vanilla without OptiFine?
no

## Additional Information
![image](https://github.com/user-attachments/assets/4bb0a269-3a1a-4cf3-92c2-fef120f1bb09)

![image](https://github.com/user-attachments/assets/7c82e5f8-3254-4c76-9921-3050a76161af)

**Comment by sp614x** [comment]
Any resource pack loaded?

**Comment by iamsyne** [comment]
no

**Comment by sp614x** [comment]
The black sky when menu blur is enabled doesn't seem to be connected to multiplayer.
More like a problem with the shader used to blur the background.
Can you post the MC error log (.minecraft/log/latest.log)?

**Comment by iamsyne** [comment]
[latest.log](https://github.com/user-attachments/files/17105249/latest.log)

**Comment by sp614x** [comment]
Can you post the video showing the flashing sky and the dynamic darkness?

**Comment by sp614x** [comment]
Can you try resetting the video settings (Options -> Video Settings -> Other -> Reset)

**Comment by iamsyne** [comment]
> Can you try resetting the video settings (Options -> Video Settings -> Other -> Reset)

resetting video settings helped with black sky, but dynamic darkness still happen

**Comment by sp614x** [comment]
Now the question is what combination of video settings caused the menu blur not to work properly?
In the single-player screenshot there is no fog and clouds, the horizon color is also not default.

**Comment by sp614x** [comment]
Probably Details->Vignette=Fast, it breaks the menu blur for me.

**Comment by iamsyne** [comment]
![image](https://github.com/user-attachments/assets/af03b1c7-eb12-4d04-872d-969f7725bc57)

**Comment by iamsyne** [comment]
yes it is Vignette

**Comment by sp614x** [comment]
Reproduced, should be easy to fix.
Can you make a separate issue for the dynamic darkness as it is probably caused by something very different (multiplayer chunks with wrong lighting)?

**Comment by sp614x** [comment]
The cause was a patch for Forge compatibility, Forge has the same problem when graphics is set to Fast.
Fixed, coming in next preview.
