### ISSUE TITLE
[Bug] Optifine not compatible with cobblemon

### ISSUE THREAD

**Issue by Gag2nd** [sp614x/optifine#7766]
## Description of Issue

Optifine is not compatible with the mod "Cobblemon" (https://www.curseforge.com/minecraft/mc-mods/cobblemon)
I did the "Thanos Method" so I'm 100% sure that this mod is the one causing the issue

## Installation Method

I dropped all the jar files in my mods folder

## Fabric/Optifine/Mods/Minecraft version

Minecraft 1.20.1
Fabric 0.16.5
Fabric API 0.92.2
Optifabric 1.14.3
OptiFine HD U I6
Cobblemon 1.5.2

## Log Files/Crash Reports

I got this message :

> The game crashed whilst mouseclicked event handler
> Error: java.lang.NullPointerException: mouseClicked event handler

**Comment by Gag2nd** [comment]
> can you send the full crash report

Sure sorry 

https://pastebin.com/72PAG5j7

**Comment by sp614x** [comment]
Null pointer exception in the Cobblemon classes, can't be fixed by OF.
```
java.lang.NullPointerException: mouseClicked event handler
  at com.cobblemon.mod.common.client.render.models.blockbench.repository.BerryModelRepository.patchModels(BerryModelRepository.java:60)
  at com.cobblemon.mod.common.client.CobblemonClient$initialize$3.invoke(CobblemonClient.java:114)
  at com.cobblemon.mod.common.client.CobblemonClient$initialize$3.invoke(CobblemonClient.java:113)
```
