### ISSUE TITLE
All the custom models for things like doors, items don't load

### ISSUE THREAD

**Issue by Wabbabrick** [sp614x/optifine#7773]
## Description of Issue

All the custom models for things like doors, items don't load. 
I am using Brixel resource pack 3.2 and BSL 8.3 shader.
It works fine in all prevous releases of optifine like OptiFine HD U I7 so it makes me beleve there has to be something missing in OptiFine_1.21.1_HD_U_J1.
I've tested BSL 8.3 and older to exlude the shader problem. 
Are there any big changes in code for custom models between 1.20.4 and 1.21.1 vanilla minecraft release? 
## Steps to Reproduce

Install the OptiFine_1.21.1_HD_U_J1 with BRIXEL + BSL shader

## OptiFine Version

OptiFine_1.21.1_HD_U_J1

## Other Installed Mods

just optifine+ bsl shader

## F3 Debug Screenshot
OptiFine_1.21.1_HD_U_J1
![2024-09-27_09 00 00](https://github.com/user-attachments/assets/51c08840-f1ed-4730-8718-5d21b71f9093)
![2024-09-27_09 11 17](https://github.com/user-attachments/assets/f09e2cf5-23a4-44dd-996a-5d5a94e7b31e)
OptiFine HD U I7 
[2024-09-27_14 50 30](https://github.com/user-attachments/assets/2a2c59bd-4e20-4fbc-8583-423524c7bec9)
![2024-09-27_14 50 50](https://github.com/user-attachments/assets/124e08f6-d7b5-4bfd-ab07-36d31c846bbe)

## Prior Testing
It works fine in all prevous releases of optifine like OptiFine HD U I7 so it makes me beleve there has to be something missing in OptiFine_1.21.1_HD_U_J1.

## Additional Information

Free version of Brixel for debug 
[Brixel 3.2 64x BSL - unpack this in your .minecraft folder.zip.zip](https://github.com/user-attachments/files/17164072/Brixel.3.2.64x.BSL.-.unpack.this.in.your.minecraft.folder.zip.zip)

**Comment by sp614x** [comment]
The resource pack is using invalid file names, uppercase letters are not allowed.
Only following characters are allowed in resource pack file names: `a` to `z`, `0` to `9`, `_`, `-` and `.`.
In previous versions the OF check was more relaxed than vanilla, in 1.21 OF was changed to follow the MC standard.
```
[Worker-Main-4/WARN]: [OptiFine] Error loading model: minecraft:models/item/allium.json
[Worker-Main-4/WARN]: [OptiFine] com.google.gson.JsonParseException: block/flower/allium_B is not valid resource location
...
[Worker-Main-2/WARN]: Invalid path in datapack: minecraft:textures/block/flower/allium_B.png, ignoring
```
