### ISSUE TITLE
No pt-br language

### ISSUE THREAD

**Issue by Inky1003** [sp614x/optifine#778]
Hello
There are too many brazilians that don't know fluently the english language. Please, can you an pt-br(Brazilian Portuguese) language strings file?
Inky from Brazil

**Comment by sp614x** [comment]
You or anyone else who knows brasilian portuguese, can create a new language file here: https://github.com/sp614x/optifine/tree/master/OptiFineDoc/assets/minecraft/optifine/lang
then submit a pull request and it will be added to the OptiFine translations.
