### ISSUE TITLE
[1.21.3] Mipmapping is incorrect

### ISSUE THREAD

**Issue by Lolothepro** [sp614x/optifine#7780]
## Description of Issue

Mipmapping is incorrect

## Steps to Reproduce

1. Launch Minecraft

## OptiFine Version

J2_pre1

## Installation Method

Prism

## Screenshot

![2024-10-28_18 56 11](https://github.com/user-attachments/assets/d4c37b96-3edb-4585-8cdf-5d9d2a972018)

**Comment by sp614x** [comment]
Fixed, coming in next preview.
