### ISSUE TITLE
[GFX] The “Fast” setting does not work for leaves.

### ISSUE THREAD

**Issue by Lolothepro** [sp614x/optifine#7781]
## Description of Issue

The “Fast” setting does not work on leaves.

## Steps to Reproduce

1. Launch Minecraft
2. Try to change the graphic setting

## OptiFine Version

J2_pre1

## Installation Method

Prism

## Video

https://github.com/user-attachments/assets/fd97e8f6-18e4-416a-8698-2103c0052935

**Comment by CeelB-2055440** [comment]
I have noticed this same issue. Also when they look really bugged out from a distance when using an x32 resource pack.

**Comment by sp614x** [comment]
Fixed, coming in next preview.
