### ISSUE TITLE
[1.21.3 pre1 Bug] Infinite loading screen with resource pack enabled

### ISSUE THREAD

**Issue by SeaOfPixels** [sp614x/optifine#7782]
## Description of Issue
In 1.21.3 pre1, attempting to enable my resource pack New Default+ causes an infinite loading screen. The game doesn't crash, so I can't seem to get a crashlog to see what's causing it. Given the statement "CEM and CIT models are not working", I'd assume my resource pack including those is what's causing it. For debugging purposes, here is a link to the resource pack: https://legacy.curseforge.com/minecraft/texture-packs/newdefaultplus/files/5793752

## OptiFine Version
1.21.3 J2 pre2

**Comment by sp614x** [comment]
Fixed loading of CIT models
