### ISSUE TITLE
[1.21.3] No cloud rendering

### ISSUE THREAD

**Issue by Lolothepro** [sp614x/optifine#7785]

**Comment by sp614x** [comment]
What clouds (fast, fancy), shaders, resource pack?
Normal clouds work for me:
![image](https://github.com/user-attachments/assets/9f0ca416-29ca-4d26-8a20-da03a9f168c6)

**Comment by Lolothepro** [comment]
No idea how I caused this bug, I'll close it, and reopen it if I find it.
