### ISSUE TITLE
[Shader] Mipmap of block atlas texture inconsistent in deferred pipeline

### ISSUE THREAD

**Issue by GeForceLegend** [sp614x/optifine#7786]
## Description of Issue

Detailed info is provided in [Iris #2501](https://github.com/IrisShaders/Iris/issues/2501). Optifine's behavior in provided example is same as Iris.

## Steps to Reproduce

1. Set certain colortex to block atlas texture in composite pipeline (like `texture.composite.colortex6 = minecraft:textures/atlas/blocks.png`)
2. Set output of composite program to the block atlas texture with mipmaps (like `textureLod(colortex6, texcoord, 4.0)`, colortex6 has been set to block atlas texture as above)
3. Switch held item and see sometimes mipmap of block atlas texture is on but sometimes off

## OptiFine Version

1.21.1 J1

## Installation Method

Standalone

## Log Files/Crash Reports

Looks like nothing useful in log.

## F3 Debug Screenshot

![2024-10-29_16 43 31](https://github.com/user-attachments/assets/3ae34d59-50ee-4430-bcb7-51dada49cae0)
![2024-10-29_16 43 42](https://github.com/user-attachments/assets/63b4e6ab-52ac-4705-9cbd-0a3746c71f73)

**Comment by sp614x** [comment]
The block atlas mipmaps in deferred/composite/final should be enabled.
Fixed, coming next 1.21.3 preview.
