### ISSUE TITLE
1.21.3 blocks in water with shaders is just gray

### ISSUE THREAD

**Issue by proswag69** [sp614x/optifine#7787]
## Steps to Reproduce

1. What do you do...
2. ...to find this bug? i just look at caves and water and cannot see blocks inside just are gray clouds until I come close

## Installation Method

 just clicked download link  and auto installed

## F3 Debug Screenshot
!
![2024-10-29_13 18 33](https://github.com/user-attachments/assets/eea7c8bc-8d53-4ae0-b57f-42228cf1bd6e)
![2024-10-29_13 18 42](https://github.com/user-attachments/assets/8b27cc0e-bca5-43b9-b6b6-06863a0717a0)
![2024-10-29_13 19 28](https://github.com/user-attachments/assets/27db10a7-0efd-4574-9c6a-a420b2d24120)
![2024-10-29_13 19 33](https://github.com/user-attachments/assets/c3c7bd4e-0077-49ab-88cc-71472069dbbb)
sets/22579a54-caba-44dd-8e2a-8e08fdfab858)

**Comment by sp614x** [comment]
Fixed in pre3
