### ISSUE TITLE
Grass blocks in CTM are green-sided everywhere

### ISSUE THREAD

**Issue by kcrca** [sp614x/optifine#779]
I have a texture pack in which grass is ctm'ed, and the sides of the grass blocks are greenish. Compare the following two pics, the first without ctm the second with:

![2017-07-19_21 37 40](https://user-images.githubusercontent.com/923203/28400840-9c49c4e4-6cca-11e7-819b-e98f120f146c.png)

![2017-07-19_21 38 00](https://user-images.githubusercontent.com/923203/28400842-9dfa53d0-6cca-11e7-8aa3-2fe8b238ec21.png)

Obviously I want the sides of the grass to look more like what they do in the first shot.

You can download a version of my texture pack with the problem at http://claritypack.com/Clarity\ 1.12.zip @`

**Comment by sp614x** [comment]
The grass sides are colored per biome. 
The vanilla model uses two textures on top of each other:
- `blocks/grass_side` ![grass_side](https://user-images.githubusercontent.com/16635441/28412598-031683cc-6d45-11e7-85fe-9b375fbc7550.png)
- `blocks/grass_side_overlay` ![grass_side_overlay](https://user-images.githubusercontent.com/16635441/28412601-06ce871c-6d45-11e7-8491-96083f74ebfa.png)

Only the second texture (overlay) is colored.

If you want to get a similar effect (bottom not colored, top colored), then you have to make separate rules per texture and include a connected overlay texture which has the bottom part transparent.

**Comment by kcrca** [comment]
I believe I’ve done exactly that. I’ve attached a zip file for the two ctm’s, they look like what I think you’ve said to do. Any help will be, well, helpful, thanks.

grass_side/block2.properties:
> method=horizontal
> tiles=1 2 3 0
> innerSeams=false
> connect=tile
> solid=0
> faces=sides

grass_side_overlay/block2.properties:
> method=horizontal
> tiles=1 2 3 0
> innerSeams=false
> connect=tile
> solid=0
> faces=sides

		Ken
		健
