### ISSUE TITLE
Pale garden 

### ISSUE THREAD

**Issue by Scattttty** [sp614x/optifine#7791]
pale garden leaves don’t move. 

## Steps to Reproduce

1. What do you do... 
2. ...to find this bug?

**Comment by GeForceLegend** [comment]
This is mostly a shader related issue as pale oak leaves haven't been added into `block.properties` of most shaders, so they do not consider them as leaves. However, if the shader you are using does not contain `block.properties`, then Optifine should add pale oak leaves to legacy mapping

**Comment by sp614x** [comment]
Shader packs have a list of the moving block IDs.
The shader pack have to be updated.
