### ISSUE TITLE
[Shader | 1.21.3] Shadowmapping only renders chunk very near on some shaders

### ISSUE THREAD

**Issue by GeForceLegend** [sp614x/optifine#7795]
## Description of Issue

On some shaders, only very near chunks are rendered in shadowmapping.

## Steps to Reproduce

1. Launch OptiFine_1.21.3_HD_U_J2_pre5
2. Select shaders to SEUS PTGI HRR 3 (tons of earlier PTGI also affected by this)
3. See only terrain in 1~2 chunks near are rendered in shadowmapping and get voxelized.

## OptiFine Version

OptiFine_1.21.3_HD_U_J2_pre5

## Installation Method

Standalone

## Log Files/Crash Reports

Looks nothing useful in log

## F3 Debug Screenshot

![2024-11-17_22 37 09](https://github.com/user-attachments/assets/68e92eba-ac3a-4719-97c4-71583a2ec677)

## Prior Testing

I'v heard this starts at pre3 or pre4, earlier preview OF on 1.21.3 works fine. Not have tested this my self.

**Comment by sp614x** [comment]
Last working version is OF for 1.21.1
