### ISSUE TITLE
Text not displayed on 1.21.3

### ISSUE THREAD

**Issue by SlimeDog** [sp614x/optifine#7798]
## Description of Issue

Text not displayed on MC 1.21.3. Initial screen displays four buttons without text.

![Screenshot 2024-11-18 at 10 23 12](https://github.com/user-attachments/assets/d7ce1f2b-8dc2-4232-b2e7-a75c88aa3218)

Following screens (SinglePlayer or MultiPlayer) similarly display no text.

## Steps to Reproduce

1. Download preview versions of OptiFine 1.21.3
2. Start client
3. Observe screens

## OptiFine Version

preview-OptiFine_1.21.3_HD_U_J2_pre6 (and since preview-OptiFine_1.21.3_HD_U_J2_pre1)

## Installation Method

Java installer: java -jar preview-OptiFine_1.21.3_HD_U_J2_pre6.jar

## Log Files/Crash Reports

No report of OptiFine in server logs. No server crash reports (server does not crash).

`$ grep OptiFine ~/Library/Application\ Support/minecraft/logs/latest.log`
[https://pastebin.com/VjKbhJSS](https://pastebin.com/VjKbhJSS)

## F3 Debug Screenshot

Debug screen contains no text, only background shading.

## Prior Testing

- Does this happen in Vanilla without OptiFine? No.

**Comment by SlimeDog** [comment]
OptiFine is unusable without text. Is there a workaround that I'm missing?

**Comment by sp614x** [comment]
You can disable Antialiasing to fix it for now.
Either click the buttons to get to the AA setting or delete the `optionsof.txt` file in the `.minecraft` folder to reset all settings.

**Comment by SlimeDog** [comment]
> You can disable Antialiasing to fix it for now. Either click the buttons to get to the AA setting or delete the `optionsof.txt` file in the `.minecraft` folder to reset all settings.

Thanks.

**Comment by sp614x** [comment]
Fixed, coming in next preview.

**Comment by SlimeDog** [comment]
Confirmed fixed with preview_OptiFine_1.21.3_HD_U_J2_pre7. Thanks.
