### ISSUE TITLE
[1.21.1-1.21.3 Bug] Custom Bookself Texture Overridden by Optifine

### ISSUE THREAD

**Issue by BerryCutePixels** [sp614x/optifine#7800]
## Description of Issue

Using a resource pack that changes vanilla bookshelf model + optifine together shows incorrectly in-game (pictured below)
When optifine is not installed the bookshelf displays correctly as intended.
When optifine is installed model changes (displays correctly) texture (displays incorrectly) looks like it's force using the vanilla bookshelf texture
Only optifine files in the resource pack itself are some CEM models for entities, a colormap for EXP, and some custom skies.
![image](https://github.com/user-attachments/assets/85354b14-19fe-46a1-a39b-da9f0afe1a8f)

## Steps to Reproduce

1. install optifine
2. install a pack that changes the bookshelf model + new texture
3. run game with pack + optifine install

## OptiFine Version

1.21.3 (HD U J2 pre6) and 1.21.1 (HD U J1 pre9)

## Installation Method

used the standalone installer

## F3 Debug Screenshot

![image](https://github.com/user-attachments/assets/0fedd0ac-3acc-4ab0-b1bb-7d3f8154e3b2)

**Comment by sp614x** [comment]
This comes from Connected Textures.
To disable CTM for the bookshelf add a bookshelf texture in the resource pack.
