### ISSUE TITLE
[Display] Game graphics are significantly darker

### ISSUE THREAD

**Issue by emag1nations** [sp614x/optifine#7801]
## 
It's immediate to see that the UI has some graphics issue, as the text for all buttons is extremely dark and difficult to see. This issue carried on into the game, with the skin barely visible at all, armor slots appearing a yellow-ish color, item symbols not showing up in the creative inventory. Blocks within the game also appear to be a slightly darker shade. The text chat is also a darker shade.
When opening up some creative panels, some items don't seem to appear at all. They have no display to show, so when you hold an item in hand, it appears to be a void item.

No major steps are needed to see the situation. I simply downloaded the mod and saw the change in display.

This all happened in the latest version of optifine, 1.21.3 pre_6.

I have no other mods installed.

## Installation Method

I downloaded the file onto my computer from the website. It appeared under the Recent Files section, so I clicked on it from there. I then clicked install, and then after I got the confirmation it was downloaded, I booted up the game.

## F3 Debug Screenshot

![2024-11-19_19 04 37](https://github.com/user-attachments/assets/5a7bf23b-c425-4c73-97de-ebeff0b8681b)

<!-- If you've installed standalone:

This does not appear to happen outside of optifine, in vanilla minecraft. 
It's possible the issue is with my setup, but I'm hesitant to think it's true based on the visuals when in vanilla.

Here are a few more screenshots

![2024-11-19_19 04 45](https://github.com/user-attachments/assets/56638eef-e499-4915-85a5-56a712fbf108)

![2024-11-19_19 04 28](https://github.com/user-attachments/assets/df786a5a-16fa-4b81-9615-86711b6c923d)

**Comment by sp614x** [comment]
Fixed, coming in next preview.
