### ISSUE TITLE
[1.21.3 Bug] CIT elytras are overriden by player capes even with show capes disabled

### ISSUE THREAD

**Issue by SeaOfPixels** [sp614x/optifine#7802]
## Description of Issue
CIT elytras are being overriden by equipped player capes, even with show capes disabled. This was not the case in previous OptiFine versions. Also affects 1.21. In the screenshot example, I have the veteran cape on my character but have show capes disabled, but still the veteran elytra is overriding the CIT one (CIT elytras really shouldn't be overriden by player capes ever even with show capes enabled, but I digress).

## OptiFine Version
OptiFine 1.21.1 J1, OptiFine 1.21.3 J2 pre5, OptiFine 1.21.3_HD_U_J2_pre6

## Screenshots
![2024-11-19_22 38 34](https://github.com/user-attachments/assets/6a65edaa-7497-4943-871f-daef00424043)

**Comment by sp614x** [comment]
Fixed, coming in next 1.21.3 preview.
