### ISSUE TITLE
[1.21.3 Bug] CIT elytras no longer function in the world, and "Show Capes" still overrides CIT elytras

### ISSUE THREAD

**Issue by SeaOfPixels** [sp614x/optifine#7806]
## Description of Issue
The partial fix of https://github.com/sp614x/optifine/issues/7802 has resulted in CIT elytras not showing in the world, for example on armor stands. Additionally, the "Show Capes" option still overrides CIT elytras when active, which shouldn't be the case (you shouldn't have to disable show capes to see CIT elytras, since CIT elytras are deliberate and thus should always take priority).

## OptiFine Version
OptiFine 1.21.3_HD_U_J2_pre7

## Screenshots
Show capes off (correct on player, incorrect in world):
![2024-11-23_07 49 31](https://github.com/user-attachments/assets/cfeda315-d5d4-4766-b855-ba2c9da02b1e)

Show capes on (incorrect on player and world):
![2024-11-23_07 51 46](https://github.com/user-attachments/assets/0186fbeb-a78d-484c-bcb9-0d639af6b9ef)

**Comment by sp614x** [comment]
Fixed armor stand CIT elytra.
Fixed player CIT elytra not to be overriden by cape texture.
