### ISSUE TITLE
[1.21.3 Bug] Block outlines are invisible.

### ISSUE THREAD

**Issue by Diantina** [sp614x/optifine#7810]
## Description of Issue

Block outlines not visible, when targetting or breaking a Block. Changing the High Contrast Block Outlines to on have the same effect.

## OptiFine Version

Preview OptiFine 1.21.3_HD_U_J2_pre8, Preview OptiFine 1.21.3_HD_U_J2_pre9

## Screenshots
Block Outlines with/without High Contrast Block Outlines in preview 7 (visible):
![2024-11-25_18 24 54](https://github.com/user-attachments/assets/c74f6616-fbe6-4ef9-a50a-45575bd88cf4)
![2024-11-25_18 25 09](https://github.com/user-attachments/assets/1e1037d2-ac38-449d-a68d-108ab0fe6a4f)

Block Outlines with/without High Contrast Block Outlines in preview 8/9 (invisible):
![2024-11-25_17 21 59](https://github.com/user-attachments/assets/af345713-0ab3-4ffb-8922-85758572e9ca)

**Comment by sp614x** [comment]
Fixed, coming in next preview.
