### ISSUE TITLE
[1.21.3 | Shaders] particles.before.deferred=true makes particles not rendered

### ISSUE THREAD

**Issue by GeForceLegend** [sp614x/optifine#7813]
## Description of Issue

When using `particles.before.deferred=true` in shaders.properties, particles become invisible, and I can't find their draw calls in Nsight Graphics capture

## Steps to Reproduce

1. Loading any shader
2. Add `particles.before.deferred=true` into its shaders.properties
3. Save the file, reload the shader, and see particles disappear.

## OptiFine Version

1.21.3 J2 Pre11

## Installation Method

Standalone

## Log Files/Crash Reports

Looks nothing useful in log

## F3 Debug Screenshot

Using ComplementaryReimagined_r5.2.2 as reference. I'v tested 3 shaders and all of them result in same.
![2024-11-29_23 35 44](https://github.com/user-attachments/assets/9615d6ee-cd81-4d1b-b40c-b992105cd5d0)

**Comment by sp614x** [comment]
Fixed, coming in next preview
