### ISSUE TITLE
[1.21.4 | Shader] Normal and specular textures is not using nearest filter

### ISSUE THREAD

**Issue by GeForceLegend** [sp614x/optifine#7822]
## Description of Issue

Normal and specular textures is not using nearest filter, causing visual artifacts when using PBR resource pack and shaders.

## Steps to Reproduce

1. Load any shader that supports PBR
2. Load any resource pack that uses PBR textures (low resolution pack will be better to see this)
3. See normal and specluar data get filtered

## OptiFine Version

1.21.4 J3 Pre1

## Log Files/Crash Reports

Looks nothing useful in log

## F3 Debug Screenshot

Kappa 5.2 + VNR, with emission mode set to hardcoded+LabPBR. VNR is a 16x resourcepack, but the normal is too smooth, and alpha channel of specular texture on white concrete's edge is affected by nearby textures, causing it becomes emissive.

![2024-12-04_09 35 02](https://github.com/user-attachments/assets/4c8cfaec-7a63-4417-b606-8311758aad24)

**Comment by sp614x** [comment]
Is this working correctly in previous versions?

**Comment by GeForceLegend** [comment]
Optifine in 1.21.3 works fine. iirc Iris for 1.21.4 have the same issue, might be Mojang changed something in vanilla.

**Comment by sp614x** [comment]
Fixed, coming in next preview
