### ISSUE TITLE
When it rains it causes the whole world to turn fluorescent green.

### ISSUE THREAD

**Issue by MarcDanielWagner** [sp614x/optifine#783]
As it started raining the world started to turn green (see pictures below for the sequence) 
I'm using 'OptiFine 1.12_HD_U_C4' on Minecraft 1.12 with the 'Faithful 64x64 1.12-1.9.4' resource pack.
Below is the sequence right after it starts raining. I did notice that after the whole screen turned green and I saved and quit and went back in the color was gone but immediately started turning green again.

What's happening? I don't even have an idea as to what is causing this.

![2017-07-21_13 12 10](https://user-images.githubusercontent.com/30352424/28474348-5baf288c-6e16-11e7-956a-8d87b01f4cb9.png)
![2017-07-21_13 12 14](https://user-images.githubusercontent.com/30352424/28474347-5baceee6-6e16-11e7-958e-c8bc706e2f3d.png)
![2017-07-21_13 12 48](https://user-images.githubusercontent.com/30352424/28474349-5baf5dac-6e16-11e7-9a3f-365fbd921071.png)

**Comment by MarcDanielWagner** [comment]
Outside of the cave pictures above this is what is happening above ground...
![2017-07-21_13 18 54](https://user-images.githubusercontent.com/30352424/28474798-ec1dc300-6e17-11e7-9622-27dab352613a.png)

I'm running a Geforce GTX970 with the latest drivers.

**Comment by sp614x** [comment]
Running with Forge or standalone?
Other mods installed, which?
Shaders active?

**Comment by MarcDanielWagner** [comment]
Thanks for the response.
I'm not running with forge just stand alone.
There are no other mods installed.
But I'm running Seus v.11 shader and when I tried a different shader the
problem seemed to go away. Not sure what setting it would be with the SEUS
shader because I've tried turning many things off and adjusting others to
no avail.

**Comment by sp614x** [comment]
Then this is a SEUS problem. 
Some of the recent NVidia drivers had problems with SEUS, downgrading the drivers may help.
