### ISSUE TITLE
[Crash] - Game crashes when blocks are broken 1.21.4

### ISSUE THREAD

**Issue by Reesewwilliams98** [sp614x/optifine#7833]
## Description of Issue

I've been experiencing crashes every time I break a block and rarely when I kill a mob.  It is a guaranteed crash every time I break a block that drops something.

## Steps to Reproduce

1. Breaking any block that drops something, breaking a leaf block does not cause a crash.  Happens in a servers and on single player worlds.

## OptiFine Version

OptiFine HD U J3 pre4 - 1.21.4

## Installation Method

Dropped jar in files

## Fabric/Forge Version

54.0.6

## Other Installed Mods

Xaeros minimap

## Log Files/Crash Reports

https://pastebin.com/ME3yAhb8

## F3 Debug Screenshot

<img width="1920" alt="image" src="https://github.com/user-attachments/assets/8c6c3b65-cab7-4848-acf2-72e07d9e8e6d">

## Prior Testing

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   - Yes
- Does this happen without any mods at all?
   - No
- Does this happen in OptiFine standalone? 
   - Unsure
- Does this happen in Vanilla without OptiFine? 
   - No
- Have you tried using a binary search to find which mods cause this issue?
   - No, I just have one mod and it's a lightweight minimap mod.
   - Does the issue still happen with only the remaining mods installed?
      - Forge/Fabric and remaining mods, without OptiFine --> No

**Comment by sp614x** [comment]
Fixed, coming in next preview
