### ISSUE TITLE
[Bug] Glow squid CEM defaults to normal squid texture

### ISSUE THREAD

**Issue by FFreshLX** [sp614x/optifine#7834]
## Description of Issue

Glow squid CEM seems to default to the normal squid texture. Models in the screenshot are from the CEM Template Loader with some animations added to demonstrate that it's custom. Doesn't seem to matter what edits are made to the model, just that there is one. 

![image](https://github.com/user-attachments/assets/b967fded-6b38-45b4-ab91-d0203fdfece1)

## Steps to Reproduce

1. Create a CEM glow_squid.jem of any form with a valid part and no texture defined.
2. Add it to a resource pack and load it in-game.

## OptiFine Version

OptiFine HD U J2 for 1.21.3. Not tested in preview versions for 1.21.3 or 1.21.4

## Installation Method

Standalone installer used.

## F3 Debug Screenshot

![image](https://github.com/user-attachments/assets/57db1f6b-6ebb-44c2-ac3e-d0920f6214ea)

**Comment by ZenithRogue** [comment]
looks like `ModelAdapterGlowSquid` is incorrectly importing and returning the squid model rather than the glowsquid model
```java
return (AgeableMobRenderer) new SquidRenderer(context, new SquidModel(bakeModelLayer(ModelLayers.GLOW_SQUID)), new SquidModel(bakeModelLayer(ModelLayers.GLOW_SQUID_BABY)));
```

**Comment by sp614x** [comment]
Fixed, coming in next preview.
