### ISSUE TITLE
Invisible textures with Tinker's Construct on 1.12

### ISSUE THREAD

**Issue by federicorl** [sp614x/optifine#785]
That's basically it. Whenever I load TiC on 1.12 with latest stable optifine the standard TiC tools are invisible. Doesn't happen with other mods like PlusTiC tho, don't know what's happening.

[http://imgur.com/SlPAWff](url)

**Comment by AaronSzaboo** [comment]
The issue at the Tinker's Construct tracker: https://github.com/SlimeKnights/TinkersConstruct/issues/3008

They might have found the reason of the bug. Check the discussion for details.

**Comment by gerhard2202** [comment]
https://github.com/sp614x/optifine/issues/775

Seems to be a duplicate of this issue.

**Comment by sp614x** [comment]
Updated preview C5 for 1.12
 - fixed Forge custom sprite loading with dependencies (Tinkers Construct)

**Comment by cyberpunkbln** [comment]
It works perfectly, thx.
