### ISSUE TITLE
Support for Image Load Store

### ISSUE THREAD

**Issue by DethRaid** [sp614x/optifine#791]
Could you add support for the ARB_shader_image_load_store extension, as documented at https://www.khronos.org/opengl/wiki/Image_Load_Store?

The code in the shader might look like 

```glsl
layout(rgba32f) uniform image2D voxelized_world;    // 1024x1024
```

which would have Optifine create a 1024x1024 RGBA32f image that can be accessed through the voxelized_world variable. As that variable name suggests, I want to create a voxelized representation of Minecraft, and also do things like fluid simulation. I'd want a fixed-size one because the math will be much easier than if I'm using screen-space data.

Support for 3D textures could be incredibly valuable as well, since that would map better to fluid simulation.

The OpenGL wiki page suggests order-independent transparency as a possible use for this feature. I could use that for shadows through multiple stained glass blocks maybe, or light transmission through leaves/grass

**Comment by DethRaid** [comment]
Support for a compute shader to update each texture could also be incredibly valuable, but would definitely be a lot of trouble to implement.

**Comment by bobcao3** [comment]
#1120 describes a more CPU-side solution where this can bring us a GPU-side solution, and it can be used in several other more interesting stuff with higher efficiency.

**Comment by DethRaid** [comment]
So like... is there any chance this will ever happen?

**Comment by sp614x** [comment]
Actually yes, I was thinking about playing with it after the shaders start working in 1.15.

**Comment by sp614x** [comment]
Compute programs and imageLoad/Store added in G7_pre11 for 1.16.5
