### ISSUE TITLE
Support for deferred + forward transperancy

### ISSUE THREAD

**Issue by bobcao3** [sp614x/optifine#792]
Just like Unity3D's rendering pipeline, you have the ability to do some deferred shading before transparent is rendered.

So the pipeline will become this:
1. Shadowmap rendering
2. Gbuffers for Opaque / cut-outs
3. (This is important) Some composites, probably will need 3 or more of them with all those gbuffers data available
4. Gbuffers for Transparent (gbuffers_water)
5. Other composites + final

If we have the access to this feature, we will have realistic glass refraction/blurs/reflections. And this will be multi layered.

In most of the shaders pack that has a complex water/glass system, they all do the rendering of water surface after all other deferred lighting and rendering, and before bloom or other full-screen post-processing. This has a huge limitation that we can only store the front most layer of transparent data to the gbuffer (usually in totally different buffers than all those opaque). In most modern triple A titles, a deferred opaque + forward transparent system is used just like the description mentioned before.

**Comment by dotModded** [comment]
This is the plan for nova but if we could get it on both this is a huge plus, I'd love for this to happen. It would save me a lot of bits and make my shader use far less memory bandwidth.

**Comment by sp614x** [comment]
So the idea is to move some of the composites before gbuffers_water and then give access to colortexN in gbuffers_water. Correct?

**Comment by bobcao3** [comment]
Probably also need a depthtex without water in gbuffers_water, just for ray tracing stuff

**Comment by DethRaid** [comment]
I would also love to have this

**Comment by jcm2606** [comment]
If this were to be added, I would prefer it to use a different set of shaders, maybe "deferred0", "deferred1", "deferred2" and "deferred3"?

**Comment by DethRaid** [comment]
That could be good - render the deferred shaders between the gbuffers_terrain and gbufers_water. That way it's easy to opt-in and won't break anything

**Comment by sp614x** [comment]
Preview for deferred programs: http://optifine.net/tmp/OptiFine_1.12.2_HD_U_C7_pre_Deferred.jar 
- added deferred programs `deferred, deferred1, deferred2, ... deferred7`
- rendered between terrain and water (translucent layer) 
- in all other aspects they work identically to composite programs

**Comment by sp614x** [comment]
- added access to `gaux1-4` in gbuffers programs when deferred programs are available

**Comment by sp614x** [comment]
Added to official preview C7 for 1.12.2.
