### ISSUE TITLE
Transparent section of beacon beams does not write to any depth buffers

### ISSUE THREAD

**Issue by Builderb0y** [sp614x/optifine#796]
The opaque section writes to all 3 depth buffers, however the transparent section doesn't write to any of them. This is a problem for shaders because water and other transparent things end up rendering in front of it when they should be behind it (which can mess up auxiliary data written by the beacon beam).
![](http://i.imgur.com/pISyTHf.png)
In that screenshot, water has been modified to be completely opaque, and as you can see, it cuts off the transparent section of the beam entirely. Additionally, the top half of that screenshot shows depth information (red = depthtex0, green = depthtex1, and blue = depthtex2), and you can also see that the transparent section of the beam doesn't show up in any of them.

Shader used for that screenshot can be found [here](https://www.dropbox.com/s/v835pdvsu60dmn8/Beacon%20depth%20test.zip?dl=0).

Using preview HD_U_C5 for MC 1.12.

**Comment by sp614x** [comment]
Updated preview C9 for 1.12.2
 - added shaders configuration for beacon beam depth (#796)
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.properties#L53
