### ISSUE TITLE
1.12 - Inventory items not appearing within player inventory

### ISSUE THREAD

**Issue by Seth0067** [sp614x/optifine#797]
I realize this may be a mod interaction, but when I remove Optifine, this problem goes away.

On my particular pack (you can view mods at http://modlister.com/user/Seth0067), with Shaders turned ON (any other than "internal"):

When I open my inventory, all of my in-hand items vanish from my hotbar and internal inventory. Additionally the modded GUI tabs are missing and armor does not appear. The only thing in the GUI popup is my 3D character model.

I am using Forge 2424, which I know is not supported in the current Optifine version (tried this with "OptiFine_1.12_HD_U_C4" and the latest preview), but I thought I would let you guys know anyway.  

Let me know if there's anything I can do to get you better information - would be happy to do so!

Thanks and keep up the great work!

**Comment by TygreWolf** [comment]
Related to this issue, using the same version of forge, and version 1.12.2.7.1.9 of Tinker's Construct, there are rendering issues of their resources, including patterns and tools.

Sample log output:
```
[10:39:55] [main/INFO]: [OptiFine] Custom loader: TextureAtlasSprite{name='tconstruct:items/pattern_tough_tool_rod', frameCount=0, rotated=false, x=0, y=0, height=1, width=1, u0=0.0, u1=0.0, v0=0.0, v1=0.0}
[10:39:55] [main/INFO]: [OptiFine] Scaled too small texture: tconstruct:items/pattern_tough_tool_rod, 1 -> 16
```

![image](https://user-images.githubusercontent.com/8293997/28744303-f9165fd0-742b-11e7-99be-75d75c2c06ab.png)

**Comment by Seth0067** [comment]
Also today seeing "GL Error 1283" in the console with inventory glitching without shaders enabled.

**Comment by Seth0067** [comment]
Apologies!  I have been now testing without Optifine at all and this seems to be happening without it installed at all!  I will prusue another route.  Please consider this issue closed on my part.

**Comment by sp614x** [comment]
Latest preview C5 fixes the Tinkers Construct missing textures: https://github.com/sp614x/optifine/issues/785
