### ISSUE TITLE
[Suggestion] Anisotropic Filtering description in 1.7.10

### ISSUE THREAD

**Issue by TheSnowyChickens** [sp614x/optifine#800]
Hello
Is it possible , that you can add a description for the Anisotropic Filtering option ?
I would highly prefer this ,because I never known what this option do.

I dont know , if the higher versions has a description , but I think the 1.7.10 version need it. :)

Thx
![2017-07-29_03 35 53](https://user-images.githubusercontent.com/29357962/28741080-19c1c87c-740f-11e7-9b2f-c0f158163148.png)

**Comment by KaiAF** [comment]
Versions 1.8+ have the tooltip. I personally doubt that it would get added to an older version if it hasn't been already, closing
