### ISSUE TITLE
Custom Enitity Models - Zombie Villagers

### ISSUE THREAD

**Issue by F0RMATTED** [sp614x/optifine#801]
For whatever reason, creating a CEM for zombie villagers has absolutely no effect. Dont know if its a bug or not, would be good to have it fixed though, i'm in the middle of changing all villagers/illagers into pigmen.

**Comment by sp614x** [comment]
Using latest OptiFine for 1.12?
CEM for zombie villagers were added in C1 for 1.11.

**Comment by F0RMATTED** [comment]
Yes i am using Ultra C4 for 1.12. I have changed the models for the Witch, Vindicator and Evoker without any issues, but the zombie villager models refuse to change. Using Optifine by itself, no forge, running on Windows 10 Creators Update.

**Comment by KaiAF** [comment]
Seems to be fixed now, if not let me know, please.
