### ISSUE TITLE
CTM Overlay Issue

### ISSUE THREAD

**Issue by ProxyPlayerHD** [sp614x/optifine#807]
OF Version: U_C4 (updating to U_C5_pre didn't change anything)
Forge: 2389 (doesn't actually matter as it worked beofre without changing Versions)

I used CTM to make Grass kinda lay over other blocks, like sand Stone, Wood, etc.
to make it look a bit more natural... Problem is, this happend:
![2017-08-01_17 05 27](https://user-images.githubusercontent.com/13576843/28838140-b489d60a-76ef-11e7-9b3f-2496ec31a9dc.png)
For some reason the North-West Corner is lighter than the rest, and this is everywhere
![2017-08-01_17 10 53](https://user-images.githubusercontent.com/13576843/28838200-ec6c7dca-76ef-11e7-904d-339a81a63e15.png)
Every North-West Corner has this and i have no idea why... the Textures that are being used worked perfectly fine before and have the same Brightness.

Here a Link to the Pack: [LUNK](http://www.mediafire.com/file/aujwm7gaj35fn0j/Pack.zip.zip)

**Comment by sp614x** [comment]
Does it work with OptiFine standalone (no Forge)?

**Comment by sp614x** [comment]
Looks like `assets\minecraft\mcpatcher\ctm\grass\0.png` is saved in Grayscale mode, not RGB.
Converting to RGB should fix it.

**Comment by ProxyPlayerHD** [comment]
oh wow. it would've taken me hour to see that one.

Thanks!
