### ISSUE TITLE
Optifine 1.8 Zoom Broken?

### ISSUE THREAD

**Issue by Frechette** [sp614x/optifine#815]
Currently zoom doesn't work for my optifine 1.8 forge/liteloader version. It just randomly stopped. I don't know why...

**Comment by Frechette** [comment]
EDIT: It doesn't work at all for some reason. Even on 1.7 or anything else...

**Comment by Coolboy21** [comment]
Are you using the correct keyboard button?

**Comment by sp614x** [comment]
You can check the control options to see which button is configured for zoom.

**Comment by Frechette** [comment]
I am using the right button. I have it set for button 4 and it doesnt work. I tried button 3, doesnt work. I try left/right click button, doesnt work. I am pressing the right buttons because they are also used for my settings on csgo.

**Comment by sp614x** [comment]
Is zoom working when OptiFine is installed standalone (no Forge)?
With Forge + OptiFine only?
