### ISSUE TITLE
Optifine, Minecraft version 1.12 not found

### ISSUE THREAD

**Issue by Oxile** [sp614x/optifine#819]
Hello!

I keep getting this error, even though I did start the game manually and open a new world. I tried several things, cannot find the solution anywhere from Google or Youtube. I've been looking for an answer for almost 2 hours now.

Thank you for any kind of feedback!

**Comment by 71Baker** [comment]
I think you need to provide some more info. Like what version of Optifine, Forge and Minecraft are you running?

**Comment by sp614x** [comment]
Make sure to start vanilla 1.12 (not 1.12.1) once so the launcher can download it.

**Comment by Oxile** [comment]
Thank you guys! 
@sp614x What you said worked, thank you good sir! I didn't even think of it.
