### ISSUE TITLE
Extend normal and specular map support to mobs

### ISSUE THREAD

**Issue by matteorizzo** [sp614x/optifine#824]
It would be extremely cool to add normal and specular maps to mobs (and eventually other entities that are not yet supported).

**Comment by EskiMojo14** [comment]
Are you sure it isn't possible now? I seem to remember being able to do it a long time ago - though that may have been with karyonix's Shader Mod.

**Comment by matteorizzo** [comment]
@EskiMojo14 100% sure and confirmed ; )

**Comment by sp614x** [comment]
Fixed in preview OptiFine C9 for 1.12.2.
