### ISSUE TITLE
Unable to access OptiFine.net in China

### ISSUE THREAD

**Issue by HeartyYF** [sp614x/optifine#826]
I even tried to use SSR but it doesn't work, I just wonder to know if it's because the site is under maintenance or it's blocked by the government.

**Comment by NyanMeow** [comment]
Look sp614x's twitter

> The website is temporary down for maintenance.
Download links are available on http://optifined.net

**Comment by HeartyYF** [comment]
@NyanMeow Thank you...you know, because there is a wall so I hardly visit twitter...
