### ISSUE TITLE
[Shaders] Field of view is wrong when underwater

### ISSUE THREAD

**Issue by DethRaid** [sp614x/optifine#827]
When the player goes underwater, the field of view changes but it doesn't change in gbuffersProjection or gbuffersProjectionInverse (I think), which leads to a few glitches including shadows not lining up with the visible geometry

**Comment by bobcao3** [comment]
This happened also in my shader.
I have this "bug" before, and spend a lot of time dealing with it. And over several month I don't know it's an FOV issue.

**Comment by sp614x** [comment]
OptiFine 1.12.2_HD_U_D2_pre
 - fixed shaders projection matrix when underwater (#1344, #827)
