### ISSUE TITLE
CIT resource pack item color

### ISSUE THREAD

**Issue by PeakXing** [sp614x/optifine#829]
type=item
matchItems=cooked_beef
texture=burrito_beef
nbt.display.Name=＃ff0000beef

or

type=item
matchItems=cooked_beef
texture=burrito_beef
nbt.display.Name=\u00a74beef

The color doesn't change, and the texture doesn't change。
1.11.2_HD_U_B8

**Comment by MisterQuiggly** [comment]
In mine I have and it works for me, so maybe try that? nbt.display.Name=ipattern:\u00A74

**Comment by PeakXing** [comment]
It doesn't work with me

type=item
matchItems=cooked_beef
texture=burrito_beef
nbt.display.Name=ipattern:\u00A74\u725b\u8089\u5377\u997c

**Comment by MisterQuiggly** [comment]
The code I gave you would change the texture if you had a cooked_beed with the name of beef in red.

What are you trying to have it do?

**Comment by PeakXing** [comment]
type=item
matchItems=cooked_beef
texture=burrito_beef
nbt.display.Name=iregex:(\\u00a7d\\u725b\\u8089\\u5377)

@MisterQuiggly  I've got it. Thank you for helping me
