### ISSUE TITLE
Always night in creative

### ISSUE THREAD

**Issue by Dauphni** [sp614x/optifine#83]
When I'm playing in a creative world with Optifine, it is always night. If I use /time to set the time to what should be daytime, it defaults back to the start of night. Trying to set it to night times works as normal.

I've had this issue since the 1.9 versions of Optifine came out, and in vanilla Minecraft it works as it should. I'm not running any other mods.

**Comment by sp614x** [comment]
Options -> Video Settings -> Other -> Time -> Default
