### ISSUE TITLE
Custom Block Item Textures

### ISSUE THREAD

**Issue by badhaloninja** [sp614x/optifine#832]
@sp614x I agree with #406 and hope that you will add support for changing the texture of a block item based on nbt for example it would be useful for command blocks that replaces it's self once it's placed with something else so that you could model it / retexture it for what the command block does.

**Comment by sp614x** [comment]
The normal blocks do not have NBT data, so this will not work with CTM.
The command blocks are tile (block) entities and CTM can't control their textures.

**Comment by badhaloninja** [comment]
@sp614x no not the block texture it's self just the in hand texture

**Comment by badhaloninja** [comment]
just to be clear CIT not CTM

**Comment by badhaloninja** [comment]
#837
