### ISSUE TITLE
I CANT LOGIN TO MY ACCOUNT OPTIFINE WTF!?!?!?!

### ISSUE THREAD

**Issue by Khqlifa** [sp614x/optifine#833]
so i bought an optifine cape and then when i Try and i say TRY and login to my account i can't so i reset my password and i cant and i try every single email i had with all my passwords and i cant so i would like to say Optifine Fix My Account Or Get Sued

**Comment by Abady321x123** [comment]
clam body, Try to login to optifine "login as donator" but your email that you bought It and If It login then see the **I got the confirmation email, but I do not see the cape on my player, what can I do?** [http://optifine.net/faq](url) If not Bank transfer, eChecks, etc... take several days to complete the payment.

**Comment by ZenIsBestWolf** [comment]
If this is still an issue, please contact Support via Discord, Twitter, or Email.
