### ISSUE TITLE
Optifine 1.10.2 Rendering/Texture Issues

### ISSUE THREAD

**Issue by Jack134** [sp614x/optifine#836]
I've had issues with a mini modpack I set up and I managed to narrow down the issues to Optifine (Clarified by testing with the only mod used being optifine.) Basically, (I'm using default optifine settings) if I load up a world, all I can see is a white screen with the crosshair, health & hunger bar, levels, and hotbar being visible. Everything else is white. No keys work apart from Esc. I am lead to believe this is some sort of rendering/texture issue because, upon loading up another world with a minimap mod installed, I am able to see the map on the screen with the map rendering fine. An interesting fact to note is that if I press space, I can see my y-value of the coordinates (below the map) increase.  The delay between me pressing space and the increase in y-value is negligible, which makes me think that there should be little issues with lag. Pressing F3 does not work. I'll try to post a screenshot (assuming I can edit this) later.

**Comment by sp614x** [comment]
If this is a problem with a modpack, then you should list which other mods are installed.
Also Forge and OptiFine versions.

**Comment by Jack134** [comment]
I already tested it using no other mods apart from Optifine. Could you elaborate on what you mean by Forge and Optifine versions? I'm using the 1.10.2 version for both.

**Comment by sp614x** [comment]
Latest Forge for 1.10.2 is #2422 and latest OptiFine for 1.10.2 is E3. 
Are you using these versions and no other mods installed?

**Comment by Jack134** [comment]
I know I'm using the latest version for Optifine for 1.10.2, although I don't think that I'm using the latest version for forge. In 2-3 days I'll update Forge to the latest version and let you know what the result is.

**Comment by Jack134** [comment]
Thank you, updating forge to the latest version worked. However, I'd like to request that you make this more obvious, as most mods would display a message when trying to load that profile, ie. mod x requires forge version x to run.

**Comment by sp614x** [comment]
OptiFine is tested against one specific Forge version, but it is flexible enough to work with a wide range of Forge versions. It is not possible to detect if a specific version of Forge is compatible or not.
