### ISSUE TITLE
[1.7.10 HD U D6] Already Tesselating

### ISSUE THREAD

**Issue by Timeslice42** [sp614x/optifine#840]
Optifine Version: HD U D6 (and various others).

https://paste.ee/p/5GoWe

This is a long standing issue with Forestry trees which only occurs while multi-core chunk loading is enabled. With chunk loading set to default this does not occur. Is multi-core chunk loading fully supported? Is this something that's even fixable on Optifine's side?

**Comment by sp614x** [comment]
Multi-core chunk loading is very complex and it is only guaranteed to work with vanilla. 
It is possible that some mods do not work correctly with it, depending on how they organize the loading/generating of modded blocks/structures.
If there is a conflict the best solution is to turn the multi-core chunk loading off.
