### ISSUE TITLE
Stop reloading the game when changing shaders!

### ISSUE THREAD

**Issue by Paul17041993** [sp614x/optifine#841]
It shouldn't be necessary at all, all you're doing is loading the shader files, compiling them and swapping them out in the program calls...

**Comment by sp614x** [comment]
Do you mean reloading the resources?

**Comment by Paul17041993** [comment]
all of them, yes

**Comment by sp614x** [comment]
The resources are reloaded when switching from non-shaders to shaders mode or when changing between shader packs which have different value for old lighting https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.properties#L25
The first one is needed to reload the block models with extended vertex formats, the second one is needed to update the baked-in light levels in the block models.
