### ISSUE TITLE
My minecraft 1.12 crashs with optifine and java

### ISSUE THREAD

**Issue by RemiZou** [sp614x/optifine#843]
Sorry for my bad english. Today I wanted to play minecraft again so I downloaded java 8, installed it, then minecraft and optifine for 1.12 .

Without optifine, I can play minecraft without any problems. But with optifine, when I came into a world my game crashs after 5 seconds. I tried Optifine for 1.10, 1.8 etc... but always the same problem. 

This is the issue log :
https://pastebin.com/jcKxf3sU

Thanks for you help

**Comment by sp614x** [comment]
The crash is inside the graphics driver:
```
# Problematic frame:
# C  [ig75icd64.dll+0x6a9b5]
```
You could try to disable VBO.
