### ISSUE TITLE
FontRenderer.getStringWidth returns wrong width

### ISSUE THREAD

**Issue by Johni0702** [sp614x/optifine#845]
Note: This is almost certainly the same as #396, however that thread suggests various causes/symptoms that I cannot reproduce and has been close half a year ago.

### Summary
The default font renderer returns values from `getStringWidth(String)` that are smaller than expected for certain inputs using certain resource packs (with HD fonts).

### Example
```
String text = "Login to ReplayMod.com"
FontRenderer fontRenderer = Minecraft.getMinecraft().fontRendererObj;

int width = fontRenderer.getStringWidth(text); // width is 100 but probably should be 101
fontRenderer.listFormattedStringToWidth(text, width);
// ^ expected ["Login to ReplayMod.com"] but is ["Login to", "ReplayMod.com"]
fontRenderer.listFormattedStringToWidth(text, width + 1);
// ^ as expected ["Login to ReplayMod.com"]

width = fontRenderer.getStringWidth("*"); // width is 4 but probably should be 5
fontRenderer.listFormattedStringToWidth("*", width + 1);
// ^ As expected ["*"]
fontRenderer.listFormattedStringToWidth("*", width);
// ^ Throws StackOverflowException
```

### Environment
Minecraft: 1.11.2
Optifine: 1.11.2_HD_U_C3
Forge: build 2366
No other mods (IntelliJ Remote Debugging for testing)
Resource Pack used for the Example: http://www.minecraftforum.net/forums/mapping-and-modding/resource-packs/1242763-conquest-wip-weekly-updates

**Comment by sp614x** [comment]
The given example works correctly with the default resource pack.

**Comment by Johni0702** [comment]
Yes, as mentioned, this only happens with some resource packs (those with HD fonts or possibly only a subset of those).

**Comment by sp614x** [comment]
Updated preview C6 for 1.12.2
- fixed string width calculation for HD fonts
