### ISSUE TITLE
Player Skin does not load in 1.12.1

### ISSUE THREAD

**Issue by AshenPheonix** [sp614x/optifine#846]
So, I decided to do some work on 1.12.1 minecraft and updated my game and optifine (I'm running on a potato right now so it's realistically the best way for me to get minecraft to load properly). I have a redstone testing world, which up until this point has worked fine, however when loading into it in optifine, my player skin does not work. I thought this might be another bug, but I tried opening it in vanilla and even without moving it's working fine. I'm attaching screenshots below.

![2017-08-16_22 09 39](https://user-images.githubusercontent.com/6516394/29396888-a704a6b8-82cf-11e7-94c3-c11b70326c09.png)
![2017-08-16_22 08 28](https://user-images.githubusercontent.com/6516394/29396901-badc5726-82cf-11e7-901c-fb210bdd6820.png)

**Comment by KaiAF** [comment]
Is this still an issue? Could be related to #5195 or #4976?
