### ISSUE TITLE
Weird rendering of structure void and air inside structure bounds

### ISSUE THREAD

**Issue by misode** [sp614x/optifine#847]
Image says it all. Doesn't happen in vanilla.

![javaw_2017-08-17_15-09-27](https://user-images.githubusercontent.com/17352009/29414184-38220da4-835f-11e7-9eee-f2f3db558313.png)

**Comment by Luke18033** [comment]
Is this going to be fixed? Still an issue in 1.13.2

**Comment by sp614x** [comment]
Fixed, coming in next preview for 1.13.2
