### ISSUE TITLE
Suggestion - Custom GUIs

### ISSUE THREAD

**Issue by D3monPixel** [sp614x/optifine#848]
Please make Optifine be able to change the GUI of different inventories or containers.

The custom textures could go in _/assets/minecraft/optifine/gui_ and the properties could allow specification of what gui texture to apply to which inventory or maybe even a biome to change an inventory in.
That would allow a small chest to use a different inventory than just a cut-out of the big chest inventory and also differently colored gui's for shulker boxes or maybe even different carpeted llamas.

I suggest the following formatting of the .properties files:
```
texture=[Name of texture to use]
container=[Name of the block or inventory to use. This also tells what kind of inventory it is (5 slots; hopper, 9 slots; dispenser, 27 slots; shulker box or 54 slots; big trapped chest]
biome=[List of biomes]
nbt=[Only for entity gui's, NBT data that needs to be partially matched, for example by a colored carpet in the correct slot for llamas]
```

**Comment by D3monPixel** [comment]
As an addition to this previous suggestion it would also be cool if the blocks that have a gui also had the ability to change texture when held or placed.

**Comment by sp614x** [comment]
Starting with the chest GUIs.
```
Normal chest
  chest.properties
  chest_double.properties
  
Trapped chest  
  trapped_chest.properties
  trapped_chest_double.properties
  
Christmas chest
  christmas_chest.properties
  christmas_chest_double.properties

Ender chest
  ender_chest.properties
  ender_chest_double.properties
```

Properties `biome`, `height` and maybe `facing`?

Should the suffix be `double` or `large`?

**Comment by sp614x** [comment]
updated preview C6 for 1.12.1
- added Custom GUIs: https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/custom_guis.properties
