### ISSUE TITLE
[BUG?] Certain UI elements that overlay the sky/water are invisible/not blending properly

### ISSUE THREAD

**Issue by Drakonas** [sp614x/optifine#85]
This bug has been existent for a while, and I looked through all the issues and didn't see anything related to it. I have a feeling this isn't fixable, but hopefully someone can help my understand what is happening, as it is slightly irritating (especially at night)

Thankfully recent patches have fixed a lot of the bugs like the empty hand bug. The overlays used to look worse when they were overlaying sky or water... they became super bright white. Now they're just invisible.

This is with the KUDA 6.2.81 Beta Ultra.

It looks to me like the shaders are processing shadows/reflections on the UI elements. Any way to work around that?

Screenshot daytime:
![Screenie](https://dl.dropboxusercontent.com/u/3907397/img/javaw_2016-04-18_17-12-40.png)
Screenshot daytime water:
![Screenie2](https://dl.dropboxusercontent.com/u/3907397/img/javaw_2016-04-18_17-18-33.png)
Screenshot nighttime water:
![Screenie3](https://dl.dropboxusercontent.com/u/3907397/img/javaw_2016-04-18_17-20-16.png)
Screenshot nighttime sky:
![Screenie4](https://dl.dropboxusercontent.com/u/3907397/img/javaw_2016-04-18_17-23-18.png)

**Comment by Drakonas** [comment]
Update: Looking closer, I can actually see the UI elements being reflected on the water:
![Screenie5](https://dl.dropboxusercontent.com/u/3907397/img/javaw_2016-04-18_17-37-46.png)

**Comment by sp614x** [comment]
The shaders should not affect the UI elements (menus, buttons, hotbar, etc).
This looks like a translucent entity, similar to stained glass. Where exactly are the water reflections?
Most shader packs have problems with translucent textures stacking, rendered against the sky or combined with water reflections. For example water reflection behind stained glass. Correct alpha blending is expensive and not easy to get right.

**Comment by Drakonas** [comment]
In the last post you can see the water ripple effect being applied to the text.

**Comment by sp614x** [comment]
The ingame labels are rendered as entities and they are processed by the shaders. 
It looks like this is a shader specific bug, not fixable by OptiFine.
