### ISSUE TITLE
World loading screen per dimension

### ISSUE THREAD

**Issue by sp614x** [sp614x/optifine#850]
The world loading screen should depend on the world dimension
https://www.reddit.com/r/minecraftsuggestions/comments/5veo9s/different_loading_screens/
Optionally animated or panorama.

**Comment by sp614x** [comment]
Added to pocket edition
https://www.reddit.com/r/Minecraft/comments/6ue1bs/pocket_edition_now_has_different_backgrounds_when/

**Comment by r543** [comment]
Would be lovely to have.

**Comment by Coolboy21** [comment]
+1

**Comment by IsaiahPatton** [comment]
Mojang said during a Minecon that when the background of the loading screen is first rendered, the game hasn't yet loaded the information about your destination, so it doesn't know what dimension you're going to yet

**Comment by sp614x** [comment]
For single-player it could guess the new dimension from the current world type and the portal type. 
For multi-player this may not always be correct as the server decides which dimension is to be loaded.

**Comment by sp614x** [comment]
Another option is to start with a generic portal animation depending on the portal type (nether or end portal texture) and fade to the correct texture when the new world starts loading.

**Comment by Coolboy21** [comment]
It would be great to be able to set own texture for own world (in multiplayer), or even server loading screen texture using resourcepack.

**Comment by r543** [comment]
Didn't get to comment on it but I wanted to say that having a generic animation and then switching when decided would be a nice implementation like sp614x said.

**Comment by sp614x** [comment]
Updated preview C8 for 1.12.2
- added custom loading screens per world dimension

Textures are located at `assets/minecraft/optifine/gui/loading/background<dim>.png`.
For example the nether is `assets/minecraft/optifine/gui/loading/background-1.png`

**Comment by CoolboyUA** [comment]
How about texture change depending on the name of the world? (useful for servers)

**Comment by sp614x** [comment]
Added configuratin: https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/loading.properties

**Comment by sp614x** [comment]
@CoolboyUA The world name in multiplayer is always "MpServer"

**Comment by Brottweiler** [comment]
@sp614x any chance you can make the loading screens dim? With custom loading screens in optifine it's very bright, but in default the texture is much more dimmer.

**Comment by sp614x** [comment]
You can make the custom texture dimmer.

**Comment by Brottweiler** [comment]
For anyone wondering, with GIMP. I took the texture I wanted, made a new layer, and made that layer black. Then I made it have 75% opacity (100% opacity is black, 75% opacity is 25% transparent). I compared it with vanilla, and it's identical.
