### ISSUE TITLE
Requesting Permissions

### ISSUE THREAD

**Issue by flareblitz21** [sp614x/optifine#859]
Hello I am here to request permissions to use optifine in a mod pack I saw the licence on
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1272953-optifine-hd-c2-fps-boost-dynamic-lights-shaders
and it says that I may request permissions.
My modpack is hosted on two websites Curse/Twitch, which will not except optifine as it does something with the minecraft code, and Technic. 
Here is the link for the Technic page:
https://www.technicpack.net/modpack/chozo-texh.1084051
It is unfinished at the moment but I would, again, say that I would like you permission in using optifine in the modpack.(Note: The modpack does have optifine in it but is listed as private so only those with the link can view)

**Comment by sp614x** [comment]
Sorry, no.

**Comment by flareblitz21** [comment]
May i ask why you are denying permissions for this mod?

**Comment by DJTiqer** [comment]
If this is still open, I need permission too.
