### ISSUE TITLE
Shader render quality macro

### ISSUE THREAD

**Issue by BruceKnowsHow** [sp614x/optifine#861]
The render quality setting basically plays with the screen DPI, which can have a pretty dramatic effect on certain things, such as dithering, and relative bloom size on screen. I would like to have certain effects scale with the render quality.

You mentioned adding a render res macro to the shaders, this means you will have to start recompiling the shader every time you change the render resolution. I recommend only recompiling after exiting the screen (all the other screens work this way, just wanna make sure you don't forget).

**Comment by sp614x** [comment]
Updated preview C6 for 1.12.1
- added shader macros for user options (FXAA, Normal Map, Specular Map, Render Quality, etc.)
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.txt#L501
