### ISSUE TITLE
[Suggestion] Custom Shield Banner Support

### ISSUE THREAD

**Issue by r543** [sp614x/optifine#862]
Currently in MC the Custom Shields don't support banner patterns and colors.
The patterns exist as texture file, so I wonder if it would be possible to have Optifine add another model(so you have the shiled model+banner area) which supports this.

**Comment by HRudy94** [comment]
The problem is how optifine could do it... (I mean optifine cannot edit nbttags...) The only thing optifine could do is to replace the texture of the shield pattern with a new one in certain circonstancies.

**Comment by ewanhowell5195** [comment]
the shield CEM support should have fixed this
