### ISSUE TITLE
Mipmap flicker

### ISSUE THREAD

**Issue by TheSnowyChickens** [sp614x/optifine#867]
Hello [first , sry for maybe bad english]

Since 1.10.2 optifine I found some flicker in the world , it comes with the mipmap level 1-4.
I can't post screenshots ,but I found a video ,who you can see the flicker. (I hope its ok , when I post the link here) : https://youtu.be/uiGYhQJJvtA

At the begin you can see it clearly , in the background.
Its always in modpacks like this from the video (1.11.2) , or in my own modpack (1.10.2) and in skyfactory3 (1.10.2, newest version) (there I found it).
The user "CD4017BE" (you can see his post in the comments from the Video) has a describtion , from his view why this flicker exist. (but its in German)

I hope you can change there something ,because its very annoying. :)

**Comment by sp614x** [comment]
Looks like the modpack has Better Foliage and some other mod which moves the chunks vertically when they are loading. Only the foliage textures seems to be flickering (leaves, tall grass, vines).
This may be a problem between the chunk mod and the Better Foliage mod.
