### ISSUE TITLE
pt_br.lang stuck with a lot of issues

### ISSUE THREAD

**Issue by DaDodger** [sp614x/optifine#869]
I've noticed several issues in the Portuguese translation of Optifine (by @Inky1003 ) such as missing strings and grammatical errors. Now I'm fixing them. Hope you like it!

A pull request is coming!

**Comment by Inky1003** [comment]
Excuse me, I revised my translation to dont have any grammatical errors, and there were no missing strings, can you explain yourself please?

Or you are a kind of jealous guy that is trying to have te credits to yourself?
