### ISSUE TITLE
Unexpected Gloomy Rendering with Forge (1.9+)

### ISSUE THREAD

**Issue by wbxshiori** [sp614x/optifine#87]
The whole scene including **items in inventory** will have strangely dark color when OptiFine is activated via Forge.  The brightness settings are the same.  Both vanilla 1.9 and OptiFine-only environment aren't affected, so I'm sure this is another issue with forge.
Affecting versions for 1.9 (Tested with B2 pre-release).  Not known if it occurs in 1.9.2 too because forge 1.9.2 isn't out yet.
![renderbugwithforge_1 9b1](https://cloud.githubusercontent.com/assets/17959600/14663008/70b6ca7c-06ee-11e6-9db3-95d6a848e114.png)

**Comment by sp614x** [comment]
Video Settings -> Shaders -> OFF ?

**Comment by wbxshiori** [comment]
The shader settings was left untouched because Fast Render locked it.
I recently tried disabling Fast Render then taking a look at shader settings, and it was OFF.
The problem happens regardless of Fast Render.

**Comment by sp614x** [comment]
The problem seems to appear sporadically, each restart has 50% chance to be broken. This looks like a race condition.

**Comment by wbxshiori** [comment]
In my case, the probability of gloomy bug is 100%.  Even I delete all config files of OptiFine, the bug never disappears.  Also, there seems to be no error message about this.

**Comment by sp614x** [comment]
Fixed in latest preview B2: http://optifine.net/adloadx?f=preview_OptiFine_1.9.0_HD_U_B2_pre.jar

**Comment by sp614x** [comment]
Updated preview B2, fixed long grass shading.
