### ISSUE TITLE
noisetex channel offset for faster 3D clouds

### ISSUE THREAD

**Issue by BruceKnowsHow** [sp614x/optifine#870]
Currently, 3D clouds construct a 3D noise texture out of two 2D noise texture lookups. These 3D noise functions have to be computed a ton of times for 3D raymarched clouds. The 2 texture lookups that the 3D noise function does could actually be accomplished with only 1 texture lookup if the noise texture was modified slightly.

The necessary modification is this: one channel of the noise texture must be identical to another channel, but offset by a couple pixels (17 pixels is standard, this number is not totally arbitrary).

Here is the 3D noise function in my shader:

```glsl
float Get3DNoise(vec3 pos) {
    float p = floor(pos.z);
    float f = pos.z - p;
    
    const float noiseResInverse = 1.0 / noiseTextureResolution;
    const float zStretch = 17.0 * noiseResInverse;
    
    vec2 coord = pos.xy * noiseResInverse + (p * zStretch);
    
    vec2 noise = vec2(
    texture2D(noisetex, coord).x,
    texture2D(noisetex, coord + zStretch).x);
    
    return mix(noise.x, noise.y, f);
}
```

Notice how the second texture2D() is identical to the first, except the coordinate is offset by 17 pixels. Here is how this function would ideally look if you modified the 3rd channel of the noise texture:

```glsl
float Get3DNoise(vec3 pos) {
    float p = floor(pos.z);
    float f = pos.z - p;
    
    const float noiseResInverse = 1.0 / noiseTextureResolution;
    const float zStretch = 17.0 * noiseResInverse;
    
    vec2 coord = pos.xy * noiseResInverse + (p * zStretch);
    
    vec2 noise = texture2D(noisetex, coord).xz;
    
    return mix(noise.x, noise.y, f);
}
```

This would be faster, because looking up 2 components at the same coordinate is still a single texture lookup. Currently, we have to look up 1 component, but at different coordinates separated by a constant, it's two texture lookups.

I don't think this would cause issues with most shaders -- I don't even know anybody who uses all 3 components of the noise texture. You could have an opt-in const just in case, and possibly have it define the offset, i.e.

`const int noisetexOffset = 17; // noisetex.z becomes offset noisetex.x`

It is not feasible to do this in our own custom textures, because custom textures do not interpolate at all, and even if they did, they don't tile nicely like the noise texture does.

**Comment by Builderb0y** [comment]
> custom textures do not interpolate at all, and even if they did, they don't tile nicely like the noise texture does.

Actually, both of those properties can be specified in the .png.mcmeta file:
```json
{
	"texture": {
		"blur": true,
		"clamp": false
	}
}
```
By default (with no .png.mcmeta file included), both are set to false.

**Comment by BruceKnowsHow** [comment]
Okay, a custom noise texture still would not have flexible resolution. It would also require its own buffer, I currently have exactly 1 buffer free and I would like to use a variety of custom textures. I was planning to put them all in a single atlas image, which would not be an ideal place to put a custom noise texture to be used in this way (sampling an atlas would be slower, tiling would get really complicated).

**Comment by sp614x** [comment]
This may be expanded to allow custom noise texture generation:
- noise type (per channel)
- custom noise (load one or more channels from texture)
- channel dependencies (channel A is a function of channel B)
etc.

**Comment by BruceKnowsHow** [comment]
I took Builderb0y's advice and tried it out with a custom texture, performance improvement is great, 3D clouds are almost twice as fast in many situations.

There are two details that you need to pay attention to when generating the modified noise channel:
1. You can't just regenerate the basis noise channel with offset coordinates, you have to mod() the offset. [I made this picture to show exactly what I mean.](https://cdn.discordapp.com/attachments/341758509429424129/353066280062025728/Comp_1_0-00-00-00_0-00-00-00.png)
2. The direction you have to apply the offset in Java is ambiguous, there are 4 possible left/right/up/down combinations. GLSL sampling, Java noisetex generation, and After Effects all seem to follow different conventions as far as which direction coordinates go in. If you stick the noisetex onscreen in Minecraft, the correct offset is down+left. Building the texture in After Effects, I had to do an up+left offset. What the heck needs to happen in genHFNoiseImage()? If you do the wrong comination, then I have to add a single-component multiplication in my function to compensate (not a B I G deal but it is inconvenient). I do not know how we can figure out the right offset direction in the Java code, besides you just trying all 4 of them until we land on it.

Here is my custom noise texture:
![noise](https://user-images.githubusercontent.com/17636733/29958362-5683d86a-8ea7-11e7-89ac-7d5cc5fdfb8c.png)
All I did was display the noisetex onscreen, take a screenshot, clone the red channel and offset it 17 pixels up+left, tile the offset and put it in the green channel.

The new method is active in the [latest Ebin Shaders](https://github.com/BruceKnowsHow/Ebin-Shaders/tree/8e5585a8d8f63e3269792d8125672b0cf4186ce2). It will take a little work to even set up Ebin to check whether the modified noise setup right. I don't want you have to spend a few hours figuring this out with me, but it might be the only option, and I think it would be justified by the big performance gains for any shader that uses this method of 3D noise generation.

**Comment by sp614x** [comment]
So, loading the noise texture from texture file should solve the problem?

**Comment by BruceKnowsHow** [comment]
The only issue with that is that the resolution would not be dynamic... not a big deal because there's not really a case where you would want a dynamic resolution. It would be a pain if you ever realized you needed a different resolution texture, then you have to go remake it, but that has honestly never happened so probably not a worry.

If you let us overwrite the noise texture I think that would work fine.

**Comment by sp614x** [comment]
Updated preview C6 for 1.12.2
- added custom noise texture: https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.properties#L62
Currently the custom texture ignores the `noiseTextureResolution`, no rescaling.
