### ISSUE TITLE
Lines and boxes around placed items and boxes.

### ISSUE THREAD

**Issue by Deluvina** [sp614x/optifine#871]
This issue happens whilst using optifine. Not sure how to fix it, I have tried the old fixes for disabling antialiasing in my nvidia control panel which used to fix this for vanilla MC. Any suggestions?

**Comment by sp614x** [comment]
Screenshot?
Video Settings -> Quality -> Antialiasing -> OFF ?

**Comment by Deluvina** [comment]
To be honest, that was off but I tried turning it back on and the issue is fixed. Which is odd.

**Comment by sp614x** [comment]
If turning it ON fixes the problem, then the driver is forcing some sort of AA on the game.
