### ISSUE TITLE
A simple shorthand for if-then-else statements for CEM animation?

### ISSUE THREAD

**Issue by DNGR-Tyler** [sp614x/optifine#872]
Hello.
I'm not sure about Java, to tell you the truth, I never once learn a thing about Java language.
But, I know some web programming languages. With those languages, I could do _if/else_ shorthand like this: `(x = y) ? true : false`. I think this would be nice to have for CEM animation. What do you think?

**Comment by sp614x** [comment]
Updated preview C7 for 1.12.2
- added boolean expressions for CEM animations
- function `if(cond, val, [cond2, val2, ...], val_else)` select a value based one or more conditions
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/cem_animation.txt#L118
