### ISSUE TITLE
.obj models in resourcepacks

### ISSUE THREAD

**Issue by Coolboy21** [sp614x/optifine#874]
In snapshot 14w06b this ability was added, but unfortunately, it was removed in next snapshot.
It would be great to bring it back.

Video with demonstration:
https://www.youtube.com/watch?v=CGoFCIJgt7I
and this
https://www.youtube.com/watch?v=iEh5j4ZBV88

**Comment by sp614x** [comment]
Snapshot 14w06b had only bugfixes, no new features.
https://minecraft.gamepedia.com/14w06b

**Comment by Coolboy21** [comment]
Just typed in google snapshot name and realized that's json but with less restrictions.
Reddit changelog: https://www.reddit.com/r/Minecraft/comments/1x6ino/minecraft_snapshot_14w06a/

![](http://i.imgur.com/Quo9nQ7.png)

But is it possible to add ability to use .obj files in resourcepacks?

**Comment by sp614x** [comment]
The JSON model is very specific to Minecraft (face culling, ao, handheld rotations, tint index, etc). A general OBJ model can't do this. It may be possible to make a tool which converts OBJ to JSON models.
