### ISSUE TITLE
[1.12.1] Weird black box

### ISSUE THREAD

**Issue by KokkieBeer** [sp614x/optifine#876]
Hello,
I have this issue where when I go to a chunk border and look down a long shaft there is a black box with (sometimes) an orange stripe at the side (see pictures).
If you need more info just ask.
Also when I get too close it disappears, and when I go to the block on the right it also disappears.
![2017-09-01_21 56 47](https://user-images.githubusercontent.com/24627191/30002122-de5767e2-90a1-11e7-88be-f2ccee93110a.png)
![2017-09-01_21 56 49](https://user-images.githubusercontent.com/24627191/30002124-de5bb928-90a1-11e7-9fe2-2f7003343d5b.png)
![2017-09-01_21 57 07](https://user-images.githubusercontent.com/24627191/30002123-de5ba4ec-90a1-11e7-877a-f1a437060fb9.png)

**Comment by Builderb0y** [comment]
Possibly related to #400?

**Comment by sp614x** [comment]
Looks the same as #400.
This is a vanilla problem and it is not easy to fix.
OptiFine tweaks the visibility detection a little and this results in different problematic cases.
There are cases which work in OptiFine and don't work in vanilla. And there are cases that work in vanilla and don't work in OptiFine.
