### ISSUE TITLE
[Suggestion] Add option for interpolation to custom animations

### ISSUE THREAD

**Issue by MisterQuiggly** [sp614x/optifine#878]
As the title suggests, maybe it could be like:

>   from=<path to animation>
>   to=<path to texture to animate>
>   x=<x coordinate of area to animate>
>   y=<y coordinate of area to animate>
>   w=<width of area to animate>
>   h=<height of area to animate>
>  interpolate=true/false (default false if interpolate wasn't added by owner)>

But it could also be how you would see it to best work in the properties file.
I hope you like it and it gets added because I believe it could be useful?

**Comment by sp614x** [comment]
OptiFine 1.12.2_HD_U_E1
 - added interpolate and frame skip to Custom Animations

https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/custom_animations.txt#L34
