### ISSUE TITLE
[Suggestion] Separated color settings for 'portal' particles

### ISSUE THREAD

**Issue by realjackasterisk** [sp614x/optifine#881]
I've recently changed the color of Nether portal particles to match the changes I've made in my resource pack. After playing around for a while, I realized that this setting also changed the colors of particles for several different things, like the Endermen, Eye of Ender, etc. I thought this was a bug at first, and I was actually about to report this as one, but then I did a little more looking around and realized it all uses the same particle in-game.

What I would like to suggest is to split the options for these particles, so that each element can have different colors according to color.properties in the resource pack.

The list of particles could be something like this:
```
particle.portal
particle.enderman
particle.endermite
particle.pearl
particle.endereye
particle.enderchest
particle.dragonegg
particle.gateway
```

**Comment by r543** [comment]
Would love to see this(hope we also have custom colors again soon) I did think of this a while ago when I read about a retro texture pack not being able to restore the old enderman particles.
Wonder if we could also have them use different particle textures.

**Comment by Coolboy21** [comment]
Just imagined a custom particle models... Unfortunately, particles are not entities, and this is, maybe, impossible.

**Comment by r543** [comment]
@Coolboy21 True, but what about having different sprites for them? would already be a good start.

**Comment by sp614x** [comment]
Currently it is not possible to detect what generated the portal particles (portal, enderman, etc). 
All particles are rendered from one texture for performance, only the particle color can be changed.
