### ISSUE TITLE
Optifine ''deleted my mc account''

### ISSUE THREAD

**Issue by AkixZZ** [sp614x/optifine#882]
Ok so basically 2 days ago I think i changed my cape design.There were 2 errors at  cape design so I had to change to other design,then when I closed my mc and run it again it said that I need to log in,I tryed but it didnt work,It happened before like 2 times but bug was fixed in 12h,Now i dont have my mc account
IGN:AkixZZ
These people in comment section dont have their accounts as well as me
Also I wanted to say that when I try to change my password or gmail I can't I don't get email.
https://www.youtube.com/watch?v=3SjyCz_-ojM
Please get my acc back <3

**Comment by sp614x** [comment]
Relevant issue: https://github.com/sp614x/optifine/issues/582

**Comment by sp614x** [comment]
The username/password are sent to the Mojang login server, which decides if the login is valid or not.
After severail failed attempts the Mojang login server may lock the account temporary (24h) or permanently (requires password change). The temporary block (10/20/40 min) is to avoid the block by the login server.

The only possible solution is to try again later or to change the password. Trying many times with wrong password may lead to the account being locked temporarily or permanently.
