### ISSUE TITLE
Indicate used blend mode for gbuffer shaders.

### ISSUE THREAD

**Issue by Choca13** [sp614x/optifine#884]
As said in the title, sending an attribute/uniform that would indicate the blend mode which is currently used would help to support custom skies with multiplicative blend mode for example.

**Comment by sp614x** [comment]
Is this only helpful for custom skies or generally (mods, translucent items, etc)?

**Comment by Builderb0y** [comment]
I would say generally, as mods that use anything other than alpha blending often have visual artifacts when using shaders. This would give shader developers the ability to compensate for that somewhat.

**Comment by sp614x** [comment]
OptiFine 1.12.2_HD_U_D2_pre
 - added shaders uniform blendFunc (#884)
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.txt#L164
