### ISSUE TITLE
[Request] CIT for Shulker Box

### ISSUE THREAD

**Issue by Yogunmm** [sp614x/optifine#885]
Hi sp614x !
Can you add the "Shulker Box" to the "Custom Items Textures" (CIT) ?

**examples for the "purple_shulker_box" :**
type=item
items=229
texture=./aquadolphin
nbt.display.Name=Aqua Dolphin

_With all good wishes._

**Comment by TomLewis** [comment]
Did this get added?

**Comment by ewanhowell5195** [comment]
shulker boxes support CIT. issues occur when placed in the world, but that is due to the server syncing data with the client, and is unfixable by optifine. i am closing this as completed, as the item form of shulker boxes support CIT just fine
