### ISSUE TITLE
[REQUEST] Support for Elytra CIT?

### ISSUE THREAD

**Issue by LordIgnis** [sp614x/optifine#89]
I'm not sure if its currently possible using the already implemented MCPatcher CIT features but being able to change the model of the Elytra like you would do for the Armor would be a great addition

**Comment by sp614x** [comment]
CIT can only change the armor texture, not the model.
The elytra texture can be easily changed: assets\minecraft\textures\entity\elytra.png.
CIT support for elytra based on enchantment and durability added to TODO list.

**Comment by sp614x** [comment]
Elytra CIT added in latest preview B3 for 1.9.
Use "type=elytra" in the CIT properties.
