### ISSUE TITLE
Custom sky dependent on biome

### ISSUE THREAD

**Issue by MushirMickeyJoe** [sp614x/optifine#892]

**Comment by sp614x** [comment]
One problem is that the biome transition is sharp. 
Some biome smoothing would be needed to make it acceptable.

**Comment by sp614x** [comment]
Updated preview C7 for 1.12.2
- added Custom Sky options: biomes, heights and transition
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/sky.properties#L126
