### ISSUE TITLE
Extended lightmap generation size.

### ISSUE THREAD

**Issue by robobo1221** [sp614x/optifine#894]
So currently the default lightmaps of emitters and the sky only go up to 16 blocks. Could you add an constant to control the lightmap distance from it's source?

For example:
`const int lightmapEmitterSize = 16;` 
and
`const int lightmapSkySize = 16;`

With this feature, we could do accurate lighting when it comes to lightmaps (inverse square root law, etc).

**Comment by McHox** [comment]
+1

**Comment by sp614x** [comment]
The light levels 0-15 are hardcoded in many places and can't be changed. 
They are saved on disk as 4 bits and used in light propagation. 
They also affect the gameplay (mob spawning, plants growing, grass spreading and snow/ice melting).

**Comment by robobo1221** [comment]
Hm fair enaugh
