### ISSUE TITLE
Running on Integrated Graphics

### ISSUE THREAD

**Issue by rainartchik** [sp614x/optifine#895]
I'm not even sure if this is an issue but I can't find an answer anywhere. When I run Minecraft without Optifine it runs on my GTX 1070 but when I run it with Optifine it runs on the Intel integrated graphics, which I do not want to happen. I can't see any way to make it run with the GTX.  I use Optifine because I have resource packs installed that require it but I will have to stop using it and find new resource packs if it won't run on the GTX. I never play games with the integrated graphics. Should Optifine be running with my GTX???

**Comment by sp614x** [comment]
OptiFine can't decide which GPU to use. This is something that the operating system or the graphics driver decides. There should be settings in the graphics driver control panel which GPU to use for each program. Make sure that "java.exe" or "javaw.exe" is configured to use the Nvidia.

**Comment by rainartchik** [comment]
Thank you for responding but that didn't work. I added both in the Nvidia
Control Panel but Optifine is still running on the integrated graphics

**Comment by rainartchik** [comment]
I've tried everything and I still can't get Optifine to run with the Nvidia. I've uninstalled it. I can't (won't) run Minecraft on the integrated graphics.

**Comment by rainartchik** [comment]
I managed to get it fixed. It's a new computer so it needed some tweaks. Working fine now.
