### ISSUE TITLE
Sensitivity glitch

### ISSUE THREAD

**Issue by TheDarkShadowYT** [sp614x/optifine#897]
I have been using optifine for a while and just recently I logged onto my forge profile that I have been using for a long time and has optifine on it, I logged into a server and whenever I moved my head around it would always flicker in that direction or do a full 360 when I barely move my mouse. I tried some other servers, survival worlds, and even trying a different profile but nothing seemed to work. I finally did some research and learned that it is something with optifine but when I uninstalled optifine and tried nothing changed, it was still messed up. This has been going on for a long time now and **NONE** of the solutions online work! If you need any more info or have a solution please tell me or email me and I will try that or tell you what you need but please respond quickly this is SO annoying! Thank you!

**Comment by KaiAF** [comment]
Seems to be related to #1761 and that should have been fixed. If you are still having any issues, let me know.
