### ISSUE TITLE
error on gamelog

### ISSUE THREAD

**Issue by JaviertINC** [sp614x/optifine#898]
Error:

Couldn't get hash for optifine/OptiFine/1.12.1_HD_U_C6_pre/OptiFine-1.12.1_HD_U_C6_pre.jar from https://libraries.minecraft.net/optifine/OptiFine/1.12.1_HD_U_C6_pre/OptiFine-1.12.1_HD_U_C6_pre.jar.sha1: HTTP 404: Not Found
--
14:16:01 | launcher | Have local file C:/Users\JaviertINC\AppData\Roaming\.minecraft\libraries\optifine/OptiFine/1.12.1_HD_U_C6_pre/OptiFine-1.12.1_HD_U_C6_pre.jar but don't know what size or hash it should be. Have to assume it's good.
11:16:07 | game | OptiFineTweaker: acceptOptions OptiFineTweaker: injectIntoClassLoader OptiFine ClassTransformer OptiFine URL: file:/C:/Users/JaviertINC/AppData/Roaming/.minecraft/libraries/optifine/OptiFine/1.12.1_HD_U_C6_pre/OptiFine-1.12.1_HD_U_C6_pre.jar OptiFine ZIP file: C:\Users\JaviertINC\AppData\Roaming\.minecraft\libraries\optifine\OptiFine\1.12.1_HD_U_C6_pre\OptiFine-1.12.1_HD_U_C6_pre.jar OptiFineTweaker: getLaunchArguments OptiFineTweaker: getLaunchTarget   <log4j:Event logger="LaunchWrapper" timestamp="1505754967329" level="INFO" thread="main">     <log4j:Message><![CDATA[Launching wrapped minecraft {net.minecraft.client.main.Main}]]></log4j:Message>   </log4j:Event>
11:16:07 | monitor | expected <

**Comment by sp614x** [comment]
OptiFine is not hosted on "libraries.minecraft.net" and it is not meant to be automatically updated by the launcher. The warning is normal.

**Comment by JaviertINC** [comment]
Thx ;)
