### ISSUE TITLE
Texture Pack menu BUGGGGG

### ISSUE THREAD

**Issue by RRR222** [sp614x/optifine#899]
I'll stuck in the Texture pack menu if I try to enter it
(https://user-images.githubusercontent.com/32079404/30567416-7d9933ac-9c8d-11e7-8ad1-a4acf735e61e.jpg)

Plz fix it ;(((

**Comment by sp614x** [comment]
Error log or game output?

**Comment by RRR222** [comment]
No,I'll still stuck in the Texture pack menu if I try to enter it after I relog.Is my setting wrong or it's just a bug of optifine?(the version that Im using OptiFine 1.8.9 HD U H8)
U should watch this,it's my YT video:
https://www.youtube.com/watch?v=GqJn_VzT7mI

**Comment by sp614x** [comment]
You can remove all resource packs and then add them one by one until the problem appears.

**Comment by RRR222** [comment]
I think maybe I have too many packs
but.... idk

**Comment by RRR222** [comment]
Now Im using a Mod that fixed this bug
![Uploading javaw 2017-09-23 14-03-19-268.jpg…]()
