### ISSUE TITLE
OptiFine H1 Ultra to H4 Ultra (preview) shaders hand glitch

### ISSUE THREAD

**Issue by rexcaptain501** [sp614x/optifine#9]
Starting with most, if not all versions related to OptiFine H1 Ultra, whilst shaders are activated the 1st person hand has some sort of transparency glitch inside blocks and other players.

Graphics Card: ASUS STRIX NVIDIA GeForce GTX 750 Ti 2GB OC

Drivers tested: NVIDIA 361.43 (H1, H2 and H3 I believe) and the latest driver (at time of the issue post) NVIDIA 361.91 (G9, H1 and H4 I believe), both have the same result.

The main shader pack I tested with was SEUS v10.1 Standard.

Affected versions:

Working fine - G9 Ultra and previous

Affected - Most, if not all versions relating to - Ultra H1, Ultra H2, Ultra H3 and Ultra H4 (Preview). (All at time of the issue post).

Screenshots:

1. (https://cloud.githubusercontent.com/assets/10300935/13239585/6185c0e2-da40-11e5-8b28-abf2f3e73e21.png)

2. (https://cloud.githubusercontent.com/assets/10300935/13239604/83439704-da40-11e5-8689-b29fe92639f2.png)

**Comment by sp614x** [comment]
Is only the empty hand affected or also handheld blocks and items?

**Comment by sp614x** [comment]
Most probably caused by the change in ShadersRender.renderItemFP() which fixes handheld translucent items (3D water bucket).

**Comment by rexcaptain501** [comment]
Tested with H3 Ultra - handheld blocks and items are affected too.

Screenshots:

Diamond Sword - (https://cloud.githubusercontent.com/assets/10300935/13264656/16393a30-dad4-11e5-8ae2-df3bd05c34cd.png)

Diamond Pick - (https://cloud.githubusercontent.com/assets/10300935/13265121/2598f496-dad6-11e5-8dd1-01847918f272.png)

Stone Block - (https://cloud.githubusercontent.com/assets/10300935/13265242/c1070f58-dad6-11e5-832a-5aa78c49455e.png)

Grass Block - (https://cloud.githubusercontent.com/assets/10300935/13265461/e770ee88-dad7-11e5-9f24-6a0fb4cdb44d.png)

Oak Wood Plank - (https://cloud.githubusercontent.com/assets/10300935/13268407/33ba3b46-dae7-11e5-99a4-f2d7be272e48.png)

**Comment by sp614x** [comment]
Tested on Intel GPU. 
With SEUS 10.1 Ultra, the hand seems to render correctly. However SEUS is broken on Intel so this may be luck.
With other shader packs (Chocapic13, Kuda, MrMeepz, Sildurs), the hand is rendered correctly and it is not colliding with nearby blocks.
Needs test on NVidia.
Are other shader packs affected?

**Comment by rexcaptain501** [comment]
Tested again (H3 Ultra) with ASUS STRIX NVIDIA GeForce GTX 750 Ti.

Tested:
- (Internal Shaders)
- RudoPlays
- SEUS v10.1 Standard
- SEUS v10.1 Ultra DOF
- SEUS v10.1 Ultra Motion Blur
- SEUS v10.2 Ultra

All have the following symptoms - empty hand through blocks and players glitching along with items and blocks glitching too.

This is probably a NVIDIA GPU/GeForce Driver specific problem? AMD GPU's/Radeon Drivers needs testing. On that note, it might not be specific and affected on all GPU's (due to SEUS being broken on Intel of course).

**Comment by sp614x** [comment]
If the "(internal)" shaders are affected then it is not shader pack related.

**Comment by rexcaptain501** [comment]
(duh, me).

**Comment by sp614x** [comment]
Reproduced with NVidia, but it is probably not GPU specific.
To fix it set Video Settings -> Shaders -> Hand Depth -> 1x
Hand depth value 8x reproduces the problem, value 4x has minimal artifacts and 2x is safe.

**Comment by sp614x** [comment]
Hand depths 4x and 8x seem to be broken.
The hand depth is a setting for DoF shader packs and it configures the focus distance at which the handheld item should be sharp.
With 2x the handheld item is sharp when looking at an object at distance 2m. The values below 2x work identically at shorter distances.
With values 4x and 8x the handheld item does not get sharp when looking at objects at 4m and 8m. In fact it never gets sharp independant of the focus distance. Even when working correctly the 4x and 8x values would be very unrealistic, the handheld item will be blurred when focused on near objects and sharp when focused on far objects.

**Comment by rexcaptain501** [comment]
Ah, so that's what that setting does. I thought it had something to do with the realism of the hand, so to speak and I had it set to 8x.

0.5x, 1x, 2x and 4x were all safe for me, 8x was broken for me.

Would it be a good idea to create a mouse hover warning for Hand Depth?

**Comment by sp614x** [comment]
Hand depths 4x and 8x will probably be removed because they are problematic and not realistic.

**Comment by sp614x** [comment]
Hand depths 4x and 8x are removed in OptiFine 1.8.9_HD_U_H4_pre.
