### ISSUE TITLE
TE Pipes chunk border render

### ISSUE THREAD

**Issue by Fabboz** [sp614x/optifine#90]
I want to share that issue of cofh becouse optifine may be the problem.... i think...

[(https://github.com/CoFH/Feedback/issues/1101)]

**Comment by sp614x** [comment]
Is this still a problem with latest OptiFine D4_pre for 1.7.10: http://optifine.net/adloadx?f=preview_OptiFine_1.7.10_HD_U_D4_pre.jar
A similar bug was fixed recently, so it may be working now.

**Comment by Fabboz** [comment]
i had ereased the world where i found that bug. i hope someone else can do
that.

2016-04-24 0:15 GMT+02:00 sp614x <notifications@github.com>:

**Comment by sp614x** [comment]
Most probably fixed in D4_pre.
