### ISSUE TITLE
Rendering issue with Pneumaticraft elevator frames when run with OptiFine_1.7.10_HD_U_D6 and above

### ISSUE THREAD

**Issue by venarium** [sp614x/optifine#900]
Hi,

Per Minecraft forum discussion, ran into an issue running Optifine with Pneumaticraft. Issue has been reported to the Pneumaticraft mod author, but they appear to have not been active in some time, so I thought I'd trying reporting it here since it seems to have more to do with a recent Optifine update.

Pneumaticraft's elevator frames seem to render duplicates of themselves if 15 or more are stacked in a column. The duplicated frames render in place of other existing blocks above and one block away from the originals. This issue started with OptiFine_1.7.10_HD_U_D6 and occurs on any version of pneumaticraft paired with it. Not an issue on OptiFine_1.7.10_HD_U_D4 and below.

More info on the bug here: https://github.com/MineMaarten/PneumaticCraft/issues/890

Screencap:
![ekyypsd](https://user-images.githubusercontent.com/32106177/30618849-495c6c7a-9d6a-11e7-95a1-fa5a4d4a1b98.png)

While I could simply downgrade to Ultra D4, I would lose shaders and the ability to turn them off in game, a very useful feature the original GLSL shaders mod doesn't support.

Thanks again.

**Comment by sp614x** [comment]
Is this only happening when shaders are enabled or always?

**Comment by sp614x** [comment]
I can reproduce it with OptiFine D6 for 1.7.10 and PneumaticCraft_1.7.10_1.12.7-150.
And I have an idea what may be the problem.

**Comment by venarium** [comment]
It always happens, whether shaders are on or off. Figured it probably had do to with something in the D6 update. Thanks!

**Comment by sp614x** [comment]
Updated preview E4 for 1.7.10
- fixed ghost blocks in chunk cache
