### ISSUE TITLE
Rendering issue with Lookingglass(api used by Mystcraft/Securitycraft) dimension texture when run with 1.7.10 OptiFine shaders, any version.

### ISSUE THREAD

**Issue by venarium** [sp614x/optifine#901]
Hi again, 

Per Minecraft forum discussion, opening this for an issue running 1.7.10 Optifine shaders with Lookingglass (any versions). Issue has been reported to the Lookingglass author, but they appear to have reached an impasse, so I thought I'd try reporting it here since it seems to also have to do with Optifine shader rendering.

Lookingglass should grab a render of another dimension and display it on a Mystcraft book or Securitycraft monitor. The issue instead causes the screen to turn grey or blue and the render is shown on the bottom left corner of the screen instead of appearing where it should on the item GUI or monitor block which are no longer visible. The issue is specifically tied to shaders and does not occur when shaders are turned off. It is not related to any specific shader pack either; it will occur even with Internal shaders. It was an issue with the GLSL Shaders mod as well prior to Optifine, though it appeared differently (The render of the other dimension would simply fullscreen with GLSL shders mod). I was hoping the integration with optifine would fix it, but no luck. Issue occurs with all existing shader supported versions of 1.7.10 Optifine (7 & 8) as well as GLSL Shaders mod and all versions of Lookingglass.

More info here: https://github.com/XCompWiz/LookingGlass/issues/2

Screencap:

Shaders on:
![a5lwcnt](https://user-images.githubusercontent.com/32106177/30619101-8f6c9068-9d6b-11e7-916d-19c169b18403.png)

Shaders off:
![cnscvnn](https://user-images.githubusercontent.com/32106177/30619141-bccb6fa2-9d6b-11e7-99fc-6f3ccbba9efe.png)

Thanks again.

**Comment by sp614x** [comment]
Adding shaders to 1.7.10 is complex enough by itself. 
Adding a portal rendering API to another world on top of it is even more complex. 
Posted some ideas how this could be made to work in XCompWiz/LookingGlass#2.
