### ISSUE TITLE
Optifine not working on 1.12.2

### ISSUE THREAD

**Issue by xKnightGamingx** [sp614x/optifine#904]
According to some of my players that use Optfine, they say they are crashing cause of Optifine not being updated for 1.12.2. I don't have any type of screenshots to show this as It was reported to me.

**Comment by mcsnetworks** [comment]
Here's the stack trace:  https://gist.github.com/mcsnetworks/41f28b9ce72e8630f67a9fd57cbc7a91

**Comment by xKnightGamingx** [comment]
ok

**Comment by sp614x** [comment]
OptiFine for 1.12.1 is not going to work on Minecraft 1.12.2.
Generally OptiFine is only compatible with the exact MC version it was made for.
