### ISSUE TITLE
Optifine 1.12.x crashes mc when opening servers

### ISSUE THREAD

**Issue by iTecAI** [sp614x/optifine#905]
I don't know whether this is just my computer, or a bug, but whenever I try to load up a server with Optifine  for mc 1.12.x, it just crashes my game. Any ideas?
Thanks.

**Comment by Brottweiler** [comment]
What versions exactly? 1.12.x doesn't say much.

**Comment by sp614x** [comment]
OptiFine 1.12.1 will not work with Minecraft 1.12.2

**Comment by iTecAI** [comment]
OptiFine 1.12.1 HD U C5 and OptiFine 1.12.2 HD U C5

**Comment by iTecAI** [comment]
> OptiFine 1.12.1 will not work with Minecraft 1.12.2
I know, I have tried both with their respective versions

I will try some more tests, maybe with 1.12?
Thanks!

**Comment by Brottweiler** [comment]
What MC version? I can use optifine 1.12.2 with 1.12.2 just fine. Post crash log...

**Comment by iTecAI** [comment]
It doesn't put up any crash message, but at the beginning it says this:


```
Couldn't get hash for optifine/OptiFine/1.12.2_HD_U_C5/OptiFine-1.12.2_HD_U_C5.jar from https://libraries.minecraft.net/optifine/OptiFine/1.12.2_HD_U_C5/OptiFine-1.12.2_HD_U_C5.jar.sha1: HTTP 404: Not Found
--
06:32:33 | launcher | Have local file C:/Users\Matteo\AppData\Roaming\.minecraft\libraries\optifine/OptiFine/1.12.2_HD_U_C5/OptiFine-1.12.2_HD_U_C5.jar but don't know what size or hash it should be. Have to assume it's good.
06:32:33 | launcher | Checking installations.
06:32:33 | launcher | Minecraft client 1.12.2-OptiFine_HD_U_C5 requires 18446744073709518617 bytes to download.
06:32:33 | launcher | Starting!
06:32:33 | launcher | Using default game log configuration client-1.12.xml (outputs XML)
06:32:35 | LaunchWrapper | Loading tweak class name optifine.OptiFineTweaker
06:32:35 | LaunchWrapper | Using primary tweak class name optifine.OptiFineTweaker
06:32:35 | LaunchWrapper | Calling tweak class optifine.OptiFineTweaker
02:32:35 | game | OptiFineTweaker: acceptOptions OptiFineTweaker: injectIntoClassLoader OptiFine ClassTransformer OptiFine URL: file:/C:/Users/Matteo/AppData/Roaming/.minecraft/libraries/optifine/OptiFine/1.12.2_HD_U_C5/OptiFine-1.12.2_HD_U_C5.jar OptiFine ZIP file: C:\Users\Matteo\AppData\Roaming\.minecraft\libraries\optifine\OptiFine\1.12.2_HD_U_C5\OptiFine-1.12.2_HD_U_C5.jar OptiFineTweaker: getLaunchArguments OptiFineTweaker: getLaunchTarget   <log4j:Event logger="LaunchWrapper" timestamp="1506249155495" level="INFO" thread="main">     <log4j:Message><![CDATA[Launching wrapped minecraft {net.minecraft.client.main.Main}]]></log4j:Message>   </log4j:Event>
02:32:35 | monitor | expected <
```

**Comment by iTecAI** [comment]
Again, it could just be my computer, but I doubt it because I tried it on another one and the same thing happened

**Comment by sp614x** [comment]
Here is how to enable the error log with the new launcher:
http://hopper.minecraft.net/help/guides/minecraft-logs/

**Comment by iTecAI** [comment]
[PasteBin](http://paste.ubuntu.com/25622908/)

**Comment by iTecAI** [comment]
could be the Hash thing

**Comment by sp614x** [comment]
The log is OK, no mention of any errors.
If the game is crashing in Java, there should be a crash report with more details.
If there is no crash report the game is probably crashing in native code, most probably in the graphics drivers.
You could try to reset the video settings: "Video settings ->Other -> Reset" or to update the graphics drivers

**Comment by iTecAI** [comment]
Thanks! Resetting worked! Thanks for all your help!

**Comment by Leppan** [comment]
The same thing is happening to me. C7, tried resetting.
