### ISSUE TITLE
My Optifine cape!!!

### ISSUE THREAD

**Issue by Trixeri** [sp614x/optifine#910]
I bought an Optifine cape yesterday, and I haven't been able to see it even once! If I buy a product shouldn't I be able to review it or something? This isn't an issue I have to be worrying myself over, but I payed 10 euros for it so this annoys me. Please give me instructions to enable it or please fix it as soon as possible if it's a problem on your end. Thank you. 

P.S: I've already installed OptiFine 1.12.1 HD U C5.

**Comment by sp614x** [comment]
The cape for Trixeri is active: http://s.optifine.net/capes/Trixeri.png
Please check that:
- the username is correctly spelled, upper/lowercase matters
- OptiFine is correctly installed (installation instructions)
- the option Video Settings -> Details -> Show Capes is ON
- the option Multiplayer Settings -> Show Cape is ON
- no firewall or router is blocking OptiFine from accessing the OptiFine server where the cape is located
- the cape is visible in single-player worlds. Some servers may modify the player name by adding tags or truncating it, which changes the player identity and the cape may not be displayed.

**Comment by Trixeri** [comment]
Thank you. I mainly play on Hypixel but sometimes, when I load Optifine on Forge 1.12.1, it works, then on other times it doesn't. Could you please explain that to me? Thank you in advance.

**Comment by sp614x** [comment]
OptiFine loads the cape from http://optifine.net/capes/Trixeri.png
The network may not be reliable (firewalls, antivirus, etc) and sometimes loading the cape may fail. Some other Forge mods may be overwriting OptiFine classes and cause the cape not to be visible.
In any case the cape is visible to all other players using OptiFine even if you can't see it.

**Comment by Trixeri** [comment]
Hi! I would like to thank you for giving me the most likely problems to this situation. I found out that my firewall was blocking a couple of features of Minecraft. So I set it to ignore Minecraft in total. The cape now works (almost) every time I log on. Thank you very much for your assistance! <3. Have a wonderful day!
