### ISSUE TITLE
[1.7.10]MultiCore Chunk loading cause Chisel Block disappear

### ISSUE THREAD

**Issue by TataTawa** [sp614x/optifine#916]
<img src="https://cloud.githubusercontent.com/assets/21981691/18229545/5397586a-72a7-11e6-8bfd-b445eb1b1c3b.png">

It's an old problem. Optifine and Chisel are great mods. but they conflicts in multicore chunk loading.
[1.7.10]  I use Optifine HD U D6 and chisel 2.9.5
If the author of Optifine are interested to fix this conflist , I am willing help to code my branch of Chisel compatible with Optifine.

**Comment by sp614x** [comment]
The Multi-Core Chunk Loading in 1.7.10 is not compatible with some mods and it can't be fixed.
You can use Default or Smooth Chunk Loading instead.
