### ISSUE TITLE
CEM prevents mods from registering Renderers for that entity

### ISSUE THREAD

**Issue by F43nd1r** [sp614x/optifine#918]
### Scenario
 - I am using Quark (a mod which loads different textures for chicks in contrast to chickens, see https://github.com/Vazkii/Quark/blob/master/src/main/java/vazkii/quark/client/render/random/RenderChickenRandom.java)
 - I am using PureBDCraft, which contains a CEM for chickens

### Result
The CEM Renderer overrides the Quark renderer 

### Expected Result
The CEM Renderer works on top of the quark renderer

### Relevant code
`ModelAdapterChicken.makeEntityRenderer()` creates a `new RenderChicken()`.
It would be great if it could use the custom (quark or other mod) renderer registered in the `RenderManager` instead.

**Comment by sp614x** [comment]
Quark modifies the getEntityTexture() to return random texture.
CEM changes the whole model so it is not using getEntityTexture() anymore.
Can't be fixed without disabling CEM when quark is installed.
