### ISSUE TITLE
Custom profile names

### ISSUE THREAD

**Issue by robobo1221** [sp614x/optifine#925]
Hey so I'm trying to setup different type of camera profiles. But I only can use one profile wich is called "profile". Is there a way to create multiple profile names?

Something like this:

`profile.PROFILENAME.NAME`

So you are not restricted to just one type of profile

**Comment by sp614x** [comment]
What is a camera profile? 
Shaders option profile maybe?

**Comment by robobo1221** [comment]
Like i'm trying to setup a profile list for different types of camera types in continuum. But im only restricted to one profile list wich we are going to use for presets like low, medium, high, etc. Like I said, is there a way to get multiple profile lists?

**Comment by sp614x** [comment]
A camera type can be selected with a normal option:
```
#define CAMERA_TYPE DSLR // Camera type [DSLR COMPACT SUPERZOOM]
```
