### ISSUE TITLE
Change render layer per block (translucency)

### ISSUE THREAD

**Issue by sp614x** [sp614x/optifine#927]
The first step would be to allow changing CUTOUT blocks to TRANSLUCENT.
This would not need any other changes except the render layer.

![image](https://user-images.githubusercontent.com/16635441/31167468-731dcbec-a8f2-11e7-964e-e44d56942e33.png)

The next step would be to allow changing SOLID blocks to CUTOUT/TRANSLUCENT. 
This would also need  changing:
- `isOpaqueCube()` to fix culling
- `getLightOpacity()` to fix lighting around the block. 

Changing the lighting may need the chunk to be relit to fix black spots. 

This should probably be limited to decorative blocks (not naturally generated) to avoid massive performance problems and possible cheating.

**Comment by sp614x** [comment]
Updated preview C8 for 1.12.2
 - added custom block render layers
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/block.properties

**Comment by theDaleighChronicle** [comment]
I do have a question on this. How do we utilize this file to, per say, add transparency to normal Minecraft glass?

**Comment by sp614x** [comment]
You can configure the glass block (glass pane) to be rendered on the translucent layer. Then it could use a translucent (semi-transparent) texture and it would be rendered correctly.

**Comment by theDaleighChronicle** [comment]
Oh, so I would add the block ID of glass to the translucent section in the properties file, and it will render as semi-transparent?

**Comment by sp614x** [comment]
Yes.

**Comment by theDaleighChronicle** [comment]
Awesome, thank you so much!
