### ISSUE TITLE
Wrong Update Log

### ISSUE THREAD

**Issue by HeartyYF** [sp614x/optifine#93]
![wul](https://cloud.githubusercontent.com/assets/17660052/14875969/c872be1a-0d42-11e6-9b38-88421d6e982f.png)

**Comment by sp614x** [comment]
The block shading with Forge is fixed in 1.9.2.
OptiFine for 1.9.2 is almost identical to OptiFine for 1.9 and the fixed block shading will work properly when Forge is updated to 1.9.2 or later 1.9.x versions.

**Comment by HeartyYF** [comment]
But after all,Forge isn't updated to 1.9.2...

**Comment by sp614x** [comment]
The bugfix was ported from OptiFine 1.9 to 1.9.2 together with many other Forge bugfixes. 
It will become relevant when Forge updates to 1.9.2.
