### ISSUE TITLE
CIT not working - it's not about lowercase :/

### ISSUE THREAD

**Issue by babbajagga** [sp614x/optifine#930]
Hi,
I am running out of ideas, actually, I did already run out of them.
No matter what I try, the CIT item texures are not freaking working for me.

I double-checked the texture extension to be .png,
I double-checked the lowercase of files, hell I even lowercased the pack title.
I deca-checked the .properties files
I deca-checked the path and everything else I can think off

still the freaking CITs are not working at all.

I tried the damage value
I tried the nbt tag .Name

I followed 2-3 video guides on YT to recreate the CIT, with no success.

I downloaded a working CIT template pack, tested it, it working fine.
As soon I have edited only the texture and renamed the .properties file IT FREAKING STOPPED TO WORK.

I have no idea WTH is this absurdity :'-(

I am using Paint.NET for making my resourcepack, and it works all fine, but not CIT.
I have tried GIMP... uther bs. I cannot get used to it, overcomplicated, antiintuitive. boah... duh... no way, thanks, never. Same goes for PS.

Maybe it has nothing to do with Optifine at all, but I don't have a clue where to turn.

I am adding the CIT pack link below so you can check it yourself.
[WTF-CIT.zip](https://github.com/sp614x/optifine/files/1357208/WTF-CIT.zip)

I have tried this in MC 1.12.1 with OF HD_U_C5

**Comment by sp614x** [comment]
Did you read the error log (game output)?
This is the place where all errors are shown.

**Comment by sp614x** [comment]
Options -> Video Settings -> Quality -> Custom Items -> ON ?

**Comment by sp614x** [comment]
If you remove the line `damage=1` it will start working

![image](https://user-images.githubusercontent.com/16635441/31201635-aa72fece-a95f-11e7-89b3-2afd929091c5.png)

**Comment by babbajagga** [comment]
alright, things getting even more strange...
I have sent the pack over to a friend, and... dang it works for him...
hmmm...

any idea what might be the issue? but I guess it's not a proper place to ask this here.

**Comment by sp614x** [comment]
Can you post the error log (game output)?
http://hopper.minecraft.net/help/guides/minecraft-logs/

**Comment by babbajagga** [comment]
O_o Don't ask me how, but it works now...
I did nothing since the last post, except switching MC versions with OF in the MC Launcher menu, maybe I had a wrong OF version for MC version I ran, it's the only thing that I can think off.
Thanks for the interest m8, I really appreciate such approach nowadays.
I will report back if this issue ever again occurs, with a report log pasted.
