### ISSUE TITLE
Forge 1.10.2 build 2488

### ISSUE THREAD

**Issue by KrauzeBartek** [sp614x/optifine#932]
Can you update optifine to forge version 2488 ?

**Comment by sp614x** [comment]
OptiFine 1.10.2_HD_U_E3 is compatible with Forge #2316.
According to the changleog the next 3 versions are small bugfixes, so it should be compatible (as not crashing) with #2488.
Official support for #2488 will be added on next 1.10.2 update.

**Comment by KrauzeBartek** [comment]
How long we must wait for next update ?

**Comment by sp614x** [comment]
It should be updated with the next round of backporting to older versions. No fixed date for now.
Is there any incompatibility between OptiFine 1.10.2_HD_U_E3 and Forge #2488.
