### ISSUE TITLE
My Cape is not showing.

### ISSUE THREAD

**Issue by YayL** [sp614x/optifine#933]
I've bought an Optfine Cape but my cape is not showing. I have proof I bought the cape but I won't show it's really annoying I've tired everything is there anything I can do to make it work... PS: I have Os x Sierra on a Mac.

**Comment by sp614x** [comment]
Please check that:
- the username is correctly spelled, upper/lowercase matters
- OptiFine is correctly installed (installation instructions)
- the option Video Settings -> Details -> Show Capes is ON
- the option Multiplayer Settings -> Show Cape is ON
- no firewall or router is blocking OptiFine from accessing the OptiFine server where the cape is located
- the cape is visible in single-player worlds. Some servers may modify the player name by adding tags or truncating it, which changes the player identity and the cape may not be displayed.

For which username was the cape activated?

**Comment by YayL** [comment]
I activated it for the name YayL just like my Minecraft name and I can't see the cape in Single Player either...

**Comment by YayL** [comment]
I just saw something. Everytime I restart Optfine the Show Capes button turns from On to Off and it's doing this every time I restart Optfine or LabyMod with Optifine in it.

**Comment by sp614x** [comment]
LabyMod is probably not compatible with OptiFine, it overwrites some OptiFine classes to add its own capes.

**Comment by sp614x** [comment]
Make sure that the game can write to `optionsof.txt` in the MC folder. 
The Show Capes option is saved as `ofShowCapes:true`.

**Comment by ap125** [comment]
This was created for a long time, if you are still online you can answer one question, what if there is no line ofShowCapes:true in the optionsof.txt, what should I do then?

**Comment by Ari-RERA-43** [comment]
> This was created for a long time, if you are still online you can answer one question, what if there is no line ofShowCapes:true in the optionsof.txt, what should I do then?

This is a very old issue and there are other things that can cause your cape not to show. Get support in https://discord.gg/optifine.
