### ISSUE TITLE
Placing an Chisel & Bits Block next to an ArchitectureCraft causes the Client to crash when optifine is installed

### ISSUE THREAD

**Issue by D3nnis3n** [sp614x/optifine#934]
See here: https://github.com/AlgorithmX2/Chisels-and-Bits/issues/313#issuecomment-334959271

**Comment by sp614x** [comment]
This is the code at the crash site:
```
    // Get facing
    EnumFacing facing = getFacing(side);
    // Try with face quads
    List quads = model.getQuads(neighbourState, facing, 0);
    if(quads.size() > 0)               // <------- CRASH here with NullPointerException
    {
      // The quad
      BakedQuad quad = (BakedQuad) quads.get(0);
      // The icon
      return quad.getSprite();
    }

```
Looks like the ArchitectureCraft block model returns null from getQuads(state, facing, 0) instead of a list.
This method should **always** return a non-null value (empty list) as it is used without a null check everywhere in the vanilla and forge code.

**Comment by sp614x** [comment]
This is the code at the crash site:
```
    // Get facing
    EnumFacing facing = getFacing(side);
    // Try with face quads
    List quads = model.getQuads(neighbourState, facing, 0);
    if(quads.size() > 0)               // <------- CRASH here with NullPointerException
    {
      // The quad
      BakedQuad quad = (BakedQuad) quads.get(0);
      // The icon
      return quad.getSprite();
    }

```
Looks like the ArchitectureCraft block model returns null from getQuads(state, facing, 0) instead of a list.
This method should **always** return a non-null value (empty list) as it is used without a null check everywhere in the vanilla and forge code.
