### ISSUE TITLE
Optifine Ultra C6 causes crashes with WorldEdit

### ISSUE THREAD

**Issue by MaygeKyatt** [sp614x/optifine#935]
Minecraft 1.12.1
If Optifine C6 is installed, then any blocks placed with worldedit (whether by using //paste, /up, or anything else) will mostly not be placed (from limited testing, I think only 1 block gets placed) and the game will immediately crash if the player comes into contact with (or tries to interact in any way with) the block that is placed. I do have WorldEditCUI installed as well, which could conceivably be part of the problem, but I find that unlikely as WorldEditCUI only interacts with selections in WorldEdit and this bug has nothing to do with selections, only block placement.

**Comment by sp614x** [comment]
Can you post the crash report, game output or the error log?
