### ISSUE TITLE
Optifine installation corrupts launcher profiles' names

### ISSUE THREAD

**Issue by violine1101** [sp614x/optifine#938]
It looks like the Optifine installer does not use the correct encoding for the `launcher_profiles.json` file, so special characters appear as question marks after the Optifine installation has completed.

I actually don't have this issue myself, but I wanted to forward this to the correct place. Here is the ticket on Mojang's bug tracker: [MCL-8254](https://bugs.mojang.com/browse/MCL-8254)

**Comment by sp614x** [comment]
Updated preview C7 for 1.12.2
- fixed installer to use UTF8 encoding for JSONs

**Comment by sp614x** [comment]
Older versions will be fixed when they are updated.
