### ISSUE TITLE
Audio problems with HD_U_C5 and HD_U_C6

### ISSUE THREAD

**Issue by kedvenced** [sp614x/optifine#939]
I have to start the game several times again and again, because most of time I can not get no audio signal. No music or any sound. Game is mute like a fish. 
I use external audio card (Behringer XENYX 302 USB) or the built in sound card via HDMI in some cases.  

Is anybody here experienced like this? It is annoying. 

1.12.2 sounds at every startup but optifine provide sounds rarely.

**Comment by xCuri0** [comment]
I sometimes have this issue when using Windows but not Linux. Other people on the server also report the same issue.

**Comment by kedvenced** [comment]
I only use Windows. Win 10.

**Comment by Zefferis** [comment]
I've had the same issue with C6, Windows.

Music and sounds play in the menu but upon entering the game theres long pauses between music playing or sounds.

**Comment by kedvenced** [comment]
Haha, maybe I fix this by changing the USB port. I put my audio device to another slot, and (magic!) this issue disappeared! only one of ten starting has any audio problem. 
Thank you for your comments!

**Comment by xCuri0** [comment]
I'm using my laptop's internal speakers and I have this problem too.
