### ISSUE TITLE
CTM Quartz pillar broken in OptiFine 1.9.2 HD U B2

### ISSUE THREAD

**Issue by eccentricdevotion** [sp614x/optifine#94]
In OptiFine 1.9.2 HD U B1 the TARDIS Police Box sign texture works fine

![quartzpillarb1](https://cloud.githubusercontent.com/assets/1841924/14906725/03acde22-0e13-11e6-875c-4a69a740a163.jpg)

In OptiFine 1.9.2 HD U B2 the texture does not display at all

![quartzpillarb2](https://cloud.githubusercontent.com/assets/1841924/14906731/14bb95e6-0e13-11e6-9ceb-d19609f14220.jpg)

Textures and property files if it helps

[TARDIS_sign_textures.zip](https://github.com/sp614x/optifine/files/241695/TARDIS_sign_textures.zip)

**Comment by sp614x** [comment]
The properties use "metadata=3,4" which are rotated pillars (X and Z).
CTM for pillars (logs, quartz, etc) currently removes the rotation metadata (quartz 3 and 4 => 2) and automatically corrects the faces for rotated blocks. It is enough to define CTM for the standard pillar (Y) and it will be correctly applied to the rotated variants. Currently it is not possible to specifically target the rotated variants.

**Comment by sp614x** [comment]
I could add a flag "autoRotate=true|false" which can be used to turn off the automatic rotation and then the metadatas 3 and 4 should work.

**Comment by eccentricdevotion** [comment]
Removing the metadata property does the trick nicely, thank you.

![police_box_sign_ofb2](https://cloud.githubusercontent.com/assets/1841924/14912343/9b90d0cc-0e4f-11e6-8a96-5ad10280a5d8.jpg)

**Comment by sp614x** [comment]
Added fix in 1.9 preview B3 to keep the rotated metadata when the properties specify rotated metadata. It will be ported to 1.9.2 later.
