### ISSUE TITLE
Cannot set render distance to 1 unlike normal non-optifine minecraft.

### ISSUE THREAD

**Issue by GlitchHead** [sp614x/optifine#941]
Hey I have been running minecraft 1.12.2 recently on the raspberry pi 3 based off of this tutorial:
https://www.raspberrypi.org/forums/viewtopic.php?t=186547

After using optifine on the raspberry pi 3 I saw massive performance boosts which was very nice... The only issue was that I could not set the render distance to 1 unlike the normal non-optifine minecraft 1.12.2. I could normally just set the options.txt file to 1 chunks for render distance and it would help minecraft run very well on the raspberry pi 3. But when I edit the options.txt and optionsof.txt files to 1 render distance it refuses to use 1 render distance and just uses 2. I have absolutely tried everything I could think of and it just does not work. Could you potentially add support for 1 render distance in optifine? It probably wont be hard to implement considering its already supported in normal non-optifine minecraft. It would also help people with really old computers run at even better performances.

**Comment by GlitchHead** [comment]
Hey i just realized that on non-optifine minecraft entities do not render at 1 render distance in singleplayer but in multiplayer everything works flawlessly.

**Comment by sp614x** [comment]
If you delete "optionsof.txt" and edit "options.txt" to use "renderDistance:1" then it should work.
Make sure to use latest preview C7 for 1.12.2.

**Comment by GlitchHead** [comment]
It works well in multiplayer some parts of the map wont render unless I go inside of them. This does not happen in non-Optifine 1.12.2 I have been messing with Optifines options trying to fix the issue and I can't seem to fix it.
