### ISSUE TITLE
Error in your custom_guis

### ISSUE THREAD

**Issue by MisterQuiggly** [sp614x/optifine#942]
Testing out the new custom GUI, having trouble with it.
Here is what I have:

> container=villager
> texture=fisherman.png
> professions=farmer:fisherman

my texture is in the same folder as my properties file, which is called fisherman.properties, and my texture is called fisherman.png

All of this located in 
\assets\minecraft\optifine\gui\container

EDIT: Figured out my issue, which leads to another issue on your end, sp614x.

> Example:
> Professions farmer (all careers) or blacksmith (all careers)
> professions=farmer blacksmith
> Careers fisherman, shepherd or nitwit
> profession=farmer:fisherman,shepherd nitwit:nitwit
> 
> Professions and careers can also be given by their numeric ID values.
> See https://minecraft.gamepedia.com/Villager#Professions_and_careers
> professions=<professions>

In one place you have: 
professions=

In another place you have:
profession=

the correct one is profession=

**Comment by sp614x** [comment]
The correct key is `professions` as given here: 
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/custom_guis.properties#L154

Fixed the examples in the comments to use `professions`.
