### ISSUE TITLE
Option to change shadow format

### ISSUE THREAD

**Issue by dotModded** [sp614x/optifine#944]
I would like to see options to change formats and filtering types of shadow buffers; shadow, watershadow, shadowtex0, and shadowtex1. Also exposing the depth shader for shadows would be extremely useful.

Adding an option to change the shadow and shadow depth(s) format to R32_UINT and R32G32_UINT are better for methods like VSM and ESM, also being able to select the filtering type of the buffers would be a nice addition.

Another feature I think a lot of shader devs would like as well, having the shadow depth shader exposed to the shaderpack, being able to write custom depth values is very useful for shadow mapping and being able to write other things to it could be used for a lot of features as well.

**Comment by DethRaid** [comment]
The depth shader is available. It's called `shadow`

**Comment by DethRaid** [comment]
You know how waving leaves can cast shadows? Bam custom shadow depth shader

**Comment by DethRaid** [comment]
You can change filtering from point to bilinear to hardware pcf. What more do you want?

**Comment by dotModded** [comment]
We can't write to the shadow, or shadowtex's on a per fragment basis unless we can?

**Comment by DethRaid** [comment]
Yes you can. Just change gl_FragDepth (iirc)

**Comment by dotModded** [comment]
Disregard the writing depth feature, writing to gl_FragDepth works. Just being able to change format and filtering would be great!

**Comment by sp614x** [comment]
The shadow depth buffers currently use the general format `GL_DEPTH_COMPONENT`.
It could be changed to `GL_DEPTH_COMPONENT16/24/32`, where /32 is probably not widely supported.

https://www.khronos.org/registry/OpenGL-Refpages/gl2.1/xhtml/glTexImage2D.xml
https://gamedev.stackexchange.com/questions/111955/gl-depth-component-vs-gl-depth-component32
https://www.gamedev.net/forums/topic/297369-gl_depth_component/

**Comment by sp614x** [comment]
Added configurable color buffer format:
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.txt#L492
