### ISSUE TITLE
MrCrayfish Furniture/Optifine texture issues

### ISSUE THREAD

**Issue by chevrelune** [sp614x/optifine#946]
The oven and washing machine's front texture is solid white instead of transparent. After uninstalling Optifine, the texture was fixed

MC version: 1.10.2
Optifine version: 1.10.2 HD U E3
CFM version: 4.1.2

**Comment by xCuri0** [comment]
Maybe try OptiFine and CFM with forge because they could be interfering

**Comment by chevrelune** [comment]
tried it, did not work

**Comment by InuYasha86000** [comment]
I would like to note that with some shaderpacks enabled the TV at minimum gets treated as water and ends up with a water effect in the screen (this is in 1.7.10 though as I have not tested it in newer versions).

**Comment by KaiAF** [comment]
Is this still an issue?
