### ISSUE TITLE
Problems with villager custom GUI

### ISSUE THREAD

**Issue by MisterQuiggly** [sp614x/optifine#947]
what I have:

> container=villager
> texture=fisherman.png
> profession=farmer:fisherman

This is what I gathered from your text document on Custom GUIs; that for villager professions, to specify a specific thing I would list the profession then the career:

> farmer:fisherman

I've tried just putting fisherman, I still have the problem.

Now for the problem itself. 
This does not just apply to fisherman, rather every farmer villager no matter if it is Fletcher, fisherman, farmer, etc.

**Comment by okl1001** [comment]
I have the exact same issue.

**Comment by sp614x** [comment]
Change `profession` to `professions`, as defined in the specification: 
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/custom_guis.properties#L154
