### ISSUE TITLE
Font

### ISSUE THREAD

**Issue by ThijsSlop** [sp614x/optifine#95]
Hi, when I enable my 64x64 resourcepack and OptiFine, bold fonts are no longer bold. It's really irritating me and many other users.
Screenshots:

(without optifine, how it supposed to be)
![without optifine](https://cloud.githubusercontent.com/assets/17639076/14938576/78f21934-0f28-11e6-8b76-a5e8451c7106.png)

(with optifine)
![with optifine](https://cloud.githubusercontent.com/assets/17639076/14938577/7c245c0c-0f28-11e6-88da-9f57217a36f4.png)

I already tried toggling the custom font option, but that did not work.

I hope you can fix it.

**Comment by sp614x** [comment]
The bold HD fonts with OptiFine are less bold than vanilla in order to avoid the ghost effect.
Vanilla 64x font: http://imgur.com/nYSYzeb.png
OptiFine 64x font: http://imgur.com/TTdVPbn.png

**Comment by sp614x** [comment]
Added option "offsetBold" in font properties (preview B3).
For the default font add in "/assets/minecraft/textures/font/ascii.properties" the line "offsetBold=1.0".
The default bold offset is 1.0 for 16x and 0.5 for 32x and higher resolutions.
