### ISSUE TITLE
Can you add Vietnamese?

### ISSUE THREAD

**Issue by phjtieudoc** [sp614x/optifine#950]
Hello, sp614x. I'm phjtieudoc, this is the first time I use github. Can you add Vietnamese, I can help you translate optifine into Vietnamese.

**Comment by sp614x** [comment]
You can create the vietnamese language file here: https://github.com/sp614x/optifine/tree/master/OptiFineDoc/assets/minecraft/optifine/lang
and it will be added in the next versions.

**Comment by sp614x** [comment]
The vietnamese file name is probably "vi_vn.lang"
