### ISSUE TITLE
[1.7.10][Suggestion]Using GL15 Vertex Buffer Object In Tessellator Class

### ISSUE THREAD

**Issue by TataTawa** [sp614x/optifine#951]
I think using VBO might be a great help for FPS, especially for advanced graphics cards.Is it right for Minecraft?(and possibly VAO?)
The Ancient GL11 methods is older than me though..

**Comment by sp614x** [comment]
VBOs are available in Minecraft since 1.8. 
They increase the FPS about 10-15%.
Backporting VBOs to 1.7.x is too complex to be realistic.
VAOs can't help with the FPS, as it is limited by other factors.
