### ISSUE TITLE
An unexpected bug.... HELP.

### ISSUE THREAD

**Issue by SuperNinjaPedro1** [sp614x/optifine#954]
I ran across this bug while playing hypixel with Optifine_1.12.2_HD_U_C6. It surprised me, but i was able to fix it by re downloading optifine. But it would be nice if it was fixed. Here's a picture. Thanks! :)

![optifine 1 12 2 c6 bug](https://user-images.githubusercontent.com/32976499/31849346-4f337bc4-b684-11e7-81c0-0320015d5929.png)

**Comment by sp614x** [comment]
This may be caused by custom Fullscreen Mode.
Some graphics drivers may have problems with it.
