### ISSUE TITLE
Custom GUI not working if placed by command

### ISSUE THREAD

**Issue by UserAnimated** [sp614x/optifine#955]
If you place a Dropper down manually with a custom name of "Test Dropper" it will work and have the custom GUI, but if you use command blocks and use a command /setblock ~ ~ ~ minecraft:dropper 1 replace {CustomName:"Test Dropper"} it does not have the custom GUI

**Comment by sp614x** [comment]
Updated preview C7 for 1.12.2
-  - fixed Custom GUIs check by name

**Comment by UserAnimated** [comment]
Thank you so much
