### ISSUE TITLE
[SUGGESTIONS] Big suggestion post for optifine.

### ISSUE THREAD

**Issue by HRudyPlayZ** [sp614x/optifine#957]
This is a big suggestion post for @sp614x. Feel free to add your ideas in the comments.
Let's get started.
Some suggestions could have been already suggested or added to the game.

# I - Compatibility between Custom Entity Models & Random Mobs

Let me explain, in optifine you cannot actually change randomly a model or change it depending on biome, height. So i thought of adding for example a line in random mobs like
`type.<n>=texture` or `type.<n>=model`. 

- if the texture type is selected, the skins tag will be used. But if the model type is selected instead, a new tag called models will be used to refers to the model file.
(The models tag will be searching the model in subfolders in assets/minecraft/optifine/cem; ex:
assets/minecraft/optifine/cem/creeper/1.jem)

Example:

(Taken & edited from the mob.properties example.)
type.1=texture
skins.1=10-14
weights.1=10 10 10 3 10
heights.1=0-55

or

type.1=model
models.1=Creeper/10-14.jem
weights.1=10 10 10 3 10
heights.1=0-55

# II - More tags for CEM & RandomMobs

In optifine you can already change texture/models depending on biome, height & chances. But you cannot change them depending on tags like name, nbt...
I would like to see this tags added to optifine's CEM & RANDOMMOBS:

- `entity.name=<name>` Changes the model/texture depending on entity's name.
- `entity.nbt={NBT}` Changes the model/texture depending on entity's datatags.
- `env.time=<Time in ticks>` Changes the model/texture depending on the time of the day of Minecraft.
- `env.weather=clear|rain|storm` Changes the model/texture depending on the weather in Minecraft.
- `dimension=overworld|nether|end` Changes the model/texture depending on the entity's dimension.

# III - More types for Custom Item Textures

We need to have new types for CIT:

- `horsearmor` to change the texture of an armor on a horse.
- `blockitem` to change the model/texture of a block in inventory.

# IV - Custom Sky depending on biome

We could have a new tag (`biome=<biome>`) in the sky.properties to change the texture of the sky for a specific biome.

# V - Custom sounds for items/entities

In vanilla minecraft we can't change a sound depending of the source's name (for exemple when a bow is named "My Bow").
In optifine, we should have an addon to existing features that could do that:

We could add to our files a line like:
`sound.forthis.<original sound name>=<new sound path>`

(from CIT)
type=item
items=<list of item IDs>
nbt.display.Name=My Bow
sound.forthis.entity.arrow.shoot=./flame.ogg

# VI - Loading screen background different for each dimension

We could have a folder in our resourcepack like
optifine/loading and files inside like:

- DIM0.png
- DIM1.png
- DIM-1.png
- ...

# VII - Custom projectiles with Custom Item Textures

In optifine, for now, we can't change the texture of the launched projectile,
we could have a tag like this:

`projectile=<path>`

Example:

(from CIT)
type=item
items=<list of item IDs>
nbt.display.Name=My Bow
projectile=./flamearrow.png

# VIII - Interpolate Animations

Actually, we can't interpolate animations.

We could have something like that:
from=
to=
x=
y=
w=
h=
interpolate=true/false (default false if interpolate wasn't added by owner)>
[SUGGESTED BY @MisterQuiggly]

# IX - Separating particles for colors
Actually, we can't change independently colors for particles of the nether portal or the enderman's particles.

We could have new particles:
particle.portal
particle.enderman
particle.endermite
particle.pearl
particle.endereye
particle.enderchest
particle.dragonegg
particle.gateway
[SUGGESTED BY @realjackasterisk]

# X - Connected Models

Actually we can't can't connect models together,
We could have a new tag for CTM:

`type=model|texture`
If the model type is selected, the tiles tag will search for json models but if the texture type is selected,
the tiles tag will works as usual.

### Thank you for reading everything.

**Comment by sp614x** [comment]
The Custom Sky per biome is already on the list: https://github.com/sp614x/optifine/issues/892

Dynamic entity models (CEM, mobs, etc) are currently not possible: 
https://github.com/sp614x/optifine/issues/377
https://github.com/sp614x/optifine/issues/937

Currently sounds can't be customized by source name (custom bow). They could only be customized by type and position (biome, height, arow hitting stone/dirt/water). This is a technical limitation.

Custom loading screen backgrounds are on the list: https://github.com/sp614x/optifine/issues/850

Custom arrow texture depending on owner properties could be added. It will depend on the current equiped item (bow). Switching the bow will reset the texture in-flight.

Interpolation for custom animations is on the list: https://github.com/sp614x/optifine/issues/878
The main problem is that interpolations are very resource intensive.

Separate particle colors are on the list: https://github.com/sp614x/optifine/issues/881

Connected Models are not existing because they have some problems:
- connected models are only interesting for non-cube models. Connecting cube models works with CTM.
- many non-cube blocks are already connected (glass panes, walls, fences, rails, redstone) or are dynamic (doors, fences, pistons).
- converting a cube block to use non-cube model is problematic. Face culling and light propagation changes. Light is a gameplay factor (mob spawning) and it should not be changed by resource packs. This alse requires chunks to be relit, which is very slow and complicated process.
At the end there are very little blocks that would benefit from connected models.

**Comment by HRudy94** [comment]
@sp614x Hey, i have some questions for you:

- Can i use connected textures with custom block models (ex: I have a sea lantern with a custom models made with json [just cubes] & i want to use CTM)
- Can i use Random Mobs texture with a custom entity model? (Just texture, like changing the texture on the model when the mob is in certain biomes...)
- Why Dynamic Models aren't possible?
- Is there a way to change jukebox's texture depending on if he plays a disk or not?

Thank you for answering!

**Comment by sp614x** [comment]
- CTM can work with all block models, results may vary
- Random Mobs will probably not work with CEM
- What Dynamic Models?
- The Jukebox is a block so its texture can't be changed on the fly. The chunk will have to be reloaded and it will have to use another block model (or something similar)

**Comment by HRudy94** [comment]
@sp614x 

- How can i use the block models with CTM?
- I saw a resource pack where villagers have human models (made with optifine CEM) & you can change the villager's texture when you rename it.
- Dynamic Entity Models. In fact, if it's compatible with RandomMobs, you can change the model by using transparent textures.
- The Jukebox has a different datavalue when a disk plays so it's possible.

**Comment by sp614x** [comment]
- CTM works identically with vanilla models and models from resource packs
- Random Mobs could selecte texture per name if the texture is loaded from "assets/minecraft/textures/entity"
- CEM depending on entity properties is not possible yet
- Different datavalue can be checked with CTM

**Comment by SkaliberWasTaken** [comment]
I've been looking into ways of changing mob skins with accompanying datapacks, but currently the best way is to change the mobs name, which is obviously not ideal because it can be changed by the player at any time.
`entity.nbt={NBT}
`
Is there any reason why this isn't already in OptiFine, or could we have it, if not? (:

**Comment by Azagwen** [comment]
About CTM, is there any equivalent of it for Block models ? like a CMM (Connected Model Mod)
Like for example in the same way fences change models when they are placed next to each others.

**Comment by HRudy94** [comment]
@SkaliberWasTaken It would be cool. For now, you could theorically put a custom tag on the mob in question and then just change it's name with the /entitydata (or equivalent, i don't remember how it's done in 1.13+)

@Azagwen I think they are. You could make blockstates to allow for vanilla Connected Models.
Random models can also be done in blockstates. If you want to use CTM for some of it's option (biome...), you can always make a texture with transparent part and map the texture to your model correctly.

**Comment by SkaliberWasTaken** [comment]
The reason why i asked for this specific integration, is because the player can very easily change the name of any mob they like with a nametag.

**Comment by HRudy94** [comment]
> The reason why i asked for this specific integration, is because the player can very easily change the name of any mob they like with a nametag.

Yes i know, but try using the hidden tags (if i recall correctly on 1.12.2, you can set an NBT like {Tags:"Something that players can't change"} and then use the entity with @e[tag=...]). Players can't change those tags so you can just do a /entitydata (again 1.12, i will need to look at 1.13+ syntax) to set the name back...

Keep in mind that if players try to rename the entity, they will just lose a name tag though.

**Comment by SkaliberWasTaken** [comment]
Wait, so can you do random entity skins based on NBT already!?

I know exactly how to use tags, and a number of other features, but i was under the impression that you can only change entity skins based off of names, biomes, heights (and now age, moon cycle, time of day, etc)

**Comment by SuperTux20** [comment]
What if you have a single custom model, but want to use multiple random textures on it? I don't know if that's possible, but if it is I can't figure out how. I've had random textures for different colored chickens, and I just made a model to add a comb on the chicken's head but now the random textures don't work, just the one I have in the cem folder. If I remove that, there's just a blank white texture instead.

**Comment by tobyplowy** [comment]
@sp614x This looks like a suggestion tread? I have a suggestion (Hope I'm in the right place for this) 
I would like to see biome specific block models be possible.
It does not seem possible yet but it would be very beneficial to have =D
Thanks for all the amazing work so far guys. You have done gods work!!!

**Comment by KaiAF** [comment]
Closing this as it seems like most of the suggestions were added. If you want to make new suggestions, I think it would be best to create a new issue.

**Comment by NXEJQJ** [comment]
every feature can be downloaded on its own, no need to download the full mod!
