### ISSUE TITLE
Old Lighting doesn't affect entities

### ISSUE THREAD

**Issue by Godlander** [sp614x/optifine#958]
When setting the Old Lighting option to On, only full blocks are affected. All entities and Tile entities appear super bright since they have no shadow compared to normal blocks.

**Comment by sp614x** [comment]
Screenshot with and withoud Old Lighting?

**Comment by Godlander** [comment]
Vanilla picture with resourcepack
![2017-10-24_16 51 21](https://user-images.githubusercontent.com/16228717/31973602-c6a18012-b8db-11e7-9eac-07006c08383c.png)

Shaders on, Old Lighting off
![2017-10-24_16 51 43](https://user-images.githubusercontent.com/16228717/31973622-dfe5be30-b8db-11e7-9674-f4ac9ce97046.png)

Shaders on, Old Lighting on
![2017-10-24_16 51 57](https://user-images.githubusercontent.com/16228717/31973642-fda2be32-b8db-11e7-8c2f-580f7654a4d7.png)

**Comment by sp614x** [comment]
Old Lighting affects only the fake lighting which is baked in the terrain vertex data.
The entity lighting is computed on the fly by the shaders or by the fixed function pipeline.
You can add a program `gbuffers_entities` and compute the entity lighting in another way.
