### ISSUE TITLE
[Suggestion] Secondary overworld lightmap exclusively for weather

### ISSUE THREAD

**Issue by realjackasterisk** [sp614x/optifine#963]
I've been using custom lightmaps ever since I first started making my resource pack. It's absolutely fantastic, it's like budget shaders. There's only been one consistent issue with them: Weather. Custom lightmaps work fine until it starts raining or snowing. Once the weather starts, the lighting has to get slightly darker, so it adjusts according to the lightmap. But the lightmap was designed mostly for sunny days, so it just gets darker as if the sun is setting. (more orange/red even though its all gray and cloudy in the sky) It gets especially worse when it starts raining while the sun is actually going down.

See, this works fine for vanilla, as it uses near-grayscale lighting. (I assume) However, for custom lightmaps that generally use real colors, this isn't great. It's a huge pain trying to balance these to work for both sunny and rainy weather, while still trying to look nice.

I suggest adding another lightmap that's ONLY ever used for weather, completely separate from the overworld lightmap. To provide some backwards-compatibility, I also suggest making this additional lightmap optional. So, if it's not included in the lightmaps folder, Optifine could just read from the overworld lightmap as it already does.

**Comment by sp614x** [comment]
Would a "thunder" lightmap also be useful, similar to custom sky? 
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/sky.properties#L119

**Comment by DataCrusader** [comment]
Not OP, but a rain lightmap, a thunderstorm lightmap, and maybe even a snow lightmap would definitely be useful.

**Comment by sp614x** [comment]
Snow and rain are the same. It depends on the current biome if rain or snow will be shown.
On the border between biomes it is possible to see rain and snow at the same time.

**Comment by realjackasterisk** [comment]
A thunder lightmap would be nice. More customization options are always a big plus in my book.

**Comment by sp614x** [comment]
Updated preview C7 for 1.12.2
- added rain and thunder palettes
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/custom_lightmaps.txt#L34

**Comment by realjackasterisk** [comment]
Damn, that was fast. Just tried it, it works exactly as I wanted. Thanks!
