### ISSUE TITLE
[Question] Minecraft 1.13

### ISSUE THREAD

**Issue by nicuch** [sp614x/optifine#964]
So with the first snapshot for 1.13, they updated LWJGL to latest version.
Will Optifine still work on 1.13? (And maybe added new features and improvements?

**Comment by xCuri0** [comment]
@nicuch I guess it will work if Mojang doesn't change the render code since OptiFine changes the rendering which isn't affected by the LWJGL version.If the rendering code is rewritten (likely as they hired a new device to do it) then OptiFine will have to be rewritten too.

**Comment by sp614x** [comment]
Most probably OptiFine wil be ported to 1.13 like it was with all previous versions.
The new LWJGL library may allow new features to be added. Especially for shaders or for performance optimizations.
