### ISSUE TITLE
[Suggestion] Use links as a texture | use variables in textures

### ISSUE THREAD

**Issue by VexIsRed** [sp614x/optifine#966]
so, for example, you might have:
nbt.display.name=Henry
texture={nbt.display.name}
this will use a texture named Henry if there is one.
nbt.display.name={Notch:name}
texture=https://minecraftskinstealer.net/{name}
this will use the URL as a texture, and it will be notched skin provided if the link is valid

i don't think the variables should be called what I called it but none the less

nbt.display.name= Letter to {*:name}
texture=https://minecraftskinstealer.net/{name}

{} would represent a variable
on the right would be the name of the variable

**Comment by sp614x** [comment]
Is this request for CIT or something else?
Dynamic textures in CIT are not really possible. On startup the game has to load all possible block and item textures and pack them in a texture atlas which has a limited size.

**Comment by KaiAF** [comment]
Closing this as there has been no response from the author. And it's not currently possible.
