### ISSUE TITLE
Custom parrot texture doesn't appear when on shoulder.

### ISSUE THREAD

**Issue by sixfootblue** [sp614x/optifine#967]
Hello!

I created a custom texture for when the blue_yellow parrot is given a specific name. The parrot mob shows the proper texture when on the ground, but the texture disappears once the parrot is on my shoulder. Is it possible to fix this, or is the shoulder parrot handled differently than the mob itself?

https://i.gyazo.com/97bfbc4f195097fe52bbff966d1e267f.png

**Comment by sp614x** [comment]
The parrot on shoulder is rendered as a part of the player model, not as a standalone entity. 
A special hack will be needed to make it work with Random Mobs.

**Comment by sp614x** [comment]
Updated preview C8 for 1.12.2
- fixed parrot on shoulder with andom mobs
