### ISSUE TITLE
CTM Glitchy top texture

### ISSUE THREAD

**Issue by dallin1016** [sp614x/optifine#969]
I'm very new to CTM, so I am sorry if this has already been answered/if it's just me doing something wrong.

So I am trying to make a ctm texture with the compact method, I made every tile and the properties file, but when i start placing the blocks next to each other in game, this happens:

https://imgur.com/HsK9XpB

It adds an elongated version of one of the tiles on top, and it glitches with the actual textures, which work properly. 

I am unsure what is happening, so, how can i fix this? Again I am sorry if this has been answered before.

EDIT: If you need any info/the pack itself, let me know :)

**Comment by realjackasterisk** [comment]
I had this happen to me before, it was really odd. I didn't know how to fix it so I just ended up scrapping it entirely.

**Comment by MisterQuiggly** [comment]
When I use CTM Compact on glass panes, part of the top texture spreads diagonally off the texture when viewed from the top. I don't know what block this is but it may have to do with some kind of model applied to the block? Could you say what block it is?

**Comment by dallin1016** [comment]
I just put it on stone to test it, so there really shouldn't be any issue in terms of the block's model.

**Comment by sp614x** [comment]
Link to resource pack?

**Comment by dallin1016** [comment]
https://www.dropbox.com/s/b6ll69zgdcopbyq/Undertale%20Map.zip?dl=0

**Comment by sp614x** [comment]
There is a conflict between the compact_ctm and the option "Alternate Blocks".
By default vanilla uses alternate models for some blocks (grass, sand, stone) and this breaks the ctm_compact.
To fix it either disable "Video Settings -> Details -> Alternate Blocks" or use ctm_compact with another block which does not have alternate models.

**Comment by dallin1016** [comment]
Ah, Okay. Thank you!

**Comment by sp614x** [comment]
You can also change the stone block model to be normal cube, this should fix the compact CTM.
