### ISSUE TITLE
1.12.2 Crash on chunk load

### ISSUE THREAD

**Issue by MortisAeternalis** [sp614x/optifine#973]
Only run into this issue with Optifine added, assuming it's probably a Chisel incompatibility, though not entirely sure on that; also, yes I know my hardware is insanely out of date, can't afford anything newer. The server continues to run, but any and all clients that connect crash on "chunk load", so not entirely sure what's going on. Last time I tried this with 1.10.2 and it was clearly a Chisel incompatibility since the phrase "chisel:extramarble" was in it, though I can't tell what it is this time.

Forge v1.12.2-14.23.0.2503
Optifine C6 and/or C7 since I tried the newer version to see if that did anything

[crash-2017-10-24_22.56.02-client.txt](https://pastebin.com/XQSEyr1E)

**Comment by sp614x** [comment]
Probably a conflict with one of the installed mods.
To fix it disable Anisotropic Filtering and Antialiasing.
