### ISSUE TITLE
Allow custom rebinds

### ISSUE THREAD

**Issue by Strum355** [sp614x/optifine#974]
F3+R is incredibly inconvenient on my keyboard (60% size). Can we have a way to rebind them please

**Comment by sp614x** [comment]
The F3+R is not configurable, exactly like all other F3 key combos.

**Comment by DethRaid** [comment]
Alternately, make reloading shaders a chat command like `\reloadShaders`

**Comment by Strum355** [comment]
commands work, else some ~~hardcoded~~ alternative? :)

**Comment by sp614x** [comment]
Using a commands is even harder. 
Commands are executed on the server, reloading shaders is a client functionality.

**Comment by xCuri0** [comment]
@sp614x I have seen client mode which are configured by commanda

**Comment by Strum355** [comment]
any updates?

**Comment by Strum355** [comment]
I believe this was added as a command so im closing this
