### ISSUE TITLE
[Suggestion] Allow LocName in cit

### ISSUE THREAD

**Issue by VexIsRed** [sp614x/optifine#975]
so we can have custom items without them showing names in item frames also being able to rename it in an anvil without it loosing texture

**Comment by sp614x** [comment]
Wat is LocName?
Currently the only way to set an item name is to use anvil or command and this custom name is shown as the item name.

**Comment by Builderb0y** [comment]
LocName is an NBT tag found under (main tag) > display > LocName. https://minecraft.gamepedia.com/Player.dat_format#Display_Properties

**Comment by Jiingy** [comment]
LocName has been removed as of [18w01a](https://minecraft.fandom.com/wiki/Java_Edition_18w01a)
