### ISSUE TITLE
Anisotropic filtering halves framerate

### ISSUE THREAD

**Issue by Nico-0** [sp614x/optifine#976]
Good morning
Anisotropic / AA filtering causes me extreme fps decrease at any level, no matter if I change all the other settings. 
[Anisotropic off](https://i.imgur.com/c2XFHTb.png)
[Anisotropic 2x](https://i.imgur.com/rcH6DaN.png)
I know this changes something on the render because it makes the game not look bad when external antialiasing is enabled,
but still this is too much frames????
Also 2x anisotropic doesn't add anything to the game and yet many people may enable it

**Comment by sp614x** [comment]
Anisotropic Filtering and Antialiasing switch the renderer in a different mode which is much less efficient. The significant FPS drop is normal. There is no way to fix it for now.
