### ISSUE TITLE
Connected textures don't work outside of vanilla bounds

### ISSUE THREAD

**Issue by BaccarWozat** [sp614x/optifine#977]
With mods with nonvanilla heights such as Cubic Chunks [(builds)](http://forkie.me/job/Cubic%20Chunks%20Related%20Jobs/job/Cubic%20Chunks%201.12-1.12.2/) [(MC Forum)](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2792887-cubic-chunks-mod-almost-infinite-world-height-and) , connected textures do not work at Y<0 or Y>1024 but do work at other heights.

Using Forge 2515, Optifine_1.12.2_HD_U_C6, Cubic Chunks build 775, and Conquest resource pack.

At Y=0 you can see the switch from connected to not:
![2017-11-05_09 15 11](https://user-images.githubusercontent.com/8357501/32416291-9f47a430-c20c-11e7-8328-a53bb33fbb8f.png)

At Y=1024 the same switch:
![2017-11-05_09 32 33](https://user-images.githubusercontent.com/8357501/32416297-bbb46da6-c20c-11e7-9c0d-0cc0535520f8.png)

The "Optifine required" texture appears even with Connected Textures set to Fancy.
![2017-11-05_09 18 31](https://user-images.githubusercontent.com/8357501/32416315-fb20a496-c20c-11e7-9a95-71bd835d9ac7.png)

**Comment by BaccarWozat** [comment]
I've been asked to make a clearer image of the transition at Y=0.
![2017-11-05_09 52 35](https://user-images.githubusercontent.com/8357501/32416473-216165da-c20f-11e7-8b0f-c25927a3c26d.png)

**Comment by BaccarWozat** [comment]
Works now in HD_U_C7_pre. Thanks!

**Comment by sp614x** [comment]
Probably a side effect of fixing the "heights" configuration.
