### ISSUE TITLE
Custom armor in texture pack not showing on other players in multiplayer.

### ISSUE THREAD

**Issue by ColinAV516** [sp614x/optifine#978]
I am using OptiFine 1.12.2 HD U C6 on a multiplayer server, and my custom armor texture only shows on me and not other players. The custom armor activates while armor has the protection enchantment level. Is this possible to be fixed?

**Comment by ColinAV516** [comment]
It appears to be the same with items

**Comment by mindforger** [comment]
did you config your server properly to provide the resource pack? did the others activate the server resourcepack?

**Comment by ColinAV516** [comment]
I don't mean it as in that they would have the resource pack. I mean as in if I look at someone who has the protection enchantment on their armor, the texture of their armor doesn't change, but mine does if I do.

**Comment by ColinAV516** [comment]
I noticed it works properly on a server I was playing on that only accepted one version, compared to hypixel which I was playing on earlier.

**Comment by sp614x** [comment]
Most probably Hypixel does not send the information about the armor enchantments to the client.
Big servers use customized software which sends to the client only the needed information. The armor enchantment is not required for the game functionality so it can be skipped. The weapon hit effect is calculated on the server and it can account for the enchanted armor.
