### ISSUE TITLE
Spidereyes overlay glitching

### ISSUE THREAD

**Issue by Triliton** [sp614x/optifine#979]
It seems like there is an issue with Spider eyes overlay in the shaders.
Not any particular, but ive tested 4 different shaders, and all have the same outcome.

The issue is as follows:

https://imgur.com/mj9okW0

The eyes work, but the texture glitches/blinks and mostly render the spiders/enderman black.

I have tried following versions and optifine:

1.10.2 HD U E3

1.12 HD U C5

1.12.2 HD U C6

I have updated my drivers, but the issue seems to be for other gpus as well and not only
for the 960 series.

**Comment by sp614x** [comment]
The programs `gbuffers_entity` and `gbuffers_spidereyes` have to use identical transforms otherwise the eye overlway will have z-fighting with the main texture.
If the spiders/endermen are black, then the transparency of the eye overlay is not correctly processed by the shaders.
