### ISSUE TITLE
Shaders settings tooltips

### ISSUE THREAD

**Issue by Jerozgen** [sp614x/optifine#980]
Add tooltips for the shaders settings ("Antialiasing", "Normal Map", etc.)! Some players don't know what this settings do.

**Comment by sp614x** [comment]
Updated preview C7 for 1.12.2
- added shaders options tooltips

![image](https://user-images.githubusercontent.com/16635441/33272967-23016262-d38c-11e7-9620-ce6ca440ba69.png)
