### ISSUE TITLE
[Random Mobs] Name condition isn't working?

### ISSUE THREAD

**Issue by Jwguy0** [sp614x/optifine#981]
Using two evokers, and a modified .png file for the texture, I'm aiming to have one evoker named "Moriarty" qualify to change to a different texture while other Evokers do not.

The evoker.properties file is written as such:
`skins.1=1`
`name.1=!pattern:Moriarty`
`skins.2=2`
`name.2=pattern:Moriarty`

In this case, both evokers, standing side by side, do not change their skin. If I invert the <n> values (making rule 2, rule 1, and rule 1, rule 2), the opposite is true: Both change their skin to the evoker2.png stored in the same folder as the evoker.properties file.

It doesn't appear that the naming condition for mob skins is working. Unless there is some other condition required to make it work that isn't listed in the examples on mob.properties:

https://github.com/sp614x/optifine/blob/4547a72e98edc9bb6f93d704fc50c83fed02e4e5/OptiFineDoc/doc/mob.properties#L104

**Comment by sp614x** [comment]
Make sure to use latest preview C7 for 1.12.2.

**Comment by Jwguy0** [comment]
Ah, should have figured that. You're absolutely right; I must have forgotten how relatively new that was.

False alarm. My bad.
