### ISSUE TITLE
CTM matchTiles vs matchBlocks priority issue

### ISSUE THREAD

**Issue by Monsterfisch** [sp614x/optifine#986]
matchTiles always overwrites the matchBlocks method so its impossible to combine the two in order to use matchTile s for the base of the block/material and use matchBlocks for variations (other blockmodels of the same material/block) 

for example we have a cobblestone base that gets applied via matchTiles I cannot in the current state use matchBlocks to add variations like a different top and side texture for the stair variant  it will always get overwritten by matchTiles at the moment. 

if we could get that loading priority order reversed or a method that allows us to target blocks specifically before matchTiles making the resourcepacks would be much more efficient. since we dont have to use matchblock for all the different variations.

**Comment by sp614x** [comment]
It shoud work if the `matchBlocks` properties also contain a `matchTiles` check.

doubleslab.properties
```
matchBlocks=125
matchTiles=planks_acacia
tiles=1-4 
metadata=4 
method=repeat 
height=2 
width=2 
weight=11 
```
zacacia.properies
```
matchTiles=planks_acacia
tiles=5 
method=random 
faces=top 
weight=11 
```

**Comment by sp614x** [comment]
For performance reasons CTM uses shortcuts by tile ID and by block ID. 
The tile related properties are checked first and then the block releated.
Adding `matchTiles` to the block properties marks it as tile related so it gets checked together with rest of the tile related properties.

**Comment by Monsterfisch** [comment]
tested and confirmed thanks glad it works this way and thanks
