### ISSUE TITLE
I tried to play 1.8.9 with shaders and then this happened...

### ISSUE THREAD

**Issue by Cogr6260** [sp614x/optifine#987]
![glitch](https://user-images.githubusercontent.com/28227235/32681438-25a5bff4-c635-11e7-961c-a75802485a68.png)
![glitch 2](https://user-images.githubusercontent.com/28227235/32681442-2be40e34-c635-11e7-81e3-e3ea65ca6463.png)
![glitch 3](https://user-images.githubusercontent.com/28227235/32681449-31337906-c635-11e7-8ee7-65cf0e2771f1.png)
The first one is shaders with item in hand for glass
The second one it shaders with item in hand for water
The third one is shaders with no item in hand

**Comment by sp614x** [comment]
This looks like a conflict with one of the installed mod.
You can try with without mods or with less mods installed.
Especially the 5zig mod is known to modify the OptiFine classes.

**Comment by Cogr6260** [comment]
I have already done a mod check removing 1 mod each time. running it, then
it still happens.

**Comment by sp614x** [comment]
Does it happen with only OptiFine installed?

**Comment by Cogr6260** [comment]
Ok. So. It only happens when I have a certain mod installed. (I have no
clue which one.) I will update every mod I have then I will report back.

**Comment by Cogr6260** [comment]
https://imgur.com/a/k3SL6  this is my mods. if anyone wants to check them
for non-updated or if they don't work together please tell me

On Mon, Nov 13, 2017 at 8:44 PM, Colin Green <colin.jonathan.green@gmail.com
> wrote:

> Ok. So. It only happens when I have a certain mod installed. (I have no
> clue which one.) I will update every mod I have then I will report back.
>

**Comment by sp614x** [comment]
The following mods may be thep roblem:
- 5zig
- Better Foliage
- Replay Mod
