### ISSUE TITLE
More flexible DRAWBUFFERS comment parsing.

### ISSUE THREAD

**Issue by jcm2606** [sp614x/optifine#989]
I think it'd be a good idea to rewrite how Optifine parses the DRAWBUFFERS comment, to allow the syntax to be more flexible.

My current understanding of how it is parsed, is Optifine specifically looks for it in the format of `/* DRAWBUFFERS:________ */`. Instead, I suggest that Optifine just looks for `DRAWBUFFERS:` alone, making the specific format irrelevant, so long as the comment contains `DRAWBUFFERS:`.

Additionally, you could further generalise it by looking for `DRAWBUFFERS` and `:` individually, and if a line contains both of these substrings, trim all whitespace and parse the comment. This would further improve flexibility, perhaps allowing shaders to roll the DRAWBUFFERS comment into another comment containing other options Optifine parses, for instance:

```glsl
/*
   const bool colortex0MipmapEnabled = true;
   const bool colortex3MipmapEnabled = true;

   const bool colortex5Clear = false;

   DRAWBUFFERS: 01
*/
```

**Comment by sp614x** [comment]
Looking only for `DRAWBUFFERS:` and ignoring the text around it could easily make a wrong match.
Relaxing the check to have optional comment start/end and flexible whitespace is realistic. This would allow the DRAWBUFFERS to be packed in a block comment with the rest of the configurations.

**Comment by sp614x** [comment]
With the relaxed check this should work:
```
  DRAWBUFFERS:  03
```
and this should not work:
```
// Use DRAWBUFFERS:03 for water shadow in composite2
```

**Comment by sp614x** [comment]
A singe line comment could also be accepted:
```
// DRAWBUFFERS: 03
```

**Comment by sp614x** [comment]
Updated preview C7 for 1.12.2
- relaxed check for DRAWBUFFERS, SHADOWRES, etc

Recognized:
```
 /*   DRAWBUFFERS:   03 */
  // DRAWBUFFERS:03
    DRAWBUFFERS:  03
```
Not recognized:
```
// Use RAWBUFFERS:03 for water shadow
DRAWBUFFERS:  03 - for testing
Don't set DRAWBUFFERS:  03
```
