### ISSUE TITLE
[1.9] Crash when loaded using Forge

### ISSUE THREAD

**Issue by johnlage** [sp614x/optifine#99]
On certain servers which give/take away a shield to imitate blocking with a sword on 1.8, Optifine crashes, but only when loaded with Forge. I tested this using Forge build 1889 with no mods other than Optifine on the hypixel.net server. To reproduce, join a game (in 1.9) which uses swords (I tested using SkyWars) and right click with a sword in your hand. It may take a couple right clicks to crash the game.
Before build 1889, Forge (without any mods) crashed with the same error.
Forge Bug Report: http://www.minecraftforge.net/forum/index.php/topic,38684.msg203527.html
fml-client-latest: http://pastebin.com/VBQ9U5Dk

**Comment by sp614x** [comment]
This should be fixed in latest preview B3 for 1.9.

**Comment by johnlage** [comment]
I am confirming that the latest preview fixed the issue. Thanks!
