### ISSUE TITLE
[Suggestion] Allow the mushrooms on the Mooshroom's back to be changed

### ISSUE THREAD

**Issue by DataCrusader** [sp614x/optifine#992]
Right now, they are completely unable to be altered in anyway besides changing the red mushroom item's texture. I would suggest the Mooshroom's back mushrooms to have a place in the Mooshroom texture, and altering that would change the mushrooms. Right now doing CEM and random mob textures for Mooshrooms is pointless because the mushrooms on the back will stay no matter what. Being able to change or remove the mushrooms on the Mooshroom would be pretty useful imo.

**Comment by sp614x** [comment]
The Mooshroom texture does not have free space for a mushrooom (16x16).

**Comment by DataCrusader** [comment]
Well, that was just a suggestion for a way to change it. How about a Mooshroom-specific thing for the random mobs properties file that lets you direct to a specific texture to replace the mushroom texture on the Mooshroom for each skin?

**Comment by sp614x** [comment]
I am experimenting with a new model for the mushrooms which uses a separate texture.
So far it seems to work. 

![image](https://user-images.githubusercontent.com/16635441/32973559-6a3d0258-cbf8-11e7-8aa4-1275dadf4ebe.png)

**Comment by sp614x** [comment]
OptiFine 1.12.2_HD_U_C7_pre
 - added alternative Mooshroom mushroom model, uses "assets/minecraft/textures/entity/cow/mushroom_red.png"
