### ISSUE TITLE
Linked textures for double tall plants not working

### ISSUE THREAD

**Issue by Blockstate** [sp614x/optifine#995]
I might be missing something, but I followed the documentation for linked textures and they don't seem to be working.
![2017-11-13_17 51 10](https://user-images.githubusercontent.com/11284043/32788895-4b2d5174-c90f-11e7-9957-d29909fc1263.png)

My property files are as follows:

double_plant_fern_bottom.properties has the following...
`tiles=0 1
method=random
weights=50 50
linked=true`

double_plant_fern_top.properties has the following...
`tiles=2 3
method=random
weights=50 50
linked=true`

**Comment by sp614x** [comment]
Updated preview C7 for 1.12.2
- added CTM property "linked" for random double plants and doors

**Comment by sp614x** [comment]
Extended to support higher plants
![image](https://user-images.githubusercontent.com/16635441/33087834-003ec944-ceec-11e7-8b41-5983a081d373.png)
