### ISSUE TITLE
Issues so far with Emissive Textures

### ISSUE THREAD

**Issue by DataCrusader** [sp614x/optifine#996]
Doesn't work for torches at all, not sure if this expands to similar blocks
Doesn't seem to work for textures that make use of custom non-vanilla textures, for example: giving the lit redstone ore block (which I gave its own texture) its own emissive overlay doesn't work
Animated textures do appear to work on full blocks so far
Doesn't work with overlays, not sure how far into CTM it doesn't work

**Comment by sp614x** [comment]
Torches are permanently lit, how should it work for them?

**Comment by sp614x** [comment]
Updated preview C7 for 1.12.2
 - added emissive overlays for items

**Comment by DataCrusader** [comment]
sorry, I meant redstone torches @sp614x, my bad.

**Comment by sp614x** [comment]
Should be fixed now.
