### ISSUE TITLE
Opti (Version X) 1.12.X Render Entitie Issue

### ISSUE THREAD

**Issue by NintendoBest** [sp614x/optifine#999]
While playing Cubecraft's SG there is armor stand acting like corpse, they started to become invisible sinse Optifine's 1.12.X. any 'null' character are causing entitie to become invisible after giving them a null character in their name. Someone found the reason of why this is happening, here is the detail below.
Someone sent me this:
https://www.youtube.com/watch?v=B0373XVexmw

> «Since then I looked into that issue and it seems that it is caused by all corpses having the null character as their name».

I hope this will be fix has soon has possible.
And thank you for your amazing MODs/Work!!!
Affected version: Any Optifine version above 1.12 (C7 preview as-well)

**Comment by RasmusAntons** [comment]
In the video I say something about entity names, but I actually only saw it happen with player names. As far as I know the corpses on the server are not armor stands but fake players that are sleeping.

**Comment by NintendoBest** [comment]
> In the video I say something about entity names, but I actually only saw it happen with player names. As far as I know the corpses on the server are not armor stands but fake players that are sleeping.
Trust me, they are armor stand.

**Comment by NintendoBest** [comment]
@sp614x is this will be fixed soon... or on you're to do list?

**Comment by sp614x** [comment]
Updated preview C7 for 1.12.2
- fixed crash when username contains ASCII 0 character (#999)

**Comment by NintendoBest** [comment]
*Perfectly fixed!
